### PR TITLE
dev-java/netty-* Version bump to latest release

### PR DESCRIPTION
**Pull request by wltjr**
@gentoo/java Version bump to latest release, removed previous unstable version. Ebuilds are already EAPI=5, so I did not do any review, assuming who ever did the EAPI bump addressed any ebuild semantics. I was unable to bump netty-handler due to it depending on parts of Jetty not in tree. Have to look into packaging Jetty not only for netty-handler but other future packages such as Zookeeper, and likely others.

### CODE REVIEW

**Comment by monsieurp** [comment]
I'll take it :+1:

**Comment by monsieurp** [comment]
Merged! :+1:

**Comment by hasufell** [comment]
something weird happened here... we have a merge commit, but the commits from @wltjr were rewritten, possibly removing user GPG signatures
```
Author: William L. Thomson Jr <wlt@o-sinc.com>  2015-10-12 23:23:25
Committer: Patrice Clement <monsieurp@gentoo.org>  2015-10-13 13:56:53
```
do you remember how you merged this, I mean which command?

**Comment by monsieurp** [comment]
git merge --no-ff <commit id>
NB: I rebased and reworded some of his commits.. maybe that explains why?

**Comment by hasufell** [comment]
> I rebased and reworded some of his commits.

well yeah, that should be avoided, that's his turn to fix ;)

**Pull request closed without merging**
