### PR TITLE
mail-filter/amavisd-new: Depend on app-arch/arj

### PR DESCRIPTION
**Pull request by rseichter**
Depend on app-arch/arj instead of app-arch/unarj because of licensing.

### CODE REVIEW

**Comment by chewi** [comment]
Great but you'll need to address the older versions if we want to last-rite unarj. I know this is a stable package but I don't think pushing this change straight-to-stable would be too controversial.

**Comment by rseichter** [comment]
@chewi I have added a commit that removes the outdated ebuilds. As for going straight to stable, I am not so sure. If you think it is really OK, you can make this change before committing the changes, correct?

**Comment by chewi** [comment]
Turns out we can't do that yet because arj isn't stable on ppc64. I've pushed this now so I'll get that sorted and stabilise this afterwards.

**Comment by rseichter** [comment]
Thanks for checking, and for processing the merge request.

**Pull request closed without merging**
