### PR TITLE
app-office/ledger: Bump version to 3.2.1

### PR DESCRIPTION
**Pull request by d-e-s-o**
3.2.0 has a bad performance regression [0] and should almost certainly
not be the sole version available in the 3.2* realm. This change adds an
ebuild for 3.2.1.

[0] https://github.com/ledger/ledger/issues/1946

Signed-off-by: Daniel Müller <deso@posteo.net>

### CODE REVIEW

**Comment by d-e-s-o** [comment]
Can this pull request be merged?

**Comment by d-e-s-o** [comment]
^ @a17r

**Comment by d-e-s-o** [comment]
ping

**Comment by a17r** [comment]
Just saw this now. Please note that I do not maintain this package, and as @gentoo-bot said:

> **app-office/ledger**: ~stasibear~
> 
> At least one of the listed packages is maintained entirely by non-GitHub developers!

**Pull request closed without merging**
