### PR TITLE
x11-misc/xbindkeys: Fix key mask patch

### PR DESCRIPTION
**Pull request by aclex**
Change logical to bitwise AND while applying the mask on the key value in the applied patch. The patch was added in the request #12938, but the previous version of it occasionally wasn't correct.

### CODE REVIEW

**Comment by aclex** [comment]
@heroxbd could you please take a look at this as well? This is actually a follow-up for #12938, where wrong patch accidentally slipped to commit. Thanks in advance!

**Review by jkroonza — COMMENTED** [review]
What's the meaning of bit 13 & 14?

In the patch ~(numlock_mask | ... | 0x3000)

Would be clearer and less confusing, but even better would be if there was a constant similar to number_mask indicating *what* were being masked.

Anyway, GLEP 61 (Bug: or Closes: header in commit).

If this is the patch that was merged upstream, has a new version been released upstream yet to which we can rather version bump?

**Review by jkroonza — COMMENTED** [review]
Already in 1.8.7 - recommend we rather stable that version.

**Comment by thesamesam** [comment]
Closing as per @jkroonza's suggestion. Let us know if it's still applicable.

**Pull request closed without merging**
