### PR TITLE
sci-libs/gdal: version bump 3.0.2

### PR DESCRIPTION
**Pull request by cjmayo**
Get bash completion working
Partially tested with USE="java", in that without emake, emake install and dev-java/ant no bindings were getting installed. dev-java/ant did mean dropping arm and arm64 for repoman to allow the commit.

```diff
--- gdal-2.4.1-r2.ebuild
+++ gdal-3.0.2.ebuild
@@ -6,7 +6,7 @@
 GENTOO_DEPEND_ON_PERL="no"
 PYTHON_COMPAT=( python3_{5,6,7,8} )
 DISTUTILS_OPTIONAL=1
-inherit autotools perl-module distutils-r1 flag-o-matic java-pkg-opt-2 toolchain-funcs
+inherit autotools bash-completion-r1 perl-module distutils-r1 flag-o-matic java-pkg-opt-2 toolchain-funcs
 
 DESCRIPTION="Translator library for raster geospatial data formats (includes OGR support)"
 HOMEPAGE="https://gdal.org/"
@@ -14,7 +14,7 @@
 
 SLOT="0/2.3"
 LICENSE="BSD Info-ZIP MIT"
-KEYWORDS="~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x86-macos"
+KEYWORDS="~amd64 ~ia64 ~ppc ~ppc64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x86-macos"
 IUSE="armadillo +aux_xml curl debug doc fits geos gif gml hdf5 java jpeg jpeg2k lzma mdb mysql netcdf odbc ogdi opencl oracle pdf perl png postgres python spatialite sqlite threads webp xls zstd"
 
 REQUIRED_USE="
@@ -24,8 +24,12 @@
 "
 
 BDEPEND="
+	virtual/pkgconfig
 	doc? ( app-doc/doxygen )
-	java? ( >=virtual/jdk-1.7:* )
+	java? (
+		dev-java/ant
+		>=virtual/jdk-1.7:*
+	)
 	perl? ( dev-lang/swig:0 )
 	python? (
 		dev-lang/swig:0
@@ -38,12 +42,13 @@
 	dev-libs/libpcre
 	dev-libs/libxml2:=
 	media-libs/tiff:0=
-	sci-libs/libgeotiff:=
+	>=sci-libs/libgeotiff-1.5.1-r1:=
+	>=sci-libs/proj-6.0.0
 	sys-libs/zlib:=[minizip(+)]
 	armadillo? ( sci-libs/armadillo:=[lapack] )
 	curl? ( net-misc/curl )
 	fits? ( sci-libs/cfitsio:= )
-	geos? ( >=sci-libs/geos-2.2.1 )
+	geos? ( >=sci-libs/geos-3.8.0 )
 	gif? ( media-libs/giflib:= )
 	gml? ( >=dev-libs/xerces-c-3.1 )
 	hdf5? ( >=sci-libs/hdf5-1.6.4:=[szip] )
@@ -79,12 +84,8 @@
 
 PATCHES=(
 	"${FILESDIR}/${PN}-2.2.3-soname.patch"
-	"${FILESDIR}/${PN}-2.2.3-bashcomp-path.patch" # bug 641866
+	"${FILESDIR}/${PN}-3.0.2-bashcomp-path.patch" # bug 641866
 	"${FILESDIR}/${PN}-2.3.0-curl.patch" # bug 659840
-	"${FILESDIR}/${P}-poppler-0.75.patch"
-	"${FILESDIR}/${P}-poppler-0.76.patch"
-	"${FILESDIR}/${P}-swig-4.patch" # bug 689110
-	"${FILESDIR}/${P}-poppler-0.82.patch"
 )
 
 src_prepare() {
@@ -137,20 +138,22 @@
 		# podofo - we use poppler instead they are exclusive for each other
 		# tiff is a hard dep
 		--includedir="${EPREFIX}"/usr/include/${PN}
+		--disable-lto
+		--disable-static
+		--disable-driver-bsb
+		--disable-driver-mrf
 		--disable-pdf-plugin
-		--disable-static
 		--enable-shared
+		--enable-driver-grib
 		--with-expat
 		--with-cryptopp=no
 		--with-geotiff
-		--with-grib
 		--with-hide-internal-symbols
 		--with-libjson-c="${EPREFIX}"/usr/
 		--with-libtiff
 		--with-libtool
 		--with-libz="${EPREFIX}"/usr/
 		--with-gnm
-		--without-bsb
 		--without-charls
 		--without-dods-root
 		--without-ecw
@@ -172,7 +175,6 @@
 		--without-mrsid
 		--without-mrsid_lidar
 		--without-msg
-		--without-mrf
 		--without-rasdaman
 		--without-rasterlite2
 		--without-pcraster
@@ -183,7 +185,6 @@
 		--without-sfcgal
 		--without-sosi
 		--without-teigha
-		--disable-lto
 		$(use_enable debug)
 		$(use_with armadillo)
 		$(use_with aux_xml pam)
@@ -193,7 +194,7 @@
 		$(use_with gif)
 		$(use_with gml xerces)
 		$(use_with hdf5)
-		$(use_with jpeg pcidsk) # pcidsk is internal, because there is no such library yreleased developer by gdal
+		$(use_with jpeg pcidsk) # pcidsk is internal, because there is no such library released developer by gdal
 		$(use_with jpeg)
 		$(use_with jpeg2k openjpeg)
 		$(use_with lzma liblzma)
@@ -257,6 +258,12 @@
 	# gdal-config needed before generating Python bindings
 	default
 
+	if use java ; then
+		pushd "${S}"/swig/java > /dev/null || die
+		emake
+		popd > /dev/null || die
+	fi
+
 	if use perl ; then
 		pushd "${S}"/swig/perl > /dev/null || die
 		perl-module_src_configure
@@ -276,6 +283,12 @@
 }
 
 src_install() {
+	if use java ; then
+		pushd "${S}"/swig/java > /dev/null || die
+		emake install
+		popd > /dev/null || die
+	fi
+
 	if use perl ; then
 		pushd "${S}"/swig/perl > /dev/null || die
 		myinst=( DESTDIR="${D}" )
@@ -305,11 +318,21 @@
 		distutils-r1_src_install
 		popd > /dev/null || die
 
-		newdoc swig/python/README.txt README-python.txt
+		newdoc swig/python/README.rst README-python.rst
 
 		insinto /usr/share/${PN}/samples
-		doins -r swig/python/samples/
-	fi
+		doins -r swig/python/samples/.
+	fi
+
+	for cmd in gdal2tiles.py gdal2xyz.py gdaladdo gdalbuildvrt gdal_calc.py \
+			gdalchksum.py gdalcompare.py gdal-config gdal_contour gdaldem \
+			gdal_edit.py gdalenhance gdal_fillnodata.py gdal_grid gdalident.py \
+			gdalimport.py gdallocationinfo gdalmanage gdal_merge.py gdalmove.py \
+			gdal_polygonize.py gdal_proximity.py gdal_rasterize gdal_retile.py \
+			gdalserver gdal_sieve.py gdalsrsinfo gdaltindex gdaltransform \
+			gdal_translate gdalwarp ogr2ogr ogrinfo ogrlineref ogrmerge.py ogrtindex; do
+		bashcomp_alias gdalinfo $cmd
+	done
 
 	doman "${S}"/man/man*/*
 	find "${D}" -name '*.la' -type f -delete || die
```

### CODE REVIEW

**Comment by a17r** [comment]
lgtm, also fixes https://bugs.gentoo.org/703790 according to release notes. @Amynka?

**Comment by cjmayo** [comment]
I'm afraid it's turning out to be a bit more complicated but I think I am getting there. I'm sending as much upstream as I can first.

I think https://github.com/OSGeo/gdal/commit/1f8fa16f58cfe0364099ddad0e1d86522d8de41a is backported as https://github.com/OSGeo/gdal/commit/852d1d29fa38779aa0557d81f05754e371fef62e
and https://github.com/OSGeo/gdal/commit/7318576fc7037412b755f038f8148f2d299587 as https://github.com/OSGeo/gdal/commit/6cc6d4dd9d331d4ac8f160285cfa12c3e0de8843

**Comment by a17r** [comment]
> I will include.

As said, both patches are already in ´FILESDIR`, you should be able to simply reuse them as they applied to 2.4.1 without other changes.

**Comment by cjmayo** [comment]
Updated with all new diff below. Two patches upstreamed to sort out the installation data directory and bash completion. Bash completion will now always be installed using the eclass to report the completions directory instead of the automagic dependency from previous gdal ebuilds.

2.4.1 Poppler 0.8.3 patches included.

I have tested the USE="java" since I realised you only need ant-core. A manual doins of the jar file here, still more work to get make install working for Java. I think the ebuild is OK with this, at least it is a partial improvement.

Most of the sed'ing gone from src_prepare:
swig/python/GNUmakefile fixed in https://github.com/OSGeo/gdal/commit/84cbef8b791e59fa3c967ec8321ccbda0aca4b50 and https://github.com/OSGeo/gdal/commit/8cae2eb06969b85725acd7094e9481e32ab23b5b
FREEXL_LIBS fixed in https://github.com/OSGeo/gdal/commit/a924d8269f09c86e59ca9e0196f26f3458b43940
swig/python/setup.cfg change obsolete since https://github.com/OSGeo/gdal/commit/74f6101415415a871e

I can't see what has fixed this, but compiling fine for me without:
```sh
	sed -e "s: gdal_array.i: ../include/gdal_array.i:" \
		-i swig/python/GNUmakefile || die "sed python makefile failed"
```

Disabling perl and python configure options, we are building them ourselves. Avoid unnecessary compilation.

```diff
--- gdal-2.4.1-r2.ebuild
+++ gdal-3.0.2.ebuild
@@ -6,7 +6,7 @@
 GENTOO_DEPEND_ON_PERL="no"
 PYTHON_COMPAT=( python3_{5,6,7,8} )
 DISTUTILS_OPTIONAL=1
-inherit autotools perl-module distutils-r1 flag-o-matic java-pkg-opt-2 toolchain-funcs
+inherit autotools bash-completion-r1 perl-module distutils-r1 flag-o-matic java-pkg-opt-2 toolchain-funcs
 
 DESCRIPTION="Translator library for raster geospatial data formats (includes OGR support)"
 HOMEPAGE="https://gdal.org/"
@@ -24,8 +24,12 @@
 "
 
 BDEPEND="
+	virtual/pkgconfig
 	doc? ( app-doc/doxygen )
-	java? ( >=virtual/jdk-1.7:* )
+	java? (
+		dev-java/ant-core
+		>=virtual/jdk-1.7:*
+	)
 	perl? ( dev-lang/swig:0 )
 	python? (
 		dev-lang/swig:0
@@ -38,12 +42,13 @@
 	dev-libs/libpcre
 	dev-libs/libxml2:=
 	media-libs/tiff:0=
-	sci-libs/libgeotiff:=
+	>=sci-libs/libgeotiff-1.5.1-r1:=
+	>=sci-libs/proj-6.0.0
 	sys-libs/zlib:=[minizip(+)]
 	armadillo? ( sci-libs/armadillo:=[lapack] )
 	curl? ( net-misc/curl )
 	fits? ( sci-libs/cfitsio:= )
-	geos? ( >=sci-libs/geos-2.2.1 )
+	geos? ( >=sci-libs/geos-3.8.0 )
 	gif? ( media-libs/giflib:= )
 	gml? ( >=dev-libs/xerces-c-3.1 )
 	hdf5? ( >=sci-libs/hdf5-1.6.4:=[szip] )
@@ -79,48 +84,24 @@
 
 PATCHES=(
 	"${FILESDIR}/${PN}-2.2.3-soname.patch"
-	"${FILESDIR}/${PN}-2.2.3-bashcomp-path.patch" # bug 641866
 	"${FILESDIR}/${PN}-2.3.0-curl.patch" # bug 659840
-	"${FILESDIR}/${P}-poppler-0.75.patch"
-	"${FILESDIR}/${P}-poppler-0.76.patch"
-	"${FILESDIR}/${P}-swig-4.patch" # bug 689110
-	"${FILESDIR}/${P}-poppler-0.82.patch"
-	"${FILESDIR}"/${P}-poppler-0.83-{1,2}.patch # bug 703790
+	"${FILESDIR}"/${PN}-2.4.1-poppler-0.83-{1,2}.patch # bug 703790
+	"${FILESDIR}/${PN}-3.0.2-complete.patch"
+	"${FILESDIR}/${PN}-3.0.2-datadir.patch"
 )
 
 src_prepare() {
-	# fix datadir and docdir placement
-	sed -e "s:@datadir@:@datadir@/gdal:" \
-		-e "s:@exec_prefix@/doc:@exec_prefix@/share/doc/${PF}/html:g" \
-		-i "${S}"/GDALmake.opt.in || die
-
-	# the second sed expression should fix bug 371075
-	sed -e "s:setup.py install:setup.py install --root=\$(DESTDIR):" \
-		-e "s:--prefix=\$(DESTDIR):--prefix=:" \
-		-i "${S}"/swig/python/GNUmakefile || die
+	default
+
+	sed -e "s: /usr/: \"${EPREFIX}\"/usr/:g" \
+		-i configure.ac || die
 
 	# Fix spatialite/sqlite include issue
 	sed -e 's:spatialite/sqlite3.h:sqlite3.h:g' \
 		-i ogr/ogrsf_frmts/sqlite/ogr_sqlite.h || die
 
-	# Fix freexl configure check
-	sed -e 's:FREEXL_LIBS=missing):FREEXL_LIBS=missing,-lm):g' \
-		-i configure.ac || die
-
-	sed -e "s: /usr/: \"${EPREFIX}\"/usr/:g" \
-		-i configure.ac || die
-
 	sed -e 's:^ar:$(AR):g' \
 		-i ogr/ogrsf_frmts/sdts/install-libs.sh || die
-
-	# updated for newer swig (must specify the path to input files)
-	sed -e "s: gdal_array.i: ../include/gdal_array.i:" \
-		-e "s:\$(DESTDIR)\$(prefix):\$(DESTDIR)\$(INST_PREFIX):g" \
-		-i swig/python/GNUmakefile || die "sed python makefile failed"
-	sed -e "s:library_dirs = :library_dirs = /usr/$(get_libdir):g" \
-		-i swig/python/setup.cfg || die "sed python setup.cfg failed"
-
-	default
 
 	eautoreconf
 }
@@ -138,20 +119,23 @@
 		# podofo - we use poppler instead they are exclusive for each other
 		# tiff is a hard dep
 		--includedir="${EPREFIX}"/usr/include/${PN}
+		--disable-lto
+		--disable-static
+		--disable-driver-bsb
+		--disable-driver-mrf
 		--disable-pdf-plugin
-		--disable-static
 		--enable-shared
+		--enable-driver-grib
+		--with-bash-completion="$(get_bashcompdir)"
+		--with-cryptopp=no
 		--with-expat
-		--with-cryptopp=no
 		--with-geotiff
-		--with-grib
+		--with-gnm
 		--with-hide-internal-symbols
 		--with-libjson-c="${EPREFIX}"/usr/
 		--with-libtiff
 		--with-libtool
 		--with-libz="${EPREFIX}"/usr/
-		--with-gnm
-		--without-bsb
 		--without-charls
 		--without-dods-root
 		--without-ecw
@@ -173,18 +157,18 @@
 		--without-mrsid
 		--without-mrsid_lidar
 		--without-msg
-		--without-mrf
 		--without-rasdaman
 		--without-rasterlite2
 		--without-pcraster
 		--without-pdfium
+		--without-perl
 		--without-podofo
+		--without-python
 		--without-qhull
 		--without-sde
 		--without-sfcgal
 		--without-sosi
 		--without-teigha
-		--disable-lto
 		$(use_enable debug)
 		$(use_with armadillo)
 		$(use_with aux_xml pam)
@@ -194,7 +178,7 @@
 		$(use_with gif)
 		$(use_with gml xerces)
 		$(use_with hdf5)
-		$(use_with jpeg pcidsk) # pcidsk is internal, because there is no such library yreleased developer by gdal
+		$(use_with jpeg pcidsk) # pcidsk is internal, because there is no such library released developer by gdal
 		$(use_with jpeg)
 		$(use_with jpeg2k openjpeg)
 		$(use_with lzma liblzma)
@@ -205,10 +189,8 @@
 		$(use_with ogdi ogdi "${EPREFIX}"/usr)
 		$(use_with opencl)
 		$(use_with pdf poppler)
-		$(use_with perl)
 		$(use_with png)
 		$(use_with postgres pg)
-		$(use_with python)
 		$(use_with spatialite)
 		$(use_with sqlite sqlite3 "${EPREFIX}"/usr)
 		$(use_with threads)
@@ -258,7 +240,13 @@
 	# gdal-config needed before generating Python bindings
 	default
 
-	if use perl ; then
+	if use java; then
+		pushd "${S}"/swig/java > /dev/null || die
+		emake
+		popd > /dev/null || die
+	fi
+
+	if use perl; then
 		pushd "${S}"/swig/perl > /dev/null || die
 		perl-module_src_configure
 		perl-module_src_compile
@@ -277,26 +265,25 @@
 }
 
 src_install() {
-	if use perl ; then
+	local DOCS=( NEWS )
+	use doc && HTML_DOCS=( html/. )
+
+	default
+
+	if use java; then
+		pushd "${S}"/swig/java > /dev/null || die
+		insinto /usr/share/${PN}/java/jar
+		doins gdal.jar
+		popd > /dev/null || die
+	fi
+
+	if use perl; then
 		pushd "${S}"/swig/perl > /dev/null || die
 		myinst=( DESTDIR="${D}" )
 		perl-module_src_install
 		popd > /dev/null || die
-		sed -e 's:BINDINGS        =       \(.*\) perl:BINDINGS        =       \1:g' \
-			-i GDALmake.opt || die
-	fi
-
-	use perl && perl_delete_localpod
-
-	local DOCS=( Doxyfile HOWTO-RELEASE NEWS )
-	use doc && HTML_DOCS=( html/. )
-
-	default
-
-	python_install() {
-		distutils-r1_python_install
-		python_doscript scripts/*.py
-	}
+		perl_delete_localpod
+	fi
 
 	if use python; then
 		# Don't clash with gdal's docs
@@ -306,10 +293,10 @@
 		distutils-r1_src_install
 		popd > /dev/null || die
 
-		newdoc swig/python/README.txt README-python.txt
+		newdoc swig/python/README.rst README-python.rst
 
 		insinto /usr/share/${PN}/samples
-		doins -r swig/python/samples/
+		doins -r swig/python/samples/.
 	fi
 
 	doman "${S}"/man/man*/*
```

**Comment by cjmayo** [comment]
Updated again for the aux_xml rename.

**Comment by cjmayo** [comment]
> I can't see what has fixed this, but compiling fine for me without:
> 
> ```shell
> 	sed -e "s: gdal_array.i: ../include/gdal_array.i:" \
> 		-i swig/python/GNUmakefile || die "sed python makefile failed"
> ```

OK it silences:
`SWIG:1: Warning 125: Use of the include path to find the input file is deprecated and will not work with ccache. Please include the path when specifying the input file.`

Added back with message as comment.

**Comment by cjmayo** [comment]
Java needs swig...

**Comment by cjmayo** [comment]
I can't see why this is needed:
```sh
       # Fix spatialite/sqlite include issue
       sed -e 's:spatialite/sqlite3.h:sqlite3.h:g' \
               -i ogr/ogrsf_frmts/sqlite/ogr_sqlite.h || die
```

SPATIALITE_AMALGAMATION should not be defined. If the sed is needed it would indicate a problem that should be fixed.

**Comment by Amynka** [comment]
If its not needed lets not use it :)

**Comment by cjmayo** [comment]
Good. That's gone. I guess their must have been an issue at some point with the logic in configure.ac.

As per the new 2.4.3 I've dropped Python 3.5 and fixed the conflict with the Manifest.

**Comment by cjmayo** [comment]
Use java-pkg_dojar to install the jar file into standard Gentoo location:

```diff
@@ -271,12 +271,7 @@
 
 	default
 
-	if use java; then
-		pushd "${S}"/swig/java > /dev/null || die
-		insinto /usr/share/${PN}/java/jar
-		doins gdal.jar
-		popd > /dev/null || die
-	fi
+	use java && java-pkg_dojar "${S}"/swig/java/gdal.jar
 
 	if use perl; then
 		pushd "${S}"/swig/perl > /dev/null || die
```

**Comment by a17r** [comment]
Thanks for your great work! Small changes to follow after the merge.

**Pull request closed without merging**
