### PR TITLE
net-p2p/go-ipfs: verbump to 0.9.1

### PR DESCRIPTION
**Pull request by stkw0**
Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: David Roman <davidroman96@gmail.com>

### CODE REVIEW

**Comment by kakra** [comment]
@stkw0 Maybe remove the 0.7 version, especially since it is affected by a security issue?

**Comment by kakra** [comment]
You could then add a `Closes: https://bugs.gentoo.org/778182`

**Comment by stkw0** [comment]
sorry for the delay, will do it now

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Oh right, we can't close security bugs with commits as they need to be checked by the security team, so just reference a security bug with `Bug:` instead in future.

**Pull request closed without merging**
