### PR TITLE
app-admin/lastpass-cli version bump to 0.8.0 and metadata <bugs-to> update

### PR DESCRIPTION
**Pull request by gktrk**
Fairly straightforward bump: copied 0.7.1 ebuild and updated the copyright year in the header. Checked the diff between two tags on upstream's git repository, spotted no changes in deps.
Also added <bugs-to> tag to the metadata.

@jdhore

### CODE REVIEW

**Comment by jdhore** [comment]
LGTM. In fact, can someone give @gktrk this package for proxy maintenance if he wants it? I do not use Lastpass any longer.

**Comment by monsieurp** [comment]
yo @jdhore, thanks for signing off on the PR. I'll do the necessary deed. Cheers.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Ack. Will update the metadata on the next bump.

**Pull request merged**
