### PR TITLE
media-tv/kodi: Drop old versions

### PR DESCRIPTION
**Pull request by candrews**
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by candrews** [comment]
@fordfrog in order to drop media-tv/kodi-16* I need to drop media-libs/kodi-platform-16* and media-plugins/kodi-pvr-hts-16* which I've done in this PR. As maintainer of those packages is that okay with you?

@v00d00 as maintainer of dev-libs/libplatform, would you mind if we dropped dev-libs/libplatform-1.0.10 since nothing depends upon it any more? (I have a commit in this PR that does so)

**Comment by v00d00** [comment]
Dropping the older libplatform is fine with me 👍

**Comment by ulm** [comment]
Reopening because of https://bugs.gentoo.org/show_bug.cgi?id=621788.

**Comment by mgorny** [comment]
I don't think reopening this serves any purpose. We can discuss this on Bugzilla and/or reopen if the commits gets reverted and @candrews has a new version.

**Pull request closed without merging**
