### PR TITLE
dev-libs/glib: add v2.64.2 and extend configuration options

### PR DESCRIPTION
**Pull request by jsmolic**
Add v2.64.2 and introduce the option to disable native language support.

Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>
Signed-off-by: Luka Perkov <luka.perkov@sartura.hr>

### CODE REVIEW

**Comment by mattst88** [comment]
- We don't want IUSE=nls here. Just use `INSTALL_MASK` if you want to prevent the installation of some locales.

  - glib must always be bumped along with gdbus-codegen and glib-utils

  - I doubt the patch needs to be duplicated?

**Comment by jsmolic** [comment]
@mattst88 Thank you for the information :)\
I prepared separate pull requests for bumping `glib-utils` (https://github.com/gentoo/gentoo/pull/15462) and `gdbus-codegen` (https://github.com/gentoo/gentoo/pull/15461)

Regarding the `nls` USE flag, we thought it would be good to provide the option for users to install the package without nls support given the significant size impact of locales. We have a use-case where we would like to reduce size of installed packages where possible, hence the added option to exclude native language support.\
Kindly advise and if the `nls` USE flag can't be added here I will drop it.

**Comment by mattst88** [comment]
Yes, we definitely don't want an nls USE flag. Please see `INSTALL_MASK` in `make.conf(5)` for a way to achieve what you want.

It would be better to combine all of these merge requests, since none of them can be merged without the others. You may want to bump `dev-libs/gobject-introspection` and `dev-libs/gobject-introspection-common` at the same time.

(You can just force push to the branch to update it)

**Comment by mattst88** [comment]
Sorry, are you closing the PRs because you don't want to work on this anymore?

**Comment by jsmolic** [comment]
@mattst88 Yes, unfortunately in the meantime after making this PR we decided not to use glib for now, so that's why I closed my pull requests.

**Pull request closed without merging**
