### PR TITLE
JDK9: slot 9 for JVM ebuilds

### PR DESCRIPTION
**Pull request by labre**
This time branched from a clean master. ;)
This PR has been based on the PR #1721 from @candrews .
The symlink issue in my original PR has been magically resolved by doing that. Probably because of the env adaptation.
There still is the issue from the invalid CLASSPATH. Java9 does not seem to need it, but if you compile for 6 till 8, that could cause errors. CLASSPATH currently references files, that do not exist anymore.
Dependency wise it could be an issue, that virtual/jre depends on virtual/jre, which then currently only depends oracle-jdk-bin:9, since icedtea:9 is not ready yet. That could cause a dependency hell for users in ~arches, because all Java packages would pull it in. A mask could be advisable, but that is for you to decide.

### CODE REVIEW

**Comment by labre** [comment]
Pardon, I meant virtual/jre depends on virtual/jdk.

**Comment by labre** [comment]
There is an issue, with the nsplugin symlink in oracle-jre-bin. Fixing it. oracle-jdk-bin is not affected, so it may be possible to peek there.

**Comment by labre** [comment]
Ok, i’ve fixed it. What would be the best way to commit the fix without messing up the history? Sorry for causing 635070 by the way. I thought, it was a safe bump, so I just did the download and manifesting.

**Comment by chewi** [comment]
Learn about interactive rebases with `git rebase -i`. Then learn about auto-squashing. These are powerful tools and I use them almost every day. When you're done, do `git push --force-with-lease`.

No worries about that bug, I don't usually check the jce flag either so that would have caught me out too.

**Comment by labre** [comment]
Found a little bit more inconsistencies jdk-bin and jre-bin and fixed them. I did not list the changes in the commit message, but I could amend it, if you prefer that.

– Mostly some of the deletions tried to delete non-existent files, amongst other existing files, which did not lead to dying.
– JDK9 has introduced modules, which do reside in jmods folder. Although I could compile a one file project with it, that might not be true for others, so I include the jmods folder now. javafx use flag handling is updated to delete the javafx.* jmods.
– It also includes now a conf folder, which seems to be intended for system wide configuation. Since these are text files and users might make use of them, they get now copied too.
– The paths in 1.8 include a wildcard pattern prefix of the form jre/lib/*/. I had not deleted the wildcard part yet.
– I did not use the source flag, so I noticed just now the movement of src.zip to lib/src.zip. Javafx source is not provided anymore.
—end of fixups—
– README has moved into the legal folder along with others. The symlink in legal/ points to java.base/README, so I”m using that.
– Number of provided binaries is currently limited, so I reduced the arches.
– Updated the Oracle-BCLA-JavaSE license to the current one. Had a number of changes.

**Comment by wltjr** [comment]
Please add a package.mask to this so it can be added to tree. Till it has time for proper vetting in tree. Though having been using similar to 1721 in my overlay for many months. It is likely save without mask. The mask is just to be uber cautious. Thanks!

**Comment by labre** [comment]
Probably should have answered right after pushing. Added a commit. Although I would assume, that the eclasses for JDK9 have yet to be rewritten, which is probably currently more reasoning for delaying the merge.

**Comment by wltjr** [comment]
No the reason for delay is superficial, and lack of man power. Most the focus is on icedtea/openjdk. This was an [issue in the past with JDK8](https://forums.gentoo.org/viewtopic-t-1015376-postdays-0-postorder-asc-start-25.html) as well.

The eclasses do not need to be re-written to support JDK 9. I have been using it for months similar to #1721. The eclasses do not support JDK 9 -release, new replacement for source/target. Nor has the issue with missing tools.jar been addressed. Only a very small amount of ebuilds require tools.jar. The -release aspect is semi moot, as source/target now does not properly use older rt.jar for bootclasspath purposes. Likely eclasses will not be modified to support -release till 1.8/8 has been removed. Since there would have to be support in eclasses for both source/target and release. None of this is show stoppers for adding JDK 9.

The only issue I have seen that is valid. If someone builds under 9, and then goes to run that stuff under 8 there can be issues due to the [source/target bootclasspath issue](https://wiki.gentoo.org/wiki/Java_Developer_Guide#Bootstrap_class_path). However that exists now and has for some time. If you use 1.8 and got back to 1.7, etc.

The real issue is none actually use this stuff, none are Java devs. Most time and effort goes to icedtea/openjdk as many in Gentoo dislike Oracle, having to download binary, etc. If they needed or used this stuff it would be in tree. I am a long time Java developer. I do not see things improving anytime soon. Not till people get out of the way and stop being the problem and let others be the solution. The result is my [massive overlay](https://github.com/Obsidian-StudiosInc/os-xtoo) with tons of Java stuff not in tree. All that would be in tree and other things long ago.

As of now all JDK/JRE stuff falls to one person @chewi. There is no team, its just @chewi with hellp from @monsieurp . There are some others @fordfrog handles netbeans, tomcat, and some stuff. Though things like #1358 remain. There are some new devs but they have yet to contribute anything substantial and doing JDK/JRE eclass stuff is not really trivial for new devs.

Sadly its been this way for close to a decade now. I have made tons of noise on list, etc and been [banned from github](https://archives.gentoo.org/gentoo-project/message/d96082f8327661da4a5c256d05f2e09f) due to comments like this...

This will be added to tree when @chewi has time and/or signs off. I tried to get him to allow other devs to commit your work or #1721. Thus the request for the mask. No one wants to do anything to move things along faster. No one wants to work as a team. Its all up to one individual...

**Comment by labre** [comment]
> Sadly its been this way for close to a decade now. I have made tons of noise on list, etc and been banned from github due to
> comments like this...
I’ve read it when I was reviewing the beta JDK ebuilds. @chewi also
pointed out the scarce staff in one of the previous PRs of these
ebuilds. Well, I was mostly forced to 9, because my compiler design
lecturer demands it and there is no icedtea-9 currently… oracle-jdk-bin
ebuilds have been indeed annoying lately, because sometimes they are
already out-of-date, when updating and Oracle requires an account
Java Archive downloads. So far, I bumped locally in that case, but looks
like I better create a PR instead for the future. If it helps…

No idea however, what the radical solution, @chewi spoke of, should look
like. In Gentoo terms likely a g-sorcery module, but Java has no
centralized repository and it would be hard to create them properly from
portable Apps.

Thanks for linking your Overlay though. Maybe I’ll find something useful.
> This will be added to tree when @chewi has time and/or signs off. I tried to get him to allow other devs to commit your work or
> #1721. Thus the request for the mask. No one wants to do anything to move things along faster. No one wants to work as a
> team. Its all up to one individual...
I think, he will find some time eventually. Have you tried to become a
Java Team member, regardless of its existence or not? If you got
rejected, you could still open a Userrel bug.

Best regards,
Manuel

**Comment by wltjr** [comment]
I [was a developer before](https://bugs.gentoo.org/show_bug.cgi?id=135927) and have tried to return many times. They have prevented me, forced me to jump through hula hoops to contribute etc. I work outside now. I do not contribute as I have been discouraged. My overlay is the result. I do still try to help via information and other things at times. I was the only one updating the Gentoo Java Developer Guide and related. Though I stopped doing that some time ago. Its a dumb situation that has persisted for close to a decade now.

**Comment by labre** [comment]
> I was a developer before and have tried to return many times. They have prevented me, forced me to jump through hula hoops
> to contribute etc. I work outside now. I do not contribute as I have been discouraged. My overlay is the result. I do still try to
> help via information and other things at times. I was the only one updating the Gentoo Java Developer Guide and related.
> Though I stopped doing that some time ago. Its a dumb situation that has persisted for close to a decade now.
I see. Temper seems to be a hindrance to being acknowledged as Gentoo
developer. Even Linus has resorted to moderate temper lately. Sorry for
getting OT.

But to give an example for attidude preventing technological progress,
the merge of grsecurity patches into mainline has been likely prevented
by the attidudes of Linus and spencer. Both opinions were partially
wrong.

Linus claimed Grsecurity breaks things. That’s correct, but it is the
purpose of a OS security system to break things, especially malicious
ones.  SELinux does the same, if you don’t have appropriate policies
installed or written. In my experience it did not break kernel things in
moderate configurations, but most of the userspace would break of
course, unless you followed the Hardened migration guide, all binaries
got ELF pax flags and you don’t recognize the slightest difference after
rebooting.  I liked it.

spencer mostly prevented the merge by keeping the opinion, that his
patches should be merged as a whole, because any missing part would open
attack vectors. That’s of course also correct. But still, if he wouldn’t
have been repeatedly pointing out the flaws of kernel security and
instead split features into small patches, that would have been dripping
into mainline eventually, he and his company likely would have a better
standing point right now as mainline kernel developers maintaining the
Grsecurity subsystem.

I also don’t get the current financing approach. They could have
documented proposed features in unselectable Kconfig options and
requiring a certain amount from donators till they develop that
feature. That feature would then published regularly and thus there
would be no doubts about GPL compliance, since the whole code is always
available to the general public. It would make sense to always give a
donation share to dependent projects. Could be useful for any open
source licensed project.

**Comment by wltjr** [comment]
Rebuilding packages with java 9, running into various issues. It will likely have to remain masked till addressed. Which likely cannot be till its added to tree. There are fair amount of issues to address with various packages.

**Comment by wltjr** [comment]
Just as a follow up, having worked with JDK 9. There is a considerable amount of work needed to get it into tree. It could be added masked, but would not be safe for a system vm. To many packages in tree will fail to build. Till that is addressed. Java 9 will be slow going on Gentoo. There is tremendous work to be done for such.

Just wanted to correct my previous comments on being superficial. There are some very legit major reasons for it not being added to tree. Sadly knowing the work I do not see it happening any time soon. I have been doing the work in my overlay for a couple weeks now. To many things have issues. its almost worse than 1.4 going to 1.5. Which required new eclasses java-config etc called Generation 2, all the 2 stuff, java-utils-2, etc. Likely need Generation 3 now, major changes across the board.

**Comment by labre** [comment]
> Just wanted to correct my previous comments on being superficial. There are some very legit major reasons for it not being
> added to tree. Sadly knowing the work I do not see it happening any time soon. I have been doing the work in my overlay for a
> couple weeks now. To many things have issues. its almost worse than 1.4 going to 1.5. Which required new eclasses
> java-config etc called Generation 2, all the 2 stuff, java-utils-2, etc. Likely need Generation 3 now, major changes across the
> board.

After having read the mask on 7 by @chewi, I almost suspected the
required eclass adaptions/rewrites. Thanks for checking the Java
packages against JDK9.

Since Java now has complete support for running in legacy versions and
compiling for them, the adaptions are quite inevitable. However, as with
GCC5 C++ ABI forward compatibility, we hopefully are spared from
changing them again in future versions.

I also accidentally forgot to switch the system VM a few times and any
JDK8-Bytecode crashed (Eclipse, IntelliJ, hibiscus).
So probably running and compiling any existing code for JDK8 by default
for the time being would help to release the mask after some testing.

My main goal of being able to compile with JDK9 class dependencies has
been achieved though, and I don’t have so much time right now, since
exams are approaching, so I can’t adapt (nor understand the intentions
of) the eclasses myself for now.

Best regards,
Manuel

**Comment by wltjr** [comment]
The bytecode aspect can be worked around as you discovered, recompile again with older as you switch back etc. But there are other issues, stuff that doesn't build under 9, lack of source/target < 1.6, eclasses not supporting --release, no tools.jar, various sun. and com.sun classes are not visible without java 9 exports and other things. Not to mention doing it all in way that does not break it for 1.8 or 9. In supporting 9 in my overlay. I am essentially breaking some packages. There is not really a clean solution.

Really needed to be working on this stuff months ago. Now its a catch up game, and a lose lose one. Why? Well java is going to start seeing like 3 or 4 release per year.... New one coming in March. Hopefully should not be major, but who knows. Either way Gentoo needs to be more proactive on java front, and that has not happened for some time. Chewi and others do all they can, but its a lot of work. Without others and it happen on a regular basis. Any work done today is outdated in a few months if not done again, updates etc. It needs people to care more about Java. But being either educational or enterprise. Gentoo ends up in a void where there isn't any one interested in Java. Much less people like me and others who code in Java primarily for a living. Though I do some C, it is mostly Java for me :)

**Comment by wltjr** [comment]
Link regarding Java release schedules.
https://mreinhold.org/blog/forward-faster

**Comment by chewi** [comment]
I'm done putting this off now and Java 7 is gone so I'll take a look. I had an idea that maybe instead of masking everything, I could add a masked `gentoo-vm` flag to the Oracle packages that would control whether the "env" file gets installed or not. The virtuals would still be masked and would require this flag to be enabled. That way people are free to use this but the Gentoo Java packages simply won't see it. I need to test it out but how does that sound?

**Comment by labre** [comment]
Sounds like a clean intermediate solution actually.

Of course Java 9’s cross compiling capabilities should be used in the
long-term. Upstream Java project maintainers seem to adapt quite slowly,
so a variant using a, say, java-2 eclass flag for setting the version of
source and target bytecode should be cleaner and we could completely
move to Java 9 in theory.

Since Java’s release cycle has been increased though, the main
question is, whether Java 9 now does ABI breaking changes, while not
allowing to build for previous ABI versions in 9. That would be hell.
In that case your solution could be cleaner in the long-term.

**Comment by labre** [comment]
> Of course Java 9’s cross compiling capabilities should be used in the
> long-term. Upstream Java project maintainers seem to adapt quite slowly,
> so a variant using a, say, java-2 eclass flag for setting the version of
> source and target bytecode should be cleaner and we could completely
> move to Java 9 in theory.
Just noticed, that these flags already exist. ;) So at least geogebra
compiles because of them, although it hard depends on oracle-jdk-bin:1.8.

So this sounds like a clean solution. :) I should note, that I didn’t
the env file in this version. Java 9 still works, because it does not
need any of the previous classpath jars and ignores them, if they are
not found.

If that does not bother you, go ahead. Otherwise I could add and test a
1.9 env file with empty classpath with my compiler construction
projects. I can recall however, that on the first try with a modified
env file, the vm symlink was not set correctly, so I would prefer
leaving it untouched. ;)

**Comment by chewi** [comment]
Just pushed my own java-sdk-docs update. Hey, it's a start. :stuck_out_tongue: I didn't use yours because it didn't have the handy fetch restriction stuff from the earlier versions.

I take it you're talking about the BOOTCLASSPATH variable in the env file? Don't get too hung up on this, I can't even remember what it's used for and I know it's been wrong in the past so it's not that important.

**Comment by labre** [comment]
> Just pushed my own java-sdk-docs update. Hey, it's a start. 😛 I didn't use yours because it didn't have the handy fetch
> restriction stuff from the earlier versions.
Congratulations! ;)
> I take it you're talking about the BOOTCLASSPATH variable in the env file? Don't get too hung up on this, I can't even
> remember what it's used for and I know it's been wrong in the past so it's not that important.
Yes, I meant that. Good to know.

**Comment by labre** [comment]
Rebased from current master.  Deleted sdk-docs commit.  Maybe this makes
the remaining work a little bit less tedious? ;)

**Comment by chewi** [comment]
Made some progress tonight. I'm surprised I hadn't noticed all the platforms they've dropped before. With this few to support, I suppose we may as well add the others to the JRE. I've been making some changes too, the ebuild might look quite different by the end.

**Comment by chewi** [comment]
Just about done the JRE now. Onto the JDK...

**Comment by chewi** [comment]
Aaaand done. Sorry I didn't use your commits in the end but I changed the ebuilds so much, the changes would have been longer than the ebuilds. I did give credit though!

**Pull request closed without merging**
