### PR TITLE
Bump frescobaldi to 2.18.1 and depend on python-ly, fixes #543052, #561022

### PR DESCRIPTION
**Pull request by lilrc**
Also the 2.18 version has been removed.

### CODE REVIEW

**Comment by filmor** [comment]
Any particular reason for removing Python 3 from the compat list? I'm running Frescobaldi fine with 3.4 with the ebuild from Bugzilla.

**Comment by lilrc** [comment]
I could not figure out what would happen if it was built with portmidi and python3 and I wanted to be sure it works with all python implementations. Also one would have to use python_gen_cond_dep to make repoman happy. (Honestly, I did not research any deeper what would happen when USE="portmidi" and PYTHON_TARGETS="python3_*".)

**Comment by idella** [comment]
eeeer
@gentoo/proxy-maint

**Comment by idella** [comment]
@lilrc ;  starting with the new dev-python/python-ly

1. while the python impls work in those in PYTHON_COMPAT, you're expected to have run tested on all. You have pypy3 emerged?

2. KEYWORDS are clearly copy pasted from another ebuild.  For a new package, similarly one submits only on the arches on which you tested. For amd64, you can default add x86.

3. The doc build connects to the internet which is disallowed in 'gentoo protocol". A full emerge need occur with no connection to a network.
See: WARNING: autodoc: failed to import module u'ly.data.makeschemedata'; the following exception was raised:
For this we might have to sacrifice a doc build.

4. The install need be set to doc?build for installing the built docs.
python-ly has to be made 'right' before moving onto Bump frescobaldi.

**Comment by mgorny** [comment]
@gentoochainsaw, @aballier, @chutz, @radhermit, @yngwin, @gentoo/python for frescobaldi

**Comment by lilrc** [comment]
@idella @mgorny: I will and want to fix the issues when I find some time.

**Comment by lilrc** [comment]
@idella 
1 & 2. OK. I got the ebuild from @filmor, but I guess he also copy pasted it. Dropped.
3 & 4. Would it be unnacceptibly lazy to drop the doc USE-flag, entirely?

**Comment by mgorny** [comment]
It's fine unless it's really needed to use this ;-).

**Comment by lilrc** [comment]
I can use frescobaldi without the documentation for pythons-ly, so I dropped the USE-flag. :)

**Comment by filmor** [comment]
Regarding 1 and 2, I have indeed only tested x86 and amd64 with cpython 2.7, 3.3 and 3.4. I just assumed since the library is pure python, but I see your point.

**Comment by idella** [comment]
pypy and pypy3 are fine once emerged, just like Cpython, but they are poorly understood and very thinly and poorly supported in 'userland'. You can do without them.

Docs are nice if they work, but if they're troublesome, abandon them without guilt. 
So this pull request is os double barrelled. Ideally it ought be one package per request, but not to worry. Is python-ly looking 'good to go'?

**Comment by lilrc** [comment]
@idella: I do not think it is worthwhile to include USE="doc" for python-ly, no. You are not asking if I think python-ly looks good to go, right? Anyway, I will rebase the python-ly commits when I get home today so that it is merge ready.

**Comment by lilrc** [comment]
Rebased. I am ready to go on.

**Comment by idella** [comment]
python-ly  has a doc build but we can do that later. Missed preserving the sig this time otherwise merged.

**Pull request closed without merging**
