### PR TITLE
media-libs/gavl: Add patch for x32, bug #472288

### PR DESCRIPTION
**Pull request by bjacquin**
Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/video

**Comment by mgorny** [comment]
@bjacquin, when submitting PR for existing bug, please also leave a comment on the bug and CC reviewers@gentoo.org. This will help us notice approval of your request when relevant developers don't use GitHub.

**Comment by mgorny** [comment]
(but i'll do that for you now)

**Comment by aballier** [comment]
lgtm (patch is from upstream, right?)

**Pull request merged**
