### PR TITLE
dev-java/jstl{,-api}: new package, add 1.2.7 | dev-java/javax-{el,jsp,servlet}-api: new package

### PR DESCRIPTION
**Pull request by vaukai**
Needed to unbundle [`jstl.jar` and `standard.jar`](https://github.com/i2p/i2p.i2p/blob/i2p-2.1.0/build.properties#L156-L159) in [`i2p-2.1.0`](https://github.com/i2p/i2p.i2p/tree/i2p-2.1.0/apps/susidns/src/lib).

Bug: https://bugs.gentoo.org/892703

### CODE REVIEW

**Comment by fordfrog** [comment]
i just went through the commits, wouldn't it be better to create separate packages for `jstl-api` and `jstl-impl`?

**Comment by vaukai** [comment]
> i just went through the commits, wouldn't it be better to create separate packages for `jstl-api` and `jstl-impl`?

What's the benefit of splitting them? Presently, there is only one [potential consumer](https://github.com/gentoo/gentoo/pull/29290) which needs them both. And splitting them would double the workload in case of version bumps.

**Comment by fordfrog** [comment]
imo it would be a cleaner way to split the api and the implementation. you can have one api and several implementations. and packages usually need only the api to compile. whereas during runtime some implementation is needed.

**Comment by vaukai** [comment]
> imo it would be a cleaner way to split the api and the implementation. you can have one api and several implementations. and packages usually need only the api to compile. whereas during runtime some implementation is needed.

`jstl-api` for `compile-classpath` and `jstl-impl` for `runtime-classpath`, if using these terms?
If a consumer has the combo package is in `CP_DEPEND`, could this cause trouble?  Please understand I am not strictly against splitting but prefer keeping it simple for version bumps.  Give me one day think about.

**Comment by fordfrog** [comment]
`jstl-api` does not compile for me:
```
>>> Emerging (4 of 5) dev-java/jstl-api-1.2.7::gentoo
 * jstl-1.2.7.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                                                                                        [ ok ]
 * Using: openjdk-17
>>> Unpacking source...
>>> Unpacking jstl-1.2.7.tar.gz to /var/tmp/portage/dev-java/jstl-api-1.2.7/work
>>> Source unpacked in /var/tmp/portage/dev-java/jstl-api-1.2.7/work
>>> Preparing source in /var/tmp/portage/dev-java/jstl-api-1.2.7/work/tags-1.2.7-RELEASE ...
Searching for bundled jars:
None found.
Searching for bundled classes (no output if none found):
Search done.
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-java/jstl-api-1.2.7/work/tags-1.2.7-RELEASE ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-java/jstl-api-1.2.7/work/tags-1.2.7-RELEASE ...
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 @sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:20: error: cannot find symbol
import javax.servlet.jsp.JspException;
                        ^
  symbol:   class JspException
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:21: error: cannot find symbol
import javax.servlet.jsp.JspTagException;
                        ^
  symbol:   class JspTagException
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:22: error: cannot find symbol
import javax.servlet.jsp.PageContext;
                        ^
  symbol:   class PageContext
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:23: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.TagSupport;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:45: error: cannot find symbol
    extends TagSupport
            ^
  symbol: class TagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:58: error: cannot find symbol
    protected abstract boolean condition() throws JspTagException;
                                                  ^
  symbol:   class JspTagException
  location: class ConditionalTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/ConditionalTagSupport.java:82: error: cannot find symbol
    public int doStartTag() throws JspException {
                                   ^
  symbol:   class JspException
  location: class ConditionalTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:20: error: cannot find symbol
import javax.servlet.ServletContext;
                    ^
  symbol:   class ServletContext
  location: package javax.servlet
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:21: error: cannot find symbol
import javax.servlet.ServletRequest;
                    ^
  symbol:   class ServletRequest
  location: package javax.servlet
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:22: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpSession;
                         ^
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:23: error: cannot find symbol
import javax.servlet.jsp.PageContext;
                        ^
  symbol:   class PageContext
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:100: error: cannot find symbol
    public static Object get(PageContext pc, String name, int scope) {
                             ^
  symbol:   class PageContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:129: error: cannot find symbol
    public static Object get(ServletRequest request, String name) {
                             ^
  symbol:   class ServletRequest
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:148: error: cannot find symbol
    public static Object get(HttpSession session, String name) {
                             ^
  symbol:   class HttpSession
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:172: error: cannot find symbol
    public static Object get(ServletContext context, String name) {
                             ^
  symbol:   class ServletContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:189: error: cannot find symbol
    public static void set(PageContext pc, String name, Object value,
                           ^
  symbol:   class PageContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:222: error: cannot find symbol
    public static void set(ServletRequest request, String name, Object value) {
                           ^
  symbol:   class ServletRequest
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:239: error: cannot find symbol
    public static void set(HttpSession session, String name, Object value) {
                           ^
  symbol:   class HttpSession
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:256: error: cannot find symbol
    public static void set(ServletContext context, String name, Object value) {
                           ^
  symbol:   class ServletContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:273: error: cannot find symbol
    public static void remove(PageContext pc, String name, int scope) {
                              ^
  symbol:   class PageContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:303: error: cannot find symbol
    public static void remove(ServletRequest request, String name) {
                              ^
  symbol:   class ServletRequest
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:318: error: cannot find symbol
    public static void remove(HttpSession session, String name) {
                              ^
  symbol:   class HttpSession
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:333: error: cannot find symbol
    public static void remove(ServletContext context, String name) {
                              ^
  symbol:   class ServletContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/Config.java:355: error: cannot find symbol
    public static Object find(PageContext pc, String name) {
                              ^
  symbol:   class PageContext
  location: class Config
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:20: error: package javax.el does not exist
import javax.el.ELContext;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:21: error: package javax.el does not exist
import javax.el.ValueExpression;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:27: error: cannot find symbol
public final class IndexedValueExpression extends ValueExpression {
                                                  ^
  symbol: class ValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:34: error: cannot find symbol
    protected final ValueExpression orig;
                    ^
  symbol:   class ValueExpression
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:39: error: cannot find symbol
    public IndexedValueExpression(ValueExpression orig, int i) {
                                  ^
  symbol:   class ValueExpression
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:49: error: cannot find symbol
    public Object getValue(ELContext context) {
                           ^
  symbol:   class ELContext
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:64: error: cannot find symbol
    public void setValue(ELContext context, Object value) {
                         ^
  symbol:   class ELContext
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:77: error: cannot find symbol
    public boolean isReadOnly(ELContext context) {
                              ^
  symbol:   class ELContext
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IndexedValueExpression.java:91: error: cannot find symbol
    public Class getType(ELContext context) {
                         ^
  symbol:   class ELContext
  location: class IndexedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:27: error: package javax.el does not exist
import javax.el.ELContext;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:28: error: package javax.el does not exist
import javax.el.ELException;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:29: error: package javax.el does not exist
import javax.el.ValueExpression;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:31: error: cannot find symbol
import javax.servlet.jsp.JspTagException;
                        ^
  symbol:   class JspTagException
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:40: error: cannot find symbol
    protected final ValueExpression orig;
                    ^
  symbol:   class ValueExpression
  location: class IteratedExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:47: error: cannot find symbol
    public IteratedExpression(ValueExpression orig, String delims) {
                              ^
  symbol:   class ValueExpression
  location: class IteratedExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:57: error: cannot find symbol
    public Object getItem(ELContext context, int i) {
                          ^
  symbol:   class ELContext
  location: class IteratedExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedExpression.java:81: error: cannot find symbol
    public ValueExpression getValueExpression() {
           ^
  symbol:   class ValueExpression
  location: class IteratedExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:20: error: package javax.el does not exist
import javax.el.ELContext;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:21: error: package javax.el does not exist
import javax.el.ValueExpression;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:27: error: cannot find symbol
public final class IteratedValueExpression extends ValueExpression {
                                                   ^
  symbol: class ValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:38: error: cannot find symbol
    public Object getValue(ELContext context) {
                           ^
  symbol:   class ELContext
  location: class IteratedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:42: error: cannot find symbol
    public void setValue(ELContext context, Object value) {
                         ^
  symbol:   class ELContext
  location: class IteratedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:45: error: cannot find symbol
    public boolean isReadOnly(ELContext context) {
                              ^
  symbol:   class ELContext
  location: class IteratedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/IteratedValueExpression.java:49: error: cannot find symbol
    public Class getType(ELContext context) {
                         ^
  symbol:   class ELContext
  location: class IteratedValueExpression
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTag.java:20: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.Tag;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTag.java:36: error: cannot find symbol
public interface LoopTag extends Tag {
                                 ^
  symbol: class Tag
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:26: error: package javax.el does not exist
import javax.el.ValueExpression;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:27: error: package javax.el does not exist
import javax.el.VariableMapper;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:28: error: package javax.el does not exist
import javax.el.ELException;
               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:30: error: cannot find symbol
import javax.servlet.jsp.JspException;
                        ^
  symbol:   class JspException
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:31: error: cannot find symbol
import javax.servlet.jsp.JspTagException;
                        ^
  symbol:   class JspTagException
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:32: error: cannot find symbol
import javax.servlet.jsp.PageContext;
                        ^
  symbol:   class PageContext
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:33: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.IterationTag;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:34: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.TagSupport;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:35: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.TryCatchFinally;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:76: error: cannot find symbol
    extends TagSupport
            ^
  symbol: class TagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:77: error: cannot find symbol
    implements LoopTag, IterationTag, TryCatchFinally
                        ^
  symbol: class IterationTag
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:77: error: cannot find symbol
    implements LoopTag, IterationTag, TryCatchFinally
                                      ^
  symbol: class TryCatchFinally
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:119: error: cannot find symbol
    protected ValueExpression deferredExpression;
              ^
  symbol:   class ValueExpression
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:123: error: cannot find symbol
    private ValueExpression oldMappedValue;
            ^
  symbol:   class ValueExpression
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:193: error: cannot find symbol
    protected abstract Object next() throws JspTagException;
                                            ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:209: error: cannot find symbol
    protected abstract boolean hasNext() throws JspTagException;
                                                ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:219: error: cannot find symbol
    protected abstract void prepare() throws JspTagException;
                                             ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:236: error: cannot find symbol
    public int doStartTag() throws JspException {
                                   ^
  symbol:   class JspException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:278: error: cannot find symbol
    public int doAfterBody() throws JspException {
                                    ^
  symbol:   class JspException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:470: error: cannot find symbol
    protected void validateBegin() throws JspTagException {
                                          ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:479: error: cannot find symbol
    protected void validateEnd() throws JspTagException {
                                        ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:488: error: cannot find symbol
    protected void validateStep() throws JspTagException {
                                         ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:518: error: cannot find symbol
    private void calibrateLast() throws JspTagException {
                                        ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:532: error: cannot find symbol
    private void exposeVariables(boolean firstTime) throws JspTagException {
                                                           ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:604: error: cannot find symbol
    private void discard(int n) throws JspTagException {
                                       ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:622: error: cannot find symbol
    private void discardIgnoreSubset(int n) throws JspTagException {
                                                   ^
  symbol:   class JspTagException
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:637: error: cannot find symbol
    private ValueExpression getVarExpression(ValueExpression expr) {
                                             ^
  symbol:   class ValueExpression
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/core/LoopTagSupport.java:637: error: cannot find symbol
    private ValueExpression getVarExpression(ValueExpression expr) {
            ^
  symbol:   class ValueExpression
  location: class LoopTagSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:26: error: cannot find symbol
import javax.servlet.ServletResponse;
                    ^
  symbol:   class ServletResponse
  location: package javax.servlet
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:27: error: package javax.servlet.http does not exist
import javax.servlet.http.HttpServletRequest;
                         ^
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:28: error: cannot find symbol
import javax.servlet.jsp.PageContext;
                        ^
  symbol:   class PageContext
  location: package javax.servlet.jsp
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:71: error: cannot find symbol
    public static String getLocalizedMessage(PageContext pageContext, 
                                             ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:93: error: cannot find symbol
    public static String getLocalizedMessage(PageContext pageContext, 
                                             ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:117: error: cannot find symbol
    public static String getLocalizedMessage(PageContext pageContext, 
                                             ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:142: error: cannot find symbol
    public static String getLocalizedMessage(PageContext pageContext, 
                                             ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:182: error: cannot find symbol
    private static LocalizationContext getLocalizationContext(PageContext pc) {
                                                              ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:224: error: cannot find symbol
    private static LocalizationContext getLocalizationContext(PageContext pc,
                                                              ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:296: error: cannot find symbol
    private static LocalizationContext findMatch(PageContext pageContext,
                                                 ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:401: error: cannot find symbol
    private static Locale getLocale(PageContext pageContext, String name) {
                                    ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:430: error: cannot find symbol
    private static void setResponseLocale(PageContext pc, Locale locale) {
                                          ^
  symbol:   class PageContext
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/fmt/LocaleSupport.java:515: error: cannot find symbol
    private static Enumeration getRequestLocales(HttpServletRequest request) {        
                                                 ^
  symbol:   class HttpServletRequest
  location: class LocaleSupport
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:25: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.PageData;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:26: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.TagLibraryValidator;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:27: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.ValidationMessage;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:50: error: cannot find symbol
public class PermittedTaglibsTLV extends TagLibraryValidator {
                                         ^
  symbol: class TagLibraryValidator
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:98: error: cannot find symbol
	    String prefix, String uri, PageData page) {
	                               ^
  symbol:   class PageData
  location: class PermittedTaglibsTLV
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:97: error: cannot find symbol
    public synchronized ValidationMessage[] validate(
                        ^
  symbol:   class ValidationMessage
  location: class PermittedTaglibsTLV
api/src/main/java/javax/servlet/jsp/jstl/tlv/PermittedTaglibsTLV.java:154: error: cannot find symbol
    private ValidationMessage[] vmFromString(String message) {
            ^
  symbol:   class ValidationMessage
  location: class PermittedTaglibsTLV
api/src/main/java/javax/servlet/jsp/jstl/tlv/ScriptFreeTLV.java:24: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.PageData;
                               ^
api/src/main/java/javax/servlet/jsp/jstl/tlv/ScriptFreeTLV.java:25: error: package javax.servlet.jsp.tagext does not exist
import javax.servlet.jsp.tagext.TagLibraryValidator;
                               ^
100 errors
1 warning
only showing the first 100 errors, of 169 total; use -Xmaxerrs if you would like to see more
 * ERROR: dev-java/jstl-api-1.2.7::gentoo failed (compile phase):
 *   ejavac failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 2400:  Called java-pkg-simple_src_compile
 *   environment, line  883:  Called ejavac '-d' 'target/classes' '-encoding' 'UTF-8' '@sources.lst'
 *   environment, line  642:  Called die
 * The specific snippet of code:
 *       "${args[@]}" || die "ejavac failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-java/jstl-api-1.2.7::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-java/jstl-api-1.2.7::gentoo'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-17  CLASSPATH="" JAVA_HOME="/usr/lib64/openjdk-17"
JAVACFLAGS="-source 1.8 -target 1.8" COMPILER=""
and of course, the output of emerge --info =jstl-api-1.2.7
 * The complete build log is located at '/var/tmp/portage/dev-java/jstl-api-1.2.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-java/jstl-api-1.2.7/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-java/jstl-api-1.2.7/work/tags-1.2.7-RELEASE'
 * S: '/var/tmp/portage/dev-java/jstl-api-1.2.7/work/tags-1.2.7-RELEASE'
'''

**Comment by vaukai** [comment]
Shit, merged from wrong branch. Sorry.

**Pull request closed without merging**
