### PR TITLE
multiprocessing.eclass & revdeps: kill multijob*

### PR DESCRIPTION
**Pull request by mgorny**
https://bugs.gentoo.org/613322

### CODE REVIEW

**Comment by mgorny** [comment]
I've also included a cleanup of old dev-embedded/openocd as the only consumer of old dev-lang/jimtcl. If that's not acceptable, please let me know if I should clean a subset of them or keep and update old versions of jimtcl instead.

**Comment by mgorny** [comment]
Updated the ebuild approved by @floppym and @robbat2 (on IRC). Only jimtcl left.

**Comment by sarnold** [comment]
Yes, this also broke ncurses for me so i have work-around version in my overlay.  I totally approve ;)

**Comment by mgorny** [comment]
> Yes, this also broke ncurses for me so i have work-around version in my overlay. I totally approve ;)

Could you elaborate on this a bit? Do you mean that multijob logic broke the ncurses ebuild? Or is the multijob completely broken for you? In the latter case, I'll give it a higher priority to get it out of `sys-apps/portage` internals as well.

**Comment by sarnold** [comment]
it was a while ago since i tweaked the ebuild locally; iirc it would do exactly what you said above (ie, sub job failed but build kept going until the failure caught up and stopped the build).  Note my local ebuild (portage-overlay repo in my personal github) also has Ada language fixes that go along with modified toolchain for Ada support.  At that time there were no associated bugs for ncurses and I was sure if some hacking had broken it or not (plus i was busier than one-legged man at an a**-kicking contest).  As far as urgency, that's your call but I'd say as soon as convenient.  Plus i'm not home so difficult to test again for me.

**Pull request closed without merging**
