### PR TITLE
media-gfx/hydrus: Drop 515, Add 518 with python 3.11 support

### PR DESCRIPTION
**Pull request by vaartis**
Needs a patch for tests to pass, submitted it upstream, hopefully will be included in the next version.

### CODE REVIEW

**Review by mgorny — APPROVED** [review]
LGTM. Thanks!

**Review by mgorny — CHANGES_REQUESTED** [review]
Actually, the patch is a bit large. Could you fetch via `SRC_URI` instead? If you submitted it via GH pull request, you can link to the relevant commit with `.patch` appended to the URL.

**Comment by vaartis** [comment]
> If you submitted it via GH pull request, you can link to the relevant commit with .patch appended to the URL.

Unfortunately the author does not accept pull request, I send the patches to them directly.

**Review by mgorny — APPROVED** [review]
Thanks!

**Pull request closed without merging**
