### PR TITLE
app-misc/doublecmd-bin: new package

### PR DESCRIPTION
**Pull request by band-a-prend**
> Double Commander is a cross platform open source file manager with two panels side by side. 
> It is inspired by Total Commander and features some new ideas.

Build from sources requires `dev-lang/lazarus` and not-in-tree `dev-qt/qtpascal`
therefore there is a binary package with bundled `libQt5Pas.so.1` for `qt5` USE-flag

Bug: https://bugs.gentoo.org/415029

### CODE REVIEW

**Comment by band-a-prend** [comment]
I'm not sure about licence as some components and plugins have different licences.

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). Therefore it might take quite some time for this to get any attention. If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by band-a-prend** [comment]
@AndrewAmmerlaan 
Thank you for offer. I'm thinking about to bring this and some other binary/bundled packages (e.g. scilab-bin, WebPlotDigitizer-bin) from my "overlay" to GURU.

I hope to do it soon, sorry for delay with reply.

**Comment by band-a-prend** [comment]
Sent to [GURU repository (dev)](https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=db822d7cb6f2cec1086d946f5376474b49902ca6)

**Comment by AndrewAmmerlaan** [comment]
> Sent to [GURU repository (dev)](https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=db822d7cb6f2cec1086d946f5376474b49902ca6)

Looks good, I made one small change to the metadata file because repoman complained about inconsistent use of tabs/spaces. 

Also, I noticed that you are installing `exeinto /op/${PN}` this is not in `PATH` so you might want to `exeinto /opt/bin/${PN}` instead to be able to execute this from the command line. Or maybe:
```
exeinto "/opt/${PN}"
doexe "${S}/${MY_PN}"

exeinto "/opt/bin/${PN}"
newexe "${S}/${MY_PN}.sh" "${MY_PN}"
```
If the .sh is the only one that is supposed to be executed. (Unless of course these files *have* to be in the same directory)

If the executable is in ${PATH} then you can also simplify the make_desktop_entry line to:
```
make_desktop_entry "${MY_PN}" "Double Commander" "${MY_PN}" "Utility;"
```

**Comment by band-a-prend** [comment]
I don't place bundled library libQt5pas into system lib directory, so the .sh is used to run application.

I tried to experiment with running from command line after placing executable and it's symlink to /usr/bin but had some problems. Don't remember exactly what.

**Comment by band-a-prend** [comment]
@AndrewAmmerlaan 

> Also, I noticed that you are installing exeinto /op/${PN} this is not in PATH ...

I fixed it in guru repo commit by using `make_wrapper` call.

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan
> 
> > Also, I noticed that you are installing exeinto /op/${PN} this is not in PATH ...
> 
> I fixed it in guru repo commit by using `make_wrapper` call.

Awesome :+1: 

I pushed your commit to master just now. Thank you for your contribution!

**Pull request closed without merging**
