### PR TITLE
net-nds/openldap 2.6.1 version bump

### PR DESCRIPTION
**Pull request by expeditioneer**
Fixed various issues with the ebuild.

Signed-off-by: Dennis Lamm <expeditioneer@gentoo.org>

### CODE REVIEW

**Comment by robbat2** [comment]
@expeditioneer does this past `src_test`? I have local ebuilds for 2.5.9 & 2.6.0, but they don't pass tests, so they haven't been added

**Comment by expeditioneer** [comment]
@robbat2 "It works on my machine (amd64)" -  tests are passing but tests require '--enable-cleartext' otherwise they will  fail.

**Comment by thesamesam** [comment]
Merged in https://gitweb.gentoo.org/repo/gentoo.git/commit/net-nds/openldap?id=d12a02243969b7c715e9b639345ec8aacd925a28.

Do tests pass now then?

**Comment by robbat2** [comment]
Ok, I wrongly pushed this, and it's borked in multiple ways
```
>>> Compiling source in /var/tmp/portage-tmpfs/portage/net-nds/openldap-2.6.1/work/openldap-OPENLDAP_REL_ENG_2_6_1 ...                                       
 * abi_x86_32.x86: running multilib-minimal_abi_src_compile                                                                                                  
make -j14 -l12 CC=x86_64-pc-linux-gnu-gcc -m32 SHELL=/bin/sh                                                                                                 
make: invalid option -- '3'                                                                                                                                  
make: invalid option -- '2'                                                                                                                                  
Usage: make [options] [target] ... 
```

**Comment by thesamesam** [comment]
> Ok, I wrongly pushed this, and it's borked in multiple ways
> 
> ```
> >>> Compiling source in /var/tmp/portage-tmpfs/portage/net-nds/openldap-2.6.1/work/openldap-OPENLDAP_REL_ENG_2_6_1 ...                                       
>  * abi_x86_32.x86: running multilib-minimal_abi_src_compile                                                                                                  
> make -j14 -l12 CC=x86_64-pc-linux-gnu-gcc -m32 SHELL=/bin/sh                                                                                                 
> make: invalid option -- '3'                                                                                                                                  
> make: invalid option -- '2'                                                                                                                                  
> Usage: make [options] [target] ... 
> ```
I've fixed that and some other bits in tree

**Comment by SoapGentoo** [comment]
@robbat2 in future, please pay mroe attention before merging PRs. This PR was badly broken.

**Pull request closed without merging**
