### PR TITLE
dev-python/virtualenvwrapper: add python3_8 to PYTHON_COMPAT

### PR DESCRIPTION
**Pull request by Tatsh**

### CODE REVIEW

**Comment by prometheanfire** [comment]
looks live stevedore needs py38 as well

**Comment by Tatsh** [comment]
> looks live stevedore needs py38 as well

Thanks. I added stevedore.

**Comment by prometheanfire** [comment]
stevedore itself needs some of it's deps with 3_8 as well, repoman full should show you what's needed.

**Comment by Tatsh** [comment]
Closing this?

**Comment by prometheanfire** [comment]
not necessarily needed.  If you'd like to update the dependncies with 3_8 as needed we can do the review.

**Comment by Tatsh** [comment]
Okay. I updated all deps and checked with repoman.

**Comment by prometheanfire** [comment]
thanks, the last thing is the ordering of commits, it should be reversed (deps should get py38 before the dependant package).

I can do that myself (reorder the commits) or you can do it, just let me know.  Thanks for all this.

**Comment by Tatsh** [comment]
Should be in the correct order now but I have no idea why GitHub isn't showing this order. My Git log:

```
commit e746036df8ced589140a81c74707870f4e917e5b (HEAD -> virtualenvwrapper-add-38, origin/virtualenvwrapper-add-38)
Author: Andrew Udvare <audvare@gmail.com>
Date:   Fri May 1 13:26:17 2020 -0400

    dev-python/virtualenvwrapper: add python3_8 to PYTHON_COMPAT

    Signed-off-by: Andrew Udvare <audvare@gmail.com>

commit 52c49a2e2f20d78907ae18af64b57c065038ac1c
Author: Andrew Udvare <audvare@gmail.com>
Date:   Fri May 1 17:57:48 2020 -0400

    dev-python/stevedore: add python3_8 to PYTHON_COMPAT

    Signed-off-by: Andrew Udvare <audvare@gmail.com>

commit f17012c8f97e12f33b33f86df3d7a450e7510635
Author: Andrew Udvare <audvare@gmail.com>
Date:   Fri May 1 18:45:38 2020 -0400

    dev-python/stestr: add python3_8 to PYTHON_COMPAT

    Signed-off-by: Andrew Udvare <audvare@gmail.com>

commit ced23240638d95fdcd9b70d646fd28ff490dfee2
Author: Andrew Udvare <audvare@gmail.com>
Date:   Fri May 1 18:45:50 2020 -0400

    dev-python/voluptuous: add python3_8 to PYTHON_COMPAT

    Signed-off-by: Andrew Udvare <audvare@gmail.com>

commit 1bd71ba4baeefec56eefa1cdf8276964219bcf56
Author: Andrew Udvare <audvare@gmail.com>
Date:   Fri May 1 18:45:25 2020 -0400

    dev-python/cliff: add python3_8 to PYTHON_COMPAT

    Signed-off-by: Andrew Udvare <audvare@gmail.com>
```

Could you check this branch locally?

**Comment by Tatsh** [comment]
I cloned my branch fresh and got the correct commit order in `git log`.

**Comment by prometheanfire** [comment]
works for me, I've committed your commits, it's in the tree now.

**Pull request closed without merging**
