### PR TITLE
Convert sddm to acct eclass

### PR DESCRIPTION
**Pull request by floppym**

### CODE REVIEW

**Comment by a17r** [comment]
Thanks, but this is already in preparation including reserved UID/GID.

**Comment by floppym** [comment]
> Thanks, but this is already in preparation including reserved UID/GID.

Where is this being prepared? I looked in bugzilla and in the kde overlay.

**Comment by a17r** [comment]
Not very discoverable, should make a PR at some point: https://github.com/a17r/gentoo/tree/sddm-glep81

A bit stalled currently due to https://github.com/sddm/sddm/issues/1316

Not decided yet whether we shouldn't try and drop `video` membership and hard-depend on `pam` instead.

**Comment by floppym** [comment]
Ok. Do you want to close this then?

**Comment by a17r** [comment]
Yes please, I'll make sure to add you for my upcoming PR review then.

**Pull request closed without merging**
