### PR TITLE
media-tv/mythtv: Bump and fix compilation with libva

### PR DESCRIPTION
**Pull request by DarkDefender**
@thesamesam Do you want me to backport the patch to the 32 version as well or do you think just having it in the 33.1 version is OK?

### CODE REVIEW

**Comment by thesamesam** [comment]
Would you mind backporting too if it's not too much trouble so stable works again?

**Comment by DarkDefender** [comment]
@thesamesam just to be clear.
It seems to me like 33.1 build is the latest stable upstream release.
The 32 ebuild that is currently in portage is ~keyworded for both supported arches.

I think it should be kinda trivial to backport the patch, I'm just double checking that I understand you correctly.

**Comment by thesamesam** [comment]
Oh! Myth has no stable keywords in Gentoo. Ignore me, sorry!

**Comment by thesamesam** [comment]
Much appreciated, thank you!

**Comment by DarkDefender** [comment]
Thanks for bringing it to my attention! :)

**Pull request closed without merging**
