### PR TITLE
media-sound/spotify: Bump version to 1.2.8

### PR DESCRIPTION
**Pull request by Kaukov**
Updated to the latest version of Spotify as the current (1.1.84) can no longer be downloaded.

### CODE REVIEW

**Comment by Kaukov** [comment]
The issue produced is

```
RDEPEND: deprecated dependencies: app-accessibility/at-spi2-atk dev-libs/atk
```

However I don't see how they're deprecated as their latest `amd64` versions are `2.46.0`. Am I reading the error wrong?

**Comment by Kangie** [comment]
On mobile with broken touch so will be brief:

https://github.com/gentoo/gentoo/blob/master/profiles/package.deprecated#L90

Should enlighten you. :)

**Comment by Kaukov** [comment]
Thank you so much, that was indeed enlightening.

I've updated the PR and I hope that's all that was needed to have a valid one :)

**Review by juippis — APPROVED** [review]
Thanks, I'll fix style issues regarding our https://www.gentoo.org/glep/glep-0066.html#commit-messages and general workflow. I'll also add some missing dependencies while at it.

**Pull request closed without merging**
