### PR TITLE
www-servers/nginx: Version bump and HTTPoxy mitigation

### PR DESCRIPTION
**Pull request by Whissi**
This PR bumps nginx:mainline to v1.11.2 and adds a mitigation for the HTTPoxy vulnerability to both slots.

Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=588816

### CODE REVIEW

**Comment by Whissi** [comment]
*Pinging* @jbergstroem and @krifisk

**Comment by Whissi** [comment]
Pushed again to add bug information to the commit message of the version bump.

**Comment by jbergstroem** [comment]
LGTM

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by Polynomial-C** [comment]
Now in portage.

**Pull request closed without merging**
