### PR TITLE
app-benchmarks/sysbench: bump to 1.0.6, drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.5, Repoman-2.3.2

### CODE REVIEW

**Comment by mgorny** [comment]
I suppose it's not the first time somebody asks you this but those libraries in DEPEND look suspicious. Did you go through that already? ;-)

**Comment by hydrapolic** [comment]
@mgorny, yes, it looks a bit strange, but they are really needed :)

**Comment by gktrk** [comment]
https://github.com/gentoo/gentoo/compare/5aede65...a1ced72

**Comment by hydrapolic** [comment]
Thanks @gktrk

**Pull request closed without merging**
