### PR TITLE
www-client/surf: Introduce tabbed use flag and bug fix

### PR DESCRIPTION
**Pull request by arkamar**
Surf is shipped with `surf-open.sh` script for running surf in [`tabbed`](http://tools.suckless.org/tabbed). The newly introduced use flag installs this script and appends `x11-misc/tabbed` to a runtime dependency list.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Would it make more sense to always install surf-open.sh and put *tabbed* as `optfeature`? We do have a policy not to control installing small files via USE flag.

**Comment by thesamesam** [comment]
ping

**Comment by arkamar** [comment]
I did not know `optfeature` eclass, thank you. Anyway, yes, I can change it this way, but I like the version with USE flag more, because `surf-open.sh` script does not make any sense without tabbed being installed, surf is tiny program composed of 2 fairly small C files (compilation is fast) and it is configured in header file (users are used to recompile/reemerge it).

So, let me know if I convinced you or if I should change it to `optfeature` thing :) At the end, heaving `surf-open.sh` installed somehow systematically is most important for me.

**Review by juippis — COMMENTED** [review]
Sure, please rebase against fresh ::gentoo because your metadata.xml is throwing conflicts, and update surf's copyright year.

**Comment by arkamar** [comment]
Thanks! I have prepared fix for https://bugs.gentoo.org/show_bug.cgi?id=742602 related with `www-client/surf`, do you want me to create new PR or can I push it here as well?

**Comment by juippis** [comment]
Well as I can test this earliest tomorrow morning (in ~12 hours) you can add it here if you have time. It also makes testing a bit easier and faster, but I don't really mind. I'll check this in 12 hours!

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
