### PR TITLE
app-text/texlive{,-core}: Security cleanup (bug #536454)

### PR DESCRIPTION
**Pull request by Whissi**
Security cleanup, dropping an old vulnerable version.

### CODE REVIEW

**Comment by aballier** [comment]
well, yes, you need to remove matching dev-texlive/* versions along with app-text/texlive{,-core} and also the split packages ( dev-libs/kpathsea, dev-libs/ptexenc, app-text/ps2pkm, app-text/dvipsk, dev-tex/bibtexu )

after that the bot will check if it does not break anything

**Comment by Whissi** [comment]
Closed via commit bc8ce02b8f9e4add6ffffd174e564540d78e2ea2.

**Comment by Whissi** [comment]
Re-opening, app-text/texlive is clean, texlive-core not cleaned up yet.

**Comment by aballier** [comment]
yep we need to clean dev-texlive/* from pre-2016 versions; this requires pkgmoves and thus matching keywords

hppa is laggin behind

**Comment by monsieurp** [comment]
@Whissi @aballier ping.

**Comment by aballier** [comment]
fix the conflicts and get CI happy first

**Comment by mgorny** [comment]
Ping?

**Comment by flappyports** [comment]
new request opened:

https://github.com/gentoo/gentoo/pull/7576

**Pull request closed without merging**
