### PR TITLE
Add python-3.7 to tested packages

### PR DESCRIPTION
**Pull request by abecerra**

### CODE REVIEW

**Comment by a17r** [comment]
One commit per package please.

**Comment by flappyports** [comment]
@abecerra, thank you for the PR. A couple of items that need to be addressed though:

1. Please make the commits atomic (e.g. one commit per package changed)
2. Did you happen to test these against py3.8 as well? It is not a requirement but could be done now vice later.

**Comment by abecerra** [comment]
Starting to make it atomic in: 

https://github.com/gentoo/gentoo/pull/13883

**Comment by a17r** [comment]
You can btw force-push over your remote branch so that you do not have to create new PRs whenever there are rebases happening.

**Comment by a17r** [comment]
Plus, one PR may well include multiple commits. They should just be atomic, so one commit per changed package.

**Pull request closed without merging**
