### PR TITLE
media-gfx/xpaint: fix compilation with lto

### PR DESCRIPTION
**Pull request by ceamac**

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Let's not revbump here.

**Comment by ceamac** [comment]
I didn't want to revbump, the fix does basically nothing.  But it's stable.  Is it ok not to revbump in this case?

**Comment by thesamesam** [comment]
You should as it'll affect code generation. These bugs aren't usually LTO specific.

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Let's merge together with #26631 since they're related.

**Pull request closed without merging**
