### PR TITLE
net-analyzer/ntopng-6.0: add a new package

### PR DESCRIPTION
**Pull request by dpronin**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

Closes: https://bugs.gentoo.org/933818
Closes: https://bugs.gentoo.org/933819

### CODE REVIEW

**Comment by dpronin** [comment]
@thesamesam done

**Comment by thesamesam** [comment]
No, that's precisely why one PR is _good_, as you get passing CI? The CI failure here is different, it's not about a non-existent dep.

**Comment by dpronin** [comment]
> No, that's precisely why one PR is _good_, as you get passing CI? The CI failure here is different, it's not about a non-existent dep.

Ok, could you explain to me what is wrong? Maybe I am unable to understand messages given by CI

**Comment by thesamesam** [comment]
> "=" operator used without package revision: RDEPEND="=net-libs/nDPI-4.8:="

The issue is that it's ambiguous. It doesn't allow -r1 but it's not explicit about it so it's considered suspicious.

You probably want: `=net-libs/nDPI-4.8*:=` (`*` means `4.8.*`, not `4.8*` here) or `~net-libs/nDPI-4.8` possibly.

**Comment by dpronin** [comment]
> > "=" operator used without package revision: RDEPEND="=net-libs/nDPI-4.8:="
> 
> The issue is that it's ambiguous. It doesn't allow -r1 but it's not explicit about it so it's considered suspicious.
> 
> You probably want: `=net-libs/nDPI-4.8*:=` (`*` means `4.8.*`, not `4.8*` here) or `~net-libs/nDPI-4.8` possibly.

Thank you, let's wait for the next CI results, I have pushed

**Comment by dpronin** [comment]
@thesamesam the PR seems to have passed CI

**Pull request closed without merging**
