### PR TITLE
x11-libs/wxGTK: new slot - 3.1-gtk3

### PR DESCRIPTION
**Pull request by stefantalpalaru**
Closes: https://bugs.gentoo.org/577030

This version is required by software like http://cubicsdr.com/

### CODE REVIEW

**Comment by leio** [comment]
Happy to add a stable 3.2 version. Unfortunately that requires upstream to actually stabilize API/ABI and make such a release. As such, there is really nothing to do here. If there are even more consumers, MAYBE a package.masked main tree version eventually...
Most definitely a NAK without p.mask, that is.

**Comment by stefantalpalaru** [comment]
> If there are even more consumers, MAYBE a package.masked main tree version eventually...

How can there be any consumers, if you failed to add this development version since 2016-02-29 when 3.1.0 was released?

Also, why mask a slotted version that works just fine in ~arch, along all those other development versions?

**Comment by leio** [comment]
Yes, I've failed to add 3.1 versions. Very much on purpose. There's no need for such a tone (`you failed`, etc) for being a responsible maintainer and not adding ABI unstable development releases. I don't have the time to even get to fixing up wxpython situation (3.0 gtk3 usage + that phoenix 4.0 stuff), so adding more maintenance need for an unstable ABI is not something I desire in the current state. I'd rather get around to wxpython gtk3 and initial looks into phoenix..

Under consumers I meant "potential consumers". Yes, there are apparently some by now in the form of cubicsdr and more. Their choice to rely on a development release of wx is however most unfortunate.

Regarding p.mask: ABI unstable development releases do not belong in ~arch. 3.1.2 will likely be incompatible with 3.1.1 and every application using this 3.1-gtk3 SLOT would have to be rebuilt, and there aren't even any mechanism in place for that here.

This is in my opinion a wxWidgets upstream failure and I can't do anything about it without investing yet more volunteer time to a library (upstream work) I don't care about anymore.
Active users of wxWidgets are welcome to join the project and maintain it - but maintain it properly, e.g. handle these technical details in a responsible manner. I'm not saying you haven't - I think your version is quite good compared to what I remember seeing elsewhere, but it's a conceptual and technical problem from upstream releasing new stable releases so rarely and slipping all their target dates all the time.

As you can see, I don't actually notice github comments unless I stumble on them due to some other reason to visit the site and stumble on a particular PR, so comments in bugzilla or mail are better.

**Comment by stefantalpalaru** [comment]
> Yes, there are apparently some by now in the form of cubicsdr and more. Their choice to rely on a development release of wx is however most unfortunate.

Funny you should say that. cubicsdr-0.2.3 was recently added to the main tree: https://packages.gentoo.org/packages/net-wireless/cubicsdr

That's actually an old release from January, the current one being 0.2.5 (from August). The reason we get old software is a lack of dependencies for newer versions. Guess which dependency is involved here.

> 3.1.2 will likely be incompatible with 3.1.1 and every application using this 3.1-gtk3 SLOT would have to be rebuilt, and there aren't even any mechanism in place for that here

Yes there are - use subslots and ":SLOT=" operators on wxGTK dependencies: https://devmanual.gentoo.org/general-concepts/dependencies/index.html

> As you can see, I don't actually notice github comments unless I stumble on them due to some other reason to visit the site and stumble on a particular PR, so comments in bugzilla or mail are better.

Or you could just click the "Subscribe" button in the right column - it's the same that said "Unsubscribe" when you clicked it the last time.

**Comment by leio** [comment]
I am aware of cubicsdr, as I talked and help ZeroChaos on it. And because that upstream started relying on a development version, you can't have the newest version in the current state.

Yes, I am perfectly aware of subslot operators, but these need to be used then properly, things tested, and so on. I don't have reports of this being done as part of this PR. However the development cycle concern remains either way..

GitHub mails are a firehose, I don't read them, nothing to do about subscription (I get them all tucked away in a folder I don't visit outside full mail body searches once in a while).

Please stop being so condescending in your interactions here.

**Comment by stefantalpalaru** [comment]
> Yes, I am perfectly aware of subslot operators, but these need to be used then properly, things tested, and so on.  I don't have reports of this being done as part of this PR.

Well, I did just that with the CubicSDR ebuild in my overlay and everything works as advertised in the documentation. I added the ABI subslot to this PR.

> Please stop being so condescending in your interactions here.

You don't understand the context. I've had CubicSDR in my overlay since December 2015: https://github.com/stefantalpalaru/gentoo-overlay/commits/master/net-wireless/cubicsdr

Two years ago, I contributed a patch upstream to allow using the system RtAudio library instead of the embedded one: https://github.com/cjcliffe/CubicSDR/pull/436

Now what do I see in the main Gentoo tree? An old version of the software using the embedded RtAudio library and with no support for the JACK backend (the one I'm using right now): https://github.com/cjcliffe/CubicSDR/blob/0.2.3/CMakeLists.txt#L256

How am I supposed to react to this comedy of errors?

**Comment by stefantalpalaru** [comment]
I'd rather fix problems on the point of contact instead of trying to change the world. My way leads to up-to-date software being available to those Gentoo users who discovered my overlay.

**Comment by blshkv** [comment]
@leio Gentoo was always knows as a cutting age distro so please push the ebuild. You can hardmask it with comments and not accept any bug reports - this is totally fine. But let users shoot themselves in the foot if this is what they want.

**Comment by ajakk** [comment]
@stefantalpalaru, care to modernize this ebuild and add a mask?

**Comment by stefantalpalaru** [comment]
> care to modernize this ebuild and add a mask?

No. Just use my overlay, like all those other Gentoo developers who need up to date software ;-)

**Pull request closed without merging**
