### PR TITLE
dev-libs/spdlog: New package

### PR DESCRIPTION
**Pull request by stkw0**
Live ebuild is included.

spdlog is a C++ logging library.
Other distributions already have a package for this library.

Gentoo Bug: #592708

### CODE REVIEW

**Comment by victoredwardocallaghan** [comment]
Any news on when this is going to be merged?

**Comment by SoapGentoo** [comment]
@stkw0 I've changed the ebuilds a bit, please do have a look

**Comment by victoredwardocallaghan** [comment]
@stkw0 can you update to the `0.12` release please?

**Comment by stkw0** [comment]
@victoredwardocallaghan of course. I already had it planned, today I will create the PR.

**Comment by victoredwardocallaghan** [comment]
@stkw0 thx I have issues with the current version: I need to copy the `format.h` header from my fedora host in to get a build working. here is the udiff between the working `/usr/include/spdlog/fmt/bundled/format.h` and non-working ` build/usr/include/spdlog/fmt/bundled/format.h` versions:

```
--- /usr/include/spdlog/fmt/bundled/format.h	2016-08-26 07:38:08.000000000 +1000
+++ build/usr/include/spdlog/fmt/bundled/format.h	2016-09-18 09:28:41.000000000 +1000
@@ -1308,19 +1308,25 @@
 };
 
 // For bcc32 which doesn't understand ! in template arguments.
-template<bool>
+template <bool>
 struct Not
 {
     enum { value = 0 };
 };
 
-template<>
+template <>
 struct Not<false>
 {
     enum { value = 1 };
 };
 
-template<typename T, T> struct LConvCheck
+template <typename T>
+struct False
+{
+    enum { value = 0 };
+};
+
+template <typename T, T> struct LConvCheck
 {
     LConvCheck(int) {}
 };
@@ -1340,6 +1346,36 @@
     return "";
 }
 
+#define FMT_CONCAT(a, b) a##b
+
+#if FMT_GCC_VERSION >= 407
+# define FMT_UNUSED __attribute__((unused))
+#else
+# define FMT_UNUSED
+#endif
+
+#ifndef FMT_USE_STATIC_ASSERT
+# define FMT_USE_STATIC_ASSERT 0
+#endif
+
+#if FMT_USE_STATIC_ASSERT || FMT_HAS_FEATURE(cxx_static_assert) || \
+  (FMT_GCC_VERSION >= 403 && FMT_HAS_GXX_CXX11) || _MSC_VER >= 1600
+# define FMT_STATIC_ASSERT(cond, message) static_assert(cond, message)
+#else
+# define FMT_CONCAT_(a, b) FMT_CONCAT(a, b)
+# define FMT_STATIC_ASSERT(cond, message) \
+  typedef int FMT_CONCAT_(Assert, __LINE__)[(cond) ? 1 : -1] FMT_UNUSED
+#endif
+
+template <typename Formatter, typename Char, typename T>
+void format_arg(Formatter &, const Char *, const T &)
+{
+    FMT_STATIC_ASSERT(False<T>::value,
+                      "Cannot format argument. To enable the use of ostream "
+                      "operator<< include fmt/ostream.h. Otherwise provide "
+                      "an overload of format_arg.");
+}
+
 // Makes an Arg object from any type.
 template <typename Formatter>
 class MakeValue : public Arg
@@ -1387,9 +1423,9 @@
     static void format_custom_arg(
         void *formatter, const void *arg, void *format_str_ptr)
     {
-        format(*static_cast<Formatter*>(formatter),
-               *static_cast<const Char**>(format_str_ptr),
-               *static_cast<const T*>(arg));
+        format_arg(*static_cast<Formatter*>(formatter),
+                   *static_cast<const Char**>(format_str_ptr),
+                   *static_cast<const T*>(arg));
     }
 
 public:
@@ -1461,7 +1497,9 @@
 
     FMT_MAKE_VALUE(char *, string.value, CSTRING)
     FMT_MAKE_VALUE(const char *, string.value, CSTRING)
+    FMT_MAKE_VALUE(signed char *, sstring.value, CSTRING)
     FMT_MAKE_VALUE(const signed char *, sstring.value, CSTRING)
+    FMT_MAKE_VALUE(unsigned char *, ustring.value, CSTRING)
     FMT_MAKE_VALUE(const unsigned char *, ustring.value, CSTRING)
     FMT_MAKE_STR_VALUE(const std::string &, STRING)
     FMT_MAKE_STR_VALUE(StringRef, STRING)
@@ -3260,7 +3298,10 @@
     case 'n':
     {
         unsigned num_digits = internal::count_digits(abs_value);
-        fmt::StringRef sep = internal::thousands_sep(std::localeconv());
+        fmt::StringRef sep = "";
+#ifndef ANDROID
+        sep = internal::thousands_sep(std::localeconv());
+#endif
         unsigned size = static_cast<unsigned>(
                             num_digits + sep.size() * ((num_digits - 1) / 3));
         CharPtr p = prepare_int_buffer(size, spec, prefix, prefix_size) + 1;
@@ -3871,7 +3912,6 @@
 #define FMT_ARG_N(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, N, ...) N
 #define FMT_RSEQ_N() 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
 
-#define FMT_CONCAT(a, b) a##b
 #define FMT_FOR_EACH_(N, f, ...) \
   FMT_EXPAND(FMT_CONCAT(FMT_FOR_EACH, N)(f, __VA_ARGS__))
 #define FMT_FOR_EACH(f, ...) \
```

and here is the build error:

```
: In file included from /usr/include/epoxy/glx.h:36:0,
:                  from /var/tmp/portage/app-misc/hyperflow-1.0.0/work/hyperflow-1.0.0/src/VideoStream.cpp:8:
: /usr/include/spdlog/fmt/bundled/format.h:1324:8: error: expected identifier before numeric constant
:  struct False
:         ^
: /usr/include/spdlog/fmt/bundled/format.h:1324:8: error: expected unqualified-id before numeric constant
: In file included from /usr/include/spdlog/fmt/fmt.h:21:0,
:                  from /usr/include/spdlog/common.h:41,
:                  from /usr/include/spdlog/spdlog.h:12,
:                  from /var/tmp/portage/app-misc/hyperflow-1.0.0/work/hyperflow-1.0.0/src/VideoStream.cpp:17:
: /usr/include/spdlog/fmt/bundled/format.h: In function ‘void fmt::internal::format_arg(Formatter&, const Char*, const T&)’:
: /usr/include/spdlog/fmt/bundled/format.h:1373:5: error: expected primary-expression before ‘>’ token
:      FMT_STATIC_ASSERT(False<T>::value,
:      ^
: /usr/include/spdlog/fmt/bundled/format.h:1373:5: error: ‘::value’ has not been declared
:      FMT_STATIC_ASSERT(False<T>::value,
```

**Comment by stkw0** [comment]
Thanks for the report. With the 0.12.0 this is don't occur? The version of spdlog provided by fedora is the 0.10.0?

Anyway, I don't know if a closed PR is the best way to discuss this. Maybe we can talk about it on the IRC (my nick on freenode is "droman", I have time today if you want) or you could open an issue on gentoo bugzilla.

**Pull request closed without merging**
