### PR TITLE
sys-boot/grub: add platform xen_pvh

### PR DESCRIPTION
**Pull request by j-licht**
Package-Manager: Portage-2.3.76, Repoman-2.3.16
RepoMan-Options: --ignore-arches

### CODE REVIEW

**Comment by j-licht** [comment]
> ## Pull request CI report
> _Report generated at_: 2019-10-18 16:38 UTC
> _Newest commit scanned_: [b66b0c9](https://github.com/gentoo/gentoo/commit/b66b0c9337680020159f4a05119373d3e15f443f)
> _Status_:  **broken**
> 
> New issues caused by PR:
> https://qa-reports.gentoo.org/output/gentoo-ci/9620d88/output.html#sys-boot/grub

Need help to fix the dependency problem with ppc and xen-tools.

**Comment by floppym** [comment]
We will need to add some entry in a package.use.mask file somewhere in profiles/. I can take care of that.

I don't think these changes warrant a revbump, so please update your PR to drop that.

**Comment by floppym** [comment]
Also, please update grub-9999.ebuild.

**Comment by j-licht** [comment]
@floppym Do you have any further remarks?

**Pull request closed without merging**
