### PR TITLE
sci-chemistry/easychem: Fix build with clang 16

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/886085

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Comment by thesamesam** [comment]
@AndrewAmmerlaan could you restore the revbump please, we need it for these because it changes the compiler output (it was wrong before, same for all implicit func decl warnings; ditto int conversion here)

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan could you restore the revbump please, we need it for these because it changes the compiler output (it was wrong before, same for all implicit func decl warnings; ditto int conversion here)

Done in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=fc38348bbe30c0140b9d8c5d86cbb44264855cb8

Sorry I thought this was a build-time only fix.

**Comment by thesamesam** [comment]
Thank you! No worries

**Pull request closed without merging**
