### PR TITLE
app-arch/zstd: version bump to 1.2.0-r1

### PR DESCRIPTION
**Pull request by kholk**
Bump the version to 1.2.0-r1 for new major features.

### CODE REVIEW

**Comment by kholk** [comment]
The commit has been forcepushed.
The new version contains USE flags support to enable support for LZMA, LZ4 or both features introduced in the new 1.2.0 version.

**Comment by Amynka** [comment]
@kholk fix please the QA issue you have here. :) And if there are no more QA issues you are free to merge. Approved by Patrick.

**Comment by kholk** [comment]
Updated, waiting for QA check.

**Comment by Amynka** [comment]
Can you please rebase?

**Comment by monsieurp** [comment]
@kholk ping? Feel free to reopen if you're still interested in getting this contribution in the tree.

**Pull request closed without merging**
