### PR TITLE
mail-client/evolution, gnome-extra/evolution-data-server, gnome-extra/evolution-data-ews: Version bump to 3.48.0

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
In evolution-data-server:

````diff
-                       webkit2gtk-5.0>=${webkit2gtk4_minimum_version}
+                       webkitgtk-6.0>=${webkit2gtk4_minimum_version}
````

Kind of a bit missing dependency...

**Comment by flint2** [comment]
> In evolution-data-server:
> 
> ```diff
> -                       webkit2gtk-5.0>=${webkit2gtk4_minimum_version}
> +                       webkitgtk-6.0>=${webkit2gtk4_minimum_version}
> ```
> 
> Kind of a big missing dependency...

Ouch...
I have webkitgtk in another branch (https://github.com/flint2/gentoo/tree/gnome-console-beta) together with all his dependencies and libadwaita dependencies, should I drop this PR and merge all together in one branch? 
Or separate webkitgtk and libadwaita and somehow indicate in dependent PRs that are required?
Thanks!

**Comment by mattst88** [comment]
It's fine to leave it open. I can just merge it after webkit-gtk:6 goes in via another PR.

**Comment by mattst88** [comment]
I'll try to add webkit-gtk:6 today, unless you have it already.

**Comment by mattst88** [comment]
> Also I can´t compile last version 2.39.91

Same here. Compile error about a missing header.

**Comment by flint2** [comment]
> > Also I can´t compile last version 2.39.91
> 
> Same here. Compile error about a missing header.

Builds OK against dev version: webkit-gtk-2.39.7-r600 (https://github.com/gentoo/gentoo/commit/c2347daca46ae9b6c87a5d1b815508de3e324b83)

**Comment by flint2** [comment]
3.48.0 is out

**Pull request closed without merging**
