### PR TITLE
ros-catkin.eclass: don't set KEYWORDS in eclass and fix live ebuilds

### PR DESCRIPTION
**Pull request by hasufell**
Gentoo-Bug: 562464

@aballier

### CODE REVIEW

**Comment by aballier** [comment]
this makes live & release ebuilds differ, so certainly not an option

as I told you, the only maintainable way is to duplicate the if/then/else for live vs non live; but then, in the default case (aka all cases in tree), eclass decides what is a live ebuild and what is not, so this would actually rely on an a priori private behavior of the eclass...

**Comment by hasufell** [comment]
> this makes live & release ebuilds differ, so certainly not an option

I cannot follow, why?

**Comment by aballier** [comment]
because live ebuilds track default branch, releases are cut from default branch, so release ebuilds are copied from live ebuilds

this is the workflow I've found to work best, and if you have a look at the tree, you'll find a lot of ebuilds maintained that way

**Comment by hasufell** [comment]
> so release ebuilds are copied from live ebuilds

Then you need to fix your scripts. You can easily adjust the KEYWORDS for live ebuilds after copying with sed. Do you need help there?

**Comment by hasufell** [comment]
example
```sh
sed \
    -e 's/^KEYWORDS=.*/KEYWORDS=""/' \
    dev-ros/pcl_ros/pcl_ros-1.3.0.ebuild > dev-ros/pcl_ros/pcl_ros-9999.ebuild
```

**Comment by hasufell** [comment]
oh sorry, I misread, you do it the other way around

**Comment by aballier** [comment]
I don't need scripts for this, it is just the same reason we use ${P}, ${PV} etc. in ebuilds instead of sedding them on bump: We have bash, we use it.

**Comment by hasufell** [comment]
> I don't need scripts for this, it is just the same reason we use ${P}, ${PV} etc. in ebuilds instead of sedding them on bump: We have bash, we use it.

That doesn't make any sense. We use sed all over the place, in ebuilds, in eclasses and in the PM even.

If you workflow causes trouble (and it does), then we need to do something about it. Writing a proper function for this would also help others with avoiding these hacks.

**Comment by hasufell** [comment]
Don't get me wrong... I just want to help and I think we can reasonably do this without breaking anyones workflow.

**Comment by aballier** [comment]
> That doesn't make any sense. We use sed all over the place, in ebuilds, in eclasses and in the PM even.

This comment doesn't make any sense to me, or makes me think you're confusing totally different things. Of course, sed is a very useful tool, used everywhere, but almost nobody uses it for bumping ebuilds...

> If you workflow causes trouble (and it does), then we need to do something about it. Writing a proper function for this would also help others with avoiding these hacks.

It triggers a false-positive in a QA check. "trouble" and "hacks" seem a bit exagerated to me :)

> Don't get me wrong... I just want to help and I think we can reasonably do this without breaking anyones workflow.

You helped greatly by checking that 'unset KEYWORDS' is ok and reporting the warning. Why not stick with that?

If 'unset KEYWORDS' is ok, but 'KEYWORDS=""' triggers a QA warning, since both cases will result in the exact same behavior of bash I think, I blame the QA check for having false-positives :)

**Comment by hasufell** [comment]
> This comment doesn't make any sense to me, or makes me think you're confusing totally different things. Of course, sed is a very useful tool, used everywhere, but almost nobody uses it for bumping ebuilds...

Well, your comment sounds similarly confused. There's no logical reason to not use sed for bumping. It's a common tool, which was my point. Do you have a problem with sed?

example function (draft):
```sh
copy_from_live_ebuild() {
	# usage:
	#  copy_from_live_ebuild app-misc/foo-1.2 app-misc/foo-1.3
	#
	# this will use the live ebuild app-misc/foo-9999 as a basis,
	# use the KEYWORDS variable from app-misc/foo-1.2 and save
	# the result in app-misc/foo-1.3

	die() {
		echo "$@"
		return
	}

	local old_ver=$1
	local new_ver=$2
	local cat=$(qatom ${old_ver} | awk '{ print $1 }')
	local pn=$(qatom ${old_ver} | awk '{ print $2 }')
	local old_ebuild="${cat}/${pn}/${old_ver##*/}.ebuild"
	local new_ebuild="${cat}/${pn}/${new_ver##*/}.ebuild"
	local live_ebuild="${cat}/${pn}/${pn}-9999.ebuild"

	[[ -e ${old_ebuild} ]] || die "${old_ebuild} does not exist!"
	[[ -e ${live_ebuild} ]] || die "${live_ebuild} does not exist!"
	[[ -e ${new_ebuild} ]] && die "${new_ebuild} already exists!"

	# set KEYWORDS
	eval $(grep -e '^KEYWORDS=.*' ${old_ebuild})

	local new_keywords=$(for i in ${KEYWORDS} ; do echo "~${i#\~} " ; done)

	# copy ebuilds
	sed \
		-e "s|^KEYWORDS=.*|KEYWORDS=\"$(echo ${new_keywords})\"|" \
		"${live_ebuild}" > "${new_ebuild}" || die "copying ebuild failed!"

	unset KEYWORDS
}
```

**Comment by hasufell** [comment]
> If 'unset KEYWORDS' is ok, but 'KEYWORDS=""' triggers a QA warning, since both cases will result in the exact same behavior of bash I think, I blame the QA check for having false-positives :)

This is not just about QA warnings, but also about readability of ebuilds.

**Comment by aballier** [comment]
> Well, your comment sounds similarly confused. There's no logical reason to not use sed for bumping. It's a common tool, which was my point. Do you have a problem with sed?

Do you use sed for bumping your packages?
Except for texlive, for which I use scripts an order of magnitude more complex than match'n'replace, I don't, and so far I don't see a reason to.
And again, let alone the code duplication, having:
```
if not_live_ebuild ; then
   KEYWORDS="something"
else
  KEYWORDS=""
fi
```

in ebuilds is much nicer to have than any magical script that would depend on package workflow.

> This is not just about QA warnings, but also about readability of ebuilds.

Readability is very subjective and at maintainer's discretion usually :)

**Comment by hasufell** [comment]
> Do you use sed for bumping your packages?

I bump my packages properly, which means I don't use _any_ script for that and I don't do code-duplication or add misleading variables, just because I am lazy :)

> And again, let alone the code duplication, having: [...] in ebuilds is much nicer to have than any magical script that would depend on package workflow.

Exactly: it is useless code duplication and is similarly annoying like C code full of ifdefs. But if you like code duplication, I can certainly convert all the ebuilds with a single sed line.

> If 'unset KEYWORDS' is ok, but 'KEYWORDS=""' triggers a QA warning, since both cases will result in the exact same behavior of bash I think, I blame the QA check for having false-positives :)

It's not the PMs job to think of exceptions for a sane QA rule and do tons of checks in order to determine if something _actually_ breaks. QA rules should be simple. And this one is easy to enforce, so I think the PM is absolutely correct to report this.

**Comment by aballier** [comment]
> I bump my packages properly, which means I don't use any script for that and I don't do code-duplication or add misleading variables, just because I am lazy :)
[...]
> Exactly: it is useless code duplication and is similarly annoying like C code full of ifdefs. But if you like code duplication, I can certainly convert all the ebuilds with a single sed line.

I do not like code duplication nor do I use custom sed scripts for bumping. Hence the code is how it is currently. You're trying to force your scripts on me, or code duplication, and I don't think you'll end up maintaining said packages...

> It's not the PMs job to think of exceptions for a sane QA rule and do tons of checks in order to determine if something actually breaks. QA rules should be simple. And this one is easy to enforce, so I think the PM is absolutely correct to report this.

inherit() behavior wrt to variables is perfectly defined by PMS. PM role is just to execute this behavior.


Now, QA rule is not to define KEYWORDS within eclasses, which I completely agree with and believe should be better enforced because it is a complete mess to keyword packages whose KEYWORDS are defined in an eclass...
However, the case at hand is just about providing an easy to use API for eclass consumers to have live ebuilds without having code duplication nor having to use custom scripts for day to day maintainance. No KEYWORDS is ever defined in the eclass, but rather unset to avoid carrying the if/then/else everywhere.


Finally, please provide *concrete* examples or arguments when making claims that something might break or someone is lazy.

**Comment by hasufell** [comment]
> Finally, please provide concrete examples or arguments when making claims that something might break or someone is lazy.

The reason you introduced this hackery is that you don't want to edit a single line of code after copying an ebuild.

I provided you:
* a complete PR to fix the issue
* a script that automates editing the _single_ line of code, if you really think that is too much to do manually (which I could see if you have to bump hundreds of packages at once)

You seem not to be interested in either and just keep status quo.

I don't know what you call that, I'd call it laziness. And laziness is a good thing (really), until it collides with QA.

**Comment by aballier** [comment]
Lazyness would be to let you commit this, without trying to understand nor fixing the underlying issue :)

Now, I still fail to understand why you call this hackery. Could you please elaborate on this?
Again, this does not rely on any undefined behavior. Uncommon, yes, but so far, the other options have not been convincing.

**Comment by hasufell** [comment]
> Lazyness would be to let you commit this, without trying to understand nor fixing the underlying issue :)

That would be poor QA, which is why this PR exists ;)

> Now, I still fail to understand why you call this hackery.

Because it
* confuses the casual ebuild reader
* breaks the casual ebuild grep
* is very uncommon and because of that increases chances someone messes up (not you, probably)
* causes QA warnings

**Comment by aballier** [comment]
> confuses the casual ebuild reader

maybe it would help by documenting this better in the eclass ?

> breaks the casual ebuild grep

as much as classical if/then/else
tools that implement proper ebuild parsing get it right

> is very uncommon and because of that increases chances someone messes up (not you, probably)

documentation could help understanding it better
but if you declare KEYWORDS after inherit, it will overwrite it, so nothing will be messed up

> causes QA warnings

I think we discussed this at length :)

**Comment by hasufell** [comment]
> maybe it would help by documenting this better in the eclass ?

It would help doing it properly.

> as much as classical if/then/else

Exactly, which is why I don't use them either for live ebuilds, since that is just plain code duplication.

> documentation could help understanding it better

Instead of documenting hacks, we should remove them. What's the purpose of increasing complexity here? Should we introduce an eclass-pitfall section in the wiki or remove the pitfalls?

**Comment by aballier** [comment]
> It would help doing it properly.

Yes, and I think all the other options at hand (bump script, or if/then/else in each ebuild) are worse.
Do we have any other option here?

**Comment by hasufell** [comment]
Fixing the QA warning alone can be done with an indirection variable like ROS_KEYWORDS which is then used to set the actual KEYWORDS variable in the ebuild. But that will not fix the indirection in the first place, which is the worst part about this and a hidden state change.

I don't understand your problem with a bump script. Why is that so bad?

**Comment by hasufell** [comment]
btw... however this turns out, we sure had a lot of fun ;)

**Comment by aballier** [comment]
> Fixing the QA warning alone can be done with an indirection variable like ROS_KEYWORDS which is then used to set the actual KEYWORDS variable in the ebuild. But that will not fix the indirection in the first place, which is the worst part about this and a hidden state change.

I think I thought about it at the beginning, but discarded it for this reason. From a "do not confuse readers" perspective, I found it worse. But if your sole purpose is to fix the QA warning (instead of the actual check), why not.

> I don't understand your problem with a bump script. Why is that so bad?

Added complexity for no gain. And goes against the Gentoo way of having ebuild names giving $PV & friends to be used as readonly variables in the ebuild so that ebuild maintainance is made easier by minimizing diff between versions.

**Comment by hasufell** [comment]
> Added complexity for no gain. And goes against the Gentoo way of having ebuild names giving $PV & friends to be used as readonly variables in the ebuild so that ebuild maintainance is made easier by minimizing diff between versions.

It removes ebuild complexity. And I don't really understand what you mean with $PV & friends being readonly variables and how that is possibily related to a script that just modifies KEYWORDS.

**Comment by aballier** [comment]
> It removes ebuild complexity.

I don't care about one-time complexity. I do care about every time I bump something complexity.

> And I don't really understand what you mean with $PV & friends being readonly variables and how that is possibily related to a script that just modifies KEYWORDS.

eclass says: PV = 9999 implies live ebuild. Policy says: live ebuild implies empty keywords.
eclass provides an optional safe guard by unsetting KEYWORDS when doing live ebuild in case you want to avoid code duplication by setting your keywords before inherit.

**Comment by hasufell** [comment]
> I don't care about one-time complexity. I do care about every time I bump something complexity.

how is `cp foo bar` different from `bump-script foo bar`

> eclass says: PV = 9999 implies live ebuild. Policy says: live ebuild implies empty keywords.
> eclass provides an optional safe guard by unsetting KEYWORDS when doing live ebuild in case you want to avoid code duplication by setting your keywords before inherit.

I still don't see how that is related to the bump script.

**Comment by aballier** [comment]
> how is cp foo bar different from bump-script foo bar?

It differs from every other ebuild in the tree and is thus way too much prone to errors (e.g. being forgotten)...
If you can convince people to use your 'bump-script' because it has clear advantages (or better, fix ebump and get it widely used), then I might reconsider. So far, this just seems you're trying to impose your ways by claiming a false-positive QA warning is the end of the world.

> I still don't see how that is related to the bump script.

It is not and is not meant to be. Let's start from the beginning then: Could you please explain me what is missing betwen "eclass says: PV = 9999 implies live ebuild" and "Policy says: live ebuild implies empty keywords" ?

PS: How the **** can we do proper comment quoting here ? So far I've been copy/pasting and adding '>'  but it is annoying...

**Comment by hasufell** [comment]
> It differs from every other ebuild in the tree and is thus way too much prone to errors (e.g. being forgotten)...
> If you can convince people to use your 'bump-script' because it has clear advantages (or better, fix ebump and get it widely used), then I might reconsider. So far, this just seems you're trying to impose your ways by claiming a false-positive QA warning is the end of the world.

So far, it seems to me you are not only unwilling to accept any help or deviate 1 bit from your broken workflow which causes eclass and ebuild complexity, confuses developers and causes QA warnings, but you are also unable to give any logical reasons for not using the proposed bump script, except something that sounds like "I like mine better".

I'm certainly not going to convince 200 developers to use my script (why should I care?), so that you have your reason to use it.

This is really far from being rationale, so it seems like discussion here is impossible.

**Comment by aballier** [comment]
I don't think there can be any logical reason for using or not using your bump script: It is like vim vs emacs. Best I can say is: I'm used to some workflow, I am efficient with it, and the chances of messing up are much lower than with a brand new one. Also, believe me, when we're talking of 400+ packages, proper workflow is the key, so yeah, deviating from it is not something to take lightly.

You have your reasons to prefer sedding live ebuilds when bumping a new version, which I respect and am not trying to take a QA hammer to make you change, but I find it way too much error prone. I have mine to keep live & release ebuilds identical. You might find them error prone or confusing. But in the end, "error prone" or "confusing" is just a matter of what you're used to...

**Comment by hasufell** [comment]
> I don't think there can be any logical reason for using or not using your bump script: It is like vim vs emacs.

Comparing a script solution (that has the same use pattern as `cp`) for a concrete QA issue (QA team told you it's an issue) with editor war is really far-fetched. You arguments are getting more and more exotic.

> You have your reasons to prefer sedding live ebuilds when bumping a new version, which I respect and am not trying to take a QA hammer to make you change, but I find it way too much error prone.

As I already said, I don't use any scripts to bump ebuilds.

> I have mine to keep live & release ebuilds identical. You might find them error prone or confusing. But in the end, "error prone" or "confusing" is just a matter of what you're used to...

Yeah, seems you are used to confusing APIs.

And I understand now that you don't care about code-complexity (which you interestingly called _one-time complexity_), clean code, readability or QA issues, as long as everything works.

**Pull request closed without merging**
