### PR TITLE
media-gfx/exif: update HOMEPAGE

### PR DESCRIPTION
**Pull request by fturco**
Signed-off-by: Francesco Turco <fturco@fastmail.fm>

### CODE REVIEW

**Comment by fturco** [comment]
I realized I don't have enough technical knowledge for properly bumping an ebuild to `EAPI=7`. So I decided to only fix `HOMEPAGE` for now.

**Comment by a17r** [comment]
> I realized I don't have enough technical knowledge for properly bumping an ebuild to `EAPI=7`. So I decided to only fix `HOMEPAGE` for now.

There's a good read: https://blogs.gentoo.org/mgorny/2018/05/03/the-ultimate-guide-to-eapi-7/

**Comment by fturco** [comment]
@a17r Thanks for the link. Added to my todo list!

**Comment by a17r** [comment]
See also: c5797f46441ad82e64b941c5fe426da84e351cf0

**Pull request closed without merging**
