### PR TITLE
dev-libs/spdlog: fix compilation error 

### PR DESCRIPTION
**Pull request by stkw0**
The patch was wrong which, in some cases, caused a compilation error.

### CODE REVIEW

**Comment by a17r** [comment]
Thanks for your work. Re commit messages, I notice:
- Repoman blurb is missing, do you not use `repoman commit`?
- first commit summary is in plural, despite only one old ebuild is removed. Maybe just say `drop 0.17.0`

**Comment by stkw0** [comment]
> Thanks for your work. Re commit messages, I notice:
> 
>     * Repoman blurb is missing, do you not use `repoman commit`?
> 
>     * first commit summary is in plural, despite only one old ebuild is removed. Maybe just say `drop 0.17.0`

No, I run `repoman -dx full` and if it's ok I do the commit with git commit manually. I suppose I should start using repoman commit.

**Comment by a17r** [comment]
if you start using it this also automatically adds the signoff you configured in make.conf

**Comment by stkw0** [comment]
I've also linked an old bug (not specifically related with this PR, but in their moment I forgot to link it)

**Pull request closed without merging**
