### PR TITLE
sys-apps/s6-linux-init: New package

### PR DESCRIPTION
**Pull request by atlaua**
s6-linux-init is a tool to ease the creation of /sbin/init executables
for s6-based init systems.

### CODE REVIEW

**Comment by atlaua** [comment]
For reference, here are some comments that got lost because I force-pushed an updated commit:

polynomial-c wrote:
> The whole DEPEND variable can be reduced to this one-liner:
>-
> `DEPEND=">=dev-libs/skalibs-2.3.8.0[static-libs=]"`--
>-
> See https://devmanual.gentoo.org/general-concepts/dependencies/index.html section "Built with USE dependencies".

Thanks. I'm aware of this syntax, but I don't see how it applies here;
I need to depend on [static-libs] if USE=static is enabled;
[static-libs=] would be conditional on USE=static-libs which doesn't
even exist in this ebuild.

Or am I doing something wrong? I've copied the whole dependency syntax
from sys-apps/s6.

**Comment by idella** [comment]
atlaua think if you care for the same request to be made to WilliamH. Your call really

**Comment by monsieurp** [comment]
@williamh @gentoo/proxy-maint

**Comment by williamh** [comment]
Using a use flag to pull in optional runtime dependencies is a qa violation [1], so we have two choices -- make them hard runtime dependencies, or drop the runtime? ( ... ) section of the dependencies and the runtime use flag.

[1] https://devmanual.gentoo.org/general-concepts/use-flags/index.html

**Comment by williamh** [comment]
Correction to the last comment: The only valid choice from the manual is to add some information to pkg_postinst if it is needed; we should remove the runtime use flag and the dependencies that depend on it.

**Comment by atlaua** [comment]
I've just pushed an updated ebuild without the "runtime" useflag.

**Comment by williamh** [comment]
I thoughtabout this further, and this seems to be a good case for PDEPEND.
I suggest putting the dependencies the generated binary requires in PDEPEND without a use flag.

**Comment by atlaua** [comment]
Isn't PDEPEND just for breaking dependency cycles? If anything, I'd add
those deps to RDEPEND.

But I'm reluctant to add them unconditionally, as they're not required
to run s6-linux-init itself, just for the scripts it generates. For
example, if someone uses s6 only on an embedded machine, they might
like to use s6-linux-init on their desktop, but won't need s6 there.

**Comment by williamh** [comment]
Anything listed in RDEPEND is supposed to be needed for the package 
itself to run, so if they are not required for s6-linux-init to run, 
RDEPEND isn't where they should be placed
I wasn't aware of the ability to use s6-linux-init separately from s6, 
but given that, I don't think we should attempt to install the 
dependencies the generated binary requires.

**Comment by williamh** [comment]
This has been accepted. :-)

**Pull request closed without merging**
