### PR TITLE
media-sound/pulseaudio - Fix bugs 627894, 646566, 655432, 656704

### PR DESCRIPTION
**Pull request by a17r**
Tired of waiting for pulseaudio-12.

### CODE REVIEW

**Comment by leio** [comment]
Depends are probably sorted per occurrence in configure.ac and they shouldn't be pointlessly sorted lexically.

**Comment by a17r** [comment]
> Depends are probably sorted per occurrence in configure.ac and they shouldn't be pointlessly sorted lexically.

Autobiographical at best. I've randomly checked 3 use flags.

**Comment by a17r** [comment]
I can keep it in fuzzy order if you prefer it like that, I'll certainly not go over configure.ac...

**Comment by a17r** [comment]
> others I have not reviewed, but apparently 5 days is a timeout to PR review

glibc and flat-volumes bugs are months old with fixes that I just picked up from there, and on *Qt5 deps I'm going to assume some competence...

Leaving the DEPEND sorting commit for QA consideration, beyond that I'm going to forget about pulseaudio again...

**Comment by a17r** [comment]
This chance for sane ordering came... and went.

**Pull request closed without merging**
