### PR TITLE
media-video/vlc: Version bump to 2.2.2

### PR DESCRIPTION
**Pull request by jok-ts**
Gentoo bug: #574064

### CODE REVIEW

**Comment by idella** [comment]
maintainer for vlc in bugzilla is sdnick484@gmail.com

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by jok-ts** [comment]
So the rebase picked a couple of hundred existing commits here.

**Comment by floppym** [comment]
It look like you accidentally created a merge commit (08287b2). You should reset to your parent 6835f7a, and do a rebase this time.

If you can't figure that out, start over from a clean copy of the repository and repeat your changes.

**Comment by jok-ts** [comment]
It should be properly rebased now.

**Comment by jok-ts** [comment]
Nevermind, fixed in commit fe5dc79e

**Pull request closed without merging**
