### PR TITLE
app-text/tree: add 2.0.4

### PR DESCRIPTION
**Pull request by capezotte**
This version fixes the "strverscmp.o twice" oversight that causes the linked bug.

The original SRC_URI seems to no longer work (at least on my network, the download never actually starts), so I've changed it to the Gitlab mirror (which the author plans to make the definitive location in the future).

Closes: https://bugs.gentoo.org/869893
Signed-off-by: Carlos Eduardo <carana2099@gmail.com>

### CODE REVIEW

**Comment by xgqt** [comment]
Since mama.indstate.edu vanished(?) I think this is a good replacement.

**Comment by capezotte** [comment]
It didn't, but a footnote says it might soon.

Anyhow, the major reason I changed the SRC_URI is the original link didn't work for me -- trying to `curl` it (or the HTTP version) just made the ebuild hang. I then changed the HOMEPAGE for consistency. Strangely, http://mama.indstate.edu/users/ice opens just fine.

**Comment by xgqt** [comment]
> 

It does not for me :shrug:

**Comment by jonasstein** [comment]
I saw this PR too after I did the version bump. Sorry and thank you for your PR.

**Pull request closed without merging**
