### PR TITLE
dev-python/{PyQt6,PyQt6-WebEngine}: Remove qmake g++ hack

### PR DESCRIPTION
**Pull request by vimproved**
This appears to no longer be necessary, I've verified that it builds without the hack with both clang and gcc. This also removes the dependency on gcc.

### CODE REVIEW

**Comment by ionenwks** [comment]
Doesn't seem to have changed:
```
Generating the Makefiles...
/usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro
gpep517: '/usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
Project ERROR: Cannot run compiler 'g++'. Output:
===================
===================
Maybe you forgot to setup the environment?
 * ERROR: dev-python/PyQt6-WebEngine-6.5.0::gentoo failed (compile phase):
 *   Wheel build failed
```

Also fails if g++ is symlinked to clang++ given it's trying to parse output:
```
gpep517: '/usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
Info: creating stash file /tmp/portage/dev-python/PyQt6-WebEngine-6.5.0/temp/tmph4qffy72/.qmake.stash
Project ERROR: failed to parse default search paths from compiler output
```

**Comment by ionenwks** [comment]
> This also removes the dependency on gcc.

Do you mean you've managed to build these without gcc installed? I still can't, it does use clang to build but qmake uses g++ for some detection stuff and fails if it's not there.

Technically this hack would belong in qmake-utils.eclass if anything (+ gcc dep), about all qmake packages have that problem.

**Comment by vimproved** [comment]
> > This also removes the dependency on gcc.
> 
> Do you mean you've managed to build these without gcc installed? I still can't, it does use clang to build but qmake uses g++ for some detection stuff and fails if it's not there.
> 
> Technically this hack would belong in qmake-utils.eclass if anything (+ gcc dep), about all qmake packages have that problem.

Yes, building works for me on my musl/llvm system without GCC installed. No idea what the difference is. I've also had someone using GCC confirm that it builds on their machine.

**Comment by vimproved** [comment]
> Doesn't seem to have changed:
> 
> ```
> Generating the Makefiles...
> /usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro
> gpep517: '/usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
> Project ERROR: Cannot run compiler 'g++'. Output:
> ===================
> ===================
> Maybe you forgot to setup the environment?
>  * ERROR: dev-python/PyQt6-WebEngine-6.5.0::gentoo failed (compile phase):
>  *   Wheel build failed
> ```
> 
> Also fails if g++ is symlinked to clang++ given it's trying to parse output:
> 
> ```
> gpep517: '/usr/lib64/qt6/bin/qmake -recursive PyQt6-WebEngine.pro' failed returning 3
> Info: creating stash file /tmp/portage/dev-python/PyQt6-WebEngine-6.5.0/temp/tmph4qffy72/.qmake.stash
> Project ERROR: failed to parse default search paths from compiler output
> ```

That's really odd. Here's my build.log and emerge --info output for dev-python/PyQt6-WebEngine if it helps at all:
`emerge --info dev-python/PyQt6-WebEngine`: https://bpa.st/LEZDK
build.log: https://bpa.st/3KTIE

**Comment by vimproved** [comment]
This is with `sys-devel/clang-toolchain-symlinks` installed without the gcc-symlinks use flags by the way.

**Comment by ionenwks** [comment]
Hm, I see now. It requires qtbase to have been built with clang to work -- it hardcodes what to use (g++ or clang++, ignores CXX on current package either way). Unsure if qt5 does the same.

Albeit the hack is still needed anyway to respect CHOST and ensure it reads the right paths. But the dependency is not strictly required and hack could be changed to do both g++ and clang++ symlinks and be optimistically non-fatal if not found.

I'll go ahead and update it myself.

**Comment by vimproved** [comment]
I see, that makes sense. Thanks for clarifying.

**Comment by ionenwks** [comment]
And thanks for bringing to my attention, this will be an improvement.

**Pull request closed without merging**
