### PR TITLE
www-apps/netbox: bump version to 2.9.7 with bumped dependencies versions refs #750836

### PR DESCRIPTION
**Pull request by xakrume**
https://bugs.gentoo.org/750836

### CODE REVIEW

**Comment by thesamesam** [comment]
Please fix CI failure and add the GCO sign off.

**Comment by DefauIt** [comment]
I'll try, thnx!

**Comment by DefauIt** [comment]
Commit was sent erroneously.
missed and sent to the wrong place
sorry

**Comment by arkamar** [comment]
The package was last-rited and removed from the tree, see commit 425b5090d422 - `www-apps/netbox: Remove last-rited pkg`. This PR is obsolete, its successor #19948 was also closed.

**Pull request closed without merging**
