### PR TITLE
kde-frameworks/ki18n: Add PYTHON_COMPAT=python3_5

### PR DESCRIPTION
**Pull request by a17r**
works for me, tests ok.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by idella** [comment]
Attempting a runtest, this pulled up in src_configure with

```bash
CMake Warning at CMakeLists.txt:7 (find_package):
  Could not find a configuration file for package "ECM" that is compatible
  with requested version "5.22.0".

  The following configuration files were considered but not accepted:

    /usr/share/ECM/cmake/ECMConfig.cmake, version: 5.21.0
-- 
 * ECM (required version >= 5.22.0) , Extra CMake Modules. , <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>
```

So at this point, is this covered by $(add_qt_dep qtscript)? At a brief glance it looks not, but qt being a specialty I still have not fully taken on, I do not know.

**Comment by idella** [comment]
On updating that package, it built fine

 $ PYTHON_SINGLE_TARGET=python3_5 ebuild ki18n-5.22.1.ebuild clean install
 yielded

#!/usr/bin/env python3.5
for ts-pmap-compile.py which only means the python eclass works.
This is fine at ebuild level:  build install.  The real test is runtime.

**Comment by idella** [comment]
Once the issue over whether extra-cmake-modules required version >= 5.22.0 is resolved, i can add this it being an issue of adding a python vn. to PYTHON_COMPAT

**Comment by johu** [comment]
Thanks, picked and pushed.

**Pull request closed without merging**
