### PR TITLE
dev-lang/mono-basic: New package

### PR DESCRIPTION
**Pull request by ConiKost**
dev-lang/mono-basic: New package

Needed by: https://bugs.gentoo.org/651396

Closes: https://bugs.gentoo.org/651394

See for reference: https://bugs.gentoo.org/569252

### CODE REVIEW

**Comment by ConiKost** [comment]
@Zlogene: Since you were so kind to review my prog-express eBuild, could you have also here a look? This is a needed dependency for prog-express.

**Comment by Zlogene** [comment]
I am neither mono user nor ebuild writer
@gentoo/dotnet, please comment on this.

**Comment by mpkh** [comment]
on it

**Comment by mpkh** [comment]
merged, thanks!

**Pull request closed without merging**
