### PR TITLE
net-im/telegram-desktop, media-libs/tg_owt: Resolve missing dependencies

### PR DESCRIPTION
**Pull request by mid-kid**
"oops"

### CODE REVIEW

**Comment by wellWINeo** [comment]
i manually installed glibmm and still have error that the cmake can't find it. Is it building successful on your system?

**Comment by mid-kid** [comment]
@wellWINeo Install dev-cpp/glibmm:2, specificially SLOT 2.

**Comment by gyakovlev** [comment]
I'll merge it with some fixes asap, but you should start using repoman or pkgcheck (recommended) to check your work before committing. just run `pkgcheck scan --commits` on the branch before pushing, it'll print some messages, especially that `RDEPEND` was modified without revbump.

we can't change `RDEPEND` without a revision bump. that's because users who already have telegram installed with improper `RDEPEND` will never get an updated ebuild until it's bumped, because version does not change.
so portage will technically allow removing libXtst and glibmm:2 from the system if nothing else requires it, breaking telegram.

yeah, it sucks that with -r1 users will have to rebuild it, but it's the preferred way.

**Comment by mid-kid** [comment]
I see. That makes sense, though it isn't the most obvious thing. I'll be more careful about `RDEPEND` in the future. I don't mind using something to check my changes, so I'll just use whatever you recommend, but I sort of expected the qa-bot to do the same...

**Pull request closed without merging**
