### PR TITLE
dev-java/commons-beanutils: Snapshot 1.9.4_p20211229

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

The intention for using a recent snapschot was to get rid of these failures, but it failed.  Still happens with `openjdk-11`.
I'll keep it in `draft` mode.
```
There were 8 failures:
1) testPropertyUtilsBean_descriptorsCache_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
2) testPropertyUtilsBean_mappedDescriptorsCache_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
3) testMappedPropertyDescriptor_MappedMethodReference1(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
4) testMappedPropertyDescriptor_MappedMethodReference2(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
5) testLocaleConvertUtilsBean_converters_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
6) testWrapDynaClass_dynaClasses_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
7) testMethodUtils_cache_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
8) testConvertUtilsBean_converters_memoryLeak(org.apache.commons.beanutils2.memoryleaktests.MemoryLeakTestCase)
# java.lang.OutOfMemoryError: Java heap space: failed reallocation of scalar replaced objects
```

### CODE REVIEW

**Comment by vaukai** [comment]
Draft mode, should find a way to avoid that long list in `JAVA_TEST_RUN_ONLY`.

**Comment by fordfrog** [comment]
what test failures exactly?

**Comment by vaukai** [comment]
> what test failures exactly?

@fordfrog 
It allows to get rid of the snippet below that we presently need to have in `commons-beanutils-1.9.4-r1.ebuild`.
```
	local vm_version="$(java-config -g PROVIDES_VERSION)"
	if [[ "${vm_version}" == "11" ]] ; then
		JAVA_TEST_EXCLUDES+=( "org.apache.commons.beanutils.memoryleaktests.MemoryLeakTestCase" )
	fi
```

**Comment by vaukai** [comment]
> what test failures exactly?

See the updated comment in the `ebuild`.

**Pull request closed without merging**
