### PR TITLE
dev-vcs/git-cola: add 4.6.1

### PR DESCRIPTION
**Pull request by bearsh**
Add pyqt5 pyqt6 pyside2 pyside6 which selects the desired qt backend. this backend is then forced to be used by patching the binaries.

Bug: https://bugs.gentoo.org/926353

### CODE REVIEW

**Comment by bearsh** [comment]
> Add pyqt5 pyqt6 pyside2 pyside6 which selects the desired qt backend. this backend is then forced to be used by patching the binaries.

I'm not sure if this is desired / the gentoo way of doing it but makes it possible to select the backend even if multiple backends are installed

**Comment by stkw0** [comment]
For me the approach you propose for the backend is okay. btw why the dev-python/QtPy dependency is duplicated in RDEPEND and BDEPEND?

**Comment by bearsh** [comment]
> btw why the dev-python/QtPy dependency is duplicated in RDEPEND and BDEPEND?

AFAIK it is needed to run tests

**Comment by bearsh** [comment]
> ## Pull request CI report
> _Report generated at_: 2024-03-07 13:07 UTC _Newest commit scanned_: [8cb4d22](https://github.com/gentoo/gentoo/commit/8cb4d226ebb52d0a22d4bb4bcb7360a8d8b26a1c) _Status_: ❌ **broken**
> 
> New issues caused by PR: https://qa-reports.gentoo.org/output/gentoo-ci/ca29da5267/output.html#dev-vcs/git-cola
> 
> There are existing issues already. Please look into the report to make sure none of them affect the packages in question: https://qa-reports.gentoo.org/output/gentoo-ci/ca29da5267/output.html

does anyone know how to solve this? is it required to mask useflags on mentioned profiles?

**Comment by stkw0** [comment]
It seems to be due to pyqt6 and pyside6 are masked by default, and unmasked on amd64. So either:
- We remove ~x86 keyword from git-cola
- We mask pyqt6 and pyside6, or add `amd64? () ` around pyqt6 and pyside6. I thought we could add `!amd64? ( !pyqt6 !pyside6 )` to REQUIRED_USE but that doesn't seems to work :(

btw, I guess we could remove version 4.1.0 as we already have 4.2.1-r1 in stable

**Comment by juippis** [comment]
They should be available on x86 now, but I wonder if we should simplify the ebuild based on our Qt policies:
https://wiki.gentoo.org/wiki/Project:Qt/Policies#Requires_one_of_two_Qt_versions

**Comment by bearsh** [comment]
closing in favor of #38550

**Pull request closed without merging**
