### PR TITLE
sci-libs/rocSOLVER: restrict to dev-libs/libfmt-8

### PR DESCRIPTION
**Pull request by littlewu2508**
Closes: https://bugs.gentoo.org/866839

### CODE REVIEW

**Comment by littlewu2508** [comment]
@AndrewAmmerlaan Please try whether this patch can fix the issue at https://bugs.gentoo.org/866839

**Comment by heroxbd** [comment]
Missing GCO sign-off

**Comment by littlewu2508** [comment]
> Missing GCO sign-off

Fixed.

Seems that I forgot to change the default config for pkgdev on this machine.

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan Please try whether this patch can fix the issue at https://bugs.gentoo.org/866839

Yes! This fixes the problem, Thanks :+1:

**Pull request closed without merging**
