### PR TITLE
Feature/bump clion

### PR DESCRIPTION
**Pull request by strahlc**
Closes: https://bugs.gentoo.org/653952
Closes: https://bugs.gentoo.org/659070
Closes: https://bugs.gentoo.org/640954
Closes: https://bugs.gentoo.org/644980

    dev-util/clion: version bump to 2018.2
    dev-util/clion: remove old version
    dev-util/clion: prevent file collisions with other jetbrains products

### CODE REVIEW

**Comment by gyakovlev** [comment]
Hi, thanks for the bump.

There is a number of bugs that affects all idea packages and `clion` in particular.

https://bugs.gentoo.org/640954
https://bugs.gentoo.org/644980
https://bugs.gentoo.org/644980


Probably 

`RESTRICT="splitdebug"`

can fix the bug, since there is little to no sense installing debug files for bundled pre-built stuff.

I tested on one of the packages that installs  debug files to similar directory and it effectively prevents installing those files, but the binaries get installed unstripped in my case.

I'm not sure if this is the most correct solution, but it works.

@mgorny any opinions on that? Seems `RESTRICT` is a portage thing, not sure if pkgcore has it, and paludis is going away soon anyway.

**Comment by strahlc** [comment]
@gyakovlev 
Can you please merge this PR? :)

**Comment by gyakovlev** [comment]
Disregard previous comment:
I have a system without java installed, and clion simply does not work after emerging, complaining there is no JAVA_HOME, JDK_HOME or CLION_JDK and no java found.

Looks like java is bundled but is not detected somehow by the wrapper script.

**Comment by gyakovlev** [comment]
here's script output with `-x`

```shell
clion 
++ which uname
+ UNAME=/usr/bin/uname
++ which egrep
+ GREP=/bin/egrep
+ GREP_OPTIONS=
++ which cut
+ CUT=/usr/bin/cut
++ which readlink
+ READLINK=/usr/bin/readlink
++ which xargs
+ XARGS=/usr/bin/xargs
++ which dirname
+ DIRNAME=/usr/bin/dirname
++ which mktemp
+ MKTEMP=/usr/bin/mktemp
++ which rm
+ RM=/bin/rm
++ which cat
+ CAT=/bin/cat
++ which sed
+ SED=/bin/sed
+ '[' -z /usr/bin/uname -o -z /bin/egrep -o -z /usr/bin/cut -o -z /usr/bin/mktemp -o -z /bin/rm -o -z /bin/cat -o -z /bin/sed ']'
++ /usr/bin/uname -s
+ OS_TYPE=Linux
+ SCRIPT_LOCATION=/opt/clion-2018.2/bin/clion.sh
+ '[' -x /usr/bin/readlink ']'
+ '[' -L /opt/clion-2018.2/bin/clion.sh ']'
++ dirname /opt/clion-2018.2/bin/clion.sh
+ cd /opt/clion-2018.2/bin
++ pwd
+ IDE_BIN_HOME=/opt/clion-2018.2/bin
++ dirname /opt/clion-2018.2/bin
+ IDE_HOME=/opt/clion-2018.2
+ cd /home/ya
+ '[' -n '' -a -x /bin/java ']'
+ '[' -z '' -a -s /home/ya/.CLion2018.2/config/clion.jdk ']'
+ '[' -z '' -a Linux = Linux ']'
+ BUNDLED_JRE=/opt/clion-2018.2/jre64
+ '[' '!' -d /opt/clion-2018.2/jre64 ']'
+ '[' -x /opt/clion-2018.2/jre64/bin/java ']'
+ '[' -z '' -a -n '' -a -x /bin/java ']'
+ '[' -z '' -a -n '' -a -x /bin/java ']'
+ '[' -z '' ']'
++ which java
which: no java in (/home/ya/.local/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/8.1.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/games/bin)
+ JDK_PATH=
+ '[' -n '' ']'
+ '[' -z '' -a -x /usr/bin/readlink -a -x /usr/bin/xargs -a -x /usr/bin/dirname ']'
++ /usr/bin/readlink -f ''
+ JAVA_LOCATION=
+ case "$JAVA_LOCATION" in
++ echo ''
++ /usr/bin/xargs /usr/bin/dirname
++ /usr/bin/xargs /usr/bin/dirname
/usr/bin/dirname: missing operand
Try '/usr/bin/dirname --help' for more information.
/usr/bin/dirname: missing operand
Try '/usr/bin/dirname --help' for more information.
+ JAVA_LOCATION=
+ '[' -x /bin/java ']'
+ JAVA_BIN=/bin/java
+ '[' -z '' -o '!' -x /bin/java ']'
+ message 'No JDK found. Please validate either CLION_JDK, JDK_HOME or JAVA_HOME environment variable points to valid JDK installation.'
+ TITLE='Cannot start CLion'
++ which zenity
which: no zenity in (/home/ya/.local/bin:/usr/x86_64-pc-linux-gnu/gcc-bin/8.1.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin:/usr/games/bin)
+ '[' -n '' ']'
++ which kdialog
+ '[' -n /usr/bin/kdialog ']'
+ kdialog --error 'No JDK found. Please validate either CLION_JDK, JDK_HOME or JAVA_HOME environment variable points to valid JDK installation.' --title 'Cannot start CLion'
```


something wrong with it's `dirname` usage, I believe it's somewhere in the case loop, lines 117-134

**Comment by strahlc** [comment]
I've added a 'custom-jdk' use flag. (like dev-util/idea-{community,ultimate} has)
If it is set, the custom jdk will be installed and used. If not, the bundled jdk will be removed and the system jdk will be used.

**Comment by gyakovlev** [comment]
works fine now, thanks for fixing a lot of stuff here! merged

**Pull request closed without merging**
