### PR TITLE
Fix dependency issue for Gentoo/FreeBSD, fix bug 489984.

### PR DESCRIPTION
**Pull request by nigoro**
dev-libs/libexecinfo has been merged into sys-freebsd/freebsd-lib-10.0 or higher version.
This PR fixes the dependency issue by changing elibc_FreeBSD? ( dev-libs/libexecinfo ) to elibc_FreeBSD? ( || ( dev-libs/libexecinfo >=sys-freebsd/freebsd-lib-10.0 ) ).
Could you please review this?

Thanks.

### CODE REVIEW

**Comment by mgorny** [comment]
This generally requires revbump of the newest version of each package. Otherwise, people who installed it already won't be able to unmerge libexecinfo.

**Comment by jsbronder** [comment]
Ok for sys-cluster/openmpi.  Thanks!

**Comment by monsieurp** [comment]
@nigoro Hi! Could you please rebase this PR against master? Thanks!

**Comment by nigoro** [comment]
@monsieurp, I've updated this PR. Could you please check it? thanks!

**Pull request closed without merging**
