### PR TITLE
dev-lang/go error fix for arm

### PR DESCRIPTION
**Pull request by longlene**

### CODE REVIEW

**Comment by mgorny** [comment]
@willamh.

**Comment by mgorny** [comment]
Since this is a build-time failure fix, revision bump is not necessary. Could you update the pull request to change the file in-place and rebase on current master?

**Comment by hasufell** [comment]
don't expect a review from William, he doesn't use github afaik and barely responds to email-patches as well

**Comment by kensington** [comment]
You could try IRC - he's pretty active there.

**Comment by longlene** [comment]
@mgorny Thanks for your advise, I've changed it.

**Comment by hasufell** [comment]
I guess we can merge this, since it's a very small fix anyway.

**Comment by hasufell** [comment]
@longlene please rebase against latest master:
```sh
git pull --rebase=preserve https://github.com/gentoo/gentoo.git master
```

**Comment by longlene** [comment]
@hasufell Thanks for your reply. This pr may can be closed as the bug has been fixed. https://github.com/gentoo/gentoo/commit/c1f324086082c9409d54126842985e0eaf5f137a

**Pull request closed without merging**
