### PR TITLE
app-misc/jq: update

### PR DESCRIPTION
**Pull request by rindeal**
No changes are obtrusive enough to require revbump.

@radhermit

### CODE REVIEW

**Comment by radhermit** [comment]
Wouldn't it be simpler to just use prune_libtool_files from eutils? Other than that, stuff looks fine at a glance.

**Comment by rindeal** [comment]
Never heard of that function, but it seems to do the same job.

**Comment by rindeal** [comment]
And what about https://bugs.gentoo.org/show_bug.cgi?id=580606, should I add that patch as well?

**Comment by radhermit** [comment]
Sure, then revbump it as well.

**Comment by rindeal** [comment]
Done

**Comment by radhermit** [comment]
I meant revbump just 1.5, doing both isn't worth it. :smile:

**Comment by rindeal** [comment]
Ok, 1.4 is gone

**Comment by radhermit** [comment]
If you squash all this into one revbump commit with details in the commit message body, I'll merge it.

**Comment by rindeal** [comment]
Like this?

**Comment by radhermit** [comment]
Thanks, merged.

**Pull request closed without merging**
