### PR TITLE
app-metrics/{various}: add transitive licenses for go packages

### PR DESCRIPTION
**Pull request by hhoffstaette**
This adds the required licenses of transitive dependencies to various go ebuilds.
Verified via go-licenses tool as described in https://bugs.gentoo.org/694792.

Bug: https://bugs.gentoo.org/695212
Signed-off-by: Holger Hoffstätte <holger@applied-asynchrony.com>

### CODE REVIEW

**Comment by Whissi** [comment]
I am wondering if we should do rev bump for changing licenses (mv, not cp) in case someone is actively blocking a license this update would add.

**Comment by hhoffstaette** [comment]
> I am wondering if we should do rev bump for changing licenses (mv, not cp) in case someone is actively blocking a license this update would add.

I don't know whether this is required by policy, so either tell me to do it .. or not. ;)

**Comment by Whissi** [comment]
OK, after talking with @ulm we will do no rev bump where we just add `MIT`, `BSD` (i.e. anything listed as authorized 3rd party license of `Apache-2.0`). But for the mongodb exporter we will do a rev bump.

**Comment by hhoffstaette** [comment]
> New issues caused by PR:
> https://qa-reports.gentoo.org/output/gentoo-ci/1120c49/output.html#app-metrics/mongodb_exporter

Has nothing to do with the revbump and was an existing issue (user/group creation).
@Whissi Care to merge what is in here so far?

**Comment by mgorny** [comment]
Also, I'd suggest keeping the direct license listed first, and additional licenses after it.

**Comment by mgorny** [comment]
Remember to reopen it before pushing, otherwise GitHub will mess it up.

**Comment by hhoffstaette** [comment]
> Also, I'd suggest keeping the direct license listed first, and additional licenses after it.

Done & done.

**Comment by SoapGentoo** [comment]
@hhoffstaette thanks for helping us fix this, keep up the good work :+1:

**Pull request closed without merging**
