### PR TITLE
dev-qt/qtbluetooth

### PR DESCRIPTION
**Pull request by dannftk**
fixed undefined errno when using with clang++ and libc++

Signed-off-by: Denis Pronin <dannftk@yandex.ru>

### CODE REVIEW

**Comment by dannftk** [comment]
done, the patch is propagated to 5.14.1

**Comment by Pesa** [comment]
Can you also send the patch upstream please?

**Comment by dannftk** [comment]
Can you please provide a link where I am supposed to provide the patch? It is the first time I have been requested to feed an upstream
Thank you

**Comment by Pesa** [comment]
You have to submit the patch to upstream's gerrit instance, see https://wiki.qt.io/Qt_Contribution_Guidelines for instructions

Your patch should probably be submitted against the `5.15` branch just to be safe. We can apply it to 5.14.x downstream in gentoo.

**Comment by dannftk** [comment]
The patch is forwarded to upstream and successfully applied to 5.14 branch

What should we do further to have it in here? Are you going to update sources as just the new version of Qt is released or you can apply the patch right now?

Thank you

**Pull request closed without merging**
