### PR TITLE
dev-lang/lazarus: revbump 1, fixed Python support

### PR DESCRIPTION
**Pull request by TheChymera**
Python support was broken with the original version.
@Amynka

### CODE REVIEW

**Comment by Amynka** [comment]
Hi, Can you fix the warnings please?

**Comment by TheChymera** [comment]
@Amynka which warnings do you mean? This bit? `${ED%/} unnecessary slash strip on lines: 87, 100, 102`? That was in `2.0.2`, I suspected you put it in there for a good reason.

**Comment by Amynka** [comment]
Still fails for me with [1].

[1] http://amynka.cz/build.log

**Comment by TheChymera** [comment]
ok, officially giving up on this since [upstream does not support lazbuild](https://github.com/Alexey-T/Python-for-Lazarus/issues/17), and [the Lazarus forums could not help out](https://forum.lazarus.freepascal.org/index.php/topic,48949.0.html) either.

**Pull request closed without merging**
