### PR TITLE
media-libs/mesa: add correct multilib usedep on ocl-icd

### PR DESCRIPTION
**Pull request by jvesely**

### CODE REVIEW

**Comment by jvesely** [comment]
ping. @mattst88 does this look OK to you?

**Comment by mattst88** [comment]
Looks good to me. Thanks. I'll merge in a few minutes.

**Comment by jvesely** [comment]
> Looks good to me. Thanks. I'll merge in a few minutes.

thanks. was there any reason to skip 18.2.2-r1? Is the build going away soon?

**Comment by mattst88** [comment]
Yeah, there's no reason for users to expect fixes to old minor releases. I just keep them around for a little while so people who list explicit =media-libs/mesa-18.x.y in their package.keywords don't get a downgrade if they're not paying much attention.

**Pull request closed without merging**
