### PR TITLE
RFC: Add transitional kdebase-meta:5 package for plasma profile migration

### PR DESCRIPTION
**Pull request by a17r**
In short, fix kde-apps/kdebase-meta:5 and introduce kde-apps/kde-meta:5 so both meta packages provide an equivalent package selection to their :4 counterparts and are scheduled for upgrade as soon as the user switches from kde to plasma profile.

- [x] pkgmove kde-base/kde-meta to kde-apps/kde-meta

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/kde

**Comment by monsieurp** [comment]
@gentoo/kde

**Comment by a17r** [comment]
I tested this on a stable system that had KDE SC 4 installed through kde-base/kdebase-meta:4 that was updated to the state of current pending kde4-stabilisation-list, and - after some world file cleanup - portage was able to auto-resolve all the blockers. Except for Qt conflicts, since QT_MINIMAL currently only enforces >=dev-qt/qtcore-${QT_MINIMAL}:5. - I think this could be solved through an eclass upgrade with the introduction of add_qt_dep() similar to add_kdecategory_dep().

What else is missing then? I'd say
- pkgmove kde-base/kde-meta to kde-apps/kde-apps-meta
- pkgmove kde-base/kdebase-startkde to kde-plasma/plasma-desktop
to have an upgrade path, and of course add both slot 5 versions to kde profile's package.mask.

**Comment by a17r** [comment]
Adding kdenetwork-meta from overlay and a preliminary version of kde-apps-meta:5 (whatever it should be called in the end). I can only test the downgrade from KDE Applications 15.12 right now but it resolves fine.

Together they bring back kopete and kdepim-meta:4 since in 15.08.3 I have no hope of plasma-telepathy-meta and kdepim-meta entering tree. kdeedu-meta would stay at 4.14.3 for the time being, until it can also be moved to tree.

I guess more *meta:5 packages should enter kde profile's package.mask.

**Comment by kensington** [comment]
You are the master!

**Pull request closed without merging**
