### PR TITLE
www-apps/gitea: add 1.20.4

### PR DESCRIPTION
**Pull request by eeyrjmr**
Signed-off-by: JonRB jon.roadleybattin@gmail.com
Closes: https://bugs.gentoo.org/911419

### CODE REVIEW

**Comment by stkw0** [comment]
Could you also add "Closes: https://bugs.gentoo.org/911419" to the commit so it close the relevant bug when merging the PR?

**Comment by kioplato** [comment]
Hello. I'm interested in working on this. Is someone else assigned to this issue?

**Comment by hydrapolic** [comment]
Tested with 1.20.4.

**Review by juippis — APPROVED** [review]

**Comment by hydrapolic** [comment]
Thanks @eeyrjmr @juippis!

**Pull request closed without merging**
