### PR TITLE
net-libs/kimap2: Version bump and new mirror for pulling

### PR DESCRIPTION
**Pull request by listout**
Signed-off-by: brahmajit das <listout@protonmail.com>

### CODE REVIEW

**Comment by a17r** [comment]
I doubt it is a good idea to bump one without the other(s). https://github.com/gentoo/gentoo/pull/22371

**Comment by listout** [comment]
@a17r Oh. I was planning to update revbump the kimap2 and sink. Whys is the PR still open? At least the sink and kimap2 seems to work.

**Comment by a17r** [comment]
It needs a maintainer, it (sink) needs to actually build.

**Comment by listout** [comment]
@a17r I'm working on to get it build. sink is dependent on kimap2 v0.4.0 (IIRC).

**Comment by a17r** [comment]
Consider dropping kde.org if you do not need any of its facilities, it is barely a KDE project at all at this point anyway.

**Comment by listout** [comment]
Okay, I'll do it

**Comment by juippis** [comment]
@a17r so proceed here or not?

**Comment by thesamesam** [comment]
This doesn't work as-is:
```
>>> Source compiled.
 * Skipping make test/check due to ebuild restriction.
>>> Test phase [disabled because of RESTRICT=test]: net-libs/kimap2-0.4.0

>>> Install net-libs/kimap2-0.4.0 into /var/tmp/portage/net-libs/kimap2-0.4.0/image
>>> Completed installing net-libs/kimap2-0.4.0 into /var/tmp/portage/net-libs/kimap2-0.4.0/image

 * Final size of build directory: 980 KiB
 * Final size of installed tree:   28 KiB

~/g/net-libs/kimap2 $ find /var/tmp/portage/net-libs/kimap2-0.4.0/image
/var/tmp/portage/net-libs/kimap2-0.4.0/image
/var/tmp/portage/net-libs/kimap2-0.4.0/image/usr
/var/tmp/portage/net-libs/kimap2-0.4.0/image/usr/share
/var/tmp/portage/net-libs/kimap2-0.4.0/image/usr/share/doc
/var/tmp/portage/net-libs/kimap2-0.4.0/image/usr/share/doc/kimap2-0.4.0
/var/tmp/portage/net-libs/kimap2-0.4.0/image/usr/share/doc/kimap2-0.4.0/README.md.zst
~/g/net-libs/kimap2 $
```

It just installs nothing because the cmake inherit got lost when losing the KDE eclasses.

**Comment by listout** [comment]
I'm working on others as well. I hit this when rev bumping sink

**Comment by AndrewAmmerlaan** [comment]
Closing since it seems the objective of this PR has been reached and it is now obsolete. Please re-open if this is not the case.

**Pull request closed without merging**
