### PR TITLE
app-misc/tmux: add sixel flag to compile with sixel support

### PR DESCRIPTION
**Pull request by denisstrizhkin**
Add flag that allows to compile tmux with enabled sixel support. I tested that it compiles and that it works.

### CODE REVIEW

**Comment by thesamesam** [comment]
Needs a rebase and for 9999/live to be updated.

**Review by arthurzam — APPROVED** [review]

**Comment by denisstrizhkin** [comment]
rebased on current master

**Comment by zx2c4** [comment]
Why not turn this on by default? (`+sixel`) Or just always turn it on? It doesn't seem to add a dependency.

**Comment by thesamesam** [comment]
No objection from me, I just don't know enough about the feature or its status in tmux. If it's well-supported and ideally other distros have turned it on by default, why not?

My only concern would be those sixel vulnerabilities a few years ago (implying implementations may not be great), IIRC they weren't just in xterm, but I might be misremembering

**Pull request closed without merging**
