### PR TITLE
dev-lang/rust: fix the build with musl-1.2.4

### PR DESCRIPTION
**Pull request by orbea**
This fixes the build with musl-1.2.4, may need `-system-bootstrap` after updating musl.

Closes: https://bugs.gentoo.org/903607
Upstream-PR: https://github.com/rust-lang/rust/pull/106246
Upstream-Issue: https://github.com/rust-lang/libc/issues/2934
Upstream-PR: https://github.com/rust-lang/libc/pull/2935
Upstream-Commit: https://github.com/rust-lang/libc/commit/1e8c55cbed0b6e05a6c5063baa1fea50cad49269
Upstream-PR: https://github.com/rust-random/getrandom/pull/326
Upstream-Commit: https://github.com/rust-random/getrandom/commit/7f73e3ccc1f53bfc419e4ddcfd343766aa5837b6

### CODE REVIEW

**Comment by vimproved** [comment]
Would it potentially be a good idea to have a dependency along the lines of
```
elibc_musl? (
    !system-boostrap? (
        <sys-libs/musl-1.2.4
    )
)
```
to ensure people aren't trying to build it without system-bootstrap on 1.2.4?
This might be better suited to a check in pre_build_checks though.

**Comment by orbea** [comment]
Good idea, I updated the PR. It seems there is already a `elibc_musl` check in DEPEND and if `USE=-system-boostrap` is set then emerge will try to downgrade to musl-1.2.3. I think the remaining foot gun is that when rust was built successfully built without these patches before upgrading to musl-1.2.4, but it can be manually resolved and is still probably better than not being able to build rust at all.

**Comment by orbea** [comment]
I updated this PR for rust-1.70.0.

@gyakovlev Can you please review this PR, its a blocking issue for me.

**Comment by orbea** [comment]
@gyakovlev Can you please review this? Its a pain to rebase this over and over again.

**Comment by vimproved** [comment]
Would probably be a good idea to re-add 1.69 since 1.70 is now unkeyworded and masked.

**Comment by orbea** [comment]
Downgrading rust is unfortunately a lot of effort to test.

**Comment by vimproved** [comment]
Did it myself, working fine for me.

**Comment by vimproved** [comment]
(Plus it was working fine before, so it should be fine.)

**Comment by orbea** [comment]
If @gyakovlev wants it I can add it back, but until I hear something one way or another I'd prefer to do as little work as possible.

**Comment by LinuxUserGD** [comment]
> if `USE=-system-boostrap` is set then emerge will try to downgrade to musl-1.2.3.

Downgrading musl works if only a few packages have been compiled with `musl-1.2.4`, otherwise the Gentoo installation might break.
https://www.openwall.com/lists/musl/2023/05/02/1
> The dynamic linker (and static-PIE entry point code) adds support for
the new compact "RELR" format for relative relocations which recent
linkers can generate. Use of this linker feature for dynamic-linked
programs will make them depend on having musl 1.2.4 or later available
at runtime.

**Comment by vimproved** [comment]
> > if `USE=-system-boostrap` is set then emerge will try to downgrade to musl-1.2.3.
> 
> Downgrading musl works if only a few packages have been compiled with `musl-1.2.4`, otherwise the Gentoo installation might break. https://www.openwall.com/lists/musl/2023/05/02/1
> 
> > The dynamic linker (and static-PIE entry point code) adds support for
> > the new compact "RELR" format for relative relocations which recent
> > linkers can generate. Use of this linker feature for dynamic-linked
> > programs will make them depend on having musl 1.2.4 or later available
> > at runtime.

What I've been doing is reverting the musl commits that removed lfs64 support before rebuilding rust. I don't know if this would be feasible, however the only thing I can think of that would be able to fix it is adding a default disabled USE flag to musl that reverts the LFS64 removal until the issue gets fixed upstream, and then adding something like
```
elibc_musl? (
    !system-bootstrap? (
        || (
            <sys-libs/musl-1.2.4
            sys-libs/musl[revert-lfs64]
        )
    )
)
```
Obviously this would be an inelegant fix but I don't think there's a particularly good solution to this until Rust gets it together and finally fixes it upstream.

**Comment by orbea** [comment]
Fwiw I believe this is the only rust PR we are waiting on. https://github.com/rust-lang/rust/pull/106246

Conditional patches for musl sounds like an even bigger mess to me.

**Comment by vimproved** [comment]
Yeah, at this point it's probably best to just wait on upstream until the fixes make it into the bootstrap tarballs.

**Comment by orbea** [comment]
> Yeah, at this point it's probably best to just wait on upstream until the fixes make it into the bootstrap tarballs.

That only makes it harder for anyone with musl-1.2.4 and downgrading your system could be problematic regardless if rust is fixed or not.

**Comment by 12101111** [comment]
I'm using this wrapper to workaround linking issue for upstream release

```c
#include <unistd.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <dirent.h>

int fstat64(int fd, struct stat *statbuf) {
  return fstat(fd, statbuf);
}
off_t lseek64(int fd, off_t offset, int whence) {
  return lseek(fd, offset, whence);
}
int stat64(const char* pathname, struct stat* statbuf) {
  return stat(pathname, statbuf);
}
int open64(const char* pathname, int flags) {
  return open(pathname, flags);
}
int openat64(int dirfd, const char* pathname, int flags, mode_t mode) {
  return openat(dirfd, pathname, flags, mode);
}
int fstatat64(int dirfd, const char* pathname, struct stat* statbuf, int flags) {
  return fstatat(dirfd, pathname, statbuf, flags);
}
struct dirent* readdir64(DIR *dirp) {
  return readdir(dirp);
}
int lstat64(const char* pathname, struct stat* statbuf) {
  return lstat(pathname, statbuf);
}
```

Compile this to archive file (eg. `libalias.a`) and add `-L/usr/local/lib -lalias` to RUSTFLAGS.

```
cc -O2 -c -o alias.o alias.c
ar -crs libalias.a alias.o
sudo cp libalias.a /usr/local/lib
```

**Comment by vimproved** [comment]
Here's a very hacky solution that allows bootstrapping from the stage0 tarball without downgrading or patching musl, using objcopy to redefine symbols in the rust stdlib:
```bash
src_prepare() {
	eapply_crate vendor/getrandom "${FILESDIR}"/1.69.0-musl-1.2.4-getrandom.patch
	eapply_crate vendor/libc-0.2.138 "${FILESDIR}"/1.69.0-musl-1.2.4-libc-0.2.138.patch
	eapply_crate vendor/libc-0.2.139 "${FILESDIR}"/1.69.0-musl-1.2.4-libc.patch
	eapply_crate vendor/libc "${FILESDIR}"/1.69.0-musl-1.2.4-libc.patch

	if ! use system-bootstrap; then
		has_version sys-devel/gcc || esetup_unwind_hack
		local rust_stage0_root="${WORKDIR}"/rust-stage0
		local rust_stage0="rust-${RUST_STAGE0_VERSION}-$(rust_abi)"

		if use elibc_musl; then
			LIBSTD="${WORKDIR}/${rust_stage0}/rust-std-$(rust_abi)/lib/rustlib/$(rust_abi)/lib/libstd-"*".rlib"

			"${OBJCOPY:-objcopy}" \
				--redefine-sym=stat64=stat \
				--redefine-sym=fstat64=fstat \
				--redefine-sym=lstat64=lstat \
				--redefine-sym=open64=open \
				--redefine-sym=readdir64=readdir \
				--redefine-sym=fstatat64=fstatat \
				--redefine-sym=lseek64=lseek \
				--redefine-sym=ftruncate64=ftruncate \
				"${LIBSTD}" \
				"${LIBSTD}.out" || die

			mv "${LIBSTD}.out" "${LIBSTD}" || die
		fi

		"${WORKDIR}/${rust_stage0}"/install.sh --disable-ldconfig \
			--without=rust-docs-json-preview,rust-docs --destdir="${rust_stage0_root}" --prefix=/ || die
	fi

	default
}
```

**Comment by orbea** [comment]
Would that be compatible with both gcc and clang? Also `< musl-1.2.4`?

**Comment by vimproved** [comment]
> Would that be compatible with both gcc and clang? Also `< musl-1.2.4`?

Yes. All functions on musl are automatically 64-bit, and this works with both LLVM and GNU binutils.

**Comment by orbea** [comment]
@vimproved I pushed your suggestion with minor changes.

**Comment by richfelker** [comment]
> Yes. All functions on >=musl-1.2 are automatically 64-bit, and this works with both LLVM and GNU binutils.

You mean >=musl-0.5.0.

**Comment by vimproved** [comment]
> > Yes. All functions on >=musl-1.2 are automatically 64-bit, and this works with both LLVM and GNU binutils.
> 
> You mean >=musl-0.5.0.

Didn't know that, thanks for the correction. Was thinking of 64-bit time_t probably.

**Comment by orbea** [comment]
@xen0n Can you please review this PR?

**Pull request closed without merging**
