### PR TITLE
app-admin/yadm: bump version to 1.05

### PR DESCRIPTION
**Pull request by esphen**
Gentoo-Bug: https://bugs.gentoo.org/593332

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
ping?

**Comment by esphen** [comment]
@monsieurp Are you pinging me, or the proxy-maint team? Do I need to do anything further?

**Comment by monsieurp** [comment]
Hi. I'm ping you. Please look at my comments above. :)

**Comment by esphen** [comment]
Hi @monsieurp! I'm sorry, but I am not seeing any comments. Are they made visible to me? Am I blind?

**Comment by monsieurp** [comment]
Check out this link: https://github.com/gentoo/gentoo/pull/2364/commits/56cbcd37c9e967f64cdaa1213b7f555dd2f57ac9#diff-fb47ada7b65217be8eadbfc22d60a073R35

**Comment by esphen** [comment]
Thanks for the link. Not seeing any comments there unfortunately

tmp_32698-screenshot_20160926-232411251811631

**Comment by monsieurp** [comment]
Mamma mia. Github is becoming a pile of shit every passing day. Can you give it another try?

**Comment by esphen** [comment]
Thanks, I see the comments now! I have amended the commit with your requests

**Pull request closed without merging**
