### PR TITLE
dev-lang/zig: Bump to version 0.7.1

### PR DESCRIPTION
**Pull request by atomsymbol**
This patch is performing the following actions:
- Adds new "shared" USE flag to `>=sys-devel/lld-11*`
- Drops `zig-0.5.0.ebuild`
- Adds `zig-0.7.1.ebuild`, which depends on `sys-devel/lld[shared]`
- Removes support for the "experimental" USE flag from `zig-9999`
- Adds a proxy maintainer to `dev-lang/zig/metadata.xml`

@mgorny Please specify (in sufficient detail) how to split this patch into smaller sub-patches, if required. Thanks.

Closes: https://bugs.gentoo.org/719736

### CODE REVIEW

**Comment by mattst88** [comment]
I'm not the maintainer of either package, but I think at a minimum the changes to lld should be in a separate commit from the zig version bump.

Thanks for working on this!

**Comment by atomsymbol** [comment]
> I think at a minimum the changes to lld should be in a separate commit from the zig version bump.

lld ebuild changes as a separate pull request: https://github.com/gentoo/gentoo/pull/19038

**Comment by atomsymbol** [comment]
Updated: lld ebuild changes as a separate pull request: #19038

**Comment by ajakk** [comment]
> Updated: lld ebuild changes as a separate pull request: #19038

This PR still has the changes? To drop it you should be able to do something like `git reset --soft HEAD^`, then dropping the lld changes and doing `git commit --amend`.

**Comment by atomsymbol** [comment]
> > Updated: lld ebuild changes as a separate pull request: #19038
> 
> This PR still has the changes? To drop it you should be able to do something like `git reset --soft HEAD^`, then dropping the lld changes and doing `git commit --amend`.

After dropping lld from this PR, github says that the pull request is broken. Is there a way to tell Gentoo's CI that a PR depends on another PR?

**Comment by ajakk** [comment]
No. Just rebase this PR when/if the other one is merged.

**Comment by atomsymbol** [comment]
@mattst88 Please review. Thanks.

**Comment by atomsymbol** [comment]
There is no interest in this patch.

**Comment by thesamesam** [comment]
I don't think that's quite fair. I think somebody hasn't reviewed it yet, but that doesn't mean nobody is interested at all. Reviewing is quite hard and we have a high workload.

Also, in this case, I really need someone with knowledge of LLVM to do it. I can't/shouldn't do it myself.

**Comment by atomsymbol** [comment]
> Reviewing is quite hard and we have a high workload.

I don't see an entry point enabling me to lower the workload other than closing this pull request. Sorry.

**Comment by mgorny** [comment]
It's not fair to claim that we have no interest when I'm still waiting for you to confirm whether it actually works. Like in, runtime works, not just builds.

https://bugs.gentoo.org/719736#c16

**Comment by atomsymbol** [comment]
> It's not fair to claim that we have no interest when I'm still waiting for you to confirm whether it actually works. Like in, runtime works, not just builds.
> 
> https://bugs.gentoo.org/719736#c16

It didn't work out because the amount of implicit synchronization between your mind and my mind is too low.

**Comment by mjsir911** [comment]
Its disheartening to see that this didn't get in. For reference: #19606 does basically the same thing, without the suggestion to split into two PRs nor the useful `shared` lld USE flag. Thank you for the try @atomsymbol

**Comment by mattst88** [comment]
> Its disheartening to see that this didn't get in. For reference: #19606 does basically the same thing, without the suggestion to split into two PRs nor the useful `shared` lld USE flag. Thank you for the try @atomsymbol

The suggestion wasn't to make a separate PR. It was to separate the lld ebuild changes from the zig version bump. That is, to put them in separate patches. I have no idea why this was misinterpreted as a suggestion to make a separate PR:

> I'm not the maintainer of either package, but I think at a minimum the changes to lld should be in a separate commit from the zig version bump.

This isn't even the first time I've seen atomsymbol rage quit a free software project, so please don't mistake this situation for something it's not.

**Comment by mjsir911** [comment]
Ah, thank you for shedding light on the situation @mattst88 and ty for correcting me, I hope your clarifications will help future MRs continue along more smoothly

**Comment by atomsymbol** [comment]
> This isn't even the first time I've seen atomsymbol rage quit a free software project, so please don't mistake this situation for something it's not.

I would like to know which free software projects I have quit in rage according to your best knowledge. Please post the list of those projects here or to my email address. Please don't choose the option **not** to post the list. Thanks.

**Comment by mattst88** [comment]
Mesa.

(And we were somewhat relieved)

**Comment by atomsymbol** [comment]
> (And we were somewhat relieved)

I am used to prejudice and mistreatment.

**Pull request closed without merging**
