### PR TITLE
app-misc/nnn: bumped to 3.3

### PR DESCRIPTION
**Pull request by florianjr**
Closes: https://bugs.gentoo.org/732566
Package-Manager: Portage-2.3.103, Repoman-2.3.23

### CODE REVIEW

**Comment by florianjr** [comment]
I thought that repoman would automatically add the signed-off.

**Comment by Zlogene** [comment]
Thanks. I will merge in 5h, totally forgot

**Comment by florianjr** [comment]
Thank you. I would suggest me as maintainer.

**Comment by Zlogene** [comment]
You forgot to SGoB this commit, I bumped it myself this time :(

**Pull request closed without merging**
