### PR TITLE
kde-apps/mplayerthumbs: Drop pointless version bumps

### PR DESCRIPTION
**Pull request by a17r**
mplayerthumbs has no code change since 4.10, no porting branch and is of no use with dolphin:5, the existence of 15.{08,12} versions only serves to confuse people.

For reference: https://forums.gentoo.org/viewtopic-t-1037780.html

@gentoo/kde

### CODE REVIEW

**Comment by kensington** [comment]
I'm not sure if this is a good idea - dropping versions in this way will cause a downgrade to appear to anybody who has it installed.

**Comment by a17r** [comment]
Yes it would, not a big deal imo - but I have no strong opinion there.

**Comment by a17r** [comment]
no downgrades, then, but dropping the use flag

**Comment by kensington** [comment]
Thanks, picked as 611729fccbcac3aef50d86aa0a5ad0fb04825752...114f07ce956fb1868361595a0c0ad3b35255eb93.

**Pull request closed without merging**
