### PR TITLE
add arm keyword to some ruby packages

### PR DESCRIPTION
**Pull request by rindeal**
@gentoo/ruby

### CODE REVIEW

**Comment by graaff** [comment]
You are missing dependencies, see the QA report for details. How did you confirm that these packages work on ~arm?

**Comment by monsieurp** [comment]
@rindeal hi and thanks for the PR. could you attach a build log for this list of newly keyworded packages?

**Comment by rindeal** [comment]
> @rindeal hi and thanks for the PR. could you attach a build log for this list of newly keyworded packages?

hi, I could, but it will take time, ETA ~next week

**Comment by monsieurp** [comment]
@rindeal hi. we're in September and no log file has been provided yet. I'm closing this PR for the time being. feel free to reopen it and provide a link to a log file this time round. cheers.

**Pull request closed without merging**
