### PR TITLE
sys-apps/flashrom: update IUSE_PROGRAMMERS in 9999 ebuild

### PR DESCRIPTION
**Pull request by jsmolic**
Closes: https://bugs.gentoo.org/735974
Package-Manager: Portage-2.3.99, Repoman-2.3.23
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>

### CODE REVIEW

**Comment by jsmolic** [comment]
ping @mkszuba

**Comment by mkszuba** [comment]
Support for Realtek MST is off by default in the Makefile, although interestingly enough defaults to true in Meson. Otherwise LGTM!

In the future you might want to open a Bugzilla ticket instead, I do not really use GitHub.

**Comment by jsmolic** [comment]
@mkszuba Thanks!\
https://bugs.gentoo.org/735974 was there so I did not want to open new bug.

**Comment by mkszuba** [comment]
Odd, somehow I haven't received a notification about this ticket. Either way, thanks for your contribution!

**Pull request closed without merging**
