### PR TITLE
 net-analyzer/openvas: bump to 10.0.1 & big cleanup

### PR DESCRIPTION
**Pull request by hsntgm**
Hi,

To keep commit messages clean here is the detailed information about PR.

- OpenVAS with version 10 has been renamed in Greenbone Vulnerability Management (GVM).Also some of the component names has been renamed. In short there is no new package in this PR.

- GVM-10 (previously named OpenVAS-9) is a major update so structer has changed dramatically.Healthy upgrade from old OpenVAS-9 to GVM-10 is not possible. Manuel database update is still possible.

- Project has started to use react.js for WebUI (GSA). Thanks to upstream for pre-generated npm stuff that made GSA possible to compile on source based distros.

Official discussion about new package naming schema : 
-- > https://github.com/greenbone/gvm-libs/issues/197

The final GVM (Greenbone Vulnerability Management) component names that agreed by upstream and openvas maintainers (Arch, Debian, Fedora, Alpine, Kali, Ubuntu{~mrazavi} and Atomic repo) -->
 
```
Main Project Name:

GVM                          --> previously named OpenVAS

-------------------------------------------------------------------

Components Names:

gvm-libs                     --> previously named openvas-libraries
openvas-scanner              --> not changed
gvmd                         --> previously named openvas-manager
greenbone-security-assistant --> not-changed
gvm-tools                    --> previously named openvas-cli
ospd                         --> not changed

```

Upgarde to GVM-10 from old OpenVAS-9 not possible if i drop old OpenVAS-9 with all components from main gentoo tree users will confuse. Because of that i decided to keep OpenVAS-9 and brand new GVM-10 on main gentoo tree until new package names are synchronized in other linux distros and community start to know openvas with new name GVM. Then i will drop old openvas-9 and components completely.

### PR Details:

GVM Ebuild Versions in this PR :

    gvm (loader package)         --> 10.0.1 (stable, latest)

---------------------------------------

    gvm-libs                     --> 10.0.1 (stable, latest)
    openvas-scanner              -->  6.0.1 (stable, latest)
    gvmd                         -->  8.0.1 (stable, latest)
    greenbone-security-assistant -->  8.0.1 (stable, latest)

*Bump to latest GVM-10 with all renamed & updated components,
*All ebuilds written start from scratch according to changed dependencies,
*Used official pre-generated npm stuff to compile GSA,
*Changed licences, package descriptions, website information, metadatas updated,
*Added PostgreSQL backend support to gvmd with "postgres" use flag,
*Added SQLite backend support with "sqlite" use flag,
*Added "cron" use flag for GVM's vulnerability feed updates,
*Systemd unit files, init scripts, logrotate files updated,
*Broken OpenVAS-9 scripts removed,
*Added slots & hard-blocks to prevent upgrading from OpenVAS-9 to GVM-10,
*Dropped very old ebuilds,patches,files (big cleanup),

### Request from devs :

We can add below packages to package.mask **for removal in 30 days.**
net-analyzer/openvas-cli (replaced with net-analyzer/gvm-tools )
net-analyzer/openvas-tools (deprecated)

Also i am very pleased if you put database migration link to web **net-analyzer/openvas** and inform users about emerging latest stable GVM **net-analyzer/gvm**
Database migration instruction link -->
https://github.com/greenbone/gvmd/blob/v8.0.0/INSTALL.md#migrating-to-version-80

Thanks,
Hasan | Proxy Maint

Update:
----------------------------
Because of node & yarn dependencies following packages masked in profiles/arch/amd64/x32/package.mask

net-analyzer/greenbone-security-assistant-8.0.1:1
net-analyzer/gvm

### CODE REVIEW

**Comment by juippis** [comment]
One thing I noticed: You shouldn't drop the existing packages given these strict requirements. If someone fails to update some package middleway through, their system will be left in an awkward position where they cant use (given the dependency requirements) either version.

Then I saw
```
	enewgroup gvm
	enewuser gvm -1 /bin/bash /var/lib/gvm gvm
```
This is now handled via methods by GLEP-81, we should start by setting that up before merging this PR. I think you've seen enough examples in Gentoo tree, and in gentoo-dev ML how to properly handle that packaging? So open a new PR to add acct-*/gvm ebuilds, then send them to gentoo-dev mailing list to be reviewed, then let's come back to this PR (I will try to review everything before asking you to rebase this).

Let me know if you disagree or need help with anything.

**Comment by hsntgm** [comment]
Hi juippis,

How will i determine ACCT_USER_ID ?
For example i assigned 1453
Do i have to check all user_IDs in use ?

Also i confused about the logic.

This code creates next available user ID on system but i manually assigned 1453 in acct_user.

```
enewgroup gvm
enewuser gvm -1 /bin/bash /var/lib/gvm gvm
```

gvm-0.ebuild

```
# Copyright 2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

inherit acct-user

DESCRIPTION="Greenbone vulnerability management program user"
ACCT_USER_ID=1453
ACCT_USER_HOME=/var/lib/gvm
ACCT_USER_SHELL=/bin/bash
ACCT_USER_GROUPS=( gvm )

acct-user_add_deps
```

**Comment by juippis** [comment]
I think you can just choose something below 500, currently taken IDs are listed in: 
https://wiki.gentoo.org/wiki/Project:Quality_Assurance/UID_GID_Assignment
I couldn't find gvm having a fixed ID in fedora or arch.

I'm not sure if the code for randomizing IDs was put in place yet. 

Here's simple examples how these ebuilds and metadata.xml work:
https://archives.gentoo.org/gentoo-dev/message/e953d4cacb974ee1db62773d30d77f63

**Comment by hsntgm** [comment]
> I couldn't find gvm having a fixed ID in fedora or arch.

Because all distros run gvm and daemons under root which is not secure. Community edition of gvm uses only rsync to updating feeds and rsyncing under root is not secure. Because of that i settet up the package run under user gvm. I dropped all executables to /usr/bin instead of /usr/sbin . All services and init scripts runs under user gvm expect openvas-scanner. It needs root privileges for extra checks.

**Comment by hsntgm** [comment]
I hope my workflow was correct. I requested ID 495 in dev-list also opened a PR ( ci not happy )
For being sure i sent a fixup to gvm-libs commit.

```
pkg_setup() {
	enewgroup gvm 495
	enewuser gvm 495 /bin/bash /var/lib/gvm gvm
}
```

**Comment by juippis** [comment]
Can we do it so you only focus on bumping versions in this PR, then clean up old ebuilds / files in a new PR? This is too messy to get my head around it currently.

**Comment by hsntgm** [comment]
Why not ? 
I don't know what have you found messy here :) but i will try to split this PR.
But you know still i haven't PONG to my PING for 'user request'. 
@mgorny need to decide about /bin/bash vs nologin..

So no need to hurry :)

**Pull request closed without merging**
