### PR TITLE
Add pypy3 py3.12 to pipenv

### PR DESCRIPTION
**Pull request by oz123**
This PR is a requirement for https://github.com/gentoo/gentoo/pull/34062

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
I'm getting a test failure on virtualenv-clone with pypy3 that does not happen with python3.11 or python3.12:

```
================================================== FAILURES ==================================================
__________________________________ TestVirtualenvClone.test_clone_contents ___________________________________

self = <tests.test_virtualenv_clone.TestVirtualenvClone testMethod=test_clone_contents>

def test_clone_contents(self):
"""Walk the virtualenv and verify clonedenv contents"""

sys.argv = ['virtualenv-clone', venv_path, clone_path]
clonevirtualenv.main()

version = clonevirtualenv._virtualenv_sys(venv_path)[0]

for root, dirs, files in os.walk(venv_path):
clone_root = root.replace(venv_path,clone_path)
for dir_ in dirs:
dir_in_clone = os.path.join(clone_root,dir_)
assert os.path.exists(dir_in_clone),\
'Directory %s is missing from cloned virtualenv' % dir_

for file_ in files:
if file_.endswith('.pyc') or\
file_.endswith('.exe') or\
file_.endswith('.egg') or\
file_ in ['python', 'python%s' % version]:
# binarys fail reading and
# compiled will be recompiled
continue

file_in_clone = os.path.join(clone_root,file_)
assert os.path.exists(file_in_clone),\
'File %s is missing from cloned virtualenv' % file_

if os.path.islink(file_in_clone):
target = os.readlink(file_in_clone)
assert venv_path != target
assert venv_path not in target
assert os.path.basename(venv_path) not in target
continue

with open(file_in_clone, 'rb') as f:
lines = f.read().decode('utf-8')
>                   assert venv_path not in lines,\
'Found source path in cloned file %s' % file_in_clone
E                   AssertionError: Found source path in cloned file /tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/clone_venv/bin/wheel
E                   assert '/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv' not in "#!/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv/bin/pypy3\n# -*- coding: utf-8 -*-\nimport re\nimport sys\nfrom wheel.cli import main\nif __name__ == '__main__':\n    sys.argv[0] = re.sub(r'(-script\\.pyw|\\.exe)?$', '', sys.argv[0])\n    sys.exit(main())\n"
E                     '/tmp/portage/dev-p...mplddty8o_/srs_venv' is contained here:
E                       #!/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv/bin/pypy3
E                       # -*- coding: utf-8 -*-
E                       import re
E                       import sys
E                       from wheel.cli import main
E                       if __name__ == '__main__':
E                           sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])
E                           sys.exit(main())

clone_root = '/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/clone_venv/bin'
dir_       = 'lib'
dir_in_clone = '/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/clone_venv/lib'
dirs       = []
f          = <_io.BufferedReader name='/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/clone_venv/bin/wheel'>
file_      = 'wheel'
file_in_clone = '/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/clone_venv/bin/wheel'
files      = ['pypy',
'pypy3',
'python',
'python3',
'python3.10',
'wheel',
'wheel3',
'wheel-3.10',
'wheel3.10',
'pip',
'pip3',
'pip-3.10',
'pip3.10',
'activate',
'activate.csh',
'activate.fish',
'activate.nu',
'activate.ps1',
'activate_this.py']
lines      = ('#!/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv/bin/pypy3\n'
'# -*- coding: utf-8 -*-\n'
'import re\n'
'import sys\n'
'from wheel.cli import main\n'
"if __name__ == '__main__':\n"
"    sys.argv[0] = re.sub(r'(-script\\.pyw|\\.exe)?$', '', sys.argv[0])\n"
'    sys.exit(main())\n')
root       = '/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv/bin'
self       = <tests.test_virtualenv_clone.TestVirtualenvClone testMethod=test_clone_contents>
target     = 'pypy'
version    = '3.10'

tests/test_virtualenv_clone.py:75: AssertionError
-------------------------------------------- Captured stdout call --------------------------------------------
created virtual environment PyPy3.10.13.final.0-64 in 503ms
creator PyPy3Posix(dest=/tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmplddty8o_/srs_venv, clear=False, no_vcs_ignore=False, global=False)
seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/tmp/portage/dev-python/virtualenv-clone-0.5.7/homedir/.local/share/virtualenv)
added seed packages: pip==23.3.1, setuptools==68.2.2, wheel==0.41.3
activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
========================================== short test summary info ===========================================
FAILED tests/test_virtualenv_clone.py::TestVirtualenvClone::test_clone_contents - AssertionError: Found sourcepath in cloned file /tmp/portage/dev-python/virtualenv-clone-0.5.7/temp/tmpl...
================================== 1 failed, 17 passed in 106.86s (0:01:46) ==================================
```

 Could you look into the above failure? The tests on shellingham pass though, so I will merge the first two commits.

**Comment by oz123** [comment]
@AndrewAmmerlaan thank you for your support and comments so far.
I cloned virtualenv-clone and tried running the tests with pypy3, and they seem to work...

```
$ pypy3 -m pytest tests/
============================================================================================================ test session starts =============================================================================================================
platform linux -- Python 3.10.13[pypy-7.3.13-final], pytest-7.4.3, pluggy-1.3.0
rootdir: /home/oznt/Software/virtualenv-clone
collected 18 items                                                                                                                                                                                                                           

tests/test_dirmatch.py .                                                                                                                                                                                                               [  5%]
tests/test_fixup_scripts.py ........                                                                                                                                                                                                   [ 50%]
tests/test_virtualenv_clone.py .....                                                                                                                                                                                                   [ 77%]
tests/test_virtualenv_sys.py ....                                                                                                                                                                                                      [100%]

===========================================================================================================
```

I am still not able to run pypy3 tests for the ebuild though. Is this pypy3 issue a gentoo only issue?

**Comment by oz123** [comment]
Hmm... trying to figure this issue, I just found out, we actullay removed virtualenv-clone from pipenv.

https://github.com/pypa/pipenv/commit/6ac1451ec86d2949855e557109c2eb92b61930fc#diff-42124158e5163ef7b4d14448626c5cf90c40d6ce350caf8fe77674cb559d0d2f.

So we can totally remove it from the dependencies.

**Comment by AndrewAmmerlaan** [comment]
Great, this resolves the pypy3 problem. I merged the commits adding the pypy3 compatibility. 

There is still some problem in `dev-python/dparse` with `python3.12`:
```
* python3_12: running distutils-r1_run_phase python_test
python3.12 -m pytest -vv -ra -l -Wdefault --color=yes -o console_output_style=count -p no:cov -p no:flake8 -p no:flakes -p no:pylint -p no:markdown -p no:sugar -p no:xvfb -p no:pytest-describe -p no:plus -p no:tavern
============================================ test session starts =============================================
platform linux -- Python 3.12.0, pytest-7.4.3, pluggy-1.3.0 -- /tmp/portage/dev-python/dparse-0.6.3-r1/work/dparse-0.6.3-python3_12/install/usr/bin/python3.12
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/dparse-0.6.3-r1/work/dparse-0.6.3
plugins: anyio-4.1.0, flaky-3.7.0, pkgcore-0.12.23
collecting ... collected 51 items

tests/test_dependencies.py::test_dependency_serialize PASSED                                          [ 1/51]
tests/test_dependencies.py::test_dependency_deserialize PASSED                                        [ 2/51]
tests/test_dependencies.py::test_dependency_file_serialize PASSED                                     [ 3/51]
tests/test_dependencies.py::test_dependency_file_deserialize PASSED                                   [ 4/51]
tests/test_dependencies.py::test_parser_class FAILED                                                  [ 5/51]
tests/test_parse.py::test_requirements_with_invalid_requirement PASSED                                [ 6/51]
tests/test_parse.py::test_tox_ini_with_invalid_requirement FAILED                                     [ 7/51]
tests/test_parse.py::test_conda_file_with_invalid_requirement PASSED                                  [ 8/51]
tests/test_parse.py::test_conda_file_invalid_yml PASSED                                               [ 9/51]
tests/test_parse.py::test_conda_file_marked_line PASSED                                               [10/51]
tests/test_parse.py::test_tox_ini_marked_line FAILED                                                  [11/51]
tests/test_parse.py::test_resolve_file PASSED                                                         [12/51]
tests/test_parse.py::test_index_server PASSED                                                         [13/51]
tests/test_parse.py::test_requirements_package_with_index_server PASSED                               [14/51]
tests/test_parse.py::test_requirements_parse_empty_line PASSED                                        [15/51]
tests/test_parse.py::test_requirements_parse_unsupported_line_start PASSED                            [16/51]
tests/test_parse.py::test_file_resolver PASSED                                                        [17/51]
tests/test_parse.py::test_is_marked_file PASSED                                                       [18/51]
tests/test_parse.py::test_is_marked_line PASSED                                                       [19/51]
tests/test_parse.py::test_pipfile PASSED                                                              [20/51]
tests/test_parse.py::test_pipfile_lock PASSED                                                         [21/51]
tests/test_parse.py::test_pipfile_with_invalid_toml PASSED                                            [22/51]
tests/test_parse.py::test_pipfile_lock_with_invalid_json PASSED                                       [23/51]
tests/test_parse.py::test_poetry_lock PASSED                                                          [24/51]
tests/test_parse.py::test_poetry_lock_with_invalid_toml PASSED                                        [25/51]
tests/test_updater.py::test_update_tox_ini FAILED                                                     [26/51]
tests/test_updater.py::test_update_conda_yml PASSED                                                   [27/51]
tests/test_updater.py::test_update_requirements_multispace PASSED                                     [28/51]
tests/test_updater.py::test_update_requirements_compatible PASSED                                     [29/51]
tests/test_updater.py::test_update_requirements_compatible_matching_latest PASSED                     [30/51]
tests/test_updater.py::test_update_requirements_contains_correct_sep_char PASSED                      [31/51]
tests/test_updater.py::test_update_requirements_with_hashes PASSED                                    [32/51]
tests/test_updater.py::test_update_requirements_with_hashes_and_comment_and_env_markers PASSED        [33/51]
tests/test_updater.py::test_update_requirements_with_hashes_and_comment_inline PASSED                 [34/51]
tests/test_updater.py::test_update_requirements_with_hash_and_space_separator PASSED                  [35/51]
tests/test_updater.py::test_update_requirements_with_hash_and_comment_and_env_markers_inline PASSED   [36/51]
tests/test_updater.py::test_update_requirements_with_hash_inline PASSED                               [37/51]
tests/test_updater.py::test_update_requirements_with_env_markers PASSED                               [38/51]
tests/test_updater.py::test_update_requirements_with_env_markers_and_comment PASSED                   [39/51]
tests/test_updater.py::test_update_requirements_with_extras PASSED                                    [40/51]
tests/test_updater.py::test_update_requirements_with_tabs PASSED                                      [41/51]
tests/test_updater.py::test_update_requirements_with_plus PASSED                                      [42/51]
tests/test_updater.py::test_update_requirements_line_endings PASSED                                   [43/51]
tests/test_updater.py::test_update_requirements_simple_pinned PASSED                                  [44/51]
tests/test_updater.py::test_update_requirements_simple_unpinned PASSED                                [45/51]
tests/test_updater.py::test_update_requirements_simple_unpinned_with_comment PASSED                   [46/51]
tests/test_updater.py::test_update_requirements_cookiecutter_template PASSED                          [47/51]
tests/test_updater.py::test_update_requirements_with_double_package_name PASSED                       [48/51]
tests/test_updater.py::test_update_requirements_ranged PASSED                                         [49/51]
tests/test_updater.py::test_update_requirements_unfinished_line PASSED                                [50/51]
tests/test_updater.py::test_update_pipfile PASSED                                                     [51/51]

================================================== FAILURES ==================================================
_____________________________________________ test_parser_class ______________________________________________

def test_parser_class():

dep_file = parse("", file_type=filetypes.requirements_txt)
assert isinstance(dep_file.parser, parser.RequirementsTXTParser)

dep_file = parse("", path="req.txt")
assert isinstance(dep_file.parser, parser.RequirementsTXTParser)

dep_file = parse("", path="req.in")
assert isinstance(dep_file.parser, parser.RequirementsTXTParser)

>       dep_file = parse("", file_type=filetypes.tox_ini)

dep_file   = <dparse.dependencies.DependencyFile object at 0x7f8a56c64ec0>

tests/test_dependencies.py:139:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dparse/parser.py:506: in parse
return dep_file.parse()
content    = ''
dep_file   = <dparse.dependencies.DependencyFile object at 0x7f8a56c659a0>
file_type  = 'tox.ini'
marker     = ((), ())
parser     = None
path       = None
resolve    = False
sha        = None
dparse/dependencies.py:226: in parse
self.parser.parse()
self       = <dparse.dependencies.DependencyFile object at 0x7f8a56c659a0>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <dparse.parser.ToxINIParser object at 0x7f8a56c64ce0>

def parse(self):
"""

:return:
"""
parser = ConfigParser()
>       parser.readfp(StringIO(self.obj.content))
E       AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

parser     = <configparser.ConfigParser object at 0x7f8a56c64fe0>
self       = <dparse.parser.ToxINIParser object at 0x7f8a56c64ce0>

dparse/parser.py:312: AttributeError
___________________________________ test_tox_ini_with_invalid_requirement ____________________________________

def test_tox_ini_with_invalid_requirement():

content = "[testenv]" \
"passenv = CI TRAVIS TRAVIS_*" \
"setenv =" \
"PYTHONPATH = {toxinidir}" \
"deps =" \
"-r{toxinidir}/requirements_dev.txt" \
"pytest-cov" \
"codecov"
>       dep_file = parse(content, file_type=filetypes.tox_ini)

content    = ('[testenv]passenv = CI TRAVIS TRAVIS_*setenv =PYTHONPATH = {toxinidir}deps '
'=-r{toxinidir}/requirements_dev.txtpytest-covcodecov')

tests/test_parse.py:34:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dparse/parser.py:506: in parse
return dep_file.parse()
content    = ('[testenv]passenv = CI TRAVIS TRAVIS_*setenv =PYTHONPATH = {toxinidir}deps '
'=-r{toxinidir}/requirements_dev.txtpytest-covcodecov')
dep_file   = <dparse.dependencies.DependencyFile object at 0x7f8a56c65f40>
file_type  = 'tox.ini'
marker     = ((), ())
parser     = None
path       = None
resolve    = False
sha        = None
dparse/dependencies.py:226: in parse
self.parser.parse()
self       = <dparse.dependencies.DependencyFile object at 0x7f8a56c65f40>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <dparse.parser.ToxINIParser object at 0x7f8a56c67a70>

def parse(self):
"""

:return:
"""
parser = ConfigParser()
>       parser.readfp(StringIO(self.obj.content))
E       AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

parser     = <configparser.ConfigParser object at 0x7f8a56c64320>
self       = <dparse.parser.ToxINIParser object at 0x7f8a56c67a70>

dparse/parser.py:312: AttributeError
__________________________________________ test_tox_ini_marked_line __________________________________________

def test_tox_ini_marked_line():
content = "[testenv:bandit]\n" \
"commands =\n" \
"\tbandit --ini setup.cfg -ii -l --recursive project_directory\n" \
"deps =\n" \
"\tbandit==1.4.0 # naaah, marked\n" \
"\n" \
"[testenv:manifest]\n" \
"commands =\n" \
"\tcheck-manifest --verbose\n"

>       dep_file = parse(content, "tox.ini")

content    = ('[testenv:bandit]\n'
'commands =\n'
'\tbandit --ini setup.cfg -ii -l --recursive project_directory\n'
'deps =\n'
'\tbandit==1.4.0 # naaah, marked\n'
'\n'
'[testenv:manifest]\n'
'commands =\n'
'\tcheck-manifest --verbose\n')

tests/test_parse.py:80:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dparse/parser.py:506: in parse
return dep_file.parse()
content    = ('[testenv:bandit]\n'
'commands =\n'
'\tbandit --ini setup.cfg -ii -l --recursive project_directory\n'
'deps =\n'
'\tbandit==1.4.0 # naaah, marked\n'
'\n'
'[testenv:manifest]\n'
'commands =\n'
'\tcheck-manifest --verbose\n')
dep_file   = <dparse.dependencies.DependencyFile object at 0x7f8a56ced070>
file_type  = 'tox.ini'
marker     = ((), ())
parser     = None
path       = None
resolve    = False
sha        = None
dparse/dependencies.py:226: in parse
self.parser.parse()
self       = <dparse.dependencies.DependencyFile object at 0x7f8a56ced070>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <dparse.parser.ToxINIParser object at 0x7f8a56cee780>

def parse(self):
"""

:return:
"""
parser = ConfigParser()
>       parser.readfp(StringIO(self.obj.content))
E       AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

parser     = <configparser.ConfigParser object at 0x7f8a56cec470>
self       = <dparse.parser.ToxINIParser object at 0x7f8a56cee780>

dparse/parser.py:312: AttributeError
____________________________________________ test_update_tox_ini _____________________________________________

def test_update_tox_ini():
content = "[testenv:bandit]\n" \
"commands =\n" \
"\tbandit --ini setup.cfg -ii -l --recursive project_directory\n" \
"deps =\n" \
"\tbandit==1.4.0\n" \
"\n" \
"[testenv:manifest]\n" \
"commands =\n" \
"\tcheck-manifest --verbose\n"

>       dep_file = parse(content, "tox.ini")

content    = ('[testenv:bandit]\n'
'commands =\n'
'\tbandit --ini setup.cfg -ii -l --recursive project_directory\n'
'deps =\n'
'\tbandit==1.4.0\n'
'\n'
'[testenv:manifest]\n'
'commands =\n'
'\tcheck-manifest --verbose\n')

tests/test_updater.py:22:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dparse/parser.py:506: in parse
return dep_file.parse()
content    = ('[testenv:bandit]\n'
'commands =\n'
'\tbandit --ini setup.cfg -ii -l --recursive project_directory\n'
'deps =\n'
'\tbandit==1.4.0\n'
'\n'
'[testenv:manifest]\n'
'commands =\n'
'\tcheck-manifest --verbose\n')
dep_file   = <dparse.dependencies.DependencyFile object at 0x7f8a56cee4b0>
file_type  = 'tox.ini'
marker     = ((), ())
parser     = None
path       = None
resolve    = False
sha        = None
dparse/dependencies.py:226: in parse
self.parser.parse()
self       = <dparse.dependencies.DependencyFile object at 0x7f8a56cee4b0>
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <dparse.parser.ToxINIParser object at 0x7f8a56cee480>

def parse(self):
"""

:return:
"""
parser = ConfigParser()
>       parser.readfp(StringIO(self.obj.content))
E       AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?

parser     = <configparser.ConfigParser object at 0x7f8a56cee540>
self       = <dparse.parser.ToxINIParser object at 0x7f8a56cee480>

dparse/parser.py:312: AttributeError
============================================== warnings summary ==============================================
tests/test_updater.py::test_update_pipfile
/usr/lib/python3.12/site-packages/pipenv/environment.py:20: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
from pipenv.patched.pip._vendor import pkg_resources

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================== short test summary info ===========================================
FAILED tests/test_dependencies.py::test_parser_class - AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
FAILED tests/test_parse.py::test_tox_ini_with_invalid_requirement - AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
FAILED tests/test_parse.py::test_tox_ini_marked_line - AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
FAILED tests/test_updater.py::test_update_tox_ini - AttributeError: 'ConfigParser' object has no attribute 'readfp'. Did you mean: 'read'?
================================== 4 failed, 47 passed, 1 warning in 0.75s ===================================
```

> I am still not able to run pypy3 tests for the ebuild though. Is this pypy3 issue a gentoo only issue?

To run the test from the ebuild: `FEATURES="test" USE="test" emerge -1 -j1 dev-python/dparse`. Sometimes a failure is related to the ebuild sandboxing. However, I doubt that is the case here, since it works fine for pypy3 and python3.11.

**Comment by oz123** [comment]
I am not the upstream maintainer of dparse, but I can definitly take a look at the issue.
Shall I open a new PR for that issue?

**Review by AndrewAmmerlaan — CHANGES_REQUESTED** [review]
Per the [Ebuild File Formatting](https://devmanual.gentoo.org/ebuild-writing/file-format/index.html) guide lines, this should be `dparse-0.6.4_beta0.ebuild`. This ensures that portage treats this version as older then the upcoming `dparse-0.6.4.ebuild`.

**Comment by oz123** [comment]
@AndrewAmmerlaan thank you for the review again. I accidentally remove pydantic as a dependency. But it's still needed.
Upstream has still not migrated pydantic2 but gentoo does not have pydantic1 anymore.
That means that currently, pipenv isn't installable on gentoo.
Now what?

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan thank you for the review again. I accidentally remove pydantic as a dependency. But it's still needed. Upstream has still not migrated pydantic2 but gentoo does not have pydantic1 anymore. That means that currently, pipenv isn't installable on gentoo. Now what?

We still have pydantic-1.10.13: https://packages.gentoo.org/packages/dev-python/pydantic this should satisfy the dependency.  The CI complaint occurs because the dparse ebuild does not conform to the file naming guidelines, portage considers it an invalid file and it therefore cannot satisfy the dparse dependency in the pipenv ebuild.

**Comment by oz123** [comment]
OK, I have fixed the name for dparse, and also pinned pythonfinder version in pipenv. Hopefully this works now.

**Comment by oz123** [comment]
Note, I opened a bug for adding riscv architecture.
https://bugs.gentoo.org/919790

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1: 

For next time, could you use `git rebase` instead of `git merge` please? This makes live a bit easier on my end.

**Pull request closed without merging**
