### PR TITLE
www-apps/joomla: bump to www-apps/joomla-3.6.5

### PR DESCRIPTION
**Pull request by hnaparst**
Gentoo-Bug: https://bugs.gentoo.org/612650

Package-Manager: Portage-2.3.3, Repoman-2.3.1

http://filebin.ca/3G3IhO0cNAJg/build.log

### CODE REVIEW

**Comment by antematherian** [comment]
Joomla supports php-7.0 with version 3.6.5 and you should add mariadb and postgres support to the ebuild. At Funtoo we use this version of the ebuild: https://github.com/antematherian/archive-overlay/blob/master/www-apps/joomla/joomla-3.6.5.ebuild . There seem to be issues with php-7, but upstream officially started supporting php 7 with joomla-3.6.5, and a user should be able to install it. I didn't have time to submit a pull request to Gentoo for the version bump, you're free to use any changes you deem useful from my ebuild.

Just my two cents.

**Comment by hnaparst** [comment]
It is not necessarily the case that the database backend lives on the same computer as Joomla.  Thus, it would be a mistake to include database dependencies.  This was pointed out to me by dlan, the Gentoo developer who reviewed my ebuild.  Thank you for your comments.

**Comment by antematherian** [comment]
That makes sense, thank you for your comment. I guess that the only thing that might be relevant is this line: https://github.com/antematherian/archive-overlay/blob/master/www-apps/joomla/joomla-3.6.5.ebuild#L21 Can you verify that php needs to be built with the session use flag turned on for joomla to work properly? That's the only thing that might be useful to add. Anyway, thank you for the work on making joomla better!

**Comment by hnaparst** [comment]
Actually, I don't use Joomla at all.  If you use Joomla, and you want to maintain the e-build for Gentoo, be my guest.

**Comment by hnaparst** [comment]
I have asked if it would be possible to compile php with session support turned off.  I would question whether this question is more important to get an answer to than resolving the many security problems in the existing joomla version in portage, which this new version solves.

I would respectfully submit that merging the changes as proposed is the best thing for the Gentoo project, since it resolves many serious vulnerabilities.   If it turns out down the road that it is possible to remove session support, that could be changed in a future version of the ebuild.  For the present time, no one upstream seems to know the answer to this rather obscure question.

**Comment by hnaparst** [comment]
Upstream confirms that session support is required
https://forum.joomla.org/viewtopic.php?f=727&t=948458

**Comment by monsieurp** [comment]
joomla has been last-rited. See fe7d7445faf698a716e9f542fdc18b771fa42b6a.

**Pull request closed without merging**
