### PR TITLE
www-apps/gitea: version bump to 1.4.0

### PR DESCRIPTION
**Pull request by stefangweichinger**
Bug: https://bugs.gentoo.org/640764
Bug: https://bugs.gentoo.org/651498

### CODE REVIEW

**Comment by monsieurp** [comment]
@mrueg ?

**Comment by Perlovka** [comment]
@lafriks 
According to this https://docs.gitea.io/en-us/config-cheat-sheet , all changes should be done in `custom` directory, so app.ini is pretty useless. I think it's better to leave all files in /var/lib/gitea.

**Comment by lafriks** [comment]
@Perlovka yes but it is possible to set other location for configuration file, see:
https://docs.gitea.io/en-us/command-line/

**Comment by stefangweichinger** [comment]
Provide patches if you like. I don't see the real improvement in setting the different location. That just drifts off from upstream and irritates new gitea-users when they read upstream documentation. IMO.

**Comment by stefangweichinger** [comment]
see latest commit https://github.com/gentoo/gentoo/pull/7622/commits/4500df93f244a56dd89407b64908d40634d219a7 

upstream moved to 1.4.1 already ....

**Comment by Dessa** [comment]
@Perlovka but in the same line it does say distribution packaged versions install the config to /etc/gitea/conf/app.ini

/etc is generally better to have configs installed to since they are CONFIG_PROTECT'ed so something like dispatch-conf can handle it.

the config actually moved quite a lot. the config was in /usr/share initially (thats end of 2016), then 4 days after initial version it moved to /etc/gitea/conf/ then it moved to /var/lib/gitea one day later. why i have no real idea, but its been in its location long enough that it could be quite possibly be moved maybe @mrueg knows more about it.

@lafriks since when was it possible to specify a custom config on command line? maybe it wasn't possible in the 1.0 days and it was just carried over ever since.

thanks @mrueg for merging this now btw.

**Comment by lafriks** [comment]
@Dessa `-c` cli option has been around for two years at least probably even more

**Comment by Perlovka** [comment]
@Dessa yes, they said that custom/conf/app.ini in real distribution usually point to /etc/gitea/conf/app.ini.
But all other customizations (public files, page templates etc.) should be placed in the same directory (https://docs.gitea.io/en-us/customizing-gitea/). I think it's not good idea keep such files in /etc.

I agree that all config files should go to /etc, but this application does not allow to separate config file location and location of all other customizations. And this was the reason, why all files been moved to /var/lib, i suppose.

Anyway, the new ebuild main goal was to fix some bugs and set right ENV variables for the application, as stated in inital bug. And it is already in the tree (https://github.com/gentoo/gentoo/commit/7062b1979c463885eb37690519eccd51825e3a6b), so we could improve it further, if anyone have better solution =)

**Comment by Perlovka** [comment]
@stefangweichinger service file been not updated, it's still uses old environment:
`Environment="GITEA_CUSTOM=/var/lib/gitea"`

Should be
Environment="GITEA_WORK_DIR=/var/lib/gitea"

**Comment by lafriks** [comment]
@Perlovka it does support other location for configuration file, I have updated docs and sample startup files in gitea repository, see https://docs gitea.io/

**Comment by lafriks** [comment]
@Perlovka it is not required for configuration to be writeable if you do not use web install and pre-configure it manually. To generate required secrets it is possible to use gitea cli:
```
gitea generate secret INTERNAL_TOKEN
gitea generate secret LFS_JWT_SECRET
gitea generate secret SECRET_KEY
```
More details: https://docs.gitea.io/en-us/command-line/

**Comment by lafriks** [comment]
As for using git user I don't think anyone would be running multiple git server solutions on same server, imho
Just like https://wiki.gentoo.org/wiki/GitLab also does use `git` user that would conflict with git-shell usage

**Pull request closed without merging**
