### PR TITLE
toolchain.eclass: cleanup < GCC 8 debris

### PR DESCRIPTION
**Pull request by thesamesam**
If you need this, please use toolchain-legacy.eclass from the ::toolchain repository.

### CODE REVIEW

**Comment by thesamesam** [comment]
Reviewers: please take special care in checking some of the simplifications for the boolean expressions, in case I collapsed any of it wrongly

**Review by SoapGentoo — APPROVED** [review]
great cleanup!

**Review by ArsenArsen — APPROVED** [review]
lgtm

**Review by ionenwks — APPROVED** [review]
Cleans up more than I thought, very nice.

Went through the changes and bit of minor testing, but couldn't find any logic regressions -- not that I looked at this eclass as a whole much for the big picture.

**Comment by thesamesam** [comment]
Thank you for reviewing!

**Pull request closed without merging**
