### PR TITLE
net-libs/webkit-gtk: add eme-free flag [please reassign]

### PR DESCRIPTION
**Pull request by bqv**

### CODE REVIEW

**Comment by mattst88** [comment]
EME is basically DRM, like as required by Netflix?

**Comment by bqv** [comment]
> EME is basically DRM, like as required by Netflix?

Correct :)

**Comment by telans** [comment]
Perhaps the use flag should be called `eme-free`? It would match that of www-client/firefox

**Comment by bqv** [comment]
> Perhaps the use flag should be called `eme-free`? It would match that of www-client/firefox

@telans done :)

**Comment by leio** [comment]
So your goal is to enable experimental support for it, but it got changed to be named `eme-free` from something else (that I can't get a compare out of github from the force push anymore) based on earlier feedback?
As-is, this ends up enabling experimental support by default, and I don't think we want that. And `IUSE=+eme-free` would give a weird impression, I think

**Comment by bqv** [comment]
> So your goal is to enable experimental support for it, but it got changed to be named `eme-free` from something else (that I can't get a compare out of github from the force push anymore) based on earlier feedback? As-is, this ends up enabling experimental support by default, and I don't think we want that. And `IUSE=+eme-free` would give a weird impression, I think.
> 
> Edit: Based on PR summary change I see it was named IUSE=eme before the force push

Yes, originally I had the `eme` USE, not enabled by default, which enabled EME support. Then changed to `eme-free` to match firefox, which I suppose implicitly made it enable EME by default. What would you suggest as a resolution?

**Comment by leio** [comment]
To my knowledge, this doesn't bring any value to Gentoo, as it won't get you DRM working, sorry. There is no EME support in open source webkitgtk. More information on the closed bug.

**Pull request closed without merging**
