### PR TITLE
update my packages' metadata.xml to contain a name-tag

### PR DESCRIPTION
**Pull request by tomboy-64**
To fix some broken tools, I added the <name> tag to all the metadata files i'm listed in.

### CODE REVIEW

**Comment by mgorny** [comment]
What tools? Did you report a bug? Only `<email/>` is required.

**Comment by tomboy-64** [comment]
According to K_F and @idella at least euscan has problems with metadata.xml without a ```<name>``` tag.

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
@tomboy-64  can you split it, but still keep it one pull request, one commitper pkg.
Then good to go.

**Comment by tomboy-64** [comment]
@idella oh, how i love bash one-liners <3

**Pull request merged**
