### PR TITLE
app-laptop/tuxedo-drivers: add 4.11.3

### PR DESCRIPTION
**Pull request by immolo**
A user with a Tuxedo Stellaris Slim 15  are reporting drivers in tree are no longer working and following NixOS's advice we need to bump.

Using Mirko Guenther's work, I have bumped to the latest version and tested as far as I can but needs one user test before merging.

Once added I'll start the discussion about adding to the Gentoo install media as we should likely be carrying this there too.

Closes: https://bugs.gentoo.org/940899

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Kangie** [comment]
> error: initialization of ‘void (*)(struct platform_device *)’ from incompatible pointer type ‘int (*)(struct platform_device *)’ [-Wincompatible-pointer-types]
  124 |         .remove = tuxedo_nb04_kbd_backlight_remove


I swear I've patched this before in tuxedo stuff.

> gcc version 14.2.1 20240921 (Gentoo 14.2.1_p20240921 p1) 
> linux-6.11.5-gentoo

**Comment by Kangie** [comment]
```
# MODPOST /var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/Module.symvers
   scripts/mod/modpost -M -m       -o /var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/Module.symvers -n -T /var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/modules.order -i Module.symvers -e 
ERROR: modpost: "devm_led_classdev_multicolor_unregister" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_8291/ite_8291.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_register_ext" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_8291/ite_8291.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_register_ext" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_8291_lb/ite_8291_lb.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_unregister" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_8291_lb/ite_8291_lb.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_register_ext" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_829x/ite_829x.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_unregister" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/ite_829x/ite_829x.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_register_ext" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/tuxedo_nb04/tuxedo_nb04_kbd_backlight.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_unregister" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/tuxedo_nb04/tuxedo_nb04_kbd_backlight.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_register_ext" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/tuxedo_keyboard.ko] undefined!
ERROR: modpost: "devm_led_classdev_multicolor_unregister" [/var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/src/tuxedo_keyboard.ko] undefined!
make[3]: *** [scripts/Makefile.modpost:145: /var/tmp/portage/app-laptop/tuxedo-drivers-4.11.3/work/tuxedo-drivers-v4.11.3/Module.symvers] Error 1
```

**Comment by immolo** [comment]
> This looks suspiciously like a missing kconfig. These come from drivers/leds/led-class-multicolor: `CONFIG_LEDS_CLASS_MULTICOLOR`

Thanks added a check for this at https://github.com/gentoo/gentoo/pull/39473/commits/98e0983d6cc87525755d38426456bcda9216df6f#diff-5e9af9f10fcd140383983b63536d8bf6aee26831b54237f09af4df21978f6630R22-R29

Works very well when using with the correct version :)

**Comment by Kangie** [comment]
`${drm_helper_msg}`?

https://github.com/gentoo/gentoo/blob/0d02169e9ab82895e81b4a5168de4cbcb0b1c9ce/app-laptop/tuxedo-drivers/tuxedo-drivers-4.11.3.ebuild#L25-L33

**Comment by immolo** [comment]
> `${drm_helper_msg}`?
> 
I was using the `x111-drivers/nvidia-driver` as a reference, I only tested keeping the variable in  but as I can't find a noticeable change removing it this package I have removed it.

```
 * Checking for suitable kernel configuration options ...
 *   CONFIG_LEDS_CLASS_MULTICOLOR: is not set but needed for keyboard backlight
 *   CONFIG_INPUT_SPARSEKMAP: is not set but required for tuxedo-drivers
 *   CONFIG_IIO:	 is not set when it should be.                                                           [ !! ]
```

**Comment by mschiff** [comment]
I just pushed 4.11.4 to the tree before I saw you PR. Sorry for that.

So are there really missing config checks in the current ebuild or not? TIA

**Comment by immolo** [comment]
> I just pushed 4.11.4 to the tree before I saw you PR. Sorry for that.
> 
> So are there really missing config checks in the current ebuild or not? TIA
> 
> Edit: I just added the config checks to the more recent ebuild. Thanks for contributing!

Other than CONFIG_IIO and CONFIG_ERROR_LEDS_CLASS_MULTICOLOR this have always been in the ebuild the last two seem to be required since 4.5.

I just cleaned it up to make it more obvious to the user that they are missing.

**Pull request closed without merging**
