### PR TITLE
Add USE flag for mail functionality

### PR DESCRIPTION
**Pull request by shiftypenguin**
Just a tidbit for toggling the mail functionality in nethack.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Thank you for your work. Unfortunately, I'm going to have to reject it. Please make sure to read https://wiki.gentoo.org/wiki/Gentoo_GitHub and feel free to file another PR once you've understood the process.

**Comment by atlaua** [comment]
@shiftypenguin: monsieurp is referring to the 6 separate commits in
your PR. Those should be squashed into a single one, because it's a
single logical change. (This can be done with git rebase -i).

Anyway, there's no need for you to submit a new PR. I can change this
myself if you can convince me it's a good idea.

I don't understand why you want this USE flag, though. The code
overhead is negligible, and the mail feature can be disabled at runtime
using the 'mail' option. If you want to disable it globally for all
users, you can add "OPTIONS=!mail" in /etc/nethack.sysconf.

Cheers,
Luis Ressel

**Comment by shiftypenguin** [comment]
On my system(musl), nethack segfaults if /var/run/nscd/socket doesn't exist, even with !mail. After testing. it appears this is not the case for glibc.

I was under the impression that USE flags were a case of more is better, at least that was essentially what various users on IRC said.

**Comment by atlaua** [comment]
On Fri, 30 Jun 2017 13:05:58 -0700
shiftypenguin <notifications@github.com> wrote:

> On my system(musl), nethack segfaults if /var/run/nscd/socket doesn't
> exist, even with !mail. After testing. it appears this is not the
> case for glibc.

That's funny. And this segfault goes away when nethack is compiled with
-DNOMAIL? That'd be a strong case for introducing the 'mail' use flag;
musl compatibility is something I'm certainly interested in.

I'll have a look at this issue as soon as time permits. If I don't find
a better fix (perhaps it's an outright nethack bug that could be
patched?), I'll add the use flag.

Could you perhaps also investigate this a little further? In
particular, where does this access to the nscd socket come from?
Grepping the nethack sources for "nscd" doesn't yield anything, and
musl obviously doesn't hardcode anything about nscd either.

FWIW, I don't run nscd on any of my (glibc) machines, and I haven't run
into any nethack segfaults.

> I was under the impression that USE flags were a case of more is
> better, at least that was essentially what various users on IRC said.

Usually, but not always. USE flags also have an inherent cost, in
particular for the maintainer, who has to check that all possible USE
flag combinations still work after a version bump. Hence, USE flags
should only be added for features which introduce additional
dependencies, cause significant overhead or aren't configurable at
runtime.

**Comment by shiftypenguin** [comment]
Nethack calls getpwuid[0], which in musl calls __getpw_a(internal) which calls __nscd_query(internal) which does have it hardcoded[1]. On further review, it's not a lack of nscd that causes the segfault, it's the lack of a valid /etc/passwd. Test programs[2] demonstrate that the segfault does not occur in musl.

I had assumed it was the fault of nscd since it was the last system call before the segfault, my mistake.

[0] https://github.com/NetHack/NetHack/blob/e14120b282a1f233be29d9fbcdf0225e78d974e0/src/mail.c#L57
[1] http://git.musl-libc.org/cgit/musl/tree/src/passwd/nscd_query.c#n15
[2] https://github.com/shiftypenguin/pwtest

**Comment by mgorny** [comment]
You are not checking the return value. AFAICS, nethack doesn't do that either. If you don't check for errors, don't complain when stuff segfaults because you play with a NULL pointer. Unless it's not NULL, which you should prove by testing for it.

**Comment by shiftypenguin** [comment]
> You are not checking the return value. AFAICS, nethack doesn't do that either.

And that is precisely why I didn't. I was demonstrating why it segfaults. Nothing more.

**Pull request closed without merging**
