### PR TITLE
sci-libs/cantera: 3.0.0 version bump

### PR DESCRIPTION
**Pull request by band-a-prend**
* New release is compatible with `cython-3`.
* The `USE="cti"` is dropped due to supplied converters have restricted functionality or doesn't work (`yaml2ck`) without full python support.
* Python examples aren't provided within tarball since this release.
* `USE="lapack"` support is still restricted using `>=sundials-6.5.0`.
* add `USE="hdf5"` for HDF5 container files support via new package `sci-libs/HighFive` (header-only library).

Closes: https://bugs.gentoo.org/913141
Bug: https://bugs.gentoo.org/888667

P.S.  
The `cantera-3.0.0_env.patch` contains hunk that makes the versioned/sonamed library from plugin library that is opened via `dlopen` (see https://github.com/Cantera/cantera/pull/1613 for details).
Is there preferred place for plugins installation in Gentoo instead of common under `/usr/{lib,lib64}`? Mentioned patch is used to avoid
```
* QA Notice: The following shared libraries lack a SONAME
* /usr/lib64/libcantera_python3_11.so
```

E.g. I see that `media-gfx/nomacs` plugins are versioned.

Should `QA_SONAME_NO_SYMLINK` be used instead of patching in this case?

---

Update:
The `QA_SONAME="usr/lib.*/libcantera_python3.*.so"` is added instead of `cantera-3.0.0_env.patch` hunk with soname/versioned of `/usr/lib64/libcantera_python3_11.so`. There is no problem to patch to install library under e.g. `/usr/lib64/cantera/libcantera_python3_11.so` and to patch `src/base/application.cpp` to load it from this absolute path but then appropriate test will fail.

### CODE REVIEW

**Comment by band-a-prend** [comment]
I'm thinking about placing the `libcantera_python3_11.so` into `/usr/lib/python3_11/site-packages/cantera/` with patching path within `src/base/application.cpp`. But it could require to copy this library on src_test phase into appropreate relative path to find it on testing.

**Comment by band-a-prend** [comment]
Ping!

**Comment by thesamesam** [comment]
i think we should try to put it under a subdir in `/usr/$(get_libdir)/cantera` as this is convention for plugins. But I wonder - if these are for Python, shouldn't they be in site-packages so that python can actually `import` them? Or am I misunderstanding how it's used?

(What do upstream say about this? `/usr/$(get_libdir)` feels clearly wrong and it shouldn't even work for Python imports...)

**Comment by band-a-prend** [comment]
This plugin is for non-python applications that provides interface to python `ExtensibleRate` class and it's library isn't imported by python scripts. It's loaded e.g. by C++ applications. So python-site-packages dir isn't good place.

The discussion with upstream was here https://github.com/Cantera/cantera/pull/1613 and the path to this plugin currently is hardcoded into `Application::loadExtension` method of `application.cpp`. I could patch it to use `/usr/$(get_libdir)/cantera` path but last problem for me was to patch the test environment to find this plugin. Currently I could disable this appropriate test as it's separate feature for someone who want write own C++ application and use the method provided by plugin.

**Comment by band-a-prend** [comment]
I added setarate commit where changed installation and search path of `libcantera_python3_*.so` plugin to `/usr/$(get_libdir)/cantera` directory. Now appropriate scons test and example from user directory successfully run as dlopen() find plugin in both cases.

**Comment by thesamesam** [comment]
Thank you and I apologise for the wait. It has been hectic IRL.

**Comment by band-a-prend** [comment]
Don't worry! :) Thank you for review.

**Pull request closed without merging**
