### PR TITLE
gui-wm/dwl: fix nonexistent ${S}

### PR DESCRIPTION
**Pull request by sevz17**
and install desktop file (only for 0.4)

ups...

@thesamesam

### CODE REVIEW

**Comment by thesamesam** [comment]
I'm going to refrain from comment wrt desktop file 😛

**Comment by thesamesam** [comment]
merged w/ e9a788630a7c0305474f2c3f8fd2faf4520b1fb7 too (see commit msg), thx

**Comment by sevz17** [comment]
> merged w/ [e9a7886](https://github.com/gentoo/gentoo/commit/e9a788630a7c0305474f2c3f8fd2faf4520b1fb7) too (see commit msg), thx

Thanks, and... sorry for the trouble (how embarrassing, I just want to disappear...)

**Comment by thesamesam** [comment]
been there many a time, don't stress over it - the feeling one has from it is enough to make sure it doesn't happen again, you don't need a telling off. relax!

**Pull request closed without merging**
