### PR TITLE
dev-python/xmlschema: version bump to 1.2.5, update metadata

### PR DESCRIPTION
**Pull request by wimmuskee**
- add upstream ids to metadata

Signed-off-by: Wim Muskee <wimmuskee@gmail.com>

### CODE REVIEW

**Review by mgorny — CHANGES_REQUESTED** [review]
Tests fail: 
[dev-python:xmlschema-1.2.5:20201101-074705.log](https://github.com/gentoo/gentoo/files/5470351/dev-python.xmlschema-1.2.5.20201101-074705.log)

**Comment by wimmuskee** [comment]
confirmed, I was testing with a network connection, gonna figure out if those tests should be skipped (there are others that require network that are skipped), or the xsd's can be referred locally

**Comment by wimmuskee** [comment]
@mgorny This was a known issue upstream, https://github.com/sissaschool/xmlschema/issues/206, applied the patch provided there.

**Review by mgorny — APPROVED** [review]
Thank you!

**Pull request closed without merging**
