### PR TITLE
net-print/hplip-plugin: bump to 3.19.5

### PR DESCRIPTION
**Pull request by xdch47**
Package-Manager: Portage-2.3.66, Repoman-2.3.13
Signed-off-by: Felix Neumärker <xdch47@posteo.de>

### CODE REVIEW

**Comment by stefson** [comment]
would you mind to add dev-libs/libusb-compat as a dep? it's gentoo bug 684428

**Comment by xdch47** [comment]
Additional bump to `EAPI7` - add support for `arm` / `arm64`

**Comment by xdch47** [comment]
use the defaults of `unpacker` eclass -> makeself extraction recognized by `.run` extension

**Comment by elsandosgrande** [comment]
Any news on when this pull request will get merged?

**Comment by xdch47** [comment]
never…

**Comment by stefson** [comment]
why not?

**Comment by xdch47** [comment]
simple bump has been done ~ 1 week ago - see: https://github.com/gentoo/gentoo/commits/d64acf53dbaea549f68daa42913b71babe95af2a

well, i don't know… community driven? bug tracker ? what's the use of it?

**Comment by stefson** [comment]
The problem with some packages is that the teams behind it are virtually non existent, which is essentially a lack of manpower. True for gaming team, and so it seems true for printing team. #12438 is supposed to fix four CVE's and is stuck since a month. 

In case of hplip-plugin, you can't really assign this pullrequest to maintainer, as it's the printing team. Have you tried to write an email to the last person who did a commit on the package, so that they are able to learn of this request here? 

P.S: keywording not yet keyworded packages should be done by the ${arch} team

**Comment by a17r** [comment]
Unfortunately, for packages with maintainers, situations like these are always going to happen. github notification system is super bad and not everyone is even looking at github for existing work prior to bumps.

@billie80 does most of the work on hplip*, maybe something of this PR is salvageable?

**Comment by stefson** [comment]
I think the keywording will be rejected, but other than that it seems fine. Mind you, I tested the ebuild on my rpi2 - packages emerges fine, maybe I can find some time to actually do runtime testing. 

@xdch47 maybe you want to do a rebase without the keywording? I know it's frustrating though. 

also @mrueg has done some revbumps in the past.

**Comment by xdch47** [comment]
well, yes the ${arch} team…;  i feel like all those Q/A stuff and rules are doing exactly the opposite of its purpose…  destroying the community spirit and update-to-date characteristic - debain stable will soon take over with more fresh/ less outdate package, if thing are keep going like this.

**Comment by xdch47** [comment]
Moving a package from ~arch to arch is done only by the relevant arch teams ? 
but introducing ~arch as well ? a hassle…

**Comment by a17r** [comment]
That's what keywording bugs are for.

**Comment by stefson** [comment]
true, I've got a ton of packages emerged on arm with `**` keywords. If I was member of arm team, that qualified them for keywording, but I'm not, so yeah :-)

**Comment by xdch47** [comment]
in https://devmanual.gentoo.org/keywording/index.html it's just mention for moving form ~arch to arch, but anyways - i also have a fat `**` package.accept_keywords list on arm - at least now know the reason why…
just don't understand if it is lacking of man power, why spending time with an  `~arch` team ??? 
come on it's an **unstable** keyword

**Comment by a17r** [comment]
But it is right there in your link:

``Important: New packages should be marked as ~arch only upon architectures for which the committing developer has tested.``

If no one files keywording requests, then no one knows. If you do the work already, you may as well become arch team tester or communicate with them.

**Comment by billie80** [comment]
@xdch47: Thank you very much for your contribution. I only maintain hplip but not the plugins. Mainly because they are a source of trouble, binary and I can not test them fully as I do not own hardware requiring a plugin.

You may have recognised that the most recent version of hplip is 3.19.6. If yo could update your pull request for the plugins to 3.19.6 I will commit the changes for you. But please consider this an exception. Also you are responsible for picking up the pieces if there are any issues.

**Comment by xdch47** [comment]
well, I agree it's a source of trouble… however, unfortunately i've such a print device which relays on the plugin…
i think there might be other users as well who like to see it in the portage tree.

there haven't be *real* changes - trivial bump with some cleanup work + adding a dependency.

PR is #12717

thank you.

**Comment by stefson** [comment]
uhm, you did strip the arm and aarch64 love?

**Comment by billie80** [comment]
No but you did. Take a look at your pull request!

**Comment by stefson** [comment]
duh? The only thing that got fixed is the missing libusb-comp dependency via the virtual, also it certainly wasn't me who wrote the code to support arm/aarch64. keywording is done by the responsible team, but it should be fine to add the code, so users can use the package with `**` keywords.

**Comment by billie80** [comment]
I don't get it. It was in your changes and has not been there before. So technically you wrote it.

I have added support for arm only as there is no arm64 support for hplip. Something which you should have checked before as well.

**Comment by billie80** [comment]
@stefson Sorry about the last two comments I mistook you for @xdch47.

I do not know If he let this changes out deliberately. As I said I added support for arm but not arm64 as hplip is not keyworded on arm64.

**Comment by stefson** [comment]
Ah, lovely, you pushed the arm code! 
You could still add the aarch64 code as in

```
aarch64)   hplip_arch="arm64"  ;;
```

but without the keywording. 

The lack of keywords, despite packages emerging without any problems, is a super common thing on arm. It's not much of a big deal for users to set them in their keyword file.

**Comment by xdch47** [comment]
yes, after the discussion, i just strip them because i thought is has to be done be the arch team and was happy that it finally got merged !
>I think the keywording will be rejected, but other than that it seems fine.

**Comment by stefson** [comment]
Actually, I really meant it that way: keywording as in adding an ~arm keyword to the ebuild is done by the ~arm team, while the rest of the code is fine. Same goes for aarch64.

**Comment by xdch47** [comment]
okay then i competely misunderstood - next time

**Pull request closed without merging**
