### PR TITLE
sci-libs/openblas: add new version 0.3.7

### PR DESCRIPTION
**Pull request by cdluminate**
@heroxbd 

Version bump is enough. No diff in the ebuild file.

### CODE REVIEW

**Comment by heroxbd** [comment]
Please use `repoman` for the commits.

**Comment by cdluminate** [comment]
Are the GPG signature mandatory? It's just not convenient for me to sign a commit on remote machine.

**Comment by heroxbd** [comment]
> Are the GPG signature mandatory? It's just not convenient for me to sign a commit on remote machine.

GPG sig is not needed, because I will sign it before commit anyway.

By the way, I am using gpg-agent forwarding for signing things remotely.

**Comment by heroxbd** [comment]
@cdluminate Have updated your commits with `repoman`?

**Comment by cdluminate** [comment]
Does it look good now?

**Pull request closed without merging**
