### PR TITLE
sci-physics/geant-vmc: new package.

### PR DESCRIPTION
**Pull request by olifre**
Geant4 VMC represents the realisation of the
Virtual Monte Carlo (VMC) for Geant4.

Package-Manager: Portage-2.3.24, Repoman-2.3.6
RepoMan-Options: --force

This replaces #7088 , ping @amadio who was reviewing the package there.

### CODE REVIEW

**Comment by olifre** [comment]
I now tested the package against `=sci-physics/root-6.14.02` and `=sci-physics/geant-4.10.03-r1`. 
All tests work for me when activating the USE-flags: `g4root geant3 mtroot test vgm` for `geant-vmc`. 

Sadly, some tests fail for `=geant-vmc-9999` (but that should be an upstream issue) and some tests also fail if I disable the `geant3` flag. I am unsure if the test-suite can be instructed accordingly...

**Comment by amadio** [comment]
Thanks, @olifre. I will have a look at this today, and merge once I test it too.

**Comment by amadio** [comment]
Unfortunately, ROOT requires things linked against it to use the same C++ standard, and when I tried to emerge this package, it didn't work because the standard is not enforced to be the same as ROOT. I'm not quite sure how we should tackle this yet, but one idea is to use `append-flags $(root-config --cflags)` in ebuilds that depend on ROOT. Otherwise if I install ROOT with USE=root7, which enables C++14 support, packages linked against ROOT will break, like this one did.

**Comment by amadio** [comment]
Actually, sci-physics/vgm is also broken and fails for me with USE=root. We need to find a way to fix these. That may involve changing how ROOT works in Gentoo as well.

**Comment by olifre** [comment]
@amadio : Ah! I was unaware that the `root7` flag changes the C++ standard ROOT is compiled with. Yeah, that naturally has to break anything, also any user code not aware of that, which tries to link against it. 
I'd claim this should be fixed upstream - we should not run `root-config` in the ebuild, but rather the CMake build systems of `sci-physics/vgm` and `sci-physics/geant-vmc` should choose the correct C++ standard matching the installed ROOT. 

So my plan would be:to prepare an upstream patch for both `sci-physics/geant-vmc` and `sci-physics/vgm` doing that, and incorporating this into the packages until the next release happens. 

However - I wonder whether the `root7` flag as such is something portage can handle correctly. 
We have a serious problem in the following case:
- User build `sci-physics/root[root7]` and several packages linking against it. 
- User rebuilds the same version of `sci-physics/root` but without `root7`. 
- Portage will see no need to rebuild the packages linking against it! 
Portage can only trigger rebuild via slot dependencies, though, or by a use flag present and changed for both packages. 

So in my opinion, `sci-physics/root` needs to be fixed to allow this, as follows:
- Adding the `c++14` flag to `sci-physics/root` and making the `root7` flag depend on it:
```REQUIRED_USE="root7 ? ( c++14 )"```
- Using that to set `-Dcxx14=`. I think that a user may want to set this independently anyways - right? Also, it will make this significant change, which may also break user code, much more obvious, which is otherwise hidden behind `root7` only. 
- Add the `c++14` flag to both `sci-physics/vgm` and `sci-physics/geant-vmc` and have them do 
```
DEPEND="c++14? (sci-physics/root[c++14])
!c++14? (sci-physics/root[-c++14])
```

What do you think?

**Comment by olifre** [comment]
> sci-physics/vgm is still broken with FEATURES=test USE=-root, unfortunately.

Yes - upstream's test suite will not work correctly in this configuration. 
I'm not sure whether I will get this patched upstream, I'd claim this is still better than disabling tests completely. Maybe I should add an `ewarn` that the only supported USE-flag combination by upstream is with `root`?


> Maybe it's better to keep both geant-vmc and vgm in the science overlay until they are mature enough for the main tree...

Since they are not accepting any PRs anymore since about a year, many packages in `sci` are by now broken and outdated. So I'd vote against this solution, and rather fix the known issues here.

**Comment by olifre** [comment]
> one idea is to use append-flags $(root-config --cflags) in ebuilds that depend on ROOT.

I think that's a bad idea, and even violates how portage works. It will essentially inherit also the user chosen CFLAGS from ROOT, so per-package-CFLAGS are broken. 
I'll patch upstream to only inherit the C++-standard and allow overriding it instead.

**Comment by amadio** [comment]
For vgm, if it only works with a certain `USE` combination, then we should remove the broken combination by removing the `USE=root` flag altogether. As for the C++ standard, we could make it a USE flag, as in some other projects, and add dependencies with a particular standard, e.g. sci-physics/root[cxx11], or similar. It had something like that in the past. Maybe it's worth discussing with other devs how to treat packages that cannot use different C++ standard, because if Geant4 locks packages to C++11 and ROOT locks packages to C++14, then we cannot install any package that depends on both of them afterwards, for example. I've complained to the team about this, but it's not seen as a problem yet. I'll bring this up again with them.

**Comment by amadio** [comment]
> Oh, that's funny. Upstream is already correctly checking for -std=c++14 in ROOT's cflags

```bash
$ root-config --cflags
-pthread -std=c++1y -m64 -march=native -O2 -pipe -I/usr/lib64/root/6.14/include
```
Maybe upstream needs to check for `c++1y` too?

**Comment by olifre** [comment]
> For vgm, if it only works with a certain USE combination, then we should remove the broken combination by removing the USE=root flag altogether.

The package can also be used without `root`, but the test suite will bail. 
I guess I'll go with `RESTRICT` to disable tests for that combination. Will prepare a PR on this shortly, and also update the `sci-physics/geant-vmc` ebuild here to disable tests in combinations where upstream does not test the test suite. 



> I'll bring this up again with them.

Thanks! Further input on this would indeed be helpful. The only way I see right now would be to add `c++14` and `c++11` flags to `sci-physics/root`, `sci-physics/geant` and anything dependent on any of these, and then express dependencies in portage. Let me know how to proceed once you have a reply. 



> Maybe upstream needs to check for c++1y too?

Yes, this they don't do. 
But the fact that `c++1y` is shown there indeed seems to be caused by a serious bug in `root-config`. I'll open a ticket with upstream on that and link it here.

**Comment by olifre** [comment]
@amadio The explanation is simple for `sci-physics/vgm`. There has been no new release after they added detection of `sci-physics/root` build with `c++14`. `=sci-physics/vgm-9999` works fine. 

I'll make `=sci-physics/vgm-4.4` depend on `sci-physics/root[-root7]` then. 
For `sci-physics/geant-vmc`, the detection appears to work, but things break later in the build. I'm on it.

**Comment by olifre** [comment]
@amadio Ok. This happens with `sci-physics/geant-vmc` if `sci-physics/geant` is not build with `c++14`, but only ROOT is. There's also no useflag for that (yet) in `sci-physics/geant`. 

Can you confirm your `sci-physics/geant` is not build with C++14?

**Comment by amadio** [comment]
Yes, I have Geant with C++11 and ROOT with C++14.

**Comment by olifre** [comment]
Thanks, this clarifies that. 
So there are two approaches we could take:

1) 
Have `sci-physics/geant-vmc` block `sci-physics/root[-root7]` for now, since this can never work with the current state of `sci-physics/geant`, and get this package in soon. 
Then, subsequently, start discussion with other devs on how to approach this. My feeling is we need `c++11` and `c++14` flags for all packages we're looking at now, but maybe there's a more elegant approach. 

2)
Wait for discussion results first.

**Comment by olifre** [comment]
I've updated this PR with the following changes: 
- Restrict tests to the useflag-combination for which upstream supports testing. 
- Depend on `sci-physics/root[-root7]`. 

In case you go with option 1 and this passes your testing, I believe it could go in as-is.

**Comment by olifre** [comment]
Thanks to you, too!

**Comment by olifre** [comment]
@amadio Shall we / I close the PR, or do you want to leave it open in case the behaviour of the `root7` flag on `sci-physics/root` changes?

**Comment by amadio** [comment]
No, we can close this. I just keep forgetting to add the magic tag to make it close automatically...

**Comment by olifre** [comment]
@amadio It seems current `=sci-physics/root-6.14.06` has changed the behaviour and now there are `c++11`, `c++14` and `c++17`. I appreciate this change, however defaulting to `c++14` breaks:
- `sci-physics/geant-vmc`
- `sci-physics/vgm`
- any user code linking against ROOT and Geant when Geant is compiled wiht `c++11`. 

Which path should we follow to resolve this? There are several things which should be solved before / synchronously to adding these flags to `sci-physics/root`:
- Adapt `sci-physics/geant`to also accept these flags. 
- Have all mentioned packages force `sci-physics/root[c++11]`. 
- Subsequently, try to adapt upstream code for the new C++ standards, and then depend on geant + root using the same C++ standard. 

Right now, several in-tree packages are broken by that change, so I think we should first consider the best way to go before changing root alone and breaking everything else.

**Comment by olifre** [comment]
> Ideally, the dependencies should configure themselves to use the same C++ standard as ROOT, since that's a requirement.

I agree, this could be fixed in upstreams (VGM, geant-vmc), and while it is not, I could add that to required_use of geant-vmc and vgm. 
However, since e.g. geant-vmc depends on both geant and root, this means that a user of geant-vmc needs to have both geant and root with exactly the same standard. Without useflags for c++11 and c++14 on geant, this can't be done. 

So I would vote for reverting the default to C++11 for now, I will check if I can adapt upstreams codebases of VGM and geant-vmc with PRs within the next days (or maybe weeks, not sure how complex it is), and we need to find a solution for Geant, since a proper solution is only possible if also Geant is built with the same standard.

**Comment by olifre** [comment]
(unrelated: https://bugs.gentoo.org/671810 is also a regression in the most recent version of the root ebuild / build system for you )

**Comment by olifre** [comment]
> I will check if I can adapt upstreams codebases of VGM and geant-vmc with PRs within the next days

I checked geant-vmc right now. It already does the right thing for anything that purely links against root, i.e. it takes over the standard as exposed by `root-config`. However, stuff which links against root + geant takes over the flags from ROOT and Geant, and Geant wins. For Gentoo, Geant4 - is always built with C++11 as of now, so that breaks compilation against a C++14 root.

**Pull request closed without merging**
