### PR TITLE
app-editors/{neovim,vim-core}: Remove textwidth=78 *.txt autocommands, fixes #559800

### PR DESCRIPTION
**Pull request by waldolemmer**
This PR modifies autocommands in vimrc and sysinit.vim so `set textwidth=78` is no longer automatically executed on .txt files, but instead on ebuilds and eclasses. This follows from [a complaint in the forums](https://forums.gentoo.org/viewtopic-p-8450986.html?sid=259d4a127ff952898585d3af4ee29333#8450986) as well as [bug 559800](https://bugs.gentoo.org/559800).

This is my first PR here, so go easy on me :)

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by floppym — CHANGES_REQUESTED** [review]
We don't want to wrap ebuilds and eclasses at 78 characters either.
Please just drop the code entirely.

**Review by floppym — CHANGES_REQUESTED** [review]
Thanks, that looks good.

Please revbump the associated ebuilds so that this change actually gets pushed out for existing users.

**Comment by thesamesam** [comment]
Please include rationale in the commit messages (at the least the stuff you said in the PR body, maybe more). It also needs a `Closes:` tag for the bug.

**Comment by waldolemmer** [comment]
@thesamesam Will do. The vim-core commit has a `Closes:` tag, but I'll add it to the neovim one as well.

**Comment by thesamesam** [comment]
I'll wait for @xxc3nsoredxx to comment.

**Comment by xxc3nsoredxx** [comment]
Does it make sense for both commits to have a `Closes:` tag for the bug? Maybe just a `Bug:` tag on one of them? This may just be a question of aesthetics, not a huge deal.

Otherwise, LGTM (at least as far as `vim-core` is concerned).

**Comment by waldolemmer** [comment]
> Maybe just a `Bug:` tag on one of them? This may just be a question of aesthetics, not a huge deal.

@xxc3nsoredxx Should I make that change before this gets merged? It would require another force push, and therefore another review from your side.

Also, should we wait for @listout's approval? I'm not familiar with Gentoo's policy/procedure.

**Comment by waldolemmer** [comment]
I changed "Closes" to "Bug".

**Pull request closed without merging**
