### PR TITLE
app-text/recode: revbump, fix build for clang16

### PR DESCRIPTION
**Pull request by Schievel1**
Closes: https://bugs.gentoo.org/879649

Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

### CODE REVIEW

**Comment by Schievel1** [comment]
I ran this with the hooks from https://gist.github.com/thesamesam/4ddaa95f3f42c2be312b676476cbf505 and it at least fixes the 
```+ignoreme: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
 main ()
      ^
       void
```
Is this already enough?

**Comment by Schievel1** [comment]
Shall we remove 3.7.11 and 3.7.9?

**Comment by thesamesam** [comment]
> Shall we remove 3.7.11 and 3.7.9?

yes. Is that the only reason still draft, or any other issues?

**Review by thesamesam — APPROVED** [review]

**Comment by Schievel1** [comment]
> > Shall we remove 3.7.11 and 3.7.9?
> 
> yes. Is that the only reason still draft, or any other issues?
> 
> (cleanup in separate commit)

Actually because of 
> Is this already enough?

Those silent errors in configure are a bit confusing to me. I don't like it when I can't be sure if a problem is fixed or not.

**Comment by thesamesam** [comment]
The hook works a bit better now so should help you see problems. Let me know if it needs more work. This is still a new problem we're all trying to handle so we might be able to make some changes to help debugging!

PR looks good, thank you!

**Pull request closed without merging**
