### PR TITLE
net-wireless/gnuradio: fix 3.10.3.0 build problem

### PR DESCRIPTION
**Pull request by vowstar**
Fix static assertion failed : Cannot format an argument
Fix error: ‘HUGE_VAL’ was not declared in this scope

Closes: https://bugs.gentoo.org/858659
Closes: https://bugs.gentoo.org/858665

### CODE REVIEW

**Comment by vowstar** [comment]
Should fix https://github.com/gentoo/gentoo/pull/26774 first to prevent build issue of freedv

**Comment by vowstar** [comment]
libfmt-9.0.0 require explicit tagging of ARG types. This commit
adds those tags for the types that are currently formatted via fmt.
Pull request to upstream: https://github.com/gnuradio/gnuradio/pull/6053

**Comment by dl1jbe** [comment]
Looks like the two patch files are missing. Please add.

**Comment by vowstar** [comment]
> Looks like the two patch files are missing. Please add.

Done

**Comment by dl1jbe** [comment]
Very well and many thanks for looking into the problem and providing a solution.
Your patches will be added shortly to the tree.

**Pull request closed without merging**
