### PR TITLE
[CI test] de-stabilise more hppa

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by Arfrever** [comment]
Instead of de-stabilization, it is better to add `>=kde-frameworks/extra-cmake-modules-5.37 test` (or just `kde-frameworks/extra-cmake-modules test`) to `profiles/arch/hppa/package.use.stable.mask`.

**Comment by a17r** [comment]
@trofi please advise if it is worth keeping those keywords to add even more content to `profiles/arch/hppa/package.use.stable.mask` or rather drop from stable as proposed.

**Comment by a17r** [comment]
slyfox agreed with dropping the keywords.

 @Arfrever @gentoo/cjk any objections?
@xmw any objections?

**Comment by trofi** [comment]
Let's drop down to ~hppa. C++ is very slow on hppa.

**Comment by Arfrever** [comment]
Clarification in IRC:
```
<+[Arfrever]> slyfox: You supposedly agreed with dropping of what exactly to ~hppa?
<@slyfox> i was ok to drop qt stuff for hppa
```
Anyway I accept destabilization for app-i18n/fcitx and x11-terms/mlterm.

**Pull request closed without merging**
