### PR TITLE
sci-libs/m4ri: New upstream release.

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-2.3.79, Repoman-2.3.16
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>

### CODE REVIEW

**Comment by kiwifb** [comment]
Yes, I'd like some more info. I tried a few combinations, in particular to see if the `-O1` was still needed. So I definitely want to know the failure(s), the useflags and cflags that go with it.

**Comment by orlitzky** [comment]
Environment:
```sh
CFLAGS="-O2 -pipe -march=native"
CHOST="x86_64-pc-linux-gnu"
CXXFLAGS="-O2 -pipe -march=native"
FCFLAGS="-O2 -pipe -march=native"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
MAKEOPTS="-j5"
```

Emerge and configure output:

```
$ sudo ACCEPT_KEYWORDS="~amd64" FEATURES=test emerge -v1 m4ri

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] sci-libs/m4ri-20200115::gentoo [20140914::gentoo] USE="openmp -debug -png -static-libs (-test%)" CPU_FLAGS_X86="sse2" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB


>>> Verifying ebuild manifests
>>> Running pre-merge checks for sci-libs/m4ri-20200115

>>> Emerging (1 of 1) sci-libs/m4ri-20200115::gentoo
 * m4ri-20200115.tar.gz BLAKE2B SHA512 size ;-) ...                      [ ok ]
>>> Unpacking source...
>>> Unpacking m4ri-20200115.tar.gz to /var/tmp/portage/sci-libs/m4ri-20200115/work
>>> Source unpacked in /var/tmp/portage/sci-libs/m4ri-20200115/work
>>> Preparing source in /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115 ...
 * econf: updating m4ri-20200115/config.sub with /usr/share/gnuconfig/config.sub
 * econf: updating m4ri-20200115/config.guess with /usr/share/gnuconfig/config.guess
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/m4ri-20200115 --htmldir=/usr/share/doc/m4ri-20200115/html --with-sysroot=/ --libdir=/usr/lib64 --disable-debug --enable-openmp --disable-png --enable-sse2 --disable-static
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-gnu
checking for a BSD-compatible install... /usr/lib/portage/python3.6/ebuild-helpers/xattr/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking whether make supports the include directive... yes (GNU style)
checking for x86_64-pc-linux-gnu-gcc... x86_64-pc-linux-gnu-gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether x86_64-pc-linux-gnu-gcc accepts -g... yes
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C89... none needed
checking whether x86_64-pc-linux-gnu-gcc understands -c and -o together... yes
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking for ld used by x86_64-pc-linux-gnu-gcc... /usr/x86_64-pc-linux-gnu/bin/ld
checking if the linker (/usr/x86_64-pc-linux-gnu/bin/ld) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/x86_64-pc-linux-gnu-nm -B
checking the name lister (/usr/bin/x86_64-pc-linux-gnu-nm -B) interface... BSD nm
checking whether ln -s works... yes
checking the maximum length of command line arguments... 1572864
checking how to convert x86_64-pc-linux-gnu file names to x86_64-pc-linux-gnu format... func_convert_file_noop
checking how to convert x86_64-pc-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/x86_64-pc-linux-gnu/bin/ld option to reload object files... -r
checking for x86_64-pc-linux-gnu-objdump... x86_64-pc-linux-gnu-objdump
checking how to recognize dependent libraries... pass_all
checking for x86_64-pc-linux-gnu-dlltool... no
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for x86_64-pc-linux-gnu-ar... x86_64-pc-linux-gnu-ar
checking for archiver @FILE support... @
checking for x86_64-pc-linux-gnu-strip... x86_64-pc-linux-gnu-strip
checking for x86_64-pc-linux-gnu-ranlib... x86_64-pc-linux-gnu-ranlib
checking command to parse /usr/bin/x86_64-pc-linux-gnu-nm -B output from x86_64-pc-linux-gnu-gcc object... ok
checking for sysroot... /
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for x86_64-pc-linux-gnu-mt... no
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... x86_64-pc-linux-gnu-gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if x86_64-pc-linux-gnu-gcc supports -fno-rtti -fno-exceptions... no
checking for x86_64-pc-linux-gnu-gcc option to produce PIC... -fPIC -DPIC
checking if x86_64-pc-linux-gnu-gcc PIC flag -fPIC -DPIC works... yes
checking if x86_64-pc-linux-gnu-gcc static flag -static works... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... yes
checking if x86_64-pc-linux-gnu-gcc supports -c -o file.o... (cached) yes
checking whether the x86_64-pc-linux-gnu-gcc linker (/usr/x86_64-pc-linux-gnu/bin/ld -m elf_x86_64) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no
checking for x86_64-pc-linux-gnu-gcc option to accept ISO C99... none needed
checking for x86 cpuid 0x00000001 output... 100f42:3040800:802009:178bfbff
checking whether mmx is supported... yes
checking whether sse is supported... yes
checking whether sse2 is supported... yes
checking whether sse3 is supported... yes
checking whether ssse3 is supported... no
checking whether C compiler accepts -mmmx... yes
checking whether C compiler accepts -msse... yes
checking whether C compiler accepts -msse2... yes
checking whether C compiler accepts -msse3... yes
checking mm_malloc.h usability... yes
checking mm_malloc.h presence... yes
checking for mm_malloc.h... yes
checking for working posix_memalign... yes
checking for OpenMP flag of C compiler... -fopenmp
checking for PAPI_start_counters in -lpapi... no
checking for x86 cpuid 0x0 output... 5:68747541:444d4163:69746e65
checking for the processor vendor... AMD
checking for x86 cpuid 0x0 output... (cached) 5:68747541:444d4163:69746e65
checking for the processor vendor... (cached) AMD
checking the L1 cache size... 65536 Bytes
checking the L2 cache size... 524288 Bytes
checking the L3 cache size... 6291456 Bytes
checking whether to build with PNG support... no
checking whether make sets $(MAKE)... (cached) yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating tests/Makefile
config.status: creating bench/Makefile
config.status: creating m4ri/m4ri_config.h
config.status: creating m4ri.pc
config.status: creating m4ri/config.h
config.status: executing depfiles commands
config.status: executing libtool commands
>>> Source configured.
>>> Compiling source in /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115 ...
```

and then finally, after the build succeeds, the test output:

```sh
make  check-TESTS
make[3]: Entering directory '/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/tests'
make[4]: Entering directory '/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/tests'
FAIL: test_elimination
FAIL: test_multiplication
FAIL: test_solve
FAIL: test_trsm
FAIL: test_ple
FAIL: test_kernel
FAIL: test_colswap
FAIL: test_smallops
FAIL: test_random
FAIL: test_transpose
PASS: test_misc
FAIL: test_invert
FAIL: test_alignment
FAIL: test_djb
============================================================================
Testsuite summary for m4ri 20200115
============================================================================
# TOTAL: 14
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
============================================================================
```

and finally, the test-suite.log file:

```
=========================================
   m4ri 20200115: tests/test-suite.log
=========================================

# TOTAL: 14
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  13
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_elimination
======================

./test_elimination: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_elimination (exit status: 127)

FAIL: test_multiplication
=========================

./test_multiplication: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_multiplication (exit status: 127)

FAIL: test_trsm
===============

./test_trsm: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_trsm (exit status: 127)

FAIL: test_ple
==============

./test_ple: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_ple (exit status: 127)

FAIL: test_solve
================

./test_solve: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_solve (exit status: 127)

FAIL: test_kernel
=================

./test_kernel: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_kernel (exit status: 127)

FAIL: test_random
=================

./test_random: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_random (exit status: 127)

FAIL: test_smallops
===================

./test_smallops: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_smallops (exit status: 127)

FAIL: test_transpose
====================

./test_transpose: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_transpose (exit status: 127)

FAIL: test_colswap
==================

./test_colswap: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_colswap (exit status: 127)

FAIL: test_invert
=================

./test_invert: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_invert (exit status: 127)

FAIL: test_alignment
====================

./test_alignment: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_alignment (exit status: 127)

FAIL: test_djb
==============

./test_djb: symbol lookup error: /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so: undefined symbol: log2
FAIL test_djb (exit status: 127)
```

**Comment by kiwifb** [comment]
OK. I have seen stuff with `log2` recently. First thing first, is the final libm4ri completely resolved? In other words, does `ldd -r libm4ri.so` report any missing symbols?

**Comment by kiwifb** [comment]
This is quite atrocious. `USE=-png` means that libm is not linked to libm4ri. However I cannot reproduce your failures because `-lm` is still used when I compile the checks. Unless it even more hilariously picks up the wrong libm4ri...

**Comment by orlitzky** [comment]
```
# ldd -r ./.libs/libm4ri-0.0.20200115.so
	linux-vdso.so.1 (0x00007ffe613ef000)
	libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgomp.so.1 (0x00007f0a736c1000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f0a734ef000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f0a734e9000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f0a734c5000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f0a73750000)
undefined symbol: log2	(./.libs/libm4ri-0.0.20200115.so)
undefined symbol: round	(./.libs/libm4ri-0.0.20200115.so)
```

**Comment by kiwifb** [comment]
So when you do ebuild ... test, the compilation does not use `-lm` for the test executables?
```
libtool: link: x86_64-pc-linux-gnu-gcc -I./.. -I./.. -D_XOPEN_SOURCE=600 -fopenmp -march=native -O2 -pipe -Wl,-rpath -Wl,/dev/shm/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs -Wl,-O1 -Wl,--as-needed -o test_ple test_ple.o  -L/dev/shm/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs /dev/shm/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri.so -lm -fopenmp -Wl,-rpath -Wl,/dev/shm/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs
```
For example.

**Comment by orlitzky** [comment]
Linking of the test executable looks OK:

```
/bin/bash ../libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -I./.. -I./.. -D_XOPEN_SOURCE=600  -fopenmp  -O2 -pipe -march=native -L/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs -Wl,-rpath,/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs -lm4ri -lm   -no-install -Wl,-O1 -Wl,--as-needed -o test_elimination test_elimination.o
```

I think things went wrong when the library was linked:

```
/bin/bash ./libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc -mmmx -msse -msse2 -msse3 -fopenmp  -O2 -pipe -march=native -release 0.0.20200115 -no-undefined -Wl,-O1 -Wl,--as-needed -o libm4ri.la -rpath /usr/lib64 m4ri/brilliantrussian.lo m4ri/misc.lo m4ri/mzd.lo m4ri/graycode.lo m4ri/strassen.lo m4ri/mzp.lo m4ri/triangular.lo m4ri/triangular_russian.lo m4ri/ple.lo m4ri/ple_russian.lo m4ri/solve.lo m4ri/echelonform.lo m4ri/mmc.lo m4ri/debug_dump.lo m4ri/io.lo m4ri/djb.lo m4ri/mp.lo  
libtool: link: x86_64-pc-linux-gnu-gcc -shared  -fPIC -DPIC  m4ri/.libs/brilliantrussian.o m4ri/.libs/misc.o m4ri/.libs/mzd.o m4ri/.libs/graycode.o m4ri/.libs/strassen.o m4ri/.libs/mzp.o m4ri/.libs/triangular.o m4ri/.libs/triangular_russian.o m4ri/.libs/ple.o m4ri/.libs/ple_russian.o m4ri/.libs/solve.o m4ri/.libs/echelonform.o m4ri/.libs/mmc.o m4ri/.libs/debug_dump.o m4ri/.libs/io.o m4ri/.libs/djb.o m4ri/.libs/mp.o    -mmmx -msse -msse2 -msse3 -fopenmp -O2 -march=native -Wl,-O1 -Wl,--as-needed   -fopenmp -Wl,-soname -Wl,libm4ri-0.0.20200115.so -o .libs/libm4ri-0.0.20200115.so
```

**Comment by kiwifb** [comment]
Yes it looks like `-lm` is missing when you are not using `png`. And that's almost certainly a bug. However the final executable should not miss any symbols - or the compile line would fail. So I don't quite understand why it fails at execution for you and not for me. It is like there is something interfering with symbol resolution.

**Comment by orlitzky** [comment]
It's not immediately obvious to me what went wrong. Maybe in the morning...

**Comment by kiwifb** [comment]
OK. A summary.
* libm4ri is underlinked  against libm
* this is hidden when png is enabled because it brings libm in - incidentally.
* the tests are properly linked against libm. Which suggests that not linking libm4ri against libm may not be accidental. Underlinking libraries is legal and the author may think it is not needed.
* m4ri.pc does include `-lm` so the author knows that libm is needed and provides the right flags.
* the test executables should be properly linked. Underlinking executables is forbidden and the linking should fail in that case.

You successfully compile the test but running fails. This suggests something hides libm or interpose the wrong libm4ri. We need `ldd -r` and `readelf -d` from say `test_ple` in your case.

**Comment by orlitzky** [comment]
```
# ldd -r tests/test_ple
	linux-vdso.so.1 (0x00007ffcb213d000)
	libm4ri-0.0.20200115.so => /var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so (0x00007ff25d73a000)
	libc.so.6 => /lib64/libc.so.6 (0x00007ff25d548000)
	libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/9.2.0/libgomp.so.1 (0x00007ff25d510000)
	/lib64/ld-linux-x86-64.so.2 (0x00007ff25d776000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007ff25d50a000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff25d4e6000)
undefined symbol: log2	(/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so)
undefined symbol: round	(/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs/libm4ri-0.0.20200115.so)
```

```
# readelf -d tests/test_ple

Dynamic section at offset 0x2d10 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000003 (PLTGOT)             0x3f58
 0x0000000000000002 (PLTRELSZ)           432 (bytes)
 0x0000000000000017 (JMPREL)             0x820
 0x0000000000000014 (PLTREL)             RELA
 0x0000000000000007 (RELA)               0x760
 0x0000000000000008 (RELASZ)             192 (bytes)
 0x0000000000000009 (RELAENT)            24 (bytes)
 0x000000006ffffff9 (RELACOUNT)          3
 0x0000000000000015 (DEBUG)              0x0
 0x0000000000000006 (SYMTAB)             0x278
 0x000000000000000b (SYMENT)             24 (bytes)
 0x0000000000000005 (STRTAB)             0x4e8
 0x000000000000000a (STRSZ)              461 (bytes)
 0x000000006ffffef5 (GNU_HASH)           0x6b8
 0x0000000000000001 (NEEDED)             Shared library: [libm4ri-0.0.20200115.so]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000c (INIT)               0x9d0
 0x000000000000000d (FINI)               0x2290
 0x000000000000001a (FINI_ARRAY)         0x3d00
 0x000000000000001c (FINI_ARRAYSZ)       8 (bytes)
 0x0000000000000019 (INIT_ARRAY)         0x3d08
 0x000000000000001b (INIT_ARRAYSZ)       8 (bytes)
 0x000000000000001d (RUNPATH)            Library runpath: [/var/tmp/portage/sci-libs/m4ri-20200115/work/m4ri-20200115/.libs]
 0x000000000000001e (FLAGS)              BIND_NOW
 0x000000006ffffffb (FLAGS_1)            Flags: NOW
 0x000000006ffffff0 (VERSYM)             0x6e8
 0x000000006ffffffe (VERNEED)            0x71c
 0x000000006fffffff (VERNEEDNUM)         1
 0x0000000000000000 (NULL)               0x0
```

**Comment by kiwifb** [comment]
May be I should have started with that. You are using the gold linker, aren't you?

**Comment by orlitzky** [comment]
Yes! Sorry, I forgot to mention it. It's enabled by USE="default-gold" on sys-devel/binutils now.

**Comment by kiwifb** [comment]
OK, that kind of behavior is why I don't put it as default. This is just wrong. OK, there is a patch added to sage for some bug that have been acknowledge upstream I should add. And I can fix your issue in two ways. Patching Makefile.am - which requires eautoreconf to run - or passing `LIBS=-lm` to configure. Which one would you favor?

**Comment by orlitzky** [comment]
Probably in Makefile.am, because then it's easy to send upstream. I just dealt with a libm issue in symmetrica that amounted to

```m4
dnl Ensure that "libm" refers to the math library on this machine when
dnl we go to link against it.
LT_LIB_M
```

in configure.ac and then

```m4
libsymmetrica_la_LIBADD = $(LIBM)
```

in Makefile.am. The fix here is likely similar?

**Comment by kiwifb** [comment]
Using `LT_LIB_M` is a good idea and I can propagate it places. I was vastly more economical. But I can send a motivated report upstream now that we know gold is the cause.

**Comment by kiwifb** [comment]
Issue: I noticed on configuration and compilation that there much more than sse2 being enabled during a build. If sse2 is enabled and works (which means that we are on x86 hardware) the following are automagically enabled:
* mmx
* sse
* sse3
* ssse3
so branding the useflag sse2 is slightly misleading at the very least. Opinions, guidelines to follow I don't know?

**Comment by orlitzky** [comment]
In Gentoo, I guess I would pass `--enable-sse2` only if _all_ of the corresponding CPU USE flags are set.

Then upstream, I would open a bug and ask them to add separate flags for `--enable-sse3` etc. The automagic detection should be removed completely, in my opinion, because it breaks cross-compiling. But if the author is attached to it, then you could also do something like `--enable-sse3=yes/no/auto` where "auto" retains the current behavior.

**Comment by kiwifb** [comment]
I thought you would say something like that. That will be some extra patching. All the macros I can see from the autoconf archives focuses on detections. None of them offer enable/disable options. Just plain automagic with no disable button. The best available thing would be the macro used by givaro/fflas-ffpack/linbox, but it comes with a different license.

If it is essential we should disable the detection of the other simd instructions until a work around is found.

**Comment by kiwifb** [comment]
Check if the additional commits here fix your testing issue.

**Comment by orlitzky** [comment]
> Check if the additional commits here fix your testing issue.

Works now. Should I merge as-is? The SSE flag thing isn't new, right?

**Comment by kiwifb** [comment]
Indeed it is not. It is present in the previous version as well. I am OK for merging this. I have been waiting before bumping m4rie.

**Comment by orlitzky** [comment]
Can you add your Signed-off-by to that first commit (or maybe just squash them together?)

**Comment by kiwifb** [comment]
Added the signed-off bit. Had to rewrite history, hope it is OK.

**Comment by orlitzky** [comment]
Merged, thanks!

> Added the signed-off bit. Had to rewrite history, hope it is OK.

Yeah, no problem. I stick `.patch` on the end of the URL and feed the result to `git am` to merge these. Do whatever you want =)

**Pull request closed without merging**
