### PR TITLE
package.use.mask: mask USE=binary on dev-lang/scala, dev-java/sbt

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/733086
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by thesamesam** [comment]
I think this might prevent installing scala on a fresh install.

**Comment by pvgoran** [comment]
Why remove the possibility to use `USE=binary` if it can be *trivially* fixed instead??

**Comment by vaukai** [comment]
> Why remove the possibility to use `USE=binary` if it can be _trivially_ fixed instead??

Stabilization is blocked by https://bugs.gentoo.org/733086 and https://bugs.gentoo.org/731830. 
Would be great if you provided _trivial_ fixes for them

**Comment by pvgoran** [comment]
> > Why remove the possibility to use `USE=binary` if it can be _trivially_ fixed instead??
> 
> Stabilization is blocked by https://bugs.gentoo.org/733086 and https://bugs.gentoo.org/731830. Would be great if you provided _trivial_ fixes for them

Done. See https://github.com/gentoo/gentoo/pull/26037 and https://github.com/gentoo/gentoo/pull/26038.

**Comment by vaukai** [comment]
Closing in favor of https://github.com/gentoo/gentoo/pull/26037 and https://github.com/gentoo/gentoo/pull/26038.

**Comment by pvgoran** [comment]
@vaukai Done, I think.

**Comment by vaukai** [comment]
> @vaukai Done, I think.

But sign-off still missing in both your PRs :-(

**Comment by pvgoran** [comment]
> But sign-off still missing in both your PRs :-(

I'm not using to committing to Gentoo, so I don't know/remember the protocol. :)

Anyway, now the sign-off lines are in place.

**Pull request closed without merging**
