### PR TITLE
kde-base/contactthemeeditor: Remove obsolete kdepim package

### PR DESCRIPTION
**Pull request by a17r**
Leftover from before 4.14 that doesn't do anything except being blocked by kaddressbook which contains it since 4.14.

willikins: Reverse RDEPEND for kde-base/contactthemeeditor: [B]kde-apps/kaddressbook-4.14.10 [B]kde-apps/kaddressbook-4.14.8

### CODE REVIEW

**Comment by kensington** [comment]
Good spot. We will need to send last-rites, but of course you know that because it's a quiz question. ;-)

**Comment by monsieurp** [comment]
@gentoo/kde

**Comment by kensington** [comment]
I sent the last-rites and will merge when it's time.

**Comment by monsieurp** [comment]
@kensington ping

**Comment by kensington** [comment]
Thanks, picked as ce9e8e3af7e858a6ce2d317dbf6e691b4241b649 (with last-rite mask dropped in 25dab8527ad800ab29e715ec39e246389afc7388).

**Pull request closed without merging**
