### PR TITLE
media-fonts/fontawesome: Yank old versions on slot 5

### PR DESCRIPTION
**Pull request by lovesegfault**

### CODE REVIEW

**Comment by flappyports** [comment]
This would drop media-fonts/fontawesome-5.1.0 which is the only stable one.

**Comment by lovesegfault** [comment]
D'oh, that's annoying. Both 4.7.0 and 5.10.1 should be stable, I guess I'll make a PR to stabilize 4.7.0, and change this one to not drop 5.1.0.

A few weeks from now when 5.10.1 stabilizes I can yank 5.1.0.

**Comment by lovesegfault** [comment]
* What do you think @flappyports ?

**Comment by flappyports** [comment]
> What do you think @flappyports ?

Anything going stable requires a bug to be opened so the respective arch teams can do their stable work. Open a bug on b.g.o and CC arches.

**Comment by lovesegfault** [comment]
Rebased

**Pull request closed without merging**
