### PR TITLE
Don't explicitly list maksbotan in metadata as he's a member of proxy-maint project already

### PR DESCRIPTION
**Pull request by Coacher**
Acked by Maxim Koltsov <maksbotan@gentoo.org> via email.
I forwarded the email to <proxy-maint@gentoo.org>.

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Merged. Thanks.

**Comment by Coacher** [comment]
Thank you very much, @gktrk.

**Comment by gktrk** [comment]
Thank you for your contribution!

**Pull request closed without merging**
