### PR TITLE
fixing too loose dependency from media-libs/giflib. Bug #579246

### PR DESCRIPTION
**Pull request by ChaosEngine**
Not compiling with >media-libs/giflib-4.1*
Bug #579246

### CODE REVIEW

**Comment by rindeal** [comment]
Why not to also bump year and EAPI?

**Comment by ChaosEngine** [comment]
done. tested and building

**Comment by idella** [comment]
<name>Gentoo Graphics Project</name>
Now you need to find someone from this project to attend to this pull req.
Typo: media-libs/giflibs, but we have a media-libs/giflib.
The commit msgs need adhere to a style of syntax. These will all need re-doing. There are docs  of git itself and gentoo docs that outline style for commit msg.

**Comment by monsieurp** [comment]
Please format your commit messages. This PR cannot be merged as is.

**Comment by ChaosEngine** [comment]
@monsieurp now should be better.
@idella I took a pragmatic aproach and blocked version of giflib that give errors. The qgifer project is somehwat stale AFAIK

**Comment by monsieurp** [comment]
@radhermit @lu-zero

**Comment by idella** [comment]
@ChaosEngine  I suggest you CC these two devs in the bug in bugzilla. Alternatively I might commit it anyway but what should happen is they review - commit.

**Comment by ChaosEngine** [comment]
@idella added them as CC. Do you have any doubts 'bout this change? Is there anything I can do or test?

**Comment by idella** [comment]
Firstly, on getting into the cloned repo, 'repoman full' failed on the spot.
cmake-utils eclass has changed its form in EAPI 6, so I only got to run the ebuild switching back to EAPI 5.  The docs of P.M.S. will outline these changes, I have seen this recently with other new added packages.  The code entries for EAPI 5 simply do not work under EAPI 6. 
The new package was wlc i am pretty sure.

Downgrading can be awkward and using emerge to downgrade invoked more head aches with incompatibility of deps re the slotted values. Once I did get it to build, it still failed.

< <atom> is generally frowned upon because it can invite unexpected wrong versions, however in the case of <media-libs/giflib-4.2.3:0, there are only versions 4.1.6-r2,3 making for 'no - less' chance of confusion.  The preferred path here is to have it build with the current giflib anyway.

Also, after 23 days the master of gentoo has changed alot.  The metadata was in an old state and was wrong also. Can you try to generate a branch in the cloned gentoo for each pull req thx.

.

**Comment by monsieurp** [comment]
Please refrain from pulling from master, merging back into your local branch and pushing. It creates a mess we simply can't merge. Also, the repository state has changed a lot between the time this was filed and now (a revbump took place for instance). File another PR containing only the 1st commit. Thank you.

**Comment by ChaosEngine** [comment]
ok

**Pull request closed without merging**
