### PR TITLE
media-gfx/gimp: 2.99.14 version bump

### PR DESCRIPTION
**Pull request by band-a-prend**

### CODE REVIEW

**Comment by band-a-prend** [comment]
Failed due to
2.99.14 | DeprecatedDep | DEPEND: deprecated dependency: >=dev-libs/atk-2.38.0
-- | -- | --
  | DeprecatedDep | RDEPEND: deprecated dependency: >=dev-libs/atk-2.38.0

`x11-libs/gtk+-3.24.4` anyway depends on `dev-libs/atk`

**Comment by thesamesam** [comment]
New package versions shouldn't depend on it -- see package.deprecated:
```
# Matt Turner <mattst88@gentoo.org> (2022-10-02)
# Dummy packages, now merged into app-accessibility/at-spi2-core.
# When possible, replace dependencies on these packages with a dependency on
#       >=app-accessibility/at-spi2-core-2.46.0
app-accessibility/at-spi2-atk
dev-libs/atk
```

**Comment by band-a-prend** [comment]
@thesamesam 
I saw that but at the dead of night I decided I need to patch `meson.build`.
Actually `>=dev-libs/atk-2.46.0` just installs  `>=app-accessibility/at-spi2-core-2.46.0` :)
I replaced dependency with offered.

**Comment by band-a-prend** [comment]
Thanks!

**Comment by band-a-prend** [comment]
@thesamesam 
I didn't mention that new gegl now has USE openmp flag so the appropreate phases were added into it's ebuild:
```
pkg_pretend() {
	[[ ${MERGE_TYPE} != binary ]] && use openmp && tc-check-openmp
}

pkg_setup() {
	[[ ${MERGE_TYPE} != binary ]] && use openmp && tc-check-openmp
	python-any-r1_pkg_setup
}
```

**Pull request closed without merging**
