### PR TITLE
sys-boot/grub: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Signed-off-by: Michael Mair-Keimberger <mmk@levelnine.at>
Portage 3.0.37 / pkgdev 0.2.2 / pkgcheck 0.10.15

### CODE REVIEW

**Comment by floppym** [comment]
When I run `pkgcheck scan --commits`, I get the following warning:
```
% pkgcheck scan --commits
gentoo -- updating git cache: commit date: 2022-09-27
commit
  InvalidCommitMessage: commit 30b1e5625e8: non-tag in footer, line 4: 'Portage 3.0.37 / pkgdev 0.2.2 / pkgcheck 0.10.15'
```
Could you please update your script to not add this line?

**Review by floppym — CHANGES_REQUESTED** [review]
Please remove this line from the commit message:
```
Portage 3.0.37 / pkgdev 0.2.2 / pkgcheck 0.10.15
```

**Comment by mm1ke** [comment]
> Please remove this line from the commit message:
> 
> ```
> Portage 3.0.37 / pkgdev 0.2.2 / pkgcheck 0.10.15
> ```

Sure. I've removed that line now. Also going to change my script, so further PRs won't have it.

**Comment by floppym** [comment]
Thanks!

**Pull request closed without merging**
