### PR TITLE
media-tv/mythtv: bump snapshot 20210506, add Python 3.9 target

### PR DESCRIPTION
**Pull request by thebitpit**
Package-Manager: Portage-3.0.18, Repoman-3.0.2
Signed-off-by: Wilson Michaels <thebitpit@austincustomerrands.com>
Bug: 788730

### CODE REVIEW

**Review by mgorny — CHANGES_REQUESTED** [review]
It looks like snapshot bump, so the commit message is wrong. Also, you're missing the signoff.

**Comment by thebitpit** [comment]
Add my sign-off and bug reference to python 3.9 update.
Not sure what commit message should be so I tried something else.

**Comment by arthurzam** [comment]
> 
> 
> Add my sign-off and bug reference to python 3.9 update.
> Not sure what commit message should be so I tried something else.

Change the commit message **title** to something like:
`media-tv/mythtv: bump snapshot 20210506, add python 3.9`

And add you sign-off to the commit **description** itself, something like:
`Signed-off-by: Full Name <e-mail>`

**Comment by thebitpit** [comment]
> It looks like snapshot bump, so the commit message is wrong. Also, you're missing the signoff.
Fixed

**Comment by thebitpit** [comment]
> It looks like snapshot bump, so the commit message is wrong. Also, you're missing the signoff.

Fixed

**Comment by arthurzam** [comment]
> > It looks like snapshot bump, so the commit message is wrong. Also, you're missing the signoff.
> 
> Fixed

We mean the commit itself, not the Pull Request. Please follow those instructions:

1. Enter your repository directory at your local computer.
2. Check that you are at the correct branch
3. Use the command `git commit --amend` to edit the commit description.
4. In the editor windows that opened, fix the commit message to the one I wrote at the end of this reply (based on your text above):
5. Use the command `git push --force` to force-push and override your old commit.

```
media-tv/mythtv: bump snapshot 20210506, add Python 3.9 target

Package-Manager: Portage-3.0.18, Repoman-3.0.2
Signed-off-by: Wilson Michaels <thebitpit@austincustomerrands.com>
```

**Pull request closed without merging**
