### PR TITLE
sys-apps/bleachbit: Bump to 1.17 beta

### PR DESCRIPTION
**Pull request by tietzc**
Bleachbit 1.17 beta has been released in the meantime. Therefore, I updated this PR. Also switched SRC_URI from Sourceforge to Github.

Build log: https://bpaste.net/show/ad664fe4c557

### CODE REVIEW

**Comment by tietzc** [comment]
Pushed another commit in order to get rid of $Id$. Should finally be squashed of course.

CCing @monsieurp who has already pushed previous PRs regarding this package, as I see no real progress here. Hope that is fine.

**Comment by tietzc** [comment]
Rebased. Now we have only two commits.

**Comment by monsieurp** [comment]
LGTM! :+1:

**Comment by tietzc** [comment]
@monsieurp, thank you.

**Pull request closed without merging**
