### PR TITLE
app-emulation/wine: Bump to 1.9.21

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Hey there,
this is a bump upgrade for wine-1.9.21 I've been using it for some time,
and I've upgrade my overlay to 1.9.22.

I would like to help maintaining it so tell me if there is any feedback or fix to be made.

Below the short summary of the changelog of the 1.9.21:
```
What's new in this release (see below for details):
  - Initial version of the HID minidriver.
  - Support for lists in the RichEdit control.
  - System tray improvements.
  - Various bug fixes.
```

https://www.winehq.org/announce/1.9.21

Guillaume

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I've fixed the title of the PR.

**Comment by gktrk** [comment]
@gentoo/wine

**Comment by soredake** [comment]
ping

**Comment by GuillaumeSeren** [comment]
Hey,
can I add anything to help this PR, it is a simple bump I've tested it successfully for some time.

I am trying to follow each wine upgrade (and wine-staging) so I've moved from this release some time ago, so if you know what i can do to help this get merged faster, I'll could move to the next release faster.

**Comment by mgorny** [comment]
@GuillaumeSeren, I look forward to this version bump as well but it seems that our wine team is a bit MIA. I'll try to test it today and merge it afterwards.

Suggestions on how to get things merged faster:
- [ ] include (inline as a code block) diff between previous ebuild and the current one,
- [ ] mention whether you diffed `configure.ac` between previous and current versions ;-).

**Comment by GuillaumeSeren** [comment]
Hi @mgorny not really sure about the meaning of 'MIA' but I asked them on their irc chan and they reply that the maintainer is pretty much afk and it is not a real hurry, I am already on wine-2.0-rc1 on my overlay.

I opened a bug here: https://bugs.gentoo.org/show_bug.cgi?id=603968

And after rebasing, the diff is empty against the 1.9.20.

> mention whether you diffed configure.ac between previous and current versions
I did not, but I am curious how to do it ;)

**Comment by GuillaumeSeren** [comment]
@Amynka Yes ! 

It has been updated and closed on the BTS -> https://bugs.gentoo.org/show_bug.cgi?id=601324

**Comment by Amynka** [comment]
Thank you very much for your contribution ! :)

**Comment by GuillaumeSeren** [comment]
@Amynka Thank you for the feedback and Happy New Year !

**Pull request closed without merging**
