### PR TITLE
x11-base/xorg-server: Bump xorg-proto dep

### PR DESCRIPTION
**Pull request by mjsir911**
Doesn't build using any earlier version

### CODE REVIEW

**Comment by mattst88** [comment]
Presumably the problem is

```
Dependency presentproto found: NO found 1.3 but need: '>= 1.4'
Found CMake: /usr/bin/cmake (3.28.3)
Run-time dependency presentproto found: NO (tried pkgconfig and cmake)
Looking for a fallback subproject for the dependency presentproto

meson.build:84:19: ERROR: Neither a subproject directory nor a xorgproto.wrap file was found.
```

**Comment by mattst88** [comment]
Changed upstream by https://gitlab.freedesktop.org/xorg/xserver/-/commit/ac0bc0b3b6e678f6f0157e7ae3a77122783d2eed which landed yesterday.

**Comment by mattst88** [comment]
Thanks!

**Comment by mjsir911** [comment]
> Presumably the problem is
> 
> ```
> Dependency presentproto found: NO found 1.3 but need: '>= 1.4'
> Found CMake: /usr/bin/cmake (3.28.3)
> Run-time dependency presentproto found: NO (tried pkgconfig and cmake)
> Looking for a fallback subproject for the dependency presentproto
> 
> meson.build:84:19: ERROR: Neither a subproject directory nor a xorgproto.wrap file was found.
> ```

Oh yeah, this is it. Would this have been better placed in the original
commit or PR?

-- 
Marco Sirabella

**Comment by mattst88** [comment]
Yeah, in either case it helps the reviewer (i.e. me) to confirm that the PR is correct. I update the commit message with this info before pushing, see commit 4a3ed6c65660a0da9ebdb51e070ea0213abe5cba.

**Pull request closed without merging**
