### PR TITLE
media-sound/spotify : bump to 1.1.84

### PR DESCRIPTION
**Pull request by wamuu-sudo**
Bump to 1.1.84

### CODE REVIEW

**Comment by Kangie** [comment]
Hi @wamuu-sudo 

Can you please squash these changes into a single commit?

`git rebase -i HEAD~3`, squash the commits, `git push --force-with-lease`

You won't need to close the PR in order to do this - the squashed commit will replace these three. :)

**Comment by wamuu-sudo** [comment]
@Kangie 

Should be ok ?

**Comment by wamuu-sudo** [comment]
i think i've broke something ...

**Comment by Kangie** [comment]
That seems to have gone a little awry - We should only see one commit with all of your changes here.

As your changes weren't terribly complex, it might be easiest to start fresh and commit everything at once.

In future I'd recommend working off of a [git branch](https://www.atlassian.com/git/tutorials/using-branches) (at its simplest, from master, `git checkout -b new-branch-name`); it looks like you just rewrote a few commits more than intended!

FYI, you also need to sign off your commits - Try adding a `SIGNED_OFF_BY` line to your make.conf, e.g:

`SIGNED_OFF_BY="Matt Jolly <Matt.Jolly@footclan.ninja>"`

You can also use `pkgdev commit` (from `dev-util/pkgdev`) to automatically add this line to your commits if you aren't already.

**Comment by Kangie** [comment]
```
git checkout -b bump-spotify
git reset --hard HEAD~10
git clean -ndX
git status
git cherry-pick cca3865ac8f4b07abadd429263dd189c40701e66
git cherry-pick b1548dd83caa22c62eca9eef2071a6635cff130e
git rebase -i HEAD~2 
```
'Pick' the top commit, 'squash' the second commit.

**Pull request closed without merging**
