### PR TITLE
x11-misc/sddm: revbump. Fix pam activation, move qttest to DEPEND

### PR DESCRIPTION
**Pull request by Vindex17**
PAM is now enabled through a boolean variable

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks for your contribution. I have two notes, however:

1. The commit message is incorrect. It should start with `x11-misc/sddm:`, and afterwards state a meaningful summary of changes. In your case, the important change would be fixing use of USE=pam. `Update mycmakeargs` is too general.
2. You're mixing in `qttest` dep change with no mention of it.

**Comment by mgorny** [comment]
Oh, and both changes require a revision bump. Dep change because otherwise PM won't unmerge unnecessarily kept tests, cmake arg change because people who installed it so far will have the broken flag.

**Comment by mgorny** [comment]
@jauhien, @kensington, @mrueg, @yngwin

**Comment by kensington** [comment]
Thanks, applied.

**Pull request closed without merging**
