### PR TITLE
net-im/telegram-desktop: add 4.2.4

### PR DESCRIPTION
**Pull request by joecool1029**
Dropped tdesktop-4.0.2-fix-gcc12-cstdint.patch as I got it upstreamed. Otherwise no other changes, builds and runs fine here.

Signed-off-by: Joe Kappus <joe@wt.gd>

### CODE REVIEW

**Comment by mid-kid** [comment]
First test build has an issue:
```
CMake Error at cmake/external/kcoreaddons/CMakeLists.txt:28 (find_package):
  By not providing "FindKF5CoreAddons.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "KF5CoreAddons", but CMake did not find one.

  Could not find a package configuration file provided by "KF5CoreAddons"
  with any of the following names:

    KF5CoreAddonsConfig.cmake
    kf5coreaddons-config.cmake

  Add the installation prefix of "KF5CoreAddons" to CMAKE_PREFIX_PATH or set
  "KF5CoreAddons_DIR" to a directory containing one of the above files.  If
  "KF5CoreAddons" provides a separate development package or SDK, be sure it
  has been installed.
```
 * USE:        abi_x86_64 amd64 elibc_glibc enchant jemalloc kernel_linux prefix qt6 screencast spell userland_GNU wayland

Will look into this later.

**Comment by joecool1029** [comment]
> KF5CoreAddons

Need a qt6 dependency on kde-frameworks/kcoreaddons since https://github.com/telegramdesktop/tdesktop/commit/e20840b4d4c828d930b55a93995ded9eb2784c2d

Looks like that can be built against qt6 but gentoo's ebuild only builds against qt5.

Info on it: https://www.volkerkrause.eu/2021/12/11/kf6-building-against-qt6.html
They later added support officially back in February.

**Comment by mid-kid** [comment]
In that case it's time to file bugs and drop the flag.

**Comment by joecool1029** [comment]
It actually seems there may be another way, telegram needs the qt5 version that gentoo has but it also needs a qt6 version. Alpine added another package for it, upstream issue discussing the packaging issues: https://github.com/telegramdesktop/tdesktop/issues/25073

**Comment by mid-kid** [comment]
Yeah that sounds like a new SLOT for kf5. We should file a bug and discuss it with whatever maintainer.

**Comment by catdevnull** [comment]
Don't take Alpine's (my) solution for granted; this makes the two packages (kcoreaddons and kcoreaddons-qt6) conflict, and is probably wrong.

**Comment by mid-kid** [comment]
@catdevnull The idea of a SLOT in gentoo is to install the files either with different names or under a different path such that they don't conflict. From the telegram ebuild we can then hardcode the path to the version we pick.
But I'd rather speak with the kde team as they'll have a better idea on how to do this.

**Comment by mid-kid** [comment]
Apparently kcoreaddons is required regardless of qt6.

**Comment by mid-kid** [comment]
Another alternative would be to do something like `sed -e 's/NOT LINUX/TRUE/' -i cmake/external/kcoreaddons/CMakeLists.txt`. It seems only `KUrlMimeData::exportUrlsToPortal` and `KUrlMimeData::urlsFromMimeData` are used, which is a very minor functionality. This might be a good solution for qt6 builds until we get qt6 kcoreutils in ::gentoo.

**Comment by mid-kid** [comment]
Opened an issue for qt6 builds of kcoreaddons.
https://bugs.gentoo.org/871582

**Comment by joecool1029** [comment]
So to move forward on this for now, should I drop qt6 from the ebuild or leave as is? It's less than ideal to build on qt5 (since upstream doesn't support it), but Gentoo hasn't included qt6 and is already signalling they won't support this unless extra libraries get bundled.

**Comment by mid-kid** [comment]
Considering the status of the kcoreaddons bug, we have no choice but to bundle it when building for qt6, or hack around needing it like I mentioned above, although ideally the former. It's not ideal but I really don't think this is worth dropping the qt6 flag over, since we're going to need it sooner rather than later.

I'll do this soon, currently a bit busy.

**Comment by mid-kid** [comment]
Superseded by https://github.com/gentoo/gentoo/pull/27553
Made some qt6-related changes to provide a more full-featured package.

**Pull request closed without merging**
