### PR TITLE
app-emulation/xen: security bump for 4.10.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Latest security fixes.

### CODE REVIEW

**Comment by hydrapolic** [comment]
@dlan17

**Comment by Whissi** [comment]
Can you name the XSA you addressed? Of course I could go through the patch diff but maybe you have a list:
```
0082-x86-spec-ctrl-Yet-more-fixes-for-xpti-parsing.patch
0083-x86-vmx-Fix-handing-of-MSR_DEBUGCTL-on-VMExit.patch
0084-x86-vmx-Defer-vmx_vmcs_exit-as-long-as-possible-in-c.patch
0085-x86-vmx-API-improvements-for-MSR-load-save-infrastru.patch
0086-x86-vmx-Internal-cleanup-for-MSR-load-save-infrastru.patch
0087-x86-vmx-Factor-locate_msr_entry-out-of-vmx_find_msr-.patch
0088-x86-vmx-Support-remote-access-to-the-MSR-lists.patch
0089-x86-vmx-Improvements-to-LBR-MSR-handling.patch
0090-x86-vmx-Pass-an-MSR-value-into-vmx_msr_add.patch
0091-x86-vmx-Support-load-only-guest-MSR-list-entries.patch
0092-VMX-fix-vmx_-find-del-_msr-build.patch
0093-common-gnttab-Introduce-command-line-feature-control.patch
0094-ARM-disable-grant-table-v2.patch
0095-x86-vtx-Fix-the-checking-for-unknown-invalid-MSR_DEB.patch
0096-tools-oxenstored-Make-evaluation-order-explicit.patch
0097-x86-spec-ctrl-Calculate-safe-PTE-addresses-for-L1TF-.patch
0098-x86-spec-ctrl-Introduce-an-option-to-control-L1TF-mi.patch
0099-x86-shadow-Infrastructure-to-force-a-PV-guest-into-s.patch
0100-x86-mm-Plumbing-to-allow-any-PTE-update-to-fail-with.patch
0101-x86-pv-Force-a-guest-into-shadow-mode-when-it-writes.patch
0102-x86-spec-ctrl-CPUID-MSR-definitions-for-L1D_FLUSH.patch
0103-x86-msr-Virtualise-MSR_FLUSH_CMD-for-guests.patch
0104-x86-spec-ctrl-Introduce-an-option-to-control-L1D_FLU.patch
0105-x86-Make-spec-ctrl-no-a-global-disable-of-all-mitiga.patch
0106-xl.conf-Add-global-affinity-masks.patch
0107-x86-write-to-correct-variable-in-parse_pv_l1tf.patch
0108-libxl-start-pvqemu-when-9pfs-is-requested.patch
0109-tools-prepend-to-PKG_CONFIG_PATH-when-configuring-qe.patch
```

**Comment by hydrapolic** [comment]
@Whissi, the following vulnerabilities were addressed (compared with 4.10.1-r1): XSA-268, XSA-269, XSA-272, XSA-273

**Comment by hydrapolic** [comment]
However, when we compare 4.9.2 (latest stable) and this release, there is much more, that's why we should stabilize 4.10.1-r2 :)

**Pull request closed without merging**
