### PR TITLE
dev-libs/intel-common dev-lang/icc dev-lang/ifc: version bumps

### PR DESCRIPTION
**Pull request by mmokrejs**
https://github.com/gentoo/sci/issues/787

### CODE REVIEW

**Comment by amadio** [comment]
Are these commits picked from the science repo? There were changes to the intel-sdp.eclass, so it would be good if @SoapGentoo had a look first. It will be very nice to have these new versions in the main tree. Thanks for the nice work!

**Comment by mmokrejs** [comment]
No, I just copied the existing 2015-based ebuild from main repo and computed the checksums.

**Comment by amadio** [comment]
Did you install each package and checked that it worked?

**Comment by mmokrejs** [comment]
Sorry, no, not yet. Normally I wouldn't do it this way but in this particular case I am anyway not up to fixing any issues.

**Comment by mmokrejs** [comment]
OK, there is a problem. Somehow the version numbers get messed up from the ebuilds, but I do not know how the version numbers from ebuild filename are used to make up the filenames anticipated. Anyway, current error is:

```
>>> Emerging (1 of 3) dev-libs/intel-common-17.0.4.196::gentoo
 * parallel_studio_xe_2017_update4.tgz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                                                                                                                                             [ ok ]
 * /opt/intel/composerxe-2017_update4.4.196
>>> Unpacking source...
 * Unpacking intel-openmp-196-17.0-4.x86_64.rpm
/usr/bin/rpm2tar: line 156: parallel_studio_xe_2017_update4/rpm/intel-openmp-196-17.0-4.x86_64.rpm: No such file or directory
rpm2tar: warning: unable to locate cpio offset (broken/unknown compression?)
tar: This does not look like a tar archive
tar: Exiting with failure status due to previous errors
 * ERROR: dev-libs/intel-common-17.0.4.196::gentoo failed (unpack phase):
 *   unpacking parallel_studio_xe_2017_update4/rpm/intel-openmp-196-17.0-4.x86_64.rpm failed
 * 
 * Call stack:
 *               ebuild.sh, line  115:  Called src_unpack
 *             environment, line 2603:  Called intel-sdp_src_unpack
 *             environment, line 1819:  Called assert 'unpacking parallel_studio_xe_2017_update4/rpm/intel-openmp-196-17.0-4.x86_64.rpm failed'
 *   isolated-functions.sh, line   16:  Called die
 * The specific snippet of code:
 *      [[ $x -eq 0 ]] || die "$@"
 * 
 * If you need support, post the output of `emerge --info '=dev-libs/intel-common-17.0.4.196::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-libs/intel-common-17.0.4.196::gentoo'`.
 * The complete build log is located at '/scratch/var/tmp/portage/dev-libs/intel-common-17.0.4.196/temp/build.log'.
 * The ebuild environment file is located at '/scratch/var/tmp/portage/dev-libs/intel-common-17.0.4.196/temp/environment'.
 * Working directory: '/scratch/var/tmp/portage/dev-libs/intel-common-17.0.4.196/work'
 * S: '/scratch/var/tmp/portage/dev-libs/intel-common-17.0.4.196/work'
```

**Comment by jlec** [comment]
Please submit a PR to the science overlay. There is still an update of the eclass stuck in the overlay.

**Comment by tamiko** [comment]
icc versions 16 and newer need the intel-sdp-r1.eclass.

I suggest we simply version bump to latest icc version in the overlay and try to migrate to ::gentoo rather quickly.

As it is, this PR cannot be merged, I'm sorry.

**Pull request closed without merging**
