### PR TITLE
dev-lang/lazarus: add 3.4

### PR DESCRIPTION
**Pull request by dpronin**
Closes: https://bugs.gentoo.org/933988

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by dpronin** [comment]
@thesamesam would you merge it?

**Comment by dpronin** [comment]
@arthurzam would you take a look at the PR?

**Comment by thesamesam** [comment]
I've had the tab open for a few days and I've had a tonne to do. Please wait a bit of time between pings.

**Comment by thesamesam** [comment]
Merged with the libqt6pas change split into its own commit - thanks

**Comment by dpronin** [comment]
> I've had the tab open for a few days and I've had a tonne to do. Please wait a bit of time between pings.
> 
> The exception being if something is quite broken - and then say that in the pings.

I wouldn't ping you if you weren't the only one developer of gentoo that has power to merge into master

**Pull request closed without merging**
