### PR TITLE
net-p2p/i2p: version bump 0.9.25

### PR DESCRIPTION
**Pull request by tomboy-64**
- also enabled the ecdsa use-flag

@tharvik
@gentoo/java
@gentoo/proxy-maint

### CODE REVIEW

**Comment by tomboy-64** [comment]
I also implemented the ecdsa use-flag.

Still don't like it, since it relies on upstream checking whether our implementation of ecdsa is broken ...

**Comment by tharvik** [comment]
LGTM, thanks!

One small change if you don't mind, duplicate the patches (`${P}` instead of `${PN}-0.9.24`) so that's easier to update the ebuild and force us to check for it.

**Comment by monsieurp** [comment]
Indeed.

**Comment by tomboy-64** [comment]
@tharvik please runtest

**Comment by tomboy-64** [comment]
@tharvik ping

**Comment by tharvik** [comment]
emerged, run, everything seems just fine, I guess we can merge it.

**Comment by tomboy-64** [comment]
@idella @monsieurp please merge.
thanks @tharvik

**Pull request closed without merging**
