### PR TITLE
net-misc/networkmanager-l2tp: new package

### PR DESCRIPTION
**Pull request by kuraga**
NetworkManager-l2tp is a VPN plugin for NetworkManager 1.8 and later which
provides support for L2TP and L2TP/IPsec (i.e. L2TP over IPsec) connections.

Signed-off-by: Alexander Kurakin <kuraga333@mail.ru>

---

That's my first package. And I can't maintain it but I'd be very pleased if you have a look and merge, maybe. Thanks.

### CODE REVIEW

**Comment by mgorny** [comment]
No new packages without maintainer, sorry.

**Comment by kuraga** [comment]
Can we ask for a maintainer anywhere? I can do updating of this package, it's not a probleb Just my knowledge base of this application and Gentoo is not so serious....

**Comment by kuraga** [comment]
@mgorny , Can we ask for a maintainer anywhere? I can do updating of this package, it's not a probleb Just my knowledge base of this application and Gentoo is not so serious....

**Comment by mgorny** [comment]
Well, being maintainer is about taking care of updates and responding to bugs. You don't have to know it inside out; however, you need to be willing and ready to do some hard work whenever necessary.

Normally, the way to find a maintainer is to wait for somebody to take it from the bug.

**Pull request closed without merging**
