### PR TITLE
dev-python/pyroute2: add 0.7.4

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
waiting for an upstream tag so we do not need that sha in S and SRC_URI

https://github.com/svinota/pyroute2/issues/1067

**Review by juippis — APPROVED** [review]

**Comment by henning-schild** [comment]
@juippis what was going on with 3be2b10f54e5e0d53c1fd9a84d2761c33957ce17

did i get that checksum wrong or did it change

**Comment by juippis** [comment]
Hey, 

yes, most likely it was caused by https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/ but of course you could check if something weird happened upstream meanwhile. Wouldn't be the first time some upstream re-packages a release.

**Comment by henning-schild** [comment]
i see, thanks ... good to know about that one

**Pull request closed without merging**
