### PR TITLE
app-portage/g-cpan: required updates for last git version

### PR DESCRIPTION
**Pull request by bor**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@kentfredric

**Comment by kentfredric** [comment]
@bor, I'd just rebase out that last commit: There's no need to "optimise" virtuals.

All doing that does is kill the security upgrade path.

If you use a thing, depend on the virtual, unless there is good reason not to.

That way when we need to inspire an update to stop everything thats affected being insecure, we have things on the systems of people who are using the things to make that happen.

(This is extra important if upstream decide to remove something from core)

**Comment by bor** [comment]
@kentfredric is it your advice about ebuild/portage only? Or you think so for `Makefile.PL` and application also?

**Comment by kentfredric** [comment]
> your advice about ebuild/portage only? Or you think so for Makefile.PL and application also?

Yes, the only good case for *not* stating dependencies is when there is a known problem with doing so, but this typically only occurs in packages that are shipped with Perl Itself because "bootstrap", or any other case where you know there is harm to be had from stating a dependency.

This is mostly just future proofing, but there are multiple precedents of "People thought they could assume a dependency" which were followed by those dependencies moving to CPAN, which resulted in their packages becoming broken due to the lack of an explicit dependency ( CF: Module::Build )

If its *not* "dual life", ( that is, can't be installed from CPAN ) then that's probably a better situation to *consider* omitting the dependency, but there's nothing from stopping you declaring them ( Dist::Zilla and friends regularly create dependencies on strict.pm and warnings.pm which are not ever likely to be removed/dual-lifed )

Outside the only thing you kinda have to be careful with is "threads.pm", because "use threads" causes "die()" on non-threaded perls and dependencies on virtual/perl-threads depends on perl[ithreads]

**Comment by akhuettel** [comment]
Agree with kent... I've added the one of the commits manually.

**Comment by bor** [comment]
Personally I don't really like such approach.
I know only few examples of really "important" removes from perl core. They are M::B and CGI.pm.

But ok I've revert changes for `Makefile.PL` also, to keep deps synced between it and ebuild.

**Pull request closed without merging**
