### PR TITLE
media-libs/ffmpegsource: revbump to drop useless '0' SLOTS

### PR DESCRIPTION
**Pull request by Coacher**
Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by aballier** [comment]
ewww no, they're not useless

it happened in the past we needed to preserve abi-compat releases outside of slot 0 for binary packages
(both upstream provide lts releases these days)

**Comment by Coacher** [comment]
> it happened in the past we needed to preserve abi-compat releases outside of slot 0 for binary packages
> (both upstream provide lts releases these days)

Hmm, and how packages that didn't have ':0' deps survived this in the past?

**Comment by SoapGentoo** [comment]
Unless there exists other `SLOT`s than 0, `:=` is the right slot operator

**Comment by kensington** [comment]
Please see metadata.xml from ffmpeg:

```
  <slots>
    <slot name="0">For building against. This is the only slot that provides
     headers and command line tools. Binary compatibility slots come and go
     as required, so always pin dependencies to this slot when appropriate.</slot>
  </slots>
```

**Comment by Coacher** [comment]
@kensington, let's not go this way then.

**Comment by kensington** [comment]
> Hmm, and how packages that didn't have ':0' deps survived this in the past?

By chance, and the fact that these binary compatibility slots are temporary. When multiple slots are available and one is not specified, portage tends to pick the highest. A good example if virtual/jpeg. Most people tend to have slot 62 installed, even though very few packages directly depend on it. If nothing pinned to slot 0, we could easily see build failures.

**Comment by Coacher** [comment]
> By chance, and the fact that these binary compatibility slots are temporary.

I expected 'we've updated all ebuilds as needed prior to introducing this new SLOTs'.

**Comment by kensington** [comment]
> I expected 'we've updated all ebuilds as needed prior to introducing this new SLOTs'.

Surely you've been around in Gentoo long enough to know that "should" and "did" rarely match up. :-D

**Comment by aballier** [comment]
> I expected 'we've updated all ebuilds as needed prior to introducing this new SLOTs'.

This was the case IIRC.

As for why it didn't survive time, I'm pretty sure the reason is debates like this one and most ppl dont consider it important enough to raise voices :)
(and the fact that binary slots are annoying)

**Pull request closed without merging**
