### PR TITLE
dev-python/jaraco-classes: bump to 1.4

### PR DESCRIPTION
**Pull request by sbraz**
This new version adds documentation.

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
This compiles without hgtools and I couldn't find a reference to it in the sources. In which way is this a build time dependency?

**Comment by sbraz** [comment]
Looks like it was removed in jaraco/jaraco.classes@3c9474e55cd9d0a3fff52ae55d8c9ac8247fe269, I'll fix this.

**Comment by sbraz** [comment]
Re-pushed with the right dependencies

**Comment by gktrk** [comment]
Merged https://github.com/gentoo/gentoo/commit/a6bda1d212f9022e111979d5ebe41bd944629ef3. Thanks!

**Pull request closed without merging**
