### PR TITLE
sys-cluster/hpx: Bump to v1.8.1

### PR DESCRIPTION
**Pull request by shifty91**
Bump to hpx to v1.8.1. Thanks.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Would be nice to have a stable hpx in ::gentoo. Any reason why we shouldn't stabilize 1.8.0 and instead drop it?

**Comment by shifty91** [comment]
@Flowdalic No objections. How to stabilize it?

**Comment by Flowdalic** [comment]
> @Flowdalic No objections. How to stabilize it?

First, remove the commit from this PR that drops the to-be-stabilized ebuild :) Then fill a stabilization bug, you may also want to check https://devmanual.gentoo.org/keywording/#moving-from-arch-to-arch. Feel free to ask in #gentoo-proxy-maint or me directly if you have issues with the process.

**Comment by shifty91** [comment]
On Wed Aug 10 2022, Florian Schmaus wrote:
>> @Flowdalic No objections. How to stabilize it?
>
> First, remove the commit from this PR that drops the to-be-stabilized
> ebuild :)

Done.

> Then fill a stabilization bug, you may also want to check
> https://devmanual.gentoo.org/keywording/#moving-from-arch-to-arch. Feel
> free to ask in #gentoo-proxy-maint or me directly if you have issues
> with the process.

OK. Thanks.

**Pull request closed without merging**
