### PR TITLE
app-emacs/desktop+: new package

### PR DESCRIPTION
**Pull request by gavv**
Hi!

This PR adds ebuild for [`desktop+`](https://github.com/ffevotte/desktop-plus) emacs module and its dependencies.

See [Bug 590890](https://bugs.gentoo.org/show_bug.cgi?id=590890).

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Please detail a bit more each commit message: https://wiki.gentoo.org/wiki/Gentoo_Github#New_packages. Thanks.

**Comment by gavv** [comment]
@monsieurp, updated.

**Comment by monsieurp** [comment]
Thanks! @graaff or @ulm will take it from there.

**Comment by gavv** [comment]
Ping? @graaff, @ulm

BTW, the bug is assigned to `maintainer-wanted@gentoo.org` for some reason.

**Comment by gavv** [comment]
@ulm Ping. Actually no hurry, just ensuring that the bug was not lost from your backlog.

**Comment by monsieurp** [comment]
@gavv hi! please ping him on the bug report. some developers do not sign up for github notifications.

**Pull request closed without merging**
