### PR TITLE
sys-apps/lshw: update to v02.18b

### PR DESCRIPTION
**Pull request by rindeal**
- EAPI6
- proper linguas
- simplified thanks to usex()
- disable update notifications
- proper version

TODO:
- port musl patch

@vapier

### CODE REVIEW

**Comment by vapier** [comment]
one big file is hard to review ...

i rewrote the l10n change and made it simpler in commit 7b458ea982b270ec5a50b2923a4ff9c58ab6fbc0.

i'm not sure your usex changes are entirely correct (like the desktop entry).  i've pushed 83fea39722d9a5a51a8643dba2a946e74b0b2560 which should do the same thing afaict.

**Comment by rindeal** [comment]
> one big file is hard to review ...

I agree, thus I split it

> i rewrote the l10n change and made it simpler in commit 7b458ea.

nice

> i'm not sure your usex changes are entirely correct (like the desktop entry). i've pushed 83fea39 which should do the same thing afaict.

How does my usex changes differ from yours?

**Comment by vapier** [comment]
you changed make_desktop_entry to always run even when `USE=-gtk` which we don't want

**Comment by rindeal** [comment]
Oh, so you mean `use` changes, I fixed it in https://github.com/gentoo/gentoo/pull/1474/commits/f29da6f67358ef1ae8620e7db5e305e4e35565c2

**Pull request closed without merging**
