### PR TITLE
dev-libs/tre: enable py3.11, cleanups

### PR DESCRIPTION
**Pull request by joecool1029**
Cleaned up, enabled py3.11. I think it won't depend on python anymore with -python.

Signed-off-by: Joe Kappus <joe@wt.gd>

### CODE REVIEW

**Comment by thesamesam** [comment]
You seem to have both deleted the warning _and_ dropped the blockers re agrep? It should've just been keeping the blockers?

**Comment by joecool1029** [comment]
> You seem to have both deleted the warning _and_ dropped the blockers re agrep? It should've just been keeping the blockers?

It would have made sense to keep the blockers if the blockers were actually in ::gentoo, but they aren't anymore. If someone installs something else providing agrep from an overlay then collision detection will pick it up and they will file a bug or take the agrep useflag off this package.

**Comment by thesamesam** [comment]
dev-ruby/amatch is still in Gentoo, glimpse was removed only recently, and I _think_ agrep was removed only recently too. We keep blockers for 2 years at least or they disrupt upgrades (cause an abort).

**Comment by joecool1029** [comment]
> dev-ruby/amatch is still in Gentoo, glimpse was removed only recently, and I _think_ agrep was removed only recently too. We keep blockers for 2 years at least or they disrupt upgrades (cause an abort).

I stand corrected, I'll update the URL for dev-ruby/amatch. 

> pkgcheck warns when a blocker is due to be dropped.

It gave me deprecated warnings so I dropped them out before. Readded now.

**Comment by thesamesam** [comment]
> > dev-ruby/amatch is still in Gentoo, glimpse was removed only recently, and I _think_ agrep was removed only recently too. We keep blockers for 2 years at least or they disrupt upgrades (cause an abort).
> 
> I stand corrected, I'll update the URL for dev-ruby/amatch.
> 
> > pkgcheck warns when a blocker is due to be dropped.
> 
> It gave me deprecated warnings so I dropped them out before. Readded now.

Ah, this might be because of the age of your clone. It's not smart enough if it's a fresh clone sometimes.

Thanks!

**Pull request closed without merging**
