### PR TITLE
games-puzzle/nudoku: fix compilation and update eapi

### PR DESCRIPTION
**Pull request by rndxelement**
I am suggesting a fix for [764497](https://bugs.gentoo.org/764497). 

Configure was broken because it couldn't find pkg-configure (dev-util/pkgconf). 
It suggested specifying the path to it via a variable, which I added to the existing patch.
I tested it on three different devices

Also, I added support for EAPI 8.

### CODE REVIEW

**Comment by thesamesam** [comment]
It seems _really_ odd to need to do that, and we also shouldn't hardcode the pkgconf implementation (in theory others are permissible or might be in future), we want the `pkg-config` binary.

**Comment by thesamesam** [comment]
Is it maybe a missing `PKG_PROG_PKG_CONFIG` call before `PKG_CHECK_MODULES`?

**Comment by rndxelement** [comment]
> Is it maybe a missing `PKG_PROG_PKG_CONFIG` call before `PKG_CHECK_MODULES`?

That was actually it. Thanks :)

**Comment by Flowdalic** [comment]
> That was actually it. Thanks :)
The patch appears to be worthy for upstream submission (if you not already did so).

**Comment by rndxelement** [comment]
The patch now respects the check for the ncursesw library via pkg-check.

Thanks, @Flowdalic, for the suggestion. I created a [PR](https://github.com/jubalh/nudoku/pull/46) to upstream.

**Pull request closed without merging**
