### PR TITLE
sys-apps/help2man: make Locale-gettext unconditional

### PR DESCRIPTION
**Pull request by scardracs**
Every time You try to set a clean lxd container it does not pull Locale-gettext and everytime help2man fails because it requires Locale-gettext, even if nls is not set. On a "normal" installation Locale-gettext is pulled up by other packages (eg: man-pages-l10n calls po4a calls Locale-gettext) so the error does not appears.

Signed-off-by: Marco Scardovi <scardracs-gentoo@proton.me>

### CODE REVIEW

**Comment by floppym** [comment]
I think we should either fix USE="-nls" to work without Locale-gettext, or drop the nls USE flag entirely.

**Comment by floppym** [comment]
I just did a quick test:

1. I reinstalled sys-apps/help2man with USE="-nls".
2. I unmerged dev-perl/Locale-gettext.
3. I ran `help2man /usr/sbin/grub-install` to generate a man page.

This worked just fine.

Please file a bug with details on packages that fail with sys-apps/help2man[-nls].

**Comment by scardracs** [comment]
> I just did a quick test:
> 
> 1. I reinstalled sys-apps/help2man with USE="-nls".
> 2. I unmerged dev-perl/Locale-gettext.
> 3. I ran `help2man /usr/sbin/grub-install` to generate a man page.
> 
> This worked just fine.
> 
> Please file a bug with details on packages that fail with sys-apps/help2man[-nls].

Fails is during emerge of help2man itself. TBH I’ve not looked where Locale-gettext is called so maybe is a simple thing patching USE=“-nls”

**Comment by scardracs** [comment]
Ok, I've do a new clean container to test it. Basically nls is set by default but help2man does not pull Locale-gettext.

You can easily test following the @juippis guide here: https://wiki.gentoo.org/wiki/User:Juippis/The_ultimate_testing_system_with_lxd. The error appears to me every time. Also be sure to use the auto script here: https://wiki.gentoo.org/wiki/User:Juippis/The_ultimate_testing_system_with_lxd#Automatic_configuration_via_a_script here.

**Comment by scardracs** [comment]
I'm gonna close that for now for further investigations. I'm not sure it depends by help2man anymore

**Comment by floppym** [comment]
Sorry, but I'm not going to set up a container to try and trigger an error without more detail. Please file a bug with a build log the next time it happens.

**Pull request closed without merging**
