### PR TITLE
sys-fs/bcachefs-tools: cleanup and re-enable musl support

### PR DESCRIPTION
**Pull request by csfore**
Cleans up old versions of sys-fs/bcachefs-tools and re-enables musl profiles for >=1.11.0

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Please keep 1.7.0, see https://bugs.gentoo.org/938568#c4

**Comment by csfore** [comment]
Fixed!

**Comment by Kangie** [comment]
@csfore: something went wrong with this PR. You're adding files (for 1.7.0) to the manifest in a commit that says we're only removing obsolete ebuilds.

https://github.com/gentoo/gentoo/pull/38315/commits/8e4a77d6f3c30aaa86c248aee5a3f5dc8abd5704

Looks good otherwise, if you can fix the 1.7.0 stuff we can get this merged :)

**Comment by csfore** [comment]
@Kangie Should be fixed! I think that was caused by `pkgdev` automatically regenerating the Manifest on the first commit when it was intended for the second.

**Pull request closed without merging**
