### PR TITLE
dev-python/elasticsearch-curator: bump to 4.0.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Tests run ok on a normal system (elasticsearch fails to start in chroot).

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
LGTM. :+1:

**Comment by hydrapolic** [comment]
Thank you @monsieurp

**Pull request closed without merging**
