### PR TITLE
dev-util/visualvm: visualize what to keep bundled

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
i merged the first commit but i'm not sure about the second one. the way it is done now it fails when the file is renamed. the new way i think we can end up with the bundled jar and our jar side by side if the version changes.

**Comment by vaukai** [comment]
> i merged the first commit but i'm not sure about the second one. the way it is done now it fails when the file is renamed. the new way i think we can end up with the bundled jar and our jar side by side if the version changes.

Did you mean if the the `bundled jar version` changes?  The `java-pkg_clean` command removes any jar file which is not explicitely ecluded.

**Comment by fordfrog** [comment]
what i mean is that
```
rm hamcrest-core-1.3.jar && java-pkg_jar-from hamcrest-core-1.3 hamcrest-core.jar hamcrest-core-1.3.jar || die
```
fails when the version changes as the file to remove does not exist, but
```
java-pkg_jar-from hamcrest-core-1.3 hamcrest-core.jar hamcrest-core-1.3.jar || die
```
just creates a new jar along the old bundled one. if i'm not wrong.

**Comment by vaukai** [comment]
Got it. Closing.

**Pull request closed without merging**
