### PR TITLE
media-libs/imlib2: bump version 1.7.4

### PR DESCRIPTION
**Pull request by N-R-K**
Signed-off-by: Nickolas Raymond Kaczynski

### CODE REVIEW

**Comment by N-R-K** [comment]
any specific reason for the hold off or just the maintainer being away/inactive?

**Comment by bircoph** [comment]
Hi!

> any specific reason for the hold off or just the maintainer being away/inactive?

I usually review patches through bugzilla.

**Comment by N-R-K** [comment]
> Hi!
> 
> > any specific reason for the hold off or just the maintainer being away/inactive?
> 
> I usually review patches through bugzilla.

Not familiar with the bugzilla workflow. Should I re-open it there or something? @bircoph

**Comment by thesamesam** [comment]
> > Hi!
> > > any specific reason for the hold off or just the maintainer being away/inactive?
> > 
> > 
> > I usually review patches through bugzilla.
> 
> Not familiar with the bugzilla workflow. Should I re-open it there or something? @bircoph

I guess they want you to file a bug with a git am-able patch (use git format-patch) or just save the .patch you get from adding .patch to the URL of this PR.

**Comment by N-R-K** [comment]
> I guess they want you to file a bug with a git am-able patch (use git format-patch) or just save the .patch you get from adding .patch to the URL of this PR.

Done. https://bugs.gentoo.org/828503
Closing this.

**Pull request closed without merging**
