### PR TITLE
media-gfx/feh: drop 3.10.2

### PR DESCRIPTION
**Pull request by henning-schild**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by orbea** [comment]
Is there any reason to drop the old stable now? There are only two versions and it may help workaround regressions in the new version which I believe was only recently made stable?

**Comment by henning-schild** [comment]
I thought having a new stable would be the reason to drop the old now. The changelog and and the version bump on only the third digit suggest that regressions are unlikely. And i would assume that a new bug would more likely cause a "-r" ebuild or a new upstream release than a downgrade.

No specific reason from my side. I just saw that stable bump and that we are left with two stable versions, which looks like time to drop the old.

**Comment by orbea** [comment]
Look at programs like dev-lang/rust or dev-lang/python, there many more than 2 stable releases. In packages I maintain fully I usually drop the previous old stable unless there is a specific reason to keep it, but ultimately this is up to the Gentoo developers.

For reference these are the differences between 3.10.2 and 3.10.3.

https://github.com/derf/feh/compare/3.10.2...3.10.3

**Comment by dlan17** [comment]
there is no hard policy here to drop old stable version immediately, but let's do it less aggressively, since there aren't too many versions in tree.. besides, we can revisit once there is new version bump, thanks

**Comment by henning-schild** [comment]
feel free to close or keep open until anyone feels like merging

**Comment by Flowdalic** [comment]
Closing then to reduce the noise in open PRs.

**Pull request closed without merging**
