### PR TITLE
app-admin/op-cli-bin: 2.23.0

### PR DESCRIPTION
**Pull request by jaredallard**
Adds `2.23.0`, which is the first 2.x version supported. Updated to EAPI
`8`.

Keeping unstable for a bit, but I've been using this in my own overlay
for awhile now with no issues.

### CODE REVIEW

**Comment by jaredallard** [comment]
Replaces https://github.com/gentoo/gentoo/pull/33958. I'll probably end up creating a bug for this since it seems like this package is largely unmaintained. I'd be happy to maintain it (in an unofficial capacity [FD: I will be working at 1Password here soon]), but unsure what that process would be since I haven't contributed that much.

**Comment by jaredallard** [comment]
Ooook, I'm not sure how to fix the unsortted keyword issue :|

**Comment by FuzzyGophers** [comment]
> Ooook, I'm not sure how to fix the unsortted keyword issue :|

in KEYWORDS="" and SRC_URI="" you should sort the arches. e.g. "amd64 arm64 x86"...

**Comment by jaredallard** [comment]
> > Ooook, I'm not sure how to fix the unsortted keyword issue :|
> 
> in KEYWORDS="" and SRC_URI="" you should sort the arches. e.g. "amd64 arm64 x86"...

That makes sense, I don't know why I was struggling with getting that to pass yesterday 😄

**Pull request closed without merging**
