### PR TITLE
dev-lang/crystal: bump to 0.11.1

### PR DESCRIPTION
**Pull request by longlene**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
Hmmm nice timing. longlene this should never have been added under your authorship because you lack a registered email address in bugzilla of gentoo.prg. It was overlooked at the time the initial pull request of dev-lang/crystal was submitted.

**Comment by longlene** [comment]
@idella I've registered at https://bugs.gentoo.org/ now. I'm always waiting for the stable crystal which can compile with llvm-3.7 and haven't commit the newer version. Sorry for that.

**Comment by mgorny** [comment]
@longlene, @idella: when you commit the mentionedn ew version, please remember to update https://wiki.gentoo.org/wiki/LLVM_compatibility.

**Comment by longlene** [comment]
@mgorny Thanks for your advise. I'll update it if crystal can compile with llvm-3.7.

**Comment by idella** [comment]
atm the ebuild stipulates <sys-devel/llvm-3.7.0
No need for any change

**Pull request merged**
