### PR TITLE
games-fps/eduke32: version 20220702.10113

### PR DESCRIPTION
**Pull request by ccharon**
just felt like playing duke3d so i wanted to use the newest eduke version

### CODE REVIEW

**Comment by ConiKost** [comment]
Please add sign-off, as otherwise, I am not able to merge.

**Comment by ccharon** [comment]
I fixed it

**Comment by ConiKost** [comment]
Your SOB needs to be added as a new line.

**Comment by ccharon** [comment]
I tried the following ... checking out my fork of the gentoo repo.

using "git commit --amend" entering a new comment with the signoff in an extra line.
then "git push --force" to push the changes.

when I look at the pr the commit commit looks to me the same with the signoff in an extra line.


I hope you stay patient, I'll improve :)

**Comment by ConiKost** [comment]
No problem. Looks now better. I checked the ebuild and it looks fine for me. Jast a small nit pick: Please put your email address of your SOB entry into `<>`.

**Comment by ccharon** [comment]
ok, done.

**Review by ConiKost — APPROVED** [review]

**Pull request closed without merging**
