### PR TITLE
net-p2p/syncthing: Add ufw use flag to install net-firewall/ufw app p…

### PR DESCRIPTION
**Pull request by rywng**
…rofile

The ufw app profile file is downloaded from:

https://raw.githubusercontent.com/syncthing/syncthing/main/etc/firewall-ufw/syncthing

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by rywng** [comment]
Bug filed at https://bugs.gentoo.org/933985, since no proxy maintainer is present.

**Comment by mm1ke** [comment]
Usually such small files shouldn't be behind a useflag. They should be installed unconditionally (like systemd files on openrc systems). 

However, i think the best way would be to install this file as an additional (doc) file and let the user know that there is an example config for ufw firewalls.

Besides that, since i have no idea how `ufw` works: If you install this file into `/etc/ufw/applications.d` would `ufw` automatically open ports for syncthing? (like after restarting ufw)? Because in that case it's certainly a bad idea to install it 
automatically there. Just because someone installs `syncthing` it doesn't mean automatically they also want to have the firewall open for it.

**Comment by rywng** [comment]
Hello,

> Usually such small files shouldn't be behind a useflag. They should be installed unconditionally (like systemd files on openrc systems).

That makes sense, I added a use flag because I referred to `net-misc/mosh`'s ebuild when writing the patch, which has `ufw` as an use flag.


> Besides that, since i have no idea how `ufw` works: If you install this file into `/etc/ufw/applications.d` would `ufw` automatically open ports for syncthing? (like after restarting ufw)? Because in that case it's certainly a bad idea to install it automatically there. Just because someone installs `syncthing` it doesn't mean automatically they also want to have the firewall open for it.

I will answer this first: That's not the case.

If you put this file into `/etc/ufw/applications.d`, ufw will **not** automatically use the configuration (open the port). You will have to manually enable the "profile" by running `ufw allow syncthing` as root.

> However, i think the best way would be to install this file as an additional (doc) file and let the user know that there is an example config for ufw firewalls.

So, given my answer before, the best solution would be to install the file **unconditionally** into `/etc/ufw/applications.d`, which is also the case for other distros (for example [Arch Linux](https://archlinux.org/packages/extra/x86_64/syncthing/)), and then notify the users about the presence of ufw application file and how to enable it.

If that's how it should be done, I will update the PR in accordance to the aforementioned specification (Maybe also an update for `net-misc/mosh`) two or three weeks later, since I'm prepping for my final exam.

Ryan

**Comment by mm1ke** [comment]
> 
> I will answer this first: That's not the case.
> 
> If you put this file into `/etc/ufw/applications.d`, ufw will **not** automatically use the configuration (open the port). You will have to manually enable the "profile" by running `ufw allow syncthing` as root.

Thanks for explaining. :+1: 

> 
> So, given my answer above, the best solution would be to install the file **unconditionally** into `/etc/ufw/applications.d`, which is also the case for other distros (for example [Arch Linux](https://archlinux.org/packages/extra/x86_64/syncthing/)), and then notify the users about the presence of ufw application file and how to enable it.
> 
> If that's how it should be done, I will update the PR in accordance to the aforementioned specification (Maybe also an update for `net-misc/mosh`) two or three weeks later, since I'm prepping for my school exam.
> 
> Ryan

That sounds good to me!
Please note that i'm not a developer. Some dev still gonna look at this and might have a different opinion.

**Comment by rywng** [comment]
This was closed by https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=35b15dad1e5d3397aae68a56a06a01c9edfd747f

**Pull request closed without merging**
