### PR TITLE
Lilypond updates

### PR DESCRIPTION
**Pull request by lilrc**
Just keeping everything fresh. The main commit is the one that fixes bug 525712 (the one fixing metapost deps). The other commits I hope are obvious...

Gentoo-Bug: https://bugs.gentoo.org/525712

### CODE REVIEW

**Comment by lilrc** [comment]
@gentoo/proxy-maint
@idella

**Comment by monsieurp** [comment]
@lilrc Hi and thanks for the PR. Could you please rebase this PR and squash those 7 commits into a single one? You can provide as much details as you wish in the body of the commit message if you wish. Cheers.

**Comment by lilrc** [comment]
Okay. That should be it!

**Comment by lilrc** [comment]
Thank you!

**Pull request closed without merging**
