### PR TITLE
games-emulation/ppsspp:new ebuild

### PR DESCRIPTION
**Pull request by RobinDX**

### CODE REVIEW

**Comment by monsieurp** [comment]
Robin... using git for the -9999 ebuild is fine and you should leave it as such. But for the other two ebuilds? Why not fetching the repository content from github directly? Namely, https://github.com/hrydgard/ppsspp/archive/v1.1.1.zip and https://github.com/hrydgard/ppsspp/archive/v1.1.0.zip. We much prefer dealing with an archive than checking out "live" from a repo. Thanks for rewriting these 2 ebuilds and changing this behaviour.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by RobinDX** [comment]
@monsieurp
Because ppsspp use a lot of  submodules on github,use GIT-R3.ECLASS can easily fetch them.
Use directly link cannot use GIT-R3.ECLASS anymore.
And set a EGIT_COMMIT value can set the version of main source code.
The submodules have no version and often cahnge.
So if use zip download links,it impossible to get the submodules zip files sha256 sum in Manifest.

**Comment by RobinDX** [comment]
So I choose the easy way.

**Comment by RobinDX** [comment]
https://devmanual.gentoo.org/eclass-reference/git-r3.eclass/index.html
GIT-R3.ECLASS is very nice.

**Comment by monsieurp** [comment]
OK. Fair enough. I didn't know about the way the PPSSPP project manages modules. Let's merge the PR then. There are some minor mistakes (missing dies) that I will fix after merging.

**Comment by monsieurp** [comment]
Merged. Thank you. You're in charge of that package from now on. Enjoy!

**Comment by monsieurp** [comment]
@RobinDX
There's a small bug wrt this package. Please see https://bugs.gentoo.org/show_bug.cgi?id=572606 and check your emails (this bug has also been forwarded to your email address). Thanks!

**Comment by RobinDX** [comment]
@monsieurp
https://github.com/gentoo/gentoo/pull/738

**Pull request merged**
