### PR TITLE
dev-util/idea-community: added wayland USE flag

### PR DESCRIPTION
**Pull request by wqvi**
JetBrains added a wayland support preview in 2024.2 EAP. The wayland USE flag toggles the support preview on/off accordingly.

Edit:
I have come to the realization perhaps this should be a separate ebuild under the ~amd64 keyword, and only that ebuild should have the wayland use flag. Let me know what you think.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by mpagano** [comment]
We need an update to the metadata.xml file:
<use>
  <flag name="experimental">Apply experimental patches; for more information, see "https://wiki.gentoo.org/wiki/Project:Kernel/Experimental".</flag>
</use>

Let's do a -r1 of the ebuild.

Split the make_desktop_entry so we don't get an "excessive line length" error:
        make_desktop_entry "/opt/idea-community/bin/idea -Dawt.toolkit.name=WLToolkit" \
            "IntelliJ Idea Community Edition" "${PN}" "Development;IDE;"

Please install pkgcheck and run "pkgcheck scan"

**Comment by wqvi** [comment]
> We need an update to the metadata.xml file: Apply experimental patches; for more information, see "https://wiki.gentoo.org/wiki/Project:Kernel/Experimental".

Okay! I added the experimental USE flag to metadata.xml with the description: "Enables Wayland support preview". When running xmllint on metadata.xml I receive an error. Failed to load external entity, and no valid DTD found. Is that something I should be concerned about before I commit the file and do you think I should add anything else to metadata.xml? I was thinking about adding a bug-to section.

> Let's do a -r1 of the ebuild.

Would copying the current ebuild be acceptable? Or would rewriting it be necessary? I will add the necessary USE flag information where appropriate. Does the SLOT variable need to be set for the -r1 of the ebuild?

> Split the make_desktop_entry so we don't get an "excessive line length" error: make_desktop_entry "/opt/idea-community/bin/idea -Dawt.toolkit.name=WLToolkit" "IntelliJ Idea Community Edition" "${PN}" "Development;IDE;"
> Please install pkgcheck and run "pkgcheck scan"

Duly noted.

I should have the commit added within the next couple days

**Comment by mpagano** [comment]
Yeah, copy the build, and do the necessary changes (make it -r1) and I can commit it easily. Thanks for your work

**Comment by wqvi** [comment]
Hello! I believe I completed what was necessary. Apologies for the messy git history, I hope it's not too hard to clean up!

I do have a question, when running `pkgcheck scan --net --commits` I run into a python stack trace. However I can still see the necessary output for dev-util/idea-community.

Let me know if anything else needs to be done!

**Pull request closed without merging**
