### PR TITLE
net-dns/knot-resolver: add 5.7.4 && SRC_URI

### PR DESCRIPTION
**Pull request by PPN-SD**
add 5.7.4 : 
useflag systemd reworked. Using it for libsystemd (optional) instead of systemd_files (requires)
useflag xdp added

5.7.2 : 
fix redirects in SRC_URI

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by Flowdalic — CHANGES_REQUESTED** [review]
Thanks for your contribution.

Changes to files under `FILESDIR` require a revision bump of the changed files, as otherwise existing versions of a package referencing those files would suddenly install different files after the change.

**Comment by PPN-SD** [comment]
> Thanks for your contribution.
> 
> Changes to files under `FILESDIR` require a revision bump of the changed files, as otherwise existing versions of a package referencing those files would suddenly install different files after the change.

I think it's ok.

**Comment by Flowdalic** [comment]
> @Flowdalic I think it's ok. Keep stable keyword is ok ?

I am not sure, as I don't know much about the backstory and motivation to change `/var/run` into `/run`. Personally, I potentially would play it safe and only introduce this change in the new ebuild, instead of modifying existing ones.

You asking me if keeping the stable keywords is ok probably signs that we should play it safe and only introduce this change in the new ebuild.

**Comment by PPN-SD** [comment]
> > @Flowdalic I think it's ok. Keep stable keyword is ok ?
> 
> I am not sure, as I don't know much about the backstory and motivation to change `/var/run` into `/run`. Personally, I potentially would play it safe and only introduce this change in the new ebuild, instead of modifying existing ones.
> 
> You asking me if keeping the stable keywords is ok probably signs that we should play it safe and only introduce this change in the new ebuild.

Initial change was to comment on capabilities to close bug 939471. I'll remove /var/run > /run, even if I think it's trivial and don't require revbump.

**Comment by PPN-SD** [comment]
> Initial change was to comment on capabilities to close bug 939471. I'll remove /var/run > /run, even if I think it's trivial and don't require revbump.

libcap will be no longer optional in openrc soon, so I'll remove any change in FILESDIR. End of problem.

**Comment by PPN-SD** [comment]
Thank you @Flowdalic 👍

**Pull request closed without merging**
