### PR TITLE
x11-misc/albert: version bump to 0.22.12

### PR DESCRIPTION
**Pull request by CaseOf**

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. Please also ensure that the packages you are maintaining get stabilized.

**Review by juippis — APPROVED** [review]
I couldn't launch it, could be some container-qt thing or a missing dep (error log isn't helpful).

Sorry for the delay!

**Comment by CaseOf** [comment]
@juippis here is a lddtree on the binary:
```
albert => /usr/bin/albert (interpreter => /lib64/ld-linux-x86-64.so.2)
    libalbert.so.0.22 => /usr/lib64/libalbert.so.0.22
        libQt6Widgets.so.6 => /usr/lib64/libQt6Widgets.so.6
        libQt6Concurrent.so.6 => /usr/lib64/libQt6Concurrent.so.6
        libQt6Network.so.6 => /usr/lib64/libQt6Network.so.6
            libzstd.so.1 => /lib64/libzstd.so.1
            libz.so.1 => /lib64/libz.so.1
        libQt6Sql.so.6 => /usr/lib64/libQt6Sql.so.6
        libqhotkey.so.1 => /usr/lib64/libqhotkey.so.1
            libX11.so.6 => /usr/lib64/libX11.so.6
                libxcb.so.1 => /usr/lib64/libxcb.so.1
                    libXau.so.6 => /usr/lib64/libXau.so.6
                    libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6
        libQt6Gui.so.6 => /usr/lib64/libQt6Gui.so.6
            libEGL.so.1 => /usr/lib64/libEGL.so.1
                libGLdispatch.so.0 => /usr/lib64/libGLdispatch.so.0
            libfontconfig.so.1 => /usr/lib64/libfontconfig.so.1
                libexpat.so.1 => /usr/lib64/libexpat.so.1
            libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0
                libpcre2-8.so.0 => /lib64/libpcre2-8.so.0
            libQt6DBus.so.6 => /usr/lib64/libQt6DBus.so.6
                libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3
            libxkbcommon.so.0 => /usr/lib64/libxkbcommon.so.0
            libGLX.so.0 => /usr/lib64/libGLX.so.0
            libOpenGL.so.0 => /usr/lib64/libOpenGL.so.0
            libpng16.so.16 => /usr/lib64/libpng16.so.16
            libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0
                libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3
            libfreetype.so.6 => /usr/lib64/libfreetype.so.6
                libbz2.so.1 => /lib64/libbz2.so.1
                libbrotlidec.so.1 => /usr/lib64/libbrotlidec.so.1
                    libbrotlicommon.so.1 => /usr/lib64/libbrotlicommon.so.1
        libQt6Core.so.6 => /usr/lib64/libQt6Core.so.6
            libicui18n.so.73 => /usr/lib64/libicui18n.so.73
            libicuuc.so.73 => /usr/lib64/libicuuc.so.73
                libicudata.so.73 => /usr/lib64/libicudata.so.73
            libdouble-conversion.so.3 => /usr/lib64/libdouble-conversion.so.3
            libb2.so.1 => /usr/lib64/libb2.so.1
                libgomp.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libgomp.so.1
            libpcre2-16.so.0 => /usr/lib64/libpcre2-16.so.0
            libcrypto.so.3 => /usr/lib64/libcrypto.so.3
            ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libstdc++.so.6
        libm.so.6 => /lib64/libm.so.6
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/13/libgcc_s.so.1
    libc.so.6 => /lib64/libc.so.6
```
I do not see something missing on dependencies based on this.
Do I see something I did not here?

**Comment by juippis** [comment]
All libraries that were linked to were present, no problem there. Just that Qt is a bit weird. Sometimes it's a dep of a dep that's missing some feature and causing trouble, and you have these ... qml schemas(?) that can be missing too. Or it could be some general X/wayland issue in a container.

I just wanted to point that out **in case** you hadn't tested it, or knew a similar issue from upstream.

**Comment by CaseOf** [comment]
@juippis thanks to details in this [issue](https://codeberg.org/Case_Of/gentoo-overlay/issues/1), we have a fix.
Can you fix it without needing me to create a new PR?

**Comment by juippis** [comment]
I'll test if it makes a difference and update the ebuild if yes :)

**Comment by juippis** [comment]
Unfortunately that wasn't it for me. I'm guessing this is something container-related.

```
albert 
08:27:14 [fatal:default] No terminals available.  --  [(null)]
```

**Comment by CaseOf** [comment]
ah!
Try to install a GUI terminal emulator?

**Pull request closed without merging**
