### PR TITLE
app-admin/syslog-ng: fix building with CFLAGS=-fno-common

### PR DESCRIPTION
**Pull request by hydrapolic**
Closes: https://bugs.gentoo.org/707124
Package-Manager: Portage-2.3.85, Repoman-2.3.20
Signed-off-by: Tomáš Mózes <hydrapolic@gmail.com>

### CODE REVIEW

**Comment by a17r** [comment]
The point is not to add overrides all over the place. There is some time left until GCC-10 final will enter the tree, you can patch the package properly when upstream have a fix.

**Comment by hydrapolic** [comment]
@a17r I know, but having it working is better than having it perfect.

**Comment by a17r** [comment]
Then you shouldn't close the bug.

**Comment by hydrapolic** [comment]
Yeah, I was thinking about putting Bug instead of Closes into the commit, but I also saw other packages using the same workaround (calling it a fix), so I went with that. You're right, I've pushed an update with Bug: ... instead.

**Comment by hydrapolic** [comment]
Patch taken from https://github.com/syslog-ng/syslog-ng/pull/3114

**Comment by hydrapolic** [comment]
The upstream patch was changed, I'll change it here too.

**Comment by hydrapolic** [comment]
Done

**Comment by hydrapolic** [comment]
Thanks @juippis

**Pull request closed without merging**
