### PR TITLE
sys-boot/grub: fix GRUB_TOP_LEVEL for SYMLINK

### PR DESCRIPTION
**Pull request by xz-dev**
For fix GRUB_TOP_LEVEL support for SYMLINK which created by genkernel, it's look like `/boot/kernel`

### CODE REVIEW

**Comment by thesamesam** [comment]
Should probably be merged together with https://github.com/gentoo/gentoo/pull/33931.

**Comment by xz-dev** [comment]
> Should probably be merged together with #33931.

How to merge together? What should I do.

**Comment by floppym** [comment]
Upstream status?

**Comment by thesamesam** [comment]
> > Should probably be merged together with #33931.
> 
> How to merge together? What should I do?

I meant the maintainer should merge it at the same time, sorry. Anyway, see floppym's q.

**Comment by floppym** [comment]
Please send bug fixes upstream first.

**Pull request closed without merging**
