### PR TITLE
Optional replacement of system set packages with busybox (Bug #618096)

### PR DESCRIPTION
**Pull request by staalmannen**
I have tried these replacements for a while and they seem to be working fine. There are several advantages with tracing busybox symlinks (ownership via package manager, ability to do virtual dependencies knowing that the symlink is there, ...)

### CODE REVIEW

**Comment by mgorny** [comment]
I don't think busybox replacements are fully-featured / POSIX-compliant.

**Comment by staalmannen** [comment]
They are not as feature-rich but they do work (I am using them right now) and certain distros only run on busybox (Alpine for example). The purpose of these packages is to simplify for users to choose to replace one or a few packages with busybox based on their own needs, and to let the package manager be aware of such replacements by virtual dependencies.

**Comment by Polynomial-C** [comment]
Why did you add ebuilds with deprecated EAPI? Everything lower than EAPI-5 should not be used anymore. Please migrate to EAPI-6.
Also new ebuilds should **never** be submitted with stable KEYWORDS. Please drop them to _~arch_ in all ebuilds.

**Comment by mgorny** [comment]
As far as I'm concerned, this is a mostly controversial change and as such I suggest that you start by discussing it, possibly on gentoo-dev mailing list, and do not put any more effort into this before you get a reasonable agreement.

I'm personally opposed to this change, and I believe more @gentoo/qa members may have concerns. My main concerns are:

1. I don't think that busybox is or aims to be fully POSIX-compliant. As such, using it system-wide is a recipe for disaster. Especially considering how poorly most of shell script handle different kinds of errors. I'm against developers having to add workarounds for busybox tools to their packages.
2. The PMS requires a number of ebuild tools to be compatible with the GNU versions. Following that requirement, most of package managers (Portage included) rely on `find` etc. on Linux systems to be the GNU variants. If you want to replace them with busybox, you need to fix Portage to account for that first.
3. Installing 'overrides' for system tools in /usr is short-sighted, and breaks stuff for people using `/usr -> /` symlink and similar variants of the '/usr merge'.

As @gentoo/proxy-maint member I'm seriously concerned about proxied maintainers maintaining such low-level system stuff. So you'd probably have to convince @gentoo/base-system to maintain it with you.

All that said, I should point out that there are very serious concerns regarding the ebuilds you have submitted. I suspect you have never submitted a (valid) ebuild for Gentoo, so I'd suggest you start 'low', and read our development documentation.

**Comment by staalmannen** [comment]
Indeed. This is my first attempt (so it is very possible that the ebuilds
are of low quality, and should probably be seen as "duscussion examples" )
and on my system these replacements work fine (portage works etc ...).

If someone has a smarter/better solution for making the package management
system aware of symlinks and an easy way to do modular replacements I am
all for it. No personal ambition/pride standing in the way.

It might even be better that I just publish them as a 3rd party overlay
instead.

Den 11 maj 2017 14:05 skrev "Michał Górny" <notifications@github.com>:

**Comment by blueness** [comment]
Are we discussing the issue here or in https://bugs.gentoo.org/show_bug.cgi?id=618096.  Anyhow, at first I was intrigued by the idea, but then I came to the same conclusion as @mgorny regarding POSIX compliance and system wide disaster.  For an embedded system its fine because embedded systems are cul-del-sacs which are not then used to further bootstrap other systems.  But for a regular gentoo system, this is a bad idea.  I'm going to close this as WONT FIX.  Sorry @staalmannen.

**Comment by blueness** [comment]
Follow up, please discuss this on gentoo-dev as suggested above if you still want to pursue it.

**Pull request closed without merging**
