### PR TITLE
media-video/mpv: verbump to 0.16.0

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by Coacher** [comment]
Someone already reported a bug and upstream already fixed it. Quickly backport the fix while this PR haven't been merged :)

**Comment by maksbotan** [comment]
What bug do you mean? Should I commit this now?

**Comment by Coacher** [comment]
@maksbotan, see the patch added with 0.16.0 in this PR.

**Comment by Coacher** [comment]
@idella, thank you for the merge.

**Pull request merged**
