### PR TITLE
sys-fs/ncdu: add 2.1.2

### PR DESCRIPTION
**Pull request by BratishkaErik**
Signed-off-by: BratishkaErik <bratishkaerik@getgoogleoff.me>

Tested on my amd64 machine.

### CODE REVIEW

**Review by jsmolic — CHANGES_REQUESTED** [review]
We can't drop 1.15.1 yet as it's the only stable version in the tree, so please leave it as is (and 1.16 since it's next stable candidate)

**Comment by BratishkaErik** [comment]
> We can't drop 1.15.1 yet as it's the only stable version in the tree, so please leave it as is (and 1.16 since it's next stable candidate)

Done.

**Comment by thesamesam** [comment]
Ping @Whissi - how do you want to handle the Zig rewrite?

**Comment by BratishkaErik** [comment]
So according to fdac6c3cdbea5a387df8c1ef528f831ad562d6f5 I should add only 2.1.2 version?

**Comment by jsmolic** [comment]
Yes, I was just about to ping you (I've actually pushed 1.17 quickly to not bother you needlessly since this needs rebasing), could you please rebase (leave only version 2 in the PR)? Thanks

**Comment by BratishkaErik** [comment]
> Yes, I was just about to ping you (I've actually pushed 1.17 quickly to not bother you needlessly since this needs rebasing), could you please rebase (leave only version 2 in the PR)? Thanks

OK

**Comment by BratishkaErik** [comment]
> Yes, I was just about to ping you (I've actually pushed 1.17 quickly to not bother you needlessly since this needs rebasing), could you please rebase (leave only version 2 in the PR)? Thanks

Done.

**Comment by mgorny** [comment]
Please check your mail.

**Comment by BratishkaErik** [comment]
> Please check your mail.

Thank you!  Did you receive my email?

**Pull request closed without merging**
