### PR TITLE
Split off xxd from vim-core

### PR DESCRIPTION
**Pull request by Peter-Levine**
Of `app-editors/vim-core`'s 16 reverse-dependencies, all with the exceptions of `app-editors/vim`, `app-editors/gvim`, and `dev-cpp/ctemplate` rely solely on the xxd hexdump utility included with vim-core.  Although vim is already fragmented by splitting off vim-core, it's hard to justify keeping vim's resource files as a dependency of so many packages that have absolutely nothing to do with text editing.  For reference,  this includes [app-crypt/ima-evm-utils](https://sourceforge.net/p/linux-ima/ima-evm-utils/ci/master/tree/tests/functions.sh#l216), [app-misc/tek](https://github.com/m-ou-se/tek/blob/5ca61325229a66236845f5cb0c362bd01b94312f/Makefile#L42), [dev-db/percona-xtrabackup](https://github.com/percona/percona-xtrabackup/blob/6c73c8214070e494b896efb046b03863668de85d/storage/innobase/xtrabackup/src/CMakeLists.txt#L28), [dev-libs/libbase58](https://github.com/luke-jr/libbase58/blob/b1dd03fa8d1be4be076bb6152325c6b5cf64f678/tests/decode-small.sh#L2), [dev-util/diffoscope](https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/master/diffoscope/comparators/utils/compare.py#L44), [media-libs/libvmaf](https://github.com/Netflix/vmaf/blob/a754965ef876ba5f47fbf60dec3107a3275eb975/libvmaf/src/meson.build#L117), [media-video/harvid](https://github.com/x42/harvid/blob/82d5dba6e5f358edeb6addea57f6132dee5d8e37/src/Makefile#L1), [sci-libs/kim-api](https://github.com/openkim/kim-api/blob/431e641788a5df5ff6058e1974004c7efe93931e/cmake/items-macros.cmake.in#L508), [sys-fs/cryptsetup](https://gitlab.com/cryptsetup/cryptsetup/-/blob/c07cfa20de3b6632d27c256749b93ef8b8b19e18/tests/generators/lib.sh#L150), [sys-fs/dosfstools](https://github.com/dosfstools/dosfstools/blob/77ffb87e8272760b3bb2dec8f722103b0effb801/configure.ac#L80), [www-client/netsurf](https://source.netsurf-browser.org/netsurf.git/tree/content/handlers/javascript/duktape/Makefile?id=e27df0c0b8081f06fec44562b87b35dc0ad434a3#n15), [dev-libs/rocr-runtime](https://github.com/RadeonOpenCompute/ROCR-Runtime/blob/fc99cf8516ef4bfc6311471b717838604a673b73/src/image/blit_src/create_hsaco_ascii_file.sh#L46), and [app-crypt/tpm2-tools](https://github.com/tpm2-software/tpm2-tools/blob/c043b6b453f2be7c205dce11f028823aacf42981/test/integration/tests/ecc.sh#L33).

This PR proposes to split off xxd into `dev-util/xxd` with the blocker `RDEPEND="!<app-editors/vim-core-9.0.0099-r1"` while  for `app-editors/vim-core`, adding `dev-util/xxd` as a runtime dependency, `sed`ing `src/Makefile` to remove the build and installation of xxd, and revbumping `app-editors/vim-core-9.0.0099`.  If accepted, changes can be made piecewise to ebuilds depending on xxd while preventing breakage by having their dependency satisfied indirectly via `app-editors/vim-core` in the meantime. Also added are some aesthetic changes which can be dropped if need be.

Note, if you do decide to accept the PR, `dev-util/xxd` is added as a Vim Project maintained package.

- **dev-util/xxd: new package, add 9999**
Most packages that depend on app-editors/vim-core only depend on xxd. We break it off into its own package and make it a hard dependency of app-editors/vim-core.

- **app-editors/vim-core: add patch to PATCHES array**
Clean up src_prepare a bit by moving patches to the PATCHES array within the topmost conditional version block.

- **app-editors/vim-core: use eautoconf**
Calling "emake -j1 -C src autoconf" is really a src_prepare task, and can be handled just fine with eautoconf.  This avoids a lot of unnecessary deprecation warnings. Other distros like Arch and Fedora call autoconf directly, as well.

- **app-editors/vim-core: don't build xxd along with vim-core**
Roughly 80% of packages in the Gentoo tree that depend on app-editors/vim-core only depend on the xxd hexdump utility included with it.  Break off xxd to it's own package and have vim-core and the rest depend on it.  There doesn't appear any need to couple its versioning to vim-core's.

- **dev-util/xxd: add 9.0.0099**

- **app-editors/vim-core: revbump xxd-less vim-core-9.0.0099** 

Signed-off-by: Peter Levine <plevine457@gmail.com>

### CODE REVIEW

**Comment by Flowdalic** [comment]
vim project (@mkszuba, @monsieurp) this does sound sensible, please review. Thanks

**Comment by thesamesam** [comment]
I don't love the idea of making vim even harder to maintain, as it'll now become yet another package to bump in sync.

If we're going to merge this, someone other than security@ needs to properly handle maintaining vim.

**Comment by mkszuba** [comment]
On 2022-10-03 09:05, Florian Schmaus wrote:

> vim project ***@***.***, @monsieurp) this does sound sensible, please review. Thanks

Personally, I do not like the idea. More maintenance work, and as a 
recent example of IIRC borgmatic shows, it is quite simple to switch 
from xxd to a different hex dumper.

-- 
Marecki

**Comment by Flowdalic** [comment]
Thanks for your feedback. :) Apparently there is a opposition to this (which is fine by me).

**Comment by Peter-Levine** [comment]
If the sentiment is still against splitting off xxd, feel free to close.  I don't personally have a problem with building vim-core with the `minimal` flag.  xxd just seems utterly orthogonal and functionally distinct from the rest of vim.

**Comment by xxc3nsoredxx** [comment]
I disagree with it being orthogonal. The Vim docs in [tips](https://vimhelp.org/tips.txt.html#hex-editing) and [User Manual 23.4](https://vimhelp.org/usr_23.txt.html#23.4) give examples on using `xxd` to turn Vim into "a real binary editor" (and even advertises it as being included with Vim).

So it's gonna be a NACK from me.

**Comment by Peter-Levine** [comment]
> I disagree with it being orthogonal. The Vim docs in [tips](https://vimhelp.org/tips.txt.html#hex-editing) and [User Manual 23.4](https://vimhelp.org/usr_23.txt.html#23.4) give examples on using `xxd` to turn Vim into "a real binary editor" (and even advertises it as being included with Vim).

That it requires piping with `%!xxd` only serves to demonstrate that it's a separate utility which doesn't share any code or functionality with the rest of vim.  It's included because it happens to be very useful as a simple binary editor that can be piped to and from.  This PR only exists because so many other packages also find the utility equally useful in that regard.

But it's not me who would have to maintain the separate ebuild and it's reasonable to not want to split off yet another vim derived package.  I'm fine using `minimal`.

Closing.

**Pull request closed without merging**
