### PR TITLE
app-text/podofo: add 0.10.1

### PR DESCRIPTION
**Pull request by eli-schwartz**
Upstream moved to github and did a lot of cleanup. I have taken the opportunity to drop lots of complicated logic that I don't understand the need for, but which doesn't seem to be relevant to 0.10.x anyway. This is effectively a brand-new ebuild.

Of particular note, the library soname is now incremented in CMakeLists.txt (with real ABI tracking!) and is NOT simply the appended project version in full. The slot has been adjusted accordingly.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I need this for calibre.

**Comment by zmedico** [comment]
Thanks!

**Comment by eli-schwartz** [comment]
range-diff of my patch to the one that landed in the tree:

```
 1:  90da2f004544 ! 80:  fb167a63978a app-text/podofo: add 0.10.1
    @@ Commit message
         CMakeLists.txt (with real ABI tracking!) and is NOT simply the appended
         project version in full. The slot has been adjusted accordingly.
     
    +    Closes: https://github.com/gentoo/gentoo/pull/32941
         Signed-off-by: Eli Schwartz <eschwartz93@gmail.com>
    +    Signed-off-by: Zac Medico <zmedico@gentoo.org>
     
      ## app-text/podofo/Manifest ##
     @@
    @@ app-text/podofo/podofo-0.10.1.ebuild (new)
     +"
     +
     +LICENSE="LGPL-2+ tools? ( GPL-2+ )"
    -+SLOT="0/2"
    ++SLOT="0/${PV}"
     +KEYWORDS="~amd64 ~arm ~arm64 ~hppa ~ppc ~ppc64 ~sparc ~x86"
    -+IUSE="idn jpeg tiff png fontconfig test tools"
    ++IUSE="fontconfig idn jpeg png tiff test +tools"
     +RESTRICT="!test? ( test )"
     +
     +RDEPEND="
    @@ app-text/podofo/podofo-0.10.1.ebuild (new)
     +  if use test; then
     +          rmdir extern/resources || die
     +          mv "${WORKDIR}"/podofo-resources-4afe5c3fdb543a4347681b2e52252f1b10f12f24 extern/resources || die
    ++
    ++          sed -i -e 's|TEST_CASE("testLoadEncrypedFilePdfParser")|void testLoadEncrypedFilePdfParser()|' \
    ++                  -e 's|TEST_CASE("testLoadEncrypedFilePdfMemDocument")|void testLoadEncrypedFilePdfMemDocument()|' \
    ++                  test/unit/EncryptTest.cpp || die
    ++          sed -i -e 's|TEST_CASE("testCyclicTree")|void testCyclicTree()|' \
    ++                  -e 's|TEST_CASE("testEmptyKidsTree")|void testEmptyKidsTree()|' \
    ++                  -e 's|TEST_CASE("testNestedArrayTree")|void testNestedArrayTree()|' \
    ++                  -e 's|TEST_CASE("testCreateDelete")|void testCreateDelete()|' \
    ++                  test/unit/PageTreeTest.cpp || die
     +  fi
     +}
     +
```

I object to the SLOT= change, as I very specifically changed it to "2" for reasons documented in the commit message... for which the commit message was kept when merging.

I also don't understand the requirement for those two seds, they don't have comments describing why they are needed so I can't really judge them.

**Comment by zmedico** [comment]
> I object to the SLOT= change, as I very specifically changed it to "2" for reasons documented in the commit message... for which the commit message was kept when merging.

I noticed that the soname corresponded to ${PV}, so I thought it would be more meaningful and convenient to keep using ${PV} there. If the soname does not change during a future version bump, we can easily fill in that specific soname version in place of ${PV} in the SLOT. I'm skeptical that the soname will be stable enough to make it practical to stop using SLOT="0/${PV}".

> I also don't understand the requirement for those two seds, they don't have comments describing why they are needed so I can't really judge them.

Those test failed for me, so I disabled them. Did they all succeed for you?

**Comment by eli-schwartz** [comment]
> I noticed that the soname corresponded to ${PV}, so I thought it would be more meaningful and convenient to keep using ${PV} there.

No??? Please check again. The soname is, precisely like I said in the commit message, no longer ${PV}, the soname is "2".

There's an additional alias containing ${PV}, but a library *version* is different from the *soname*.

> I'm skeptical that the soname will be stable enough to make it practical to stop using SLOT="0/${PV}".

This seems to generally defeat the purpose of a SLOT and I cannot approve of it at all. Fundamentally, this must bind to the soname ABI and ensure rdeps are rebuilt when required... and ***not*** rebuilt when not required!

Unless you have specific, sustained reasons to believe that upstream is announcing a specific soname but failing to uphold that contract, a package ***MUST NOT***  be overly restrictive on the version and enforce unwanted rebuilds of all rdeps for every patchlevel bugfix release regardless of soname.

It has nothing to do with practicality, just technical correctness.

> Those test failed for me, so I disabled them. Did they all succeed for you?

Yes, they succeeded for me. That's why I submitted the PR.

However, disabling failing updates -- and via a sed no less -- is the wrong way to handle failing tests. I would prefer it if you would simply review the PR and tell me "hey Eli, thanks for the update. Unfortunately the tests fail for me, please investigate why this is happening and make sure podofo is still safe to run."

Analyzing why tests fail for someone else when they don't fail for me is hard, but I started off with disabling various USE flags, and checking the verbose ctest output, and was able to verify that a bunch of the tests fail with error messages such as "could not find an Arial font" or "png support is disabled", so it is plain that the solution here is to mark those tests as skipped based on the USE flags, rather than unconditionally.

I have those changes locally, and they are significantly more extensive than the seds.

I also found a failing test that you don't have a failure for, but that only occurs under rather specific optimizations and is genuinely an upstream bug...

**Comment by eli-schwartz** [comment]
The big problem, as I see it, is that you committed an ebuild with me as the author, which is significantly different from what I offered.

This means that `git blame` accuses me of doing things I believe are wrong and should not be done, which feels personally embarrassing on a reputational level.

**Comment by juippis** [comment]
Yeah, let's try to follow upstream's lead on SONAME and not cause needless rebuilds for minor library bumps. `0/${PV}` has the danger of forgetting the value when copy-pasting old ebuild into new. while when you see a soname change it's easier to spot when testing before pushing.

I'll revert the commit and apply @eli-schwartz's original patch. Eli please make a follow-up PR fixing the test issues, since I also ran into them. 

```
The following tests FAILED:
      9 - testCMYKConstructor (Failed)
     46 - testLoadEncrypedFilePdfParser (Failed)
     47 - testLoadEncrypedFilePdfMemDocument (Failed)
     50 - TestImage2 (Failed)
     51 - TestImage3 (Failed)
     52 - TestImage4 (Failed)
     53 - TestImage5 (Failed)
     64 - testCyclicTree (Failed)
     65 - testEmptyKidsTree (Failed)
     66 - testNestedArrayTree (Failed)
     67 - testCreateDelete (Failed)
Errors while running CTest
```

@zmedico remember that our copyright GLEP (https://www.gentoo.org/glep/glep-0076.html) says 
> The contribution was provided directly to me by some other person who certified 1., 2., 3., or 4., **and I have not modified it.**

when committing. I fix typos and copyright years for the original author, but if you think *"will the author mind me doing this change"*, it's better to just do your follow-up own commit afterwards instead. 

Sorry for the mess, hopefully somewhat handled now, with Eli's test-fix PR!

**Comment by eli-schwartz** [comment]
> I'll revert the commit and apply @eli-schwartz's original patch. Eli please make a follow-up PR fixing the test issues, since I also ran into them.

Followup issue is at #32989

**Comment by zmedico** [comment]
> The big problem, as I see it, is that you committed an ebuild with me as the git commit author, which is significantly different from what I offered. The nature of a signoff is a chain of custody, not an indication that it may have been arbitrarily changed along the way.
> 
> This means that `git blame` accuses me of doing things I believe are wrong and should not be done, which feels personally embarrassing on a reputational level.

I'm sorry about this. The revert in d6d55e48fb313205b8f794771a8c6b70ae835558 hopefully makes things clear.

> @zmedico remember that our copyright GLEP (https://www.gentoo.org/glep/glep-0076.html) says
> 
> > The contribution was provided directly to me by some other person who certified 1., 2., 3., or 4., **and I have not modified it.**
> 
> when committing. I fix typos and copyright years for the original author, but if you think _"will the author mind me doing this change"_, it's better to just do your follow-up own commit afterwards instead.
> 
> Sorry for the mess, hopefully somewhat handled now, with Eli's test-fix PR!

Thanks @juippis!

**Pull request closed without merging**
