### PR TITLE
net-im/skypeforlinux: Bump version to 8.33.0.41

### PR DESCRIPTION
**Pull request by jvesely**

### CODE REVIEW

**Comment by oniGino** [comment]
This version is old we are on 8.33.0.44 now, which has already been merged.
Am I missing something here?

**Comment by oniGino** [comment]
Nevermind I see it..

This is fine except you need to add RDEPEND changes queued up in #10215

https://github.com/gentoo/gentoo/blob/4b57534fdb864aeea46bf2f0de6e67fcdf443447/net-im/skypeforlinux/skypeforlinux-8.32.0.44-r1.ebuild#L25

**Comment by oniGino** [comment]
looks good to me i'll close #10215 after this merges

**Comment by mgorny** [comment]
I'm going to merge #10215 first, as it shouldn't cause any issues while preserving cleaner history of changes.

**Comment by mgorny** [comment]
Hm, or I can't.

**Pull request closed without merging**
