### PR TITLE
 ⬆️♻️🩹🐛 media-libs/oidn: add 2.3.0, fix bugs

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

**Intel Open Image Denoise** `2.3.0` [was released](https://github.com/RenderKit/oidn/releases/tag/v2.3.0) recently.
It would be nice to have it in the Portage tree.

These changes also:
  - ♻️ migrate from [python-single-r1](https://devmanual.gentoo.org/eclass-reference/python-single-r1.eclass/) to [python-any-r1](https://devmanual.gentoo.org/eclass-reference/python-any-r1.eclass/) eclass (`2.3.0` only)
  - 🩹 fix not used `OIDN_APPS_OPENIMAGEIO` CMake variable (bug [928424](https://bugs.gentoo.org/928424))
  - 🐛 fix the `hip` USE flag (bug [930391](https://bugs.gentoo.org/930391))
  - add a repository url to the `HOMEPAGE` (`2.3.0` only)
  - update the `remote-id`

`media-libs/oidn-2.3.0` is based on:
  - [media-libs/oidn-2.2.2](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-libs/oidn/oidn-2.2.2.ebuild?id=493d9099) from #35972 by @negril

<details><summary>diff -u oidn-2.{2.2,3.0}.ebuild</summary>
<p>

```diff
--- oidn-2.2.2.ebuild	2024-06-26 06:56:38.254305797 +0300
+++ oidn-2.3.0.ebuild	2024-06-26 06:55:35.638451835 +0300
@@ -3,35 +3,33 @@
 
 EAPI=8
 
-PYTHON_COMPAT=( python3_{10..12} )
+PYTHON_COMPAT=( python3_{10..13} )
 LLVM_COMPAT=( {15..17} )
 ROCM_VERSION=5.7
 
-inherit cuda cmake python-single-r1 llvm-r1 rocm
+inherit cmake cuda llvm-r1 python-any-r1 rocm
 
-DESCRIPTION="Intel(R) Open Image Denoise library"
-HOMEPAGE="https://www.openimagedenoise.org/"
+DESCRIPTION="Intel® Open Image Denoise library"
+HOMEPAGE="https://www.openimagedenoise.org https://github.com/RenderKit/oidn"
 
 if [[ ${PV} = *9999 ]]; then
-	EGIT_REPO_URI="https://github.com/OpenImageDenoise/oidn.git"
+	EGIT_REPO_URI="https://github.com/RenderKit/oidn.git"
 	EGIT_BRANCH="master"
 	inherit git-r3
 else
-	SRC_URI="https://github.com/OpenImageDenoise/${PN}/releases/download/v${PV}/${P}.src.tar.gz -> ${P}.tar.gz"
-	KEYWORDS="amd64 ~arm ~arm64 ~ppc64 ~x86"
+	SRC_URI="https://github.com/RenderKit/${PN}/releases/download/v${PV}/${P}.src.tar.gz -> ${P}.tar.gz"
+	KEYWORDS="~amd64 ~arm ~arm64 ~ppc64 ~x86"
 fi
 
 LICENSE="Apache-2.0"
 SLOT="0"
 REQUIRED_USE="
-	${PYTHON_REQUIRED_USE}
 	test? ( apps )
 "
 IUSE="apps cuda hip openimageio test"
 RESTRICT="!test? ( test )"
 
 RDEPEND="
-	${PYTHON_DEPS}
 	dev-cpp/tbb:=
 	dev-lang/ispc
 	cuda? ( dev-util/nvidia-cuda-toolkit )
@@ -39,6 +37,7 @@
 	openimageio? ( media-libs/openimageio:= )
 "
 DEPEND="${RDEPEND}"
+BDEPEND="${PYTHON_DEPS}"
 
 PATCHES=(
 	"${FILESDIR}/${PN}-2.2.2-amdgpu-targets.patch"
```

</p>
</details> 

_Best regards!_

---

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

### CODE REVIEW

**Comment by thesamesam** [comment]
As a nit, please avoid "app-misc/foo-1.0.0: x", instead please write "app-misc/foo: fix x in 1.0.0" or similar (i.e. don't write a version number before the colon).

**Comment by Jamim** [comment]
_Hello @thesamesam,_
Thank you for the suggestion!
I've updated commit messages.

**Comment by thesamesam** [comment]
negril is going to ask someone to runtime test it then he'll let me know when it's good-to-go. Thanks!

**Comment by negril** [comment]
Didn't hear or had any failures. Can be merged.

**Comment by DarkDefender** [comment]
2.3.0 is now the version the used upstream builds of Blender. So I don't expect too many issues either :)

**Pull request closed without merging**
