### PR TITLE
sys-fs/cryptsetup: Allow USE="gcrypt" with USE="static"

### PR DESCRIPTION
**Pull request by negge**

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Can you please apply this change to cryptsetup-1.7.5 and 2.0.0-r1?

**Comment by robbat2** [comment]
Does it actually work if you do this? Do the tests complete?

**Comment by negge** [comment]
I am still using this patch, and yes it works if you apply it.  I can test on the latest version.

**Comment by negge** [comment]
I just installed gentoo on a new system with USE="gcrypt" and USE="static" using this patch.  Since cryptsetup-1.7.5-r1 is still the only stable version, can we please land this?

**Comment by Whissi** [comment]
This PR is dead and broken. Please create a new one.

**Comment by negge** [comment]
Right, that is all that is needed to allow you to build a static cryptsetup that uses gcrypt.  It was a patch to the ebuild.  I'm happy to make the same comment on 496612, other people there have also made this change with success.

**Pull request closed without merging**
