### PR TITLE
dev-util/hip-5.4.3 enhancement, rocm 9999 ebuilds, rocRAND/rocFFT/hipFFT-5.4.3

### PR DESCRIPTION
**Pull request by littlewu2508**
1. For dev-util/hip-5.4.3, fix a QA issue, fixed a runtime issue, corrected a patch bumped from previous version, enable tests, remove 5.1.3 ebuild to reduce number of patches
2. Complete 5.4.3 and add 9999 ebuilds for ROCm stack: dev-libs/rocm-device-libs, dev-libs/rocm-comgr, dev-util/hip, dev-util/rocprofiler, dev-util/roctracer
3. sci-libs/rocFFT-5.1.3 and sci-libs/hipFFT-5.1.3: loose SLOT dependency on dev-util/hip due to removal of 5.1.3
4. Add sci-libs/{rocFFT,rocRAND,hipFFT}-5.4.3.

### CODE REVIEW

**Comment by matoro** [comment]
Hi, what is missing to get this marked as ready for review?  It is blocking use of `USE=amdgpu_targets_gfx1100` across the ROCm stack.

**Comment by littlewu2508** [comment]
> Hi, what is missing to get this marked as ready for review? It is blocking use of `USE=amdgpu_targets_gfx1100` across the ROCm stack.

If I remember correctly, this PR contains too much changes making it hard to review, and there's a little work left.  I wish to split it into several parts but unfortunately I was occupied.

Then ROCm 5.5 came out and have much better gfx11* support, so I would like to go directly to 5.5, so this is somehow abandoned.

**Comment by matoro** [comment]
> > Hi, what is missing to get this marked as ready for review? It is blocking use of `USE=amdgpu_targets_gfx1100` across the ROCm stack.
> 
> If I remember correctly, this PR contains too much changes making it hard to review, and there's a little work left. I wish to split it into several parts but unfortunately I was occupied.
> 
> Then ROCm 5.5 came out and have much better gfx11* support, so I would like to go directly to 5.5, so this is somehow abandoned.

I agree, I made a stab at 5.5 myself but ran into mysterious include problems with the clang headers.  Would appreciate a ping if you get a PR up, I can poke in the dev channel to get it reviewed!

**Comment by littlewu2508** [comment]
> I agree, I made a stab at 5.5 myself but ran into mysterious include problems with the clang headers. Would appreciate a ping if you get a PR up, I can poke in the dev channel to get it reviewed!

Yes. I met similar problems and managed to resolve them. And as rocm-5.6 came out, I'll have a try. And I'll spend some time to sort all my ebuilds and patches out -- packaging ROCm stack requires a large amount of working.

My 5.5 ebuilds are in https://github.com/littlewu2508/gentoo/tree/rocm-5.5, maybe it can provide some help.

**Comment by sozforex** [comment]
@matoro If you have working hipBLAS-5.5.1, can you please share your rocm/hip related ebuilds?

**Comment by matoro** [comment]
> @matoro If you have working hipBLAS-5.5.1, can you please share your rocm/hip related ebuilds?

@sozforex Here you go, I just pushed it up here in case anyone wants to build off this:  https://github.com/matoro/overlay/tree/rocm-5.5.1.  Note that I did NOT run or wire up unit tests, I just did the bare minimum to get everything to compile.  I also used prebuilt pytorch wheels from the nightly archive, I did not build torch myself.

Perhaps I did something wrong or perhaps my GPU is a piece of junk.  Either way, I just ended up attaching an NVIDIA card and passing it through to a virtual machine, where it works like a charm, but I am sorely missing the 24G of VRAM.

**Comment by sozforex** [comment]
Thank you @matoro, I've tried your 5.5.1 and @littlewu2508's https://github.com/littlewu2508/gentoo/tree/rocm-5.6 but were not able to compile rocBLAS (possibly because I'm using clang gentoo profile)

I get bunch of errors like this while compiling rocBLAS:

```
In file included from /var/tmp/portage/sci-libs/rocBLAS-5.6.0/work/rocBLAS-rocm-5.6.0/library/src/include/rocblas_ostream.hpp:39:                                                                                                                               
In file included from /usr/include/c++/v1/queue:229:                                                                                                                                                                                                            
/usr/include/c++/v1/deque:406:67: error: expected ')'                                                                                                                                                                                                           
  static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
                                                                  ^                                                                                                                                                                                             
/usr/include/c++/v1/deque:406:56: note: to match this '('                                                                                                                                                                                                       
  static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
                                                       ^                                                                                                                                                                                                        
/usr/include/c++/v1/deque:406:57: error: redefinition of '_Iterator' as different kind of symbol                                                                                                                                                                
  static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
                                                        ^                                                                                                                                                                                                       
/usr/include/c++/v1/deque:398:9: note: previous definition is here                                                                                                                                                                                              
  using _Iterator = __deque_iterator<_ValueType, _Pointer, _Reference, _MapPointer, _DiffType, _BlockSize>;                                                                                                                                                     
        ^                                                                                                                                                                                                                                                       
/usr/include/c++/v1/deque:406:77: error: expected expression                                                                                                                                                                                                    
  static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
                                                                            ^                                                                                                                                                                                   
/usr/include/c++/v1/deque:419:4: error: expected ';' at end of declaration list                                                                                                                                                                                 
  }
```

**Comment by matoro** [comment]
> Thank you @matoro, I've tried your 5.5.1 and @littlewu2508's https://github.com/littlewu2508/gentoo/tree/rocm-5.6 but were not able to compile rocBLAS (possibly because I'm using clang gentoo profile)
> 
> I get bunch of errors like this while compiling rocBLAS:
> 
> ```
> In file included from /var/tmp/portage/sci-libs/rocBLAS-5.6.0/work/rocBLAS-rocm-5.6.0/library/src/include/rocblas_ostream.hpp:39:                                                                                                                               
> In file included from /usr/include/c++/v1/queue:229:                                                                                                                                                                                                            
> /usr/include/c++/v1/deque:406:67: error: expected ')'                                                                                                                                                                                                           
>   static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
>                                                                   ^                                                                                                                                                                                             
> /usr/include/c++/v1/deque:406:56: note: to match this '('                                                                                                                                                                                                       
>   static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
>                                                        ^                                                                                                                                                                                                        
> /usr/include/c++/v1/deque:406:57: error: redefinition of '_Iterator' as different kind of symbol                                                                                                                                                                
>   static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
>                                                         ^                                                                                                                                                                                                       
> /usr/include/c++/v1/deque:398:9: note: previous definition is here                                                                                                                                                                                              
>   using _Iterator = __deque_iterator<_ValueType, _Pointer, _Reference, _MapPointer, _DiffType, _BlockSize>;                                                                                                                                                     
>         ^                                                                                                                                                                                                                                                       
> /usr/include/c++/v1/deque:406:77: error: expected expression                                                                                                                                                                                                    
>   static _LIBCPP_HIDE_FROM_ABI __local_iterator __local(_Iterator __iter) { return __iter.__ptr_; }                                                                                                                                                             
>                                                                             ^                                                                                                                                                                                   
> /usr/include/c++/v1/deque:419:4: error: expected ';' at end of declaration list                                                                                                                                                                                 
>   }
> ```

Looks like some sort of naming conflict with libc++ maybe?  I briefly went through the rocBLAS source code but didn't see any obvious culprits.  Does it work when you use libstdc++?  (`-stdlib=libstdc++`)  Or vice-versa with libc++ if you are using libstdc++.

**Comment by sozforex** [comment]
@matoro Thank you very much, I was able to build rocBLAS with -stdlib=libstdc++ (everything else in system is built with libc++).

**Comment by sozforex** [comment]
@matoro I do not have enough understanding of this to make a reasonable report. I was able to build hipBLAS-5.5.1 and hipBLAS-5.6.0, but not to make it work, even after switching to a normal gentoo profile (not clang). hipBLAS-5.4.3 works for me.

**Comment by matoro** [comment]
> @matoro I do not have enough understanding of this to make a reasonable report. I was able to build hipBLAS-5.5.1 and hipBLAS-5.6.0, but not to make it work, even after switching to a normal gentoo profile (not clang). hipBLAS-5.4.2 works for me.

Can you elaborate what you mean by "make it work"?  That gives no information about what exactly went wrong.

**Comment by sozforex** [comment]
@matoro In my case to "make it work" was to make ROCm Port of llama.cpp (that requires hipBLAS) to not crash at runtime when computation is offloaded to my GPU (RX 6850M XT, navi 22, gfx1031).
I was able to make it work on non-clang profile with latest hip/rocm packages available in main gentoo repository (5.4.2 / 5.4.3).

At some point I've decided to try clang profile (clean install). Had problems building some hip/rocm packages (5.4.2). Tried newer versions of those packages (5.5.1, 5.6.0), was able (with your help) to make them build, but not to make them work with ROCm Port of llama.cpp. At least some build problems were related to stdlib (libc++ is used systemwide in clang profile, but I was able to compile rocBLAS only with libstdc++). Runtime errors were possibly related to dev-libs/boost being build with libc++ and rocBLAS with libstdc++. I have not been able to build boost with libstdc++.
I have not tried to build rocBLAS-5.4.2 with libstdc++ on clang profile.

On non-clang profile it was not a problem to build 5.5.1 and 5.6.0 hipBLAS, but llama.cpp crushed at runtime. With hipBLAS-5.4.2 it works. I do not know how to debug problems related to hip/rocm, so no idea why 5.5.1 and 5.6.0 did not work.

**Comment by littlewu2508** [comment]
> On non-clang profile it was not a problem to build 5.5.1 and 5.6.0 hipBLAS, but llama.cpp crushed at runtime.

I was also bumping rocBLAS to 5.6 in the past month, but tests badly crashed on any cards I can access, so that's why the rocBLAS-5.6 stucks at version bumping.

**Comment by littlewu2508** [comment]
> I was also bumping rocBLAS to 5.6 in the past month, but tests badly crashed on any cards I can access, so that's why the rocBLAS-5.6 stucks at version bumping.

However the test from official rocBLAS binary distribution by AMD does not meet any issue. I'm still investigating this.

**Comment by matoro** [comment]
> @matoro In my case to "make it work" was to make ROCm Port of llama.cpp (that requires hipBLAS) to not crash at runtime when computation is offloaded to my GPU (RX 6850M XT, navi 22, gfx1031). I was able to make it work on non-clang profile with latest hip/rocm packages available in main gentoo repository (5.4.2 / 5.4.3).
> 
> At some point I've decided to try clang profile (clean install). Had problems building some hip/rocm packages (5.4.2). Tried newer versions of those packages (5.5.1, 5.6.0), was able (with your help) to make them build, but not to make them work with ROCm Port of llama.cpp. At least some build problems were related to stdlib (libc++ is used systemwide in clang profile, but I was able to compile rocBLAS only with libstdc++). Runtime errors were possibly related to dev-libs/boost being build with libc++ and rocBLAS with libstdc++. I have not been able to build boost with libstdc++. I have not tried to build rocBLAS-5.4.2 with libstdc++ on clang profile.
> 
> On non-clang profile it was not a problem to build 5.5.1 and 5.6.0 hipBLAS, but llama.cpp crushed at runtime. With hipBLAS-5.4.2 it works. I do not know how to debug problems related to hip/rocm, so no idea why 5.5.1 and 5.6.0 did not work.

By crashed do you mean segfaulted in userspace, or the kernel driver crashed?  For me it was the latter.  If it was the former what error did you get, and can you grab a traceback?

**Comment by sozforex** [comment]
> By crashed do you mean segfaulted in userspace, or the kernel driver crashed? For me it was the latter. If it was the former what error did you get, and can you grab a traceback?

Segfault in userspace (to best of my knowledge), without any information that looked useful to me. Will try to get some useful extra info tomorrow or day after tomorrow (it will help if you can tell me how to get useful traceback, or point me to a some related reading).

Oh, and I've just remembered that your rocBLAS-5.5.1.ebuild (https://github.com/matoro/overlay/blob/rocm-5.5.1/sci-libs/rocBLAS/rocBLAS-5.5.1.ebuild) uses old Tensile-asm_full-navi22.tar.gz file (at least directory structure is different in 5.5.1). You can find a newer one by littlewu2508 here: https://github.com/littlewu2508/littlewu2508.github.io/tree/main/gentoo-distfiles

**Comment by matoro** [comment]
> > By crashed do you mean segfaulted in userspace, or the kernel driver crashed? For me it was the latter. If it was the former what error did you get, and can you grab a traceback?
> 
> Segfault in userspace (to best of my knowledge), without any information that looked useful to me. Will try to get some useful extra info tomorrow or day after tomorrow (it will help if you can tell me how to get useful traceback, or point me to a some related reading).
> 
> Oh, and I've just remembered that your rocBLAS-5.5.1.ebuild (https://github.com/matoro/overlay/blob/rocm-5.5.1/sci-libs/rocBLAS/rocBLAS-5.5.1.ebuild) uses old Tensile-asm_full-navi22.tar.gz file (at least directory structure is different in 5.5.x). You can find a newer one by littlewu2508 here: https://github.com/littlewu2508/littlewu2508.github.io/tree/main/gentoo-distfiles

There's a guide on the Gentoo wiki [here](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Backtraces).  Basically, just compile with `CFLAGS="-O0 -pipe -ggdb3"` and `FEATURES="nostrip"`, then run the command that's segfaulting under gdb.  When it segfaults, run `bt` to get a backtrace.

**Comment by sozforex** [comment]
@mataro sorry for delay, I do not have a need to look for a reason for the runtime error I've mentioned anymore, because I was able to make it work.

CC: @littlewu2508

I've been able to make hipBLAS-5.6.0 (with all hip/rocm dependencies 5.6.0) work just now (for llama.cpp [ggerganov/llama.cpp@`4024f91` (#1087)](https://github.com/ggerganov/llama.cpp/pull/1087/commits/4024f91a665d83b6de8658d45ec9d004c5d90c79) with clang-16.0.6, and the latest https://github.com/ggerganov/llama.cpp/pull/1087 with AOCC-4.1). I'll share ebuilds tomorrow.

Not sure how this time was different from past attempts exactly, but couple unverified things of note:

- I've used hop/rocm related ebuilds (5.6.0) from https://github.com/littlewu2508/gentoo/tree/rocm-5.6 . 
- Made ebuilds for sci-libs/hipBLAS-5.6.0 and it's dependencies which were not available with 5.6.0 version in littlewu2508's repo (used either newest ebuilds from littlewu2508's repo, or from gentoo as a base, with some small changes in some cases)
- ensured sys-devel/clang-runtime is built with +openmp flag
- ensured sys-libs/libomp is built with +offload flag (it was disabled previously on my system)
- Tensile ebuild with LLVM_MAX_SLOT=15 (not sure if required, will test with 16 tomorrow)

As a note, if you get a compilation error similar to this (https://github.com/ggerganov/llama.cpp/pull/1087#issuecomment-1672569636), try using AOCC-4.1 for your project (CC=<somepath>/aocc-compiler-4.1.0/bin/clang, CXX=<somepath>/aocc-compiler-4.1.0/bin/clang++) without recompiling rocm/hip with AOCC.

**Comment by sozforex** [comment]
@matoro here are all 5.6.0 ebuilds required for hipBLAS-5.6.0 [rocm-5.6.0-ebuilds.tar.gz](https://github.com/gentoo/gentoo/files/12329828/rocm-5.6.0-ebuilds.tar.gz), most of them were taken from [littlewu2508/gentoo@rocm-5.6](https://github.com/littlewu2508/gentoo/tree/rocm-5.6?rgh-link-date=2023-08-12T21%3A50%3A23Z) without changes.
hipBLAS-5.6.0, rocPRIM-5.6.0, rocSOLVER-5.6.0, rocSPARSE-5.6.0 are newly created.

@littlewu2508 here is a patch for your rocm-5.6 branch if you want to include these ebuilds [rocm56-littlewu2508.patch.gz](https://github.com/gentoo/gentoo/files/12329845/rocm56-littlewu2508.patch.gz)

**Comment by littlewu2508** [comment]
> @matoro here are all 5.6.0 ebuilds required for hipBLAS-5.6.0 [rocm-5.6.0-ebuilds.tar.gz](https://github.com/gentoo/gentoo/files/12329828/rocm-5.6.0-ebuilds.tar.gz), most of them were taken from [littlewu2508/gentoo@rocm-5.6](https://github.com/littlewu2508/gentoo/tree/rocm-5.6?rgh-link-date=2023-08-12T21%3A50%3A23Z) without changes. hipBLAS-5.6.0, rocPRIM-5.6.0, rocSOLVER-5.6.0, rocSPARSE-5.6.0 are newly created. Archive contains some patches that are not used in 5.6.0 ebuilds.
> 
> @littlewu2508 here is a patch for your rocm-5.6 branch if you want to include these ebuilds [rocm56-littlewu2508.patch.gz](https://github.com/gentoo/gentoo/files/12329845/rocm56-littlewu2508.patch.gz)

Thank you for the contribution! I'll run tests for them. Can you send a PR to my branch (or send PR containing my rocBLAS ebuild directly to ::gentoo)?

**Pull request closed without merging**
