### PR TITLE
dev-lang/erlang: fix localhost clash with Docker

### PR DESCRIPTION
**Pull request by ignamartinoli**
need is incompatible with Docker

Closes: https://bugs.gentoo.org/857099
Signed-off-by: igna_martinoli <ignamartinoli@protonmail.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
@tgbugs ok?

**Comment by tgbugs** [comment]
Hrm. In my testing this fails to start. Debugging now.

**Comment by tgbugs** [comment]
Ok, so there is some really broken stuff going on between rabbitmq and epmd. This does indeed resolve my immediate issue with docker ... but only because epmd is technically "running" when it is in the crashed state and rabbitmq then seemingly starts its own instance of epmd (!?!?!). It looks like epmd crashes in docker no matter what right now. I did my test with loopback down/disabled, and everything seems ok with `use loopback`.

All in all I think this is ok, and more representative of correct epmd behavior. The epmd init in docker is still borked, but let's take that in a separate issue.

**Comment by tgbugs** [comment]
On further though, why not just comment out the `-command-args` line in conf.d while we're at it since that is technically the default behavior anyway?

**Comment by MatthewGentoo** [comment]
Would it be best to have `use net` instead of `use lo` for cases like this where the bind address is changed?

**Comment by ignamartinoli** [comment]
Hey, sorry for going missing. I was submerged by university and planned to resume the work with this on November.

Thanks @MatthewGentoo for giving this issue a conclusion, I really hope to be able to help on other issues soon :smiley:

**Pull request closed without merging**
