### PR TITLE
net-misc/frr: Fix implicit declaration of function basename

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/938756

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by jkroonza — COMMENTED** [review]
Has this been submitted upstream?

I don't have objections to this, but would like to know it's been submitted upstream at least.

I don't like the fact that strrchr is called twice, an inline function may be more appropriate (assuming strrchr is marked pure this should be fine as the compiler can then optimize out the second call).

The bigger issue is that the result is wrong in a case like basename("foo/bar/") which here will return "" rather than "bar".  If you can prove that no such cases exist for frr I'd be OK with this change.

**Comment by listout** [comment]
> Has this been submitted upstream?

Yes, with commit https://github.com/FRRouting/frr/commit/0ef71391f0fb15039550a09c218977fa3e1abaf1. I just took the patch from upstream source.

**Comment by jkroonza** [comment]
If this comes from Upstream I have no objection.  Is it really required, or can we just wait for a version bump?  In other words - is there an immediate need for musl support?

**Comment by eli-schwartz** [comment]
> Is it really required, or can we just wait for a version bump? In other words - is there an immediate need for musl support?

Well, there's an available upstream version that isn't getting packaged...

Also yes, packages that are broken would ideally be fixed. Gentoo officially supports musl, so fixing musl support should be done sooner rather than later unless you're aware of an imminent new release.

**Comment by jkroonza** [comment]
OK, @eli-schwartz I think a version bump is then more in order.  Will see what I can do about that this week still.  Sorry, whilst frr is critical for us unfortunately time is a luxury which currently isn't in abundance.

**Comment by alarig** [comment]
I didn’t bumped the version yet because there are confits on the yang files from frr and libyang

**Comment by jkroonza** [comment]
> I didn’t bumped the version yet because there are confits on the yang files from frr and libyang

I thought we intended to abandon libyang entirely since it's so tightly integrated with frr anyway that it's unlikely to see other users regardless and really ships as the same tarball anyway, so might just as well just have frr ... which should simplify the entire build process?

If that's going to take some time, let's ship this PR so long and then rather deal with that properly?  I think even if we merge these two packages we should test more thoroughly than usual so perhaps shipping this is a good intermediary anyway?

**Review by juippis — APPROVED** [review]
Works on both musl and glibc. Still getting this though:
```
 * QA Notice: Found the following implicit function declarations in configure logs:
 *   /var/tmp/portage/net-misc/frr-9.1-r1/work/frr-frr-9.1/config.log:13345 - mallinfo
 *   /var/tmp/portage/net-misc/frr-9.1-r1/work/frr-frr-9.1/config.log:13599 - mallinfo2
```

**Pull request closed without merging**
