### PR TITLE
dev-lang/lazarus-3.4: add a new version of the package

### PR DESCRIPTION
**Pull request by dpronin**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

Closes: https://bugs.gentoo.org/933988

### CODE REVIEW

**Comment by dpronin** [comment]
@thesamesam please, check it out. I think that the maintainer has flown away somewhere

**Comment by thesamesam** [comment]
Can you check https://forums.gentoo.org/viewtopic-t-1169386.html? Your commit might already handle it though.

**Comment by dpronin** [comment]
> Can you check https://forums.gentoo.org/viewtopic-t-1169386.html? Your commit might already handle it though.

If we merge these changes then we will require qt6 with correct SLOT requirements. I think the issue in this topic is in inconsistency between SLOT of lazarus and its dependency libqt6pas

**Comment by thesamesam** [comment]
You can rebase and just drop the conan commit, and force push.

**Comment by dpronin** [comment]
> You can rebase and just drop the conan commit, and force push.

My mistake, I have closed the PR since it fetches changes from my master

See https://github.com/gentoo/gentoo/pull/37136

**Pull request closed without merging**
