### PR TITLE
Pecl parallel php8

### PR DESCRIPTION
**Pull request by jkroonza**

### CODE REVIEW

**Comment by ConiKost** [comment]
Could you test also ```php8-2``` support? Thx!

**Comment by jkroonza** [comment]
1.  Updated to support php 8.2
2.  Updated to use PHP_EXT_NEEDED_USE rather than re-doing the entire structure again.
3.  Updated to drop IUSE=test since there are no extra deps required for tests (trust this is in order).
4.  Upstream tests pass for all versions (on my system at least).

**Comment by jkroonza** [comment]
> ## Pull request CI report
> 
> _Report generated at_: 2022-10-24 22:58 UTC _Newest commit scanned_: [1de2e5a](https://github.com/gentoo/gentoo/commit/1de2e5a667020433f160e5e74ecde712ea2f67e4) _Status_: x **broken**
> 
> New issues caused by PR: https://qa-reports.gentoo.org/output/gentoo-ci/d9bc636f79/output.html#global
> 
> There are existing issues already. Please look into the report to make sure none of them affect the packages in question: https://qa-reports.gentoo.org/output/gentoo-ci/d9bc636f79/output.html

@ConiKost - I don't see what I did to cause this, could you perhaps assist please?

**Comment by ConiKost** [comment]
Yes, please rebase to newest master, this will fix it. There was a pkgmove which caused this.

**Pull request closed without merging**
