### PR TITLE
sys-apps/miller: new package

### PR DESCRIPTION
**Pull request by rindeal**

### CODE REVIEW

**Comment by idella** [comment]
@gentoo/proxy-maint 

1. `DESCRIPTION="Miller is like sed, awk, cut, join, and sort for name-indexed data (CSV, JSON)"`
In DESCRIPTION the name of the package is not to appear.
The text is to come in <= 80 chars.

2. SRC_URI="https://github.com/johnkerl/miller/archive/v${PV}.tar.gz" ->
    SRC_URI="https://github.com/johnkerl/${PN}/archive/v${PV}.tar.gz -> ${P}.tar.gz"

The rest should be ok

**Comment by idella** [comment]
Wondering if TEST_DIRS=( c/{reg,unit}_test  need be set a  global var.
Why can it not be set as 
local TEST_DIRS=( c/{reg,unit}_test 
within the for_each_test_dir()

**Comment by rindeal** [comment]
1. The DESCRIPTION is 79 chars wide, please suggest an alternative if you have problem with $PN in it
2. will do, thanks for noticing, I'm ashamed
3. x86 not tested, but generally when amd64 is there, x86 is there too

TEST_DIRS is just as global as the helper func, because before I rewrote the ebuild it was used in multiple `src_*()` functions.

**Comment by idella** [comment]
It is simply a gentoo ebuilding rule that most seem not to know. Perhaps
"A text formatting tool for name-indexed data (CSV, JSON)"
w/e. Taking the name out automatically reduced the length which is however just inside the border anyway.

I am fine with x86 to accompany and while there are some who are not. On my part, the instances of something not working on x86 that does work on amd64 are rare corner case. I still need to get my CB2 working again to capture requests like this.

TEST_DIRS being local or global is not cortical. There are some devs who object to global vars our of principle rather than out of any practical malfunction. Both work

**Comment by rindeal** [comment]
>  "A text formatting tool for name-indexed data (CSV, JSON)"

Formatting is only a small part of what this tool is capable of.

I think it's just bike shedding, but my 2c anyway:

> A tool like sed, awk, cut, join, and sort for name-indexed data (CSV, JSON, ..)

 which is 80 chars exactly.

**Comment by rindeal** [comment]
Btw. what is `CB2` ?

**Comment by idella** [comment]
CB2 is cubieboard2, like an rpi, has an arm board.

**Comment by idella** [comment]
All works for me.

**Comment by rindeal** [comment]
> The ordering of the vars LICENSE SLOT SRC_URI is curious.

Not so much curious, it's rather logical:

1. DESCRIPTION, HOMEPAGE, LICENSE are all raw metadata and thus go together as first
2. SRC_URI often contains MY_PN/MY_PV, which goes hand in hand with SLOT, thus the next logical block is MY_PN, MY_PV, SLOT, SRC_URI. I'd call these variable metadata
3. Then go simple enumerations - KEYWORDS, IUSE
4. Next are complex dependencies - *DEPEND
5. And finally restrictions for all of the above and below - REQUIRED_USE, RESTRICT

**Pull request closed without merging**
