### PR TITLE
 gnome-extra/gnome-commander: version bump and remove old

### PR DESCRIPTION
**Pull request by turboscholz**

### CODE REVIEW

**Comment by leio** [comment]
Requiring a specific gcc version is typically a wrong thing to do. Why is that done? Does it not work with clang? Why >=8.2 specifically?

**Comment by leio** [comment]
Upstream (you?) should properly test for warning flag availability before use first; there is also clang to consider with. At downstream we can filter them out from build system or so. At this point probably gcc7 can be assumed to be in use and it's fine to just implicitly fail with older. Soon that'll be gcc8.
Depending on compilers isn't something we really do, and is typically a QA issue.

**Comment by turboscholz** [comment]
Okay, you're right, I should have done this. But isn't it a bug if we would get an error if someone with gcc7 get's a build error? By using the gcc8 dependency we don't have this kind of error at all.

Regarding clang: I do not have experience with it. I don't even know how to compile my packages with it. Is there a HowTo for package maintainers how to test their packages with clang?

**Comment by juippis** [comment]
In it's simplest form, 
`CC=clang CXX=clang++ emerge -1av gnome-commander` :)

I just did and it compiles and runs fine when clang-8 is being used. That brings me to my 2nd point: As you can see, the DEPEND="gcc" doesn't work as you intended. Gcc-8 can be installed, and it satisfies the dependency, but it might not be used when building. So I can choose gcc-7  from gcc-config, and the build will still break if you say it doesn't work with gcc-7. 

The correct way to test >=gcc-8 satisfaction is to use toolchain-funcs.eclass. You want to make a check `ìf tc-is-gcc && gcc-major-version -lt 8 ; then die "GCC too old, please use gcc-8 or above."` in pkg_setup or something like that. There are examples in the tree, and study toolchain-funcs.eclass. This is just out of my head, but you get the idea. 

Keep it in mind if you want to fix this version, or when updating for next one :)

**Comment by turboscholz** [comment]
Thank you, this was really helpful! I will keep this in mind.

**Pull request closed without merging**
