### PR TITLE
dev-libs/pigpio: fix libdir variable

### PR DESCRIPTION
**Pull request by github-k8n**
Fixed libdir variable (/usr/ prefix missing, current ebuilds do not install libs at all)

Signed-off-by: Daniel Kenzelmann <gentoo@k8n.de>

### CODE REVIEW

**Comment by github-k8n** [comment]
Ah, crap, wanted to make two separate cases here, but somehow it did join the pull requests here .. still not that good with git :-(

Hope that still works, the updated old ebuilds and the new ebuild are separate commits here..

**Comment by github-k8n** [comment]
Forgot to update Manifest file with second commit, included/rebased it with new ebuild commit ...

**Comment by github-k8n** [comment]
There was a new bug after I submitted the pull request pointing out the libdir issue https://bugs.gentoo.org/691948

**Comment by juippis** [comment]
Can't test this (yet) but overall looks good. Thanks!

**Comment by github-k8n** [comment]
hmm.. isn't it supposed to include both commits? I only see "dev-libs/pigpio-70: new ebuild" (201ab91) merged, but not "dev-libs/pigpio: fix libdir variable" (05740e2)

**Comment by juippis** [comment]
It's there, as a separate commit:
c85f15d0dd0ee6fe1c031dc6ab115cb980693c4d
7ab8f5559849fa4eac973b582d03e2734cdd488f

PS your `dev-libs/pigpio-70` is wrongly formatted, I apparently failed to rebase it to its right form while closing the bug you linked, but keep that in mind for the next time :) write something like `dev-libs/pigpio: bump to version 70`.

**Comment by github-k8n** [comment]
thanks, will do :)

**Pull request closed without merging**
