### PR TITLE
dev-libs/{sway,wlroots}: some fixes & version bump; app-text/scdoc: version bump; app-misc/sway{idle,lock}: new packages

### PR DESCRIPTION
**Pull request by SpeedJack**
Sway has split into some subprojects: `swayidle` and `swaylock`. This PR adds these new packages and fixes `sway-9999` that now no longer installs `sway{idle,lock}`. `scdoc` is updated to v1.8.0 (it is required by Sway to generate man pages). ~`dev-libs/sway` is moved to `x11-wm/sway`, as decided in related bug (see commit).~ This PR contains also some other minor fixes in `sway` and `wlroots`.

### CODE REVIEW

**Comment by SpeedJack** [comment]
> You mention it was 'decided' in the bug that sway should go into x11-wm,
> this is not the case and nothing was decided, just a lot of back and forth banter.

I thought it was decided since a Gentoo dev, @mgorny , recently changed the title of the bug saying that it "should be x11-wm/sway". And anyway `x11-wm` is still better that `dev-libs`.
I'll soon remove the commit that moves `dev-libs/sway -> x11-wm/sway`. But it would be better to have a definitive decision on where to put Sway - maybe from the @gentoo/x11 team(?).

**Comment by bemeurer** [comment]
@SpeedJack Thanks for the work! Hope this gets merged in soon!

**Comment by bemeurer** [comment]
@SpeedJack Maybe add the newly-cut RC1 as well? https://github.com/swaywm/sway/releases/tag/1.0-rc1

**Comment by bemeurer** [comment]
@hanetzer Can this be merged?

**Comment by hanetzer** [comment]
@bemeurer I'm not a dev so not my sayso

**Comment by bemeurer** [comment]
@mgorny Any chance this can be merged?

**Comment by SpeedJack** [comment]
@Zlogene bman, who usually takes care of Sway, is inactive in this period. Can you review & merge, please?

**Comment by bemeurer** [comment]
@Zlogene One could say it would be [_sway_](https://www.urbandictionary.com/define.php?term=Sway) if you were able to merge this.

I'll show myself out now :stuck_out_tongue:

**Comment by AzP** [comment]
@SpeedJack, do you happen to have a published overlay, that one could use in the meantime? I added the 'sorrow' overlay, that seems to have some sway-related stuff.
https://gpo.zugaina.org/Overlays/sorrow

**Comment by SpeedJack** [comment]
Not for now, but I will publish an overlay on github in the next days with Sway and all related packages.

**Comment by flappyports** [comment]
> @Zlogene bman, who usually takes care of Sway, is inactive in this period. Can you review & merge, please?

Sorry, I am not always on Github.  Do you still intend to make the changes you mentioned in bug #677522

**Comment by prometheanfire** [comment]
Didn't see this before I bumped it in tree.  I also made a thread for a new category on gentoo-dev.  wayland-wm I think is too small, but something more general like wayland-misc would be a good catch-all until more wayland things are packaged and more categories can be made.

**Comment by SpeedJack** [comment]
> Do you still intend to make the changes you mentioned in bug #67752

Yes, but I'll do it in a new PR (rebasing this PR requires too much time). But I still don't understand what causes the bug.

**Comment by prometheanfire** [comment]
ok, just ping me in the new PR when made

**Pull request closed without merging**
