### PR TITLE
net-misc/netctl: bump 1.19 

### PR DESCRIPTION
**Pull request by xenoist**
Bump 1.19
Support removable devices in automatic connections.
mobile_ppp: do not try to determine the local IP from the hostname.

Reported-by: Andrey Tikhomirov <vamp@vampik.ru>
Tested-by: Joerg Neikes <xenoist@midlandgate.de>
Closes: https://bugs.gentoo.org/653928
Signed-off-by: Joerg Neikes <xenoist@midlandgate.de>
Package-Manager: Portage-2.3.52, Repoman-2.3.12

### CODE REVIEW

**Comment by a17r** [comment]
Advice for future: you can force-push over remote branch after editing commit history. No need to always open new PRs. Especially to keep comments/reviews traceable.

**Comment by mgorny** [comment]
(in particular, get rid of the merge commit)

**Comment by mgorny** [comment]
In case you attempted to fix, you've only introduced more meaningless merge commits. Please read the git documentation on rebasing. https://git-scm.com/book is a good one.

**Comment by a17r** [comment]
Nope. `git pull --rebase upstream master`

**Pull request closed without merging**
