### PR TITLE
sys-boot/gnu-efi-3.0.0: Update the license of the gnu-efi.

### PR DESCRIPTION
**Pull request by YukiOhtsuka**
License of gnu-efi is the BSD license from version 3.0.0.
however, current license field of ebuild is GPL-2.
therefore, I fixed the license from GPL-2 to the BSD license.
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=584934

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by omasanori** [comment]
Version 3.0a, 3.0g and 3.0i are not BSD-licensed ones IIRC.
The license is, at least, mix of the 3-clause BSD License ("BSD") and the 2-clause BSD License ("BSD-2"). Thus, `LICENSE="BSD BSD-2"` is more precise, though.

**Comment by YukiOhtsuka** [comment]
I'm sorry.
Mistake had pull request has closed.

**Comment by omasanori** [comment]
no worry ;-)

**Comment by floppym** [comment]
Please collapse this into 1 commit.

**Comment by floppym** [comment]
Sorry, but I need some better supporting documentation on this. Please discuss on the bug report.

**Pull request closed without merging**
