### PR TITLE
dev-java/oracle-jre-bin-1.8.0.152: version bump

### PR DESCRIPTION
**Pull request by labre**
This is the last version released by Oracle. Sorry, I know, that I”m not a project member (nor developer). I just wanted to help out, because 144 could not be installed anymore by regular users, since it can’t be fetched from Oracle.

I made the mistake to not branch before my jdk bump commit, so there are some useless reverting and branching commits in this PR. I can cherry-pick them.

### CODE REVIEW

**Comment by chewi** [comment]
Many thanks for this, you saved me from a very tedious task.

**Comment by labre** [comment]
I think you had a typo. It should be trivial, not tedious.
I needed some practice with github before pulling JDK9. I somehow doubt, that it can be auto-assigned however. Could you do that? That would be PR #6008.
It has currently still some issues, so I”d appreciate any help. I can compile stuff though after a trivial fix.

**Comment by chewi** [comment]
Having to manually download all those large files is tedious for me.

We're not ready for Java 9 yet. I at least want to get rid of 7 first.

**Comment by labre** [comment]
Ah, ok. Sorry for misunderstanding you. Probably read too much fortune-mod-gentoo-dev.  I have a 100 MBit connection, so I usually don’t worry about download size. The JDK has even more files to download and you would do me a favor by freeing my master branch from its PR, which I accidentally used. PR #5998 
For some reason the existing ebuild had a wrong file name in it. solaris-amd64 instead of solaris-x64. I have a v144 file named like that, so actually it already should have had this name back then.

Are there any easy tasks, that I could help with, for ditching slot 7?

**Comment by chewi** [comment]
Hopefully closing the PR is sufficient, otherwise I'm not sure how to detach from your branch.

I thought the filename change was odd but I checked it out. I could see references to both names so they must have renamed it some time after the release. It wouldn't be the first time Oracle have pulled a weird stunt like that.

Thanks for the offer. There's not much left to be done at this point, I just need to see it through but I've been without my desktop for 3 weeks. Java team definitely does need more members though. We're in a bad situation at the moment because the traditional approach to packaging just isn't scaling any more so something radical is needed but I haven't had the time to put something together and no one else has stepped up.

**Comment by diotteo** [comment]
Hi, I'm trying to update my system and portage is asking me to download this (well, the jdk, but whatever).

On Oracle's website, the latest SE 8 release available is 144 (the one before that is 141). Did they change it back? I can't locate 152 anywhere.

**Comment by chewi** [comment]
Please read the text carefully and click the right link.

**Pull request closed without merging**
