### PR TITLE
app-emulation/cloud-init: bump to 22.1

### PR DESCRIPTION
**Pull request by t0b3**
app-emulation/cloud-init: bump to 22.1

see https://github.com/gentoo/gentoo/pull/23512

### CODE REVIEW

**Comment by prometheanfire** [comment]
out of curiosity, are you upstreaming your patches?  Also, was this tested?

**Comment by t0b3** [comment]
> out of curiosity, are you upstreaming your patches? Also, was this tested?

I just quickly rewrote the failing patches 4 and 5 from https://code.launchpad.net/~gilles-dartiguelongue/cloud-init/+git/cloud-init/+merge/358777 without testing them. Feel free to test and upstream ...

**Comment by holmanb** [comment]
@t0b3 - I see this was closed, are you planning on reopening?

If so, I can help with review. Minimally, the current dependencies will need some dusting off.

**Comment by holmanb** [comment]
I'm fairly certain we can strike `six` and `nose` - they are long gone. `dev-python/coverage` might need to be replaced with `dev-python/pytest-cov` as well - I'm not familiar enough to tell without digging in a little.

Since the patches carried are applied to the Gentoo specific part of the code base `
I'm fairly certain we can strike `six` and `nose` - they are long gone. `dev-python/coverage` might need to be replaced with `dev-python/pytest-cov` as well.

Since the patches carried are applied to the Gentoo specific part of the code base, it should be relatively painless.
`, it should be painless to upstream them. I can do that and update the -9999 ebuild later when they hit upstream.

**Comment by holmanb** [comment]
I see now, this is upstream already. I'll open a new bug && PR for the issue(s) I see. Sorry for the noise on this PR.

**Comment by t0b3** [comment]
... which is also great :+1:

**Pull request closed without merging**
