### PR TITLE
net-im/skypeforlinux: Bump version to 8.31.0.92

### PR DESCRIPTION
**Pull request by jvesely**

### CODE REVIEW

**Comment by jvesely** [comment]
@Amynka, @Zlogene, you handled previous bumps.
are you interested?

**Comment by mgorny** [comment]
@jvesely, do you want to co-maintain it? I'll merge it now but feel free to add yourself to metadata.xml next time or in a separate PR.

**Comment by jvesely** [comment]
> @jvesely, do you want to co-maintain it? I'll merge it now but feel free to add yourself to metadata.xml next time or in a separate PR.

Can I answer this in January? right now I need skype for meetings, but that might change in a few months.

I'll take a look at the reported failure. is it new in this version?.
I don't know much about ebuild rules, the updates are mostly "copy to a new name" when Skype notifies me about a new version.

**Comment by mgorny** [comment]
I suppose so, we aren't planning to stop accepting maintainers soon ;-).

It might be an old issue that has been unnoticed since since the path check is pretty new to Portage.

**Comment by jvesely** [comment]
Hi,
I assume the /usr/share/doc/skypeforlinux should really be in /opt/. However, the ebuild contains this:
>    dodoc usr/share/skypeforlinux/*.html
>    dodoc -r usr/share/doc/skypeforlinux/.
>    \# symlink required for the "Help->3rd Party Notes" menu entry  (otherwise frozen skype -> xdg-open)
>    dosym ${P} usr/share/doc/skypeforlinux

It no longer hangs but the menu entry is not working without the symlink.

the ebuild currently installs these files:
> /usr/share/doc/skypeforlinux
> /usr/share/doc/skypeforlinux-8.31.0.92
> /usr/share/doc/skypeforlinux-8.31.0.92/LICENSES.chromium.html
> /usr/share/doc/skypeforlinux-8.31.0.92/third-party_attributions.html

I guess the problem is that the symlink is not versioned?

**Comment by mgorny** [comment]
Ok, let's ignore it for now.

**Pull request closed without merging**
