### PR TITLE
dev-python/pymilter: Python interface to sendmail milter API (new package)

### PR DESCRIPTION
**Pull request by rseichter**
Python extension module to enable python scripts to attach to Sendmail's libmilter API (also used by Postfix), enabling filtering of messages as they arrive.

### CODE REVIEW

**Comment by rseichter** [comment]
As discussed with @mgorny dev-python/pymilter has been made available via [GURU](https://wiki.gentoo.org/wiki/Project:GURU).

**Comment by monsieurp** [comment]
@rseichter: Cool! In this case, feel free to close this PR :-)

**Comment by rseichter** [comment]
@monsieurp : This pull request has now been open for a month. If no changes are required, it would be nice to have this merged. 😉

**Comment by rseichter** [comment]
@monsieurp : I should probably also mention that pymilter is a requirement for dkimpy-milter. @orlitzky and I are working with the author to improve OpenRC and systemd support, and I want to submit dkimpy-milter as a new package when the requirements are available in the Gentoo tree.

**Comment by Whissi** [comment]
Updated to v1.0.4.

Feel free to ping me in future for mail server related packages.

**Pull request closed without merging**
