### PR TITLE
Added Intel CET features to llvm

### PR DESCRIPTION
**Pull request by StormBytePP**
This PR adds necessary changes to ebuilds to support Intel CET features in LLVM

Closes: https://bugs.gentoo.org/908600

### CODE REVIEW

**Comment by thesamesam** [comment]
Sorry, this kept falling down the list. Could you rebase?

Also, we'll need to do some wiring in clang-common but I can handle that. Do clang and llvm themselves need anything for this?

**Comment by StormBytePP** [comment]
> Sorry, this kept falling down the list. Could you rebase?
> 
> Also, we'll need to do some wiring in clang-common but I can handle that. Do clang, llvm, and lld themselves need anything for this?

Allow a couple of days please for rebasing the content to be able to merge it :)

On the other hand, the reason that the other components have references to CET is that I've inspected Cmake's build for each package (with ccmake) once configured and found that the variable is referenced internally. I don't know if it is really used to change code's compile but for sure it is referenced inside.

**Comment by StormBytePP** [comment]
@mgorny rebased and reopened, hope you find it useful :)

**Comment by thesamesam** [comment]
One more rebase and one-commit-per-package please? 👼

**Comment by StormBytePP** [comment]
I've made the changes @thesamesam requested and updated to newer ebuilds

**Comment by StormBytePP** [comment]
Do you want me to merge all the commits into just 2 (one for compiler-rt and one for llvm-libunwind)?

**Comment by mgorny** [comment]
Yes, please. One commit per package, with descriptive commit messages, and only for 18+.

**Comment by mgorny** [comment]
(specifically newest 18.1.2 and 19.0.0.9999)

**Comment by StormBytePP** [comment]
Ok, done, ready for review

**Comment by mgorny** [comment]
Ok, I'm thoroughly confused as what is the purpose of this pull request.

FWICS `*_ENABLE_CET` only appends CFLAGS when building libunwind/compiler-rt. This doesn't seem to be the same thing as `USE=cet` on GCC, and I dare say this is pretty much useless, unless we want to add `USE=cet` to every single package in Gentoo (and we don't).

`COMPILER_RT_USE_LLVM_UNWINDER` is used only when building sanitizers, so it doesn't do anything in `sys-libs/compiler-rt`.

**Comment by StormBytePP** [comment]
I've reviewed what you say and you are probably right with a little note: In case of compiler-rt, `COMPILER_RT_ENABLE_CET` enables a fatal error if CET is enabled but compiler does not have support for it (in line 304 of `CMakeLists.txt`). In case this is not needed/wanted then this can be closed (along with the bugreport) and just put the C{XX}FLAGS globally.

Regarding llvm-libunwind, well I think it is already handled as I tested without it and it avoids gcc_s entirelly.

**Comment by mgorny** [comment]
Yeah, this is not a valid addition.

**Pull request closed without merging**
