### PR TITLE
dev-lang/rust-bin: restore keywords for mips

### PR DESCRIPTION
**Pull request by matoro**
Now that dev-lang/rust has crossdev support, we can build our own binaries for mips in the same fashion as sparc.  Here is the first round of binaries for 1.75.0.  Tested and confirmed that the binaries work on real hardware.

For posterity, here is how these were generated:
```
emerge -v1 app-eselect/eselect-repository sys-devel/crossdev
eselect repository create crossdev-mips-unknown-linux-gnu
eselect repository create crossdev-mipsel-unknown-linux-gnu
eselect repository create crossdev-mips64-unknown-linux-gnu
eselect repository create crossdev-mips64el-unknown-linux-gnu
rm -v /etc/portage/package.accept_keywords
crossdev --abis o32 --target mips-unknown-linux-gnu
crossdev --abis o32 --target mipsel-unknown-linux-gnu
crossdev --abis n64 --target mips64-unknown-linux-gnu
crossdev --abis n64 --target mips64el-unknown-linux-gnu
PORTAGE_CONFIGROOT=/usr/mips-unknown-linux-gnu eselect profile set default/linux/mips/17.0/o32
PORTAGE_CONFIGROOT=/usr/mipsel-unknown-linux-gnu eselect profile set default/linux/mips/17.0/mipsel/o32
PORTAGE_CONFIGROOT=/usr/mips64-unknown-linux-gnu eselect profile set default/linux/mips/17.0/n64
PORTAGE_CONFIGROOT=/usr/mips64el-unknown-linux-gnu eselect profile set default/linux/mips/17.0/mipsel/n64
LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mips-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'
LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mipsel-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'
LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mips64-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'
LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mips64el-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'
ls -l /usr/mips*/usr/lib/rust/*/dist/*.tar.xz
```

### CODE REVIEW

**Comment by vidraj** [comment]
> LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mips-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'

It seems that the Rust build system uses the host CFLAGS for the build bootstrap as well – when building on amd64 for a non-amd64 target with `-mcpu` in the CFLAGS, the build first says `warning: cc: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead` and then fails, because the given value of `-mcpu` is not known on amd64.

**Comment by matoro** [comment]
> > LLVM_TARGETS="X86" USE="dist system-bootstrap" MAKEOPTS="$(portageq envvar MAKEOPTS)" FEATURES="-parallel-fetch" mips-unknown-linux-gnu-emerge --autounmask=y --autounmask-continue=y -v1 '~dev-lang/rust-1.75.0' '~virtual/rust-1.75.0'
> 
> It seems that the Rust build system uses the host CFLAGS for the build bootstrap as well – when building on amd64 for a non-amd64 target with `-mcpu` in the CFLAGS, the build first says `warning: cc: warning: '-mcpu=' is deprecated; use '-mtune=' or '-march=' instead` and then fails, because the given value of `-mcpu` is not known on amd64.

This was already addressed in the crossdev support item:  https://github.com/gentoo/gentoo/pull/35246/files#diff-9bdb360d09105eaaae699c535b9970bf9d9a3118993350d9dbeeac433cefcc5fR396-R408

Are you targeting 1.74.1 or later, and is your portage repo synced?

**Comment by vidraj** [comment]
> Are you targeting 1.74.1 or later, and is your portage repo synced?

I'm using dev-lang/rust-1.75.0-r1 and I've synced yesterday. The issue showed up when cross-compiling for powerpc-gentoo-linux-musl using crossdev.

**Comment by matoro** [comment]
> > Are you targeting 1.74.1 or later, and is your portage repo synced?
> 
> I'm using dev-lang/rust-1.75.0-r1 and I've synced yesterday. The issue showed up when cross-compiling for powerpc-gentoo-linux-musl using crossdev.

Can you dump the contents of your `config.toml`?  Does it have `CMAKE_C_FLAGS` set?

**Comment by vidraj** [comment]
> Can you dump the contents of your `config.toml`? Does it have `CMAKE_C_FLAGS` set?

There are multiple `config.toml`s in the workdir, but none set that variable. None of them contain the contents of my CFLAGS either.

**Comment by vidraj** [comment]
Also, the file references `powerpc-unknown-linux-gnu` in multiple places, which seems weird, since the host and target are both `-musl` and only the build is `-gnu`. But maybe that's OK?

**Comment by matoro** [comment]
> Also, the file references `powerpc-unknown-linux-gnu` in multiple places, which seems weird, since the host and target are both `-musl` and only the build is `-gnu`. But maybe that's OK?

No, this would appear to be broken because the eclass does not have wiring up for `powerpc-unknown-linux-musl`:  https://github.com/gentoo/gentoo/blob/master/eclass/rust-toolchain.eclass#L37-L55

We only appear to have support for musl on x86_64 and aarch64.  Try manually editing `rust-toolchain.eclass` and see if it helps.

**Comment by vidraj** [comment]
I tried that, now I'm getting this error: `when targeting MUSL either the rust.musl-root option or the target.$TARGET.musl-root option must be specified in config.toml`

I have to somehow sneak the line `musl-root = "/usr/powerpc-gentoo-linux-musl/usr"` into config.toml. It seems that [line 570](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L570-L574) in the ebuild is already supposed to be doing that?

Also, [line 542](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L542) seems fishy?

**Comment by matoro** [comment]
> I tried that, now I'm getting this error: `when targeting MUSL either the rust.musl-root option or the target.$TARGET.musl-root option must be specified in config.toml`
> 
> I have to somehow sneak the line `musl-root = "/usr/powerpc-gentoo-linux-musl/usr"` into config.toml. It seems that [line 570](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L570-L574) in the ebuild is already supposed to be doing that?
> 
> Also, [line 542](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L542) seems fishy?
> 
> EDIT: Oh, now I see that [they are commented out](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L517). I'll add the relevant stuff to the block above.

I don't think that will work, because the stuff under `I_KNOW_WHAT_I_AM_DOING_CROSS` is not my work - it's separate work from [bug 679878](https://bugs.gentoo.org/show_bug.cgi?id=679878) which is for `CBUILD == CHOST != CTARGET(s)`, whereas what we want is `CBUILD != CHOST == CTARGET`.

It's possible that my crossdev compat simply doesn't work with musl targets; I did not test it.

**Comment by vidraj** [comment]
I see.

I added `musl-root = "$($(tc-getCC) -print-sysroot)/usr"` after [line 504](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L504) and now it's compiling.

Regarding the original CFLAGS issue I raised in the first comment.
temp/environment contains the following:
```
declare -x BUILD_CFLAGS="-O2 -ggdb -march=znver1 -pipe"
declare -x BUILD_CPPFLAGS=""
declare -x BUILD_CXXFLAGS="-O2 -ggdb -march=znver1 -pipe"
[...]
declare -x CFLAGS="-O2 -pipe -fno-stack-protector"
declare -x CFLAGS_default
declare -x CFLAGS_powerpc_unknown_linux_musl=""
```

The BUILD_CFLAGS and CFLAGS correspond to CFLAGS on the build and host, respectively. The fact that `CFLAGS_powerpc_unknown_linux_musl` are empty is weird, but I don't know whether it matters.

temp/build.log contains the following:
```
CC_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-gcc"
CFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC"]
CXX_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-g++"
CXXFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-pipe", "-fno-stack-protector"]
AR_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-ar"
CC_x86_64-unknown-linux-gnu = "cc"
CFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe", "-fno-stack-protector"]
CXX_x86_64-unknown-linux-gnu = "c++"
CXXFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe", "-fno-stack-protector"]
AR_x86_64-unknown-linux-gnu = "ar"
```

So `-O2` is missing completely, `CFLAGS_powerpc-unknown-linux-musl` are probably based on the empty flags from `environment` (as opposed to `CXXFLAGS_powerpc-unknown-linux-musl`, which seem correct) and `CFLAGS_x86_64-unknown-linux-gnu` are based on the host flags, not build ones.

Anyway, I apologize for hijacking this pull request for unrelated issues. O:-) Should I file bugs both for the gnu vs. musl mismatch and for the build vs. host CFLAGS issue, so that we can continue the discussion there? This is probably not the best place for it.

And thank you for your guidance, I really appreciate it.

**Comment by matoro** [comment]
> I see.
> 
> I added `musl-root = "$($(tc-getCC) -print-sysroot)/usr"` after [line 504](https://github.com/gentoo/gentoo/blob/55cd1bfe864726fe3630c8fb8a3bc6596c86de80/dev-lang/rust/rust-1.75.0-r1.ebuild#L504) and now it's compiling.
> 
> Regarding the original CFLAGS issue I raised in the first comment. temp/environment contains the following:
> 
> ```
> declare -x BUILD_CFLAGS="-O2 -ggdb -march=znver1 -pipe"
> declare -x BUILD_CPPFLAGS=""
> declare -x BUILD_CXXFLAGS="-O2 -ggdb -march=znver1 -pipe"
> [...]
> declare -x CFLAGS="-O2 -pipe -fno-stack-protector"
> declare -x CFLAGS_default
> declare -x CFLAGS_powerpc_unknown_linux_musl=""
> ```
> 
> The BUILD_CFLAGS and CFLAGS correspond to CFLAGS on the build and host, respectively. The fact that `CFLAGS_powerpc_unknown_linux_musl` are empty is weird, but I don't know whether it matters.
> 
> temp/build.log contains the following:
> 
> ```
> CC_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-gcc"
> CFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC"]
> CXX_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-g++"
> CXXFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-pipe", "-fno-stack-protector"]
> AR_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-ar"
> CC_x86_64-unknown-linux-gnu = "cc"
> CFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe", "-fno-stack-protector"]
> CXX_x86_64-unknown-linux-gnu = "c++"
> CXXFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe", "-fno-stack-protector"]
> AR_x86_64-unknown-linux-gnu = "ar"
> ```
> 
> So `-O2` is missing completely, `CFLAGS_powerpc-unknown-linux-musl` are probably based on the empty flags from `environment` (as opposed to `CXXFLAGS_powerpc-unknown-linux-musl`, which seem correct) and `CFLAGS_x86_64-unknown-linux-gnu` are based on the host flags, not build ones.
> 
> Anyway, I apologize for hijacking this pull request for unrelated issues. O:-) Should I file bugs both for the gnu vs. musl mismatch and for the build vs. host CFLAGS issue, so that we can continue the discussion there? This is probably not the best place for it.
> 
> And thank you for your guidance, I really appreciate it.

First one should have a bug.

Second one I think is behaving correctly actually, we purposely leave `CFLAGS` empty under cross because we can't assume any flag is valid for both host and target architecture.  What you're seeing is probably what rust build system defaults to.

**Comment by vidraj** [comment]
> Second one I think is behaving correctly actually, we purposely leave `CFLAGS` empty under cross because we can't assume any flag is valid for both host and target architecture. What you're seeing is probably what rust build system defaults to.

It's not, because when I remove `-fno-stack-protector` from the host `CFLAGS`, the flags in build.log become
```
CC_x86_64-unknown-linux-gnu = "cc"
CFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe"]
CXX_x86_64-unknown-linux-gnu = "c++"
CXXFLAGS_x86_64-unknown-linux-gnu = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-m64", "-pipe"]
AR_x86_64-unknown-linux-gnu = "ar"
CC_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-gcc"
CFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC"]
CXX_powerpc-unknown-linux-musl = "powerpc-gentoo-linux-musl-g++"
CXXFLAGS_powerpc-unknown-linux-musl = ["-ffunction-sections", "-fdata-sections", "-fPIC", "-pipe"]
```

(note the different order of printouts when comparing with the previous post)

Therefore, `CXXFLAGS_powerpc-unknown-linux-musl`, `CFLAGS_x86_64-unknown-linux-gnu`  and `CXXFLAGS_x86_64-unknown-linux-gnu` are taken from the host (powerpc) `CFLAGS`/`CXXFLAGS`, while `CFLAGS_powerpc-unknown-linux-musl` are default/empty.

**Comment by arthurzam** [comment]
I've repeated the instructions here, created tarballs and updated the ebuild for rust-bin-1.77.1. @matoro tested and it built `maturin` successfully for him on mips.

I think we can close this PR now?

**Comment by matoro** [comment]
> I've repeated the instructions here, created tarballs and updated the ebuild for rust-bin-1.77.1. @matoro tested and it built `maturin` successfully for him on mips.
> 
> I think we can close this PR now?

Yep, closing as superseded.

**Pull request closed without merging**
