### PR TITLE
www-client/google-chrome: add optional supports for emoji

### PR DESCRIPTION
**Pull request by scardracs**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by stha09** [comment]
Optional runtime dependencies are not allowed in ::gentoo, see https://projects.gentoo.org/qa/policy-guide/dependencies.html

**Comment by Flowdalic** [comment]
If you add such an 'emoji' use flag to chrome, then, as consequence, you would need it to most GUI applications. This is clearly not viable. In general, I believe, Gentoo users are trusted to know which font packages to install to get the best emoji support. Even though, we could probably do a better job documenting it. That said, and keep in mind that it is the decision of the package maintainer, I wonder if `optfeature media-fonts/noto-emoji` in the chrome ebuild wouldn't be a bad idea.

**Comment by scardracs** [comment]
> If you add such an 'emoji' use flag to chrome, then, as consequence, you would need it to most GUI applications. This is clearly not viable. In general, I believe, Gentoo users are trusted to know which font packages to install to get the best emoji support. Even though, we could probably do a better job documenting it. That said, and keep in mind that it is the decision of the package maintainer, I wonder if `optfeature media-fonts/noto-emoji` in the chrome ebuild wouldn't be a bad idea.

Yeah, that would be a better solution. I was adding it as I saw there are some packages that already have that IUSE

**Comment by floppym** [comment]
We won't add a USE flag for this.

We used to output a message about installing various fonts, but I never liked it and removed it in 17a656b0a47a95521b49c2ed968e5a7cff508e93. I don't think it makes sense to output a message for a web browser when fonts affect every GUI app on the system.

**Pull request closed without merging**
