### PR TITLE
dev-util/diff-cover: add python3_12

### PR DESCRIPTION
**Pull request by Tatsh**
Trivial change.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
The current ebuild fails quite drastically, e.g.

```
_______________________________________________________________________ ERROR at setup of TestSimpleCommandTestCase.test_run_simple_success _______________________________________________________________________
file /var/tmp/portage/dev-util/diff-cover-6.5.0-r1/work/diff_cover-6.5.0/tests/test_violations_reporter.py, line 1743
      def test_run_simple_success(self):
file /var/tmp/portage/dev-util/diff-cover-6.5.0-r1/work/diff_cover-6.5.0/tests/test_violations_reporter.py, line 39
  @pytest.fixture(autouse=True)
  def patch_so_all_files_exist(mocker, request):
E       fixture 'mocker' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, fake_process, fp, git_repo, make_git_repo, make_repo, monkeypatch, patch_so_all_files_exist, patcher, process_patcher, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, repo, testrun_uid, tmp_home_dir, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id
>       use 'pytest --fixtures [testpath]' for help on them.
```

**Comment by eli-schwartz** [comment]
Please do more than just rebase onto the revbump -- figure out how to actually pass the tests. Thanks.

**Comment by Tatsh** [comment]
The problem is that the dev/test dependencies are too new and the assertions are too specific to string output from said dependencies.

I was able to reproduce 4 of the failing tests with a local copy of diff-cover 6.5.0 after upgrading flake8 in the virtualenv (using Python 3.10):

```shell
pip install flake8==5.0.4
```

Failing tests:

```
FAILED tests/test_integration.py::TestDiffQualityIntegration::test_fail_under_console - assert 0 == 1
FAILED tests/test_integration.py::TestDiffQualityIntegration::test_fail_under_pass_console - AssertionError: assert '------------...-------------' == '------------...-------------'
FAILED tests/test_integration.py::TestDiffQualityIntegration::test_added_file_pyflakes_console - AssertionError: assert '------------...-------------' == '------------...-------------'
FAILED tests/test_integration.py::TestDiffQualityIntegration::test_added_file_pyflakes_console_two_files - AssertionError: assert '------------...-------------' == '------------...-------------'
```

I was able to reproduce the HTML mismatches by updating packages and dependencies, and at least one sub-dependency of something in `pyproject.toml` is what causes the mismatches.


Then I realised in version 6.5.1, the HTML fixtures were updated:

https://github.com/Bachmann1234/diff_cover/commit/bd39c1c410721aac5a73e38d8f989df0261cdbb6

I tried tests with a 6.5.1 ebuild but unfortunately newer flake8 is still an issue for 6.5.1.

Our best bet is to update to 9.2.0 but that still has one error only in Portage environment and I am not sure of the cause. It seems like it most likely is sandbox related:

```
TestFlake8QualityReporterTest.test_file_does_not_exist _____________________________________________________________________________

self = <tests.test_violations_reporter.TestFlake8QualityReporterTest object at 0x7fd9b40e6ef0>

    @pytest.mark.disable_all_files_exist
    def test_file_does_not_exist(self):
        quality = QualityReporter(flake8_driver)
        file_paths = ["ajshdjlasdhajksdh.py"]
        # Expect that we get no results because that file does not exist
        for path in file_paths:
>           result = quality.violations(path)

file_paths = ['ajshdjlasdhajksdh.py']
path       = 'ajshdjlasdhajksdh.py'
quality    = <diff_cover.violationsreporters.base.QualityReporter object at 0x7fd9b297df00>
self       = <tests.test_violations_reporter.TestFlake8QualityReporterTest object at 0x7fd9b40e6ef0>

tests/test_violations_reporter.py:1170:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <diff_cover.violationsreporters.base.QualityReporter object at 0x7fd9b297df00>, src_path = 'ajshdjlasdhajksdh.py'

    def violations(self, src_path):
        """
        Return a list of Violations recorded in `src_path`.
        """
        if not any(src_path.endswith(ext) for ext in self.driver.supported_extensions):
            return []
        if src_path not in self.violations_dict:
            if self.reports:
                self.violations_dict = self.driver.parse_reports(self.reports)
            else:
                if self.driver_tool_installed is None:
                    self.driver_tool_installed = self.driver.installed()
                if not self.driver_tool_installed:
>                   raise OSError(f"{self.driver.name} is not installed")
E                   OSError: flake8 is not installed

self       = <diff_cover.violationsreporters.base.QualityReporter object at 0x7fd9b297df00>
src_path   = 'ajshdjlasdhajksdh.py'

diff_cover/violationsreporters/base.py:160: OSError
============================================================================================ short test summary info ============================================================================================
FAILED tests/test_violations_reporter.py::TestFlake8QualityReporterTest::test_file_does_not_exist - OSError: flake8 is not installed
```

For 9.2.0 tests to work up to this point, these test deps must be added:

- flake8
- pylint
- pytest-datadir

**Comment by Tatsh** [comment]
After doing some modification to print out the error, the test that fails does call flake8 and has no issue finding it since it is in `PATH`. The problem is the project's own .flake8 file is stopping flake8 from working even if only invoked with `flake --version`. `flake8`'s output:

```
@@ Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.12/flake8", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File "/usr/lib/python3.12/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File "/usr/lib/python3.12/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File "/usr/lib/python3.12/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
                                 ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flake8/options/parse_args.py", line 53, in parse_args
    opts = aggregator.aggregate_options(option_manager, cfg, cfg_dir, rest)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flake8/options/aggregator.py", line 30, in aggregate_options
    parsed_config = config.parse_config(manager, cfg, cfg_dir)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/flake8/options/config.py", line 131, in parse_config
    raise ValueError(
ValueError: Error code '#' supplied to 'ignore' option does not match '^[A-Z]{1,3}[0-9]{0,3}$'
```

The config:

```
[flake8]
max-line-length=100
select=
    C901,  # flake8-mccabe
    E,  # flake8-pycodestyle
    F,  # flake8-pyflakes
    W,  # flake8-pycodestyle
ignore =
    W503,E203,  # conflict with black formatter
per-file-ignores =
    # supression for __init__
    diff_cover/tests/*: E501
    diff_cover/tests/fixtures/*: E,F,W
```

I think it is complaining about any of the lines with comments because upon removing them the test passes.

I added a sed command to remove the comments. Simpler alternative is to remove the file altogether as it is not needed for the tests.

**Pull request closed without merging**
