### PR TITLE
eclass/rust-toolchain.eclass: add powerpc*musl support

### PR DESCRIPTION
**Pull request by pkubaj**
Also adjust indentation.

### CODE REVIEW

**Comment by pkubaj** [comment]
cc @gyakovlev as the only member of the rust team

**Comment by pkubaj** [comment]
@thesamesam 
CC

**Comment by arthurzam** [comment]
Missing sign-off

**Comment by thesamesam** [comment]
diff with `-w`:
```

-               powerpc64le*) echo powerpc64le-unknown-linux-gnu;;
-               powerpc64*)   echo powerpc64-unknown-linux-gnu;;
-               powerpc*)     echo powerpc-unknown-linux-gnu;;
+               powerpc64le*gnu)  echo powerpc64le-unknown-linux-gnu;;
+               powerpc64le*musl) echo powerpc64le-unknown-linux-musl;;
+               powerpc64*gnu)    echo powerpc64-unknown-linux-gnu;;
+               powerpc64*musl)   echo powerpc64-unknown-linux-musl;;
+               powerpc*gnu)      echo powerpc-unknown-linux-gnu;;
+               powerpc*musl)     echo powerpc-unknown-linux-musl;;
```

lgtm, thanks

**Pull request closed without merging**
