### PR TITLE
sys-libs/glibc: Repair devpts checks within containers

### PR DESCRIPTION
**Pull request by kakra**

### CODE REVIEW

**Comment by palica** [comment]
This is not going to fix the issue for nested containers. 

```
first-container:~ # cat /proc/self/gid_map 
         0     165536     200000
first-container:~ # mount |grep dev/pts
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=165541,mode=620,ptmxmode=666,max=1024)

```
```
second-container ~ # cat /proc/self/gid_map 
         0      65536     131072
second-container ~ # mount|grep dev/pts
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=231077,mode=620,ptmxmode=666,max=1024)
```

the second container is nested inside first-container, for the second container the gid number is 
offset_of_first_container + offset_of_second_container + 5 = 165536+65536+5 = 231077

**Comment by kakra** [comment]
Is there even a way to properly fix this from user space? Maybe the kernel should just properly map those info back into the container? Then, why doesn't it do it in the first place?

OTOH, this also shows that the check should probably be downgraded to a warning when running within containers. I could imagine using a variable in `make.conf` to indicate whether you're aware of the issue and only warn instead of dying in the ebuild. Maybe a (masked) useflag could also do.

**Comment by palica** [comment]
The question really is - is this test still needed?

 used this code to test the grantpt function on a glibc ebuild with disabled devpts check but no suid:

```
#define _XOPEN_SOURCE 600
#include <stdlib.h>
#include <stdio.h>
#include <fcntl.h>
#include <errno.h>

int main(void)
{
int fdm;
int rc;

// Display /dev/pts
system("ls -l /dev/pts");

fdm = posix_openpt(O_RDWR);
if (fdm < 0)
{
fprintf(stderr, "Error %d on posix_openpt()\n", errno);
return 1;
}

rc = grantpt(fdm);
if (rc != 0)
{
fprintf(stderr, "Error %d on grantpt()\n", errno);
return 1;
}

rc = unlockpt(fdm);
if (rc != 0)
{
fprintf(stderr, "Error %d on unlockpt()\n", errno);
return 1;
}

// Display the changes in /dev/pts
system("ls -l /dev/pts");

printf("The slave side is named : %s\n", ptsname(fdm));

return 0;
} // main
```
Reference: http://rachid.koucha.free.fr/tech_corner/pty_pdip.html

After compilation I run the code with these results:

```
palica@lmo-01 ~ $ gcc test_grantpt.c -o test_grantpt
palica@lmo-01 ~ $ ./test_grantpt
total 0
crw-rw-rw- 1 root root 5, 2 Oct  1 20:32 ptmx
total 0
crw--w---- 1 palica tty  136, 0 Oct 10 09:44 0
crw-rw-rw- 1 root   root   5, 2 Oct  1 20:32 ptmx
The slave side is named : /dev/pts/0
palica@lmo-01 ~ $
```

**Comment by kakra** [comment]
I'll consider this closed as a patch will appear in one of the next ebuilds.

**Pull request closed without merging**
