### PR TITLE
Dev python/spyder: version bump 4.1.1

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
This version bumps spyder and some dependencies

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
@juippis could you take a look at this please, it's mostly minor version bumps (no new packages this time xD ) so I think it should be mostly fine. Let me know if you find any issues.

**Comment by juippis** [comment]
Didn't even see your comment. I've been "testing" this for 2 days (qtwebengine..)

**Comment by AndrewAmmerlaan** [comment]
> Please don't use `git mv` to bump to a new version, but rather one commit to update version and 2nd commit to remove old files.
> 
> ```
>  * ERROR: dev-python/qdarkstyle-2.8.1::testworld failed (compile phase):
>  *   doc/conf.py not found, distutils_enable_sphinx call wrong
> ```

Hmm, upstream seems to have renamed the `doc` directory to `docs`. Sorry about that, I forgot to test USE="doc", I have now added USE="doc" to my test environment so I won't forget in the future.

**Comment by juippis** [comment]
Without testing, I hope this is enough:
c8f06ea53d6fea360fc156620610b943b86a7ece

**Comment by AndrewAmmerlaan** [comment]
> Without testing, I hope this is enough:
> [c8f06ea](https://github.com/gentoo/gentoo/commit/c8f06ea53d6fea360fc156620610b943b86a7ece)

Works for me :+1: Thank you

**Pull request closed without merging**
