### PR TITLE
media-sound/gtick: Version bump to 0.5.5

### PR DESCRIPTION
**Pull request by puleglot**

### CODE REVIEW

**Comment by juippis** [comment]
media-sound/gtick
  DroppedStableKeywords: commit d20986ab6a2 (or later) dropped stable keywords: [ amd64, x86 ]
  UnstableOnly: for arches: [ amd64, ppc, sparc, x86 ], all versions are unstable: [ 0.5.5 ]

**Comment by puleglot** [comment]
> DroppedStableKeywords: commit d20986ab6a2 (or later) dropped stable keywords: [ amd64, x86 ]
Ooops.. For some reason I was sure that it doesn't have stable keywords. =/

**Comment by juippis** [comment]
Want it to be reverted, or do you think there are no stable users anyway?

**Comment by puleglot** [comment]
Lets revert the second commit. Thanks!

**Pull request closed without merging**
