### PR TITLE
Mask proton-ge packages in multilib profiles

### PR DESCRIPTION
**Pull request by CHN-beta**

### CODE REVIEW

**Comment by thesamesam** [comment]
We don't normally mask stuff in ::gentoo for overlays, but I appreciate there's some precedent of doing this for Steam and stuff.

@gentoo/games?

**Comment by chewi** [comment]
I'm pretty sure package.mask works in overlays. Why do we need this here?

**Comment by ionenwks** [comment]
> I'm pretty sure package.mask works in overlays. Why do we need this here?

Never experimented but pretty sure can't for profile-specific masks -- not that I'm fond at the idea of adding them because of it.

If this is mostly due to pkgcheck noise, you can enable/disable checking only specific profiles.

**Comment by chewi** [comment]
> If this is mostly due to pkgcheck noise, you can enable/disable checking only specific profiles.

It must be. Running Steam on non-multilib is a total non-starter. Even if Steam does go 64-bit, there are still plenty of games that aren't.

**Pull request closed without merging**
