### PR TITLE
eutils -> epunt_cxx... for sound pkgs

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by aballier** [comment]
add a repoman warning for missing inherit when calling those functions and useless inherit when not calling it like the autotools.eclass/user.eclass ones

it'd be much easier to see what requires a change

**Comment by aballier** [comment]
cant find the button to approve that but that's ok ofc

**Comment by mgorny** [comment]
@aballier, i actually wanted to but the repoman code is horrible. I'm not even sure if any inherit checks are performed by default these days, and what's the relation with 'experimental inherit checks'.

The approved button is on 'files changed' tab ;-P.

**Comment by mgorny** [comment]
Merged.

**Pull request closed without merging**
