### PR TITLE
app-editors/kakoune: new ebuild

### PR DESCRIPTION
**Pull request by Hummer12007**
This PR adds a new ebuild: the kakoune text editor.

@gentoo/proxy-maint

### CODE REVIEW

**Comment by rindeal** [comment]
- test phase is missing
- `emake` in `src_compile()` requires `debug=no` argument (might look like `debug=$(usex debug)`), maybe even `pedantic=no`
- Makefile requires some patching 
  - `-g` and `-O3` in CXXFLAGS
  - LIBS and includes should probably be handled via `pkg-config` (`NCURSESW_INCLUDE` definitely)

**Comment by Hummer12007** [comment]
Addressed issues raised by @rindeal, unable to access the QA report.

**Comment by rindeal** [comment]
- `virtual/pkgconfig` is build-time only dep
- you forgot to add the patch and rerun `repoman manifest`

**Comment by Hummer12007** [comment]
Moved dep, added the patch and rebased everything.

**Comment by rindeal** [comment]
Although `CXXFLAGS += -g` makes sense do not add flags which are not necessary for the build.

Also `sed` might be a better bet in this case as it's often more future-proof.

I'd handle it like this:
```ebuild
inherit flag-o-matic toolchain-funcs

src_prepare() {
    eapply_user

	local sed_args=(
		# delete hardcoded flags
		-e 's|-O3||g'
		-e 's|-g||g'
		
		# delete hardcoded ncursesw -I flags (using pkg-config in src_configure() instead)
		-e '\|NCURSESW_INCLUDE *\?=|d'
		-e 's|-I\$\(NCURSESW_INCLUDE\)||g'
	)
	sed -i -r "${sed_args[@]}" 'src/Makefile' || die
}

src_compile() {
	append-cppflags $($(tc-getPKG_CONFIG) --cflags ncursesw)
	...
}
```

**Comment by rindeal** [comment]
In case you will go the way with patching, replace `src_prepare()` with `PATCHES=( "${FILESDIR}/${PN}-makefile.patch" )`

**Comment by Hummer12007** [comment]
I've moved appending cppflags to src_configure, removed the NCURSESW_INCLUDE entries from the resulting Makefile, replaced the src_prepare() function, but kept the CXXFLAGS += -g (as I was told, that it's fine).

**Comment by idella** [comment]
that would be an underlying qa break, you need do a new --rebase to try clear it

**Comment by idella** [comment]
On a runtest this is found to "disrespect CXX", meaning g++ is called directly.
You will need to patch the build system in order to have it called being set by a function, called indirectly. The fix will need be put to upstream.

```
make: Entering directory '/mnt/gen2/TmpDir/portage/app-editors/kakoune-2016.05.05/work/kakoune-2016.05.05/src'
g++  -D_GNU_SOURCE -I/usr/include/ncursesw -march=amdfam10 -O2 -pipe -msahf -mpopcnt -mlzcnt --param l1-cache-size=64 --param 	l1-cache-line-size=64 --param l2-cache-size=512 -frecord-gcc-switches -pedantic -std=gnu++11 -Wall -Wno-reorder -Wno-sign-compare -Wno-address -MD -MP -MF .buffer_manager.opt.d -c -o .buffer_manager.opt.o buffer_manager.cc

```

**Comment by rindeal** [comment]
> On a runtest this is found to "disrespect CXX", meaning g++ is called directly.

The makefile is very simple:
```Makefile
kak : $(objects)
    $(CXX) $(LDFLAGS) $(CXXFLAGS) $(objects) $(LIBS) -o $@

-include $(deps)

.%$(suffix).o: %.cc
    $(CXX) $(CPPFLAGS) $(CXXFLAGS) -MD -MP -MF $(addprefix ., $(<:.cc=$(suffix).d)) -c -o $@ $<
```

and as you can see, it respects everything.

**Comment by idella** [comment]
further discussion / runtesting vis URC. Passes all required now

**Pull request closed without merging**
