### PR TITLE
mail-client/roundcube: version bump to 1.1.5

### PR DESCRIPTION
**Pull request by Philippe23**
Almost the same as the files attached to https://bugs.gentoo.org/580746, except for an update to the copyright line and masked all arches as requested by repoman.

1.1.5 ebuild is essentially a copy of 1.1.4 with the following changes:
 * Changed SRC_URI to point to github as the upstream project no longer uses sourceforge.  NOTE: mirror://github/ url format didn't work, so for now it is using the https://github.com/ url.
 * Updated copyright line to 2016 at repoman's urging.

Gentoo-bug: https://bugs.gentoo.org/580746

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by Philippe23** [comment]
That's nice, QA-bot, but I'm not clear on how those relate to this webapp ebuild....

**Comment by Philippe23** [comment]
Forgot to ping @gentoo/webapps & @titanofold.

**Comment by rindeal** [comment]
>That's nice, QA-bot, but I'm not clear on how those relate to this webapp ebuild....

Rule of thumb: don't bother with QA-bot messages related to "Issues persisted from underlying repository state"

**Comment by titanofold** [comment]
@Philippe23 thanks for working on this. The changes you've made have been integrated into the 1.2.0 ebuild.

Closing this PR without merging as it's superseded by 1.2.0.

**Pull request closed without merging**
