### PR TITLE
sci-geosciences/josm: Version bump and repair svn ebuild

### PR DESCRIPTION
**Pull request by henning-schild**
This commit repairs the svn ebuild to deal with the changed icon paths.
It also adds one ebuild for the current "tested" revision.

Closes: https://bugs.gentoo.org/628944
Closes: https://bugs.gentoo.org/648838
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
I regularly use this editor and also contribute to gentoo a bit, would take this one as proxy maintainer.

**Comment by henning-schild** [comment]
Adding a -bin ebuild to maybe replace the one where we did build it ourselfs. Building would be complicated and there might not be much value in doing that.

**Comment by henning-schild** [comment]
@casta #9771

**Comment by henning-schild** [comment]
The last commit switches the ebuild from upstream svn to fetching a .zip from the github mirror. Using that .zip gentoo QA does not complain anymore "VisibleVcsPkg" but the build will still fetch libs with svn.

So we could switch to that pattern and add svn as a build-dep, but the ebuild would always contain the mirror hash. The -bin looks much cleaner to me and solves the problem that the build steps pulls in libs, but we do not build anymore ...

**Comment by mgorny** [comment]
If you want to take it, please add yourself to metadata.xml and ping me. I'll mark the PR 'self-maintained' then to add it to our queue.

**Comment by henning-schild** [comment]
Sweet. It has been a while so i would have to review what i tried to do here.

As far as i remember it would have been much easier to switch to -bin, would that be OK?

I do not remember what was going on with the "VisibleVcsPkg", any high level advice what to do about that. Or maybe a link to documentation explaining what that is about and how to fix such issues?

**Comment by mgorny** [comment]
> As far as i remember it would have been much easier to switch to -bin, would that be OK?

We'd really, really prefer to have packages in source form.

> I do not remember what was going on with the "VisibleVcsPkg", any high level advice what to do about that. Or maybe a link to documentation explaining what that is about and how to fix such issues?

You can't have keywords in VCS ebuilds.

**Comment by henning-schild** [comment]
@mgorny 

This repairs the svn version and introduces a vcs ebuild of the latest upstream-stable. Upstream does not provide src-taballs anymore. And even if you get the main source i.e. via github ... you will also need secondary sources.
So for now just vcs ... We either have to mirror ourselfs or live with that vcs only i am afraid. Or open an upstream bug to request src-packages.

Added myself to metadata

**Comment by martin-kokos** [comment]
I understand this is a bit old. I have used @henning-schild 's ebuild as base for ebuild that builds the now current version of josm. Although it builds, there is few FIXME's that I am sure need to be done differently, but are beyond my abilities.
https://gist.github.com/martin-kokos/fa73a163171851904fbc40ea2c113a2f
If you would be willing to adapt these changes in proper way, great. If not, I'd be for closing this PR and perhaps reopening one for the Guru overlay and fix it up after getting some help and merge there.

**Comment by henning-schild** [comment]
I am essentially using josm-bin in my personal overlay since this looked like -bin would not be an option, i might look into it again now that is seems someone else does care as well.

**Comment by martin-kokos** [comment]
Yes, some more users care as commented in gentoo bugs. Please consider if it would be a good option to maintain it collectively in the Guru overlay instead of pushing you into maintainership in official repo.

**Comment by henning-schild** [comment]
@mgorny 
> We'd really, really prefer to have packages in source form.

I looked into this again. The build system uses ivy to download 88 additional jar files, 31MB. Maybe some are just required for testing but that number makes configuration management "somehow done in the ebuild" not feasible or maintainable ... I do not see a way for a true source ebuild.
I will push an ebuild that works but disables the network-sandbox, something that might be "allowed" in the 99999-case.

**Comment by henning-schild** [comment]
@martin-kokos this last one can be named i.e. 17428 to get a "stable" build

**Comment by henning-schild** [comment]
https://github.com/gentoo/gentoo/pull/19018

**Comment by henning-schild** [comment]
#19018

**Pull request closed without merging**
