### PR TITLE
media-libs/opencv: fix build problem with contribdnn

### PR DESCRIPTION
**Pull request by vowstar**
- support tflite import with contribdnn
- add dev-libs/flatbuffers RDEPEND and fix build problem
- fix protobuf 23.3 build problem with contribdnn

Bug: https://bugs.gentoo.org/909081
Bug: https://bugs.gentoo.org/912788
Blocked by: https://github.com/gentoo/gentoo/pull/32428

This PR depends on https://github.com/gentoo/gentoo/pull/32428, needs to be merged first.

### CODE REVIEW

**Comment by vowstar** [comment]
The QA will be fixed by https://github.com/gentoo/gentoo/pull/32428 merged.

**Comment by a17r** [comment]
That patch clearly was not tested:

> --     Protobuf:                    __location-NOTFOUND (23.3.0)

https://github.com/gentoo/gentoo/pull/34663

**Comment by negril** [comment]
I think that is caused by the General configuration block looking for `IMPORTED_LOCATION_RELEASE` instead of `IMPORTED_LOCATION_RELWITHDEBINFO` because it assumes we build the RELEASE target. There are a bunch of places where that breaks.

**Comment by a17r** [comment]
I'm talking about `4.8.0-fix-protobuf.patch`, that just broke cmake.

**Pull request closed without merging**
