### PR TITLE
xfce-extra/xfce4-whiskermenu-plugin: Version bumps

### PR DESCRIPTION
**Pull request by tietzc**
Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by tietzc** [comment]
I updated this PR as new versions have been released in the meantime.

**Comment by tietzc** [comment]
Ping.

**Comment by mgorny** [comment]
I'm sorry about the delay. I'm going to remove `gnome2_icon_savelist` calls since they are no longer necessary, and merge it afterwards. Thanks!

**Comment by tietzc** [comment]
@mgorny, not a problem. Thanks for merging.

**Pull request closed without merging**
