### PR TITLE
media-sound/musescore: add 4.2.0

### PR DESCRIPTION
**Pull request by zx2c4**
Closes: https://bugs.gentoo.org/913160

### CODE REVIEW

**Comment by zx2c4** [comment]
@fordfrog I'll push this myself if you have no objections.

**Comment by fordfrog** [comment]
> @fordfrog I'll push this myself if you have no objections.

cool, thanks! i had a quick look and it looks good. just the patches might need scrubbing.

**Comment by zx2c4** [comment]
Done. @fordfrog - would you mind if I add myself to the sound/prosound herds so I can more casually bump these packages? I find I'm doing a lot of work lately with sound tools, so this could be handy.

**Comment by fordfrog** [comment]
> Done. @fordfrog - would you mind if I add myself to the sound/prosound herds so I can more casually bump these packages? I find I'm doing a lot of work lately with sound tools, so this could be handy.

@zx2c4 that'd be awesome, thank you!

**Pull request closed without merging**
