### PR TITLE
net-misc/dhcp: add support for Infiniband

### PR DESCRIPTION
**Pull request by hlein**
Taken from Ubuntu's patchset, although it does not apply cleanly: https://packages.ubuntu.com/lunar/isc-dhcp-server

Closes: https://bugs.gentoo.org/908986

### CODE REVIEW

**Comment by hlein** [comment]
Rebased

**Comment by robbat2** [comment]
@hlein  that's a large patch.

A better way to maintain it would be to add the Ubuntu .debian.tar.* file as a distfile, and apply that patch.
Some of the existing patches in $FILESDIR might be duplicates

**Comment by hlein** [comment]
> @hlein that's a large patch.
> 
> A better way to maintain it would be to add the Ubuntu .debian.tar.* file as a distfile, and apply that patch. Some of the existing patches in $FILESDIR might be duplicates

Ah sure, I could look at that. Is the objection about sheer maintainability, or bloat of the portage tree rather than a devspace tarball, or both?

Hm, well the challenge with that is that their patchset doesn't apply cleanly to our version. Short of possibly throwing out all of our patches so that we use their series (or a subset), I'd have to... patch their patch before applying it maybe?

In Ubuntu's patchset, Infiniband changes are spread across multiple diffs (sometimes patching previous patches) and they are also quite large:
```
isc-dhcp_4.4.3-P1-4ubuntu1.debian/debian/patches $ ls -lU $(egrep -f <(egrep -il infiniband *) series)
-rw-rw-r-- 1 hlein wheel 20953 Nov 27 04:23 dhcp-lpf-ib.patch
-rw-rw-r-- 1 hlein wheel  5241 Nov 27 04:23 dhcp-improved-xid.patch
-rw-rw-r-- 1 hlein wheel  2760 Nov 27 04:23 dhcp-gpxe-cid.patch
-rw-rw-r-- 1 hlein wheel  1428 Nov 27 04:23 dhcp-improved-xid-correct-byte-order.patch
-rw-rw-r-- 1 hlein wheel  6111 Nov 27 04:23 dhcp-4.2.4-dhclient-options-changed.patch
```
The good news is, if I apply those to our `dhcp-4.4.3_p1-r4`, there's actually only one hunk that outright fails; the rest just get various dirty offsets. Would it in fact be better to use the upstream patchset, patching the failing patch (`dhcp-lpf-ib.patch`) before applying?

We have some quite big patches in `net-misc/dhcp/files/` already, although my `dhcp-4.4.3-infiniband.patch` is indeed the biggest by almost a factor of 2.

I also wondered about giving up on ISC `dhcpd` entirely, as ISC themselves have done, and maybe switch to their replacement `kea`. But... it _also_ doesn't support Infiniband without third-party patches.

Thanks!

**Comment by thesamesam** [comment]
> In Ubuntu's patchset, Infiniband changes are spread across multiple diffs (sometimes patching previous patches) and they are also quite large:

Given this, I don't think it's really going to be a win for us to change to it. Normally, I'd really prefer using the Debian/Ubuntu patchsets in a situation like this and just patch stuff on top if we must, but it doesn't really seem like a good fit here...

Longer-term though, we should probably figure out Kea and patch it if needed given dhcp is limping on...

**Pull request closed without merging**
