### PR TITLE
net-libs/libwebsockets: add v4.0.1

### PR DESCRIPTION
**Pull request by jsmolic**
Update to latest version.
Closes: https://bugs.gentoo.org/716386

Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>
Signed-off-by: Luka Perkov <luka.perkov@sartura.hr>
Acked-by: Jaco Kroon <jaco@uls.co.za>

### CODE REVIEW

**Comment by jkroonza** [comment]
Hi.

I do not object to adding ~arm64, but please do file a keywording bug for that.  This will let you know all the deps that's also required to be keyworded (https://devmanual.gentoo.org/keywording/index.html).  Please don't add arches until you've gotten the full list, so in package list, place "net-libs/libwebsockets ~arm64" and so forth.  You should at the very least compile-test every package you list, and ideally action some functionality testing too (FEATURES=test, but IIRC there isn't much automated tests for these packages that I can reproduce).  Looks like libhubub is the one that cropped up here.

Also don't object to bumping, and welcome the help.  If you're going to be using this longer term, please feel free to also add yourselves to the list of maintainers.  Same for libhubbub - which I picked up because of the fact that libwebsockets depend thereon.

**Comment by jsmolic** [comment]
@jkroonza Thank you for your help and quick response. 
I checked right now, and it seems that `libhubbub` is the only dependancy that needs to be keyworded. That said, I will file a keywording bug, and test the package accordingly.

**Comment by jkroonza** [comment]
@jsmolic 

Please drop ~arm64 here (take that via a bug report).  You're welcome to post the link or assign to me - I've got someone that can confirm that we can add ~arm64.

Then, to this commit, please add a Closes: https://bugs.gentoo.org/716386

I've sent the fix for that upstream but never added the patch to ::gentoo preferring to wait for next release.

**Comment by jkroonza** [comment]
Also please:

Acked-by: Jaco Kroon <jaco@uls.co.za>

**Comment by jsmolic** [comment]
@jkroonza I filed a keywording bug: https://bugs.gentoo.org/717232
Also, I removed ~arm64 keyword and added comments to commit message.

Thank you again :)

**Comment by jkroonza** [comment]
Sorry for this, between last post and now I picked up that Andy changed the licensing to MIT, if you could please update the LICENSE to ="MIT" instead of LGPL-2.1 please?

I'll be pushing a PR now as well to remove 4.0.0 from the tree.

**Comment by jsmolic** [comment]
@jkroonza No worries, I changed the license, it should be okay now :)

**Comment by jsmolic** [comment]
@jkroonza We can help with maintaining, so I added @lperkov and myself as package maintainers

**Comment by jsmolic** [comment]
@jkroonza Thank you!\
We will be making further improvements of this package, such as adding mbedTLS support.

**Comment by juippis** [comment]
@jsmolic your friend who was added to metadata.xml doesn't have a bugzilla account registered to that e-mail.

Could you make the account, or remove this e-mail from metadata.xml?

**Comment by jsmolic** [comment]
@juippis Thank you for notifying me.\
I created new account with his email address, so you should able to assign a proxy maintainer bug  to him.

**Comment by juippis** [comment]
@jsmolic did I understand it right that you now have 2 bugzilla accounts? :)

The point of someone being added to metadata.xml is that they get bugzilla mails. It ruins the purpose if YOU receive double mails...

**Comment by jsmolic** [comment]
@juippis No, no :)\
I should have specified it a bit better. I only went on create account page on Bugzilla (https://bugs.gentoo.org/createaccount.cgi) and entered my friend's mail address, so now he has to activate the account and then he will receive bugzilla notifications on his email address (to which I have no access)

Of course it makes no sense if I receive double emails.\
Hope that clarifies it :)

**Comment by juippis** [comment]
Heh, yes, thank you. All good now I hope.

**Pull request closed without merging**
