### PR TITLE
media-video/libav: fix workdir for libav-12

### PR DESCRIPTION
**Pull request by pefoley2**
20160522 vs 201605022
Package-Manager: portage-2.3.0_rc1

### CODE REVIEW

**Comment by Coacher** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=584042

**Comment by monsieurp** [comment]
@lu-zero yo. can you take a look?

**Comment by lu-zero** [comment]
Hi, there should be a new snapshot in, sadly the previous one was rushed in between some travels =/

**Comment by lu-zero** [comment]
A new snapshot should be already available, sorry for the typo =)

**Pull request closed without merging**
