### PR TITLE
www-apps/klaus: bump to 1.2.1, add Python 3.6 + bump/add python targets to dependencies

### PR DESCRIPTION
**Pull request by sbraz**
Lots of commits here, mostly to add Python 3.6 (and PyPy where possible).
Klaus itself didn't change much. It still can't be tested outside of the git repository. I made sure that it worked with the listed Python targets.
The biggest change is probably the dulwich bump:
```diff
--- dulwich-0.17.3.ebuild       2017-09-18 16:45:17.939973347 +0200
+++ dulwich-0.18.3.ebuild       2017-09-19 01:12:46.254604762 +0200
@@ -13,7 +13,7 @@
 
 LICENSE="GPL-2+"
 SLOT="0"
-KEYWORDS="amd64 ~arm64 ~ppc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
+KEYWORDS="~amd64 ~arm64 ~ppc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
 IUSE="doc examples test"
 
 DEPEND="
@@ -27,6 +27,10 @@
 
 DISTUTILS_IN_SOURCE_BUILD=1
 
+# One test sometimes fails
+# https://github.com/jelmer/dulwich/issues/541
+PATCHES=( "${FILESDIR}/${P}-skip-failing-test.patch" )
+
 python_compile_all() {
        use doc && emake -C docs html
 }
@@ -37,6 +41,10 @@
 
 python_install_all() {
        use doc && local HTML_DOCS=( docs/build/html/. )
-       use examples && dodoc -r examples
+       if use examples; then
+               insinto "/usr/share/doc/${PF}"
+               docompress -x "/usr/share/doc/${PF}/examples"
+               doins -r examples
+       fi
        distutils-r1_python_install_all
 }
```

### CODE REVIEW

**Comment by grobian** [comment]
dev-python/dulwich pushed

**Comment by sbraz** [comment]
@grobian Thanks! Do you also want to remove the older versions?

**Comment by grobian** [comment]
not yet, I have to look into the depgraph for that, the keywords are weird somehow

**Comment by sbraz** [comment]
Version 0.17.3 is stable on amd64 and x86. 0.9.9 is only stable on amd64 and 0.13.0 isn't stable at all. I'm pretty sure the bot would have complained if my commit had broken anything:
https://qa-reports.gentoo.org/output/gentoo-ci/53c9b61e6/output.html
I grepped the tree and I don't see any deps on old versions:
```
/usr/portage # grep -R dev-python/dulwich --include '*.ebuild' .
./dev-vcs/hg-git/hg-git-0.8.5.ebuild:   >=dev-python/dulwich-0.9.7[${PYTHON_USEDEP}]
./dev-vcs/hg-git/hg-git-0.8.8.ebuild:   >=dev-python/dulwich-0.9.7[${PYTHON_USEDEP}]
./dev-vcs/hg-git/hg-git-0.8.6.ebuild:   >=dev-python/dulwich-0.9.7[${PYTHON_USEDEP}]
./dev-vcs/bzr-git/bzr-git-0.6.8-r1.ebuild:RDEPEND=">=dev-python/dulwich-0.8.2[${PYTHON_USEDEP}]
./dev-vcs/rabbitvcs/rabbitvcs-0.16-r1.ebuild:   git? ( dev-python/dulwich[${PYTHON_USEDEP}] )
./dev-python/anyvc/anyvc-0.3.7.1-r1.ebuild:     git? ( dev-python/dulwich[${PYTHON_USEDEP}] )
./dev-python/openstackdocstheme/openstackdocstheme-1.16.1.ebuild:       >=dev-python/dulwich-0.15.0[${PYTHON_USEDEP}]"
./dev-python/reno/reno-2.5.0.ebuild:    >=dev-python/dulwich-0.15.0[${PYTHON_USEDEP}]"
./dev-python/reno/reno-2.2.1.ebuild:    >=dev-python/dulwich-0.15.0[${PYTHON_USEDEP}]"
./www-apps/klaus/klaus-1.0.1.ebuild:    >=dev-python/dulwich-0.13.0[${PYTHON_USEDEP}]
./www-apps/klaus/klaus-1.1.0.ebuild:    >=dev-python/dulwich-0.13.0[${PYTHON_USEDEP}]
```

**Comment by grobian** [comment]
cleaned, thanks!

**Comment by sbraz** [comment]
I guess I should remove the dulwich changes from the PR to solve the conflicts? I thought git would find out you pushed similar commits to mine.

**Comment by grobian** [comment]
I think that's easiest indeed.  Dunno why it conflicts.

**Comment by sbraz** [comment]
Removed dulwich-related commits and rebased against master.

**Pull request closed without merging**
