### PR TITLE
dev-util/dmake: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from dev-util/dmake.
Package belongs to @chithanh 

Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
ping, just rebased my PR :)

**Comment by mm1ke** [comment]
ping, just another rebase :)

**Comment by chithanh** [comment]
Hi,

Thanks for the pr
I was away in November so could not get to it yet, but it is on my todo 
list.


Best regards,
Chí-Thanh Christopher Nguyễn


Michael Mair-Keimberger (iamnr3) schrieb:

**Comment by mgorny** [comment]
Since this is a trivial change, I've just verified that neither of the patches is used and merged it.

**Pull request closed without merging**
