### PR TITLE
dev-python/{rtslib-fb,configshell-fb}, sys-block/targetcli-fb: version bumps

### PR DESCRIPTION
**Pull request by diogocp**

### CODE REVIEW

**Comment by prometheanfire** [comment]
I don't think configshll-fb needs uriwd anymore.

Is there a reason why targetcli-fb now depends on the latest version of rtslib-fb?

**Comment by diogocp** [comment]
> I don't think configshll-fb needs uriwd anymore.

See https://github.com/open-iscsi/configshell-fb/blob/v1.1.fb22/configshell/node.py#L1062

> Is there a reason why targetcli-fb now depends on the latest version of rtslib-fb?

Yes, I tried with the old version and it didn't work. It imports classes that were added in rtslib-fb 2.1.62.

**Comment by prometheanfire** [comment]
k, lgtm then, will merge in a min

**Comment by prometheanfire** [comment]
pushed

**Pull request closed without merging**
