### PR TITLE
media-libs/mesa: d3d9 now supports also iris

### PR DESCRIPTION
**Pull request by okias**
Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by okias** [comment]
May I remaind this one line change, which allow iris users to use d3d9? Thank you

**Comment by mattst88** [comment]
You forgot the other necessary part of the change: the conditional that protects emesonargs+=($(meson_use d3d9 gallium-nine)).

**Comment by okias** [comment]
@mattst88 sorry about that, now it should be OK :)

P.S. why so many checks?

**Comment by mattst88** [comment]
Thanks. Merged.

The reason for the conditionals (and all of pkg_pretend()) is because the new Meson build system is more strict about enabling options that cannot be used with the enabled drivers.

See commits a0ece8925e0d757751a9b9d26eeae2796f5aa4b8 and 4d352ccbca4ba4e136efdee4ac5962724ee6294c for more details.

**Pull request closed without merging**
