### PR TITLE
app-doc/single-unix-specification: Add 4-r3.

### PR DESCRIPTION
**Pull request by omasanori**
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=601592

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/qa, are we ok with base-system abusing -r for next upstream revisions?

**Comment by robbat2** [comment]
@base-system here, I think this should be changed to use something else, maybe _p$N ?

**Comment by mgorny** [comment]
> @base-system here, I think this should be changed to use something else, maybe _p$N ?

My thought as well.

**Comment by omasanori** [comment]
Is it better to close this PR and make a new PR to rename SUSv4TC1 to 4_p1 and SUSv4TC2 to 4_p2?

**Comment by robbat2** [comment]
Yes please, and cite this PR in the message.

**Comment by omasanori** [comment]
OK. Thank you!

**Pull request closed without merging**
