### PR TITLE
app-misc/libdatovka: Fix error call to undeclared function getopt

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/900495

### CODE REVIEW

**Comment by thesamesam** [comment]
They have a gitlab at https://gitlab.nic.cz/datovka/libdatovka/- send it upstream?

**Comment by Amynka** [comment]
@listout I agree the upstream is quite active they will be happy for the pr. Can you please submit it there?

**Comment by Amynka** [comment]
However maybe before Karel applies it we can patch it too..

**Comment by thesamesam** [comment]
You might have to email them to request permissions to fork, it's an anti-spam measure on some gitlabs now. Try gitlab@nic.cz.

**Comment by listout** [comment]
Please close this one, the fix has been merged. https://gitlab.nic.cz/datovka/libdatovka/-/merge_requests/26

cc: @thesamesam

**Pull request closed without merging**
