### PR TITLE
sys-apps/inxi: version bump and fix DESCRIPTION.toolong

### PR DESCRIPTION
**Pull request by jonasstein**
Project moved from google source to github.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by jonasstein** [comment]
next time I will split this in several commits...

**Comment by doughdemon** [comment]
Please remove the NoFinalNewLine commits. The fixes are already in the tree.

**Comment by monsieurp** [comment]
Apparently, this is a maintainer-needed package. Would you like to take over maintainership?

**Comment by jonasstein** [comment]
@monsieurp Yes, I want to take over maintainership, I will create a new PR then and close this one.

**Pull request closed without merging**
