### PR TITLE
games-emulation/rmg: add 0.6.6

### PR DESCRIPTION
**Pull request by orbea**
* Fix mupen64plus-core URL in the about dialog
* Fix GLideN64 not showing native path seperator in the configuration dialog (see https://github.com/gonetz/GLideN64/pull/2860)
* Add 'SDL controller mode' option to the options dialog of RMG-Input
* Add 'None' option to configuration file of mupen64plus-input-gca (thank you @GhostlyDark)
* Update GLideN64, mupen64plus-core and SDL_GameControllerDB

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
There appears to be quite a bit of recursive cmake calls calling into cmake??

The build failed somewhere deeply nested inside:

```
[67/149] Building CXX object CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o
FAILED: CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o 
/usr/bin/x86_64-pc-linux-gnu-g++ -DM64P_GLIDENUI -DMUPENPLUSAPI -DOS_LINUX -DQT_CORE_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DTXFILTER_LIB -Dmupen64plus_video_GLideN64_EXPORTS -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6_build/Source/3rdParty/mupen64plus-video-GLideN64/mupen64plus-video-GLideN64_autogen/include -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6_build/Source/3rdParty/mupen64plus-video-GLideN64/inc -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/. -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/inc -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/osal -I/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/GLideNHQ -I/usr/include/freetype2 -isystem /usr/include/qt6/QtWidgets -isystem /usr/include/qt6 -isystem /usr/include/qt6/QtCore -isystem /usr/lib64/qt6/mkspecs/linux-g++ -isystem /usr/include/qt6/QtGui -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -flto=4 -Werror=odr -Werror=lto-type-mismatch -Werror=strict-aliasing  -Wformat -Werror=format-security -std=c++11 -pthread -O2 -g -DNDEBUG -std=gnu++17 -flto=auto -fno-fat-lto-objects -fPIC -fPIC -MD -MT CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o -MF CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o.d -o CMakeFiles/mupen64plus-video-GLideN64.dir/Textures.cpp.o -c /var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4IA_RGBA4444(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:55:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   55 |                 return IA88_RGBA4444(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B & 0x0F)) & 0x1FF]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:57:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   57 |                 return IA88_RGBA4444(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B >> 4)) & 0x1FF]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4IA_RGBA8888(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:65:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   65 |                 return IA88_RGBA8888(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B & 0x0F)) & 0x1FF]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:67:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   67 |                 return IA88_RGBA8888(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B >> 4)) & 0x1FF]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4RGBA_RGBA5551(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:75:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   75 |                 return RGBA5551_RGBA5551(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B & 0x0F)) & 0x1FF]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:77:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   77 |                 return RGBA5551_RGBA5551(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B >> 4)) & 0x1FF]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4RGBA_RGBA8888(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:85:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   85 |                 return RGBA5551_RGBA8888(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B & 0x0F)) & 0x1FF]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:87:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
   87 |                 return RGBA5551_RGBA8888(*(u16*)&TMEM[(0x100 + (palette << 4) + (color4B >> 4)) & 0x1FF]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8IA_RGBA4444(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:123:31: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  123 |         return IA88_RGBA4444(*(u16*)&TMEM[(0x100 + color) & 0x1FF]);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8IA_RGBA8888(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:129:31: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  129 |         return IA88_RGBA8888(*(u16*)&TMEM[(0x100 + color) & 0x1FF]);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8RGBA_RGBA5551(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:135:35: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  135 |         return RGBA5551_RGBA5551(*(u16*)&TMEM[(0x100 + color) & 0x1FF]);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8RGBA_RGBA8888(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:141:35: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  141 |         return RGBA5551_RGBA8888(*(u16*)&TMEM[(0x100 + color) & 0x1FF]);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI16IA_RGBA8888(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:196:27: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  196 |         const u16 col = (*(u16*)&TMEM[0x100 + (tex & 0xFF)]);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI16IA_RGBA4444(u16, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:205:27: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  205 |         const u16 col = (*(u16*)&TMEM[0x100 + (tex & 0xFF)]);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4IA_RGBA4444_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:306:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  306 |                 return IA88_RGBA4444(*(u16*)&TMEM[256 + (palette << 4) + (color4B & 0x0F)]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:308:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  308 |                 return IA88_RGBA4444(*(u16*)&TMEM[256 + (palette << 4) + (color4B >> 4)]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4IA_RGBA8888_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:316:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  316 |                 return IA88_RGBA8888(*(u16*)&TMEM[256 + (palette << 4) + (color4B & 0x0F)]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:318:39: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  318 |                 return IA88_RGBA8888(*(u16*)&TMEM[256 + (palette << 4) + (color4B >> 4)]);
      |                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4RGBA_RGBA5551_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:326:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  326 |                 return RGBA5551_RGBA5551(*(u16*)&TMEM[256 + (palette << 4) + (color4B & 0x0F)]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:328:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  328 |                 return RGBA5551_RGBA5551(*(u16*)&TMEM[256 + (palette << 4) + (color4B >> 4)]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI4RGBA_RGBA8888_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:336:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  336 |                 return RGBA5551_RGBA8888(*(u16*)&TMEM[256 + (palette << 4) + (color4B & 0x0F)]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:338:43: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  338 |                 return RGBA5551_RGBA8888(*(u16*)&TMEM[256 + (palette << 4) + (color4B >> 4)]);
      |                                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8IA_RGBA4444_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:371:31: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  371 |         return IA88_RGBA4444(*(u16*)&TMEM[256 + ((u8*)src)[x ^ (i << 1)]]);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8IA_RGBA8888_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:376:31: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  376 |         return IA88_RGBA8888(*(u16*)&TMEM[256 + ((u8*)src)[x ^ (i << 1)]]);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8RGBA_RGBA5551_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:381:35: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  381 |         return RGBA5551_RGBA5551(*(u16*)&TMEM[256 + ((u8*)src)[x ^ (i << 1)]]);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI8RGBA_RGBA8888_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:386:35: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  386 |         return RGBA5551_RGBA8888(*(u16*)&TMEM[256 + ((u8*)src)[x ^ (i << 1)]]);
      |                                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI16IA_RGBA8888_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:432:27: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  432 |         const u16 col = (*(u16*)&TMEM[256 + (tex & 0xFF)]);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp: In function ‘u32 GetCI16IA_RGBA4444_BG(u64*, u16, u16, u8)’:
/var/tmp/portage/games-emulation/rmg-0.6.6/work/RMG-0.6.6/Source/3rdParty/mupen64plus-video-GLideN64/src/Textures.cpp:441:27: error: dereferencing type-punned pointer will break strict-aliasing rules [-Werror=strict-aliasing]
  441 |         const u16 col = (*(u16*)&TMEM[256 + (tex & 0xFF)]);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cc1plus: some warnings being treated as errors
```

**Comment by orbea** [comment]
I reported it upstream. https://github.com/gonetz/GLideN64/issues/2877

**Comment by eli-schwartz** [comment]
Thanks. Can you also add append-flags -fno-strict-aliasing / filter-lto as a temporary workaround?

**Comment by orbea** [comment]
> Thanks. Can you also add append-flags -fno-strict-aliasing / filter-lto as a temporary workaround?

Done.

**Comment by eli-schwartz** [comment]
```
games-emulation/rmg
  IndirectInherits: version 0.6.5: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
  RedundantVersion: version 0.6.5: slot(0) keywords are overshadowed by version: 0.6.6
  UnusedInherits: version 0.6.5: unused eclass: toolchain-funcs
  IndirectInherits: version 0.6.6: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
  UnusedInherits: version 0.6.6: unused eclass: toolchain-funcs
  IndirectInherits: version 9999: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
  UnusedInherits: version 9999: unused eclass: toolchain-funcs
```

append-flags / filter-lto are part of flag-o-matic.eclass, not toolchain-funcs. They are indirectly inherited as a side effect of cmake and cargo both inheriting flag-o-matic, so it still appears to work when you test it, but the linter (`pkgcheck scan .`) notices.

**Comment by orbea** [comment]
> ```
> games-emulation/rmg
>   IndirectInherits: version 0.6.5: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
>   UnusedInherits: version 0.6.5: unused eclass: toolchain-funcs
>   IndirectInherits: version 0.6.6: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
>   UnusedInherits: version 0.6.6: unused eclass: toolchain-funcs
>   IndirectInherits: version 9999: flag-o-matic: indirect inherit usage: 'append-flags -fno-strict-aliasing', line 124
>   UnusedInherits: version 9999: unused eclass: toolchain-funcs
> ```
> 
> append-flags / filter-lto are part of flag-o-matic.eclass, not toolchain-funcs. They are indirectly inherited as a side effect of cmake and cargo both inheriting flag-o-matic, so it still appears to work when you test it, but the linter (`pkgcheck scan .`) notices.

Oops, I copied the wrong eclass... Thanks for catching that.

**Comment by orbea** [comment]
The `qa-reports` page is not loading for me and I don't see any errors locally with `pkgcheck scan .`

**Comment by eli-schwartz** [comment]
It claimed there was a "global" error which I doubt. There were some infra errors with report/gentoo-ci.git not too long ago, that may have been related. I wouldn't worry about it.

**Pull request closed without merging**
