### PR TITLE
sci-mathematics/eclib: add 20230424

### PR DESCRIPTION
**Pull request by kiwifb**

### CODE REVIEW

**Comment by kiwifb** [comment]
A note, this sets `SLOT="0/10"` down from the ebuild of the previous version. The previous ebuild has the following
```
# Major version of /usr/lib64/libec.so
# It *should* be at 11 in v20221012, as this commit shows,
#
#   https://github.com/JohnCremona/eclib/commit/b63b8bb
#
# but it's actually still at 10, probably due to a forgotten autoreconf
# or something.
SLOT="0/11"
```
which seems to indicate a lack of understanding of autotools versioning. `configure.ac` in 20230424 is like
```
# NB The suffix of the library name (libec.so here) is (c-a).a.r

LT_CURRENT=12
LT_REVISION=0
LT_AGE=2
```
and as indicated by the formula we get `libec.so.10.2.0` because it is 12-2. And in the previous version it was still 10 as 11-1.
I did not correct the 20221012 ebuild and whatever we do may cause strange rebuild downstream anyway.

**Comment by orlitzky** [comment]
Should we just use `$PV` for the slot then and update the comment? We're only lying to ourselves :)

**Comment by kiwifb** [comment]
No, John does do it the correct way (which is confusing in autotools notation) so I do not think we are lying to ourselves. Certainly, the PR for updating eclib in sage-10 did not require any changes sage side. Formally, using the old eclib would be just as good.

**Comment by orlitzky** [comment]
In this version `CC` was dropped from `interface.h`: https://github.com/JohnCremona/eclib/commit/333a505d0cb244340cb0a67e6ef5e43f2c56e341

So I think library version should be 12.0.0 according to https://www.gnu.org/software/libtool/manual/html_node/Updating-version-info.html?

I guess a better solution would be to fix the "age" and run eautoreconf. If some program was using `CC`, it should try to rebuild against the new libec, fail, and then remain linked to the old libec. But for the old libec to stick around it needs to have a different soname than the new one. I think I'll do this and set the subslot to 12 (which will then match the soname) unless you object.

**Pull request closed without merging**
