### PR TITLE
app-admin/collectd: Bumped to v5.5.1

### PR DESCRIPTION
**Pull request by Whissi**
- New upstream version (Closes #[570766](https://bugs.gentoo.org/show_bug.cgi?id=570766), #[517060](https://bugs.gentoo.org/show_bug.cgi?id=517060))

- Non-functional mongodb plugin disabled in ebuild (see upstream
  issue #492, closes #[524400](https://bugs.gentoo.org/show_bug.cgi?id=524400))

- Multiple dependency problems fixed

- linux-info eclass usage fixed (Closes #[570778](https://bugs.gentoo.org/show_bug.cgi?id=570778))

- Support for new plugins added (amqp, genericjmx, ipvs, modbus, sigrok,
  tail_csv, vserver, write_riemann)

- PYTHON_SINGLE_TARGET support for Python 3.4 and 3.5 enabled

- Documentation improved (USE flag description, elogs)

- Linux capabilities usage expanded to improve running collectd as
  unprivileged user (disable via filecaps USE flag)

- Runscript rewritten

  - Runscript now supports OpenRC's default status function

  - Runscript now guarantees service shutdown

  - Validating configuration before (re)starting daemon

### CODE REVIEW

**Comment by Whissi** [comment]
@jbergstroem *ping*

**Comment by jbergstroem** [comment]
Thanks for your work. Will review over the weekend.

**Comment by gktrk** [comment]
Is there a reason why "epatch ${PATCHES[@]}" is called on line 265? I believe the EAPI6 equivalent is eapply, unless the patches are not in p1 format.

**Comment by jbergstroem** [comment]
@gktrk afaik its easier to call `default` in eapi6 to get PATCHES() applied (among other things).

**Comment by Whissi** [comment]
Yes, because we provide our own `SRC_PREPARE()` function so we have to call `epatch` and `eapply_user` on our own.

In theory we could call `default` instead however if we ever have to apply a patch with different patch level we would have to rewrite so I chose this style on purpose.

**Comment by Whissi** [comment]
However I re-read EAPI6's `src_prepare()` definition and will update the PR to switch to `default` usage and also eliminate eutils eclass usage.

**Comment by jbergstroem** [comment]
@Whissi yeah, sorry for not being clear enough; I meant invoking `default` to get parent functionality just like you implemented.

**Comment by monsieurp** [comment]
@jbergstroem let us know when the PR's good go to!

**Comment by jbergstroem** [comment]
LGTM

**Pull request merged**
