### PR TITLE
net-misc/buka: version bump to 2.0

### PR DESCRIPTION
**Pull request by drylemon**
Adds support for different file formats
through the 'pdf' and 'cbz' USE flags.

### CODE REVIEW

**Comment by gktrk** [comment]
Not sure if I favor this. The semantics are a bit off since `USE='-pdf -cbz'` does not actually disable anything. Furthermore, if the user wants to enable pdf support, enabling `USE="pdf"` for this package causes an unnecessary merge of this package. It may be better to print a `postinst` message about optional dependencies and tell the user to install those themselves.

**Comment by gktrk** [comment]
Also, please do not remove and bump packages in a single commit. It's better to have one commit for the bump followed by another commit for the removal.

**Comment by gktrk** [comment]
Lastly, we should keep the summary line (the first line) in the commit message around 70-75 characters to comply with the [commit message format](https://devmanual.gentoo.org/ebuild-maintenance/index.html#git-commit-message-format)

**Comment by drylemon** [comment]
@gktrk I wasn't sure whether to use USE flags or optfeature. What you're saying makes sense though, so I'll make the necessary changes. My bad about combining the commits.

**Comment by drylemon** [comment]
changes have been made.

**Comment by drylemon** [comment]
squashed commits to keep things clean.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/85e0c86...0f1163b. Thanks!

- I split the bump and removal into two commits before pushing.
- It may be better if you use a separate development branch instead of master, it's simpler.
- In the future, please try to use repoman for committing things, see https://wiki.gentoo.org/wiki/Gentoo_Github#Use_of_repoman

**Pull request closed without merging**
