### PR TITLE
app-crypt/certbot: add ~arm64 keywords to certbot and dependencies.

### PR DESCRIPTION
**Pull request by stikonas**
Signed-off-by: Andrius Štikonas <andrius@stikonas.eu>

### CODE REVIEW

**Comment by prometheanfire** [comment]
has conflicts :(

**Comment by stikonas** [comment]
Oh, looks like certbot was stabilized in the meantime. I'll update the merge request (maybe tomorrow?)

**Comment by stikonas** [comment]
Delay in push request processing? At the time of pull request 0.28 was the latest. I think 0.27 is still in tree, so technically not all versions....

Before yesterday, it was latest plus -9999 (which actually has no keywords, they are fake, just easier for next bump if maintainer copies 9999 to new version).

On 4 January 2019 06:24:33 GMT+00:00, digitallyelite <notifications@github.com> wrote:
>Is there a specific reason to add the keyword to every package version?
> Typically you just add it to the latest package version.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/gentoo/gentoo/pull/10393#issuecomment-451362398

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by prometheanfire** [comment]
I'm waiting for arm64 team to ack this, I still need to stabilize 0.29.1 for amd64 and x86 (so you'll need to rebase...).  Would you rather I bump to 0.30.0 now as well?

**Comment by stikonas** [comment]
> I'm waiting for arm64 team to ack this, I still need to stabilize 0.29.1 for amd64 and x86 (so you'll need to rebase...). Would you rather I bump to 0.30.0 now as well?

I guess one rebase is better for me.

**Comment by prometheanfire** [comment]
merged

**Pull request closed without merging**
