### PR TITLE
sys-libs/db: Security revbumps to disable usage of bundled sqlite.

### PR DESCRIPTION
**Pull request by Polynomial-C**
This fixes Gentoo bug #605688

### CODE REVIEW

**Comment by Polynomial-C** [comment]
@gentoo/base-system

**Comment by robbat2** [comment]
Please see the bug and do NOT merge.

**Comment by mgorny** [comment]
Should we close this or…?

**Comment by robbat2** [comment]
@mgorny I was looking deeper, and it seems the usage base of this functionality is much smaller than I previously thought, so going to merge it as a revbump and see what breakage falls out.

**Comment by mgorny** [comment]
@robbat2, @Polynomial-C, ping. It seems that this still hasn't been merged.

**Pull request closed without merging**
