### PR TITLE
Don't skip xvfb dependency on Prefix

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by heroxbd** [comment]
Thanks for the pull request!  Could you please explain briefly why it should be so?

**Comment by heroxbd** [comment]
I see, I have discovered https://archives.gentoo.org/gentoo-dev/message/af21c0264b352659e3fe393263712c0b 

LGTM

**Comment by DarthGandalf** [comment]
So... Could this be merged?

@grobian?

**Comment by grobian** [comment]
pushed, thanks

**Comment by heroxbd** [comment]
Thanks!

**Pull request closed without merging**
