### PR TITLE
sys-boot/grub: Move to EAPI 6

### PR DESCRIPTION
**Pull request by bjacquin**
Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by nvinson** [comment]
If you haven't already, please reach out to @floppym or the base system project (base-system@gentoo.org) to see if they're okay with this commit.

**Comment by SoapGentoo** [comment]
@williamh @Polynomial-C could you check this please?

**Comment by floppym** [comment]
It seems a little pointless to do an EAPI bump just for the sake of it. I would wait until there is some other change that needs to be made.

**Comment by bjacquin** [comment]
Well, the reason for me to do this EAPI bump is because I am applying a few patches to grub:0 and I'd like to rely on epatch_user (which is now part of EAPI 6) instead of maintaining my own version of the ebuild in my own overlay.

**Comment by nvinson** [comment]
In that case, I would just add a call to epatch_user() in src_prepare() and not worry about an EAPI bump.  Given the nature of the change you could probably avoid a revision bump as well.

By the way, epatch_user() is available in EAPI 5.  The EAPI 6 version is called eapply_user().

**Comment by floppym** [comment]
The patchset that gets applied in the ebuild does not work with `eapply` (see below). The patches do not work with `patch -p1`.

I would accept a patch to add an `epatch_user` call to the ebuild using EAPI 5 instead.

```
>>> Preparing source in /tmp/portage/sys-boot/grub-0.97-r18/work/grub-0.97 ...
 * Applying patches from /tmp/portage/sys-boot/grub-0.97-r18/work/patch ...
 *   001_all_grub-0.95.20040823-splash.patch ...                                             [ ok ]
 *   002_all_grub-0.97-splashimage-safety.patch ...                                          [ ok ]
 *   003_all_grub-0.97-example-rescue-shell.patch ...                                        [ ok ]
 *   005_all_grub-0.96-PIC.patch ...                                                         [ ok ]
 *   008_all_grub-0.97-AM_PROG_AS.patch ...
The text leading up to this was:
--------------------------
|cleanup autotools a bit
|
|http://bugs.gentoo.org/156524
|
|--- configure.ac
|+++ configure.ac
--------------------------
No file to patch.  Skipping patch.
```

**Comment by floppym** [comment]
Also, that would *not* require a revbump.

**Comment by bjacquin** [comment]
Done in last PR

**Comment by floppym** [comment]
Rebased as 47510f3ef16cd103897ce2be858c5fbdee9de001. Thanks!

**Pull request closed without merging**
