### PR TITLE
sys-process/procps: Allow installing "skill" and "snice"

### PR DESCRIPTION
**Pull request by emanuele6**
Signed-off-by: Emanuele Torre <torreemanuele6@gmail.com>

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by emanuele6** [comment]
@thesamesam
I have just tried your suggested `EXTRA_ECONF=--enable-skill` as alternative to adding the `skill` local USE flag to avoid having to maintain my local ebuild for procps since this PR hasn't been merged yet.
Unfortunately, that does not work since `sys-process/procps` has a binary package, and there is no easy way to disable `FEATURES=getbinpkg` for a single package. https://bugs.gentoo.org/463964
One would have to enable a random procps USE flag that they don't necessarily want for which there is not a binary package available, to make the `EXTRA_ECONF` approach work.
Another reason why I think adding this USE flag makes sense; these tools are installed by default on the majority of distributions, and getting them on gentoo is unnecessarily hard.

**Comment by floppym** [comment]
I would like to see some justification given. The commands have clearly been flagged as obsolete by upstream. Why do you want/need them?

**Comment by emanuele6** [comment]
@floppym I think that is a very weird question. To use them of course.
They haven't just been "marked obsolete"; they haven't been built by default for over 12 years; it doesn't change the fact that it is readily available on most systems, and on gentoo it is made unnecessarily hard to install them.
Is that your only objection?

**Comment by floppym** [comment]
README.md file describes skill as an "obsolete version of pgrep/pkill".

This [commit](https://gitlab.com/procps-ng/procps/-/commit/1462c4e581caf22b2e7fe155691dfcddcb51b3f7) also says they are obsolete and unportable, and discourages distros from installing them.

The skill.1 man page starts with the text "These  tools  are  obsolete and unportable.  The command syntax is poorly defined.  Consider using the killall, pkill, and pgrep commands instead.".

I see no reason to make it "easy" to install these when better alternatives are available by default.

**Comment by emanuele6** [comment]
I don't understand what you are pointing out; they have been marked obsolete 12 years ago, not now.
I honestly don't understand why you are so against a USE flag that simply passes a `--enable-` configure flag for users that want to use `snice`.

**Comment by floppym** [comment]
Again, I don't see any reason for it.

**Comment by eli-schwartz** [comment]
> Another reason why I think adding this USE flag makes sense; these tools are installed by default on the majority of distributions, and getting them on gentoo is unnecessarily hard.

By "majority of distributions" I assume you mean, "debian does it". https://salsa.debian.org/debian/procps/-/commit/0bf315335098f6b50d3f4fb91aed1af0cecf101d

They don't document why they do it and it's a decision made "over 12 years ago" and seemingly never revisited, which I don't think is a compelling argument in favor of it actually receiving usage. Debian is pretty good at re-enabling deprecated functionality the day it is deprecated, to give people a bit more time to migrate off, then forgetting about the topic for a decade or two.

> I don't understand what you are pointing out; they have been marked obsolete 12 years ago, not now.

I can't parse this sentence into semantically meaningful English.

**Comment by eli-schwartz** [comment]
Fedora is in the same situation: https://bugzilla.redhat.com/show_bug.cgi?id=974752

> Either that the command is found, removed from documentation or a note in documentation that the command is deprecated and which command to use instead.

> By googling I found that skill and snice are no longer built by default. The only place where someone has noted it was on the arch mailing list. Anyway, a bit annoying that some scripts depending on skill stopped working.

Re-enabled "for the sake of scripts depending on it" I guess, and a decade later still nobody remembers this is being overridden to revisit the situation.

**Comment by emanuele6** [comment]
@eli-schwartz opensuse, fedora, and debian off the top of my head.

**Comment by floppym** [comment]
To clarify, I don't object to adding a USE flag for this if there's a reason you need these commands, or if they do something that would really be useful for multiple people.

I just question if it makes sense to add a USE flag for a single user just to make your Gentoo system look slightly more like Debian/Fedora/SUSE.

If someone else wants to merge this without justification I wont block it.

**Comment by emanuele6** [comment]
> I just question if it makes sense to add a USE flag for a single user just to make your Gentoo system look slightly more like Debian/Fedora/SUSE.

Are you calling me a Debian poser? :o
What do you mean? I just want `snice`.

**Comment by eli-schwartz** [comment]
I also don't really object to the USE flag per se, it's just that my reading of both distros where it is possible to look for change history, indicate that `skill` was enabled very early on in the deprecation process and in a manner that makes it fairly evident that the motivating concern was avoiding breakage in scripts that haven't been updated to use e.g. pkill.

The argument in favor of adding a USE flag to Gentoo is... what, exactly? "I just want to use it" -- but upstream tells you not to use it? So *why* do you want to use it? Are there interesting features only it has?

**Comment by emanuele6** [comment]
@eli-schwartz 
> The argument in favor of adding a USE flag to Gentoo is... what, exactly? "I just want to use it" -- but upstream tells you not to use it? So *why* do you want to use it? Are there interesting features only it has?

You are forgetting that portage doesn't give me a way to install those tools using `EXTRA_ECONF=--enable-skill` while using `FEATURES=getbinpkg`. https://bugs.gentoo.org/463964

Procps-ng only discourages using these tools for scripts that are meant to be portable, and the commit that has been link just says that installing these tools by default is discouraged. Extending that to mean you are discouraged from using these tools interactively or installing them intentionally is quite ludicrous.
Why would I not want to use `snice` and instead reinvent a script with `pgrep` that does a similar thing probably not as well for interactive process management? It is a very convenient tool to modify the niceness of processes based on namespace, user, tty, etc.

**Comment by floppym** [comment]
> Why would I not want to use snice and instead reinvent a script with pgrep that does a similar thing probably not as well for interactive process management? It is a very convenient tool to modify the niceness of processes based on namespace, user, tty, etc.

Thanks for explaining. That's good enough for me.

**Comment by eli-schwartz** [comment]
I concur. Thanks for elaborating on why you'd find this option useful.

**Comment by emanuele6** [comment]
Thank you for making my process management easier! \\o/

**Pull request closed without merging**
