### PR TITLE
dev-util/bats: bump to 1.1.0

### PR DESCRIPTION
**Pull request by hoefling**
* bump to EAPI 7
* use bats-core repo https://github.com/bats-core/bats-core
  to fetch sources instead of the abandoned https://github.com/sstephenson/bats
* updated headers for all bats ebuilds

Package-Manager: Portage-2.3.66, Repoman-2.3.14

### CODE REVIEW

**Comment by ntnn** [comment]
Poly-C and I discussed switching to bats-core previously and came to the conclusion to wait to see if the project survives.

So far it hasn't strayed drastically from the original project from sstephenson. Most of the changes were related to documentation or travis configuration.

We're not opposed to providing bats-core, but then rather as a separate package.

On a more personal note: I don't think the fork is going anywhere. I've made a feature PR in 2017 and rebased it in mid-2018: https://github.com/bats-core/bats-core/pull/27
And there are many more PRs like that.

**Comment by hoefling** [comment]
Oh ok, I wasn't that original then :-) Thank you for the clarification, let's close this PR. The reason I have suggested it was that I recently started to work on a custom formatter for `bats` that uses Gentoo's `e*` functions (`ebegin`, `eend`, `eerror` etc) and wanted to bump the package to the current version before suggesting any new changes to the `bats-core` upstream; will reconsider that now, though. Maybe a patchset stored along with the ebuild in the overlay is a better idea.

**Comment by Chiitoo** [comment]
Closing per request(s) (you should be able to do it yourself, too).

Regardless, thank you for your first contribution (here)!

**Comment by henning-schild** [comment]
I have to disagree here. The fork has substantial changes that gentoo users might want to receive. A notable change is in the TAP format that changed its "skip" syntax. I do not know the details of the changes, probably a new "TAP-standard". But today i found myself needing a more recent bats to be able to post-process its output ... using tools outside the scope of gentoo, it was another container taking the output to make CI look nice ... But CI of a pipeline in which gentoo bats was outdated!

In the end i ended up taking the latest git commit of "bats-core" because it contains another very valuable feature ... timing of tests and junit output format. That is what you need for gitlab ... probably github and others as well. I expect them to release > 1.2.0 anytime soon ... so they are not dead. And i will happily bump when they come out with the next release.

Please reconsider the switch to that fork and the bumping.

**Comment by henning-schild** [comment]
In fact the current version of `bats` has its issues as well and certainly is not maintained anymore ... So switch and shift the problem to another "not good upstream" would not make it much worse ...

**Comment by henning-schild** [comment]
After all we have at least two gentoo contributors willing to work on that, who knows how many gentoo users might be interested as well.

**Comment by sublimino** [comment]
As the sole maintainer of `bats-core` I agree that changes are not being reviewed and merged quickly, which as ever is due to my time constraints : ]

There is a general inertia for others to test and review PRs, although people do and I am deeply grateful, but in lieu of a wider team I have prioritised major changes (parallelism, junit formatting, spec timing, OSX compatibility). I am also attempting to be militant about backwards-compatibility where practical, which also slows things down.

`1.2.1` will be cut shortly and should be stable enough for an `LTS`-like release. HTH.

**Comment by henning-schild** [comment]
Cool, thanks! So we have a reasonably well maintained project with a maintainer that even goes downstream. Awesome!

I want 1.2.0 in gentoo and am looking forward to 1.2.1 and the junit support.

**Pull request closed without merging**
