### PR TITLE
sys-power/thermald: version bump 1.5.3, drop old

### PR DESCRIPTION
**Pull request by lkraav**

### CODE REVIEW

**Comment by lkraav** [comment]
Ping

**Comment by monsieurp** [comment]
@lkraav hi. it is your responsibility to let maintainer(s) know of opened PR as highlighted in https://wiki.gentoo.org/wiki/Gentoo_Github#Ping_maintainers.

**Comment by monsieurp** [comment]
@dlan17

**Comment by monsieurp** [comment]
but I'm a nice guy so I'm doing it instead.

**Comment by lkraav** [comment]
Aha, I'll keep that in mind. Thanks.

**Comment by ofree** [comment]
@lkraav , I've pushed this, many thanks, but something I'd like to you learn ;-)
1) the $PACHES should removed in 1.5.3 (better compile & test), make sure the ebuild work
2) I'd like "one thing per commit". since we're using git, better take advantage of it. try a) bump new b) drop old. we may revert any of them if we find something wrong..
3) I'm less aggressive ;-) , I always keep at least one old ebuild.

**Comment by dlan17** [comment]
@lkraav , I've pushed this, many thanks, but something I'd like to you learn ;-)
1) the $PACHES should removed in 1.5.3 (better compile & test), make sure the ebuild work
2) I'd like "one thing per commit". since we're using git, better take advantage of it. try a) bump new b) drop old. we may revert any of them if we find something wrong..
3) I'm less aggressive ;-) , I always keep at least one old ebuild.

**Comment by lkraav** [comment]
Yeah, it looks like I did miss the `$PATCHES` part.

With appropriately timed bumps, keeping one old definitely makes sense. `1.4.x` is so ancient by now though, that's why I killed it.

One thing per commit, in general yes, I haven't inspected the tree flow enough yet - does everybody really drop old in separate commits all the time? Doesn't feel like there's too much win to be had vs the noise + effort, but I could be wrong.

**Pull request closed without merging**
