### PR TITLE
app-emulation/xen-tools: Added selinux USE flag

### PR DESCRIPTION
**Pull request by jpds**

### CODE REVIEW

**Comment by hydrapolic** [comment]
LGTM, but I don't use selinux with xen, please @perfinion add your notes, thanks.

**Comment by jpds** [comment]
@hydrapolic I think we can drop the `flask` USE flag for xen-tools - it's only really needed for xen itself; but I can't test this as https://bugs.gentoo.org/800935 is blocking me there.

**Comment by hydrapolic** [comment]
Done in https://github.com/gentoo/gentoo/pull/22270

**Comment by jpds** [comment]
@hydrapolic Pushed a commit up as I didn't see this in `::gentoo` directly - closing this one now, thanks.

**Comment by hydrapolic** [comment]
> @hydrapolic Pushed a commit up as I didn't see this in `::gentoo` directly - closing this one now, thanks.

It's not merged yet, thanks for this PR.

**Pull request closed without merging**
