### PR TITLE
dev-java/slf4j-{api,ext,log4j12,nop,simple}: bump to 1.7.30

### PR DESCRIPTION
**Pull request by vaukai**
Needed for dev-java/velocity-2.3 upgrade

### CODE REVIEW

**Comment by vaukai** [comment]
`slf4j-ext` has ugly dependencies not compiling with `openjdk:11`:
https://bugs.gentoo.org/779703 
https://bugs.gentoo.org/779472
But it seems that `slf4j-ext` itself has no reverse dependencies. So we might consider last-riting it.

**Comment by Dessa** [comment]
commons-lang is just an easy sed (which other distros appear to be doing), the other one im not so sure about

**Comment by vaukai** [comment]
> commons-lang is just an easy sed to 3 (which other distros appear to be doing) https://src.fedoraproject.org/rpms/slf4j/c/06831a1cfd01cbb008710f7fdfff97c89f9de477?branch=rawhide, 
>
Are you saying to patch `slf4j-ext`'s [`pom.xml`](https://github.com/qos-ch/slf4j/blob/0b97c416e42a184ff9728877b461c616187c58f7/slf4j-ext/pom.xml#L43-L48)?  
Please provide `groupId`, `artifactId` and `version`.

> the other one im not so sure about; maybe just a target/source change? it worked with 1.8 / 1.8 but im also still on icedtea)
> 
`jdk:9` is not the problem here. Can you fix those bugs for `jdk:11`?

> also a jss bump needs slf4j-jdk14 but thats probably for another day

Who's asking for [a jss bump?](https://bugs.gentoo.org/721052#c6)

**Comment by fordfrog** [comment]
@vaukai cool, thanks! i just had an issue with `dev-java/cal10n` which is set for java 5 and so doesn't compile with java 11.

**Comment by vaukai** [comment]
> @vaukai cool, thanks! i just had an issue with `dev-java/cal10n` which is set for java 5 and so doesn't compile with java 11.

@fordfrog For that package I already created https://bugs.gentoo.org/779703
What do you think about completely tossing that package along with the dependency?  Would anyone be missing it?

**Comment by fordfrog** [comment]
> > @vaukai cool, thanks! i just had an issue with `dev-java/cal10n` which is set for java 5 and so doesn't compile with java 11.
> 
> @fordfrog For that package I already created https://bugs.gentoo.org/779703
> What do you think about completely tossing that package along with the dependency? Would anyone be missing it?

@vaukai no, it's ok to lastrite both, no deps afaics.

**Comment by vaukai** [comment]
> @vaukai no, it's ok to lastrite both, no deps afaics.

Will you do? I'm not familiar with the procedure ...

**Comment by fordfrog** [comment]
@vaukai ok, will put that on my list. anyway, just for reference for you: https://devmanual.gentoo.org/ebuild-maintenance/removal/

**Comment by fordfrog** [comment]
@vaukai both masked

**Comment by vaukai** [comment]
@fordfrog 
Back to `slf4j-simple`. Trying to remove the test restriction:
```
>>> Test phase: dev-java/slf4j-simple-1.7.30
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:slf4j-simple.jar://usr/share/junit-4/lib/junit.jar://usr/share/slf4j-api/lib/slf4j-api.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar://usr/share/slf4j-api/lib/slf4j-api.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/helpers/SimpleLoggerMultithreadedInitializationTest.java:37: error: cannot find symbol
public class SimpleLoggerMultithreadedInitializationTest extends MultithreadedInitializationTest {
                                                                 ^
  symbol: class MultithreadedInitializationTest
slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/helpers/SimpleLoggerMultithreadedInitializationTest.java:47: error: cannot find symbol
    final String loggerName = this.getClass().getName();
                                  ^
  symbol: method getClass()
slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/helpers/SimpleLoggerMultithreadedInitializationTest.java:52: error: cannot find symbol
        System.out.println("THREAD_COUNT=" + THREAD_COUNT);
                                             ^
  symbol:   variable THREAD_COUNT
  location: class SimpleLoggerMultithreadedInitializationTest
slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/helpers/SimpleLoggerMultithreadedInitializationTest.java:65: error: method does not override or implement a method from a supertype
    @Override
    ^
slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/helpers/SimpleLoggerMultithreadedInitializationTest.java:70: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: slf4j-v_1.7.30/slf4j-simple/src/test/java/org/slf4j/InvocationTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
5 errors
```
Just found the missing `MultithreadedInitializationTest` in [slf4j-api-1.7.30-tests.jar](https://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.30/).

Need to solve [this instead of excluding it](https://github.com/gentoo/gentoo/pull/20210/commits/af177283eb7428690a372be592fea063851d5b60#diff-d890deaf1bef352b58b1028e60e14bf9958cb658fac677d2e01bd5dadc27451aR43-R44).

**Comment by fordfrog** [comment]
@vaukai nice :-) so the helper needs to be part of the api jar? that'd sound weird... or can you just copy it to `slf4j-simple` test sources to make it work?

**Comment by vaukai** [comment]
> @vaukai nice :-) so the helper needs to be part of the api jar? 

I'm far from understanding.  
Does it need to create two jars, `api.jar` and `api-tests.jar`?
All I understand is, `Failures: 4` in slf4j-api needs to be solved.

Can we ignore the `java.lang.IllegalStateException:`?
And exlude those (3 x) `ExceptionInInitializerError`, `Caused by: java.lang.UnsupportedOperationException`?

The main problem seems to be the `java.lang.InstantiationException`. 
What's going on there?  Looks even worse to me than snakeyaml

Is it all caused by `org.junit.runners`, something wrong in `junit`?

> that'd sound weird... or can you just copy it to `slf4j-simple` test sources to make it work?

Not really clear for me what you mean. Sorry
```
3 warnings
>>> Source compiled.
>>> Test phase: dev-java/slf4j-api-1.7.30
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:slf4j-api.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
JUnit version 4.13.2-SNAPSHOT
............E.E.E.............................I.......SLF4J: Failed toString() invocation on an object of type [org.slf4j.helpers.MessageFormatterTest$1]
Reported exception:
java.lang.IllegalStateException: a
        at org.slf4j.helpers.MessageFormatterTest$1.toString(MessageFormatterTest.java:147)
        at org.slf4j.helpers.MessageFormatter.safeObjectAppend(MessageFormatter.java:277)
        at org.slf4j.helpers.MessageFormatter.deeplyAppendParameter(MessageFormatter.java:249)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:211)
        at org.slf4j.helpers.MessageFormatter.arrayFormat(MessageFormatter.java:161)
        at org.slf4j.helpers.MessageFormatter.format(MessageFormatter.java:124)
        at org.slf4j.helpers.MessageFormatterTest.testExceptionIn_toString(MessageFormatterTest.java:150)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:61)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
.....E....
Time: 0.046
There were 4 failures:
1) testMDC(org.slf4j.NoBindingTest)
java.lang.ExceptionInInitializerError
        at org.slf4j.MDC.bwCompatibleGetMDCAdapterFromBinder(MDC.java:99)
        at org.slf4j.MDC.<clinit>(MDC.java:108)
        at org.slf4j.NoBindingTest.testMDC(NoBindingTest.java:49)
        ... 32 trimmed
Caused by: java.lang.UnsupportedOperationException: This code should never make it into the jar
        at org.slf4j.impl.StaticMDCBinder.<init>(StaticMDCBinder.java:43)
        at org.slf4j.impl.StaticMDCBinder.<clinit>(StaticMDCBinder.java:40)
        ... 36 more
2) testLogger(org.slf4j.NoBindingTest)
java.lang.ExceptionInInitializerError
        at org.slf4j.LoggerFactory.bind(LoggerFactory.java:150)
        at org.slf4j.LoggerFactory.performInitialization(LoggerFactory.java:124)
        at org.slf4j.LoggerFactory.getILoggerFactory(LoggerFactory.java:417)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:362)
        at org.slf4j.LoggerFactory.getLogger(LoggerFactory.java:388)
        at org.slf4j.NoBindingTest.testLogger(NoBindingTest.java:42)
        ... 32 trimmed
Caused by: java.lang.UnsupportedOperationException: This code should have never made it into slf4j-api.jar
        at org.slf4j.impl.StaticLoggerBinder.<init>(StaticLoggerBinder.java:63)
        at org.slf4j.impl.StaticLoggerBinder.<clinit>(StaticLoggerBinder.java:44)
        ... 39 more
3) testMarker(org.slf4j.NoBindingTest)
java.lang.ExceptionInInitializerError
        at org.slf4j.MarkerFactory.bwCompatibleGetMarkerFactoryFromBinder(MarkerFactory.java:61)
        at org.slf4j.MarkerFactory.<clinit>(MarkerFactory.java:71)
        at org.slf4j.NoBindingTest.testMarker(NoBindingTest.java:55)
        ... 32 trimmed
Caused by: java.lang.UnsupportedOperationException: This code should never make it into the jar
        at org.slf4j.impl.StaticMarkerBinder.<init>(StaticMarkerBinder.java:51)
        at org.slf4j.impl.StaticMarkerBinder.<clinit>(StaticMarkerBinder.java:48)
        ... 36 more
4) multiThreadedInitialization(org.slf4j.helpers.MultithreadedInitializationTest)
java.lang.InstantiationException
        at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:250)
        at org.junit.runners.BlockJUnit4ClassRunner.createTest(BlockJUnit4ClassRunner.java:260)
        at org.junit.runners.BlockJUnit4ClassRunner$2.runReflectiveCall(BlockJUnit4ClassRunner.java:309)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.BlockJUnit4ClassRunner.methodBlock(BlockJUnit4ClassRunner.java:311)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
        at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 59,  Failures: 4
```

**Comment by fordfrog** [comment]
@vaukai i'd first concentrate on these `This code should have never made it into slf4j-api.jar`. looking at the content of the jar, it also contains implementation classes which is obviously wrong.

**Comment by vaukai** [comment]
> i'd first concentrate on these `This code should have never made it into slf4j-api.jar`. looking at the content of the jar, it also contains implementation classes which is obviously wrong.

It should be ignored, right?  The `pom.xml` says
```
          <ignores>
            <ignore>org.slf4j.impl.StaticMDCBinder</ignore>
            <ignore>org.slf4j.impl.StaticLoggerBinder</ignore>
            <ignore>org.slf4j.impl.StaticMarkerBinder</ignore>
          </ignores>
``` 
So how to translate this `ignore` directive to the ebuild?  
Deleting the whole directory as shown in `<tasks/>` is possible only after compilation, but then the `.jar` file already exists.
```
          <tasks>
            <echo>Removing slf4j-api's dummy StaticLoggerBinder and StaticMarkerBinder</echo>
            <delete dir="target/classes/org/slf4j/impl"/>
          </tasks>
```
And then, it seems the `.jar` is missing some maven stuff.  Do we need to add it?

**Comment by fordfrog** [comment]
@vaukai just delete the whole `impl` directory in `src_prepare`. it should not be needed for the api, that would not make much sense imo. iirc maven stuff in the jar is mostly just a metadata, usually not needed.

**Comment by vaukai** [comment]
> @vaukai just delete the whole `impl` directory in `src_prepare`. 
```
src_prepare() {
    default
    java-pkg_clean
    rm -r "${JAVA_SRC_DIR}/org/slf4j/impl" || die
}
```
Already tried, but it leads to:
```
warning: [options] bootstrap class path not set in conjunction with -source 8
src/main/java/org/slf4j/MarkerFactory.java:29: error: package org.slf4j.impl does not exist
import org.slf4j.impl.StaticMarkerBinder;
                     ^
src/main/java/org/slf4j/MDC.java:33: error: package org.slf4j.impl does not exist
import org.slf4j.impl.StaticMDCBinder;
                     ^
src/main/java/org/slf4j/LoggerFactory.java:42: error: package org.slf4j.impl does not exist
import org.slf4j.impl.StaticLoggerBinder;
                     ^
src/main/java/org/slf4j/MarkerFactory.java:61: error: cannot find symbol
            return StaticMarkerBinder.getSingleton().getMarkerFactory();
                   ^
  symbol:   variable StaticMarkerBinder
  location: class MarkerFactory
src/main/java/org/slf4j/MarkerFactory.java:64: error: package StaticMarkerBinder does not exist
            return StaticMarkerBinder.SINGLETON.getMarkerFactory();
                                     ^
src/main/java/org/slf4j/MDC.java:99: error: cannot find symbol
            return StaticMDCBinder.getSingleton().getMDCA();
                   ^
  symbol:   variable StaticMDCBinder
  location: class MDC
src/main/java/org/slf4j/MDC.java:102: error: package StaticMDCBinder does not exist
            return StaticMDCBinder.SINGLETON.getMDCA();
                                  ^
src/main/java/org/slf4j/LoggerFactory.java:150: error: cannot find symbol
            StaticLoggerBinder.getSingleton();
            ^
  symbol:   variable StaticLoggerBinder
  location: class LoggerFactory
src/main/java/org/slf4j/LoggerFactory.java:268: error: cannot find symbol
            String requested = StaticLoggerBinder.REQUESTED_API_VERSION;
                               ^
  symbol:   variable StaticLoggerBinder
  location: class LoggerFactory
src/main/java/org/slf4j/LoggerFactory.java:349: error: cannot find symbol
            Util.report("Actual binding is of type [" + StaticLoggerBinder.getSingleton().getLoggerFactoryClassStr() + "]");
                                                        ^
  symbol:   variable StaticLoggerBinder
  location: class LoggerFactory
src/main/java/org/slf4j/LoggerFactory.java:423: error: cannot find symbol
            return StaticLoggerBinder.getSingleton().getLoggerFactory();
                   ^
  symbol:   variable StaticLoggerBinder
  location: class LoggerFactory
Note: src/main/java/org/slf4j/helpers/BasicMarker.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
11 errors
```

**Comment by fordfrog** [comment]
@vaukai ok, so it seems you have to remove the compiled files from the created jar, not before compilation.

**Comment by vaukai** [comment]
> @vaukai ok, so it seems you have to remove the compiled files from the created jar, not before compilation.

I will try that.

And for the other one, I found [this reference](https://www.cis.upenn.edu/~bcpierce/courses/629/jdkdocs/api/java.lang.InstantiationException.html).  Would this help to fix it?
```
1) multiThreadedInitialization(org.slf4j.helpers.MultithreadedInitializationTest)
java.lang.InstantiationException
        at java.base/jdk.internal.reflect.InstantiationExceptionConstructorAccessorImpl.newInstance(InstantiationExceptionConstructorAccessorImpl.java:48)
```

**Comment by fordfrog** [comment]
@vaukai i will have to check the code...

**Comment by fordfrog** [comment]
@vaukai could you please create a new pr where we could work on resolving the tests?

**Comment by vaukai** [comment]
> @vaukai could you please create a new pr where we could work on resolving the tests?

https://github.com/gentoo/gentoo/pull/20305

**Pull request closed without merging**
