### PR TITLE
app-i18n/uchardet: Fix SSE2 usage on x86

### PR DESCRIPTION
**Pull request by Whissi**
Closes: https://bugs.gentoo.org/631852

### CODE REVIEW

**Comment by Coacher** [comment]
Why per-package? This affects everything x86.

**Comment by trofi** [comment]
What I don't like about this fix is that `append-flags -ffloat-store` makes code less precise by truncating 80-bit values down to 64 (and does it in very unpredictable places).

Is there more information why test actually fails? (What are the actual/expected values for test)
Does test expect bit-for-bit compatibility with IEEE float64? That sounds wrong.

**Comment by Coacher** [comment]
@trofi, please check out the discussion at https://bugs.freedesktop.org/show_bug.cgi?id=101033

**Comment by trofi** [comment]
Unfortunately I don't see any details there if the failure real or test just does precise floating point comparison.

Bug discusses workarounds but does not tell what does test do. Does test yield incorrect data
or just slightly different? What kind of incorrectness it is? Or I've completely missed breakage
mechanics described there.

**Comment by trofi** [comment]
From what I have poked around the failing test:

```bash
$ LD_LIBRARY_PATH=$(pwd)/src /dev/shm/portage/app-i18n/uchardet-0.0.6/work/uchardet-0.0.6_build/test/uchardet-tests /dev/shm/portage/app-i18n/uchardet-0.0.6/work/uchardet-0.0.6/test/th/tis-620.txt
```
yields two "different" probers: `Tis_620ThaiModel` and `Iso_8859_11ThaiModel` yielding exactly the same values in `float nsSBCSGroupProber::GetConfidence(void)`:

```c++
float nsSBCSGroupProber::GetConfidence(void)
{
  PRUint32 i;
  float bestConf = 0.0, cf;

  switch (mState)
  {
  case eFoundIt:
    return (float)0.99; //sure yes
  case eNotMe:
    return (float)0.01;  //sure no
  default:
    for (i = 0; i < NUM_OF_SBCS_PROBERS; i++)
    {
      if (!mIsActive[i])
        continue;
      cf = mProbers[i]->GetConfidence();
      if (bestConf < cf)
      {
        bestConf = cf;
        mBestGuess = i;
      }
    }
  }
  return bestConf;
}
```

Note the strict float comparison here in `if (bestConf < cf)`. That code is unstable on the following value:

```
13/35: confidence is 0.618840
14/35: confidence is 0.618840
```

I don't have the confidence this code will work correctly on sse2 either on different input data.


To fix it properly there perhaps should be comparison against some error margin like `if (cf - bestConf > some_epsilon)` to make the output stable.

Random post from internetz: http://www.cygnus-software.com/papers/comparingfloats/Comparing%20floating%20point%20numbers.htm

**Comment by Jehan** [comment]
Hello!

Thanks for the patch upstream, but I don't think this to be the right solution.

> To fix it properly there perhaps should be comparison against some error margin like if (cf - bestConf > some_epsilon) to make the output stable.

Comparing with epsilon is usually good when you check for equality. Actually even the link you gave earlier (as well as its [updated version](https://randomascii.wordpress.com/2012/02/25/comparing-floating-point-numbers-2012-edition/)) only deals about comparing for equality:

> Random post from internetz: http://www.cygnus-software.com/papers/comparingfloats/Comparing%20floating%20point%20numbers.htm

It does not say anything about comparing to know which one is the higher. And actually I don't think there are much cases to use epsilon comparisons other than for equality (well I can imagine a few cases actually, but ours - trying to get the encoding with max confidence - is definitely not one of these).
As I explained on upstream bug report, a good counter-example to see that this fix is problematic is that the result would change depending on the order of the tests.

As a conclusion, to make the output stable, we should just make sure that the computation accuracy stays the same (i.e. IEEE floating point standard) with the proper compilation flags.

**Comment by mgorny** [comment]
FWICS the relevant bug has been fixed with a backport, so closing this as well.

**Pull request closed without merging**
