### PR TITLE
app-emulation/wine: Fix ebuild bug with !abi_x86_64

### PR DESCRIPTION
**Pull request by a17r**
See also: https://bugs.gentoo.org/show_bug.cgi?id=585250

@NP-Hardass

### CODE REVIEW

**Comment by NP-Hardass** [comment]
No pork belly please. Drop the commit rearranging the USE flags

**Comment by a17r** [comment]
I still think it should be done, but there you go.

**Comment by austin987** [comment]
It probably should, but as a separate commit.

**Comment by austin987** [comment]
@a17r / @NP-Hardass I saw this issue before my patch as well, but this patch doesn't help for me. I suspect it's an issue on my system though, so don't block on account of me. I'll try to dig into this afternoon.

**Comment by a17r** [comment]
I can add a seperate PR for the already seperate commit any time, if you wish. ;)

**Comment by austin987** [comment]
I just noticed it was a separate commit, my bad :).

Anyway, I agree it should be done, but I'll leave the commit / PR splitting decisions to @NP-Hardass.

**Comment by NP-Hardass** [comment]
Regarding the reordering, I'm OK with a separate PR for that. Only change from what I recall was in your original commit, the abi_x86_32? block should be last as blockers are usually the last part of a DEPEND block.

**Pull request closed without merging**
