### PR TITLE
www-apps/gitea: version bump

### PR DESCRIPTION
**Pull request by nemunaire**
Hi,

This PR includes `npm` as a [new requirement](https://blog.gitea.io/2020/02/gitea-1.11.0-is-released/) to build the 1.11 branch and above.

Switching to `emake -j1`, because the Makefile doesn't handle dependency (and without that, frontend parts are not build before the embedding of frontend assets) and in any case, the real build parallelism is handle by the go compiler itself.

We can eventually avoid the dependency with npm, because the given archive already contains compiled frontend assets. Perhaps we can add a USE flag for that?

### CODE REVIEW

**Comment by juippis** [comment]
It'd be good if you could avoid npm. Is it possible now? Was a bit unclear from your message. 

The error needs to be handled, check https://github.com/gentoo/gentoo/blob/master/profiles/arch/amd64/x32/package.mask

**Comment by holgersson32644** [comment]
Avoiding npm is possible now with a new(?) make target. I added a bump patch to the bug at bugs.gentoo.org.

**Comment by holgersson32644** [comment]
@nemunaire and @juippis, 1.11.5 was released two days ago: https://github.com/go-gitea/gitea/releases

**Comment by nemunaire** [comment]
Here is a solution to don't force the requirement of `npm` and the `nodejs` stack: I added a USE flag `build-client`, disabled by default: with it enabled, it will built the client/frontend part, otherwise, it uses precompiled JS provided by the Gitea team.

**Pull request closed without merging**
