### PR TITLE
kde-plasma/plasma-desktop: Fix task icons w/ >=KF-5.19

### PR DESCRIPTION
**Pull request by a17r**
@gentoo/kde

### CODE REVIEW

**Comment by johu** [comment]
why is the one patch camel cased?

**Comment by a17r** [comment]
fixed patch name

**Comment by a17r** [comment]
Tested plasma-desktop-5.5.5-r1 successfully with KF 5.19. What's missing is trying out the KF 5.18 backport.

**Comment by kensington** [comment]
Thanks, picked as d45e4e9f309fad5d9687d86f7209203e9c835b4d...a29e51d47b0acbf2794829e48da596d43b3c8820.

I reordered the commits slightly so that the USE mask comes before the flag itself is introduced.

**Pull request closed without merging**
