### PR TITLE
media-tv/plex-media-server: add 1.40.5.8921 (and drop old)

### PR DESCRIPTION
**Pull request by joecool1029**
I have a stablereq pending on the last release, this drops all the old unstable releases as well as adding the new public release. 

Release notes thread: https://forums.plex.tv/t/plex-media-server/30447/642

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by joecool1029** [comment]
added the old stable to the drop and rebased since new one was stabilized in the tree.

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Your drop commit dropped the last arm64 stable, so I didn't merge it. Version bump is merged. Please do that again once arm64 has finished stabilization :)

**Comment by joecool1029** [comment]
They said arm64 was done https://bugs.gentoo.org/938717

**Comment by juippis** [comment]
Oh, my bad, my tree was apparently a minute outdated. I'll merge the drop commit!

**Comment by joecool1029** [comment]
Thanks!

**Pull request closed without merging**
