### PR TITLE
app-forensics/yara: add 4.5.0

### PR DESCRIPTION
**Pull request by hamarituc**

### CODE REVIEW

**Comment by thesamesam** [comment]
What's https://github.com/gentoo/gentoo/pull/35328/commits/9ef8e7188ab950c404ecf7f65cbe7d9fecbcce3d about? It needs some description (see https://devmanual.gentoo.org/general-concepts/manifest/index.html#updating-manifest-files).

**Comment by hamarituc** [comment]
> What's [9ef8e71](https://github.com/gentoo/gentoo/commit/9ef8e7188ab950c404ecf7f65cbe7d9fecbcce3d) about? It needs some description (see https://devmanual.gentoo.org/general-concepts/manifest/index.html#updating-manifest-files).

Sorry, for not commenting this PR. For some reason upstream did a re-release of the version which changed the checksum. When I remember correctly the original release was flagged as pre-release in GitHub whereas the current release is a normal release.

**Comment by thesamesam** [comment]
Can you put that in the commit message please?

**Comment by hamarituc** [comment]
> Can you put that in the commit message please?
> 
> Once that's done, please ping me (either here on IRC) and I'll get this in.

*ping* :bellhop_bell:

**Comment by thesamesam** [comment]
Thanks!

BTW, with the new tarball:
```
>>> Preparing source in /var/tmp/portage/dev-python/yara-python-4.4.0/work/yara-python-4.4.0 ...
 * Applying yara-python-4.4.0-python3_12.patch ...
patching file tests.py
Hunk #1 FAILED at 719.
1 out of 1 hunk FAILED -- saving rejects to file tests.py.rej                                                                                                                     [ !! ]
 * ERROR: dev-python/yara-python-4.4.0::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/dev-python/yara-python-4.4.0/files/yara-python-4.4.0-python3_12.patch
 *
```

**Pull request closed without merging**
