### PR TITLE
dev-util/patchelf,dev-lua/{luajson,lua-bit32,luaposix}: keywording ~riscv 

### PR DESCRIPTION
**Pull request by wiredhikari**

### CODE REVIEW

**Comment by winterheart** [comment]
OK from me on my packages.

**Comment by ConiKost** [comment]
Did you tested yourself on riscv?

**Comment by wiredhikari** [comment]
> Did you tested yourself on riscv?

I have tested on gentoo prefix on riscv.

**Comment by chewi** [comment]
Just to be extra clear, have you run the tests? patchelf has some very architecture-specific quirks.

**Comment by wiredhikari** [comment]
> Just to be extra clear, have you run the tests? patchelf has some very architecture-specific quirks.

I have tested with `FEATURES="test"` and 45/45 tests passed successfully.

**Review by chewi — APPROVED** [review]

**Pull request closed without merging**
