### PR TITLE
nt-misc/streamlink: bump version & add python 3_6 compat to 9999 ebuild

### PR DESCRIPTION
**Pull request by oczkers**
No changes at all, i've just bumped version, add compatibility flag and test.

### CODE REVIEW

**Comment by mgorny** [comment]
Have you looked whether any dependencies have changed?

@soredake, please review.

**Comment by oczkers** [comment]
> Have you looked whether any dependencies have changed?

Nothing has changed here since 0.9.0
https://github.com/streamlink/streamlink/commits/master/setup.py

**Comment by soredake** [comment]
@mgorny looks good.

**Comment by mgorny** [comment]
Merged, thanks!

**Pull request closed without merging**
