### PR TITLE
net-dns/bind-tools: gost requires openssl 1.0 or dev-libs/gost-engine

### PR DESCRIPTION
**Pull request by candrews**
Closes: https://bugs.gentoo.org/669504
Signed-off-by: Craig Andrews <candrews@gentoo.org>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by idl0r** [comment]
Looks good to me. We should change net-dns/bind as well.

**Comment by candrews** [comment]
> Looks good to me. We should change net-dns/bind as well.

Sounds good - want me to amend this PR with a commit doing that or create another PR?

**Comment by idl0r** [comment]
> > Looks good to me. We should change net-dns/bind as well.
> 
> Sounds good - want me to amend this PR with a commit doing that or create another PR?

That'd be awesome! Either way works for me. Thanks!

**Comment by candrews** [comment]
I've added a commit to this PR for bind

**Comment by juippis** [comment]
Sorry for jumping in like this, but quickly glancing through I see **at least** 10 external commands missing `|| die` in here. When we commit through proxy maint project we are advised not to use `rm -f`, well, since it never fails and "we ought to know what we're removing". 

With EAPI-7 `virtual/pkgconfig` belongs under BDEPEND as well. 

As I said, sorry for stucking my nose in here, just wanted to give my input of some standards required from us :)

**Comment by juippis** [comment]
@candrews umm, sure, I can in ~10 hours. I'll ping you in the PR again, then. I'll ask ahead: Do we agree those changes don't require a revbump? :)

**Comment by candrews** [comment]
Perhaps? Let's see the changes then decide for sure :)

**Pull request closed without merging**
