### PR TITLE
mail-client/bower: bump to version 0.11

### PR DESCRIPTION
**Pull request by rseichter**
Upstream release 0.11.

### CODE REVIEW

**Comment by juippis** [comment]
Noo don't use `git mv` but make a fresh copy of a file, and delete the previous in a separate commit.

**Comment by rseichter** [comment]
I did not actually use `git mv`, but I did squash my commits. Apparently Git decided to represent this as a rename operation, which is understandable, given that the file contents are identical.

**Comment by juippis** [comment]
There's something one of us isnt seeing here. To me, it looks like the old file gets deleted (check Manifest file) and new one isn't identical (like, DESCRIPTION changes and COMMON_DEPEND introduced). If this is truly the case, could you split the commit into two? Or is my Github view somehow messing it up... I only see one commit.

**Comment by rseichter** [comment]
I squashed two commits because I forgot to remove the "A" in DESCRIPTION in the first commit. I did not introduce COMMON_DEPEND in 0.11. GitHub just seems to be confused, presenting diffs between obsolete ebuild 0.9 and 0.11 instead of 0.10 and 0.11. Here is what `diff` shows me:
```shell
$ diff bower-0.10.ebuild bower-0.11.ebuild
8c8
< DESCRIPTION="A curses terminal client for the Notmuch email system"
---
> DESCRIPTION="Curses terminal client for the Notmuch email system"
14c14
< KEYWORDS="amd64"
---
> KEYWORDS="~amd64"
```
So, the only difference between 0.10 (stable) and 0.11 are KEYWORDS and the article "A" in the description. I don't see what I could do to de-confuse GitHub.

**Comment by juippis** [comment]
```
git reset --hard HEAD~1
wget https://raw.githubusercontent.com/gentoo/gentoo/8a2af298fc3fbbaed3a83fe651f7d34dbbeaea54/mail-client/bower/bower-0.11.ebuild
repoman manifest
git add Manifest bower-0.11.ebuild
repoman ci
git rm bower-0.9.ebuild
repoman manifest
git add Manifest
repoman ci
```
Note that repoman ci generates and commits the Manifest file, but I really use it for automated `cat/pkg: ` messages.

All in all you want to do: 
```
vim newfile.ebuild
generate manifest
git add Manifest newfile.ebuild
git commit
git rm oldfile.ebuild
generate manifest
git add Manifest
git commit
```

**Comment by rseichter** [comment]
Looks OK to me now, thanks for the pointers. In the future, I need to be more selective about when and when not to squash commits.

**Comment by juippis** [comment]
Thanks!

```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * curs.m:772:10: warning: implicit declaration of function ‘get_wch’; did you mean ‘getwc’? [-Wimplicit-function-declaration]
 * Please do not file a Gentoo bug and instead report the above QA
 * issues directly to the upstream developers of this software.
 * Homepage: https://github.com/wangp/bower
```
if you havent already, this should be reported to upstream.

**Pull request closed without merging**
