### PR TITLE
Bump x11-terms/terminator version to 1.91

### PR DESCRIPTION
**Pull request by DanBUK**

### CODE REVIEW

**Comment by candrews** [comment]
The homepage, http://www.tenshu.net/p/terminator.html , returns an error. Can you please change the homepage to something that works? I believe the homepage is https://gnometerminator.blogspot.com/p/introduction.html

Can you also please update to EAPI=6? See https://devmanual.gentoo.org/ebuild-writing/eapi/ and https://blogs.gentoo.org/mgorny/2015/11/13/the-ultimate-guide-to-eapi-6/ for references

**Comment by EvaSDK** [comment]
I have local bump for this as well, will try to take over the package before it gets purged from tree.

**Comment by EvaSDK** [comment]
someone pushed 1.91 already, could you check the diff against your work to see if anything is still required ?

**Comment by monsieurp** [comment]
c150d6ab20f93daf0400a75e2ff9ec035ad6a740 got there first. Sorry. Closing.

**Pull request closed without merging**
