### PR TITLE
dev-php/pecl-http: add 4.2.6, drop 4.2.2-r1

### PR DESCRIPTION
**Pull request by logistiker**
Closes: https://bugs.gentoo.org/945977

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
This needs to either contain an initial commit handling pecl-hapf, or you need to make another PR handling pecl-hapf and clearly state this one depends on that one.

**Comment by logistiker** [comment]
Can't you just merge the PR for pecl-raphf first and then this one?

**Comment by thesamesam** [comment]
I didn't know there was one as it wasn't linked here.

**Comment by thesamesam** [comment]
https://github.com/gentoo/gentoo/pull/39681

**Pull request closed without merging**
