### PR TITLE
Update myspell-ru-20150711.ebuild

### PR DESCRIPTION
**Pull request by perfect7gentleman**
app-dicts/myspell-ru: revision bump 20150711-r1

Bugfix for bug 579054

Acked-by: Perfect Gentleman <perfect007gentleman@gmail.com>
Reported-by: Igor Poboiko <igor.poboiko@gmail.com>

### CODE REVIEW

**Comment by idella** [comment]
Sorry this commit msg needs completely re-doing,   See format of commit msgs

https://wiki.gentoo.org/wiki/Gentoo_git_workflow

**Comment by tomboy-64** [comment]
still no good.
https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by perfect7gentleman** [comment]
i don't get it really. what more can i write there?

**Comment by tomboy-64** [comment]
Please read the link I provided. It explains in detail how commit messages ***must*** be formatted.

**Comment by mjeveritt** [comment]
Also https://wiki.gentoo.org/wiki/Gentoo_Github .
User clearly cannot have run 'repoman full' as required by Gentoo QA.

**Comment by monsieurp** [comment]
ping @perfect7gentleman

**Comment by perfect7gentleman** [comment]
yep, my monsieurp

**Comment by idella** [comment]
commit 1e0492819fb5c3a27ed65b6e3767876dba3c9803
Author: Ian Delaney <idella4@gentoo.org>
Date:   Tue May 10 14:10:16 2016 +0800

    app-dicts/myspell-ru: rebump -> myspell-ru-20150711-r1.ebuild
    
    upgrade src_install, add symlinks to the dictionary files
    patch supplied by proxied maintianer via the gentoo bug
    
    Gentoo-bug: #579054

**Pull request closed without merging**
