### PR TITLE
 net-im/spectrum2: fix wrong user in systemd tmpfiles

### PR DESCRIPTION
**Pull request by ConiKost**
Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by andrey-utkin** [comment]
Hi @ConiKost , what is the problem you are solving here?

**Comment by ConiKost** [comment]
There is a wrong user definied in ```spectrum2.tmpfiles```, so the directory will have a wrong owner, which does not exist.

**Comment by andrey-utkin** [comment]
> There is a wrong user definied in `spectrum2.tmpfiles`, so the directory will have a wrong owner, which does not exist.

But content of new .tmpfiles file is literally the same.

**Comment by ConiKost** [comment]
> But content of new .tmpfiles file is literally the same.

Please have more al look ;-) It's not the same:
https://github.com/gentoo/gentoo/blob/5b6bf38d11915a5f3c1504a05aa3b5dbc8f626f1/net-im/spectrum2/files/spectrum2.tmpfiles
https://github.com/gentoo/gentoo/blob/fea7e6ba6d1263ea373c2ea7fc3cb5d5590b3f6a/net-im/spectrum2/files/spectrum2.tmpfiles-r1

```specturm``` vs ```spectrum```.

**Comment by andrey-utkin** [comment]
Ah now I see. I expected to see sth like `spectrum` vs `spectrum2`.
I hope this highlights my previous point about making smaller and more obvious changes. It's really easy to miss a critical detail in the sea of removed and new added lines.

**Pull request closed without merging**
