### PR TITLE
sci-libs/rocPRIM: HIP parallel primitives for ROCm GPU.

### PR DESCRIPTION
**Pull request by heroxbd**
@candrews @justxi please take a look.  rocThrust, hipCUB, rocSPARSE depend on rocPRIM.

hipSPARSE depends on rocSPARSE.

Bug: https://bugs.gentoo.org/650804
Bug: https://github.com/gentoo/gentoo/pull/10724

### CODE REVIEW

**Comment by justxi** [comment]
@heroxbd 
I don´t have any comments on this. But I have to learn from your "sed" optimisations =).

**Comment by heroxbd** [comment]
> @heroxbd
> I don´t have any comments on this. But I have to learn from your "sed" optimisations =).

LoL, my pleasure.  Thanks!

**Comment by heroxbd** [comment]
> @heroxbd
> I don´t have any comments on this. But I have to learn from your "sed" optimisations =).

I have learnt regular expressions from this book https://www.oreilly.com/library/view/mastering-regular-expressions/0596528124/

It could help.

**Comment by justxi** [comment]
Thanks.

**Pull request closed without merging**
