### PR TITLE
app-editors/vim: remove warning due to missing defaults.vim

### PR DESCRIPTION
**Pull request by dongsupark**
vim >= 8.2.3428 prints out a warning on missing file, when it is built with USE="minimal" and `app-editors/vim-core` is not installed.

```
$ vim
E1187: Failed to source defaults.vim
Press ENTER or type command to continue
```

To remove the warning, explicitly install /usr/share/vim/vim82/defaults.vim.

Closes: https://bugs.gentoo.org/820356
Signed-off-by: Dongsu Park <dpark@linux.microsoft.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
Won't this collide with vim-core?

**Comment by thesamesam** [comment]
> @thesamesam It should not. I have added the check for `use minimal` to avoid colliding with vim-core. AFAICT vim-core is pulled in when `minimal` is not set.

I could have vim-core installed independently though, I think (even if this seems unlikely)? It seems like it would then collide.

**Comment by dongsupark** [comment]
Thanks, you are right.
I updated the PR, so that vim and vim-core do not conflict with each other.

**Comment by thesamesam** [comment]
This looks good now (we need || die on external commands like 'sed', see https://devmanual.gentoo.org/ebuild-writing/error-handling/) but could you verify gvim is okay now?

i.e. Does gvim use the file that vim-core used to install? Or does it not affect gvim?

**Comment by dongsupark** [comment]
Thanks, updated the PR to add `|| die` to sed and rm commands.

Checked also gvim. That is not affected by vim-core at all.

**Comment by thesamesam** [comment]
Thanks for being thorough here! Really appreciate the PR.

**Comment by thesamesam** [comment]
Oh, note for future: we should've possibly revbumped here (it changes the installed files/runtime behaviour of these) but it seems like a trivial issue and we're going to end up bumping for the never-ending CVEs shortly enough I suspect, so not worth it.

**Pull request closed without merging**
