### PR TITLE
gui-apps/waybar: update to 0.9.8

### PR DESCRIPTION
**Pull request by msathieu**

### CODE REVIEW

**Comment by JonasToth** [comment]
Lgtm

**Comment by msathieu** [comment]
Missed a dependency in my previous commit

**Comment by JonasToth** [comment]
@msathieu which one was it? `libxkbcommon` is it missing in the older ebuilds, too?

**Comment by msathieu** [comment]
The dependency on libxkbcommon was added in 0.9.8 (https://github.com/Alexays/Waybar/commit/8310700bbb52af17477cedc61ea9f660c7965053)

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
