### PR TITLE
sci-astronomy/siril: fix call to undeclared function

### PR DESCRIPTION
**Pull request by hamarituc**
Closes: https://bugs.gentoo.org/883121
Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>

### CODE REVIEW

**Comment by a17r** [comment]
Doesn't really require a revbump, right?

**Comment by thesamesam** [comment]
> Doesn't really require a revbump, right? If you wanted to be extra careful, then you would not touch the stable ebuild.

No, it does: https://github.com/gentoo/devmanual/commit/2b94b64306230dc3595150c5bba87ec0763d93a3.

**Comment by a17r** [comment]
Then only fix ~arch and call for stabilisation afterwards.

**Comment by hamarituc** [comment]
In this case we leave version 1.0.5 as is (broken) and apply the fix only to 1.0.6 (unstable), because there is not advantage to fix it for 1.0.5.

**Pull request closed without merging**
