### PR TITLE
media-video/ffmpeg and media-libs/amf-headers: Fix bugs 908956 and 910406

### PR DESCRIPTION
**Pull request by Peter-Levine**
`ffmpeg-6` now depends on `>=media-libs/amf-headers-1.4.28` when built with `USE=amf`.  This PR adds `media-libs/amf-headers1.4.30` and removes two redundant older versions. 
It also adds a patch which backports https://github.com/FFmpeg/FFmpeg/commit/11eca6018c40f5ebe6af93cbc4b4dce447d8b3bc and https://github.com/FFmpeg/FFmpeg/commit/1231003c3c6d4839a9e838d06f8e16ee7690958f to fix building against libplacebo-6.

I don't believe it impacts unaffected builds, so it shouldn't need a revbump.

Closes [908956](https://bugs.gentoo.org/908956) and [910406](https://bugs.gentoo.org/910406).

### CODE REVIEW

**Review by ticoombs — APPROVED** [review]
Confirming fix. 6.0-rc2 builds with amf support with v1.4.30

**Review by ConiKost — CHANGES_REQUESTED** [review]
Please revbump ffmpeg. Yes, normally not needed for build fix, but you changed deps. Otherwise lgtm.

**Review by ConiKost — CHANGES_REQUESTED** [review]
Just a small nit-pick, you can drop then -r3 ;-)

**Review by ionenwks — APPROVED** [review]
Don't have much to say wrt libplacebo (been keeping that disabled on ffmpeg, so I wouldn't know better), but builds w/ both old and new and alpine been using these backports too, so lgtm.

fwiw it'll also be fixed in ffmpeg-6.1 which I *think* will come out this week or so

**Comment by thesamesam** [comment]
> Don't have much to say wrt libplacebo (been keeping that disabled on ffmpeg, so I wouldn't know better), but builds w/ both old and new and alpine been using these backports too, so lgtm.

Thanks - I just wanted to check w/ you (sorry, should've commented, just going through PR backlog) if there was any caveat you were aware of. Cheers!

**Comment by ConiKost** [comment]
Thanks!

**Comment by AdelKS** [comment]
Sorry guys, in the upcoming three weeks I'll get back my Gentoo machine and I'll be able to continue maintaining my packages. Thanks !

**Pull request closed without merging**
