### PR TITLE
app-text/podofo: add libressl useflag

### PR DESCRIPTION
**Pull request by Wonko7**
Is this the right place for this?

### CODE REVIEW

**Comment by monsieurp** [comment]
Yes. @blueness

**Comment by monsieurp** [comment]
@gentoo/kde

**Comment by kensington** [comment]
kde does not maintain podofo

**Comment by monsieurp** [comment]
@blueness still :)

**Comment by blueness** [comment]
@Wonko7 yeah this is the right place, it just slipped under my radar.  its pushed.

**Comment by kensington** [comment]
Please note that I've reverted the kdelibs4support changes in. 8dc13f6e3a0479a851bafe44a7f200764c37de0e.

**Comment by blueness** [comment]
@kensington what was wrong, i tested

**Comment by kensington** [comment]
@blueness in general kde-*/ changes to the tree can easily get lost as our normal workflow is to make changes to live ebuilds, from which version bumps are made and finally moved to the main tree. This gets us a lot of extra free testing.

Regarding this change specifically, I'd prefer to avoid targeting 5.21 as it's been settled for a while now and is slated to be stabilised shortly. libressl support has already been baking in the overlay for a while and should appear in the main tree within a week with as 5.22 is bumped.

The diff itself needed a minor cosmetic changes regarding sorting of USE flags / dependencies.

Also, I don't agree with the use of slot operators here. IIRC kssl loads the crypto library at runtime with QLibrary so I'm not sure that a rebuild would definitely be required. As for openssl, there is no metadata describing the meaning of the subslot the way libressl does. I did ask one of the maintainers to clarify in the past but he actively refused to share that information.

**Pull request closed without merging**
