### PR TITLE
net-libs/grpc: remove unused patch(es)

### PR DESCRIPTION
**Pull request by mm1ke**
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Michael Mair-Keimberger <mmk@levelnine.at>

### CODE REVIEW

**Comment by gyakovlev** [comment]
@arthurzam seems you've committed a patch, but it's not used in ebuild. can you please check if it's correct?

non-working tests for `net-libs/grpc` is ok, it's complete PITA to make it work properly.

**Comment by gyakovlev** [comment]
6808a5a7420dfa7355ed17d81b0f88d6889f3894 just for the record

**Comment by arthurzam** [comment]
@gyakovlev Yes, my mistake - we can remove it.
I was trying to fix IUSE="test" build (do note that it fails for older versions also, but thankfully it is tests restricted so we hide it).
I thought the fix would be to use system gtest or manually bundle gtest (using manual download and link) - but both failed.

**Comment by gyakovlev** [comment]
thanks for checking, merged.

**Pull request closed without merging**
