### PR TITLE
net-im/telegram-desktop: Bump to 4.8.4

### PR DESCRIPTION
**Pull request by mid-kid**

### CODE REVIEW

**Comment by thesamesam** [comment]
Please cleanup old in a separate commit unless there's really no reason anyone would want to roll back to 4.8.3 (and if so, state that in the commit message).

**Comment by mid-kid** [comment]
4.8.4 is a very minor bugfix release over 4.8.3. the tdesktop maintainers have this tendency of doing one big release and then spending maybe a week shotgunning hotpatches. This is one of those.

**Comment by mid-kid** [comment]
@thesamesam the issue was solved.

**Comment by mid-kid** [comment]
oooooooo @thesamesam saaaaaaaaaaaaaam

**Pull request closed without merging**
