### PR TITLE
gnome-extra/nemo: Bump to 4.6.0

### PR DESCRIPTION
**Pull request by herbmillerjr**
Addresses -fno-common as part of Gentoo Bug Day and brings back a feature upstream fixed.

@SparkyBluefang would you mind bumping the rest of the stack to match?

### CODE REVIEW

**Comment by SparkyBluefang** [comment]
I've got every thing bumped to the latest 4.6 releases in my personal overlay. However, there are some regressions in display management with HIDPI/4K setups.

I was hoping to wait on 4.4 getting stabilized before getting 4.6 merged in. That would also give upstream some time to fix the problems.

**Comment by herbmillerjr** [comment]
Sounds like a plan. Is it safe to bump nemo alone in the meantime to help with gcc-10 adoption? My experience with it is it's not one of those applications that needs to be kept in lockstep with the stack, but I could be mistaken.

**Comment by juippis** [comment]
@SparkyBluefang please inform how to continue with this.

**Comment by juippis** [comment]
b46e841f00b4d4310445bd674f13270aff9e2485 probably does it...

**Pull request closed without merging**
