### PR TITLE
sci-physics/lammps: add 20240829

### PR DESCRIPTION
**Pull request by denisstrizhkin**
New stable version available.

### CODE REVIEW

**Comment by denisstrizhkin** [comment]
I noticed that it's not really an issue with this new version but older `amd64` versions also try to download gtest tar.xz from the internet.
https://github.com/lammps/lammps/blob/570c9d190fee556c62e5bd0a9c6797c4dffcc271/unittest/CMakeLists.txt#L13

**Comment by AndrewAmmerlaan** [comment]
>  In my case it does download it without any issues:

Then you have the network-sandbox disabled. Per policy packages in `::gentoo` must be able to build with the network-sandbox enabled.

**Comment by denisstrizhkin** [comment]
I see. Maybe you have a tip on fixing this issue? The cmake is hardcoded to compile its own version of gtest. One possibility that comes to mind that gtest can be downloaded as another src tarball.

**Comment by AndrewAmmerlaan** [comment]
> I see. Maybe you have a tip on fixing this issue? The cmake is hardcoded to compile its own version of gtest. One possibility that comes to mind that gtest can be downloaded as another src tarball.

I don't think downloading it from `SRC_URI` will help, cmake will probably still try to fetch it.

Maybe patching out the lines in the cmake files where it tries to download this is enough to make it work properly.

**Comment by denisstrizhkin** [comment]
I tried removing the download of gtest part but cmake file written in a way where it is not enough. It expects its own gtest version. I tried some stuff but ended up just predownloading gtest version it needs.

**Comment by AndrewAmmerlaan** [comment]
> I tried removing the download of gtest part but cmake file written in a way where it is not enough. It expects its own gtest version. I tried some stuff but ended up just predownloading gtest version it needs.

hmm, it's not ideal, but it does work now and it's a definite improvement over the current ebuilds so I'll merge it. Thanks!

Closed per https://github.com/gentoo/gentoo/commit/ce0042600ff75a6c1a00d43d271a247b6d29f553

**Pull request closed without merging**
