### PR TITLE
games-action/*: EAPI7, eclass and other minor improvements

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This udpates a few EAPI6 ebuilds towards EAPI7. Some notes:

* There were some ebuilds using `gnome2_icon_savelist`. I was reading the eclass about this and it was written that "This is only necessary for eclass implementations that call gnome2_icon_cache_update conditionally". I'm not really sure about this but since we don't call them conditionally we don't need this, do we?

* `games-action/brutal-legend` is has `~amd64 ~x86` keywords but doesn't have `-*` like other binary only games. Shouldn't we change that and add this too?

Please review

### CODE REVIEW

**Comment by thesamesam** [comment]
1. Yeah, just use the xdg eclass (or xdg-utils if you prefer, but xdg is less work as it implements phases for us)
2. Yep, -* all the way.

**Comment by mm1ke** [comment]
@thesamesam 
updated and rebased. I've updated the ebuilds to use the `xdg` eclass and also remove the phase functions completely.

**Review by ionenwks — COMMENTED** [review]
Can't test most of these but looks good to me on paper, just 3 minor things I could see (one unrelated to your changes).

**Comment by ionenwks** [comment]
Given trivial I went ahead and added the missing desktop, plus another commit wrt toolchain. Thanks!

**Comment by mm1ke** [comment]
Thank you @ionenwks 
Sorry that i haven't updated my PR yet, i was afk the last few days ;)

**Pull request closed without merging**
