### PR TITLE
net-libs/libwebsockets: change USE flag name

### PR DESCRIPTION
**Pull request by jsmolic**
Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>
Signed-off-by: Luka Perkov <luka.perkov@sartura.hr>

### CODE REVIEW

**Comment by jsmolic** [comment]
@jkroonza @juippis Related with https://github.com/gentoo/gentoo/pull/15452. Since LWS_WITH_HTTP_BASIC_AUTH and LWS_WITH_HTTP_UNCOMMON_HEADERS are tied with the same USE flag, I think that `http-basic-auth` better describes this flag.\
The last pull request was closed before I got the chance to fix the flag name. This commit is just a name correction, no configuration options were changed.

**Comment by jkroonza** [comment]
So http basic auth required not-so-common-headers?

I'm assuming LWS doesn't really support challenge-response auth (My use cases doesn't require authentication).

What else is affected?  I don't have a particular opinion about this, but the only use case for disabling this would be for embedded systems where every byte counts.  So what other http headers are affected?  Surely it's more than basic auth, because frankly, the code for that cannot be particularly large.

**Comment by jsmolic** [comment]
@jkroonza Yeah, aparrently BASIC_AUTH requires uncommon headers as WWW_AUTHENTICATE is included in the uncommon headers.
Linking Andy's response to my question about this: https://libwebsockets.org/pipermail/libwebsockets/2020-May/008489.html

I mean http basic auth was the one that was causing build problems (namely, in [http/server/server.c](https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/server/server.c) file)  if uncommon headers were not included, and this was in the first place done for embedded use-case, to save space.

I dug though the source a bit, and these headers seem to be affected as well:
https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/lextable.h
https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/lextable-strings.h

And are present in these `.c` files:
https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/minilex.c
https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/parsers.c
https://github.com/warmcat/libwebsockets/blob/master/lib/roles/http/header.c

This particular commit was just to rename the USE flag, as it was already merged in https://github.com/gentoo/gentoo/pull/15452 I just thought that that `http-basic-auth` better described the flag rather than `http-uncommon-headers`...

**Comment by juippis** [comment]
Please find a common consensus on how you want to deal with this package.
I had to revert this "USE flag mess" for now.

**Comment by jkroonza** [comment]
Jakov, Luka,

I have no objections to getting changes in to accommodate you with respect to embedded systems here.  What I do need, however, is for those builds to work.  The reason I requested juippis to revert was that we found multiple other build failures post merging.  I believe there were at least three independent build failures that I'm aware of with respect to the changes.

So please, we need to do better than this.  I've inquired about burn-in compile tests that'll throw random USE combinations at the package, so we'll be needing to do that going forward.  We can't drop those kind of failures onto consumers.

Thank you for your understanding.

**Comment by lperkov** [comment]
@jkroonza we will open a new pull request with a package that worked for us as it is not clear what error you have hit and we can polish it there. Thanks!

**Pull request closed without merging**
