### PR TITLE
www-client/chromium: version bump to 58.0.3029.110

### PR DESCRIPTION
**Pull request by zozom**
Package-Manager: Portage-2.3.5, Repoman-2.3.1

### CODE REVIEW

**Comment by DmitryHetman** [comment]
Does this version supports Wayland or goes into the trash.

**Comment by mgorny** [comment]
Is there any specific change between the ebuild for this version and the previous? GitHub doesn't like to diff new files ;-).

**Comment by zozom** [comment]
Only the version and keywords have changed compared to version 58.0.3029.81. Otherwise everything is the same as version 58.0.3029.81.

**Comment by floppym** [comment]
Rebased as 57618cb3d9bbd84f417cd358374943435aa3dd0d. Thanks.

**Pull request closed without merging**
