### PR TITLE
app-emacs/org-mode: added 9.6.26

### PR DESCRIPTION
**Pull request by gentoo-setan**
Based on version 24 and 23. Works for me but I have added the unstable flag for all supported architectures.

This is my first PR to Gentoo.

EDIT:
Signed-off-by: setan <gentoo@supporter.addy.io>

### CODE REVIEW

**Comment by gentoo-setan** [comment]
[I have read](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Creating_a_key) that I do not need to sign my commits.
Is that true?
How much burden is it for the developers to sign my stuff?

**Comment by xgqt** [comment]
> [I have read](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Creating_a_key) that I do not need to sign my commits. Is that true? How much burden is it for the developers to sign my stuff?

it verifies your authenticity so you have to sign yourself

**Comment by ulm** [comment]
There's two different kinds of "sign":
- Signoff for the Certificate of Origin, see "Missing GCO sign-off" above: This is required.
- PGP signature of the commit: This is not necessary, developers will (re-)sign your commits before merging them.

**Comment by gentoo-setan** [comment]
What should I do now?
Is the edit enough?

**Comment by xgqt** [comment]
> What should I do now? Is the edit enough?

just `git commit --amend --signoff`

**Comment by xgqt** [comment]
> This is my first PR to Gentoo.

> EDIT:
> Signed-off-by: setan gentoo@supporter.addy.io


You have to add it to the commit and force push to your branch

**Comment by gentoo-setan** [comment]
is this sufficient?

**Comment by xgqt** [comment]
It looks ok, there shouldn't be a "Merge [...]" commit but this we can remove.

**Pull request closed without merging**
