### PR TITLE
git-r3.eclass: Use '__init__' as initial branch

### PR DESCRIPTION
**Pull request by konsolebox**
Solve https://bugs.gentoo.org/841392.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Please add a

Closes: https://bugs.gentoo.org/841392

gut trailer to the commit.

**Comment by konsolebox** [comment]
> Please add a
> 
> Closes: https://bugs.gentoo.org/841392
> 
> gut trailer to the commit.

Done, please check.

**Comment by Flowdalic** [comment]
Thanks. I missed that you also did not sign off your commit. See the messages the bot wrote. Please add this too and then append [please reassign] to the pull request title.

**Comment by konsolebox** [comment]
I didn't think that's also necessary for a public PR.  Unfortunately I don't think I can sign commits so maybe someone can just replicate this and push it themselves.

**Comment by Flowdalic** [comment]
This is not about a cryptographically signing the commit. But about a missing Signed-Off-By git trailer.

**Comment by konsolebox** [comment]
The GCO sign-off requires legal name to be used and I never use mine in this pseudo so I can't.  I hope someone can just take over the commit.

I'll take note not to make a PR again in the future and stick to reporting to bugzilla.  Sorry for the trouble.  The bug report is just taking too long to be given action.  It's just a simple fix.

**Comment by mattst88** [comment]
I've sent this to gentoo-dev@ for review.

**Pull request closed without merging**
