### PR TITLE
media-video/mpv: update live ebuild

### PR DESCRIPTION
**Pull request by Coacher**
https://bugs.gentoo.org/635650

### CODE REVIEW

**Comment by l29ah** [comment]
$(use_enable vaapi vaapi-hwaccel) should be replaced to $(use_enable vaapi)

**Comment by l29ah** [comment]
same for vdpau

**Comment by l29ah** [comment]
oh, never mind, i've missed it above

**Comment by kensington** [comment]
Thanks, picked as bf6d0cba4d23dc69f652eecd009a2e237abef542...3b67b8897d76031905fdfadd9a7296bf9ed11e68.

**Comment by Coacher** [comment]
Thank you, @kensington.

**Comment by haasn** [comment]
Why was vulkan disabled? `media-libs/vulkan-loader` is packaged. (Requires -9999 though for the .pc file)

**Comment by haasn** [comment]
Also, would it still be possible to get ffmpeg-mpv packaged; preferably in a way that doesn't conflict with normal ffmpeg?

**Comment by Coacher** [comment]
@haasn, because as you've said it requires shaderc packaged (which requires glslang and spirv-tools packaged) to be usable anywhere, but the very recent NVIDIA cards. I don't have NVIDIA hardware, so I need to package shaderc first to be able to test it. It's on my TODO list, but not right now, though. You can help by submitting proper ebuilds for the required packages.

As for ffmpeg-mpv issue, please see https://bugs.gentoo.org/635650

**Comment by haasn** [comment]
I'm not sure what you need to test. Adding a USE flag and a DEPENDS line should be enough. I mean, it worked already, your recent change broke that by forcing the --disable flag.

(Also, spirv-compiler=nvidia works with all nvidia cards that support vulkan. You just need recent enough nvidia drivers)

**Pull request closed without merging**
