### PR TITLE
net-fs/curlftpfs: fix sys-fs/fuse SLOT

### PR DESCRIPTION
**Pull request by okias**
Closes: https://bugs.gentoo.org/697018

Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by trofi** [comment]
`RDEPEND` changes need a ebuild revbump: https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html. Can you tweak it? I'll merge it as-is then.

**Comment by okias** [comment]
@trofi  can I git mv to new revbump or should I copy?

**Comment by okias** [comment]
@trofi done

**Comment by trofi** [comment]
Copy should always be preferred in case of new ebuild having problems.

Pulled as-is. Thank you!

**Pull request closed without merging**
