### PR TITLE
sys-cluster/keepalived: fix crash during shutdown

### PR DESCRIPTION
**Pull request by hydrapolic**
Fix taken from upstream master

https://bugs.gentoo.org/670856
https://github.com/acassen/keepalived/issues/1061

### CODE REVIEW

**Comment by Zlogene** [comment]
It seems it suffers from some spacing problems:

```
.git/rebase-apply/patch:25: space before tab in indent.
 	/* We handle the global oid if we are running SNMP */
.git/rebase-apply/patch:26: space before tab in indent.
 	snmp_agent_init(snmp_socket, true);
.git/rebase-apply/patch:27: space before tab in indent.
 	snmp_register_mib(check_oid, OID_LENGTH(check_oid), "Healthchecker",
.git/rebase-apply/patch:35: space before tab in indent.
 	snmp_unregister_mib(check_oid, OID_LENGTH(check_oid));
.git/rebase-apply/patch:36: space before tab in indent.
```

**Comment by hydrapolic** [comment]
@Zlogene, i know. It was taken directly from github (https://github.com/acassen/keepalived/compare/v2.0.10...master.diff), i didn't want to modify it.

This should not happen in an ebuild, but it's a patch that won't be modified.

**Comment by Zlogene** [comment]
well, this is C, so thats not a problem indeed

**Comment by hydrapolic** [comment]
Thanks @Zlogene

**Pull request closed without merging**
