### PR TITLE
app-admin/graylog2: bump to 2.2.3

### PR DESCRIPTION
**Pull request by hydrapolic**
Been using for a while, works nice.

Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by hydrapolic** [comment]
@gentoochainsaw

**Comment by gentoochainsaw** [comment]
Don't drop 2.2.2 unless there is a compelling reason, i.e. it is broken. If you remove the "drop old" aspect of this, it can be merged immediately with my blessing.

**Comment by hydrapolic** [comment]
@gentoochainsaw, is there a reason to keep 2.2.2? Basically, 2.2.3 is just a minor version fixing bugs. But I'm ok with keeping version 2.2.2 too.

**Comment by gentoochainsaw** [comment]
Exactly my point, it is a minor upgrade and thus users wishing to remain on 2.2.2 for a little while longer have the right to do so. Forcing upgrades is not necessary here. Thank you for your contribution :)
Team github; this is okay to merge to the portage tree.

**Comment by hydrapolic** [comment]
Thank you @SoapGentoo

**Pull request closed without merging**
