### PR TITLE
Java pkg simple improve module support

### PR DESCRIPTION
**Pull request by 2Kmm**
Closes: https://bugs.gentoo.org/922157

### CODE REVIEW

**Comment by fordfrog** [comment]
@vaukai can you please have a look at it?

**Comment by vaukai** [comment]
> @vaukai can you please have a look at it?

This all looks reasonable but i haven't run any tests yet. Can you think of any of the existing bug reports being fixed by it?
Think i willl check with those packages where we have special handling for `module-info` like e.g. `byte-buddy` or `asm`.

**Comment by vaukai** [comment]
It feels like decades ago when working in research and looking for problems to all our nice solutions ...
@fordfrog i ran some tests and from my point of view it is ok.

**Comment by vaukai** [comment]
> Thank you! Nice to see another Java contributor too :)
> 
> (For future reference: I recommend using `Bug:` tags in commits for the non-final commit so the bug still gets tagged)

But in this case `Closes:` was correct (we cannot remove an older revision of the eclass).

**Comment by thesamesam** [comment]
I'm talking about the other commits in the series. They were related to the bug.

**Comment by vaukai** [comment]
Sorry for misreading ...

**Comment by vaukai** [comment]
This commit seems to have caused https://bugs.gentoo.org/923599

**Pull request closed without merging**
