### PR TITLE
gui-apps/gnome-console: Version bump to 45.0

### PR DESCRIPTION
**Pull request by flint2**
Test OK

```

>>> Test phase: gui-apps/gnome-console-45.0
meson test --print-errorlogs -C /var/tmp/portage/gui-apps/gnome-console-45.0/work/gnome-console-45.0-build --num-processes 12
ninja: Entering directory `/var/tmp/portage/gui-apps/gnome-console-45.0/work/gnome-console-45.0-build'
[1/22] Generating kgx-config.h with a custom command
fatal: not a git repository (or any parent up to mount point /var/tmp)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
1/1 Validate schema file        OK              0.00s

Ok:                 1   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gui-apps/gnome-console-45.0/work/gnome-console-45.0-build/meson-logs/testlog.txt
>>> Completed testing gui-apps/gnome-console-45.0


```

### CODE REVIEW

**Comment by mattst88** [comment]
```diff
-gtk_dep = dependency('gtk4', version: '>= 4.10.5')
+gtk_dep = dependency('gtk4', version: '>= 4.12.2')
```

They're really requiring an unreleased version of GTK? :(

(The ebuild only requires 4.12.1 FYI

**Comment by mattst88** [comment]
I asked about the requirement here (https://gitlab.gnome.org/GNOME/console/-/commit/af40a0cb23bb541522b94c0198126de7acf76aec#note_1849394) but I wouldn't be surprised to not receive an answer.

**Comment by flint2** [comment]
> There's a new version of vte as well. I'm curious, have you looked into it?

Yes, but still struggling with the non vanilla patchset, applied it but is not compiling

**Comment by mattst88** [comment]
Ah, makes sense :(

Don't spend too much time on that. I never did a full rebase myself. I just waited for Fedora to update vte and then grabbed the new patches from them. (And once, they didn't update vte for a long while so I forced `USE=vanilla` on via `package.use.force`)

**Comment by flint2** [comment]
> Ah, makes sense :(
> 
> Don't spend too much time on that. I never did a full rebase myself. I just waited for Fedora to update vte and then grabbed the new patches from them. (And once, they didn't update vte for a long while so I forced `USE=vanilla` on via `package.use.force`)

Draft PR, do you want to  check it?
https://github.com/gentoo/gentoo/pull/32929

**Comment by mattst88** [comment]
> I asked about the requirement here (https://gitlab.gnome.org/GNOME/console/-/commit/af40a0cb23bb541522b94c0198126de7acf76aec#note_1849394) but I wouldn't be surprised to not receive an answer.

The maintainer replied and confirmed that 4.12.2 is the real requirement (and it was just released today).

**Pull request closed without merging**
