### PR TITLE
x11-drivers/xf86-input-mtrack: version bump to 0.4.1

### PR DESCRIPTION
**Pull request by gsora**
BlueDragonX doesn't actively develop this driver anymore, the new codebase is maintained aton https://github.com/p2rkw/xf86-input-mtrack.

Package-Manager: portage-2.3.3

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/x11 @mattst88 I meant to ask about this PR. What's blocking it from landing in the tree?

**Comment by mattst88** [comment]
I don't use the software, and I don't know how to test it. It's evidently been forked -- I know nothing about the fork.

If they'd just host the damn thing on freedesktop like the rest of the xf86-input-* drivers this would be a lot clearer.

@naota is the primary maintainer. I think he should handle this.

**Comment by gsora** [comment]
I am just an user who thought that updating the version served through 
the Portage tree was *the right thing to do*.

Sadly, I don't control the development process thus I can't guarantee 
for stability, security, or the delivery platform.

If you believe this ebuild should be published in an overlay and not in 
the central tree, you're free to close this PR.

**Comment by mattst88** [comment]
Holy shit. Take it down a notch.

I'm just answering a question -- why I haven't acted on the pull request.

**Comment by gsora** [comment]
I'm sorry if my tone seemed harsh, I'm not being mad at you or anyone else involved in this PR. 

I was just expressing my though, in the most peaceful manner my (not so great) English let me :-)




On Wed, Mar 22, 2017 at 8:14 PM +0100, "Matt Turner" <notifications@github.com> wrote:












Holy shit. Take it down a notch.


I'm just answering a question -- why I haven't acted on the pull request.

**Comment by monsieurp** [comment]
Alright gents. Let's have it my way.

@gsora could you provide a build log for this new version as a way to warrant it does compile? Also, I guess you've been using this driver with Gentoo. Could you also provide your `dmesg` output as proof it works and is recognised as it should by the kernel? Thanks!

PS: https://bpaste.net/ for a pastebin-like yet ad-free website. You're welcome.

**Comment by gsora** [comment]
Tomorrow I'll post the requested data.

**Comment by gsora** [comment]
Ok @monsieurp here's all the log you requested:

- [an `ls` of `/usr/lib64/xorg/modules/input`](https://bpaste.net/show/4c6249eab3b7)
- [the output of `emerge --ask xf86-input-mtrack` from a local overlay](https://bpaste.net/show/0a5e98711412)
- [the proof of the module being loaded and used by Xorg](https://bpaste.net/show/7f213fe1f722) 

If more logs are needed, just ask and I'll deliver :)

**Comment by monsieurp** [comment]
Thanks @gsora! :) It looks good enough to me. Will merge it shortly.

**Comment by mattst88** [comment]
Fetching the sources don't work... https://bugs.gentoo.org/show_bug.cgi?id=613930

**Comment by gsora** [comment]
I'll check out what's happening and rebuild the manifest accordingly.

I really don't know why it's giving bad checksum, it is building fine on my machine.

I apologize for this (dumb) error, these are my first ebuilds/commits to the official tree, I should have checked more thoroughly.

**Comment by monsieurp** [comment]
Fixed.

**Pull request closed without merging**
