### PR TITLE
sci-geosciences/qgis: Version bump 2.18.2

### PR DESCRIPTION
**Pull request by cjmayo**
Basically a copy of 2.14.5

A couple of fixes which I think are relevant to 2.14.5 too:
* `inherit multilib` isn't need for `$(get_libdir)` with EAPI 6
* missing D prefix `"-WITH_QSPATIALITE=ON"`

Maybe relevant to 2.14.5, haven't checked:
* gsl is only used for georeferencer plugin as stated in INSTALL
` - for georeferencer - GSL >= 1.8`

plus `-DWITH_GSL` isn't used:
```
CMake Warning:
  Manually-specified variables were not used by the project:

    WITH_GSL
```
There is automagic detection of gsl to decide whether to build the plugin or not.
Therefore, added a `cmake_comment_add_subdirectory` to control this.

 * But maybe a new `georeferencer` USE flag would be better instead of `gsl`?

New stuff:
* qjson dependency

@Amynka

### CODE REVIEW

**Comment by Amynka** [comment]
If you want to change name of the useflag then submit the pull request but as you know atomagic detection is not allowed in gentoo so patches are also welcome. As you wish I will not merge it. 

For the multilib eclass I am sorry I did accidentally merge it back. Will be fixed in sec.

**Comment by cjmayo** [comment]
Thanks for reviewing. I just wanted to check. Having said that I've made a few extra changes to the ebuild as well as the USE flag:

Some tidying of mycmakeargs:
*  Take the double quotes off (makes them line up...)
*  Change -DENABLE_TESTS from no to OFF

Also there was a space on the end of QGIS in make_desktop_entry that was being written into the desktop file.

**Comment by Amynka** [comment]
Nice work! Any ideas how to patch the GSL auto magic?

**Comment by cjmayo** [comment]
It won't be too hard to create an upstream PR for the automagic. In the meantime the
`use georeferencer || cmake_comment_add_subdirectory "georeferencer"`
works for the ebuild.

I've updated again to improve the logging in pkg_postinst():
* replace else if with elif
* tweak the wording

**Comment by Amynka** [comment]
Well if you think that upstream would want it. Normally they have it on purpose but well you can try it.

I will test it and merge. Good job!

**Comment by Amynka** [comment]
I propose wait for 30 days and then make stable request for the 2.18.2 and remove all the old versions.
Do you agree?

Thanks for your job

**Comment by fedeliallalinea** [comment]
qgis 2.18 need 
>=sci-libs/libspatialindex-1.8.5
>=dev-db/spatialite-4.1.0
otherwise when load a WFS layer program crash with segfault.

**Comment by Amynka** [comment]
Any proof from upstream or something please?

**Comment by fedeliallalinea** [comment]
I post stack trace tomorrow. I use qgis only at work (not installed at home).

**Comment by cjmayo** [comment]
For https://github.com/gentoo/gentoo/pull/3136#issuecomment-267819238
I suggest dropping 1.8.0 and 2.12.x as unsupported upstream.
2.14 is a bit different because it is long term release, maybe mask with a 30 day warning asking if anyone wants to proxy and dropping if no one steps forward?

**Comment by Amynka** [comment]
Well point is which of the version we want stable. Masking and asking for proxy would be if the package does not have maintainer. We can of course make 2.14 stable instead of 2.18 but then we have to fix the ebuild as the 2.18 one.

**Comment by fedeliallalinea** [comment]
As promised
[qgis stack trace with dev-db/spatialite-2.4.0_rc4](https://paste.pound-python.org/show/FB6BeXAGGIYPSZW6F928/)
[qgis stack trace with dev-db/spatialite-4.3.0](https://paste.pound-python.org/show/ZvL5oN0YdjkpD1i8HhbC/)

In my previous comment I've mentioned `sci-libs/libspatialindex-1.8.5`, but this is wrong only `>=dev-db/spatialite-4.1.0` is necessary

**Comment by Amynka** [comment]
Thank you very much!

**Comment by fedeliallalinea** [comment]
For use 'Add Oracle GeoRaster Layer' we need gdal with oracle support (`gdalinfo --formats | grep GeoRaster`). It's no longer accurate change gdal dependency from 
`>=sci-libs/gdal-1.6.1:=[geos,python?,${PYTHON_USEDEP}]`
to
`>=sci-libs/gdal-1.6.1:=[geos,python?,oracle?,${PYTHON_USEDEP}]`
?

**Pull request closed without merging**
