### PR TITLE
net-misc/freerdp: Add sample flag

### PR DESCRIPTION
**Pull request by fictitiousexistence**
Add sample flag to enable / disable build of sample client named "sfreerdp".

### CODE REVIEW

**Comment by floppym** [comment]
Is the sample client actually useful for users? I think it's just meant as a starting point for developers of new clients.

**Comment by fictitiousexistence** [comment]
@floppym I at first thought that sfreerdp was the sdl one but upon asking in the freerdp irc they said the same thing as what you said, its just a starting point for developers. 

Would it be better to not add a flag and just put 
`-DWITH_SAMPLE=OFF` ?

**Comment by floppym** [comment]
Yes, let's just disable it unconditionally.

**Comment by floppym** [comment]
I recently added 3.4.0, so please include that version as well.

Also, this change requires a revbump since the set of installed files will change.

**Comment by fictitiousexistence** [comment]
@floppym Did I do this properly?
Thanks.

**Comment by floppym** [comment]
I squashed your commits and pushed it. Thanks.

**Pull request closed without merging**
