### PR TITLE
net-wireless/wpa_supplicant: bump to version 2.9

### PR DESCRIPTION
**Pull request by ConiKost**
Also allowing privsep only without macsec.
According to upstream, it's not a valid combination, when you do enable
macsec and privsep together.

Upstream says:
CONFIG_PRIVSEP=y does not have sufficient support for the new driver
interface functions used for MACsec, so this combination cannot be used
at least for now.

Closes: https://bugs.gentoo.org/684442
Closes: https://bugs.gentoo.org/692062
Package-Manager: Portage-2.3.71, Repoman-2.3.17
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by ConiKost** [comment]
Fixed merge conflict.

**Comment by charIes17** [comment]
Could you please bump to version 2.9 (bug 692062)

**Comment by ConiKost** [comment]
Done. Also added new option CONFIG_TEAP, which got added in 2.9.

**Comment by charIes17** [comment]
Maybe, could you also include my old PR (never pulled-in) https://github.com/gentoo/gentoo/pull/5236/commits/7b7e91fb992 for https://bugs.gentoo.org/615872 ?

**Comment by ZeroChaos-** [comment]
thanks all, I am tracking this PR (and the comments), just haven't had time to actually pull it.  I will try to get to it today

**Comment by ConiKost** [comment]
@ZeroChaos- Do you want me to update the PR for the icon stuff?

**Comment by ZeroChaos-** [comment]
naw, I have a window open with the other PR I just need a few minutes to actually test everything (and reboot into a kernel with working wifi, don't ask)

**Comment by ConiKost** [comment]
Allright ;-) But I was too fast now, since I added it :D

**Comment by ZeroChaos-** [comment]
pulled, as is, with no changes.  Thanks!

**Comment by ConiKost** [comment]
Many thanks!

**Pull request closed without merging**
