### PR TITLE
media-libs/gstreamer: add 1.22.9, drop 1.22.3 (security)

### PR DESCRIPTION
**Pull request by lanodan**
Closes: https://bugs.gentoo.org/908978
Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

### CODE REVIEW

**Comment by joakim-tjernlund** [comment]
@leio , please review

**Comment by leio** [comment]
This can't be merged as it is a straight to stable (but it does make for an easier review), other than that:

* Why do we need an explicit soup disabling in -base now instead of eclass magic?
* gst-plugins-mpg123 is regressed by moving -r0 instead of the latest; potentially others might have same issues that had revbump that I missed when looking through the changes (it's still a lot because copyright year changed everywhere). Though I don't see any others that have deleted revisions, so unless some where missed, maybe that's the only one.

In general the gstreamer bumps as PRs aren't really useful unless it is described what was done to achieve it, not only see the end result commit(s). As in, what was done beyond just running a script that copies the ebuilds to new version. If that's tracked and documented in the PR, it's a win, otherwise I'm afraid it's faster to just run the script on my end instead and deal with any needed changes with it.

Other than that, I was about to do just that today and only somewhat accidentally noticed there's a PR by now. Given the need to re-do this as bumps instead of moves (we aren't in a position to be marking everything straight to stable on bump and skipping arch teams) and that I expect to be away from Gentoo until next weekend again, I might end up running my own bump scripting still afterall, unfortunately.

**Comment by leio** [comment]
Oh, it actually isn't straight to stable, because we didn't have 1.22.3 stable yet, thus the moves might be just fine (sans the mpg123 thing)

**Comment by leio** [comment]
The explicit disable is needed because the option was shuffled around to add `soup-lookup-dep` option as well, so the eclass doesn't catch it. But the eclass has other exceptions in there to handle those (e.g. qt6 that is from gst-plugins-good as well).
If we just handle it in gst-plugins-good ebuild, don't all splits try to build the soup plugin as well now? Looks like they might, but in usual setup don't, as ninja is only ran within the plugin folder, but otherwise e.g. gst-plugins-ximagesrc outputs:

```
Run-time dependency libsoup-2.4 found: YES 2.74.3
Run-time dependency libsoup-3.0 found: YES 3.4.4
...
gst-plugins-good 1.22.9

    Plugins              : video4linux2, ximagesrc, soup
```

Also it still tries to run tests for it:

```
 84/100 elements_souphttpsrc3              FAIL             0.15s   exit status 14
 85/100 elements_souphttpsrc2              FAIL             0.16s   exit status 14
```

**Comment by leio** [comment]
I had other distractions and couldn't look into solving all these, so in the hope that I can at least review changes and merge things before next weekend, here's the TODO I have so far:

* Review/fix the gst-plugins-mpg123 situation; making sure no others lost changes in a revbump (some might be due to revbump done after the initial bump branch was made and that's why they are missed).
* Look into soup plugin tests being ran with it disabled; might be something that's fixed upstream in `main` branch or something to submit an upstream fix for.
* Fix up the eclass to know about plugins that the automatic version doesn't manage to catch. `soup` is a new case, but others have been missed, e.g. `v4l2` in gst-plugins-good too, but maybe also others. Looking at what the main media-libs packages explicitly disable and adding them to eclass if needed would hopefully cover all that.
* If per the above things are disabled in eclass, is it even necessary to disable them separately in the main package afterwards?

**Review by leio — CHANGES_REQUESTED** [review]
Updating review status

**Comment by jospezial** [comment]
Is somebody of you working on 1.22.10 ebuilds?

**Comment by leio** [comment]
Thanks. This will take a bit more time to get in main tree as I want to deal with the recompilation of helper libs (discussed on IRC, solution known, need final tests and making it work right for all splits that use `gstreamer_system_package`) and some cleanups to the ebuilds. Also we need to check out gst-plugins-ladspa, if it's worth making lrdf optional, as upstream added a meson knob for it. If not, we should probably force that meson option always on though (currently leaning towards just that, but do not have much knowledge into ladspa stuff).

I'll try to finalize this during the week, but can't promise for sure.

**Comment by leio** [comment]
gst-python python-3.12 compat would be good to test and sort out too as part of the bump.

**Comment by jospezial** [comment]
https://gstreamer.freedesktop.org/releases/1.24/
Do we still need 1.22.x or can we skip straight to 1.24?

**Comment by jospezial** [comment]
https://bugs.gentoo.org/926789
media-plugins/gst-plugins-libav-1.22.3 fails to compile against latest ffmpeg git
Fixes are in 1.24.0 release. Do you plan to backport?

**Pull request closed without merging**
