### PR TITLE
Subslots

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by mgorny** [comment]
Why are you changing subslot on packages that didn't change ABI? I know the current subslot isn't perfect but its change belongs when the ABI changes and not now.

Besides, if ABI of zlib or bzip2 changed, we'd certainly need full slots to prevent the system from becoming unusable in the process.

**Comment by SoapGentoo** [comment]
currently nothing really `:=` depends on zlib really (except some people adding it randomly), so adding shouldnt cause any massive rebuilds. And this is a silent addition, not a revbump.

**Comment by l29ah** [comment]
But why?

**Comment by flussence** [comment]
>And this is a silent addition

[It absolutely is not.](https://forums.gentoo.org/viewtopic-t-1069092.html) You've just wasted hours of many people's time, not to mention megawatt-hours, with a pointless 2 character change.

**Comment by stefson** [comment]
Oh boy, why did you do that? Triggers llvm rebuild on all arches, esp. arm users will be very unhappy about this.

**Comment by hkmaly** [comment]
What is the recommended way to deal with this without pointlessly recompiling everything? https://forums.gentoo.org/viewtopic-p-8119326.html ?

**Comment by heroxbd** [comment]
See also https://forums.gentoo.org/viewtopic-p-8116864.html?sid=148230fb1de446b98ff0f64b96516671

**Comment by Jose123456** [comment]
An explanation would be nice, given I just wasted some precious on this.

**Comment by angryvincent** [comment]
this is case for a serious QA discussion. Its not any good to make such a needless slot bump (they are really, really needless) with speculating on unstable features which sub-slots still are. @SoapGentoo - please, zlib and bzip2 are core packages and neither versions of both had the ABI changes. That's quite unfortunate decision based on nothing. More serious problem is that this pull request silently accepted without any discussion.

**Comment by canaaerus** [comment]
So you said this wouldn't be a problem, because it's not a revbump. Well now there is `zlib-1.2.11-r1` and for a complete system update, i basically have to reinstall everything. I am a paludis user, but i have feelings too :-(.

**Comment by simonbuehler** [comment]
ok also have the problem of beeing unable to emerge, whats the fix for this? i will not recompile everything for nothing , this is just a bad decision and i'm suprised there is no peer review for such a brainless action, this must be avoided in the future!

**Comment by flussence** [comment]
@simonbuehler: the hack in https://github.com/gentoo/gentoo/pull/5635#issuecomment-331686155 should be safe, as it's exactly the same result you'd get with an `emerge -e @world` (addition of a useless subslot that'll likely never need to change in our lifetimes).

As ridiculous as this whole affair was, undoing it at this point would just be doubling the pain for all the people whose time it's already wasted (the vast majority of the gentoo userbase), and that's probably not a good move for them given the already shaky reputation of the developer cabal in the wider community as of late.

>i'm suprised there is no peer review

FWIW, there *was* peer review upthread from a dev before it was merged — 100% NAK. But it was ignored. All we can do at this point is push for whatever broken process led to this in the first place to get fixed so that it doesn't happen again.

**Pull request closed without merging**
