### PR TITLE
app-benchmarks/sysbench: bump to 1.0.7

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by gktrk** [comment]
Any ideas?

```
# FEATURES='test' emerge -v -j1 =sysbench-1.0.7
...
These are the packages that would be merged, in order:

Calculating dependencies  ...... .... done!
[ebuild   R   ~] app-benchmarks/sysbench-1.0.7::local  USE="{test*} -aio -mysql -postgres" 0 KiB

Total: 1 package (1 reinstall), Size of downloads: 0 KiB


>>> Verifying ebuild manifests

>>> Emerging (1 of 1) app-benchmarks/sysbench-1.0.7::local
...
>>> Test phase: app-benchmarks/sysbench-1.0.7
make -j4 -l4 check test 
cd tests && make test
make[1]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
./test_run.sh
Making check in doc
make[1]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc'
Making check in xsl
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc/xsl'
make[2]: Nothing to be done for 'check'.
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc/xsl'
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc'
make[1]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/doc'
Making check in src
make[1]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src'
Making check in drivers
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/drivers'
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/drivers'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/drivers'
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/drivers'
Making check in tests
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests'
Making check in cpu
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/cpu'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/cpu'
Making check in fileio
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/fileio'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/fileio'
Making check in memory
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/memory'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/memory'
Making check in threads
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/threads'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/threads'
Making check in mutex
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/mutex'
make[3]: Nothing to be done for 'check'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests/mutex'
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests'
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/tests'
Making check in lua
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua'
Making check in internal
t/1st.t: make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua/internal'
make  check-am
make[4]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua/internal'
make[4]: Nothing to be done for 'check-am'.
make[4]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua/internal'
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua/internal'
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua'
make[3]: Nothing to be done for 'check-am'.
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua'
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/lua'
Making check in .
passed
t/api_basic.t: make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src'
make[2]: Nothing to be done for 'check-am'.
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src'
make[1]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src'
Making check in tests
make[1]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make  check-TESTS
make[2]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make[3]: Entering directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
passed
t/api_histogram.t: passed
t/api_legacy_basic.t: skipped
t/api_legacy_rand.t: failed
--- t/api_legacy_rand.t
+++ t/api_legacy_rand.t.err
@@ -44,4 +44,5 @@
   $ sysbench $SB_ARGS --max-requests=100000 --test=$CRAMTMP/api_rand_uniq.lua run |
   > grep -v WARNING |  sort -n | uniq | wc -l | sed -e 's/ //g'
   WARNING: the --test option is deprecated. You can pass a script name or path on the command line without any options.
-  100000
+  PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
+  8
t/api_legacy_sql.t: skipped
t/api_rand.t: failed
--- t/api_rand.t
+++ t/api_rand.t.err
@@ -41,4 +41,5 @@
 
   $ sysbench $SB_ARGS --events=100000 $CRAMTMP/api_rand_uniq.lua run |
   >   sort -n | uniq | wc -l | sed -e 's/ //g'
-  100000
+  PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
+  8
t/api_reports.t: failed
--- t/api_reports.t
+++ t/api_reports.t.err
@@ -21,8 +21,9 @@
   > EOF
 
   $ sysbench $SB_ARGS run
-  [ 2s ] thds: 1 tps: *.* qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 1.* err/s 0.00 reconn/s: 0.00 (glob)
-  [ 3s ] thds: 0 tps: *.* qps: 0.00 (r/w/o: 0.00/0.00/0.00) lat (ms,95%): 1.* err/s 0.00 reconn/s: 0.00 (glob)
+  PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
+  /bin/bash: line 15: 14830 Killed                  sysbench $SB_ARGS run
+  [137]
 
 ########################################################################
 # CSV format via a custom hook
@@ -40,8 +41,9 @@
   > EOF
 
   $ sysbench $SB_ARGS run
-  2,1,*.*,0.00,0.00,0.00,0.00,1.*,0.00,0.00 (glob)
-  3,0,*.*,0.00,0.00,0.00,0.00,1.*,0.00,0.00 (glob)
+  PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
+  /bin/bash: line 28: 14867 Killed                  sysbench $SB_ARGS run
+  [137]
 
 ########################################################################
 # JSON format via a custom hook
@@ -59,31 +61,6 @@
   > EOF
 
   $ sysbench $SB_ARGS run
-  {
-    "time":    2,
-    "threads": 1,
-    "tps": *.*, (glob)
-    "qps": {
-      "total": 0.00,
-      "reads": 0.00,
-      "writes": 0.00,
-      "other": 0.00,
-    },
-    "latency": 1.*, (glob)
-    "errors": 0.00,
-    "reconnects": 0.00
-  },
-  {
-    "time":    3,
-    "threads": 0,
-    "tps": *.*, (glob)
-    "qps": {
-      "total": 0.00,
-      "reads": 0.00,
-      "writes": 0.00,
-      "other": 0.00,
-    },
-    "latency": 1.*, (glob)
-    "errors": 0.00,
-    "reconnects": 0.00
-  },
+  PANIC: unprotected error in call to Lua API (runtime code generation failed, restricted kernel?)
+  /bin/bash: line 41: 14888 Killed                  sysbench $SB_ARGS run
+  [137]
t/api_sql_mysql.t: skipped
t/api_sql_pgsql.t: skipped
t/cmd_cleanup.t: passed
t/cmd_help.t: passed
t/cmd_prepare.t: passed
t/cmd_run.t: passed
t/cmdline.t: passed
t/commands.t: passed
t/drivers.t: passed
t/drv_mysql.t: skipped
t/drv_pgsql.t: skipped
t/help_drv_mysql.t: skipped
t/help_drv_pgsql.t: skipped
t/opt_help.t: passed
t/opt_histogram.t: passed
t/opt_report_checkpoints.t: skipped
t/opt_report_interval.t: skipped
t/opt_version.t: passed
t/script_bulk_insert_mysql.t: skipped
t/script_bulk_insert_pgsql.t: skipped
t/script_oltp_help.t: passed
t/script_oltp_insert_mysql.t: skipped
t/script_oltp_insert_pgsql.t: skipped
t/script_oltp_point_select_mysql.t: skipped
t/script_oltp_point_select_pgsql.t: skipped
t/script_oltp_read_write_mysql.t: skipped
t/script_oltp_read_write_pgsql.t: skipped
t/script_select_random_mysql.t: skipped
t/script_select_random_pgsql.t: skipped
t/test_cpu.t: passed
t/test_fileio.t: passed
t/test_memory.t: passed
t/test_mutex.t: passed
t/test_threads.t: passed
t/tests.t: passed
# Ran 43 tests, 20 skipped, 3 failed.
make[1]: *** [Makefile:969: test] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make: *** [Makefile:919: test] Error 2
make: *** Waiting for unfinished jobs....
FAIL: test_run.sh
============================================================================
Testsuite summary for sysbench 1.0.7
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See tests/test-suite.log
Please report to https://github.com/akopytov/sysbench/issues
============================================================================
make[3]: *** [Makefile:636: test-suite.log] Error 1
make[3]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make[2]: *** [Makefile:744: check-TESTS] Error 2
make[2]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make[1]: *** [Makefile:817: check-am] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/tests'
make: *** [Makefile:498: check-recursive] Error 1
 * ERROR: app-benchmarks/sysbench-1.0.7::local failed (test phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-benchmarks/sysbench-1.0.7::local'`,
 * the complete build log and the output of `emerge -pqv '=app-benchmarks/sysbench-1.0.7::local'`.
 * The complete build log is located at '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/temp/environment'.
 * Working directory: '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7'
 * S: '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7'

>>> Failed to emerge app-benchmarks/sysbench-1.0.7, Log file:

>>>  '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/temp/build.log'

 * Messages for package app-benchmarks/sysbench-1.0.7:

 * ERROR: app-benchmarks/sysbench-1.0.7::local failed (test phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=app-benchmarks/sysbench-1.0.7::local'`,
 * the complete build log and the output of `emerge -pqv '=app-benchmarks/sysbench-1.0.7::local'`.
 * The complete build log is located at '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/temp/environment'.
 * Working directory: '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7'
 * S: '/var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7'
```

**Comment by hydrapolic** [comment]
Is that a hardened machine (pax/grsecurity/selinux)?

**Comment by gktrk** [comment]
> Is that a hardened machine (pax/grsecurity/selinux)?

you got me :)

**Comment by hydrapolic** [comment]
@gktrk, from what I've checked on the net it seems it won't work on hardened. I would restrict the tests for that reason and document that they fail on hardened. What do you think?

**Comment by gktrk** [comment]
```
[  537.811103] PAX: execution attempt in: <anonymous mapping>, 32644756000-326448ae000 32644756000
[  537.811111] PAX: terminating task: /var/tmp/portage/app-benchmarks/sysbench-1.0.7/work/sysbench-1.0.7/src/sysbench(sysbench):21992, uid/euid: 1000/1000, PC: 0000032644765dec, SP: 00000326434f6c70
[  537.811114] PAX: bytes at PC: c7 04 25 a0 74 0a 40 01 00 00 00 49 bc 00 b1 5e e4 6d 00 00 
[  537.811127] PAX: bytes at SP-8: 00000000400a7f70 00000000400b4d88 000003264420c781 0000006de4a14fc0 0000006de45f7ab0 0000000000000002 400b4cb8400a7378 0000000000000000 0000006de45f68d0 00000326434f7700 0000000000000000 
```

It's not using the binary under `${ED}`, so I've pax-marked the other binary as well:
```
src_test() {
	pax-mark m "${S}/src/${PN}"
	emake check test
}
```

It works like this.

**Comment by hydrapolic** [comment]
Thanks @gktrk, so pushed a version setting it for both, test and the final binary.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/2496ccd...87dfbe7. Thanks!

I've simplified the logic by pax-marking the binary at the end of `src_compile()` and removing `src_install()`

**Comment by hydrapolic** [comment]
Thanks

**Pull request closed without merging**
