### PR TITLE
dev-db/influxdb bump version 1.8.0, fix -version option, USE flag doc

### PR DESCRIPTION
**Pull request by podshumok**

### CODE REVIEW

**Comment by juippis** [comment]
Hey, looks like the maintainer doesn't use Github. You have better chances of reaching them by opening a bug at bugzilla. You can then link this PR to that bug, for the maintainer to review and merge, if they so wish.

**Comment by podshumok** [comment]
I can't reach the package maintainer via bugzilla. Relevant bug there is still in unconfirmed state. 1.7.8 is going to be released soon, I believe, and the natural move would be to make a new version bump which is not that easy with go packages for now.

**Comment by robbat2** [comment]
@podshumok this does not build.
Otherwise, thank you for the fantastic work on the license!

If you can fix the build issues, then also update the commit message trailer, and it'll be mostly good to go (GLEP81 changes for user/group should come later I feel).
Footer update:
```
Bug: https://bugs.gentoo.org/691168
Closes: https://bugs.gentoo.org/689880
Closes: https://bugs.gentoo.org/695232
Closes: https://github.com/gentoo/gentoo/pull/12586
```

Build failure
```
>>> Configuring source in /var/tmp/portage-tmpfs/portage/dev-db/influxdb-1.7.9/work/influxdb-1.7.9 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage-tmpfs/portage/dev-db/influxdb-1.7.9/work/influxdb-1.7.9 ...
env GOPATH=/var/tmp/portage-tmpfs/portage/dev-db/influxdb-1.7.9/work/influxdb-1.7.9 go install -a -installsuffix cgo -ldflags=-s -X main.version=1.7.9 -X main.branch=master -X main.commit=23bc63d -v -work -x ./...
go: cannot find main module, but found Gopkg.lock in /var/tmp/portage-tmpfs/portage/dev-db/influxdb-1.7.9/work/influxdb-1.7.9
	to create a module there, run:
	go mod init
 * ERROR: dev-db/influxdb-1.7.9::gentoo failed (compile phase):
 *   compile failed
 * 
```

**Comment by podshumok** [comment]
@robbat2 what golang version do you use?

**Comment by robbat2** [comment]
@podshumok 1.14.1 here

**Comment by podshumok** [comment]
Ok, looks like this version is for pre go-1.13
(the PR is open for half a year)
I'll look into 1.7.10 which is already out

**Comment by r7l** [comment]
Would be great to see a new version in Portage. The maintainer has Github btw. https://github.com/williamh

Not sure why it is stated otherwise in here.

**Comment by a17r** [comment]
Please note that the maintainer of this package does not look at GitHub. All interaction (of remaining changes that would improve 1.8.0) should go to bugzilla.

**Comment by podshumok** [comment]
Hi @robbat2! Thanks for the merge! About one of your follow-up cleanups: please, note, that `pidfile` is not required (and is useless) in `supervise-daemon` managed init file.

**Pull request closed without merging**
