### PR TITLE
Clean up old maintainer needed ebuilds

### PR DESCRIPTION
**Pull request by Moiman**

### CODE REVIEW

**Comment by jonasstein** [comment]
please use repoman ci for commits.
I can't see a reason for the removal of each package. 
You can find some hints here: https://wiki.gentoo.org/wiki/Project:Treecleaner

**Comment by Moiman** [comment]
@jonasstein I did use repoman commit for all commits. I'm not trying to treeclean packages either. Just removing old and unused versions. Usually ones with deprecated  eapi. I checked them with eshowkw.

**Comment by jonasstein** [comment]
I see. I will look into it again.

**Comment by jonasstein** [comment]
all done. Thank you.

**Pull request closed without merging**
