### PR TITLE
app-forensics/lynis-3.0.0 version bump

### PR DESCRIPTION
**Pull request by chusopr**
New version for app-forensics/lynis-3.0.0
Remove app-forensics/lynis-2.7.5 due to vulnerabilities (#728696).
I'm also proposing myself as new maintainer.

Gentoo Bug: https://bugs.gentoo.org/730754

### CODE REVIEW

**Comment by ajakk** [comment]
Please separate version bumps and the removal of old versions into separate commits and reference bug 728696 with a `Bug:` commit tag.

**Comment by chusopr** [comment]
Hi @ajakk, thanks for your review.

I guess the best approach then is to close this PR and submit a new one with a new commit history? Or should I force-push a new commit history to this same PR overwriting the previous one?

Is the attempt to become the proxied maintainer correct? Or should it be split to a new commit too?

**Comment by ajakk** [comment]
You can force push on your branch and this PR will be updated. You've also added yourself to the metadata in a separate commit already so that's fine.

**Comment by chusopr** [comment]
Hi, thanks for your quick reply.

Actually, no, I hadn't split the metadata change into a separate commit. I had pushed a separate commit to make an additional change (https://github.com/chusopr/gentoo/commit/0c15485) but there was a first metadata change bundled with the version bump (https://github.com/chusopr/gentoo/commit/1203c99#diff-564aa0fc531e9f817e812cb3c8d41593).

It was a whole mess because I didn't know these committing rules.

Now this is fixed with the rest of your recommendations in a new commit history I just force-pushed.

**Comment by juippis** [comment]
Sorry, but looks like this has been done already.
a51e4e08b3ed6503b7b9bed9eaa57ad8c07dfb10

**Pull request closed without merging**
