### PR TITLE
dev-php/pecl-parallel-1.1.3: A succinct parallel concurrency API for PHP7

### PR DESCRIPTION
**Pull request by kwhat**
Bug: https://bugs.gentoo.org/702018
Closes: https://bugs.gentoo.org/702018
Signed-off-by: Alex Barker <alex@1stleg.com>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by kwhat** [comment]
Hi @AndrewAmmerlaan,

Seems a lot like the now defunct [Sunrise Overlay](https://wiki.gentoo.org/wiki/Sunrise).

**Comment by AndrewAmmerlaan** [comment]
> Hi @AndrewAmmerlaan,
> 
> Seems a lot like the now defunct [Sunrise Overlay](https://wiki.gentoo.org/wiki/Sunrise).

Indeed, it is very similar. But it is different in that the GURU overlay does not require as much work from the devs. Instead Trusted Contributors also have access to push to the master branch, their role is mainly to make sure that the master branch does not contain malicious ebuilds, and to fix obvious mistakes. This means less work for the devs, and a faster review process of contributions. Thus potentially creating a faster, more interactive and rewarding user-contribution experience.

**Comment by kwhat** [comment]
Good deal, I will stop submitting bugs and just keep this stuff to myself.  Please close my PRs.

**Comment by ajakk** [comment]
Closing as requested.

**Pull request closed without merging**
