### PR TITLE
games-rpg/runescape-launcher: Rev-bump and adjust manifest

### PR DESCRIPTION
**Pull request by herbmillerjr**
Upstream updated without bumping version, so manifest was off. https://bugs.gentoo.org/625884

### CODE REVIEW

**Comment by mgorny** [comment]
Updated = did they actually change anything in the installed files? If they did, then this deserves a revbump. And shouldn't be called 'fixing the Manifest' because it wasn't broken in the first place.

**Comment by herbmillerjr** [comment]
I'll see if I can find a copy of the old .deb package and compare. Any tips on how to locate one would be greatly appreciated!

**Comment by mgorny** [comment]
Oh, you're not the maintainer. We generally presume maintainer may have the old version but since he didn't reply to the bug yet, I wouldn't expect much. In this case, I'd go for revbump just in case.

**Comment by mgorny** [comment]
Also, feel free to add yourself as co-maintainer if you're interested in the package. In the meantime, I'll try to determine if the original maintainer is still available.

**Comment by mgorny** [comment]
No reply still. Please revbump and I'll be happy to merge it.

**Comment by herbmillerjr** [comment]
You got it.

**Comment by mgorny** [comment]
'Any obvious differences' = there are no differences or the differences are non-obvious? ;-)

**Comment by herbmillerjr** [comment]
Well, the reason I say it that way is when I do a diff of the two directories from the uncompressed .deb files, a few files show up as different, but they're the same file size. The only difference is the timestamp.

I ran vbindiff on /usr/share/games/runescape-launcher/runescape and there are indeed bytes that are different, but the file size is exactly the same between the two down to the byte, so I'm not sure what is actually different about any of it. It almost looks like the .deb was generated on two different systems two different ways and that's the only thing that changed, but that's just a hunch.

**Comment by mgorny** [comment]
I kinda suspect upstream is running some kind of 'nightly' package builds there, i.e. repeatedly rebuild the package, possibly updating the system in the meantime. That would explain the insignificant differences but it could also mean that from time to time there could be significant differences (i.e. linking against updated system package).

**Comment by monsieurp** [comment]
@herbmillerjr what's the status of this PR?

**Comment by flappyports** [comment]
no activity

**Comment by herbmillerjr** [comment]
Sorry for going dark on this one. Would it be possible we could reopen this one? I've updated the manifest and have a script running that will alert me when they change the .deb file, thus changing the hash. This is the best I can think of until we can find a way to contact upstream.

**Comment by mgorny** [comment]
Can't do, the branch has probably been moved since then. Please open a new one.

**Pull request closed without merging**
