### PR TITLE
media-libs/libraw: Version bump, restore keywords

### PR DESCRIPTION
**Pull request by a17r**
Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by a17r** [comment]
See also bugs 556440, 555646 - problematic commit for libkdcraw only exists in 0.16.2, this version is fine.

**Comment by mgorny** [comment]
@gentoo/graphics

**Comment by maekke** [comment]
I've bumped this in git. I didn't use your patch because the subslot was wrong (it was bumped to 0.15).

https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=aecf6d7b9e3e19fe9796ac6840d2b326445ff5b8

**Comment by a17r** [comment]
Thx, I missed that.

**Pull request closed without merging**
