### PR TITLE
dev-libs/modsecurity: fix build with slibtool

### PR DESCRIPTION
**Pull request by orbea**
Closes: https://bugs.gentoo.org/913484
Upstream-PR: https://github.com/SpiderLabs/ModSecurity/pull/2980

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution and upstreaming it. You may want to considering adding https://github.com/SpiderLabs/ModSecurity/commit/4d7d1fa376b34509be71208941eabbd7279c8cd9.patch into `SRC_URI` instead of placing the patch in `FILESDIR` (if possible).

**Comment by orbea** [comment]
Would you mind explaining the benefit or reasoning behind that? Its not something I have been asked to do before and I am not sure how reliable to use github PR commit link when upstream has not responded yet?

**Comment by Flowdalic** [comment]
Benefits are that it does not add something to FILESDIR, which is just nice to have, as it reduces the size for ::gentoo for everyone. The main advantages is that you will accidentally to forget to cleanup files FILESDIR once you drop the last ebuild referencing them. And people, including me, forget that all the time.

As long as the commit is part of your repo, the source repo of the PR, the commit's patch URL will be available.

**Comment by orbea** [comment]
Thanks for explaining, I changed my commit as suggested.

> As long as the commit is part of your repo, the source repo of the PR, the commit's patch URL will be available.

This will be true even in the case of force pushing to my branch? I probably won't in this case, but it can be hard to predict.

**Comment by Flowdalic** [comment]
If you want to be sure that the commit exists, then you could tag it and push the tag.

**Comment by orbea** [comment]
Done. https://github.com/orbea/ModSecurity/releases/tag/gentoo-slibtool-patch

**Comment by orbea** [comment]
@Flowdalic Is there anything more I can do here?

**Comment by orbea** [comment]
@hydrapolic Can you please review this PR?

**Pull request closed without merging**
