### PR TITLE
media-sound/spotify: bump to 1.2.40

### PR DESCRIPTION
**Pull request by kernaltrap8**
Bump package to latest available in upstream. Should not need rekeywording to ~amd64 as it is a binary release from Spotify.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by kernaltrap8** [comment]
Im deciding to also update `app-admin/cpulimit`, hopefully it is fine to be in this PR as i dont know how to include it in a separate PR.

**Comment by prometheanfire** [comment]
The first three commits look ok on the face of it (and cpulimit is marked as maintainer-needed, so here can be ok).  It looks like there was a merge request that needed to be removed from the pull request though.

**Comment by kernaltrap8** [comment]
> The first three commits look ok on the face of it (and cpulimit is marked as maintainer-needed, so here can be ok). It looks like there was a merge request that needed to be removed from the pull request though.

Yes.. I had to commit again because I forgot to remake the manifest after dropping the old ebuild, and had to sync my fork with upstream. Is there anything that needs fixing or is this good for merge?

**Comment by eli-schwartz** [comment]
> Yes.. I had to commit again because I forgot to remake the manifest after dropping the old ebuild, and had to sync my fork with upstream. Is there anything that needs fixing or is this good for merge?

Simply do not "sync my fork with upstream", in the general case. Forks don't need to be synced as merging a PR will already handle that. It is only necessary to sync a fork with upstream in the event that merge conflicts occur. BUT when that happens, it is preferable to sync by using the `git rebase` command, rather than `git merge`.

Please use rebase. Thanks.

**Comment by kernaltrap8** [comment]
> > Yes.. I had to commit again because I forgot to remake the manifest after dropping the old ebuild, and had to sync my fork with upstream. Is there anything that needs fixing or is this good for merge?
> 
> Simply do not "sync my fork with upstream", in the general case. Forks don't need to be synced as merging a PR will already handle that. It is only necessary to sync a fork with upstream in the event that merge conflicts occur. BUT when that happens, it is preferable to sync by using the `git rebase` command, rather than `git merge`.
> 
> Please use rebase. Thanks.

i synced it via github itself, i didnt know how to sync with upstream via cli so i just do that. i dont see the big issue here. i had to update the manifest for the package since i had forgotten to, but couldnt push because there were upstream changes. i think at least. i dont remember. i was sick at the time and didnt have my head on straight.

**Comment by eli-schwartz** [comment]
> i dont see the big issue here.

I mean, if policies exist that we all have to follow then it does seem to be a bit of a big issue to not follow them?

Please read https://www.gentoo.org/glep/glep-0066.html#specification -- it is important information.

**Comment by kernaltrap8** [comment]
> > i dont see the big issue here.
> 
> I mean, if policies exist that we all have to follow then it does seem to be a bit of a big issue to not follow them?
> 
> Please read https://www.gentoo.org/glep/glep-0066.html#specification -- it is important information.

okay, but what do i need to do to fix it? just saying "follow this policy" doesnt help when the damage is already done.

**Comment by prometheanfire** [comment]
If it were me, I'd make a new branch off of master, then `git cherry-pick` the sha's for each of the commits you want me to approve.  I could also select a few commits from the ones here if you want.

**Comment by eli-schwartz** [comment]
Currently providing live help in IRC. And the Manifest needs to be updated in the second commit, still. :)

**Comment by prometheanfire** [comment]
I'm there too if you want to ping me (I looked in the proxy-maint channel but didn't see you?)

**Comment by prometheanfire** [comment]
:checkered_flag:

**Pull request closed without merging**
