### PR TITLE
sys-kernel/rt-sources: version bumps

### PR DESCRIPTION
**Pull request by karllinden**
@aliceinwire

### CODE REVIEW

**Comment by aliceinwire** [comment]
please make atomic commits

**Comment by karllinden** [comment]
@aliceinwire But these commits are atomic?

**Comment by aliceinwire** [comment]
please squash it in one commit.

**Comment by karllinden** [comment]
@aliceinwire Alright, I have squashed the commits. I want to point out that @mgorny wanted the versions to be committed separately in https://github.com/gentoo/gentoo/pull/5295.

**Comment by aliceinwire** [comment]
@karllinden talked with @mgorny and yes you are right please split it, sorry.

**Comment by karllinden** [comment]
@aliceinwire Okay, the commits are splitted again. I also removed an old ebuild.

**Pull request closed without merging**
