### PR TITLE
dev-libs/{libbson,mongo-c-driver}: bump to 1.11.0

### PR DESCRIPTION
**Pull request by hydrapolic**
Thank you :)

### CODE REVIEW

**Comment by hydrapolic** [comment]
@gentoochainsaw, can be merged? :)

**Comment by gentoochainsaw** [comment]
Sorry, I no longer participate in the Gentoo Github project. You will have to rely on other developers.

**Comment by hydrapolic** [comment]
@gentoochainsaw, ok thanks for the update.

**Comment by hydrapolic** [comment]
Thanks, @ultrabug

**Pull request closed without merging**
