### PR TITLE
net-irc/kvirc: Install reasonable defaults during dodoc.

### PR DESCRIPTION
**Pull request by DarthGandalf**
Fixes build after https://github.com/kvirc/KVIrc/pull/2366

### CODE REVIEW

**Comment by mgorny** [comment]
@Arfrever

**Comment by Arfrever** [comment]
Maybe I should set empty `DOCS=()`...
`ChangeLog` was updated last time in 2014.
`README.md` is mostly irrelevant to Gentoo users.

**Comment by DarthGandalf** [comment]
Yeah, see https://github.com/kvirc/KVIrc/pull/2365 regarding the changelog.

**Comment by Arfrever** [comment]
Installation failure was fixed in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=fb87683b787f65dc4775674d8e6f4b720078c4ee.
Please close this pull request.

(If `ChangeLog` becomes useful in the future, I might re-consider installing it.)

**Pull request closed without merging**
