### PR TITLE
dev-libs/intel-compute-runtime: add patch to remove `-D_FORTIFY_SOURCE=2` configuration from build process

### PR DESCRIPTION
**Pull request by ran-dall**
Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Comment by ran-dall** [comment]
ping @thesamesam

**Comment by ConiKost** [comment]
Can't be this done with sed instead using a patch for it?

**Comment by ran-dall** [comment]
@ConiKost It could, but we decided to get rid of the whole line so I think we decided on a `patch`, but honestly either way is good with me.

**Review by ConiKost — APPROVED** [review]
lgtm. Just a small nit pick: I added ```${PN}-${PV}``` to patch name and updated ebuild. Otherwise merged as it is.

**Comment by ran-dall** [comment]
Thank you @ConiKost 🤝

**Pull request closed without merging**
