### PR TITLE
app-shells/atuin: add 16.0.0, add 'self-hosting' USE flag

### PR DESCRIPTION
**Pull request by freijon**
## Notable changes:

- Minimal rust version 1.71.0 (according to upstream dev. I didn't try to build it with latest stable on ::gentoo)
- New use flag "self-hosting". I can remove it if you don't like it. But I think most users will not need this feature (thus: disabled by default). You need a working PostgreSQL db to use this feature. It also uses a different config file. Reduces the output binary size by 4.25 MB

### CODE REVIEW

**Comment by Flowdalic** [comment]
Is there a reason to drop 15.0? I'd like to stabilize atuin at some point

**Comment by freijon** [comment]
I usually look how many versions there were before and keep it the same. But I didn't consider that 15.0.0 was the first/only version on Gentoo. We can keep 15.0.0 if you want to stabilize it.

**Comment by Flowdalic** [comment]
Then let's not drop 15.0. PR looks otherwise fine. Good work and thanks for your contribution.

**Comment by Flowdalic** [comment]
Thanks, please also see https://github.com/gentoo/gentoo/commit/d8cda4beebb8cf112236181810e3b0ea71094243

**Pull request closed without merging**
