### PR TITLE
app-emacs/ws-butler: Use elisp test runner instead of default src_test

### PR DESCRIPTION
**Pull request by qookei**
Closes: https://bugs.gentoo.org/922377

### CODE REVIEW

**Comment by xgqt** [comment]
Thanks for poining it out, but if that's all it takes I would rather have src_test overwritten, don't you agree?

Just add this as last line:

> elisp-enable-tests ert tests -l tests/run-test.el

**Comment by qookei** [comment]
Okay yeah, that seems like a significantly better idea

**Comment by qookei** [comment]
Changed that, should be good to go now.

**Comment by xgqt** [comment]
Perfect. It will be merged today.

**Review by xgqt — APPROVED** [review]

**Pull request closed without merging**
