### PR TITLE
dev-lisp/sbcl: Add system-bootstrap, unmask on musl.

### PR DESCRIPTION
**Pull request by vi-improved**
May need review.

### CODE REVIEW

**Comment by vi-improved** [comment]
Converted to draft until I can do more extensive testing tonight or tomorrow.

**Comment by thesamesam** [comment]
The current structure of this is useful for reviewing, but it needs to be a new revision without modifying the old ones given it's quite an invasive change.

**Comment by vi-improved** [comment]
Got it. Will do.

**Comment by vi-improved** [comment]
Quick question: would it be a g better idea to make the flag with "system-bootstrap", and make it depend on `|| ( dev-lisp/clisp dev-lisp/sbcl)` so clisp can be depcleaned atter installation?

**Comment by vi-improved** [comment]
Converted back to draft, I'm still doing some work on this.

**Comment by vi-improved** [comment]
SBCL should be able to bootstrap itself from an existing installation now, so no need to have both CLisp and SBCL installed at the same time after initial installation. Doing more testing now.

**Comment by vi-improved** [comment]
Bootstrapping from clisp, SBCL Installation, and SBCL binary all work on my system, removing draft status again.

**Comment by vi-improved** [comment]
@thesamesam

**Comment by thesamesam** [comment]
Great work! Thank you!

**Pull request closed without merging**
