### PR TITLE
app-editors/neovim: Delete useless patch

### PR DESCRIPTION
**Pull request by qsdrqs**
I noticed that neovim-9999 building will fail after [this commit](https://github.com/neovim/neovim/pull/18914) because the `darwin` patch can't apply. 

However, I also noticed that this `darwin` patch might be useless because the deleted blocks by this patch will only judge whether the system is OSX (in gentoo definitely no), and it will not introduce more compiling tasks.

So I think this patch is useless and can be deleted to reduce the maintenance work.

Signed-off-by: Tianyang Zhou <qsdrqs@gmail.com>

### CODE REVIEW

**Comment by qsdrqs** [comment]
Is there any review of this PR?

**Comment by DarkDefender** [comment]
@thesamesam Are there any guidelines on what to do when the maintainers for the package doesn't respond?

**Comment by DarkDefender** [comment]
@qsdrqs you need to include the sign-off in the commit message

**Comment by qsdrqs** [comment]
> @qsdrqs you need to include the sign-off in the commit message

Ok, fixed

**Comment by thesamesam** [comment]
You're wrong there -- the patch was added _for Gentoo_ on macOS Prefix! But it needs rebasing indeed. I guess let's just drop it for now.

As for when maintainers don't respond, yes, you can invoke maintainer timeout and ping someone else to merge after a week or 2 weeks depending on how sensitive it is .

**Comment by qsdrqs** [comment]
All right, I didn't know Gentoo can be installed on MacOS before... 

Just a reminder that the new neovim 0.7.2 ebuild script in this repository also doesn't contain this darwin patch

**Comment by thesamesam** [comment]
Thanks for the spot! Yep, Prefix is wild and it lets you run Gentoo on all sorts of kernels and in all sorts of environments :)

**Pull request closed without merging**
