### PR TITLE
kde-apps: Move a bigger part of 15.08.3 to tree

### PR DESCRIPTION
**Pull request by a17r**
Moved all of:
- [x] kdeaccessibility
- [x] kdeartwork (nothing else to be done?)
 - kdeartwork-meta: Add USE=minimal (same as in 4.14.3)
- [x] kdegames
 - katomic added patch to fix configure with USE=handbook
 - kblocks bumped for new dependencies
 - kdegames-meta: Move kubrick behind USE=opengl
 - kfourinline bumped for new dependencies
 - kshisen added patch to fix dependencies
 - libkdegames bumped for new dependencies, dropped patch in favor of KDE_TEST=forceoptional
- [x] kdegraphics
 - gwenview bumped for new dependencies
- [x] kdesdk
 - kde-dev-scripts ported to kde5.eclass
- [x] kdeutils
 - kcalc bumped for fixed dependencies
 - kteatime bumped for runtime fix
 - kwalletmanager-15.04.3:4 re-introduced for USE=minimal and fixes
 - kwalletmanager bumped for new dependency
 - print-manager bumped for new dependencies
- [x] kdewebdev
 - with klinkstatus dropped from meta (conflicts with kdepimlibs-15.08.3)

...including meta ebuilds.

Also kde-apps/gpgmepp as the only part of kdepimlibs:4 that can be co-installed with kdepimlibs:5.

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/kde?

**Comment by kensington** [comment]
We'll have to do this in bits, some ebuilds are still of varying quality: https://wiki.gentoo.org/wiki/Project:KDE/Frameworks/Applications#Applications

**Comment by a17r** [comment]
Yes, I'm somewhat halfway through games ebuilds, but more needs to be done.

**Comment by mgorny** [comment]
@a17r, all ready now?

**Comment by a17r** [comment]
(imo) yes, though @kensington might have some better unused-deps magic, and with the exception of kteatime which seems to have a major (upstream) showstopper at runtime.

**Comment by a17r** [comment]
kteatime showstoper bugfix went upstream, patch included here

**Comment by kensington** [comment]
Thanks, all done!

**Pull request closed without merging**
