### PR TITLE
www-servers/nginx: add 1.25.4

### PR DESCRIPTION
**Pull request by hydrapolic**
Bug: https://bugs.gentoo.org/924619

### CODE REVIEW

**Comment by hydrapolic** [comment]
Hello @ConiKost

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Hmm, why has 1.25.3-r1 dropped so many keywords?

**Comment by hydrapolic** [comment]
> Is it due to test deps? We could just use.mask `test` instead, easier to approach it like that.

Yes, seems like that, this is the diff:

```bash
--- nginx-1.25.3.ebuild 2023-12-01 20:10:39.000000000 +0000
+++ nginx-1.25.3-r1.ebuild      2023-11-22 12:10:41.000000000 +0000
@@ -11,6 +11,7 @@
 #      * sane packaging
 #      * builds cleanly
 #      * does not need a patch for nginx core
+# - Update NGINX_TESTS_REV to the current available revision and run tests.
 # - TODO: test the google-perftools module (included in vanilla tarball)
 
 # prevent perl-module from adding automagic perl DEPENDs
@@ -164,11 +165,14 @@
 NJS_MODULE_URI="https://github.com/nginx/njs/archive/${NJS_MODULE_PV}.tar.gz"
 NJS_MODULE_WD="${WORKDIR}/njs-${NJS_MODULE_PV}"
 
+# nginx-tests (http://hg.nginx.org/nginx-tests, BSD-2)
+NGINX_TESTS_REV="24482e311749"
+
 # We handle deps below ourselves
 SSL_DEPS_SKIP=1
 AUTOTOOLS_AUTO_DEPEND="no"
 
-inherit autotools lua-single ssl-cert toolchain-funcs perl-module systemd pax-utils
+inherit autotools lua-single multiprocessing ssl-cert toolchain-funcs perl-module systemd pax-utils
 
 DESCRIPTION="Robust, small and high performance http and reverse proxy server"
 HOMEPAGE="https://nginx.org"
@@ -201,17 +205,17 @@
        nginx_modules_http_vhost_traffic_status? ( ${HTTP_VHOST_TRAFFIC_STATUS_MODULE_URI} -> ${HTTP_VHOST_TRAFFIC_STATUS_MODULE_P}.tar.gz )
        nginx_modules_stream_geoip2? ( ${GEOIP2_MODULE_URI} -> ${GEOIP2_MODULE_P}.tar.gz )
        nginx_modules_stream_javascript? ( ${NJS_MODULE_URI} -> ${NJS_MODULE_P}.tar.gz )
-       rtmp? ( ${RTMP_MODULE_URI} -> ${RTMP_MODULE_P}.tar.gz )"
+       rtmp? ( ${RTMP_MODULE_URI} -> ${RTMP_MODULE_P}.tar.gz )
+       test? ( https://hg.nginx.org/nginx-tests/archive/${NGINX_TESTS_REV}.tar.gz -> nginx-tests-${NGINX_TESTS_REV}.tar.gz )"
 
 LICENSE="BSD-2 BSD SSLeay MIT GPL-2 GPL-2+
        nginx_modules_http_security? ( Apache-2.0 )
        nginx_modules_http_push_stream? ( GPL-3 )"
 SLOT="mainline"
-KEYWORDS="amd64 arm arm64 ~loong ~ppc ~ppc64 ~riscv x86 ~amd64-linux ~x86-linux"
+KEYWORDS="~amd64 ~x86 ~amd64-linux ~x86-linux"
 
-# Package doesn't provide a real test suite
-RESTRICT="test"
+RESTRICT="!test? ( test )"
 
 NGINX_MODULES_STD="access auth_basic autoindex browser charset empty_gif
        fastcgi geo grpc gzip limit_req limit_conn map memcached mirror
@@ -252,7 +256,7 @@
        stream_javascript
 "
 
-IUSE="aio debug +http +http2 http3 +http-cache ktls libatomic pcre +pcre2 pcre-jit rtmp selinux ssl threads vim-syntax"
+IUSE="aio debug +http +http2 http3 +http-cache ktls libatomic pcre +pcre2 pcre-jit rtmp selinux ssl test threads vim-syntax"
 
 for mod in $NGINX_MODULES_STD; do
        IUSE="${IUSE} +nginx_modules_http_${mod}"
@@ -327,7 +331,24 @@
 DEPEND="${CDEPEND}
        arm? ( dev-libs/libatomic_ops )
        libatomic? ( dev-libs/libatomic_ops )"
-BDEPEND="nginx_modules_http_brotli? ( virtual/pkgconfig )"
+BDEPEND="
+       nginx_modules_http_brotli? ( virtual/pkgconfig )
+       test? (
+               dev-lang/perl
+               dev-perl/Cache-Memcached
+               dev-perl/Cache-Memcached-Fast
+               dev-perl/CryptX
+               dev-perl/FCGI
+               dev-perl/GD
+               dev-perl/Net-SSLeay
+       )"
+# Unpackaged perl modules which would be used by tests
+# Protocol::WebSocket
+# SCGI
+
+# Uwsgi doesn't start in tests
+# www-servers/uwsgi
+
 PDEPEND="vim-syntax? ( app-vim/nginx-syntax )"
 
 REQUIRED_USE="pcre-jit? ( pcre )
@@ -827,6 +848,19 @@
        fi
 }
 
+src_test() {
+       pushd "${WORKDIR}"/nginx-tests-"${NGINX_TESTS_REV}" > /dev/null || die
+
+       # FIXME: unsure why uwsgi fails to start
+       rm uwsgi*.t || die
+
+       local -x TEST_NGINX_BINARY="${S}/objs/nginx"
+       local -x TEST_NGINX_VERBOSE=1
+
+       prove -v -j $(makeopts_jobs) . || die
+       popd > /dev/null || die
+}
+
 pkg_postinst() {
        if use ssl; then
                if [[ ! -f "${EROOT}"/etc/ssl/${PN}/${PN}.key ]]; then
```

I don't see a bug for KW request. Maybe the author of https://github.com/gentoo/gentoo/commit/5556c6e4683c80d27c4583e13aa3bc21e9a6c05e could help here? @parona-source

**Comment by parona-source** [comment]
> I don't see a bug for KW request. Maybe the author of [5556c6e](https://github.com/gentoo/gentoo/commit/5556c6e4683c80d27c4583e13aa3bc21e9a6c05e) could help here? @parona-source

This is a failing on my part for forgetting that there were dropped keywords by the time it was merged.

https://github.com/gentoo/gentoo/pull/33260#issuecomment-1778325559

**Comment by hydrapolic** [comment]
Hello @parona-source, I would agree with @juippis that we block tests on unkeyworded platforms for now, what do you think?

**Comment by juippis** [comment]
I can handle it tomorrow (in ~12 hours) but if someone wants to PR it before then, no objections :)

**Comment by ConiKost** [comment]
@hydrapolic Sorry for being late, but thanks to @juippis ,all PR was handled. Just a quick question, any reason to use njs 0.8.2 instead of newest 0.8.3?

**Comment by hydrapolic** [comment]
> @hydrapolic Sorry for being late, but thanks to @juippis ,all PR was handled. Just a quick question, any reason to use njs 0.8.2 instead of newest 0.8.3?

Missed the njs update on the webpage, we can update njs to 0.8.3. Since I don't use it I tent to forget about it.

**Pull request closed without merging**
