### PR TITLE
BFGMiner 5.4.1 bump

### PR DESCRIPTION
**Pull request by luke-jr**
@blueness

### CODE REVIEW

**Comment by blueness** [comment]
@luke-jr I don't know why this is failing.

**Comment by blueness** [comment]
@luke-jr let me be more specific, i'm not sure why you're hitting the dep problem you are, can you please fix it before I merge.  same with the bitcoincore eclass.

**Comment by luke-jr** [comment]
It doesn't look related to Core or BFGMiner as far as I can tell...

**Comment by blueness** [comment]
i committed these and checked carefully with repoman full

**Pull request closed without merging**
