### PR TITLE
media-libs/freeverb3: EAPI-7 bump, fix audacious USE-dep

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by a17r** [comment]
`get_libdir` is part of EAPI-6 itself so no need to add `multilib`. See also: https://blogs.gentoo.org/mgorny/2015/11/13/the-ultimate-guide-to-eapi-6/

**Comment by hartwork** [comment]
Thanks!

We would we want to `Drop gtk, qt5 from 3.9; gtk3-only` from Audacious 3.9? Yes, 3.10 dropped gtk3 but why touch 3.9?

**Comment by a17r** [comment]
> For the rest of this pull request I don't follow why we'd need a revbump

We need revbumps because of the dep changes.

> why the audacious dependency nees a change and why we'd want to drop Audacious 3.9 and how freeverb3 would still be working then. if you could writre a bit of prose to enlighten me, that would be welcome.

audacious-3.9 `REQUIRED_USE` is a horrible mess that is fixed by dropping the gtk and qt option from 3.9. 3.9 is retained as gtk3-only version so that freeverb3 continues to work.

**Comment by hartwork** [comment]
I'm unsure if that's the right direction for audacious-3.9 but it's not mine, maybe some else can +1 or -1 on that.

I don't see what is broken in `>=media-sound/audacious-3.9[gtk3]` that would be fixed `=media-sound/audacious-3.9*[gtk3(+)]`. Is suppose to be a "style fix"?

**Comment by a17r** [comment]
> I'm unsure if that's the right direction for audacious-3.9 but it's not mine, maybe some else can +1 or -1 on that.

I'll do that in my own responsibility while also fixing a lot of stuff there.

> I don't see what is broken in `>=media-sound/audacious-3.9[gtk3]` that would be fixed `=media-sound/audacious-3.9*[gtk3(+)]`. Is suppose to be a "style fix"?

This is a `USE` dependency default. It means the dependency is fulfulled by audacious[gtk3] as well as audacious [no gtk3 use flag] assuming the latter contains the functionality requested by `gtk3`.

**Comment by hartwork** [comment]
Because you dropped `IUSE=".. gtk3 .."` from Audacious 3.9.x, I see.

If freeverb3 still emerges fine after, I'm good :)

**Comment by a17r** [comment]
Thanks for looking over it.

This PR now depends on https://bugs.gentoo.org/671890 for the audacious cleanup.

**Pull request closed without merging**
