### PR TITLE
latest version of aufs-sources

### PR DESCRIPTION
**Pull request by adioskid**
Hi, I made a ebuild with the latest version of the aufs sources, with the latest patch.

Signed-off-by: Lucas C.S. lucascs@protonmail.com

### CODE REVIEW

**Comment by adioskid** [comment]
Sorry, I send another commit, was a mistake

**Comment by adioskid** [comment]
missing something?

**Comment by DarthGandalf** [comment]
> missing something?

You didn't sign off the commit. https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Comment by ConiKost** [comment]
I am sorry, but aufs-sources got dropped: https://gitweb.gentoo.org/repo/gentoo.git/commit/sys-kernel/aufs-sources?id=12a57dcdb261de4c2230101532d477876c9525ba

**Pull request closed without merging**
