### PR TITLE
net-p2p/classified-ads: add missing DEPEND on gettext for 0.10

### PR DESCRIPTION
**Pull request by gktrk**
Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by idella** [comment]
so after all that is is needed. all right

**Comment by operatornormal** [comment]
Looks like ok patch to me. Gettext was originally in RDEPEND (see https://github.com/gentoo/gentoo/pull/1327) but was removed because it is not needed at runtime. Gettext is indeed used in build process  so adding it there is no mistake and definitely breaks nothing. 

--
Antti Järvinen

**Comment by monsieurp** [comment]
@idella @gentoo/proxy-maint

**Comment by idella** [comment]
ok all good thx gok

**Pull request closed without merging**
