### PR TITLE
app-arch/upx{,-bin} update to 4.2.4

### PR DESCRIPTION
**Pull request by winterheart**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
This PR fails to apply due to commit 3bfe682893548e6fa2bdce8f2072fafca247027d. Can you rebase?

**Comment by winterheart** [comment]
Done.

**Comment by eli-schwartz** [comment]
I tried to install and run upx-bin, but could not. Then I realized that it installs the binary to /opt and doesn't symlink it to /usr/bin, so it is not usable via $PATH.

This seems to be a decision we inherited from 2003: https://bugs.gentoo.org/17794 (reported by @robbat2). I'm not sure I agree with that initial resolution to begin with, but it's been over 20 years and frankly prelink has been given up as a bad idea...

**Comment by winterheart** [comment]
I don't have such issues. upx-bin installs into `/opt/bin/upx` and `/opt/bin` is in PATH according to `/etc/env.d/50baselayout`:

```
~ /etc/env.d $ grep -r 'opt/bin'
50baselayout:PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin"
50baselayout:ROOTPATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/bin"
```

**Comment by eli-schwartz** [comment]
Hmm, I did not realize it did that. :eyes:
Also, my test chroot apparently stopped sourcing /etc/profile somehow. My bad.

**Pull request closed without merging**
