### PR TITLE
net-im/discord-bin: add maintainer

### PR DESCRIPTION
**Pull request by ran-dall**
This commit also adds additional trivial comments and fixes a minor compliance issue.

Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Comment by ran-dall** [comment]
@thesamesam, sorry for bugging ya, mate. I figured I'd be considered a Proxy Maintainer (for now), so I hope I added myself correctly.

**Comment by ran-dall** [comment]
@thesamesam, I apologize; I didn't see your comments last night on the previous PR before opening this. Regardless, I've updated the ebuild to use `/opt/discord`.

**Comment by thesamesam** [comment]
Thanks! Could you clarify what the compliance issue is that you fixed too?

**Comment by thesamesam** [comment]
Sorry, I didn't mean to push this earlier -- I'd started `pram`ing things then pushed some stablereqs:
```
commit 6a2b2e7256f76bd39a5adf27429f7fb5976dfb88 (HEAD -> master, origin/master, origin/HEAD)
Author: Sam James <sam@gentoo.org>
Date:   Fri May 20 03:40:01 2022 +0100

    Revert "net-im/discord-bin: add maintainer; tidy ebuild"

    This reverts commit d83c48e3e6bde9fda19bd17bbaa171f3b7dc7490.

    (Didn't mean to push this with the lot earlier -- pushed with
    a bunch of stablereqs and forgot I'd started doing PRs.)

    Signed-off-by: Sam James <sam@gentoo.org>
```

It doesn't install for me because of the mixed capitalisations.

**Comment by ran-dall** [comment]
@thesamesam 😥 Sorry about that. I just pushed the fixes. It should all be good now.

**Comment by ran-dall** [comment]
> ```shell
> * QA Notice: Files built without respecting CFLAGS have been detected
> * Please include the following list of files in your report:
> * /opt/discord/Discord
> * QA Notice: Files built without respecting LDFLAGS have been detected
> *  Please include the following list of files in your report:
> * /opt/discord/Discord
> ```

@juippis, I can't seem to get this error.

**Comment by juippis** [comment]
Shouldn't happen in ::gentoo anymore, 1e047cc733c9384eee474fc1720a19bf2250a2d7

**Pull request closed without merging**
