### PR TITLE
www-client/epiphany-40 and net-libs/webkit-gtk-2.32.0 bumps

### PR DESCRIPTION
**Pull request by mattst88**
@thesamesam: can you help test webkit-gtk? Specifically with and without USE=opengl and USE=jumbo-build.

### CODE REVIEW

**Comment by thesamesam** [comment]
@mattst88 of course! Running now, will need to upgrade to ~arch GNOME first

**Comment by thesamesam** [comment]
Not forgot about you. Hit some horrible seccomp incompatibility with old systemd on Debian. Upgraded the box now and I've set off tatt now.

**Comment by mattst88** [comment]
> All failed with the same error: [1.txt](https://github.com/gentoo/gentoo/files/6441964/1.txt)
> 
> > /var/tmp/portage/net-libs/webkit-gtk-2.32.0/work/webkitgtk-2.32.0/Source/JavaScriptCore/runtime/IntlSegmenter.cpp:128:77: error: ‘ubrk_safeClone’ was not declared in this scope; did you mean ‘ucol_safeClone’?
> 
>     * USE='X -egl examples -gamepad geolocation -gles2-only -gnome-keyring gstreamer -gtk-doc -introspection jpeg2k jumbo-build -libnotify -opengl -spell -systemd -wayland'
> 
>     * USE='X egl -examples -gamepad -geolocation gles2-only -gnome-keyring gstreamer -gtk-doc introspection -jpeg2k jumbo-build -libnotify -opengl -spell systemd -wayland'
> 
>     * USE='X egl -examples gamepad geolocation gles2-only -gnome-keyring gstreamer -gtk-doc introspection -jpeg2k -jumbo-build libnotify -opengl spell systemd wayland'
> 
> 
> Testing the others now.

Strange. I cannot reproduce these failures.

I repushed with an upstream patch that fixes the build with USE="-opengl -gles2-only".

I'm still seeing USE="opengl" fail to build with an error about `primitiveRestartIndex`.

**Comment by mattst88** [comment]
@thesamesam: okay, I added a new patch that I've submitted upstream and dropped some other patches that don't seem to be necessary anymore. The build works for me in all configurations I tried. Please give it a test!

**Comment by thesamesam** [comment]
Thanks Matt! Trying it... (frustratingly, I had that same error for +/- OpenGL x jumbo-build)

**Comment by thesamesam** [comment]
Frustratingly, still seeing:
```
/var/tmp/portage/net-libs/webkit-gtk-2.32.0/work/webkitgtk-2.32.0/Source/JavaScriptCore/runtime/IntlSegments.cpp: In member function ‘JSC::JSObject* JSC::IntlSegments::createSegmentIterator(JSC::JSGlobalObject*)’:
/var/tmp/portage/net-libs/webkit-gtk-2.32.0/work/webkitgtk-2.32.0/Source/JavaScriptCore/runtime/IntlSegments.cpp:103:77: error: ‘ubrk_safeClone’ was not declared in this scope; did you mean ‘ucol_safeClone’?
  103 |     auto segmenter = std::unique_ptr<UBreakIterator, UBreakIteratorDeleter>(ubrk_safeClone(m_segmenter.get(), nullptr, nullptr, &status));
      |                                                                             ^~~~~~~~~~~~~~
      |                                                                             ucol_safeClone
```
all the time.

But we can e.g. drop ~arm64 or mask it there for now while we debug it, no need to hold up merging.

**Comment by thesamesam** [comment]
Maybe 2.32.1 will be better? I'm not sure where to find the webkit-gtk sources, I didn't poke too hard but could only find the monorepo which made looking through history a pain.

**Comment by mattst88** [comment]
Hm, are you using `dev-libs/icu-69`? I see this in the WebKit ChangeLog:

````
2021-04-12  Ross Kirsling  <ross.kirsling@sony.com>

        ICU 69 deprecates ubrk_safeClone in favor of ubrk_clone
        https://bugs.webkit.org/show_bug.cgi?id=224093

        Reviewed by Yusuke Suzuki.

        In a shining example of "disappointing library practices", ICU 69 deprecates ubrk_safeClone in favor of
        a new *draft* API ubrk_clone, meaning that no function with this functionality is exposed by default.

        This patch introduces a function cloneUBreakIterator to abstract over this change; however, since we need to:

          1. confine the effects of disabling U_HIDE_DRAFT_API to a non-unified implementation file
          2. still be able to include ubrk.h from IntlSegmenter.h to instantiate ICUDeleter<ubrk_close> (*not* `clone`!)

        ...the new helper function is introduced in a *headerless* implementation file, IntlWorkaround.cpp.
````

**Comment by thesamesam** [comment]
No worries, I was just feeling guilty about being the hold up.

FYI it's looking good here, it's just building various combinations now

**Comment by mattst88** [comment]
Pushed without WebGL2 support.

**Pull request closed without merging**
