### PR TITLE
elastic: update elasticsearch/kibana/logstash/filebeat

### PR DESCRIPTION
**Pull request by hydrapolic**
Versions 6.8.15 / 7.12.0 with license change :(

Thank you for your time!

### CODE REVIEW

**Comment by ulm** [comment]
@gentoo/licenses: I wonder if this is a candidate for the EULA license group?

@hydrapolic: Can you file a bug for the Elastic-2.0 license, please? Assign to licenses@gentoo.org. Note that this isn't meant to be a blocker for this PR, but the licenses team should check the status.

**Review by juippis — APPROVED** [review]
```
app-admin/logstash-bin
  IncorrectCopyright: version 6.8.15: incorrect copyright year 2020: '# Copyright 1999-2020 Gentoo Authors'

app-admin/filebeat
  StableRequest: version 7.10.2: slot(0) no change in 67 days for unstable keyword: [ ~amd64 ]
  IncorrectCopyright: version 7.12.0: incorrect copyright year 2020: '# Copyright 1999-2020 Gentoo Authors'
```
I'm seriously starting to get tired to fix these after you. Please start using repoman to commit. Next time I'll reject it.

Also please do open the bug as @ulm instructed.

**Comment by hydrapolic** [comment]
> @gentoo/licenses: I wonder if this is a candidate for the EULA license group?
> 
> @hydrapolic: Can you file a bug for the Elastic-2.0 license, please? Assign to [licenses@gentoo.org](mailto:licenses@gentoo.org). Note that this isn't meant to be a blocker for this PR, but the licenses team should check the status.

https://bugs.gentoo.org/779460

**Comment by hydrapolic** [comment]
> ```
> app-admin/logstash-bin
>   IncorrectCopyright: version 6.8.15: incorrect copyright year 2020: '# Copyright 1999-2020 Gentoo Authors'
> 
> app-admin/filebeat
>   StableRequest: version 7.10.2: slot(0) no change in 67 days for unstable keyword: [ ~amd64 ]
>   IncorrectCopyright: version 7.12.0: incorrect copyright year 2020: '# Copyright 1999-2020 Gentoo Authors'
> ```
> 
> I'm seriously starting to get tired to fix these after you. Please start using repoman to commit. Next time I'll reject it.
> 
> Also please do open the bug as @ulm instructed.

Thank you @juippis, sorry for that, I currently don't have gpg on my test machine from where I commit so I do plain git. I'll try to re-add repoman or pkgcheck, I thought the CI checks here should check it and block merging. Sorry for the trouble.

**Comment by juippis** [comment]
Well that does explain a bit. The CI check can't catch it because it's a commit error. You should be able to run `pkgcheck scan --commits` locally before doing git push without gpg.

**Pull request closed without merging**
