### PR TITLE
dev-python/jedi: add pypy3 support to all jedi ebuilds

### PR DESCRIPTION
**Pull request by tgbugs**
Part of a series of PRs working toward pypy3 support for IPython.
Bug: https://bugs.gentoo.org/729958

### CODE REVIEW

**Comment by tgbugs** [comment]
Bug: https://bugs.gentoo.org/729958

**Comment by mgorny** [comment]
Please merge it all into a single PR.
--
Best regards, 
Michał Górny

**Comment by tgbugs** [comment]
Will do and will close the others.

**Comment by mgorny** [comment]
Thank you. Please ping me if I don't review it today.
--
Best regards, 
Michał Górny

**Pull request closed without merging**
