### PR TITLE
sci-physics/fastjet: add 3.4.2

### PR DESCRIPTION
**Pull request by APN-Pucky**
PR created by [pkgpr](https://github.com/APN-Pucky/pkgpr).

Does not work with dash. Too many m4 modules that use bash ifs.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
> Does not work with dash. Too many m4 modules that use bash ifs.

Do these modules have `/bin/sh` in the shebang, if not then this is no problem. Otherwise we should find+sed these shebangs to `/bin/bash`.

**Comment by APN-Pucky** [comment]
> > Does not work with dash. Too many m4 modules that use bash ifs.
> 
> Do these modules have `/bin/sh` in the shebang, if not then this is no problem. Otherwise we should find+sed these shebangs to `/bin/bash`.

Yes, I think the easiest way is just to replace it in the configure file after reconfigure. Do I have to depend on bash explicitly then?

**Comment by AndrewAmmerlaan** [comment]
> Do I have to depend on bash explicitly then?

You can, but its not required because bash is in the `@system` set, and also a dependency of portage.

**Comment by AndrewAmmerlaan** [comment]
Great, now it works!

Fixed this while merging:
```
VariableShadowed: version 3.4.2: variable 'BDEPEND' may be shadowed, on lines: 35, 36
```
We don't need to depend on fortran anyway since the eclass adds it for us.

**Pull request closed without merging**
