### PR TITLE
dev-util/codeblocks: update to EAPI-7 and fix RDEPEND in live-ebuild and 17.12-r302

### PR DESCRIPTION
**Pull request by band-a-prend**
@leio please review this pull request

### CODE REVIEW

**Comment by leio** [comment]
Why is the revbump with fixes done only to the gtk2 version, which we were pondering on dropping overall instead, while gtk3 revisions retain EAPI-6 and astyle/tinyxml dependency problems?

**Comment by band-a-prend** [comment]
You ask once to make new revisions only for gtk3, so I create -r2 as gtk3.
Should I rename it to -r302?

**Comment by leio** [comment]
oh - but r2 is "older" than r301, so ~arch people won't even get an upgrade. So, yes, with amended commit, not follow-up of course.

**Comment by leio** [comment]
as discussed on IRC, this is now pending a s/epatch/eapply/ fix

**Pull request closed without merging**
