### PR TITLE
media-libs/lsp-plugins: Add missing libglvnd[X] USE dependendency

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Closes: https://bugs.gentoo.org/737536

Signed-off-by: Simon van der Veldt <simon.vanderveldt+gentoo@gmail.com>

### CODE REVIEW

**Comment by fordfrog** [comment]
@simonvanderveldt thank you for the fix. though as this is a compile-time fix, you should do the fix without revbump. could you please update the pr? or i can fix it directly, your choice. it also needs to inherit xdm as the icon cache is not updated correctly. that's the issue of the original ebuild and not of your patch, but this should be fixed aswell.

**Comment by fordfrog** [comment]
also, looking at the upstream site, 1.1.29 is already out.

**Comment by simonvanderveldt** [comment]
> @simonvanderveldt thank you for the fix. though as this is a compile-time fix, you should do the fix without revbump. could you please update the pr? or i can fix it directly, your choice. it also needs to inherit xdm as the icon cache is not updated correctly. that's the issue of the original ebuild and not of your patch, but this should be fixed aswell.

I can do this, no problem. Will do so tonight.

> also, looking at the upstream site, 1.1.29 is already out.

I'll have a look at doing a revbump in a follow-up PR

**Comment by simonvanderveldt** [comment]
@fordfrog Should be fixed now :)

**Comment by fordfrog** [comment]
@simonvanderveldt cool, thanks! :-)

**Pull request closed without merging**
