### PR TITLE
cmake-utils: Better support for non-Gentoo CMAKE_BUILD_TYPE

### PR DESCRIPTION
**Pull request by mgorny**
https://bugs.gentoo.org/599628

This is the first step towards making things less dependent on `CMAKE_BUILD_TYPE=="Gentoo"`.

1. Custom code paths in cmake can now be alternatively triggered by `CMAKE_GENTOO_BUILD` variable that is set independently of the `CMAKE_BUILD_TYPE`.
2. Additional cleanup for default `CMAKE_*_FLAGS_${CMAKE_BUILD_TYPE}` has been added to the eclass for EAPI 6 and newer (old EAPIs excluded because I don't want to bother with old bash versions).

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/kde

**Comment by johu** [comment]
+1 
@kensington ?

**Comment by kensington** [comment]
If it works, ship it!

**Comment by mgorny** [comment]
Shipped.

**Pull request closed without merging**
