### PR TITLE
dev-util/clippy: treeclean

### PR DESCRIPTION
**Pull request by jkroonza**
Only dependency was net-misc/frr.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
I guess we should still start off by last-riting it for removal in profiles/package.mask, though.

**Comment by jkroonza** [comment]
> I guess we should still start off by last-riting it for removal in profiles/package.mask, though.

Even though there never could/would/should have been a dep other frr?

Sure can go that route.

**Comment by eli-schwartz** [comment]
The simplest reason why it might matter is, someone could have a forked frr in a personal overlay that depends on this. The last-rite would be their signal to figure out a frr update in their own overlay, or fork clippy as well.

**Comment by jkroonza** [comment]
@Flowdalic already actioned same via 9ca10d92ba04bb4295c6f72aaaa14612505dc4db

**Pull request closed without merging**
