### PR TITLE
media-libs/libplacebo: bump to v2.43.1

### PR DESCRIPTION
**Pull request by haasn**
This is a straightforward bugfix release.

Signed-off-by: Niklas Haas <gentoo@haasn.xyz>

### CODE REVIEW

**Comment by thesamesam** [comment]
Merged in https://github.com/gentoo/gentoo/commit/dd165a1bb47fd36137dd2a047efccf54afeaec80.

**Comment by haasn** [comment]
Heads up: This commit turned out to be broken. (Disclaimer: I no longer have a gentoo machine I can test on)

The patch from `patches` also needs to be renamed.

**Comment by thesamesam** [comment]
If you're not able to test things, it's okay to step down if you need to as a maintainer. I'm sorry to hear that though.

**Comment by negge** [comment]
I have a working system and confirm renaming `files/libplacebo-2.43.0-vulkan-headers-1.2.140-compatibility.patch` to `files/libplacebo-2.43.1-vulkan-headers-1.2.140-compatibility.patch` fixes the epatch error.

**Comment by juippis** [comment]
A perfect example why `git mv` shouldn't be used on version bumps. Anyhow it's fixed now, but I had to also reset the KEYWORDS for 2.43.1 to ~, and keep the current stable around until 2.43.1 can be stabilized. Just launch the stabilization in 7-14 days if you feel so.

**Comment by lu-zero** [comment]
sorry for rushing it in

**Pull request closed without merging**
