### PR TITLE
sci-electronics/kicad: Limit boost version to max 1.60

### PR DESCRIPTION
**Pull request by zpuskas**
Gentoo bug: #583640

Package-Manager: portage-2.3.0_rc1

### CODE REVIEW

**Comment by mgorny** [comment]
Just a minor suggestion: could you put the `<` before `>=`? It's a good practice for simpler dependency solvers to have the more restrictive variant first.

**Comment by zpuskas** [comment]
Sure. Will do.

**Comment by zpuskas** [comment]
@mgorny : Done :)

**Comment by mgorny** [comment]
```
commit 5b8e557b3eb86e7611af46338a876b4ad1d5a7ae
Author:     Zoltan Puskas <zoltan@sinustrom.info>
AuthorDate: Sat Jun 11 09:03:42 2016
Commit:     Michał Górny <mgorny@gentoo.org>
CommitDate: Sat Jun 11 10:16:54 2016

    sci-electronics/kicad: Limit boost version to max 1.60, #583640
    
    Bug: https://bugs.gentoo.org/583640
    Pull-Request: https://github.com/gentoo/gentoo/pull/1645
    Package-Manager: portage-2.3.0_rc1

**Pull request closed without merging**
