### PR TITLE
dev-perl/Growl-GNTP: version bump, 0.210.0

### PR DESCRIPTION
**Pull request by tomboy-64**
@gentoo/perl
@gentoo/proxy-maint

### CODE REVIEW

**Comment by tomboy-64** [comment]
Not sure what to make of this ...

Installing /tmp/portage/dev-perl/Growl-GNTP-0.210.0/image/usr/share/man/man3/Growl::GNTP.3pm
 * Fixing packlist file /usr/lib64/perl5/vendor_perl/5.22.1/x86_64-linux-thread-multi/auto/Growl/GNTP/.packlist
 * Pruning surplus packlist entry /usr/share/man/man3/Growl::GNTP.3pm

**Comment by tomboy-64** [comment]
@kentfredric could you take a look at this please?

**Comment by kentfredric** [comment]
Those are notices from our "new" packlist cleaner. There was a bug ( https://bugs.gentoo.org/show_bug.cgi?id=579492 ) where:

- Bogus entries from a previous packlist were incorporated into a future one
- Including when the distribution releases a new version that removed some files ( resulting in the packlist continuing to list files that portage had cleaned )
- Also included items that had been injected in the build process buy Module::Build, but had been pruned by our eclass ( on purpose ).

That step simply makes sure that there is nothing in the packlist that isn't in "${D}", making sure the packlist remains valid after installation.

**Comment by kentfredric** [comment]
Also, its worth taking a look at the (very new) `DIST_EXAMPLES=()` var that was added to perl-module.class this week.


This block can be nuked:

```bash
+src_install() {
+	perl-module_src_install
+	if use examples; then
+		docompress -x /usr/share/doc/${PF}/examples
+		dodoc -r examples
+	fi
+}

``` 

And instead, above the inherit line, you can write 

```
DIST_EXAMPLES=("examples/*")
```

And as long as it is *above* the inherit line, you don't even have to declare `examples` in IUSE.

**Comment by kentfredric** [comment]
Oh, and probably also remove the dep on IO::PortState, that was the primary reason for them to release 0.21 :) 

https://metacpan.org/diff/file?target=MATTN%2FGrowl-GNTP-0.21%2F&source=MATTN%2FGrowl-GNTP-0.20%2F#Changes

And I suspect you can drop the CPAN::Meta dep now as well, as that was excised from Build.PL

https://metacpan.org/diff/file?target=MATTN%2FGrowl-GNTP-0.21%2F&source=MATTN%2FGrowl-GNTP-0.20%2F#META.json

**Pull request closed without merging**
