### PR TITLE
net-im/prosody: remove unused patch

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patch(es) from:
net-im/prosody

Please review

Signed-off-by: Michael Mair-Keimberger <m.mairkeimberger@gmail.com>

### CODE REVIEW

**Comment by klausman** [comment]
I still don't know how to actually approve merges like these, but I do, in spirit.

**Comment by a17r** [comment]
> I still don't know how to actually approve merges like these, but I do, in spirit.

what exactly is the problem?

**Comment by klausman** [comment]
> > I still don't know how to actually approve merges like these, but I do, in spirit.
> 
> what exactly is the problem?

As I said: how do I approve the change? or does it somehow go through automagically?

I know how PRs *usually* work, but this wasn't that.

**Comment by a17r** [comment]
Approval is only a formal act. If you are the maintainer, and approve of it, then just pull the PR as a git am patch and push to tree.

**Pull request closed without merging**
