### PR TITLE
media-video/celluloid: bump to version 0.24

### PR DESCRIPTION
**Pull request by Elserjo**
Signed-off-by: Serg <reznov90210@gmail.com>

Newer version of celluloid now requires new dependencies:

1. libadwaita >= 1.0.0 (acts as >=gui-libs/libadwaita-1.0.0 in this ebuild)
2. gtk >= 4.6.1 (acts as >=gui-libs/gtk-4.6.1:4 in this ebuild)

It seems, that GTK3 build is not supported. According this commit https://github.com/celluloid-player/celluloid/commit/8b68f560628a0961d434ee0d39a8397eab4578b6

### CODE REVIEW

**Comment by kuraga** [comment]
@Elserjo , merge 2a17d5c70ddfbb51076f38ec74972f47148dfcc9, please.

**Comment by jospezial** [comment]
See also:
https://bugs.gentoo.org/768939

**Comment by kuraga** [comment]
Any news?

/cc @leio

**Comment by kuraga** [comment]
[0.25 is here](https://github.com/celluloid-player/celluloid/releases/tag/v0.25) (when you are implementing it, take a look at https://github.com/celluloid-player/celluloid/commit/df3ae8b5a35f90e01df22343687d6be362799b26.

**Comment by kuraga** [comment]
~[0.25](https://github.com/celluloid-player/celluloid/releases/tag/v0.25)~ [0.26](https://github.com/celluloid-player/celluloid/releases/tag/v0.26) is here (when you are implementing it, take a look at https://github.com/celluloid-player/celluloid/commit/df3ae8b5a35f90e01df22343687d6be362799b26 / https://github.com/celluloid-player/celluloid/pull/852.

**Comment by kuraga** [comment]
New live ebuild in https://bugs.gentoo.org/768939 by @jospezial .

**Comment by kuraga** [comment]
Obsolete by 7b7eb01b79d3aa47cd1121128ca337abd34a0a37.

**Pull request closed without merging**
