### PR TITLE
app-misc/pwsafe: support libressl

### PR DESCRIPTION
**Pull request by Hawk777**
Related bug: https://bugs.gentoo.org/620784

No changes to the compilation logic, tarball, patches, etc.. Only DEPEND.

Note that I am the proxied maintainer for this package.

### CODE REVIEW

**Comment by mgorny** [comment]
Any reason to keep the previous revision?

**Comment by Hawk777** [comment]
@mgorny, my plan was to STABLEREQ r4 after this PR is merged and then delete everything else all at once. Would you prefer r3 deleted now and r2 after r4 is stable?

**Comment by mgorny** [comment]
Yes, it's easier to review diffs then ;-).

**Comment by Hawk777** [comment]
Better?

**Pull request closed without merging**
