### PR TITLE
add ~arm64 keyword to app-misc/khard/khard-0.12.2 and deps.

### PR DESCRIPTION
**Pull request by NeddySeagoon**
Addresses [Bug 643066] app-misc/khard initial keywording request for arm64

### CODE REVIEW

**Comment by mgorny** [comment]
@leio, you handling this? Or should I verify and commit?

**Comment by leio** [comment]
I'll handle it soon, thanks for triggering a reminder

**Comment by leio** [comment]
```
  dependency.badindev           3
   app-misc/khard/khard-0.12.2.ebuild: RDEPEND: ~arm64(default/linux/arm64/17.0)
[     'dev-python/ruamel-yaml[python_targets_python3_4(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-)]']
   app-misc/khard/khard-0.12.2.ebuild: RDEPEND: ~arm64(default/linux/arm64/17.0/desktop/systemd)
[     'dev-python/ruamel-yaml[python_targets_python3_4(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-)]']
   app-misc/khard/khard-0.12.2.ebuild: RDEPEND: ~arm64(default/linux/arm64/17.0/systemd)
[     'dev-python/ruamel-yaml[python_targets_python3_4(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,-python_single_target_python3_4(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-)]']
```

**Comment by leio** [comment]
Last commit (khard) dropped, rest merged. Please test ruamel-yaml and file new PR (or just give me an OK go-ahead) for the rest

**Pull request closed without merging**
