### PR TITLE
net-analyzer/nagios: bump to 4.4.1 with a mask

### PR DESCRIPTION
**Pull request by hydrapolic**
https://bugs.gentoo.org/662194

### CODE REVIEW

**Comment by hydrapolic** [comment]
@orlitzky

**Comment by orlitzky** [comment]
If we mask the new v4.4.1 and drop v4.4.0, then most ~arch users will be downgraded to v4.3.4 (stable). Honestly... 4.4.1 is just a dud, and I think we should wait this one out until v4.4.2 is released. It's being worked on right now, e.g.

* https://github.com/NagiosEnterprises/nagioscore/commit/7fbb312c592eae7279bdb338b8c7848290cec3f3
* https://github.com/NagiosEnterprises/nagioscore/commit/332fb40ec0c269ea4d943cb88fcd62b84bc2c313

**Comment by orlitzky** [comment]
It feels weird but I suppose it's possible to think too hard about these things. Merged, thanks for your help.

Now somebody with 2FA will have to close this =P

**Comment by hydrapolic** [comment]
Thanks @orlitzky

**Pull request closed without merging**
