### PR TITLE
Gvm update

### PR DESCRIPTION
**Pull request by j-licht**

### CODE REVIEW

**Comment by j-licht** [comment]
I've created some Bugs for this:
[725892](https://bugs.gentoo.org/show_bug.cgi?id=725892) [725894](https://bugs.gentoo.org/show_bug.cgi?id=725894) [725896](https://bugs.gentoo.org/show_bug.cgi?id=725896) [725898](https://bugs.gentoo.org/show_bug.cgi?id=725898) [725900](https://bugs.gentoo.org/show_bug.cgi?id=725900) [725902](https://bugs.gentoo.org/show_bug.cgi?id=725902) [725904](https://bugs.gentoo.org/show_bug.cgi?id=7259004)

**Comment by j-licht** [comment]
It's broken caused by missing cgreen package see PR: https://github.com/gentoo/gentoo/pull/16488

**Comment by juippis** [comment]
Please rebase against fresh ::gentoo copy to run CI again.

**Comment by juippis** [comment]
Good work here, sorry it took a while. Massive PR.
You can close bugs while merging with using `Closes:` tag instead of `Bug:`. Bug is nice if you're uncertain that a commit fixes the bug, and want to wait for feedback or something else.

**Comment by j-licht** [comment]
@juippis Thanks. I've created a patch to fix the test in net-analyser/gvmd in the same branch.
Should I create an extra PR and Bug for this?

**Comment by juippis** [comment]
Please open a new PR with rebased ::gentoo master. You don't have to create a bug for it... but it's possible some automated tinderbox tests will hit this, and then they'll create bugs nevertheless.

**Pull request closed without merging**
