### PR TITLE
dev-ruby/poltergeist: treeclean

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

Both packages were masked in June 2017 with a note to remove it in 30 days...
Guess we waited long enough ;)

Please review.

### CODE REVIEW

**Comment by graaff** [comment]
Please check with @gentoochainsaw because he had interest to keep this around for people doing automated testing (where all the security issues are less of a concern).

**Comment by gentoochainsaw** [comment]
Do not treeclean PhantomJS, I've worked hard to keep it building on modern systems. By all means keep the mask if that makes you happy, but this is needed and used.

**Comment by mm1ke** [comment]
Hi, i've changed the PR to keep PhantomJS and updated the package.mask entry.

**Comment by mm1ke** [comment]
Ping, i've just rebased this PR :)

**Comment by mm1ke** [comment]
@graaff 
Are the changes ok for you?

**Comment by mm1ke** [comment]
ping, another rebase, any chance for a merge? :)

**Pull request closed without merging**
