### PR TITLE
www-apps/gitea: security bump to 1.7.4

### PR DESCRIPTION
**Pull request by hydrapolic**
Thanks

### CODE REVIEW

**Comment by hydrapolic** [comment]
Thanks @monsieurp

**Comment by xdch47** [comment]
@hydrapolic Was there any reason with not to reuse the work that has been done in #10961?
Is it because you don't like the ebuild or you don't like contributions? 

What about putting the putting the config-file to etc like other distro's do?
See https://github.com/nemunaire/gentoo-overlay/issues/1

**Comment by hydrapolic** [comment]
I only did the minimum that was needed for the bump that sticks to upstream as much as possible. We can improve the ebuild of course.

**Comment by xdch47** [comment]
Mmh, well I just don't understand…
Since 1.6.1 there was a lot of work has been done to get it upstream (as you know):
- 1.6.1 https://github.com/gentoo/gentoo/pull/10510
- 1.6.3 https://github.com/gentoo/gentoo/pull/10601
- 1.7.0 https://github.com/gentoo/gentoo/pull/10947
- 1.7.1/2 https://github.com/gentoo/gentoo/pull/10947

Feels kind of frustrating that with out any review's with one day the package went upstream…

**Comment by hydrapolic** [comment]
The mentioned improvements are continued in https://github.com/gentoo/gentoo/pull/11387

**Pull request closed without merging**
