### PR TITLE
gnome-extra/zeitgeist: Include zeitgeist in vanilla gentoo.

### PR DESCRIPTION
**Pull request by herbmillerjr**
Would like to get this into vanilla gentoo as it's useful or porting over Elementary desktop (Pantheon).

Would like to know what modifications I need to make for this to be vanilla gentoo worthy, and would like to become the package's proxy maintainer.

### CODE REVIEW

**Comment by mgorny** [comment]
This package has been historically removed:

```
# Pacho Ramos <pacho@gentoo.org> (28 Dec 2017)
# Requires dead gnome2 python bindings (#629180) and old gstreamer, also all
# zeitgeist stack has important bugs and upstream is gone (#629180#c2):
# zeitgeist-explorer doesn't start (#622084), activity-log-manager fails to
# build (#625140), 
gnome-extra/gnome-activity-journal
gnome-extra/zeitgeist-explorer
gnome-extra/activity-log-manager
gnome-extra/zeitgeist
dev-libs/libzeitgeist
```

Do the conditions for removal no longer hold, i.e. has upstream resumed development?

**Comment by herbmillerjr** [comment]
Eew. Zeitgeist shows upstream released 1.0.1 last month. Libzeitgeist on the other hand indeed looks dead. May be not worth it to pull this in as on second look it appears to be an optional dependency on everything.

**Comment by mgorny** [comment]
Well, I don't strictly mind having it back, provided it'll be maintained properly. However, I would mind readding it just to have all the same bugs re-reported and then it being removed again.

So if you want to add it, please at least look through all the closed bugs and determine which ones apply still and whether you'll be able to fix them.

**Comment by EvaSDK** [comment]
Also note that having zeitgeist alone does not make it much useful so hopefully there is a working frontend to go with it.

**Comment by herbmillerjr** [comment]
Would it still be useful for some applications without a frontend? The specific reason I'm eyeing it up right now is pantheon-files uses it: https://github.com/elementary/files.

**Comment by flappyports** [comment]
no activity

**Pull request closed without merging**
