### PR TITLE
dev-python/pipenv: bump version to 2020.11.15

### PR DESCRIPTION
**Pull request by oz123**
Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: Oz Tiram <oz.tiram@gmail.com>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Your commits seem to be mixed a bit and you're removing some older version in your bump.

Is the `<pytest-5` requirement still true? Can't it be patched?

**Comment by oz123** [comment]
@juippis I should split that commit. You are right.

As for pytest ...  this is taken[ from here](https://github.com/pypa/pipenv/blob/48e1f18930aec29d3d8dc1e346a7726f5d324907/setup.py#L45).
```
    "tests": ["pytest<5.0", "pytest-timeout", "pytest-xdist<2.0", "flaky", "mock"],
```
However, I can check if this also works with pytest 5 or later..

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Please make/find a comment upstream about it, it could just be they forgot to update README or something.

**Comment by oz123** [comment]
Already done here: https://github.com/pypa/pipenv/issues/4559

The development of pipenv was taken over by a new team pretty abruptly. I think there is still a lot of old cruft hiding there.
Is the update OK besides this? Can the PR be merged as is?

**Comment by juippis** [comment]
Yep, sorry for the delay, I usually attempt to push as many finished PRs as possible at once.

**Pull request closed without merging**
