### PR TITLE
gnome-extra/zenity: Version bump to 3.92.0 BETA

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
Looks like the error is

````
[26/161] /usr/bin/help2man --no-info --section=1 --help-option=--help-all --include=../zenity-3.91.0/data/zenity.roff --output=data/zenity.1 /var/tmp/portage/gnome-extra/zenity-3.91.0/work/zenity-3.91.0-build/src/zenity
FAILED: data/zenity.1 
/usr/bin/help2man --no-info --section=1 --help-option=--help-all --include=../zenity-3.91.0/data/zenity.roff --output=data/zenity.1 /var/tmp/portage/gnome-extra/zenity-3.91.0/work/zenity-3.91.0-build/src/zenity
help2man: can't get `--help-all' info from /var/tmp/portage/gnome-extra/zenity-3.91.0/work/zenity-3.91.0-build/src/zenity
Try `--no-discard-stderr' if option outputs to stderr
````

`--help-all` usage was added in https://gitlab.gnome.org/GNOME/zenity/-/commit/011783da148ce9c81d042feecd202f6935f7ef71

So I think the way it works is help2man passes `--help-all` to zenity to get its help output to include in the man page.

Running `/var/tmp/portage/gnome-extra/zenity-3.91.0/work/zenity-3.91.0-build/src/zenity` I get

`(zenity:3730396): Gtk-WARNING **: 12:42:27.550: cannot open display: `

I've filed https://gitlab.gnome.org/GNOME/zenity/-/issues/53

**Comment by mattst88** [comment]
3.92.0 is out, but it doesn't fix the requirement that on X for the build.

It does switch to webkit-gtk:6, which is nice.

**Comment by larathbone** [comment]
Correct, unfortunately it didn't make 3.92.0 (essentially 4.0, alpha 3), but there were so many fixes from 3.91.0 that I wanted to get a new release pushed ASAP. FWIW, I consider this issue a blocker for beta, so hopefully it will be addressed soon. As I indicated on your upstream bug report, it may take some fairly major refactoring in the GApplication-based code. If it can't be fixed in a timely fashion, I'll just drop help2man manpage generation, or at least include a meson option to disable it so that a display manager is not required to be running in order to build the manpage.

**Comment by mattst88** [comment]
Hey, thanks a bunch!

**Comment by flint2** [comment]
Bumped to 3.92.0 and changed PR name

**Comment by flint2** [comment]
Applied upstream commit https://gitlab.gnome.org/GNOME/zenity/-/commit/db1ad8ee7c3db36a7cca6e998e86719293d37838 as patch

**Pull request closed without merging**
