### PR TITLE
Update dotnet-sdk-bin and runtimes for .NET 8.0.100

### PR DESCRIPTION
**Pull request by Blackburn29**
Tested on amd64 only, but have merged and verified it on my own machine

### CODE REVIEW

**Comment by xgqt** [comment]
Thanks for taking time to make this PR! :pray: finally some making PRs against new .NET ecosystem in Gentoo :heart:

**Comment by xgqt** [comment]
We will also need a virtual/dotnet-sdk bump to 8.0 :)

**Comment by Blackburn29** [comment]
@xgqt Added

**Comment by xgqt** [comment]
> @xgqt Added

with stable amd64, this has to be unstable on all arches

If you have any questions about checking the right versions or dotnet-runtime-nugets feel free to ask.

**Comment by Blackburn29** [comment]
> > @xgqt Added
> 
> with stable amd64, this has to be unstable on all arches
> 
> If you have any questions about checking the right versions or dotnet-runtime-nugets feel free to ask.

With .NET8 being a stable release, do we want to mark this as stable on amd64? Or would you prefer it be unstable?

**Comment by xgqt** [comment]
> With .NET8 being a stable release, do we want to mark this as stable on amd64? Or would you prefer it be unstable?

Every new package version has to be unstable (`~arch`), there are some exceptions, but .NET is not one of them.

**Comment by Blackburn29** [comment]
> > With .NET8 being a stable release, do we want to mark this as stable on amd64? Or would you prefer it be unstable?
> 
> Every new package version has to be unstable (`~arch`), there are some exceptions, but .NET is not one of them.
> 
> The version you added will be stabilized later, after soem time passes, such is the Gentoo policy.

Noted. 

I have updated the PR. Thank you for all your help thus far!

**Comment by xgqt** [comment]
Please rebase your commits such that that one marking pkgs as unstable is not separate.

**Comment by xgqt** [comment]
I bumped .NET SDK from-source build to 8.0.100 so I will also merge your PR partially (1st commit) with nugets fixed. Thanks a lot.

**Comment by Blackburn29** [comment]
> I bumped .NET SDK from-source build to 8.0.100 so I will also merge your PR partially (1st commit) with nugets fixed. Thanks a lot.

I will rebase the sdk-bin commits shortly when I get back to my desk

**Comment by xgqt** [comment]
> > I bumped .NET SDK from-source build to 8.0.100 so I will also merge your PR partially (1st commit) with nugets fixed. Thanks a lot.
> 
> I will rebase the sdk-bin commits shortly when I get back to my desk

There is no need to do that since I needed the changes I was writing about for from-source build and had to write those. As I said the 1st commit will be merged with updated nugets version. (In case you worry about crediting, it will remain with your sign-off-by)

**Comment by Blackburn29** [comment]
> > > I bumped .NET SDK from-source build to 8.0.100 so I will also merge your PR partially (1st commit) with nugets fixed. Thanks a lot.
> > 
> > 
> > I will rebase the sdk-bin commits shortly when I get back to my desk
> 
> There is no need to do that since I needed the changes I was writing about for from-source build and had to write those. As I said the 1st commit will be merged with updated nugets version. (In case you worry about crediting, it will remain with your sign-off-by)

No problem at all. Just happy to contribute!

**Pull request closed without merging**
