### PR TITLE
Fixed efl configure options

### PR DESCRIPTION
**Pull request by StinGer-ShoGuN**
When setting the `drm` use flag on efl 1.18.4, configure stage fails because the `--enable-drm` option now requires the `--enable-elput` new option.

This pull request adds this new option and sets up a new flag, `elput`, required by the use flag `drm`.

In addition, it fixes dependencies, adding `app-text/poppler[cxx]` as a requirement, makes the `dev-libs/libinput` requirement depending on the `elput` flag, and lower the minimum version to 0.6 as stated in the efl README file.

I'll provide a `diff` of `efl-1.18.4.ebuild` and `efl-1.18.4-r1.ebuild` to see the "real" differences, as well as a build log made from a stage3 archive.

### CODE REVIEW

**Comment by StinGer-ShoGuN** [comment]
Build log: https://bpaste.net/show/4ec137a52925
diff with `efl-1.18.4.ebuild`: https://bpaste.net/show/345c021e84df

**Comment by bjacquin** [comment]
PR https://github.com/gentoo/gentoo/pull/5832 took a different approach by enforcing elput if drm is selected. Can elput has a value as a separate USE flag ?

**Comment by StinGer-ShoGuN** [comment]
From the tests I tried at the time, you could have `--enable-elput` without `--enable-drm`. So I figured out I would add a use flag because IMHO this is all what Gentoo is about: customisation !

Now, does it make sense to have `--enable-elput` without `--enable-drm`, honestly, I don't remember... Sorry. 😞

**Comment by mgorny** [comment]
Closing in favor of #5832. @bjacquin is going to become the new maintainer, and AFAICS he's aware of your request, so let's let him decide how to proceed eventually.

**Comment by StinGer-ShoGuN** [comment]
Fine with me.
I've spotted another build failure in EFL with some USE flags for mesa (something with `classic`, `egl` or so..., I don't remember).

**Comment by bjacquin** [comment]
Indeed, this request was handled as part of #5832.

**Pull request closed without merging**
