### PR TITLE
sci-libs/amd: fix bashism in doc building

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>

sci-libs/camd: fix bashism in doc building

Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>

sci-libs/klu: fix bashism in doc building, remove .la file.

Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>
bug: https://bugs.gentoo.org/show_bug.cgi?id=760408

### CODE REVIEW

**Comment by orlitzky** [comment]
The fix looks good to me, but can you split the single commit into separate ones for each package? Otherwise QA tools complain.

**Comment by kiwifb** [comment]
Argh. I squashed, I thought that was more appropriate that way. I may have to redo the branch.

**Comment by kiwifb** [comment]
Is it OK if I do a forced push or would you favor a different PR altogether?

**Comment by orlitzky** [comment]
force push won't hurt anything

**Comment by kiwifb** [comment]
And pushed. I signed my commits, it used to give me a tick. Is there something with my key that repoman didn't tell me?

**Comment by orlitzky** [comment]
One more thing, sorry :(

Since the existing ebuilds are all stable, the changes should be made in -r1 ebuilds.

**Comment by kiwifb** [comment]
I should have known that.

**Comment by kiwifb** [comment]
OK - third time is a charm :)

**Pull request closed without merging**
