### PR TITLE
sys-devel/clang: Set the correct LLVM_CMAKE_PATH on Gentoo Prefix 

### PR DESCRIPTION
**Pull request by indocomsoft**
Trying to fix https://bugs.gentoo.org/696844, a problem on Gentoo Prefix

### CODE REVIEW

**Comment by mgorny** [comment]
Doesn't that imply printing that verbose message that llvm-config is deprecated and will be removed soon? If we really need to specify the path explicitly, I'd prefer using `LLVM_CMAKE_PATH`.

**Comment by indocomsoft** [comment]
Alright, I changed my patch to use `LLVM_CMAKE_PATH` instead

**Comment by mgorny** [comment]
Please avoid calling llvm-config at all, the path should be predictable.

**Comment by indocomsoft** [comment]
Done

**Comment by indocomsoft** [comment]
I have resolved the conflict with the removal of the RC's for clang-9.0.1

**Comment by mgorny** [comment]
Thank you. I'm sorry that I haven't merged it sooner. I'll do a final test right now and merge it once I've confirmed it working.

**Pull request closed without merging**
