### PR TITLE
x11-wm/icewm updates

### PR DESCRIPTION
**Pull request by jubalh**
* Add new 3.3.1 version
* Update deprecated virtual/jpeg with media-libs/libjpeg-turbo
* Drop old version 2.8.0

### CODE REVIEW

**Review by a17r — CHANGES_REQUESTED** [review]
Changing RDEPENDs requires revbump to ebuilds. My suggestion would be to only switch to libjpeg-turbo in the new version bump, then flush the deprecated virtual dep off the system naturally by stabilisation and cleanup old.

Do we need a slot operator on libjpeg-turbo there?

**Comment by jubalh** [comment]
> Changing RDEPENDs requires revbump to ebuilds

Even in such a case where it basically resolves to the same provider libjpeg-turbo?

> My suggestion would be to only switch to libjpeg-turbo in the new version bump, then flush the deprecated virtual dep off the system naturally by stabilisation and cleanup old.

Makes sense. I'll update the PR.

> Do we need a slot operator on libjpeg-turbo there?

Not that I'm aware of.

**Comment by thesamesam** [comment]
> Even in such a case where it basically resolves to the same provider libjpeg-turbo?

Yes, or you won't be able to ever depclean virtual/jpeg.

**Comment by jubalh** [comment]
Updated the PR. Is it better now?

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
