### PR TITLE
dev-java/htmlcleaner: bump to 2.24 (and remove old)

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
i got test failures:
```
There were 4 failures:
1) preserveUnicodeTest(org.htmlcleaner.DomSerializerTest)
org.apache.xml.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at org.apache.xml.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:323)
	at org.apache.xalan.templates.OutputProperties.<init>(OutputProperties.java:84)
	at org.apache.xalan.transformer.TransformerIdentityImpl.<init>(TransformerIdentityImpl.java:88)
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at org.htmlcleaner.AbstractHtmlCleanerTest.documentToString(AbstractHtmlCleanerTest.java:184)
	at org.htmlcleaner.DomSerializerTest.preserveUnicodeTest(DomSerializerTest.java:147)
2) attributeNames(org.htmlcleaner.HtmlCleanerTest)
org.apache.xml.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at org.apache.xml.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:323)
	at org.apache.xalan.templates.OutputProperties.<init>(OutputProperties.java:84)
	at org.apache.xalan.transformer.TransformerIdentityImpl.<init>(TransformerIdentityImpl.java:88)
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at org.htmlcleaner.AbstractHtmlCleanerTest.assertCleanedDom(AbstractHtmlCleanerTest.java:101)
	at org.htmlcleaner.HtmlCleanerTest.attributeNames(HtmlCleanerTest.java:364)
3) elementNames(org.htmlcleaner.HtmlCleanerTest)
org.apache.xml.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at org.apache.xml.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:323)
	at org.apache.xalan.templates.OutputProperties.<init>(OutputProperties.java:84)
	at org.apache.xalan.transformer.TransformerIdentityImpl.<init>(TransformerIdentityImpl.java:88)
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at org.htmlcleaner.AbstractHtmlCleanerTest.assertCleanedDom(AbstractHtmlCleanerTest.java:101)
	at org.htmlcleaner.HtmlCleanerTest.elementNames(HtmlCleanerTest.java:344)
4) preserveUnicodeTest(org.htmlcleaner.TraversalDomSerializerTest)
org.apache.xml.serializer.utils.WrappedRuntimeException: Could not load the propery file 'output_xml.properties' for output method 'xml' (check CLASSPATH)
	at org.apache.xml.serializer.OutputPropertiesFactory.getDefaultMethodProperties(OutputPropertiesFactory.java:323)
	at org.apache.xalan.templates.OutputProperties.<init>(OutputProperties.java:84)
	at org.apache.xalan.transformer.TransformerIdentityImpl.<init>(TransformerIdentityImpl.java:88)
	at org.apache.xalan.processor.TransformerFactoryImpl.newTransformer(TransformerFactoryImpl.java:818)
	at org.htmlcleaner.AbstractHtmlCleanerTest.documentToString(AbstractHtmlCleanerTest.java:184)
	at org.htmlcleaner.TraversalDomSerializerTest.preserveUnicodeTest(TraversalDomSerializerTest.java:158)
```

**Comment by vaukai** [comment]
> i got test failures:

Here it looks like:
```
Time: 2.041
There were 2 failures:
1) preserveUnicodeTest(org.htmlcleaner.DomSerializerTest)
org.junit.ComparisonFailure: expected:<....0" encoding="UTF-8"[ standalone="no"?>
]<html>
    <head/>
 ...> but was:<....0" encoding="UTF-8"[?>]<html>
    <head/>
 ...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.htmlcleaner.DomSerializerTest.preserveUnicodeTest(DomSerializerTest.java:147)
2) preserveUnicodeTest(org.htmlcleaner.TraversalDomSerializerTest)
org.junit.ComparisonFailure: expected:<....0" encoding="UTF-8"[ standalone="no"?>
]<html>
    <head/>
 ...> but was:<....0" encoding="UTF-8"[?>]<html>
    <head/>
 ...>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.htmlcleaner.TraversalDomSerializerTest.preserveUnicodeTest(TraversalDomSerializerTest.java:158)

FAILURES!!!
Tests run: 310,  Failures: 2

```

**Comment by vaukai** [comment]
2 test ailures: [build.log.gz](https://github.com/gentoo/gentoo/files/6386326/build.log.gz)

**Comment by vaukai** [comment]
Patching makes it even worse:  [build.log.gz](https://github.com/gentoo/gentoo/files/6404628/build.log.gz)

**Comment by vaukai** [comment]
If I changed the `DomSerializerTest.java` to
```
        @Test
        public void preserveUnicodeTest() throws Exception
        {
            final String nonAsciiWord = "hemförsäkring";
            final String html = "<html>"
                    + "<body>"
                    + "<p>"
                    + nonAsciiWord
                    + "</p>"
                    + "</body>"
                    + "</html>";

            final String expectedOutput =
                    "<?xml version=\"1.0\" encoding=\"UTF-8\"?><html>\n"
                    "    <head/>\n" +
                    "    <body>\n" +
                    "        <p>" + nonAsciiWord + "</p>\n" +
                    "    </body>\n" +
                    "</html>\n"
                    + "";

                final TagNode tagNode = new HtmlCleaner().clean(html);
                final CleanerProperties cleanerProperties = new CleanerProperties();
                final Document doc = new DomSerializer(cleanerProperties, false).createDOM(tagNode);
                assertEquals(expectedOutput, documentToString(doc));
```
the test run would tell me
```
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
src/test/java/org/htmlcleaner/DomSerializerTest.java:138: error: not a statement
                    "        <p>" + nonAsciiWord + "</p>\n" + 
                                                   ^
1 error
1 warning
```

**Pull request closed without merging**
