### PR TITLE
media-tv/kodi: Allowing building with FEATURES="network-sandbox"

### PR DESCRIPTION
**Pull request by candrews**
https://bugs.gentoo.org/show_bug.cgi?id=598150

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@candrews any reason to bundle all this stuff and not just use the packages from the tree? I'm super uncomfortable with bundling all this.

**Comment by candrews** [comment]
I hear you, I really don't like bundling either.

I asked this question on the Kodi forums at http://forum.kodi.tv/showthread.php?tid=294976

I don't really know enough about the appropriate build tools to make a patch myself in any reasonable amount of time. But if you do, that would be pretty awesome :)

At least with this PR, the two big problems are resolved:
* The build works offline
* The build is deterministic

So in my mind, that's a pretty good improvement... and we can continue to work on the bundling issue (which I expect to not be a quick thing).

**Comment by SoapGentoo** [comment]
@mgorny QA-input?

**Comment by mgorny** [comment]
We don't like it but it's better than the current auto-downloading thing. If you can't solve it properly anytime soon, feel free to commit it. However, open a bundled-libs bug to track this.

**Comment by wsnipex** [comment]
fyi, I'd be pretty easy to build with system libs, but the resulting kodi wouldn't be able to play DVDs.
The reason is that we carry kodi specific patches in libdvd, so we don't do it for the fun of it.

**Comment by mgorny** [comment]
@wsnipex, thanks for the information. Is there a decent note somewhere explaining what was patched, why and what efforts were done to upstream the patches? I think it's very important to have such notes available publicly whenever a project is relying on a patched version of third-party library.

**Comment by wsnipex** [comment]
I'm afraid there is no (public) documentation about it, but the commits in the respective repos themselves.

**Comment by candrews** [comment]
So what do we say?

I'm not going to hold my breath on upstream allowing the use of these system libraries so I think this approach is probably the best solution.

**Comment by mgorny** [comment]
@wsnipex, I suppose this means that the patches were not submitted upstream. Is there any chance to get them upstream, and avoid forking libraries like that?

@candrews, I won't object but wait for the approval from maintainer(s).

**Comment by candrews** [comment]
I've requested that upstream merge Kodi's changes to the 3 libraries (upstream's system doesn't allow forking and pull requests, so I couldn't do that):
https://code.videolan.org/videolan/libdvdread/issues/1
https://code.videolan.org/videolan/libdvdcss/issues/2
https://code.videolan.org/videolan/libdvdnav/issues/1

The current Gentoo maintainer for these libraries is media-video@gentoo.org - perhaps that group could also help out?

Finally, @vapier seems to be AWOL (see https://bugs.gentoo.org/show_bug.cgi?id=597034 ), so last time, @SoapGentoo merged the Kodi PR. Perhaps that could happen again?

**Pull request closed without merging**
