### PR TITLE
app-backup/kfoldersync: version bump

### PR DESCRIPTION
**Pull request by Vindex17**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/kde

**Comment by kensington** [comment]
Which arm device did you test on?

**Comment by Vindex17** [comment]
https://build.opensuse.org/package/binaries/home:Vindex17:myapps/kfoldersync?repository=openSUSE_Factory_ARM

**Comment by kensington** [comment]
Thanks for the info and the bump. Picked as a89992f3cabcbec606f4bf77224014eddf78e750.

**Pull request closed without merging**
