### PR TITLE
dev-java/commons-lang: 3.1 slot removal | app-forensics/sleuthkit: switch to dev-java/commons-lang:3.6

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
filed [stablereq for commons-lang](https://bugs.gentoo.org/796155) to resolve the issue

**Comment by vaukai** [comment]
> filed [stablereq for commons-lang](https://bugs.gentoo.org/796155) to resolve the issue (i closed that one...)
> 
> hm, i don't get what's the issue about...

Guess it's `about sleuthkit-4.9.0` depending on `commons-lang:3.1`

**Comment by fordfrog** [comment]
yes, right. we need to update both versions of `sleuthkit` to be able to get rid of the slot `:3.1`

**Comment by vaukai** [comment]
But we cannot remove stable version (without dropping stable keywords before)

**Comment by gktrk** [comment]
@fordfrog I'm not doing a good job paying attention to this. Feel free to commit for me if you think it's correct.

**Comment by vaukai** [comment]
> @fordfrog I'm not doing a good job paying attention to this. Feel free to commit for me if you think it's correct.

@gktrk @fordfrog 
wrt unresolved bugs [689752](https://bugs.gentoo.org/689752), [784026](https://bugs.gentoo.org/784026) and [774441](https://bugs.gentoo.org/774441): are you ok with completely dropping the `java?` option in both `4.9.0` and `4.10.1`?
I have no clue what needs to be runtime-tested if we tried to fix.

**Comment by fordfrog** [comment]
@vaukai thanks!

@gktrk please verify i did not break anything. also, you should be able to unbundle to `dev-java/sparsebitset` and `dev-java/gson`. @vaukai already prepared bump for `dev-java/commons-validator` so once we resolve the issues, you should be able to unbundle to that too.

**Comment by gktrk** [comment]
> @vaukai thanks!
> 
> @gktrk please verify i did not break anything. also, you should be able to unbundle to `dev-java/sparsebitset` and `dev-java/gson`. @vaukai already prepared bump for `dev-java/commons-validator` so once we resolve the issues, you should be able to unbundle to that too.

I unbundled sparsebitset. For gson, sleuthkit uses 2.8.5 but we only have up to 2.7. I'm not sure if they're API compatible.

**Comment by fordfrog** [comment]
@gktrk it should be sufficient to unbundle `gson` and test whether `sleuthkit` compiles against it. if so, it should be fine. i just tried to bump  `gson` to 2.8.7 but there is an issue (`module-info.java`) that needs `java-pkg-simple.eclass` patched and that patch is not yet tree ready.

**Pull request closed without merging**
