### PR TITLE
dev-util/codeblocks: unbundle tinyxml, astyle

### PR DESCRIPTION
**Pull request by band-a-prend**
Since version 17.12 package dev-util/codeblocks could has auto-detection of system installed 
dev-libs/tinyxml and dev-util/astyle libraries and could use them instead of bundled during build process.
Library dev-util/astyle has changed interface in version 3.1 comparison with 3.0.x, so this update add conditional patching of Codeblocks Astyle plugin to provide the compatibility with new version of astyle.

This dev-util/codeblocks ebuild update offers:

1. update application description to correspond that on codeblocks site;

2. remove --with-wx-config="${WX_CONFIG}" from econf in src_configure() section;

3. unbundle the dev-libs/tinyxml library in favor of system installed 
by adding it as build dependency (>=dev-libs/tinyxml-2.6.2-r3);

4. unbundle the dev-util/astyle library in favor of system installed
by adding it as build dependency ( >=dev-util/astyle-3.0.1-r1:0= ):

* patching (update) the Codeblocks Astyle plugin to be compatible with dev-util/astyle-3.1:
"codeblocks-17.12_update_astyle_plugin_to_v3.1.patch" that is taken from upstream:
https://sourceforge.net/p/codeblocks/code/11266/
(using conditional patching depends on presence of "/usr/lib/libastyle.so.3.1.0" file in system);;
* use sub-sloting of dev-util/astyle to force rebuild Codeblocks on system update
if sub-slot of dev-util/astyle is changed;
* remove KEYWORD "arm" to avoid repoman QA warning about "dependency.bad" and
"dependency.badindev" due to dev-util/astyle dependency doesn't have this KEYWORD.

5. Replace contrib plugin dependency from dev-libs/libgamin to app-admin/gamin
as in some cases **it cause Codeblocks craches of FileManager plugin** due to errors
'Failed to connect to socket /tmp/fam-elmar-' and 'failed to find gam_server' [1].

6. Remove '-fno-delete-null-pointer-checks' compiler flag.
This flag was added to allow to run Codeblocks after compiling codeblocks-16.01
with gcc-6.1 [2] and this issue was fixed in upstream on 2016-07-16 in ticket 10875 [3].
On the 2017-03-24 in upstream ticket 11033 [4] this flag was removed as no needed anymore:
'linux: Partially Revert rev 10875 because we no longer do null pointer checks'.

7. Add updated codeblocks-9999.ebuild that is synced with codeblocks-17.12-r1.ebuild
(has updated dependencies) and allow to build Codeblocks from svn trunk. 
The USE-flag 'fortran' removed in this ebuild-file as FortranProject plugin sources downloads from external svn repo and could requires from time to time changes of the autotools script patch to build successfully.

Refs:
[1] http://forums.codeblocks.org/index.php/topic,22641.0.html
[2] http://forums.codeblocks.org/index.php?topic=21283.0
[3] https://sourceforge.net/p/codeblocks/code/10875/
[4] https://sourceforge.net/p/codeblocks/code/11033/

@leio 
This pull request depends on https://github.com/gentoo/gentoo/pull/8585 (it already merged)

Bug: https://bugs.gentoo.org/383037
Closes: https://bugs.gentoo.org/383037

Bug: https://bugs.gentoo.org/656758
Closes: https://bugs.gentoo.org/656758

### CODE REVIEW

**Comment by band-a-prend** [comment]
I re-check the Codeblocks upstream and found that Astyle plugin was updated to 3.1 version on 15 January 2018 [1]. So I need to replace patch for astyle-3.1 compatibility taken from upstream.

Also I need to replace -9999.ebuild to sync it with updated version of 17-r1.ebuild and make it compatible only with astyle-3.1. The current live-ebuild is broken if alredy astyle-3.0.x installed in system.

[1] https://sourceforge.net/p/codeblocks/code/11266/

**Comment by band-a-prend** [comment]
There is else another issue: http://forums.codeblocks.org/index.php/topic,22641.0/nowap.html

I want to try install entire gamin as dependency instead only libgamin and update the ebuilds here.

**Comment by band-a-prend** [comment]
I assume all changes that I planned for this revision update is made. The full changelog is in initial pull request post.

**Comment by band-a-prend** [comment]
@toralf 
Could you please confirm that updated codeblocks-17.12-r1.ebuild ( e.g. from 00d928e ) is resolved the issue you reported?

**Comment by leio** [comment]
Initial review from phone while on train. 
Can the conditional patching be avoided for the astyle patch, so that the patched version would work with both?
If not, don't check based on a file presence. I'd need to think of a better way, but one option might be to check via the `has` ebuild function (iirc). 

It's rather unexpected that tinyxml and astyle unbundling didn't need any changes to configure options nor patching (regarding bundling, not compact). Was it automatically linking against system ones without dependency before, if the packages happened to be installed? Can the build system be convinced to never fallback to the bundled versions?

**Comment by band-a-prend** [comment]
@leio 

Codeblocks-17.12 has implemented unbundle patches:
1. https://sourceforge.net/p/codeblocks/code/10874/ (for tinyxml)
2. https://sourceforge.net/p/codeblocks/code/10873/ (for astyle)

In first case it checks the presence of tinyxml.pc file by means of pkgconfig (see appropriate closed PR https://github.com/gentoo/gentoo/pull/8361 for dev-libs/tinyxml). 

In second there is a checking of system astyle package installation and linking during compilation with "libastyle.so" via "-lastyle" compiler flag (see also closed PR https://github.com/gentoo/gentoo/pull/8585).

So there is no need additional changes in configure options after closing two PR mentioned above.
Yes it now automatically linked against system installed libraries for codebllocks binary itself
```
$ ldd /usr/bin/codeblocks  | grep tinyxml
        libtinyxml.so.2 => /usr/lib64/libtinyxml.so.2 (0x00007f9e9263b000)
```
and for Astyle plugin
```
$ ldd /usr/lib64/codeblocks/plugins/libAstyle.so | grep astyle
        libastyle.so.3 => /usr/lib64/libastyle.so.3 (0x00007f1ce8663000)
```

As for "astyle"  patching I think it couldn't be avoided for now.
The main reasons is that dev-util/astyle-3.1 has changed interface. I wrote previously a simple small patch that allows to compile codeblocks against atyle-3.1 instead of -3.0.1 (patch is available in my [testing overlay](https://github.com/band-a-prend/gentoo-overlay/blob/6af161bb6568f7d4d176647ff4d0347d62ad467c/dev-util/codeblocks/files/codeblocks-17.12_astyle-3.1_compat.diff)). But after that I replaced it with new from upstream that appeared just after codeblocks-17.12 release and updated astyle plugin to new version and made it compatible with astyle-3.1.

I assume that some users could still require astyle-3.0 for their purpose instead of -3.1 (that has changed interface) and Codeblocks itself was tested by it's developers against asyle-3.0.1. So "hard" dependency of codeblocks against only new astyle-3.1 could potentially result in bug without availability of providing the temporary way to quick resolve this. On the other hand the users that has installed dev-embedded/arduino package requires =dev-util/astyle-3.1 to be installed so they could not then use simultaneously arduino with codeblocks if last has "hard" dependency of astyle-3.0.1 (and I know at least one man that encounters this problem). And without this patch this users aren't allowed to install codeblocks if they have astyle-3.1 installed in system (see the [bug](https://bugs.gentoo.org/656758)).

> If not, don't check based on a file presence. I'd need to think of a better way, but one option might be to check via the has ebuild function (iirc).

Unfortunately I currently can't find "has" function or something similar after quick search.

**Comment by band-a-prend** [comment]
I replaced library presence checking with "if has_version '~dev-util/astyle-3.1' ... " before conditional patching. New conditional check section is placed into src_prepare() as required.

**Comment by leio** [comment]
Yes, I meant has_version.
Under non-conditional patching I meant having a patch that makes it work with both versions via some C #ifdef, #if or similar logic. If not, don't use ~ version specifier, but > or >= as appropriate, as surely a 3.1.1 will want the patch and any 3.2 will definitely not work without patch either.

For bundling stuff I meant making sure it errors out if system version isn't used, instead of silently falling back to bundled version. No `--with-astyle=system` or similar is passed as far as I saw, so if the system astyle is somehow broken for the user despite the dep, it seems like it would silently fallback to using bundled version. That's not ideal, though acceptable.

**Comment by band-a-prend** [comment]
> Under non-conditional patching I meant having a patch that makes it work with both versions via some C #ifdef, #if or similar logic. 

I'm afraid my programming skills are too cursory to make such corrections carefully with selecting of variables names and activation of additional functions with it's calls. And such conditional patch will not make sence for upstream as they already updated trunk to astyle-3.1 and next version of Codeblocks will use astyle-3.1 or newer. So I ask to leave conditional patching this time. 

Also as upstream patch update Astyle plugin itself and this patch is too big it apparently should be downloaded as source tarball rather then stored in portage tree. Is it worth then to list 'fortran' patches explicitly within "${WORKDIR}"/patches/ directory and then unpack astyle plugin patch to the same directory?

> If not, don't use ~ version specifier, but > or >= as appropriate, as surely a 3.1.1 will want the patch and any 3.2 will definitely not work without patch either.

Yes, I completely forgot about versions 3.1.x. Versions 3.2.y maybe will also have changes in interface, so it could requires other patch or maybe not. I replaced "~" with ">=" sign.

> For bundling stuff I meant making sure it errors out if system version isn't used, instead of silently falling back to bundled version. No --with-astyle=system or similar is passed as far as I saw, so if the system astyle is somehow broken for the user despite the dep, it seems like it would silently fallback to using bundled version. That's not ideal, though acceptable.

CodeBlocks build scripts uses internal checking of tinyxml and astyle installation and all appropriate changes were made recently in portage tree to operate this codeblocks internal autotools tests in the proper way for available version of tinyxml and versions of astyle libraries. Also if any problems with installation of one of this libraries will appeared it will be easier to repair and test them.

**Pull request closed without merging**
