### PR TITLE
Frr 202410

### PR DESCRIPTION
**Pull request by jkroonza**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by alarig** [comment]
Looks good to me

**Comment by jkroonza** [comment]
The largest impact change is dropping of IUSE=ipv6, based on the fact that it doesn't pull in additional dependencies at all, and as per "insistence" from pkgcheck scan.

**Comment by thesamesam** [comment]
Please always file a bug for security issues affecting your packages and tag them with `Bug:`.

**Comment by jkroonza** [comment]
@thesamesam there are another bunch of security bugs, I'm assuming don't merge them, the security team will handle that?

**Comment by thesamesam** [comment]
If it's the same package w/ multiple CVEs fixed in the same versions, one bug is OK

**Comment by jkroonza** [comment]
There are a number of existing security bugs already for frr, none of which are still relevant, I'll file a new bug for this set only, and then update the PR accordingly.  Thanks for the feedback.

**Pull request closed without merging**
