### PR TITLE
import of net-voip/blink and dependencies

### PR DESCRIPTION
**Pull request by hasufell**
@mgorny @floppym 

Bug 446026, 446198, 446192, 446188, 446194, 446024, 365131

### CODE REVIEW

**Comment by kensington** [comment]
Curious about the placement of KEYWORDS - I didn't encounter that placement style before.

**Comment by mgorny** [comment]
I don't see anything obviously wrong with it. Though I'd say that I'd prefer seeing KEYWORDS in the regular position, and I'm not sure if python team wants to maintain any more packages :-P.

**Comment by hasufell** [comment]
> and I'm not sure if python team wants to maintain any more packages

It's more of a "if you come across this, just bump it" tag

**Comment by floppym** [comment]
I'm fine with it, so long as you don't plan on retiring any time soon. ;-)

**Comment by kensington** [comment]
@mgorny not complaining, just curious.

**Pull request closed without merging**
