### PR TITLE
app-admin/hddtemp: add drives to Gentoo db

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo-Bug: https://bugs.gentoo.org/573380

### CODE REVIEW

**Comment by PPed72** [comment]
And "fix" whitespace apparently. :(

**Comment by monsieurp** [comment]
Hi. Are you sure about the bug number? AFAICT, it looks like a totally different issue.

**Comment by PPed72** [comment]
Crap! It's 573380. What can I do to fix it?

**Comment by PPed72** [comment]
Amended commit message.

**Comment by mgorny** [comment]
I'm afraid you are breaking whitespace actually. I'm going to take the guts of your diff, and commit them separately. Thanks!

**Comment by mgorny** [comment]
And done! Please close the bug now ;-).

**Pull request closed without merging**
