### PR TITLE
media-sound/audacity: add 3.4.2, update 9999, drop 3.2.5

### PR DESCRIPTION
**Pull request by winterheart**
Update dependencies, SRC_URI, minor fixes to ebuild.

Closes: https://bugs.gentoo.org/916782
Closes: https://bugs.gentoo.org/920363

### CODE REVIEW

**Comment by stefantalpalaru** [comment]
"libmad" is no longer used: https://github.com/audacity/audacity/commit/d4b2ac46cf3c6dbd5461e898adb17fdfc230fef8

**Comment by winterheart** [comment]
> "libmad" is no longer used: [audacity/audacity@d4b2ac4](https://github.com/audacity/audacity/commit/d4b2ac46cf3c6dbd5461e898adb17fdfc230fef8)

Fixed.

**Comment by thesamesam** [comment]
See also https://github.com/gentoo/gentoo/pull/35523.

**Comment by thesamesam** [comment]
cc @mehw

**Comment by mehw** [comment]
> cc @mehw

@thesamesam thanks ;)

@winterheart when `audacity-3.3.3` is no longer in the tree, you might think about changing the `mpg123` flag description in `metadata.xml`:
```
diff a/metadata.xml b/metadata.xml
24,25c24
<     <flag name="mpg123">Use <pkg>media-sound/mpg123</pkg> instead of
<       <pkg>media-libs/libmad</pkg> for decoding MPEG decoding</flag>
---
>     <flag name="mpg123">Use <pkg>media-sound/mpg123</pkg> for MPEG decoding</flag>
```

In the meantime, I can't quite get the sense of `for decoding MPEG decoding`:
```
diff a/metadata.xml b/metadata.xml
25c25
<       <pkg>media-libs/libmad</pkg> for decoding MPEG decoding</flag>
---
>       <pkg>media-libs/libmad</pkg> for MPEG decoding</flag>
```

**Pull request closed without merging**
