### PR TITLE
www-apps/radicale: Version bump to 2.1.11

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
@mgorny @Whissi what is holding that back?

**Comment by Whissi** [comment]
Please comment on pr #10574. I'd like to merge both changes together.

**Comment by henning-schild** [comment]
in the discussion around #10574 we found that radicale lacks a systemd service file, i will take care of that, either in this bump or on top of it

**Comment by henning-schild** [comment]
Interesting merge order, i guess the bump should technically get a -r1 after with 6f6b42f, but i guess nobody will run into this.

**Pull request closed without merging**
