### PR TITLE
media/gfx-geeqie: add geeqie-9999.ebuild

### PR DESCRIPTION
**Pull request by grumpytetra**

### CODE REVIEW

**Comment by voyageur** [comment]
@grumpytetra checked and it looks good to go! Can you add the signoff entry so I can pull it in?
"git rebase --signoff" should do the trick to add that Signed-off-by line

**Comment by grumpytetra** [comment]
@juippis, Yeah, that's not going to work for me. I'm not putting my SPI in or on a public commit.

**Comment by voyageur** [comment]
Thanks for the PR, to get around the sign-off requirements, I just pushed my own take (simple rename, git changes and dropping a prepare step not needed with a git checkout), available [now](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=0cdab62709c862dc0582f4662a6ae3739dc8942e).
So marking this one closed :)

**Comment by grumpytetra** [comment]
Alright. Happy new year :)

**Comment by a17r** [comment]
Would have been nice to address [bug 667568](https://bugs.gentoo.org/show_bug.cgi?id=667568) while at it.

**Comment by voyageur** [comment]
Ack sorry this bug was not on my radar, will fix in my next round of updates!

**Pull request closed without merging**
