### PR TITLE
sci-libs/opencascade: fix unused cmake variable

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/710694

The two other commits drop the old 7.3.0 ebuild and change the SLOT variable to be like `<MAJOR_VERSION>/<PV>`.

### CODE REVIEW

**Comment by waebbl** [comment]
@juippis Had you set the `doc` useflag? Need to know to decide how to guard the dep on linguist-tools.

**Comment by juippis** [comment]
Yes, 
`[ebuild  N     ] sci-libs/opencascade-7.4.0:7.4.0::gentoo  USE="doc examples qt5 vtk -debug -ffmpeg -freeimage -gles2 -inspector -java -optimize -tbb"`

**Comment by juippis** [comment]
```
!!! Error: Need exactly 1 arguments!
Call stack:
    * switch_implem (opencascade.eselect:49)
    * do_set (opencascade.eselect:99)
    * check_do (core.bash:24)
    * do_action (core.bash:105)
    * main (eselect:181)
exiting
 * ERROR: sci-libs/opencascade-7.4.0::testworld failed (postinst phase):
 *   failed to switch to updated implementation
 * 
 * Call stack:
 *     ebuild.sh, line 125:  Called pkg_postinst
 *   environment, line 3653:  Called die
 * The specific snippet of code:
 *       eselect ${PN} set ${PV_MAJ} || die "failed to switch to updated implementation";
 * 
 * If you need support, post the output of `emerge --info '=sci-libs/opencascade-7.4.0::testworld'`,
 * the complete build log and the output of `emerge -pqv '=sci-libs/opencascade-7.4.0::testworld'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME=""
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =opencascade-7.4.0
 * The complete build log is located at '/tmp/portage/sci-libs/opencascade-7.4.0/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/sci-libs/opencascade-7.4.0/temp/environment'.
 * Working directory: '/tmp/portage/sci-libs/opencascade-7.4.0/homedir'
 * S: '/tmp/portage/sci-libs/opencascade-7.4.0/work/occt-V7_4_0'
 * FAILED postinst: 1
>>> Regenerating /etc/ld.so.cache...

>>> Failed to execute postinst for sci-libs/opencascade-7.4.0
```

```
 * QA Notice: Pre-stripped files found:
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIVtkDraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKQADraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTObjDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDEDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKDCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXSDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKViewerTest.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTopTest.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKDraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKRWMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKVRML.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDESTEP.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDEIGES.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIGES.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEP.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEP209.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEPAttr.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEPBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXSBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKVCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKStd.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKStdL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXml.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBin.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKLCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKCDF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIVtk.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMeshVS.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKOpenGl.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKV3d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKService.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKFeat.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKOffset.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKFillet.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKHLR.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBool.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKShHealing.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBO.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKPrim.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTopAlgo.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKGeomAlgo.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBRep.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKGeomBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKG3d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKG2d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMath.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKernel.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/Tutorial-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/IESample-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/FuncDemo-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/DRAWEXE-7.4.0
```

Does this bundle *dev-ros/* packages, can it use the system ones?

**Comment by waebbl** [comment]
@juippis No it doesn't bundle ros packages. The ros directory has there from the beginning, when I first updated the package from ::gentoo in my overlay, back with release 6.4.0 or so and is integrated into the build system. I never bothered why it's named like this or why it's there.

I removed the slot changing commit for now. The last failure was due to how eselect-opencascade handles the installed environment file. I need to learn more about eselect modules and update the eselect-opencascade module before I can change the slot in the way I want.

**Pull request closed without merging**
