### PR TITLE
app-text/linuxdoc-tools: drop obsolete autotools-utils eclass

### PR DESCRIPTION
**Pull request by Coacher**
Bug: 623222
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by Coacher** [comment]
I want EAPI6-compatible automatic PATCHES and user patches handling provided by autotools-utils. I would drop autotools-utils and switch to default EAPI6 functions if I could, but more eclasses need to be ported (see comment in ebuild).

**Comment by mgorny** [comment]
epatch "${PATCHES[@]}"
    epatch_user

If you want autotools-utils, then use it correctly. Otherwise, remove it instead of using some horrible hack that turns things into random unreliable shit.

**Comment by Coacher** [comment]
Removing autotools-utils requires a revbump. Thus your suggestion requires revbump + a stabilization round to fix the problem for stable users. I won't do a revbump for cosmetic ebuild-only changes, but I'll consider removing autotools-utils for later.

**Comment by mgorny** [comment]
If nothing changes effectively, it doesn't. Just do it and diff the metadata in gentoo-mirror repo. It includes all important stuff and all phase function mappings.

**Comment by Coacher** [comment]
metadata.diff:
```diff
diff --git a/metadata/md5-cache/app-text/linuxdoc-tools-0.9.72 b/metadata/md5-cache/app-text/linuxdoc-tools-0.9.72
index e8458edf0e3..a9d89c89bca 100644
--- a/metadata/md5-cache/app-text/linuxdoc-tools-0.9.72
+++ b/metadata/md5-cache/app-text/linuxdoc-tools-0.9.72
@@ -1,5 +1,5 @@
-DEFINED_PHASES=compile configure install postinst postrm prepare prerm test unpack
-DEPEND=|| ( app-text/openjade app-text/opensp ) app-text/sgml-common dev-lang/perl:= || ( sys-apps/gawk sys-apps/mawk ) sys-apps/groff sys-devel/flex doc? ( dev-texlive/texlive-fontsrecommended virtual/latex-base ) >=app-portage/elt-patches-20170317 virtual/latex-base >=sys-apps/texinfo-4.2-r5 >=app-text/sgml-common-0.6.3-r2
+DEFINED_PHASES=compile configure install postinst postrm prepare prerm unpack
+DEPEND=|| ( app-text/openjade app-text/opensp ) app-text/sgml-common dev-lang/perl:= || ( sys-apps/gawk sys-apps/mawk ) sys-apps/groff sys-devel/flex doc? ( dev-texlive/texlive-fontsrecommended virtual/latex-base ) >=app-portage/elt-patches-20170317 !<sys-devel/gettext-0.18.1.1-r3 || ( >=sys-devel/automake-1.15:1.15 ) >=sys-devel/autoconf-2.69 >=sys-devel/libtool-2.4 virtual/latex-base >=sys-apps/texinfo-4.2-r5 >=app-text/sgml-common-0.6.3-r2
 DESCRIPTION=A toolset for processing LinuxDoc DTD SGML files
 EAPI=5
 HOMEPAGE=https://gitlab.com/agmartin/linuxdoc-tools
@@ -9,6 +9,6 @@ LICENSE=GPL-3+ MIT SGMLUG
 RDEPEND=|| ( app-text/openjade app-text/opensp ) app-text/sgml-common dev-lang/perl:= || ( sys-apps/gawk sys-apps/mawk ) sys-apps/groff virtual/latex-base
 SLOT=0
 SRC_URI=https://gitlab.com/agmartin/linuxdoc-tools/repository/archive.tar.gz?ref=v0.9.72 -> linuxdoc-tools-0.9.72.tar.gz
-_eclass_exported_funcs=pkg_prerm:sgml-catalog pkg_postrm:- pkg_postinst:- src_unpack:vcs-snapshot src_prepare:- src_configure:- src_compile:- src_test:autotools-utils src_install:-
-_eclasses_=autotools	7027963e8e8cc12c91117bdb9225dc26	autotools-utils	5a4611dfba155b1659528663fad4cd5e	base	df2aa567b3f0595aae0d0923889f7631	epatch	8233751dc5105a6ae8fcd86ce2bb0247	estack	43ddf5aaffa7a8d0482df54d25a66a1f	eutils	9c113d6a64826c40154cad7be15d95ea	latex-package	79acad19b9efeec616d0ad70cd117b03	libtool	e32ea84bf82cf8987965b574672dba93	ltprune	2770eed66a9b8ef944714cd0e968182e	multilib	97f470f374f2e94ccab04a2fb21d811e	perl-functions	01e8c68d5a528bbcda4d3c60205983df	sgml-catalog	013e5c68335c5b4df8f1b72d7d7ad25d	toolchain-funcs	8fec6b1eb195836560e70b66d98fb163	vcs-snapshot	03289f51c769cf409d200d2d628cdd6e
-_md5_=b4df6c26357a746eaabb3ba3d09c3357
+_eclass_exported_funcs=pkg_prerm:sgml-catalog pkg_postrm:- pkg_postinst:- src_unpack:vcs-snapshot src_prepare:- src_configure:- src_compile:- src_install:-
+_eclasses_=autotools	7027963e8e8cc12c91117bdb9225dc26	base	df2aa567b3f0595aae0d0923889f7631	epatch	8233751dc5105a6ae8fcd86ce2bb0247	estack	43ddf5aaffa7a8d0482df54d25a66a1f	eutils	9c113d6a64826c40154cad7be15d95ea	latex-package	79acad19b9efeec616d0ad70cd117b03	libtool	e32ea84bf82cf8987965b574672dba93	ltprune	2770eed66a9b8ef944714cd0e968182e	multilib	97f470f374f2e94ccab04a2fb21d811e	perl-functions	01e8c68d5a528bbcda4d3c60205983df	sgml-catalog	013e5c68335c5b4df8f1b72d7d7ad25d	toolchain-funcs	8fec6b1eb195836560e70b66d98fb163	vcs-snapshot	03289f51c769cf409d200d2d628cdd6e
+_md5_=07aeb45b87ac181fece5ae9c5cd64182
```

**Comment by Coacher** [comment]
Thank you, @mgorny.

**Pull request closed without merging**
