### PR TITLE
app-emulation/virt-manager: Version updated to 3.1.0.

### PR DESCRIPTION
**Pull request by jpds**
Tested on amd64 system.

### CODE REVIEW

**Comment by gyakovlev** [comment]
I'm pretty sure upstream switched from pod2man to python's docutils, or did it happen in 3.1 (which is already out)

**Comment by gyakovlev** [comment]
yup they did

https://github.com/virt-manager/virt-manager/commit/65a39a74950722eecaf165a42bd743ec86b4ef63

so probably can remove perl dependency and add docutils to `DEPEND`

**Comment by jpds** [comment]
@gyakovlev Thank you for the suggestion, I have now added this.

**Comment by gyakovlev** [comment]
thanks, I will test today and merge it it works ok for me.

**Comment by gyakovlev** [comment]
works beautifully, and thanks for catching argcomplete dep!

**Pull request closed without merging**
