### PR TITLE
dev-libs/spdlog: Use GNUInstalldirs, fix cmake files location

### PR DESCRIPTION
**Pull request by a17r**
Fix indentation also.

### CODE REVIEW

**Comment by stkw0** [comment]
Why don't you open an issue on spdlog project for the cmake issue?

**Comment by a17r** [comment]
The file is from their git master.

**Comment by stkw0** [comment]
There is a live ebuild that can be used for that type of things until spdlog release a new version with those fixes.

**Comment by a17r** [comment]
You suggest the live ebuild to fix install to /usr/lib instead of the correct libdir? What if we want to stabilise some spdlog release soon?

**Comment by stkw0** [comment]
I don't like too much the idea of fixing small bugs that are already solved in upstream.
I don't see any strong objection anyway, but it will be better to apply a patch instead of replacing the whole file.

**Comment by a17r** [comment]
The patch will only be double in size due to the incompatible CRLF line terminators (hence the comment).

**Comment by stkw0** [comment]
I don't know if spdlog plans to release a new version soon,  so if there is no other objections and some Gentoo developer approves it, I suppose we could merge this PR.

Thank you for your time and your fast response.

**Comment by a17r** [comment]
> and some Gentoo developer approves it, I suppose we could merge this PR.

thanks, I do.

**Pull request merged**
