### PR TITLE
dev-php/composer: bump to 1.7.2 (+ friends)

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested on (~)amd64. Thanks!

https://bugs.gentoo.org/665426

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hey,
thank you for the work @hydrapolic !

LGTM :+1:

**Comment by GuillaumeSeren** [comment]
@hydrapolic yes you can add me to the xdebug-handler proxy maintainer.

@monsieurp hey, maybe @orlitzky can have a look he helped me to get composer ebuild in gentoo, back 2 years ago.

**Comment by hydrapolic** [comment]
Updated metadata.xml with your e-mail, thanks :)

**Comment by Whissi** [comment]
Thanks, pushed!

**Pull request closed without merging**
