### PR TITLE
app-editors/gedit: Version bump to 43.2

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by scardracs** [comment]
Could you verify if [that bug](https://bugs.gentoo.org/879817) is fixed with new release?

**Comment by flint2** [comment]
> Could you verify if [that bug](https://bugs.gentoo.org/879817) is fixed with new release?



> Could you verify if [that bug](https://bugs.gentoo.org/879817) is fixed with new release?

Cannot reproduce it, and gedit ebuild properly pulls gspell, so we can close it.

**Comment by flint2** [comment]
> Could you verify if [that bug](https://bugs.gentoo.org/879817) is fixed with new release?

Now is solved https://github.com/gentoo/gentoo/commit/333e53f3d42f284c75438cc3eb54efc08fd90c11

**Comment by flint2** [comment]
Closed by: https://github.com/gentoo/gentoo/commit/10da1022bb7116a7e266a0110f40621dad3ee848

**Pull request closed without merging**
