### PR TITLE
sci-physics/geant4_vmc: add 6.6_p1

### PR DESCRIPTION
**Pull request by olifre**
New upstream release (actually, 6.6 was released, too, but I waited for the first patch release).

### CODE REVIEW

**Comment by amadio** [comment]
Hi @olifre, I am seeing some test failures with errors like the one below:
```
Processing load_g4.C...
Loading Geant4 libraries (using geant4-config) ...
36
Loading VMC library ...
Loading g4root library ...
Loading geant4vmc library ...
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TG4RunConfiguration.h
   requested to autoload type TG4RunConfiguration
Error in cling::AutoLoadingVisitor::InsertIntoAutoLoadingState:
   Missing FileEntry for TGeant4.h
   requested to autoload type TGeant4
Processing test_E02.C("g4ConfigOld.C",kTRUE)...
libgeant4vmc dictionary payload:17:10: fatal error: 'TG4RunConfiguration.h' file not found
#include "TG4RunConfiguration.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TG4RunConfiguration with content:

#line 1 "libgeant4vmc dictionary payload"
```
and
```
In file included from input_line_17:1:
/tmp/portage/sci-physics/geant4_vmc-6.6_p1/work/geant4_vmc-6-6-p1/examples/E02/g4ConfigOld.C:23:11: error: allocation of incomplete type 'TG4RunConfiguration'
    = new TG4RunConfiguration("geomVMCtoGeant4", "FTFP_BERT");
          ^~~~~~~~~~~~~~~~~~~
libgeant4vmc dictionary forward declarations' payload:5:74: note: forward declaration of 'TG4RunConfiguration'
class __attribute__((annotate("$clingAutoload$TG4RunConfiguration.h")))  TG4RunConfiguration;
                                                                         ^
libgeant4vmc dictionary payload:17:10: fatal error: 'TG4RunConfiguration.h' file not found
#include "TG4RunConfiguration.h"
         ^~~~~~~~~~~~~~~~~~~~~~~
Error in <TInterpreter::AutoParse>: Error parsing payload code for class TGeant4 with content:

#line 1 "libgeant4vmc dictionary payload"
```
It could well be a problem with my local setup, but I wonder if you've hit similar issues before? It seems some header path is missing, or maybe ROOT changed behavior a bit and cannot find the header. As soon as I understand this I will merge this pull request. Thanks!

**Comment by olifre** [comment]
> To reproduce, you will need to remove the package, then emerge with `FEATURES=test`

Thanks! This is indeed something I did not test in quite a while. I will take a look later this week, the test suite of `geant4_vmc` should take care of setting correct paths, but probably something got broken there. Thanks for pinning it down to the reproducer!

**Comment by amadio** [comment]
Most tests work, it's only the first few that have a broken header path.

**Comment by olifre** [comment]
> Most tests work, it's only the first few that have a broken header path.

Thanks, that helped! Indeed only the "macro-based tests" fail, and the problem is the lack of `ROOT_INCLUDE_PATH` whcih is not set when the tests are executed . I already have a fix prepared and tested and will PR it upstream, and add it as a patch for Gentoo (likely tonight).

**Comment by olifre** [comment]
@amadio Done, I force-pushed right now, the patch fromt he linked PR is now included here. Many thanks again for catching this! :+1:

**Comment by amadio** [comment]
Thank you!

**Pull request closed without merging**
