### PR TITLE
dev-lang/fasm-bin: New package

### PR DESCRIPTION
**Pull request by Fulgurance**
Flat Assembler for the x86 architecture processors

Package-Manager: Portage-3.0.2, Repoman-2.3.23
Signed-off-by: Zohran Londais zohran.londais@gmail.com

### CODE REVIEW

**Comment by Fulgurance** [comment]
Hello, what is the problem ? I don't understand

**Comment by Fulgurance** [comment]
Is it okay ? I don't see my package in Gentoo

**Comment by juippis** [comment]
Hi, 
we're currently not pushing new packages to main repo via proxy-maint, because the workload is too heavy already. You should definitely look into putting these to the Guru repository, which is linked above. Once the situation settles, we are looking into moving popular packages from Guru to ::gentoo.

Also I'd suggest to only push 1 version, having 10 different versions with matching KEYWORDS serves no one.

**Comment by Fulgurance** [comment]
How can i submit it ? Pull request into git repository ? This overlay have github?

**Comment by juippis** [comment]
You can do it yourself after you get an account setup, please see 
https://wiki.gentoo.org/wiki/Project:GURU

here's the mirror:
https://github.com/gentoo/guru

**Pull request closed without merging**
