### PR TITLE
prune old versions

### PR DESCRIPTION
**Pull request by anomaly256**
@python

### CODE REVIEW

**Comment by jlec** [comment]
Ayn particular reason why?

**Comment by anomaly256** [comment]
Because Ian told me to as a learning exercise.  That version of bedup is the last consumer of alembic-0.6.7 and would break with it's removal, mgorny via IRC ok'd its removal along with this.

**Comment by idella** [comment]
I am not certain but it appears this was merged before the completion of the travis C.I. which would have exposed the deficit of py3.3 in the failed test

**Comment by idella** [comment]
commit a9af629c57ef330e236be95ae7811f10e04f570a
Author: Ian Delaney <idella4@gentoo.org>
Date:   Sun Feb 7 21:25:15 2016 +0800

    dev-python/alembic: return of vn -0.7.4 to fix breakage
    
    sourced from taskflow-0.7.1 requiring a stabled verison of alembic
    that supports python3.3
    
    Pull request: https://github.com/gentoo/gentoo/pull/809

**Comment by jlec** [comment]
> commit a9af629c57ef330e236be95ae7811f10e04f570a
Author: Ian Delaney <idella4@gentoo.org>
Date:   Sun Feb 7 21:25:15 2016 +0800

    dev-python/alembic: return of vn -0.7.4 to fix breakage

    sourced from taskflow-0.7.1 requiring a stabled verison of alembic
    that supports python3.3

this has been fixed earlier by 4321a2a2619b8bda039843b0da12fa3c3909e617 So can revert this again.


    Pull request: https://github.com/gentoo/gentoo/pull/809

    Package-Manager: portage-2.2.26
    RepoMan-Options: --force

Why are you using --force here?

**Pull request merged**
