### PR TITLE
app-i18n/man-pages-it: bump version to 4.00

### PR DESCRIPTION
**Pull request by axelgenus**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
@axelgenus there's two more things Id like to get done before committing this. Check in the channel since we have precedent of making decisions there. ditto for sys-power/acpi

**Comment by idella** [comment]
@axelgenus  just declare in a line here you actually request to be the proxy maintainer of the package.
Then add to this pull request, and for the other, a metadata.xml.
That was missing in the other you did which could have been added and is why it was still listed as orphaned package when you asked about it

**Comment by idella** [comment]
DESCRIPTION="Attempts to replicate the functionality of the 'old' apm command on ACPI systems" is 97 chars long
Need be reduced

**Comment by idella** [comment]
merged, virtual/httpd-php unrelated. Minor white space issue fixed manually post commit

**Pull request closed without merging**
