### PR TITLE
media-libs/libavif: new package

### PR DESCRIPTION
**Pull request by jsmolic**
Libavif is a library for encoding and decoding .avif files. It is a
portable C implementation of the AV1 Image File Format.
Initial ebuild was submitted by Daniel Novomesky.

Closes: https://bugs.gentoo.org/711022
Package-Manager: Portage-3.0.3, Repoman-3.0.0
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>

### CODE REVIEW

**Comment by novomesk** [comment]
I would suggest using updated ebuild from Gentoo GURU overlay:
https://github.com/gentoo/guru/tree/master/media-libs/libavif

**Comment by jsmolic** [comment]
> I would suggest using updated ebuild from Gentoo GURU overlay:
> https://github.com/gentoo/guru/tree/master/media-libs/libavif

Thanks, done!

**Comment by novomesk** [comment]
"<flag name='rav1e'>Use <pkg>media-video/rav1e</pkg> for decoding</flag>"
Change "decoding" to "encoding" because rav1e is encoder-only.

**Comment by jsmolic** [comment]
> "Use media-video/rav1e for decoding"
> Change "decoding" to "encoding" because rav1e is encoder-only.

Right, that was a typo, thanks

**Comment by juippis** [comment]
Hi,
sorry I've missed this PR. This package is already in the tree, and I've asked @novomesk to become the primary maintainer for it (since I found it in GURU maintained by him). 

So if @novomesk declines I'll gladly welcome you to take over @jsmolic :)
Let's wait a bit and I'll let you know what happens, but please open a new PR for proposed changes and let's take it from there.
Apparently there is a "hidden" AVIF_BUILD_GDK_PIXBUF flag, and there is demand for -9999 live ebuild that I'm personally reluctant to maintain.

For now I'm looking into keywording libavif for multiple available arches.

**Comment by jsmolic** [comment]
@juippis No worries :)\
I see that @novomesk submitted some changes already and became maintainer, so the package seems to be in good hands ;)\
Cheers

**Pull request closed without merging**
