### PR TITLE
dev-libs/glib: Adding $(get_exeext) to MULTILIB_CHOST_TOOLS

### PR DESCRIPTION
**Pull request by g-braeunlich**
Gentoo-bug: https://bugs.gentoo.org/show_bug.cgi?id=588330

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by g-braeunlich** [comment]
Tested glib-2.48.1-r2 with i686-w64-mingw32 and glib-2.46.2-r3 with
x86_64-pc-linux-gnu

**Comment by monsieurp** [comment]
@mgorny

**Comment by mgorny** [comment]
@g-braeunlich, I don't think this needs a version bump. The package did fail to build before, didn't it?

**Comment by g-braeunlich** [comment]
Yes it failed with i686-w64-mingw32.
Removed the version bumps.

**Comment by mgorny** [comment]
(please disregard the QA check comment, it was for the previous version)

**Pull request closed without merging**
