### PR TITLE
dev-python/pytest-cov: Version bump to 2.2.0

### PR DESCRIPTION
**Pull request by flacjacket**
Bump `dev-python/pytest-cov` to version 2.2.0, also adding `python3_5` target for pytest-cov and a dependency, `dev-python/cov-core`. The other change from the 2.1.0 ebuild is removing the `<dev-python/coverage-4` dependency.

Edit: so this has taken adding several more dependencies to support 3.5. I'm not sure at what point I should consider throwing in the towel. I tried tackling this because pytest-cov can't be installed on Python 3.5, since only coverage-4.0 got the python3_5 target added to it, maybe it is easier to add python3_5 to coverage-3.7.1.

### CODE REVIEW

**Comment by hasufell** [comment]
@mgorny @floppym @djc

**Comment by hasufell** [comment]
procrastination? To me this looks good

**Comment by floppym** [comment]
I'm rather busy at the moment. Hopefully someone else in @gentoo/python can take this.

One thing I notice is that the summary line of the commit messages is incorrect; these are revbumps, not version bumps.

If they were version bumps, I would like to see the version number in the summary line (bump to x.y.z).

Regardless, the summary line should better describe the change, like "add python3.5 support". If that is the only change, the ebuilds do not really need to be rev-bumped; the new python can be added in-place to PYTHON_COMPAT.

**Comment by mgorny** [comment]
Looking at diffs right now. Will take a while to process ;-).

**Comment by mgorny** [comment]
Ok, I see that this is a mix of version and revision bumps. So few major notes at a first glance:

1. *Git commit messages*. The summary line should list major changes. The 'extended' body is optional, and if used should repeat and expand on what summary said. See examples below.
2. That said, most of your commit messages don't really refer to what's done in the ebuild ;-).
3. When you only add python3.5, you don't revbump. Just do it in place ;-).
4. I see you've dropped keywords and I suspect that's due to setuptools. Please don't do that yet, we're working on restoring keywords on setuptools. I'm sorry for the mess caused, and I'm going to get it fixed soon. I'll let you know when setuptools are fixed, so you could rebase and continue ;-).

**Comment by flacjacket** [comment]
@floppym @mgorny Thanks a lot for taking a look at this, I'll try to address everything later today. Most changes are just adding 3.5, I'll do that in place, I'd see some other packages rev bumping and thought that was preferred. I tried playing around with keywords when the QA bot was checking, there were problems with setuptools and also pytest.

**Comment by flacjacket** [comment]
Tho it looks like now everything was un-revbumped, so in place update it is!

**Comment by mgorny** [comment]
Yes, just wanted to tell you that you can start updating this PR ;-).

**Comment by flacjacket** [comment]
Alright, it looks like the one QA issue is in master, since it's tripping on `dev-python/networkx`.

**Comment by mgorny** [comment]
That is correct, https://archives.gentoo.org/gentoo-automated-testing/message/ef702dbbc61d204e05017c1c85ac5726.

**Comment by flacjacket** [comment]
It looks like at least the `~ppc` keyword issues were fixed in master, so I rebased, but looking closer, the `x86` and `amd64` keywords may still come back with problems

**Comment by mgorny** [comment]
Oh u stupid slowbot ;-P.

**Pull request merged**
