### PR TITLE
app-emulation/lxc: Forward-port !GRKERNSEC* checks to 1.1.3+

### PR DESCRIPTION
**Pull request by jirutka**
This was already added to previous versions (see 78ef1b565ae26608f11a81f2b60e4a8e404ef9c3 and a226893bb48e8979b054b1b8cb463402a8d58e27), but the patch was merged after someone bump to 1.1.3. Please merge it before bumping to 1.1.4…

### CODE REVIEW

**Comment by mgorny** [comment]
Errr… could you update this for 1.1.4? ;-D

**Comment by mgorny** [comment]
But seriously, don't worry. I'll copy the patch ;-).

**Comment by mgorny** [comment]
Err, or not. Also, your commit message are way too long. So please update this and create proper git commit messages.

**Comment by jirutka** [comment]
Could yo please propose a better title of the commit that will be short enough?

**Comment by mgorny** [comment]
Hmm… `app-emulation/lxc: Forward-port !GRKERNSEC* checks to 1.1.3+`

**Comment by jirutka** [comment]
Sorry for delay, I kinda forgot to finish it. I’ve updated it to 1.1.4 and changed log message.

**Comment by mgorny** [comment]
Merged, thanks.

**Pull request merged**
