### PR TITLE
app-office/libreoffice: Backport upstream patch to allow compilation with GCC 14

### PR DESCRIPTION
**Pull request by 0xr0bert**
Bug: https://bugs.gentoo.org/928152

### CODE REVIEW

**Review by thesamesam — COMMENTED** [review]
Thanks. No need for new revisions for this as it's a build-time only fix and it's not a correctness issue at all (I mean, it is, but if it builds, it's because the transitive include got picked up, so no runtime behaviour diff. before/after).

Could you fix that and then lgtm?

**Comment by 0xr0bert** [comment]
All done @thesamesam

**Review by a17r — CHANGES_REQUESTED** [review]
@thesamesam, @0xr0bert: As far as I can see this is just duplicating what we already have as `libreoffice-7.6.5.2-gcc14.patch` but got dropped from `7.6.6.3` because it was not applied to `7.6.9999` and `7.6.5.2` ebuild had said `# upstream` only, instead of which branch this was coming from.

So, neither do we have to add the patch to FILESDIR in the first place nor should we touch the stable `7.6.4.1` as a matter of principle. We only need to re-add the patch to `7.6.6.3`, there's probably not going to be another release spun from `7.6.9999`.

**Comment by a17r** [comment]
Also, since `7.6.5.2` already has the patch applied by ebuild, the change here makes it fail in `src_prepare()` if you really test this.

**Comment by 0xr0bert** [comment]
Thanks @a17r

Should it not be applied to the stable 7.6.4.1? If not, could we add specify as a dependency that gcc < 14.

Should it not also be added to 7.6.9999 as well as 7.6.6.3?

**Comment by a17r** [comment]
7.6.4.1 does not need any change as long as GCC-14 does not even have any keywords. No one should try this with arch-only and if they do, they may apply user patches. It is just busywork for us and we do not touch stable ebuilds unless really really necessary. For 7.6.9999 it is likely to be dropped soon, or if upstream decide to backport, it was again just busywork for us.

**Comment by 0xr0bert** [comment]
I have done as you've suggested @a17r and it compiles with GCC 14

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
