### PR TITLE
dev-java/openjdk: update riscv patch for 11.0.18_p10 #898978

### PR DESCRIPTION
**Pull request by YangMame**
old patch fail to build, need to upgrade this patch

### CODE REVIEW

**Comment by YangMame** [comment]
tatt build report:
USE tests started on Fri Mar  3 16:32:53 CST 2023

FEATURES=' test' USE='' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa cups -doc examples -headless-awt jbootstrap -source -system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='alsa cups -doc examples -headless-awt jbootstrap -source -system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa -cups doc examples -headless-awt jbootstrap source -system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='alsa -cups doc examples -headless-awt jbootstrap -source system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa -cups -doc examples -headless-awt jbootstrap source system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa -cups doc examples -headless-awt jbootstrap source system-bootstrap -systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='alsa -cups doc -examples headless-awt jbootstrap -source -system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa cups doc examples headless-awt jbootstrap -source -system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa -cups doc -examples -headless-awt -jbootstrap -source system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa cups doc -examples headless-awt -jbootstrap -source system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='-alsa -cups doc examples -headless-awt jbootstrap -source system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10
USE='alsa -cups doc examples headless-awt jbootstrap source system-bootstrap systemtap' succeeded for =dev-java/openjdk-11.0.18_p10

**Comment by YangMame** [comment]
also need somebody upload this patch to dev distfiles make it stable

**Comment by YangMame** [comment]
ping

**Comment by Flowdalic** [comment]
> also need somebody upload this patch to dev distfiles make it stable

Why? The current URL seems stable, just make sure that the commit does not disappear in the repo. I wonder, however, if we couldn't simply use the primary source of the patch: https://raw.githubusercontent.com/felixonmars/archriscv-packages/91d136561d07d90a163f328ddfff1ffd691b436d/java11-openjdk/java11-riscv64.patch. Or did you add modifications on top of that?

**Comment by YangMame** [comment]
> > also need somebody upload this patch to dev distfiles make it stable
> 
> Why? The current URL seems stable, just make sure that the commit does not disappear in the repo. I wonder, however, if we couldn't simply use the primary source of the patch: https://raw.githubusercontent.com/felixonmars/archriscv-packages/91d136561d07d90a163f328ddfff1ffd691b436d/java11-openjdk/java11-riscv64.patch. Or did you add modifications on top of that?

yes, the patch from felixonmars is missing `include "asm/macroAssembler.hpp"` in`src/hotspot/cpu/riscv64/icache_riscv64.cpp` will fail to build

**Comment by arthurzam** [comment]
Uploaded as https://dev.gentoo.org/~arthurzam/distfiles/dev-java/openjdk/openjdk-11.0.18-riscv.patch.xz

**Comment by YangMame** [comment]
> Uploaded as https://dev.gentoo.org/~arthurzam/distfiles/dev-java/openjdk/openjdk-11.0.18-riscv.patch.xz

updated, pls merge, thanks:)

**Review by arthurzam — APPROVED** [review]
Thank you

**Pull request closed without merging**
