### PR TITLE
dev-python/carbon: remove unused patch

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patch(es) from:
dev-python/carbon

Please review

Signed-off-by: Michael Mair-Keimberger <m.mairkeimberger@gmail.com>

### CODE REVIEW

**Comment by grobian** [comment]
lgtm

**Comment by a17r** [comment]
@grobian are you merging it or do you expect someone else to do that?

**Comment by grobian** [comment]
I don't expect anyone to merge it, but I won't object to anyone doing it before I am in the position to do so.

**Comment by a17r** [comment]
Thanks, I'll do it shortly.

**Pull request closed without merging**
