### PR TITLE
new version...new location for the eula, and xterm is no longer required

### PR DESCRIPTION
**Pull request by Metuchen**
net-misc/icaclient update for latest available version

### CODE REVIEW

**Comment by Metuchen** [comment]
updating download urls, version bump, and removing dependency upon xterm for latest version

**Comment by monsieurp** [comment]
Thanks a lot for your PR. It looks ready to go except the commit messages which do not follow our coding style. Could you reformat them to the following format?
"cat/pkg: commit message"
Also, keep the commit message short. You can style expend in the body of the commit message but the commit message itself has to be brief. Cheers.

**Comment by monsieurp** [comment]
fauli is AWOL. Let's transfer this package to @gentoo/proxy-maint.

**Comment by Metuchen** [comment]
Thanks for the guidance, I've updated the comments.

**Pull request merged**
