### PR TITLE
Mythtv 32.0 r1

### PR DESCRIPTION
**Pull request by thebitpit**

### CODE REVIEW

**Comment by thebitpit** [comment]
Upstream v32.0 requires `libbluray` and `libzip` to configure.

**Comment by thebitpit** [comment]
Why are the QA checks taking so long?

**Comment by thesamesam** [comment]
Can you rebase and force push?

**Comment by thesamesam** [comment]
Worth trying out iwdevtools if not using it already to catch missing deps in some cases at least. Thanks!

**Pull request closed without merging**
