### PR TITLE
sys-apps/ipmicfg: bump to version 1.28.0.180302

### PR DESCRIPTION
**Pull request by ConiKost**
Package-Manager: Portage-2.3.40, Repoman-2.3.9

### CODE REVIEW

**Comment by gyakovlev** [comment]
merged fine here, but please make it 2 separate commits (bumps commit count too =D)
* bumping the package
* removing old one (if required)

**Comment by ConiKost** [comment]
> but please make it 2 separate commits

Okay, done. But that's new for me, as other (simple) bump PRs got this way merged without splitting (unless I want to drop multiple versions). :-)

**Comment by gyakovlev** [comment]
it depends on the dev, but policy is atomic commits. sometimes we may want to revert the removal but leave the new version in the tree. simple mv bump will not let do that cleanly.

Merged, thanks!

**Comment by ConiKost** [comment]
Fine for me, will more split in future :-) Thanks!

**Pull request closed without merging**
