### PR TITLE
gui-wm/hyrpland: Add wlroots-headers use flag and right wlroots version 

### PR DESCRIPTION
**Pull request by MrDuartePT**
The wlroots ebuild added here is to be used with the new wlroots-header use flag added to the Hyprland package.

I made this PR since if you what to use hyprland-plugin ebuild in guru or other hyprland plugin, the plugin will fail to compile since the wlroots version on gentoo is behind the version use to compile hyprland. See this [Issue](https://github.com/hyprwm/hyprland-plugins/issues/46)

Since hyprland use specific commit and not the latest stable version, the version name on the ebuild is the date that specif commit was added to the master brach (ebuild dont allow the commit hash to be use as the version name [wlroots-3406c1b1.ebuild is not valid as atom])

### CODE REVIEW

**Comment by MrDuartePT** [comment]
I notice this version of wlroots break waybar and gamescope, because both of them use 0.16 atom.
Waybar can be solve just by using the live ebuild.
Gamescope dosent have a live ebuild.
I dont know if i can add the atom as 0.16 in this wlroots ebuild?

**Comment by parona-source** [comment]
Adding these wlroots snaphots because of hyprland is no the way to go imo. better to look at making hyprland install its bundled wlroots headers into a non conflicting location and making sure that hyrpland-plugins uses that.

**Comment by sevz17** [comment]
I agree with parona (although I think it would be even better if hyprland didn't create releases from unreleased wlroots versions, but the maintainer is... ugh)

**Comment by MrRoy** [comment]
Did you try the ebuild for hyprland-plugins (in guru)? I ask as someone updated it to 0.31.0 so I'm assuming it can be installed, so this PR wouldn't be needed in the first place.

**Comment by MrDuartePT** [comment]
> Did you try the ebuild for hyprland-plugins (in guru)? I ask as someone updated it to 0.31.0 so I'm assuming it can be installed, so this PR wouldn't be needed in the first place.

Yes, I updated to version 0.31.0 and notice that needed the headers.

**Comment by MrDuartePT** [comment]
> I agree with parona (although I think it would be even better if hyprland didn't create releases from unreleased wlroots versions, but the maintainer is... ugh)

Since both you and @parona-source not like this approach, and you kinda have a good point since this break other package that dependent on wlroots, I will just change this PR to install the headers in another location. 
I think I don’t have time today but tomorrow should have a solution.

**Comment by parona-source** [comment]
@MrDuartePT ill have a look at installing them in the hyprland ebuild. and /usr/local is not good location. package managers are not supposed to touch that

**Comment by MrDuartePT** [comment]
> @MrDuartePT ill have a look at installing them in the hyprland ebuild. and /usr/local is not good location. package managers are not supposed to touch that

I was thinking the same /usr/local is only use when you what to install program manually. Installing hyprland manually using meson will use /usr/local for headers. You have any opnion for the path

**Comment by MrDuartePT** [comment]
@parona-source i give a look to the [makefile](https://github.com/hyprwm/Hyprland/blob/88b47dfa833db2d230a2d6e6bbbf92c69afbdc28/Makefile#L70) I need to verify if meson use the same patch but if its we can use this approach I think this will not overwrite wlroots. I also not sure if meson file includes a way to install the headers like cmake mades

**Comment by parona-source** [comment]
> https://github.com/gentoo/gentoo/pull/33649#issuecomment-1792227846

Id install to /usr/include/hyprland.

**Comment by MrDuartePT** [comment]
@parona-source why hyprland ebuild not use cmake instead since hyprland wiki recomend cmake to build?

**Comment by parona-source** [comment]
The Makefile+cmake(AND meson subprojects still in the mix!!) monstrosity is not great for packaging. The nix packagers added meson in there for a reason, and that is reason is packagers sanity.

**Comment by MrDuartePT** [comment]
Ok go you well I think I found out how nix install the headers gonna do the same for hyprland ebuild

**Comment by parona-source** [comment]
https://github.com/gentoo/gentoo/pull/33661

**Pull request closed without merging**
