### PR TITLE
app-emulation/cadvisor: depend need docker

### PR DESCRIPTION
**Pull request by iamdenchik**
added "need docker" in init scripts
without it have to restart /etc/init.d/cadvisor after reboot server

Signed-off-by: Denis Pershin bazukajo@gmail.com

### CODE REVIEW

**Comment by iamdenchik** [comment]
@mrueg Hi! pls review

**Comment by mrueg** [comment]
Disagreeing here as docker is not the only solution that can be used with cadvisor.

**Comment by iamdenchik** [comment]
@mrueg changed "need" to "use"

**Comment by iamdenchik** [comment]
@mrueg option "use" in init script is correct?

**Comment by mrueg** [comment]
Yes that looks good please squash it into a single commit on master and add a signoff.

**Comment by iamdenchik** [comment]
close

**Pull request closed without merging**
