### PR TITLE
s6 related update

### PR DESCRIPTION
**Pull request by arkamar**
- `sys-apps/s6-rc` is bumped to 0.5.3.1
- the rest is cleanup of old versions

### CODE REVIEW

**Comment by arkamar** [comment]
@thesamesam, @juippis or @williamh Could any of you look at this please?

**Review by juippis — APPROVED** [review]
Didn't seem urgent so I decided to process these PRs in a natural order, but was getting to this soon anyway!

**Comment by arkamar** [comment]
Thanks! No, it wasn't urgnet. I pinged you guys just in case because of my experience from https://github.com/gentoo/gentoo/pull/20895.

**Comment by juippis** [comment]
Heh, yeah. Since you became the maintainer along with proxy-maint project, we get pinged by the team mention from gentoo-bot now! So all good. You can check the "assigned" or "need-assignment" labels.

**Comment by arkamar** [comment]
Ok, thanks :)

**Pull request closed without merging**
