### PR TITLE
dev-python/mpi4py: add 3.1.5

### PR DESCRIPTION
**Pull request by negril**
Adds python3.12 support

Closes: https://bugs.gentoo.org/909923

### CODE REVIEW

**Comment by alexfanqi** [comment]
Hi, thanks for pr.

Please move `DISTUTILS_EXT=1` before `inherit distutils-r1`  to inherit the eclass properly.

I tried to run the test phase, but hit this error.
```                                          
Traceback (most recent call last):
  File "/var/tmp/portage/dev-python/mpi4py-3.1.5/work/mpi4py-3.1.5/./test/runtests.py", line 299, in 
<module>                                                                                             
    sys.exit(main())                                                                                 
             ^^^^^^
  File "/var/tmp/portage/dev-python/mpi4py-3.1.5/work/mpi4py-3.1.5/./test/runtests.py", line 286, in 
main                                              
    package = import_package(options, pkgname)                                                       
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                       
  File "/var/tmp/portage/dev-python/mpi4py-3.1.5/work/mpi4py-3.1.5/./test/runtests.py", line 132, in 
import_package                                                                                       
    package = __import__(pkgname)                                                                    
              ^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'mpi4py'
```
runtests need the module already installed. I am not sure the proper way to fix it, perhaps using `distutils_pep517_install "${BUILD_DIR}"/test`?

Also, `export FAKEROOTKEY=1` is removed from upstream. Can you get rid of it by removing the whole src_compile function (default)? I forgot to do it for last version.

**Comment by mgorny** [comment]
With mpich, I'm getting:

```
 * python3_10: running distutils-r1_run_phase python_test
Beginning test phase
[mpiexec@localhost] match_arg (/tmp/portage/sys-cluster/mpich-3.4.3/work/mpich-3.4.3/src/pm/hydra/utils/args/args.c:163): unrecognized 
argument use-hwthread-cpus
[mpiexec@localhost] HYDU_parse_array (/tmp/portage/sys-cluster/mpich-3.4.3/work/mpich-3.4.3/src/pm/hydra/utils/args/args.c:178): argume
nt matching returned error
[mpiexec@localhost] parse_args (/tmp/portage/sys-cluster/mpich-3.4.3/work/mpich-3.4.3/src/pm/hydra/ui/mpich/utils.c:1603): error parsing input array
[mpiexec@localhost] HYD_uii_mpx_get_parameters (/tmp/portage/sys-cluster/mpich-3.4.3/work/mpich-3.4.3/src/pm/hydra/ui/mpich/utils.c:1655): unable to parse user arguments
[mpiexec@localhost] main (/tmp/portage/sys-cluster/mpich-3.4.3/work/mpich-3.4.3/src/pm/hydra/ui/mpich/mpiexec.c:128): error parsing parameters
```

I'm going to try openmpi.

**Comment by mgorny** [comment]
With openmpi, py3.10 and py3.11 pass. Py3.12 crashes:

```
testToReadonly (test_memory.TestMemory.testToReadonly) ... python3.12: Objects/bytearrayobject.c:64: bytearray_releasebuffer: Assertion `obj->ob_exports >= 0' failed.
[localhost:00185] *** Process received signal ***
[localhost:00185] Signal: Aborted (6)
[localhost:00185] Signal code:  (-6)
[localhost:00185] [ 0] /lib64/libc.so.6(+0x39d70)[0x7f8dce652d70]
[localhost:00185] [ 1] /lib64/libc.so.6(+0x89d6c)[0x7f8dce6a2d6c]
[localhost:00185] [ 2] /lib64/libc.so.6(raise+0x12)[0x7f8dce652cc2]
[localhost:00185] [ 3] /lib64/libc.so.6(abort+0xd3)[0x7f8dce63b4ed]
[localhost:00185] [ 4] /lib64/libc.so.6(+0x22415)[0x7f8dce63b415]
[localhost:00185] [ 5] /lib64/libc.so.6(+0x325e2)[0x7f8dce64b5e2]
[localhost:00185] [ 6] /usr/lib64/libpython3.12.so.1.0(+0x160bdf)[0x7f8dce960bdf]
[localhost:00185] [ 7] /usr/lib64/libpython3.12.so.1.0(PyBuffer_Release+0x58)[0x7f8dcea39428]
[localhost:00185] [ 8] /tmp/portage/dev-python/mpi4py-3.1.5/work/mpi4py-3.1.5-python3_12/install/usr/lib/python3.12/site-packages/mpi4py/MPI.cpython-312-x86_64-linux-gnu.so(+0x4f660)[0x7f8dcc008660]
[localhost:00185] [ 9] /usr/lib64/libpython3.12.so.1.0(+0x22b4f5)[0x7f8dcea2b4f5]
[localhost:00185] [10] /usr/lib64/libpython3.12.so.1.0(+0x22aeb2)[0x7f8dcea2aeb2]
[localhost:00185] [11] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x109f)[0x7f8dcea0f08f]
[localhost:00185] [12] /usr/lib64/libpython3.12.so.1.0(+0x25a75d)[0x7f8dcea5a75d]
[localhost:00185] [13] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x502a)[0x7f8dcea1301a]
[localhost:00185] [14] /usr/lib64/libpython3.12.so.1.0(_PyObject_FastCallDictTstate+0xaa)[0x7f8dcea032aa]
[localhost:00185] [15] /usr/lib64/libpython3.12.so.1.0(_PyObject_Call_Prepend+0x91)[0x7f8dcea3c451]
[localhost:00185] [16] /usr/lib64/libpython3.12.so.1.0(+0x2efd36)[0x7f8dceaefd36]
[localhost:00185] [17] /usr/lib64/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x80)[0x7f8dce9fe110]
[localhost:00185] [18] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0xc2d)[0x7f8dcea0ec1d]
[localhost:00185] [19] /usr/lib64/libpython3.12.so.1.0(+0x25a75d)[0x7f8dcea5a75d]
[localhost:00185] [20] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x502a)[0x7f8dcea1301a]
[localhost:00185] [21] /usr/lib64/libpython3.12.so.1.0(_PyObject_FastCallDictTstate+0xaa)[0x7f8dcea032aa]
[localhost:00185] [22] /usr/lib64/libpython3.12.so.1.0(_PyObject_Call_Prepend+0x91)[0x7f8dcea3c451]
[localhost:00185] [23] /usr/lib64/libpython3.12.so.1.0(+0x2efd36)[0x7f8dceaefd36]
[localhost:00185] [24] /usr/lib64/libpython3.12.so.1.0(_PyObject_MakeTpCall+0x80)[0x7f8dce9fe110]
[localhost:00185] [25] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0xc2d)[0x7f8dcea0ec1d]
[localhost:00185] [26] /usr/lib64/libpython3.12.so.1.0(+0x25a75d)[0x7f8dcea5a75d]
[localhost:00185] [27] /usr/lib64/libpython3.12.so.1.0(_PyEval_EvalFrameDefault+0x502a)[0x7f8dcea1301a]
[localhost:00185] [28] /usr/lib64/libpython3.12.so.1.0(_PyObject_FastCallDictTstate+0xaa)[0x7f8dcea032aa]
[localhost:00185] [29] /usr/lib64/libpython3.12.so.1.0(_PyObject_Call_Prepend+0x91)[0x7f8dcea3c451]
[localhost:00185] *** End of error message ***
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpiexec noticed that process rank 0 with PID 0 on node localhost exited on signal 6 (Aborted).
--------------------------------------------------------------------------
```

**Review by mgorny — CHANGES_REQUESTED** [review]
Blocking because of py3.12 crashes.

**Comment by thesamesam** [comment]
Alex has reported it upstream at https://github.com/mpi4py/mpi4py/issues/450.

**Comment by negril** [comment]
I can't reproduce it locally. Can you get me a full build log in IRC?

**Pull request closed without merging**
