### PR TITLE
dev-libs/libevent: enable thread support unconditionally

### PR DESCRIPTION
**Pull request by floppym**
Bug: https://bugs.gentoo.org/869722

### CODE REVIEW

**Review by mgorny — APPROVED** [review]
LGTM modulo what CI found.

**Comment by xgqt** [comment]
ad rsyslog: LGTM

**Comment by mattst88** [comment]
I suggest letting maintainers handle this on the next bump for large packages (like firefox). I don't think triggering a rebuild here is worth it.

**Comment by arkamar** [comment]
ACK `net-analyzer/sslsplit`

**Comment by floppym** [comment]
> I suggest letting maintainers handle this on the next bump for large packages (like firefox). I don't think triggering a rebuild here is worth it.

I will have to test to ensure portage how will handle existing thunderbird/firefox installs if I change the dependency in-place without a revbump.

**Pull request merged**
