### PR TITLE
www-misc/zoneminder: add myself as maintainer

### PR DESCRIPTION
**Pull request by ktrace**
Add myself and proxy-maint@ as maintainers

Signed-off-by: Victor V. Kustov <ktrace@yandex.ru>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by ktrace** [comment]
On Tue, 04 Dec 2018 14:39:37 -0800
Michał Górny <notifications@github.com> wrote:

> mgorny requested changes on this pull request.
> 
> There's 10 bugs open AFAICS. Fix at least one of them; fixing more
> would be appreciated.

OK 


-- 
  С уважением,            |  Best regards,
          Виктор Кустов   |          Victor Kustov
  XMPP: ktrace@jabber.ru
  I use FREE operation system: 4.14.67-calculate GNU/Linux
  up 9 weeks, 5 days, 16 minutes

**Comment by mgorny** [comment]
Ping.

**Comment by ktrace** [comment]
On Wed, 03 Apr 2019 01:02:56 -0700
Michał Górny <notifications@github.com> wrote:

> Ping.

Alive but too busy till april's end.

-- 
  С уважением,            |  Best regards,
          Виктор Кустов   |          Victor Kustov
  XMPP: ktrace@jabber.ru
  I use FREE operation system: 4.19.29-calculate GNU/Linux
  up 2 days, 1 hour, 54 minutes

**Comment by mgorny** [comment]
Ok. You know what to do and there's no code besides maintainer addition here, so I'm going to close it. Please open a new PR with fixes to the package at your leisure, and add yourself as the maintainer there.

**Pull request closed without merging**
