### PR TITLE
dev-qt/qtwebkit: Allow for compiling with GCC 6

### PR DESCRIPTION
**Pull request by SoapGentoo**
@Pesa @kensington 
While I am fully aware that Qt4 is on its way out, it probably won't disappear from the tree as quickly as we'd like. In the mean time, can we have it work with GCC 6 at least?

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@Pesa mind me adding it?

**Comment by Pesa** [comment]
adding what?

**Comment by SoapGentoo** [comment]
Adding `-std=c++98` to qtwebkit for GCC 6 to not fail compiling it.

**Comment by Pesa** [comment]
commit 5959cfdb7a736cd0ac83bfb13e6fdfb987ac0217 is not enough?

**Pull request closed without merging**
