### PR TITLE
sys-libs/libomp: bump to 3.9.0

### PR DESCRIPTION
**Pull request by zzlei**
@voyageur @mgorny 

BTW, could someone shed light on what the "os detection" patch actually does?

### CODE REVIEW

**Comment by mgorny** [comment]
> BTW, could someone shed light on what the "os detection" patch actually does?

Well, LLVM's openmp comes with some fancy perl scripts which try to detect the distro for some reason. Those scripts used to fail with Gentoo for some reason. So we hacked them to make them work. But honestly, I no longer remember why it failed and have no clue if it's still needed. If you could figure it out, that would be much appreciated. Possibly look for old bugs.

**Comment by voyageur** [comment]
> Well, LLVM's openmp comes with some fancy perl scripts which try to detect the distro for some reason. Those scripts used to fail with Gentoo for some reason. So we hacked them to make them work

At the time the perl script would base its detection on /etc/lsb-release content if it finds it, but would fail if some fields were not set (DISTRIB_RELEASE, DISTRIB_CODENAME, …). And a Gentoo file only has DISTRIB_ID.

**Comment by doughdemon** [comment]
In current openmp git, these perl modules don't seem to be used at all.

**Comment by voyageur** [comment]
Indeed, the old build system was cleaned some time ago:
https://github.com/llvm-mirror/openmp/commit/8aa5b7d1461247f0ab90a02c08c53fc9c9c5f702
and the cmake one does not use these modules. So the patch is not needed anymore :)

**Comment by zzlei** [comment]
**Update**: the "os detection" patch is no longer used in 3.9.0.

**Comment by mgorny** [comment]
Thanks a lot. I'm going to merge this in a few minutes.

**Pull request closed without merging**
