### PR TITLE
media-libs/shaderc: verbump to 2018.0

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by mgorny** [comment]
Sorry, can't test due to https://bugs.gentoo.org/668286

**Comment by mgorny** [comment]
Thanks for the reminder. I couldn't find this PR ;-).

**Comment by mgorny** [comment]
[media-libs:shaderc-2018.0:20181019-105725.log](https://github.com/gentoo/gentoo/files/2495564/media-libs.shaderc-2018.0.20181019-105725.log)

**Comment by haasn** [comment]
A note on your `#ifdef NV_EXTENSIONS` guard. This being removed from newer versions of glslang means this would fail to build against `glslang-9999` or other newer versions of glslang.

If you didn't know, glslang (miraculously!) exports version macros, `#include <glslang/Include/revision.h>`, that you could do use to make this check a bit more flexible, in theory.

Well, in practice, they didn't actually bump the `GLSLANG_PATCH_LEVEL` yet since removing those fields. The best I could narrow down:

Patch level 2892 introduced these fields, guarded by the ifdef. They're currently on patch level 2904 when they removed the macro.

So you would need to depend on `defined(NV_EXTENSIONS) && GLSLANG_PATCH_LEVEL >= 2892 || GLSLANG_PATCH_LEVEL > 2904` and hope they fix the patch level upstream soon.

**Comment by a17r** [comment]
This was bumped in d7b891fb1485664188eebc4efb01b1865d664cbd.

Please rebase and re-open if your ebuild adds fixes over the existing version.

**Pull request closed without merging**
