### PR TITLE
app-dicts/myspell-en: add 20240601, remove redundant l10n_en USE flag

### PR DESCRIPTION
**Pull request by BalkanMadman**
In the previous versions of app-dicts/myspell-en there was a IUSE=l10n_en, which unconditionally enabled all the English varieties. This USE flag is redundant, since the purpose it serves can be as easily achieved by switching the individual USE flags on. Hence, the IUSE=l10n_en is removed. All other English varieties' USE flags are set to be enabled by default, to avoid the need to manually set them in order to mimic the old behaviour (which might have been required in the most cases).

Additionally, as per the dictionary specification in the ./dictionaries.xcu file in the root of the distfile, American thesaurus is suitable for any English variety; British hyphenation is for any non-American English variety. The ebuild is changed to reflect this.

Closes: https://bugs.gentoo.org/481618

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Sorry the latest version got merged from a previous PR. Could you perhaps rebase and implement your changes on top of the already merged version, or try to get it done via the June's version bump? You may have to ping @kuraga to work on it together.

**Comment by kuraga** [comment]
`20240601` version has been bumped yesterday.

**Comment by kuraga** [comment]
@BalkanMadman , thanks very much!

Rename please the  commit _and_ this Github issue to something like
```
app-dicts/myspell-en: add 20240601, change use flags
```

Approve.

**Comment by kuraga** [comment]
@BalkanMadman , approved but let's continue :)

> ```
> PLOCALES=( "en-AU" "en-CA" "en-GB" "en-US" "en-ZA" )
> for lang in "${PLOCALES[@]}"; do
>     if use "l10n_${lang}"; then
>     else
>     fi
> if [[ non_us_dic_used -eq 1 ]]; then
> fi
> ```

Isn't it simpler to make five (or less) `if`s? :)

> ```
> # This is used by every English variety, except for the en-US.
> ```

How could I check it (and other interactions)?

Thanks!

**Comment by kuraga** [comment]
@BalkanMadman ,

The first: oh, thanks about your investigation!

The second: yes, I did. So, at the discretion of @juippis .

**Comment by kuraga** [comment]
Shouldn't we have somewhere?
```bash
MYSPELL_DICT=( )
MYSPELL_HYPH=( )
MYSPELL_THES=( )
```

**Comment by kuraga** [comment]
@BalkanMadman , thanks!

**Comment by kuraga** [comment]
Hm, we didn't set the default `L10N`...

@BalkanMadman , @juippis

**Comment by juippis** [comment]
Could you work up a fast PR and ping me when it's done? I can take a look tomorrow morning.

**Comment by kuraga** [comment]
@BalkanMadman , yes, you're right.
There was `L10N="en ru uk"` in  my `/etc/portage/make.conf`.
Sorry.

**Comment by kuraga** [comment]
Interesting BTW `USE` in  my `/etc/portage/make.conf` means "add to the set of turned on flags" while `L10N` means "set the set of turned on flags exactly to". Right, @juippis ?

**Comment by dememax** [comment]
Sorry, but I've got some troubles updating world:
```
$ emerge -uND --with-bdeps=y --verbose-conflicts --backtrack=30 -pv @world 

These are the packages that would be merged, in order:

Calculating dependencies... done!
Dependency resolution took 9.03 s (backtrack: 0/30).


!!! The ebuild selected to satisfy "app-dicts/myspell-en" has unmet requirements.
- app-dicts/myspell-en-20240801::gentoo USE="" ABI_X86="(64)" L10N="-en-AU -en-CA -en-GB -en-US -en-ZA"

  The following REQUIRED_USE flag constraints are unsatisfied:
    any-of ( l10n_en-AU l10n_en-CA l10n_en-GB l10n_en-US l10n_en-ZA )

(dependency required by "app-text/hunspell-1.7.2-r1::gentoo[l10n_en]" [ebuild])
(dependency required by "app-text/enchant-2.6.1::gentoo" [installed])
(dependency required by "app-text/gspell-1.12.2::gentoo" [installed])
(dependency required by "app-editors/mousepad-0.6.2::gentoo" [installed])
(dependency required by "xfce-base/xfce4-meta-4.18-r1::gentoo" [installed])
(dependency required by "@selected" [set])
(dependency required by "@world" [argument])

 * IMPORTANT: 52 news items need reading for repository 'gentoo'.
 * Use eselect news read to view new items.
```
I've got this values set in `make.conf`:
```
L10N="ru ru_RU en en_GB en_US es fr fr_FR ja zh zh-CN zh-TW"
```
What's wrong with my configurations?

How should I fix my problem, any idea? Thanks!

**Comment by dememax** [comment]
@BalkanMadman    Thanks!

**Pull request closed without merging**
