### PR TITLE
app-antivirus/clamav: package maintenance

### PR DESCRIPTION
**Pull request by Kangie**
- fix failing 1.2.0_rc build (oops) ( <https://bugs.gentoo.org/912178> )
- add `USE=system-mspack`; mask for `x86`  ( <https://bugs.gentoo.org/911402> )
- bump minimum rust version (strictly a rust-bin thing, but it's not stabled yet so 1.2.0 only) ( <https://bugs.gentoo.org/911589> )
- drop 1.0.1

### CODE REVIEW

**Comment by thesamesam** [comment]
Can you rebase?

**Comment by LordVan** [comment]
@Kangie  please do not remove 1.0 (especially not the one i just added last night).
The reason I want to leave it in the tree is because it is the next LTS release - I want to get this stabilized soon as well - even if we have 1.1
see for an easy overview: https://endoflife.date/clamav 0.103 is the old LTS which ends on 2023-09-14 and 1.0 will be the next LTS where supports ends 2025-11-28

**Comment by Kangie** [comment]
Sure, but we'll need to deal with the inevitable 'downgrade' from stabled 1.1.0. I don't have it in me atm but please look into whether 1.0.2 is impacted by <https://bugs.gentoo.org/911402> and take appropriate action.

**Comment by LordVan** [comment]
Yeah I am hesitant to remove stable on 1.1 but if someone wnts the LTS 1.0 they should have the option so I'd like to keep both (stable ) in the tree for now if possible (even if it is something unusual in the tree, but it kinda makes sense to me) I'll look into that bug later.

**Comment by Dessa** [comment]
> 0.103 is the old LTS which ends on 2023-09-14 and 1.0 will be the next LTS where supports ends 2025-11-28
this is no longer accurate for 0.103 due to this: https://blog.clamav.net/2023/05/end-of-life-eol-policy-change-0103-one.html
see also: https://docs.clamav.net/faq/faq-eol.html#version-support-matrix

**Comment by orlitzky** [comment]
> > 0.103 is the old LTS which ends on 2023-09-14 and 1.0 will be the next LTS where supports ends 2025-11-28
> 
> this is no longer accurate for 0.103 due to this: https://blog.clamav.net/2023/05/end-of-life-eol-policy-change-0103-one.html see also: https://docs.clamav.net/faq/faq-eol.html#version-support-matrix

I intend to keep it working for as long as possible, even after the EOL date. That probably means until the first incompatible signature is released.

**Comment by Kangie** [comment]
@orlitzky 

Any objection to (sub)slotting LTS and STS? Any thoughts on how that might impact 0.* or any implementation advice?

**Comment by ConiKost** [comment]
Maybe something like www-servers/nginx has? We use :0 for stable releases, :mainline (term used by upstream) for newer releases.

**Comment by thesamesam** [comment]
I don't like "fake slotting" because it's very confusing for UX. But subslots should work fine here.

**Comment by Kangie** [comment]
Subslotted with `0/lts` and `0/sts`. Happy to amend for any feedback but at this point I think we're good to merge.

**Comment by LordVan** [comment]
I have no objections to those slots

**Comment by orlitzky** [comment]
> @orlitzky
> 
> Any objection to (sub)slotting LTS and STS? Any thoughts on how that might impact 0.* or any implementation advice?

No objection. Someday we may want to use the subslot for e.g. the libclamav ABI but I don't think the "lts" would preclude that.

In general a subslot change would require a revbump but if the subslot is purely informational then I think it's OK to skip.

**Pull request closed without merging**
