### PR TITLE
python-r1.eclass: Ensure that PYTHON_COMPAT is an array

### PR DESCRIPTION
**Pull request by floppym**
As suggested by Arfrever.

Bug: https://bugs.gentoo.org/564258

### CODE REVIEW

**Comment by floppym** [comment]
@gentoo/python please review.

**Comment by prometheanfire** [comment]
lgtm :+1:

**Comment by djc** [comment]
LGTM!

**Comment by mgorny** [comment]
:+1:

**Comment by monsieurp** [comment]
:+1:

**Comment by hasufell** [comment]
:+1:

**Comment by monsieurp** [comment]
Are we going to merge this PR? @floppym?

**Comment by floppym** [comment]
I will merge it this weekend.

**Comment by floppym** [comment]
I made a small tweak and merged this as 4d18149d91c43e257a99df9efbb54ea8d7b05637.

**Pull request closed without merging**
