### PR TITLE
eclass/rust-toolchain: switch back to tar.xz for sources

### PR DESCRIPTION
**Pull request by stefson**
closes: https://bugs.gentoo.org/655600

~@djc - the checks are likely going to fail, as I didn't refresh the `Manifest` file with the new checksums. Can you do that after you merged this?~ 

> problem solved by fetching it at university.

### CODE REVIEW

**Comment by djc** [comment]
So this needs the GCO signoff, can you add that to your commits?

**Comment by stefson** [comment]
like this?

**Comment by djc** [comment]
Squashed, fixed and rebased as b1e72b014ab0da096b840576a295474655da8846. Thanks!

**Comment by stefson** [comment]
Great, but now you've add tar.gz again for `rust-bin`?

**Pull request closed without merging**
