### PR TITLE
net-p2p/syncthing: bump to 0.14.6

### PR DESCRIPTION
**Pull request by sbraz**
@djc just a bugfix release https://github.com/syncthing/syncthing/releases/tag/v0.14.6

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
can we add bash style '[[ ]]' to pkg_postinst?

**Comment by djc** [comment]
LGTM.

**Comment by sbraz** [comment]
@gktrk I replaced all `[` with `[[`.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/16ea9ee...7723b3d. Thanks!

**Pull request closed without merging**
