### PR TITLE
dev-util/edb-debugger: version bump to 1.0.0 and cleanup.

### PR DESCRIPTION
**Pull request by Petross404**
Removed (old) specific versions of Boost and Graphviz.

Package-Manager: Portage-2.3.36, Repoman-2.3.9

### CODE REVIEW

**Comment by mgorny** [comment]
```
 * Messages for package dev-util/edb-debugger-1.0.0:
 * Log file: /var/log/portage/dev-util:edb-debugger-1.0.0:20180807-090051.log

 * One or more CMake variables were not used by the project:
 *   CMAKE_DISABLE_FIND_PACKAGE_GRAPHVIZ

**Comment by monsieurp** [comment]
@Petross404: ping.

**Comment by Petross404** [comment]
I don't know why the following isn't working:
```
src_configure(){
        local mycmakeargs=(
                -DCMAKE_DISABLE_FIND_PACKAGE_GRAPHVIZ=$(usex !graphviz)
        )
        cmake-utils_src_configure
}
```

Based on [this](https://blogs.kde.org/2011/11/11/cool-new-stuff-cmake-286-3-standard-way-disable-optional-packages) that's the way to disable automagic dependencies. [That's](https://github.com/eteran/edb-debugger/blob/master/CMakeLists.txt#L37) the relevant code of CMakeLists.txt too : 
```
if (UNIX)
	find_package(PkgConfig REQUIRED)
	pkg_check_modules(GRAPHVIZ libgvc>=2.38.0)
	if(${GRAPHVIZ_FOUND})
		include_directories(${GRAPHVIZ_INCLUDE_DIRS})
		link_directories(${GRAPHVIZ_LIBRARY_DIRS})
		add_definitions(-DENABLE_GRAPH)
	endif()
endif()
```

**Comment by mgorny** [comment]
That code will work for `find_package()` and not for pkg-config use. Maybe try something along the line of:

    -DGRAPHVIZ_FOUND=NO

**Comment by Petross404** [comment]
Nice catch. The way I get it is to hardcode this variable inside the ebuild with an `if` 
```
src_configure(){
    if ! use graphviz ; then
        local mycmakeargs=(
            -DGRAPHVIZ_FOUND=NO
        )
    fi
    cmake-utils_src_configure
}
```
But with this way, no matter what the use graphviz is I get this : 
```
$ lddtree /usr/bin/edb | grep gr
    libcgraph.so.6 => /usr/lib64/libcgraph.so.6
            libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3

$ equery b /usr/lib64/libcgraph.so.6
 * Searching for /usr/lib64/libcgraph.so.6 ... 
media-gfx/graphviz-2.40.1-r1 (/usr/lib64/libcgraph.so.6 -> libcgraph.so.6.0.0)
media-gfx/graphviz-2.40.1-r1 (/usr/lib64/libcgraph.so.6.0.0)

```

If you are willing please c&c this approach too
```
src_prepare(){
    sed -i -e 's/if(${GRAPHVIZ})/if(NOT ${GRAPHVIZ})/' CMakeLists.txt | die
    ....
}
```

**Comment by Petross404** [comment]
At last, this works : 
```
src_prepare(){
....

        if ! use graphviz ; then
                sed -i -e '/pkg_check_modules(GRAPHVIZ/d' CMakeLists.txt || die
        fi

        cmake-utils_src_prepare
}
```
As soon as I get the gpg signing to work, I will commit the changes.

**Pull request closed without merging**
