### PR TITLE
Update sddm-0.16.0-r1.ebuild

### PR DESCRIPTION
**Pull request by perfect7gentleman**
apply sddm-0.16.0-ck2-revert.patch only case of USE=consolekit

### CODE REVIEW

**Comment by kensington** [comment]
Does it affect runtime behaviour? We generally try to avoid conditional patching.

**Comment by perfect7gentleman** [comment]
>Does it affect runtime behaviour?
of course, not. the patch is applied only consolekit is used.

**Comment by kensington** [comment]
I'm curious why you think conditional patching is better? Fewer code paths means less chance of breakage. flameeyes [described](https://blog.flameeyes.eu/2008/06/why-conditional-patching-and-autotools-rebuild-is-a-bad-idea/) some. good reasons why we avoid it where possible.

Based on my understanding of the code, this patch will only have a runtime affect when consolekit is active and logind is not, so I don't see any benefit of making it conditional at build time.

**Comment by perfect7gentleman** [comment]
I think we should patching where it's possible. The less patches, the better.

**Comment by kensington** [comment]
Sure, the fewer patches the better, but for the patches we do carry we need to maintain. For example, in all probability when sddm-0.17.0 comes out, if this patch was applied conditionally the bump will be broken because nobody that touches our sddm package uses consolekit.

**Comment by perfect7gentleman** [comment]
What do you mean by "bump will be broken"?
I always thought the patch applying should be checked anyway for all use-flags.

**Comment by kensington** [comment]
It's nice in theory but it's not practical. For example, I'm not going to convert my system to consolekit/systemd/libressl/musl/whatever for every single new package I bump.

**Comment by perfect7gentleman** [comment]
in that case how can you guarantee that the patch works? for example, may be patch fixes consolekit2, but breaks elogind and systemd.

**Comment by kensington** [comment]
In context of the full file, it's clear that only consolekit is affected:
```
    if (QDBusConnection::systemBus().interface()->isServiceRegistered(QStringLiteral("org.freedesktop.ConsoleKit"))) {
        qDebug() << "Console kit interface found";
        available = false;
        serviceName = QStringLiteral("org.freedesktop.ConsoleKit");
        managerPath = QStringLiteral("/org/freedesktop/ConsoleKit/Manager");
        managerIfaceName = QStringLiteral("/org.freedesktop.ConsoleKit.Manager"); //note this doesn't match logind
        seatIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.Seat");
        sessionIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.Session");
        userIfaceName = QStringLiteral("org.freedesktop.ConsoleKit.User");
        return;
    }
```

So, I prepared the patch and posted it to the bug where someone reported it worked for them. Considering that the ebuild is already completely broken with consolekit, that's good enough for me.

**Comment by a17r** [comment]
I'm confused here, is there any reason this PR was opened?

**Comment by perfect7gentleman** [comment]
not to use excessive patching

**Comment by kensington** [comment]
Sorry, we won't be merging this for the reasons mentioned in previous comments.

**Pull request closed without merging**
