### PR TITLE
profiles: add CC/CXX to info_vars

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
@mgorny does that look reasonable? It is helpful if people run clang for example or do other funny stuff with their CC/CXX variables

**Comment by mgorny** [comment]
Let's get some more teams to discuss this.

**Comment by mgorny** [comment]
@gentoo/qa, @gentoo/portage.

**Comment by zmedico** [comment]
LGTM. Portage only displays the variables if they are set, so I don't see any harm in adding CC and CXX to the list.

**Pull request closed without merging**
