### PR TITLE
maintainer-needed: old version cleanup

### PR DESCRIPTION
**Pull request by mgorny**
This PR removes all old/redundant versions from maintainer-needed packages, as reported by pkgcheck.

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/qa, anyone wants to review it? ;-)

**Comment by ulm** [comment]
Have you checked that this won't cause any license masks, i.e. old version free, new version non-free?

**Comment by mgorny** [comment]
> Have you checked that this won't cause any license masks, i.e. old version free, new version non-free?

Nope. Can you suggest a quick way of checking that? I guess grepping LICENSE after the changes might help.

**Comment by mgorny** [comment]
For all packages with non-free licenses, no license changes I see.

**Pull request closed without merging**
