### PR TITLE
sci-libs/openblas: New Package

### PR DESCRIPTION
**Pull request by hsntgm**
@perfinion as discussed on IRC openblas is ready for lc0 -> https://github.com/gentoo/gentoo/pull/11526
After this one merged i will update lc0 PR.

Thanks.

### CODE REVIEW

**Comment by hsntgm** [comment]
We were working with @perfinion for that one.I also want to inform @maffblaster @alexxy @tamiko that i see on IRC they are in science-group (I am not sure %100).

If no one interested, i am adding @monsieurp (hopefully will return) @candrews from proxy-maint.

There is a script comes with package for switching between default reference blas,lapack,cblas and gsl set system-wide.Script is compatible with eselect.

I hope proxy-maint is not over and one of you is interested in contributions.If no one cares please let me know and i will stop contribution and add maintainer-needed to all my packages.

Thanks.

**Comment by perfinion** [comment]
Hey,
I'm back from travelling a bunch, I'll take a look at this over the next couple days :) thanks for your patience

**Comment by hsntgm** [comment]
@perfinion 
ping
Hope you didn't forget.Did you find something I should edit here?

**Comment by hsntgm** [comment]
@perfinion i see that an-other openblas PR has already merged  :)))

I am closing this PR.

Thank you @cdluminate

**Comment by heroxbd** [comment]
@hsntgm Thank you for your pull request!  I am very glad to see your featureful switching script as well.

I apologized for not noticing your work when @cdluminate and I implemented the new framework.

Please give the new blas switching framework a test, referring to https://wiki.gentoo.org/wiki/Blas-lapack-switch.

Feel free to ping me when you have other ebuilds to get into the tree in the future.

**Comment by hsntgm** [comment]
@heroxbd you are welcome ! My switch script was very experimental :)

You do great job. No problem at all. Sure i will test new framework as soon as possbile but first there are some notes i can suggest for ebuild. Maybe you consider.

```
src_unpack () {
	default
	find "${WORKDIR}" -maxdepth 1 -type d -name \*OpenBLAS\* && \
		mv "${WORKDIR}"/*OpenBLAS* "${S}" || die
}
```
to

```
src_unpack() {
	default
	mv "${WORKDIR}"/*OpenBLAS* "${S}" || die
}
```

Also cblas lapack and int64 use flags can be add -->

```
use int64 && openblas_flags+=( INTERFACE64=1 )
use !cblas && openblas_flags+=( NO_CBLAS=1 )
use !lapack && openblas_flags+=( NO_LAPACK=1 )
```

You can also consider testing OpenMP  -->

`use openmp && tc-check-openmp`

**Pull request closed without merging**
