### PR TITLE
net-wireless/rtl88x2bu new ebuild

### PR DESCRIPTION
**Pull request by ephemer0l**
Signed-off-by: Scott Martin <om@organizedmagnetism.com>

Tested on amd64. Could potentially support arm arm64 and x86.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
802.11r is broken in this version of the driver, but the entropiceffect fork which I've been using doesn't even build against 5.12.13 so I'm kind of unsure which to proceed with.  802.11r isn't in "wide" use, so I suspect "builds" is better than "has 802.11r support but doesn't build"  Lemme poke at this and I'll merge something.

**Comment by ephemer0l** [comment]
Thanks for your time.

**Comment by ZeroChaos-** [comment]
even the maintainer of the driver says "don't use this driver", I'm not sure we want this
https://github.com/morrownr/88x2bu/commit/cc94acc06fb7fb85ec27f4983953bef1fe35a474

**Comment by ephemer0l** [comment]
Is a working driver better then none?

**Comment by ephemer0l** [comment]
Updated to add to @module-rebuild set. I still cant find a way to get the ebuild to sign the kernel module.

**Comment by ZeroChaos-** [comment]
> Updated to add to @module-rebuild set. I still cant find a way to get the ebuild to sign the kernel module.

this is how I do it
https://github.com/pentoo/pentoo-overlay/blob/master/profiles/pentoo/base/profile.bashrc#L26-L49

**Comment by ephemer0l** [comment]
I've added it to the README. Any other critiques?

**Comment by thesamesam** [comment]
Closing per Z_C's comments and issues with past maintenance.

**Pull request closed without merging**
