### PR TITLE
dev-java/commons-beanutils: fix test failures

### PR DESCRIPTION
**Pull request by vaukai**
Test sources of commons-collections-3.2.2 are needed for compiling the test cases but are not part of the commons-collections.jar file.

Also some minor style update.

Closes: https://bugs.gentoo.org/923600

### CODE REVIEW

**Comment by fordfrog** [comment]
i went through this but i don't understand the fix and there is no explanation in the patch nor the referenced bug. could you please enhance the patch header to explain the fix?

**Comment by vaukai** [comment]
> i went through this but i don't understand the fix and there is no explanation in the patch nor the referenced bug. could you please enhance the patch header to explain the fix?

just added the header explaining from where the patch is stolen.

**Comment by fordfrog** [comment]
> > i went through this but i don't understand the fix and there is no explanation in the patch nor the referenced bug. could you please enhance the patch header to explain the fix?
> 
> just added the header explaining from where the patch is stolen.

oh my poor memory 🤦 😄

**Comment by fordfrog** [comment]
```
There were 3 failures:
1) testFloatLimits(org.apache.commons.beanutils.locale.converters.FloatLocaleConverterTestCase)
junit.framework.AssertionFailedError: Positive Float.MIN_VALUE expected:<1.4E-45> but was:<1.4012984E15>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:78)
	at junit.framework.TestCase.assertEquals(TestCase.java:238)
	at org.apache.commons.beanutils.locale.converters.FloatLocaleConverterTestCase.testFloatLimits(FloatLocaleConverterTestCase.java:277)
2) testObjectToStringScalar(org.apache.commons.beanutils.locale.LocaleConvertUtilsTestCase)
junit.framework.ComparisonFailure: Double->String expected:<123[,]4> but was:<123[.]4>
	at junit.framework.Assert.assertEquals(Assert.java:100)
	at junit.framework.TestCase.assertEquals(TestCase.java:253)
	at org.apache.commons.beanutils.locale.LocaleConvertUtilsTestCase.testObjectToStringScalar(LocaleConvertUtilsTestCase.java:301)
3) testPositiveScalar(org.apache.commons.beanutils.locale.LocaleConvertUtilsTestCase)
junit.framework.AssertionFailedError: expected:<123456.0> but was:<123.456>
	at junit.framework.Assert.fail(Assert.java:57)
	at junit.framework.Assert.failNotEquals(Assert.java:329)
	at junit.framework.Assert.assertEquals(Assert.java:120)
	at junit.framework.Assert.assertEquals(Assert.java:129)
	at junit.framework.TestCase.assertEquals(TestCase.java:277)
	at org.apache.commons.beanutils.locale.LocaleConvertUtilsTestCase.testPositiveScalar(LocaleConvertUtilsTestCase.java:479)
```
i think we should force english locale as with my locale some tests fail

**Comment by vaukai** [comment]
> ```
> 
> ```
> 
> 
>     
>   
> 
> i think we should force english locale as with my locale some tests fail

i've added `export LC_ALL="en_US.UTF-8"`

**Pull request closed without merging**
