### PR TITLE
Keyword some packages for ~arm64

### PR DESCRIPTION
**Pull request by stintel**
Tested on MacBook Air (15-inch, M2, 2023).

### CODE REVIEW

**Review by bowlofeggs — APPROVED** [review]
LGTM for starship

**Comment by thesamesam** [comment]
Do tests pass for all of these?

**Comment by ajakk** [comment]
Fine by me for arti iff tests pass.

**Review by ConiKost — APPROVED** [review]
ok for networkmanager-strongswan-1.6.0, it you tested it.

**Comment by stintel** [comment]
> Do tests pass for all of these?

FEATURES=test failed for arti, succeeded for the other 3. Dropped arti from the PR.

**Comment by thesamesam** [comment]
> > Do tests pass for all of these?
> 
> FEATURES=test failed for arti, succeeded for the other 3. Dropped arti from the PR.

Thanks!

**Pull request closed without merging**
