### PR TITLE
dev-vcs/darcs: remove unused patch

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

Another small PR. This removes a unused patch from dev-vcs/darcs.
The package belongs to the gentoo haskell project: @markwright @orlitzky @qnikst @vikraman 

Please review.

### CODE REVIEW

**Comment by orlitzky** [comment]
Pulled, thanks! Is there a Haskell team alias set up? If so, please add @trofi to it =)

**Comment by mm1ke** [comment]
Thanks for the pull :) I hope you're not asking me about the team alias.
I don't see any aliases nor can i add members there.. ;)

**Comment by trofi** [comment]
LGTM

**Comment by SoapGentoo** [comment]
Merged

**Pull request closed without merging**
