### PR TITLE
sys-devel/llvm-roc: new version: 5.0.1

### PR DESCRIPTION
**Pull request by littlewu2508**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Yiyang Wu <xgreenlandforwyy@gmail.com>

### CODE REVIEW

**Comment by littlewu2508** [comment]
@candrews @heroxbd Please have a look at the new version. The ROCm-5.0 is a major new release with RDNA2 chip officially supported, and I've already got half of the ebuilds, and there are [users wishing for the upgrade](https://www.phoronix.com/forums/forum/phoronix/latest-phoronix-articles/1312623-amd-rocm-5-0-2-released-with-a-fix-minor-documentation-update?p=1312627#post1312627), so it would be very nice if we start packaging.

**Comment by heroxbd** [comment]
`dev-libs/rocm-comgr` depends on and links to `llvm-roc`.  Do you have a accompanying pull request of `rocm-comgr` to be tested with `llvm-roc`?

**Comment by littlewu2508** [comment]
> `dev-libs/rocm-comgr` depends on and links to `llvm-roc`. Do you have a accompanying pull request of `rocm-comgr` to be tested with `llvm-roc`?

rocm-comgr-5 is in https://github.com/littlewu2508/gentoo/commits/dev-libs/rocm-comgr. Need rocm-device-libs first

**Comment by littlewu2508** [comment]
The new version bump PR is https://github.com/gentoo/gentoo/pull/24681 containing llvm-roc

**Comment by heroxbd** [comment]
littlewu2508 ***@***.***> writes:

> there are users wishing for the upgrade

Consider thanking these users in one of your commit messages ;)

**Pull request closed without merging**
