### PR TITLE
Nftables version bump to 0.6, support file cleanup, and removed of old version

### PR DESCRIPTION
**Pull request by nvinson**

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by nvinson** [comment]
Please hold on merging this one.  There is a scenario I forgot to consider.  Once I review it, I'll reply back to this request.  Thanks.

**Comment by nvinson** [comment]
I think what I have now is about as good as it's going to get.  Please review.  Thanks.

**Comment by gktrk** [comment]
LGTM for the most part. Last commit warrants a revbump since we change the init files and whatnot.

**Comment by gktrk** [comment]
Merged. Thanks!

**Comment by gktrk** [comment]
What I did extra before merge:

- Remove unnecessary inherit on eutils
- Add missing ${EROOT} in postinst.

**Pull request closed without merging**
