### PR TITLE
media-sound/teamspeak-{client,server}-bin: renamed by dropping -bin

### PR DESCRIPTION
**Pull request by ConiKost**
media-sound/teamspeak-{client,server}-bin: renamed by dropping -bin

### CODE REVIEW

**Comment by mgorny** [comment]
Do you really think that's worth the hassle? If you insist, please rebase ;-).

**Comment by mgorny** [comment]
(also, it's a good idea to ping us when you file PRs with early expiration date)

**Comment by ConiKost** [comment]
@mgorny: I would be happy, thanks! :)

**Comment by ConiKost** [comment]
Sorry, should be now okay.

**Comment by mgorny** [comment]
Merged, thanks!

**Pull request closed without merging**
