### PR TITLE
dev-python/backports-{tempfile,weakref}: revbump to r2 and move to PYTHON3_{8..10}

### PR DESCRIPTION
**Pull request by scardracs**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by mgorny** [comment]
Why would you be adding new implementations to a backport package?

**Comment by scardracs** [comment]
Because bmaptools (on ::guru) depends on these for tests

**Comment by mgorny** [comment]
Wouldn't it be better to fix bmaptools then?

**Comment by scardracs** [comment]
> Wouldn't it be better to fix bmaptools then?

What you mean about "fix bmaptools"? Are these backports like "patches"?

**Pull request closed without merging**
