### PR TITLE
net-p2p/syncthing-relaysrv: remove

### PR DESCRIPTION
**Pull request by khumarahn**
Hi, net-p2p/syncthing-relaysrv has been merged into net-p2p/syncthing by both upstream and gentoo.

### CODE REVIEW

**Comment by khumarahn** [comment]
@djc

**Comment by mgorny** [comment]
Hi, Alexey. Thank you for your PR. However, in Gentoo we don't remove packages (even if obviously merged) without last rites procedure that helps our users see why the package disappears.

Please take a look at https://devmanual.gentoo.org/ebuild-maintenance/index.html#removing-a-package. While the procedure is pretty much dev-oriented, you can send the last rites yourself and provide a PR adding an appropriate package.mask, with your name and e-mail in it.

**Comment by khumarahn** [comment]
Hi Michał,

ok. I have sent the email, and changed this PR to mask `net-p2p/syncthing-relaysrv`. Does it look correct?

**Comment by khumarahn** [comment]
@mgorny ping?

**Comment by khumarahn** [comment]
anybody ping?

**Comment by djc** [comment]
Pushed as 192eb41, thanks!

**Comment by monsieurp** [comment]
It's dealt with in this case. Closing.

**Pull request closed without merging**
