### PR TITLE
Cinnamon 5.0 Version Bump

### PR DESCRIPTION
**Pull request by SparkyBluefang**
https://bugs.gentoo.org/792933
https://bugs.gentoo.org/467994

This updates the Cinnamon collection of packages to the latest released 5.0.x versions.

After major releases, Cinnamon has a period of fairly high churn for bug fixes and point releases. While this PR is open, I'll keep it updated with any releases as they happen.

Supersedes #21029 and includes the #20957 changes for 5.0.0 - though not sure it's worth going back and updating old versions, as I'm going to remove 4.6 and 4.8 as soon as 5.0 is stabilized.

### CODE REVIEW

**Comment by gyakovlev** [comment]
I've cherry picked caribou vala fix, feel free to drop that commit https://github.com/gentoo/gentoo/pull/21047/commits/e68b7f70bc26da03f4c09873b30cea369dddeb75

**Comment by SparkyBluefang** [comment]
I split out the unrelated xapp[s] changes into #21079

**Comment by ItzSwirlz** [comment]
Cinnamon 5.0.0x has a new spices updater tool named "harvester" and since the upstream developers are Debian central, the directory 'usr/lib/python3' may need to be relocated, Fedora moves it to 'usr/lib/python3.9'. Linked PR to the upstream issue.

**Comment by SparkyBluefang** [comment]
@ItzSwirlz This is handled in the currently proposed package. It's just a little clunky :)
https://github.com/gentoo/gentoo/pull/21047/files#diff-dcc99c866b10435d1dbc1165cccc4f9579b77973863934b0d31a6f4d51e2e49cR136-R137

**Comment by thesamesam** [comment]
Great work, thank you!

**Pull request closed without merging**
