### PR TITLE
dev-lang/moarvm: revbump 2016.03

### PR DESCRIPTION
**Pull request by tomboy-64**
@patricklauer I made the ebuild actually reflect the build system. I will leave forwarding of the patch up to you.
@gentoo/proxy-maint

### CODE REVIEW

**Comment by rindeal** [comment]
The use of `usex()` in `src_configure()` would make the section much shorter and readable

**Comment by tomboy-64** [comment]
fair enough. the reason for not using it is no longer valid.

**Comment by monsieurp** [comment]
@tomboy-64 Hi! Patrick does not look at github at all. File a bug please.

**Comment by rindeal** [comment]
@monsieurp [his log](https://github.com/patricklauer?tab=activity) shows some activity just 16 days ago

**Comment by tomboy-64** [comment]
Closing for now, pending response on the respective bug.

**Pull request closed without merging**
