### PR TITLE
sci-misc/boinc: bump 7.8.4 & SLOT wxGTK:3.0-gtk3

### PR DESCRIPTION
**Pull request by kuzetsa**
bug: https://bugs.gentoo.org/618642

Package-Manager: Portage-2.3.13, Repoman-2.3.3

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@Yamakuzure please have a look, this is semi-urgent, we need to move people off the old gtk2-using wxGTK crap, because it's a gaping security hole.

**Comment by leio** [comment]
Added reference to https://bugs.gentoo.org/640822 manually. Either the bot collided with my changes, or it didn't work from forced push.

**Comment by kuzetsa** [comment]
boincmgr runs on the new version, tentatively at:

https://github.com/kuzetsa/gentoo/tree/acb4e1386f1d9d07ac18a47433ee8f79bff74eaf/x11-libs/wxGTK  
@ PR https://github.com/gentoo/gentoo/pull/6513

**Comment by Yamakuzure** [comment]
@SoapGentoo : I am all for it. Moving away from gtk2-using wxGTK is a good thing.

I'll have a fresh look at BOINC soon, but this won't be until next weekend, sorry.

**Comment by Yamakuzure** [comment]
@SoapGentoo While I am fixing the issues on my laptop (see bug 640822) I'd appreciate if this was merged, as I wanted to bump the version anyway. I can then rebase my current work on this ebuild and will clean up the old one with my upcoming PR.

**Comment by leio** [comment]
Merged, with a follow-up commit to do iconcache update (which was another PR merged separately in the meantime), but with fixes to that (didn't re-add unnecessary gnome2_icon_savelist call). I guess theoretically the iconcache update isn't necessary without USE=X, but that's how it was. If you find that it should be conditional, do it with savelist re-added and the list checking around gnome2_icon_cache_update calls like in eclass/gnome2.eclass - not based on X USE flag conditional.

**Pull request closed without merging**
