### PR TITLE
Test pull request

### PR DESCRIPTION
**Pull request by mgorny**
This one's testing updated CI. Please disregard.

### CODE REVIEW

**Comment by monsieurp** [comment]
LGTM. Can we merge it? @mgorny

**Comment by mgorny** [comment]
@monsieurp, doesn't look good actually. Unless I'm missing something, it should have the gimp/gegl failure from ::gentoo.

**Comment by mgorny** [comment]
Good.

**Comment by mgorny** [comment]
@monsieurp, you can merge now.

**Pull request closed without merging**
