### PR TITLE
sys-apps/bat: don't pre-strip executable; use shell-completion.eclass; modernize cargo.eclass

### PR DESCRIPTION
**Pull request by sevz17**
Not sure if first commit requires a revbump

### CODE REVIEW

**Comment by thesamesam** [comment]
> Not sure if first commit requires a revbump

I think so.

**Comment by thesamesam** [comment]
Looks like we really need to stable something newer too.

**Comment by sevz17** [comment]
> Looks like we really need to stable something newer too.

True, seems like last release was ~6 months ago...
Do you want me to create a stabilization bug?

**Comment by thesamesam** [comment]
I just filed https://bugs.gentoo.org/914779 real quick so we didn't forget (I was planning on having you do it, but given it's been like 200 days since the last thing got stabled, I didn't want to risk forgetting).

**Pull request closed without merging**
