### PR TITLE
net-dns/dnsdist: add ~arm ~arm64 ~x86 keywords

### PR DESCRIPTION
**Pull request by 9dt**
Sorry to bother you so soon after the last changes of yesterday.

The architectures added with this change do work without problems.

Thanks a lot.

### CODE REVIEW

**Comment by mgorny** [comment]
Not sure what the exact rules on ARM keywording are, with all the ARM versions. @gentoo/arm?

**Comment by 9dt** [comment]
If I search through the portage tree for arm64, there are ebuilds containing it.
Also, I've tested it on real arm64 (if you prfere aarch64) hardware. It does work.

**Comment by mgorny** [comment]
AArch64 & x86 are fine. Plain ARM (32-bit) is what I'm not sure about.

**Comment by 9dt** [comment]
Can/should [the arch list of portage](https://github.com/gentoo/gentoo/blob/19519a2a06843b322d5074858242816ac6b1963a/profiles/arch.list) considered as a reference?

**Comment by mgorny** [comment]
> Can/should the arch list of portage considered as a reference?

This file lists only valid keyword values. You need to account for state of profiles and arch team policies as well.

amd64 & x86 are pretty much 'free for all', as long as you test it on some hardware.

arm64 is a bit more complex. If you have a hardware, it's mostly fine to add keywords. However, note that the profiles for arm64 are not stable, so you need to specifically set `repoman` to check depgraph for arm64 and make sure you don't introduce new breakage. The arm64 team is working hard to clean up the current keywording mess, and they aren't very happy about having new packages marked arm64 unless people actually are interested in them.

For all other arches, you have to refer to specific arch team instructions and/or talk to them. Many of less common architectures have specific rules and/or do not add keywords to new packages unless someone explicitly needs them (and by 'needs', I mean 'is going to actually use the package on this architecture'). Most of the time just file a keywordreq for the arch team, and they either test the package on all relevant hardware, or reject the request.

**Comment by 9dt** [comment]
Michał, thank you very much for the explanation.

**Comment by 9dt** [comment]
Sorry it took a little longer.

For now ~amd64 and ~x86 should do fine.

**Pull request closed without merging**
