### PR TITLE
games-arcade/xsfcave: EAPI8 bump, drop old

### PR DESCRIPTION
**Pull request by mm1ke**
another `EAPI8` bump for `games-arcade/xsfcave`

The sourceforge Homepage is pretty useless (but the download works). I've decided to use an archive page of the homepage. Still better than nothing.
Also added an missing dependency.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by chewi** [comment]
I was actually going to last-rite this, along with spacerider and tuxdash. I needed to find the time to see which other games were dead upstream and so awful that they weren't work keeping. I didn't try njam yet, but it looks passable.

**Comment by mm1ke** [comment]
> I was actually going to last-rite this, along with spacerider and tuxdash. I needed to find the time to see which other games were dead upstream and so awful that they weren't worth keeping. I didn't try njam yet, but it looks passable.

@chewi 
That's fine, let me know if you want to last-rite it. 
Actually I had a quick look at the others too but also decided to leave them as they had open bugs and carrying lots of patches. I already thought they might be last-rited.
`njam` looked fine as it had an (semi)official homepage and only one bug which was easy to fix. since `xsfcave` didn't had any bugs and doesn't carry any patches i though it would be worth keeping.

I was also thinking to look at the other `EAPI6` games to see if i can update them - should i leave them for now?

**Comment by chewi** [comment]
All the others have open bugs, apart from gmudix, which is dead upstream and GTK+2. That should probably go, but the rest are fair game if you want to have a look. I'd quite like to keep xu4, which is still active but long overdue a bump and requires some new dependencies.

**Comment by chewi** [comment]
Closing this so I can last rite it.

**Pull request closed without merging**
