### PR TITLE
app-editors/{vscode,vscodium}: version bump to 1.67.0

### PR DESCRIPTION
**Pull request by AdelKS**
Hello, 

A little version bump for vscode and vscodium. The `vscodium` package is missing the `arm` arch because of dependency issues, more information [here](https://github.com/VSCodium/vscodium/issues/1072). So we will drop it for now.

Adel

### CODE REVIEW

**Comment by AdelKS** [comment]
@arthurzam Ready to go! (check my first comment, I dropped `arm` from `vscodium` for now)

**Comment by arthurzam** [comment]
@AdelKS I think the fix for wlroots was merged for 1.67.0 - could you test id I'm correct
Either way, tomorrow I can test on my sway machine.

Also, is the `arm` drop because of no bin upstream? It would be nice to have some more info added to commit message :)

**Comment by AdelKS** [comment]
> I think the fix for wlroots was merged for 1.67.0 - could you test id I'm correct
Either way, tomorrow I can test on my sway machine.

Yeah please check (I do not have sway installed), I couldn't find information about it, as [the relevant issue](https://github.com/microsoft/vscode/issues/141964) did not get proper tags to understand if it got released or not.

**Review by ArnaudLier — APPROVED** [review]

**Review by arthurzam — CHANGES_REQUESTED** [review]
Yep, it works on `gui-wm/sway-1.7` and `gui-libs/wlroots-0.15.1` - please remove the `has_version` warning 😄

**Review by arthurzam — APPROVED** [review]
Excellent - good job!

**Pull request closed without merging**
