### PR TITLE
net-im/telegram-desktop: add 4.14.15

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

**Telegram Desktop** 4.14.15 was released recently.
It would be nice to have it available in the Portage tree.

_Release:_
  - https://github.com/telegramdesktop/tdesktop/releases/tag/v4.14.15

_Changelog:_
  - https://github.com/telegramdesktop/tdesktop/blob/v4.14.15/changelog.txt

_Best regards!_

### CODE REVIEW

**Comment by mid-kid** [comment]
Hi, thanks for your contribution. It looks good to me, and I trust that you've tested it, but please give it a few days, as upstream has a tendency to do releases in quick succession before starting the next dev cycle. I'd rather test one version than trying to track a moving target that takes an hour to build (assuming it does so in one attempt) these days.

Speaking of testing, I'm currently building a sideproject (my livecd) which might take another week depending on how many iterations I need to get it working, so I'm kind of unable to run my usual testing scripts right now. I'm fine releasing this particular version without my usual testing (no strange new deps), but it bothers me that I still haven't managed to procure a method of doing CI without clogging my main machine.

Anyway, I'll ping dlan to merge it if there's no new versions by thursday.

**Comment by Jamim** [comment]
Thank you, @mid-kid!
There is no rush, so let's wait and see if there are any updates in the upstream.
In fact, this version was released when I was going to build 4.14.12, but I checked for updates before starting an hour-long build process 😅

**Comment by Jamim** [comment]
_Hello @mid-kid,_
Your were right. They just released two new versions in quick succession.
I've built and verified 4.14.15. The PR has been updated.
_Best!_

**Comment by dlan17** [comment]
@mid-kid I don't mind to have more frequent/quick updates, even might encounter some issues, we can always fix them later.. so let me know if you want to push this version.. btw, I will usually do a quick local build/run time test before pushing it

**Comment by mid-kid** [comment]
@dlan17 alright, sorry for holding you up. go ahead

**Comment by dlan17** [comment]
@mid-kid yeah, no worry, it's always a trade-off to "keep stable" vs "move fast", as a downstream package maintainer, I'd suggest to just follow upstream & balance your efforts, thanks

**Pull request closed without merging**
