### PR TITLE
mail-filter/rspamd: Version bump to 1.5.6

### PR DESCRIPTION
**Pull request by croessner**
New version that adds a new USE flag hyperscan (dev-libs/hyperscan)

### CODE REVIEW

**Comment by djc** [comment]
Since rspamd does not configure hyperscan by default, I think it we should not default it to enabled for rspamd, either. Maybe there should be a proper `REQUIRED_USE` restriction on the use of `pcre2` and `hyperscan` USE flags, because it appears that enabling both does not make sense. Also, `hyperscan` appears to only work on `amd64`, so that should probably also be restricted in the ebuild somehow (also `REQUIRED_USE`?).

Do you want to take over as (proxied) maintainer for rspamd? I CC'ed you on https://bugs.gentoo.org/show_bug.cgi?id=611890, but apparently you haven't seen that?

**Comment by croessner** [comment]
I asked in IRC yesterday, if the suggest hyperscan. And they do. The reason, why it is not default is that most distris do not have hyperscan. So, as we do have this now, we should follow there suggestion. :-)

**Comment by croessner** [comment]
And yes, I can do proxy maint :-) Thanks :-)

**Comment by croessner** [comment]
I read again :) hyperscan and pcre can both be enabled and this is the suggested path. All rules that can not be processed by hyperscan are done with pcre.

Concerning REQUIRED_USE: I have no idea how to do it :)

For amd64 pcre2 and hyperscan should be enabled by default
For x86 only pcre2

Can you do this? :) Please?

**Comment by djc** [comment]
Okay, in that case it looks like `REQUIRED_USE` is the wrong method anyway. I think what you have to do is add a mask entry to `profiles/arch/base/package.use.mask` and then also add an enabling entry to `profiles/arch/amd64/package.use`. Can you test if you can get that working? Obviously you need to add the comments as per usual in those files, you'll see.

**Comment by croessner** [comment]
Ok, first I removed the ~x86 USE flag from the hyperscan ebuild (I must PR this, too. I guess this does not require a revbump, right?). Then I added:

# Christian Roessner <cr@sys4.de> (24 Apr 2017)
# dev-libs/hyperscan is only keyworded on amd64
mail-filter/rspamd hyperscan

to the package.use.mask, which works:

[ebuild   R   ~] mail-filter/rspamd-1.5.6::croessner  USE="fann gd jemalloc jit pcre2 (-hyperscan*) -libressl" 0 KiB

But no matter how hard I try to add the hyperscan USE flag to the other file, it still masks it as shown above. I use Gentoo hardened, so I also tried to add it to the correct profile as well. Did not work, adding it also to no-multilib. Here are the three files I tested:

/misc/portage/profiles/hardened/linux/amd64/package.use
/misc/portage/profiles/hardened/linux/amd64/no-multilib/package.use
/misc/portage/profiles/arch/amd64/package.use

/misc/portage is autofs to my LVM partition lv_portage, which contains the portage tree).

In which file should I place the USE flag?

cd /etc/portage; ls -l

make.profile -> ../../misc/portage/profiles/hardened/linux/amd64/no-multilib

**Comment by croessner** [comment]
I found a better solution. I have modified hyperscan to REQUIRED_USE="cpu_flags_x86_ssse3", which is the only dependency in the official documentation.

This way I have added this USE flag to IUSE in rspamd ebuild instead of hyperscan. If the USE flag is found, the ebuild implicitly uses hyperscan, which is the recommended way from the Rspamd guys.

What do you think? Is this ok for you? If so, I will update the PRs (createing a new one for hyperscan and updateing this one for rspamd)

**Comment by croessner** [comment]
Just have a look at my h441 branch for dev-libs/hyperscan and r156 branch for changes to Rspamd. I have modified the ebuilds as described in my last post.

**Pull request closed without merging**
