### PR TITLE
app-admin/ulogd: remove useless description from metadata.xml

### PR DESCRIPTION
**Pull request by Coacher**
Again.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by idella** [comment]
Coacher the description tag is not useless, but rather decided not mandatory. I edited commit msg accordingly. It is still a valid tag within maintainer, it was decided that preference is for it to not be made a default sub tag.

**Comment by Coacher** [comment]
@idella, it seems useless to me because I am already the first in the maintainer's list so bugs already should be assigned to me. Stating the obvious again in the description is unnecessary IMHO.

**Comment by Coacher** [comment]
Thank you for commiting.

**Pull request closed without merging**
