### PR TITLE
sys-devel/gcc-apple: drop toolchain.eclass

### PR DESCRIPTION
**Pull request by thesamesam**
We use only a tiny function from it and this prevents modernising the eclass.

Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by thesamesam** [comment]
@grobian can you check the gcc-apple bit please? I haven't got any hw to test build it. It looks like it doesn't use anything from toolchain.eclass after my commit, but I've only checked by eye.

**Comment by grobian** [comment]
@thesamesam yes ok, go ahead and push this

**Review by grobian — APPROVED** [review]

**Comment by ionenwks** [comment]
Briefly mentioned that on IRC before, but gcc-apple also uses CTARGET that's been initialized by toolchain.eclass'
```
export CTARGET=${CTARGET:-${CHOST}}
if [[ ${CTARGET} = ${CHOST} ]] ; then
    if [[ ${CATEGORY} == cross-* ]] ; then
        export CTARGET=${CATEGORY#cross-}
    fi
fi
```
Without that CTARGET is likely to give a blank value in bits like:
`sed -i -e "s:/usr/bin/libtool:${EPREFIX}/usr/bin/${CTARGET}-libtool:"`

And because nothing is setting it anymore, pkgcheck should actually be giving a misleading warning when drop the eclass even along the already removed is_cross:
```
  MissingInherits: version 4.2.1_p5666-r3: kernel-2: missing inherit usage: 'CTARGET', line 76
  MissingInherits: version 4.2.1_p5666-r3: toolchain: missing inherit usage: 'is_crosscompile', line 46
```

**Comment by ionenwks** [comment]
> Without that CTARGET is likely to give a blank value in bits like: `sed -i -e "s:/usr/bin/libtool:${EPREFIX}/usr/bin/${CTARGET}-libtool:"`

... that aside, looking at this line I randomly copied, where are even tuple-libtool at? ;p

**Comment by grobian** [comment]
not sure what you're asking for here, but "libtool" on darwin hosts is a compiler helper tool, not GNU libtool.  That's why it gets fully qualified.  E.g.:
```
% readlink $EPREFIX/usr/bin/libtool
arm64-apple-darwin22-libtool
```

**Comment by thesamesam** [comment]
Handling the eclass cleanup in https://github.com/gentoo/gentoo/pull/31362.

**Pull request closed without merging**
