### PR TITLE
net-libs/libwebsockets: bump to 1.7.6

### PR DESCRIPTION
**Pull request by mapx**
[http2 patch](https://github.com/warmcat/libwebsockets/commit/476329f3f8070c1f5e7df4549037c8041b8b8907) fixes [issue 473](https://github.com/warmcat/libwebsockets/issues/473)

It's strange `ebuild libwebsockets-1.7.4.ebuild digest` won't digest files other than ebuilds if it is executed in the repo directory. Could someone tell me why?

Update: To digest the new Manifest,
 - have tried: `=sys-apps/portage-2.2.26` and `=sys-apps/portage-2.2.27`
 - delete (or not delete) older ebuild files as well as `metadata.xml`
 - copy `net-libs/libwebsockets` to `/tmp/net-libs/libwebsockets` and do ebuild digest again. This time Manfiest includes all files.

Update2: The patch is removed.

### CODE REVIEW

**Comment by idella** [comment]
With that snippet of info we have no idea what is going wrong. Need far more info of the lead up steps

**Comment by idella** [comment]
attr(iuse): iuse unknown flags: [ server, client, http2 ]  suggests you don't have use flags in metadata.xml consistent with the ebuilds

**Comment by idella** [comment]
why are you not using repoman full ?

**Comment by mapx** [comment]
Sorry, I forgot this step before the second PR. What's more, repoman's output is confusing:
```
RepoMan scours the neighborhood...
RepoMan sez: "If everyone were like you, I'd be out of business!"
```
It looks it's telling a joke. Have I done something wrong this time? How could you know I didn't use repoman?

I read `man repoman` again.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
yes it's a tongue in cheek comment, a joke

**Comment by idella** [comment]
While this actually compiles and installs, there are a number of issues:

1. Any such patch ought be submitted upstream ofr consideration by them
2. We take note of their assessment of it accordingly.
3. Any such patch ought have its origin entered in / from line one.
4. Once approved, we either add the patch citing upstrem's endorsement, ot they would make a new release with the patch incorprated.
5. There is not matching bug in bugzilla. Therefore the designated maintainer,  Jaco Kroon, has been bypassed entirely.  As designated proxy maintainer, this requires his notification and endorsement. Alternatively, you could be given co-maintainership.

**Comment by mapx** [comment]
The issue and patch was discussed in https://github.com/warmcat/libwebsockets/issues/473
@lws-team could you help us bump the version? You are the upstream in qustion :)
@idella, should I remove http2 support iuse as well as the patch this time, and leave it to the next version?

**Comment by lws-team** [comment]
Yes @mapx approached us already and the patch came from and is pushed upstream.

We run a stable history branch for each release, in this case

https://github.com/warmcat/libwebsockets/commits/v1.7-stable

and tag off that at intervals for point releases... this patch is already on v1.7-stable.  So in terms of correctness and provenance, there's no problem with this patch from upstream POV.

If it'll help sort this out I can tag it out, but since this is the only new patch since the last tag a few days ago and no other distro has shipping ALPN-capable openssl that triggers the compiler warning, I would normally wait for more patches / something more scary before bothering the other distros with a new point release.

**Comment by mapx** [comment]
No patch now. Done is better than perfect.
HTTP2 IUSE could be enabled in the next version.

**Comment by monsieurp** [comment]
Could you please file a bug? Not sure the proxy maintainer of this package actually has a github account and knows the existence of this PR. Even if he did, you'd have to file a bug in the first place and THEN, file a PR. Thank you.

**Comment by mapx** [comment]
Found a existing bug https://bugs.gentoo.org/show_bug.cgi?id=578820 in UNCONFIRMED status and added a comment there.
Is it as good as filing a bug?

**Comment by monsieurp** [comment]
Perfect. Let's wait for the maintainer's response. Thanks.

**Comment by monsieurp** [comment]
We shall merge this PR after so long. Too bad the maintainer didn't respond and/or comment the bug report.

**Comment by mjeveritt** [comment]
@mapx would you mind acting as proxy maintainer for this? We can help you out in the gentoo IRC channels if you get stuck, but it would be good to have someone 'active' who is familiar on the team, if possible :)
@monsieurp : suggest appending mapx to metadata perhaps, what do you think?

**Comment by monsieurp** [comment]
If he wants to, he either should either file a bug or reopen the previous one and let us know he'd like to co-maintain the ebuild.

**Comment by mapx** [comment]
@mjeveritt  @monsieurp It's my pleasure :)
Since the previous bug was marked RESOLVED FIXED and I'm unable to edited its status, a new one was opened as
https://bugs.gentoo.org/show_bug.cgi?id=582024

Thanks :)

**Pull request closed without merging**
