### PR TITLE
net-p2p/syncthing: add 1.27.4

### PR DESCRIPTION
**Pull request by anthonyryan1**
Routine version bump. Move `S=` higher up to match `skel.ebuild` preferred order.

### CODE REVIEW

**Comment by stkw0** [comment]
I was about to create the same PR. Could you replace 1.27.3 with the new 1.27.4 and add the "Closes: https://bugs.gentoo.org/927343" to the commit??

**Comment by anthonyryan1** [comment]
Updated, cheers.

**Comment by stkw0** [comment]
Thanks!  I forgot, can you also append "[please reassign]" to the title? (`In order to force reassignment and/or bug reference scan, please append [please reassign] to the pull request title.`)

**Comment by juippis** [comment]
Looks like this was bumped.

**Pull request closed without merging**
