### PR TITLE
Mate: Mega bump to 1.20.x V2

### PR DESCRIPTION
**Pull request by Odelpasso**
Hello,

I take the risk to bump myself Mate 1.20.x to Gentoo, I try to tame the devil.
All this work was done by "Chris Henhawke" on the bug report concerning the bump request. I only made the push from my branch so big thanks to him :-)

Closes: https://bugs.gentoo.org/646896
Signed-off-by: Maxime Lombard <berillions@gmail.com>

### CODE REVIEW

**Comment by Odelpasso** [comment]
No news about this mega-bump ? :-)

**Comment by juippis** [comment]
@Odelpasso I don't know how strict it is, but your sign-off seems to be wrongly formatted. You forgot `< >` around your e-mail. You can automate it by adding the correct line to your make.conf, check man 5 make.conf and search for DCO_SIGNED_OFF_BY. 

@mudler could you take a look? Seems like the MATE project's leader is on devaway.

**Comment by Odelpasso** [comment]
No news since the last month ?

**Comment by a17r** [comment]
Thanks for your work, next time please do as @juippis advised and fix your sign-off string.

MATE 1.22 was bumped by zlogene so this PR seems to be obsolete.

**Pull request closed without merging**
