### PR TITLE
kde-plasma/kscreenlocker: Fix blocker on kdebase-pam:0 instead of 4

### PR DESCRIPTION
**Pull request by a17r**
See also: https://github.com/gentoo/kde/pull/585

Not fixing old versions, dropping instead: https://github.com/gentoo/gentoo/pull/797

@gentoo/kde

### CODE REVIEW

**Comment by kensington** [comment]
Is it worth it to revbump in this case? Risk of any breakage seems low.

**Comment by a17r** [comment]
Given the original problem was kdebase-pam claiming the same files and being able to remove them from under plasma-workspace on unmerge, I rather revbumped. But all the recent cases of kscreenlocker trouble were unrelated indeed.

**Comment by kensington** [comment]
Ah, I forgot about that.

**Comment by kensington** [comment]
Thanks, picked as 0213f9b60f85f85553b4f99f3000a90167e31d54...7c78300529249e425d20e3faac99b5c3e9a33f56.

I ended up making the changes inline to avoid a double-revbump (applied security patches in 386f4b18b5bcfa51bdb9d515b79d90812f3838ad and 0be8df1b52ad6ee0dbfe86ca22ec19fb47e88797).

**Comment by a17r** [comment]
Even better then ;)

**Pull request closed without merging**
