### PR TITLE
Add python-3.5 support to some of my dev-python/* packages

### PR DESCRIPTION
**Pull request by Coacher**
CC @gentoo/proxy-maint

### CODE REVIEW

**Comment by monsieurp** [comment]
I know you're very reliable @Coacher but how can I check they do work? Care to provide a build log?

**Comment by Coacher** [comment]
@monsieurp, sure. No problem, but only tomorrow. Build and test logs.
I've already rebuilt everything without Python-3.5 after testing.

**Comment by Coacher** [comment]
enzyme-0.4.1-r2: https://bpaste.net/show/8a6d460566f0
enzyme-9999: https://bpaste.net/show/aa50ef5a0afb
guessit-1.0.3-r1: https://bpaste.net/show/fe964184333b
guessit-2.0.5-r1: https://bpaste.net/show/98d1819fc296

**Comment by monsieurp** [comment]
:+1:

**Comment by Coacher** [comment]
Thank you, @monsieurp.

**Pull request closed without merging**
