### PR TITLE
net-libs/libaccounts-glib: add 1.27

### PR DESCRIPTION
**Pull request by parona-source**

### CODE REVIEW

**Comment by a17r** [comment]
Do tests pass for you?

> 8/8 accounts-glib-testsuite                   FAIL             2.54s   exit status 1

**Comment by parona-source** [comment]
They passed when I bumped it. Ill see if something changed or if they still pass.

**Comment by parona-source** [comment]
Could you share logs? They pass for me.

<details>

```
>>> Test phase: net-libs/libaccounts-glib-1.27
 * python3_11: running run_in_build_dir meson_src_test
meson test --print-errorlogs -C /var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_11 --num-processes 12
ninja: Entering directory `/var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_11'
ninja: no work to do.
1/8 xmllint-applications-Gallery.application  OK               0.48s
2/8 xmllint-applications-Mailer.application   OK               0.41s
3/8 xmllint-services-MyService.service        OK               0.35s
4/8 xmllint-services-MyService2.service       OK               0.33s
5/8 xmllint-services-OtherService.service     OK               0.28s
6/8 xmllint-providers-MyProvider.provider     OK               0.23s
7/8 xmllint-service-types-e-mail.service-type OK               0.19s
8/8 accounts-glib-testsuite                   OK              16.52s

Ok:                 8   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_11/meson-logs/testlog.txt
 * python3_12: running run_in_build_dir meson_src_test
meson test --print-errorlogs -C /var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_12 --num-processes 12
ninja: Entering directory `/var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_12'
ninja: no work to do.
1/8 xmllint-applications-Gallery.application  OK               0.17s
2/8 xmllint-applications-Mailer.application   OK               0.17s
3/8 xmllint-services-MyService.service        OK               0.15s
4/8 xmllint-services-MyService2.service       OK               0.11s
5/8 xmllint-services-OtherService.service     OK               0.10s
6/8 xmllint-providers-MyProvider.provider     OK               0.08s
7/8 xmllint-service-types-e-mail.service-type OK               0.05s
8/8 accounts-glib-testsuite                   OK              16.02s

Ok:                 8   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/net-libs/libaccounts-glib-1.27/work/libaccounts-glib-VERSION_1.27-python3_12/meson-logs/testlog.txt
```

</details>

**Comment by a17r** [comment]
My fault - missing dependency. Good to go!

**Review by a17r — APPROVED** [review]

**Comment by a17r** [comment]
(albeit I dislike the `sed`ing, should be upstreamed in some way)

**Comment by parona-source** [comment]
Upstreaming might be challenging depending on if its possible to get a valid TMPDIR with meson. So it may force bigger modification to how the argument is passed.

**Pull request closed without merging**
