### PR TITLE
app-admin/conky: add 1.19.2

### PR DESCRIPTION
**Pull request by jubalh**

### CODE REVIEW

**Comment by jubalh** [comment]
@billie80 short reminder about https://github.com/gentoo/gentoo/pull/29770#issuecomment-1445155601 ;)

**Comment by billie80** [comment]
I will bump when I find the time. Actually I see no use in such pull requests if the ebuild is simply copied. Without looking I guess this is the case here. If not please explain the changes and why they are necessary.
If it is just a copy a version bump request using bugzilla would be appropriate. Even then normally I regularly check for new versions and just don't have the time to bump immediately. So if the new version is not there after let's say a few weeks a bump request makes sense. Else I don't see the point. In this case it would have made sense to remind me about 1.19.1 which was released 10th of April. I am aware however and just did not find the time.

**Comment by jubalh** [comment]
>  If not please explain the changes and why they are necessary.

After my last PR I chose to ignore conky and not update it via a PR. The result was that 1.19.1 that came out quite a while ago was not added to the Gentoo tree by you.

So when I got notified about the 1.19.2 upstream update I decided to do it again.

> Else I don't see the point.

The point is to have the bugfix release in the Gentoo tree.
As it seemed that you don't have time to do this (as I saw with 1.19.1) I decided to help here.

I'm not a Gentoo dev so I don't know the workflow from the side of the person with commit access. But I guess that it's one or two lines to merge such a PR.

So I think such tested PRs should help the developer quite a bit.

**Comment by billie80** [comment]
Well this is appreciated, but why not mention this in the pull request as a comment?

"Hello there is a new version in case you have missed it. I checked this and that. It looks like no changes to the ebuild are required and it can be bumped as is."

This would have been really helpful, else I have to assume it did not happen. So I have to ask or check it myself.

**Comment by jubalh** [comment]
I didn't mention this because I thought that's the default ;)

**Comment by billie80** [comment]
Even if it is I would say "communication is key" and "verbosity is key". We don't know each but when a certain level of trust has been established we can reduce both. 😀

**Pull request closed without merging**
