### PR TITLE
app-backup/kfoldersync: version bump

### PR DESCRIPTION
**Pull request by Vindex17**

### CODE REVIEW

**Comment by johu** [comment]
Thanks for the PR. One question: As you are the upstream maintainer, which version are you targeting for stablization as you always remove latest version?

**Comment by Vindex17** [comment]
I'm actually using a rolling release approach, that's why I've never stabilized

**Comment by johu** [comment]
Gentoo has the rolling release model as well, but we have a stable profile and a testing profile. So stable user can't kfoldersync without accepting testing keywords.

**Comment by Vindex17** [comment]
Well, this version should be bug-free and the last in the 3.4.x series, so it could be a good candidate

**Comment by johu** [comment]
Thanks for the info.

**Pull request closed without merging**
