### PR TITLE
sci-libs/cgnslib-3.4.0: fix doc installation

### PR DESCRIPTION
**Pull request by waebbl**
First commit solves an issue with `USE=doc`, second commit bumps to EAPI 7 and switches to cmake.eclass.

Closes: https://bugs.gentoo.org/760342
Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Bernd Waibel <waebbl@gmail.com>

### CODE REVIEW

**Comment by waebbl** [comment]
Tried to backport the changes to 3.3.0, but it fails building the first fortran file with gcc:10. Using gcc:9.3.0 or gcc:8.4.0 fixes that, but leads to bug https://bugs.gentoo.org/662210, so I omitted this.

**Comment by waebbl** [comment]
Forgot to rebase before pushing, hence the force-push

**Comment by thesamesam** [comment]
Hmm, I had:
```
 * One or more CMake variables were not used by the project:
 *   HDF5_NEED_SZIP
 *   HDF5_NEED_ZLIB
```

**Comment by thesamesam** [comment]
Thanks!

**Comment by waebbl** [comment]
@thesamesam I can check again using a more in-depth variation on USE flags. I believe, I haven't tested all combinations.

**Comment by waebbl** [comment]
@thesamesam https://github.com/gentoo/gentoo/pull/18838 solves the cmake warnings

**Pull request closed without merging**
