### PR TITLE
base-system@g.o: drop versionator in favor of eapi7-ver

### PR DESCRIPTION
**Pull request by hanetzer**
Some of these entirely drop versionator, as it is not used at all in the ebuild that
I could see. Some of the pkg_postinst logic I need a double check on to make
sure my logic is right, but I think I got it.

### CODE REVIEW

**Comment by Whissi** [comment]
Again, this is not how anything in Gentoo works, especially not base-system project: Things will get updated (=migrated to eapi7-ver) over time. There is zero need to do it outside a regular bump. And especially for base-system packages... **we don't touch previous stable packages without a need**.
I am getting a little bit angry that you are ignoring this. So I really have to say that I hope to some point that you will learn it once due to a big mess up caused by your changes which didn't go through the ATs test circle...

Have fun finding another member of the project like you did before.

**Comment by Zlogene** [comment]
I disregard these changes personally, there's no rush to replace versionator vith eapi7-ver

**Comment by hanetzer** [comment]
@Whissi 'have fun finding another member of the project like you did before' is
not what I'd call an apropriate response here. The rest of your post was enough,
and I'll agree, this change was more than the whole git-2->git-r3 bit. I'd prefer
you keep your reviews and comments professional on this matter.

**Comment by Whissi** [comment]
> Have fun finding another member of the project like you did before.

...and for me it was somehow disrespectful the way you asked for another review from someone else in the past when you disliked my response. But this shouldn't sound like "You did this to me, so I did that to you", so please take my excuse for that.

Just for the records: I appreciate most contributions, including contributions from you. However, you have to accept some rules. If you don't like our rules, become a developer, join the project and convince us to change something together. Take that challenge!

**Comment by hanetzer** [comment]
Ending this here, but I did not ask for another review. I asked for *a* review, as
you were not comfortable with the way github forced an all or nothing review. I
am more than happy to take criticism from you, another developer, or even a
lay user like myself as far as improvements or a plain 'this is unacceptable',
such as when you said so regarding my sys-libs/db port.

**Pull request closed without merging**
