### PR TITLE
virtual/bitcoin-leveldb: Add =dev-libs/leveldb-1.18-r2 (only changed depends)

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by a17r** [comment]
That looks really strange. What's the reason for limiting leveldb versions like that?

**Comment by SoapGentoo** [comment]
Agree with @a17r, please describe rationale

**Comment by luke-jr** [comment]
LevelDB is part of Bitcoin's consensus logic. The nature of consensus code is such that it *must* guarantee bug-for-bug compatibility, *especially* for data-loss bugs. It would be unreasonable to expect upstream LevelDB to make such a guarantee (and indeed, they do not), so instead what we typically do for Bitcoin is bundle the library in the code, and review new releases to ensure they do not fix any bugs that would break this compatibility. Similarly, it would be unreasonable for the Gentoo packager of LevelDB to make this guarantee, as other software using LevelDB would expect to have such bugs fixed - indeed, if such a bug were critical enough, it might even get backported in a `-rN` package revision.

Ordinarily, [we advise distros to not package Bitcoin at all](http://luke.dashjr.org/tmp/code/20130723-linux-distribution-packaging-and-bitcoin.md.asc), since the nature of consensus code is unfamiliar to most packagers, and distros are generally not capable of making this bug-for-bug compatibility guarantee. However, Gentoo is an exception to the rule here, since we can use a virtual to ensure only known-compatible LevelDBs are used in combination with Bitcoin.

**Comment by a17r** [comment]
I'm not sold, but committed for now (and fixed length of commit message according to our guidelines).

**Pull request closed without merging**
