### PR TITLE
www-client/firefox: Add ebuilds that enable wasm gc by default

### PR DESCRIPTION
**Pull request by viviicat**
Firefox as of 120 has enabled wasm gc by default. My guess is that the `--disable-wasm-gc` flag was kept in the ebuild due to this not being known by the packagers - but if this isn't true please feel free to correct me. I also needed to remove the `--disable-wasm-function-reference` to build with this flag.

It doesn't feel like it would be something we need a USE flag for at the moment, but if that's desired let me know.

I figure we need revision ebuilds (r1) as the functionality is changing - let me know if I should modify the existing ebuilds instead, I'm not very well-versed on this.

Tests: I built 122.0-r1 and it is working as expected and can run GC wasm (e.g. the wasm at the bottom of the page https://spritely.institute/news/scheme-wireworld-in-browser.html )

*This is my first time making a gentoo contribution so apologies if I did something incorrectly*

Closes: https://bugs.gentoo.org/923634

### CODE REVIEW

**Comment by viviicat** [comment]
Closes: https://bugs.gentoo.org/923634

(unsure if the bot understands comments)

**Comment by parona-source** [comment]
It parses commits for that information. It will then show up in the bug when commit is merged as well.

**Comment by viviicat** [comment]
> It parses commits for that information. It will then show up in the bug when commit is merged as well.

thanks, working on updating/force-pushing a new commit

**Comment by parona-source** [comment]
Not a firefox maintainer but I don't think touching 121.0.1 is necessary. Maybe the ESR should have the same treatment as well, but I'd wait on @juippis or anyone else in @gentoo/mozilla to weigh in on the change in general.

**Comment by viviicat** [comment]
And now I am also verified on GH ^_^

**Comment by viviicat** [comment]
Oops I guess I need to add "Closes: xxx" to the commit, sorry :crying_cat_face:

**Comment by viviicat** [comment]
I appreciate the guidance, thanks so much!

**Comment by parona-source** [comment]
And add the closes should be added like

```
commit title

Closes: XXXX
Some-other-tag: XXXX
Signed-off-by: me
```

**Comment by viviicat** [comment]
*gives the cow some delicious grass to appease it*

**Comment by parona-source** [comment]
Add the whole link there. 

Closes: https://bugs.gentoo.org/923634

Sorry for being misleading with the XXXXX.

**Comment by viviicat** [comment]
> In the future with working with ebuilds you should get accustomed to using pkgdev and pkgcheck.

I did use those, but the issue is that I didn't make the bug until afterwards. I suspect it would have been a *lot* easier that way :) Thanks again

**Comment by juippis** [comment]
I'm pretty sure we haven't enabled anything with "wasm" in it due to webassembly not being packaged in Gentoo. Did you try to build this? It may be unrelated to wasm, or not need it.

And yeah, 121 is currently kept just in case someone can't update to 122 - so no reason to edit that :)

**Comment by juippis** [comment]
I'm testing this, but I will say I'm not too comfortable revbumping for this fix. Since you're the first one I hear having this issue, it may not be so wide-spread. It's true this is a change that would require revbumping, but Firefox is amongst the packages where we try to avoid it. The update will naturally be activated on any version bump, like if/when 122.0.1 comes out.

**Comment by viviicat** [comment]
> I'm testing this, but I will say I'm not too comfortable revbumping for this fix. Since you're the first one I hear having this issue, it may not be so wide-spread. It's true this is a change that would require revbumping, but Firefox is amongst the packages where we try to avoid it. The update will naturally be activated on any version bump, like if/when 122.0.1 comes out.

Makes sense - I'm fine with it going in with the next release ^_^ I have my own build so I'm happy to use that until then. Thank you!

**Review by juippis — APPROVED** [review]
Thanks!

**Pull request closed without merging**
