### PR TITLE
dev-lang/zig: always install self-hosted compiler, workaround upstream bugs

### PR DESCRIPTION
**Pull request by BratishkaErik**
Closes: https://bugs.gentoo.org/867592
Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Current upstream bugs (will work on this):
* "-Denable-stage1" option doesn't work for self-hosted compiler
* CMake builds and installs self-hosted compiler in same command

**Comment by correabuscar** [comment]
This works for me, thank you very much for your work!

```json
$ zig env
{
 "zig_exe": "/usr/bin/zig",
 "lib_dir": "/usr/lib/zig",
 "std_dir": "/usr/lib/zig/std",
 "global_cache_dir": "/home/user/.cache/zig",
 "version": "0.10.0"
}

$ zig-stage1 env
{
 "zig_exe": "/usr/bin/zig-stage1",
 "lib_dir": "/usr/lib/zig",
 "std_dir": "/usr/lib/zig/std",
 "global_cache_dir": "/home/user/.cache/zig",
 "version": "0.10.0-dev.3844+f7784a081"
}
```

**Comment by thesamesam** [comment]
Is it ready or not? If not, mark as a draft 😉

**Comment by BratishkaErik** [comment]
> Is it ready or not? If not, mark as a draft 😉 

Now it is ready.

**Comment by BratishkaErik** [comment]
> > Is it ready or not? If not, mark as a draft wink
> 
> Now it is ready.

I'll push some changes to this branch, but they are not important and you can merge this PR without these, it's ready.

**Pull request closed without merging**
