### PR TITLE
app-containers/podman: add 4.7.2, drop 4.7.{0,1}, update live

### PR DESCRIPTION
**Pull request by rahilarious**
4.7.2 fixes security issue
https://github.com/moby/moby/security/advisories/GHSA-jq35-85cj-fj4p

Just to be safe removing 4.7.0 and 4.7.1 as well.

### CODE REVIEW

**Comment by rahilarious** [comment]
@zmedico Pinging cause this one is security fix.

**Comment by zmedico** [comment]
Thanks!

**Comment by rahilarious** [comment]
@zmedico thoughts on stabilizing 4.7.2? I'm aware of 30-day policy but with podman getting updated quite frequently it's hard

**Comment by thesamesam** [comment]
@rahilarious In future, please cleanup old versions in a separate commit, but also file security bugs in Gentoo if you know something has a vulnerability. Thanks!

**Comment by rahilarious** [comment]
> @rahilarious In future, please cleanup old versions in a separate commit, but also file security bugs in Gentoo if you know something has a vulnerability. Thanks!

noted.

**Pull request closed without merging**
