### PR TITLE
New package: media-libs/pyliblo

### PR DESCRIPTION
**Pull request by lilrc**
Needed for gtklick [1], which I need. See also Gentoo bug 291611 [2].

[1] http://das.nasophon.de/gtklick/
[2] https://bugs.gentoo.org/show_bug.cgi?id=291611

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Ditto #1548. Please provide a link to a build log. Thanks!

**Comment by lilrc** [comment]
Sure! Here is a link:
https://karll.portknox.net/index.php/s/U4AELjjyaTrsk9R

**Comment by monsieurp** [comment]
Ok thanks. Will add both packages shortly.

**Comment by lilrc** [comment]
Thank you!

**Pull request closed without merging**
