### PR TITLE
app-cdr/kcdemu: add SLOT="0"

### PR DESCRIPTION
**Pull request by yegortimoshenko**

### CODE REVIEW

**Comment by a17r** [comment]
That would require a slotmove since it is now slot 5. Why do you want to do this?

**Comment by yegortimoshenko** [comment]
I was just worried because I didn't see any SLOT specified in the ebuild.

**Comment by a17r** [comment]
SLOT in this case is defined by kde5.eclass.

**Comment by yegortimoshenko** [comment]
I see. Thanks!

**Pull request closed without merging**
