### PR TITLE
app-emulation/wine-vanilla: fix a crash in install phase

### PR DESCRIPTION
**Pull request by shimataro**
Hello!

`app-emulation/wine-vanilla` crashes in install phase with following message:
```
/var/tmp/portage/app-emulation/wine-vanilla-2.0.2/temp/environment: line 3644: no match: /var/tmp/portage/app-emulation/wine-vanilla-2.0.2/image/usr/share/wine-vanilla-2.0.2/man/pl*
```

this pull-request will fix it.

### CODE REVIEW

**Comment by NP-Hardass** [comment]
@a17r This really shouldn't have been merged for just wine-vanilla.  Should have been applied to all of wine-* and a patch prepared for the overlay...

Did you clear this with Austin, or take it upon yourself to merge it?

**Comment by NP-Hardass** [comment]
@shimataro Thanks for the PR.

**Comment by aikipooh** [comment]
Um, I'm experiencing this bug supposedly.
/big/volatile/tmp/portage/app-emulation/wine-vanilla-2.0.3/temp/environment: line 3608: no match: /big/volatile/tmp/portage/app-emulation/wine-vanilla-2.0.3/image/usr/share/wine-vanilla-2.0.3/man/pl*

But I see rm -rf in there. What's wrong then?

**Comment by Chiitoo** [comment]
aikipooh,

See: https://bugs.gentoo.org/617864

**Comment by aikipooh** [comment]
@Chiitoom, oh, silly me. I see, globbing, complicated:) I'll make it install locally for this time and hopefully forget until next update.

**Pull request closed without merging**
