### PR TITLE
net-print/epson-inkjet-printer-escpr: add 1.2.3 (new slot)

### PR DESCRIPTION
**Pull request by beatussum**

### CODE REVIEW

**Comment by mpagano** [comment]
A later version, 1.8.0, is in the main repository

**Comment by beatussum** [comment]
> A later version, 1.8.0, is in the main repository

@mpagano I think you are talking about _the ESC/P-R Driver (generic driver)_. However, the ebuild provided by this pull request does not refer to it but refers to _the ESC/P-R Driver **2** (generic driver)_. Some PPDs are not provided by the first one but by the second one (for example, the ppd used for XP-6100 Series is provided by _the ESC/P-R Driver 2 (generic driver)_).

However, you are right: this pull request seems to be outdated as the latest version of _the ESC/P-R Driver 2 (generic driver)_ seems to be 1.2.3 and no more 1.1.62.

**Comment by mpagano** [comment]
Update to the latest, and I will merge this.  But I will need to depend on others to test since I don't have the hardware to do so.

**Comment by beatussum** [comment]
@mpagano Normally, it's done.

**Comment by mpagano** [comment]
Was the patch in files/ uploaded from Windows ?

**Comment by mpagano** [comment]
Patch for 1.2.3 does not apply for me. Can you check that ?

**Review by mpagano — CHANGES_REQUESTED** [review]
Ok, let's get this in.
Looks like the warnings patch is not needed anymore in 1.2.9.
Bump the version, remove ppc64 unless you know it's valid, and I'll pull this in right away.  

FYI to save you some time: (1.2.9 tarball) 
https://download3.ebz.epson.net/dsc/f/03/00/15/33/96/607198a4f064daa9e7931913eaf27f3a58125f2b/${MY_P}-1.tar.gz

**Comment by beatussum** [comment]
> Ok, let's get this in. Looks like the warnings patch is not needed anymore in 1.2.9. Bump the version, remove ppc64 unless you know it's valid, and I'll pull this in right away.
> 
> FYI to save you some time: (1.2.9 tarball) [https://download3.ebz.epson.net/dsc/f/03/00/15/33/96/607198a4f064daa9e7931913eaf27f3a58125f2b/${MY_P}-1.tar.gz](https://download3.ebz.epson.net/dsc/f/03/00/15/33/96/607198a4f064daa9e7931913eaf27f3a58125f2b/$%7BMY_P%7D-1.tar.gz)

Okay, normally it's done : I have dropped `ppc64` and removed the patch file.

Sorry for the delay but I'm a student and the last months have been very busy.

**Pull request closed without merging**
