### PR TITLE
net-libs/ripe-atlas-sagan: Version bump to 1.1.10

### PR DESCRIPTION
**Pull request by danielquinn**
I think I did this right, but the `Manifest` file doesn't list an `EBUILD` entry anymore and I don't know how to get one in there.  I just ran `ebuild ripe-atlas-sagan-1.1.10.ebuild manifest` and it this is what came out.

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by kensington** [comment]
Thanks, picked as ef6a6d05fa9d20f5f4cebb5a67ebbc917a080377 with updated copyright year squashed in.

It's expected behaviour that there's no ``EBUILD`` entry in ``Manifest`` in this repository as thin manifests are enabled - so git's own mechanisms are used for tracking these files.

**Comment by kensington** [comment]
I suggest a few changes/enhancements that could be incorporated into a future bump:

* EAPI 6 could be used instead (I don't think anything else in the ebuild needs porting to make use of it)
* ``${PVR}`` includes Gentoo-specific revision numbers (if there are any) which may cause breakage if introduced. ``${PV}`` contains just the version number.
* There's a couple of docs that are not installed - this could be achieved with ``DOCS=( CHANGES.rst README.rst )``.
* Extra quoting of ``${RDEPEND}`` inside ``${DEPEND}`` is not required.

**Comment by danielquinn** [comment]
All good suggestions, thank you.  I messed up the other two companion packages with a conflict as I failed to pull the upstream, so I'll make these changes on them as well, and when Sagan is bumped (should happen in a few weeks) I'll make these changes there as well.

**Pull request closed without merging**
