### PR TITLE
Various py37/py38 bumps

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by hartwork** [comment]
Please drop elogv here: I was already working on https://bugs.gentoo.org/701584 when I saw this and it needs 
```
RDEPEND="sys-apps/portage[${PYTHON_USEDEP}]"
DEPEND="${RDEPEND}"
```
more to work, as well. So that's fixed in aa8d33ba7b5b83a6dd5cdb2ea0bec36b0c2c108a already now.

**Comment by hydrapolic** [comment]
Ack for syslog-ng, thanks.

**Comment by zmedico** [comment]
Merged dev-python/ssl-fetch affeea2a023a467ab8355ed32b4eac60cf096b64 and app-portage/mirrorselect 83cba265c1df1a4eded315d221414e530e70136b.

**Comment by Whissi** [comment]
NACK at least for sys-apps/file: Like said today in IRC, I noticed that package will install 3.7/3.8 in /usr/lib but 2.7 and 3.6 in /usr/lib64 at least on my system which is weird and needs investigation.

**Comment by floppym** [comment]
> NACK at least for sys-apps/file: Like said today in IRC, I noticed that package will install 3.7/3.8 in /usr/lib but 2.7 and 3.6 in /usr/lib64 at least on my system which is weird and needs investigation.

This is completely normal behavior due to changes that were introduced with dev-lang/python-3.7.

**Comment by Polynomial-C** [comment]
ACK for my packages

**Comment by Whissi** [comment]
ACK for base-system packages.

**Comment by mattst88** [comment]
Ack for x11.

**Comment by lovesegfault** [comment]
ACK

**Pull request closed without merging**
