### PR TITLE
[bug 881043] app-crypt/acme, app-crypt/certbot and its modules: fix DistutilsNonPEP517Build & PythonGHDistfileSuffix

### PR DESCRIPTION
**Pull request by thican**
Bug: https://bugs.gentoo.org/881043

Signed-off-by: Thibaud CANALE <thican@thican.net>

### CODE REVIEW

**Comment by MatthewGentoo** [comment]
Thanks for doing this :)

> We could then use some cohesion between packages to store and to handle one and single archive, saving storage and download.

There are plenty of other certbot modules that we don't package too - maybe it's worth creating an eclass and packaging the rest of them.

**Comment by thican** [comment]
Hi @MatthewGentoo, sorry for my late answer,

> Thanks for doing this :)

You’re welcome, thanks to you for your feedback,

> > We could then use some cohesion between packages to store and to handle one and single archive, saving storage and download.
> 
> There are plenty of other certbot modules that we don't package too - maybe it's worth creating an eclass and packaging the rest of them.

I totally agree, however I don’t have (yet?) the knowledge around eclass.
I think the near [Certbot 2.0](https://github.com/certbot/certbot/releases/tag/v2.0.0) version could be a good opportunity to bring this feature to life.

Anyway, meanwhile I just rebased and removed 1.30.0 version, just I would like to know when this PR could be integrated; should I ping once more the other maintainers?

**Comment by thican** [comment]
Hello again, sorry it took so long for update and for fixing issues raised by the CI; about this matter, I dropped the commit updating other Python modules to Python 3.11, and therefore the Certbot’s modules depending on them.

**Comment by prometheanfire** [comment]
good work in here, the one question I have is why the change to use `tools/requirements.txt`  that is more for package pinning, not for packagers.  https://github.com/certbot/certbot/blob/4ab4c9b65d93509bb0337321dea9945c6e7b9102/tools/requirements.txt#L4-L7

If the versions change back to what's defined in setup.py for each package I think I can merge this.

**Comment by thesamesam** [comment]
This touches 2.3.0 in-place instead of revbumping it like the others?

**Comment by thican** [comment]
> good work in here, the one question I have is why the change to use `tools/requirements.txt` that is more for package pinning, not for packagers. https://github.com/certbot/certbot/blob/4ab4c9b65d93509bb0337321dea9945c6e7b9102/tools/requirements.txt#L4-L7
> 
> If the versions change back to what's defined in setup.py for each package I think I can merge this.

Oh indeed, my bad, I never noticed this part. Let me fix it, sorry for the issue.

> This touches 2.3.0 in-place instead of revbumping it like the others?

You mean my MR doesn’t provide a "-r1" for 2.3.0? There were no 2.3.0 bump yet. Or maybe I didn’t understand.

**Comment by thican** [comment]
Here we go, I finally reverted the changes where I was basing the versions of dependencies on "tools/requirements.txt", sorry for that.
I also pull the version 2.1.1, even the 2.2 branch is already stable in Gentoo’s tree, just in case of some people wants it.
and I updated some tests dependencies (pytest-tox also).

I think you can review it. Thanks for your feedback.

**Pull request closed without merging**
