### PR TITLE
net-im/telegram-desktop-bin: Version bump to 1.2.6 + Cleanup

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by henning-schild** [comment]
@NP-Hardass @gavv

**Comment by SoapGentoo** [comment]
@gavv can we maybe add @henning-schild as second proxy-maintainer, so that we can get this into the tree if one of you is absent?

**Comment by gavv** [comment]
Tested, works for me.

**Comment by gavv** [comment]
@SoapGentoo 

> @gavv can we maybe add @henning-schild as second proxy-maintainer, so that we can get this into the tree if one of you is absent?

I'm all for it.

**Comment by henning-schild** [comment]
@SoapGentoo 

sure, add me as proxy-maintainer

**Comment by SoapGentoo** [comment]
@henning-schild add an additional commit, adding yourself to `metadata.xml`

**Comment by henning-schild** [comment]
@SoapGentoo that already happened in
https://github.com/gentoo/gentoo/commit/411fb47506ebcdce4c73e5f9c365e1640c4567c7

Should that entry be changed somehow or did you overlook it?

**Comment by SoapGentoo** [comment]
@henning-schild sorry, missed that, everything is perfect :+1:

**Comment by monsieurp** [comment]
is it ready for prime-time?

**Comment by henning-schild** [comment]
@monsieurp from my side, yes

@gavv said that it works for him and @SoapGentoo wanted me as proxy-maintainer, so he probably did not find issues

If you are still not sure let us know who should give the confirmation.

**Comment by NP-Hardass** [comment]
I'd say if either proxied user, through me (@henning-schild ) or @gentoo/proxy-maint (@gavv) signs off, then either committing party (proxy-maint or me) can merge it.

**Pull request closed without merging**
