### PR TITLE
icinga - add icingadb + icingadb-web

### PR DESCRIPTION
**Pull request by hydrapolic**
https://icinga.com/blog/2022/06/30/finally-accomplished-icinga-db-released/

Tested on my sample instance running on amd64.

@prometheanfire if you don't want to maintain this I can add myself as maintainer.

### CODE REVIEW

**Comment by prometheanfire** [comment]
ya, go ahead and add yourself as maintainer, thanks

**Comment by hydrapolic** [comment]
> 

Do you want to be listed as co-maint?

**Comment by prometheanfire** [comment]
Ya, I can be.

**Comment by hydrapolic** [comment]
> Ya, I can be.

Good, pushed an update.

**Comment by hydrapolic** [comment]
Thanks @prometheanfire

**Pull request closed without merging**
