### PR TITLE
dev-java/commons-net: EAPI 7, update Java

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.17, Repoman-3.0.2
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
@vaukai thanks! `commons-net-3.6-r1` can be requested for stabilization, or we can wait a week or so and request `commons-net-3.8` stabilization and then cleanup the old.

**Comment by vaukai** [comment]
> @vaukai thanks! `commons-net-3.6-r1` can be requested for stabilization, or we can wait a week or so and request `commons-net-3.8` stabilization and then cleanup the old.

Yep, better wait and then directly stabilize `commons-net-3.8`
BTW: These are for cleanup after stabilization https://bugs.gentoo.org/buglist.cgi?quicksearch=dev-java%2Fcommons-net

**Comment by fordfrog** [comment]
https://bugs.gentoo.org/783024 should be resolved already as i removed `3.6` and left only your `3.6-r1`.

**Comment by vaukai** [comment]
> https://bugs.gentoo.org/783024 should be resolved already [...]
RESOLVED FIXED :-)

**Pull request closed without merging**
