### PR TITLE
sys-cluster/pacemaker: python compats, disable static

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-2.3.77, Repoman-2.3.17
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by gentoo-bot2** [comment]
## Pull Request assignment

*Submitter*: @Alessandro-Barbieri
*Areas affected*: ebuilds
*Packages affected*: sys-cluster/pacemaker

**sys-cluster/pacemaker**: @gentoo/cluster

## Linked bugs

No bugs to link found. If your pull request references any of the Gentoo bug reports, please add appropriate [GLEP 66](https://www.gentoo.org/glep/glep-0066.html#commit-messages) tags to the commit message and request reassignment.

**If you do not receive any reply to this pull request, please open or link a bug to attract the attention of maintainers.**

---
In order to force reassignment and/or bug reference scan, please append `[please reassign]` to the pull request title.

*Docs*: [Code of Conduct](https://wiki.gentoo.org/wiki/Project:Council/Code_of_conduct) ● [Copyright policy](https://www.gentoo.org/glep/glep-0076.html) ([expl.](https://dev.gentoo.org/~mgorny/articles/new-gentoo-copyright-policy-explained.html)) ● [Devmanual](https://devmanual.gentoo.org/) ● [GitHub PRs](https://wiki.gentoo.org/wiki/Project:GitHub/Pull_requests) ● [Proxy-maint guide](https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide)

**Comment by ultrabug** [comment]
@Alessandro-Barbieri thanks a lot for yet another contribution!

- did you test this with pypy and pypy3 for real?
- can you share your rationale for removing static-libs USE flag?

Thanks again

**Comment by Alessandro-Barbieri** [comment]
The context about static-libs is here
https://flameeyes.blog/2011/08/29/useless-flag-static-libs/
https://archives.gentoo.org/gentoo-dev/message/2dada80c2b9c85b0e83e6328428bf8ab

With pypy and pypy3 builds fine. I also tried opening a python console and it loads the modules. What could I test more?

**Comment by ultrabug** [comment]
> The context about static-libs is here

My point is not arguing about static-libs, I hate them as much as they do. But since we're talking about context here I think it is important that your commit message links at least the archive URL and stipulate that you're aligning with this point of view unless a strong requirement is raised by users.

> What could I test more?

I don't know. I've not used pacemaker for more than 8 years now.. I just wonder about the point of having pypy + pacemaker tbh. I tend to not add stuff "because I can".

**Comment by Alessandro-Barbieri** [comment]
I removed pypy* since I don't know how to test it better

**Comment by ultrabug** [comment]
Thank you!

**Pull request closed without merging**
