### PR TITLE
games-fps/serioussam: update LICENSE, SRC_URI

### PR DESCRIPTION
**Pull request by tx00100xt**
Fix broken texture effects. Update license.

Texture effects were broken when ported to Linux in 2016. https://github.com/icculus/Serious-Engine/commit/24cb244d4399845aa22cb4d8bf1e25760ae66a11
Version tagged 1.10.6d includes a fix for texture effects.
**Before fix:**
before-fix
**After fix:**
after-fix
When building for Linux, libvorbis source codes and headers are not used. 
The game engine uses system headers when building.
After commit: https://github.com/tx00100xt/SeriousSamClassic-VK/commit/432b8fabad98b1ce82d17b40ca31a40458979db1
zlib headers are also not used when building for Linux.
When built, the game engine uses the zlib library headers installed on the system.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution.

This requires a (re)version bump. I wonder if the packages version should be 1.10.6d (instead of 1.10.6).

**Comment by tx00100xt** [comment]
@Flowdalic
There are not many ebuilds containing letters in the version number, but they exist. Eg:
- app-shells/bash/bash-2.05b_p13.ebuild
- sci-biology/glimmer/glimmer-3.02b.ebuild
- net-misc/iperf/iperf-2.0.14a.ebuild

Therefore, probably the ebuild name serioussam-1.10.6d.ebuild is acceptable.
It is also possible to name the ebuild serioussam-1.10.6-r1.ebuild
Please tell me what’s best and I’ll update the pull request.

**Comment by Flowdalic** [comment]
serioussam-1.10.6d.ebuild please (IIRC this is valid according to PMS)

**Comment by tx00100xt** [comment]
> serioussam-1.10.6d.ebuild please (IIRC this is valid according to PMS)

Thank you. I will update the pull request with this ebuild name.

**Pull request closed without merging**
