### PR TITLE
sci-geosciences/qgis: version 3.8.3 and 3.10.0

### PR DESCRIPTION
**Pull request by fedeliallalinea**
Bug: https://bugs.gentoo.org/672952
Signed-off-by: Marco Genasci <fedeliallalinea@gmail.com>
Package-Manager: Portage-2.3.66, Repoman-2.3.11

### CODE REVIEW

**Comment by fedeliallalinea** [comment]
> Some changes were made to `9999` ebuild and meanwhile `3.8.3` was released. Your branch needs to be rebased anyway. Can you update your work with these recent fixes included?

In the next days I update branch with your changes and 3.10 version

**Comment by a17r** [comment]
I'm sorry for letting you wait that long. A planned test emerge yesterday completely bogged down the system so that will have to be investigated (maybe just resources dried up on that end).

**Comment by a17r** [comment]
Thanks for your work! 3.10.0 is in tree now. I did not do 3.8.x, as I lack time to test both versions, so I kept your PR open. But keep in mind that mostly everyone with ~arch is immediately going to 3.10.0 anyway.

**Comment by fedeliallalinea** [comment]
No problem for delay.
Also for 3.8.x version isn't a problem I currently use 3.10.0 now without any problem, then you can close bug for me.

**Pull request closed without merging**
