### PR TITLE
x11-wm/twm: remove empty IUSE

### PR DESCRIPTION
**Pull request by fkobi**
---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by jkroonza** [comment]
ACK, happy with evilwm side thanks.  You may also just outright drop 1.3.1 I reckon.

**Review by jkroonza — APPROVED** [review]
I'd have swapped the remove and remove empty IUSE, but the net result are the same, and in your ordering if someone does revert the remove at least the IUSE will be good for the reverted commit, so from my side I'm happy.

**Review by a17r — COMMENTED** [review]
I've picked evilvm cleanup, but twm tequires ACK by x11 proj and I can not tell if they fancy it.

**Comment by mattst88** [comment]
Feel free.

**Pull request closed without merging**
