### PR TITLE
app-admin/filebeat: revert stable version drop

### PR DESCRIPTION
**Pull request by hydrapolic**
Accidentally dropped the stable version too.

This reverts commit 75f6acc429f35dfd5f9bc60711a399020ee0fea1.

### CODE REVIEW

**Comment by juippis** [comment]
Remember sign-off! :)

**Comment by hydrapolic** [comment]
Yeah, I forgot, thanks @juippis :)

**Comment by hydrapolic** [comment]
Sign-off added.

**Comment by hydrapolic** [comment]
Thanks @Whissi

**Pull request closed without merging**
