### PR TITLE
dev-libs/rocr-runtime: provide xxd in-build and remove vim-core dep

### PR DESCRIPTION
**Pull request by Peter-Levine**
xxd is hex-dump utility built from a single [C source file](https://github.com/vim/vim/blob/bf9158408a9d27932b8678f824cf1fe32d3cd920/src/xxd/xxd.c) and only used at build-time for cpp file generation.
It requires a simple command to build, [$(CC) $(CFLAGS) $(LDFLAGS) -DUNIX -o xxd xxd.c](https://github.com/vim/vim/blob/bf9158408a9d27932b8678f824cf1fe32d3cd920/src/xxd/Makefile#L4).
The file can be added to `SRC_URI`, compiled during build, and PATH can be exported with xxd's parent directory as it's first component during `scr_compile`.  This would eliminate dependence on `app-editors/vim-core`.  xxd from the latest tagged version was chosen but it may likely never need to be updated..

Signed-off-by: Peter Levine <plevine457@gmail.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
Even though it is a small file, I don't see how bundling it is desirable. It'd be far better to fix vim-core to have whatever properties you desire instead, or split xxd into its own package, and then adapt the various packages depending on vim-core purely for xxd.

**Comment by Peter-Levine** [comment]
Feel free to close the PR but this isn't bundling.

From the [wiki](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies):
> In other words, code bundling occurs whenever a program or library ends up containing code that does not belong to it. 

xxd is never installed along with rocr-runtime. 

Your description of having to update it "all over the place" seems to confuse it with a static library.  It is a basic hexdump utility used in the generation of cpp files at build-time.  It stays in `${WORKDIR}`.  And it's basic functionality hasn't changed throughout its existence.

It would be ideal if xxd was maintained in the main tree.  It is in GURU overlay.

**Comment by Peter-Levine** [comment]
> It would be ideal if xxd was maintained in the main tree. It is in GURU overlay.

I think I'll apply to proxy-maintain it.

**Comment by Peter-Levine** [comment]
Sorry.  I'm a bit embarrassed to say I didn't even notice `app-editors/vim-core` has a `minimal` flag.  That solves my issue.

**Comment by thesamesam** [comment]
> Feel free to close the PR but this isn't bundling.
> 
> From the [wiki](https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies):
> 
> > In other words, code bundling occurs whenever a program or library ends up containing code that does not belong to it.
> 
> xxd is never installed along with rocr-runtime.

The wiki is not authoritative on all matters. If I fetched Python and used that to build, but didn't (statically) link against libpython, does that mean it's not bundled? What would you call the practice? We consider this bundling.

We use the bundling term in this sense for gtest too (although we often, but not always, allow that because of how hard it is for projects to keep up for it).

> 
> Your description of having to update it "all over the place" seems to confuse it with a static library. It is a basic hexdump utility used in the generation of cpp files at build-time. It stays in `${WORKDIR}`. And it's basic functionality hasn't changed throughout its existence.

I'm not confusing it though? If it stopped building with a newer compiler (or if we needed to apply a patch to port it to a new environment), we'd still have to do that, for example.

> 
> It would be ideal if xxd was maintained in the main tree. It is in GURU overlay.

This is a policy violation as it shadows something in ::gentoo (it's duplicating vim-core).

I am open to it if you want to explore the solutions I mentioned above which would solve this properly for all packages.

**Comment by thesamesam** [comment]
> Sorry. I'm a bit embarrassed to say I didn't even notice `app-editors/vim-core` has a `minimal` flag. That solves my issue.

I'm still open to us changing things around as you're not the first to complain about it. But it'd require a more holistic view than just rocr-runtime. The vim packages need love and it's not crazy to suggest they could be shuffled about a bit differently.

**Comment by Peter-Levine** [comment]
I see.  Though it would mean fragmenting vim a bit more, it would seem to me that xxd provides such utility as to justify breaking it off into its own package and having `app-editors/vim-core` depend on it.  That would make it possible for `dev-libs/rocr-runtime` to depend directly on xxd, as well as [app-crypt/ima-evm-utils](https://sourceforge.net/p/linux-ima/ima-evm-utils/ci/master/tree/tests/functions.sh#l216), [app-misc/tek](https://github.com/m-ou-se/tek/blob/5ca61325229a66236845f5cb0c362bd01b94312f/Makefile#L42), [dev-db/percona-xtrabackup](https://github.com/percona/percona-xtrabackup/blob/6c73c8214070e494b896efb046b03863668de85d/storage/innobase/xtrabackup/src/CMakeLists.txt#L28), [dev-libs/libbase58](https://github.com/luke-jr/libbase58/blob/b1dd03fa8d1be4be076bb6152325c6b5cf64f678/tests/decode-small.sh#L2), [dev-util/diffoscope](https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/master/diffoscope/comparators/utils/compare.py#L44), [media-libs/libvmaf](https://github.com/Netflix/vmaf/blob/a754965ef876ba5f47fbf60dec3107a3275eb975/libvmaf/src/meson.build#L117), [media-video/harvid](https://github.com/x42/harvid/blob/82d5dba6e5f358edeb6addea57f6132dee5d8e37/src/Makefile#L1), [sci-libs/kim-api](https://github.com/openkim/kim-api/blob/431e641788a5df5ff6058e1974004c7efe93931e/cmake/items-macros.cmake.in#L508), [sys-fs/cryptsetup](https://gitlab.com/cryptsetup/cryptsetup/-/blob/c07cfa20de3b6632d27c256749b93ef8b8b19e18/tests/generators/lib.sh#L150), [sys-fs/dosfstools](https://github.com/dosfstools/dosfstools/blob/77ffb87e8272760b3bb2dec8f722103b0effb801/configure.ac#L80), and [www-client/netsurf](https://source.netsurf-browser.org/netsurf.git/tree/content/handlers/javascript/duktape/Makefile?id=e27df0c0b8081f06fec44562b87b35dc0ad434a3#n15).

**Pull request closed without merging**
