### PR TITLE
net-p2p/deluge: revbump for python-3.12 support

### PR DESCRIPTION
**Pull request by PPed72**
Tests RESTRICTed because they need dev-python/python-twisted, which has no python-3.12 support.

Closes: https://bugs.gentoo.org/933212

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by candrews** [comment]
> Tests RESTRICTed because they need dev-python/python-twisted, which has no python-3.12 support.

Do you mean dev-python/twisted? If so, that does support 3.12: https://github.com/gentoo/gentoo/blob/eedd9727fa3daf3efb5c3f2e238a1862fdd8e5b9/dev-python/twisted/twisted-24.3.0.ebuild#L7

**Comment by PPed72** [comment]
Sorry, I meant dev-python/pytest-twisted

**Comment by parona-source** [comment]
Are there blockers for pytest-twisted where you cant add python3.12 to it? If you didnt have to disable tests it would give better confidence that deluge suppots python3.12 properly.

**Comment by thesamesam** [comment]
@kangie ^

**Comment by thesamesam** [comment]
I've handled the deps now, hopefully.

**Pull request closed without merging**
