### PR TITLE
dev-util/spirv-llvm-translator: Add multilib support

### PR DESCRIPTION
**Pull request by WhatAmISupposedToPutHere**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by ConiKost** [comment]
Please explain, for what you want to add multilib support.

**Comment by WhatAmISupposedToPutHere** [comment]
Certain mesa drivers require spirv-llvm-translator, and I need mesa with both multilib support and those drivers to run legacy 32-bit software.

**Comment by mattst88** [comment]
Mesa's only dependency on `spirv-llvm-translator` is for `USE=opencl` and I don't think rusticl (Mesa's current OpenCL implementation) supports 32-bit.

**Comment by WhatAmISupposedToPutHere** [comment]
The specific driver is asahi, it requires spirv-llvm-translator, it has support for running on 32-bit x86 via an unholy chain of binary translators.

**Comment by mattst88** [comment]
Thanks. I'm still confused though, because we don't have multilib support on arm. Can you explain how this actually works?

**Comment by WhatAmISupposedToPutHere** [comment]
I have a special version of mesa that is compiled for x86, but with support for arm gpus enabled. When i run my x86 only app in a binary translator, this version of mesa gets loaded, and does the normal mesa thing of translating gl/vulkan into native gpu commands. Other libraries that the app needs work in a similar way, all of them are compiled for x86, and the binary translator works on the entire process.

**Comment by mattst88** [comment]
Ahh! I see. The x86 game binary loads an x86-compiled asahi driver. I got it. Thanks!

I'd be fine to take this PR, but we don't even have `VIDEO_CARDS=asahi` in `media-libs/mesa`. Would you like to add support for that in this PR? I understand that even with that we wouldn't be able to build Mesa for the configuration you need.

**Comment by WhatAmISupposedToPutHere** [comment]
Asahi mesa lives in the asahi overlay, and considering the pace of updates and the fact that it requires downstream patches (due to an out-of-tree kernel driver), it is better for it to stay in the overlay for now.

**Pull request closed without merging**
