### PR TITLE
App text asciidoc 9.1.0 bump

### PR DESCRIPTION
**Pull request by marcecj**

### CODE REVIEW

**Comment by orlitzky** [comment]
Since we're waiting to hear back about the `convert` issue... can you update the imagemagick reference in

>  \* Install additional packages for optional runtime features:
>  \*   media-sound/lilypond and media-gfx/imagemagick for "music" filter support

too? Thanks for looking into this! (And sorry it's more annoying than I thought it would be.)

**Comment by marcecj** [comment]
Hah, no worries, I was expecting it to be trivial myself.  I'll wait a week and if I haven't heard anything by then, I'll go back to a hard IM dependency, otherwise I'll update the message (thanks for catching that!).

**Comment by marcecj** [comment]
> Hah, no worries, I was expecting it to be trivial myself. I'll wait a week and if I haven't heard anything by then, I'll go back to a hard IM dependency, otherwise I'll update the message (thanks for catching that!).

Well, no word from upstream, so I'm playing it safe and delaying the dependency change.

**Comment by marcecj** [comment]
Gentle ping, as it's been almost two months now.

**Review by ionenwks — APPROVED** [review]
> Gentle ping, as it's been almost two months now.

Don't hesitate to do so when this takes a while so can know it's ready, lot of older PRs tend to be on hold for one reason or another so I don't look at them much.

**Pull request closed without merging**
