### PR TITLE
net-irc/kvirc: 9999 requires cmake 3.12, not 3.16

### PR DESCRIPTION
**Pull request by DarthGandalf**
Package-Manager: Portage-2.3.84, Repoman-2.3.20
Signed-off-by: Alexey Sokolov <sokolov@google.com>

### CODE REVIEW

**Comment by a17r** [comment]
Dependency was added in commit 4d91171b612acd924ca814c715634d639b853f47, but the referenced upstream commit indeed says 3.12 not 3.16. @Arfrever?

**Comment by Arfrever** [comment]
This pull request is hereby rejected.
With CMake <3.16, `-DPython3_INCLUDE_DIR=...` and `-DPython3_LIBRARY=...` in ebuild would be ignored, resulting in incorrect version of Python being used (the newest found version instead of `PYTHON_SINGLE_TARGET`-selected version).
See also https://gitlab.kitware.com/cmake/cmake/issues/19492 and https://bugs.gentoo.org/691092.
I am not interested in patching KVIrc's `CMakeLists.txt` only in order to support older CMake.

**Comment by a17r** [comment]
We will start stabilisation of cmake-3.16.x soon anyway.

**Comment by DarthGandalf** [comment]
I see, thanks for the links.

Is it possible to somehow add comments inside the DEPEND variable which would explain the discrepancy between the upstream requirement and this requirement?

**Comment by a17r** [comment]
We can't comment inside DEPEND, it would certainly be an improvement to describe the reason for diverging from upstream minimum dep in the commit introducing it. But often times, packaging has practical reasons for tightening minimum dependencies on top of what upstream does, and KDE proj is no exception there.

**Comment by DarthGandalf** [comment]
@a17r Initially KVIrc targeted KDE, but it's not part of KDE project and never been, and you can build KVIrc without KDE. Without KDE, some features are not available, and some windows look a bit differently.
But somehow this is a common confusion... Anyway, it's not related to this pull request

**Comment by a17r** [comment]
It was a general comment regarding KDE proj which I am part of.

**Pull request closed without merging**
