### PR TITLE
dev-python/rdflib: add ~ia64

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://bugs.gentoo.org/829921

### CODE REVIEW

**Comment by t0b3** [comment]
WIP see https://bugs.gentoo.org/814179

**Comment by thesamesam** [comment]
You've really tested on ia64? Or you're just testing CI?

**Comment by t0b3** [comment]
Nope, just filed to fulfill the dependency the gentoo-repo-qa-bot requested ...

**Comment by thesamesam** [comment]
Then we can't just add the keyword ;)

We have to request it via Bugzilla but that's already in progress. Someone has to test it on real Itanium hardware.

**Comment by t0b3** [comment]
unfortunately I can't help with real Itanium ;) let's wait for someone to test this...

**Pull request closed without merging**
