### PR TITLE
net-im/telegram-desktop-bin: add 4.6.5

### PR DESCRIPTION
**Pull request by joecool1029**
Signed-off-by: Joe Kappus <joe@wt.gd>

### CODE REVIEW

**Comment by henning-schild** [comment]
Let us keep this open for at least one week.

This noise is known from that project, and they never get it right.

I already said so when 4.6.0 was suggested.

This does not look like its pressing, and i do not trust them to not come with the next fixup in three days ... this is only worth looking at 5-7 days after a release

**Comment by joecool1029** [comment]
Still think it was fine bumping 4.6.0. I agree on waiting for future minor releases, most of the problems are build or windows issues. I'm going to set this PR to a draft and set it ready for review once things settle down or there's a good reason to bump again.

**Comment by henning-schild** [comment]
thanks, i am sure you will un-Draft when the time has come or follow up with "very likely coming fixes"

as i said before, if gentoo is fast enough that does not matter ... and we can follow

but history has shown that there is not much of a point to do all that, because we have to expect several rounds and should rather follow that thing slowly to avoid noise

**Comment by henning-schild** [comment]
i am always happy when i am wrong on "i told you so" ... but here i have seen too much and can tell you that it is much less trouble if we simply wait

**Comment by henning-schild** [comment]
but i can also tell you that upstream gets thing right when it is about Linux vs Windows/Mac ... they do "releases" that do not even have artifacts for Linux if they did not touch Linux ... not all "releases" are for all OSs

**Comment by joecool1029** [comment]
Oh I got confused yesterday when I went to bump the source ebuild and the patch I knew I upstreamed wasn't in there. Turns out they messed up and reverted their submodules by accident when they pushed the 4.6.1 release: https://github.com/telegramdesktop/tdesktop/pull/25849

**Comment by henning-schild** [comment]
should there be any updates that look like "security" on top of 4.6.0 ... please un-Draft ... we have to follow

**Comment by joecool1029** [comment]
Ok, I'll keep track of the releases.

**Comment by henning-schild** [comment]
all that said ... i really enjoy you helping out

but i would suggest you add youself as co-maintainer, or resort to opening bugs for updates and let me deal with it

**Comment by joecool1029** [comment]
I'll think about adding myself, as a matter of policy I try to only add myself to stuff I directly use full-time. I usually only bump this specific package when I'm doing testing on telegram and the source ebuild is giving me build problems.

I requested to co-maintain that one but didn't hear back from @mid-kid. They do all the heavy lifting but I can help with minor stuff like the recent build fixes.

**Comment by henning-schild** [comment]
maybe undraft now, a few days without more hotfixes have passed

**Comment by henning-schild** [comment]
ROFL ... 4.6.3 is out, banana yellow this time?

**Comment by mid-kid** [comment]
I want to get off mr bone's wild ride.

**Comment by joecool1029** [comment]
move fast break stuff i guess

**Comment by henning-schild** [comment]
we have 4.6.5 now https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.5

**Comment by joecool1029** [comment]
ok, ready to merge I think?

image

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
