### PR TITLE
net-dns/ddclient-3.8.3: version bump

### PR DESCRIPTION
**Pull request by nE0sIghT**
Fixes: https://bugs.gentoo.org/show_bug.cgi?id=558790

### CODE REVIEW

**Comment by idella** [comment]
Note the entry here in
 profiles/arch/arm/package.use.mask by Whissi. It is an attribution statement declaring endorsement by the supervising dev or a project's members.  You will require one of its kind for each and all such entries under /profiles directory.

**Comment by nE0sIghT** [comment]
Yes, I also saw a note in hppa profile directory that forbids package.use.mask file edits.
However I'm in doubt about proper way to handle this case.

**Comment by monsieurp** [comment]
@titanofold

**Comment by titanofold** [comment]
Oh, great, somebody got around to this! I've been too busy fiddling around with PostgreSQL stuff...and imgur.

For use flag masking, it's best to just leave it alone and either email the arch teams or open a bug on b.g.o.

The worst that'll happen is people will have to jump through hoops to get cloudflare working on those arches due to no keyword and we won't be able to stable this ebuild until it's done.

So, revert the changes to hppa and arm profiles.

**Comment by nE0sIghT** [comment]
I dropped "alpha arm hppa ia64 ppc ppc64 sparc" keywords from ebuild and reverted profile changes

**Comment by monsieurp** [comment]
@titanofold ping

**Comment by nE0sIghT** [comment]
Pushed new ebuild with "default" added to src_prepare

**Comment by monsieurp** [comment]
@titanofold please review and merge accordingly.

**Pull request closed without merging**
