### PR TITLE
media-sound/spotify: update SRC_URI and ebuild version

### PR DESCRIPTION
**Pull request by kernaltrap8**
Update the SRC_URI and ebuild version to match the current build available.

---

Please check all the boxes that apply:

- [x ] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x ] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [ x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x ] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Kangie** [comment]
Hi @kernaltrap8,

Thanks for the PR, however in this case it's best to add the new version in one commit and then, if required, drop the old ebuild. Making changes atomic like this makes it easy to roll back changes, and if we encounter an issue with the newer package we still have an older version to fall back on.

You can accomplish this in a few ways using Git, please reach out if you need assistance.

My other concern here is that this new version is keyworded stable - as per the [Keywording and Stablisation Policy](https://devmanual.gentoo.org/keywording/#keywording-on-upgrades) we need to drop all keywords on a new version to `~arch` to ensure that we don't inadvertently introduce new bugs on stable systems.

We have a handy tool to automate this process as it's prone to mistakes when done by hand - `ekeyword`; try `ekeyword ~all spotify-${ver}.ebuild`

**Comment by kernaltrap8** [comment]
Understood. I will work on this soon. Thank you for replying.

**Comment by parona-source** [comment]
https://bugs.gentoo.org/933403

Include a closes tag for this^

@Kangie spotify is a package where you are forced to push to stable, the old version is broken quite often by the time a new version is added.

**Comment by kernaltrap8** [comment]
@parona-source so what should I do here exactly?

**Comment by parona-source** [comment]
Add new spotify version in one commit, remove old spotify version in another. Commiting straight to stable is fine in this case.

**Comment by kernaltrap8** [comment]
So... should I revert this commit and make the changes then? Sorry I'm not used to working with others and I want to make sure I'm doing this correctly.

**Comment by kernaltrap8** [comment]
Okay, I have made the proper changes. If anything else is needed, let me know. @parona-source

**Comment by parona-source** [comment]
git rebase to remove the original commit + revert commit.

amend the closes tags to be like this:

```
media-sound/spotify: add 1.2.37

Closes: https://bugs.gentoo.org/933403
Signed-off-by: kernaltrap8 <kernaltrap@gmail.com>
```

A guide on using rebase.
https://git-rebase.io/

**Comment by prometheanfire** [comment]
thanks for this, just merged it

**Pull request closed without merging**
