### PR TITLE
dev-python/python-nbxmpp: Fix libsoup dependencies without slot requirement

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/881557
Signed-off-by: brahmajit das <listout@protonmail.com>

### CODE REVIEW

**Review by mattst88 — APPROVED** [review]
I'm not 100% sure that we should touch `PYTHON_COMPAT` in the older two ebuilds, but it's fine with me.

**Comment by scardracs** [comment]
Please fix the title: python/python is a bit misleading

**Comment by listout** [comment]
@scardracs Sorry about that. If you look at the commit tab you can see that it's actually fixed but GitHub doesn't update the label via commit.

**Comment by mgorny** [comment]
Thanks!

**Pull request closed without merging**
