### PR TITLE
dev-lang/php: add 8.3.12, inherit postgres.eclass

### PR DESCRIPTION
**Pull request by matoro**
Unfortunately since dev-lang/php[postgres] builds against libpq which changes soname with postgres major versions, it must be built against a specific postgres version.  The only way to properly do this while respecting slotted postgresql is to bring in `POSTGRES_TARGETS` & friends.

This adds maintenance overhead as `POSTGRES_COMPAT` now needs to be kept up to date.

Closes: https://bugs.gentoo.org/762370

(PR note:  compat range starts at 15 because otherwise older postgres has to be keyworded for riscv/loong)

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by orlitzky** [comment]
I'm still not quite sold on this. Looking back at my old comments, there's only an issue with postgres major-version updates. And even then, the "issue" is that `@preserved-rebuild` wants to rebuild PHP.

The postgres eclass doesn't really fix the rebuild problem. What it does is introduce a bunch of `USE` flags that can be set in the profile to control the version of postgres that gets used as a dependency at emerge time. When a new major version of postgres is stabilized, the value of `POSTGRES_TARGETS` gets bumped in the profiles, and then `USE=postgres_targets_postgres16` (or whatever) becomes set automatically, whereas the old version would have been `USE=postgres_targets_postgres15`. This doesn't trigger a rebuild by itself though -- it's only the portage `--changed-use` option that will notice the ninja-edit within the profile and initiate a rebuild.

So we have two portage only solutions to a non-problem :)

1. Use `@preserved-rebuild` whenever postgres is updated
2. Always use `--changed-use` when you emerge

While I admit that a lot of people probably do it, I think the second option is actually the worse of the two. Using `@preserved-rebuild` alerts you to the problem, only when there's a problem, and then it fixes the problem and goes away. Adding `--changed-use` to every `emerge`, on the other hand, will slow it down a great deal, and will cause you to rebuild hundreds of unrelated packages between postgres updates as various maintainers make `USE` changes without revbumps.

Am I missing something? I barely remembered this issue so it's very possible.

**Comment by thesamesam** [comment]
> I'm still not quite sold on this. Looking back at my old comments, there's only an issue with postgres major-version updates. And even then, the "issue" is that @preserved-rebuild wants to rebuild PHP.

The issue is that right now, FEATURES="preserved-libs" is the only thing keeping the old library around, and relying on that is worse, because:
a) preserved-libs is far more of a Portageism than changed-use;
b) even without changed-use, the behaviour with proper use of the eclass means that you get the dep pinned by USE, and you just can't depclean it until you re-emerge with a newer USE set (for whatever reason, be it a new version, manually, or with changed-use), which is better than relying on the PM to keep it around via preserved-libs.

**Comment by orlitzky** [comment]
Ok, that is exactly what I was missing, thanks. I'm convinced.

**Comment by eli-schwartz** [comment]
> This doesn't trigger a rebuild by itself though -- it's only the portage `--changed-use` option that will notice the ninja-edit within the profile and initiate a rebuild.
> 
> So we have two portage only solutions to a non-problem :)
> 
>  1. Use `@preserved-rebuild` whenever postgres is updated
> 
>  2. Always use `--changed-use` when you emerge

If you think about it -- you don't have to use --changed-use, you are welcome to keep old postgresql around. preserved-libs / `@preserved-rebuild` also keeps old posgresql (the relevant package contents if not the vdb record) around, but it does so outside of PMS and users are permitted to configure it (for speed, perhaps) to not do so.

Using the class and the USE flag based dependencies allows people to choose when they wish to migrate postgresql, either by updating with --changed-use or by explicitly re-emerging php. It also comes with one more side benefit: by setting the POSTGRES_TARGETS globally, you can (try to) align all packages on your system towards using the same version of postgres, e.g. in case some packages don't support the latest version N you can configure your system with N-1 instead, to have just one version installed, and then forget about it (and bother with changed-use, or not, as you choose).

**Comment by orlitzky** [comment]
This would need a revbump for the dependency change, but php-8.3.12 is out, so if you want to do the version bump instead it should be trivial.

**Comment by orlitzky** [comment]
> 
> If you think about it -- you don't have to use --changed-use, you are welcome to keep old postgresql around.

Well obviously I didn't think about it :P

I was listening to 2021 mjo, but that guy's an idiot.

**Comment by matoro** [comment]
Sure, did a copy-paste bump (compile test only) with the postgres changes applied.  8.3.11 is untouched now.

**Pull request closed without merging**
