### PR TITLE
app-shells/starship: add 1.6.3

### PR DESCRIPTION
**Pull request by ixti**
Signed-off-by: Alexey Zapparov <alexey@zapparov.com>
See-Also: https://github.com/gentoo/gentoo/pull/25020

### CODE REVIEW

**Comment by ixti** [comment]
New version adds a couple of new dependencies. One of them (terminfo) requires additional license (WTFPL-2).

**Comment by thesamesam** [comment]
@bowlofeggs ok?

**Comment by bowlofeggs** [comment]
@thesamesam I have not yet reviewed this, but if you have reviewed it and approve then I see no reason to hold it up on me. If you would prefer me to review it, I will attempt to do so in the next few days. Your option ☺

**Comment by thesamesam** [comment]
@bowlofeggs Thanks! I'll give it a look and if it looks alright, I'll merge it, because I've got a few minutes now. Cheers!

**Comment by bowlofeggs** [comment]
Stabilization request: https://bugs.gentoo.org/853925

**Pull request closed without merging**
