### PR TITLE
net-mail/mu: bump to 1.3.3

### PR DESCRIPTION
**Pull request by 00-matt**
Package-Manager: Portage-2.3.69, Repoman-2.3.16

### CODE REVIEW

**Comment by 00-matt** [comment]
I hope this is okay, I saw #12127 from a few months ago but it looks like the author disappeared.

**Comment by juippis** [comment]
Would be nice to have a maintainer for this, though :I

**Comment by 00-matt** [comment]
Hi, I added myself and the Proxy Maintainers project as maintainers.

**Comment by juippis** [comment]
Thanks! Everything looks good, but could you include fix for https://bugs.gentoo.org/684140 while at it? Otherwise you'll have to revbump, forcing everyone to build it twice.

**Comment by 00-matt** [comment]
Thanks, updated! :)

**Comment by juippis** [comment]
Thanks! Welcome aboard :)

**Pull request closed without merging**
