### PR TITLE
⬆️ net-im/telegram-desktop: add 4.16.6

### PR DESCRIPTION
**Pull request by Jamim**
_Hello @dlan17 and @mid-kid,_

**Telegram Desktop** `4.16.6` [was released](https://github.com/telegramdesktop/tdesktop/releases/tag/v4.16.6) recently.
As always, I've tested it on my `~amd64` machine and it works fine for me.

Changelog:
  - https://github.com/telegramdesktop/tdesktop/blob/v4.16.6/changelog.txt

Based on:
  - [net-im/telegram-desktop-4.16.4](https://gitweb.gentoo.org/repo/gentoo.git/commit/net-im/telegram-desktop/telegram-desktop-4.16.4.ebuild?id=4b681a67160271ec96912fc12ad1c50536825705) from #36157
  - [net-im/telegram-desktop-4.11.7-r1](https://gitweb.gentoo.org/repo/gentoo.git/commit/net-im/telegram-desktop/telegram-desktop-4.11.7-r1.ebuild?id=3006f656e6dd79d109533b220b224ad7de22a818) from #34226
  - [files/tdesktop-4.2.4-jemalloc-only-telegram-r1.patch](https://gitweb.gentoo.org/repo/gentoo.git/commit/net-im/telegram-desktop/files/tdesktop-4.2.4-jemalloc-only-telegram-r1.patch?id=ce4cbbe6125f6444606f3c3df4c82c93e17a8e64) from #31044

<details>
<summary>diff -u telegram-desktop-4.16.{4,6}.ebuild</summary>

```diff
--- telegram-desktop-4.16.4.ebuild	2024-04-08 15:58:45.604823719 +0300
+++ telegram-desktop-4.16.6.ebuild	2024-04-11 00:19:13.630540766 +0300
@@ -17,7 +17,7 @@
 LICENSE="BSD GPL-3-with-openssl-exception LGPL-2+"
 SLOT="0"
 KEYWORDS="~amd64 ~arm64 ~loong ~ppc64 ~riscv"
-IUSE="dbus enchant +fonts screencast qt6 qt6-imageformats wayland webkit +X"
+IUSE="dbus enchant +fonts +jemalloc screencast qt6 qt6-imageformats wayland webkit +X"
 REQUIRED_USE="
 	qt6-imageformats? ( qt6 )
 "
@@ -47,6 +47,7 @@
 	sys-libs/zlib:=[minizip]
 	!enchant? ( >=app-text/hunspell-1.7:= )
 	enchant? ( app-text/enchant:= )
+	jemalloc? ( dev-libs/jemalloc:=[-lazy-lock] )
 	!qt6? (
 		>=dev-qt/qtcore-5.15:5=
 		>=dev-qt/qtgui-5.15:5=[dbus?,jpeg,png,wayland?,X?]
@@ -95,8 +96,10 @@
 	virtual/pkgconfig
 	wayland? ( dev-util/wayland-scanner )
 "
+# dev-libs/jemalloc:=[-lazy-lock] -> https://bugs.gentoo.org/803233
 
 PATCHES=(
+	"${FILESDIR}/tdesktop-4.2.4-jemalloc-only-telegram-r1.patch"
 	"${FILESDIR}/tdesktop-4.10.0-system-cppgir.patch"
 )
 
@@ -180,6 +183,7 @@
 
 		-DDESKTOP_APP_DISABLE_X11_INTEGRATION=$(usex !X)
 		-DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION=$(usex !wayland)
+		-DDESKTOP_APP_DISABLE_JEMALLOC=$(usex !jemalloc)
 		## Enables enchant and disables hunspell
 		-DDESKTOP_APP_USE_ENCHANT=$(usex enchant)
 		## Use system fonts instead of bundled ones
@@ -218,6 +222,13 @@
 		ewarn "both the 'X' and 'screencast' USE flags are disabled, screen sharing won't work!"
 		ewarn
 	fi
+	if ! use jemalloc && use elibc_glibc; then
+		# https://github.com/telegramdesktop/tdesktop/issues/16084
+		# https://github.com/desktop-app/cmake_helpers/pull/91#issuecomment-881788003
+		ewarn "Disabling USE=jemalloc on glibc systems may cause very high RAM usage!"
+		ewarn "Do NOT report issues about RAM usage without enabling this flag first."
+		ewarn
+	fi
 	if use wayland && ! use qt6; then
 		ewarn "Wayland-specific integrations have been deprecated with Qt5."
 		ewarn "The app will continue to function under wayland, but some"
```

</details>

Related PRs:
  - #36181
  - #36192

_Best regards!_

### CODE REVIEW

**Comment by dlan17** [comment]
hi @jamim , can you double check if this version introduce jemalloc dependency? as I've got this build error..

-- Checking for module 'jemalloc'
--   Package 'jemalloc', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:619 (message):
  The following required packages were not found:

   - jemalloc

**Comment by mid-kid** [comment]
I'm so glad I added the snippet to mark every dependency as required, otherwise this would've gone unnoticed.

Apparently they ["switched back from scudo to jemalloc"](https://github.com/desktop-app/cmake_helpers/commit/5a19eddd4554486547d6d5dac3002a93bc105867), and "scudo" is a dependency that went unnoticed because it can only be used when linked statically, so it was bundled. It would've been nice if that one was a use flag as well.

Anyway, I think it's fine to turn fully off at this point, as it seems that it's only meant to fix issues with older glibc allocators, and these days it should work fine (it has always worked fine with musl). If you decide to add a USE=jemalloc anyway, follow the old ebuild: https://github.com/gentoo/gentoo/blob/e5ff869f9552459a8b0698738ce03fcb8aeeb376/net-im/telegram-desktop/telegram-desktop-4.11.7.ebuild and make sure to include the `jemalloc-only-telegram` patch to avoid build failures.

**Comment by mid-kid** [comment]
Scratch that, jemalloc must be enabled on glibc systems

**Comment by Jamim** [comment]
Thank you @dlan17 and @mid-kid! 🙇🏼
I've brought back the `jemalloc` USE flag.

**Comment by dlan17** [comment]
hi, I've pushed with minor commit msg adjustment, also tested with jemalloc[lazy-lock], found it works fine, so I went ahead and loosen this restriction,  see 
https://github.com/gentoo/gentoo/commit/a9e6c3310976482ab2d9c2bcba2c0a1100ce1f6a

**Comment by mid-kid** [comment]
I hope you're right about lazy-lock, because this was an intermittent problem that I couldn't really reproduce in all scenarios.

**Comment by dlan17** [comment]
Ok, thanks for your explanation.. then let's just watch it and see what will happen, if lazy-lock eventually become a problem, we can revert that commit back..

**Pull request closed without merging**
