### PR TITLE
Cleanup incorrect MIT-with-advertising

### PR DESCRIPTION
**Pull request by parona-source**
Haven't gone through ebuilds where homepage / source 404's (sandy and stimg). Or if I found it too arduous (pycharm-community and skypeforlinux). The only valid uses of MIT-with-advertising that I can confirm are e16-keyedit and e16menuedit2.

And go-jira may have to have all-rights-reserved due to this https://github.com/coryb/kingpeon/issues/3

### CODE REVIEW

**Review by ulm — APPROVED** [review]
I've checked app-editors/hyx-2021.06.09 and x11-terms/st-0.9, both LGTM.

**Review by lanodan — APPROVED** [review]

**Comment by lanodan** [comment]
Checked gtk-layer-shell, LGTM

**Review by ionenwks — APPROVED** [review]
Cherry picking the imv one given I'm about to revbump it and it'll need rebasing. Haven't checked the others but I imagine they're fine.

**Review by ZeroChaos- — APPROVED** [review]

**Review by juippis — APPROVED** [review]

**Comment by ferki** [comment]
I'm fairly late to the party over here :sweat_smile: Thank you folks for double-checking and reviewing the licenses, including for x11-terms/st{,-terminfo} :heart:

**Pull request closed without merging**
