### PR TITLE
net-irc/znc: fix URI and change USE-flags

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by wraeth** [comment]
Thanks :)

**Comment by Whissi** [comment]
@DarthGandalf: Is there a reason why you disabled the *icu* USE flag per default? According to ZNC's *configure* script this should be enabled per default...

**Comment by DarthGandalf** [comment]
@Whissi no special reason. I thought defaults should be managed by the selected profile?

**Comment by DarthGandalf** [comment]
By the way, ZNC's configure script (and CMakeLists.txt in 1.7) by default enables most optional features *if they are available*. Explicit `--enable-foo` changes the behavior to report an error if the feature is not available (e.g. if libicu is not installed).
Having icu with a USE-flag disables such guessing, and ensures the environment is consistent.

In any case, I'm not opposed to making it `+icu`

**Comment by Whissi** [comment]
First, I appreciate your contribution. Looks like you fixed an automagic bug.

In general, at least that's what I learned when I did my quizzes, we follow upstream when choosing default USE flags. And judging from the *configure* script upstream wants to enable *icu* per default.

I tried to answer the question by myself but I am not really sure where ZNC is using ICU. From http://wiki.znc.in/Charset I would say that most users would want to enable *ICU* per default but I maybe wrong. So you have more insight... that's why I am asking.

If you are going to turn on everything which is possible in future the package maintainer has to select the default feature set based on things like "Features most people use vs as few dependencies as possible".

**Comment by DarthGandalf** [comment]
I see.
In that case `ssl` and `ipv6` USE flags also should be on by default.
IPv6 doesn't require any additional dependency, and not having SSL support just makes the software useless these days.

**Pull request closed without merging**
