### PR TITLE
media-sound/moc: Add sndio support

### PR DESCRIPTION
**Pull request by strikersh**
Signed-off-by: Jules de Sartiges <desartij@protonmail.com>

### CODE REVIEW

**Comment by fordfrog** [comment]
you should keep alphabetical order at least in the use flags and the conditional deps. and there is an issue with the dependency.

**Comment by strikersh** [comment]
okay, I changed the order.
I don't understand the issue with `media-sound/sndio`
it is part of `::gentoo` https://packages.gentoo.org/packages/media-sound/sndio

**Comment by fordfrog** [comment]
@strikersh i did some testing and noticed that the problem is in the fact that you are modifying stable ebuilds and depending on an unstable package. that's the cause of the issues. basically, before you commit anything, you should run `repoman full` and `pkgcheck scan` in the package directory to verify none of these programs has any complaints. there are two solutions to this issue. either do a revbump instead of modifying the stable ebuilds, or first ask for stabilization of sndio and then this pr would work. or you can do a revbump, and in the meantime you can ask for sndio stabilization and once sndio is stable we can stabilize your revbumps.

**Comment by fordfrog** [comment]
@strikersh i did some testing and noticed that the problem is in the fact that you are modifying stable ebuilds and depending on an unstable package. that's the cause of the issues. basically, before you commit anything, you should run `repoman full` and `pkgcheck scan` in the package directory to verify none of these programs has any complaints. there are two solutions to this issue. either do a revbump instead of modifying the stable ebuilds, or first ask for stabilization of sndio and then this pr would work. or you can do a revbump, and in the meantime you can ask for sndio stabilization and once sndio is stable we can stabilize your revbumps.

**Comment by fordfrog** [comment]
@strikersh thanks!

**Pull request closed without merging**
