### PR TITLE
dev-python/pyodbc: add support for python3

### PR DESCRIPTION
**Pull request by strahlc**

### CODE REVIEW

**Comment by monsieurp** [comment]
Please reformat your commit message: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by monsieurp** [comment]
@gentoo/python

**Comment by floppym** [comment]
What kind of testing have you done to verify that this works with python3?

**Comment by strahlc** [comment]
I'm using pyodbc since 2014 with python3.

mgorny has droped python3 support by switching from pyodbc-3.0.7 to pyodbc-3.0.7-r1 without writing any reasons. (Perhaps by accident)
Since that, I've use pyodbc from my local overlay with Python3 support.

I've used pyodbc with python3.2, python3.3 and currently python3.4 on diffent machines (2 Workstations, 3 VMs) each amd64.

I'm using pyodbc with the FreeTDS driver to access MS-SQL Databases and generate hourly reports.

Quote from the official release change log [1] regarding python3 support :
> 3.0.2 - 2011-12-26
> 
> This is the first official pyodbc release that supports both Python 2 and Python 3 (3.2+). Merry Christmas!

[1] http://mkleehammer.github.io/pyodbc/releases.html

**Comment by monsieurp** [comment]
Fair enough. Thanks for linking to the changelog. There was no reason to remove it in the first place so I guess we can add it back.

**Pull request closed without merging**
