### PR TITLE
Asterisk init scripts

### PR DESCRIPTION
**Pull request by jkroonza**
Not to be merged yet.  Diff for the revision bump is:

```
--- asterisk-18.18.0.ebuild	2023-06-02 09:16:45.218947570 +0200
+++ asterisk-18.18.1.ebuild	2023-07-09 21:52:21.677897234 +0200
@@ -5,7 +5,7 @@
 
 LUA_COMPAT=( lua5-{1..4} )
 
-inherit autotools linux-info lua-single systemd toolchain-funcs tmpfiles
+inherit autotools linux-info lua-single toolchain-funcs
 
 DESCRIPTION="Asterisk: A Modular Open Source PBX System"
 HOMEPAGE="https://www.asterisk.org/"
@@ -96,6 +96,7 @@
 RDEPEND="${DEPEND}
 	net-misc/asterisk-core-sounds
 	net-misc/asterisk-extra-sounds
+	net-misc/asterisk-init-scripts
 	net-misc/asterisk-moh-opsound
 	selinux? ( sec-policy/selinux-asterisk )
 	syslog? ( virtual/logger )"
@@ -312,14 +313,6 @@
 	diropts -m 0750 -o asterisk -g asterisk
 	keepdir /var/log/asterisk/{cdr-csv,cdr-custom}
 
-	newsbin "${FILESDIR}/asterisk_wrapper-18.17.1-20.2.1" asterisk_wrapper
-	newinitd "${FILESDIR}"/initd-18.17.1-20.2.1 asterisk
-	newconfd "${FILESDIR}"/confd-16.26.1-18.12.1 asterisk
-
-	systemd_dounit "${FILESDIR}"/asterisk.service
-	newtmpfiles "${FILESDIR}"/asterisk.tmpfiles-16.22.0-18.8.0.conf asterisk.conf
-	systemd_install_serviced "${FILESDIR}"/asterisk.service.conf
-
 	# Reset diropts else dodoc uses it for doc installations.
 	diropts -m0755
 
@@ -343,8 +336,6 @@
 }
 
 pkg_postinst() {
-	tmpfiles_process asterisk.conf
-
 	if [ -z "${REPLACING_VERSIONS}" ]; then
 		elog "Asterisk Wiki: https://wiki.asterisk.org/wiki/"
 		elog "Gentoo VoIP IRC Channel: #gentoo-voip @ irc.libera.chat"
```

We get to drop a bunch of files from net-misc/asterisk/files eventually, and we get to avoid cases like currently in the tree where the init scripts for asterisk 16 ended up lagging behind 18 and 20.

I only see upsides to this in the longer term, in the short term we have some complexity in terms of what's going into the tree.

mysql-init-scripts only has blockers, however, my feeling is that neither asterisk nor asterisk-init-scripts makes sense without the other, thus this has to be a *circular* RDEPEND (Not BDEPEND as either one can be installed first).

### CODE REVIEW

**Comment by juippis** [comment]
Let us know when this is good.

**Comment by jkroonza** [comment]
> Let us know when this is good.

I thought converting from draft to "ready for review" was good enough :).

**Review by juippis — APPROVED** [review]
Okay, looks good! Upgrading could be a bit messy but it should work out. Let's figure it out if problems arise.

**Comment by jkroonza** [comment]
I did a test upgrade, went smooth but I do agree I had my reservations, and issues could still crop up.

Anyone that bites into this, please either file a bug on bugs.gentoo.org, or perhaps simpler to see if you can get hold of me via IRC on #gentoo-voip at libera.chat.

**Pull request closed without merging**
