### PR TITLE
app-mobilephone/gammu: bump and new Python library

### PR DESCRIPTION
**Pull request by sbraz**
Fixes https://bugs.gentoo.org/show_bug.cgi?id=536722 and https://bugs.gentoo.org/show_bug.cgi?id=566168
Tests pass for both gammu and the Python lib.

```diff
--- gammu-1.33.0-r1.ebuild	2016-01-06 01:01:00.402938259 +0100
+++ gammu-1.36.8.ebuild	2016-02-02 15:21:04.510437047 +0100
@@ -1,21 +1,19 @@
-# Copyright 1999-2015 Gentoo Foundation
+# Copyright 1999-2016 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
 EAPI=5
 
-PYTHON_COMPAT=( python2_7 )
-
-inherit eutils cmake-utils python-single-r1
+inherit eutils cmake-utils
 
 DESCRIPTION="A tool to handle your cellular phone"
-HOMEPAGE="http://www.wammu.eu/"
+HOMEPAGE="http://wammu.eu/gammu/"
 SRC_URI="http://dl.cihar.com/${PN}/releases/${P}.tar.bz2"
 
 LICENSE="GPL-2"
 SLOT="0"
 KEYWORDS="~amd64 ~x86"
-IUSE="bluetooth curl dbi debug irda mysql nls postgres python usb"
+IUSE="bluetooth curl dbi debug irda mysql nls postgres usb"
 
 # TODO: figure out a way to disable gudev
 RDEPEND="dev-libs/glib:2=
@@ -25,27 +23,21 @@
 	dbi? ( >=dev-db/libdbi-0.8.3:= )
 	mysql? ( virtual/mysql:= )
 	postgres? ( dev-db/postgresql:=[server] )
-	python? ( ${PYTHON_DEPS} )
 	usb? ( virtual/libusb:1= )
 	dev-util/dialog"
 DEPEND="${RDEPEND}
 	irda? ( virtual/os-headers )
 	nls? ( sys-devel/gettext )"
-REQUIRED_USE="${PYTHON_REQUIRED_USE}"
 
 # sys-devel/gettext is needed for creating .mo files
 # Supported languages and translated documentation
 # Be sure all languages are prefixed with a single space!
-MY_AVAILABLE_LINGUAS=" af ar bg ca cs da de el en_GB es et fi fr gl he hu id it ko nl pl pt_BR ru sk sv sw tr zh_CN zh_TW"
+MY_AVAILABLE_LINGUAS=" af ar bg bn ca cs da de el en_GB es et fi fr gl he hu id it ko nl pl pt_BR ro ru sk sv sw tr zh_CN zh_TW"
 IUSE="${IUSE} ${MY_AVAILABLE_LINGUAS// / linguas_}"
 
-pkg_setup() {
-	use python && python-single-r1_pkg_setup
-}
-
 src_prepare() {
-	epatch "${FILESDIR}/${PN}-skip-locktest.patch"
-	epatch "${FILESDIR}/${PN}-1.32.0-bashcompdir.patch"
+	epatch "${FILESDIR}/${PN}-skip-locktest.patch" \
+		"${FILESDIR}/${PN}-1.36.8-bashcompdir.patch"
 
 	local lang support_linguas=no
 	for lang in ${MY_AVAILABLE_LINGUAS} ; do
@@ -71,7 +63,6 @@
 		$(cmake-utils_use_with irda IRDA)
 		$(cmake-utils_use_with curl CURL)
 		$(cmake-utils_use_with usb USB)
-		$(cmake-utils_use_with python PYTHON)
 		$(cmake-utils_use_with mysql MySQL)
 		$(cmake-utils_use_with postgres Postgres)
 		$(cmake-utils_use_with dbi LibDBI)
@@ -80,17 +71,9 @@
 		-DBUILD_SHARED_LIBS=ON
 		-DINSTALL_DOC_DIR="share/doc/${PF}"
 	)
-	if use python; then
-		mycmakeargs+=( -DBUILD_PYTHON="${PYTHON}" )
-	fi
 	cmake-utils_src_configure
 }
 
 src_test() {
 	LD_LIBRARY_PATH="${WORKDIR}/${PN}_build/common" cmake-utils_src_test
 }
-
-src_install() {
-	cmake-utils_src_install
-	use python && python_optimize
-}

```

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/python @gentoo/proxy-maint

**Comment by awilfox** [comment]
I intend to be the proxy maintainer for python-gammu per bugs #566168 and #573612.  Please update the metadata.xml file accordingly, thanks :+1:

**Comment by sbraz** [comment]
Done @awilfox

**Comment by hartwork** [comment]
Thanks for your contribution!

**Comment by hartwork** [comment]
For those using Wammu as well, I bumped it to 0.40 now.
33ba954a2247e36de35acae4f96da4dceb0bceed

**Pull request merged**
