### PR TITLE
app-accessibility/at-spi2-core: Version bump to 2.48.3

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
There's a new option in meson_options.txt. Related to https://bugs.gentoo.org/699958

**Comment by flint2** [comment]
> There's a new option in meson_options.txt. Related to https://bugs.gentoo.org/699958
Added dbus_broker USE flag in
https://github.com/gentoo/gentoo/commit/dfbe567cb53c191a1e0ad4c87d445baec76f2171
Let me know if there are better patterns for conditional RDEPEND or meson arguments
Thanks!

**Comment by flint2** [comment]
> > There's a new option in meson_options.txt. Related to https://bugs.gentoo.org/699958
> > Added dbus_broker USE flag in
> > [dfbe567](https://github.com/gentoo/gentoo/commit/dfbe567cb53c191a1e0ad4c87d445baec76f2171)
> > Let me know if there are better patterns for conditional RDEPEND or meson arguments
> > Thanks!

Added usex pattern in meson arguments in commit: https://github.com/gentoo/gentoo/commit/5a3f8a4bbd5a2ec30cd004575747711e33bd1621

**Comment by mattst88** [comment]
Thanks!

Please always use `pkgcheck scan --commits`. There are a few warnings here:

````
app-accessibility/at-spi2-core
  PkgMetadataXmlIndentation: metadata.xml: metadata.xml has inconsistent indentation on line: 12
  UnderscoreInUseFlag: USE flag 'dbus_broker' uses reserved underscore character
  IndirectInherits: version 2.48.0: multibuild: indirect inherit usage: 'BUILD_DIR', line 56
  IndirectInherits: version 2.48.2-r1: multibuild: indirect inherit usage: 'BUILD_DIR', line 63
  RedundantVersion: version 2.48.2-r1: slot(2) keywords are overshadowed by version: 2.48.3
  DoubleEmptyLine: version 2.48.3: ebuild has unneeded empty line on on line: 59
  IndirectInherits: version 2.48.3: multibuild: indirect inherit usage: 'BUILD_DIR', line 61
````

**Comment by mattst88** [comment]
I fixed those^ things, and a few others:

- dbus-broker doesn't have multilib-support, presumably because it doesn't need it (e.g. it doesn't install a library), and at-spi2-core only needs to execute a binary from it, so I dropped the [${MULTILIB_USEDEP}] from it
- it's a runtime-only dependency, so I switched around RDEPEND and DEPEND and added dbus-broker only to RDEPEND
- dbus-broker does not replace dbus, and dbus is still needed regardless, so I changed that
- I masked USE=dbus-broker for at-spi2-core for all architectures where sys-apps/dbus-broker is not keyworded

Thanks! One bug down :)

**Pull request closed without merging**
