### PR TITLE
net-misc/x11-ssh-askpass: remove unneeded command call

### PR DESCRIPTION
**Pull request by ionenwks**

### CODE REVIEW

**Comment by juippis** [comment]
I didn't hit the error that ago did, but now I got:
```
>>> Failed to emerge net-misc/x11-ssh-askpass-1.2.4.1-r2, Log file:
>>>  '/var/tmp/portage/vbslogs/build/net-misc/x11-ssh-askpass-1.2.4.1-r2:20210415-090047.log'
>>> Jobs: 0 of 1 complete, 1 failed                 Load avg: 0.00, 0.00, 0.00
 * Package:    net-misc/x11-ssh-askpass-1.2.4.1-r2
 * Repository: gentoo
 * Maintainer: spiderx@spiderx.dp.ua proxy-maint@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox

>>> Unpacking source...
>>> Unpacking x11-ssh-askpass-1.2.4.1.gh.tar.gz to /var/tmp/portage/net-misc/x11-ssh-askpass-1.2.4.1-r2/work
>>> Source unpacked in /var/tmp/portage/net-misc/x11-ssh-askpass-1.2.4.1-r2/work
>>> Preparing source in /var/tmp/portage/net-misc/x11-ssh-askpass-1.2.4.1-r2/work/x11-ssh-askpass-1.2.4.1 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/net-misc/x11-ssh-askpass-1.2.4.1-r2/work/x11-ssh-askpass-1.2.4.1 ...
./configure --prefix=/usr --build=x86_64-pc-linux-gnu --host=x86_64-pc-linux-gnu --mandir=/usr/share/man --infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib --libdir=/usr/lib64 --libexecdir=/usr/lib64/misc --disable-installing-app-defaults

x11-ssh-askpass has been configured with the following options:

                  Askpass directory: /usr/lib64/misc
                        Manual page: /usr/share/man/man1
          Application defaults file: SshAskpass-default.ad
     Application defaults directory: default
  Install application defaults file: no

        Compiler: default
  Compiler flags: -march=native -O2 -pipe -frecord-gcc-switches
    Linker flags: -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0

You may now create the Makefile and build x11-ssh-askpass using the
following commands:

        xmkmf
	make includes
	make

imake -DUseInstalled -I/usr/lib64/X11/config
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-misc/x11-ssh-askpass-1.2.4.1-r2/work/x11-ssh-askpass-1.2.4.1 ...
make -j16 -l10 CC=x86_64-pc-linux-gnu-gcc 'CDEBUGFLAGS=-march=native -O2 -pipe -frecord-gcc-switches' 
x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -frecord-gcc-switches      -I/usr/include    -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 				-D_POSIX_SOURCE -D_XOPEN_SOURCE 	-D_BSD_SOURCE -D_SVID_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 				  				  -DFUNCPROTO=15 -DNARROWPROTO       -c -o drawing.o drawing.c
x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -frecord-gcc-switches      -I/usr/include    -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 				-D_POSIX_SOURCE -D_XOPEN_SOURCE 	-D_BSD_SOURCE -D_SVID_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 				  				  -DFUNCPROTO=15 -DNARROWPROTO       -c -o dynlist.o dynlist.c
x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -frecord-gcc-switches      -I/usr/include    -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 				-D_POSIX_SOURCE -D_XOPEN_SOURCE 	-D_BSD_SOURCE -D_SVID_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 				  				  -DFUNCPROTO=15 -DNARROWPROTO       -c -o resources.o resources.c
x86_64-pc-linux-gnu-gcc -march=native -O2 -pipe -frecord-gcc-switches      -I/usr/include    -Dlinux -D__amd64__ -D_POSIX_C_SOURCE=199309L 				-D_POSIX_SOURCE -D_XOPEN_SOURCE 	-D_BSD_SOURCE -D_SVID_SOURCE                                 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 				  				  -DFUNCPROTO=15 -DNARROWPROTO       -c -o x11-ssh-askpass.o x11-ssh-askpass.c
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdlib.h:25,
                 from resources.c:27:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp]]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
In file included from /usr/include/ctype.h:25,
                 from x11-ssh-askpass.c:37:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp]]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
In file included from /usr/include/bits/libc-header-start.h:33,
                 from /usr/include/stdio.h:27,
                 from dynlist.c:25:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp]]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
In file included from /usr/include/sys/types.h:25,
                 from /usr/include/X11/Xlib.h:38,
                 from /usr/include/X11/Intrinsic.h:53,
                 from drawing.c:18:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wcpp]]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
x11-ssh-askpass.c:71:10: fatal error: SshAskpass_ad.h: No such file or directory
   71 | #include "SshAskpass_ad.h"
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [<builtin>: x11-ssh-askpass.o] Error 1
make: *** Waiting for unfinished jobs....
 * ERROR: net-misc/x11-ssh-askpass-1.2.4.1-r2::gentoo failed (compile phase):
 *   emake failed
```

**Comment by ionenwks** [comment]
Hm odd, I'm not getting this, but looking at how it might happen.

**Comment by ionenwks** [comment]
Hm, please wait a moment before merging, think this can be simplified.

**Comment by ionenwks** [comment]
Yes, I had wrong impression about this one because of other gccmakedep ebuilds. Original `emake includes` was fine. Sorry about this one. This now reverts to previous behavior while keeping only -native-symlinks fixes.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
