### PR TITLE
app-admin/lastpass-binary-component: new package #571280

### PR DESCRIPTION
**Pull request by gktrk**
This is a split off from app-admin/lastpass and only installs the binary
components required by the browser extension, as opposed to installing
the extension too. Beginning with lastpass-4, the upstream only
installs the binary components.

Also, add this package as a blocker for app-admin/lastpass. These two
packages cannot be installed at the same time as that would introduce
file collisions.

Gentoo-Bug: https://bugs.gentoo.org/571280

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by gktrk** [comment]
As requested by @robbat2 in bug 571280.

**Comment by rindeal** [comment]
Why such a long name, wouldn't `lastpass-bin` suffice?

**Comment by idella** [comment]
A pertinent question indeed. gokturk this is set for authority of robbat2 only. Unless or until i get a 'nod 'from him only I / we cannot commit this pull request

**Comment by robbat2** [comment]
I was happy with the -binary-features suffix, as it's NOT a complete package on it's own as is often implied by the `-bin` suffix on a package name.

**Comment by gktrk** [comment]
@rindeal '-bin' typically has a different meaning. think about firefox vs firefox-bin, libreoffice vs. libreoffice-bin etc. Using lastpass-bin would be misleading in that sense. Also, it would give users the false impression that this is a standalone package which is not the case. It is a companion to the browser addon and useless without it. lastpass-binary-features sounds similar to chrome-binary-plugins and also similar in concept.

**Comment by rindeal** [comment]
Ok, got it, `-bin` is out. Though, `-binary-features` is still somewhat misleading as this package doesn't provide any binary features, like converting endianness for example. The official name is _Binary Component_ and I think that's more reasonably descriptive of what this package is all about.

**Comment by robbat2** [comment]
@gktrk @rindeal Would you be happy with `lastpass-binary-component` then? (following the guideline to use the same name as upstream)

**Comment by gktrk** [comment]
I would be ok with the logic of "Installing binary components to enable binary features". The [support page](https://lastpass.com/support.php?cmd=showfaq&id=5576&questiondefault=binary) uses the term "binary component" and the installer script users "software components". I'll refactor for lastpass-binary-component.

**Comment by robbat2** [comment]
Added to tree:
[master cda9963] app-admin/lastpass-binary-component: new package #571280
 Author: Göktürk Yüksek <gokturk@binghamton.edu>
 Date: Mon Apr 4 03:24:00 2016 -0400
 4 files changed, 97 insertions(+), 1 deletion(-)
 create mode 100644 app-admin/lastpass-binary-component/Manifest
 create mode 100644 app-admin/lastpass-binary-component/lastpass-binary-component-4.1.2.ebuild
 create mode 100644 app-admin/lastpass-binary-component/metadata.xml

**Pull request closed without merging**
