### PR TITLE
app-admin/qtpass: version bump to 1.2.3

### PR DESCRIPTION
**Pull request by SpiderX**
Package-Manager: Portage-2.3.40, Repoman-2.3.9

### CODE REVIEW

**Comment by gyakovlev** [comment]
Hi,
what about this bug?
https://bugs.gentoo.org/655896

test still fails.

wanna try using virtualx.eclass? =)

**Comment by a17r** [comment]
It would certainly be nice to get that fixed.

**Comment by gyakovlev** [comment]
just tested that using virtualx requires like 4 line change and tests pass with flying colors, so please include that.

**Comment by SpiderX** [comment]
> wanna try using virtualx.eclass? =)

Never even heard about this eclass.
Very useful and handy. Thanks.

**Comment by gyakovlev** [comment]
looks good,
good job catching that you can remove test from IUSE and not explicitly define VIRTUALX_REQUIRED

Can you squash it? Makes sense to have it in single commit, bumping and fixing the bug at the same time.

**Comment by SpiderX** [comment]
Squashed.

**Comment by gyakovlev** [comment]
tested and pushed, thanks!

**Pull request closed without merging**
