### PR TITLE
gnome-base/gnome-shell, x11-wm/mutter: Bump to 46.4, gnome-extra/gnome-shell-extensions: Bump to 46.2

### PR DESCRIPTION
**Pull request by flint2**
- gnome-base/gnome-shell: Bump to 46.1
- gnome-extra/gnome-shell-extensions: Bump to 46.1
- x11-wm/mutter: Bump to 46.1

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by robszy** [comment]
bump

**Comment by robszy** [comment]
I don't understand why gnome-shell is masked when glib is the problem ?

**Comment by pacho2** [comment]
Because it needs a newer gio version:

gio_req = '>= 2.79.2'

**Comment by robszy** [comment]
Ok so can you add glib in that version to portage ? It will unblock gnome 46 :)

**Comment by flint2** [comment]
> Ok and 2.79.2 have that issue ? It seams yes ;( So we are doomed Is gnome 46 really needs 2.79 ?

Yes since 2.79 glib requires 2 builds, we are not doomed, we will solve the circular dep or explain to the users how to do it, and yes Gnome 46 gnome-shell needs glib 2.79, there are other packages that require it, like nautilus for example.
https://gitlab.gnome.org/GNOME/gnome-shell/-/blob/gnome-46/meson.build?ref_type=heads
```
gio_req = '>= 2.79.2'
```

Please follow up on https://bugs.gentoo.org/937616

Some background for distraction https://youtu.be/H6NQAsb3pkI

**Comment by robszy** [comment]
Thanks for answer !!!

For me I would go with boostrap or building glib without introspection within single build of glib to build glib with introspection. I wouldn't want to rebuild world only to build glib with introspection - it is worst case and we should avoid it.

**Comment by robszy** [comment]
Any news ?

**Pull request closed without merging**
