### PR TITLE
go-env.eclass: niche platform fixes

### PR DESCRIPTION
**Pull request by xen0n**

### CODE REVIEW

**Comment by t-lo** [comment]
Looks good to me, thank you @xen0n for the fix!

**Comment by t-lo** [comment]
Fix was confirmed in the Gentoo bug tracker: https://bugs.gentoo.org/917750#c4

**Comment by thesamesam** [comment]
Thanks, merged. Sorry, I meant to do that last night.

**Comment by t-lo** [comment]
Thank you @thesamesam !

**Pull request closed without merging**
