### PR TITLE
Fix whitespace related QA warnings

### PR DESCRIPTION
**Pull request by doughdemon**
Should remove some noise from the QA reports. The commits touch many packages and don't do any revbumps (even for stable packages).Use 'git show -w' to check that apart from whitespace changes the commits only update copyright years. Also, each commit should be cherry-pickable.Some leading whitespace warnings remain. These could be regarded as false positives.

### CODE REVIEW

**Comment by mgorny** [comment]
The diff looks good and thanks a lot of doing this. Would it be hard for you to split it into per-package commits? You can squash the categories, and go for generic `cat/pkg: whitespace` so that people can clearly see which packages were altered and that there were no changes of significance.

Alternatively, I can try to split those commits when I have some time.

**Comment by doughdemon** [comment]
Thanks for the review!

I'll later squash/split the commits.

**Comment by mgorny** [comment]
Thanks, I'm going to take a look at it and merge it.

**Comment by mgorny** [comment]
And merged!

**Pull request closed without merging**
