### PR TITLE
net-misc/asterisk: prune vulnerable.

### PR DESCRIPTION
**Pull request by jkroonza**
Along with no longer used files/ files.

Bug: https://bugs.gentoo.org/838391
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Jaco Kroon <jaco@uls.co.za>

### CODE REVIEW

**Comment by ajakk** [comment]
Could you split this up into one commit per package?

**Comment by jkroonza** [comment]
> Could you split this up into one commit per package?

I could, but the g729 and opus cannot stand on their own regardless.  Should I also split the different asterisk slots into their own prunes?  Ie, total 5 commits?

**Comment by ajakk** [comment]
Sure, if you think that's necessary

**Comment by jkroonza** [comment]
> Sure, if you think that's necessary

Necessary?  No.  But by the logic of the packages being split into separate remove commits it's also better to handle the different slots in different commits.  Done.

**Review by MatthewGentoo — APPROVED** [review]

**Pull request closed without merging**
