### PR TITLE
app-admin/bitwarden-desktop-bin: Added symlink pointing to /opt/Bitwa…

### PR DESCRIPTION
**Pull request by lima-limon-inc**
…rden/bitwarden

Bug: https://bugs.gentoo.org/909095

### CODE REVIEW

**Comment by lima-limon-inc** [comment]
Kind ping!

**Comment by abdrysdale** [comment]
Any progress on this being merged?

**Comment by lima-limon-inc** [comment]
@kensington What do you think?

**Comment by kensington** [comment]
It's fine by me, but I don't currently have access to my devbox. @mgorny, would you be kind enough to help with merging?

**Comment by dlan17** [comment]
> It's fine by me, but I don't currently have access to my devbox. @mgorny, would you be kind enough to help with merging?

I will take care of this..
@kensington btw, you probably need to check your dev bug (407809) and give response?

**Comment by kensington** [comment]
Thank-you, dlan.

I have an active devaway, but I know how these things go - I can't think of any response I can give that will change the outcome.

**Pull request closed without merging**
