### PR TITLE
games-fps/chocolate-doom: add 3.1.0, drop 3.0.1-r2

### PR DESCRIPTION
**Pull request by Abdulsarhan**
Bug: https://bugs.gentoo.org/937108
Closes: https://bugs.gentoo.org/937108
The patches that were deleted were patches to backport fixes for chocolate-doom-3.0.1-r2. With this version bump, these patches are no longer necessary.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vilhelmgray** [comment]
Reorder your commits to add the 3.1.0 ebuild first, then combine the other two commits as a simple drop of the 3.0.1-r2 and its patches.

**Comment by Abdulsarhan** [comment]
Okay, I did it. It took me a while because I suck at git.

**Review by vilhelmgray — APPROVED** [review]

**Comment by Abdulsarhan** [comment]
Sorry, I am trying to open up another PR at the moment. I pushed to master by mistake. I did fix it.

**Review by vilhelmgray — APPROVED** [review]

**Comment by thesamesam** [comment]
I fixed the commit message to include the PR desc.

**Pull request closed without merging**
