### PR TITLE
update profiles for ayatana USE flag

### PR DESCRIPTION
**Pull request by beatussum**
As said in the title.

### CODE REVIEW

**Comment by beatussum** [comment]
@gentoo/github ping

**Comment by mgorny** [comment]
Could you shortly explain in the commit message why this needs to  be done?

**Comment by beatussum** [comment]
The **ayatana** USE flag depends on two dependencies: _libindicate_ and _libappindicator_. But the keywording of these ebuilds changed since the creation of this USE flag.

**Comment by mgorny** [comment]
Suspected so. Thanks, will merge.

**Pull request closed without merging**
