### PR TITLE
Bump media-sound/podget to version 0.7.12

### PR DESCRIPTION
**Pull request by Kitcat490**
Just a simple version bump, no dependency changes needed.

### CODE REVIEW

**Comment by Coacher** [comment]
0.7.10 should be removed in favor of 0.7.12 as 0.7.12 contains fixes for bugs introduced in 0.7.10.

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by Kitcat490** [comment]
Okay, 0.7.10 removed.

**Comment by Coacher** [comment]
Good.

**Comment by Coacher** [comment]
Please follow Gentoo guidelines for commit messages: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by Coacher** [comment]
`repoman commit` automatically prepends proper CATEGORY/PN for you.

**Comment by monsieurp** [comment]
Please format your commit message: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Pull request closed without merging**
