### PR TITLE
net-misc/sstp-client: Version bump to 2.0.11

### PR DESCRIPTION
**Pull request by mjeveritt**
Package-Manager: Portage-2.3.6, Repoman-2.3.1

### CODE REVIEW

**Comment by mjeveritt** [comment]
Emerge.log and build.log please. Tia.

**Comment by mgorny** [comment]
Enable `FEATURES=network-sandbox test` and see for yourself. Ofc, you should've done that in the first place.

**Comment by mjeveritt** [comment]
@mgorny : funny that, it worked with FEATURES="test".

Perhaps you can point me to the policy document which details what tests a maintainer should be running for his packages ... I appear to have missed it. Either that, or my testing environment is lacking some setting ..
As a QA representative, this should be quite a trivial request ...

**Comment by mgorny** [comment]
https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html

The big section on network access.

Also, please cut your snarky comments. They are not welcome here, or anywhere else in Gentoo, and you have been warned multiple times.

**Comment by mjeveritt** [comment]
> Also, please cut your snarky comments. They are not welcome here, or anywhere else in Gentoo, and you have been warned multiple times.

Funny that .. seems to be par for the course for anyone with an @ .. yourself especially. Perhaps leading a good example might get you a bit further than your normal bullying tactics. Besides, what you gonna do anyway, ComRel me, or just ban me from Github .. and what's that gonna achieve? Nadda, yes.

**Pull request closed without merging**
