### PR TITLE
An ebuild for dev-lang/julia-1.4.2 

### PR DESCRIPTION
**Pull request by xianwenchen**
It works on my amd64 computer. I have been using julia 1.4.2 for a couple of weeks now.

Signed-off-by: Xianwen Chen <x@chen.ac>

### CODE REVIEW

**Comment by xianwenchen** [comment]
Signed-off-by: Xianwen Chen <x@chen.ac>

**Comment by xianwenchen** [comment]
@juippis, could you have a look?

**Comment by juippis** [comment]
It's not my package, nor maintained by projects I'm involved with. So I can't touch it yet. 

You should make a bug and link this PR to that bug using git message tags, 
https://www.gentoo.org/glep/glep-0066.html#commit-messages

And this PR has 3 commits when there should be 1. You need to update the message summary to match our requirements too, see the link above. And sign-off your commits, 
https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

If you commit via `repoman` tool, it can automate the sign-off part to you.

**Comment by xianwenchen** [comment]
Gotcha. Thanks for sharing how it works internally at Gentoo Dev.

**Comment by xianwenchen** [comment]
Do I have to find a way to merge the 3 commits into one?

**Comment by heroxbd** [comment]
> ve to find a way to merge the 3 commits into one?

Use git rebase to squash commits.  Check out https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/ for example.

**Comment by heroxbd** [comment]
> Signed-off-by: Xianwen Chen [x@chen.ac](mailto:x@chen.ac)

This incorrect.  Please study https://www.gentoo.org/glep/glep-0066.html#id9

**Comment by xianwenchen** [comment]
> > ve to find a way to merge the 3 commits into one?
> 
> Use git rebase to squash commits. Check out https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/ for example.

Thanks. I think the webpage that you recommended is for the case, where I have committing privilege to the gentoo portage repository.

I am sending a pull request from a forked gentoo portage repository. I read the webpage and do not think it applies to my case. 

So I don't know what to do now.

**Comment by heroxbd** [comment]
> > > ve to find a way to merge the 3 commits into one?
> > 
> > 
> > Use git rebase to squash commits. Check out https://blog.carbonfive.com/always-squash-and-rebase-your-git-commits/ for example.
> 
> Thanks. I think the webpage that you recommended is for the case, where I have committing privilege to the gentoo portage repository.
> 
> I am sending a pull request from a forked gentoo portage repository. I read the webpage and do not think it applies to my case.
> 
> So I don't know what to do now.

Do the rebase and squash in your forked repository.

**Comment by xianwenchen** [comment]
> Do the rebase and squash in your forked repository.

Thanks for the tip. I tried to follow the webpage, but it didn't work out.

If you have a look at the forked repository here:

https://github.com/xianwenchen/gentoo-portage-fork-xc

How would you suggest me to rebase and create a single commit? Assume that you are working on a terminal emulator on my computer. What git commands would you use?

**Pull request closed without merging**
