### PR TITLE
media-libs/libvmaf: add slotted 3.0.0, update ffmpeg ebuilds

### PR DESCRIPTION
**Pull request by AdelKS**
Rebuild ffmpeg on libvmaf SLOT change

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```diff
--- meson_options.txt
+++ meson_options.txt
@@ -15,7 +15,7 @@ option('enable_asm',
 
 option('enable_avx512',
     type: 'boolean',
-    value: false,
+    value: true,
     description: 'Build AVX-512 asm files, requires nasm 2.14')
 
 option('built_in_models',
@@ -27,3 +27,13 @@ option('enable_float',
     type: 'boolean',
     value: false,
     description: 'Compile floating-point feature extractors into the library')
+
+option('enable_cuda',
+    type: 'boolean',
+    value: false,
+    description: 'Enable CUDA support')
+
+option('enable_nvtx',
+    type: 'boolean',
+    value: false,
+    description: 'Enable NVTX range support')
```
Should we take these options into account?

Just drop the ffmpeg edits - I'll do it while merging. The patch doesn't apply cleanly anymore due to them.

**Comment by AdelKS** [comment]
Sorry for the delay, we could add an `nvidia` useflag if you wish for those new options

**Review by juippis — APPROVED** [review]
Yeah, `nvidia` flag sounds good. Could you figure whether a single flag to enable both option will work in every case, and do a PR adding the use flag?

EDIT: or `cuda`?

**Comment by AdelKS** [comment]
@juippis 
- [NVTX is something else](https://github.com/NVIDIA/NVTX) that doesn't look like is provided by `dev-util/nvidia-cuda-toolkit` so it cannot be merged in the same useflag.
- I tried implementing the `cuda` useflag but I don't know how to make `meson` find the dependency

```
Run-time dependency CUDA (modules: cudart_static, rt, pthread, dl) found: NO (tried system)

../libvmaf-9999/libvmaf/src/meson.build:164:22: ERROR: Dependency "cuda" not found, tried system
```

I need some help. Here's the ebuild patch

```patch
diff --git a/media-libs/libvmaf/libvmaf-9999.ebuild b/media-libs/libvmaf/libvmaf-9999.ebuild
index a5fc3721b828..27db261e3027 100644
--- a/media-libs/libvmaf/libvmaf-9999.ebuild
+++ b/media-libs/libvmaf/libvmaf-9999.ebuild
@@ -3,7 +3,7 @@
 
 EAPI=8
 
-inherit meson-multilib flag-o-matic
+inherit meson-multilib flag-o-matic cuda
 
 DESCRIPTION="C libary for Netflix's Perceptual video quality assessment"
 HOMEPAGE="https://github.com/Netflix/vmaf"
@@ -19,8 +19,8 @@ else
 fi
 
 LICENSE="BSD-2-with-patent"
-SLOT="0"
-IUSE="+embed-models test"
+SLOT="0/3"
+IUSE="+embed-models cuda test"
 
 RESTRICT="!test? ( test )"
 
@@ -29,7 +29,11 @@ BDEPEND="
        embed-models? ( app-editors/vim-core )
 "
 
-RDEPEND="${BDEPEND}"
+DEPEND="
+       cuda? ( dev-util/nvidia-cuda-toolkit )
+"
+
+RDEPEND="${DEPEND}"
 
 if [[ ${PV} == "9999" ]]; then
        S="${WORKDIR}/libvmaf-${PV}"
@@ -49,6 +53,7 @@ multilib_src_configure() {
        local emesonargs=(
                $(meson_use embed-models built_in_models)
                $(meson_use test enable_tests)
+               $(meson_use cuda enable_cuda)
        )
 
        EMESON_SOURCE="${S}/libvmaf"
```

**Comment by juippis** [comment]
I skimmed through https://github.com/Netflix/vmaf/commit/3071d7eeaa055696f8fc3ffbb3f6abb640ed5505 and https://github.com/Netflix/vmaf/blob/master/libvmaf/src/meson.build and looks like cuda can only be enabled with static-libs on. I can't see a clear motivation for adding this support, but let's leave it until someone requests it :)

Thanks for trying it out!

**Comment by AdelKS** [comment]
@juippis thanks for your feedback. [Cuda already got requested](https://bugs.gentoo.org/927296), it didn't take long haha.

**Pull request closed without merging**
