### PR TITLE
dev-libs/libprelude: Fix #611550

### PR DESCRIPTION
**Pull request by ToToL**

### CODE REVIEW

**Comment by kensington** [comment]
``` * QA Notice: command not found:
 * 
 *      /var/tmp/portage/dev-libs/libprelude-3.1.0-r1/temp/environment: line 2935: perl_delete_localpod: command not found
```

This function is provided by ``perl-functions.eclass``, so either that would need to be inherited, or the offending file(s) just removed manually.

**Comment by ToToL** [comment]
Yes, missing prel-module, just fixed it

**Comment by ToToL** [comment]
I don't undestand the QA check, can someone help me ?

**Comment by kentfredric** [comment]
Somebody broke the tree and you're seeing the result in your PR. Rebase after they fix it and the warning will go away.

https://archives.gentoo.org/gentoo-automated-testing/message/9da32ce346aedc82f17a32992bec28bb

**Comment by kentfredric** [comment]
Hold on though, investigating why this problem even happens in the first place, hamlib seemed to be making the mistake of calling "install_site" instead of "install" , which is wrong as far as I can understand.

( default install target does not generate this file, as we have not one, but two mitigations against this bug which this package avoids )

**Comment by kentfredric** [comment]
Looks like this is the root issue, you need to add this line to your econf block:

```bash
		$(use_with perl perl-installdirs vendor) \
```

Not only will that avoid generating the .pod file in the first place, but it will install the .pm files into the correct location in `/usr/lib64/perl5/vendor_perl/` , as opposed to contaminating the perl core directory.

You can keep doing delete_local_pod on top of that, but that's just covering up a symptom of the real problem.

**Comment by ToToL** [comment]
Thanks for the analyse, I include your fix

I prefer to remove the delete_local_pod if this is just covering the issue

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/66d16a6989e...3b105523bb1. Thanks!

**Pull request closed without merging**
