### PR TITLE
Profile cleanup, pt. 2

### PR DESCRIPTION
**Pull request by mgorny**
The second part is removal of `features/*` tree. It currently serves as a common parent for many multilib arches adding a few common bits, and mostly a large piece of irrelevant data for other arches. The goal is for arch profiles to be cleaner and more obvious.

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/amd64

**Comment by mgorny** [comment]
@chewi

**Comment by chewi** [comment]
LGTM.

**Comment by mgorny** [comment]
@gentoo/ppc

**Pull request closed without merging**
