### PR TITLE
media-sound/cmus: verbump to 2.9.1

### PR DESCRIPTION
**Pull request by BouncyMaster**
Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Nicu Borta <nicuborta123@tutanota.com>

### CODE REVIEW

**Comment by n1rdeks** [comment]
guys, please help me to understand, how long time need to update this ebuild? Why gentoo use old version? Where new testing ebuild? Why mergin is blocking? Why mainteiners not response on my mails?

**Comment by fordfrog** [comment]
> guys, please help me to understand, how long time need to update this ebuild? Why gentoo use old version? Where new testing ebuild? Why mergin is blocking? Why mainteiners not response on my mails?

@n1rdeks you know, we're only humans :-)

**Comment by n1rdeks** [comment]
yep, i know, maybe... But how update my favorite player? 2.8v have a memory leak bug and 2.9 have new themes ;) Who don't love themes?

**Comment by fordfrog** [comment]
@BouncyMaster thanks!

**Comment by n1rdeks** [comment]
well done. Thanks.

**Pull request closed without merging**
