### PR TITLE
www-servers/nginx: bump to 1.23.0

### PR DESCRIPTION
**Pull request by hydrapolic**
```sh
--- nginx-1.21.6-r2.ebuild      2022-07-11 13:36:18.011436017 +0000
+++ nginx-1.23.0.ebuild 2022-07-13 04:53:57.571531546 +0000
@@ -1,7 +1,7 @@
 # Copyright 1999-2022 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
+EAPI=8
 
 # Maintainer notes:
 # - http_rewrite-independent pcre-support makes sense for matching locations without an actual rewrite
@@ -29,15 +29,15 @@
 HTTP_BROTLI_MODULE_WD="${WORKDIR}/ngx_brotli-${HTTP_BROTLI_MODULE_PV}"
 
 # http_uploadprogress (https://github.com/masterzen/nginx-upload-progress-module, BSD-2 license)
-HTTP_UPLOAD_PROGRESS_MODULE_PV="0.9.2"
-HTTP_UPLOAD_PROGRESS_MODULE_P="ngx_http_upload_progress-${HTTP_UPLOAD_PROGRESS_MODULE_PV}-r1"
-HTTP_UPLOAD_PROGRESS_MODULE_URI="https://github.com/masterzen/nginx-upload-progress-module/archive/v${HTTP_UPLOAD_PROGRESS_MODULE_PV}.tar.gz"
+HTTP_UPLOAD_PROGRESS_MODULE_PV="68b3ab3b64a0cee7f785d161401c8be357bbed12"
+HTTP_UPLOAD_PROGRESS_MODULE_P="ngx_http_upload_progress-${HTTP_UPLOAD_PROGRESS_MODULE_PV}"
+HTTP_UPLOAD_PROGRESS_MODULE_URI="https://github.com/masterzen/nginx-upload-progress-module/archive/${HTTP_UPLOAD_PROGRESS_MODULE_PV}.tar.gz"
 HTTP_UPLOAD_PROGRESS_MODULE_WD="${WORKDIR}/nginx-upload-progress-module-${HTTP_UPLOAD_PROGRESS_MODULE_PV}"
 
-# http_headers_more (https://github.com/agentzh/headers-more-nginx-module, BSD license)
-HTTP_HEADERS_MORE_MODULE_PV="0.33"
+# http_headers_more (https://github.com/openresty/headers-more-nginx-module, BSD license)
+HTTP_HEADERS_MORE_MODULE_PV="d502e41996d24a382bd9c632e3ae3efa0a5fca66"
 HTTP_HEADERS_MORE_MODULE_P="ngx_http_headers_more-${HTTP_HEADERS_MORE_MODULE_PV}"
-HTTP_HEADERS_MORE_MODULE_URI="https://github.com/agentzh/headers-more-nginx-module/archive/v${HTTP_HEADERS_MORE_MODULE_PV}.tar.gz"
+HTTP_HEADERS_MORE_MODULE_URI="https://github.com/openresty/headers-more-nginx-module/archive/${HTTP_HEADERS_MORE_MODULE_PV}.tar.gz"
 HTTP_HEADERS_MORE_MODULE_WD="${WORKDIR}/headers-more-nginx-module-${HTTP_HEADERS_MORE_MODULE_PV}"
 
 # http_cache_purge (http://labs.frickle.com/nginx_ngx_cache_purge/, https://github.com/FRiCKLE/ngx_cache_purge, BSD-2 license)
@@ -59,9 +59,9 @@
 HTTP_FANCYINDEX_MODULE_WD="${WORKDIR}/ngx-fancyindex-${HTTP_FANCYINDEX_MODULE_PV}"
 
 # http_lua (https://github.com/openresty/lua-nginx-module, BSD license)
-HTTP_LUA_MODULE_PV="0.10.15"
+HTTP_LUA_MODULE_PV="b6d167cf1a93c0c885c28db5a439f2404874cb26"
 HTTP_LUA_MODULE_P="ngx_http_lua-${HTTP_LUA_MODULE_PV}"
-HTTP_LUA_MODULE_URI="https://github.com/openresty/lua-nginx-module/archive/v${HTTP_LUA_MODULE_PV}.tar.gz"
+HTTP_LUA_MODULE_URI="https://github.com/openresty/lua-nginx-module/archive/${HTTP_LUA_MODULE_PV}.tar.gz"
 HTTP_LUA_MODULE_WD="${WORKDIR}/lua-nginx-module-${HTTP_LUA_MODULE_PV}"
 LUA_COMPAT=( luajit )
@@ -113,15 +113,8 @@
 HTTP_ECHO_MODULE_URI="https://github.com/openresty/echo-nginx-module/archive/v${HTTP_ECHO_MODULE_PV}.tar.gz"
 HTTP_ECHO_MODULE_WD="${WORKDIR}/echo-nginx-module-${HTTP_ECHO_MODULE_PV}"
 
-# mod_security for nginx (https://modsecurity.org/, Apache-2.0)
-# keep the MODULE_P here consistent with upstream to avoid tarball duplication
-HTTP_SECURITY_MODULE_PV="2.9.3"
-HTTP_SECURITY_MODULE_P="modsecurity-${HTTP_SECURITY_MODULE_PV}"
-HTTP_SECURITY_MODULE_URI="https://www.modsecurity.org/tarball/${HTTP_SECURITY_MODULE_PV}/${HTTP_SECURITY_MODULE_P}.tar.gz"
-HTTP_SECURITY_MODULE_WD="${WORKDIR}/${HTTP_SECURITY_MODULE_P}"
-
 # push-stream-module (http://www.nginxpushstream.com, https://github.com/wandenberg/nginx-push-stream-module, GPL-3)
-HTTP_PUSH_STREAM_MODULE_PV="0.5.4"
+HTTP_PUSH_STREAM_MODULE_PV="8c02220d484d7848bc8e3a6d9b1c616987e86f66"
 HTTP_PUSH_STREAM_MODULE_P="ngx_http_push_stream-${HTTP_PUSH_STREAM_MODULE_PV}"
 HTTP_PUSH_STREAM_MODULE_URI="https://github.com/wandenberg/nginx-push-stream-module/archive/${HTTP_PUSH_STREAM_MODULE_PV}.tar.gz"
 HTTP_PUSH_STREAM_MODULE_WD="${WORKDIR}/nginx-push-stream-module-${HTTP_PUSH_STREAM_MODULE_PV}"
@@ -157,7 +150,7 @@
 GEOIP2_MODULE_WD="${WORKDIR}/ngx_http_geoip2_module-${GEOIP2_MODULE_PV}"
 
 # njs-module (https://github.com/nginx/njs, as-is)
-NJS_MODULE_PV="0.7.2"
+NJS_MODULE_PV="0.7.5"
 NJS_MODULE_P="njs-${NJS_MODULE_PV}"
 NJS_MODULE_URI="https://github.com/nginx/njs/archive/${NJS_MODULE_PV}.tar.gz"
 NJS_MODULE_WD="${WORKDIR}/njs-${NJS_MODULE_PV}"
@@ -188,7 +181,6 @@
        nginx_modules_http_mogilefs? ( ${HTTP_MOGILEFS_MODULE_URI} -> ${HTTP_MOGILEFS_MODULE_P}.tar.gz )
        nginx_modules_http_naxsi? ( ${HTTP_NAXSI_MODULE_URI} -> ${HTTP_NAXSI_MODULE_P}.tar.gz )
        nginx_modules_http_push_stream? ( ${HTTP_PUSH_STREAM_MODULE_URI} -> ${HTTP_PUSH_STREAM_MODULE_P}.tar.gz )
-       nginx_modules_http_security? ( ${HTTP_SECURITY_MODULE_URI} -> ${HTTP_SECURITY_MODULE_P}.tar.gz )
        nginx_modules_http_slowfs_cache? ( ${HTTP_SLOWFS_CACHE_MODULE_URI} -> ${HTTP_SLOWFS_CACHE_MODULE_P}.tar.gz )
        nginx_modules_http_sticky? ( ${HTTP_STICKY_MODULE_URI} -> ${HTTP_STICKY_MODULE_P}.tar.bz2 )
        nginx_modules_http_upload_progress? ( ${HTTP_UPLOAD_PROGRESS_MODULE_URI} -> ${HTTP_UPLOAD_PROGRESS_MODULE_P}.tar.gz )
@@ -199,11 +191,10 @@
        rtmp? ( ${RTMP_MODULE_URI} -> ${RTMP_MODULE_P}.tar.gz )"
 
 LICENSE="BSD-2 BSD SSLeay MIT GPL-2 GPL-2+
-       nginx_modules_http_security? ( Apache-2.0 )
        nginx_modules_http_push_stream? ( GPL-3 )"
 
 SLOT="mainline"
-KEYWORDS="amd64 arm arm64 ~ppc ~ppc64 ~riscv x86 ~amd64-linux ~x86-linux"
+KEYWORDS="~amd64 ~arm ~arm64 ~ppc ~ppc64 ~riscv ~x86 ~amd64-linux ~x86-linux"

 # Package doesn't provide a real test suite
 RESTRICT="test"
@@ -237,7 +228,6 @@
        http_mogilefs
        http_naxsi
        http_push_stream
-       http_security
        http_slowfs_cache
        http_sticky
        http_upload_progress
@@ -247,7 +237,7 @@
        stream_javascript
 "
 
-IUSE="aio debug +http +http2 +http-cache +ipv6 libatomic +pcre
+IUSE="aio debug +http +http2 +http-cache +ipv6 libatomic pcre +pcre2
        pcre-jit rtmp selinux ssl threads vim-syntax"
 
 for mod in $NGINX_MODULES_STD; do
@@ -283,6 +273,7 @@
        acct-user/nginx
        virtual/libcrypt:=
        pcre? ( dev-libs/libpcre:= )
+       pcre2? ( dev-libs/libpcre2:= )
        pcre-jit? ( dev-libs/libpcre:=[jit] )
        ssl? (
                dev-libs/openssl:0=
@@ -308,13 +299,6 @@
        nginx_modules_http_auth_pam? ( sys-libs/pam )
        nginx_modules_http_metrics? ( dev-libs/yajl:= )
        nginx_modules_http_dav_ext? ( dev-libs/libxml2 )
-       nginx_modules_http_security? (
-               dev-libs/apr:=
-               dev-libs/apr-util:=
-               dev-libs/libxml2:=
-               net-misc/curl
-               www-servers/apache
-       )
        nginx_modules_http_auth_ldap? ( net-nds/openldap:=[ssl?] )
        nginx_modules_stream_geoip? ( dev-libs/geoip )
        nginx_modules_stream_geoip2? ( dev-libs/libmaxminddb:= )"
@@ -324,8 +308,7 @@
 DEPEND="${CDEPEND}
        arm? ( dev-libs/libatomic_ops )
        libatomic? ( dev-libs/libatomic_ops )"
-BDEPEND="nginx_modules_http_brotli? ( virtual/pkgconfig )
-       nginx_modules_http_security? ( ${AUTOTOOLS_DEPEND} )"
+BDEPEND="nginx_modules_http_brotli? ( virtual/pkgconfig )"
 PDEPEND="vim-syntax? ( app-vim/nginx-syntax )"

 REQUIRED_USE="pcre-jit? ( pcre )
@@ -334,11 +317,12 @@
        nginx_modules_http_lua? (
                ${LUA_REQUIRED_USE}
                nginx_modules_http_rewrite
+               pcre
+               !pcre2
        )
        nginx_modules_http_naxsi? ( pcre )
        nginx_modules_http_dav_ext? ( nginx_modules_http_dav nginx_modules_http_xslt )
        nginx_modules_http_metrics? ( nginx_modules_http_stub_status )
-       nginx_modules_http_security? ( pcre )
        nginx_modules_http_push_stream? ( ssl )"
 
 pkg_setup() {
@@ -376,6 +360,12 @@
        eapply "${FILESDIR}/${PN}-1.4.1-fix-perl-install-path.patch"
        eapply "${FILESDIR}/${PN}-httpoxy-mitigation-r1.patch"
 
+       if use nginx_modules_http_sticky; then
+               cd "${HTTP_STICKY_MODULE_WD}" || die
+               eapply "${FILESDIR}"/http_sticky-nginx-1.23.0.patch
+               cd "${S}" || die
+       fi
+
        if use nginx_modules_http_brotli; then
                cd "${HTTP_BROTLI_MODULE_WD}" || die
                eapply "${FILESDIR}"/http_brotli-detect-brotli-r3.patch
@@ -392,23 +382,9 @@
                cd "${S}" || die
        fi
 
-       if use nginx_modules_http_security; then
-               cd "${HTTP_SECURITY_MODULE_WD}" || die
-
-               eautoreconf
-
-               if use nginx_modules_http_lua; then
-                       sed -i \
-                               -e "s|^\(LUA_PKGNAMES\)=.*|\1=\"${ELUA}\"|" \
-                               configure || die
-               fi
-
-               cd "${S}" || die
-       fi
-
        if use nginx_modules_http_upload_progress; then
                cd "${HTTP_UPLOAD_PROGRESS_MODULE_WD}" || die
-               eapply "${FILESDIR}"/http_uploadprogress-issue_50-r1.patch
+               eapply "${FILESDIR}"/http_uploadprogress-nginx-1.23.0.patch
                cd "${S}" || die
        fi

@@ -430,27 +406,13 @@
 }
 
 src_configure() {
-       # mod_security needs to generate nginx/modsecurity/config before including it
-       if use nginx_modules_http_security; then
-               cd "${HTTP_SECURITY_MODULE_WD}" || die
-
-               ./configure \
-                       --enable-standalone-module \
-                       --disable-mlogc \
-                       --with-ssdeep=no \
-                       $(use_enable pcre-jit) \
-                       $(use_with nginx_modules_http_lua lua) || die "configure failed for mod_security"
-
-               cd "${S}" || die
-       fi
-
        local myconf=() http_enabled= mail_enabled= stream_enabled=
 
        use aio       && myconf+=( --with-file-aio )
        use debug     && myconf+=( --with-debug )
        use http2     && myconf+=( --with-http_v2_module )
        use libatomic && myconf+=( --with-libatomic )
-       use pcre      && myconf+=( --with-pcre )
+       use pcre      && myconf+=( --with-pcre --without-pcre2 )
        use pcre-jit  && myconf+=( --with-pcre-jit )
        use threads   && myconf+=( --with-threads )
 
@@ -543,11 +505,6 @@
                myconf+=( --add-module=${HTTP_ECHO_MODULE_WD} )
        fi
 
-       if use nginx_modules_http_security ; then
-               http_enabled=1
-               myconf+=( --add-module=${HTTP_SECURITY_MODULE_WD}/nginx/modsecurity )
-       fi
-
        if use nginx_modules_http_push_stream ; then
                http_enabled=1
                myconf+=( --add-module=${HTTP_PUSH_STREAM_MODULE_WD} )
@@ -689,8 +646,6 @@
 }
 src_compile() {
-       use nginx_modules_http_security && emake -C "${HTTP_SECURITY_MODULE_WD}"
-
        # https://bugs.gentoo.org/286772
        export LANG=C LC_ALL=C
        emake LINK="${CC} ${LDFLAGS}" OTHERLDFLAGS="${LDFLAGS}"
@@ -801,11 +756,6 @@
                dodoc "${HTTP_ECHO_MODULE_WD}"/README.markdown
        fi
 
-       if use nginx_modules_http_security; then
-               docinto ${HTTP_SECURITY_MODULE_P}
-               dodoc "${HTTP_SECURITY_MODULE_WD}"/{CHANGES,README.md,authors.txt}
-       fi
-
        if use nginx_modules_http_push_stream; then
                docinto ${HTTP_PUSH_STREAM_MODULE_P}
                dodoc "${HTTP_PUSH_STREAM_MODULE_WD}"/{AUTHORS,CHANGELOG.textile,README.textile}
```

### CODE REVIEW

**Comment by ConiKost** [comment]
I have a try, but compilation fails for me.

```
x86_64-pc-linux-gnu-gcc -c -march=native -mfpmath=sse,387 -mtune=intel -O3 -frecord-gcc-switches -fomit-frame-pointer -malign-data=abi -mtls-dialect=gnu2 -pipe -I/usr/include -Wno-deprecated-declarations  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /var/tmp/portage/www-servers/nginx-1.23.0/work/ngx_metrics-0.1.1/src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-rtmp-module-1.2.1 -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../build -I /usr/include -I src/mail -I src/stream -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../build \
        -o objs/addon/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.o \
        /var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c
/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c: In function 'ngx_http_reportuploads_handler':
/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c:640:39: error: 'r->headers_out.cache_control' is a pointer; did you mean to use '->'?
  640 |     ccp = r->headers_out.cache_control.elts;
      |                                       ^
      |                                       ->
/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c:643:28: warning: passing argument 1 of 'ngx_array_init' from incompatible pointer type [-Wincompatible-pointer-types]
  643 |         if (ngx_array_init(&r->headers_out.cache_control, r->pool,
      |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                            |
      |                            ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
In file included from src/core/ngx_core.h:65,
                 from /var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c:8:
src/core/ngx_array.h:32:29: note: expected 'ngx_array_t *' but argument is of type 'ngx_table_elt_t **' {aka 'struct ngx_table_elt_s **'}
   32 | ngx_array_init(ngx_array_t *array, ngx_pool_t *pool, ngx_uint_t n, size_t size)
      |                ~~~~~~~~~~~~~^~~~~
/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c:649:30: warning: passing argument 1 of 'ngx_array_push' from incompatible pointer type [-Wincompatible-pointer-types]
  649 |         ccp = ngx_array_push(&r->headers_out.cache_control);
      |                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                              |
      |                              ngx_table_elt_t ** {aka struct ngx_table_elt_s **}
src/core/ngx_array.h:27:35: note: expected 'ngx_array_t *' but argument is of type 'ngx_table_elt_t **' {aka 'struct ngx_table_elt_s **'}
   27 | void *ngx_array_push(ngx_array_t *a);
      |                      ~~~~~~~~~~~~~^
/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.c:666:53: error: 'r->headers_out.cache_control' is a pointer; did you mean to use '->'?
  666 |         for (i = 1; i < r->headers_out.cache_control.nelts; i++) {
      |                                                     ^
      |                                                     ->
make[1]: *** [objs/Makefile:1802: objs/addon/nginx-upload-progress-module-0.9.2/ngx_http_uploadprogress_module.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'
make: *** [Makefile:10: build] Error 2
 * ERROR: www-servers/nginx-1.23.0::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=www-servers/nginx-1.23.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=www-servers/nginx-1.23.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/www-servers/nginx-1.23.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-servers/nginx-1.23.0/temp/environment'.
 * Working directory: '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'
 * S: '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'
```

**Comment by ConiKost** [comment]
Since nginx-1.23 breaks API, more external modules fail.

```
x86_64-pc-linux-gnu-gcc -c -march=native -mfpmath=sse,387 -mtune=intel -O3 -frecord-gcc-switches -fomit-frame-pointer -malign-data=abi -mtls-dialect=gnu2 -pipe -I/usr/include -Wno-deprecated-declarations  -I src/core -I src/event -I src/event/modules -I src/os/unix -I /var/tmp/portage/www-servers/nginx-1.23.0/work/ngx_metrics-0.1.1/src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-rtmp-module-1.2.1 -I /usr/include/libxml2 -I objs -I src/http -I src/http/modules -I src/http/v2 -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../build -I /usr/include -I src/mail -I src/stream -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../src -I /var/tmp/portage/www-servers/nginx-1.23.0/work/njs-0.7.5/nginx/../build \
        -o objs/addon/nginx-rtmp-module-1.2.1/ngx_rtmp_init.o \
        /var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-rtmp-module-1.2.1/ngx_rtmp_init.c
In file included from /usr/include/dlfcn.h:24,
                 from src/os/unix/ngx_linux_config.h:58,
                 from src/core/ngx_config.h:26,
                 from /var/tmp/portage/www-servers/nginx-1.23.0/work/headers-more-nginx-module-0.33/src/ddebug.h:5,
                 from /var/tmp/portage/www-servers/nginx-1.23.0/work/headers-more-nginx-module-0.33/src/ngx_http_headers_more_headers_in.c:10:
/var/tmp/portage/www-servers/nginx-1.23.0/work/headers-more-nginx-module-0.33/src/ngx_http_headers_more_headers_in.c:162:50: error: 'ngx_http_headers_in_t' has no member named 'cookies'; did you mean 'cookie'?
  162 |                  offsetof(ngx_http_headers_in_t, cookies),
      |                                                  ^~~~~~~
make[1]: *** [objs/Makefile:1823: objs/addon/src/ngx_http_headers_more_headers_in.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'
make: *** [Makefile:10: build] Error 2
 * ERROR: www-servers/nginx-1.23.0::gentoo failed (compile phase):
 *   emake failed
 *
 * If you need support, post the output of `emerge --info '=www-servers/nginx-1.23.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=www-servers/nginx-1.23.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/www-servers/nginx-1.23.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/www-servers/nginx-1.23.0/temp/environment'.
 * Working directory: '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'
 * S: '/var/tmp/portage/www-servers/nginx-1.23.0/work/nginx-1.23.0'

```

Fix:
https://github.com/openresty/headers-more-nginx-module/commit/e536bc595d8b490dbc9cf5999ec48fca3f488632
https://github.com/openresty/headers-more-nginx-module/commit/91eb0db9ef9ac05c4c514b8f1fdf8a8170cc354e

**Comment by hydrapolic** [comment]
Yeah, I got some failures too (headers-more for example), but the latest release is old anyway.
I would add it to portage and fix with new revisions as nginx core works fine.

**Comment by ConiKost** [comment]
> I would add it to portage and fix with new revisions as nginx core works fine.

Please test, which external modules do not work and mask them at least. That would be fine, so we can work on it afterwards.

**Comment by hydrapolic** [comment]
Pushed an update @ConiKost, now all should build.

Security got removed as it's unsupported anyway and fails to build. We should migrate to modsec3.
Lua only builds with legacy pcre, but nginx enables pcre2 by default.

**Comment by ajakk** [comment]
Thank you for working on this! If you're interested, do you have any opinion on https://github.com/gentoo/gentoo/pull/16053?

**Review by ConiKost — APPROVED** [review]
lgtm

**Pull request closed without merging**
