### PR TITLE
www-servers/lighttpd: cleaned up config files

### PR DESCRIPTION
**Pull request by drylemon**
removed vim config from the default config files
as well as some trailing whitespace on a few lines.

Package-Manager: Portage-2.3.76, Repoman-2.3.17

### CODE REVIEW

**Comment by drylemon** [comment]
anybody want to merge this?

**Comment by ajakk** [comment]
@herbmillerjr What do you think?

**Comment by herbmillerjr** [comment]
@ajakk Makes sense to me.

**Comment by ajakk** [comment]
@drylemon we will need a signoff as gentoo-bot reported.

**Comment by ajakk** [comment]
Ping.

**Comment by ajakk** [comment]
We still cannot merge without a proper signoff.

**Comment by drylemon** [comment]
@ajakk my bad, I am struggling to figure out how to add the signoff to an old commit

**Comment by ajakk** [comment]
Ah, you need to rebase. Something like `git rebase -i HEAD^^`, mark the commit for editing, exit your editor, then follow the prompts. In your case you want `git commit -as` to edit the commit message

**Comment by drylemon** [comment]
well, shit. The interactive rebase told me to make my changes, then run `git rebase --continue`. looks like I rebased 250K commits...

**Comment by drylemon** [comment]
I appreciate you being patient and helping, but at this point my pull request is probably not worth it for some formatting changes, I'll be closing it.

**Comment by ajakk** [comment]
If you're still interested, you might try adding the changes on top of current master to make things easier. Feel free to make a new PR!

**Pull request closed without merging**
