### PR TITLE
net-libs/nodejs: Security cleanup (bug #625562)

### PR DESCRIPTION
**Pull request by Whissi**
Testing security cleanup of old nodjs-0.x version.

### CODE REVIEW

**Comment by Whissi** [comment]
Got maintainer ACK by @patricklauer via IRC.

We will merge when we do the cleanup for https://bugs.gentoo.org/625562.

**Comment by mgorny** [comment]
I'm going to test assignment script on this one, please don't panic.

**Comment by mgorny** [comment]
Ok, thanks ;-).

**Comment by flappyports** [comment]
0.12.17 is already gone from the tree.

**Pull request closed without merging**
