### PR TITLE
games-action/prismlauncher: new package

### PR DESCRIPTION
**Pull request by flowln**
Following [the conversation about the PolyMC hijacking](https://bugs.gentoo.org/877495):

This is a fork of PolyMC (`games-action/polymc`) made by the previous maintainers that got thrown off by one of the other maintainers in a hostile takeover. Being a new fork, the ebuilds are based on the previous live ebuild from polymc, with the following changes made to the package:
- Since the last stable release of PolyMC, one more submodule was added, and we have a version of it in the `::gentoo` repository (`dev-cpp/gulrak-filesystem`). So, I've added it to `BDEPEND` and left it out of the submodules list, like what was done with quazip. I tested unmerging it afterwards, and there was no problem with Prism, so there's no linking dependency after.
- I've removed Carson Rueter from the maintainers list, considering he seems to be aligned with LennyMcLennington, the maintainer that hijacked PolyMC. If this is a mistake, please come forwards.

There may also be some problems if trying to emerge PrismLauncher with PolyMC installed, due to them installing the same JAR files in the same locations. I'm not sure what to do here, should I add something to `RESTRICT`?

If this gets added to the tree, I'm also planning to request for `~arm64` keywording on Bugzilla, since the release has added support for it (no arm32 yet though, because [there seems to be some issues going on atm](https://github.com/PrismLauncher/PrismLauncher/issues/128)). If anyone can point me to what exactly I need to do for that, I'd be very grateful. :grin: 

Thank you!

### CODE REVIEW

**Comment by thesamesam** [comment]
> Following [the conversation about the PolyMC hijacking](https://bugs.gentoo.org/877495):
> 
> This is a fork of PolyMC (`games-action/polymc`) made by the previous maintainers that got thrown off by one of the other maintainers in a hostile takeover. Being a new fork, the ebuilds are based on the previous live ebuild from polymc, with the following changes made to the package:
> 
>     * Since the last stable release of PolyMC, one more submodule was added, and we have a version of it in the `::gentoo` repository (`dev-cpp/gulrak-filesystem`). So, I've added it to `BDEPEND` and left it out of the submodules list, like what was done with quazip. I tested unmerging it afterwards, and there was no problem with Prism, so there's no linking dependency after.
> 
>     * I've removed Carson Rueter from the maintainers list, considering he seems to be aligned with LennyMcLennington, the maintainer that hijacked PolyMC. If this is a mistake, please come forwards.
> 
> 
> There may also be some problems if trying to emerge PrismLauncher with PolyMC installed, due to them installing the same JAR files in the same locations. I'm not sure what to do here, should I add something to `RESTRICT`?
> 

I've added a runtime blocker on polymc. I guess we may need one for polymc-bin to be polite to GURU users?
 
> If this gets added to the tree, I'm also planning to request for `~arm64` keywording on Bugzilla, since the release has added support for it (no arm32 yet though, because [there seems to be some issues going on atm](https://github.com/PrismLauncher/PrismLauncher/issues/128)). If anyone can point me to what exactly I need to do for that, I'd be very grateful. 😁

File a bug in Gentoo Linux -> Keywording. In package list, put "games-action/prismlauncher ~arm64", and add CC-ARCHES to the KEYWORDS field.

Yeah, definitely sounds like we should avoid arm for now.

> Thank you!

**Comment by thesamesam** [comment]
Thanks!

**Comment by AndrewAmmerlaan** [comment]
Thank you @flowln (and others) for your fast reaction and solution to this unfortunate situation.

**Comment by DioEgizio** [comment]
should work on x86 but Minecraft itself (1.13+) won't run

**Pull request closed without merging**
