### PR TITLE
x11-drivers/ati-drivers: Fix compile and runtime errors. Bugs #548118 and #542320

### PR DESCRIPTION
**Pull request by fernando-rodriguez**
Adds patches to fix bugs #542320 and #548118 without using GPL kernel exports.

### CODE REVIEW

**Comment by jlec** [comment]
Could you please squash your commits and set a commit message in following form

```
x11-drivers/ati-drivers: Explain shortly what the change does

Long message

Gentoo-Bugs: full url or bug No
``

**Comment by fernando-rodriguez** [comment]
Sorry, I looked at the top of the log and saw oneliners so I followed suit (makes sense since they where bumps and minor changes).

Should I really squash them or just reword the messages? The issues that they fix are not really related. I put them on the same PR because the package does not work at all (except when compiled against quite dated kernels) without the first so the 2nd doesn't solve anything on it's own.

**Comment by jlec** [comment]
You can do both. Just write the actual effect of the patch and add the Gentoo-Bug reference in a single line for each bug.

**Comment by fernando-rodriguez** [comment]
Done as requested.

**Comment by idella** [comment]
Also the ebuild has RESTRICT="bindist test fetch". Wonder if you can acquire the fetch restricted tarball then allow me to d'load it externally then I can runtest.

**Comment by fernando-rodriguez** [comment]
I will work on your suggestions this evening, but note that except for the patch names none of that is my work, I merely added the patches. What do you find questionable about the MODULE_NAMES? If it's the 2.6.x, that's on upstream. I suppose for historical reasons.

I will go with your suggestion on patch naming. I usually go for just a ${PN} prefix because they will likely be applied to future versions and I've only added the version when I had to rebase it for a specific release. The dont-use-gpl-symbols one was just lazyness :) 

I did noticed the fetch instructions for the zip file are wrong (also not my work) and meant to correct it but forgot. I think it just changed on the last version, they're supposed to be:

http://support.amd.com/en-us/download/desktop?os=Linux+x86
http://developer.amd.com/wordpress/media/2012/10/xvba-sdk-0.74-404001.tar.gz

Also know you will get a few compile warnings (between 1 and 3 depending on kernel version). They don't come from my patches. I could easily fix them but I tried to keep the patches to the minimum necessary to fix the actual problems.

**Comment by mgorny** [comment]
@gentoo/x11 @gentoo/proxy-maint. If someone could check if jekarlson is on github, I'd appreciate.

**Comment by fernando-rodriguez** [comment]
I don't know if it's a glitch or the comment was deleted as I didn't even get an email about it. But there was a comment by @idella suggesting some changes. I made the changes but now the record of why I did it is gone...

**Comment by idella** [comment]
@fernando-rodriguez 
_but note that except for the patch names none of that is my work, I merely added the patches_
fine don't be concerned.  Naming patches is purely a stylistic element, so this amounts to nothing more than matching gentoo's style of nomenclature.

**Comment by fernando-rodriguez** [comment]
> Fine don't be concerned. Naming patches is purely a stylistic element, so this amounts to nothing > more than matching gentoo's style of nomenclature.

I was refering to the other suggestions, the patches are part of my work of course. I did follow all your suggestions but I had never even looked at the ebuild code, I just scrolled down to src_prepapre() and added the patches. I also was asked by the developer that did the bump to add the patches for this version so that's all I did, he may find it rude that I stepped all over his work and the reason why it's gone from the PR history.

> Here is the 1st. line form the fail by the qa-report.

If I'm deciphering the qa-report correctly the package with the broken dep is dev-util/nvidia-cuda-toolkit so I ignored the failure.

**Comment by fernando-rodriguez** [comment]
Added another patch for linux 4.3-rc1

**Comment by mgorny** [comment]
Yes, the reported failure is irrelevant.

@idella, could you @-highlight him?

**Comment by idella** [comment]
@jkarlson
I gather you have done all requested by that developer.  The reporting of dev-util/nvidia-cuda-toolkit  can be overlooked

**Comment by fernando-rodriguez** [comment]
> I gather you have done all requested by that developer

Never spoke with jekarlson. The bump was done by @mrueg and he told me submit this PR.

**Comment by idella** [comment]
commit 3ee13140db47e37adf0a0c7fb88c094a39cf1a83
Author: Ian Delaney <idella4@gentoo.org>
Date:   Wed Sep 23 17:20:32 2015 +0800

    x11-drivers/ati-drivers: revbump required to ati-drivers-15.9-r1
    
    of the ati-drivers-15.9.ebuild prepared by fernando-rodriguez
    in /gentoo/pull/98
    
    Package-Manager: portage-2.2.20.1

commit 6913a35966d89d28ed6208ab9a58c20fd8a80396
Author: Fernando Rodriguez <frodriguez.developer@outlook.com>
Date:   Wed Sep 16 18:24:47 2015 -0400

    x11-drivers/ati-drivers: Fix compile errors and preemption bug
    
    Ebuild cleanup and patches to compile against recent kernels by
    replacing calls that use GPL'd kernel symbols with our own
    implementation and several others to fix compile errors caused
    by API changes on recent kernels.
    
    Also adds patch to disable preemption before calling certain
    kernel functions that trigger the following error:
    
    BUG: using smp_processor_id() in preemptible [00000000] code:firegl/3657
    
    Gentoo-Bug: 548118
    Gentoo-Bug: 542320

It is established fernando-rodriguez is content to contribute without being a proxy maintainer

**Pull request closed without merging**
