### PR TITLE
dev-python/elasticsearch-curator: bump to 4.0.6, drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint @patricklauer

**Comment by hydrapolic** [comment]
@gktrk - @patricklauer ignores github :)

**Comment by gktrk** [comment]
pinged him on #gentoo-dev

**Comment by hydrapolic** [comment]
Thanks for merging! :)

**Pull request closed without merging**
