### PR TITLE
verify-sig.eclass: Handle SHA512 checksums

### PR DESCRIPTION
**Pull request by jpds**
Needed as weechat.org only publish these.

### CODE REVIEW

**Comment by mgorny** [comment]
Could you include the weechat update here as well?

**Comment by jpds** [comment]
@mgorny I was going to stick at onto #24580 after a rebase (wasn't sure how to do this change there without it not being visible).

**Comment by mgorny** [comment]
I don't really understand. Feel free to add the eclass change there and just ping me. I'd like to test it before approving (even though it looks obviously correct).

**Comment by thesamesam** [comment]
Are we still doing this (see: https://github.com/gentoo/gentoo/pull/24580#discussion_r827397504). We've merged #24580.

**Comment by mgorny** [comment]
This is trivial, so let's return to it when we have a real test case.

**Comment by mgorny** [comment]
(no offense meant to the OP)

**Pull request closed without merging**
