### PR TITLE
Unbundle chrome-sandbox

### PR DESCRIPTION
**Pull request by floppym**

### CODE REVIEW

**Comment by scardracs** [comment]
Every electron-based apps use chrome-sandbox. I'm wondering if that change can be ported to them too

**Review by ulm — COMMENTED** [review]
Looks good.

I only wonder about the `www-misc` category. Maybe `sys-apps` would be a better fit, where tools like sandbox and bubblewrap are located?

**Comment by floppym** [comment]
`sys-apps` is described in metadata.xml as having "core system applications". I wouldn't classify chrome-sandbox as "core system".

I picked `www-misc` because it isn't really a standalone web application (www-apps or www-client), but it is tightly coupled with various www-related apps/clients. It would fit in `net-misc` with the same rationale.

It could also fit in `app-containers`, since acts like a container manager: it creates a new PID namespace and calls chroot to isolate a child process.

**Comment by ulm** [comment]
I don't have a very strong opinion, but I like `app-containers`.

**Comment by floppym** [comment]
I changed the install path to `/usr/libexec/chrome-sandbox`; there's no reason for users to run it directly from PATH.

**Comment by floppym** [comment]
Closing after discussion in #gentoo-dev.

**Pull request closed without merging**
