### PR TITLE
qmail.eclass: hide qmail-pop3 behind a use flag

### PR DESCRIPTION
**Pull request by DerDakon**
Other solutions offer much more features and better security, so do not install this by default. Keep it for the moment for those who explicitely want it.

See: https://archives.gentoo.org/gentoo-dev/message/7c6e06b10d40d8f7f9a2564d8c41e319

### CODE REVIEW

**Comment by DerDakon** [comment]
[WIP] I'll do a full sweep with tatt later today, just for review at the moment.

**Comment by juippis** [comment]
LGTM, how did your test run fare?

@mgorny any notes about the eclass change? I saw `$GROUP_ROOT` doesn't have curly brackets, but it's like that in the eclass already and seems to work in a command. Not sure what is the right way though.

**Comment by mgorny** [comment]
Curly braces for everyone would be nice but whatever.

**Comment by DerDakon** [comment]
I'm still battling with the openssl update in my test chroot, hopefully I'll get that sorted out during the rest of the day.

**Comment by DerDakon** [comment]
test builds look good

**Comment by DerDakon** [comment]
curly braces are there.

**Pull request closed without merging**
