### PR TITLE
dev-java/tomcat-native: add 2.0.3

### PR DESCRIPTION
**Pull request by vaukai**
@fordfrog 
from the [build.log](https://github.com/gentoo/gentoo/files/10758142/build.log.txt):

```
Property "test.failonerror" has not been set
```
Shouldn't the `eclass` default to setting this property?

And 
```
    [junit] Couldn't find org/apache/tools/ant/taskdefs/optional/junit/JUnit4TestMethodAdapter.class
```
This should get fixed once `dev-libs/openssl:0/3`  goes stable.
```

### CODE REVIEW

**Comment by fordfrog** [comment]
> @fordfrog from the [build.log](https://github.com/gentoo/gentoo/files/10758142/build.log.txt):
> 
> ```
> Property "test.failonerror" has not been set
> ```
> 
> Shouldn't the `eclass` default to setting this property?

i don't think this is a standard ant variable, this should be set in the ebuild instead.

**Comment by vaukai** [comment]
> i don't think this is a standard ant variable, this should be set in the ebuild instead.

Sure, found it in `build.xml`.  If staying with `java-ant-2` would need to get some lessons about voodoo on `build.xml`.  At least, dependencies would need to get changed to 

```
-       test? ( dev-java/ant-junit:0 )"
+       test? (
+               dev-java/ant-junit4:0
+               dev-java/junit:4
+       )
```
There is only [one test](https://github.com/apache/tomcat-native/blob/2.0.3/test/org/apache/tomcat/jni/TesterSSL.java)  which hangs (forever?) with the `java-pkg-simple` version shown here.  Maybe would hang also if I figured out how to handle that `build.xml` stuff.

**Comment by fordfrog** [comment]
> There is only [one test](https://github.com/apache/tomcat-native/blob/2.0.3/test/org/apache/tomcat/jni/TesterSSL.java) which hangs (forever?) with the `java-pkg-simple` version shown here. Maybe would hang also if I figured out how to handle that `build.xml` stuff.

nah, it does not hang forever i guess. it tests memory leaks and hence runs 10 million times in a loop some ssl code, so it probably takes quite some time to finish. to verify that, you can try to decrease the loop to [`100`](https://github.com/apache/tomcat-native/blob/2.0.3/test/org/apache/tomcat/jni/TesterSSL.java#L38) and see if the test finishes. imo it should.

**Comment by vaukai** [comment]
@fordfrog 
from my point of view it's ready to merge:
```
Time: 237.588
OK (1 test)
```

**Comment by fordfrog** [comment]
> @fordfrog from my point of view it's ready to merge:
> 
> ```
> Time: 237.588
> OK (1 test)
> ```

cool, thanks!

**Pull request closed without merging**
