### PR TITLE
www-client/chromium: add 114.0.5735.110

### PR DESCRIPTION
**Pull request by Kangie**
I had a go at bumping this ebuild after the recent update in -dev.

Good news: I can prepare and compile the source (with GCC 13!) and the installed binary works.

Bad news: I didn't ccache and forgot to run tests so that's going to be another 6+ hours away.

Add myself as a maintainer; I'll be a backup - @jeffgazso has more desire to maintain this package ongoing but I got to this bump first.

@thesamesam @floppym: Do you have any feedback at this stage? In particular, are there any distros whose packaging would be worth eyeballing to catch any required patches / regressions?

I'm not super happy with rming ~4/5 of the gcc13 patches; it might be better to just specify the 5 that we want to run or cut a new patch tarball. I strongly dislike the concept of storing patches on a random git repository that I control so if we want to go with the latter approach I might get one of you stash one in a dev space.

For posterity these are the only required patches for 114:

* `chromium-112-gcc-13-0001-openscreen.patch`
* `chromium-112-gcc-13-0003-ruy.patch`
* `chromium-112-gcc-13-0005-tensorflow-tflite.patch`
* `chromium-112-gcc-13-0006-vulkanmemoryallocator.patch`
* `chromium-112-gcc-13-0014-maldoca.patch`

Also, is the following still valid? I'm on Nvidia GPU and Wayland and everything seems fine for now.

> * Proprietary nVidia driver does not work with Wayland. You can disable
> * Wayland by setting DISABLE_OZONE_PLATFORM=true in /etc/chromium/default.

### CODE REVIEW

**Comment by floppym** [comment]
Thanks for the PR!

> Add myself as a maintainer; I'll be a backup - @jeffgazso has more desire to maintain this package ongoing but I got to this bump first.

Please drop proxy-maint from the maintainers. I think it would be best if someone familiar with the ebuild reviews PRs for now.

> @thesamesam @floppym: Do you have any feedback at this stage? In particular, are there any distros whose packaging would be worth eyeballing to catch any required patches / regressions?

I'm not sure, but I would imagine that Debian, Ubuntu, and Arch would be good candidates for reference.

> I'm not super happy with rming ~4/5 of the gcc13 patches; it might be better to just specify the 5 that we want to run or cut a new patch tarball. I strongly dislike the concept of storing patches on a random git repository that I control so if we want to go with the latter approach I might get one of you stash one in a dev space.

Yeah, I was feeling lazy and didn't roll a new tarball when adding 113. The patches in sam's tarball should become fully obsolete within a few major versions, so it isn't a permanent issue.

> Also, is the following still valid? I'm on Nvidia GPU and Wayland and everything seems fine for now.
>
> > * Proprietary nVidia driver does not work with Wayland. You can disable
> > * Wayland by setting DISABLE_OZONE_PLATFORM=true in /etc/chromium/default.

Please feel free to drop the warning if you think it no longer applies. We can always restore it later if necessary.

**Comment by thesamesam** [comment]
> > @thesamesam @floppym: Do you have any feedback at this stage? In particular, are there any distros whose packaging would be worth eyeballing to catch any required patches / regressions?
> 
> I'm not sure, but I would imagine that Debian, Ubuntu, and Arch would be good candidates for reference.
> 

Alpine as well.

> > I'm not super happy with rming ~4/5 of the gcc13 patches; it might be better to just specify the 5 that we want to run or cut a new patch tarball. I strongly dislike the concept of storing patches on a random git repository that I control so if we want to go with the latter approach I might get one of you stash one in a dev space.
> 
> Yeah, I was feeling lazy and didn't roll a new tarball when adding 113. The patches in sam's tarball should become fully obsolete within a few major versions, so it isn't a permanent issue.

We should probably import sultan's chromium-patches repo into somewhere on infra and just use that going forward. But the hack here is fine for this one time, I'd say.

**Comment by thesamesam** [comment]
Also, could you check if the patches in https://bugs.gentoo.org/906911 and https://bugs.gentoo.org/906962 are in this version? It'd be a shame to have to revbump again for them if they're not.

**Comment by juippis** [comment]
Looks like you're missing rust BDEP dependency, 
```
ERROR at //build/config/rust.gni:143:22: Script returned non-zero exit code.
    rustc_revision = exec_script("//tools/rust/update_rust.py",
                     ^----------
Current dir: /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/out/Release/
Command: python3.11 /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/tools/rust/update_rust.py --     print-package-version
Returned 1 and printed out:
 
The expected Rust version is 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-3 (or fallback                 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-1 but the actual version is None
Did you run "gclient sync"?

See //BUILD.gn:17:1: whence it was imported.
import("//build/config/rust.gni")
^-------------------------------
 * ERROR: www-client/chromium-114.0.5735.110::gentoo failed (configure phase):
 *   (no error message)
```

With rust-bin-1.69.0 installed I chromium builds fine with **default** use flags:
`>>> Completed (1 of 1) www-client/chromium-114.0.5735.110::gentoo`


I think this is `+lto` or `+libcxx` related, I get:
```
ld.lld: error: -mllvm: ld.lld: Unknown command line argument '-disable-auto-upgrade-debug-info'.  Try: '/usr/lib/llvm/16/bin/ld.lld --help'
ld.lld: Did you mean '--disable-auto-paired-vec-st'?
x86_64-pc-linux-gnu-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```
With
 * USE:        X abi_x86_64 amd64 elibc_glibc gtk4 kernel_linux l10n_fi l10n_sv libcxx lto official pax-kernel pic pulseaudio suid system-harfbuzz system-png

I will keep testing in the background but it takes like 2 hours to compile this

**Comment by Kangie** [comment]
> I will keep testing in the background but it takes like 2 hours to compile this

hahaha.  5 hours here.

Good catch on the rust bdep; fixed.

Bad news, I'd heard about this but thought it was a later release - chromium now requires an unreleased llvm to build. We've reverted the patch for now, but longer term it's probably better to just build a separate llvm for chromium to prevent "fun" like this again.

**Comment by stha09** [comment]
> Looks like you're missing rust BDEP dependency,
> 
> ```
> ERROR at //build/config/rust.gni:143:22: Script returned non-zero exit code.
>     rustc_revision = exec_script("//tools/rust/update_rust.py",
>                      ^----------
> Current dir: /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/out/Release/
> Command: python3.11 /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/tools/rust/update_rust.py --     print-package-version
> Returned 1 and printed out:
>  
> The expected Rust version is 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-3 (or fallback                 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-1 but the actual version is None
> Did you run "gclient sync"?
> 
> See //BUILD.gn:17:1: whence it was imported.
> import("//build/config/rust.gni")
> ^-------------------------------
>  * ERROR: www-client/chromium-114.0.5735.110::gentoo failed (configure phase):
>  *   (no error message)
> ```
> 
> With rust-bin-1.69.0 installed I chromium builds fine with **default** use flags: `>>> Completed (1 of 1) www-client/chromium-114.0.5735.110::gentoo`
> 
> I think this is `+lto` or `+libcxx` related, I get:
> 
> ```
> ld.lld: error: -mllvm: ld.lld: Unknown command line argument '-disable-auto-upgrade-debug-info'.  Try: '/usr/lib/llvm/16/bin/ld.lld --help'
> ld.lld: Did you mean '--disable-auto-paired-vec-st'?
> x86_64-pc-linux-gnu-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> ```
> 
> With
> 
> * USE:        X abi_x86_64 amd64 elibc_glibc gtk4 kernel_linux l10n_fi l10n_sv libcxx lto official pax-kernel pic pulseaudio suid system-harfbuzz system-png
> 
> I will keep testing in the background but it takes like 2 hours to compile this

Just --enable_rust=false for the moment. Rust is only used for testing.

**Comment by stha09** [comment]
> disable-auto-upgrade-debug-info

You need to update the compiler patch and drop this one:
https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/build/config/compiler/BUILD.gn#768

Compiling in less an hour here ;)

**Comment by Kangie** [comment]
> > disable-auto-upgrade-debug-info
> 
> You need to update the compiler patch and drop this one: https://chromium.googlesource.com/chromium/src.git/+/refs/heads/main/build/config/compiler/BUILD.gn#768

I think I covered that in the llvm patch

> 



> > Looks like you're missing rust BDEP dependency,
> > ```
> > ERROR at //build/config/rust.gni:143:22: Script returned non-zero exit code.
> >     rustc_revision = exec_script("//tools/rust/update_rust.py",
> >                      ^----------
> > Current dir: /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/out/Release/
> > Command: python3.11 /var/tmp/portage/www-client/chromium-114.0.5735.110/work/chromium-114.0.5735.110/tools/rust/update_rust.py --     print-package-version
> > Returned 1 and printed out:
> >  
> > The expected Rust version is 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-3 (or fallback                 17c11672167827b0dd92c88ef69f24346d1286dd-1-llvmorg-17-init-8029-g27f27d15-1 but the actual version is None
> > Did you run "gclient sync"?
> > 
> > See //BUILD.gn:17:1: whence it was imported.
> > import("//build/config/rust.gni")
> > ^-------------------------------
> >  * ERROR: www-client/chromium-114.0.5735.110::gentoo failed (configure phase):
> >  *   (no error message)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With rust-bin-1.69.0 installed I chromium builds fine with **default** use flags: `>>> Completed (1 of 1) www-client/chromium-114.0.5735.110::gentoo`
> > I think this is `+lto` or `+libcxx` related, I get:
> > ```
> > ld.lld: error: -mllvm: ld.lld: Unknown command line argument '-disable-auto-upgrade-debug-info'.  Try: '/usr/lib/llvm/16/bin/ld.lld --help'
> > ld.lld: Did you mean '--disable-auto-paired-vec-st'?
> > x86_64-pc-linux-gnu-clang++: error: linker command failed with exit code 1 (use -v to see invocation)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > With
> > 
> > * USE:        X abi_x86_64 amd64 elibc_glibc gtk4 kernel_linux l10n_fi l10n_sv libcxx lto official pax-kernel pic pulseaudio suid system-harfbuzz system-png
> > 
> > I will keep testing in the background but it takes like 2 hours to compile this
> 
> Just pass --enable_rust=false for the moment. Rust is only used for testing.

that's a `myconf_gn` option?

**Review by floppym — APPROVED** [review]

**Comment by PF4Public** [comment]
.110 is Windows release, Linux is currently at .106. Just sayin'

**Comment by thesamesam** [comment]
> .110 is Windows release, Linux is currently at .106. Just sayin'

I'm not too worried about this bit as historically (I think, correct me if I'm wrong) the tarballs haven't existed if it's really a Windows-only release, I think?

**Comment by PF4Public** [comment]
> the tarballs haven't existed if it's really a Windows-only release, I think?

AFAIK they [stopped generating tarballs for everything except Linux at some point](https://chromium.googlesource.com/chromium/tools/build/+/c481ff558c67b96f1818c3312928a6d1af7d2dff%5E%21/#F0), but [this change was reverted soon enough](https://chromium.googlesource.com/chromium/tools/build/+/a63da1c088ae5479bdc966cd24af6b736ba4df78). So presently all tarballs are supposed to be generated.

**Comment by thesamesam** [comment]
Ah! Thank you, I'll keep an eye out for this going forward then

**Pull request closed without merging**
