### PR TITLE
net-irc/irker: Version bump / Add SOCKS support

### PR DESCRIPTION
**Pull request by bjacquin**
Add an option USE flag for new SOCKS support.
Update irkerhook-Remove-file-listing.patch with a rebased version that apply on this new version

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thank you for the PR. Is there a bug report associated with theses changes?

**Comment by bjacquin** [comment]
Yes, there is, see https://bugs.gentoo.org/show_bug.cgi?id=579524

**Comment by akhuettel** [comment]
@patricklauer

**Comment by mgorny** [comment]
@gentoo/proxy-maint, please merge this. It's clear change, and maintainer timeout.

**Pull request closed without merging**
