### PR TITLE
dev-libs/vanessa-*: Update SRC_URI and HOMEPAGE

### PR DESCRIPTION
**Pull request by doughdemon**
See bug https://bugs.gentoo.org/show_bug.cgi?id=567974 . Second patch is a minor unrelated cleanup to vanessa-socket.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thanks a lot for the work you put in to this PR. Unfortunately, the Manifest changes are missing. We need them as missing/corrupt checksums in Manifest files may halt the delivery of Portage via rsync. We ran into this problem in the past already. See https://bugs.gentoo.org/show_bug.cgi?id=567102. Please update the PR accordingly. Thank you.

**Comment by doughdemon** [comment]
I think that there are no Manifest changes:

The tarballs haven't changed, they have just moved. (I've left them at *.gz.)
The patch is not recorded in the Manifest.

**Comment by mgorny** [comment]
@monsieurp, also CI catches broken Manifests these days.

**Comment by monsieurp** [comment]
okies then it's good to go. I'll merge it.

**Comment by doughdemon** [comment]
monsieurp wrote:
> okies then it's good to go. I'll merge it.

thanks.

**Pull request merged**
