### PR TITLE
dev-lang/rust: keyword 1.63.0 for ~mips

### PR DESCRIPTION
**Pull request by matoro**
Rust on mips!

This required a lot of shuffling of the musl profiles.  @Kumba42 this is your domain, so please check it out.

Reason why USE=system-llvm is masked for now:  because we can't build LLVM on n32 because our triplets are incorrect, this is tracked in https://bugs.gentoo.org/515694.  It's possible that I will mask sys-devel/llvm on n32 and keyword at a later date as an intermediate step, since changing triplets for n32/n64 is a bigger step.

I have marked the musl profiles as wd40.  Rust *is* supported on them per https://doc.rust-lang.org/beta/rustc/platform-support.html but they are Tier 3 as opposed mips/glibc in Tier 2 - in other words, no official bootstrap binary.  If anyone wants Rust on mips/musl, you need to provide a bootstrap binary.  See sparc for an example of how we do this.

Mips was the only blocker for deleting the deprecated directories `hardened/` and `default/linux/musl/`.  The former has had an explicit deprecation notice since January.  This does delete mips+musl+hardened (there was no mips+glibc+hardened profile); I did not want to bother porting it over.  It can be added back if there is more demand.

Testing was done on big-endian n64.

### CODE REVIEW

**Comment by gyakovlev** [comment]
from rust POV change is trivial and we have been carrying mips checksums in metadata for a long time.
I can't merge mips changes though...
need mips archmeister or QA to do that.

**Review by gyakovlev — APPROVED** [review]

**Comment by thesamesam** [comment]
@Kumba42 If you run this on woodpecker to update LDAP, you'll be in the github org:
`perl_ldap -b user -C gentooGitHubUser Kumba42 kumba`

then can be invited for reviews and such.

**Comment by immolo** [comment]
I just tested this commit as the current musl profiles are broken and are pulling in glibc instead, profiles are now much better for a user and fixes the issues I was having since the start of the week.

On my crossdev environment it does break previous synlinked /usr/$CHOST/etc/profile so I had to fix it with the following:

`# rm /usr/mipsr5900el-unknown-linux-musl/etc/portage/make.profile
# /var/db/repos/gentoo # ln -s /var/db/repos/gentoo/profiles/arch/mips/mipsel/o32/ /usr/mipsr5900el-unknown-linux-musl/etc/portage/make.profile
# /var/db/repos/gentoo # PORTAGE_CONFIGROOT=/usr/mipsr5900el-unknown-linux-musl eselect profile list`

**Comment by thesamesam** [comment]
I've gone ahead and pushed given @immolo's testing, the change makes sense, these were deprecated since January (and using a dubious construct), and that they didn't work since we masked musl on non features/musl profiles anyway. Thanks!

**Comment by Kumba42** [comment]
As I am so ridiculously far behind on things, I likely will not be testing Rust anytime in the near future (mid-2023 at the going rate, possibly longer), so feel free to apply any necessary fixes to the mips profiles for Rust stuff after testing in a minimum of a qemu environment.

As for Rust on N32, can anyone confirm that actually works, regardless of broken CHOST tuples or not?  Last I looked, Rust was only aware of pure 32-bit (O32) and pure 64-bit (N64).  It did not seem to understand the hybrid-like nature of a mixed 32/64-bit ABI like N32.  Did Rust upstream finally address this?  That would be great if they did.

I started trying to fix the mips glibc profile situation up last year and change out the CHOST tuples for modern ones, but the whole cascaded profiles setup is a mess for mips and there was something weird going on where some key variables were not getting set correctly that I could not hunt down before getting sidetracked.  Also, last I was aware, mips musl profiles weren't really the domain of the mips team, but instead the embedded team, so they're probably the better ones to comment on those.  I have no idea what the correct CHOST tuples for musl for mips's multiple ABIs should be, as I only have musl/O32 working and have not tried to bootstrap a musl/N32 or musl/N64 environment yet.

In any event, if someone wants to help with fixing the glibc profiles, please e-mail me direct or further discuss on Bug #515694.

And is Linux/PS2 really working?  With a modern kernel?  I see the R5900 identifier there, the PS2's CPU.  I know there's an effort out there somewhere, but it's been a while since I last saw anything on it.

**Comment by immolo** [comment]
@Kumba42 Indeed there is now a PS2 5.4 kernel however it only use the USB drive for root at the moment so the use of a binhost is required to have a good time on Gentoo.

https://github.com/frno7/linux

https://wiki.gentoo.org/wiki/User:Immolo/GentooPS2

My guide above needs to be updated slightly as the old profiles broke something to stop musl from working but I do have a glibc LiveUSB if you just want to try it out quickly.

**Comment by Kumba42** [comment]
> @Kumba42 Indeed there is now a PS2 5.4 kernel however it only use the USB drive for root at the moment so the use of a binhost is required to have a good time on Gentoo.
> 
> https://github.com/frno7/linux
> 
> https://wiki.gentoo.org/wiki/User:Immolo/GentooPS2
> 
> My guide above needs to be updated slightly as the old profiles broke something to stop musl from working but I do have a glibc LiveUSB if you just want to try it out quickly.

PS2 was the first non-SGI MIPS system we tried to get Gentoo up on back in 2003 when I was a greenhorn developer.  I've still got a tarball of /usr/portage from that era hiding someplace in my dev space, though I doubt it'll be of any use in modern times.  Still, everything old is new again!

I will bookmark that wiki entry for the future....I only have a slim PS2 that I think lacks ethernet, and a developer/testing PS2 (stands like a tower, has 128MB RAM instead of 32MB).  That latter one is buried in a closet, though, so will take some time to go digging for it.  If it even works, it'd probably be the better kit to try this out on.  As for a binhost, I have a NAS that most of my SGI systems are tied to for things, so it shouldn't be terribly difficult to setup, provided basic NFSv4 support is working.

**Comment by immolo** [comment]
@Kumba42 I remember your port very well as it was catalyst to my hobby of trying to see how many devices I could get Gentoo to run on.

Only USB networking works at the moment but the nfs system will work or you can use my web version once I get that up and running on my new server.

**Comment by matoro** [comment]
Musl explicitly does not support n32:  https://wiki.musl-libc.org/supported-platforms.html hence why I did not create a profile for it.  In fact it might not actually even support LE n64, unsure of the wording.

Rust also does not list it as a known platform:  https://doc.rust-lang.org/nightly/rustc/platform-support.html so it's unlikely to work.  I will investigate, but it is definitely not going to be until after I come up with an implementation for [bug 515694](https://bugs.gentoo.org/515694).

**Comment by Kumba42** [comment]
> Musl explicitly does not support n32: https://wiki.musl-libc.org/supported-platforms.html hence why I did not create a profile for it. In fact it might not actually even support LE n64, unsure of the wording.
> 
> Rust also does not list it as a known platform: https://doc.rust-lang.org/nightly/rustc/platform-support.html so it's unlikely to work. I will investigate, but it is definitely not going to be until after I come up with an implementation for [bug 515694](https://bugs.gentoo.org/515694).

I don't think it's explicitly stated, just not documented and/or supported.  Back in 2018, I successfully built a musl/N32 MIPS-III target using the OpenADK build system.  I still have that chroot kicking around, though it's hilariously out-of-date.  It is possible musl upstream may have removed support for N32 since then, but IMHO, that would be somewhat silly, because N32 is _the_ ABI you want to target for 64-bit-capable CPUs.  If you're referring to the lack of a dedicated CHOST tuple for musl/N32, that's an issue that needs to be resolved somehow (I think someone just needs to pick a sensible value and send patches in), but it should be possible to still build that target by using the standard mips64[el]-unknown-linux-musl tuple and passing -mabi=n32.

```
# ls -l musl-n32_mips3/lib32
total 587K
lrwxrwxrwx 1 root root   14 Sep 24  2018 cpp -> ../usr/bin/cpp*
lrwxrwxrwx 1 root root    7 Sep 24  2018 ld-musl-mipsn32.so.1 -> libc.so*
-rwxr-xr-x 1 root root 793K Sep 24  2018 libc.so*
-rw-r--r-- 1 root root  132 Sep 24  2018 libgcc_s.so
-rw-r--r-- 1 root root 276K Sep 24  2018 libgcc_s.so.1

# file musl-n32_mips3/lib32/libc.so
musl-n32_mips3/lib32/libc.so: ELF 32-bit MSB shared object, MIPS, N32 MIPS-III version 1 (SYSV), dynamically linked, stripped
```

Guess it can't hurt to dig out that OpenADK git repo I have, update it, and see if it still allows setting a musl/N32 target...

**Comment by Kumba42** [comment]
> > Musl explicitly does not support n32: https://wiki.musl-libc.org/supported-platforms.html hence why I did not create a profile for it. In fact it might not actually even support LE n64, unsure of the wording.
> > Rust also does not list it as a known platform: https://doc.rust-lang.org/nightly/rustc/platform-support.html so it's unlikely to work. I will investigate, but it is definitely not going to be until after I come up with an implementation for [bug 515694](https://bugs.gentoo.org/515694).
> 
> I don't think it's explicitly stated, just not documented and/or supported. Back in 2018, I successfully built a musl/N32 MIPS-III target using the OpenADK build system. I still have that chroot kicking around, though it's hilariously out-of-date. It is possible musl upstream may have removed support for N32 since then, but IMHO, that would be somewhat silly, because N32 is _the_ ABI you want to target for 64-bit-capable CPUs. If you're referring to the lack of a dedicated CHOST tuple for musl/N32, that's an issue that needs to be resolved somehow (I think someone just needs to pick a sensible value and send patches in), but it should be possible to still build that target by using the standard mips64[el]-unknown-linux-musl tuple and passing -mabi=n32.
> 
> ```
> # ls -l musl-n32_mips3/lib32
> total 587K
> lrwxrwxrwx 1 root root   14 Sep 24  2018 cpp -> ../usr/bin/cpp*
> lrwxrwxrwx 1 root root    7 Sep 24  2018 ld-musl-mipsn32.so.1 -> libc.so*
> -rwxr-xr-x 1 root root 793K Sep 24  2018 libc.so*
> -rw-r--r-- 1 root root  132 Sep 24  2018 libgcc_s.so
> -rw-r--r-- 1 root root 276K Sep 24  2018 libgcc_s.so.1
> 
> # file musl-n32_mips3/lib32/libc.so
> musl-n32_mips3/lib32/libc.so: ELF 32-bit MSB shared object, MIPS, N32 MIPS-III version 1 (SYSV), dynamically linked, stripped
> ```
> 
> Guess it can't hurt to dig out that OpenADK git repo I have, update it, and see if it still allows setting a musl/N32 target...

Okay, OpenADK still allows one to build a musl/N32 target, so we'll see how far this gets.

**Comment by Kumba42** [comment]
> > Guess it can't hurt to dig out that OpenADK git repo I have, update it, and see if it still allows setting a musl/N32 target...
> 
> Okay, OpenADK still allows one to build a musl/N32 target, so we'll see how far this gets.

And it builds:
```
bash-5.1# gcc -v
Using built-in specs.
COLLECT_GCC=/usr/bin/gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/mips64-openadk-linux-muslabin32/11.3.0/lto-wrapper
Target: mips64-openadk-linux-muslabin32
Configured with: /ramfs/openadk.git/build_generic-mips64_musl_n32/w-gcc-11.3.0-1/gcc-11.3.0/configure --build=x86_64-pc-linux-gnu --host=mips64-openadk-linux-muslabin32 --target=mips64-openadk-linux-muslabin32 --program-prefix= --program-suffix= --prefix=/usr --bindir=/usr/bin --datadir=/usr/share --mandir=/usr/share/man --libexecdir=/usr/libexec --localstatedir=/var --sysconfdir=/etc --disable-dependency-tracking --disable-libtool-lock --disable-nls --disable-static --enable-shared --with-abi=n32 --enable-languages=c,c++ --enable-target-optspace --host=mips64-openadk-linux-muslabin32 --target=mips64-openadk-linux-muslabin32 --build=x86_64-pc-linux-gnu --disable-__cxa_atexit --without-headers --libexecdir=/usr/lib --disable-libssp --disable-biarch --disable-libmudflap --disable-libgomp --disable-libquadmath --disable-libquadmath-support --disable-multilib --disable-libstdcxx-pch --disable-libsanitizer --disable-libitm --disable-install-libiberty --enable-dependency-tracking
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 11.3.0 (GCC)
bash-5.1#
```

It is a very minimally-configured chroot, but it has a C/C++ compiler, so it would not be impossible to bootstrap a gentoo environment off of it.  Really need the profiles situation sorted out first, though.  I can upload the tarball to my devspace if interested (it's big-endian, MIPS-III, so need qemu or an old SGI machine kicking around).

**Comment by matoro** [comment]
> > > Guess it can't hurt to dig out that OpenADK git repo I have, update it, and see if it still allows setting a musl/N32 target...
> > 
> > 
> > Okay, OpenADK still allows one to build a musl/N32 target, so we'll see how far this gets.
> 
> And it builds:
> 
> ```
> bash-5.1# gcc -v
> Using built-in specs.
> COLLECT_GCC=/usr/bin/gcc
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/mips64-openadk-linux-muslabin32/11.3.0/lto-wrapper
> Target: mips64-openadk-linux-muslabin32
> Configured with: /ramfs/openadk.git/build_generic-mips64_musl_n32/w-gcc-11.3.0-1/gcc-11.3.0/configure --build=x86_64-pc-linux-gnu --host=mips64-openadk-linux-muslabin32 --target=mips64-openadk-linux-muslabin32 --program-prefix= --program-suffix= --prefix=/usr --bindir=/usr/bin --datadir=/usr/share --mandir=/usr/share/man --libexecdir=/usr/libexec --localstatedir=/var --sysconfdir=/etc --disable-dependency-tracking --disable-libtool-lock --disable-nls --disable-static --enable-shared --with-abi=n32 --enable-languages=c,c++ --enable-target-optspace --host=mips64-openadk-linux-muslabin32 --target=mips64-openadk-linux-muslabin32 --build=x86_64-pc-linux-gnu --disable-__cxa_atexit --without-headers --libexecdir=/usr/lib --disable-libssp --disable-biarch --disable-libmudflap --disable-libgomp --disable-libquadmath --disable-libquadmath-support --disable-multilib --disable-libstdcxx-pch --disable-libsanitizer --disable-libitm --disable-install-libiberty --enable-dependency-tracking
> Thread model: posix
> Supported LTO compression algorithms: zlib
> gcc version 11.3.0 (GCC)
> bash-5.1#
> ```
> 
> It is a very minimally-configured chroot, but it has a C/C++ compiler, so it would not be impossible to bootstrap a gentoo environment off of it. Really need the profiles situation sorted out first, though. I can upload the tarball to my devspace if interested (it's big-endian, MIPS-III, so need qemu or an old SGI machine kicking around).
> 
> Edit: Forgot to add, there were some hiccups that needed fixing: add #include <sys/sysmacros.h> to findutils/gl/lib/mountlist.c in OpenADK don't build anything krb5; build will fail don't build libevent; build will fail due to oddities w/ libressl linking edit package/file/Makefile and update it to 5.40, hash will be: 167321f43c148a553f68a0ea7f579821ef3b11c27b8cbe158e4df897e4a5dd57

My box is big-endian, should be able to run this in a chroot.

I can go ahead and add a musl profile for n32 if you want.  By the profiles sorted out, you mean correcting the CHOSTs, or is there some other reorganization work you are referring to?

**Comment by Kumba42** [comment]
> My box is big-endian, should be able to run this in a chroot.
> 
> I can go ahead and add a musl profile for n32 if you want. By the profiles sorted out, you mean correcting the CHOSTs, or is there some other reorganization work you are referring to?

Uploaded the root tarball here, with a config file if you want to try rebuilding it yourself w/ OpenADK:
https://dev.gentoo.org/~kumba/mips/testing/

There's a README there with the short build notes I made from running into issues w/ OpenADK's setup.  They have a bad habit of retaining super-old package versions for some reason.  I was able to bump their 'file' package to a newer version, and I suspect findutils is in the same boat, though it was easier to just apply the "#include <sys/sysmacros.h>" fix instead.

As for the profiles, if you are having better success than I, feel free to take a crack at it.  I uploaded the last bit of work I did on 22.0 profiles to the same directory, filename "mips-22.0-profile-attempt-20220210.tar.xz".  It has as the toplevel folder 'default', so should unpack cleanly under a top-level 'profiles' directory.  I *think* there might be some changes needed under the arch/mips folder as well, but I did not keep those around, I think (or I can't find them, at least).  The goal of the 22.0 profiles was to focus on collapsing down some of the inflated/repeated folder structure, and it kinda works, but something just isn't right and I wasn't able to work out what.  I did implement the modernized CHOST tuple for the three different ABIs as well, but only for glibc targets.  At the time I worked on this musl was still in its own subfolder away from the primary mips profiles.

mgorny has a tool on his github that helps with debugging profile processing order, but it didn't really offer me any clues as to what was going wrong.  I never was a fan of the whole cascaded profiles idea when it was first proposed back in 2007 or so, but it's the devil we have to live with nowadays.  I kinda wanted a "stacked" profile system built up using concise profile "modules" that did proper overriding.  Didn't know Python back then, so unless someone else was going to code it, cascaded is what we got.

**Pull request closed without merging**
