### PR TITLE
net-misc/rsync: add USE to replace bundled zlib with system zlib

### PR DESCRIPTION
**Pull request by antonlacon**
Closes: https://bugs.gentoo.org/666934

### CODE REVIEW

**Comment by Whissi** [comment]
This one will require discussion.

**Comment by antonlacon** [comment]
I may have described the postinst message poorly.

Since 3.1.1, both sides of a sync connection using compression can use --new-compress, whether either side is using bundled or system zlib. If one side is using system zlib, it has to use --new-compress. Only when both sides are using the bundled zlib, --old-compress or --new-compress may be used. In short, both sides need to agree on the compression stream format, and system zlib can't generate the old-compress stream format.

**Comment by Whissi** [comment]
What's your motivation to add this USE flag? My first thought were "Uhh.. if only Gentoo will switch to system zlib, we will get bug reports very soon that rsync doesn't work anymore because not everyone is using Gentoo for unknown reason". Of course, you hide that feature behind a USE flag so it shouldn't affect the normal user but on the other hand, people should use system libraries if possible. So I would expect that some user will set the USE flag because of that... running into unexpected problems. So I am not sure if it is worth to add something like that. You can still pass that via *EXTRA_CONF* if you like...

**Comment by antonlacon** [comment]
My portage tree sits on an OpenWrt box, which uses the system zlib for its rsync by default. I need to set the --new-compress option in order to sync to it. Since this is 99% of my use case for rsync, I gain no benefit from the bundled zlib on my workstations/VMs, so this removes it. This is also a step towards reaping more benefits from improvements to zlib (like chromium's, cloudflare's, or intel's simd acceleration).

Rsync-3.1.1 came out in June 2014, so the option to use --new-compress should be widespread by now. If the concern is with emerge --sync, then a discussion should be had among you all on whether --new-compress is an appropriate default to add to portage's rsync options.

**Comment by thesamesam** [comment]
We have USE=system-zlib for rsync now. Thank you.

**Pull request closed without merging**
