### PR TITLE
sci-mathematics/geogebra: added live ebuild

### PR DESCRIPTION
**Pull request by Keepco**
As of https://bugs.gentoo.org/show_bug.cgi?id=596140

### CODE REVIEW

**Comment by Amynka** [comment]
Sorry looking at it.. When they changed github it broke my scripts

**Comment by Keepco** [comment]
Thanks for looking at it :+1:

**Comment by Amynka** [comment]
Trying to resolve license changes.

**Comment by gktrk** [comment]
I don't think a live ebuild is possible because gradle requires network access during build time. Taking a snapshot of the repo is the only possibility I can think of, with all the downloaded files being listed in SRC_URI.

**Comment by gktrk** [comment]
@Keepco I've created such an ebuild from a snapshot of the geogebra git repo: http://dev.gentoo.org/~gokturk/tmp/geogebra-5.0.339.0_p20170308.ebuild What do you think?

**Comment by gktrk** [comment]
https://github.com/gentoo/gentoo/pull/4160

**Comment by Keepco** [comment]
@gktrk Looks good to me, but please remove the old CVS header on line 3, those are not needed any more (Forgot to do that myself). It is a nicer solution than having to disable network-sandbox for this package for sure.  If only geogebra would tag their releases, having to change the commit hash for every update seems suboptimal

**Comment by Amynka** [comment]
Migrated to pr #4160

**Pull request closed without merging**
