### PR TITLE
media-libs/gstreamer-editing-services: support python3_7

### PR DESCRIPTION
**Pull request by okias**
Compile tested.

Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by okias** [comment]
can someone please merge it?

**Comment by okias** [comment]
Please?

**Comment by leio** [comment]
lose the bump, there are no changes to GES there over 1.14.3, which is why I didn't bump it with the rest.

**Comment by okias** [comment]
@leio sadly for example Fractal needs 1.14.4, so that's a reason why I had to do the bump..

**Comment by leio** [comment]
It's a very bogus and wrong dep in fractal meson.build, you can patch or sed it to 1.14.3 or less really. https://gitlab.gnome.org/GNOME/fractal/commit/32ca3f7c6e758d11c4900f7a9220599881357497
Upstream should change it to 1.14.0 or something.

**Pull request closed without merging**
