### PR TITLE
dev-util/bear: Add patch for missing dependency

### PR DESCRIPTION
**Pull request by lima-limon-inc**
---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

**Note**: I left `amd64` and `x86` as stable. I am not aware I those should be marked as unstable.

### CODE REVIEW

**Comment by lima-limon-inc** [comment]
The patch (as well as this commited) was tested on my machine and built correctly. 

Gentoo, `amd64`

**Comment by DarthGandalf** [comment]
If it just fixes the build, no need to revbump.

But why not use 3.1.4-r1 which is in tree already?

**Comment by lima-limon-inc** [comment]
> If it just fixes the build, no need to revbump.

Noted. I always mess that up 😅.

> But why not use 3.1.4-r1 which is in tree already?

It's marked as unstable. Version 3.1.3 is the only version marked as stable.
That's the only reason why portage pulled it into my system AFAIK.

**Comment by lima-limon-inc** [comment]
> If it just fixes the build, no need to revbump.

Changed it in the last commit.

**Comment by DarthGandalf** [comment]
> It's marked as unstable. Version 3.1.3 is the only version marked as stable.

https://bugs.gentoo.org/939594

**Comment by lima-limon-inc** [comment]
> > It's marked as unstable. Version 3.1.3 is the only version marked as stable.
> 
> https://bugs.gentoo.org/939594

Oh, nice! What do you think is the best course of action? Applying the patch regardless? Or will version 3.1.3 be dropped once 3.1.4 is stabilized?

**Comment by DarthGandalf** [comment]
once 3.1.4 is stabilized, you don't need to worry about 3.1.3 anymore. I can't drop 3.1.3 before 3.1.4 is stable

**Comment by lima-limon-inc** [comment]
> once 3.1.4 is stabilized, you don't need to worry about 3.1.3 anymore. I can't drop 3.1.3 before 3.1.4 is stable

So until then, couldn't/shouldn't this patch be applied?

**Comment by DarthGandalf** [comment]
Maybe. But good luck getting this PR merged faster than that :( Due to long queue, usual response time for p-m PRs is weeks, by someone who can apply it

**Comment by lima-limon-inc** [comment]
> Maybe. But good luck getting this PR merged faster than that :( Due to long queue, usual response time for p-m PRs is weeks, by someone who can apply it

Oooh I see, I see. I thought you were the maintainer. Are you a proxy maintainer then??

I saw that Larry 🐮 at'ed you.

Regardless, I can wait :p. Hopefully, if anyone else stumbles upon this error they'll reach the bugzilla page and it'll link them back to this PR.

**Comment by DarthGandalf** [comment]
Yes, proxy.
I'm not full Gentoo developer

**Comment by lima-limon-inc** [comment]
If anyone stumbled upon this PR because Bear failed to build, either:

- Allow the unstable version on your system. https://wiki.gentoo.org/wiki//etc/portage/package.accept_keywords
- Apply a Patch manually. Simply copy the patch file from this commit to your system. Here's the wiki for more information: https://wiki.gentoo.org/wiki//etc/portage/patches

**Comment by DarthGandalf** [comment]
And... it's stable. If the issue is gone, please close

**Pull request closed without merging**
