### PR TITLE
app-editors/mg, app-emacs/*: fix HTTPS, remove dead HOMEPAGES

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR fixes a lot of emacs related packages to use https instead of http and also removes some dead HOMEPAGES.
I saw 2 Homepages who provide https but aren't trusted by the browser. I didn't change those.

Please review.

### CODE REVIEW

**Comment by monsieurp** [comment]
@ulm Hi! Are you OK with this PR? Let me know. Thanks!

**Comment by mm1ke** [comment]
Hi,

I've open bugs for the packages with broken Homepages (except for one, because there is already a tracker for code.google.com Homepages)
I've also rebased this PR and removed the packages with the broken homepages.

**Comment by ulm** [comment]
Thanks, looks good now.
Please merge.

**Comment by monsieurp** [comment]
Merging underway.

**Pull request closed without merging**
