### PR TITLE
dev-vcs/subversion: Added USE=xinetd and optional RDEPEND on sys-apps/xinetd

### PR DESCRIPTION
**Pull request by jaakristioja**
Only install /etc/xinetd.d/svnserve if USE=xinetd is set.

Bug: https://bugs.gentoo.org/43245
Bug: https://bugs.gentoo.org/712042
Signed-off-by: Jaak Ristioja <jaak@ristioja.ee>

### CODE REVIEW

**Comment by jaakristioja** [comment]
@juippis Done. Also fixed the `xinetd` flag not being included in `IUSE` and `metadata.xml`.

**Comment by juippis** [comment]
@akhuettel @zlogene saw you took up maintainership, could you check this? Compiles with gcc-10.

@jaakristioja you need to sign-off your commit, and remember to tag bugs like you did previously.

**Comment by ajakk** [comment]
Still interested in this? If so, could you update your changes to be applied to the current version of subversion in tree?

**Comment by jaakristioja** [comment]
@ajakk Should be done now. Except I apologize for not GPG-signing the commit because my `gpg-agent` is [broken](https://dev.gnupg.org/T5270).

**Comment by akhuettel** [comment]
No, sorry. This falls under the "small text files" policy. The xinetd files hurt nobody.

**Comment by jaakristioja** [comment]
> The xinetd files hurt nobody.

They [did](https://bugs.gentoo.org/712042) when I filed this PR... but I guess I forgive You for giving me the runaround, especially since you fixed the underlying problem. Thanks! 😃

**Pull request closed without merging**
