### PR TITLE
x11-libs/gtk+: bump

### PR DESCRIPTION
**Pull request by mpkh**

### CODE REVIEW

**Comment by mpkh** [comment]
@EvaSDK updated :)

**Comment by mpkh** [comment]
summon @leio

**Comment by mpkh** [comment]
Okay, it's outdated already, newer one is `3.22.8` - feel free to close it and re-add newer one, contributing is hard XD

**Comment by mpkh** [comment]
3.22.9, nobody cares :D

**Comment by leio** [comment]
ok, then, as there was no update to 3.22.9 for including some authorship as discussed on IRC, had to commit the .9 now myself. As you might have seen from e-mail CC, I also updated a tool to notice stable release updates as well to not miss these for so long again.

commit 8f5fa722ae8c53074fa4b2c210febca68b4fb429
Author: Mart Raudsepp <leio@gentoo.org>
Date:   Sun Mar 5 17:33:51 2017 +0200

    x11-libs/gtk+: bump to 3.22.9 and apply various fixes
    
    * Stop inheriting eutils - epatch isn't used with EAPI-6 and einstalldocs
    comes from EAPI-6 itself as well
    * Remove cairo[svg] comment as it is a required dep since long ago after
    the bug was filed upstream - it is needed by file print backend (print to
    file), which is not optional
    * Adapt to libepoxy changes that made epoxy/glx.h and related source code
    optional and put it behind a USE flag, bug #611710
    * Remove unnecessary libXrender dependency (though cairo[X] will still
    pull it in), bug #611032
    * Remove -O3 to -O2 replacement and strip-flags; apparently people have
    been doing that with success, so lets give it a chance after issues that
    happened with -O3 over 10 years ago
    * Install select docs instead of the default ones, which include an
    uninteresting README.win32, README.in source file that for some reason
    is shipped in tarball, README.commits that is interesting for git usage
    instructions only, and a useless ChangeLog that isn't properly generated
    anymore. The DOCS array is declared locally in multilib_src_install_all,
    because gnome2_src_install calls "default" which calls einstalldocs too,
    which would fail if the DOCS is given in global scope and it sees it, as
    the docs won't be found in multilib WORKDIR.
    
    Gentoo-bug: 611032
    Gentoo-bug: 611710
    Package-Manager: Portage-2.3.3, Repoman-2.3.1

**Pull request closed without merging**
