### PR TITLE
app-editors/vscode: fix fcitx:5 doesn't work under native wayland

### PR DESCRIPTION
**Pull request by Dawn-Xu-helloworld**
Just a small fix and make app-i18n/fcitx:5 working in vscode under wayland

### CODE REVIEW

**Comment by Dawn-Xu-helloworld** [comment]
emmm...
How to add local USE flags??

**Comment by AdelKS** [comment]
If the extra flag doesn't hurt other uses/users who do not make use of `fcitx` you can simply add it under the `wayland` USE flag.

**Comment by Dawn-Xu-helloworld** [comment]
> If the extra flag doesn't hurt other uses/users who do not make use of `fcitx` under wayland, you can simply add it under the `wayland` USE flag.

OK, It seems that `code --enable-wayland-ime` doesn't make sense without a IME

**Comment by Dawn-Xu-helloworld** [comment]
oops....

**Comment by Dawn-Xu-helloworld** [comment]
@AdelKS does this PR still have some errors? If not, please merge it, or please tell me how to improve the PR

**Comment by AdelKS** [comment]
Unfortunately I cannot merge, I am not a Gentoo dev. 

`vscode` doesn't need any argument to support `fcitx` under `Xorg` ?

**Comment by Dawn-Xu-helloworld** [comment]
> Unfortunately I cannot merge, I am not a Gentoo dev.
> 
> `vscode` doesn't need any argument to support `fcitx` under `Xorg` ?

@AdelKS 
Yes, it doesn't. `Xorg` have globally IME interfaces, but `wayland` 's IME interface is provided by WM (In fact, it's formal name should be `composer` )

**Pull request closed without merging**
