### PR TITLE
dev-libs/json-c: add patch for static-libs support, live ebuild and add new maintainers

### PR DESCRIPTION
**Pull request by jsmolic**
Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>
Signed-off-by: Luka Perkov <luka.perkov@sartura.hr>

### CODE REVIEW

**Comment by jsmolic** [comment]
Hi @juippis, could you quickly review this pull request if it is not too much to ask :)
Initially I did a version bump as a part of this PR, but today another Gentoo developer updated json-c package before this request was reviewed and merged.
We would still like to maintain this package. I am aware that it is not a practice to grant package maintenance  without any contributions so if needed we are open to contributing to this package
in some way before we can be added as maintainers.

Thank you :)

**Comment by juippis** [comment]
Yeah, if there's "nothing to do" for the package, we'd much prefer to wait until a dev with commit access picks it. However now it was bumped without taking up maintainership. 

I checked this morning and this package had two bugs open, you could start by attempting to fix those.

**Comment by jsmolic** [comment]
@juippis Yes, I saw some new reported bugs for this package, at the time of my first comment they were not opened yet.
I fixed one bug, and I'll be working on fixing others as well.

**Comment by jsmolic** [comment]
@juippis I fixed static-libs USE flag problem. Right now this enables building either shared or static library, the goal would be to install both shared and static if static-libs support is selected. I've looked into it, and currently CMake system used in json-c source code doesn't support building both shared and static library. That would require patching source.
Is this okay to merge for now, to provide the users the option to select static library support, as they can't do that currently, and I can try to deal with this issue later?

**Comment by jsmolic** [comment]
@juippis Just a quick update, with @hofnarrr's help new patch for 0.14 ebuild and a 9999 ebuild are added. This solves all problems with static library support.

**Pull request closed without merging**
