### PR TITLE
dev-lang/execline, dev-libs/skalibs, */s6*: Update versions and add remaining packages

### PR DESCRIPTION
**Pull request by smaeul**
This bumps the version of existing packages from http://skarnet.org/software/ as all of them were out of date. s6 has a bug requesting an update, with no activity: https://bugs.gentoo.org/601482

The update to skalibs fixes https://bugs.gentoo.org/573474

I fixed the static use flags to function properly. I also added SLOT dependencies, since all of the updated packages depend on the updated skalibs anyway.

As I use most of these, I am willing to maintain them.

### CODE REVIEW

**Comment by atlaua** [comment]
Thanks! I'd been meaning to bump these ebuilds during the holidays, but I never came around to it. I'll have a closer look at your patches tomorrow.

For the ebuilds I'm currently maintaining (s6-portable-utils, s6-linux-utils, s6-linux-init, s6-rc), I'd be happy to welcome you as a co-maintainer; just submit a patch adding yourself to the respective metadata.xml files. I'm however not the maintainer of skalibs, execline and s6; for those you'll have to ask @williamh.

**Comment by atlaua** [comment]
Oh, and I've got a first feedback item before I go to bed: In your net-misc/s6-networking ebuild, please replace the "libressl" USE flag by "ssl". The former should only be used to switch between openssl and libressl; for deciding whether to build with ssl support at all (even if the package only supports libressl), the "ssl" flag is appropriate.

**Comment by williamh** [comment]
Hello, I will start looking at these when I get to the office. If you want, I'll be your backup on the s6-dns and s6-networking packages instead of @proxy-maint as I am for @atlaua.

**Comment by williamh** [comment]
In skalibs, there is no need to force ipv6 on; this is covered by the profiles.
Also, I don't know if we need the subslot, and if we do, it would be better to use versionator to calculate it than to hard code it.
For now I will change the '+ipv6' to 'ipv6' and remove the subslot so I can get this in the tree,

**Comment by smaeul** [comment]
On 01/11/17 12:42, William wrote:
> In skalibs, there is no need to force ipv6 on; this is covered by
> the profiles.

Okay.

> Also, I don't know if we need the subslot, and if we do, it would be
> better to use versionator to calculate it than to hard code it. For
> now I will change the '+ipv6' to 'ipv6' and remove the subslot so I
> can get this in the tree,

For all of the packages with shared libraries, the soname changes with
every minor version bump (like 2.1 to 2.2). So for dynamically-linked
binaries, not having the subslot will break and require revdep-rebuild
on all of the other packages. The subslot should not be needed if they
are statically linked, because the utilities are backward-compatible.

**Comment by williamh** [comment]
Ok, thanks for the information, I'll add back the subslot.

**Comment by smaeul** [comment]
I updated the pull request to not force IPv6 and to use versionator

**Comment by williamh** [comment]
I don't know if you saw my last question.

Since I maintain in one form or another all of the skarnet software in our tree, if it is ok with you, I would like to drop proxy-maint on the new packages and add myself as the backup maintainer.

**Comment by smaeul** [comment]
Sure, that's fine with me. Do you want me to update the metadata.xml or do that as a separate commit?

**Comment by williamh** [comment]
I'll update the metadata before I merge.
Can you do the ssl fix discussed above for s6-networking?

**Comment by smaeul** [comment]
Pushed

**Comment by williamh** [comment]
In the push where you used versionator and stopped forcing the ipv6 use flag, you also changed a number of the subslot dependencies.

Why that change?

**Comment by smaeul** [comment]
Because I realized that "depend on the same slot that was installed at build time" is meaningless at build time. The := slot operator only affects runtime dependencies (at least according to https://devmanual.gentoo.org/general-concepts/dependencies/)

**Comment by atlaua** [comment]
@smauel Could you please add a "!<sys-apps/s6-linux-utils-2.2.0.0"
dependency to sys-apps/s6-linux-init-0.2.0.0? Otherwise, there will be
a file collision for /bin/s6-{reboot,poweroff,halt} if s6-linux-init is
updated before s6-linux-utils.

As I said, feel free to add yourself as a co-maintainer to the
packages maintained by me. I'm currently in "devaway mode" quite often,
so I'd be happy about your help.

@williamh As far as I'm concerned, the revbumps for s6-portable-utils,
s6-linux-utils, s6-linux-init and s6-rc can be merged as soon as my
feedback above has been addressed. Unfortunately, I haven't been able to
do any significant testing, but smaeul's patches look good and compile
fine.

**Comment by smaeul** [comment]
@atlaua I added the blocker and myself as co-maintainer.
@williamh I believe all feedback has been addressed at this point.

**Comment by williamh** [comment]
I want to confirm, s6-networking only supports libressl?

**Comment by smaeul** [comment]
Yes, it only has backends for libtls (so libressl) and bearssl (which is not packaged). See http://skarnet.org/software/s6-networking/

**Comment by atlaua** [comment]
The only thing you apparently forgot is to s/proxy-maint/williamh/ in
s6-{dns,networking}/metadata.xml. :)

**Pull request closed without merging**
