### PR TITLE
app-misc/lirc fix systemd unit (bug #529210)

### PR DESCRIPTION
**Pull request by candrews**
Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by monsieurp** [comment]
Hello and thank you for the PR. This is a maintainer needed package. Would you be willing to step up and take over maintenance?

**Comment by candrews** [comment]
Sorry - I'm happy to do fixes for things that I notice like this PR, but at this time, I'm not able to commit to maintainership.

**Comment by monsieurp** [comment]
Sorry for the belated answer. Okay no worries. We need a systemd expert here. @mgorny maybe? @tomboy-64? or @floppym?

**Comment by floppym** [comment]
Looks fine to me.

**Pull request closed without merging**
