### PR TITLE
dev-util/conan: add a new package version 2.9.2

### PR DESCRIPTION
**Pull request by dpronin**
Closes: https://bugs.gentoo.org/941155

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
In future, please just force-push to the existing PR.

**Comment by dpronin** [comment]
> In future, please just force-push to the existing PR.

I am sorry

**Comment by dpronin** [comment]
Version is upgraded up to 2.9.2

**Comment by dpronin** [comment]
@thesamesam would you check it out?

**Comment by dpronin** [comment]
@azomazo approve?

**Comment by dpronin** [comment]
upgraded up to 2.9.3

**Pull request closed without merging**
