### PR TITLE
Yet more EAPI-6 and cmake-EAPI-7 cleanup

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Review by DarthGandalf — APPROVED** [review]

**Comment by DarkDefender** [comment]
ok for embree.

**Comment by band-a-prend** [comment]
Should I revbump the `sci-libs/cantera-2.6.0` to EAPI8 asap?

**Comment by a17r** [comment]
@band-a-prend if you can make it compatible with newer sundials in the same revbump it would be worth it.

**Comment by band-a-prend** [comment]
As I mentioned in https://bugs.gentoo.org/888527 currently build of cantera[cti] (and cantera[python]) is broken to build due to checking of pip version (required to install). Last time I built it on summer and it was ok. I try to find the reason.

Please delay the dropping the sci-libs/cantera-2.5.0-r4 and dev-libs/sundials-5.2.0.

The `scons-utils.eclass` get EAPI8 last month.

**Comment by a17r** [comment]
> As I mentioned in https://bugs.gentoo.org/888527 currently build of cantera[cti] (and cantera[python]) is broken to build due to checking of pip version (required to install). Last time I built it on summer and it was ok. I try to find the reason.
> 
> Please delay the dropping the sci-libs/cantera-2.5.0-r4 and dev-libs/sundials-5.2.0.

Thanks - you need to talk *versions* for me to know what the problem is ;) so, short summary:
- `2.6.0` is currently broken
- keeping `dev-libs/sundials-5.2.0` is implied by *any* currently available cantera version in ::gentoo
- `2.5.1-r1` can safely be dropped

**Comment by band-a-prend** [comment]
@a17r , yes
1. `sci-libs/cantera-2.6.0-r1[cti]` (and therefore `USE="python"`) is broken - the pip version check relies on it's internal API and it seems changed as early assumed by upstream. The `cti` provides very useful conversion tools and `python` interface is easy to use for quick modeling.
2. `sci-libs/cantera-2.5.1-r4[cti,python,fortran,lapack]` successfully built and tests are passed (with `sci-libs/sundials-5.2.0`) - I checked it again. It's OK.
3. `sci-libs/cantera-2.5.1-r1 could be dropped.

**Review by zmedico — APPROVED** [review]

**Comment by janhenke** [comment]
Ack for dev-cpp/ms-gsl-3.1.0

**Review by ionenwks — APPROVED** [review]
ok for games@, was already looking forward to dropping performous w/ its wall of patches and just giving it a few days, but doesn't need to wait :)

**Comment by mid-kid** [comment]
Mildly iffy on dropping the old telegram stack when a new stable was *just* marked, but it's probably for the best.

**Review by DarthGandalf — APPROVED** [review]

**Review by arthurzam — APPROVED** [review]

**Comment by ulm** [comment]
ACK for app-emacs/vterm-0.0.1_pre20200713.

No ACK for app-emacs/vterm-0.0.1_pre20210618, because the newer version is in the tree only since a couple of days.

**Comment by waebbl** [comment]
Shall I close https://github.com/gentoo/gentoo/pull/29296 in favor of this PR, or do you wanna remove it your PR?

**Review by zmedico — APPROVED** [review]

**Review by atupone — APPROVED** [review]
done for cvc4

**Comment by amadio** [comment]
@a17r Please don't drop clhep-2.4.5.1, as geant-4.11.0.2 depends on it. It's fine to drop geant-4.10.7.3, though. I would have kept it a bit longer as 4.11 has breaking changes not all have adapted to yet, but I guess by now it should be ok to drop it.

**Comment by a17r** [comment]
> @a17r Please don't drop clhep-2.4.5.1, as geant-4.11.0.2 depends on it. 

clhep-2.4.5.3 is stable.

**Comment by amadio** [comment]
Ok, then it should be fine.

**Review by jkroonza — COMMENTED** [review]
ACK for sipp.  Thank you.

**Pull request merged**
