### PR TITLE
dev-python/*: use HTTPs, some minor fixes and EAPI7 bumps

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR fixes some python related packages to use https instead of http. Also added some EAPI7 bumps (for the EAPI5 ebuilds), fixed the SRC_URI for dev-python/cemet and did some other small cleanups.

Please review

### CODE REVIEW

**Comment by monsieurp** [comment]
@mgorny what's your take on this PR?

**Comment by mm1ke** [comment]
```dev-python/twitter``` got bumped in the meantime (EAPI7), so I've only had to fix the homepage. There is now only one EAPI7 bump in this PR. If you want I can create a separate PR if it's simpler to accept.

**Comment by flappyports** [comment]
This no longer cleanly applies.

**Comment by mm1ke** [comment]
@flappyports 
Thanks for the merges. I've updated this PR and rebased against master (and fixed the conflict).

**Pull request closed without merging**
