### PR TITLE
Add ISOBMFF build option via package use flag

### PR DESCRIPTION
**Pull request by goeland86**
Submitting PR to provide a cleaner way of tracing the submission of the updated exiv2 build with ISOBMFF for CR3, AVIF  and HEIF support option. Bugzilla ticket is here: https://bugs.gentoo.org/814212

### CODE REVIEW

**Comment by goeland86** [comment]
Oh boy. I was hoping using the Github editor to upload my ebuild file would be easier. But it really isn't. And I don't want to clone the entire project for one new file to add - I get the need for the sign-offs, but it's a bit convoluted to make them properly when you're in a hurry late at night.

**Comment by thesamesam** [comment]
That's OK, I've got the bit I need (the sign off), so I can do the git mangling if necessary this time ;).

Thanks!

**Comment by goeland86** [comment]
Much appreciated! I'll try to do better next time!

**Comment by thesamesam** [comment]
Thanks! Done as https://github.com/gentoo/gentoo/commit/a0a701d1456974ba5e8ce8b69809889c2c569271.

**Pull request closed without merging**
