### PR TITLE
dev-php/pecl-mongodb-1.3.3: USE_PHP+="php7-2"

### PR DESCRIPTION
**Pull request by askovpen**
Signed-off-by: Alexander Skovpen alexander@skovpen.org

### CODE REVIEW

**Comment by hydrapolic** [comment]
Please call version 1.5.2 stabilization instead. This won't happen.

**Comment by askovpen** [comment]
> Please call version 1.5.2 stabilization instead. This won't happen.

1.3.3 support php 7.2 and stable for amd64. 1.5.2 - unstable.

**Comment by hydrapolic** [comment]
It's generally not allowed to add new PHP compatibility to stable packages. Stable means it's tested and pecl-mongodb 1.3.3 with php 7.2 haven't been tested in Gentoo yet. So either you add pecl-mongodb-1.3.3-r1 with php 7.2 support (and wait 30 days and stabilize that version) or stabilize 1.5.2 instead. I would suggest opening a bug report for 1.5.2 stabilization.

**Comment by askovpen** [comment]
i add  add pecl-mongodb-1.3.3-r1. to stabilize 1.5.2 need to stabilize depends.

**Comment by hydrapolic** [comment]
Why stabilize a year old version when we can have a newer one? :) We stabilize new stuff all the time, I don't see a problem in that.

**Comment by hydrapolic** [comment]
https://bugs.gentoo.org/668856

**Comment by askovpen** [comment]
to stabilize 1.5.2 need stabilize:
dev-libs/libbson-1.12.0
dev-libs/mongo-c-driver-1.12.0

**Comment by hydrapolic** [comment]
Yes, they are included in the package list.

**Comment by hydrapolic** [comment]
Yes, I was working on it, but it needs a newer libbson/mongo-c-driver which failed at first attempt. But 1.5.2 should work just fine.

**Pull request closed without merging**
