### PR TITLE
New ebuild: net-proxy/obfs4proxy, plus dependencies.

### PR DESCRIPTION
**Pull request by mkszuba**
A new obfuscating proxy for Tor bridges which supports, among others,
the OBFS4 protocol. It depends on three packages which were not in
Portage and therefore have just had ebuild files created as well:
dev-go/ed25519, dev-go/goptlib, and dev-go/siphash.

Relevant Gentoo bugs: #580582, #580622, #580626, #580628.

As mentioned on Bugzilla, I am interested in becoming the proxy maintainer of those ebuilds.

### CODE REVIEW

**Comment by blueness** [comment]
I'll proxy for this since I'm the maintainer for tor.

**Comment by blueness** [comment]
first criticism, we should break this up into one commit per pkg so if we have to revert or selectively commit, we can do so.  1 issue => 1 commit.

**Comment by blueness** [comment]
thanks for splitting that up, i'll check each wrt the QA errors being thrown and commit later today

**Comment by gktrk** [comment]
just a heads up, the Manifest files are not thin. they should be regenerated using repoman manifest.

**Comment by blueness** [comment]
okay this is committed.  a few pointers: 1) you don't need separate commits for the manifest, they get rehashed on commit at my end, 2) the license for obfs4proxy is BSD, you had GPL-2.  please recheck at your end, 3) i'll proxy maintain these for you instead of the proxy-maint team, but you're still the proxied maintainer.  these are easy ebuilds to maintain but please just ping me when there are new releases.  in particular for ed25519 and goptlib which have no tagged releases yet.

will you be able to keep an eye on new releases then?

**Comment by mkszuba** [comment]
> the license for obfs4proxy is BSD, you had GPL-2. please recheck at your end
It is indeed BSD, my bad - I based my ebuild on someone else's and forgot to check the licence.

> will you be able to keep an eye on new releases then?
Sounds good! goptlib has in fact got tagged releases, the problem with it is that git.torproject.org does not provide any tarballs; this may change in the future though (https://trac.torproject.org/projects/tor/ticket/18504). As for ed25519, looks like it may get merged into go.crypto soon - see https://go-review.googlesource.com/#/c/22030/

**Pull request closed without merging**
