### PR TITLE
sys-kernel/kpatch: add live ebuild

### PR DESCRIPTION
**Pull request by aliceinwire**
Package-Manager: Portage-2.3.6, Repoman-2.3.1

### CODE REVIEW

**Comment by gktrk** [comment]
We may have to work on this a bit more:

```
>>> Compiling source in /var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0 ...
make -j2 all 
make -C kpatch-build
make -C kpatch
make[1]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kpatch-build'
make[1]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kpatch'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kpatch'
make -C kmod
gcc -MMD -MP -O1 -march=native -pipe -I../kmod/patch -Iinsn -Wall -g -Werror -c -o create-diff-object.o create-diff-object.c
make[1]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod'
make -C core clean
make[2]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core'
rm -f -Rf .*.o.cmd .*.ko.cmd .tmp_versions *.o *.ko *.mod.c \
Module.symvers
make[2]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core'
make -C core
make[2]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core'
make -C /lib/modules/4.12.5-gentoo-quinlan/build M=/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core kpatch.ko
make[3]: Entering directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core'
make[3]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.
gcc -MMD -MP -O1 -march=native -pipe -I../kmod/patch -Iinsn -Wall -g -Werror -c -o kpatch-elf.o kpatch-elf.c
  CC [M]  /var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.o
kpatch-elf.c: In function ‘kpatch_create_symbol_list’:
kpatch-elf.c:330:6: error: format ‘%lu’ expects argument of type ‘long unsigned int’, but argument 8 has type ‘Elf64_Addr’ [-Werror=format=]
      ERROR("symbol %s at offset %lu within section %s, expected 0",
      ^
cc1: all warnings being treated as errors
make[1]: *** [Makefile:17: kpatch-elf.o] Error 1
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kpatch-build'
make: *** [Makefile:14: build-kpatch-build] Error 2
make: *** Waiting for unfinished jobs....
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c: In function ‘kpatch_write_relocations’:
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:635:8: error: ‘R_X86_64_NONE’ undeclared (first use in this function)
   case R_X86_64_NONE:
        ^
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:635:8: note: each undeclared identifier is reported only once for each function it appears in
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:637:8: error: ‘R_X86_64_PC32’ undeclared (first use in this function)
   case R_X86_64_PC32:
        ^
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:643:8: error: ‘R_X86_64_32S’ undeclared (first use in this function)
   case R_X86_64_32S:
        ^
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:648:8: error: ‘R_X86_64_64’ undeclared (first use in this function)
   case R_X86_64_64:
        ^
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:670:18: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   if (memchr_inv((void *)loc, 0, size)) {
                  ^
/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.c:695:28: warning: cast to pointer from integer of different size [-Wint-to-pointer-cast]
   ret = probe_kernel_write((void *)loc, &val, size);
                            ^
make[4]: *** [scripts/Makefile.build:303: /var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core/core.o] Error 1
make[3]: *** [Makefile:1691: kpatch.ko] Error 2
make[3]: Leaving directory '/usr/src/linux-4.12.5-gentoo'
make[2]: *** [Makefile:13: kpatch.ko] Error 2
make[2]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod/core'
make[1]: *** [Makefile:7: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/sys-kernel/kpatch-0.4.0-r1/work/kpatch-0.4.0/kmod'
make: *** [Makefile:14: build-kmod] Error 2
```

**Comment by aliceinwire** [comment]
removed x86

**Comment by aliceinwire** [comment]
added shellcheck as testing dependency

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/ca9772eb0e7...4fdae0b0e6e. Thanks!

**Pull request closed without merging**
