### PR TITLE
Metadata update

### PR DESCRIPTION
**Pull request by nvinson**

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks for your patch, Nicolas. Please disregard the QA checks. However, if you would like to improve it:

1. Please use more specific commit messages (you can use `git rebase -i` to edit the commits); i.e. instead of 'update metadata' -> 'update maintainer description'; because metadata update is a very wide term that requires people to check what you changed),
2. 'Proxied maintainer' itself is fine, there's no need to tell who to assign bugs to, just make sure you are first in metadata.xml since order is important when assigning bugs,
3. 'Proxied maintainer' is not a full sentence so does not end with a full stop (dot).

**Comment by nvinson** [comment]
> Please use more specific commit messages (you can use git rebase -i to edit the commits); i.e. instead of 'update metadata' -> 'update maintainer description'; because metadata update is a very wide term that requires people to check what you changed),

Done.

> 'Proxied maintainer' itself is fine, there's no need to tell who to assign bugs to, just make sure you are first in metadata.xml since order is important when assigning bugs,

Done.  However, I didn't change the order as the current order was agreed upon in #gentoo-proxy-maint when the xml files were first updated.

> 'Proxied maintainer' is not a full sentence so does not end with a full stop (dot).

fixed.

**Comment by gktrk** [comment]
@gentoo/proxy-maint 
we have decided to get rid of <description/> when you are listed as the first maintainer in the metadata, as bug assignment is already covered by GLEP67. They should just be removed instead.

**Comment by gktrk** [comment]
Adjusted per GLEP 67 and merged. Thanks!

**Pull request closed without merging**
