### PR TITLE
sys-apps/rng-tools: open entropy src with O_NOCTTY flag wrt bug #556456

### PR DESCRIPTION
**Pull request by gktrk**
This revision introduces a sed substitution in the ebuild to patch the source
file 'rngd_entsource.c', adding O_NOCCTY flag to one open() call.

Bug: 556456

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by mgorny** [comment]
Please use a patch for this. `sed` will fail randomly and terribly on version bumps.

**Comment by mgorny** [comment]
@gentoo/base-system @gentoo/proxy-maint @idella

**Comment by gktrk** [comment]
follow-up pull request: https://github.com/gentoo/gentoo/pull/95

**Comment by mgorny** [comment]
For the future: you should do `git push --force` to update the branch behind pull request rather than opening a new one.

**Comment by hasufell** [comment]
yep and it's also better to stuff the PR into a separate branch, so you don't have to worry about force-pushes, multiple pull requests and so on... e.g. do: `git branch PR-sys-apps/rng-tools`

**Comment by gktrk** [comment]
Thanks for the tips! Didn't know github updated PR on forced pushes.

**Pull request closed without merging**
