### PR TITLE
sci-libs/vtk: add 9.2.5

### PR DESCRIPTION
**Pull request by waebbl**
- Add Python 3.11 support.
- Simplifiy test logic. The VTK_FORBID_DOWNLOADS option now also works
  when testing is enabled, if all data files are downloaded and
  regenerated before testing.
- Drop native CUDA arch as long as detection isn't fixed upstream.

Bug: https://gitlab.kitware.com/vtk/vtk-m/issues/693
Bug: https://bugs.gentoo.org/835659
Closes: https://bugs.gentoo.org/890269
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

sci-libs/vtk: drop native CUDA arch

Backport from 9.2.5, until detection is fixed upstream, don't allow the use of
VTK_CUDA_ARCH=native.

Bug: https://bugs.gentoo.org/835659
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
I'm getting a bunch of test failures, otherwise this looks fine:

[vtk-9.2.5:20230122-160759.log.gz](https://github.com/gentoo/gentoo/files/10475277/vtk-9.2.5.20230122-160759.log.gz)
[LastTest.log](https://github.com/gentoo/gentoo/files/10475279/LastTest.log)

**Comment by waebbl** [comment]
Yeah, I know there's several test failures, between ~25 and ~75 depending on USE flag settings. I was thinking about restricting test, but compared to the overall number of tests running, the failures are still a tiny amount, so I decided to leave it in.

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Comment by waebbl** [comment]
Thanks for merging!

**Pull request closed without merging**
