### PR TITLE
net-misc/curl: add support for brotli

### PR DESCRIPTION
**Pull request by candrews**
*BLOCKED BY https://bugs.gentoo.org/643182*

Closes: https://bugs.gentoo.org/643184

Package-Manager: Portage-2.3.19, Repoman-2.3.6

### CODE REVIEW

**Comment by blueness** [comment]
This leads to the following build error
```Making all in lib
make[1]: Entering directory '/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0-abi_x86_32.x86/lib'
make  all-am
make[2]: Entering directory '/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0-abi_x86_32.x86/lib'
/bin/sh ../libtool  --tag=CC   --mode=compile x86_64-pc-linux-gnu-gcc -m32 -DHAVE_CONFIG_H   -I/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/include -I../lib -I/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib  -DBUILDING_LIBCURL  -DCURL_HIDDEN_SYMBOLS -I/usr/include/nss -I/usr/include/nspr -I/usr/include/p11-kit-1   -fvisibility=hidden -O2 -pipe -Werror-implicit-function-declaration -pthread  -c -o libcurl_la-content_encoding.lo `test -f 'content_encoding.c' || echo '/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/'`content_encoding.c
libtool: compile:  x86_64-pc-linux-gnu-gcc -m32 -DHAVE_CONFIG_H -I/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/include -I../lib -I/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib -DBUILDING_LIBCURL -DCURL_HIDDEN_SYMBOLS -I/usr/include/nss -I/usr/include/nspr -I/usr/include/p11-kit-1 -fvisibility=hidden -O2 -pipe -Werror-implicit-function-declaration -pthread -c /var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/content_encoding.c  -fPIC -DPIC -o .libs/libcurl_la-content_encoding.o
/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/content_encoding.c: In function ‘brotli_map_error’:
/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/content_encoding.c:549:8: error: ‘BROTLI_DECODER_ERROR_COMPOUND_DICTIONARY’ undeclared (first use in this function)
   case BROTLI_DECODER_ERROR_COMPOUND_DICTIONARY:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/content_encoding.c:549:8: note: each undeclared identifier is reported only once for each function it appears in
/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0/lib/content_encoding.c:550:8: error: ‘BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET’ undeclared (first use in this function)
   case BROTLI_DECODER_ERROR_DICTIONARY_NOT_SET:
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [Makefile:1508: libcurl_la-content_encoding.lo] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0-abi_x86_32.x86/lib'
make[1]: *** [Makefile:734: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-misc/curl-7.57.0-r1/work/curl-7.57.0-abi_x86_32.x86/lib'
make: *** [Makefile:906: all-recursive] Error 1```

**Comment by candrews** [comment]
What version of app-arch/brotli are you using?

**Comment by blueness** [comment]
let's chat on the gentoo bug.

**Comment by candrews** [comment]
@blueness app-arch/brotli now has the necessary keywords so this PR is ready to merge.

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
