### PR TITLE
dev-libs/sord: change dependency from dev-libs/libpcre to dev-libs/libpcre2

### PR DESCRIPTION
**Pull request by cfuga**
Upstream commit: https://github.com/drobilla/sord/commit/67bcd63bda9d7b095489a09b9880aa730ddb5488

Signed-off-by: Cristian Othón Martínez Vera <cfuga@cfuga.mx>

### CODE REVIEW

**Comment by fordfrog** [comment]
@cfuga thanks!

**Comment by thesamesam** [comment]
This needs a new revision (git mv is fine).

**Comment by fordfrog** [comment]
> This needs a new revision (git mv is fine).

i was thinking about it, but in fact i cannot even see the library linking against libpcre so i thought the rebuild is not really needed. so what is the exact reason? package metadata?

**Comment by cfuga** [comment]
I just checked the source code, and I found out that dev-libs/sord should only depend on libpcre2 when the USE flag ```tools``` is enabled: one of the command line tools, ```/usr/bin/sord_validate```, links against libpcre2-8.

I think we should leave this PR closed, and I'll open a new one with the described fix.

**Pull request closed without merging**
