### PR TITLE
sci-geosciences/qgis: Fix qtserialport dependency

### PR DESCRIPTION
**Pull request by doctaweeks**
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Daniel M. Weeks <dan@danweeks.net>

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks! Revbumped though to avoid the useless dependency for people.

**Comment by doctaweeks** [comment]
> Thanks! Revbumped though to avoid the useless dependency for people.

I thought by not bumping it would prevent unnecessary rebuilds since the actual linking *is* handled by the use flag. It would just avoid unnecessarily installing qtserialport or allow depcleaning it. (Binary packages aside...) Perhaps I still do not understand when/where dependencies are checked.

**Comment by thesamesam** [comment]
Sorry, to be clear, yes, I just wanted to allow unnecessarily installing it + allow depcleaning.

**Comment by doctaweeks** [comment]
I think I understand after reading: https://wiki.gentoo.org/wiki/Project:Portage/Dynamic_dependencies

I did not realize dynamic deps were not in PMS and all dependency changes still required a revbump.

**Pull request closed without merging**
