### PR TITLE
mail-filter/rspamd: version bump to 1.5.1

### PR DESCRIPTION
**Pull request by croessner**

### CODE REVIEW

**Comment by croessner** [comment]
I give up! Damn QA. There is nothing wrong with the PR. This way you really lose external devs :-(

**Comment by a17r** [comment]
Where is that Manifest file coming from? That's the problem - portage has switched to thin-manifest long ago.

**Comment by croessner** [comment]
This is the tool repoman on my binhost, which is no more than 24 hours old stage. I had created a local overlay and inside, I first removed the existing Manifest and then ran 'repoman manifest'. So if this leads to problems, then repoman is broken!

[I] app-portage/repoman
     Available versions:  ~2.3.0_rc1-r1 2.3.0-r1{tbz2} ~2.3.0-r2 2.3.1{tbz2} ~2.3.2 **9999 {PYTHON_TARGETS="pypy python2_7 python3_4 python3_5 python3_6"}
     Installed versions:  2.3.1{tbz2}(04:50:27 PM 03/02/2017)(PYTHON_TARGETS="python2_7 python3_4 -python3_5 -python3_6")
     Homepage:            https://wiki.gentoo.org/wiki/Project:Portage
     Description:         Repoman is a Quality Assurance tool for Gentoo ebuilds

I have no config file anywhere (I even don't know about any) concerning repoman.

**Comment by croessner** [comment]
Sorry, if I was a little bit angry, but I took several attemtps to get that PR done. This took time and yesterday was my day of being flooded by bugs all around. Then there comes a moment of being hateful ;-)

If somebody knows how to tell repoman that it please does not do these full manifests, leave me a reply please.

**Comment by croessner** [comment]
Fixed

**Comment by djc** [comment]
How did you manage to fix it?

**Comment by croessner** [comment]
/usr/local/portage/metadata/layout.conf:

thin-manifests = true

**Comment by a17r** [comment]
That's not something you have to take care of when you git clone from the usual places. Do you have an rsync style layout.conf for some reason?

**Comment by croessner** [comment]
Not that I am aware of. Only content:

cat layout.conf
masters = gentoo
thin-manifests = true

**Comment by djc** [comment]
But you aren't committing from a full gentoo/gentoo clone?

**Comment by croessner** [comment]
The full Gentoo clone s on my MacBook. When I do changes, I do them on my Gentoo binhost Overlay. After that I create a new branch on my Mac (of course synced before) and scp the files from binhost to Mac. Then git add, git commit, git push --set-origin bla. Opening a PR. After commit, I remove stuff from my binhost Overlay again.

**Comment by croessner** [comment]
Would you please merge it now? 😊

**Comment by djc** [comment]
Yes, cherry-picked as 0051dbffb6b1273a1b7b75ca26bc0c81283e2fca.

In the future, you should probably generate the Manifest in your git clone instead of in your overlay.

**Pull request closed without merging**
