### PR TITLE
net-analyzer/nagios-check_logfiles: Enable EAPI 6

### PR DESCRIPTION
**Pull request by nvinson**
Package-Manager: portage-2.2.25

### CODE REVIEW

**Comment by jlec** [comment]
Is this simply an EAPI bump? Which required feature are you using from EAPI=6?

**Comment by nvinson** [comment]
> Is this simply an EAPI bump?  

Yes, it's just an EAPI bump.

> Which required feature are you using from EAPI=6?

The ebuild doesn't require any EAPI 6 specific feature.  However, EAPI 6 introduces features users may find useful in the future (e.g. epatch_user) and bumping to EAPI 6 is painless.  Therefore, I made the change while working on other ebuild updates.

**Comment by jlec** [comment]
There is already ```epatch_user```so no need to require an EAPI bump now. Bumping the EAPI before we have any stable PM supporting that EAPI makes it impossible to stabilize the package for a long time. Just be aware of that.

**Comment by mgorny** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
merged

**Pull request closed without merging**
