### PR TITLE
dev-python/elasticsearch-py: bump to 2.4.1/5.1.0

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested with oracle-jdk-8 on ~amd64.

### CODE REVIEW

**Comment by gktrk** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=605812

**Comment by gktrk** [comment]
In elasticsearch itself we're ok with icedtea, why is it different for this package?

```
@@ -39,24 +39,25 @@
 		dev-python/mock[${PYTHON_USEDEP}]
 		dev-python/pretty-yaml[${PYTHON_USEDEP}]
 		dev-python/nosexcover[${PYTHON_USEDEP}]
-		|| ( virtual/jre:1.8 virtual/jre:1.7 ) )"
+		|| ( dev-java/oracle-jre-bin:1.8 dev-java/oracle-jdk-bin:1.8 ) )"
```

**Comment by hydrapolic** [comment]
I think it was because curator failed tests with icedtea. But I suppose that was caused by the version 1.7 included, so I'll change back to virtual/jre:1.8 only. Thanks.

**Comment by hydrapolic** [comment]
@gktrk, changed to virtual/jre:1.8.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/6ea819b3a4...120af8d0a8. Thanks!

**Pull request closed without merging**
