### PR TITLE
media-sound/lilypond: small improvements and fix bug #557320

### PR DESCRIPTION
**Pull request by lilrc**
I did a few minor improvements that I thought were good. If you wonder why I am only fixing version 2.18.2, it is because I plan to just copy changes to the live ebuild and then bump the 2.19 version in one go to save me some work.

Also I revbumped on each dependency change and to satisfy repoman I had to drop to ~arch so these ebuilds will have to be stabilized eventually (before bumping 2.19).

@gentoo/proxy-maint
@idella 

Also, could you confirm bug #558544 [1] (and maybe also get someone to CC arch teams, hopefully)? It annoys me that stable lilypond pulls in unstable metapost.

[1] https://bugs.gentoo.org/show_bug.cgi?id=558544

### CODE REVIEW

**Comment by idella** [comment]
No.
1. fontforge is a build depend so does not need revbumping. The current advice is set to revbump deps of RDEPEND.
2. This does apply for slotting guile
3. the final version on revbuping will be lilypond-2.18.2-r1.ebuild
4. lilypond has lilypond-2.18.2.ebuild  lilypond-2.19.15.ebuild  lilypond-9999.ebuild.
Each and all commit msgs need cite the version being edited / revbumped. These msgs leave the reader with no clue.

**Comment by lilrc** [comment]
This should fix it.

**Comment by idella** [comment]
Really not sure if this is trivia or not. The msgs
media-sound/lilypond-2.18.2: depend on fontforge[png], wrt 557320 
media-sound/lilypond-2.18.2-r1: call epatch_user 

don't quite conform to the syntax, albeit 'style'. The recommended or preferred  is;
full atm: statement of change

What you have is
full-atm-version: statement of change

the "full atm:" is therefore generic to the package. So
media-sound/lilypond-2.18.2: depend on fontforge[png], wrt 557320 
becomes
media-sound/lilypond: Set fontforge[png] in (stabled) version 2.18.2 in DEPEND wrt 557320 
or very similar.

That done, looks fine.

**Comment by lilrc** [comment]
This should fix it. :)

**Comment by idella** [comment]
Sounds vaguely familiar that. However:
Reoman full yields 

media-sound/lilypond/lilypond-9999.ebuild: RDEPEND: '>=dev-scheme/guile-1.8.2[deprecated,regex]' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator

so this also applies to the live ebuild. You can do that later.

The final patch with

media-sound/lilypond: Set fontforge[png] in (stabled) version 2.18.2 in DEPEND wrt 557320

should really be split into lines 1, blank line 2, and line 3. Just note for next time. The guide is to keep the line inside circa 70 chars but then I see many others also failing to honour this.

merged

**Pull request merged**
