### PR TITLE
net-vpn/i2pd: version bump 2.51.0 and 2.52.0

### PR DESCRIPTION
**Pull request by khumarahn**
No changes to the previous ebuild...

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. However, this seems to drop the only stable version of i2pd, namely 2.48.

**Comment by khumarahn** [comment]
I created a stabilization request for 2.50.2: https://bugs.gentoo.org/930122

**Comment by khumarahn** [comment]
version 2.50.2 is stabilizes, please merge (if everything else is acceptable)

**Comment by khumarahn** [comment]
hi!

**Comment by khumarahn** [comment]
Added a new version, 2.52.0. No changes to the previous ebuild, please review and merge

**Pull request closed without merging**
