### PR TITLE
sci-libs/tensorflow: add prefix support

### PR DESCRIPTION
**Pull request by amadio**
Package-Manager: Portage-2.3.44, Repoman-2.3.10

### CODE REVIEW

**Comment by perfinion** [comment]
@amadio looks good to me, i'm preparing the bump to 1.10-rc1 so i'll apply this all together in the next couple days

**Comment by amadio** [comment]
Ok, can I apply this to 1.9.0? Should I revbump to -r1?

**Comment by perfinion** [comment]
@amadio oh, if you want it quick then yeah sure go ahead and apply to 1.9.0. And no, dont revbump it. TF is huge so dont want to force people to rebuild.

**Comment by amadio** [comment]
> And no, dont revbump it. TF is huge so dont want to force people to rebuild.

Yeah, that's what I thought. I'll apply this now then, and when you do the version bump I'll immediately test on prefix. Thanks!

**Comment by amadio** [comment]
Merged.

**Pull request closed without merging**
