### PR TITLE
Bump pipenv 2023 4 29

### PR DESCRIPTION
**Pull request by oz123**

### CODE REVIEW

**Comment by thesamesam** [comment]
It's complaining because dev-python/toml should be avoided if possible. It's fine to "ignore" it on the Gentoo side if you file a bug upstream for yourself (lol) and handle it there.

**Comment by oz123** [comment]
Well, I can mark it conditionally for py39 py310.
I found out how other rebuilds do it.
Or I can leave it in the vendor directory.
I prefer the first option.
What do you think?

**Comment by thesamesam** [comment]
First one is fine as long as pipenv uses tomllib on 3.11.

**Comment by oz123** [comment]
@thesamesam CI should be OK now.

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
