### PR TITLE
games-engines/openmw: add live ebuild

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by a17r** [comment]
Who is going to maintain this live ebuild?

**Comment by DarthGandalf** [comment]
Does it need more maintenance than non-live one? I think live ebuild only helps with non-live one, because it can be fixed when broken, then, when new release happens, it's easy to copy the live ebuild under new name, and it should just work.

Are there some other guidelines about live ebuilds which I've missed?
In general, I do fix live ebuilds when I encounter issues with them.

**Comment by a17r** [comment]
A live ebuild makes sense if there is a dedicated maintainer to care for it. As this is not the case for openmw, this will just lead to bugs that likely no one is going to answer.

**Comment by DarthGandalf** [comment]
Ok.
I'll just keep it in my local overlay then for now, until I feel that I can commit to maintaining it :)

**Pull request closed without merging**
