### PR TITLE
Fix net-proxy/mitmproxy license

### PR DESCRIPTION
**Pull request by ixti**

### CODE REVIEW

**Comment by hydrapolic** [comment]
@ixti, you need to add  the signed-off-by to your commit message: https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Comment by ixti** [comment]
Sure. Will do.

**Comment by hydrapolic** [comment]
LGTM

**Comment by ixti** [comment]
Any news on this one?

**Comment by hydrapolic** [comment]
Now it's time for the proxy maint team to merge it. You can try to ping them on irc if you wish.

**Comment by ixti** [comment]
@hydrapolic :+1:

**Pull request closed without merging**
