### PR TITLE
net-p2p/qbittorrent: version bump & new 9999 ebuild

### PR DESCRIPTION
**Pull request by RobinDX**
Add python3 support

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/qt @hwoarang

**Comment by Pesa** [comment]
@jauhien

**Comment by jauhien** [comment]
Some fixes to ebuild needed (see 3.3.2 one). I'm going to fix it myself.

**Comment by jauhien** [comment]
@RobinDX: thanks for contribution. In the future, please, base your ebuilds n the latest version.

**Pull request merged**
