### PR TITLE
dev-php/symfony-yaml: Version bump to 2.3.19

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Closes: https://bugs.gentoo.org/696604
Signed-off-by: Guillaume Seren <guillaumeseren@gmail.com>
Package-Manager: Portage-2.3.76, Repoman-2.3.16

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I alse added the drop of the old version, not sure if I was supposed to but seem's cleaner

**Comment by GuillaumeSeren** [comment]
After asking about it on irc I changed it again to only add the bump of the ebuild,
then after 30 days I will open a stabilisation bug.

**Comment by Whissi** [comment]
Keep in mind that this package is not really a standalone package. It was added because it was needed for composer (and now for other packages). So when you update a package which is only a dependency for other packages, make sure depending packages support this new version.

**Comment by GuillaumeSeren** [comment]
Hey @Whissi ,
After quick check on dependency tree on this package I got this 
' dev-php/symfony-yaml -> dev-php/symfony-dependency-injection -> dev-php/symfony-event-dispatcher -> dev-php/symfony-console'

So basically, there is only package that use this package and it is dev-php/symfony-dependency-injection, and as long as we stay on this old 2.8.20, the supported version of dev-php/symfony-yaml are:
'symfony/yaml: ~2.3.42|~2.7.14|~2.8.7|~3.0.7'

So I think we should bump to 2.3.42, but this bump come from a query / check on repology, 
that asked for 2.3.19 specifically, maybe @mgorny have some idea on this.
https://repology.org/project/php:symfony-yaml/versions

**Comment by juippis** [comment]
Please fix the CI issue, and bump to latest available in that series (if its updated already)

**Comment by juippis** [comment]
Ping.

**Comment by GuillaumeSeren** [comment]
Hey @juippis :)

Sorry for the delay new job,
I have rebased the branch, also fixed the ci issue.

**Comment by GuillaumeSeren** [comment]
So I re-checked the dependencie tree on packagist,
actually the most up-to-date version in portage of symfony-dependency-injection is '2.8.50'.

This version ask for symfony/yaml: ~2.3.42|~2.7.14|~2.8.7|~3.0.7

So I have rewrite the ebuild for 2.8.7

**Comment by GuillaumeSeren** [comment]
I've also checked the test suite, it works
```
>>> Test phase: dev-php/symfony-yaml-2.8.7
PHPUnit 5.7.15 by Sebastian Bergmann and contributors.

...............................................................  63 / 396 ( 15%)
............................................................... 126 / 396 ( 31%)
............................................................... 189 / 396 ( 47%)
............................................................... 252 / 396 ( 63%)
............................................................... 315 / 396 ( 79%)
............................................................... 378 / 396 ( 95%)
..................                                              396 / 396 (100%)

Time: 147 ms, Memory: 6.00MB

OK (396 tests, 581 assertions)
>>> Completed testing dev-php/symfony-yaml-2.8.7
```

**Comment by Whissi** [comment]
I'll push a bunch of new ebuild shortly which will generate autoload.php in ebuild. I want to delay this PR until you can see what I am talking about so you can probably migrate to this new solution, too.

**Comment by ajakk** [comment]
> I'll push a bunch of new ebuild shortly which will generate autoload.php in ebuild. I want to delay this PR until you can see what I am talking about so you can probably migrate to this new solution, too.

Ever do this?

**Comment by SoapGentoo** [comment]
A year later, we're still waiting...

**Comment by GuillaumeSeren** [comment]
Hey,
I think it is time to close this.

**Pull request closed without merging**
