### PR TITLE
app-editors/retext: add 8.0.2

### PR DESCRIPTION
**Pull request by cjmayo**
dev-python/python-markdown-math is not used directly by ReText, it is a dependency of dev-python/markups

data/retext-kde5.png is a screenshot not an icon (an svg is installed into the hicolor theme).

### CODE REVIEW

**Comment by rndxelement** [comment]
Thanks a lot @cjmayo ! 
Your changes all make sense to me and I certainly learned a few new python tricks.
Setting `DISTUTILS_SINGLE_IMPL=1` is a great idea. 
Also thanks for cleaning up the deps, great job!
I was struggling with the desktop file for a long time, thanks for fixing.

I build and runtime tested app-editors/retext-9999 and app-editors/retext-8.0.2 on amd64 with python 3.10.

A few questions from my side:
- I wonder where the icon used in me.mitya57.ReText.desktop is getting installed. Is distutils-r1_src_install doing that?
- Did you test if it works with python 3.12?

**Comment by rndxelement** [comment]
> > ```
> > * I wonder where the icon used in me.mitya57.ReText.desktop is getting installed. Is distutils-r1_src_install doing that?
> > ```
> 
> Yes, it is listed as a data file in setup.py:
> 
> https://github.com/retext-project/retext/blob/29abe3ffac8d6c57966c51b9cddec8d815e086fb/setup.py#L146
> 
> > ```
> > * Did you test if it works with python 3.12?
> > ```
> 
> Yes, I'm using it with Python 3.12 and tests pass:
> 
> ```
> ----------------------------------------------------------------------
> Ran 50 tests in 2.682s
> 
> OK (skipped=2)
> >>> Completed testing app-editors/retext-8.0.2
> ```

Ah alright, thanks!

**Comment by rndxelement** [comment]
Closes: https://bugs.gentoo.org/929301

**Comment by mgorny** [comment]
LGTM, thanks!

**Pull request closed without merging**
