### PR TITLE
dev-java/log4j-core-java9: new package | dev-java/lmax-disruptor: new package

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
it seems they have the tests placed elsewhere or the test files need some manipulation as in my case zero tests were processed:
```
>>> Test phase: dev-java/log4j-core-java9-2.15.0
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
1 warning
JUnit version 4.13.2-SNAPSHOT

Time: 0,001

OK (0 tests)
```

**Comment by vaukai** [comment]
> it seems they have the tests placed elsewhere or the test files need some manipulation as in my case zero tests were processed:
> 
> ```
> >>> Test phase: dev-java/log4j-core-java9-2.15.0
>  * Compiling ...
> warning: [options] bootstrap class path not set in conjunction with -source 8
> 1 warning
> JUnit version 4.13.2-SNAPSHOT
> 
> Time: 0,001
> 
> OK (0 tests)
> ```
It got only one test class: [src/test/java/org/apache/logging/log4j/core/util/Dummy.java](https://github.com/apache/logging-log4j2/blob/c30a1398a6697fb832c650870c44284d0052103e/log4j-core-java9/src/test/java/org/apache/logging/log4j/core/util/Dummy.java).
Should we `RESTRICT="test"`?

**Comment by fordfrog** [comment]
> > it seems they have the tests placed elsewhere or the test files need some manipulation as in my case zero tests were processed:
> > ```
> > >>> Test phase: dev-java/log4j-core-java9-2.15.0
> >  * Compiling ...
> > warning: [options] bootstrap class path not set in conjunction with -source 8
> > 1 warning
> > JUnit version 4.13.2-SNAPSHOT
> > 
> > Time: 0,001
> > 
> > OK (0 tests)
> > ```
> 
> It got only one test class: [src/test/java/org/apache/logging/log4j/core/util/Dummy.java](https://github.com/apache/logging-log4j2/blob/c30a1398a6697fb832c650870c44284d0052103e/log4j-core-java9/src/test/java/org/apache/logging/log4j/core/util/Dummy.java). Should we `RESTRICT="test"`?

you are right. i just ran `mvn test` on the upstream tarball in `log4j-core-java9` dir and no tests were performed. sorry for the noise.

**Comment by vaukai** [comment]
@fordfrog From my perspective, all are ready to merge, except `dev-java/jackson-databind`.

**Comment by fordfrog** [comment]
@vaukai thanks! i'll try to get to it soon.

**Pull request closed without merging**
