### PR TITLE
net-analyzer/fail2ban: add python 3.10

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://bugs.gentoo.org/829374

### CODE REVIEW

**Comment by thesamesam** [comment]
Are you running tests for these? (FEATURES=test emerge ...)

**Comment by thesamesam** [comment]
Thanks ;)

Please make sure you do that for all packages. I do:
1. emerge -v1 --with-test-deps -o foo
2. ebuild foo.ebuild clean test install

**Comment by t0b3** [comment]
@thesamesam I missed some local patches from /etc/portage/patches :(

**Comment by t0b3** [comment]
maybe I messed something up? does it work for you now? if not, I'll have a look later on...

**Comment by t0b3** [comment]
OK, ready now. Watch out the dep on #23354

**Comment by thesamesam** [comment]
Thanks. Are you running tests for all of these now? Could you go back and do it for the earlier ones as well as future ones?

**Comment by t0b3** [comment]
> Thanks ;)
> 
> Please make sure you do that for all packages. I do:
> 
>     1. emerge -v1 --with-test-deps -o foo
> 
>     2. ebuild foo.ebuild clean test install

My system did run those tests, as I do have enabled tests for my local overlay with FEATURES=test via /etc/portage/package.env
Thus all my contributions have been `FEATURES=test`ed. (except #23354)

How do results differ from your solution?

**Comment by thesamesam** [comment]
> > Thanks ;)
> > Please make sure you do that for all packages. I do:
> > ```
> > 1. emerge -v1 --with-test-deps -o foo
> > 
> > 2. ebuild foo.ebuild clean test install
> > ```
> 
> My system did run those tests, as I do have enabled tests for my local overlay with FEATURES=test via /etc/portage/package.env Thus all my contributions have been `FEATURES=test`ed and run on my box since several weeks. (except #23354)
> 
> How do results differ from your solution?

They don't, I'm just verifying that you are so I don't have to stress so much over the results. :)

Usually contributors don't realise how to run the test suites of ebuilds so I just like to verify.

**Comment by t0b3** [comment]
Closed via 15dae333e924ac177f65934a4f8c0bee3d36b7d4

**Pull request closed without merging**
