### PR TITLE
mail-filter/spamassassin: fix PERL_USE_UNSAFE_INC=0 test failures

### PR DESCRIPTION
**Pull request by Philippe23**
Add "use lib '.'" calls before "use SATest" calls in tests that are
missing them.  This fixes tests that fail when the PERL_USE_UNSAFE_INC=0
env var is set.

Also mark this new package as masked, same as -r14.

Gentoo-Bug: 627678
Package-Manager: Portage-2.3.6, Repoman-2.3.1

### CODE REVIEW

**Comment by Philippe23** [comment]
For quick reference: https://bugs.gentoo.org/show_bug.cgi?id=627678

**Comment by orlitzky** [comment]
Can you mention the upstream bug number in the patch and commit message too please?

If you want to add the patch straight into the masked -r14, I think that's fine. I'm going to unmask it soon anyway.

**Comment by orlitzky** [comment]
Actually, I guess it's cleaner with an -r15, but you don't have to commit it masked (it will save me the trouble of unmasking it).

**Comment by Philippe23** [comment]
Sorry about that, the upstream bug didn't exist when I made the pull request.

Added another commit to the pull request.

-------------------------------------------------------------
 mail-filter/spamassassin: Tweaks requested by @orlitzky

 - Add upstream bug URL to patch
   ( https://bz.apache.org/SpamAssassin/show_bug.cgi?id=7462 )
 - Removed -r15 from package.mask
 - Unrequested: Renamed patch file now that there is an
   upstream bug to match the naming convention of the
   other patches

Gentoo-Bug: 627678

Package-Manager: Portage-2.3.6, Repoman-2.3.1
-------------------------------------------------------------

I presume you want them rebased into one from the "Can you mention the upstream bug number in the patch and commit message too please?" statement, but figured I'd make sure that everything was lined up before I do that.

**Comment by orlitzky** [comment]
It's fine as-is, I've already pulled it and am just running through an `emerge spamassassin` before I push it to the tree, thank you!

**Comment by orlitzky** [comment]
:thumbsup:

**Pull request closed without merging**
