### PR TITLE
sys-devel/icecream: verbump 1.3.1

### PR DESCRIPTION
**Pull request by stkw0**

### CODE REVIEW

**Comment by scardracs** [comment]
Ping: is this PR still followed? I'm interested on it

**Comment by stkw0** [comment]
> Ping: is this PR still followed? I'm interested on it

I stop using icecream but I will try to update it

**Comment by scardracs** [comment]
Ah, yes, you have to drop user and use acct-group/acct-user instead

**Comment by stkw0** [comment]
Yep, I think that why I put WIP

**Comment by scardracs** [comment]
As ID use -1, this will be fixed by devs on merge

**Comment by stkw0** [comment]
I just found there is already another PR for icecream (https://github.com/gentoo/gentoo/pull/15975) which also adds systemd services and so. I will close this PR. If you are interested it may be worth it to clone the code of the PR that I linked and add yourself as a maintainer.

**Pull request closed without merging**
