### PR TITLE
net-analyzer/pnp4nagios: EAPI=6, support >=rrdtool-1.6.0

### PR DESCRIPTION
**Pull request by sbraz**
@prometheanfire I committed straight to stable as the changes are very minor (using the right argument name).
I also bumped to EAPI=6, I didn't see anything that could be banned/deprecated but you should probably take a look in case i missed something.

### CODE REVIEW

**Comment by prometheanfire** [comment]
I don't think we can go straight to stable, also, someone else on the sysadmin team (we don't have an alias for it here...) will have to pick it up.

**Comment by robbat2** [comment]
I'll merge it after you're not going straight to stable anymore

**Comment by sbraz** [comment]
Done:
```diff
--- pnp4nagios-0.6.25-r2.ebuild	2016-04-28 20:23:55.157711250 +0200
+++ pnp4nagios-0.6.25-r3.ebuild	2016-04-28 20:24:14.467129098 +0200
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
-EAPI=5
+EAPI=6
 
 inherit depend.apache eutils
 
@@ -13,7 +13,7 @@
 LICENSE="GPL-2"
 SLOT="0"
 IUSE=""
-KEYWORDS="amd64 ~ppc ~ppc64 ~sparc ~x86"
+KEYWORDS="~amd64 ~ppc ~ppc64 ~sparc ~x86"
 
 # A lot of things (sync mode, for one) are broken with nagios-4.x.
 DEPEND="
@@ -32,6 +32,11 @@
 	media-fonts/dejavu
 	apache2? ( >=www-servers/apache-2.4[${APACHE_MODS}] )"
 
+PATCHES=(
+	"${FILESDIR}/${PN}-0.6.14-makefile.patch"
+	"${FILESDIR}/${P}-rrdtool-0.6.0-support.patch"
+)
+
 # There is no want_apache2_4, but we needed to specify that manually
 # anyway to be able to include the list of modules.
 want_apache2
@@ -40,10 +45,6 @@
 	depend.apache_pkg_setup
 }
 
-src_prepare() {
-	epatch "${FILESDIR}/${PN}-0.6.14-makefile.patch"
-}
-
 src_configure() {
 	local var_dir=
 	local user_group=

```

**Comment by robbat2** [comment]
merged in commit 8bd5f7e2bcb80e5d45d7071f2c60baf366373cce

**Pull request closed without merging**
