### PR TITLE
kde-plasma/plasma-workspace: Drop unused libXcomposite DEPEND

### PR DESCRIPTION
**Pull request by a17r**
Reported-by: awilfox (irc)

@gentoo/kde @awilfox

### CODE REVIEW

**Comment by kensington** [comment]
What's it used for? I see it in CMakeLists but not actually included anywhere.

**Comment by a17r** [comment]
I need to quote there:

``<awilfox> Cannot load org.kde.plasma.private.pager: Cannot load library /usr/lib/qt5/qml/org/kde/plasma/private/pager/libpagerplugin.so: Error loading shared library libXcomposite.so.1: No such file or directory: Needed by /usr/lib/libtaskmanager.so.5
<awilfox> seeing this on a computer that is taking binpkgs of x86 stable``

**Comment by kensington** [comment]
@awilfox are you using some custom CFLAGs, ie. no ``--as-needed``?

**Comment by awilfox** [comment]
This would be the `make.conf` for the build box:

```
# These USE will be forced onto every system.  DO NOT MODIFY THIS LIGHTLY!
USE="cxx icu -introspection ipv6 modules ssl unicode xattr"

# Auto-build packages, always, since it is a package builder :)
FEATURES="buildpkg splitdebug"

# Use curl instead of wget for fetching.
FETCHCOMMAND="curl -f -L -o \"\${DISTDIR}\"/\"\${FILE}\" \"\${URI}\""

# -O2           -> Perform second-level optimisations.
#                  Not -Os because most/all x86_64 aren't starved for space.
# -ggdb         -> Generate GDB debugging information.
#                  This is used with splitdebug.
# -march=core2  -> Require a Core 2 CPU or newer.
# -mtune=nehalem-> Tune for Nehalem processors.
#                  Most tuning for Nehalem is applicable to * Bridge and *well,
#                  and makes code more performant on the much larger base of
#                  those machines.
# -mfpmath=sse  -> Use SSE for all floating point math.
#                  Since SSE is always available, this knob ensures that GCC
#                  will always take advantage of it over preferring 387 math.
CFLAGS="-O2 -ggdb -march=core2 -mtune=nehalem -mfpmath=sse"
CXXFLAGS="${CFLAGS}"

ELIBC="musl"
```

Note that musl is slightly different with dynamic linking than glibc.  I suppose it *could* be related to USE flags; would you like the `package.use` as well?

**Comment by DmitryHetman** [comment]
KDE still doesn't works without xorg or xwayland?

**Comment by kensington** [comment]
Thanks, picked as ca18c48c16c6ee4afd70655c543838a5a301e135.

**Pull request closed without merging**
