### PR TITLE
Dev python/python language server: version bump

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
This fixes bug: https://bugs.gentoo.org/706420

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Version 0.31.8 just got released, I just updated the ebuild here to the new version.

**Comment by mattst88** [comment]
WRT pydocstyle: we have dev-python/pep257 in tree, with a bug open to rename it. (https://bugs.gentoo.org/672948)

**Comment by mattst88** [comment]
Thanks a bunch. I did that pkgmove and merged your patches with just a couple small changes. Notably, I removed the patch for pydocstyle and just rm'd the file in src_prepare(), since the patch was 33kB, over the size limit.

**Comment by AndrewAmmerlaan** [comment]
> Thanks a bunch. I did that pkgmove and merged your patches with just a couple small changes. 

Awesome, thank you!

**Comment by juippis** [comment]
Just a status update: Some tests failed, but I dont remember which. This is under investigation on my desktop pc that I should return to tomorrow. Mightve been something else weird too...
(if you can replicate failing tests and fix them before tomorrow would be awesome)

**Comment by juippis** [comment]
^ Oh and looks like my laptop had this page cached, and didnt show any discussion from yesterday.

Well if matts got them working, all good.

**Pull request closed without merging**
