### PR TITLE
net-im/skypeforlinux: Bump version to 8.53.0.85

### PR DESCRIPTION
**Pull request by jvesely**
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
I'm seeing a problem with this version on gnome where it blocks all keyboard input during video sessions.
This PR is therefore not removing the old versions, so people who experience the same thing can stay with 8.52.0.138

**Comment by gentoo-bot2** [comment]
## Pull Request assignment

*Submitter*: @jvesely
*Areas affected*: ebuilds
*Packages affected*: net-im/skypeforlinux

**net-im/skypeforlinux**: @oniGino, @jvesely, @gentoo/proxy-maint

## Linked bugs

No bugs to link found. If your pull request references any of the Gentoo bug reports, please add appropriate [GLEP 66](https://www.gentoo.org/glep/glep-0066.html#commit-messages) tags to the commit message and request reassignment.

---
In order to force reassignment and/or bug reference scan, please append `[please reassign]` to the pull request title.

*Docs*: [Code of Conduct](https://wiki.gentoo.org/wiki/Project:Council/Code_of_conduct) ● [Copyright policy](https://www.gentoo.org/glep/glep-0076.html) ([expl.](https://dev.gentoo.org/~mgorny/articles/new-gentoo-copyright-policy-explained.html)) ● [Devmanual](https://devmanual.gentoo.org/) ● [GitHub PRs](https://wiki.gentoo.org/wiki/Project:GitHub/Pull_requests) ● [Proxy-maint guide](https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide)

**Comment by juippis** [comment]
Lets hope upstream fixes it ASAP. Thanks!

**Comment by juippis** [comment]
Lets hope upstream fixes it ASAP. Thanks!

**Pull request closed without merging**
