### PR TITLE
dev-cpp/sourcetrail: Bump to 2019.1.11

### PR DESCRIPTION
**Pull request by dhallas**
Adds ebuild for Sourcetrail version 2018.4.8. No ebuild changes
compared to version 2018.3.55

Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by dhallas** [comment]
Sourcetrail 2019.1.11 is out, so I have updated the ebuild to that version instead. There are no ebuild changes compared to 2018.3.55-r1.

**Comment by dhallas** [comment]
Ping :)

**Comment by mgorny** [comment]
I'm sorry about the delay. I'll merge it now.

**Comment by dhallas** [comment]
> I'm sorry about the delay. I'll merge it now.

No problem, I know you devs are always busy ;) Thanks a lot for merging though

**Pull request closed without merging**
