### PR TITLE
sys-apps/bat: add 0.19.0

### PR DESCRIPTION
**Pull request by ixti**
* Add new version ebuild
* Add fixed version of 0.18.3 ebuild

Signed-off-by: Alexey Zapparov <alexey@zapparov.com>

### CODE REVIEW

**Comment by ixti** [comment]
@toshokan please take a look. This PR fixes 2 bug reports and adds new version of the bat :D

**Comment by toshokan** [comment]
@ixti Cursory glance looks good, thank you for the help!
I'll give this a closer look tomorrow

**Comment by Flowdalic** [comment]
@toshokan friendly ping

**Comment by ixti** [comment]
Thank you!

**Pull request closed without merging**
