### PR TITLE
media-gfx/yafaray: Don't assume python version

### PR DESCRIPTION
**Pull request by herbmillerjr**
Pull in vena.dewinter@ulukai.org's fix for python version assumption in bug https://bugs.gentoo.org/663522.

### CODE REVIEW

**Comment by mgorny** [comment]
Looks good at a first glance. I'll test it just in case and merge afterwards.

**Comment by herbmillerjr** [comment]
@mgorny You got it.

**Comment by mgorny** [comment]
You're also missing a conditional in `pkg_setup` -- it fails with `USE=-python` and empty PYTHON_SINGLE_TARGET:

```
 * No Python implementation selected for the build. Please set
 * the PYTHON_SINGLE_TARGET variable in your make.conf to one
 * of the following values:
 * 
 * python3_5 python3_6

```

**Comment by a17r** [comment]
It appears this PR is obsolete per 3d532c453bbfafd32c78e4886cb95969f961ffe6

**Pull request closed without merging**
