### PR TITLE
dev-libs/hyperscan: Version bump to 5.0.0

### PR DESCRIPTION
**Pull request by croessner**

### CODE REVIEW

**Comment by monsieurp** [comment]
@croessner ping.

**Comment by okias** [comment]
@mgorny would you push it if I send pull request as you suggested?

**Comment by okias** [comment]
Can we do something about it? @mgorny @croessner

**Comment by okias** [comment]
@mgorny https://github.com/gentoo/gentoo/pull/10864 I made a pull request, can you approve it? Thanks :)

**Pull request closed without merging**
