### PR TITLE
dev-perl/Net-SSLeay: bump version to 1.880.0

### PR DESCRIPTION
**Pull request by steils**
Closes: https://bugs.gentoo.org/684308
Closes: https://bugs.gentoo.org/686730
Package-Manager: Portage-2.3.66, Repoman-2.3.12
Signed-off-by: Stefan Strogin <steils@gentoo.org>

### CODE REVIEW

**Comment by steils** [comment]
$ diff -u Net-SSLeay-1.850.0.ebuild Net-SSLeay-1.880.0.ebuild
```
--- Net-SSLeay-1.850.0.ebuild	2019-05-21 04:55:47.813459938 +0300
+++ Net-SSLeay-1.880.0.ebuild	2019-05-25 13:16:29.471423524 +0300
@@ -3,8 +3,8 @@
 
 EAPI=6
 
-DIST_AUTHOR=MIKEM
-DIST_VERSION=1.85
+DIST_AUTHOR=CHRISN
+DIST_VERSION=1.88
 DIST_EXAMPLES=("examples/*")
 inherit multilib perl-module
 
@@ -31,13 +31,9 @@
 		virtual/perl-Test-Simple
 	)
 "
-export OPTIMIZE="$CFLAGS"
-export OPENSSL_PREFIX=${EPREFIX}/usr
 
 PATCHES=(
-	"${FILESDIR}/${PN}-1.82-respect-cflags.patch"
-	"${FILESDIR}/${PN}-1.82-fix-libdir.patch"
-	"${FILESDIR}/${PN}-1.82-fix-network-tests.patch"
+	"${FILESDIR}/${PN}-1.88-fix-libdir.patch"
 )
 PERL_RM_FILES=(
 	# Hateful author tests
@@ -49,6 +45,10 @@
 	't/local/06_tcpecho.t'
 	't/local/07_sslecho.t'
 )
+mymake=(
+	OPTIMIZE="${CFLAGS}"
+	OPENSSL_PREFIX="${EPREFIX}"/usr
+)
 
 src_configure() {
 	if use test && has network ${DIST_TEST_OVERRIDE:-${DIST_TEST:-do parallel}}; then
```

**Comment by kentfredric** [comment]
```
+mymake=(
+	OPTIMIZE="${CFLAGS}"
+	OPENSSL_PREFIX="${EPREFIX}"/usr
+)
```

I'm not sure this should be in global scope, I have no idea when/where EPREFIX is valid.

**Comment by steils** [comment]
> I'm not sure this should be in global scope, I have no idea when/where EPREFIX is valid.

Have looked at perl-module.eclass. I think yes, it would be better to declare it in `src_compile()`.
Let me check...

**Comment by steils** [comment]
Yes, it works and looks better.

$ diff -u Net-SSLeay-1.850.0.ebuild Net-SSLeay-1.880.0.ebuild
```
--- Net-SSLeay-1.850.0.ebuild	2019-05-21 04:55:47.813459938 +0300
+++ Net-SSLeay-1.880.0.ebuild	2019-05-25 13:41:19.474740510 +0300
@@ -3,8 +3,8 @@
 
 EAPI=6
 
-DIST_AUTHOR=MIKEM
-DIST_VERSION=1.85
+DIST_AUTHOR=CHRISN
+DIST_VERSION=1.88
 DIST_EXAMPLES=("examples/*")
 inherit multilib perl-module
 
@@ -31,13 +31,9 @@
 		virtual/perl-Test-Simple
 	)
 "
-export OPTIMIZE="$CFLAGS"
-export OPENSSL_PREFIX=${EPREFIX}/usr
 
 PATCHES=(
-	"${FILESDIR}/${PN}-1.82-respect-cflags.patch"
-	"${FILESDIR}/${PN}-1.82-fix-libdir.patch"
-	"${FILESDIR}/${PN}-1.82-fix-network-tests.patch"
+	"${FILESDIR}/${PN}-1.88-fix-libdir.patch"
 )
 PERL_RM_FILES=(
 	# Hateful author tests
@@ -60,3 +56,11 @@
 	export LIBDIR=$(get_libdir)
 	perl-module_src_configure
 }
+
+src_compile() {
+	mymake=(
+		OPTIMIZE="${CFLAGS}"
+		OPENSSL_PREFIX="${EPREFIX}"/usr
+	)
+	perl-module_src_compile
+}
```

**Comment by kentfredric** [comment]
Looking at upstream diffs, I'd suggest more changes here:

```
RDEPEND="
	!libressl? ( dev-libs/openssl:0= )
	libressl? ( dev-libs/libressl:0= )
	virtual/perl-MIME-Base64
"
DEPEND="${RDEPEND}
	virtual/perl-ExtUtils-MakeMaker
	test? (
		!minimal? (
			dev-perl/Test-Exception
			dev-perl/Test-Warn
			dev-perl/Test-NoWarnings
		)
		virtual/perl-Test-Simple
	)
"

```

But I don't know what changes, because upstream helpfully completely retooled the package... 

Among one of the things they changed, was how they do network tests, and your patch as is simply seems to *remove* the work done to make it behave nicely.

I don't have the attention today to review upstreams mess and rubber stamp if what you're doing looks close enough :/

**Comment by steils** [comment]
Oh. I see.

Added a patch:

```
diff --git a/Makefile.PL b/Makefile.PL
index 31d9c74..91ac2b4 100644
--- a/Makefile.PL
+++ b/Makefile.PL
@@ -12,11 +12,7 @@ use Symbol qw(gensym);
 # the Net-SSLeay loadable object on Windows
 my $win_link_statically = 0;
 
-my $tests = prompt(
-  "Do you want to run external tests?\n".
-  "These tests *will* *fail* if you do not have network connectivity.",
-  'n',
-) =~ /^y/i ? 't/*/*.t t/*/*/*.t' : 't/local/*.t t/handle/local/*.t';
+my $tests = ( 'yes' eq ( $ENV{NETWORK_TESTS} || '' ) ) ? 't/*/*.t t/*/*/*.t' : 't/local/*.t t/handle/local/*.t';
 
 my %eumm_args = (
   NAME => 'Net::SSLeay',
```

**Comment by KyleSanderson** [comment]
Any update on this? Current stable package doesn't build at all with libressl.

**Pull request closed without merging**
