### PR TITLE
Various quality of life tweaks following new RPi changes

### PR DESCRIPTION
**Pull request by chewi**
This is in response to the feedback I have received. Hopefully this improves things a little.

### CODE REVIEW

**Comment by chewi** [comment]
CC @parona-source.

**Review by ionenwks — APPROVED** [review]
Ok for mpv, USE feels kind of meh but I don't really have better to suggest to improve UX.

**Comment by chewi** [comment]
Okay, merged, thanks. Sorry for not waiting for further feedback here, but I was keen to address the default `REQUIRED_USE` issue. Let me know if there are further issues.

**Comment by thesamesam** [comment]
I wonder if we could have a meta/virtual instead which would hold back upgrades for us.

**Pull request closed without merging**
