### PR TITLE
x11-terms/mlterm: drop optional gtk2 support

### PR DESCRIPTION
**Pull request by epsilon-0**
Closes: https://bugs.gentoo.org/769029
Package-Manager: Portage-3.0.14, Repoman-3.0.2

### CODE REVIEW

**Comment by Arfrever** [comment]
Only 3.9.1 and no revision bump.

**Review by a17r — CHANGES_REQUESTED** [review]
ping - and don't bother with the older version.

**Comment by Arfrever** [comment]
For reviewability, changes in this pull-request are:
```
--- x11-terms/mlterm/mlterm-3.9.0.ebuild
+++ x11-terms/mlterm/mlterm-3.9.0-r1.ebuild
@@ -1,4 +1,4 @@
-# Copyright 1999-2020 Gentoo Authors
+# Copyright 1999-2021 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI="7"
@@ -11,9 +11,8 @@
 
 LICENSE="BSD"
 SLOT="0"
-KEYWORDS="amd64 ppc ppc64 x86"
-IUSE="bidi brltty cairo canna debug fbcon fcitx freewnn gtk gtk2 harfbuzz ibus libssh2 m17n-lib nls regis scim skk static-libs uim utempter wayland xft"
-REQUIRED_USE="gtk2? ( gtk )"
+KEYWORDS="~amd64 ~ppc ~ppc64 ~x86"
+IUSE="bidi brltty cairo canna debug fbcon fcitx freewnn gtk harfbuzz ibus libssh2 m17n-lib nls regis scim skk static-libs uim utempter wayland xft"
 
 RDEPEND="x11-libs/libICE
 	x11-libs/libSM
@@ -25,10 +24,7 @@
 	fbcon? ( media-fonts/unifont )
 	fcitx? ( app-i18n/fcitx )
 	freewnn? ( app-i18n/freewnn )
-	gtk? (
-		gtk2? ( x11-libs/gtk+:2 )
-		!gtk2? ( x11-libs/gtk+:3 )
-	)
+	gtk? ( x11-libs/gtk+:3 )
 	harfbuzz? ( media-libs/harfbuzz[truetype(+)] )
 	ibus? ( app-i18n/ibus )
 	libssh2? ( net-libs/libssh2 )
@@ -96,11 +92,13 @@
 	local tools="mlclient,mlcc,mlfc,mlmenu,${PN}-zoom"
 	if use gtk; then
 		myconf+=(
-			$(use_with gtk gtk $(usex gtk2 2.0 3.0))
+			--with-gtk=3.0
 			--with-imagelib=gdk-pixbuf
 		)
 		scrollbars+=",pixmap_engine"
 		tools+=",mlconfig,mlimgloader"
+	else
+		myconf+=( --without-gtk )
 	fi
 	if use regis; then
 		tools+=",registobmp"
--- x11-terms/mlterm/mlterm-3.9.1.ebuild
+++ x11-terms/mlterm/mlterm-3.9.1-r1.ebuild
@@ -1,4 +1,4 @@
-# Copyright 1999-2020 Gentoo Authors
+# Copyright 1999-2021 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI="7"
@@ -12,8 +12,7 @@
 LICENSE="BSD"
 SLOT="0"
 KEYWORDS="~amd64 ~ppc ~ppc64 ~x86"
-IUSE="bidi brltty cairo canna debug fbcon fcitx freewnn gtk gtk2 harfbuzz ibus libssh2 m17n-lib nls regis scim skk static-libs uim utempter wayland xft"
-REQUIRED_USE="gtk2? ( gtk )"
+IUSE="bidi brltty cairo canna debug fbcon fcitx freewnn gtk harfbuzz ibus libssh2 m17n-lib nls regis scim skk static-libs uim utempter wayland xft"
 
 RDEPEND="x11-libs/libICE
 	x11-libs/libSM
@@ -25,10 +24,7 @@
 	fbcon? ( media-fonts/unifont )
 	fcitx? ( app-i18n/fcitx )
 	freewnn? ( app-i18n/freewnn )
-	gtk? (
-		gtk2? ( x11-libs/gtk+:2 )
-		!gtk2? ( x11-libs/gtk+:3 )
-	)
+	gtk? ( x11-libs/gtk+:3 )
 	harfbuzz? ( media-libs/harfbuzz[truetype(+)] )
 	ibus? ( app-i18n/ibus )
 	libssh2? ( net-libs/libssh2 )
@@ -96,11 +92,13 @@
 	local tools="mlclient,mlcc,mlfc,mlmenu,${PN}-zoom"
 	if use gtk; then
 		myconf+=(
-			$(use_with gtk gtk $(usex gtk2 2.0 3.0))
+			--with-gtk=3.0
 			--with-imagelib=gdk-pixbuf
 		)
 		scrollbars+=",pixmap_engine"
 		tools+=",mlconfig,mlimgloader"
+	else
+		myconf+=( --without-gtk )
 	fi
 	if use regis; then
 		tools+=",registobmp"
```

**Comment by Arfrever** [comment]
(By the way, next version will have at least partial support for GTK 4: `https://github.com/arakiken/mlterm/issues/6`)

**Comment by epsilon-0** [comment]
done

**Pull request closed without merging**
