### PR TITLE
 net-libs/gtk-vnc: Properly generate vala files when USE='vala'

### PR DESCRIPTION
**Pull request by ganto**
Closes: https://bugs.gentoo.org/654588

### CODE REVIEW

**Comment by leio** [comment]
Please don't change old version, any changes should be a change to 0.8 instead (revbump if necessary).
The real question here is -- should vala support exist at all, if no-one noticed it before, maybe that's just pointless to have, and we should instead keep passing `--disable-vala` and remove the redundant vala deps and eclass stuff instead. In other words - did you just notice this, or actually need the vala support? This appears to be the generation of some .vapi files for consuming by vala apps or something.

**Comment by ganto** [comment]
Ok, I'll force push the change only for `net-libs/gtk-vnc-0.8.0-r1`.

I can't speak for the original bug reporter, but I noticed this "bug" when I tried to build `gnome-boxes-3.28.5` using the new meson build system. Then I got an error:
```
error: Package `gtk-vnc-2.0' not found in specified Vala API directories or GObject-Introspection GIR directories
Compilation failed: 1 error(s), 0 warning(s)
```

With this fix and USE="vala", `gnome-boxes` builds successfully.

**Comment by leio** [comment]
(older) gnome-boxes in main tree doesn't have a gtk-vnc[vala?] dependency. Does the problem happen with the main tree version as well? Does it fail for you without a fixed gtk-vnc, I mean. And I presume you have USE=vala on gnome-boxes then, right?

**Comment by ganto** [comment]
No, it doesn't happen with the main tree version. As far as I understand using the meson build system vala is not optional anymore. For gnome 3.28 most ebuilds require vala support to be enabled.

**Pull request closed without merging**
