### PR TITLE
dev-python/graph-tool: bump to 2.39

### PR DESCRIPTION
**Pull request by gerion0**
Patch is backported from
https://git.skewed.de/count0/graph-tool/-/commit/ee5cd8e8da8c35b56694d03eb9d63fb30b61702e

Closes: https://bugs.gentoo.org/795603

The entire ebuild is _not_ well tested. I have just compiled it and it can be imported within Python without a crash. Currently, when linking against the C++ headers, I got compilation errors, will evaluate this further.

### CODE REVIEW

**Comment by gerion0** [comment]
Please do _not_ apply this. There is another (more boost compatible) 2.38 release (from just now). I will update this pull request.

**Comment by gerion0** [comment]
Upstream made another follow up release: 2.39. This version should compile fine against boost 1.76.0. No patch required.
Again, I have only tested compilation and loading in the Python interpreter.

**Comment by gerion0** [comment]
Hmm, upstream has done another release. I close this and reopen a pull, when all problems are fixed.

**Comment by SoapGentoo** [comment]
You dont have to close pull requests, just rebase yoru changes

**Pull request closed without merging**
