### PR TITLE
sys-apps/darwin-miscutils: EAPI8 bump, ebuild improvments

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This updates `sys-apps/darwin-miscutils` for `EAPI8`. Afaics every version is for a different MacOS Version, which is why i've updated all of them. So far, the prominet changes are:
* adding a lot of missing `|| die`
* updated all SRC_URI's and added Apple's github homepage
* quoted some variables and defined the variable `t` as local where it's used.
* using `edo` for compiling files - and removed a lot of `echo`'s with this
* using `eapply` instead of `epatch`
* fixed `AbsoluteSymlink`

I don't have any MacOS so i couldn't test much here. I only made sure the patches can be applied.

Open issues:
* SRC_URI are able to download the files, but most of the files get `Filesize does not match recorded size`. I haven't updated the manifest since i cannot test it. This probably should be fixed.
* The `md` source file for version 10,11 and 12 is also directly downloaded from github via `https://github.com/apple-oss-distributions/adv_cmds/blob/c8dbac91aa855b2d05282f45709b318f8bc3693d/md/md.c -> adv_cmds-md-${MD_VER}.c`. This works and the `SIZE` matches that of the `Manifest`, but i'm not sure if it's fine to use such links.
* ~~Since i added the github links i also though about to update `metadata.xml`, However since we download sources from multiple repositories I wasn't sure if I could add multiple upstream. I would add something like this:~~

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE pkgmetadata SYSTEM "https://www.gentoo.org/dtd/metadata.dtd">
<pkgmetadata>
	<maintainer type="project">
		<email>prefix@gentoo.org</email>
		<name>Gentoo Prefix</name>
	</maintainer>
	<upstream>
		<remote-id type="github">apple-oss-distributions/adv_cmds</remote-id>
		<remote-id type="github">apple-oss-distributions/misc_cmds</remote-id>
		<remote-id type="github">apple-oss-distributions/shell_cmds</remote-id>
		<remote-id type="github">apple-oss-distributions/developer_cmds</remote-id>
	</upstream>
</pkgmetadata>
```

### CODE REVIEW

**Comment by grobian** [comment]
glep 46 specifically allows mulitple remote-ids, it doesn't say anything about whether the type must be distinct, so I presume this would be allowed

**Comment by mm1ke** [comment]
> glep 46 specifically allows mulitple remote-ids, it doesn't say anything about whether the type must be distinct, so I presume this would be allowed

Thanks for the clarification :)

**Comment by grobian** [comment]
I find `edo` to do be a bit odd in this case, you get output like: ```
 * arm64-apple-darwin22-gcc -O2 -pipe -I. -D__FBSDID=__RCSID -Du_int=uint32_t -include stdint.h -o shlock -Wl,-dead_strip_dylibs shlock.c
in /Users/ruurd/Gentoo-13/var/tmp/portage/sys-apps/darwin-miscutils-12-r1/work/shell_cmds-203/time:
```
not that it hurts or anything

**Comment by grobian** [comment]
thanks for bringing this to my attention, darwin-miscutils-12 compiles/installs fine on ppc-darwin9, so let me first cleanup some versions here

**Comment by grobian** [comment]
regarding the hashes, them sulkers re-created the archives with different names/directories (which more looks like a bug than a good thing, but bleh :( )

**Comment by mm1ke** [comment]
> regarding the hashes, them sulkers re-created the archives with different names/directories (which more looks like a bug than a good thing, but bleh :( )

great.. :/ so in that case the ebuilds would need to be adapted i guess ..

**Comment by grobian** [comment]
yes, doing that now, thanks again

**Comment by grobian** [comment]
I've cleaned it all up in ff8ba2125096

**Pull request closed without merging**
