### PR TITLE
media-libs/mesa: nouveau: add missing vl lib

### PR DESCRIPTION
**Pull request by MocioF**
https://gitlab.freedesktop.org/eric/mesa/-/commit/6d276b55312f26c839d1091e1b1f4029d72c64f0

Closes: https://bugs.gentoo.org/921658

### CODE REVIEW

**Comment by mattst88** [comment]
Upstream issue: https://gitlab.freedesktop.org/mesa/mesa/-/issues/10792

Patch landed in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28133
Patch reverted in https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28226 after causing issue https://gitlab.freedesktop.org/mesa/mesa/-/issues/10830

**Comment by mattst88** [comment]
Looks like https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/26680 is the new potential fix.

**Comment by MocioF** [comment]
Yes, it should be.
Sorry for the PR, I sent it when they merged this into main
https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/28133
I will test the new code and update this PR if it will work (just let's wait a couple of days to see what happens upstream)

**Comment by Flowdalic** [comment]
@MocioF It appears this PR can be closed?

**Comment by MocioF** [comment]
Yes @Flowdalic, I will do it now.

**Pull request closed without merging**
