### PR TITLE
xen: add 4.16.4/4.17.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Dropping https://gitweb.gentoo.org/proj/xen-upstream-patches.git/ and replacing with regular release. 4.17.1 contains security fixes.

Compile tested on amd64.

```bash
--- xen-4.17.1_pre1.ebuild      2023-04-17 09:30:54.456777675 +0000
+++ xen-4.17.1.ebuild   2023-05-02 22:24:51.352038816 +0000
@@ -16,8 +16,8 @@
 
        XEN_GENTOO_PATCHSET_NUM=0
        XEN_GENTOO_PATCHSET_BASE=4.17.0
-       XEN_PRE_PATCHSET_NUM=0
-       XEN_PRE_VERSION_BASE=4.17.0
+       XEN_PRE_PATCHSET_NUM=
+       XEN_PRE_VERSION_BASE=
 
        XEN_BASE_PV="${PV}"
        if [[ -n "${XEN_PRE_VERSION_BASE}" ]]; then
```

```bash
--- xen-tools-4.17.1_pre1.ebuild        2023-04-19 09:32:14.828593657 +0000
+++ xen-tools-4.17.1.ebuild     2023-05-02 22:23:07.548614829 +0000
@@ -25,8 +25,8 @@
 
        XEN_GENTOO_PATCHSET_NUM=0
        XEN_GENTOO_PATCHSET_BASE=4.17.0
-       XEN_PRE_PATCHSET_NUM=0
-       XEN_PRE_VERSION_BASE=4.17.0
+       XEN_PRE_PATCHSET_NUM=
+       XEN_PRE_VERSION_BASE=
 
        XEN_BASE_PV="${PV}"
        if [[ -n "${XEN_PRE_VERSION_BASE}" ]]; then
```

### CODE REVIEW

**Comment by hydrapolic** [comment]
Hello @Flowdalic

**Comment by hydrapolic** [comment]
Friendly ping @Flowdalic :)

**Comment by Flowdalic** [comment]
> Friendly ping @Flowdalic :)

Thanks for the reminder. I was on a business trip last week so this could have been easily missed by me.

**Comment by hydrapolic** [comment]
Thanks @Flowdalic !

**Pull request closed without merging**
