### PR TITLE
apache2.eclass: use REQUIRED_USE for dependency tracking

### PR DESCRIPTION
**Pull request by DerDakon**
@Polynomial-C

### CODE REVIEW

**Comment by flappyports** [comment]
@DerDakon Please discuss this eclass change on the gentoo-dev mailing list. This is a Gentoo requirement before eclass changes are merged.

**Comment by Polynomial-C** [comment]
This looks promising. I will give it a try soon and either merge it or will request changes here. No discussion on gentoo-dev mailing list necessary.

**Comment by DerDakon** [comment]
Added 2 missing spaces.

**Comment by DerDakon** [comment]
ping?

**Comment by Polynomial-C** [comment]
Sorry for the long delay...

**Pull request closed without merging**
