### PR TITLE
media-tv/kodi: version bump 17.1

### PR DESCRIPTION
**Pull request by candrews**
Package-Manager: Portage-2.3.5, Repoman-2.3.2

### CODE REVIEW

**Comment by candrews** [comment]
@SoapGentoo separated into two commits as requested. I'll make sure to do it that way in the future, too.

**Comment by mudler** [comment]
There is a reason why in this bump (17.1) there is no system-ffmpeg useflag?

**Comment by candrews** [comment]
@mudler just a mistake, I'll rectify in the next ebuild bump.

**Comment by mudler** [comment]
as a side note, ffmpeg is still required when vdpau useflag is enabled:

https://gitweb.gentoo.org/repo/gentoo.git/tree/media-tv/kodi/kodi-17.0-r1.ebuild#n87

**Pull request closed without merging**
