### PR TITLE
dev-ml/ocaml-pcap: new ebuild

### PR DESCRIPTION
**Pull request by tomboy-64**
- needed as a transitive dependency of Libre S3 1.1 (net-misc/libres3)
- explicit support for MirageOS is not enabled

PR as per [bug #559652](https://bugs.gentoo.org/show_bug.cgi?id=559652) for @aballier .

### CODE REVIEW

**Comment by aballier** [comment]
@mgorny: wtf ?

**Comment by mgorny** [comment]
You are **killing** CI hardware. Please do not ever tell users to open a dozen pull requests like that. Not to mention those pull requests are cross-dependent, so the CI results will be useless. And please **do not** reopen something before discussing it with person who closed it.

**Comment by aballier** [comment]
The idea behind several PRs is that they can be merged independently.

Just disable CI if that's a real issue instead of closing something before discussing it with those that asked it that way.

**Comment by hasufell** [comment]
> Just disable CI if that's a real issue instead of closing something before discussing it with those that asked it that way.

If commits depend on each other, you always send a single PR and that is common standard in the opensource world (also, you may get tons of false-positives from CI otherwise). If you need help with git workflow, you can ask other developers (e.g. how to diff best).

Anyway, for any given PR on github you can always just review the commits instead of the merge commit. So there's really not much of a difference.

**Comment by aballier** [comment]
yeah i agree interdependencies mess it up

what would be best would be to have 1 PR per package but only have PRs with no interdependencies (i.e. open those that have deps after)

**Comment by hasufell** [comment]
I'd go so far to say that a patch series via mail is almost easier to review in this case. Then send one PR to trigger a CI run.

**Pull request closed without merging**
