### PR TITLE
media-gfx/flameshot: new package

### PR DESCRIPTION
**Pull request by relkochta**
> Flameshot is a powerful, simple, customizable screenshot application written in C++ using Qt. Flameshot allows for easy annotating, copying, pasting, uploading, and more. It is licensed under the GNU General Public License version 3 or higher.

* https://github.com/lupoDharkael/flameshot

Signed-off-by: Ryan El Kochta <relkochta@lightn1ng.space>

### CODE REVIEW

**Comment by relkochta** [comment]
I have just now added a -9999 ebuild.

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by maksbotan** [comment]
Added in c8519f723d963b46b3ff2137d9ac7d498af94a57.

**Comment by a17r** [comment]
@maksbotan Please join proxy-maintainers if you want to add (and hopefully help with proxy-maintaining) new packages.

**Comment by maksbotan** [comment]
@a17r I'm pretty sure I was in, maybe I was removed from proxy-maint some time ago. If so, I'll rejoin.

**Pull request closed without merging**
