### PR TITLE
net-libs/tox: use snapshot to fetch sources wrt bug #585728

### PR DESCRIPTION
**Pull request by zetok**
Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by krifisk** [comment]
Summary should be cleaned up and move bug reference to body with a description and Gentoo-Bug: 58728 label

Copyright needs updating to current year

Although not erroneous the use flags "log-debug log-error log-info log-trace log-warn  +no-log" seems a bit messy, is this level of control useful?

**Comment by zetok** [comment]
>Summary should be cleaned up and move bug reference to body with a description and Gentoo-Bug: 58728 label

Hopefully I did this right.

>Copyright needs updating to current year

Done.

>Although not erroneous the use flags "log-debug log-error log-info log-trace log-warn +no-log" seems a bit messy, is this level of control useful?

Depends. It was useful for me some time ago.. and would be useful for anyone who would want to provide more useful info for debugging than just "doesn't work, halp", or debug by themselves. So it's primarily for toxcore & tox clients developers, and people who would want to help them.
For people who aren't interested in e.g. reporting bugs and/or helping debug stuff, who are interested in "only" using toxcore as a dependency of the client they're using, no so much.

**Comment by krifisk** [comment]
wouldn't an optional log-debug use flag satisfy that? removing the need for REQUIRED_USE and reduce complexity?

**Comment by zetok** [comment]
toxcore's "debug" level is almost always overly verbose, to the point where logs would become almost useless – thus there are several logging levels, usually something below "debug" would do the job. Then again, sometimes "debug" also can be useful for something.

**Comment by Amynka** [comment]
Did you mean by this snapshot to be pre-release? If yes then I am afraid It should be 0_preYYYYMMDD not 0_pYYYYMMDD.

**Comment by zetok** [comment]
>Did you mean by this snapshot to be pre-release? If yes then I am afraid It should be 0_preYYYYMMDD not 0_pYYYYMMDD.

No, at least if I understood docs correctly: "Alternatively, the snapshot may be treated as a pre-release to an upcoming version, usually used when a release is anticipated but not out yet."

I.e. toxcore cannot into versions – proper versions were supposed to be started for it half a year ago, and.. nothing. That is, @irungentoo said that versions will be started once new A/V code will be merged – still no versions, even though the code was merged. And it doesn't look like there will be any releases any time soon.

Unless that doesn't matter, and snapshot of toxcore repo at some commit should be treated as pre-release version, even though there are no actual releases, nor there will be in any near future, or it would seem so?

Additionally, toxcore itself claims that its version is `0.0.0`.

I might be wrong about no release in any near future, but I am simply not aware of anything that would point at some release actually happening.

**Comment by Amynka** [comment]
Well it has to be _pre anyway if this is not _p (patchset)

**Comment by zetok** [comment]
I see. Should I amend current commit?

**Comment by zetok** [comment]
Done.

**Pull request closed without merging**
