### PR TITLE
[WIP] dev-vcs/gitg: Bump to 3.32.0

### PR DESCRIPTION
**Pull request by mgorny**
Signed-off-by: Michał Górny <mgorny@gentoo.org>

---
SEGVs for me; help appreciated.

### CODE REVIEW

**Comment by mgorny** [comment]
Apparently an upstream issue: https://gitlab.gnome.org/GNOME/gitg/issues/213

**Comment by xdch47** [comment]
From Upstream:
https://gitlab.gnome.org/gaurav1999/gitg/commit/6c1efff19963d7f931806cfd1d15216d494fa123.patch

**Comment by mgorny** [comment]
FTR, I'm waiting for next upstream release.

**Comment by xdch47** [comment]
Closed by https://github.com/gentoo/gentoo/commits/5e39de2657

**Pull request closed without merging**
