### PR TITLE
dev-lisp/sbcl: remove unused patch

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes a unused patch from dev-lisp/sbcl.
If possible please assign this PR to project **gentoo/common-lisp** or it's members.
Please review.

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint @nvinson

**Comment by nvinson** [comment]
I would like the commit to mention which patch is being removed.  Other than that, I'm okay with committing this PR.

**Comment by mm1ke** [comment]
I've updated the commit message and included the filename.

**Comment by Amynka** [comment]
Thanks !

**Pull request closed without merging**
