### PR TITLE
**/metadata.xml: Replace http by https in DOCTYPE element

### PR DESCRIPTION
**Pull request by ulm**
Bug: https://bugs.gentoo.org/552720

### CODE REVIEW

**Comment by mgorny** [comment]
Do you recall what was the issue when jlec last tried it? repoman hardcoding the URL?

**Comment by ulm** [comment]
> Do you recall what was the issue when jlec last tried it? repoman hardcoding the URL?

See bug 552720 (linked above). Should be fixed with this commit:
https://gitweb.gentoo.org/proj/portage.git/commit/?id=3950d76df63cf0f3f6502014dd61b8aa9c260e36

**Review by mgorny — APPROVED** [review]
Let's do it then.

**Comment by floppym** [comment]
If our tooling has been update, this seems fine to me. Viewing the file list locks up my web browser, so I can't actually approve this in github.

We should also update the templates in app-vim/gentoo-syntax.

**Comment by ulm** [comment]
Merged.

**Pull request closed without merging**
