### PR TITLE
sys-power/apcupsd: systemd depend on network

### PR DESCRIPTION
**Pull request by johnreitan**
Update the systemd service file to match the openrc dependency on the
network to be up.

### CODE REVIEW

**Comment by Whissi** [comment]
This is bug https://bugs.gentoo.org/show_bug.cgi?id=625692

I am not sure if we should accept this PR: It is questionable whether *acpusd* is primarily a network service or not. From this point of view, if you use *acpusd* as a network service, then you also have to adjust dependencies in your init system. I.e. in OpenRC world you would be required to set `rc_need="net.<your_Interface>` when you create a listener or set `rc_use="dns"` when your *acpusd* instance will connect to an APC network service/device via hostname (when you are using net-misc/netifrc to manage your network). In systemd's world you are supposed to overwrite the default service unit if you have such a requirement.

If we would accept the PR we would add an requirement on network.target, i.e. acpusd.service, when enabled, would try to start network. So if we are going to merge this, I would at least drop the *Wants=*.

I checked some other distributions and I only found Fedora shipping with `After=network-online.target`.

**Comment by johnreitan** [comment]
So it we just do the After= step and drops the Wants= it should solve the bug creator's issue and not cause any other issues?

**Comment by Whissi** [comment]
In general, yes. But remember: The service unit isn't supposed to work on all possible configurations. For example, if I connect to a remote UPS via FQDN and use *unbound* for DNS resolution, just waiting for *network.-online.target* might not be enough. In OpenRC world you are supposed to set `rc_use="dns"` and *unbound* would provide *dns*. In systemd world you would have to overwrite the service, i.e. create */etc/systemd/system/acpuspd.service.d/depend-on-dns.conf* with 
```
[Unit]
After=unbound.service
```
for example.

**Comment by johnreitan** [comment]
So we might then actually reject the bug (and PR) with an advice to read the systemd documentation about setting up dependencies. I'm not running any systemd systems to verify this on... Thanks for your comments.

**Pull request closed without merging**
