### PR TITLE
LXQt 1.1.0 and Friends

### PR DESCRIPTION
**Pull request by Chiitoo**
Not yet fully tested.

Some point releases may be appearing soon.

### CODE REVIEW

**Comment by Chiitoo** [comment]
So far build tests and all look good on my stable test machine.  \ö/

**Comment by Dessa** [comment]
it would be nice to have [xdg-desktop-portal-lxqt](https://github.com/lxqt/xdg-desktop-portal-lxqt) added to that list

**Comment by Chiitoo** [comment]
I have been eyeing that but was also kind of waiting for someone to ask for it... so thank you!

Will add it tomorrow or so.

**Comment by Chiitoo** [comment]
For 'app-misc/qtxdg-tools' I brought over the keywords from 'dev-libs/libqtxdg' which had parts of it split into a separate repository.

Will still need to also test the new bits on my cleaner test machine.

**Comment by thesamesam** [comment]
Is this ready? Also, consider xdg.eclass in future.

**Comment by Chiitoo** [comment]
Aside from the conflict, yeah, should be good and thank you!

**Pull request closed without merging**
