### PR TITLE
Move {dev-util → dev-build}/icmake

### PR DESCRIPTION
**Pull request by LinuxUserGD**
According to the project's README, "Icmake can be used as an alternative to make"
Moved `dev-util/icmake` to `dev-build/icmake`

### CODE REVIEW

**Review by mgorny — CHANGES_REQUESTED** [review]
Thanks. However, you need to update copyright dates on all ebuilds and add a `pkgmove` entry to `profiles/updates/1Q-2024`.

**Comment by thesamesam** [comment]
`pkgcheck scan --commits` should show that.

**Comment by LinuxUserGD** [comment]
Thanks, updated the ebuilds

**Review by mgorny — APPROVED** [review]
Thanks!

**Pull request closed without merging**
