### PR TITLE
Bump tox and toxic; also update PYTHON_COMPAT

### PR DESCRIPTION
**Pull request by xWNgLWT0mQf**

### CODE REVIEW

**Comment by thesamesam** [comment]
Please fix the CI failure - let us know if you need help.

**Comment by xWNgLWT0mQf** [comment]
My apologies, I failed to recognize that tox-0.2.18-r3 > tox-0.2.18. So an error did exist where I thought none did.

**Comment by xWNgLWT0mQf** [comment]
I believe that the error above is in error. The indicated error for toxic-0.15.1 is "DEPEND="net-libs/tox[experimental]": USE flag 'experimental' missing from packages: [ net-libs/tox-0.2.13-r1, net-libs/tox-0.2.18-r3 ]" with a siimilar message for RDEPEND. While this statement is correct, the tox-0.15.1 ebuild requires >=tox-0.2.19, which has the required use flag.

**Comment by thesamesam** [comment]
It doesn't deduplicate the deps, so `experimental? ( net-libs/tox[experimental] )` should really be >= to avoid the warning even if it is harmless in practice.

**Pull request closed without merging**
