### PR TITLE
media-sound/gtklick: Initial import.

### PR DESCRIPTION
**Pull request by lilrc**
Imported from the proaudio overlay.

A build log can be found at:
https://karll.portknox.net/index.php/s/0t9l7CV8byzTwcS

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
LGTM.

**Comment by monsieurp** [comment]
There's a missing `die ||` that I've added in 1fedf83876f5fee4922919de1ddd0e05b83047a8.

**Comment by lilrc** [comment]
Thanks!

**Pull request closed without merging**
