### PR TITLE
app-misc/qlcplus: Bump to v4.12.5, v5.0.0_beta1 and remove old

### PR DESCRIPTION
**Pull request by kripton**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Jannis Achstetter <kripton@kripserver.net>
Closes: https://bugs.gentoo.org/830558

### CODE REVIEW

**Comment by kripton** [comment]
Rebased and forced-pushed due to #26153. Please merge that before this one, thanks!

**Review by juippis — COMMENTED** [review]
There's so much going on in here it's a bit hard to review. I'd suggest re-doing this (either rebase off, or save your work with git stash etc)

1: Bump to 4.12.5 in a separate commit. I can't see the whole ebuild file in here, but you can most likely update to EAPI-8, and fix these too:
```
 * QA Notice: .desktop files with MimeType= were found installed
 * but desktop mimeinfo cache has not been updated:
 *   /usr/share/applications/qlcplus.desktop
 *   /usr/share/applications/qlcplus-fixtureeditor.desktop
 * Please make sure to call xdg_desktop_database_update()
 * in pkg_postinst() and pkg_postrm() phases of appropriate pkgs.
 * QA Notice: mime-info files were found installed but mime-info
 * cache has not been updated:
 *   /usr/share/mime/packages/qlcplus.xml
 * Please make sure to call xdg_mimeinfo_database_update()
 * in pkg_postinst() and pkg_postrm() phases of appropriate pkgs.
```
(these appear due to the udev changes, you have to manually call the `xdg` functions)

Then I'd remove all versions below 4.12.5, or 4.12.4 and not modify them at all.

Then update 5.0.0_alpha with the udev thing if you wish.

Note that test phase fails for me on all versions, but runtime seems fine. Just if you have ideas / if there's an issue in upstream about:
```
./test.sh: line 10: lrelease: command not found
********* Start testing of QLCi18n_Test *********
Config: Using QtTest library 5.15.5, Qt 5.15.5 (x86_64-little_endian-lp64 shared (dynamic) release   build; by GCC 12.1.1 20220625), gentoo 2.8
PASS   : QLCi18n_Test::initTestCase()
PASS   : QLCi18n_Test::defaultLocale()
PASS   : QLCi18n_Test::translationFilePath()
XFAIL  : QLCi18n_Test::loadTranslation() No translation for this locale. Fail is OK.
   Loc: [qlci18n_test.cpp(55)]
FAIL!  : QLCi18n_Test::loadTranslation() Compared values are not the same
   Actual   (QLCi18n::loadTranslation("qlci18n")): 0
   Expected (true)                               : 1
   Loc: [qlci18n_test.cpp(59)]
PASS   : QLCi18n_Test::cleanupTestCase()
Totals: 4 passed, 1 failed, 0 skipped, 0 blacklisted, 0ms
********* Finished testing of QLCi18n_Test *********
/var/tmp/portage/app-misc/qlcplus-4.12.5/work/qlcplus-QLC-_4.12.5
1 Engine unit tests failed. Please fix before commit.
make: *** [Makefile:679: check] Error 1
emake failed
 * ERROR: app-misc/qlcplus-4.12.5::gentoo failed (test phase):
 *   Failed to run 'emake check'
```

**Comment by kripton** [comment]
@juippis : Thanks for the review and your comments.
I've split the changes to 4 commits as you proposed, updated the ebuilds to EAPI 8 and also bumped the 5.0.0 from alpha to beta.

Regarding the tests: Indeed, they currently fail and it is known to the upstream project (https://github.com/mcallegari/qlcplus/issues/1344) and will be fixed with the next release (https://github.com/mcallegari/qlcplus/pull/1349). Would you prefer to
* just ignore it for this version
* disable the test phase in the ebuilds for now
* add the changes as an additional patch so the tests won't fail?

**Review by juippis — APPROVED** [review]
I would prefer to include them. I'll add the patch to 4.12.5, it didn't apply for 5.0.0 anymore. Thanks!

**Pull request closed without merging**
