### PR TITLE
net-im/discord-bin-0.0.5.ebuild - rewrite ebuild

### PR DESCRIPTION
**Pull request by oniGino**
This rewrite offers better handling of electron files installed into
/opt

https://bugs.gentoo.org/660870

### CODE REVIEW

**Comment by johu** [comment]
Ping. Any progress on the review comments from Whissi?

**Comment by oniGino** [comment]
> Ping. Any progress on the review comments from Whissi?

Hey, so I did a re-write on this.

**Comment by oniGino** [comment]
I'm totally in support of that
, I could see a argument either way which is why i added the use flag when I submitted a bug for net-im/slack 
(same problem)

**Comment by oniGino** [comment]
hello?

**Comment by oniGino** [comment]
all changes fixed here, any more feedback?

**Pull request closed without merging**
