### PR TITLE
Fplll5.4.0

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-3.0.9, Repoman-3.0.2
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>

### CODE REVIEW

**Comment by kiwifb** [comment]
@orlitzky is the bot broken? I expected some reports from it including it assigning to you in minutes.

**Comment by orlitzky** [comment]
Beats me.Happy to take a look though (at fplll, not the bot).

**Comment by kiwifb** [comment]
Upstream released your fix for qd so I added it.  Your fix relied on the presence of pkg-config so I added it to BDEPEND. Otherwise it is fairly straightforward.

**Comment by orlitzky** [comment]
LGTM. Merged, thanks!

**Pull request closed without merging**
