### PR TITLE
Rdepend on sys-fs/lvm2 because of /opt/VirtualBox/VBoxVolInfo

### PR DESCRIPTION
**Pull request by atom-symbol**

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks a lot for your PR. Is there a bug number associated to this fix?

**Comment by atom-symbol** [comment]
There's no bug number. I find it too complicated. You are free to take the patch if you like.

**Comment by monsieurp** [comment]
Sorry but we cannot merge your PR because of the last commit you've pushed (merging master into the PR is a bad idea) and lacking information as to why this dependency is needed (sys-fs/lvm2 because of /opt/VirtualBox/VBoxVolInfo is obvious but without a bug number and no background, we cannot just merge this change). File a bug and/or provide a more detailed report and we'll consider your contribution. Thank you.

**Comment by atom-symbol** [comment]
One more try: https://github.com/gentoo/gentoo/pull/756

**Pull request closed without merging**
