### PR TITLE
sys-apps/hwloc: new version

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Closes: https://bugs.gentoo.org/699076
Closes: https://bugs.gentoo.org/698620
Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
@ultrabug ping

**Comment by ultrabug** [comment]
Hi @Alessandro-Barbieri 

I'm sorry I don't even know what those packages are. I can surely quick review them and merge them considering that I trust your testing

Would that sound okay ?

**Comment by Alessandro-Barbieri** [comment]
Thanks for the trust
the TL;DR is
version bump
now netloc is merged into hwloc an I added a !netloc dep

**Comment by ultrabug** [comment]
@Alessandro-Barbieri 

Can you please fix :

```
  <flag name="gl">Enable GL display device discovery (NVCtrl)</flag> 
warning: 1 line adds whitespace errors.

```

then we're good to go

**Comment by ultrabug** [comment]
Thanks

**Pull request closed without merging**
