### PR TITLE
sys-kernel/genkernel-next; resolves 719968.

### PR DESCRIPTION
**Pull request by FlyingWaffleDev**
Closes:  [https://bugs.gentoo.org/719968](url)
Allows genkernel-next to be emerged with latest BusyBox.
Credit goes to Iade Gesso <iade.gesso@gmail.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
The problem is that genkernel-next has a large amount of other bugs which are unresolved. If somebody is willing to step up and fix these, that'd be welcome.

**Comment by FlyingWaffleDev** [comment]
From what I've seen of the 28 bugs for gnekernel-next in Gentoo's bug tracker, most of them seem to be related to upstream patches, upstream bugs, and even a request to merge genkernel-next back into genkernel.  Given that genkernel-next seems to have been basically abandoned for the last 4 to 6 years... well I don't think I'm capable of solving that mess.

**Comment by iadegesso** [comment]
@FlyingWaffleDev thank you!

I'm not so skilled in gentoo commits... I'm not able to understand why "Mergin is blocked" :(


Iade

**Comment by thesamesam** [comment]
I think that's exactly the problem. It is dead software, and anything other than someone willing to maintain the software and fix its problems is prolonging the inevitable.

**Comment by iadegesso** [comment]
> I think that's exactly the problem. It is dead software, and anything other than someone willing to maintain the software and fix its problems is prolonging the inevitable.

Personally, I found genkernel-next perfect for my dracut-based boot chain... so... I prefer it stay alive...

**Comment by thesamesam** [comment]
Obsolete since it's been removed.

**Pull request closed without merging**
