### PR TITLE
net-im/qtox: depend on slotted net-libs/tox

### PR DESCRIPTION
**Pull request by zetok**
To make sure that it it's compiling against the right API version.

### CODE REVIEW

**Comment by mgorny** [comment]
To be honest, this is quite weird. Why would it enforce a specific subslot? We usually this kind of stuff for binary packages only.

**Comment by zetok** [comment]
>To be honest, this is quite weird. Why would it enforce a specific subslot?

For quick iteration of versions with differing API and no support for installing versions in parallel. I.e. from my understanding, slots are there to allow install of different versions in parallel, something that toxcore doesn't support. Thus the use of subslots. Given the incoming API breakage(s), stuff depending on toxcore should depend on the version (subslot) they are targeting.

`net-libs/tox` most likely will get new versions released on a weekly, or bi-weekly basis. A released version might, or might not break API. If it breaks API, I'll just bump the subslot in the new ebuild, so that clients would still build & work with the version (subslot) they are targeting.

**Comment by mgorny** [comment]
Hmm, so you're using subslots for API and not ABI? Then I guess it's fine though unusual.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/22a4540...ac24461. Thanks!

**Pull request closed without merging**
