### PR TITLE
dev-libs/{dee,glib,gobject-introspection,libsxlt,qof}: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from:
dev-libs/dee
dev-libs/glib
dev-libs/gobject-introspection
dev-libs/libxslt
dev-libs/qof

If possible please assign this PR to project **gentoo/gnome** or it's members.
Please review.

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/gnome

**Comment by leio** [comment]
dev-libs/libxslt/files/libxslt.m4-libxslt-1.1.26.patch is still in use
Rest would seem fine, but can't go deleting an in-use patch.
https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/libxslt/libxslt-1.1.29.ebuild#n45

**Comment by mm1ke** [comment]
@leio Thanks for reviewing.
I've updated my PR and fixed the libxslt commit. Should be fine now. :)

**Comment by mm1ke** [comment]
ping,
I've just rebased my PR. Any chance we could merge this?

**Comment by mm1ke** [comment]
ping. just rebased my PR. :)

**Comment by mm1ke** [comment]
ping, just another rebase of my PR :)

**Pull request closed without merging**
