### PR TITLE
sys-power/acpi: bump version to 1.7

### PR DESCRIPTION
**Pull request by axelgenus**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
DESCRIPTION   is 97 chars long.   Need be reduced. Sorry could have pointed that out from the beginning.

**Comment by idella** [comment]
the content need be re-worded to come to <= 80 chars., for both the acpi-1.6 and the bump.

**Comment by axelgenus** [comment]
I added a long description in metadata.xml and replaced the DESCRIPTION field inside the ebuilds in order to comply with the limit.

**Pull request merged**
