### PR TITLE
dev-python/pymongo: version bump

### PR DESCRIPTION
**Pull request by jauhien**
Posted for review. If no comments I'll push it in the next week.

### CODE REVIEW

**Comment by jauhien** [comment]
@ultrabug

**Comment by ultrabug** [comment]
any diff wrt to previous version ? (apart from EAPI), guess a 3.x clean up wouldn't hurt too

**Comment by jauhien** [comment]
I didn't clean up it, just tested that it works ok and also added new python version support: 3_5. That's all.

**Comment by ultrabug** [comment]
Then ok, go ahead mate, I'll take a mental note to do it later myself, thx

**Comment by jauhien** [comment]
Thanks, pushed.

**Pull request closed without merging**
