### PR TITLE
app-misc/elasticsearch: package maintenance

### PR DESCRIPTION
**Pull request by Kangie**
- add 8.10.4; drop 8.10.3
- mask on musl; add glibc as RDEPEND: (https://bugs.gentoo.org/833856)
- subslot by major version (`0/7`, `0/8`)

### CODE REVIEW

**Comment by Kangie** [comment]
@hydrapolic any issues?

The subslots here are still exclusive, but if you emerge the `0/7` slot you will never receive 8.x releases as updates.

**Comment by hydrapolic** [comment]
> @hydrapolic any issues?
> 
> The subslots here are still exclusive, but if you emerge the `0/7` slot you will never receive 8.x releases as updates.

Hey @Kangie, thanks for the updates. Haven't tested yet, but don't you need to add cross blockers so that you don't get both versions if you have elasticsearch without version constraints in package.accept_keywords?

**Comment by Kangie** [comment]
> don't you need to add cross blockers so that you don't get both versions if you have elasticsearch without version constraints in package.accept_keywords?

I don't think so, it'll just do the current thing and pick the highest version if you don't specify a (sub)slot.

**Comment by Kangie** [comment]
oh oops this didn't get merged and I undid all of my progress. Damn.

**Comment by thesamesam** [comment]
thanks, merged w/ revbumps for the 7.x subslots as they're not new ebuilds here

**Pull request closed without merging**
