### PR TITLE
sci-libs/armadillo: Version bump

### PR DESCRIPTION
**Pull request by marbre**
Package-Manager: portage-2.2.20

### CODE REVIEW

**Comment by marbre** [comment]
@akhuettel AFAIR, you maintain this package and maybe you would like to merge.

**Comment by akhuettel** [comment]
Thanks, added (as cherry-picked commit).
Not sure if this PR is closed automatically, you may have to do it manually (I can't).

**Comment by hasufell** [comment]
> Not sure if this PR is closed automatically, you may have to do it manually

see https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Pull_requests_from_users

**Comment by junghans** [comment]
Hmm, it might be useful to add a line like "Closes gentoo/gentoo#41" in the comment message to close pull-request automatically.

**Comment by hasufell** [comment]
In addition the gpg user signature was invalidated by the cherry-pick. That's why the wiki suggests a proper merge. But it seems people don't really read nor follow it.

**Comment by akhuettel** [comment]
@hasufell please cool down a bit... I promise to do better next time, but not everyone reads the entire novel before his very first attempt... and we do discourage merge commits usually. (what's the point of the merge commit if the user branch contributes exactly one commit? it's not as if a branch history is lost...)

**Comment by hasufell** [comment]
> and we do discourage merge commits usually

never heard or read about that

**Comment by akhuettel** [comment]
pointless merge commits, to be more precise.

**Comment by hasufell** [comment]
> what's the point of the merge commit if the user branch contributes exactly one commit? it's not as if a branch history is lost

The point was primarily to keep user gpg signatures. Otherwise there is no way to verify the _authorship_ of the contributor after the cherry-pick anymore. It also gives information on the state of the commit (where it happened in the history, before it was accepted) and gives an easy overview of non-developer commits.

**Comment by kensington** [comment]
The wiki page is very nice but it's essentially just your opinion. It's not productive to harass every single committer because they didn't do something the way you like.

**Comment by hasufell** [comment]
> The wiki page is very nice but it's essentially just your opinion.

That's not true. It was discussed on the ML.

**Comment by kensington** [comment]
Please provide references where consensus was achieved that the monster bikesheds were accepted as policy.

**Comment by hasufell** [comment]
There was only one bikeshed and the result is that the related policy was _not_ included. Please search the ML yourself.

**Comment by kensington** [comment]
What related policy?

**Comment by hasufell** [comment]
How to reference bug reports.

**Comment by kensington** [comment]
How is that relevant here?

**Comment by mrueg** [comment]
The wiki page collects best practices and is just a recommendation. If you have think we lack commit policies, please choose a proper place for your mission. Either use the glep process or provide patches to devmanual, discuss them on the ml and get it accepted (as this is really wide-ranging) by the council. Thanks.

**Comment by hasufell** [comment]
> How is that relevant here?

you asked

**Comment by kensington** [comment]
I asked for a reference that the wiki page is an accepted policy, and you started talking about referencing bug reports.

**Comment by hasufell** [comment]
> The wiki page collects best practices and is just a recommendation. If you think we lack commit policies, please choose a proper place for your mission. Either use the glep process or provide patches to devmanual, discuss them on the ml and get it accepted (as this is really wide-ranging) by the council. Thanks.

The wiki page was up for almost one year and discussed heavily over that period. It was even discussed again when the git migration started. Since there were _zero_ objections at that point, we removed the "this is a draft" note.

But I can see that some people who don't raise their opinion for over one year and then just do their own thing need a GLEP for this.

**Comment by hasufell** [comment]
> I asked for a reference that the wiki page is an accepted policy, and you started talking about referencing bug reports.

stop trolling please

**Comment by kensington** [comment]
Asking for a reference (which you still haven't provided) is hardly trolling.

**Comment by hasufell** [comment]
> Asking for a reference (which you still haven't provided) is hardly trolling.

I told you check the ML yourself. You should have learned how to do that in your recruitment process.

**Comment by kensington** [comment]
Now who's trolling.

**Comment by kensington** [comment]
Please stop deleting parts of the discussion. It's very inappropriate.

**Comment by hasufell** [comment]
I have deleted spam.

**Comment by kensington** [comment]
You are abusing your power as a repository owner to censor conversation.

**Comment by hasufell** [comment]
You are spamming this issue report and I will delete it again.

**Comment by kensington** [comment]
That's not your decision to make. I thought you of all people would appreciate the importance of keeping things open.

**Comment by hasufell** [comment]
All relevant comments are still in place. Can you please stop now?

**Comment by kensington** [comment]
Can you stop censoring the discussion please?

**Comment by hasufell** [comment]
I'm out of here, too much trolling. *sigh*

**Comment by kensington** [comment]
Just to be clear for anyone else reading, a number of comments here were silently and deliberately removed. I therefore suggest treating this - and any other discussion thread on github - with a grain of salt.

**Pull request closed without merging**
