### PR TITLE
dev-util/vulkan-headers: sdk update to 1.3.261

### PR DESCRIPTION
**Pull request by Miezhiko**

### CODE REVIEW

**Comment by mattst88** [comment]
This should be updated along with the whole suite of Vulkan and SPIR-V packages, as well as glslang.

**Comment by mattst88** [comment]
cc: @sarnex

**Comment by sarnex** [comment]
Sorry, I was away for a few days. @Miezhiko, yeah at matt said, we need to bump all the packages at once. Are you willing to do this?

**Comment by yann-boyer** [comment]
I would love to help but I don't have the skills for sadly, even though I'm a C++ programmer, I never maintained linux packages.

**Comment by sarnex** [comment]
I just bumped the whole stack. Thanks for your contribution in this PR

**Pull request closed without merging**
