### PR TITLE
net-misc/spice-gtk: depend on any automake version

### PR DESCRIPTION
**Pull request by t0b3**
change to recent automake version
automake 1.12 has been used since Jan 2013

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thanks for the PR. Please read https://wiki.gentoo.org/wiki/Gentoo_Github.

**Comment by monsieurp** [comment]
ping?

**Comment by t0b3** [comment]
Hi, I'm not yet familiar with gentoo repo on github PR yet.
@monsieurp I hope, I changed things correctly and the changes comply
feel free to sqash my commits
just a question: is there a way to edit online on github and squash multiple changes into one commit?

**Comment by monsieurp** [comment]
Thanks. Is there a bug report associated with this change? Could you explain to us the rationale here? Why would spice-gtk depend on any automate version? Cheers.

**Comment by t0b3** [comment]
Thanks for comment. There is no bug report. The purpose is to fade out dependencies on automake 1.12 where possible...
other automake version are supported by upstream as well e.g. https://cgit.freedesktop.org/spice/spice-gtk/commit/?id=49816b49005e82565c20a66ad89c72cba2692962
Can you agree?
Cheers

only few ebuilds in portage still depend on automake-1.12...
/usr/portage/dev-python/pythonmagick/pythonmagick-0.9.12.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/dev-python/pythonmagick/pythonmagick-0.9.14.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/lxde-base/lxdm/lxdm-0.4.1-r9.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/net-misc/spice-gtk/spice-gtk-0.31.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/net-misc/spice-gtk/spice-gtk-0.32-r1.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/net-misc/spice-gtk/spice-gtk-0.32-r2.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/net-misc/spice-gtk/spice-gtk-9999.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/sys-cluster/pacemaker/pacemaker-1.1.12-r2.ebuild:WANT_AUTOMAKE="1.12"
/usr/portage/sys-cluster/pacemaker/pacemaker-1.1.14.ebuild:WANT_AUTOMAKE="1.12"

**Comment by t0b3** [comment]
@monsieurp ping... ready to remove invalid flag now?

**Comment by monsieurp** [comment]
ping @gentoo/virtualization

**Comment by leio** [comment]
I had independently filed https://bugs.gentoo.org/show_bug.cgi?id=613600 and then got pointed to here. So there's your bugzilla report now finally.

**Comment by mgorny** [comment]
```
commit eb1f8065a3f28dcf92222d2f6da50f4912eea447
Author:     Matthias Maier <tamiko@gentoo.org>
AuthorDate: Thu May 11 07:24:35 2017
Commit:     Matthias Maier <tamiko@gentoo.org>
CommitDate: Thu May 11 07:24:35 2017

    net-misc/spice-gtk: remove WANT_AUTOMAKE, bug #613600
    
    Package-Manager: Portage-2.3.5, Repoman-2.3.2
```

I guess it was done independently but thanks nevertheless.

**Pull request closed without merging**
