### PR TITLE
sys-apps/roccat-tools-3.6.1 & dev-libs/libgaminggear-0.11.1: version bump (Bug 559954)

### PR DESCRIPTION
**Pull request by dpisklov**
sys-apps/roccat-tools-3.6.1 & dev-libs/libgaminggear-0.11.1: version bump

### CODE REVIEW

**Comment by monsieurp** [comment]
I'll take a look at it today

**Comment by mgorny** [comment]
@gentoo/proxy-maint

**Comment by hwoarang** [comment]
Patches are being discussed on the respective bug. Please do not merge this yet.

**Comment by hwoarang** [comment]
"Merge branch 'master' of github.com:/dpisklov/gentoo"

what's the point of this commit?

**Comment by dpisklov** [comment]
It's autogenerated by git when you do pull before you will be able to push.
15 сент. 2015 г. 19:11 пользователь "Markos Chandras" <
notifications@github.com> написал:

**Comment by hasufell** [comment]
> It's autogenerated by git when you do pull before you will be able to push.

nah, you can pull with a rebase... the gentoo git workflow suggest to do:
```
git pull --rebase origin master
```
in case of push-conflicts. In addition, for PR-branches you want to force-push to update them.

**Comment by dpisklov** [comment]
Well I wasn't quite sure if it's good idea after doing rebase -i.
But you can always cherry pick if you're so scared of merge commits...
For now it just looks like process for the sake of the process.
15 сент. 2015 г. 19:14 пользователь "Julian Ospald" <
notifications@github.com> написал:

**Comment by hwoarang** [comment]
we can do a cherry-pick but this does seem a good opportunity for you to do things properly when submitting pull requests for git based projects. if that's too much hassle i will just cherry-pick them.

**Comment by hasufell** [comment]
Right, you can:
1. create a new PR-branch which is based off of the current gentoo/gentoo repo (not yours)
2. cherry-pick your own commits from your old PR-branch
3. force-push from your new PR-branch to your old PR-branch

figuring out all the steps with the correct commands would indeed be good exercise

**Comment by dpisklov** [comment]
Well that's becoming too much of a hassle. That's not my first pull request
and I used git for quite a while on my current job, and never had any
issues...
Even though I do understand where you're coming from and do appreciate
those rules now, for I obviously kind of misunderstood the level of
granularity you're looking for - redoing all this just for the process is a
bit painful.
15 сент. 2015 г. 19:19 пользователь "Markos Chandras" <
notifications@github.com> написал:

**Comment by hwoarang** [comment]
ok i will cherry pick them then

**Comment by dpisklov** [comment]
Thanks Markos for understanding.
Next time I'll try to do it properly, I promise :)
(And given how frequent are roccat-tools releases, that's to be very soon)

On 15 September 2015 at 19:31, Markos Chandras <notifications@github.com>
wrote:

> ok i will cherry pick them then
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/gentoo/gentoo/pull/91#issuecomment-140492007>.
>



-- 
Best regards,
Dmitry V. Pisklov

**Comment by hwoarang** [comment]
The latest PR you have around does not include the following commit from your previous PR

cfda66a sys-apps/roccat-tools: dependency incompatibility fix 

can you please list the hashes which you want me to cherry-pick?

**Comment by dpisklov** [comment]
cfda66a9
a06792c2
2af34c66
ea1ad5c3
2d83cf9a
15 сент. 2015 г. 21:18 пользователь "Markos Chandras" <
notifications@github.com> написал:

**Comment by hwoarang** [comment]
Ok i merged them but I had to edit them myself since the workflow says to only use Category/Package without the version. Please close this full request since the hashes do not match anymore and github wont do it automatically

**Comment by dpisklov** [comment]
OK sure, thanks Markos and sorry for screwing this up...
15 сент. 2015 г. 21:41 пользователь "Markos Chandras" <
notifications@github.com> написал:

**Comment by hasufell** [comment]
@hwoarang another way would be to cherry-pick his commits on a non-master branch and then merge them back with an enforce merge commit (`--no-ff`) into master... then you can append something like `closes #91` in the commit message which will make github close this automatically and create references

but that might be considered overkill

**Pull request closed without merging**
