### PR TITLE
cmake-utils--

### PR DESCRIPTION
**Pull request by a17r**
In the year 2021 we don't use cmake-utils anymore.

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
ACK, description could use some work, this is just a cleanup of old ebuilds, but yeah, ACK, thanks

**Comment by a17r** [comment]
> ACK, description could use some work, this is just a cleanup of old ebuilds, but yeah, ACK, thanks

How would you improve it?

**Comment by ZeroChaos-** [comment]
"cleanup old ebuilds".  No changes were made, saying things like
"cmake-utils shouldn't be used in 2021" makes me think that you were
actually modifying something, rather than just dropping old ebuilds.

**Comment by a17r** [comment]
But that's just on github.

**Pull request merged**
