### PR TITLE
games-strategy/hedgewars: Bump to version 0.9.24_rc1

### PR DESCRIPTION
**Pull request by CaseOf**
hedgewars is available on a first release candidate for 0.9.24, it adds improvements on Qt5 support.
It's actually on release candidate mainly because of issues on Microsoft Windows builds, and is working nicely on Linux distributions.
Also, an issue on MakeFiles about building local server have been fixed, so I added a use flag for those who want to build it.
First release candidate mercurial commit 6313386c851e is matching commit in ebuild from their Github mirror.

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Superseded by commit efb8f5c1462cc3e6b4dae373724cd8a78e9acf48

**Comment by CaseOf** [comment]
And about the server USE flag? Why is it still ignored?

**Comment by Polynomial-C** [comment]
Sorry, it seems I missed that one. Can you please file a new PR on top of hedgewars-0.9.24?

**Comment by CaseOf** [comment]
made a new PR with a new bugfix release 0.9.24.1 with it

**Pull request closed without merging**
