### PR TITLE
Bump app-misc/qlcplus to 4.10.3

### PR DESCRIPTION
**Pull request by kripton**
Bump app-misc/qlcplus to 4.10.3

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. A version bump requires both a new file added to the Manifest as well as the ebuild to install the new version. You're missing the latter.

**Comment by monsieurp** [comment]
@xmw

**Comment by kripton** [comment]
@monsieurp I'm not sure I understand. This pull requests does add an ebuild and modifies the Manifest. What exactly is missing?

**Comment by monsieurp** [comment]
Oh sorry, I didn't see the 1st commit. :+1: 
Could you format the commit message as well?

**Comment by kripton** [comment]
No problem, will do so. Is there any documentation on how to format them?

**Comment by monsieurp** [comment]
Yes, there is: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by kripton** [comment]
Great, thanks for the link. I've made one commit out of it and pushed again

**Pull request closed without merging**
