### PR TITLE
sys-apps/shadow: 4.14.3-r1 set HOME_MODE to 0700

### PR DESCRIPTION
**Pull request by weseven**
Sets `HOME_MODE` to 0700 in `/etc/login.defs`.

When `HOME_MODE` is unset, useradd to use the default umask 022 when creating users and their home directories, resulting in world-readable home directories (that get flagged in security assessments).
Many distros set HOME_MODE to 0700 by default, as this only affects useradd and newusers when creating home directories.
Currently in gentoo (and in upstream) it is commented out:
https://github.com/shadow-maint/shadow/blob/3e59e9613ec40c51c19c7bb5c28468e33a4529d5/etc/login.defs#L207

The only change is at line 168 of shadow-4.14.3-r1.ebuild, adding
```
set_login_opt HOME_MODE 0700
```

Thanks!

### CODE REVIEW

**Comment by floppym** [comment]
> Many distros set HOME_MODE to 0700 by default

Please provide examples of this. I hesitate to change such a long-standing default without really good justification.

**Comment by floppym** [comment]
[Debian](https://salsa.debian.org/debian/shadow/-/blob/master/debian/login.defs?ref_type=heads#L156) has it commented out.

[Ubuntu](https://git.launchpad.net/ubuntu/+source/shadow/tree/debian/login.defs#n156) sets it to 0750.

[Fedora](https://src.fedoraproject.org/rpms/shadow-utils/blob/rawhide/f/shadow-utils.login.defs#_122) sets it to 0700.

**Comment by weseven** [comment]
Sorry, I should have provided examples, here are a couple more:

[Arch linux](https://gitlab.archlinux.org/archlinux/packaging/packages/shadow/-/blob/main/0003-Add-Arch-Linux-defaults-for-login.defs.patch?ref_type=heads#L40) sets it to 0700.
[OpenSuse](https://build.opensuse.org/package/view_file/openSUSE:Factory/shadow/shadow-login_defs-suse.patch?expand=1) sets it to 0700 (line 75).
RHEL & RHEL derived distro have it at 0700 (I've checked shadow-utils-4.9-8.el9.x86_64.rpm through a subscription).

**Comment by floppym** [comment]
My preference would be to stick with the upstream default (respect umask) unless some consensus is reached among gentoo devs to vary from that default.

**Comment by thesamesam** [comment]
> Please raise this for discussion on the gentoo-dev mailing list if you feel strongly about it.

I'll go further and say _please do_. Just make sure to subscribe to the ML first.

**Comment by weseven** [comment]
I've sent a message in the ML, I think it's at least worth discussing :)

**Comment by alejandro-colomar** [comment]
Could you put here a lint to the ML discussion?  Thanks!

**Comment by thesamesam** [comment]
https://marc.info/?l=gentoo-dev&m=170758415218730&w=2

**Pull request closed without merging**
