### PR TITLE
sys-freebsd: Fix multiple Security Advisory and Errata.

### PR DESCRIPTION
**Pull request by nigoro**
Security Advisory
https://security.freebsd.org/advisories/FreeBSD-SA-16:38.bhyve.asc
https://security.freebsd.org/advisories/FreeBSD-SA-16:37.libc.asc

Errata
https://security.freebsd.org/advisories/FreeBSD-EN-16:21.localedef.asc

I got an error when applying a patch to freebsd-ubin.
If patch is applied with ${WORKDIR} instead of ${S}, the problem is solved.

Note, S="${WORKDIR}/usr.bin" is defined in freebsd-ubin-11.0-r1.ebuild.
```
$ cat /var/tmp/portage/sys-freebsd/freebsd-ubin-11.0-r1/temp/freebsd-ubin-EN-1621-localedef.patch.out
***** freebsd-ubin-EN-1621-localedef.patch *****
PWD: /var/tmp/portage/sys-freebsd/freebsd-ubin-11.0-r1/work/usr.bin
PATCH TOOL: gpatch -> /usr/bin/gpatch
VERSION INFO:
GNU patch 2.7.5
Copyright (C) 2003, 2009-2012 Free Software Foundation, Inc.
Copyright (C) 1988 Larry Wall

License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Larry Wall and Paul Eggert

================================================

PATCH COMMAND:  gpatch -p0 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/var/tmp/portage/sys-freebsd/freebsd-ubin-11.0-r1/distdir/freebsd-ubin-EN-1621-localedef.patch'

================================================
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c.orig
|+++ contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
can't find file to patch at input line 14
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- usr.bin/localedef/ctype.c.orig
|+++ usr.bin/localedef/ctype.c
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored
can't find file to patch at input line 38
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- usr.bin/localedef/parser.y.orig
|+++ usr.bin/localedef/parser.y
--------------------------
No file to patch.  Skipping patch.
2 out of 2 hunks ignored

patch program exited with status 1
================================================

PATCH COMMAND:  gpatch -p1 -g0 -E --no-backup-if-mismatch  --dry-run -f < '/var/tmp/portage/sys-freebsd/freebsd-ubin-11.0-r1/distdir/freebsd-ubin-EN-1621-localedef.patch'

================================================
can't find file to patch at input line 3
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|--- contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c.orig
|+++ contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c
--------------------------
No file to patch.  Skipping patch.
1 out of 1 hunk ignored
checking file localedef/ctype.c
checking file localedef/parser.y

patch program exited with status 1
================================================
```

### CODE REVIEW

**Comment by mgorny** [comment]
Doesn't upstream use a stable -p level for patches?

**Comment by nigoro** [comment]
Is patch level bump better than revision bump ?
And, if I change the file name, is it OK ?

freebsd-lib-10.3-r3.ebuild --> freebsd-lib-10.3_p3.ebuild
freebsd-lib-11.0-r1.ebuild --> freebsd-lib-11.0_p1.ebuild
freebsd-ubin-11.0.ebuild --> freebsd-ubin-11.0_p1.ebuild

**Comment by mgorny** [comment]
You did misunderstood my question. Can those patches be applied without `cd` if you pass e.g. `epatch -p1`? Are all upstream patches suitable for the same `-p` option?

> Is patch level bump better than revision bump ?

Well, strictly speaking, we do tend to use _p when we're fetching official patches/updates upstream rather than combining Gentoo sets of patches.

> And, if I change the file name, is it OK ?

Yes, that's fine. As long as the newer version still evaluates as newer, there's no problem for users.

**Comment by nigoro** [comment]
> You did misunderstood my question. Can those patches be applied without cd if you pass e.g. epatch -p1?

Sorry for my misunderstanding. 

cd to "${WORKDIR}" is required.
contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c exists in "${WORKDIR}"
If S="$ {WORKDIR}/usr.bin" is set, epatch strives to apply the patch in "${S}".

> Are all upstream patches suitable for the same -p option?

All upstream patches do not require -p option of patch command.
That means, the same as -p0 option.


>     Is patch level bump better than revision bump ?
> 
> Well, strictly speaking, we do tend to use _p when we're fetching official patches/updates upstream rather than combining Gentoo sets of patches.
> 
>     And, if I change the file name, is it OK ?
> 
> Yes, that's fine. As long as the newer version still evaluates as newer, there's no problem for users.

ok, thanks. I'll change file name next time.
(I don't have time to try Gentoo/FreeBSD for several days.)

**Comment by mgorny** [comment]
>> You did misunderstood my question. Can those patches be applied without cd if you pass e.g. epatch -p1?

> Sorry for my misunderstanding. 

No problem.

> cd to "${WORKDIR}" is required.
> contrib/netbsd-tests/lib/libc/locale/t_mbstowcs.c exists in "${WORKDIR}"
> If S="$ {WORKDIR}/usr.bin" is set, epatch strives to apply the patch in "${S}".

Oh, so all patches are suitable for applying in WORKDIR? Then it's good with me.

> > Are all upstream patches suitable for the same -p option?

> All upstream patches do not require -p option of patch command.
> That means, the same as -p0 option.

Nice to know that. If you want to fiddle a bit, you may try using 'eapply -p0' in EAPI 6 and see if it all works fine.

>>     Is patch level bump better than revision bump ?
> 
> Well, strictly speaking, we do tend to use _p when we're fetching official patches/updates upstream rather than combining Gentoo sets of patches.
> 
>     And, if I change the file name, is it OK ?
> 
> Yes, that's fine. As long as the newer version still evaluates as newer, there's no problem for users.

> ok, thanks. I'll change file name next time.
(I don't have time to try Gentoo/FreeBSD for several days.)

Cool, no hurry with that. It's not like the name is breaking anything ;-).

**Comment by mgorny** [comment]
Note that I've reordered the commits so the eclass change comes first. I presume it's necessary for one of the patches to apply.

**Pull request closed without merging**
