### PR TITLE
Mintlib removal

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Review by thesamesam — APPROVED** [review]
Happy.

**Comment by grobian** [comment]
ok

**Comment by SoapGentoo** [comment]
@grobian I'd like to remove `elibc_FreeBSD` too now, are you onboard with that?

**Comment by grobian** [comment]
is Gentoo/FreeBSD dead?  If yes, go ahead and do it.  Prefix dropped support for it long ago already.

**Comment by SoapGentoo** [comment]
yes, Gentoo/FreeBSD is dead since 2018 and we've removed support for it long ago too.

**Comment by thesamesam** [comment]
not enough of it is gone, lots of mint-like crust we can drop (mainly elibc_freebsd)

**Comment by SoapGentoo** [comment]
@grobian can we remove `kernel_AIX` too?

**Comment by grobian** [comment]
ack

**Pull request closed without merging**
