### PR TITLE
games-arcade/opentyrian: add 2.1.20220318

### PR DESCRIPTION
**Pull request by poopingpenis**
Signed-off-by: poopingpenis <poopingpeniz@outlook.com>

Update OpenTyrian to the latest version!

### CODE REVIEW

**Comment by poopingpenis** [comment]
I accidentally added more updates to the same commit, but basically I updated the Java JDKs since the ones on the repo right now are terribly outdated and insecure, see: https://neilmadden.blog/2022/04/19/psychic-signatures-in-java/

**Comment by gyakovlev** [comment]
I'm about to commit java/jdk bumps. your PR still have some issues that will take longer to fix, than for me just to commit.
I can explain: you bumped all JDKs in single commit. we don't do it like that. each version requires separate commit bump
also you need to reset KEYWORDS for each arch to ~ (unstable)
we don't commit new ebuilds as stable.
ans this is still a mixed PR with unrelated packages.

**Comment by poopingpenis** [comment]
@gyakovlev

> I'm about to commit java/jdk bumps. your PR still have some issues that will take longer to fix, than for me just to commit. I can explain: you bumped all JDKs in single commit. we don't do it like that. each version requires separate commit bump also you need to reset KEYWORDS for each arch to ~ (unstable) we don't commit new ebuilds as stable. ans this is still a mixed PR with unrelated packages.

I understand, sorry about that! I meant to fix it but I've been busy with uni and am still new to git (and contributing to Gentoo), so I couldn't yet. My apologies. I'll definitely remember this for next time, though.

**Comment by gyakovlev** [comment]
I merged the jdk bumps of my version and we discussed this a bit more on IRC =)
I suggest opening separate PR for game bump.
couple of tips: 
* do a separate branch for each PR. Do not re-use single `changes` branch for multiple. 
* keeps commits atomic (single logical change - single commit). Sometimes it's ok to combine those, but usually single is better.
history is cleaner that way, and easier to rebase/revert/check.

and check docs, those contain useful tips and pointers:
https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide

**Pull request closed without merging**
