### PR TITLE
sys-cluster/heartbeat: Critical bugfixes #648336

### PR DESCRIPTION
**Pull request by spacefreak86**
Heartbeat restarts itself after returning from partition (split-brain).
Due to a bug in 3.0.6-configure.patch, the daemon dies instead.
The init-script was totally broken, some rework was needed.

Package-Manager: Portage-2.3.19, Repoman-2.3.6

### CODE REVIEW

**Comment by spacefreak86** [comment]
I filed a bug and linked it to the PR as requested.

**Comment by spacefreak86** [comment]
@monsieurp I filed a bug and linked it to the PR almost 5 days ago. Is there anything else missing to apply to PR to portage?

**Comment by spacefreak86** [comment]
It has been 20 days already since I filed a bug and linked it to the PR as requested.
Since then, I did not get any response at all.
It is very annoying that I did the whole work, tried to comply with all the requirements within the shortest
time possible, and now just be left alone in the rain.
If this is the normal way you treat volunteers, no wonder that Gentoo always has trouble to get enough support.

I would really appreciate a short feedback.

**Comment by prometheanfire** [comment]
I'll look at it tonight, I may not be the maintainer, but I am in the cluster group.  guess that's good enough

**Comment by prometheanfire** [comment]
merged, I just fixed the src_uri to be the `SRC_URI="http://hg.linux-ha.org/${PN}-STABLE_3_0/archive/STABLE-${PV}.tar.bz2 -> ${P}.tar.bz2"`

now it saves as `/usr/portage/distfiles/heartbeat-3.0.6.tar.bz2` instead of `/usr/portage/distfiles/STABLE-3.0.6.tar.bz2`.

**Pull request closed without merging**
