### PR TITLE
app-editors/neovim: Bump to v0.1.4

### PR DESCRIPTION
**Pull request by lluixhi**
dev-lua/messagepack was dropped in favor of dev-lua/mpack.

QA issues right now because dev-lua/mpack and its dependency dev-lua/busted need ~x86 keyworded

https://bugs.gentoo.org/581210

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. Please make sure the QA check passes.

**Comment by monsieurp** [comment]
@radhermit

**Comment by radhermit** [comment]
Can you drop the ~x86 keyword then until mpack is keyworded for it and also open a (re-)keywording bug  for neovim/mpack when this is merged?

Otherwise if this is mostly a version bump with a dep change it's probably fine to merge.

**Comment by lluixhi** [comment]
@radhermit 
Done. Wasn't sure what the right way to do this was so I tried to be careful about it.

https://bugs.gentoo.org/581300

**Comment by lluixhi** [comment]
Oh, before this is merged, should I change the dependencies so dev-lua/mpack[luajit] and dev-lua/lpeg[luajit] is required?

I believe that would fix this bug (See my last comment):
https://bugs.gentoo.org/577124

**Comment by radhermit** [comment]
If luajit is a hard dep right now (apparently because they want to use its FFI support at some point), just do the latter. IMHO, I'd only support using lua when upstream allows it to be used by itself without luajit also being required (I imagine there's an issue already open about this, or at least closed WONTFIX). :wink: 

If people want vim on other architectures that luajit doesn't support yet... they're probably already using the canonical vim project. :smile:

**Comment by lluixhi** [comment]
@radhermit 
Done.

**Comment by radhermit** [comment]
Merged, thanks.

**Pull request closed without merging**
