### PR TITLE
Dev-python/python-language-server: allow newer ujson versions

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
This fixes a bug in pyls_jsonrpc preventing the use of ujson newer than 1.35 in pyls.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Could you revbump both of these so people who already have these installed can update to later ujson as well? `git mv` with your changes is fine here.

**Comment by AndrewAmmerlaan** [comment]
> Could you revbump both of these so people who already have these installed can update to later ujson as well? `git mv` with your changes is fine here.

Done

**Review by juippis — COMMENTED** [review]
Sooo after your update the tests fail with updated ujson, 
```
============================================== FAILURES ==============================================
______________________________________ test_writer_bad_message _______________________________________

wfile = <_io.BytesIO object at 0x7f8541835e90>
writer = <pyls_jsonrpc.streams.JsonRpcStreamWriter object at 0x7f8541850210>

    def test_writer_bad_message(wfile, writer):
        # A datetime isn't serializable(or poorly serializable),
        # ensure the write method doesn't throw, but the result could be empty
        # or the correct datetime
        datetime.datetime = JsonDatetime
        writer.write(datetime.datetime(
            year=2019,
            month=1,
            day=1,
            hour=1,
            minute=1,
            second=1,
        ))
    
>       assert wfile.getvalue() in [
            b''
            b'Content-Length: 10\r\n'
            b'Content-Type: application/vscode-jsonrpc; charset=utf8\r\n'
            b'\r\n'
            b'1546300861'
            ]
E       AssertionError: assert b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546304461' in [b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546300861']
E        +  where b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546304461' = <built-in method getvalue of _io.BytesIO object at 0x7f8541835e90>()
E        +    where <built-in method getvalue of _io.BytesIO object at 0x7f8541835e90> = <_io.BytesIO object at 0x7f8541835e90>.getvalue

test/test_streams.py:124: AssertionError
====================================== short test summary info =======================================
FAILED test/test_streams.py::test_writer_bad_message - AssertionError: assert b'Content-Length: 10\...
==================================== 1 failed, 26 passed in 0.09s ====================================
 * ERROR: dev-python/python-jsonrpc-server-0.4.0-r1::testworld failed (test phase):
 *   Tests fail with python3.7
```
But the ::gentoo version passes all tests. So there's definitely still something broken with this.

**Comment by AndrewAmmerlaan** [comment]
Which ujson version where you using? this was working for me with ujson-4.0.0

**Comment by juippis** [comment]
`[ebuild   R    ] dev-python/ujson-4.0.1::gentoo`

Let me try with 4.0.0
Nope, it still fails :\ 
So it must be some missing dep issue.

Basically my deps are always the latest available version.

**Comment by AndrewAmmerlaan** [comment]
> Basically my deps are always the latest available version.

Same, but I just retested and this works for me, so I'm a bit confused now

Lets compare equery depgraphs:

```
* dependency graph for dev-python/python-jsonrpc-server-0.4.0
`--  dev-python/python-jsonrpc-server-0.4.0  ~amd64 
`--  dev-python/ujson-4.0.0  (>=dev-python/ujson-3) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-lang/python-3.7.9  (dev-lang/python) ~amd64 
`--  dev-lang/python-3.8.6  (dev-lang/python) ~amd64 
`--  dev-lang/python-3.9.0  (dev-lang/python) ~amd64 
`--  dev-lang/python-exec-2.4.6-r2  (>=dev-lang/python-exec-2) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-python/versioneer-0.18-r1  (dev-python/versioneer) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-python/mock-3.0.5-r2  (dev-python/mock) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-python/pycodestyle-2.6.0  (dev-python/pycodestyle) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-python/pytest-6.1.1  (>=dev-python/pytest-4.5.0) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
`--  dev-python/setuptools-50.3.0  (>=dev-python/setuptools-42.0.2) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-)-python_single_target_python3_8(-) -python_single_target_python3_9(-)]
[ dev-python/python-jsonrpc-server-0.4.0 stats: packages (11), max depth (1) ]
```

**Comment by juippis** [comment]
> ```
> * dependency graph for dev-python/python-jsonrpc-server-0.4.0
> ```

Do note that your version is -r1, the ::gentoo version (-r0) works for me too as I said previously. But here's mine:
```
 * dependency graph for dev-python/python-jsonrpc-server-0.4.0-r1
 `--  dev-python/python-jsonrpc-server-0.4.0-r1  ~amd64 
   `--  dev-python/ujson-4.0.1  (>=dev-python/ujson-3) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-lang/python-3.7.9  (dev-lang/python) ~amd64 
   `--  dev-lang/python-3.8.6  (dev-lang/python) ~amd64 
   `--  dev-lang/python-3.9.0  (dev-lang/python) ~amd64 
   `--  dev-lang/python-exec-2.4.6-r2  (>=dev-lang/python-exec-2) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-python/versioneer-0.18-r1  (dev-python/versioneer) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-python/mock-3.0.5-r2  (dev-python/mock) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-python/pycodestyle-2.6.0  (dev-python/pycodestyle) amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-python/pytest-6.1.1  (>=dev-python/pytest-4.5.0) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
   `--  dev-python/setuptools-50.3.0  (>=dev-python/setuptools-42.0.2) ~amd64  [python_targets_python3_7(-)? python_targets_python3_8(-)? python_targets_python3_9(-)? -python_single_target_python3_7(-) -python_single_target_python3_8(-) -python_single_target_python3_9(-)]
[ dev-python/python-jsonrpc-server-0.4.0-r1 stats: packages (11), max depth (1) ]
```

**Comment by AndrewAmmerlaan** [comment]
> Yep, they seem to pass happily without the patch.

The plot thickens, I get this without the patch:

```
=============================================================================================== FAILURES ================================================================================================
________________________________________________________________________________________ test_writer_bad_message ________________________________________________________________________________________

wfile = <_io.BytesIO object at 0x7efc2afa0bf0>, writer = <pyls_jsonrpc.streams.JsonRpcStreamWriter object at 0x7efc2afafd90>

def test_writer_bad_message(wfile, writer):
# A datetime isn't serializable(or poorly serializable),
# ensure the write method doesn't throw, but the result could be empty
# or the correct datetime
datetime.datetime = JsonDatetime
writer.write(datetime.datetime(
year=2019,
month=1,
day=1,
hour=1,
minute=1,
second=1,
))

>       assert wfile.getvalue() in [
b'',
b'Content-Length: 10\r\n'
b'Content-Type: application/vscode-jsonrpc; charset=utf8\r\n'
b'\r\n'
b'1546304461'
]
E       AssertionError: assert b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546300861' in [b'', b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546304461']
E        +  where b'Content-Length: 10\r\nContent-Type: application/vscode-jsonrpc; charset=utf8\r\n\r\n1546300861' = <built-in method getvalue of _io.BytesIO object at 0x7efc2afa0bf0>()
E        +    where <built-in method getvalue of _io.BytesIO object at 0x7efc2afa0bf0> = <_io.BytesIO object at 0x7efc2afa0bf0>.getvalue

test/test_streams.py:124: AssertionError
```

**Comment by juippis** [comment]
I get the error you posted **with** the patch you included here. If no pathes are applied, python-jsonrpc-server-0.4.0-r1 passes all tests and installs just fine. Are you doing something weird on your end? :) 

I'm applying this on top of ::gentoo tree and running emerge.

**Comment by AndrewAmmerlaan** [comment]
> Are you doing something weird on your end? :)

Not that I know

Looking at the PR where I got this patch the upstream CI checks seem to be failing as well: https://github.com/palantir/python-jsonrpc-server/pull/49

Though presumably the submitter wrote the patch in the first place because they were getting this error.

So it seems like some people need this patch to get the test to work, and for others the patch breaks the test.

I don't know what's going on, but the test seems to be doing _something_ with date and time, so I suspect locale settings are causing these issues.

**Comment by rossbridger** [comment]
Probably upstream hasn't fully fixed this issue.

**Comment by rossbridger** [comment]
I took the liberty of fixing this issue, apply
```
diff --git a/test/test_streams.py b/test/test_streams.py
index 6985aec..9e64489 100644
--- a/test/test_streams.py
+++ b/test/test_streams.py
@@ -119,6 +119,7 @@ def test_writer_bad_message(wfile, writer):
         hour=1,
         minute=1,
         second=1,
+        tzinfo=datetime.timezone.utc
     ))

     assert wfile.getvalue() in [
```
It should work like a charm.

**Comment by AndrewAmmerlaan** [comment]
> I took the liberty of fixing this issue, apply
> 
> ```
> diff --git a/test/test_streams.py b/test/test_streams.py
> index 6985aec..9e64489 100644
> --- a/test/test_streams.py
> +++ b/test/test_streams.py
> @@ -119,6 +119,7 @@ def test_writer_bad_message(wfile, writer):
>          hour=1,
>          minute=1,
>          second=1,
> +        tzinfo=datetime.timezone.utc
>      ))
> 
>      assert wfile.getvalue() in [
> ```
> 
> It should work like a charm.

Awesome, Thank You!

This works for me, @juippis does this fix the issue for you too?

**Review by juippis — APPROVED** [review]
Thanks, both of you!

**Pull request closed without merging**
