### PR TITLE
app-admin/lastpass: bump to 3.2.16 #550834 #551312

### PR DESCRIPTION
**Pull request by gktrk**
Bump app-admin/lastpass to 3.2.16. Upstream does not support versioned
tarballs, so remove the old version. Closes a bump request and a
checksum mismatch bug.

Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=550834
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=551312

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by mgorny** [comment]
@robbat2

**Comment by gktrk** [comment]
Rebased because it was 5167 commits behind

**Comment by mgorny** [comment]
Hmm, if that's not a problem, please add a `|| die` to every `cat ... >` line, like:

    cat >"${T}"/lastpass_policy.json <<-EOF || die

**Comment by gktrk** [comment]
I can fixup the second commit if you want.

**Comment by gktrk** [comment]
Renamed all distfiles using '->'.
Added the missing build time dependency on app-arch/unzip per devmanual.

Potentially need another revision to use unpack instead of unzip. Waiting on robbat's input on the issue.

**Comment by robbat2** [comment]
Already merged

**Pull request closed without merging**
