### PR TITLE
dev-libs/libhid: add 0.12.0 (switch to libusb fork)

### PR DESCRIPTION
**Pull request by thesamesam**
Couldn't build older version (as a dep of app-misc/graphlcd-base) and came across this libusb fork (which lets us drop legacy libusb:0 dep, yay!)

Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by thesamesam** [comment]
@ConiKost can you diff old/new files with iwdevtools or whatever? I couldn't install the old version because of an xsltproc issue (which is how I found the fork)

**Comment by ConiKost** [comment]
Yeah, will test later on today and report back. Thank you!

**Comment by ConiKost** [comment]
This fork causes a file collision for me:

```
 * Detected file collision(s):
 *
 *      /usr/include/hidapi/hidapi_libusb.h
 *      /usr/include/hidapi/hidapi.h
 *      /usr/lib64/pkgconfig/hidapi-libusb.pc
 *      /usr/lib64/pkgconfig/hidapi-hidraw.pc
 *      /usr/lib64/libhidapi-libusb.so
 *      /usr/lib64/libhidapi-libusb.so.0
 *      /usr/lib64/libhidapi-hidraw.so
 *      /usr/lib64/libhidapi-hidraw.so.0
 *
 * Searching all installed packages for file collisions...
 *
 * Press Ctrl-C to Stop
 *
 * dev-libs/hidapi-0.12.0:0::gentoo
 *      /usr/include/hidapi/hidapi.h
 *      /usr/include/hidapi/hidapi_libusb.h
 *      /usr/lib64/libhidapi-hidraw.so
 *      /usr/lib64/libhidapi-hidraw.so.0
 *      /usr/lib64/libhidapi-libusb.so
 *      /usr/lib64/libhidapi-libusb.so.0
 *      /usr/lib64/pkgconfig/hidapi-hidraw.pc
 *      /usr/lib64/pkgconfig/hidapi-libusb.pc
```

**Comment by ConiKost** [comment]
Are you sure, that this is a drop-in replacement for libhid?

**Comment by thesamesam** [comment]
Nope, I confused it with dev-libs/hidapi!

I wonder if anything really needs libhid itself now.

**Pull request closed without merging**
