### PR TITLE
Feature/bump clion

### PR DESCRIPTION
**Pull request by strahlc**
dev-util/clion: version bump to 2019.1.3
dev-util/clion: remove old version

### CODE REVIEW

**Comment by strahlc** [comment]
> `eutils` in an EAPI-7 ebuild?

this is required for `make_wrapper` call

**Comment by strahlc** [comment]
@a17r 
Can you please merge my PR?

**Comment by gyakovlev** [comment]
@strahlc 

`x86_64-pc-linux-gnu-strip: Unable to recognise the format of the input file `/tmp/portage/dev-util/clion-2019.1.2/image/opt/clion-2019.1.2/lib/pty4j-native/linux/ppc64le/libpty.so'`

can you remove ppc64le libs?
I'll merge it after you fix it.

**Comment by strahlc** [comment]
@gyakovlev done

**Pull request closed without merging**
