### PR TITLE
app-crypt/envchain: New ebuild

### PR DESCRIPTION
**Pull request by sorah**
Add ebuild for https://github.com/sorah/envchain . This allows save credentials or any secret values to a secure vault (libsecret, gnome-keyring for Linux), so to avoid writing credentials to your `~/.*shrc` file.

This project is now more than 2 yrs old, and supported Linux from 1.0.0 so I'm proposing this ebuild for easy installation from many people.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thanks for the PR. As is, it can't be merged since:
- you did not use repoman to commit but git instead, I suspect.
- you must provide a bit more background as to what this package is meant to be doing.
- a metadata.xml file is missing and without it, we have no idea who's in charge of maintaining your package.
- whilst at it (creating the above file), add yourself to metadata.xml as you'll be maintaining envchain, I guess (?)
- preferably, you should also file a bug at https://bugs.gentoo.org so that we make sure your email is recorded in our systems and can keep track of the package inclusion in Portage.

Please also take a moment and read https://wiki.gentoo.org/wiki/Gentoo_Github. Thanks!

**Comment by sorah** [comment]
Force pushed and filed https://bugs.gentoo.org/show_bug.cgi?id=585634

**Comment by sorah** [comment]
Also updated the issue description to explaining background

**Comment by sorah** [comment]
> preferably, you should also file a bug at https://bugs.gentoo.org so that we make sure your email is recorded in our systems and can keep track of the package inclusion in Portage.

other says this isn't reuqired so the bug has been closed

**Comment by monsieurp** [comment]
> other says this isn't reuqired so the bug has been closed 

Please disregard. I have reopened the bug report and commented it.

**Comment by sorah** [comment]
Thanks!

**Pull request closed without merging**
