### PR TITLE
media-video/imagination: restrict test

### PR DESCRIPTION
**Pull request by mm1ke**
Signed-off-by: Michael Mair-Keimberger <mmk@levelnine.at>

Closes: https://bugs.gentoo.org/935691

Restricting tests as they're no practical tests to run anyway.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Can you include a comment that it doesn't actually test anything?

**Comment by eli-schwartz** [comment]
Note also `pkgdev commit -c/--closes 935691` would place the Closes line on the line before your signoff... it would also not separate them by a blank line.

pkgcheck complains about the blank line:
```
InvalidCommitMessage: commit XXXXXX: empty line 4 in footer
```

**Comment by mm1ke** [comment]
> Can you include a comment that it doesn't actually test anything?

Sure, sorry i was thinking the link was enough :)

**Comment by mm1ke** [comment]
> Note also `pkgdev commit -c/--closes 935691` would place the Closes line on the line before your signoff... it would also not separate them by a blank line.
> 
> pkgcheck complains about the blank line:
> 
> ```
> InvalidCommitMessage: commit XXXXXX: empty line 4 in footer
> ```

Hmm, that's strange.. actually i do use `pkgdev commit -c`, just a bit differently. I'm using a script which basically calls: `pkgdev commit -s -a "${2}" -M /tmp/commit-msg-${i}` (via ${2} i'm adding the `-c` flag)
I guess all my commits suffer from that? Need to check this, thanks for letting me know.

**Comment by eli-schwartz** [comment]
If your commit-msg has its own signoff then maybe pkgdev doesn't add its own, but treats the commit-msg file as a separate "paragraph"?

**Comment by mm1ke** [comment]
> If your commit-msg has its own signoff then maybe pkgdev doesn't add its own, but treats the commit-msg file as a separate "paragraph"?

Yeah, i think so too.  The commit-msg file has my sign-off too.

The script is already quite old and i've created it to use it with `repoman`. It's just a simple wrapper to easily make commits for gentoo. When `pkgdev` arrived i just adopted it.
I'll look into it before making any other PRs - just not today anymore, tomorrow ;)

**Comment by mm1ke** [comment]
btw, i've just updated the commit manually, at least here it should be correct now.

**Pull request closed without merging**
