### PR TITLE
media-video/pitivi: version bump

### PR DESCRIPTION
**Pull request by MeisterP**
```diff
--- pitivi-0.999-r4.ebuild	2021-11-28 15:57:22.155434219 +0100
+++ pitivi-2021.05.ebuild	2021-11-28 16:26:31.894065857 +0100
@@ -1,28 +1,25 @@
 # Copyright 1999-2021 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
+EAPI=8
 PYTHON_COMPAT=( python3_{8..9} )
 PYTHON_REQ_USE="sqlite"
 
-inherit gnome.org meson python-single-r1 virtualx xdg
+inherit gnome.org meson python-single-r1 xdg
 
 DESCRIPTION="A non-linear video editor using the GStreamer multimedia framework"
 HOMEPAGE="http://www.pitivi.org"
 
 LICENSE="LGPL-2.1"
 SLOT="0"
-KEYWORDS="amd64 x86"
+KEYWORDS="~amd64 ~x86"
 
-IUSE="v4l test"
-RESTRICT="!test? ( test )"
+IUSE=""
 REQUIRED_USE="${PYTHON_REQUIRED_USE}"
 
-# XXX: recommends gst-plugins-libav and frei0r-plugins
-
 # Do not forget to check pitivi/check.py for dependencies!!!
-# pycanberra, libav, libnotify and liwnck are optional
-GST_VER="1.14.2"
+# gsound, libav, libnotify and v4l are optional
+GST_VER="1.18.4"
 
 COMMON_DEPEND="
 	${PYTHON_DEPS}
@@ -32,10 +29,6 @@ COMMON_DEPEND="
 	>=x11-libs/cairo-1.10
 
 	>=media-libs/gstreamer-${GST_VER}:1.0[introspection]
-	|| (
-		>media-libs/gst-plugins-bad-1.18
-		>=media-plugins/gst-transcoder-1.14.1
-	)
 "
 RDEPEND="${COMMON_DEPEND}
 	>=dev-libs/glib-2.30.0:2
@@ -50,7 +43,6 @@ RDEPEND="${COMMON_DEPEND}
 	')
 
 	gnome-base/librsvg:=
-	>=media-libs/gsound-1.0
 
 	>=media-libs/gstreamer-editing-services-${GST_VER}:1.0[introspection]
 	>=media-libs/gst-plugins-base-${GST_VER}:1.0[introspection,theora]
@@ -63,8 +55,6 @@ RDEPEND="${COMMON_DEPEND}
 	>=x11-libs/libnotify-0.7[introspection]
 	x11-libs/libwnck:3[introspection]
 	>=x11-libs/gtk+-3.20.0:3[introspection]
-
-	v4l? ( >=media-plugins/gst-plugins-v4l2-${GST_VER}:1.0 )
 "
 DEPEND="${RDEPEND}"
 BDEPEND="
@@ -74,30 +64,9 @@ BDEPEND="
 	dev-util/itstool
 	sys-devel/gettext
 	virtual/pkgconfig
-	test? (
-		$(python_gen_cond_dep '
-			dev-python/nose2[${PYTHON_USEDEP}]
-		')
-	)
 "
 
-PATCHES=(
-	# https://gitlab.gnome.org/GNOME/pitivi/-/merge_requests/245
-	# support python 3.8
-	"${FILESDIR}"/${P}-python38.patch
-
-	# use /usr/share/metainfo
-	"${FILESDIR}"/${P}-metainfo.patch
-
-	# Make tests optional, bug #594096
-	# https://gitlab.gnome.org/GNOME/pitivi/issues/2303
-	"${FILESDIR}"/${P}-optional-tests.patch
-)
-
 src_configure() {
-	local emesonargs=(
-		-Denable-tests=$(usex test true false)
-	)
 	meson_src_configure
 }
 
@@ -105,11 +74,6 @@ src_compile() {
 	meson_src_compile
 }
 
-src_test() {
-	export PITIVI_TOP_LEVEL_DIR="${S}"
-	virtx meson_src_test
-}
-
 src_install() {
 	meson_src_install
 	python_fix_shebang "${D}"
```

```diff
--- gstreamer-editing-services-1.16.3.ebuild	2021-04-22 20:46:03.346357744 +0200
+++ gstreamer-editing-services-1.18.4.ebuild	2021-11-28 16:26:31.894065857 +0100
@@ -1,22 +1,22 @@
 # Copyright 1999-2021 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
-PYTHON_COMPAT=( python3_{7,8,9} )
-GNOME2_LA_PUNT="yes"
+EAPI=8
+PYTHON_COMPAT=( python3_{8..9} )
 
-inherit bash-completion-r1 gnome2 python-r1
+inherit meson python-r1
 
 DESCRIPTION="SDK for making video editors and more"
 HOMEPAGE="http://wiki.pitivi.org/wiki/GES"
-SRC_URI="https://gstreamer.freedesktop.org/src/${PN}/${P}.tar.xz"
+SRC_URI="https://gstreamer.freedesktop.org/src/${PN}/${P/gstreamer/gst}.tar.xz"
 
 LICENSE="LGPL-2+"
 SLOT="1.0"
-KEYWORDS="amd64 x86"
+KEYWORDS="~amd64 ~x86"
 
-IUSE="+introspection"
+IUSE="+introspection gtk-doc test"
 REQUIRED_USE="${PYTHON_REQUIRED_USE}"
+RESTRICT="!test? ( test )"
 
 RDEPEND="
 	${PYTHON_DEPS}
@@ -31,37 +31,27 @@ BDEPEND="
 	>=dev-util/gtk-doc-am-1.3
 	virtual/pkgconfig
 "
-# XXX: tests do pass but need g-e-s to be installed due to missing
-# AM_TEST_ENVIRONMENT setup.
+# Some tests are failing
 RESTRICT="test"
 
-src_prepare() {
-	gnome2_src_prepare
-	# Install python overrides manually for each python and old upstream
-	# autotools code prefers python2 and installs in wrong location
-	sed -e '/WITH_PYTHON/d' -i bindings/Makefile.in || die
-}
+S=${WORKDIR}/${P/gstreamer/gst}
 
 src_configure() {
-	# gtk is only used for examples
-	gnome2_src_configure \
-		$(use_enable introspection) \
-		--disable-examples \
-		--with-bash-completion-dir="$(get_bashcompdir)" \
-		--with-package-name="GStreamer editing services ebuild for Gentoo" \
-		--with-package-origin="https://packages.gentoo.org/package/media-libs/gstreamer-editing-services"
-}
-
-src_compile() {
-	# Prevent sandbox violations, bug #538888
-	# https://bugzilla.gnome.org/show_bug.cgi?id=744135
-	# https://bugzilla.gnome.org/show_bug.cgi?id=744134
-	addpredict /dev
-	gnome2_src_compile
+	local emesonargs=(
+		$(meson_use gtk-doc docs)
+		$(meson_feature introspection)
+		$(meson_feature test tests)
+		-Dbash-completion=disabled
+		-Dxptv=disabled
+		-Dpython=enabled
+		-Dvalidate=disabled
+		-Dexamples=disabled
+	)
+	meson_src_configure
 }
 
 src_install() {
-	gnome2_src_install
+	meson_src_install
 	python_moduleinto gi.overrides
 	python_foreach_impl python_domodule bindings/python/gi/overrides/GES.py
 }
```

### CODE REVIEW

**Comment by kobboi** [comment]
Hmm, this does not seem to work for me:

>>>  '/var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/temp/build.log'
>>> Jobs: 0 of 2 complete, 1 failed                 Load avg: 0.51, 0.32, 0.35
 * Package:    media-libs/gstreamer-editing-services-1.18.4
 * Repository: kobboi-linux
 * USE:        abi_x86_64 amd64 elibc_glibc introspection kernel_linux python_targets_python3_9 userland_GNU
 * FEATURES:   compressdebug installsources network-sandbox preserve-libs sandbox splitdebug userpriv usersandbox
meson setup --libdir lib64 --localstatedir /var/lib --prefix /usr --sysconfdir /etc --wrap-mode nodownload --build.pkg-config-path /usr/share/pkgconfig --pkg-config-path /usr/share/pkgconfig --native-file /var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/temp/meson.x86_64-pc-linux-gnu.amd64.ini --buildtype plain -Ddocs=false -Dintrospection=enabled -Dtests=disabled -Dbash-completion=disabled -Dxptv=disabled -Dpython=enabled -Dvalidate=disabled -Dexamples=disabled /var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/work/gst-editing-services-1.18.4 /var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/work/gstreamer-editing-services-1.18.4-build
The Meson build system
Version: 0.60.3
Source dir: /var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/work/gst-editing-services-1.18.4
Build dir: /var/tmp/portage/media-libs/gstreamer-editing-services-1.18.4/work/gstreamer-editing-services-1.18.4-build
Build type: native build
DEPRECATION: Option examples already exists.

meson.build:1:0: ERROR: Unknown options: "docs"

**Comment by kobboi** [comment]
I left out the docs thing, compiles fine. So does the pitivi ebuild and it starts up as expected (the 0.999 was giving me a coredump on a wayland assertion failure)

**Comment by MeisterP** [comment]
> meson.build:1:0: ERROR: Unknown options: "docs"

My mistake. It should be $(meson_use gtk-doc doc) and not $(meson_use gtk-doc doc**s**)
https://gitlab.freedesktop.org/gstreamer/gst-editing-services/-/blob/1.18/meson_options.txt#L2

**Comment by kobboi** [comment]
@MeisterP  Could you add https://gitlab.gnome.org/GNOME/pitivi/-/commit/ddf2369d1fc6fddd63f676cc905a8b8e96291a4c to support meson-0.61? Thanks!

**Review by pacho2 — APPROVED** [review]

**Comment by kobboi** [comment]
When building this from scratch, I noticed a missing dependency:
Run-time dependency gstreamer-plugins-bad-1.0 found: NO (tried pkgconfig and cmake)

**Comment by MeisterP** [comment]
> When building this from scratch, I noticed a missing dependency:
> Run-time dependency gstreamer-plugins-bad-1.0 found: NO (tried pkgconfig and cmake)

I can not reproduce this. Configure succeeds without `media-libs/gst-plugins-bad` installed here. And I can't find a check for plugins-bad in pitivi's source code either.

**Comment by kobboi** [comment]
I forgot to mention that I get this when building media-libs/gstreamer-editing-services-1.18.4, not pitivi-2021.05

**Comment by MeisterP** [comment]
> I forgot to mention that I get this when building media-libs/gstreamer-editing-services-1.18.4, not pitivi-2021.05

Added the dependency. Thanks.

I don't know why `media-libs/gstreamer-editing-services` doesn't get updated with the other gstreamer packages in gentoo. Seems weird. Newer versions than 1.18.4 are available upstream.

**Comment by thesamesam** [comment]
Thanks a lot!

**Pull request closed without merging**
