### PR TITLE
Libva intel media driver 2.3.0 r1

### PR DESCRIPTION
**Pull request by Karlson2k**
Added USE flag to enable native host optimisation.

### CODE REVIEW

**Comment by Karlson2k** [comment]
I can squash down commits and remove -r1 revision.

**Comment by Karlson2k** [comment]
To be merged after #17730

**Comment by rossbridger** [comment]
Why not just bump a single ebuild and close https://github.com/gentoo/gentoo/pull/17730?

**Comment by Karlson2k** [comment]
> Why not just place everything in a single commit and close #17730?

As I mentioned in the [second comment](https://github.com/gentoo/gentoo/pull/17733#issuecomment-702177851), it could be combined into single commit and single version bump. No problem.
 
> Also what kind of trick does this native-optimisation USE have to offer? Shouldn't passing "-march=native" CFLAG suffice for such feature?
It doesn't work as build system add many flags including `-march=core-i7`. Without patching sources, the only way to override it is to define `UFO_MARCH` which supply argument for -march.
If it is preferable, I can patch cmake files to use user CFLAGS, but it will be untested by upstream.

**Comment by rossbridger** [comment]
> > It doesn't work as build system add many flags including `-march=core-i7`. Without patching sources, the only way to override it is to define `UFO_MARCH` which supply argument for -march.
> > If it is preferable, I can patch cmake files to use user CFLAGS, but it will be untested by upstream.

I think it is preferable to make the build system to respect user's own cflags.

**Comment by Karlson2k** [comment]
Superseded by https://github.com/gentoo/gentoo/pull/18955

**Pull request closed without merging**
