### PR TITLE
dev-db/mydumper: Fix implicit declaration of function open

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/935389

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
Upstream appears to be active, so please submit your patch there first and then backport it here (even if you don't wait for them to accept it).

We really don't want to be in the position of carrying tons of downstream patches just so the software works at all...

**Comment by thesamesam** [comment]
@listout To be explicit, please send patches upstream by default unless you're unsure about them. If you're unsure about them, please say that clearly in the Gentoo PR so someone can take a look more closely. (Include fixes should be trivial usually but sometimes e.g. the pointer type stuff needs checking.)

**Comment by listout** [comment]
@thesamesam ack

**Comment by eli-schwartz** [comment]
Thank you! <3

**Comment by listout** [comment]
Upstream pull request merged https://github.com/mydumper/mydumper/pull/1557

**Comment by eli-schwartz** [comment]
Yay!

**Comment by hydrapolic** [comment]
Thanks!

**Pull request closed without merging**
