### PR TITLE
net-misc/i2pd: updates to daemon handling

### PR DESCRIPTION
**Pull request by khumarahn**
Hi, this pull request implements graceful shutdown in openrc on
```
rc-service i2pd graceful
```
Graceful shutdown respects commitments for existing tunnels. It takes 10 minutes.

It also fixes a pid file bug in openrc. Currently openrc starts the service by
```
checkpath -f /var/run/i2pd.pid -o i2pd:i2pd
start-stop-daemon -S -u i2pd:i2pd -p /var/run/i2pd.pid /usr/bin/i2pd -- ${I2PDOPTIONS}
```
I observe that the above works as follows: the first command creates a file `/var/run/i2pd.pid` with correct permissions. The second command _deletes_ this file, starts the daemon and expects it to create the pid file. The daemon cannot create it, because it is run as `i2pd:i2pd`, and has no write access to `/var/run`. The whole thing is weird, and the daemon does not start.

I wanted to fix the pid file problem in my previous pull requests by not using `-p` option in start-stop-daemon, which worked OK, because the pid file was not deleted, but that was not accepted by the reviewer. This time I have a better solution, as I found in some other ebuilds in the tree: to create a folder `/run/i2pd` with correct permissions, and expect the daemon to create the pid file there. I tested it for both openrc and systemd, seems to work well.

I updated systemd service for compatibility, so that pid file is the same as in openrc. Also I made some cosmetic changes, like using longer names for start-stop-daemon options, and using more matching options in stopping routines, and migrating from `/var/run` to `/run`.

### CODE REVIEW

**Comment by khumarahn** [comment]
@blueness @tomboy-64 
Hi guys!

**Comment by tomboy-64** [comment]
at first glance it looks good; gonna check it out and comment on it.

**Comment by rindeal** [comment]
- there is no need to redefine default `start()`/`stop()`
- also replace `/sbin/runscript` with `/sbin/openrc-run`
- `--retry` argument has unescaped space
- bump year
- script makes assumptions that all `I2PD*` variables are defined

You could use this as a base for improvements:
```sh
#!/sbin/openrc-run
# Copyright 1999-2016 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# $Id$

description="C++ daemon for accessing the I2P network"
description_graceful="Graceful shutdown, takes 10 minutes"

command="/usr/bin/i2pd"
command_args="${I2PDOPTIONS}"
user="${I2PD_USER}:${I2PD_GROUP}"
start_stop_daemon_args="
    --user \"${user}\"
    --pidfile \"${I2PD_PID}\"
    --progress --retry 'SIGTERM/20 SIGKILL/20'
"

extra_started_commands="graceful"

depend() {
    use dns logger netmount
}

start_pre() {
    checkpath -f -o "${user}" "${I2PD_LOG}"
    checkpath -d -m 0750 -o "${user}" "${I2PD_PID_DIR}"
}

graceful() {
    # on SIGINT, i2pd stops accepting tunnels and shuts down in 600 seconds
    ebegin "Gracefully stopping i2pd, this takes 10 minutes"
    mark_service_stopping
    eval start-stop-daemon --stop "${start_stop_daemon_args}" \
        --exec "${command}" --retry 'SIGINT/620 SIGTERM/20 SIGKILL/20'
    eend $? && mark_service_stopped
}

```

**Comment by khumarahn** [comment]
Thanks, this looks impressive. Is it OK to have `--retry 'SIGTERM/20 SIGKILL/20` on the start of the daemon?

**Comment by rindeal** [comment]
`--retry` should do nothing when `--start` is used

**Comment by rindeal** [comment]
also there is an extra tab in `depend()`

**Comment by khumarahn** [comment]
What is the right thing to do with I2PD_PID and other variables? Currently they are defined in /etc/conf.d/i2pd.

**Comment by khumarahn** [comment]
One more question: is there a conflict in the graceful shutdown, between `--retry 'SIGINT/620 SIGTERM/20 SIGKILL/20'` and `"${start_stop_daemon_args}"`?

**Comment by rindeal** [comment]
> What is the right thing to do with I2PD_PID and other variables? Currently they are defined in /etc/conf.d/i2pd.

I guess setting default values
```sh
: ${VAR:=default}
```
or checking in runtime
```sh
start_pre() {
    if [ -z "$VAR" ] ;then
        eerror "not defined"
        return 1
    fi
}
```

>  is there a conflict in the graceful shutdown, between --retry

No, because I put `"${start_stop_daemon_args}"` before `--retry` and thus it overrides whatever was its previous value.

**Comment by khumarahn** [comment]
Thank you. I updated init.d and conf.d as you suggest. I found I had to remove question marks from `"${start_stop_daemon_args}"`, but everything else went fine.

**Comment by rindeal** [comment]
What question marks?

**Comment by khumarahn** [comment]
that was a typo. I meant quotes `"`.

**Comment by blueness** [comment]
in the future, squash these commits. remember, one issue, one commit.  think of it this way, if we had to revert this, we want to get rid of it with one and only one revert.  so you want it as one commit.  if you did two fixes then you want two commits so you can revert each fix individually if you have to.

**Comment by khumarahn** [comment]
Thank you!

I am happy - now we have a properly working ebuild for i2pd in the tree. The daemon works, and no initial configuration is necessary. The upstream is not without problems and bugs, but on packaging side we are clean.

There is still an issue that the daemon is given full access to /etc/i2pd, which seems not needed and could be a security threat... I will do a pull request for that soon.

**Pull request closed without merging**
