### PR TITLE
ROC cleanup old

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by littlewu2508** [comment]
Thanks for the cleanup!

I also suggest dropping `<dev-util/rocm-cmake-5`, `<dev-util/rocm_bandwidth_test-5`, `<sci-libs/miopen-5`

**Comment by heroxbd** [comment]
I have no objections.  Thank you.

That said, we'd better check if some version should be kept for old cards like Hawaii (GFX7), Fiji (GFX8) and Polaris (GFX9).

**Comment by littlewu2508** [comment]
> That said, we'd better check if some version should be kept for old cards like Hawaii (GFX7), Fiji (GFX8) and Polaris (GFX9).

By looking into the source code of `=dev-util/rocm-opencl-runtime-5.1.3` provides support down to Hawaii. removing `<dev-util/hip-5` won't cause older cards to be dropped. I don't have pre-vega devices so these observations stay at theoretical level.

**Comment by heroxbd** [comment]
littlewu2508 ***@***.***> writes:

> By looking into the source code of =dev-util/rocm-opencl-runtime-5.1.3
> provides support down to Hawaii. removing <dev-util/hip-5 won't cause
> older cards to be dropped. I don't have pre-vega devices so these
> observations stay at theoretical level.

OK, let's go for it.  We could add anything back if necessary after all.

**Comment by heroxbd** [comment]
Thanks, Andreas!

**Pull request merged**
