### PR TITLE
kde-apps/kdebase-runtime-meta: Require kdesu[-handbook]

### PR DESCRIPTION
**Pull request by a17r**
Minor adjustment for non-plasma profile users. Might help with dep resolution...

Package-Manager: portage-2.2.26

@gentoo/kde

### CODE REVIEW

**Comment by kensington** [comment]
Won't this cause a conflict for KDE4 users (handbook USE flag is on by default)?

**Comment by a17r** [comment]
KDE4 users should not use the slot 5 metas at all, since USE=minimal was dropped it is missing vital packages for Plasma 4 - in kde profile it is masked. Anyone outside of plasma profile upgrading to 15.08.3 however is met with a conflict with kde-cli-tools (it blocks kdesu[handbook]).

**Comment by kensington** [comment]
Right, I keep forgetting about the SLOT 5 metas. :blush: 

+handbook exceptions seems fine.

**Comment by kensington** [comment]
Thanks, picked as b8df6aaa86b5d2632bfa8828767e4e2d45293de2 & 08f9f7a994066ebb0aae618864c3e0da0e2424b3.

**Pull request closed without merging**
