### PR TITLE
Add amd64 & x86 uclibc [hardened] 17.0 profiles

### PR DESCRIPTION
**Pull request by mjeveritt**
Signed-off-by: M. J. Everitt <m.j.everitt@iee.org>

### CODE REVIEW

**Comment by mjeveritt** [comment]
@blueness : follow up from previous

**Comment by blueness** [comment]
pushed and building the stage3's.  BTW, there are some issues which have yet to be address, eg. sanitize needs to be masked on all uclibc profiles as well as some other flag changes.  i've added these locally in the stage3's /etc/portage, but this is just makeshift.

**Comment by mjeveritt** [comment]
Ok I'll follow up, have you pushed the appropriate stages to the releng.git repo for now? I'll prepare a patch and email direct, unless you want another PR?! :smiley:

**Comment by mjeveritt** [comment]
Cheers!

On a slightly tangential subject, I see that the x86/musl/hardened profile is missing, but its selinux sub-profile seems to be present, can you touch that one up, or shall I ?!

**Comment by blueness** [comment]
no.  hardened x86 is broken in a serious way.  we need to wait on that.

**Comment by mjeveritt** [comment]
OK thanks!

**Pull request closed without merging**
