### PR TITLE
gnome-base/gnome-session: Version bump to 44_rc BETA

### PR DESCRIPTION
**Pull request by flint2**
Neeed mask, in preparation for Gnome 44

### CODE REVIEW

**Comment by mattst88** [comment]
````diff
+option('systemduserunitdir', type: 'string', description: 'Directory for systemd user service files')
````

**Comment by flint2** [comment]
Removed mask, will be added in separate PR

**Comment by mattst88** [comment]
There's a specific function we should use for this in the future:

> -Dsystemduserunitdir="$(systemd_get_userunitdir)"

I've fixed it up locally.

**Comment by mattst88** [comment]
Please use `pkgbump` and `pkgcheck scan`:

````
gnome-base/gnome-session
  IncorrectCopyright: version 44_rc: incorrect copyright year 2022: '# Copyright 1999-2022 Gentoo Authors'
  DirectStableKeywords: version 44_rc: directly committed with stable keywords: [ amd64, arm64, x86 ]
````

**Pull request closed without merging**
