### PR TITLE
media-libs/assimp: fix version mismatch in pkg-config and cmake files

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/859862
Bug: https://github.com/assimp/assimp/issues/4655
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by waebbl** [comment]
I was thinking about doing a straight-to-stable push, due to the minor change involved. Feel free to ping me, if you think it's better to not drop to unstable keywords.

**Comment by waebbl** [comment]
Added missed fix in test file for version.

**Review by juippis — COMMENTED** [review]
I honestly do think you don't have to revbump for this fix. But I remember disagreeing with this before.

@thesamesam what's the right way?

**Comment by waebbl** [comment]
I was thinking, because it changes the installed files, it should be revbumped, so users / consumers are getting noticed, but I can change it to -r0 if desired.

**Comment by juippis** [comment]
Well I would weigh whether this revbump is fixing an issue, and in this case, it's an upstream issue, since it's only relevant for assimp's rdep developers. No one may actually "require" this, you're just closing a gentoo-related bug. 

Just my thoughts.

**Comment by waebbl** [comment]
Fair enough. The only revdeps in tree, which have version requirements seem to be dev-qt/qt3d:5 (>=4.0.0) and sci-libs/dart (>=3.0.0), so they won't be affected by the change.

**Comment by thesamesam** [comment]
> I honestly do think you don't have to revbump for this fix. But I remember disagreeing with this before.
> 
> @thesamesam what's the right way?

in general, yes, do, because of the consistency argument. In the event that something actually does want a proper fixed version, it's going to be very confusing if one system works and another doesn't.

**Comment by waebbl** [comment]
Thanks for merging!

**Pull request closed without merging**
