### PR TITLE
dev-util/kdevplatform: Remove bogus deps

### PR DESCRIPTION
**Pull request by a17r**
Gentoo-bug: 595116

@gentoo/kde

### CODE REVIEW

**Comment by shentino** [comment]
I might be missing something, but it appears that Quick and Quickwidgets are being removed unconditionally, but the commit message says they are required only if "use welcomepage"

Shouldn't there be some conditional logic rather than a flat removal?  This breaks "use welcomepage" if the commit message is correct.

NB:  Not a CMake expert so I could be wrong.

**Comment by a17r** [comment]
They are removed from the place where they are bogus, not from welcomepage.

Commit is upstream: https://quickgit.kde.org/?p=kdevplatform.git&a=commit&h=9d2423f20458d735454b9917b4b0f5e39a7929f5

**Comment by shentino** [comment]
username234 on freenode has pointed out that you changed depencency information but didn't revbump.

**Comment by a17r** [comment]
It fixes a build error with USE=-welcomepage but no dependency information.

**Comment by nvinson** [comment]
I would agree with that assessment if the ebuild was completely broken.  However, I assume kdevplatform[welcomepage] does work, so it could cause confusion among users as to why some of them would be able to build successfully with kdevplatform[-welcomepage] and others not when the version is the same.  For that reason, I believe the revbump would be necessary.

**Comment by kensington** [comment]
Thanks, picked as d9696ae28b9b675eda8afacfcc5eebce8b0e56e1.

**Pull request closed without merging**
