### PR TITLE
app-office/calligra: Bump to 2.9.10 and disable GHNS

### PR DESCRIPTION
**Pull request by MJDSys**
This bumps calligra, as requested in 562516.  The change to make this work is slightly different then the version in the bug, to ensure we download the stable release.

Also fixes bug 559598 by disabling GHNS.  GHNS is not supported upstream, and they recommend disabling it in distributions.

I tested the dependency fix on an empty chroot.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/kde @gentoo/office-overlay

**Comment by a17r** [comment]
diff lgtm, but didn't go further than configure. :)

**Comment by a17r** [comment]
fyi, there also just landed a GHNS fix in calligra/2.9 branch: https://quickgit.kde.org/?p=calligra.git&a=commit&h=90721e76ea9dfbae872aeaf1975dc4a6a2b0aa0a

**Comment by kensington** [comment]
Thanks, picked as 627d2440902e45b27712a556d5b1eff43fdc67e1 and a98587ecfb99778645824cdb17506573ff83d760.

**Comment by MJDSys** [comment]
@a17r Yep that's me.  In the review request, they also mentioned GHNS is not recommended and is buggy.

**Pull request closed without merging**
