### PR TITLE
media-sound/podget: verbump to 0.7.14, remove old

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint, @Kitcat490

**Comment by idella** [comment]
once again the issue over quoting vars.

**Comment by Coacher** [comment]
Once again this is not an issue, ${PN} is guaranteed to not contain spaces as per PMS: https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-210003.1.2

**Comment by idella** [comment]
We have been thru this already

**Comment by Coacher** [comment]
Yet you've brought this up again for some reason.

**Comment by Coacher** [comment]
Thank you, @monsieurp.

**Pull request closed without merging**
