### PR TITLE
net-print/hplip: Fix deps w/ USE=fax,scanner; add USE=libressl

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by billie80** [comment]
Looks okay! Can you include the fix of Bug #602506 in the Changlog?

**Comment by billie80** [comment]
Ah, that's okay. I just did not look close enough.

**Comment by devurandom** [comment]
Is it possible to merge this soon, please?

**Comment by billie80** [comment]
Will do it tomorrow!

**Comment by billie80** [comment]
Merged now.

**Comment by devurandom** [comment]
Thanks! The dependency conflict seems to be resolved. Could you please close this PR and the associated bugreport[1]?

[1]: https://bugs.gentoo.org/show_bug.cgi?id=602478

**Pull request closed without merging**
