### PR TITLE
dev-libs/json-c: remove vulnerable versions

### PR DESCRIPTION
**Pull request by jsmolic**
Remove json-c ebuilds with security vulnerabilities.

Bug: https://bugs.gentoo.org/722150
Package-Manager: Portage-2.3.99, Repoman-2.3.22
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>

### CODE REVIEW

**Comment by jsmolic** [comment]
@jkroonza Thanks, there was a lot of noise recently with security issues in json-c, so I had to clean it, and libhubbub also cropped up in here as a user of old json-c ebuilds.

**Comment by jkroonza** [comment]
You broke cryptsetup @jsmolic :p.  I think it's a keyword issue.

**Comment by jsmolic** [comment]
@jkroonza Yeah, I saw that. I think the problem here is that recently json-c was bumped to 0.14, and `~riscv` was left out of it in the process, so right now with removing old versions there isn't one json-c ebuild that is keyworded with `riscv`, which is required as `sys-fs/cryptsetup-2.3.2` depends on json-c and is keyworded with riscv. I'll file a keywording bug for `json-c`, I think one more json-c dependency needs to be keyworded with `riscv`, and it should be good after that.

**Comment by jsmolic** [comment]
Cleaned up in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=64b400382afdbff8b60d4f9726ffd3bcee6e628e

**Pull request closed without merging**
