### PR TITLE
media-libs/sdl2-mixer: add 2.8.0, co-maintain

### PR DESCRIPTION
**Pull request by mechakotik**
The new ebuild has following changes over 2.6.3-r1:

- Using CMake instead of autoconf: CMake is the preferred way of building it, autoconf seems to be no longer supported since 3.0
- Added GME and WavPack support, introduced in 2.8.0
- Added OGG Vorbis support via dev-libs/stb
- Added MOD support via media-libs/libxmp
- Removed static-libs USE flag, seems to be pointless as some of the dependencies still don't have static version

There are lots of changes in USE flags and I am rather unexperienced in it, so feedback is welcome.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by chewi — APPROVED** [review]
The ebuild looks fine, but at least with games-engines/odamex, the sound doesn't seem to work anymore. Some other games work fine though. :confused: Please could you test with this.

FWIW, static-libs does not require the dependencies to be static. That's only the case for completely static executables. It's probably unnecessary here though.

**Comment by thesamesam** [comment]
@mechakotik Could you check out @chewi's comment? I'm hoping this will resolve https://bugs.gentoo.org/945154.

**Comment by mechakotik** [comment]
> @mechakotik Could you check out @chewi's comment? I'm hoping this bump will resolve https://bugs.gentoo.org/945154.

Sorry, I'm quite busy with studies right now. I'll check it out when I'll have some free time.

**Comment by mechakotik** [comment]
> The ebuild looks fine, but at least with games-engines/odamex, the sound doesn't seem to work anymore. Some other games work fine though. 😕 Please could you test with this.

It works fine, you just need to enable MIDI support with `midi` use flag.

**Pull request closed without merging**
