### PR TITLE
sys-cluster/glusterfs: Bump to 3.12.0, EAPI 6, fix #616760, and more

### PR DESCRIPTION
**Pull request by chewi**
* Fix URLs.
* Prefix fixes.
* Migration away from autotools-utils.eclass.
* Use upstream tmpfiles.d file.
* Fix poisoned sysmacros.h issue (#616760).

Note that I was going to keyword this for arm but it's still building right now and I also need to keyword dbench first. I guess I should also try it out!

### CODE REVIEW

**Comment by chewi** [comment]
Hmm I just noticed while booting that the tmpfiles.d file complains about a missing gluster user and group. Aren't we supposed to create these?

**Comment by ultrabug** [comment]
@chewi we are yes

**Comment by chewi** [comment]
Okay. I can merge this soon and would have done so already but I was actually trying to put my Portage repository on Gluster and the performance on my humble hardware just wasn't good enough.

**Comment by chewi** [comment]
Merged.

**Comment by ultrabug** [comment]
Thanks @chewi !

**Pull request closed without merging**
