### PR TITLE
net-p2p/syncthing: fix licence & description, update metadata.xml

### PR DESCRIPTION
**Pull request by bor**
switch HOMEPAGE to use 'https://' (redirected by default to it),
description was taken from official repo description,
long description (taken from official site),
also bugs-to link was added

### CODE REVIEW

**Comment by bor** [comment]
https://github.com/syncthing/syncthing/blob/master/LICENSE
`Mozilla Public License Version 2.0`

**Comment by monsieurp** [comment]
@sbraz @gentoo/proxy-maint

**Comment by bor** [comment]
@djc

**Comment by sbraz** [comment]
This looks like a sensible fix :) I don't know if @monsieurp can commit it or if @djc should do it.

**Pull request merged**
