### PR TITLE
dev-python/sabyenc --> dev-python/sabctools bump, net-nntp/sabnzbd bump

### PR DESCRIPTION
**Pull request by joecool1029**
- add net-nntp/sabnzbd-4.0.0_alpha2 (not keyworded)
- add dev-python/sabctools-6.1.0

Realized the old link probably broke for sabyenc since ebuilds fetch the tags, not a release tarball.

### CODE REVIEW

**Comment by joecool1029** [comment]
dirscanner currently failing on sabnzbd-4.0.0_alpha2, says I'm missing mocker, I'm not. So I am skipping that test. Everything else appears to be working.

**Comment by mgorny** [comment]
All other things aside, is sabctools really backwards compatible with the previous module name? If not, then package move isn't appropriate.

**Comment by joecool1029** [comment]
> All other things aside, is sabctools really backwards compatible with the previous module name? If not, then package move isn't appropriate.

No, but it doesn't matter currently anyway. Sabnzbd depends on specific releases of sabyenc/sabctools and it's the only package depending on it in the tree.

I spoke to @thesamesam  before doing this PR as I wasn't sure if I should create a second package and drop sabyenc when the old releases requiring it fell out of portage. They assured me this was the correct way forward. I think if we had to worry about more dependencies than just sabnzbd I would have pushed to split into two packages, but given that it's the dependency for just one package and that package requires specific versions, this should be ok?

**Comment by mgorny** [comment]
Maybe it's "ok" but there's no real benefit from the package move and it adds complexity. I'm not going to stop you but if you really want to pursue it this way, then split it into multiple commits, that is:

1. Commit preparing `sabyenc` for the rename — updating URLs and ensuring that the ebuild will yield *exactly* the same result prior to and after rename (except for the changed docdir because that's inevitable).
2. Doing the rename and just that.
3. Version bumps (also as separate commits).

**Comment by joecool1029** [comment]
> Maybe it's "ok" but there's no real benefit from the package move and it adds complexity. I

I went out of my way to ask advice before doing this and was told to [RTFM](https://devmanual.gentoo.org/ebuild-maintenance/package-moves/index.html) which doesn't really answer what to do in a scenario like this. Needless to say I'm a little annoyed the path I was advised to take is still causing problems.

> split it into multiple commits

I figured I'd have to do this, not a problem I'll complete it shortly. Thanks for taking the time to review this.

**Comment by thesamesam** [comment]
> > Maybe it's "ok" but there's no real benefit from the package move and it adds complexity. I
> 
> I went out of my way to ask advice before doing this and was told to [RTFM](https://devmanual.gentoo.org/ebuild-maintenance/package-moves/index.html) which doesn't really answer what to do in a scenario like this. Needless to say I'm a little annoyed the path I was advised to take is still causing problems.
> 

You asked me how to handle renames, I showed you the manual, then you said you were confused, then I thought we cleared everything up. You did not tell me that there was this situation with the module name or similar or which package it involved.

This isn't a normal rename case. Also, 1. and 2. being split is really mgorny's preference, and it's not always done in that order, although it's fine to do it.

**Comment by thesamesam** [comment]
I don't really want to engage in future if you're going to just take swipes at me because I didn't have a crystal ball.

**Comment by joecool1029** [comment]
I'm not taking swipes, is it not ok that I'm frustrated? I want to do this correctly and learn along the way. Log of me asking yesterday:



The module name changed, if the situation changes in the future where a package other than sabnzbd uses it, we'll be using a different package name from everyone else.

**Comment by thesamesam** [comment]
I didn't see the "old module name" bit last night, sorry. But in any case, I think "I went out of my way to ask, then was told to do this and it's wrong" isn't very helpful.

It's fine to be frustrated, but you don't need to make it sound like I've given you terrible advice and wasted your time either.

**Comment by joecool1029** [comment]
> I didn't see the "old module name" bit last night, sorry.

Thanks, I am following your example in trying to reference as much as possible. I want you to know I tagged you in here for clarification, not to make you look bad. 

> But in any case, I think "I went out of my way to ask, then was told to do this and it's wrong" isn't very helpful.

Do not **ever** contextualize my writing and present it in quotes as if that's something I said. I know what you meant to convey but this is absolutely unacceptable. I'm just a contributor at the end of the day that has to follow what the developers want, but I will not stand to have my words rewritten and presented as my own to suit you or anyone else's perspective on matters.

> It's fine to be frustrated, but you don't need to make it sound like I've given you terrible advice and wasted your time either.

Thanks for the acknowledgement, but to clarify it wasn't wrong information, it was incomplete. I still learned something new from it.

**Comment by joecool1029** [comment]
Changed my mind. I'd have to revbump the current release and change the tarball name to avoid pulling the outdated gentoo one. In order to comply with what mgorny's ask and make the ebuild work the same before and after, I'd have to rewrite it to remove the variables and I don't want to do that just to readd them back in on the next bump. Up to @Kangie if he wants to do the rename, I'll live with being downstream on whatever his choice is with sabnzbd.

**Pull request closed without merging**
