### PR TITLE
net-libs/libsoup: Fix automagic test dependencies

### PR DESCRIPTION
**Pull request by lanodan**
Related: https://bugs.gentoo.org/870019
Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

### CODE REVIEW

**Comment by mattst88** [comment]
What test dependencies are automagic?

**Comment by lanodan** [comment]
As noted in <https://bugs.gentoo.org/870019>, quart and autobahn are.

**Comment by mattst88** [comment]
Sorry this fell off my radar.

Why are we adding a test dependency on `dev-python/autobahn` but then also adding

```diff
+		-Dautobahn=disabled # depends on py-cryptography, which depends on Rust
```

?

**Comment by lanodan** [comment]
Not sure why, removed adding the dependency, together with rebasing on current versions.

**Comment by mattst88** [comment]
Thanks!

If I understand correctly, in this case all the automagic dependencies are tests dependencies, right? That is, they don't change what's installed? If that's right, I think we can probably just modify the stable ebuilds in-place without an revision bump.

**Comment by lanodan** [comment]
> If I understand correctly, in this case all the automagic dependencies are tests dependencies, right? That is, they don't change what's installed? If that's right, I think we can probably just modify the stable ebuilds in-place without an revision bump.

This is correct, sorry for the lag. Rebased and changed it to in-place.

**Comment by mattst88** [comment]
It looks like the `http2_tests` config option was removed in https://gitlab.gnome.org/GNOME/libsoup/-/commit/261cbad7cf9134ba5b63983ccbc61834724ae5ab in v3.1.2.

It was added in https://gitlab.gnome.org/GNOME/libsoup/-/commit/2dae529ab45b8693b1771ccca89b055eda76561b which was first in v2.99.8, so it's not relevant to 2.74 either.

I've dropped it from the commits.

Thanks!

**Pull request closed without merging**
