### PR TITLE
app-misc/elasticsearch: bump to 5.6.3

### PR DESCRIPTION
**Pull request by hydrapolic**

### CODE REVIEW

**Comment by mgorny** [comment]
@hydrapolic, as a side request, would you be interested in adding/maintaining elasticsearch-ruby? Infra would need that.

**Comment by hydrapolic** [comment]
I don't use it yet and so it would be hard for me to test it properly. Probably someone who is going to use it with better ruby knowledge should maintain it.

**Comment by mgorny** [comment]
Don't worry, I take that back. Ruby packaging in Gentoo is such a horrible painful experience I wouldn't wish to make anyone have to do that.

**Comment by hydrapolic** [comment]
I see you did it yourself,was it that bad?

**Comment by mgorny** [comment]
Yes, it's bad. I've only added the packages absolutely necessary for the thing to run, and skipped tests because of missing deps.

Then I've discovered we need the ES-1 branch, swore aloud and hacked it locally on Infra to install the other branch. If you restore older versions of ES, I will add the official ebuilds for them.

However, I suppose bumping it should be relatively easy now. So feel free to add yourself as co-maint. I may look into fixing tests and packaging the remaining sub-libraries one day.

**Comment by mgorny** [comment]
Hmm, and a small request: given that you're bumping N closely related packages, could you merge them into a single pull request? This should be less effort with git on your end than with us having to merge them one by one.

**Comment by hydrapolic** [comment]
I could bump all ES related package in 1 PR, but if someone who has never seen anything from ES is about to review the change, it may be better for him to review 1 package at a time and not to commit all or nothing. But ok, next time for such a trivial bump I can just open 1 PR.

**Comment by hydrapolic** [comment]
Thanks @monsieurp

**Pull request closed without merging**
