### PR TITLE
www-servers/nginx-unit: dynamic web and application server (new package)

### PR DESCRIPTION
**Pull request by rseichter**
Please find attached my initial version of an ebuild for NGINX Unit (for version 1.3, released 2018-07-13).

Quoting the [home website](https://unit.nginx.org):

> NGINX Unit is a dynamic web and application server, designed to run applications in multiple languages. Unit is lightweight, polyglot, and dynamically configured via API. The design of the server allows reconfiguration of specific application parameters as needed by the engineering or operations.

See also [Gentoo Bugzilla](https://bugs.gentoo.org/661074).

### CODE REVIEW

**Comment by hydrapolic** [comment]
Something is not right here, only your commit should appear here.

Git clone gentoo/gentoo,then create a branch,switch to it,commit and create PR. Then then diff only shows your changes.

**Comment by mgorny** [comment]
Oh, so you're the reason I ended up fetching 800 MiB of commits today. You are using the syncing mirror to create commits instead of the source repository. Please **force push** over your branch and don't touch the pull request until you do that, as otherwise you'd mess up our checkouts forever.

**Comment by rseichter** [comment]
@mgorny: Nothing like making a good first impression, is there? I'm very sorry, I still don't know what exactly happened. My local repository seems messed up, I cannot pull anymore. Before I make things any worse, how exactly should I force-push? Would discarding the whole pull request be an option?

**Comment by rseichter** [comment]
I don't understand how, or why, but it seems like I branched from the `stable` branch of `https://github.com/gentoo-mirror/gentoo.git`. What the heck?

What is the best way to abort this pull request in order to minimise the impact on all you guys? I can always create a fresh PR later.

**Comment by mgorny** [comment]
> I don't understand how, or why, but it seems like I branched from the stable branch of https://github.com/gentoo-mirror/gentoo.git. What the heck?

You should have branched from master of https://github.com/gentoo/gentoo.git.

> What is the best way to abort this pull request in order to minimise the impact on all you guys? I can always create a fresh PR later.

Lemme try fixing it for you.

**Comment by mgorny** [comment]
Ok, I've managed to clear all commits out of that branch. This should solve it. Please salvage your work from your local copy before fetching.

**Comment by rseichter** [comment]
> You should have branched from master of https://github.com/gentoo/gentoo.git.

Exactly. Why on earth would I ever branch from the mirror's stable branch? I wish I had an explanation.

> I've managed to clear all commits out of that branch.

Thank you for your quick help, and my sincere apologies for causing extra work for you. I shall delete my  fork's www-servers/nginx-unit branch, have a coffee, read the Gentoo Wiki _again_, and start afresh, creating a new branch.

**Pull request closed without merging**
