### PR TITLE
dev-python/enzyme: add missing PYTHON_REQ_USE

### PR DESCRIPTION
**Pull request by Coacher**
Package-Manager: portage-2.3.0_rc1

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by gktrk** [comment]
Shouldn't this be a revbump? it's forcing a use flag which pulls in extra runtime deps.

**Comment by Coacher** [comment]
Revbumped.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by Coacher** [comment]
Thank you, @gktrk.

**Pull request closed without merging**
