### PR TITLE
app-dicts/ydpdict: Fix call to undeclared function textdomain

### PR DESCRIPTION
**Pull request by listout**
Upstream PR: https://github.com/wojtekka/ydpdict/pull/4

Closes: https://bugs.gentoo.org/894364

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Your pastebin build.log url has expired in the upstream issue. Did it work, did it fail? We can of course ship this one and fix it later too.

**Comment by listout** [comment]
It did not work with the diff @wojtekka's gave

**Comment by listout** [comment]
@juippis http://ix.io/4DPK Build log with @wojtekka's patch

**Comment by thesamesam** [comment]
Yeah, I think the libintl.h include is still needed.

**Review by juippis — APPROVED** [review]
As said, if upstream comes up with a better idea we can update this. But you should update your build.log in the upstream issue since the previous one has expired. You can attach build.logs to GH - you can put it into container's directory location which is shared with your host, and make sure your browser has access to that location too under your username. If you use external sandboxing tools for your browser, that is, such as firejail, bubblewrap, apparmor, selinux and so. 
Or you can use **lxc file pull** to get the log file into your host.

**Pull request closed without merging**
