### PR TITLE
media-gfx/monica: fix Bug 588452, add eapply_user

### PR DESCRIPTION
**Pull request by mm1ke**
This fixes bug [588452](https://bugs.gentoo.org/show_bug.cgi?id=588452)

### CODE REVIEW

**Comment by candrews** [comment]
Instead of using `eapply_user`, I think it would be better to:
* Drop `src_prepare()` entirely
* Use PATCHES instead of doing `epatch` in `src_prepare()`

See https://devmanual.gentoo.org/ebuild-writing/eapi/

I've made these changes and submitted a pull request to you: https://github.com/mm1ke/gentoo/pull/1 I also tested them and the ebuild merged successfully.

**Comment by SoapGentoo** [comment]
Please squash all commits and merges into one commit, preferably retaining @candrews's commit, which is the canonical and simple way to apply patches.

**Comment by mm1ke** [comment]
I'll gonna close this PR as i made a new, clean PR for fixing bug 588452 using @candrews solution.

**Comment by SoapGentoo** [comment]
@mm1ke using **git rebase** and **git push -f** you never have to close a PR for just some edits.

**Pull request closed without merging**
