### PR TITLE
RetroArch & Co

### PR DESCRIPTION
**Pull request by nE0sIghT**
Here is attempt to bring RetroArch and libretro cores for most popular retro platforms to Gentoo.

### CODE REVIEW

**Comment by juippis** [comment]
@candrews this looks like your stuff, any notes?

**Comment by nE0sIghT** [comment]
Updated all packages to actual versions

**Comment by nE0sIghT** [comment]
All packages updated to actual versions

**Comment by ajakk** [comment]
Thank you for your work on this! Unfortunately candrews doesn't seem interested, and because proxy-maint doesn't take new leaf packages anymore I will close this PR. If you're still interested, this would be welcome in the [GURU repository](https://wiki.gentoo.org/wiki/Project:GURU), so please add there!

**Pull request closed without merging**
