### PR TITLE
dev-python/ipykernel: Version bump to 4.5.0

### PR DESCRIPTION
**Pull request by marbre**
@SoapGentoo Just a copy of 4.4.1.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@marbre Please have a look at the ebuild I committed, I've enabled tests (for which I had to struggle with getting `dev-python/nose_warnings_filters` into the tree). The testsuite completes succesfully me then.

**Comment by marbre** [comment]
@SoapGentoo I actually tested ipykernel, while bumping the version to 4.5.1. However, tests fail on my system

```
FAIL: ipykernel.tests.test_kernel.test_matplotlib_inline_on_import
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.4/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/usr/lib64/python3.4/site-packages/IPython/testing/decorators.py", line 212, in skipper_func
    return f(*args, **kwargs)
  File "/var/tmp/portage/dev-python/ipykernel-4.5.1/work/ipykernel-4.5.1/ipykernel/tests/test_kernel.py", line 266, in test_matplotlib_inline_on_import
    nt.assert_in('backend_inline', backend_bundle['data']['text/plain'])
AssertionError: 'backend_inline' not found in "'Qt5Agg'"
----------------------------------------------------------------------
```

Same with 4.5.0. Does it pass on your system?

**Comment by SoapGentoo** [comment]
@marbre matplotlib is broken atm. Could you look into it?

**Comment by marbre** [comment]
@SoapGentoo I currently use the stable 1.4.3, is this version affected too? I'll see if I can spend some time on it, but I cannot promise it.

**Pull request closed without merging**
