### PR TITLE
dev-libs/libuev: Simple event loop for Linux

### PR DESCRIPTION
**Pull request by oz123**
libuev is a simple event loop in the style of the more established

libevent, libev and the venerable Xt(3) event loop. The u (micro) in the
name refers to both the small feature set and the small size overhead
impact of the library.

Experienced developers may appreciate that libuEv is built on top of
modern Linux APIs: epoll, timerfd and signalfd. Note however, a certain
amount of care is needed when dealing with APIs that employ signalfd.

Libuev is required for net-ftp/uftpd (see bug https://bugs.gentoo.org/639564).

Bug: https://bugs.gentoo.org/639630

Package-Manager: Portage-2.3.13, Repoman-2.3.1

### CODE REVIEW

**Comment by kensington** [comment]
This looks pretty good. Is the static library and .la file required for anything? We normally try to avoid installing those by default.

**Comment by oz123** [comment]
@kensington 
The ``configure`` script has both enabled. I can modify the ebuild and disable the building of the static library, if desired.
From the ``configure --help``:
```
  --enable-shared[=PKGS]  build shared libraries [default=yes]
  --enable-static[=PKGS]  build static libraries [default=yes]
```

**Comment by kensington** [comment]
Unless you explicitly need it for something (in which case it should be hidden behind a USE flag), we recommend to just disable that static library.

**Comment by oz123** [comment]
@kensington , no need to add `use_enable` as above?

**Comment by kensington** [comment]
If you prefer to expose the option, that's fine too.

I didn't check the source, but based on that help snippet and assuming the build system is autotools, you probably want ``econf --enable-static=$(usex static-libs)``

**Comment by oz123** [comment]
@kensington okay!
Thanks btw, I didn't know about `usex` (still new to EAPI 6).

**Comment by oz123** [comment]
@kensington The static lib is now excluded from the ebuild.

**Comment by kensington** [comment]
Great, thanks! I think the .la file [can go](https://blog.flameeyes.eu/2009/09/removing-la-files-for-dum-w-uncertain-people/) too, but let me know if you just want me to squash this in when I merge.

**Comment by oz123** [comment]
@kensington go ahead make the squash, this also needs to be done with libite, so I will watch and learn.

Much appreciated !

**Comment by kensington** [comment]
Thanks! I squashed in a couple of minor little things too.

**Pull request closed without merging**
