### PR TITLE
sci-geosciences/gmt: version bump

### PR DESCRIPTION
**Pull request by uleysky**
Update ebuild to the version 4.5.18 and update the coastline database.
Closes: https://bugs.gentoo.org/512834

### CODE REVIEW

**Comment by Amynka** [comment]
Hey, did you think how to address this issue [1].

[1] https://bugs.gentoo.org/492792#c9

**Comment by uleysky** [comment]
Amynka, yes, I think. There are some problems with it.
1) It is necessary to make a slots for gmt-4 and gmt-5.
2) It is necessary to separate databases of coastlines and countries in own ebuilds.
3) Gmt-5 uses cmake, not configure. And the different set of dependencies. Many new flags and tests.
I builded Gmt-5 for myself, it's not a problem, but I'm not very familiar with writing ebuilds. In any case, I plan to address this issue, gradually solving the above problems.

**Comment by Amynka** [comment]
Sounds good to me want to make PR for that? :)

**Comment by uleysky** [comment]
First a job has to be done, then PR :)

**Comment by Amynka** [comment]
True.. My point is it might be good idea to clean it all at once even with this version bump to the new slot?

**Comment by uleysky** [comment]
The gmt ebuilds already have a SLOT=0. It would be more logical to make SLOT=4. But this will require editing of all ebuilds, including stable ones, and I'm not sure that this is really necessary.

**Comment by Amynka** [comment]
Question is can both version be installed at the same time?

**Comment by uleysky** [comment]
Versions 4 and 5 definitely can be installed at the same time. Such installation supported by upstream, but they use a special script to switch between versions (analog of the eselect). Nevertheless, simultaneous operation of both versions is possible. I want to implement an option when the command "triangulate" uses gmt4 and the command "gmt triangulate" uses gmt5.

**Comment by uleysky** [comment]
Amynka, I finished work on GMT5. But I think it's better to make a separate pull request for this, because there are questions that need to be clarified.

**Comment by Amynka** [comment]
Alright

**Pull request closed without merging**
