### PR TITLE
media-plugins/vdr-Pkgcheck fixes #1

### PR DESCRIPTION
**Pull request by madmartin**
d41ff7885989 G - Martin Dummer / media-plugins/vdr-dummydevice: update EAPI 7 -> 8
4caab04de2ea G - Martin Dummer / media-plugins/vdr-cdplayer: update EAPI 7 -> 8
dfa978ea2848 G - Martin Dummer / media-plugins/vdr-calc: update EAPI 7 -> 8
2af69efdd026 G - Martin Dummer / media-plugins/vdr-clock: update EAPI 7 -> 8
dda23b664e46 G - Martin Dummer / media-plugins/vdr-beep: update EAPI 7 -> 8
4af4a6330808 G - Martin Dummer / media-plugins/vdr-avards: drop 0.2.4, eapi 7->8
65c35e364a32 G - Martin Dummer / media-plugins/vdr-streamdev: drop 0.6.1_p20170930

### CODE REVIEW

**Comment by ConiKost** [comment]
Do all vdr plugins need this?

```
DEPEND="media-video/vdr"
RDEPEND="${DEPEND}"
BDEPEND="${DEPEND}"
```

I do wonder, if in this case, this should not be automatically added by the ```vdr-plugin-2``` eclass?

**Comment by madmartin** [comment]
> Do all vdr plugins need this?

BDEPEND: yes, vdr plugins need vdr header files during compile


> 
> I do wonder, if in this case, this should not be automatically added by the `vdr-plugin-2` eclass?

Hmm it should, I should double check it.

**Comment by madmartin** [comment]
> So many QA errors
> 
> There's something about **vdr-beep** and it refuses to install. But I doubt it's related to EAPI change.
> 
> ```
> >>> Install media-plugins/vdr-beep-0.1.2 into /var/tmp/portage/media-plugins/vdr-beep-0.1.2/image
>  * QA Notice: Plugin use still the old Makefile handling
>  * Installing locales
> cp: cannot stat 'en*': No such file or directory
>  * ERROR: media-plugins/vdr-beep-0.1.2::gentoo failed (install phase):
>  *   could not copy linguas files
> ```

Hello @juippis ,
the ebuild works fine, but you must not define `LINGUAS="en"` - you can define any `LINGUAS` you want, but not `"en"` - it is the default language, and LINGUAS defines the extra translations to be copied.
Please retry....

**Comment by madmartin** [comment]
@juippis added a small fix to media-plugins/vdr-streamdev

**Comment by juippis** [comment]
> Hello @juippis , the ebuild works fine, but you must not define `LINGUAS="en"` - you can define any `LINGUAS` codes you want, except `"en"` - it is the default language, and LINGUAS defines the extra translations to be copied. Please retry....

That makes absolutely no sense. If you know that is causing the problem, could you fix it in the ebuild?

I'll merge this since as I said, this was probably broken on previous version too, but please make a new PR handling this ridiculous restriction.

**Comment by madmartin** [comment]
@juippis First, thanks for merging!

Second, yes you are right - this is really confusing and makes no sense. I use vdr with gentoo at least 15 years, and have discovered this just now on after your finding....
The best option will be a change in the function vdr-plugin-2_src_install - just silently ignore a lingua "en". 
I remember discussions that the old vdr maintainer "hd_brummy" had with sam or mgorny (dont remember exactly) about the linguas concept at all, and the confusion caused with the attempt to convert that to the L10N variable....

**Pull request closed without merging**
