### PR TITLE
sci-lib/sundials: install LICENSE to correct place. closes: #679160

### PR DESCRIPTION
**Pull request by cdluminate**
Fixes: https://bugs.gentoo.org/679160

### CODE REVIEW

**Comment by cdluminate** [comment]
@heroxbd

**Comment by wimmuskee** [comment]
A better commit message can be made by following the [standard](https://www.gentoo.org/glep/glep-0066.html#commit-messages). You definitely need the **Signed-off-by** keyword, and in this case the **Closes** keyword, both with the correct info. If in doubt, look at some recent commits on the master branch.

You can _git commit --amend_ your original commit message and force push to your branch to update the pull request.

**Comment by heroxbd** [comment]
Thanks, I second @wimmuskee 's comment.

**Comment by cdluminate** [comment]
@gentoo-bot The commit has been standarlized.

**Comment by heroxbd** [comment]
I don't think it ideal to install LICENSE into `/usr/include/sundials` either.  It should be put into `/usr/share/doc/sundials-3.1.0/LICENSE`.

**Comment by cdluminate** [comment]
@heroxbd I totally agree with you but the installation path is decided by upstream: https://sources.debian.org/src/sundials/3.1.2+dfsg-3/CMakeLists.txt/#L1638

I just picked that change from upstream/3.1.2 release.

**Comment by heroxbd** [comment]
> @heroxbd I totally agree with you but the installation path is decided by upstream: https://sources.debian.org/src/sundials/3.1.2+dfsg-3/CMakeLists.txt/#L1638

This is a bug of upstream.  We can either patch the build system or move `LICENSE` to `/usr/share/doc`.

> I just picked that change from upstream/3.1.2 release.

Then, we'd better just bump the version to 3.1.2.

**Comment by cdluminate** [comment]
This PR has been replaced by https://github.com/gentoo/gentoo/pull/11715

**Pull request closed without merging**
