### PR TITLE
cmake-utils--, misc cleanup

### PR DESCRIPTION
**Pull request by a17r**
Maintainers, please ack your packages.

### CODE REVIEW

**Review by sarnex — APPROVED** [review]

**Comment by voyageur** [comment]
Looking good for net-libs/librsync with https://bugs.gentoo.org/822252

**Comment by blueness** [comment]
ack for fcron cleanup

**Comment by atupone** [comment]
ack for media-libs/glm

**Comment by a17r** [comment]
ping @candrews ...

**Comment by candrews** [comment]
Good by me!

**Comment by a17r** [comment]
thanks.

**Pull request merged**
