### PR TITLE
sys-block/open-iscsi: Remove unnecessary dependency on udev (bug #563082)

### PR DESCRIPTION
**Pull request by jirutka**
More info on bugzilla: [#563082](https://bugs.gentoo.org/show_bug.cgi?id=563082).

### CODE REVIEW

**Comment by mgorny** [comment]
@jirutka, are you still there? I've asked on Bugzie if there's any real reason to disable udev rules at all. If there is, I'm going to merge this. If there is not and udev is not used in any other way, please just remove the dependency instead.

**Comment by jirutka** [comment]
@mgorny Yeah, I’m here, sorry for late response. I don’t know about any other reason than avoiding pollution of system with useless files. ;)

**Comment by mgorny** [comment]
Ok. Then please remove the flag, remove the dep and use `doexe` as I pasted above. Can you do that? ;-)

**Comment by jirutka** [comment]
Yeah, of course! Wait a minute. :smile_cat:

**Comment by jirutka** [comment]
Done.

**Comment by mgorny** [comment]
Oh man! Your commit message is too long (see how github strips it). Try `Remove unnecessary dependency on udev, #nnnnnn`

**Comment by jirutka** [comment]
Grrr, it was only 74 characters long… But okay, fixed now.

**Comment by mgorny** [comment]
Thanks a lot. Gonna merge now.

**Pull request merged**
