### PR TITLE
net-p2p/syncthing: bump to 0.12.19, add init script, man, logrotate

### PR DESCRIPTION
**Pull request by sbraz**
@djc Here's the pull request we discussed.
Thanks to @bor and @Dr-Terrible; my scripts are heavily based on theirs.

### CODE REVIEW

**Comment by sbraz** [comment]
Updated to include the newest release that should pass tests on x86 too. I wasn't able to test it myself though so I didn't change KEYWORDS. @djc can you test it on x86? I'll add the keyword then.

**Comment by bor** [comment]
What about to add systemd/init.d stuff by condition?
like
```
	if use systemd; then
		systemd_dounit etc/linux-systemd/system/${PN}@.service
		systemd_douserunit etc/linux-systemd/user/${PN}.service
	else
		newconfd "${FILESDIR}"/${PN}.confd ${PN}
		newinitd "${FILESDIR}"/${PN}.initd ${PN}
	fi
```

**Comment by bor** [comment]
Another point: please use my approach for `${PN}.logrotate`.
It care about systemd also, not just about init.d

**Comment by sbraz** [comment]
@bor I envisaged it for a while but I realised it's against Gentoo's policy, see https://wiki.gentoo.org/wiki/Project:Systemd/Ebuild_policy#General_guidelines
> Ebuilds must not introduce USE=systemd

Anyway, systemd uses journald by default, not `/var/log/syncthing/syncthing.log`. If you want to log syncthing's output in a separate log and have your own logrotate config, it's fine but it's beyond the scope of this ebuild.

**Comment by bor** [comment]
@sbraz thanks for the explanation & link, wasn't aware about that.
I will reduce my ebuild also.

**Comment by djc** [comment]
Rebased these and pushed them, after disabling the tests again in an extra commit. Thanks!

**Pull request closed without merging**
