### PR TITLE
dev-java/jetty-io: Initial ebuild for jetty-io

### PR DESCRIPTION
**Pull request by wltjr**
@gentoo/java Initial ebuild for jetty-io, dependency of other jetty ebuilds to
come. Which are dependencies of other things like netty-handler in tree
that needs to be updated, but cannot be without such dependencies. This depends on PR #210

### CODE REVIEW

**Comment by hasufell** [comment]
@chewi @monsieurp

**Comment by hasufell** [comment]
The QA reports seem to be false positives because ebuild commits haven't been in one PR and I think they should be (for the future), also to ensure correct commit order.

**Comment by wltjr** [comment]
Not sure that is possible as there will be more coming and still in the works. This is all part of the dependency chain for updating netty-handler and other things to come. Other ebuilds are still in the works. Waiting till all are in one will slow things down. The QA report should look at dependencies. As I did base these branches off the jetty-util one. I think github should like that per their documentation, not sure if that happened. Not sure how the QA CI stuff handles that.

**Comment by wltjr** [comment]
Closing, I will just let you all come fetch this stuff from my overlay or not. Doesn't matter to me if stuff in tree is updated. This is all needed to update netty-handler to current 4.0.32 :)

**Pull request closed without merging**
