### PR TITLE
dev-libs/quazip: bump version to 1.3

### PR DESCRIPTION
**Pull request by flowln**
Closes: https://bugs.gentoo.org/839264

Differences from 1.2 are:
- Updated patch because the `CMakeFiles.txt` has been changed since 1.2
- Removed `-DQUAZIP_QT_MAJOR_VERSION=5` because upstream now automatically detects the Qt version
- Made all KEYWORDS unstable (sorry for not knowing if I should do it or not, but repoman told me to, so I just followed it!)

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Thiago Donato Ferreira <flowlnlnln@gmail.com>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Great, Thanks :+1:

**Comment by thesamesam** [comment]
>Removed -DQUAZIP_QT_MAJOR_VERSION=5 because upstream now automatically detects the Qt version

We don't want that because it means it'll [automagically](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies) use Qt 6 if installed, even though the package doesn't depend on it.

re KEYWORDS, see [devmanual](https://devmanual.gentoo.org/keywording/index.html#keywording-on-upgrades) (you did it right).

**Comment by flowln** [comment]
> We don't want that because it means it'll [automagically](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/Automagic_dependencies) use Qt 6 if installed, even though the package doesn't depend on it.

Ohh I see, sorry then!

> re KEYWORDS, see [devmanual](https://devmanual.gentoo.org/keywording/index.html#keywording-on-upgrades) (you did it right).

I'll read it, thank you!

**Comment by thesamesam** [comment]
No worries! This stuff takes time to learn (and make sense of) 😃

**Pull request closed without merging**
