### PR TITLE
dev-java/*: remove unused patches and files

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

Basically the same like the last PR, but with the branch merge. This PR removes unused patches and files from dev-java/*
@monsieurp: Should be fine now :)

### CODE REVIEW

**Comment by floppym** [comment]
@gentoo/java: Please review.

**Comment by chewi** [comment]
Sorry, some of these were because of me. I take it this is an automated check? I'm not going to check them all manually and I was going to say that I trust it works but I did find one mistake. `dev-java/jna/files/jna-3.4.0-makefile-flags.patch` is still being used.

**Comment by mm1ke** [comment]
Well, it's an semi automated check.. I wrote a script which checks for obsolete patches. However, i always double/triple check the output for false-positives which is still common. If you want to check out the script you can have a look here: https://github.com/mm1ke/gentoo-scripts

**Comment by chewi** [comment]
Merged, thanks!

**Pull request merged**
