### PR TITLE
www-client/elinks: add libressl support also to live ebuild

### PR DESCRIPTION
**Pull request by doughdemon**

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Could you please file a bug so that the proxy maintainer of this package is aware of this change? Thanks.

**Comment by SoapGentoo** [comment]
Also please add subslot operators to both openssl and libressl.

**Comment by doughdemon** [comment]
monsieurp wrote:
> Could you please file a bug so that the proxy maintainer of this package is aware of this change? Thanks.

There is already a bug on this topic

https://bugs.gentoo.org/show_bug.cgi?id=566068

with no reply from the proxy-maintainer since months.


This pull-request just copies

https://github.com/gentoo/gentoo/commit/807b6c2744675b40ccda55e350e4f8b49d5cd2cf

which added libressl support only to the non-live version.
So maybe also @blueness

**Comment by blueness** [comment]
i took care of this

**Pull request closed without merging**
