### PR TITLE
gnome-extra/gnome-commander: add 1.16.1

### PR DESCRIPTION
**Pull request by turboscholz**
Closes: https://bugs.gentoo.org/906473

### CODE REVIEW

**Comment by mattst88** [comment]
Can we drop the dependency on libunique? (https://gitlab.gnome.org/GNOME/gnome-commander/-/issues/127)

**Comment by turboscholz** [comment]
I removed the dependency from the ebuild since `libunique` is not mandatory.

**Review by a17r — APPROVED** [review]

**Review by a17r — CHANGES_REQUESTED** [review]
If you just drop the dependency and meson_feature, then this ends up to be an unacceptable automagic dependency (gnome-commander still links with libunique if installed), visible as preserved-rebuild fragment once people cleanup libunique package.

Can you hard-disable it for this package?

**Comment by turboscholz** [comment]
Is hard-disabling possible somehow in the ebuild? Since other distributions still ship libunique I don't want to throw the dependency out in upstream yet. If nothing helps we can also create a patch. But I don't know if and when I will find the time for it.

**Comment by mattst88** [comment]
*sigh*

> If needed, package maintainers can remove the dependency completely.

But also... I don't know how to remove the dependency.

**Comment by turboscholz** [comment]
If anybody of you knows how to create a ebuild patch, here is what needs to happen in it:

https://gitlab.gnome.org/GNOME/gnome-commander/-/blob/master/meson_options.txt#L7

Instead of `value: 'auto'` it should be `value: 'false'` in line 7 so that unique support will be deactivated when configuring the package. That should do it.

Later on when libunique is removed from gnome commander, the patch can be removed as well.

**Comment by mattst88** [comment]
/o\

You just disable the feature...?

That is, instead of removing `$(meson_feature unique)` from `src_configure`, you replace it with `-Dunique=disabled`.

I've done that in commit b1bc5b49d4bcdfb3313f4caf140f117d8013ca3b.

**Comment by turboscholz** [comment]
Ah! Thanks. This is the only package I maintain in Gentoo voluntarily. Please have mercy on me. ... ^_^ Recently I have not much time to dig into the mysteries of this distribution because of challenges in real live.

**Pull request closed without merging**
