### PR TITLE
Cinnamon 4.6 Version Bump

### PR DESCRIPTION
**Pull request by SparkyBluefang**
https://bugs.gentoo.org/733544

This updates the Cinnamon collection of packages to the latest released 4.6.x versions. The remaining EAPI=6/gnome2 packages have also been updated to EAPI=7.

For transparency: Cinnamon 4.6 reworked multi-display and HiDPI support. Most major regressions seem to be addressed at this point, but there are still some remaining issues being reported/fixed, such as:
https://github.com/linuxmint/cinnamon-control-center/issues/241
https://github.com/linuxmint/cinnamon/issues/9371
https://github.com/linuxmint/cinnamon/issues/9452
https://github.com/linuxmint/cinnamon/issues/9462

This also includes a few dependency fixes that have been back-ported to the 4.4.x packages.

This also supersedes #16103 with a newer version of nemo.

### CODE REVIEW

**Comment by ajakk** [comment]
Please rebase and force push to get more accurate CI results.

**Comment by thesamesam** [comment]
cinnamon-screensaver failed to build:
- [build.log](https://github.com/gentoo/gentoo/files/5046689/build.log)
- [meson-log.txt](https://github.com/gentoo/gentoo/files/5046688/meson-log.txt)

Excerpt:
```
Program g-codegen.py found: YES (/usr/bin/python3.7 /var/tmp/portage/gnome-extra/cinnamon-screensaver-4.6.0/work/cinnamon-screensaver-4.6.0/libcscreensaver/g-codegen.py)

libcscreensaver/meson.build:148:0: ERROR: Unknown variable "xinerama".

A full log can be found at /var/tmp/portage/gnome-extra/cinnamon-screensaver-4.6.0/work/cinnamon-screensaver-4.6.0-build/meson-logs/meson-log.txt
 * ERROR: gnome-extra/cinnamon-screensaver-4.6.0::gentoo failed (configure phase):
 *   (no error message)
```

**Comment by thesamesam** [comment]
@SparkyBluefang Have you been able to hit the failure I showed?

**Comment by SparkyBluefang** [comment]
@thesamesam Sorry, I totally missed that you had commented. My email DNS was busted at the beginning of the month, so I missed some notifications. I haven't seen that failure, but I'll dig into it when I have a free moment.

**Comment by SparkyBluefang** [comment]
@thesamesam cinnamon-screensaver[-xinerama] builds should be fixed now.

**Comment by thesamesam** [comment]
Not forgot about this -- building stuff in a chroot (with binpkgs to speed up testing of anything graphical) at present.

**Review by thesamesam — APPROVED** [review]

**Comment by thesamesam** [comment]
Thank you for this!

**Pull request closed without merging**
