### PR TITLE
www-client/qutebrowser: Update Desktop file name

### PR DESCRIPTION
**Pull request by ykgmfq**
This belongs to https://github.com/qutebrowser/qutebrowser/pull/4547.

### CODE REVIEW

**Comment by jsbronder** [comment]
Merged:
adbabc7f47db www-client/qutebrowser: Update Desktop file name

**Comment by jsbronder** [comment]
And reverted, bleh.  Upstream isn't using that path, https://github.com/qutebrowser/qutebrowser/blob/master/misc/qutebrowser.desktop.  Did you mean to rename it, and if so, is this due to some policy for desktop files?

**Comment by jsbronder** [comment]
I see, it's waiting on an upstream PR to get merged.  When that happens, I'll pull this in.  Sorry for the noise.

**Comment by ykgmfq** [comment]
Sorry for the confusion 🙃 please merge now.

**Comment by jsbronder** [comment]
Merged, thanks!

6a8708c54b87 www-client/qutebrowser: Update Desktop file name

**Pull request closed without merging**
