### PR TITLE
dev-java/tomcat-native: Add 2.0.1

### PR DESCRIPTION
**Pull request by orbea**
Also adds a patch to fix the build with rlibtool.

Bug: https://bugs.gentoo.org/778914
Upstream-PR: https://github.com/apache/tomcat-native/pull/14

### CODE REVIEW

**Comment by fordfrog** [comment]
i will have to test this with the tomcat versions we have currently in the tree. also, upstream website states that minimum supported version of java is 11 which would not work with tomcat versions 10 and lower which support also version 8 of java. though i can see in your ebuild you still have version 1.8 set, but idk whether for your tests jdk 1.8 or a newer version was used for compilation.

**Comment by orbea** [comment]
It defaulted to `dev-java/openjdk-bin-17.0.3_p7:17::gentoo` when I was tested this. The build including the test phase worked for me, but I don't know much about java so review is welcome. My main goal is fixing the remaining slibtool issues.

**Comment by orbea** [comment]
@fordfrog Any news?

**Comment by fordfrog** [comment]
i just tried to compile it and it failed because if needs at least `dev-libs/openssl-3.0.0`, so it has to be specified in the deps.

**Comment by fordfrog** [comment]
this has been resolved via another pr, we have now `2.0.2` in the tree. thank you!

**Pull request closed without merging**
