### PR TITLE
dev-python/peewee: add ebuild for version 2.8.0

### PR DESCRIPTION
**Pull request by Elizafox**
Simple bump, tested and works fine for me.

### CODE REVIEW

**Comment by idella** [comment]
2 issues currenty:

1.  * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * playhouse/speedups.c:4587:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 * playhouse/_sqlite_ext.c:1894:5: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]
 * playhouse/_sqlite_ext.c:1915:3: warning: dereferencing type-punned pointer will break strict-aliasing rules [-Wstrict-aliasing]


2.  * ERROR: dev-python/peewee-2.8.0::gentoo failed (install phase):
 *   EXAMPLES are banned in EAPI 6

**Comment by idella** [comment]
That would mean that you need explicitly add the Manifest file (git add Manifest)  and re-submit

**Comment by gktrk** [comment]
Hi! I would like to nitpick 2 things if you don't mind:

- Out-of-date copyright year in the header
- For atomicity, 3b00397 should be fixed up to ee08190 if possible. As long as an explicit merge commit is created for this changeset, however, it doesn't break atomicity. Just wanted to bring it to attention.

**Comment by Elizafox** [comment]
I am presuming a merge commit will be made.

**Comment by Elizafox** [comment]
Squashed the commits.

**Comment by Elizafox** [comment]
Another force update to fix the examples build.

**Comment by idella** [comment]
Be aware the error of dev-lang/idb is as it states;   from underlying repository state:

**Comment by Elizafox** [comment]
I do not consider dev-lang/idb to be under my provenance (that's under the sci project); it is not related to peewee in the slightest. That belongs in another issue; also keep in mind my branch is behind master.

**Comment by monsieurp** [comment]
Thanks for your work. Pushed.

**Pull request merged**
