### PR TITLE
dev-libs/gobject-introspection, dev-libs/gobject-introspection-common: Version bump to 1.75.6 BETA

### PR DESCRIPTION
**Pull request by flint2**
Need mask, in preparation for Gnome 44

### CODE REVIEW

**Comment by mattst88** [comment]
````
Dependency glib-2.0 found: NO found 2.74.6 but need: '>=2.75.0'
````

Please test the PRs. I know some things will slip through, and that's what review is for, but it's not a good use of reviewers' time to catch things like this.

**Comment by mattst88** [comment]
> Please test the PRs. I know some things will slip through, and that's what review is for, but it's not a good use of reviewers' time to catch things like this.

I was probably wrong to suggest that you hadn't tested this—I suspect you did and you just already had glib-2.75.4 installed since you already provided a PR for that. Sorry.

Something to note about gobject-introspection: the minor version should match the glib minor version. E.g. gobject-introspection-1.74 depends on glib-2.74, etc. It's not obvious from the build scripts, but here's the logic that controls it, in gobject-introspection's `meson.build`:

````
# Reset to 0 if g-i micro version exceeds GLib's
glib_micro_version = 0  # gi_version[2]
glib_version = '>=2.@0@.@1@'.format(gi_versions[1], glib_micro_version)

glib_dep = dependency('glib-2.0', version: glib_version,
                      default_options: ['tests=false'])
````

**Comment by flint2** [comment]
> introspection: the minor version should match the glib minor version. E.g. gobject-introspection-1.74 depends on glib-2.74, et

I did a quick test after installing, I've tried to follow the order of https://wiki.gentoo.org/wiki/Project:GNOME/GNOME_Bumping_Guide#glib for the PRs unless I hit a dependency and needed to change the order.
Will look into gobject-introspection issue later
Thanks!

**Comment by flint2** [comment]
Removed mask, will do a PR with only one commit for masking all Gnome 44 BETA related packages

If glib 1.75 is a dependency, should be included in same PR?

What do you suggest?

**Comment by mattst88** [comment]
> If glib 1.75 is a dependency, should be included in same PR?
> 
> What do you suggest?

That's probably a good idea for the future.

**Pull request closed without merging**
