### PR TITLE
net-misc/xmrig: Move optional rdep to optfeature

### PR DESCRIPTION
**Pull request by 00-matt**

### CODE REVIEW

**Comment by candrews** [comment]
The systemd service would also have to be updated to make msr-tools usage optional.

**Comment by 00-matt** [comment]
Thanks for catching that! I didn't look too deeply into the XMRig service because I don't use it.

Do you think it's patching `randomx_boost.sh` to check for the existence of `/usr/sbin/rdmsr` and `/usr/sbin/wrmsr` before running would be enough?

**Comment by candrews** [comment]
Perhaps?

But what's the motivation? What benefit does the user get by having this dependency be optional? I feel like all users would benefit from this dependency.

**Comment by 00-matt** [comment]
Sorry, I mis-remembered the devmanual.  I thought it said to never put optional runtime deps in RDEPENDS, but it actually just says not to make USE flags for them.

**Pull request closed without merging**
