### PR TITLE
dev-util/idea-community: not remove jetbrains runtime

### PR DESCRIPTION
**Pull request by unlsycn**
The Jetbrains runtime cannot simply be replaced by the user's Java runtime since it has some specific features. For example, removing it will break the Wayland support based on WLToolkit.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by unlsycn** [comment]
Another acceptable option might be to package JBR standalone and make all JetBrains packages depend on it.

**Comment by unlsycn** [comment]
cc @mpagano

**Comment by mpagano** [comment]
Seems like a few changes for no reason.  Is the end of this commit what you are really asking for ?

**Comment by unlsycn** [comment]
> Seems like a few changes for no reason. Is the end of this commit what you are really asking for ?

Perhaps I didn't express myself clearly. Forgive my poor English. 

[This line](https://github.com/unlsycn/gentoo/blob/75fee9cbbf6b002d3c585cb29f30a83be6c6241f/dev-util/idea-community/idea-community-2024.2.2.ebuild#L133) that removes the Jetbrains Runtime will break some specific features like wayland support.

**Comment by unlsycn** [comment]
> Seems like a few changes for no reason. Is the end of this commit what you are really asking for ?

Sorry, I just notice that my formatter changes something irrelevant, which might cause the commit to look obfuscated.

**Comment by mpagano** [comment]
"For example, removing it will break the Wayland support based on WLToolkit."

Are you saying this only  exists in the Java runtime from idea or should we just be matching what they bundle with. The newest version including: JAVA_VERSION="21.0.4"

**Comment by unlsycn** [comment]
> "For example, removing it will break the Wayland support based on WLToolkit."
> 
> Are you saying this only  exists in the Java runtime from idea or should we just be matching what they bundle with. The newest version including: JAVA_VERSION="21.0.4"

I think this feature only exists in the [Jetbrains Runtime](https://github.com/JetBrains/JetBrainsRuntime) since you can find the commits for it.

**Comment by mpagano** [comment]
Thanks for your replies. You are correct. I'll fix this, but not with this pull request since it has some extra changes that are not needed.  Thanks for your work.  I'll close this once I fix it.

**Comment by mpagano** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=037e8638df7d222b5c089c5447e079ed5748e8b0

**Pull request closed without merging**
