### PR TITLE
sci-geosciences/bt747: build without BSFIX, drop java-ant-2

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog this PR contains the fix for https://bugs.gentoo.org/939021
```
# Java 11 because of compile error with 1.8
# /var/tmp/portage/sci-geosciences/bt747-2.1.7-r3/work/build.xml:1478:
# java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
DEPEND="${CDEPEND}
	>=virtual/jdk-1.8:*
	>=virtual/jdk-11:*
"
```

**Comment by fordfrog** [comment]
i can't test it because i can't emerge `rxtx` (https://bugs.gentoo.org/927898)

**Comment by vaukai** [comment]
> i can't test it because i can't emerge `rxtx` (https://bugs.gentoo.org/927898)

what should we do? ago opened that [bug](https://bugs.gentoo.org/939021). maybe he could merge this?
otherwise i'd really like to `last-rite` this package as i am almost sure nobody uses or needs it. 
why unused? between [commit b28ee9959f](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=b28ee9959f571130fe9530d423fd8eff3055aede) leading to [bug 833946](https://bugs.gentoo.org/833946) and [commit c519379f6e](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c519379f6e313e9a060a819c3316723070239682) it not at all get compiled but there were no complaints, no bugs.

i could prepare the `last-rite` PR. would you support it?

**Comment by vaukai** [comment]
@fordfrog have you seen the PR in https://bugs.gentoo.org/927898?

**Pull request closed without merging**
