### PR TITLE
net-misc/asterisk: back-port security fix for 16.30.1

### PR DESCRIPTION
**Pull request by jkroonza**
Bug: https://bugs.gentoo.org/937844

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
utils.c:99:12: error: static declaration of 'gethostbyname_r' follows non-static declaration
   99 | static int gethostbyname_r (const char *name, struct hostent *ret, char *buf,
      |            ^~~~~~~~~~~~~~~
In file included from /var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/include/asterisk/network.h:46,
                 from utils.c:45:
/usr/include/netdb.h:177:12: note: previous declaration of 'gethostbyname_r' with type 'int(const char * restrict,  struct hostent * restrict,  char * restrict,  size_t,  struct hostent ** restrict,  int * restrict)' {aka 'int(const char * restrict,  struct hostent * restrict,  char * restrict,  long unsigned int,  struct hostent ** restrict,  int * restrict)'}
  177 | extern int gethostbyname_r (const char *__restrict __name,
      |            ^~~~~~~~~~~~~~~
x86_64-pc-linux-gnu-gcc -o version.o -c version.c -MD -MT version.o -MF .version.o.d -MP -pthread -I/var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/include -march=native -O2 -pipe -frecord-gcc-switches  -I/usr/include/libxml2 -Wall -Wstrict-prototypes -Wmissing-prototypes -Wmissing-declarations     -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=2 -DAST_MODULE=\"core\" -DAST_IN_CORE
make[1]: *** [/var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/Makefile.rules:165: utils.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/main'
make: *** [Makefile:396: main] Error 2
 * ERROR: net-misc/asterisk-16.30.1-r3::gentoo failed (compile phase):
```
but I compiled asterisk-16.30 just fine earlier today? Am I missing a dep or did the patch break this?

**Comment by jkroonza** [comment]
Your USE flags?  I just recompiled this one too as a test with no problems.

The patch only touches manager.c, I know mgorny provided me some patches a while back to deal iwth things like gethostbyname_r detection in ./configure ... but those have been upstreamed for some time.

Possibly (but unlikely) a missing DEPEND="".

**Comment by jkroonza** [comment]
man page says the function is deprecated, perhaps you also got a newer libc between then and now that no longer thas this?

```
gethostbyname(3)

       [[deprecated]]
       int gethostbyname_r(const char *restrict name,
                        struct hostent *restrict ret,
                        char buf[restrict .buflen], size_t buflen,
                        struct hostent **restrict result,
                        int *restrict h_errnop);
```

The specific file has:

  87 #if !defined(HAVE_GETHOSTBYNAME_R_5) && !defined(HAVE_GETHOSTBYNAME_R_6)

+2021-11-10 20:05 +0000 [e65f7e50b8]  Michał Górny <mgorny@NetBSD.org>
+
+       * BuildSystem: Fix misdetection of gethostbyname_r() on NetBSD
+
+         Fix the configure script not to detect the presence of gethostbyname_r()
+         on NetBSD incorrectly.  NetBSD includes it as an internal libc symbol
+         that is not exposed in system headers and that is incompatible with
+         other implementations.  In order to avoid misdetecting it, perform
+         the symbol check only if the declaration is found in the public header
+         first.
+
+         ASTERISK-29817
+
+         Change-Id: Iafa359b09908251bcd299ff54be003ea129b9eda

And this fix was included.

Looking at the ./configure code I don't see why this would fail for you.

After recompile the only QA notices I see are:

```
 * QA Notice: Found the following implicit function declarations in configure logs:
 *   /var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/config.log:5938 - htonll
 *   /var/tmp/portage/net-misc/asterisk-16.30.1-r3/work/asterisk-16.30.1/config.log:6180 - ntohll
 * Check that no features were accidentally disabled.
 * See https://wiki.gentoo.org/wiki/Modern_C_porting.
```

Which for me is still a sticky one, Sam answered the questions quite nicely in the link, but I'm still trying to convince myself that merely hiding the implicit QA warning is the right thing to do since another possible cause is inclusion of the wrong headers ...

```
QA_CONFIG_IMPL_DECL_SKIP=( htonll )
```

So here I'm still not sold, but Sam usually are right about such matters.

**Comment by juippis** [comment]
I can't compile it with any use flags :) there's no way my glibc version has changed, but maybe something else. Anyway the patch applies and if it works for you, I guess we ship it.

**Comment by jkroonza** [comment]
> I can't compile it with any use flags :) there's no way my glibc version has changed, but maybe something else. Anyway the patch applies and if it works for you, I guess we ship it.

I'd still like to know what causes it ...

**Pull request closed without merging**
