### PR TITLE
sys-apps/yarn: version bump to 0.19.1

### PR DESCRIPTION
**Pull request by soredake**
also removed 9999 version

### CODE REVIEW

**Comment by gktrk** [comment]
why is the live ebuild being removed?

**Comment by soredake** [comment]
@gktrk i've realised that i commited an non-working live ebuild, but in order to get it you must execute 'npm install' or 'yarn install' in src_compile.

**Comment by gktrk** [comment]
I'm not sure if I completely get it, is there no way to fix it? If so, can you separate that out in a separate commit with a clear message as to why it's being removed? Combining a bump with a removal of the live build is bad taste IMO.

**Comment by soredake** [comment]
@gktrk 
>I'm not sure if I completely get it, is there no way to fix it?

I can get the 9999 version work with something like this if you okay with this.
```
IUSE="+bootstrap_npm bootstrap_yarn"
DEPEND="${RDEPEND}
        bootstrap_yarn? ( sys-apps/yarn )
        bootstrap_npm? ( net-libs/nodejs[npm] )

"
src_install() {
        if use bootstrap_yarn; then
                yarn install
        fi
        if use bootstrap_npm; then
                npm install
        fi
}
```

**Comment by soredake** [comment]
ping

**Comment by gktrk** [comment]
I'm not familiar with the internals of your suggested solution but I have two questions: Would that successfully install things under `${ED}`?; Does that require any network activity?

**Comment by soredake** [comment]
> install things under ${ED}

{yarn,npm} installs in the folder from which it was launched, so answer is yes.
>Does that require any network activity?

Yes.

Another way is use 9999.tar.gz (https://nightly.yarnpkg.com/latest.tar.gz) version with pre-installed modules. Then it (https://github.com/gentoo/gentoo/pull/3892#issuecomment-280400984) will not be necessary.

**Comment by gktrk** [comment]
We don't allow network activity during src_* phases, all the distfiles should be fetched beforehand. 9999.tar.gz would be a lot of maintenance overhead because we'd have to regenerate the Manifest for the new tarball every single day. I guess we'll just nuke it :(.

**Comment by soredake** [comment]
@gktrk ok, commits updated.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/967eed6...0c0ad37. Thanks!

**Pull request closed without merging**
