### PR TITLE
profiles/package.mask: Last rite dev-java/icedtea{,-bin}

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
@gyakovlev referring to https://github.com/gentoo/gentoo/pull/28993, would you agree to last-riting `dev-java/icedtea`instead eapi bumping?

**Comment by gnu-andrew** [comment]
Is the intention to drop 8u support from Gentoo?
Otherwise it's not clear why you would drop IcedTea but keep a version of 8u with fewer features (e.g. no Shenandoah, no arm32 support) and questionable changes such as this commit: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=250d2f45f958ccb2a4e3c437d396b88f5d3bd59e

**Comment by vaukai** [comment]
> Is the intention to drop 8u support from Gentoo? Otherwise it's not clear why you would drop IcedTea but keep a version of 8u with fewer features (e.g. no Shenandoah, no arm32 support) and questionable changes such as this commit: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=250d2f45f958ccb2a4e3c437d396b88f5d3bd59e

- Due to lack of maintainer capacity it was intended to last-rite them both, see https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/package.mask?id=9d1c2c7c952dbd66c6594a3ed8ebd648b69e6fab
- Then there was [bug 924945](https://bugs.gentoo.org/924945)
- And then, only and really only because there was/is no `openjdk-bin:8` for `x86`, we concluded to keep the `-bin`: https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/package.mask?id=c75dc8a3278096459ed73e2bae27441175efb8e4

**Comment by gnu-andrew** [comment]
> > Is the intention to drop 8u support from Gentoo? Otherwise it's not clear why you would drop IcedTea but keep a version of 8u with fewer features (e.g. no Shenandoah, no arm32 support) and questionable changes such as this commit: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=250d2f45f958ccb2a4e3c437d396b88f5d3bd59e
> 
>     * Due to lack of maintainer capacity it was intended to last-rite them both, see https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/package.mask?id=9d1c2c7c952dbd66c6594a3ed8ebd648b69e6fab
> 
>     * Then there was [bug 924945](https://bugs.gentoo.org/924945)
> 
>     * And then, only and really only because there was/is no `openjdk-bin:8` for `x86`, we concluded to keep the `-bin`: https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/package.mask?id=c75dc8a3278096459ed73e2bae27441175efb8e4

Ok, thanks. Well that explains why I didn't need to unmask `icedtea-bin` to bootstrap, but not whether 8u support as a whole is to be continued. I would be happy to maintain `dev-java/icedtea` as I did before, but there is not much point if the intent is to remove ` virtual/jdk-1.8.0` and `dev-java/openjdk:8` in the near term as well.

I managed to build the current `dev-java/icedtea` fine yesterday. I looked through the list of bugs and most of them go back years, and would likely apply to `dev-java/openjdk:8` too (IcedTea being a wrapper and extension of the same sources). Some are just requesting updates which would be resolved by bumping to the latest, which should be fairly trivial.  Are there particular bugs that were blockers for IcedTea remaining in the distro or was it just the general lack of a maintainer?

I've never maintained `icedtea-bin` and I'm not sure how those binaries were created. Yesterday is actually the first time I used it at all, as I used to bootstrap via gcj -> IcedTea for OpenJDK 6 or 7 -> IcedTea for OpenJDK 8. It looks like Adoptium have [x86 binaries for 8u](https://adoptium.net/temurin/releases/?arch=x86&version=8) so maybe this could just be added to `openjdk-bin` and `icedtea-bin` dropped?

**Comment by gnu-andrew** [comment]
PR to bump to 3.30: https://github.com/gentoo/gentoo/pull/35942

**Comment by vaukai** [comment]
> It looks like Adoptium have [x86 binaries for 8u](https://adoptium.net/temurin/releases/?arch=x86&version=8) so maybe this could just be added to `openjdk-bin` and `icedtea-bin` dropped?

That link goes to `Operating System` `Windows`. Can `Windows` binaries be used for `Linux`?

**Comment by fordfrog** [comment]
just with regard to removal of java 8 from gentoo, that should not happen for quite some time yet. the official eol for java 8 is [2030-12-31](https://endoflife.date/oracle-jdk)

**Comment by gnu-andrew** [comment]
> > It looks like Adoptium have [x86 binaries for 8u](https://adoptium.net/temurin/releases/?arch=x86&version=8) so maybe this could just be added to `openjdk-bin` and `icedtea-bin` dropped?
> 
> That link goes to `Operating System` `Windows`. Can `Windows` binaries be used for `Linux`?

Ah, I missed that. I thought it was showing only the OS I was on. It looks like they don't support it: https://github.com/adoptium/adoptium-support/issues/521 Sorry for the noise

It looks like Azul are the only vendor to offer x86_32 Linux:

https://adoptium.net/marketplace/?arch=x86&version=8
https://www.azul.com/downloads/?version=java-8-lts&os=linux&architecture=x86-32-bit&package=jdk#zulu

**Comment by gnu-andrew** [comment]
> just with regard to removal of java 8 from gentoo, that should not happen for quite some time yet. the official eol for java 8 is [2030-12-31](https://endoflife.date/oracle-jdk)

That's for the proprietary Oracle JDK. When OpenJDK 8u support ends will depend on the OpenJDK community.

**Comment by vaukai** [comment]
> It looks like Azul are the only vendor to offer x86_32 Linux:
> 
> https://adoptium.net/marketplace/?arch=x86&version=8 https://www.azul.com/downloads/?version=java-8-lts&os=linux&architecture=x86-32-bit&package=jdk#zulu

Created https://bugs.gentoo.org/927961 for it.

**Pull request closed without merging**
