### PR TITLE
dev-util/google-perftools: allow llvm-libunwind to be used

### PR DESCRIPTION
**Pull request by dante-robinson**
Signed-off-by: Dante Robinson danterobinson2000@gmail.com

### CODE REVIEW

**Comment by dante-robinson** [comment]
Signed-off-by: Dante Robinson danterobinson2000@gmail.com

**Comment by Kangie** [comment]
Hi @dante-robinson 

Thanks for opening a PR. There seems to be a few QA issues that we need to resolve before we look at merging:

1. Your commit doesn't contain a [Gentoo Certificate of Origin sign-off](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin). Please read the terms of the CoO and acknowledge them by amending your commit with an appropriate signoff. (`pkgdev` as described below does this [automagically with the right settings in `make.conf`](https://devmanual.gentoo.org/eclass-reference/make.conf/index.html))
2. Your manifest seems to contain things that it shouldn't, in this case it's probably appropriate to regenerate the manifest by removing the file and running `pkgdev manifest` (available from `dev-util/pkgdev`)
3. There's a little extra whitespace at the end of your ebuild causing some QA errors, should be a quick fix.

You can use `pkgcheck scan` within the directory containing your ebuilds (from `dev-util/pkgcheck`) to validate that the QA issues have been resolved without waiting for the QA bot.

**Comment by dante-robinson** [comment]
1, 3 and 4 should all be fixed now 

> 2. Your manifest seems to contain things that it shouldn't, in this case it's probably appropriate to regenerate the manifest by removing the file and running `pkgdev manifest` (available from `dev-util/pkgdev`)

I'm not sure what this means pkgdev wouldn't let me rebuild the manifest in the custom directory I have but did let me generate the manifest I uploaded inside the gentoo repo I have. This manifest is missing ebuild files though is this ok?

> 5. I'd suggest that, rather than removing the dependency entirely, you look into adding `USE=llvm-libunwind`

Well it should be using libunwind by default right and then for systems running Clang/LLVM over GCC it should just run with llvm-libunwind should be fine like is I think. I am unsure how to add libunwind or llvm-libunwind in the dependency options the gentoo wiki doesn't seem to have a great guide on ebuilds besides a basic guide. If you would like to add it should work the same. 

> You can use `pkgcheck scan` within the directory containing your ebuilds (from `dev-util/pkgcheck`) to validate that the QA issues have been resolved without waiting for the QA bot.

I tried that command and it returns nothing after a second or 2 so Im assuming this is ok.

**Comment by Kangie** [comment]
Sorry, this one fell off my radar. I'll look over it this weekend. Thanks for your work so far!

**Comment by Kangie** [comment]
> 1, 3 and 4 should all be fixed now

Unfortunately the sign-off needs to be part of the commit message (i.e. when git asks for a commit message) - comments in the PR won't make it through to when the commits are merged; we can fix this up when we squash your commits. [Here](https://github.com/gentoo/gentoo/commit/463a06f28960ff4931f3811e884eef363573701e) is one of my commits with a detailed commit message under the "short message" (first line) and CoO signoff (twice!).

You'll also need to request a re-scan by appending `[please reassign]` to your PR title so that the bot knows to remove the `no-signoff` label.

3 and 4 look good.

> > 2. Your manifest seems to contain things that it shouldn't, in this case it's probably appropriate to regenerate the manifest by removing the file and running `pkgdev manifest` (available from `dev-util/pkgdev`)
> 
> I'm not sure what this means pkgdev wouldn't let me rebuild the manifest in the custom directory I have but did let me generate the manifest I uploaded inside the gentoo repo I have. This manifest is missing ebuild files though is this ok?

The order of files in the Manifest has changed but that's not a big deal - the issue was only that files other than source archives were in the Manifest.

The "easy" solution (if this comes up in future) is to be in the package directory and run `rm Manifest && pkdgev manifest` so that pkgdev can regenerate the entire file.

> Well it should be using libunwind by default right and then for systems running Clang/LLVM over GCC it should just run with llvm-libunwind should be fine like is I think. I am unsure how to add libunwind or llvm-libunwind in the dependency options the gentoo wiki doesn't seem to have a great guide on ebuilds besides a basic guide. If you would like to add it should work the same.

The `llvm-libunwind` global USE flag controls which implementation of libunwind your system uses; you can only have one available at a time, see: [useflags/llvm-libunwind](https://packages.gentoo.org/useflags/llvm-libunwind)

We need to provide the ability to build the package with either flavour of libunwind, so the ebuild needs to look more like:

```diff
# AIX ppc/ppc64
 KEYWORDS="-* ~amd64 ~arm ~arm64 ~ppc ~ppc64 ~riscv ~x86 ~amd64-linux ~x86-linux"
 
-IUSE="largepages largepages64k +debug minimal optimisememory test static-libs"
+IUSE="largepages largepages64k +debug llvm-libunwind minimal optimisememory test static-libs"
 
 RESTRICT="!test? ( test )"
 
- # TODO: remove the riscv special case once either libunwind has begun supporting this arch
- # or this package allows using llvm-libunwind for other arches
-DEPEND="!ppc64? (
-       riscv? ( sys-libs/llvm-libunwind:= )
-)"
+DEPEND="
+       llvm-libunwind? ( sys-libs/llvm-libunwind:= )
+       !llvm-libunwind? ( sys-libs/libunwind:= )
+"
 RDEPEND="${DEPEND}"
 
 S="${WORKDIR}/${MY_P}"
```

Based on the supported arches for this package and `sys-libs/llvm-libunwind` I don't see a need to retain the special case!

> > You can use `pkgcheck scan` within the directory containing your ebuilds (from `dev-util/pkgcheck`) to validate that the QA issues have been resolved without waiting for the QA bot.
> 
> I tried that command and it returns nothing after a second or 2 so Im assuming this is ok.

No news is good news! Might be worth asking for the output to be more `repoman`-like though - it positively confirms that no issues were detected.

Once you've amended the two packages, it would be ideal to 'squash' the three commits down to one, although this can be done when the package is merged if you're not confident with git - just make sure that the last commit contains the CoO signoff!

Recommended approach:

1. update libunwind dependency / USE
2. run `git add .`
3. run `pkgdev commit` (make sure that you've got the options for pkgdev and portage set as per the previous comment and it'll automatically add the CoO signoff)
4. push your commits so that you have a copy stashed on GitHub just in case: `git push`
5. run `git rebase -i HEAD~3` - this will ask you some questions about your commits - you want to 'squash' the second and third commit into the first commit (this basically means combine all of the changes into one commit and rewrite the history)
6. When you're happy with that, run `git push --force-with-lease` to forcibly push your new consolidated commit over the top of the previous commits.

A reasonable resource on git rebasing and squashing commits can be found [here](https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec).

Again, if you're not comfortable doing this, please just use `pkgdev` to create the third commit and add the CoO signoff and we can take care of it when merging your changes.

**Comment by dante-robinson** [comment]
> You'll also need to request a re-scan by appending `[please reassign]` to your PR title so that the bot knows to remove the `no-signoff` label.

This looks good now.

> The order of files in the Manifest has changed but that's not a big deal - the issue was only that files other than source archives were in the Manifest.

I used ebuild originally to make the manifest not sure what the difference is there but I do see when using pkgdev it removes the .ebuild from the mainfest. Different use case I guess.

> The `llvm-libunwind` global USE flag controls which implementation of libunwind your system uses; you can only have one available at a time, see: [useflags/llvm-libunwind](https://packages.gentoo.org/useflags/llvm-libunwind)
> 
> We need to provide the ability to build the package with either flavour of libunwind, so the ebuild needs to look more like:
> 
> ```diff
> # AIX ppc/ppc64
>  KEYWORDS="-* ~amd64 ~arm ~arm64 ~ppc ~ppc64 ~riscv ~x86 ~amd64-linux ~x86-linux"
>  
> -IUSE="largepages largepages64k +debug minimal optimisememory test static-libs"
> +IUSE="largepages largepages64k +debug llvm-libunwind minimal optimisememory test static-libs"
>  
>  RESTRICT="!test? ( test )"
>  
> - # TODO: remove the riscv special case once either libunwind has begun supporting this arch
> - # or this package allows using llvm-libunwind for other arches
> -DEPEND="!ppc64? (
> -       riscv? ( sys-libs/llvm-libunwind:= )
> -)"
> +DEPEND="
> +       llvm-libunwind? ( sys-libs/llvm-libunwind:= )
> +       !llvm-libunwind? ( sys-libs/libunwind:= )
> +"
>  RDEPEND="${DEPEND}"
>  
>  S="${WORKDIR}/${MY_P}"
> ```

I was thinking of something along the lines of libunwind || llvm-libunwind under depend, I understand how this works though.

> No news is good news! Might be worth asking for the output to be more `repoman`-like though - it positively confirms that no issues were detected.

Not sure what you mean here.

> Once you've amended the two packages, it would be ideal to 'squash' the three commits down to one, although this can be done when the package is merged if you're not confident with git - just make sure that the last commit contains the CoO signoff!
> 
> Recommended approach:
> 
> 1. update libunwind dependency / USE
> 
> 2. run `git add .`
> 
> 3. run `pkgdev commit` (make sure that you've got the options for pkgdev and portage set as per the previous comment and it'll automatically add the CoO signoff)
> 
> 4. push your commits so that you have a copy stashed on GitHub just in case: `git push`
> 
> 5. run `git rebase -i HEAD~3` - this will ask you some questions about your commits - you want to 'squash' the second and third commit into the first commit (this basically means combine all of the changes into one commit and rewrite the history)
> 
> 6. When you're happy with that, run `git push --force-with-lease` to forcibly push your new consolidated commit over the top of the previous commits.

I see your using pkgdev to make the commit I did not do this before which is probably why the commit message didn't have the signoff the 2nd time either. I think everything is good with the squash. When I did the rebase I used reword on the original commit to keep the fix of the original commit message and then did sqaush on the other 2 commits then I just used the 3rd commit message. Lemme know if this is ok. Thanks for the help so far!

**Comment by Kangie** [comment]
> I used ebuild originally to make the manifest not sure what the difference is there but I do see when using pkgdev it removes the .ebuild from the mainfest. Different use case I guess.

Thin vs thick [manifests](https://devmanual.gentoo.org/general-concepts/manifest/index.html). The tl;dr is that we only need to commit thin manifests here and thick manifests will be generated where they're needed. :)

> Not sure what you mean here.

`repoman` was the tool that we used before `pkgcheck` - it used positively affirm that no issues were detected while `pkgcheck`, as you've described, has no output for the "no issues" case.

> Lemme know if this is ok.

The squash (etc) looks good and I can't see any issues with the ebuild. Based on the changes made here I don't think that we'll need a `-r1` ebuild (it shouldn't impact existing users so no need to trigger a rebuild) - I could be wrong though.

Have you run the ebuild through its test phase?

`FEATURES="test" USE="test llvm-libunwind" ebuild ... clean test` and `FEATURES="test" USE="test -llvm-libunwind" ebuild ... clean test`

The second case *shouldn't* have any test failures, because it was the default before - you can use it to validate the results with llvm-unwind enabled. I don't expect that we'll uncover any issues, but if there are we can address them. :)

@thsamesam any thoughts on your part?

Thanks for your work here!

**Comment by dante-robinson** [comment]
> Have you run the ebuild through its test phase?
> 
> `FEATURES="test" USE="test llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`
> 
> and
> 
> `FEATURES="test" USE="test -llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`
> 
> The second case _shouldn't_ have any test failures, because it was the default before - you can use it to validate the results with `llvm-libunwind` enabled. I don't expect that we'll uncover any issues, but if there are we can address them. :)

I have test installed the package on my system using llvm-libunwind I did not know I could test the package without actually installing it. Running both of the commands provided returns with source compiled and then says "Unable to run tests when sandbox is enabled." it links to a bug but its from 2009 so I would assume the patch is already applied to the current version of sandbox in that bug report. The bug report can be found [here](https://bugs.gentoo.org/290249).

**Comment by Kangie** [comment]
I thought I finished replying to this one this morning!

That's correct - I noted the sandbox thing in the ebuild and forgot to adjust my instructions accordingly; sorry that one's one me!

Typically we don't want to let things run without the sandbox (and never want users to need to do so!) but we can disable that `FEATURE` for development purposes:

`FEATURES="-sandbox test" USE="test llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`

and

`FEATURES="-sandbox test" USE="test -llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`

will be more appropriate, in the case of this ebuild.

**Comment by dante-robinson** [comment]
> `FEATURES="-sandbox test" USE="test llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`
> 
> and
> 
> `FEATURES="-sandbox test" USE="test -llvm-libunwind" ebuild google-perftools-2.10.ebuild clean test`
> 
> will be more appropriate, in the case of this ebuild.

Both pass all 26 tests without issue. 

> Edit: You can also comment out the check in `src_test` and run with the sandbox enabled to see if the restriction there is still valid. I wouldn't be surprised if there are unexpected and unexplained test failures though! :)

Unsure how to do this sorry.

**Comment by Kangie** [comment]
> > Edit: You can also comment out the check in `src_test` and run with the sandbox enabled to see if the restriction there is still valid. I wouldn't be surprised if there are unexpected and unexplained test failures though! :)
> 
> Unsure how to do this sorry.

Don't worry about it for now, but for future reference, [this](https://github.com/gentoo/gentoo/pull/26885/files#diff-6ecf93ee2ce8049a83193b95e401fd09647de6bf1d9ac752495900b20d87f6fbL90) line is the conditional that checks for `FEATURES="sandbox"`, so commenting that whole conditional out would allow you to try with the sandbox enabled.

I'm not particularly concerned about the restriction - it seems sane, but we can verify that this sort of thing isn't just being restricted because it used to be required. :)

**Pull request closed without merging**
