### PR TITLE
dev-util/android-sdk-update-manager: switch to dev-java/ant

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
I can't test this, would you have an idea?
```
                ::::::::::::::::::::::::::::::::::::::::::::::

                ::          UNRESOLVED DEPENDENCIES         ::

                ::::::::::::::::::::::::::::::::::::::::::::::

                :: org.scala-sbt#sbt;0.13.18-r1: not found

                ::::::::::::::::::::::::::::::::::::::::::::::



:: USE VERBOSE OR DEBUG MESSAGE LEVEL FOR MORE DETAILS
unresolved dependency: org.scala-sbt#sbt;0.13.18-r1: not found
Error during sbt execution: Error retrieving required libraries
  (see /var/tmp/portage/dev-lang/scala-2.12.10/work/.sbt/boot/update.log for complete log)
Error: Could not retrieve sbt 0.13.18-r1
 * ERROR: dev-lang/scala-2.12.10::gentoo failed (compile phase):
 *   sbt compile failed
 * 
 * Call stack:
 *     ebuild.sh, line 136:  Called src_compile
 *   environment, line 2445:  Called die
 * The specific snippet of code:
 *           "${S}"/sbt -Dsbt.log.noformat=true compile || die "sbt compile failed";
```

**Comment by vaukai** [comment]
> I can't test this, would you have an idea?
> 
> ```
>                 ::::::::::::::::::::::::::::::::::::::::::::::
> 
>                 ::          UNRESOLVED DEPENDENCIES         ::
> 
>                 ::::::::::::::::::::::::::::::::::::::::::::::
> 
>                 :: org.scala-sbt#sbt;0.13.18-r1: not found
> 
>                 ::::::::::::::::::::::::::::::::::::::::::::::
> ```

Oops, does the presently stable version compile?

**Comment by vaukai** [comment]
@juippis Would you agree to last-riting `dev-lang/mozart{,-stdlib}`?

**Comment by juippis** [comment]
I don't personally mind at all, but is there a real reason to?

**Comment by vaukai** [comment]
> I don't personally mind at all, but is there a real reason to?

- Cannot be compiled due to broken `dev-lang/scala` (should imho also be last-rited in favour of `dev-lang/scala-bin`)
- Blocks last-riting [dev-java/ant-core](https://packages.gentoo.org/packages/dev-java/ant-core/reverse-dependencies) which is nothing but an ugly compatibility symlink.

Would be great if you could merge the remaining commit of this PR ( `dev-util/android-sdk-update-manager` ) and maybe also PR [35724.](https://github.com/gentoo/gentoo/pull/35724)

**Comment by juippis** [comment]
Could you rebase? This doesn't apply cleanly anymore:
https://gitweb.gentoo.org/repo/gentoo.git/log/dev-util/android-sdk-update-manager?showmsg=1

unfortunate timing. But I'll take a look asap.

**Review by juippis — APPROVED** [review]
I'll add some missing deps while at it, thanks!
```
 * QA Notice: Unresolved soname dependencies:
 * 
 *      /opt/android-sdk-update-manager/tools/lib/gles_mesa/libGL.so: libX11.so.6 libXdamage.so.1 libXext.so.6 libXfixes.so.3
 *      /opt/android-sdk-update-manager/tools/lib/gles_mesa/libGL.so.1: libX11.so.6 libXdamage.so.1 libXext.so.6 libXfixes.so.3
 *      /opt/android-sdk-update-manager/tools/lib/libEGL_translator.so: libX11.so.6
 *      /opt/android-sdk-update-manager/tools/lib/libOpenglRender.so: libX11.so.6
 *      /opt/android-sdk-update-manager/tools/lib/monitor-x86/libcairo-swt.so: libX11.so.6 libXrender.so.1 libfontconfig.so.1 libfreetype.so.6
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86/qemu-system-aarch64: libX11.so.6 libpulse.so.0
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86/qemu-system-mips64el: libX11.so.6 libpulse.so.0
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86/qemu-system-x86_64: libX11.so.6 libpulse.so.0
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86_64/qemu-system-aarch64: libpulse.so.0
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86_64/qemu-system-mips64el: libpulse.so.0
 *      /opt/android-sdk-update-manager/tools/qemu/linux-x86_64/qemu-system-x86_64: libpulse.so.0
```
```
 *                  > media-libs/fontconfig
 *                  > media-libs/freetype
 * dev-java/swt:3.7 < 
 *                  > x11-libs/libX11
 *                  > x11-libs/libXdamage
 *                  > x11-libs/libXext
 *                  > x11-libs/libXfixes
 *                  > x11-libs/libXrender
```

**Pull request closed without merging**
