### PR TITLE
www-apps/rutorrent: add 4.3.7

### PR DESCRIPTION
**Pull request by henning-schild**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by ceamac — APPROVED** [review]
Thanks!

**Comment by stickz** [comment]
@henning-schild @ceamac

1. ruTorrent version 5 is ready for deployment on Gentoo Linux. It's now one of the very few web interfaces for torrent clients, to offer native support for mobile devices! https://github.com/Novik/ruTorrent/releases/tag/v5.0.0

   - We added 1 external dependency. It's not required to use it: https://github.com/TheGoblinHero/dumptorrent
   - You can remove the following folder to drop it: https://github.com/Novik/ruTorrent/tree/master/plugins/dump

2. We will be offering long term support for `ruTorrent v4.3`. We would like to work with you to get this marked as stable on Gentoo Linux. We'll be backporting one stability change from version 5 and releasing `v4.3.8`. It's been 7 months since this minor was released. We're on track to release our 8th hotfix for this minor. 

   - The major has received over 40 bug fixes with 3 sets of minors released, to improve the performance and stability of the web client! We want to keep this legacy release around for a little while longer, while we polish all the CSS styles on version 5. We spent 2 years ironing out all the bugs. There was no such thing as hotfixes, before I took over project management! It would be a mistake to drop support for `ruTorrent v4.3` now. This is a stability milestone!

   - Our userbase now exceeds over ten thousand outside of Linux. We've got this minor onto three large hosting providers with thousands of customers. There are thousands more users across various installation scripts, docker containers and Linux distributions. Our GitHub is no longer being flooded with issue reports, even with an exponential increase in users.

**Comment by henning-schild** [comment]
@stickz i saw it

and i tried rc3 a few days ago, also looking at the changelog

i might give it some time, gentoo users can already install it via the -9999 ebuild using latest git

**Comment by stickz** [comment]
@henning-schild We thoroughly tested 3 times leading up to rc3. We have 5.0.1 coming with minor style fixes, but we have yet to find anther major or breaking with version 5. There's a few hundred people using it right now. Next week there will be thousands.

**Pull request closed without merging**
