### PR TITLE
Bump corosync and pacemaker + (new) dependencies

### PR DESCRIPTION
**Pull request by BtbN**
Both corosync and pacemaker version in portage are affected by various CVEs and are just generally quite old.
This bumps their needed dependencies, adds a new dependency and finally bumps the two packages and fixes a bunch of QA issues while at it, plus bumping all of those ebuilds to EAPI 7.

### CODE REVIEW

**Comment by thesamesam** [comment]
Some notes:
- Build fixes don't require a revbump usually (see [here](https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html))
- Normally, we do one package-per-PR. That'd be appreciated if you could do it, but it's not a complete requirement here given at least some of them are inter-linked/dependent.

Thanks for the work!

**Comment by BtbN** [comment]
It's pretty much one big chain of dependencies from pacemaker, all the way down to cluster-glue and resource-agents.

**Comment by ultrabug** [comment]
```
Applying: sys-cluster/libqb: bump for 2.0.0
error: patch failed: sys-cluster/libqb/Manifest:2
error: sys-cluster/libqb/Manifest: patch does not apply
Patch failed at 0001 sys-cluster/libqb: bump for 2.0.0
```

Could you rebase @BtbN please?

Also, can you remove all reference to **sys-cluster/heartbeat** since it's been removed from tree?

I'll get this in right after this, I promise

**Comment by ultrabug** [comment]
Thank you so much @BtbN

**Pull request closed without merging**
