### PR TITLE
dev-python/pivy: bump to 0.6.7

### PR DESCRIPTION
**Pull request by waebbl**
Add py3_11 support, enabling tests

Closes: https://bugs.gentoo.org/849746
Bug: https://bugs.gentoo.org/835724
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
i have already tried to bump it, but i have some issue with compiling it. i have the same issue with the current version too though:
```
# PORTDIR=/usr/src/gentoo.git/ emerge -va1 pivy

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild     U  ] dev-python/pivy-0.6.7::gentoo [0.6.6-r1::gentoo] USE="quarter -soqt -test%" PYTHON_TARGETS="python3_8 python3_9 python3_10%* -python3_11%" 0 KiB

Total: 1 package (1 upgrade), Size of downloads: 0 KiB

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-python/pivy-0.6.7::gentoo
 * pivy-0.6.7.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                       [ ok ]
>>> Unpacking source...
>>> Unpacking pivy-0.6.7.tar.gz to /var/tmp/portage/dev-python/pivy-0.6.7/work
>>> Source unpacked in /var/tmp/portage/dev-python/pivy-0.6.7/work
>>> Preparing source in /var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7 ...
 * Applying pivy-0.6.6-0001-fix-CMakeLists.txt-for-distutils_cmake.patch ...                                                                                                           [ ok ]
 * Applying pivy-0.6.6-0002-Gentoo-specific-clear-swig-deprecation-warning.patch ...                                                                                                   [ ok ]
 * Build system packages:
 *   dev-python/gpep517            : 6-r1
 *   dev-python/installer          : 0.5.1-r1
 *   dev-python/setuptools         : 62.3.3
 *   dev-python/setuptools_scm     : 6.4.2
 *   dev-python/wheel              : 0.37.1-r1
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7 ...
 * python3_8: running distutils-r1_run_phase distutils-r1_python_compile
python3.8 setup.py build_ext -j 17
Oooh, it's a Gentoo! Nice nice! tuhtah salutes you! :)
running build_ext
 *   Building the wheel for pivy-0.6.7 via setuptools.build_meta:__legacy__
Oooh, it's a Gentoo! Nice nice! tuhtah salutes you! :)
running bdist_wheel
running build
Traceback (most recent call last):
  File "setup.py", line 237, in check_with_cmake
    self.QTINFO = qtinfo.QtInfo()
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 14, in __init__
    getattr(self, thing)
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 23, in getVersion
    return self.getProperty("QT_VERSION")
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 68, in getProperty
    self._dict[prop_name] = self._getProperty(prop_name)
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 57, in _getProperty
    proc = subprocess.Popen(cmd, stdout = subprocess.PIPE, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

                            _____
                        .-'`     '.                                     
                     __/  __       \                                   
                    /  \ /  \       |    ___                          
                   | /`\| /`\|      | .-'  /^\/^\                   
                   | \(/| \(/|      |/     |) |)|                     
                  .-\__/ \__/       |      \_/\_/__..._             
          _...---'-.                /   _              '.               
         /,      ,             \   '|  `\                \           
        | ))     ))           /`|   \    `.       /)  /) |             
        | `      `          .'       |     `-._         /               
        \                 .'         |     ,_  `--....-'               
         `.           __.' ,         |     / /`'''`                     
           `'-.____.-' /  /,         |    / /                           
               `. `-.-` .'  \        /   / |                           
                 `-.__.'|    \      |   |  |-.                         
                    _.._|     |     /   |  |  `'.                       
              .-''``    |     |     |   /  |     `-.                    
           .'`         /      /     /  |   |        '.                  
         /`           /      /     |   /   |\         \               
        /            |      |      |   |   /\          |               
       ||            |      /      |   /     '.        |                
       |\            \      |      /   |       '.      /              
       \ `.           '.    /      |    \        '---'/               
        \  '.           `-./        \    '.          /                
         '.  `'.            `-._     '.__  '-._____.'--'''''--.         
           '-.  `'--._          `.__     `';----`              \       
              `-.     `-.          `.''```                     ;        
                 `'-..,_ `-.         `'-.                     /         
                        '.  '.           '.                 .'          


                            ~~~ HISSSSSSSSSS ~~~
                           Welcome to Pivy 0.6.7!
                 Building Pivy has never been so much fun!

    
Platform...linux
Python version...3.8.13
Checking for swig...
'/usr/bin/swig'
Checking for SWIG version...
4.0.2
Warning: Pivy has only been tested with the following SWIG versions: 3.0.8 3.0.10 3.0.12 4.0.0.
calling: cmake distutils_cmake
-- The C compiler identification is GNU 11.3.0
-- The CXX compiler identification is GNU 11.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/x86_64-pc-linux-gnu-g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- COIN_FOUND: TRUE
-- COIN_INCLUDE_DIR: /usr/include
-- COIN_LIB_DIR: /usr/lib64
-- COIN_VERSION: 4.0.0
-- SOQT_FOUND: True
-- SOQT_INCLUDE_DIR: /usr/include;/usr/include
-- SOQT_LIB_DIR: /usr/lib64
-- SOQT_VERSION: 1.6.0
-- Configuring done
-- Generating done
-- Build files have been written to: /var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7



checking for COIN via cmake
COIN_FOUND: TRUE
COIN_VERSION: 4.0.0
COIN_INCLUDE_DIR: /usr/include
COIN_LIB_DIR: /usr/lib64

checking for SOQT via cmake
SOQT_FOUND: True
SOQT_VERSION: 1.6.0
SOQT_INCLUDE_DIR: /usr/include" -I"/usr/include
SOQT_LIB_DIR: /usr/lib64

disable soqt, because there was a problem running qtinfo (needs qmake)
------------------------------------------------------------
Traceback (most recent call last):
  File "setup.py", line 237, in check_with_cmake
    self.QTINFO = qtinfo.QtInfo()
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 14, in __init__
    getattr(self, thing)
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 23, in getVersion
    return self.getProperty("QT_VERSION")
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 68, in getProperty
    self._dict[prop_name] = self._getProperty(prop_name)
  File "/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7/qtinfo.py", line 57, in _getProperty
    proc = subprocess.Popen(cmd, stdout = subprocess.PIPE, shell=False)
  File "/usr/lib/python3.8/subprocess.py", line 858, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.8/subprocess.py", line 1585, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.8/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/gpep517", line 4, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 191, in main
    return func(args)
  File "/usr/lib/python3.8/site-packages/gpep517/__main__.py", line 87, in build_wheel
    wheel_name = backend.build_wheel(args.wheel_dir, args.config_json)
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 244, in build_wheel
    return self._build_with_temp_dir(['bdist_wheel'], '.whl',
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 229, in _build_with_temp_dir
    self.run_setup()
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 281, in run_setup
    super(_BuildMetaLegacyBackend,
  File "/usr/lib/python3.8/site-packages/setuptools/build_meta.py", line 174, in run_setup
    exec(compile(code, __file__, 'exec'), locals())
  File "setup.py", line 669, in <module>
    setup(name="Pivy",
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 148, in setup
    return run_commands(dist)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
    dist.run_commands()
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 299, in run
    self.run_command('build')
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/dist.py", line 1229, in run_command
    super().run_command(command)
  File "/usr/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
    cmd_obj.run()
  File "setup.py", line 607, in run
    self.pivy_configure()
  File "setup.py", line 463, in pivy_configure
    self.check_with_cmake()
  File "setup.py", line 242, in check_with_cmake
    print(red(traceback.print_exc()))
  File "/usr/lib/python3.8/site-packages/portage/output.py", line 437, in __call__
    return colorize(self._color_key, text)
  File "/usr/lib/python3.8/site-packages/portage/output.py", line 404, in colorize
    return codes[color_key] + text + codes["reset"]
TypeError: can only concatenate str (not "NoneType") to str
 * ERROR: dev-python/pivy-0.6.7::gentoo failed (compile phase):
 *   Wheel build failed
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_compile
 *   environment, line 3339:  Called distutils-r1_src_compile
 *   environment, line 1594:  Called _distutils-r1_run_foreach_impl 'distutils-r1_python_compile'
 *   environment, line  736:  Called python_foreach_impl 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 3028:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2603:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 2601:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'distutils-r1_python_compile'
 *   environment, line 1078:  Called distutils-r1_run_phase 'distutils-r1_python_compile'
 *   environment, line 1576:  Called distutils-r1_python_compile
 *   environment, line 1412:  Called distutils_pep517_install '/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7-python3_8/install'
 *   environment, line 1899:  Called die
 * The specific snippet of code:
 *       einfo "  Installing the wheel to ${root}";
 * 
 * If you need support, post the output of `emerge --info '=dev-python/pivy-0.6.7::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/pivy-0.6.7::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-python/pivy-0.6.7/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/pivy-0.6.7/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7'
 * S: '/var/tmp/portage/dev-python/pivy-0.6.7/work/pivy-0.6.7'
```

**Comment by waebbl** [comment]
@fordfrog I think I found the issue. This is probably due to `qtinfo.py` calling `qmake` instead of `qmake5`. The issue also only appears if `media-libs/SoQt` happens to be installed, no matter if `USE=soqt` is used or `USE=-soqt`. If this package isn't present the package builds without issues for me.

Could you try if applying the following patch manually works for you? I'm gonna update the PR then.

```
diff --git a/qtinfo.py b/qtinfo.py
index 49b03b4..2aa5eda 100644
--- a/qtinfo.py
+++ b/qtinfo.py
@@ -7,7 +7,7 @@ class QtInfo(object):
         if qmake_command:
             self._qmake_command = qmake_command
         else:
-            self._qmake_command = [find_executable("qmake"),]
+            self._qmake_command = [find_executable("qmake5"),]
         self._dict = {}
         # bind all variables early at __init__ time.
         for thing in self.__class__.__dict__:
@@ -79,4 +79,4 @@ class QtInfo(object):
     translations_dir = property(getTranslationsPath)
     headers_dir = property(getHeadersPath)
     docs_dir = property(getDocsPath)
-    qml_dir = property(getQmlPath)
\ No newline at end of file
+    qml_dir = property(getQmlPath)
-- 
2.35.1
```

**Comment by fordfrog** [comment]
@waebbl cool, with the patch the package merges fine, thanks!

**Comment by fordfrog** [comment]
@waebbl thanks for the fix. i merged it. wrt the bug for 0.6.6, lets keep it as it is, it'll be gone after this version is stable. thank you!

**Comment by waebbl** [comment]
Thanks for merging @fordfrog

**Pull request closed without merging**
