### PR TITLE
app-misc/khard-0.16.1: bump

### PR DESCRIPTION
**Pull request by Hawk777**

### CODE REVIEW

**Comment by thesamesam** [comment]
I would suggest trying in a chroot as it won't be easy for you to do this until very close to, or after, the change (which you need to be ready for as a maintainer) on a stable system otherwise.

**Comment by thesamesam** [comment]
I would suggest trying in a chroot as it won't be easy for you to do this until very close to, or after, the change (which you need to be ready for as a maintainer) on a stable system otherwise.

**Comment by Hawk777** [comment]
I suppose I might try 3.8 in a chroot some day, if I find time to create one. It’s not something I just have lying around. I’m not the maintainer though, to clarify, just an ordinary user of this package, who submitted this PR because my usual weekly update fell over.

**Comment by epsilon-0** [comment]
@Hawk777 I've noticed that you have a few version bump PR.  
Maybe it might be good to ping the maintainer separately as these are going to give CI errors on old EAPI problems.

**Comment by Hawk777** [comment]
> @Hawk777 I've noticed that you have a few version bump PR.
> Maybe it might be good to ping the maintainer separately as these are going to give CI errors on old EAPI problems.

I’m not sure what you mean there @epsilon-0 ; on the Radicale PR your review said I should bump to EAPI 7 myself, so if I did that, why would there be CI errors?

**Comment by epsilon-0** [comment]
I take back that statement. I meant something totally different, sorry for being vague.  
Manually adding setuptools and the other dependencies is not something you want to do in EAPI 7:https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/distutils-r1.eclass

**Comment by Hawk777** [comment]
55d8aeb258894dac72718ab07bb61557b8ccd27a adds a call to `distutils_enable_tests` (and, accordingly, removes `test` from `IUSE`, deletes the `RESTRICT` line, and deletes the `test?` block from `DEPEND`), and deletes the `DEPEND` on `dev-python/setuptools` (it should have been an `RDEPEND` because `entry_points` is used).

I’m not sure what you mean by “Manually adding setuptools *and the other dependencies*”. Did you just mean `dev-python/setuptools` and the `test?` block? I don’t see anything in the `distutils-r1.eclass` man page about how an eclass-provided way to depend on other random packages (or even `setuptools_scm` for that matter); I thought those were still supposed to be added to the appropriate variable by hand.

**Comment by Hawk777** [comment]
@epsilon-0 anything further you’d like changed here?

**Comment by epsilon-0** [comment]
Looks okay to me. Will ping it to the devs so they can take a look.

**Comment by Hawk777** [comment]
e15f8559f064d5216fa02da87206a58b95a48657 is a rebase and includes 3.8 as well as 3.7.

**Comment by holgersson32644** [comment]
Hi, I still like to take over maintenance and added support for python 3.9 aswell, but did so in a separate PR #17128. So I'd like to ask you to just close yours here. Again, sorry for the long delay and thanks for you efforts!

**Comment by Hawk777** [comment]
> Hi, I still like to take over maintenance and added support for python 3.9 aswell, but did so in a separate PR #17128. So I'd like to ask you to just close yours here. Again, sorry for the long delay and thanks for you efforts!

Glad to hear it. Hopefully your PR gets merged a bit faster than mine :)

**Pull request closed without merging**
