### PR TITLE
dev-libs/{libbson,mongo-c-driver}: bump to 1.9.3

### PR DESCRIPTION
**Pull request by hydrapolic**
Also cleaning ancient versions :) Thank you!

### CODE REVIEW

**Comment by hydrapolic** [comment]
@ultrabug, can you please check it? Thank you :)

**Comment by hydrapolic** [comment]
Dropping old versions is not possible at the moment: https://bugs.gentoo.org/518624

**Comment by ultrabug** [comment]
:+1: as usual mate

**Comment by hydrapolic** [comment]
Thanks! :)

**Pull request closed without merging**
