### PR TITLE
dev-lang/python + eclass build fixes

### PR DESCRIPTION
**Pull request by mgorny**
Probably the cleanest solution possible.

### CODE REVIEW

**Comment by mgorny** [comment]
The idea is that `python_export` -- similarly to other eclass functions -- respects `PYTHON` if it's already set, and sets it if requested, respecting request order. If in any case `PYTHON` ends up being unset at time of sitedir getting or alike, it simply errors out.

Appropriately, the ebuilds set `PYTHON` in non-cross-compile case or request it in cross-compile case. Afterwards, they request `EPYTHON` and `PYTHON_SITEDIR`, so `PYTHON` is always either set by ebuild or by eclass.

I've also removed redundant ebuilds and added missing `||die`. What do we want to do about ol' ebuilds that have some extra stable keywords?

```
Keywords for dev-lang/python:
                |                                 | u          |  
                | a a   a         n   p r     s   | n          |  
                | l m   r h i m m i   p i s   p   | u s        | r
                | p d a m p a 6 i o p c s 3   a x | s l        | e
                | h 6 r 6 p 6 8 p s p 6 c 9 s r 8 | e o        | p
                | a 4 m 4 a 4 k s 2 c 4 v 0 h c 6 | d t        | o
----------------+---------------------------------+------------+-------
       2.7.9-r1 | + + + + + + + ~ o + + o + + + + | o 2.7      | gentoo
      2.7.10    | ~ + + ~ + + ~ ~ o + + o ~ ~ + + | o          | gentoo
      2.7.10-r2 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o          | gentoo
[M][I]2.7.10-r3 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o          | gentoo
----------------+---------------------------------+------------+-------
       3.3.5-r1 | + + + + + + + ~ o + + o + + + + | o 3.3      | gentoo
    [I]3.3.5-r2 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o          | gentoo
----------------+---------------------------------+------------+-------
    [M]3.3.5-r3 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o 3.3/3.3m | gentoo
----------------+---------------------------------+------------+-------
       3.4.1    | + + + + + + + ~ o + + o + + + + | o 3.4      | gentoo
       3.4.3    | + + + ~ + + ~ ~ o + + o ~ ~ + + | o          | gentoo
       3.4.3-r2 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o          | gentoo
----------------+---------------------------------+------------+-------
 [M][I]3.4.3-r3 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o 3.4/3.4m | gentoo
----------------+---------------------------------+------------+-------
       3.5.0-r1 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o 3.5      | gentoo
----------------+---------------------------------+------------+-------
 [M][I]3.5.0-r2 | ~ ~ ~ ~ ~ ~ ~ ~ o ~ ~ o ~ ~ ~ ~ | o 3.5/3.5m | gentoo

**Comment by jlec** [comment]
Looks good to me.

**Comment by mgorny** [comment]
Added pypy & jython fixes.

**Comment by mgorny** [comment]
PyPy fix is broken since it returns full prefix path, including `${ED}`. Stupid PyPy.

**Comment by mgorny** [comment]
And Jython does some random accesses to target paths which are not installed…

**Comment by mgorny** [comment]
Now with correct pypy&jython fixes. Which kinda leaves CPython the only thing getting sitedir from just-built executable.

**Comment by mgorny** [comment]
Pushed.

**Pull request closed without merging**
