### PR TITLE
media-print/: new category

### PR DESCRIPTION
**Pull request by scardracs**
As suggested by @thesamesam, I've also opened a thread on gentoo-dev mailing-list: https://archives.gentoo.org/gentoo-dev/message/7c35c1084cbf869493151ffad6936642

net-print is not the right place where to put these packages. Creating a new media-print category makes things much better and can be used for other printer-related packages as well. See following bug and related mailing-list.

Bug: https://bugs.gentoo.org/829351

Signed-off-by: Marco Scardovi <mscardovi@icloud.com>

### CODE REVIEW

**Comment by scardracs** [comment]
@mpagano, @akhuettel is it ok for you?

**Comment by thesamesam** [comment]
1. See https://devmanual.gentoo.org/profiles/categories/index.html. Needs to be posted to gentoo-dev ML.
2. Normally a new category would have more than 2 ebuilds...?

**Comment by scardracs** [comment]
> 1. See https://devmanual.gentoo.org/profiles/categories/index.html. Needs to be posted to gentoo-dev ML.
> 
> 2. Normally a new category would have more than 2 ebuilds...?

About 2nd point that's a start. I'm looking to move others as well. About the 1st you are right, I'd have to figure it out too. Do you think that thing could be done in short time? Because I saw that was proposed a year ago and still not done

**Comment by mpagano** [comment]
Ok from me

**Comment by scardracs** [comment]
pappl will be added in another PR. This one will be specific only for creating the new media-print/ category and start to move things inside it

**Comment by scardracs** [comment]
I don't really want to touch these old packages, if possible. I'd prefer to stable new one and drop them

**Comment by scardracs** [comment]
foomatic-db will be moved in a 2nd moment

**Comment by scardracs** [comment]
Feel free to do it by yourself.

**Pull request closed without merging**
