### PR TITLE
dev-python/awscli: version bump including dependency botocore

### PR DESCRIPTION
**Pull request by neurolabs**
version bump on botocore necessary.

### CODE REVIEW

**Comment by mgorny** [comment]
@neurolabs, Patrick is a known GitHub hater, so I'm afraid you'd have to go through Bugzilla for the awscli thing.

**Comment by neurolabs** [comment]
@mgorny thanks for the comment. Too bad. Would have been so easy and collaborative ;)

What about botocore? You probably can't say, can you?

**Comment by neurolabs** [comment]
@mgorny regarding going through bugzilla: https://bugs.gentoo.org/show_bug.cgi?id=604728 - been there, added the important part (upgrading the colorama dependency). Back in January. Hopefully patrick will pick it up.

**Comment by neurolabs** [comment]
@mgorny attached the 1.11.82 ebuild to the issue. Would you be so kind and update the issue title? Thanks a bunch.

**Comment by neurolabs** [comment]
This pull request seems obsolete. botocore 1.5.52 is in the official tree, and no response to the issue in the tracker. My hope is fading. Thanks @mgorny for trying.

**Pull request closed without merging**
