### PR TITLE
virtual/rust: Drop 1.68.2 and 1.71.0

### PR DESCRIPTION
**Pull request by bowlofeggs**

### CODE REVIEW

**Comment by mattst88** [comment]
The reason I didn't drop 1.71 was because of mips -- see https://github.com/gentoo/gentoo/pull/34990#issuecomment-1917187770

Has something changed? I see https://github.com/gentoo/gentoo/pull/35314 is still open.

**Comment by bowlofeggs** [comment]
@thesamesam, do we have MIPS for 1.71.1? I don't see a difference between 1.71.0 and 1.71.1 in `dev-lang/rust`.

**Comment by thesamesam** [comment]
Look at dev-lang/rust-bin. Anyway, I've had no time to rebuild the binaries using matoro's instructions yet.

**Comment by Jamim** [comment]
_Hello everyone,_

Thanks to @arthurzam, we now have `~mips` in the KEYWORDS for [rust-bin-1.77.1](https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-lang/rust-bin/rust-bin-1.77.1.ebuild?id=16737d9c012bec2183b055e119ea1df0fda41344), so I believe these changes might be accepted once conflicts are resolved.

@bowlofeggs by the way, do you have any plans on submitting a PR for [Rust 1.78.0](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html)?

**Comment by bowlofeggs** [comment]
> @bowlofeggs by the way, do you have any plans on submitting a PR for [Rust 1.78.0](https://blog.rust-lang.org/2024/05/02/Rust-1.78.0.html)?

I think our friend @navi-desu might be working on that soon.

**Comment by arthurzam** [comment]
@mattst88 @thesamesam Do you think we can drop those rust versions now? We now have quite a good record on mips

**Pull request closed without merging**
