### PR TITLE
sci-physics/vgm: Bump to version 4.9.

### PR DESCRIPTION
**Pull request by olifre**
This also fixes issues with the test suite in the live ebuild.

### CODE REVIEW

**Comment by olifre** [comment]
Rebased and force-pushed, seems I hit the middle of a platform removal....

**Review by juippis — APPROVED** [review]

**Comment by amadio** [comment]
Thanks for the help with these, @juippis!

**Comment by juippis** [comment]
Thanks @olifre for contributions :)

**Comment by olifre** [comment]
And thanks to both of you for the reviews and merging :+1: . Special thanks to @juippis for the additional improvements commited to the `ebuild`s, I'll make sure to learn from these for future contributions :smile:.

**Pull request closed without merging**
