### PR TITLE
dev-util/conan: remove old broken version

### PR DESCRIPTION
**Pull request by winterheart**
Fix #675626

Closes: https://bugs.gentoo.org/675626
Signed-off-by: Azamat H. Hackimov <azamat.hackimov@gmail.com>
Package-Manager: Portage-2.3.66, Repoman-2.3.16

### CODE REVIEW

**Comment by winterheart** [comment]
So I need to wipe out mirrored conan-1.18.1.tar.gz from gentoo mirrors or else we'll get checksum mismatch.

**Comment by mgorny** [comment]
> So I need to wipe out mirrored conan-1.18.1.tar.gz from gentoo mirrors or else we'll get checksum mismatch.

Just rename it, e.g. to `${PN}.gh.tar.gz`

**Comment by winterheart** [comment]
I decided to fix 692036 in another pr with major version bump.

**Comment by winterheart** [comment]
@mgorny ping?

**Comment by juippis** [comment]
Thanks.

**Pull request closed without merging**
