### PR TITLE
net-im/mcabber: Add -9999 ebuild

### PR DESCRIPTION
**Pull request by andrey-utkin**

### CODE REVIEW

**Comment by kensington** [comment]
@wschlich @gentoochainsaw @mrueg

**Comment by andrey-utkin** [comment]
Could masking ppc arch help?

**Comment by mgorny** [comment]
@andrey-utkin, please disregard that check, it's underlying Gentoo tree being broken.

**Comment by andrey-utkin** [comment]
@mgorny so what is our next step?

**Comment by mgorny** [comment]
We wait some more hoping that package maintainers may reply one day. I'll try to bring their attention here.

**Comment by andrey-utkin** [comment]
```
9999	MissingSlotDep	'sys-libs/ncurses' matches more than one slot: [ 0, 5 ]
```
Ebuild excerpt:
```
RDEPEND="...
	sys-libs/ncurses
...
```

What is supposed to be a fix? Any help?

**Comment by kensington** [comment]
This warning occurs because sys-libs/ncurses has multiple slots, and the ebuild does not specify which (if any) is required.

Slot 5 is library only (no headers, for binary packages), so you want slot 0. Also consider using the slot dependency operator to trigger a rebuild when ABI breaks.

I would therefore suggest ```sys-libs/ncurses:0=```.

**Comment by andrey-utkin** [comment]
@kensington thanks for guidance (although the explanation is still cryptic), all checks have passed!

**Comment by kensington** [comment]
Binary packages in the tree are linked against specific versions of libraries, such as libncurses.so.5. When ncurses upstream makes breaking changes, they bump the soversion resulting in libraries like libncurses.so.6. Upgrading to the newer ncurses will break these binary packages since  libncurses.so.5 is no longer present - but we also don't want to be stuck with an ancient ncurses forever.

The solution in Gentoo is to have multiple slots. Slot 0 is the normal package you can build against - with headers, libraries, and everything else installed. Slot 5 installs just the library that a binary package would need - and everything else is thrown away. If the ebuild did not specify which slot it needs, there could be a build failure if the package needs to build against ncurses, but the wrong slot is installed.

Of course, different packages use slots in different ways so the above is only true for certain packages like ncurses, libpng etc. If in doubt, it's best to ask or test which is the correct slot or operator to specify - in the main tree there is already a lot of bogus dependencies because a random operator was added just to shut up the warning.

**Comment by andrey-utkin** [comment]
Thanks. I am aware about slots concept, just "slot 0" semantics, and ```library only (no headers, for binary packages)``` moment were unknown to me. I don't ask for further explanations though :)

**Comment by wschlich** [comment]
I've modified your ebuild (so it doesn't differ from the release ebuild too much) and committed it directly:
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c8f77c70cf139c7b197803f9c9cdfa72962b5bdc
Thanks for the pull-request!

**Comment by andrey-utkin** [comment]
The only change I see is `cd ${PN}` and `doins "${S}"` -> `doins "${S}/${PN}"`, is that all? It's a bit pity that my name is completely not mentioned.

While you are at editing it, I'd suggest to drop also lines 11-12, it mentions commit id from the oldest ebuild.

**Comment by monsieurp** [comment]
@wschlich Please keep the commit authorship if possible next time i.e. merge the author's commit and then clean it up / fix mistakes with another commit (yours). Credit must be given when and where it's due.

**Comment by wschlich** [comment]
@andrey-utkin : No, it's not all. Please take a diff between your ebuild and mine :) I've mentioned you now in another commit, though ;)
@monsieurp: Okay.

**Pull request closed without merging**
