### PR TITLE
media-fonts/source-han-sans: version bump to 1.004

### PR DESCRIPTION
**Pull request by lluixhi**
Gentoo-Bug: https://bugs.gentoo.org/587074

### CODE REVIEW

**Comment by lluixhi** [comment]
@ulm @monsieurp

**Comment by lluixhi** [comment]
Does this package have a maintainer?

**Comment by mgorny** [comment]
It's the fonts project which is kinda low-throughput right now, to say lightly. If you'd like to co-maintain this, please by all means add yourself.

**Comment by lluixhi** [comment]
Alright, added myself.

**Pull request closed without merging**
