### PR TITLE
lxde-base/lxappearance: Add ~ppc64 keyword

### PR DESCRIPTION
**Pull request by djames1**

### CODE REVIEW

**Comment by juippis** [comment]
Hey, we can't do that here. KEYWORDS are requested through bugzilla, check examples here:
https://bugs.gentoo.org/buglist.cgi?component=Keywording&list_id=4762706&product=Gentoo%20Linux&resolution=---

Also whenever contributing something to our portage tree, we need a proper sign-off line to the commit. Check the linked note about it above.

If you need help getting started with keywording in bugzilla, don't hesitate to ask.

**Comment by djames1** [comment]
@gyakovlev on #gentoo-powerpc IRC you told me you can merge pull requests to add KEYWORDS. Is this not correct?

**Comment by juippis** [comment]
@gyakovlev is indeed part of the ppc arch team. If you have come to a mutual agreement, please state it in the PR's opening message, since this is an unconvential way of adding KEYWORDS. You probably weren't aware, just like I wasn't aware of your deal with @gyakovlev ;) 

Please highlight me and @gyakovlev in the 2nd PR you had so it can reopened it again.

**Comment by juippis** [comment]
Note that you still need to amend your commit and add a proper sign-off, but it can be done now that this PR is reopened.

**Comment by gyakovlev** [comment]
Yes, I offered to merge keywording PRs (with ppc64 hat on), so I'll handle it later today in bulk.

**Comment by gyakovlev** [comment]
this PR was not signed-off, so I just keyworded it myself, as I actually use this app.

**Pull request closed without merging**
