### PR TITLE
www-servers/nginx: version bump to 1.9.13

### PR DESCRIPTION
**Pull request by jbergstroem**
Update 3rd party modules:
 - lua
 - modsecurity

Upstream changes: http://nginx.org/en/CHANGES

/cc=@mrueg, @gentoo/proxy-maint

### CODE REVIEW

**Comment by Whissi** [comment]
You forgot to bump *http_auth_pam* to v1.5 which contains a fix from Gentoo'ler @sbraz

**Comment by Whissi** [comment]
Also please revert the logrotate changes, see https://bugs.gentoo.org/show_bug.cgi?id=576558

**Comment by sbraz** [comment]
Not really my fix but I'd still like to see it added :) Thanks for pinging me, @Whissi!

**Comment by jbergstroem** [comment]
Ok; will have a look today.

**Pull request closed without merging**
