### PR TITLE
dev-python/clang-python, dev-util/perf, sys-apps/baselayout-java: add ~riscv keyword

### PR DESCRIPTION
**Pull request by caoye275**
Also add ~riscv keyword to related packages

### CODE REVIEW

**Comment by dlan17** [comment]
I've got this, I think we need to do more test for 
 dev-python/clang-python, sys-devel/clang-runtime, sys-libs/compiler-rt-sanitizers

either make sure the functionality work fine or mask those which still not work (haven't checked myself..)

# emerge -q1 clang-python

!!! The ebuild selected to satisfy "~sys-libs/compiler-rt-sanitizers-12.0.1:12.0.1" has unmet requirements.
- sys-libs/compiler-rt-sanitizers-12.0.1::gentoo USE="clang (-asan) (-cfi) (-dfsan) (-gwp-asan) (-hwasan) (-libfuzzer) (-lsan) (-memprof) (-msan) (-profile) (-safestack) (-scudo) (-shadowcallstack) -test (-tsan) (-ubsan) (-xray)"

  The following REQUIRED_USE flag constraints are unsatisfied:
    any-of ( asan dfsan lsan msan hwasan tsan ubsan safestack cfi scudo shadowcallstack gwp-asan libfuzzer profile xray )

  The above constraints are a subset of the following complete expression:
    any-of ( asan dfsan lsan msan hwasan tsan ubsan safestack cfi scudo shadowcallstack gwp-asan libfuzzer profile xray ) test? ( cfi? ( ubsan ) gwp-asan? ( scudo ) )

(dependency required by "sys-devel/clang-runtime-12.0.1::gentoo[compiler-rt,sanitize]" [ebuild])
(dependency required by "sys-devel/clang-12.0.1::gentoo" [ebuild])
(dependency required by "dev-python/clang-python-12.0.1::gentoo" [ebuild])
(dependency required by "clang-python" [argument])

**Comment by dlan17** [comment]
sys-devel/automake:1.9 has been masked, check
https://github.com/gentoo/gentoo/85fb9e060cbba2053036988833c2affc9bb6d454

**Comment by dlan17** [comment]
hi caoye
 I've partially pushed these commits (drop these: clang-python, automake, baselayout-java)
 I'd like to wait to keyword baselayout-java when we really come to support java in tree.
 thanks

**Comment by dlan17** [comment]
commit 310723717fdb3131ac2c9a05fc171b5b2e4b58a6 
Author: Ye Cao <ye.c@rioslab.org>
Date:   Sat Jul 31 21:43:28 2021 +0800

    dev-util/perf: add ~riscv keyword

    Package-Manager: Portage-3.0.18, Repoman-3.0.3
    Signed-off-by: Ye Cao <ye.c@rioslab.org>
    Signed-off-by: Yixun Lan <dlan@gentoo.org>

commit a612f6e430c2aa29e2cced42a9408143c671a91f
Author: Ye Cao <ye.c@rioslab.org>
Date:   Sat Jul 31 22:36:37 2021 +0800

    profiles/arch/riscv: Mask dev-util/perf[unwind]

    Signed-off-by: Ye Cao <ye.c@rioslab.org>
    Signed-off-by: Yixun Lan <dlan@gentoo.org>

commit 031b93d3c1c569c31e7e594206c065fd31d0acbb
Author: Ye Cao <ye.c@rioslab.org>
Date:   Sat Jul 31 21:26:57 2021 +0800

    dev-util/babeltrace: add ~riscv keyword

    Package-Manager: Portage-3.0.18, Repoman-3.0.3
    Signed-off-by: Ye Cao <ye.c@rioslab.org>
    Signed-off-by: Yixun Lan <dlan@gentoo.org>

commit 3ec8650ca0023576c9804003f35d3df78706a4fd
Author: Ye Cao <ye.c@rioslab.org>
Date:   Sat Jul 31 21:16:35 2021 +0800

    app-arch/gcab: add ~riscv keyword

    Package-Manager: Portage-3.0.18, Repoman-3.0.3
    Signed-off-by: Ye Cao <ye.c@rioslab.org>
    Signed-off-by: Yixun Lan <dlan@gentoo.org>

**Comment by caoye275** [comment]
> hi caoye
> I've partially pushed these commits (drop these: clang-python, automake, baselayout-java)
> I'd like to wait to keyword baselayout-java when we really come to support java in tree.
> thanks

Thanks for your reviewing. I'd check them again.

**Pull request closed without merging**
