### PR TITLE
dev-util/pycharm-community: version bump to 5.0.1

### PR DESCRIPTION
**Pull request by JiajunW**

### CODE REVIEW

**Comment by kensington** [comment]
@xmw

**Comment by monsieurp** [comment]
@xmw doesn't seem to be active on Github. I even sent him an email to have him look at PR but no chance either. :/

**Comment by JiajunW** [comment]
I have also submit the PR #395 to update dev-util/pycharm-professional several days ago, which is merge automatically by @gentoo-bot (while @xmw is the maintainer). I wonder under what circumstances will the bot merge a PR?

**Comment by mgorny** [comment]
@JiajunW, it's just github stupidity attributing commits to random github account performing the push. The bot is a machine account used to push changes from git.gentoo.org to github mirror.

**Pull request merged**
