### PR TITLE
dev-python/shiboken2 dev-python/pyside2 dev-python/pyside2-tools - bump to 5.15.5

### PR DESCRIPTION
**Pull request by waebbl**
An attempt for a bump of the packages. There's probably still some love missing for the packages.
I can think of co-maintaining the packages, but I don't have the resources for primary maintaining them.

Closes: https://bugs.gentoo.org/835763
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
For some reason I'm getting a bunch of confusing sandbox violations when compiling shiboken2:
```
>>> Source compiled.
* ----------------------- SANDBOX ACCESS VIOLATION SUMMARY -----------------------
* LOG FILE: "/var/tmp/portage/dev-python/shiboken2-5.15.5/temp/sandbox.log"
* 
VERSION 1.0
FORMAT: F - Function called
FORMAT: S - Access Status
FORMAT: P - Path as passed to function
FORMAT: A - Absolute Path (not canonical)
FORMAT: R - Canonical Path
FORMAT: C - Command Line

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/__init__.cpython-311.pyc.140501841581168
A: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/__init__.cpython-311.pyc.140501841581168
R: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/__init__.cpython-311.pyc.140501841581168
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/more.cpython-311.pyc.140501841581312
A: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/more.cpython-311.pyc.140501841581312
R: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/more.cpython-311.pyc.140501841581312
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/recipes.cpython-311.pyc.140501841588080
A: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/recipes.cpython-311.pyc.140501841588080
R: /usr/lib/python3.11/site-packages/more_itertools/__pycache__/recipes.cpython-311.pyc.140501841588080
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/__pycache__/appdirs.cpython-311.pyc.140501842061104
A: /usr/lib/python3.11/site-packages/__pycache__/appdirs.cpython-311.pyc.140501842061104
R: /usr/lib/python3.11/site-packages/__pycache__/appdirs.cpython-311.pyc.140501842061104
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/__init__.cpython-311.pyc.140501842150576
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/__init__.cpython-311.pyc.140501842150576
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/__init__.cpython-311.pyc.140501842150576
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/__about__.cpython-311.pyc.140501842150720
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/__about__.cpython-311.pyc.140501842150720
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/__about__.cpython-311.pyc.140501842150720
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/version.cpython-311.pyc.140501842065712
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/version.cpython-311.pyc.140501842065712
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/version.cpython-311.pyc.140501842065712
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/_structures.cpython-311.pyc.140501842151440
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/_structures.cpython-311.pyc.140501842151440
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/_structures.cpython-311.pyc.140501842151440
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/specifiers.cpython-311.pyc.140501842151872
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/specifiers.cpython-311.pyc.140501842151872
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/specifiers.cpython-311.pyc.140501842151872
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/utils.cpython-311.pyc.140501842363696
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/utils.cpython-311.pyc.140501842363696
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/utils.cpython-311.pyc.140501842363696
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/tags.cpython-311.pyc.140501842363696
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/tags.cpython-311.pyc.140501842363696
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/tags.cpython-311.pyc.140501842363696
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/_manylinux.cpython-311.pyc.140501842153600
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/_manylinux.cpython-311.pyc.140501842153600
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/_manylinux.cpython-311.pyc.140501842153600
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/_musllinux.cpython-311.pyc.140501 * 
842154752
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/_musllinux.cpython-311.pyc.140501842154752
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/_musllinux.cpython-311.pyc.140501842154752
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/requirements.cpython-311.pyc.140501842154896
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/requirements.cpython-311.pyc.140501842154896
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/requirements.cpython-311.pyc.140501842154896
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shibo * 
ken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/ordered_set/__pycache__/__init__.cpython-311.pyc.140501837345776
A: /usr/lib/python3.11/site-packages/ordered_set/__pycache__/__init__.cpython-311.pyc.140501837345776
R: /usr/lib/python3.11/site-packages/ordered_set/__pycache__/__init__.cpython-311.pyc.140501837345776
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 
154896
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/__init__.cpython-311.pyc.140501842155040
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/util.cpython-311.pyc.140501842365616
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/exceptions.cpython-311.pyc.140501842155616
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/unicode.cpython-311.pyc.140501842366000
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/actions.cpython-311.pyc.140501841172528
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/core.cpython-311.pyc.140501841174960
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/results.cpython-311.pyc.140501838989872
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/helpers.cpython-311.pyc.140501838993456
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0 

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/testing.cpython-311.pyc.140501841171504
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
A: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
R: /usr/lib/python3.11/site-packages/pyparsing/__pycache__/common.cpython-311.pyc.140501837141040
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2/libshiboken/embed/embedding_generator.py --cmake-dir /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shiboken2_build-python3_11/libshiboken/embed --limited-api 0

F: open_wr
S: deny
P: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
A: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
R: /usr/lib/python3.11/site-packages/packaging/__pycache__/markers.cpython-311.pyc.140501837142064
C: /usr/bin/python3.11 -E /var/tmp/portage/dev-python/shiboken2-5.15.5/work/pyside-setup-opensource-src-5.15.5/sources/shibo * --------------------------------------------------------------------------------

>>> Failed to emerge dev-python/shiboken2-5.15.5, Log file:
```
The problem seems to be only in `python3_11`, the `python3_10` target compiles fine.

CC'ing @thesamesam who added python3_11 compatibility to version 5.15.2 earlier.

**Comment by thesamesam** [comment]
py3.11 changed byte code format, see pkg_postinst of latest versions. Need to run a command to fix it.

(mobile so can't give details)

**Comment by AndrewAmmerlaan** [comment]
> py3.11 changed byte code format, see pkg_postinst of latest versions. Need to run a command to fix it.
> 
> It's not specific to this package. It's your system which needs fixing because Python snuck in a change before RC.
> 
> (mobile so can't give details)

Aah right, thanks for explaining.

I had missed the python postinst message because I'm doing too many things simultaneously again.

**Comment by AndrewAmmerlaan** [comment]
I found these QA notices, otherwise it is fine. I briefly tested it with some QtPy applications and found no issues.

* QA Notice: pkg-config files not respecting libdir found
* (contains reference to either lib or lib64 in wrong directory)
*   /usr/lib64/pkgconfig/pyside2-python3.11.pc
*   /usr/lib64/pkgconfig/pyside2.pc
*   /usr/lib64/pkgconfig/pyside2-python3.10.pc

**Comment by waebbl** [comment]
> I found these QA notices, otherwise it is fine. I briefly tested it with some QtPy applications and found no issues.
> 
> ```
> * QA Notice: pkg-config files not respecting libdir found
> * (contains reference to either lib or lib64 in wrong directory)
> *   /usr/lib64/pkgconfig/pyside2-python3.11.pc
> *   /usr/lib64/pkgconfig/pyside2.pc
> *   /usr/lib64/pkgconfig/pyside2-python3.10.pc
> ```

I got these as well, but I suppose these to be related to how Gentoo installs files. The pkg-config files list the libs in lib64, but the python binaries (*.cpython-*.so) are installed in the python site-packages dir, thus in `/usr/lib/python-3.x/site-packages`.
There's nothing which I know of, that I could do here.

**Comment by AndrewAmmerlaan** [comment]
> > I found these QA notices, otherwise it is fine. I briefly tested it with some QtPy applications and found no issues.
> > ```
> > * QA Notice: pkg-config files not respecting libdir found
> > * (contains reference to either lib or lib64 in wrong directory)
> > *   /usr/lib64/pkgconfig/pyside2-python3.11.pc
> > *   /usr/lib64/pkgconfig/pyside2.pc
> > *   /usr/lib64/pkgconfig/pyside2-python3.10.pc
> > ```
> 
> I got these as well, but I suppose these to be related to how Gentoo installs files. The pkg-config files list the libs in lib64, but the python binaries (_.cpython-_.so) are installed in the python site-packages dir, thus in `/usr/lib/python-3.x/site-packages`. There's nothing which I know of, that I could do here.

Can't we just move them from `/usr/lib64/pkgconfig/` to `/usr/lib/pkgconfig/`?

**Comment by waebbl** [comment]
> > > * (contains reference to either lib or lib64 in wrong directory)
> Can't we just move them from `/usr/lib64/pkgconfig/` to `/usr/lib/pkgconfig/`?

As far as I understand this, it's about the contents of the pkg-config files. They have references to the `/usr/lib64/libpyside*.so` as well as to `/usr/lib/python3.10/site-packages/*.cpython-*.so` and that's causing the warning.

**Comment by AndrewAmmerlaan** [comment]
> > > > * (contains reference to either lib or lib64 in wrong directory)
> > > >   Can't we just move them from `/usr/lib64/pkgconfig/` to `/usr/lib/pkgconfig/`?
> 
> As far as I understand this, it's about the **contents** of the pkg-config files. They have references to the `/usr/lib64/libpyside*.so` or something, as well as to `/usr/lib/python3.10/site-packages/*.cpython-*.so` and that's causing the warning.

Alright, makes sense, nothing to do about it then.

Merged, Thanks :+1:

**Comment by waebbl** [comment]
Thanks for merging.

**Pull request closed without merging**
