### PR TITLE
www-servers/tomcat: restrict to max java 17

### PR DESCRIPTION
**Pull request by vaukai**
Closes: https://bugs.gentoo.org/916705

@fordfrog haven't tested all the USE flags, just only ensured it can compile.

### CODE REVIEW

**Comment by vaukai** [comment]
Changing `build.xml` like this didn't help
```
<property name="compile.release" value="8"/>
<property name="min.java.version" value="8"/>
```

**Comment by fordfrog** [comment]
> Changing `build.xml` like this didn't help
> 
> ```
> <property name="compile.release" value="8"/>
> <property name="min.java.version" value="8"/>
> ```

i guess it's caused by this:
```
modules/jdbc-pool/build.properties.default:compile.release=7
```

**Comment by vaukai** [comment]
> i guess it's caused by this:
> 
> ```
> modules/jdbc-pool/build.properties.default:compile.release=7
> ```

Verified, solved.

**Comment by fordfrog** [comment]
> Verified, solved.

cool! i also revbumped it as it changes the bytecode. previous ebuild would not run (at least the affected part) with java 21 (i suppose java 21 does not support bytecode < 1.8).

**Pull request closed without merging**
