### PR TITLE
Add mongrel2

### PR DESCRIPTION
**Pull request by jasom**
https://bugs.gentoo.org/show_bug.cgi?id=350826

### CODE REVIEW

**Comment by jasom** [comment]
whoops, I have an extra commit in here; I will fix

**Comment by idella** [comment]
points given in irc re commit message

**Comment by jasom** [comment]
Just noticed I forgot to set prefix; fixing now.

**Comment by idella** [comment]
Also to add IUSE examples and install the examples, and an init script

**Comment by idella** [comment]
PREFIX="${D}/usr"  ->   PREFIX="${D}usr"
I still prefer emake  DESTDIR="${D}" install || die

**Comment by jasom** [comment]
@idella changed to your preferred style for specifying the destination

**Comment by idella** [comment]
merged

**Comment by gktrk** [comment]
@jasom I know this is merged already but for future reference: starting with EAPI4, the utilities die by themselves on failure [1], so you don't need the '|| die' in src_install(). Good luck!

[1] https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-176000E

**Pull request closed without merging**
