### PR TITLE
media-libs/libavif: drop 1.0.1 and 1.0.3

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

**libavif** 1.0.1 and 1.0.3 contain [known issues](https://github.com/AOMediaCodec/libavif/releases/tag/v1.0.4), so it's worth removing them in favor of 1.0.4.

These changes also:
  - add `~mips` to the `KEYWORDS`
  - fix [pkgcheck](https://wiki.gentoo.org/wiki/Pkgcheck) warnings
    * enable `dav1d` by default for big-endian arches
    * remove redundant `unset __GL_NO_DSO_FINALIZER`
    * replace deprecated `virtual/jpeg` with `media-libs/libjpeg-turbo`

Bug: https://bugs.gentoo.org/375615
Closes: https://bugs.gentoo.org/918451

_Best regards!_

### CODE REVIEW

**Comment by novomesk** [comment]
I am attempting to add 1.0.4 in https://github.com/gentoo/gentoo/pull/35356

**Comment by Jamim** [comment]
_Hello @novomesk,_

Sorry for missing your PR. My version contains additional changes, so I'd like to keep it as a draft for now and update it once #35356 is merged.

_Thanks!_

**Comment by Jamim** [comment]
_Hello @novomesk,_
I've updated the PR, so it's ready for review now.

**Comment by mgorny** [comment]
Are older versions not suitable stabilization candidates?

**Comment by novomesk** [comment]
OK, to remove old versions. We should stabilize 1.0.4 in the near future.

**Comment by Jamim** [comment]
> Are older versions not suitable stabilization candidates?

Assuming by older versions you mean `0.10.1` and `0.11.1`, there are no packages restricting **libavif** to `<1.0.0`, so those old versions might be safely dropped once `1.0.4` or some newer version is stable enough.

**Comment by Jamim** [comment]
_Hello @mgorny,_
Is there something preventing these changes from being accepted?

**Comment by mgorny** [comment]
Ah, sorry, I asked a question without reviewing it.

Now that I review it: it's not fine to mix removal of old versions with other changes in a single commit. Please split it, so that if removal needs to be reverted, we can do that cleanly.

**Comment by Jamim** [comment]
I've updated the PR. Thank you, @mgorny!

**Review by mgorny — APPROVED** [review]
Thanks. I have kernel bumps queued right now, so I'll merge it when I'm done testing them.

**Pull request closed without merging**
