### PR TITLE
dev-util/watchman: keyword 2024.11.04.00 for ~arm64

### PR DESCRIPTION
**Pull request by sin-ack**
All dependencies with tests were confirmed to pass inside a QEMU chroot.

Depends on #39296.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by sin-ack** [comment]
The test skips have been moved to #39296.

**Comment by sin-ack** [comment]
This PR now depends on #39296 per https://github.com/gentoo/gentoo/pull/39296#issuecomment-2494667078.

**Comment by thesamesam** [comment]
Needs a rebase but I was/am hoping that the regular archtesting machinery would pick up the bug now the test failures are fixed. But let's not wait anymore. Will merge when rebased.

**Comment by sin-ack** [comment]
@thesamesam Done.

**Pull request closed without merging**
