### PR TITLE
dev-java/jython: Remove vulnerable versions. Fixes security bug 552452.

### PR DESCRIPTION
**Pull request by monsieurp**
Just to have the CI checks run and make sure I'm not breaking the tree. ;)

### CODE REVIEW

**Comment by monsieurp** [comment]
Looks good. I'm going to merge it.

**Comment by iHateInventNames** [comment]
does jython-2.7 depend on icedtea-**bin**:7?

**Comment by monsieurp** [comment]
I don't think so. @chewi can you confirm?

**Comment by chewi** [comment]
Huh? It needs at least JDK 7 and that could be satisfied by icedtea-bin:7 as well as any of the other JDKs we currently support. Where did that question even come from?

**Comment by iHateInventNames** [comment]
I had no jdk:7, but I had jdk8:7. Once I installed ant or freemind, it pulled jython:2.7 that pulled jdk:7 and guess what was installed. icedtea-**bin**:7, just like mentioned in jdk RDEPEND first item. Anyone mind if I swap it with icedtea:7?

**Comment by chewi** [comment]
What is jdk8:7? Assuming you meant virtual/jdk:1.8, I'm not sure why it pulled in 7 as very few things require that explicitly but preferring -bin is intentional as I explained in your pull request.

**Pull request merged**
