### PR TITLE
dev-libs/trio: Add 1.17

### PR DESCRIPTION
**Pull request by orbea**
Closes: https://github.com/gentoo/gentoo/pull/26711

I followed @ionenwks suggestion (https://github.com/gentoo/gentoo/pull/26711#issuecomment-1204216702) and forked trio's inactive upstream git repo at their sourceforge. Merged the one pending PR from 2018 that fixed various typos in the documentation. Applied any seemingly relevant changes from various trio packages found with repology.org. Added a standard autotools build based on a patch from yacp and tagged a `1.17` release.

In the future I don't plan to do much with this besides merge any reasonable PRs and make sure it continues to work with mednafen. Probably not much else depends on it and they shouldn't start now...

### CODE REVIEW

**Comment by thesamesam** [comment]
By the way, have you tried speaking to bagder about this? he's very active in #curl and is a nice guy. He might be willing to make it official, dunno.

**Comment by ionenwks** [comment]
Nice, may get adopted by other distros when it hits repology over time.

I'll have a closer look tomorrow or so for merging.

**Comment by orbea** [comment]
> By the way, have you tried speaking to bagder about this? he's very active in #curl and is a nice guy. He might be willing to make it official, dunno.

I sent a PM on irc and will see. :)

**Comment by ionenwks** [comment]
Thanks, did some minor ebuild adjustments in commit bf2fdc6c65ff7a1ad573266929907b2287f39de9 for the record.

**Comment by orbea** [comment]
@ionenwks Thanks! There are many examples of using `${ED}` and `${D}` when removing the `.la` files, I clearly copied the wrong one.

Is there a general guide for when `DOCS_DEPEND` is needed? All I found was this and I don't know much about doxygen.

https://devmanual.gentoo.org/eclass-reference/docs.eclass/index.html

**Comment by ionenwks** [comment]
For doxygen typically the only thing that's sometime needed is media-gfx/graphviz for `dot` (typically get some dot command not found if don't have it installed), but trio doesn't seem to enable it. Not that I really know doxygen either.

Previous .la wasn't wrong per-se given ${D} works too, but just trying to keep these the same.

*Technically* from:
https://projects.gentoo.org/qa/policy-guide/installed-files.html#pg0303
But currently it's a bit outdated, `-type f` was added:
https://gitweb.gentoo.org/proj/policy-guide.git/commit/?id=48c7ed27d229014f560f0be4d4eda8dab4d1ec7d

**Pull request closed without merging**
