### PR TITLE
media-libs/libva-intel-driver: unmask USE flag 'hybrid' on stable branch

### PR DESCRIPTION
**Pull request by kcning**
With [commit](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=09f8b6f499b97355bb74248db0b4be5efa720802), one can unmask USE flag 'hybrid' on stable branch.

### CODE REVIEW

**Comment by mattst88** [comment]
Is the hybrid driver actually valuable? For example, are there any benchmarks that show it working?

**Comment by kcning** [comment]
> Is the hybrid driver actually valuable? For example, are there any benchmarks that show it working?

Please see comments from a FreeBSD dev: https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=232981

**Comment by mattst88** [comment]
Thanks!

**Comment by kcning** [comment]
Thank you too!

**Pull request closed without merging**
