### PR TITLE
dev-libs/wlc: fix missing RDEPEND and X configuration

### PR DESCRIPTION
**Pull request by tajjada**
Gentoo-Bug: https://bugs.gentoo.org/584462

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
You should revbump on non-live ebuilds when modifying RDEPEND like this

**Comment by tajjada** [comment]
@gktrk 
Done.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/commit/9fa1f6828f5af35745fbf59cd58b62f86bf13de7. Thanks!

Modifications I've made on top of your patch:
- Edited the commit message to use the Gentoo-Bug tag as mentioned in [devmanual](https://devmanual.gentoo.org/ebuild-maintenance/index.html#git-commit-message-format)
- Removed an extra indent in DEPEND

**Pull request closed without merging**
