### PR TITLE
*/*: Add [profile?] to dev-lang/ghc RDEPEND

### PR DESCRIPTION
**Pull request by hololeap**
Original PR: https://github.com/gentoo/gentoo/pull/30773

- Add `[profile?]` to every dev-lang/ghc RDEPEND to make sure `ghc` was built with profiling support when `USE=profile` is used.

  Virtually every Haskell package has a dependency on the `base` library that ships with dev-lang/ghc. As a result, there will be errors if dev-lang/ghc was not built with `USE=profile` when a Haskell package uses the same.

- Add new version of `hackport` which adds `dev-lang/ghc:=[profile?]` automatically.

Closes: https://bugs.gentoo.org/735172
Closes: https://bugs.gentoo.org/905132
Closes: https://bugs.gentoo.org/905133
Closes: https://github.com/gentoo/gentoo/pull/30773
Reported-by: Filip Kszczot <filip@kszczot.pl>

### CODE REVIEW

**Comment by szczot3k** [comment]
Also - Closes: https://github.com/gentoo/gentoo/pull/30773

**Comment by orlitzky** [comment]
Looks reasonable since I bet what usually happens is that people miss `dev-lang/ghc` when they set flags for `dev-haskell/*`.

Is this a GHC-only problem? In other words, if my package depends on `dev-haskell/foo` and I build foo without profiling but my own package with it, does that still work?

**Comment by hololeap** [comment]
> Looks reasonable since I bet what usually happens is that people miss dev-lang/ghc when they set flags for dev-haskell/*.

The idea is reasonable, but my approach isn't. It is better to add `dev-lang/ghc:=[profile?]` in the eclass only when `CABAL_FEATURES="profile"` is set, otherwise you get issues with exe-only packages which do not support `IUSE="profile"`.

I'll un-draft this when the eclass approach is ready.

> Is this a GHC-only problem? In other words, if my package depends on dev-haskell/foo and I build foo without profiling but my own package with it, does that still work?

The `profile` USE flag tells the haskell build system to build the profiling libs alongside the regular libs for a package. If your package needs profiling support, it would need those profiling libs available for all of its dependencies (and therefore its entire dependency tree, including ghc).

**Comment by hololeap** [comment]
This was solved in https://github.com/gentoo-haskell/gentoo-haskell/commit/f124fde040358178ce7c0e07b8cfc9ac199b0e84 and added to `::gentoo` in https://github.com/gentoo/gentoo/commit/c8764f6dc7265b3bf42dc30cd6c86de2d6612ee0.

**Pull request closed without merging**
