### PR TITLE
dev-lang/zig: fix building with Clang 16, fix searching LLD 

### PR DESCRIPTION
**Pull request by BratishkaErik**
Upstream PR https://github.com/ziglang/zig/pull/13121
Signed-off-by: Eric Joldasov <bratishkaerik@getgoogleoff.me>

Patches has been accepted upstream.

### CODE REVIEW

**Comment by BratishkaErik** [comment]
Oops, wrong bug.

**Comment by arkamar** [comment]
Could you please reference correct bug in commit message and patch and then append `[please reassign]` to the pull request title, which will link this PR to it? It would be also beneficial for everyone if you add a link to upstream PR or commit to the patch as well.

**Comment by BratishkaErik** [comment]
> Could you please reference correct bug in commit message and patch and then append `[please reassign]` to the pull request title, which will link this PR to it? It would be also beneficial for everyone if you add a link to upstream PR or commit to the patch as well.

There is no bug for `dev-lang/zig`, should I fill one or remove "Bug:" in PR?

**Review by mgorny — APPROVED** [review]
Thanks for the fix! I'll merge it along with 15.x bump, i.e. in 2-3 hours once I finish building it ;-).

**Pull request closed without merging**
