### PR TITLE
www-misc/zoneminder: version bump to 1.30.4

### PR DESCRIPTION
**Pull request by MalakymR**
new dependency added dev-php/pecl-apcu https://github.com/ZoneMinder/ZoneMinder/releases/tag/1.30.4

### CODE REVIEW

**Comment by monsieurp** [comment]
@akhuettel ping?

**Comment by MalakymR** [comment]
What else is needed for this?

**Comment by monsieurp** [comment]
@MalakymR: not much. we're just waiting for @akhuettel to wake up.

**Comment by MalakymR** [comment]
Any news on this?

**Pull request closed without merging**
