### PR TITLE
media-sound/spotify: bump to 1.1.42, remove patchelf version from dep, remove 1.1.26-r1

### PR DESCRIPTION
**Pull request by realnc**
patchelf < 0.10 has been removed from portage for a while now, so no need to depend against >= 0.10.

### CODE REVIEW

**Comment by prometheanfire** [comment]
you mind rebasing this without the removal of 1.1.26?

**Comment by realnc** [comment]
> you mind rebasing this without the removal of 1.1.26?

1.1.26-r2 is still there. Only r1 was removed.

**Comment by realnc** [comment]
Looks like there is now a different version bump in portage. Closing.

**Comment by prometheanfire** [comment]
ah, in that case, fixing the conflict would be my request, then I'll merge.

**Comment by realnc** [comment]
Pushed.

**Pull request closed without merging**
