### PR TITLE
app-emacs/org-roam: install gentoo sitefile

### PR DESCRIPTION
**Pull request by mm1ke**
@ArsenArsen 

I was about to create another PR removing the sitefile from this package. However, since this is a new package i guess this was just forgotten to be installed?
Please review, if it's a leftover, this file could be removed too.

### CODE REVIEW

**Review by ulm — APPROVED** [review]

**Comment by xgqt** [comment]
Don't you need to require the file created by `elisp-make-autoload-file`?

**Comment by ulm** [comment]
> Don't you need to require the file created by `elisp-make-autoload-file`?

The site-init file does `(load "@SITELISP@/org-roam-autoloads.el" nil t)`.

**Review by ArsenArsen — CHANGES_REQUESTED** [review]
the omission is unintentional.  this needs a revbump, however.

thanks!

**Comment by mm1ke** [comment]
@ArsenArsen done

**Pull request closed without merging**
