### PR TITLE
sys-apps/lshw: Add support for musl libc, tested on musl and glibc.

### PR DESCRIPTION
**Pull request by jakeogh**
Tested on glibc 2.19-r1 and musl 1.1.12.

### CODE REVIEW

**Comment by monsieurp** [comment]
Please edit your commit as well and not only the PR title like you just did.

**Comment by monsieurp** [comment]
@gentoo/base-system

**Comment by jakeogh** [comment]
Thanks, updated commit message to PR title.

**Comment by blueness** [comment]
The patch looks sane.  It should go upstream so we don't maintain a bunch of patches downstream.  So far we've been putting these on the musl overlay but maybe its time to start adding thsee to the tree.  The must overlay is at https://gitweb.gentoo.org/proj/musl.git/

@jakeogh are you going to submit this patch upstream?

**Comment by jakeogh** [comment]
@blueness Thanks yes, I'll add the request link here.

**Comment by jakeogh** [comment]
It's upstream: https://github.com/lyonel/lshw/pull/8#issuecomment-180628782

**Comment by blueness** [comment]
@jakeogh i just noticed that patch is against 02.16b-r2 which is stable.  can you make it against 02.17b-r2 which would be a bump of 02.17b-r1.  we can't commit patches to stable ebuild.  this will have to go through the stabilization process.

**Comment by jakeogh** [comment]
Sure, should that be a new PR?

**Comment by blueness** [comment]
@jakeogh whatever works for you really.

**Comment by cardoe** [comment]
@jakeogh I would just force push into this PR. I'm fine with merging this since it looks like upstream doesn't release too often. It looks like they don't have a tag pushed for the most recent 2.17 release either.

**Comment by jakeogh** [comment]
Created https://github.com/gentoo/gentoo/pull/800 closing this one.

**Comment by jakeogh** [comment]
Sorry, do you mean add this patch to 02.16b-r2 (stable?). Reopen this if you want me to force merge.

**Comment by blueness** [comment]
@cardoe, its been a while so we should stabilize 02.17b-r2 after a couple of weeks of testing.  the original PR was against only 0.2.16b and not 0.2.17b so we would have lost the patch on the next stabilization.  0.2.17b is already three years old, so i think its time to stabilize it.  From upstream:

```
[ ]	lshw-B.02.16.tar.gz 	2012-01-10 23:02 	1.8M	 
[ ]	lshw-B.02.17.tar.gz 	2013-08-04 15:18 	1.9M	 
```

**Comment by cardoe** [comment]
@blueness I don't disagree. I was merely stating that upstream's repo didn't have a tag for B.02.17 and they don't have a frequent release cadence so I'm good with putting this patch in tree. If they had a release cadence of every 30 days I would have said let's hold off and catch it on the next version bump.

**Pull request closed without merging**
