### PR TITLE
dev-libs/libdbusmenu: Version bump 16.04.0

### PR DESCRIPTION
**Pull request by anthonyryan1**
* Eliminates the need for patch
* EAPI 6 bump and conversion to eapply_user

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/kde

**Comment by kensington** [comment]
The ebuild looks good, but for some reason gtkdocs are no longer installed.

**Comment by anthonyryan1** [comment]
You are correct. I had first approached this as a simple bump but it looks like it merits a more in depth review of the ebuild.

* The dependency on `app-text/gnome-doc-utils` has been replaced by a dependency on `dev-util/gtk-doc`. There was even a warning about this in the build log that I somehow missed.
* The lack of docs being installed seems is because we now need to use `--enable-gtk-doc` when configuring to build those.
* It also seems like a good time to remove the pkg_preinst cleanup. No version currently in the tree makes the mess that it's trying to clean up.
* Gentoo-bug: 440192 was resolved "idiotic"-ally, and should be revisited. There should be a RESTRICT="test" (or better yet, get the tests working). We shouldn't just make `src_test` a no-op.

I'll resolve these and post here is I find any other issues before amending this pull request.

**Comment by anthonyryan1** [comment]
The updated changes are as follows:

* Add USE=doc
* Split USE=vala out of USE=introspection
* **[Controversial]** Rename USE=gtk to USE=gtk2
* **[Controversial]** Remove KEYWORD=~hppa until `dev-util/gtk-doc` can be keyworded
* Remove preinstall phase that removed symlinks that don't exist anymore

I look forward to comments and criticism.

**Comment by anthonyryan1** [comment]
After discussion with the folks in #gentoo-qa I have reverted the rename of USE=gtk to USE=gtk2.

**Comment by kensington** [comment]
@gentoo/gnome, can anyone review the vala/introspection changes? I don't know enough about it.

Otherwise, I think this is good to merge.

It looks like libxml2 and dbus-glib may no longer be required - there's some removal mention in the changelog and there's no links to those libraries, but I didn't actually try building without it yet. I don't think this is caused by this bump though so no obligation to fix it here.

**Comment by anthonyryan1** [comment]
No time like the present, I'll test removing those dependencies and amend the pull request shortly.

**Comment by anthonyryan1** [comment]
I've confirmed that we're able to successfully build without libxml2 and dbus-glib, there's also no change to the subset of tests that are actually passing leading me to believe you're correct and we can safely remove those.

I've rebased pushed the latest changes.

**Comment by monsieurp** [comment]
what's the status of this PR? is it ready for merging?

**Comment by anthonyryan1** [comment]
Rebased and fixed upstream in metadata.xml

**Comment by kensington** [comment]
@monsieurp It LGTM but I don't know anything about introspection/vala to review those changes, so ship it?

**Comment by anthonyryan1** [comment]
I'll find someone in #gentoo-gnome to give it a once-over and double check all those bits myself.

**Comment by leio** [comment]
I don't know about vala/introspection and what the do here either. But perhaps introspection is required when vala is enabled? Just a hunch - something to double-check before shipping perhaps.

Regarding USE=gtk, it seems one of the very few packages where it's about shipping of gtk2 and gtk3 support out of the same package, and there USE=gtk2 would make somewhat sense, but it's only a few packages that are like this, and it doesn't seem like we have went that route.
Similar packages in behaviour for the gtk flags are for example app-accessibility/caribou, app-i18n/ibus, media-libs/libcanberra, net-dns/avahi, net-libs/gtk-vnc
In caribou we just enable both gtk2 and gtk3 modules right now. ibus has USE=gtk and gtk3, but gtk3 is default enabled (and one out of gtk, gtk3 or X is required). libcanberra has gtk and gtk3 like libdbusmenu, but both are default enabled. avahi is exactly like libdbusmenu right now, but I think this is a non-ideal situation coming from not a good way to split these libraries at a source level with current manpower. gtk-vnc is similar, but there we currently always build gtk2 version and gtk3 is behind default enabled USE=gtk3.
We don't like having support for both in case of applications, like we don't want to have a USE=gtk3 control an application build whether it builds against gtk2 or gtk3, but want the maintainer to make that decision (use gtk2 if gtk3 version is not on feature-parity yet, gtk3 otherwise), but libdbusmenu isn't such a case here. I don't know exactly what USE=gtk and USE=gtk3 build in there to know more. I presume neither is required and without gtk USE flag it builds something generic? How are the gtk things ending up being consumed? Maybe it doesn't make sense to USE flag them at all, or made sense to default enable as well? I don't know the package specifics here to suggest one way or the other.
Either way, don't really want to see an exceptional USE=gtk2 for now without a broad decision to go that way with everything (mainly having libcanberra, avahi, caribou and so on in mind here).

**Comment by leio** [comment]
Ok, so, for the USE=gtk stuff upon some looking at it:

It first builds a version without gtk (--disable-gtk), this just means not building libdbusmenu-gtk library.
Then based on USE=gtk and gtk3 it does more configures in separate build dirs, with --enable-gtk and --with-gtk={2,3} out of what is selected by USE. For that it removes the libdbus-glib in the out of tree gtk configure result and symlinks that to the build already done at the start to avoid rebuilding later. During other phase it then goes into these extra out of tree configures as well, and only builds and installs the libdbusmenu-gtk bits by limiting make runs to only that subdir (and its docs dir).
So ideally, we would instead have a libdbusmenu or libdbusmenu-glib package that provides the common libdbusmenu-glib library, a libdbusmenu-gtk2 package that builds the gtk2 library (and uses the separate libdbusmenu-glib package as a system dep), and a libdbusmenu-gtk3 package for the gtk3 library. Or a libdbusmenu-gtk package with SLOT=2 and SLOT=3 as -r2xx and -r3xx revisions like libappindicator does.

Then app-misc/workrave can dep on libdbusmenu-gtk3; libappindicator:3 as well, while libappindicator:2 can dep on libdbusmenu-gtk2 instead. Then there's also libindicate, and that's about it as far as in-tree consumers go...
Hence I can understand this splitting is not done - it'd be currently for the benefit of just 2-3 in-tree packages.
But this is what I'd suggest to avoid any USE=gtk2 business in an ideal world - split it at source level, because it's about shipping specific differently named libraries, not features in existing ones based on USE flags. But because we can't just do like binary distributions do it (and probably actually do split it up at binary package level), it's hard to justify the maintenance burden of handling the separate libdbusmenu-glib split and patching things up for libdbusmenu-gtk builds to use system libdbusmenu-glib headers and libs.

**Comment by anthonyryan1** [comment]
Hello @leio,

Thank you for the excellent feedback. You were spot on with all of that (even me missing the dependency between vala and introspection). For the moment I'm going to close this issue, and when my schedule permits I'll see about splitting this up as you suggested (probably mirroring the way it's done in libappindicator) and re-proposing it.

**Comment by leio** [comment]
@anthonyryan1 - keep in mind the maintenance burden points raised with the split with low benefit on actual consuming packages at the time. I suggest checking with libdbusmenu maintainers if they'd be OK with such a splitting when the work is done once initially, given the extra maintenance burden going forward. Or maybe you will be involved with the package maintenance going forward yourself for the foreseeable future anyways :)

**Comment by anthonyryan1** [comment]
@leio To be honest, this package is probably a once-off for me, this pull request is the first I ever used it.

A few weeks ago on a whim I added the unofficial [elementary overlay](https://github.com/pimvullers/elementary) (pantheon-shell & friends) because I had heard some good things about their interface design, but I found the overlay wasn't in great shape. If I ultimately clean things up there and become a regular user of that desktop environment, I'm likely to continue working on this, but I can't guarantee it as I haven't even used it yet.

On the subject of maintenance:

* Yes, it would end up being 2 extra ebuilds that need to be version bumped. On the flip side, this is the first new release in 4 years.
* All 3 ebuilds would be relatively trivial in complexity compared to the current one, which IMO makes them easier to test and maintain going forward.

With that said, I'll follow your recommended course of action @leio .

**Pull request closed without merging**
