### PR TITLE
~arm64 keyword for a few packages and their dependencies

### PR DESCRIPTION
**Pull request by khumarahn**
The packages in this PR already have arm or ~arm keywords, except pavucontrol and f3. I have been using them on my arm64 laptop without any obvious problems.

There are some issues repoman complains about, but these are inherited from before.

@leio

### CODE REVIEW

**Comment by leio** [comment]
Keywording and stabilization PRs for an architecture should be handled by the relevant arch team (not merged by github/proxy team without architecture team ACK). Thus assigning to myself to review and merge, hopefully tomorrow.

**Comment by khumarahn** [comment]
@leio ping :-)

**Comment by leio** [comment]
dev-perl/Tie-Cycle has newer versions available than you keyword, please test newer and let me know (IRC). No need for PR updates, I'm already merging current state.
Also that ping did nothing, I don't see GH notifications as I said; I meant to ping me on IRC or mail. Got to working on this merge on my own remembering :)

**Comment by leio** [comment]
dev-perl/DateTime-Format-Strptime as well

**Comment by leio** [comment]
media-fonts/wqy-microhei as well

**Comment by khumarahn** [comment]
Yes. I noticed the problem with the packages you mention. They lost ~arm keyword at some point. I wondered what was the problem, but to be safe, keyworded ~arm64 only those versions which had ~arm.

Will look at the newer versions some time later, but this can be separate from this PR.

**Comment by leio** [comment]
What's going on here? Are we done with this PR and what was skipped due to not being latest you have or will submit as new PR?

**Comment by khumarahn** [comment]
Hi, I did not have much time. I tried to test the packages with USE=test, but had random problems. Probably not because of the packages themselves, but because of QEMU.

I still plan to look at what's happening, but this may take time. Could be a new PR.

**Pull request closed without merging**
