### PR TITLE
app-dicts/myspell-ru-20200606 version bump

### PR DESCRIPTION
**Pull request by kuraga**
0.4.5 is out: https://extensions.libreoffice.org/en/extensions/show/russian-dictionary-pack

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
!!! Fetched file: dict_pack_ru-aot-0-4-5.oxt VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      26800
!!! Expected: 26018
Refetching... File renamed to '/var/cache/distfiles/dict_pack_ru-aot-0-4-5.oxt._checksum_failure_.tcz20jd2'
```
After regenerating the manifest, I get
```
>>> Emerging (1 of 1) app-dicts/myspell-ru-20200606::testworld
 * dict_pack_ru-aot-0-4-5.oxt BLAKE2B SHA512 size ;-) ...                                    [ ok ]
>>> Unpacking source...
>>> Unpacking /var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt to /var/tmp/portage/app-dicts/myspell-ru-20200606/work
[/var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt]
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt or
        /var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt.zip, and cannot find /var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt.ZIP, period.
 * ERROR: app-dicts/myspell-ru-20200606::testworld failed (unpack phase):
 *   failed unpacking /var/tmp/portage/app-dicts/myspell-ru-20200606/distdir/dict_pack_ru-aot-0-4-5.oxt
 * 
```

**Comment by juippis** [comment]
Would you like to become the maintainer for this package, since you do the bumps lately? Just replace the current maintainer in `metadata.xml` file.

**Comment by perfect7gentleman** [comment]
Fuck, i don't get it. My PR was there for 2 weeks and no one intervened. This is here for 3 days and they want to replace maintainer. Great!

**Comment by perfect7gentleman** [comment]
```
# Copyright 1999-2020 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

MYSPELL_DICT=( ru_RU.{dic,aff} )
MYSPELL_HYPH=( hyph_ru_RU.dic )
MYSPELL_THES=( th_ru_RU_v2.{dat,idx} )

inherit myspell-r2

EXT="extensions"
DICT="russian-dictionary-pack"
MY_PN="dict_pack_ru-aot"
MY_PV="0.4.5"

DESCRIPTION="Russian spellcheck dictionary based on works of AOT group for myspell/hunspell"
HOMEPAGE="https://extensions.libreoffice.org/extensions/russian-dictionary-pack"
SRC_URI="https://extensions.libreoffice.org/assets/downloads/48/${MY_PN}-${MY_PV}.oxt"

LICENSE="LGPL-2.1"
SLOT="0"
KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~sparc ~x86 ~amd64-linux"

src_prepare() {
	default
	mv russian-aot.dic ru_RU.dic || die
	mv russian-aot.aff ru_RU.aff || die
	mv ru_th_aot.dat th_ru_RU_v2.dat || die
	mv ru_th_aot.idx th_ru_RU_v2.idx || die
}
```

that ebuild works.

**Comment by juippis** [comment]
All of your PRs were missing a sign-off that we require to merge this, and most of them were broken and you just closed them. 
And again, the ebuild you posted cannot be merged like this. 
https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

Are **you** saying you're doing a good job maintaining this package?

**Comment by kuraga** [comment]
Guys, chill out :) @juippis , about #19580, #19581, #19667, #19668, #19669: I just copied an old version to a new version after I've checked dependencies haven't been changed. But seems like it was a bad idea.

**Comment by juippis** [comment]
8488746efc326e6f9d8afa96478f0b6f5d096e9b

**Pull request closed without merging**
