### PR TITLE
www-apache/{mod_security,modsecurity-crs}: bump

### PR DESCRIPTION
**Pull request by hydrapolic**
Thanks :)

### CODE REVIEW

**Comment by hydrapolic** [comment]
@orlitzky @whissi, do you use them?

**Comment by orlitzky** [comment]
No, sorry. I made the last few major commits, but I was probably procrastinating for something more important.

If you're using it, you should take over as maintainer. Oh, and become a dev already.

**Comment by hydrapolic** [comment]
> No, sorry. I made the last few major commits, but I was probably procrastinating for something more important.

@orlitzky Thanks for the update :) I thought so you are not using it but wanted to make sure.

> 
> If you're using it, you should take over as maintainer. Oh, and become a dev already.

Just starting to experiment with it, probably later on i'll add myself if it's useful.

**Comment by Whissi** [comment]
No, I don't use it. I only have to keep maintaining mod_security within nginx ebuild :/

**Comment by hydrapolic** [comment]
Thanks @Whissi.

With modsec3 it's split from apache, will that help you?

**Pull request closed without merging**
