### PR TITLE
net-misc/icingadb: add 1.1.1, drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested on my instance, seems to work fine.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Uhh,
```
!!! Fetched file: icingadb-1.1.1-deps.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      132
!!! Expected: 9308260
```
You've uploaded the wrong tarball :)

sorry for the delay.

**Comment by hydrapolic** [comment]
> Uhh,
> 
> ```
> !!! Fetched file: icingadb-1.1.1-deps.tar.xz VERIFY FAILED!
> !!! Reason: Filesize does not match recorded size
> !!! Got:      132
> !!! Expected: 9308260
> ```
> 
> You've uploaded the wrong tarball :)
> 
> sorry for the delay.

Hello @juippis, Github disabled LFS for me because I also tried to update filebeat (https://github.com/gentoo/gentoo/pull/32374), however that passed the limit. 

Any ideas where can these huge packages be uploaded? I can reupload and change the ebuilds, but currently I don't have any server where this can be done.

**Comment by ceamac** [comment]
@hydrapolic you don't need to push the tarball to git, you can create a new release and add the tarball there.

**Comment by hydrapolic** [comment]
> @hydrapolic you don't need to push the tarball to git, you can create a new release and add the tarball there.

Not sure what you mean @ceamac. 

I need to fetch the go modules, put them in a tarball a place it somewhere on the public Internet so that anyone can download it.

**Comment by hydrapolic** [comment]
@juippis, updated with d.g.o deps hosting so should work now.

**Comment by ceamac** [comment]
> > @hydrapolic you don't need to push the tarball to git, you can create a new release and add the tarball there.
> 
> Not sure what you mean @ceamac.
> 
> I need to fetch the go modules, put them in a tarball a place it somewhere on the public Internet so that anyone can download it.

Sorry, I missed your reply.  What I meant was something like this https://github.com/ceamac/netpbm-make-dist/releases - you don't need to add the tarball to git

**Review by juippis — APPROVED** [review]

**Comment by hydrapolic** [comment]
Huge thanks @juippis

**Comment by juippis** [comment]
No, it was all you buddy :)

**Comment by hydrapolic** [comment]
> > > @hydrapolic you don't need to push the tarball to git, you can create a new release and add the tarball there.
> > 
> > 
> > Not sure what you mean @ceamac.
> > I need to fetch the go modules, put them in a tarball a place it somewhere on the public Internet so that anyone can download it.
> 
> Sorry, I missed your reply. What I meant was something like this https://github.com/ceamac/netpbm-make-dist/releases - you don't need to add the tarball to git

That tar.xz was made from the scripts by github (gh actions)? Or you created a tag/release and attached the file to it?

Are there any limits in place? Because the filebeat deps took around 500MB.

**Comment by ceamac** [comment]
https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

**Comment by hydrapolic** [comment]
> https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases#storage-and-bandwidth-quotas

Thanks, will give it a try!

**Pull request closed without merging**
