### PR TITLE
sys-apps/readahead-list: remove old, update Homepage, fix header

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

Any objections to remove the older ebuilds?
The latest stable has the same KEYWORDS as the old stable.
Futhermore i've also updated the Homepage which would fix: https://bugs.gentoo.org/116329

Please review.

### CODE REVIEW

**Comment by candrews** [comment]
Can you please update the commit that changes the home page to reference the bug it fixes using GLEP 66 tags?

**Comment by mm1ke** [comment]
@candrews Done :)

**Comment by robbat2** [comment]
Probably use the GitHub page as the newer homepage for it:
https://github.com/robbat2/readahead-list
I'm astounded that feature-complete code I wrote 15 years ago, using best practices at the time only have 2 lines of patches to the codebase, for GCC changes.

**Comment by mm1ke** [comment]
@robbat2 thx for the homepage :)
I've updated and rebased the ebuild. Please review.

**Comment by candrews** [comment]
95aa384488283311a5105dc76c393a2ab0ec62db
e8ee4e9dd40524c72161505be792a5b354b10da4

Thanks!

**Pull request closed without merging**
