### PR TITLE
app-admin/rex: bump version to 1.9.0

### PR DESCRIPTION
**Pull request by ferki**
This PR bumps rex to version 1.8.0, and also fixes the following in the ebuild:
  - copyright year
  - switch to EAPI 7
  - switch EGIT_BRANCH to master (only used in the live ebuild, though)
  - uses correct DIST_AUTHOR for the release
  - updates dependencies:
    - replace dev-perl/JSON-XS with dev-perl/JSON-MaybeXS
    - fix test deps (add missing + move out from RDEPEND)
    - edit: update DESCRIPTION

I made the same changes to the live ebuild too in my overlay, but I'd like to handle those changes separately from this PR.

Please review, and either merge or let me know what to change.

Closes: https://bugs.gentoo.org/705190
Package-Manager: Portage-2.3.84, Repoman-2.3.20

### CODE REVIEW

**Comment by ferki** [comment]
I've rebased this branch on top of current master, and updated DESCRIPTION on top of the previous changes.

**Comment by kentfredric** [comment]
I'll review and pull this myself ASAP. Just have some rust stuff to polish off.

**Comment by ferki** [comment]
@kentfredric: thanks for your reply here earlier! If you have any questions about this PR, feel free to ask here or on IRC :)

**Comment by kentfredric** [comment]
The addition of the Test-Pod dependency seems wrong at a glance, it usually is.

Usually it means somebody has shipped a file in `t/` which ubiquitously uses Test::Pod.

But too many people don't understand how pushing this to users is both:
1. Useless
2. Potentially harmful to users

Its useless because it doesn't test anything relevant about the code as per the end user, its an authorship concern. It failing or not failing, tells the user nothing of value.

And its potentially harmful, because the only thing that could cause it to fail for a user, when it didn't fail for the author, would be a change in the semantics in Test::Pod itself, ... and this then means the failure says *nothing* of worth about the Module itself, and could never be a good reason to block all packages that use that module from being installed.

Subsequently, my force of habit seeing this is to employ either nuking of the cause, or patching the cause out.

Additionally, not requiring the installation of Test::Pod and its dependencies is a big plus.

**Comment by ferki** [comment]
@kentfredric: thanks for the feedback! As briefly discussed on IRC, I've removed `dev-perl/Test-Pod` from the dependencies. I've also opened upstream PR to mark it as a development dep instead of a build dep, and it should be part of the next release.

Since this PR was opened a while ago, I've also rebased it on top of current master. Please review again, and let me know if further changes are required.

**Comment by kentfredric** [comment]
For EAPI7, you should also probably be using more BDEPENDS instead of DEPENDS, as DEPENDS are for "target" dependencies, where BDEPENDS are for "build host" dependencies, and as Configure et-al and test all happen on the build host, not the target, BDEPENDS is the right place for these.

**Comment by ferki** [comment]
@kentfredric: I hope I got the BDEPENDS right :crossed_fingers:

Otherwise I would consider reverting to EAPI 6 just to get done with the version bump and let Gentoo folks use a newer version sooner (and then do the EAPI bump separately from this PR).

**Comment by a17r** [comment]
Please git pull --rebase on top of HEAD, so that we get rid of the old gentoo-ci errors, and then maybe @kentfredric finds the time to merge this.

**Comment by ferki** [comment]
Rebased, bumping to newer version, cleaned up depends. Hopefully it's OK to merge now.

**Comment by ferki** [comment]
@kentfredric: I've updated this PR to cut the rex-1.9.0 ebuild based on your recent update to the live ebuild (and rebased it on top of current master branch).

Thank you very much for your work on the live ebuild!

**Comment by kentfredric** [comment]
Merging, but will patch in this diff:
```diff
diff --git a/app-admin/rex/metadata.xml b/app-admin/rex/metadata.xml
index 115fdc8c168..a1b89deccc2 100644
--- a/app-admin/rex/metadata.xml
+++ b/app-admin/rex/metadata.xml
@@ -29,6 +29,7 @@
                <remote-id type="cpan-module">Rex::Box</remote-id>
                <remote-id type="cpan-module">Rex::Box::Amazon</remote-id>
                <remote-id type="cpan-module">Rex::Box::Base</remote-id>
+               <remote-id type="cpan-module">Rex::Box::Docker</remote-id>
                <remote-id type="cpan-module">Rex::Box::KVM</remote-id>
                <remote-id type="cpan-module">Rex::Box::VBox</remote-id>
                <remote-id type="cpan-module">Rex::CLI</remote-id>
@@ -308,11 +309,15 @@
                <remote-id type="cpan-module">Rex::Virtualization::Docker::daemon</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::delete</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::destroy</remote-id>
+               <remote-id type="cpan-module">Rex::Virtualization::Docker::guestinfo</remote-id>
+               <remote-id type="cpan-module">Rex::Virtualization::Docker::images</remote-id>
+               <remote-id type="cpan-module">Rex::Virtualization::Docker::import</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::info</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::list</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::reboot</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::shutdown</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::Docker::start</remote-id>
+               <remote-id type="cpan-module">Rex::Virtualization::Docker::status</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::LibVirt</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::LibVirt::blklist</remote-id>
                <remote-id type="cpan-module">Rex::Virtualization::LibVirt::clone</remote-id>
```

( But that's something so trivial I have a tool that does it for me ;) )

**Pull request closed without merging**
