### PR TITLE
mail-filter/mailfilter: bump to 0.8.9, add proxy-maintainer

### PR DESCRIPTION
**Pull request by hhoffstaette**
Closes: https://bugs.gentoo.org/859514
Signed-off-by: Holger Hoffstätte <holger@applied-asynchrony.com>

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Cleaning up 0.8.7 since it no longer works with GMail. 0.8.8 was buggy, 0.8.9 works fine again.

**Comment by thesamesam** [comment]
> Cleaning up 0.8.7 since it no longer works with GMail. 0.8.8 was buggy, 0.8.9 works fine again.

I'd mention that detail in the commit message.

**Comment by hhoffstaette** [comment]
> I'd mention that detail in the commit message.

Commit message updated accordingly.

**Comment by hhoffstaette** [comment]
Now also with OpenSSL slot removed.

**Comment by thesamesam** [comment]
Thanks, merging..

It's not a blocker (I'm merging anyway now) but could you investigate this with /bin/sh as dash:
```
[...]
checking dependency style of x86_64-pc-linux-gnu-gcc... none
checking whether make sets $(MAKE)... (cached) yes
checking for bison... bison -y
./configure: 5325: test: xbison -y: unexpected operator
checking for flex... flex
checking for lex output file root... lex.yy
checking for lex library... none needed
checking whether yytext is a pointer... yes
./configure: 5548: test: xflex: unexpected operator
checking for stdio.h... yes
checking for stdlib.h... yes
[...]
```

(I think they're configure bashisms, not checked).

**Comment by hhoffstaette** [comment]
> It's not a blocker (I'm merging anyway now) but could you investigate this with /bin/sh as dash:
> 
> ```
> [...]
> checking dependency style of x86_64-pc-linux-gnu-gcc... none
> checking whether make sets $(MAKE)... (cached) yes
> checking for bison... bison -y
> ./configure: 5325: test: xbison -y: unexpected operator

I can reproduce these with dash, and they are indeed configure bashisms.
The messages only appear with dash, but I cannot really tell why.
In any case they are harmless.

**Comment by thesamesam** [comment]
Still need fixing!

**Comment by hhoffstaette** [comment]
> Still need fixing!

Added to https://github.com/gentoo/gentoo/pull/27301

**Comment by thesamesam** [comment]
thanks!

**Pull request closed without merging**
