### PR TITLE
net-p2p/mldonkey: 3.2.1 version bump.

### PR DESCRIPTION
**Pull request by chusopr**
New net-p2p/mldonkey version which closes the bugs below.

I also removed the Sourceforge URL from the upstreams because maintenance was taken over years ago by a different team. The Sourceforge project has been abandoned for years by the previous maintainers, the SF website has been deleted and the newer versions are not available in SF.

Closes: https://bugs.gentoo.org/749609
Closes: https://bugs.gentoo.org/921257

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
The CI report is weird. It looks like it's reporting something we already fixed recently, and I *think* the reason may be because the PR is based on a slightly out of date repository commit. This should not usually matter as the PR can still be applied without conflicts, but it throws off the CI.

Can you try rebasing on the latest gentoo.git commit to see if that fixes the CI?

**Comment by chusopr** [comment]
Yeah, it seems that fixed it.

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
It doesn't fix the LTO issue. Can you either remove that Closes line or apply a filter-lto for it?

**Comment by chusopr** [comment]
Sorry, my mistake, I mixed things.
I didn't pay enough attention and thought that [bug 927332](927332) was the same as upstream https://github.com/ygrek/mldonkey/issues/62 because both are related to GCC failures with the bundled crypto++.
We will have to wait for the next release that will unbundle crypto++ to close that one.

**Comment by chusopr** [comment]
I just noticed I forgot to remove this comment which is not correct anymore: https://github.com/gentoo/gentoo/blob/6f18219/net-p2p/mldonkey/mldonkey-3.2.1.ebuild#L30

I guess it's not worth creating a new PR just to update a commit and that can be removed in the next update.

**Comment by eli-schwartz** [comment]
Yeah, updating the comment can be done in the next update indeed.

**Pull request closed without merging**
