### PR TITLE
app-arch/x-compressor: Add new package

### PR DESCRIPTION
**Pull request by xbarin02**
Please find attached the x-compressor-8-r1.ebuild. The [x-compressor](https://github.com/xbarin02/x-compressor) is an easily verifiable and portable lossless data compressor based on an adaptive Golomb-Rice coding and context modeling.

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
Please remove all that CFLAGS from the makefile

**Comment by xbarin02** [comment]
> Please remove all that CFLAGS from the makefile

Which ones? Do you mean remove CFLAGS+=-std=c99 -pedantic -Wall -Wextra completely? I guess that at least -std=c99 should be there.

**Comment by mgorny** [comment]
> > Please remove all that CFLAGS from the makefile
> 
> Which ones? Do you mean remove CFLAGS+=-std=c99 -pedantic -Wall -Wextra completely? I guess that at least -std=c99 should be there.

Tbose four are fine.

**Comment by Alessandro-Barbieri** [comment]
The various `-O3` `-g` `-march=native`

**Comment by xbarin02** [comment]
> The various `-O3` `-g` `-march=native`

But these are not in effect unless you set the `BUILD` variable (see `ifeq ($(BUILD)`). They are disabled by default. Should I remove these optional parts anyway?

**Comment by ajakk** [comment]
There doesn't seem to be any interest in base-system on this, and since new packages aren't added via proxy-maint anymore I'm going to close this. A better place for this contribution is the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU), please add there if still interested!

**Pull request closed without merging**
