### PR TITLE
net-misc/tigervnc: version bump 1.7.1

### PR DESCRIPTION
**Pull request by khumarahn**
Hi, this is a security update. Release notes:

> This is a security update for TigerVNC 1.7.0 which fixes a memory overflow issue via the RRE decoder. A malicious server could possibly use this issue to take control of the TigerVNC viewer.
> 
> Users are advised to upgrade as soon as possible.

The update is simply renaming the ebuild for version 1.7.0. The previous version is not saved because it is unsafe.

Tigervnc has no maintainer. I volunteered, but there was no answer.

### CODE REVIEW

**Comment by khumarahn** [comment]
@SoapGentoo hi, you merged the previous version, maybe you could take a look at this PR. It is really elementary, corresponds to a minor code change upstream.

**Comment by SoapGentoo** [comment]
@khumarahn can you please rebase

**Comment by khumarahn** [comment]
@SoapGentoo 
Sure, rebased.

**Comment by SoapGentoo** [comment]
@khumarahn already in tree due to @Whissi, thanks for the PR, next time I will merge it quicker :smile:

**Pull request closed without merging**
