### PR TITLE
x11-libs/libxcb: Only install man pages with USE="doc"

### PR DESCRIPTION
**Pull request by cjmayo**
Reduces default installation by 2043 files

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by floppym** [comment]
cc @gentoo/x11

**Comment by monsieurp** [comment]
LGTM. :+1:

**Comment by leio** [comment]
I'm sorry, but I have reverted this unauthorized merge. I do not see any ACKs by x11 team members and USE=doc is not meant for controlling installation of man pages. FEATURES=noman is. USE=doc is only used when it imposes extra build time dependencies, but the man pages are generated during buildtime with a simple python script from xml in a very fast manner, with the xml shipped in the tarball. IFF this would be changed in any way, it should be about also skipping the generation of them, not just removing them after the fact (but I don't think that should be done, it's very fast and imposes no big build times nor extra downloads). Out of these 2043 man files, only 658 are real manuals, each around 1kB; rest are see also manual links.
Additionally the phase was wrong, as pkg_preinst has nothing to do with $D and breaks the existing FEATURES=noman feature (though this was fixed by someone separately).
As such, I have removed the revbump from tree.

@monsieurp: Stop merging things without maintainer ACKs!! If you do get maintainer ACK, then add an Acked-by tag, so other project members know and know who to talk to if necessary.

@cjmayo: Sorry for this; it is not your job to know these nuances like USE=doc, so I'm not blaming you in any way and thanks for your contribution regardless and please do keep it up! If you want to follow-up on this, please open a new bug on Gentoo bugzilla to discuss the merits of doing this - there were some discussions about this on https://bugs.gentoo.org/show_bug.cgi?id=534122 already back then afterall (you might want to reference that in the new bug if you do file a new one).

**Comment by cjmayo** [comment]
OK. Created https://bugs.gentoo.org/show_bug.cgi?id=595936.

**Pull request closed without merging**
