### PR TITLE
media-libs/libsdl2: mingw-w64: --enable-loadso

### PR DESCRIPTION
**Pull request by hanetzer**
Just some things to make media-libs/libsdl2 a bit more nice to use
under a crossdev mingw-w64 target.

Also, unsure if I should regenerate the manifests in this PR. Please
do comment on that.

Signed-off-by: Marty Plummer <ntzrmtthihu777@gmail.com>

### CODE REVIEW

**Comment by chewi** [comment]
There's a few issues here.

* Changes should be made in a new revision of 2.0.5. Don't modify the existing ebuilds.
* These USE flags should be local and described in metadata.xml. You need several packages to use a flag before it can become global and this needs to be agreed by other developers.
* Please explain the change to the dependencies. Are you saying that Windows can use OpenGL but those packages are not required? Is any package required or are the libraries and headers assumed to be there? Either way, this could be dealt with in virtual/opengl.
* Following the above, the win32 USE flag seems redundant. Just use directx.
* REQUIRED_USE should not be overused as it is an inconvenience to users. In this case, I think it would be sufficient for direct3d to automatically imply directx.
* These new flags are not appropriate for most system profiles and should be masked by default. media-video/vlc has a directx flag that is masked in the base profile. You could unmask them in the prefix/windows profile.

You don't need to regenerate the Manifest as ebuilds are not included in it.

**Comment by ntzrmtthihu777** [comment]
@chewi thanks for the suggestions.
* so a new file, libsdl2-2.0.5-r1.ebuild or sommat?
* I'm intending to work over a fair amount of packages treewide for mingw-w64 stuff, so I figured
a set of global flags would be best in this case, correct me if I'm wrong here.
* basically I'm mirroring arch on this. The use case here is simply a crossdev-based mingw-w64 toolchain, so these and their deps aren't needed as far as I can tell. I was not aware of the operation of the virtual/opengl package and the kernel bit.
* I don't understand how one would do that.
* a good point. on another note, I'm unsure how one would even make use of the prefix/windows profile as the gentoo wiki's page on mingw doesn't make mention of it iirc, I ended up using the copy the embedded profile and edit technique.

**Comment by chewi** [comment]
I don't think the loadso flag is really needed. As mentioned earlier, REQUIRED_USE creates unnecessary headaches. You may as well do `$(use_enable kernel_Winnt loadso)` instead.

**Comment by hanetzer** [comment]
It is, trust me on this one, I've checked and double checked. Sure, I'll adjust it.

**Comment by chewi** [comment]
I think you misunderstood, I do trust you that the change is needed, I was just debating the need for the USE flag. This looks good. I'll try to merge once I've finished constructing this bookshelf...

**Comment by chewi** [comment]
I merged this but as modifications to the existing ebuilds. No point triggering rebuilds for everyone when this only affects Windows.

**Pull request closed without merging**
