### PR TITLE
media-libs/codec2: disable tests in configure phase for now

### PR DESCRIPTION
**Pull request by matoro**
Until unrestricted.

### CODE REVIEW

**Comment by thesamesam** [comment]
Add a conditional restrict instead like normal?

**Comment by matoro** [comment]
> Add a conditional restrict instead like normal?

That doesn't work, because all that does is prevent the test phase from running if `USE=test` is not set.  But in this case, when `USE=test` is set, it fails in the configure phase, not the test phase.

**Comment by thesamesam** [comment]
The commit message and comment don't explain that ;)

**Comment by matoro** [comment]
> The commit message and comment don't explain that ;)

Done, reworded both the comment and commit message.

**Pull request closed without merging**
