### PR TITLE
dev-python/evernote-sdk: new package

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
My first ebuild.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by vitaly-zdanevich** [comment]
Thank you for help.

I hope to wait for approve for main Portage tree.

And I have concern about this ebuild because it required Python 2, do you think ebuilds with Python 2 will be removed in this year?

**Comment by AndrewAmmerlaan** [comment]
> Thank you for help.
> 
> I hope to wait for approve for main Portage tree.
> 
> And I have concern about this ebuild because it required Python 2, do you think ebuilds with Python 2 will be removed in this year?

The python team is currently slowly removing python2 support from ebuilds, and I'm pretty sure they won't add any new py2_7 packages. I think you'll have better luck trying to add the beta py3 version of this package: https://github.com/evernote/evernote-sdk-python3

Also, try to squash your commits, for PRs it is preferred to have one commit per package changed. Furthermore, you cannot add stable KEYWORDS in PRs, please commit with unstable KEYWORDS only. Stable KEYWORDS can be added once a package has been in the tree for a while. Also, try to use the latest EAPI (which is 7 at the moment).

Apart from that your ebuild looks fine :+1: (though admittedly I haven't tried actually installing it yet)

**Comment by vitaly-zdanevich** [comment]
Thank you, but I need evernote sdk for Python 2 only because I need [Geeknote](https://github.com/jeffkowalski/geeknote/), it is still for Python 2 :(

**Comment by AndrewAmmerlaan** [comment]
> Thank you, but I need evernote sdk for Python 2 only because I need [Geeknote](https://github.com/jeffkowalski/geeknote/), it is still for Python 2 :(

I'm not on the python-team, but I'm pretty sure the current policy is to not add any new packages that *only* support py2 :(

I just tried running the Geeknote tests with py3, and it's giving a lot of invalid syntax errors, so it looks like it is non-trivial to patch this to support py3 (though it could be done I suppose). It also looks like py2 support has already been removed on some dependencies :(

Sorry about that, but it looks like Geeknote can't be added to ::gentoo until upstream ports to py3. We also can't add Geeknote to ::guru, because it would require overriding some packages in ::gentoo which is against the guru regulations. That being said, you can still put Geeknote in a personal overlay until such time as it supports py3, though it might be a lot of work to also add py2 support to all the dependencies, and that might not be worth the effort.

The py3 version of evernote-sdk could still be added to ::gentoo or ::guru though.

**Comment by vitaly-zdanevich** [comment]
Ok, thank you for clarification.

**Pull request closed without merging**
