### PR TITLE
www-apps/rutorrent: bump version to 4.1.3

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by henning-schild** [comment]
@stickz i ended up with 4.1.3 4.1 had issues, i guess those are known because they seem fixed

**Comment by henning-schild** [comment]
@stickz the merge of this might take weeks, reply here in case there are more hotfixes and i should use another tag

**Comment by stickz** [comment]
> @stickz i ended up with 4.1.3 4.1 had issues, i guess those are known because they seem fixed

Yes agreed `v4.1.3` release should be shipped. I plan to restructure the ruTorrent project to offer long term support for `v4.1`. There are too many regressions being introduced by minor releases. I strongly believe aligning our versioning system closer to that of the Linux Kernel, will allow ruTorrent to become stable on Linux distributions. More point releases will be beneficial.

> @stickz the merge of this might take weeks, reply here in case there are more hotfixes and i should use another tag

There are no new hot fixes at this moment in time. Any future point releases for `v4.1` should be shipped separately. We're dropping support for `v4` due to the old rolling release cycle. It will never become truly stable due to https://github.com/Novik/ruTorrent/issues/2495.

**Comment by stickz** [comment]
After `v4.1` is pushed to upstream, I strongly believe we should install all the required dependencies. `ruTorrent` was never intended to be a standalone web application. It uses many different packages shipped with Gentoo Linux for it's plugin modules.

The user can decide which functionality they wish to disable from the web application. However, they shouldn't have to install all the packages manually to make it work. This is like installing `GCC` and requiring manual installation of all the compile features.

**Comment by ceamac** [comment]
@henning-schild please add yourself to maintainers if you want, I am not using rutorrent so I only did basic checks (installed and started with php 8.1, seems to run, the tests are not accessible from the browser).  It's better to have a maintainer that actively uses it.

Thank you!

**Comment by henning-schild** [comment]
@ceamac note that i am not a dev and other packages where i am maintainer i am proxied

So i would not know if i needed to add myself and proxy-maint and if i should keep web-apps in that case.

Maybe you can tell me that and suggest a concrete change, or even open an MR where i ack your change adding me in whichever way.

**Comment by ceamac** [comment]
Just add
```
<maintainer type="person" proxied="yes">
	<email>your email</email>
	<name>your name</name>
</maintainer>
```

You can be proxied by anyone, not only by proxy-maint.  In this case it will be web-apps.

**Comment by ceamac** [comment]
Sorry, I see you added it already.  It's ok, I'll fix it when merging.  Thanks!

**Comment by henning-schild** [comment]
Yes i decided to put a patch to have a discussion base and some code for you to possibly modify. Which i see worked great. Thanks.

**Comment by henning-schild** [comment]
Yes i decided to put a patch to have a discussion base and some code for you to possibly modify. Which i see worked great. Thanks.

**Pull request closed without merging**
