### PR TITLE
sys-apps/bleachbit: version bump

### PR DESCRIPTION
**Pull request by tietzc**
Gentoo-Bug: https://bugs.gentoo.org/530188

Since sys-apps/bleachbit has been lacking maintenance, I would like to proxy-maintain this package in order to keep it more up to date in the tree.

This is basically the bleachbit-1.9.1.ebuild in portage. I merely bumped EAPI and dropped a fix for an issue which has been solved upstream in the meantime.

For reference, I am also proxy-maintainer of app-editors/gummi.

### CODE REVIEW

**Comment by monsieurp** [comment]
@dastergon

**Comment by monsieurp** [comment]
Ok @dastergon is AWOL. @tietzc could you kindly provide a build log to prove that the version bump indeed works? Please attach it to the bug and CC me in so that I get an email notification. Thanks.

**Comment by tietzc** [comment]
Done. I have pushed a second commit to add en_CA to PLOCALES.

**Comment by tietzc** [comment]
Looks like things got messed up when I pushed the second commit from my then outdated branch. I attempted to bring it back in sync, but have no idea if I did it correctly. After all we have 3 commits now.

**Comment by monsieurp** [comment]
Oh noes :disappointed: ... You've merged master back into this PR ..... We can't merge it anymore. Please file another one.

**Pull request closed without merging**
