### PR TITLE
media-tv/plex-media-server: add 1.32.3.7162

### PR DESCRIPTION
**Pull request by joecool1029**
will be adding a commit to drop old too.

### CODE REVIEW

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Couldn't merge the 2nd commit, it will drop stable keywords from the package.

**Comment by joecool1029** [comment]
Isn't there already a stable keyworded release? This is the older of the two.

**Comment by juippis** [comment]
Why are you asking when you can check it out? :)
https://packages.gentoo.org/packages/media-tv/plex-media-server

or

**equery y plex-media-server** on a system freshly synced.

So yeah, the only stabilized packages were dropped with that commit. I noticed it with **pkgdev scan --commits** which you should after committing but before pushing to a branch.

**Comment by joecool1029** [comment]
Couldn't check at that moment because was about to fall asleep and answered on my phone.

I manually checked that there were 2 stables before dropping the oldest, I meant to drop the oldest unstable, just picked the wrong one. I'll use those utilities in the future instead of just ripgrepping and manually picking. I'll open a new stabilization bug and a new PR to drop olds.

**Pull request closed without merging**
