### PR TITLE
Cleanup packages broken by >=OpenSSL-1.1

### PR DESCRIPTION
**Pull request by a17r**
(please ack)

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
ACK for app-crypt/johntheripper
ACK for net-wireless/crda

**Comment by Whissi** [comment]
ACK for sys-block/partimage

**Comment by gyakovlev** [comment]
ACK app-admin/conserver

**Comment by aidecoe** [comment]
dev-erlang/fast_tls: @aidecoe
dev-erlang/p1_utils: @aidecoe

ok

**Comment by haubi** [comment]
ACK for net-misc/mico

**Comment by mgorny** [comment]
Feel free to prune anything @gentoo/python. Expect some nested trouble though.

**Comment by candrews** [comment]
ACK for media-video/rtmpdump

**Pull request closed without merging**
