### PR TITLE
dev-lua/lua-cjson Correct library path

### PR DESCRIPTION
**Pull request by gringus**
Closes: https://bugs.gentoo.org/909417

### CODE REVIEW

**Review by ConiKost — CHANGES_REQUESTED** [review]
Thank you for spotting. Change looks good, but please revbump.

**Comment by gringus** [comment]
@ConiKost Do you want me to keep the old ebuild?

**Comment by ConiKost** [comment]
No, you drop old one.

**Comment by gringus** [comment]
Done

**Review by ConiKost — APPROVED** [review]

**Pull request closed without merging**
