### PR TITLE
acct-{group, user}/gatling: Fix OutsideRangeAccountIdentifier

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Review by SoapGentoo — CHANGES_REQUESTED** [review]
revbump

**Comment by jsmolic** [comment]
> revbump

Done

**Comment by hartwork** [comment]
@jsmolic @SoapGentoo please enlighten me why 500 is a problem. I didn't get any warning and the eclass didn't prohibit 500 either. Thanks!

**Comment by SoapGentoo** [comment]
https://projects.gentoo.org/qa/policy-guide/user-group.html#pg0901
_The range 101..499 is provided for regular use by packages. The assignments from this range follow the following rules_

**Comment by hartwork** [comment]
@SoapGentoo thanks! I'm wondering: Any ideas where to find `uid-gid.txt`? Any ideas why the eclasses do no check for <=500? How can I enable warning `OutsideRangeAccountIdentifier` for myself? Thanks in advance!

**Comment by SoapGentoo** [comment]
1. it's checked by `pkgcore`, not repoman (because repoman is a lost cause)
2. https://gitweb.gentoo.org/data/api.git/tree/files/uid-gid.txt
3. on the eclass: that's a good point, and I don't currently know why we aren't prohibting that in the eclass

**Pull request closed without merging**
