### PR TITLE
dev-db/mariadb: add 10.3.36/10.4.26/10.5.17/10.6.10

### PR DESCRIPTION
**Pull request by hydrapolic**
No changes to the ebuilds, tests pass on amd64.

### CODE REVIEW

**Comment by hydrapolic** [comment]
Tested 10.3, 10.4, 10.5 on real servers, seems like they are doing fine.

**Comment by arkamar** [comment]
Thanks!

**Comment by hydrapolic** [comment]
Thanks @thesamesam

**Comment by hydrapolic** [comment]
Can we take a look at https://github.com/gentoo/gentoo/pull/26517 please?

**Comment by thesamesam** [comment]
of course, sorry I'd missed it

**Pull request closed without merging**
