### PR TITLE
kde-frameworks/kdoctools: fix build with latest cmake master

### PR DESCRIPTION
**Pull request by MatthewGentoo**
Signed-off-by: Matthew Smith <matthew@gentoo.org>

### CODE REVIEW

**Comment by a17r** [comment]
Thanks!

Does it really require revbump? As far as I can see the change is not reflected in install image.

**Comment by MatthewGentoo** [comment]
Ah yep, no rev bump required. Have amended :)

**Comment by a17r** [comment]
Thanks for your quick fix! I've subscribed upstream and will wait for it to be accepted there. In the meantime you are invited to also fix 5.96.0 and pick the fix to kde overlay, unless you think there might be a chance for upstream to request changes still.

**Review by a17r — APPROVED** [review]

**Review by a17r — CHANGES_REQUESTED** [review]
Looks like a filename typo there.

**Comment by MatthewGentoo** [comment]
Fixed in cmake, kdoctools no longer needs patching: https://gitlab.kitware.com/cmake/cmake/-/merge_requests/7680

**Pull request closed without merging**
