### PR TITLE
dev-libs/elfutils: revbump to disable thread safety by default

### PR DESCRIPTION
**Pull request by hhoffstaette**
Closes: https://bugs.gentoo.org/868402
Signed-off-by: Holger Hoffstätte holger@applied-asynchrony.com

### CODE REVIEW

**Comment by hhoffstaette** [comment]
The configure script says:
```
  NOT RECOMMENDED FEATURES (should all be no)
    Experimental thread safety         : yes
```
however since we have IUSE="+threads" we enable it unconditionally anyway, which just makes sense.

**Comment by thesamesam** [comment]
> The configure script says:
> 
> ```
>   NOT RECOMMENDED FEATURES (should all be no)
>     Experimental thread safety         : yes
> ```
> 
> however since we had IUSE="+threads" we enable it unconditionally anyway, which just makes sense.

I think this is a sign to not do that. The flag is masked in some profiles anyway. We need to be careful to look out for stuff like this.

**Comment by hhoffstaette** [comment]
> I think this is a sign to not do that. The flag is masked in some profiles anyway. We need to be careful to look out for stuff like this.

That's why I pasted the note. I guess you would prefer that we **dis**able threading support then?

**Comment by thesamesam** [comment]
Yep, definitely:
```
$ grep -rsin "elfutils"
base/package.use.mask:660:dev-libs/elfutils threads
default/linux/musl/package.mask:10:# dev-libs/elfutils needs a port to musl, bug #602126
default/linux/musl/package.mask:11:dev-libs/elfutils
```

It's masked everywhere, so we should certainly hard-disable it (and keep a note in the ebuild about it).

**Comment by hhoffstaette** [comment]
> It's masked everywhere, so we should certainly hard-disable it (and keep a note in the ebuild about it).

Yeah, I just realized I completely missed the mask..my bad. Will disable and leave a breadcrumb.

**Comment by thesamesam** [comment]
Thanks! Could you make sure to include the rationale in the commit message? (This PR and all others)

Really appreciate the help on this!

**Comment by hhoffstaette** [comment]
Now unconditionally disabled & flag removed.

$ebuild elfutils-0.187-r1.ebuild manifest clean configure
```
...
  NOT RECOMMENDED FEATURES (should all be no)
    Experimental thread safety         : no
    install elf.h                      : no
...
```

**Pull request closed without merging**
