### PR TITLE
RISC-V keyword for app-arch/*

### PR DESCRIPTION
**Pull request by wiredhikari**

### CODE REVIEW

**Comment by wiredhikari** [comment]
Could we please get this reviewed @amadio

**Review by mgorny — CHANGES_REQUESTED** [review]
CC @gentoo/qa 

I'm against merging this (and for reverting the previous merges). Overall, I feel like what we're seeing is a huge influx of `~riscv` keywords on totally random packages. Many of them will probably never be used on RISCV. Most of them probably weren't even tested correctly.

The `~riscv` keyword that was added to `app-portage/unsymlink-lib` is perhaps the best example because this package really makes zero sense on non-amd64 and if it were ever *really* tested, you would realize something's wrong.

**Comment by MatthewGentoo** [comment]
(I also think that upx will be useless on RISC-V since it doesn't have a loader stub)

**Comment by amadio** [comment]
This work is part of the GSoC project for supporting RISC-V in Gentoo prefix. After @wiredhikari managed to get a full bootstrapping procedure working on RISC-V, he's now working on adding `~riscv` to more packages in the tree by merging them with `FEATURES=test` in the RISC-V prefix environment, that's why you are seeing a stream of keyword additions for `~riscv`. This should be fine for most packages, although I agree some packages make no sense to have on RISC-V or require extra runtime testing. The first packages were chosen based on what is needed by EESSI (see https://github.com/EESSI/compatibility-layer), and after that he just tried to add the keyword to `app-arch` packages. While I agree that just trying to keyword all packages in a given category is a bit random, I don't think reverting previous merges or block merging this is warranted. I think we should just filter what doesn't make sense out, as is the example of `app-portage/unsymlink-lib`, and merge the rest or ask for more tests before merging where it makes sense (or ask for acks from the package maintainers). Going forward, I've suggested that we pick higher level packages, like gimp for example, and add keywords for that and the dependencies that get pulled with it, so that way we avoid adding keywords to random packages that don't make much sense. @mgorny What do you think?

**Pull request closed without merging**
