### PR TITLE
dev-java/bcprov - dev-java/bcpg - dev-java/bcutil - dev-java/bcpkix - dev-java/bcmail -versions 1.69 | https://bugs.gentoo.org/717950

### PR DESCRIPTION
**Pull request by vaukai**
These `ebuilds` are in an early stage and all have test failures.
However, all consumers of `dev-java/bcprov` which are [`ant-ivy-2.5.0`](https://github.com/gentoo/gentoo/pull/21197), `pdftk`, [`pdfbox-2.0.23`](https://github.com/gentoo/gentoo/pull/21139) and `net-p2p/freenet` can be compiled without errors.
https://bugs.gentoo.org/717950

Update:
How to deal with `IllegalStateException: bc.test.data.home property not set`?

Comparing the jar files with [upstream](https://www.bouncycastle.org/latest_releases.html) shows a different location of `module-info.class`.  Upstream has it in `META-INF/versions/9/`.

### CODE REVIEW

**Comment by fordfrog** [comment]
here's a patch that adds support for passing properties to `java` when running tests. set something like `JAVA_TEST_EXTRA_ARGS="-Dbc.test.data.home=\"some path\""`. please test and report back.
[java-utils-2-test-args.patch](https://github.com/gentoo/gentoo/files/6756244/java-utils-2-test-args.patch.txt)

**Comment by vaukai** [comment]
> here's a patch that adds support for passing properties to `java` when running tests. set something like `JAVA_TEST_EXTRA_ARGS="-Dbc.test.data.home=\"some path\""`. please test and report back. you'll proly need to rebase first as i fixed a typo in the eclass so the patch may not apply.
> [java-utils-2-test-args.patch](https://github.com/gentoo/gentoo/files/6756244/java-utils-2-test-args.patch.txt)

Glad about 99 test failures in `bcprov` compared to 251 before.
Will `JAVA_TEST_EXTRA_ARGS` be an array so that one could - if needed - put several extra args?

Thanks for this great patch

**Comment by fordfrog** [comment]
i can change it to an array though atm you can specify more than one too, just by `JAVA_TEST_EXTRA_ARGS="-Dvar1=val1 -Dvar2=val2"`. maybe the array version would be better though.

**Comment by fordfrog** [comment]
here's the updated patch. can you please test it before i commit it?
[java-utils-2-test-args.patch](https://github.com/gentoo/gentoo/files/6756928/java-utils-2-test-args.patch.txt)

**Comment by vaukai** [comment]
> here's the updated patch. can you please test it before i commit it?
> [java-utils-2-test-args.patch](https://github.com/gentoo/gentoo/files/6756928/java-utils-2-test-args.patch.txt)

Seems ok here [build.log.gz](https://github.com/gentoo/gentoo/files/6757890/build.log.gz)

**Comment by vaukai** [comment]
How many lives does this have? 
```
Time: 354.957
There was 1 failure:
1) testJCE(org.bouncycastle.jce.provider.test.SimpleTestTest)
junit.framework.AssertionFailedError: index 29 KeyStore: Exception: java.security.KeyStoreException: BKS-V1 not found
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.TestCase.fail(TestCase.java:223)
        at org.bouncycastle.jce.provider.test.SimpleTestTest.testJCE(SimpleTestTest.java:26)

FAILURES!!!
Tests run: 609,  Failures: 1
```
Impossible to exclude it from the tests?
```
JAVA_TEST_EXCLUDES=(
    # releasenotes.html
    # The old BKS-V1 format keystore is now disabled by default. If you need to use BKS-V1 for legacy reasons, it can be re-enabled ...
    "org.bouncycastle.jce.provider.test.SimpleTestTest"
    "org.bouncycastle.jce.provider.test.SimpleTestTest.testJCE"
```

**Comment by fordfrog** [comment]
here's a patch for selecting tests that should only be run, the rest of the tests will be ignored. it's `JAVA_TEST_RUN_ONLY=(...)`. please test when you get to it, no hurry :-)
[java-pkg-simple-test-run-only.patch](https://github.com/gentoo/gentoo/files/6758882/java-pkg-simple-test-run-only.patch.txt)

**Comment by vaukai** [comment]
> here's a patch for selecting tests that should only be run, the rest of the tests will be ignored. it's `JAVA_TEST_RUN_ONLY=(...)`. please test when you get to it, no hurry :-)
> [java-pkg-simple-test-run-only.patch](https://github.com/gentoo/gentoo/files/6758882/java-pkg-simple-test-run-only.patch.txt)

According to the output it seems to run **only the very first** `AllTests` from the list:
```
>>> Source compiled.
>>> Test phase: dev-java/bcprov-1.69
debug: java-pkg-simple_getclasspath: entering function, parameters: 
debug: java-pkg_getjars: entering function, parameters: --build-only --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: CLASSPATH=target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg-simple_prepend_resources: entering function, parameters: target/test-classes src/test/resources
debug: ejavac: entering function, parameters: -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
debug: java-pkg_get-javac: entering function, parameters: 
debug: java-pkg_init-compiler_: entering function, parameters: 
debug: Read "" from /etc/java-config-2/build/compilers.conf
debug: java-pkg_javac-args: entering function, parameters: 
debug: want source: 1.8
debug: want target: 1.8
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
debug: ejunit4: entering function, parameters: -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests
debug: ejunit_: entering function, parameters: junit-4 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests
debug: java-pkg_getjars: entering function, parameters: --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: Calling: java -cp "target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar" -Djava.io.tmpdir="/var/tmp/portage/dev-java/bcprov-1.69/temp" -Djava.awt.headless=true -Dbc.test.data.home=/var/tmp/portage/dev-java/bcprov-1.69/work/bc-java-r1rv69/prov/../core/src/test/data org.junit.runner.JUnitCore org.bouncycastle.crypto.agreement.test.AllTests
JUnit version 4.13.2-SNAPSHOT
..............
Time: 0.174

OK (14 tests)

>>> Completed testing dev-java/bcprov-1.69
```
But any of these can pass by commenting out all above it:
```
JAVA_TEST_RUN_ONLY=(
    # Tests selection according to 
    # https://github.com/bcgit/bc-java/blob/273f09ff3c0842254b61bb8b6afab4246f356731/ant/bc%2B-build.xml#L994-L999
#   "org.bouncycastle.asn1.test.AllTests"   # goes to dev-java/bcutil
    "org.bouncycastle.crypto.agreement.test.AllTests"   # OK (14 tests)
    "org.bouncycastle.crypto.ec.test.AllTests"  # OK (1 test)
    "org.bouncycastle.crypto.prng.test.AllTests" # OK (1 test)
    "org.bouncycastle.jcajce.provider.test.AllTests"    # OK (29 tests)
    "org.bouncycastle.jce.provider.test.AllTests"   # OK (1 test)
    "org.bouncycastle.jce.provider.test.nist.AllTests"  # OK (283 tests)
    "org.bouncycastle.jce.provider.test.rsa3.AllTests"  # OK (11 tests)
    "org.bouncycastle.pqc.jcajce.provider.test.AllTests"    # OK (89 tests)
    "org.bouncycastle.util.encoders.test.AllTests"  # OK (15 tests)
```

Looking forward to an update showing all the `OK (xxx tests)`. It's very promising so far

**Comment by fordfrog** [comment]
my bad, thanks for catching this. here's the update: 
[java-pkg-simple-test-run-only.patch](https://github.com/gentoo/gentoo/files/6759867/java-pkg-simple-test-run-only.patch.txt)

**Comment by vaukai** [comment]
> my bad, thanks for catching this. here's the update:
> [java-pkg-simple-test-run-only.patch](https://github.com/gentoo/gentoo/files/6759867/java-pkg-simple-test-run-only.patch.txt)

Much better ...
```
>>> Test phase: dev-java/bcprov-1.69
debug: java-pkg-simple_getclasspath: entering function, parameters: 
debug: java-pkg_getjars: entering function, parameters: --build-only --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: CLASSPATH=target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg-simple_prepend_resources: entering function, parameters: target/test-classes src/test/resources
debug: ejavac: entering function, parameters: -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
debug: java-pkg_get-javac: entering function, parameters: 
debug: java-pkg_init-compiler_: entering function, parameters: 
debug: Read "" from /etc/java-config-2/build/compilers.conf
debug: java-pkg_javac-args: entering function, parameters: 
debug: want source: 1.8
debug: want target: 1.8
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
debug: ejunit4: entering function, parameters: -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests org.bouncycastle.crypto.ec.test.AllTests org.bouncycastle.crypto.prng.test.AllTests org.bouncycastle.jcajce.provider.test.AllTests org.bouncycastle.jce.provider.test.AllTests org.bouncycastle.jce.provider.test.nist.AllTests org.bouncycastle.jce.provider.test.rsa3.AllTests org.bouncycastle.pqc.jcajce.provider.test.AllTests org.bouncycastle.util.encoders.test.AllTests
debug: ejunit_: entering function, parameters: junit-4 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests org.bouncycastle.crypto.ec.test.AllTests org.bouncycastle.crypto.prng.test.AllTests org.bouncycastle.jcajce.provider.test.AllTests org.bouncycastle.jce.provider.test.AllTests org.bouncycastle.jce.provider.test.nist.AllTests org.bouncycastle.jce.provider.test.rsa3.AllTests org.bouncycastle.pqc.jcajce.provider.test.AllTests org.bouncycastle.util.encoders.test.AllTests
debug: java-pkg_getjars: entering function, parameters: --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: Calling: java -cp "target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar" -Djava.io.tmpdir="/var/tmp/portage/dev-java/bcprov-1.69/temp" -Djava.awt.headless=true -Dbc.test.data.home=/var/tmp/portage/dev-java/bcprov-1.69/work/bc-java-r1rv69/prov/../core/src/test/data org.junit.runner.JUnitCore org.bouncycastle.crypto.agreement.test.AllTests
debug: org.bouncycastle.crypto.ec.test.AllTests
debug: org.bouncycastle.crypto.prng.test.AllTests
debug: org.bouncycastle.jcajce.provider.test.AllTests
debug: org.bouncycastle.jce.provider.test.AllTests
debug: org.bouncycastle.jce.provider.test.nist.AllTests
debug: org.bouncycastle.jce.provider.test.rsa3.AllTests
debug: org.bouncycastle.pqc.jcajce.provider.test.AllTests
debug: org.bouncycastle.util.encoders.test.AllTests
JUnit version 4.13.2-SNAPSHOT
............................................................................................................................................................................................................................................................................................................................................................................................................................................................
Time: 232.866

OK (444 tests)

>>> Completed testing dev-java/bcprov-1.69
```
Should I worry about remaining test failures documented [in the ebuild](https://github.com/gentoo/gentoo/pull/21479/commits/6215aed86b6429f13cb09ba93db69b24fdbb500d#diff-587335a03c8dad83cd5350570d64375ac5287e1d98c98f29a363b202551a272fR55-R199)?

**Comment by fordfrog** [comment]
you might check the referenced lines in the source code what the test is missing (for those nullpointerexception), or you can leave that for me for later.
so i'll commit the patch in a sec...

**Comment by vaukai** [comment]
> you might check the referenced lines in the source code what the test is missing (for those nullpointerexception), or you can leave that for me for later.
> so i'll commit the patch in a sec...

I'll try to fix as much I can without spending too much time and then proceed with the other ebuilds in this PR.
Thanks for the patch!

**Comment by vaukai** [comment]
That's weird. If uncommenting a test class which is not found in `JAVA_TEST_SRC_DIR`it seems to run **only that one**.
```
FAILURES!!!
Tests run: 1,  Failures: 1
```

I got to this by uncommenting this one while it was the last in the list:

```
"org.bouncycastle.asn1.util.test.AllTests"
```
And it doesn't matter if it's moved to the beginning or somewhere in the middle of the list.

```
>>> Test phase: dev-java/bcprov-1.69
debug: java-pkg-simple_getclasspath: entering function, parameters: 
debug: java-pkg_getjars: entering function, parameters: --build-only --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: CLASSPATH=target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg-simple_prepend_resources: entering function, parameters: target/test-classes src/test/resources
debug: ejavac: entering function, parameters: -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
debug: java-pkg_get-javac: entering function, parameters: 
debug: java-pkg_init-compiler_: entering function, parameters: 
debug: Read "" from /etc/java-config-2/build/compilers.conf
debug: java-pkg_javac-args: entering function, parameters: 
debug: want source: 1.8
debug: want target: 1.8
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
debug: ejunit4: entering function, parameters: -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests org.bouncycastle.crypto.ec.test.AllTests org.bouncycastle.crypto.prng.test.AllTests org.bouncycastle.jcajce.provider.test.AllTests org.bouncycastle.jce.provider.test.AllTests org.bouncycastle.jce.provider.test.nist.AllTests org.bouncycastle.jce.provider.test.rsa3.AllTests org.bouncycastle.pqc.jcajce.provider.test.AllTests org.bouncycastle.util.encoders.test.AllTests org.bouncycastle.crypto.test.AllTests org.bouncycastle.pqc.crypto.lms.AllTests org.bouncycastle.pqc.crypto.test.AllTests org.bouncycastle.asn1.util.test.AllTests
debug: ejunit_: entering function, parameters: junit-4 -classpath target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar org.bouncycastle.crypto.agreement.test.AllTests org.bouncycastle.crypto.ec.test.AllTests org.bouncycastle.crypto.prng.test.AllTests org.bouncycastle.jcajce.provider.test.AllTests org.bouncycastle.jce.provider.test.AllTests org.bouncycastle.jce.provider.test.nist.AllTests org.bouncycastle.jce.provider.test.rsa3.AllTests org.bouncycastle.pqc.jcajce.provider.test.AllTests org.bouncycastle.util.encoders.test.AllTests org.bouncycastle.crypto.test.AllTests org.bouncycastle.pqc.crypto.lms.AllTests org.bouncycastle.pqc.crypto.test.AllTests org.bouncycastle.asn1.util.test.AllTests
debug: java-pkg_getjars: entering function, parameters: --with-dependencies junit-4
debug: junit-4://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar
debug: java-pkg_ensure-dep: entering function, parameters: build junit-4
debug: Matching against: /junit(-4(-[^:]+)?:0|(-[^:]+)?:4)\b
debug: java-pkg_record-jar_: entering function, parameters: --build-only junit-4
debug: Calling: java -cp "target/test-classes:bcprov.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar://usr/share/junit-4/lib/junit.jar://usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar" -Djava.io.tmpdir="/var/tmp/portage/dev-java/bcprov-1.69/temp" -Djava.awt.headless=true -Dbc.test.data.home=/var/tmp/portage/dev-java/bcprov-1.69/work/bc-java-r1rv69/prov/../core/src/test/data org.junit.runner.JUnitCore org.bouncycastle.crypto.agreement.test.AllTests
debug: org.bouncycastle.crypto.ec.test.AllTests
debug: org.bouncycastle.crypto.prng.test.AllTests
debug: org.bouncycastle.jcajce.provider.test.AllTests
debug: org.bouncycastle.jce.provider.test.AllTests
debug: org.bouncycastle.jce.provider.test.nist.AllTests
debug: org.bouncycastle.jce.provider.test.rsa3.AllTests
debug: org.bouncycastle.pqc.jcajce.provider.test.AllTests
debug: org.bouncycastle.util.encoders.test.AllTests
debug: org.bouncycastle.crypto.test.AllTests
debug: org.bouncycastle.pqc.crypto.lms.AllTests
debug: org.bouncycastle.pqc.crypto.test.AllTests
debug: org.bouncycastle.asn1.util.test.AllTests
JUnit version 4.13.2-SNAPSHOT
.E
Time: 0.002
There was 1 failure:
1) initializationError(org.junit.runner.JUnitCommandLineParseResult)
java.lang.IllegalArgumentException: Could not find class [org.bouncycastle.asn1.util.test.AllTests]
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:100)
        at org.junit.runner.JUnitCommandLineParseResult.parseArgs(JUnitCommandLineParseResult.java:50)
        at org.junit.runner.JUnitCommandLineParseResult.parse(JUnitCommandLineParseResult.java:44)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:72)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
Caused by: java.lang.ClassNotFoundException: org.bouncycastle.asn1.util.test.AllTests
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
        at java.base/java.lang.Class.forName0(Native Method)
        at java.base/java.lang.Class.forName(Class.java:398)
        at org.junit.internal.Classes.getClass(Classes.java:42)
        at org.junit.internal.Classes.getClass(Classes.java:27)
        at org.junit.runner.JUnitCommandLineParseResult.parseParameters(JUnitCommandLineParseResult.java:98)
        ... 4 more

FAILURES!!!
Tests run: 1,  Failures: 1
```
Also these three `AllTests` are presently commented as they keep showing test failures (detailes documented in the ebuild).
```
#   "org.bouncycastle.crypto.test.AllTests" # Tests run: 6,  Failures: 1
#   "org.bouncycastle.pqc.crypto.lms.AllTests" # Tests run: 17,  Failures: 4
#   "org.bouncycastle.pqc.crypto.test.AllTests" # Tests run: 81,  Failures: 2
```
Could we still use `JAVA_TEST_EXCLUDES` to silence singe tests from those `AllTests`?

**Comment by vaukai** [comment]
> you might check the referenced lines in the source code what the test is missing (for those nullpointerexception), or you can leave that for me for later.
> so i'll commit the patch in a sec...

Done, all solved, no more nullpointerexceptions, all test passed

**Comment by vaukai** [comment]
Now coming to `dev-java/bcmail`.  Tests run on errors which seen related to [registries removal](https://github.com/gentoo/gentoo/commit/5b2fa22e5ffabe7b2e6c457307cd4b653ddb33e7#diff-09dba7f2568087d9d1124174781c3c3954d200f76fd78a004d01915a417765beR41-R44).
Similar was mentioned in https://github.com/eclipse-ee4j/jaf/issues/60.
```
java.lang.NoClassDefFoundError: com/sun/activation/registries/LogSupport
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.mail.smime.SMIMECompressedGenerator
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.mail.smime.SMIMEEnvelopedGenerator
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.mail.smime.SMIMESigned
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.mail.smime.SMIMESignedGenerator
java.lang.NoClassDefFoundError: Could not initialize class org.bouncycastle.mail.smime.SMIMESignedParser
```
How to solve?

**Comment by fordfrog** [comment]
well, we have only `jakarta-activation-api` package but we also need to package the implementation part separately in `jakarta-activation` and then `bcmail` needs to depend on it.

**Comment by vaukai** [comment]
with `jakarta-activation` finally all of `bcmail` `bcpg` `bcpkix` `bcprov` and `bcutil` pass their AllTests

**Comment by fordfrog** [comment]
@vaukai `dev-java/jakarta-activation` merged, thanks! i did some cleanup in 286401c631ff8ea6ae71d7272fcf56b98b42ee42.

**Comment by fordfrog** [comment]
@vaukai `dev-java/bcprov` merged, well done, thanks! :-)

**Comment by fordfrog** [comment]
@vaukai `dev-java/bcpg` merged, thanks!

**Comment by fordfrog** [comment]
@vaukai `dev-java/bcutil` merged, thanks!

**Comment by fordfrog** [comment]
@vaukai `dev-java/bcpkix` merged, thanks!

**Comment by fordfrog** [comment]
@vaukai `dev-java/bcmail` merged too, well done, thank you! :-) now you can rebase other prs that include these packages.

**Pull request closed without merging**
