### PR TITLE
mongodb: bump to 4.2.15/4.4.8/5.0.2

### PR DESCRIPTION
**Pull request by hydrapolic**
Compiles and runs on ~amd64.

Thank you

### CODE REVIEW

**Comment by ultrabug** [comment]
build okay, thanks!

**Comment by hydrapolic** [comment]
Thanks @ultrabug.

I was wondering - how about adding mongodb-bin?

**Comment by ultrabug** [comment]
> I was wondering - how about adding mongodb-bin?

I'm not too keen on adding yet another ebuild tbh, I'm slacking enough already

**Comment by hydrapolic** [comment]
I meant it as a replacement.

**Comment by ultrabug** [comment]
hmm, I'm not the best person to ask anymore I'm afraid, what's the problems this move would solve in your opinion?

**Comment by hydrapolic** [comment]
Faster bumping / testing / installation, more aligned with upstream. Sure, it has it's downsides like optional deps or that it's impossible to make changes to the code.

**Comment by ultrabug** [comment]
Yeah seeing the history of this package I'd rather keep it from source on Gentoo

**Pull request closed without merging**
