### PR TITLE
media-libs/openexr: add 3.1.6

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/901201

### CODE REVIEW

**Comment by waebbl** [comment]
v3.1.7 has just been released

**Comment by waebbl** [comment]
v3.1.6 introduced intrinsics for neon on armv8 (aarch64) machines, [see Release notes](https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.1.6).
I suppose, adding `cpu_flags_arm_{neon,v8}` and passing an appropriate cmake option could do the thing. However, I don't have access to a proper machine to test the build. If adding this is desired, I'd be happy if someone could determine the details needed to add this support and test it.

**Review by juippis — APPROVED** [review]
Let someone with arm give the specifics :)

**Comment by waebbl** [comment]
Thanks for merging! :+1: 
If the need arises, a bug can be opened.

**Pull request closed without merging**
