### PR TITLE
Import some ebuilds from the muscraft overlay

### PR DESCRIPTION
**Pull request by suhr**
Merge some ebulds from the [muscraft](https://github.com/suhr/muscraft) overlay.

media-sound/mixxx: update to 2.0.0
media-sound/carla: new ebuild
media-sound/jack-audio-connection-kit: add jack2

JACK2 uses slot `2` and conflicts with `jack:0`. Is this fine or I should use subsloting instead?

### CODE REVIEW

**Comment by suhr** [comment]
Hm, dev-libs/efl is broken for some reason. But I didn't touch it at all.

**Comment by monsieurp** [comment]
Hello and thanks a lot for your PR. A couple of things need to be addressed before we can move onto the next stage:
- We need to be able to trace every newly added package and every commit affecting a package in the tree. Could you split each commit separately?
- We expect commits to be formatted according to the following format:
"cat/pkg: commit message". You have to rebase / edit your commits. If this is too complicated for you or you're not familiar enough with Git, close this PR and open a new one following these guidelines.
- Adding live ebuilds (-9999) is fine as long as there is at least one version to fall back on. Why? Live ebuilds break easily and need constant caring and tweaking.
- New ebuilds must be committed along with a metadata.xml file. It must be assigned to a herd. If you don't know which herd to pick, assign it to proxy-maint and add yourself as a maintainer. Of course, you'll be maintaining the package, it goes without saying! :+1: 

Cheers

**Comment by suhr** [comment]
Ok, will split.

> It must be assigned to a herd.

Is this really required? [GLEP:67](https://wiki.gentoo.org/wiki/GLEP:67) says it's deprecated.

**Comment by suhr** [comment]
Since other ebuilds was already following GLEP:67, I'm following it too.
Probably I should register a project, but I guess it's long and complicated process.

**Comment by monsieurp** [comment]
Yes, I meant project and not herd. Sorry I'm still used to the old naming scheme. ;)

**Comment by suhr** [comment]
So, is everything fine?

**Comment by idella** [comment]
@aballier

**Comment by aballier** [comment]
nice, thanks! could you please split the addition of virtual/jack ?
maybe even a new PR just for the virtual, since I'll have to back you up and announce it on gentoo-dev

Also, don't spend too much time now adapting ebuilds to virtual/jack: it is common practice to leave some time pass (~1 week) between announcing a new virtual and actually adding it, to let people raise concerns if there are. And I wouldn't want you to have to rebase and re-do all your work because some rebase conflicts happened.

**Comment by suhr** [comment]
Oh very well, I will put ebuild adapting into an another branch.

**Comment by radhermit** [comment]
Regarding mixxx, I believe there's a bug that's further along, e.g. this one appears to be missing a patch to use system libs for certain things. Being the person that had fun of patching the build system to get mixxx back in the tree, I highly doubt upstream fixed all those issues. :smile:

**Comment by suhr** [comment]
@radhermit I'll try to actually run it. What exactly didn't work without patching?

**Comment by suhr** [comment]
Added `jack` flag to media-sound/mixxx.

**Comment by suhr** [comment]
Looks like I've broken the metadata somehow.

**Comment by aballier** [comment]
btw, email announcing the virtual sent to gentoo-dev

**Comment by suhr** [comment]
Any news here?

**Comment by monsieurp** [comment]
@aballier Can you sign off on merging this PR please? Cheers!

**Comment by aballier** [comment]
well, as I said, I've sent the email to gentoo-dev for adding the virtual; we need to wait a few more days before adding it, then I'll merge the virtual and jack2 ebuild

**Comment by radhermit** [comment]
^ I'm pretty sure that's why there are failing QA checks. Clearly I should improve the error messages in that situation. :smile:

**Comment by aballier** [comment]
okey, so I've merged media-sound/jack2 and virtual/jack, thanks!

Now, we need to convert packages to use virtual/jack. For this, I think it is better to test each of them with jack2, and make a PR per package so that the respective maintainers can merge it. No need to do them all at once, go progressively: it is better to get it right.


For mixxx & carla: could you please rebase this PR (with the changes I've commented) so that it can be merged ?

**Comment by suhr** [comment]
r?

**Comment by aballier** [comment]
sorry, i was about to merge it but found some issues in mixxx ebuild :/

**Comment by monsieurp** [comment]
@aballier hi! what's holding the merge?

**Comment by aballier** [comment]
this:

> sorry, i was about to merge it but found some issues in mixxx ebuild :/

**Comment by monsieurp** [comment]
ping?

**Comment by monsieurp** [comment]
pong.

Feel free to reopen if you still want to see this PR through.

**Pull request closed without merging**
