### PR TITLE
net-wireless/yatebts: remove eutils, use eapply, remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

With this PR i try to cleanup the ebuild a bit.
Since both ebuilds are at EAPI 6 we can use eapply and remove the eutils eclass.
I also updated one patch, since configure would fail with eapply otherwise.
Also use https instead of http.

There are also 2 unused patch with this package, which would be addressed in https://github.com/gentoo/gentoo/pull/7230 ;)

Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
I've put the patches into the PATCHES var. Also squashed all commits to one single one.

**Comment by mm1ke** [comment]
just rebased this PR, any chance for a merge? :)

**Comment by mm1ke** [comment]
another rebase, any chance for a merge? :)

**Comment by a17r** [comment]
question is, do @gentoo/radio people look at github?

**Comment by mm1ke** [comment]
Well, i'll give it another 2 weeks or so before opening a bug :/

**Pull request closed without merging**
