### PR TITLE
app-editors/vscod*: version bump to 1.64.2

### PR DESCRIPTION
**Pull request by AdelKS**
@arthurzam

### CODE REVIEW

**Review by arthurzam — CHANGES_REQUESTED** [review]
Please update the copyright header at the new added ebuilds, into `1999-2022`

**Comment by AdelKS** [comment]
Will do, give me a minute!

**Comment by AdelKS** [comment]
Done!

**Comment by arthurzam** [comment]
Thanks for fast response - looks good.
Just to be safe, I will wait for CI to pass, and then merge.

**Pull request closed without merging**
