### PR TITLE
app-editors/tea: add 62.1.1

### PR DESCRIPTION
**Pull request by parona-source**
Closes: https://bugs.gentoo.org/830654
Bug: https://bugs.gentoo.org/917587

### CODE REVIEW

**Comment by xgqt** [comment]
QT Team, @parona-source, is is possible to also rename the older version of this package to `tea-qt`?

see: https://bugs.gentoo.org/917587

**Comment by parona-source** [comment]
Well modifying it would require a revision bump and therefore dropped stable keywords. So I'd personally wait for the new version to be stable keyworded and then drop the old version.

**Comment by xgqt** [comment]
> Well modifying it would require a revision bump and therefore dropped stable keywords. So I'd personally wait for the new version to be stable keyworded and then drop the old version.

I do not see it as a very important change, so I think we will have to revbump but keep kwds. Unless Im missing something, but I do not think users will launch this app from terminal, would they? (only then this might come as a surprise, but then why we are not issuing a `einfo` about the change :P)

**Comment by parona-source** [comment]
https://bugs.gentoo.org/917587 should be only closed once old app-editors/tea is removed from the tree.

**Pull request closed without merging**
