### PR TITLE
sys-cluster/teleport: remove v2.4.2 v2.4.5 v2.5.2 v2.5.6, add v2.5.8 v2.6.7

### PR DESCRIPTION
**Pull request by gclawes**
Resubmission, old PR was #8658 

* remove v2.4.2 v2.4.5 v2.5.2 v2.5.6
* add v2.5.8 v2.6.0 

New 2.6.6 release: https://github.com/gravitational/teleport/releases/tag/v2.6.6

Teleport v2.5.8 contains important security update (https://github.com/gravitational/teleport/releases/tag/v2.5.8).  Remove all previous v2.5.* versions.

Teleport v2.4.* is deprecated

Includes recommendations (inherit changes, remove golang DEPEND) from un-merged #8658

### CODE REVIEW

**Comment by mgorny** [comment]
Ping.

**Comment by gclawes** [comment]
Fixed.  Sorry for the delay.  I also changed v2.6.6 to v2.6.7 to include a recent bugfix: https://github.com/gravitational/teleport/releases/tag/v2.6.7.

**Comment by mgorny** [comment]
Note for the future: when eclasses support EAPI 7, you should be able to replace `RESTRICT=strip` with `estrip` to disable stripping only on the executable needing it.

**Comment by mgorny** [comment]
That said, looks good, builds good, thanks!

**Pull request closed without merging**
