### PR TITLE
java-pkg-2.eclass: deprecate functions which depend on java-ant-2.eclass, remove unused for commons.apache.org packages

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog ci complains about `DeprecatedEclassFunction` but there was a similar commit deprecating [tc-ld-disable-gold](https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/toolchain-funcs.eclass?id=65060aed1078b800684e8d39f2dcfac6acd7cf99) with even more such ci complaints.

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
i merged the removal of javacc.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
@vaukai what's approved is merged. what's the status of the eclass changes?

**Comment by vaukai** [comment]
> @vaukai what's approved is merged. what's the status of the eclass changes?

@fordfrog thanks for merging. 
the eclass changes were sent to ML on `2024-08-24 14:47` and no comment so far. from my point of view they're ready to merge.
those [New issues caused by PR](https://github.com/gentoo/gentoo/pull/38203#issuecomment-2308881718), there are `amap,` `cxprolog,` `mythtv` and `smtinterpol` handled in https://github.com/gentoo/gentoo/pull/37468,

**Pull request closed without merging**
