### PR TITLE
dev-python/pyftpdlib: bump to 1.5.4, drop unsupported pypy{,3}

### PR DESCRIPTION
**Pull request by sbraz**
I had to pass `--force` because pysendfile isn't keyworded on some archs. I dropped pypy and pypy3 because tests fail on these and upstream doesn't officially support them.
https://github.com/giampaolo/pyftpdlib/compare/release-1.5.3...release-1.5.4

Some of the dependencies are now required to run the tests:
```diff
--- pyftpdlib-1.5.3.ebuild      2018-04-28 18:04:14.483510669 +0200
+++ pyftpdlib-1.5.4.ebuild      2018-05-12 16:24:25.976209443 +0200
@@ -2,7 +2,7 @@
 # Distributed under the terms of the GNU General Public License v2

 EAPI=6
-PYTHON_COMPAT=( python{2_7,3_{4,5,6}} pypy{,3} )
+PYTHON_COMPAT=( python{2_7,3_{4,5,6}} )
 PYTHON_REQ_USE="ssl(+)"

 inherit distutils-r1
@@ -24,6 +24,9 @@
        test? (
                ${RDEPEND}
                dev-python/mock[${PYTHON_USEDEP}]
+               dev-python/psutil[${PYTHON_USEDEP}]
+               dev-python/pyopenssl[${PYTHON_USEDEP}]
+               dev-python/pysendfile[${PYTHON_USEDEP}]
        )
 "

```

### CODE REVIEW

**Comment by mgorny** [comment]
1. You need to drop keywords, and open a rekeywording bug once this is merged.
2. Did you check whether any revdeps need pypy?

**Comment by sbraz** [comment]
Do we really need all arches to support this test dependency?
The only revdep is dev-vcs/bzr which only supports py2.7.

**Comment by mgorny** [comment]
We let the arch teams decide if they want to rekeyword it or not.

**Comment by sbraz** [comment]
@mgorny repushed without the unsupported arches:
```
  KEYWORDS.dropped              1
   dev-python/pyftpdlib/pyftpdlib-1.5.4.ebuild: alpha amd64-fbsd arm arm64 ia64 ppc ppc64
```

**Comment by sbraz** [comment]
Just noticed I forgot to DEPEND on sphinx, I'll repush with the fixed ebuild.

**Comment by sbraz** [comment]
Repushed with the proper sphinx deps. This should be good to go.

**Pull request closed without merging**
