### PR TITLE
net-im/telegram-desktop-bin: Version bump to 1.2.0 + Cleanup

### PR DESCRIPTION
**Pull request by henning-schild**
@NP-Hardass

### CODE REVIEW

**Comment by Vfrol2011** [comment]
Related Gentoo bug: https://bugs.gentoo.org/640630

**Comment by rykbrown** [comment]
Pull request looks good to me. Maintainer, please merge ASAP.

**Comment by gavv** [comment]
Just tested it, LGTM.

**Comment by alexishutin88** [comment]
Who can merge this pull request today?

**Comment by henning-schild** [comment]
@alexishutin88 and @rykbrown if you want to use that ASAP or today, go ahead and pull it to your own portage-tree. Spamming here with accounts that where created for just that purpose will probably not speed up the process.

**Pull request closed without merging**
