### PR TITLE
dev-util/{bakefile,codeblocks}: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from dev-util/bakefile and dev-util/codeblocks.
Both packages are part of the **gentoo/wxwidgets** project.

@leio @dirtyepic 
Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
ping. just rebased my PR. :)

**Comment by mm1ke** [comment]
ping, just another rebase of my PR :)

**Comment by dirtyepic** [comment]
I will get to this, I'm just between laptops at the moment and don't have a dev environment set up yet.

**Comment by mm1ke** [comment]
ping, another rebase :)

**Comment by kensington** [comment]
Thanks, picked as 97299fcf41506a869c9a265a2c5e819e4d4b76b5...c57d92c7c443593c89d2033abe2dc9a3b7431d91.

**Pull request closed without merging**
