### PR TITLE
 net-im/signal-desktop-bin: bump version 1.15.4

### PR DESCRIPTION
**Pull request by robert7k**
Closes: https://bugs.gentoo.org/663002

### CODE REVIEW

**Comment by mgorny** [comment]
Are we really permitted to redistribute their files?

**Comment by mgorny** [comment]
Or to be more specific, why is bindist restricted?

**Comment by robert7k** [comment]
I guess I just put it there when I wrote the initial version of the ebuild, because other binary ebuilds had it. I can't remember doing it on purpose.

**Comment by mgorny** [comment]
Then please remove both.

**Comment by robert7k** [comment]
Done

**Comment by sbraz** [comment]
You need to bump to 1.15.4 now, 1.15.3 is already gone :/

**Comment by robert7k** [comment]
Updated to 1.15.4.

**Comment by perfinion** [comment]
merged, thanks!

**Pull request closed without merging**
