### PR TITLE
Make Neutral cursors great again in Gentoo

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by wraeth** [comment]
Thanks @Coacher, this looks good at first glance. I should have this pushed for you shortly.

@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Definitely :+1:

**Comment by monsieurp** [comment]
The current x11-themes/xcursor-neutral ebuild is a disgrace btw.. Thanks @Coacher for cleaning it up.

**Pull request closed without merging**
