### PR TITLE
x11-misc/slop: fix icu build

### PR DESCRIPTION
**Pull request by N-R-K**
Bug: https://bugs.gentoo.org/933863

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Probably you should just bump the C++ standard used?

**Comment by thesamesam** [comment]
Ping, just do what Eli said?

**Comment by N-R-K** [comment]
> Ping, just do what Eli said?

I will try patching the standard, but it could take me a while before I can get back to this.

**Comment by N-R-K** [comment]
Ping. This should work I think.

**Pull request closed without merging**
