### PR TITLE
Remove last-rited pkgs

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by juippis** [comment]
I know zookeeper said "in ~30 days", but was not in a hurry to not wait at least 30 days...

**Comment by jsmolic** [comment]
@juippis Ah, I see. Is there any interest for returning the package in the tree?

**Comment by juippis** [comment]
@jsmolic nope and it's been dead for too long. I added the `:(` to jokingly indicate I was looking forward to personally removing it (hadn't forgotten!), as I do very little of "my own stuff" outside project work in Gentoo.

As removing the package is easy work, performing the last-rite procedure is the tedious process.

The main thing is that it's gone now, along with other apparently forgotten last-rite removals. 👍

**Comment by jsmolic** [comment]
Okay perfect :)

**Pull request closed without merging**
