### PR TITLE
app-emulation/xen: add upstream patches

### PR DESCRIPTION
**Pull request by hydrapolic**
Adding recent patches from:
https://xenbits.xen.org/gitweb/?p=xen.git;a=shortlog;h=refs/heads/staging-4.12
https://xenbits.xen.org/gitweb/?p=xen.git;a=shortlog;h=refs/heads/staging-4.13

It should fix the credit2 instability issue too.

Thanks!

### CODE REVIEW

**Comment by thesamesam** [comment]
Could you ensure this contains patches for this [bug](https://bugs.gentoo.org/717446)?

**Comment by hydrapolic** [comment]
No, the new patches were added just a few minutes ago. Please don't merge this PR and I'll refresh the PR with new patches fixing the recent XSAs.

**Comment by thesamesam** [comment]
Thanks for that - I didn't think so but given the timing it seemed sensible to check. Let us know when you're ready.

**Comment by hydrapolic** [comment]
@thesamesam patches fixing recent CVEs added

**Comment by hydrapolic** [comment]
Thanks @dlan17

**Pull request closed without merging**
