### PR TITLE
dev-lang/python: port to EAPI 7

### PR DESCRIPTION
**Pull request by hanetzer**
Without the features of EAPI 7, an armv7a-hardfloat-linux-gnueabi
toolchain from crossdev cannot emerge python, as it cannot find the
host's autotools packages.

The new patchset tarballs are included in this pr; whoever thinks to merge
this can stuff these into the/a devspace and remove them from the commit
prior to pushing; older versions can use these tarballs without issue, so we
can cut down on used space in the cloud. Dropped the old sys-libs/db from
ebuilds to satisfy repoman, as they no longer exist.

Package-Manager: Portage-2.3.36, Repoman-2.3.9

### CODE REVIEW

**Comment by hanetzer** [comment]
Put a hold on this; I can do away with the eshopt stuff, but I need to sleep.

**Comment by floppym** [comment]
Using EAPI 7 for system packages this soon is a bit tricky. We will need to be careful not to remove older ebuilds to accommodate a stable upgrade path for at least one year.

**Comment by mgorny** [comment]
Not to mention we won't be able to stabilize it until Portage goes stable.

**Comment by hanetzer** [comment]
True, but for those doing unstable things on unstable portage are likely very up to date,
and those out of date won't be able to install this python with their old portage anyway
(masked by EAPI), so if we keep at least one relatively old eapi in each slot this should be
safe.

**Comment by mgorny** [comment]
…unless a vulnerability is found, upstream makes a security release and we need pull back to EAPI 6 to stabilize this release

**Comment by floppym** [comment]
My suggestion would be for you to maintain an overlay of packages you need to cross-compile for now. I will be happy to accept an EAPI 7 conversion around a year from now.

**Pull request closed without merging**
