### PR TITLE
dev-ml/lablgtk: revbump 2.18.8, EAPI-7, fix CI issue, restore KEYWORDS

### PR DESCRIPTION
**Pull request by juippis**
- bump EAPI-7, 
 - drop findlib.eclass, 
 - drop multilib.eclass, 
 - fix DeprecatedInsinto CI issue,
 - restore KEYWORDS from lablgtk-2.18.5.ebuild, 
 - rework 'examples' logic to obey small-files QA policy, 
 - sort dependencies, 
 - sort ebuild global variables to follow default skel, 
 - sort IUSE, 
 - use BDEPEND, 
 - use DOCS array, 
 - use econf array.

@zx2c4

### CODE REVIEW

**Comment by juippis** [comment]
> I'm not super hip on ocaml ebuilds, but looks fine.

You seem to be using this program, so I wanted someone to runtime-test it correctly. I built-tested and tested that the binaries work, but no idea how to actually use this program properly.

> 
> Why drop findlib?

I looked at the eclass and it's horribly outdated. It doesn't meet the modern QA requirements, so I thought to handle whatever it was needed for in the ebuild. It should work similarily...

**Comment by juippis** [comment]
I added this, 
```
	if use examples; then
		dodoc -r examples/
		docompress -x /usr/share/doc/${PF}/examples
	fi
```

And did `lablgtk2 /usr/share/doc/lablgtk-2.18.8-r1/examples/*.ml` and it seems to work fine. I'll update the ebuild and push sometime today.

**Comment by zx2c4** [comment]
I just tested this against coq and it seems to work. Thanks for fixing this.

**Comment by juippis** [comment]
Thanks for testing! I'm trying to reduce the CI reports to get these Github PRs working again.

**Pull request closed without merging**
