### PR TITLE
app-misc/resolve-march-native: Add ~alpha keyword

### PR DESCRIPTION
**Pull request by maquis196**
Signed-off-by: maquis196 <chris@maytownsend.co.uk>

### CODE REVIEW

**Comment by mattst88** [comment]
I'm confused. gcc on alpha doesn't support `-march=`. What would this tool do on alpha?

**Comment by maquis196** [comment]
ah, admittedly, I didn't know that. 

in the guide https://wiki.gentoo.org/wiki/Safe_CFLAGS#Determining_CPU_type_in_order_to_set_CFLAGS_manually

There is a small section that either says "use -march=native" or run the tool in the OP to suggest your setting. 

The tool confirmed I was using "-mcpu=pca56" properly, so possibly some value if someone stumbles on that guide in the future on this platform? happy closing this otherwise.

**Comment by hartwork** [comment]
@maquis196 sounds like it does work on alpha then. I believe the usual process would be to file a bug requesting keywording for alpha with keyword `KEYWORDREQ` under `Keywording` in Bugzilla (https://devmanual.gentoo.org/keywording/index.html#keywording-new-packages). I think I can dare cherry-picking it this time.

PS: The commit message and sign-of line were broken, please take a look.

**Comment by hartwork** [comment]
@maquis196 de-facto merged, thank you! :+1:

**Pull request closed without merging**
