### PR TITLE
Fix copyright years

### PR DESCRIPTION
**Pull request by hasufell**
@gentoo/reviewers haha... review xD

### CODE REVIEW

**Comment by hasufell** [comment]
```
git show 0cbd2d80a63baa62f8fd4ff98ab17746b62b1429 | grep '^\+' | grep -v '+++' | grep -v '+# Copyright 1999-2015 Gentoo Foundation'
```
shows zero hits, so it looks safe

**Comment by aballier** [comment]
not sure it is correct to do it like that: I think copyright year should be '(project birth year) - (last year file has been modified)'; that's why we had echangelog/repoman update changed files.

OTOH I've seen other projects do that kind of sedding at the beginning of january each year :p

**Comment by hasufell** [comment]
> not sure it is correct to do it like that: I think copyright year should be '(project birth year) - (last year file has been modified)'; that's why we had echangelog/repoman update changed files.

If I sed those ebuilds, then they _have_ been modified.

**Comment by aballier** [comment]
IANAL, you're right, but this sounds a bit too much biting its own tail

**Comment by hasufell** [comment]
I started this, because your ebuilds had incorrect copyright year. I'm not going to write another script to figure out who wants his ebuild copyright year fixed.

**Comment by mgorny** [comment]
Wrong! If the file wasn't updated, then you wouldn't sed it, so it wouldn't be updated this year ;-P. OTOH all files were modified thanks to $Header$ -> $Id$, so I don't hink it really matters.

**Comment by mgorny** [comment]
@ulm, what's your opinion about this?

**Comment by hasufell** [comment]
> @ulm, what's your opinion about this?

I don't think he uses github actively. I'll probably have to send the diff to him via mail xD

**Comment by ulm** [comment]
So far we use the date of each individual file's last modification as the end year in the file's header (and I don't think that an automatically expanded line like $Header$ or $Id$ counts here).

We could argue that the whole tree is a single project, because certainly ebuilds are not independent of each other (think of *DEPEND or eclasses) and use the date of last change of the tree instead. However, this isn't something that could be done ad-hoc, but will require prior discussion in mailing lists and/or a trustees' decision.

So -1 from me, please don't merge this.

**Comment by mgorny** [comment]
@hasufell, I know you love our mailing lists. Would you like to start the discussion? I think it would fit for -project ml.

**Comment by hasufell** [comment]
more bikeshedding... it will probably require council approval!

Let's do it this way: I don't care, but will keep telling people about broken copyright post-commit, whether repoman is fixed or not.

**Comment by tamiko** [comment]
> whether repoman is fixed or not.

The last time "I checked" (*cough*) it worked.

**Pull request closed without merging**
