### PR TITLE
x11-misc/gpaste: drop 3.14, bump 3.16.3.1, 3.18.3

### PR DESCRIPTION
**Pull request by lkraav**
`gpaste-3.18.3.ebuild` bumps dependencies to `gnome-3.18` level.

There is also `gpaste-3.20'release already, but it'll have to wait until `gnome-3.20` hits the tree.

I'm also not sure why we still have `gnome-base/gnome-3.14.0` ebuild sitting in the tree, but it's not directly related to this PR.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/gnome

**Comment by monsieurp** [comment]
Actually this package should be maintained by a former dev which has walked away from the project. @lkraav do you want to take over maintainership?

**Comment by lkraav** [comment]
@monsieurp in theory, yes I can. Depends on what exactly "maintainership" entails.

**Comment by monsieurp** [comment]
First off, you need a Bugzilla account. Maintaining a package is fairly straightforward: if the package needs bumping or security bugs are filed, it is your responsibility to look after the ebuild and either file a PR and/or a bug with a diff attached. You are also in charge of stabilising the package, should it needs stabilisation. That's pretty much it.

**Comment by monsieurp** [comment]
More info here: https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers#Getting_Started

**Comment by monsieurp** [comment]
Oh and we'll be assisting you along the process of course :) but you seem to be comfortable already with GH and Gentoo.

**Comment by lkraav** [comment]
Yup, I've been gentooing for more than a decade now, but making time for some public package maintainership has only become possible after git era started.

> It is also possible to create a pull request at Gentoo's GitHub mirror instead of filing a bug. 

Well, this settles it, I'm good to go. Who is the package assignment god? Where do I see a complete list of all packages which is sortable / filterable by assigned people etc?

**Comment by monsieurp** [comment]
I'm part of the proxy maintainer team and I'll grant your maintainership after merging this PR. As for a list of searchable bugs, have you taken a look at https://bugs.gentoo.org/ ?

**Comment by lkraav** [comment]
> I'm part of the proxy maintainer team and I'll grant your maintainership after merging this PR. As for a list of searchable bugs, have you taken a look at https://bugs.gentoo.org/ ?

Not sure what bugzilla has to do with the original question. I'd like to perform a query against a username, which lists the packages that particular person maintains. Do we have such a web frontend? https://packages.gentoo.org doesn't seem to have filtering by maintainer.

**Comment by monsieurp** [comment]
I wasn't sure about what you meant. Yes, we've got such a tool: http://euscan.gentooexperimental.org/maintainers/monsieurp@gentoo.org/ for instance.

**Comment by monsieurp** [comment]
Maintainership granted in 579b55a12de9ca39ec30f14b5b3ff59f6fa1c6f6. Thanks!

**Comment by lkraav** [comment]
> I wasn't sure about what you meant. Yes, we've got such a tool: http://euscan.gentooexperimental.org/maintainers/monsieurp@gentoo.org/ for instance.

Super nice! (y) For some reson the /feed/ links throw a 500 error though.

I also see ` Last scan: April 9, 2016, 6:32 a.m. (6 days, 15 hours ago)`, how often does this refresh?

**Comment by monsieurp** [comment]
Hmm.. @patricklauer looks after this website. I honestly don't know. :disappointed: Gotta ask him.

**Pull request closed without merging**
