### PR TITLE
media-plugins/mythplugins: Remove oauth2 dependency

### PR DESCRIPTION
**Pull request by thebitpit**
Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Wilson Michaels <thebitpit@austincustomerrands.com>

### CODE REVIEW

**Comment by thebitpit** [comment]
Remove oauth2 dependency from mythnetvision option as it has been blocked from building by upstream for the mythplugins versions in gentoo. It has been fixed on the upstream master, but not yet released. This revision is done to help with dev-python/oauth2 clean up.

**Comment by sbraz** [comment]
Hi, thanks for the PR. I still don't really understand why `oauth2` would have been needed as I don't see anything that would reference it [here](https://github.com/MythTV/mythtv/search?q=oauth2).

I don't like the idea that we are dropping a dependency that might be needed if that plugin is fixed. If you confirm that even if the plugin is fixed, this dependency is not really required (as I was thinking), I will merge this.

**Comment by sbraz** [comment]
Hi @thebitpit did you see my previous message?

**Comment by thebitpit** [comment]
> Hi @thebitpit did you see my previous message?

Yes! I guess I failed to hit the Comment button. I am sure it no longer needs oauth2 and the version in portage builds without it.

**Pull request closed without merging**
