### PR TITLE
dev-util/kcov: fix test failures

### PR DESCRIPTION
**Pull request by beatussum**
These changes do not affect the installed program.

Close: https://bugs.gentoo.org/937314
Close: https://bugs.gentoo.org/937315

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
If the patch solely fixes test failures _that were issues in the tests_, not fixing some general code which affected the tests, there's no need to revbump.

Also, please make the commit summary more descriptive ("revbump" -> "fix tests").

**Comment by beatussum** [comment]
Done!

**Comment by beatussum** [comment]
@thesamesam ping

**Review by juippis — APPROVED** [review]
Seems ok, 
```
Ran 88 tests in 95.872s

OK (skipped=8, expected failures=7)
>>> Completed testing dev-util/kcov-43
```

**Pull request closed without merging**
