### PR TITLE
gstreamer packages: Security bump to version 1.16.3

### PR DESCRIPTION
**Pull request by Polynomial-C**
Bug: https://bugs.gentoo.org/765163
Package-Manager: Portage-3.0.14, Repoman-3.0.2
Signed-off-by: Lars Wendler <polynomial-c@gentoo.org>

### CODE REVIEW

**Comment by leio** [comment]
Please share the command you used to batch bump them all and what changes were done on top.
I spot an unused gst-plugins-base bashism patch on very very quick first look.

**Comment by Polynomial-C** [comment]
> Please share the command you used to batch bump them all and what changes were done on top.
> I spot an unused gst-plugins-base bashism patch on very very quick first look.

Thanks for spotting this. I thought this patch is still needed to avoid pinning `CONFIG_SHELL` to /bin/bash but I was wrong and forgot to remove the patch again after testing.
I have removed the patch and force-pushed again.

**Comment by Odelpasso** [comment]
Thanks for your work @Polynomial-C but it will be possible to push GStreamer 1.18.x after this bump ?
The 1.18.x version is needed for wine (and winegstreamer.dll.so)

**Comment by Polynomial-C** [comment]
This is not up for me to decide. The responsible Team within Gentoo seems to be unable or unwilling to work on it so I just provided the necessary security bump for QA to merge once the maintainer timeout has been reached.

**Pull request closed without merging**
