### PR TITLE
*/*: change my name and email address

### PR DESCRIPTION
**Pull request by tastytea**
my name and email address changed to: tea <`tea+gentoo@cuddleslut.fr`>

Bug: https://bugs.gentoo.org/678396

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by mattst88** [comment]
> cuddleslut.fr

Seriously?

But also, this doesn't seem to resolve.

**Comment by mattst88** [comment]
> But also, this doesn't seem to resolve.

Actually it does. Never mind.

**Comment by xgqt** [comment]
> > cuddleslut.fr
> 
> Seriously?

Hi @mattst88,

I had to face similar dilemma where a maint had `deps.tar.xz` hosted in a domain with (let's say...) inappropriate name.

Generally having this anywhere looks very unprofessional and like a joke.

**Comment by tastytea** [comment]
i wasn't aware that gentoo has professionalism requirements (and a definition of professionalism?). where can i find it?

i'd really like to avoid maintaining a second email domain just for gentoo.

**Comment by juippis** [comment]
> i wasn't aware that gentoo has professionalism requirements (and a definition of professionalism?). where can i find it?
> 

You need some sort of written document to list you what is considered distasteful? It has nothing to do with "professionalism", more with common sense. This indeed comes out as a bad joke.

> i'd really like to avoid maintaining a second email domain just for gentoo.

If that won't do, and you won't use another mail provider / mail alias, I guess we'll lose maintainer for these packages. This metadata isn't something any of us wants to push to the Gentoo tree, nor something anyone wants to find from it.

Come on.

**Comment by tastytea** [comment]
distastefulness is wildly subjective. frankly, i have no idea what the problem is and why someone would care about my email address. this is the first time someone has a problem with it. i would appreciate to be told before i register another domain. is cuddling considered distasteful or sluts? both?

**Comment by vimproved** [comment]
with all due respect i'd like to remind the devs here that we have things like `games-misc/sex` in tree with the description "Spouts silly mad-lib-style porn-like text." If Gentoo is going to start policing "distastefulness" i'd like to see it be applied consistently. Additionally, as tastytea said, distastefulness is very subjective. My existence as a transgender woman is seen as distasteful to many, so should I be barred from contributing to Gentoo?

**Comment by thesamesam** [comment]
In every dictionary I've looked at, "slut" is called "offensive". It's obviously not a professional term to be using. I wouldn't apply for a job using that.

`games-misc/sex` is a package name from like 2006. I'm not sure I'd add it today (not least because it's kind of a lame game) but it's also not a _derogatory_ term either.

> My existence as a transgender woman is seen as distasteful to many, so should I be barred from contributing to Gentoo?

Obviously not. Please don't conflate the two.

**Comment by vimproved** [comment]
> `games-misc/sex` is a package name from like 2006. I'm not sure I'd add it today (not least because it's kind of a lame game) but it's also not a _derogatory_ term either.

While slut can be used as a derogatory term, I think we've seen a significant reclaimation of the term in recent years and the context in which it is used here is clearly not in a derogatory way.

But also, in terms of dictionary definitions, the usage much more fits the second definition from dictionary.com:

> Informal. a person with a seemingly insatiable but often undiscerning desire to do or have something specified: a book slut, reading five books at once.

I do understand if the objection is on the grounds that it contains a word that is often used in a derogatory context, but that is not the same as being "distasteful." But this is also treading a fine line in my opinion. How would the terms "queer" or "autistic" be handled, for example. I'm not saying these are exactly the same but they all fall into the category of words that have both derogatory and non-derogatory usages.

I think it would be really be a shame to lose a maintainer as active and hardworking as tastytea over this.

**Comment by vimproved** [comment]
> Obviously not. Please don't conflate the two.
> 
> Suppose that were the case (which is, IMO, a ridiculous suggestion, not least because it would go against the CoC), it would be about far more than an email anyway? This doesn't make sense.

Sorry, this was a poorly made point on my part. I was trying to make a point about the use of the word "distasteful" and the potential issues that come with respectability politics, not any accusations against developers or gentoo as a whole.

**Comment by thesamesam** [comment]
I think it's best in professional contexts to avoid terms which are prone to misunderstanding and not language-lawyer. I wouldn't say "slut" to my mother, and dictionary.com's first definition says "disparaging and offensive".

It doesn't matter if the term has been reclaimed if one common interpretation is obviously offensive to many, because that's where people's minds will go. It's also, IMO, _clearly_ pushing a boundary and at least someone should acknowledge this rather than act like it's not known to be a problem. If it's the latter, it implies they're missing the problem (because many people will read it in the other sense). At least if they _know_ it's edgy, they can make some defence of it in spite of that, even if I'm unlikely to be convinced by it...

An email address is, by definition, used to communicate with _other people_, and hence avoiding misunderstanding is important. You have several people here who aren't bigots that are raising concerns here.

> How would the terms "queer" or "autistic" be handled, for example.

We're not talking about those and I wouldn't consider either of them an issue. I get the point, but I don't really know what to say about it. It's obviously different and you have to trust our judgement on it.

**Comment by tastytea** [comment]
> In every dictionary I've looked at, "slut" is called "offensive".

dictionaries are always a few years or decades behind reality. i don't think they can tell us what the current public opinions are.

> It's obviously not a professional term to be using. I wouldn't apply for a job using that.

is this a professional context? i was under the impression that gentoo is a community project.

> There are any number of things you can do in a public space which are clearly and uncontroversially unacceptable without some specific rule being written to prevent it.

having an email address with the word slut in it is not one of these things. i didn't imagine someone would be offended by that. i asked some friends and no one saw a problem, more than 15 signaled that it's not an issue.  
either me and my friends are out of touch or you 4 are. i honestly can't tell which it is.

**Comment by juippis** [comment]
> is this a professional context? i was under the impression that gentoo is a community project.
> 

> i asked some friends and no one saw a problem, more than 15 signaled that it's not an issue. either me and my friends are out of touch or you 4 are. i honestly can't tell which it is.

I surround myself with people who are similar to me, etc. But it's no use arguing this between us, we won't find resolution here. I'd suggest you open a bug addressed to council, ask **them** how they want Gentoo to be represented while justifying your stance to them. If the council sees no problem including this kind of maintainer contact metadata, then we can proceed as you originally intended. That's also the most community-based resolution we can get.

**Comment by mgorny** [comment]
Try to use some empathy. Put yourself in the body of someone who's been insulted as "slut" multiple times in their life, and then meets someone who uses this word to name themselves "for fun". It's not about dictionaries, it's about humanity. And it doesn't say anything good about you if you put so much effort into arguing that doing harmful things is acceptable if you can twist the logic hard enough.

**Comment by tastytea** [comment]
> And it doesn't say anything good about you if you put so much effort into arguing that doing harmful things is acceptable if you can twist the logic hard enough.

look. i came here to update some metadata. i get insulted. i try to find out what's wrong. i find out that we live in different realities and try to explain mine. and then you come along and blame me for trying to reach some kind of mutual understanding? can you imagine how utterly bizarre this whole process is to me?

> Try to use some empathy.

i tried to understand the problem, but the accusations have been vague. the “critics” don't seem to want to show me even a bit of empathy and assume i'm acting in bad faith.

> Put yourself in the body of someone who's been insulted as "slut" multiple times in their life, and then meets someone who uses this word to name themselves "for fun".

i know people who have been insulted as “slut” repeatedly. not one of them is offended by me calling myself “slut”, much less “cuddleslut”. i have been insulted as “faggot” and other things often, i don't mind at all that some people are calling themself that.

is anyone here actually offended by the word, or knows someone who is? or is this all conjecture? i'm getting the feeling that you are acting on an instinct here and trying to come up with reasons.

**Comment by tastytea** [comment]
i opened a bug addressed to the council here: <https://bugs.gentoo.org/937886>

**Comment by eli-schwartz** [comment]
> dictionaries are always a few years or decades behind reality. i don't think they can tell us what the current public opinions are.

However, this thread is full of people who organically believed that it's considered an insulting term. Count me among that number as well.

Within that context, consulting a dictionary constitutes supporting evidence, not the only evidence available.

In fact I haven't heard anything about it being "reclaimed"...

> While slut can be used as a derogatory term, I think we've seen a significant reclaimation of the term in recent years and the context in which it is used here is clearly not in a derogatory way.
> 
> But also, in terms of dictionary definitions, the usage much more fits the second definition from dictionary.com:

I have seen the second definition be used and not even once did I feel it was being used in a non-derogatory manner there either.

"seemingly insatiable but often undiscerning desire" is key to that definition. The principle use of the term "slut" is insulting (the desire to shame and stigmatize someone else for perceived inappropriate sexual behavior, in particular by claiming that said behavior is "a "freakishly obsessive, demeaning urge"), all that is happening here is that people take an insulting term and apply it to contexts where it isn't intrinsically applicable in order to insult people that they feel have a "freakishly obsessive, demeaning urge" even if that accused urge isn't specifically sexual in nature.

The usefulness of "slut" in the term "book slut" is a *result* of the fact that it's an insulting word, and therefore to someone that wants to insult and mock a person who has been found to be insatiably reading 5 books at once... "well hey, there's an insulting term available already that practically fits, and as a bonus it makes a sex joke".

I wouldn't use the term "book slut" because it's a term of mockery. And I'll thank no one for calling me a "book slut" either.

...

Frankly, the fact that it's seen as surprising and out of the blue that Gentoo Devs might have reservations about this, is something that leaves me with a weird feeling about the entire situation.

**Comment by juippis** [comment]
> is anyone here actually offended by the word, or knows someone who is? or is this all conjecture? i'm getting the feeling that you are acting on an instinct here and trying to come up with reasons.

If I saw my kids typing `cuddleslut` into the URL bar, I wouldn't let them press enter. I may be overly protective, but that's perhaps the "instict" you speak of. That made me think maybe we (proxy-maint) better pay attention what these custom URLs actually resolves into.


> i opened a bug addressed to the council here: https://bugs.gentoo.org/937886

Thanks! While we wait for that bug to go through whatever bureaucracy, could you revert back to your old e-mail in the bugzilla meanwhile? Currently there's a mismatch between your bugzilla and metadata info in the repo, so no bugs can be assigned to you. Essentially meaning you're unreachable, and these packages have no maintainer.

**Comment by tastytea** [comment]
> could you revert back to your old e-mail in the bugzilla meanwhile?

it looks to be impossible? maybe there is a time-limit?

screenshot_2024-08-14T09:21:50

**Comment by juippis** [comment]
A timeout makes sense indeed. I'll consider your post as consent and I'll do it for now. Let me know if you don't agree with it.

**Pull request closed without merging**
