### PR TITLE
dev-python/vdirsyncer: declare conflict with =dev-python/requests-2.11.1

### PR DESCRIPTION
**Pull request by andrey-utkin**
With this version of requests, `vdirsyncer sync` gives error:

InvalidHeader: Header value 0 must be of type str or bytes, not <type 'int'>

### CODE REVIEW

**Comment by Amynka** [comment]
seems that version bump will be more convenient according to https://github.com/pimutils/vdirsyncer/issues/522

**Comment by Amynka** [comment]
Hello, Can you please test new version bump which is now in tree vdirsyncer-0.14.0 and confirm if it solves the problem?
Thank you

**Comment by andrey-utkin** [comment]
Seems to work with vdirsyncer-0.14.0 and dev-python/requests-2.11.1. Thanks.

**Comment by Amynka** [comment]
Thank you ! :)

**Pull request closed without merging**
