### PR TITLE
x11-wm/fluxbox: Stablise -r5 for musl users + New Proxy Maintainer

### PR DESCRIPTION
**Pull request by immolo**
Been running this on my musl amd64 machine long enough to push this and dropping -r4 version as there is no need to keep both

While I run this daily I've decided I might as well look after it at the same time.

Closes: https://bugs.gentoo.org/829825

### CODE REVIEW

**Comment by a17r** [comment]
Let's add yourself as a proxy maintainer when you actually have to do any maintenance work on fluxbox? Are there bugs to fix, e.g.?

Stabilisation is done by arch teams in Gentoo.

**Comment by a17r** [comment]
You're effectively dropping `arm` stable keyword here also.

**Comment by a17r** [comment]
Besides, you are making changes here that would require individual commits each, doing it all at once would be a no-go as well.

**Comment by immolo** [comment]
> Besides, you are making changes here that would require individual commits each, doing it all at once would be a no-go as well.

Thanks for the advice here. I rushed in with this one as a good candidate for renew my ebuild skills and got ahead of myself in the process so needed the levelheaded feedback.

I'll instead look into creating a live ebuild as suggested in a bug for aiding with cherry picking patches for bugs and report the llvm compiling bug to track my progress on solving like I should have started with :)

**Pull request closed without merging**
