### PR TITLE
Add python3_8 target to many ebuilds

### PR DESCRIPTION
**Pull request by neeshy**
These are just the packages which I had to edit in order to get them to build against python 3.8.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
have you tested every package with python 3.8?

**Comment by neeshy** [comment]
> have you tested every package with python 3.8?

Yes. I currently only have python 3.8 and 2.7 on my machine. The only issue I've ran into is deluge-console outputs a warning related to gettext.

Unable to initialize gettext/locale!
'ngettext'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/deluge/i18n/util.py", line 118, in setup_translation
    builtins.__dict__['_n'] = builtins.__dict__['ngettext']
KeyError: 'ngettext'

It runs fine though. I've ran into the same issue on Arch (they've already globally switched to python 3.8), so it seems to be an upstream problem.

**Comment by neeshy** [comment]
I managed to fix the aforementioned issue via a patch in: https://github.com/gentoo/gentoo/pull/15081

**Comment by mgorny** [comment]
What we're really asking is: have you run all of them with `FEATURES=test` and had no test failures? Also could you identify which of `dev-python/*` packages are lacking tests at the moment, and whether there are tests present in the upstream repository?

**Comment by neeshy** [comment]
After emerging all of the packages in this PR with FEATURES=test, most of the packages' tests succeeded, but the following packages' tests failed:
```
dev-python/pycrypto
dev-python/numpy
dev-python/fonttools
sys-devel/gdb
sys-devel/llvm
sys-devel/clang
```
pycrypto seems to rely on an interface which was removed in python 3.8. It fails on:
```
AttributeError: module 'time' has no attribute 'clock'
```
See: https://docs.python.org/3.7/library/time.html#time.clock

And the following packages' tests seemed like they were hanging. They each ran for about an hour before I manually killed them.
```
net-libs/libtorrent-rasterbar
app-emulation/qemu
```
For many of these packages python is only a component of their build system, so I think the tests are failing due to other reasons. That being said, I haven't tried building against python 3.6 with tests, so I'm not sure.

**Comment by neeshy** [comment]
I'll remove the packages which failed from the PR.

**Comment by thesamesam** [comment]
Can you please include the signed off header?

**Comment by neeshy** [comment]
> Can you please include the signed off header?

Done

**Comment by neeshy** [comment]
I added back dev-python/fonttools and net-libs/libtorrent-rasterbar to satisfy dependencies.

**Comment by mgorny** [comment]
For packages where tests are failing, please do a comparative run with py3.7 and py3.8, and see if the same tests fail.

**Comment by neeshy** [comment]
Failed tests on python 3.7
- sys-devel/gdb
- dev-python/numpy

For me, tests were also failing when numpy 1.17 was being built against python 3.8

Successful tests on python 3.7
- dev-python/fonttools
- dev-python/pycrypto

Still hang
- net-libs/libtorrent-rasterbar
- app-emulation/qemu

Here's a relevant bug report about that: https://bugs.gentoo.org/712138

**Comment by neeshy** [comment]
Can you take another look at this? I noticed many of the ebuilds for which I had added python 3.8 compatibility in this PR were similarly addressed by @candrews. What's the hold up for the rest of the commits here?

**Comment by neeshy** [comment]
@candrews Why did you close this PR?

**Comment by candrews** [comment]
Because I merged it.

**Comment by neeshy** [comment]
Oh, thanks.

**Pull request closed without merging**
