### PR TITLE
dev-libs/uchardet: add live ebuild, remove old

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by idella** [comment]
This failed a build test since make.conf was lacking CXXFLAG -fpic. I suggest you inherot flag-o-matic and append =fpic to CXX FLAGS

**Comment by idella** [comment]
My runtest does not build it

**Comment by Coacher** [comment]
@idella, can you show me your build.log the please?

**Comment by idella** [comment]
No, it was from troubled settings on the background. It now builds

**Pull request closed without merging**
