### PR TITLE
version bump: net-libs/nodejs-5.6.0

### PR DESCRIPTION
**Pull request by jbergstroem**
A few notable changes in here, see commit message.
Not super happy about how we pass stuff to `find`. Suggestions welcome.

CC @patricklauer, @gentoo/proxy-maint.

### CODE REVIEW

**Comment by jbergstroem** [comment]
Minor nit: I didn't mean to move 5.4.1 to 5.5.0; I had a 5.4.1 in a previous branch which decided to stick around while rebasing. Happy to rebase again if you prefer.

**Comment by idella** [comment]
Patrick can do this one unless ...

**Comment by jbergstroem** [comment]
note: work in progress in its current state; i'm rewriting the IUSE=npm deletion.

**Comment by monsieurp** [comment]
@jbergstroem is it still a WIP?

**Comment by jbergstroem** [comment]
Everything merged. Closing.

**Pull request closed without merging**
