### PR TITLE
app-text/mupdf1.24.8 patch for gcc-15 compilation

### PR DESCRIPTION
**Pull request by steveo314**
patch to allow this version of mupdf to compile using gcc15

C23 removes unprototyped functions, so this conflicted with the definition in fg_init_x11.c.

Closes: https://bugs.gentoo.org/944028

---

Please check all the boxes that apply:

- [ X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [ X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [ X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [ X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please squash the merge commits and also add `Closes: https://bugs.gentoo.org/9440281` above the `Signed-off-by` line.

But you also need to fix the commit summary/message.

**Comment by thesamesam** [comment]
There's still some merge commits there and the commit message doesn't match the PR description -- I'll fix both on merging. Thanks!

**Comment by steveo314** [comment]
> There's still some merge commits there and the commit message doesn't match the PR description -- I'll fix both on merging. Thanks!

That wasn't my intention to give you extra work. This is my first Gentoo commit. I was trying to figure if i should close this PR and re do it as I was unable to squash anymore.

**Comment by thesamesam** [comment]
No problem -- check out the final version that I merged and compare with what you had. That should help with the right format. Thanks for the contribution!

**Comment by thesamesam** [comment]
BTW, you did pretty well -- the only real issue was the merges which then confused you I think (as one of the merges had the right commit message too). `git pull` unfortunately defaults to merges, not rebases, which is the main reason this happens. `git config --global pull.rebase true` should help.

**Comment by steveo314** [comment]
I am going to keep this PR handy as well. Trying to make notes on everything.

**Pull request closed without merging**
