### PR TITLE
app-admin/ngxtop: enable python 3.{7,8}

### PR DESCRIPTION
**Pull request by hydrapolic**
Works fine with python 3.8.

### CODE REVIEW

**Comment by hydrapolic** [comment]
> This doesn't resolve the first problem mention in p.mask message.

Yes it's unmaintained, but it works with the latest python, just tested.

**Comment by mgorny** [comment]
It means it doesn't have Gentoo maintainer. You can take it if you want.

**Comment by hydrapolic** [comment]
> It means it doesn't have Gentoo maintainer. You can take it if you want.

Sure, added myself as maintainer.

**Comment by hydrapolic** [comment]
Thanks @mgorny

**Comment by mgorny** [comment]
Thank you!

**Comment by oxr463** [comment]
@hydrapolic see also: https://github.com/ngxtop/ngxtop

**Comment by hydrapolic** [comment]
@oxr463 thanks didn't know about that one. So you are actively maintaining a fork?

**Comment by oxr463** [comment]
> 
> 
> @oxr463 thanks didn't know about that one. So you are actively maintaining a fork?

As of last week? Yes (😂). Working on merging all of the open PRs for the old repository now.

**Comment by hydrapolic** [comment]
Can you ping when you're done merging the PRs and I'll add a new version to Gentoo with all the patches for others to test?

**Pull request closed without merging**
