### PR TITLE
keyword ~riscv for certbot and dependencies.

### PR DESCRIPTION
**Pull request by ahmedcharles**

### CODE REVIEW

**Comment by prometheanfire** [comment]
generally ok with this, is riscv seeking to have this be marked stable soon as well?

**Comment by ahmedcharles** [comment]
I don't actually know. I'm fairly new to using gentoo, I'm just testing packages and keywording them as having been tested.

**Comment by ahmedcharles** [comment]
Merged, thanks.

**Comment by ionenwks** [comment]
> generally ok with this, is riscv seeking to have this be marked stable soon as well?

riscv is marked testing-only in arches.desc right now, so stabilization doesn't happen for anything yet

**Comment by dlan17** [comment]
> > generally ok with this, is riscv seeking to have this be marked stable soon as well?
> 
> riscv is marked testing-only in arches.desc right now, so stabilization doesn't happen for anything yet

quite right, given current status (not too many developers working on this arch, not too many packages keyworded/tested),
we'd still keep it as testing-only .. thanks

**Pull request closed without merging**
