### PR TITLE
sys-devel/bmake: Stabilize 20210314-r1; Remove few last-rited packages

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
ACK on go-usb removal, go for it

**Comment by jsmolic** [comment]
@ZeroChaos- Thanks, while you're here could you check https://github.com/gentoo/gentoo/pull/20517 as well?

**Review by SoapGentoo — APPROVED** [review]

**Comment by jsmolic** [comment]
@thesamesam wanna do this one as well? ;)

**Comment by thesamesam** [comment]
Cheeky so and so.. go on then!

**Pull request closed without merging**
