### PR TITLE
bump media-sound/picard and dev-python/python-discid

### PR DESCRIPTION
**Pull request by davidhicks**
picard v1.4 was released on 14 Feb 2017 (see: https://blog.musicbrainz.org/2017/02/14/picard-1-4-released/)

dependency python-discid v1.1.1 was released on 29 Jan 2017 (see: https://github.com/JonnyJD/python-discid/releases/tag/v1.1.1)

### CODE REVIEW

**Comment by davidhicks** [comment]
The Manifest was produced with app-portage/repoman-2.3.2, command "repoman manifest". Is this the wrong way to produce a Manifest?

**Comment by davidhicks** [comment]
https://devmanual.gentoo.org/general-concepts/manifest/ indicates that the correct behaviour is for the Manifest file to contain the digests for every file in the directory and subdirectories.

repoman -dx full doesn't report issues either.

Which is correct, the QA check bot, or the dev manual?

**Comment by djc** [comment]
The QA bot, I'm afraid. The Gentoo tree uses thin manifests, meaning that we don't include files that are in the tree, only distfiles. You probably generated your Manifest in an overlay tree and copied it over, or something?

I filed a bug against the devmanual: https://bugs.gentoo.org/show_bug.cgi?id=612482. If you regenerate the manifest from within your gentoo repository clone, the QA issue should resolve itself.

**Comment by davidhicks** [comment]
Thanks @djc, I'll resubmit new pull requests with a thin manifest.

**Pull request closed without merging**
