### PR TITLE
app-backup/restic: version bump to 0.13.1

### PR DESCRIPTION
**Pull request by Philippe23**
Just a copy of the 0.13.0 ebuild.

Closes: https://bugs.gentoo.org/839279
Closes: https://github.com/gentoo/gentoo/pull/25091
Signed-off-by: Philippe Chaintreuil <gentoo_bugs_peep@parallaxshift.com>

### CODE REVIEW

**Comment by stkw0** [comment]
Thanks. Why is this PR self-referenced in the Closes tag?

**Comment by Philippe23** [comment]
So this PR will auto-closr

> Thanks. Why is this PR self-referenced in the Closes tag?

So this PR will auto close upon commit.  I've been doing it since I was first asked to in 2019: https://github.com/gentoo/gentoo/pull/10460#issuecomment-464469163

**Comment by stkw0** [comment]
> > Thanks. Why is this PR self-referenced in the Closes tag?
> 
> So this PR will auto close upon commit. I've been doing it since I was first asked to in 2019: [#10460 (comment)](https://github.com/gentoo/gentoo/pull/10460#issuecomment-464469163)

Oh, I didn't know that. I will try to use it too, thanks :)

**Comment by juippis** [comment]
> > Thanks. Why is this PR self-referenced in the Closes tag?
> 
> So this PR will auto close upon commit. I've been doing it since I was first asked to in 2019: [#10460 (comment)](https://github.com/gentoo/gentoo/pull/10460#issuecomment-464469163)

Just so you know the tools we use to merge these PRs adds this automatically. So you don't **have** to do it on your own.

**Pull request closed without merging**
