### PR TITLE
Introduce python3.5 support

### PR DESCRIPTION
**Pull request by floppym**
@gentoo/python Please review.

### CODE REVIEW

**Comment by jlec** [comment]
Looks good so far.
There is a entry in ```base/package.use.force``` regarding ```python-exec```. Do we need to add python3_5 there as well?

**Comment by mgorny** [comment]
Yes, we do. And we need to stable-unmask it too.

**Comment by mgorny** [comment]
Please also update `app-portage/gpyutils/files/implementations.txt` :-).

**Comment by mgorny** [comment]
Hmm, didn't I mention rebasing for implemenetations update? :-P Sorry. But I guess you can proceed with it now.

**Comment by floppym** [comment]
Rebased and pushed to master as 325c7c3a3bdfff2cec519c4bfd790154d2772c85.

**Pull request closed without merging**
