### PR TITLE
blender, oiio, ocio, imath, openexr bumps

### PR DESCRIPTION
**Pull request by negril**
* Academy Software Foundation (ASWF) became host to a bunch of projects. This changed the github url and the source folder names. To avoid extra logic rename the packages to match upstream.
* Since `media-gfx/blender` makes use of a ASWF projects and had a blocker on the latest `media-libs/OpenColorIO`, this adds `3.6.4` with the backported fix from `media-gfx/blender-4.0`.
* Dropped the `static-libs` USE-flag from `media-libs/OpenColorIO` as it settting it cause the shared library not to be build.

### renamed:
- media-libs/openimageio -> media-libs/OpenImageIO
- media-libs/opencolorio -> media-libs/OpenColorIO
- media-libs/osl -> media-libs/OpenShadingLanguage
- dev-libs/imath -> dev-libs/Imath

### added:
- media-gfx/blender
  - 3.6.5
- media-libs/OpenImageIO
  - 2.4.14.0
  - 2.4.15.0
  - 2.4.16.0
  - 2.5.4.0
- dev-libs/Imath
  - 3.1.9
- media-libs/openexr
  - 3.1.11
 
### removed:
- dev-libs/Imath
  - 3.1.7
 
Closes: https://bugs.gentoo.org/907211

### CODE REVIEW

**Comment by DarthGandalf** [comment]
hi, I've noticed this PR completely accidentally, but such change in RDEPEND requires revbump of dependent packages, and you'd need to split such renaming commit by package. Also this is probably more work than keeping specifying the correct name in the imath ebuild

**Comment by thesamesam** [comment]
> hi, I've noticed this PR completely accidentally, but such change in RDEPEND requires revbump of dependent packages, and you'd need to split such renaming commit by package. Also this is probably more work than keeping specifying the correct name in the imath ebuild

You don't need to do that for renames.

**Comment by jonasstein** [comment]
Did you check, if we break overlays with the rename? If so, we should inform them first and spare the trouble for our users.

**Comment by thesamesam** [comment]
> Did you check, if we break overlays with the rename? If so, we should inform them first and spare the trouble for our users.

We don't really do that.

**Comment by thesamesam** [comment]
I've dropped the renames given they don't seem inline with our policy of strongly preferring lowercase (https://devmanual.gentoo.org/ebuild-writing/file-format/index.html). We could maybe still expand 'osl' though.

**Pull request closed without merging**
