### PR TITLE
 sys-devel/autoconf-2.69-r3: add support for runstatedir

### PR DESCRIPTION
**Pull request by candrews**
Backported from autoconf 2.70

https://bugs.gentoo.org/show_bug.cgi?id=589248

### CODE REVIEW

**Comment by mgorny** [comment]
This sounds like a very bad idea. You're intentionally diverging from upstream for no real benefit.

If a configure script relies on this, it will need to require at least autoconf 2.70. Therefore, it will reject Gentoo 2.69 anyway.

If a configure script originates from Gentoo, people will mistakenly put 2.69 and have it break everywhere else.

**Comment by candrews** [comment]
Configure scripts can be written defensively to use runstatedir only if it's available. For example:
* zfsonlinux: https://github.com/zfsonlinux/zfs/blob/master/config/user-runstatedir.m4 )
* connman: http://connman.connman.narkive.com/IJvnGf3r/rfc-2-5-build-use-runstatedir-instead-of-deriving-it-from-localstatedir
* krb5: https://github.com/krb5/krb5/blob/master/src/configure.in#L3

and more

Also, if hyper conservative Debian can include this patch and thinks it's a good idea, that seems to indicate that it probably is okay.

**Comment by mgorny** [comment]
Gentoo is more conservative than Debian these days. Though both often get harm enough due to thoughtlessness of developers who care for nothing but testing their whims.

**Comment by mgorny** [comment]
@gentoo/base-system

**Comment by robbat2** [comment]
@mgorny The other day for work stuff, I came across a configure.ac that didn't realize this macro was so new, and was mysteriously failing,  so I'm in favor of including it, just marking that it's backported 2.70 (it would help if upstream autoconf actually made a release as it's been many years).

**Comment by candrews** [comment]
I tried to get autoconf to make a release, but it doesn't look good. @robbat2 perhaps you could offer to assist them in doing so? 

Here's the thread where I requested the release: https://lists.gnu.org/archive/html/autoconf/2016-07/msg00011.html

**Comment by robbat2** [comment]
@candrews Ha, free time to do so, not like that exists. I would echo Julien's request on the list to release 2.70 as-is and get the remaining patches ready for the next release (more frequent releases also help testing).

**Comment by candrews** [comment]
@robbat2 I suggest you reply to the list and say that. :-)

**Comment by SoapGentoo** [comment]
@candrews I'm generally opposed to backporting this. This shifts the blame from upstream GNU to us, and I'd much rather pressure them into releasing 2.70.

**Comment by SoapGentoo** [comment]
@candrews I'm closing this, as we're not going to merge this. Let's try and get upstream to finally release a new Autoconf version.

**Pull request closed without merging**
