### PR TITLE
app-office/texstudio & dev-dotnet/xsp: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patch from app-office/texstudio (which slip through in https://github.com/gentoo/gentoo/pull/1876/commits/79e73bfedf14b341c4348d2ee8776087ef8ec725) and also removes a unused patch in dev-dotnet/xsp.
Please review.

### CODE REVIEW

**Comment by gktrk** [comment]
@mrueg

**Comment by mm1ke** [comment]
Any chance we can merge this?

**Comment by monsieurp** [comment]
Please rebase against master and I'll merge it.

**Comment by mm1ke** [comment]
@monsieurp 
Just rebased my PR. Should be fine now :)

**Pull request closed without merging**
