### PR TITLE
eclasses: Add missing '|| die' on pushd/popd

### PR DESCRIPTION
**Pull request by hasufell**
Don't merge this. It might even break the tree and needs review.

### CODE REVIEW

**Comment by hasufell** [comment]
* java eclasses: @chewi 
* haskell eclasses: @trofi 

You can also just cherry-pick what looks right for you. Not sure if it makes sense to send this to dev ML.

**Comment by trofi** [comment]
Cherry-picked haskell-cabal.eclass as: https://github.com/gentoo/gentoo/commit/45dd7b77d48f80c2f778b8d9b2b448d3776d3cf8

Thanks!

**Comment by hasufell** [comment]
@trofi what about `darcs.eclass`?

**Comment by trofi** [comment]
Looks fine as well. Cherry-picked darcs.eclass as: https://github.com/gentoo/gentoo/commit/bc41a427792ca39c2986befe964380aa1a951cba

**Comment by hasufell** [comment]
@graaff can you take a look at the commit for ruby eclasses?

**Comment by mgorny** [comment]
As past x11 member, I'm telling ya xorg-2 looks fine. Please commit ;-P.

**Comment by monsieurp** [comment]
AFAICS, the two commits concerning the java eclasses look good. @chewi, what do you think?

Also, not speaking on behalf of @akhuettel but the change affecting the perl eclass LGTM as well.

**Comment by chewi** [comment]
Yeah, I'm happy.

**Comment by hasufell** [comment]
java eclasses cherry-picked a413cb15f841e85c2800cb68321d1d0c7d791039 67a6620144235b427852f93ca030b38651a43024

**Comment by hasufell** [comment]
Please review and cherry-pick the related commits, don't merge the whole PR:
* [autotools](https://github.com/hasufell/gentoo/commit/8658efd02ac7dbaaedee637d1d11ec88ff594973)/[toolchain](https://github.com/hasufell/gentoo/commit/65a1b7c1659299ff14a2250f966d4cedd6b6f1e1)/[toolchain-funcs](https://github.com/hasufell/gentoo/commit/c1144c3767649f42a60986eb8de6127ec1d31576)/[base](https://github.com/hasufell/gentoo/commit/eb174f08e8243f5c95e692f61ee58e675268ff04)/[libtool](https://github.com/hasufell/gentoo/commit/bc4c001f20485626c7aa3b67bd0aa2eb0be3b38c)/[savedconfig](https://github.com/hasufell/gentoo/commit/65d18313f6f532274bf9a6229a27b89ec56f738d).eclass: @gentoo/base-system 
* [bzr.eclass](https://github.com/hasufell/gentoo/commit/9ed1063a655c7c16a092f719e4a56ecffc1135a3): @jmbsvicetto 
* [cmake-utils.eclass](https://github.com/hasufell/gentoo/commit/65c05cd2435ba21c9edab69344373b85cf2bd129): @scarabeusiv @reavertm 
* [font.eclass](https://github.com/hasufell/gentoo/commit/cb65042ef56e027b5bcf5eebf884335277217cd0): @gentoo/fonts 
* [gnatbuild.eclass](https://github.com/hasufell/gentoo/commit/69a990b8625bb80551c780833f42226517cc8881): @sarnold 
* [gnome2-utils.eclass](https://github.com/hasufell/gentoo/commit/8640f8cf3813967298dfb8b5a94c487089a8985b): @gentoo/gnome 
* [intel-sdp.eclass](https://github.com/hasufell/gentoo/commit/e13bc38e0268e9ec8d8c0eee5760db5aa4595178): @jlec 
* [kde4-functions](https://github.com/hasufell/gentoo/commit/229066fce6825c8754ab2d3e14dbe1f1a5023b08)/[kde4-meta](https://github.com/hasufell/gentoo/commit/2b9b9ccd91ab2e56e34c26fd9dc1dc53e0328858)/[kde5](https://github.com/hasufell/gentoo/commit/61cc15e3b2c1b3583074e6046be6b9dc03d9313a).eclass: @gentoo/kde 
* [kernel-2.eclass](https://github.com/hasufell/gentoo/commit/62e8c6b60f7c4ba86ae21fc63c9fd1920da56d0f): @robbat2 
* [l10n.eclass](https://github.com/hasufell/gentoo/commit/38b4f6766eb8dbee6c668835c27a0067dfb5005d): @yngwin 
* [mercurial.eclass](https://github.com/hasufell/gentoo/commit/2ffb3f85c1d71ffcea0d25a1c37b98fd717cc1b8): @djc 
* [mysql-multilib](https://github.com/hasufell/gentoo/commit/5b5a4e90aedbc93531b0018332998da87fdd01f4)/[mysql-v2](https://github.com/hasufell/gentoo/commit/c64bdd4ccafb1536c77cf70d1933837b0502a80a)/[mysql_fx](https://github.com/hasufell/gentoo/commit/32c20b0c28548524a4fb256293ba5ae1f2693783).eclass: @robbat2 @jmbsvicetto @grknight 
* [office-ext-r1.eclass](https://github.com/hasufell/gentoo/commit/4baf5abb7487f5904276b99a298bd83b7f8176f0): @gentoo/openoffice 
* [perl-module.eclass](https://github.com/hasufell/gentoo/commit/2a6037f186913e55e3f1efb64e1ef74f8c696753): @gentoo/perl 
* [ruby-fakegem](https://github.com/hasufell/gentoo/commit/5db28b9d74cdd8c3c54901d58625e510b527c8fc)/[ruby-ng](https://github.com/hasufell/gentoo/commit/c01a563dcf482bfb7b0e205493b5272dd2c4df16).eclass: @gentoo/ruby 
* [subversion.eclass](https://github.com/hasufell/gentoo/commit/e678aa7fdb843535c3a5434f71200ea0d6c4975b): @hattya 
* [x-modular.eclass](https://github.com/hasufell/gentoo/commit/5f1fd8fbdb60b17f3bab022444e43bbcb1542346): @gentoo/x11 
* [xemacs-elisp-common.eclass](https://github.com/hasufell/gentoo/commit/e19099a6f9b034ab9cdb193bb7dfbdf79a6374d1): @graaff

**Comment by graaff** [comment]
ruby eclasses look fine to me.

For xemacs you need matsl, not sure if he has a github account. In any case those look fine as well.

**Comment by kensington** [comment]
cmake-utils done in 51c366676fb2b2292a85accce933f228f3a9b5c0

**Comment by kensington** [comment]
* kde4-functions - b047be9d2ec0f55138f75d7eb950707a9f28f0dd
* kde4-meta - d308bf4fdf801e965c9ee2312f14adb366086aa2
* kde5 - 3b6b9d43fb1ecdd7eb61fa86d041afa5e7d9e892 (was already baking in the overlay)

**Comment by jlec** [comment]
> * intel-sdp.eclass: @jlec 

looks good.

**Comment by djc** [comment]
2ffb3f85c1d71ffcea0d25a1c37b98fd717cc1b8 looks fine to me, but I'm not really the maintainer, anyway. Better ask @junghans.

**Comment by monsieurp** [comment]
There's no need to keep this PR open and in fact, we can close it. Teams interested in merging/cherry-picking commits from this PR can still do so even if the PR in question is closed. Let's move on.

**Pull request closed without merging**
