### PR TITLE
net-wireless/broadcom-sta: Various fixes

### PR DESCRIPTION
**Pull request by sarnex**
Hi,

I have fixed two bugs in this PR, and added myself as the proxy co-maintainer. I emailed the maintainer on Feb 3 with no response, so I believe they are unavailable. Please review.
Thanks,
Sarnex

### CODE REVIEW

**Comment by sarnex** [comment]
I guess I will manually tag @gentoo/proxy-maint

**Comment by EvaSDK** [comment]
I have this hardware so I'll try to get to testing your changes.

**Comment by matoro** [comment]
Thank you so much for volunteering to take over this.  My card is not supported by `b43` so it would suck having this pulled from the portage tree.  If there is any hardware testing you need done I can help as well.

**Comment by sarnex** [comment]
@EvaSDK Have you had a chance to take a look at this? If we don't get some fixes in the package will be removed.

Thanks,
Sarnex

**Pull request closed without merging**
