### PR TITLE
QGIS and kodi-19 cleanup

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Please provide a better title and a description of what this is about.

**Comment by a17r** [comment]
I'm not sure what could be misunderstood about it.

**Comment by hhoffstaette** [comment]
Sorry, I didn't recognize the user name - it looked like a random drive-by. :zany_face:

**Comment by a17r** [comment]
> Sorry, I didn't recognize the user name - it looked like a random drive-by. 🤪

In a way, it was, as I didn't expect most of the pinged package maintainers to respond, out of experience.

As the rolling phase of this PR has come to an end, let's use it to put some users on notice, i.e. comply with your initial request. ;)

**Comment by mfld-fr** [comment]
Is this drop a good thing to do at this time, as version 124 is known to break the off / reset functions of the Xfce power manager, while version 123 works fine ?

**Comment by a17r** [comment]
> Is this drop a good thing to do at this time, as version 124 is known to break the off / reset functions of the Xfce power manager, while version 123 works fine ?

If people are not responding to the bug, we need to assume it is fixed.

**Comment by mfld-fr** [comment]
Just spotted the question in the related bug... please let me a few hours
to test and answer...

**Comment by mfld-fr** [comment]
See https://bugs.gentoo.org/934314: just tested with the suggested versions, it does not solve the problem. So I am afraid you should keep polkit-123 for now as it is the only way to workaround the problem.

**Comment by thesamesam** [comment]
@mfld-fr I've posted bisect instructions at https://bugs.gentoo.org/934314#c12. Please give them a try.

**Comment by mfld-fr** [comment]
@thesamesam : OK, starting to bisect... please be patient, as I am using my PC to work at the same time and such bisecting requires to reboot on each try...

**Comment by mfld-fr** [comment]
@thesamesam : bisect completed, see https://bugs.gentoo.org/934314

**Pull request merged**
