### PR TITLE
dev-util/lxqt-build-tools: new package

### PR DESCRIPTION
**Pull request by rndevfx**

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Thanks for your contribution. Two things:
* we use thin Manifests in the main repository and your contribution does not.
* do you want to maintain this package yourself? if not, did you talk to the lxqt team? either way, you've got to file a bug at https://bugs.gentoo.org.

**Comment by monsieurp** [comment]
ping?

**Comment by rndevfx** [comment]
Hi @monsieurp - sorry for delay; vacation time 🎉 

I created a new bug report for this: https://bugs.gentoo.org/show_bug.cgi?id=604344
This package should be maintained by the LXQt-team because it's related to many other LXQt-applications

**Comment by rndevfx** [comment]
Created thin Manifest

**Pull request closed without merging**
