### PR TITLE
sys-block/targetcli-fb, dev-python/configshell-fb: new packages

### PR DESCRIPTION
**Pull request by diogocp**
targetcli-fb and configshell-fb are forks of targetcli and configshell maintained by Red Hat.

Gentoo-Bug: [590714](https://bugs.gentoo.org/590714)
Gentoo-Bug: [590722](https://bugs.gentoo.org/590722)

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/python, @alexxy, @bircoph, @jsbronder, @mschiff, @prometheanfire, @ultrabug, @Xarthisius.

Is the original configshell maintained? Is there a value in having both? I can see having two forks being at least a bit confusing.

**Comment by diogocp** [comment]
The fb versions do seem to be better maintained. They also support Python 3, unlike the original.

We already have dev-python/rtslib-fb in Gentoo, so it would make sense to also include the other two fb packages (configshell-fb and targetcli-fb).

**Comment by bircoph** [comment]
One of Gentoo's best features is support of multiple choices. If both forks work (which is yes in this case), we should support both and let users to choose.

**Comment by mgorny** [comment]
Well, `dev-python/rtslib` is -9999 only, so it's pretty much useless as a dependency. Treecleaning it would probably be fine.

**Comment by mgorny** [comment]
Same goes for `dev-python/configshell`.

**Comment by bircoph** [comment]
> Well, dev-python/rtslib is -9999 only, so it's pretty much useless as a dependency. Treecleaning it would probably be fine.

Original targetcli and rtslib are still rather active and used by many people. But ebuilds are indeed outdated (though they still work).

**Comment by diogocp** [comment]
Should I merge #2043 (targetcli-fb) into this PR, seeing as the two packages go hand in hand?

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Pull request closed without merging**
