### PR TITLE
media-gfx/imv: added missing deps for the test phase

### PR DESCRIPTION
**Pull request by Hummer12007**
CC @gentoo/proxy-maint

### CODE REVIEW

**Comment by monsieurp** [comment]
I'm not quite sure testing a live package makes sense.

**Comment by monsieurp** [comment]
Please provide a rationale as to why a live package needs testing. IMO live packages are too prone to fail to compile in the first place so testing them should be the least of our worries.

**Comment by mgorny** [comment]
@monsieurp, please don't close valid pull requests just because you don't care for live packages. They are packages as good as any, and there is no reason not to fix bugs like missing dependencies. Especially that the maintainer may use the live ebuild to write a release ebuild afterwards, and the test dependencies will be useful information to him.

**Comment by mgorny** [comment]
@Hummer12007, is this a new dep or does the current release version ebuild miss them as well? If the latter, please update it too.

**Comment by monsieurp** [comment]
The PR is valid. The rationale isn't provided. ;) Anyway, it's yours now.

**Comment by Hummer12007** [comment]
@mgorny, changes necessary for the tests to link correctly had only been recently been shipped into the upstream, but are yet to be released. So tests are restricted for the current version, but still work on the live ebuild. I was waiting for the release, but @gktrk asked me to make the change. I can put the pr on hold for the time being (until the new version gets released).

**Comment by gktrk** [comment]
@Hummer12007 given the upstream's aperiodic release schedule and that there haven't been many commits to warrant a new release, I will merge this. I also suggest to fix the test deps for 2.1.2 too even though it is test restricted: We don't have to remember adding them in the next bump, we'll simply remove the test restriction. I can squash the 2.1.2 fix on top of this locally before pushing it to the tree unless you insist on doing the work and updating this PR.

**Pull request closed without merging**
