### PR TITLE
dev-libs/imath: bump to 3.1.1

### PR DESCRIPTION
**Pull request by waebbl**
Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by waebbl** [comment]
updated KEYWORDS from the changes in 3.0.5

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
dev-libs/imath
  DroppedKeywords: version 3.1.1: mips

Let me know if this was a mistake, or if there was some reason for it. I'll add it back if it belong here.

**Comment by juippis** [comment]
Apparently it was keyworded after this PR was opened, I'll add it back.

**Comment by waebbl** [comment]
@juippis Thanks for adding the ~mips keyword, which was just added yesterday.

**Pull request closed without merging**
