### PR TITLE
media-libs/assimp: add 5.2.4

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/846698
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
CMP: media-libs/assimp-5.2.3/image with media-libs/assimp-5.2.4/image
   ABI: libassimp.so.5(64) func(+2,-1) [BREAKING]
------> ABI(+2,-1,>B<)
```
that's a bit worrying o.O

**Comment by waebbl** [comment]
Do we have more information on what is causing the breakage? How can we handle this? Do we need to add slot operator to revdeps?
The release page doesn't mention any breaking changes. I can ask upstream about this, but I think, a little more information would be helpful.

**Comment by juippis** [comment]
You can run the abidiff directly to see what functions have changed:
```
# abidiff assimp-5.2.3/image/usr/lib64/libassimp.so assimp-5.2.4/image/usr/lib64/libassimp.so
Functions changes summary: 0 Removed, 0 Changed, 0 Added function
Variables changes summary: 0 Removed, 0 Changed, 0 Added variable
Function symbols changes summary: 1 Removed, 2 Added function symbols not referenced by debug info
Variable symbols changes summary: 0 Removed, 0 Added variable symbol not referenced by debug info

1 Removed function symbol not referenced by debug info:

  [D] TextureTypeToString

2 Added function symbols not referenced by debug info:

  [A] _ZN6Assimp6Logger4warnIJRA22_KcRmRA11_S2_RNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEERA50_S2_EEEvDpOT_
  [A] aiTextureTypeToString

```
I don't know whether any revdep uses these functions, but there's a chance they do. Then we'd need to add a subslot to assimp, and indeed update its revdeps with subslot binders against assimp.

**Comment by waebbl** [comment]
```
$ equery d -a media-libs/assimp
 * These packages depend on media-libs/assimp:
dev-games/ogre-1.12.9-r1 (assimp ? media-libs/assimp)
dev-qt/qt3d-5.15.3 (>=media-libs/assimp-4.0.0)
dev-qt/qt3d-5.15.4 (>=media-libs/assimp-4.0.0)
dev-qt/qt3d-5.15.4.9999 (>=media-libs/assimp-4.0.0)
(::qt) dev-qt/qtquick3d-6.3.0 (media-libs/assimp)
(::qt) dev-qt/qtquick3d-6.3.9999 (media-libs/assimp)
(::qt) dev-qt/qtquick3d-6.9999 (media-libs/assimp)
dev-ros/collada_urdf-1.12.13-r1 (media-libs/assimp)
dev-ros/collada_urdf-9999 (media-libs/assimp)
dev-ros/geometric_shapes-0.7.3 (media-libs/assimp)
dev-ros/geometric_shapes-9999 (media-libs/assimp)
dev-ros/rviz-1.14.14 (media-libs/assimp)
dev-ros/rviz-9999 (media-libs/assimp)
games-fps/doomsday-2.1.1-r1 (media-libs/assimp)
games-fps/doomsday-2.3.0 (media-libs/assimp)
(::waebbl) media-libs/vsgXchange-9999 (assimp ? media-libs/assimp)
(::guru) sci-libs/dart-6.12.1-r2 (>=media-libs/assimp-3.0.0)
sci-libs/dealii-9.3.1-r4 (assimp ? media-libs/assimp)
sci-libs/dealii-9.3.3 (assimp ? media-libs/assimp)
sci-libs/dealii-9999 (assimp ? media-libs/assimp)
```

The list includes files outside of ::gentoo, i.e. vsgXchange from my overlay, qtquick3d from ::qt and dart from ::guru. Repo annotations through me.

**Comment by waebbl** [comment]
Is it even necessary to inform upstream about the ABI breakage? As long as there's no API change at the same time, increasing the patch version would be ok, and it's only a distro internal issue, isn't it?

**Comment by juippis** [comment]
Well, if you have good relations, you could ask / inform them about it yes. This is not **as** critical to binary distros as it is to source-based ones, since with binary distros a single packager can deal with it - but we have to cater for **all** of our users with different setups. And yes it still does **can** affect everyone shipping assimp. But again, I don't know whether these functions are ever used by consumers of this library, or if they're just some internal things.

I don't understand increasing "patch version" - do you mean revbumping consumers while adding `media-libs/assimp:=` dep? That's what must be done in Gentoo if the change is breaking indeed.

**Comment by waebbl** [comment]
> I don't understand increasing "patch version" - do you mean revbumping consumers while adding `media-libs/assimp:=` dep? That's what must be done in Gentoo if the change is breaking indeed.

I mean the (upstream) bump from 5.2.**3** to 5.2.**4** in the context of semantic versioning. If there's also an API change involved, it would require a bump in minor, or even major number. But I don't know if upstream follows such guidelines.

**Comment by waebbl** [comment]
Is it ok to add the subslot only to the new release?

**Comment by juippis** [comment]
> Is it ok to add the subslot only to the new release? 

Yeah, we're going to revbump the consumers which is going to trigger a rebuild anyway.


> And how to inform package maintainers so they can add the slot-operator?

We can/will do it while merging this PR. There's really not much to discuss about adding a subslot binder - it's simply something that needs to be done.

I can most likely test this tomorrow earliest.

**Comment by waebbl** [comment]
> > And how to inform package maintainers so they can add the slot-operator?
> 
> We can/will do it while merging this PR. There's really not much to discuss about adding a subslot binder - it's simply something that needs to be done.
> 
> I can most likely test this tomorrow earliest.

It's not about discussing. I was thinking, whether I should ping the maintainers from this PR, so they are aware of the needed change.

**Comment by juippis** [comment]
You could of course do the revbump and adding subslot binders in this PR, so the bot would ping the maintainers automatically. But looking at the revdep list, I don't think this'll be a problem. Maybe the most "problematic" package is qt3d (@gentoo/qt) but looking at its reverse deps, they don't seem too widely used.

**Comment by juippis** [comment]
That being said I'm currently running rdeptester for ALL reverse dependencies for assimp, to spot if the update breaks anything.

**Comment by waebbl** [comment]
> You could of course do the revbump and adding subslot binders in this PR, so the bot would ping the maintainers automatically. 

Of course, and I was actually thinking about it. But then, nobody seems to do it this way. At least, I was never informed by a maintainer to update my revdeps, when they needed to add subslots to their packages, which happened a few times in the past. And some maintainers are not happy, if someone else is fiddling with their packages. So I'd prefer some structured process to inform maintainers about the need for revbumping and adding of the subslot operator.

> rdeptester

Which package includes this? I don't have it installed with my set of ebuild related dev packages.

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
> Of course, and I was actually thinking about it. But then, nobody seems to do it this way. 
At least, I was never informed by a maintainer to update my revdeps, when they needed to add subslots to their packages, which happened a few times in the past. 

From a developer standpoint, this is something that **needs** to be done, and something that generally everyone agrees to, because _not_ revbumping here would cause more breakage than rebuilding the package. Obviously for behemoths such as chromium, qtwebengine etc we want to synchronize the changes as much as possible with other fixes / version bumps. Could also be that contributors are not fully aware of the procedure what needs to be done. 


> And some maintainers are not happy, if someone else is fiddling with their packages. So I'd prefer some structured process to inform maintainers about the need for revbumping and adding of the subslot operator.

You are right. But referencing the previous sentence ^ I do strongly believe this action is backed by QA. Of course do inform the maintainers beforehand as much as possible so they have a chance to sync their intended changes to the ebuild along with the subslot binder. And a subslot binder can be added before this PR gets merged for example, leaving it out from our hands. 


> 
> > rdeptester
> 
> Which package includes this? I don't have it installed with my set of ebuild related dev packages.

I use a very simple custom script, 
https://github.com/juippis/my-gentoo-lxd-scripts/blob/master/container/bin/rdeptester.sh

but for it to be effective it also requires
https://github.com/juippis/my-gentoo-lxd-scripts/blob/master/container/bin/errors_and_qa_notices.sh

tatt has an option to test rdeps while running tests against the main package:
https://github.com/gentoo/tatt

Also if you use eix, it should be simple to generate a list of rdeps manually.

**Comment by waebbl** [comment]
> > Of course, and I was actually thinking about it. But then, nobody seems to do it this way.
> > At least, I was never informed by a maintainer to update my revdeps, when they needed to add subslots to their packages, which happened a few times in the past.
> 
> From a developer standpoint, this is something that **needs** to be done, and something that generally everyone agrees to, because _not_ revbumping here would cause more breakage than rebuilding the package. Obviously for behemoths such as chromium, qtwebengine etc we want to synchronize the changes as much as possible with other fixes / version bumps. Could also be that contributors are not fully aware of the procedure what needs to be done.
> 

Sorry, if I was vague in my formulation. I don't doubt the need for revbumping, my question is about a structured process for informing revdep maintainers about the added subslots and the needs for their package deriving from this (adding subslot, revbumping).


> Of course do inform the maintainers beforehand as much as possible so they have a chance to sync their intended changes to the ebuild along with the subslot binder. And a subslot binder can be added before this PR gets merged for example, leaving it out from our hands.
> 

Which I haven't done yet...

> > > rdeptester
> > 
> > 
> > Which package includes this? I don't have it installed with my set of ebuild related dev packages.
> 
> I use a very simple custom script, https://github.com/juippis/my-gentoo-lxd-scripts/blob/master/container/bin/rdeptester.sh
> 
> but for it to be effective it also requires https://github.com/juippis/my-gentoo-lxd-scripts/blob/master/container/bin/errors_and_qa_notices.sh
> 
> tatt has an option to test rdeps while running tests against the main package: https://github.com/gentoo/tatt
> 
> Also if you use eix, it should be simple to generate a list of rdeps manually.

Thanks for the extra pointers! I was thinking it might be part of a package, I'm not aware of.

**Pull request closed without merging**
