### PR TITLE
sys-boot/{udk,refind}: put french first to prevent portage bug

### PR DESCRIPTION
**Pull request by sveyret**
Due to portage bug, as temporary workaround, we must keep french data at first position in metadata.

### CODE REVIEW

**Comment by sveyret** [comment]
Correction for @shentino 
Please review: @gktrk @gentoo/proxy-maint

**Comment by shentino** [comment]
Looks good to me.  Should suffice until portage gets fixed.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/ef27371...6122936. Thanks!

**Pull request closed without merging**
