### PR TITLE
dev-python/wxpython: add 4.2.0

### PR DESCRIPTION
**Pull request by thesamesam**
Closes: https://bugs.gentoo.org/542672
Closes: https://bugs.gentoo.org/766914
Closes: https://bugs.gentoo.org/890953
Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by ArsenArsen** [comment]
Seems to build, even in the edge cases.  I lack packages to test actual functionality with, though :/

**Comment by eeyrjmr** [comment]
Works for me, needed to build kicad7

**Comment by ArsenArsen** [comment]
OK, tried merging this alongside 4.0 and got a conflict.  Maybe they should share a slot?

**Comment by ArsenArsen** [comment]
The APIs also appear to be compatible from a skim of the release notes.  I'm thinking that we can make this one slot and update to that

**Pull request closed without merging**
