### PR TITLE
net-im/telegram-desktop: Bump to 4.7.1

### PR DESCRIPTION
**Pull request by mid-kid**
Sorry for being so late. I think the new glibmm wasn't in the tree and afterwards I just forgot.

@gyakovlev

### CODE REVIEW

**Comment by thesamesam** [comment]
Please fix CI.

**Comment by mid-kid** [comment]
Sorry, I hadn't noticed that yet.

**Comment by gyakovlev** [comment]
also cleaned up unused old libtgvoip  https://github.com/gentoo/gentoo/commit/f102fd510dc7e7d4713b873a24baf5871bb5e602

**Comment by mid-kid** [comment]
Thanks!

**Pull request closed without merging**
