### PR TITLE
net-misc/rclone: drop old

### PR DESCRIPTION
**Pull request by kuraga**
Signed-off-by: Alexander Kurakin <kuraga333@mail.ru>

/cc @perfinion

### CODE REVIEW

**Comment by perfinion** [comment]
merged in 956acf1eb0b19b765bc4f2c1df7630dc49a49ba6
thanks :)

**Comment by kuraga** [comment]
@perfinion BTW, I see a bad thing now. You [made](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=09da98dc67ab8c18c70c4f3ec5ffcceeb64d6207) 1.50.0 stable and we don't have any other 1.50.x version now. But there is [1.50.2](https://github.com/rclone/rclone/releases/tag/v1.50.2) version instead. I think it should be stable and the once of 1.50.x.

**Comment by perfinion** [comment]
@kuraga hmm were supposed to wait a month before stabling so doesn't that one have to wait a bit longer still?

**Comment by kuraga** [comment]
@perfinion I'm telling about 1.50.2 not 1.51.0. [1.50.2](https://github.com/rclone/rclone/releases/tag/v1.50.2) released this on 19 Nov 2019.

**Pull request closed without merging**
