### PR TITLE
x11-misc/qt5ct: silence useless debug messages by default

### PR DESCRIPTION
**Pull request by Coacher**
@pesa, @kensington, please review whether system-wide QT_LOGGING_RULES manipulation is allowed.

### CODE REVIEW

**Comment by Pesa** [comment]
I'm not opposed, but maybe I'm missing something. What are the consequences?

**Comment by Coacher** [comment]
In this particular case I see no downsides in disabling debug output.
Maybe we should warn users how to get it back?
If multiple packages will start doing this will QT_LOGGING_RULES stack properly?

**Comment by Pesa** [comment]
> Maybe we should warn users how to get it back?

Standard qt methods will still work, right? In that case, upstream documentation should be sufficient.

> If multiple packages will start doing this will QT_LOGGING_RULES stack properly?

Good question. Can you test this scenario?

**Comment by Coacher** [comment]
> Standard qt methods will still work, right? In that case, upstream documentation should be sufficient.

Yes.

> Good question. Can you test this scenario?

```
 /etc/env.d # echo 'QT_LOGGING_RULES="qt5ct.debug=10test;"' > 10test
 /etc/env.d # echo 'QT_LOGGING_RULES="qt5ct.debug=12test;"' > 12test
 /etc/env.d # echo 'QT_LOGGING_RULES="qt5ct.debug=12test1;"' > 12test1
 /etc/env.d # env-update && source /etc/profile
>>> Regenerating /etc/ld.so.cache...
 /etc/env.d # echo $QT_LOGGING_RULES
qt5ct.debug=12test1;
```
The last one wins.

**Comment by Pesa** [comment]
What special handling were you thinking about? "last one wins" is the behavior I'd expect

**Comment by Coacher** [comment]
> What special handling were you thinking about? "last one wins" is the behavior I'd expect

Some variables handled specially, e.g. many colon-separated variables like various *PATH and *DIRS are concatenated across multiple env files.

**Comment by Coacher** [comment]
@Pesa, since the last one wins I guess system-wide env file isn't the right solution here, right?
I think users should do it manually on their own.

**Comment by Pesa** [comment]
Yeah... Also, if a user specifies `QT_LOGGING_RULES` for just one category on the command-line, it will override *all* system-wide rules, including unrelated ones. I'm not sure if that's the behavior we want. So I'm going to close this.

As an aside: it seems that Qt should really provide a built-in way of combining multiple rules together... I don't see any way of doing that at the moment.

**Pull request closed without merging**
