### PR TITLE
net-im/pidgin: add 2.14.12

### PR DESCRIPTION
**Pull request by scardracs**
Closes: https://bugs.gentoo.org/890283

Signed-off-by: Marco Scardovi <mscardovi@icloud.com>

### CODE REVIEW

**Comment by scardracs** [comment]
@thesamesam by the way are there any particular bug/s you want to be checked on this PR?

**Review by iv4nhoe — CHANGES_REQUESTED** [review]
That irc_join_sleep.patch should not be necessary anymore. The original [issue](https://bugs.gentoo.org/577286) has been fixed in Pidgin 2.14.9 (see [PIDGIN-11089](https://issues.imfreedom.org/issue/PIDGIN-11089) for details).

**Comment by scardracs** [comment]
> That irc_join_sleep.patch should not be necessary anymore. The original [issue](https://bugs.gentoo.org/577286) has been fixed in Pidgin 2.14.9 (see [PIDGIN-11089](https://issues.imfreedom.org/issue/PIDGIN-11089) for details).

Did you test it on any way?

**Comment by iv4nhoe** [comment]
> > That irc_join_sleep.patch should not be necessary anymore. The original [issue](https://bugs.gentoo.org/577286) has been fixed in Pidgin 2.14.9 (see [PIDGIN-11089](https://issues.imfreedom.org/issue/PIDGIN-11089) for details).
> 
> Did you test it on any way?

I just tested auto-joining 10 channels on libera with Pidgin 2.14.12 compiled from source with no issues.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
