### PR TITLE
dev-java/xerces: build against java >=8

### PR DESCRIPTION
**Pull request by neeshy**

### CODE REVIEW

**Comment by vaukai** [comment]
@neeshy the restriction to `jdk:1.8` is there for a certain reason which  is explained [in the ebuild](https://github.com/gentoo/gentoo/commit/743111a72f39a1b24f87bd1b2fc32ef707b41407#diff-e54415b6a43fc90c92a1715f6c6f2ca58adb1410a7900356db561538c450647aR23-R32).

**Comment by neeshy** [comment]
IDK, works for me. I'm on JDK 21 though. I don't know about 11 or 17, but maybe having `|| ( virtual/jdk:1.8 virtual/jdk:21 )` would be better.

**Comment by neeshy** [comment]
Then again, the `||` operator might confuse the way the Java eclass determines which JDK to build against. I will test this.

**Comment by fordfrog** [comment]
i tested it with openjdk 8, 11, 17 and 21 and the issue does not appear anymore.

**Comment by fordfrog** [comment]
merged, again dropped to unstable and i also removed the comment which seems to be obsolete now (ec4267af1ead5e442d41f4337ff1805d2ea56db3).

**Pull request closed without merging**
