### PR TITLE
x11-libs/libxcb, x11-proto/xcb-proto: add support for python 3.5

### PR DESCRIPTION
**Pull request by hkgz**
Seems like #776 missed these changes.

### CODE REVIEW

**Comment by idella** [comment]
I do not know to whom this ought be assigned, or given prompt of notice, but to my knowledge it is time to bump EAPI to 6

**Comment by monsieurp** [comment]
@gentoo/python @gentoo/x11

**Comment by jlec** [comment]
> ... but to my knowledge it is time to bump EAPI to 6

Please only bump to EAPI 6 in revision and version bumps. Simple additions of python impl support should not include an EAPI bump.

@hkgz does the testsuite work with python3.5?

**Comment by hkgz** [comment]
@jlec x11-libs/libxcb works. x11-proto/xcb-proto has no test flag.

**Comment by monsieurp** [comment]
can we proceed and merge this PR?

**Pull request closed without merging**
