### PR TITLE
www-client/chromium: Add hangout USE flag

### PR DESCRIPTION
**Pull request by wking**
With [Mario Sanchez Prada's fix for the "WebRTC screensharing does not
work in hangouts" issue][1].

[1]: https://code.google.com/p/chromium/issues/detail?id=416856#c53

### CODE REVIEW

**Comment by wking** [comment]
Filed in Bugzilla as https://bugs.gentoo.org/show_bug.cgi?id=562590.

**Comment by mgorny** [comment]
@floppym

**Comment by Tatsh** [comment]
Works great for me with version 46.0.2490.42. Needs clarity on licensing.

**Comment by Tatsh** [comment]
Please add this for all versions, or at least beta too.

**Comment by mgorny** [comment]
Seems to be cherry-picked. Closing.

**Pull request closed without merging**
