### PR TITLE
app-i18n/rime-data: Add 1.0.20241201.

### PR DESCRIPTION
**Pull request by ryanli**
Also add rime-cantonese to extras.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by liangyongxiang** [comment]
Thanks. I think it's best to keep the old version.

**Comment by ryanli** [comment]
Thanks, I've added it back.

**Comment by liangyongxiang** [comment]
The manifest also needs to be updated.
 You can run the `pkgdev manifest` in the package directory.

**Comment by ryanli** [comment]
Thanks, done.

**Review by liangyongxiang — APPROVED** [review]

**Comment by dlan17** [comment]
em.. please notice next time
1) no need to have full-stop in commit message (I missed this)
2) no commit stable keywords directly (I've fixed)

**Pull request closed without merging**
