### PR TITLE
dev-libs/libsecp256k1: bump to 0.6.0

### PR DESCRIPTION
**Pull request by whitslack**
See: https://github.com/bitcoin-core/secp256k1/releases/tag/v0.6.0
Closes: https://bugs.gentoo.org/942890

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] `pkgcheck scan --commits --net` doesn't know how to deal with Git worktrees.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks. Please make sure to file stablereqs regularly and also cleanup old afterwards.

**Comment by whitslack** [comment]
@thesamesam: I don't know that I'm technically/officially the proxied maintainer of this package. At least, it doesn't show up in the list [here](https://packages.gentoo.org/maintainer/gentoo@mattwhitlock.name).

**Comment by whitslack** [comment]
> Adopt it?

@thesamesam: Sure. How? Do I open another PR to modify its `metadata.xml`? Is that the sole repository of truth about its maintainership, or is there some manifest somewhere else?

On a related note, I tried to follow your instruction that I request stabilization of net-p2p/bitcoin-core-27.1, but I've now been waiting for 3½ weeks for my [request](https://bugs.gentoo.org/941227) to be completed, so I wonder if maybe I missed a step needed to push it into the pipeline.

**Comment by whitslack** [comment]
> The source of truth is `metadata.xml`. Please make a new PR adding yourself.

Will do.

> Up to you if you drop Luke while doing it. I don't think he's touched these packages in a long time.

I don't think he has either, but I'd prefer to let him step down affirmatively rather than effectively timing him out. I feel like I stepped on his toes a bit when reintegrating Bitcoin Core back into a monobuild, and he even reverted my dropping of some extremely outdated split packages in the Bitcoin overlay, so I'd rather not make any assumptions about what he wants to happen to things he's touched.

> I don't think you have _editbugs_ permissions on Bugzilla yet. You've been around more than long enough for me to trust you with that and vouch for you. If you would like such permissions to edit bugs, please let me know, and also promise to be responsible and ask someone if you are unsure.

I don't know how often I would make use of such permission. I guess it would let me add dependencies between bugs that I don't own, such as to add a bug to a tracker. I would hesitate to do anything any more disruptive than that, like "confirming" a bug once an actual problem in the code has been identified. (I don't often see bugs even transition into the `CONFIRMED` state before being resolved, so maybe there are some unintuitive constraints around it.) But yes, if you grant me that permission, I do promise not to be reckless with it.

> Also, for future bugs, please don't CC arches manually, but use `CC-ARCHES` in the bug Keywords

Ah ha! The things they don't teach you in school. :P

**Comment by thesamesam** [comment]
Fair enough.

I've granted editbugs. We indeed don't tend to use `CONFIRMED` in Gentoo but it's not wrong to set it either. If you assign bugs, please use https://github.com/projg2/bug-assign-user-js.

**Pull request closed without merging**
