### PR TITLE
sci-geosciences/grass: add version 9999 (7.9 dev)

### PR DESCRIPTION
**Pull request by tmszi**
Add version 9999 (7.9 dev).

### CODE REVIEW

**Comment by juippis** [comment]
Since it increases the maintenance burden, I'd like to hear approval from the main maintainers.
@hamarituc, @gentoo/sci-geosciences any thought?

**Comment by hamarituc** [comment]
> Since it increases the maintenance burden, I'd like to hear approval from the main maintainers.
> @hamarituc, @gentoo/sci-geosciences any thought?

I would appreciate to add development version 7.9 to the portage tree. Since @tmszi is involved into GRASS development, it would facilitate the preparation of the next GRASS major release for Gentoo.

But I am a novice Gentoo package maintainer and unsure whether I am in the position to decide it finally.

@tmszi: Could you please check, whether it is necessary to apply the patch `grass-7.8-flock.patch`? A race condition in the GRASS build system leads to a build failure in version 7.8 for highly parallel builds like the Gentoo tinderbox build service. See https://bugs.gentoo.org/746590 for the details.

**Comment by tmszi** [comment]
> I would appreciate to add development version 7.9 to the portage tree. Since @tmszi is involved into GRASS development, it would facilitate the preparation of the next GRASS major release for Gentoo.

I think it's a good idea for users who want to experience the latest changes in GRASS GIS, but also for developers who want to participate in the development of GRASS GIS. I am actively using/compiling (daily) GRASS GIS (version 7.9 dev, which is quite stable) on Gentoo GNU/Linux distribution, and I am also a new member of the GRASS GIS development team. 

> @tmszi: Could you please check, whether it is necessary to apply the patch `grass-7.8-flock.patch`? A race condition in the GRASS build system leads to a build failure in version 7.8 for highly parallel builds like the Gentoo tinderbox build service. See https://bugs.gentoo.org/746590 for the details.

I didn't notice this bug when compiling GRASS GIS (arch amd64, 4 cores, MAKEOPTS = "- j4"), but so far I haven't tried to compile through the Gentoo tinderbox build service.

**Review by juippis — COMMENTED** [review]
```
checking whether to use PostgreSQL... no
checking whether to use MySQL... no
checking whether to use SQLite... no
checking whether to use OpenGL... yes
checking for location of OpenGL includes... 
checking for GL/gl.h... yes
checking for GL/glu.h... no
configure: error: *** Unable to locate OpenGL includes.

!!! Please attach the following file when seeking support:
!!! /var/tmp/portage/sci-geosciences/grass-9999/work/grass-9999/config.log
 * ERROR: sci-geosciences/grass-9999::testworld failed (configure phase):
 *   econf failed
```
Both USE flag combinations ends up in this error:
atom: =sci-geosciences/grass-9999, USE flags: 'X -blas cxx -fftw geos lapack liblas -mysql -netcdf nls -odbc opencl opengl openmp -png -postgres -python_single_target_python3_7 python_single_target_python3_8 -python_single_target_python3_9 readline -sqlite threads -tiff truetype zstd'
atom: =sci-geosciences/grass-9999, USE flags: 'X -blas -cxx fftw -geos lapack liblas -mysql -netcdf -nls -odbc opencl opengl openmp png -postgres -python_single_target_python3_7 python_single_target_python3_8 -python_single_target_python3_9 readline -sqlite -threads -tiff -truetype -zstd'

Could you please investigate this? Otherwise looks good to me.

**Comment by tmszi** [comment]
> ```
> checking whether to use PostgreSQL... no
> checking whether to use MySQL... no
> checking whether to use SQLite... no
> checking whether to use OpenGL... yes
> checking for location of OpenGL includes... 
> checking for GL/gl.h... yes
> checking for GL/glu.h... no
> configure: error: *** Unable to locate OpenGL includes.
> 
> !!! Please attach the following file when seeking support:
> !!! /var/tmp/portage/sci-geosciences/grass-9999/work/grass-9999/config.log
>  * ERROR: sci-geosciences/grass-9999::testworld failed (configure phase):
>  *   econf failed
> ```
> 
> Both USE flag combinations ends up in this error:
> atom: =sci-geosciences/grass-9999, USE flags: 'X -blas cxx -fftw geos lapack liblas -mysql -netcdf nls -odbc opencl opengl openmp -png -postgres -python_single_target_python3_7 python_single_target_python3_8 -python_single_target_python3_9 readline -sqlite threads -tiff truetype zstd'
> atom: =sci-geosciences/grass-9999, USE flags: 'X -blas -cxx fftw -geos lapack liblas -mysql -netcdf -nls -odbc opencl opengl openmp png -postgres -python_single_target_python3_7 python_single_target_python3_8 -python_single_target_python3_9 readline -sqlite -threads -tiff -truetype -zstd'
> 
> Could you please investigate this? Otherwise looks good to me.

Yes, of course I fixed it in the commit https://github.com/gentoo/gentoo/pull/19160/commits/7d50510056b7776d0062c74caa5dbc299c65540a.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
