### PR TITLE
app-text/nfoview-1.26 version bump

### PR DESCRIPTION
**Pull request by tillschaefer**
also fixed license from GPL-3 to GPL-3+

### CODE REVIEW

**Comment by gyakovlev** [comment]
Hi.
can you please squash this into 1 or 2 commits?
general practice is that you introduce changes to live or versioned ebuild and then just copy versioned <-> live ebuilds to make sure they match and then push changes to the tree. don't commit same stuff to several ebuilds at once. commit to single one, and sync files as last commit.
you can document all the changes in commit body instead of introducing multiple commits to multiple files.

your commits may look like this

> 1.26: ->  bump to 1.26
*  remove pkg_preinst
*  fix license
*  capitalize description
*  add py3.7

> 9999: sync live ebuild

This is easier on git history, can be reverted if needed and easier to review and merge.

**Comment by tillschaefer** [comment]
Sorry for the holiday delay. Finally, I did the squashing/reordering of the commits.

**Comment by gyakovlev** [comment]
pushed.

your sign-off line was a bit incorrect, probably because you did it by hand,
there was no space between `:` and your name, I fixed that.

to get repoman automatically signo-ff for you just add

`DCO_SIGNED_OFF_BY="Till Schäfer <till2.schaefer@uni-dortmund.de>"`

to 

`/etc/portage/make.conf`

**Comment by tillschaefer** [comment]
> to get repoman automatically signo-ff for you just add
> 
> `DCO_SIGNED_OFF_BY="Till Schäfer <till2.schaefer@uni-dortmund.de>"`
> 
> to
> 
> `/etc/portage/make.conf`
THX for the tip. I have done a `rebase -i` a lot of times because I have missed that signed-of-by-line :-)

**Pull request closed without merging**
