### PR TITLE
media-libs/dssi: depend on virtual/jack

### PR DESCRIPTION
**Pull request by lilrc**
@SoapGentoo, is this good enough? If it is I'll redo my other PR's á la this pattern.

### CODE REVIEW

**Comment by aballier** [comment]
no need to revbump straight to stable

**Comment by lilrc** [comment]
@aballier should I revbump to ~arch and file a stabilization bug? In #4336 @SoapGentoo said I had to revbump when changing RDEPEND.

**Comment by aballier** [comment]
let @SoapGentoo explain but I see this change like a build fix against jack2 (thus not requiring revbump) rather than something changing runtime behavior

**Comment by lilrc** [comment]
@aballier This is now two weeks old, should I redo this w/o a revbump?

**Comment by aballier** [comment]
since soap isn't responding, please do so and I'll merge it, thanks

**Comment by SoapGentoo** [comment]
soz, everything is fine, let me merge

**Pull request closed without merging**
