### PR TITLE
app-admin/webmin: bump to 1.930 & add support on Virtualmin

### PR DESCRIPTION
**Pull request by hsntgm**
* PR has one issue about max file size, emerge --config script is huge. 
I hope devs take care it to find trusted upload space.
* With time i am planning to tweak all virtualmin modules for gentoo.

~Hasan

### CODE REVIEW

**Comment by hsntgm** [comment]
ping

**Comment by tamiko** [comment]
@hsntgm Will have a look at it this weekend. Thanks!

**Comment by hsntgm** [comment]
Thanks.

**Comment by tamiko** [comment]
Is there a particular reason why you closed the PR?

**Comment by hsntgm** [comment]
I stopped contributing because of personal conflicts and retired so closed all active PRs and my packages to grabs.

Thanks for your help.
Feel free to use code if you wanna bump it.

**Comment by tamiko** [comment]
I am sorry to hear that :-(
Thanks a lot for your contributions, hope to see you back soon!

**Pull request closed without merging**
