### PR TITLE
dev-libs/protobuf-3.0.0_beta2.ebuild

### PR DESCRIPTION
**Pull request by iHateInventNames**
Can someone help on this?

Change-Id: I2262c279fb5bd060b3f6270d844e15a3dc445c51

### CODE REVIEW

**Comment by rindeal** [comment]
Why to bother with pre-release software?

**Comment by blueness** [comment]
@rindeal While I cannot speak to this package, I sometimes push out pre-releases to give the community the possibility to test and participate in the "release often release early" approach in Open Source.

**Comment by rindeal** [comment]
@blueness But isn't this something overlays are for?

**Comment by iHateInventNames** [comment]
I need it to build Cura 3d printing software. Cura-build requires protobuf
3.
11 апр. 2016 г. 22:02 пользователь "Jan Chren" <notifications@github.com>
написал:

**Comment by blueness** [comment]
@rindael its a judgment call.  overlays are splinters (like a fork) and thing should be in the tree as much as possible
@vapier you're pkg man, your call

**Comment by tomboy-64** [comment]
@iHateInventNames I am currently working on this as well as on the cura package. If you don't mind I'd like to have a look at it?

@rindeal @blueness This might be pre-release, BUT
- protobuf3 is a new format, which requires support
- the last release of protobuf is 2.6.1 from autumn 2014 -> a new package is overdue.

**Comment by iHateInventNames** [comment]
@tomboy-64 that would be great

**Comment by tomboy-64** [comment]
Please have a look at [PR1256](https://github.com/gentoo/gentoo/pull/1256). It is part of my attempt to get a current Cura into the tree.
Considering there's this pr with protobuf 3, I extracted it from my cura branch and made it a separate one.

**Comment by tomboy-64** [comment]
protobuf 3.0.0_beta2 has been pushed. please close.

**Pull request closed without merging**
