### PR TITLE
net-misc/electrum, net-p2p/bitcoind: remove unused patches/file

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patch(es) from:
net-misc/electrum
net-p2p/bitcoind

Please review

### CODE REVIEW

**Comment by mm1ke** [comment]
ping, any chance we can merge this :)

**Comment by blueness** [comment]
i would have merged it but i'm the maintainer of electrum, not bitcoind.  you need to isolate your PR's to just one maintainer.  i don't want to step on anyone else's toes.

**Comment by blueness** [comment]
my recommendation is that you divide this up

**Comment by luke-jr** [comment]
I already said it was fine on the bitcoind end...

**Comment by blueness** [comment]
the patch no longer applies.  i'll just clean up electrum myself.

**Pull request closed without merging**
