### PR TITLE
media-gfx/converseen: add 0.12.0.1, drop overshadowed stable versions

### PR DESCRIPTION
**Pull request by rndxelement**
Hi,
I added an ebuild for media-gfx/converseen-0.12.0.1.
Notes:
- Due to upstream changes in `CMakeLists.txt` I had to change the linking for GraphicsMagick slighlty in `converseen-0.12.0.1-graphicsmagick-support.patch`.
- Had to add two more `#elif MagickLibVersion > 0x100000` cases in `converseen-0.12.0.1-graphicsmagick-support.patch` (these are needed because GraphicsMagick implements an older subset of the ImageMagick API, so the `#if` directives which fire for classic ImageMagick API calls have to fire for GraphicsMagick as well).
- Build and runtime tested with ImageMagick
- Build tested with GraphicsMagick
- Upstream now supports QT6. I'd like to give users the opportunity to compile with QT6 via the `qt6` use flag. However, this migration will be done in a future PR.
- The recent upstream changes can be found in the [changelog](https://converseen.fasterland.net/changelog/)

Furthermore, I removed the old, overshadowed stable ebuilds.

### CODE REVIEW

**Comment by thesamesam** [comment]
Thank you for the great description! My only suggestion would be to include more of it in the commit messages as well in future.

**Comment by thesamesam** [comment]
Oh, had to fix direct stable keywords too.

**Comment by rndxelement** [comment]
> Thank you for the great description! My only suggestion would be to include more of it in the commit messages as well in future.

Thanks, noted!

**Comment by rndxelement** [comment]
> Oh, had to fix direct stable keywords too.
Thank you, hopefully one day I'll learn to remember it :D

**Pull request closed without merging**
