### PR TITLE
net-p2p/freenet: add 0.7.5_p1498 | dev-java/pebble: new package, add 3.1.6

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
With this PR which I am adding to the open bugs on https://bugs.gentoo.org/showdependencytree.cgi?id=918647 there are now only 3 PRs left.  Hopefully that's all for `jdk:21` stabilization.

**Comment by vaukai** [comment]
`freenet-java21.patch` is now in a separate commit.

**Comment by vaukai** [comment]
@juippis 
rebased after https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4d62857e9b7f2933d218d66d747647cbca514087

**Review by juippis — COMMENTED** [review]
```
>>> Configuring source in /var/tmp/portage/net-p2p/freenet-0.7.5_p1497-r1/work/freenet-build01497 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-p2p/freenet-0.7.5_p1497-r1/work/freenet-build01497 ...
!!! ERROR: Package ant was not found!
```

```
>>> Configuring source in /var/tmp/portage/dev-java/pebble-3.1.6/work/pebble-3.1.6/pebble ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-java/pebble-3.1.6/work/pebble-3.1.6/pebble ...
!!! ERROR: Package junit-4 was not found!
 * ERROR: dev-java/pebble-3.1.6::gentoo failed (compile phase):
 *   java-config --classpath=junit-4 failed
```
pebble was during test phase, so junit is a test dependency at least.

**Comment by vaukai** [comment]
@juippis 
i am separating commits. presently we only need the part helping for [java 21 stabilization ](https://bugs.gentoo.org/showdependencytree.cgi?id=918647&hide_resolved=1).

**Comment by vaukai** [comment]
> >>> Configuring source in /var/tmp/portage/net-p2p/freenet-0.7.5_p1497-r1/work/freenet-build01497 ...
> >>> Source configured.
> >>> Compiling source in /var/tmp/portage/net-p2p/freenet-0.7.5_p1497-r1/work/freenet-build01497 ...
> !!! ERROR: Package ant was not found!

Cannot reproduce. Does that happen also before the patch? with freenet as presently is in the tree? There is no such [bug report](https://packages.gentoo.org/packages/net-p2p/freenet/bugs).

**Comment by vaukai** [comment]
going to re-add those two commits. checked everything, wfm.

**Comment by vaukai** [comment]
maybe this package is a candidate to last rite?

**Comment by vaukai** [comment]
I've just removed anything `ant{,-1.7.1}.jar` left over from ancient times and obviously unneeded.

**Pull request closed without merging**
