### PR TITLE
net-analyzer/ripe-atlas-tools: Version bump. Adds dependency for IPy

### PR DESCRIPTION
**Pull request by danielquinn**
For some reason, when I run `ebuild <package> test` everything fails on account of `IPy` not existing, but running the tests locally work just fine so I'm assuming that this is a quirk I don't understand.

### CODE REVIEW

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
danielquinn,
before starting the state of this package, I would point out there are already 4 versions present.
the git log tells me:

commit 4d205e923c3acd11b0f69781f72369fdb7d7b24e
should have had the commit msg split over at least 3 lines and cited that it was a revbump -> 1.2.3-r1
The other versions have been  long present.

I suggest therefore that you add to this pull request the removal of ebuilds of vns. 1.2.[1-3],
so as to purge stale old versions, with a commit msg "rm old".  Otherwise they simply build up and bloat portage (which you can observe on most other packages)

Please edit your commit $msg to

```
net-analyzer/ripe-atlas-tools: Version bump to 2.0.1

Adds dependency for IPy
``` 

You might also consider putting this package up for stabilisation some time.

Now to check the package

**Comment by idella** [comment]
So: a way to go

The best result I get with the tests is 

```bash
ERROR: User passes no args, should fail with SystemExit
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/net-analyzer/ripe-atlas-tools-2.0.1/work/ripe.atlas.tools-2.0.1/tests/commands/report.py", line 68, in test_with_empty_args
    self.cmd.run()
  File "/mnt/gen2/TmpDir/portage/net-analyzer/ripe-atlas-tools-2.0.1/work/ripe.atlas.tools-2.0.1/ripe/atlas/tools/commands/report.py", line 181, in run
    use_regular_file
  File "/mnt/gen2/TmpDir/portage/net-analyzer/ripe-atlas-tools-2.0.1/work/ripe.atlas.tools-2.0.1/ripe/atlas/tools/commands/report.py", line 243, in _get_results_from_file
    sample = next(self.file)
StopIteration

----------------------------------------------------------------------
Ran 148 tests in 6.162s

FAILED (errors=1)
 * ERROR: net-analyzer/ripe-atlas-tools-2.0.1::gentoo failed (test phase):
 *   Tests failed with python2.7
```

So I do not know if you did a full test on the testsuite.
Without having emerge the full bumped package, you get a FAILED (errors=1, failures=5)
with

```bash
FAIL: Tests autocompletion of specific command.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/gen2/TmpDir/portage/net-analyzer/ripe-atlas-tools-2.0.1/work/ripe.atlas.tools-2.0.1/tests/test_bash_completion.py", line 56, in test_command_completion
    self.assertTrue("measure" in output)
AssertionError: False is not true
-------------------- >> begin captured stdout << ---------------------
(u'', u'/bin/sh: ripe-atlas: command not found\n')
```

which illustrates that the author of this package has written the suite to read the script ripe-atlas for /usr/bin/.  This is not uncommon by upstreams, and it also breaks both the norm for how testsuites 'should' be written and gentoo's inhouse design.
A test suite is both expected and required to run out of the box forn the source, in this case with calling the testrunner, nose(tests).

Options:
1. skip over the cuplrit tests that require the script to be system installed already, because
I have runtested them and found they all pass once the script 'ripe-atlas' is in fact accessed.
Do not simply delete the tests since they are legit and work
2. prompt upstream to rewrite the suite to access and run the scripts locally, which means he will have to make a next release and you skip this release until the new is released.
3. report the test yielding "ERROR: User passes no args, should fail with SystemExit" which appears to be a legit fail exposed by his testsuite.

python testsuites are tricky
Also, the deps ought all have py3.5 support added to them as well as this package. I could do that (add to the deps) off my own bat if required.

**Comment by danielquinn** [comment]
Thanks so much for the feedback.  I'll pass your suggestions regarding the tests upstream and close this ticket in anticipation of an update release.

As for the old packages, I'll happily remove them in a separate PR, or in the same PR that will be coming in the aforementioned update release.  Is there a preference?

Lastly, regarding a stabilisation request, [I issued one for 1.2.2 back in February](https://bugs.gentoo.org/show_bug.cgi?id=575396) and no one acted on it.  Is there something else I should be doing?

**Pull request closed without merging**
