### PR TITLE
Keyword mupdf and dep for ~arm64

### PR DESCRIPTION
**Pull request by NeddySeagoon**
Works on Raspberry Pi 3 in 64 bit mode.

### CODE REVIEW

**Comment by chewi** [comment]
Are these related? If not, you should submit them separately, otherwise each maintainer can't deal with their own package without it looking weird in the commit history.

**Comment by NeddySeagoon** [comment]
Yes.  mupdf depends on media-libs/glfw.
From equery d media-libs/glfw
mupdf is the only user.

**Comment by chewi** [comment]
Fair enough. I checked glfw and repoman complains about the Wayland stuff. I guess this could be ignored as it is an experimental profile.

**Comment by NeddySeagoon** [comment]
Probably.  The only changes I made were to the KEYWORDS and copyright date.
What's the conflict?

**Comment by chewi** [comment]
dev-libs/wayland and dev-libs/wayland-protocols (behind the wayland USE flag) are not keyworded for arm64.

**Comment by NeddySeagoon** [comment]
Wayland on a Raspberry Pi sounds a bit adventurous.  Its tested on Xfce4.
Please suggest a way forward.  I can build test the libs but not runtime test.  I don't think that's good enough for a ~arm64 keyword.

**Comment by chewi** [comment]
The wayland flag could be masked on arm64 pending further testing but I don't mind that much since it's an experimental profile. Just thought I should mention it.

**Comment by NeddySeagoon** [comment]
Others may be playing with wayland on arm64. I have no way to tell.  It might take them by surprise.  Yes its a bit piecemeal but its experimental.  leio ran a PR to show all tud ~arm64 arm64 inconsistencies like this.  There were 310.  This fixes some and creates a few more.

**Comment by chewi** [comment]
I'll hand over to @xmw to okay this change. I can merge it if he wants.

**Comment by NeddySeagoon** [comment]
WFM.

**Comment by NeddySeagoon** [comment]
How does adding an ~arm64 keyword cause ppc issues?

**Comment by chewi** [comment]
You didn't resolve the conflict properly and made ppc/ppc64 unstable rather than stable. You need to rebase in any case as we don't want conflict resolutions in the commit history. Try to follow the steps I told you the other day.

**Comment by xmw** [comment]
commit 9a6260ead24bf83591d78d4d99e0e66bab448b1b
Author: Michael Weber <xmw@gentoo.org>
Date:   Sun Jan 29 23:33:58 2017 +0100

    app-text/mupdf: Add ~arm64 keyword (https://github.com/gentoo/gentoo/pull/3638).
    
    Package-Manager: Portage-2.3.3, Repoman-2.3.1

commit 3ae2c5ab3f7a90531025cdf62db60fb32ef16e3f
Author: Michael Weber <xmw@gentoo.org>
Date:   Sun Jan 29 23:32:05 2017 +0100

    media-libs/glfw: Add ~arm64 keyword (https://github.com/gentoo/gentoo/pull/3638).
    
    Package-Manager: Portage-2.3.3, Repoman-2.3.1

**Comment by chewi** [comment]
As demonstrated, it's easy enough to make keyword changes ourselves. Just trying to get you more familiar with git!

**Comment by NeddySeagoon** [comment]
chewi,

I don't understand how I screwed up the ppc keyword.  I'll need to learn how to get the history out of git.

xmw,

Thank  you for fixing my mess.

**Comment by chewi** [comment]
It's hard to say exactly what you did but even though you only wanted to add ~arm64, it looks like in attempting to resolve the conflict, you made it say:

```bash
KEYWORDS="~arm64 ~ppc ~ppc64"
```

Rather than:

```bash
KEYWORDS="~arm64 ppc ppc64"
```

You can see this if you click the __Files changed__ tab at the top.

**Pull request closed without merging**
