### PR TITLE
sci-electronics/kicad: Add new 4.0.4 ebuild

### PR DESCRIPTION
**Pull request by zpuskas**
Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by dlan17** [comment]
hey, a few minor suggestions ..

1) please try to follow "one commit per change" if possible
      you can split the renaming patches and version bump (4.0.4)

2) add the github PR link to the commit message
     so once we commit, this PR will be closed automatically

      add line "Closes: https://github.com/gentoo/gentoo/pull/2377"

3) always run "repoman full"

>>> Creating Manifest for /home/gentoo/gentoo/sci-electronics/kicad
  dependency.missingslot        6
   sci-electronics/kicad/kicad-4.0.1-r1.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
   sci-electronics/kicad/kicad-4.0.2-r1.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
   sci-electronics/kicad/kicad-4.0.2-r2.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
   sci-electronics/kicad/kicad-4.0.2-r3.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
   sci-electronics/kicad/kicad-4.0.2-r4.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator
   sci-electronics/kicad/kicad-4.0.4.ebuild: RDEPEND: 'media-libs/glew' matches more than one slot, please specify an explicit slot and/or use the := or :* slot operator

**Comment by dlan17** [comment]
also, any idea why we would keep so many revisions in tree? I personally tend to leave at most two ..
I'm talking about 4.0.2-r{1,2,3,4}

**Comment by zpuskas** [comment]
I can take out r1-r3 in a next diff.

**Comment by zpuskas** [comment]
I had to rename patches because of the the new revision.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Pull request closed without merging**
