### PR TITLE
Various prefix related fixes aiming to make media-sound/pulseeffects work

### PR DESCRIPTION
**Pull request by nado**

### CODE REVIEW

**Comment by nado** [comment]
I'm guessing you were talking about media-libs/lilv, if the others should be revbumped too, I'll do so after a confirmation.

**Comment by prometheanfire** [comment]
anything that changes files on disk, the use flags, the EDROOT, all that.

**Comment by nado** [comment]
I hope it will be the last, I’ll try remembering the rules for revbumping in the future.

**Comment by prometheanfire** [comment]
merged, thanks :D

**Pull request closed without merging**
