### PR TITLE
media-gfx/openscad: don't call ccache if it's not present

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by a17r** [comment]
It should not use ccache at all, so please disable it always.

**Comment by l29ah** [comment]
ok

**Comment by a17r** [comment]
Thanks, does it also affect any release version in tree?

**Comment by l29ah** [comment]
On Mon, Dec 25, 2017 at 04:41:28PM +0000, Andreas Sturmlechner wrote:
> Thanks, does it also affect any release version in tree?

I doubt this, as the latest release built fine w/o any hacks on my machine.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Pull request closed without merging**
