### PR TITLE
app-emulation/vagrant: version bump to 1.8.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Currently hard masked: https://bugs.gentoo.org/show_bug.cgi?id=505124. This is based on great work of Reto Gantenbein (ganto) at: https://bugs.gentoo.org/show_bug.cgi?id=563548.

This needs: https://bugs.gentoo.org/show_bug.cgi?id=572290

### CODE REVIEW

**Comment by monsieurp** [comment]
We'll need the @gentoo/ruby folks to help us out here.
@hydrapolic: vagrant has been masked apparently. merging this PR means removing the mask and giving you maintainership. are you willing to maintain vagrant?

**Comment by hydrapolic** [comment]
@monsieurp, yes I'll proxy maintain the package(s), if anybody wants to join, I'll be glad. And I agree, the ruby team should check this and probably the 2 new ruby packages (rb-kqueue, hashicorp-checkpoint) should be under ruby project as well, so we can co-maintain them.

**Comment by ganto** [comment]
@hydrapolic  Thanks a lot for bringing it up here and showing interest in maintaining the package. It would be a pity to loose Vagrant in Gentoo. I still have the one or other thing in mind to improve the ebuild and you can ask me to help testing things if I have time.

By the way, the ebuild was mostly following some ideas from the [Fedora package](https://admin.fedoraproject.org/pkgdb/package/rpms/vagrant/) which I adapted to Gentoo. The Fedora packagers already made a big effort identifying the integration knobs, so I don't want to miss thanking them for their great work.

**Comment by hydrapolic** [comment]
@ganto, feel free to share your tips for improvement :) If not in this release, we can go on and make it better in the future.

**Comment by hydrapolic** [comment]
Thanks for the review @graaff, I've dropped rb-kqueue, updated dep on newer net-scp and hashicorp-checkpoint is now with rdoc and with proper test dep hopefully.

**Comment by graaff** [comment]
:+1:

**Comment by hydrapolic** [comment]
Thanks guys for the help, glad we made it into the main tree!

**Pull request merged**
