### PR TITLE
dev-db/pgcli: bump to version 2.1.1.

### PR DESCRIPTION
**Pull request by dargor**
Bump version to 2.1.0.

### CODE REVIEW

**Comment by mgorny** [comment]
I've taken care of bumping tabulate, cli_helpers and adding py3.7 to them. Please rebase, test pgcli on py3.7 and add tests if possible.

**Comment by dargor** [comment]
If I enable `python3_7` repoman gets angry, I am not sure why : 
```
$ repoman -dx full

RepoMan scours the neighborhood...
  dependency.bad [fatal]        28
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/gnome/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/desktop/plasma/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/developer)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/hardened)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/hardened/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/no-multilib/hardened/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/desktop)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/desktop/gnome)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/desktop/gnome/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/desktop/plasma)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/desktop/plasma/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/developer)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/hardened)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/hardened/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/no-multilib)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/no-multilib/hardened)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/no-multilib/hardened/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/selinux)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.1/systemd)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
  dependency.badindev           1
   dev-db/pgcli/pgcli-2.1.0.ebuild: RDEPEND: ~amd64(default/linux/amd64/17.0/x32)
[     '<dev-python/python-sqlparse-0.3.0[python_targets_python2_7(-)?,python_targets_python3_5(-)?,python_targets_python3_6(-)?,python_targets_python3_7(-)?,-python_single_target_python2_7(-),-python_single_target_python3_5(-),-python_single_target_python3_6(-),-python_single_target_python3_7(-)]']
Please fix these important QA issues first.
RepoMan sez: "Make your QA payment on time and you'll never see the likes of me."
```

**Comment by sbraz** [comment]
That's because you have version boundaries: `<dev-python/python-sqlparse-0.3.0` and only 0.3.0 has Python 3.7 in `PYTHON_COMPAT`.

**Comment by dargor** [comment]
`pgcli==2.1.1` is compatible `python3_7`.

**Comment by dargor** [comment]
Closing zombie PR.

**Pull request closed without merging**
