### PR TITLE
dev-util/cbindgen: add 0.24.5

### PR DESCRIPTION
**Pull request by xen0n**

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Looks like 0.24.6 is out already. Could you use that?

**Review by juippis — COMMENTED** [review]
I've been monitoring https://github.com/mozilla/cbindgen/releases releases instead of https://github.com/mozilla/cbindgen/tags tags :\

**Comment by xen0n** [comment]
> Looks like 0.24.6 is out already. Could you use that?

Isn't that version [yanked](https://github.com/mozilla/cbindgen/commit/e9e88b0ab0ed10da6dc49368d3c212fa0736d017)?

**Review by juippis — APPROVED** [review]
Apparently so.
https://github.com/mozilla/cbindgen/issues/841

btw you're welcome to co-maintain by yourself / toolchain if you're interested / this package is important.

**Pull request closed without merging**
