### PR TITLE
sci-libs/gdal: add live

### PR DESCRIPTION
**Pull request by t0b3**
live ebuild becomes very handy i.e. to debug qgis issues related to gdal like https://github.com/qgis/QGIS/issues/48012

### CODE REVIEW

**Comment by t0b3** [comment]
see also #24885

**Comment by thesamesam** [comment]
I'll make you a deal. I'll merge it if you add yourself as maintainer to gdal and the other bits you use? 😄

**Comment by thesamesam** [comment]
I'm not really keen on having even more live ebuilds especially if I'm going to need to maintain it myself but if it's useful for you I guess we can add one more. Is it useful?

**Comment by thesamesam** [comment]
If you're willing to help maintian gdal / keep this in sync, we can merge it. Otherwise live ebuilds are usually a pain to keep up to date (I don't use them and I'm the main person bumping gdal right now, reluctantly). Cheers!

**Pull request closed without merging**
