### PR TITLE
Create spotify-1.2.25.ebuild

### PR DESCRIPTION
**Pull request by MinamiX99**
Couldn't figure out the sha and blake2 stuff, I'm kinda new. Sorry.

### CODE REVIEW

**Comment by sevz17** [comment]
To generate the manifest you need to run either `pkgdev manifest` or `ebuild manifest`

**Comment by mm1ke** [comment]
You can use `pkgcheck manifest` or `ebuild foo.ebuild` to generate ebuild manifests. Also see: https://devmanual.gentoo.org/general-concepts/manifest/index.html

**Comment by parona-source** [comment]
Handled by Ammerlaam https://github.com/gentoo/gentoo/commit/bf94ef893e784dcb5a2240d85cdf02546563e4cc

Also good to check if there are previous merge request already for the same thing https://github.com/gentoo/gentoo/pull/33947

**Comment by AndrewAmmerlaan** [comment]
Sorry it seems I missed your PR when bumping this package :(

Closing as obsolete now, latest version in ::gentoo is 1.2.37

**Pull request closed without merging**
