### PR TITLE
media-plugins/audacious{,-plugins}: bump to 4.1

### PR DESCRIPTION
**Pull request by scardracs**
Drop 3.x as it is require GTK+:2

Closes: https://bugs.gentoo.org/775989
Closes: https://bugs.gentoo.org/797835
Bug: https://bugs.gentoo.org/711292

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by a17r** [comment]
Without having checked upstream changes, bump lgtm. Do you want to maintain this package? I never officially committed to maintenance there, previous maintainer assigned me without permission after having neglected it for most of the time.

**Comment by scardracs** [comment]
> Without having checked upstream changes, bump lgtm. Do you want to maintain this package? I never officially committed to maintenance there, previous maintainer assigned me without permission after having neglected it for most of the time.

Not a problem for me

**Review by juippis — APPROVED** [review]
While these ebuilds do work, they don't apply cleanly anymore. Even if I try to cherry-pick relevant ones, they're split in a way that seems impossible and I'm not in the mood of reconstructing this git history manually, sorry. 

@a17r I wasn't aware of the package maintenance history. I see 21b6fe1f683cdf5260e27a2bdc1c1e1a654ace37 happened, but anyone looking at the metadata.xml will find you a primary maintainer, and therefore hold you responsible for the package. If the change was done without your consent, why haven't you fixed the situation in 2  years time? Are we now always supposed to check metadata history? :D 

Anyway, builds fine, looks fine apart for few minor updates (EAPI-8, iwdevtools dependency fixes)

**Comment by scardracs** [comment]
@juippis the problem, iirc, was about a "maintainer" who added a17r as maintainer without his consent

**Comment by a17r** [comment]
@juippis I'm telling you why you can touch this package now, not every package in the future.

**Comment by scardracs** [comment]
Did you mind merging it? It's the last PR I've still opened with gentoo

**Comment by juippis** [comment]
@scardracs I told you I can't, it doesn't apply to the git tree at all and basically requires so much manual work I'd be faster doing it on my own :P 
(and I don't care about audacious to do it on my own)

**Comment by scardracs** [comment]
> @scardracs I told you I can't, it doesn't apply to the git tree at all and basically requires so much manual work I'd be faster doing it on my own :P 
> (and I don't care about audacious to do it on my own)
> 
> EDIT: So please rebase against fresh ::gentoo master and drop any irrelevant modifications, just basically do the version bumps and let's continue from there on another time.

Ok, I'll follow that way, thanks

**Pull request closed without merging**
