### PR TITLE
dev-php/pecl-memcached: add 3.3.0

### PR DESCRIPTION
**Pull request by hydrapolic**
Working tests, php 8.3 support

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by orlitzky** [comment]
Do you still use dev-php/pecl-mcrypt? It needs an update too :)

(php:8.1 masks are coming soon)

**Comment by hydrapolic** [comment]
> Do you still use dev-php/pecl-mcrypt? It needs an update too :)
> 
> (php:8.1 masks are coming soon)

Not really, we stopped using it. Are you fine with removing it from portage?

Thanks for helping out @orlitzky

**Comment by orlitzky** [comment]
Yeah, no problem, there are a bunch of others stuck on 8.1 that I plan
to mask. I'll add it to the list.

**Comment by hydrapolic** [comment]
> Do you still use dev-php/pecl-mcrypt? It needs an update too :)
> 
> (php:8.1 masks are coming soon)

@orlitzky I thought only some legacy pecl packages are about to be removed, I'm quite surprised we've masked php 8.1 given it's still security supported and works just fine. Are there any issues with current toolchain and php 8.1 or is it just a precaution? 

I would recommend stabilizing 8.2/8.3 and keeping 8.1 just in ~arch so we still have at least 1 year time to migrate the workload to newer php versions.

**Comment by orlitzky** [comment]
On 2024-11-14 01:55:37, Tomáš Mózes wrote:
> @orlitzky I thought only some legacy pecl packages are about to be removed, I'm quite surprised we've masked php 8.1 given it's still security supported and works just fine. Are there any issues with current toolchain and php 8.1 or is it just a precaution? 
> 
> I would recommend stabilizing 8.2/8.3 and keeping 8.1 just in ~arch so we still have at least 1 year time to migrate the workload to newer php versions.

8.2 is already stable, but 8.1 doesn't build with gcc-14 and upstream
isn't interested in fixing it. They also aren't interested in updating
the test suite for newer versions of dependencies, or fixing the
./configure script so that features aren't disabled by mistake due to
compiler strictness, or musl support, or... anything else.

I'm on 8.2/8.3 and the PHP project has been empty for a year and a
half now so the question is really, do we leave it in the tree,
broken, and blocking things like the gcc-14 stabilization? Or give up
and remove it? I can't afford to fork it and backport all of the bug
fixes that make it into 8.2, and there's nobody else to do it.

**Comment by hydrapolic** [comment]
> On 2024-11-14 01:55:37, Tomáš Mózes wrote: @orlitzky I thought only some legacy pecl packages are about to be removed, I'm quite surprised we've masked php 8.1 given it's still security supported and works just fine. Are there any issues with current toolchain and php 8.1 or is it just a precaution? I would recommend stabilizing 8.2/8.3 and keeping 8.1 just in ~arch so we still have at least 1 year time to migrate the workload to newer php versions.
> 8.2 is already stable, but 8.1 doesn't build with gcc-14 and upstream isn't interested in fixing it. They also aren't interested in updating the test suite for newer versions of dependencies, or fixing the ./configure script so that features aren't disabled by mistake due to compiler strictness, or musl support, or... anything else. I'm on 8.2/8.3 and the PHP project has been empty for a year and a half now so the question is really, do we leave it in the tree, broken, and blocking things like the gcc-14 stabilization? Or give up and remove it? I can't afford to fork it and backport all of the bug fixes that make it into 8.2, and there's nobody else to do it.

Maybe then specifying the gcc dependency for php 8.1 and keeping it in ~arch (removing the stable kw)? That way, it would not block gcc-14 stabilization as  the newer versions are probably compatible with it.

Forking/backporting is out of option I suppose, it's too much work. Anyways, thank you for dedicating your time for php! If you say it's better to remove, I'll keep it in my overlay.

**Comment by orlitzky** [comment]
On 2024-11-14 06:15:26, Tomáš Mózes wrote:
> Maybe then specifying the gcc dependency for php 8.1 and keeping it
> in ~arch (removing the stable kw)? That way, it would not block
> gcc-14 stabilization as the newer versions are probably compatible
> with it.

This is harder than it sounds because putting gcc:13 in BDEPEND
doesn't have any effect on the gcc-config'd version. Then you might
need to limit the clang version, too. It would be easier to disable
the new compiler features with -Wno-error flags but the flags differ
between compilers, and some of the warnings/errors are real bugs that
won't get fixed, and this all needs to be investigated and tested...


> Forking/backporting is out of option I suppose, it's too much
> work. Anyways, thank you for dedicating your time for php! If you
> say it's better to remove, I'll keep it in my overlay.

I am pretty bad about cleaning up masked packages, so it will probably
be there until the end of the year at least. FWIW 8.1 -> 8.2 was
relatively easy for us. I looked back at the upgrade ticket in our
Redmine and nobody even noticed. A few one-time deprecation warnings
showed up in Drupal (visibly!), and I had to patch the old D7 version
of drush in ::gentoo, but nothing actually broke, and Wordpress (our
biggest concern by far) was fine.

**Pull request closed without merging**
