### PR TITLE
dev-libs/tree-sitter-* updates and clean ups

### PR DESCRIPTION
**Pull request by mattst88**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by arthurzam** [comment]
Can you please run ebuild tests for pkgcheck-9999 (non live version has version cap on tree sitter).On Sep 5, 2024 06:48, Gentoo repository mirror & CI project bot ***@***.***> wrote:
Pull request CI report
Report generated at: 2024-09-05 03:48 UTC
Newest commit scanned: 4ff5088
Status: ✅ good
There are existing issues already. Please look into the report to make sure none of them affect the packages in question:
https://qa-reports.gentoo.org/output/gentoo-ci/2b0bfc05bf/output.html

**Comment by mattst88** [comment]
I assume you're asking about updating `tree-sitter-bash`.

Today with the current version, I get this:

```
=========================== 65 failed, 711 passed, 111 skipped, 200 warnings in 125.02s (0:02:05) ===========================
```

With `tree-sitter-bash-0.23.1`, pkgcheck fails to emerge:

```
2024-09-05 19:22:13,166 gpep517 INFO Building wheel via backend py_build
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/objects.py", line 87, in _dict
    result = getattr(_defaults, self._attr)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'object' object has no attribute 'KEYWORDS'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 443, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 439, in main
    return func(args)
           ^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 229, in build_wheel
    print(build_wheel_impl(args, args.wheel_dir), file=out)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/gpep517/__main__.py", line 221, in build_wheel_impl
    wheel_name = backend.build_wheel(str(wheel_dir), args.config_json)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/py_build.py", line 133, in build_wheel
    return prepare_pkgcheck(callback, only_version=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/py_build.py", line 118, in prepare_pkgcheck
    write_objects(cleanup_files)
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/py_build.py", line 61, in write_objects
    from pkgcheck import objects
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/__init__.py", line 3, in <module>
    from .api import keywords, scan
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/api.py", line 9, in <module>
    from . import objects
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/objects.py", line 198, in <module>
    KEYWORDS = _KeywordsLazyDict("KEYWORDS", ("checks", "results.Result"))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/objects.py", line 82, in __init__
    self._dict
  File "/usr/lib/python3.12/site-packages/snakeoil/klass.py", line 205, in __get__
    obj = self.function(instance)
          ^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/objects.py", line 89, in _dict
    result = _find_obj_classes(*self._func_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/objects.py", line 51, in _find_obj_classes
    module = import_module(f".{module_name}", "pkgcheck")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/checks/__init__.py", line 10, in <module>
    from .. import addons, base, feeds, runners, sources
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/feeds.py", line 3, in <module>
    from . import base, sources
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/sources.py", line 17, in <module>
    from .bash import ParseTree
  File "/var/tmp/portage/dev-util/pkgcheck-9999/work/pkgcheck-9999/src/pkgcheck/bash/__init__.py", line 8, in <module>
    lang = Language(tree_sitter_bash.language())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: an integer is required
```

**Comment by mattst88** [comment]
With `tree-sitter-bash-0.23.1`, I get:

```
================================ 776 passed, 111 skipped, 200 warnings in 142.51s (0:02:22) =================================
```

**Comment by arthurzam** [comment]
Managed to return to the base and verify it also, and it indeed passes. I'll merge it.

Much thanks!

**Pull request closed without merging**
