### PR TITLE
Cinnamon 6.2 updates (24/7/5)

### PR DESCRIPTION
**Pull request by SparkyBluefang**
Cinnamon 6.2 package updates and clean-up old versions

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by eli-schwartz — COMMENTED** [review]
Not saying this PR is wrong, but. Some of these "drop old versions" are the previous most recent release, which hasn't yet been stabilized. It is halfway through the month so could in theory be up for stabilizing pretty soon... do we still want to drop it? (I do acknowledge the situation was less clear on the date that you opened the PR in the first place :))

**Comment by eli-schwartz** [comment]
@SparkyBluefang I queued up a few more changes that I think make sense here as well.

https://github.com/gentoo/gentoo/compare/master...eli-schwartz:gentoo:cinnamon-updates

**Comment by SparkyBluefang** [comment]
> Not saying this PR is wrong, but. Some of these "drop old versions" are the previous most recent release, which hasn't yet been stabilized. It is halfway through the month so could in theory be up for stabilizing pretty soon... do we still want to drop it? (I do acknowledge the situation was less clear on the date that you opened the PR in the first place :))

Yeah, this how I've always handled updates to unstable packages. It always felt like a waste of everyone's time and attention to go through a bunch of add/stabilize/clean-up cycles while upstream goes through their usual post-release version churn.

> @SparkyBluefang I queued up a few more changes that I think make sense here as well.
> 
> [master...eli-schwartz:gentoo:cinnamon-updates](https://github.com/gentoo/gentoo/compare/master...eli-schwartz:gentoo:cinnamon-updates)

That all looks reasonable to me. I'd say I don't know how well/if any of Cinnamon would work without `gtk+[X]`, but I guess that's technically a possibility now with the automagic dependency. I honestly haven't tried testing any of the wayland stuff since it's incomplete/broken (and I can't live without xf86-input-synaptics).

Would these maybe benefit from also adding `REQUIRED_USE="|| ( wayland X )"`?

**Comment by eli-schwartz** [comment]
I can't make up my mind whether to simply require X, have it be optional the way I did here, or use the REQUIRED_USE approach. It does not help that in some cases these packages are only actually looking at gdk backends in fairly niche components, like the one that is only part of the wacom plugin.

**Comment by eli-schwartz** [comment]
cinnamon itself only uses X, in NaTrayManager. It will otherwise emit:

```
g_warning ("Port NaTrayManager to this GTK+ backend");
```

So perhaps this is another indicator that cinnamon DE doesn't really support wayland yet. :) Mandatory X for this package? wdyt

**Comment by SparkyBluefang** [comment]
Yeah, mandatory X with optional/masked wayland seems like the safest thing for the time being, and we can revisit as upstream continue to make progress with wayland support and fixing explicit X references.

`gnome-extra/cinnamon[wayland]` is currently masked, so the wayland launcher/sessions aren't available. As far as I'm aware, there's no side affect for having wayland enabled in the other packages when running under X, so those aren't masked.

**Comment by eli-schwartz** [comment]
Ok so I'm going to convert all X? to X, drop the `use X || append-cflags ...`, and keep the wayland changed I made, times all packages. Sounds like a plan.

**Pull request closed without merging**
