### PR TITLE
app-backup/kfoldersync: version bump

### PR DESCRIPTION
**Pull request by Vindex17**

### CODE REVIEW

**Comment by kensington** [comment]
I would change the license to just ``GPL-3``, as, in the event of a later GPL version, the ``+`` part would only be valid with KDE e.V. approval. What do you think?

**Comment by Vindex17** [comment]
This is what I put in the source code:
 * This program is free software; you can redistribute it and/or        
 * modify it under the terms of the GNU General Public License as       
 * published by the Free Software Foundation; either version 3 of       
 * the License or any later version accepted by the membership of       
 * KDE e.V. (or its successor approved by the membership of KDE         
 * e.V.), which shall act as a proxy defined in Section 14 of           
 * version 3 of the license.  

There's also a GPL3+ here: https://community.kde.org/Policies/Licensing_Policy

I think GPL-3+ is fine, but you tell me

**Comment by kensington** [comment]
Right, but if tomorrow GPL-4 was released, ``LICENSE="GPL-3+"`` will be wrong until such a time as the KDE e.V. membership accepts it (if they ever do).

**Comment by Vindex17** [comment]
I think you are right, but then I do not understand the meaning of GPL-2+ since it has the same limitation... Can you make the change directly to the tree or must I update this pr?

**Comment by kensington** [comment]
Indeed, I must have just missed that previously.

In any case, I did pick this already as 04b9e235ca3ca28baef777b1138a432c93261a67 but forgot to mention that.

Thanks for the PR!

**Pull request closed without merging**
