### PR TITLE
dev-lang/zig: add stage2 support

### PR DESCRIPTION
**Pull request by BratishkaErik**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: BratishkaErik <bratishkaerik@getgoogleoff.me>

### CODE REVIEW

**Comment by BratishkaErik** [comment]
no no no, wrong commit, bot

**Review by juippis — COMMENTED** [review]
This new virtual is useless here. 

What does stage2 do?

**Comment by 12101111** [comment]
stage1 is a zig frontend implemented using c++, stage2 is a zig frontend implemented using zig itself

**Comment by BratishkaErik** [comment]
> This new virtual is useless here.

It will choose between `dev-lang/zig` and future `dev-lang/zig-bin`, like `virtual/rust` (currently there is critical bugs with it)

**Comment by BratishkaErik** [comment]
> And because zig currently doesn't have any reverse dependencies, the virtual would still be useless in the tree.

https://github.com/gentoo/gentoo/pull/25242 new version depends on Zig :)

**Review by juippis — APPROVED** [review]
```
 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/bin/zig-stage2
```
If zig does start getting reverse dependencies, then I'll admit a -bin version has some attraction. But let's see how ncdu's maintainer wants to handle it. Since in any case, we **can't** add new packages to the tree without a maintainer.

I'd also like if in future we expand the description in zig to explain stage1 & stage2 a bit better. It currently doesn't tell me anything what they do.

**Pull request closed without merging**
