### PR TITLE
dev-libs/aws-sdk-cpp: Fix typo in metadata.xml and add proxy maintainer

### PR DESCRIPTION
**Pull request by Yamakuzure**
I found a typo and a stray soft hyphen (0xad). Repoman is happy now.

Further I have added myself as proxy maintainer as asked for in #12718.

Signed-off-by: Sven Eden <yamakuzure@gmx.net>
Package-Manager: Portage-2.3.76, Repoman-2.3.17

### CODE REVIEW

**Comment by nE0sIghT** [comment]
Looks like some commit missing

**Comment by Yamakuzure** [comment]
> Looks like some commit missing

No. I wrote "Signed-Off-By" instead of "Signed-off-by" ... *gnarf*

**Comment by nE0sIghT** [comment]
> No....

Ok, but you didn't touch any line with UTF-8 characters... You just added yourself as proxy maintainer in metadata.xml

**Comment by Yamakuzure** [comment]
@nE0sIghT : You are right. Someone fixed this while I was preparing the PR. Sorry.

Well, at least I found a typo and eventually managed to add myself as a proxy maintainer. I was asked to do so in #12718

**Comment by juippis** [comment]
I was approached last night about the ufed issue, I made a fast attempt at fixing it before hitting bed. Didnt notice there was a bug open. Thanks for fixing the final typo.

So if length is an issue in metadata.xml (as I originally was afraid of...) I think we should update the metadata.xml and maybe move the documentation to wiki page.

**Comment by juippis** [comment]
FYI, 
https://bugs.gentoo.org/695462

they need to be made one-liners after all. The documentation should be moved somewhere, so could you fix the metadata.xml ASAP and then start moving them to, for example, wiki? Or install upstream docs with the ebuild, or link to upstream docs about modules?

**Comment by juippis** [comment]
Also you can automate the Sign-off part by adding DCO_SIGNED_OFF_BY to make.conf and using repoman to commit.

**Comment by Yamakuzure** [comment]
> Also you can automate the Sign-off part by adding DCO_SIGNED_OFF_BY to make.conf and using repoman to commit.

I always use repoman to commit, but didn't know about DCO_SIGNED_OFF_BY . Thanks for the hint!

**Comment by Yamakuzure** [comment]
> FYI,
> https://bugs.gentoo.org/695462
> 
> they need to be made one-liners after all. The documentation should be moved somewhere, so could you fix the metadata.xml ASAP and then start moving them to, for example, wiki? Or install upstream docs with the ebuild, or link to upstream docs about modules?

I will shorten that tag. The content, as described in GLEP-68, is explicitly allowed to be multi-line and will be flattened according to the PMS. (Which is indeed is. The flag is a one-liner in use.local.desc, it is just extremely long. Too long, also for ufed.)

**Pull request closed without merging**
