### PR TITLE
Updates for botocore, boto3, awscli

### PR DESCRIPTION
**Pull request by andrey-utkin**
Updates for these loosely related packages. I reached @alunduil who is maintainer of botocore and boto3 on IRC and he recommended me to open pull request here.

I understand that awscli is maintained not solely by @alunduil but by python project so different approach may apply here. I'm fine if my patchset will be merged just partially.

I have tested merging all new ebuilds with such settings:

* with both `test` and `doc` being disabled - works
* `FEATURES="test"` - works
* `USE="doc" PYTHON_TARGETS="python2_7"` - works
* `USE="doc"` with any python 3.x in `PYTHON_TARGETS` - emerge `sphinx-1.2.3-r1` fails for python 3.x, but 1.1.3 - 1.3 is the versions range for sphinx specified in botocore and boto3 upstream sources. Seems this should be resolved upstream, but I think this is not a reason to wait with this ebuilds submission.

Thanks for review.

### CODE REVIEW

**Comment by andrey-utkin** [comment]
b.g.o ticket: https://bugs.gentoo.org/show_bug.cgi?id=614940

**Comment by mgorny** [comment]
@andrey-utkin, thanks for your work. However, we seem to be long past merging it.

I have merged the botocore-1.4.93 commit since that still seems to be the newest version in 1.4* branch. I've also tested it on python3.6.

Could you update botocore-1.5* to the newest version? I will merge it immediately this time ;-). boto3 seems still up-to-date, so I will be able to merge it afterwards. As for awscli, we seem to have a newer version around already.

**Comment by andrey-utkin** [comment]
@mgorny please pick b643c84ee646250c7d30a63540604706c41430f6 (single commit).

**Comment by mgorny** [comment]
Thanks again! I've also added py3.6 to boto3 ;-).

**Pull request closed without merging**
