### PR TITLE
net-analyzer/openvas: bump to 10.0.1

### PR DESCRIPTION
**Pull request by hsntgm**
Detailed information can be get from my old closed PR -> https://github.com/gentoo/gentoo/pull/12542

Old PR was splitted to two part as suggested Juippis.

1)Cleanups PR. (Merged) https://github.com/gentoo/gentoo/pull/12669
2)Version bumps PR. (package.masks included)

This is the version bumps PR @juippis 

@mgorny Here is the acct-*/gvm UID GID PR that ready to merge for user 'gvm' https://github.com/gentoo/gentoo/pull/12609

Thanks.

### CODE REVIEW

**Comment by hsntgm** [comment]
ping

**Comment by blshkv** [comment]
@hsntgm this package is important for me, and I was waiting for it  to be accepted. May I know why you decided not to wait and closed the pull request?

**Comment by hsntgm** [comment]
@blshkv if you need it personally you can get it from my overlay. 
https://github.com/hsntgm/gvm-10-gentoo-overlay

As you see GVM is major version of OpenVAS and integration to gentoo tree needs lots of work and dev attention because of changed package names also there are some internal issues sadly not solved yet. So i could't go further from this point.

https://bugs.gentoo.org/692076
https://bugs.gentoo.org/692004

**Comment by blshkv** [comment]
I took your work and pushed to Pentoo: https://github.com/pentoo/pentoo-overlay/commit/72321affa0624f273a56462864de753c0916c2f4

There is an issue with init.d scripts (unable to stop) but I managed to start it.

Thanks for your work.
Cheers

**Comment by hsntgm** [comment]
:) Cheers

**Comment by juippis** [comment]
It's probably my fault. I've neglected to take care of this before I had to wrap up some work due to my vacation (where I gave no thought for Gentoo). 

There is a lot to due and I was always waiting to have that 1-2 hours to check this, but honestly looks like @hsntgm has done an awesome work regarding this PR. Everything seems to be thought carefully. 

Currently the openvas situation is a bit messed in Gentoo, but I might resolve it by myself. I'll use these commits if @hsntgm allows me to, it's good work.

@blshkv can you give a quick rundown to fix init.d things?

**Comment by hsntgm** [comment]
@juippis as always, thank you. Sure you can use these PR's commits. Pls bear in mind that acct-user gvm 495 too.

There are total 5 bugs you can close with these commits.
684220, 692004, 684186, 692076, 692004

**Comment by hsntgm** [comment]
@juippis  it seems we have new bug.
https://bugs.gentoo.org/696470

There are total 5 bugs you can close with these commits.
684220, 692004, 684186, 692076, 696470 (@mgorny opened the new bug)

**Comment by juippis** [comment]
Thanks for the heads-up!

**Comment by juippis** [comment]
Merged now, 
please send last-rites to gentoo-dev about new gvm resolver. Also I forgot to close that newly linked bug here. 
Also also lets move to acct-* whenever we can, gonna merge them later today I think.

**Comment by blshkv** [comment]
FYI, I'm testing the latest gvm-11, it is available via pentoo overlay.
However, there is a major bug in this version, see https://github.com/greenbone/gvmd/issues/822 for more details. So it is not ready to production yet.

**Comment by hsntgm** [comment]
Thank you @juippis .I was busy today couldn't reply you earlier. I will send last-rites. Acct UID-GID 495 has been reserved and shared with gentoo-dev already. You can safely commit it.

@blshkv i am aware of that. They released buggy version. SCAP Data not rsyncing and postgres always use %100 cpu. I took your gnutls.patch and ospd-openvas ebuild.

Feel free to add your name to metadata on pentoo overlay also if you want in gentoo metadata too.

Cheers!

**Comment by hsntgm** [comment]
@blshkv i will no longer maintain GVM (OpenVAS) set in gentoo. Could you drop me on metadata for **pentoo-overlay** too? It seems pentoo not in sync with gentoo for below packages.

net-analyzer/gvm
net-analyzer/gvm-libs
net-analyzer/openvas-scanner
net-analyzer/gvmd
net-analyzer/greenbone-security-assistant
net-analyzer/ospd
net-analyzer/gvm-tools

Cheers!

**Comment by blshkv** [comment]
@linxon could you please help to fix our metadata files?

**Comment by hsntgm** [comment]
@ZeroChaos-

**Comment by linxon** [comment]
@blshkv @hsntgm done.

**Pull request closed without merging**
