### PR TITLE
dev-perl/*: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from dev-perl/*
Please look at the list below for the packages affected. 
All packages are part of the **gentoo/perl** project: @Zlogene @axs-gentoo @Civil @akhuettel @kentfredric @monsieurp @titanofold 
Please review.

### CODE REVIEW

**Comment by monsieurp** [comment]
Woah! Thanks a lot. This is a massive clean up.

**Comment by monsieurp** [comment]
@mm1ke Hi! Out of curiosity, could you show us the script you use for getting rid of unused patches? Thanks!

**Comment by kentfredric** [comment]
@monsieurp despite my initial reservations about being able to review this efficiently, I found a way to do it quickly.

Most of the affected dists no longer have any patching implied at all, and the handful that do I don't see any references to the removed files.

In short, this has my ACK now. :+1:

**Comment by mm1ke** [comment]
@monsieurp You can get the script here: https://github.com/mm1ke/gentoo-scripts
Please bare in mind this script isn't well written and still lists a lot of false positive's (see README), but it's usually a good start to look at obsolete patches. :)

**Pull request closed without merging**
