### PR TITLE
media-gfx/gimp: added patch to use nullptr

### PR DESCRIPTION
**Pull request by mazunki**
Closes: https://bugs.gentoo.org/887587
Signed-off-by: Mazunki Hoksaas <rolferen@gmail.com>

### CODE REVIEW

**Comment by band-a-prend** [comment]
Please use upstream patch from https://gitlab.gnome.org/GNOME/gimp/-/merge_requests/792

**Comment by mazunki** [comment]
@band-a-prend Thanks, I hadn't realized it was a duplicate. I couldn't find it in the bug tracker. I changed it to return -1 as per upstream instead. 

Closes: https://bugs.gentoo.org/875413

**Comment by band-a-prend** [comment]
[gimp-2.10.zip](https://github.com/gentoo/gentoo/files/10282593/gimp-2.10.zip)
Could you please update pull request with attached files?

1. Patch file is renamed;
2. bug, upstream issue and upstream patch is linked within patch file;
3. all KEYWORDS set to unstable (I'm not sure it could be as is, maybe initial -r3 could be rename this time as dcom is not so popular plugin: @thesamesam could you please give an advise?);
4. the deprecated dependency is replaced with new.

**Comment by thesamesam** [comment]
I think technically as it is a change, we should do unstable keywords indeed without git mv.

**Comment by band-a-prend** [comment]
@thesamesam 
great thanks for fixing gegl.
Sorry for my huge delay of dealing with it.

**Comment by band-a-prend** [comment]
@mazunki 
sorry for my misleading notice but as @thesamesam mentioned gimp-2.10.32-r3 revision stays stable there it was (please restore it from portage tree) and new file gimp-2.10.32-r4 (with all unstable KEYWORDS) is added with new patch for it.

**Comment by mazunki** [comment]
@band-a-prend Ah, I understand what you meant now. Thanks, -r3 stays stable, -r4 is unstable.

**Comment by band-a-prend** [comment]
@mazunki 
Thanks for PR

**Comment by mazunki** [comment]
Thanks yourself, @band-a-prend :)

**Pull request closed without merging**
