### PR TITLE
profiles/package.mask: last-rite games-board/megamek

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/787374

Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by vaukai** [comment]
@thesamesam

**Comment by ionenwks** [comment]
This runs fine with 1.8 even with the current severely outdated version (upstream is very active), I'll fix this soon'ish.

**Comment by ionenwks** [comment]
Actually, bumping this may be difficult, guess last riting may still be on the table.

**Comment by ionenwks** [comment]
Sorry for the noise, won't bump but I fixed it locally for 1.8 -- it was just something dumb, expect this not to be an issue soon.

**Pull request closed without merging**
