### PR TITLE
net-libs/tox: add ebuild for the v0.1.1 release

### PR DESCRIPTION
**Pull request by zetok**
Freshly released.

### CODE REVIEW

**Comment by mgorny** [comment]
@zetok, do I recall correctly that you are upstream of this? Any reason you couldn't `make dist` and upload a proper tarball with no need for eautoreconf?

**Comment by zetok** [comment]
@mgorny 
>@zetok, do I recall correctly that you are upstream of this?

I'm an upstream of `net-im/qtox` :-)
I do happen to make PRs with improvements to c-toxcore when I spot something to improve.

>Any reason you couldn't `make dist` and upload a proper tarball with no need for eautoreconf?

From what I read, it would seem that `make dist` requires running it to make tarballs, right? If so, it would just add unnecessary work for c-toxcore maintainers – currently making a git tag and pushing it to the repo is all that is necessary to make a "release", since github automatically provides tarballs for tags. So right now there is ~0 effort involved when it comes to releasing tarballs, and throwing in `make dist` would increase load for.. what exactly?

`eautoreconf` just seems like something that works for everyone.

**Comment by mgorny** [comment]
You're talking about calling a single command and attaching a file by one person doing the release vs having to eautoreconf by every single user. Which means additional dependencies (-> reduced portability) and a lot of time wasted (autotools are damn slow). This is basically the assumption upon which the whole design of autotools is based. If you don't want to ship portable packages, then you're probably better off with cmake.

**Comment by zetok** [comment]
>If you don't want to ship portable packages, then you're probably better off with cmake.

Well, c-toxcore is switching to cmake. The only reason why ebuilds are still using autotools are missing docs on using cmake for c-toxcore.

Once docs are in place, new (and live) ebuilds will use cmake.

**Comment by mgorny** [comment]
Ok, that works for me :-P.

**Comment by mgorny** [comment]
Hey, now I'm going to complain. I've just tested it and it lacks proper `S=` assignment. I'll fix it now but next time, please be more careful to commit what you have tested.

**Pull request closed without merging**
