### PR TITLE
Incidental fixes for packages

### PR DESCRIPTION
**Pull request by NHOrus**
Resolves problems found during triaging c99-porting bugs

### CODE REVIEW

**Review by ZeroChaos- — APPROVED** [review]

**Comment by ZeroChaos-** [comment]
It would help to break these completely unrelated changes up so they can be more easily merged by their respective maintainers.  That said, I'm fine with the sigutils fix so I'm going to ACK this.  Feel free to fix the checks here and we can try to get it merged without breaking it up, but next time please break it up.

**Review by ZeroChaos- — APPROVED** [review]

**Comment by NHOrus** [comment]
Will do.
Sorry, I was getting various answers on "should I bunch this up" or "should I break it up"

**Comment by ceamac** [comment]
@NHOrus it's fine by me too, we can merge this.  But please fix your Signed-off-by lines, they have 2 problems:

- one of them is missing the angle brackets (it has "Signed-off-by: NHO jy6x2b32pie9@yahoo.com" instead of "Signed-off-by: NHO **<**jy6x2b32pie9@yahoo.com**>**"
- both the name and the email in the Signed-off-by line must be the same as the ones used in the Author: line.  In your case, the author is `NHOrus` but the Signed-off-by is `NHO`.

Please fix these problems, force push, and we can merge your changes.

Thank you!

**Comment by NHOrus** [comment]
I am sorry for inconvenience.
Fixed.

**Pull request closed without merging**
