### PR TITLE
dev-lang/icon: Fixes compile error with glibc 2.28

### PR DESCRIPTION
**Pull request by CheyenneWills**
Added patch pending upstream patch approval

Bug: https://bugs.gentoo.org/669330
Signed-off-by: Cheyenne Wills <cwills@witznd.net>
Package-Manager: Portage-2.3.49, Repoman-2.3.11

### CODE REVIEW

**Comment by mgorny** [comment]
1. Could you include a diff against the current version?
2. Could you please link the upstream submission here? Or was it via private mail?

**Comment by CheyenneWills** [comment]
> 1. Could you include a diff against the current version?

The patch file contains the diff.  All it was was removing some code associated with an ancient level of glibc and changing the #if to pull in the "new" glibc method for any level of glibc. (there was one trailing blank change as well..) The only change to the ebuild was adding the patch file

> 2. Could you please link the upstream submission here? Or was it via private mail?

I work closely with upstream directly (I help out with upstream work at times).  There was a pull request, however the upstream maintainer is still new with git, so he just pulled it in via a different route plus added some comments and change log updates.  It might be a while before the patch actually makes it into a "published" tar file.  Here is upstream's commit -> https://github.com/gtownsend/icon/commit/bfc4a6004d0d3984c8066289b8d8e563640c4ddd

---

Let me know if that was what you wanted.. or if you need more info.

Thanks

**Comment by mgorny** [comment]
1. Sorry, I meant diff between old and new ebuild revision.
2. If upstream accepted the commit already, please include a link to that commit, so it's easy to find.

**Comment by CheyenneWills** [comment]
Upstream commit -> https://github.com/gtownsend/icon/commit/bfc4a6004d0d3984c8066289b8d8e563640c4ddd

[ebuild_diff.txt](https://github.com/gentoo/gentoo/files/2545292/ebuild_diff.txt)

As I noted above, it may be a while before upstream creates a new "level" with the patch/update applied.  Also their commit contains some updated documentation, a "version date" bump, etc. but the actual code change is the same.  

The patch simply recognizes glibc 2.28 as the same as glibc 2.27 in terms of an #if statement.  

This PR was in response to a failed QA build with a glibc (2.28), and it will also work with glibc 2.27 and earlier (the pre-processor check in the code was for a glibc level from 1995ish timeframe)

**Comment by gyakovlev** [comment]
I pushed this as requested on IRC.
The linked bug https://bugs.gentoo.org/669330, probably should be closed. It could be closed automatically by using `Closes:` tag instead of `Bug:` but I didn't want to edit commit message that way.

lmk if you want me to close the bug (if you can't yourself)

**Pull request closed without merging**
