### PR TITLE
www-misc/monitorix: Removed older versions

### PR DESCRIPTION
**Pull request by Dwosky**
- Removed older versions

Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by Silmano** [comment]
This pull request goes along [bug 632938](https://bugs.gentoo.org/632938), to update and integrate my accounts.

**Comment by Silmano** [comment]
Makes sense, lets see if I'm able to split the commit in two.

**Comment by Silmano** [comment]
Ok, I've left just the older version change to this PR, but not sure why the bot still complains regarding the GCO or account.

**Comment by Dwosky** [comment]
I'm closing this request, will propose a new clear one.

**Pull request closed without merging**
