### PR TITLE
dev-java/eclipse-ecj: add 4.33 - W I P

### PR DESCRIPTION
**Pull request by vaukai**
@fordfrog 
wrt. `dev-java/eclipse-ecj: add 4.33`, this is without `src_install` and `pkg_post*`, which means dropping support for `eselect ecj`. since `eselect ecj` seems completely unused we might do this also for the other slots and then drop it from `app-eselect/eselect-java`. wdyt about?

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
what's approved is merged

**Comment by fordfrog** [comment]
> @fordfrog wrt. `dev-java/eclipse-ecj: add 4.33`, this is without `src_install` and `pkg_post*`, which means dropping support for `eselect ecj`. since `eselect ecj` seems completely unused we might do this also for the other slots and then drop it from `app-eselect/eselect-java`. wdyt about?

it's used to switch the default ecj compiler. i guess that might be rather a feature used by users than the build system.

**Comment by vaukai** [comment]
> > @fordfrog wrt. `dev-java/eclipse-ecj: add 4.33`, this is without `src_install` and `pkg_post*`, which means dropping support for `eselect ecj`. since `eselect ecj` seems completely unused we might do this also for the other slots and then drop it from `app-eselect/eselect-java`. wdyt about?
> 
> it's used to switch the default ecj compiler. i guess that might be rather a feature used by users than the build system.

that was my guess also. since we don't know if it's being used by anyone i'd like to propose merging `eclipse-ecj-4.33` as is and adding the _missing_ details on request, if any.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
> > > @fordfrog wrt. `dev-java/eclipse-ecj: add 4.33`, this is without `src_install` and `pkg_post*`, which means dropping support for `eselect ecj`. since `eselect ecj` seems completely unused we might do this also for the other slots and then drop it from `app-eselect/eselect-java`. wdyt about?
> > 
> > 
> > it's used to switch the default ecj compiler. i guess that might be rather a feature used by users than the build system.
> 
> that was my guess also. since we don't know if it's being used by anyone i'd like to propose merging `eclipse-ecj-4.33` as is and adding the _missing_ details on request, if any.

well, i'd keep it the way we used to do it before. or is there any technical problem for which we would need to drop this support?

btw, what's approved has been merged.

**Comment by vaukai** [comment]
> > > > @fordfrog wrt. `dev-java/eclipse-ecj: add 4.33`, this is without `src_install` and `pkg_post*`, which means dropping support for `eselect ecj`. since `eselect ecj` seems completely unused we might do this also for the other slots and then drop it from `app-eselect/eselect-java`. wdyt about?
> > > 
> > > 
> > > it's used to switch the default ecj compiler. i guess that might be rather a feature used by users than the build system.
> > 
> > 
> > that was my guess also. since we don't know if it's being used by anyone i'd like to propose merging `eclipse-ecj-4.33` as is and adding the _missing_ details on request, if any.
> 
> well, i'd keep it the way we used to do it before. or is there any technical problem for which we would need to drop this support?
> [...]

no problems at all. 
just found it sets ANT_BUILD_COMPILER{,_DEPS} being used by the `eant()` function:
```
	local compiler_env="${JAVA_PKG_COMPILER_DIR}/${compiler}"
	local build_compiler="$(source ${compiler_env} 1>/dev/null 2>&1; echo ${ANT_BUILD_COMPILER})"
	if [[ "${compiler}" != "javac" && -z "${build_compiler}" ]]; then
		die "ANT_BUILD_COMPILER undefined in ${compiler_env}"
	fi

	if [[ ${compiler} != "javac" ]]; then
		antflags="${antflags} -Dbuild.compiler=${build_compiler}"
		# Figure out any extra stuff to put on the classpath for compilers aside
		# from javac
		# ANT_BUILD_COMPILER_DEPS should be something that could be passed to
		# java-config -p
		local build_compiler_deps="$(source ${JAVA_PKG_COMPILER_DIR}/${compiler} 1>/dev/null 2>&1; echo ${ANT_BUILD_COMPILER_DEPS})"
		if [[ -n ${build_compiler_deps} ]]; then
			antflags="${antflags} -lib $(java-config -p ${build_compiler_deps})"
		fi
	fi
```
reading further i find 
```
# @VARIABLE: JAVA_PKG_COMPILERS_CONF
# @INTERNAL
# @DESCRIPTION:
# Path to file containing information about which compiler to use.
# Can be overloaded, but it should be overloaded only for local testing.
JAVA_PKG_COMPILERS_CONF=${JAVA_PKG_COMPILERS_CONF:="/etc/java-config-2/build/compilers.conf"}
```
on my systems there is in `/etc/java-config-2` there is no such `build` subdirectory. would that get created be something else?

**Comment by fordfrog** [comment]
@vaukai it seems, even with the older versions of `ecj`, it doesn't update the compilers file anymore. i don't have it either. i recall there used to be such a file, but obviously it's not used anymore. all that `eselect-ecj` seems to do on my system is set the symlink to `/usr/bin/ecj` from the appropriate version. so i would not bother setting these vars as they seem to be noop.

**Comment by fordfrog** [comment]
merged. `eselect ecj list` shows the new version so it's visible there so it should be probably fine.

**Pull request closed without merging**
