### PR TITLE
Zig 0.10.0

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by BratishkaErik** [comment]
> Should I enable "threads" unconditionally (default and most tested configuration by upstream) and remove this USE flag?

I guess silence means yes...

**Comment by thesamesam** [comment]
yes

**Comment by thesamesam** [comment]
Style tweak in 9c3e47685b03e771b87da1f38df6cb534530c3d6 & added bug tag for LLVM 13

**Comment by thesamesam** [comment]
oh, please sync live too

**Comment by BratishkaErik** [comment]
> oh, please sync live too later

Oh, I just tried to push this...

**Pull request closed without merging**
