### PR TITLE
www-apps/gitea: Version bump to 1.17.1

### PR DESCRIPTION
**Pull request by eeyrjmr**
Signed-off-by: Jonathan Roadley-Battin jon.roadleybattin@gmail.com

### CODE REVIEW

**Comment by kuraga** [comment]
@eeyrjmr , good day! Interesting: why is `acct` optional in this package?

**Comment by eeyrjmr** [comment]
> @eeyrjmr , good day! Interesting: why is `acct` optional in this package?

if you do not want to use the gentoo-controlled/suggested account. Typical use-case is you have been downloading gitea from dl.gitea.io and have a system setup. to then use gentoo-provided could cause some havoc in useraccounts (which a user should straighten out) but until that is done...

**Comment by stintel** [comment]
Doesn't seem to build on x86_64 musl system.
[build.log](https://github.com/gentoo/gentoo/files/9388348/build.log)

**Comment by ajakk** [comment]
Yeah, all of the phase functions were removed. That seems like a mistake.

**Comment by eeyrjmr** [comment]
corrected... unsure how the partial ebuild go copied into the git area...

**Comment by stintel** [comment]
Works fine, thanks!

**Comment by thesamesam** [comment]
I'm not sure why but @thamognya even had the update in their overlay: https://github.com/thamognya/thamognya-overlay/commit/0846a546722f8a5dd290a78754cbe8211019b00d but didn't PR it here.

Anyway, thanks, all done!

**Pull request closed without merging**
