### PR TITLE
www-servers/nginx: fix directory path to pid file

### PR DESCRIPTION
**Pull request by alopatindev**
Closes: https://bugs.gentoo.org/939560

Feel free to make any changes. Thanks.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by juippis — APPROVED** [review]
Kind of there and there should we revbump and reset keywords here, but seems to work from what I can tell with a quick test.

**Comment by sbraz** [comment]
@juippis @alopatindev, this broke nginx with systemd. Nothing creates the parent directory so the startup fails:
```
nginx: [emerg] open() "/run/nginx/nginx.pid" failed (2: No such file or directory)
```
Can you please fix this? Maybe using `RuntimeDirectory`? https://www.freedesktop.org/software/systemd/man/latest/systemd.exec.html#RuntimeDirectory=

**Comment by juippis** [comment]
@sbraz nginx is maintainer-needed so you should've committed it already :P if it works, looks good! Needs another set of revbumps though. Looking at my own doubting whether I should edit a stable ebuild, well, that didn't age well.

**Comment by sbraz** [comment]
Fixed in 6f136d56a588639697e42a27391f83483d333e0e :)

**Pull request closed without merging**
