### PR TITLE
dev-util/ninja: add fortran support

### PR DESCRIPTION
**Pull request by junghans**
Package-Manager: Portage-2.3.40, Repoman-2.3.9

Rel: gentoo/kde#865

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@floppym can we maybe switch this unconditionally? That is, only use the fortran variant

**Comment by floppym** [comment]
Yeah, I'm debating whether or not I want to diverge from ninja upstream; it looks like the maintainer has been inactive for several months.

I'm not sure it's worth the possible maintenance problems just so Fortran cmake projects can build slightly faster.

**Comment by junghans** [comment]
Kitware is only doing a release when ninja does one!

And I am not even sure about the speed advantages (even for C)....

**Comment by SoapGentoo** [comment]
Yes, there are [massive performance gains](http://www.kaizou.org/2016/09/build-benchmark-large-c-project/) on 16 core machines. The whole reason why Meson only uses ninja is to build everything in a non-recursive fashion.

**Comment by junghans** [comment]
Thanks for the link, that looks indeed like a nice gain!

**Comment by floppym** [comment]
Please revise this PR to make fortran support unconditional, as suggested by @SoapGentoo . I'm ok with merging that.

**Comment by junghans** [comment]
@floppym done!

**Pull request closed without merging**
