### PR TITLE
sys-cluster/glusterfs: bump to 6.8/7.3

### PR DESCRIPTION
**Pull request by hydrapolic**
See: https://github.com/gentoo/api-gentoo-org/pull/261

Thanks

### CODE REVIEW

**Comment by ultrabug** [comment]
thanks mate

**Comment by hydrapolic** [comment]
Can you please merge the PR at api-gentoo-org to add it to uid-git map? Thanks

**Comment by Whissi** [comment]
Too late. This already collided with https://github.com/gentoo/api-gentoo-org/commit/04b2f3e52b20ee0b06ab5ca0f19e005590e26fe8 and commit 3afefe1d2c9d5243e13e0ec54add360de9b9ad3a

**Comment by Whissi** [comment]
Fixed via https://github.com/gentoo/api-gentoo-org/commit/16a8cec755cb81918a94a10614deac806dcbfdef, https://github.com/gentoo/api-gentoo-org/commit/a6dc3b0bd18c6d7c0d08b5f864c44785ad1b8829 and 8ac1f4d0731d7f90272b52d21cb8f25d1480bddf.

@erayaslan informational ping

**Comment by hydrapolic** [comment]
Thanks @Whissi for fixing this. The PR to api-g-o for adding the uid/gid didn't make it into the master, the PR was pending as long as this PR. When taking the uid/gid, it was free.

**Pull request closed without merging**
