### PR TITLE
dev-java/jimfs: new package, add 1.3.0 | dev-java/junit: add 5.10.2

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/916398

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog 
this one might please be the next of my PRs to get merged. the junit5 update was overdue since ages, the junit4 update to snapshot allows removing the jdk restriction at the cost of one failing test which  i had to patch out. the junit3 commit is just a minor style update including EAPI 7 -> 8.

**Comment by fordfrog** [comment]
junit-5 fails the tests for me:
```
>>> Test phase: dev-java/junit-5.10.2
removed 'example/IgnoredTestsDemo.java'
removed 'example/DocumentationTestSuite.java'
removed 'example/SuiteDemo.java'
removed 'example/JUnit4Tests.java'
removed 'example/JUnitPlatformClassDemo.java'
removed 'example/JUnitPlatformSuiteDemo.java'
removed 'example/testkit/EngineTestKitAllEventsDemo.java'
removed 'example/testkit/EngineTestKitFailedMethodDemo.java'
removed 'example/testkit/EngineTestKitSkippedMethodDemo.java'
removed 'example/testkit/EngineTestKitStatisticsDemo.java'
removed directory 'example/testkit/'
removed 'org/junit/api/tools/AbstractApiReportWriter.java'
removed 'org/junit/api/tools/ApiReport.java'
removed 'org/junit/api/tools/ApiReportGenerator.java'
removed 'org/junit/api/tools/ApiReportWriter.java'
removed 'org/junit/api/tools/AsciidocApiReportWriter.java'
removed 'org/junit/api/tools/HtmlApiReportWriter.java'
removed 'org/junit/api/tools/MarkdownApiReportWriter.java'
removed directory 'org/junit/api/tools/'
removed 'example/HamcrestAssertionsDemo.java'
removed 'example/session/HttpTests.java'
javac -source 1.8 -target 1.8 -d /var/tmp/portage/dev-java/junit-5.10.2/temp/junit5_src_test/classes -encoding UTF-8 -classpath /usr/share/apiguardian-api/lib/apiguardian-api.jar:/usr/share/opentest4j/lib/opentest4j.jar:/usr/share/open-test-reporting-events/lib/open-test-reporting-events.jar:/usr/share/picocli/lib/picocli.jar:/usr/share/univocity-parsers/lib/univocity-parsers.jar:/usr/share/open-test-reporting-schema/lib/open-test-reporting-schema.jar::/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-commons/junit-platform-commons.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-engine/junit-platform-engine.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-launcher/junit-platform-launcher.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-reporting/junit-platform-reporting.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-console/junit-platform-console.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-api/junit-jupiter-api.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-engine/junit-jupiter-engine.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-params/junit-jupiter-params.jar @/var/tmp/portage/dev-java/junit-5.10.2/temp/junit5_src_test/sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -source 1.8 -target 1.8 -d /var/tmp/portage/dev-java/junit-5.10.2/temp/junit5_src_test/test-classes -encoding UTF-8 -classpath /var/tmp/portage/dev-java/junit-5.10.2/temp/junit5_src_test/classes:documentation/src/test/resources:/usr/share/apiguardian-api/lib/apiguardian-api.jar:/usr/share/opentest4j/lib/opentest4j.jar:/usr/share/open-test-reporting-events/lib/open-test-reporting-events.jar:/usr/share/picocli/lib/picocli.jar:/usr/share/univocity-parsers/lib/univocity-parsers.jar:/usr/share/open-test-reporting-schema/lib/open-test-reporting-schema.jar::/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-commons/junit-platform-commons.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-engine/junit-platform-engine.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-launcher/junit-platform-launcher.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-reporting/junit-platform-reporting.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-platform-console/junit-platform-console.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-api/junit-jupiter-api.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-engine/junit-jupiter-engine.jar:/var/tmp/portage/dev-java/junit-5.10.2/work/junit5-r5.10.2/junit-jupiter-params/junit-jupiter-params.jar @/var/tmp/portage/dev-java/junit-5.10.2/temp/junit5_src_test/test-sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
documentation/src/test/java/example/TempDirectoryDemo.java:28: error: package com.google.common.jimfs does not exist
import com.google.common.jimfs.Configuration;
                              ^
documentation/src/test/java/example/TempDirectoryDemo.java:29: error: package com.google.common.jimfs does not exist
import com.google.common.jimfs.Jimfs;
                              ^
documentation/src/test/java/example/TempDirectoryDemo.java:135: error: cannot find symbol
			private final FileSystem fileSystem = Jimfs.newFileSystem(Configuration.unix());
			                                      ^
  symbol:   variable Jimfs
  location: class JimfsTempDirFactory
documentation/src/test/java/example/TempDirectoryDemo.java:135: error: cannot find symbol
			private final FileSystem fileSystem = Jimfs.newFileSystem(Configuration.unix());
			                                                          ^
  symbol:   variable Configuration
  location: class JimfsTempDirFactory
4 errors
4 warnings
```

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]
i was postponing this one as i wanted to have a look why it fails. i didn't dig much deep but what i found is that this test has over the ages recurring issues so i'm leaving it as it is.

**Comment by fordfrog** [comment]
what's approved is merged now. i also reordered variables on some ebuilds to remove to pkgcheck warnings.

**Comment by vaukai** [comment]
> error:



> junit-5 fails the tests for me:

oops, i didn't even try the tests. but `jimfs` does ring a bell for me. it is not yet in `::gentoo` but i have it in https://github.com/gentoo/gentoo/pull/33490 as a dependency of `sparsebitset`. and `dev-java/jimfs-1.3.0` also matches the version listed in [gradle/libs.versions.toml](https://github.com/junit-team/junit5/blob/r5.10.2/gradle/libs.versions.toml#L45). if you could merge that one first? i am still looking how to add it to the junit5 ebuild.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — COMMENTED** [review]
problem with the tests imo is that the package misses `META-INF/services` file in the jar. i suggest you first build the package using maven, then check the content of the file and replicate that within the ebuild. that should fix the tests.

**Comment by vaukai** [comment]
> problem with the tests imo is that the package misses `META-INF/services` file in the jar. i suggest you first build the package using maven, then check the content of the file and replicate that within the ebuild. that should fix the tests.

done.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
it's done now, i just merged junit.

**Comment by vaukai** [comment]
> it's done now, i just merged junit.

sorry for those many late changes ...

**Pull request closed without merging**
