### PR TITLE
dev-db/mariadb: bump to 10.5.15

### PR DESCRIPTION
**Pull request by hydrapolic**
Patches taken from 10.5.13, one patch needed updating. Compile & run test on amd64.

```
--- mariadb-10.5.13.ebuild  2022-02-28 02:11:17.000000000 +0000
+++ mariadb-10.5.15.ebuild      2022-04-01 15:34:43.519904476 +0000
@@ -10,7 +10,7 @@
        multiprocessing java-pkg-opt-2 cmake
 
 # Patch version
-PATCH_SET="https://dev.gentoo.org/~whissi/dist/${PN}/${PN}-10.5.13-patches-01.tar.xz"
+PATCH_SET="https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.5.15-patches-01.tar.xz"
 
 SRC_URI="mirror://mariadb/${PN}-${PV}/source/${P}.tar.gz
        ${PATCH_SET}"
@@ -31,7 +31,7 @@
        ?? ( tcmalloc jemalloc )
        static? ( yassl !pam )"
 
-KEYWORDS="~alpha amd64 arm arm64 ~hppa ~ia64 ~mips ppc ppc64 ~riscv ~s390 ~sparc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
 
 # Shorten the path because the socket path length must be shorter than 107 chars
 # and we will run a mysql server during test phase
```

### CODE REVIEW

**Comment by hydrapolic** [comment]
```
The servers were restarted 1109 times
Spent 8444.781 of 2900 seconds executing testcases

Completed: Failed 1/4058 tests, 99.98% were successful.

Failing test(s): connect.misc
```

```
  CURRENT_TEST: connect.misc
mysqltest: At line 62: query 'create table beers (
`Name` char(16) xpath='brandName',
`Origin` char(16) xpath='origin',
`Description` char(32) xpath='details')
engine=CONNECT table_type=XML file_name='$MYSQLTEST_VARDIR/tmp/beer.xml'
tabname='table' option_list='rownode=tr,colnode=td%n'' failed: 1105: Unsupported table type XML

The result from queries just before the failure was:
< snip >
select *from t;
ERROR HY000: Got error 174 'MakeSQL: Wrong place holders specification' from CONNECT
drop table t;
create table t engine=connect table_type=mysql
CONNECTION='mysql://root@localhost:MASTER_MYPORT/test/foobar'
  SRCDEF='SELECT 1,%n FROM DUAL WHERE %s';
ERROR HY000: (1064) You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '%n FROM DUAL WHERE 1=1 LIMIT 0' at line 1 [SELECT 1,%n FROM DUAL WHERE 1=1 LIMIT 
0]
create table t engine=connect table_type=mysql
CONNECTION='mysql://root@localhost:MASTER_MYPORT/test/foobar'
  SRCDEF='SELECT 1 FROM DUAL WHERE %s';
select *from t;
1
1
drop table t;
create table beers (
`Name` char(16) xpath='brandName',
`Origin` char(16) xpath='origin',
`Description` char(32) xpath='details')
engine=CONNECT table_type=XML file_name='MYSQLTEST_VARDIR/tmp/beer.xml'
tabname='table' option_list='rownode=tr,colnode=td%n';
```

**Comment by hydrapolic** [comment]
After adding USE=xml, the tests run properly:

```
USE='extraengine perl server xml' FEATURES='test userpriv' emerge -v1 mariadb
```

```
The servers were restarted 1112 times
Spent 8466.994 of 2934 seconds executing testcases

Completed: All 4066 tests were successful.

713 tests were skipped, 219 by the test itself.

 * Tests successfully completed
```

**Comment by Whissi** [comment]
Thanks. Like explained in our mail conversation, we are going to skip this release, the versions Gentoo currently has are the best GA releases for most common workloads. The versions released since then have serious regressions and one version got already pulled. The next releases are around the corner (hopefully this week) and current git versions are looking promising.

**Comment by hydrapolic** [comment]
> 

I've been using 10.5.15 since then on 2x RO slaves and they seem to be working just fine. Maybe we could add new versions masked since they've also fixed security issues? But as you say that new versions are going to be released soon, then we can wait. However, by checking https://jira.mariadb.org/projects/MDEV/versions/27508 it seems like the release date for 10.5.16 is set to "2022-04-29".

**Comment by mgorny** [comment]
Reopening since the bump hasn't happened for a month now and users are still stuck on the vulnerable version.

**Comment by robbat2** [comment]
@Whissi the 10.5.13 version is broken for infra as previously discussed re Galera replication getting stuck, whereas 10.5.15 works for that case - and has been running great on infra since 2022/04/05 (just over 1 month).

Yes, 10.5.14 was withdrawn because of the upgrade bug, but 10.5.15 is the best available upstream GA release.

As of writing this bug, the only upgrade bug tagged with regression as affected 10.5.15 is this one, which requires a very specific configuration flag (`innodb_encrypt_tables = ON`) that's not default at all 
https://jira.mariadb.org/browse/MDEV-27980?jql=affectedVersion%20%3D%2010.5.15%20AND%20labels%20%3D%20regression

If 10.5.16 had been released already, we could test that, but it's been sufficiently long that I don't think we should wait further.

**Comment by mgorny** [comment]
I get two test failures with this:

```
Failing test(s): client.mariadb-conv client.mariadb-conv-utf16
```

Apparently they're failing because something is outputting warnings:
```
+/var/tmp/portage/dev-db/mariadb-10.5.15/work/mariadb-10.5.15_build/client//mariadb-conv: Warning: Charset id '33' csname 'utf8mb3' try
ing to replace existing csname 'utf8'
+/var/tmp/portage/dev-db/mariadb-10.5.15/work/mariadb-10.5.15_build/client//mariadb-conv: Warning: Charset id '83' csname 'utf8mb3' try
ing to replace existing csname 'utf8'
```

Full log: 
[dev-db:mariadb-10.5.15:20220511-201451.log](https://github.com/gentoo/gentoo/files/8673415/dev-db.mariadb-10.5.15.20220511-201451.log)

**Comment by GieltjE** [comment]
While I can understand regressions holding things back, can we at least list the regressions?
Also putting the releases into ~arch would allow us to test more and at least secure network facing machines with the latest CVE patches.

**Comment by hydrapolic** [comment]
Thanks @SoapGentoo and others too.

**Pull request closed without merging**
