### PR TITLE
Mate 1.28

### PR DESCRIPTION
**Pull request by oz123**
mate 1.28. has been released, slowly adding ebuilds here.

### CODE REVIEW

**Comment by immolo** [comment]
Thanks for starting this, can you please mark this as draft as I don't want merged until I've tested it.

Are you happy to finish these moves (ebuilds should just need a `git mv`) so we aren't trending on each other toes with the commits.

**Review by immolo — APPROVED** [review]

**Review by immolo — CHANGES_REQUESTED** [review]
Missing ebuild to complete dependency check. (I know you are aware so this is just for my own tracking.)

**Comment by immolo** [comment]
I've been thinking about this more and I feel it's time to move this to an overlay to make life a little easier on both of us plus stop causing multiple PRs in the gentoo repo. I've moved your work and finished the bumps in  https://github.com/immolo/mate-overlay so please contact me on IRC or via github and I'll get you commit access sorted.

(Sorry for the noise in PRs while we figure out a system that works better for everyone)

**Comment by oz123** [comment]
There was also my old overlay...
Does that mean mate packages will move out of the main rebuild repository? 
That's not good if yes.

**Comment by immolo** [comment]
> There was also my old overlay... Does that mean mate packages will move out of the main rebuild repository? That's not good if yes.

Of course not, this is just a way to manage us working together and allow us to test new things with out worry. Think of it as a staging area.

**Comment by ceamac** [comment]
Is this PR still relevant?  I see mate 1.28 is in tree now.

**Pull request closed without merging**
