### PR TITLE
dev-db/mysql-init-scripts update init.d script for other than default running user

### PR DESCRIPTION
**Pull request by j4Hu**
mysql instance running with differend user than default "mysql". 
for example multi mysql instances, each has own user.

Signed-off-by: j4Hu github@jahu.sk

### CODE REVIEW

**Comment by hydrapolic** [comment]
Can you please open a bug report for this?

**Comment by hydrapolic** [comment]
The commit message begins with dev-db/mysql-init-scripts:... and the Signed-off-by needs to be included in the commit too.

**Comment by hydrapolic** [comment]
As an example of a standard commit message please check out https://github.com/gentoo/gentoo/commit/5cfed9ef168f047ff675081482302d5506061caa

**Comment by j4Hu** [comment]
> 
> 
> Can you please open a bug report for this?

looks like exists:
https://bugs.gentoo.org/593046

**Comment by hydrapolic** [comment]
Please squash those 3 commits into 1 with the correct format.

**Comment by j4Hu** [comment]
PL: #11819
https://github.com/gentoo/gentoo/pull/11819

**Comment by a17r** [comment]
Why did you file a new PR? Now it is not obvious at all what has been reviewed already.

**Comment by j4Hu** [comment]
> 
> 
> Why did you file a new PR? Now it is not obvious at all what has been reviewed already.

sorry but i have no idea about process. i am not developer.
all i want is functionality

**Pull request closed without merging**
