### PR TITLE
x11-misc/xsecurelock: add to portage

### PR DESCRIPTION
**Pull request by ngg**
Closes: https://bugs.gentoo.org/687070
Signed-off-by: Gergely Nagy <ngg@ngg.hu>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by ajakk** [comment]
Closing in favor of adding to GURU. Please add there if still interested in this!

**Comment by ngg** [comment]
I think this is a critical security product which is included in basically every large distro (at least Debian, Ubuntu, Arch, Fedora), it is a mistake not to include in Gentoo. There is no alternative package which would solve this problem either.

I'm not interested in using GURU as we use Gentoo on security-critical machines where we do not want to enable a community overlay. If anyone would like to add it to GURU and maintain it there, feel free to do so.

**Comment by razamatan** [comment]
+1 on what @ngg stated.  this should be supported in gentoo as it's a pretty secure and lean screen lock for X.

**Comment by ajakk** [comment]
There's not been activity on this in several years. As said before, please add to GURU if there's interest in this being in ::gentoo.

**Comment by razamatan** [comment]
do all new ebuilds need to go through guru in order to make it into gentoo?  what's the formal policy here?

**Comment by ngg** [comment]
I have no objection if someone merges this or a similar ebuild to GURU, but
I won't do that as I don't use (and do not want to use) that overlay.

**Pull request closed without merging**
