### PR TITLE
dev-java/snappy: add 1.1.10.1

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/908557

### CODE REVIEW

**Comment by fordfrog** [comment]
@vaukai do the tests pass for you? i get plenty errors like this about the undefined symbol:
```
1) shuffleDirectIntArray(org.xerial.snappy.BitShuffleTest)
java.lang.UnsatisfiedLinkError: /var/tmp/portage/dev-java/snappy-1.1.10.1/temp/snappy-1.1.10-960912c8-4e7c-4842-a363-1c41ff3dae80-libsnappyjava.so: /usr/lib64/libbitshuffle.so.0: undefined symbol: LZ4_compressBound
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.xerial.snappy.SnappyLoader.loadNativeLibrary(SnappyLoader.java:182)
	at org.xerial.snappy.SnappyLoader.loadBitShuffleApi(SnappyLoader.java:167)
	at org.xerial.snappy.BitShuffle.<clinit>(BitShuffle.java:34)
	at org.xerial.snappy.BitShuffleTest.shuffleDirectIntArray(BitShuffleTest.java:194)
```

**Comment by vaukai** [comment]
> @vaukai do the tests pass for you? i get plenty errors like this about the undefined symbol:

@fordfrog 
Tested again and it turned out tests need java 17.  Added such condition to `src_test()`.

**Comment by fordfrog** [comment]
i merged the bump. the tests are still failing for me but it might be a local issue. if the issue is not local, it will pop up from our testing infrastructure.

**Comment by vaukai** [comment]
> i merged the bump. the tests are still failing for me but it might be a local issue. if the issue is not local, it will pop up from our testing infrastructure.

Indeed, https://bugs.gentoo.org/914570 was reported.

**Pull request closed without merging**
