### PR TITLE
profiles/base/p.use: disable gdbm USE for net-firewall/fwknop by default

### PR DESCRIPTION
**Pull request by Coacher**
Otherwise it enforces server USE to all users via REQUIRED_USE.

### CODE REVIEW

**Comment by kensington** [comment]
I still hit the REQUIRED_USE with this patch applied on hardened/linux/amd64.

**Comment by Coacher** [comment]
@kensington, should be fixed now.

**Comment by kensington** [comment]
Thanks, picked as 1c63090d8c1f532cce466d799b838383121e325f...99b480992dfb2ae7559f877a46fe64129e122ceb.

**Comment by Coacher** [comment]
Thank you, @kensington.

**Pull request closed without merging**
