### PR TITLE
Remove Xen 4.2.x series

### PR DESCRIPTION
**Pull request by cardoe**
This version is unsupported and unmaintained and has been package masked for a month. Time to remove it.

### CODE REVIEW

**Comment by mgorny** [comment]
And Ian already attempted that without checking and got shouted at.

**Comment by cardoe** [comment]
I merely created this to see what the issue was that he saw without running pkgcheck locally like we discussed on IRC.

Really the issue is that xen-tools should not be masked on x86. 

--
Doug

**Comment by monsieurp** [comment]
as discussed on IRC, you're handling this PR @cardoe

**Comment by idella** [comment]
Rest assured our starting point was based upon all previous attempts. We know what we are doing. And remember it is I who is the long standing maintainer of xen and it was I who initiated this whole chain of events with Cardoe in irc today

**Comment by cardoe** [comment]
@gentoo-repo-qa-bot: rerun

**Comment by cardoe** [comment]
@mgorny does your bot not have the ability to rerun a test?

**Comment by idella** [comment]
Cardoe occasionally it gets stuck, I think, and he has to manually restart it

**Comment by mgorny** [comment]
@cardoe, it already did that. Look at the 'all checks have passed' thingie. It just doesn't leave comments when everything's fine not to spam too much.

**Pull request closed without merging**
