### PR TITLE
Update keepass-2.34.ebuild

### PR DESCRIPTION
**Pull request by wldev1**

### CODE REVIEW

**Comment by monsieurp** [comment]
Thank you for the PR. Please read carefully https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format and format your commit accordingly.

**Comment by wldev1** [comment]
I dont understand: Im not Gentoo user, so Im not able to modify it? Stupid as its FREE software editable by anyone who wish to do it. Or is it just naming itself free?

**Comment by akhuettel** [comment]
> I dont understand: Im not Gentoo user, so Im not able to modify it?

It's free and you can make as many copies as you want and modify them as much as you want.
If you want us to use your changes, you need to stick to our rules.

**Comment by akhuettel** [comment]
Oh and after reading the actual contents of the patch, please refrain from posting such garbage in the future.

**Pull request closed without merging**
