### PR TITLE
*/*: Switch proxy-maint to cmake.eclass

### PR DESCRIPTION
**Pull request by a17r**
- Only concerns EAPI-7 ported ebuilds
- See also: https://archives.gentoo.org/gentoo-dev/message/3aa1a3aeebad353a7cefcb86a8101943
- Please ACK your packages

### CODE REVIEW

**Comment by hydrapolic** [comment]
Ack

**Comment by olifre** [comment]
Very nice, ACK!

**Comment by 0xd34df00d** [comment]
liblaretz looks good, ack

**Comment by nE0sIghT** [comment]
At the 1st look it will break games-emulation/pcsx2 because of dropped multilib eclass.

**Comment by a17r** [comment]
@nE0sIghT multilib eclass is obsolete since `EAPI-6`.

**Comment by nE0sIghT** [comment]
games-emulation/pcsx2 looks good now.

**Comment by puleglot** [comment]
net-libs/libvncserver - ack

**Comment by evdenis** [comment]
net-misc/seafile-client - ack

**Comment by winterheart** [comment]
app-text/cmark: ok

**Comment by vilhelmgray** [comment]
games-action/minetest: ack
games-engines/odamex: ack
games-fps/gzdoom: ack

**Comment by lovesegfault** [comment]
app-editors/neovim: ACK
dev-lua/luv: ACK

Very nice!

**Comment by oniGino** [comment]
x11-apps/copyq: ACK

**Comment by Peter-Levine** [comment]
gtest-1.10.0.ebuild: ack
gtest-1.8.1-r1.ebuild: ack
gtest-1.9.0_pre20190607.ebuild: ack
gtest-9999.ebuild: ack

**Comment by rseichter** [comment]
media-radio/KochMorse ACK

**Comment by YangMame** [comment]
net-proxy/trojan: ack

**Comment by djc** [comment]
mail-filter/rspamd ACK

**Comment by l3u** [comment]
app-misc/vcontrold: ACK

I would really aapreciate a small hint though: I tried to update the ebuild and wanted to test it, but I can't update the manifest: ebuild yields an error:

    # ebuild vcontrold-0.98.8.ebuild digest 
    Traceback (most recent call last): 
    File "/usr/lib/python-exec/python3.6/ebuild", line 307, in <module> 
        cpv, Package.metadata_keys, myrepo=myrepo))) 
    File "/usr/lib64/python3.6/site-packages/portage/dbapi/porttree.py", line 614, in aux_get 
        myrepo=myrepo, loop=loop)) 
    File "/usr/lib64/python3.6/site-packages/portage/dbapi/porttree.py", line 702, in async_aux_get 
        proc.start() 
    File "/usr/lib64/python3.6/site-packages/_emerge/AsynchronousTask.py", line 30, in start 
        self._start() 
    File "/usr/lib64/python3.6/site-packages/_emerge/EbuildMetadataPhase.py", line 59, in _start 
        self._async_wait() 
    File "/usr/lib64/python3.6/site-packages/_emerge/AbstractPollTask.py", line 99, in _async_wait 
        self._unregister() 
    File "/usr/lib64/python3.6/site-packages/_emerge/EbuildMetadataPhase.py", line 147, in _unregister 
        self.scheduler.remove_reader(self._files.ebuild) 
    AttributeError: 'NoneType' object has no attribute 'ebuild'

is there currently something broken, or is this some weired local problem?

**Comment by linxon** [comment]
`media-video/qmplay2` — ack

merry Christmas!

**Comment by khumarahn** [comment]
net-vpn/i2pd - ack

**Comment by a17r** [comment]
Thanks everyone for checking in so far!

**Comment by hjudt** [comment]
dev-lisp/c2ffi: ACK (both c2ffi-9.0.0.9999 and c2ffi-9.0.20191017)

**Comment by AnAverageHuman** [comment]
dev-libs/stp ACK

**Comment by hsntgm** [comment]
net-analyzer/greenbone-security-assistant: ACK 
net-analyzer/gvm-libs: ACK
net-analyzer/gvmd: ACK
net-analyzer/openvas-scanner: ACK

**Comment by tietzc** [comment]
xfce-extra/xfce4-whiskermenu-plugin: ACK

**Comment by tillschaefer** [comment]
kde-misc/playbar2: ACK

**Comment by stkw0** [comment]
dev-libs/spdlog: ACK

**Comment by waebbl** [comment]
media-gfx/alembic: ack
media-gfx/yafaray: ack
sci-libs/med: ack @tamiko 
sci-libs/opencascade:7.4.0: ack

**Comment by nrdmn** [comment]
dev-lang/zig: ack

**Comment by jkroonza** [comment]
net-libs/libwebsockets: ack

**Comment by Yamakuzure** [comment]
dev-libs/aws-c-common: ack
dev-libs/aws-c-event-stream: ack
dev-libs/aws-checksums: ack
dev-libs/aws-sdk-cpp: ack

Also:
dev-games/ogre: PR is on its way, see: #13655

**Comment by zpuskas** [comment]
sci-electronics/kicad.*: ACK
app-doc/kicad-doc: ACK

**Comment by Perlovka** [comment]
dev-libs/libarcus: ack
dev-libs/libcharon: ack
dev-libs/libsavitar: ack
dev-python/uranium: ack
media-gfx/fdm-materials: ack
media-gfx/curaengine: ack
media-gfx/cura: ack

**Comment by arthurzam** [comment]
app-text/sigil: ack

**Comment by mgorny** [comment]
Feel free to presume maintainer timeout for the rest.

**Pull request merged**
