### PR TITLE
app-cdr/cdemu: Version bump to 3.1.0

### PR DESCRIPTION
**Pull request by automorphism88**
Also includes app-cdr/gcdemu, app-cdr/cdemu-daemon, and dev-libs/libmirage since these packages constitute a single release from an upstream perspective and in some cases depend on others in the set having the same `$PV`.

Ebuilds are simply copies of the previous version with keywords changed to testing and copyright year changed to 2017.

### CODE REVIEW

**Comment by automorphism88** [comment]
@mgorny: I did look at the news page on the upstream website (the [changes](http://cdemu.sourceforge.net/news/) are pretty minor across the board and don't look likely to break anything) and also tested the new version on my own computer and the new versions both build successfully and work at runtime. These packages use cmake so there's no `configure.ac` as such but as far as I can tell there are no differences that would necessitate changes in the ebuilds.

I'm not sure if the bold means there's something I should have noticed but missed, but I did go back and look at both the upstream website and the Gentoo Bugzilla for bug reports regarding these packages and didn't find any related to the new versions.

The expansion of language support may mean the `rm_po` function defined in the cdemu ebuild should be extended to the other ebuilds but that seemed like more of an enhancement that should be done separately, since as I said, the version in this PR worked when I tested it. If the localization is something that should be done with the version bump then I'll look at adding that functionality - or maybe a TODO comment?

**Comment by mgorny** [comment]
I'm talking about https://bugs.gentoo.org/show_bug.cgi?id=597922#c3.

As far as I'm concerned, you can throw all that locale magic into trash.

**Comment by automorphism88** [comment]
That bug is about an older version, not 3.1.0, and the issue has been fixed since upstream bumped the SOVERSION with 3.1.0 to address this problem.

**Comment by mgorny** [comment]
In that case, why is subslot not changed in the ebuild?

**Comment by mgorny** [comment]
The ebuilds needs much more work, and since I was planning on doing it anyway (I actually mailed the maintainer three weeks ago), it really wouldn't be appropriate or productive to throw it all on you. I'm therefore going to reject this and commit updated ebuilds later today. I'm sorry for my attitude.

**Pull request closed without merging**
