### PR TITLE
dev-python/aesara: Add blocker against dev-python/theano-pymc

### PR DESCRIPTION
**Pull request by jsmolic**
Closes: https://bugs.gentoo.org/774072

### CODE REVIEW

**Comment by thesamesam** [comment]
The blocker should be two-way, right? (added to thano-pymc, and I guess theano).

**Comment by jsmolic** [comment]
Yes, yes, we should block against theano as well

**Comment by jsmolic** [comment]
theano and theano-pymc should probably block each other as well

**Comment by mgorny** [comment]
Maybe we should strip `bin/__init__.py` in all packages. It looks namespace-ish.

**Review by mgorny — APPROVED** [review]
Looks good, thanks!

**Pull request closed without merging**
