### PR TITLE
dev-vcs/mercurial: no py2, no zsh-completion use

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-2.3.99, Repoman-2.3.22
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
@cedk ping

**Comment by Alessandro-Barbieri** [comment]
@cedk ping, please merge before I have to rebase another time

**Comment by Alessandro-Barbieri** [comment]
@cedk ping

**Review by juippis — COMMENTED** [review]
On a 2nd thought, since mercurial is quite big to compile, we wouldn't want to push this update to users who have already installed this version. However I see a new version, 5.8 is available. Could you bump mercurial to latest version in this / a separate PR? 

I did a **quick** peek at setup.py and Makefile and doesn't look like there's been many relevant changes regarding the ebuild itself, just some test cases perhaps need an udpate.

**Comment by juippis** [comment]
I'll cherry-pick the -9999 change at some point today, it seems to work.

**Comment by juippis** [comment]
https://bugs.gentoo.org/792876 mercurial-5.8 bump request.

**Pull request closed without merging**
