### PR TITLE
sci-libs/gdal: fix compilation with >=app-text/poppler-0.64.0

### PR DESCRIPTION
**Pull request by ConiKost**
Closes: https://bugs.gentoo.org/656252
Package-Manager: Portage-2.3.40, Repoman-2.3.9

### CODE REVIEW

**Comment by Amynka** [comment]
Looks nice lets wait for ci to finish..

**Comment by a17r** [comment]
this is really a buildfix with poppler-0.64.0, it would be nice to have in git message :)

**Comment by ConiKost** [comment]
Better? :)

**Comment by Amynka** [comment]
I think its extremely bad idea to add it to stable.. Can you please make revbump and put it to ~arch?

**Comment by ConiKost** [comment]
Done.

**Pull request closed without merging**
