### PR TITLE
media-video/obs-studio: version bump to 23.1.0 (was 23.0.2)

### PR DESCRIPTION
**Pull request by Chiitoo**
Just a simple copy and bump point release hotfix.

### CODE REVIEW

**Comment by juippis** [comment]
Btw, there was a user having trouble with obs-studio yesterday and while reading build.log came across this:

```
16:54  spacedust: /var/tmp/portage/media-video/obs-studio-23.0.1/temp/environment: line 
                  2379: gnome2_icon_cache_update: command not found
```

Asked them to make a bug report but since you opened this PR while I had this in backlog... could you investigate? :)

Btw icon_cache_update is called from xdg or xdg-utils eclass now (but the gnome2-utils should still work...)

**Comment by Chiitoo** [comment]
Hmmm, yeah, that's pretty weird.

I think I had seen the gnome2 one being deprecated at some point, but completely forgot about it.  Will need to get rid of that in some LXQt ebuilds too...

Thanks!

**Comment by Chiitoo** [comment]
Switched from using 'gnome2-utils' to 'xdg-utils' for icon_cache_update.

**Comment by Chiitoo** [comment]
Okay, not that weird since the thing is not included in EAPI="7" (thanks, @leio for pointing that out!).

Might also switch from 'xdg-utils' to 'xdg' instead of manually calling for these things...

**Comment by Chiitoo** [comment]
A release candidate for 23.1.0 has been out since 2019-03-29 already, so might as well wait for that.

**Pull request closed without merging**
