### PR TITLE
kde-apps/kcalc: Add missing DEPENDs, bug 568818

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/kde

**Comment by kensington** [comment]
Is a revbump definitely needed here? Also, I couldn't find any direct gettext usage (I saw the indirect usage via ki18n, and it is an rdepend there).

**Comment by a17r** [comment]
definitely not ;)

**Comment by kensington** [comment]
Thanks, picked as af0270a710f7c151c7db687ee233d7b29282e9d1.

**Pull request closed without merging**
