### PR TITLE
net-im/discord-bin: refactor the Discord ebuild

### PR DESCRIPTION
**Pull request by ran-dall**
This is a general refactor of the Discord ebuild. It cleans up several things and fixes permissions, mostly. It seems to improve performance greatly.

Closes: https://bugs.gentoo.org/845219
Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
1. Please use `pkgdev commit` or a similar tool to get the commit message format right (`cat/pkg: ...`)
2. Please describe your changes in the commit message.
3. If possible, please (for convenience) share a unified diff (`diff -u`) of the two ebuilds in this PR to ease review.

**Comment by ran-dall** [comment]
@thesamesam Alright. Sorry about that. I'll look at `pkgdev` and read up on it. Thanks for the tips, mate; good looking out.

Here's that diff...

```diff
$ diff /var/db/repos/gentoo/net-im/discord-bin/discord-bin-0.0.17.ebuild /var/db/repos/gentoo/net-im/discord-bin/discord-bin-0.0.17-r1.ebuild 
6c6,7
< MY_PN="${PN%-bin}"
---
> MY_PN="${PN/-bin}"
> MY_PV="${PV/-r*}"
9c10,16
< inherit desktop linux-info optfeature pax-utils unpacker
---
> CHROMIUM_LANGS="
> 	am ar bg bn ca cs da de el en-GB en-US es es-419 et fa fi fil fr gu he hi
> 	hr hu id it ja kn ko lt lv ml mr ms nb nl pl pt-BR pt-PT ro ru sk sl sr sv
> 	sw ta te th tr uk vi zh-CN zh-TW
> "
> 
> inherit chromium-2 desktop linux-info optfeature pax-utils unpacker
13,14c20
< SRC_URI="https://dl.discordapp.net/apps/linux/${PV}/${MY_PN}-${PV}.deb"
< S="${WORKDIR}"
---
> SRC_URI="https://dl.discordapp.net/apps/linux/${MY_PV}/${MY_PN}-${MY_PV}.tar.gz"
18,19c24
< KEYWORDS="amd64"
< RESTRICT="mirror bindist"
---
> KEYWORDS="~amd64"
51a57,58
> RESTRICT="bindist mirror strip test"
> 
53,63c60,70
< 	opt/discord/${MY_BIN}
< 	opt/discord/chrome-sandbox
< 	opt/discord/libffmpeg.so
< 	opt/discord/libvk_swiftshader.so
< 	opt/discord/libvulkan.so
< 	opt/discord/libEGL.so
< 	opt/discord/libGLESv2.so
< 	opt/discord/libVkICD_mock_icd.so
< 	opt/discord/swiftshader/libEGL.so
< 	opt/discord/swiftshader/libGLESv2.so
< 	opt/discord/swiftshader/libvk_swiftshader.so
---
> 	${DESTDIR}/${MY_BIN}
> 	${DESTDIR}/chrome-sandbox
> 	${DESTDIR}/libffmpeg.so
> 	${DESTDIR}/libvk_swiftshader.so
> 	${DESTDIR}/libvulkan.so
> 	${DESTDIR}/libEGL.so
> 	${DESTDIR}/libGLESv2.so
> 	${DESTDIR}/libVkICD_mock_icd.so
> 	${DESTDIR}/swiftshader/libEGL.so
> 	${DESTDIR}/swiftshader/libGLESv2.so
> 	${DESTDIR}/swiftshader/libvk_swiftshader.so
67a75,91
> S="${WORKDIR}/${MY_BIN}"
> 
> DESTDIR="/opt/${MY_BIN}"
> 
> pkg_pretend() {
> 	chromium_suid_sandbox_check_kernel_config
> }
> 
> src_unpack() {
> 	unpack ${MY_PN}-${MY_PV}.tar.gz || die
> }
> 
> src_configure() {
> 	chromium_suid_sandbox_check_kernel_config
> 	default
> }
> 
70a95,100
> 	rm postinst.sh
> 
> 	pushd "locales/" || die
> 	chromium_remove_language_paks
> 	popd
> 	
72,73c102,103
< 		-e "s:/usr/share/discord/Discord:discord:" \
< 		usr/share/${MY_PN}/${MY_PN}.desktop || die
---
> 	-e "s:/usr/share/discord/Discord:${DESTDIR}/${MY_BIN}:" \
> 	${MY_PN}.desktop || die
77,78c107,118
< 	doicon usr/share/${MY_PN}/${MY_PN}.png
< 	domenu usr/share/${MY_PN}/${MY_PN}.desktop
---
> 	doicon -s 256 ${MY_PN}.png
> 
> 	# Install desktop file
> 	domenu ${MY_PN}.desktop
> 
> 	exeinto ${DESTDIR}
> 	doexe ${MY_BIN} chrome-sandbox libEGL.so libffmpeg.so libGLESv2.so  libvk_swiftshader.so
> 
> 	insinto ${DESTDIR}
> 	doins chrome_100_percent.pak chrome_200_percent.pak icudtl.dat resources.pak snapshot_blob.bin v8_context_snapshot.bin
> 	insopts -m0755
> 	doins -r locales resources swiftshader
80,83c120,122
< 	insinto /opt/${MY_PN}
< 	doins -r usr/share/${MY_PN}/.
< 	fperms +x /opt/${MY_PN}/${MY_BIN}
< 	dosym -r /opt/${MY_PN}/${MY_BIN} /usr/bin/${MY_PN}
---
> 	# chrome-sandbox requires the setuid bit to be specifically set.
> 	# See https://github.com/electron/electron/issues/17972
> 	fperms 4755 ${DESTDIR}/chrome-sandbox || die
85c124,128
< 	pax-mark -m "${ED}"/opt/${MY_PN}/${MY_PN}
---
> 	pax-mark m ${DESTDIR}/${MY_BIN} || die "could not set proper PAX permissions"
> 
> 	dosym ${DESTDIR}/${MY_BIN} /usr/bin/${MY_PN} || die
> 
> 	dodir ${DESTDIR}
88a132,135
> 	xdg_desktop_database_update
> 	xdg_icon_cache_update
> 	xdg_mimeinfo_database_update
> 	
92a140,146
> 
> pkg_postrm() {
> 	xdg_desktop_database_update
> 	xdg_icon_cache_update
> 	xdg_mimeinfo_database_update
> }
> 
```

**Comment by thesamesam** [comment]
Looking good! Seems pretty reasonable to be using the chromium-2 eclass bits like we do in other places.

**Comment by ran-dall** [comment]
@thesamesam Thanks mate, `pkgdev` is the bee's knees! Way better than Repoman. Thanks 1000x.

Also, I wouldn't mind being made the maintainer for Discord, as this would be, after all, my ebuild now...

**Comment by thesamesam** [comment]
... and:
```
 * QA Notice: Files built without respecting CFLAGS have been detected
 *  Please include the following list of files in your report:
 * /opt/Discord/libEGL.so
 * /opt/Discord/swiftshader/libEGL.so
 * /opt/Discord/swiftshader/libGLESv2.so
 * /opt/Discord/chrome-sandbox
 * /opt/Discord/libffmpeg.so
 * /opt/Discord/libvk_swiftshader.so
 * /opt/Discord/libGLESv2.so
 * /opt/Discord/Discord

 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /opt/Discord/Discord
 * /opt/Discord/chrome-sandbox
 * /opt/Discord/libEGL.so
 * /opt/Discord/libGLESv2.so
 * /opt/Discord/libffmpeg.so
 * /opt/Discord/libvk_swiftshader.so
 * /opt/Discord/swiftshader/libEGL.so
 * /opt/Discord/swiftshader/libGLESv2.so

 * QA Notice: Pre-stripped files found:
 * /opt/Discord/libEGL.so
 * /opt/Discord/swiftshader/libEGL.so
 * /opt/Discord/swiftshader/libGLESv2.so
 * /opt/Discord/chrome-sandbox
 * /opt/Discord/libffmpeg.so
 * /opt/Discord/libvk_swiftshader.so
 * /opt/Discord/libGLESv2.so
 * /opt/Discord/Discord
```

Did you try installing this? These warnings weren't there before (were silenced appropriately).

**Comment by thesamesam** [comment]
OK, fixed all of above. Please verify the language pack stuff is necessary - I've got no idea if it is.

**Comment by thesamesam** [comment]
We changed from /opt/discord/ to /opt/Discord/, but I notice the tarball has /usr/share/discord (so, lower case). Should we be using /opt/discord then?

**Comment by ran-dall** [comment]
@thesamesam As for your comment (https://github.com/gentoo/gentoo/pull/25542#issuecomment-1130992557), those files are typical in all electron redistributables. It is sometimes possible to delete them, though, and force the app to use locally installed ones, but it doesn't seem possible in this particular case. I believe it did silence them appropriately, as well.

**Pull request closed without merging**
