### PR TITLE
vgm fixes

### PR DESCRIPTION
**Pull request by olifre**
- Remove unused versionator inheritance. 
- Restrict test-suite to USE flag combinations supported by upstream's test-suite. 
- Block `sci-physics/root[root7}` for release 4.4 of VGM since this activates `std=c++14` which will only be supported starting from next release.

### CODE REVIEW

**Comment by olifre** [comment]
Ping @amadio since parts of these fixes were born from discussion in #9643 .

**Comment by mgorny** [comment]
Thanks. I'll repoman this and merge it if it passes.

**Comment by amadio** [comment]
@mgorny Please let me handle this. I am rebuilding sci-physics/root on my machine to test. I am considering removing USE=root7, as that only enables some experimental features and because it may cause problems with other packages that depend on ROOT due to the strict C++standard requirement for things linking with ROOT.

**Comment by amadio** [comment]
Well, too late I guess. Anyway, I will update sci-physics/vgm if I modify sci-physics/root to remove the USE=root7 flag.

**Comment by amadio** [comment]
FYI, this is what I get when trying to emerge vgm after recompiling ROOT:
```
...
-- Found CLHEP Version 2.4.0.4
-- Found CLHEP: /usr/lib/libCLHEP.so (Required is at least version "2.4.0.4") 
-- Found Geant4 CMake configuration in /usr/lib/Geant4-10.3.0
-- Found CLHEP in /usr/lib
-- Found ROOT 6.14/02 in /usr/lib64/root/6.14
CMake Error at cmake/VGMRequiredPackages.cmake:39 (find_package):
  By not providing "FindG4Root.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "G4Root", but
  CMake did not find one.

  Could not find a package configuration file provided by "G4Root" with any
  of the following names:

    G4RootConfig.cmake
    g4root-config.cmake

  Add the installation prefix of "G4Root" to CMAKE_PREFIX_PATH or set
  "G4Root_DIR" to a directory containing one of the above files.  If "G4Root"
  provides a separate development package or SDK, be sure it has been
  installed.
Call Stack (most recent call first):
  CMakeLists.txt:57 (include)


-- Configuring incomplete, errors occurred!
```
I have `sci-physics/geant` installed with all USE flags enabled, and this is my config for vgm:
```
# FEATURES=test emerge -av1 vgm

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] sci-physics/vgm-4.4::gentoo  USE="geant4 root* test* -doc -examples" 0 KiB
```

**Comment by olifre** [comment]
> It does work without FEATURES=test, though, so I guess this is not a problem. It might just trigger a bug from tinderbox sometime.

Thanks for reporting that! 
That indeed slipped through my fingers - `sci-physics/vgm[test]` indeed should depend on `sci-physics/geant-vmc[g4root]`, since for all tests of VGM to run, g4root is needed for the tests to link against. 
I'll fix this in a subsequent PR.

**Comment by amadio** [comment]
Thanks for fixing it!

**Pull request closed without merging**
