### PR TITLE
dev-python/gevent: bump to 1.4.0

### PR DESCRIPTION
**Pull request by linux4life798**
Bumping gevent to the latest upstream stable, version 1.4.0.
This builds on amd64.

Signed-off-by: Craig Hesling <hesling@chromium.org>

### CODE REVIEW

**Comment by hartwork** [comment]
Hi Craig, I'll try to have a close look today.

**Comment by hartwork** [comment]
Merged now as 48ddca6fa973721e4647ac464fc5def7bddfe748. I added some improvements on top ec6bbbcd2e357c495f3def3910a519d7b5ea6da4. It would have been hard to justify asking for these improvements as "required" yet at the same time I felt they should be done. I hope this two-commit approach without review ping-pong is okay with you for this case.

**Comment by linux4life798** [comment]
Awesome. Thanks!

**Comment by linux4life798** [comment]
Note for posterity, this package (and the previous 1.3.7) seems to have some issues cross compiling for arm.
I am experimenting with a few patches:
* crrev.com/c/2021740
* crrev.com/c/2021739

**Comment by hartwork** [comment]
Sounds like something to take to either bugs.gentoo.org or gevent upstream.

**Comment by linux4life798** [comment]
Roger that.

I opened a gentoo bug: https://bugs.gentoo.org/707024
The proposed solution is: https://github.com/linux4life798/gentoo/commit/3bf7986f8fc1e19ecfc57800858d3f67d98dd707

**Pull request closed without merging**
