### PR TITLE
app-portage/pkg-testing-tools: moving to a snapshot

### PR DESCRIPTION
**Pull request by scardracs**
On that snapshot --autounmask=n is removed, as it could be a problem for these that use auto test-suite, like lxd and arch-testing.

Signed-off-by: Marco Scardovi <mscardovi@icloud.com>

### CODE REVIEW

**Comment by slashbeast** [comment]
Over the weekend I will go over whatever is pending there in issues and pull request and make proper release, it will include this change, I'd prefer this over going with snapshot. Would that work for you?

**Comment by scardracs** [comment]
> Over the weekend I will go over whatever is pending there in issues and pull request and make proper release, it will include this change, I'd prefer this over going with snapshot. Would that work for you?

It used to work on my lxd container without much problems but yes, it will be definitely better to make a proper release 😅

**Comment by scardracs** [comment]
Leave it up to you

**Comment by slashbeast** [comment]
Well overdue as it is, it is now present in fe9737e720cf5820a91982c7ec709d80ef676b94

**Pull request closed without merging**
