### PR TITLE
sys-devel/gettext: build against java >=8

### PR DESCRIPTION
**Pull request by neeshy**

### CODE REVIEW

**Comment by neeshy** [comment]
@gentoo/java Maybe you guys can take a look?

**Comment by neeshy** [comment]
Related: https://bugs.gentoo.org/888996

**Comment by neeshy** [comment]
I'm gonna do it. I'm gonna ping @thesamesam and no one can stop me.

**Comment by neeshy** [comment]
@mgorny

**Comment by vaukai** [comment]
> @gentoo/java Maybe you guys can take a look?

See https://bugs.gentoo.org/888996#c10

**Comment by vaukai** [comment]
@thesamesam 
also `22.4` could be switched without further changes, if it's worth the effort.

**Pull request closed without merging**
