### PR TITLE
media-libs/mesa: introduce X flag / enable wayland-only systems

### PR DESCRIPTION
**Pull request by trilean**
See https://bugs.gentoo.org/560096. This is a continuation of #4374.

This PR introduces an X use-flag for Mesa. This makes it possible to build Mesa without GLX and therefore without XLib & friends. To make existing packages not break I've `sed`ed the entire tree and replaced most dependencies on `media-libs/mesa` with `media-libs/mesa[X(+)]`. Exceptions are:
* no change if ebuild depends on virtual/opengl
* obvious packages (such as weston) didn't get the mesa[X] dependency

# Obvious
* dev-cpp/waylandpp
* dev-games/ogre (only for USE=opengl)
* dev-libs/efl (only for USE="opengl X")
* dev-libs/weston
* dev-qt/qtgui (only for USE="xcb")
* dev-qt/qtwayland
* gui-libs/wlroots
* kde-frameworks/kwayland
* x11-libs/libva-intel-driver (depends on mesa[X] via x11-libs/libva[X] -> virtual/opengl)

# DONE
* dev-qt/qtgui
* media-libs/libepoxy
* x11-libs/cairo
* x11-libs/gtk+

# TODO
* sci-electronics/kicad (uses wxGTK, I'll test this myself)
* sys-apps/kmscon (added `COMMON_DEPEND="media-libs/mesa[X(+)]"` as stop-gap)
* x11-terms/kitty (gles headers are #include'd)
* media-plugins/gst-plugins-vaapi (does `if use opengl || use gles2` in `src_configure`)
* media-tv/kodi (it should be easy to make GLX optional but I have no way of testing it)

### CODE REVIEW

**Comment by Arfrever** [comment]
One pull request per package, or at least one pull request per group of packages with the same maintainer, would have been better.

**Comment by SoapGentoo** [comment]
Why the default `(+)`?

**Comment by trilean** [comment]
> Why the default `(+)`?

https://bugs.gentoo.org/560096#c22:

> Aside: make the dependency media-libs/mesa[X(+)] so that versions of Mesa that don't have the X flag will be accepted. The (+) means that if IUSE doesn't contain X then assume its functionality is present.

What do we do about the QA issues? They're not related to my PR but existing issues in the tree.

**Comment by mgorny** [comment]
On Thu, 2019-06-27 at 00:55 -0700, Philipp Ammann wrote:
> > What do we do about the QA issues? They're not related to my PR but existing issues in the tree.
> 

They are fixed now, so please rebase.

**Comment by trilean** [comment]
> They are fixed now, so please rebase.
Rebase and force-push over the existing PR? I'll do that in the evening (UTC+2).

**Comment by trilean** [comment]
I've rebased the PR again, fixing a new conflict.

**Comment by trilean** [comment]
And another rebase...can we move this forward?

**Comment by mattst88** [comment]
Sorry, I don't know how this fell off my radar. I've committed the first two patches (and modified the second to only modify mesa-9999 since there's so much potential for breakage).

I'm concerned about the 3rd patch. I see lots of packages left that look like they should be modified. media-libs/waffle for instance has a USE=X flag. Don't you think it should depend on mesa[X(+)?]?

**Comment by trilean** [comment]
My reasoning was that it's better to make everything that depends on mesa now require the X flag and sort out those that don't later. That way we don't cause any breakage because there's no change from the status quo.

IMO users will try to build wayland-only systems and will report packages that needlessly depend on `media-libs/mesa[X]`.

In case of `media-libs/waffle` it certainly looks like it should depend on `media-libs/mesa[X?]` since the X flag enables GLX (as it does in mesa): `$(meson_feature X glx)`.

**Comment by jonhere** [comment]
Is there a reason not to take the "depends" patch?
From what I can tell the issue is there may be additional indirect dependencies also (e.g. just uses GTK but needs and expects X.) This does not change the correctness of the patch.
The only potential breakage I see is when you explicitly "enable the new feature" of no X, this isn't the default and should have no impact on existing systems.

**Comment by mattst88** [comment]
Thanks, merged (after some updates) as commit 97c3d2d26f9cc06c46d0c479f67b446214177463.

**Comment by Arfrever** [comment]
New ebuilds missed by that commit:
media-tv/kodi-18.3-r1

**Pull request closed without merging**
