### PR TITLE
sys-power/powertop: version bump

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by l29ah** [comment]
On Sun, Dec 03, 2017 at 07:30:50AM -0800, Gentoo repository mirror & CI project bot wrote:
> **If there is no bug open for this pull request, please open one. Otherwise, please link it to the commit messages as noted above.**

No.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by holgersson32644** [comment]
Hi, as another powertop user I’d like to thank you for the ebuild!
I have a few suggestions:
- Could you please rename the distfile to ${P}.tar.gz? ( SRC_URI="... -> ${P}.tar.gz")
- according to http://www.openwall.com/lists/kernel-hardening/2017/02/08/32
CONFIG_TIMER_STATS is entirely dropped in 4.11, so please drop that option or add a kernel version detection
- Please rebase after your commited changes (before you push). You can do that by running the following
`git git checkout master && git fetch --all && git reset --hard <upstream>/master && git checkout <branch> && git rebase --ignore-date master`

Thanks in advance!

**Comment by flappyports** [comment]
no activity

**Comment by holgersson32644** [comment]
It's inside the tree anyways:
commit 56d45d2e211908e6a4055c67d798c2a90395e77d
Author: Mike Frysinger <vapier@chromium.org>
Date:   Wed Jan 24 18:34:54 2018 -0500

    sys-power/powertop: version bump to 2.9 #637342

**Comment by flappyports** [comment]
Good to see.  Leave it to vapier to not close the PR or associate it to the contributor (assuming your changes were what he merged).

**Pull request closed without merging**
