### PR TITLE
latex-package.eclass:  allow passing arguments to pdflatex

### PR DESCRIPTION
**Pull request by ghostav**
allow passing arguments to tex compiler

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. This PR can't go further: eclass changes have to be discussed on the @gentoo-dev mailing list first. Send your patch to the mailing list and have someone sign off on it. We'll take it from there. Sorry.

**Comment by ghostav** [comment]
Didn't know that. Just got told to do a PR in bugzilla: https://bugs.gentoo.org/show_bug.cgi?id=576424

**Comment by aballier** [comment]
nah, it's ok in that case :)

**Comment by aballier** [comment]
also, please follow: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format
for the commit message

**Comment by aballier** [comment]
could you please squash the commits ? ('git rebase -i' allows to do that easily); you'll need to push --force afterwards, but it's ok

**Comment by aballier** [comment]
merged, thanks!

**Comment by ghostav** [comment]
your welcome!
One last question: in order to apply this to ebuilds (e.g. dev-tex/minted) which way have I to go? just create a PR or, as mentioned for submitting ebuilds, create a bug report first?

**Comment by aballier** [comment]
it depends on the maintainer I think; I tend to prefer github PR because it is simpler for me, but some devs do not use github I think; if I were you, I'd try a github PR first, and if nothing happens within a few days, file a bug report linking to the PR for the patch

**Pull request merged**
