### PR TITLE
dev-libs/xapian: Add subslot, remove .la file, ewarn -> einfo

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by blueness** [comment]
you have made more changes than just add a subslot.

**Comment by blueness** [comment]
sorry i should add i iwll add the  subslot, but i need to look at 1.2 as well.

**Comment by blueness** [comment]
The subslot names are going to be 1.2.<abi> for the 1.2 series and 1.3.<abi> for the 1.3.

**Comment by a17r** [comment]
So, what about the other changes? I could have perfectly well rebased the commit against the now subslotted ebuid.

**Comment by monsieurp** [comment]
@blueness @kensington what's the deal with this PR?

**Comment by blueness** [comment]
the pr globs together a series of unrelated fixes which i can't just commit

1. i don't see the dependency on pkg-config.  to convince myself i'm not overlooking anything, i took a stage3 amd64, removed pkg-config and emerged successfully.  while the pkg does include .pc files, it doesn't required pkg-config to build.

2. i have confirmed the REQUIRED_USE="inmemory? ( chert )".  this fits the old 1.2 behavior.  it should be fixed in the configure.ac file, but the REQUIRED_USE is good enough for now.

3. ewarn was requested by the original ebuild writer, so i'm not going to drop it for einfo.

4. i want prefix team to test the ${D} to ${ED} switch.

5. the first `|| die's in src_install()` is correct. the second is unnecessary because we are guaranteed something is at "${D}usr/share/doc/${PF}" else the previous `|| die` would have been triggered.

6. i'll put in the removal of the .la files, but i'm not 100% convinced this will be okay.

again, each issue needs to be its own commit so that if there's an issue with one of the changes, it can be reverted in isolation.

anyhow, only open issue, if we want ${D} -> ${ED}, let's get an ack from prefix.

finally these sorts of discussions should happen on our bugzilla so we have a history of non-trivial changes to ebuilds.

**Comment by a17r** [comment]
OK then.

**Comment by blueness** [comment]
@a17r i made the switch to einfo.  its not that big a deal.  the last item after that is prefix support and i'd like the team to test it unless you use prefix personally.

**Pull request closed without merging**
