### PR TITLE
www-apps/kibana-bin: add license for bundled libs

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.5, Repoman-2.3.2

https://bugs.gentoo.org/show_bug.cgi?id=617716

### CODE REVIEW

**Comment by mgorny** [comment]
```
$ find -name 'LICENSE*' | wc -l
673
```

**Comment by mgorny** [comment]
```
$ license-checker --csv | cut -d, -f2 | sort -u 
"Apache*"
"Apache 2.0"
"Apache-2.0"
"BSD"
"BSD*"
"BSD-2-Clause"
"BSD-3-Clause"
"BSD-3-Clause OR MIT"
"CC-BY-4.0"
"ISC"
"license"    # <- this is header, ignore it
"MIT"
"MIT*"
"(MIT AND CC-BY-3.0)"
"(MIT OR Apache-2.0)"
"MIT/X11"
"OFL-1.1 AND MIT"
"UNKNOWN"
"Unlicense"
"WTFPL"
```

Now, the UNKNOWNs are:
```
$ license-checker --csv | grep UNKNOWN
"buffers@0.1.1","UNKNOWN","https://github.com/substack/node-buffers"
"bytes@1.0.0","UNKNOWN","https://github.com/visionmedia/bytes.js"
"css-parse@1.0.4","UNKNOWN",""
"css-stringify@1.0.5","UNKNOWN",""
"css@1.0.8","UNKNOWN",""
"indexof@0.0.1","UNKNOWN",""
"ripemd160@0.2.0","UNKNOWN","https://github.com/cryptocoinjs/ripemd160"
"uglify-js@2.2.5","UNKNOWN","https://github.com/mishoo/UglifyJS2"
```

However, this only covers ~600 of the files. The tool probably looks only for nodejs modules.

**Comment by hydrapolic** [comment]
Seems I missed CC-BY-3.0, others should be fine I suppose?

**Comment by mgorny** [comment]
Well, I suppose Unlicense might be mentioned since we have it explicitly.

**Comment by hydrapolic** [comment]
Thanks, added. I thought it's the same as public domain.

**Comment by hydrapolic** [comment]
Thank you

**Pull request closed without merging**
