### PR TITLE
dev-libs/criterion: improvements

### PR DESCRIPTION
**Pull request by hydrapolic**
Closes: https://bugs.gentoo.org/703530

### CODE REVIEW

**Comment by juippis** [comment]
This doesn't apply cleanly anymore, could you please rebase and update?

**Comment by hydrapolic** [comment]
Yes, cmake-utils got replaced, will do, thanks.

**Comment by hydrapolic** [comment]
Pushed an update, but the tests fail because emake in https://github.com/gentoo/gentoo/blame/master/eclass/cmake.eclass#L570 is called like:
make 'VERBOSE=1 criterion_tests'
instead of
make VERBOSE=1 criterion_tests
as before in cmake-utils. Because of that, the test applications are not built and the tests are failing.

Email sent to @a17r

**Comment by hydrapolic** [comment]
@juippis, the cmake eclass is fixed, now the tests should pass fine (tested on amd64). Thanks

**Comment by hydrapolic** [comment]
Thanks @juippis

**Pull request closed without merging**
