### PR TITLE
bazel.eclass: add support for a custom bazel executable

### PR DESCRIPTION
**Pull request by gburgessiv**
Multiple bazel packages can be installed in different `SLOT`s if you use version suffixes, e.g., `/usr/bin/bazel-5`, `/usr/bin/bazel-6`, etc. These can be easily simultaneously supported with an eclass param.

/cc @vapier, @perfinion

### CODE REVIEW

**Comment by gburgessiv** [comment]
Friendly ping :)

**Comment by xgqt** [comment]
@gburgessiv so this is meant for some future effort of making bazel SLOTtable?

**Comment by SoapGentoo** [comment]
and what about revdeps? Every slot disaster starts with someone thinking slots solve their problem.

**Comment by gburgessiv** [comment]
Uhh, ignore the recent changes I pushed - completely forgot I had this up & didn't use a non-`master` branch for sending this PR out; sorry.

> @gburgessiv so this is meant for some future effort of making bazel SLOTtable?

In ChromeOS, Bazel is currently SLOTable, yeah. We're shipping both 5 and 6 simultaneously. I don't intend to personally make Bazel SLOTable in Gentoo, but wanted to see if this CL would be useful/appreciated upstream anyway.

> and what about revdeps? Every slot disaster starts with someone thinking slots solve their problem.

_At the moment_, the story here isn't terrible on ChromeOS. This may be a product of our small number of bazel users, though.

**Pull request closed without merging**
