### PR TITLE
net-libs/nodejs: Bump to 17.7.1

### PR DESCRIPTION
**Pull request by guyu2876**
Closes: https://bugs.gentoo.org/829813
Signed-off-by: Yu Gu <guyu2876@gmail.com>

### CODE REVIEW

**Comment by theblobscp** [comment]
Can you update this to v17.8.0?

**Comment by guyu2876** [comment]
> Can you update this to v17.8.0?

Yes I can, but it need maintainer's ack. And I'm not sure this ebuild works well enough. So I prepared close this pr. If you indeed need 17.8.0, you can search it in overlay or make your own overlay.

**Comment by theblobscp** [comment]
Yeah I have no idea on how to make one so ill just take what I can get

**Comment by theblobscp** [comment]
Why did you close this?

**Comment by guyu2876** [comment]
> Why did you close this?

Because I think this pr won't be merged. Just wait maintainer's bump. Or I can help you get what you want.
follow this guide https://wiki.gentoo.org/wiki/Eselect/Repository
and add respository pg_overlay, you can find it by `eselect-repository list` and set it.
then you can install nodejs 17.7.1 from this overlay.
If you want 17.8.0, I would like to add it to my overlay for you.

**Pull request closed without merging**
