### PR TITLE
mail-filter/rspamd: Bump to version 1.5.7

### PR DESCRIPTION
**Pull request by croessner**

### CODE REVIEW

**Comment by croessner** [comment]
@djc Hopefully better this time ;-)

**Comment by djc** [comment]
Why do we need the patch? Is the patch upstream, as well?

**Comment by croessner** [comment]
No, but Vsevelod made a mistake and told me that I would have to patch it. He released too soon and seconds later, when I tried to build, it failed. And he does not want to release a 1.5.8 or 1.5.7.1 :-)

But he pointed me to the wrong patch that Andrew Lewis had cherry-picked

**Comment by croessner** [comment]
They aslo no longer provide the tar ball on there homepage

**Comment by croessner** [comment]
Would you PLEASE commit this? There is everything fine with this ebuild. And I need it on production systems now.

**Comment by djc** [comment]
Why do you need it so badly?

I looked at the home page, and 1.5.7 still appears to be linked there.

**Comment by djc** [comment]
Cherry-picked as ddd3d83f783a7ea13b44a28fd3f8dce0ec39f6d4.

**Pull request closed without merging**
