### PR TITLE
dev-libs/skalibs: revbump for upstream bugfixes

### PR DESCRIPTION
**Pull request by smaeul**
Fixes https://bugs.gentoo.org/show_bug.cgi?id=617976

### CODE REVIEW

**Comment by williamh** [comment]
Please rename the patches to something like skalibs-2.5.0.0-what-it-does.patch so they can be referred to in the ebuild as "${FILESDIR}"/${P}-what-it-does.patch

**Comment by smaeul** [comment]
@williamh renamed

**Comment by williamh** [comment]
I'll merge it later today or tomorrow.

**Comment by mgorny** [comment]
@williamh, ping.

**Comment by williamh** [comment]
There is a  new version of skalibs that should take care of this. Please re-open if it doesn't. Thanks.

**Pull request closed without merging**
