### PR TITLE
media-fonts/*: Add missing FONT_S assignment.

### PR DESCRIPTION
**Pull request by ulm**

### CODE REVIEW

**Comment by janhenke** [comment]
For media-fonts/jetbrains-mono: Looks good to me

**Comment by juippis** [comment]
Why is this required? The eclass has, 
`FONT_S=${FONT_S:-${S}}`
which to me looks like it's giving the `${S}` value unless defined otherwise?

**Comment by SoapGentoo** [comment]
@juippis that only works if you define `FONT_S` before the inherit. This whole eclass is a mess to be honest.

**Comment by juippis** [comment]
I only now saw a bug being linked, these mobile devices...

**Pull request closed without merging**
