### PR TITLE
sci-astronomy/stellarium: fix test on x86

### PR DESCRIPTION
**Pull request by DarthGandalf**
Patch from https://github.com/Stellarium/stellarium/issues/2460

Closes: https://bugs.gentoo.org/847064
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Alexey Sokolov <alexey+gentoo@asokolov.org>

```diff
--- stellarium-0.22.1.ebuild	2022-05-24 22:42:13.648556452 +0100
+++ stellarium-0.22.1-r1.ebuild	2022-05-24 22:45:30.482002494 +0100
@@ -27,7 +27,7 @@ SRC_URI="
 
 LICENSE="GPL-2+ SGI-B-2.0"
 SLOT="0"
-KEYWORDS="amd64 ppc ppc64 ~riscv ~x86"
+KEYWORDS="~amd64 ~ppc ~ppc64 ~riscv ~x86"
 IUSE="debug deep-sky doc gps media nls stars telescope test webengine"
 
 # Python interpreter is used while building RemoteControl plugin
@@ -73,6 +73,7 @@ PATCHES=(
 	"${FILESDIR}/stellarium-0.20.3-unbundle-zlib.patch"
 	"${FILESDIR}/stellarium-0.22.1-fix-star-manager-segfault.patch"
 	"${FILESDIR}/stellarium-0.22.1-unbundle-qtcompress.patch"
+	"${FILESDIR}/stellarium-0.22.1-fix-test-x86.patch"
 )
 
 src_prepare() {
```

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Since it touches `src/core/StelUtils.cpp` I wonder if it does something other than fix tests on x86? I'd say we don't revbump here - I'll do the test runs on stable amd64 & x86, and if both work, we trust it's going to work on other stabilizied arches too. (I can do runtime testing too) 

Would that work?

**Comment by thesamesam** [comment]
If it touches non-tests and makes tests pass, in general, I would revbump unless you have a good reason not to (strong evidence that it _won't_ affect non-tests). I can't think of a time I've had such a case though.

Inconsistent runtime in the same revision is how we end up with very confusing bugs!

**Comment by DarthGandalf** [comment]
I went with revbump because it touches non-tests, so can subtly change runtime behavior, but if you trust that it's fine to change it on already stable arch like that... ok.

**Comment by juippis** [comment]
Let's keep this, we don't really have anything to lose by playing it safe. I'm already doing test runs but...
`>>> Emerging (118 of 119) dev-qt/qtwebengine-5.15.4_p20220505::gentoo`
...

**Comment by juippis** [comment]
@DarthGandalf were you able to pass tests? On ~amd64 I'm not getting
```
FAIL!  : TestConversions::testRadToHMSStr() 'expectedHMS==hms' returned FALSE. (0.08727 radians = 0h20m-0.0s (expected 0h20m00.0s))
   Loc: [/var/tmp/portage/sci-astronomy/stellarium-0.22.1-r1/work/stellarium-0.22.1/src/tests/          testConversions.cpp(938)]
```
```
20/26 Test  #9: testConversions ..................***Failed    0.04 sec
21/26 Test #21: testEphemeris ....................   Passed    0.18 sec
22/26 Test  #5: testStelJsonParser ...............   Passed    0.32 sec
23/26 Test  #4: testStelSphericalIndex ...........   Passed    0.36 sec
24/26 Test  #1: testDates ........................   Passed    1.56 sec
25/26 Test  #3: testStelSphereGeometry ...........   Passed    1.71 sec
26/26 Test  #7: testStelVertexArray ..............   Passed    2.38 sec

96% tests passed, 1 tests failed out of 26

Total Test time (real) =   2.40 sec

The following tests FAILED:
	  9 - testConversions (Failed)
Errors while running CTest
```
(which I believe happened previously on x86)

**Comment by juippis** [comment]
So it works now on stable-x86, but fails on stable-amd64 and unstable-~amd64 :)

**Comment by DarthGandalf** [comment]
Devs fixed that too now. Did the new patch break it for some another arch? :)

**Comment by DarthGandalf** [comment]
For these 2 arches it now works for me.

**Review by juippis — APPROVED** [review]
Yep, works now on ~amd64 and x86. What a pleasure working with a responsive upstream, and ebuild maintainer, thanks!

**Pull request closed without merging**
