### PR TITLE
x11-misc/qt5ct: verbump to 0.27

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by kensington** [comment]
Thanks.

The upstream dbus change is interesting, by the way. I concur with your assessment that dbus is indeed used only via qtgui, but libqt5ct.so ends up with libQt5DBus in NEEDED.

**Comment by Coacher** [comment]
Thank you, @kensington.

**Pull request closed without merging**
