### PR TITLE
sci-mathematics/rstudio: version bump to 1.1.383

### PR DESCRIPTION
**Pull request by waebbl**
Another try for a PR of this file. 
Please see the commit message for related bugs (#633936 and #622254) on gentoo's bugzilla.

I mixed in the changes suggested by a17r in my last try for a PR, streamlined my commit history, but unfortunately the old PR got lost on the way to get the changes back on my remote branch.

### CODE REVIEW

**Comment by a17r** [comment]
Try updating the Manifest without adding the ebuild in the same go, repoman would complain loudly. Same for adding the ebuild without Manifest. So this should only be one self-contained commit.

**Comment by waebbl** [comment]
Thanks for you reply. I was first trying to use `git revert` when I saw the first lines of your messages while I was still at work, but that didn't work well.
After some tries on which commit to squash and which to pick, I managed the create the commit. 
But now I have diverged branches locally and remote and I am worried about pushing the commit, because I think I will need to `git push --force`, resulting again in a destruction of this PR.

I was trying to use `repoman commit` yesterday, but it refused for some reason, I don't remember. I'm quite aware of using `repoman` when working with ebuilds.

**Comment by a17r** [comment]
We do `git push -f` all the time, what makes you think it destroys your PR?

**Comment by waebbl** [comment]
It got destroyed the last time, I think because the commit it belonged to doesn't exist anymore.
I'll go and check out the channel :)

**Comment by waebbl** [comment]
Ok this time, it updated the commit.

**Pull request closed without merging**
