### PR TITLE
media-sound/guitarix: EAPI 8 and py3.11

### PR DESCRIPTION
**Pull request by puleglot**
Also switch to github repo. SourceForge repo is outdated.

Closes: https://bugs.gentoo.org/897030

### CODE REVIEW

**Comment by fordfrog** [comment]
i can't get past this when compiling `guitarix-0.44.1`:
```
Checking for zita-convolver >= 3.0       : Zita-convolver version 3 not found, trying version 4 
Checking for zita-convolver >= 4.0       : yes 
Checking for zita-resampler >= 1.0       : Zita-resampler version 1 not found 
The configuration failed
```

and though `guitarix-9999` does not fail for me, it's because it silently switches to internal code:
```
Use internal zita-resampler                  : yes 
Use internal zita-convolver                  : no 
```

i have `media-libs/zita-resampler-1.10.1:0/1` installed.

**Comment by fordfrog** [comment]
the in-tree version suffers from the same issue too, so it's not related to this pr, so merging it.

**Comment by puleglot** [comment]
> i have `media-libs/zita-resampler-1.10.1:0/1` installed.
It doesn't define ZITA_RESAMPLER_MAJOR_VERSION in the headers, so the check in guitarix fails.
https://github.com/brummer10/guitarix/issues/122

**Comment by fordfrog** [comment]
ah, nice finding. it's now even reported [here](https://bugs.gentoo.org/900609)

**Pull request closed without merging**
