### PR TITLE
net-vpn:protonvpn-cli: vbump

### PR DESCRIPTION
**Pull request by ILMostro**
* bump to version 2.2.2
* See [Changelog](https://github.com/ProtonVPN/protonvpn-cli-ng/blob/master/CHANGELOG.md) for details

### CODE REVIEW

**Comment by juippis** [comment]
The ebuild looks good, but commit summary and message box are a bit lacking. 
Check https://www.gentoo.org/glep/glep-0066.html#commit-messages for our git commit summary syntax, or some previous commits to ::gentoo repo. 

Then check https://www.gentoo.org/glep/glep-0076.html about a required sign-off that is also missing.

**Comment by ILMostro** [comment]
I thought I had configured git to sign the commits.  Thanks for pointing that out.  Resolved issue with `git config --local commit.gpgSign true`.

The commit message had a typo for the name of the package.  I also shortened it to a single subject line to indicate a simple version bump.

**Comment by juippis** [comment]
Actually no, your sign-off isn't good enough for us. 
https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Comment by ILMostro** [comment]
> Actually no, your sign-off isn't good enough for us.
> https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

Good catch.  Thank you for that.  I'm working on figuring out why the sign-off is not working as intended via `DCO_SIGNED_OFF_BY` env var.  I suspect that `repoman` adheres to this always and I used `git` instead of repoman for the commit.

**Pull request closed without merging**
