### PR TITLE
app-text/cherrytree: Bug: https://bugs.gentoo.org/888717

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. 

You may want to consider to remove the old ebuild in the commit. Then the changes would become easily visible. It is not always sensible to remove the old ebuild, but it appears to be a situation where it is sensible.

**Review by juippis — COMMENTED** [review]
Hmm, even with this change I'm getting:
```
--   Package 'vte-2.91', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPkgConfig.cmake:607 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPkgConfig.cmake:829 (_pkg_check_modules_internal)
  CMakeLists.txt:160 (pkg_check_modules)
```
but this vte is installed:
`[binary   R    ] gui-libs/vte-0.70.2-1:2.91-gtk4::gentoo  USE="crypt icu introspection vala -debug -gtk-doc -systemd -vanilla" 0 KiB`

Anny ideas?

**Comment by flint2** [comment]
> 

reverted to x11-libs/vte
https://github.com/gentoo/gentoo/commit/77c9553210b48fb2f15457de394e0aa53366e6df

Now should work
Thanks!

**Comment by thesamesam** [comment]
Could you fix the summary/title/first line of the commit message to describe what changes? Thanks.

**Comment by juippis** [comment]
(btw sorry your fix resolves the issue I originally had, but gives another compilation failure I've been trying to solve (a dependency issue but dep of THAT dep fails to compile...))

**Comment by flint2** [comment]
> Could you fix the summary/title/first line of the commit message to describe what changes? Thanks.

Added in https://github.com/gentoo/gentoo/commit/8a0e312109753113d472586e48b0966961f235f9

**Comment by flint2** [comment]
Deprecated by https://github.com/gentoo/gentoo/pull/30060

**Pull request closed without merging**
