### PR TITLE
media-video/mpv: fix build without any video outputs in 9999

### PR DESCRIPTION
**Pull request by Coacher**
Tidy comments. Minor cleanups.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by idella** [comment]
```ebuild
 -		pax-mark -m "${ED}usr/bin/${PN}"
+		pax-mark -m "${ED}"usr/bin/${PN}
```

This appears to be right the first time and the change to be wrong

**Comment by Coacher** [comment]
@idella, no it's not wrong. The quotes are now around the part that really needs it, i.e. the ED variable that can have spaces. The rest cannot have spaces and doesn't need quoting. It's also a common practice to omit quotes around variables like PN, P, PV, which are guaranteed to not have spaces as per PMS.

**Comment by monsieurp** [comment]
:+1:

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by Coacher** [comment]
Thank you, @monsieurp.

**Pull request closed without merging**
