### PR TITLE
x11-misc/obconf-qt: version bump to 0.11.0

### PR DESCRIPTION
**Pull request by Wesmania**
Also adds a USE flag whether to use translations from lxqt-l10n or pull
them in as part of the package.

Bug: https://bugs.gentoo.org/601884
Package-Manager: Portage-2.3.19, Repoman-2.3.6

### CODE REVIEW

**Comment by Wesmania** [comment]
@kensington @jlec I used the github address for the source package at obconf-qt-0.11.0.ebuild:14, I assume the address in the 0.9 ebuild is your own mirror. Let me know if it should be changed.

**Comment by Dessa** [comment]
im not sure that adding that intermediate version is helpful. @dracwyrm ? relates to #7026

**Comment by kensington** [comment]
> @kensington @jlec I used the github address for the source package at obconf-qt-0.11.0.ebuild:14, I assume the address in the 0.9 ebuild is your own mirror. Let me know if it should be changed.

It looks like 0.9 had a Gentoo SRC_URI as it was a custom snapshot rather than an upstream release.

**Comment by flappyports** [comment]
no activity

**Pull request closed without merging**
