### PR TITLE
dev-python/pybluez: python3_{9..10} support

### PR DESCRIPTION
**Pull request by dAgbeve**

### CODE REVIEW

**Comment by dAgbeve** [comment]
@mgorny  Would you kindly check this?

**Comment by mgorny** [comment]
Is grc commit intentionally here or a mistake? How did you test it?

**Comment by dAgbeve** [comment]
grc is a mistake here which has been corrected to this pull request #20701. There are no test script so i just run it on my system.

**Comment by thesamesam** [comment]
I think you forgot to drop the grc commit from this PR. Anyway, done! Thanks.

**Pull request closed without merging**
