### PR TITLE
app-emulation/docker-compose: version bump to 1.4.2

### PR DESCRIPTION
**Pull request by hasufell**
@alunduil 

diff:
```diff
--- /usr/portage/app-emulation/docker-compose/docker-compose-1.4.0.ebuild
+++ /usr/portage/app-emulation/docker-compose/docker-compose-1.4.2.ebuild
@@ -27,6 +27,7 @@
 	>=dev-python/pyyaml-3.10[${PYTHON_USEDEP}]
 	<dev-python/pyyaml-4[${PYTHON_USEDEP}]
 	>=dev-python/requests-2.6.1[${PYTHON_USEDEP}]
+	<dev-python/requests-2.7[${PYTHON_USEDEP}]
 	>=dev-python/six-1.3.0[${PYTHON_USEDEP}]
 	<dev-python/six-2[${PYTHON_USEDEP}]
 	>=dev-python/texttable-0.8.1[${PYTHON_USEDEP}]
@@ -37,6 +38,7 @@
 DEPEND="
 	test? (
 		${CDEPEND}
+		dev-python/flake8[${PYTHON_USEDEP}]
 		>=dev-python/mock-1.0.1[${PYTHON_USEDEP}]
 		dev-python/nose[${PYTHON_USEDEP}]
 	)
```

### CODE REVIEW

**Comment by hasufell** [comment]
upstream setup.py snippet:
```py
install_requires = [
    'docopt >= 0.6.1, < 0.7',
    'PyYAML >= 3.10, < 4',
    'requests >= 2.6.1, < 2.7',
    'texttable >= 0.8.1, < 0.9',
    'websocket-client >= 0.32.0, < 1.0',
    'docker-py >= 1.3.1, < 1.4',
    'dockerpty >= 0.3.4, < 0.4',
    'six >= 1.3.0, < 2',
]


tests_require = [
    'mock >= 1.0.1',
    'nose',
    'pyinstaller',
    'flake8',
]
```

**Comment by alunduil** [comment]
@hasufell I have that version in my overlay's history.  It's not passed my automated testing so I've not committed it (haven't had time to fix it).  

flake8 is a linter and not run by portage.  Therefore, that dependency isn't required.  

The requests version, I've been uncapping due to request versions and pressure from python updates in the past.

See this ref for my version of this ebuild:

https://github.com/alunduil/alunduil-overlay/blob/f12a7dc0fe02606213957fbae6d6362f0cdf9306/app-emulation/docker-compose/docker-compose-1.4.2.ebuild

**Comment by hasufell** [comment]
> It's not passed my automated testing so I've not committed it (haven't had time to fix it).

what testing do you mean? runtime tests? The test suite alone seems to pass

**Comment by hasufell** [comment]
But anyway, I actually stopped actively using docker-compose a while ago, because it's too limited and doesn't give too much gain over plain shell scripts. So I ended up doing the same stuff via openrc init scripts. Works relatively well so far.

**Comment by alunduil** [comment]
I've got a utility (that needs some improvements) that runs the emerge in a clean container.  Due to the dependence resolution of `--autounmask-write` (open bug on Gentoo bugzilla) I've been having issues with some packages running in this fashion.

**Comment by alunduil** [comment]
@hasufell what were you using it for?  In my opinion, compose is only good for development environments and integration tests.

**Comment by hasufell** [comment]
> what were you using it for?

Web deployment, like pydio, xwiki, confluence and so on. But doing things very modular (e.g. php container connected with nginx container, connected with mysql container, connected...) turns out to be a bad idea to some extent since docker doesn't really have the abstraction you would need to handle that complexity. And docker-compose cannot really deliver that job either.

**Comment by mgorny** [comment]
Any plans for htis?

**Comment by alunduil** [comment]
Yep, checking the latest version today.  Watch my overlay for progress.

**Comment by alunduil** [comment]
With 1.5.x in the tree now does this still need to exist?

**Comment by monsieurp** [comment]
@alunduil no, if a more up-to-date version is already in the tree, it means this PR is obsolete.

**Pull request closed without merging**
