### PR TITLE
media-sound/clementine: version 1.4.0_rc2

### PR DESCRIPTION
**Pull request by DarthGandalf**
Closes: https://bugs.gentoo.org/865939
Bug: https://bugs.gentoo.org/829307

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Alexey Sokolov <alexey+gentoo@asokolov.org>

### CODE REVIEW

**Comment by ajakk** [comment]
How does this address the security bug?

**Comment by DarthGandalf** [comment]
Pretty indirectly.

The security bug affects only the windows build because it uses an old dependency in the installer. It probably can be closed already, but with the new release we can be 100% sure the old dependency is not there anymore

**Comment by ajakk** [comment]
Well, if we were really never affected then we can just close the security bug as invalid. In any case, you were one of the people in the upstream issue so thank you for your work on it!

**Review by juippis — APPROVED** [review]
Had some trouble compiling -9999, 
```
pc-linux-gnu/12.2.0/../../../../lib64/libQt5Network.so: undefined reference to symbol 'deflateInit_'
/usr/lib/gcc/x86_64-pc-linux-gnu/12.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /lib64/libz.so.1:    error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
 * ERROR: media-sound/clementine-9999::gentoo failed (compile phase):
```
(it's tied to some USE flag)
And no troubles with the release. Thanks!

**Pull request closed without merging**
