### PR TITLE
profiles: mark musl profiles w/o rust bins as wd40

### PR DESCRIPTION
**Pull request by matoro**
This marks several additional profiles that do not have rust bootstrap binaries as wd40:

* arm musl
* m68k musl
* mips musl
* ppc musl
* ppc64 musl
* ppc64le musl
* x86 musl
* all riscv rv32
* all x86 i486

This necessitated a bunch of additional masks, and a couple untested keywords on `gnome-base/librsvg`.  Newer versions were missing s390 keywords despite rust being available on that arch, and the older version was missing ppc64 keywords.

Since the pre-rust version has known security vulnerabilities, to minimize the impact of adding additional keywords (and to prevent users on rust-available profiles from accidentally installing the old version), I have added a base mask for the older version, and then unmasked it in wd40.

Closes: https://bugs.gentoo.org/936643

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by stefson** [comment]
hi, can I still use my custom rustc on armv7-musl when this has been merged?

**Comment by matoro** [comment]
> hi, can I still use my custom rustc on armv7-musl when this has been merged?

It won't prevent you from running the binary of course, but you will have to manually unmask the packages/flags that you want via `/etc/portage/profile`.

**Comment by arthurzam** [comment]
> hi, can I still use my custom rustc on armv7-musl when this has been merged?

@stefson Hi, as the rust bootstrapper for Gentoo, could you say for which target do you want? Can you give your full toolchain name (I'll use crossdev for that)

> This marks several additional profiles that do not have rust bootstrap binaries as wd40:

@matoro For rust 1.80.1, I'll add ppc64{ul,le} rust for musl. Let's merge as is, but we will soon be able to drop wd40 for ppc64{,le}-musl 😄

**Comment by stefson** [comment]
had a chance to test my local portage tree with this patch today, the profile change to wd40 just leads to unmasking all rust relevant packages on my side, and thats all there is to do. 

@arthurzam I'll write you a message to your dev email this week, its complicated.

**Pull request closed without merging**
