### PR TITLE
media-sound/audacious: version bump to 3.7.1

### PR DESCRIPTION
**Pull request by RobinDX**

### CODE REVIEW

**Comment by monsieurp** [comment]
Hello @RobinDX and thank you very much for your PR. Please rebase/amend your commits so that they all respect the following format: "cat/pkgname: commit message" (like I did when editing the PR title). Cheers.

**Comment by monsieurp** [comment]
@gentoochainsaw

**Comment by gentoochainsaw** [comment]
Team github, this is okay to commit. RobinDX, thank you :)

**Comment by monsieurp** [comment]
Alright @gentoochainsaw, thanks for signing off on the PR. We still need the commit messages to be edited and I'll take care of merging it back into Portage.

**Comment by RobinDX** [comment]
@monsieurp 
So what should I do now？

**Comment by monsieurp** [comment]
You have to edit your commit messages. We won't merge the PR until you've done so. Thank you.

**Pull request closed without merging**
