### PR TITLE
sys-apps/accountsservice: Adds musl build fixes Closes: https://bugs.…

### PR DESCRIPTION
**Pull request by mipseb**
…gentoo.org/762442

https://gitlab.alpinelinux.org/alpine/aports/-/raw/75528d8dc4206a74501799f6a6042be20b80801d/community/accountsservice/musl-fgetspent_r.patch https://gitlab.alpinelinux.org/alpine/aports/-/raw/75528d8dc4206a74501799f6a6042be20b80801d/community/accountsservice/musl-wtmp.patch

### CODE REVIEW

**Comment by Kangie** [comment]
Thanks for your contribution @mipseb - few things to fix up.

As discussed on discord:

- GCO signoff format
- group `Closes` and amend title

Once you've done that and pushed the changes, edit the title of the PR and add `[please reassign] to the end to trigger a new bot scan.

**Comment by Kangie** [comment]
LGTM. For posterity: you said that this PR passes tests on amd64 and ppc32 musl?

**Comment by Kangie** [comment]
I've discussed the need to drop the fastfetch commit with @mipseb

**Comment by mipseb** [comment]
> LGTM. For posterity: you said that this PR passes tests on amd64 and ppc32 musl?

Yes I had performed ebuild tests for sys-apps/accountsservice on an LLVM Musl and an Glibc  Libc box.

**Pull request closed without merging**
