### PR TITLE
app-arch/torrentzip: add 1.3

### PR DESCRIPTION
**Pull request by miller-alex**
This release contains a few bug fixes and introduces a test suite.
Tests not enabled because of unpackaged dependency <https://nih.at/nihtest/>.
--
I'm looking into packaging nihtest and setting up test phase. Since that warrants a proper review, you may still want to fix the serious regression in 1.2 first (PR #35634)—or, alternatively, commit 1.3 in its current form without tests.

### CODE REVIEW

**Comment by miller-alex** [comment]
Tests added do nihtest. Since tests can be built as a standalone cmake project, I'm doing that and not using cmake for anything else, though the dependency is unconditional due to the eclass. Somebody should have a closer look at this ebuild since I'm not very familiar with python packaging and the cmake test suite might be a bit unusual.

Also note that the ebuild lists several mirrors of the distfile, these could be removed if you think that's overkill.

**Comment by miller-alex** [comment]
The masked test case in nihtest has been fixed upstream, but I'm not going to backport the fix.

Since torrentzip-1.2 turned out to be broken, it would be nice to get a fixed version into the tree quickly. There's still the straightforward PR for 1.2-r1 in case reviewing this one needs more time.

**Comment by mgorny** [comment]
Ok, this looks wrong. You are installing `nihtest` for a specific Python implementation, selected via `PYTHON_SINGLE_TARGET` but then are running it using an arbitrary, possibly different Python implementation via `python-any-r1`.

If you need to run it like that, then I suppose you ought to include a proper any-dep on it, and `python_check_deps()` to select a matching interpreter.

**Comment by miller-alex** [comment]
No, `nihtest` is just run as `nihtest` and should use the Python implementation it was installed for.
The dependency on Python via `python-an-r1` is for a different Python script, `remove-timestamps`, which is used by the tests.

**Review by mgorny — APPROVED** [review]
Thanks!

**Pull request closed without merging**
