### PR TITLE
net-libs/nodejs: OpenSSL 1.1.1 support

### PR DESCRIPTION
**Pull request by candrews**
Closes: https://bugs.gentoo.org/670574
Package-Manager: Portage-2.3.52, Repoman-2.3.12
Signed-off-by: Craig Andrews <candrews@gentoo.org>

### CODE REVIEW

**Comment by gcs-github** [comment]
I just uploaded new patches on https://bugs.gentoo.org/670574 to reflect the latest upstream efforts.

**Comment by candrews** [comment]
> I just uploaded new patches on https://bugs.gentoo.org/670574 to reflect the latest upstream efforts.

I just updated this PR to include those, thanks!

**Comment by okias** [comment]
rebase needed, anyway, applied and I'm going to test it right now..

**Comment by okias** [comment]
and also for nodejs-11.7.0 there is one block from src/node_crypto.cc already incorporated into code.

**Comment by Whissi** [comment]
Thank you for the patches. Although maintainer ignored bug/PR, patches were helpful.
Now that NodeJS upstream is compatible with OpenSSL 1.1.1, this PR is no longer needed.

**Pull request closed without merging**
