### PR TITLE
dev-php/pecl-memcached: Enable PHP 8.3 support

### PR DESCRIPTION
**Pull request by anthonyryan1**
Building properly, and working well in personal use on PHP 8.3.

### CODE REVIEW

**Review by matoro — CHANGES_REQUESTED** [review]
Please update the `USE=igbinary` dep string, test and add compat there.  It can't find it when `USE=igbinary` is enabled (which is required by `USE=test`).

```
checking for session includes... /usr/lib64/php8.2/include/php
checking for igbinary includes... /usr/lib64/php8.2/include/php

...

checking for session includes... /usr/lib64/php8.3/include/php
checking for igbinary includes... configure: error: Cannot find igbinary.h
```

**Comment by anthonyryan1** [comment]
Fixed and updated the USE_PHP is used to set the required use flags for igbinary, rather than duplicating it later in the config.

Will avoid future errors of this type.

**Comment by anthonyryan1** [comment]
I'm also going to note that this pattern would also benefit `dev-php/pecl-redis`  & `dev-php/pecl-http` for ensuring there's only one line change needed to change the PHP version numbers.

**Comment by anthonyryan1** [comment]
Amended commit to close https://bugs.gentoo.org/931962 which was created after this pull request.

**Comment by matoro** [comment]
Thanks, this lets it compile but it skips the entire test suite.  See [bug 922139](https://bugs.gentoo.org/922139).  Any idea if you could fix this?  Otherwise I can't reliably test.

**Comment by matoro** [comment]
I see this warning:
```
Warning: PHP Startup: Unable to load dynamic library 'memcached.so' (tried: /var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.3/modules/memcached.so (/var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.3/modules/memcached.so: undefined symbol: igbinary_serialize), /var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.3/modules/memcached.so.so (/var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.3/modules/memcached.so
.so: cannot open shared object file: No such file or directory)) in Unknown on line 0
```

**Comment by matoro** [comment]
This seems to have worked correctly for php8.2, but not for php8.3.  E.x. here's what I get when running this with `PHP_TARGETS="php8-2 php8-3"`:

```
>>> Test phase: dev-php/pecl-memcached-3.2.0_p20231008
PHP Warning:  Module "igbinary" is already loaded in Unknown on line 0
PHP Warning:  Module "memcached" is already loaded in Unknown on line 0

=====================================================================
PHP         : /usr/lib64/php8.2/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 8.2.20
ZEND_VERSION: 4.2.20
PHP_OS      : Linux - Linux localhost 6.9.8-gentoo-ppc64le #1 SMP Mon Jul  8 11:41:51 EDT 2024 ppc64le
INI actual  : /etc/php/cli-php8.2/php.ini
More .INIs  : /etc/php/cli-php8.2/ext-active/igbinary.ini,/etc/php/cli-php8.2/ext-active/memcached.ini,/etc/php/cli-php8.2/ext-active/opcache.ini  
CWD         : /var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.2
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2024-07-12 21:49:23
=====================================================================
PASS Check for memcached presence [tests/001.phpt] 
PASS Memcached::add() [tests/add.phpt] 
PASS Memcached::addByKey() [tests/add_bykey.phpt] 
PASS Memcached::addServer() unix doamin socket [tests/addserver_unixdomain.phpt] 
PASS Memcached::append() [tests/append.phpt] 
PASS Memcached::appendByKey() [tests/append_bykey.phpt] 
SKIP Memcached construct with bad arguments [tests/bad_construct.phpt] reason: PHP 7 only
PASS Memcached construct with bad arguments [tests/bad_construct_8.phpt] 
PASS Memcached: Bug #16084 (Crash when addServers is called with an associative array) [tests/bug_16084.phpt] 
PASS Memcached: Bug #16959 (getMulti + BINARY_PROTOCOL problem) [tests/bug_16959.phpt] 
PASS Change prefix, pecl bug #17137 [tests/bug_17137.phpt] 
PASS Memcached::getServerByKey(): Bug pecl#18639 (Segfault in getServerByKey) [tests/bug_18639.phpt] 
PASS Memcached::get() with cache callback [tests/cachecallback.phpt] 
PASS make sure that callback exception behaves correctly [tests/callback_exception.phpt] 
PASS Callback initializer throws and dies [tests/callback_exception_2.phpt] 
PASS Memcached fetch cas & set cas [tests/cas.phpt] 
PASS Memcached::casByKey() [tests/cas_bykey.phpt] 
PASS set data exceeding size limit [tests/cas_e2big.phpt] 
PASS Memcached::cas() with strange key [tests/cas_invalid_key.phpt] 
PASS Memcached multi fetch cas & set cas [tests/cas_multi.phpt] 
PASS Check if persistent object is persistent [tests/check_if_persistent.phpt] 
PASS Check if persistent object is new or an old persistent one [tests/check_if_pristine.phpt] 
PASS Memcached::checkKey() [tests/check_key.phpt] 
PASS Test cloning [tests/clone.phpt] 
PASS Memcached compression test [tests/compression_conditions.phpt] 
PASS Memcached compression test [tests/compression_types.phpt] 
PASS Conf settings persist. [tests/conf_persist.phpt] 
PASS Memcached constructor [tests/construct.phpt] 
PASS persistent memcached connection [tests/construct_persistent.phpt] 
PASS Default behaviors [tests/default_behavior.phpt] 
PASS Memcached::deleteByKey() [tests/delete_bykey.phpt] 
PASS Memcached store & fetch type correctness [tests/deleted.phpt] 
PASS Delete multi [tests/deletemulti.phpt] 
PASS Delete multi with integer keys [tests/deletemulti_nonstringkeys.phpt] 
PASS Delete multi key types [tests/deletemultitypes.phpt] 
PASS Memcached store, fetch & touch expired key [tests/expire.phpt] 
PASS Memcached getDelayed() and fetch() with and without cas [tests/fetch.phpt] 
PASS Memcached::fetch() with bad unserialize [tests/fetch_badunserialize.phpt] 
PASS Memcached::fetch() with bad unserialize [tests/fetchall_badunserialize.phpt] 
PASS Test flushing buffers [tests/flush_buffers.phpt] 
PASS Memcached::get() [tests/get.phpt] 
PASS Memcached::getByKey() [tests/get_bykey.phpt] 
PASS Memcached::getByKey() with CAS [tests/get_bykey_cas.phpt] 
PASS Memcached::get/getMulti() flags [tests/get_flags.phpt] 
PASS Memcached getDelayed callback [tests/getdelayed.phpt] 
PASS Memcached::getDelayedByKey() with bad server [tests/getdelayed_badserver.phpt] 
PASS Memcached::getDelayed() with bad unserialize [tests/getdelayed_badunserialize.phpt] 
PASS Memcached::getDelayedByKey() [tests/getdelayed_bykey.phpt] 
PASS Memcached::getDelayedByKey() with CAS [tests/getdelayed_bykey_cas.phpt] 
PASS Memcached getDelayed non string keys [tests/getdelayed_nonstring_keys.phpt] 
PASS Memcached::getMulti() [tests/getmulti.phpt] 
PASS Memcached::getMulti() bad server [tests/getmulti_badserver.phpt] 
PASS Memcached::getMulti() with bad unserialize [tests/getmulti_badunserialize.phpt] 
PASS Memcached::getMultiByKey() [tests/getmulti_bykey.phpt] 
PASS Memcached::getMulti() with empty array [tests/getmulti_empty.phpt] 
PASS Memcached::getMulti() partial error [tests/getmulti_partial_error.phpt] 
PASS Memcached::getServerByKey() [tests/getserverbykey.phpt] 
PASS getServerList [tests/getserverlist.phpt] 
PASS Memcached::getVersion() [tests/getversion.phpt] 
PASS Test for bug 155 [tests/gh_155.phpt] 
PASS Test for Github issue 21 [tests/gh_21.phpt] 
PASS Test for Github issue 500 [tests/gh_500.phpt] 
PASS Test for Github issue #77 [tests/gh_77.phpt] 
PASS Test for GH #90 [tests/gh_90.phpt] 
PASS Test for Github issue #93 (double and long overflow) [tests/gh_93.phpt] 
PASS Memcached::increment() Memcached::decrement() [tests/incrdecr.phpt] 
PASS 64-bit Memcached::increment() decrement() incrementByKey() decrementByKey() [tests/incrdecr_64.phpt] 
PASS Memcached::incrementByKey() Memcached::decrementByKey() [tests/incrdecr_bykey.phpt] 
PASS Memcached::increment() Memcached::decrement() with initial support [tests/incrdecr_initial.phpt] 
PASS Memcached::increment() Memcached::decrement() with invalid key [tests/incrdecr_invalid_key.phpt] 
PASS Get version [tests/invalid_options.phpt] 
PASS Test that callback is invoked on new object [tests/invoke_callback.phpt] 
PASS Use callback initializer [tests/invoke_callback_2.phpt] 
PASS Test that callback is invoked on new object only once [tests/invoke_callback_twice.phpt] 
PASS Test valid and invalid keys - ascii [tests/keys_ascii.phpt] 
PASS Test valid and invalid keys - binary [tests/keys_binary.phpt] 
SKIP Float should not consider locale [tests/locale_float.phpt] reason: no suitable locale
PASS Memcached local server test [tests/localserver.phpt] 
SKIP MemcachedServer [tests/memcachedserver.phpt] reason: memcached not built with libmemcachedprotocol support
SKIP MemcachedServer [tests/memcachedserver6.phpt] reason: memcached not built with libmemcachedprotocol support
PASS Memcached::phpinfo() [tests/moduleinfo.phpt] 
PASS Memcached GET_PRESERVE_ORDER flag in getMulti [tests/multi_order.phpt] 
PASS Test that correct return value is returned [tests/no-not-found.phpt] 
PASS Memcached options [tests/options.phpt] 
PASS Wrong return values for binary protocol [tests/pr_75.phpt] 
PASS Memcached::prepend() [tests/prepend.phpt] 
PASS Memcached::appendByKey() [tests/prepend_bykey.phpt] 
PASS Memcached::replace() [tests/replace.phpt] 
PASS Memcached::replaceByKey() [tests/replace_bykey.phpt] 
PASS Memcached result codes. [tests/rescode.phpt] 
PASS Cannot reset OPT_PREFIX_KEY #293 [tests/reset_keyprefix.phpt] 
SKIP Test SASL authentication [tests/sasl_basic.phpt] reason: no SASL support enabled
PASS Session bad configurations, prefix [tests/session_badconf_emptyprefix.phpt] 
SKIP Session bad configurations, lock wait time [tests/session_badconf_locktime.phpt] reason: skip until timeout in memcached set
PASS Session bad configurations, persistent [tests/session_badconf_persistent.phpt] 
PASS Session bad configurations, prefix [tests/session_badconf_prefix.phpt] 
PASS Session bad configurations, invalid save path (server list) [tests/session_badconf_servers-php72.phpt] 
SKIP Session bad configurations, invalid save path (server list) [tests/session_badconf_servers.phpt] 
PASS Session basic open, write, destroy [tests/session_basic.phpt] 
PASS Session basic open, write, destroy [tests/session_basic2.phpt] 
PASS Session basic open, write, destroy [tests/session_basic3.phpt] 
SKIP Session lazy binary warning old libmemcached [tests/session_lazy_warning.phpt] reason: too recent libmemcached
PASS Session lock [tests/session_lock-php71.phpt] 
SKIP Session lock [tests/session_lock.phpt] 
PASS Session persistent [tests/session_persistent.phpt] 
PASS Session regenerate [tests/session_regenerate.phpt] 
PASS Memcached::setByKey() [tests/set_bykey.phpt] 
PASS Compress below factor and fail to plain. [tests/set_comp_below_factor.phpt] 
PASS Set default serializer [tests/set_default_serializer.phpt] 
PASS Test libmemcached encryption [tests/set_encoding_key.phpt] 
SKIP Test libmemcached encryption [tests/set_encoding_key2.phpt] reason: test for libmemcached lower than 1.0.18
PASS Set invalid serializer [tests/set_invalid_serializer.phpt] 
PASS set large data [tests/set_large.phpt] 
PASS set data exceeding size limit [tests/set_large_e2big.phpt] 
PASS Compress with 0 factor and get [tests/setget_zero_factor.phpt] 
PASS Memcached::setMulti() [tests/setmulti.phpt] 
PASS Memcached::setMultiByKey() [tests/setmulti_bykey.phpt] 
PASS Set options using setOptions [tests/setoptions.phpt] 
PASS Check stats [tests/stats.phpt] 
PASS Check stats does not hang on non-blocking binary protocol [tests/stats_hang.phpt] 
PASS Touch in binary mode [tests/touch_binary.phpt] 
PASS Memcached store & fetch type and value correctness using igbinary serializer [tests/types_igbinary.phpt] 
PASS Memcached multi store & multi fetch type and value correctness using igbinary serializer [tests/types_igbinary_multi.phpt] 
SKIP Memcached store & fetch type and value correctness using JSON serializer [tests/types_json.phpt] reason: json not enabled
SKIP Memcached multi store & multi fetch type and value correctness using JSON serializer [tests/types_json_multi.phpt] reason: json not enabled
SKIP Memcached store & fetch type and value correctness using msgpack serializer [tests/types_msgpack.phpt] reason: msgpack not enabled
SKIP Memcached multi store & fetch type and value correctness using msgpack serializer [tests/types_msgpack_multi.phpt] reason: msgpack not enabled
PASS Memcached store & fetch type and value correctness using PHP serializer [tests/types_php.phpt] 
PASS Memcached multi store & fetch type and value correctness using PHP serializer [tests/types_php_multi.phpt] 
PASS Set with undefined key and value [tests/undefined_set.phpt] 
PASS Memcached user flags [tests/user-flags.phpt] 
PASS Memcached virtual buckets [tests/vbucket.phpt] 
SKIP Memcached virtual buckets [tests/vbucket_error_7.phpt] reason: PHP 7 only
PASS Memcached virtual buckets [tests/vbucket_error_8.phpt] 
PASS Get version [tests/version.phpt] 
=====================================================================
TIME END 2024-07-12 21:49:39

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :    0
Exts tested     :   31
---------------------------------------------------------------------

Number of tests :  135               120
Tests skipped   :   15 ( 11.1%) --------
Tests warned    :    0 (  0.0%) (  0.0%)
Tests failed    :    0 (  0.0%) (  0.0%)
Tests passed    :  120 ( 88.9%) (100.0%)
---------------------------------------------------------------------
Time taken      :   16 seconds
=====================================================================
PHP Warning:  Module "igbinary" is already loaded in Unknown on line 0

=====================================================================
PHP         : /usr/lib64/php8.3/bin/php 
PHP_SAPI    : cli
PHP_VERSION : 8.3.9
ZEND_VERSION: 4.3.9
PHP_OS      : Linux - Linux localhost 6.9.8-gentoo-ppc64le #1 SMP Mon Jul  8 11:41:51 EDT 2024 ppc64le
INI actual  : /etc/php/cli-php8.3/php.ini
More .INIs  : /etc/php/cli-php8.3/ext-active/igbinary.ini,/etc/php/cli-php8.3/ext-active/opcache.ini  
CWD         : /var/tmp/portage/dev-php/pecl-memcached-3.2.0_p20231008/work/php8.3
Extra dirs  : 
VALGRIND    : Not used
=====================================================================
TIME START 2024-07-12 21:49:40
=====================================================================
SKIP Check for memcached presence [tests/001.phpt] reason: memcached is not loaded
SKIP Memcached::add() [tests/add.phpt] reason: memcached is not loaded
SKIP Memcached::addByKey() [tests/add_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::addServer() unix doamin socket [tests/addserver_unixdomain.phpt] reason: memcached is not loaded
SKIP Memcached::append() [tests/append.phpt] reason: memcached is not loaded
SKIP Memcached::appendByKey() [tests/append_bykey.phpt] reason: memcached is not loaded
SKIP Memcached construct with bad arguments [tests/bad_construct.phpt] reason: memcached is not loaded
SKIP Memcached construct with bad arguments [tests/bad_construct_8.phpt] reason: memcached is not loaded
SKIP Memcached: Bug #16084 (Crash when addServers is called with an associative array) [tests/bug_16084.phpt] reason: memcached is not loaded
SKIP Memcached: Bug #16959 (getMulti + BINARY_PROTOCOL problem) [tests/bug_16959.phpt] reason: memcached is not loaded
SKIP Change prefix, pecl bug #17137 [tests/bug_17137.phpt] reason: memcached is not loaded
SKIP Memcached::getServerByKey(): Bug pecl#18639 (Segfault in getServerByKey) [tests/bug_18639.phpt] reason: memcached is not loaded
SKIP Memcached::get() with cache callback [tests/cachecallback.phpt] reason: memcached is not loaded
SKIP make sure that callback exception behaves correctly [tests/callback_exception.phpt] reason: memcached is not loaded
SKIP Callback initializer throws and dies [tests/callback_exception_2.phpt] reason: memcached is not loaded
SKIP Memcached fetch cas & set cas [tests/cas.phpt] reason: memcached is not loaded
SKIP Memcached::casByKey() [tests/cas_bykey.phpt] reason: memcached is not loaded
SKIP set data exceeding size limit [tests/cas_e2big.phpt] reason: memcached is not loaded
SKIP Memcached::cas() with strange key [tests/cas_invalid_key.phpt] reason: memcached is not loaded
SKIP Memcached multi fetch cas & set cas [tests/cas_multi.phpt] reason: memcached is not loaded
SKIP Check if persistent object is persistent [tests/check_if_persistent.phpt] reason: memcached is not loaded
SKIP Check if persistent object is new or an old persistent one [tests/check_if_pristine.phpt] reason: memcached is not loaded
SKIP Memcached::checkKey() [tests/check_key.phpt] reason: memcached is not loaded
SKIP Test cloning [tests/clone.phpt] reason: memcached is not loaded
SKIP Memcached compression test [tests/compression_conditions.phpt] 
SKIP Memcached compression test [tests/compression_types.phpt] reason: memcached is not loaded
SKIP Conf settings persist. [tests/conf_persist.phpt] reason: memcached is not loaded
SKIP Memcached constructor [tests/construct.phpt] reason: memcached is not loaded
SKIP persistent memcached connection [tests/construct_persistent.phpt] reason: memcached is not loaded
SKIP Default behaviors [tests/default_behavior.phpt] reason: memcached is not loaded
SKIP Memcached::deleteByKey() [tests/delete_bykey.phpt] reason: memcached is not loaded
SKIP Memcached store & fetch type correctness [tests/deleted.phpt] reason: memcached is not loaded
SKIP Delete multi [tests/deletemulti.phpt] reason: memcached is not loaded
SKIP Delete multi with integer keys [tests/deletemulti_nonstringkeys.phpt] reason: memcached is not loaded
SKIP Delete multi key types [tests/deletemultitypes.phpt] reason: memcached is not loaded
SKIP Memcached store, fetch & touch expired key [tests/expire.phpt] reason: memcached is not loaded
SKIP Memcached getDelayed() and fetch() with and without cas [tests/fetch.phpt] reason: memcached is not loaded
SKIP Memcached::fetch() with bad unserialize [tests/fetch_badunserialize.phpt] reason: memcached is not loaded
SKIP Memcached::fetch() with bad unserialize [tests/fetchall_badunserialize.phpt] reason: memcached is not loaded
SKIP Test flushing buffers [tests/flush_buffers.phpt] reason: memcached is not loaded
SKIP Memcached::get() [tests/get.phpt] reason: memcached is not loaded
SKIP Memcached::getByKey() [tests/get_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::getByKey() with CAS [tests/get_bykey_cas.phpt] reason: memcached is not loaded
SKIP Memcached::get/getMulti() flags [tests/get_flags.phpt] reason: memcached is not loaded
SKIP Memcached getDelayed callback [tests/getdelayed.phpt] reason: memcached is not loaded
SKIP Memcached::getDelayedByKey() with bad server [tests/getdelayed_badserver.phpt] reason: memcached is not loaded
SKIP Memcached::getDelayed() with bad unserialize [tests/getdelayed_badunserialize.phpt] reason: memcached is not loaded
SKIP Memcached::getDelayedByKey() [tests/getdelayed_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::getDelayedByKey() with CAS [tests/getdelayed_bykey_cas.phpt] reason: memcached is not loaded
SKIP Memcached getDelayed non string keys [tests/getdelayed_nonstring_keys.phpt] reason: memcached is not loaded
SKIP Memcached::getMulti() [tests/getmulti.phpt] reason: memcached is not loaded
SKIP Memcached::getMulti() bad server [tests/getmulti_badserver.phpt] reason: memcached is not loaded
SKIP Memcached::getMulti() with bad unserialize [tests/getmulti_badunserialize.phpt] reason: memcached is not loaded
SKIP Memcached::getMultiByKey() [tests/getmulti_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::getMulti() with empty array [tests/getmulti_empty.phpt] reason: memcached is not loaded
SKIP Memcached::getMulti() partial error [tests/getmulti_partial_error.phpt] reason: memcached is not loaded
SKIP Memcached::getServerByKey() [tests/getserverbykey.phpt] reason: memcached is not loaded
SKIP getServerList [tests/getserverlist.phpt] reason: memcached is not loaded
SKIP Memcached::getVersion() [tests/getversion.phpt] reason: memcached is not loaded
SKIP Test for bug 155 [tests/gh_155.phpt] reason: memcached is not loaded
SKIP Test for Github issue 21 [tests/gh_21.phpt] reason: memcached is not loaded
SKIP Test for Github issue 500 [tests/gh_500.phpt] reason: memcached is not loaded
SKIP Test for Github issue #77 [tests/gh_77.phpt] reason: memcached is not loaded
SKIP Test for GH #90 [tests/gh_90.phpt] reason: memcached is not loaded
SKIP Test for Github issue #93 (double and long overflow) [tests/gh_93.phpt] reason: memcached is not loaded
SKIP Memcached::increment() Memcached::decrement() [tests/incrdecr.phpt] reason: memcached is not loaded
SKIP 64-bit Memcached::increment() decrement() incrementByKey() decrementByKey() [tests/incrdecr_64.phpt] reason: memcached is not loaded
SKIP Memcached::incrementByKey() Memcached::decrementByKey() [tests/incrdecr_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::increment() Memcached::decrement() with initial support [tests/incrdecr_initial.phpt] reason: memcached is not loaded
SKIP Memcached::increment() Memcached::decrement() with invalid key [tests/incrdecr_invalid_key.phpt] reason: memcached is not loaded
SKIP Get version [tests/invalid_options.phpt] reason: memcached is not loaded
SKIP Test that callback is invoked on new object [tests/invoke_callback.phpt] reason: memcached is not loaded
SKIP Use callback initializer [tests/invoke_callback_2.phpt] reason: memcached is not loaded
SKIP Test that callback is invoked on new object only once [tests/invoke_callback_twice.phpt] reason: memcached is not loaded
SKIP Test valid and invalid keys - ascii [tests/keys_ascii.phpt] reason: memcached is not loaded
SKIP Test valid and invalid keys - binary [tests/keys_binary.phpt] reason: memcached is not loaded
SKIP Float should not consider locale [tests/locale_float.phpt] reason: memcached is not loaded
SKIP Memcached local server test [tests/localserver.phpt] reason: memcached is not loaded
SKIP MemcachedServer [tests/memcachedserver.phpt] reason: memcached is not loaded
SKIP MemcachedServer [tests/memcachedserver6.phpt] reason: memcached is not loaded
SKIP Memcached::phpinfo() [tests/moduleinfo.phpt] reason: memcached is not loaded
SKIP Memcached GET_PRESERVE_ORDER flag in getMulti [tests/multi_order.phpt] reason: memcached is not loaded
SKIP Test that correct return value is returned [tests/no-not-found.phpt] reason: memcached is not loaded
SKIP Memcached options [tests/options.phpt] reason: memcached is not loaded
SKIP Wrong return values for binary protocol [tests/pr_75.phpt] reason: memcached is not loaded
SKIP Memcached::prepend() [tests/prepend.phpt] reason: memcached is not loaded
SKIP Memcached::appendByKey() [tests/prepend_bykey.phpt] reason: memcached is not loaded
SKIP Memcached::replace() [tests/replace.phpt] reason: memcached is not loaded
SKIP Memcached::replaceByKey() [tests/replace_bykey.phpt] reason: memcached is not loaded
SKIP Memcached result codes. [tests/rescode.phpt] reason: memcached is not loaded
SKIP Cannot reset OPT_PREFIX_KEY #293 [tests/reset_keyprefix.phpt] reason: memcached is not loaded
SKIP Test SASL authentication [tests/sasl_basic.phpt] 
SKIP Session bad configurations, prefix [tests/session_badconf_emptyprefix.phpt] reason: memcached is not loaded
SKIP Session bad configurations, lock wait time [tests/session_badconf_locktime.phpt] reason: memcached is not loaded
SKIP Session bad configurations, persistent [tests/session_badconf_persistent.phpt] reason: memcached is not loaded
SKIP Session bad configurations, prefix [tests/session_badconf_prefix.phpt] reason: memcached is not loaded
SKIP Session bad configurations, invalid save path (server list) [tests/session_badconf_servers-php72.phpt] reason: memcached is not loaded
SKIP Session bad configurations, invalid save path (server list) [tests/session_badconf_servers.phpt] reason: memcached is not loaded
SKIP Session basic open, write, destroy [tests/session_basic.phpt] reason: memcached is not loaded
SKIP Session basic open, write, destroy [tests/session_basic2.phpt] reason: memcached is not loaded
SKIP Session basic open, write, destroy [tests/session_basic3.phpt] reason: memcached is not loaded
SKIP Session lazy binary warning old libmemcached [tests/session_lazy_warning.phpt] reason: memcached is not loaded
SKIP Session lock [tests/session_lock-php71.phpt] reason: memcached is not loaded
SKIP Session lock [tests/session_lock.phpt] reason: memcached is not loaded
SKIP Session persistent [tests/session_persistent.phpt] reason: memcached is not loaded
SKIP Session regenerate [tests/session_regenerate.phpt] reason: memcached is not loaded
SKIP Memcached::setByKey() [tests/set_bykey.phpt] reason: memcached is not loaded
SKIP Compress below factor and fail to plain. [tests/set_comp_below_factor.phpt] reason: memcached is not loaded
SKIP Set default serializer [tests/set_default_serializer.phpt] reason: memcached is not loaded
SKIP Test libmemcached encryption [tests/set_encoding_key.phpt] 
SKIP Test libmemcached encryption [tests/set_encoding_key2.phpt] 
SKIP Set invalid serializer [tests/set_invalid_serializer.phpt] reason: memcached is not loaded
SKIP set large data [tests/set_large.phpt] reason: memcached is not loaded
SKIP set data exceeding size limit [tests/set_large_e2big.phpt] reason: memcached is not loaded
SKIP Compress with 0 factor and get [tests/setget_zero_factor.phpt] reason: memcached is not loaded
SKIP Memcached::setMulti() [tests/setmulti.phpt] reason: memcached is not loaded
SKIP Memcached::setMultiByKey() [tests/setmulti_bykey.phpt] reason: memcached is not loaded
SKIP Set options using setOptions [tests/setoptions.phpt] reason: memcached is not loaded
SKIP Check stats [tests/stats.phpt] reason: memcached is not loaded
SKIP Check stats does not hang on non-blocking binary protocol [tests/stats_hang.phpt] reason: memcached is not loaded
SKIP Touch in binary mode [tests/touch_binary.phpt] reason: memcached is not loaded
SKIP Memcached store & fetch type and value correctness using igbinary serializer [tests/types_igbinary.phpt] reason: memcached is not loaded
SKIP Memcached multi store & multi fetch type and value correctness using igbinary serializer [tests/types_igbinary_multi.phpt] reason: memcached is not loaded
SKIP Memcached store & fetch type and value correctness using JSON serializer [tests/types_json.phpt] reason: memcached is not loaded
SKIP Memcached multi store & multi fetch type and value correctness using JSON serializer [tests/types_json_multi.phpt] reason: memcached is not loaded
SKIP Memcached store & fetch type and value correctness using msgpack serializer [tests/types_msgpack.phpt] reason: memcached is not loaded
SKIP Memcached multi store & fetch type and value correctness using msgpack serializer [tests/types_msgpack_multi.phpt] reason: memcached is not loaded
SKIP Memcached store & fetch type and value correctness using PHP serializer [tests/types_php.phpt] reason: memcached is not loaded
SKIP Memcached multi store & fetch type and value correctness using PHP serializer [tests/types_php_multi.phpt] reason: memcached is not loaded
SKIP Set with undefined key and value [tests/undefined_set.phpt] reason: memcached is not loaded
SKIP Memcached user flags [tests/user-flags.phpt] reason: memcached is not loaded
SKIP Memcached virtual buckets [tests/vbucket.phpt] reason: memcached is not loaded
SKIP Memcached virtual buckets [tests/vbucket_error_7.phpt] reason: memcached is not loaded
SKIP Memcached virtual buckets [tests/vbucket_error_8.phpt] reason: memcached is not loaded
SKIP Get version [tests/version.phpt] reason: memcached is not loaded
=====================================================================
TIME END 2024-07-12 21:49:40

=====================================================================
TEST RESULT SUMMARY
---------------------------------------------------------------------
Exts skipped    :     0
Exts tested     :    29
---------------------------------------------------------------------

Number of tests :   135                 0
Tests skipped   :   135 (100.0%) --------
Tests warned    :     0 (  0.0%) (  0.0%)
Tests failed    :     0 (  0.0%) (  0.0%)
Tests passed    :     0 (  0.0%) (  0.0%)
---------------------------------------------------------------------
Time taken      :     0 seconds
=====================================================================
>>> Completed testing dev-php/pecl-memcached-3.2.0_p20231008
```

**Comment by anthonyryan1** [comment]
Confirmed the next issue. I was testing on a system that enabled memcached in the PHP ini files and you're not.

We also have a warning that your machine has igbinary in the ini and mine does not, so there's a warning that it's loaded twice.

I'll see about getting a vanilla ini file to test on for each of these so system state doesn't leak into the tests. It looks like that will be a problem.

**Comment by anthonyryan1** [comment]
I believe I've fixed the problems with the tests, such that it's now better decoupled from the server state when the tests are being run.

Please try again at your convenience.

**Review by matoro — APPROVED** [review]

**Comment by hydrapolic** [comment]
Thanks @anthonyryan1, just tested with version 3.3.0 https://github.com/gentoo/gentoo/pull/39040, tests pass! <3

**Comment by anthonyryan1** [comment]
Closing in favour of https://github.com/gentoo/gentoo/pull/39040

**Pull request closed without merging**
