### PR TITLE
app-admin/logstash-bin: bump to 2.2.4/2.3.1, remove old

### PR DESCRIPTION
**Pull request by hydrapolic**
Fixes bugs #578954 and #578978

### CODE REVIEW

**Comment by hydrapolic** [comment]
@patricklauer will check this first.

**Comment by monsieurp** [comment]
He doesn't like github.

**Comment by hydrapolic** [comment]
I talked to him, let's do it ;) He said if it breaks, he'll help cleaning it up.

**Comment by idella** [comment]
I shall add it on that basis

**Comment by hydrapolic** [comment]
Thank you @idella!

**Pull request closed without merging**
