### PR TITLE
net-im/ejabberd-16.01-r1: add libressl support

### PR DESCRIPTION
**Pull request by toralf**
compile tested at one tinderbox image

Signed-off-by: Toralf Förster <toralf.foerster@gmx.de>

### CODE REVIEW

**Comment by idella** [comment]
toralf I don't understand,
net-im/ejabberd; maintainers: aidecoe, hanno

arew either of these expected to attend to a pull request?

**Comment by toralf** [comment]
Gah, no, forgot it, just pinged later @aidecoe in #gentoo-dev
I do not find his nickname here, but found @hanno - maybe you'd like to take this change ?

**Comment by monsieurp** [comment]
@blueness also.

**Comment by blueness** [comment]
this is a pretty innocent commit, so i pushed it.

**Pull request closed without merging**
