### PR TITLE
dev-python/rst-linker: bump to 1.7

### PR DESCRIPTION
**Pull request by sbraz**
Using setuptools to run tests seems to work better.
```diff
--- rst-linker-1.6.ebuild       2016-05-26 09:34:54.107144169 +0200
+++ rst-linker-1.7.ebuild       2016-06-07 12:18:35.929113459 +0200
@@ -27,6 +27,7 @@
        >=dev-python/setuptools_scm-1.9[${PYTHON_USEDEP}]
        doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )
        test? (
+               dev-python/path-py[${PYTHON_USEDEP}]
                >=dev-python/pytest-2.8[${PYTHON_USEDEP}]
                dev-python/pytest-runner[${PYTHON_USEDEP}]
        )
@@ -39,7 +40,7 @@
 }
 
 python_test() {
-       py.test || die "tests failed with ${EPYTHON}"
+       esetup.py test
 }
 
 python_install_all() {
```

### CODE REVIEW

**Comment by gktrk** [comment]
Can you reproduce this?

```
>>> Test phase: dev-python/rst-linker-1.7
 * python2_7: running distutils-r1_run_phase python_test
================================================================================ test session starts =================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.30, pluggy-0.3.1
rootdir: /var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7, inifile: pytest.ini
collected 6 items / 1 errors

test_all.py ..xxx.

======================================================================================= ERRORS =======================================================================================
___________________________________________________________________________ ERROR collecting rst/linker.py ___________________________________________________________________________
/usr/lib64/python2.7/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('rst.linker', '/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7-python2_7/lib/rst/linker.py', local('/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7/rst/linker.py'))
==================================================================== 3 passed, 3 xfailed, 1 error in 0.11 seconds ====================================================================
 * ERROR: dev-python/rst-linker-1.7::local failed (test phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  133:  Called src_test
 *   environment, line 2584:  Called distutils-r1_src_test
 *   environment, line  788:  Called _distutils-r1_run_foreach_impl 'python_test'
 *   environment, line  300:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_test'
 *   environment, line 2098:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1402:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1400:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_test'
 *   environment, line  500:  Called distutils-r1_run_phase 'python_test'
 *   environment, line  721:  Called python_test
 *   environment, line 2463:  Called die
 * The specific snippet of code:
 *       py.test || die
 * 
 * If you need support, post the output of `emerge --info '=dev-python/rst-linker-1.7::local'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/rst-linker-1.7::local'`.
 * The complete build log is located at '/var/log/portage/dev-python:rst-linker-1.7:20160607-185123.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/rst-linker-1.7/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7'
 * S: '/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7'

```

**Comment by sbraz** [comment]
Re-pushed, I forgot to force `PYTHONPATH`. It should work now.
```diff
--- rst-linker-1.6.ebuild       2016-04-30 12:34:45.088967905 +0200
+++ rst-linker-1.7.ebuild       2016-06-08 00:38:52.158836366 +0200
@@ -27,6 +27,7 @@
        >=dev-python/setuptools_scm-1.9[${PYTHON_USEDEP}]
        doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )
        test? (
+               dev-python/path-py[${PYTHON_USEDEP}]
                >=dev-python/pytest-2.8[${PYTHON_USEDEP}]
                dev-python/pytest-runner[${PYTHON_USEDEP}]
        )
@@ -39,7 +40,7 @@
 }
 
 python_test() {
-       py.test || die "tests failed with ${EPYTHON}"
+       PYTHONPATH=. py.test || die "tests failed with ${EPYTHON}"
 }
 
 python_install_all() {
```

**Comment by gktrk** [comment]
Here's the full call stack:
```
  File "setup.py", line 58, in <module>
    setuptools.setup(**setup_params)
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib64/python2.7/site-packages/ptr.py", line 79, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib64/python2.7/site-packages/setuptools/command/test.py", line 127, in with_project_on_sys_path
    func()
  File "/usr/lib64/python2.7/site-packages/ptr.py", line 124, in run_tests
    self.result_code = __import__('pytest').main()
  File "/usr/lib64/python2.7/site-packages/_pytest/config.py", line 48, in main
    return config.hook.pytest_cmdline_main(config=config)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 115, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 90, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 120, in _main
    config.hook.pytest_collection(session=session)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 129, in pytest_collection
    return session.perform_collect()
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 561, in perform_collect 
    items = self._perform_collect(args, genitems)
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 597, in _perform_collect
    self.items.extend(self.genitems(node))
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 734, in genitems
    rep = collect_one_node(node)
  File "/usr/lib64/python2.7/site-packages/_pytest/runner.py", line 411, in collect_one_node
    rep = ihook.pytest_make_collect_report(collector=collector)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 333, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 595, in execute
    return _wrapped_call(hook_impl.function(*args), self.execute)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 247, in _wrapped_call
    call_outcome = _CallOutcome(func)
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 264, in __init__
    self.result = func()
  File "/usr/lib64/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 596, in execute
    res = hook_impl.function(*args)
  File "/usr/lib64/python2.7/site-packages/_pytest/runner.py", line 283, in pytest_make_collect_report
    call = CallInfo(collector._memocollect, "memocollect")
  File "/usr/lib64/python2.7/site-packages/_pytest/runner.py", line 149, in __init__
    self.result = func()
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 431, in _memocollect
    return self._memoizedcall('_collected', lambda: list(self.collect()))
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 311, in _memoizedcall   
    res = function()
  File "/usr/lib64/python2.7/site-packages/_pytest/main.py", line 431, in <lambda>
    return self._memoizedcall('_collected', lambda: list(self.collect()))
  File "/usr/lib64/python2.7/site-packages/_pytest/doctest.py", line 175, in collect
    module = self.fspath.pyimport()
  File "/usr/lib64/python2.7/site-packages/py/_path/local.py", line 668, in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
```

distutils-r1 [overrides PYTHONPATH](https://github.com/gentoo/gentoo/blob/master/eclass/distutils-r1.eclass#L630) before the test phase. `esetup.py test` also works as long as you override PYTHONPATH in the phase function. A careful look at the exception reveals the problem:

```
modname: 'rst.linker'
modfile: '/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7-python2_7/lib/rst/linker.py'
self: local('/var/tmp/portage/dev-python/rst-linker-1.7/work/rst.linker-1.7/rst/linker.py'))
```

Tests also pass if you patch `pytest.ini` like so:

```
--- a/pytest.ini
+++ b/pytest.ini
@@ -1,4 +1,4 @@
 [pytest]
-norecursedirs=*.egg .eggs dist build
+norecursedirs=*.egg .eggs dist rst
 addopts=--doctest-modules
 doctest_optionflags=ALLOW_UNICODE ELLIPSIS
```

I am not sure how python people typically fix these problems.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by sbraz** [comment]
@gktrk Hmm yeah I guess using `PYTHONPATH=.` makes it test the files from `${S}` instead of those in `${BUILD_DIR}/lib`. I'd go with something similar to the ini trick but which doesn't require patching:
```sh
python_test() {
    py.test --ignore=rst || die "tests failed with ${EPYTHON}"
}
```
This will make `py.test` ignore the module in `${S}/rst` and make it run  tests using `${BUILD_DIR}/lib/rst` instead. Sounds good to you?

**Comment by gktrk** [comment]
Yup. That sounds like a smart way to solve it.

**Comment by gktrk** [comment]
Hmm ... you typically include ${RDEPEND} in 'test ? ( )' block right? Does this one not require it?

**Comment by gktrk** [comment]
yup, tests fail without it. fixing that and pushing. thanks for your contribution!

**Pull request closed without merging**
