### PR TITLE
kernel-install.eclass: pkg_preinst: fix symlinks for merged-usr

### PR DESCRIPTION
**Pull request by floppym**
Closes: https://bugs.gentoo.org/843821

### CODE REVIEW

**Comment by thesamesam** [comment]
@gentoo/dist-kernel

**Review by thesamesam — APPROVED** [review]
Works for me, thanks.

Do wonder about adding a USE=split-usr (or USE=merged-usr) to make it more predictable but I don't think there's much value in that.

**Review by mgorny — APPROVED** [review]
I don't have an environment to test it but it looks sane-ish.

**Comment by floppym** [comment]
> Do wonder about adding a USE=split-usr (or USE=merged-usr) to make it more predictable but I don't think there's much value in that.

I thought about wiring this up in kernel-build_src_install with a USE flag. However, that would complicate things for gentoo-kernel-bin, which uses a binpkg as a distfile.

I don't think there's any benefit in a USE flag to control the logic in pkg_preinst. Putting the logic in pkg_preinst without a USE flag means the same binpkg can be used on both split-usr and merged-usr systems.

**Pull request closed without merging**
