### PR TITLE
sys-libs/libcxx: add support for libunwind & musl

### PR DESCRIPTION
**Pull request by zzlei**
With USE=libunwind, libcxx will be built against libunwind, instead of libgcc_s.
In addition, a patch will be applied when building against musl-libc.

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by monsieurp** [comment]
Thank you for your PR. Is there a bug report associated with this fix?

**Comment by zzlei** [comment]
@monsieurp No related bug report. It's just a functional enhancement.

**Comment by zzlei** [comment]
It seems I need to reflect the use of flag "libunwind" by libcxx in /usr/portage/profiles/use.local.desc. But I don't see this file in the repo; where can I update it?

**Comment by zzlei** [comment]
> It seems I need to reflect the use of flag "libunwind" by libcxx in /usr/portage/profiles/use.local.desc. But I don't see this file in the repo; where can I update it?

I get it; just need to update metadata.xml instead.

**Comment by zzlei** [comment]
Sorry, I messed up this PR... I'm closing this and will send another one.

**Pull request closed without merging**
