### PR TITLE
dev-php/*: remove unused patches/files

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR cleans up dev-php and removes obsolete patches and files.
See the commits for the packages affected.
All packages are part of the php project which why it should be assign to **gentoo/php** or it's members.
Please review.

### CODE REVIEW

**Comment by kensington** [comment]
@grknight @orlitzky

**Comment by orlitzky** [comment]
The commits that remove the patches look good to me, but I'm not sure that the channel.xml files are unused. The php-pear-r1 eclass is doing,

```bash
PEAR_PN="${PHP_PEAR_PKG_NAME}-${PEAR_PV}"
: ${PHP_PEAR_URI:=pear.php.net}
: ${PHP_PEAR_CHANNEL:=${FILESDIR}/channel.xml}
```

...which looks like a real bad idea to me, but we're stuck with it. Does that wind up using those channel.xml files?

(And will I see the Manifest updates in a pull request? If not, don't forget to run `repoman manifest` before you commit.)

**Comment by kensington** [comment]
> (And will I see the Manifest updates in a pull request? If not, don't forget to run repoman manifest before you commit.)

Only if there's changes to distfiles (thin manifests).

**Comment by mm1ke** [comment]
@orlitzky Thanks for checking those channel.xml files. After I read your comment i remembered that I saw a similar case with other packages & eclasses. It's really difficult to find out if those files are really used or not (expect from maybe installing it).

I've remove those 3 commits for now.

**Comment by orlitzky** [comment]
Thanks, I just pushed the four remaining commits. Don't worry about the channel.xml thing; if I didn't recognize the filename, I would have missed it too. It's ridiculous for an eclass to go poking around in the `$FILESDIR` of the ebuilds that inherit it.

**Comment by kensington** [comment]
It was picked as 6c4ef372ff8792cd66129babf7c055ce84c1b82d...fd5be9e20c437ab9bf3dd451ab66b1bdeb6b4378.

**Pull request closed without merging**
