### PR TITLE
sys-apps/openrc: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes two unused patches from sys-apps/openrc.

Please review.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@mm1ke have you checked that the -9999 ebuilds dont need these?

**Comment by mm1ke** [comment]
@SoapGentoo yes checked the ebuild. Also tested it before. The 9999 ebuild builds fine without the patches.

**Comment by williamh** [comment]
I will take a look at this tomorrow, I need to look at encorporating these upstream, please do not merge.

**Comment by williamh** [comment]
These are already committed upstream, so feel free to merge this p/r.

**Comment by mm1ke** [comment]
Just rebased this PR, can we merge it? :)

**Comment by mm1ke** [comment]
Ping, another rebase. Any chance for a merge :)

**Comment by mm1ke** [comment]
Another rebase, please consider for a merge :)

**Pull request closed without merging**
