### PR TITLE
sys-kernel/raspberrypi-sources: Fix the rest of files for git-r3, like in #6102

### PR DESCRIPTION
**Pull request by DarthGandalf**
Also partially revert 524925d4b833502b81a5c653b57cfe5437820d81

Closes:  https://bugs.gentoo.org/633542

#6102

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@monsieurp
@sarnold

**Comment by DarthGandalf** [comment]
ping?

**Comment by DarthGandalf** [comment]
anyone here?

**Comment by sarnold** [comment]
Apparently I can't merge this but it looks like it should work (I'm assuming you've tested everything).

**Pull request closed without merging**
