### PR TITLE
dev-db/sqlitebrowser: Handling test dependency correctly

### PR DESCRIPTION
**Pull request by saboya**
Changed in: https://github.com/sqlitebrowser/sqlitebrowser/pull/1419/files

### CODE REVIEW

**Comment by juippis** [comment]
Can you walk me through what's happening here? It modifies `if ! use test` block, so when *test* is not enabled? 

If this is a build-time only fix (like for testing phase), there's no need to revbump. If it affects runtime behaviour someway, then revbump, but please don't use `git mv` for this change but make a new file.

**Comment by saboya** [comment]
@juippis Yes, it's a buid-time only fix. I'll force-push a PR without the revbump.

And yes, it's for when test is not enabled. It should remove the dependency from the makefile, but the makefile changed so that `sed` is no longer good.

**Comment by saboya** [comment]
@juippis Force-pushed a PR without the revbump.

**Comment by juippis** [comment]
Thanks! You can use `Closes:` instead of `Bug:` to automatically close the bug on merge.

**Pull request closed without merging**
