### PR TITLE
dev-lang/python: version bump to 3.8.0

### PR DESCRIPTION
**Pull request by Barracuda72**
Bug: https://bugs.gentoo.org/697842
Patches also there.
@gentoo/python

### CODE REVIEW

**Comment by Barracuda72** [comment]
Patch files as an archive
[python-gentoo-patches-3.8.0.tar.xz.gz](https://github.com/gentoo/gentoo/files/3790429/python-gentoo-patches-3.8.0.tar.xz.gz)

**Comment by floppym** [comment]
While I appreciate the effort, I will need to manually review each of the patches anyway. I will probably not be merging this PR.

**Comment by Barracuda72** [comment]
> While I appreciate the effort, I will need to manually review each of the patches anyway. I will probably not be merging this PR.

That's fine by me (I know already that at least some patches ported by me from 3.7.5 requires review and stated that in bug report); I just wanted to give a bit of push by this pull request. Python 3.8.0 was released two weeks ago, and yet there is still no work at all being done by maintainers - no reaction to the bug report, no comments on it, _nothing_. It seems there is no major problems with this version bump, so it should be pretty easy to put it into the tree (masked, of course); wherefore complete silence from the Gentoo Python team seems quite strange for me.

**Comment by juippis** [comment]
Python-3.8 should be added and working now, closing.

**Pull request closed without merging**
