### PR TITLE
net-im/skypeforlinux: New version (5.0.0.5), remove old

### PR DESCRIPTION
**Pull request by karolgrudzinski**
- Added ebuild for new version (5.0.0.5)
- Removed ebuild for version not available anymore (1.16.0.1)

Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=611486

### CODE REVIEW

**Comment by bearsh** [comment]
AFAIK v5.0.0.5 is beta, pkg_postinst still refer to it as alpha

**Comment by karolgrudzinski** [comment]
You're right. This version is called Beta now and is official version available on Skype's download page. I removed pkg_postinst from ebuild.

**Comment by shentino** [comment]
Thumbs up from proxied maintainer.

**Comment by SoapGentoo** [comment]
@karolgrudzinski would you like to co-maintain skype?

**Comment by karolgrudzinski** [comment]
@mgorny @SoapGentoo It depends on what are responsibilities of co-maintainer.

**Comment by mgorny** [comment]
@karolgrudzinski, you will be CC-ed on all bugs reported against the package, and will be partially expected to look at them ;-).

**Comment by shentino** [comment]
Yeah, fundamentally classic and new skype are completely different architecturally so I very much oppose giving them a common name.

The classic version still has features the new one does not and until it gets officially EOL'ed by microsoft I oppose its removal or preemption.

**Pull request closed without merging**
