### PR TITLE
x11-libs/fltk: dedup & xdg-utils migration.

### PR DESCRIPTION
**Pull request by hanetzer**

### CODE REVIEW

**Comment by flappyports** [comment]
please rebase/adjust patches against latest HEAD

**Comment by hanetzer** [comment]
There's some problem here; 1.3.9999's svn repo requires credentials, which I assume
we don't have access to; their website says to press enter twice if prompted for them,
so I think a user:password of `"":""` would be sufficient to fix this. Will look into the svn
eclass and see if it has some tools to use.

**Comment by hanetzer** [comment]
```
>>> Unpacking source...
 * subversion check out start -->
 *      repository: http://seriss.com/public/fltk/fltk/branches/branch-1.3
svn: E170013: Unable to connect to a repository at URL 'http://seriss.com/public/fltk/fltk/branches/branch-1.3'
svn: E215004: No more credentials or we tried too many times.
Authentication failed
 * ERROR: x11-libs/fltk-1.3.9999::gentoo failed (unpack phase):
 *   subversion: can't fetch to /var/cache/portage/distfiles/svn-src/fltk/branch-1.3 from http://seriss.com/public/fltk/fltk/branches/branch-1.3.
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_unpack
 *   environment, line 3219:  Called subversion_src_unpack
 *   environment, line 3544:  Called subversion_fetch
 *   environment, line 3437:  Called die
 * The specific snippet of code:
 *               ${ESVN_FETCH_CMD} ${options} "${repo_uri}" || die "${ESVN}: can't fetch to ${wc_path} from ${repo_uri}.";
 * 
 * If you need support, post the output of `emerge --info '=x11-libs/fltk-1.3.9999::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=x11-libs/fltk-1.3.9999::gentoo'`.
 * The complete build log is located at '/tmp/portage/x11-libs/fltk-1.3.9999/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/x11-libs/fltk-1.3.9999/temp/environment'.
 * Working directory: '/var/cache/portage/distfiles/svn-src/fltk'
 * S: '/tmp/portage/x11-libs/fltk-1.3.9999/work/fltk-1.3.9999'
```

**Comment by hanetzer** [comment]
@flappyports looks like everything is in order now. Thanks to some help from @mgorny
I was able to figure out the svn nouser nopass setup, and fixed the live ebuilds.

**Pull request closed without merging**
