### PR TITLE
Re-keyword etckeeper ~ppc64

### PR DESCRIPTION
**Pull request by luke-jr**
Context: https://bugs.gentoo.org/show_bug.cgi?id=666988

### CODE REVIEW

**Comment by mjeveritt** [comment]
Per https://bugs.gentoo.org/666988#c5 , it's redundant to simply file a PR with changed keywords. Please supply build logs to prove that, at the very least, the package builds successfully on the chosen Arch. Thank you.

**Comment by mjeveritt** [comment]
You may also wish to tag the PR/Bug in your commit message, and re-assign.

**Comment by gyakovlev** [comment]
it's very strange to request a build log for shell scripts...

```sh
[32;01m * [39;49;00mPackage:    sys-apps/etckeeper-1.18.7
[32;01m * [39;49;00mRepository: gentoo
[32;01m * [39;49;00mMaintainer: m.j.everitt@iee.org proxy-maint@gentoo.org
[32;01m * [39;49;00mUSE:        abi_ppc_64 ppc64 elibc_glibc kernel_linux python_targets_python2_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug test userpriv usersandbox
[32;01m * [39;49;00mPackage:    sys-apps/etckeeper-1.18.7
[32;01m * [39;49;00mRepository: gentoo
[32;01m * [39;49;00mMaintainer: m.j.everitt@iee.org proxy-maint@gentoo.org
[32;01m * [39;49;00mUSE:        abi_ppc_64 ppc64 elibc_glibc kernel_linux python_targets_python2_7 test userland_GNU
[32;01m * [39;49;00mFEATURES:   compressdebug network-sandbox preserve-libs sandbox splitdebug test userpriv usersandbox
>>> Unpacking source...
>>> Unpacking etckeeper-1.18.7.tar.gz to /tmp/portage/sys-apps/etckeeper-1.18.7/work
>>> Source unpacked in /tmp/portage/sys-apps/etckeeper-1.18.7/work
>>> Preparing source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
 [32;01m*[0m Applying etckeeper-1.18.6-gentoo.patch ...
[A[277C [34;01m[ [32;01mok[34;01m ][0m
>>> Source prepared.
>>> Configuring source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
>>> Source configured.
>>> Compiling source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
>>> Source compiled.
>>> Test phase: sys-apps/etckeeper-1.18.7
make -j64 -l64   test
mkdir /tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.qitns2jamu
testdir=/tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.qitns2jamu ./test-etckeeper
1..10
ok 1 test: etckeeper init
ok 2 test: etckeeper commit
ok 3 test: etckeeper commit empty dir
ok 4 test: etckeeper commit not empty dir
ok 5 test: etckeeper commit non-default mode
ok 6 # skip (need to use fakeroot, the rest of the root tests will be skipped as well) root_test: check if root
ok 7 # skip root_test: create file owned by root:root
ok 8 # skip root_test: create file owned by bin:daemon
ok 9 # skip test: etckeeper debug (git)
ok 10 test: etckeeper uninit -f
rm -rf /tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.qitns2jamu
>>> Completed testing sys-apps/etckeeper-1.18.7
```

with fakeroot, btw, you are missing a testdep

```sh
Forcing test.
 * etckeeper-1.18.7.tar.gz BLAKE2B SHA512 size ;-) ...                                                                                                                                                                                                                                [ ok ]
>>> Unpacking source...
>>> Unpacking etckeeper-1.18.7.tar.gz to /tmp/portage/sys-apps/etckeeper-1.18.7/work
>>> Source unpacked in /tmp/portage/sys-apps/etckeeper-1.18.7/work
>>> Preparing source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
 * Applying etckeeper-1.18.6-gentoo.patch ...                                                                                                                                                                                                                                         [ ok ]
>>> Source prepared.
>>> Configuring source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
>>> Source configured.
>>> Compiling source in /tmp/portage/sys-apps/etckeeper-1.18.7/work/etckeeper-1.18.7 ...
>>> Source compiled.
>>> Test phase: sys-apps/etckeeper-1.18.7
make -j64 -l64   test
mkdir /tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.UnjSjev7lP
testdir=/tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.UnjSjev7lP fakeroot ./test-etckeeper
1..10
ok 1 test: etckeeper init
ok 2 test: etckeeper commit
ok 3 test: etckeeper commit empty dir
ok 4 test: etckeeper commit not empty dir
ok 5 test: etckeeper commit non-default mode
ok 6 root_test: check if root
ok 7 root_test: create file owned by root:root
ok 8 root_test: create file owned by bin:daemon
ok 9 # skip test: etckeeper debug (git)
ok 10 test: etckeeper uninit -f
rm -rf /tmp/portage/sys-apps/etckeeper-1.18.7/temp/tmp.UnjSjev7lP
>>> Completed testing sys-apps/etckeeper-1.18.7
```

**Comment by mjeveritt** [comment]
@gyakovlev : Thanks for that .. I was marginally more concerned about the bats dependency, which caught me personally out previously, than etckeeper itself. I will fix the test dep as noted!

**Comment by gyakovlev** [comment]
that `bats` thing is also just a bunch of shell scripts.

lmk and I'll merge this.

```sh
qlist bats | xargs file
/usr/libexec/bats/bats:                            Bourne-Again shell script, ASCII text executable
/usr/libexec/bats/bats-exec-suite:                 Bourne-Again shell script, ASCII text executable
/usr/libexec/bats/bats-exec-test:                  Bourne-Again shell script, ASCII text executable
/usr/libexec/bats/bats-format-tap-stream:          Bourne-Again shell script, UTF-8 Unicode text executable
/usr/libexec/bats/bats-preprocess:                 Bourne-Again shell script, ASCII text executable
/usr/bin/bats:                                     symbolic link to ../libexec/bats/bats
/usr/share/doc/bats-0.4.0_p20170219/README.md.bz2: bzip2 compressed data, block size = 900k
/usr/share/man/man1/bats.1.bz2:                    bzip2 compressed data, block size = 900k
/usr/share/man/man7/bats.7.bz2:                    bzip2 compressed data, block size = 900k
```

**Comment by mjeveritt** [comment]
@gyakovlev : Fine by me. Apologies for the apparent paranoia - always sceptical of PR's/bugs with just a keyword change, as often the user doesn't understand the keywording process!

Also, partial slap-on-wrist to self, for not knowing my own packages properly! :smiley:

**Comment by gyakovlev** [comment]
no prob, will merge a bit later.
I used etckeeper on ppc64 for many years at work, it'll be fine.

**Pull request closed without merging**
