### PR TITLE
media-libs/libebur128: bump to 1.2.0

### PR DESCRIPTION
**Pull request by diogocp**
- Bump to EAPI 6
- Drop the dependency on media-libs/speex (jiixyj/libebur128#16)

### CODE REVIEW

**Comment by diogocp** [comment]
@Amynka

**Comment by Amynka** [comment]
Thanks :))

**Comment by diogocp** [comment]
I noticed that you bumped the subslot to 2, but the soname is still libebur128.so.1.

**Comment by Amynka** [comment]
Fixed.. Thanks !

**Pull request closed without merging**
