### PR TITLE
dev-cpp/websocketpp: bump to 0.7.0

### PR DESCRIPTION
**Pull request by sbraz**
More detailed info in the commit message.
@johu Hi, can you look at this? The tests seem to sometimes fail, I have yet to see if I can reproduce this outside of portage and open an upstream issue. Other than that, the changes are pretty simple.
FYI here's the diff with the older ebuild:
```diff
--- websocketpp-0.6.0.ebuild    2016-01-06 01:01:00.552933492 +0100
+++ websocketpp-0.7.0.ebuild    2016-02-27 17:18:30.059936494 +0100
@@ -1,8 +1,8 @@
-# Copyright 1999-2015 Gentoo Foundation
+# Copyright 1999-2016 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
-EAPI=5
+EAPI=6
 
 inherit cmake-utils
 
@@ -20,16 +20,16 @@
        boost? ( dev-libs/boost )
 "
 
-# tests no-op
-RESTRICT="test"
-
 src_configure() {
-       # Disable EXAMPLES as compilation is broken upstream
        local mycmakeargs=(
-               -DBUILD_EXAMPLES=OFF
-               $(cmake-utils_use_enable !boost CPP11)
-               $(cmake-utils_use_build test TESTS)
+               -DENABLE_CPP11="$(usex !boost)"
+               -DBUILD_TESTS="$(usex test)"
        )
 
        cmake-utils_src_configure
 }
+
+src_install() {
+       use examples && DOCS=( examples/ )
+       cmake-utils_src_install
+}
```

### CODE REVIEW

**Comment by sbraz** [comment]
I just noticed the examples aren't installed, I'll fix this tomorrow.

**Comment by monsieurp** [comment]
@johu

**Comment by sbraz** [comment]
It should be good to merge now, whenever Johannes can look at it.

**Comment by johu** [comment]
Thanks, rebased onto gentoo master.

**Pull request closed without merging**
