### PR TITLE
app-portage/elogviewer-2.6: update

### PR DESCRIPTION
**Pull request by rindeal**
- EAPI6
- readme.gentoo -> readme.gentoo-r1
- distutils-r1 -> python-single-r1
- proper src_install()
- minor fixes

Other things worth consideration:
- drop 2.1-r*
- drop 2.6
- drop sparc and x86-fbsd ARCHs

@fuzzyray @dol-sen

### CODE REVIEW

**Comment by dol-sen** [comment]
Why the distutils-r1 to python-single-r1 change?

I personally finding it more annoying getting packages bitching because I have too many pythons in my python_compat and end up having to add entries in package.use to fix things.

**Comment by rindeal** [comment]
> Why the distutils-r1 to python-single-r1 change?

Because the bundled `setup.py` is not used anyway.

> I personally finding it more annoying getting packages bitching because I have too many pythons in my python_compat and end up having to add entries in package.use to fix things.

Portage is bitching only if you have `python_single_target_python2_7` globally and the app is for python3+ only, but that's not a problem on the side of ebuilds and also is not a problem for this app, which supports both major pythons.

**Comment by idella** [comment]
Why is a bundled setup.py ignored?

**Comment by rindeal** [comment]
Because it sucks and is not worth patching.

**Comment by floppym** [comment]
If setup.py is not being used in the ebuild, I agree that distutils-r1 should not be used either.

If elogviewer.py were renamed to elogviewer upstream, setup.py could be used quite easily.

**Comment by monsieurp** [comment]
What's the status here?

**Comment by idella** [comment]
What's the status here?

**Comment by rindeal** [comment]
> What's the status here?

Apparently no objections to merging it.

**Comment by floppym** [comment]
This needs maintainer approval before it is merged.

For what it's worth, the new version seems ok to me.

**Comment by rindeal** [comment]
> This needs maintainer approval before it is merged.

Yeah, but some timeout in case of unresponsiveness should be ok, like 3 notices and 1 month seem appropriate.

**Comment by fuzzyray** [comment]
I'm fine with it being merged.  I'm not where I can do it myself though.

**Pull request closed without merging**
