### PR TITLE
app-emulation/playonlinux : Version bump

### PR DESCRIPTION
**Pull request by Kreyren**
Version bump to 4.3.4
Added app-misc/jq to RDEPEND which was requested by app
Fixes: https://bugs.gentoo.org/672944
Package-Manager: Portage-2.3.53-r1, Repoman-2.3.12
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>

### CODE REVIEW

**Comment by Kreyren** [comment]
Notices issues, fixing

**Comment by Chiitoo** [comment]
> Notices issues, fixing
> 
> EDIT: based on https://paste.pound-python.org/show/IHC6yQ2FRSzW2hZoOLou/ i understand that i can't fix it from my side.

I don't believe GitHub sends notification mail for edits, so I, and likely others watching this place didn't catch that edit of yours.  :]

Which part there exactly do you mean when you say “can't fix it from my side”?

It looks like you haven't done 'git add playonlinux-4.3.4.ebuild'.

Also, it looks like you're doing that as root, under 'kreyren' user's home, which might lead into more and/or less strange permission issues sooner or later.

A few other comments:

- You'd probably want to 'squash' the commits so that there is no separate 'Update Manifest' commit.

- Usually dependencies are sorted alphabetically, but I see they're all over the place before your addition here already... so that would be a bigger change, and I'm not sure if I'd suggest that for a version bump commit.

- With regards to the dependency itself, what exactly does it fix?

**Comment by Kreyren** [comment]
@Chiitoo it's mensioned on https://bugs.gentoo.org/672944 too.. Seems that maintainer is devaway?

I've had missconfigured git it is fixed now

Repoman outputs that playonlinux-4.3.4 is not present in master directory -> Needs to be added by someone who has access to a tree? 

`qj` dependency was requested by the software once i've emerged new version, confirmed working on my system. 

About version bump i would probably agree? POL 4 is obsolete by POL 5 (phoenicis) would be probably saner to focus on ebuild on phoenicis instead..

**Comment by Chiitoo** [comment]
> @Chiitoo it's mensioned on https://bugs.gentoo.org/672944 too.. Seems that maintainer is devaway?

Yes, the main person has not been able to be around for a while now, unfortunately.

While we, the Wine Project, are listed as maintainer as well, I personally haven't ever used PlayOnLinux, nor do I currently have the energy and time to really get familiar with it, so I can't be too much help with maintaining it at this time.  :\

Not sure about @sarnex.

> I've had missconfigured git it is fixed now
> 
> Repoman outputs that playonlinux-4.3.4 is not present in master directory -> Needs to be added by someone who has access to a tree?

That should be fixed by 'git add playonlinux-4.3.4.ebuild'.

> `qj` dependency was requested by the software once i've emerged new version, confirmed working on my system.

You mean PlayOnLinux itself requires it, not some Windows/other application?

> About version bump i would probably agree? POL 4 is obsolete by POL 5 (phoenicis) would be probably saner to focus on ebuild on phoenicis instead..

I haven't looked into that at all.  I'll try to give it a bit of time, soon, I hope.

**Comment by Kreyren** [comment]
Obsolete by https://github.com/gentoo/gentoo/pull/10737

**Pull request closed without merging**
