### PR TITLE
www-client/qutebrowser: add an explicit `kerberos` USE-flag

### PR DESCRIPTION
**Pull request by webknjaz**
Ref: https://github.com/qutebrowser/qutebrowser/issues/4595#issuecomment-2369165892

Signed-Off-By: Sviatoslav Sydorenko <webknjaz@redhat.com>

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [ ] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by ionenwks** [comment]
I don't think it makes sense for qutebrowser ebuild to duplicate the USE of qtwebengine to ensure they're set, e.g. this could also apply to USE="alsa pulseaudio" if you wonder why you have no sound because you built qtwebengine with neither alsa nor pulseaudio support.

Typically I'd assume(?) kerberos users would set this globally too, so it'd end up set on qtwebengine in the process.

Also, while exceptions can be made (e.g. USE=widevine right now), it's generally against gentoo policy to introduce USE that do nothing but add an optional runtime-only dependency. Sometime we can do an optfeature for these though, albeit given how few kerberos users there is I think it'd just be noisy.

**Comment by ionenwks** [comment]
Furthermore, if failed to notice that USE=kerberos was not set on qtwebengine (the big heavy eye-catching package that takes forever to compile), may not necessarily notice on qutebrowser nor PyQt6-WebEngine either so I don't think this is much of an improvement.

**Comment by webknjaz** [comment]
> Furthermore, if failed to notice that USE=kerberos was not set on qtwebengine (the big heavy eye-catching package that takes forever to compile), may not necessarily notice on qutebrowser nor PyQt6-WebEngine either so I don't think this is much of an improvement.

I don't think that an average user's first thought would be to check and arbitrary transitive dependency or even have prior knowledge that it exists, though.

**Comment by webknjaz** [comment]
> USE that do nothing but add an optional runtime-only dependency.

I was seeing it as enabling a feature, because there's no documentation of signaling anywhere that a non-functioning feature needs some change in an unrelated location.

**Comment by webknjaz** [comment]
FWIW, I updated the wiki doc with the instructions: https://wiki.gentoo.org/wiki/Qutebrowser#Kerberos_authentication_does_not_work.

**Pull request closed without merging**
