### PR TITLE
Bitcoin 0.18.0

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by candrews** [comment]
So close...

One small thing... why the -r1 for net-p2p/bitcoind-0.18.0-r1?

The bigger thing - the tests fail for net-p2p/bitcoind-0.18.0-r1:
```
Running tests: random_tests from test/random_tests.cpp
test/test_bitcoin -l test_suite -t "`cat test/random_tests.cpp | grep -E "(BOOST_FIXTURE_TEST_SUITE\\(|BOOST_AUTO_TEST_SUITE\\()" | cut -d '(' -f 2 | cut -d ',' -f 1 | cut -d ')' -f 1`" > test/random_tests.cpp.log 2>&1 || (cat test/random_tests.cpp.log && false)
Test setup error: no test cases matching filter or all test cases were disabled
make[3]: *** [Makefile:14458: test/raii_event_tests.cpp.test] Error 1
```
Here's the log: [build.log](https://github.com/gentoo/gentoo/files/3219016/build.log)


If you can get the tests passing, I'd be happy to merge this, thank you!

**Comment by luke-jr** [comment]
I could disable the tests, but IIRC the existing ebuilds have that issue too. Haven't had time to figure out why (they all pass when building from git).

The bitcoind -r1 is for the patch needed to fix `-daemon` mode.

**Comment by candrews** [comment]
Can you patch it to disable the failing test? Either that or fix it... We can merge with failing tests, sorry

**Comment by a17r** [comment]
> The bitcoind -r1 is for the patch needed to fix `-daemon` mode.

...but there is no `0.18.0` in tree, so why...?

**Comment by candrews** [comment]
@luke-jr I'd really like to merge this - can you please fix the test failures so I can do so?

**Comment by luke-jr** [comment]
The tests pass fine outside of Portage. I haven't figured out yet why they fail within Portage. I'll see if I can make some time to look into it again, but it's certainly not a simple thing.

**Comment by candrews** [comment]
@luke-jr you mentioned you were making progress on this... anything I can test or look at?

**Comment by luke-jr** [comment]
I have a fix for the main issue now, but beyond that there's another one I'm still working on resolving.

**Comment by candrews** [comment]
Hello again @luke-jr - think you can get this PR updated so we can merge it?

**Comment by luke-jr** [comment]
What's the policy for a test that fails 1-10% of the time? Should I just skip it? Leave it? :/

**Comment by mgorny** [comment]
Fix it! But seriously, we usually skip them.

**Comment by luke-jr** [comment]
Fixing this one is a slow process, unfortunately, in part due to how long it takes and how unreliably it is to even reproduce it (it's a test we normally skip in CI simply because of how long a single run takes).

**Comment by candrews** [comment]
The issue is that test `raii_event_creation` fails.

```
/var/tmp/portage/net-p2p/bitcoind-0.18.0-r1/work/bitcoin-2472733a24a9364e4c6233ccd04166a26a68cc65/src # test/test_bitcoin -l test_suite -t raii_event_creation
Test setup error: no test cases matching filter or all test cases were disabled
```
which makes sense as there's an `#ifdef` that skips all the code in the file, which was added in https://github.com/bitcoin/bitcoin/pull/9647/
The test isn't being skipped as that commit intended; it's being cleared but the test is still attempted to be run.

Here's a PR fixing that issue:
https://github.com/bitcoin/bitcoin/pull/16564

**Comment by candrews** [comment]
Merged - thank you!

**Pull request closed without merging**
