### PR TITLE
sys-apps/util-linux 2.30.2 and 2.31 and 9999: enable support of /etc/mtab…

### PR DESCRIPTION
**Pull request by iDarkTemplar**
… being a regular file.

Closes: https://bugs.gentoo.org/637082

### CODE REVIEW

**Comment by Whissi** [comment]
We are probably going to reject this PR. The old behavior is causing problems for systemd users. And given that both supported init systems in Gentoo (OpenRC and systemd) now uses mtab->/proc/self/mounts and throw warnings if it is a regular file, I think even adding a USE flag would cause more problems than help.

Please tell us why you still need this in Gentoo's bug tracker.

**Comment by iDarkTemplar** [comment]
How does this change break systemd? I'm openrc user and it works fine for me. It doesn't force you to use /etc/mtab as regular file, it just allows you to use it instead of that symlink, as far as I know. Openrc support /etc/mtab as symlink, but it also supports it as regular file, and no, it doesn't make any warnings, as far as I can see it's a supported configuration. And without changes requested here it's broken by new util-linux. I'll add info how exactly I found this issue to bug tracker.

**Comment by williamh** [comment]
See the comments I put on the gentoo bug for reasons besides systemd that you should not be using /etc/mtab at all. Software should use /proc/self/mounts.
Also, the plan for OpenRC is to remove /etc/init.d/mtab in the future.
I am in favor of rejecting this pull request.

**Comment by iDarkTemplar** [comment]
I did. So we agree that software should use /proc/self/mounts if it needs /proc/self/mounts. How does that justify breaking /etc/mtab? And why an option to support /etc/mtab as file is disabled on purpose? Does turning this option on forces you to use /etc/mtab as file or what? I thought Gentoo was about a choice and configurability, is it not anymore? As for reasons besides systemd, I didn't see any reasons besides personal preferences, and I'm not forcing my preferences onto you, unlike you do, because capability to use /etc/mtab as symlink to /proc/self/mounts would remain with this change.

**Comment by floppym** [comment]
Exposing this as a USE flag, disabled by default, seems fine to me.

**Comment by Whissi** [comment]
This was already discussed in https://bugs.gentoo.org/637082. In summary: We won't add a USE flag and OpenRC is going to remove "/etc/mtab" support soon.

However, the ebuild already supports "EXTRA_ECONF". Feel free to use this feature to pass `--enable-libmount-support-mtab` flag. But keep in mind: You are on your own.

**Pull request closed without merging**
