### PR TITLE
dev-python/dulwich: bump to 0.19.4, fix deps

### PR DESCRIPTION
**Pull request by sbraz**
```diff
--- dulwich-0.18.6.ebuild	2018-04-28 18:04:14.463510520 +0200
+++ dulwich-0.19.4.ebuild	2018-06-26 01:43:48.209717096 +0200
@@ -1,9 +1,9 @@
 # Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
 
-PYTHON_COMPAT=( python{2_7,3_4,3_5,3_6} )
+PYTHON_COMPAT=( python{2_7,3_{4,5,6}} )
 
 inherit distutils-r1
 
@@ -13,12 +13,18 @@
 
 LICENSE="GPL-2+"
 SLOT="0"
-KEYWORDS="amd64 ~arm64 ~ppc ~ppc64 x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
+KEYWORDS="~amd64 ~arm64 ~ppc ~ppc64 ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x86-macos ~sparc-solaris ~sparc64-solaris ~x64-solaris ~x86-solaris"
 IUSE="doc examples test"
 
+RDEPEND="
+	dev-python/certifi[${PYTHON_USEDEP}]
+	>=dev-python/urllib3-1.21[${PYTHON_USEDEP}]
+"
 DEPEND="
 	dev-python/setuptools[${PYTHON_USEDEP}]
+	doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )
 	test? (
+		${RDEPEND}
 		dev-python/gevent[${PYTHON_USEDEP}]
 		dev-python/geventhttpclient[${PYTHON_USEDEP}]
 		dev-python/mock[${PYTHON_USEDEP}]
@@ -36,15 +42,17 @@
 }
 
 python_test() {
-	emake check
+	# Do not use make check which rebuilds the extension and uses -Werror,
+	# causing unexpected failures.
+	"${EPYTHON}" -m unittest dulwich.tests.test_suite \
+		|| die "tests failed with ${EPYTHON}"
 }
 
 python_install_all() {
 	use doc && local HTML_DOCS=( docs/build/html/. )
 	if use examples; then
-		insinto "/usr/share/doc/${PF}"
 		docompress -x "/usr/share/doc/${PF}/examples"
-		doins -r examples
+		dodoc -r examples
 	fi
 	distutils-r1_python_install_all
 }
```

### CODE REVIEW

**Comment by grobian** [comment]
Why did you close/delete this?  It looks fine to me, yet I don't see it in gx86?  Am I missing something?

**Comment by sbraz** [comment]
Oh crap! I deleted all my GH branches to clean up a little. Let me try to bring it back.

**Comment by sbraz** [comment]
@grobian done, you can either pick the commit or I'll merge it if you're OK with the changes.

**Comment by grobian** [comment]
merge it please, thanks very much!

**Pull request closed without merging**
