### PR TITLE
www-client/firefox: Fix for 48.0 Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=590424

### PR DESCRIPTION
**Pull request by tgbugs**
https://bugs.gentoo.org/show_bug.cgi?id=590424

### CODE REVIEW

**Comment by tgbugs** [comment]
Closing and will resubmit with proper formatting.

**Comment by eldondev** [comment]
Tom, are you emerging with the system-sqlite USE flag enabled? I ran into the sqlite issue as well, but I would imagine if there is an embedded sqlite being used that version would suffice.

**Comment by tgbugs** [comment]
I am emerging with system-sqlite enabled, which means that I need to add the conditional dependency.

**Comment by tgbugs** [comment]
Corrected version https://github.com/gentoo/gentoo/pull/2013

**Comment by axs-gentoo** [comment]
Issue already fixed in gentoo repo with a different patch.  Thank you for your input though!

**Pull request closed without merging**
