### PR TITLE
sys-apps/shadow: Allow POSIX user names

### PR DESCRIPTION
**Pull request by wonderfly**

### CODE REVIEW

**Comment by wonderfly** [comment]
@gentoo/base-system

**Comment by mgorny** [comment]
is this yet another variation of diverging from upstream with no intent of following upstream?

**Comment by wonderfly** [comment]
Is there a particular reason against a more relaxed user name constraint except following upstream?

The user name regex used at upstream is 10 years old. Most Linux distros (Ubuntu, Debian, Fedora, RHEL, Ubuntu) in practice are patching upstream. And for applications that have to support both Windows and Linux, POSIX is a rather reasonable standard.

**Comment by robbat2** [comment]
Do Ubuntu and RHEL really permit numbers as the start of the username? I'd worry about that breaking a lot of code that naively checks the first character via `isdigit`.

**Comment by mgorny** [comment]
> Is there a particular reason against a more relaxed user name constraint except following upstream?

Yes, diverging from upstream causes portability issues. If you start permitting more relaxed usernames, software written for working with original shadow can start failing randomly (and our divergence has already resulted in a CVE). In any case, this is something that needs to be done via a bug and not silently sneaked in via a pull request.

Above considered, I'm closing this with my QA hat on (@gentoo/qa). If you want to pursue this, please open a bug about it and prepare to find very convincing arguments.

**Pull request closed without merging**
