### PR TITLE
Clean up old s6* versions

### PR DESCRIPTION
**Pull request by atlaua**
@williamh

### CODE REVIEW

**Comment by williamh** [comment]
I'll take care of this p/r. I need to wait for a few days before I merge it.

**Comment by flappyports** [comment]
please rebase and fix the Manifest conflicts.

**Comment by williamh** [comment]
I'm really sorry about losing track of this. Please rebase and fix the conflicts. I'll take it from there.

**Comment by flappyports** [comment]
@atlaua Please rebase to fix the Manifest conflicts and then @williamh will merge.  Thank you.

**Comment by atlaua** [comment]
Push is in progess, should be done in a few minutes. Thanks for the
ping, @flappyports, I'd lost track of this too!

**Comment by williamh** [comment]
This has been merged.

**Pull request closed without merging**
