### PR TITLE
app-emulation/firecracker-bin: add 1.2.0

### PR DESCRIPTION
**Pull request by s-hamann**
Trivial version bump for latest upstream release.

Note: Upstream releases now also contain binaries with debug symbols. I ignored them, because I do not think they are of great use to most Gentoo users. If you think the ebuild should be able to install them, please say so. I would then add a `debug` USE flag (or similar).

### CODE REVIEW

**Comment by ceamac** [comment]
@s-hamann there is a conflict, please solve it

**Comment by s-hamann** [comment]
Done. Sorry, I meant to do that earlier.

**Comment by ceamac** [comment]
Look good.

Just a quick question: is there a reason for keeping so many old releases in the tree?

**Comment by s-hamann** [comment]
> Just a quick question: is there a reason for keeping so many old releases in the tree?

No particular reason. It's just that I often think *this* is not the best time to clean up. I think sneaking it into this pull request is not ideal. I'll do it with the next version bump.

**Pull request closed without merging**
