### PR TITLE
www-client/chromium: add 117.0.5398.88

### PR DESCRIPTION
**Pull request by Kangie**
- Update dead devspace URIs
- add `USE=system-zstd`
- move `USE=system*` to `IUSE_SYSTEM_LIBS`

### CODE REVIEW

**Comment by Kangie** [comment]
I'd really appreciate a sanity check build with `USE=system-zstd` if anyone is willing, this has been my first exposure to `gn` and I want to be sure that I got the whole system-shim thing right.

I dropped the GTK4 patches because of the below commit; let's see what happens!

https://github.com/chromium/chromium/commit/e19535767316b9ded7e3e1d9252a79d469016e2f

**Comment by stha09** [comment]
You need to rebase the GTK4 patch. Upstream compiles with gtk-4.1.0.
There is no zstd system replacement. It is simply a no-op in the unbundle script and still uses the bundled copy.

**Comment by Kangie** [comment]
> You need to rebase the GTK4 patch. Upstream compiles with gtk-4.1.0.

Thanks, will do.

> There is no zstd system replacement. It is simply a no-op in the unbundle script and still uses the bundled copy.

I'm under the impression that by adding an entry to the unbundle script and replacing the BUILD.gn for zstd with a system-zstd one that `gn` should use the system version; what am I missing?

I can say that without that shim dropping in system header files, when I unbundle the shipped version builds fail.

**Comment by stha09** [comment]
> > You need to rebase the GTK4 patch. Upstream compiles with gtk-4.1.0.
> 
> Thanks, will do.
> 
> > There is no zstd system replacement. It is simply a no-op in the unbundle script and still uses the bundled copy.
> 
> I'm under the impression that by adding an entry to the unbundle script and replacing the BUILD.gn for zstd with a system-zstd one that `gn` should use the system version; what am I missing?
> 
> I can say that without that shim dropping in system header files, when I unbundle the shipped version builds fail.

Ah you have the gn file in the patches. TBH, I wouldn't try to unbundle more things. It is unsupported upstream, might infer with the sandbox and the compile time reduction is minimal.

**Comment by Kangie** [comment]
I'm just validating a faulty gtk4 build now, but I theoretically _have_ a working patch for it that I'll... update and test if/when this fails!

**Comment by Kangie** [comment]
Ok, got a working `gtk4` patch, just out at appointments; push in about an hour.

**Comment by Kangie** [comment]
OK, bulds and runs with `USE=gtk4`. I'm going to call that a day before someone tells me that _more_ patches are required! :wink:

**Pull request closed without merging**
