### PR TITLE
kde-misc/krename: Use subslot operator for exiv2

### PR DESCRIPTION
**Pull request by a17r**
Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by hasufell** [comment]
I think we want revbumps for adding slot operators afair. @mgorny is that the case?

**Comment by mgorny** [comment]
Yes. Though to avoid -r56 I'd rather add slot ops to all potential other libs too.

**Comment by kensington** [comment]
Until such a point as this is policy please take your bikeshedding somewhere else. This is already cherry-picked as d9dfa8bf442b0da36bd9eedb140dead7017d74f6.

**Comment by hasufell** [comment]
> take your bikeshedding somewhere else

I asked the question _before_ you cherry-picked as part of the __review__. Thanks for your answer @mgorny

**Pull request closed without merging**
