### PR TITLE
dev-php/pecl-xdiff: Version bump 2.1.1

### PR DESCRIPTION
**Pull request by anthonyryan1**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Anthony Ryan <anthonyryan1@gmail.com>

### CODE REVIEW

**Comment by anthonyryan1** [comment]
Amended to add PHP 8.2 support

**Comment by thesamesam** [comment]
Could you rebase and drop old in a separate commit instead (or ideally not at all and clean up later to allow people to downgrade in case of problems)? Thanks!

**Comment by anthonyryan1** [comment]
Rebased

**Comment by thesamesam** [comment]
Thank you!

**Pull request closed without merging**
