### PR TITLE
sys-apps/flashrom: Get rid of underscores in IUSE

### PR DESCRIPTION
**Pull request by eugene-bright**
Closes: https://bugs.gentoo.org/694664

### CODE REVIEW

**Comment by eugene-bright** [comment]
@juippis, finally I got rid of dashes.

**Comment by juippis** [comment]
Thanks, what a massive PR. Let's see if it works...

**Comment by eugene-bright** [comment]
Thanks for help!

**Comment by juippis** [comment]
Thanks for taking care of the package :)

**Pull request closed without merging**
