### PR TITLE
x11-misc/barrier: new package v2.3.2

### PR DESCRIPTION
**Pull request by MathyV**
The ebuild is mostly based on the synergy ebuild as barrier is a fork

Package-Manager: Portage-2.3.81, Repoman-2.3.20
Signed-off-by: Mathy Vanvoorden <mathy@vanvoorden.be>

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
This seems to be already available in ::gentoo at the moment, so I think this can be closed, right?

**Comment by MathyV** [comment]
Yes, it seems that meanwhile @chewi created an ebuild in parallel, no longer needed :-)

**Comment by chewi** [comment]
Oh sorry, was unaware of this. At least you copied most of it from synergy... right?!

**Comment by MathyV** [comment]
Yes, no worries, it was an almost one-on-one copy of synergy ;-)

**Pull request closed without merging**
