### PR TITLE
Add "SSSD" USE flag for sudo.

### PR DESCRIPTION
**Pull request by mazgi**
Add SSSD USE flag to `app-admin/sudo`.

Should I bump revision number?

### CODE REVIEW

**Comment by mazgi** [comment]
Oops...

**Comment by mgorny** [comment]
Yes, since this is a stable ebuild, you should revbump and drop it to ~arch (e.g. `ekeyword ~all sudo-....ebuild`)

**Comment by mgorny** [comment]
@mazgi, are you still there?

**Comment by mazgi** [comment]
Yes!
Please just a moment.
I'm busy at work for out Gentoo production environment...

**Comment by mgorny** [comment]
Pleaes do not ever commit reverse merges of master. Instead, rebase your work on top of current master.

**Comment by monsieurp** [comment]
I will take this PR tomorrow and improve it a bit in order to merge it.

**Comment by mazgi** [comment]
> Pleaes do not ever commit reverse merges of master. Instead, rebase your work on top of current master.

OK.
I'll rebase after all done.

**Comment by mazgi** [comment]
rebased.

**Comment by monsieurp** [comment]
Merged! :+1:

**Comment by mazgi** [comment]
Thanks! :smile:

**Comment by monsieurp** [comment]
You PR is actually breaking the tree. Two issues here:
- sssd isn't keyworded for ia64+sparc.
- sssd isn't recognised as a valid USE flag.

I don't how we can solve these but I'm afraid your changes can't hit the tree just yet.

**Comment by mgorny** [comment]
@monsieurp, but you know that there's CI running for all pull requests and you seen the results before committing, right?

**Pull request closed without merging**
