### PR TITLE
dev-util/packer: bump version to 1.6.1

### PR DESCRIPTION
**Pull request by xp-vit**
This bumps dev-util/packer to latest version 1.6.1.
Also adding myself as proxy maintainer.

Signed-off-by: Viktar Patotski xp.vit.blr@gmail.com
New ebuild is just a copy paste of 1.4.5 version. Already tested this bump in my overlay: https://github.com/xp-vit/gentoo-overlay

### CODE REVIEW

**Comment by mrgz** [comment]
Hey, @xp-vit I guess your PR superseeds [mine](https://github.com/gentoo/gentoo/pull/17177). And you are adding yourself as a maintainer. So, good thing :)

**Comment by xp-vit** [comment]
@mrgz  seems like yes. And since I'm using packer on weekly basis, I'm ready to tale care of it!.

**Comment by ap4y** [comment]
@xp-vit I have made a patch for `1.6.2` along with fixes to the ebuild. Since you want to adopt this packages I was curious if you will be interested in it. I can open a separate PR if you'll prefer it that way. Thanks.

[0001-dev-util-packer-1.6.2-bump.patch.txt](https://github.com/gentoo/gentoo/files/5222565/0001-dev-util-packer-1.6.2-bump.patch.txt)

**Comment by xp-vit** [comment]
@ap4y Thanks a lot! nice changes, however some of them were already applied in upstream (mostly clean up). Do you want to update patch and then I'll update my PR applying it or I can just integrate your changes into my PR? With second way I will need to add your Signoff manually or drop it.

**Comment by ap4y** [comment]
thanks @xp-vit , I'll send you updated patch tomorrow.

**Review by juippis — APPROVED** [review]

**Comment by xp-vit** [comment]
@ap4y Since this PR was merged to upstream, can you please attach your patch to https://bugs.gentoo.org/732174 ? Then we'll make version bump and close this bug. Thanks a lot!!!

**Comment by ap4y** [comment]
@xp-vit I have opened another PR (https://github.com/gentoo/gentoo/pull/17572), I think dev manual recommends this over bugzilla, please let me know if you'll prefer ticket instead. Thanks!

**Comment by xp-vit** [comment]
@ap4y Opening PR is absolutely appreciated! Thanks a lot!

**Pull request closed without merging**
