### PR TITLE
gui-apps/wf-recorder: add 0.5.0

### PR DESCRIPTION
**Pull request by sevz17**
---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by dlan17** [comment]
there is a compiling err with USE="-pipewire -pulseaudio", can you check?

**Comment by sevz17** [comment]
Opened https://github.com/ammen99/wf-recorder/pull/277. Not sure if we should apply it now or wait until it's merged.

**Comment by dlan17** [comment]
> Opened [ammen99/wf-recorder#277](https://github.com/ammen99/wf-recorder/pull/277). Not sure if we should apply it now or wait until it's merged.

since this isn't urgent? so, let's give a few days to see upstream's response, the downside of merging now may lead to rework later (if find something wrong..)

**Comment by dlan17** [comment]
@sevz17 seems no response from upstream, I'm not against this if you want to push with this patch..  feel free

**Comment by sevz17** [comment]
Pushed with the patch applied.

**Pull request closed without merging**
