### PR TITLE
net-dns/knot: version bump

### PR DESCRIPTION
**Pull request by nemunaire**
Update ebuild following new release + remove no more supported upstream releases.

### CODE REVIEW

**Comment by monsieurp** [comment]
@nemunaire: ping.

**Comment by nemunaire** [comment]
Commits updated; also a new release has landed, I skipped this PR original one

**Comment by mgorny** [comment]
```
 * Messages for package net-dns/knot-2.7.1:
 * Log file: /var/log/portage/net-dns:knot-2.7.1:20180821-130743.log

 * QA Notice: Unrecognized configure options:
 * 
 * 	--with-module-cookie
 * 	--with-module-cookie

**Comment by nemunaire** [comment]
Sorry, I didn't have the time past weeks.

QA notice fixed + bump 2.7.2

**Comment by mgorny** [comment]
(also sorry about the delay)

**Pull request closed without merging**
