### PR TITLE
*/s6* related version bumps

### PR DESCRIPTION
**Pull request by arkamar**
This is a version bump of s6 related software to the newest versions. Most significant change is a fix of long standing issue described in https://github.com/gentoo/gentoo/pull/12120#discussion_r296437625, where utilities were installed to `/bin` but linking shared libraries from `/usr/lib*`. Newly, all packages install shared libraries to `/lib*`. Few packages use helper utilities, they were originally installed to `/usr/libexec` but this location was changed to `/lib/s6` (namely `sys-apps/s6` and `sys-apps/s6-rc`).

### CODE REVIEW

**Comment by smaeul** [comment]
I believe changing the helper binary location will require users to restart their supervision trees and recompile their `s6-rc` databases. Maybe we should warn about that?

**Comment by arkamar** [comment]
> I believe changing the helper binary location will require users to restart their supervision trees and recompile their `s6-rc` databases. Maybe we should warn about that?

Yes, you are right! Thanks! I'll add the warning to `pkg_postinst` phase in `sys-apps/s6-rc`. There is probably no issue with `/lib/s6/s6lockd-helper` from `sys-apps/s6` because it is used only by `/bin/s6lockd` which is invoked by `s6-ipcserver`, therefore, everything should work without restart in this case.

**Comment by arkamar** [comment]
@smaeul, I have appended post-install upgrade/downgrade messages to all `s6-rc` ebuilds. What do you think, are they sufficient? I was thinking to add some copy-paste command examples, but I have changed my mind because `s6-rc` source and complied database directory locations can differ installation to installation, thus they have to be written in some pseudo form anyway.

**Comment by smaeul** [comment]
Your instructions look detailed enough to me. Thanks!

**Pull request closed without merging**
