### PR TITLE
x11-libs/vte, gui-libs/vte, gui-libs/vte-common: Version bump to 0.72.0

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
Want to update this for 0.72?

**Comment by flint2** [comment]
> Want to update this for 0.72?

Yes, when I see the release in https://download.gnome.org/sources/vte/?C=M&O=D if RC is not merged I will update open PR and skip RC

**Comment by mattst88** [comment]
The upstream maintainer for vte and gnome-terminal doesn't make tarballs usually. That's why we fetch them from gitlab directly for these two packages. (https://gitlab.gnome.org/GNOME/vte/-/tags)

````
# Upstream is hostile and refuses to upload tarballs.
SRC_URI="https://gitlab.gnome.org/GNOME/${PN}/-/archive/${PV}/${P}.tar.bz2"
````

**Comment by flint2** [comment]
> The upstream maintainer for vte and gnome-terminal doesn't make tarballs usually. That's why we fetch them from gitlab directly for these two packages. (https://gitlab.gnome.org/GNOME/vte/-/tags)
> 
> ```
> # Upstream is hostile and refuses to upload tarballs.
> SRC_URI="https://gitlab.gnome.org/GNOME/${PN}/-/archive/${PV}/${P}.tar.bz2"
> ```

Ah, OK, done

**Pull request closed without merging**
