### PR TITLE
dev-java/jdom: add 2.0.6.1

### PR DESCRIPTION
**Pull request by vaukai**
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by Flowdalic** [comment]
Any particular reason why the new version has no tests anymore?

**Comment by vaukai** [comment]
> Any particular reason why the new version has no tests anymore?

Too many test failures, also in the old version (which seems to simply ignore test failures).

**Comment by Flowdalic** [comment]
Fails to emerge with

```
>>> Compiling source in /data-scratch/var-tmp/portage/dev-java/jdom-2.0.6.1/work/jdom-JDOM-2.0.6.1 ...
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath /usr/share/iso-relax/lib/iso-relax.jar:/usr/share/jaxen-1.2/lib/jaxen.jar:/usr/share/xalan/lib/xalan.jar:/usr/share/bcel/lib/bcel.jar:/usr/share/javacup/lib/javacup.jar:/usr/share/javacup/lib/javacup-runtime.jar:/usr/share/xalan-serializer/lib/xalan-serializer.jar:/usr/share/ant-core/lib/ant.jar:/usr/share/ant-core/lib/ant-bootstrap.jar:/usr/share/ant-core/lib/ant-launcher.jar @sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: core/src/java/org/jdom2/util/JDOMNamespaceContext.java uses unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 warning
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath jdom.jar:/usr/share/iso-relax/lib/iso-relax.jar:/usr/share/jaxen-1.2/lib/jaxen.jar:/usr/share/xalan/lib/xalan.jar:/usr/share/ant-core/lib/ant.jar:/usr/share/ant-core/lib/ant-bootstrap.jar:/usr/share/ant-core/lib/ant-launcher.jar:/usr/share/bcel/lib/bcel.jar:/usr/share/javacup/lib/javacup.jar:/usr/share/javacup/lib/javacup-runtime.jar:/usr/share/xalan-serializer/lib/xalan-serializer.jar @sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:71: error: package org.junit does not exist
import org.junit.After;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:72: error: package org.junit does not exist
import org.junit.AfterClass;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:73: error: package org.junit does not exist
import org.junit.Before;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:74: error: package org.junit does not exist
import org.junit.BeforeClass;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:75: error: package org.junit does not exist
import org.junit.Ignore;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:76: error: package org.junit does not exist
import org.junit.Test;
                ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:207: error: cannot find symbol
		if (tclass.getAnnotation(Ignore.class) != null) {
		                        ^
  symbol:   class Ignore
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:218: error: cannot find symbol
				if (m.getAnnotation(Before.class) != null) {
				                   ^
  symbol:   class Before
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:222: error: cannot find symbol
				if (m.getAnnotation(After.class) != null) {
				                   ^
  symbol:   class After
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:238: error: cannot find symbol
				if (m.getAnnotation(BeforeClass.class) != null) {
				                   ^
  symbol:   class BeforeClass
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:249: error: cannot find symbol
				if (m.getAnnotation(AfterClass.class) != null) {
				                   ^
  symbol:   class AfterClass
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:256: error: cannot find symbol
				Test tanno = null;
				^
  symbol:   class Test
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:257: error: cannot find symbol
				if ((tanno = m.getAnnotation(Test.class)) != null && m.getAnnotation(Ignore.class) == null) {
				                            ^
  symbol:   class Test
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:257: error: cannot find symbol
				if ((tanno = m.getAnnotation(Test.class)) != null && m.getAnnotation(Ignore.class) == null) {
				                                                                    ^
  symbol:   class Ignore
  location: class TranslateTests
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:267: error: package Test does not exist
						if (tanno.expected() == Test.None.class) {
						                           ^
contrib/src/java/org/jdom2/contrib/android/TranslateTests.java:280: error: package Test does not exist
						if (tanno.expected() == Test.None.class) {
						                           ^
Note: contrib/src/java/org/jdom2/contrib/beans/BeanMapper.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
16 errors
1 warning
 * ERROR: dev-java/jdom-2.0.6.1::gentoo failed (compile phase):
```

**Comment by vaukai** [comment]
> * ERROR: dev-java/jdom-2.0.6.1::gentoo failed (compile phase):

Whatever I tried I cannot reproduce those compile errors. 
Does [re-adding the "Remove Android stuff"](https://github.com/gentoo/gentoo/compare/09bc2328d867b6b1587bd0f8e7f534eef0fe7945..3338cb430d830049ec0377fc85c8498881f991d4)  solve it for you?

**Comment by Flowdalic** [comment]
> Does [re-adding the "Remove Android stuff"](https://github.com/gentoo/gentoo/compare/09bc2328d867b6b1587bd0f8e7f534eef0fe7945..3338cb430d830049ec0377fc85c8498881f991d4) solve it for you?

Yes, at least I do no longer see the build failures.

**Pull request closed without merging**
