### PR TITLE
p7zip supports clang and c++17

### PR DESCRIPTION
**Pull request by dannftk**
1. clang is enabled thoroughly
2. the project compiles with c++17

### CODE REVIEW

**Comment by prometheanfire** [comment]
The change looks good, though I do want to know more about that patch (changing the bool to an int).  So we need a good (signed both gpg and text in the message) commit message, also need reason behind the changes (basic is fine).

**Comment by dannftk** [comment]
> The change looks good, though I do want to know more about that patch (changing the bool to an int). So we need a good (signed both gpg and text in the message) commit message, also need reason behind the changes (basic is fine).
> 
> https://wiki.gentoo.org/wiki/Gentoo_GitHub

'bool' is changed to 'int' because c++17 forbids to increment booleans. From the code's context and the name the variable seems to be an integer.
There is a [post](https://www.viva64.com/en/b/0402/) that talks about a research done on 7-zip project with PVS studio. PVS studio finds that issue with boolean increment dangerous. The author assumes that there are two possible variants: either the variable must have been assigned by 'true' or 'false' and been examined in conditions as a boolean, or must have it been an integer what is more probable according to the variable's name. p7zip seems to have adopted this issue from 7-zip project because code looks the same
Also there are [7z](http://npwl.npiot.com:380/lygz/soui/blob/0ca4b55e6aa30bbb69a0bbed1debdd9fc8f6c120/third-part/7z) and [7zip](https://github.com/zone117x/7zip-mirror) project in the internet. There are WimHandler files in there declaring `numMethods` variable as an integer one
For example, debian project also has this numMethods in [WimHandler.cpp](https://sources.debian.org/src/p7zip/16.02+dfsg-6/CPP/7zip/Archive/Wim/WimHandler.cpp/) set as an integer value

**Comment by dannftk** [comment]
The commit is signed both ways

**Comment by prometheanfire** [comment]
ok, commit message needs minor fixups, the title should have more to it's subject than `cat/pkg:`.  The grammar on the commit message text needs a little.  If you want an updated version it's below.

`It is now possible to compile with clang and c++17.`

Beyond that the ebuild should be r5 as it's changing the installed files.

**Comment by prometheanfire** [comment]
oh, and r5 should be fully unstable (all arches marked ~).

**Comment by dannftk** [comment]
@prometheanfire,

should I create a second new ebuild r5 or substitute the existing r4 by a new one?

PS: I am sorry for being newbie in this deal, it is the first time I have committed to the gentoo's portage tree

**Comment by prometheanfire** [comment]
It would be a new file, based on r4, with your changes.  r4 would remain as it currently is in tree.

First time is alright, I still remember my first sunrise commit :D

**Comment by dannftk** [comment]
@prometheanfire,

Should I update a manifest file and if so how do I do that?

**Comment by prometheanfire** [comment]
ya, first, install these two packages, `pkgcheck` and `repoman`.  Once you made your changes run `repoman manifest` and it'll update the manifest file.

When you are ready to commit, run `pkgcheck scan` within the package directory to check for issues (you can ignore the ones below, I'll fix them in a follow-on commit.

    AbsoluteSymlink: version 16.02-r4: dosym called with absolute path on line 143: dosym "/usr/share/kservices5/ServiceMenus/${item}"
    DeprecatedEapiCommand: version 16.02-r4: 'dohtml' deprecated in EAPI 6, used on line 163: 'dohtml -r DOC/MANUAL/*'
    PotentialStable: version 16.02-r4: slot(0), stabled arches: [ alpha, amd64, arm64, hppa, ia64, ppc, ppc64, sparc, x86 ], potential: [ ~arm ]
    UnstableOnly: for arch: [ arm ], all versions are unstable: [ 16.02-r4 ]

Then if that looks good you just run `repoman commit`.  the commit takes values from your git config, the relevant values from the git config are below.

```
[user]
  name = Matthew Thode
  email = prometheanfire@gentoo.org
  signingkey = 0x64A37BEAAE19A4E8
[push]
  gpgsign = 1
[stash]
  sign = false
```

you probably don't need the last two sections but I consider them nice to have (gentoo requires signed pushes, but github doesn't support that yet so, don't include it I guess)

**Comment by dannftk** [comment]
I ran `pkgcheck scan' and got:
```
app-arch/p7zip
  AbsoluteSymlink: version 16.02-r4: dosym called with absolute path on line 143: dosym "/usr/share/kservices5/ServiceMenus/${item}"
  DeprecatedEapiCommand: version 16.02-r4: 'dohtml' deprecated in EAPI 6, used on line 163: 'dohtml -r DOC/MANUAL/*'
  PotentialStable: version 16.02-r4: slot(0), stabled arches: [ alpha, amd64, arm64, hppa, ia64, ppc, ppc64, sparc, x86 ], potential: [ ~arm ]
  AbsoluteSymlink: version 16.02-r5: dosym called with absolute path on line 145: dosym "/usr/share/kservices5/ServiceMenus/${item}"
  DeprecatedEapiCommand: version 16.02-r5: 'dohtml' deprecated in EAPI 6, used on line 165: 'dohtml -r DOC/MANUAL/*'
  UnstableOnly: for arch: [ arm ], all versions are unstable: [ 16.02-r4, 16.02-r5 ]
```
Is it acceptable?
PS: Manifest is left untouched by `repoman manifest`

**Comment by prometheanfire** [comment]
the subject should be `app-arch/p7zip: it is now possible to compile with clang and c++17` (it was missing the `/p7zip part).  Looks good to me otherwise.  I forgot that the manifest wouldn't be touched as the sources stay the same.

**Comment by dannftk** [comment]
is it OK now? Or still any issues?

**Comment by dannftk** [comment]
@prometheanfire,

Could you help me what went wrong? I seem to have done everything the way you offered

**Comment by prometheanfire** [comment]
it's fine, I'll merge it some time today

**Comment by prometheanfire** [comment]
merged, thanks for the work

**Pull request closed without merging**
