### PR TITLE
dev-cpp/notcurses: 2.4.9 -> 3.0.0

### PR DESCRIPTION
**Pull request by dankamongmen**
Remove 2.4.9 after adding 3.0.0. Ideally we would use `libdeflate`, but it's only in `arch-app`, so we pass `-DUSE_DEFLATE=off` for now.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
You forgot to push an .ebuild file :P

**Review by juippis — APPROVED** [review]
Thanks!
```
 * VDB: detected possibly incorrect RDEPEND (dev-cpp/notcurses-3.0.0)
 * sys-libs/zlib < 
```
I'm gonna take the dep out, even though it doesn't matter much since it's basically a dep of `@system` set. 

This was the API-break release? In future, we may have to start thinking about subslots. Well, rather before any rdeps are being added to the gentoo tree. We handle soname API/ABI breakage via subslots in ebuilds, 
https://devmanual.gentoo.org/general-concepts/slotting/index.html#sub-slots

```
 * CMP: listing dev-cpp/notcurses-3.0.0/image info
 * SONAME: libnotcurses++.so.3(32)
 * SONAME: libnotcurses-core.so.3(32)
 * SONAME: libnotcurses.so.3(32)
 * SONAME: libnotcurses++.so.3(64)
 * SONAME: libnotcurses-core.so.3(64)
 * SONAME: libnotcurses.so.3(64)
```
So this'd be `SLOT="0/3"`. When a subslot changes, ie from 3 to 4, all packages linking to this will get rebuilt.

**Comment by dankamongmen** [comment]
yeah the zlib dep ought not be there, sorry. i added libdeflate, then realized it wasn't present outside arch-app, and added that back stupidly.

btw, what's the relationship of gentoo and the "gentoo science overlay"?

thanks for all the info above!

**Comment by juippis** [comment]
Overlays are repositories that go on top of the main ::gentoo repository. So you can't depend on a package in ::gentoo repo that's found from ::science overlay if that's what you are asking? Do I understand it correctly here that the deflate option requires a package that's not available in ::gentoo? You can ofc start maintaining it in ::gentoo if you wish. But if it's available in an overlay, it'd be polite to ask the overlay maintainer first if they're interested in maintaining it in ::gentoo main repo.

**Pull request closed without merging**
