### PR TITLE
sci-biology/bedtools: bump to 2.30.0

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
The samtools patch is no longer needed, as upstream has fixed this. Test
suite passes without it now.

Signed-off-by: Wolfgang E. Sanyer <ezzieyguywuf@gmail.com>

### CODE REVIEW

**Comment by ezzieyguywuf** [comment]
See https://bugs.gentoo.org/696188

**Comment by ezzieyguywuf** [comment]
Is the CI failing solely b/c of the DuplicateFiles warning?

If so, how should I resolve this?

1. rename patch to newer version, and update older ebuild?
2. reference older versioned patch in this new ebuild?
3. remove version from patch filename?

**Comment by SoapGentoo** [comment]
@ezzieyguywuf yup, why duplicate the patch? Just refer to the patch using `${PN}`

**Comment by ezzieyguywuf** [comment]
> 
> 
> @ezzieyguywuf yup, why duplicate the patch? Just refer to the patch using `${PN}`

@SoapGentoo I was worried that referring to `${PN}-2.29.2...` in `bedtools-2.30.0.ebuild` would be misleading/"wrong"

Is this a non-issue?

**Comment by SoapGentoo** [comment]
@ezzieyguywuf yup, complete non-issue, so much that it's encouraged if it avoids duplicating patches. If you fix this, I'll merge it.

**Comment by ezzieyguywuf** [comment]
> 
> 
> @ezzieyguywuf yup, complete non-issue, so much that it's encouraged if it avoids duplicating patches. If you fix this, I'll merge it.

already fixed before your comment even posted :)

**Pull request closed without merging**
