### PR TITLE
gui-apps/swaybg: upgrade to 1.1.1, various fixes

### PR DESCRIPTION
**Pull request by Hello71**
- fix cross-compile deps
- make gdk-pixbuf optional
- add ~riscv to -9999

### CODE REVIEW

**Comment by prometheanfire** [comment]
Hi, thanks for doing this, main thing I want to know is if you've tested 9999 with riscv (and sway in general).

**Comment by Hello71** [comment]
no, but if it's enabled for 1.1 why shouldn't it be enabled for 9999? i don't really care about that personally though

**Comment by prometheanfire** [comment]
do you mind rebasing so this can be merged?

**Comment by prometheanfire** [comment]
thanks, merged

**Pull request closed without merging**
