### PR TITLE
www-servers/nginx: Bump to v1.11.3

### PR DESCRIPTION
**Pull request by Whissi**
Version bump.

 - Upstream added 3 new STREAM modules:
     - geo
     - geoip
     - split_clients

 - Each HTTP/STREAM upstream module can now be enabled/disabled
   using a dedicated USE flag

 - Cherry picked patch to allow build without stream_ssl_module ([ticket #1032](https://trac.nginx.org/nginx/ticket/1032))

### CODE REVIEW

**Comment by Whissi** [comment]
@jbergstroem *ping*

**Comment by monsieurp** [comment]
@jbergstroem hi?

**Comment by jbergstroem** [comment]
LGTM

**Comment by monsieurp** [comment]
If you get round to it for the next PR, think about putting your patches into the PATCHES array and calling epatches "${PATCHES[@]}" in the `src_prepare()` phase. It shortens the code.

**Pull request closed without merging**
