### PR TITLE
acct-*/amavis: New group and user (333) for mail-filter/amavisd-new

### PR DESCRIPTION
**Pull request by rseichter**
Precondition for upgrading amavis ebuild according to [GLEP81](https://wiki.gentoo.org/wiki/Categories_acct-group_and_acct-user).

### CODE REVIEW

**Comment by rseichter** [comment]
@orlitzky Working through my notes, I realized today that this still has not made it into the Gentoo tree.

**Comment by orlitzky** [comment]
This one still needs some thought/testing that I haven't had time to do. I think the amavis user needs to have a home directory, because (at least) spamassassin and pyzor will look to `$HOME/.spamassassin` and `$HOME/.pyzor` for configuration.

I would rather not re-use `/var/lib/amavis/` for its home directory, since that creates an implicit dependency in the `mail-filter/amavisd-new` ebuild on a side effect of the `acct-user/amavis` ebuild. So, where could we put it? The obvious `/home/amavis` can't be used because ebuilds aren't allowed to install into `/home`.

I think `/var/lib/amavis/home` is a good candidate, but I'd have to check to see what happens on a clean install. The user will be installed before amavisd-new is, and we should wind up with `/var/lib/amavis` being owned by `root:root` in that case and `/var/lib/amavis/home` being owned by `amavis:amavis`. Does installing amavisd-new then fix the permissions on `/var/lib/amavis`? I dunno.

**Comment by rseichter** [comment]
I'm not sure `/var/lib/amavis/home` is the best choice, it being a subdirectory of `/var/lib/amavis` which is "owned" by the amavisd-new ebuild. How about using a sibling directory like `/var/lib/amavishome` instead? The name may sound a bit awkward, but it would mean having disjunct directories between the two ebuilds.

**Comment by orlitzky** [comment]
I finally got around to testing this, and `/var/lib/amavis/home` doesn't work because the `root:root` permissions on `/var/lib/amavis` don't get fixed when amavisd-new is installed.

`/home/amavis` would be my next choice, but it's a QA violation at the moment. I asked about it on the -dev list, because maybe that QA rule is counterproductive now that we have GLEP81.

**Comment by orlitzky** [comment]
We've only got one chance to do this right, and the QA team insists on a subpar solution. I don't really want to put my name on that, and TBH I'm just fed up with the whole thing. I've removed myself as maintainer of amavisd-new so that I can take this issue off my to-do list.

**Comment by rseichter** [comment]
> TBH I'm just fed up with the whole thing. I've removed myself as maintainer of amavisd-new so that I can take this issue off my to-do list.

I'm sorry to hear that, but I can understand you, based on the developer mailing list discussion. I don't want to deal with this myself if I am honest. Some developers seem too much like crusaders to me, out to defend the "purity" of Gentoo instead of aiming for pragmatic solutions.

**Comment by rseichter** [comment]
For lack of an alternative, I have added the Antivirus Project as maintainer.

**Comment by SoapGentoo** [comment]
@rseichter please add proxy-maint

**Comment by rseichter** [comment]
@SoapGentoo Just to be sure: Would you like to see both proxy-maint@g.o and antivirus@g.o, or only the former?

**Comment by SoapGentoo** [comment]
In practice it doesnt really make a difference (antivirus is mostly dead), but do the former (i.e. add both proxy-maint and antivirus). If you like, make the order
1. anti-virus
2. you
3. proxy-maint
If you want to maintain this, you can also put anti-virus as the last maintainer, your call.

**Comment by rseichter** [comment]
Updated.

**Comment by rseichter** [comment]
@SoapGentoo I don't know who else to ask, so here goes: Can you please merge this pull request, or actively prod somebody to merge it? I don't mean to be impolite, but I cannot do anything more myself. Another three weeks have passed, and I am very frustrated about this small PR collecting ever more dust. The Amavis team (which includes me) has made changes upstream, and this unresolved pull request blocks potential new Amavis releases for Gentoo.

**Comment by a17r** [comment]
Thanks for your patience.

**Pull request closed without merging**
