### PR TITLE
sci-libs/sundials: upgrade to 3.1.2

### PR DESCRIPTION
**Pull request by cdluminate**
Closes: https://bugs.gentoo.org/679160

### CODE REVIEW

**Comment by heroxbd** [comment]
Thank you for the new pull request.  You still need to move LICENSE to `/usr/share/doc` after `cmake-utils_src_install`, otherwise bug 679160 is not fixed.  Upstream has made a wrong decision and we need to fix it.

**Comment by cdluminate** [comment]
@heroxbd Ok. And do I need to update Manifest as well? What's the tool for that?

**Comment by heroxbd** [comment]
> @heroxbd Ok. And do I need to update Manifest as well? What's the tool for that?

https://devmanual.gentoo.org/general-concepts/manifest/index.html

https://wiki.gentoo.org/wiki/Repoman

**Comment by cdluminate** [comment]
Look good now?

**Comment by heroxbd** [comment]
``` 
.../sci-libs/sundials-3.1.2/image/usr/share/doc  $ ls 
sundials  sundials-3.1.2
```

Gentoo is using `/usr/share/doc/${PF}` , where `${PF}` is defined at https://devmanual.gentoo.org/ebuild-writing/variables/

Versions are used in the directory names because portage has SLOT, where multiple versions of a package can be installed side-by-side.

**Comment by cdluminate** [comment]
Updated and force-pushed. The hardcoded path should be fine since the patch is version-specific.

**Pull request closed without merging**
