### PR TITLE
dev-db/postgis: fix direct ar call

### PR DESCRIPTION
**Pull request by waebbl**
Fix done during bugday 2020-12-05

Closes: https://bugs.gentoo.org/756046
Package-Manager: Portage-3.0.11, Repoman-3.0.2
Signed-off-by: Bernd Waibel <waebbl@gmail.com>

### CODE REVIEW

**Comment by titanofold** [comment]
Please do this as a revbump. Also, include 3.1.0_alpha3.

Have you submitted the patch upstream?

**Comment by titanofold** [comment]
OK, great, thanks!

No problem on upstream. I'll pass it along to them. I didn't want to submit a duplicate.

**Comment by waebbl** [comment]
Ok thanks for the upstream call! :+1:

**Review by titanofold — APPROVED** [review]
Looks good to me. I'll get it merged as soon as I can.

**Pull request closed without merging**
