### PR TITLE
sys-devel/binutils: 2.26.1

### PR DESCRIPTION
**Pull request by P424D0X**

### CODE REVIEW

**Comment by monsieurp** [comment]
:+1: Thanks for the PR. I'm going to merge it.

**Comment by vapier** [comment]
do not do this again.  the toolchain team is responsible for the toolchain, and neither of you are on the toolchain team.  this was not ready for publishing.

**Comment by monsieurp** [comment]
hi? you should relax. it's a mere version bump. i don't think i've harmed anyone in pushing this pr but feel free to revert it if it's such a big deal for you.

**Comment by vapier** [comment]
you seem to be confused.  binutils is a core piece of the OS and used by every package to compile/link.  there's a reason 2.26 wasn't added to the tree, and if you blindly merged a request for that, you would have broken a ton of packages.

it's not "a mere version bump".  if you understood how these ebuilds/eclasses worked, you'd see they rely on a significant patchset with Gentoo changes.  i wasn't done testing that patchset, and had more changes to add and fixes to evaluate before it was ready for unstable.  P424D0X happened to notice i had prematurely uploaded the patchset and did a bump using it.

to be clear: you haven't been maintaining this software for more than a decade in Gentoo.  you haven't written any of the fixes, any of that patches, or touched any of the bugs.  you don't have the experience to judge what's appropriate for adding here.  if you see a package owned by toolchain@, **never** merge it yourself without talking to someone in the toolchain project first.  this is not a request.

**Pull request closed without merging**
