### PR TITLE
www-client/otter: Added support for qtwebengine and qtwebkit

### PR DESCRIPTION
**Pull request by JellyBrick**
Otter can use QtWebkit and QtWebEngine at the same time.

### CODE REVIEW

**Comment by Chiitoo** [comment]
Thanks!

Howver, QtWebKit is kind of on its way out at this time, which is why it was removed from this ebuild (I believe).

**Comment by JellyBrick** [comment]
> Thanks!
> 
> However, QtWebKit is kind of on its way out at this time, which is why it was removed from this ebuild (I believe).

But as long as Otter supports QtWebkit, I think to should be able to use QtWebkit as a backend.

**Comment by juippis** [comment]
I can't even compile this with `+qtwebkit`. I really don't see a point keeping this package in gentoo, it's supposed to be in high-development mode yet this release is from 2 years ago. That's not very convincing in browser market right now.

**Comment by a17r** [comment]
I didn't file https://bugs.gentoo.org/712172 out of the blue. QtWebKit must not be used for browsers.

**Pull request closed without merging**
