### PR TITLE
net-misc:anydesk need media-libs/libcanberra[gtk2]

### PR DESCRIPTION
**Pull request by inode64**
the error when libcanberra compile without gtk2
<pre>
Gtk-Message: 15:50:46.330: Failed to load module "canberra-gtk-module" Gtk-Message: 15:50:46.610: Failed to load module "canberra-gtk-module" Gtk-Message: 15:50:46.620: Failed to load module "canberra-gtk-module" Gtk-Message: 15:50:46.633: Failed to load module "canberra-gtk-module" </pre>

Signed-off-by: INODE64 <ffelix@inode64.com>

### CODE REVIEW

**Comment by jkroonza** [comment]
This is non-fatal anydesk continues on further regardless (for me at least).

On my system at least enabling this USE flag doesn't seem to cause additional harm, so I have no objection to this.

Changing RDEPEND values should be done by way of revision bump though, so please revision bump both ebuilds (6.2.0-r1 to 6.2.0-r2, and 6.2.1 to 6.2.1-r1).

This is to ensure that we can know for a fact what the RDEPEND value is of installed packages.

**Comment by inode64** [comment]
> This is non-fatal anydesk continues on further regardless (for me at least).
> 
> On my system at least enabling this USE flag doesn't seem to cause additional harm, so I have no objection to this.
> 
> Changing RDEPEND values should be done by way of revision bump though, so please revision bump both ebuilds (6.2.0-r1 to 6.2.0-r2, and 6.2.1 to 6.2.1-r1).
> 
> This is to ensure that we can know for a fact what the RDEPEND value is of installed packages.

update

**Comment by jkroonza** [comment]
Hi @inode64 

Thank you.

Please discard your last commit (git rebase -i master is useful for this), then use git mv to rename the existing ebuilds, since this is a trivial change we really don't need to keep the old copies so rename is sufficient.  You can then git commit --amend that such that we stick to a single commit for all of this.

**Comment by inode64** [comment]
Sorry, I'm new to git, create another fork because what you tell me doesn't work,

**Comment by jkroonza** [comment]
> Sorry, I'm new to git, create another fork because what you tell me doesn't work,

I'd rather you don't create a new fork, let's rather try and fix what you're doing, else I can push same in a new PR, but I'd really prefer to get you operational rather.  You keen?  Where exactly are you getting stuck?  I'm generally available in IRC ... #gentoo-proxy-maint.  And if I'm not there, there are usually others willing and able to assist as well.

**Comment by juippis** [comment]
Would `optfeature` be enough? But as @jkroonza said if this doesn't cause any harm, then whatever.

**Comment by jkroonza** [comment]
juippis - I believe we're trying to get rid of gtk2 overall.  anydesk is one of the last blockers I think.

Hard depending on [gtk2] in this case strenghens the dependency on gtk2, and I believe libcanberra only affects sound.  Not sure about other people but I could not care less about sound in this specific use-case.  That said I agree the startup error is misleading, and perhaps it's worth adding the dependency simply to shut that up.  Perhaps linked to IUSE=sound?  And a postinst warning that without sound you may get the error, alternatively, optfeature as you say, something like:

```
pkgpostint() {
   optfeature "Enable sound and work around failing to load libcanberra... error" media-libs/libcanberra[gtk2]
}
```
If I understand the documentation correctly?  I personally prefer the USE flag mechanism though ... but since a recompile of anydesk is not required that's technically not correct, but then again, anydesk is pre-compiled, so it takes all of 10 seconds to re-install.

**Comment by inode64** [comment]
oops i think i made a little mess :-(

**Comment by jkroonza** [comment]
> oops i think i made a little mess :-(

Indeed it does...

Simplest may be to remove your local branch (after copying the stuff for anydesk).  Recreating it off of master and then committing again.

**Comment by inode64** [comment]
I have created a new pull #29576
I have done something wrong because what you told me has not worked

**Pull request closed without merging**
