### PR TITLE
games-puzzle/world-of-goo: update and split for humblebundle and gog vendors 

### PR DESCRIPTION
**Pull request by CaseOf**
Hello,
I made ebuilds for both HumbleBundle and GOG providers of the game.
Chewi on #gentoo-games on freenode told me that splitting in two packages was the best solution he/she can find at that time.
This update drops sdl1 dependency and now uses sdl2.

### CODE REVIEW

**Comment by juippis** [comment]
@chewi 
@gentoo/games 

Is there / should there be a bug to discuss, or is @chewi aware of your contribution here?

**Comment by chewi** [comment]
I'm aware.

**Comment by CaseOf** [comment]
> @chewi
> @gentoo/games
> 
> Is there / should there be a bug to discuss, or is @chewi aware of your contribution here?

He’s aware, he saw the PR link I gave him on #gentoo-games on freenode. Feel free to ask him ;-)

**Comment by CaseOf** [comment]
Hah, you were faster than me ^_^

**Comment by chewi** [comment]
I hadn't realised that you can also obtain the game from 2DBOY itself if you ordered it early enough. I guess they would provide the latest version but I don't know whether it would be the same as Humble Bundle. Do we just drop the old package? Normally we could do a package move but unless it's the same download, that wouldn't make sense here.

And what about the demo? It's no longer downloadable from 2DBOY. I can only find it [here](https://sourceforge.net/projects/slackbuildsdirectlinks/files/worldofgoo/), which isn't terrible so I guess we could keep it?

**Comment by CaseOf** [comment]
If we cant download it from 2DBOY, I think that, yes, we can drop legacy package. This one is the same archive as the old version (1.41) on HumbleBundle though. It has the same checksum.

About demo version, if you think that source is acceptable, we can keep it with this one.

**Comment by chewi** [comment]
Sorry for the wait. I did a bunch of work on top of this. Check out git if you're interested. I found that the Vorbis libraries bundled with the demo clash with system Vorbis libraries pulled in via PulseAudio, causing a crash. I then thought about dropping bundled libraries entirely as I'm not a fan but then I figured the later versions do work for me and we haven't enabled them by default.

**Comment by chewi** [comment]
Oh and please retry the GOG version just in case I broke it!

**Comment by CaseOf** [comment]
Ok, checking now

**Pull request closed without merging**
