### PR TITLE
Test ipython-py3 mask [wip]

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by hsoft** [comment]
The shape of things to come... yay!

**Comment by mgorny** [comment]
Now we just have to figure out a way to do this with minimal fallout.

**Comment by mgorny** [comment]
No, we don't need to kill ipy5. However, we really need to avoid the situation where some random package will prevent Portage from upgrading to ipy6 forever, and most likely also making dep resolution horribly slow. We also need to consider how to limit the changes to ~arch systems.

**Comment by mgorny** [comment]
(so probably in the end up revbumping packages with py27 removed would be the way to go)

**Comment by hsoft** [comment]
With some luck, these commits will make the CI entirely green. I'm not so sure about my `python_gen_cond_dep`. The most important is the `rpy` one: pandas depends on it and it has a lot of revdeps. Masking py27 on pandas has a big ripple effect. the `gen_cond_dep` on rpy allows us to avoid this.

We should tell people in the `sci-*` team to start getting rid of py27 in all future revbumps: ipython is a dep of a lot of stuff there.

**Comment by hsoft** [comment]
@mgorny is it possible that the GLEP73Immutability check doesn't properly consider package.mask? I've been struggling with that.

**Comment by mgorny** [comment]
As in is run on package completely masked? Possible but unlikely.

**Comment by hsoft** [comment]
In my latest commit, `sci-geosciences/seawater` is masked and is part of CI's warnings.

**Comment by mgorny** [comment]
Oh, that `package.mask`. I guess not then; it should probably work if it was masked in specific profiles though.

**Pull request closed without merging**
