### PR TITLE
profiles: Update plasma package.use

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by mgorny** [comment]
@Pesa, @kensington, @yngwin, @Zlogene.

**Comment by mgorny** [comment]
Hmm, I see also a few KDE-related changes. @johu, @alexxy, @creffett, @jmbsvicetto, @mrueg, @scarabeusiv.

**Comment by mgorny** [comment]
We really need to port some teams to github...

**Comment by a17r** [comment]
-kde is necessary in two places because it would trigger the same conflict, as spotted by @johu

**Comment by kensington** [comment]
Thanks, ACK from KDE team.

**Comment by kensington** [comment]
Regarding akonadi-server, I have been wondering if we should mask or even remove completely the qt5 USE flag, since it seems to cause conflicts and not be used by anything.

**Comment by mgorny** [comment]
Let's test the new fun stuff: @gentoo/qt, @gentoo/kde.

**Comment by kensington** [comment]
I didn't get any notification for the above but then again I always seem to be missing a lot of github mail.

**Comment by hasufell** [comment]
> I didn't get any notification for the above but then again I always seem to be missing a lot of github mail.

Github database sometimes has quirks. I've had a problem where I couldn't post issues for weeks, because no one except me could see them. You should contact github support.

**Comment by mgorny** [comment]
So far I've figured out that github usually sends you one mail per issue, until you re-visit it. Also makes sense to check the github inbox.

**Comment by johu** [comment]
@a17r  Thanks. Patch applied.
@mgorny  How can i close this PR?

**Comment by hasufell** [comment]
you didn't merge (instead you cherry-picked or something similar), so github doesn't know it's fixed

**Comment by mgorny** [comment]
If you promise you won't accidentally click 'merge' or push to the mirror, I can give you the privileges to close :).

**Pull request closed without merging**
