### PR TITLE
net-libs/pjproject: Add 2.12.1-r2

### PR DESCRIPTION
**Pull request by orbea**
* Fixes the build with musl
* Fixes a bashism
* Backports two CVE fix patches

Closes: https://bugs.gentoo.org/865719
Upstream-PR: https://github.com/pjsip/pjproject/pull/3220
Upstream-Commit: https://github.com/pjsip/pjproject/commit/bae7e5f4ff9047170e7e160ab52f6d9993aeae80
Bug: https://bugs.gentoo.org/875863
Upstream-Commit: https://github.com/pjsip/pjproject/commit/d2acb9af4e27b5ba75d658690406cec9c274c5cc
Upstream-Commit: https://github.com/pjsip/pjproject/commit/c4d34984ec92b3d5252a7d5cddd85a1d3a8001ae
Closes: https://bugs.gentoo.org/867343
Upstream-PR: https://github.com/pjsip/pjproject/pull/3263

### CODE REVIEW

**Comment by thesamesam** [comment]
@jkroonza: let me know what you think

**Review by jkroonza — APPROVED** [review]
Looks good to me (Assuming you've done the required test compiles).  Just saw the bug and was thinking "here we go again".

Have you or do you intend to submit this upstream to pjproject?  Are we even allowed to given this comes from Alpine?  Can we request them to submit it?

**Comment by orbea** [comment]
> Assuming you've done the required test compiles

Can you elaborate?

> Have you or do you intend to submit this upstream to pjproject?

Good idea. https://github.com/pjsip/pjproject/pull/3263

> Are we even allowed to given this comes from Alpine?

Should not be a problem, its only trivial preprocessor code.

**Comment by jkroonza** [comment]
> > Assuming you've done the required test compiles
> 
> Can you elaborate?

Meaning you compiled both with MUSL and glibc here?

**Comment by orbea** [comment]
> I agree. But I still appreciate the test compile. Is there any usecase where GLIBC can be defined and we won't have <execinfo.h>? If so, why test for PJ_LINUX at all?

Actually this is a good point. Looking it up `execinfo.h` is a GNU specific header, the `PJ_DARWINOS` might also be redundant? I will update the patch.

**Comment by orbea** [comment]
> I will update the patch.

Done.

**Comment by orbea** [comment]
> if you'd like to

@jkroonza Sure I added all of the commits and made added `2.12.1-r2`, can you please check it over to make sure I didn't miss anything?

**Comment by jkroonza** [comment]
@orbea 

Two things I would like to explicitly state that I appreciate:

* The speed of your responses and updates.
* The comments indicating the bug numbers on the PATCHES array!  Good one.

One thing I'm not sure of - should the filenames include the revision number?  I usually include it.  @thesamesam ?

And one thing in commit log:

Closes: https://bugs.gentoo.org/875863

Should be:

Bug: https://bugs.gentoo.org/875863

This is because the bug cannot be closed until stabilization has happened and a GLSA has been issued.

Thank you very much for your efforts.

**Review by jkroonza — CHANGES_REQUESTED** [review]
As above ... need to make comment to relabel.

**Comment by thesamesam** [comment]
Personal preference wrt patch naming. I usually don't bother with revision unless it's distinguishing it from an earlier patch with the same name. But there's no right/wrong :)

**Comment by orbea** [comment]
> The comments indicating the bug numbers on the PATCHES array! Good one.

I would never remember in a few months without such helpful reminders. :)

> One thing I'm not sure of - should the filenames include the revision number? I usually include it.

I changed it to your preference since it was no problem to do so.

> This is because the bug cannot be closed until stabilization has happened and a GLSA has been issued.

Thanks for pointing this out, I did not know this.

**Review by jkroonza — APPROVED** [review]
@thesamesam please merge

**Comment by orbea** [comment]
@jkroonza An alternate equivalent version of the patch was merged upstream so next version you can just drop the musl patch. :)

https://github.com/pjsip/pjproject/commit/c804b31f854b22b3d2806937dd0ba1185ca3875f

**Pull request closed without merging**
