### PR TITLE
net-misc/i2pd: fix static build #591334

### PR DESCRIPTION
**Pull request by khumarahn**
https://bugs.gentoo.org/show_bug.cgi?id=591334
@blueness @tomboy-64 @klondi

### CODE REVIEW

**Comment by blueness** [comment]
My understanding is that this will only add -ldl when statically linking.  If that's the case, the I'll commit.  If we add -ldl unconditionally then we're probably overlingking.

**Comment by khumarahn** [comment]
Here is the build command that I see without `static` use flag:
```
/usr/bin/x86_64-pc-linux-gnu-g++   -O2 -pipe -march=native  -Wall -Wextra -Winvalid-pch -std=c++11 \
-pipe -maes -pthread -fPIC   -Wl,-O1 -Wl,--as-needed \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/Daemon.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/HTTPServer.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/I2PControl.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/i2pd.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/UPnP.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/DaemonLinux.cpp.o  \
-o i2pd  -L/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0_build/zlib/lib -rdynamic \
-lminiupnpc libi2pd.a libi2pdclient.a -ldl -lboost_system-mt -lboost_filesystem-mt \
-lboost_program_options-mt -lboost_date_time-mt -lssl -lcrypto -lz -pthread -ldl \
-lboost_system-mt -lboost_filesystem-mt -lboost_program_options-mt -lboost_date_time-mt \
-lssl -lcrypto -lz libi2pd.a \
-Wl,-rpath,/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0_build/zlib/lib
```

**Comment by khumarahn** [comment]
For comparison, this is linking without the patch:
```
/usr/bin/x86_64-pc-linux-gnu-g++   -O2 -pipe -march=native  -Wall -Wextra -Winvalid-pch -std=c++11 \
-pipe -maes -pthread -fPIC   -Wl,-O1 -Wl,--as-needed \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/Daemon.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/HTTPServer.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/I2PControl.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/i2pd.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/UPnP.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0/DaemonLinux.cpp.o  \
-o i2pd  -L/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0_build/zlib/lib -rdynamic \
-lminiupnpc libi2pd.a libi2pdclient.a -ldl -lboost_system-mt -lboost_filesystem-mt \
-lboost_program_options-mt -lboost_date_time-mt -lssl -lcrypto -lz -pthread \
libi2pd.a \
-Wl,-rpath,/var/tmp/portage/net-misc/i2pd-2.9.0/work/i2pd-2.9.0_build/zlib/lib
```

**Comment by blueness** [comment]
The comparison should be with the patch, but between USE=static and USE=-static.

**Comment by khumarahn** [comment]
with patch, with USE=static:
```
/usr/bin/x86_64-pc-linux-gnu-g++   -O2 -pipe -march=native  -Wall -Wextra -Winvalid-pch -std=c++11 \
-pipe -maes -pthread   -Wl,-O1 -Wl,--as-needed -static \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/Daemon.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/HTTPServer.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/I2PControl.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/i2pd.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/UPnP.cpp.o \
CMakeFiles/i2pd.dir/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0/DaemonLinux.cpp.o  \
-o i2pd  -L/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0_build/zlib/lib -rdynamic \
-lminiupnpc libi2pd.a libi2pdclient.a -ldl -Wl,-Bstatic -lboost_system -lboost_filesystem \
-lboost_program_options -lboost_date_time -lssl -lcrypto -lz -Wl,-Bdynamic -pthread \
-ldl -Wl,-Bstatic -lboost_system -lboost_filesystem \
-lboost_program_options -lboost_date_time -lssl -lcrypto -lz \
libi2pd.a -Wl,-Bdynamic \
-Wl,-rpath,/var/tmp/portage/net-misc/i2pd-2.9.0-r1/work/i2pd-2.9.0_build/zlib/lib
```

**Comment by blueness** [comment]
looks okay, pushed.

**Pull request closed without merging**
