### PR TITLE
app-antivirus/clamav: add 1.0.0_rc2; drop 0.105.1

### PR DESCRIPTION
**Pull request by Kangie**
Signed-off-by: Matt Jolly <Matt.Jolly@footclan.ninja>

### CODE REVIEW

**Comment by Kangie** [comment]
This should make the 1.0.0 revbump trivial :)

- dropped external TomsFastMath (see Cisco-Talos/clamav/issues/743)
- A bunch of crates are now required
  + I could use some feedback on licences as a result - it's my first rust crated ebuild!

cargo ebuild suggests `LICENSE="(MIT 0BSD Apache-2.0 Apache-2.0) Apache-2.0-with-LLVM-exceptions BSD Boost-1.0 ISC MIT MPL-2.0 Unicode-DFS-2016 Unlicense ZLIB"`

I'll do some searching and see if I can come up with something that I'm happy with.

Not ready to merge until I've had a chance to update `LICENSE` in the ebuild!

**Comment by Kangie** [comment]
Everything looks good aside from the `jit` flag which still fails to link.

[build.log](https://github.com/gentoo/gentoo/files/9942688/build.log)
[emerge-info.txt](https://github.com/gentoo/gentoo/files/9942691/emerge-info.txt)

**Comment by Kangie** [comment]
Added RC2. Having some trouble with CMake selecting py3.12 and failing to run unit tests so I'll need to come up with a solution for that before 1.0.0 (upstream says they're aiming for around the end of the month).

Everything else seems fine!

**Comment by Kangie** [comment]
@orlitzky Are you intending to maintain the 1.0.0 LTS releases as well?

**Comment by orlitzky** [comment]
> @orlitzky Are you intending to maintain the 1.0.0 LTS releases as well?

No, it's become more trouble than it's worth to me.

**Comment by LordVan** [comment]
Sorry I was super busy (as usual this time of the year). I will have a quick look asap - although why drop 0.105.1 because of the 1.00_rc2 ? I would keep it until it is released at least tbh

**Comment by LordVan** [comment]
Actually I do not agree with you keeping the 0.105 patch file name and dropping 0.105 completely and using that for 1.0.0 (apart from leaving 0.105 for now until final 1.0 release if you make a patch for 1.0 please also name it that way

**Comment by Kangie** [comment]
It's mostly because there's no point having older STS releases than the current LTS (which is imminently 1.0.0); I'm actually considering dropping 0.104.x as well with the same rationale. 0.103.x gets a pass as it's supported for another few years and due to the inclusion of required rust code in the next LTS is going to be the only option for certain arches.

I don't expect us to merge this until 1.0.0 is officially out and the PR has been updated unless we *really* want to push a release candidate out instead of waiting a week or so for the official 1.0.0.

No rush getting this reviewed or merged; I was just in a position to continue the rust changes from 0.105 and figured a PR would be a good place to track that. I am definitely interested in any feedback you may have though!

I *still* can't work out what's going on with LLVM linking / the `jit` use, any input there would be appreciated!

**Comment by LordVan** [comment]
I will look but for some reason it fails linking the clamav stuff on my machine gonna have to investigate that first:
[build.log](https://github.com/gentoo/gentoo/files/10050752/build.log)

Not sure why tbh .. maybe you see something (or I see it in the morning as it is getting late here now)

**Comment by Kangie** [comment]
It seems to be failing to build the rust side of things in that log. I can confirm that it 'just works' for me, and your log doesn't appear to be 'missing crate' or any of the usual suspects.

Ah

>```error: package `image v0.24.5` cannot be built because it requires rustc 1.61.0 or newer, while the currently active rustc version is 1.60.0```

I'll add a minimum rust version - I'm running 1.65 for development so never noticed!

**Comment by Kangie** [comment]
After a bit of research this afternoon it looks like I should patch the CMakeLists to look for a specific python version. This should prevent CMake from selecting a python impl according to its own internal logic and let us respect `PYTHON_COMPAT`. I'll get that done before 1.0.0.

**Comment by thesamesam** [comment]
commit 5417ffb0a0d9e19240e4c5f1ecdc9d36bf8c63c5
Author: Sam James <sam@gentoo.org>
Date:   Wed Nov 23 01:44:26 2022 +0000

    app-antivirus/clamav: unkeyword RC versions

    Signed-off-by: Sam James <sam@gentoo.org>

commit e15d277d2bd24eafbe60674be3e41db261d40498
Author: Matt Jolly <Matt.Jolly@footclan.ninja>
Date:   Sat Nov 5 11:19:12 2022 +1100

    app-antivirus/clamav: add 1.0.0_rc2

    Signed-off-by: Matt Jolly <Matt.Jolly@footclan.ninja>
    Signed-off-by: Sam James <sam@gentoo.org>

**Pull request closed without merging**
