### PR TITLE
sys-cluster/keepalived: bump to 1.4.2/drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
Fixes https://bugs.gentoo.org/648252

### CODE REVIEW

**Comment by hydrapolic** [comment]
@ultrabug

**Comment by ultrabug** [comment]
awesome thanks mate

**Comment by hydrapolic** [comment]
Meanwhile, 1.4.2 got released that includes the linux-headers-4.15 patch :) If you want, I can open a PR for that or just move this to 1.4.2 and drop the patch.

**Comment by ultrabug** [comment]
PR is good, you're the one behind it! thx

**Comment by hydrapolic** [comment]
Ok I'll push the change next week.

**Comment by hydrapolic** [comment]
@ultrabug, pushed 1.4.2 :)

**Comment by hydrapolic** [comment]
Been using it for a few weeks, seems fine :)

**Comment by ultrabug** [comment]
Dunno why but trying to merge this fails in applying the patch because of the Manifest it seems, so can't easily merge it for now. Can you redo/rework it a bit ?

**Comment by hydrapolic** [comment]
@ultrabug, pushed again, should work now :)

**Comment by ultrabug** [comment]
Still not, are you sure you rebased ?

```
error: patch failed: sys-cluster/keepalived/Manifest:1
error: sys-cluster/keepalived/Manifest: patch does not apply
```

**Comment by hydrapolic** [comment]
Hm, strange. I did a complete re-work of the bump/drop, no idea why it fails :(

**Pull request closed without merging**
