### PR TITLE
app-admin/lnav: Backport patches to fix tests, build failure, and a segfault

### PR DESCRIPTION
**Pull request by bowlofeggs**
Please see individual commit messages for details.

Closes: https://bugs.gentoo.org/713600
Closes: https://bugs.gentoo.org/786456
Closes: https://bugs.gentoo.org/792582
Package-Manager: Portage-3.0.18, Repoman-3.0.2
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
I'm having problems compiling either version. I wonder, if it's related to gcc-11?
```
In file included from lnav_log.hh:49,
                 from lnav_log.cc:86:
opt_util.hh:66:1: error: 'optional_constexpr' does not name a type
   66 | optional_constexpr nonstd::optional< typename std::decay<T>::type > make_optional_from_nullable( T && v )
      | ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:413: lnav_log.o] Error 1
make[3]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src/base'
make[2]: *** [Makefile:1193: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src'
make[1]: *** [Makefile:917: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src'
make: *** [Makefile:489: all-recursive] Error 1
 * ERROR: app-admin/lnav-0.9.0-r1::gentoo failed (compile phase):
 *   emake failed
 * 
```

**Comment by bowlofeggs** [comment]
Hi @juippis!

Yes, there is an issue with gcc-11 that I have been meaning to attend to: https://bugs.gentoo.org/786456

I see that upstream has written a patch in response to that issue, so I may be able to backport it to Gentoo (there is not yet an upstream release with that fix). If I can make time to do that, would you like me to try to do that in this PR, or would a separate PR be preferred?

**Comment by juippis** [comment]
Please include it in this PR, since right now, this is unbuildable on ~arch without dirty hacks.

**Comment by bowlofeggs** [comment]
Hello @juippis! Apologies for taking so long - it was a while before I could make the time to perform the backport for the gcc-11 fix. At first it seemed a bit tricky, but then I realized that I only needed part of the patch, and fortunately that part of the patch cleanly applies.

**Review by juippis — COMMENTED** [review]
Sorry for not noticing updates to this PR.

`0.9.0` seems to fail every time, while `0.9.0-r1` seems to fail with `-unicode`.
```
 * Package:    app-admin/lnav-0.9.0
 * Repository: gentoo
 * Maintainer: randy@electronsweatshop.com proxy-maint@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux unicode userland_GNU
...
In file included from lnav_log.hh:49,
                 from lnav_log.cc:86:
opt_util.hh:66:1: error: 'optional_constexpr' does not name a type
   66 | optional_constexpr nonstd::optional< typename std::decay<T>::type >                         make_optional_from_nullable( T && v )
      | ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:413: lnav_log.o] Error 1
make[3]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src/base'
make[2]: *** [Makefile:1193: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src'
make[1]: *** [Makefile:917: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src'
make: *** [Makefile:489: all-recursive] Error 1
 * ERROR: app-admin/lnav-0.9.0::gentoo failed (compile phase):
 *   emake failed
```
```
 * Package:    app-admin/lnav-0.9.0-r1
 * Repository: gentoo
 * Maintainer: randy@electronsweatshop.com proxy-maint@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
...
listview_curses.cc: In member function 'virtual void listview_curses::do_update()':
listview_curses.cc:289:13: error: 'mvwin_wchnstr' was not declared in this scope; did you mean      'mvwinchnstr'?
  289 |             mvwin_wchnstr(this->lv_window, y, this->lv_x, row_ch, width - 1);
      |             ^~~~~~~~~~~~~
      |             mvwinchnstr
listview_curses.cc:293:13: error: 'mvwadd_wchnstr' was not declared in this scope; did you mean     'mvwaddchnstr'?
  293 |             mvwadd_wchnstr(this->lv_window, y, this->lv_x, row_ch, width - 1);
      |             ^~~~~~~~~~~~~~
      |             mvwaddchnstr
make[3]: *** [Makefile:1160: listview_curses.o] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src'
make[2]: *** [Makefile:1193: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src'
make[1]: *** [Makefile:917: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0-r1/work/lnav-0.9.0/src'
make: *** [Makefile:489: all-recursive] Error 1
 * ERROR: app-admin/lnav-0.9.0-r1::gentoo failed (compile phase):
 *   emake failed
```
```
 * Package:    app-admin/lnav-0.9.0
 * Repository: gentoo
 * Maintainer: randy@electronsweatshop.com proxy-maint@gentoo.org
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox userpriv usersandbox
...
In file included from lnav_log.hh:49,
                 from lnav_log.cc:86:
opt_util.hh:66:1: error: 'optional_constexpr' does not name a type
   66 | optional_constexpr nonstd::optional< typename std::decay<T>::type >                         make_optional_from_nullable( T && v )
      | ^~~~~~~~~~~~~~~~~~
make[3]: *** [Makefile:413: lnav_log.o] Error 1
make[3]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src/base'
make[2]: *** [Makefile:1193: all-recursive] Error 1
make[2]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src'
make[1]: *** [Makefile:917: all] Error 2
make[1]: Leaving directory '/var/tmp/portage/app-admin/lnav-0.9.0/work/lnav-0.9.0/src'
make: *** [Makefile:489: all-recursive] Error 1
 * ERROR: app-admin/lnav-0.9.0::gentoo failed (compile phase):
 *   emake failed
```

**Comment by thesamesam** [comment]
First error looks GCC11 related, second seems to be [this](https://github.com/tstack/lnav/issues/865) .

**Comment by thesamesam** [comment]
Tested now. This PR seems to fix each of those errors and works for me, so I'll merge.

**Pull request closed without merging**
