### PR TITLE
net-im/telegram-desktop-bin: bump 4.1.1

### PR DESCRIPTION
**Pull request by joecool1029**
Signed-off-by: Joe Kappus <joe@wt.gd>

### CODE REVIEW

**Comment by henning-schild** [comment]
ACK

It seems this packages maintains itself ;)

**Comment by henning-schild** [comment]
what is going on with this one? please merge

**Comment by joecool1029** [comment]
So now that 4.2.0 is out, do I change this to bump to that or open a new PR? or just add both packages to this request?

**Comment by juippis** [comment]
Hey, 

first of all sorry for not noticing this earlier. 

Please add the new version in this PR then rebase and squash your commits so you only add the newest version. Adding 4.1.1 and 4.2.0 wouldn't make much sense since no one would ever install 4.1.1 after 4.2.0 is available.

**Comment by joecool1029** [comment]
>Please add the new version in this PR then rebase and squash your commits so you only add the newest version. 

I think I did what you asked for?

>Adding 4.1.1 and 4.2.0 wouldn't make much sense since no one would ever install 4.1.1 after 4.2.0 is available.

Eh, by that logic all the old versions should be dropped from the tree. In the least 4.1.0 should have gone 4.1.1.  I don't use the -bin enough to opine about whether major versions tend to have breakages but the non -bin there's been some historical reasoning for hanging on older versions longer than expected.

**Comment by juippis** [comment]
> I think I did what you asked for?
> 

Yes, looks good, testing atm.


> Eh, by that logic all the old versions should be dropped from the tree. In the least 4.1.0 should have gone 4.1.1. I don't use the -bin enough to opine about whether major versions tend to have breakages but the non -bin there's been some historical reasoning for hanging on older versions longer than expected.

You **leave** a version that's proven to work in case the bump doesn't for some reason. You don't add many versions hoping one of them would work.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
