### PR TITLE
sys-apps/eza: add 0.16.3, drop 0.14.0, 0.15.0

### PR DESCRIPTION
**Pull request by sevz17**

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
error[E0433]: failed to resolve: use of undeclared crate or module `git2`
   --> src/main.rs:230:18
    |
230 |             .map(git2::Repository::open)
    |                  ^^^^ use of undeclared crate or module `git2`
    |
help: there is a crate or module with a similar name
    |
230 |             .map(git::Repository::open)
    |                  ~~~

For more information about this error, try `rustc --explain E0433`.
error: could not compile `eza` (bin "eza") due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name eza --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C                    metadata=d9433cf4a8a661af -C extra-filename=-d9433cf4a8a661af --out-dir /var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps -L dependency=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps --extern ansiterm=/var/tmp/portage/sys-apps/eza- 0.16.2/work/eza-0.16.2/target/release/deps/libansiterm-4bcad5722beea530.rlib --extern chrono=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libchrono-97ee6d0d564e14f0.rlib --extern eza=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/  deps/libeza-742b2b9a8103ea04.rlib --extern glob=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libglob-e0ac7f1068441e63.rlib --extern libc=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/liblibc-a8aba44f97f2fa81.rlib --extern     locale=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/liblocale-ff2065f28a2ad829.rlib --extern log=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/liblog-c48cb34e5e36b8ec.rlib --extern natord=/var/tmp/portage/sys-apps/eza-0.16.2/ work/eza-0.16.2/target/release/deps/libnatord-cb9acc1a76dc71a4.rlib --extern num_cpus=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libnum_cpus-fd730de7188fcaac.rlib --extern number_prefix=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/     release/deps/libnumber_prefix-d6814778a0742f75.rlib --extern once_cell=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libonce_cell-6a353a784dd13945.rlib --extern palette=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libpalette- 11c0d215ae284fbb.rlib --extern percent_encoding=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libpercent_encoding-038e7247177add6a.rlib --extern phf=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libphf-ad4e257054333f98.rlib -- extern plist=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libplist-e69c40ee70973f0e.rlib --extern proc_mounts=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libproc_mounts-1ac6074bbc8795e0.rlib --extern scoped_threadpool=/var/ tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libscoped_threadpool-e829cd09a7d7a261.rlib --extern terminal_size=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libterminal_size-8c96f0bab80e8dfb.rlib --extern timeago=/var/tmp/portage/ sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libtimeago-6dfbefeedb1c68eb.rlib --extern unicode_width=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libunicode_width-a4914f373a9bbe63.rlib --extern term_grid=/var/tmp/portage/sys-apps/eza-0.16.2/ work/eza-0.16.2/target/release/deps/libterm_grid-d6c90b5b17d330fb.rlib --extern uzers=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/release/deps/libuzers-80357973f361c9d9.rlib --extern zoneinfo_compiled=/var/tmp/portage/sys-apps/eza-0.16.2/work/eza-0.16.2/target/    release/deps/libzoneinfo_compiled-d7b84ee1383bdf2f.rlib` (exit status: 1)
 * ERROR: sys-apps/eza-0.16.2::gentoo failed (compile phase):
 *   cargo build failed
```

EDIT: This seems to be with `-git`

**Comment by sevz17** [comment]
Right, see https://github.com/eza-community/eza/issues/698.

If possible, please cherry-pick the commits dropping 0.1{4,5}, I did local tests and seems like all 0.16.x are affected

**Comment by MartinFillon** [comment]
FYI there is a PR on eza right know to fix this waiting for original writer modifications

**Comment by sevz17** [comment]
@juippis please review again, the fix is in 0.16.3

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
