### PR TITLE
www-apps/gitea: bump + maintainership

### PR DESCRIPTION
**Pull request by nemunaire**
Hi!

I maintain gitea in my own overlay for many months now: https://github.com/nemunaire/gentoo-overlay/commits/master/www-apps/gitea, as I noticed the package need a maintainer, I propose myself.

I merged my changes with the already existing ebuild: some are to be able to compile newer release, some others to prepare a basic configuration.

### CODE REVIEW

**Comment by hydrapolic** [comment]
Ongoing bump request in https://github.com/gentoo/gentoo/pull/10601. Maybe you both can be listed as maintainers if you wish.

**Comment by nemunaire** [comment]
Thanks @hydrapolic ; I don't care about maintainership, just want to help to have an up-to-date portage tree, as gitea 1.5.2 is 4 months old, contains at least 10 security vulnerabilities patched in next releases.

**Comment by xdch47** [comment]
1.7.1 has been released in the meantime - I would propose @nemunaire - he seem to be more experienced than myself and last but not least his logo is logo is more than adequately :)

**Comment by xdch47** [comment]
maybe @nemunaire can create a new pull request going straight to 1.7.1 ?

**Comment by Perlovka** [comment]
I would suggest to use gitea user instead of git. It's already used by gitolite.

-

**Comment by xdch47** [comment]
1.7.2 has been released

**Comment by xdch47** [comment]
Could be considered as obsolete - ongoing #10961

**Pull request closed without merging**
