### PR TITLE
dev-util/bitrise: bump version 1.21.0

### PR DESCRIPTION
**Pull request by koral--**

### CODE REVIEW

**Comment by mgorny** [comment]
Depends on #9626, I presume.

**Comment by mgorny** [comment]
```
>>> Test phase: dev-util/stepman-0.10.2
env GOPATH=/tmp/portage/dev-util/stepman-0.10.2/work/stepman-0.10.2:/usr/lib/go-gentoo go test -v -work -x github.com/bitrise-io/stepman
can't load package: package github.com/bitrise-io/stepman: cannot find package "github.com/bitrise-io/stepman" in any of:
	/usr/lib/go/src/github.com/bitrise-io/stepman (from $GOROOT)
	/tmp/portage/dev-util/stepman-0.10.2/work/stepman-0.10.2/src/github.com/bitrise-io/stepman (from $GOPATH)
	/usr/lib/go-gentoo/src/github.com/bitrise-io/stepman
 * ERROR: dev-util/stepman-0.10.2::gentoo failed (test phase):
```

Could you please fix the dependency?

**Comment by koral--** [comment]
That dependency is in another PR: #9625

**Comment by mgorny** [comment]
It apparently has been merged without proper testing, for which I'm really sorry about.

Also, in the future you can combine related bumps in a single pull request, as long as they are separate commits. This will keep reviews more focused and CI more happy.

**Comment by koral--** [comment]
OK, good to know. I'll combine them in the future.

**Comment by koral--** [comment]
@mgorny next version is in #10137 should I close this PR?

**Comment by mgorny** [comment]
Sure.

**Pull request closed without merging**
