### PR TITLE
media-sound/teamspeak-client: block against qt-5.12

### PR DESCRIPTION
**Pull request by ConiKost**
Current version of the teamspeak client is not compatible with Qt 5.12.

Closes: https://bugs.gentoo.org/675874
Package-Manager: Portage-2.3.60, Repoman-2.3.12
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by juippis** [comment]
You should revbump this.

**Comment by ConiKost** [comment]
> You should revbump this.
Why do you think so? Since a revbump would force all users for a rebuild, which would currently change nothing, as Qt 5.12 is currently not in portage?

**Comment by juippis** [comment]
Yes, it also updates the condition so people won't have broken teamspeak once qt-5.12 does hit portage. I thought that was your purpose in here? 

Also, doesn't devmanual say to revbump when updating RDEPEND entries?

**Comment by ConiKost** [comment]
> Yes, it also updates the condition so people won't have broken teamspeak once qt-5.12 does hit portage. I thought that was your purpose in here?

Yes, this is correct.

> Also, doesn't devmanual say to revbump when updating RDEPEND entries?
I guess so, anyway, added.

**Comment by a17r** [comment]
The bug should stay open until this is either fixed by upstream or another solution found for the package. Even if some time ahead from now, Qt-5.11 is EOL upstream and will not be in tree forever.

**Comment by ConiKost** [comment]
> The bug should stay open until this is either fixed by upstream or another solution found for the package.
> Even if some time ahead from now, Qt-5.11 is EOL upstream and will not be in tree forever.

I guess, we don't want qt 5.6, which is shipped by default? So currently, the only solution would be removal in terms for qt 5.12.. Unfortunately, even Teamspeak GmbH didn't replied until today to my open ticket.

**Comment by a17r** [comment]
Going forward, if we bundled major deps then there is not much left of packaging for teamspeak-bin, except lending people a hand for a handful of minor deps. Then they may as well just download it from their website, as teamspeak upstream obviously prefers.

**Pull request closed without merging**
