### PR TITLE
dev-php/composer: bump to 1.5.2

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.13, Repoman-2.3.4

### CODE REVIEW

**Comment by hydrapolic** [comment]
@GuillaumeSeren

**Comment by GuillaumeSeren** [comment]
Hey @hydrapolic ,
I have checked the dependencies list on packagist (https://packagist.org/packages/composer/composer),
and I think you should also bump to >=dev-php/json-schema-3.0.0. 🚀

**Comment by orlitzky** [comment]
Pulled with Guillaume's suggestion, thanks!

**Comment by hydrapolic** [comment]
Thanks guys!

**Pull request closed without merging**
