### PR TITLE
gnome-extra/chrome-gnome-shell: version bump

### PR DESCRIPTION
**Pull request by nE0sIghT**
https://mail.gnome.org/archives/ftp-release-list/2016-May/msg00067.html
https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome/ReleaseNotes/6

### CODE REVIEW

**Comment by idella** [comment]
I find this:

`+RDEPEND="dev-lang/python `

very loose. Python in gentoo currently actively supports py2.7 3.3 3.4 3.5
this juyt lists python and for any python related ebuild it is fundamental to ascertain which pythons are supported. I prompt you to inherit a python eclass, escertain just which pythons are supported and set them in PYTHON_COMPAT accordingly. 

I would not have added it in the form in which it was added. I therefore suggest you edit this bumped ebuild and delete the initial in that loose form.

**Comment by nE0sIghT** [comment]
Pushed new ebuild with python-single-r1 eclass

**Comment by idella** [comment]
Fine it is mn here I shall look and runtest tomorrow

**Comment by nE0sIghT** [comment]
> Do a check but python-single-r1 requires addition of pkg_setup with python_pkg_setup so as to ensure the correct selection of the system python

It should be executed as I see without explicit call

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
python_setup is src_configure see to the action of the python_pkg_setup now.

The line of DESCRIPTION= comes in at 92 chars.  The text of the DESCRIPTION need comes in at 79 chars. This is right on the border so I suppose it can stay. It is an arbitrary limit, set for anticipated convenience of any viewer viewing.

DEPEND="" being empty can be taken out however it is quite optional. It can stay.

`KEYWORDS="~amd64 ~arm ~x86"`
Oh. This says that on its addition, you had runtested on all three arches.

On my part, I accept "~amd64 ~x86" given the precedent and history of x86 being a 'cutdown' or pre-cursor to amd64.
@arm on the other hand. This appears to me it slipped through unnoticed by the dev who added it.
What i would anticipate is keywords set to "~amd64 ~x86", then formerly request the adtion of arm via a 'keyword request' bug. If you DID test on arm just say so and cite the make model of the motherboard here.

`python_fix_shebang "${S}"/connector`
this is another non critical entry that is better corrected.  
the $PWD at the point of `src_configure() {` is already  "${S}". so the "${S}"

The ebuild as such is functional. It just needs these tidying.

**Comment by nE0sIghT** [comment]
> the $PWD at the point of src_configure() { is already "${S}". so the "${S}" in redundant

Is usage of absolute paths is not prefered?
If for some reason someone will use "cd" in ebuild - no changes will be needed.

**Comment by idella** [comment]
No it's not

**Comment by nE0sIghT** [comment]
Oh I forgot about out of source builds, my bad.

**Comment by nE0sIghT** [comment]
Dropped ~arm keyword
Removed empty DEPEND
Removed python_setup
Removed ${S}

**Comment by idella** [comment]
My intention was for you to leave python_setup , however it is not required.

**Comment by nE0sIghT** [comment]
@idella 
> else make a std. keyword request bug to the team.

I will fill the bug request.

Thanks for review!

**Pull request closed without merging**
