### PR TITLE
media-video/obs-studio: Version bump to 0.15.0.

### PR DESCRIPTION
**Pull request by Chiitoo**
Add ebuild for the 0.15.0 release.

Linux-Specific ([Upstream] (https://github.com/jp9000/obs-studio/releases/tag/0.15.0)) Changes:

- Fixed the long-standing crashes with linux window capture
- Fixed a bug where window capture would not display window titles with the right text encoding

### CODE REVIEW

**Comment by monsieurp** [comment]
:+1:

**Comment by Chiitoo** [comment]
Hrm.  There's already a [0.15.1 “hotfix” release] (https://github.com/jp9000/obs-studio/releases/tag/0.15.1) out.

Would it be best to edit this request to be for 0.15.1, or make a new one for that later?  The latter feels like it might be at least a bit redundant.  :]

**Comment by monsieurp** [comment]
You can close this PR and file a new one for 0.15.1, that works as well.

**Comment by Chiitoo** [comment]
Okies.

I think I'll do just that.  At this time I don't know of a reason to have 0.15.0 in tree as well, so I I'll skip that one.  I am planning on keeping old versions around for a while, just in case regression happens, but will eventually clean them out.

Thanks!

**Pull request closed without merging**
