### PR TITLE
app-emulation/looking-glass: new ebuild

### PR DESCRIPTION
**Pull request by SpiderX**
Application that allows the use of a KVM (Kernel-based Virtual Machine)
configured for VGA PCI Pass-through without an attached physical monitor,
keyboard or mouse. This is the final step required to move away from dual
booting with other operating systems for legacy programs that
require high performance graphics.

Signed-off-by: Vladimir Pavljuchenkov <spiderx@spiderx.dp.ua>
Package-Manager: Portage-2.3.49, Repoman-2.3.11

### CODE REVIEW

**Comment by dracwyrm** [comment]
I was going to make an ebuild for this when a12 was released because it's using CMake, and I thought it wasn't going to be too much longer until it was released (that was back in August XD). Anyways, I was trying to get help with a bug and the dev made it very obvious to me that he did not want this to be in distro repositories yet because it was very early alpha stuff (https://github.com/gnif/LookingGlass/issues/93#issuecomment-414091385)

I'll have a look at your ebuilds as I actually want to use this software. However, I believe the correct version number should be 0_alpha11 as we don't know what the first non-alpha version will be.

**Comment by gyakovlev** [comment]
I may have a setup to test this, but looks upstream does not want this in repos as @dracwyrm pointed out. Don't get me wrong, we want this in repos, but after it's at least beta or upstream gives green light on packaging it.
quickly checking repology it seems only AUR has it (which is similar to overlay in gentoo world)
https://repology.org/metapackage/looking-glass/versions
I suggest putting this into overlay for now, but please submit it as soon as it's out of alpha.

**Comment by SpiderX** [comment]
What a point to have it in overlay and not to have it in portage?
I am already keeping it in an overlay for 10 months.
From the point of software - it works, from the point of portage - ebuild does it job (no build issues, no QA issues, no issues).

I am fine with keeping this in overlay. Just curious.

**Comment by gyakovlev** [comment]
It's all about upstream stance.
ask upstream to give it a go and If approved I'm ok with merging it.
I'm just guessing, but it seems @gnif does not want it to get into hands of non-power users right now and I respect that.
just as an example, sway ( i3-compatible wayland window manager) is in the same situation right now. upstream asked not to package it until it's ready.

**Comment by SpiderX** [comment]
> It's all about upstream stance.

Noted. Thanks.

**Comment by gnif** [comment]
Thank you for respecting my position on this. A12 is pending release, when it is it will very likely be the last Alpha build.

**Pull request closed without merging**
