### PR TITLE
dev-cpp/folly: simple version bump

### PR DESCRIPTION
**Pull request by listout**
Signed-off-by: brahmajit das <listout@protonmail.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
I couldn't actually build this when I tried the other day, I hit https://bugs.gentoo.org/833583. There's a patch we can try now though.

**Comment by thesamesam** [comment]
I've just pushed https://github.com/gentoo/gentoo/pull/26807 so please rebase too.

**Comment by listout** [comment]
> I couldn't actually build this when I tried the other day, I hit [facebook/folly#1823](https://github.com/facebook/folly/issues/1823). There's a patch we can try now though.

Same for me. Cant build it. It's some example code that causing the trouble

**Comment by thesamesam** [comment]
> 

Why'd you do a PR for it without mentioning the issue then? 👀 

Anyway, try the patch upstream committed.

**Comment by listout** [comment]
> Why'd you do a PR for it without mentioning the issue then? eyes

My bad, I made a PR before testing it myself


> Anyway, try the patch upstream committed? Does it help?

Trying it.

**Comment by listout** [comment]
@thesamesam which patch are you referring to? This one -> https://github.com/facebook/folly/commit/437b29dd062a40c741b2147827025a2f413b76c7

**Comment by listout** [comment]
@thesamesam The following patch seems to fix the issue for me, can you try? also that issue was for really old verison, the code in that particular file has changed

```diff
diff --git a/folly/detail/base64_detail/Base64Api.cpp b/folly/detail/base64_detail/Base64Api.cpp
index 9c8493c..1d578ea 100644
--- a/folly/detail/base64_detail/Base64Api.cpp
+++ b/folly/detail/base64_detail/Base64Api.cpp
@@ -22,7 +22,7 @@
 
 namespace folly::detail::base64_detail {
 Base64RuntimeImpl base64EncodeSelectImplementation() {
-#if FOLLY_SSE_PREREQ(4, 2)
+#if FOLLY_x64 && FOLLY_SSE_PREREQ(4, 2)
   if (folly::CpuId().sse42()) {
     return {
         base64Encode_SSE4_2,
```

**Comment by thesamesam** [comment]
> @thesamesam which patch are you referring to? This one -> [facebook/folly@437b29d](https://github.com/facebook/folly/commit/437b29dd062a40c741b2147827025a2f413b76c7)

I was thinking of https://github.com/facebook/folly/commit/10fc2e449038d9ffda5cd53999edb9875c4cb151 -- that patch you linked should already be in this tag.

Let me try your patch now...

**Comment by listout** [comment]
@thesamesam my patch seems to be more of a hack than an actual fix. I'll add in the patch you linked. Do I create a sep. PR or add a commit to this one?

**Comment by listout** [comment]
@thesamesam how about now?

**Comment by thesamesam** [comment]
Latest state of this PR works for me (please add link in the patch though).

We should try upstreaming the musl patch too, but that's not a blocker for merging this. Yay!

**Comment by listout** [comment]
Done and squashed commits. I've kept the format of the original patch while adding the link to the undefined reference issue.

**Comment by thesamesam** [comment]
Bleh, tests fail to build for me:
```
/var/tmp/portage/dev-cpp/folly-2022.08.08.00/work/folly/lang/Hint-inl.h:109:3: warning: ‘asm’ operand 1 probably does not match constraints
  109 |   asm volatile("" : "+r"(t));
      |   ^~~
/var/tmp/portage/dev-cpp/folly-2022.08.08.00/work/folly/lang/Hint-inl.h:109:3: error: impossible constraint in ‘asm’
At global scope:
```

**Pull request closed without merging**
