### PR TITLE
net-im/skypeforlinux: Version bump to 5.5.0.1

### PR DESCRIPTION
**Pull request by karolgrudzinski**
- Bump to 5.5.0.1
- Remove ebuild for unfetchable version 5.3.0.1

Package-Manager: Portage-2.3.10, Repoman-2.3.3

### CODE REVIEW

**Comment by monsieurp** [comment]
@karolgrudzinski it's no big deal since it's just a QA Notice. Please file another PR if you find the root of this problem. Thanks!

**Comment by leio** [comment]
There's also this:

 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /opt/skypeforlinux/libnode.so

Of course this is expected, but I believe there's a way to squelch this for binary packages

**Comment by shentino** [comment]
I'd be interested in knowing.  Where would I need to listen to learn how to do the binary squelch?

**Comment by karolgrudzinski** [comment]
@leio I don't know where did you get this message from. I can't see this. I can only see warning mentioned by @monsieurp 

    # emerge -1v skypeforlinux 

    --- CUT HERE ---

    * skypeforlinux_5.5.0.1-1.x86_64.rpm SHA256 SHA512 WHIRLPOOL size ;-) ... [ ok ]
    >>> Unpacking source...
    >>> Unpacking skypeforlinux_5.5.0.1-1.x86_64.rpm to /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/work
    >>> Source unpacked in /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/work
    >>> Preparing source in /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/work ...
    >>> Source prepared.
    >>> Configuring source in /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/work ...
    >>> Source configured.
    >>> Compiling source in /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/work ...
    >>> Source compiled.
    >>> Test phase [not enabled]: net-im/skypeforlinux-5.5.0.1

    >>> Install skypeforlinux-5.5.0.1 into /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/image/ category net-im
    >>> Completed installing skypeforlinux-5.5.0.1 into /var/tmp/portage/net-im/skypeforlinux-5.5.0.1/image/

    * Final size of build directory: 170760 KiB (166.7 MiB)
    * Final size of installed tree:  167464 KiB (163.5 MiB)

    * QA Notice: This package installs one or more .desktop files that do not
    * pass validation.
    * 
    *      /usr/share/applications/skypeforlinux.desktop: warning: key "OnlyShowIn" in group "Desktop Action QuitSkype" is deprecated
    * 
    ecompressdir: bzip2 -9 /usr/share/doc

    >>> Installing (1 of 1) net-im/skypeforlinux-5.5.0.1::gentoo
    * checking 80 files for package collisions
    >>> Merging net-im/skypeforlinux-5.5.0.1 to /
    --- /opt/
    --- /opt/skypeforlinux/

    --- CUT HERE ---

    >>> /usr/share/icons/hicolor/512x512/apps/skypeforlinux.png
    --- /usr/share/applications/
    >>> /usr/share/applications/skypeforlinux.desktop
    >>> Safely unmerging already-installed instance...
    No package files given... Grabbing a set.
    --- replaced obj /usr/share/pixmaps/skypeforlinux.png
    --- replaced dir /usr/share/pixmaps

    --- CUT HERE ---

    --- replaced obj /opt/bin/skypeforlinux
    --- replaced dir /opt/bin
    --- replaced dir /opt
    * Updating .desktop files database ...                                  [ ok ]
    * Updating shared mime info database ...                                [ ok ]
    >>> Regenerating /etc/ld.so.cache...
    >>> Original instance of package unmerged safely.
    * Updating .desktop files database ...                                  [ ok ]
    * Updating shared mime info database ...                                [ ok ]
    >>> net-im/skypeforlinux-5.5.0.1 merged.
    >>> Auto-cleaning packages...

    >>> No outdated packages were found on your system.

    * GNU info directory index is up-to-date.

**Comment by karolgrudzinski** [comment]
After some googling I discovered that these warnings are a result of portage running desktop-file-validate on skypeonlinux.desktop file. I checked official desktop file spec [1] and it looks that only first of two warnings is correct.

> $ desktop-file-validate /usr/share/applications/skypeforlinux.desktop 
> /usr/share/applications/skypeforlinux.desktop: warning: key "Encoding" in group "Desktop Entry" is deprecated
> /usr/share/applications/skypeforlinux.desktop: warning: key "OnlyShowIn" in group "Desktop Action QuitSkype" is deprecated

"Encoding" is listed as deprecated in spec, "OnlyShowIn" is not. It is bug in desktop-file-validate tool or I'm missing something.

[1] https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html

**Pull request closed without merging**
