### PR TITLE
app-crypt/swtpm: Re-add gnutls for swtpm_cert

### PR DESCRIPTION
**Pull request by salahcoronya**
A long time ago, swtpm used a series a shell scripts to build the certificates and key which required gnutls with the "tools" and "pkcs11" flags. It no longer requires these. But the swtpm_cert still requires gnutls (as a binary). Unconditionally depends on net-libs/gnutls, as gnutls is de-facto part of the "system" set via app-crypt/gnupg[ssl]  which sys-apps/portage[rsync-verify] depends on, which the default.

### CODE REVIEW

**Comment by salahcoronya** [comment]
Actually, the above turns out not to be true -  swtpm_cert exec's certtool . It also has PKCS11 support (optional). The tests need it but swtpm_cert will run without it. So I need to rethink this.

**Comment by salahcoronya** [comment]
Well, the situation is this: libvirt needs app-crypt/swtpm[gnutls] to provision the TPM for each VM (and the create the CAQ as well, if it doesn't already exist) . So as for now, swtpm is broken wrt app-emulation/libvirt[qemu]. 

So there's 2 ways to do this:

1. Make net-libs/gnutls[pkcs11,tools] unconditional.
2. Add a "gnutls" use flag to app-crypt/swtpm and have app-emulation/libvirt[qemu] RDEPEND on app-crypt/swtpm[gnutls]. 

There's really no way to avoid needed USE flags for net-libs/gnutls - "tools" is required;  and "-pkcs11" is not supported by upstream. They expect net-libs/gnutls to be compiled with PKCS11 support.

**Comment by salahcoronya** [comment]
The "gnutls" USE flag was restored in https://gitweb.gentoo.org/repo/gentoo.git/commit/app-crypt/swtpm?id=e470d198cc9fe863a54e392fb7e8bf963b5be5e9 so I'm going to close this PR and open a new one to fix the reverse dependencies.

**Comment by tamiko** [comment]
@salahcoronya Excellent. Thank you! I am sorry that I missed this PR.

**Comment by tamiko** [comment]
@salahcoronya I will apply this pull request retroactively. Thanks!

**Pull request closed without merging**
