### PR TITLE
gui-wm/hyprland: add 0.46.2

### PR DESCRIPTION
**Pull request by MrRoy**
Hypr* version bumps

Two new packages:
dev-libs/hyprgraphics
gui-libs/hyprland-qtutils

Added some missing RDEPENDS to gui-wm/hyprland reported by qa-vdb
git diff --no-index hyprland-0.45.2.ebuild hyprland-0.46.2.ebuild
```
diff --git a/hyprland-0.45.2.ebuild b/hyprland-0.46.2.ebuild
index 43fde5978f27..6b827f24debf 100644
--- a/hyprland-0.45.2.ebuild
+++ b/hyprland-0.46.2.ebuild
@@ -35,12 +35,19 @@ RDEPEND="
        ${HYPRPM_RDEPEND}
        dev-cpp/tomlplusplus
        dev-libs/glib:2
-       dev-libs/libinput
+       dev-libs/hyprlang
+       dev-libs/libinput:=
+       dev-libs/hyprgraphics:=
+       dev-libs/re2:=
        >=dev-libs/udis86-1.7.2
        >=dev-libs/wayland-1.22.90
        >=gui-libs/aquamarine-0.4.2
        >=gui-libs/hyprcursor-0.1.9
+       gui-libs/hyprutils:=
+       gui-libs/hyprland-qtutils
        media-libs/libglvnd
+       media-libs/mesa
+       sys-apps/util-linux
        x11-libs/cairo
        x11-libs/libdrm
        x11-libs/libxkbcommon
@@ -57,9 +64,7 @@ RDEPEND="
 DEPEND="
        ${RDEPEND}
        >=dev-libs/hyprland-protocols-0.4
-       >=dev-libs/hyprlang-0.3.2
        >=dev-libs/wayland-protocols-1.36
-       >=gui-libs/hyprutils-0.2.3
 "
 BDEPEND="
        || ( >=sys-devel/gcc-14:* >=llvm-core/clang-18:* )
```

CC: @dlan17 

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by JohnMH** [comment]
Hah, had just bumped in my local tree last night. Was going to push when I woke up. Nice.

**Comment by dlan17** [comment]
@MrRoy thanks pushed, btw, you could consider to stable new one & drop some old versions..

**Comment by brettalcox** [comment]
@MrRoy hyprland technically doesn't require hyprland-qtutils (and the visual warning for it not being installed can be disabled by setting `disable_hyprland_qtutils_check` in hyprland.conf -- see [here](https://wiki.hyprland.org/Configuring/Variables/#misc).

Might be worth throwing behind a USE flag? Reason I suggest this is pulling that dep in also pulls in 12 KDE dependencies which is not ideal, especially for people who are trying to keep their system devoid of KDE deps (if possible)

**Comment by MrRoy** [comment]
@brettalcox I had thought about it, but I disliked the idea that by default most people will get the warning OOTB

Also the devmanual says not to put dependencies behind USE flags if all the USE flag does is pull dependencies; so it would have to be behind a optfeature where people have to explicitly register hyprland-qtutils in their world file to avoid that warning.

I'm not sure what's the best way to handle this, I will ask in #gentoo-dev-help

**Comment by MrRoy** [comment]
@brettalcox after discussion with sam, this situation permits the dependencies to be put behind a USE flag so I will open a PR later today for this.

**Pull request closed without merging**
