### PR TITLE
 dev-libs/spdlog: bump to 0.16.2

### PR DESCRIPTION
**Pull request by stkw0**

### CODE REVIEW

**Comment by candrews** [comment]
`spdlog` bundles `libfmt` - this is bad idea: https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies

Can you please unbundle `libfmt` and instead depend on `dev-libs/libfmt`? Upstream should be asked to do the same.

**Comment by stkw0** [comment]
I have added a system-fmt USE that patch the source code excluding the bundled version from the installation and removes SPDLOG_FMT_EXTERNAL option (thus, breaking compatibility, so it's not enabled by default).

**Comment by candrews** [comment]
How does it break compatibility?

**Comment by stkw0** [comment]
With that patch users who were not using SPDLOG_FMT_EXTERNAL must modify their build system to link against libfmt (which wasn't needed by default).

**Comment by candrews** [comment]
Requested upstream to not bundle libfmt: https://github.com/gabime/spdlog/issues/600

**Comment by stkw0** [comment]
@candrews I already try it (to move the SPDLOG_FMT_EXTERNAL to a compile time option, which is less problematic) but the maintainer of spdlog wanted to maintain the SPDLOG_FMT_EXTERNAL for compatibility, in that case the only option that I see is to fix it downstream

**Comment by candrews** [comment]
> I have added a system-fmt USE that patch the source code excluding the bundled version from the installation and removes SPDLOG_FMT_EXTERNAL option (thus, breaking compatibility, so it's not enabled by default).

Are you sure it breaks compatibility? What are you using to test this?

**Comment by stkw0** [comment]
@candrews For example the next code

**Comment by stkw0** [comment]
@candrews For example the next code 
```cpp
#include <spdlog/spdlog.h>
int main() {}
```
it will compile as normal (ie: `g++ example.cpp`). If we force to unconditionally use system libfmt, we will need to link against fmt library or obviously we will get undefined references. 

If we enable it by default I see the next problems:

**Comment by SoapGentoo** [comment]
* Why does it matter whether `SPDLOG_FMT_EXTERNAL` works? We build stuff without bundling and will change build systems if necessary to do so, and this rule isn't really optional: https://wiki.gentoo.org/wiki/Why_not_bundle_dependencies
* What reason is there to believe that users' code will stop working? The burden of proof is on the bundled lib, we unbundle unless proven beyond reasonable doubt that things might break
* Binary sizes will not be increased an iota, because libfmt uses shared libraries, and object code will not be included in the library (http://www.portagefilelist.de/site/query/listPackageFiles/?category=dev-libs&package=libfmt&version=4.1.0&do#result)

This will not be merged unless libfmt is unbundled or you have conclusively proven that the bundled lib is somehow necessary and is a total fork.

**Comment by candrews** [comment]
In my opinion, we shouldn't even have a use flag. We should always unbundle.

**Comment by stkw0** [comment]
@candrews I removed the use flag now.

**Comment by SoapGentoo** [comment]
@stkw0 go through the tree, you'll see tons of examples where we unbundle boost, zlib and friends, and they all run happily.

**Comment by candrews** [comment]
If you change from using `epatch` to `PATCHES` which will then allow you to not have to override `src_prepare` that'll do it, and I'll merge this.

Thanks for working though the issues.

Out of curiosity, what are you using spdlog for? If you're using something not (yet) in Gentoo, feel free to submit a PR adding it.

**Comment by stkw0** [comment]
@SoapGentoo I'm not against the norm of unbundle libraries (if they are bundled). But if it's not totally transparent for the user I don't like to do it by default, but if the norm in Gentoo is to always remove bundled dependencies by default, I obviously will do it (and I already did it and I hope that if there aren't further issues it can be merged). For a think like this I think we wasted more effort than needed (in part caused because my English level is somewhat limited) .

--

@candrews Just now I saw your message. Thanks for the tip about the patches, will do it now. I use spdlog on a personal project and  also in a work project and I didn't like it to bundle spdlog inside those projects, for this reason I wanted to maintain this library. If I see something popular that I want to use and is not in Gentoo in general I try to create an ebuild for it (and learning about Gentoo along the way) like #6510 PR.

Thank you both.

**Comment by candrews** [comment]
I noticed that you didn't also update the -9999 ebuild, so I did that.
And you didn't clean up all the old versions as I believe was your intent, so I did that, too.

6fa73c3cf9ca1a0ee739797af332cea10e6ae485
af55a5c796ec9dee9334f17e8e8b6c64eeef4672

**Pull request closed without merging**
