### PR TITLE
dev-libs/rocm-opencl-runtime: removed two spaces, opencl is working …

### PR DESCRIPTION
**Pull request by justxi**
…again

Package-Manager: Portage-2.3.69, Repoman-2.3.16

### CODE REVIEW

**Comment by candrews** [comment]
Unfortunately, I'm still seeing clinfo showing "Number of Devices 0"
```
$ clinfo 
Number of platforms                               1
  Platform Name                                   AMD Accelerated Parallel Processing
  Platform Vendor                                 Advanced Micro Devices, Inc.
  Platform Version                                OpenCL 2.0 AMD-APP.internal (2949.0)
  Platform Profile                                FULL_PROFILE
  Platform Extensions                             cl_khr_icd cl_amd_object_metadata cl_amd_event_callback 
  Platform Max metadata object keys (AMD)         8
  Platform Extensions function suffix             AMD

  Platform Name                                   AMD Accelerated Parallel Processing
Number of devices                                 0

NULL platform behavior
  clGetPlatformInfo(NULL, CL_PLATFORM_NAME, ...)  AMD Accelerated Parallel Processing
  clGetDeviceIDs(NULL, CL_DEVICE_TYPE_ALL, ...)   
  clCreateContext(NULL, ...) [default]            No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_DEFAULT)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_GPU)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ACCELERATOR)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_CUSTOM)  No devices found in platform
  clCreateContextFromType(NULL, CL_DEVICE_TYPE_ALL)  No devices found in platform

ICD loader properties
  ICD loader Name                                 OpenCL ICD Loader
  ICD loader Vendor                               OCL Icd free software
  ICD loader Version                              2.2.12
  ICD loader Profile                              OpenCL 2.2
```

**Comment by justxi** [comment]
Ok, then there must be a second problem somewhere inbetween.
I installed unstable (*9999) ebuilds of rocm-comgr, rocm-device-libs and llvm-roc. 
This combination works. I will revert them to see which one makes the problem.
But when I insert the two spaces again, there come two errors in clinfo, which I found with an "strace clinfo".

**Comment by justxi** [comment]
I confirm, this is not the only reason why clinfo do not show any devices.
I have added COMMIT IDs to all of my unstable ebuilds and with this state there is no progress.

**Comment by justxi** [comment]
I think this out dated, isn't it?

**Pull request closed without merging**
