### PR TITLE
eapi6cleanup

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by chewi** [comment]
Fine for the games. I don't know why we even have all those old versions.

**Comment by robbat2** [comment]
app-arch/bzip2: @gentoo/base-system - APPROVED
dev-util/dialog: @gentoo/base-system - APPROVED
sys-apps/sg3_utils: @gentoo/base-system - APPROVED

**Comment by floppym** [comment]
sys-fs/udev: @gentoo/udev - APPROVED

**Comment by a17r** [comment]
Thanks everyone!

**Pull request merged**
