### PR TITLE
app-text/cherrytree: fix sandbox issue

### PR DESCRIPTION
**Pull request by rindeal**
Gentoo-Bug: 580190

@gentoo/proxy-maint

### CODE REVIEW

**Comment by idella** [comment]
This was missed on the initial review because python-r1s are not easy
https://wiki.gentoo.org/wiki/Project:Python/python-single-r1#PYTHON_REQUIRED_USE
KEYWORDS='~amd64', normally has ~x86 as well but it is not obligatory.

```bash
~/github/gentoo/app-text/cherrytree $ ebuild cherrytree-0.36.9.ebuild clean install
```

does indeed install.

**Comment by rindeal** [comment]
I will add `~x86` in the next PR.

I've already done the migration to `distutils-r1.eclass` - https://github.com/rindeal/gentoo/blob/cherrytree-update2/app-text/cherrytree/cherrytree-0.36.9.ebuild. It's just waiting on this PR.

This package supports only python 2, that's for sure.

**Comment by idella** [comment]
It is easier to over-write the patch with the conversion to distutils-r1, I think.
The cherrytree-0.36.9.ebuild having python-single-r1 meeds to be rest or edited to match it correctly.  A switch to the other eclass would warrant a revbump.

**Comment by rindeal** [comment]
Ok, that makes sense, so I'll close this PR and open a new one with everything included.

**Pull request closed without merging**
