### PR TITLE
sys-apps/biosdisk: version bump to 20171116 git commit.

### PR DESCRIPTION
**Pull request by logistiker**
Bumped to most recent git commit by date.  Changed the repo to github since it no longer exists on dell.com and fixed bug 619968.

### CODE REVIEW

**Comment by candrews** [comment]
Can you please separate the new version and the removal of the old version into 2 commits?

**Comment by logistiker** [comment]
Done.

**Comment by candrews** [comment]
Can you clean up each of the commits' messages?
* You don't need to mention the bug number in the summary line
* Since you're closing the bug, use "Closes:" instead of "Bug:" (see https://www.gentoo.org/glep/glep-0066.html#commit-messages )
* The commit with summary "Removed old 20100611 version since it no longer works" - what do you mean it doesn't work? Also, the commit message references a bug that doesn't seem related to the commit
* should have `|| die` after `gunzip` to catch failures

**Comment by logistiker** [comment]
I realize the bug only mentions the doman problem but it's pointless to just fix that and push it if the SRC_URI doesn't work anymore.  I rewrote the ebuild so it works with github and incorporates additional files in the newer version.  As a result, I bumped the version and removed the old one.

**Pull request closed without merging**
