### PR TITLE
net-p2p/syncthing: bump to 0.14.0

### PR DESCRIPTION
**Pull request by sbraz**
@djc Here is the new major release, this fixes https://bugs.gentoo.org/589236
@khumarahn Can you test relaysrv? I don't really use it. 

I replaced the patch with a call to sed since the file moved and the change is quite trivial.

### CODE REVIEW

**Comment by khumarahn** [comment]
Hi, `relaysrv` needs changes. Upstream changed binary name, user and group. I submitted a PR to your repo https://github.com/sbraz/gentoo/pull/1

**Comment by sbraz** [comment]
So we would end up with two users for people who already installed the package? Seems a bit ugly, don't you think?

**Comment by khumarahn** [comment]
Yeah, I thought about it. I really dislike upstream changes. But there are a couple of arguments in support of staying close to upstream:
* We introduced `tools` use flag very recently, and probably there aren't many people who used it; my estimate is that there is only one gentoo user who runs syncthing relay server, and it is me. There are only 100 public relays worldwide, and most of them have been running for a long time, so I should not be too far off.
* It is nice to stay close to the upstream (easier to manage the package, less chance to make a mistake). Especially if changes do not yet affect many users. Especially while the package is young and quickly changes.

**Comment by sbraz** [comment]
I think it's prudent to wait for a second opinion :)

**Comment by khumarahn** [comment]
I am sure my suggested commit will be reviewed by a couple of people. Also I am not a maintainer of syncthing to make any decisions.

**Comment by sbraz** [comment]
Re-pushed with a fix for https://bugs.gentoo.org/show_bug.cgi?id=589504
I think it might be a good idea to handle the relaysrv issue in a subsequent PR.

**Comment by khumarahn** [comment]
Hmmm. Now in the tree relaysrv service files are broken for both systemd and openrc. I mean, it simply would not start because binary and user/group have changed.

**Comment by sbraz** [comment]
Right, sorry :/ I just saw a lot of people complaining on the bug and wanted to bump the programme ASAP. Can you make a PR with the correct fixes?

**Pull request closed without merging**
