### PR TITLE
Don't pass -Wl,--undefined-version on clang macos prefix

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by chewi** [comment]
Fine by me for rhash. @thesamesam added this part of the code to rhash anyway, so I don't have strong opinions about it. I only note that it says the flag is also needed for mold, but I use mold system-wide and haven't seen this issue.

**Comment by thesamesam** [comment]
IIRC mold wound back the default change but I'd have to check.

**Comment by orbea** [comment]
On osx you should be able to use `-Wl,-undefined,error`, maybe that works here too?

**Comment by DarthGandalf** [comment]
@thesamesam I was going to update this PR today to pass the flag via `test-flags-CCLD`, but looks like you did it yesterday :D

**Pull request closed without merging**
