### PR TITLE
sci-geosciences/gpsbabel: 1.7.0 version bump, EAPI 7 (no GUI)

### PR DESCRIPTION
**Pull request by cjmayo**
GUI support is dropped because of multiple issues with resource paths.

Closes: https://bugs.gentoo.org/689586
Package-Manager: Portage-2.3.79, Repoman-2.3.16
Signed-off-by: Chris Mayo <aklhfex@gmail.com>

```diff
--- gpsbabel-1.5.4-r1.ebuild
+++ gpsbabel-1.6.0.ebuild
@@ -1,98 +1,69 @@
-# Copyright 1999-2017 Gentoo Foundation
+# Copyright 1999-2020 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
 
-inherit autotools eutils qmake-utils
+inherit qmake-utils
+
+MY_PV="${PV//./_}"
+MY_P="${PN}_${MY_PV}"
 
 DESCRIPTION="GPS waypoints, tracks and routes converter"
 HOMEPAGE="https://www.gpsbabel.org/ https://github.com/gpsbabel/gpsbabel"
 SRC_URI="
-	https://dev.gentoo.org/~asturm/${P}.tar.gz
+	https://github.com/${PN}/${PN}/archive/${MY_P}.tar.gz
 	doc? ( https://www.gpsbabel.org/style3.css -> gpsbabel.org-style3.css )"
+
 LICENSE="GPL-2"
+SLOT="0"
+KEYWORDS="~amd64 ~ppc ~x86"
+IUSE="doc"
+RESTRICT="test" # bug 421699
 
-SLOT="0"
-KEYWORDS="amd64 ~ppc x86"
-IUSE="doc +gui"
-
-RDEPEND="
+DEPEND="
 	dev-libs/expat
 	dev-qt/qtcore:5
 	sci-libs/shapelib:=
-	sys-libs/zlib[minizip]
+	sys-libs/zlib
 	virtual/libusb:0
-	gui? (
-		dev-qt/qtgui:5
-		dev-qt/qtnetwork:5
-		dev-qt/qtwebchannel:5
-		dev-qt/qtwebengine:5[widgets]
-		dev-qt/qtwidgets:5
-		dev-qt/qtxml:5
-	)
 "
-DEPEND="${RDEPEND}
+BDEPEND="
+	virtual/pkgconfig
 	doc? (
 		app-text/docbook-xml-dtd:4.1.2
 		dev-lang/perl
 		dev-libs/libxslt
 	)
-	gui? ( dev-qt/linguist-tools:5 )
 "
-
-DOCS=( AUTHORS README.{contrib,igc,mapconverter,md,xmapwpt} )
+RDEPEND="${DEPEND}"
 
 PATCHES=(
-	"${FILESDIR}"/${PN}-1.4.3-fix_binary_name.patch
-	"${FILESDIR}"/${P}-disable_statistic_uploading.patch
-	"${FILESDIR}"/${P}-disable_update_check.patch
-	"${FILESDIR}"/${P}-disable_version_check.patch
+	"${FILESDIR}"/${PN}-1.5.4-xmldoc.patch
 	"${FILESDIR}"/${P}-use_system_shapelib.patch
-	"${FILESDIR}"/${P}-use_system_zlib.patch
-	"${FILESDIR}"/${P}-xmldoc.patch
-	"${FILESDIR}"/${P}-qt-5.9-{1,2}.patch
 )
 
-RESTRICT="test" # bug 421699
+S="${WORKDIR}/${PN}-${MY_P}"
 
 src_prepare() {
 	default
 
-	# remove bundled libs and cleanup
+	# ensure bundled libs are not used
 	rm -r shapelib zlib || die
+	# remove prerequisite zlib/zlib.h
 	sed -i -e "s: zlib\/[a-z]*\.h::g" Makefile.in || die
 
-	mv configure.in configure.ac || die
-	sed -i -e "/^configure:/s/configure.in/configure.ac/" Makefile.in || die
-
 	use doc && cp "${DISTDIR}/gpsbabel.org-style3.css" "${S}"
-
-	eautoreconf
 }
 
 src_configure() {
 	econf \
 		$(use_with doc doc "${S}"/doc/manual) \
-		LRELEASE=$(qt5_get_bindir)/lrelease \
-		LUPDATE=$(qt5_get_bindir)/lupdate \
 		QMAKE=$(qt5_get_bindir)/qmake \
 		--with-zlib=system
-
-	if use gui; then
-		pushd "${S}/gui" > /dev/null || die
-		$(qt5_get_bindir)/lrelease *.ts || die
-		eqmake5
-		popd > /dev/null
-	fi
 }
 
 src_compile() {
 	default
-	if use gui; then
-		pushd "${S}/gui" > /dev/null || die
-		emake
-		popd > /dev/null
-	fi
 
 	if use doc; then
 		perl xmldoc/makedoc || die
@@ -104,12 +75,4 @@
 	use doc && HTML_DOCS=( "${S}"/${PN}.html "${S}"/${PN}.org-style3.css )
 
 	default
-
-	if use gui; then
-		dobin gui/objects/gpsbabelfe
-		insinto /usr/share/${PN}/translations/
-		doins gui/gpsbabel*_*.qm
-		newicon gui/images/appicon.png ${PN}.png
-		make_desktop_entry gpsbabelfe ${PN} ${PN} "Science;Geoscience"
-	fi
 }
```

### CODE REVIEW

**Comment by kentfredric** [comment]
There is probably a *much* better way to disable the network tests than employing a blanket RESTRICT="test", which prevents all tests, even the ones that don't need network, to be run.

**Comment by cjmayo** [comment]
Yes, an individual test can be disabled by deleting the relevant file in the testo.d directory.

Looking at the original bug report (421699) it was kml.test that was failing. I guess it was xmllint trying to download schemas. In 1.6.0 xmllint is only called if running the test from valgrind, so no longer an issue for the ebuild.

Enabling tests revealed one warning and another test failure, both reported upstream and now fixed. The fix for the cause of the test failure does not apply cleanly to 1.6.0 so disabled here:

```
	# remove failing test (fixed by 9f5e3e4b)
	rm testo.d/arc-project.test || die
```

**Comment by akhuettel** [comment]
Chris, first of all, sorry I wasnt aware of the PRs and started the work myself. But maybe we can combine things somehow. Which one of the two PRs is "current"? (Let's close the other one then.)

**Comment by cjmayo** [comment]
No problem. Do take whatever is useful - I've just rebased it on master with no changes, hopefully that will get a QA OK.

**Comment by cjmayo** [comment]
Updated to 1.7.0. No further changes to the ebuild but needed updated shapelib and xmldoc patches.

**Comment by vazhnov** [comment]
Any hope to see v1.7 this in Gentoo Portage?
`sci-geosciences/gpsbabel-9999` is not compiling (I tried with `-doc -gui`).

**Pull request closed without merging**
