### PR TITLE
app-editors/gvim: drop gtk2, nextaw, athena GUIs

### PR DESCRIPTION
**Pull request by laumann**
See: 7dea592a9f4 ("app-editors/gvim: drop gtk2, nextaw, athena GUIs")
Signed-off-by: Thomas Bracht Laumann Jespersen <t@laumann.xyz>

### CODE REVIEW

**Comment by laumann** [comment]
cc @thesamesam

**Comment by thesamesam** [comment]
Let's either revbump for this or do it in a version bump?

**Comment by laumann** [comment]
> Let's either revbump for this or do it in a version bump?

Sure, I must've misunderstood then, I thought the use flag changes would be
caught by --changed-use (so a revbump wouldn't be needed). I'll just let it
happen for the next version bump, there's no rush.

**Comment by thesamesam** [comment]
> Let's either revbump for this or do it in a version bump?
> Sure, I must've misunderstood then, I thought the use flag changes would be caught by --changed-use (so a revbump wouldn't be needed). I'll just let it happen for the next version bump, there's no rush.

They will be, but it's a pain for users to then downgrade, and it's a substantial revamp. It's just easier to introduce with a new version (it's due, btw ;))

**Comment by thesamesam** [comment]
Could you rebase?

**Comment by laumann** [comment]
This one isn't relevant anymore, I think. 9.0.0099 is stable now (and already dropped neXt, gtk2 and athena GUIs) and this one is for 9.0.0049.

**Pull request closed without merging**
