### PR TITLE
app-backup/btrbk: add "~alpha ~arm ~arm64 ~mips ~ppc64 ~sparc" to KEYWORDS

### PR DESCRIPTION
**Pull request by candrews**
https://bugs.gentoo.org/show_bug.cgi?id=588854

### CODE REVIEW

**Comment by candrews** [comment]
@gentoo/proxy-main

**Comment by gktrk** [comment]
@gentoo/proxy-maint 

Have you personally tested this package on all these arches? Do all the deps have keywords for those given arches?

**Comment by candrews** [comment]
@gktrk I have not personally tested on these arches (is that okay? I'm not sure what the process is, so I'm making a best guess assumption here). I'm going by what the dependencies permit and upstream's claim. All dependencies are also matching these keywords and repoman confirms that.

**Comment by monsieurp** [comment]
As per my response in the bug report.

**Comment by candrews** [comment]
@monsieurp thank you again for your clarification and help!

**Pull request closed without merging**
