### PR TITLE
games-emulation/dolphin: add 5.0_p20241130

### PR DESCRIPTION
**Pull request by Tatsh**
- Uses bundled minizip-ng and zlib-ng because `USE=compat` is masked on both of these packages
- Fixed using system xxHash
- Now requires Qt 6
- Added missing dependencies
- Games crash on start if LTO is enabled, likely due to JIT incompatibility. Perhaps LTO works
  without JIT but most users are going to want JIT enabled. `filter-lto` added.

### CODE REVIEW

**Comment by thesamesam** [comment]
fwiw I'm fine with bundled minizip/zlib-ng for now given the complete hell there

**Comment by thesamesam** [comment]
@mgorny

**Comment by FireBurn** [comment]
Hey, this seems to have gotten stuck, was just looking at packages are still depending on pulseaudio rather than libpulse

**Comment by Tatsh** [comment]
Friendly bump @mgorny @thesamesam

**Comment by Tatsh** [comment]
It appears this branch/PR has been superseded by the 2407 ebuild (why is it masked?) since Dolphin switched to rolling releases. I assume you will update to 2412 soon.

**Comment by Tatsh** [comment]
Okay. This PR is no longer needed.

**Pull request closed without merging**
