### PR TITLE
x11-base/xorg-server: test meson port

### PR DESCRIPTION
**Pull request by hanetzer**
For testing and commentary. Works well, but we may need to interact with upstream
to get some of our stuff in (the equivalent of --disable-selective-werror is not available
on meson). Not quite on par with the autotools build from what I can see.

Package-Manager: Portage-2.3.44, Repoman-2.3.10

### CODE REVIEW

**Comment by hanetzer** [comment]
As a point of refererence, `time ebuild xorg-server-9999.ebuild clean install` has
the following  results:

## meson:
```
real	0m24.402s
user	3m3.449s
sys	0m24.789s
```
## autotools
```
real	1m32.233s
user	5m10.535s
sys	0m41.258s
```
It should be noted, however, that I'm not certain that every little thing handled in
the autotools build is handled in the meson one.

**Comment by mattst88** [comment]
This looks really good.

The unfortunate situation is that upstream's Meson build system is not ready (as you noted in your comments). See https://gitlab.freedesktop.org/xorg/xserver/merge_requests/31 for a makeshift tracker of the situation.

I think we would at least want libunwind to be configurable and Xorg.wrap to be unbroken before switching.

**Comment by scardracs** [comment]
Ping: is this project still in progress?

**Comment by mattst88** [comment]
It's something I'd still like to do, yes.

**Comment by thesamesam** [comment]
meson'd Xorg is now in tree.

**Pull request closed without merging**
