### PR TITLE
net-im/dino: remove dependency on gspell

### PR DESCRIPTION
**Pull request by jubalh**
Bug: https://bugs.gentoo.org/869971

See also:
https://github.com/dino/dino/pull/1385

### CODE REVIEW

**Comment by a17r** [comment]
RDEPEND changes require revbumps. How much sense does it make to keep the 0.4.0 version around? Since 0.4.1 was added at the same time no one in ~arch ever got to install it unless they for some reason masked .1.

**Comment by jubalh** [comment]
> RDEPEND changes require revbumps. 

Ok I renamed to -r1.

>  How much sense does it make to keep the 0.4.0 version around?

I was not sure whether 0.4.1 works as good. But now after some weeks of testing I didn't see any problems. Will drop 0.4.0.

**Comment by thesamesam** [comment]
Thanks!

**Comment by thesamesam** [comment]
I had to fix -1 -> -r1 in the filename fwiw

**Pull request closed without merging**
