### PR TITLE
app-emulation/vagrant: add version bump 2.0.0

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Gentoo-Bug: 630498

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
Hey,
I've just rebased the branch on https://github.com/gentoo/gentoo/pull/5657
let me know if any changes are needed.

**Comment by GuillaumeSeren** [comment]
Oups small mistake in the Manifest rebase (deleted the 1.9.7 hash),
I've fixed it.

**Comment by hydrapolic** [comment]
Thanks,it looks fine. I cannot test it right now so I rely on you on this :)

**Comment by GuillaumeSeren** [comment]
I have tested it, and hitting (v2.0.0) milestone is not a joke for such a project 👍

**Comment by hydrapolic** [comment]
Tested, can be merged, thanks @GuillaumeSeren!

**Comment by hydrapolic** [comment]
Thanks @Amynka

**Pull request closed without merging**
