### PR TITLE
Update dev-util/conan and dependencies

### PR DESCRIPTION
**Pull request by winterheart**
Update to 1.18.0, fixes multiple bugs (#686568, #666984, #666980, #643152).

### CODE REVIEW

**Comment by TheChymera** [comment]
@winterheart lgtm

**Comment by juippis** [comment]
Hey, would you like to become the maintainer of conan? I saw in bugzilla that @bschindler wishes to hand it over. If yes, just add a new commit modifying its metadata.xml adding yourself there and removing the previous maintainer.
(I can also manually add you if its easier)

**Comment by rpolasek** [comment]
please merge it finally :-(

**Comment by sbraz** [comment]
I've bumped deprecation in 29a7bda6343d32b047a409b1afc739ea47c8b7b0. I'll see if I can do the other packages that the Python project maintains.

**Comment by sbraz** [comment]
node-semver bumped in 802c9a05f99c475a79c2a538d9388c5c0495aa70

**Comment by juippis** [comment]
Thanks @sbraz I can cherry pick the proxy-maintained packages.
However, 
```
>>> Source compiled.
>>> Test phase: dev-util/conan-1.18.0
 * python3_5: running distutils-r1_run_phase python_test

----------------------------------------------------------------------
Ran 0 tests in 0.490s

OK
 * python3_6: running distutils-r1_run_phase python_test

----------------------------------------------------------------------
Ran 0 tests in 0.498s

OK
```
With all these test-deps this is unacceptable. Please look into them. Rest is looking good.

**Comment by winterheart** [comment]
@juippis added myself to maintainers, and bumped to 1.18.1

**Pull request closed without merging**
