### PR TITLE
media-gfx/blender: add 4.0.1, update 9999

### PR DESCRIPTION
**Pull request by negril**
dds support is now provided via openimageio, dropped the useflag. Adjusted the cmake options to use yes/no, so the options we don't set explicitly show up as ON/OFF.
Added new cmake options.

Changed the test location to T as ED is not allowed outside src_install().
Introduced code so cycles tests use all configured devices. They will still fail because CUDA devices can't be found in sandbox.

Added code that sets a supported CUDA_HOST_COMPILER via cuda.eclass when using gcc.

Added HIP support to 9999 for testing.

Masked test for 4.0.1 because we don't pull the test source from svn anymore.

Bug: https://bugs.gentoo.org/895414
Closes: https://bugs.gentoo.org/917482

This requires https://github.com/gentoo/gentoo/pull/33874 so =media-gfx/blender-9999[hip] does not fail CI.

### CODE REVIEW

**Comment by DarkDefender** [comment]
Thanks for working on this!

I'll try to go through it more thoroughly later but my quite impressions are:
1. Do not turn on developer debug cmake flags with `debug`.
Those are not meant to be used but the end user.
Additionally it means that the debug build behaves significantly differently than the non debug build. Not something you want to happen when you are trying to find a bug that you discovered in the regular non debug build.

2. There is already a 4.0.1 release out, I didn't submit any bump PR for 4.0 as it contained some very bad crashing bugs.
However 4.0.1 was release today, so I am very happy that you already did the work for me! (And a lot of clean up as well!)

**Comment by DarkDefender** [comment]
I'm guessing this supersedes https://github.com/gentoo/gentoo/pull/27552 as well?

**Comment by negril** [comment]
1. Which ones are the `debug` cmake flags? `3.6.5` had `WITH_ASSERT_ABORT` and `WITH_CXX_GUARDEDALLOC` behind `debug`. Are those okay to set?
2. I'll bump to `4.0.1` before this get's merged.
3. I enabled `hip` only in `9999` for now so we can get it tested. So I think this should super seed the old PR.

**Comment by negril** [comment]
Do you know when/if the test source will be moved off svn?

**Comment by DarkDefender** [comment]
> 1. Which ones are the `debug` cmake flags? `3.6.5` had `WITH_ASSERT_ABORT` and `WITH_CXX_GUARDEDALLOC` behind `debug`. Are those okay to set?
Nice catch!
`WITH_ASSERT_ABORT` is on per default in the official builds but asserts are only active when `-DDEBUG` is passed.
However this had lead to a few issues in the past where I've tried to get a stack trace but hit an assert instead.
Of course sometimes the asserts are more helpful than the stack trace as the assert already shows that something went wrong earlier in the call stack.

Perhaps we can have an additional debug flag for this? What do you think?

`WITH_CXX_GUARDEDALLOC` is off per default and is slowly getting phased out in favor of ASAN.
We (the Blender developers) don't really use this at all anymore.

> 2. I'll bump to `4.0.1` before this get's merged.
> 3. I enabled `hip` only in `9999` for now so we can get it tested. So I think this should super seed the old PR.
:+1:

**Comment by DarkDefender** [comment]
> Do you know when/if the test source will be moved off svn?

It is still planned but there is not concrete time frame yet sadly.
I hope it can be done within half a year or so, but it all depends on how smoothly some other infrastructure projects go.

**Comment by negril** [comment]
I'll just leave them unset. The cmake eclass supports passing additional parameters via the `MYCMAKEARGS` variable so you can set the flags via that option if you need to.

**Comment by DarkDefender** [comment]
Sounds good! :+1:

**Comment by DarkDefender** [comment]
From just looking at the changes, LGTM!

**Comment by thesamesam** [comment]
Great work, thank you both!

**Pull request closed without merging**
