### PR TITLE
sys-libs/musl: add USE=crypt for libxcrypt support

### PR DESCRIPTION
**Pull request by thesamesam**
Add USE=crypt to allow enabling/disabling crypt.h installation
(to allow sys-libs/libxcrypt[system] usage). Many things are starting
to want functions from libxcrypt itself (additional functions and
algorithms).

Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by blueness** [comment]
Why are we adding this to the musl ebuild?  We have many standalone libraries that are not pulled in by a USE flag on the musl ebuild, so what makes this special.  Also, is this a standalone library?  If so, we've chosen the convention of naming these with -standalone.

What I'd like to see is a set of -standalone packages and then one musl-compat ebuild which pulls the individual packages in selectively (or in toto).

**Comment by blueness** [comment]
@mattst88   This is the point right here ->  # Allow sys-libs/libxcrypt[system] to provide it instead, comment on line 138.  The key word being "instead".  This isn't clear from the commit message.  This is the exact opposite of a breakout library, its a substitution.

**Comment by mattst88** [comment]
> @mattst88 This is the point right here -> # Allow sys-libs/libxcrypt[system] to provide it instead, comment on line 138. The key word being "instead". This isn't clear from the commit message. This is the exact opposite of a breakout library, its a substitution.

I don't understand the indignity, but I think you're missing the point. Let me try to explain:

> Why are we adding this to the musl ebuild?

We need to at least make it possible to *not* install musl's `crypt.h`, since that would conflict with libxcrypt's. By `RDEPEND`ing (only!) on libxcrypt, we ensure that `crypt.h` is always provided.

> We have many standalone libraries that are not pulled in by a USE flag on the musl ebuild, so what makes this special.

`crypt.h`.

> Also, is this a standalone library? If so, we've chosen the convention of naming these with -standalone.

It is a standalone library, and it's not specific to musl. Perhaps you've missed it, but we've switched from using glibc's built-in libcrypt to libxcrypt too, quite some time ago. It would be inappropriate to rename the package to fit in with other musl "-standalone" libraries (whose upstream names often include "-standalone"!).

**Comment by blueness** [comment]
@mattst88 no indignity intended!  I apologize if it came across that way.  What I meant is I got the point when I read that comment on line 138, not when I read the commit message.  Also, I did miss the switch-over from glibc's built-in, so I tought libxcrypt was just now being added as an augmentation to musl as I did with obstack, rpmatch, etc., not that this was something we were doing with all libc's.

**Comment by mattst88** [comment]
> What I meant is I got the point when I read that comment on line 138, not when I read the commit message.

Okay, so are you okay with the changes now? Or do you have a suggestion for improvement?

**Comment by thesamesam** [comment]
I've updated the commit messages. Is there anything that remains unclear?

**Comment by blueness** [comment]
@mattst88 @thesamesam Yes, I'm good with this.  Again, I'm sorry I caused noise with my initial confusion.  The commit message clearly explains the situation.  Thanks for looking after this Sam.

**Comment by thesamesam** [comment]
Thanks @blueness! No worries at all, this has been on the list for ages, and sorry, I'd assumed some of it was more obvious than it was -- this is one of those things I've been living and breathing while handling the glibc migration, so I've been unable to get away from it!

I'll merge this shortly if you're happy then. Rip off the bandaid!

**Pull request closed without merging**
