### PR TITLE
net-libs/pjproject: add 2.13.1

### PR DESCRIPTION
**Pull request by jkroonza**
https://github.com/pjsip/pjproject/security/advisories/GHSA-q9cp-8wcq-7pfr

The other two security issues are patched in 2.13 already, and as a rule we recommend avoiding DNS like the plague when it comes to SIP, but we can't eliminate that SIP is in use.

### CODE REVIEW

**Review by juippis — APPROVED** [review]
Looks good, can merge, but I noticed:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: mips_test.c:(.text+0x1a95): undefined reference to `pjmedia_codec_opencore_amrnb_deinit'
/usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: output/pjmedia-test-x86_64-pc-linux-gnu/mips_test.o: in function `ilbc_init':
mips_test.c:(.text+0x166): undefined reference to `pjmedia_codec_ilbc_init'
collect2: error: ld returned 1 exit status
make[2]: *** [/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/build/rules.mak:125: ../bin/pjmedia-test-x86_64-pc-linux-gnu] Error 1
make[2]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/pjmedia/build'
make[1]: *** [Makefile:245: pjmedia-test-x86_64-pc-linux-gnu] Error 2
make[1]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/pjmedia/build'
make: *** [Makefile:14: all] Error 1
 * ERROR: net-libs/pjproject-2.13.1::gentoo failed (compile phase):
 *   emake failed
```
From a quick glance the `ilbc` use flag seems to cause it. Immediate ideas?

**Comment by jkroonza** [comment]
> Looks good, can merge, but I noticed:
> 
> ```
> /usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: mips_test.c:(.text+0x1a95): undefined reference to `pjmedia_codec_opencore_amrnb_deinit'
> /usr/lib/gcc/x86_64-pc-linux-gnu/13/../../../../x86_64-pc-linux-gnu/bin/ld: output/pjmedia-test-x86_64-pc-linux-gnu/mips_test.o: in function `ilbc_init':
> mips_test.c:(.text+0x166): undefined reference to `pjmedia_codec_ilbc_init'
> collect2: error: ld returned 1 exit status
> make[2]: *** [/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/build/rules.mak:125: ../bin/pjmedia-test-x86_64-pc-linux-gnu] Error 1
> make[2]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/pjmedia/build'
> make[1]: *** [Makefile:245: pjmedia-test-x86_64-pc-linux-gnu] Error 2
> make[1]: Leaving directory '/var/tmp/portage/net-libs/pjproject-2.13.1/work/pjproject-2.13.1/pjmedia/build'
> make: *** [Makefile:14: all] Error 1
>  * ERROR: net-libs/pjproject-2.13.1::gentoo failed (compile phase):
>  *   emake failed
> ```
> 
> From a quick glance the `ilbc` use flag seems to cause it. Immediate ideas?

similar issue to the webrtc one probably.  Not needed for asterisk, but annoying none the less.

I note the .o file is called mips_test.o, yet it looks like you're compiling for x86_64?

**Comment by juippis** [comment]
> 
> I note the .o file is called mips_test.o, yet it looks like you're compiling for x86_64?

Yep, beats me :) try it yourself with `+ilbc` if you can replicate?

**Comment by juippis** [comment]
I guess it's a missing dependency then. Could you check with **iwdevtools** now that you've merged pjproject with `+ilbc`? 

**qa-vdb pjproject**

**Comment by jkroonza** [comment]
jkroon@plastiekpoot ~ $ qa-vdb pjproject
VDB: detected possibly incorrect RDEPEND (net-libs/pjproject-2.13.1)
media-libs/libilbc < 
                   > sys-apps/util-linux

Does that mean what I think it does?

We don't need the libilbc dep at all it's using an embedded version, and instead need sys-apps/util-linux?

**Comment by juippis** [comment]
Be careful with the `<` detection. It's not **linking** againgst the library, but it can use headers (DEPEND-only), it can dlopen it, etc.

**Pull request closed without merging**
