### PR TITLE
dev-python/sympy: Resolve test issues with theano-pymc

### PR DESCRIPTION
**Pull request by jsmolic**
I ran into couple of test issues while with theano-pymc
```bash
FAILED sympy/printing/tests/test_theanocode.py::test_Derivative - AttributeError: module 'theano' has no attribute 'gof'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_simple - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_multi - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_numpy - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_matrix - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_kwargs - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_scalar - AttributeError: module 'theano' has no attribute 'Variable'
FAILED sympy/printing/tests/test_theanocode.py::test_MatrixSlice - ImportError: cannot import name 'Constant' from 'theano' (/usr/lib/python3.8/site-packages/theano/__init__.py)
FAILED sympy/printing/tests/test_theanocode.py::test_cache_complex - AttributeError: module 'theano' has no attribute 'gof'
FAILED sympy/printing/tests/test_theanocode.py::test_constantfunctions - AttributeError: module 'theano' has no attribute 'Variable'
```

Tha patch is a WIP for now as I still need to fix 2 more failures:
```
FAILED sympy/printing/tests/test_theanocode.py::test_Derivative - theano.graph.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute Elemwise{second,no_inplace}(x, TensorConstant{1....
FAILED sympy/printing/tests/test_theanocode.py::test_theano_function_scalar - AttributeError: module 'theano.compile.function' has no attribute 'Function'
```

### CODE REVIEW

**Comment by mgorny** [comment]
Nice work, man! Did you test against old theano for comparison?

**Comment by jsmolic** [comment]
Thanks! Yeah, I've tried against old theano and everything works well. I'm almost there, but the `test_theanocode.py::test_Derivative` still refuse to work
```
FAILED test_theanocode.py::test_Derivative - theano.graph.fg.MissingInputError: Input 0 of the graph (indices start from 0), used to compute Elemwise{second,no_inplace}(x, TensorConstant{1.0}), was not provided and not given a value.
```
I don't know if it's a bug in theano-pymc or something...

**Comment by thesamesam** [comment]
@mgorny happy with this?

**Comment by jsmolic** [comment]
@thesamesam I forgot to close the PR as this has been properly fixed upstream, and since version 1.8 only `dev-python/aesara` is supported

**Comment by thesamesam** [comment]
Aha, that makes sense. Thanks a bunch for the work @jsmolic

**Pull request closed without merging**
