### PR TITLE
net-vpn/i2p: bump to 1.7.0

### PR DESCRIPTION
**Pull request by tharvik**
* mostly copied from 1.6.1
* allow to run with `virtual/jdk:11`
* use `mockito:4` for test

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. Any particular reason for dropping 'arm'?

**Comment by tharvik** [comment]
> Any particular reason for dropping 'arm'?

Hum, I was waiting on https://bugs.gentoo.org/834926 to be resolved, but if you think I can already add "~arm" to it, I'll happily do so :)

**Comment by Flowdalic** [comment]
> but if you think I can already add "~arm" to it, I'll happily do so :)

Well, net-vpn/i2p-1.6.1 already has the ~arm keyword, so it would be unusual to drop it unless there is a particular reason (like a known compilation or runtime issue on arm). The fact that it hasn't been keyworded for arm64 doesn't matter here.

**Comment by tharvik** [comment]
> it would be unusual to drop it unless there is a particular reason (like a known compilation or runtime issue on arm).

No specific reason, alright, putting "~arm" into keywords, thanks for the explanation.

**Pull request closed without merging**
