### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by DarthGandalf**

### CODE REVIEW

**Comment by xgqt** [comment]
cpp-httplib is already in ::gentoo

**Comment by DarthGandalf** [comment]
Oh ok, I guess we did it in parallel. Will drop from here

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
> DroppedKeywords: version 23.4: ppc, ppc64, riscv

**Comment by DarthGandalf** [comment]
I know, I had to wait until this is merged before requesting rekeywording...

**Pull request closed without merging**
