### PR TITLE
sci-misc/boinc: Fix VSYSCALL check

### PR DESCRIPTION
**Pull request by Yamakuzure**
Gentoo-Bug: 578750

The configuration options were misunderstood.

- CONFIG_X86_VSYSCALL_EMULATION only enables a dmesg message if any legacy application tries to use any vsyscall. If disabled, these applications simply segfault with no output in dmesg.
- To make the old calls available, either CONFIG_LEGACY_VSYSCALL_NATIVE or CONFIG_LEGACY_VSYSCALL_EMULATE must be used.

Therefore the ebuild was reverted to check against the CONFIG_LEGACY_VSYSCALL_NONE option, and warns the user if this is set.

Package-Manager: portage-2.2.28

@SoapGentoo @jlec I was not sure if the one-commit-per-ebuild-policy applies to such a case were all fixes are the same.

### CODE REVIEW

**Comment by Yamakuzure** [comment]
@SoapGentoo @jlec Is there something wrong with the QA check? None of these make sense and if I try to open any of the links, the page loads until time-out without showing anything...

**Comment by monsieurp** [comment]
Disregard all warnings. The VM meant to be hosting our QA servers is down atm.

**Comment by SoapGentoo** [comment]
Merged, thanks.

**Comment by idella** [comment]
merged it seems

**Comment by idella** [comment]
is closed

**Pull request closed without merging**
