### PR TITLE
New ARM 17.0 uclibc profiles + features subsection

### PR DESCRIPTION
**Pull request by mjeveritt**
@blueness

### CODE REVIEW

**Comment by mjeveritt** [comment]
I've taken the liberty of removing the games-* from the package masks, as they probably need a re-audit of ones that are still present in-tree or still cause problems.

I see there is a pending switch between uclibc[-vanilla] and uclibc-ng which I'm pretty keen to 'encourage' for stage-building, although there are issues in catalyst and toolchain.eclass which need attention.

**Comment by blueness** [comment]
I have this on my radar.  I need to test them on my arm system before committing to the tree, hence the delay

**Comment by mjeveritt** [comment]
@blueness : That's fine - just wanted to get them in the queue! :)

**Comment by chewi** [comment]
@blueness, not sure how you're attempting to change CHOST but doing it with Catalyst is fiddly. You're better off running my migration script against an existing stage3 and then use that as a seed stage.

**Comment by mjeveritt** [comment]
I had a go at running the migration myself, but fell into a number of traps:
* masking of uclibc
* patch required to re-build uclibc
* toolchain.eclass deficiencies with regard to uclibc-ng (which I possibly unwittingly opted for)
* crossdev deficiencies with respect to uclibc-ng (required for distcc compiling)

at which point I decided to take a break and seek advice on the appropriate way to proceed.
I feel that a decision should be taken whether to continue using unsupported uclibc or 'bite the bullet' and move to uclibc-ng, for which I note there is a tracker bug open.
I'm happy to do some of the leg-work involved here, particularly patches involving crossdev and catalyst, but will have to defer to slyfox/toolchain probably for toolchain eclass issues, unless someone else wishes to volunteer... !

**Comment by blueness** [comment]
i'm still working on the stage3 migrations.  i'll get it.

**Comment by blueness** [comment]
okay pushed.  i hope to have the stage3s built on this on the mirrors in the next few days.

@mjeveritt can you look at amd64 and x86 as well.

**Pull request closed without merging**
