### PR TITLE
Magick virtual subslot

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@pacho2 having both imagemagick and graphicsmagick use lfags is the only way to make subslots useable. What do you do if a package support IM, GM, or none?

**Comment by pacho2** [comment]
Yes, I agree with needing USE flags... but I was wondering about the ?? RESTRICTED_USE

I am unsure about how to ensure people will use that RESTRICTED_USE properly, we could make repoman warn if that is not set and the USEs are there... but we could maybe have cases of a package having a real graphicsmagick support and, then, being able to get both supports enabled at the same time :/

**Comment by pacho2** [comment]
I mean, I was thinking more on using a syntax similar to ffmpeg vs libav, that consists on !libav ( "ffmpeg support enabled") over relying on REQUIRED_USE

**Comment by SoapGentoo** [comment]
@pacho2 in 90% of cases, packages only support one lib simulanteously. And concerning the somewhat awful `REQUIRED_USE`, we'll turn it into a QA rule that imagemagick **has** to be the default - so that the default works for users without hacking `package.use`

**Comment by SoapGentoo** [comment]
After all, imagemagick is the ffmpeg of both of them

**Comment by SoapGentoo** [comment]
@pacho2 
Ok here's an idea: If a package **needs** either im or gm (i.e. `REQUIRED_USE="^^ ( im gm )"`), then we do:
```
imagemagick? ( media-gfx/imagemagick:= )
!imagemagick? ( media-gfx/graphicsmagick:= )
```
If a package **can** use either im or gm (i.e. `REQUIRED_USE="?? ( im gm )"`), then we do:
```
imagemagick? ( media-gfx/imagemagick:= )
!imagemagick? ( graphicsmagick? ( media-gfx/graphicsmagick:= ) )
```
This avoids the `REQUIRED_USE` completely

**Comment by pacho2** [comment]
Yeah, that was my suggestion to try to not mess with REQUIRED_USE and also be a bit more "coherent" with the ffmpeg/libav issue :)

**Comment by SoapGentoo** [comment]
@pacho2 Ok, I will implement it, but to give our users better default, this should still be a QA rule, i.e.,
```
graphicsmagick? ( media-gfx/graphicsmagick:= )
!graphicsmagick? ( imagemagick? ( media-gfx/imagemagick:= ) )
```
should not be allowed, just because the maintainer hates imagemagick

**Comment by SoapGentoo** [comment]
@pacho2 please recheck, you only need to look at the last 5 commits, as those deal with subslots.

**Comment by pacho2** [comment]
yes, that last virtual looks to be ok from my point of view :)

**Comment by mgorny** [comment]
Looks like a terrible idea. You're making the flags semi-magical and unclear, and relying on maintainers using IUSE defaults to make things work the way you imagined it.

Let's say we have following types of packages worth considering:
* **IG** - supports either, always on,
* **I?** - supports only IM, optional,
* **G?** - supports only IM, optional,
* **IG?** - supports only IM, optional.

With your solution:

USE | IG | I? | G? | IG?
------------ | ------------- | ---------- | ------- | -------
\- | I | - | - | I
imagemagick | I | I | - | I
-imagemagick | G | - | - | -
graphicsmagick | I | - | G | I
graphicsmagick -imagemagick | G | - | G | G
graphicsmagick imagemagick | I | I | G | I
? | I | - | - | -
? | G | I | G | G

So, three problems:
1. Do you really expect all people to use IUSE defaults as you want them?
2. Do you really expect all users to figure out this matrix on their own? Like that USE=graphicsmagick is silently ignored unless you explicitly force USE=-imagemagick?
3. What about the missing cases? You are forcing ImageMagick always on. If I don't want it when it's optional, I'm suddenly switching to GraphicsMagick implicitly.

**Comment by SoapGentoo** [comment]
@pacho2 so what do you suggest? The clearest solution remains the `REQUIRED_USE` one, where `USE="+im"` directly maps to -> `"I want to build against imagemagick"`

I still think the ffmpeg one is confusing, as has been shown on a gazillion occasions with LibreSSL too (which uses the same logic/idea). So either:

1. ffmpeg style
2. REQUIRED_USE

The latter is semantically the clearest, but can be painful. @pacho2 @mgorny please decide. I just want to implement something.

**Pull request closed without merging**
