### PR TITLE
Create qt5ct-0.22.ebuild

### PR DESCRIPTION
**Pull request by mndar**
https://bugs.gentoo.org/show_bug.cgi?id=577840

### CODE REVIEW

**Comment by monsieurp** [comment]
Thank you for the PR. Make sure your contributions passes our QA checks and do read https://wiki.gentoo.org/wiki/Gentoo_Github. We expect commit messages to be formatted according to a naming scheme. See https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format.

**Comment by monsieurp** [comment]
@kensington

**Comment by mndar** [comment]
Thanks monsierup. I'll read the docs you mentioned and fix the ebuild

**Comment by mndar** [comment]
Had to create a new pull request. Sorry for the trouble.
This PR was missing Manifest and metadata.xml
New Request: https://github.com/gentoo/gentoo/pull/1143

**Comment by monsieurp** [comment]
Fair enough. Let's close this one then.

**Pull request closed without merging**
