### PR TITLE
lxqt 0.10 version bump

### PR DESCRIPTION
**Pull request by PPed72**
Just pushing Alpha Bravo's changes in https://bugs.gentoo.org/show_bug.cgi?id=564718 and https://bugs.gentoo.org/show_bug.cgi?id=565952 since they've been there for a week and nothing happened yet.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thank you for you PR. LGTM except the messages format. Could you reformat your commit messages and instead write "package/category: message" ? That'd helpful. Thanks!

**Comment by monsieurp** [comment]
@jauhien

**Comment by PPed72** [comment]
In data Wednesday 25 November 2015 00:45:28, monsieurp ha scritto:
> Hi and thank you for you PR. LGTM except the messages format. Could you
> reformat your commit messages and instead write "package/category: message"

Shouldn't it be "category/package", like "lxqt-base/lxqt-meta"?

> ? That'd helpful. Thanks!

I'll do that, probably tomorrow.

Thanks.

-- 
Paolo Pedroni
paolo.pedroni<at>iol.it

**Comment by PPed72** [comment]
Changed all the commit messages. Are they OK, now? Thanks for the attention

**Comment by jauhien** [comment]
Hi,

I'm busy at the moment and also have problems with my computer. Could you, please, ping somebody else from the lxqt herd?

**Comment by monsieurp** [comment]
Thank for the PR @PPed72. Unfortunately, there are still errors that are to be looked after.

https://qa-reports.gentoo.org/output/gentoo-ci/7c7f0d1/10.html#l1826

Something's up with the ~arm keyword, lxqt-base/lxqt-config and lxqt-base/lxqt-panel. Could you please make sure all ebuilds are keyworded correctly and your PR is not generating errors? Thanks!

**Comment by PPed72** [comment]
kde-frameworks/solid and kde-plasma/libkscreen have no keywords for arm. I'm going to drop arm and arm64 for the moment

**Comment by monsieurp** [comment]
Thanks a lot. PR merged. :+1:

**Pull request closed without merging**
