### PR TITLE
Cleanup more

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by billie80** [comment]
No problem from my side! Just one question.
Why? I mean why exactly this set of packages. I guess there are a lot more around!
I usually clean up old versions of the packages I maintain myself. Just wait some time after stabilising a newer version. In the case of ttcut this happened just a few days ago!

**Comment by a17r** [comment]
> No problem from my side! Just one question.
> Why? I mean why exactly this set of packages. I guess there are a lot more around!

Trying to cut down on old EAPI consumers of qmake-utils.eclass.

**Comment by billie80** [comment]
Okay, I see!

**Comment by a17r** [comment]
ping

**Comment by a17r** [comment]
ping

**Comment by a17r** [comment]
@aballier They're safe, nevertheless I would like to test my ViSP changes but I can't because even pre-change it fails with https://bugs.gentoo.org/729576

**Comment by kiwifb** [comment]
No objections in principle from me. But I'd like to have more details on the failures building the documentation. They should be fixed sooner rather than later. There is a potential missing tex dependency spotted in https://bugs.gentoo.org/729634 and if there is more stuff needed I very much would like to know.

I will also want to discuss what we do next with suitesparse because the current approach limits the way we can work on improving things.

**Comment by a17r** [comment]
> and Rolf mentioned a `VARTEXFONTS` sandbox issue on https://bugs.gentoo.org/716960.

Re that issue see also https://bugs.gentoo.org/223077

**Pull request merged**
