### PR TITLE
www-plugins/passff-host: Use $(get_libdir) instead of lib

### PR DESCRIPTION
**Pull request by lanodan**
Closes: https://bugs.gentoo.org/662672

### CODE REVIEW

**Comment by lanodan** [comment]
I haven’t confirmed it (would probably require building another gentoo with firefox and passff), but I’m pretty sure firefox wants lib64/lib32 instead of lib as it’s probably using get_libdir and so the path would be considered to be wrong.

**Comment by mgorny** [comment]
Well, either do confirm it or request the user to confirm it. Plus, it probably needs to be tested with firefox and firefox-bin separately. FWIR, they used to disagree on the plugin paths, so this might be affected as well x_x.

**Comment by a17r** [comment]
Any plans for this, still?

**Comment by lanodan** [comment]
Was on hold, did a 17.1 system and I remember that firefox was inconsistent between `amd64` and `~amd64` at the time.

**Comment by devurandom** [comment]
> Well, either do confirm it or request the user to confirm it. Plus, it probably needs to be tested with firefox and firefox-bin separately. FWIR, they used to disagree on the plugin paths, so this might be affected as well x_x.

I confirm that it not only looks wrong, but actually is wrong. PassFF in Firefox complains: `Connection to the host app failed or returned an unexpected result!`. I am on on amd64, where lib and lib64 are different directories and my Firefox is built for x86-64, not x86-32. I added some more information to the bug report to clarify this.

**Comment by lanodan** [comment]
[2019-03-30 13:35:25-0700] Dennis Schridde:
> I confirm that it not only looks wrong, but actually is wrong. PassFF in Firefox complains: `Connection to the host app failed or returned an unexpected result!`. I am on on amd64, where lib and lib64 are different directories and my Firefox is built for x86-64, not x86-32. I added some more information to the bug report to clarify this.

Okay, thanks I’ll redo this change for the current version of the ebuild then.

**Comment by lanodan** [comment]
Closing in favor of https://github.com/gentoo/gentoo/pull/11762

**Pull request closed without merging**
