### PR TITLE
VA-API: move category and take over maintainership

### PR DESCRIPTION
**Pull request by mattst88**

### CODE REVIEW

**Comment by mattst88** [comment]
cc: @aballier, @Karlson2k, @ConiKost

**Comment by Karlson2k** [comment]
Several changes in one PR:
* libva intel media driver bump - _OK by me_
* Rename x11-libs/libva-\* -> media-libs/libva-\* - _Fine. Makes sense as libs are not X11-specific._
* Change maintainer - _I like to see someone from Gentoo team. I'm less active last months._

**Review by ConiKost — APPROVED** [review]
I like the move to media-libs.

**Comment by ajakk** [comment]
Please rebase, CI was erroneously counting too many warnings and then treating them as errors for a while.

**Comment by mattst88** [comment]
https://wiki.gentoo.org/wiki/Project:VA-API — project created. @ConiKost: feel free to join.

**Comment by ConiKost** [comment]
> https://wiki.gentoo.org/wiki/Project:VA-API — project created. @ConiKost: feel free to join.

Thanks, done!

**Pull request closed without merging**
