### PR TITLE
sci-misc/menedeleydesktop: Version bump, enable python3_5, bump to EAPI=6 

### PR DESCRIPTION
**Pull request by marbre**
@jlec Please bump.

Version bump + python3_5 enabled. Bump to EAPI=6 will follow later; currently failing with `eapply_user (or default) must be called in src_prepare()!`. Probably won't find time to dig in before next week.

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@marbre that errors comes if you fail to do `default` in src_prepare.

**Comment by marbre** [comment]
@SoapGentoo Do you suggest to simply add `default` to the end of the `src_prepare` phase? I currently only have limited time available.

**Comment by SoapGentoo** [comment]
@marbre yes

**Comment by marbre** [comment]
Done :)

**Comment by SoapGentoo** [comment]
@marbre could you maybe just squash the commits together? Such that ebuild bumps are atomic and not spread over multiple commits? Thanks :)

**Comment by marbre** [comment]
@SoapGentoo Done.

**Pull request merged**
