### PR TITLE
dev-vcs/gitstats: fix the live ebuild's repo URI, license, dependencies, docs

### PR DESCRIPTION
**Pull request by gktrk**
@amadio

### CODE REVIEW

**Comment by gktrk** [comment]
Please do not merge without amadio's approval.

**Comment by monsieurp** [comment]
is @amadio aware of this PR?

**Comment by gktrk** [comment]
I did hilight him here, and also left a !note on IRC. your guess is as good as mine :) I'll try to email him.

**Comment by amadio** [comment]
Hi, I was not aware of this before, sorry. I will have a look at it today.

**Comment by amadio** [comment]
Looks good to me. Please feel free to go ahead.

**Pull request closed without merging**
