### PR TITLE
net firewall/ipsec-tools - add systemd support

### PR DESCRIPTION
**Pull request by PPed72**
Compared to my suggestions in Gentoo bug #534316, I've reworked the unit files to avoid sourcing /etc/conf.d/racoon. I'm still keeping ipsec.service and racoon.service as separate files because I see value in that.

### CODE REVIEW

**Comment by monsieurp** [comment]
@blueness it might be of interest to you

**Comment by blueness** [comment]
okay this is committed.  two points: 1) never add an ebuild with stable keywords, drop to ~arch.  2) there as a lot of whitespace damage.

i don't use systemd, so i can't say if this works.  please test.

**Comment by PPed72** [comment]
On Fri, 27 Nov 2015 14:21:50 -0800
"Anthony G. Basile" <notifications@github.com> wrote:

> okay this is committed.  two points: 1) never add an ebuild with stable keywords, drop to ~arch.  2) there as a lot of whitespace damage.

Thanks a lot and sorry for the rookie mistakes: I'm trying to improve.

> 
> i don't use systemd, so i can't say if this works.  please test.

I'm sure it works, I use it almost daily.

-- 
Paolo Pedroni <paolo.pedroni@iol.it>

**Comment by blueness** [comment]
np, there was also a collision with libreswan's ipsec.service so i had to rename the file ot ipsec-tools.service.  anyhow, these type of file collision are hard to anticipate.  thanks for the contribution even though systemd is my mortal enemy :)

**Comment by PPed72** [comment]
Ok, but then you have to change the "Requires" line in the racoon.service file to require ipsec-tools.service instead of ipsec.service
-- 
Paolo Pedroni
paolo.pedroni<at>iol.it
Il 30/nov/2015 11:48, "Anthony G. Basile" <notifications@github.com> ha scritto:np, there was also a collision with libreswan's ipsec.service so i had to rename the file ot ipsec-tools.service.  anyhow, these type of file collision are hard to anticipate.  thanks for the contribution even though systemd is my mortal enemy :)

**Comment by blueness** [comment]
ok fixed.

**Pull request closed without merging**
