### PR TITLE
media-libs/openimageio: fix 936472 (FindLibheif problem)

### PR DESCRIPTION
**Pull request by vowstar**
- media-libs/openimageio: add 2.5.13.1
- media-libs/openimageio: fix FindLibheif with compiler preprocessing
- heif_version.h multilib warpper caused FindLibheif can't fetch version, use compiler to get correct version info.

Closes: https://bugs.gentoo.org/936472

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
cc @negril

**Comment by negril** [comment]
What libheif version did you test your fix against? https://github.com/gentoo/gentoo/pull/36951 might already fix that if it ever gets done.

Your commits have warpper instead of wrapper in them.

I'll have more stuff I want to check. I'll try to do that tomorrow.

**Comment by vowstar** [comment]
> What libheif version did you test your fix against? #36951 might already fix that if it ever gets done.
> 
> Your commits have warpper instead of wrapper in them.
> 
> I'll have more stuff I want to check. I'll try to do that tomorrow.

I've test ``media-libs/openimageio-2.5.12`` and ``media-libs/openimageio-2.5.13.1``.
Because I'm using a macro definition that uses compiler preprocessing to get version information, it's more general than using regular expressions. Even if https://github.com/gentoo/gentoo/pull/36951 is merged, it will be compatible. Even if you use the old version ``media-libs/libheif``, you can still be compatible.

**Comment by negril** [comment]
I wanted to know the version of `media-libs/libheif` you tested against. `media-libs/libheif-1.17.6` has since been added to the tree. Did you test against that or only against the old `media-libs/libheif-1.15.2-r1`? Iirc your fix becomes unneeded with the newer `libheif`, so that should be noted in the ebuild.

The word is [wrapper](https://en.wikipedia.org/wiki/Wrapper_function), not `warpper`. Not the position of the `r`.

**Comment by vowstar** [comment]
> I wanted to know the version of `media-libs/libheif` you tested against. `media-libs/libheif-1.17.6` has since been added to the tree. Did you test against that or only against the old `media-libs/libheif-1.15.2-r1`? Iirc your fix becomes unneeded with the newer `libheif`, so that should be noted in the ebuild.
> 
> The word is [wrapper](https://en.wikipedia.org/wiki/Wrapper_function), not `warpper`. Not the position of the `r`.

No, not ``media-libs/libheif-1.15.2-r1``. The version of libheif I've tested is ``media-libs/libheif-1.17.6``.

```bash
OIIO 2.5.13.1 | Linux/x86_64
    Build compiler: gcc 13.3 | C++17/201703
    HW features enabled at build:
    sse2,sse3,ssse3,sse41,sse42,avx,avx2,avx512f,avx512dq,avx512ifma,avx512cd,
    avx512bw,avx512vl,fma,f16c
Dependencies: Boost 1.85.0, BZip2 1.0.8, FFmpeg 6.0, fmt 9.1.0, Freetype
    2.13.0, GIF 5.2.2, Libheif 1.17.6, libjpeg-turbo 3.0.3, OpenColorIO
    2.3.2, OpenEXR 3.2.4, OpenGL, OpenJPEG 2.5, PNG 1.6.43, pugixml 1.14,
    pybind11 2.13.1, Python 3.11.9, Qt5 5.15.14, Qt6 NONE, Robinmap, TIFF
    4.6.0, WebP, ZLIB 1.3.1
```

**Comment by vowstar** [comment]
Corrected the misspelling of the word ``wrapper`` in commit message, thanks for review!

**Comment by vowstar** [comment]
Evidence:

```bash
$ qfile /usr/include/libheif/heif_version.h
media-libs/libheif: /usr/include/libheif/heif_version.h

$ equery l media-libs/libheif 
 * Searching for libheif in media-libs ...
[IP-] [  ] media-libs/libheif-1.17.6:0/1.17

$ [ "x" != "x$(cat /usr/include/libheif/heif_version.h | grep LIBHEIF_VERSION)" ] && echo "found" || echo "not found"
not found

$ [ "x" != "x$(cat /usr/include/libheif/heif_version.h | grep ABI)" ] && echo "found" || echo "not found"
found

head -n 4 /usr/include/libheif/heif_version.h
/* This file is auto-generated by multilib-build.eclass
 * as a multilib-friendly wrapper. For the original content,
 * please see the files that are #included below.
 */

```

According to the above information, the ``/usr/include/libheif/heif_version.h`` installed by ``media-libs/libheif-1.17.6`` does not contain the ``LIBHEIF_VERSION`` macro definition at all, which will inevitably cause ``media-libs/openimageio`` to not be recognized when compiling. version resulting in failure.

Reading the content of ``heif_version.h`` will reveal that this file is automatically generated by ``multilib-build.eclass`` and is not the original file of the libheif project. The original file has been hidden elsewhere. So having the compiler preprocess it makes it easier to get the correct version.

**Comment by vowstar** [comment]
ping @negril

**Review by negril — APPROVED** [review]

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Pull request closed without merging**
