### PR TITLE
cargo.eclass updates to support crates.io packages

### PR DESCRIPTION
**Pull request by cardoe**
These are some updates to the cargo.eclass to support building most crates.io packages as Gentoo packages. It should be pretty trivial to take a crates.io package and make an ebuild using https://github.com/cardoe/cargo-ebuild

CC @gentoo/rust @leio @gentoo90 
ref: https://github.com/gentoo/gentoo-rust/issues/195
ref: https://github.com/rust-lang/cargo/issues/2998

### CODE REVIEW

**Comment by cardoe** [comment]
Doing this as a pull request to get some feedback before I merge it.

**Comment by gentoo90** [comment]
Maybe  also set `ECARGO_HOME=${DISTDIR}/cargo-src` for `9999` packages. The same way as `git-r3.eclass` and the others keep their sources in `${DISTDIR}` subfolders.

Package can do this by themselves but this could lead to multiple `CARGO_HOME`s in `${DISTDIR}`

**Comment by cardoe** [comment]
So they all share dependencies? I'm not understanding the motivation. We can do it but just trying to understand.

**Comment by mgorny** [comment]
@cardoe, please don't edit comments like that. I've spent quite a while figuring out wtf could the bot output rust there when proxy-maint is hardcoded. Besides, if you don't want auto-assignment, just assign the PR or set the assigned label.

**Comment by gentoo90** [comment]
@cardoe motivation is to reduce network activity and let user to reinstall `9999` ebuild when offline.
Currently if you set `EVCS_OFFLINE=1` it will prevent tries to update the git repo for ebuild, but cargo will still download the full index and the dependencies (or fail if there's no internet connection).

**Comment by cardoe** [comment]
@gentoo90 I'm still not following. Changing the CARGO_HOME shouldn't cause reduced network activity and these changes make builds work without network. My understanding of how this works with this PR, your package manager downloads SRC_URI and stores them in your distfiles. When you build the package it creates a per package CARGO_HOME and copies from distfiles the various crates that are dependencies. The only crates and metadata available are those specified in the ebuild in SRC_URI. It will then build the package or fail to build the package.

If CARGO_HOME is shared between multiple packages then you have situations where the Cargo.lock isn't present (which is the case for most binary crates) and when cargo generates the Cargo.lock it could decide to use something newer than what the ebuild specified (but still semver compatible) and it need different dependencies and fail to build.

**Comment by cardoe** [comment]
Well since this is for -9999 ebuilds, which we still don't have in the tree I'll merge this and we can improve it later.

**Pull request closed without merging**
