### PR TITLE
app-admin/ulogd: fix Gentoo bug #564396, remove old

### PR DESCRIPTION
**Pull request by Coacher**
https://bugs.gentoo.org/show_bug.cgi?id=564396

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by Coacher** [comment]
^^Unrelated postfix problems.

**Comment by Coacher** [comment]
Rebased on top of recent master to avoid QA warnings.

**Comment by hasufell** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
thanks hasufell

**Comment by idella** [comment]
pushed

**Pull request merged**
