### PR TITLE
app-vim/csound-syntax: bump to 0.8.1

### PR DESCRIPTION
**Pull request by jsmolic**
Closes: https://bugs.gentoo.org/736358
Package-Manager: Portage-2.3.99, Repoman-2.3.23
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>

### CODE REVIEW

**Comment by jsmolic** [comment]
ping @monsieurp

**Comment by jsmolic** [comment]
ping @radhermit

**Review by monsieurp — APPROVED** [review]
Sorry for taking so long to review your PR. Looks good. Merging underway.

**Comment by jsmolic** [comment]
@monsieurp No worries, thank you

**Pull request closed without merging**
