### PR TITLE
x11-libs/gtk+: add media-libs/libepoxy[egl], media-libs/libepoxy[egl]: remove hppa stable mask

### PR DESCRIPTION
**Pull request by vimproved**
`gdk/wayland/gdkdisplay-wayland.h` includes `epoxy/egl.h`.

### CODE REVIEW

**Comment by mattst88** [comment]
I'm totally fine with just always requiring `libepoxy[egl(+)]`. I can imagine removing the egl USE flag from libepoxy at some point.

**Comment by vimproved** [comment]
> I'm totally fine with just always requiring `libepoxy[egl(+)]`. I can imagine removing the egl USE flag from libepoxy at some point.

That's fine if you think it's better. I was just screwing around with `USE="-*"` in a chroot to catch bugs, highly doubt anyone would actually encounter this under normal circumstances.

**Comment by mattst88** [comment]
Yeah, that makes sense. Feel free to update the PR and I'll take it.

**Comment by vimproved** [comment]
`media-libs/libepoxy[egl]` is stable-masked on hppa, so I can't add the usedep without destabilizing for hppa. What would you like me to do?

**Comment by vimproved** [comment]
> `media-libs/libepoxy[egl]` is stable-masked on hppa, so I can't add the usedep without destabilizing for hppa. What would you like me to do?

`USE=wayland` is also stable-masked, so that's why it wasn't an issue previously.

**Comment by vimproved** [comment]
> `media-libs/libepoxy[egl]` is stable-masked on hppa, so I can't add the usedep without destabilizing for hppa. What would you like me to do?

Actually, this stable-mask appears to be wrong since the reasoning is "media-libs/mesa is not marked stable on HPPA", however 22.3.7-r1 has been stabilized since.

**Comment by mattst88** [comment]
It looks like the second commit only renames ebuilds and doesn't modify them.

Let's modify only `gtk+-3.24.38.ebuild` and do it in-place. There's no good reason to force a rebuild here.

**Comment by mattst88** [comment]
Ping?

**Comment by vimproved** [comment]
My bad -- intended to update this but forgot.

**Comment by mattst88** [comment]
> I'm totally fine with just always requiring libepoxy[egl(+)]. I can imagine removing the egl USE flag from libepoxy at some point.

```diff
-       >=media-libs/libepoxy-1.4[X(+)?,${MULTILIB_USEDEP}]
+       >=media-libs/libepoxy-1.4[X(+)?,egl,${MULTILIB_USEDEP}]
```

This is not what I suggested.

**Pull request closed without merging**
