### PR TITLE
games-emulation/ryujinx: add 1.1.1388

### PR DESCRIPTION
**Pull request by Tatsh**
This package requires latest (currently masked) 8.0 SDK to build or it will fail with CS0535 errors.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by xgqt** [comment]
since we do not have a mechanism to require X.Y.Z (only X.Y) you will have to add `|| ( >=bin-8.0.401 >=non-bin-8.0.401 )` :/

**Comment by Tatsh** [comment]
Updated to reference 8.0.401 as bdep and rdep. Added back keywords.

**Comment by xgqt** [comment]
> Updated to reference 8.0.401 as bdep and rdep. Added back keywords.

Well then this will fail with KWSS since it is a "unsolvable dependency".
Im pretty sure the .401 is only needed on BDEPEND

Either way... no way to patch it to support <.401?
For Powershell (similar case - requires newest or sometimes even bleeding edge SDK) we can not patch it since it is very complicated with their custom generators.

Here patching for <.401 might be possible... hopefully.

**Comment by Tatsh** [comment]
Build is now fixed with a downgrade of the `Microsoft.CodeAnalysis.CSharp` dependency and its dependencies. The patch is done with `sed` in `src_prepare()`.

**Comment by xgqt** [comment]
> Build is now fixed with a downgrade of the `Microsoft.CodeAnalysis.CSharp` dependency and its dependencies. The patch is done with `sed` in `src_prepare()`.

I would prefer a .patch file but this is good enough. Thanks very much!

**Pull request closed without merging**
