### PR TITLE
net-libs/ripe-atlas-sagan: Stabilisation

### PR DESCRIPTION
**Pull request by danielquinn**
As I understand things, I'm supposed to issue a stabilisation request after about a month of use with no bug reports, so here it is.

### CODE REVIEW

**Comment by monsieurp** [comment]
Daniel, thank you for your PR. Stabilising a package is a process handled for and by arch teams. Typically, in this case, you'd file a bug on bugs.gentoo.org and call for a package stabilisation by CCing the relevant arch teams in to the bug (amd64 and x86 in your case). I really would like to merge your PR but there are policies we have to go by and I might get told off if I do so. This is also valid for the two other PRs you've sent. 

For you to avoid filing a report for each package, file one "global" report and list in the summary all the packages you'd like to stabilise. Here's an example:

https://bugs.gentoo.org/show_bug.cgi?id=573480

Feel free to CC me in should you need help.

Sorry! :disappointed:

**Comment by danielquinn** [comment]
No problem!  I still need to learn the process :-)

**Comment by monsieurp** [comment]
Dude! You're the guy who paid for my meal at the FOSDEM dinner! I was looking for you all over the place in order to thank you! :smile: 

Thanks again! Much appreciated! :+1:

**Comment by danielquinn** [comment]
Anytime :-)
By the way, should I mention the removal of `ripe-atlas-cousteau-1.0.6` and `ripe-atlas-tools-1.2.1` in the bugzilla ticket as well, or should I make separate PRs for those?

**Comment by monsieurp** [comment]
No, simply wait for the arch teams to sort out the stabilisation request. They don't deal with old versions removals. Get back to us with a PR that cleans those up.

**Pull request closed without merging**
