### PR TITLE
net-im/discord: add 0.0.50, drop 0.0.49

### PR DESCRIPTION
**Pull request by parona-source**

### CODE REVIEW

**Comment by Flowdalic** [comment]
This commits 0.0.50 straight to stable. Please keep 0.0.49 and add 0.0.50 with unstable keywords.

**Review by juippis — APPROVED** [review]
I'll echo what I said in IRC:
```
<@juippis> it's a pre-compiled binary, not much will change it being stable or unstable
<@juippis> AT does nothing with the package. It just unpacks
```

**Comment by Flowdalic** [comment]
> <@juippis> it's a pre-compiled binary, not much will change it being stable or unstable
> <@juippis> AT does nothing with the package. It just unpacks

Just to add. The argument that can be made here in favor of committing straight to stable is that the current version of discord does no longer work. Which was not obvious from this PR nor in any commit message.

Just because a package is a binary package is IMHO not enough justification to commit straight to stable.

**Comment by parona-source** [comment]
Discord is a case where it breaks immediately.

**Comment by sarnex** [comment]
As (one of the) maintainers, I have been doing straight to stable for as long as I can remember

**Pull request closed without merging**
