### PR TITLE
kde-apps/kwalletd: Add missing DEPEND on dev-libs/libgcrypt

### PR DESCRIPTION
**Pull request by a17r**
Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by hasufell** [comment]
This needs a revbump.

**Comment by kensington** [comment]
Thanks, merged.

**Comment by hasufell** [comment]
@a17r kensington might ignore this because of his stubbornness, but I'll explain it to you nonetheless: When you fix/add runtime dependencies, then you need to do a revbump, because otherwise you are relying on [dynamic dependencies](https://wiki.gentoo.org/wiki/Project:Portage/Dynamic_dependencies) which
* are not part of PMS
* cause a lot of trouble (see the link)
* will be deprecated (that's what the portage team said)
* are even optional
* only exist in portage

So for anyone else, this commit doesn't necessarily fix VDB.

**Comment by kensington** [comment]
Without a revbump, the package must be rebuilt when ABI breakage occurs (total rebuilds: 1).
With a revbump, the package must be initially rebuilt, then again when ABI breakage occurs (total rebuilds: 2).

Until there is a policy dictating that we must act in one way or the other, feel free to maintain your packages as you see fit as I will continue mine.

**Comment by hasufell** [comment]
@mgorny does the QA team have such a policy already so we can deal with people like kensington?

**Comment by kensington** [comment]
The current situation is that there is no policy, and both methods of dependency changes are common. If you'd like to see that change, please follow the usual channels instead of making vague threats on GitHub.

**Pull request closed without merging**
