### PR TITLE
sys-boot/grub: fix build with clang

### PR DESCRIPTION
**Pull request by telans**
Closes: https://bugs.gentoo.org/741924
Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Theo Anderson <telans@posteo.de>

### CODE REVIEW

**Comment by floppym** [comment]
Thank you for the patch, but I will probably add a new snapshot instead.

**Comment by telans** [comment]
@floppym do you mind merging this in the meantime?

**Comment by telans** [comment]
@floppym ping

**Comment by floppym** [comment]
This patch is included upstream in grub-2.06~rc1. That makes this PR obsolete.

**Pull request closed without merging**
