### PR TITLE
dev-python/spyder: Version bump 5.0.0

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Bumps spyder to 5.0.0, and bumps some dependencies of spyder.

One new dependency was added to spyder, and it in turn also has one new dependency.

Fixed a small bug in pytest-xvfb where the dependencies were in the wrong DEPEND variable.

This PR looks rather big, but most of the commits just add `<stabilize-allarches/>`.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
pkg_resources.DistributionNotFound: The 'decorator<5' distribution was not found and is required by spyder-kernels
```
I had the latest installed, 5.0.6. Downgrading to 4.4.2-r1 indeed allowed me to get further with spyder, but...
```
$ spyder 
No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
Numeric mode unsupported in the posix collation implementation
Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/spyder", line 33, in <module>
    sys.exit(load_entry_point('spyder==5.0.0', 'gui_scripts', 'spyder')())
  File "/usr/lib/python3.8/site-packages/spyder/app/start.py", line 213, in main
    mainwindow.main(options, args)
  File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2293, in main
    mainwindow = create_window(app, splash, options, args)
  File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2155, in create_window
    main.pre_visible_setup()
  File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 1186, in pre_visible_setup
    plugin_instance.before_mainwindow_visible()
  File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 133, in before_mainwindow_visible
    self.setup_layout(default=False)
  File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 210, in setup_layout
    self.setup_default_layouts('default', settings)
  File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 276, in setup_default_layouts
    layout.set_main_window_layout(self.main, self.get_dockable_plugins())
  File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/api.py", line 381, in set_main_window_layout
    plugin.toggle_view(area["visible"])
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 508, in toggle_view
    self.create_new_client(give_focus=False)
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1007, in create_new_client
    self.connect_client_to_kernel(client, is_cython=is_cython,
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1041, in connect_client_to_kernel
    km, kc = self.create_kernel_manager_and_kernel_client(
  File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1506, in create_kernel_manager_and_kernel_client
    kernel_client.hb_channel.time_to_dead = 25.0
  File "/usr/lib/python3.8/site-packages/jupyter_client/client.py", line 364, in hb_channel
    self._hb_channel = self.hb_channel_class(self.context, self.session, url)
  File "/usr/lib/python3.8/site-packages/qtconsole/util.py", line 64, in __new__
    QClass.__init__(inst)
TypeError: __init__() missing 1 required positional argument: 'context'
QThread: Destroyed while thread is still running
Aborted
```
any ideas? Is my Qt broken?

**Comment by juippis** [comment]
Also 
```
>       file_regression.check(sidebar.prettify(), extension=".html")
E       AssertionError: FILES DIFFER:
E       /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-portage/      pytest-0/test_sidebars_single0/test_build/test_sidebars_single.html
E       /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-portage/      pytest-0/test_sidebars_single0/test_build/test_sidebars_single.obtained.html
E       HTML DIFF: /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-   portage/pytest-0/test_sidebars_single0/test_build/test_sidebars_single.obtained.diff.html
E       ---
E       +++
E       @@ -1,7 +1,7 @@
E        <nav aria-label="Main navigation" class="bd-links" id="bd-docs-nav">
E         <div class="bd-toc-item active">
E          <!-- Specify a startdepth of 0 instead of default of 1 -->
E       -  <p class="caption">
E       +  <p>
E           <span class="caption-text">
E            Caption 1
E           </span>
E       @@ -13,7 +13,7 @@
E            </a>
E           </li>
E          </ul>
E       -  <p class="caption">
E       +  <p>
E           <span class="caption-text">
E            Caption 2
E           </span>

tests/test_build.py:182: AssertionError
================================= short test summary info =================================
FAILED tests/test_build.py::test_sidebars_single - AssertionError: FILES DIFFER:
============================== 1 failed, 12 passed in 4.31s ===============================
 * ERROR: dev-python/pydata-sphinx-theme-0.5.2::gentoo failed (test phase):
 *   pytest failed with python3.7
```

**Comment by AndrewAmmerlaan** [comment]
> Also
> 
> ```
> >       file_regression.check(sidebar.prettify(), extension=".html")
> E       AssertionError: FILES DIFFER:
> E       /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-portage/      pytest-0/test_sidebars_single0/test_build/test_sidebars_single.html
> E       /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-portage/      pytest-0/test_sidebars_single0/test_build/test_sidebars_single.obtained.html
> E       HTML DIFF: /var/tmp/portage/dev-python/pydata-sphinx-theme-0.5.2/temp/pytest-of-   portage/pytest-0/test_sidebars_single0/test_build/test_sidebars_single.obtained.diff.html
> E       ---
> E       +++
> E       @@ -1,7 +1,7 @@
> E        <nav aria-label="Main navigation" class="bd-links" id="bd-docs-nav">
> E         <div class="bd-toc-item active">
> E          
> E       -  <p class="caption">
> E       +  <p>
> E           <span class="caption-text">
> E            Caption 1
> E           </span>
> E       @@ -13,7 +13,7 @@
> E            </a>
> E           </li>
> E          </ul>
> E       -  <p class="caption">
> E       +  <p>
> E           <span class="caption-text">
> E            Caption 2
> E           </span>
> 
> tests/test_build.py:182: AssertionError
> ================================= short test summary info =================================
> FAILED tests/test_build.py::test_sidebars_single - AssertionError: FILES DIFFER:
> ============================== 1 failed, 12 passed in 4.31s ===============================
>  * ERROR: dev-python/pydata-sphinx-theme-0.5.2::gentoo failed (test phase):
>  *   pytest failed with python3.7
> ```

This is an incompatibility with docutils-0.17: https://github.com/pydata/pydata-sphinx-theme/issues/367
Will fix it asap.

**Comment by AndrewAmmerlaan** [comment]
> ```
> pkg_resources.DistributionNotFound: The 'decorator<5' distribution was not found and is required by spyder-kernels
> ```
> 
> I had the latest installed, 5.0.6. Downgrading to 4.4.2-r1 indeed allowed me to get further with spyder, but...
> 
> ```
> $ spyder 
> No QCoreApplication instance found. Application patches not applied. You have to call load_stylesheet function after instantiation of QApplication to take effect. 
> Numeric mode unsupported in the posix collation implementation
> Traceback (most recent call last):
>   File "/usr/lib/python-exec/python3.8/spyder", line 33, in <module>
>     sys.exit(load_entry_point('spyder==5.0.0', 'gui_scripts', 'spyder')())
>   File "/usr/lib/python3.8/site-packages/spyder/app/start.py", line 213, in main
>     mainwindow.main(options, args)
>   File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2293, in main
>     mainwindow = create_window(app, splash, options, args)
>   File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 2155, in create_window
>     main.pre_visible_setup()
>   File "/usr/lib/python3.8/site-packages/spyder/app/mainwindow.py", line 1186, in pre_visible_setup
>     plugin_instance.before_mainwindow_visible()
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 133, in before_mainwindow_visible
>     self.setup_layout(default=False)
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 210, in setup_layout
>     self.setup_default_layouts('default', settings)
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/plugin.py", line 276, in setup_default_layouts
>     layout.set_main_window_layout(self.main, self.get_dockable_plugins())
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/layout/api.py", line 381, in set_main_window_layout
>     plugin.toggle_view(area["visible"])
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 508, in toggle_view
>     self.create_new_client(give_focus=False)
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1007, in create_new_client
>     self.connect_client_to_kernel(client, is_cython=is_cython,
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1041, in connect_client_to_kernel
>     km, kc = self.create_kernel_manager_and_kernel_client(
>   File "/usr/lib/python3.8/site-packages/spyder/plugins/ipythonconsole/plugin.py", line 1506, in create_kernel_manager_and_kernel_client
>     kernel_client.hb_channel.time_to_dead = 25.0
>   File "/usr/lib/python3.8/site-packages/jupyter_client/client.py", line 364, in hb_channel
>     self._hb_channel = self.hb_channel_class(self.context, self.session, url)
>   File "/usr/lib/python3.8/site-packages/qtconsole/util.py", line 64, in __new__
>     QClass.__init__(inst)
> TypeError: __init__() missing 1 required positional argument: 'context'
> QThread: Destroyed while thread is still running
> Aborted
> ```
> 
> any ideas? Is my Qt broken?

This is a bug/incompatibility with jupyter_client-6.1.13: https://github.com/spyder-ide/spyder/issues/15163

**Comment by AndrewAmmerlaan** [comment]
@juippis I fixed the dependencies of spyder-kernels, it should work now :D

**Comment by juippis** [comment]
Now it works, but when I launch spyder, I get an error box stating
```
# Mandatory:
spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)
```
With `dev-python/spyder-kernels-2.0.1::gentoo` installed. The requirement seems to be fulfilled but... ?

**Comment by AndrewAmmerlaan** [comment]
> Now it works, but when I launch spyder, I get an error box stating
> 
> ```
> # Mandatory:
> spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)
> ```
> 
> With `dev-python/spyder-kernels-2.0.1::gentoo` installed. The requirement seems to be fulfilled but... ?

This is a known (slightly annoying) bug that will be fixed in 5.0.1: https://github.com/spyder-ide/spyder/issues/15091

(Actually, I went and looked at the issue again, and there is a patch in the linked PR, I'll rebase and add the patch)

**Comment by AndrewAmmerlaan** [comment]
> > Now it works, but when I launch spyder, I get an error box stating
> > ```
> > # Mandatory:
> > spyder_kernels >=2.0.1,<2.1.0 : 2.0.1 (NOK)
> > ```
> > 
> > 
> > With `dev-python/spyder-kernels-2.0.1::gentoo` installed. The requirement seems to be fulfilled but... ?
> 
> This is a known (slightly annoying) bug that will be fixed in 5.0.1: [spyder-ide/spyder#15091](https://github.com/spyder-ide/spyder/issues/15091)
> 
> (Actually, I went and looked at the issue again, and there is a patch in the linked PR, I'll rebase and add the patch)

Fixed, I ended up opting for sed over a patch, because this particular file has DOS type line endings and we had problems with that before.

**Comment by juippis** [comment]
Yep, that works. WAiting for CI before merging. Thanks!

**Comment by AndrewAmmerlaan** [comment]
Thank You @juippis :)

**Pull request closed without merging**
