### PR TITLE
dev-db/postgresql: use /bin/sh instead of /bin/bash for postgres user

### PR DESCRIPTION
**Pull request by jirutka**
See https://bugs.gentoo.org/show_bug.cgi?id=559884

### CODE REVIEW

**Comment by jirutka** [comment]
The QA check is obviously broken, these issues can’t come from this PR.

**Comment by mgorny** [comment]
You could bother reading the comment at the end of the report which states that the check can't yield clean results if Gentoo developers don't care about the repository being terribly broken.

**Comment by jirutka** [comment]
> You could bother reading the comment at the end of the report

I’ve read this comment and I wrote the last comment just to make clear that these issues are not caused by this PR, to save reviewers’ time.

**Comment by mgorny** [comment]
@grknight

**Comment by grknight** [comment]
Dunno why I was pinged.  I don't have anything to do with postgresql

**Comment by mgorny** [comment]
Ah sorry. @titanofold

**Pull request merged**
