### PR TITLE
virtual/bitcoin-leveldb: correct the || deps order

### PR DESCRIPTION
**Pull request by l29ah**
so the newer versions of leveldb are prefered

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@l29ah could you revbump the ebuild? so it triggers for users with it installed and makes depgraph cleaning easier.

**Comment by l29ah** [comment]
On Mon, Feb 06, 2017 at 11:42:46AM -0800, David Seifert wrote:
> @l29ah could you revbump the ebuild? so it triggers for users with it installed and makes depgraph cleaning easier.

I don't really understand why should i revbump an ebuild that doesn't fix anything runtime-wise. What do you mean by depgraph cleaning?

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by SoapGentoo** [comment]
`|| ( a b c )` gets recorded in the package manager VDB. Now if you want to slim down the depgraph (i.e. `--depclean`), it will try to keep the most preferred dep, which is the first one. But as the old worse one is still in users VDB, this won't allow them to slim down their installations.

**Comment by l29ah** [comment]
On Mon, Feb 06, 2017 at 12:19:45PM -0800, David Seifert wrote:
> `|| ( a b c )` gets recorded in the package manager VDB. Now if you want to slim down the depgraph (i.e. `--depclean`), it will try to keep the most preferred dep, which is the first one. But as the old worse one is still in users VDB, this won't allow them to slim down their installations.

Doesn't matter as they can't be installed together.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by SoapGentoo** [comment]
again, the VDB change needs to be recorded. Please rev bump it (it's just a virtual after all, not libreoffice).

**Comment by l29ah** [comment]
ok

**Comment by mgorny** [comment]
@luke-jr, could you review this? It's a bit outdated but ack on the idea would be enough. I can update it afterwards for the new version and merge.

**Comment by luke-jr** [comment]
Sounds fine. (The order is actually already reversed in the overlay.)

**Pull request closed without merging**
