### PR TITLE
games-util/xboxdrv: fix wireless pad udev match

### PR DESCRIPTION
**Pull request by rkitover**
Add "Xbox 360 Wireless Adapter" to the ID_MODEL_FROM_DATABASE match
patterns so that the wireless Xbox 360 controller adapter is detected.

### CODE REVIEW

**Comment by rkitover** [comment]
If you would like, I can see what other dists have for patches for this and update this PR?

**Comment by chewi** [comment]
It's okay, it's mainly a stack of patches I've written.

**Comment by rkitover** [comment]
Thank you very much for merging!

**Comment by rkitover** [comment]
Oh I was going to ask you something, since you seem to be the right person, if you don't mind...

I noticed that when I use xboxdrv and a game with only controller input, KDE doesn't know that the controller is active and enters display sleep.

Is this something that needs to be fixed in xboxdrv or in KDE?

**Comment by chewi** [comment]
Good question. I certainly used to have this problem under Xfce but not recently. I couldn't say what changed though. I suspect Steam has some handling for this but I've been playing Badlands outside of Steam and it hasn't happened there. Perhaps SDL2 has some handling too.

**Pull request closed without merging**
