### PR TITLE
Add ebuild for xmltv-0.5.67

### PR DESCRIPTION
**Pull request by jasom**

### CODE REVIEW

**Comment by gktrk** [comment]
ebuild.badheader              1
   media-tv/xmltv/xmltv-0.5.67.ebuild: Invalid Gentoo Copyright on line: 1

**Comment by gktrk** [comment]
Just a quick note: you'll find yourself less frustrated if you use a separate branch instead of master to do a pull request ;)

You probably want '|| die' in line 198 after sed.

The commit is signed and looks repoman valid apart form the s/2015/2016/ in the copyright line.

**Comment by jasom** [comment]
Thanks @gktrk I made those fixes

**Comment by gktrk** [comment]
Looks like the metadata.xml has no maintainer information. We need something along the lines of:

<maintainer type="project">
    <email>proxy-maint@gentoo.org</email>
    <name>Proxy Maintainers</name>
</maintainer>
<maintainer type="person">
    <email>your email</email>
    <name>Your Name</name>
    <description>Proxied maintainer. Assign bugs to him.</description>
</maintainer>

@idella would have the exact format for that.

**Comment by jasom** [comment]
@gktrk thanks to @idella I have added the metadata

**Comment by idella** [comment]
merged

**Comment by gktrk** [comment]
:+1: thanks for putting up with my indentation OCD!

**Pull request closed without merging**
