### PR TITLE
dev-util/rustup: add 1.26.0

### PR DESCRIPTION
**Pull request by paul-jewell**
Closes: https://bugs.gentoo.org/918953

### CODE REVIEW

**Comment by thesamesam** [comment]
1. Please sync the live ebuild (9999) too.
2. I'd stick to the existing style wrt whitespace (fixing bad indentation is fine, but I wouldn't change `> x` to `>x` for example, or unindent something if it's a style thing (the pkg_postinst change looks fine, the configure one looks odd though).
3. You've left the automagic cargo-ebuild comments above LICENSE and HOMEPAGE

**Comment by paul-jewell** [comment]
Thanks Sam - I'll attend to the suggestions you have made at the end of the week (I am working in Spain at the moment without my gentoo machine! :))

**Comment by avdb13** [comment]
Please get this merged in main ... `rustup` has been broken for half a year now ... putting the ebuild in a custom repository as a workaround has failed so far.

**Comment by paul-jewell** [comment]
> Please get this merged in main ... `rustup` has been broken for half a year now ... putting the ebuild in a custom repository as a workaround has failed so far. 

I have a copy of my propsed ebuild in a local repository and it installs and works OK, so this should be an interim option. Message me if you want more details about how to set this up.
Regarding merging this change - I need to fix the issues Sam raised, and then I think it will be merged. I will try and get these done in the next 48 hours, but I am working in Spain still and only have remote access to my Gentoo system!

**Comment by paul-jewell** [comment]
> Please get this merged in main ... `rustup` has been broken for half a year now ... putting the ebuild in a custom repository as a workaround has failed so far. 

I have a copy of my propsed ebuild in a local repository and it installs and works OK, so this should be an interim option. Message me if you want more details about how to set this up.
Regarding merging this change - I need to fix the issues Sam raised, and then I think it will be merged. I have made the changes to my repo remotely, but can't commit them to this pull request because I am working in Spain still and only have remote access to my Gentoo system! I am trying to get remote gpg-agent working so I can sign my commit with my yubikey from a distance.

**Comment by thesamesam** [comment]
Can you squash the commits please?

**Comment by paul-jewell** [comment]
Thanks Sam - hopefully this is now OK for you! Both 1.26.0 and 9999 build and run locally on my machine.

**Pull request closed without merging**
