### PR TITLE
media-video/mpv: restrict 0.9.2-r1 to ffmpeg < 3.0 wrt bug 575146

### PR DESCRIPTION
**Pull request by Coacher**
Gentoo-Bugs: 575146

Package-Manager: portage-2.2.27

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by Coacher** [comment]
Ok. Rebased and repushed.

**Comment by Coacher** [comment]
Stupid GitHub removed comments after `git push -f'. Here's the link to it: https://github.com/Coacher/gentoo/commit/8283b49360085e11051d41b49dcf9251643004ab#commitcomment-16215316

**Comment by idella** [comment]
Thanks for pointing that out Coacher. I was wondering if I was going silly.

**Comment by Coacher** [comment]
Thank you very much, @idella.

**Pull request merged**
