### PR TITLE
games-fps/gzdoom: Version bump to 4.4.2

### PR DESCRIPTION
**Pull request by vilhelmgray**
This pull request also introduces the new media-libs/zmusic library package.

### CODE REVIEW

**Comment by chewi** [comment]
Bleugh, really not liking the amount of bundling going on in zmusic. We already have packages for dumb, game-music-emu, and timidity++. Ideally the rest should be packaged too but we'd have to evaluate the cost of that. I'm perplexed by the presence of both timidity *and* timidity++, given that one is a fork of the other. I guess [this wiki page](https://doomwiki.org/wiki/TiMidity) explains it.

**Comment by vilhelmgray** [comment]
I wholeheartedly agree with you on the bundling problem; the reason GZDoom takes so absurdly long to compile compared to the other DOOM source port packages is because users have to compiled all these static bundled libraries.

Unfortunately, the upstream GZDoom team has some reservations against the concept of dynamic linking with external libraries. You can see some of the discussion and their reasons in this thread: https://forum.zdoom.org/viewtopic.php?f=2&t=64633

This makes it difficult to submit patches to unbundle these libraries to upstream GZDoom because the developer's opposition to dynamic linkage is philosophical rather than technical. Given that the upstream team expects these libraries to be bundled, they occasionally make their own changes to the libraries' respective code -- thus effectively forking each of these projects -- thus further complicating things.

It'll be good however to do an investigation at some point to determine which of the bundled libraries have actually diverged from their respective upstreams versus those which have remained unchanged. We can then remove the unchanged bundled libraries and instead link to the shared objects provided by the system.

**Comment by chewi** [comment]
Heh damn, that's quite some thread. I get that they want to avoid needless bug reports but we, as the distribution, will take the responsibility of ensuring this stuff fits together, even if it means we have to carry the patches ourselves.

I did consider custom patching. It sounds like their timidity is custom. That's fine, we don't package it anyway. At first glance, the others we have packaged look largely unmodified but then again, they may have included modifications in the initial commit. I'll have to compare.

**Comment by vilhelmgray** [comment]
> Heh damn, that's quite some thread. I get that they want to avoid needless bug reports but we, as the distribution, will take the responsibility of ensuring this stuff fits together, even if it means we have to carry the patches ourselves.
> 
> I did consider custom patching. It sounds like their timidity is custom. That's fine, we don't package it anyway. At first glance, the others we have packaged look largely unmodified but then again, they may have included modifications in the initial commit. I'll have to compare.

I took a look at the GZDoom bundled libraries:

- **bzip2**, **jpeg**, and **zlib** can be provided by system libraries and GZDoom already supports this; no change necessary on own end.
- I think lzma can also work as a system library with some minor changes to the GZDoom CMake file; see also <https://bugs.gentoo.org/733978> for header installation request.
- I think **gdtoa** came originally from <https://www.netlib.org/fp/gdtoa.tgz> but it's been modified by the GZDoom team with several changes to accommodate various compilers. We can consider this a fork because it looks the original gdtoa upstream hasn't made a new release in at least 12 years.
- [GZDoom CMake comments](https://github.com/coelckers/gzdoom/blob/86bac6bfcf38b0150e2d5965f0b59bf82aa1126a/CMakeLists.txt#L191) indicate the bundled **asmjit** is required due to changes **asmjit** upstream has not yet taken; I haven't verified if this comment is outdated, but I'm assuming it can be trusted and GZDoom bundled **asmjit** is effectively a fork.
- I don't believe that the GZDoom team has modified the bundled **glslang** (yet) -- they seem to be using **glslang version 8.13.3559**; there is an [upstream PR to fixup the CMake configuration exports](https://github.com/KhronosGroup/glslang/pull/1978), after which it'll be simple to modify the GZDoom CMake file to find the system **glslang**.

**Comment by vilhelmgray** [comment]
> I did consider custom patching. It sounds like their timidity is custom. That's fine, we don't package it anyway. At first glance, the others we have packaged look largely unmodified but then again, they may have included modifications in the initial commit. I'll have to compare.

I took a look at the ZMusic bundled libraries:

- **oplsynth**, **timidity**, **timidityplus**, and **wildmidi** have been modified from their respective upstreams; I suppose we can consider these forks.
- The rest appear to be untouched when I casually looked over them, but they are older versions compared to their respective upstreams; it might be possible to replace some of these with the respective Gentoo packages for them.

**Comment by vilhelmgray** [comment]
>     * I think lzma can also work as a system library with some minor changes to the GZDoom CMake file; see also https://bugs.gentoo.org/733978 for header installation request.

I did some more digging and discovered that the only GZDoom source files that appear to depend on **lzma** are `src/common/utility/files_decompress.cpp`, `src/common/filesystem/file_7z.cpp`, and `tools/zipdir/zipdir.c`.

The LZMA API GZDoom is using is legacy and no longer supported by upstream. We will have to migrate this code to the modern XZ API in order to use the `lzma.h` header file provided by Gentoo's **app-arch/xz-utils** package.

I'm not familiar with either API, so I don't think I'll be able to migrate GZDoom for this version 4.4.2 release. Perhaps some time in the future I might do so.

**Comment by chewi** [comment]
Thanks for all this, I do find it very interesting, as I'm still working with GZDoom myself, just short on time as usual.

**Comment by vilhelmgray** [comment]
No worries, I'm in the same boat just going through these when free time pops up in my schedule.

The only remaining items left are to see if the bundled libraries for ZMusic can be swapped out for the new versions provided by Gentoo. I'm not sure when I'll get around to testing that, but maybe a couple weeks from now -- unless you few the urge to merge this PR as-is, and we can make the changes as a revision bump later if there are any.

**Comment by chewi** [comment]
I thought I could at least unbundle Dumb but they've used loads from an internal header. :facepalm: We could keep using the bundled header but that could easily break later. Oh well.

**Pull request closed without merging**
