### PR TITLE
dev-java/openjdk: openjdk8 source ebuild

### PR DESCRIPTION
**Pull request by gyakovlev**
Tested on `~amd64` only for now, will soon test on ppc64 and arm*

not sure what to do with build variants, are they even needed?

builds fine with icedtea and with itself, jbootstrap works.

minimal runtime testing, but PyCharm seems to be working fine.

### CODE REVIEW

**Comment by gyakovlev** [comment]
looks like there's something happening with ca-certs. nothing is truster. will look into it

**Comment by fordfrog** [comment]
so i tried to build it:

# emerge -va openjdk:8

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  NS    ] dev-java/openjdk-8.192_p26:8::local [11.0.1_p13:11::gentoo] USE="alsa doc gentoo-vm jbootstrap jvm_variant_client jvm_variant_server source webstart -debug -examples -headless-awt -jvm_variant_core -jvm_variant_minimal -jvm_variant_zero -nsplugin (-pch) (-selinux)" 0 KiB

and it failed with this:
...
configure: error: You cannot build a client JVM for a 64-bit machine.
...

**Comment by fordfrog** [comment]
i got another error, probably because the 'doc' use flag:

```
# USE="-jvm_variant_client" emerge -va openjdk:8

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild  NS    ] dev-java/openjdk-8.192_p26:8::local [11.0.1_p13:11::gentoo] USE="alsa doc gentoo-vm jbootstrap jvm_variant_server source webstart -debug -examples -headless-awt -jvm_variant_client -jvm_variant_core -jvm_variant_minimal -jvm_variant_zero -nsplugin (-pch) (-selinux)" 0 KiB
...
 * XATTR_PAX marking -m /var/tmp/portage/dev-java/openjdk-8.192_p26/image/usr/lib64/openjdk-8/jre/bin/tnameserv with paxctl-ng
 * XATTR_PAX marking -m /var/tmp/portage/dev-java/openjdk-8.192_p26/image/usr/lib64/openjdk-8/jre/bin/unpack200 with paxctl-ng
Traceback (most recent call last):
  File "/usr/lib/portage/python3.7/doins.py", line 611, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.7/doins.py", line 602, in main
    os.path.dirname(source)):
  File "/usr/lib/portage/python3.7/doins.py", line 450, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.7/doins.py", line 386, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.7/doins.py", line 195, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'/var/tmp/portage/dev-java/openjdk-8.192_p26/work/jdk8u-jdk8u192-b26/build/*-release/images/docs/*'
 * ERROR: dev-java/openjdk-8.192_p26::local failed (install phase):
 *   doins failed
```

**Comment by gyakovlev** [comment]
will try `doc` use later, haven't really tested yet.

**Comment by fordfrog** [comment]
this compiled fine for me:

\# USE="-jvm_variant_client -doc" emerge -va openjdk:8

These are the packages that would be merged, in order:

Calculating dependencies... done!
[ebuild   R    ] dev-java/openjdk-8.192_p26:8::local  USE="alsa gentoo-vm jbootstrap jvm_variant_server source webstart -debug -doc -examples -headless-awt -jvm_variant_client -jvm_variant_core -jvm_variant_minimal -jvm_variant_zero -nsplugin (-pch) (-selinux)" 0 KiB

**Comment by joakim-tjernlund** [comment]
Please backport https://bugs.openjdk.java.net/browse/JDK-8204142 too.
Needed for webstart.

**Comment by gyakovlev** [comment]
@joakim-tjernlund I can't backport it myself.
 here's bug for jdk8 https://bugs.openjdk.java.net/browse/JDK-8217439
if it's going to be fixed and merged I'll try to include that patch.

**Comment by joakim-tjernlund** [comment]
> @joakim-tjernlund I can't backport it myself.
> here's bug for jdk8 https://bugs.openjdk.java.net/browse/JDK-8217439
> if it's going to be fixed and merged I'll try to include that patch.

OK, but can we have the ebuild in Gentoo repo now ?

**Comment by gyakovlev** [comment]
@joakim-tjernlund as soon as it's ready, it needs just a bit more work. probably later this week.

**Comment by gyakovlev** [comment]
thanks, I use custom certs at work, will check it how it behaves. I know `update-ca-certificates` is supposed to copy those local certs somewhere but it's been a while since I updated certs.

**Comment by joakim-tjernlund** [comment]
Yes, the sum of all cerst are in /etc/ssl/certs/
There is an include all certs there: ca-certificates.crt
It should include  all certs, provide you have run update-ca-certificates each time
you have modified /usr/local/share/ca-certificates

**Comment by gyakovlev** [comment]
I wonder if it's possible to use the summary cert from /etc/ssl, because it may exclude some stuff people opted-out via config files. I'll check later. Please open bugs on bugzilla if you find something that needs to be fixed.

**Comment by joakim-tjernlund** [comment]
The ca-certificates.crt is the summary of all in the dir. That said I think it would be easier to just do
for c in "${EPREFIX}"/etc/ssl/certs/*.pem; do
    openssl x509 -text -in "${c}" >> all.crt || die
done

That will keep the interface fro the perl script.

**Comment by joakim-tjernlund** [comment]
Also, the /etc/ssl/certs/ is what all apps use, firefox etc.
It does not matter how it got there. An admin may have installed certs there manually as well.

**Comment by joakim-tjernlund** [comment]
Here is a diff I have, not sure if that is relevant though:
`diff -u openjdk-bin-8.env.sh /usr/portage/dev-java/openjdk-bin/files/openjdk-bin-8.env.sh 
--- openjdk-bin-8.env.sh	2019-01-08 14:17:54.000000000 +0100
+++ /usr/portage/dev-java/openjdk-bin/files/openjdk-bin-8.env.sh	2019-02-01 10:39:28.000000000 +0100
@@ -1,4 +1,4 @@
-# Copyright 1999-2018 Gentoo Authors
+# Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
 VERSION="AdoptOpenJDK ${PV}"
@@ -7,11 +7,10 @@
 JAVAC="\${JAVA_HOME}/bin/javac"
 PATH="\${JAVA_HOME}/bin"
 ROOTPATH="\${JAVA_HOME}/bin"
-LDPATH="\${JAVA_HOME}/jre/lib/$(get_system_arch)/:\${JAVA_HOME}/jre/lib/$(get_system_arch)/server/"
-MANPATH=""
+LDPATH="\${JAVA_HOME}/lib/:\${JAVA_HOME}/lib/server/"
+MANPATH="\${JAVA_HOME}/man"
 PROVIDES_TYPE="JDK JRE"
-PROVIDES_VERSION="${SLOT}"
-# Taken from icedtea-bin:8
-BOOTCLASSPATH="\${JAVA_HOME}/jre/lib/resources.jar:\${JAVA_HOME}/jre/lib/rt.jar:\${JAVA_HOME}/jre/lib/jsse.jar:\${JAVA_HOME}/jre/lib/jce.jar:\${JAVA_HOME}/jre/lib/charsets.jar"
+PROVIDES_VERSION="1.${SLOT}"
+BOOTCLASSPATH="\${JAVA_HOME}/jre/lib/resources.jar:\${JAVA_HOME}/jre/lib/rt.jar:\${JAVA_HOME}/jre/lib/jsse.jar:\${JAVA_HOME}/jre/lib/jce.jar:\${JAVA_HOME}/jre/lib/charsets.jar:\${JAVA_HOME}/jre/lib/jfr.jar"
 GENERATION="2"
 ENV_VARS="JAVA_HOME JDK_HOME JAVAC PATH ROOTPATH LDPATH MANPATH"
`

**Comment by joakim-tjernlund** [comment]
hmm, how do I enable gentoo-vm USE(in my profile)?

**Comment by fordfrog** [comment]
@joakim-tjernlund this should override the mask (adjust for your needs):
```
# cat /etc/portage/profile/package.use.mask/multi 
# java
dev-java/openjdk:11 -gentoo-vm
dev-java/openjdk-bin:11 -gentoo-vm
dev-java/oracle-jdk-bin:11 -gentoo-vm
```

**Comment by joakim-tjernlund** [comment]
@gyakovlev, you are not using /etc/ssl/certs in latest icedtea, did you forget ?

**Pull request closed without merging**
