### PR TITLE
net-irc/telepathy-idle: fix 100% cpu usage and tests

### PR DESCRIPTION
**Pull request by okias**
Added latest fixes from 0.2.0 branch.
- fixes tests
- fixes extreme CPU usage.
It's unlikely that new version (0.2.1 nor 1.x) will be released soon, so
it's really good idea merge these patches.

Closes: https://bugs.gentoo.org/636576
Closes: https://bugs.gentoo.org/684832

Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by a17r** [comment]
* Package already is EAPI-7
* What exactly is it fixing in src_prepare?
* If it only fixes a test, why revbump?

**Comment by okias** [comment]
>     * Package already is EAPI-7
> 
>     * What exactly is it fixing in src_prepare?
> 
>     * If it only fixes a test, why revbump?

I updated description of Pull from commit. Since my first PullReq there been changes to ebuild.

**Comment by a17r** [comment]
Then please change your git commit message title to describe your major fix accordingly, `bump r2` is not it. ;)

**Comment by mattst88** [comment]
I dropped the gcc warning fix, because I think that should be investigated and not papered over.

Thanks :)

**Pull request closed without merging**
