### PR TITLE
dev-util/radare2: bump to 2.0.0

### PR DESCRIPTION
**Pull request by stkw0**
Also:
- Added zsh-completion USE
- Update live ebuild
- Update description of the new ebuild and live ebuild 
- Add ~arm keyword (test passed on my raspberry pi)
- Closes bug 633892 (but without adding ~arm64 keyword as it depends on capstone which don't have ~arm64 keyword)

### CODE REVIEW

**Comment by trofi** [comment]
Looks good. I'd like two more changes here:
- add ~arm64 into `KEYWORDS` (https://bugs.gentoo.org/633892)
- move `default` call up to the first line in `src_install()` if it does not make the difference. That way it will be clear we extend `src_install()` and don't override it. I don't know why I did put it last :)

**Comment by dlrobertson** [comment]
> Closes bug 633892 (but without adding ~arm64 keyword as it depends on capstone which don't have ~arm64 keyword)

Ah, totally my bad. I forgot to add it to the patch in [633892](https://bugs.gentoo.org/633892), but I have `~arm64` added to the `KEYWORDS` for `dev-util/capstone`. Also, this shouldn't be a problem if the `system-capstone` use flag is not enabled.

**Comment by stkw0** [comment]
@trofi I applied your requested changes. I saw you are the maintainer of capstone too, so I suppose we don't need to open an issue for adding ~arm64

**Comment by trofi** [comment]
Pulled and added `~arm64` keywords to capstone. Thank you!

**Comment by trofi** [comment]
Pulled as-is and keyworded capstone.

Thanks all!

**Pull request closed without merging**
