### PR TITLE
[proxy-maint, please do not merge] x11-wm/awesome: add live 3.5.9999 version, multiple fixes

### PR DESCRIPTION
**Pull request by Coacher**
Hello.

Though I am not going to maintain x11-wm/awesome any longer as per #772, during my short time of dealing with the current awesome ebuilds I think I've managed to fix several problems.

I offer my changes to the current awesome maintainers for review. If you don't find them useful, then please just close this PR.

### CODE REVIEW

**Comment by Coacher** [comment]
CC @maksbotan, @krigstack, @wired.

**Comment by idella** [comment]
So these patches prepare by Coacher are offered to those who DO maintain x11-wm/awesome as they see fit.

**Comment by monsieurp** [comment]
@Coacher my friend, did you ping the x11-wm/awesome maintainers to have them review this PR?

**Comment by Coacher** [comment]
>@Coacher my friend, did you ping the x11-wm/awesome maintainers to have them review this PR?

See https://github.com/gentoo/gentoo/pull/774#issuecomment-178564098

**Comment by Coacher** [comment]
CC @maksbotan, @krigstask, @wired one more time.
This is going nowhere. I'll remove my branch and close this PR in a week.

**Comment by krigstask** [comment]
@Coacher, sorry, the situation with awesome maintenance is grim, as you can see.  I fully understand your frustration, and I have to fork your branch for all your hard work not to be in vain. I hope it will make its way into the tree ASAP.

**Pull request closed without merging**
