### PR TITLE
Adding ROCm packages version 5.1.3

### PR DESCRIPTION
**Pull request by orbitgray**

### CODE REVIEW

**Comment by heroxbd** [comment]
Is this superseded by https://github.com/gentoo/gentoo/pull/27219 ?

**Comment by orbitgray** [comment]
> Is this superseded by #27219 ?

I don't think that change does the same. But think I've seen version bump in main.

**Comment by heroxbd** [comment]
Sergii Parubochyi ***@***.***> writes:

> I don't think that change does the same. But think I've seen version
> bump in main.

Thanks Sergii!  Sorry I did not notice your PR until yesterday.  I
should have based the bumps on your commits.

**Comment by orbitgray** [comment]
> Sergii Parubochyi ***@***.***> writes:
> I don't think that change does the same. But think I've seen version bump in main.
> Thanks Sergii! Sorry I did not notice your PR until yesterday. I should have based the bumps on your commits.

No worries, glad it was updated.

**Pull request closed without merging**
