### PR TITLE
net-irc/znc: Remove l10n/linguas variables.

### PR DESCRIPTION
**Pull request by DarthGandalf**
Simply install all available locales instead.

### CODE REVIEW

**Comment by sbraz** [comment]
I'm not sure what to think about this change. What was the reason you initially introduced the locale-related code?

**Comment by DarthGandalf** [comment]
Because I thought it's a good idea. There was a support for linguas use-flags in portage, and there are other packages which use that.
But:
* Neither linguas_ nor l10n_ are in USE_EXPAND now, so that `emerge -p znc` says nothing what locales are installed
* It adds maintainance burden, because list of locales changes over time, and because right now the way how it's handled isn't correct anymore either - one more file needs to be deleted per locale, and more to come in future.

**Comment by sbraz** [comment]
Oh I didn't know that they did not include it any more, then I guess it makes no sense to keep it :)

**Comment by DarthGandalf** [comment]
https://archives.gentoo.org/gentoo-dev/message/29b00839ba5be715d883412011d8a421
It would be possible to either continue using LINGUAS as is with l10n.eclass, or to switch to use L10N manually, but the second point still stands.

**Pull request closed without merging**
