### PR TITLE
media-sound/qmidiroute: Patch away unnecessary check for QtOpenGL.

### PR DESCRIPTION
**Pull request by lilrc**
Gentoo-Bug: 623414
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by a17r** [comment]
Yikes, you have found an EAPI=2 ebuild. Would you mind porting to EAPI 6 as well? ;)

**Comment by lilrc** [comment]
Sure, I'll bump EAPI as soon as I get home from work today! Should I bump 0.3.0 as well? Do I need to revbump at the same time?

**Comment by a17r** [comment]
No bump necessary, and don't bother with 0.3.0 which can be dropped as soon as 0.4.0 goes stable.

**Comment by aballier** [comment]
merged, thanks!

**Pull request closed without merging**
