### PR TITLE
app-editors/neovim: add 0.9.2

### PR DESCRIPTION
**Pull request by listout**

### CODE REVIEW

**Comment by listout** [comment]
Dependent on the following PR:
- https://github.com/gentoo/gentoo/pull/32708
- https://github.com/gentoo/gentoo/pull/32709

**Comment by thesamesam** [comment]
Please rebase now the prereqs are in, thanks!

**Comment by listout** [comment]
> Please rebase now the prereqs are in, thanks!

Done.

**Comment by thesamesam** [comment]
Please sync live too.

**Pull request closed without merging**
