### PR TITLE
games-board/cockatrice: version bump to 20160506

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Hello,
this is a big bump I brewed on my overlay (https://github.com/GuillaumeSeren/gentoo-overlay),
I used it for some time now and it works well.

As it is my first commit in official please let me know if I made something wrong.

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I am not sure to understand well the result of the QA,
I have upgraded the banch, but I will search for more documentation about the QA.

**Comment by GuillaumeSeren** [comment]
According from what I've seen on other PR the QA error are not related to my PR,
can anyone confirm this / review the PR ?

@gentoo/games-board

**Comment by monsieurp** [comment]
Hi. If you read https://wiki.gentoo.org/wiki/Gentoo_Github before filing this PR, you'd know what those warnings mean and you'd know how to correctly format commit messages.

**Comment by GuillaumeSeren** [comment]
@monsieurp Thank you for the feedback,
I recheck the doc and I supposed I made some errors, I rebased my banch and changed the commit message, hope it will be good !

Guillaume

**Comment by GuillaumeSeren** [comment]
'All checks have passed' \o/

Can anyone have a feedback, something to fix on the ebuild ?

**Comment by monsieurp** [comment]
@GuillaumeSeren Your changes look good. I'll merge your PR later on.

**Comment by GuillaumeSeren** [comment]
@monsieurp :+1:

**Comment by GuillaumeSeren** [comment]
Yeah !

**Pull request closed without merging**
