### PR TITLE
app-crypt/argon2: Version bump

### PR DESCRIPTION
**Pull request by sonOfRa**
Also delete some old versions

Package-Manager: Portage-2.3.19, Repoman-2.3.6
Closes: https://bugs.gentoo.org/641390

### CODE REVIEW

**Comment by candrews** [comment]
Can you please separate the changes in that one commit into two commits, one for the version bump, then one for dropping the old versions?

I also see you added the `~arm64` keyword - did you test on `~arm64`? If so, can you please provide the build log? If not, please remove the keyword.

You don't need to `inherit multilib` - `get_libdir` is provided by EAPI=6.

**Comment by sonOfRa** [comment]
I haven't tested on arm64 no, apparently I already had the keyword set on the older versions. I will remove it because I do not have any hardware available to test it on. Should I also drop the ~arm64 keyword on the existing version 20161029-r1 that I'm keeping around, because it was not tested on that release either. If yes, should that be 20161029-r2?

**Comment by candrews** [comment]
Okay, looking at the git log, the keyword was added in 58bed4b2532281f5421e6238762c1140584db258 so it's okay. Keep the `~arm64` keyword, my apologies for the confusion.

**Comment by candrews** [comment]
2 small suggestions:
* `sed` can have `-e` specified multiple times, so you don't need 4 `sed`s, just use one
* wrap `$(get_libdir)` in `"` - just in case it has spaces or something (better to be safe than sorry)

**Comment by sonOfRa** [comment]
Rebased the requested changes into d07f5a7

**Comment by candrews** [comment]
Thank you!

1ade9cbd223a4d7f6237e5fe3d22c37a08edbab3
bcbd83cd3a4958c79e9efe39940376cb32345aef

**Pull request closed without merging**
