### PR TITLE
mail-client/roundcube: Add 1.5_rc

### PR DESCRIPTION
**Pull request by Philippe23**
mail-client/roundcube: Add 1.5_rc

 - Now requires `>=dev-lang/php-5.5.0`
 - `intl` required to be enabled on `dev-lang/php`
 - Added `exif fileinfo zip` USE flags

Bug: https://bugs.gentoo.org/782883
Closes: 19700
Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Philippe Chaintreuil <gentoo_bugs_peep@parallaxshift.com>

---
Helpful links:
 - 1.5_beta's Release Notes: https://github.com/roundcube/roundcubemail/releases/tag/1.5-rc
 - 1.5_beta's `INSTALL` readme: https://github.com/roundcube/roundcubemail/blob/1.5-rc/INSTALL
---

1.4.11 -> 1.5_rc diff for convenience:
```diff
--- roundcube-1.4.11.ebuild     2021-03-24 14:40:05.619354394 -0400
+++ roundcube-1.5_rc.ebuild     2021-07-06 11:30:31.498856135 -0400
@@ -16,7 +16,7 @@
 # for bundled PEAR components, googiespell and utf8.class.php
 LICENSE="GPL-3 BSD PHP-2.02 PHP-3 MIT public-domain"

-IUSE="change-password enigma ldap mysql postgres sqlite ssl spell"
+IUSE="change-password enigma exif fileinfo ldap mysql postgres sqlite ssl spell zip"
 REQUIRED_USE="|| ( mysql postgres sqlite )"

 # this function only sets DEPEND so we need to include that in RDEPEND
@@ -24,7 +24,7 @@

 RDEPEND="
        ${DEPEND}
-       >=dev-lang/php-5.4.0[filter,gd,iconv,json(+),ldap?,pdo,postgres?,session,sqlite?,ssl?,unicode,xml]
+       >=dev-lang/php-5.5.0[exif?,fileinfo?,filter,gd,iconv,intl,json(+),ldap?,pdo,postgres?,session,sqlite?,ssl?,unicode,xml,zip?]
        virtual/httpd-php
        change-password? (
                dev-lang/php[sockets]
@@ -52,7 +52,7 @@
 else
        SRC_URI="https://github.com/${PN}/${MY_PN}/releases/download/${MY_PV}/${MY_P}-complete.tar.gz"
        S="${WORKDIR}/${MY_P}"
-       KEYWORDS="amd64 arm ~hppa ppc ppc64 sparc x86"
+       KEYWORDS="~amd64 ~arm ~hppa ~ppc ~ppc64 ~sparc ~x86"
 fi

 src_unpack() {
@@ -71,7 +71,7 @@
 src_install() {
        webapp_src_preinst

-       dodoc CHANGELOG INSTALL README.md UPGRADING
+       dodoc CHANGELOG.md INSTALL README.md UPGRADING SECURITY.md

        insinto "${MY_HTDOCSDIR}"
        doins -r [[:lower:]]* SQL
```

### CODE REVIEW

**Comment by candrews** [comment]
Can you please update the -9999 ebuild too?

**Comment by Philippe23** [comment]
1.5_rc was released, so I've updated this to reflect that build instead.

**Comment by candrews** [comment]
The `fileinfo` use flag description isn't really useful... Could you update it to say why a user would want to enable it? What does it do for roundcube?

Also, can you please update the -9999 ebuild?

**Comment by Philippe23** [comment]
> The `fileinfo` use flag description isn't really useful... Could you update it to say why a user would want to enable it? What does it do for roundcube?

Think I just copied the fileinfo text from `dev-php/PEAR-HTTP_Request2`.  :-)

Updated to: "Use the dev-lang/php fileinfo extension guess the mime_type of attachments" 

> Also, can you please update the -9999 ebuild?

Done.

> Finally, in the commit message, please `Closes:` the bug instead of `Bug:` reference it

Done.

**Comment by candrews** [comment]
Thank you!

**Comment by Philippe23** [comment]
Thanks, @candrews!

**Pull request closed without merging**
