### PR TITLE
gnome-base/gnome-settings-daemon: Version bump to 45_rc

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
It looks to me like the nss and gcr deps changed.

**Comment by flint2** [comment]
> It looks to me like the nss and gcr deps changed.

I think we don't use it:

src_configure() 
```
		-Dgcr3=false
```

meson.build
```
+  if get_option('gcr3')
+    smartcard_deps = dependency('gck-1', version: '>= 3.36')
+  else
+    smartcard_deps = dependency('gck-2')

```

**Comment by mattst88** [comment]
No, I think we need to update things for `IUSE=smartcard`. We currently have `smartcard? ( >=dev-libs/nss-3.11.2 )`, but the `pkgdiff -b` output shows:

```
 # smartcard section
 enable_smartcard = get_option('smartcard')
 if enable_smartcard
-  nss_dep = dependency('nss', version: '>= 3.11.2')
-
-  system_nssdb_dir = get_option('nssdb_dir')
-  if system_nssdb_dir == ''
-    system_nssdb_dir = join_paths(gsd_sysconfdir, 'pki', 'nssdb')
+  if get_option('gcr3')
+    smartcard_deps = dependency('gck-1', version: '>= 3.36')
+  else
+    smartcard_deps = dependency('gck-2')
   endif
 endif
```

So it needs to switch from nss to gcr:4. See https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/b7121e3814d83b27799e2163a13722dad87d0d36 for the upstream commit.

**Comment by flint2** [comment]
> No, I think we need to update things for `IUSE=smartcard`. We currently have `smartcard? ( >=dev-libs/nss-3.11.2 )`, but the `pkgdiff -b` output shows:
> 
> ```
>  # smartcard section
>  enable_smartcard = get_option('smartcard')
>  if enable_smartcard
> -  nss_dep = dependency('nss', version: '>= 3.11.2')
> -
> -  system_nssdb_dir = get_option('nssdb_dir')
> -  if system_nssdb_dir == ''
> -    system_nssdb_dir = join_paths(gsd_sysconfdir, 'pki', 'nssdb')
> +  if get_option('gcr3')
> +    smartcard_deps = dependency('gck-1', version: '>= 3.36')
> +  else
> +    smartcard_deps = dependency('gck-2')
>    endif
>  endif
> ```
> 
> So it needs to switch from nss to gcr:4. See https://gitlab.gnome.org/GNOME/gnome-settings-daemon/-/commit/b7121e3814d83b27799e2163a13722dad87d0d36 for the upstream commit.


Oh, I missed this:
```
+  else
+    smartcard_deps = dependency('gck-2')
```

Now is depending on >=app-crypt/gcr-4.0.0:4 that provides lib gck-2

**Pull request closed without merging**
