### PR TITLE
app-dicts/myspell-en: add 20240501

### PR DESCRIPTION
**Pull request by kuraga**
~20240301~ ~20240401~ 20240501 version of the English dictionaries for myspell is out: https://extensions.libreoffice.org/extensions/english-dictionaries

Closes: https://bugs.gentoo.org/926044

### CODE REVIEW

**Comment by kuraga** [comment]
20240401 version of the English dictionaries for myspell is out: https://extensions.libreoffice.org/extensions/english-dictionaries

Updated.

**Comment by kuraga** [comment]
20240501 version of the English dictionaries for myspell is out: https://extensions.libreoffice.org/extensions/english-dictionaries

Updated.

**Comment by Jamim** [comment]
_Hello @kuraga,_

Would you mind amending the commit message and PR's title/description? Now they mention older versions of the package.
Hope your changes will be merged soon.

_Best regards!_

**Comment by kuraga** [comment]
@Jamim , thanks!

**Review by juippis — APPROVED** [review]

**Comment by kuraga** [comment]
@juippis, thanks!
`20240601` version has been bumped yesterday.
I've intended to push it tomorrow. (For several hours is also possible :).) Would you look at it, please?

**Comment by juippis** [comment]
I pinged you in the other PR, could you check whether the changes from there can be applied to the next release? No promises when I'll take a look, but getting there slowly...

**Pull request closed without merging**
