### PR TITLE
app-editors/ghostwriter: add 2.1.6

### PR DESCRIPTION
**Pull request by stkw0**

### CODE REVIEW

**Comment by a17r** [comment]
Why not keep 2.1.4 and stabilise it?

**Comment by stkw0** [comment]
I didn't had any good reason. Version 2.1.5 and 2.1.6 have bug fixes so I thought it didn't make sense to keep a version with known bugs while there is a never version which fixes them. To be honest I sometime doubt about when to stabilize a package, how many versions of a package should be kept in the repository and similar questions. Is there an official policy about this?

**Comment by a17r** [comment]
It is the maintainer's decision. How many bugs do you think currently stable 2.0.2 will have compared to 2.1.4?

**Comment by stkw0** [comment]
mmm tbh I never thought much about stabilization I will try to take a better approach to it because I was not usually very proactive in stabilizing packages (which retrospectively I see it's wrong because users using stable packages will be impacted negatively).

**Comment by a17r** [comment]
Looks like this project is on track to move to kde.org. So I might as well take care of this PR.

https://mail.kde.org/pipermail/kde-devel/2022-September/001351.html

**Review by a17r — APPROVED** [review]

**Pull request closed without merging**
