### PR TITLE
dev-python/jaraco-functools: bump to 1.13, add doc, changelog

### PR DESCRIPTION
**Pull request by sbraz**
Not much changed: https://github.com/jaraco/jaraco.functools/compare/1.12...1.13

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Are we missing a dep?

```
 	install_requires=[
+		'more_itertools',
 	],
```

**Comment by sbraz** [comment]
Absolutely, I don't know how I missed it, fixed :)

**Comment by gktrk** [comment]
python2 tests fails for me, do you reproduce this? :

```
>>> Test phase: dev-python/jaraco-functools-1.13
 * python2_7: running distutils-r1_run_phase python_test
================================================================================ test session starts =================================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.30, pluggy-0.3.1
rootdir: /var/tmp/portage/dev-python/jaraco-functools-1.13/work/jaraco.functools-1.13, inifile: pytest.ini
collected 7 items / 2 errors

jaraco/functools.py .......

======================================================================================= ERRORS =======================================================================================
_________________________________________________________________________ ERROR collecting test_functools.py _________________________________________________________________________
test_functools.py:5: in <module>
    from unittest import mock
E   ImportError: cannot import name mock
_________________________________________________________________________ ERROR collecting test_functools.py _________________________________________________________________________
test_functools.py:5: in <module>
    from unittest import mock
E   ImportError: cannot import name mock
========================================================================= 7 passed, 2 error in 0.16 seconds ==========================================================================
```

**Comment by sbraz** [comment]
You probably forgot to emerge the backport dependency.

**Comment by gktrk** [comment]
Right, I installed the lru-cache backport but missed the mock. sorry about that. LGTM.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/4c8e16e...deadb00. Thanks!

**Pull request closed without merging**
