### PR TITLE
git-r3: fetch pullrequest refs on mirror clone type

### PR DESCRIPTION
**Pull request by fepitre**
Signed-off-by: Frédéric Pierret (fepitre) <frederic.pierret@qubes-os.org>

### CODE REVIEW

**Review by mgorny — APPROVED** [review]
I suppose no harm in that.

**Comment by mgorny** [comment]
Could you send the patch to `gentoo-dev` for completeness?

**Comment by fepitre** [comment]
> Could you send the patch to `gentoo-dev` for completeness?

Sure. Just done it.

**Comment by fepitre** [comment]
@mgorny do you know if there is something more to do for merging this PR?

**Comment by mgorny** [comment]
I see that a week has passed with no replies, so I'll merge it now.

**Pull request closed without merging**
