### PR TITLE
dev-lang/spidermonkey: add 102.8.0 & enable-optimize

### PR DESCRIPTION
**Pull request by juippis**

### CODE REVIEW

**Comment by mattst88** [comment]
Just did some tests -- the `nm -CDg /usr/lib64/libmozjs-102.so.0` output is identical (modulo the addresses) for

- `--disable-optimize`
 - `--disable-optimize`, `CFLAGS=-g`, 
- `--enable-optimize`

The output is only different when using `--enable-optimize` and `CFLAGS=-g`.

I don't know what symbols are supposed to be ABI and what reverse dependencies might link to. I think we should probably just check whether reverse dependencies built against spidermonkey with `--enable-optimize`, `CFLAGS=-g` work with spidermonkey built without `CFLAGS=-g` and vice versa?

**Comment by mattst88** [comment]
I emerged spidermonkey, optimized and with `CFLAGS=-g` and then ran polkit's test suite. It passed. I reemerged spidermonkey, optimized and without `CFLAGS=-g` and reran polkit's test suite; it passed (and didn't rebuild anything).

So I don't think the subslot is needed.

**Comment by juippis** [comment]
Wow, thanks for checking thoroughly! That sounds good. I'll merge the spidermonkey bump (without subslot) and let's see what happens.

**Comment by juippis** [comment]
f3e81dffcabc5549927a1bed355991c5c441d9d8

**Pull request closed without merging**
