### PR TITLE
dev-libs/{libbson,mongo-c-driver}: bump to 1.10.3

### PR DESCRIPTION
**Pull request by hydrapolic**
- Now uses same git repo
- Migrated to cmake
- License updated to Apache-2.0
- Tests are built in mongo-c-driver (using libbson[static-libs])

### CODE REVIEW

**Comment by Whissi** [comment]
@hydrapolic: Is it right that dev-libs/libbson-1.10.3 itself doesn't run tests?

**Comment by hydrapolic** [comment]
Yes, since they merged it into one repo, we need to build a static-lib from libbson and then compile libmongoc that will produce a binary for tests. It *MAY* be patched around to build the tests for libbson, but it would be a huge diff :(

**Comment by hydrapolic** [comment]
Even libmongoc needed to be patched a bit because normally it refuses to build the test when libbson is not built along with it.

**Comment by Whissi** [comment]
I am going to merge but there's a test failure:
```
/var/tmp/portage/dev-libs/mongo-c-driver-1.10.3/work/mongo-c-driver-1.10.3/src/libmongoc/tests/test-mongoc-topology.c:878 test_multiple_selection_errors(): [No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'doesntexist'] [Failed to resolve 'example.com']] does not contain [calling ismaster on 'example.com:2']
    { "status": "FAIL", "test_file": "/Topology/multiple_selection_errors", "seed": "3011425125", "start": 2204.986123, "end": 2205.081497, "elapsed": 0.095374  },
```

**Comment by hydrapolic** [comment]
Thanks @Whissi. What arch did you test on please? I ran the test 3 times on ~amd64.

**Comment by Whissi** [comment]
Also ~amd64.



[build.txt](https://github.com/gentoo/gentoo/files/2129864/build.txt)

**Comment by hydrapolic** [comment]
Thanks I'll test again and attach the build log. And your emerge --info please?

**Comment by Whissi** [comment]
```
Portage 2.3.40 (python 3.6.5-final-0, default/linux/amd64/17.0, gcc-7.3.0, glibc-2.27-r4, 4.17.1-gentoo x86_64)
=================================================================
System uname: Linux-4.17.1-gentoo-x86_64-Intel-R-_Core-TM-_i7-3770K_CPU_@_3.50GHz-with-gentoo-2.6
KiB Mem:     8125248 total,   6296068 free
KiB Swap:    1048572 total,   1048572 free
Timestamp of repository gentoo: Sat, 23 Jun 2018 11:06:15 +0000
Head commit of repository gentoo: 8d98da90b7aa9294af1b338b131e39b628e6cb32

sh bash 4.4_p23
ld GNU ld (Gentoo 2.30 p3) 2.30.0
app-shells/bash:          4.4_p23::gentoo
dev-java/java-config:     2.2.0-r4::gentoo
dev-lang/perl:            5.26.2::gentoo
dev-lang/python:          2.7.15::gentoo, 3.6.5-r1::gentoo
dev-util/cmake:           3.11.4::gentoo
dev-util/pkgconfig:       0.29.2::gentoo
sys-apps/baselayout:      2.6::gentoo
sys-apps/openrc:          0.37::gentoo
sys-apps/sandbox:         2.13::gentoo
sys-devel/autoconf:       2.69-r4::gentoo
sys-devel/automake:       1.13.4-r2::gentoo, 1.16.1-r1::gentoo
sys-devel/binutils:       2.30-r3::gentoo
sys-devel/gcc:            6.4.0-r1::gentoo, 7.3.0-r3::gentoo
sys-devel/gcc-config:     1.9.1::gentoo
sys-devel/libtool:        2.4.6-r5::gentoo
sys-devel/make:           4.2.1-r3::gentoo
sys-kernel/linux-headers: 4.17::gentoo (virtual/os-headers)
sys-libs/glibc:           2.27-r4::gentoo
Repositories:

gentoo
    location: /usr/portage
    sync-type: git
    sync-uri: https://github.com/gentoo-mirror/gentoo.git
    priority: -1000

ABI="amd64"
ABI_X86="64"
ACCEPT_KEYWORDS="amd64 ~amd64"
ACCEPT_LICENSE="* -@EULA"
ACCEPT_PROPERTIES="*"
ACCEPT_RESTRICT="*"
ANT_HOME="/usr/share/ant"
APACHE2_MPMS="worker"
ARCH="amd64"
BROOT=""
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Wno-error=missing-prototypes -Wno-error=enum-compare -Wno-error=unused-function -Wno-error=deprecated-declarations -frecord-gcc-switches"
CFLAGS_amd64="-m64"
CFLAGS_x32="-mx32"
CFLAGS_x86="-m32"
CHOST="x86_64-pc-linux-gnu"
CHOST_amd64="x86_64-pc-linux-gnu"
CHOST_x32="x86_64-pc-linux-gnux32"
CHOST_x86="i686-pc-linux-gnu"
COLLISION_IGNORE="/lib/modules/* *.py[co] *$py.class */dropin.cache"
CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
CPU_FLAGS_X86="aes avx mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3"
CURL_SSL="gnutls"
CXXFLAGS="-O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Wno-error=missing-prototypes -Wno-error=enum-compare -Wno-error=unused-function -Wno-error=deprecated-declarations -frecord-gcc-switches"
DEFAULT_ABI="amd64"
EDITOR="/bin/nano"
ELIBC="glibc"
ENV_UNSET="DBUS_SESSION_BUS_ADDRESS DISPLAY PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
EPREFIX=""
EROOT="/"
ESYSROOT="/"
FCFLAGS="-O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Wno-error=missing-prototypes -Wno-error=enum-compare -Wno-error=unused-function -Wno-error=deprecated-declarations -frecord-gcc-switches"
FEATURES="assume-digests binpkg-logs cgroup config-protect-if-modified distlocks downgrade-backup ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch preserve-libs protect-owned sandbox sfperms strict strict-keepdir unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
FFLAGS="-O2 -pipe -march=ivybridge -mtune=ivybridge -mno-xsaveopt -Wno-error=missing-prototypes -Wno-error=enum-compare -Wno-error=unused-function -Wno-error=deprecated-declarations -frecord-gcc-switches"
GCC_SPECS=""
GRUB_PLATFORMS=""
HOME="/root"
INFOPATH="/usr/share/gcc-data/x86_64-pc-linux-gnu/7.3.0/info:/usr/share/binutils-data/x86_64-pc-linux-gnu/2.30/info:/usr/share/info"
INPUT_DEVICES="libinput keyboard mouse"
IUSE_IMPLICIT="abi_x86_64 prefix prefix-chain prefix-guest"
JAVAC="/etc/java-config-2/current-system-vm/bin/javac"
JAVA_HOME="/etc/java-config-2/current-system-vm"
JDK_HOME="/etc/java-config-2/current-system-vm"
KERNEL="linux"
L10N="en en-US de de-DE"
LANG="en_US.UTF-8"
LC_MESSAGES="C"
LC_NUMERIC="de_DE.UTF-8"
LC_PAPER="de_DE.UTF-8"
LDFLAGS="-Wl,-O1 -Wl,--as-needed"
LDFLAGS_amd64="-m elf_x86_64"
LDFLAGS_x32="-m elf32_x86_64"
LDFLAGS_x86="-m elf_i386"
LIBDIR_amd64="lib64"
LIBDIR_x32="libx32"
LIBDIR_x86="lib32"
LINGUAS="en de"
LOGNAME="root"
MAIL="/var/mail/root"
MAKEOPTS="--jobs 6"
MANPAGER="manpager"
MULTILIB_ABIS="amd64 x86"
NOCOLOR="true"
OFFICE_IMPLEMENTATION="libreoffice"
OLDPWD="/root"
OPENCL_PROFILE="mesa"
OPENGL_PROFILE="xorg-x11"
ORACLE_HOME="/usr/lib64/oracle/12.2/client"
PAGER="/usr/bin/less"
PATH="/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
PHP_TARGETS="php5-6 php7-2"
POSTGRES_TARGETS="postgres9_5 postgres10"
PWD="/tmp"
PYTHONDONTWRITEBYTECODE="1"
PYTHON_SINGLE_TARGET="python3_6"
PYTHON_TARGETS="python2_7 python3_6"
QT_GRAPHICSSYSTEM="raster"
ROOT="/"
ROOTPATH="/usr/x86_64-pc-linux-gnu/gcc-bin/7.3.0:/usr/lib/llvm/6/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin"
RUBY_TARGETS="ruby23"
SHELL="/bin/bash"
SHLVL="2"
SSH_TTY="/dev/pts/0"
SYMLINK_LIB="yes"
SYSROOT="/"
TERM="screen"
TMUX="/tmp//tmux-0/default,5517,0"
TMUX_PANE="%1"
TNS_ADMIN="/etc/oracle/"
TWISTED_DISABLE_WRITING_OF_PLUGIN_CACHE="1"
USER="root"
USERLAND="GNU"
```

**Comment by hydrapolic** [comment]
Is it run in chroot or on a normal system?

**Comment by Whissi** [comment]
My normal dev system.

**Comment by hydrapolic** [comment]
I think I never saw this line during the build on my system (cgroups):
 * Failed to kill pid(s) in '/sys/fs/cgroup/portage/dev-libs:mongo-c-driver-1.10.3.svaff96s/cgroup.procs': 113797

Maybe just haven't noticed yet :)

**Comment by Whissi** [comment]
Seems to be a sandbox issue: It is passing with `FEATURES=-network-sandbox`, but network-sandbox is enabled by default.

**Comment by hydrapolic** [comment]
Yes, it tries to resolve a non existing server and how the library will behave. In the next version this will be documented. Thank you.

**Pull request closed without merging**
