### PR TITLE
⬆️ games-strategy/dunelegacy: add 0.97.02

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

**Dune Legacy** `0.97.02` [exists](https://sourceforge.net/p/dunelegacy/code/ci/6ea9ac96/tree/include/config.h#l19) for a while now.
It would be nice to have it in the Portage tree.

News:
  - https://dunelegacy.sourceforge.net/website/news.html

Based on:
  - [games-strategy/dunelegacy-0.96.4-r1](https://gitweb.gentoo.org/repo/gentoo.git/commit/games-strategy/dunelegacy/dunelegacy-0.96.4-r1.ebuild?id=7b0d522b) by @chewi
  - https://aur.archlinux.org/packages/dunelegacy

<details><summary>diff -u dunelegacy-0.9{6.4-r1,7.02}.ebuild</summary>
<p>

```diff
--- dunelegacy-0.96.4-r1.ebuild	2024-07-17 07:36:36.418959869 +0300
+++ dunelegacy-0.97.02.ebuild	2024-07-19 04:44:58.650595041 +0300
@@ -3,11 +3,15 @@
 
 EAPI=8
 
-inherit desktop xdg
+inherit autotools desktop xdg
 
 DESCRIPTION="Updated clone of Westood Studios' Dune II"
 HOMEPAGE="https://dunelegacy.sourceforge.net"
-SRC_URI="https://downloads.sourceforge.net/${PN}/${P}-src.tar.bz2"
+
+COMMIT="6ea9ac96854daa8c75ba429e78dc6716b147e106"
+SRC_URI="https://sourceforge.net/code-snapshots/git/d/du/${PN}/code.git/${PN}-code-${COMMIT}.zip -> ${P}.zip"
+S="${WORKDIR}/${PN}-code-${COMMIT}"
+
 LICENSE="GPL-2+"
 SLOT="0"
 KEYWORDS="~amd64 ~arm ~riscv ~x86"
@@ -15,19 +19,24 @@
 RDEPEND="
 	media-libs/libsdl2[sound,threads(+),video]
 	media-libs/sdl2-mixer[midi]
+	media-libs/sdl2-ttf
 "
 DEPEND="${RDEPEND}"
-BDEPEND="virtual/pkgconfig"
+BDEPEND="
+	app-arch/unzip
+	virtual/pkgconfig
+"
 
 PATCHES=(
-	"${FILESDIR}"/${P}-init-mid.patch
+	"${FILESDIR}"/${P}-flickering.patch
+	"${FILESDIR}"/${P}-text-manager.patch
 )
 
 src_prepare() {
 	default
+	eautoreconf
 
-	# Prepend upstream flags.
-	sed -i -r 's/^(C.*FLAGS)=[^$]+$/\0" ${\1}"/' configure || die
+	sed -i s/0.96.4/0.97.02/ configure.ac || die
 }
 
 src_install() {
```

</p>
</details> 

_Best regards!_

---

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

### CODE REVIEW

**Comment by chewi** [comment]
Does this actually work? I was assuming that it had only been released for Windows for a reason.

**Comment by Jamim** [comment]
> Does this actually work? I was assuming that it had only been released for Windows for a reason.

Yes, it works perfectly fine for me on Sway in both windowed and full-screen modes.

**Comment by chewi** [comment]
Thanks, merged this now. There were some issues though, please check them out. In particular, you need to make modifications to configure.ac _before_ running `eautoreconf`.

**Comment by Jamim** [comment]
_Hello @chewi,_
Thank you for merging and improving these changes! 🙇🏼

**Pull request closed without merging**
