### PR TITLE
net-im/skypeforlinux: version bump to 8.11.0.4

### PR DESCRIPTION
**Pull request by karolgrudzinski**
- Bump to 8.9.0.1
- Remove ebuild for unfetchable version 5.4.0.1

Package-Manager: Portage-2.3.13, Repoman-2.3.4

### CODE REVIEW

**Comment by karolgrudzinski** [comment]
Gentoo Bug: https://bugs.gentoo.org/636278

**Comment by leio** [comment]
Have you tested this? It gives me STARTUP_LOAD_ERROR upon login. Has https://forums.gentoo.org/viewtopic-p-8116114.html and the likes been solved with the final release?

**Comment by karolgrudzinski** [comment]
Yes, you are right. I should test this before making PR. Older ebuild doesn't install some necessary files. I replaced insinto/doins madness in ebuild with simple 'mv usr "${D}"/' but it also doesn't work, I still get STARTUP_LOAD_ERROR. I'm really sorry, but I don't know how to make this work :( .

**Comment by leio** [comment]
I think the forum thread had some hints. Something about rpm having directories with @ in it and it failing to unpack beyond that? Maybe worth checking out if that's the issue here.

@nicolasbock - for me it starts up just fine, it's after I enter my password that it doesn't actually show the contacts and be functional with that error code displayed and really only a log out button available (and it's also now out of beta or something, and doesn't seem to migrate settings over from the beta, hence the need to re-log too).

**Comment by nicolasbock** [comment]
@leio I am going to try it out too. I think I just figured out how to run it in my docker sandbox :smile:

**Comment by karolgrudzinski** [comment]
Yes, rpm has directory with @ in it but it unpacks fine:

```
/var/tmp/portage/net-im/skypeforlinux-8.9.0.1 # find work/
work/
work/usr
work/usr/bin
work/usr/bin/skypeforlinux
work/usr/share
work/usr/share/applications
work/usr/share/applications/skypeforlinux.desktop
work/usr/share/doc
work/usr/share/doc/skypeforlinux
work/usr/share/doc/skypeforlinux/third-party_attributions.html
work/usr/share/icons
work/usr/share/icons/hicolor
work/usr/share/icons/hicolor/1024x1024
work/usr/share/icons/hicolor/1024x1024/apps
work/usr/share/icons/hicolor/1024x1024/apps/skypeforlinux.png
work/usr/share/icons/hicolor/16x16
work/usr/share/icons/hicolor/16x16/apps
work/usr/share/icons/hicolor/16x16/apps/skypeforlinux.png
work/usr/share/icons/hicolor/256x256
work/usr/share/icons/hicolor/256x256/apps
work/usr/share/icons/hicolor/256x256/apps/skypeforlinux.png
work/usr/share/icons/hicolor/32x32
work/usr/share/icons/hicolor/32x32/apps
work/usr/share/icons/hicolor/32x32/apps/skypeforlinux.png
work/usr/share/icons/hicolor/512x512
work/usr/share/icons/hicolor/512x512/apps
work/usr/share/icons/hicolor/512x512/apps/skypeforlinux.png
work/usr/share/pixmaps
work/usr/share/pixmaps/skypeforlinux.png
work/usr/share/skypeforlinux
work/usr/share/skypeforlinux/LICENSES.chromium.html
work/usr/share/skypeforlinux/blink_image_resources_200_percent.pak
work/usr/share/skypeforlinux/content_resources_200_percent.pak
work/usr/share/skypeforlinux/content_shell.pak
work/usr/share/skypeforlinux/icudtl.dat
work/usr/share/skypeforlinux/libffmpeg.so
work/usr/share/skypeforlinux/libnode.so
work/usr/share/skypeforlinux/locales
work/usr/share/skypeforlinux/locales/am.pak
work/usr/share/skypeforlinux/locales/ar.pak
work/usr/share/skypeforlinux/locales/bg.pak
work/usr/share/skypeforlinux/locales/bn.pak
work/usr/share/skypeforlinux/locales/ca.pak
work/usr/share/skypeforlinux/locales/cs.pak
work/usr/share/skypeforlinux/locales/da.pak
work/usr/share/skypeforlinux/locales/de.pak
work/usr/share/skypeforlinux/locales/el.pak
work/usr/share/skypeforlinux/locales/en-GB.pak
work/usr/share/skypeforlinux/locales/en-US.pak
work/usr/share/skypeforlinux/locales/es-419.pak
work/usr/share/skypeforlinux/locales/es.pak
work/usr/share/skypeforlinux/locales/et.pak
work/usr/share/skypeforlinux/locales/fa.pak
work/usr/share/skypeforlinux/locales/fake-bidi.pak
work/usr/share/skypeforlinux/locales/fi.pak
work/usr/share/skypeforlinux/locales/fil.pak
work/usr/share/skypeforlinux/locales/fr.pak
work/usr/share/skypeforlinux/locales/gu.pak
work/usr/share/skypeforlinux/locales/he.pak
work/usr/share/skypeforlinux/locales/hi.pak
work/usr/share/skypeforlinux/locales/hr.pak
work/usr/share/skypeforlinux/locales/hu.pak
work/usr/share/skypeforlinux/locales/id.pak
work/usr/share/skypeforlinux/locales/it.pak
work/usr/share/skypeforlinux/locales/ja.pak
work/usr/share/skypeforlinux/locales/kn.pak
work/usr/share/skypeforlinux/locales/ko.pak
work/usr/share/skypeforlinux/locales/lt.pak
work/usr/share/skypeforlinux/locales/lv.pak
work/usr/share/skypeforlinux/locales/ml.pak
work/usr/share/skypeforlinux/locales/mr.pak
work/usr/share/skypeforlinux/locales/ms.pak
work/usr/share/skypeforlinux/locales/nb.pak
work/usr/share/skypeforlinux/locales/nl.pak
work/usr/share/skypeforlinux/locales/pl.pak
work/usr/share/skypeforlinux/locales/pt-BR.pak
work/usr/share/skypeforlinux/locales/pt-PT.pak
work/usr/share/skypeforlinux/locales/ro.pak
work/usr/share/skypeforlinux/locales/ru.pak
work/usr/share/skypeforlinux/locales/sk.pak
work/usr/share/skypeforlinux/locales/sl.pak
work/usr/share/skypeforlinux/locales/sr.pak
work/usr/share/skypeforlinux/locales/sv.pak
work/usr/share/skypeforlinux/locales/sw.pak
work/usr/share/skypeforlinux/locales/ta.pak
work/usr/share/skypeforlinux/locales/te.pak
work/usr/share/skypeforlinux/locales/th.pak
work/usr/share/skypeforlinux/locales/tr.pak
work/usr/share/skypeforlinux/locales/uk.pak
work/usr/share/skypeforlinux/locales/vi.pak
work/usr/share/skypeforlinux/locales/zh-CN.pak
work/usr/share/skypeforlinux/locales/zh-TW.pak
work/usr/share/skypeforlinux/natives_blob.bin
work/usr/share/skypeforlinux/pdf_viewer_resources.pak
work/usr/share/skypeforlinux/resources
work/usr/share/skypeforlinux/resources/app.asar
work/usr/share/skypeforlinux/resources/app.asar.unpacked
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build/Release
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build/Release/cld.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build/Release
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build/Release/spellchecker.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build/Release
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin/sharing-indicator.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin/slimcore.node
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib/binding
work/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib/binding/node_sqlite3.node
work/usr/share/skypeforlinux/resources/default_app.asar
work/usr/share/skypeforlinux/resources/electron.asar
work/usr/share/skypeforlinux/skypeforlinux
work/usr/share/skypeforlinux/snapshot_blob.bin
work/usr/share/skypeforlinux/ui_resources_200_percent.pak
work/usr/share/skypeforlinux/version
work/usr/share/skypeforlinux/views_resources_200_percent.pak
```

And it also installs all files without problems:

```
/var/tmp/portage/net-im/skypeforlinux-8.9.0.1 # find image/
image/
image/usr
image/usr/bin
image/usr/bin/skypeforlinux
image/usr/share
image/usr/share/applications
image/usr/share/applications/skypeforlinux.desktop
image/usr/share/doc
image/usr/share/doc/skypeforlinux
image/usr/share/doc/skypeforlinux/third-party_attributions.html
image/usr/share/icons
image/usr/share/icons/hicolor
image/usr/share/icons/hicolor/1024x1024
image/usr/share/icons/hicolor/1024x1024/apps
image/usr/share/icons/hicolor/1024x1024/apps/skypeforlinux.png
image/usr/share/icons/hicolor/16x16
image/usr/share/icons/hicolor/16x16/apps
image/usr/share/icons/hicolor/16x16/apps/skypeforlinux.png
image/usr/share/icons/hicolor/256x256
image/usr/share/icons/hicolor/256x256/apps
image/usr/share/icons/hicolor/256x256/apps/skypeforlinux.png
image/usr/share/icons/hicolor/32x32
image/usr/share/icons/hicolor/32x32/apps
image/usr/share/icons/hicolor/32x32/apps/skypeforlinux.png
image/usr/share/icons/hicolor/512x512
image/usr/share/icons/hicolor/512x512/apps
image/usr/share/icons/hicolor/512x512/apps/skypeforlinux.png
image/usr/share/pixmaps
image/usr/share/pixmaps/skypeforlinux.png
image/usr/share/skypeforlinux
image/usr/share/skypeforlinux/LICENSES.chromium.html
image/usr/share/skypeforlinux/blink_image_resources_200_percent.pak
image/usr/share/skypeforlinux/content_resources_200_percent.pak
image/usr/share/skypeforlinux/content_shell.pak
image/usr/share/skypeforlinux/icudtl.dat
image/usr/share/skypeforlinux/libffmpeg.so
image/usr/share/skypeforlinux/libnode.so
image/usr/share/skypeforlinux/locales
image/usr/share/skypeforlinux/locales/am.pak
image/usr/share/skypeforlinux/locales/ar.pak
image/usr/share/skypeforlinux/locales/bg.pak
image/usr/share/skypeforlinux/locales/bn.pak
image/usr/share/skypeforlinux/locales/ca.pak
image/usr/share/skypeforlinux/locales/cs.pak
image/usr/share/skypeforlinux/locales/da.pak
image/usr/share/skypeforlinux/locales/de.pak
image/usr/share/skypeforlinux/locales/el.pak
image/usr/share/skypeforlinux/locales/en-GB.pak
image/usr/share/skypeforlinux/locales/en-US.pak
image/usr/share/skypeforlinux/locales/es-419.pak
image/usr/share/skypeforlinux/locales/es.pak
image/usr/share/skypeforlinux/locales/et.pak
image/usr/share/skypeforlinux/locales/fa.pak
image/usr/share/skypeforlinux/locales/fake-bidi.pak
image/usr/share/skypeforlinux/locales/fi.pak
image/usr/share/skypeforlinux/locales/fil.pak
image/usr/share/skypeforlinux/locales/fr.pak
image/usr/share/skypeforlinux/locales/gu.pak
image/usr/share/skypeforlinux/locales/he.pak
image/usr/share/skypeforlinux/locales/hi.pak
image/usr/share/skypeforlinux/locales/hr.pak
image/usr/share/skypeforlinux/locales/hu.pak
image/usr/share/skypeforlinux/locales/id.pak
image/usr/share/skypeforlinux/locales/it.pak
image/usr/share/skypeforlinux/locales/ja.pak
image/usr/share/skypeforlinux/locales/kn.pak
image/usr/share/skypeforlinux/locales/ko.pak
image/usr/share/skypeforlinux/locales/lt.pak
image/usr/share/skypeforlinux/locales/lv.pak
image/usr/share/skypeforlinux/locales/ml.pak
image/usr/share/skypeforlinux/locales/mr.pak
image/usr/share/skypeforlinux/locales/ms.pak
image/usr/share/skypeforlinux/locales/nb.pak
image/usr/share/skypeforlinux/locales/nl.pak
image/usr/share/skypeforlinux/locales/pl.pak
image/usr/share/skypeforlinux/locales/pt-BR.pak
image/usr/share/skypeforlinux/locales/pt-PT.pak
image/usr/share/skypeforlinux/locales/ro.pak
image/usr/share/skypeforlinux/locales/ru.pak
image/usr/share/skypeforlinux/locales/sk.pak
image/usr/share/skypeforlinux/locales/sl.pak
image/usr/share/skypeforlinux/locales/sr.pak
image/usr/share/skypeforlinux/locales/sv.pak
image/usr/share/skypeforlinux/locales/sw.pak
image/usr/share/skypeforlinux/locales/ta.pak
image/usr/share/skypeforlinux/locales/te.pak
image/usr/share/skypeforlinux/locales/th.pak
image/usr/share/skypeforlinux/locales/tr.pak
image/usr/share/skypeforlinux/locales/uk.pak
image/usr/share/skypeforlinux/locales/vi.pak
image/usr/share/skypeforlinux/locales/zh-CN.pak
image/usr/share/skypeforlinux/locales/zh-TW.pak
image/usr/share/skypeforlinux/natives_blob.bin
image/usr/share/skypeforlinux/pdf_viewer_resources.pak
image/usr/share/skypeforlinux/resources
image/usr/share/skypeforlinux/resources/app.asar
image/usr/share/skypeforlinux/resources/app.asar.unpacked
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build/Release
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/cld/build/Release/cld.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build/Release
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/@paulcbetts/spellchecker/build/Release/spellchecker.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keyboard-layout/build/Release/keyboard-layout-manager.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build/Release
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/keytar/build/Release/keytar.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin/sharing-indicator.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/slimcore/bin/slimcore.node
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib/binding
image/usr/share/skypeforlinux/resources/app.asar.unpacked/node_modules/sqlite3/lib/binding/node_sqlite3.node
image/usr/share/skypeforlinux/resources/default_app.asar
image/usr/share/skypeforlinux/resources/electron.asar
image/usr/share/skypeforlinux/skypeforlinux
image/usr/share/skypeforlinux/snapshot_blob.bin
image/usr/share/skypeforlinux/ui_resources_200_percent.pak
image/usr/share/skypeforlinux/version
image/usr/share/skypeforlinux/views_resources_200_percent.pak
```

**Comment by ylep** [comment]
Fyi, I uploaded an improved ebuild to https://bugs.gentoo.org/636278. It includes an updated list of dependencies, maybe this can fix your runtime problems.

**Comment by karolgrudzinski** [comment]
I replaced ebuild with @ylep's version (with one change - I removed 'no-source-code' from licenses list).

**Comment by shentino** [comment]
:thumbsup:

Thanks for covering this during my absence.

**Comment by karolgrudzinski** [comment]
There was another version bump today :)

**Comment by ylep** [comment]
I double-checked, the the shared-library dependencies did not change in the new version, so the ebuild can work unchanged.
May I suggest one small improvement to the ebuild: the KEYWORDS line should read `KEYWORDS="~amd64 -*"` (i.e. `-*` should be added) because this is a binary package.

**Comment by karolgrudzinski** [comment]
Another day, another version bump.

**Comment by ylep** [comment]
Fixed the QA warning, new ebuild is attached to the bug report (https://bugs.gentoo.org/attachment.cgi?id=506434)

**Comment by MathyV** [comment]
I installed the ebuild, it seems to be working, also the webcam works. Since the version in the tree (5.5.0.1) is no longer able to connect I suggest this is merged asap :-)

**Comment by karolgrudzinski** [comment]
I will remove ebuild for 5.5.0.1 from PR.

27 lis 2017 17:31 "Mathy Vanvoorden" <notifications@github.com> napisał(a):

**Comment by asarubbo** [comment]
merged, thanks

**Pull request closed without merging**
