### PR TITLE
x11-wm/fluxbox: Fix ISO C++17 does not allow register storage class s…

### PR DESCRIPTION
**Pull request by listout**
…pecifier

Closes: https://bugs.gentoo.org/898884

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Can't seem to test this on musl due to gnome-base/librsvg not compiling on musl.

**Comment by listout** [comment]
> Can't seem to test this on musl due to gnome-base/librsvg not compiling on musl.

I don't think this bug has anything to musl in particular, just requires clang:16

**Comment by ceamac** [comment]
I'm trying it on musl now, I managed to build a librsvg on the stable musl profile to bypass the blocker and now I'm compiling clang-16.

**Comment by listout** [comment]
> I'm trying it on musl now, I managed to build a librsvg on the stable musl profile to bypass the blocker and now I'm compiling clang-16.

The main blocker for gnome stuff on clang16 is vala. Until that gets fixed, it's quite difficult.

**Review by ceamac — APPROVED** [review]
The fix works, it built successfully on musl with gcc-16.

I saw you sent the patch upstream, unfortunately the project doesn't seem too active.

Thank you!

**Pull request closed without merging**
