### PR TITLE
Kicad 5.1.2

### PR DESCRIPTION
**Pull request by zpuskas**

### CODE REVIEW

**Comment by hsoft** [comment]
Builds and runs fine for me. I have two questions:

1. Any particular reason why you left out python 3.5 compat? I understand why 3.7 isn't there (boost < 1.70 doesn't have it and 1.70 is masked), but I don't understand 3.5.

2. I don't understand why the CI doesn't cry about this: wxpython:4.0 isn't keyworded for arm64. repoman -dx full complains about this on my machine. Doesn't it complains on yours too? You will have to drop the ~arm64 keyword and open a re-keywording request.

**Comment by zpuskas** [comment]
@hsoft Good points.

1, I left out Python 3.5, because I thought there was a dependency not supporting it. However having gone through them now quickly this does not seem to be the case. I might have confused this with something. Will double check and reenable 3.5 tonight.

2, I think it complained for the 17.1 dev profile only as a warning, not an error. However I would argue that here the better solution would be either make wxpython-4 work with arm64 or maybe reverting to previous wxpython that works on arm64 too?  Should we not move toward arm64 support?

Though I don't know how many people use KiCAD on arm64, maybe we can just drop it completely, since on arm64 we already have some use mask for it:

```
/usr/portage/profiles $ rg kicad
...
arch/arm64/package.use.mask
77:sci-electronics/kicad occ oce ngspice
```

**Comment by hsoft** [comment]
Dropping arches when new dependencies aren't keyworded for them is fine, it's part of the regular process. It's just that whenever we drop them, we open re-keywording bugs so that the arch teams can keyword new dependencies and re-keyword kicad.

It's just that arm64 arches typically take a long time to process these bug, to re-keywording takes a while...

So to answer your question 2: sure, if you want, you can stay with wxpython 3.x (and python 2, and gtk 2) until wxpython is keyworded for arm64, but that could take a long while. Personally, I'd rather go for dropping arm64 and move forward.

**Comment by zpuskas** [comment]
Added Python 3.5, double checked deps and ran `repoman -dx full` too. No warnings.

I've decided to drop ~arm64 as half of the KiCAD ebuild have not been even keyworded for that. There is no point in providing a broken experience.

**Comment by NeddySeagoon** [comment]
kicad-5.1.0 seems OK on an ~arm64  Raspberry Pi and an ~arm64 Acer R13 Chromebook.
It would be a shame to drop the ~arm64 keyword as proposed in bug 687322.

I'll do the work to keyword the dependencies on ~arm64.  If new keywords are required for this PR to go ahead, drop ~arm64 now and I'll add it back later.  It will be a week or two until I get to this.

**Pull request closed without merging**
