### PR TITLE
media-libs/elles_icc_profiles: new package

### PR DESCRIPTION
**Pull request by mkszuba**
Elle Stone, the author of a Web site dedicated colour management with FLOSS software (http://ninedegreesbelow.com/), produces a set of ICC profiles for many standard RGB working spaces. All these profiles are free to use (they are based on publicly available documentation and licensed under a Creative Commons licence), are carefully checked for accuracy, and are guaranteed to be well-behaved which makes them suitable for colour-managed image editing.

In addition to the ICC profiles themselves, the package also contains the source code of Elle's profile generator (depends on lcms; licensed under the GPL), which can be either used to independently reproduce the provided profiles or customised to produce additional profiles.

Gentoo-Bug: https://bugs.gentoo.org/583420
Package-Manager: portage-2.3.0_rc1

### CODE REVIEW

**Comment by Coacher** [comment]
It looks like LICENSE is incomplete as installed C code is GPL-2+.

**Comment by Coacher** [comment]
It's not exactly a library even with shipped C programs, so maybe media-gfx/ category is more suitable.

**Comment by mkszuba** [comment]
I guess it makes sense, however as we have already got media-libs/icc-profiles-basiccolor-printing2009 and media-libs/icc-profiles-openicc, maybe this one should go into the same category for consistency?

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by Coacher** [comment]
@mkszuba, fair enough.

**Comment by idella** [comment]
Are you not going to set x86 with KEYWORDS="~amd64" ?

**Comment by idella** [comment]
The checks by" repoman full" etc. check out fine. The ebuild installs.

So check: Is this

`/path/to/media-libs/elles_icc_profiles-20160501.0932/image/usr/share/color/icc/ellestone/`

intended as the only path of files for installation to the system, beside use of USE=tools ?
ALso you have not replied to the prompt re adding x86 keyword

**Comment by mkszuba** [comment]
Sorry, been travelling. Yes, this should be the only path. As for the keywords, should I? I've only tested it under amd64, even though nothing in this package should be arch-dependent.

**Pull request closed without merging**
