### PR TITLE
app-text/wgetpaste: Add gnutls and libressl support

### PR DESCRIPTION
**Pull request by nvinson**
Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by nvinson** [comment]
I don't believe so.  Per https://wiki.gentoo.org/wiki/Project:LibreSSL, the USE flags should be set up this way.  If ssl and gnutls are set, the rebuild should use gnutls.  If ssl and libressl and not gnutls, libressl.  If just ssl, openssl.  Otherwise, don't require any.

Personally, I think REQUIRED_USE would have been the better idea here, but to be consistent with other ebuilds and the libressl project, I cannot use it here.

**Comment by mkszuba** [comment]
Not quite. Even assuming the code snippets on the Wiki page you have quoted constitute rules rather than guidelines (and IMHO they are the latter), these apply to ebuilds directly depending on SSL libraries - like net-misc/wget itself, for instance. Under such circumstances you *have to* have multiple atoms because each of them is different. Not so for wgetpaste, in which case the underlying dependency does not change and all the ebuild does is forward USE flags.

**Comment by nvinson** [comment]
Since the goal was to ensure wgetpaste didn't cause an incompatibility with non-openssl implementations and because wget has to be +ssl to even select an implementation, I'm OK with closing this PR without making the change as wget's current ebuild already meets this goal.  In fact, I'll go ahead and close it.

**Comment by SoapGentoo** [comment]
@mkszuba no, those examples constitute rules, not guidelines. The `USE=libressl` flag has defined semantics, and it has those a) as 10 years ago noone could have anticipated LibreSSL b) you can't change the semantics of `USE=openssl` anymore c) `REQUIRED_USE` sucks in practice. So yes, please heed that page's advice.

**Pull request closed without merging**
