### PR TITLE
Updates to Vulkan packages

### PR DESCRIPTION
**Pull request by amadio**

### CODE REVIEW

**Comment by RarogCmex** [comment]
Hey, @amadio, really thank for you, your save me a lot of time to bumping vulkan packages by myself to satisfy upcoming media-libs/amdvlk package.

**Comment by amadio** [comment]
I must have messed up the rebase. I had originally bumped to 1.2.132, but updated to 1.2.133. I will push again fixes for the errors reported by CI.

**Comment by sarnex** [comment]
Thanks, please make sure all the dependencies versions match. For example, dev-util/vulkan-tools-1.2.133 should depend on media-libs/vulkan-loader-1.2.133, not 1.1.125. Please double check this for the other version bumps.

**Comment by amadio** [comment]
Indeed, I missed that one. The others are fine. I will fix it and push later today. Thanks!

**Comment by mattst88** [comment]
No one noticed that EGIT_COMMIT hadn't been updated for vulkan-{tools,layers}, so we're just shipping the same thing with a new version. /facepalm

**Comment by amadio** [comment]
Damn, thanks for noticing! Big facepalm. I didn't notice the ${EGIT_COMMIT} instead of ${PV} in SRC_URI! That's a very unusual thing.

**Comment by a17r** [comment]
working on it.

**Pull request closed without merging**
