### PR TITLE
net-misc/yandex-disk: version bump to v0.1.5.1010-1

### PR DESCRIPTION
**Pull request by Kami-no**
Signed-off-by: Dmitriy Zinin <admin@kami-no.ru>

### CODE REVIEW

**Comment by monsieurp** [comment]
Please update the format of the commit message according to our guidelines.

**Comment by Kami-no** [comment]
OK, got it

**Comment by juippis** [comment]
Hey, is this still relevant? If yes:
Your sign-off is wrongly formatted. You can automate it by using repoman to commit, and adding `SIGNED_OFF_BY` to your make.conf. 
Also don't use `git mv` but make a new commit for addition and removal of files.

**Comment by Pinkbyte** [comment]
Closed via 287a7f706de2e53aafc0d81ef53639f35421ae8e

**Pull request closed without merging**
