### PR TITLE
net-p2p/airdcpp-webclient & webui: bumps to 1.0.7 and 1.0.8

### PR DESCRIPTION
**Pull request by sbraz**
Mostly bug fixes: https://github.com/airdcpp-web/airdcpp-webclient/releases/tag/1.0.7
I also noticed that the client doesn't compile with `openssl[bindist]`: https://forums.gentoo.org/viewtopic-p-7916882.html

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
- Missing dep on pkgconfig https://github.com/airdcpp-web/airdcpp-webclient/blob/master/CMakeLists.txt#L20
- The license should be GPL-2+ https://github.com/airdcpp-web/airdcpp-webclient/blob/master/airdcpp-core/airdcpp/AirUtil.cpp#L7

**Comment by sbraz** [comment]
@gktrk

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/commit/7a49130784b1b4714c46888a83e1ec11462e70ef. Thanks!

**Pull request closed without merging**
