### PR TITLE
games-util/lutris: bump + bugfixes

### PR DESCRIPTION
**Pull request by nado**
May I add myself as proxied-maintainer of this package?

### CODE REVIEW

**Comment by a17r** [comment]
one after another, please.

https://github.com/gentoo/gentoo/pull/10533
https://github.com/gentoo/gentoo/pull/10749

**Comment by nado** [comment]
:') My bad, I checked bgo but didnt think about Github, I’ll close this in the meantime. Apologies if any feel needed.

**Comment by a17r** [comment]
Of course please check if you have input for the existing PRs.

**Comment by nado** [comment]
I invite you to check my tests, install and postinst changes as well of removal of default functions.

**Comment by a17r** [comment]
You can make line comments in the first PR, that makes much more sense as you are already in the code anyway, much more than a casual reviewer. I'm not sure anyone else volunteered for lutris yet.

**Comment by nado** [comment]
Ok, I’ll do that tomorrow then.

**Comment by a17r** [comment]
Thank you very much for your work, I've salvaged it as best as possible after merging the oldest still pending lutris PR. Having seen this PR, I am open to add you as proxied maintainer to this package in the future if you are still interested.

**Comment by nado** [comment]
I am, I'll check what needs to be done after this weekend.

**Pull request closed without merging**
