### PR TITLE
sys-apps/ucspi-tcp: fix compilation

### PR DESCRIPTION
**Pull request by powerman**
Fixes https://bugs.gentoo.org/902013

### CODE REVIEW

**Comment by powerman** [comment]
There is no `make-makelib.sh` in this package. There is a `makelib` script, which is generated by `make makelib`. So, it looks like tools from qmail.eclass are not really helpful for the package. Moreover, to me it looks like some change in qmail.eclass is responsible for breaking compilation of the package.

I've just tried to add

```
src_compile() {
	qmail_set_cc
	emake
}
```

but it doesn't work: `sed: can't read make-makelib.sh: No such file or directory`.
This can be worked around by adding `touch make-makelib.sh` before `qmail_set_cc`, but it just doesn't feels right.

> The result would be, that cross compilation wouldn't work anymore.

Yeah, you probably right. But right now any compilation is broken, so maybe it worth to merge this fix for now, then remove 0.88-r18 ebuild (because it's also broken now), and then look for improvements.

I do proxy-maintain a few packages, but not this one. I don't see why qmail.eclass should be used for this package at all. And I'm probably not the best person to fix cross compilation because I don't use it.

**Comment by powerman** [comment]
Given the cc/ld part is non-trivial enough it looks like eclass change to support absent make-makelib.sh sounds reasonable. If eclass will be changed this way then current PR should be rejected.

**Comment by thesamesam** [comment]
@DerDakon

**Comment by arkamar** [comment]
I would like to point out that the `|| die` was recently added by @SoapGentoo in this commit https://github.com/gentoo/gentoo/commit/fd4e88c55e349b6c18cae294aeb01e0709bc9bdb.

**Pull request closed without merging**
