### PR TITLE
app-misc/boxes: drop version 1.1.2

### PR DESCRIPTION
**Pull request by Schievel1**
I know this belongs to shell-tools, but can I add myself as a maintainer here? 
I wrote an email asking that to the shell-tools project but they did not answer. 

Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

### CODE REVIEW

**Comment by Schievel1** [comment]
Let’s check if we can close the bugs as well

**Comment by thesamesam** [comment]
Thanks! I fixed metadata indentation.

**Comment by Schievel1** [comment]
> Thanks! I fixed metadata indentation.

Yup, it was only a warning so I pushed that regardless yesterday as it was late. Did not know that CI is going to complain. 
This is from emacs autoindent (M-x indent-region).

**Comment by thesamesam** [comment]
Warnings are things CI will complain about ;)

Yeah, I figured, it's a bit tricky to configure Emacs for metadata.xml.

**Pull request closed without merging**
