### PR TITLE
gui-libs/wlroots: add 0.17.0

### PR DESCRIPTION
**Pull request by sevz17**

### CODE REVIEW

**Comment by oniGino** [comment]
Please if you can add 
`DOCS=( docs/env_vars.md docs/architecture.md )`

**Comment by thesamesam** [comment]
> `DOCS=( docs/env_vars.md docs/architecture.md )`

Isn't that covered already by the `dodoc docs/*`?

**Comment by oniGino** [comment]
> > `DOCS=( docs/env_vars.md docs/architecture.md )`
> 
> Isn't that covered already by the `dodoc docs/*`?

It's not working properly...
Neither markdown file is in the docs folder after install

**Comment by sevz17** [comment]
Thanks!

Perfect timing!, I was preparing everything to release dwl 0.5

**Comment by sevz17** [comment]
> > > `DOCS=( docs/env_vars.md docs/architecture.md )`
> > 
> > 
> > Isn't that covered already by the `dodoc docs/*`?
> 
> It's not working properly... Neither markdown file is in the docs folder after install

In 9999 all works fine
```
equery f wlroots | grep share                                                                                                                                         took 534ms at 00:15:21 
/usr/share
/usr/share/doc
/usr/share/doc/wlroots-9999
/usr/share/doc/wlroots-9999/README.md.zst
/usr/share/doc/wlroots-9999/architecture.md.zst
/usr/share/doc/wlroots-9999/env_vars.md.zst
```

Let me end some things and then I'll check that

**Comment by oniGino** [comment]
> > > > `DOCS=( docs/env_vars.md docs/architecture.md )`
> > > 
> > > 
> > > Isn't that covered already by the `dodoc docs/*`?
> > 
> > It's not working properly... Neither markdown file is in the docs folder after install
> 
> In 9999 all works fine
> ```
> equery f wlroots | grep share                                                                                                                                         took 534ms at 00:15:21 
> /usr/share
> /usr/share/doc
> /usr/share/doc/wlroots-9999
> /usr/share/doc/wlroots-9999/README.md.zst
> /usr/share/doc/wlroots-9999/architecture.md.zst
> /usr/share/doc/wlroots-9999/env_vars.md.zst
> ```
> 
> Let me end some things and then I'll check that

Interesting I suppose they didn't exist in 0.16 and that's why they are missing? 

Thanks anyway then!

**Pull request closed without merging**
