### PR TITLE
app-text/pandoc: version bump to 2.2.1

### PR DESCRIPTION
**Pull request by jok-ts**
Bug: https://bugs.gentoo.org/645082

All the necessary ebuilds are already in the haskell overlay. This PR uses those ebuilds in an order that keeps repoman satisfied throughout.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/haskell: ping. could someone review this lengthy PR?

**Comment by jok-ts** [comment]
All those ebuilds _are_ from the ::haskell overlay and the versions selected here work with ghc-8.0.2 as already in the main tree. 

www-apps/gitit doesn't have a version there that would support pandoc-2 so it isn't included in the set.

**Comment by jok-ts** [comment]
The only other in-tree revdep I saw was pandoc-citeproc, and for that adding 
dev-haskell/xml-conduit-1.4.0.3
dev-haskell/hs-bibutils-6.2.0.1
dev-haskell/pandoc-citeproc-0.14.3.1-r1
from ::haskell should suffice. 

Wouldn't waiting for the _latest_ versions to be installable mean that there won't be a pandoc-2 in the tree until well after ghc-8.4, if then?

I'll see what repoman thinks about adding those three, even if that is just a waste of my time.

**Comment by jok-ts** [comment]
I suppose I might as well put these here while I still have the data... 
To build gitit-0.12.2.1_p20180806 w/ ghc-8.0.2 and pandoc-2.2.1 one would need five packages in addition to those already in this PR. 

Ebuilds already in ::haskell : 
dev-haskell/hoauth2-1.5.1
dev-haskell/uri-bytestring-0.3.2.0
dev-haskell/uri-bytestring-aeson-0.1.0.6-r1

Ebuilds not in ::haskell but found in hackage: 
dev-haskell/feed-1.0.0.0
dev-haskell/xml-conduit-1.5.1

Everything else needed is already in the main tree.

**Comment by jok-ts** [comment]
OK, this clearly isn't happening. Five of these package versions have since been removed from :::haskell and the only remaining pandoc-2.2 version there requires four additional packages and cabal-2. Closing.

**Pull request closed without merging**
