### PR TITLE
www-client/firefox: reenable elf-hack for arm

### PR DESCRIPTION
**Pull request by stefson**
this was fixed in patchlevel 06 from a few days ago. 

@Whissi

### CODE REVIEW

**Comment by anarchpenguin** [comment]
> this was fixed in patchlevel 06 from a few days ago.
> 
> @Whissi

I have no problem pushing the update to the eclass. I do however need a signed-off added to the patch then I will get it pushed.

**Comment by stefson** [comment]
I thought to have signed it. Redid the commit and pushed forced it, is it now ok?

**Comment by anarchpenguin** [comment]
> I thought to have signed it. Redid the commit and pushed forced it, is it now ok?

Thank you, I have pushed it.

**Comment by stefson** [comment]
thanks, closing.

**Pull request closed without merging**
