### PR TITLE
keyword riscv for packages in app-portage

### PR DESCRIPTION
**Pull request by wiredhikari**

### CODE REVIEW

**Comment by jsmolic** [comment]
Have you verified that all of these packages have working tests or correctly work at runtime?

**Comment by wiredhikari** [comment]
Yes, I have tested this on RISC-V environment

**Comment by jsmolic** [comment]
You should use `pkgdev` for commiting changes (see https://wiki.gentoo.org/wiki/Pkgdev), notice 
```
app-portage/epkg
  IncorrectCopyright: version 0.4-r2: incorrect copyright year 2021: '# Copyright 1999-2021 Gentoo Authors'
```
warning which pkgdev would automatically fix when commiting.
You've also missed to keyword latest revision of app-portage/metagen, but I can fix that for you.

**Comment by jsmolic** [comment]
@wiredhikari I'm sorry, I had to revert the commits from this PR as it's unclear how these packages were tested and if they even work on RISC-V. The fact that some package compiles doesn't mean that "it works" or that it is even useful to anyone on RISC-V. In future please explain the rationale behind keywording a package and write some details about how it was actually proven to work at runtime.

**Pull request closed without merging**
