### PR TITLE
app-text/cherrytree: update

### PR DESCRIPTION
**Pull request by rindeal**
based on https://github.com/gentoo/gentoo/pull/1277

@idella

### CODE REVIEW

**Comment by idella** [comment]
inherit fdo-mime eutils distutils-r1
This ought be straight fwd but makes a never ending argument.  distutils-r1 now
```ebuild
[[ ${EAPI} == [45] ]] && inherit eutils
inherit toolchain-funcs
```
Before it unconditionally inheirted eutils. Iner EAPI 6 and now eutils need be explicitly inherited.  Well that reduces the argument at least.

**Comment by idella** [comment]
Another twist in the distutils-r1 tail;
# @ECLASS-VARIABLE: DISTUTILS_SINGLE_IMPL

# Note that inheriting python-single-r1 will cause pkg_setup()
# to be exported. It must be run in order for the eclass functions
# to function properly.

Also:
1. python_prepare_all() is a single run, so it is contradictory to do a 
l10n_for_each_disabled_locale_do rm_loc in a python_prepare_all(). It may work ok I am not sure.
2. The sed statement would fit in the python_prepare_all().
3. python_configure_all() I don't recall even seeing one of these. Check to see if there exists a 
distutils-r1_python_configure_all(), I think there isn't. If there is you need call it post use nls ||

**Comment by rindeal** [comment]
Actually, the new ebuild doesn't use `eutils` at all. I'll drop it in a moment.

1., 2.) When `DISTUTILS_SINGLE_IMPL` is set, all functions should behave normally (== no copying and no BUILD_DIR changes) and do only a single run. That means `python_prepare_all()` could be replaced by `src_prepare()`. Once this package adds support for multiple python versions, I'll figure out what needs to be run for all and what for each implementation.

3.) There is no such function as `distutils-r1_python_configure_all()`

**Comment by idella** [comment]
Use of python_prepare_all vs src_prepare is contentious. The purists insist that the eclass uses python_ so ebuilds should.  src_prepare can simply call the default distutils-r1_src_prepare which calls the python_prepare /  python_prepare_all duo. Personally I cannot be bothered arguing. 
w/e works

Considering  3.) There is no such function as distutils-r1_python_configure_all(), this ought be set as src_configure()

**Comment by rindeal** [comment]
Ok @idella, so I've renamed it to `src_configure()` and left `python_prepare_all()` as it was. Thanks for your thorough review.

**Comment by rindeal** [comment]
I've just found out `distutils-r1` has its own wiki page - https://wiki.gentoo.org/wiki/Project:Python/distutils-r1, which is a very good reading explaining quite everything.

Among other things it states:
> Overriding standard phase functions is discouraged

**Comment by idella** [comment]
not quite.
eclass/distutils-r1.eclass
```ebuild
# @ECLASS-VARIABLE: DISTUTILS_SINGLE_IMPL

# Note that inheriting python-single-r1 will cause pkg_setup()
# to be exported. It must be run in order for the eclass functions
# to function properly.
```

Alternatively you can just take out DISTUTILS_SINGLE_IMPL alltogether

**Comment by rindeal** [comment]
```
# @ECLASS-VARIABLE: DISTUTILS_SINGLE_IMPL

# Note that inheriting python-single-r1 will cause pkg_setup()
# to be exported. It must be run in order for the eclass functions
# to function properly.
```

This is just a reminder to call `python-single-r1_pkg_setup()` whenever someone overrides `pkg_setup()`, but this is not our case.

Taking out `DISTUTILS_SINGLE_IMPL` doesn't make sense to me as this package is an app, rather then a library. Also it would only add unnecessary complexities.

**Comment by idella** [comment]
This is not my understanding or interpretation.
This is from the notes by the eclass writer
" It will effectively replace the python-r1 eclass inherit with python-single-r1 "

The requirements change with the change of the selected eclass used as a backend. His notes (to me) indicate that the backend now being python-single-r1, it is required to explicitly set
 pkg_setup() { \  python-single-r1_pkg_setup
Even then this is slippery and allows room for getting wrong, depending upon whether the packahe has IUSE python.
At this point you need verify with the eclass writer directly, or drop the var DISTUTILS_SINGLE_IMPL all together. You will note it is hardly ever used and is imo more trouble then it is worth.

**Comment by rindeal** [comment]
`eclass-debug.log` shows that it runs just fine:
```
python-single-r1_pkg_setup: entering function, parameters:
python_setup: entering function, parameters:
python_export: entering function, parameters: python2_7 EPYTHON PYTHON
python_export: implementation: python2.7
python_export: EPYTHON = python2.7
python_export: PYTHON = /usr/bin/python2.7
python_wrapper_setup: entering function, parameters:
python_export: entering function, parameters: python2.7 EPYTHON PYTHON
python_export: implementation: python2.7
python_export: EPYTHON = python2.7
python_export: PYTHON = /usr/bin/python2.7
python_export: entering function, parameters: python2.7 PYTHON_CONFIG
python_export: implementation: python2.7
python_export: PYTHON_CONFIG = /usr/bin/python2.7-config
distutils-r1_src_prepare: entering function, parameters:
distutils-r1_python_prepare_all: entering function, parameters:
distutils-r1_src_compile: entering function, parameters:
_distutils-r1_run_foreach_impl: entering function, parameters: distutils-r1_python_compile
distutils-r1_run_phase: entering function, parameters: distutils-r1_python_compile
distutils-r1_python_compile: entering function, parameters:
esetup.py: entering function, parameters: build
```

Quick grepping through the tree show 78 packages are using it.

**Comment by idella** [comment]
get a confirmation from mgorny and I can add it. I have had unwanted grief with this before and it his his place to provide clarity here.

**Comment by rindeal** [comment]
@mgorny could you please take a look?

**Comment by mgorny** [comment]
@rindeal you are correct nad @idella is wrong.

**Comment by idella** [comment]
how brutally summarised

**Comment by idella** [comment]
3.) There is no such function as distutils-r1_python_configure_all()
In fact there is and it is used on other python ebuilds, but not a commonality. I shall change this back myself despite that it appears to take effect.

**Comment by rindeal** [comment]
The function is called `python_configure_all()`, with no `distutils-r1` prefix, and is called from `distutils-r1_src_configure()`. There is even a deprecated `distutils-r1_python_configure()`, but there is really no function with those names mixed together.

By renaming `python_configure_all()` to `src_configure()` we currently lost only `python_export_utf8_locale()`, which doesn't hurt so much. But as the wiki page suggests, the override should be dismissed.

All in all, I think that we should give this ebuild a well deserved rest until the next version bump.

**Comment by idella** [comment]
Perhaps you can rest, I can't

**Pull request closed without merging**
