### PR TITLE
net-p2p/nicotine+: add python 3.12 support

### PR DESCRIPTION
**Pull request by gentoo-setan**
also improved wording.

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by parona-source** [comment]
You don't need necessarily need a new revision here. 

The change to EPYTEST_IGNORE is subjective but I personally prefer it the previous way as if there are more broken test files you can just add them (or add comments for why this particular file is ignored [example](https://github.com/gentoo/gentoo/blob/master/dev-python/elasticsearch/elasticsearch-8.13.1.ebuild#L66)).

To be extra pedantic maybe blurb from upstream is a better description? https://github.com/Nicotine-Plus/nicotine-plus. To someone unfamiliar to nicotine sayings it a fork of it doesnt say much (the fork appeared to have happened over a decade ago either way), while sayings its a graphical client for soulseek tells a person a lot more.

**Comment by parona-source** [comment]
Would you be interested in bumping this to 3.3.4? 

It looks relatively straightforward (proper pep517, stuff moved to setup.cfg and directories moved).

Only thing I notice is that gettext is missing from BDEPEND and that the test maybe unnecessarily ignored. Id try to get that test working with virtualx as I guess that was the issue at the time.

https://devmanual.gentoo.org/eclass-reference/virtualx.eclass/index.html

**Comment by parona-source** [comment]
Oh and there is bug you can add a closes tag to https://bugs.gentoo.org/929736

**Comment by gentoo-setan** [comment]
> Would you be interested in bumping this to 3.3.4?
> ...  (proper pep517, stuff moved to setup.cfg and directories moved)
Yes I would, however my experience is close to none and I would like to finish this first.

For the BDEPEND i assume you mean adding a line like this?
`BDEPEND="sys-devel/gettext"`

Thanks for linking the virtualx as I did not know about it earlier.
Can you please suggest where to read more about testing and maybe some guilde if there is one?

**Comment by parona-source** [comment]
> For the BDEPEND i assume you mean adding a line like this?

Yes, this can be added without a new revision.

>  Can you please suggest where to read more about testing and maybe some guilde if there is one?

devmanual.gentoo.org is the most comprehensive place, but it wont address all situations and to my knowledge some stuff are undocumented where looking for examples in ebuilds is more helpful.  https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html

And Ill do one better. With packages that use python there is a larger guide made by mgorny. There is a lot here, but I think its good you check out the page that explains the which eclass is appropriate for any situation https://projects.gentoo.org/python/guide/eclass.html.

https://projects.gentoo.org/python/guide/test.html

**Comment by gentoo-setan** [comment]
Thanks for the links.
I'll look into upgrading the package.

**Comment by gentoo-setan** [comment]
@parona-source could you help me out [here](https://forums.gentoo.org/viewtopic-p-8828123.html#8828123)?
I will get the ebuild for the newest release in the repo

**Comment by parona-source** [comment]
Also with python3.12 timeline it would fine if you work on the bump in a different PR. This could be merged and the bump could be handled on its own.

**Comment by parona-source** [comment]
Please focus on the miscellaneous fixes in the bump instead.

**Comment by parona-source** [comment]
Well this PR ought to stay simple with the python3.12 bump. Like a bump is a better to place to handle maintenance debt. So id focus work on that.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
