### PR TITLE
java-pkg-simple.eclass: use --module-path for ejavadoc when applicable

### PR DESCRIPTION
**Pull request by 2Kmm**
Bug: https://bugs.gentoo.org/923599

### CODE REVIEW

**Comment by vaukai** [comment]
we might also need this for the [enhanced ejavadoc function](https://gitweb.gentoo.org/repo/gentoo.git/commit/eclass/java-utils-2.eclass?id=cb202546d81ed4e591c366d192e7b15d4c184ffa) in the `java-utils-2.eclass`. [multi module mode](https://www.logicbig.com/tutorials/core-java-tutorial/modules/modes.html) might be needed too.
Background for this enhancement is that for `multi-jar` ebuilds like `dev-java/batik` the `ejavadoc` function is unnecessarily called per each jar file and finally once again for all modules together. I've started converting ebuilds with JAVADOC_SRC_DIRS and calling `ejavadoc` in the ebuild.
later or sooner we should then try to get a full multi-jar support in `java-pkg-simple.eclass`.

**Comment by vaukai** [comment]
I thinks it would be better to change the bug reference in your commit message to https://bugs.gentoo.org/925691.
(don't forget putting [please reassign] to this PRs title)

**Comment by 2Kmm** [comment]
> I thinks it would be better to change the bug reference in your commit message to https://bugs.gentoo.org/925691. (don't forget putting [please reassign] to this PRs title)

Done :)

**Comment by vaukai** [comment]
@2Kmm 
thanks for your works on this `eclass`. i haven't had much time recently to participate, too busy on ant, bnd and tomcat.
do you think you could make this coding respect also the eclass variables `JAVADOC_CLASSPATH` and `JAVADOC_SRC_DIRS`so that we could finally revert commits [cb20254](https://github.com/vaukai/gentoo/commit/cb202546d81ed4e591c366d192e7b15d4c184ffa) and [0126d6a](https://github.com/vaukai/gentoo/commit/0126d6a3c2ef4dd488ceac132b8c5dca2490e96f)?

**Comment by 2Kmm** [comment]
@vaukai
I have not much time either, but maybe I can allocate some minutes the coming days.

**Comment by vaukai** [comment]
@fordfrog
could we please get this merged next? (i don't know if it's already sent to devs)
it solves the javadoc trouble for single-jar packages and should close https://bugs.gentoo.org/927893.
i've got some idea how to integrate it with our existing multi-jar javadoc and also want to try the multi module mode in my next works.

**Pull request closed without merging**
