### PR TITLE
Update supertuxkart to version 0.9.3

### PR DESCRIPTION
**Pull request by fx-carton**
This updates STK to version 0.9.3 and adds media-libs/libopenglrecorder (a new optional dependency for STK).

### CODE REVIEW

**Comment by doughdemon** [comment]
Thanks for your pull request!

As you can see, the gentoo-qa-bot is complaining. Please take a look at (all of) https://wiki.gentoo.org/wiki/Gentoo_GitHub .

It also seems that libopenglrecorder also depends on media-libs/libvorbis and has a build-time dependency on virtual/pkgconfig.

**Comment by chewi** [comment]
Many thanks, I'll try this later today.

**Comment by chewi** [comment]
Done, though I had to make many changes to libopenglrecorder in gentoo/gentoo@aa603dbb75d476cce89a9fb10a247f9d2910baab. Please commit with repoman in future to be pre-warned of these issues. Thanks!

Gah, missed the note about pkgconfig. I'll add that now.

**Comment by fx-carton** [comment]
Thanks for your changes. I'm a new gentoo user and didn't know about repoman. I'll use it now.

**Pull request closed without merging**
