### PR TITLE
Add new musl ppc64 [& hardened] 17.0 profiles

### PR DESCRIPTION
**Pull request by mjeveritt**
Signed-off-by: M. J. Everitt <m.j.everitt@iee.org>

### CODE REVIEW

**Comment by mjeveritt** [comment]
@blueness : sorry bud! :stuck_out_tongue: 
@gentoo-powerpc

**Comment by blueness** [comment]
I can't really add this since I'm not working with ppc64 + uclibc, only ppc 32-bit.  The litmus test is to be able to build stage3's using catalyst.  Have you done this?

**Comment by mjeveritt** [comment]
I'm in contact with the ppc team via IRC, and will get some testing underway.
Would you like the ppc32 profiles adding too?

**Comment by chewi** [comment]
Aww, @blueness, how can you say that after all that work I put into reviving timberdoodle? We also have bogsucker for ppc64le now. Still fighting my way through my backlog but yes, I could help here.

@mjeveritt, if you're referring to the wrapper trick, I don't think I used that from glibc to musl as I don't believe that's possible. It's only good for ABI-compatible migrations like going from armv7 to armv6 or *-hardfloat-* to *eabihf. The two options are cross-compiling from scratch with cross-boss or, as you say, using the migration script against an older stage if there is one.

**Comment by ajakk** [comment]
This is obsolete according to #gentoo-powerpc

**Pull request closed without merging**
