### PR TITLE
kernel-2.eclass cleanup and needed fixes in other ebuilds

### PR DESCRIPTION
**Pull request by hanetzer**
See also #8825

### CODE REVIEW

**Comment by mgorny** [comment]
Also @gentoo/kernel

**Comment by hanetzer** [comment]
@mgorny k, I just found using `git mv` to be quick and simple, since all the
ebuilds are the same, minus the filename.

**Comment by hanetzer** [comment]
Thefuck? How did those get in there...

**Comment by mgorny** [comment]
Ping. @hanetzer, can you try to get some attention here?

**Comment by juippis** [comment]
Is this still alive? I see zen-sources lack a maintainer. This PR doesn't seem to have anything to do with kernel-2.eclass though anymore.

**Comment by ConiKost** [comment]
Since it only contains commits for zen-sources and we have already 5.*, we can close here.

**Pull request closed without merging**
