### PR TITLE
net is a hard dependency

### PR DESCRIPTION
**Pull request by josephg5**
busybox-ntpd service starts and fails otherwise on my box

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Please read https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format.

**Comment by josephg5** [comment]
thank you @monsieurp for the prompt response. i can't get my head around what you need me to do. 

all i'm saying is that busybox-ntpd needs net and fails without net! if you think that is valid, feel free to change what you think is appropriate. if not, just ignore.

**Comment by SoapGentoo** [comment]
@josephg5 Your **COMMITMSG** doesn't follow the Gentoo format. In addition, you're changing an init file, without revbumping any ebuilds, meaning users won't automatically get the fix.

**Comment by josephg5** [comment]
thank you for explaining @SoapGentoo. sorry for the bother, as i am still a gentoo newbie, and a bit lost with the gentoo format. i'll mention this on the forums, and hope someone will pick this up, if anyone finds this useful.

**Comment by monsieurp** [comment]
I'm going to close this PR. @josephg5 feel free to add more commits to it if you want.

**Pull request closed without merging**
