### PR TITLE
app-text/tesseract: fix the ViewerDebugger/ScrollViewer

### PR DESCRIPTION
**Pull request by diotteo**
Link to the bug: https://bugs.gentoo.org/show_bug.cgi?id=572492

### CODE REVIEW

**Comment by monsieurp** [comment]
I've left a few notes that you should take into consideration ;) Also, could you please edit/rebase your two commits so that it matches the format we use?
"cat/pkg: commit message"
exactly like you did when opening the PR and giving it a title. Thank you.

**Comment by monsieurp** [comment]
@chutz @tom111

**Comment by monsieurp** [comment]
Also, please fix the QA warning. We cannot merge your PR unless QA is green.

**Comment by tom111** [comment]
@monsieurp He can't really fix those QA: piccolo3d needs a lot more keywords.

**Comment by diotteo** [comment]
Ok, I put in the changes as requested.

As for the QA checks, how should I proceed?
Should I reopen the piccolo2d pull request with all the keywords added? If so, I suppose I should bump it to -r1?

**Comment by tom111** [comment]
@diotteo keywords are only added by arch teams after testing.  You can start reading about this here: https://devmanual.gentoo.org/keywording/
I'll try to understand the situation later today or tomorrow.

**Comment by monsieurp** [comment]
Yeah but no. Java is supported for a few platforms only: amd64, ppc64 and x86. It's a tricky one. Maybe @chewi can chime in here?

**Comment by chewi** [comment]
And arm. The correct thing to do is mask the scrollview USE flag on the other platforms. So in `profiles/arch/{alpha,powerpc/ppc32,sparc}/package.use.mask`, you need:

```
app-text/tesseract scrollview
```

The ebuild isn't sufficient though. You should be using java-pkg-opt-2.eclass.

**Comment by tom111** [comment]
@chewi Is there a manual for java-pkg-opt-2.eclass somewhere? https://devmanual.gentoo.org/eclass-reference/java-pkg-opt-2.eclass/index.html is not helpful :(

**Comment by chewi** [comment]
[The wiki](https://wiki.gentoo.org/wiki/Java_Developer_Guide) should help though I can't vouch for its correctness. There is at least an example at the bottom. In this case, you want:

```sh
JAVA_PKG_OPT_USE="scrollview"
```

**Comment by diotteo** [comment]
The wiki doesn't quite say how to use java-pkg-opt-2 (OPT_ doesn't appear anywhere on the page).

That being said, the variable (JAVA_PKG_OPT_USE) appears in 3 different packages: `sci-mathematics/isabelle`, `sci-astronomy/cpl` and `app-admin/collectd`

`isabelle` appears to have only used `java-pkg-opt-2` in the first ebuild, using java-pkg-2 in all subsequent ebuilds. I'm not quite sure why, since that ebuild was authored in 2011 (based on the filenames) and git log doesn't go that far back (yet?).

Looking at the other two, they sometimes call the java-pkg-opt-2 version of the function they define, but sometimes not. Moreover, most of the packages that `inherit java-pkg-opt-2`, do just that even though some of them define functions which have a counterpart in java-pkg-opt-2.

I am not sure whether @tom111 wanted to fix the ebuild by himself or if the assumption was for me to resubmit a fixed ebuild, but I figure it may be helpful to figure out what is to be done here whichever may be the case.

Please let me know if I can help get this ebuild into the tree.

**Comment by tom111** [comment]
@diotteo Any research you can do on this is highly appreciated.  I had also read the wiki and come to the conclusion that I probably need to read the eclass itself to understand how to use it :-1: for Java. I'm busy with real life at the moment, so my resolution of this will be delayed. Please go ahead.

**Comment by diotteo** [comment]
Ok, based on the eclass and how it is used in the tree, this is my best guess as to what the ebuild should look like (I just pushed).

@chewi can you confirm whether it is now acceptable?

**Comment by monsieurp** [comment]
We're getting there. Could you please add the masks to the correct files as @chewi pointed out? The QA check hasn't passed yet.

**Comment by diotteo** [comment]
Ok, going by @chewi's comment I added the masks. Since the QA checks were also complaining about powerpc/ppc64 and arm, I masked those too.

**Comment by chewi** [comment]
Hi guys, sorry for the delay. I've taken @diotteo's work, reworked it a bit, and made some other improvements. I'll file another pull request when I'm done to run it by @tom111 first.

**Comment by chewi** [comment]
Superseded by #747.

**Pull request closed without merging**
