### PR TITLE
dev-python/pylatex: disable py3.7

### PR DESCRIPTION
**Pull request by janko-j1**
Signed-off-by: David Denoncin <ddenoncin@gmail.com>

### CODE REVIEW

**Comment by Flowdalic** [comment]
I am pretty sure that this does not require a revision bump. See python guide. I'd also just wait for the next version bump to remote py3.7.

**Comment by janko-j1** [comment]
> I am pretty sure that this does not require a revision bump. See python guide. I'd also just wait for the next version bump to remote py3.7.

Of course, I remember now, you told me last time. I did a revision bump because of @juippis' comment on my last PR (see the last comment on https://github.com/gentoo/gentoo/pull/24791): unless I misunderstood the both of you say something different here?

**Comment by juippis** [comment]
I think you misunderstood :) version != revision.

Basically, python-3.7 is just text without function right now in the ebuilds. You definitely do not revision bump to get rid of it. It's usually naturally phased out by version bumps, or other cleanups in the ebuild.

**Comment by janko-j1** [comment]
I understand your second paragraph, but I do not get the point I missed in your comment "Yes, with version/revision bumps whenever possible". Anyway I'll try and remember that adding or disabling a python version generally does not imply a revbump. I'll just disable 3.7 in the stable ebuild :-)

**Review by juippis — APPROVED** [review]
What I meant was, try to pair the removal with whatever other changes you're doing to the ebuild. Be it a version bump, or some other modification to the ebuild. There's no need to make a single commit just removing python-3.7 support...

**Pull request closed without merging**
