### PR TITLE
app-admin/collectd: Multiple sub slot operators (deps) set

### PR DESCRIPTION
**Pull request by Whissi**
I added some deps' slot operators.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
@jbergstroem please OK this set of changes.

**Comment by jbergstroem** [comment]
Ah, thanks for doing this. I'll make the assumption that you've gone through all deps and these are the only sub slots. LGTM.

**Comment by monsieurp** [comment]
Thanks for reviewing. Let's merge it then.

**Pull request closed without merging**
