### PR TITLE
profiles/base: use.mask dev-java/{ant-apache-,}bsf}[python] | profiles/package.mask: Last rite dev-java/jython 

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/825486

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog are there any objections against last riting `dev-java/jython`?

**Comment by fordfrog** [comment]
> @fordfrog are there any objections against last riting `dev-java/jython`?

i checked the github project and there is no jython-3 afaics, so imo it's ok to drop it. i'm just not sure about he process of dropping the use flags. is the mask needed or we can just drop them?

**Comment by vaukai** [comment]
> > @fordfrog are there any objections against last riting `dev-java/jython`?
> 
> i checked the github project and there is no jython-3 afaics, so imo it's ok to drop it. i'm just not sure about he process of dropping the use flags. is the mask needed or we can just drop them?

I think the procedure should be similar to what we did with [`dev-tex/pdfannotextractor`](https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/base/package.use.mask?id=0ab57a0eeb810d8b645170496a191baaae00404b) in https://github.com/gentoo/gentoo/pull/23049.
The difference is, we can remove `dev-java/jython` as it's maintained by Java team while we could not remove `pdfannotextractor` which is not maintained by Java team.
So the `package.use.mask` could stay until there is a reason to touch those use-masked ebuilds.

**Comment by fordfrog** [comment]
oki, done! you can send the email now.

**Pull request closed without merging**
