### PR TITLE
[ready] sys-kernel/ck-sources: v.bump (4.9.81)

### PR DESCRIPTION
**Pull request by kuzetsa**
Package-Manager: Portage-2.3.19, Repoman-2.3.6

### CODE REVIEW

**Comment by kuzetsa** [comment]
as per: https://github.com/gentoo/gentoo/pull/6942

This is the only branch getting updates at this time.

**Comment by gktrk** [comment]
@kuzetsa I don't get updates apparently for title changes, so I don't know when you go from `[nomerge]` to merge-ready. What's the status here? Are we good to go? What about #6942 ?

**Comment by kuzetsa** [comment]
per https://github.com/gentoo/gentoo/pull/7093#issuecomment-365148043 (comment)

Closed other PR, this one is ready.

@gktrk (*ping / mention will hopefully send a notification*)

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/49e97b6b6b3...26c33bc65a5. Thanks!

**Pull request closed without merging**
