### PR TITLE
sec-keys/openpgp-keys-apache-tomcat: add 9.0.72 | www-servers/tomcat: depend on jax-rpc-api | dev-java/jax-rpc-api: new package, add 1.1.4

### PR DESCRIPTION
**Pull request by vaukai**
Still think it's time to drop both [rm -rv java/javax/{el,servlet}](https://github.com/gentoo/gentoo/blob/master/www-servers/tomcat/tomcat-9.0.71-r1.ebuild#L91) and [adding to classpath](https://github.com/gentoo/gentoo/blob/master/www-servers/tomcat/tomcat-9.0.71-r1.ebuild#L106).

### CODE REVIEW

**Comment by fordfrog** [comment]
well, i just merged your changes which replace `dev-java/tomcat-servlet-api:4.0' with jakarta package so i think we can do it now, that's don't use el, jsp and servlet api external packages anymore and compile it within the tomcat ebuild. what do you think?

**Comment by vaukai** [comment]
> well, i just merged your changes which replace `dev-java/tomcat-servlet-api:4.0' with jakarta package so i think we can do it now, that's don't use el, jsp and servlet api external packages anymore and compile it within the tomcat ebuild. what do you think?

Yes. It should save you some work in future tomcat version bumps.  I am almost sure it should work, but I haven't tested. 
I also have https://github.com/gentoo/gentoo/pull/29591 providing the `javax` namespace for `javax-{el,jsp,servlet}-api`.

**Comment by fordfrog** [comment]
@vaukai , i picked some of your commits and bumped `tomcat-10.1.6` without all the external stuff.

**Comment by vaukai** [comment]
> @vaukai , i picked some of your commits and bumped `tomcat-10.1.6` without all the external stuff.

You did it?  I was having a look at the build.xml patches, then finally gave up.

**Comment by fordfrog** [comment]
i pretty simplified the patch, i patched only the parts that caused the ebuild to fail, now it's much smaller.

**Comment by fordfrog** [comment]
all tomcat versions bumped now. i think i merged all the relevant commits from this pr so closing the bug.

**Comment by vaukai** [comment]
> all tomcat versions bumped now. i think i merged all the relevant commits from this pr so closing the bug.

Thanks for picking up my proposal.

**Pull request closed without merging**
