### PR TITLE
dev-python/cssutils: add support for Python3.7, EAPI 7

### PR DESCRIPTION
**Pull request by arthurzam**
Updated this new ebuild to `EAPI=7`
Added support for Python3.7

I put the bug for `dev-python/cssutils` a week ago, without any response. So now I try to put up a Pull Request.
This Pull Request is needed for #11264.

Closes: https://bugs.gentoo.org/679494
Package-Manager: Portage-2.3.62, Repoman-2.3.12

### CODE REVIEW

**Comment by juippis** [comment]
EAPI bump requires a revbump for the ebuild (-r1), while adding python3.7 doesn't. I'd recommend you to just add python3.7 without bumping EAPI. 

And make sure you run tests / the python executable with python3.7 to test it :P

**Comment by arthurzam** [comment]
@juippis @monsieurp Thanks for your feedback.
I have added `-r1` to the ebuild. I have moved the file to the new revision, instead of saving the previous version without the revbump `1.0.2 -> 1.0.2-r1`. Is it OK?

**Comment by juippis** [comment]
I think in this case it's ok, but usually you want to make a new file and remove the old file with 2nd commit. It makes reverting changes easier, and better for users who might have trouble compiling the -r1 ebuild.

**Comment by arthurzam** [comment]
Well, after 5 days without reply, I guess it isn't OK in this PR.
I divided into adding version r1, and removing version r0

**Pull request closed without merging**
