### PR TITLE
dev-libs/nss: fix bitness check for LTO

### PR DESCRIPTION
**Pull request by thesamesam**
Closes: https://bugs.gentoo.org/917792

### CODE REVIEW

**Comment by thesamesam** [comment]
I would've ported it to the new toolchain-funcs helpers but I don't really fancy testing all the environments right now

**Review by juippis — COMMENTED** [review]
Is the **nssbits** check faulty, or is it actually broken with clang+lto? Because the lto flag is still stripped in `src_prepare`.

**Comment by thesamesam** [comment]
I've no reason to believe that it's broken on LTO - in this case, the issue is that the `file` check gets confused by LTO bitcode. I just forgot to clean up the other filter, fixing...

**Review by juippis — APPROVED** [review]
Thanks!

**Comment by thesamesam** [comment]
Thanks!

**Pull request closed without merging**
