### PR TITLE
media-gfx/graphviz: dev-scheme/guile requires USE=deprecated to be enabled

### PR DESCRIPTION
**Pull request by austin987**
Gentoo-Bug: https://bugs.gentoo.org/569516

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by austin987** [comment]
@lu-zero @maekke @radhermit @vapier

**Comment by Arfrever** [comment]
This change is incorrect and should not be merged.
dev-lang/swig should be fixed instead.

**Comment by austin987** [comment]
Care to elaborate? Or some reference link(s)?

**Comment by Arfrever** [comment]
See bug 491716. (Bug 569516 is duplicate of it.)

**Comment by austin987** [comment]
Thanks.

**Comment by austin987** [comment]
On Jul 3, 2016 4:11 PM, "Austin English" <austinenglish@gmail.com> wrote:
>
> Thanks.
>
> On Jul 3, 2016 11:39 AM, "Arfrever" <notifications@github.com> wrote:
>>
>> See bug 491716. (Bug 569516 is duplicate of it.)
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub, or mute the thread.

So it appears to be https://github.com/swig/swig/issues/312. @arfrever,
would you like to submit your patch upstream, or do you want me to?

**Comment by monsieurp** [comment]
@austin987 Hi! This PR has been sitting here without any review for many months and will likely bitrot due to a lack of interest in Github from maintainers. Let's cut it short and close it now. Please post your contribution in the bug report and ping them there. Thanks!

**Pull request closed without merging**
