### PR TITLE
 media-sound/gtklick and co: take maintainership

### PR DESCRIPTION
**Pull request by puleglot**

### CODE REVIEW

**Comment by mgorny** [comment]
Please bump those packages to EAPI 7, fix license and add slot operators.

**Comment by puleglot** [comment]
Sorry, but I don't see dependencies that needs slot operators.

**Comment by mgorny** [comment]
How about boost?

**Comment by mgorny** [comment]
Oh, you moved it to DEPEND.

**Comment by mgorny** [comment]
EAPI=7 really deserves a revbump. It is a potentially breaking change.

**Comment by puleglot** [comment]
> Oh, you moved it to DEPEND.

Yes, media-sound/klick doesn't link with boost. Only boost headers are needed at build time.

> EAPI=7 really deserves a revbump. It is a potentially breaking change.

Oops, I forgot to revbump media-sound/klick

**Pull request closed without merging**
