### PR TITLE
sci-electronics/iverilog: fix overwrite installation bug

### PR DESCRIPTION
**Pull request by vowstar**
The upstream's Makefile used a very unusual
installation method. It may cause overwrite
installation bug.
A fix pull request have been send to upstream
https://github.com/steveicarus/iverilog/pull/300
This ebuild fix will update all files' timestamp
before compile. This have tested on my overlay:
https://github.com/vowstar/vowstar-overlay

Closes: https://bugs.gentoo.org/705412
Package-Manager: Portage-2.3.84, Repoman-2.3.20
Signed-off-by: Huang Rui <vowstar@gmail.com>

### CODE REVIEW

**Comment by vowstar** [comment]
Combined https://github.com/gentoo/gentoo/pull/14376 to this PR.

**Comment by vowstar** [comment]
@a17r I have split it into two commits and merged them into this PR.

**Comment by vowstar** [comment]
ping

**Comment by vowstar** [comment]
ping

**Comment by vowstar** [comment]
@a17r @juippis 

I'm sorry to bother you. I want to fix this bug (https://bugs.gentoo.org/706366) . Should I open a new PR or just add a new commit here?

**Comment by juippis** [comment]
Please open a new PR. I've been meaning to find a better solution for this PR because what you're doing seems a bit weird and unnecessary.

**Comment by juippis** [comment]
> 
> About https://bugs.gentoo.org/705412 and this PR, I've send a fix to upstream
> [steveicarus/iverilog#300](https://github.com/steveicarus/iverilog/pull/300) , should it be a patch instead of `find . -exec touch {} + || die` ?

Yes please, if you've taken into account the feedback you got in that issue. I didn't read it all, I trust you know better.

**Comment by vowstar** [comment]
@juippis Thank you!

I've merged new bug fix (https://bugs.gentoo.org/706366) with latest commit,
The new commit have been sent to https://github.com/gentoo/gentoo/pull/14487

**Pull request closed without merging**
