### PR TITLE
app-containers/buildah: add 1.32.0

### PR DESCRIPTION
**Pull request by rahilarious**
Closes: https://bugs.gentoo.org/914417

My first time of writing ebuild in 3 years of daily driving of Gentoo. First times always feel great (no more virgin in ebuild-ing).

No more bugging already-busy devs with "version bump" bugs. Though baby step, but I'm proud of first ebuild. Please do the needful of QA & criticize.

### CODE REVIEW

**Comment by zmedico** [comment]
Thanks!

**Comment by rahilarious** [comment]
> Thanks!

Yay!!! I suppose the reason behind creating patch instead of `sed` is better readability?!

**Comment by zmedico** [comment]
> > Thanks!
> 
> Yay!!! I suppose the reason behind creating patch instead of `sed` is better readability?!

Readability, and also the patch will fail to apply if that line is modified upstream, while the sed command would silently fail to apply!

**Comment by rahilarious** [comment]
> Readability, and also the patch will fail to apply if that line is modified upstream, while the sed command would silently fail to apply!
Noted. Also added live version, check out  #32927

**Pull request closed without merging**
