### PR TITLE
*/*: migrate to tmpfiles.eclass

### PR DESCRIPTION
**Pull request by telans**
Migrates:
- `systemd_newtmpfilesd` to `newtmpfiles`
- `systemd_dotmpfilesd` to `dotmpfiles`
- `systemd_tmpfiles_create` to `tmpfiles_process`

No revbumps as functionality is identical

Tracker: https://bugs.gentoo.org/740638

### CODE REVIEW

**Comment by telans** [comment]
@gentoo-bot will be missed

**Comment by ConiKost** [comment]
Could you update to fix conflicts?

**Comment by telans** [comment]
Rebased

The only remaining usage of `systemd_dotmpfilesd|systemd_newtmpfilesd|systemd_tmpfiles_create` is within `toolchain-glibc.eclass`, but I didn't want to touch that.

**Comment by SoapGentoo** [comment]
@telans sorry for the massive delay, I have time now. Coudl you do a clean rebase, and then I will check it.

**Comment by telans** [comment]
Most recent push just makes sure the copyright is up to date

**Pull request closed without merging**
