### PR TITLE
dev-python/virtualenvwrapper: get absolute path for python executable

### PR DESCRIPTION
**Pull request by parona-source**
* Using the absolute path avoid issues when going inside the venv

### CODE REVIEW

**Comment by prometheanfire** [comment]
I understand the bug but I'm curious how you encountered it.

**Comment by prometheanfire** [comment]
I suppose what I'm asking for is a more full commit message (or link to a bug where the full issue is laid out).

**Comment by parona-source** [comment]
Well as the maintainer of the package I presumed Id get away with just fixing it rather than being verbose  :P

Issue is that it tries to use the python interpeter in venv if its not an absolute path.

```
 $ mkvirtualenv dotdroptest -p python3.10
created virtual environment CPython3.10.12.final.0-64 in 181ms
  creator CPython3Posix(dest=/home/ask/.virtualenvs/dotdroptest, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/ask/.local/share/virtualenv)
    added seed packages: pip==23.2, setuptools==68.0.0, wheel==0.40.0
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
/home/ask/.virtualenvs/dotdrop/bin/python3.11: Error while finding module specification for 'virtualenvwrapper.hook_loader' (ModuleNotFoundError: No module named 'virtualenvwrapper')
```

**Comment by prometheanfire** [comment]
Sorry, for some reason I thought I was maintaining it, I guess I've done stuff on it but never added myself as maintainer.

Thanks for your work on it :D

**Comment by prometheanfire** [comment]
merged, thanks for playing

**Pull request closed without merging**
