### PR TITLE
dev-java/antlr: Version bump to 4.9.3

### PR DESCRIPTION
**Pull request by Leo3418**
The commits in this pull request aim to update ANTLR to 4.9.3 to serve the following purposes:
- To update the package from a release that is nearly 6 years old,
- To aid documentation generation of `sci-mathematics/coq`, which requires ANTLR 4.7 or higher,
- To split `antlr-runtime` and `antlr-tool` just like in https://github.com/gentoo/gentoo/pull/23904, so this package can get rid of pre-built binaries entirely during the build process

### CODE REVIEW

**Comment by fordfrog** [comment]
`dev-java/antr-runtime`, `dev-java/json-api` and `dev-java/jol-core` merged.

**Comment by fordfrog** [comment]
for `dev-java/antlr-tool`, you should not call `java` directly but imo should instead retrieve it using `java-config -J`. it did not work for me, i got test failures. my system vm is `openjdk-17`. i did not have time to dig into this deeper but no matter what i set to `JAVA_PKG_FORCE_VM`, it always complained that source 6 is not supported, so it obviously always used `openjdk-17`.

**Comment by Leo3418** [comment]
> for `dev-java/antlr-tool`, you should not call `java` directly but imo should instead retrieve it using `java-config -J`. it did not work for me, i got test failures. my system vm is `openjdk-17`. i did not have time to dig into this deeper but no matter what i set to `JAVA_PKG_FORCE_VM`, it always complained that source 6 is not supported, so it obviously always used `openjdk-17`.

Fixed, although directly calling `java` should not be the root cause of the test failure on Java 17.  It's because one of the test sources would invoke `javac` with hard-coded `-source 1.6 -target 1.6` in the arguments.  It has been [patched](https://github.com/gentoo/gentoo/pull/24006/files#diff-cf2a8cac9ba8022f2de2fb9bd07809e34f9b790d62264d31d435c8f3e3ab1318) and tests should now pass on every Java version we currently have.

**Comment by fordfrog** [comment]
@Leo3418 merged, thanks!

**Pull request closed without merging**
