### PR TITLE
dev-util/idea-ultimate: Version bump

### PR DESCRIPTION
**Pull request by switch87**
version bump 14.1.5
version bump 16 EAP

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Thanks a lot for the PR. Please format the commit message according to our standards: "cat/pkg: commit msg".

**Comment by monsieurp** [comment]
@tomboy-64 @gentoo/proxy-maint

**Comment by monsieurp** [comment]
Please rebase/amend your commit and push it again to your branch. Editing the PR title on Github is not enough.

**Comment by switch87** [comment]
changed the commit message

**Comment by tomboy-64** [comment]
uhm ... why did you change the description from
Excel at enterprise, mobile and web development with Java, Scala and Groovy, with all the latest modern technologies and frameworks available out of the box.
to
Fully Integrated C/C++ Development Environment. ?

It's still foremost a JVM dev app; CLion is for C/C++.

**Comment by switch87** [comment]
ow... becouse I changed the wrong metadata file for my other PR. undid it.

**Comment by tomboy-64** [comment]
looks good to me. lgtm?

**Comment by tomboy-64** [comment]
looks good to me. (didn't test-merge them, though)

**Pull request merged**
