### PR TITLE
zmqpp version bump + multilib-strict fix

### PR DESCRIPTION
**Pull request by MathyV**

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi @MathyV. Could you please rebase this PR against master? Thanks!

**Comment by MathyV** [comment]
@monsieurp done

**Comment by monsieurp** [comment]
Thanks. Is there a bug report for this change?

**Comment by MathyV** [comment]
No, I thought this was no longer necessary for version bumps?

**Comment by monsieurp** [comment]
Come on.. you're squeezing in a fix. ;)

**Comment by MathyV** [comment]
@monsieurp a fix that was necessary for the version bump ;-)

**Comment by MathyV** [comment]
@monsieurp I think you forgot to commit the patch?

**Pull request closed without merging**
