### PR TITLE
media-tv/v4l-dvb-saa716x: updated ebuild for kernel 4.6 and up

### PR DESCRIPTION
**Pull request by madmartin**
- fixes Bug #612420
- fix repoman issue: shorten the ebuild description

Package-Manager: Portage-2.3.4, Repoman-2.3.2

### CODE REVIEW

**Comment by cjmayo** [comment]
This is needed for 4.10 and above (compile tested only), should be OK for earlier too.

```
--- a/linux/drivers/media/common/saa716x/saa716x_ff.h
+++ b/linux/drivers/media/common/saa716x/saa716x_ff.h
@@ -1,7 +1,6 @@
 #ifndef __SAA716x_FF_H
 #define __SAA716x_FF_H
 
-#include "dvb_filter.h"
 #include "dvb_ringbuffer.h"
 #include <linux/version.h>
 #include <linux/workqueue.h>
@@ -95,6 +94,7 @@
 #define MAX_RESULT_LEN		256
 #define MAX_DATA_LEN		(1024 * 1024)
 
+#define TS_SIZE			188
 #define TSOUT_LEN		(1024 * TS_SIZE)
 #define TSOUT_LEVEL_FILL	(350 * TS_SIZE)
 #define TSOUT_LEVEL_HIGH	(30 * TS_SIZE)
```

**Comment by cjmayo** [comment]
These two fix a lot of compiler warnings:
https://github.com/ljalves/linux_media/commit/eba969410ca1ae428455abd8d51a3298651a6886
https://github.com/ljalves/linux_media/commit/d9f9147c2de76463b0553745bace09610efaf8d8

**Comment by mgorny** [comment]
@madmartin, could you update the PR according to what @cjmayo pointed out? Alterantively, @cjmayo, can you submit a PR with all the changes necessary?

**Comment by madmartin** [comment]
@mgorny Changes implemented as requested

**Comment by mgorny** [comment]
Can we remove some of the old versions now?

**Comment by madmartin** [comment]
Hello @mgorny , yes, older ebuild versions can be removed. I propose to keep 0.0.1_p20140322 (oldest,stable) and 0.0.1_p20170225 (newest,unstable). Better I file a stabilization request for 0.0.1_p20170225 and we remove all older ebuilds afterwards.

**Comment by mgorny** [comment]
Sure. I'll then presume you'll file a PR cleaning up the old versions when done.

**Pull request closed without merging**
