### PR TITLE
media-video/jubler: Bump to 7.0.3

### PR DESCRIPTION
**Pull request by vaukai**
Jubler still has an issue with the launcher which cannot find the native library.  No clue how to solve this

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog 
@Flowdalic 
Still no luck to get this thing started.  The launcher is `/usr/bin/jubler` and it also has the `.desktop` entry which opens a graphical interface.  Starting it from console would open the same graphical interface and additionaly returns:
```
Using default language
Registering plugin Multi-platform application support
Registering plugin ASpell checker
Registering plugin Text subtitles
Registering plugin Basic tools
Registering plugin MPlayer media player
Registering plugin Zemberek spell checker
6 plugins found
32 plugin items found
4 listeners found
Unable to locate library ffdecode
```
Any attempt to set `-Djava.library.path` fails like:
```
 $(java-config -J) -Djava.library.path=/usr/lib64/jubler/ffdecode Jubler
Exception in thread "main" java.lang.NoClassDefFoundError: com/panayotis/jubler/os/ExceptionHandler
        at Jubler.main(Jubler.java:46)
Caused by: java.lang.ClassNotFoundException: com.panayotis.jubler.os.ExceptionHandler
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
        ... 1 more
```
What am I doing wrong, how could I get this solved?

**Comment by fordfrog** [comment]
is there still the issue with the launcher?

**Comment by vaukai** [comment]
> is there still the issue with the launcher?

Not really sure if it's an issue. The application window comes up and it seems to work.
I've tried to find out how it was done in version `5.1`, so I fixed [bug 753209](https://bugs.gentoo.org/753209) by removing the `doins dist/lib/*.jar` line. I could then install the old version but the launcher showed the same message `Unable to locate library ffdecode`.
I guess that [bug 753209](https://bugs.gentoo.org/753209) must have been there form beginning of version `5.1` since the `doins dist/lib/*.jar` line was already commented out in the version before.

Given that `5.1` does not compile at all and probably never did due to [bug 753209](https://bugs.gentoo.org/753209)  I'd propose to merge this PR as is and to keep `Unable to locate library ffdecode` for later.

Alternatively, `media-video/jubler` could be `last rited` with an extended period (3 months?) for removal. 

Otherwise I am (still) out of ideas.

**Comment by fordfrog** [comment]
maybe this is the cause?
```
 * QA Notice: Symbolic link /usr/lib64/jubler/libffdecode.so points to /usr/resources/ffmpeg/ffdecode/libffdecode.so which does not exist.
```

**Comment by vaukai** [comment]
> maybe this is the cause?
> 
> ```
>  * QA Notice: Symbolic link /usr/lib64/jubler/libffdecode.so points to /usr/resources/ffmpeg/ffdecode/libffdecode.so which does not exist.
> ```

I will check it within next days. thanks for merging.

**Pull request closed without merging**
