### PR TITLE
app-emulation/vagrant: Bump to 2.4.0

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Closes: https://bugs.gentoo.org/916978

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I just discover an issue while trying to manage the vagrant module:
```
/usr/lib64/ruby/site_ruby/3.1.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'grpc' (>= 1.56.0) - did find: [grpc-1.54.0] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/home/gseren/.gem/ruby/3.1.0:/usr/lib64/ruby/gems/3.1.0:/usr/local/lib64/ruby/gems/3.1.0' , execute `gem env` for more information
        from /usr/lib64/ruby/site_ruby/3.1.0/rubygems/dependency.rb:323:in `to_spec'
        from /usr/lib64/ruby/site_ruby/3.1.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        from /usr/lib64/ruby/gems/3.1.0/gems/vagrant-2.4.0/bin/vagrant:95:in `block (2 levels) in <main>'
        from /usr/lib64/ruby/gems/3.1.0/gems/vagrant-2.4.0/bin/vagrant:94:in `each'
        from /usr/lib64/ruby/gems/3.1.0/gems/vagrant-2.4.0/bin/vagrant:94:in `block in <main>'
        from /usr/lib64/ruby/gems/3.1.0/gems/vagrant-2.4.0/bin/vagrant:105:in `<main>'
```

**Comment by GuillaumeSeren** [comment]
Ok I found the issue the new vagrant-2.4.0 need grpc-1.59.2 witch need protobuf-3.24.4,
now it works, I have bump those packages and rebased the branch.

**Comment by GuillaumeSeren** [comment]
Hey,
I have upgraded the branch:
* app-emulation/vagrant: Upgrade rdep >=dev-ruby/grpc-1.59.2
* dev-ruby/grpc: Upgrade rdep >=dev-ruby/google-protobuf-3.24.4

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Actually I can't merge this without rebasing, since ruby-3.3 target has been added to some of these packages (and deps). Sorry for the delay, but could you rebase this against the current master?

**Comment by GuillaumeSeren** [comment]
Hey @juippis,
Thank you for the review I will rebase and upgrade the branch this week.

**Comment by GuillaumeSeren** [comment]
Hey @juippis,
I have upgraded the branch, 
* Adding ruby33 target.
* I tested with ruby31 only :/ (I need to work on a patch around this on ebuildtester, but if you have suggestion for better testing please do).
* The test flag works.
* I used this version on my machine for a while now and it works.
* I think a lot can be done to improve, but I also like to keep change small if I can.

**Review by juippis — APPROVED** [review]
Thanks, I'll fix the CI issues. Need to drop `~arm64` from vagrant because new dependencies don't have `~arm64` keyword yet. Please request re-keywording through bugzilla, including the new dependencies.

**Comment by GuillaumeSeren** [comment]
Thank you @juippis :trophy:

**Pull request closed without merging**
