### PR TITLE
app-text/podofo requires -std=c++11 to compile

### PR DESCRIPTION
**Pull request by antematherian**
On compilers where the default standard is lower
than c++11, the ebuild will fail to build.

The gcc compiler series up to but not including
gcc-6 is affected. gcc-6 hich switched from c++98
to c++14 as the default standard.

Issue tracked here: https://bugs.funtoo.org/browse/FL-3785

No equivalent issue was found on the Gentoo bugtracker.

### CODE REVIEW

**Comment by zmedico** [comment]
If I switch my compiler from gcc-6.3.0 to gcc-4.9.3 and uninstall cppunit, it builds for me without the `append-cxxflags -std=c++11`. I haven't bothered recompiling cppunit with gcc-4.9.3 to see if that makes any difference.

**Comment by zmedico** [comment]
If you built cppunit with `-std=c++11` in your CXXFLAGS then that explains your problem. In that case you have to build everything with `-std=c++11` in your CXXFLAGS, for ABI compatibility, as described here:

https://www.gentoo.org/support/news-items/2014-10-26-gcc_4_7_introduced_new_c++11_abi.html

**Comment by antematherian** [comment]
Thanks for the explanation. This is going to be more complicated than I thought. I'll open a new pull request when I have a proper fix.

**Comment by zmedico** [comment]
In 24598d33ad2f2c5f9c2077ad850fb7516f782bdd, I've disabled linking with cppunit whenever tests are not enabled (see [bug 620934](https://bugs.gentoo.org/show_bug.cgi?id=620934)).

**Pull request closed without merging**
