### PR TITLE
dev-games/aseprite: Stabilization on x86 (#590976)

### PR DESCRIPTION
**Pull request by winterheart**
Removed old 0.9.5-r1 as linked to Google Code.

Gentoo-Bug: https://bugs.gentoo.org/590976

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by gktrk** [comment]
Have you tested personally this on x86? Moreover, please do not stabilize and remove in a single commit, stabilization and removal of old should be separate.

**Comment by winterheart** [comment]
@gktrk Yes, I compiled and tested on x86.
Reworked commit into two, as you suggested.

**Comment by monsieurp** [comment]
Please provide a build log or a bpaste containing the log.

**Comment by winterheart** [comment]
@monsieurp, placed here - https://bugs.gentoo.org/show_bug.cgi?id=590976

**Pull request closed without merging**
