### PR TITLE
mail-client/evolution, gnome-extra/evolution-data-server, gnome-extra/evolution-ews: Version bump to 3.50.0

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
I see some new configuration options in evolution-data-server. I haven't checked the other packages.

- ENABLE_GI_DOCGEN
- ENABLE_TESTS

**Comment by mattst88** [comment]
```
@@ -32,6 +32,7 @@
 	>=gnome-extra/evolution-data-server-${PV}:=[gtk,weather?]
 	>=media-libs/libcanberra-0.25[gtk3]
 	>=net-libs/libsoup-3.0:3.0
+	>=app-crypt/libsecret-0.5
 	>=net-libs/webkit-gtk-2.38.0:4.1=[spell?]
 	>=x11-libs/cairo-1.9.15[glib]
 	>=x11-libs/gdk-pixbuf-2.24:2
```

It looks to me like you just randomly threw this new dependency into the list. Please understand how the dependencies are organized and put it in the appropriate place.

**Comment by flint2** [comment]
> ```
> @@ -32,6 +32,7 @@
>  	>=gnome-extra/evolution-data-server-${PV}:=[gtk,weather?]
>  	>=media-libs/libcanberra-0.25[gtk3]
>  	>=net-libs/libsoup-3.0:3.0
> +	>=app-crypt/libsecret-0.5
>  	>=net-libs/webkit-gtk-2.38.0:4.1=[spell?]
>  	>=x11-libs/cairo-1.9.15[glib]
>  	>=x11-libs/gdk-pixbuf-2.24:2
> ```
> 
> It looks to me like you just randomly threw this new dependency into the list. Please understand how the dependencies are organized and put it in the appropriate place.

Added in the same order that configure:
```
-- Checking for module 'libsecret-1>=0.5'
--   Found libsecret-1, version 0.21.0
-- Checking for module 'libsoup-3.0>=3.0'
--   Found libsoup-3.0, version 3.4.3

```

**Comment by flint2** [comment]
> I see some new configuration options in evolution-data-server. I haven't checked the other packages.
> 
>     * ENABLE_GI_DOCGEN
> 
>     * ENABLE_TESTS

Added ENABLE_GI_DOCGEN , there is a QA notice about document location that I don´t know how to fix
Added ENABLE_TESTS=ON, It does not configure if disabled

**Comment by mattst88** [comment]
Thanks.

It looks to me like the deps in evolution's ebuild are in alphabetical order, so I moved libsecret.

> Added ENABLE_GI_DOCGEN , there is a QA notice about document location that I don´t know how to fix

Yeah, I see this too. Let's ignore it for now -- probably almost no one enables gtk-doc.

>  Added ENABLE_TESTS=ON, It does not configure if disabled

Strange. It configures for me and disabling it allows for a significant compile-time reduction.

What error do you get with it disabled?

**Comment by flint2** [comment]
> Thanks.
> 
> It looks to me like the deps in evolution's ebuild are in alphabetical order, so I moved libsecret.
> 
> > Added ENABLE_GI_DOCGEN , there is a QA notice about document location that I don´t know how to fix
> 
> Yeah, I see this too. Let's ignore it for now -- probably almost no one enables gtk-doc.
> 
> > Added ENABLE_TESTS=ON, It does not configure if disabled
> 
> Strange. It configures for me and disabling it allows for a significant compile-time reduction.
> 
> What error do you get with it disabled?

Now configure OK with either ENABLE_TESTS ON or OFF, not sure what happened

**Pull request closed without merging**
