### PR TITLE
net-im/bitlbee: unbundle dev-libs/json-parser

### PR DESCRIPTION
**Pull request by arkamar**
This PR fixes multiple issues found in `net-im/bitlbee`. I decided to fix strict-aliasing issue and wrong libdir in pkgconfig file in `btilbee-3.6-r2` (first two commits) rev bump. However, the issue is in bundled library `dev-libs/json-parser` which is here proposed as a new package (third commit) and unbundled in `bitlbee-3.6-r3` rev bump (fourth commit). It is worth to say that `bitlbee` is not the only package in `::gentoo` which bundles `dev-libs/json-parser`, see linked bugs. The last commit is live ebuild sync. Please, see the commit messages for more info.

It was neccessary to drop `arm64`, `ppc`, `ppc64` and `x86` keywords from `bitlbee-3.6-r3` because `dev-libs/json-parser` is keyworded only with `~amd64`. I'll create keyword request if this PR will be accepted.

### CODE REVIEW

**Comment by thesamesam** [comment]
Did you mean to tag the Teeworlds and VLC bugs?

**Comment by arkamar** [comment]
Yes, they also use bundled `dev-libs/json-parser`, which makes this new ebuild related to them as well. But I can drop those links if it is too much.

**Comment by thesamesam** [comment]
No, it's fine, I just hadn't read the commit message yet. Oops.

**Comment by arkamar** [comment]
FP where I have added info about upstream PR https://github.com/bitlbee/bitlbee/pull/162 to the first commit.

**Review by juippis — APPROVED** [review]
Thanks for this massive effort!

**Pull request closed without merging**
