### PR TITLE
dev-qt: remove Qt 5.4.2

### PR DESCRIPTION
**Pull request by Pesa**
The PR is just to double check. I will handle it myself.

### CODE REVIEW

**Comment by Pesa** [comment]
@gentoo/qt @gentoo/kde any objections?

**Comment by johu** [comment]
@Pesa Please go ahead. We defined Qt min version 5.5.1 in kde5*.eclass already, so no objections from us.

**Comment by kensington** [comment]
Sounds good.

**Comment by Pesa** [comment]
68ecf80efed26cb35e3197057d6c32466c1cfa79

**Pull request closed without merging**
