### PR TITLE
sys-kernel/pf-sources: Update to 5.1_p7

### PR DESCRIPTION
**Pull request by hallabro**
If I remember it correctly @juippis was the one who updated this to EAPI 6 and made other improvements but I have since kept it updated it in a local overlay.

The current ebuild is very outdated and this package is in need of a maintainer. I think the package should be deleted or a new maintainer assigned.

Please see bug: https://bugs.gentoo.org/640366

### CODE REVIEW

**Comment by juippis** [comment]
Thanks for the initiative. My current ebuild implementation is a bit different from what you posted, it's a lot cleaner and up-to-date with modern standards, and it includes genpatches from Gentoo. I'll paste it below if you want to study the differences, and use some.

```
# Copyright 2018-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=6
ETYPE="sources"
KEYWORDS="~amd64 ~x86"

HOMEPAGE="
	https://gitlab.com/post-factum/pf-kernel/wikis/README
	https://dev.gentoo.org/~mpagano/genpatches/
	https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux
"

IUSE=""

# No 'experimental' USE flag provided, but we still want to use genpatches
K_EXP_GENPATCHES_NOUSE="1"

# No reason to bump this number unless something new gets included in genpatches, 
# in that case we can manually remove the linux kernel patches from genpatches.
K_GENPATCHES_VER="1"

K_NOSETEXTRAVERSION="don't_set_it"

# Not supported by the Gentoo crew
K_SECURITY_UNSUPPORTED="1"

K_USEPV="yes"

# We want the very basic patches from gentoo-sources, experimental patch
# is already included in pf-sources
K_WANT_GENPATCHES="base extras"

UNIPATCH_STRICTORDER="yes"

inherit kernel-2
detect_version

DESCRIPTION="Linux kernel fork that includes pf-kernel patch and Gentoo's genpatches"

PF_URI="https://github.com/pfactum/pf-kernel/compare/v${PV/_p*/}...v${PV/_p*/}-pf${PV/*_p/}.diff -> ${P}.patch"
SRC_URI="
	${KERNEL_URI}
	${PF_URI}
	https://dev.gentoo.org/~mpagano/genpatches/tarballs/genpatches-${PV/_p*/}-${K_GENPATCHES_VER}.base.tar.xz
	https://dev.gentoo.org/~mpagano/genpatches/tarballs/genpatches-${PV/_p*/}-${K_GENPATCHES_VER}.extras.tar.xz
"

KV_FULL="${PVR}-pf"
S="${WORKDIR}/linux-${KV_FULL}"

PATCHES=(
	"${DISTDIR}/${P}.patch"
)

K_EXTRAEINFO="For more info on pf-sources and details on how to report problems,
see: ${HOMEPAGE}."

pkg_setup(){
	ewarn
	ewarn "${PN} is *not* supported by the Gentoo Kernel Project in any way."
	ewarn "If you need support with the kernel, please contact the pf "
	ewarn "developers directly. If you need support with the ebuild, contact the "
	ewarn "package maintainer. Do *not* open bugs in Gentoo's bugzilla."
	ewarn
	kernel-2_pkg_setup
}

src_prepare() {
	default
	kernel-2_src_prepare
}

pkg_postrm() {
	kernel-2_pkg_postrm
}
```

(Even in that, the src_prepare part can probably be taken out, and it would still work)

Now if you intend to bring it to ::gentoo you should probably take out the whole message in pkg_setup :P 

Also I'd remove any older pf ebuilds, since they pose a security risk, and none is stabilized.

**Comment by hallabro** [comment]
@juippis thanks! I reused your ebuild but stripped `https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/linux` from `HOMEPAGE` (because I couldn't find any other references to it) and reinstated the proper warning in `pkg_setup`.

**Comment by monsieurp** [comment]
@juippis any comment on this PR?

**Comment by juippis** [comment]
@monsieurp yes :) I've tried to push pf-sources via proxy-maint project before and it has been declined, twice actually. If this is going get merged, I'd like to be added as a co-maintainer at least (I can be the sole maintainer as well, if @hallabro wishes) - since the ebuild offered is written by me. Other than that, looks good to me and I'm excited about reviving the status of pf-sources in Gentoo, whoever gets to maintain it.

@hallabro -pf3 is out already ;) one important note: `
the PDS-mq CPU scheduler has been replaced by the BMQ CPU scheduler`

**Comment by hallabro** [comment]
@juippis is probably the better maintainer of the two of us but I wouldn't mind helping out in case of absence or otherwise. I'm happy if we manage to prune the very outdated versions out of the tree. :smiley:

**Comment by mgorny** [comment]
Could you squash those commits? Especially drop interim versions.

**Comment by hallabro** [comment]
Updated to `5.0_p6` and sqashed!

**Comment by mgorny** [comment]
Please don't remove all the old versions at once. Also, removals belong in separate commit from addition.

**Comment by hallabro** [comment]
@mgorny Do you mean you want to keep any of the older versions? If so, which ones?

**Comment by mgorny** [comment]
Yes, that would be my suggestion that you keep at least the current newest version, so in case the new version caused new issues for someone, he could easily downgrade.

**Comment by mgorny** [comment]
We need your `Signed-off-by` on all commits, sorry.

**Comment by mgorny** [comment]
Also, any particular reason you've chosen to keep 4.8? I'm asking because that might be result of wrong sorting that missed 4.13 being newer.

**Comment by hallabro** [comment]
Yep, you're totally right about the lexical sorting. I'll fix it. :+1:

**Comment by mgorny** [comment]
What's the reason for removing non-x86 keywords?

**Comment by hallabro** [comment]
No idea. I'll reinstate them.

**Pull request closed without merging**
