### PR TITLE
Update dev-util/trace-cmd to 3.0.2 and dev-util/kernelshark to 2.1.0,…

### PR DESCRIPTION
**Pull request by chrschmidt**
Update dev-util/trace-cmd to 3.0.2 and dev-util/kernelshark to 2.1.0
Includes prerequisites dev-libs/traceevents and dev-libs/tracefs, which have been factored out from trace-cmd, and updated homepage URLs.
Created in response to stale bug https://bugs.gentoo.org/824982

### CODE REVIEW

**Comment by thesamesam** [comment]
- Could you split into one commit per package? (git reset HEAD (no --hard!) and pkgdev commit in each directory)?
- Commit summary (first line) should be like: `cat/pkg: foo`
- Use Bug/Closes tags in commits
- Include `Signed-off-by: Real Name <email>` in commits (at bottom)

**Comment by chrschmidt** [comment]
Withdrawing PR to address issues

**Comment by chrschmidt** [comment]
Reopened to review changes

**Comment by thesamesam** [comment]
You can figure out most of the CI warnings yourself (but let me know if you need help), but the unnecessary files one is because your local overlay probably has thin manifests _off_, but thin manifests are much more sensible for git repos, because git already assures the integrity of the whole repo.

**Pull request closed without merging**
