### PR TITLE
net-nds/389-ds-base: version bump

### PR DESCRIPTION
**Pull request by expeditioneer**

### CODE REVIEW

**Comment by Dessa** [comment]
diff against PR:
```
--- 389-ds-base-2.1.0.ebuild.1	2022-03-18 12:44:24.533743485 +0100
+++ 389-ds-base-2.1.0.ebuild	2022-03-18 12:34:18.431534009 +0100
@@ -1,7 +1,7 @@
 # Copyright 1999-2022 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
+EAPI=8
 
 CRATES="
 	ahash-0.7.6
@@ -116,7 +116,7 @@
 DISTUTILS_SINGLE_IMPL=1
 DISTUTILS_USE_SETUPTOOLS=rdepend
 
-inherit autotools distutils-r1 systemd tmpfiles db-use cargo
+inherit autotools distutils-r1 systemd tmpfiles cargo
 
 DESCRIPTION="389 Directory Server (core libraries and daemons)"
 HOMEPAGE="https://directory.fedoraproject.org/"
@@ -133,13 +133,12 @@
 # lib389 tests (which is most of the suite) can't find their own modules.
 RESTRICT="test"
 
-# always list newer first
 # Do not add any AGPL-3 BDB here!
 # See bug 525110, comment 15.
-BERKDB_SLOTS=( 5.3 )
 
 DEPEND="
 	>=app-crypt/mit-krb5-1.7-r100[openldap]
+	dev-db/lmdb:=
 	>=dev-libs/cyrus-sasl-2.1.19:2[kerberos]
 	>=dev-libs/icu-60.2:=
 	dev-libs/nspr
@@ -148,11 +147,9 @@
 	dev-libs/libpcre:3
 	dev-libs/openssl:0=
 	>=net-analyzer/net-snmp-5.1.2:=
-	>=net-nds/openldap[sasl]
-	|| (
-		$(for slot in ${BERKDB_SLOTS[@]} ; do printf '%s\n' "sys-libs/db:${slot}" ; done)
-	)
+	net-nds/openldap[sasl]
 	sys-libs/cracklib
+	sys-libs/db:5.3
 	|| ( sys-fs/e2fsprogs sys-libs/e2fsprogs-libs )
 	pam-passthru? ( sys-libs/pam )
 	selinux? (
@@ -176,7 +173,7 @@
 
 # perl dependencies are for logconv.pl
 RDEPEND="${DEPEND}
-	!net-nds/389-ds-base:0
+	!net-nds/389-ds-base:1.4
 	acct-user/dirsrv
 	acct-group/dirsrv
 	${PYTHON_DEPS}
@@ -243,7 +240,7 @@
 		--with-pythonexec="${PYTHON}"
 		--with-fhs
 		--with-openldap
-		--with-db-inc="$(db_includedir)"
+		--with-db-inc="${EPREFIX}"/usr/include/db5.3
 		--disable-cockpit
 	)
 
```
Please also in-place revbump 1.4 with a blocker against 2.1, just as i did here with 1.4

**Comment by expeditioneer** [comment]
@Dessa if you are agree to the Code I would merge this PR.

**Comment by Dessa** [comment]
please add the 2.1 blocker to the 1.4 ebuild as i said.
when that's done, it'll get my +1

**Review by Dessa — APPROVED** [review]

**Comment by Dessa** [comment]
> Why is this slotted?
to avoid surprises with replication, i opted for mysql-like slotting initially #17049 comment 1

> also, revbump to add blockers.
i uh. said that but i didn't look close enough if it was done, my bad.

**Comment by thesamesam** [comment]
Sorry, wrote previous comment on mobile, so bit terse.

I don't think the slots are really going to be useful for doing that -- they just make it look like they're parallel installable, even if they're not. I think it's confusing for UX. You can use subslost to pin to specific releases.

MySQL and MariaDB does this as does Firefox (I think it's less of an issue w/ Firefox because it's never even a library), but I think for MySQL and MariaDB it's particularly confusing given that PostgreSQL is _really_ slotted.

A news item should be given or something if we need people to exercise care. Slots don't really achieve anything special here -- the new version is still going to be installed if people have it in world w/o some more specific info, IMO.

**Pull request closed without merging**
