### PR TITLE
media-sound/supercollider: Bump to 3.11.2

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Closes: https://bugs.gentoo.org/755719
Signed-off-by: Simon van der Veldt <simon.vanderveldt+gentoo@gmail.com>

@marcan I had a bit of time to spare and wanted the latest release to test the boost issue so figured I might as well create a PR :)

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
```
[ebuild  N     ] media-sound/supercollider-3.11.2::testworld  USE="emacs fftw server vim -X -debug -gedit -gpl3 -jack -qt5 -sndfile -static-libs -webengine -zeroconf" CPU_FLAGS_X86="sse sse2" 0 KiB
```
```
-- FFT library (supernova): FFTW
CMake Error at server/supernova/CMakeLists.txt:155 (message):
  Cannot find libsndfile


-- Found ALSA: /usr/lib64/libasound.so (found version "1.2.4") 
-- Found GNU Readline version 8.0: /usr/lib64/libreadline.so
-- Compiling with Ableton Link support
-- Compiling with Readline support
-- Looking for wsyncup in /usr/lib64/libcurses.so
-- Looking for wsyncup in /usr/lib64/libcurses.so - found
-- Looking for cbreak in /usr/lib64/libncurses.so
-- Looking for cbreak in /usr/lib64/libncurses.so - not found
-- Looking for nodelay in /usr/lib64/libncurses.so
-- Looking for nodelay in /usr/lib64/libncurses.so - not found
-- Found Curses: /usr/lib64/libncurses.so  
-- Compiling with ALSA midi support
CMake Warning at editors/CMakeLists.txt:31 (message):
  SC_VIM requested, but NO_GPL3 flag is on, so not activated.


-- <<< Gentoo configuration >>>
Build type      Gentoo
Install path    /usr
Compiler flags:
C               -march=native -O2 -pipe -frecord-gcc-switches -DNDEBUG   -msse -mfpmath=sse -msse2
C++             -march=native -O2 -pipe -frecord-gcc-switches -DNDEBUG -msse -mfpmath=sse -msse2
Linker flags:
Executable      -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Module          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0
Shared          -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0

-- Configuring incomplete, errors occurred!
See also "/var/tmp/portage/gpm/portage/media-sound/supercollider-3.11.2/work/supercollider-3.11.2_build/CMakeFiles/CMakeOutput.log".
See also "/var/tmp/portage/gpm/portage/media-sound/supercollider-3.11.2/work/supercollider-3.11.2_build/CMakeFiles/CMakeError.log".
 * ERROR: media-sound/supercollider-3.11.2::testworld failed (configure phase):
 *   cmake failed
```
Sooo maybe sndfile is not so optional?

**Comment by simonvanderveldt** [comment]
@juippis Is this a new error for 3.11.2? The relevant code hasn't been touched in 9 years https://github.com/supercollider/supercollider/blame/Version-3.11.2/server/supernova/CMakeLists.txt#L153

**Comment by juippis** [comment]
Weirdly it seems to work with *media-sound/supercollider-3.11.0-r1*.

FYI this also didn't compile with `qt5` enabled, can you test?

**Comment by simonvanderveldt** [comment]
> Weirdly it seems to work with _media-sound/supercollider-3.11.0-r1_.

Hmm, that's strange. I'll look into this some more. Probably has something do to with the patches then.



> FYI this also didn't compile with `qt5` enabled, can you test?

My personal/local config is `media-sound/supercollider jack server qt5 X` and that emerged and ran fine.

**Comment by thesamesam** [comment]
I merged this in its current state because of this [bug](https://bugs.gentoo.org/760489) with the new stable Boost. I managed to get both GUI and non-GUI building.

**Pull request closed without merging**
