### PR TITLE
sys-apps/ucspi-ssl: version alias

### PR DESCRIPTION
**Pull request by powerman**
Bug: https://bugs.gentoo.org/686430
Package-Manager: Portage-2.3.76, Repoman-2.3.16
Signed-off-by: Aleksandr Efros <powerman-asdf@yandex.ru>

### CODE REVIEW

**Comment by powerman** [comment]
@juippis This ebuild is same as existing ucspi-ssl-0.99e.ebuild, only difference is version (needed because author has released 0.10.11 as **newer** than 0.99e - see https://www.fehcom.de/ipnet/ucspi-ssl.html). Here is full diff:
```diff
--- ucspi-ssl-0.99e.ebuild	2019-05-21 03:36:19.885895173 +0300
+++ ucspi-ssl-0.0.99e.ebuild	2019-12-09 09:18:06.957092614 +0200
@@ -5,9 +5,10 @@
 
 inherit fixheadtails qmail
 
+MY_P="${P/0./}"
 DESCRIPTION="Command-line tools for building SSL client-server applications"
 HOMEPAGE="https://www.fehcom.de/ipnet/ucspi-ssl.html"
-SRC_URI="https://www.fehcom.de/ipnet/ucspi-ssl/${P}.tgz"
+SRC_URI="https://www.fehcom.de/ipnet/ucspi-ssl/${MY_P}.tgz"
 
 LICENSE="public-domain"
 SLOT="0"
@@ -20,7 +21,7 @@
 RDEPEND="${DEPEND}
 	sys-apps/ucspi-tcp"
 
-S="${WORKDIR}"/host/superscript.com/net/${P}
+S="${WORKDIR}"/host/superscript.com/net/${MY_P}
 
 src_prepare() {
 	ht_fix_all
```

**Comment by juippis** [comment]
So which one should be merged first, the new version or this one?

**Comment by powerman** [comment]
> So which one should be merged first, the new version or this one?

No difference, this one will replace existing versions, new one will provide an upgrade for this one.

**Comment by powerman** [comment]
@juippis Please finish your review.

**Comment by mgorny** [comment]
What about all the remaining 0.9* versions? Aren't they affected as well?

**Comment by powerman** [comment]
@mgorny Sure, but I belive we should merge these 2 PRs before removing remaining 0.9* version - isn't it? Adding new ebuilds for 0.0.9x and 0.10.x shouldn't affect existing installations, then we should somehow let users either replace existing 0.9x with 0.0.9x or upgrade to 0.10.x - I've no idea how this should be done, maybe just by removing existing 0.9x ebuilds, or maybe there is some feature in portage suitable for this use case.

**Comment by juippis** [comment]
Sorry for not noticing progress on this. 

Since there is only 2 packages in ::gentoo depending on this, I suggest:
 - we merge 0.10, 
 - we stabilize 0.10 immediately on arches that reverse deps have stable keywords, 
 - we remove 0.99 after stabilization is done, causing people to downgrade but such is life.

Looking at https://packages.gentoo.org/packages/mail-mta/netqmail every arch needs to be stabilized. I wonder if we can drop keywords from netqmail and ucpi-ssl from... lesser active arches?

**Comment by powerman** [comment]
@juippis I don't see why we must drop 0.0.99 immediately. 0.10 wasn't tested much, for obvious reasons. But if you believe it's good idea to drop 0.0.99 - I've nothing against this, let's drop it.

As for arches - I've no idea is they all really used by someone or not and what happens if we'll drop some of them.

**Comment by juippis** [comment]
Well the drop won't be immediate since we have to pretty much stabilize it on every arch due to netqmail. 

And sorry I didn't mean to drop keywords, but raise them back to ~. However we can merge 0.10, start stabilization and it will take a while.

**Comment by powerman** [comment]
I've switched from qmail to postfix and don't use this package anymore.

**Pull request closed without merging**
