### PR TITLE
dev-python/pypy3: fix regression in tkinter

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo-bug: 533384

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/python

**Comment by mgorny** [comment]
Looks good, however… do you happen to know any other problems with the (rather outdated) PyPy3 version? Since it's pretty time-consuming to build, it would be nice to add more patches if possible, for one rebuild ;-).

**Comment by PPed72** [comment]
In data domenica 24 aprile 2016 22:21:46 CEST, Michał Górny ha scritto:
> Looks good, however… do you happen to know any other problems with the
> (rather outdated) PyPy3 version? Since it's pretty time-consuming to build,
> it would be nice to add more patches if possible, for one rebuild ;-).

Nothing more (that I know of, at least).

-- 
Paolo Pedroni
Email: paolo.pedroni<at>iol.it

**Comment by mgorny** [comment]
Since this involves library files, could you add the patch to pypy3-bin as well, please?

**Comment by PPed72** [comment]
Shall I bump the ebuild revision or just modify the current one?

**Comment by PPed72** [comment]
Replying to myself: after seeing some of the package history on p.g.o, I don't think I'm wrong if I just add the patch to current ebuild revision. Please correct me if I am ;-)

**Comment by monsieurp** [comment]
@floppym could you review this patch as well and sign off on it? thx!

**Comment by floppym** [comment]
Looks ok to me.

**Pull request closed without merging**
