### PR TITLE
sys-fs/xfs{progs,dump}: proper handling of locale files

### PR DESCRIPTION
**Pull request by jvesely**
Proper handling of locale files
https://bugs.gentoo.org/show_bug.cgi?id=561664

### CODE REVIEW

**Comment by monsieurp** [comment]
@blueness

**Comment by monsieurp** [comment]
@blueness ping?

**Comment by blueness** [comment]
@monsieurp these belong to base-system and i'm not a part of base-system.  also they make changes to existing ebuilds rather than rev-bumping.  whenever an ebuild changes what files might be one the filesystem,

**Comment by monsieurp** [comment]
fair enough. can @vapier maybe pitch in?

**Comment by jvesely** [comment]
I have added -r1 (~arch) for stable packages. and also LINGUAS support for ~arch xfsprogs since <4.5.0 fails to build with latest linux-headers

**Comment by vapier** [comment]
the l10n eclass is a big hammer.  it's generally preferable to get the issue fixed in the source itself and send it upstream.  i've done that now for both xfsdump & xfsprogs.

see commit 66fdb7748f7595e3f467797b46047b8a4b177c2e and commit 32b41cf94528d0012231b59123a61b67fb7ca373.

**Comment by jvesely** [comment]
Thanks, better fix is ... better. Although it would be nice if the LINGUAS were exported, so portage tools could show which languages are installed.

**Pull request closed without merging**
