### PR TITLE
Add myself as proxy maintainer for sys-fs/bcache-tools

### PR DESCRIPTION
**Pull request by pvgoran**

### CODE REVIEW

**Comment by pvgoran** [comment]
Being a long-time user of both Gentoo and bcache, I want to take care of `sys-fs/bcache-tools` which seems to have been orphaned for a while.

**Comment by pvgoran** [comment]
Sign-off line now added.

**Comment by Flowdalic** [comment]
@pvgoran Are you still interested in co-maintaining bcache-tools (together with me)?

**Comment by pvgoran** [comment]
@Flowdalic Yes.

**Comment by Flowdalic** [comment]
Then feel free to update the PR accordingly. You may also want to add [please reassign] to the title afterwards.

**Comment by Flowdalic** [comment]
Closing due inactivity, feel free to re-open if necessary.

**Pull request closed without merging**
