### PR TITLE
dev-cpp/simpleini: install cmake config files

### PR DESCRIPTION
**Pull request by nE0sIghT**
Without this only header file is installed

### CODE REVIEW

**Comment by ionenwks** [comment]
Did consider cmake when it became more usable recently (I already have my own local branch to use cmake), but decided to leave it alone for now, see message in commit 2d7190383288

Was thinking to look again next devilutionx bump or so, felt no urgency given its the only revdep in ::gentoo that I have to worry about.

**Comment by nE0sIghT** [comment]
Got it. Simpleini is dependency of suyu which I try to include in my overlay, so it would be nice to have cmake configs.

**Comment by ionenwks** [comment]
Well, if something needs it guess I could take this then.

But I'll have a look at fixing devilutionx at same time.

**Comment by ionenwks** [comment]
> Well, if something needs it guess I could take this then.
> 
> But I'll have a look at fixing devilutionx at same time.

Oh wait I see, actually there's no need. The simpleini-4.22-include-dir.patch you included sorts that out. Thanks for that (had looked at this back in December so that wasn't upstream yet).

Well devilutionx should still switch to find_package() eventually but not going to be an issue.

**Pull request closed without merging**
