### PR TITLE
gui-libs/gtk: add 4.15.0

### PR DESCRIPTION
**Pull request by PeakKS**
add 4.15.0

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by jospezial** [comment]
4.15.x is the last version that works with gstreamer-1.22
https://gitlab.gnome.org/GNOME/gtk/-/tags/4.15.6
See also https://github.com/gentoo/gentoo/pull/38629

**Comment by jospezial** [comment]
Your ebuild is missing a lot of changes made in the last months to gui-libs/gtk in Gentoo tree.

**Comment by jospezial** [comment]
See also https://github.com/gentoo/gentoo/pull/38636

**Comment by jospezial** [comment]
gtk-4.15 was the transition from gstreamer 1.22 over 1.23 to 1.24. So this PR has no use for us with gtk-4.16 released.
Please close.

**Comment by PeakKS** [comment]
> gtk-4.15 was the transition from gstreamer 1.22 over 1.23 to 1.24. So this PR has no use for us with gtk-4.16 released. Please close.

Not sure why you are looking at this, it's obviously outdated as it is 5 months old.

**Comment by jospezial** [comment]
I was hoping to bump to libadwaita-1.6.0.ebuild without bumping to gstreamer-1.24.

**Pull request closed without merging**
