### PR TITLE
Create new 17.0 arm64 musl & uclibc [+ hardened] profiles

### PR DESCRIPTION
**Pull request by mjeveritt**
Per request on #gentoo-arm from @Necktwi via @Chewi
Signed-off-by: M. J. Everitt <m.j.everitt@iee.org>

### CODE REVIEW

**Comment by mjeveritt** [comment]
@blueness Hai :smile:

**Comment by blueness** [comment]
I have the same problem as with ppc64 uclibc profiles.  I can't build the stage3's.  I don't want to add profiles to the tree we don't use.  So do you have stage3's for any of these profles?

**Comment by mjeveritt** [comment]
I don't personally yet .. but I have hardware to test with.
Would you be amenable to setting up a builder on the OSL Cavium Thunder box Gentoo has for these perhaps? I believe @leio should have credentials to get you in ..

**Comment by chewi** [comment]
I have access to that box now. This will require cross-building so I guess it's my job!

**Comment by blueness** [comment]
arm64 musl is done.

**Comment by scardracs** [comment]
Kind ping. I don't think uclibc is still a thing.. Is this PR still valid or can be closed?

**Comment by chewi** [comment]
uClibc is gone. We can close this now.

**Pull request closed without merging**
