### PR TITLE
mail-client/neomutt: add 20231023

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/915323

### CODE REVIEW

**Comment by listout** [comment]
Some test results https://0x0.st/HyqF.log

**Comment by mschiff** [comment]
There is already version 20231023 out, maybe you can update your PR?

**Comment by listout** [comment]
> There is already version 20231023 out, maybe you can update your PR?

Thanks a lot, didn't notice it.

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Thanks for submitting this PR!

Looks good overall, but I wonder why you removed the `asan` USE flag.

**Comment by listout** [comment]
Huh, maybe I missed something but I don't see a `asan` use flag in neomutt-20230517 ebuild. I used neomutt-20230517.ebuild and the pkgbump script.

**Comment by nicolasbock** [comment]
That flag was added in the `-r1` revision.

**Comment by listout** [comment]
```
~/g/mail-client/neomutt neomutt-vbump-20231006 22s
>> rg asan

~/g/mail-client/neomutt neomutt-vbump-20231006
>>
```

**Comment by nicolasbock** [comment]
Oops, you are right. That revision is on my local branch and I haven't pushed that the tree yet 😞 Sorry for the confusion.

**Review by nicolasbock — APPROVED** [review]

**Comment by nicolasbock** [comment]
Thanks for the PR!

**Pull request closed without merging**
