### PR TITLE
dev-python/sphinx-autoapi: add new package

### PR DESCRIPTION
**Pull request by mjsir911**
Required to compile documentation for some other packages eg app-misc/khard

### CODE REVIEW

**Review by andrey-utkin — CHANGES_REQUESTED** [review]
Thanks for the patch.

Does this require pulling the `autoapi` package as a dependency? Seems so to me.

Building this ultimately fails for me, first thing being
```
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/var/tmp/portage/dev-python/sphinx-autoapi-1.8.4/work/sphinx-autoapi-1.8.4/docs/conf.py", line 55, in <module>
    import autoapi
ModuleNotFoundError: No module named 'autoapi'
```

Strangely, on that it doesn't stop and it goes until it tries to install something which hasn't been built apparently:
```
 * Using python3.9 in global scope
 * python3_9: running distutils-r1_run_phase distutils-r1_python_install_all
Traceback (most recent call last):
  File "/usr/lib/portage/python3.9/doins.py", line 607, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/usr/lib/portage/python3.9/doins.py", line 596, in main
    if _doins(
  File "/usr/lib/portage/python3.9/doins.py", line 439, in _doins
    return install_runner.install_file(source, os.path.dirname(dest))
  File "/usr/lib/portage/python3.9/doins.py", line 373, in install_file
    return self._ins_runner.run(source, dest_dir)
  File "/usr/lib/portage/python3.9/doins.py", line 181, in run
    sstat = os.stat(source)
FileNotFoundError: [Errno 2] No such file or directory: b'html/.'
```

**Comment by thesamesam** [comment]
One PR is usually easier for combined changes as long as it's one commit per package but done now. I've left comments on the sphinx-autoapi ebuild in the other PR: https://github.com/gentoo/gentoo/pull/24386.

The build continues because of a missing `die`.

**Comment by mjsir911** [comment]
> Building this ultimately fails for me, first thing being

Thanks for catching this! Fixed it now with `PYTHONPATH=.` on the sphinx-build which is kinda icky if any better ways are suggested.

**Comment by andrey-utkin** [comment]
I agree with Sam https://github.com/gentoo/gentoo/pull/24385#issuecomment-1056036177
and suggest we close this PR and focus on both new package and khard flag addition in the same PR https://github.com/gentoo/gentoo/pull/24386 .

**Pull request closed without merging**
