### PR TITLE
games-fps/freedoom-data: Set DOOMWADPATH in freedoom launch script

### PR DESCRIPTION
**Pull request by vilhelmgray**
Engines such as Odamex may not have a default search path and simply
search for freedoom1.wad relative to the current directory. This can
cause an unexpected WAD file not found error when executing the freedoom
script.

This issue is mitigated by setting a default DOOMWADPATH environment
variable with sensible search paths, if it is not already set. All
engines listed in the PORTS variable support the DOOMWADPATH environment
variable, which makes it a simple and convenient way of helping prevent
this error.

### CODE REVIEW

**Comment by chewi** [comment]
To make this work on prefix, you should use `hprefixify` from `prefix.eclass` against the scripts in `src_prepare`.

**Comment by vilhelmgray** [comment]
> To make this work on prefix, you should use `hprefixify` from `prefix.eclass` against the scripts in `src_prepare`.

The patch is pretty simple so I opted instead to update it to use `@GENTOO_PORTAGE_EPREFIX@` and called **eprefixify** in the ebuilds.

**Comment by chewi** [comment]
Right but this patch has been accepted upstream and they obviously cannot add `@GENTOO_PORTAGE_EPREFIX@`. Just calling `hprefixify dist/freedoom` with no modifications will do what you need.

**Comment by vilhelmgray** [comment]
> Right but this patch has been accepted upstream and they obviously cannot add `@GENTOO_PORTAGE_EPREFIX@`. Just calling `hprefixify dist/freedoom` with no modifications will do what you need.

I see what you mean. I've updated it now to use **hprefixify** instead as you suggest.

**Pull request closed without merging**
