### PR TITLE
net-print/hplip-plugin: bump to 3.19.8

### PR DESCRIPTION
**Pull request by xdch47**
Package-Manager: Portage-2.3.69, Repoman-2.3.17
Signed-off-by: Felix Neumärker <xdch47@posteo.de>

### CODE REVIEW

**Comment by elsandosgrande** [comment]
https://bugs.gentoo.org/694480

You're welcome @xdch47!

**Comment by elsandosgrande** [comment]
Is this going to get approved, or...?

**Comment by xdch47** [comment]
giving up - better using an overlay …

**Comment by elsandosgrande** [comment]
Wow... This is a sad situation. Oh well...

**Comment by a17r** [comment]
@billie80 per earlier discussion, is it safe to assume that printing team does not maintain hplip-plugin and others should maintain the package if they so wish? or would you be willing to add a proxy-maintainer to metadata.xml and consider their PRs in the future?

**Comment by billie80** [comment]
According to Git history hplip-plugin was maintained primarily by Michael Rüger (mrueg) who also added the printing team as maintainer. He stopped doing so since 3.19.5.
I helped bumping to 3.19.6 but consider this an exception. Also I am not a member of the printing team I only maintain hplip. I have more than once stated that I am not interested in also maintaining the plugins for various reasons.
So I think at the moment you basically can consider hplip-plugin unmaintained. If others want to maintain the plugin they should contact the printing team about it. If there is no reaction within a reasonable time they can just start maintaining it.

**Comment by xdch47** [comment]
the point is i do not understand the proxy maintainer stuff.
tried that with gitea and besides the label `self-mainained` I could not see any difference. the pr rested there for ages, nobody caring about it or willing to merge. - here i guess it would be the same, since no gentoo-dev interested, the pr is going to rest for ages.

**Comment by a17r** [comment]
A package not related to Go will probably be reviewed much faster.

**Pull request closed without merging**
