### PR TITLE
app-laptop/tuxedo-control-center-bin add 1.2.4

### PR DESCRIPTION
**Pull request by LukashonakV**
Signed-off-by: Viktar Lukashonak <myxabeer@gmail.com>

### CODE REVIEW

**Comment by mschiff** [comment]
Thanks, I fixed EAPI first. Can you please update PR to just add new version with EAPI=8?

**Comment by LukashonakV** [comment]
> Thanks, I fixed EAPI first. Can you please update PR to just add new version with EAPI=8?

Done. There's only thing I've also updated Manifest file. Shouldn't I  ?

**Comment by LukashonakV** [comment]
Hi @mschiff , up ))

**Comment by mschiff** [comment]
Please review your commit and recreate your PR. You seem to have commited many changes, not only in this ebuild.

**Comment by LukashonakV** [comment]
> Please review your commit and recreate your PR. You seem to have commited many changes, not only in this ebuild.

Sure, thanks. Will recreate once it's been ready

**Pull request closed without merging**
