### PR TITLE
dev-java/javassist: add 3.30.2

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog regarding my open PRs, this PR please be the next
it solves a blocker: https://bugs.gentoo.org/showdependencytree.cgi?id=916492&hide_resolved=1

**Comment by fordfrog** [comment]
> @fordfrog regarding my open PRs, this PR please be the next it solves a blocker: https://bugs.gentoo.org/showdependencytree.cgi?id=916492&hide_resolved=1

i still need to find some time to have a look at the test issues. do they fail only with our ebuild or they don't work even when using upstream build system?

**Comment by vaukai** [comment]
> > @fordfrog regarding my open PRs, this PR please be the next it solves a blocker: https://bugs.gentoo.org/showdependencytree.cgi?id=916492&hide_resolved=1
> 
> i still need to find some time to have a look at the test issues. do they fail only with our ebuild or they don't work even when using upstream build system?

running `mvn test` would pass them all.

**Comment by fordfrog** [comment]
> > > @fordfrog regarding my open PRs, this PR please be the next it solves a blocker: https://bugs.gentoo.org/showdependencytree.cgi?id=916492&hide_resolved=1
> > 
> > 
> > i still need to find some time to have a look at the test issues. do they fail only with our ebuild or they don't work even when using upstream build system?
> 
> running `mvn test` would pass them all.

hm, so it seems they should be fixable

**Comment by vaukai** [comment]
> hm, so it seems they should be fixable

guess yes.  but no idea how to :-(

**Comment by fordfrog** [comment]
> > hm, so it seems they should be fixable
> 
> guess yes. but no idea how to :-(

i'll try to find some time to have a look at it.

**Comment by vaukai** [comment]
Just rearranged the patches, one for eclass specifics and the other to skip unresolved test failures.

**Comment by fordfrog** [comment]
for this one i still wanna review the tests.

**Comment by vaukai** [comment]
> for this one i still wanna review the tests.

added it as a stabilization blocker: https://bugs.gentoo.org/showdependencytree.cgi?id=918647&hide_resolved=1

**Comment by vaukai** [comment]
> for this one i still wanna review the tests.

@fordfrog This might explain why we're getting ` no such field: j` and ` no such field: i` errors.

From comparing the test logs, where `maven` builds a `local variable table` 
```
Hello end :) 
java.lang.ClassNotFoundException: caught an exception while obtaining a class file for javassist.LoaderTestByRandall
**** local variable table ***
9 7 s Ljava/lang/String; 3
0 20 this Ltest1/LocalVars; 0
0 20 i I 1
2 18 j I 2
**** end ***
```

gentoo fails with `java.lang.IndexOutOfBoundsException: bad descriptor`:
```
.Say Hello...
Hello end :) 
..............java.lang.ClassNotFoundException: caught an exception while obtaining a class file for javassist.LoaderTestByRandall
..E..@annotation.Tag(z=true, b=1, c=a, s=2, i=3, j=4, f=5.0, d=5.0, string="abc", enumtest=annotation.EnumTest.A, integer=java.lang.Integer.class, array={"p", "q", "r"}, annotation=@annotation.Id(id=20))
..testDescriptor(): dataSize() java.lang.IndexOutOfBoundsException: bad descriptor
testDescriptor(): numOfParameters() java.lang.IndexOutOfBoundsException: bad descriptor
........Line 8 at 0
Line 9 at 10
```
But why are we getting that `IndexOutOfBoundsException`?

**Comment by fordfrog** [comment]
so, i did some investigation and my conclusion is that their test classes are compiled with debug enabled whereas our test classes are compiled without debug enabled, hence the variable names are not preserved and the tests fail.

to illustrate it, there is the content of a test class file on which a test fails, when using upstream sources and mvn:
```
$ javap -v target/test-classes/test4/MethodParamTest.class 
Classfile /home/fordfrog/src/gentoo/javassist-rel_3_30_2_ga/target/test-classes/test4/MethodParamTest.class
  Last modified 15. 11. 2024; size 458 bytes
  SHA-256 checksum 89ef928b4a9dcd0b4f15952b6a4a716802d7e6e1e29a9bed22ef2fa0309f72c0
  Compiled from "MethodParamTest.java"
public class test4.MethodParamTest
  minor version: 0
  major version: 55
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #7                          // test4/MethodParamTest
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 1
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Class              #8             // test4/MethodParamTest
   #8 = Utf8               test4/MethodParamTest
   #9 = Utf8               Code
  #10 = Utf8               LineNumberTable
  #11 = Utf8               LocalVariableTable
  #12 = Utf8               this
  #13 = Utf8               Ltest4/MethodParamTest;
  #14 = Utf8               test
  #15 = Utf8               (ILjava/lang/String;)V
  #16 = Utf8               i
  #17 = Utf8               I
  #18 = Utf8               s
  #19 = Utf8               Ljava/lang/String;
  #20 = Utf8               MethodParameters
  #21 = Utf8               SourceFile
  #22 = Utf8               MethodParamTest.java
{
  public test4.MethodParamTest();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 3: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       5     0  this   Ltest4/MethodParamTest;

  public void test(int, java.lang.String);
    descriptor: (ILjava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=0, locals=3, args_size=3
         0: return
      LineNumberTable:
        line 4: 0
      LocalVariableTable:
        Start  Length  Slot  Name   Signature
            0       1     0  this   Ltest4/MethodParamTest;
            0       1     1     i   I
            0       1     2     s   Ljava/lang/String;
    MethodParameters:
      Name                           Flags
      i
      s
}
SourceFile: "MethodParamTest.java"
```
and here is the same file compiled by our ebuild:
```
$ javap -v ./target/test-classes/test4/MethodParamTest.class
Classfile /var/tmp/portage/dev-java/javassist-3.30.2/work/javassist-rel_3_30_2_ga/target/test-classes/test4/MethodParamTest.class
  Last modified 15. 11. 2024; size 281 bytes
  SHA-256 checksum 6edff44a345d4d1b14a885d793a79797f6068ab025a39d7c13b88fd88d17c35d
  Compiled from "MethodParamTest.java"
public class test4.MethodParamTest
  minor version: 0
  major version: 55
  flags: (0x0021) ACC_PUBLIC, ACC_SUPER
  this_class: #7                          // test4/MethodParamTest
  super_class: #2                         // java/lang/Object
  interfaces: 0, fields: 0, methods: 2, attributes: 1
Constant pool:
   #1 = Methodref          #2.#3          // java/lang/Object."<init>":()V
   #2 = Class              #4             // java/lang/Object
   #3 = NameAndType        #5:#6          // "<init>":()V
   #4 = Utf8               java/lang/Object
   #5 = Utf8               <init>
   #6 = Utf8               ()V
   #7 = Class              #8             // test4/MethodParamTest
   #8 = Utf8               test4/MethodParamTest
   #9 = Utf8               Code
  #10 = Utf8               LineNumberTable
  #11 = Utf8               test
  #12 = Utf8               (ILjava/lang/String;)V
  #13 = Utf8               SourceFile
  #14 = Utf8               MethodParamTest.java
{
  public test4.MethodParamTest();
    descriptor: ()V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=1, locals=1, args_size=1
         0: aload_0
         1: invokespecial #1                  // Method java/lang/Object."<init>":()V
         4: return
      LineNumberTable:
        line 3: 0

  public void test(int, java.lang.String);
    descriptor: (ILjava/lang/String;)V
    flags: (0x0001) ACC_PUBLIC
    Code:
      stack=0, locals=3, args_size=3
         0: return
      LineNumberTable:
        line 4: 0
}
SourceFile: "MethodParamTest.java"
```
the constant pool in the first output shows at `#16` and `#18` the variable names. in the second output the constant pool doesn't contain those, and the list is much shorter.

so to make the tests work correctly, at least some test files have to compiled with debug flag on.

**Comment by vaukai** [comment]
> the constant pool in the first output shows at `#16` and `#18` the variable names. in the second output the constant pool doesn't contain those, and the list is much shorter.

feels like i've seen that somewhere but could not guess where that difference comes from.
> 
> so to make the tests work correctly, at least some test files (java files used by the tests and for the tests, probably not the test files themselves) have to be compiled with debug flag on.

`compiled with debug flag on`? how could we do that, is it a `javac` option?

**Comment by fordfrog** [comment]
> > the constant pool in the first output shows at `#16` and `#18` the variable names. in the second output the constant pool doesn't contain those, and the list is much shorter.
> 
> feels like i've seen that somewhere but could not guess where that difference comes from.

i just noticed that in `build.xml` they have debug turned on probably for everything. but we need it just for some files used in the test cases. but if we turn debug on for all test files, it shouldn't cause any issues.

> > so to make the tests work correctly, at least some test files (java files used by the tests and for the tests, probably not the test files themselves) have to be compiled with debug flag on.
> 
> `compiled with debug flag on`? how could we do that, is it a `javac` option?

`javac -g` does the trick.

**Comment by vaukai** [comment]
> `javac -g` does the trick.

That way I could solve 4 test exclusions but 2 others remain. Java 23+ is a different story, shouldn't bother us here.

**Comment by vaukai** [comment]
I could solve the `testURL(javassist.JvstTest2)` failure in `javassist-3.29.2-failing-tests.patch `.

**Comment by fordfrog** [comment]
> I could solve the `testURL(javassist.JvstTest2)` failure in `javassist-3.29.2-failing-tests.patch `.

nice! so only one test still failing?

**Comment by vaukai** [comment]
> > I could solve the `testURL(javassist.JvstTest2)` failure in `javassist-3.29.2-failing-tests.patch `.
> 
> nice! so only one test still failing?

Yeah, so far as for java 11, 17 and 21.

**Comment by fordfrog** [comment]
iirc the last failing test is the one on which i did the tests and which resulted in the fact that we need to compile the classes with debug symbols. so you can simply check the file whether it really contains debug symbols using `javap -v ./target/test-classes/test4/MethodParamTest.class`. for details you can look at https://github.com/gentoo/gentoo/pull/33582#issuecomment-2479628761.

**Comment by vaukai** [comment]
> iirc the last failing test is the one on which i did the tests and which resulted in the fact that we need to compile the classes with debug symbols. so you can simply check the file whether it really contains debug symbols using `javap -v ./target/test-classes/test4/MethodParamTest.class`. for details you can look at [#33582 (comment)](https://github.com/gentoo/gentoo/pull/33582#issuecomment-2479628761).

You like to make me learn, right? I've spent several hours on searching and comparing. I can now see that what the ebuild produces with `JAVAC_ARGS="-g"` is missing `MethodParameters` on `#20`. 
```
1,3c1,3
< Classfile /var/tmp/portage/dev-java/javassist-3.29.2/work/javassist-rel_3_29_2_ga/target/test-classes/test4/MethodParamTest.class
<   Last modified Dec 7, 2024; size 424 bytes
<   SHA-256 checksum 7ee06ca5b081629f1884bc4d5652555d6e6277bb1f2f3093cb1f303427d30f9d
---
> Classfile /home/volkmar/MethodParamTest.class
>   Last modified Dec 7, 2024; size 458 bytes
>   SHA-256 checksum 89ef928b4a9dcd0b4f15952b6a4a716802d7e6e1e29a9bed22ef2fa0309f72c0
32,33c32,34
<   #20 = Utf8               SourceFile
<   #21 = Utf8               MethodParamTest.java
---
>   #20 = Utf8               MethodParameters
>   #21 = Utf8               SourceFile
>   #22 = Utf8               MethodParamTest.java
61a63,66
>     MethodParameters:
>       Name                           Flags
>       i
>       s
```
No idea how to get this solved. Can you help?

**Comment by fordfrog** [comment]
> You like to make me learn, right?

just partially. i didn't have much time for digging deeper and i recalled what was my conclusion when i had a quick look at it several weeks back.

> I've spent several hours on searching and comparing. I can now see that what the ebuild produces with `JAVAC_ARGS="-g"` is missing `MethodParameters` on `#20`.
> 
> ```
> 1,3c1,3
> < Classfile /var/tmp/portage/dev-java/javassist-3.29.2/work/javassist-rel_3_29_2_ga/target/test-classes/test4/MethodParamTest.class
> <   Last modified Dec 7, 2024; size 424 bytes
> <   SHA-256 checksum 7ee06ca5b081629f1884bc4d5652555d6e6277bb1f2f3093cb1f303427d30f9d
> ---
> > Classfile /home/volkmar/MethodParamTest.class
> >   Last modified Dec 7, 2024; size 458 bytes
> >   SHA-256 checksum 89ef928b4a9dcd0b4f15952b6a4a716802d7e6e1e29a9bed22ef2fa0309f72c0
> 32,33c32,34
> <   #20 = Utf8               SourceFile
> <   #21 = Utf8               MethodParamTest.java
> ---
> >   #20 = Utf8               MethodParameters
> >   #21 = Utf8               SourceFile
> >   #22 = Utf8               MethodParamTest.java
> 61a63,66
> >     MethodParameters:
> >       Name                           Flags
> >       i
> >       s
> ```
> 
> No idea how to get this solved. Can you help?

looks like `javac -parameters` does the trick.

**Comment by fordfrog** [comment]
just to make sure it's obvious, what i meant is `javac -g -parameters`

**Comment by vaukai** [comment]
> just to make sure it's obvious, what i meant is `javac -g -parameters`

Indeed, that solves it. Thank you.

**Comment by fordfrog** [comment]
> Indeed, that solves it. Thank you.

cool, thanks!

**Pull request closed without merging**
