### PR TITLE
app-editors/helix: add 24.07

### PR DESCRIPTION
**Pull request by imwints**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by freijon** [comment]
I'd like to fix https://bugs.gentoo.org/934041 before we merge the new version (re-introduce grammar compilation). Also, we should utilise the relatively new [HELIOS_RUNTIME_DIR](https://github.com/helix-editor/helix/blob/44504b720b5ad2ac8bf521b678a3fae2370f182d/helix-loader/src/lib.rs#L64) which would make things easier for us, no need to set any environment variables if I understand correctly.

**Comment by imwints** [comment]
I'm unable to get the grammar to build from the source tarball. I tried fetching it outside of portage as well. After running `cargo build` or `ebuild helix-24.07 clean compile` the build directories don't contain any `.so` files.

**Comment by freijon** [comment]
Would you mind giving me access to your fork? I'll push my latest changes that should fix the issue.

**Comment by imwints** [comment]
Ok I was just incompetent. `fd-find` respects `.gitignore` so I was unable to find the libs in `runtime/grammars/` and I didn't check again after the last push which would have showed the installed libs. It works now as expected.

**Comment by imwints** [comment]
I requested to stabilize `24.03`, so we can drop `23.10` as well since the patches to make the grammar build with `-std=c11` and stricter compilers is a PITA. Currently `23.10` from this PR doesn't build. I'd like to exclude it from the grammar USE flag change if possible before merge.

**Review by juippis — APPROVED** [review]
I'll drop 23.10 since it doesn't indeed build with grammar use flag.

**Pull request closed without merging**
