### PR TITLE
games-emulation/dosbox: remove games eclass and convert to EAPI 6

### PR DESCRIPTION
**Pull request by austin987**
Gentoo-Bug: https://bugs.gentoo.org/566498
Gentoo-Bug: https://bugs.gentoo.org/587382

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by SoapGentoo** [comment]
LGTM

**Comment by DmitriyHetman** [comment]
How fix this issues?

**Comment by monsieurp** [comment]
Read the Wiki page. Please.

**Comment by monsieurp** [comment]
LGTM as well. Let's proceed.

**Pull request closed without merging**
