### PR TITLE
net-im/telegram-desktop: Fix USE=webkit on GCC 11

### PR DESCRIPTION
**Pull request by mid-kid**
@gyakovlev

Included small `REQUIRED_USE` fix as well, is a revbump necessary?

### CODE REVIEW

**Comment by gyakovlev** [comment]
normally revbump is needed.

but, since:

1) big package with long build time
2) non-default enabled useflag
3) not stable yet

let's skip it.

**Review by gyakovlev — APPROVED** [review]

**Comment by gyakovlev** [comment]
merged, thanks again.

**Comment by mid-kid** [comment]
@gyakovlev 
> not stable yet

but it is...

**Comment by gyakovlev** [comment]
damn I missed it's already stable =)
anyway, not big deal in this particular situation.

**Comment by gyakovlev** [comment]
much worse is then you change RDEPEND without revbumps.

**Comment by mid-kid** [comment]
Fair enough, thanks for merging.

**Pull request closed without merging**
