### PR TITLE
dev-embedded/platformio: bump to 6.1.7

### PR DESCRIPTION
**Pull request by mischief**

### CODE REVIEW

**Comment by thesamesam** [comment]
Please always diff the build system for old vs new ebuilds, e.g. ```pkgdiff-mg -b platformio-6.1.6-r2.ebuild platformio-6.1.7.ebuild```.

In this case, we may need to adjust our seds & deps in the ebuild. We don't want to stick with upstream's pins, but we may want to increase the minimum versions in the ebuild's dependencies. We may then have to adjust the seds to ensure we're not picking up pins we don't want.

**Comment by mischief** [comment]
```diff
--- /tmp/mgorny-dev-scripts/portage/dev-embedded/platformio-6.1.6-r2/work/platformio-core-6.1.6/setup.py        2023-01-23 03:01:56.000000000 -0800
+++ /tmp/mgorny-dev-scripts/portage/dev-embedded/platformio-6.1.7/work/platformio-core-6.1.7/setup.py   2023-05-08 07:58:34.000000000 -0700
@@ -36,16 +36,17 @@ minimal_requirements = [
     "pyelftools>=0.27,<1",
     "pyserial==3.5.*",  # keep in sync "device/monitor/terminal.py"
     "requests==2.*",
+    "urllib3<2", # issue 4614: urllib3 v2.0 only supports OpenSSL 1.1.1+
     "requests==%s" % ("2.27.1" if PY36 else "2.*"),
     "semantic_version==2.10.*",
     "tabulate==%s" % ("0.8.10" if PY36 else "0.9.*"),
 ]

 home_requirements = [
-    "aiofiles==%s" % ("0.8.0" if PY36 else "22.1.*"),
+    "aiofiles==%s" % ("0.8.0" if PY36 else "23.1.*"),
     "ajsonrpc==1.*",
-    "starlette==%s" % ("0.19.1" if PY36 else "0.23.*"),
-    "uvicorn==%s" % ("0.16.0" if PY36 else "0.20.*"),
+    "starlette==%s" % ("0.19.1" if PY36 else "0.26.*"),
+    "uvicorn==%s" % ("0.16.0" if PY36 else "0.22.*"),
     "wsproto==%s" % ("1.0.0" if PY36 else "1.2.*"),
 ]

@@ -67,6 +68,8 @@ setup(
             "assets/templates/ide-projects/*/*.tpl",
             "assets/templates/ide-projects/*/.*.tpl",  # include hidden files
             "assets/templates/ide-projects/*/.*/*.tpl",  # include hidden folders
+            "assets/templates/ide-projects/*/*/*.tpl",  # NetBeans
+            "assets/templates/ide-projects/*/*/*/*.tpl", # NetBeans
         ]
     },
     entry_points={
```

**Comment by thesamesam** [comment]
Right, so the ebuild needs adjusting.

**Comment by mischief** [comment]
> Right, so the ebuild needs adjusting is what I'm saying.

my apologies, it is just for my own reference because i do not have time to look now.

**Comment by thesamesam** [comment]
Ah, no worries, I was just worried I wasn't clear. Just ping me when updated. Cheers!

**Pull request closed without merging**
