### PR TITLE
dev-python/flask-admin: Bump to 1.5.5, dev-python/peewee: Bump to 3.13.1

### PR DESCRIPTION
**Pull request by cjmayo**
flask-admin-1.5.5 needs peewee for testing. Bumping the peewee ebuild fixes an open bug. I've dropped Python 2 in the peewee ebuild - I haven't checked for any dependencies.

emerging flask-admin with FEATURES="test" does pass. It handily avoids the tests requiring a server. I have manually tested with PostgreSQL, but not MongoDB. I will try and get Python 3.8 testing upstream. Updating chai and arrow with Python 3.8 was needed to test locally, as were the masked geoalchemy2 (I have got that passing tests for Python 3.8 in an upstream PR (not PyPy yet)) and wtf-peewee.

Do check, there is quite a lot going on here. There may well be some things I forgot to mention.

```diff
--- flask-admin-1.5.1.ebuild
+++ flask-admin-1.5.5.ebuild
@@ -1,12 +1,10 @@
 # Copyright 1999-2020 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
-PYTHON_COMPAT=( python3_6 )
+EAPI=7
+PYTHON_COMPAT=( python3_{6,7,8} )
 
 inherit distutils-r1
-
-#RESTRICT="test" # we're still missing some of the dependencies
 
 MY_PN="Flask-Admin"
 MY_P="${MY_PN}-${PV}"
@@ -17,43 +15,20 @@
 
 LICENSE="BSD"
 SLOT="0"
-KEYWORDS="amd64 x86"
-IUSE="examples test"
-RESTRICT="!test? ( test )"
+KEYWORDS="~amd64 ~x86"
+IUSE="test"
 
 RDEPEND="
-	>=dev-python/flask-0.7[${PYTHON_USEDEP}]
+	dev-python/flask[${PYTHON_USEDEP}]
 	dev-python/wtforms[${PYTHON_USEDEP}]"
-DEPEND="${RDEPEND}
-	dev-python/setuptools[${PYTHON_USEDEP}]
+BDEPEND="${RDEPEND}
 	test? (
-		dev-python/nose[${PYTHON_USEDEP}]
-		dev-python/flask-wtf[${PYTHON_USEDEP}]
+		dev-python/flask-sqlalchemy[${PYTHON_USEDEP}]
 		dev-python/peewee[${PYTHON_USEDEP}]
-		dev-python/wtf-peewee[${PYTHON_USEDEP}]
-		dev-python/flask-pymongo[${PYTHON_USEDEP}]
-		dev-python/flask-mongoengine[${PYTHON_USEDEP}]
-		dev-python/flask-sqlalchemy[${PYTHON_USEDEP}]
-		dev-python/flask-babelex[${PYTHON_USEDEP}]
-		sci-libs/Shapely[${PYTHON_USEDEP}]
-		dev-python/geoalchemy2[${PYTHON_USEDEP}]
-		>=dev-python/pillow-2.9[${PYTHON_USEDEP},jpeg(+)]
+		dev-python/pillow[${PYTHON_USEDEP},jpeg,tiff]
+		dev-python/pymongo[${PYTHON_USEDEP}]
 	)"
 
 S="${WORKDIR}/${MY_P}"
 
-python_prepare_all() {
-	sed \
-		-e 's:find_packages():find_packages(exclude=["*.examples", "*.examples.*", "examples.*", "examples"]):g' \
-		-i setup.py || die
-	distutils-r1_python_prepare_all
-}
-
-python_test() {
-	nosetests || die "Testing failed with ${EPYTHON}"
-}
-
-python_install_all() {
-	use examples && dodoc -r examples
-	distutils-r1_python_install_all
-}
+distutils_enable_tests nose
```

```diff
--- peewee-3.1.0.ebuild
+++ peewee-3.13.1.ebuild
@@ -1,48 +1,29 @@
 # Copyright 1999-2020 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
-PYTHON_COMPAT=( python{2_7,3_6} )
-PYTHON_REQ_USE="sqlite(+)"
+EAPI=7
+PYTHON_COMPAT=( python3_{6,7,8} )
+PYTHON_REQ_USE="sqlite"
 
 inherit distutils-r1
 
-DESCRIPTION="Small python ORM"
+DESCRIPTION="Small Python ORM"
 HOMEPAGE="https://github.com/coleifer/peewee/"
-SRC_URI="https://github.com/coleifer/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"
+SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"
 
 LICENSE="BSD"
 SLOT="0"
-KEYWORDS="amd64 x86"
-IUSE="doc examples"
+KEYWORDS="~amd64 ~x86"
+IUSE="examples"
 
-DEPEND="dev-python/cython[${PYTHON_USEDEP}]
-	dev-python/setuptools[${PYTHON_USEDEP}]
-	doc? ( dev-python/sphinx[${PYTHON_USEDEP}] )"
-# Req'd to ensure a unique tmp.db for each python impl running the testsuite.
-DISTUTILS_IN_SOURCE_BUILD=1
+# tests not included in PyPI tarball
+RESTRICT="test"
 
-python_prepare_all() {
-	sed -i -e "s#test_suite='tests',##g;" ./setup.py || die
-	distutils-r1_python_prepare_all
-}
+DEPEND="dev-python/cython[${PYTHON_USEDEP}]"
 
-python_compile() {
-	python_is_python3 || local -x CFLAGS="${CFLAGS} -fno-strict-aliasing"
-	distutils-r1_python_compile
-}
-
-python_compile_all() {
-	use doc && emake -C docs html
-}
-
-python_test() {
-	# Testsuite run using runtests.py does not require deps listed in previous ebuild
-	"${PYTHON}" ./runtests.py || die "tests failed under ${EPYTHON}"
-}
+distutils_enable_sphinx docs
 
 python_install_all() {
-	use doc && local HTML_DOCS=( docs/_build/html/. )
 	use examples && DOCS=( examples/ )
 	distutils-r1_python_install_all
 }
```

### CODE REVIEW

**Comment by cjmayo** [comment]
Dropped the dev-python/pymongo test dependency. Only PyMongo 3 is available in Gentoo but the test only supports PyMongo 2.

```diff
--- a/flask-admin-1.5.5.ebuild
+++ b/flask-admin-1.5.5.ebuild
@@ -26,9 +26,14 @@
 		dev-python/flask-sqlalchemy[${PYTHON_USEDEP}]
 		dev-python/peewee[${PYTHON_USEDEP}]
 		dev-python/pillow[${PYTHON_USEDEP},jpeg,tiff]
-		dev-python/pymongo[${PYTHON_USEDEP}]
 	)"
 
 S="${WORKDIR}/${MY_P}"
 
 distutils_enable_tests nose
+
+src_prepare() {
+	default
+	# Tests only work with PyMongo 2
+	rm -rf flask_admin/tests/pymongo || die
+}
```

The silent skipping of tests by nose mentioned in the original comment appears to only happen from the ebuild and not when running nosetests in the source directory.

**Comment by cjmayo** [comment]
Need to drop the old 1.5.1 ebuild because of masked packages.

**Comment by cjmayo** [comment]
Updated because Postgresql tests are now failing from ebuild...

```diff
--- a/flask-admin-1.5.5.ebuild
+++ b/flask-admin-1.5.5.ebuild
@@ -23,7 +23,6 @@
 	dev-python/wtforms[${PYTHON_USEDEP}]"
 BDEPEND="${RDEPEND}
 	test? (
-		dev-python/flask-sqlalchemy[${PYTHON_USEDEP}]
 		dev-python/peewee[${PYTHON_USEDEP}]
 		dev-python/pillow[${PYTHON_USEDEP},jpeg,tiff]
 	)"
@@ -36,4 +35,7 @@
 	default
 	# Tests only work with PyMongo 2
 	rm -rf flask_admin/tests/pymongo || die
+	# Tests require PostgreSQL server
+	rm -rf flask_admin/tests/geoa || die
+	rm -rf flask_admin/tests/sqla || die
 }
```

**Comment by juippis** [comment]
flask-admin got removed with 7622f900c65
so did flask-peewee. Peewee itself seems to be present, but outdated. I suggest to open a new PR with clean history and fresh ::gentoo master tree state. Python team has been pretty slow to respond to PRs lately, but I hope it gets better after python2 and 3.6 are cleaned.

**Pull request closed without merging**
