### PR TITLE
nagios: bump to 4.4.5

### PR DESCRIPTION
**Pull request by hydrapolic**
@orlitzky GLEP 81?

### CODE REVIEW

**Comment by orlitzky** [comment]
> GLEP 81?

We should eventually. I've avoided it so far because I inherited the nagios package with the user the way it is and I think it's all wrong. It's probably fine with `/dev/null` as its home directory and no shell. Moreover, `/var/nagios` should be moved to `/var/lib/nagios`. An `ewarn` to run `mv` probably suffices for that, but who knows.

Finally, the other packages that share the "nagios" user need to be tested with the new settings.

If you're up for it, I support you =)

Otherwise, I can merge as-is.

**Comment by hydrapolic** [comment]
> Otherwise, I can merge as-is.

I think it's ok for now, thanks.

**Comment by orlitzky** [comment]
I pulled it, and I began the "testing" phase of the user changes I mentioned. In nagios-core, nagios-plugins, and nrpe, I switched the user's home directory and shell to `-1` for the defaults. This should be less disruptive than doing it with an acct-user package would be: if it causes problems, those problems should only appear on new installs (and hopefully people file bugs about them).

I also did a revision to move the localstatedir to `/var/lib/nagios`. I don't *think* there's anything crucial in there, but you probably know better than I do. (On my installation, it's only logs and service check results that can be regenerated.) Upgraders will get an ewarn about that. Please keep an eye out and let me know if I broke anything. If nobody reports problems, a direct migration into an acct-user package is probably safe.

**Comment by hydrapolic** [comment]
@orlitzky, upgraded Nagios and Nrpe and so far so good, thanks!

**Pull request closed without merging**
