### PR TITLE
net-libs/mbedtls: add v2.16.5

### PR DESCRIPTION
**Pull request by jsmolic**
Include 2.16.5 version as 2.16 mbedTLS branch is LTS and will be supported until the end of 2021.

Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Jakov Smolic <jakov.smolic@sartura.hr>
Signed-off-by: Luka Perkov <luka.perkov@sartura.hr>

### CODE REVIEW

**Comment by blueness** [comment]
Thanks for this.  Let me test it first and then I'll commit.

**Comment by blueness** [comment]
Okay you're just restoring an older ebuild.  Do you want to stabilize it?  If so, open a stabilization requiest on bugzilla.gentoo.org.

**Comment by blueness** [comment]
Actually 2.16.6 is also out.  I'll add that.

**Comment by jsmolic** [comment]
@blueness Thank you :)
Yes, apparently they released 2.16.6 just today.

We want to stabilize this package, I will open a stabilization request for that.

**Pull request closed without merging**
