### PR TITLE
dev-lua/luafilesystem: version bump to 1.8.0

### PR DESCRIPTION
**Pull request by epsilon-0**
Package-Manager: Portage-3.0.8, Repoman-3.0.1
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

### CODE REVIEW

**Comment by gyakovlev** [comment]
```
Aborting due to QA concerns: 6 files installed in /var/tmp/portage/dev-lua/luafilesystem-1.8.0/image/var/tmp/portage/dev-lua/luafilesystem-1.8.0/image
```

looks like double prefix gets applied somewhere, upstream changes in makefile?
also you should test installation packages you bump ;-)

**Comment by epsilon-0** [comment]
> ```
> Aborting due to QA concerns: 6 files installed in /var/tmp/portage/dev-lua/luafilesystem-1.8.0/image/var/tmp/portage/dev-lua/luafilesystem-1.8.0/image
> ```
> 
> looks like double ${D} gets applied somewhere, upstream changes in makefile?
> also you should test installation of packages you bump ;-)

Snap, i just compiled and ran tests. Should've installed too :crying_cat_face: 
Will do in bit.

**Comment by gyakovlev** [comment]
https://github.com/keplerproject/luafilesystem/commit/12d1692f14075b2c5991df5b0dc74755aff33181

so setting `${ED}` in config no longer needed, adjust that and it should be fine.

**Comment by gyakovlev** [comment]
probably just EPREFIX needed there.

**Comment by epsilon-0** [comment]
Oh, i did the other way around, removed DESTDIR=$D in install.

**Comment by gyakovlev** [comment]
agreed, better remove config hack as it's not standard.

**Comment by epsilon-0** [comment]
done

**Pull request closed without merging**
