### PR TITLE
Plasma profile: fix net-analyzer/wireshark: at-most-one-of ( qt4 qt5 )

### PR DESCRIPTION
**Pull request by DarthGandalf**
Related: https://bugs.gentoo.org/show_bug.cgi?id=559212

### CODE REVIEW

**Comment by johu** [comment]
Could you please update the commit message to follow our guidelines?

**Comment by DarthGandalf** [comment]
I tried :-(
I don't know how to do that. I would start commit message with "net-analyzer/wireshark:" as the guideline says, but the changed file is in `profiles/.../plasma`, not `net-analyzer/wireshark/`. That's why I've put "plasma" at beginning. Is "net-analyzer/wireshark:" more correct?

**Comment by monsieurp** [comment]
"profile: commit message" is fine.

**Comment by johu** [comment]
@DarthGandalf  git commit --amend or git rebase -i will help to modify the commit

**Comment by DarthGandalf** [comment]
@johu you've got me wrong: I know how to use git. I don't know how to apply Gentoo guidelines for commit messages in this case.
Based on what @monsieurp said, it looks like my commit message was fine.
To ask again: Is `net-analyzer/wireshark:` more correct?

**Comment by rindeal** [comment]
I guess the problem can be solved with `s|Plasma profile|profiles|`

**Comment by DarthGandalf** [comment]
Done.

**Comment by kensington** [comment]
Thanks, picked as 755b2562ee02f018d83abb99f12abe0238e9690f.

**Comment by DarthGandalf** [comment]
Thanks

**Pull request closed without merging**
