### PR TITLE
net-nntp/pan: fix crash on startup

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo bug #570108

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/gnome

**Comment by Tranquility** [comment]
Please remove the colon and parentheses from the patch filename and squash your commits.

**Comment by PPed72** [comment]
Will do!
-- 
Paolo Pedroni
<paolo.Pedroni@iol.it>
Il 09/mar/2016 19:30, Ole Reifschneider <notifications@github.com> ha scritto:Please remove the colon and parentheses from the patch filename and squash your commits.

**Comment by PPed72** [comment]
I messed up my git tree (again). I'll close this and open a new pull request.

**Pull request closed without merging**
