### PR TITLE
sys-freebsd/*: Please version bump 10.2.

### PR DESCRIPTION
**Pull request by nigoro**
FreeBSD 10.2 ebuilds and patches.

FreeBSD 10.2-RELEASE Release Notes
https://www.freebsd.org/releases/10.2R/relnotes.html

### CODE REVIEW

**Comment by mgorny** [comment]
Lookie finey, please squash the commits into one and give it a nice commit message. Get yourself a [GLEP 63](https://wiki.gentoo.org/wiki/GLEP:63)-compliant key (e.g. [using gkeys](https://wiki.gentoo.org/wiki/Project:Gentoo-keys/Generating_GLEP_63_based_OpenPGP_keys#GLEP_63)) and sign it like a real developer. Then squash the commits in #13, set a nice description, sign and add here. When I have the two nice commits (or even one, whichever you prefer), I'm going to try to merge it preserving your commits.

**Comment by hasufell** [comment]
And don't forget to rebase against gentoo/master after you have squashed them.

**Comment by mgorny** [comment]
@hasufell, could you handle this? I still have no electricity.

**Comment by hasufell** [comment]
> I still have no electricity.

err, wat?

**Comment by hasufell** [comment]
@nigoro can you please rebase against latest master?

**Comment by nigoro** [comment]
@hasufell, Thank you for your comment. I think lost the sign when rebasing.
I did to sign and rebasing in a new following steps.
Please tell me if something is wrong.

Thanks in advance.
```
git checkout master
git remote add upstream git@github.com:gentoo/gentoo.git
git pull upstream master
git checkout freebsd10.2
export GPG_TTY=`tty`
git rebase master freebsd10.2 -S
git log --show-signature # check sign
git push -f origin freebsd10.2
```

**Comment by hasufell** [comment]
Do you have done `git config --local commit.gpgsign 1` in your local repository?

**Comment by nigoro** [comment]
Yeah, I've set it.
I think that it is necessary to upgrade the git.

Ubuntu 14.04.3 (I used in the first rebase)
$ git --version
git version 1.9.1

Gentoo/FreeBSD (I used to this time rebase.)
$ git --version
git version 2.5.0

**Comment by mgorny** [comment]
`git rebase -S` re-signs the commits.

**Comment by nigoro** [comment]
rebased & re-signed.

**Comment by mgorny** [comment]
Lol, it attributed it to me. I guess because of the reviewed-by ;D.

**Comment by hasufell** [comment]
No, you are always the merger, probably because of how this mirror is set up.

**Comment by mgorny** [comment]
This mirror just does `git push --mirror` on infra hw. It isn't affiliated with me in any way.

**Pull request merged**
