### PR TITLE
app-editors/vscod*: version bump to 1.62.2

### PR DESCRIPTION
**Pull request by AdelKS**
Hello!

Small version bump as usual.

One question: should we stabilize old versions ?

Adel

### CODE REVIEW

**Comment by AdelKS** [comment]
Okay 1.62.2 just got released, please don't merge till I bump that.

**Comment by AdelKS** [comment]
I bumped to 1.62.2, ready to go!

**Review by juippis — APPROVED** [review]
Remember that stabilization will bring extra maintenance burden to anyone. If you yourself are running stable, or people on stable are requesting it and you feel like you can do it, go for it. 

But in general I dislike these programs that have multiple releases weekly getting stabilized. You'll just have to pick a release and treat it like LTS, even though upstream didn't mean it.

**Comment by AdelKS** [comment]
Yea then just forget about it. I feel the same, this editor just cannot be treated as such: people will need to accept_keywords for it and basta. x)

**Pull request closed without merging**
