### PR TITLE
app-i18n/fcitx* bump

### PR DESCRIPTION
**Pull request by liangyongxiang**
- x11-libs/xcb-imdkit: add 1.0.7
- x11-libs/xcb-imdkit: drop 1.0.6
- app-i18n/fcitx: add 5.1.8
- app-i18n/fcitx: drop 5.1.7
- app-i18n/fcitx-gtk: add 5.1.2

### CODE REVIEW

**Comment by stshine** [comment]
Now Qt6 and Plasma 6 are both in the main tree, how about support them in fcitx-configtool?

**Comment by liangyongxiang** [comment]
> Now Qt6 and Plasma 6 are both in the main tree, how about support them in fcitx-configtool?

You're right. I should update the qt6 section of fcitx-configtool

**Comment by liangyongxiang** [comment]
After adding qt6 use and dependencies, fcitx-configtool runs ok. But the pkgcheck scan prompts a NonsolvableDepsInDev issue that I don't know how to fix:

```
app-i18n/fcitx-configtool
  UnstableOnly: for arch: [ arm64 ], all versions are unstable: [ 0.4.10, 5.1.4 ]
  EmptyGlobalAssignment: version 0.4.10: line 17: empty global assignment: SRC_URI=""
  EmptyGlobalAssignment: version 0.4.10: line 25: empty global assignment: IUSE=""
  PotentialStable: version 0.4.10: slot(4), stabled arches: [ amd64, ppc, ppc64, x86 ], potential: [ ~arm64 ]
  EmptyGlobalAssignment: version 4.9999: line 17: empty global assignment: SRC_URI=""
  EmptyGlobalAssignment: version 4.9999: line 24: empty global assignment: KEYWORDS=""
  EmptyGlobalAssignment: version 4.9999: line 25: empty global assignment: IUSE=""
  DroppedKeywords: version 5.1.4-r1: arm64, loong, ppc, ppc64, riscv, x86
  NonsolvableDepsInDev: version 5.1.4-r1: nonsolvable depset(depend) keyword(~amd64) dev profile (default/linux/amd64/17.0/musl) (3 total): solutions: [ kde-frameworks/kcmutils:6, kde-frameworks/kcoreaddons:6, kde-frameworks/kdeclarative:6, kde-frameworks/ki18n:6, kde-frameworks/kiconthemes:6, kde-frameworks/kirigami:6, kde-frameworks/kitemviews:6, kde-frameworks/kpackage:6, kde-frameworks/ksvg:6, kde-frameworks/kwidgetsaddons:6, kde-plasma/libplasma:6 ]
  NonsolvableDepsInDev: version 5.1.4-r1: nonsolvable depset(rdepend) keyword(~amd64) dev profile (default/linux/amd64/17.0/musl) (3 total): solutions: [ kde-frameworks/kcmutils:6, kde-frameworks/kcoreaddons:6, kde-frameworks/kdeclarative:6, kde-frameworks/ki18n:6, kde-frameworks/kiconthemes:6, kde-frameworks/kirigami:6, kde-frameworks/kitemviews:6, kde-frameworks/kpackage:6, kde-frameworks/ksvg:6, kde-frameworks/kwidgetsaddons:6, kde-plasma/libplasma:6 ]
  NonsolvableDepsInStable: version 5.1.4-r1: nonsolvable depset(depend) keyword(~amd64) stable profile (default/linux/amd64/17.1) (14 total): solutions: [ kde-frameworks/kcmutils:6, kde-frameworks/kcoreaddons:6, kde-frameworks/kdeclarative:6, kde-frameworks/ki18n:6, kde-frameworks/kiconthemes:6, kde-frameworks/kirigami:6, kde-frameworks/kitemviews:6, kde-frameworks/kpackage:6, kde-frameworks/ksvg:6, kde-frameworks/kwidgetsaddons:6, kde-plasma/libplasma:6 ]
  NonsolvableDepsInStable: version 5.1.4-r1: nonsolvable depset(rdepend) keyword(~amd64) stable profile (default/linux/amd64/17.1) (14 total): solutions: [ kde-frameworks/kcmutils:6, kde-frameworks/kcoreaddons:6, kde-frameworks/kdeclarative:6, kde-frameworks/ki18n:6, kde-frameworks/kiconthemes:6, kde-frameworks/kirigami:6, kde-frameworks/kitemviews:6, kde-frameworks/kpackage:6, kde-frameworks/ksvg:6, kde-frameworks/kwidgetsaddons:6, kde-plasma/libplasma:6 ]

```

**Comment by liangyongxiang** [comment]
It seems better to update fcitx-configtool after plasma6 is not masked.

**Comment by stshine** [comment]
Oh that's fine.

**Comment by dlan17** [comment]
hi @liangyongxiang , it's fine to drop old ebuilds while pushing the new versions, but I'd suggest at least keeping one old version, in case there are some bugs and users are able to fall back to downgrade.. less aggressive

**Pull request closed without merging**
