### PR TITLE
xapp-text/xmldiff-2.3: version bump

### PR DESCRIPTION
**Pull request by acerisara**
Happy to maintain the package.

Not sure what I'm supposed to do regarding keywords.

Package _1.1.1_ specifies

`KEYWORDS="~alpha amd64 ia64 ppc sparc x86 ~x86-linux"`

while the new ebuild only has `KEYWORDS="~amd64"` which is the arch I did my tests on.

Let me know how to proceed.

### CODE REVIEW

**Comment by j-licht** [comment]
You should add you and the proxy maintainer project as maintainer:
https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Proxied_maintainer_in_metadata.xml
Maybe you could add python tests.

**Comment by thesamesam** [comment]
You should drop the old keywords to just ~arches, rather than removing them, unless there has been a big change in functionality which makes it likely it may not work there anymore.

**Comment by acerisara** [comment]
@j-licht @thesamesam I'll do the changes, no problem. @j-licht Re python tests, do you mean https://wiki.gentoo.org/wiki/Project:Python/Tests?

**Comment by j-licht** [comment]
I think for testing you can simple add ``distutils_enable_tests unittest``
https://devmanual.gentoo.org/eclass-reference/distutils-r1.eclass/index.html#lbAE

**Comment by Alessandro-Barbieri** [comment]
`In order to force reassignment and/or bug reference scan, please append [please reassign] to the pull request title.`

**Comment by acerisara** [comment]
Getting there, account created.

**Pull request closed without merging**
