### PR TITLE
dev-lang/lazarus: version bump 2.0.6

### PR DESCRIPTION
**Pull request by TheChymera**
@Amynka this is to bump our lazarus and get rid of the now broken python USE flag which still exists in the latest version.

Package-Manager: Portage-2.3.96, Repoman-2.3.22
Signed-off-by: Horea Christian <chr@chymera.eu>

### CODE REVIEW

**Comment by TheChymera** [comment]
@juippis @mgorny could you help me out with this? Regarding the current errors:

1. I don't want to change anything regarding how prefix is handled since I have no machine to test it on.
2. I don't understand the issue with `MissingSlotDep`.

**Comment by juippis** [comment]
Think you just synced your local copy in a bad timing. Fetch latest ::gentoo master and rebase your branch to get rid of these external CI issues.

We can't help before 30 days have passed, please ping us again after.

**Comment by juippis** [comment]
30 days from opening a bug, because that's the only site that counts towards maintainer timeout.

**Comment by TheChymera** [comment]
@juippis ok, filed a bug here: https://bugs.gentoo.org/719142

**Comment by jonasstein** [comment]
add
Closes: https://bugs.gentoo.org/719142

**Pull request closed without merging**
