### PR TITLE
media-gfx/slic3r: bugfix

### PR DESCRIPTION
**Pull request by tomboy-64**
Slic3r depends on recent perl packages. Instabilities have been reported with stable (e.g. for recent perl outdated) packages.
Additionally a small dep-fix for Growl-GNTP.

@kentfredric 
@gentoo/proxy-maint

### CODE REVIEW

**Comment by kentfredric** [comment]
Curious, does it *factually* need newer versions of *every* virtual with a version?

That's not really recommended, the idea is to only raise minimums sufficient to "satisfy requirements", as opposed to forcing users to "upgrade everything" "just because".

Hard-Maximising things only leads to increased dependency fragility.

**Comment by tomboy-64** [comment]
No, it does not. That's why I ping'd you.
I was alerted by a user, that for correct functionality of the 1.2.9 version the currently latest versions are advised. And since it hardly makes sense to tell users to go testing on their whole machine, this would be the logical resort.

**Comment by kentfredric** [comment]
But if users want to mix ~arch and arch, we really shouldn't be arbitrarily trying to stop them.

"Not a good idea" ne "Forbidden".

Besides, the easiest way to "force ~arch" would just require ">=perl 5.22.0" in the slic3r build. But when you write it so tersely it becomes obvious why its evil.

**Comment by tomboy-64** [comment]
so your suggestion would be to just depend on that?
fair enough.

**Comment by kentfredric** [comment]
And there were more dependencies pruned in the upgrade than just IO::Socket::* , that's why I just didn't want to bother with this, because there's not much point in doing a -r1 bump to fix one thing when there are ~3 similar things that need fixing in the same way.  Its better to just do them all at once, or not at all.

**Comment by kentfredric** [comment]
> so your suggestion would be to just depend on that?

I don't like it, but I don't like any of this. But that would at least be simpler, and easier for an end user to reverse.

Personally I'd rather we found out exactly what was breaking and why, and only increment virtuals when *necessary*, not for some arbitrary non-problem.

**Comment by tomboy-64** [comment]
@kentfredric better?

**Comment by kentfredric** [comment]
Much better. All that's left to do now is clean up those deps

1. These 2 can be nuked from DEPEND
```
 	virtual/perl-File-Spec
 	virtual/perl-CPAN-Meta
```

2. `Module-Build-Tiny` should be dep-upgraded to version 0.35.0

**Comment by tomboy-64** [comment]
@idella good to go

**Pull request closed without merging**
