### PR TITLE
www-client/firefox-bin: -pulseaudio ewarn helpful

### PR DESCRIPTION
**Pull request by vitaly-zdanevich**
Signed-off-by: Vitaly Zdanevich <zdanevich.vitaly@ya.ru>

### CODE REVIEW

**Comment by juippis** [comment]
patchelfing could be done within the ebuild based on USE conditions, like `+alsa -pulseaudio`, or `apulse` or simply `sound`. That's how I'd do it, but I'm not the maintainer.

**Comment by vitaly-zdanevich** [comment]
But maybe some users do not need audio :)

**Comment by juippis** [comment]
Yes, that's why you don't do anything special if none of the flags are set, and don't pull any deps either.

**Comment by stefson** [comment]
ah, seems that is the reason I never got the sound to work with the bin package. patchelf should be forged into the ebuild, indeed. Is there a bug open?

**Comment by vitaly-zdanevich** [comment]
Not all users need sound, so I do not think that ebuild should emerge patchelf.

Open bug is necessary to merge?

**Comment by juippis** [comment]
> Not all users need sound, so I do not think that ebuild should emerge patchelf.
You can call it conditionally when a specific USE flag is enabled, such as *apulse* or *sound -pulseaudio*. 

> 
> Open bug is necessary to merge?
It depends on the maintainer, some devs don't look at Github at all, so bugzilla remains the only way of contacting them.

**Comment by Whissi** [comment]
Looks like this should be hidden behind USE=alsa.

**Pull request closed without merging**
