### PR TITLE
dev-cpp/folly: initial import (2022.02.21.00)

### PR DESCRIPTION
**Pull request by thesamesam**
Needed for dev-util/watchman.

Closes: https://bugs.gentoo.org/419599
Signed-off-by: Sam James <sam@gentoo.org>

### CODE REVIEW

**Comment by thesamesam** [comment]
@gyakovlev sadly watchman can't yet be built, it won't pick up the cargo.eclass crates bit, but it looks like it should be possible: https://github.com/facebook/watchman/blob/789678cf9855fb07b402afb75b01e4f8786deba2/build/fbcode_builder/CMake/RustStaticLibrary.cmake#L15.

**Comment by gyakovlev** [comment]
as for rust
 looks like cmake file makes own cargo.conf, we want to prevent that.
basically it should not do anything `GENERATE_CARGO_VENDOR_CONFIG` cmake knob does, we already do that.
so you probably want to set `USE_CARGO_VENDOR` to `ON` and set `RUST_VENDORED_CRATES_DIR` to the value of `ECARGO_VENDOR`

also you HAVE to run `cargo_gen_config`  before cmake.

**Comment by gyakovlev** [comment]
oh looks like you already do this, but still need `cargo_gen_config` - that one will prepare directory structure.
but maybe it wants the real vendor dir, in that case you can run `cargo vendor --offline ${ECARGO_VENDOR} || die` before cmake but after gen_config

**Comment by thesamesam** [comment]
No luck. `cargo_src_unpack` already calls it too I think.

```
src_prepare() {
        cmake_src_prepare

        local rust_dir
        for rust_dir in watchman/cli watchman/rust/serde_bser watchman/rust/watchman_client ; do
                cd ${rust_dir} || die
                cargo vendor --offline ${ECARGO_VENDOR} || die
                cd "${S}" || die
        done
}

src_configure() {
        # https://github.com/facebook/watchman/blob/789678cf9855fb07b402afb75b01e4f8786deba2/build/fbcode_builder/CMake/RustStaticLibrary.cmake#L17
        export RUST_VENDORED_CRATES_DIR="${ECARGO_HOME}"
        export RUST_CARGO_HOME="${ECARGO_HOME}"
        export CARGO_HOME="${ECARGO_HOME}"

        local mycmakeargs=(
                -DUSE_CARGO_VENDOR=ON
                -DGENERATE_CARGO_VENDOR_CONFIG=OFF
        )

        cmake_src_configure
}
```

```
>>> Source unpacked in /var/tmp/portage/dev-util/watchman-2022.02.28.00/work
!!! Failed to set new SELinux execution context. Is your current SELinux context allowed to run Portage?
>>> Preparing source in /var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00_build"
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  no matching package named `ahash` found
  location searched: registry `crates-io`
  required by package `watchmanctl v0.1.0 (/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00/watchman/cli)`
  As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
 * ERROR: dev-util/watchman-2022.02.28.00::gentoo failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 127:  Called src_prepare
 *   environment, line 4368:  Called die
 * The specific snippet of code:
 *           cargo vendor --offline ${ECARGO_VENDOR} || die;
```

**Comment by thesamesam** [comment]
No luck. `cargo_src_unpack` already calls it too I think.

```
src_prepare() {
        cmake_src_prepare

        local rust_dir
        for rust_dir in watchman/cli watchman/rust/serde_bser watchman/rust/watchman_client ; do
                cd ${rust_dir} || die
                cargo vendor --offline ${ECARGO_VENDOR} || die
                cd "${S}" || die
        done
}

src_configure() {
        # https://github.com/facebook/watchman/blob/789678cf9855fb07b402afb75b01e4f8786deba2/build/fbcode_builder/CMake/RustStaticLibrary.cmake#L17
        export RUST_VENDORED_CRATES_DIR="${ECARGO_HOME}"
        export RUST_CARGO_HOME="${ECARGO_HOME}"
        export CARGO_HOME="${ECARGO_HOME}"

        local mycmakeargs=(
                -DUSE_CARGO_VENDOR=ON
                -DGENERATE_CARGO_VENDOR_CONFIG=OFF
        )

        cmake_src_configure
}
```

```
>>> Source unpacked in /var/tmp/portage/dev-util/watchman-2022.02.28.00/work
!!! Failed to set new SELinux execution context. Is your current SELinux context allowed to run Portage?
>>> Preparing source in /var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00_build"
error: failed to sync

Caused by:
  failed to load pkg lockfile

Caused by:
  no matching package named `ahash` found
  location searched: registry `crates-io`
  required by package `watchmanctl v0.1.0 (/var/tmp/portage/dev-util/watchman-2022.02.28.00/work/watchman-2022.02.28.00/watchman/cli)`
  As a reminder, you're using offline mode (--offline) which can sometimes cause surprising resolution failures, if this error is too confusing you may wish to retry without the offline flag.
 * ERROR: dev-util/watchman-2022.02.28.00::gentoo failed (prepare phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line 127:  Called src_prepare
 *   environment, line 4368:  Called die
 * The specific snippet of code:
 *           cargo vendor --offline ${ECARGO_VENDOR} || die;
```

**Comment by thesamesam** [comment]
Ooh, I might have got it.

**Pull request closed without merging**
