### PR TITLE
media-video/rav1e: add USE=static-libs

### PR DESCRIPTION
**Pull request by Hello71**
tested libheif[rav1e], libavif[rav1e] still working

### CODE REVIEW

**Comment by mgorny** [comment]
What's the purpose of supporting static libs in the first place?

**Comment by Hello71** [comment]
i don't know that much about rust, but i think possibly the ABI is not stable? anyways, i don't want to break someone's spacebar heating if the USE flag is easy to add. i don't feel strongly about the option, just don't want them installed by default.

**Comment by thesamesam** [comment]
Would you mind changing to just [never](https://projects.gentoo.org/qa/policy-guide/installed-files.html#pg0302) install static libs, then I'll merge? Thanks!

**Comment by thesamesam** [comment]
Thanks!

**Pull request closed without merging**
