### PR TITLE
net-libs/libmicrohttpd: upstream version 1.0.1

### PR DESCRIPTION
**Pull request by Karlson2k**
Also added USE `debug` flag

### CODE REVIEW

**Comment by Karlson2k** [comment]
@thesamesam, please check this PR.

**Comment by Karlson2k** [comment]
@thesamesam @juippis please check this PR.

**Comment by Karlson2k** [comment]
@thesamesam Please check this PR with the major version update.

**Comment by thesamesam** [comment]
You don't need to ping 3 times for a PR that is only a week old..

**Comment by Karlson2k** [comment]
OK, no problem.
I though nine-days-old is already too old for a simple PR. :)

**Comment by Karlson2k** [comment]
Unlike xz, there is no binary in the tarbal, except test TLS certificates.

Sidenote: my previous PRs fro version updates were published usually in the same day when I publish the upstream tarball. This tarball one is more than one month old.

@eli-schwartz, if you think that three pings in 9 days is too much, I may delete this PR to avoid any concerns.
Should I proceed with it?
As a proxied maintainer I should try to keep repo updated for my packages, however I have no problems with not updating gentoo repo, if it is not needed.

**Comment by Karlson2k** [comment]
I'm *mostly* kidding as well. ;)
However the things around XZ are terrifying as they destroy trust in FLOSS community.

Frankly I thought that XZ-related cleanup has been finished quickly, but I haven't checked git commit log.

**Comment by Karlson2k** [comment]
This PR is one month old and still valid. ;)

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
