### PR TITLE
net-im/qtox: add ebuild for v1.4.0 release

### PR DESCRIPTION
**Pull request by zetok**
cc @gentoo/proxy-maint

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by wraeth** [comment]
I am currently running some tests on this ebuild, however there are a couple of points that I will note now:

- RDEPEND.suspect
This package has `virtual/pkgconfig` in `RDEPEND`, when normally this should only be in `DEPEND`. Is this required, or can the dependency be moved?

- EAPI
Currently this ebuild uses EAPI5. This could be bumped to EAPI6. You can read about the differences between them [here](https://projects.gentoo.org/pms/6/pms.html#x1-175000E).

Also, do you know of the `repoman` utility? This is installed with Portage itself and performs some QA checks on ebuilds. Running `repoman` should have highlighted the `RDEPEND.suspect` warning for you. `repoman` should generally be used to commit ebuilds to the tree (using `repoman commit`) and pre-format commit messages.

Thanks!

**Comment by zetok** [comment]
>This package has `virtual/pkgconfig` in `RDEPEND`, when normally this should only be in `DEPEND`. Is this required, or can the dependency be moved?

Done.

>Currently this ebuild uses EAPI5. This could be bumped to EAPI6. You can read about the differences between them [here](https://projects.gentoo.org/pms/6/pms.html#x1-175000E).

Thanks for the link, bookmarked, it will come useful when moving to EAPI6. :)

With that being said, no, ebuilds can't be moved to EAPI6 yet, since current stable portage version doesn't have the fix for the bug that is basically a deal-breaker for ebuilds that support user-patching.

https://github.com/gentoo/gentoo/pull/1033#issuecomment-195923761
[bug #573920](https://bugs.gentoo.org/573920)

After version with fix included gets stabilized, yeah, I too would want to move ebuilds to EAPI6.

>Also, do you know of the `repoman` utility? This is installed with Portage itself and performs some QA checks on ebuilds. Running `repoman` should have highlighted the `RDEPEND.suspect` warning for you. `repoman` should generally be used to commit ebuilds to the tree (using `repoman commit`) and pre-format commit messages.

Yeah, I've read about it on wiki some time ago, but as usual I forgot to use it. Thanks for reminder, I'll try to not forget to use it :)

**Comment by wraeth** [comment]
> With that being said, no, ebuilds can't be moved to EAPI6 yet, since current stable portage version doesn't have the fix for the bug that is basically a deal-breaker for ebuilds that support user-patching.

While, as I understand it, this is only an issue if the patch directory exists but is empty, it's fair enough - EAPI5 is still valid and usable.

My testing has finished and I am about to push, however there is one last point I will note: each commit should represent a complete and "repoman-happy"  state, meaning that these two commits could be squashed into one or the dependency fixed first and then the version bump added.

Given that this is quite minor, I've left it as-is, but it's something to note in the future.

Otherwise, good work, and thanks!

**Pull request closed without merging**
