### PR TITLE
dev-vcs/tortoisehg: 6.2.3 version bump; drop 5.8.1, 5.9.1, 6.1, 6.1.2, 6.2

### PR DESCRIPTION
**Pull request by band-a-prend**

### CODE REVIEW

**Comment by band-a-prend** [comment]
@thesamesam 
The python 3.11 compatibility of tortoisehg depends on >=mercurial-6.3.1 where were fixed regex issues.

If I will file a PR in the future could I use then the following form of restriction:
```
HG_DEPEND=">=dev-vcs/mercurial-5.9[${PYTHON_USEDEP}]
		use python_targets_python3_11 && >=dev-vcs/mercurial-6.3.1[${PYTHON_USEDEP}]
		<dev-vcs/mercurial-6.4[${PYTHON_USEDEP}]
"
```

**Comment by thesamesam** [comment]
> @thesamesam The python 3.11 compatibility of tortoisehg depends on >=mercurial-6.3.1 where were fixed regex issues.
> 
> If I will file a PR in the future could I use then the following form of restriction:
> 
> ```
> HG_DEPEND=">=dev-vcs/mercurial-5.9[${PYTHON_USEDEP}]
> 		use python_targets_python3_11 && >=dev-vcs/mercurial-6.3.1[${PYTHON_USEDEP}]
> 		<dev-vcs/mercurial-6.4[${PYTHON_USEDEP}]
> "
> ```

We must use python_gen_cond_dep, see python guide, I am on mobile but if you can't find it, let me know and I'll show you an example

**Comment by thesamesam** [comment]
> @thesamesam The python 3.11 compatibility of tortoisehg depends on >=mercurial-6.3.1 where were fixed regex issues.
> 
> If I will file a PR in the future could I use then the following form of restriction:
> 
> ```
> HG_DEPEND=">=dev-vcs/mercurial-5.9[${PYTHON_USEDEP}]
> 		use python_targets_python3_11 && >=dev-vcs/mercurial-6.3.1[${PYTHON_USEDEP}]
> 		<dev-vcs/mercurial-6.4[${PYTHON_USEDEP}]
> "
> ```

We must use python_gen_cond_dep, see python guide, I am on mobile but if you can't find it, let me know and I'll show you an example

**Comment by band-a-prend** [comment]
Thanks for tip. I found example in https://devmanual.gentoo.org/eclass-reference/python-r1.eclass/index.html :
```
PYTHON_COMPAT=( python3_{8..11} )
HG_DEPEND=">=dev-vcs/mercurial-5.9[${PYTHON_USEDEP}]
	$(python_gen_cond_dep '>=dev-vcs/mercurial-6.3.1[${PYTHON_USEDEP}]' python3_11 )
	<dev-vcs/mercurial-6.4[${PYTHON_USEDEP}]
"
```

**Pull request closed without merging**
