### PR TITLE
Scite update to 4.1.2 and removal of 3.x Versions

### PR DESCRIPTION
**Pull request by dermoench42**
new ebuild scite-4.1.2. Removal of 3,x Versions
Bug: https://bugs.gentoo.org/647586
Closes: https://bugs.gentoo.org/647586
Closes: #10534

Signed-off-by: Ervin Peters <ervin.peters@ervnet.de>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by dermoench42** [comment]
How to solve the "no signoff" complain?

**Comment by dermoench42** [comment]
Got it, sign-off is missing in the commit messages. Grrr

**Comment by juippis** [comment]
No no no, you can quite literally amend your commit afterwards to sign it, or even sign it when rebasing. You need to stop opening and closing these PRs over small things that can easily be fixed.

You can also automate the signoff so repoman signs your commit when using it. Check `man 5 make.conf` and search for DCO_SIGNED_OFF_BY.

**Comment by dermoench42** [comment]
Pardon, but I read 3 Times that it is not a good idea to amend commits
at the point published to github. This could be misleading, because of
pull requests, not merges...

All this should be covered in the doc ;)

But with #10562, I hope I got it. Thanks for the experiences, learned
much.

ervin

Am Tue, 04 Dec 2018 00:37:43 -0800 schrieb juippis
<notifications@github.com>:

> No no no, you can quite literally amend your commit afterwards to
> sign it, or even sign it when rebasing. You need to stop opening and
> closing these PRs over small things that can easily be fixed.
> 
> You can also automate the signoff so repoman signs your commit when
> using it. Check `man 5 make.conf` and search for DCO_SIGNED_OFF_BY.
> 


-- 
Ervin Peters
Herderplatz 12
D 99423 Weimar

Mobile: +49 172 2043926

http://coder.ervnet.de

**Comment by juippis** [comment]
>Pardon, but I read 3 Times that it is not a good idea to amend commits at the point published to github. This could be misleading, because of pull requests, not merges...

That's exactly it ;) you can mess around in PR as much as you like, but once the commit gets merged into the tree, it can not be touched anymore. (the commit that is, the FILES can but in new commits)

**Pull request closed without merging**
