### PR TITLE
media-sound/denemo: Version bump to 2.2.0

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/515888

I added static, debug and coverage USE flags as requested in the comments in above bug.
Don't have any knowledge about coverage analysis, so beside testing whether it compiles, I have no clue, whether the binary, produced by enabling coverage can be analyzed.

**Update: The test failure seem to be related to parallel build. I added -j1 to the src_test emake command and now it works.**

 **The package actually compiles fine, tested with several USE flag combinations, only the test fails:**
```
========================================
   denemo 2.2.0: tests/test-suite.log
========================================

# TOTAL: 2
# PASS:  1
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: integration
=================

# random seed: R02Sbe0860eb19e532efaf1182219b5c5325
1..39
# Start of integration tests
Opening /var/tmp/portage/media-sound/denemo-2.2.0/work/denemo-2.2.0/tests/fixtures/denemo/blank.denemo
ok 1 /integration/open-blank-file
**
ERROR:integration.c:152:test_open_save_blank_file: assertion failed: (g_file_test(output, G_FILE_TEST_EXISTS))
# ERROR:integration.c:152:test_open_save_blank_file: assertion failed: (g_file_test(output, G_FILE_TEST_EXISTS))
../build/tap-test: line 5: 19246 Aborted                 (core dumped) $1 -k --tap
```

### CODE REVIEW

**Comment by waebbl** [comment]
The log output of the test is at http://dpaste.com/355MABY for one month

**Comment by waebbl** [comment]
Ok, the tests are working now, it seems indeed to be an issue with parallel ebuilds.

**Comment by flappyports** [comment]
Package has been last-rited and is scheduled for removal due to dependency on old guile.

**Comment by radhermit** [comment]
Re-opening since the new version can use guile-2.

**Comment by flappyports** [comment]
@radhermit Should the PR be modified then to remove the possibility of depending on old guile based on the USE flag?

**Comment by flappyports** [comment]
@waebbl, please see previous comment from radhermit and adjust the ebuilds as needed.

**Comment by jonasstein** [comment]
media-sound/denemo was treecleaned, but I think we still want to have a working denemo ebuild in the tree in general. Waebbl works also on a personal overlay. If you want to help to improve the ebuild: https://github.com/waebbl/waebbl-gentoo/blob/master/media-sound/denemo/denemo-2.2.0.ebuild
@waebbl  I have not seen you since 4 months on IRC, are you still on board with denemo? Plaese look for help on IRC, so that we can get this finished.

**Pull request closed without merging**
