### PR TITLE
sys-apps/roccat-tools-5.1.0 & & dev-libs/libgaminggear-0.13.0: version bump

### PR DESCRIPTION
**Pull request by dpisklov**
Gentoo-Bug: https://bugs.gentoo.org/579512

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
src_configure failed with

```bash
CMake Warning (dev) at CMakeLists.txt:85 (FIND_PACKAGE):
  Ignoring EXACT since no version is requested.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at cmake_modules/FindLUA.cmake:12 (MESSAGE):
  Lua finder needs exact version!
```

This implies that even if lua is not selected, the configure script unconditionally expects it to be intalled for a version check.  This to me suggests the check itself is badly written.

Cannot add

**Comment by monsieurp** [comment]
@dpisklov ping?

**Comment by dpisklov** [comment]
Yeah I'm looking
27 мая 2016 г. 15:27 пользователь "monsieurp" <notifications@github.com>
написал:

**Comment by dpisklov** [comment]
Basically it's an upstream change, I'm trying to get hold of upstream dev to confirm if it's a bug or intended change to depend on Lua.

**Comment by dpisklov** [comment]
Upstream confirmed this is intended - I committed new version and retired old one.
Please merge

**Pull request closed without merging**
