### PR TITLE
Bitrise 1.32.0

### PR DESCRIPTION
**Pull request by koral--**

### CODE REVIEW

**Comment by mgorny** [comment]
The tests fail for me: 
[dev-util:bitrise-1.30.0:20190608-074343.log](https://github.com/gentoo/gentoo/files/3268309/dev-util.bitrise-1.30.0.20190608-074343.log)

**Comment by mgorny** [comment]
Ping.

**Comment by mgorny** [comment]
Now envman fails to run tests: [dev-util:envman-2.2.5:20190715-193848.log](https://github.com/gentoo/gentoo/files/3393916/dev-util.envman-2.2.5.20190715-193848.log)
So does stepman: [dev-util:stepman-0.11.7:20190715-194023.log](https://github.com/gentoo/gentoo/files/3393920/dev-util.stepman-0.11.7.20190715-194023.log)

**Comment by mgorny** [comment]
Ping.

**Comment by koral--** [comment]
Sorry for the delay I'll try to fix this ASAP.

**Comment by koral--** [comment]
It looks like something went wrong while rebasing. I'll create a new PR.

**Pull request closed without merging**
