### PR TITLE
dev-scheme/guile: Add 2.2.6 SLOT=2.2 + patches

### PR DESCRIPTION
**Pull request by fulax**
Bug: https://bugs.gentoo.org/689408
Closes: https://bugs.gentoo.org/598986
Closes: https://bugs.gentoo.org/590904
Closes: https://bugs.gentoo.org/629004

Signed-off-by: Cyprien Nicolas <cyprien@nicolas.tf>

### CODE REVIEW

**Comment by Amynka** [comment]
Hi, Can you please explain your idea with introduction of slotting?

**Comment by fulax** [comment]
Hi @Amynka 

My idea is to stop breaking packages like texmacs or lilypond, while keeping up with guile releases for toolchain packages like autogen.

No slot means we can only have one guile branch in gentoo. the guile-2.0 stabilization was required by autogen for toolchain updates, while we knew it would break packages like texmacs and other at that time. We are currently in the same situation regarding lilypond and guile-2.2.

SLOT will allow us to keep those packages around.

Upstream, guile-2.2 is on maintenance for a year or so, and guile-3.0 will be released in the coming months, and offers huge performance improvements. But I guess it will also break packages compatible with guile-2.0 or 2.2, so slots will enable us to provide guile-3.0 without breaking the whole ~arch depending packages.

My plan was to slot guile 2.2, see how it goes, then retro-slot guile 2.0, and keep guile-1.8 for texmacs (whose developers are concerned about the guile-2 performance issues and maybe will go with 3.0).

But I'm not a gentoo dev, I haven't been able to organize my time when I took the quizzes years ago, after slotting guile in the lisp overlay.

So I have to trust your judgement on this. I am convinced that SLOTing guile is the way to go, but I do not have the power to provide the maintenance effort it might require, I volunteer for proxy-maintenance, but the time I can devote to this is currently reduced to 2 to 3 weeks each month.

Thanks

**Comment by thesamesam** [comment]
@Amynka Are you okay with the principle of slotting based on this? Upstream seem to [intend](https://www.gnu.org/software/guile/manual/html_node/Parallel-Installations.html#Parallel-Installations) for multiple versions to be installed in parallel, to allow moving forward while older consumers haven't yet.

@fulax In general, a few weekends a month is enough.

**Comment by thesamesam** [comment]
> @Amynka Are you okay with the principle of slotting based on this? Upstream seem to [intend](https://www.gnu.org/software/guile/manual/html_node/Parallel-Installations.html#Parallel-Installations) for multiple versions to be installed in parallel, to allow moving forward while older consumers haven't yet.
> 
> @fulax In general, a few weekends a month is enough.

Let us know if you want to move forward with this.

**Pull request closed without merging**
