### PR TITLE
gnome-extra/chrome-gnome-shell: new package

### PR DESCRIPTION
**Pull request by nE0sIghT**
Hi everyone.

This PR continues https://github.com/gentoo/gentoo/pull/849.
Project was moved to GNOME infrastructure and 1st release as GNOME project was made.

Summary of PR commits:
1. Added [gnome-extra/chrome-gnome-shell](https://wiki.gnome.org/Projects/GnomeShellIntegrationForChrome) package that provides integration with GNOME Shell and the corresponding extensions repository https://extensions.gnome.org for Google Chrome browser and derivatives.
2. Added optional "chrome" use flag for gnome-base/gnome-shell that provides runtime dependency for gnome-extra/chrome-gnome-shell.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/gnome

**Comment by nE0sIghT** [comment]
Rebased to avoid gnome-shell-3.18.4-r1 (created/created) conflict

**Comment by leio** [comment]
No point in patching 3.16, we won't be adding such things to that.
Also it's unlikely we want to do it for 3.18 either, as it's stable and not sure we will do another pass of stabilization for this at this point. So we should look into getting this in together with 3.20 bump really.

**Comment by nE0sIghT** [comment]
I removed commit with gnome-shell changes.

**Comment by monsieurp** [comment]
@leio @tetromino can someone from the @gentoo/gnome team ack this package and merge it?

**Comment by nE0sIghT** [comment]
Pushed commit with fixed ```<bugs-to/>``` value in manifest file

**Comment by monsieurp** [comment]
Tested in my repo and looks OK. Gonna merge it ASAP.

**Comment by monsieurp** [comment]
Just a note: this packages depends on python:2.7, for the `gs-chrome-connector` script is indeed written in Python. For some reason, the maintainer took the cmake road and decided to have cmake install the script, instead of the traditional `setup.py`.

**Pull request closed without merging**
