### PR TITLE
sys-cluster/lmod: Add symlinks to profile

### PR DESCRIPTION
**Pull request by APN-Pucky**
Signed-off-by: Alexander Puck Neuwirth <alexander@neuwirth-informatik.de>

I had to setup those symlinks for lmod to work. 
Do you prefer copy/installing these files so that `etc-update` can handle updated profiles?

If you disagree with including this step in the ebuild I'll change the PR to adding a `post_install` message.

Cheers,
APN

### CODE REVIEW

**Comment by APN-Pucky** [comment]
The similar `modules` package also uses symlinks: https://github.com/gentoo/sci/blob/master/sys-cluster/modules/modules-4.6.0.ebuild

**Review by AndrewAmmerlaan — COMMENTED** [review]
Do we need to do something similar for the completion files?
```
/usr/share/Lmod/init/fish_tab_completion/module.fish
/usr/share/Lmod/init/lmod_bash_completions
```

**Comment by APN-Pucky** [comment]
> Do we need to do something similar for the completion files?
> 
> ```
> /usr/share/Lmod/init/fish_tab_completion/module.fish
> /usr/share/Lmod/init/lmod_bash_completions
> ```

I don't use/have fish, but in a normal bash I don't need `lmod_bash_completions` for completion since the call order of files is `profile`->`bash`->`lmod_bash_completions` .

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Pull request closed without merging**
