### PR TITLE
mail-filter/spamassassin: merge upstream patches + cleanup

### PR DESCRIPTION
**Pull request by Philippe23**
Almost the same as the files attached to https://bugs.gentoo.org/show_bug.cgi?id=579222, except the 3.4.0-r2 ebuild has a fix for a repoman flag (by specifying ":0" on openssl) and I've masked all the arches as well.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Thanks for the PR. This is a maintainer-needed package. Are you willing to maintain it as well?

**Comment by monsieurp** [comment]
@kentfredric @gentoo/perl I *KNOW* we dropped maintainership months ago. Could someone have a look at this PR still?

**Comment by kentfredric** [comment]
Why does github have to be so useless at comparing "copied a file before changing", *why*

**Comment by Philippe23** [comment]
> This is a maintainer-needed package. Are you willing to maintain it as well?

I actually have an open "Maintainership request" bug: https://bugs.gentoo.org/show_bug.cgi?id=583908
Footnote: I use a different e-mail address on the bug tracker than I do on Github to compartmentalize, but it's still me.

> Why does github have to be so useless at comparing "copied a file before changing", why

Try passing "--find-copies-harder" to git diff according to [](http://stackoverflow.com/questions/1043388/record-file-copy-operation-with-git).  (You got me curious.)

**Comment by Philippe23** [comment]
Crap.  I just realized I made this pull request reference my master instead of a specific commit.  Ignore the roundcube change that came after this request was openned.  Or I can submit a fresh pull request and this time use an actual branch.

**Comment by monsieurp** [comment]
> Or I can submit a fresh pull request and this time use an actual branch.
Please. It is a lot easier on our end to merge.

**Pull request closed without merging**
