### PR TITLE
Bump dev-python/torment

### PR DESCRIPTION
**Pull request by alunduil**

### CODE REVIEW

**Comment by hasufell** [comment]
QA messages look like unrelated java foo, otherwise looks fine

**Comment by alunduil** [comment]
Do I need to do anything else or will this be merged shortly?

**Comment by hasufell** [comment]
> Do I need to do anything else or will this be merged shortly?

You can just merge/push yourself.

**Comment by mgorny** [comment]
Yeah, I'd suggest you do that since you have commit rights. We can help a bit with reviews and CI runs, but please don't abuse us ;-).

**Comment by alunduil** [comment]
So I should just skip this process in the future?  @hasufell made it sound like this was the way to go since my code has items that need to be updated on seemingly every commit.

**Comment by hasufell** [comment]
@alunduil nah, I said it's fine to have pre-commit reviews if you need help with new ebuilds or even version bumps, but it's not necessary as a general workflow and we currently don't have the manpower :)

**Comment by alunduil** [comment]
Alright, can I request any post-commit reviews just get turned into bugs rather than github comments then?

**Comment by hasufell** [comment]
I am not sure I have the time to file a bug for every missing `|| die` I find. Filing a bug takes ~10x the time of responding on github or via mail. So for trivial things, I do prefer those methods. For some things, bug reports are more appropriate ofc.

**Comment by alunduil** [comment]
I guess we're at an impasse until we can find a better way to merge workflows.  Perhaps we should try to hash it out when we both have time (I'm guessing nearly never).  Let me know what you think.

**Comment by hasufell** [comment]
> Let me know what you think.

If you want to make pre-commit reviews possible, you'll have to help the team.

**Comment by alunduil** [comment]
I can with what little time I have.  How does one proceed?

**Comment by hasufell** [comment]
@alunduil You just add yourself here https://wiki.gentoo.org/wiki/Project:Reviewers and start reviewing pull requests... when I have extra time, I skim through the commits overview on github and look for version bumps and ebuild additions.. hence those pesky post-commit reviews. But our focus is definitely on pull requests

**Pull request merged**
