### PR TITLE
sys-fs/mount-zip: Add mount-zip 1.0.11 and 1.0.12

### PR DESCRIPTION
**Pull request by fdegros**
Bug: https://bugs.gentoo.org/914374
Closes: https://bugs.gentoo.org/914375

### CODE REVIEW

**Comment by Flowdalic** [comment]
Does this fix the mentioned bugs? If so, then please use the `Closes:` git trailer instead.

**Comment by fdegros** [comment]
> Does this fix the mentioned bugs? If so, then please use the `Closes:` git trailer instead.

I don't know if it closes the bugs yet. At least, the new version 1.0.11 tries to address them. But nothing has changed for the version 1.0.10 against which the bugs were reported.

**Comment by ceamac** [comment]
Bug 914375 is fixed, the other one is not.

[build.txt](https://github.com/gentoo/gentoo/files/13776575/build.txt)

**Comment by Flowdalic** [comment]
Why not simply add just 1.0.22?

**Comment by fdegros** [comment]
> Why not simply add just 1.0.22?

What is 1.0.22?

At the moment, `mount-zip` 1.0.11 and 1.0.12 have been released, but they are not part of Gentoo yet.

**Comment by Flowdalic** [comment]
> What is 1.0.22?

Sorry, typo, I meant 1.0.12. Is there a reason why we would also want to add 1.0.11?

**Comment by fdegros** [comment]
> Is there a reason why we would also want to add 1.0.11?

If we add 1.0.12, which is the most recent release, there is no real reason to also add 1.0.11.

Version 1.0.11 is there because this PR was first created three months ago, at the time when 1.0.11 was the most recent release, and this PR still hasn't been merged. I thought I would be removing old versions in a subsequent commit.

The review process is quite opaque to me. What is the usual timeline for such a review? What's the next step to be taken, and who should take it?

**Pull request closed without merging**
