### PR TITLE
Retire proxy maintainer (William Breathitt Gray) from various packages

### PR DESCRIPTION
**Pull request by vilhelmgray**
I'm removing myself from some packages I no longer use in the hopes that someone more familiar with these projects can maintain them better.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Many of these packages has games@g.o listed as a maintainer, so adding `	<!-- maintainer-needed -->` there is not necessary ;)

Please update the relevant metadata.xml files. You most likely just used a sed magic :P 
https://github.com/pkgcore/pkgcheck/issues/239

**Comment by vilhelmgray** [comment]
Oops, you're right. I'll fix these up. :-)

**Review by juippis — APPROVED** [review]
Thanks! Could you send the "packages up for grabs" mail to gentoo-dev? Let me know if not, and I'll do it.

**Comment by chewi** [comment]
Doom's more important, right!? :wink:

**Pull request closed without merging**
