### PR TITLE
www-servers/resin: clean duplicate files

### PR DESCRIPTION
**Pull request by hanetzer**
Package-Manager: Portage-2.3.28, Repoman-2.3.9

### CODE REVIEW

**Comment by chewi** [comment]
In this case, you may as well just drop the old versions entirely.

**Comment by hanetzer** [comment]
@chewi how many old versions?

**Comment by chewi** [comment]
All of them, just keep 4.0.48-r1.

**Comment by hanetzer** [comment]
@chewi k, done. Went ahead and made the patch names we were keeping match the
version we were keeping as well.

**Pull request closed without merging**
