### PR TITLE
net-misc/i2pd: version bump 2.10.0

### PR DESCRIPTION
**Pull request by khumarahn**
@tomboy-64 @klondi @blueness

### CODE REVIEW

**Comment by doughdemon** [comment]
Compare `/usr/portage/licences/BSD` to the upstream license to see whether it is correct.

**Comment by blueness** [comment]
pushed

**Comment by blueness** [comment]
I pushed this already.  Can you please verify asap and close if its correct, else please fix it.  We shouldn't keep the wrong license in the tree.

**Comment by khumarahn** [comment]
Looks correct. Closing. Thank you.

**Pull request closed without merging**
