### PR TITLE
sci-libs/shapelib: version bump 1.5.0

### PR DESCRIPTION
**Pull request by cjmayo**
No longer dependent on sci-libs/proj:
http://shapelib.maptools.org/release.html

Bump to EAPI 7

```
--- shapelib-1.4.1.ebuild
+++ shapelib-1.5.0.ebuild
@@ -1,7 +1,7 @@
 # Copyright 1999-2019 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
 
 inherit autotools
 
@@ -14,9 +14,6 @@
 KEYWORDS="~amd64 ~arm ~arm64 ~ppc ~ppc64 ~x86 ~x86-fbsd ~amd64-linux ~x86-linux"
 IUSE="doc static-libs"
 
-RDEPEND="sci-libs/proj"
-DEPEND="${RDEPEND}"
-
 src_prepare() {
 	default
 	rm -r m4/* || die
```

### CODE REVIEW

**Comment by steils** [comment]
> ```
> -RDEPEND="sci-libs/proj"
> -DEPEND="${RDEPEND}"
> ```

Please do not remove this. If a package does not depend on anything outside `@system`, set `[R]DEPEND=""` explicitly.

Also this change closes bug 685232, so you might add
```
Closes: https://bugs.gentoo.org/685232
```
to the commit message.

**Comment by cjmayo** [comment]
> > ```
> > -RDEPEND="sci-libs/proj"
> > -DEPEND="${RDEPEND}"
> > ```
> 
> Please do not remove this. If a package does not depend on anything outside `@system`, set `[R]DEPEND=""` explicitly.

Done.

> 
> Also this change closes bug 685232, so you might add
> 
> ```
> Closes: https://bugs.gentoo.org/685232
> ```
> 
> to the commit message.

Added.

**Comment by Amynka** [comment]
@steils  feel free to merge, but please test it first and check properly.. Thank you :)

**Comment by steils** [comment]
Thanks. I have also fixed Prefix support and pushed.

**Pull request closed without merging**
