### PR TITLE
dev-python/cryptography ~ia64 removal CI run

### PR DESCRIPTION
**Pull request by mgorny**
So it happened and cryptography upstream has made a release requiring Rust. This means that long-term we're losing this package at least for alpha, hppa and ia64. Other arches (e.g. ppc) are heavily depending on Gentoo maintainers finally making Rust work on them (it's apparently supported upstream).

`~ia64` should have the lowest number of keywords on Python packages, so let's start estimating the damage by dekeywording cryptography there.

### CODE REVIEW

**Comment by mgorny** [comment]
TODO: try to figure out if we can selectively skip tests in some of these packages

**Comment by mgorny** [comment]
Test checklist:

- [x] dev-python/aiohttp: handles missing trustme gracefully
- [x] dev-python/cheroot: added conditional EPYTEST_IGNORE
- [ ] dev-python/fs
- [ ] dev-python/passlib
- [ ] dev-python/pip
- [ ] dev-python/pypiserver
- [ ] dev-python/requests
- [ ] dev-python/requests-toolbelt
- [ ] dev-python/trio
- [ ] dev-python/twisted
- [ ] dev-python/urllib3
- [ ] dev-python/werkzeug

**Comment by mgorny** [comment]
(note: temporary breakage while pip is being rekeyworded)

**Review by arthurzam — APPROVED** [review]

**Review by arthurzam — APPROVED** [review]

**Comment by mgorny** [comment]
Merged.

**Pull request closed without merging**
