### PR TITLE
sys-libs/compiler-rt: Override start symbol when adding -nostartfiles

### PR DESCRIPTION
**Pull request by miller-alex**
* Add -emain together with -nostartfiles to LDFLAGS in sys-libs/compiler-rt-14.0.6-r1.

* flag-o-matic.eclass: test-flag-PROG, strip unused args that generate warnings
I think that the exemption wrt. -Qunused-arguments is no longer necessary, so I dropped it.
Instead, we could actually add -Qunused-arguments to the flags to get rid of the warnings,
but that would be much more complicated, so let's try the simpler solution.
If further discussion is needed I can move the commit to a separate pull request.

### CODE REVIEW

**Comment by mgorny** [comment]
CC @akhuettel, @thesamesam

**Comment by mgorny** [comment]
BTW congratulations, you've managed to DoS pull request assignment script by listing wrong bug ID in the second commit!

So much for free Sunday…

**Comment by mgorny** [comment]
> BTW congratulations, you've managed to DoS pull request assignment script by listing wrong bug ID in the second commit!
> 
> So much for free Sunday…

(please don't fix it yet, I want to fix the script)

**Comment by mgorny** [comment]
Ok, please fix the bug ref now ;-).

**Comment by thesamesam** [comment]
Thanks! Sent eclass patch to ML.

**Comment by thesamesam** [comment]
Thanks!

**Pull request closed without merging**
