### PR TITLE
www-misc/monitorix: Fix for bug#580210

### PR DESCRIPTION
**Pull request by Silmano**
This update removes the information leakage bug created in the previous version.

Reported-by: Göktürk Yüksek <gokturk@binghamton.edu>

### CODE REVIEW

**Comment by Amynka** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
@gktrk Hi! Could you please review this PR?

**Comment by idella** [comment]
gokturk already appears to have done this.

1.  emerge -epv @system | grep "sed" reveals immediately that sys-apps/sed is indeed included in @system. It may be removed from all 3 ebuilds, noting that this is a carry over from the
monitorix-3.5.1.ebuild.
2. The sed statements in src_prepare do indeed need the "|| die"
3. The making of src_compile() I would seek further opinion on. This was never done for 
monitorix-3.5.1.ebuild and it was never before declared a bug or break in the ebuild.
4. I suggest you seek further advice on the placement and installation of systemd files. I would have thought that having a systemd file in docs was a sane selection of location for if it might be required by a user.

As Amynka said above, the fix need be applied to both versions 3.6.0 & 3.8.1, and 3.6.0 could even be removed without issue

**Comment by Silmano** [comment]
May I ask why wasn't all the QA issues been reported for 3.5.1? I though that build didn't had any more issues aside from the bugs already opened in the past years.

As for the bug, from my point of view, I think it should be divided in two. I mean, we have clearly two issues:

1. The leakage bug with the chmod 777
2. The QA issues that where previously found in 3.5.1

Shouldn't we try to solve the first one, so mask in the package can be lifted? I don't mind in looking for all the QA issues, in fact I had in mind rewriting the build with the last EAPI, but I don't think the QA issue has anything to do with the leakage.

As for the 3.6.0, should I update it as well or should we remove it from the portage tree and focus in 3.8.1?

**Comment by idella** [comment]
Silmano you may ask why the ebuild of 3.5.1 was not clean, but the answer is simply it was missed.
Frankly, minor issues like those have been added and missed in the past. I skipped over in perusing the ebuild and also missed them. gokturk stopped and trawled every line, post commit.

It is just as easy to rectify  the minor issues 1 & 2 in this pull req. 
```bash
~/github/gentoo/www-misc/monitorix $ sudo ebuild monitorix-3.8.1.ebuild clean compile
>>> Compiling source in /mnt/gen2/TmpDir/portage/www-misc/monitorix-3.8.1/work/Monitorix-3.8.1 

make --jobs=9 --load-average=4.0 
Run one of the following:
  make install-systemd-all (systemd based systems)
  make install-upstart-all (upstart based systems)
  make install-debian-all (legacy debian sysv based systems)
  make install-redhat-all (legacy redhat sysv based systems)

Default targets may be overridden on the shell so
check out the Makefile for specific rules.
>>> Source compiled.
```
There was no compiling by a Makefile. Point 3 should never have been raised.

You merely re-commit and re force push.  The tip to just bump one version still stands, and just remove the superfluous monitorix-3.6.0.ebuild. 
The important thing is the reversion to "chown monitorix:monitorix"

**Comment by Silmano** [comment]
I've added the fixes to issues 1 & 2 and recommited the changes. Should this suffice or should I also include the removal of 3.6.0 ebuild?

**Comment by idella** [comment]
The $msg for " || die"  are optional and with sed are not used; i.e. just "|| die" will suffice. They do not make it wrong though.
As I said, either duplicate those changes to the monitorix-3.6.0.ebuild, or remove it as un-needed.

**Comment by Silmano** [comment]
I've applied the same changes to 3.6.0, since it was requested in [Bug#539480](https://bugs.gentoo.org/show_bug.cgi?id=539480).

**Comment by NP-Hardass** [comment]
> May I ask why wasn't all the QA issues been reported for 3.5.1? I though that build didn't had any more issues aside from the bugs already opened in the past years.

Honestly, it doesn't matter why.   Simple fact of the matter is that as a proxied maintainer, you are bound by project policy (https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Commit_Policy_for_Users) which in this case, states that while you do not have to update preexisting ebuilds to fix QA issues, any submissions by you must conform to QA standards.  The fact that your commit originally went through with QA issues was a blunder, which obviously you can now correct.

**Comment by Silmano** [comment]
> any submissions by you must conform to QA standards.

Aside from running `repoman full`, is there any other way to check the QA standards? I followed the guide and executed the `repoman` command before making the commit, but the command didn't output any error in my case.

**Comment by NP-Hardass** [comment]
> any submissions by you must conform to QA standards.
Aside from running repoman full, is there any other way to check the QA standards? I followed the guide and executed the repoman command before making the commit, but the command didn't output any error in my case.

Running repoman full is exactly what you should have done.  There isn't much else (apart from another qa tool like pkgcheck, but I don't think it's necessary to do that). Fine points like calling || die are discussed throughout the devmanual.  Any instances missed by you should be picked up by your proxy upon review.

**Comment by gktrk** [comment]
Hi @Silmano, sorry for the late response.

> emerge -epv @system | grep "sed" reveals immediately that sys-apps/sed is indeed included in @system.

I would add '--nodeps' to it just to be safe. You can also check the contents of [profiles/base/packages](https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/base/packages) which contains the @system set. Devmanual has a [section](https://devmanual.gentoo.org/profiles/packages/index.html) on the topic too.

> The sed statements in src_prepare do indeed need the "|| die"

You can find more about error handling [here](https://devmanual.gentoo.org/ebuild-writing/error-handling/index.html)

> There was no compiling by a Makefile. Point 3 should never have been raised.

There *shouldn't* be any compiling by the Makefile. It just so happens that this one does not define a default target. I think it's good practice to override the compile phase if the package is not supposed to compile anything, noting that the default behavior of src_compile() is to call emake. Here is one example: [www-apps/lxr](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-apps/lxr/lxr-0.9.8-r1.ebuild?id=755b2562ee02f018d83abb99f12abe0238e9690f#n53). Also, there's no need to go all the way down the call stack just to bail out in the end.

> I suggest you seek further advice on the placement and installation of systemd files. I would have thought that having a systemd file in docs was a sane selection of location for if it might be required by a user.

I don't use systemd, so I don't know if this runs on systemd systems. However, given the following line:

> systemd_dounit **docs/${PN}.service**

Installing the same service file using dodoc isn't necessary: 

> dodoc Changes README{,.nginx} **docs/${PN}.service** docs/${PN}-{alert.sh,apache.conf,lighttpd.conf}

&nbsp;
> May I ask why wasn't all the QA issues been reported for 3.5.1?

Sometimes things slip by :) Please don't take my review personal. It is focused on repairing the ebuild, not criticizing you in any way.

> As for the bug, from my point of view, I think it should be divided in two. I mean, we have clearly two issues:
>
> 1. The leakage bug with the chmod 777

The leakage bug is enabled by the chmod which is a QA violation. It is also partially the package's fault that it follows symlinks. Perhaps that should be reported upstream.

I'll look at possible fixes to the problem and report back.

**Comment by gktrk** [comment]
In any case, chown should be replaced with its Gentoo equivalent [fowners](https://devmanual.gentoo.org/function-reference/install-functions/index.html) which operates on ${D}, not the live system. Therefore, it needs to be called in src_install(). See the [www-misc/zoneminder](https://gitweb.gentoo.org/repo/gentoo.git/tree/www-misc/zoneminder/zoneminder-1.28.1.ebuild#n118) example.

**Comment by NP-Hardass** [comment]
Something else that might be nice... Rather than calling sed multiple times in a row, you can chain sed with the -e flag.  so sed -e "s/sub1/rep1/g" -e "s/sub2/rep2/" -i somefile || die

**Comment by idella** [comment]
It should be apparent now that the "chown monitorix:monitorix /var/lib/${PN}/www/imgs"
should be 
fowners monitorix:monitorix /var/lib/${PN}/www/imgsor

or possibly even 

fowners apache:apache /var/lib/${PN}/www/imgsor

(given that a file "apache.conf" is installed into the docs location) within src_install()

**Comment by Silmano** [comment]
@gktrk Thanks for the explanation, I will update the ebuild with the recommendations.

@idella The package has some example configuration for apache, lighttpd and also nginx. Since not everyone will be using apache, I think its best to stick to the monitorix user right now.

There is an open bug [Bug#524970](https://bugs.gentoo.org/show_bug.cgi?id=524970) with information to fix this issue. Correct me if I'm wrong, but I don't think it should be added to the PR we're handling right now, but in a new one.

**Comment by Silmano** [comment]
I've updated the reported QA issues present in the build. Could you check if all its ok now?

**Comment by gktrk** [comment]
Hi,

Looks good for the most part. I'd like to make a few points:

- I think a revision bump is required at this point: all the users who have installed the vulnerable version will remain vulnerable until they merge the fixed version. The package manager will not reinstall unless there's a newer version or revision (newuse, changed-use etc. excluded). Revbumping the package (as in monitorix-3.6.0-r1 and monitorix-3.8.1-r1) and removing the old ones, since they contain the vulnerability, should fix that.

- I see that you inherit [eutils](https://devmanual.gentoo.org/eclass-reference/eutils.eclass/index.html) but you don't utilize any of the eclass functions. Unnecessary inherit should be removed.

- In terms of local use flags, looks like some of the flags have become global USE flags and there's no need to list them in metadata.xml:
  - **global:hddtemp**: Enable monitoring of hdd temperature (app-admin/hddtemp)

    **local:hddtemp:www-misc/monitorix**: Use SMART to monitor the temperature of hard drives with app-admin/hddtemp.

  - **global:lm_sensors**: Add linux lm_sensors (hardware sensors) support

    **local:apcupsd:www-misc/monitorix**: Make use of a daemon that controls APC UPSes with sys-power/apcupsd.

- As for addressing [#524970](https://bugs.gentoo.org/show_bug.cgi?id=524970), there is no technical reason why it cannot be done in this PR. However, it's up to the devs to decide that. Keep in mind that if you follow the suggestion in the bug and modify the init script in a new commit, you'll need another revision bump to ensure that users upgrade to the new init script.

  Also, I don't know if the functionality similar to checkpath, as suggested in the bug, exists for systemd.

- As for the security vulnerability itself, I still think this should be reported upstream. I don't know perl but I think the culprit is `lib/HTTPServer.pm`:
```
216        if($target_cgi eq "monitorix.cgi") {
217                chdir("cgi");
218                open(EXEC, "./$target_cgi |");
219                @data = <EXEC>;
220                close(EXEC);
221        } elsif($target) {
222                if(open(IN, $target)) {
223                        @data = <IN>;
224                        close(IN);
225                }
226        }
```

- This is a minor nitpick but you can multiline sed statements to increase readibility if you like:
```
sed -e "s|\(base_dir.*\)/usr/share/${PN}|\1/usr/share/${PN}/htdocs|" \
	-e "s|\(secure_log.*\)/var/log/secure|\1/var/log/auth.log|" \
	-e "s|nobody|${PN}|g" -i ${PN}.conf || die
```

Hope this helps,

**Comment by idella** [comment]
yes it will require a revbump due to the above. A for metadata content, you can do that  separately. The salient issue here it the +	fowners monitorix:monitorix /var/lib/${PN}/www/imgs with a revbump

**Comment by Silmano** [comment]
I've edited the commit to move the ebuild to `monitorix-3.8.1-r1` to force the update of the affected users. Also updated it to reflect the latest changes given.

I've reported the issue upstream to see if we find a definitive solution as well.

**Comment by gktrk** [comment]
LGTM. Thanks for putting up with me :)

**Pull request closed without merging**
