### PR TITLE
*/*: fix MissingRemoteId for maintener-needed packages

### PR DESCRIPTION
**Pull request by cfuga**
*: fix MissingRemoteId for maintener-needed packages

Signed-off-by: Cristian Othón Martínez Vera <cfuga@cfuga.mx>

### CODE REVIEW

**Comment by thesamesam** [comment]
Would you mind splitting to one-commit-per-package? I have a script which helps do this: https://github.com/thesamesam/sam-gentoo-scripts/blob/main/git/commit-changed-pkgs.

**Comment by cfuga** [comment]
> Would you mind splitting to one-commit-per-package? I have a script which helps do this: https://github.com/thesamesam/sam-gentoo-scripts/blob/main/git/commit-changed-pkgs.

Sure! I'll revert my current patches, and update this PR after running your script. Thanks!

**Comment by ceamac** [comment]
This is funny.  What's up with [Revert "app-emulation/virtualbox: drop 7.0.6-r1"](https://github.com/gentoo/gentoo/pull/29710/commits/2ff50dd332cddfa361a1a226b1c48a2194d29164) and [Revert "Revert "app-emulation/virtualbox: drop 7.0.6-r1""](https://github.com/gentoo/gentoo/pull/29710/commits/a222fc5bcfcc7c384113d91d27963376fc0cc6ed)?

**Comment by thesamesam** [comment]
> > Would you mind splitting to one-commit-per-package? I have a script which helps do this: [thesamesam/sam-gentoo-scripts@`main`/git/commit-changed-pkgs](https://github.com/thesamesam/sam-gentoo-scripts/blob/main/git/commit-changed-pkgs?rgh-link-date=2023-02-22T16%3A52%3A57Z).
> 
> Sure! I reverted my initial patches, and updated this PR after running your script. Thanks!

Thanks! It looks like the commit message mangling didn't work, for some reason. In the template, try "*: fix MissingRemoteId for maintainer-needed packages"? At worst, I can do it for you, so no big deal.

**Comment by cfuga** [comment]
> This is funny. What's up with [Revert "app-emulation/virtualbox: drop 7.0.6-r1"](https://github.com/gentoo/gentoo/pull/29710/commits/2ff50dd332cddfa361a1a226b1c48a2194d29164) and [Revert "Revert "app-emulation/virtualbox: drop 7.0.6-r1""](https://github.com/gentoo/gentoo/pull/29710/commits/a222fc5bcfcc7c384113d91d27963376fc0cc6ed)?

My bad. When I was reverting my patches, I copied the wrong hash from ```git log``` and reverted a totally unrelated commit. I could deleted the branch, but it's already attached to this PR.

**Comment by thesamesam** [comment]
Sure, no problem. Thank you for the PR!

**Comment by thesamesam** [comment]
All done! I kept your authorship for the split commits, of course.

FWIW, what I did was:
1. git reset origin/master # note: no --hard, this just drops all the commits but keeps the changes
2. I put `*: fix MissingRemoteId for maintainer-needed packages` in `~/git/sam-gentoo-scripts/git/template-pkgdev`
3. bash `~/git/sam-gentoo-scripts/git/template-pkgdev`

I fixed the repoman references in that repository today after @juippis pointed it out, I think that might have been why your attempt went wrong (as repoman used to accept another format).

Cheers.

**Pull request closed without merging**
