### PR TITLE
x11-misc/qt5ct: Qt5 Configuration Tool

### PR DESCRIPTION
**Pull request by mndar**
This program allows users to configure Qt5 settings (theme, font,
icons, etc.) under DE/WM without Qt integration.

Ebuild-By: Mandar Joshi <emailmandar@gmail.com>
Reported-By: Michael Palimaka <kensington@gentoo.org>

### CODE REVIEW

**Comment by monsieurp** [comment]
@kensington

**Comment by monsieurp** [comment]
Something is up with the metadata.xml file. Make sure it passes our QA checks.

**Comment by mndar** [comment]
Updated the ebuild & metadata with help of the kind folks at #gentoo-proxy-maint and #gentoo-dev-help

**Comment by idella** [comment]
The Manifest file has a +EBUILD and it should not.   Maybe uou have locally changed 'thin-manifests = true' to 'thin-manifests = false' in metadata/layout.conf. Either way this entry of
+EBUILD  in the Mxnifest ought not be present

**Comment by idella** [comment]
This looks to have been overlooked in past few days. It passes all required qa checks.

emake INSTALL_ROOT="${ED}" install
could equally be
emake INSTALL_ROOT="${D}" install
Both work and the preferred choice appears contentious.

**Comment by idella** [comment]
I think it will be easier if you re-do this form scratch using a new branch made just for the pull requests which is the norm.  The final patch has all three commits. one for each of the 26 28 30 April. The final patch was wrong since it was taking out a + EBUILD file which should not be there in the first place and was missing the actual entry of the qt5ct ebuild.  Re-do and add the new final patch in one clean hit and all will be fine.
The ebuild is fine. The metadata.xml is fine. The battle here is with git and the use of a branch.

**Comment by mndar** [comment]
idella,
Thanks for reviewing the PR. I'll re-do this from scratch as you suggested.

**Comment by mndar** [comment]
As advised, re-did the PR from scratch. New PR: https://github.com/gentoo/gentoo/pull/1173

**Comment by monsieurp** [comment]
This PR goes on in #1173.

**Pull request closed without merging**
