### PR TITLE
dev-lua/luaossl: Introduce new ebuild

### PR DESCRIPTION
**Pull request by jirutka**

### CODE REVIEW

**Comment by idella** [comment]
@gentoo/proxy-maint 

ty we shall review this now

**Comment by idella** [comment]
Well to open the review, the commit msg leaves me rather cold.  Introduce new ebuild is in fact 'stating the bleedin' obvious', to coin a rather blunt phrase.
Generally it goes, "Initial ebuild written by me"
which will work since the commit will carry 'you' as author.
So then, why was this ebuild added to portage?
What value does it add?
Also, why was use of a snapshot used here given snapshots are the exception to the rule.

These are the elements that an effective commit msg 'communicates'

**Comment by jirutka** [comment]
> So then, why was this ebuild added to portage?

Because I need it and I think it’ll be useful even for others.

> What value does it add?

Isn’t that obvious? Maybe I don’t understand the question…

> Also, why was use of a snapshot used here given snapshots are the exception to the rule.

This isn’t a snapshot version, it’s a stable release. Author of the module just uses kinda weird version numbers…

**Comment by idella** [comment]
Because I need it and I think it’ll be useful even for others actually look pretty reasonable.
So you need it to meet service what needs or outcomes exactly? An naswer to this in a commit msg is useful and helpful.

What value does it add? is mostly something to get you thinking. It serves an example of what might be put into a commit msg. It is certainly not obligatory.

 Author of the module just uses kinda weird versioning
Roger that. I have actually seen weirder

**Comment by jirutka** [comment]
It’s dependency of nginx module [ngx-oauth](https://github.com/jirutka/ngx-oauth) that I’m currently working on.

**Comment by jirutka** [comment]
I forgot to PGP sign the commit, fixed now.

**Comment by idella** [comment]
In that case  dependency of nginx module ngx-oauth is definitely worthy of inclusion in the msg. I'll acquire this and runtest it

**Comment by jirutka** [comment]
I’m not sure if it’s relevant. I don’t have ebuild for ngx-oauth (yet), it’s not even released.

**Comment by idella** [comment]
In that case, retry a commit msg that says why it is being added and or what benefit or value it will bring. Addition ahead of another package such as  ngx-oauth  not yet added perhaps makes it premature but still pertinent. Do you anticipate dropping working on  ngx-oauth and having this dev-lua/luaossl forever being a loose end added in a rush of blood? I don't think so.
Now to look at the actual ebuild.

**Comment by jirutka** [comment]
> Do you anticipate dropping working on ngx-oauth and having this dev-lua/luaossl forever being a loose end added in a rush of blood?

I believe that I’m not the only one for whom this ebuild may be useful, so it’s irrelevant. Otherwise I’d just added it to [my overlay](https://github.com/cvut/gentoo-overlay). And no, I’m definitely not gonna stop working on ngx-oauth. ;) It’s almost finished.

**Comment by idella** [comment]
All good

**Comment by idella** [comment]
Oh I believe I missed this
"Please look at commit history of this repo, it’s pretty common message for introduction of new ebuild."

Are you familiar with the phrase two wrongs don't make a right?

The ^^ has all the hallmarks of attempting to backup / justify the validity of the commit msg. You are then concerned about the rightness or 'aptness'. It is saying 'this commit msg is perfectly fine and long practised here'.
So let's expand here slightly

1.  history of this repo is in fact your overlay. In a personal overlay one can make commit messages like that and it's fine. However you simply had no idea you were constantly practising a bad or poor practice.
2. So 'Please' peruse the portage tree and observe commit messages for new ebuilds.
3. Realise sooner than later this is the portage tree to which you are adding packages lead with a commit message.
4. It is a gentoo dev who reviews and commits the final patch here according to the patch adhering to the reqs of gentoo protocol and style, not that of personal overlays. Even then, sometimes they slip up and commit 'stuff' that in the end gets reverted. I did it once to such a commit. gentoo devs too are 'human'.

The goal here is submit a patch and have it declared ticking all the boxes set by gentoo / portage protocol, and not enforcing your practised style in the confines of a personal overlay.
"Introduce new ebuild #372" is not a commit msg that I will be submitting in this pull request. If it is in fact submitted, it will not be by me.

After this; then all good

**Comment by idella** [comment]
It can be too easy to miss the obvious once immersed in something.

~/github/gentoo/dev-lua/luaossl $ ebuild luaossl-20150727.ebuild compile

to the PKG_CONFIG_PATH environment variable
No package 'lua' found
>>> Source prepared.
>>> Configuring source in /mnt/gen2/TmpDir/portage/dev-lua/luaossl-20150727/work/luaossl-rel-20150727 ...
>>> Source configured.
>>> Compiling source in /mnt/gen2/TmpDir/portage/dev-lua/luaossl-20150727/work/luaossl-rel-20150727 ...
make -j4 CC=x86_64-pc-linux-gnu-gcc prefix=/usr openssl 
make: *** No rule to make target 'openssl'.  Stop.

Once corrected;

~/github/gentoo/dev-lua/luaossl $ ebuild luaossl-20150727.ebuild compile
yields
>>> Source compiled.

What was missing ofc was
```ebuild
DEPEND="${RDEPEND}
                dev-lang/lua:0
```

**Comment by idella** [comment]
Actually correction. virtual/pkgconfig will pull it in but I skipped the deps check by use of ebuild.sh. Cancel that part

**Comment by idella** [comment]
One minor addition. You might care to add
<description>Proxied maintainer; set to assignee in all bugs</description>
to the edited metadata.xml, seeing you have need to amend the git patch anyway.
The source of this line is https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers

**Comment by idella** [comment]
I was expecting this to finished within 2 days of last comment then nothing.
This period of time hints at one of two things. Whichever, I shall simply close this to clear dead data if nothing within a few days

**Comment by jirutka** [comment]
>> "Please look at commit history of this repo, it’s pretty common message for introduction of new ebuild."

> 1. history of this repo is in fact your overlay. … The goal here is submit a patch and have it declared ticking all the boxes set by gentoo / portage protocol, and not enforcing your practised style in the confines of a personal overlay.

I still wonder if you’re serious or just trolling me. Isn’t it pretty obvious that “this repo” means https://github.com/gentoo/gentoo (Portage tree), the repository in which this pull requested is opened? Do you think that I’m total idiot to argue with commit style in my own overlay, that is of course totally irrelevant here?

> So 'Please' peruse the portage tree and observe commit messages for new ebuilds.

I did. Did you? The last new ebuilds in the Portage tree:

* dev-go/go-sqlite3: new package 2a49cfa9a7c79e18db738b8c4abbb36ca56b6f9d
* app-emulation/grub-xen-host: initial version: Initial version to provide a dom0 host PV grub based on grub 2. 3387c0a6f28f10d691dee9c96cca9c17c17b62f8
* dev-ml/ocaml-cairo: initial import; ebuild by me f7c9abd9fad7e0e9224ed7bd0106fac3b97c719e
* dev-ml/mongo: initial import; ebuild by me 9cce3179beb1d14edde2af712f295562481e41dd
* dev-ml/bson: initial import; ebuild by me 3fc68d2793c4c4a2381226bdd9548874fb272f7c
* dev-haskell/arithmoi: initial import, numeric library: Efficient basic number-theoretic functions. Primes, powers, integer logarithms for haskell. bcaeae87be7a6df5341e903782dc46e373dcbe3a
* dev-ml/ppx_jane: initial import; ebuild by me 4851d06031cede9063a518f8e9cc3c5ba09660cf

Should I continue?

**Comment by monsieurp** [comment]
@jirutka sorry it's taken so long. Your contribution slipped off of our radar. Please make sure you do have a Bugzilla account as well so that bug wranglers can assign bugs to you. Thank you.

**Comment by jirutka** [comment]
@monsieurp No problem, thank you for merging this!

**Pull request merged**
