### PR TITLE
gnome-base/gnome-shell: add cap_sys_nice capability for gnome-shell

### PR DESCRIPTION
**Pull request by nibon7**
Signed-off-by: nibon7 <nibon7@163.com>

### CODE REVIEW

**Comment by mattst88** [comment]
Thank you!

Could you set your real name in git with `git config --global user.name "..."`? We prefer submissions to have a real name attached to them.

**Comment by mattst88** [comment]
I'm trying to find more information about this feature. I've found

https://discourse.gnome.org/t/the-experimental-rt-scheduler-feature-of-mutter-gnome-shell-3-34/2515
https://bugs.archlinux.org/task/64204

so far. If you can explain or give more links, that would be good.

**Comment by nibon7** [comment]
`rt-scheduler` feature works only if  `CAP_SYS_NICE` is set for unprivileged user.

https://gitlab.gnome.org/GNOME/mutter/-/commit/dae2c1d420ed272710ac55b7a00f6787e5c0e762

**Comment by mattst88** [comment]
Looks like this was superseded by https://gitlab.gnome.org/GNOME/mutter/-/merge_requests/2060 which is in v42.0.

**Pull request closed without merging**
