### PR TITLE
net-im/synapse: add 1.63.1

### PR DESCRIPTION
**Pull request by arkamar**
New version with optional support for `postgres` and `systemd`.

### CODE REVIEW

**Comment by 0xC0ncord** [comment]
1.63.1 was just released: https://github.com/matrix-org/synapse/releases/tag/v1.63.1

**Comment by arkamar** [comment]
Bug fix version was just relased https://github.com/matrix-org/synapse/releases/tag/v1.63.1, I'll change this PR to this version soon.

**Comment by arkamar** [comment]
Done, PR updated with `1.63.1` version.

**Comment by arkamar** [comment]
FP with rebase in order to reflect recent `~ppc64` keywording, see commit bfa88d24584c - `net-im/synapse: Keyword 1.62.0 ppc64, #859412`

**Pull request closed without merging**
