### PR TITLE
x11-plugins/wmmp3: Fix  implicit declaration of function malloc

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/882321

### CODE REVIEW

**Comment by voyageur** [comment]
Looks good, pulling it in

Time permitting, can you also send it upstream? https://www.windowmaker.org/dev/

**Comment by listout** [comment]
Sure why not, I'll try to.

**Comment by listout** [comment]
This is the upstream I'm guessing, https://repo.or.cz/dockapps.git/tree/HEAD:/wmmp3.
How do I send in a patch or a PR?

**Comment by voyageur** [comment]
> This is the upstream I'm guessing, https://repo.or.cz/dockapps.git/tree/HEAD:/wmmp3. How do I send in a patch or a PR? Or do send it in via https://github.com/window-maker/dockapps?
Indeed the main code is hosted at https://repo.or.cz/dockapps (it is one repository for all dockapps, thse x11-plugins/wm*), and "patches should be submitted to wmaker-dev@googlegroups.com using git send-email"

**Comment by listout** [comment]
For note, I've send the patch upstream today. Waiting for feedback from them.

**Pull request closed without merging**
