### PR TITLE
haskell: keyword mjo packages ~ppc64

### PR DESCRIPTION
**Pull request by matoro**
`net-mail/list-remote-forwards` and `net-misc/hath` have `-optc-O3 -optc-march=native` hardcoded in their cabal files.  Strip out with sed for now.

CC @orlitzky

### CODE REVIEW

**Comment by orlitzky** [comment]
Thanks, I've fixed these in git and will make new releases ASAP. Somewhere along the line I started moving my personal ghc-options into the `makefile` (that only I use), but apparently I forgot to go back and update a few older ones.

**Comment by matoro** [comment]
> Thanks, I've fixed these in git and will make new releases ASAP. Somewhere along the line I started moving my personal ghc-options into the `makefile` (that only I use), but apparently I forgot to go back and update a few older ones.

Thank you!  Could you go ahead and approve + merge this then?

**Comment by orlitzky** [comment]
Can you add `Signed-off-by:` tags to the commits? Otherwise LGTM.

**Comment by orlitzky** [comment]
New versions of list-remote-forwards and hath are on hackage if you want to bump the versions now instead of `sed`. Otherwise I don't mind doing it.

**Comment by matoro** [comment]
@orlitzky I was instructed by @thesamesam not to signoff commits anymore since I'm unable to use my realname.

**Comment by orlitzky** [comment]
Oh, ok. In this case I can pretty easily tell that everything is kosher and just add my own signoff, so long as the overlords don't mind (Sam?)

**Comment by matoro** [comment]
> Oh, ok. In this case I can pretty easily tell that everything is kosher and just add my own signoff, so long as the overlords don't mind (Sam?)

Sam's been doing this on my PRs for a while since I got those instructions, see e.g.: https://github.com/gentoo/gentoo/pull/26876

So it should be fine.

**Comment by orlitzky** [comment]
> Sam's been doing this on my PRs for a while since I got those instructions, see e.g.: #26876
> 
> So it should be fine.

I had assumed it was part of our policy, but I re-read the GLEP carefully and I think it's fine if I sign off. Thanks again. I bumped hath and list-remote-forwards so the `sed`s are gone.

**Comment by matoro** [comment]
> > Sam's been doing this on my PRs for a while since I got those instructions, see e.g.: #26876
> > So it should be fine.
> 
> I had assumed it was part of our policy, but I re-read the GLEP carefully and I think it's fine if I sign off. Thanks again. I bumped hath and list-remote-forwards so the `sed`s are gone.

Thanks, I started keywording work but I am getting test failures for =net-mail/list-remote-forwards-0.0.3:

```
 * >>> Test phase [cabal test]: net-mail/list-remote-forwards-0.0.3
./setup test --show-details=streaming
Running 2 test suites...
Test suite testsuite: RUNNING...
All tests
  Report Tests
    all remote forwards are found:                               OK (0.01s)
    dropby_mxlist affects the "address" and not the "goto:       OK
    dropby_mxlist only performs comparisons on normalized names: OK
    dropby_mxlist requires all mx to be in the exclude list:     OK

All 4 tests passed (0.02s)
Test suite testsuite: PASS
Test suite logged to: dist/test/list-remote-forwards-0.0.3-testsuite.log
Test suite doctests: RUNNING...

src/DNS.hs:14:1: error:
    Ambiguous module name ‘Network.DNS’:
      it was found in multiple packages: dns-4.0.1 resolv-0.1.2.0
src/Main.hs:33: failure in expression `let default_cfg = def :: Configuration'
expected:
 but got:
          ^
          <interactive>:27:26: error:
              Not in scope: type constructor or class ‘Configuration’

src/String.hs:12: failure in expression `trim "\thello"'
expected: "hello"
 but got:
          ^
          <interactive>:33:1: error:
              Variable not in scope: trim :: String -> t

src/Report.hs:130: failure in expression `import Forward ( fwd )'
expected:
 but got:
          ^
          <no location info>: error:
              Could not find module ‘Forward’
              It is not a module in the current program, or in any known package.

src/Forward.hs:51: failure in expression `pretty_print $ fwd "user1@example.com" "user2@example.net"'
expected: "user1@example.com -> user2@example.net"
 but got:
          ^
          <interactive>:45:1: error:
              Variable not in scope: pretty_print :: t0 -> t

          <interactive>:45:16: error:
              Variable not in scope: fwd :: String -> String -> t0

src/Forward.hs:62: failure in expression `pretty_print (fwd "a@example.com" "b@example.net")'
expected: "a@example.com -> b@example.net"
 but got:
          ^
          <interactive>:51:1: error:
              Variable not in scope: pretty_print :: t0 -> t

          <interactive>:51:15: error:
              Variable not in scope: fwd :: String -> String -> t0

src/Forward.hs:85: failure in expression `strings_to_forwards [addr, gotos]'
expected: [Forward (Address "a@b.test") (Goto "a@b.test")]
 but got:
          ^
          <interactive>:61:1: error:
              Variable not in scope: strings_to_forwards :: [String] -> t

src/Forward.hs:124: failure in expression `let f = fwd "user1@example.com" "user2@example.net"'
expected:
 but got:
          ^
          <interactive>:67:9: error:
              Variable not in scope: fwd :: String -> String -> t

src/Forward.hs:158: failure in expression `let f = fwd "user1@example.com" "user2@example.net"'
expected:
 but got:
          ^
          <interactive>:73:9: error:
              Variable not in scope: fwd :: String -> String -> t

src/Forward.hs:196: failure in expression `domain_part "user2@example.net"'
expected: Just "example.net"
 but got:
          ^
          <interactive>:79:1: error:
              Variable not in scope: domain_part :: String -> t

src/Forward.hs:229: failure in expression `let ds = map normalize_string ["example.com", "example.net"]'
expected:
 but got:
          ^
          <interactive>:85:14: error:
              Variable not in scope: normalize_string :: String -> b

src/DNS.hs:54: failure in expression `normalize_string "ExAMplE.com"'
expected: NormalDomain "example.com."
 but got:
          ^
          <interactive>:91:1: error:
              Variable not in scope: normalize_string :: String -> t

Examples: 61  Tried: 13  Errors: 0  Failures: 11
Test suite doctests: FAIL
Test suite logged to: dist/test/list-remote-forwards-0.0.3-doctests.log
1 of 2 test suites (1 of 2 test cases) passed.
```

**Comment by orlitzky** [comment]
> 
> Thanks, I started keywording work but I am getting test failures for =net-mail/list-remote-forwards-0.0.3:
> 

This looks like a more general problem with the doctest runner: https://github.com/sol/doctest/issues/119

I'll think about it in the morning.. if I can't come up with a solution I'll just restrict the tests.

**Comment by matoro** [comment]
> > Thanks, I started keywording work but I am getting test failures for =net-mail/list-remote-forwards-0.0.3:
> 
> This looks like a more general problem with the doctest runner: [sol/doctest#119](https://github.com/sol/doctest/issues/119)
> 
> I'll think about it in the morning.. if I can't come up with a solution I'll just restrict the tests.

Thanks.  I think there are already packages in tree that restrict tests for this exact reason - see dev-haskell/http-date.  I guess the reason I didn't hit this when keywording ppc64 is because I must have already depcleaned all the old work already.

**Comment by orlitzky** [comment]
I've just restricted them for now and will watch the upstream issue.

**Pull request closed without merging**
