### PR TITLE
www-apps/hugo: add 0.128.2

### PR DESCRIPTION
**Pull request by tastytea**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by Jamim — APPROVED** [review]

**Comment by eli-schwartz** [comment]
I tried to test this:

```
--- PASS: TestPagesFromGoTmplEditPartial (0.07s)
--- PASS: TestPagesFromGoTmplEditGoTmpl (0.05s)
FAIL
FAIL    github.com/gohugoio/hugo/hugolib/pagesfromdata  0.986s
=== RUN   TestCompileSegments
=== RUN   TestCompileSegments/excludes
=== RUN   TestCompileSegments/includes
=== RUN   TestCompileSegments/includes_variant1
    segments_test.go:75: 
--- PASS: TestCompileSegments (0.00s)
```

```
=== RUN   TestCheckChange
--- PASS: TestCheckChange (0.00s)
PASS
ok      github.com/gohugoio/hugo/watcher/filenotify     0.307s
FAIL
 * ERROR: www-apps/hugo-0.128.1::gentoo failed (test phase):
```

(I also got an error due to pandoc and asciidoctor being missing, but that's part of package.use.stable.mask at the moment so no worries...)

Any idea where these errors come from?

**Comment by tastytea** [comment]
> Any idea where these errors come from?

do you have the full log? if not, please retest with 0.128.2 that i'm about to push here.

**Comment by eli-schwartz** [comment]
[build.log.gz](https://github.com/user-attachments/files/16104754/build.log.gz)

**Comment by tastytea** [comment]
i can't reproduce it. i'm inclined to attribute it to the missing dependencies.

**Comment by eli-schwartz** [comment]
> i can't reproduce it. i'm inclined to attribute it to the missing dependencies.

I agree, it's the same error with .2 anyway.

**Comment by eli-schwartz** [comment]
... update. I retested this after installing asciidoctor, but NOT pandoc. Asciidoctor is ruby so kind of gross, but it isn't the nightmare that haskell is.

It passed all tests. Maybe pandoc isn't needed at all? Does that mean we can remove the package.use.stable.mask preventing running the test phase by default?

**Comment by tastytea** [comment]
> Maybe pandoc isn't needed at all?

when pandoc isn't found the tests are skipped

> ruby so kind of gross, but it isn't the nightmare that haskell is.

there is app-text/pandoc-bin by the way 😉

**Comment by eli-schwartz** [comment]
> when pandoc isn't found the tests are skipped

Personally, this seems preferable to having it in package.use.stable.mask.

> there is app-text/pandoc-bin by the way 😉

Not for `~riscv ~x86` which hugo and pandoc possess. Also not for ~loong, which hugo possesses and which isn't available for *any* build of pandoc.

If it can already skip the tests smartly, that seems convenient.

...

Maybe we could add a dedicated USE flag for testing pandoc support, and enable it by default but update the loong / use.stable masks to just mask "test-pandoc"?

**Comment by tastytea** [comment]
> Maybe we could add a dedicated USE flag for testing pandoc support, and enable it by default

that's [what i did before](https://github.com/gentoo/gentoo/pull/24812), it was not well received so i [removed it](https://github.com/gentoo/gentoo/pull/25811) as soon as possible.

i could re-add it, or maybe make the dependency conditionial on the arches that have a pandoc-bin package and emit optfeature for others?

> but update the loong / use.stable masks to just mask "test-pandoc"?

it's masked because [all the haskell dependencies would have to be stabilized](https://bugs.gentoo.org/921501#c8) otherwise, so it has to stay masked everywhere.

**Comment by eli-schwartz** [comment]
> that's [what i did before](https://github.com/gentoo/gentoo/pull/24812), it was not well received so i [removed it](https://github.com/gentoo/gentoo/pull/25811) as soon as possible.

When you removed it, you removed it by switching to virtual/pandoc which simply enables pandoc-bin support, and as I said I regard that as a very incomplete solution since the bin package is only available in a few places.

Anyways, it looks to me like it was received okay, I'd love to hear additional insight from @juippis.

**Comment by juippis** [comment]
Do you have an idea how many tests are skipped due to pandoc missing? Hugo seems to run thousands of tests so missing a handful shouldn't hurt at all. We can of course utilize profile masks on different arches to block testing altogether - hugo is stabilized only on amd64.

What's the best solution? I'd be fine to just print a message saying some tests are/were skipped due to missing pandoc dependency, and keep the virtual and use.mask on amd64 as they are. Although with the virtual, I believe we can drop the use.mask too.

**Comment by tastytea** [comment]
> Do you have an idea how many tests are skipped due to pandoc missing? Hugo seems to run thousands of tests so missing a handful shouldn't hurt at all.

it seems to be just the one in `markup/pandoc/convert_test.go` that asserts that pandoc is present and working. i believe we can do without that one 😊

> We can of course utilize profile masks on different arches to block testing altogether - hugo is stabilized only on amd64.
> 
> What's the best solution? I'd be fine to just print a message saying some tests are/were skipped due to missing pandoc dependency, and keep the virtual and use.mask on amd64 as they are. Although with the virtual, I believe we can drop the use.mask too.

isn't the use.mask there so we don't have to stabilize all the haskell deps? 🤔

since it's just the one test, i think we should drop the dependency

**Review by juippis — APPROVED** [review]
Works for me. I'll add some nonfatal elog text to inform the user in `src_test` if they're missing pandoc.

**Comment by tastytea** [comment]
thank you! 💖

**Comment by eli-schwartz** [comment]
@juippis should we also remove the profile mask now? :)

**Comment by juippis** [comment]
We probably can't until the old stable ebuilds are cleaned.

**Comment by eli-schwartz** [comment]
It does make it a bit awkward to test a new stable... and the existing (amd64) mask isn't about having a valid dependency graph, since pandoc is valid on amd64 stable, just painful.

The loong mask can't be cleaned up because it's enforcing the dependency graph, indeed. Although it could be switched to a `<` mask.

**Pull request closed without merging**
