### PR TITLE
media-fonts/Humor-Sans: Use a less cryptic src_unpack, add ~x86 to ke…

### PR DESCRIPTION
**Pull request by bjacquin**
…ywords

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by hasufell** [comment]
why is there a changelog?

**Comment by bjacquin** [comment]
There is none now.

**Comment by mgorny** [comment]
As you can see, the ocmmit message is too long and gets split randomly. This also asks for two commits instead of one.

**Comment by bjacquin** [comment]
Splitted in two commits as requested

**Pull request merged**
