### PR TITLE
gui-apps/slurp: add version 1.3.2

### PR DESCRIPTION
**Pull request by tobiasjakobi**
Bug tracker entry for reference: https://bugs.gentoo.org/771966

This is the 1.2.0 ebuild with some minor modifications.
- I changed the keywords to ~x86 and ~amd64 as I can't test on arm64 system
- added missing libxkbcommon dependency (verified by inspecting the meson.build of the project)

Build and runtime check done. Compilation was done with LTO and without.

### CODE REVIEW

**Comment by tobiasjakobi** [comment]
Just added the Bug tag and my Signed-off-by.

**Comment by tobiasjakobi** [comment]
Added the distfile to the Manifest

**Comment by yamabiiko** [comment]
Maybe we should add [please reassign] to the pull title to force it? The maintainer does not seem active to me

**Comment by tobiasjakobi** [comment]
> Maybe we should add [please reassign] to the pull title to force it? The maintainer does not seem active to me

I already did this once, but apparantly that only triggered the rescan. So I should add the suffix again?

**Comment by yamabiiko** [comment]
I don't know, but it seems it needs a new maintainer. If you feel confident and have time for it, you could add yourself as co-maintainer to the Manifest file according to  [wiki](https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Taking_over_an_existing_package). Otherwise I could try to do it too

**Comment by tobiasjakobi** [comment]
@yamabiiko I'm not sure I'm really qualified for that. My knowledge about ebuild is very superficial. And time is another thing...

**Pull request closed without merging**
