### PR TITLE
mongodb: bump to 3.0.15/3.2.15/3.4.6

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested on amd64

### CODE REVIEW

**Comment by hydrapolic** [comment]
@ultrabug

**Comment by ultrabug** [comment]
I would like to stop 3.0 maintenance please.

Would you instead bump 3.4.6 please ? :)

**Comment by hydrapolic** [comment]
Our current primary database is on 3.0 and right now we're setting up a new cluster on 3.2. Then I'll move to 3.4 :) Version 3.4.6 seems to fail, need to further test it...

AttributeError: 'SConfBase' object has no attribute 'CheckBoostMinVersion':
  File "/var/tmp/portage/dev-db/mongodb-3.4.6/work/mongodb-src-r3.4.6/SConstruct", line 2921:
    env = doConfigure( env )
  File "/var/tmp/portage/dev-db/mongodb-3.4.6/work/mongodb-src-r3.4.6/SConstruct", line 2801:
    if not conf.CheckBoostMinVersion():

**Comment by hydrapolic** [comment]
After removing the code that should check for boost (we do that in the ebuild anyway), it compiles on amd64 and ~amd64.

**Comment by ultrabug** [comment]
```
Generating placeholder library build/opt/third_party/s2/util/math/libmath.a
Skipping ranlib for build/opt/third_party/s2/util/math/libmath.a
Linking build/opt/mongo/mongo
build/opt/mongo/client/mongo_uri.o:mongo_uri.cpp:function __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106300::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106300::re_set_long<unsigned int> const*, boost::re_detail_106300::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool): error: undefined reference to 'boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform_primary[abi:cxx11](char const*, char const*) const'
build/opt/mongo/client/mongo_uri.o:mongo_uri.cpp:function __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > > boost::re_detail_106300::re_is_set_member<__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, char, boost::regex_traits<char, boost::cpp_regex_traits<char> >, unsigned int>(__gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, __gnu_cxx::__normal_iterator<char const*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >, boost::re_detail_106300::re_set_long<unsigned int> const*, boost::re_detail_106300::regex_data<char, boost::regex_traits<char, boost::cpp_regex_traits<char> > > const&, bool): error: undefined reference to 'boost::re_detail_106300::cpp_regex_traits_implementation<char>::transform[abi:cxx11](char const*, char const*) const'
collect2: error: ld returned 1 exit status
scons: *** [build/opt/mongo/mongo] Error 1
scons: building terminated because of errors.
build/opt/mongo/mongo failed: Error 1
```

3.4.6 still failing here @hydrapolic, not you ?

**Comment by hydrapolic** [comment]
Worked on my box when I posted those ebuilds.

Don't you need to rebuild boost after gcc upgrade?

**Comment by ultrabug** [comment]
hmm good catch @hydrapolic , I guess the boost ebuild could use a fixup then... anyway it compiles good now. Thanks a lot :)

**Comment by hydrapolic** [comment]
Great,thanks :)

**Pull request closed without merging**
