### PR TITLE
app-portage/g-cpan: fixes & improvements

### PR DESCRIPTION
**Pull request by bor**

### CODE REVIEW

**Comment by bor** [comment]
Note: I'm not sure but seems like `diropts -m0775 -o portage -g portage` not works correctly

```
$ rm -rf /var/tmp/g-cpan /var/log/g-cpan
$ emerge -1v g-cpan
$ # ll -d /var/tmp/g-cpan /var/log/g-cpan
drwxrwxr-x 2 root root 4096 Apr 27 16:01 /var/log/g-cpan
drwxrwxr-x 2 root root 4096 Apr 27 16:01 /var/tmp/g-cpan

**Comment by monsieurp** [comment]
@gentoo/perl @kentfredric

**Comment by kentfredric** [comment]
I see nothing to object to.

**Comment by bor** [comment]
Guys, could you please test it. Especially diropts behaviour (see my comment above).
Is it works for you?

Any ideas why not? Is it may not work due to sticky bit on `/var/tmp`?

**Comment by akhuettel** [comment]
All added.

**Comment by akhuettel** [comment]
No idea about the diropts, will ask in #gentoo-portage

**Pull request closed without merging**
