### PR TITLE
dev-lang/haxe: Build haxe without stripping debugging symbols

### PR DESCRIPTION
**Pull request by MagelessMayhem**
Signed-off-by: MagelessMayhem <107271276+MagelessMayhem@users.noreply.github.com>

### CODE REVIEW

**Comment by MagelessMayhem** [comment]
The Haxe ebuild in its current state breaks its own library manager, haxelib. This is due to Haxe's building process, where it strips its own binaries prior to installation.

This small but important fix restores the functionality of haxelib and allows Haxe programmers to finally install libraries.

**Comment by xgqt** [comment]
@MagelessMayhem Please, modify the signoff according to GLEP 76, see: https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Comment by xgqt** [comment]
> @MagelessMayhem Please, modify the signoff according to GLEP 76, see: https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

@MagelessMayhem So basically use a real name nad e-mail. :-)

**Comment by MagelessMayhem** [comment]
That should do it.

**Comment by xgqt** [comment]
> That should do it.

Yes, thanks.

**Comment by thesamesam** [comment]
This need a new revision as it affects installed files.

**Comment by xgqt** [comment]
> This need a new revision as it affects installed files, btw

right, missed that

**Pull request closed without merging**
