### PR TITLE
app-i18n/ibus: Version bump to 1.5.29_rc1

### PR DESCRIPTION
**Pull request by mattst88**
I was hoping that this release would be smooth since I fixed the awful automake usage that broke parallel builds (https://github.com/ibus/ibus/pull/2523) and fixed undefined behavior that caused the build to fail on sparc (https://github.com/ibus/ibus/pull/2520)

Bug unfortunately more problems have been introduced. Current issues I'm aware of:

- https://github.com/ibus/ibus/issues/2542
- https://github.com/ibus/ibus/issues/2543
- https://github.com/ibus/ibus/issues/2544

I do not intend to push this. Just hoping for some review. The diff from 1.5.28 (not -r1, which has a bunch of upstream patches applied) to 1.5.29 is:

```diff
--- ibus-1.5.28.ebuild  2023-03-30 18:09:30.995741150 -0400
+++ ibus-1.5.29_beta1.ebuild    2023-07-28 16:08:44.775964519 -0400
@@ -1,19 +1,20 @@
 # Copyright 1999-2023 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
+EAPI=8
 
-PYTHON_COMPAT=( python3_{9..11} )
+PYTHON_COMPAT=( python3_{10..12} )
 
 inherit autotools bash-completion-r1 gnome2-utils python-r1 toolchain-funcs vala virtualx xdg-utils
 
-GENTOO_VER=
 DESCRIPTION="Intelligent Input Bus for Linux / Unix OS"
 HOMEPAGE="https://github.com/ibus/ibus/wiki"
 
+MY_PV=$(ver_rs 3 '-')
+GENTOO_VER=
 [[ -n ${GENTOO_VER} ]] && \
        GENTOO_PATCHSET_URI="https://dev.gentoo.org/~dlan/distfiles/${P}-gentoo-patches-${GENTOO_VER}.tar.xz"
-SRC_URI="https://github.com/${PN}/${PN}/releases/download/${PV}/${P}.tar.gz
+SRC_URI="https://github.com/${PN}/${PN}/releases/download/${MY_PV}/${PN}-${MY_PV}.tar.gz
        ${GENTOO_PATCHSET_URI}"
 
 LICENSE="LGPL-2.1"
@@ -41,6 +42,7 @@
                x11-libs/libX11
                >=x11-libs/libXfixes-6.0.0
        )
+       appindicator? ( dev-libs/libdbusmenu[gtk3?] )
        gtk2? ( x11-libs/gtk+:2 )
        gtk3? ( x11-libs/gtk+:3 )
        gtk4? ( gui-libs/gtk:4 )
@@ -79,8 +81,10 @@
        test? ( x11-apps/setxkbmap )
        unicode? ( app-i18n/unicode-data )"
 
+S=${WORKDIR}/${PN}-${MY_PV}
+
 src_prepare() {
-       vala_src_prepare --ignore-use
+       vala_setup --ignore-use
        if ! has_version 'x11-libs/gtk+:3[wayland]'; then
                touch ui/gtk3/panelbinding.vala \
                        ui/gtk3/panel.vala \
```

### CODE REVIEW

**Comment by mattst88** [comment]
@gentoo/cjk

**Comment by dlan17** [comment]
hi @mattst88 , the change looks good to me, but as this is beta release, I'd personally not like to push to official portage tree, unless you do have explicit reason?

please notice beta2 released, if you want to push

**Comment by mattst88** [comment]
Thanks for taking a look.

Like I said, I'm not intending to push this. Just hoping to get some testing and review before the final release :)

**Comment by mattst88** [comment]
Thanks for the heads up about beta2. I gave it a try and... it doesn't work /o\

I've filed https://github.com/ibus/ibus/issues/2556

**Comment by mattst88** [comment]
Okay, we finally have a version that builds and passes the test suite...

**Pull request merged**
