### PR TITLE
dev-java/hamcrest-core: SRC_URI (Slot 1.3) + EAPI 7

### PR DESCRIPTION
**Pull request by vaukai**
SRC_URI was from googlecode.com

https://bugs.gentoo.org/642534 still unsolved

Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
@vaukai here's [hamcrest-core-1.3-java-11.patch.zip](https://github.com/gentoo/gentoo/files/6163121/hamcrest-core-1.3-java-11.patch.zip) for fixing compilation of hamcrest-core-1.3 with jdk 11. please make it part of this pr and remove the jdk restriction. i don't know whether 1.1 is affected too or not but if so, the fix might be the same or very similar.

**Comment by vaukai** [comment]
> @vaukai here's [hamcrest-core-1.3-java-11.patch.zip](https://github.com/gentoo/gentoo/files/6163121/hamcrest-core-1.3-java-11.patch.zip) for fixing compilation of hamcrest-core-1.3 with jdk 11. please make it part of this pr and remove the jdk restriction. i don't know whether 1.1 is affected too or not but if so, the fix might be the same or very similar.

Will do that next.  Just fixed https://bugs.gentoo.org/642534.

**Comment by vaukai** [comment]
> ... don't know whether 1.1 is affected too

It is.  Let me keep that for later

**Comment by vaukai** [comment]
> @vaukai here's [hamcrest-core-1.3-java-11.patch.zip](https://github.com/gentoo/gentoo/files/6163121/hamcrest-core-1.3-java-11.patch.zip) for fixing compilation of hamcrest-core-1.3 with jdk 11. please make it part of this pr and remove the jdk restriction. i don't know whether 1.1 is affected too or not but if so, the fix might be the same or very similar.

@fordfrog 
hamcrest-core-1.3-r2 compiled with jdk:11 breaks compilation of dev-java/junit-4.13.1
No clue how to fix.

**Comment by fordfrog** [comment]
> @fordfrog
> hamcrest-core-1.3-r2 compiled with jdk:11 breaks compilation of dev-java/junit-4.13.1
> No clue how to fix.

no idea how to break it :-) the change itself doesn't change any api and the generated jar should still be 1.8 bytecode. what error you exactly get?

**Comment by vaukai** [comment]
> > @fordfrog
> > hamcrest-core-1.3-r2 compiled with jdk:11 breaks compilation of dev-java/junit-4.13.1
> > No clue how to fix.
> 
> @vaukai no idea how to break it :-) the change itself doesn't change any api and the generated jar should still be 1.8 bytecode. what error you exactly get?

Log attached to https://bugs.gentoo.org/751379#c5

**Comment by vaukai** [comment]
@fordfrog Hold on. Trouble was caused elsewhere

**Comment by vaukai** [comment]
> @vaukai here's [hamcrest-core-1.3-java-11.patch.zip](https://github.com/gentoo/gentoo/files/6163121/hamcrest-core-1.3-java-11.patch.zip) for fixing compilation of hamcrest-core-1.3 with jdk 11. please make it part of this pr and remove the jdk restriction. i don't know whether 1.1 is affected too or not but if so, the fix might be the same or very similar.

@fordfrog It's not that simple.  Your patch does not apply for hamcrest-core-1.1.
So I had to rework it, see https://dpaste.com/6WZE5US3L.
But then in compile phase it throws an [error: cannot find symbol](https://dpaste.com/62RGV63DS)
Can you help?

**Comment by fordfrog** [comment]
@vaukai can't access dpaste.com atm

**Comment by vaukai** [comment]
@fordfrog 
Finally, after allowing more and more javascripts I was able to upload those files here
[hamcrest-core-1.1-java-11.txt](https://github.com/gentoo/gentoo/files/6170698/hamcrest-core-1.1-java-11.txt)
[build log.txt](https://github.com/gentoo/gentoo/files/6170703/build.log.txt)

**Comment by fordfrog** [comment]
@vaukai looks like you need to add `import java.util.List;` to the imports at the top of the patched file.

**Comment by vaukai** [comment]
> @vaukai looks like you need to add `import java.util.List;` to the imports at the top of the patched file.

Works. Thank you.

[hamcrest-core-1.1.txt](https://github.com/gentoo/gentoo/files/6172157/hamcrest-core-1.1.txt)

Do I have to worry about these?
hamcrest-core/src/main/java/org/hamcrest/Matcher.java:15: warning - Tag @link: reference not found: CoreMatchers
hamcrest-core/src/main/java/org/hamcrest/Matcher.java:17: warning - Tag @see: reference not found: CoreMatchers

**Comment by fordfrog** [comment]
> > @vaukai looks like you need to add `import java.util.List;` to the imports at the top of the patched file.
> 
> Works. Thank you.
> 
> [hamcrest-core-1.1.txt](https://github.com/gentoo/gentoo/files/6172157/hamcrest-core-1.1.txt)
> 
> Do I have to worry about these?
> hamcrest-core/src/main/java/org/hamcrest/Matcher.java:15: warning - Tag @link: reference not found: CoreMatchers
> hamcrest-core/src/main/java/org/hamcrest/Matcher.java:17: warning - Tag @see: reference not found: CoreMatchers

not at all. these are just warnings from javadoc not being able to find the class. and `import` statement for that class would fix it, if that class would be in the package, which afaics is not.

**Comment by vaukai** [comment]
> not at all. these are just warnings from javadoc not being able to find the class. and `import` statement for that class would fix it, if that class would be in the package, which afaics is not.

Well, so I think this PR is ready for your final review. Please ...

**Comment by fordfrog** [comment]
> Will do that next. Just fixed https://bugs.gentoo.org/642534.

@vaukai is this fixed or not? i still have that issue:
```
...
  [javadoc] /var/tmp/portage/dev-java/hamcrest-core-1.3-r2/work/hamcrest-1.3/build/temp/hamcrest-core-1.3-sources.jar.contents/org/hamcrest/Matcher.java:26: error: self-closing element not allowed
  [javadoc]      * <p/>
  [javadoc]        ^
  [javadoc] /var/tmp/portage/dev-java/hamcrest-core-1.3-r2/work/hamcrest-1.3/build/temp/hamcrest-core-1.3-sources.jar.contents/org/hamcrest/CoreMatchers.java:8: error: self-closing element not allowed
  [javadoc]    * <p/>
  [javadoc]      ^
...
```

**Comment by vaukai** [comment]
> @vaukai is this fixed or not? i still have that issue:

Sorry for that.  It's still open (again).  Can be fixed by switching to java-pkg-simple, but then some important very tiny part seems missing.  I am just preparing a separate commit

**Comment by fordfrog** [comment]
@vaukai ok :-) thanks for the work you do! :-)

**Comment by fordfrog** [comment]
@vaukai btw, i think replacing `<p/>` with `<br/>` might solve the issue, but not tested.

**Comment by vaukai** [comment]
> @vaukai ok :-) thanks for the work you do! :-)

Thanks back to you for taking that partly unfinished work.  Will be back soon with more questions

**Comment by vaukai** [comment]
> @vaukai btw, i think replacing `<p/>` with `<br/>` might solve the issue, but not tested.

Switching to java-pkg-simple can also solve it. See https://github.com/gentoo/gentoo/pull/20019
But, that way we're loosing one important tiny part, "CoreMatchers.class" which the java-ant based version 1.3-r1 has.

**Pull request closed without merging**
