### PR TITLE
www-apps/bugzilla: Version bump 4.4.12 & 5.0.3

### PR DESCRIPTION
**Pull request by CraigInches**
https://bugs.gentoo.org/show_bug.cgi?id=583236

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by idella** [comment]
This makes for a huge build. Trying for at least one some cross tester

**Comment by idella** [comment]
these both build and install for me.
Only one thing though on both.
EAPI=5
Everyone will be screaming  at you for 6

**Comment by idella** [comment]
Do you get the test phases to pass ?

**Comment by CraigInches** [comment]
Both went fine with FEATURES="test" but i did only do it with sqllite db, I can run the tests on all use flag combos but it will take while on my dingy little chromebook

**Comment by idella** [comment]
EAPI now bumped

**Pull request closed without merging**
