### PR TITLE
app-emulation/spice: Added dev-python/six build dependency

### PR DESCRIPTION
**Pull request by paraenggu**
Spice requires Six, the Python 2 and 3 compatibility library, otherwise
the build will fail with the following error:

```
[...]
make[4]: Entering directory '/var/tmp/portage/app-emulation/spice-0.12.6/work/spice-0.12.6/spice-common/common'
/usr/bin/python2.7 /usr/lib64/spice-protocol/spice_codegen.py --generate-demarshallers --client --include common/messages.h /usr/lib64/spice-protocol/spice.proto generated_client_demarshallers.c >/dev/null
Traceback (most recent call last):
  File "/usr/lib64/spice-protocol/spice_codegen.py", line 7, in <module>
    from python_modules import spice_parser
  File "/usr/lib64/spice-protocol/python_modules/spice_parser.py", line 1, in <module>
    import six
ImportError: No module named six
Makefile:794: recipe for target 'generated_client_demarshallers.c' failed
make[4]: *** [generated_client_demarshallers.c] Error 1
make[4]: Leaving directory '/var/tmp/portage/app-emulation/spice-0.12.6/work/spice-0.12.6/spice-common/common'
Makefile:445: recipe for target 'all-recursive' failed
make[3]: *** [all-recursive] Error 1
```

### CODE REVIEW

**Comment by idella** [comment]
I have never seen or used python_gen_any_dep before, but when it comes to use of a python-r1 eclass and PYTHON_COMPAT=( python2_7 ), it requires nothing more than 
>=dev-python/pyparsing-1.5.6-r2[${PYTHON_USEDEP}].
Otherwise I woud just commit this since I also belong to the virt herd, or project, or projecterd

**Comment by paraenggu** [comment]
@idella The <code>dev-python/pyparsing</code> via <code>python_gen_any_dep</code> dependency was already present within the ebuild. That's why I've added the  <code>dev-python/six</code> dependency the same way... and the <code>PYTHON_COMPAT</code> is set to two versions <code>( python2_7 python3_4 )</code>.

**Comment by monsieurp** [comment]
@paraenggu OK with your change but it needs a revbump. Can you do it or should I?

**Comment by paraenggu** [comment]
@monsieurp I didn't now what the actual policy is for such pull-requests. I've revbumped the ebuild to 0.12.6-r1

**Comment by monsieurp** [comment]
You are changing the dependency graph by adding new deps. In this case, the ebuild needs revbumping otherwise Portage can't pick them up (the said new deps). That's it. Thank you, I'm going to merge your PR.

**Comment by idella** [comment]
spice-0.12.5-r1.ebuild is what had the single PYTHON_COMPAT=( python2_7 ),
however I cannot see what prevents a simple build dep from going straight into DEPEND

**Pull request merged**
