### PR TITLE
dev-java/jffi: bump to 1.3.6

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

@fordfrog 
Compared (pkgdiff) to `jffi-1.3.6.jar` from [repo1.maven.org](https://mvnrepository.com/artifact/com.github.jnr/jffi/1.3.6), only the `com/kenai/jffi/Version.class` (and some maven stuff) is missing.  Tests not compiling.

### CODE REVIEW

**Comment by fordfrog** [comment]
[jffi.patch](https://github.com/gentoo/gentoo/files/7528939/jffi.patch.txt)
here's the patch that fixes the compilation. there are some failing tests though, most probably because the install phase is not copied from the current ebuild.

**Comment by fordfrog** [comment]
what is the current status?

**Comment by vaukai** [comment]
> what is the current status?

Ready for review, ready to merge ...

**Comment by fordfrog** [comment]
i get one failure during the tests (tried with `openjdk-8`, `openjdk-11` and `openjdk-17`), otherwise it looks really good, well done :-)

```
There was 1 failure:
1) returnDefaultF128HighPrecision(com.kenai.jffi.NumberTest)
java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:87)
	at org.junit.Assert.assertTrue(Assert.java:42)
	at org.junit.Assert.assertTrue(Assert.java:53)
	at com.kenai.jffi.NumberTest.returnF128HighPrecision(NumberTest.java:271)
	at com.kenai.jffi.NumberTest.returnDefaultF128HighPrecision(NumberTest.java:260)
```

**Comment by vaukai** [comment]
> i get one failure during the tests (tried with `openjdk-8`, `openjdk-11` and `openjdk-17`), otherwise it looks really good, well done :-)
> 
> ```
> There was 1 failure:
> 1) returnDefaultF128HighPrecision(com.kenai.jffi.NumberTest)
> java.lang.AssertionError
> 	at org.junit.Assert.fail(Assert.java:87)
> 	at org.junit.Assert.assertTrue(Assert.java:42)
> 	at org.junit.Assert.assertTrue(Assert.java:53)
> 	at com.kenai.jffi.NumberTest.returnF128HighPrecision(NumberTest.java:271)
> 	at com.kenai.jffi.NumberTest.returnDefaultF128HighPrecision(NumberTest.java:260)
> ```

Sorry, but I cannot reproduce that failure :-(

**Comment by fordfrog** [comment]
@vaukai thanks! that was a tough one :-)

**Pull request closed without merging**
