### PR TITLE
libreoffice: add 5.0.3 pre-release, libwps version bump and update libreoffice-9999 dependency

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by tamiko** [comment]
@akhuettel @scarabeusiv Can you please have a look?

**Comment by mgorny** [comment]
Sorry for throwing this all at you. @akhuettel should help :-P.

**Comment by akhuettel** [comment]
This one got merged already 90%, just that @a17r added a commit on top while I was merging :(

**Comment by a17r** [comment]
@akhuettel sorry, anything I can do about it or better not interfere?

**Comment by akhuettel** [comment]
@a17r nah dont worry. I merged the branch again, the libvisio bump is in. 
About the rest, feel free to implement @mgorny 's suggestions in the live ebuilds. It's actually good that this code gets some more eyes. Let's use a separate PR for it though.

**Comment by mgorny** [comment]
@a17r, yes, please do fix those ugly issues ;-). If you need any help, just ping me.

**Pull request merged**
