### PR TITLE
dev-lang/spidermonkey: mask broken versions, add last working

### PR DESCRIPTION
**Pull request by Miezhiko**
@juippis

### CODE REVIEW

**Comment by juippis** [comment]
Did you figure it out? Both of these versions did build for me and our tinderboxes. There's a bug saying 102.1.0 was a bit incomplete but 102.2.0 should work for everyone. 

I can revert 91.12.0 back if there's a need but would be ideal to solve the issue why 91.13.0 doesn't build.

**Comment by Miezhiko** [comment]
@juippis no need to revert 91.12.0, it fails to build too. 104 builds fine but it will not work with gjs.

not 100% sure what is causing build problems for me but most likely rust 1.63.0
in gentoo it's still being outdated but this spidermonkey should be a blocker if it's really because of rust :(

**Comment by Miezhiko** [comment]
@juippis may you test building those versions with rust 1.63? https://github.com/Miezhiko/Overlay/tree/mawa/dev-lang/rust

**Comment by juippis** [comment]
Well, new rust is no wonder. Always something breaking. You can find a patch for 102esr that should apply to spidermonkey-102 just fine, but they don't plan on fixing it for 91.
https://bugzilla.mozilla.org/show_bug.cgi?id=1783784

Although some 3rd party might, it doesn't look like there's a patch available for 91 just yet.

**Comment by Miezhiko** [comment]
@juippis yes, this is it, you do it or I make Pull Request?

**Comment by juippis** [comment]
Well okay I looked at the "fix" (they just include updated cargo packages) and that's a bit more complicated to implement in ebuilds, since AFAIK you now have to update the checksums for every updated cargo manually. So if that's the case I'd much prefer wait for next versions to drop. Rust-1.63 is not available in Gentoo yet so I'm not too worried about this right now, we'll get new fixed versions in roughly 16 days. If rust gets bumped before that, I guess **I** would just limit the dependency to not accept 1.63 yet.

... but I wonder how many other packages are broken by rust-1.63 and if upstream has some compatibility implementation plan in mind before we get a release in Gentoo.

**Comment by Miezhiko** [comment]
Well I had no problems with other packages since release in Aug. 11, Maybe Gentoo will just never update it, nobody knows.

Next version is 104, it's okay, however current gjs is targetting 91, git sources of gjs is targetting 102, so from that perspective 104 is at the moment useless.

Not sure about checksums, those crates are inlcuded (seems like) in sources and we don't download/verify them separately, so I personally think having patche at least for 102 is good idea.

**Comment by Miezhiko** [comment]
(I can make PR)

**Comment by juippis** [comment]
> 
> Next version is 104, it's okay, however current gjs is targetting 91, git sources of gjs is targetting 102, so from that perspective 104 is at the moment useless.

Spidermonkey upstream also recommends not to use 104, or at least distribute it. That's why we stick to esr releases which they recommend.

> 
> Not sure about checksums, those crates are inlcuded (seems like) in sources and we don't download/verify them separately, so I personally think having patche at least for 102 is good idea.

Yeah, I checked our previous cargo patch, it was taken directly from upstream's Github page and not from Mozilla's hg, that's why it needed a checksum reset. 

But all in all right now I'm not too keen on adding the patch, since Gentoo doesn't have rust-1.63 I have no way to test it, and I'd prefer to wait for an upstream release with complete changeset included. It'd have to be included in Firefox's patch set, then firefox, thunderbird and spidermonkey tested.

**Comment by stefson** [comment]
the rust-1.63 patch will be part of firefox-esr-102.3.0 release, if you for some reason really want the combination of rustc-1.63.0 and spidermonkey-91.13.0 you have to painfully backport the changes to `packed_simd` - in 102+ its `packed_simd2`

so your best bet is to try get 102 working with your gjs version.

**Comment by Miezhiko** [comment]
> the rust-1.63 patch will be part of firefox-esr-102.3.0 release, if you for some reason really want the combination of rustc-1.63.0 and spidermonkey-91.13.0 you have to painfully backport the changes to `packed_simd` - in 102+ its `packed_simd2`
> 
> so your best bet is to try get 102 working with your gjs version.

ye I guess problem is relocating to gnome/desktop team from here.

**Comment by Miezhiko** [comment]
@gyakovlev 

https://gitlab.gnome.org/GNOME/gjs/-/issues/503

easy: mask 1.63 rust
hard: patch older version of spidermonkey

**Comment by rshanule** [comment]
spidermonkey 102 AND 91 are both not compiling on Gentoo ~amd64 with Rust 1.63-r1, as it tries to pull in Rust crate 'packed_simd_2' version 3.7.0. Supposedly version 3.8.0 fixes this, according to some other forums. I tried to change the dependency version myself in the spidermonkey source code but ran into the crate checksums roadblock and settled for the masking solution instead.

Masking Rust 1.63 fixed the problem for now.

**Comment by Miezhiko** [comment]
@rshanule you can use patched version of spidermonkey 102 and pre-3.7 gjs from my overlay https://github.com/Miezhiko/Overlay/commit/b78c1517ca6007c19f1464e1129cbc862ff36e59

**Comment by stefson** [comment]
its possible to patch spidermonkey-91, and fixed up 102.3 is only days away from release. If you can't wait, you can pull the 102 upstream patch in via /etc/portage/patches or use 102.3.0_rc1 

its all in your power

**Comment by juippis** [comment]
I'm just going to disable `rust-simd` from 91 and 102.2 for now. It should allow building with rust-1.63. Testing now...

**Pull request closed without merging**
