### PR TITLE
Death to Java 6!

### PR DESCRIPTION
**Pull request by chewi**
This is my experimental branch to check that I don't break anything when removing Java 6. It includes a commit where I have stabilized Java 8 on ppc64 because this needs to happen first but ppc64 team will be the ones to do this in practise.

### CODE REVIEW

**Comment by mgorny** [comment]
Fixed it for you.

**Comment by ryao** [comment]
I had been under the impression that Java 6 was still supported by Icedtea. Did something change?

**Comment by chewi** [comment]
It is but supporting it is a maintenance burden for us and practically nothing that isn't ancient requires it. To be honest, I'm even considering killing off Java 7 soon after if it isn't too difficult. Things can break unexpectedly when dependencies suddenly start requiring newer Java versions than they did before and the easiest way to avoid this is to support as few versions as possible. Java 9 will make it much easier to emulate older releases when building while still using the latest runtime so from then on, we should be able to cull the older releases almost immediately.

**Comment by monsieurp** [comment]
What James said + don't forget Oracle EOL'd Java 6 as well as 7 a while ago + we've got a slew of CVE reports stacked up in Bugzilla concerning Java 6 on platforms such as PowerPC.

**Comment by chewi** [comment]
Merged.

**Pull request closed without merging**
