### PR TITLE
x11-libs/libva-intel-media-driver: fixed dependency on gmmlib version

### PR DESCRIPTION
**Pull request by Karlson2k**
media-libs/gmmlib-21.3.4 and later break compatibility with old API.

Bug: https://bugs.gentoo.org/829406

No rev-bumps.

### CODE REVIEW

**Comment by thesamesam** [comment]
This (<=) won't cover any revbumps for gmmlib.

**Comment by Karlson2k** [comment]
Corrected to `<media-libs/gmmlib-21.3.4`

**Comment by Karlson2k** [comment]
Related: as gmmlib [changed API and ABI](https://github.com/intel/gmmlib/commit/6143502f4e5275b9d285693704b9cfab04819f78), does it make sense to use slot or subslot for gmmlib?

**Comment by thesamesam** [comment]
> Related: as gmmlib [changed API and ABI](https://github.com/intel/gmmlib/commit/6143502f4e5275b9d285693704b9cfab04819f78), does it make sense to use slot or subslot for gmmlib?

Yeah, existing binaries need to continue working, so we should be using a subslot. Consumers must be revbumped to depend on :=.

We can only use a slot if it's easy to install versions in parallel **and** make consumers use the right version easily (this is usually quite difficult).

**Comment by Karlson2k** [comment]
Added commit with rebuild on libgmm subslot change with revbumps for libva-intel-media-driver.

**Comment by thesamesam** [comment]
Thanks @Karlson2k. Which versions changed API and ABI? We need to add a subslot to the _newer_ one (no need to do it to the older one, as it has an implicit (sub)slot of 0/0).

**Comment by Karlson2k** [comment]
The first version of [gmmlib](https://github.com/intel/gmmlib) with [the new API and ABI](https://github.com/intel/gmmlib/commit/6143502f4e5275b9d285693704b9cfab04819f78) is [21.3.4](https://github.com/intel/gmmlib/tree/intel-gmmlib-21.3.4). Version [22.0.0](https://github.com/intel/gmmlib/tree/intel-gmmlib-22.0.0) has [new API/ABI](https://github.com/intel/gmmlib/blob/intel-gmmlib-22.0.0/Source/GmmLib/CMakeLists.txt#L27) as well.

However, [version 21.3.5](https://github.com/intel/gmmlib/tree/intel-gmmlib-21.3.5) has [old API and ABI](https://github.com/intel/gmmlib/blob/intel-gmmlib-21.3.5/Source/GmmLib/CMakeLists.txt#L27).

Looks like they released 21.3.4 version with the new API but then decided to change API only for 22.0.0 versions.
Maybe add ebuild for gmmlib 21.3.5 and drop version 21.3.4 to simplify dependency relations?
Looking at the git history, it's clear that [version 21.3.5 is based on older](https://github.com/intel/gmmlib/commits/intel-gmmlib-21.3.5) commit than [version 21.3.4](https://github.com/intel/gmmlib/commits/intel-gmmlib-21.3.4)

**Comment by Karlson2k** [comment]
I would add gmmlib version `21.3.5` as `21.3.3-21.3.5` or simply as `21.3.3-5`, because version 21.3.5 should go before version 21.3.4.

**Comment by thesamesam** [comment]
> I would add gmmlib version `21.3.5` as `21.3.3-21.3.5` or simply as `21.3.3-5`, because version 21.3.5 should go before version 21.3.4.

21.3.3_p5? :/

**Comment by Karlson2k** [comment]
@thesamesam I'm on it.

**Pull request closed without merging**
