### PR TITLE
Games cleanup

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@chewi @austin987 This PR removes overshadowed ebuilds, i.e. those that are never strictly required from the view of the package.

**Comment by austin987** [comment]
I won't be able to look until Monday at earliest, but don't let that block you, especially with Chewi's ack

**Comment by austin987** [comment]
LGTM @SoapGentoo

**Comment by SoapGentoo** [comment]
@austin987 thanks, will rebase in a sec

**Pull request closed without merging**
