### PR TITLE
app-admin/fsvs add 1.2.11 update

### PR DESCRIPTION
**Pull request by jmcelroy01**
Supersedes #32432 
Closes: [#912970](https://bugs.gentoo.org/912970)
Signed-off-by: Joseph McElroy gbug.35p6f@simplelogin.fr

### CODE REVIEW

**Comment by thesamesam** [comment]
wrt https://github.com/gentoo/gentoo/pull/32432#issuecomment-1692157353: please don't use the github web UI for this, it's not going to work out well.

You shouldn't be using `git-r3` or `EGIT_REPO_URI` as there's real tarballs available which would fix `VisibleVcsPkg`.

**Comment by jmcelroy01** [comment]
> wrt [#32432 (comment)](https://github.com/gentoo/gentoo/pull/32432#issuecomment-1692157353): please don't use the github web UI for this, it's not going to work out well.
> 
> You shouldn't be using `git-r3` or `EGIT_REPO_URI` as there's real tarballs available which would fix `VisibleVcsPkg`.

Yeah, I knew I'd have to move past using that eventually... Just got the gentoo repo/github setup locally :smiley:  

One note on that - [here](https://devmanual.gentoo.org/ebuild-maintenance/git/index.html#configuration-specific-to-the-gentoo-repository), it says to set `git config --local push.gpgsign 1`. When I tried pushing to one of my branches, it gave me "fatal: the receiving end does not support --signed push". Based on [this](https://github.com/orgs/community/discussions/23515), it seems Github doesn't support gpg signed pushes? It worked once I set it to 0. 

I had tried previously doing without `git-r3` and `EGIT_REPO_URI`, but then I get this: 
```
* ERROR: app-admin/fsvs-1.2.11::gentoo_dev failed (prepare phase):
*   The source directory '/var/tmp/portage/app-admin/fsvs-1.2.11/work/fsvs-1.2.11' doesn't exist
```
which I wasn't sure how else to solve.

**Comment by thesamesam** [comment]
> > wrt [#32432 (comment)](https://github.com/gentoo/gentoo/pull/32432#issuecomment-1692157353): please don't use the github web UI for this, it's not going to work out well.
> > You shouldn't be using `git-r3` or `EGIT_REPO_URI` as there's real tarballs available which would fix `VisibleVcsPkg`.
> 
> Yeah, I knew I'd have to move past using that eventually... Just got the gentoo repo/github setup locally 😃
> 

:)

> One note on that - [here](https://devmanual.gentoo.org/ebuild-maintenance/git/index.html#configuration-specific-to-the-gentoo-repository), it says to set `git config --local push.gpgsign 1`. When I tried pushing to one of my branches, it gave me "fatal: the receiving end does not support --signed push". Based on [this](https://github.com/orgs/community/discussions/23515), it seems Github doesn't support gpg signed pushes? It worked once I set it to 0.
> 

Ah, yeah, you need to disable that part for gh.

> I had tried previously doing without `git-r3` and `EGIT_REPO_URI`, but then I get this:

> 
> ```
> * ERROR: app-admin/fsvs-1.2.11::gentoo_dev failed (prepare phase):
> *   The source directory '/var/tmp/portage/app-admin/fsvs-1.2.11/work/fsvs-1.2.11' doesn't exist
> ```
> 
> which I wasn't sure how else to solve.

Could you run `ls /var/tmp/portage/app-admin/fsvs-1.2.11/work/` so I can see what's in there? Then we can figure out how to set `S` appropriately.

**Comment by jmcelroy01** [comment]
> 
> > I had tried previously doing without `git-r3` and `EGIT_REPO_URI`, but then I get this:
> 
> > ```
> > * ERROR: app-admin/fsvs-1.2.11::gentoo_dev failed (prepare phase):
> > *   The source directory '/var/tmp/portage/app-admin/fsvs-1.2.11/work/fsvs-1.2.11' doesn't exist
> > ```
> >   
> > which I wasn't sure how else to solve.
> 
> Could you run `ls /var/tmp/portage/app-admin/fsvs-1.2.11/work/` so I can see what's in there? Then we can figure out how to set `S` appropriately.

There was an extra fsvs- in there. I had figured it out before, but along with the other things that needed to be removed, and then dropped it after the `EGIT_REPO_URI` stuff worked. 

I think I cleaned up this PR correctly after doing a rebase incorrectly? :sweat_smile:

**Comment by jmcelroy01** [comment]
Based on [this](https://github.com/gentoo/gentoo/pull/28843#issuecomment-1366149236) comment, using `pkgdev commit` instead of `git commit` would fix the no signoff label on future PRs? 

How would I address maintainer-needed?

**Comment by thesamesam** [comment]
> Based on [this](https://github.com/gentoo/gentoo/pull/28843#issuecomment-1366149236) comment, using `pkgdev commit` instead of `git commit` would fix the no signoff label on future PRs?
> 

yes

> How would I address maintainer-needed?

What do you mean by the last bit?

**Pull request closed without merging**
