### PR TITLE
net-im/skypeforlinux - Fix libsecret dependency

### PR DESCRIPTION
**Pull request by oniGino**
libsecret dependency is runtime of underlying chrome engine and isn't actually
used or required by skypeforlinux

Gentoo Bug:
https://bugs.gentoo.org/665606

### CODE REVIEW

**Comment by oniGino** [comment]
I agree just trying to be political here.. its a run time dependency of a library inside one of the pak files..
so technically yes somewhere in the code a libsecret call exists...

**Comment by hsoft** [comment]
So if libsecret is installed on the system, electron is going to call the system library, if it's not, it's going to call the bundled library? Did I understand correctly?

If that's the case, I don't see why we should remove the libsecret dependency of even put if behind a USE flag. In gentoo, we general favor system libs over bundled ones, so if I understand things well, then we should keep the ebuild as-is.

Or do you mean that whether libsecret is installed on the system or not, skypeforlinux is always going to use its bundled library? If that's the case, then we should simply remove the dependency (it's probably not worth the effort to try to patch the app to "unbundle" libsecret).

Or do you mean that it's *linked* somewhere in the bundled library, somewhere, but that there is no actual code path to that call and so the library is never effectively called? Then, same thing, we should drop the dep.

**Comment by oniGino** [comment]
> Or do you mean that it's _linked_ somewhere in the bundled library, somewhere, but that there is no actual code path to that call and so the library is never effectively called? Then, same thing, we should drop the dep.

The last one,  libsecret is not bundled, but chromium the core of electron has a call to use libsecret as a runtime dependency, but its never actually called or used by electron.
But no built in libsecret exists in the package

**Comment by hsoft** [comment]
Oh, that took me a while to get it :) Ok, clear now.

So what would you think of simply removing the dependency?

**Comment by oniGino** [comment]
I'm totally in support of that
, I could see a argument either way which is why i added the use flag when I submitted a bug for net-im/slack
(same problem)

**Comment by hsoft** [comment]
Yay, total agreement! Then please, do, then I'll merge.

**Comment by oniGino** [comment]
@hsoft several new releases for this package exist now, how would you recommend we handle fixing those ebuilds? another PR? or add another commit?

**Comment by hsoft** [comment]
I'm unfamiliar with skypeforlinux, so I don't know for sure. Generally, we don't keep multiple versions around unless there's a good reason to. So unless there's something special with skypeforlinux (protocol compat?) that make users need older versions, the proposed course would be:

1. Modify the PR to include the latest release.
2. Squash those commit together to have only one commit.
3. Add a second commit, to this same PR, that removes old versions.
4. I merge.

**Comment by oniGino** [comment]
Ok Done @hsoft

**Comment by hsoft** [comment]
QA is going to bark at the lack of `--signoff`. Also, your commit name lacks your full name.

**Comment by hsoft** [comment]
Oh, QA didn't bark, probably because the last commit was signed off. But the first two weren't. Next time, please think about signing off all commit.

Also, the commit title format is "cat/pkg: desc", not "cat/pkg - desc". Please, think about this next time.

Thanks for your PR, merged.

**Pull request closed without merging**
