### PR TITLE
app-emulation/playonlinux: version bump to 4.3.4

### PR DESCRIPTION
**Pull request by Kreyren**
Bug: https://bugs.gentoo.org/672944
Added app-misc/jq to RDEPEND which was requested by playonlinux
Signed-off-by: Jacob Hrbek <werifgx@gmail.com>
Package-Manager: Portage-2.3.52, Repoman-2.3.12

### CODE REVIEW

**Comment by Kreyren** [comment]
**NO BUG FOUND**.. FINE!.. EVERYTHING IS FINE! .. FIIINEEE!!!

**Comment by Kreyren** [comment]
Got it.. Qapla'!

**Comment by Amynka** [comment]
Copyright policy violation of the first name.

**Comment by Kreyren** [comment]
Sharing this to prevent gentoo people making me look bad again: https://i.imgur.com/tAFCiFM.png

Will sign with David Kosecky.

**Pull request closed without merging**
