### PR TITLE
sci-misc/boinc : New ebuild sci-misc/boinc-7.6.31.ebuild

### PR DESCRIPTION
**Pull request by Yamakuzure**
Round two in trying to add a new BOINC ebuild.

Changes From first try:

- Hopefully fixed all (but one) issues reported by David Seifert
- Only one ebuild. Adding two wasn't really making sense. I think I was still in my overlay working scheme, where I keep the previous ebuild around.

Issues that remain:

- The new ebuild still uses EAPI=5, because the wxwidgets.eclass does not yet support EAPI=6.

@jlec @SoapGentoo : Justin, David, I do hope I haven't overlooked something this time.
And thank you very much for suggesting repoman to do the commit, I didn't know it could do this. Very helpful indeed!

### CODE REVIEW

**Comment by Yamakuzure** [comment]
Just a note I forgot:

I have no idea why github insist on all three commits. I *think* it has something to do with metadata.xml I updated in the first one implicitly pulling in the second.

If this is going to be a problem, just give the word and I'll merge the three into one with only one change to metadata.xml and one new ebuild.

**Comment by SoapGentoo** [comment]
Thanks Sven, that looks quite good. Have a look at
http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html
how you can merge commits together. Do this, and rebase on latest master.
@jlec please also have a look at it

**Comment by Yamakuzure** [comment]
@SoapGentoo As the PR is not merged, I will close it and squash the commits. It'll surely looks much cleaner, and nothing depends on these commits right now.

**Comment by SoapGentoo** [comment]
@Yamakuzure just for future references: you don't need to close the PR if you wish to update the PR. Just squash the commits, checkout master, pull the latest changes, checkout your branch again and rebase on master.

**Pull request closed without merging**
