### PR TITLE
dev-java/antlr: java21.patch

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
> imo those `public StringTemplate` should be patched to `public org.antlr.stringtemplate.StringTemplate` to avoid the ambiguity.

thanks for the hint. will try it when i get to the tests of this package.

**Comment by fordfrog** [comment]
> not so many bugs left on https://bugs.gentoo.org/showdependencytree.cgi?id=918647&hide_resolved=1 should something else from the [jdk:21 tracker](https://bugs.gentoo.org/showdependencytree.cgi?id=916396&hide_resolved=1) block stabilization?

i should at least find some time to go through them before we decide. i still have some tasks that i wanna finish first, like getting in your bump of tomcat with bnd support.

**Comment by fordfrog** [comment]
this still needs a revbump

**Comment by vaukai** [comment]
> this still needs a revbump

done.

**Pull request closed without merging**
