### PR TITLE
x11-misc/albert: version bump to 0.20.13

### PR DESCRIPTION
**Pull request by CaseOf**
Hello,
New versions of `x11-misc/albert` depends on `dev-qt/qt*:6`.
I did add missing package `dev-qt/qtscxml:6` ebuild.
I did add qt6 packages on `profiles/package.mask`

### CODE REVIEW

**Comment by Chiitoo** [comment]
Since 'qhotkey' isn't coming from code.qt.io, it would probably fit better into a different category, though not sure which.  Maybe 'x11-misc' or 'dev-libs'?

**Comment by CaseOf** [comment]
What's best between the two ?

**Comment by CaseOf** [comment]
Since there’s only libs, I will set `dev-libs/qhotkey`:
```
/usr/lib64/cmake/QHotkey/QHotkeyConfigVersion.cmake
/usr/lib64/cmake/QHotkey/QHotkeyConfig-relwithdebinfo.cmake
/usr/lib64/cmake/QHotkey/QHotkeyConfig.cmake
/usr/lib64/libqhotkey.so.1.5.0
/usr/include/QHotkey
/usr/include/qhotkey.h
/usr/share/doc/qhotkey-1.5.0/README.md.bz2
/usr/lib64/libqhotkey.so.1
/usr/lib64/libqhotkey.so
```

**Comment by CaseOf** [comment]
changes pushed

**Review by juippis — APPROVED** [review]
@gentoo/qt any comments?

**Comment by Chiitoo** [comment]
Fine with me, although I'm about to push Qt 6.5.0 so might want to try with that and go for it instead.

**Comment by CaseOf** [comment]
I did try to build dev-qt/qtbase-6.5.0 but it fails: [build.log](https://github.com/gentoo/gentoo/files/11242537/build.log)
Hence, I can’t actually test it with the new version.

**Comment by CaseOf** [comment]
Apparently, it depends on x11-libs/xcb-util-cursor too, should it be added to dependencies?
Merging this package did solve my issue

**Comment by Chiitoo** [comment]
Yeah, missed that but was notified about it.  I can't build a lot of things on my system right now though, so I'll fix it sometime later if no one else gets to it before that.

**Comment by CaseOf** [comment]
It works fine with 6.5.0 then I updated my commits on this PR

**Review by juippis — APPROVED** [review]
Thanks, especially for rebasing the package.mask file!

**Pull request closed without merging**
