### PR TITLE
media-tv/kodi: depend on media-video/ffmpeg[openssl]

### PR DESCRIPTION
**Pull request by candrews**
https://bugs.gentoo.org/show_bug.cgi?id=625476

### CODE REVIEW

**Comment by anarchpenguin** [comment]
The problem with this is we are working to support libressl as well. I would prefer we not cripple a package that can use both libressl or openssl, it does require ffmpeg to be patched for libressl, but that is already handled in the libressl overlay.

**Comment by candrews** [comment]
I don't think this change would be crippling in any case.

With this change and ffmpeg as-is today, kodi will require media-video/ffmpeg[openssl] always. Since there is no libressl in ffmpeg right now, that will always be the right behavior. If the user wants to use libressl with kodi, they can set the libressl use flag on kodi, but they will always be using openssl (not libressl) in ffmpeg.

With this change and ffmpeg as it is at https://github.com/gentoo/libressl/blob/master/media-video/ffmpeg/ffmpeg-3.3.ebuild , kodi will require media-video/ffmpeg[openssl]. The user can use libressl with kodi and ffmpeg by setting the libressl use flag on both, or they can use libressl on one or the other.

**Comment by anarchpenguin** [comment]
I will go back to maintaiing a local copy of kodi, thanks for the breakage. You can not install libressl and openssl on the same system.

**Comment by candrews** [comment]
@anarchpenguin how about instead of the sarcastic snarky comment, you try to help address the problem?

I suggest we talk to the libressl team seeking to add libressl support to ffmpeg be contacted. Let's see if we can help them.

**Pull request closed without merging**
