### PR TITLE
gnome-base/gnome-shell x11-wm/mutter: Version bump to 42.5

### PR DESCRIPTION
**Pull request by listout**
Signed-off-by: brahmajit das <listout@protonmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
mutter, gnome-shell, and gnome-shell extensions should always be bumped together. Please put them in the same PR. It's difficult to track things if they're dependent by in separate PRs.

**Comment by listout** [comment]
@mattst88 Updated mutter to 42.5 too. Unfortunately, there is no 42.5 release for gnome-shell-extensions :(

**Comment by mattst88** [comment]
Sorry, I might have been unclear when I said
> mutter, gnome-shell, and gnome-shell extensions should always be bumped together. Please put them in the same PR.

Please put them in separate commits, but in the same PR.

**Comment by listout** [comment]
@mattst88 Ping!

Sorry for taking so long. Should be fixed now.

**Pull request closed without merging**
