### PR TITLE
sci-libs/libgeodecomp: add version 0.4.0

### PR DESCRIPTION
**Pull request by shifty91**
Add support for libgeodecomp version 0.4.0.

Signed-off-by: Kurt Kanzenbach <kurt@kmk-computers.de>

### CODE REVIEW

**Comment by a17r** [comment]
Why drop ~ppc?
Please check open bugs next time: https://bugs.gentoo.org/668564

**Comment by shifty91** [comment]
Hi,

On Wed, May 15, 2019 at 08:22:19AM -0700, Andreas Sturmlechner wrote:
> Why drop ~ppc?

I've had no access to ppc hardware to test it.

> Please check open bugs next time: https://bugs.gentoo.org/668564

Will do.

Thanks,
Kurt

**Comment by a17r** [comment]
While true, it is not necessary to drop keywords on regular version bumps unless it is really necessary (new unkeyworded dependencies, big-scale rewrite).

**Comment by shifty91** [comment]
On Wed, May 15, 2019 at 09:54:31AM -0700, Andreas Sturmlechner wrote:
> While true, it is not necessary to drop keywords on regular version
> bumps unless it is really necessary (new unkeyworded dependencies,
> big-scale rewrite).

Okay, noted for the next time.

Thanks,
Kurt

**Comment by a17r** [comment]
In this case it was necessary due to `hpx,silo,visit` dependencies, but it was fixed by masking `sci-libs/libgeodecomp[hpx,silo,visit]` for ppc32. ;)

**Pull request closed without merging**
