### PR TITLE
sys-libs/glibc: replace systemd reexec with a warning

### PR DESCRIPTION
**Pull request by floppym**

### CODE REVIEW

**Comment by mgorny** [comment]
How about warning early in `pkg_pretend`?

**Comment by mattst88** [comment]
I saw some chatter on IRC, but I didn't fully understand. It sounds like there are some cases where it's possible that you're not able to restart systemd, and as a result we shouldn't try because doing so could leave the system in an unusable state?

**Comment by floppym** [comment]
> It sounds like there are some cases where it's possible that you're not able to restart systemd, and as a result we shouldn't try because doing so could leave the system in an unusable state?

Yes, that's essentially what @Whissi is saying.

**Comment by floppym** [comment]
> How about warning early in pkg_pretend?

That sounds reasonable to me, but I would like feedback from the toolchain project before I update the PR.

**Comment by Whissi** [comment]
> How about warning early in `pkg_pretend`?

I would prefer `pkg_postinst`. `pkg_pretend` is happening too early and I believe it won't be visible anymore if user has verbose build enabled.

**Comment by mgorny** [comment]
That's nonsense. The whole purpose of `pkg_pretend` is to make the messages visible while the user is still at the terminal and can make decisions *before* his system enters a broken state.

Also, nothing stops you from warning twice.

**Comment by thesamesam** [comment]
While I like the idea of warning users on glibc major version upgrades, there's two issues here:
- Why isn't it okay to restart systemd in glibc, but it is okay to do it in the systemd ebuilds? When we know something breaks, I'm not yet convinced that inaction is helpful.
- Outside of this bug/PR, we should _explicitly_ formulate whatever policy there is/isn't on touching system daemons within ebuilds. And in any case, a news item is probably warranted for this cycle then?

**Comment by floppym** [comment]
> Why isn't it okay to restart systemd in glibc, but it is okay to do it in the systemd ebuilds?

I have removed the reexec from the systemd ebuilds.

I also updated this PR to emit the warning in pkg_pretend and pkg_postinst.

**Pull request closed without merging**
