### PR TITLE
sys-fs/vhba: add missing linux-mod_pkg_postinst to ebuild

### PR DESCRIPTION
**Pull request by mehw**
Hello,

This PR is to add the missing `linux-mod_pkg_postinst` to `pkg_postinst()` in the ebuild.

Fix updating `/lib/modules/x.x.x-gentoo-custom/modules.dep` file.
```
# diff -Nuar vhba-20211218.ebuild vhba-20211218-r1.ebuild
--- vhba-20211218.ebuild        2023-02-07 22:46:34.794768292 +0000
+++ vhba-20211218-r1.ebuild     2023-02-18 11:44:02.063993793 +0000
@@ -52,6 +52,7 @@
 }
 
 pkg_postinst() {
+       linux-mod_pkg_postinst
        udev_reload
 }

```
Thanks.

### CODE REVIEW

**Comment by mgorny** [comment]
Thank you!

**Comment by mgorny** [comment]
BTW I see you must be running a custom pkgdev version that's based on Portage ;-).

**Comment by mehw** [comment]
@mgorny Thanks for the tip! I'm currently using https://github.com/pkgcore/pkgdev via Gentoo's `dev-util/pkgdev`. Are you aware of other versions?

**Comment by mgorny** [comment]
I was just kidding because of the `Package-Manager` thing you've added to the commit.

**Comment by mehw** [comment]
I'm so gullible... ;)

**Pull request closed without merging**
