### PR TITLE
sys-apps/systemd: Fix DNS-over-TLS, add OpenSSL

### PR DESCRIPTION
**Pull request by lamawithonel**
Since systemd v240, `systemd-resolved(8)` supports opportunistic
DNS-over-TLS, via either GnuTLS or OpenSSL.  Older ebuilds used the
_ssl_ USE flag to enable the GnuTLS build option, however it was
dependent on the _http_ USE flag.  Because of that dependency, it was
impossible to use DNS-over-TLS without also enabling the embedded HTTP
server.  This commit makes it possible to use DNS-over-TLS without the
HTTP server, and gives the user a choice between GnuTLS and OpenSSL.

See also: systemd/systemd@096cbdc
Bug: https://bugs.gentoo.org/674672
Signed-off-by: "Lucas Yamanishi" <lucas.yamanishi@gmail.com>

### CODE REVIEW

**Comment by floppym** [comment]
Please submit this without the revbumps so I can actually see what you changed.

**Comment by floppym** [comment]
I'm not a big fan of that `openssl` USE flag, and the `REQUIRED_USE` constraint that goes with it. I think I will take a different approach to this, but I haven't quite made up my mind.

**Comment by leio** [comment]
If you prefer gnutls, then

```
IUSE="+gnutls libressl ssl"
ssl? (
    gnutls? (  >=net-libs/gnutls-3.5.3 )
    !gnutls? (
        libressl? ( >=dev-libs/libressl:= )
        !libressl? ( >=dev-libs/openssl-1.1.0:= )
    )
)
```

If openssl is preferred, then slightly different, perhaps even IUSE=openssl instead of IUSE=gnutls and things swapped around accordingly.
If libressl is not supported (sounds likely if the dep on openssl >=1.1.0 is correct), then that part removed.
No REQUIRED_USE is used anywhere like this and I believe it to be the preferred way.

I won't see any follow-up comment notifications without IRC pings.

**Comment by lamawithonel** [comment]
I updated the PR with the logic suggested by @leio. I've also restricted the changes to the 9999 ebuild to keep things simple-- and I'm assuming you'll need to create new revision ebuilds anyway.  The diff from *master* will apply cleanly to any of the 240 or 241 series, where they are applicable.

To the question of the OpenSSL version, I haven't tested with other versions, but systemd's Meson build scripts specify that version.  See the `Upstream-bug:` link and the commit that closes the bug.

**Pull request closed without merging**
