### PR TITLE
net-misc/i2pd: adjust systemd .service to point to /usr/bin/i2pd

### PR DESCRIPTION
**Pull request by tomboy-64**
Package-Manager: portage-2.2.26
RepoMan-Options: --ignore-arches

Oversight on my part when updating i2pd.

@klondi 
@blueness 
@gentoo/proxy-maint

### CODE REVIEW

**Comment by tomboy-64** [comment]
Since I did some changes the last few days I added myself to the list of maintainers - in case bugs get filed.
I intend to fix own messes and would like to help keep the package sane. Only if you don't mind, of course.

**Comment by klondi** [comment]
No, no, please feel free to add yourself as a maintainer, if you want I can CC you in the currently open bugs on bugzilla as I don't have that much time lately to focus on i2pd.

**Comment by klondi** [comment]
@blueness The request seems sane enough to me, but I'm not to familiar with systemd units to give a strong opinion.

**Comment by tomboy-64** [comment]
@klondi the systemd file is a simple fix; the location of the i2pd binary apparently changed since 0.10.0 or whatever. but starting the service via systemctl suddenly failed. I don't know why I didn't notice before, since I am using systemd and I used this new version... so yes. the only change is the location of the binary.

**Comment by blueness** [comment]
@klondi i'm pretty much just accepting systemd unit files since I can't test them and I'm assuming they kinda/sorta work for the contributor, and we'll catch any bugs later

@tomboy-64 no problems taking care of this package.  as long as you use it and keep an eye that it works.  ping me when  there are updates.

**Comment by monsieurp** [comment]
Let's merge this PR then, shall we?

**Comment by tomboy-64** [comment]
Good to go. Would you please do the honors, @monsieurp ? :)

**Comment by monsieurp** [comment]
I sure shall.

**Comment by blueness** [comment]
um, i merged this locally and pushed.  why did you remerge?  i always download a patch to test locally before putting it n the tree.

**Comment by monsieurp** [comment]
@blueness are you sure? cause it's not showing up in the git history. I'm in net-misc/i2pd and ran `git log' here's what comes through:
* 61fd919 - net-misc/i2pd: add myself as proxy-maintainer to metadata.xml (3 hours ago) <tomboy64@sina.cn>
* 2acffb0 - net-misc/i2pd: update remote-id in metadata.xml to PurpleI2P/i2pd (3 hours ago) <tomboy64@sina.cn>
* 5c5a332 - net-misc/i2pd: adjust systemd .service to point to /usr/bin/i2pd (3 hours ago) <tomboy64@sina.cn>
* d3b07c1 - (github/pr/790) net-misc/i2pd: remove old versions 0.5 and 0.6 (2 weeks ago) <tomboy64@sina.cn>
* b28f9cd - net-misc/i2pd: remove live version (2 weeks ago) <tomboy64@sina.cn>
* d7f91b1 - net-misc/i2pd: version bump 2.4.0 (2 weeks ago) <tomboy64@sina.cn>
* 8849b09 - Set appropriate maintainer types in metadata.xml (GLEP 67) (4 weeks ago) <mgorny@gentoo.org>
* 20a9a88 - net-misc/i2pd: version bump (5 months ago) <tomboy64@sina.cn>
* 1bfb585 - Revert DOCTYPE SYSTEM https changes in metadata.xml (6 months ago) <floppym@gentoo.org>
* eaaface - Use https by default (6 months ago) <jlec@gentoo.org>
* 56bd759 - proj/gentoo: Initial commit (6 months ago) <robbat2@gentoo.org>

**Comment by blueness** [comment]
the first three are the commits.  it is correct, i check after sync-ing on a different server

**Comment by monsieurp** [comment]
Cleared up on IRC but it's a weird situation we ran into I must say.

**Pull request merged**
