### PR TITLE
net-vpn/vtun: Fix shell script compatibility issue in rc script (bashism).

### PR DESCRIPTION
**Pull request by leakingmemory**
Newline into the separator (IFS) apparently isn't very easy to accomplish. This seems to be the best way of doing that without relying on bash features.

I guess this fixes the last remaining reported bug for net-vpn/vtun at the moment, so hopefully the scheduled removal can be averted?

#849446

### CODE REVIEW

**Comment by thesamesam** [comment]
Nice work, thanks! I'll unmask it.

**Comment by thesamesam** [comment]
Would you like to adopt it?

**Comment by leakingmemory** [comment]
Hi,

Yes, sure, I think this is something I can take on. I'm quite new to writing ebuilds and Gentoo procedures so I'll appreciate greatly some guidance, and obviously thanks to all of you who have done so already. :)

(Btw. sorry if the message got duplicated. It appears replying by email didn't work properly)

**Comment by thesamesam** [comment]
Sounds great! I normally may not encourage someone to do it so early but I think given:
1. vtun was at risk of removal;
2. you managed to fix all the bugs properly
it's no problem.

See https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Proxied_maintainer_in_metadata.xml for how to do it (new PR). Come ask on IRC in #gentoo-proxy-maint or #gentoo-dev-help if get stuck.

**Comment by leakingmemory** [comment]
Added https://bugs.gentoo.org/886595

**Pull request closed without merging**
