### PR TITLE
Bitcoin 0.12

### PR DESCRIPTION
**Pull request by luke-jr**
Major changes:

- New JSON library: UniValue
- libsecp256k1 from 2015-11-18
- Bitcoin ebuilds using Bitcoin Core 0.12 and (with USE=ljr) Knots 0.12.0.knots20160226.rc1
- Adds mk_MK to linguas list
- LibreSSL support (note this *cannot* be safely backported to <0.12)

### CODE REVIEW

**Comment by luke-jr** [comment]
@blueness

**Comment by monsieurp** [comment]
Thank you for the PR: Please format your commit messages: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by blueness** [comment]
@monsieurp luke does a good job maintaining bitcoins even though he doesn't know some of the subtleties of gentoo QA.

@luke-jr i'll fix up these commit messages but it might be a good idea just to take a look at that page.

**Comment by blueness** [comment]
@luke-jr actually the one thing i would change i the future is patch 3.  make each pkg its own commit.  i would also make the profiles/linguas.desc its own commit.

everything should be in the tree now thanks!

**Pull request closed without merging**
