### PR TITLE
app-containers/buildah: add 1.32.1 and update live

### PR DESCRIPTION
**Pull request by rahilarious**
1) split out LICENSE
2) Follow upstream's build process in which non-live versions shouldn't have git commit so GIT_COMMIT is no longer needed
3) Swap DEPEND & RDEPEND to closely follow skel.ebuild 4) In src_prepare, make use of usex to keep it concise and readable, following app-containers/podman style
5) In src_install, changes those help with readablility

### CODE REVIEW

**Comment by zmedico** [comment]
Thanks!

**Comment by rahilarious** [comment]
@zmedico  Is there any reason to add GIT_COMMIT back in ?
 
I checked how upstream handles commit in _releases_ (non-live) versions, turns out they only want git commit to be in live versions[1]
Also checked how other distributions handle it (fedora, debian, arch) no one includes commit in releases. 

1. https://github.com/containers/buildah/blob/main/Makefile#L28

**Comment by zmedico** [comment]
> @zmedico Is there any reason to add GIT_COMMIT back in [be8013d](https://github.com/gentoo/gentoo/commit/be8013d8c9ecb946d19a90c6b39af05411bb0889) ?

I added it for a couple reasons:
1. `buildah version` showed an empty place for it
2. It's common for git commands in Makefile like this to trigger sandbox violations (tracker [bug 558556](https://bugs.gentoo.org/558556)).

> I checked how [upstream](https://github.com/containers/buildah/blob/main/Makefile#L28) handles commit in _releases_ (non-live) versions, turns out they only want git commit to be in live versions Also checked how other distributions handle it (fedora, debian, arch) no one includes commit in releases.

Okay, I'd be happy to omit the commit, but would feel safer if we did something about git sandbox violations. I see a suggestion involving GIT_CEILING_DIRECTORIES here: https://bugs.gentoo.org/558556#c6

**Comment by rahilarious** [comment]
>     1. `buildah version` showed an empty place for it
That's intended behaviour

>     2. It's common for git commands in Makefile like this to trigger sandbox violations (tracker [bug 558556](https://bugs.gentoo.org/558556)).
> 
> Okay, I'd be happy to omit the commit, but would feel safer if we did something about git sandbox violations. I see a suggestion involving GIT_CEILING_DIRECTORIES here: https://bugs.gentoo.org/558556#c6

I don't understand any of this 😅 but if that is causing problems we can export empty COMMIT_NO and GIT_COMMIT for non-live versions

**Comment by zmedico** [comment]
> I don't understand any of this 😅 but if that is causing problems we can export empty COMMIT_NO and GIT_COMMIT for non-live versions

Empty values work for me, since that's enough to prevent make from evaluating the right hand side of `?=`.

Here's an example of the unwanted stuff git does when it can't find a `.git` directory:
```console
$ mkdir -p /tmp/foo/bar
$ strace git -C /tmp/foo/bar git rev-parse HEAD |& grep /tmp
execve("/usr/bin/git", ["git", "-C", "/tmp/foo/bar", "git", "rev-parse", "HEAD"], 0x7fff43c33a38 /* 42 vars */) = 0
chdir("/tmp/foo/bar")                   = 0
getcwd("/tmp/foo/bar", 129)             = 13
stat("/tmp/foo/bar", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/bar/.git", 0x7ffead0d2c00) = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/bar/HEAD", 0x7ffead0d2ac0) = -1 ENOENT (No such file or directory)
stat("/tmp/foo", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/.git", 0x7ffead0d2c00)   = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/HEAD", 0x7ffead0d2ac0)  = -1 ENOENT (No such file or directory)
stat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=131072, ...}) = 0
stat("/tmp/.git", 0x7ffead0d2c00)       = -1 ENOENT (No such file or directory)
lstat("/tmp/HEAD", 0x7ffead0d2ac0)      = -1 ENOENT (No such file or directory)
getcwd("/tmp/foo/bar", 129)             = 13
stat("/tmp/foo/bar", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/bar/.git", 0x7ffead0d2c00) = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/bar/HEAD", 0x7ffead0d2ac0) = -1 ENOENT (No such file or directory)
stat("/tmp/foo", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/.git", 0x7ffead0d2c00)   = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/HEAD", 0x7ffead0d2ac0)  = -1 ENOENT (No such file or directory)
stat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=131072, ...}) = 0
stat("/tmp/.git", 0x7ffead0d2c00)       = -1 ENOENT (No such file or directory)
lstat("/tmp/HEAD", 0x7ffead0d2ac0)      = -1 ENOENT (No such file or directory)
getcwd("/tmp/foo/bar", 129)             = 13
stat("/tmp/foo/bar", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/bar/.git", 0x7ffead0d2ba0) = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/bar/HEAD", 0x7ffead0d2a60) = -1 ENOENT (No such file or directory)
stat("/tmp/foo", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
stat("/tmp/foo/.git", 0x7ffead0d2ba0)   = -1 ENOENT (No such file or directory)
lstat("/tmp/foo/HEAD", 0x7ffead0d2a60)  = -1 ENOENT (No such file or directory)
stat("/tmp", {st_mode=S_IFDIR|S_ISVTX|0777, st_size=131072, ...}) = 0
stat("/tmp/.git", 0x7ffead0d2ba0)       = -1 ENOENT (No such file or directory)
lstat("/tmp/HEAD", 0x7ffead0d2a60)      = -1 ENOENT (No such file or directory)
```

**Comment by rahilarious** [comment]
> Empty values work for me, since that's enough to prevent make from evaluating the right hand side of `?=`.

Done. Checkout https://github.com/gentoo/gentoo/pull/33599/

**Pull request closed without merging**
