### PR TITLE
 games-fps/eduke32: bump to version 20180620.6927

### PR DESCRIPTION
**Pull request by ConiKost**
games-fps/eduke32: bump to version 20180620.6927
`fix-build-transpal.patch` was also merged upstream.

The Duke Nukem 3D Voxels Pack has been also added

Package-Manager: Portage-2.3.40, Repoman-2.3.9

### CODE REVIEW

**Comment by ConiKost** [comment]
@chewi Could you have a look? Thanks!

**Comment by gyakovlev** [comment]
@gentoo/licenses can you please check what's the appropriate licence group here and if it's required?

**Comment by ulm** [comment]
The license already exists as licenses/HRP. Please check for such duplicates before adding a new license.
Also, please don't commit files to the tree that have DOS (CRLF) line endings.

**Comment by ConiKost** [comment]
> The license already exists as licenses/HRP. Please check for such duplicates before adding a new license.

Since, except the title, both licenses are the same, I renamed HRP to Art and changed the title.

> Also, please don't commit files to the tree that have DOS (CRLF) line endings.

Thanks for fixing! :+1:

**Pull request closed without merging**
