### PR TITLE
net-p2p/classified-ads: Fix bug 568874 - use correct qmake version

### PR DESCRIPTION
**Pull request by operatornormal**
Modifies the ebuild so that it uses same version of qmake with test suite
as it used with rest of the software. This includes also fix for bug
563606 where miniupnpc version bump changed its API making classified-ads
to not compile any more.

Reported-By: Michael Palimaka <kensington@gentoo.org>

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by operatornormal** [comment]
Yes. In line 68 the "|| true" is used because it may be normal for this command to fail - if there is no previous database file or if database file creation failed during test suite run, it is necessary to be able to continue. This is actually same reason where "||die" is not used at line 66 because there is still database file cleanup possibly pending.

**Comment by idella** [comment]
@gentoo/proxy-maint 

The proxied maintainer of this package has cited this pull req in bugs 568874 & 563606, thereby endorsing them as accepted fix(es).

**Comment by idella** [comment]
The commit msg is quite verbose, 
Modifies so ebuild so that
looks like an innocent typo, however is trivial. The msg could be reduced to terse and succinct but just make a note of this for future reference, not holding it up over style of msg esp. one can find other verbose style msgs from established devs.

" or if database file creation failed during test suite run, it is necessary to be able to continue"
poses a real problem here. What you're dictating here is that it's acceptable for the  database's file creation to fail, which will make the testsuite a failure or at least badly compromised. This def'ly needs more discussion.
Firstly, is it feasible for the making of the file to fail?
Secondly, you can encapsulate the running of the ./testca in an if then statement and account for $? > 0 within it by use of die and a msg, "this failed in running of testsuite.
Or even if  $? > 0 or if  ! $? then ...... \ fi
Allowing for a test run to fail counters how test phases are expected to run and 'behave' within gentoo.

**Comment by operatornormal** [comment]
Ok commit 6575f8a fixes 2 problems, one is "rm || die" -> "rm -f", another is quotes around $(qt4_get_bindir). 

About other issues mentioned in this thread .. the test suite is not run in sandbox or chroot. The test suite uses real sw parts when possible, including the data storage parts, referring to file "$HOME/.classified_ads/sqlite_db". User should be careful to not lose this file, this is why a backup is created prior to test run. Test suite will create a brand new file, filled with test data - because it is test suite, any test may fail so it may be that at the end of test run will have negative test result and no datafile. Regardless of test results, the original data file needs to be restored to its original place ; this is reason for large number conditions in src_test section and for not having "||die" right after the testca invocation. 

--
Antti

**Comment by floppym** [comment]
> The test suite uses real sw parts when possible, including the data storage parts, referring to file "$HOME/.classified_ads/sqlite_db". User should be careful to not lose this file, this is why a backup is created prior to test run.

In an ebuild context, HOME is always set to a temp directory; there should be no need to backup/restore anything from there.

**Comment by idella** [comment]
On re-reading, and brief discussion, it appears what you have here is a test run that will complete with failures, but then the return value read and will abort via "|| die". Also I believe that could be abbr. to
if ! result; then.
The point re  $HOME raised is valid. Within the sandbox, ${T} is made the location of HOME and ought be coded accordingly. This can easily be observed within the sandbox.
Tomorrow is Christmas, so I suppose the limiting factor here is time available.

**Comment by operatornormal** [comment]
Please have a look at  commit 537312b as it removes backup file-handling and introduces env-variable hanlinǵ.

**Comment by idella** [comment]
irc-client and ncurses have nil to do with this ebuild.
The edits to the testsuite appear to have done all that was pointed out. The removal of backup file-handling was unrequired, and the use of the added variables is effective on run testing. The only thing I have objection to is use of the word 'stolen'.  I will commit as is and I can change this myself post addition. I think the term 'modelled from' reads better all round.

**Pull request merged**
