### PR TITLE
games-util/deutex: version bump to deutex-5.1.2

### PR DESCRIPTION
**Pull request by vilhelmgray**
Closes: https://bugs.gentoo.org/680460
Closes: https://bugs.gentoo.org/687678
Package-Manager: Portage-2.3.67, Repoman-2.3.14
Signed-off-by: William Breathitt Gray <vilhelm.gray@gmail.com>

### CODE REVIEW

**Comment by chewi** [comment]
One small nitpick with this that isn't your fault. The man pages are kinda automagic. Not the end of the world but you can avoid it by doing `ac_cv_prog_ASCIIDOC= econf ...` when the `man` flag is disabled. This could be fixed upstream but I suspect they won't care that much.

**Comment by vilhelmgray** [comment]
> One small nitpick with this that isn't your fault. The man pages are kinda automagic. Not the end of the world but you can avoid it by doing `ac_cv_prog_ASCIIDOC= econf ...` when the `man` flag is disabled.

Do you mean something like this:

    if use man ; then
        econf $(use_with png libpng)
    else
        ac_cv_prog_ASCIIDOC= econf $(use_with png libpng)
    fi

> This could be fixed upstream but I suspect they won't care that much.

The autotools configuration files for this project look very simple, so I might be able to provide a patch myself to resolve this upstream. What behavior do you think would be correct -- I'm not familiar with how other projects handle manpage creation, so should I add a `--with-asciidoc` option or `--enable-manual`, etc.?

**Comment by chewi** [comment]
Yeah like that or shorten it by using `export`.

I agree it would be simple enough. There's no standard option for this but `--enable-man` using `AC_ARG_ENABLE` looks common. Make sure it defaults to the automagic behaviour to keep upstream happy. Ideally abort if it's explicitly enabled but asciidoc is not found.

**Comment by vilhelmgray** [comment]
I've bumped the version to deutex version 5.2.0 which contains the manpage generation selection configuration fix.

**Comment by chewi** [comment]
Wow, patch merged and released already! Nice!

I noticed at the last second that there was no 0 SLOT on libpng so I added that myself. The other SLOTs don't install headers.

**Pull request closed without merging**
