### PR TITLE
app-cdr/cdrtools: Add support for big endian RISC-V

### PR DESCRIPTION
**Pull request by jsmolic**
Closes: https://bugs.gentoo.org/907029

### CODE REVIEW

**Review by billie80 — COMMENTED** [review]
Thanks for your contribution. Could you please base your changes on the newly committed version 3.02_alpha09-r5 then I can use your contribution as is.

**Comment by jsmolic** [comment]
> Thanks for your contribution. Could you please base your changes on the newly committed version 3.02_alpha09-r5 then I can use your contribution as is.

Sure, it's rebased

**Comment by billie80** [comment]
Thanks,  I will add it next year though. 😃

**Comment by jsmolic** [comment]
Would you mind if I push it?

**Comment by billie80** [comment]
No I don't. Go ahead!

**Comment by jsmolic** [comment]
Thank you!

**Pull request closed without merging**
