### PR TITLE
app-crypt/keybase: bump to 6.0.2, update ebuilds, new maintainer

### PR DESCRIPTION
**Pull request by ran-dall**
Go mod Deps: https://file.io/igx532a7YPkB

Special Thanks to @simonvanderveldt for starting the work in this PR.

### CODE REVIEW

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Hi @ran-dall ! Thanks for submitting this ebuild!

Could you verify the `SRC_URI`? I can't seem to download the source code.

**Comment by ran-dall** [comment]
https://github.com/gentoo/gentoo/pull/27372#issuecomment-1253751583

**Comment by ran-dall** [comment]
@nicolasbock Also, I apologize for taking you off as a maintainer. I assumed you were no longer around. If you want me to add you back, I can.

**Comment by nicolasbock** [comment]
No worries. I am still here although I am usually pretty busy and don't have as much time for Gentoo as I would like. You can add me back.

**Comment by ran-dall** [comment]
@nicolasbock Sorry, mate, I got really busy there for a minute. So I've re-up'd the dep files to files.io: https://file.io/OytRndYmCril

You'd find both the deps for `kbfs` and `keybase` at that same link. From here, you can upload them to your Gentoo space and send me a link; I can then update both ebuilds.

To try this out locally, you should be able to drop both `.tar.xz` files into your `/var/cache/distfiles` directory and proceed.

**Comment by simonvanderveldt** [comment]
@nicolasbock Is there anything preventing this and https://github.com/gentoo/gentoo/pull/27372 from being merged?
Also pinging @thesamesam as well as @ajakk because they (were) mentioned in the removal PR (https://github.com/gentoo/gentoo/pull/26954#issuecomment-1229188360) when wanting to restore these packages.

**Comment by nicolasbock** [comment]
@simonvanderveldt No I don't see any major blockers. I just have to upload that file @ran-dall created. I'll hopefully be able to get to it by tomorrow.

**Comment by nicolasbock** [comment]
Thanks @ran-dall for working on this!

**Comment by simonvanderveldt** [comment]
@nicolasbock Thanks for getting this through/in the tree again! :+1:

**Comment by nicolasbock** [comment]
Sorry this took so long, but no worries, any time.

**Pull request closed without merging**
