### PR TITLE
[RFC] appimage.eclass: new eclass

### PR DESCRIPTION
**Pull request by Hummer12007**
I would like to add an eclass for extracting AppImage bundles. Some upstreams are already distributing their proprietary packages only in the AppImage format (for example dev-util/staruml-bin see https://bugs.gentoo.org/show_bug.cgi?id=667006).

Additionally, I'm seeking a maintainer to be mentioned in the @MAINTAINER section and asking for feedback on this eclass.

### CODE REVIEW

**Comment by candrews** [comment]
What packages would be using this eclass?

It would probably be helpful if you included a new package or an update to an existing one to demonstrate the utility of this new eclass.

**Comment by Hummer12007** [comment]
@candrews I've added the ebuild

**Comment by Zlogene** [comment]
New eclasses should not be submitted via PR, please send a message to the gentoo-dev ML

**Comment by Hummer12007** [comment]
@Zlogene done: https://archives.gentoo.org/gentoo-dev/message/c5a7d09379386416d62bbb1380cd80e8

**Pull request closed without merging**
