### PR TITLE
dev-java/mockito: add 4.4.0 | mockito dependencies | dev-java/fop: Enable tests on fop-core

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by Flowdalic** [comment]
I get

```
>>> Test phase: dev-java/fop-2.7
 * Compiling ...
JUnit version 4.13.2-SNAPSHOT
..
Time: 0.154

OK (2 tests)

 * Compiling ...
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:27: error: cannot find symbol
import static org.mockito.ArgumentMatchers.any;
                         ^
  symbol:   class ArgumentMatchers
  location: package org.mockito
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:27: error: static import only from classes and interfaces
import static org.mockito.ArgumentMatchers.any;
^
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:28: error: cannot find symbol
import static org.mockito.ArgumentMatchers.argThat;
                         ^
  symbol:   class ArgumentMatchers
  location: package org.mockito
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:28: error: static import only from classes and interfaces
import static org.mockito.ArgumentMatchers.argThat;
^
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:29: error: cannot find symbol
import static org.mockito.ArgumentMatchers.eq;
                         ^
  symbol:   class ArgumentMatchers
  location: package org.mockito
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:29: error: static import only from classes and interfaces
import static org.mockito.ArgumentMatchers.eq;
^
fop-core/src/test/java/org/apache/fop/pdf/TableHeaderScopeTestCase.java:115: error: interface expected here
    private static class IsScopeAttribute implements ArgumentMatcher<PDFDictionary> {
                                                                    ^
fop-core/src/test/java/org/apache/fop/render/java2d/Java2DUtilTestCase.java:31: error: cannot find symbol
import static org.mockito.ArgumentMatchers.anyInt;
                         ^
  symbol:   class ArgumentMatchers
  location: package org.mockito
fop-core/src/test/java/org/apache/fop/render/java2d/Java2DUtilTestCase.java:31: error: static import only from classes and interfaces
import static org.mockito.ArgumentMatchers.anyInt;
^
fop-core/src/test/java/org/apache/fop/render/java2d/Java2DUtilTestCase.java:32: error: cannot find symbol
import static org.mockito.ArgumentMatchers.eq;
                         ^
  symbol:   class ArgumentMatchers
  location: package org.mockito
```
maybe due wrong javac version when compiling the tests?

**Comment by vaukai** [comment]
> maybe due wrong javac version when compiling the tests?

@Flowdalic That bells a ring to me, looks like still using the [old mockito version](https://github.com/gentoo/gentoo/pull/24920/files#diff-6dcd5aa39fd412e6263b1f9276cb979e832b26bc527f78944bad1bf6134141acL136-R140)? Would I have to change slot for mockito?

**Comment by vaukai** [comment]
> 
> maybe due wrong javac version when compiling the tests?

Switched slot of that new version `dev-java/mockito-4.4.0:4`. Now we have to wait for [keywording](https://bugs.gentoo.org/836912).

**Comment by vaukai** [comment]
@Leo3418 Should you find time please have a look here:

```
>>> Test phase: dev-java/byte-buddy-agent-1.12.8
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 1.8 -target 1.8
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:byte-buddy-agent.jar:/usr/share/findbugs-annotations/lib/findbugs-annotations.jar:/usr/share/jna-4/lib/jna.jar:/usr/share/jna-4/lib/jna-platform.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/mockito-4/lib/mockito.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/byte-buddy/lib/byte-buddy.jar:/usr/share/byte-buddy-agent/lib/byte-buddy-agent.jar:/usr/share/objenesis/lib/objenesis.jar:/usr/share/opentest4j/lib/opentest4j.jar @test_sources.lst
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: src/test/java/net/bytebuddy/test/utility/MockitoRule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
JUnit version 4.13.2-SNAPSHOT
........................E.E.E.E........................
Time: 1.516
There were 4 failures:
1) testSystemProperties(net.bytebuddy.agent.VirtualMachineAttachmentTest)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.bytebuddy.agent.VirtualMachineAttachmentTest.testSystemProperties(VirtualMachineAttachmentTest.java:64)
        ... 11 trimmed
Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path (target/test-classes:byte-buddy-agent.jar:/usr/share/findbugs-annotations/lib/findbugs-annotations.jar:/usr/share/jna-4/lib/jna.jar:/usr/share/jna-4/lib/jna-platform.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/mockito-4/lib/mockito.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/byte-buddy/lib/byte-buddy.jar:/usr/share/byte-buddy-agent/lib/byte-buddy-agent.jar:/usr/share/objenesis/lib/objenesis.jar:/usr/share/opentest4j/lib/opentest4j.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar)
        at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1059)
        at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
        at com.sun.jna.Native.<clinit>(Native.java:221)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(VirtualMachine.java:879)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(VirtualMachine.java:910)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:245)
        ... 17 more
2) testAgentProperties(net.bytebuddy.agent.VirtualMachineAttachmentTest)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.bytebuddy.agent.VirtualMachineAttachmentTest.testAgentProperties(VirtualMachineAttachmentTest.java:78)
        ... 11 trimmed
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(VirtualMachine.java:879)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(VirtualMachine.java:910)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:245)
        ... 17 more
3) testMultipleProperties(net.bytebuddy.agent.VirtualMachineAttachmentTest)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.bytebuddy.agent.VirtualMachineAttachmentTest.testMultipleProperties(VirtualMachineAttachmentTest.java:92)
        ... 11 trimmed
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(VirtualMachine.java:879)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(VirtualMachine.java:910)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:245)
        ... 17 more
4) testAttachment(net.bytebuddy.agent.VirtualMachineAttachmentTest)
java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.bytebuddy.agent.VirtualMachineAttachmentTest.testAttachment(VirtualMachineAttachmentTest.java:51)
        ... 11 trimmed
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.sun.jna.Native
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(VirtualMachine.java:879)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(VirtualMachine.java:910)
        at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:245)
        ... 17 more
```

**Comment by Leo3418** [comment]
> @Leo3418 Should you find time please have a look here:
> 
> ```
> >>> Test phase: dev-java/byte-buddy-agent-1.12.8
>  * Verbose logging for "ejavac" function
>  * Compiler executable: javac
>  * Extra arguments: -source 1.8 -target 1.8
>  * Complete command:
>  * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:byte-buddy-agent.jar:/usr/share/findbugs-annotations/lib/findbugs-annotations.jar:/usr/share/jna-4/lib/jna.jar:/usr/share/jna-4/lib/jna-platform.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/mockito-4/lib/mockito.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/byte-buddy/lib/byte-buddy.jar:/usr/share/byte-buddy-agent/lib/byte-buddy-agent.jar:/usr/share/objenesis/lib/objenesis.jar:/usr/share/opentest4j/lib/opentest4j.jar @test_sources.lst
>  * Compiling ...
> warning: [options] bootstrap class path not set in conjunction with -source 8
> Note: src/test/java/net/bytebuddy/test/utility/MockitoRule.java uses or overrides a deprecated API.
> Note: Recompile with -Xlint:deprecation for details.
> 1 warning
> JUnit version 4.13.2-SNAPSHOT
> ........................E.E.E.E........................
> Time: 1.516
> There were 4 failures:
> 1) testSystemProperties(net.bytebuddy.agent.VirtualMachineAttachmentTest)
> java.lang.reflect.InvocationTargetException
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
>         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
>         at java.base/java.lang.reflect.Method.invoke(Method.java:568)
>         at net.bytebuddy.agent.VirtualMachineAttachmentTest.testSystemProperties(VirtualMachineAttachmentTest.java:64)
>         ... 11 trimmed
> Caused by: java.lang.UnsatisfiedLinkError: Native library (com/sun/jna/linux-x86-64/libjnidispatch.so) not found in resource path (target/test-classes:byte-buddy-agent.jar:/usr/share/findbugs-annotations/lib/findbugs-annotations.jar:/usr/share/jna-4/lib/jna.jar:/usr/share/jna-4/lib/jna-platform.jar:/usr/share/jsr305/lib/jsr305.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/mockito-4/lib/mockito.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/byte-buddy/lib/byte-buddy.jar:/usr/share/byte-buddy-agent/lib/byte-buddy-agent.jar:/usr/share/objenesis/lib/objenesis.jar:/usr/share/opentest4j/lib/opentest4j.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar)
>         at com.sun.jna.Native.loadNativeDispatchLibraryFromClasspath(Native.java:1059)
>         at com.sun.jna.Native.loadNativeDispatchLibrary(Native.java:1015)
>         at com.sun.jna.Native.<clinit>(Native.java:221)
>         at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.<init>(VirtualMachine.java:879)
>         at net.bytebuddy.agent.VirtualMachine$ForHotSpot$Connection$ForJnaPosixSocket$Factory.withDefaultTemporaryFolder(VirtualMachine.java:910)
>         at net.bytebuddy.agent.VirtualMachine$ForHotSpot.attach(VirtualMachine.java:245)
>         ... 17 more

Try adding `dev-java/jna:4` to the dependencies and classpath

**Comment by vaukai** [comment]
> 
> Might be caused by a fricking nonsense suggestion at [java-native-access/jna#384](https://github.com/java-native-access/jna/issues/384). Try adding `-Djna.nosys=false` to `JAVA_TEST_EXTRA_ARGS`. [...]

@Leo3418 
Just tried it but does not help, the test failures persist :-(

**Comment by vaukai** [comment]
@Flowdalic

**Comment by fordfrog** [comment]
i just merged those two `MAVEN_ID` commits.

**Pull request closed without merging**
