### PR TITLE
*/*: update cache

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by operatornormal** [comment]
Owner of https://bugs.gentoo.org/740866 here -> inheriting  xdg will be enough? If yes, I don't object the change at all. I'm a proxied maintainer, so I've just made pull requests myself - obviously someone is going merge this one-liner?

**Comment by jsmolic** [comment]
> Owner of https://bugs.gentoo.org/740866 here -> inheriting xdg will be enough? If yes, I don't object the change at all. I'm a proxied maintainer, so I've just made pull requests myself - obviously someone is going merge this one-liner?

Yes, xdg eclass handles updating cache automatically (if ebuild does not have pkg_postinst or pkg_postrm, which is the case here).\
A Gentoo dev will have to give final review and push this.

**Review by voyageur — APPROVED** [review]

**Comment by operatornormal** [comment]
Hey @jsmolic and others involved, thank you for your work. I have a question about my https://bugs.gentoo.org/740866 bug report -> is this supposed to be closed automatically once merge is finished?

**Comment by jsmolic** [comment]
@operatornormal Hey\
Yes, all mentioned bugs will be automatically closed when this is merged, hence the `Closes: ` tags in the [commit messages](https://www.gentoo.org/glep/glep-0066.html#commit-messages). I will ping a dev to merge this so that you are not spammed with mails about this :D

@thesamesam Hi, some QA fixes here, if you would like to merge this one :)

**Comment by SoapGentoo** [comment]
@jsmolic I'll merge in a sec, thanks for your work

**Comment by jsmolic** [comment]
@SoapGentoo Thank you :)

**Pull request closed without merging**
