### PR TITLE
app-misc/screenfetch: new version

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Closes: https://bugs.gentoo.org/696892
Package-Manager: Portage-2.3.77, Repoman-2.3.17
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by wimmuskee** [comment]
The 3.9.0 version has since been added with: https://github.com/gentoo/gentoo/commit/566e8d15d4076548f5d852ce8868e9295a31af6e. I'm also wondering why the dev didn't use your PR.

**Comment by anarchpenguin** [comment]
> The 3.9.0 version has since been added with: [566e8d1](https://github.com/gentoo/gentoo/commit/566e8d15d4076548f5d852ce8868e9295a31af6e). I'm also wondering why the dev didn't use your PR.

We do not use a PR when doing simple bumps these are just copied ebuilds.

**Comment by Alessandro-Barbieri** [comment]
> > The 3.9.0 version has since been added with: [566e8d1](https://github.com/gentoo/gentoo/commit/566e8d15d4076548f5d852ce8868e9295a31af6e). I'm also wondering why the dev didn't use your PR.
> 
> We do not use a PR when doing simple bumps these are just copied ebuilds.

This is disrespectful

**Comment by wimmuskee** [comment]
> > The 3.9.0 version has since been added with: [566e8d1](https://github.com/gentoo/gentoo/commit/566e8d15d4076548f5d852ce8868e9295a31af6e). I'm also wondering why the dev didn't use your PR.
> 
> We do not use a PR when doing simple bumps these are just copied ebuilds.

It's not always clear to us contributors how we can best help the developers. 
That being said, since the PR was correctly linked to the bugreport, some communication from the dev would have been appropriate imo.

**Comment by juippis** [comment]
> We do not use a PR when doing simple bumps these are just copied ebuilds.

Some people do. Most devs probably don't know about pram, 
https://packages.gentoo.org/packages/app-portage/pram
https://packages.gentoo.org/packages/dev-perl/Gentoo-App-Pram

which allows merging these PRs with one command. You don't have to `cp 1 2`, `repoman manifest` with it. 

Sorry @Alessandro-Barbieri that the maintainer didn't notice or communicate about this. It could be that johu has turned off Github notifications altogether, and that he decided to do a bump based on bugzilla e-mail title (ie not even opening the Bugzilla web page, just following e-mail) and failed to notice the link. Or he found bumping it himself easier. We can't say.

Devs aren't obliged to check Github, or use it. I find it convenient, but many devs hate it with passion. It's unfortunate, but you'll learn quite fast which projects / devs respond to Github PRs. What you did was correct, link the PR to that bug, to gain visibility. 

Hope it goes better next time.

**Pull request closed without merging**
