### PR TITLE
sys-kernel/linux-firmware: compress firmwares via copy-firmware.sh

### PR DESCRIPTION
**Pull request by puleglot**
Currently we only skip compression of AMD microcode, but we should skip it for all files labeled as RawFile in WHENCE. copy-firmware.sh got support for compressing firmware files at some point and it does it right.

A notable consequence of this change is that saved config now contains file names with compression extension.

Closes: https://bugs.gentoo.org/934537

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by puleglot** [comment]
Note that I didn't ported all changes to live ebuild, only those that touches passing options to copy-firmware.sh

**Comment by AndrewAmmerlaan** [comment]
Do you know if there is a reason why it wasn't done like this originally in: https://gitweb.gentoo.org/repo/gentoo.git/commit/sys-kernel/linux-firmware?id=12113f5d57730f8c36d3df433ec7f1606519e360 ?

**Comment by puleglot** [comment]
> Do you know if there is a reason why it wasn't done like this originally in: https://gitweb.gentoo.org/repo/gentoo.git/commit/sys-kernel/linux-firmware?id=12113f5d57730f8c36d3df433ec7f1606519e360 ?

Because upstream added support for this later:
https://git.kernel.org/pub/scm/linux/kernel/git/firmware/linux-firmware.git/commit/?id=ee91452dac5abfc4c5b9827cf55e701d8c0ca678

**Comment by thesamesam** [comment]
Could you note that in the commit message?

**Comment by mpagano** [comment]
Is it normal to do a new commit like this so we can't see the diff ?

**Comment by AndrewAmmerlaan** [comment]
> Is it normal to do a new commit like this so we can't see the diff ?

The revision bump is required since the effective list of files excluded from compressing is changed.

**Pull request closed without merging**
