### PR TITLE
Enlightenment - SVN removal and switch to https://

### PR DESCRIPTION
**Pull request by bjacquin**

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi @bjacquin! Sorry for taking so long to respond. Could you please send your eclass patches to gentoo-dev@ for everyone to see them? That's the usual workflow for such changes.

**Comment by bjacquin** [comment]
Thanks, this has bug been done, could you review python-efl ebuild change ?

**Comment by monsieurp** [comment]
OK. Thanks. I think @vapier is AWtOL at that point. These changes look harmless. LGTM. @mgorny can you also sign off of this PR?

**Comment by bjacquin** [comment]
I'm avoid the publication of the patches on the ML did not get much love :/

**Comment by mgorny** [comment]
Don't worry. Nobody maintains enlightenment anymore, so I doubt anybody's going to mind me merging it.

**Pull request closed without merging**
