### PR TITLE
app-admin/sysklogd: Fixing build issue with Glibc 2.24. bug #604232

### PR DESCRIPTION
**Pull request by saboya**

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Please convert the ebuild to EAPI-5 and fix the file locations in the patch. Make the patch compatible for `patch -p1` usage. See below examples:

**Bad:**
```
diff -upk.orig sysklogd-1.4.2.orig/klogd.8 sysklogd-1.4.2/klogd.8
--- sysklogd-1.4.2.orig/klogd.8 2005-03-11 16:12:09 +0000
+++ sysklogd-1.4.2/klogd.8      2005-08-18 14:37:47 +0000
@@ -18,6 +19,12 @@ klogd \- Kernel Log Daemon
```
**Good:**
```
--- sysklogd-1.4.2/klogd.8
+++ sysklogd-1.4.2/klogd.8
@@ -18,6 +19,12 @@ klogd \- Kernel Log Daemon
```

**Comment by saboya** [comment]
Is there anything non-trivial about converting to EAPI-5? I would assume it's not a simple bump.

About the patch location: will do.

**Comment by Polynomial-C** [comment]
Well that depends on the ebuild if it's trivial to bump to EAPI-5. If you want to learn something about differnt EAPIs you can read the EAPI documentation in the [devmanual](https://devmanual.gentoo.org/ebuild-writing/eapi/). Otherweise, just skip this and I do the conversion after the PR merge.

**Comment by saboya** [comment]
I'll read the documentation and give it a shot. Thanks for the review.

**Comment by saboya** [comment]
Corrected the patch and bumped to EAPI=5. Squashed the commits.

**Pull request closed without merging**
