### PR TITLE
dev-db/sqlite: Version bump (3.30.0).

### PR DESCRIPTION
**Pull request by vaibhav-rustagi**
Signed-off-by: Vaibhav Rustagi <vaibhavrustagi@google.com>

### CODE REVIEW

**Comment by vaibhav-rustagi** [comment]
@Arfrever  , @floppym 

Can you review the changes?

**Comment by vaibhav-rustagi** [comment]
cc. @Arfrever , @floppym

Closes: https://bugs.gentoo.org/697678

**Comment by anarchpenguin** [comment]
3.30.1 has been released

**Comment by juippis** [comment]
Looks like sqlite has been bumped to 3.30.1.

**Pull request closed without merging**
