### PR TITLE
dev-util/meson: bump to 0.50.0

### PR DESCRIPTION
**Pull request by hanetzer**
Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Marty E. Plummer <hanetzer@startmail.com>

### CODE REVIEW

**Comment by Whissi** [comment]
> [2019-03-14 - 16:53:16]<leio>	WilliamH: floppym: Please do not bump meson to 0.50.0 in main tree.
> [2019-03-14 - 16:53:37]<leio>	https://github.com/mesonbuild/meson/issues/5049 and various other regressions; I don't want a spree of bug reports for every gnome package.
> [2019-03-14 - 16:55:58]<leio>	https://github.com/mesonbuild/meson/milestone/37

@leio

**Comment by hanetzer** [comment]
@Whissi ah, fair. I wouldn't want things to explode for gnome folks :)

**Comment by XVilka** [comment]
Note that 0.50.1 version was released https://github.com/mesonbuild/meson/releases/tag/0.50.1

**Comment by a17r** [comment]
meson was already bumped by maintainer.

**Pull request closed without merging**
