### PR TITLE
media-video/mpv-mpris: new package.

### PR DESCRIPTION
**Pull request by olifre**
mpv-mpris is a C plugin for mpv adding MPRIS
(Media Player Remote Interfacing Specification)
support to mpv.

Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Oliver Freyermuth <o.freyermuth@googlemail.com>

**Note for reviewers:** 
The patch needed to fix `CFLAGS` and `LDFLAGS` is pending with upstream, so it can hopefully be dropped again at a later point. 
Suggestion for improvements to `src_install` are especially welcome.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by olifre** [comment]
Dear @AndrewAmmerlaan ,

thanks for the reply. I know of GURU, but did not have the time yet neither to join as developer nor to check the contents of it as user. 
While for this package, GURU is certainly a possibility, I also have other packages (coming up) which are needed as new dependencies of updated versions of existing packages I proxy-maintain. 

Does your statement mean that also these cases will likely be pending for >1 year, and there is essentially no way to proxy-maintain new packages in Gentoo proper anymore (i.e. proxy-maintenance is now "maintenance-only")?

**Comment by AndrewAmmerlaan** [comment]
> I also have other packages (coming up) which are needed as new dependencies of updated versions of existing packages I proxy-maintain.
>
> Does your statement mean that also these cases will likely be pending for >1 year, and there is essentially no way to proxy-maintain new packages in Gentoo proper anymore (i.e. proxy-maintenance is now "maintenance-only")?

It is my understanding that PRs that touch packages that are already in ::gentoo have priority (self-maintained > maintainer-needed > unassigned > new packages). Meaning that if a new package is required by a version bump of an already existing package, that it will have higher priority over new packages that are not dependencies of existing packages. And therefore will most likely be reviewed and merged faster.

In my own experience: I have made PRs that version bumped packages and introduced new dependencies and had these reviewed relatively quick. I've also made PRs that introduced new stand-alone packages, and these didn't get any love or attention at all. I therefore merged these to GURU instead, and this is also why I'm going through some of the 'new package' PRs leaving comments about the GURU overlay. Since the GURU overlay might offer a place for ebuilds that would otherwise be forgotten here.

**Comment by olifre** [comment]
> In my own experience: I have made PRs that version bumped packages and introduced new dependencies and had these reviewed relatively quick. I've also made PRs that introduced new stand-alone packages, and these didn't get any love or attention at all. I therefore merged these to GURU instead, and this is also why I'm going through some of the 'new package' PRs leaving comments about the GURU overlay. Since the GURU overlay might offer a place for ebuilds that would otherwise be forgotten here.

Thanks! That sounds like a reasonable approach (and thanks for the work to go through all those issues!). I'll then check out GURU as user first, and as developer later, and come back to this issue once I have migrated it to GURU (unless it is processed faster) ;-).

**Comment by olifre** [comment]
For a future person visiting this: I have bumped to the latest 0.5 version and it is now also in `dev` of GURU:
https://gitweb.gentoo.org/repo/proj/guru.git/commit/?h=dev&id=99f678492d15f81466c38763b0fa2c48d0d6cc47
I'd still like to get it in Portage, proxy-maintaining it, but that will allow the ebuild to see more usage and more eyes to improve it.

**Comment by ajakk** [comment]
Thank you for your work on this! Let's close this PR in favor of the GURU version.

**Comment by olifre** [comment]
@ajakk Thanks! Is it still wanted to open PRs here for migration of packages to Gentoo portage main? Or does this work in another way?

**Comment by ajakk** [comment]
Generally speaking, if a developer is interested in a package from GURU they can add it to Gentoo and then co-maintain it with (or proxy commits for) the GURU maintainer.

**Pull request closed without merging**
