### PR TITLE
app-editors/scite: Tidy ebuild

### PR DESCRIPTION
**Pull request by cjmayo**
- eutils.eclass not needed
- one sed not two for gtk/makefile
- consistent sed paths and error messages
- Encoding now removed from desktop file
- ensure variable declared in src_compile is local
- dodir's in src_install not needed

Package-Manager: Portage-2.3.13, Repoman-2.3.3

### CODE REVIEW

**Comment by a17r** [comment]
@jonasstein seems you touched the ebuild last time

**Comment by jonasstein** [comment]
Thank you for the tidy up. I can not review it before weekend but it looks good on the first look. Ervin, you can test it in the meantime and report if there is any objection from your point of position. @cjmayo do you want to join as second proxied maintainer for this package too?

**Comment by cjmayo** [comment]
Changed tag to Closes.

As to proxying, I am maintaining my own fork of the ebuild at the moment for a couple of reasons:

- Better icons, 3.7 patch at:
https://sourceforge.net/p/scintilla/feature-requests/1170/#579c/8744/d145/3e8f
Maybe that could be added behind a USE flag If it could be hosted somewhere

- Patches for my own preferences, which are relative to ```${WORKDIR}/scite``` and not ```${WORKDIR}``` so the ```cd``` before ```eapply_user``` doesn't work for me. And I don't want to have to manually edit the paths - they are made from a clone of the scintilla-scite repository.

**Comment by jonasstein** [comment]
merged in commit 0d0a3c4df07778110309e721003fb90de4398297
Thank you.

**Pull request closed without merging**
