### PR TITLE
app-emulation/xen: add 4.15.4

### PR DESCRIPTION
**Pull request by hydrapolic**
```bash
--- xen-4.15.4_pre2.ebuild      2022-12-02 01:41:51.756984798 +0000
+++ xen-4.15.4.ebuild   2022-12-02 02:14:09.086660839 +0000
@@ -14,9 +14,9 @@
 else
        KEYWORDS="~amd64 ~arm -x86"
 
-       XEN_PRE_PATCHSET_NUM=1
+       XEN_PRE_PATCHSET_NUM=
        XEN_GENTOO_PATCHSET_NUM=
-       XEN_PRE_VERSION_BASE=4.15.3
+       XEN_PRE_VERSION_BASE=
 
        XEN_BASE_PV="${PV}"
        if [[ -n "${XEN_PRE_VERSION_BASE}" ]]; then
@@ -35,6 +35,7 @@
                XEN_GENTOO_PATCHES_TAG="$(ver_cut 1-3 ${XEN_BASE_PV})-gentoo-patchset-${XEN_GENTOO_PATCHSET_NUM}"
                XEN_GENTOO_PATCHES_NAME="xen-gentoo-patches-${XEN_GENTOO_PATCHES_TAG}"
                SRC_URI+=" https://gitweb.gentoo.org/proj/xen-gentoo-patches.git/snapshot/${XEN_GENTOO_PATCHES_NAME}.tar.bz2"
+               SRC_URI+=" https://github.com/hydrapolic/gentoo-dist/raw/master/xen/${XEN_UPSTREAM_PATCHES_NAME}.tar.bz2"
                XEN_GENTOO_PATCHES_DIR="${WORKDIR}/${XEN_GENTOO_PATCHES_NAME}"
        fi
 fi
```

```bash
--- xen-tools-4.15.4_pre2.ebuild        2022-12-02 01:41:51.755984793 +0000
+++ xen-tools-4.15.4.ebuild     2022-12-02 02:13:29.148461363 +0000
@@ -23,9 +23,9 @@
        EDK2_BROTLI_COMMIT="666c3280cc11dc433c303d79a83d4ffbdd12cc8d"
        IPXE_COMMIT="3c040ad387099483102708bb1839110bc788cefb"
 
-       XEN_PRE_PATCHSET_NUM=1
-       XEN_GENTOO_PATCHSET_NUM=2
-       XEN_PRE_VERSION_BASE=4.15.3
+       XEN_PRE_PATCHSET_NUM=
+       XEN_GENTOO_PATCHSET_NUM=1
+       XEN_PRE_VERSION_BASE=
 
        XEN_BASE_PV="${PV}"
        if [[ -n "${XEN_PRE_VERSION_BASE}" ]]; then
@@ -53,6 +53,7 @@
                XEN_GENTOO_PATCHES_TAG="$(ver_cut 1-3 ${XEN_BASE_PV})-gentoo-patchset-${XEN_GENTOO_PATCHSET_NUM}"
                XEN_GENTOO_PATCHES_NAME="xen-gentoo-patches-${XEN_GENTOO_PATCHES_TAG}"
                SRC_URI+=" https://gitweb.gentoo.org/proj/xen-gentoo-patches.git/snapshot/${XEN_GENTOO_PATCHES_NAME}.tar.bz2"
+               SRC_URI+=" https://github.com/hydrapolic/gentoo-dist/raw/master/xen/${XEN_GENTOO_PATCHES_NAME}.tar.bz2"
                XEN_GENTOO_PATCHES_DIR="${WORKDIR}/${XEN_GENTOO_PATCHES_NAME}"
        fi
 fi
```

Compile tested on ~amd64.

### CODE REVIEW

**Comment by Flowdalic** [comment]
As per our mail conversation, I'll see what needs to be done to get you write access to the according xen gitweb.g.o repos and come back to you. So that we have a single source of the two patchsets.

As always, thanks for your contributions. 😄

**Comment by Flowdalic** [comment]
@hydrapolic please attach your public ssh key to https://bugs.gentoo.org/883995

**Comment by Flowdalic** [comment]
I found that the previous Gentoo patches apply cleanly on the new Xen version, so I am going for a solution where the ebuild just re-uses the patches by introducing a XEN_GENTOO_PATCHSET_BASE variable.

**Comment by hydrapolic** [comment]
Thanks @Flowdalic

**Pull request closed without merging**
