### PR TITLE
net-misc/openssh: Use pkg_pretend() to detect earlier unsupported fea…

### PR DESCRIPTION
**Pull request by bjacquin**
…tures

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by robbat2** [comment]
Merged

**Comment by Whissi** [comment]
This change blocks system updates using `--keep-going=y`: Previously, when *net-misc/openssh[hpn]* update just failed due to missing hpn patch set, world update continued. Now *emerge* is stopping immediately after this pre check so you are forcing the user to take action (i.e. applying a mask, unset hpn or to exclude the package from emerge).

Please revert... 

@bjacquin: Could you please explain why you submitted this change request? What benefits were you expecting from this change?

**Comment by bjacquin** [comment]
The purpose of this change is to get the error as soon as possible. If you run emerge word -va1uDN, some package will be updated and then when comes openssh update, it will break asking you to mask hpn USE flag for example. Then you have to do the change and rerun the update. Instead of this change prevent that by running the check as soon as possible and then you can effectivly perform a world update without carrying.

**Comment by cardoe** [comment]
@Whissi Your use case is invalid. Relying on `--keep-going=y` is not legit here.

**Pull request closed without merging**
