### PR TITLE
x11-wm/lumina: added missing deps for qtmultimediawidgets and qtsvg.

### PR DESCRIPTION
**Pull request by rubin55**
Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by rubin55** [comment]
@gentoo/proxy-maint

**Comment by blueness** [comment]
i'll test and commit.  the comment should reference bug #578320

**Comment by wraeth** [comment]
As was discussed in the proxy-maint IRC channel, there are a few issues that I will list here simply to keep it all together.

- having both `dev-qt/qtmultimedia:5` and `dev-qt/qtmultimedia:5[widgets]` is unnecessary - leave `dev-qt/qtmultimedia:5[widgets]` only
- `DEPEND` and `RDEPEND` contain many duplicate entries - this can be simplified by listing common dependencies in `COMMON_DEPEND` then setting `DEPEND` and `RDEPEND` to `="${COMMON_DEPEND} <other-deps>`
- The two file installs on lines 58-59 are better done with `newins` and `newbin` respectively (see [devmanual](https://devmanual.gentoo.org/function-reference/install-functions/))
- If possible, it would be preferable to get upstream to make a versioned release tarball rather than pinning the ebuild to a commit, though failing that it is done correctly

Additionally, I have done a build-test of this in a minimal testing environment and have come across a couple of further issues:

- Desktop file elicits QA warnings when installed:
```
 * 	/usr/share/applications/lumina-info.desktop: error: value "Lumina;" for key "OnlyShowIn" in group "Desktop Entry" contains an unregistered value "Lumina"; values extending the format should start with "X-"
 * 	/usr/share/applications/lumina-support.desktop: error: key "Categories" is present in group "Desktop Entry", but the type is "Link" while this key is only valid for type "Application"
 * 	/usr/share/applications/lumina-support.desktop: error: value "Lumina;" for key "OnlyShowIn" in group "Desktop Entry" contains an unregistered value "Lumina"; values extending the format should start with "X-"
```
- Library is installed incorrectly (failing `multilib-strict`):
```
Files matching a file type that is not allowed:
   usr/lib/libLuminaUtils.so.1.0.0
 * ERROR: x11-wm/lumina-0.8.8_p1::gentoo failed:
 *   multilib-strict check failed!
```

Keep up the hard work and let us know if there are any queries!

**Comment by blueness** [comment]
if upstream won't produce the tarballs, we could, except that its work.  but it is very annoying to have to do a git pull during a build.

**Comment by rubin55** [comment]
@blueness: they do produce tarballs upstream, however, the Gentoo related support was added in the master branch, after the latest stable tarball (0.8.8) was released. After a discussion in #gentoo-proxy-maint, we decided that the best course of action was to name a testing package 0.8.8_p1 so that if 0.9 stable comes out we can switch to building from tarball, without version number hassles AND in this way we would be able to deal with the eventuality of another 0.8.x intermediate release coming out.

**Comment by rubin55** [comment]
@wraeth: wow great summary of things to fix. I'll get right to it, thanks.

**Comment by wraeth** [comment]
@blueness also, it **is** downloading a tarball, but it's a commit snapshot rather than a versioned release tarball.

**Comment by blueness** [comment]
@rubin55 i'll wait for you to update the ebuild incorporating wraeth's comments.  it doesn't have to be perfect since its still masked.

**Comment by wraeth** [comment]
Buildtest as requested based on commit 10e5095 worked successfully and all files appear to be installing to the correct location.

Final remaining comment I have for the ebuild(s) is the call to `eqmake5` on line 43 should be broken with line continuations so as to not exceed 80 characters:

```
src_configure() {
    eqmake5 PREFIX="${ROOT}usr" L_BINDIR="${ROOT}usr/bin" \
        L_ETCDIR="${ROOT}etc" L_LIBDIR="${ROOT}usr/$(get_libdir)" \
        LIBPREFIX="${ROOT}usr/$(get_libdir)" DESTDIR="${D}" CONFIG+="NO_I18N"
}
```

Additionally, you may need to [squash](https://help.github.com/articles/about-git-rebase/) your commits into one or two logical changes and clean up the commit history - the repository should be in a "working" condition with each commit - however I am no GitHub maestro, so comment from someone who is may be advisable! :smile: 

Keep up the good work!

**Comment by monsieurp** [comment]
bash array someone?
```
src_configure() {
  local myqmake5args=(
    PREFIX="${ROOT}usr"
    L_BINDIR="${ROOT}usr/bin"
    # and so forth..
  )
  eqmake5 "${myqmake5args[@]}"
}
```

**Comment by rubin55** [comment]
@blueness: would you like to do a test install also? thanks in advance!

**Comment by Arfrever** [comment]
Wrong bug number in commit message: `x11-wm/lumina: fixes for bug #57320.`

**Comment by blueness** [comment]
i'll commit and then test.  against as long as its masked, its okay if there's still breakage.  if there isn't any, we can wait a few day sfor more testing and then lift the mask

**Comment by blueness** [comment]
this is in the tree now and i'm going to remove the mask.  thanks!

**Pull request closed without merging**
