### PR TITLE
sys-devel/slibtool: latest release

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-3.0.17, Repoman-3.0.2
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

this version has more features

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
@orbea @ionenwks

**Comment by orbea** [comment]
@midipix

**Comment by thesamesam** [comment]
This isn't a release - it's a snapshot. Anyway, let's see what midipix says.

**Comment by midipix** [comment]
Let's push this forward indeed, starting with a couple of beneficial, low-hanging-fruit fixes today and tomorrow, and release of v0.5.32 this Sunday. Generally speaking, my preference is to release slibtool often and have distros use an official release tarball rather than a specific commit (those are still gpg-signed and so not too bad altogether, but still...)

**Comment by thesamesam** [comment]
We'll add the release when it's out. Thanks, though, OP.

**Comment by midipix** [comment]
The deed is done. While we're at it, please make sure to update the git repository reference (in the package meta data) to the official https://git.foss21.org/slibtool -- thanks!

https://dev.midipix.org/cross/slibtool/c/2f2f9d566545274141c89e7e1fb506e176c7ebd5?branch=main

https://dl.midipix.org/slibtool/slibtool-0.5.32.tar.xz
https://dl.midipix.org/slibtool/slibtool-0.5.32.tar.xz.sig

https://dl.midipix.org/slibtool/slibtool-0.5.32.tar.gz
https://dl.midipix.org/slibtool/slibtool-0.5.32.tar.gz.sig

**Pull request closed without merging**
