### PR TITLE
Rename jack2-1.9.11_rc1.ebuild to jack2-1.9.11_rc2.ebuild

### PR DESCRIPTION
**Pull request by audiodef**
EAPI 6, no 2.9999 stuff, supports Firewire/libffado. Successfully tested with Mackie Onyx. Bug: https://bugs.gentoo.org/show_bug.cgi?id=624610

### CODE REVIEW

**Comment by aballier** [comment]
are you bumping to rc2 or updating rc1?

**Comment by audiodef** [comment]
I meant to update rc1 and I changed the ebuild name accordingly. Sorry, still new to some things.

**Comment by aballier** [comment]
Don't worry about rc1: it'll be overshadowed if you bump to rc2 anyway

Please drop the commits on rc1 and just update to rc2 + adding the useflag

I think it's good to keep the 2.9999 stuff and actually we could consider adding the 2.9999 live ebuild for the braves that want to test it

**Comment by audiodef** [comment]
I would be in favor of a separate live ebuild for testing. It seems more logical to keep testing and stable separate.

**Comment by simonvanderveldt** [comment]
@aballier, now that the package is called jack2 shouldn't the live ebuild simply be versioned as 9999 instead of 2.9999?

**Comment by aballier** [comment]
> I would be in favor of a separate live ebuild for testing. It seems more logical to keep testing and stable separate.

Yes, but the if/then/else in the ebuild serves to keep live & release ebuilds in sync in a simple manner; I like to do that for my own packages

> @aballier, now that the package is called jack2 shouldn't the live ebuild simply be versioned as 9999 instead of 2.9999?

Hmm, yes, this makes senses

> P.S. There's no rc2 yet ;)

So... why does this PR bumps to rc2 ?

**Comment by simonvanderveldt** [comment]
@aballier the rc2 bump was an accident, see https://github.com/gentoo/gentoo/pull/5091#issuecomment-314585250

**Comment by aballier** [comment]
ah, then please squash/rebase to remove unwanted commits; there's still some mentionning (and bumping to I think) rc2

**Comment by audiodef** [comment]
Repasted original ebuild and modified it to include ieee1394 use flag, so that 2.9999 case is included. There's no rc2 ebuild - I have renamed the file - and since I'm still new to this, I don't know what else to do. Please feel free to make any necessary adjustments/corrections.

**Comment by aballier** [comment]
https://robots.thoughtbot.com/git-interactive-rebase-squash-amend-rewriting-history
seems like a good read then: 



> “Please rebase on top of master and we’ll merge your pull request”.

> “Can you please squash your commits together so we get a clean, reversible git history?”.

> “Can you rewrite your commit’s message to describe better the problem it solves, and how it solves it?”.

are needed here :)

**Comment by monsieurp** [comment]
Feel free to reopen if you wish to pursue this PR further.

**Pull request closed without merging**
