### PR TITLE
dev-lisp/c2ffi: Version bump to c2ffi-9.0.0

### PR DESCRIPTION
**Pull request by hjudt**
Bump to use c2ffi-9.0.0 branch. At the moment, we need to
supply our own patch to get it building, though the issue
has been reported upstream and a pull request has been sent:

https://github.com/rpav/c2ffi/issues/71
https://github.com/rpav/c2ffi/pull/70

Also remove c2ffi-8.0.0, which has been deprecated upstream
by the update to 9.0.0.

Package-Manager: Portage-2.3.79, Repoman-2.3.18

### CODE REVIEW

**Comment by juippis** [comment]
Please split the addition and removals into their own commits.

**Comment by juippis** [comment]
One thing I noticed about this package:
It doesn't have any keyworded release in Gentoo. We don't support "live ebuilds only" packages, no idea how it got pushed in the first place. Besides I believe the slotting is done incorrectly in here.

So could you take some snapshot from upstream, add keywords to it, and push to tree? Then you can have *-9999 live ebuild **beside** that.

**Comment by hjudt** [comment]
There was a discussion about this prior to its merge on IRC. Upstream provides no snapshots, so I have no idea how I could provide one. Upstream only provides the git branches. Does github somehow allow to download a snapshot? Using the live ebuild was the easiest way to do.

**Comment by hjudt** [comment]
Second, what is the problem with slotting? I asked how to do it and was told it was ok.

**Comment by hjudt** [comment]
Hm. Ok, so I could use something like https://github.com/rpav/c2ffi/archive/15fda06de0bad97bf91f5590f7f24623eab2f580.zip
Are there any ebuild functions to do this?

**Comment by juippis** [comment]
There are, but you should just define it as MY_COMMIT. Check rlottie for example how to deal with no-releases upstream.

About slotting, the point is that two different versions of a same package can co-exist with different slots. I couldnt merge the current c2ffi that's in tree (most likely because llvm.eclass isn't used, linker couldnt find -iLLVM) so I can't check the list of installed files. It doesn't look like anything is done to prevent file collisions between releases, but it might work, I couldnt check now.

**Comment by hjudt** [comment]
Thanks, I'll try to learn from how they do it. And yes, you are right about slotting; the current ebuild will cause file collisions. I intend to only support a single version because the older one gets deprecated anyway by upstream once the newer one is "released".

**Pull request closed without merging**
