### PR TITLE
tree-sitter-grammar.eclass: extended packaging

### PR DESCRIPTION
**Pull request by msva**
1) installing grammar library to additional well-known path
2) also installing queries

See-Also: https://pkgs.alpinelinux.org/contents?branch=edge&name=tree%2dsitter%2dlua&arch=x86_64&repo=community
See-Also: https://pkgs.alpinelinux.org/contents?branch=edge&name=tree%2dsitter%2dcss&arch=x86_64&repo=community

### CODE REVIEW

**Comment by msva** [comment]
This is "draft" PR, and there are many things to discuss here:
1) should eclass be moved to "r1" because of changes? There is nno incompatibilities, but behaviour is changed :shrug: 

2) paths naming:
I mostly looked on alpine ones (see liks in SeeAlso), but maybe anybody here have better ideas?

3) maybe, queries installation should also be USE-conditional?

<...>

**Comment by msva** [comment]
CC: @MatthewGentoo @sarnex

**Comment by thesamesam** [comment]
The commit message doesn't contain any `Bug:` tags (IIRC at least one is relevant here) or any rationale. Please include that.

(Nit: I'd also do `See-Also`, not `SeeAlso`).

**Comment by MatthewGentoo** [comment]
> paths naming:
> I mostly looked on alpine ones (see links in SeeAlso), but maybe anybody here have better ideas?

Which package/tool uses the query files? We should install it where that tool expects them to be.

Does Neovim use them? It seems like the Emacs modes that use tree-sitter use their own highlight queries instead of using the ones provided with the grammar.

> maybe, queries installation should also be USE-conditional?

I think it's OK to install them unconditionally as they are so small. People that really hate them can use INSTALL_MASK :)

**Pull request closed without merging**
