### PR TITLE
puppet-8.6.0: Add Ruby 3.2 keyword

### PR DESCRIPTION
**Pull request by bastelfreak**
That's the officially supported Ruby version from Puppet Inc.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by bastelfreak** [comment]
I fixed the http->https URL update in https://github.com/gentoo/gentoo/pull/36827

```
# pkgcheck scan --commits --net
app-admin/puppet
  RedirectedUrl: version 8.6.0: HOMEPAGE: permanently redirected: https://puppet.com/ -> https://www.puppet.com/
  HttpsUrlAvailable: version 8.6.0: SRC_URI: HTTPS url available: http://downloads.puppetlabs.com/puppet/puppet-8.6.0.tar.gz -> https://downloads.puppetlabs.com/puppet/puppet-8.6.0.tar.gz
  UnstableOnly: for arches: [ arm, arm64, hppa, ppc, ppc64 ], all versions are unstable: [ 7.28.0-r1, 8.5.1, 8.6.0 ]
  RedundantVersion: version 7.28.0-r1: slot(0) keywords are overshadowed by versions: 8.5.1, 8.6.0
  RubyCompatUpdate: version 7.28.0-r1: USE_RUBY update available: ruby32
  NonsolvableDepsInDev: version 8.5.1: nonsolvable depset(bdepend) keyword(amd64) dev profile (default/linux/amd64/17.0/musl) (163 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInDev: version 8.5.1: nonsolvable depset(rdepend) keyword(amd64) dev profile (default/linux/amd64/17.0/musl) (163 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInStable: version 8.5.1: nonsolvable depset(bdepend) keyword(amd64) stable profile (default/linux/amd64/17.1) (175 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInStable: version 8.5.1: nonsolvable depset(rdepend) keyword(amd64) stable profile (default/linux/amd64/17.1) (175 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  RedundantVersion: version 8.5.1: slot(0) keywords are overshadowed by version: 8.6.0
  NonsolvableDepsInDev: version 8.6.0: nonsolvable depset(bdepend) keyword(amd64) dev profile (default/linux/amd64/17.0/musl) (163 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInDev: version 8.6.0: nonsolvable depset(rdepend) keyword(amd64) dev profile (default/linux/amd64/17.0/musl) (163 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInStable: version 8.6.0: nonsolvable depset(bdepend) keyword(amd64) stable profile (default/linux/amd64/17.1) (175 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  NonsolvableDepsInStable: version 8.6.0: nonsolvable depset(rdepend) keyword(amd64) stable profile (default/linux/amd64/17.1) (175 total): solutions: [ >=dev-ruby/facter-3.0.0[ruby_targets_ruby32(-)] ]
  PotentialStable: version 8.6.0: slot(0), stabled arches: [ amd64, x86 ], potentials: [ ~arm, ~arm64, ~hppa, ~ppc, ~ppc64 ]
  RdependChange: version 8.5.1: RDEPEND modified without revbump
  RdependChange: version 8.6.0: RDEPEND modified without revbump
```

**Comment by bastelfreak** [comment]
I fixed the facter version dependency in https://github.com/gentoo/gentoo/pull/36828

**Comment by bastelfreak** [comment]
works fine locally:

```
# puppet facts show puppetversion facterversion ruby
/etc/puppetlabs/code/environments/production/modules/portage/lib/facter/eselect.rb:2: warning: already initialized constant ESELECT_CMD
/opt/puppetlabs/puppet/cache/lib/facter/eselect.rb:2: warning: previous definition of ESELECT_CMD was here
{
  "facterversion": "4.4.1",
  "puppetversion": "8.6.0",
  "ruby": {
    "platform": "x86_64-linux",
    "sitedir": "/usr/lib64/ruby/site_ruby/3.2.0",
    "version": "3.2.3"
  }
}
```

(also requires https://github.com/gentoo/gentoo/pull/36829)

**Comment by graaff** [comment]
I see I got added as a reviewer but I can't really review anything here since the tests are not being run. That would need to be fixed first. The package maintainer may have a different view on this.

**Comment by bastelfreak** [comment]
we first need to resolve https://bugs.gentoo.org/934317 https://bugs.gentoo.org/934316

**Comment by thesamesam** [comment]
I'm working on the stablereqs now. @bastelfreak is there any chance I could tempt you into getting the tests passing (dropping the restriction)?

**Comment by bastelfreak** [comment]
@thesamesam I rebased the branch, but I'm not really sure what the current issues are :( I think the last CI report isn't up2date anymore (https://qa-reports.gentoo.org/output/gentoo-ci/419b8ec853/output.html)?

**Comment by bastelfreak** [comment]
@thesamesam CI finished, but I don't quite understand the output :( Can you enlighten me a bit?

**Comment by thesamesam** [comment]
We need https://bugs.gentoo.org/934881 done (which wasn't filed until I did it yesterday...)

You don't have to wait on it, though. You can revbump the ebuilds you're changing here and drop the missing keywords (so it matches facter) and I can then add the new puppet ebuilds into that bug.

**Comment by bastelfreak** [comment]
@thesamesam can you help me out a bit here? I'm a bit lost and not really sure what do to. Which flags should I adjust?

**Comment by thesamesam** [comment]
I'll take a look later today (or perhaps tomorrow), thanks! Please remind me if I don't.

**Comment by bastelfreak** [comment]
@thesamesam ping :)

**Comment by bastelfreak** [comment]
@thesamesam hey, can you please take a look again please?

**Comment by thesamesam** [comment]
It's stuck on https://bugs.gentoo.org/934881, but let's see if we can drop ~arm on puppet for now and just add it in there.

**Pull request closed without merging**
