### PR TITLE
sys-auth/munge: restore stable initd script

### PR DESCRIPTION
**Pull request by crorvick**
The init script was updated for 0.15.13, but the same init script is used for the 0.15.10 stable release and the change breaks it.  Create version-specific versions of these files to resolve.

### CODE REVIEW

**Comment by ajakk** [comment]
Still there? Please update this to apply to the tree in its current state.

**Comment by crorvick** [comment]
On Thu, Mar 25, 2021 at 8:28 AM ajakk ***@***.***> wrote:

> Still there? Please update this to apply to the tree in its current state.
>
This was to fix an issue that existed almost two years ago.  If it's not
rebasing cleanly, then probably not relevant anymore.

**Comment by ajakk** [comment]
There are plenty of reasons why a patch might not apply cleanly to the tree anymore without that patch being completely useless. I don't know this software, is the bug still a valid bug?

**Comment by crorvick** [comment]
On Thu, Mar 25, 2021 at 9:34 AM ajakk ***@***.***> wrote:

> There are plenty of reasons why a patch might not apply cleanly to the
> tree anymore without that patch being completely useless. I don't know this
> software, is the bug still a valid bug?
>

Sorry, I should have been more clear.  I believe the bug was that the
ebuilds were sharing a common init script, but when the 0.15.13 ebuild was
added an argument when calling munged that was not compatible with previous
versions.  The result was that the stable version was broken.  If the
change is not rebasing cleanly I think it's likely the problem no longer
exists because the newer versions have replaced the once broken stable
version.

**Comment by ajakk** [comment]
Well, if you think this is obsolete I guess we can close. Thanks!

**Pull request closed without merging**
