### PR TITLE
app-text/xindy: Fix building with perl-5.26, #622702

### PR DESCRIPTION
**Pull request by vaeth**

### CODE REVIEW

**Comment by aballier** [comment]
plz no revbump as this is a mere build fix

**Comment by aballier** [comment]
and squash then

**Comment by vaeth** [comment]
Last time I rebased my first commit (hence modifying its hash), the whole pull request has vanished. Might have been a bug in github. I will --force push now anyway.

**Comment by vaeth** [comment]
Done. Seems to work this time

**Comment by aballier** [comment]
merged, thanks!

**Pull request closed without merging**
