### PR TITLE
mongodb: bump to 4.0.20/4.2.10/4.4.1

### PR DESCRIPTION
**Pull request by hydrapolic**
4.2 changes:

````
--- mongodb-4.2.8.ebuild        2020-10-01 18:28:58.139406814 +0000
+++ mongodb-4.2.10.ebuild       2020-11-06 06:31:23.356505948 +0000
@@ -20,7 +20,7 @@
 
 LICENSE="Apache-2.0 SSPL-1"
 SLOT="0"
-KEYWORDS="amd64 ~arm64"
+KEYWORDS="~amd64 ~arm64"
 IUSE="debug kerberos libressl lto ssl test +tools"
 RESTRICT="!test? ( test )"
 
@@ -55,7 +55,7 @@
 
 PATCHES=(
        "${FILESDIR}/${PN}-4.2.0-fix-scons.patch"
-       "${FILESDIR}/${PN}-4.0.0-no-compass.patch"
+       "${FILESDIR}/${PN}-4.2.10-no-compass.patch"
 )
 
 S="${WORKDIR}/${MY_P}"
````

4.2 to 4.4 changes:
- add python 3.8/3.9 support
- require boost[nls] because /usr/include/boost/locale/utf.hpp is missing otherwise
- require >mongo-tools-100 with changed version numbering

### CODE REVIEW

**Comment by ultrabug** [comment]
@hydrapolic hi

did you by any chance get 4.4 to build?

we need to get rid of 3.6 and 4.0 for python2 cleanup

**Comment by hydrapolic** [comment]
> @hydrapolic hi
> 
> did you by any chance get 4.4 to build?
> 
> we need to get rid of 3.6 and 4.0 for python2 cleanup

Hello @ultrabug, maybe we should open a Jira ticket if Mongodb wants to backport py3 to 4.0? I was trying to login, but my password reset email haven't arrived yet.

Just trying 4.4.1.

**Comment by hydrapolic** [comment]
@ultrabug, https://jira.mongodb.org/browse/SERVER-52687

+ added mongodb 4.4.1.

````
[MongoDFixture:job1] Successfully stopped the mongod on port 20250.
[js_test:job1_fixture_teardown] 2020-11-09T13:44:15.035+0000 Finished the teardown of MongoDFixture (Job #1).
[executor:js_test:job1] 2020-11-09T13:44:15.036+0000 job1_fixture_teardown ran in 0.27 seconds: no failures detected.
[executor] 2020-11-09T13:44:15.037+0000 Threads are completed!
[executor] 2020-11-09T13:44:15.063+0000 Summary of latest execution: All 2055 test(s) passed in 421.26 seconds.
[resmoke] 2020-11-09T13:44:15.071+0000 ================================================================================
[resmoke] 2020-11-09T13:44:15.071+0000 Summary of core suite: All 2055 test(s) passed in 421.26 seconds.
[resmoke] 2020-11-09T13:44:15.071+0000 Exiting with code: 0
>>> Completed testing dev-db/mongodb-4.4.1

>>> Install dev-db/mongodb-4.4.1 into /var/tmp/portage/dev-db/mongodb-4.4.1/image
>>> Completed installing dev-db/mongodb-4.4.1 into /var/tmp/portage/dev-db/mongodb-4.4.1/image
````

**Comment by ultrabug** [comment]
Thanks a lot @hydrapolic

**Comment by hydrapolic** [comment]
Thanks @ultrabug

**Pull request closed without merging**
