### PR TITLE
Bump games-util/gamemode

### PR DESCRIPTION
**Pull request by kakra**

### CODE REVIEW

**Comment by kostadinsh** [comment]
I think explicitly enabling `-Dwith-pam-renicing=true` and `-Dwith-privileged-group=gamemode` is pointless? since they are already the default upstream. https://github.com/FeralInteractive/gamemode/blob/1.8/meson_options.txt. 
You could also move `-Dwith-examples` to the "main" configure options (i.e the ones that control both the native and multilib parts of the build) and put it behind USE=examples.

**Comment by kakra** [comment]
Thanks for reviewing.

> I think explicitly enabling `-Dwith-pam-renicing=true` and `-Dwith-privileged-group=gamemode` is pointless? since they are already the default upstream. https://github.com/FeralInteractive/gamemode/blob/1.8/meson_options.txt.

I made these explicit because we cannot rely on default behavior if this is integrated with existing system configuration (e.g. that group name). It also supports something like integrating with systemd and creating this group automatically via `sysusers.d` which we maybe want to prevent, too? We already rely on Gentoo's system (`acct-group/gamemode`).

> You could also move `-Dwith-examples` to the "main" configure options (i.e the ones that control both the native and multilib parts of the build) and put it behind USE=examples.

No, from my previous tests this cannot be done because this results in a double-install of some files and `ebuild` complains about that (at least back then when I tested this).

But I can put it behind an examples use flag although I wonder where the point is: Those examples are rather small.

To be clear: This is not about preventing installs of examples, it just prevents installing examples again in the other ABI case.

But both options mentioned above probably need to be moved to the native ABI phase. I'll check and correct this. Because `with-sd-bus-provider=no-daemon` is actually there to NOT install the daemon (and other files) for non-native ABI. Thanks for pointing me into that direction. :-)

I should also remove the pretend elogs from the 1.8 ebuild, it accidentally slipped through.

**Comment by kostadinsh** [comment]
> No, from my previous tests this cannot be done because this results in a double-install of some files and `ebuild` complains about that (at least back then when I tested this).
> 
> But I can put it behind an examples use flag although I wonder where the point is: Those examples are rather small.

This was just a merely suggestion of mine, the examples are indeed tiny. Up to you to decide what the best way to do it is.

**Comment by kakra** [comment]
Fixed the ebuild to no longer compile and install the example program by moving `with-examples` to the main meson args, turns out that `gamemode.ini` example has already been handled by `DOCS`.

Also moved common configuration parameters to the main meson args, so they are applied to both ABIs if needed.

I think we do not need to install example programs at all, it has been `gamemode-simulate-game` only which does nothing useful and even has no man page or help.

**Comment by kostadinsh** [comment]
A couple of notes: 

- 1.8.1 is out
- with `-Dwith_examples=false` the configuration example file does get installed, but it's compressed with bzip2 and is in `/usr/share/doc/gamemode-1.8.1/gamemode.ini.bz2`
- Apparently the user now *must* be in the `gamemode` group for even basic things like changing the CPU governor: https://github.com/FeralInteractive/gamemode/issues/452
- Can you backport this patch which fixes building with musl: https://github.com/FeralInteractive/gamemode/pull/454

**Comment by kakra** [comment]
> A couple of notes:
> 
> * 1.8.1 is out
> * with `-Dwith_examples=false` the configuration example file does get installed, but it's compressed with bzip2 and is in `/usr/share/doc/gamemode-1.8.1/gamemode.ini.bz2`

Yes, because `-Dwith_examples=false` prevents installing the example programs along with a default ini file. But we still install the example configuration file as documentation. This needs to be placed nowhere, it's not meant to go to `/etc` or something. It's there as a starting point.

> * Apparently the user now _must_ be in the `gamemode` group for even basic things like changing the CPU governor: [Gamemode 1.8.1 can't set CPU governor and GPU Optimisation FeralInteractive/gamemode#452](https://github.com/FeralInteractive/gamemode/issues/452)

I'm not even sure if that would make a difference (at least until now). The group was introduced to set nice levels (this patch was initially added by me). The bug report seems to mix up things: The policy rules may probably not load due to an installation/packaging error. The first makes an issue with running `cpugovctl`, the other just prevents running renice to raise priority. However, I think with modern systems, renice has mostly become useless anyways due to group scheduling: There's no point in raising the priority of all processes in a group if you don't raise priority of the group itself. My renice patch would need an update.

The real cause seems to be here: https://github.com/FeralInteractive/gamemode/commit/337f1b8a8e208b0e1b46d02abc86a52ce90f49af

I'm not sure why this has been merged. I assumed that only gamemode could call those helpers anyway. Introducing the group has only been a way around pam limits previously. Well, I think we could change the notes displayed to the user during install. But I don't get why such a change is introduced in a minor version update. It should have become 1.9 instead.

> * Can you backport this patch which fixes building with musl: [Fix build with musl FeralInteractive/gamemode#454](https://github.com/FeralInteractive/gamemode/pull/454)

I'm not convinced musl should actually be a thing for systems running gamemode: It is a small, alternative implementation of glibc targeted for embedded systems. Gentoo Hardened also offers it, and you probably don't game on such systems. If you feel like running on a musl system, you can place a patch in `/etc/portage/patches/games-util/gamemode`. We've seen previously what happens with carrying patches for too long. It probably solves itself because the next upstream version bump happens before this PR merges.

Putting all together, I'm currently not feeling like continue to maintain this package at all:

- pull requests are often ignored for a long time
- new versions appear even long before pull requests become merged
- there are new comments on closed bugs which makes it difficult for maintainers to discover the requests
- gamemode doesn't really make sense anymore with modern CPUs, kernel schedulers and configurations
- this starts to get out of control as new updates with breaking changes come up without this PR even being merged
- I personally don't use gamemode anymore because I see no real differences running with or without, except higher power consumption

I'll update this PR once more but if this PR still lingers around after the next upstream version bump, I'm not very inclined to continue maintaining this.

**Review by juippis — APPROVED** [review]
Sorry about the delay, and thanks! Got it before next upstream bump! ;)

**Comment by kakra** [comment]
> Sorry about the delay, and thanks! Got it before next upstream bump! ;)

Thanks and sorry for being a little grumpy. I know you got a long todo list... And it's not even your fault that different small things added together. Appreciate your work. :-)

**Pull request closed without merging**
