### PR TITLE
app-text/linuxdoc-tools-0.9.71: version bump

### PR DESCRIPTION
**Pull request by Coacher**
CC @gentoo/proxy-maint

### CODE REVIEW

**Comment by monsieurp** [comment]
I'll take it on.

**Comment by monsieurp** [comment]
Your ebuild is going boom.

>>> Creating Manifest for /home/monsieurp/gentoo/app-text/linuxdoc-tools
 * linuxdoc-tools-0.9.71.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                   [ ok ]
>>> Unpacking source...
>>> Unpacking linuxdoc-tools-0.9.71.tar.gz to /var/tmp/portage/app-text/linuxdoc-tools-0.9.71/work
>>> Source unpacked in /var/tmp/portage/app-text/linuxdoc-tools-0.9.71/work
 * ERROR: app-text/linuxdoc-tools-0.9.71::gentoo failed (prepare phase):
 *   The source directory '/var/tmp/portage/app-text/linuxdoc-tools-0.9.71/work/linuxdoc-tools-0.9.71' doesn't exist

**Comment by Coacher** [comment]
Indeed.
I am sorry. I should've tested with the actual snapshot instead of pulling the right commit.

**Comment by Coacher** [comment]
I've updated the PR to address the issue mentioned above.

**Comment by monsieurp** [comment]
Merged! :+1:

**Pull request closed without merging**
