### PR TITLE
net-dialup/freeradius: Review freeradius.service

### PR DESCRIPTION
**Pull request by geaaru**
Closes: https://bugs.gentoo.org/681696
Package-Manager: Portage-2.3.51, Repoman-2.3.12
Signed-off-by: Daniele Rondina <geaaru@gmail.com>

### CODE REVIEW

**Comment by candrews** [comment]
Rather than storing a systemd service in Gentoo, we should use the upstream supplied systemd service.

Can you install that instead?

**Comment by geaaru** [comment]
@candrews hi, thanks for your feedback. As described on IRC channel currently, freeradius.service from upstream isn't suitable for Gentoo:

* Debian version uses a different binary name and other unneeded options
* RedHat version uses unneeded options and configuration files not suitable for Gentoo.

I don't think that is correct to use Debian or RedHat version and then replace rows with sed.

As reported on IRC I will try to push a Gentoo directory to Freeradius upstream with our freeradius.service but for now, please move ahead my pr and close issue.

**Comment by candrews** [comment]
I think we should use upstream's service definitions, as then we get upstream's improvements/fixes automatically.

I looked over upstream's definitions at https://github.com/FreeRADIUS/freeradius-server/blob/release_3_0_18/debian/freeradius.service and https://github.com/FreeRADIUS/freeradius-server/blob/release_3_0_18/redhat/radiusd.service
There are some significant differences as compared to what you propose here, why is that?

- Upstream has `Type=notify`
- You propose `User=freeradius` and `Group=freeradius` while doesn't
- You propose `ReadOnlyDirectories` and `ReadWriteDirectories` - have you submitted PRs to upstream for those?
- And more

IMHO, it would be much better to use upstream's definition then patch/sed it or use systemd overrides (install a file into /etc/systemd/system/freeradius.service.d/override.conf with Gentoo specific overrides). And please submit any changes to upstream.

**Comment by geaaru** [comment]
Just a recap:
 * currently, I disabled `Type=notify` because is broken on 3.0.18 and 3.0.19 (I will patch this directly on 3.0.19. See https://github.com/FreeRADIUS/freeradius-server/pull/2698)
 * now I use freeradius.service from upstream with a patch (With security improvement)

**Comment by geaaru** [comment]
> Instead of renaming the ebuild, you should make it a new file. Removing old versions (even revisions) should be done as a separate commit.

Done, let me know if all is ok now. Thanks

**Pull request closed without merging**
