### PR TITLE
dev-cpp/notcurses: upgrade to 3.0.1

### PR DESCRIPTION
**Pull request by dankamongmen**
Your friendly weeklyish Notcurses update, done in two commits like you prefer.

### CODE REVIEW

**Comment by thesamesam** [comment]
Thanks as always!

**Comment by thesamesam** [comment]
... but it doesn't seem to install.

1. Not running tests?
```
>>> Source compiled.
>>> Test phase: dev-cpp/notcurses-3.0.1
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1_build"
No tests found. Skipping.
>>> Completed testing dev-cpp/notcurses-3.0.1
```

Try it yourself with ```ebuild ... clean test install```.

2. Doesn't install for me.
```
-- Installing: /var/tmp/portage/dev-cpp/notcurses-3.0.1/image/usr/lib64/libnotcurses++.so
!!! doman: ../tfman.1 does not exist
 * ERROR: dev-cpp/notcurses-3.0.1::gentoo failed (install phase):
 *   doman failed
 *
 * If you need support, post the output of `emerge --info '=dev-cpp/notcurses-3.0.1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-cpp/notcurses-3.0.1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/dev-cpp/notcurses-3.0.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-cpp/notcurses-3.0.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1'
 * S: '/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1'
 * QA Notice: file does not exist:
 *
 * 	doman: ../tfman.1 does not exist
```

**Comment by dankamongmen** [comment]
> ... but it doesn't seem to install.
> 
> 1. Not running tests?
> 
> ```
> >>> Source compiled.
> >>> Test phase: dev-cpp/notcurses-3.0.1
>  * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1"
>  * Build directory  (BUILD_DIR):     "/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1_build"
> No tests found. Skipping.
> >>> Completed testing dev-cpp/notcurses-3.0.1
> ```
> 
> Try it yourself with `ebuild ... clean test install`.
> 
> 2. Doesn't install for me.
> 
> ```
> -- Installing: /var/tmp/portage/dev-cpp/notcurses-3.0.1/image/usr/lib64/libnotcurses++.so
> !!! doman: ../tfman.1 does not exist
>  * ERROR: dev-cpp/notcurses-3.0.1::gentoo failed (install phase):
>  *   doman failed
>  *
>  * If you need support, post the output of `emerge --info '=dev-cpp/notcurses-3.0.1::gentoo'`,
>  * the complete build log and the output of `emerge -pqv '=dev-cpp/notcurses-3.0.1::gentoo'`.
>  * The complete build log is located at '/var/tmp/portage/dev-cpp/notcurses-3.0.1/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/dev-cpp/notcurses-3.0.1/temp/environment'.
>  * Working directory: '/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1'
>  * S: '/var/tmp/portage/dev-cpp/notcurses-3.0.1/work/notcurses-3.0.1'
>  * QA Notice: file does not exist:
>  *
>  * 	doman: ../tfman.1 does not exist
> ```

ack, i missed this, sorry! i'll look into it ASAP.

**Comment by thesamesam** [comment]
no problem, thank you!

**Comment by dankamongmen** [comment]
`tfman.1` wasn't being installed because it wasn't being included in the documentation tarball. this has been fixed.

regarding the tests, i think i needed to change `multilib_src_tests` to `cmake-multilib_src_tests`. verifying now.

**Comment by dankamongmen** [comment]
indeed, that appears to be the case

**Pull request closed without merging**
