### PR TITLE
x11-plugins/pidgin-gnome-keyring: new package

### PR DESCRIPTION
**Pull request by mkszuba**
By default Pidgin/Purple store saved passwords in plain text in their configuration files. This plug-in makes it possible to store passwords in a keyring instead, which is somewhat more secure.

I am interested in becoming the proxy maintainer of this package.

Gentoo-Bug: 581422

### CODE REVIEW

**Comment by idella** [comment]
SRC_URI="https://github.com/aebrahim/pidgin-gnome-keyring/archive/${PV}.tar.gz -> ${P}.tar.gz" ->  SRC_URI="https://github.com/aebrahim/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"

IUSE="" ebing emoty can be taken out

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by rindeal** [comment]
> SRC_URI="https://github.com/aebrahim/pidgin-gnome-keyring/archive/${PV}.tar.gz -> ${P}.tar.gz" -> SRC_URI="https://github.com/aebrahim/${PN}/archive/${PV}.tar.gz -> ${P}.tar.gz"

Why? Variables are for strings which vary.

**Comment by idella** [comment]
${PN} for a set package is not going to vary.  There are more points to come yet.

**Pull request closed without merging**
