### PR TITLE
media-libs/libpulse: Fix build with lld and backport critical fixes from upstream

### PR DESCRIPTION
**Pull request by i-garrison**
Pulseaudio uses the same linker version script for all library variants, so a few symbols remain undefined for some variants. This breaks buid with new lld which defaults to errors with undefined symbols in linker version scripts.

Fix this by adding `-Wl,--undefined-version` to linker flags.
See also https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=274111

Closes: https://bugs.gentoo.org/915207

Also backport a few critical fixes from upstream.

### CODE REVIEW

**Comment by thesamesam** [comment]
Whlie at it, could you fix https://bugs.gentoo.org/914882?

**Comment by i-garrison** [comment]
> Whlie at it, could you fix https://bugs.gentoo.org/914882?

I can pick that here too but how about doing a bump for `pulseaudio-16.99.1` instead? That would bring other future fixes + there will be `webrtc-audio-processing-1` change.

**Comment by i-garrison** [comment]
> Whlie at it, could you fix https://bugs.gentoo.org/914882?

Well upstream `webrtc-audio-processing-1` changes are not finalized yet, so I decided to backport a bit more critical changes on top of `pulseaudio-16.1` to both daemon and libpulse - please have a look.

**Comment by thesamesam** [comment]
> > Whlie at it, could you fix [bugs.gentoo.org/914882](https://bugs.gentoo.org/914882)?
> 
> I can pick that here too but how about doing a bump for `pulseaudio-16.99.1` instead? That would bring other future fixes + there will be `webrtc-audio-processing-1` change.

Fine with me when you think it's ready - maybe when the webrtc stuff is finalised.

**Pull request closed without merging**
