### PR TITLE
sys-cluster/openmpi: Drop versions depending on >=virtual/jre-1.6

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by Arfrever** [comment]
If these versions fail with newer Java, then you might just drop `java` USE flag in them.

**Comment by scardracs** [comment]
Not a good idea to drop openmpi so lightly, see https://bugs.gentoo.org/828032#c9

**Comment by vaukai** [comment]
> Not a good idea to drop openmpi so lightly, see https://bugs.gentoo.org/828032#c9

I see.  Could you then switch them to `java 1.8:*` please?

**Comment by scardracs** [comment]
> > Not a good idea to drop openmpi so lightly, see https://bugs.gentoo.org/828032#c9
> 
> I see.  Could you then switch them to `java 1.8:*` please?

I can't actually, I need cluster team to look at it

**Pull request closed without merging**
