### PR TITLE
kde-misc/latte-dock : version bump to 0.7.0 and some minor changes to…

### PR DESCRIPTION
**Pull request by Petross404**
… the dependencies

### CODE REVIEW

**Comment by a17r** [comment]
Thanks for the fixes! One QA issue (should be reported and fixed upstream) during install remains:

```
 * QA Notice: This package installs one or more .desktop files that do not
 * pass validation.
 * 
 *      /usr/share/applications/org.kde.latte-dock.desktop: error: value "0.7.0" for key "Version" in group "Desktop Entry" is not a known version
```

It seems they misunderstood the meaning of the `Value` entry:
``Version of the Desktop Entry Specification that the desktop entry conforms with. Entries that confirm with this version of the specification should use 1.1. Note that the version field is not required to be present.``
https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s05.html

For our 0.7.0 release, you should just remove the line while in src_prepare().

**Comment by Petross404** [comment]
> For our 0.7.0 release, you should just remove the line while in src_prepare(). 

So I will write a sed that will remove the whole line and then I will make another one commit? Or the changes have to exist in one single commit?

**Comment by a17r** [comment]
Yes, no need for a separate commit - you can git amend the existing one after you're done with the changes.

**Comment by Petross404** [comment]
Based on this [commit](https://github.com/psifidotos/Latte-Dock/commit/83c3502384fb46da9cd093a5e9547144b35dd862) I wrote this :  

`src_prepare() {  `
 `	cmake-utils_src_prepare  `
 `	cd app/  `
 `	sed -i 's/Version=/X-KDE-PluginInfo-Version=/g' org.kde.latte-dock.desktop.cmake || die "Sed  `
`failed"  `
`}`

The indentation sucks, but you get the point. No QA Notice, no nothing. I will push the ebuild and I hope it's good. I will be gone for a few days, so I won't be able to fix it if something is wrong.

**Comment by a17r** [comment]
Thanks! I've simplified your sed command and fixed git summary so that it fits with our git workflow policies.

**Comment by Petross404** [comment]
Nice! :)

**Pull request closed without merging**
