### PR TITLE
dev-python/widgetsnbextension: Version bump to 3.5.1

### PR DESCRIPTION
**Pull request by marbre**
Copy of 3.4.2

### CODE REVIEW

**Comment by marbre** [comment]
Somebody willing to comment or even to merge?

**Comment by juippis** [comment]
Not saying it will help with sci project, but generally, if you aren't receiving attention in Github you should always open a bug. Some of the projects / maintainers don't look at Github notifications at all. 
You can then link your PR to the bug by using formats explained in here, 
https://www.gentoo.org/glep/glep-0066.html#commit-messages

**Comment by marbre** [comment]
@heroxbd May I ping you on this PR?

**Comment by heroxbd** [comment]
> @heroxbd May I ping you on this PR?

Thanks!  We have ditched Python 3.5, please remove it.

**Comment by juippis** [comment]
0f05726576afd490853595a33b2e867fb97ac2a2

**Pull request closed without merging**
