### PR TITLE
sys-fs/rar2fs: Bump to 1.29.1

### PR DESCRIPTION
**Pull request by fdegros**
Also remove old rar2fs-1.27.2-r1.

### CODE REVIEW

**Comment by fdegros** [comment]
Ping. What's the next step for this pull request?

**Comment by 00-matt** [comment]
There are lots of pull requests from proxied maintainers but only a few people able to merge them. Just have to wait while they get through all of the PRs before this one :)

**Comment by fdegros** [comment]
Ping. What's the next step for this pull request?

**Comment by thesamesam** [comment]
Sorry, just been trying to get through various backlog(s). LGTM.

**Comment by fdegros** [comment]
Thanks.

I don't know what to do about the compressed man page. Is it a real issue? Can it be fixed in a separate change, after the upgrade to 1.29.1?

**Comment by thesamesam** [comment]
The idea is that Portage should control compression to make it optional or allow swapping out with a different algorithm (via a different tool, or whatever). But yeah, you've waited ages, I don't think it's new, we'll fix it later.

**Comment by fdegros** [comment]
Thanks.

**Pull request closed without merging**
