### PR TITLE
dev-java/jdbc-postgresql: add 42.7.4 and dependencies

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by fordfrog — COMMENTED** [review]
```
>>> Test phase: dev-java/jetbrains-annotations-24.1.0
javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:jetbrains-annotations.jar @test_sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
4 warnings
javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jetbrains-annotations.jar --module-version 24.1.0 ./module-info/src/main/java/module-info.java
warning: [options] system modules path not set in conjunction with -source 9
1 warning
JUnit version 4.13.3-SNAPSHOT
.E
Time: 0,002
There was 1 failure:
1) initializationError(org.jetbrains.annotations.TestOnly)
org.junit.runners.model.InvalidTestClassError: Invalid test class 'org.jetbrains.annotations.TestOnly':
  1. Test class should have exactly one public constructor
  2. No runnable methods
	at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
	at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
	at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
	at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
	at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
	at org.junit.runner.Computer.getRunner(Computer.java:50)
	at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
	at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
	at org.junit.runners.Suite.<init>(Suite.java:81)
	at org.junit.runner.Computer$2.<init>(Computer.java:33)
	at org.junit.runner.Computer.getSuite(Computer.java:28)
	at org.junit.runner.Request.classes(Request.java:77)
	at org.junit.runner.JUnitCommandLineParseResult.createRequest(JUnitCommandLineParseResult.java:116)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:81)
	at org.junit.runner.JUnitCore.runMain(JUnitCore.java:40)
	at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 1,  Failures: 1
```

**Comment by vaukai** [comment]
> FAILURES!!!
> Tests run: 1,  Failures: 1

`tests` in `JAVA_PKG_IUSE` was left over from the template (`app-vim/gentoo-syntax`), i just removed it.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — COMMENTED** [review]
```
>>> Install dev-java/stringprep-2.2 into /var/tmp/portage/dev-java/stringprep-2.2/image
 * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/stringprep.jar
 * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/nameprep.jar
 * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/saslprep.jar
```

**Comment by fordfrog** [comment]
`dev-java/jetbrains-annotations` has been merged

**Comment by vaukai** [comment]
> ```
> >>> Install dev-java/stringprep-2.2 into /var/tmp/portage/dev-java/stringprep-2.2/image
>  * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/stringprep.jar
>  * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/nameprep.jar
>  * Overwriting /var/tmp/portage/dev-java/stringprep-2.2/image/usr/share/stringprep/lib/saslprep.jar
> ```

@fordfrog indeed, i have to rework the `src_install()` section.

for this package i also have another version using the `switch to multi-module compilation` approach but i was hesitant to put it here since it lifts `virtual/jre` from `1.8` to `11`. how do you think about going that way?

**Comment by fordfrog** [comment]
> for this package i also have another version using the `switch to multi-module compilation` approach but i was hesitant to put it here since it lifts `virtual/jre` from `1.8` to `11`. how do you think about going that way?

what's the reason for requiring for runtime higher version of java just because the package is built a different way?

**Comment by vaukai** [comment]
> > for this package i also have another version using the `switch to multi-module compilation` approach but i was hesitant to put it here since it lifts `virtual/jre` from `1.8` to `11`. how do you think about going that way?
> 
> what's the reason for requiring for runtime higher version of java just because the package is built a different way?

@fordfrog the short answer is: 
like `cdi-api-4.0.1-r3` i did not get it to work with `-target 8`, most probably because it uses `--module-source-path`.
there i've left a comment in https://bugs.gentoo.org/923599#c10.

i am still in an early stage of playing with `--module-source-path` same as with `jdeps --create-module-info`, 
still many options to try, many questions still open for me. 
- ran into problems when trying it for `dev-java/asm`, 
- `commons-logging `seems to need `module-info.java` with optional `log44*`
- dont understand `pattern method` 
- is there any not too complicated way to have it support `-target 8`?

**Comment by vaukai** [comment]
> @vaukai modules were introduced in java 9, so anything modules related must use at least java 9 and target 9. still, the rest of the class can be target 8 if the classes of that package are designed so.

@fordfrog i am aware how `java-pkg-simplle` does it separately per each `-target` value but haven't yet figured out how to get that working for `multi-module` compilation. for this reason `stringprep` is offered here using the old way which handes each mudule separately.

getting `multi-release support` working with`multi-module` compilation and `jdeps --generate-module-info` where needed is something i think is worth to elaborate. no idea if it would ever work.

**Comment by vaukai** [comment]
@fordfrog Could you pls proceed with this PR? Except not having tests all should be ok now.

**Pull request closed without merging**
