### PR TITLE
net-misc/rwhoisd: fix build for clang16

### PR DESCRIPTION
**Pull request by Schievel1**
This is another beauty, >14000 line patch...

Draft because I wanna see if I can fix the other open bugs for this as well.  

Closes: https://bugs.gentoo.org/725194
Closes: https://bugs.gentoo.org/861830
Closes: https://bugs.gentoo.org/870940
Closes: https://bugs.gentoo.org/893906

Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

### CODE REVIEW

**Comment by juippis** [comment]
Remember to ping us when you want to process this PR, moving it out as a draft.

**Comment by Schievel1** [comment]
yes, thanks for reminding me of this. Right now I am in a bit of private trouble. I will continue this sooner or later.

**Comment by Schievel1** [comment]
I think I am done here. 
https://bugs.gentoo.org/740790 I can not reproduce. I don't know why llvm-strings is not available on the tinderbox as I think it is always included in llvm. 
https://bugs.gentoo.org/715310 Is some musl thing. I don't use musl on my system.

**Comment by Schievel1** [comment]
@juippis please review

**Review by juippis — COMMENTED** [review]
This works with gcc, but with clang-16 I get:
```
daemon.c:108:3: error: void function 'sigchld_handler' should not return a value
      [-Wreturn-type]
  return 0;
  ^      ~
daemon.c:117:3: error: void function 'sighup_handler' should not return a value
      [-Wreturn-type]main.c:173:5: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
clang -O -DFACILITY=LOG_MAIL     -DHOSTS_ACCESS -DPARANOID  -DGETPEERNAME_BUG -DBROKEN_FGETS -DLIBC_CALLS_STRTOK   -DDAEMON_UMASK=022 -DREAL_DAEMON_DIR=\"/\"   -DSEVERITY=LOG_INFO  -DRFC931_TIMEOUT=10  -DHOSTS_DENY=\"/etc/hosts.deny\" -DHOSTS_ALLOW=\"/etc/hosts.allow\"   -         DUSE_STRERROR  -Dvsyslog=myvsyslog -DALWAYS_HOSTNAME -DHAVE_IPV6 -DUSE_GETHOSTBYNAME2 -c update.c
    chdir(orig_cwd);
    ^~~~~ ~~~~~~~~

  return 0;
  ^      ~
daemon.c:127:3: error: void function 'exit_handler' should not return a value
      [-Wreturn-type]
  return 0;
  ^      ~
main.c:211:3: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
  getcwd(orig_cwd, sizeof(orig_cwd));
  ^~~~~~ ~~~~~~~~~~~~~~~~~~~~~~~~~~
daemon.c:273:66: warning: passing 'int *' to parameter of type 'socklen_t *'
      (aka 'unsigned int *') converts between pointers to integer types with different sign
      [-Wpointer-sign]
    newsockfd = accept(sockfd, (struct sockaddr *) &client_addr, &clilen);
                                                                 ^~~~~~~
/usr/include/sys/socket.h:307:28: note: passing argument to parameter '__addr_len'
      here
                   socklen_t *__restrict __addr_len);
                                         ^
daemon.c:325:9: warning: ignoring return value of function declared with
      'warn_unused_result' attribute [-Wunused-result]
        nice(get_child_priority());
        ^~~~ ~~~~~~~~~~~~~~~~~~~~
2 warnings and 3 errors generated.
1 warning generated.
make[1]: *** [Makefile:92: daemon.o] Error 1
```

**Comment by Schievel1** [comment]
Is `-Werror=return-type` set by default on clang15? I haven't altered my clang setup at all and these are warnings for me. 
I only changed what is written in https://wiki.gentoo.org/wiki/Modern_C_porting#How_do_I_reproduce_these_bugs.3F

Anyway, I will have a look and fix these as well.

**Comment by thesamesam** [comment]
I think maybe >= Clang 14 or Clang 15 sets -Werror=return-type. Not sure.

**Pull request closed without merging**
