### PR TITLE
dev-python/elasticsearch-curator: bump to 4.2.5

### PR DESCRIPTION
**Pull request by hydrapolic**
Tests passed with py2.7/3.4/3.5

### CODE REVIEW

**Comment by gktrk** [comment]
I have jre:1.8 installed, and tests fail for me :(

```
>>> Test phase: dev-python/elasticsearch-curator-4.2.5
 * python2_7: running distutils-r1_run_phase python_test
* Home for VM 'icedtea-bin-7' does not exist: //usr/lib/jvm/icedtea-bin-7
* Invalid System VM: icedtea-bin-7
 * ERROR: dev-python/elasticsearch-curator-4.2.5::gentoo failed (test phase):
 *   (no error message)
 * 
 * Call stack:
 *     ebuild.sh, line  115:  Called src_test
 *   environment, line 2721:  Called distutils-r1_src_test
 *   environment, line  850:  Called _distutils-r1_run_foreach_impl 'python_test'
 *   environment, line  341:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_test'
 *   environment, line 2198:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1491:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_test'
 *   environment, line 1489:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_test'
 *   environment, line  541:  Called distutils-r1_run_phase 'python_test'
 *   environment, line  782:  Called python_test
 *   environment, line 2576:  Called die
 * The specific snippet of code:
 *       "${ES}/bin/elasticsearch" -d -p "${PID}" -Edefault.path.repo=/ || die;
 * 
 * If you need support, post the output of `emerge --info '=dev-python/elasticsearch-curator-4.2.5::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-python/elasticsearch-curator-4.2.5::gentoo'`.
 * The complete build log is located at '/var/log/portage/dev-python:elasticsearch-curator-4.2.5:20170115-045351.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/work/curator-4.2.5'
 * S: '/var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/work/curator-4.2.5'
```

**Comment by hydrapolic** [comment]
Hello,

from the output:
* Home for VM 'icedtea-bin-7' does not exist: //usr/lib/jvm/icedtea-bin-7
* Invalid System VM: icedtea-bin-7

I tested with oracle-jre-8. Can you please test with oracle?

Looking at their travis it seems they only use oracle-jre-8, so if it helps for you, we may need to change the dep to oracle-jre.

**Comment by gktrk** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=605802

**Comment by gktrk** [comment]
I'll test it on oracle tomorrow. My current machine doesn't even have enough memory for the tests :)

**Comment by gktrk** [comment]
It fails differently on the other box with :1.8

```
>>> Test phase: dev-python/elasticsearch-curator-4.2.5
 * python2_7: running distutils-r1_run_phase python_test
 * Waiting for Elasticsearch                                                                                                                                                   [ !! ]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by hydrapolic** [comment]
Now there is hard limit on oracle-8.

That error you receive seems like related to java itself, are you sure oracle-jre/jdk-8 is active?

Just tested with:
# java -version
java version "1.8.0_112"
Java(TM) SE Runtime Environment (build 1.8.0_112-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.112-b15, mixed mode)

Related link:
https://github.com/elastic/elasticsearch/issues/17584

**Comment by gktrk** [comment]
```
$ java -version
java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

:\

```
>>> Test phase: dev-python/elasticsearch-curator-4.2.5
 * python2_7: running distutils-r1_run_phase python_test
 * Waiting for Elasticsearch                                                                                                     [ !! ]
Exception in thread "main" java.lang.UnsupportedClassVersionError: org/elasticsearch/bootstrap/Elasticsearch : Unsupported major.minor version 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
```

**Comment by hydrapolic** [comment]
Is oracle-8 set globally or is it just for your user?

`# eselect java-vm list`

**Comment by gktrk** [comment]
Right, it was set for the user. I set it for the system and it's still waiting. I realized that elasticsearch is able to start successfully, but it doesn't write anything to the log files, so the ebuild hopelessly looks for `Elasticsearch started` which never happens. If I start it by hand without the `--daemon` option, it does write to the logs, but still nothing in the logs to match that string:

```
[2017-01-24T19:13:25,090][WARN ][o.e.d.s.g.GroovyScriptEngineService] [groovy] scripts are deprecated, use [painless] scripts instead
[2017-01-24T19:13:24,483][INFO ][o.e.n.Node               ] [] initializing ...
[2017-01-24T19:13:24,525][INFO ][o.e.e.NodeEnvironment    ] [7GFb5sU] using [1] data paths, mounts [[/var/tmp/portage (portage_tmp)]], net usable_space [27.7gb], net total_space [28.1gb], spins? [no], types [tmpfs]
[2017-01-24T19:13:24,526][INFO ][o.e.e.NodeEnvironment    ] [7GFb5sU] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-01-24T19:13:24,526][INFO ][o.e.n.Node               ] node name [7GFb5sU] derived from node ID [7GFb5sUaSP-k7cKlzB3woA]; set [node.name] to override
[2017-01-24T19:13:24,528][INFO ][o.e.n.Node               ] version[5.1.1], pid[28520], build[5395e21/2016-12-06T12:36:15.409Z], OS[Linux/4.8.8/amd64], JVM[Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [aggs-matrix-stats]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [ingest-common]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [lang-expression]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [lang-groovy]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [lang-mustache]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [lang-painless]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [percolator]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [reindex]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [transport-netty3]
[2017-01-24T19:13:24,977][INFO ][o.e.p.PluginsService     ] [7GFb5sU] loaded module [transport-netty4]
[2017-01-24T19:13:24,978][INFO ][o.e.p.PluginsService     ] [7GFb5sU] no plugins loaded
[2017-01-24T19:13:26,218][INFO ][o.e.n.Node               ] initialized
[2017-01-24T19:13:26,218][INFO ][o.e.n.Node               ] [7GFb5sU] starting ...
[2017-01-24T19:13:26,336][INFO ][o.e.t.TransportService   ] [7GFb5sU] publish_address {127.0.0.1:9300}, bound_addresses {[::1]:9300}, {127.0.0.1:9300}
[2017-01-24T19:13:26,343][WARN ][o.e.b.BootstrapCheck     ] [7GFb5sU] max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
[2017-01-24T19:13:26,343][WARN ][o.e.b.BootstrapCheck     ] [7GFb5sU] max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
[2017-01-24T19:13:29,408][INFO ][o.e.c.s.ClusterService   ] [7GFb5sU] new_master {7GFb5sU}{7GFb5sUaSP-k7cKlzB3woA}{4y0p4dfNT_CzDzSbMrJ_Bw}{127.0.0.1}{127.0.0.1:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-24T19:13:29,434][INFO ][o.e.h.HttpServer         ] [7GFb5sU] publish_address {127.0.0.1:25123}, bound_addresses {[::1]:25123}, {127.0.0.1:25123}
[2017-01-24T19:13:29,437][INFO ][o.e.n.Node               ] [7GFb5sU] started
[2017-01-24T19:13:29,443][INFO ][o.e.g.GatewayService     ] [7GFb5sU] recovered [0] indices into cluster_state
[2017-01-24T19:13:54,667][INFO ][o.e.n.Node               ] [7GFb5sU] stopping ...
[2017-01-24T19:13:54,690][INFO ][o.e.n.Node               ] [7GFb5sU] stopped
[2017-01-24T19:13:54,690][INFO ][o.e.n.Node               ] [7GFb5sU] closing ...
[2017-01-24T19:13:54,703][INFO ][o.e.n.Node               ] [7GFb5sU] closed
```

Maybe the log format has changed?

**Comment by gktrk** [comment]
If I start the server on a separate shell in foreground and disable the code that starts elasticsearch in the ebuild, it tests just fine :|

**Comment by gktrk** [comment]
Nevermind, I actually have no idea what is going on. elasticsearch wouldn't start from the ebuild environment for some reason. Even if I don't change anything in the ebuild, and run elasticsearch from a different shell using `/var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/work/elasticsearch-5.1.1/bin/elasticsearch -d -p /var/tmp/portage/dev-python/elasticsearch-curator-4.2.5/work/elasticsearch-5.1.1/elasticsearch.pid -Edefault.path.repo=/`, everything works fine.

**Comment by gktrk** [comment]
For the record, I can confirm that the tests also pass with icedtea:8 successfully, if I start elasticsearch from a separate shell.

**Comment by hydrapolic** [comment]
Hello,
the string didn't change, you have the line in the log:
[2017-01-24T19:13:29,437][INFO ][o.e.n.Node               ] [7GFb5sU] started

I had the same problem as you describe, ES is started, but nothing in 
the logs. I thought it's just my ~amd64 machine, so I started a VM on a 
separate server and it worked there.

Maybe I can check with other ES version. Seems to be portage/sandbox 
related.

**Comment by hydrapolic** [comment]
I've changed the requirement to jre:1.8 again and added test instruction:
FEATURES="test -usersandbox" emerge dev-python/elasticsearch-curator

This seems to work. Can you please try if it works on your machine?

**Comment by gktrk** [comment]
Yup, disabling the `usersandbox` works well for me for both icedtea and oracle jre:1.8. I can also confirm that jre:1.7 fails miserably.

**Comment by hydrapolic** [comment]
Yes, for versions 5+ java 8 is required (https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html#jvm-version).

Thanks for testing.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/96dd044...7d589ef. Thanks!

**Comment by hydrapolic** [comment]
Thank you @gktrk

**Pull request closed without merging**
