### PR TITLE
app-portage/pacvis: New package

### PR DESCRIPTION
**Pull request by bgloyer**
port of pacvis to Gentoo.  pacvis shows a dependency graph of packages
as seen by portage

Package-Manager: Portage-2.3.69, Repoman-2.3.16

-------------------------------

This is Bug 692590.

This is my first try at this.  Let me know if something is wrong.

### CODE REVIEW

**Comment by bgloyer** [comment]
There are a few notes and a draft wiki article at:

https://wiki.gentoo.org/wiki/User:Garbanzo/PacVis

**Comment by bgloyer** [comment]
An example graph for the original pacvis (not by me) from Arch Linux is up at:

https://pacvis.farseerfc.me/

The Gentoo version is similar.

**Comment by bgloyer** [comment]
pacvis was added to the [GURU](https://wiki.gentoo.org/wiki/Project:GURU) repository

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by ajakk** [comment]
Thank you for your work on this! Closing here in favor of the GURU version.

**Pull request closed without merging**
