### PR TITLE
dev-util/visualvm: add 2.1.9

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog the `nb190_platform_20231030.zip` as from `2.1.8` seems no longer available in `2.1.9`
could that part be completely dropped?

**Comment by fordfrog** [comment]
> @fordfrog the `nb190_platform_20231030.zip` as from `2.1.8` seems no longer available in `2.1.9` could that part be completely dropped?

well, the installation process says it's needed: https://github.com/oracle/visualvm?tab=readme-ov-file#configure-the-dependencies

**Comment by fordfrog** [comment]
i think 2.1.9 commits should be squashed into one. and that revbump unfortunatelly does not resolve the slot change issue, as it just wants to install the revbump to a new slot keeping the old version, which will again cause a conflict.

**Comment by vaukai** [comment]
> i think 2.1.9 commits should be squashed into one. and that revbump unfortunatelly does not resolve the slot change issue, as it just wants to install the revbump to a new slot keeping the old version, which will again cause a conflict.

then we should keep SLOT="7"

**Comment by fordfrog** [comment]
> then we should keep SLOT="7"

i think we can get rid of the slot once we have only one version in the tree, doing a revbump with removal of the old version, like you did for `ant-ivy`.

**Comment by vaukai** [comment]
> > then we should keep SLOT="7"
> 
> i think we can get rid of the slot once we have only one version in the tree, doing a revbump with removal of the old version, like you did for `ant-ivy`.

will do this within the next days and will try to combine it with updates of `owasp-java-encoder` and `jmc`.

**Comment by fordfrog** [comment]
we first need to get the new version stabilized and the old removed i think.

**Comment by vaukai** [comment]
> we first need to get the new version stabilized and the old removed i think.

that would give us more time for the next step.  -> https://github.com/gentoo/gentoo/pull/37928 
also https://github.com/gentoo/gentoo/pull/37748 would fit here i guess.

**Pull request closed without merging**
