### PR TITLE
dev-python/QDarkStyle: A dark style sheet for QtWidgets application

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
New dependency of dev-python/spyder-4.0.0

Breaking up PR into smaller parts: https://github.com/gentoo/gentoo/pull/13988

Bug: https://bugs.gentoo.org/702458
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@riseup.net>
Package-Manager: Portage-2.3.81, Repoman-2.3.20

### CODE REVIEW

**Comment by hartwork** [comment]
I believe we'd want lowercase `dev-python/qdarkstyle` for a package name.

**Comment by AndrewAmmerlaan** [comment]
> I believe we'd want lowercase `dev-python/qdarkstyle` for a package name.

I could do that, but I'd have to hardcode the SRC_URI to:
``
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/QDarkStyle-${PV}.tar.gz"
``
Instead of:
``
SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"
``
I'd also have to manually specify `S={$WORK}/QDarkStyle-{$PV}

**Comment by hartwork** [comment]
> > I believe we'd want lowercase `dev-python/qdarkstyle` for a package name.
> 
> I could do that, but I'd have to hardcode the SRC_URI to:
> `SRC_URI="mirror://pypi/${PN:0:1}/${PN}/QDarkStyle-${PV}.tar.gz"`
> Instead of:
> `SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"`
> I'd also have to manually specify `S={$WORK}/QDarkStyle-{$PV}

Yes. We have `MY_PN`, `MY_PV`, `MY_P` in this case, see some existing ebuilds — plenty examples that use it. 


> Would that be better?

It would not be super pretty but it's a standard approach dealing with difference in naming where needed.

Maybe ignore my request for a lowercase name until supported by others though, it's more common already than I believed:
```console
# eix --only-names | grep '[A-Z]' | wc -l
1962
```
Sorry for the noise.

**Comment by juippis** [comment]
> > I believe we'd want lowercase `dev-python/qdarkstyle` for a package name.

+1 from me. 

> 
> I could do that, but I'd have to hardcode the SRC_URI to:
> `SRC_URI="mirror://pypi/${PN:0:1}/${PN}/QDarkStyle-${PV}.tar.gz"`

Doesn't really matter. The `PV` is the moving part when making new versions.

> Instead of:
> `SRC_URI="mirror://pypi/${PN:0:1}/${PN}/${P}.tar.gz"`
> I'd also have to manually specify `S={$WORK}/QDarkStyle-{$PV}`

Rather have one extra line in ebuild than everyone looking at ugly `PN` ;)

**Pull request closed without merging**
