### PR TITLE
media-video/qgifer: opencv3 slot depedency

### PR DESCRIPTION
**Pull request by ChaosEngine**
I've fixed dependency to be from specific slot rather than version number. Seems to be more gentoo way.
Just fixing my commit issue from bugzilla by Amadeusz Żołnowski

### CODE REVIEW

**Comment by monsieurp** [comment]
Hello and thanks a lot for the PR. There are however some minors change that must be done. Commit messages have to follow the following format: "cat/package: message".

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
@ChaosEngine you have to edit your commits with git and push again, and not the PR itself actually. Does it make sense?

**Comment by ChaosEngine** [comment]
@monsieurp Hope now it is ok. I'm stll a newbie to git(hub) and pushing signed PR. Especially with lots of data to cover from https://wiki.gentoo.org/wiki/Gentoo_git_workflow

**Pull request merged**
