### PR TITLE
kde-apps/kalgebra: fix LICENSE

### PR DESCRIPTION
**Pull request by mm1ke**
Package-Manager: Portage-3.0.14, Repoman-3.0.2
Signed-off-by: Michael Mair-Keimberger <mmk@levelnine.at>

Regarding LICENSE: I've checked some sourcefiles (for example: https://github.com/KDE/kalgebra/blob/master/src/main.cpp) and they all say: `...as published by the Free Software Foundation; either version 2 of the License, or (at your option) any later version.`

### CODE REVIEW

**Comment by a17r** [comment]
Please split it in two separate commits. I started an inquiry upstream about the whereabouts of kalgebra website, I don't think it is correct to use kalgebramobile instead.

**Review by ConiKost — APPROVED** [review]

**Comment by ConiKost** [comment]
Ok, won't commit that ;-)

**Comment by ConiKost** [comment]
> 
> 
> Please split it in two separate commits. I started an inquiry upstream about the whereabouts of kalgebra website, I don't think it is correct to use kalgebramobile instead.

The mobile homepage at least links to the normal application, but also provides a mobile application. The upstream Repo seems to have both included.

**Comment by a17r** [comment]
I think it is an upstream mistake and after reporting upstream you might look at a broken website on Monday already.

**Comment by ConiKost** [comment]
> 
> 
> I think it is an upstream mistake and after reporting upstream you might look at a broken website uri on Monday already.

Let's see, what they say about your inquery :-)

But https://apps.kde.org/ lists that as mobile, normal seems to be gone.
According to archive.org, this seems to be longer the case its not there anymore.

**Comment by a17r** [comment]
If anything, the normal page should link to some mobile bits, not the other way round.

**Comment by mm1ke** [comment]
I've updated this PR to only fix the LICENSE.
Lets see how upstream decides, we still can fix the website later on if needed.

**Pull request closed without merging**
