### PR TITLE
dev-util/rtags-2.33: New ebuild

### PR DESCRIPTION
**Pull request by Flowdalic**
Signed-off-by: Florian Schmaus <flo@geekplace.eu>
Closes: https://bugs.gentoo.org/577544
Package-Manager: Portage-2.3.69, Repoman-2.3.16

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by sergeyklay** [comment]
ping @Flowdalic :)

**Comment by ajakk** [comment]
Closing in favor of adding to GURU. Please do so if still interested!

**Comment by Flowdalic** [comment]
I've updated the rtags ebuild in my 'flow' overlay and consider adding it to the guru overlay (but it may requires some more testing).

**Pull request closed without merging**
