### PR TITLE
dev-libs/roct-thunk-interface: 2.8.0 version bump

### PR DESCRIPTION
**Pull request by candrews**
Unfortunately, `rocminfo` shows no devices with this version.

Switching back to dev-libs/roct-thunk-interface 2.7.0 fixes it. So there's something wrong here... maybe we need to wait for more ROC 2.8.0 packages?

### CODE REVIEW

**Comment by justxi** [comment]
I simply renamed "roct-thunk-interface" and "rocr-runtime" to 2.8.0 and use the rocminfo-2.8 and it shows suitable results on my system.

**Comment by candrews** [comment]
> I simply renamed "roct-thunk-interface" and "rocr-runtime" to 2.8.0 and use the rocminfo-2.8 and it shows suitable results on my system.

Are you using dev-libs/rocr-runtime-2.7.0 from Gentoo?

I'd love to know roct-thunk-interface 2.7.0 works for me but 2.8.0 doesn't :(

**Comment by justxi** [comment]
For ROCm 2.8 I use: 
roct-thunk-interface-2.7.0::gentoo -> roct-thunk-interface-2.8.0::localrepo (renamed, no changes)
rocr-runtime-2.7.0::gentoo -> rocr-runtime-2.8.0::localrepo (renamed, no changes)
rocminfo-2.8.0::gentoo
llvm-roc-2.8.0::gentoo

**Comment by candrews** [comment]
merged

**Pull request closed without merging**
