### PR TITLE
dev-python/ipykernel: bump to 4.10.1 & 5.1.4 with py38

### PR DESCRIPTION
**Pull request by vpayno**
@zmedico @gyakovlev @chutz

### CODE REVIEW

**Comment by vpayno** [comment]
oh, someone just added 5.1.4 but without python 3.8

**Comment by vpayno** [comment]
```
--- ipykernel-4.8.2.ebuild      2020-03-05 17:17:51.755234826 -0800
+++ ipykernel-4.10.1.ebuild     2020-03-08 13:38:21.834844525 -0700
@@ -1,9 +1,9 @@
 # Copyright 1999-2020 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2

-EAPI=6
+EAPI=7

-PYTHON_COMPAT=( python3_6 )
+PYTHON_COMPAT=( python3_6 python3_8 )
 PYTHON_REQ_USE="threads(+)"

 inherit distutils-r1
@@ -37,7 +37,7 @@

        # bug 628222, specify python 2 or 3.
        sed -e "/language/!s:python:${EPYTHON%.*}:" \
-               -i "${ED}"usr/share/jupyter/kernels/${EPYTHON%.*}/kernel.json || die
+               -i "${ED}"/usr/share/jupyter/kernels/${EPYTHON%.*}/kernel.json || die
 }

 python_test() {
```

**Comment by heroxbd** [comment]
Thank you.

I don't think we need the 4.10.1 version because Python 2 is almost phased out in Gentoo.

To add  Python 3.7 and 3.8 targets, I would like to confirm with you that they have been verified to work.

**Comment by vpayno** [comment]
Merging into a single iPython PR.

**Pull request closed without merging**
