### PR TITLE
gui-wm/dwl: fix last remnants of the old HOMEPAGE

### PR DESCRIPTION
**Pull request by sevz17**
@thesamesam this time for real, I swear.

### CODE REVIEW

**Comment by thesamesam** [comment]
u will be last rited

**Comment by sevz17** [comment]
> u will be last rited

Huh?!

**Comment by thesamesam** [comment]
> > u will be last rited
> 
> Huh?!

I was just joking about terminating you for an error!

**Comment by sevz17** [comment]
> > > u will be last rited
> > 
> > 
> > Huh?!
> 
> I was just joking about terminating you for an error!

So that was it, I'm kinda bad at communication

**Pull request closed without merging**
