### PR TITLE
kernel-2.eclass: set UNIPATCH_LIST_GENPATCHES in src_unpack()

### PR DESCRIPTION
**Pull request by mgorny**
Modify genpatches logic to delay setting UNIPATCH_LIST_GENPATCHES until src_unpack(). The value of UNIPATCH_LIST_GENPATCHES depends on state of 'use experimental', therefore it can not be obtained in global scope. Therefore, handle_genpatches() will only set the URI when called in global scope, and it will set UNIPATCH_LIST_GENPATCHES on request which is done during kernel-2_src_unpack().

### CODE REVIEW

**Comment by prometheanfire** [comment]
if the function has two different behaviours when called the same way, perhaps it should be made generic and be called differently?  Otherwise the bash itself looks fine.

**Comment by mgorny** [comment]
@prometheanfire feel free to do that. I've already done enough to that terrible thing.

**Comment by prometheanfire** [comment]
no, this is fine :P :+1:

**Comment by mgorny** [comment]
Thanks, merged.

**Pull request closed without merging**
