### PR TITLE
dev-util/hermes,sys-cluster/lmod: keywording ~riscv

### PR DESCRIPTION
**Pull request by wiredhikari**
Signed-off-by: Atharva <atharvaamritkar@protonmail.com>

### CODE REVIEW

**Comment by jsmolic** [comment]
There is one more package that needs to be keyworded, see the CI link. You can get the full package list for keywording by running `nattka make-package-list -a riscv sys-cluster/lmod` at the root of your Gentoo development repository.

**Comment by amadio** [comment]
Yes, dev-util/hermes is a test dependency of lmod. Some tests were failing too on lmod, right @wiredhikari ? Have those been fixed?

**Comment by wiredhikari** [comment]
> Yes, dev-util/hermes is a test dependency of lmod. Some tests were failing too on lmod, right @wiredhikari ? Have those been fixed?

Yes the tests were failing for `lmod-8.6.14`, with `lmod-8.5.6` tests passed successfully

**Comment by jsmolic** [comment]
> > Yes, dev-util/hermes is a test dependency of lmod. Some tests were failing too on lmod, right @wiredhikari ? Have those been fixed?
> 
> Yes the tests were failing for `lmod-8.6.14`, with `lmod-8.5.6` tests passed successfully

Could you paste tatt testing results if you have them?

**Comment by wiredhikari** [comment]
> Could you paste tatt testing results if you have them?

[Here](https://raw.githubusercontent.com/wiredhikari/prefix_on_riscv/main/test_packages/lmod/lmod.report) are the reports.

**Comment by jsmolic** [comment]
@wiredhikari if there is none, could you please open a bug to track test failures in more recent version?

**Comment by wiredhikari** [comment]
Sure. Also, thanks for reviewing

**Pull request closed without merging**
