### PR TITLE
media-sound/denemo: respect user CFLAGS with USE=debug

### PR DESCRIPTION
**Pull request by waebbl**
update EAPI 7 -> 8
Closes: https://bugs.gentoo.org/889464

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Could you revbump, with EAPI update and reset keywords to ~?

**Comment by waebbl** [comment]
Ah yes, sorry forgot about revbumping when changing EAPI.

**Review by juippis — APPROVED** [review]
Thanks!

**Comment by waebbl** [comment]
Thanks for merging!

**Pull request closed without merging**
