### PR TITLE
dev-php/composer: add bump to 1.4.1

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Hey,
this is version bump for composer and needed dependencies,
test flag is not added in this version to simplify review, suggested by @orlitzky on #4010 

Feedback is welcome !

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I've just upgraded the branch, by adding RESTRICT="test" everywhere a IUSE="test" was defined.

**Comment by orlitzky** [comment]
A few things =)

1. Some of these packages are only used by composer, can you please remove the old versions once the new ones are added to the tree? For example, nothing is going to use jsonlint-1.4.0 after v1.6.0 is in the tree.

2. The `symfony-polyfill-mbstring` and `symfony-debug` packages are completely new, can you mention that in the commit message?

3. After adding the new `symfony-filesystem`, the tests for `symfony-config` fail:
```
>>> Test phase: dev-php/symfony-config-2.8.15
PHPUnit 4.3.1 by Sebastian Bergmann.

Configuration read from /var/tmp/portage/dev-php/symfony-config-2.8.15/work/config-2.8.15/phpunit.xml.dist

...PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\Filesystem\Filesystem' not found in /var/tmp/portage/dev-php/symfony-config-2.8.15/work/config-2.8.15/ResourceCheckerConfigCache.php:142
```

4. I get a failure when trying to patch the new version of composer:
```
 * Applying composer-update-paths.patch ...
1 out of 1 hunk FAILED -- saving rejects to file tests/Composer/Test/Json/ComposerSchemaTest.php.rej
1 out of 1 hunk FAILED -- saving rejects to file src/Composer/Json/JsonFile.php.rej                                                                      [ !! ]
```

**Comment by GuillaumeSeren** [comment]
Hey @orlitzky Thank you for the feedback.

> Some of these packages are only used by composer, can you please remove the old versions once the new ones are added to the tree? For example, nothing is going to use jsonlint-1.4.0 after v1.6.0 is in the tree.
Ok I will remove them.

> The symfony-polyfill-mbstring and symfony-debug packages are completely new, can you mention that in the commit message?
Ok I will rewrite the commit message.

> After adding the new symfony-filesystem, the tests for symfony-config fail:
I will check that maybe a autoloader or a dirname has been changed.

> I get a failure when trying to patch the new version of composer:
This is odd because I got it working on my machine and you can try it on my overlay, will check it.

**Comment by GuillaumeSeren** [comment]
Just updated the branch with updated commit title for dev-php/symfony-debug and dev-php/symfony-polyfill-mbstring

**Comment by orlitzky** [comment]
I just cherry-picked the version bumps for jsonlint and json-schema. The existing version of composer doesn't seem to mind, so that should simplify the PR a tiny bit.

**Comment by GuillaumeSeren** [comment]
@orlitzky Great I am upgrading the branch

**Comment by GuillaumeSeren** [comment]
@orlitzky I have upgraded the branch
* Remove old version of package
* Upgrade text of commit for new ones

**Comment by orlitzky** [comment]
The phpdepend failure is because it needs some old versions of libraries... I think I can fix that with a version bump of phpdepend.

**Comment by orlitzky** [comment]
I've cherry-picked most of the commits now so the version bump of composer is all that's left. The patch is still failing for me, but I think I figured out a way to avoid the patch entirely by installing everything to `/usr/share/composer`, and then using a symlink from `/usr/bin/composer` to there.

With your permission, I'll commit what I have, and then you can look over it?

**Comment by GuillaumeSeren** [comment]
@orlitzky Yes you are welcome to do so 🍺 

Let me know if you want me to review.

**Comment by orlitzky** [comment]
Ok, I've committed it. I'll link to the commit on the bug, or you can see the new ebuild in the tree.

**Comment by GuillaumeSeren** [comment]
Thank's @orlitzky 🍺

**Pull request closed without merging**
