### PR TITLE
media-gfx/kuickshow: Minor version bump

### PR DESCRIPTION
**Pull request by chrgerloff**
Switches to the official KDE release package.
Also fixes an issue with docbooks being processed during the configuration phase even though USE="-handbook" is specified.

### CODE REVIEW

**Comment by a17r** [comment]
The switch is going to be an issue without renaming the tarball, because Gentoo mirrors will download the old one for 0.10.0:

```
!!! Fetched file: kuickshow-0.10.0.tar.xz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      1038552
!!! Expected: 879364
Refetching... File renamed to '/home/distfiles/kuickshow-0.10.0.tar.xz._checksum_failure_.yrh62bsa'
```

**Comment by chrgerloff** [comment]
Fixed it by changing the local filename of the new tarball to *-r1.

**Comment by a17r** [comment]
looks like we both missed that meanwhile you had ported away from kdelibs4support? ;)

**Comment by chrgerloff** [comment]
I removed all dependencies of kdelibs4support from the code back when I ported it to KF5.
I only left it in the ebuild, because the build failed at the handbook-part when kde-frameworks/kdelibs4support was not installed.
A KDE developer updated the handbook shortly after the project was hosted again on the KDE infrastructure, but I forgot to test if the dependency was still necessary.

According to my test today, it isn't necessary any more. :-)
Do you want an update with the dep removed?

**Comment by a17r** [comment]
already done ;)

**Comment by chrgerloff** [comment]
alright, thank you :)

**Pull request closed without merging**
