### PR TITLE
dev-java/commons-validator: bump to 1.7 | profiles/thirdpartymirrors: apache https 

### PR DESCRIPTION
**Pull request by vaukai**
Tests fail since `commons-csv` and `junit-clptr` are missing.

```
<!-- Needed for IBANValidatorTest --> 
<dependency>
  <groupId>org.apache.commons</groupId>
  <artifactId>commons-csv</artifactId>
  <!-- 1.6 needed for Java 7+ --> 
  <version>1.6</version>
  <scope>test</scope>
</dependency>

<dependency>
  <groupId>junit</groupId>
  <artifactId>junit</artifactId>
  <version>4.13</version>
  <scope>test</scope>
</dependency>

<dependency>
  <!-- For testing DomainValidatorStartup --> 
  <groupId>org.bitstrings.test</groupId>
  <artifactId>junit-clptr</artifactId>
  <version>1.2.2</version>
  <scope>test</scope>
</dependency>
```

### CODE REVIEW

**Comment by fordfrog** [comment]
i merged the `commons-digester` commit.

**Comment by vaukai** [comment]
For https://bugs.gentoo.org/785856#c1 in case of not last-riting that package

**Comment by fordfrog** [comment]
as agreed, we [last rite](https://bugs.gentoo.org/785856) this package, so closing this.

**Comment by vaukai** [comment]
@gktrk @fordfrog 
Just came across https://github.com/gentoo/gentoo/blob/master/app-forensics/sleuthkit/sleuthkit-4.10.1-r1.ebuild#L24-L28

**Pull request closed without merging**
