### PR TITLE
www-client/qupzilla-2.1.2 enhance with xdg_desktop_database_update, c…

### PR DESCRIPTION
**Pull request by StefanCristian**
…loses bug 640776

### CODE REVIEW

**Comment by StefanCristian** [comment]
Portage: 2.3.13 , Repoman: 2.3.3

**Comment by StefanCristian** [comment]
0_O 9 lines and 100 new bugs. Now this is a record.

**Comment by a17r** [comment]
It's probably fixed if you simply `git pull --rebase` and force-push again.

**Comment by StefanCristian** [comment]
@a17r I know, I'll surely do that later a bit :)

**Comment by kensington** [comment]
Thanks for your contribution!

**Pull request closed without merging**
