### PR TITLE
games-emulation/jgrf: add 1.0.2, drop 1.0.1

### PR DESCRIPTION
**Pull request by orbea**

### CODE REVIEW

**Comment by thesamesam** [comment]
Could you cleanup old in a separate commit?

**Comment by orbea** [comment]
The only functional changes are this so on second thought it didn't seem worth keeping the older version.

https://gitlab.com/jgemu/jgrf/-/compare/1.0.1...1.0.2?from_project_id=19286253&straight=false#7a7dfbfa056343474c1ed502078e81c43b18625d

**Comment by thesamesam** [comment]
okay, that's fine, but note it in the commit message when that's the case (if you're sure there's 0 chance of regressions with it)

**Comment by orbea** [comment]
> okay, that's fine, but note it in the commit message when that's the case (if you're sure there's 0 chance of regressions with it)

Will remember this in the future, thanks.

**Pull request closed without merging**
