### PR TITLE
net-misc/httpie: Remove vulnerable version [security]

### PR DESCRIPTION
**Pull request by rseichter**
Remove ebuild for vulnerable upstream version 1.0.2.

### CODE REVIEW

**Comment by a17r** [comment]
**don't merge until 1.0.3 is stable**

**Comment by rseichter** [comment]
Version 1.0.3 has been stabilised, please merge.

**Comment by juippis** [comment]
Gonna test etc, but FYI:
`Closes: https://bugs.gentoo.org/701832` is wrong on security bugs. It even says security team will close it in the bug. All that being said, I don't believe it even allows bot to close it, but I'll change it to `Bug:` when merging just in case.

**Comment by rseichter** [comment]
Sorry about the "Closes:", force of habit. I'll keep it in mind for the future.

**Comment by juippis** [comment]
It's all fine, just wanted to inform you about it :)

**Comment by juippis** [comment]
Oh, and I failed there myself referencing PR / bug. Well apparently it allows the bot to close the bug ;)

**Comment by rseichter** [comment]
Yeah, I just noticed. Good job, both of u.s 😄

**Pull request closed without merging**
