### PR TITLE
Bump gtest and gflags to EAPI 7

### PR DESCRIPTION
**Pull request by dm0-**
I'm cross-compiling a project using `gflags` and `gtest`, which have `cmake` as a build dependency.  The eclass now understands how to put `cmake` in `BDEPEND`, so can these ebuilds be bumped to EAPI 7 to avoid the unnecessary cross-compiling?

### CODE REVIEW

**Comment by Peter-Levine** [comment]
I would think the EAPI change should cause `dev-cpp/gtest-1.8.1` and `dev-cpp/gflags-2.2.1` to be revbumped as well.

**Comment by a17r** [comment]
@Amynka do you agree?

**Comment by Peter-Levine** [comment]
I proxy-maintain **dev-cpp/gtest** but not ￼**dev-cpp/gflags**.  I have a few more commits to make but I'm waiting on this PR.

I'd appreciate it if someone authorized could merge this.

**Comment by a17r** [comment]
@Peter-Levine and so it was done.

**Comment by Peter-Levine** [comment]
@a17r  I see. Thanks.

**Comment by mgorny** [comment]
I see that gtest part was merged already, so I'll merge gflags.

**Comment by dm0-** [comment]
It looks like both commits were cherry-picked onto master now, so I'll close the PR.

**Pull request closed without merging**
