### PR TITLE
x11-apps/igt-gpu-tools: Version bump to 1.25

### PR DESCRIPTION
**Pull request by mohanram-meenakshisundaram**
New igt-gpu-tools 1.25 release contains new hardware supports, improvements and bug fixes
check the release notes here
https://cgit.freedesktop.org/xorg/app/intel-gpu-tools/commit/?h=igt-gpu-tools-1.25&id=f49ebeee9f54d6f23c60a842f75f65561d452ab0

Signed-off-by: Mohanram Meenakshisundaram <mohanram.meenakshisundaram@gmail.com>

### CODE REVIEW

**Comment by mohanram-meenakshisundaram** [comment]
Bug create : https://bugs.gentoo.org/718582

**Comment by mattst88** [comment]
Thank you for the pull request.

Some review feedback:

  - typically we don't remove the old version at the same time as adding the new version. This allows users to switch back to the old version in case big problems are found in the new version.
  - I'm surprised to see no changes in the ebuild between v1.24 and v1.25. Usually there are some changes to the build system that require ebuild updates. I always diff `meson.build` (for changes in the required versions of dependencies) and `meson_options.txt` (for changes to the build options) between the two versions. In this case, I see a lot of changes in `meson_options.txt`. For example a lot of build options had the "build_" prefix removed from their names:

```
-option('build_chamelium',
+option('chamelium',
        type : 'feature',
-       description : 'Build chamelium test')
+       description : 'Build Chamelium test')
```

  - It's a good idea to make those modifications to the -9999 ebuild in a prior commit and then have a second commit that simply copies the -9999 ebuild to the new version. That way, it's easy to `git blame` the 9999 ebuild and see when a change was made and why.
  - Use EAPI=7 when possible. I know that sometimes the ChromeOS tree has limitations that prevent using the newest EAPI, so if that's the case using EAPI=6 is fine, but since EAPI=7 has existed for quite a while now I suspect it is safe.

**Comment by mattst88** [comment]
Are you planning to follow up?

**Comment by mohanram-meenakshisundaram** [comment]
Thanks Matt for your feedback. I will check and address your comments.

**Comment by mohanram-meenakshisundaram** [comment]
@mattst88, Updated igt-gpu-tools package with your comments.  Please review

**Comment by mattst88** [comment]
Thanks!

**Pull request closed without merging**
