### PR TITLE
dev-java/velocity: bump to 2.3

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.17, Repoman-3.0.2
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
see https://github.com/gentoo/gentoo/pull/20176#issuecomment-821885177

**Comment by vaukai** [comment]
> see [#20176 (comment)](https://github.com/gentoo/gentoo/pull/20176#issuecomment-821885177)

Wow. Lessons to learn. Understanding that procedure will keep me busy for some time.

Let me ask a general question:  
After having this trouble with the https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz I found that  https://artfiles.org/apache.org/velocity/engine/2.3/velocity-engine-core-2.3-sources.jar provides the missing file.  So the present ebuild in this PR is based on the [sources.jar](https://artfiles.org/apache.org/velocity/engine/2.3/velocity-engine-core-2.3-sources.jar) version and seems to work fine.  

But it doesn't provide tests.  
Should one prefer the https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz version which comes with tests but needs the fix for the missing file?

Should the absence of that file in [org.apache.velocity.runtime.parser](https://github.com/apache/velocity-engine/tree/9cd6c031f9a2b36b6c922b9f86c3034b822e8870/velocity-engine-core/src/main/java/org/apache/velocity/runtime/parser) be regarded as a bug in https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz or is it normal to let maven create such files?

**Comment by fordfrog** [comment]
> Let me ask a general question:
> After having this trouble with the https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz I found that https://artfiles.org/apache.org/velocity/engine/2.3/velocity-engine-core-2.3-sources.jar provides the missing file. So the present ebuild in this PR is based on the [sources.jar](https://artfiles.org/apache.org/velocity/engine/2.3/velocity-engine-core-2.3-sources.jar) version and seems to work fine.
> 
> But it doesn't provide tests.
> Should one prefer the https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz version which comes with tests but needs the fix for the missing file?

well, you could as well add the missing sources to the tarball and it will compile and even tests will be available. but it has one disadvantage: you'd have to copy those files on each bump. using `javacc` takes more time to add to the ebuild, but then the bumps should be pretty easy. and yes, it is preferred to have tests present in the ebuild, and even more when we tweak the build system to convert it from maven to javacc. that way we can verify we did not break anything.

> Should the absence of that file in [org.apache.velocity.runtime.parser](https://github.com/apache/velocity-engine/tree/9cd6c031f9a2b36b6c922b9f86c3034b822e8870/velocity-engine-core/src/main/java/org/apache/velocity/runtime/parser) be regarded as a bug in https://github.com/apache/velocity-engine/archive/refs/tags/2.3.tar.gz or is it normal to let maven create such files?

some projects really generate some sources from other files, it is not that common but sometimes it makes sense.

one more note to what i in fact did to find out what's going on. first, i checked the `pom.xml` file to see if the files are generated somehow. then i cloned the upstream sources, switched to the tag that i wanted to work with, and then i ran `mvn clean && mvn -x compile &> mvn.log`. that gave me the output of the compilation in the text file which i could search for the missing file name and see in detail what's going on there. this is a general approach that should work on projects that use maven to build.

**Comment by vaukai** [comment]
> well, you could as well add the missing sources to the tarball and it will compile and even tests will be available. but it has one disadvantage: you'd have to copy those files on each bump. using `javacc` takes more time to add to the ebuild, but then the bumps should be pretty easy. and yes, it is preferred to have tests present in the ebuild, and even more when we tweak the build system to convert it from maven to javacc. that way we can verify we did not break anything.

Ok, back to the tarball version.  
Copying the files sounds easiest and that's what I try first.  Of course I still want to explore the `javacc` method ( https://github.com/gentoo/gentoo/pull/20176#issuecomment-821885177 ) later.

After copying 4 files from  `sources.jar` to the tarball the errors are boiled down to:
```
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
src/main/java/org/apache/velocity/runtime/RuntimeInstance.java:276: error: cannot find symbol
                log.debug("Starting Apache Velocity v" + VelocityEngineVersion.VERSION);
                                                         ^
  symbol:   variable VelocityEngineVersion
  location: class RuntimeInstance
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
1 warning
```
Now I have to investigate about `VelocityEngineVersion`.
Would this error also appear when using the `javacc` method?

**Comment by fordfrog** [comment]
looking at the maven output, this is relevant:
```
[INFO] Copying 1 resource
[DEBUG] file VelocityEngineVersion.java has a filtered file extension
[DEBUG] filtering /home/fordfrog/src/gentoo/velocity-engine.git/velocity-engine-core/src/main/java-templates/org/apache/velocity/runtime/VelocityEngineVersion.java to /home/fordfrog/src/gentoo/velocity-engine.git/velocity-engine-core/target/templates-tmp2482970109/org/apache/velocity/runtime/VelocityEngineVersion.java
```

**Comment by fordfrog** [comment]
@vaukai any progress on this?

**Comment by vaukai** [comment]
> @vaukai any progress on this?

Even with [your explanation](https://github.com/gentoo/gentoo/pull/20176#issuecomment-821885177) it's still somewhat too demanding atm. 
Please feel free to take over and I will keep an eye on it. ok?

**Comment by fordfrog** [comment]
ok, i'll try to finish it.

**Comment by fordfrog** [comment]
here's the fix:
```
diff --git a/dev-java/velocity/velocity-2.3.ebuild b/dev-java/velocity/velocity-2.3.ebuild
index 492e537814ac..34fce63eeb50 100644
--- a/dev-java/velocity/velocity-2.3.ebuild
+++ b/dev-java/velocity/velocity-2.3.ebuild
@@ -73,4 +73,8 @@ src_prepare() {
        cp -v "${WORKDIR}/org/apache/velocity/runtime/parser/node/StandardParserTreeConstants.java" \
                "${WORKDIR}/org/apache/velocity/runtime/parser/node/JJTStandardParserState.java" \
                "${S}/src/main/java/org/apache/velocity/runtime/parser/node" || die
+
+       cp -v "${S}/src/main/java-templates/org/apache/velocity/runtime/VelocityEngineVersion.java" \
+               "${S}/src/main/java/org/apache/velocity/runtime/VelocityEngineVersion.java" || die
+       sed -i "s/\${project.version}/${PV}/g" "${S}/src/main/java/org/apache/velocity/runtime/VelocityEngineVersion.java" || die
 }
```

there is still one test failing, working on it...

**Comment by vaukai** [comment]
> "s/\${project.version}/${PV}/g"

Too simple.  
Needs to correctly read the term `project.version` :-)

**Comment by fordfrog** [comment]
here's the complete fix, but many tests are failing because some classes are missing from the jar:
```
diff --git a/dev-java/velocity/velocity-2.3.ebuild b/dev-java/velocity/velocity-2.3.ebuild
index 492e537814ac..7d63ca83e0aa 100644
--- a/dev-java/velocity/velocity-2.3.ebuild
+++ b/dev-java/velocity/velocity-2.3.ebuild
@@ -73,4 +73,14 @@ src_prepare() {
        cp -v "${WORKDIR}/org/apache/velocity/runtime/parser/node/StandardParserTreeConstants.java" \
                "${WORKDIR}/org/apache/velocity/runtime/parser/node/JJTStandardParserState.java" \
                "${S}/src/main/java/org/apache/velocity/runtime/parser/node" || die
+
+       cp -v "${S}/src/main/java-templates/org/apache/velocity/runtime/VelocityEngineVersion.java" \
+               "${S}/src/main/java/org/apache/velocity/runtime/VelocityEngineVersion.java" || die
+       sed -i "s/\${project.version}/${PV}/g" "${S}/src/main/java/org/apache/velocity/runtime/VelocityEngineVersion.java" || die
+
+       # fix paths for tests
+       sed -i "s%System.getProperty(\"test.compare.dir\")%\"${S}/target/test-classes\"%g" \
+               src/test/java/org/apache/velocity/test/TemplateTestBase.java || die
+       sed -i "s%System.getProperty(\"test.result.dir\")%\"${S}/results\"%g" \
+               src/test/java/org/apache/velocity/test/TemplateTestBase.java || die
 }
```

**Comment by fordfrog** [comment]
ok, here's info for how to generate the missing classes (paths have to be adjusted, and `dev-java/javacc` added to `BDEPEND`):
```
[DEBUG] Running JJTree: [-GRAMMAR_ENCODING=UTF-8, -JDK_VERSION=1.8, -BUILD_NODE_FILES=false, -MULTI=true, -NODE_PACKAGE=org.apache.velocity.runtime.parser.node, -NODE_USES_PARSER=true, -STATIC=false, -OUTPUT_DIRECTORY=/home/fordfrog/src/gentoo/velocity-engine-2.3/velocity-engine-core/target/javacc-1619169642771/node, /home/fordfrog/src/gentoo/velocity-engine-2.3/velocity-engine-core/target/parser/Parser.jjt]
...
[DEBUG] Running JavaCC: [-GRAMMAR_ENCODING=UTF-8, -JDK_VERSION=1.8, -STATIC=false, -DEBUG_PARSER=false, -DEBUG_LOOKAHEAD=false, -DEBUG_TOKEN_MANAGER=false, -BUILD_PARSER=true, -TOKEN_MANAGER_USES_PARSER=true, -OUTPUT_DIRECTORY=/home/fordfrog/src/gentoo/velocity-engine-2.3/velocity-engine-core/target/javacc-1619169642771/parser, /home/fordfrog/src/gentoo/velocity-engine-2.3/velocity-engine-core/target/javacc-1619169642771/node/Parser.jj]
```
first `jjtree` has to be run, then `javacc`. the output of this should be the missing classes saved in the source tree. it should be part of `src_prepare`.

**Comment by vaukai** [comment]
Too many errors. Maybe I did a mistake somewhere?

**Comment by vaukai** [comment]
@fordfrog 
One more step forward, but there are new errors:  [build.log.gz](https://github.com/gentoo/gentoo/files/6367098/build.log.gz)

**Comment by fordfrog** [comment]
here's a patch that fixes the remaning issues
```
diff --git a/dev-java/velocity/velocity-2.3.ebuild b/dev-java/velocity/velocity-2.3.ebuild
index cc08fa18bd40..495e3056411d 100644
--- a/dev-java/velocity/velocity-2.3.ebuild
+++ b/dev-java/velocity/velocity-2.3.ebuild
@@ -67,10 +67,6 @@ JAVA_TEST_SRC_DIR="src/test/java"
 JAVA_TEST_RESOURCE_DIRS="src/test/resources"
 
 JAVA_TEST_EXCLUDES=(
-       # org.apache.velocity.exception.VelocityException: JarHolder: error establishing connection to JAR at 
-       # "jar:file:/var/tmp/portage/dev-java/velocity-2.3/work/velocity-engine-2.3/velocity-engine-core/target/test-classes/multiloader/test2.jar!/"
-       "org.apache.velocity.test.MultiLoaderTestCase"
-
        # org.junit.runners.model.InvalidTestClassError: Invalid test class, No runnable methods
        "org.apache.velocity.test.RenderVelocityTemplateTest"
        "org.apache.velocity.test.provider.TestNumber"
@@ -82,16 +78,18 @@ JAVA_TEST_EXCLUDES=(
        "org.apache.velocity.test.misc.TestLogger"
 
        # junit.framework.AssertionFailedError: Class org.apache.velocity.test.sql.BaseSQLTest has no public constructor TestCase(String name) or TestCase()
+       "org.apache.velocity.test.sql.BaseSQLTest"
+
+       # requires configured jdbc
        # junit.framework.AssertionFailedError: Exception in constructor: testSimpleTemplate (java.lang.NullPointerException
        # junit.framework.AssertionFailedError: Exception in constructor: testNullTimestamp (java.lang.NullPointerException
        # junit.framework.AssertionFailedError: Exception in constructor: testMacroInvocation (java.lang.NullPointerException
        # junit.framework.AssertionFailedError: Exception in constructor: testRenderTool (java.lang.NullPointerException
-       "junit.framework.TestSuite$1"
+       "org.apache.velocity.test.sql.DataSourceResourceLoaderTestCase"
 )
 
 src_prepare() {
        default
-       java-pkg_clean
 
        cp -v "${JAVA_SRC_DIR}-templates/org/apache/velocity/runtime/VelocityEngineVersion.java" \
                "${JAVA_SRC_DIR}/org/apache/velocity/runtime/VelocityEngineVersion.java" || die
```
`java-pkg_clean` removed `.jar` files from the test directory which were needed for the tests. and i disabled the test that needs jdbc connection to be set up to work correctly.

@vaukai i noticed you reported a bug about `dev-java/velocity-dvsl` that is not compatible with this version. `dev-java/snakeyaml` is fine?

**Comment by vaukai** [comment]
> `java-pkg_clean` removed `.jar` files from the test directory which were needed for the tests. and i disabled the test that needs jdbc connection to be set up to work correctly.

Will try

> 
> @vaukai i noticed you reported a bug about `dev-java/velocity-dvsl` that is not compatible with this version. `dev-java/snakeyaml` is fine?

Yep, romoval is fine.  Running difftool with our velocity-2.3 jar file and upstream jar file shows it would not work.

**Comment by fordfrog** [comment]
i just checked the jars with `japi-compilance-checker` and the only issues i've found that the jar does not contain package `org.apache.velocity.shaded.commons.io` which is fine as we have it in deps.

so, imo, the only check that is left to be done is to verify that `dev-java/snakeyaml` works with this version (it is the only dep as of now) and if so, we're ready to merge :-)

**Comment by fordfrog** [comment]
ok, so both `dev-java/snakeyaml-1.16` and `dev-java/snakeyaml-1.28-r1` compile fine. for `dev-java/snakeyaml-1.16` the tests fail but i would not care about it as this version is gonna be removed soon, so i'm merging.

**Comment by fordfrog** [comment]
@vaukai thanks for the work on this, this one was a bit challenging :-) let's give it 3 days and then we can stabilize latest `snakeyaml` along with this `velocity`, and get rid of the old versions. the only consumer is `dev-java/testng`, and all the relevant tests pass both for `snakeyaml` and `velocity` so it should be fine. to be sure, i'm just checking `testng` that all tests pass.

**Comment by vaukai** [comment]
> @vaukai thanks for the work on this, this one was a bit challenging :-) let's give it 3 days and then we can stabilize latest `snakeyaml` along with this `velocity`, and get rid of the old versions. 

Do you think of adding it to https://bugs.gentoo.org/776796?

**Comment by fordfrog** [comment]
`snakeyaml` can live with the older version so no need to block it.

**Pull request closed without merging**
