### PR TITLE
x11-terms/roxterm: Update to 3.9.4

### PR DESCRIPTION
**Pull request by ekohl**
Closes: https://bugs.gentoo.org/737538
Package-Manager: Portage-2.3.103, Repoman-2.3.23
Signed-off-by: Ewoud Kohl van Wijngaarden

### CODE REVIEW

**Comment by ekohl** [comment]
Rebased

**Comment by ekohl** [comment]
ping

**Comment by thesamesam** [comment]
Added two more deps (see 2eca4a669f3678f18fc88326fc7ccdbfc571bce6). Thanks!

**Comment by ekohl** [comment]
Thanks @thesamesam!

**Pull request closed without merging**
