### PR TITLE
dev-libs/libsecp256k1: bump to 0.3.0

### PR DESCRIPTION
**Pull request by whitslack**
See: https://github.com/bitcoin-core/secp256k1/blob/master/CHANGELOG.md#030---2023-03-08

@thesamesam: PR as promised. I have tested that `net-p2p/bitcoind-24.0.1::gentoo` and `dev-util/bitcoin-tx-24.0.1-r1::gentoo` compile and link against this new library version on amd64.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please cleanup old in a separate, subsequent commit (same PR is fine if you deem it appropriate to do it immediately, but shouldn't be unconditionally done for all PRs).

**Comment by whitslack** [comment]
> Please cleanup old in a separate, subsequent commit

@thesamesam: That's an unfortunate policy because it means that web tools like GitHub won't show the differences made to the ebuild in the version bump but rather will treat the new version's ebuild as a wholly new file, immaculately conceived, with no relation to the old version. Now it'll be much harder for anyone to notice that I changed the `SLOT` to `0/2` in 0.3.0 versus `0/1` in 0.2.0-r2. But okay, your wish is my command.

**Comment by ceamac** [comment]
Your second commit doesn't have a GCO.

**Comment by whitslack** [comment]
> Your second commit doesn't have a GCO.

Ugh, okay. I still don't understand the point of that requirement. I'm already in the `Author` field of the commit object, so *obviously* I'm "signing off" on its contents. I wouldn't have authored it if I didn't endorse it. The `Signed-off-by` trailer is redundant and stupid. Adding it now.

**Comment by thesamesam** [comment]
Go complain to the kernel.org people, I guess :stuck_out_tongue:

Thank you!

**Pull request closed without merging**
