### PR TITLE
sys-cluster/glusterfs: bump to 6.9/7.5

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested on my simple setup, all versions work ok (amd64).

### CODE REVIEW

**Comment by hydrapolic** [comment]
@jkroonza please review.

**Comment by hydrapolic** [comment]
Both are just copies from previous versions and 9999 was taken from 7.x branch. Yeah, the git diff seems weird in this case...

Seems like you did the previous bump so you're probably using this so I wanted to get you involved. Thanks!

**Comment by jkroonza** [comment]
@hydrapolic yea, we use glusterfs in about 10 or different clusters just counting off the top of my head quickly.  You're also welcome to add me as a secondary maintainer or however the process is.  Ideally I'd love to just be automatically CC'ed on all bug reports, and all PRs, but not take primary lead on this package in particular.  Ie, whilst we make heavy use of it, it's generally quite stable and my attention generally goes to other issues so I'm not expecting that I've got more capacity to just deal with other people's issues on this "in the stride" so to speak (as I generally try to do with asterisk and friends).

**Comment by Whissi** [comment]
I'll add you to metadata.xml on merge.

**Comment by hydrapolic** [comment]
Thanks @Whissi

**Pull request closed without merging**
