### PR TITLE
net-im/telegram-desktop-bin: version bump to 0.10.7

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
actually 0.10.8 is already out, but not under a github tag and i did not feel like changing the ebuild
I use this in my personal overlay
```
SRC_URI="
	amd64? ( https://updates.tdesktop.com/tlinux/tsetup.${PV}.tar.xz )
	x86? ( https://updates.tdesktop.com/tlinux32/tsetup32.${PV}.tar.xz )
"
```

**Comment by gavv** [comment]
LGTM. I also suggest to remove 0.10.1 from tree.

Could someone merge it? @monsieurp

> maybe merge this or wait until .8 appears for icons and stuff as well

I think it's OK to wait for the git tag. I'll ping them if it will not appear soon.

**Comment by monsieurp** [comment]
:+1:

**Comment by gavv** [comment]
@henning-schild see telegramdesktop/tdesktop#2471

**Pull request closed without merging**
