### PR TITLE
app-admin/packagekit-base, app-text/rarian, gnome-libs/cogl, ... : remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches/files from various gnome packages.
Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
Just rebased this PR, any chance for a merge?

**Comment by mm1ke** [comment]
Rebased this PR again.

**Comment by mm1ke** [comment]
Ping.. another rebase..

**Comment by leio** [comment]
I don't see any maintainer ACKs here.

**Comment by monsieurp** [comment]
Reverted in 78ca36b4f62b9bbe20b48dd1bfaee7a2f984e085.

**Comment by monsieurp** [comment]
@

**Comment by leio** [comment]
Merged everything except net-misc/ssh-askpass-fullscreen, which already was rejected before and bug https://bugs.gentoo.org/606714 filed

**Comment by mm1ke** [comment]
Thanks for committing and sorry for overlooking the bug.. i completely forgot about it.

**Comment by leio** [comment]
Maybe you'd like to look at solving the bug fully via finding out the manpage situation, etc? :)

**Pull request closed without merging**
