### PR TITLE
dev-util/clion: version bump to 2017.1.1

### PR DESCRIPTION
**Pull request by strahlc**
Package-Manager: Portage-2.3.3

Closes Bugzilla #616028

### CODE REVIEW

**Comment by mgorny** [comment]
Wrt nits, I think I've seen inconsistent indentation in removal thingy. But don't worry, we'll fix it while merging.

**Comment by mgorny** [comment]
I've split the maintainer change commit (using hardcode revert+reset+checkout+rebase action) and retab!-ed the new version. Hope you don't mind that.

**Comment by mgorny** [comment]
```
RepoMan scours the neighborhood...
  RDEPEND.suspect               3
   dev-util/clion/clion-1.2.4.143.1186.ebuild: 'dev-util/cmake'
   dev-util/clion/clion-2016.2.1.ebuild: 'dev-util/cmake'
   dev-util/clion/clion-2017.1.1.ebuild: 'dev-util/cmake'
```

Please fix this soonish.

**Comment by mgorny** [comment]
Hmm, unless it's false positive. In which case, don't fix it ;-).

**Comment by SoapGentoo** [comment]
It is a false positive - CLion uses CMake at runtime

**Pull request closed without merging**
