### PR TITLE
dev-db/mariadb: add 10.6.18/10.11.8/11.4.2

### PR DESCRIPTION
**Pull request by hydrapolic**
Compile/run tested on amd64.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by arkamar** [comment]
Tests pass for me as well, but the old versions removal is problematic, because it would force downgrade to 10.6.14 in some arches. Could you please preserve 10.6.15 and 10.11.5?

**Comment by hydrapolic** [comment]
> Tests pass for me as well, but the old versions removal is problematic, because it would force downgrade to 10.6.14 in some arches. Could you please preserve 10.6.15 and 10.11.5?

Yes, you are right, pushed an update keeping 10.6.15/10.11.5.

**Comment by arkamar** [comment]
> Tests pass for me as well

Well, I tested only 10.6.18 and 10.11.8 previously. Apparently, I fetched the branch before 11.4.2 was introduced. However, 11.4.2 fails for me
```
...
main.ssl_autoverify 'auto,unix'          w3 [ fail ]
main.ssl_autoverify 'pem,unix'           w3 [ fail ]
sysschema.v_privileges_by_table_by_level w3 [ fail ]
...
Completed: Failed 3/5330 tests, 99.94% were successful.
```
Are you experiencing similar issues? I am testing in `~amd64` machine.

**Comment by arkamar** [comment]
I have found this https://jira.mariadb.org/browse/MDEV-32332 for ssl issues

**Comment by hydrapolic** [comment]
> > Tests pass for me as well
> 
> Well, I tested only 10.6.18 and 10.11.8 previously. Apparently, I fetched the branch before 11.4.2 was introduced. However, 11.4.2 fails for me
> 
> ```
> ...
> main.ssl_autoverify 'auto,unix'          w3 [ fail ]
> main.ssl_autoverify 'pem,unix'           w3 [ fail ]
> sysschema.v_privileges_by_table_by_level w3 [ fail ]
> ...
> Completed: Failed 3/5330 tests, 99.94% were successful.
> ```
> 
> Are you experiencing similar issues? I am testing in `~amd64` machine.

Haven't run the tests actually, I did an upgrade from 10.6 -> 10.11 -> 11.4 and it went fine, will try to run the tests for 11.4, thanks for reporting. Btw, 11.4 is without KWs.

**Pull request closed without merging**
