### PR TITLE
app-editors/kakoune: version bump to 2016.06.14

### PR DESCRIPTION
**Pull request by Hummer12007**
remove versions 2016.05.15, 2016.05.05 from the tree

fixed a ncurses[tinfo] linking bug (see upstream mawww/kakoune#695): moved configuration of ncurses linker libs to ebuild, until upstream supports pkg-config

@gentoo/proxy-maint

### CODE REVIEW

**Comment by Amynka** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
!!! Fetched file: kakoune-2016.06.14.tar.gz VERIFY FAILED!
!!! Reason: Filesize does not match recorded size
!!! Got:      370479
!!! Expected: 369625

**Comment by mgorny** [comment]
I think tarballs refed by SHA1 aren't stable. Only those on tags are.

**Comment by gktrk** [comment]
@Hummer12007 this versioning scheme is inconsistent with [how we name snapshots](https://devmanual.gentoo.org/ebuild-writing/file-format/index.html#file-naming-rules). since the upstream has no releases, this should be renamed to kakoune-0_pre20160620. the obvious downside is that it will appear as a downgrade in portage (since 2016 > 0). Given you only keep one version in the tree, the users will effectively be forced to migrate to the new versioning scheme, so this should be ok. The alternative is to contact upstream and see if they'd be willing to do a release.

**Comment by gktrk** [comment]
This is merged. I did some git-monkeying before merging and made the following fixes on top your PR:
- Use the 0_pre versioning scheme instead of 0_p in the PR. 'p' stands for patchset whereas 'pre' stands for pre-release which sounded more fitting.
- The ncurses slot change warranted a revbump.
- Fixed docdir. We usually use /usr/share/doc/${PF} whereas default make install uses /usr/share/doc/${PN}.

Thanks for your contribution!

**Comment by gktrk** [comment]
https://github.com/gentoo/gentoo/compare/86b9e422883951c9a72f8a86291ab088ed3ae4e5...c07facf65bb508e22c2c9854c811cf3ec9139b2c

**Pull request closed without merging**
