### PR TITLE
waf-utils.eclass: WAF_VERBOSE always on

### PR DESCRIPTION
**Pull request by joke-junkie**
Fix broken behavior not allowing to change the default verbosity

This should be of importance to everybody building on multi-core/multi-cpu
systems, since giving the --verbose option to waf breaks a multi-job build
(by making it one-job), at least for me. This is probably a waf issue, but
the inability to change WAF_VERBOSE is clearly a bug in the eclass.

### CODE REVIEW

**Comment by joke-junkie** [comment]
To read more about the issue you can look at this:
[https://github.com/perfect7gentleman/pg_overlay/issues/9](url)

Basically, this is multiple issues, but here I address the WAF_VERBOSE test being incorrect.

**Comment by joke-junkie** [comment]
@Coacher 
This is a ping for an mpv maintainer. I've opened a pull request fixing an issue in waf-utils.eclass

**Comment by joke-junkie** [comment]
@gentoo/samba @gentoo/media-video
Pings for consumers of waf-utils.eclass. I've opened a pull request fixing an issue in waf-utils.eclass.

Also I have no idea how team-pinging works, so this may have been in vain.

**Comment by joke-junkie** [comment]
@Polynomial-C 
This is a ping for a (supposed) samba maintainer. I've opened a pull request fixing an issue in waf-utils.eclass

**Comment by joke-junkie** [comment]
@mgorny 
Is there actually a difference and why it matters, if you don't mind me asking?
Anyway, I don't care about this particular PR, but I would like this change to be incorporated somehow. Take a look at the commit: it's literally one minor fix to one string. Also yes, I have tested it, it solves the problem and, well, I cannot see any problems possibly arising with the fix that tiny. If there are more issues, they are already there. Speaking of which, I don't know anything about waf, but I do know something about shell scripting. It's obvious the original author of this made a minor mistake.

**Comment by joke-junkie** [comment]
@mgorny 
Like, seriously, I don't get what I have to do. Reformat the PR according to "Gentoo git workflow" rules? Anyway, please say something about this.

**Comment by mgorny** [comment]
Yes, reformatting the commit messages according to GLEP 66 rules is one thing. I'm not sure if that's possible via GitHub webinterface but if it is, I'm sorry. Also, all eclass changes need to be send for review (preferably as git patches) to gentoo-dev mailing list. If you don't have access, I suppose I could forward it for you. But…

I'm not really convinced that this change makes sense. What is the use case for non-verbose build logs? If user disables verbose logs, his bug reports become invalid. Why would we ever allow that?

**Comment by joke-junkie** [comment]
@mgorny 
Well, I fixed the title and the first comment as far as I can tell.

You mean I have to make a git patch? Is there a recommended way to do this?

Regarding the change itself, I think this is a bug because it does not allow the change of the WAF_VERBOSE variable at all, which is described in the reference as if you can do it. The variable is set to "ON" by default, so unless a user explicitly sets it somewhere, there should be no changes at how emerge goes. I have no idea what Gentoo policy on this is, but, firstly, I think it's wrong to straight forbid user to tune it, and secondly, does waf logs really need to be verbose to catch an error (I mean, I don't know, that's why I ask)?

**Comment by joke-junkie** [comment]
@mgorny 
Also you can take a look at cmake-utils.eclass and the similar variable CMAKE_VERBOSE. The test in that eclass actually works like it's supposed to (maybe != "OFF" is better than = "ON" for that, I don't really care).

**Comment by joke-junkie** [comment]
OK, I have it from the github. Do I send it to you via email or something?

That is understandable, but, as I said before, there should be no issues with that, really. User would have to actually read eclass or its reference to set that variable, which makes them advanced (maybe, hopefully).

**Comment by mgorny** [comment]
I don't see the fixed commit message. Once you've done that, subscribe to gentoo-dev ml and send it there. I think it will hit moderation queue, and someone will pass it on.

**Comment by joke-junkie** [comment]
OK, apparently you cannot edit commits without local repository and I have no idea how to do it anyway. It's too hard. Also I kinda broke the change into two commits now, which is probably pretty not good. I will retry later, with a fresh pull request, and close this one.

**Pull request closed without merging**
