### PR TITLE
gui-libs/gtk: add 4.14.2

### PR DESCRIPTION
**Pull request by sideeffect42**
Replaces: #36029

### CODE REVIEW

**Review by Jamim — CHANGES_REQUESTED** [review]
_Hello @sideeffect42,_

Thank you for submitting this PR! 🙇🏼 
I noticed that **GTK** `4.14.3` and `4.15.0` [were tagged recently](https://gitlab.gnome.org/GNOME/gtk/-/tags) and https://gtk.org/ claims this:
> Latest stable **4.14.3**

Would you mind updating your changes once again?
Hope this time someone will merge it before the next update.

_Thanks in advance!_

**Comment by sideeffect42** [comment]
@Jamim apologies, but yes I would mind. 😒

I don't think bumping the PR makes sense just for it to stay in the queue.
Especially with GTK making releases faster than Gentoo can review PRs.

If somebody actually wants to merge this PR, ping me and I will update it to whatever is the latest version at that point.

Thank you for understanding.

**Comment by jospezial** [comment]
See also https://github.com/gentoo/gentoo/commit/52ff5fb39a3c2a27bc76ee78a133789f5dd92568

**Comment by Jamim** [comment]
> @Jamim apologies, but yes I would mind. 😒
> 
> I don't think bumping the PR makes sense just for it to stay in the queue. Especially with GTK making releases faster than Gentoo can review PRs.
> 
> If somebody actually plans to merge this PR, ping me and I will update it to whatever is the latest version at that point.
> 
> Thank you for understanding.

Well, fair enough.

**Review by Jamim — COMMENTED** [review]
I've tried to build `gui-libs/gtk` with the `test` USE flag enabled.
```shell
USE="X cups introspection test wayland (-aqua) -broadway -cloudproviders -colord -examples -gstreamer -sysprof (-vulkan)"
```
Below are results for different versions.

<details>
<summary>gui-libs/gtk-4.12.5-r1::gentoo (6 failures)</summary>

```
Summary of Failures:

 988/1548 gtk:gsk / parser widgetfactory.node                                                                                                            FAIL               0.31s   exit status 1
1061/1548 gtk:gtk / templates                                                                                                                            ERROR              4.72s   killed by signal 5 SIGTRAP
1359/1548 gtk:tools / validate                                                                                                                           FAIL               2.24s   0/9 subtests passed
1538/1548 gtk:reftest / reftest vbox-with-2-wrapping-labels-where-one-should-wrap.ui                                                                     FAIL               0.63s   0/1 subtests passed
1547/1548 gtk:headless / monitor                                                                                                                         FAIL               6.30s   exit status 1
1548/1548 gtk:headless / input                                                                                                                           FAIL               6.33s   exit status 1

Ok:                 1537
Expected Fail:      0   
Fail:               6   
Unexpected Pass:    0   
Skipped:            5   
Timeout:            0 
```

</details>

<details>
<summary>gui-libs/gtk-4.14.2::sideeffect42 (27 failures)</summary>

```
Summary of Failures:

   9/4256 gtk:gdk / memorytexture                                                                                                                                         ERROR              1.12s   killed by signal 11 SIGSEGV
 539/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-clipped-gl / compare gl glyph-hinting-none clipped                                                        FAIL               0.48s   exit status 1
 542/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-flipped-gl / compare gl glyph-hinting-none flipped                                                        FAIL               0.53s   exit status 1
 543/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-colorflipped-gl / compare gl glyph-hinting-none colorflipped                                              FAIL               0.56s   exit status 1
 544/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-masked-gl / compare gl glyph-hinting-none masked                                                          FAIL               0.57s   exit status 1
 545/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-plain-gl / compare gl glyph-hinting-none plain                                                            FAIL               0.48s   exit status 1
 546/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-repeated-gl / compare gl glyph-hinting-none repeated                                                      FAIL               0.41s   exit status 1
 548/4256 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-rotated-gl / compare gl glyph-hinting-none rotated                                                        FAIL               0.46s   exit status 1
1677/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-colorflipped-cairo / compare cairo glyph-hinting-none colorflipped                                  FAIL               0.10s   exit status 1
1680/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-flipped-cairo / compare cairo glyph-hinting-none flipped                                            FAIL               0.12s   exit status 1
1682/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-masked-cairo / compare cairo glyph-hinting-none masked                                              FAIL               0.14s   exit status 1
1684/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-plain-cairo / compare cairo glyph-hinting-none plain                                                FAIL               0.12s   exit status 1
1686/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-repeated-cairo / compare cairo glyph-hinting-none repeated                                          FAIL               0.18s   exit status 1
1688/4256 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-rotated-cairo / compare cairo glyph-hinting-none rotated                                            FAIL               0.17s   exit status 1
2848/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-clipped-ngl / compare ngl glyph-hinting-none clipped                                                    FAIL               0.33s   exit status 1
2851/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-colorflipped-ngl / compare ngl glyph-hinting-none colorflipped                                          FAIL               0.34s   exit status 1
2852/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-flipped-ngl / compare ngl glyph-hinting-none flipped                                                    FAIL               0.34s   exit status 1
2853/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-masked-ngl / compare ngl glyph-hinting-none masked                                                      FAIL               0.38s   exit status 1
2854/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-plain-ngl / compare ngl glyph-hinting-none plain                                                        FAIL               0.34s   exit status 1
2855/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-repeated-ngl / compare ngl glyph-hinting-none repeated                                                  FAIL               0.36s   exit status 1
2857/4256 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-rotated-ngl / compare ngl glyph-hinting-none rotated                                                    FAIL               0.35s   exit status 1
3664/4256 gtk:gsk+gsk-nodeparser / parser text-font-errors.node                                                                                                           FAIL               0.17s   exit status 1
3687/4256 gtk:gsk / scaling                                                                                                                                               ERROR              0.15s   killed by signal 11 SIGSEGV
3768/4256 gtk:gtk / templates                                                                                                                                             ERROR              4.69s   killed by signal 5 SIGTRAP
4247/4256 gtk:reftest / reftest vbox-with-2-wrapping-labels-where-one-should-wrap.ui                                                                                      FAIL               0.58s   0/1 subtests passed
4255/4256 gtk:headless / monitor                                                                                                                                          FAIL               6.31s   exit status 1
4256/4256 gtk:headless / input                                                                                                                                            FAIL               6.31s   exit status 1

Ok:                 4218
Expected Fail:      0
Fail:               27
Unexpected Pass:    0
Skipped:            11
Timeout:            0
```

</details>

<details>
<summary>gui-libs/gtk-4.14.3::mim (27 failures)</summary>

```
Summary of Failures:

   9/4294 gtk:gdk / memorytexture                                                                                                                                         ERROR              0.99s   killed by signal 11 SIGSEGV
 539/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-clipped-gl / compare gl glyph-hinting-none clipped                                                        FAIL               0.53s   exit status 1
 540/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-colorflipped-gl / compare gl glyph-hinting-none colorflipped                                              FAIL               0.51s   exit status 1
 542/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-flipped-gl / compare gl glyph-hinting-none flipped                                                        FAIL               0.53s   exit status 1
 544/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-masked-gl / compare gl glyph-hinting-none masked                                                          FAIL               0.56s   exit status 1
 545/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-plain-gl / compare gl glyph-hinting-none plain                                                            FAIL               0.49s   exit status 1
 547/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-repeated-gl / compare gl glyph-hinting-none repeated                                                      FAIL               0.52s   exit status 1
 548/4294 gtk:gsk+gsk-compare+gsk-gl+gsk-compare-gl+gsk-compare-rotated-gl / compare gl glyph-hinting-none rotated                                                        FAIL               0.48s   exit status 1
1688/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-colorflipped-cairo / compare cairo glyph-hinting-none colorflipped                                  FAIL               0.25s   exit status 1
1691/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-flipped-cairo / compare cairo glyph-hinting-none flipped                                            FAIL               0.26s   exit status 1
1692/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-masked-cairo / compare cairo glyph-hinting-none masked                                              FAIL               0.26s   exit status 1
1693/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-plain-cairo / compare cairo glyph-hinting-none plain                                                FAIL               0.29s   exit status 1
1694/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-repeated-cairo / compare cairo glyph-hinting-none repeated                                          FAIL               0.26s   exit status 1
1696/4294 gtk:gsk+gsk-compare+gsk-cairo+gsk-compare-cairo+gsk-compare-rotated-cairo / compare cairo glyph-hinting-none rotated                                            FAIL               0.27s   exit status 1
2870/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-clipped-ngl / compare ngl glyph-hinting-none clipped                                                    FAIL               0.36s   exit status 1
2873/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-colorflipped-ngl / compare ngl glyph-hinting-none colorflipped                                          FAIL               0.42s   exit status 1
2874/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-flipped-ngl / compare ngl glyph-hinting-none flipped                                                    FAIL               0.39s   exit status 1
2875/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-masked-ngl / compare ngl glyph-hinting-none masked                                                      FAIL               0.38s   exit status 1
2876/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-plain-ngl / compare ngl glyph-hinting-none plain                                                        FAIL               0.35s   exit status 1
2877/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-repeated-ngl / compare ngl glyph-hinting-none repeated                                                  FAIL               0.34s   exit status 1
2879/4294 gtk:gsk+gsk-compare+gsk-ngl+gsk-compare-ngl+gsk-compare-rotated-ngl / compare ngl glyph-hinting-none rotated                                                    FAIL               0.35s   exit status 1
3703/4294 gtk:gsk+gsk-nodeparser / parser text-font-errors.node                                                                                                           FAIL               0.31s   exit status 1
3725/4294 gtk:gsk / scaling                                                                                                                                               ERROR              0.23s   killed by signal 11 SIGSEGV
3808/4294 gtk:gtk / templates                                                                                                                                             ERROR              5.01s   killed by signal 5 SIGTRAP
4284/4294 gtk:reftest / reftest vbox-with-2-wrapping-labels-where-one-should-wrap.ui                                                                                      FAIL               0.65s   0/1 subtests passed
4293/4294 gtk:headless / monitor                                                                                                                                          FAIL               6.32s   exit status 1
4294/4294 gtk:headless / input                                                                                                                                            FAIL               6.33s   exit status 1

Ok:                 4254
Expected Fail:      0   
Fail:               27  
Unexpected Pass:    0   
Skipped:            13  
Timeout:            0 
```

</details>

There are [some related bugs](https://bugs.gentoo.org/buglist.cgi?quicksearch=gui-libs%2Fgtk%20test) for older versions.

I suppose we should at least try to investigate new failures.

**Comment by leio** [comment]
I've bumped to gtk-4.14.3 based on a contributors GNOME 46 bumps tree with many follow-up fixes. All of these would have been needed in case of this PR as well, so for future reference, please review commit 653816fe975340fde768db29517257350e1db661 and see why you missed some of these - in particular libdrm and linux-headers `DEPEND` and vulkan-loader minimum dep (the rest were suboptimal in earlier versions already).

In general all of gnome 46 bumps are available in aforementioned contributors branch, and it's a matter of reviewing it all and integrating in main tree one by one as reviewing happens.

**Comment by sideeffect42** [comment]
@leio I only wanted to be nice and send a patch for something I had written for my own experimentation anyway.

Experimentation for what? I don't know if anybody noticed but with GTK 4.12 the icons are gone on big endian systems.

Why did I miss the vulkan changes? Very simple: I don't have any Vulkan-capable hardware to test.

**Comment by Jamim** [comment]
> I've bumped to gtk-4.14.3 based on a contributors GNOME 46 bumps tree with many follow-up fixes. All of these would have been needed in case of this PR as well, so for future reference, please review commit [653816f](https://github.com/gentoo/gentoo/commit/653816fe975340fde768db29517257350e1db661) and see why you missed some of these - in particular libdrm and linux-headers `DEPEND` and vulkan-loader minimum dep (the rest were suboptimal in earlier versions already).
> 
> In general all of gnome 46 bumps are available in aforementioned contributors branch, and it's a matter of reviewing it all and integrating in main tree one by one as reviewing happens.

@leio where can that branch be found at?
The only branch I can find here and [there](https://gitweb.gentoo.org/repo/gentoo.git/refs/) is `master`.

**Pull request closed without merging**
