### PR TITLE
dev-java/tomcat-{el,jsp,servlet}-api: add 9.0.69 and verify-sig

### PR DESCRIPTION
**Pull request by vaukai**
@fordfrog 
There are always several packages built from the same tomcat tarball but verification should be needed only once.  So I put it here on `tomcat-el-api`.
The `sec-keys/openpgp-keys-apache-tomcat`package might need some refinement for versions and/or slots.

### CODE REVIEW

**Comment by fordfrog** [comment]
it makes more sense for me to add it on every relevant package. as the verification can be turned on just for a single ebuild by user, and it doesn't have to be `tomcat-el-api`.

**Comment by vaukai** [comment]
> as the verification can be turned on just for a single ebuild by user,

Good catch. Next version bumps then ...

**Comment by fordfrog** [comment]
@vaukai thanks! i also added `verify-sig` to `tomcat` itself but i excluded the bundled `bnd` jars as i was not able to find corresponding public keys for signed files downloaded from `repo.maven.apache.org`. anyway, we should eventually unbundle `bnd` in some future.

**Comment by vaukai** [comment]
> anyway, we should eventually unbundle `bnd` in some future. 

when i tried that i ended up with compilation errors in https://github.com/gentoo/gentoo/compare/master...vaukai:gentoo:aqute-bndlib where i simplified the [osgi dependencies](https://github.com/gentoo/gentoo/compare/master...vaukai:gentoo:aqute-bndlib#diff-f0f2e7739941a2371be75386684c5e19a730b07a26c4fd0c632cd3ae206bfae3R38-R40) instead of depending on and packaging each single artifact.

**Pull request closed without merging**
