### PR TITLE
dev-java/maven-bin: bump to 3.3.3

### PR DESCRIPTION
**Pull request by zxiiro**

### CODE REVIEW

**Comment by hasufell** [comment]
@chewi @monsieurp

**Comment by monsieurp** [comment]
I'm willing to merge this PR but I'm not familiar with the process. Could you walk me through it?

**Comment by hasufell** [comment]
https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Pull_requests_from_users also check the notes on the end of the section

**Comment by chewi** [comment]
I'll kindly let @monsieurp do the work for me so he gets familiar with the process. :wink: But @zxiiro, please reword your commit message so that it begins `dev-java/maven-bin:`. Your pull request title actually has this. You really should do the commit using repoman, which will automatically enter this prefix in your editor when you run `repoman commit`. It also does many other QA checks.

**Comment by hasufell** [comment]
> It also does many other QA checks.

you don't need to commit with repoman (which is incompatible to almost any git tool there is, like gitk/git-gui), but you have to run `repoman full` after you have _staged_ (not committed) your changes

**Comment by zxiiro** [comment]
Thanks for the tips, updated.

**Comment by zxiiro** [comment]
Finally was able to test this and confirm this latest patch should build now. I had to remove the "bin/*.bat" rm command as it was failing to find anything in that path.

**Comment by zxiiro** [comment]
Actually I just realized it's more correct to change it to bin/*.cmd. apparently cmd is the new bat on Windows.

**Comment by monsieurp** [comment]
Merged :+1:

**Pull request merged**
