### PR TITLE
linux-mod-r1.eclass: new eclass, rewrite of linux-mod

### PR DESCRIPTION
**Pull request by ionenwks**
See commit message(s) and/or eclass docs for more details. Included a few example ebuilds I tested this with.

Being -r1 no need to be worried about breaking old things, albeit should figure out if anything notable to sort out before it gets used.

Unfortunately no tests, being tied with multiple files, kernel, and toolchain checks, it would be a pain to implement.

~Will wait until bit of pre-review/testing before posting to ML for review.~

CC @gentoo/kernel (kept project listed a maintainer, albeit added myself too and will handle issues whenever I can)

Maintainers that will get pinged for the demo ebuilds may want to peek and maybe keep local copy of the commits for reference, albeit except for the simple ryzen_smu this isn't something I'm going to merge so no need for ack (it's volatile packages and would rather maintainers handle this themselves).

### CODE REVIEW

**Comment by ceamac** [comment]
Nice.  It's good to remove some cruft from virtualbox-modules.  

I tried migrating virtualbox-guest-additions to linux-mod-r1, it was quite painless.  I compiled the modules with a clang built kernel and it works.

**Comment by ionenwks** [comment]
Changelog (2023-05-28)
- adjust compiler mismatch warning for better visiblity and accuracy
- prevent passing -Werror even if `CONFIG_WERROR=y` which recent kernels enable by default (unrealistic for not-frequently-updated modules), the other -Werror=specific are left alone
- add `DEPMOD=:` and no-auto-sign/compress `CONFIG_` to default makeargs, this should help streamline ebuilds using `make install` (zfs-kmod, dahdi, maybe others), technically useless arguments for others but should not be harmful
- drop `INSTALL_MOD_PATH` support, upon further reflection, I think this is silly and becomes very inconsistent/messy when ebuilds use emake install, find commands, and such (getting it right in zfs-kmod was also confusing)
- drop `modules_makeargs_to_array` and replace by always-set `MODULES_MAKEARGS`, sounded like a good idea at first but this just added extra churn to ebuilds
- other minor typos, wording, and style adjustments/fix
- zfs-kmod example was updated to match changes, CC @thesamesam @gyakovlev 
- add dahdi to demo not-for-merge migrations, CC @jkroonza may want to save the commit as reference

Likely merge tomorrow if nothing comes up (been suggested there's little reason to wait that long), then maintainers can do the actual migrations as wanted. Will fix/adjust further after as need arise *hopefully* with no usage changes, albeit will fix already-migrated ebuilds if it goes there.

@gentoo/kernel btw I'll leave choosing when to `@DEPRECATED: linux-mod-r1.eclass` in linux-mod-r0 to you whenever feel this is good enough and everyone should migrate.

**Comment by jkroonza** [comment]
Hi @ionenwks 

Thanks for this.  I think it goes without saying this (Dropping -Werror) doesn't actually *fix* the underlying issues pointed out by the warnings and just delays the inevitable.

Is there a bug or some other URL I can add to reference here:  https://bugs.gentoo.org/906179

The pointer constness underlying issue still remains, this will merely work around it, and eventually the fact that this is a warning may well en up becoming an error regardless.

Also read the emails on -dev and I think this is a move in the right direction.

Kind Regards,
Jaco

**Comment by ionenwks** [comment]
> Thanks for this. I think it goes without saying this (Dropping -Werror) doesn't actually _fix_ the underlying issues pointed out by the warnings and just delays the inevitable.

> The pointer constness underlying issue still remains, this will merely work around it, and eventually the fact that this is a warning may well en up becoming an error regardless.

I think(?) there's some mix up here, there's *two* notable -Werror being passed
- -Werror (global, fails on a lot of silly things like dahdi doing implicit fallthrough, not worth worrying about)
- -Werror=incompatible-pointer-types (the const issues)

The first one is enabled by CONFIG_WERROR=y (a kernel default since recently), the 2nd one is passed unconditionally. The eclass only disables the first one similarly to many other packages that also disable -Werror.

So dahdi is still getting incompatible pointer types issues regardless of the eclass. I did make a note about the 2nd one in the commit summary (and dropping being a poor solution), but neither the commit nor the eclass actually make this change.

> Is there a bug or some other URL I can add to reference here: https://bugs.gentoo.org/906179

For what? It's not really an issue I've looked into and was just looking at a basic migration test.

> Also read the emails on -dev and I think this is a move in the right direction.

Nice.

(on another note, cleaned the commit -- noticed I had some linux-mod-r1 comment changes mixed up in there)

**Comment by jkroonza** [comment]
> I think(?) there's some mix up here, there's _two_ notable -Werror being passed
> 
>     * -Werror (global, fails on a lot of silly things like dahdi doing implicit fallthrough, not worth worrying about)
>     * -Werror=incompatible-pointer-types (the const issues)

Thanks for pointing this one out.  I do think the latter really should have from day one have been an error in the compiler, but having looked at the code I honestly don't know what causes it.  I've started wondering if it's not maybe a compiler bug, but that doesn't make sense either ... then this would definitely have cropped up elsewhere too.

> So dahdi is still getting incompatible pointer types issues regardless of the eclass. I did make a note about the 2nd one in the commit summary (and dropping being a poor solution), but neither the commit nor the eclass actually make this change.
> 
> > Is there a bug or some other URL I can add to reference here: https://bugs.gentoo.org/906179
> 
> For what? It's not really an issue I've looked into and was just looking at a basic migration test.

For refencing this from the bug, I'll just link this PR, not sure what I was smoking this morning ... just going to blame a client for waking me up a few times at inhumane hours last night.

**Comment by ionenwks** [comment]
> Is there a reason why every ebuild is required to redefine the same boilerplate `src_compile` with ambiguously named local variables instead of setting them as global vars as the old eclass did?
For starters, KV_OUT_DIR is not set in global scope. Same for many other variables you may need to use at times.

It kinda worked because it did **eval** ${BUILD_PARAMS} though, but that was rather misused.

**Comment by ionenwks** [comment]
Ultimately you pretty much *always* need to pass KV_OUT_DIR, the variable is almost never the same and the eclass can't really guess it.

**Comment by ionenwks** [comment]
Even referencing `${S}` which many ebuilds did for MODULES_NAMES is technically not legal in global scope :)

**Comment by ionenwks** [comment]
> Is there a reason why every ebuild is required to redefine the same boilerplate `src_compile` with ambiguously named local variables instead of setting them as global vars as the old eclass did?

Or rather than global, is it just that you want to set them in e.g. pkg_setup?

**Pull request closed without merging**
