### PR TITLE
media-gfx/blender-{3.2.2,9999} - add optix support

### PR DESCRIPTION
**Pull request by waebbl**
Add compile and runtime support for the NVIDIA OptiX library.
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

The `optix` USE flag needs to be masked for `arm` arch, because of `x11-drivers/nvidia-drivers` is lacking arm support. See
Bug: https://bugs.gentoo.org/870452

See https://github.com/gentoo/gentoo/pull/21435#issuecomment-1231352066 for why this update is done by me.

### CODE REVIEW

**Comment by DarkDefender** [comment]
LGTM! :)

**Comment by DarkDefender** [comment]
@ionenwks do you have time to merge this?

**Comment by ionenwks** [comment]
> @ionenwks do you have time to merge this?

Sure, I can't test runtime with my old card but it builds fine for me and see no reason to hold this back.

I'll just toss in a Closes: for https://bugs.gentoo.org/741564

**Comment by waebbl** [comment]
Thanks @ionenwks for merging and adding the Closes tag.

**Comment by DarkDefender** [comment]
Thanks! :)

**Pull request closed without merging**
