### PR TITLE
mail-client/alpine: add 2.26-r4 fixing ipv6 support, fix build on gcc-14

### PR DESCRIPTION
**Pull request by robert7k**
Closes: https://bugs.gentoo.org/935343
Closes: https://bugs.gentoo.org/920365

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by hhoffstaette** [comment]
While we have this PR can you please also throw in the fix from https://bugs.gentoo.org/920365#c10 - otherwise we won't be able to compile with gcc-14.

**Comment by hhoffstaette** [comment]
The CI error happens because you added the `ipv6` flag to `metadata.xml`, which is redundant as that's already a global flag.

**Comment by robert7k** [comment]
> The CI error happens because you added the `ipv6` flag to `metadata.xml`, which is redundant as that's already a global flag.

I did this because it was the recommended by the [pkgcheck documentation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#useflagwithoutdeps). I just reverted the change in `metadata.xml`.

**Comment by hhoffstaette** [comment]
> > The CI error happens because you added the `ipv6` flag to `metadata.xml`, which is redundant as that's already a global flag.
> 
> I did this because it was the recommended by the [pkgcheck documentation](https://pkgcore.github.io/pkgcheck/man/pkgcheck.html#useflagwithoutdeps). I just reverted the change in `metadata.xml`.

Interesting, in a sad way. :shrug: I guess we can now choose one or the other warning. The documentation is right that ipv6 should not really exist, but it still exists on the `net-libs/c-client` as well, so in this case it's better to be consistent. One day we'll get rid of it.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
