### PR TITLE
www-servers/nginx: Bugfixes

### PR DESCRIPTION
**Pull request by Whissi**
This is a security cleanup for [bug 584744](https://bugs.gentoo.org/show_bug.cgi?id=584744) and fixes [bug 585804](https://bugs.gentoo.org/show_bug.cgi?id=585804).

### CODE REVIEW

**Comment by jbergstroem** [comment]
I haven't compiled the rtmp patch but others seems to agree that it works; the rest of the changes LGTM.

**Comment by Whissi** [comment]
This PR no longer contains the security cleanup because @krifisk asked me to split the PR.

**Comment by Whissi** [comment]
Security clean up is now in pr #1670.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Pull request closed without merging**
