### PR TITLE
[WIP/Do not merge] Zabbix glep81

### PR DESCRIPTION
**Pull request by holgersson32644**
Hi,
this is my draft(!) for the glep81 integration into net-analyzer/zabbix. There will be plenty modifications.

Suggestions are welcome!

### CODE REVIEW

**Comment by fordfrog** [comment]
i did not have time for in-depth investigation and testing, but what i can see is that fowners commands need to be updated to reflect new users.

**Comment by Dessa** [comment]
as a sidenote, agent2 is now fully supported in 5.0 so it makes more sense to just support it there.
4.4 is only supported until end of next month (it was supposed to be ending end of last month but got extended)

**Comment by Dessa** [comment]
Any progress on this?

**Comment by ajakk** [comment]
I think this is unecessary after 97eea3725 and b9643bae?

**Comment by holgersson32644** [comment]
Sorry, yes, this is obsolete now.

**Pull request closed without merging**
