### PR TITLE
x11-wm/i3: use elog for messages to users

### PR DESCRIPTION
**Pull request by fturco**
See https://dev.gentoo.org/~zmedico/portage/doc/ch06s02.html for details.

### CODE REVIEW

**Comment by ntnn** [comment]
That's not quite right, see: https://devmanual.gentoo.org/ebuild-writing/messages/index.html

`einfo` is for messages meant for users that should not land in the log.

**Comment by fturco** [comment]
@ntnn: These kind of messages *should* indeed end up in the log, so users can read them later.

**Comment by ntnn** [comment]
No, not these messages.

These messages point new users of i3 towards auxiliary applications (they might be pointed there by the i3 documentation anyway, but it doesn't hurt). Since new users are likely to install it manually they're also likely to read the relevant info message - hence `einfo` is used.

With `elog` these would also be logged (and displayed) with every upgrade, cluttering the output of continuing users - who do not need these messages - over and over again. There are already enough packages abusing `elog` to print information for new users.

`elog` is meant to notify a user of changes from previous versions, e.g. if config files need to be updated due to changes of options (although ewarn may be used for that if this would break an application).

An example that would fit for this package: I'd use `elog` if `i3status` would be merged into `i3` to notify users that they can safely remove `i3status` and link a migration guide.

**Comment by ntnn** [comment]
I just remembered mail-client/mutt had a good solution for that.

They're checking beforehand if mutt was already installed and set a variable. This variable is checked in `pkg_postinst` do display messages using `elog` afterwards. That is somewhat something I can get behind. At least it doesn't clutter the emerge output merely updating.

**Comment by fturco** [comment]
Perhaps we can look at the solution in `app-portage/gentoolkit` ebuilds, too.

**Comment by ntnn** [comment]
Yes, that'd be ideal - would you update the PR accordingly?

**Comment by fturco** [comment]
Done. Is it OK now?

**Comment by ntnn** [comment]
That's perfect, thank you. I'll ask my mentor to merge the commit.

**Pull request closed without merging**
