### PR TITLE
net-misc/i2pd: use correct logrotate file, and provided in distribution configuration file

### PR DESCRIPTION
**Pull request by khumarahn**

### CODE REVIEW

**Comment by khumarahn** [comment]
discussion: https://bugs.gentoo.org/show_bug.cgi?id=564596

**Comment by monsieurp** [comment]
Looks similar as PR #1040.

**Comment by monsieurp** [comment]
@blueness

**Comment by khumarahn** [comment]
Yes, it is similar. In #1040 I missed an important change, this pull request covers that.

**Pull request closed without merging**
