### PR TITLE
dev-python/greenstalk: bump to version 1.0.1.

### PR DESCRIPTION
**Pull request by dargor**
Signed-off-by: Gabriel Linder <linder.gabriel@gmail.com>
Package-Manager: Portage-2.3.66, Repoman-2.3.16

### CODE REVIEW

**Comment by mgorny** [comment]
Tests, please?

**Comment by juippis** [comment]
Ping.

**Comment by dargor** [comment]
Sorry. I'll take care of tests and add version 1.1.0 too.

**Comment by dargor** [comment]
Done. Found a bug in tests, reported upstream https://github.com/mayhewj/greenstalk/pull/5

**Comment by juippis** [comment]
Thanks! Sorry for still bouncing this back, but could you try running tests with the method upstream suggested? https://github.com/mayhewj/greenstalk/pull/5
Otherwise LGTM.

**Comment by dargor** [comment]
Bump to last upstream release, tests are green.

**Comment by juippis** [comment]
Thanks!

**Pull request closed without merging**
