### PR TITLE
net-p2p/bitcoin-qt: Add dependency on qtcore[ssl] for Qt4

### PR DESCRIPTION
**Pull request by luke-jr**
@blueness Fixes bug 587880

### CODE REVIEW

**Comment by blueness** [comment]
@luke-jr I missed this when you submitted it.  Does it need refreshing or is it good to go?

**Comment by luke-jr** [comment]
afaik should still be good to go

**Comment by blueness** [comment]
@luke-jr you need to rev bump those.  when you do, don't rev bump the  stable version.

**Comment by luke-jr** [comment]
Why? It doesn't build at all without [ssl], and doesn't change the binaries with it.

**Comment by blueness** [comment]
The added dep isn't just the ssl on dev-qt/qtcore:4[ssl] but also on dev-qt/qtgui:4.  Current systems with bitcoin-qt installed will not have that dependency in vardb.  If bitcoin-qt is the last package depending on dev-qt/qtgui:4 and that isn't in vardb, then it can get unmerged leaving bitcoin-qt without one of its dependency installed.  While this is unlikely given that dev-qt/qtgui:4 will probably be shared between many other pkgs, its still a sloppy practice.

**Comment by luke-jr** [comment]
It already depended on qtgui. What is added is qtcore, which qtgui itself depends on.

**Comment by blueness** [comment]
pushed

**Comment by blueness** [comment]
@luke-jr please ping me on freenode/#gentoo-hardened if i delay on any of these, i've got so much stuff passing by my desk

**Pull request closed without merging**
