### PR TITLE
toolchain@g.o: migrate from git-2 to git-r3

### PR DESCRIPTION
**Pull request by hanetzer**

### CODE REVIEW

**Comment by hanetzer** [comment]
@trofi actually I'ma need to redo the glibc ones a bit; misread a thing and sourceware does
not appear to provide a https:// clone uri for either glibc or gdb.

**Comment by trofi** [comment]
Now these changes are clearly not just `git-2` -> `git-r3` transition but also a bunch of unrelated changes. This makes it hard to review and declare seemingly correct. Sometimes patches shuffle around variable declarations and inherits. This makes variables ordering in ebuilds even less usual that in other ebuilds. I would suggest not doing such invasive changes in one go and do instead them as separate pull requests:

1. handle `git-2` -> `git-r3` in this pull request. This should change only an inherit and maybe variables that are absolutely needed to change.
2. handle whitespace changes in another pull request and only for most recent ebuilds
3. handle code motion around in another pull request as it looks like personal preference change. thus might not be accepted at all

If it's too much hassle let's do at least `1.` here.

**Comment by hanetzer** [comment]
I *would* convert `toolchain.eclass` itself, but there are no live gcc ebuilds to test
it against. Could just drop the git logic entirely and whenever you guys get into a
situation where say `gcc-9.1.0_pre9999.ebuild` could become a thing add the logic
there.

**Comment by trofi** [comment]
Pulled as-is. Thank for the hard work!

**Pull request closed without merging**
