### PR TITLE
Fix install location of cuda binaries.

### PR DESCRIPTION
**Pull request by jvesely**
Turns out running pycuda was no the best test.
I didn't find a better way to do a recursive install of executables. Let me know if I missed something.

### CODE REVIEW

**Comment by jvesely** [comment]
@perfinion , does this help with the tensorflow situation?

**Comment by jvesely** [comment]
ping.
This also fixes installed nvcc.

**Comment by heroxbd** [comment]
@jvesely, Thanks!  Could you please explain in your commit message why nvcc is broken and why your patch fixes it?

**Comment by jvesely** [comment]
> @jvesely, Thanks! Could you please explain in your commit message why `nvcc` is broken and why your patch fixes it?

Added. The content of `bin/` directory need to be installed recursively in correct subdirs, otherwise nvcc fails to find `crt/link.stub` or `crt/prelink.stub`.

**Comment by perfinion** [comment]
I made some changes from this patch and the one on bugzilla and also fixed extras/demo_suite (tensorflow uses deviceQuery)

```
commit ae90e7d8c2d34aed7961f2de107959cb8605559c
Author: Jason Zaman <perfinion@g.o>
Date:   Mon Apr 29 21:22:00 2019

    dev-util/nvidia-cuda-toolkit-10.1.105: Fix installation location of executables
    
    Fixes failures when invoking nvcc. link.stub and prelink.stub need to be
    in crt subdirectory otherwise nvcc fails to find them.
    Also extras/demo_suite were not executable.
    
    Thanks to Jan Vesely and Nathaniel R. Lewis, this fix was derived from
    patches from them.
    
    Closes: https://github.com/gentoo/gentoo/pull/11735
    Closes: https://bugs.gentoo.org/684392
    Signed-off-by: Jason Zaman <perfinion@g.o>
    Package-Manager: Portage-2.3.62, Repoman-2.3.11
```

**Pull request closed without merging**
