### PR TITLE
dev-python/ipyparallel: Drop old + Version bump to 5.2.0

### PR DESCRIPTION
**Pull request by marbre**
@SoapGentoo 

Mainly a copy of 5.1.1 with adjusted dependencies (especially for the test phase).

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@marbre Can you please start removing py3.3 from ebuilds now? py3.3 has been removed from the tree, so it should be fine getting rid of it.

**Comment by marbre** [comment]
@SoapGentoo Done. Will take care of the remaining jupyter related ebuilds and send pull requests.

**Comment by SoapGentoo** [comment]
@marbre only for version bumps. No need to send in PRs just to remove py3.3 :smile:

**Comment by marbre** [comment]
@SoapGentoo Too late :wink: Merge or just close and drop #2709.

**Comment by SoapGentoo** [comment]
@marbre I just mean, you can send in as many PRs as you like, but it's pretty much just cosmetics :wink:

**Pull request closed without merging**
