### PR TITLE
dev-python/leveldb: new package

### PR DESCRIPTION
**Pull request by gitbugged**
dev-python/leveldb provides Python bindings to dev-libs/leveldb. This
dependency is part of several needed to fix #631576.

Signed-off-by: Bob Brooks <gitbugged@cool.fr.nf>

### CODE REVIEW

**Comment by monsieurp** [comment]
Could you find out what's up when generating the documentation?

**Comment by monsieurp** [comment]
@gitbugged ping

**Comment by monsieurp** [comment]
@gitbugged hi!

**Comment by gitbugged** [comment]
@monsieurp sorry, for some reason I didn't catch these pings. From what I can tell this doesn't have docs, but I'm not overly experienced in python packaging. Should I remove docs or try to get help from upstream?

**Comment by mgorny** [comment]
Closing due to no activity. Feel free to reopen when you have time to work on it again (or create a new PR). Please note that GH will not permit you to reopen if you push new commits first.

**Pull request closed without merging**
