### PR TITLE
EAPI-7 cleanups

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by amadio** [comment]
@a17r For rocksdb, please make sure ceph maintainers are ok with dropping the versions you want. Cheers,

**Comment by a17r** [comment]
@chutz ^^ I would assume so, as `ceph-18.2.4-r2` explicitly allows `7.9.2` (has `<dev-libs/rocksdb-7.9.3:=` version limit).

**Comment by amadio** [comment]
Try not to drop `dev-libs/rocksdb-6.14.6-r3`, that might fix the CI for `sys-cluster/ceph`.

**Comment by a17r** [comment]
No, that's not the case, and I mentioned it in the bugs:
https://bugs.gentoo.org/941299
https://bugs.gentoo.org/926707

**Comment by a17r** [comment]
I'm trying to avoid making arch times do unnecessary work here, considering there were 3 parallel rocksdb stabilisations until a few seconds ago.

**Pull request merged**
