### PR TITLE
[WIP] bump gstreamer to 1.16.x

### PR DESCRIPTION
**Pull request by lanodan**

### CODE REVIEW

**Comment by okias** [comment]
How it's looking? Is it OK to move fro WIP ?

**Comment by lanodan** [comment]
Will have to look at it again, thanks for the ping, it's WIP because of the size of gstreamer and how >=make-4.3 in ::gentoo was broken with it but should also get fixed.

**Comment by okias** [comment]
Also please add media-plugins/gst-plugins-meta-1.16

**Comment by okias** [comment]
also I got failure:
```
I/var/tmp/portage/media-libs/gstreamer-1.16.2/work/gstreamer-1.16.2 -I../../../libs -I../../.. -pthread -I/usr/lib64/libffi/include -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -DG_THREADS_MANDATORY -DG_DISABLE_CAST_CHECKS -fno-strict-aliasing -Wall -Wdeclaration-after-statement -Wvla -Wpointer-arith -Wmissing-declarations -Wmissing-prototypes -Wredundant-decls -Wundef -Wwrite-strings -Wformat-nonliteral -Wformat-security -Wold-style-definition -Winit-self -Wmissing-include-dirs -Waddress -Waggregate-return -Wno-multichar -Wnested-externs -fvisibility=hidden -DBUILDING_GST_CONTROLLER -march=native -O2 -flto -fno-stack-protector -pipe -fno-lto -fno-use-linker-plugin -c controller-enumtypes.c  -fPIC -DPIC -o .libs/libgstcontroller_1.0_la-controller-enumtypes.o
controller-enumtypes.c:10:1: error: stray ‘\’ in program
   10 | \#include "gstinterpolationcontrolsource.h"
      | ^
controller-enumtypes.c:10:2: error: stray ‘#’ in program
   10 | \#include "gstinterpolationcontrolsource.h"
      |  ^
controller-enumtypes.c:10:11: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before string constant
   10 | \#include "gstinterpolationcontrolsource.h"
      |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:11:1: error: stray ‘\’ in program
   11 | \#include "gstlfocontrolsource.h"
      | ^
controller-enumtypes.c:11:2: error: stray ‘#’ in program
   11 | \#include "gstlfocontrolsource.h"
      |  ^
controller-enumtypes.c: In function ‘gst_lfo_waveform_get_type’:
controller-enumtypes.c:39:9: error: ‘GST_LFO_WAVEFORM_SINE’ undeclared (first use in this function)
   39 |       { GST_LFO_WAVEFORM_SINE, "GST_LFO_WAVEFORM_SINE", "sine" },
      |         ^~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:39:9: note: each undeclared identifier is reported only once for each function it appears in
controller-enumtypes.c:40:9: error: ‘GST_LFO_WAVEFORM_SQUARE’ undeclared (first use in this function)
   40 |       { GST_LFO_WAVEFORM_SQUARE, "GST_LFO_WAVEFORM_SQUARE", "square" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:41:9: error: ‘GST_LFO_WAVEFORM_SAW’ undeclared (first use in this function)
   41 |       { GST_LFO_WAVEFORM_SAW, "GST_LFO_WAVEFORM_SAW", "saw" },
      |         ^~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:42:9: error: ‘GST_LFO_WAVEFORM_REVERSE_SAW’ undeclared (first use in this function)
   42 |       { GST_LFO_WAVEFORM_REVERSE_SAW, "GST_LFO_WAVEFORM_REVERSE_SAW", "reverse-saw" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
controller-enumtypes.c:43:9: error: ‘GST_LFO_WAVEFORM_TRIANGLE’ undeclared (first use in this function)
   43 |       { GST_LFO_WAVEFORM_TRIANGLE, "GST_LFO_WAVEFORM_TRIANGLE", "triangle" },
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~
make[5]: *** [Makefile:784: libgstcontroller_1.0_la-controller-enumtypes.lo] Error 1
make[5]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:612: all] Error 2
make[3]: *** [Makefile:553: all-recursive] Error 1
make[2]: *** [Makefile:548: all-recursive] Error 1
make[1]: *** [Makefile:742: all-recursive] Error 1
make: *** [Makefile:648: all] Error 2
 * ERROR: media-libs/gstreamer-1.16.2::gentoo failed (compile phase):
```

**Comment by lanodan** [comment]
@okias 
> Also please add
> 
> ```
> media-plugins/gst-plugins-meta
> media-plugins/gst-plugins-gtk
> media-plugins/gst-plugins-a52dec
> media-plugins/gst-plugins-faac
> media-plugins/gst-plugins-faad
> media-plugins/gst-plugins-flac
> media-plugins/gst-plugins-dts
> media-plugins/gst-plugins-mpg123
> media-plugins/gst-plugins-mpeg2dec
> media-plugins/gst-plugins-soup
> media-plugins/gst-plugins-pulse
> media-plugins/gst-plugins-x264
> media-plugins/gst-plugins-x265
> ```

Will be done by @leio as they said they have scripts for doing it.

**Comment by okias** [comment]
@leio @lanodan  any news on this pullreq?

I'd like to bring shortwave (very advanced and cool radio player) into ::guru overlay, but sadly it now depends on gst-1.16, so I'm blocked by this.

**Comment by leio** [comment]
Working on it next in my concentration allowing free time, starting now, but can't be sure to be done this weekend anymore :(

**Comment by okias** [comment]
@leio in case you need something in relation to this PR, feel free to ping me :) (irc or here)

**Comment by lanodan** [comment]
Pushed to gentoo tree, closing.

**Pull request closed without merging**
