### PR TITLE
Minetest 5.1.0 version bump

### PR DESCRIPTION
**Pull request by vilhelmgray**

### CODE REVIEW

**Comment by chewi** [comment]
You'll need to contact the gentoo-dev list about this new account. I haven't had to do this yet so I'm not familiar with the process but I think you simply request it on the list.

Also just become a dev already, you're killing me here. :stuck_out_tongue:

**Comment by orlitzky** [comment]
The eclass associated with GLEP81 will change the permissions on the user's home directory every time a package is installed, potentially leading to conflicts or outright vulnerabilities. For that reason, it's preferred to leave the user's home directory at the default (unset) unless they really need one.

Does "minetest" really use its home directory? Looking through the ebuild, it looks like even in previous versions, the directory `/var/lib/minetest` was essentially unused. The only reference to it is in `files/minetestserver.confd`:

```bash
ARGS="--logfile /var/lib/minetest/minetest-server.log"
```

That path should be `/var/log/minetest/server.log` (or something like that) instead, which might make `/var/lib/minetest` completely unused.

In any case, what I'm getting at is that you should try to drop the home directory from the user ebuild and see what goes wrong. If something other than the confd file needs that path, then it would be preferred to create it in the minetest ebuild and not as the user's home directory. Or, best of all would be if nothing else needs it; then it can simply be dropped after moving the log to the right place.

**Comment by vilhelmgray** [comment]
I changed the IDs to 480 since 481 was already taken. Additionally, I've replaced the `/var/lib/minetest` path with `/var/log/minetest` since it's a more fitting location for the log file.

**Comment by orlitzky** [comment]
> Since there is only one log file, should I bother with the `/var/log/minetest` directory, or just create the log directly in `/var/log`?

The minetest user wouldn't be able to write to `/var/log` directly, so the way you have it is right IMO. Thanks for fixing that.

**Pull request closed without merging**
