### PR TITLE
net-libs/nodejs bumps

### PR DESCRIPTION
**Pull request by hasufell**
@gentoo/proxy-maint 

Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=564594

### CODE REVIEW

**Comment by idella** [comment]
@mgorny  generally commits to net-libs/nodejs I leave to Johan and patrck. Can you tell me what goes on here, please?

**Comment by mgorny** [comment]
@idella, we highlight Johan and wait for Patrick to commit stuff anyway because he doesn't care about anyone else's work ;-P.

@jbergstroem ;-)

**Comment by idella** [comment]
ok

**Comment by jbergstroem** [comment]
yo, why close this?

**Comment by mgorny** [comment]
```
commit 7c542248554decc41c16b19269158c70e819d08f
Author: Julian Ospald <hasufell@gentoo.org>
Date:   Tue Nov 3 21:57:46 2015 +0100

    net-libs/nodejs: version bump to 5.0.0
    
    Gentoo-Bug: 564594

commit 7f2c2ca5c86f58ac12bf2d326b4f52c53f164eb2
Author: Julian Ospald <hasufell@gentoo.org>
Date:   Tue Nov 3 21:57:24 2015 +0100

    net-libs/nodejs: version bump to 4.2.2
    
    Gentoo-Bug: 564594
```

I guess he failed to wait for your review but if you have any remarks, please state them nevertheless.

**Comment by jbergstroem** [comment]
No worries, appreciate all help!

Three notes:
 - icu dep should be 56 for both ebuilds
 - suggesting we do `+icu` since that's what upstream is doing in release builds
 - there's been an increase in tests removed that I assume are failing; I'd like to reduce this upstream so ping me on IRC so we can start figuring it out instead of removing them.

**Pull request closed without merging**
