### PR TITLE
app-misc/anki: bump to 2.1.15

### PR DESCRIPTION
**Pull request by cburroughs**
Bug: https://bugs.gentoo.org/700010
Signed-off-by: Chris Burroughs <chris.burroughs@gmail.com>

### CODE REVIEW

**Comment by cburroughs** [comment]
> Status: x broken

I'm not familiar with all of these checks, but I believe the `MissingTestRestrict` already existed with the prior ebuild version.

**Comment by tsudoko** [comment]
While not directly related to this particular PR, `anki` requires `dev-python/jsonschema` since 2.1.13<sup>[[1]](https://github.com/dae/anki/commit/2f75d1758db66105d12dcbd533cf4c353cadb9eb)</sup><sup>[[2]](https://apps.ankiweb.net/docs/changes.html#changes-in-2.1.13)</sup> and won't run without it. It's currently not present in `RDEPEND`.

**Comment by tsudoko** [comment]
`USE=recording` requires `dev-python/pyaudio` too<sup>[[1]](https://github.com/dae/anki/blob/5411cf06c1254fba5f0cd5dc1953edc41c5b1cb1/aqt/sound.py#L7-L19)[[2]](https://github.com/dae/anki/blob/5411cf06c1254fba5f0cd5dc1953edc41c5b1cb1/anki/sound.py#L411-L412)[[3]](https://github.com/dae/anki/blob/5411cf06c1254fba5f0cd5dc1953edc41c5b1cb1/anki/sound.py#L310-L321)</sup>

**Comment by cburroughs** [comment]
Rebased ontop of 41fc05a8d3ea6aee49bcff68ddce01151dec6a62

Thanks for the comments! I think  those issues are covered by some of https://bugs.gentoo.org/645314 and https://bugs.gentoo.org/688798

Since they are preexisting issues with 2.1.13 I'd prefer to them handled separately from this little bump.

**Comment by cburroughs** [comment]
Rebased on top of 064af661d0c9a31cecdf348632bc5603333a9149 and updated the year.  I'm unsure of what the next step is to get this landed.

**Comment by cburroughs** [comment]
Rebased on top of 78368340e8df47f36adcd144c744197eebadfff5

@a17r or @mgorny I know you are not listed as a maintainer, but you are the last two people to have touched `app-misc/anki`.  Would you mind taking a look at this PR?

**Comment by cburroughs** [comment]
At this point, #16054 should probably be preferred.

**Pull request closed without merging**
