### PR TITLE
media-sound/lilypond: fix compilation with fontforge wrt #557160

### PR DESCRIPTION
**Pull request by lilrc**
Package-Manager: portage-2.2.23

### CODE REVIEW

**Comment by lilrc** [comment]
Since I am an active user of this package I can proxy-maintain it, as it seems to be abandoned by the maintainer. I would like to get the other lilypond bugs fixed and bump the ebuild for the developement release.

**Comment by hasufell** [comment]
@radhermit

**Comment by mgorny** [comment]
Indeed I see many bugs open. I'll try to get in contact with the maintainers.

**Comment by mgorny** [comment]
@lilrc: good news! The maintainers will be happy to have a proxied maintainer. Please add yourself to metadata.xml and the proxy-maintainers herd.

**Comment by mgorny** [comment]
By the way, for git patches it's usually better to take the git format patch (with the commit message etc.)

**Comment by lilrc** [comment]
@mgorny: I added myself as maintainer in metadata.xml and sent a mail to proxy-maint@gentoo.org, as I guess that is the way to be added to the proxy-maintainers herd. Also, do you mean sending the patches by mail rather than via pull requests?

**Comment by mgorny** [comment]
1. You don't get added to proxy-maint. Those are people who can commit stuff for you when nobody else's around to review it since you don't have direct commit access. And you don't need to mail them, we just highlight them via github.
2. I meant the patches in FILESDIR. You could get them via `git format-patch` to have full patch metadata.

@gentoo/proxy-maint, need approval for making this package `<herd>proxy-maintainers</herd>`.

**Comment by idella** [comment]
indeed yes

**Comment by idella** [comment]
metadata.xml is missing the line
<herd>proxy-maintainers</herd>
following 	
      <herd>scheme</herd>

hmm:
```ebuild
               <email>hkBst@gentoo.org</email>
                <name>Marijn Schouten</name>
```
It appears he is an ex dev, never heard of him. So current line 5-8 will also require deleting, and the patch here needs ammending accordingly.

**Comment by lilrc** [comment]
@idella: Fixed. Also, all lilypond bugs [1] need to be reassigned.

[1] https://bugs.gentoo.org/buglist.cgi?quicksearch=lilypond

**Comment by mgorny** [comment]
@idella … You could really consult the list of developers before calling someone an ex-dev and telling people to remove him. He's an active developer alright, though on a devaway. And that doesn't justify remove people behind their backs.

@lilrc I'm sorry for the confusion. Please restore hkBst.

**Comment by idella** [comment]
hmm sure, fair comment

**Comment by lilrc** [comment]
@mgorny, @idella: Fixed. Also I rebased the commits to remove any noice and confusion.

**Comment by lilrc** [comment]
Oh, sorry! There was a merge conflict I missed... I will fix and rebase right now! Just a few minutes, please.

**Comment by lilrc** [comment]
Oh, sorry again for the noice. I realised it was only on my local copy of the repo there were issues. The commits should be fine. :)

**Comment by idella** [comment]
Will do this first thing to morrow. Late. Sorry for presuming dev had left.

**Comment by idella** [comment]
Test run drew error; see  Bug 557160

**Comment by idella** [comment]
@hasufell  if you got anything here,  that's fine

**Comment by idella** [comment]
The ebuild has been built effectively by a dev and a user in their systems, confirming the patch is functional. The dep fontforge itself has issues distinct to the lilypond package. I shall likely commit it tomorrow.

**Comment by idella** [comment]
pushed

**Comment by lilrc** [comment]
Thank you!

**Pull request merged**
