### PR TITLE
net-p2p/retroshare add 0.6.7

### PR DESCRIPTION
**Pull request by gentoo-setan**
This:
1. Updates to 0.6.7
2. Adds new `plugins` flag
3. Adds new (needed) dependencies if plugins are needed
4. Unifies coding style

Closes: https://bugs.gentoo.org/927207
WARNING: this PR closes a bug^ but I did not put that in the approprieate commit.

### CODE REVIEW

**Comment by gentoo-setan** [comment]
This is my second PR. I hope that I have followed the protocol well

**Comment by gentoo-setan** [comment]
I see that "Closes" needed to be in the commit message, not the github one.
Can somebody please tell me how to change the old commit message?

**Comment by G10h4ck** [comment]
@gentoo-setan to rewrite last commit message just use `git commit -a --amend` then edit the commit message the `git push --force` to update the PR

**Comment by G10h4ck** [comment]
Anyway very nice profile image ;)

**Comment by gentoo-setan** [comment]
> Anyway very nice profile image ;)

Thanks.

I think I broke something :<

**Pull request closed without merging**
