### PR TITLE
dev-db/mysql: add 8.0.36

### PR DESCRIPTION
**Pull request by parona-source**
https://github.com/parona-source/mysql-server/releases/tag/mysql-8.0.36-patches-01

### CODE REVIEW

**Comment by parona-source** [comment]
Adding patches for musl and testing they work.

**Comment by matoro** [comment]
This still dies for me due to a timeout on the overall test suite (I think).  In the time it takes to hit timeout, 44% progress, 31 failed tests.  On clean glibc stage3.

```
The servers were restarted 1386 times
The servers were reinitialized 15 times
Spent 55529.309 of 18065 seconds executing testcases
 
Check of testcase failed for: rpl.rpl_master_connection
 
Timeout: Failed 31/1298 tests, 97.61% were successful.
 
Failing test(s): rpl.rpl_innodb_bug28430 rpl.rpl_eventlog_psi_memory rpl.rpl_parallel_ddl_myisam clone.remote_dml_replace rpl.rpl_semi_sync_turn_on_off_optimize_for_static_plugin_config rpl_gtid.rpl_mixed_temp_table_stored_function rpl_gtid.rpl_async_conn_failover_checks rpl_nogtid.rpl_upgrade_slave_master_info rpl.rpl_parallel rpl_gtid.rpl_gtid_while_super_read_only clone.ddl_dml rpl_gtid.rpl_perfschema_applier_status_by_worker_gtid_skipped_transaction_mts rpl.rpl_many_optimize federated.federated_server rpl.rpl_channel_creation_under_replica_load rpl_gtid.mysqldump_bug33630199 rpl_gtid.rpl_delayed_slave rpl.rpl_mysql_upgrade rpl.rpl_parallel_ddl_innodb rpl_gtid.rpl_wait_for_executed_gtid_set rpl_gtid.rpl_gtid_row_event_max_size rpl_nogtid.rpl_row_event_max_size rpl_nogtid.rpl_loaddatalocal rpl.rpl_master_connection rpl_nogtid.rpl_invoked_features_myisam rpl.rpl_connection_compression
 
The log files in var/log may give you some hint of what went wrong.
 
If you want to report this error, please read first the documentation
at http://dev.mysql.com/doc/mysql/en/mysql-test-suite.html
 
2336 tests were skipped, 96 by the test itself.
 
Test suite timeout! Terminating...
mysql-test-run: *** ERROR: Test suite aborted
```

Complete log:  [build.log](https://github.com/gentoo/gentoo/files/14159139/build.log)

**Comment by parona-source** [comment]
It doesn't appear it can disabled, just modified. The current default appears to be 300 minutes but some scenarios set it a higher value.

Valgrind is x6, with sanitizers x2 (may be applied on top of the previous), callgrind is a another x6 and debug is set to a hard value of a week.

Is there any opinions on what is reasonable here?

**Comment by thesamesam** [comment]
> It doesn't appear it can disabled, just modified. The current default appears to be 300 minutes but some scenarios set it a higher value.
> 
> Valgrind is x6, with sanitizers x2 (may be applied on top of the previous), callgrind is a another x6 and debug is set to a hard value of a week.
> 
> Is there any opinions on what is reasonable here?
> 
> The value can be modified with an env variable MTR_SUITE_TIMEOUT which accepts the timeout in minutes.

Let's try 8x, I think. Valgrind is a good approximation, and then a bit more again.

**Comment by parona-source** [comment]
New test failures showed up on glibc with TLS 1.3

https://bugs.mysql.com/bug.php?id=113258

**Pull request closed without merging**
