### PR TITLE
dev-python/sabyenc: add 6.1.0

### PR DESCRIPTION
**Pull request by joecool1029**
Not used by current sabnzbd yet, but will be by next release. Might as well get it in the tree now.

### CODE REVIEW

**Comment by Kangie** [comment]
LGTM!

**Review by mgorny — CHANGES_REQUESTED** [review]
```
 * ERROR: dev-python/sabyenc-6.0.0::gentoo failed (prepare phase):
 *   The source directory '/tmp/portage/dev-python/sabyenc-6.0.0/work/sabyenc-6.0.0' doesn't exist
```

The repository has apparently been renamed upstream, and since the checksum matches, it has been renamed prior to you generating the Manifest.

**Comment by joecool1029** [comment]
My bad on there. I can submit this as the new package name, but should I rename the old or wait for it to fall out of use in a few months and treat the old and new as different packages? net-nntp/sabnzbd is the only package depending on this in the tree.

**Comment by mgorny** [comment]
Does it install the same Python module or has it been renamed already? If the former, just update `HOMEPAGE`, `SRC_URI` and `<remote-id/>` and set `S` appropriately.

**Comment by joecool1029** [comment]
ok I've bumped it again and added the changes to get it working, thanks!

**Comment by joecool1029** [comment]
I'm closing this PR, will make a new one to move the package and add the new sabnzbd alpha for testing.

**Pull request closed without merging**
