### PR TITLE
dev-util/codeblocks: version bump to 17.12

### PR DESCRIPTION
**Pull request by band-a-prend**
dev-util/codeblocks: version bump to 17.12 pull request

Code::Blocks IDE package version bump to 17.12 with
switching 'WX_GTK_VER' from x11-libs/wxGTK:2.8 to x11-libs/wxGTK:3.0
( codeblocks-17.12.ebuild )
and adding branch for x11-libs/wxGTK:3.0-gtk3
codeblocks-17.12-r300.ebuild

This also:

adds a new USE flag 'fortran' which controls the
building of 'FortranProject plugin' for Code::Blocks IDE
( https://sourceforge.net/projects/fortranproject/ )
after applying of 'FortranProject_autotools_build.diff' patch;

adds appropriate patch 'FortranProject_autotools_build.diff' to 'files' dir;

adds info about new co-maintainer of 'dev-util/codeblocks' package to 'metadata.xml'
and info about new USE-flag 'fortran' that controls applying the patch for 'FortranProject' plugin building that mentioned above;

adds Manifest data (size, blake2b and sha512 checksums) about 'codeblocks_17.12.tar.xz' tarball.

@gentoo/wxwidgets
@leio 
@gentoo-repo-qa-bot 

Closes: https://bugs.gentoo.org/643494

### CODE REVIEW

**Comment by monsieurp** [comment]
@leio ping

**Comment by leio** [comment]
will try to find time for review and merge before 15th March, in contact with author via e-mail

**Comment by monsieurp** [comment]
Cool, I'm assigning the PR to you then.

**Comment by leio** [comment]
Sorry for the delay, got too busy with work work things. I'll get this looked over this weekend for sure, thanks for patience

**Comment by leio** [comment]
Lets call it an extended weekend :(

Anyhow, your commits have the summary twice - don't repeat it after the first line. First line is summary, then empty line, then details - you are repeating the summary in details, don't.
Manifest should be updated in the same commit as the ebuild for it is added, not a separate commit; after finding the mistake of not having updated it for the same commit, you can rebase or amend it in with git.
The USE flag addition should probably also be in the same commit as the one that added the ebuild having IUSE=fortran, otherwise that commit is technically broken, albeit not visible to users - but the CI bot might bisect into it and trip up or something. Though in this case fortran is a global USE flag as well, and that's not the case as repoman/CI will be happy with the global description — but noting in general for the future. It is good to have a detailed description here though, as it's a more detailed one, could mention that in the commit summary as well explicitly, but that's just perfectionism and not really needed at all.

Functional review to come soon as well. Feel free to try to fix the commit logs and too much splitting of commits meanwhile, but not too important - it's easy for me to rebase appropriately as well. But I'd imagine it'd be a good practice for you for the future. I envision one commit to add yourself as maintainer, another to bump (which adds the fortran patch and updated Manifest as well, and optionally the fortran USE flag detailed descrtipion), another to add a 3.0-gtk3 version. You could also not introduce the fortran support at first, but do the bump first and then a second commit to add the patch AND add the changes to the ebuild in the separate commit - this would ease review a bit. As they'd be pushed at once, that'd be fine without a revbump.

Also there is little point to have a WX_GTK_VER=3.0 and WX_GTK_VER=3.0-gtk3 together in ~arch. You should add the 3.0-gtk3 to profiles/package.mask (alongside filezilla for the coordinated conversion to 3.0-gtk3) if 3.0-gtk3 isn't quite as good as gtk2 using version yet, or just have only 3.0-gtk3 version if it's great. Code::Blocks isn't something many people have, so the coordinated effort aspect isn't very important and just moving over to 3.0-gtk3 immediately should be fine (but as said, then the gtk2 version mostly just adds maintenance effort).

**Comment by band-a-prend** [comment]
It looks like I undestand request to make [separate atomic commits](https://wiki.gentoo.org/wiki/Gentoo_GitHub#Separate_.28or_.22atomic.22.29_commits) too literally.
I'll try to rebase commits before weekends.

Also I prefer currently to have WX_GTK_VER=3.0-gtk3 separate branch in profiles/package.mask because some additional interface  glitches comparing with WX_GTK_VER=3.0.

**Comment by leio** [comment]
Yeah, atomic commits are good, but each such commit should work individually too. So that's why e.g. the manifest should be updated in the same commit, otherwise the change is broken for use by package manager at that commit.
Please leave a comment when done, not sure when things are just temporary pushes and when ready (having these PR 1 and 2 in mind..). You'll probably need to force push due to rebases.

Though maybe check back here before working on things later - I might have managed to add proper ebuild review by then, not just commit logs/atomicity

**Comment by band-a-prend** [comment]
Yes, I'll comfirm the when do all rebase and squash changes.The PR1 & 2 was made to sync my fork (master and feature branches) with parent gentoo/master branch as I want to have more recent package.mask file.  At least I didn't expect the first one is shown in current pull request as it's from not the same branch where current PR about codeblocks was made.28.03.2018, 10:57, "Mart Raudsepp" <notifications@github.com>:
Please leave a comment when done, not sure when things are just temporary pushes and when ready (having these PR 1 and 2 in mind..). You'll probably need to force push due to rebases.

**Comment by band-a-prend** [comment]
I finished the rebasing. The only problem is that I don't know how resolve conflicts within 'package.mask' file. I tried to add info about "=dev-util/codeblocks-17.12-r300" to old (initial) and newest 'package.mask' file but conflicts appers again as there are many changes since the initial PR commit. Could you resolve this conflict?

It seems that 'package.mask'  breaks last commit as ebuild itself is definitly working as it's identical to ebuild from previous commit.

**Comment by band-a-prend** [comment]
I resolved 'package.mask' conflict by preliminarily updated my fork master branch and after that by updated feature branch. But while resolving conflict my fork master branch syncing with feature branch (oops). And I still need to make rebase to restore my master branch, update feature branch and move feature branch updating commit before commits about codeblocks version bump... if current state of isn't good because of additional commits again, isn't it?

P.S. 
That is strange that gentoo-repo-qa-bot doesn't remove info about failed checking of commits that doesn't exist any-more.

**Comment by band-a-prend** [comment]
@leio, I complited the rebase and there is still a conflict of 'package.mask'. If I resolve it here (on github PR page) the commit "Merge branch 'master' into feature"appears in this PR (with all changes from upstream gentoo/master branch and I think it's not good idea). The 'package.mask' file  is updated periodically so the conflict will arise again after it's changing in  upstream gentoo/master branch. 

Could you resolve it when Merge PR to upstream master if all is Ok and if you decide to do it? I don't know how handle this situation with continiously changing files.

**Comment by leio** [comment]
I can handle the package.mask conflicts during merge, yes. However your commit has more additions that yours it seems, unless GH is fooling me. BUT I meant that you put the mask together with filezilla in the same block, not make a new one on the top of the mask file. That area shouldn't change much and we probably won't get conflicts. The point is to have all these wxGTK:3.0-gtk3 masks together and then try to unmask them all at once. In other words, put the codeblocks gtk3 revision mask right below filezilla, with no new comment lines at all - just the package row added right after filezilla, as if they were masked together

**Comment by band-a-prend** [comment]
I took the newest 'package.mask' file from upstream master for last commit as with the file of month ogo there were too much conflicts with actual version of file due to many updates of it since begining of March. It's strange that there are additional blocks that are alredy presented in upstream master. "Resolve conflict" show only my block. Could I leave the recent copy of this file and just remove this block partially to filezilla or it's better to commit sync with upstream master branch and replace this commit before my commits about codeblocks?

**Comment by leio** [comment]
I'm not really following, but how I would want this is:

A separate package.mask commit right before -r300 revision adding commit, or just in the same commit, that just adds it to the existing mask. That is, not at the top, but together with filezilla, like this:

```
# Bernard Cafarelli <voyageur@gentoo.org> (8 May 2017)
# Coordinated conversion to wxGTK:3.0-gtk3
# Drop mask after migration of existing wxGTK:3.0 users
=net-ftp/filezilla-3.30.0-r300
=net-ftp/filezilla-3.31.0-r300
=dev-util/codeblocks-17.12-r300
```

So you just add it to the existing block, not make a new one. This is an old one, so it's much less likely to conflict as well during the time it's updated and I get to fully review it.

I'm getting close to getting my desktop up to date again, so I hope to be back in reviewing things and doing work myself in more full force soon.

**Comment by band-a-prend** [comment]
Done. 
I finally sync my fork 'master' and 'feature' branches with upstream 'gentoo/master' and made rebase.
So now the commit about 'package.mask' contains only one additional string to add.
It seems there a conflict  could be appear when upstream 'package.mask' file will change so commit can become 'broken'. Does the 'package.mask' patch becomes inapplicable if inside upstream version of this file string shift is appears?

**Comment by band-a-prend** [comment]
Update ebuilds:

1. Fix src_prepare section by replacing "eautoconf" and "eautomake"
with "eautoreconf" to regenerate autotools scripts and to avoid
warning message:
> * Automake used for the package (1.13.4) differs from the installed version (1.X.Y).
> * Forcing a full rebuild of the autotools to workaround.

Remove einfo output from src_prepare section.

Remove " touch "${S}"/revision.m4 -r "${S}"/m4/acinclude.m4"
from src_configure section as autotools files regenerated now in src_prepare.


2. Remove needless "eutils" item from "inherit" section


3.  Fix GTK+ icon cache QA notice
> * QA Notice: new icons were found installed but GTK+ icon cache
> * has not been updated:
> ...

by adding "gnome2-utils" to inherit block
and "gnome2_icon_cache_update" to "pkg_postinst()" and "pkg_postrm()" sections.


4. Add clarifying comments about conditional section of choice
of "contrib" and/or "fortran" USE-flags.

**Comment by leio** [comment]
Now waiting on build fixes of USE=fortran with gcc7; or bumping without new fortran support at first and adding that in revbumps (plural due to for both 3.0 and 3.0gtk-3 WX_GTK_VER slots) later on, once solved.

**Comment by band-a-prend** [comment]
Update ebuilds:

1. Fix USE="fortran" GCC7 compilation error with upsteam patch.
2. Remove direct passing "-g" compiler option to CFLAGS and CXXFLAGS when USE="debug" by appropriate autotools files patching.
3. Remove USE="stacis-libs" flag with permanent passing econf "--disable-static" within src_configure() section.
4. Update SRC_URI from "mirror://sourceforge/codeblocks/${P/-/_}.tar.xz" to "mirror://sourceforge/${PN}/${P/-/_}.tar.xz"

USE="pch" still presented as it noticeably reduces compilation time of codeblocks on the low- and mid-end pc configurations.

**Comment by leio** [comment]
I don't think --with-wx-config passing is needed, as the eclass should set things up so that the default wx-config honors what is chosen via WX_GTK_VER. However, it shouldn't hurt to be explicit here, so just a comment, no need to change unless you want to and test it through

**Comment by leio** [comment]
automake and autoconf are still in DEPEND — autotools.eclass takes care of it instead. I'll remove those myself with a small follow-up commit

**Comment by leio** [comment]
Any particular reason we don't just always enable the fortran plugin? It's not like it demands fortran compiler itself as an additional dependency. Would simplify the --with-plugins as well and just be always available? Though in that logic, same about USE=contrib I suppose, and then it might be a bit much, especially if the plugins get always enabled out of the box too?

**Comment by leio** [comment]
Can tinyxml get unbundled at some point? Depending on, compiling against and using system version instead of the bundled code

**Comment by leio** [comment]
Otherwise merged after rolling the fortran patches to a patchset hosted on my distfiles directory and changing the bump commits to use it, plus two follow-up commits https://github.com/gentoo/gentoo/commit/96338dd36fda6d4aeebf9ba20e9282160c5554e8 and https://github.com/gentoo/gentoo/commit/3391e6b07d5fb349c45ea637f19765cbada8cd98

**Comment by band-a-prend** [comment]
> I don't think --with-wx-config passing is needed, as the eclass should set things up so that the default wx-config honors what is chosen via WX_GTK_VER. However, it shouldn't hurt to be explicit here, so just a comment, no need to change unless you want to and test it through

I'll try to test it with also installed and chosen via wxwidgets-config others versions of wxGTK.

> Any particular reason we don't just always enable the fortran plugin? It's not like it demands fortran compiler itself as an additional dependency. Would simplify the --with-plugins as well and just be always available? Though in that logic, same about USE=contrib I suppose, and then it might be a bit much, especially if the plugins get always enabled out of the box too?

I'm still thinking about merging it to "contrib" flag or not. It's also maybe worth to update "live"-ebuild (codeblocks-9999-ebuild) to sync it mainly with new codeblocks-17.12.ebuild. But as it's "trunk" doesn't include mentioned fortran plugin then "contrib" use-flag will be install not the same set of plugins. Also I'm thinking about future possibility of updating "fortran" plugin if it will be possible. 

Use="contrib" significaly increases compilation time of this package and some users may not require this  set of plugins presence if they for example just want to use batch running of codeblocks (it has such mode) for automated build of projects.

> Can tinyxml get unbundled at some point? Depending on, compiling against and using system version instead of the bundled code

The codeblocks-17.12 release contains fedora unbundles patch that allow to use system installed [squirrel](https://sourceforge.net/p/codeblocks/code/10872/), [astyle](https://sourceforge.net/p/codeblocks/code/10873/) and [tinyxml](https://sourceforge.net/p/codeblocks/code/10874/). But there are some problems exists that must be fixed and tested before emplementing using of this iside codeblocks ebuilds.

1. I'm not tested yet compilation with system installed dev-lang/squirrel.

2. Package dev-util/astyle-3.0.1 doesn't create symlink 'libastyle.so' and without it linking error appears during compilation like couldn't find '-lastyle'. If symlink is created manualy - linking is successfull.

3. Codeblocks 17.12 is incompatible with new dev-util/astyle-3.1 as last has some changes in implimentations of "ASSourceIterat" class and some others small changes that result in compilation errors.

4. Instalation of dev-libs/tinyxml doesn't create pkg-config file "tinyxml.pc" that is requred during configuration ("./configure") of codeblocks to chek is it use system tinyxml or not. Also this package has "stl" use-flag so I need to test is it worth to create this file with addition parameter "-DTIXML_USE_STL=YES" inside "$TINYXML_CFLAGS" variable of not dpending on setting of this use-flag. Codeblocks add  "-DTIXML_USE_STL=YES" of bunled tinyxml but I don't know is it required in common case.  

Anyway I need additional testing of modyfied ebuilds of dev-util/astyle-3.0.1 and dev-libs/tinyxml, then pull request changes of it and after thier merging it could be add as build dependencies of codeblocks. At least changes in ebuild of this packages could be usefull. The resolving all problems with dev-util/astyleastyle also will close [bug #383037](https://bugs.gentoo.org/383037).

**Pull request closed without merging**
