### PR TITLE
dev-lang/php: Fix implicit declaration of function '__c11_atomic_load'

### PR DESCRIPTION
**Pull request by listout**
This is observed with GCC14 and upstream commit[0] fixing the bug is merged only in RC branches.

[0]: https://github.com/php/php-src/commit/72526609413e8a8cd768ed4966c17b1a9db6c12c.patch

### CODE REVIEW

**Comment by orlitzky** [comment]
Thanks! Since these are build fixes, I think we can apply them directly to php-8.2.15.ebuild and php-8.3.2.ebuild (without an `-r1`)`, that way people on gcc-13.x don't have to rebuild PHP.

**Comment by listout** [comment]
@orlitzky We might need a revision bump for error/build failure like there, for reference https://wiki.gentoo.org/wiki/Modern_C_porting#Is_this_cosmetic.3F

**Comment by eli-schwartz** [comment]
Yes, if the patch fixes a crash on GCC 13 in addition to a compilation failure on GCC 14 (and ModernC failures are at best a potential crash and at worst a guaranteed !amd64 crash) then a revbump is appropriate.

For something like filter-lto I likely wouldn't revbump.

**Comment by orlitzky** [comment]
Ok, better safe than sorry. I forgot that php-.8.2.15 is stable on one arch already too. Thanks.

**Pull request closed without merging**
