### PR TITLE
app-backup/kfoldersync: version bump

### PR DESCRIPTION
**Pull request by Vindex17**

### CODE REVIEW

**Comment by monsieurp** [comment]
LGTM but let's wait for @gentoo/kde and @kensington input.

**Comment by kensington** [comment]
As the upstream maintainer how about maintaining it directly via @gentoo/proxy-maint ?

**Comment by Vindex17** [comment]
OK, what do I have to do?

**Comment by monsieurp** [comment]
File a bug and ask for maintainership of the package.

**Comment by idella** [comment]
isn't that ahead of time ?

**Comment by titanofold** [comment]
Removing the old version should be done separately from adding the new version.

**Comment by Vindex17** [comment]
Can you accept it now?

**Comment by idella** [comment]
I will begin a review yes. The actual designation of proxy . user maintainer occurs at the point of addition to the tree.

**Comment by idella** [comment]
1. IUSE="" is empty.  In modern EAPI values, it m,ay be left out entirely 

2.
```ebuild
DEPEND="${RDEPEND}
        sys-devel/gettext
"
```
sys-devel/gettext is in @system and is redundant

**Comment by idella** [comment]
you also need to edit metadata.xml to add yourself as proxy maintainer

https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide

**Comment by mgorny** [comment]
> 1. IUSE="" is empty.  In modern EAPI values, it may be left out entirely 

This does not depend on EAPI. Variables can be always left out. However, keeping them is good style since it saves future contributors from looking for it and figuring out where to add it.

> 2. [...] sys-devel/gettext is in @system and is redundant

No, it is not.

**Comment by idella** [comment]
mgorny are you trying to be helpful of just argumentative for its own sake.

sys-devel/gettext might not BE in @system but it is pulled in by it.
It is gokturk who first hi-lighted this and prompted it as redundant in such an ebuild

Do us all the courtesy of clarifying the position on this and any other package in @system, or pulled in by @system.

**Comment by mgorny** [comment]
It is pulled in implicitly on *some* (but not all) systems. You should DEPEND on it explicitly if the project is using gettext to compile message files. It is also a good idea to RDEPEND on virtual/libintl if you are using the `gettext()` function.

**Comment by Vindex17** [comment]
Just at compile time. At runtime I use the ki18n library

**Comment by idella** [comment]
Very well I we shall follow that guide accordingly.

**Comment by idella** [comment]
All looks fine

**Pull request closed without merging**
