### PR TITLE
dev-db/redict: add 7.3.1, drop 7.3.0-r1

### PR DESCRIPTION
**Pull request by navi-desu**
This release of redict fixes 3 CVEs as per https://redict.io/posts/2024-10-01-redict-7.3.1-released/

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by navi-desu** [comment]
due to an issue bumping the version, one of the tests is failing (an assert on the version)

**Comment by navi-desu** [comment]
i marked the given test as skip for this release (since it's broken upstream, and it's just a version number check)

**Review by arkamar — CHANGES_REQUESTED** [review]
Could you please split addition and removal to two commits and reference bug https://bugs.gentoo.org/940609 in both of them? Otherwise LGTM, tests pass for me.

**Comment by navi-desu** [comment]
i was unsure how to reference it (since the bug asks to not mark it as resolved, i assumed "Closes: ..." would be wrong), so i tagged both as just "Bug: ..."

**Comment by arkamar** [comment]
> i tagged both as just "Bug: ..."

Yes, `Bug:` trailer is the correct one in this case. Thanks!

**Review by arkamar — APPROVED** [review]

**Pull request closed without merging**
