### PR TITLE
Drop old versions of packages maintained by me@rahil.rocks

### PR DESCRIPTION
**Pull request by mattst88**
`app-containers/aardvark-dns` and `app-containers/netavark` have their `Manifest` files reduced from 77K to ~600 bytes each.

(Please occasionally drop old versions of your packages in the future)

### CODE REVIEW

**Comment by thesamesam** [comment]
Did you miss https://github.com/gentoo/gentoo/pull/34744?

**Comment by mattst88** [comment]
Yes, although I don't know how I should have found it, given that his github account isn't wired up:

> app-containers/aardvark-dns: @zmedico, ~~me[at]rahil.rocks~~, @gentoo/proxy-maint

**Comment by thesamesam** [comment]
I'm not saying you should've -- just that the other one existed (although academically: you may have been able to find it via p.g.o's PR tab for a package). We should figure out what's wrong with the mapping there for the email.

**Comment by rahilarious** [comment]
> We should figure out what's wrong with the mapping there for the email.

This is what I know so far. 
When I create fresh PR and bot automatically does assignment it wrongly shows email address and doesn't tag github user (like app-containers/aardvark-dns: ~~me[at]rahil.rocks~~, @gentoo/proxy-maint )

but when I do reassign by adding  "[please reassign]" in title it correctly tags user ( like app-containers/aardvark-dns: @ zmedico, @ rahilarious, @gentoo/proxy-maint )

**Pull request closed without merging**
