### PR TITLE
dev-ruby/backports: initial commit

### PR DESCRIPTION
**Pull request by junghans**
In the dependency tree for https://github.com/travis-ci/travis.rb, @gentoo/ruby please review as ruby ebuilds are usually not my cup of tea.

### CODE REVIEW

**Comment by junghans** [comment]
@gentoo/ruby: For this one I cannot really figure the test stuff out!

**Comment by graaff** [comment]
I can have a look but I'm not sure when I'll have time.

**Comment by junghans** [comment]
Update: tests actually run, so the ebuild is ok, but some tests fail.

**Comment by graaff** [comment]
I don't see any test failures with your ebuild. What problems are you seeing?

There is also a "spec" directory which in this case does not contain rspec code but mspec code. mspec is used to run the rubyspecs (the specs for the language itself). See https://rubygems.org/gems/mspec
We don't have this packaged at the moment. Not sure if we want to do that right now, given that backports also has other tests that we can run.

**Comment by junghans** [comment]
Got it! I missing dependency, one test needs `rails`. I would be ok with only run the 50 tests, which the ebuild does currently!

**Pull request merged**
