### PR TITLE
Updates for asahi packages

### PR DESCRIPTION
**Pull request by chadmed**
This PR includes updates and stabilisation for existing Asahi-related packages, as part of the effort to get bootable install media ready without needing to rely on the Asahi overlay.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by chadmed** [comment]
cc @thesamesam @immolo

**Comment by thesamesam** [comment]
I assume that the versions need updating first then can merge it (ditto the PR that depends on this)?

**Comment by chadmed** [comment]
@thesamesam have done so for both branches/PRs. Thanks!

**Comment by thesamesam** [comment]
Done, thanks, with fixed copyright header (please use `pkgcheck scan --commits`).

**Pull request closed without merging**
