### PR TITLE
dev-libs/openssl: serialize install as it's racy

### PR DESCRIPTION
**Pull request by DerDakon**
Bug: https://bugs.gentoo.org/651880

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Your initial report was for `openssl-1.0.2o`. Have you checked the other versions being affected as well before opening this PR? Because if not please do so and only change the versions that are affected by this.
For the record, I (re)compile openssl with `MAKEOPTS="-j32"` frequently and never stumbled across this issue. Thus I am a bit reluctant to apply this change.

**Comment by DerDakon** [comment]
This seems to be fixed for the 1.1 branch with https://github.com/openssl/openssl/commit/70a56b914772e6b21cda2a5742817ae4bb7290f1, which is not present in 1.0.2.

**Comment by Whissi** [comment]
In this case I'll add this patch to our patch set. Better than restricting parallel execution.

**Comment by DerDakon** [comment]
Or just nuke that script and it's execution and call plain "mkdir -p" instead ;)

**Comment by Whissi** [comment]
For the records, this is more or less a follow-up of https://bugs.gentoo.org/196554 and our fix-parallel-* patch series.

**Comment by Whissi** [comment]
Pushed, thanks for the report Rolf!

**Pull request closed without merging**
