### PR TITLE
media-video/mpv: revbump to 0.17.0-r6

### PR DESCRIPTION
**Pull request by Coacher**
CC @wraeth. Sam, please keep the previous patchset tarball for a couple more days JIC.

### CODE REVIEW

**Comment by mgorny** [comment]
@Coacher, please try to work a bit on your commit messages. 'Revbump to X' does not really tell us anything useful. Please use the summary line to describe the most important change, i.e. 'backport memleak patches'.

**Comment by Coacher** [comment]
I've updated the commit message. Please re-review.

**Comment by mgorny** [comment]
Looks good, thanks. Should I merge it or wait for @wraeth?

**Comment by Coacher** [comment]
@mgorny, feel free to merge.

**Comment by Coacher** [comment]
Thank you very much, @dlan17.

**Pull request closed without merging**
