### PR TITLE
Version bumps of dev-utils/electron and app-editors/atom.

### PR DESCRIPTION
**Pull request by elprans**
This bumps electron to 1.3.13, fixes [compilation failures with CUPS](https://bugs.gentoo.org/show_bug.cgi?id=607462), and also adds the latest released version of the Atom editor.

### CODE REVIEW

**Comment by mpkh** [comment]
whatever, I don't like anything old, I accept, lazy to push, please take it someone

**Comment by elprans** [comment]
@mpkh Would you like me to remove you from the package metadata?

**Comment by mpkh** [comment]
@elprans not, it's my overtaken ebuild, you bump it into 1.13.1 (only if PR will be accepted)
I'm running 1.14.0_beta2, people often complain to me about errors in your version
I tell them that you're doing it in right way but I aslo can't use your version :D
so one day I wish complexity you introduced will bring real effort to people
either developers like me will be able to bump it easily and people will get less errors, there I will try to help some...

**Comment by elprans** [comment]
I'm not aware of any outstanding issues with the ebuild (minus the cups compile error, which this PR fixes), care to provide more info?

**Comment by mpkh** [comment]
@eliasp not at the moment, maybe @aliceinwire can provide something
for me major blocker is ebuild complexity (and my own free time)

I will be glad if you will either support versions alike `1.14.0_beta2` and there share me instructions how can I bump it into next beta etc...

**Comment by elprans** [comment]
Bumping app-editors/atom is actually not that hard.  All you need to do is go through ``package.json`` (sometimes recursively) and find the versions of binary node packages for this particular atom release. Put them into the corresponding ``_V`` variable, and you're done.

The main difficulty is bumping ``dev-utils/electron``, but, fortunately, atom doesn't bump its own dep too often (atom 1.14 uses electron-1.3, just like 1.13 and 1.12).

**Comment by elprans** [comment]
I actually stage these ebuilds in [my overlay](https://github.com/elprans/atom-overlay), I can add 1.14_beta there.

**Comment by nicolasbock** [comment]
@elprans I tried to build the package but it fails. I have added mored details in [bug #608478](https://bugs.gentoo.org/show_bug.cgi?id=608478).

**Comment by elprans** [comment]
@nicolasbock I added the x11-libs/libxkbfile dep.  Thanks for catching this.

**Comment by nicolasbock** [comment]
Do we need anything else to merge this?

**Comment by mpkh** [comment]
@elprans @nicolasbock merged, thank you

**Comment by nicolasbock** [comment]
@mpkh Thanks!

**Pull request closed without merging**
