### PR TITLE
app-admin/ulogd: enable out-of-source build, minor cleanups

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
^^ Unrelated dev-python/sqlalchemy-migrate problems.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint 

Yes no worries. The repo was broken well before you sent the PR.

**Comment by Coacher** [comment]
Rebased to avoid QA problems.

**Comment by monsieurp** [comment]
Spasiba!

**Pull request merged**
