### PR TITLE
Adopt www-client/seamonkey-bin, etc.

### PR DESCRIPTION
**Pull request by Elizafox**
Hello,

I am wishing to proxy-maintain www-client/seamonkey-bin. Accordingly, I have bumped it and removed an old version (to match www-client/seamonkey), and fixed a typo in the javascript file for system preferences.

### CODE REVIEW

**Comment by akhuettel** [comment]
@jdhore

**Comment by Elizafox** [comment]
I have spoken to jdhore elsewhere on IRC recently and he intends to go devaway. He has not been active since earlier in the year.

**Comment by jdhore** [comment]
Sounds good to me. Elizafox is correct, I would like to go devaway as I am moving across the country, however my Gentoo SSH keys are on a hard drive in a box in my storage unit currently so i'm not able to do it properly.

**Comment by Elizafox** [comment]
Since I've "messed up the history" with a merge commit I am going to close this and redo it at some other point when my patience with git is not exhausted.

**Comment by monsieurp** [comment]
A much easier way to work around the problem would be to:
$ git reset --hard dd80071
$ git push --force-with-lease origin master

**Comment by Elizafox** [comment]
See new PR at #478 which does not contain the offending commit and fixes metadata spacing to boot.

**Pull request closed without merging**
