### PR TITLE
net-analyzer/{gvm,openvas} stuff: drop old & remove last rited packages

### PR DESCRIPTION
**Pull request by hsntgm**
I tried to split PR's https://github.com/gentoo/gentoo/pull/14018 & https://github.com/gentoo/gentoo/pull/14016 
Unfortunately this is not possible in current package condition.

@juippis

These are the last parts of old openvas-stuff in the tree.
Removed last rited packages and dropped old ebuilds with all patches etc.
Now we will completely get rid off old openvas stuff.

For last rited & removed packages:

-------------------------------

Last rite mail:
https://archives.gentoo.org/gentoo-dev/message/4e5b9c1f8795c46149161bea25f85322

Package Mask Commit: --> 30 days have expired.
5ba7b3b

Removal Bug:
https://bugs.gentoo.org/692004

### CODE REVIEW

**Comment by hsntgm** [comment]
:)
```
#!/bin/bash
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2
#
# being a dev script

pr_status="$(wget https://github.com/gentoo/gentoo/pull/14044 -q -O - | grep -o "✅.*" | awk '{print $2}' | rev | cut -c5- | rev)"
current_experience="1.5"
expected_experience="1"
mentor_approval="approved"

if [[ "${mentor_approval}" == "approved" ]]; then
        if [[ "${pr_status}" == "good" ]]; then
                if (( $(echo "$current_experience > $expected_experience" |bc -l) )); then
                        echo "time to get dev quiz"
                        else
                            	echo "wait for next year"
                fi
                else
                    	echo "try again"
        fi
else
    	echo "go to bed"
fi
```

**Comment by juippis** [comment]
Also, 
```
net-analyzer/greenbone-security-assistant
  MissingUseDepDefault: version 8.0.1: DEPEND="net-libs/libmicrohttpd[messages]": USE flag 'messages' missing from packages: [ net-libs/libmicrohttpd-0.9.68, net-libs/libmicrohttpd-0.9.69 ]
  MissingUseDepDefault: version 8.0.1: RDEPEND="net-libs/libmicrohttpd[messages]": USE flag 'messages' missing from packages: [ net-libs/libmicrohttpd-0.9.68, net-libs/libmicrohttpd-0.9.69 ]
```

**Comment by hsntgm** [comment]
> Could you check if these have any meaning anymore?
> 
> ```
> base/package.use.stable.mask:net-analyzer/openvas-manager extras
> use.local.desc:net-analyzer/openvas-libraries:extras - Html docs support
> use.local.desc:net-analyzer/openvas-libraries:ldap - Enable support for ldap
> use.local.desc:net-analyzer/openvas-libraries:radius - Enable support for radius
> use.local.desc:net-analyzer/openvas-manager:extras - Html docs support
> use.local.desc:net-analyzer/openvas-scanner:cron - Install a cron job to update GVM's feed daily.
> use.local.desc:net-analyzer/openvas-scanner:extras - Html docs support
> ```
> 
> You could've left openvas in RDEPEND for a bit longer, but that is not an issue since whoever syncs next won't have those in portage anymore, and is easy to fix.

@juippis we don't need them. There was a bug on dev-perl/GD so it seems kent frederic added them for net-analyzer/openvas-manager. We last rited the package ant the renamed package gvmd not use dev-perl/GD. SO it is safe to drop it from package.use.stable.mask.

This is same for use.local.desc. I am not ware of that. Thank you.
PR is coming.

**Comment by hsntgm** [comment]
> Also,
> 
> ```
> net-analyzer/greenbone-security-assistant
>   MissingUseDepDefault: version 8.0.1: DEPEND="net-libs/libmicrohttpd[messages]": USE flag 'messages' missing from packages: [ net-libs/libmicrohttpd-0.9.68, net-libs/libmicrohttpd-0.9.69 ]
>   MissingUseDepDefault: version 8.0.1: RDEPEND="net-libs/libmicrohttpd[messages]": USE flag 'messages' missing from packages: [ net-libs/libmicrohttpd-0.9.68, net-libs/libmicrohttpd-0.9.69 ]
> ```

I just released that messages use flag dropped for latest ~ARCHED net-libs/libmicrohttpd versions. But stable one still have messages use flag.

So i will fix it.

**Pull request closed without merging**
