### PR TITLE
net-libs/xdp-tools: bump to 1.3.1 & add build fixes

### PR DESCRIPTION
**Pull request by hhoffstaette**
Closes: https://bugs.gentoo.org/889842

### CODE REVIEW

**Comment by hhoffstaette** [comment]
I just realized that I created an -r1 even though the existing ebuild could have been changed in-place (no keyword changes) since it doesn't even build. Let me know if I should remove the previous rev.

**Comment by hhoffstaette** [comment]
Btw I didn't do a bump since latest 1.3.1 (or even 1.3.0) don't even compile, so for now I decided to just fix 1.2.8.

**Comment by hhoffstaette** [comment]
Will rework this since we might be able to update to the latest upstream release after all.

**Comment by hhoffstaette** [comment]
This PR now does a simple update to the latest upstream release with two contributed fixes to make it actually build.

**Comment by thesamesam** [comment]
Thanks Holger!

**Comment by thesamesam** [comment]
https://bugs.gentoo.org/899684 is a good reminder of why it's better to cleanup in a separate commit :wink:

**Pull request closed without merging**
