### PR TITLE
net-misc/ubridge: Version bump to 0.9.16

### PR DESCRIPTION
**Pull request by linxon**
Package-Manager: Portage-2.3.62, Repoman-2.3.11
Signed-off-by: Yury Martynov email@linxon.ru

### CODE REVIEW

**Comment by garrymar** [comment]
I would like to add a comment to add some clarity. Currently, there is a bug (https://github.com/GNS3/ubridge/issues/60 ) reported by @linxon at upstream ubridge project. The problem prevents us to use system's provided iniparser. As a workaround author suggested using the library supplied by ubridge.

If it is fine to supply the version 0.9.15 with embedded iniparser then I am in favour of the PR (or I can create a separate PR myself if required).

Thanks.

**Comment by linxon** [comment]
@garrymar https://github.com/GNS3/ubridge/issues/60 has been [resolved](https://github.com/GNS3/ubridge/pull/61) in **0.9.16**

the latest version requires `>=dev-libs/iniparser-4.1:4` and I had to apply a [patch](https://github.com/gentoo/gentoo/blob/795981bbd5aba4508ddbc1638fb2d9dfcb3642ac/net-misc/ubridge/files/ubridge-0.9.16_add_slotted_iniparser-4.1%2B_support.patch) because `iniparser-4.1.ebuild` uses slots and it changes a library name while installing:
https://github.com/gentoo/gentoo/blob/9efd1b77286fba5e3f9abbb60f2f2775edbcb37c/dev-libs/iniparser/iniparser-4.1.ebuild#L58

**Comment by garrymar** [comment]
@linxon, yes I've been following the development of ubridge and prepared almost the same ebuild with a patch an hour ago, but you were the first to prepare the pull request. :) Thank you.

**Comment by mgorny** [comment]
@linxon, we can't merge this without your signoff.

**Pull request closed without merging**
