### PR TITLE
gnome-extra/gnome-weather: Version bump to 45_alpha

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
````diff
-# Tests have a lot of issues, starting with reliance on a system installation,
-# accessing the network and other intermittent failures with network-sandbox disabled
-# https://gitlab.gnome.org/GNOME/gnome-weather/issues/67 (and rest not filed)
-# test dep: $(python_gen_any_dep 'dev-util/dogtail[${PYTHON_USEDEP}]')
-# With 3.34, this is now behind a dogtail option we can pass (and have data validation)
-
````

This comment still seems relevant. Why remove it?

**Comment by flint2** [comment]
> ```diff
> https://gitlab.gnome.org/GNOME/gnome-weather/issues/67
> ```

I cannot reproduce the issues:

---------------------------------------------------------------------------------------------

1/2 Validate desktop file        OK              0.00s
2/2 validate-appdata             OK              0.01s

Ok:                 2   
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45_alpha-build/meson-logs/testlog.txt
>>> Completed testing gnome-extra/gnome-weather-45_alpha
 # equery l gnome-weather                                              @gnome-weather
!!! No installed packages matching 'gnome-weather'
 * Searching for gnome-weather ...

**Comment by mattst88** [comment]
That's because `dogtail` is explicitly disabled, right?

Apply this

```diff
diff --git a/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild b/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
index 38143d799022..efff46ee667e 100644
--- a/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
+++ b/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
@@ -3,7 +3,7 @@
 
 EAPI=8
 
-inherit gnome.org gnome2-utils meson xdg
+inherit gnome.org gnome2-utils meson virtualx xdg
 
 DESCRIPTION="A weather application for GNOME"
 HOMEPAGE="https://wiki.gnome.org/Design/Apps/Weather"
@@ -33,7 +33,11 @@ BDEPEND="
 "
 
 src_configure() {
-       meson_src_configure -Dprofile=default -Ddogtail=false
+       meson_src_configure -Dprofile=default -Ddogtail=true
+}
+
+src_test() {
+       virtx meson_src_test
 }
 
 pkg_postinst() {
```

and you'll see the failure.

**Comment by flint2** [comment]
> That's because `dogtail` is explicitly disabled, right?
> 
> Apply this
> 
> ```diff
> diff --git a/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild b/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
> index 38143d799022..efff46ee667e 100644
> --- a/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
> +++ b/gnome-extra/gnome-weather/gnome-weather-45_alpha.ebuild
> @@ -3,7 +3,7 @@
>  
>  EAPI=8
>  
> -inherit gnome.org gnome2-utils meson xdg
> +inherit gnome.org gnome2-utils meson virtualx xdg
>  
>  DESCRIPTION="A weather application for GNOME"
>  HOMEPAGE="https://wiki.gnome.org/Design/Apps/Weather"
> @@ -33,7 +33,11 @@ BDEPEND="
>  "
>  
>  src_configure() {
> -       meson_src_configure -Dprofile=default -Ddogtail=false
> +       meson_src_configure -Dprofile=default -Ddogtail=true
> +}
> +
> +src_test() {
> +       virtx meson_src_test
>  }
>  
>  pkg_postinst() {
> ```
> 
> and you'll see the failure.

Now I can reproduce it:

----------------------------------------------------------------------------------
```
>>> Test phase: gnome-extra/gnome-weather-45_alpha
 * Starting Xvfb ...
 * Xvfb started on DISPLAY=:2
meson test --print-errorlogs -C /var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45_alpha-build --num-processes 12
ninja: no work to do.
ninja: Entering directory `/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45_alpha-build'
ninja: no work to do.
1/3 Validate desktop file        OK              0.01s
2/3 validate-appdata             OK              0.02s
3/3 world_view                   FAIL           14.44s   exit status 1
>>> MALLOC_PERTURB_=193 /usr/bin/python3 tests/world_view.py
 ✀  
stdout:
Creating logfile at /tmp/dogtail-portage/logs/world_view_20230712-192631_debug ...
Warning: AT-SPI's desktop is visible but it has no children. Are you running any AT-SPI-aware applications?
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 3)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 4)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 5)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 6)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 7)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 8)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 9)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 10)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 11)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 12)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 13)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 14)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 15)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 16)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 17)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 18)
searching for descendent of [application | org.gnome.Weather]: child with name="Places" (attempt 19)
Traceback (most recent call last):
  File "/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45.alpha/tests/world_view.py", line 26, in <module>
    places_button = app.child('Places')
                    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dogtail/tree.py", line 1008, in child
    return self.findChild(predicate.GenericPredicate(name=name, roleName=roleName, description=description,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dogtail/tree.py", line 939, in findChild
    raise SearchError(describeSearch(self, pred, recursive, debugName))
dogtail.tree.SearchError: descendent of [application | org.gnome.Weather]: child with name="Places"

stderr:

(world_view.py:58): dconf-WARNING **: 19:26:31.268: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user: Permission denied



Summary of Failures:

3/3 world_view            FAIL           14.44s   exit status 1

Ok:                 2   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45_alpha-build/meson-logs/testlog.txt
 * ERROR: gnome-extra/gnome-weather-45_alpha::gentoo failed (test phase):
 *   tests failed
 * 
 * Call stack:
 *               ebuild.sh, line  136:  Called src_test
 *             environment, line 2489:  Called virtx 'meson_src_test'
 *             environment, line 3278:  Called nonfatal 'meson_src_test'
 *   isolated-functions.sh, line  100:  Called meson_src_test
 *             environment, line 1908:  Called die
 * The specific snippet of code:
 *       "$@" || die "tests failed"
 * 
 * If you need support, post the output of `emerge --info '=gnome-extra/gnome-weather-45_alpha::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=gnome-extra/gnome-weather-45_alpha::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45.alpha'
 * S: '/var/tmp/portage/gnome-extra/gnome-weather-45_alpha/work/gnome-weather-45.alpha'
```
----------------------------

Should we leave dogtail=true  ?

**Comment by mattst88** [comment]
No :)

The point was, you shouldn't remove the comment about why we have dogtail disabled.

You said you didn't think it was relevant because you couldn't reproduce the issue.

I showed you how to reproduce the issue... so the comment should remain and we should leave dogtail disabled.

**Pull request closed without merging**
