### PR TITLE
games-emulation/ppsspp: bug fix #572606

### PR DESCRIPTION
**Pull request by RobinDX**
Fix https://bugs.gentoo.org/show_bug.cgi?id=572606

### CODE REVIEW

**Comment by RobinDX** [comment]
@monsieurp
What happened to QA ?

**Comment by monsieurp** [comment]
@RobinDX: I told you a zillion times that you **only** need to push your changes to the branch you've created when sending the PR for the bot to pick them up and run the QA tests again; in this case: `RobinDX:psp`. There's no need to create a PR every time you want the QA tests to run

**Comment by monsieurp** [comment]
Since this fix modifies the install path of the ppsspp binary, we have to create a new revision. Please, undo your changes in both ebuilds and create two new revisions, namely ppsspp-1.1.0-r1.ebuild and ppsspp-1.1.1-r1.ebuild with your fix in it. Cheers.

**Comment by monsieurp** [comment]
and DO NOT close this PR and send a new one! :angry:

**Comment by RobinDX** [comment]
@monsieurp 
Jobs done

**Comment by mgorny** [comment]
@RobinDX, please rebase your commits against fresh repository. This pull request is based on pre-GLEP67 ::gentoo repository which triggers so many QA issues that the script fails with lack of resources to process them all. Otherwise, it would throw around 18k errors here ;-P.

**Comment by RobinDX** [comment]
@mgorny
So what should I do ？

**Comment by RobinDX** [comment]
I think I have do something wrong with git rebase.

**Pull request closed without merging**
