### PR TITLE
sys-block/btrace: update

### PR DESCRIPTION
**Pull request by rindeal**
@robbat2 

Also this package could be renamed to `blktrace` to be on a par with the rest of the world.

### CODE REVIEW

**Comment by rindeal** [comment]
And package moves has to be announced prior to the change or can I include it in this PR?

**Comment by robbat2** [comment]
The move doesn't need to be announced, but I would like it in a separate commit than the update.

commit 1: update to EAPI=6, keywords
commit 2: just the move (no other changes in the package):
```
git mv sys-block/{btrace,blktrace} && \ 
echo sys-block/{btrace,blktrace} >> profiles/updates/2Q-2016 && \
git commit sys-block/{btrace,blktrace}  profiles/updates/2Q-2016
```

**Comment by rindeal** [comment]
ok, done

**Comment by monsieurp** [comment]
Hi. What's blocking this PR from being merged? @robbat2 are you still interested in it? If not, should we close it? Thanks.

**Pull request merged**
