### PR TITLE
app-backup/zbackup: new ebuild

### PR DESCRIPTION
**Pull request by SpiderX**
zbackup is a globally-deduplicating backup tool, based on the ideas found in rsync.
Feed a large .tar into it, and it will store duplicate regions of it only once,
then compress and optionally encrypt the result. Feed another .tar file,
and it will also re-use any data found in any previous backups.
This way only new changes are stored, and as long as the files are not very different,
the amount of storage required is very low. Any of the backup files stored previously
can be read back in full at any time.

Base for ebuild from https://github.com/SpiderX/portage-overlay/tree/master/app-backup/zbackup

Gentoo-Bug: https://bugs.gentoo.org/576796

Package-Manager: portage-2.3.3

### CODE REVIEW

**Comment by SpiderX** [comment]
A tartool utility is out of main build process, so a workaround was introduced to build it.

**Comment by SpiderX** [comment]
Added a libressl support. Tested.

**Comment by gbraekmans** [comment]
Nice to see this, is it possible to build zbackup without tartool?

**Comment by SpiderX** [comment]
Sure. It is possible. But I like to have a tartool in portage too.
Anyway, I have created a small patch to include a build of tartool utility into the main build process.
Also, I've made it optional via appropriated USE flag.

**Comment by SpiderX** [comment]
I would like that this package appears in portage. What do I need to do to make this happen?

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/31c4885...29f1455. Thanks!

**Pull request closed without merging**
