### PR TITLE
dev-python/pywlroots: add patch to solve sandbox violations for qtile

### PR DESCRIPTION
**Pull request by mrtnvgr**
Closes: https://bugs.gentoo.org/905743

### CODE REVIEW

**Comment by thesamesam** [comment]
I think we need to do a bit more wrt fixing the automagic xwayland dep on top (see my comment on the bug).

**Comment by thesamesam** [comment]
ping

**Comment by mrtnvgr** [comment]
@thesamesam
Sorry for the delay. Can this be solved by adding `xwayland` as a `pywlroots` dependency _(only if X is installed)_?

**Comment by thesamesam** [comment]
We can't do ebuild dependencies based on whether something is installed. We either need to unconditionally depend on xwayland or we need to add a USE flag that patches/seds/toggles the logic in qtile/pywlroots.

**Comment by mrtnvgr** [comment]
> We can't do ebuild dependencies based on whether something is installed. 

I phrased it wrong, I meant that we can use X use flag.


```
RDEPEND = "
    X? ( x11-base/xwayland )
"
```

**Comment by thesamesam** [comment]
We _can_ do that but only if USE="X" actually controls something.

Otherwise, if USE=-X and xwayland is installed, we get misbehaviour.

**Pull request closed without merging**
