### PR TITLE
www-servers/tomcat: SRC_URI

### PR DESCRIPTION
**Pull request by vaukai**
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by Flowdalic** [comment]
I'd expect this to require a revision bump. Is there a reason it does not ?

**Comment by vaukai** [comment]
> I'd expect this to require a revision bump. Is there a reason it does not ?

`revbump` for what reason? There is no change in `package.env`

**Comment by Flowdalic** [comment]
> `revbump` for what reason? 

I have no clue how tomcat distributes it source, but I assumed that, since we change SRC_URI, we are building some, maybe slightly, different source. So the typical rule that, if the installed image changes, then a revision bump is required, would apply.

> There is no change in `package.env`

But maybe there is a change in the .jar?

But again, I have no clue about tomcat source distribution, and the significance of tomcat-9 vs tomcat-10 in this particular context.

**Comment by Flowdalic** [comment]
I just realized that the Manifest hash stays the same, and checked that it matches https://dlcdn.apache.org/tomcat/tomcat-10/v10.0.20/src/apache-tomcat-10.0.20-src.tar.gz. Thanks!

**Pull request closed without merging**
