### PR TITLE
dev-java/ant-eclipse-ecj: Drop unneeded slots 4.10 and 4.13 | dev-java/eclipse-ecj: Drop unneeded slots 4.10 and 4.13

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
i think we should first check whether the depending apps can be updated to the newer versions of ecj.

**Comment by vaukai** [comment]
> i think we should first check whether the depending apps can be updated to the newer versions of ecj.

According to my analysis there was nothing dependent on those 2 slots.  Did I miss something?

**Comment by fordfrog** [comment]
no, i just meant we would still keep that old 4.5 and remove newer versions though it might be that the apps depending on 4.5 might be updated to use newer ecj instead.

**Comment by vaukai** [comment]
> no, i just meant we would still keep that old 4.5 and remove newer versions though it might be that the apps depending on 4.5 might be updated to use newer ecj instead.

Got it.  But as long things work I see no reason to touch them.  So we better leave it as is atm and try upgrading once reverse deps have issues.  Closing this PR

**Pull request closed without merging**
