### PR TITLE
gui-apps/wf-recorder: new package

### PR DESCRIPTION
**Pull request by heroin-moose**
Closes: https://bugs.gentoo.org/717976
Signed-off-by: Olaf Torvaldsson <consus@ftml.net>

### CODE REVIEW

**Comment by heroin-moose** [comment]
I'm sure about OpenCL though, how it should be treated in Gentoo.

**Comment by vitaly-zdanevich** [comment]
Pulseaudio only, no Alsa?

**Comment by heroin-moose** [comment]
Yep, hard dependency right now. I can try with apulse if anyone is interested in pure ALSA.

**Comment by vitaly-zdanevich** [comment]
> Yep, hard dependency right now. I can try with apulse if anyone is interested in pure ALSA.

I am interested.

**Comment by heroin-moose** [comment]
> I am interested.
Okay then, I'll git apulse a shot.

**Comment by heroin-moose** [comment]
It seems to me that there is no way to emulate `pa_simple_read` via apulse (this function is a placeholder with `return -1`). So unless someone writes a patch we're stuck with PA only.

**Comment by vitaly-zdanevich** [comment]
Ok, anyway thank you.

Just now I recognized the missed case: recording without audio, and for deaf people. Do you think it is possible to build and use this software without pulseaudio at all?

**Comment by heroin-moose** [comment]
@vitaly-zdanevich, no, not right now, it's hard dependency. There is a pending patch, so maybe some next release.

**Pull request closed without merging**
