### PR TITLE
media-gfx/freecad: add 0.20.2

### PR DESCRIPTION
**Pull request by waebbl**
- cleanup some depstrings (med, vtk, boost)
- not yet ready for py311 (SEGV when running test suite)
- backport changes from live ebuild to prepare for Qt6 (headless -> gui USE flag)

Closes: https://bugs.gentoo.org/887589
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by waebbl** [comment]
For the missing Python 3.11 compatibility, see https://forum.freecadweb.org/viewtopic.php?f=10&t=74026&sid=7314bd04c28eae442f442293f9755bb3#p649103 and the discussion in this thread.
The 0.20 FreeCAD series officially only supports OpenCASCADE 7.6 series. While the live ebuild already has support for 7.7, not all of the patches were cherry-picked for the 0.20.2 release, so I decided to stick with 7.6 for now, see https://bugs.gentoo.org/883073#c7

**Review by juippis — COMMENTED** [review]
Meh, can't test this due to https://bugs.gentoo.org/890293 :(

**Review by juippis — APPROVED** [review]
```
FAILED: src/Tools/plugins/widget/FreeCAD_widgets_autogen/timestamp src/Tools/plugins/widget/FreeCAD_widgets_autogen/mocs_compilation.cpp /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/timestamp /var/tmp/portage/ media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/mocs_compilation.cpp
cd /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget && /usr/bin/cmake -E cmake_autogen /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/CMakeFiles/FreeCAD_widgets_autogen.dir/AutogenInfo.json   RelWithDebInfo && /usr/bin/cmake -E touch /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/timestamp && /usr/bin/cmake -E cmake_transform_depfile Ninja gccdepfile /var/tmp/portage/media-gfx/freecad-0.20.2/work/    FreeCAD-0.20.2 /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2/src/Tools/plugins/widget /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget /var/tmp/portage/  media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/deps /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/CMakeFiles/d/10d55a4b4db33bba7b909a67ef876d51b8dd68131a399d1d11ec77a26c8e3a4d.d
 
AutoMoc subprocess error
------------------------
The moc process failed to compile
  "SRC:/src/Tools/plugins/widget/plugin.h"
into
  "SRC:_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/EWIEGA46WW/moc_plugin.cpp"
 
Command
-------
/usr/lib64/qt5/bin/moc -DFreeCAD_widgets_EXPORTS -DHAVE_CONFIG_H -D_OCC64 -I/var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build -I/var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src -I/var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2/src -I/usr/include/qt5 -I/usr/include/qt5/QtCore -I/usr/lib64/qt5/mkspecs/linux-g++ -I/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12 -I/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/x86_64-pc-linux-gnu -I/usr/lib/gcc/x86_64-pc-linux-gnu/12/include/g++-v12/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/12/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/12/include-fixed -I/usr/include --include /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/moc_predefs.h --output-dep-file -o /var/tmp/     portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2_build/src/Tools/plugins/widget/FreeCAD_widgets_autogen/EWIEGA46WW/moc_plugin.cpp /var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2/src/Tools/plugins/widget/plugin.h
 
Output
------
/var/tmp/portage/media-gfx/freecad-0.20.2/work/FreeCAD-0.20.2/src/Tools/plugins/widget/plugin.h:32: Error: Undefined interface
 
```
 * USE:        abi_x86_64 amd64 designer elibc_glibc fem idf image kernel_linux path python_single_target_python3_10 robot show techdraw userland_GNU

**Comment by waebbl** [comment]
Did it finish the build even with this error?

**Comment by juippis** [comment]
Nope, but that happened 1/7 times so I deemed it ... something you should work on later :P 

I don't want to recompile all the deps "from empty" again like I did to get the pyside2 binpkg built.

**Comment by waebbl** [comment]
Ok, thanks for the info. Never saw the designer plugin failing in such a way. I suppose it'll be due to the specific USE flag settings. I'm investigating this.

**Pull request closed without merging**
