### PR TITLE
libmygpo-qt: version bump; fix testing; add qt5 support + fix recent clementine deps

### PR DESCRIPTION
**Pull request by Fat-Zer**
@gentoo/proxy-maint
@diogocp

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by Polynomial-C** [comment]
Can you please bump all affected libmygpo-qt ebuilds to EAPI-6?

**Comment by a17r** [comment]
Looks good, quite similar to how I attempted libmygpo-qt[qt5] but then abandoned (hope clementine-qt5 works better in the meantime).

Why bother with the 'regular' 1.0.9 bump? Just make 1.0.9 what -r1 is already. ;)

**Comment by Fat-Zer** [comment]
Sorry, I haven't replied for a while...

>Why bother with the 'regular' 1.0.9 bump? Just make 1.0.9 what -r1 is already. ;)

Well, initially I was going to do just a version bump, but 3 days later decided to resolve the bug as well in the same PR. But you are right. better to do it the same time.

>Can you please bump all affected libmygpo-qt ebuilds to EAPI-6?

Removed the non EAPI-6 version 1.0.9 as described above.

Also squashed and reordered some commits.

**Comment by diogocp** [comment]
@Fat-Zer wouldn't it be better to open another PR just for the Clementine changes? They are much easier to review and I get the feeling that they would have already been merged months ago.

**Comment by Fat-Zer** [comment]
@diogocp, no sense: the Clementine changes are just update deps associated with this version bump and qt4/5 support (there is also a relatively small fix for libechonest dep, which doesn't really deserves a separate PR).

**Pull request closed without merging**
