### PR TITLE
net-news/liferea: unstable version bump, remove old

### PR DESCRIPTION
**Pull request by nE0sIghT**
New RC [released](https://github.com/lwindolf/liferea/releases/tag/v1.12-rc2).

Also 
 * fixed homepage URL
 * added check for elibtoolize call in gnome2_src_prepare
 * and removed outdated einfo entry.

### CODE REVIEW

**Comment by nE0sIghT** [comment]
I see that gentoo-repo-qa-bot do not knows my Github's nickname.
Is there any way to teach him?

**Comment by wraeth** [comment]
This looks good to me and I will push it shortly.

As for having the QA bot mention you by GitHub name, I'm not sure - @mgorny would likely be able to answer that.

Thanks!

**Comment by mgorny** [comment]
@nE0sIghT, you need to ping me when you change e-mail. For performance reasons, the spam collector only looks for user's email once -- i.e. you were still tied to gmail.

**Comment by nE0sIghT** [comment]
@mgorny 
I have 3 emails attached to my github account.
gnome.org email is set to public (it shown in my profile).

**Pull request closed without merging**
