### PR TITLE
dev-games/ogre: Bump to 1.12.4 and add dev releases (#699770)

### PR DESCRIPTION
**Pull request by Yamakuzure**
#### Changes
* Bump stable release to 1.12.4
* Project moved to github
* In this release we have to also fetch the current release of imlib, as the tree has it as a submodule which is not included in the ogre release zip.
* Further I have put myself into metadata.xml, as I am proxy-maintaining ogre.
* Bump 2.1 development ebuild to 2.1_pre20191212 ; Also moved to github.
* Old ebuilds and patches removed.

However, the 1.9.0 ebuild has to stay, as it has reverse dependencies. This ebuild has been updated to the new EAPI=7 rules.

#### About the development ebuild:
* Still much of the old plugins aren't ported, yet.
* The 1.x series are CPU powered, the 2.x series are GPU powered
* As the API evolves, developers might wish to use these version to fully support the future API. (I do, however)

Package-Manager: Portage-2.3.84, Repoman-2.3.20
Bug: https://bugs.gentoo.org/699770
Closes: https://bugs.gentoo.org/699770
Signed-off-by: Sven Eden <sven.eden@gmx.de>

### CODE REVIEW

**Comment by Yamakuzure** [comment]
About the patches for 1.12.3:
The "double-precision" patches are simply backported from master, so we do not have to wait for the 1.12.4 release.

About the [NOMERGE] hold:
I am unhappy with fetching with git. I am currently testing a change to fetch the release files and than using a custom src_unpack() function.
This way both releases can be mirrored, and I also find the constant git fetch highly irritating.

**Comment by Yamakuzure** [comment]
> ## Pull request CI report
> _Report generated at_: 2019-11-18 08:21 UTC
> _Newest commit scanned_: [d1b2e8c](https://github.com/gentoo/gentoo/commit/d1b2e8c6cbe0e2dfbd7c270210f3aa94a1c160e7)
> _Status_:  **broken**

Oh damn!

I'd really appreciate if `repoman full` could catch this!

**Comment by Yamakuzure** [comment]
> > ## Pull request CI report
> > _Report generated at_: 2019-11-18 08:21 UTC
> > _Newest commit scanned_: [d1b2e8c](https://github.com/gentoo/gentoo/commit/d1b2e8c6cbe0e2dfbd7c270210f3aa94a1c160e7)
> > _Status_:  **broken**
> 
> Oh damn!
> 
> I'd really appreciate if `repoman full` could catch this!

I just realized that it is not possible to determine what I mean with "this".

The QA check complained, that although there were tarballs available, I chose to download zip files. Well, those zips would have been significantly smaller.
But the real problem the QA check detected, was, that I also forgto to add app-arch/unzip to the dependencies.

The latter is what `repoman` really should be able to detect.

**Comment by Yamakuzure** [comment]
@chewi @SoapGentoo @steils @vapier 
Sorry for pinging you all, but I am a bit lost, here. No need to feel pressed, though, I just have no clue whom to ping, and therefore simply copied from the project page.

As mentioned in https://bugs.gentoo.org/633138 I am taking a bit care of dev-games/ogre. Unfortunately the bug for this PR did not get any attention or feedback. Although I added myself to metadat.xml, the bot didn't add the "self-maintained" tag.
I guess my refusal to erase the games team is the reason. But I don't want to take over, just to help a bit.

However, I am pinging because dev-games/ogre has reverse dependencies which I'd like to investigate. Some packages still depend on the ancient and long deprecated 1.9.0 series.

But before I can open bugs an/or PRs for these packages, this one here has to be either rejected or merged. At least I'd like to have some feedback. In the long run, I hope we can get rid of ogre-1.9.0 entirely.

Thanks in advance!

**Comment by chewi** [comment]
I'll take most of the blame. I deal with most of the games stuff at the moment but it's really hard to keep up. I know this has been in the queue longer than some other things but it's a lot easier to knock off small changes and simple bumps than meatier requests like this one. Your long history of contributions isn't lost on me so I'll keep trying to get to this.

**Comment by Yamakuzure** [comment]
No pressure, I just was lost at deciding whom to ping. :wink:

**Comment by Yamakuzure** [comment]
@chewi I just noted that opencv-4.1.2-r1 no longer builds when OGRE is presetn, as 'ovis' uses features introduced in ogre-1.12.x

After I installed ogre-1.12.3, opencv-4.1.2-r1 merged fine.

However, I have no idea what gentoo-ci wants from me. The page linked does not show any errors with this PR. What am I missing?

**Comment by Yamakuzure** [comment]
@chewi : Seems like the CI failing had nothing to do with my patches. :man_shrugging:

**Comment by chewi** [comment]
Don't worry about CI, if I think you've broken something, I'll say so.

I was actually looking to merge this today but I now see that 1.12.4 came out this week, making those big patches unnecessary. I could make the adjustments but I'd feel more comfortable if you did it. I'll then try to get it merged in short order. I feel more comfortable doing so now I realise that all the versions concerned are masked anyway. If you want to test some revdeps so that we can get them unmasked then please do although the dev releases should probably stay masked for now.

**Comment by Yamakuzure** [comment]
@chewi Happy new year!

Family matters kept me busy, but I'll update to the latest version this weekend.

Once we get this merged I can eventually go and propose fixes for the packages that are currently in an odd state regarding Ogre. (Like OpenCV)

**Comment by Yamakuzure** [comment]
@chewi : Done and tested. I had some trouble because of old cache entries in '~/.cache/Ogre Sample Browser', so I have also added a pkg_postinst message about that folder.

**Comment by chewi** [comment]
1.12.4 fails to build for me because it cannot find pugixml.hpp. This is a missing dependency. If you don't already have it installed then it's possible that it downloaded it during the build. To prevent that, turn on `FEATURES="network-sandbox"`.

I was going to address some more things myself but since we're going round again...

* `cmake-utils.eclass` is now deprecated in favour of `cmake.eclass`. That just happened, sorry!
* `EGIT_CLONE_TYPE` is a user setting that's not meant for ebuilds.
* It would also be nice if you could shorten your patches so they just remove lines instead of commenting them out. Any additional comments can go at the top of the patch, where they will be ignored when applying.

**Comment by chewi** [comment]
2.1_pre20191212 builds and installs fine but 2.2_pre20191118 fails in a bizarre way.

```
>>> Compiling source in /var/tmp/portage/dev-games/ogre-2.2_pre20191118/work/ogre-2.2_pre20191118 ...
>>> Working in BUILD_DIR: "/var/tmp/portage/dev-games/ogre-2.2_pre20191118/work/ogre-2.2_pre20191118_build"
ninja -v -j12 -l0
ninja: error: '/home/matias/Projects/vulkan/1.1.121.1/x86_64/lib/libglslang.a', needed by 'lib/RenderSystem_Vulkan.so.2.2.1', missing and no known rule to make it
```

Note that my name is not _matias_! Apart from the silly path, if libglslang really is needed then dev-util/glslang is probably a missing dependency?

**Comment by Yamakuzure** [comment]
Thanks for the feedback, it is always good when another pair of eyes dare a look. ;-)

I'll tackle the new issues in the next few days.

**Comment by Yamakuzure** [comment]
@chewi : Alright, this _should_ be it.

- pugixml.hpp : Belongs to dev-libs/pugixml, which is now an RDEPEND. (ogre-1.12.4 only)
- cmake.eclass: All cmake-utils renamed to cmake, also in 1.9.0-r1. Here no revision bump, a rebuild would help nobody, right?
- EGIT_CLONE_TYPE: removed
- Patches: All patches shortened where possible
- /home/matias : That's the author and maintainer of the vulkan part. I didn't know he'd put in so many hardcoded local paths! I thought about patching this, but it will be better to step back from 2.2-vulkan until they sorted their stuff out.

Anything I missed?

**Comment by chewi** [comment]
I had to fix up the 1.9.0 ebuild a fair bit. Please test your changes in future. `cmake_use` isn't a thing, `CMAKE_BUILD_DIR` has been renamed, and `eutils` is no longer necessary. I've also added `BDEPEND` across all the ebuilds as needed for EAPI 7.

This is a lot of disruption for the 1.9.0 stable ebuild so I've put the changes in a revbump.

Thanks for making this happen. I'd never have found the time otherwise.

**Comment by Yamakuzure** [comment]
@chewi Thanks alot!

And sorry for the extra work, I really haven't paid enough attention to the 1.9.0 ebuild. To be honest, I'll research now whether and how we can get rid of it. :wink:

**Pull request closed without merging**
