### PR TITLE
gui-libs/wlroots: make revdeps rebuild on slot change

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <floss@aisha.cc>

### CODE REVIEW

**Comment by JonasToth** [comment]
LGTM

**Review by juippis — APPROVED** [review]
Need to revbump these ebuilds, gonna do it.

**Comment by ionenwks** [comment]
> Need to revbump these ebuilds, gonna do it.

There's also https://github.com/gentoo/gentoo/pull/21506 that's more important, I was going to do both at same time.

**Comment by juippis** [comment]
@ionenwks ah, sorry, missed it.

**Pull request closed without merging**
