### PR TITLE
dev-util/visualvm: slotmove 7 -> 0

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by fordfrog** [comment]
`owasp-java-encoder` fails some tests for me:
```
Time: 55,76
There were 3 failures:
1) Encode.forJavaScript(org.owasp.encoder.BenchmarkTest$1$3)
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:200)
	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)
2) Encode.forCssString(org.owasp.encoder.BenchmarkTest$1$3)
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:200)
	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)
3) Encode.forJava(org.owasp.encoder.BenchmarkTest$1$3)
junit.framework.AssertionFailedError
	at junit.framework.Assert.fail(Assert.java:55)
	at junit.framework.Assert.assertTrue(Assert.java:22)
	at junit.framework.Assert.assertTrue(Assert.java:31)
	at junit.framework.TestCase.assertTrue(TestCase.java:200)
	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)

FAILURES!!!
Tests run: 960,  Failures: 3
```

**Comment by vaukai** [comment]
> `owasp-java-encoder` fails some tests for me (openjdk-21):
> 
> ```
> Baseline is 125,018618 ns/op
> .Benchmarked Encode.forXml: 249,948090 ns/op (+99,93% on baseline)
> .Benchmarked Encode.forJavaScript: 442,382250 ns/op (+253,85% on baseline)
> E.Benchmarked Encode.forCssString: 446,929231 ns/op (+257,49% on baseline)
> E.Benchmarked Encode.forCDATA: 67,124081 ns/op (-46,31% on baseline)
> .Benchmarked Encode.forJava: 409,038065 ns/op (+227,18% on baseline)
> E.Benchmarked Encode.forXmlComment: 49,786235 ns/op (-60,18% on baseline)
> 
> Time: 55,76
> There were 3 failures:
> 1) Encode.forJavaScript(org.owasp.encoder.BenchmarkTest$1$3)
> junit.framework.AssertionFailedError
> 	at junit.framework.Assert.fail(Assert.java:55)
> 	at junit.framework.Assert.assertTrue(Assert.java:22)
> 	at junit.framework.Assert.assertTrue(Assert.java:31)
> 	at junit.framework.TestCase.assertTrue(TestCase.java:200)
> 	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)
> 2) Encode.forCssString(org.owasp.encoder.BenchmarkTest$1$3)
> junit.framework.AssertionFailedError
> 	at junit.framework.Assert.fail(Assert.java:55)
> 	at junit.framework.Assert.assertTrue(Assert.java:22)
> 	at junit.framework.Assert.assertTrue(Assert.java:31)
> 	at junit.framework.TestCase.assertTrue(TestCase.java:200)
> 	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)
> 3) Encode.forJava(org.owasp.encoder.BenchmarkTest$1$3)
> junit.framework.AssertionFailedError
> 	at junit.framework.Assert.fail(Assert.java:55)
> 	at junit.framework.Assert.assertTrue(Assert.java:22)
> 	at junit.framework.Assert.assertTrue(Assert.java:31)
> 	at junit.framework.TestCase.assertTrue(TestCase.java:200)
> 	at org.owasp.encoder.BenchmarkTest$1$3.runTest(BenchmarkTest.java:115)
> 
> FAILURES!!!
> Tests run: 960,  Failures: 3
> ```

is this due to some locale to be set? here, all tests pass even with openjdk-bin:24

**Comment by fordfrog** [comment]
my suspition is that the benchmark values are rather out of the expected values. but i didn't check the code. i guess checking the code would reveal more.

**Comment by vaukai** [comment]
> my suspition is that the benchmark values are rather out of the expected values. but i didn't check the code. i guess checking the code would reveal more.

just found, we already have this patch:
```
owasp-java-encoder-1.2.3-BenchmarkTest.patch
```
could try to enhance that patch for `1.3.0`, wdyt?

**Comment by fordfrog** [comment]
just looking at the [code](https://github.com/OWASP/owasp-java-encoder/blob/v1.3.0/core/src/test/java/org/owasp/encoder/BenchmarkTest.java#L115). i found this test kinda unpredictable as it expects that it cannot surpass a predefined value, which in my case obviously doesn't work. i wouldn't even mind if we'd disable this test suite completely because of the unpredictable results.

**Comment by vaukai** [comment]
> this test kinda unpredictable as it expects that it cannot surpass a predefined value, which in my case obviously doesn't work.

removed the test and added a comment. pls adjust with your own words if needed.

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
`owasp-java-encoder` merged. i made the description more specific in 73efed650da577848f5a9b33ff9703148986725a

**Comment by vaukai** [comment]
> `owasp-java-encoder` merged. i made the description more specific in [73efed6](https://github.com/gentoo/gentoo/commit/73efed650da577848f5a9b33ff9703148986725a)

should i rebase?

**Comment by fordfrog** [comment]
> should i rebase?

yes. we can do the slot move only after the new version is stabilized and the old one is removed. i guess we can speed up the stabilization a bit, like starting it in a few days or so.

**Comment by vaukai** [comment]
> > should i rebase?
> 
> yes. we can do the slot move only after the new version is stabilized and the old one is removed. i guess we can speed up the stabilization a bit, like starting it in a few days or so.

rebase done. do you have an idea how to handle https://bugs.gentoo.org/937128?

**Comment by fordfrog** [comment]
> rebase done. do you have an idea how to handle https://bugs.gentoo.org/937128?

i added comment to the bug

**Comment by vaukai** [comment]
> > should i rebase?
> 
> yes. we can do the slot move only after the new version is stabilized and the old one is removed. i guess we can speed up the stabilization a bit, like starting it in a few days or so.

slotmoves on java packages, [this one](https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-java/guava?id=db6f1ad5edce356930cecb857d94a4fd58c7e9ee) was done even without touching reverse dependencies. we might add [dev-java/asm-9.7](https://github.com/gentoo/gentoo/pull/33579/commits) with `SLOT=0`?

**Comment by vaukai** [comment]
@fordfrog stabilization is done and one commit added for removing 2.1.8

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
i still get the file collisions error.  it might probably be better to do the slotmove approach in this case, maybe even with keeping the revbump.

**Comment by vaukai** [comment]
> i still get the file collisions error. it might probably be better to do the slotmove approach in this case, maybe even with keeping the revbump. and i merged the first commit.

just rebased. as much i would like to move back to default slot, will keep that part for later and mark this PR as draft
could you please merge https://github.com/gentoo/gentoo/pull/38364?

**Comment by fordfrog** [comment]
> could you please merge #38364?

still waiting for the checks to finish...

**Comment by vaukai** [comment]
> > could you please merge #38364?
> 
> still waiting for the checks to finish...

what about merging https://github.com/gentoo/gentoo/pull/38203? i can see "status broken" but in https://qa-reports.gentoo.org/output/gentoo-ci/19980bc720/output.html there are about 200 other `DeprecatedEclass` complaints most of them `llvm` or `linux-mod`

**Comment by vaukai** [comment]
> i still get the file collisions error. it might probably be better to do the slotmove approach in this case, maybe even with keeping the revbump. and i merged the first commit.

@fordfrog something's weird, no idea if related or not:: it does not have a `package.env` file.
and in the build log (eclass debugging is on) it's not having any line with `java-pkg_init_paths_:`.
did i break it?

**Comment by fordfrog** [comment]
> @fordfrog something's weird, no idea if related or not:: it does not have a `package.env` file. and in the build log (eclass debugging is on) it's not having any line with `java-pkg_init_paths_:`. did i break it?

i also noticed there is no `package.env` but i have no idea whether it was the same before or it is because it has its own script for running. anyway, the app starts fine without issues.

**Comment by vaukai** [comment]
> i still get the file collisions error. [...]

what exactly is the conflicting file(s)? i could try to investigate.

**Comment by fordfrog** [comment]
> > i still get the file collisions error. [...]
> 
> what exactly is the conflicting file(s)? i could try to investigate.

just emerge current visualvm and then try to emerge the reslotted one.

**Comment by vaukai** [comment]
> > > i still get the file collisions error. [...]
> > 
> > 
> > what exactly is the conflicting file(s)? i could try to investigate.
> 
> just emerge current visualvm and then try to emerge the reslotted one.

oh oh, didn't you already mention we should try with sofblocking?

**Pull request closed without merging**
