### PR TITLE
Unmask qt5 USE flag on some profiles

### PR DESCRIPTION
**Pull request by Pesa**
Let's see what breaks... @gentoo/qt

### CODE REVIEW

**Comment by Pesa** [comment]
@jer-gentoo can you please review/ack the `hppa` changes (3rd commit)?

I've already filed a bug for one of the two missing deps, but I'm not sure if you want to stabilize them just for one package that needs them... although there might be more in the future... either way, let me know, thanks.

**Comment by mgorny** [comment]
@Pesa, i don't think jer actually replies on github. Try to catch him elsewhere.

**Comment by Pesa** [comment]
Alright then, I'll open a bug for the hppa changes, and merge the rest.

**Comment by Pesa** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=585390

**Pull request closed without merging**
