### PR TITLE
sys-block/targetcli-fb: bump to 2.1.49

### PR DESCRIPTION
**Pull request by diogocp**

### CODE REVIEW

**Comment by diogocp** [comment]
Upstream maintainer.

**Comment by monsieurp** [comment]
He has no account on https://bugs.gentoo.org.

**Comment by diogocp** [comment]
Yeah, he is an **upstream** maintainer. Same as Andy Grover (who doesn't seem very active anymore).

**Comment by monsieurp** [comment]
Great! Nonetheless he still has no account on https://bugs.gentoo.org. Please get him to create one so that he can be assigned bugs.

**Comment by monsieurp** [comment]
@diogocp: Hi! Is Maurrizio willing to create an account? This PR won't be merged until he does so.

**Comment by juippis** [comment]
I think the question here is: Do you have his consent on being added here as a ebuild maintainer, or did you just add him because he's the upstream maintainer? Does _he_ even use Gentoo?

**Comment by diogocp** [comment]
I did not add him as an ebuild maintainer. I added him to the upstream section because he is an upstream maintainer. He is not supposed to get assigned Gentoo bugs. I've done the same in several other packages and there was never a problem.

Anyway, I won't have access to a computer until next week, so I won't be touching this until then.

**Comment by monsieurp** [comment]
> I've done the same in several other packages and there was never a problem.

Well that's actually a problem. Email addresses in metadata.xml files are meant to be linked to Gentoo Bugzilla accounts for bug assignments. Why? Gentoo bug wranglers read this file when a bug against a package is filed. Again, I'm not trying to be a PITA, I just want to avoid a situation in which we've got to deal with a bug but there's no maintainer to talk to. It happened before and we would like it not to happen again.

**Comment by mgorny** [comment]
I'm sorry about the mistake here. Could you rebase this?

**Comment by diogocp** [comment]
Rebased, thanks.

**Pull request closed without merging**
