### PR TITLE
dev-python/paho-mqtt: add pypy3 in PYTHON_COMPAT

### PR DESCRIPTION
**Pull request by MocioF**
---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by mattst88** [comment]
This is fine with me, but I have no idea whether the Python team has any policy about adding `pypy3` to `PYTHON_COMPAT`.

Do the tests run by `src_test` pass with `pypy3`?

**Comment by mgorny** [comment]
Please don't revbump for `PYTHON_COMPAT`, unless you absolutely have to (i.e. the implementation is unmasked on stable and the deps don't have matching keywords).

Adding pypy3 is fine, as long as tests pass.

**Comment by mattst88** [comment]
Do the tests run by `src_test` pass with `pypy3`?

**Comment by MocioF** [comment]
This is a log for 1.6.1-r1:
https://pastebin.com/nYqGTj1B

**Comment by MocioF** [comment]
And this is a log for 2.1.0: https://pastebin.com/C3W1L2cz
On 2.1.0 I have some random failures on tests/test_client.py::TestCompatibility::test_callback_v1_mqtt3[tcp] FAILED 
but it happens even if pypy3 is not set (I am not able to reproduce it in a predictable way)

**Pull request closed without merging**
