### PR TITLE
net-im/mattermost-desktop-bin: New package (#608646)

### PR DESCRIPTION
**Pull request by mhz-tamb**

### CODE REVIEW

**Comment by monsieurp** [comment]
Thank you for your contribution :+1: It's now in the tree.

**Comment by hartwork** [comment]
Hi!
I just noticed that [3.5.0 is of 2016-11-15](https://github.com/mattermost/platform/releases/tag/v3.5.0) while [upstream is at 3.6.2 by now](https://github.com/mattermost/platform/releases).
A bump to a more recent version would be welcome, if you find time.
Thanks!

**Comment by mhz-tamb** [comment]
@hartwork thank you for your notice!
You are mixed up repositories for [server side](https://github.com/mattermost/platform) and [desktop](https://github.com/mattermost/desktop) applications. Current version is relevant.

**Comment by hartwork** [comment]
I see. Nevermind then :smiley:

**Pull request closed without merging**
