### PR TITLE
net-firewall/shorewall: Version bump wrt bug #563088

### PR DESCRIPTION
**Pull request by Whissi**
This PR bumps net-firewall/shorewall to v5.0.1.

Maybe you'll stumble across some QA warnings regarding systemd. Please ignore them. These are not new, see the discussion from https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/101 ...

Bug: https://bugs.gentoo.org/show_bug.cgi?id=563088

Changes regarding v4.6.13.1:
- In v5 we finally dropped `rc_need="net"`

- Files moved from $FILESDIR/$MAJOR_VERSION to $FILESDIR (subdir per version is no longer needed).

Bug: https://bugs.gentoo.org/show_bug.cgi?id=563088

### CODE REVIEW

**Comment by Whissi** [comment]
Thank you for your feedback.

People following upstream know that v5.0.1 replaced v5.0.0 within 48h. But I'll take your feedback and next time I'll try to be more precise to avoid confusion of people who don't follow upstream.

Same with `rc_need`: I tested this with people I know running shorewall in v4.6 (this change was already planned for 4.6). Next time when writing a commit message I'll try to write for people who maybe don't know.

Because I am currently on vacation please don't expect me to update the PR within the next week. If this will block feel free to alter my MSG (and drop my signed commit) to proceed.

Thank!

**Comment by idella** [comment]
Added to portage

**Comment by mgorny** [comment]
@idella, why do you add stuff to the package manager?

**Comment by idella** [comment]
Oh I see. You are attempting to correct my use of english.  The term portage like server has been pushed and shoved around to represent or denote who knows how many disparate concepts, and you take opportunity to poke at me at use of one of its many denotations. Duly noted.

**Pull request closed without merging**
