### PR TITLE
dev-db/mydumper: bump to 0.9.3

### PR DESCRIPTION
**Pull request by hydrapolic**
https://bugs.gentoo.org/572516
https://bugs.gentoo.org/630848

### CODE REVIEW

**Comment by UnixRonin** [comment]
Builds for me but with the following warnings:

/var/tmp/portage/dev-db/mydumper-0.9.3/work/mydumper-0.9.3_build/docs/_sources/files.rst:39: WARNING: unknown option: mydumper --schemas
WARNING: html_static_path entry '/var/tmp/portage/dev-db/mydumper-0.9.3/work/mydumper-0.9.3/docs/_static' does not exist

**Comment by UnixRonin** [comment]
Verified operational functionality of mydumper-0.9.3

**Comment by hydrapolic** [comment]
Thanks for checking and reporting back @UnixRonin.

**Comment by Amynka** [comment]
@hydrapolic Now it works for me. Is it ready for merge?

**Comment by hydrapolic** [comment]
@Amynka,I believe yes it is.

**Comment by hydrapolic** [comment]
Thank you

**Comment by Amynka** [comment]
Thank you ! :)

**Pull request closed without merging**
