### PR TITLE
Drop old gstreamer versions

### PR DESCRIPTION
**Pull request by mattst88**

### CODE REVIEW

**Comment by mattst88** [comment]
Cc: @i-garrison

**Comment by i-garrison** [comment]
Does it make sense to wait for stabilizing updates to these two packages and then clean up them as well in one go?
```
media-libs/gst-rtsp-server/gst-rtsp-server-1.16.3.ebuild
media-libs/gstreamer-editing-services/gstreamer-editing-services-1.16.3.ebuild
```

**Comment by mattst88** [comment]
> 

If we can do that in the next couple of days, sure. Otherwise, those don't seem to be blocking the removal of any other old versions, so it's not required.

I thought we'd gotten all the stragglers in https://bugs.gentoo.org/848426 :(

**Comment by i-garrison** [comment]
> If we can do that in the next couple of days, sure. Otherwise, those don't seem to be blocking the removal of any other old versions, so it's not required.
I just double-checked that these two from 1.16.3 and new 1.20.2 counterparts are building fine against rest of gstreamer being 1.20.2 so this should be fine to clean up later.

**Comment by mattst88** [comment]
Merged.

**Pull request closed without merging**
