### PR TITLE
dev-vcs/hg-fast-export: bump to 20160914, add ~x86

### PR DESCRIPTION
**Pull request by sbraz**
@junghans Hi, there is a new version of the package, it was [tagged on GitHub](https://github.com/frej/fast-export/releases/tag/v160914).

I got rid of the now-useless `rm Makefile`, added the hg-reset script and replaced dodoc with a call to default. I also removed an old version and added ~x86 after testing the package on this arch. Let me know if you want me to change anything.
```diff
--- hg-fast-export-20150816.ebuild      2016-09-14 09:32:18.578997340 +0200
+++ hg-fast-export-20160914.ebuild      2016-09-14 14:42:13.879879433 +0200
@@ -1,21 +1,21 @@
-# Copyright 1999-2015 Gentoo Foundation
+# Copyright 1999-2016 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
-EAPI=5
+EAPI=6
 
 PYTHON_COMPAT=( python2_7 )
 
 inherit python-r1 vcs-snapshot
 
-COMMIT="3c27c693e13482059966003dd6545941b942a97a"
+COMMIT="v${PV#20}"
 DESCRIPTION="mercurial to git converter using git-fast-import"
 HOMEPAGE="https://github.com/frej/fast-export"
 SRC_URI="${HOMEPAGE}/archive/${COMMIT}.tar.gz -> ${P}.tar.gz"
 
 LICENSE="MIT"
 SLOT="0"
-KEYWORDS="~amd64 ~arm"
+KEYWORDS="~amd64 ~arm ~x86"
 IUSE=""
 
 DEPEND=""
@@ -24,16 +24,18 @@
        ${PYTHON_DEPS}"
 
 src_prepare() {
+       default
        sed -e '/^PYTHON/s/python/&2.7/' \
                -e '/^PYTHON/s/PYTHON:/E&/g' \
                -e "/^ROOT/s:=.*:='${EPREFIX}/usr/bin':" \
-               -i "${PN}".sh || die
-       rm Makefile || die #don't compile old svn2git code
+               -i "${PN}".sh hg-reset.sh || die
 }
 
 src_install() {
+       default
        newbin "${PN}".sh "${PN}"
-       dodoc README
+       newbin hg-reset.sh hg-reset
        python_foreach_impl python_doexe "${PN}".py
+       python_foreach_impl python_doexe hg-reset.py
        python_foreach_impl python_domodule hg2git.py
 }

```

### CODE REVIEW

**Comment by sbraz** [comment]
Maybe we should wait for this to be fixed before bumping: https://github.com/frej/fast-export/pull/73

**Comment by sbraz** [comment]
Thanks for merging it! I think there's a problem with the version scheme change: I ran `emerge -uND world` and it did not "downgrade" the package (which is what I assume you were trying to do by removing the older versions). I may be wrong but I think you should revert this commit.

**Comment by junghans** [comment]
In my case `emerge -auND world` picks up the new (downgraded) version fine, maybe you forgot to unmask it.

**Comment by sbraz** [comment]
Hmm you might be right, it is now upgraded, I might have missed it when I ran emerge last time :)
I think you could remove `COMMIT="v${PV#20}"` now that you follow the upstream versioning scheme.

**Comment by junghans** [comment]
7764cc7d84f50a520759c138e6965cfaf3d392f4

**Pull request closed without merging**
