### PR TITLE
dev-lang/zig-bin: new package

### PR DESCRIPTION
**Pull request by BratishkaErik**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: BratishkaErik <bratishkaerik@getgoogleoff.me>

### CODE REVIEW

**Comment by BratishkaErik** [comment]
ok, merge conflict

**Comment by thesamesam** [comment]
Is there a reason you closed this? I think we want it.

cc @jsmolic

**Comment by jsmolic** [comment]
Yes, I think having a binary zig version is a good idea (we can even do ncdu-bin alongside), @BratishkaErik if you'd like to work on this again could you reopen this one or create a new PR?

**Comment by BratishkaErik** [comment]
> Yes, I think having a binary zig version is a good idea (we can even do ncdu-bin alongside), @BratishkaErik if you'd like to work on this again could you reopen this one or create a new PR?

AFAIR `dev-lang/zig-bin` dynamically linked executables with musl libc, so packages it built didn't work. I can create `ncdu-bin` ebuild, but I don't know if I can get `zig-bin` to work :)

**Comment by BratishkaErik** [comment]
See https://github.com/gentoo/gentoo/pull/26325

**Pull request closed without merging**
