### PR TITLE
=www-client/seamonkey-2.53.17: missing dependencies fix.

### PR DESCRIPTION
**Pull request by BioMike**
Adds dependencies for clang and llvm.

Closes: https://bugs.gentoo.org/911830

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
I don't have time to properly review this right now (hopefully tomorrow), but I don't believe this is the right fix. You may be better usign *llvm.eclass* here, since it looks to be using llvm's toolchain. Are you sure it doesn't work with llvm:16?

Please see https://devmanual.gentoo.org/eclass-reference/llvm.eclass/index.html and e.g. how firefox handles llvm. Simply I think, specify LLVM_MAX_SLOTS, add the deps 
```
|| (
	(
		clang:16
		llvm:16
	)
	(
		clang:15
		llvm:15
	)
)
```
and do the `pkg_setup` step necessary.

**Comment by BioMike** [comment]
Ok, I thought that the BDEPEND was just enough. I'll have a look at the link and the firefox ebuild and push my changes to a new commit.

**Comment by BioMike** [comment]
Tested with setting LLVM_MAX_SLOTS to both 15 and 16 (to enforce use of a specific version), both seemed to compile and run without issues.

**Review by juippis — COMMENTED** [review]
Sigh, sorry to bother you again but:
```
 4:53.35 In file included from Unified_cpp_url-classifier0.cpp:74:
 4:53.35 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/toolkit/components/url-classifier/nsUrlClassifierDBService.cpp: In member function 'nsresult nsUrlClassifierDBServiceWorker::NotifyUpdateObserver(nsresult)':
 4:53.35 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/toolkit/components/url-classifier/nsUrlClassifierDBService.cpp:654:12: warning: variable 'updateStatus' set but not used [-Wunused-but-set-variable]
 4:53.35   654 |   nsresult updateStatus = mUpdateStatus;
 4:53.35       |            ^~~~~~~~~~~~
 4:53.36 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h: Assembler messages:
 4:53.36 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.36 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.36 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.36 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 /var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/media/ffvpx/libavcodec/x86/mathops.h:125: Error: operand type mismatch for `shr'
 4:53.37 gmake[4]: *** [/var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/config/rules.mk:708: flac.o] Error 1
 4:53.37 gmake[4]: Leaving directory '/var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/seamonk/media/ffvpx/libavcodec'
 4:53.37 gmake[3]: *** [/var/tmp/portage/www-client/seamonkey-2.53.17/work/seamonkey-2.53.17/config/recurse.mk:74: media/ffvpx/libavcodec/target] Error 2
 4:53.37 gmake[3]: *** Waiting for unfinished jobs....
```
This is bug https://bugs.gentoo.org/911679 - you can find the patch there, but you most likely have to edit the paths.

**Comment by BioMike** [comment]
Not a problem regarding bothering me, what counts is that it works for everyone. Seems like this issue is unrelated to the llvm/clang issue, but I'll have a look at it later this day.

I'll also have a look at some of the CI/QA issues reported by the automated tests.

**Comment by juippis** [comment]
> Not a problem regarding bothering me, what counts is that it works for everyone. Seems like this issue is unrelated to the llvm/clang issue, but I'll have a look at it later this day.

Indeed, but if I push this now onto ~arch, people running ~arch are going to hit it :) 
Thanks! It shouldn't be a hard thing to fix, but as said, patching it needs manual path mangling.

**Review by juippis — APPROVED** [review]
Thanks!

**Pull request closed without merging**
