### PR TITLE
media-libs/urt: build fixes, QA cleanups, new shared lib build and static-libs USE flag

### PR DESCRIPTION
**Pull request by sarnold**
Workflow-compliant even.

This fixes base object build, creates a shared library, and adds a use
flag for static-libs.  Updated SRC_URI, created upstream repo (homepage
is "inactive" and doesn't even have a download link anymore).

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by vapier** [comment]
this should be sep commits imo.  the fact your summary line describes multiple things is a pretty strong indicator of that.

**Comment by sarnold** [comment]
I thought about that, but stable is old/stale/broken anyway, so one commit seemed "logical" enough, at least according to the workflow doc.  The stable changes are just QA fixes to make repoman happy, so the primary "logical" commit is new unstable with fixes.  How would you split that up into multiple logical commits?  Maybe I'm just not seeing it...

**Comment by mgorny** [comment]
@gentoo/graphics

**Comment by vapier** [comment]
the status of the current ebuild is irrelevant when it comes to applying fixes.  independent changes should be independent.  review (historical & current) is made much harder when a lot of unrelated changes are squashed into one.

**Comment by sarnold** [comment]
So you think this needs to be split between repoman/eapi bump and a new unstable package?  It doesn't seem like a big commit as it stands, or really worth splitting up, but I suppose since I have about 5 years of life left I have plenty of time to do this again...

**Comment by mgorny** [comment]
I don't know about all that splitting. Of course, you could say it's easier to look at stuff when you copy the ebuild first, then apply changes. But that means you get interim commits which are broken by themselves, or inline changes which normally require a revbump.

**Comment by sarnold** [comment]
I actually did try it both ways, but git ends up making it look the same (at least without an interim commit). I'm also working on RC version but it's not quite ready...

**Comment by sarnold** [comment]
Ping...  Somebody should at least fix ncurses with a rev-bump...

**Comment by mgorny** [comment]
Err, did you fail to use separate branches for irrelevant changes? :-P

**Comment by monsieurp** [comment]
Are we getting somewhere with this PR?

**Comment by mgorny** [comment]
Doubt it. I have no clue how to proceed.

**Comment by sarnold** [comment]
Keep your panties on, I just got my new key data updated so I should be able to make this go away (In Theory...)

**Comment by sarnold** [comment]
Hold on to your hats...

**Comment by hasufell** [comment]
wooooosh :rage4:

**Comment by hasufell** [comment]
@sarnold did you use the merge button? That won't work...

**Pull request merged**
