### PR TITLE
media-fonts/symbols-nerd-font: take over maintainership

### PR DESCRIPTION
**Pull request by imwints**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by ionenwks** [comment]
If you want to take it over the per-comment, then I guess that means you have plans for this package? If you just want it as-is, then there's no need to do this. I will likely keyword it later and bump it regularly.

If planning to e.g. start bringing more nerd fonts to ::gentoo, then I'd rather not add extra burden on proxy-maint with (new) packages. With that comment I had more in mind of a Gentoo developer taking it over rather than proxied maintainer.

**Comment by ionenwks** [comment]
Either way, I'll close this given (bare some exception) we don't typically add proxied maintainers unless they have changes to go along with it.

**Comment by imwints** [comment]
I just wanted to bump the package on updates. I use kitty and since they recommend using this in addition to an unpatched font I was happy you introduced this into ::gentoo. I interpreted the comment as that you didn't want to maintain it further. I had nothing special in mind :)

**Comment by ionenwks** [comment]
Ah ok, and no the comment is because a lot of users care about nerd fonts and there's a whole suite of them (overlays that package them are far more involved), but I didn't want to go that far and just did a simple package w/ the prebuilt version.

Figured someone may be unhappy with that so I left a comment.

Just bumping it in its current state is super trivial, so yeah I'll do it :) Thanks for trying to help still!

**Pull request closed without merging**
