### PR TITLE
net-fs/davfs2: bump to 1.5.4, eapi bump, add nls flag, update license

### PR DESCRIPTION
**Pull request by gktrk**
- Bump to EAPI 6
- Add a "nls" USE flag along with the gettext build time, and libintl
  and libiconv runtime deps
- The source is licensed with GPL-3+ now

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
LGTM.

**Comment by idella** [comment]
That line 1 commit msg stretched to like 83 chars but, well it's trivial
and there are worse in the git log.

**Comment by gktrk** [comment]
$ echo 'ebuild-writing/variables: add a section to explain the ROOT variable #144332' | wc -c
77

**Pull request closed without merging**
