### PR TITLE
Remove Qross 0.3.1

### PR DESCRIPTION
**Pull request by 0xd34df00d**
It's an old Qt4-only version. Also a nice way to fix https://bugs.gentoo.org/show_bug.cgi?id=581540

### CODE REVIEW

**Comment by 0xd34df00d** [comment]
@SoapGentoo ping.

**Comment by 0xd34df00d** [comment]
Oh, I force-pushed a new set of changes without noticing this one isn't merged yet. Should finally learn aprpoved ≠ merged :)

**Comment by SoapGentoo** [comment]
@0xd34df00d can you resend the changes?

**Comment by 0xd34df00d** [comment]
@SoapGentoo sure, see #4154.

**Pull request closed without merging**
