### PR TITLE
app-misc/beep: capabilities

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-3.0.14, Repoman-3.0.2
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
ping

**Comment by mgorny** [comment]
https://bugs.gentoo.org/716734 pretty correctly says `USE=suid` doesn't work anymore, so at the very least you can remove that.

It works just fine for me, though. I don't recall if I set some special rules for it but I doubt it. Is there really a need to play with caps these days?

**Review by mgorny — APPROVED** [review]
Thanks for this, and I'm sorry that it took this long to merge it. Please remember to leave a comment after pushing changes as we otherwise find it hard to notice that something has happened.

**Comment by ionenwks** [comment]
Note that if USE=-filecaps, this will fallback to installing beep suid root without the former :audio group limitation.

**Pull request closed without merging**
