### PR TITLE
profiles/thirdpartymirrors: big cleanup & update of mirror lists

### PR DESCRIPTION
**Pull request by benkohler**
I opened bug 494672 a while back to track various problems & cleanups of the profiles/thirdparymirrors list.  Some of the mirror groups were fixed right away, some never were.  But I thought it was time to take another look at this list in 2017.

I have a semi-automated mirror checking script that I have used in conjunction with fully-manual testing where needed.  In some lists I have merely pruned the dead mirrors leaving the good ones, but where possible & appropriate I have pulled a fresh list from upstream.

Also a few mirror groups are flat-out removed.

If there are any questions about how I came to make any of the changes, let me know.

### CODE REVIEW

**Comment by benkohler** [comment]
I see QA bot isn't going to allow me to remove mirror lists still in active use, so this is going to need some more work.  Any ideas for a dummy URL to be used where upstream is gone? Or do we have to get every affected ebuild fixed before the mirror group can be cleaned?

**Comment by Dessa** [comment]
unless the process changed recently, its the latter.

**Comment by mgorny** [comment]
You really ought to fix the ebuilds properly first. Either use the new homepage if there is one, or replace it with No_homepage + mirror://gentoo if there is not.

**Comment by benkohler** [comment]
The whole freebsd group is a mistake, so those problems all will go away.  That just leaves snobol and vdrfiles groups, I have open bugs on them already, for the purposes of this cleanup I will just leave them as-is, no removal no fix.  Working on a revised PR now.

**Pull request closed without merging**
