### PR TITLE
www-client/firefox{,-bin}: Disable ad attribution api by default

### PR DESCRIPTION
**Pull request by WhatAmISupposedToPutHere**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
I've really thought about what to do with this. Based on https://andrewmoore.ca/blog/post/mozilla-ppa/ I decided not to touch it. Few things:

If you use ublock origin (and especially the advanced mode), it's the best guard you can have. I you build Firefox with `-telemetry` option, it should disable this feature and many more by default. And finally from the blog 

> You have to remember that the alternative is NOT the absence of tracking, but invasive personalized tracking done by ad networks. 

So I'm not convinced turning the option off from the ebuild is the best practice.

**Comment by WhatAmISupposedToPutHere** [comment]
I disagree with the opinion in that blog. 

1. For some reason mozilla thinks that they need to throw adtechs a bone before introducing strengthened tracking protections in firefox. However, they have previously successfully introduced similar protections without having to beg for permission from the ad networks, and they can do that again. 

2. Pre-surrendering to the adtechs' demands will not make them more likely to be benevolent and voluntarily reduce their tracking. While mozilla thinks that the choice is between invasive tracking and less invasive one, we have a lot of historical evidence that shows that its actually a choice between invasive tracking by adtechs or somewhat privacy preserving tracking by mozilla _and_ invasive tracking by adtechs. 

3. The actual reason mozilla enabled this feature by default is because nobody would enable it otherwise. The public perception of ad networks is strongly negative, and i do not see anyone wanting to help them in any way, shape, or form, and mozilla also understands that the only way this feature would ever take off is by being "sneakily" enabled and hoping most people would not notice.

**Comment by juippis** [comment]
You clearly have a strong opinion on the subject. But I'd like some facts, not opinions, why this is bad enough to be disabled for everyone.

You can use ublock origin and this doesn't affect you.
You can disable `-telemetry` completely and it doesn't work.
You can use `/etc/firefox/sysprof.js` to deliver the config for multiple installations.

And so far no distro other than Alpine seems to disable this. That's why I'm leaning towards not handling it on distro-level either. (and especially not for firefox-bin, that should remain as close to upstream as possible - in fact, I should remove the DoH limitation too)

**Comment by juippis** [comment]
**If** it gets disabled by default upstream, that solves it for us too :) I'll keep an eye out on https://bugzilla.mozilla.org/show_bug.cgi?id=1900929 - is your bug linked there? 

I'll also send a message to a certain ["distribution-maintainer-list"](https://lore.kernel.org/distributions/) asking how other distro maintainers feel about toggling this option distribution-wise. Let me know if your endeavours prove to be successful and I'll reconsider this.

**Comment by juippis** [comment]
Here's a patch to turn it off by default, that can be thrown into */etc/portage/patches/*:
https://phabricator.services.mozilla.com/D216714

**Comment by WhatAmISupposedToPutHere** [comment]
No offense, i understand that you are trying to be helpful, but it just so happens that you are linking _my_ patch here :P

**Pull request closed without merging**
