### PR TITLE
*/*: Add python 3.13 compat to various packages

### PR DESCRIPTION
**Pull request by WhatAmISupposedToPutHere**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please confirm the test suite passes for these, will merge then, thanks

**Comment by WhatAmISupposedToPutHere** [comment]
Fixed test suites for icu and rdflib, everything else had no regressions.

**Comment by thesamesam** [comment]
> Fixed test suites for icu and rdflib, everything else had no regressions.

Thanks. Can you drop the revbump for ICU? (It's a test-only fix).

Also, could you add the link to the upstream patches/references to the top of each patch?

(I would just fix that myself but I can't push right now b/c of some infra issues)

**Comment by WhatAmISupposedToPutHere** [comment]
Added patch urls, undid revbump

**Comment by thesamesam** [comment]
Thanks, pushed with pycups dropped to ~arch!

**Pull request closed without merging**
