### PR TITLE
ROCm 6.1.1 libraries

### PR DESCRIPTION
**Pull request by AngryLoki**
This PR fixes multiple issues in previous 6.1 ROCm packages (critical ones, which caused these packages to be masked in https://github.com/gentoo/gentoo/commit/563b5abdaf7e92576aa92b559e4c7970ed2c44fd).

Major things to note:
* This release adds new targets gfx940/gfx941/gfx942 to profiles/desc
* Update in `dev-libs/half` relocates headers from `/usr/include` to `/usr/include/half`. However transition is smooth, as all current packages expect to see `half.hpp` in `/usr/include/half` in the first place.
* In `dev-util/rocm-smi` soname is now librocm_smi64.so.6 (was librocm_smi64.so.1 as in Debian). Now it matches official/Fedora scheme.

New packages added to gradually close gap with official release:
* `dev-libs/hipother` - ROCclr runtime implementation for non-AMD HIP platforms, like NVIDIA
* `sci-libs/rpp` - AMD ROCm Performance Primitives (RPP) high-performance computer vision library
* `dev-libs/rocdbgapi` - AMD Debugger API - `dev-debug/gdb-14.2` can debug AMDGPU code, if you build/link it with rocdbgapi.

Not added:
* hipBLASLt - 6.0.2 has multiple compilation issues, which were fixed in master branch. It will be needed in caffe2 later (unless https://github.com/pytorch/pytorch/pull/120551 is merged), but there is still some time to wait for the next release

Closes: https://bugs.gentoo.org/927274

### CODE REVIEW

**Comment by AngryLoki** [comment]
Also I would be grateful if you could merge these PRs:
* https://github.com/gentoo/gentoo/pull/33861
* https://github.com/gentoo/gentoo/pull/34212

so I could resolve git conflicts (if any) and apply test suite patches from there.

**Comment by littlewu2508** [comment]
`rocm.eclass` for ROCm-6 is ready now: https://github.com/gentoo/gentoo/pull/36254

**Comment by Bratzmeister** [comment]
@heroxbd @AngryLoki can we please have review/merge? I eagerly await this <3 sadly rocm 5.7.1 makes my gpu crash often and it's about to be deprecated upstream for newer libraries (pytorch and friends)

**Comment by heroxbd** [comment]
Bratzmeister ***@***.***> writes:

> @heroxbd @AngryLoki can we please have review/merge? I eagerly await
> this <3 sadly rocm 5.7.1 makes my gpu crash often and it's about to be
> deprecated upstream for newer libraries (pytorch and friends)

Thanks for reminding.  Can you confirm that ROCm-6 solves your issue?

**Comment by AngryLoki** [comment]
@Bratzmeister , I'd like to see https://github.com/gentoo/gentoo/pull/36509 merged first. I'll update my PR after that.

**Comment by Bratzmeister** [comment]
> Bratzmeister ***@***.***> writes:
> @heroxbd @AngryLoki can we please have review/merge? I eagerly await this <3 sadly rocm 5.7.1 makes my gpu crash often and it's about to be deprecated upstream for newer libraries (pytorch and friends)
> Thanks for reminding. Can you confirm that ROCm-6 solves your issue?

I currently run rocm6 as docker containers on t he same machine as 5.7 natively always results in crashes/hangs freezes but it's very bothersome as I have multiple use cases for pytorch etc. Maintaining all these containers is very annoying. I'm running a Radeon RX 7900 XT (gfx1100) btw. If I can help with something let me know.

**Comment by AngryLoki** [comment]
@negril , I integrated all commits littlewu2508's PR here, rebased everything against master branch and rebuilt everything one more time, added few more fixes; most important is that now `clang` now never fails with this:
```
clang: error: cannot find ROCm device library; provide its path via '--rocm-path' or '--rocm-device-lib-path', or pass '-nogpulib' to build without ROCm device library
```

Now this PR does not depend on anything and can be merged.

**Comment by negril** [comment]
> Now this PR does not depend on anything and can be merged.

Nice work. I'll check later and open a PR for the hipother stuff.

**Comment by AngryLoki** [comment]
@negril , I'm still waiting for review...

**Comment by NHOrus** [comment]
As far as I can see by quick look at commit names, my PR is orthogonal to this one, but they would go well together

**Comment by NHOrus** [comment]
Wait, does your rocm-smi-6.1.1 includes patch for GCC-14? https://github.com/gentoo/gentoo/pull/37289
It's not yet merged, but... Would be nice if it hasn't caused any tinderboxes to scream.

**Comment by negril** [comment]
> Wait, does your rocm-smi-6.1.1 includes patch for GCC-14? #37289 It's not yet merged, but... Would be nice if it hasn't caused any tinderboxes to scream.

https://github.com/AngryLoki/gentoo/commit/d6ae0551b0fc5eadd6442199e152e96a26c5fa5a#diff-514f5ccd6e810a334e74013efe440e4ec4ec38a5aeadefbf61c8baa3959cf3ac

**Comment by negril** [comment]
I found something to fix for `sci-libs/miopen`, but I don't think we should block this for that. @thesamesam feel free to merge.

**Pull request closed without merging**
