### PR TITLE
Keyworded mate and mate-extras for ~arm64

### PR DESCRIPTION
**Pull request by NeddySeagoon**
Keyworded mate and mate-extras for ~arm64
Removed the dvd use.mask.  A 64 bit Pi 3 plays the 1960s TV Robin Hood properly from a USB DVD.
It struggles with The Good the Bad and the Ugly.

Its not repoman clean but its no worse than when I started adding keywords.

### CODE REVIEW

**Comment by monsieurp** [comment]
this is one hell of a PR! how are we supposed to sign off on it?

**Comment by NeddySeagoon** [comment]
It does one thing to 60+ related packages. By adding ~arm64 to mate-base/mate-1.18, repoman wants most of the rest.  Its all build tested. Most of it operates on arm64 too.  There were a small number of packages that repoman spotted that I did not already have built. They built but I have no Idea how to test them.

The package.use change, (dvd) came about because something in mate-extras wanted it. Its tested with a USB DVD/RW drive.  That's a story in itself.  You really can burn CDs and play some DVDs properly with an arm64 Raspberry Pi 3.

Its a single logical change. If I split it up,  
repoman full -d arm64 
will get upset at the pieces.  Advice welcome. 

How to sign it off ...
First make sure it does no harm to non ~arm64.
Then build it and test it on arm64.

**Comment by NP-Hardass** [comment]
https://bugs.gentoo.org/636538
@gentoo/mate

**Comment by leio** [comment]
This now means that some of the stuff here has arm64 keywords for non-latest, and no keyword on the latest version in tree, from bumps that have happened in the meantime. Not a good place to stay at for long. Please go over the list and test the newer versions, or at least identify what do have newer versions that can be just marked too (as they would have carried over anyhow if the PR were merged earlier)

**Pull request closed without merging**
