### PR TITLE
media-video/ffmpeg: apply upstream patches needed to build docs

### PR DESCRIPTION
**Pull request by mehw**
Apply upstream patches to build FFmpeg's documentation with sys-apps/texinfo-6.8.

1. Fix missing CSS with texinfo 6.8 and above:
https://github.com/FFmpeg/FFmpeg/commit/c980dd7a976635426f129417836251740e19b54b

2. Fix missing TOC with texinfo 6.8 and above:
https://github.com/FFmpeg/FFmpeg/commit/bfbd5954e50e407693932b3900ca77c3daee26d7

```
diff -u ffmpeg-4.4-r1.ebuild ffmpeg-4.4-r2.ebuild
--- ffmpeg-4.4-r1.ebuild	2021-11-11 23:21:44.984997893 +0100
+++ ffmpeg-4.4-r2.ebuild	2021-11-14 08:59:19.185707723 +0100
@@ -59,7 +59,7 @@
 	samba? ( GPL-3 )
 "
 if [ "${PV#9999}" = "${PV}" ] ; then
-	KEYWORDS="~alpha amd64 arm arm64 ~hppa ~ia64 ~mips ppc ppc64 ~riscv sparc x86 ~amd64-linux ~x86-linux"
+	KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~sparc ~x86 ~amd64-linux ~x86-linux"
 fi
 
 # Options to use as use_enable in the foo[:bar] form.
@@ -318,6 +318,8 @@
 
 PATCHES=(
 	"${FILESDIR}"/chromium-r1.patch
+	"${FILESDIR}/${P}-fix-missing-CSS-with-texinfo-6.8.patch"
+	"${FILESDIR}/${P}-fix-missing-TOC-with-texinfo-6.8.patch"
 )
 
 MULTILIB_WRAPPED_HEADERS=(

```

```
diff -u ffmpeg-4.4.1-r1.ebuild ffmpeg/ffmpeg-4.4.1-r2.ebuild
--- ffmpeg-4.4.1-r1.ebuild	2021-11-11 23:21:44.984997893 +0100
+++ ffmpeg-4.4.1-r2.ebuild	2021-11-14 08:59:19.189707743 +0100
@@ -321,6 +321,8 @@
 
 PATCHES=(
 	"${FILESDIR}"/chromium-r1.patch
+	"${FILESDIR}/${PN}-4.4-fix-missing-CSS-with-texinfo-6.8.patch"
+	"${FILESDIR}/${PN}-4.4-fix-missing-TOC-with-texinfo-6.8.patch"
 )
 
 MULTILIB_WRAPPED_HEADERS=(

```

### CODE REVIEW

**Comment by ConiKost** [comment]
Is this still needed for current versions?

**Comment by mehw** [comment]
> Is this still needed for current versions?

Looking at the master tree right now, `media-video/ffmpeg-4.4.4-r8` can apply it.

About `media-video/ffmpeg-5.1.4-r1` and above (`6.0-r9`, `6.0-r10`, `6.0.1`, `6.1-r3`, `6.1.1`), this PR was already integrated upstream.

**Comment by thesamesam** [comment]
I think I added it to -r8?

**Comment by mehw** [comment]
> I think I added it to -r8?

@thesamesam thank you: http://distfiles.gentoo.org/distfiles/a1/ffmpeg-4.4.4-texinfo.patch.xz

I'm closing this PR, the issue is fixed.

**Pull request closed without merging**
