### PR TITLE
dev-ml/qcheck: new ebuild

### PR DESCRIPTION
**Pull request by tomboy-64**
- needed as a transitive dependency for Libre S3 1.1 (net-misc/libres3)

PR as per [bug #559652](https://bugs.gentoo.org/show_bug.cgi?id=559652) for @aballier .

### CODE REVIEW

**Comment by aballier** [comment]
this one has no out of tree dep

**Comment by aballier** [comment]
lgtm: please squash and double check how to enable/disable ounit support

**Comment by aballier** [comment]
@gentoo-repo-qa-bot please test this

@mgorny : in other projects we were doing like that for build tests

**Comment by mgorny** [comment]
Nah, CI is much simpler. Doesn't do magic, just `git fetch ...` and checks for changed refs.

**Pull request merged**
