### PR TITLE
net-misc/libres3: new ebuild

### PR DESCRIPTION
**Pull request by tomboy-64**
See [bug #559652](https://bugs.gentoo.org/show_bug.cgi?id=559652).
PR as per [bug #559652](https://bugs.gentoo.org/show_bug.cgi?id=559652) for @aballier .

### CODE REVIEW

**Comment by mgorny** [comment]
Sory for mass-closing PRs like this but really *please do not kill* our scripts. Please add all those commits to a single pull request.

**Comment by aballier** [comment]
it is much harder to review in a single pr imho

**Comment by mgorny** [comment]
If you really want single pull requests, do them, say, at most 3 at once, as long as they're not inter-dependent. Then open more once you finished reviewing those that are open. Please remember that every PR implies a CI run. Therefore, if you open >10 PRs, you are blocking CI for a few hours, at least, preventing anything else from being checked.

**Comment by mgorny** [comment]
@tomboy-64, also please run `repoman full` on each added package in each commit before adding a PR. Something like this: commit pkg1, repoman full in pkg1, commit pkg2, repoman full in pkg2… then push them all to a PR.

**Comment by mgorny** [comment]
Ok, since @aballier insists on separate PRs, let's see how they go. I will try to manually start CI runs to avoid killing the hardware and preventing others from contributing.

**Comment by aballier** [comment]
let's close this one as it has missing deps, please update it meanwhile

**Pull request closed without merging**
