### PR TITLE
sys-fs/btrfsmaintenance: Add better systemd support.

### PR DESCRIPTION
**Pull request by comio**

### CODE REVIEW

**Comment by madmartin** [comment]
hello @comio 
thanks for you contribution.
At first I have to say this is not the right place here. You contribution is MUCH better placed at the upstream project https://github.com/kdave/btrfsmaintenance because it is of a general interest, not only focused on gentoo ebuilds.

Second, I would propose you to change the implementations of systemd timers before you send it to @kdave

I think there are too many timer files, two timer/cron scripts where one should be sufficient.
I propose
- merge the functionality of btrfsmaintenance-refresh-timers.sh into btrfsmaintenance-refresh-cron.sh
- add something like TIMER_IMPLEMENTATION="cron|systemd-timers" into the config file
- reduce timer files (daily,weekly,monthly) into ONE timer file without OnCalendar= setting for each component. Example: btrfs-trim.timer 
- This files go to /usr/lib/systemd/system/
- the timer schedule can then be added to a extension file under e.g. /etc/systemd/system/btrfs-trim.timer.d/ by the btrfsmaintenance-refresh-cron.sh script
look here for more information: 

https://access.redhat.com/documentation/en-US/Red_Hat_Enterprise_Linux/7/html/System_Administrators_Guide/sect-Managing_Services_with_systemd-Unit_Files.html#brid-Managing_Services_with_systemd-Extending_Unit_Config

**Comment by madmartin** [comment]
Upstream project's discussion place:
https://github.com/kdave/btrfsmaintenance/issues/29

**Comment by comio** [comment]
Hi @madmartin rtin,

don't worry, I know how extend systemd units/services ;) I just don't like to mkdir and create files... bypassing the systemd by means a self made script. BTW I understand that there are too much timers and I will write a new version following your suggestions.

Regarding the script I'm not sure that I like to have just one script managed by an option (TIMER_IMPLEMENTATION). I will investigate a solution in order to cover your idea... but I don't like too much the script name (*-cron.sh) because is too specific and it can create confusion (if I call *cron-sh why it changed my systemd's timers?). This is my stupid opinion.

finally, I sent the same patches also to upstream.

Tomorrow I will prepare the new pr.

ciao

luigi

**Comment by comio** [comment]
@madmartin I tried to reduce the timers following your suggestion. I'm evaluating to squash refresh-cron.sh and refresh-timers.sh to a single file.

I will give my contribution to upstream asap.

ciao

luigi

**Comment by comio** [comment]
Hi @madmartin ,

I refreshed the patches here https://github.com/kdave/btrfsmaintenance/pull/35
I still don't have feedback, then my proposal is to use my fork (if the changes are ok for you) or import the patches into portage trree.

ciao

luigi

**Comment by mgorny** [comment]
Very well.

**Comment by madmartin** [comment]
@gentoo/proxy-maint 
This PR wants to implement enhancements that should be implemented upstream. I reject this.
Because I have no rights to do this can you please close this PR?

**Pull request closed without merging**
