### PR TITLE
x11-plugins/{wmSMPmon, wmMatrix, wmCalClock, wmapm, wmfortune, wmgrabimage}: EAPI6, use HTTPS, improve ebuild

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR updates a few DockApp ebuilds.
Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
@voyageur again no problem. :)
I've added new revisions now and bumped the ebuilds straight to EAPI7 and put them to ~
The existing ebuilds only got the HTTPS changes. Please let me know if you want me to squash the commits together (per package).

**Comment by mm1ke** [comment]
Damn, yes your're right.
While changing the PR in order to have newer revisions of the ebuilds i lost the changes to the patches. 
I actually tested each package, but didn't try after the change.
Gonna fix the patches tonight and let you know.
Thanks for testing

**Comment by mm1ke** [comment]
@voyageur Fixed the patches and rebased the PR. Should be good now :)

**Comment by voyageur** [comment]
Thanks, applied!

**Pull request closed without merging**
