### PR TITLE
net-misc/*: drop old

### PR DESCRIPTION
**Pull request by fkobi**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by jkroonza — APPROVED** [review]
For stuntman at least.

**Comment by jkroonza** [comment]
@fkobi I have no objection against the removals, I just noticed this is one commit though, if I'm not mistaken it should be one commit per package, so you will just need to split this up into three commits, and adjust the commit messages accordingly.

Thanks for your efforts.

**Review by jkroonza — APPROVED** [review]
looks good to me.

@thesamesam I think this can be merged.

**Comment by juippis** [comment]
I'll cherry-pick the stuntman removal, looks like other packages have been handled already.

**Pull request closed without merging**
