### PR TITLE
dev-qt: EAPI-8 bumps and KDE Qt5PatchCollection snapshots for qttools

### PR DESCRIPTION
**Pull request by a17r**
- EAPI-8 bump and KDE Qt5PatchCollection snapshots for QT5_MODULE=qttools
- Restore QT5_TARGET_SUBDIRS for QT5_MODULE=qttools, see also: https://github.com/gentoo/qt/pull/246
- Switch from ~PV to =QT5_PV* version dependencies for all revbumped ebuilds, see also https://github.com/gentoo/qt/pull/247

### CODE REVIEW

**Comment by Pesa** [comment]
is there a reason for EAPI bumping the (stable!) 5.15.2 ebuilds in-place? I think you need a pretty good reason for that.

**Comment by a17r** [comment]
> is there a reason for EAPI bumping the (stable!) 5.15.2 ebuilds in-place? I think you need a pretty good reason for that.

Overconfidence that nothing relevant in the (mostly only qt5-build) inherited eclasses has changed.

**Comment by Pesa** [comment]
I dunno, still seems against policy/established practice to me (e.g., ["This must be done even if you think you're just making a trivial fix"](https://devmanual.gentoo.org/keywording/index.html#keywording-on-upgrades)). And keeping EAPI 7 support in qt5-build.eclass has virtually zero maintenance cost. So my recommendation is: don't bother :)

That being said, I'm not vetoing the change, you've been the _de facto_ maintainer of qt5 for quite some time (and done a great job). But I won't ACK it either.

**Comment by Chiitoo** [comment]
Things seem to work for me so far, though I only tested the following so far:

```
dev-qt/designer
dev-qt/linguist-tools
dev-qt/qtcharts
dev-qt/qtchooser
dev-qt/qtconcurrent
dev-qt/qtcore
dev-qt/qtdbus
dev-qt/qtdeclarative
dev-qt/qtgraphicaleffects
dev-qt/qtgui
dev-qt/qtmultimedia
dev-qt/qtnetwork
dev-qt/qtopengl
dev-qt/qtprintsupport
dev-qt/qtquickcontrols
dev-qt/qtquickcontrols2
dev-qt/qtscript
dev-qt/qtsql
dev-qt/qtsvg
dev-qt/qttest
dev-qt/qtvirtualkeyboard
dev-qt/qtwayland
dev-qt/qtwebchannel
dev-qt/qtwebengine
dev-qt/qtwidgets
dev-qt/qtx11extras
dev-qt/qtxml
dev-qt/qtxmlpatterns
```

**Comment by Chiitoo** [comment]
Tested some more today, building and/or installing everything except for qtwebkit, and qt-docs.

Only issue so far that I've noticed (qt-docs):

```
[...]
unpack 5.15.2-0-202011130614qmake-documentation.7z: file format not recognized. Ignoring.
[...]
```

**Pull request merged**
