### PR TITLE
ROCm runtime ISA expansion; dev-util/hip AVX512 fix improvement

### PR DESCRIPTION
**Pull request by littlewu2508**
Commits are picked from https://github.com/gentoo/gentoo/pull/33400

Two ISA expansion commit enables `rocr-runtime` and `hip` runtime library to automatically treat all RDNA2 GPU as gfx1030, so only one GPU target needs to be built for all RDNA2 GPUs.

The other one is an improved version of https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=74964e47d7cb86d9cbb992f02e9de25a554727ac

### CODE REVIEW

**Comment by AngryLoki** [comment]
Hi @littlewu2508 ,

In this PR you remove hip-5.7.1-fix-unaligned-access.patch (nontemporalMemcpy -> memcpy replacement) with alternative solution (setting PARAMETERS_MIN_ALIGNMENT). 

However, just setting PARAMETERS_MIN_ALIGNMENT is not enough. It willv still crash in the same place in test in rocThrust, for example. A complete fix includes setting PARAMETERS_MIN_ALIGNMENT and changing alignment in KernelParameters as described in https://github.com/ROCm/clr/issues/18#issuecomment-1785948267 . 

Both versions of patch should solve crash issue. But on my gfx1036 I had extra test failure for BinarySearchTests.TestBinarySearchDevice in rocThrust, that's why I used `nontemporalMemcpy -> memcpy` approach.

**Comment by littlewu2508** [comment]
@AngryLoki Sorry I my AVX512 machine is still on the way, so I cannot reproduce the issue, so I was just applying https://github.com/gentoo/gentoo/commit/6648534eedd1a1a09f533b65650e5f9e71a62b2b#diff-29d328ef381c60ad2e9731756f2d3c0465678976b91ef2bb5d2b63f45e05b9e0 blindly.

So, it seems that there are 3 patches:

1. `hip-5.7.0-set-correct-alignement.patch` (probably) inspired by https://github.com/ROCm/clr/issues/18#issuecomment-1771155982
2. Your second patch at https://github.com/ROCm/clr/issues/18#issuecomment-1785948267
3.  `hip-5.7.1-fix-unaligned-access.patch` coming from https://github.com/ROCm/clr/pull/19, seems to be superseded by 1. and 2.

So do you mean I should apply both 1. and 2.?

And what about the rocThrust test suite failure at https://github.com/ROCm/clr/issues/18#issuecomment-1771155982? Do you have any updates?

**Comment by AngryLoki** [comment]
@littlewu2508 , https://github.com/gentoo/gentoo/blob/master/dev-util/hip/files/hip-5.7.1-fix-unaligned-access.patch already fully fixed the issue. 

Alternative "full fix" for crash is a combination of hip-5.7.0-set-correct-alignement.patch AND https://github.com/ROCm/clr/issues/18#issuecomment-1785948267 . Just join these 2 patches. Yes, in theory it is a "fix improvement", but it behaved _slightly worse_ on my environment (BinarySearchTests.TestBinarySearchDevice in rocThrust failed and that's all), so I did not include it.

> Do you have any updates?

Looks like fix was committed in https://github.com/ROCm/clr/commit/c4f773db0b4ccbbeed4e3d6c0f6bff299c2aa3f0 and https://github.com/ROCm/clr/commit/7868876db742fb4d44483892856a66d2993add03 . But they did not include these fixes into 6.0.0 release (it was released last week), probably due to internal cycles.

**Comment by littlewu2508** [comment]
Thank you for these information. So this PR should be closed now.

> but it behaved slightly worse on my environment (BinarySearchTests.TestBinarySearchDevice in rocThrust failed and that's all), so I did not include it

I'll try to reproduce the issue when I come to rocThrust :)

**Pull request closed without merging**
