### PR TITLE
net-im/slack-bin: new package

### PR DESCRIPTION
**Pull request by SpiderX**
Please confirm.
Gentoo bug: https://bugs.gentoo.org/show_bug.cgi?id=575786

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint @monsieurp

**Comment by monsieurp** [comment]
LGMT to me except the commit message which should be a lot more explanatory as to what slack is. See [1].

[1]: https://wiki.gentoo.org/wiki/Gentoo_Github#New_packages

**Comment by SpiderX** [comment]
Do I have to remake the commit and add more info about slack?

**Comment by eliasp** [comment]
> Do I have to remake the commit and add more info about slack?

Just:
- `git checkout your-local-branch-containing-your-slack-ebuild`
- `git commit --amend '-S'`
- Edit the commit msg to be [more descriptive](https://wiki.gentoo.org/wiki/Gentoo_Github#New_packages)
- `git push --force`

**Comment by SpiderX** [comment]
Thank you, eliasp!

**Pull request closed without merging**
