### PR TITLE
media-libs/libavif: add 1.0.4, update live ebuild

### PR DESCRIPTION
**Pull request by novomesk**

### CODE REVIEW

**Comment by arkamar** [comment]
Could you please make a version bump and live ebuild update in separate commits?

`qa-vdb libavif` tool from [`iwdevtools`](https://github.com/ionenwks/iwdevtools) detected this:
```
VDB: detected possibly incorrect RDEPEND (media-libs/libavif-1.0.4)
media-libs/libjpeg-turbo <
media-libs/libpng        <
sys-libs/zlib            <
```
could you look at it?

Moreover, live ebuild fails to configure for me:
```
 * Package:    media-libs/libavif-9999:0/9999
 * Repository: gentoo
 * USE:        abi_x86_64 amd64 aom elibc_glibc kernel_linux test
 * FEATURES:   network-sandbox preserve-libs sandbox test userpriv usersandbox
>>> Unpacking source...
[snip]
>>> Source unpacked in /var/tmp/portage/media-libs/libavif-9999/work
>>> Preparing source in /var/tmp/portage/media-libs/libavif-9999/work/libavif-9999 ...
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/media-libs/libavif-9999/work/libavif-9999"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/media-libs/libavif-9999/work/libavif-9999_build"
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/media-libs/libavif-9999/work/libavif-9999 ...
 * abi_x86_64.amd64: running multilib-minimal_abi_src_configure
 * Source directory (CMAKE_USE_DIR): "/var/tmp/portage/media-libs/libavif-9999/work/libavif-9999"
 * Build directory  (BUILD_DIR):     "/var/tmp/portage/media-libs/libavif-9999/work/libavif-9999_build-abi_x86_64.amd64"
cmake -C /var/tmp/portage/media-libs/libavif-9999/work/libavif-9999_build-abi_x86_64.amd64/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DAVIF_CODEC_AOM=SYSTEM -DAVIF_CODEC_DAV1D=OFF -DAVIF_CODEC_LIBGAV1=OFF -DAVIF_ZLIBPNG=SYSTEM -DAVIF_JPEG=SYSTEM -DAVIF_BUILD_GDK_PIXBUF=OFF -DAVIF_ENABLE_WERROR=OFF -DAVIF_CODEC_RAV1E=OFF -DAVIF_CODEC_SVT=OFF -DAVIF_BUILD_EXAMPLES=OFF -DAVIF_BUILD_APPS=OFF -DAVIF_BUILD_TESTS=ON -DAVIF_ENABLE_GTEST=OFF -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/media-libs/libavif-9999/work/libavif-9999_build-abi_x86_64.amd64/gentoo_toolchain.cmake /var/tmp/portage/media-libs/libavif-9999/work/libavif-9999
loading initial cache file /var/tmp/portage/media-libs/libavif-9999/work/libavif-9999_build-abi_x86_64.amd64/gentoo_common_config.cmake
-- The C compiler identification is GNU 14.0.1
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/x86_64-pc-linux-gnu-gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Checking for module 'libyuv'
--   Package 'libyuv', required by 'virtual:world', not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find libyuv (missing: LIBYUV_LIBRARY LIBYUV_LIBRARIES
  LIBYUV_INCLUDE_DIR) (found version "")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
  cmake/Modules/Findlibyuv.cmake:52 (find_package_handle_standard_args)
  CMakeLists.txt:188 (find_package)
  CMakeLists.txt:205 (check_avif_option)


-- Configuring incomplete, errors occurred!
 * ERROR: media-libs/libavif-9999::gentoo failed (configure phase):
 *   cmake failed
```

**Comment by novomesk** [comment]
I made few edits.

Live ebuild should work again, added `-DAVIF_LIBYUV=OFF` cmake option.

**Comment by Jamim** [comment]
_Hello @arkamar,_

It looks like @novomesk addressed all the issues.
I've compiled and verified `libavif` using the suggested  `libavif-9999.ebuild`.
It works fine for me.

Would you mind re-reviewing this PR?

_Thanks in advance!_

**Review by Jamim — APPROVED** [review]

**Comment by Jamim** [comment]
_Hello @mgorny,_
Would you mind reviewing this PR?
_Thanks in advance!_

**Comment by mgorny** [comment]
Sure. I'll test it and push if nothing fails.

**Pull request closed without merging**
