### PR TITLE
sci-libs/lapack: readd deprecated functions

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Closes: https://bugs.gentoo.org/702254
Package-Manager: Portage-2.3.89, Repoman-2.3.20
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
@cdluminate @heroxbd

**Comment by heroxbd** [comment]
LGTM

**Comment by vince-ice** [comment]
Please add the deprecated USE to virtual/lapack as well @Alessandro-Barbieri

**Comment by heroxbd** [comment]
> Please add the deprecated USE to virtual/lapack as well @Alessandro-Barbieri

Do other lapack implementations have the deprecated routines exposed?

**Comment by heroxbd** [comment]
Sorry, my memory confused https://github.com/gentoo/gentoo/pull/14783 with this one.   And I was not consistent on whether to introduce a USE flag for this.

**Comment by Alessandro-Barbieri** [comment]
@heroxbd my openblas has deprecated routines

**Comment by heroxbd** [comment]
> @heroxbd my openblas has deprecated routines
Thanks!

I think the solution of deprecated routines is temporary.  The introduction of it to lapack is just for compatibility with 1 or 2 pieces of outdated software.  Therefore I have no interest to carry them to other lapack implementations.

Feel free to correct me if I am wrong.

**Pull request closed without merging**
