### PR TITLE
dev-python/neovim-python-client: Bump to 0.1.13

### PR DESCRIPTION
**Pull request by hazelnusse**

### CODE REVIEW

**Comment by hazelnusse** [comment]
@monsieurp I've rebased this off the tip of master -- these failures I think are unrelated to my patch. Can you retrigger the build?

**Comment by hazelnusse** [comment]
@monsieurp Can this be merged?

**Comment by Tranquility** [comment]
The reason for this release is python 3.6 so we shouldn't add it without adding that.

**Comment by hazelnusse** [comment]
@Tranquility I added Python 3.6 and rebased off of the tip of master

**Pull request closed without merging**
