### PR TITLE
net-dns/ddclient: bump to version 3.9.0

### PR DESCRIPTION
**Pull request by ConiKost**
Closes: https://bugs.gentoo.org/665070
Package-Manager: Portage-2.3.48, Repoman-2.3.10

### CODE REVIEW

**Comment by titanofold** [comment]
Looks good to me! Thanks for working on this.

**Comment by SkeLLLa** [comment]
@ConiKost according to systemd script ddclient's executable should be in `/usr/sbin`, openrc - in `/usr/bin` directory. And actually binary is located in `/usr/bin`, so systemd script will not find it.

**Comment by ConiKost** [comment]
@SkeLLLa: Yeah, sorry for that. See https://bugs.gentoo.org/665150. PR is filled, needs only to be merged.

**Comment by SkeLLLa** [comment]
Great.

Also it seems that it can't create `ddclient.cache` file due to `/var/cache/ddclient` directory is missing. Probably it worth to create it during emerge install phase or in systemd/openrc before start.

**Comment by ConiKost** [comment]
Hm, but that's something, that would have happend with the old version too? I didn't made there any changes. But yes, a `keepdir` should help. OpenRC does create it, when missing.

**Comment by ConiKost** [comment]
> dclient[31763]: FATAL:    Cannot create file '/var/cache/ddclient/ddclient.cache'

Could you modify the unit and test, if this would do the trick?

```
PermissionsStartOnly=true
ExecStartPre=/bin/mkdir -p /run/ddclient /var/cache/ddclient
ExecStartPre=/bin/chown ddclient:ddclient /run/ddclient /var/cache/ddclient
```

**Comment by SkeLLLa** [comment]
@ConiKost I could try tomorrow and share the result.

**Comment by SkeLLLa** [comment]
@ConiKost the lines above fixed issue with missing directory.

**Pull request closed without merging**
