### PR TITLE
 sys-apps/hw-probe: New package

### PR DESCRIPTION
**Pull request by ConiKost**
sys-apps/hw-probe: New package
Closes: https://bugs.gentoo.org/669722
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by a17r** [comment]
There are privacy concerns over the information shared by default, head over to gentoo-user mailing list if you are not aware if it already.

**Comment by ConiKost** [comment]
Yes, I am aware of that discussion on the g-u-ml. Let's see, what happens on upstream, as the want to change a few things, as it looks..

**Comment by linuxhw** [comment]
Hi,

Please apply the [attached patch](https://github.com/gentoo/gentoo/files/2879967/merge-with-linuxhw.patch.tar.gz) from [my pull request](https://github.com/gentoo/gentoo/pull/11105):

* Add `arm` and `ppc` architectures
* Require `hdparm`, `mcelog`, `pmtools`, `util-linux`, `lm_sensors`, `libwww-perl` and `HTML-Parser`
* Do not require `systemd`, `cpuid` and `hplip`
* Fix `longdescription` in metadata

The ability to skip collecting of unwanted logs is already added in the master version of the tool. I'll prepare the release candidate for Gentoo soon.

We can change the default set of collected logs for Gentoo. E.g. disable collecting of `fstab` or `mount` by default (w/o the need to specify any additional flags). What do you think?

Thank you.

**Comment by ConiKost** [comment]
Hi!

> Please apply the [attached patch](https://github.com/gentoo/gentoo/files/2879967/merge-with-linuxhw.patch.tar.gz) from [my pull request](https://github.com/gentoo/gentoo/pull/11105):

Your patch is fine, so I've applied it. But I did some small changes like alphabetical order for arches and deps.

> The ability to skip collecting of unwanted logs is already added in the master version of the tool. I'll prepare the release candidate for Gentoo soon.

Sounds good, 1.5 release i guess?

> We can change the default set of collected logs for Gentoo. E.g. disable collecting of `fstab` or `mount` by default (w/o the need to specify any additional flags). What do you think?

Yeah, I think this is a good idea! Better let the use decide, if he want's more.

**Comment by linuxhw** [comment]
> Hi!
> 
> > Please apply the [attached patch](https://github.com/gentoo/gentoo/files/2879967/merge-with-linuxhw.patch.tar.gz) from [my pull request](https://github.com/gentoo/gentoo/pull/11105):
> 
> Your patch is fine, so I've applied it. But I did some small changes like alphabetical order for arches and deps and stable arches are not allowed ;-).
> 
> > The ability to skip collecting of unwanted logs is already added in the master version of the tool. I'll prepare the release candidate for Gentoo soon.
> 
> Sounds good, 1.5 release i guess?
> 
> > We can change the default set of collected logs for Gentoo. E.g. disable collecting of `fstab` or `mount` by default (w/o the need to specify any additional flags). What do you think?
> 
> Yeah, I think this is a good idea! Better let the use decide, if he want's more.

Yes, I'm preparing the 1.5 release currently. Already removed `fstab` and `mount` from the default log level (i.e. `sudo hw-probe -all -upload` w/o additional options).

I'll submit a new patch in this thread upgrading to 1.5 when it will be ready and tested enough.

Thank you.

**Comment by ConiKost** [comment]
Any ETA on 1.5 release?

**Comment by lvc** [comment]
> Any ETA on 1.5 release?

Hope this winter.

Temp solution is (secure enough): https://flathub.org/apps/details/org.linux_hardware.hw-probe

**Comment by ConiKost** [comment]
It's near end of year :-) What the status of version 1.5?

**Comment by linuxhw** [comment]
> It's near end of year :-) What the status of version 1.5?

OK, let's intensively test and release it.

Need to test latest master on:

1. Latest popular Linux distribution versions (Gentoo, Ubuntu, Fedora, Debian, Manjaro, openSUSE, ROSA, Mageia, CentOS, Arch Linux, Puppy)
2. Previous Linux distribution versions with `hwinfo` available (https://pkgs.org/download/hwinfo)
3. Test with Perl 5.8 and Perl 5.30
4. Test with MegaRAID

In all cases the probe link should be returned.

Install instructions: https://github.com/linuxhw/hw-probe/blob/master/INSTALL.md (+ `replace /usr/bin/hw-probe` by master version).

**Comment by linuxhw** [comment]
@ConiKost 

Do you have a MegaRAID somewhere to test master hw-probe on it?

Thanks.

**Comment by ConiKost** [comment]
@linuxhw Nope. Dont' have any MegaRAID hardware. I can only offer Adaptec RAID (arcconf).

**Comment by linuxhw** [comment]
@ConiKost 

> @linuxhw Nope. Don't have any MegaRAID hardware. I can only offer Adaptec RAID (arcconf).

Could you please install `arcconf` utility from http://download.adaptec.com/raid/storage_manager/arcconf_v2_06_23167.zip and make a probe of it?

Thanks!

**Comment by ConiKost** [comment]
Yep, will give a test. Please keep in mind, there is also a newer version 3.x of arcconf.

**Comment by linuxhw** [comment]
@ConiKost 

> Yep, will give a test. Please keep in mind, there is also a newer version 3.x of arcconf.

Could you please also check if `smartctl -a -d "aacraid,0,0,1" /dev/sda` returns better output than `arcconf GETSMARTSTATS 1 TABULAR`?

Thanks.

**Comment by ConiKost** [comment]
@linuxhw arcconf works just fine. Tested 2.06 and 3.01. Both work fine. Here is an example with latest git checkout: https://linux-hardware.org/?probe=a893a616e4

**Comment by linuxhw** [comment]
Let's schedule the release for January 15. I need to update docs and rebuild all app images.

**Comment by ConiKost** [comment]
Great. When it's released, I will update the eBuild. There is some work to do, as most of the dependencies in RDEPEND are optional and will be moved into `optfeature`.

**Comment by linuxhw** [comment]
@ConiKost 

Released: https://github.com/linuxhw/hw-probe/releases/tag/1.5

Thanks a lot for your help.

**Comment by linuxhw** [comment]
@ConiKost 

When to expect the update of Gentoo package?

Thanks.

**Comment by ConiKost** [comment]
Hi!
Allright, I've locally prepared something. So this should be soon the case. I've a question.

Is the list of required and optional dependecies up to date?

**Comment by linuxhw** [comment]
Hi,

Current list of optional dependencies marked by `?` in https://github.com/gentoo/gentoo/blob/27e5602992be8be1cd9780791d2e970c26d0de99/sys-apps/hw-probe/hw-probe-1.4.ebuild looks good.

Thank you.

**Pull request closed without merging**
