### PR TITLE
media-video/mpv: fix CUDA HW decoding in 9999

### PR DESCRIPTION
**Pull request by Coacher**
@kkkrackpot, if you could test this, it would be great. It builds at least.

### CODE REVIEW

**Comment by Coacher** [comment]
@aballier, indeed. Thank you. I'll rework this PR then.
Why the heck `emerge -s codec` doesn't show it though >:(

**Comment by Coacher** [comment]
Ok, should be good to go now. @aballier, please re-review.

**Comment by Coacher** [comment]
Thank you very much, @kkkrackpot

**Comment by mgorny** [comment]
Thanks!

**Comment by Coacher** [comment]
Thank you, @mgorny.

**Pull request closed without merging**
