### PR TITLE
app-text/bact: fix cpp14 compilation errors; bug #594312

### PR DESCRIPTION
**Pull request by kolodziej**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@kolodziej are you working on bumping the ebuild to `EAPI=6`?

**Comment by kolodziej** [comment]
Yes, but I'll commit it in separate PR.

**Comment by SoapGentoo** [comment]
`dohtml` is deprecated in `EAPI=6`. I recommend putting the files into `HTML_DOCS` and then using `einstalldocs`, which also means you can get rid of the `dodoc`, as the files are part of the default set.

**Comment by kolodziej** [comment]
Ok, thanks

**Pull request closed without merging**
