### PR TITLE
dev-lang/execline, dev-libs/skalibs, */s6*: version bumps

### PR DESCRIPTION
**Pull request by smaeul**
Here are some version bumps following the recent release (see https://www.mail-archive.com/skaware@list.skarnet.org/msg00890.html).

As there have been no bugs filed against the previous version of these packages, in tree for multiple months, mark them as stable (except s6-networking, which needs libressl).

Remove everything older than the stabilized versions.

I also added some unstable keywords on arm to resolve https://bugs.gentoo.org/show_bug.cgi?id=609728

### CODE REVIEW

**Comment by atlaua** [comment]
Looks good to me; thanks! I'm not sure about the amd64/x86 stable
keywords, though; let's see what @williamh thinks about those.

**Comment by williamh** [comment]
The version bumps are fine, but that should be the only thing in this pull request. I will be working on extracting them today.

**Comment by williamh** [comment]
The version bumps are done. I will add the arm arch to the bug and update the versions for them to keyword. The stabilizations and removals should be done separately as well. I'll look into those. Thanks for the p/r.

**Comment by smaeul** [comment]
Ok, thank you. I'll keep them separate in the future.

**Pull request closed without merging**
