### PR TITLE
Destabilize Haskell

### PR DESCRIPTION
**Pull request by mattst88**
Haskell is very difficult to package, and stabilizations have not happened in nearly a year. Let's acknowledge reality and drop old stable keywords.

### CODE REVIEW

**Comment by mattst88** [comment]
Might make sense to just squash these last three commits together:

- dev-haskell/*: Drop stable keywords
- dev-lang/ghc: Drop stable keywords
- app-admin/haskell-updater: Drop stable keywords

**Comment by mattst88** [comment]
cc: @hololeap

**Comment by hololeap** [comment]
@thesamesam had been pushing for us to stabilize some of the haskell packages in `::gentoo`, saying that it would help reduce confusion for end users.

Are you proposing that we destabilize these packages, or are you also proposing _that no haskell packages get stabilized in the future?_ Does more need to be done to improve the quality of the packages before you think they can be marked stable, and if so, can you specify what needs to improve?

I don't quite understand the motivation to do this.

**Comment by hololeap** [comment]
Also, just so you know, I have been planning opening PRs to remove these old versions, add latest versions that are currently in `::haskell`, and then potentially ask to stabilize the latest versions that are currently in `::gentoo`. The biggest issue has been that I've been the only one who has been working on any of this and I don't have unlimited time to do so.

**Comment by mattst88** [comment]
> @thesamesam had been pushing for us to stabilize some of the haskell packages in ::gentoo, saying that it would help reduce confusion for end users.

I've also asked (asked you, I think) to stabilize newer `dev-haskell/*` versions as well, since noticing the number of packages that haven't been stabilized despite being in tree for 300+ days. I don't have access to my IRC logs at the moment, but I think I've asked at least twice in the past few months.

> Are you proposing that we destabilize these packages, or are you also proposing that no haskell packages get stabilized in the future? Does more need to be done to improve the quality of the packages before you think they can be marked stable, and if so, can you specify what needs to improve?
> 
> I don't quite understand the motivation to do this.

Sorry for not being clear about the motivation. Let me try to clarify.

I am not proposing that haskell packages are never stabilized in the future.

I'm only suggesting that if we're not going to stabilize new versions within 10 months of them being in tree, then we probably shouldn't have stable versions at all.

> Also, just so you know, I have been planning opening PRs to remove these old versions, add latest versions that are currently in ::haskell, and then potentially ask to stabilize the latest versions that are currently in ::gentoo. The biggest issue has been that I've been the only one who has been working on any of this and I don't have unlimited time to do so.

I totally understand. I maintained all of GNOME for years essentially by myself. It's a huge amount of work, and I'm not trying to add to that.

In fact, I'm trying to do the opposite: free you (or any other haskell contributors) from having to worry about stabilizations (at least until something changes and you feel like the state of haskell packages in Gentoo is in a healthy state and you're ready to take on that additional work). Sorry for not making this clear from the outset.

By dropping the stable keywords, you'll be free to drop the old versions whenever you please, hopefully making it easier to bring new versions over from the `::haskell` repo.

**Comment by hololeap** [comment]
Thank you for explaining. This all seems very reasonable. I don't have any problem with destabilizing these versions as long as there remains an avenue to stabilize haskell packages in the future.

**Pull request merged**
