### PR TITLE
dev-libs/intel-neo, dev-libs/opencl-clang, dev-util/intel-graphics-compiler, and dev-util/spirv-llvm-translator: Version Bumps (can now be build with llvm 11)

### PR DESCRIPTION
**Pull request by Titaniumtown**
Note: This is my first PR to this project!

This PR updates: dev-libs/intel-neo, dev-libs/opencl-clang, dev-util/intel-graphics-compiler, and dev-util/spirv-llvm-translator
Currently you can't install any of those packages while having llvm/clang 11.0.0 installed, this PR updates those packages so it is possible to build. Also, these ebuilds come from my own Gentoo overlay.

Hope this PR can be accepted!

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
While the ebuilds look rather good, a sign-off is required from you to each of your commits. Please see https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

And because you'll have to amend your commits, you could edit your git commit summaries to match our requirements, https://www.gentoo.org/glep/glep-0066.html#commit-messages (just check the git log on repo really)

**Comment by thesamesam** [comment]
@Titaniumtown Hey! Can you have a look at juippis' comment above?

We also need to address the CI issue.

**Comment by Titaniumtown** [comment]
@thesamesam Sorry, I have been busy lately. I'll try to do it when I get the time.

**Comment by ConiKost** [comment]
It seems, that all versions of this PR are already in tree, so closing here.

**Pull request closed without merging**
