### PR TITLE
media-libs/libechonest: fix 2 bugs

### PR DESCRIPTION
**Pull request by Fat-Zer**
@gentoo/proxy-maint
@gentoo/sound

### CODE REVIEW

**Comment by idella** [comment]
Fat-Zer first thanks for taking these on. Before I actually look at the ebuild of  media-libs/libechonestm
firstly the commit msg.
`media-libs/libechonest: fix bug #581844 : fix bug #581844` 
firstly it needs a version cited that was edited which goes in line one.
Line 3 onwards gives a brief description of the fix. Within this brief description, you might say

```
fixes

Gentoo-bug: # 581844
```
Don't be put off. A great % of the comments in these pull res go into tidying commit messages to a good state before addition to the tree.  Fix that then we can continue.

Thanks

**Comment by idella** [comment]
Fat-Zer re libechonest-9999.ebuild it's a live ebuild same make it a live ebuild

[[ ${PV} == *9999* ]]  is generally used fir an ebuild that doubles as a versioned ebuild.  This is a live ebuild so these entires are un-needed and taking up space

RESTRICT="test" # Networking required

If you can skip or take out the test that require the network, you can run the remainder of the suite. This is preferable.

**Comment by Fat-Zer** [comment]
> [[ ${PV} == 9999 ]] is generally used fir an ebuild that doubles as a versioned ebuild. This is a live ebuild so these entires are un-needed and taking up space

This will ease life with further releases, so I'd prefer to keep those lines, but  if you insist I'll remove them...
Also note that upstream is not active nowadays and I'm not sure if the live ebuild really needed...

>If you can skip or take out the test that require the network, you can run the remainder of the suite. This is preferable.

It seems all the tests require the internet access...

**Comment by idella** [comment]
well the live ebuild runtests and installs ok. 
I can get a second opinion on those lines but I do not follow your logic. A live is a live so why set it for a condition for not being a live.

**Comment by Fat-Zer** [comment]
>I can get a second opinion on those lines but I do not follow your logic. A live is a live so why set it for a condition for not being a live. 

The logic is next: the live ebuilds are maintained all the times (at least more often than the release ones) and according to changes on the upstream. If the maintenance was done well, the only thing that should be done on release is to copy the live ebuild.

**Comment by idella** [comment]
lemme try once more     ${PV} of libechonest-9999.ebuild will always be -9999.
the  ${PV} of libechonest-9999.ebuild can never be that of any release tagged versioned ebuild.

**Comment by idella** [comment]
I am not content with this check if live. Someone else can support this patch in this state

**Comment by wraeth** [comment]
I am having a look at this (as time allows), however the first thing I will suggest is that instead of having multiple `[[ ${PV} == *9999* ]] && ...` statements, these could be put into a single `if` block (with the alternatives in an `else`, improving readability. You could use `${PORTDIR}/sys-kernel/genkernel/genkernel-3.4.52.4-r1.ebuild` as an example of this.

Otherwise, I am having a look and running some tests and will let you know if I have any further observations.

Thanks!

**Comment by wraeth** [comment]
I've had more of a look and there are a couple of additional points:

- `REQUIRED_USE` is missing from the live ebuild, causing it to try (and fail) `USE="-qt4 -qt5"`
- The `Gentoo bug` tag in both commit messages should not have a space: `Gentoo-bug: 123456`

Can you have a look at these two (as well as the multiple `if` statements for the live ebuild) and re-push? If you have any questions, just let me know.

Cheers.

**Comment by Fat-Zer** [comment]
>I am having a look at this (as time allows), however the first thing I will suggest is that instead of having multiple [[ ${PV} == *9999* ]] && ... statements, these could be put into a single if block

ok, I was afraid this may break some crappy parsers...

> REQUIRED_USE is missing from the live ebuild, causing it to try (and fail) USE="-qt4 -qt5" 

thanks, dunno how I could missed that myself...

>The Gentoo bug tag in both commit messages should not have a space: Gentoo-bug: 123456 

fixed

**Comment by wraeth** [comment]
Okay, so the `REQUIRED_USE` issue has been fixed in the live ebuild, and the commit messages look good; however it seems a dependency has been dropped from 2.3.1-r1 - specifically `dev-qt/qtxml:5`.

**Comment by Fat-Zer** [comment]
just updated the latest release one to match the live...
I wasn't sure what subSLOT should I use (release/release+0.1/none), I decided to match it to release's.

**Pull request closed without merging**
