### PR TITLE
dev-java/tomcat-{el,jsp,servlet}-api: package separation

### PR DESCRIPTION
**Pull request by vaukai**
setting to artifactId "tomcat-jsp-api" because this depends on the two other packages in this bundle and an ebuild can have only one MAVEN_ID

Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
well, i was thinking about splitting the package to three packages, one for each jar, but i still didn't get to it, and not sure when i would get to it. if you would like to split the package, feel free to create a pr.

**Comment by vaukai** [comment]
@fordfrog for your kind attention - if this is OK we could proceed with the lower versions

**Comment by fordfrog** [comment]
> @fordfrog for your kind attention - if this is OK we could proceed with the lower versions

thank you. i'll probably get to it during the weekend, busy week again :-|

**Comment by fordfrog** [comment]
@vaukai the ebuilds look good to me. i was just thinking about how to proceed with it, and for me it would be the easiest to do it along with tomcat bumps so that i don't have to care about handling the "double implementation" situation. currently, tomcat `9.0.68` has been released and i did not bump it yet in gentoo. could you please prepare the ebuilds for this version on tomcat along in this bug? i'd pick them and test it on this tomcat version bump.

**Pull request closed without merging**
