### PR TITLE
app-portage/g-cpan: version bump (to 0.16.9)

### PR DESCRIPTION
**Pull request by bor**
move to use github tag generated archive instead of uploaded release file,
 to simplify release process
also remove extra tabs

### CODE REVIEW

**Comment by bor** [comment]
casting @gentoo-perl

**Comment by bor** [comment]
ChangeLog

> 11 Jul 2016; Sergiy Borodych <Sergiy.Borodych@gmail.com> g-cpan-0.16.8:
>    Fix bug #542180 (github#23), some POD fixes

**Comment by bor** [comment]
@gentoo-repo-qa-bot

**Comment by bor** [comment]
Please hold on.
Will be new version with one more fix today.

**Comment by bor** [comment]
@monsieurp please go ahead

**Comment by monsieurp** [comment]
:+1:

**Pull request closed without merging**
