### PR TITLE
dev-java/jackcess: bump to 4.0.0 | dev-java/poi: new package | dev-java/sparsebitset: new package

### PR DESCRIPTION
**Pull request by vaukai**
Before I start excluding tests (this is from jackcess-4.0.0):
```
Time: 38.611
There were 3 failures:
1) testWriteAndReadDate(com.healthmarketscience.jackcess.DatabaseTest)
java.lang.AssertionError: Expected -2208988800000 (Mon Jan 01 00:00:00 CET 1900), found -2208992400000 (Mon Jan 01 00:00:00 CET 1900)
        at com.healthmarketscience.jackcess.TestUtil.assertSameDate(TestUtil.java:397)
        at com.healthmarketscience.jackcess.DatabaseTest.testWriteAndReadDate(DatabaseTest.java:681)
2) testAncientDates(com.healthmarketscience.jackcess.DatabaseTest)
junit.framework.AssertionFailedError: expected:<[1582-10-15, 1582-10-14, 1492-01-10, 1392-01-10]> but was:<[1582-10-14, 1582-10-13, 1492-01-09, 1392-01-09]>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:86)
        at junit.framework.TestCase.assertEquals(TestCase.java:246)
        at com.healthmarketscience.jackcess.DatabaseTest.testAncientDates(DatabaseTest.java:733)
3) initializationError(com.healthmarketscience.jackcess.TestUtil)
org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.healthmarketscience.jackcess.TestUtil':
  1. Test class should have exactly one public constructor
  2. No runnable methods
        at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
        at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
        at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
        at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
        at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
        at org.junit.runner.Computer.getRunner(Computer.java:50)
        at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
        at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
        at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
        at org.junit.runners.Suite.<init>(Suite.java:81)
        at org.junit.runner.Computer$2.<init>(Computer.java:33)
        at org.junit.runner.Computer.getSuite(Computer.java:28)
        at org.junit.runner.Request.classes(Request.java:77)
        at org.junit.runner.JUnitCommandLineParseResult.createRequest(JUnitCommandLineParseResult.java:116)
        at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
        at org.junit.runner.JUnitCore.main(JUnitCore.java:36)

FAILURES!!!
Tests run: 189,  Failures: 3
```

### CODE REVIEW

**Comment by fordfrog** [comment]
> Before I start excluding tests (this is from jackcess-4.0.0):
> 
> ```
> Time: 38.611
> There were 3 failures:
> 1) testWriteAndReadDate(com.healthmarketscience.jackcess.DatabaseTest)
> java.lang.AssertionError: Expected -2208988800000 (Mon Jan 01 00:00:00 CET 1900), found -2208992400000 (Mon Jan 01 00:00:00 CET 1900)
>         at com.healthmarketscience.jackcess.TestUtil.assertSameDate(TestUtil.java:397)
>         at com.healthmarketscience.jackcess.DatabaseTest.testWriteAndReadDate(DatabaseTest.java:681)
> 2) testAncientDates(com.healthmarketscience.jackcess.DatabaseTest)
> junit.framework.AssertionFailedError: expected:<[1582-10-15, 1582-10-14, 1492-01-10, 1392-01-10]> but was:<[1582-10-14, 1582-10-13, 1492-01-09, 1392-01-09]>
>         at junit.framework.Assert.fail(Assert.java:57)
>         at junit.framework.Assert.failNotEquals(Assert.java:329)
>         at junit.framework.Assert.assertEquals(Assert.java:78)
>         at junit.framework.Assert.assertEquals(Assert.java:86)
>         at junit.framework.TestCase.assertEquals(TestCase.java:246)
>         at com.healthmarketscience.jackcess.DatabaseTest.testAncientDates(DatabaseTest.java:733)
> 3) initializationError(com.healthmarketscience.jackcess.TestUtil)
> org.junit.runners.model.InvalidTestClassError: Invalid test class 'com.healthmarketscience.jackcess.TestUtil':
>   1. Test class should have exactly one public constructor
>   2. No runnable methods
>         at org.junit.runners.ParentRunner.validate(ParentRunner.java:525)
>         at org.junit.runners.ParentRunner.<init>(ParentRunner.java:102)
>         at org.junit.runners.BlockJUnit4ClassRunner.<init>(BlockJUnit4ClassRunner.java:84)
>         at org.junit.runners.JUnit4.<init>(JUnit4.java:23)
>         at org.junit.internal.builders.JUnit4Builder.runnerForClass(JUnit4Builder.java:10)
>         at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
>         at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:37)
>         at org.junit.runner.Computer.getRunner(Computer.java:50)
>         at org.junit.runner.Computer$1.runnerForClass(Computer.java:31)
>         at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:70)
>         at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:125)
>         at org.junit.runners.model.RunnerBuilder.runners(RunnerBuilder.java:111)
>         at org.junit.runners.Suite.<init>(Suite.java:81)
>         at org.junit.runner.Computer$2.<init>(Computer.java:33)
>         at org.junit.runner.Computer.getSuite(Computer.java:28)
>         at org.junit.runner.Request.classes(Request.java:77)
>         at org.junit.runner.JUnitCommandLineParseResult.createRequest(JUnitCommandLineParseResult.java:116)
>         at org.junit.runner.JUnitCore.runMain(JUnitCore.java:77)
>         at org.junit.runner.JUnitCore.main(JUnitCore.java:36)
> 
> FAILURES!!!
> Tests run: 189,  Failures: 3
> ```

cool! wrt the tests, 1) and 2) is imo issue with timezone, for the tests it should be probably set to UTC/GMT. you can try to run tests from `src_test` using `TZ=UTC java-pkg-simple_src_test` to see whether that helps. 3) - it's not a test class, can be excluded.

also, i merged the maven id commits, you can rebase if you want.

**Comment by vaukai** [comment]
> you can try to run tests from `src_test` using `TZ=UTC java-pkg-simple_src_test` to see whether that helps. 3) - it's not a test class, can be excluded.

One excluded, but `TZ=UTC` does not help:  [build.log.gz](https://github.com/gentoo/gentoo/files/6338271/build.log.gz)

**Comment by fordfrog** [comment]
i will have a look at it tomorrow, i will either try to push the timezone somehow for the tests or i might tweak the test sources to respect timezone.

**Comment by fordfrog** [comment]
@vaukai well done, thanks a lot! i did some minor changes in the ebuilds, see d472cb651c1e61ae9e0ceca2a7f123b3c55ff2e0 and 868880a152daceb5e18039231631cdb71d5e9c3b

**Pull request closed without merging**
