### PR TITLE
media-libs/openexr slot 3 cleanup

### PR DESCRIPTION
**Pull request by waebbl**
Cleanup old and vulnerable slot 3 related versions of OpenEXR.
Cleanup package versions which still use slot 3.

**media-libs/openexr:** drop 3.1.{2,3,4}

Bug: https://bugs.gentoo.org/817431
Bug: https://bugs.gentoo.org/820674
Bug: https://bugs.gentoo.org/830384
Bug: https://bugs.gentoo.org/833158

**media-libs/openimageio:** drop 2.3.11.0{,-r2}

No consumers of these versions explicitly.
2.3.11.0-r2 depends on openexr slot 3 and is missing a patch file.

**kde-frameworks/kimageformats:** drop 5.90.0

Depends on slot 3 of openexr.
There's a stable -r1 in tree, which uses unslotted openexr.

Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by waebbl** [comment]
Wasn't sure if I can close bugs #820674 (tracker) and #833158 (unslotting) with this PR.
If so, just tell me and I can change the tag.

**Comment by ajakk** [comment]
soap/asturm: please ack for touched sci@/kde@ packages

**Comment by a17r** [comment]
Already ACKed in bug.

**Review by thesamesam — APPROVED** [review]

**Comment by a17r** [comment]
Fixed in commit 5a1d9ccaaa866fd0a831653dc92588fc59be0085, thx.

**Pull request closed without merging**
