### PR TITLE
profiles: unmask app-admin/collectd[collectd_plugins_mqtt] for arm

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. Could you attach a build log as a proof that collectd does compile on the arm platform?

**Comment by l29ah** [comment]
On Sun, Apr 09, 2017 at 06:58:48AM -0700, monsieurp wrote:
> Thanks for the PR. Could you attach a build log as a proof that collectd does compile on the arm platform?

I'd prefer not to as my arm is quite weak. Anyways the pull request ~'ing collectd for arm was already accepted ages ago :3

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by monsieurp** [comment]
Sorry I meant to write "this collectd plugin" not just collectd. I edited my answer in the meantime.

**Comment by l29ah** [comment]
On Sun, Apr 09, 2017 at 07:20:52AM -0700, monsieurp wrote:
> Sorry I meant to write "this collectd plugin" not just collectd. I edited my answer in the meantime.

http://bpaste.net/show/9d312a04d72b

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Pull request closed without merging**
