### PR TITLE
dev-go/delve: bump version to 1.3.0

### PR DESCRIPTION
**Pull request by g4s8**
Bug: https://bugs.gentoo.org/675900
Package-Manager: Portage-2.3.76, Repoman-2.3.16
Signed-off-by: Kirill Che <g4s8.public@gmail.com>

### CODE REVIEW

**Comment by juippis** [comment]
Thanks for showing interest in this package! Could you see if `go-module.eclass` can be used to install this?

**Comment by g4s8** [comment]
@juippis thanks. I checked it with `go-module.eclass` and it works. Please see new commit.

**Comment by juippis** [comment]
Oh and sorry I failed to mention, but you should check the correct LICENSE field with this ebuild. I think the bundled deps need to be included. Theres a tool to check it, 
https://packages.gentoo.org/packages/dev-go/go-license-detector

**Comment by g4s8** [comment]
@jubalh sure, I checked licenses from `go.mod` with this tool and added to `LICENSE` list. But I faced one issue: some packages has `BSD-3-Clause` license, but the're no such license in `/usr/portage/licenses/`, is it OK to use `BSD-4` for that?
```bash
$ find /usr/portage/licenses/ -iname '*bsd*'
/usr/portage/licenses/Clear-BSD
/usr/portage/licenses/BSD-4
/usr/portage/licenses/Ruby-BSD
/usr/portage/licenses/UCAR-BSD
/usr/portage/licenses/BSD-2
/usr/portage/licenses/BSD-1
/usr/portage/licenses/BSD
/usr/portage/licenses/BSD-with-attribution
```

**Comment by jubalh** [comment]
@g4s8 wrong mention probably? :-)

**Comment by g4s8** [comment]
@jubalh yes, sorry ;) @juippis please see https://github.com/gentoo/gentoo/pull/13127#issuecomment-539038263

**Pull request closed without merging**
