### PR TITLE
www-servers/nginx-unit: Bump to version 1.17.0

### PR DESCRIPTION
**Pull request by rseichter**
Remove obsolete ebuilds, bump to version 1.17.0. The upstream change log is available [here](http://unit.nginx.org/CHANGES.txt).

### CODE REVIEW

**Comment by rseichter** [comment]
Really? Last time I made a change to net-mail/automx2, I was told to use `git mv` instead of remove/add operations.

**Comment by juippis** [comment]
If f9bf82da2b70f7943f649ef80c18ff089fabe882 is the change, that's acceptable. It's one logical action with a small update. Now you introduce a new version, a new ebuild file. Then you remove old files. That is 2 separate actions and should use 2 separate commits.

**Comment by rseichter** [comment]
Sorry, I don't see the problem. I have removed obsolete ebuilds (all unstable <= 0.15) in one commit, and renamed one ebuild file in a second commit (0.16 to 0.17). GitHub is for some reason representing this as a rename from 0.15, which is *not* what I did.

**Comment by juippis** [comment]
Don't rename, use `cp` then add the new file on its own commit. Renaming while bumping to a new version counts as two actions.

**Comment by rseichter** [comment]
I have changed the order of commits, but GitHub still represents this in the wrong way although my commits are correct.

**Pull request closed without merging**
