### PR TITLE
dev-lang/yasm: add ~ppc64 keyword

### PR DESCRIPTION
**Pull request by djames1**

### CODE REVIEW

**Comment by floppym** [comment]
Why is this wanted/needed? Are you trying to cross-compile some assembly code?

**Comment by djames1** [comment]
@floppym My desktop is an IBM POWER9 workstation. I have been using yasm for cross compilation.

**Comment by floppym** [comment]
Please also update yasm-9999.ebuild.

**Comment by djames1** [comment]
@floppym Updated yasm-9999.ebuild as well

**Pull request closed without merging**
