### PR TITLE
x11-drivers/xf86-video-intel: fix erroneous date-based filename

### PR DESCRIPTION
**Pull request by lkraav**
There's no `010` day number

### CODE REVIEW

**Comment by lkraav** [comment]
Oops, updated `Manifest`

**Comment by monsieurp** [comment]
@gentoo/x11

**Comment by monsieurp** [comment]
It looks fairly trivial. Lemme merge it.

**Comment by lkraav** [comment]
I saw this was already bumped by another member. This PR should be closed.

**Comment by monsieurp** [comment]
Yep. 30d8de5a5e1494522d53c7aa340d419f1a5b92f6 took care of it. Thanks anyway!

**Pull request closed without merging**
