### PR TITLE
games-util/lutris: Version bump. Updated copyright year.

### PR DESCRIPTION
**Pull request by chritting**
PYTHON_COMPAT=( python3_{4,5,6} ) differs from the bug report as {4,5,6,7} presented errors, so reverted to {4,5,6}, which it was initially.

Thank you.
https://bugs.gentoo.org/675458

### CODE REVIEW

**Comment by a17r** [comment]
https://github.com/gentoo/gentoo/pull/10533
https://github.com/gentoo/gentoo/pull/10749

Does your PR add anything over those existing?

**Comment by chritting** [comment]
Yes, it supports and likely will support the 0.5.0 version when it gets released in one to two weeks.

**Comment by chritting** [comment]
commit 8a9da5c includes my signing off. 
https://github.com/gentoo/gentoo/commit/8a9da5c1b041402e7386ba140eb5549354a05f84

**Comment by nado** [comment]
@chritting: https://github.com/gentoo/gentoo/pull/10749 already supports 0.5 and adds broader changes/support.
You also hardcoded the beta string which is part of the version string normally.
Would you consider helping reviewing pr 10749 instead?

**Comment by chritting** [comment]
@nado what's the status on the other PR? I haven't tried the other ebuild, but if the latest Lutris version is out of the beta period now - with both v0.5.0.1 and v0.5.0 released - can we please update either ebuild accordingly? If @hanetzer has been away should we adjust this ebuild to reflect 0.5.0.1 or should I attempt to improve #10749 instead?

**Comment by nado** [comment]
Well, IMO, hanetzer's PR is still more complete opposed to your single ebuild update, even if it needs to be refreshed. Also, hanetzer's not away, just busy fwics ;)  Maybe ping him on irc if needed?

**Comment by hanetzer** [comment]
@nado was half-away; I messed up in repartitioning my gentoo install and basically
nuked it, so I've been doing reinstall and such, getting back to a point I can actually
'work' again. Don't worry, it was just the system itself, all my personal files (including
work done here) survived.

**Comment by a17r** [comment]
Closing this PR in favor of https://github.com/gentoo/gentoo/pull/10749 to avoid further confusion or duplicate work.

**Pull request closed without merging**
