### PR TITLE
media-gfx/iscan: Add missing use flag dependencies

### PR DESCRIPTION
**Pull request by gringus**
Closes: https://bugs.gentoo.org/737298
Signed-off-by: Marcin Deranek <marcin.deranek@slonko.net>

### CODE REVIEW

**Comment by thesamesam** [comment]
I suspect you need to add some USE flags for virtual/imagemagick-tools (and add it as a test dep), given that is the package whicch provides 'convert'?

```
convert: no decode delegate for this image format `TIF' @ error/constitute.c/ReadImage/562convert: no decode delegate for this image format `TIF' @ error/constitute.c/ReadImage/562.
convert: no images defined `data/left-bottom.png' @ error/convert.c/ConvertImageCommand/3285.
.
convert: no images defined `data/top-left.png' @ error/convert.c/ConvertImageCommand/3285.
make[4]: *** [Makefile:1420: data/top-left.png] Error 1
make[4]: *** Waiting for unfinished jobs....
make[4]: *** [Makefile:1420: data/left-bottom.png] Error 1
```

[build.log](https://github.com/gentoo/gentoo/files/5177440/build.log)

**Comment by gringus** [comment]
Yes, you are right. Just added and tested.

**Comment by thesamesam** [comment]
Thanks!

**Comment by thesamesam** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=d7feb60a9b28e2e88a4a0e5e2672d99c72fe7c06

**Pull request closed without merging**
