### PR TITLE
sys-libs/db: port to EAPI 7

### PR DESCRIPTION
**Pull request by hanetzer**
There are some problems with this one I can't quite solve myself. The upstream
patches seem to be formatted to be -p0, which means they can't be just slapped
into the PATCHES array. One suggestion would be to mirror them in a devspace,
modified to be -p1 applicable (and preferably converted to a unified diff format,
as the context diff used by upstream is 1. very large relatively speaking to a unified
diff and 2. difficult to easily assess visually, as compared to unified diffs).

Porting to EAPI 7 because with an otherwise stock crossdev toolchain this cannot
be emerged because it cannot find autotools, with the following error:

```
* Running eautoreconf in '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/sys-libs/db-6.0.35-r1/work/db-6.0.35/dist' ...
 * ERROR: sys-libs/db-6.0.35-r1::gentoo failed (prepare phase):
 *   Cannot find the latest automake! Tried 1.16:1.16 1.15.1:1.15
 * 
 * Call stack:
 *     ebuild.sh, line  124:  Called src_prepare
 *   environment, line 4944:  Called eautoreconf
 *   environment, line 1112:  Called _elibtoolize '--auto-ltdl' '--install' '--copy' '--force'
 *   environment, line  324:  Called autotools_run_tool 'libtoolize' '--install' '--copy' '--force'
 *   environment, line  672:  Called autotools_env_setup
 *   environment, line  625:  Called die
 * The specific snippet of code:
 *           [[ ${WANT_AUTOMAKE} == "latest" ]] && die "Cannot find the latest automake! Tried ${_LATEST_AUTOMAKE[*]}";
 * 
 * If you need support, post the output of `emerge --info '=sys-libs/db-6.0.35-r1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=sys-libs/db-6.0.35-r1::gentoo'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=  CLASSPATH="" JAVA_HOME="/etc/java-config-2/current-system-vm"
JAVACFLAGS="" COMPILER=""
and of course, the output of emerge --info =db-6.0.35
 * The complete build log is located at '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/sys-libs/db-6.0.35-r1/temp/build.log'.
 * The ebuild environment file is located at '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/sys-libs/db-6.0.35-r1/temp/environment'.
 * Working directory: '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/sys-libs/db-6.0.35-r1/work/db-6.0.35/dist'
 * S: '/usr/armv7a-hardfloat-linux-gnueabi/tmp/portage/sys-libs/db-6.0.35-r1/work/db-6.0.35/build_unix'
```

### CODE REVIEW

**Comment by Whissi** [comment]
Sorry, base-system won't adopt EAPI=7 that soon, see https://wiki.gentoo.org/wiki/Project:Base#Rules_and_limitations

**Comment by hanetzer** [comment]
```diff
--- db-6.0.35-r1.ebuild	2018-05-08 02:35:11.845517925 -0500
+++ db-6.0.35-r2.ebuild	2018-05-08 03:05:36.519585967 -0500
@@ -1,8 +1,8 @@
 # Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=5
-inherit eutils db flag-o-matic java-pkg-opt-2 autotools multilib multilib-minimal versionator toolchain-funcs
+EAPI=7
+inherit db flag-o-matic java-pkg-opt-2 autotools multilib-minimal toolchain-funcs
 
 #Number of official patches
 #PATCHNO=`echo ${PV}|sed -e "s,\(.*_p\)\([0-9]*\),\2,"`
@@ -16,8 +16,8 @@
 	MY_P=${PN}-${MY_PV}
 fi
 
-S_BASE="${WORKDIR}/${MY_P}"
-S="${S_BASE}/build_unix"
+S="${WORKDIR}/${MY_P}"
+BUILD_DIR="${S}/build${MULTIBUILD_VARIANT}"
 DESCRIPTION="Oracle Berkeley DB"
 HOMEPAGE="http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/overview/index.html"
 SRC_URI="http://download.oracle.com/berkeley-db/${MY_P}.tar.gz"
@@ -26,7 +26,7 @@
 done
 
 LICENSE="AGPL-3"
-SLOT="$(get_version_component_range 1-2)"
+SLOT="$(ver_cut 1-2)"
 KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~m68k ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86 ~x86-fbsd"
 IUSE="doc java cxx tcl test"
 
@@ -41,48 +41,51 @@
 	java? ( >=virtual/jre-1.5 )"
 
 MULTILIB_WRAPPED_HEADERS=(
-	/usr/include/db$(get_version_component_range 1-2)/db.h
+	/usr/include/db$(ver_cut 1-2)/db.h
 )
 
-src_prepare() {
-	cd "${WORKDIR}"/"${MY_P}"
-	for (( i=1 ; i<=${PATCHNO} ; i++ ))
-	do
-		epatch "${DISTDIR}"/patch."${MY_PV}"."${i}"
-	done
-
+PATCHES=()
+for (( i=1 ; i<=${PATCHNO} ; i++ ))
+do
+	PATCHES+=( "${DISTDIR}"/patch."${MY_PV}"."${i}" )
+done
+PATCHES+=(
 	# bug #510506
-	epatch "${FILESDIR}"/${PN}-4.8.24-java-manifest-location.patch
+	"${FILESDIR}"/${PN}-4.8.24-java-manifest-location.patch
 
 	# use the includes from the prefix
-	epatch "${FILESDIR}"/${PN}-4.6-jni-check-prefix-first.patch
-	epatch "${FILESDIR}"/${PN}-4.3-listen-to-java-options.patch
+	"${FILESDIR}"/${PN}-4.6-jni-check-prefix-first.patch
+	"${FILESDIR}"/${PN}-4.3-listen-to-java-options.patch
 
 	# sqlite configure call has an extra leading ..
 	# upstreamed:5.2.36, missing in 5.3.x/6.x
 	# still needs to be patched in 6.0.20
-	epatch "${FILESDIR}"/${PN}-6.0.35-sqlite-configure-path.patch
+	"${FILESDIR}"/${PN}-6.0.35-sqlite-configure-path.patch
 
 	# The upstream testsuite copies .lib and the binaries for each parallel test
 	# core, ~300MB each. This patch uses links instead, saves a lot of space.
-	epatch "${FILESDIR}"/${PN}-6.0.20-test-link.patch
+	"${FILESDIR}"/${PN}-6.0.20-test-link.patch
+)
+
+src_prepare() {
+	default
 
 	# Upstream release script grabs the dates when the script was run, so lets
 	# end-run them to keep the date the same.
 	export REAL_DB_RELEASE_DATE="$(awk \
 		'/^DB_VERSION_STRING=/{ gsub(".*\\(|\\).*","",$0); print $0; }' \
-		"${S_BASE}"/dist/configure)"
+		dist/configure)"
 	sed -r -i \
 		-e "/^DB_RELEASE_DATE=/s~=.*~='${REAL_DB_RELEASE_DATE}'~g" \
-		"${S_BASE}"/dist/RELEASE || die
+		dist/RELEASE || die
 
 	# Include the SLOT for Java JAR files
 	# This supersedes the unused jarlocation patches.
 	sed -r -i \
 		-e '/jarfile=.*\.jar$/s,(.jar$),-$(LIBVERSION)\1,g' \
-		"${S_BASE}"/dist/Makefile.in || die
+		"${S}"/dist/Makefile.in || die
 
-	cd "${S_BASE}"/dist || die
+	cd dist || die
 	rm -f aclocal/libtool.m4
 	sed -i \
 		-e '/AC_PROG_LIBTOOL$/aLT_OUTPUT' \
@@ -106,7 +109,7 @@
 	# looks for 'Skipping\s'
 	sed -i \
 		-e '/db_repsite/s,Skipping:,Skipping,g' \
-		"${S_BASE}"/test/tcl/reputils.tcl || die
+		"${S}"/test/tcl/reputils.tcl || die
 }
 
 multilib_src_configure() {
@@ -149,7 +152,7 @@
 	# --enable-sql_compat
 	# Don't --enable-sql* because we don't want to use bundled sqlite.
 	# See Gentoo bug #605688
-	ECONF_SOURCE="${S_BASE}"/dist \
+	ECONF_SOURCE="${S}"/dist \
 	STRIP="true" \
 	econf \
 		--enable-compat185 \
@@ -213,7 +216,7 @@
 	#	"${S_BASE}/test/testparams.tcl"
 	sed -ri \
 		-e '/multi_repmgr/d' \
-		"${S_BASE}/test/tcl/test.tcl" || die
+		"${S}/test/tcl/test.tcl" || die
 
 	# This is the only failure in 5.2.28 so far, and looks like a false positive.
 	# Repmgr018 (btree): Test of repmgr stats.
@@ -226,7 +229,7 @@
 	sed -ri \
 		-e '/set parms.*repmgr018/d' \
 		-e 's/repmgr018//g' \
-		"${S_BASE}/test/tcl/test.tcl" || die
+		"${S}/test/tcl/test.tcl" || die
 
 	multilib-minimal_src_test
 }
```
```diff
--- db-5.3.28-r3.ebuild	2018-05-08 01:12:00.084331781 -0500
+++ db-5.3.28-r4.ebuild	2018-05-08 03:05:36.519585967 -0500
@@ -1,8 +1,8 @@
 # Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=5
-inherit eutils db flag-o-matic java-pkg-opt-2 autotools multilib multilib-minimal toolchain-funcs
+EAPI=7
+inherit db flag-o-matic java-pkg-opt-2 autotools multilib-minimal toolchain-funcs
 
 #Number of official patches
 #PATCHNO=`echo ${PV}|sed -e "s,\(.*_p\)\([0-9]*\),\2,"`
@@ -16,8 +16,8 @@
 	MY_P=${PN}-${MY_PV}
 fi
 
-S_BASE="${WORKDIR}/${MY_P}"
-S="${S_BASE}/build_unix"
+S="${WORKDIR}/${MY_P}"
+BUILD_DIR="${S}/build${MULTIBUILD_VARIANT}"
 DESCRIPTION="Oracle Berkeley DB"
 HOMEPAGE="http://www.oracle.com/technetwork/database/database-technologies/berkeleydb/overview/index.html"
 SRC_URI="http://download.oracle.com/berkeley-db/${MY_P}.tar.gz"
@@ -26,7 +26,7 @@
 done
 
 LICENSE="Sleepycat"
-SLOT="5.3"
+SLOT="$(ver_cut 1-2)"
 KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~m68k ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86 ~x86-fbsd"
 IUSE="doc java cxx tcl test"
 
@@ -41,50 +41,53 @@
 	java? ( >=virtual/jre-1.5 )"
 
 MULTILIB_WRAPPED_HEADERS=(
-	/usr/include/db5.3/db.h
+	/usr/include/db$(ver_cut 1-2)/db.h
 )
 
-src_prepare() {
-	cd "${WORKDIR}"/"${MY_P}"
-	for (( i=1 ; i<=${PATCHNO} ; i++ ))
-	do
-		epatch "${DISTDIR}"/patch."${MY_PV}"."${i}"
-	done
-
+PATCHES=()
+for (( i=1 ; i<=${PATCHNO} ; i++ ))
+do
+	PATCHES+=( "${DISTDIR}"/patch."${MY_PV}"."${i}" )
+done
+PATCHES+=(
 	# bug #510506
-	epatch "${FILESDIR}"/${PN}-4.8.24-java-manifest-location.patch
+	"${FILESDIR}"/${PN}-4.8.24-java-manifest-location.patch
 
 	# use the includes from the prefix
-	epatch "${FILESDIR}"/${PN}-4.6-jni-check-prefix-first.patch
-	epatch "${FILESDIR}"/${PN}-4.3-listen-to-java-options.patch
+	"${FILESDIR}"/${PN}-4.6-jni-check-prefix-first.patch
+	"${FILESDIR}"/${PN}-4.3-listen-to-java-options.patch
 
 	# sqlite configure call has an extra leading ..
 	# upstreamed:5.2.36, missing in 5.3.x
-	epatch "${FILESDIR}"/${PN}-5.2.28-sqlite-configure-path.patch
+	"${FILESDIR}"/${PN}-5.2.28-sqlite-configure-path.patch
 
 	# The upstream testsuite copies .lib and the binaries for each parallel test
 	# core, ~300MB each. This patch uses links instead, saves a lot of space.
-	epatch "${FILESDIR}"/${PN}-6.0.20-test-link.patch
+	"${FILESDIR}"/${PN}-6.0.20-test-link.patch
 
 	# Needed when compiling with clang
-	epatch "${FILESDIR}"/${PN}-5.1.29-rename-atomic-compare-exchange.patch
+	"${FILESDIR}"/${PN}-5.1.29-rename-atomic-compare-exchange.patch
+)
+
+src_prepare() {
+	default
 
 	# Upstream release script grabs the dates when the script was run, so lets
 	# end-run them to keep the date the same.
 	export REAL_DB_RELEASE_DATE="$(awk \
 		'/^DB_VERSION_STRING=/{ gsub(".*\\(|\\).*","",$0); print $0; }' \
-		"${S_BASE}"/dist/configure)"
+		dist/configure)"
 	sed -r -i \
 		-e "/^DB_RELEASE_DATE=/s~=.*~='${REAL_DB_RELEASE_DATE}'~g" \
-		"${S_BASE}"/dist/RELEASE || die
+		dist/RELEASE || die
 
 	# Include the SLOT for Java JAR files
 	# This supersedes the unused jarlocation patches.
 	sed -r -i \
 		-e '/jarfile=.*\.jar$/s,(.jar$),-$(LIBVERSION)\1,g' \
-		"${S_BASE}"/dist/Makefile.in || die
+		"${S}"/dist/Makefile.in || die
 
-	cd "${S_BASE}"/dist || die
+	cd dist || die
 	rm -f aclocal/libtool.m4
 	sed -i \
 		-e '/AC_PROG_LIBTOOL$/aLT_OUTPUT' \
@@ -108,7 +111,7 @@
 	# looks for 'Skipping\s'
 	sed -i \
 		-e '/db_repsite/s,Skipping:,Skipping,g' \
-		"${S_BASE}"/test/tcl/reputils.tcl || die
+		"${S}"/test/tcl/reputils.tcl || die
 }
 
 multilib_src_configure() {
@@ -151,7 +154,7 @@
 	# --enable-sql_compat
 	# Don't --enable-sql* because we don't want to use bundled sqlite.
 	# See Gentoo bug #605688
-	ECONF_SOURCE="${S_BASE}"/dist \
+	ECONF_SOURCE="${S}"/dist \
 	STRIP="true" \
 	econf \
 		--enable-compat185 \
@@ -215,7 +218,7 @@
 	#	"${S_BASE}/test/testparams.tcl"
 	sed -ri \
 		-e '/multi_repmgr/d' \
-		"${S_BASE}/test/tcl/test.tcl" || die
+		"${S}/test/tcl/test.tcl" || die
 
 	# This is the only failure in 5.2.28 so far, and looks like a false positive.
 	# Repmgr018 (btree): Test of repmgr stats.
@@ -228,7 +231,7 @@
 	sed -ri \
 		-e '/set parms.*repmgr018/d' \
 		-e 's/repmgr018//g' \
-		"${S_BASE}/test/tcl/test.tcl" || die
+		"${S}/test/tcl/test.tcl" || die
 
 	multilib-minimal_src_test
 }
```

**Comment by hanetzer** [comment]
@Whissi so we're going to wait a year before the stuff that makes EAPI 7 specifically
useful over EAPI 6 to actually hit the packages that will actually benefit from it? Seems
short-sighted.

**Comment by Whissi** [comment]
Yes, remember that base-system project is special: We need to ensure for example that people with an 1y old Gentoo system are able to upgrade/catch up. And until recently, base-system packages were 2-3 EAPI's behind, so while I understand that this can be annoying especially when a new EAPI makes life so much easier sometimes, the rule has its reason.

**Comment by Alessandro-Barbieri** [comment]
@hanetzer hey, since EAPI 7 is in base-system stable can you reopen this? I'm making changes to sys-libs/db and will be useful to have this changed merged.

**Comment by hanetzer** [comment]
@Alessandro-Barbieri I cannot, I lack the perms. Someone else could, however.

**Comment by Whissi** [comment]
The eapi7/sys-libs/db branch was force-pushed or recreated and therefore can't be reopen. Please create a new one.

**Comment by hanetzer** [comment]
Yeah, it may have been during that hack. It fsck'd a lot of my open pull requests.

**Pull request closed without merging**
