### PR TITLE
mail-filter/rspamd: Version bump to 1.8.1

### PR DESCRIPTION
**Pull request by croessner**

### CODE REVIEW

**Comment by djc** [comment]
@croessner GCO signoff is still missing, can you fix that, please? It should be as easy as `git commit --amend --signoff && git push -f`.

**Comment by rseichter** [comment]
A question about procedure, if I may: Why is this a new pull request, what with https://github.com/gentoo/gentoo/pull/10057 still being open? Would it not be better to modify the existing PR? This is not meant as nagging, I'm really interested in the answer.

**Comment by croessner** [comment]
> A question about procedure, if I may: Why is this a new pull request, what with #10057 still being open? Would it not be better to modify the existing PR? This is not meant as nagging, I'm really interested in the answer.

Well, 1.8.1 was released newly and I thought this also obsoletes 1.8.0 directly, as the minor number is a bug fix release.

And... to be honest... I am not very good with git :-/ So, to not mix things, I always do:

git checkout master
git pull ...from...gentoo...
git add -A
git commit -a
git push

and then I create a new branch

git checkout -b rspamd-newversion

At least that worked for me. If you guys can give me some easier way, I will follow that next time ;-)

Thanks

Christian

**Comment by rseichter** [comment]
> Well, 1.8.1 was released newly and I thought this also obsoletes 1.8.0 directly, as the minor number is a bug fix release.

That's why I wondered about. If the 1.8.1 ebuild indeed renders the 1.8.0 ebuild obsolete (looking at the rspamd release notes I believe it does), you can either repurpose https://github.com/gentoo/gentoo/pull/10057 as a vehicle for version 1.8.1 (using `git mv ...` to rename your ebuild), or you can close that PR if you are certain it is no longer needed. Given that the existing PR contains reviews and other information, I'd personally lean towards modifying it, instead of creating a new PR.

As for Git, I found [this page](https://wiki.gentoo.org/wiki/GitHub_Pull_Requests) a good starting point.

**Comment by djc** [comment]
Rebased and pushed as 2a83bb6d12bebbcf671a54f65ed7f8b072dfb8ce, thanks!

**Pull request closed without merging**
