### PR TITLE
dev-java/spin: min java 1.8:*

### PR DESCRIPTION
**Pull request by vaukai**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by vaukai** [comment]
> javadoc is failing here for me. it might need `cglib` on the classpath for javadoc:
> 

Solved by switching to `java-pkg-simple`.

**Comment by fordfrog** [comment]
nice, thanks.

now i get this:
```
There was 1 error:
1) testNonAccessibleInterface(spin.JDKProxyFactoryTest)java.awt.HeadlessException
	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
	at java.desktop/java.awt.Window.<init>(Window.java:553)
	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
	at spin.JDKProxyFactoryTest$1.<init>(JDKProxyFactoryTest.java:44)
	at spin.JDKProxyFactoryTest.testNonAccessibleInterface(JDKProxyFactoryTest.java:44)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

FAILURES!!!
Tests run: 5,  Failures: 0,  Errors: 1
```
anyone can reproduce this issue or is it just me?

**Comment by vaukai** [comment]
> nice, thanks.
> 
> now i get this:
> 
> ```
> There was 1 error:
> 1) testNonAccessibleInterface(spin.JDKProxyFactoryTest)java.awt.HeadlessException
> 	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:166)
> 	at java.desktop/java.awt.Window.<init>(Window.java:553)
> 	at java.desktop/java.awt.Frame.<init>(Frame.java:428)
> 	at java.desktop/java.awt.Frame.<init>(Frame.java:393)
> 	at java.desktop/javax.swing.JFrame.<init>(JFrame.java:180)
> 	at spin.JDKProxyFactoryTest$1.<init>(JDKProxyFactoryTest.java:44)
> 	at spin.JDKProxyFactoryTest.testNonAccessibleInterface(JDKProxyFactoryTest.java:44)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> FAILURES!!!
> Tests run: 5,  Failures: 0,  Errors: 1
> ```
> 
> anyone can reproduce this issue or is it just me?

Here, `spin.JDKProxyFactoryTest` isn't run at all. At least not using the ebuiild.  
However running `mvn test`, I get the following (openjdk-8):

```
-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running spin.JDKProxyFactoryTest
Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.132 sec
Running spin.CGLibProxyFactoryTest
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.064 sec
Running spin.off.AWTReflectDispatcherTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.004 sec
Running spin.off.SpinOffTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.012 sec

Results :

Tests run: 11, Failures: 0, Errors: 0, Skipped: 0

```

**Comment by fordfrog** [comment]
now tested with 1.8 and 11, still have the issue. also, i just noticed this issue:
```
/var/tmp/portage/dev-java/spin-1.5-r2/temp/environment: line 2421: [[: 1.8: syntax error: invalid arithmetic operator (error token is ".8")
```

**Comment by vaukai** [comment]
> now tested with 1.8 and 11, still have the issue. also, i just noticed this issue:
> 
> ```
> /var/tmp/portage/dev-java/spin-1.5-r2/temp/environment: line 2421: [[: 1.8: syntax error: invalid arithmetic operator (error token is ".8")
> ```

Confirmed.  I can reproduce that message, but only with `jdk-1.8` and only in test phase.
@fordfrog @Leo3418 Do you have any recommendation how to solve it?

Another point is that running those four test classe in one batch doesn't work here.  So it seems we need to run them separately. And exclude that one with test failure.

Looking forward to last-riting this package in a hopefully not too far future ...

**Comment by Leo3418** [comment]
> > now tested with 1.8 and 11, still have the issue. also, i just noticed this issue:
> > ```
> > /var/tmp/portage/dev-java/spin-1.5-r2/temp/environment: line 2421: [[: 1.8: syntax error: invalid arithmetic operator (error token is ".8")
> > ```
> 
> Confirmed. I can reproduce that message, but only with `jdk-1.8` and only in test phase. @fordfrog @Leo3418 Do you have any recommendation how to solve it?
> 
> Another point is that running those four test classe in one batch doesn't work here. So it seems we need to run them separately. And exclude that one with test failure.
> 
> Looking forward to last-riting this package in a hopefully not too far future ...

Use `ver_test`:
```bash
	if ver_test "${vm_version}" -ge "17" ; then
```

**Comment by fordfrog** [comment]
@vaukai merged, thanks!

**Pull request closed without merging**
