### PR TITLE
dev-lua/toluapp: new maintainer

### PR DESCRIPTION
**Pull request by winterheart**
Package-Manager: Portage-2.3.79, Repoman-2.3.16
Signed-off-by: Azamat H. Hackimov <azamat.hackimov@gmail.com>

### CODE REVIEW

**Comment by juippis** [comment]
Could you fix some bugs for this package before adding yourself as a maintainer? We'd like to see you're dedicated to the cause. And I see no contributions from you to this in recent history.
https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Taking_over_an_existing_package 2-3.

**Comment by winterheart** [comment]
Currently none of opened bugs can be resolved without deep patching. Package in abandoned state and need some developer's care.

**Comment by juippis** [comment]
If you don't intend to spend time fixing bugs... why become the maintainer? I hope you understand where this is coming from, but we'd much rather wait and let someone take over the package, instead of putting people to metadata.xml without any action done to the package.

**Comment by winterheart** [comment]
There only two bugs on package:
* https://bugs.gentoo.org/508222 - Lua 5.2 compatibility issue. I don't have lua 5.2 unmasked, I can't fix any of >=lua-5.2 issues until there will be resolution for stable and universal approach for whole Lua ecosystem.
* https://bugs.gentoo.org/730384 - (tracker created by me) uses Lua 5.1 deprecated code. Again, this is complex bug which requires lots of time for fixing and testing and somehow related to 508222.

As you probably noticed, I do care about my packages and trying to fix every bug encountered on them. Just for now this package needs extensive research and development.

**Comment by ConiKost** [comment]
As for now, both bugs where done in past, so closing here for now..

**Pull request closed without merging**
