### PR TITLE
*/*: update desktop mimeinfo cache

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by rossbridger** [comment]
For starters, you submitted 9 PRs all for just adding xdg inheritance. Shouldn't they be squashed into one PR?

**Comment by jsmolic** [comment]
> For starters, you submitted 9 PRs all for just adding xdg inheritance. Shouldn't they be squashed into one PR?

Yes, I'll force push not to pollute with multiple PR's (there were different maintainers so I initially created separately)

**Comment by chewi** [comment]
The games-emulation/lxdream change is fine but the bug # here is also wrong. It should be 739190. 739324 is about games-puzzle/xye, which has the same issue.

**Comment by jsmolic** [comment]
@voyageur @chewi Thanks, I confused some bug numbers during the process. I updated it now

**Review by chewi — APPROVED** [review]
Games look good! The rest look good too but they're not mine.

**Review by voyageur — APPROVED** [review]

**Review by juippis — APPROVED** [review]
I don't see any harm done to any package involved here, and bugs seem to be correctly linked. Merging all. Thanks!

**Comment by jsmolic** [comment]
Thanks @juippis

**Pull request closed without merging**
