### PR TITLE
app-misc/nnn: add 4.9

### PR DESCRIPTION
**Pull request by s-hamann**
~Trivial~ version bump for latest upstream release.

Edit: Changes the patch behind the `colemak` USE flag (because it is broken) and drops `colemak-dh` USE flag (because the patch is also broken and scheduled to be removed upstream).

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Looks like `-nerdfonts` use flag is broken, 
```
>>> Compiling source in /var/tmp/portage/app-misc/nnn-4.9/work/nnn-4.9 ...
make -j32 O_NORL=0 O_PCRE=1 O_CTX8=0 O_ICONS=0 O_NERD=0 O_EMOJI=1 O_QSORT=0 O_COLEMAK=1 O_COLEMAK_DH=0 O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=0 
x86_64-pc-linux-gnu-gcc -DPCRE -DEMOJI -DICONS_INCLUDE=\"icons-generated-emoji.h\" -march=native -O2 -pipe -frecord-gcc-switches -std=c11 -Wall -Wextra -Wshadow -O3 -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=600 -I/usr/include/ncursesw -Wl,-O1 -Wl,--as-needed -Wl,--defsym=__gentoo_check_ldflags__=0 -DICONS_GENERATE -o src/icons-hash-gen src/icons-hash.c
./src/icons-hash-gen > src/icons-generated-emoji.h
patching file src/nnn.c
Hunk #1 succeeded at 282 (offset 12 lines).
Hunk #2 succeeded at 325 (offset 12 lines).
Hunk #3 succeeded at 381 (offset 12 lines).
Hunk #4 succeeded at 433 (offset 12 lines).
Hunk #5 succeeded at 3946 (offset 119 lines).
Hunk #6 succeeded at 4314 (offset 119 lines).
Hunk #7 succeeded at 5803 (offset 135 lines).
Hunk #8 succeeded at 6008 (offset 135 lines).
Hunk #9 succeeded at 6614 (offset 149 lines).
Hunk #10 succeeded at 8439 (offset 191 lines).
Hunk #11 succeeded at 8579 (offset 191 lines).
Hunk #12 succeeded at 8624 (offset 191 lines).
Hunk #13 succeeded at 8678 (offset 191 lines).
patching file src/nnn.c
Hunk #1 FAILED at 5098.
1 out of 1 hunk FAILED -- saving rejects to file src/nnn.c.rej
patching file src/nnn.h
Hunk #1 succeeded at 138 (offset 1 line).
Hunk #2 succeeded at 156 (offset 1 line).
Hunk #3 succeeded at 201 (offset 2 lines).
Hunk #4 succeeded at 228 (offset 2 lines).
Hunk #5 succeeded at 245 (offset 2 lines).
Hunk #6 succeeded at 257 (offset 2 lines).
make[1]: *** [Makefile:338: prepatch] Error 1
make: *** [Makefile:211: nnn] Error 2
 * ERROR: app-misc/nnn-4.9::gentoo failed (compile phase):
 *   emake failed
```
```
[ERROR] >>> Not all runs were successful.
atom: =app-misc/nnn-4.9, USE flags: '-8contexts colemak -colemak-dh -emoji gitstatus icons namefirst -nerdfonts pcre -qsort -readline -restorepreview'
atom: =app-misc/nnn-4.9, USE flags: '8contexts -colemak colemak-dh -emoji -gitstatus icons namefirst -nerdfonts pcre -qsort -readline restorepreview'
atom: =app-misc/nnn-4.9, USE flags: '8contexts colemak -colemak-dh -emoji gitstatus -icons -namefirst -nerdfonts pcre qsort readline -restorepreview'
atom: =app-misc/nnn-4.9, USE flags: '8contexts colemak -colemak-dh -emoji gitstatus icons -namefirst -nerdfonts -pcre qsort readline restorepreview'
atom: =app-misc/nnn-4.9, USE flags: '-8contexts colemak -colemak-dh emoji gitstatus -icons -namefirst -nerdfonts pcre -qsort readline -restorepreview'
```
This build system is also very weird o.o

**Comment by s-hamann** [comment]
Thanks for catching this. For me, it's not `-nerdfont`, though, but `colemak` (and `colemak-dh`) that seem to fail. I'll try to find out more.

**Comment by s-hamann** [comment]
It looks like an upstream issue to me. I raised a PR (jarun/nnn#1744). I'll add a downstream fix for Colemak.
I'm not sure about Colemak-DH, though. Upstream dropped that patch, so it won't be in the next release. We could simply drop Colemak-DH earlier on Gentoo. Or I could do a downstream fix for this bit of dead code. I'm in favour of the former. @juippis What do you think?

**Comment by juippis** [comment]
Please include the patch for colemak and yeah let's drop colemak-dh already. I think that's the cleanest and easiest solution here. Thanks for looking into it!

**Comment by s-hamann** [comment]
Done. Let me know if I should squash the commits.

**Review by juippis — APPROVED** [review]
I'll squash, thanks!

**Pull request closed without merging**
