### PR TITLE
gui-wm/wayfire: fix wlroots dependencies

### PR DESCRIPTION
**Pull request by epsilon-0**

### CODE REVIEW

**Comment by epsilon-0** [comment]
@prometheanfire can you take a look here?

**Comment by epsilon-0** [comment]
@Freed0mBear @prometheanfire 
pinging reminder

**Comment by prometheanfire** [comment]
I understand that my review is requested but I don't have any to give as it isn't my package (it depends on wlroots, but that's the limit of things).  My only advice on packaging something that depends on wlroots is to look at what sway is doing :D

**Comment by thesamesam** [comment]
No worries, I just have literally no idea about this stuff, so someone who knows a tiny bit is better ;)

You’re free to merge it if you’re happy.

**Review by juippis — APPROVED** [review]
I had some sort of error with seatd not found in some -9999 version... probably related to -elogind -systemd change. Sorry, lost the logs. Still works mostly fine ;)

**Pull request closed without merging**
