### PR TITLE
app-arch/rpm: fix building RPM package with clang

### PR DESCRIPTION
**Pull request by dpronin**

### CODE REVIEW

**Comment by thesamesam** [comment]
Is this upstream somewhere? If not, please submit it.

>Signed-off-by: Arthur Zamarin <arthurzam@gentoo.org>

You're not Arthur!

**Comment by dpronin** [comment]
@arthurzam 

I've checked latest [lib/fsm.c:1022](https://github.com/rpm-software-management/rpm/blob/master/lib/fsm.c#L1022) and seen that code was changed so that there has not been defined a new variable right under the label, so clang does not fail to compile anymore

**Comment by dpronin** [comment]
In this package we have old code database, so we still need these changes to enable clang to compile out

**Comment by thesamesam** [comment]
am I missing something for why you keep involving arthur here?

**Comment by pastalian** [comment]
Upstream fixed this bug with [this](https://github.com/rpm-software-management/rpm/commit/6ad8a71407b173b6c50d389f01edd8a4aecd6807) commit. We can just bump to 4.18.2 though.

**Comment by dpronin** [comment]
@pastalian so, what are the further steps?

**Comment by pastalian** [comment]
@dpronin Up to you (unless Gentoo developer says otherwise).
I'm just suggesting that you take a patch from upstream or make a bump PR so you don't need the patch anymore.

**Comment by thesamesam** [comment]
> am I missing something for why you keep involving arthur here?

I'm really curious as to the answer to this?

**Comment by dpronin** [comment]
@thesamesam because I've gone crazy, sorry for that

**Comment by thesamesam** [comment]
no worries!

**Pull request closed without merging**
