### PR TITLE
sys-apps/gentoo-functions: omit consoletype when USE=prefix-chaining

### PR DESCRIPTION
**Pull request by haubi**
Package-Manager: portage-2.3.3

### CODE REVIEW

**Comment by haubi** [comment]
For the live ebuild please review https://github.com/gentoo/gentoo-functions/pull/5 first.

**Comment by williamh** [comment]
Please rebase this. Also, please avoid using sed in the ebuild.
Also, what is "prefix-chaining"? I know of prefix, but not prefix-chaining.

**Comment by monsieurp** [comment]
Hi @haubi! What's the status here? Are you still working on this PR?

**Comment by haubi** [comment]
I do need at least one of two options here:
1) Avoid consoletype eventually, as it currently fails to compile for native windows.
2) Fix consoletype for native windows to output "unknown" at least.
A patch for each option is waiting for review in https://github.com/gentoo/gentoo-functions/pull/5 still...

About "prefix-chaining": Underlying problem is that portage&co do not run as native windows binaries, but with cygwin only. Fortunately I do not need the whole build environment to be native windows binaries, but some libraries only. Now portage is installed in some Cygwin Prefix, and the native Windows Prefix is managed by that cygwin portage, resolving DEPENDs into the Cygwin Prefix while RDEPENDs get emerged into the Windows Prefix. To some degree this is a combination of cross compiling (but ROOT='') and multilib (but different EPREFIX).

Strictly speaking, gentoo-functions should not be installed into the Windows Prefix at all, because it should be a build DEPENDency only, but that would require lots of patching for packages installed into the Windows Prefix to find gentoo-functions from the Cygwin Prefix, so it is easier to install gentoo-functions into the Windows Prefix as well.

**Comment by flappyports** [comment]
no activity

**Pull request closed without merging**
