### PR TITLE
kernel-2.eclass: Implicit dependency cleanups (and others)

### PR DESCRIPTION
**Pull request by karlguy**
Binutils is listed as a dependency of many packages, which is undesired. It is provided implicitly with the system.

### CODE REVIEW

**Comment by karlguy** [comment]
@gentoo-repo-qa-bot ?

**Comment by karlguy** [comment]
@gentoo-repo-qa-bot

**Comment by karlguy** [comment]
@gentoo-repo-qa-bot

**Comment by karlguy** [comment]
Sorry @mgorny, I'm gonna ping you since this bot is bad at it's job.

**Comment by mgorny** [comment]
What do you need to be done? The CI seems to be working just fine, and your latest commit is marked as good.

**Comment by karlguy** [comment]
Oh sorry then. I thought it wasn't assigned to anyone, so it wasn't going to be merged anytime soon.

**Comment by blueness** [comment]
@karlguy I'm okay with removing binutils dep.  Is this just a simple cleanup or did it cause a problem somewhere?

**Comment by karlguy** [comment]
It makes it less hackish to replace the programs provided by GNU binutils with equivilent LLVM implementiations

**Comment by blueness** [comment]
Okay, but you bundled the commit against kernel-2.eclass (which I can signoff on and commit) with commits against other eclasses (which I cannot signoff on).  You can either unbundle it, or get a signoff on all those eclasses.  Your choice.

**Comment by karlguy** [comment]
I'll wait for the mozconfig to get signed off on. I don't want to break everything because of my inability to use git.

**Comment by karlguy** [comment]
I removed the changes to gnatbuild, since I don't really care about it, and if you have are using gnat, you probably have gnu-binutils and gcc, and all that stuff.

So the only other eclass that requires signing off is now mozconfig.

**Comment by karlguy** [comment]
@axs-gentoo

**Comment by axs-gentoo** [comment]
So far as I can tell, the atom in mozilla's eclasses were only to ensure a minimun version and since that minimum has long been dropped from the gentoo repo I think we're fine to drop the atom.  I'll sign-off.

**Comment by karlguy** [comment]
@blueness

**Comment by karlguy** [comment]
@blueness

**Comment by karlguy** [comment]
I think this is ready to be merged.

**Comment by karlguy** [comment]
@blueness All the appropriate eclasses have been signed off now. This is now ready to be merged.

**Comment by mgorny** [comment]
@karlguy, did you obtain ack from maintainer of all those packages or just eclasses?

**Comment by karlguy** [comment]
Just eclasses

**Comment by karlguy** [comment]
@blueness What's the status on this?

**Comment by blueness** [comment]
I'm okay with both kernel-2.eclass and paxctl

**Comment by karlguy** [comment]
Sorry if this is a silly question, but do I have to get ack from all the maintainers for this to get merged?

**Comment by blueness** [comment]
@karlguy yes, i'm not going to speak for other people's packages.

**Comment by karlguy** [comment]
Ok, I understand. @maekke @markwright @robbat2

**Comment by flappyports** [comment]
no activity

**Pull request closed without merging**
