### PR TITLE
app-misc/goobook: version bump to 3.4

### PR DESCRIPTION
**Pull request by thinrope**
ebuild is unchanged, upstream fixed 2 bugs
Removing goobook-3.3, since it is fully replaceble by 3.4

Bug: https://bugs.gentoo.org/696462
Signed-off-by: Kalin KOZHUHAROV <kalin@thinrope.net>
Related: https://bugs.gentoo.org/678398

### CODE REVIEW

**Comment by juippis** [comment]
Still, dont use `git mv` but make a separate commit for ebuild addition and deletion.

**Comment by thinrope** [comment]
I apologize if I have asked that before, but why not use `git mv` (cannot see anything in the devmanual either)?
 Looking at the screen, I guess git did squished what I did upon commit anyway.
Please guide me a bit, I'll take notes ;-D

**Comment by thinrope** [comment]
Hopefully that works now, @juippis let me know if you spot anything weird!

If you can, please add a line in https://devmanual.gentoo.org/ebuild-maintenance/maintenance-tasks/index.html#upgrading-ebuilds to note that one needs 2 separate commits (first adding new version; second removing old/replaced one), and don't forget `repoman full` before every commit.

**Comment by juippis** [comment]
For proxy-maintainers: it makes reviewing ebuilds etc related files impossible in Github. 

For Gentoo workflow: it makes reverting possible bad commits break a lot more than with split commits. Also commits need to be logical. 
You can interpret it from GLEP-66.

Anyway thanks, looks good now! setuptools shouldn't be in DEPEND but I'll edit it out.

**Pull request closed without merging**
