### PR TITLE
app-arch/xarchiver-0.5.4.17 version bump

### PR DESCRIPTION
**Pull request by kuraga**
app-arch/xarchiver-0.5.4.17 version bump: https://github.com/ib/xarchiver/releases/tag/0.5.4.17

Closes: https://bugs.gentoo.org/771951
Signed-off-by: Alexander Kurakin <kuraga333@mail.ru>

### CODE REVIEW

**Comment by kuraga** [comment]
See also: https://github.com/gentoo/gentoo/pull/18939

**Comment by mgorny** [comment]
Hmm, why am I not following this package still?!

**Comment by mgorny** [comment]
Also, please use `repoman full` or `pkgcheck scan` to do at least basic linting on the ebuilds. You've got wrong copyright date and stable keywords in a new ebuild.

**Comment by kuraga** [comment]
> Also, please use `repoman full` or `pkgcheck scan` to do at least basic linting on the ebuilds. You've got wrong copyright date and stable keywords in a new ebuild.

Thanks !

**Comment by kuraga** [comment]
> Also, please use `repoman full` or `pkgcheck scan` to do at least basic linting on the ebuilds. You've got wrong copyright date and stable keywords in a new ebuild.

@mgorny but CI report doesn't show it, does it?

**Pull request closed without merging**
