### PR TITLE
net-nds/gssproxy: Fix build with musl llvm

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/898064

### CODE REVIEW

**Comment by orbea** [comment]
Small suggestion, but adding the upstreamed commit url to the patch file and adding `Upstream-PR:` and `Upstream-Commit:` to the commit message would make it clearer this is merged upstream. :)

**Comment by listout** [comment]
> Small suggestion, but adding the upstreamed commit url to the patch file and adding `Upstream-PR:` and `Upstream-Commit:` to the commit message would make it clearer this is merged upstream. :)

done :+1:

**Comment by listout** [comment]
ping! upstream is commit is merged

**Review by juippis — APPROVED** [review]
Can confirm this patch works with clang:16 and/or musl+clang:16. I'm not eligible to merge @gentoo/base-system packages though.

**Pull request closed without merging**
