### PR TITLE
dev-vcs/hg-git: update deps and stable for recently stable hg-4.2

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by grobian** [comment]
You should drop the keyword changes.  Apart from that, it looks ok.  Thanks.

**Comment by henning-schild** [comment]
done, how to address the keyword change, bugtracker?

**Comment by grobian** [comment]
Yes, stable keywords need a bug.  They are handled by the arch teams, maintainers can't just stabilise packages.

**Comment by grobian** [comment]
I've picked your commit and pushed it, thanks!

**Pull request closed without merging**
