### PR TITLE
bump version of dev-python/grpcio, dev-python/grpcio-tools, dev-python/grpcio-testing to 1.64.1

### PR DESCRIPTION
**Pull request by LeoQuote**
fix https://bugs.gentoo.org/904945 https://bugs.gentoo.org/929457

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by LeoQuote** [comment]
@mgorny Hi, would you consider merging this pr and unmask dev-python/grpcio ?

**Comment by mgorny** [comment]
1. This doesn't include all grpcio packages.
2. It still doesn't include any tests.

**Review by mgorny — CHANGES_REQUESTED** [review]
See above.

**Comment by LeoQuote** [comment]
@mgorny Thank you for your review. I have just provided ebuilds for `dev-python/grpcio-tools` and `dev-python/grpcio-testing`. Please take another look.

Regarding the testing issue you mentioned, I have investigated and found that in the grpc project, tests are centralized in a [single folder](https://github.com/grpc/grpc/tree/master/src/python/grpcio_tests) rather than being separated in individual clients. This means that in order to run tests in the ebuild, we would need to:
1. Clone the entire code repository instead of using the PyPI tarball.
2. Install all dependencies required for testing.
3. Follow the steps outlined in the [contribution guide](https://github.com/grpc/grpc/blob/master/CONTRIBUTING.md#building--running-tests) to run the tests.

Considering the above points, I would recommend adding tests only to dev-python/grpcio to avoid duplicated code or work. If you are satisfied with this approach, I will proceed accordingly. Looking forward to your response.

**Pull request closed without merging**
