### PR TITLE
net-irc/ii: version bump to 1.9

### PR DESCRIPTION
**Pull request by spencermp**
Bump ii to version 1.9, upstream latest.

Package-Manager: Portage-3.0.28, Repoman-3.0.3
Signed-off-by: Spencer Pavkovic <smp@nandre.com>

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution. Note that this causes a QA notice:

```
 * QA Notice: The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/share/doc/ii
 ```

It appears to be related to DOCDIR, which is set in `src_install` not being respected by the projects build system.

**Comment by spencermp** [comment]
That seems to fix it, thanks for spotting it.

**Comment by Flowdalic** [comment]
Now the problem is that the doc files get installed multiple times:

```
/usr/share/doc/ii-1.9/README.bz2
/usr/share/doc/ii-1.9/FAQ.bz2
/usr/share/doc/ii-1.9/CHANGES.bz2
/usr/share/ii/README
/usr/share/ii/FAQ
/usr/share/ii/LICENSE
/usr/share/ii/CHANGES
```

**Comment by thesamesam** [comment]
We want to install them to /usr/share/doc/${PF}. You can do one of:
- remove the Makefile installing it and keep the dodoc
- fix the Makefile path and remove the dodoc (preferred, I think, but it may be a bit awkward given not using `./configure`)

**Comment by Flowdalic** [comment]
@spencermp do you need help with this? Then feel free to join #gentoo-proxy-maint or #gentoo-dev-help and ask for help. Or do you lost interest? Then please consider closing this PR.

**Comment by spencermp** [comment]
I like suckless software, but wish they either put almost all variables in one file, or had a configure option.

**Comment by Flowdalic** [comment]
Looks good now, please quash

**Comment by Flowdalic** [comment]
> I like suckless software, but wish they either put almost all variables in one file, or had a configure option.

You can always try to bring your changes upstream :)

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
