### PR TITLE
net-misc/openfortivpn: version bump to the latest release 1.3.0

### PR DESCRIPTION
**Pull request by stefan-langenmaier**
There is already an open bug on b.g.o

https://bugs.gentoo.org/show_bug.cgi?id=602676

### CODE REVIEW

**Comment by MathyV** [comment]
Since the previous version isn't stable either, please remove it. Other than that looks ok to me.

**Comment by stefan-langenmaier** [comment]
The old version is removed.

**Comment by MathyV** [comment]
Please squash the commits

**Comment by stefan-langenmaier** [comment]
Sorry, the pull request should now be reduced to a single commit.

**Comment by MathyV** [comment]
It seems the QA check failed on the manifest file even though it looks okay to me

@SoapGentoo race condition?

**Comment by stefan-langenmaier** [comment]
Before I pushed the squashed commit there was a push where I forgot to commit the Manifest file. But it looks okay to me now.

**Comment by stefan-langenmaier** [comment]
Is it possible to just re-run the QA bot?

**Comment by mgorny** [comment]
The result is green now. But if you insist on re-running, just rebase to master and force push over.

**Comment by stefan-langenmaier** [comment]
I rebased it and I now have also the okay of the QA bot. :)

**Pull request closed without merging**
