### PR TITLE
net-dns/knot-resolver: add 6.0.9

### PR DESCRIPTION
**Pull request by PPN-SD**
Summary :

New optional python component, [manager](https://www.knot-resolver.cz/documentation/latest/dev/architecture.html), to start/manage Knot Resolver : 
- useflag manager (enabled by default)
- distutils / PEP517(poetry)
- python3_10..12 (no 3.13 due to app-admin/supervisor)
- start with /etc/init.d/knot-resolver or knot-resolver.service
- config file : /etc/conf.d/knot-resolver /etc/knot-resolver/config.yaml

Old/legacy way to start Knot Resolver is still supported and installed by default, even with the manager enabled by useflag :
- start with /etc/init.d/kresd or kresd'@'.service (installed by default with the meson_feature systemd_legacy_units)
- config file : /etc/conf.d/kresd /etc/kresd.conf (installed by default with -Dinstall_kresd_conf=enabled)

Useflags :
kresc (removed) : [has never gone beyond experiment/alpha](https://gitlab.nic.cz/knot/knot-resolver/-/commit/2db9970ae0b3f8e21de79d12cd0fc42f80de09e4)
prometheus (new) : prometheus metrics endpoint for the manager (dev-python/prometheus-client)

Patches : 
- 5/X patches to set docdir and optional deps (nghttp, openssl)
- 6.0.9-libsystemd.patch : rebase from 5.7.4. tmpfiles is independent of the systemd option/useflag
- 6.0.9-config-example.patch : for the manager. A default config file is installed in /etc/knot-resolver/config.yaml and examples in /usr/share/doc/
- 6.0.9-sd_notify_alt.patch : [upstream, fix systemd dep with sd_notify alternative for manager](https://gitlab.nic.cz/knot/knot-resolver/-/merge_requests/1608)
- 6.0.9-pytest_tomli.patch : for one pytest, import toml is replaced with tomli

Tests :
- unit_tests for kresd : enabled
- unit_tests for manager : enabled
- config_tests : disabled. It requires external lua modules (basexx, cqueues)
- extra_tests : disabled. Too extra ...

Knot DNS API/ABI :
[>=net-dns/knot-3.3 required](https://gitlab.nic.cz/knot/knot-resolver/-/blob/v6.0.9/meson.build?ref_type=tags#L21). Cf PR #39066

Extra package : 
Knot Resolver requires [lua-cqueues](http://25thandclement.com/~william/projects/cqueues.html) for some modules (graphite, http), tests and to watch and reload RPZ file, continuing without watching. [Guru package is available](https://gitweb.gentoo.org/repo/proj/guru.git/tree/dev-lua/cqueues)

If there are too many words, please tell me for next time ...

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please rebase and see https://github.com/gentoo/gentoo/pull/39066#issuecomment-2509793989. In general, verbose commit messages are good -- just use some light formatting like I did to structure them so they're easier to read. Thank you again!

**Comment by PPN-SD** [comment]
> Please rebase and see [#39066 (comment)](https://github.com/gentoo/gentoo/pull/39066#issuecomment-2509793989). In general, verbose commit messages are good -- just use some light formatting like I did to structure them so they're easier to read. Thank you again!

I think it's better for this one.
Thanks to you.

**Comment by thesamesam** [comment]
Looks good to me. I have applied a small fixup on top: https://github.com/gentoo/gentoo/pull/39482.

Thank you!

**Comment by thesamesam** [comment]
You can ignore that failure -- it's because you didn't rebase on a commit after I'd pushed knot itself.

**Comment by PPN-SD** [comment]
Could you consider [cqueues](https://github.com/gentoo/guru/tree/master/dev-lua/cqueues) extra package that enables, among others features, reloading policy file ?

**Comment by thesamesam** [comment]
If you proxy maintain it, sure.

**Comment by PPN-SD** [comment]
> If you proxy maintain it and make a PR to add it, sure.

I will 👍

**Pull request closed without merging**
