### PR TITLE
dev-lang/php: Bump to 7.2.7

### PR DESCRIPTION
**Pull request by Asgavar**

### CODE REVIEW

**Comment by orlitzky** [comment]
The new version fails to build:

```
 * php-7.2.7.tar.xz BLAKE2B SHA512 size ;-) ...                          [ ok ]
>>> Unpacking source...
>>> Unpacking php-7.2.7.tar.xz to /var/tmp/portage/dev-lang/php-7.2.7/work
>>> Source unpacked in /var/tmp/portage/dev-lang/php-7.2.7/work
>>> Preparing source in /var/tmp/portage/dev-lang/php-7.2.7/work/php-7.2.7 ...
 * Applying libressl-compatibility.patch ...
7 out of 7 hunks FAILED -- saving rejects to file ext/openssl/openssl.c. [ !! ]
 * ERROR: dev-lang/php-7.2.7::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/dev-lang/php-7.2.7/files/libressl-compatibility.patch
```

The patch `libressl-compatibility.patch` was intended to fix upstream [bug 76174](https://bugs.php.net/bug.php?id=76174), but it's no longer necessary (and conflicts, obviously) with php-7.2.7. So, you'll have to drop that patch from your ebuild.

Also feel free to remove the php-7.2.6 ebuild while you're at it. There's not much reason to keep around multiple versions of the unstable branch.

**Comment by Asgavar** [comment]
Sorry! It compiles now.

**Comment by hydrapolic** [comment]
In master https://github.com/gentoo/gentoo/commit/3950b5401883de03587875855c0f9d5c34560b21#diff-f32ea586d860e917ac6621180e1a4bb3

**Comment by Asgavar** [comment]
Well, no use in keeping this open then.

**Pull request closed without merging**
