### PR TITLE
dev-util/yuicompressor: adding package

### PR DESCRIPTION
**Pull request by hydrapolic**
https://bugs.gentoo.org/show_bug.cgi?id=500656

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
This ebuild contains two bundled jars:
`
>>> Preparing source in /var/tmp/portage/dev-util/yuicompressor-2.4.8/work ...
Searching for bundled jars:
/var/tmp/portage/dev-util/yuicompressor-2.4.8/work/yuicompressor-2.4.8/lib/rhino-1.7R2.jar
/var/tmp/portage/dev-util/yuicompressor-2.4.8/work/yuicompressor-2.4.8/lib/jargs-1.0.jar
`

**Comment by hydrapolic** [comment]
@monsieurp does not work with the latest rhino that is in portage :-(

**Comment by monsieurp** [comment]
Of course.

https://github.com/yui/yuicompressor#modified-rhino-files

YUI Compressor uses a modified version of the Rhino library (http://www.mozilla.org/rhino/) The changes were made to support JScript conditional comments, preserved comments, unescaped slash characters in regular expressions, and to allow for the optimization of escaped quotes in string literals.

**Comment by monsieurp** [comment]
@hydrapolic nah, we'll just leave the bundled jars as is.. we try to avoid this kind of situation but if there's no workaround then too bad.

**Comment by hydrapolic** [comment]
@monsieurp, well that explains it. I overlooked this.

**Comment by idella** [comment]
well looks fine at a glance

**Comment by monsieurp** [comment]
To be fair, I'm not comfortable adding this package to Portage. We can however add it to the Java overlay.

**Comment by hydrapolic** [comment]
Why @monsieurp?

**Pull request merged**
