### PR TITLE
gui-apps/waybar: Add support for sndio

### PR DESCRIPTION
**Pull request by lanodan**
Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

### CODE REVIEW

**Comment by JonasToth** [comment]
Thank you for the Patch!

Please adjust the whitespace in the diff to be consistent.

**Comment by ionenwks** [comment]
> Please adjust the whitespace in the diff to be consistent.

Hm, was just looking over the differences and I don't see what you're referring to. This is only using tabs and they're matching indenting.

**Comment by JonasToth** [comment]
Weird, maybe its a Bug from github on Smartphone



Checked with my laptop and I can't see anything bad either, sorry for the noise

**Review by ionenwks — APPROVED** [review]
Ah I see. Well, if that's all there was I assume that means you're fine with it then?

Patch looks simple and builds fine, so I'll go ahead with merging.

**Pull request closed without merging**
