### PR TITLE
[wip] dev-lang/nim: add 2.0.0

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/913623

### CODE REVIEW

**Comment by xgqt** [comment]
@listout 

Experimental patches do not apply anymore (`USE=experimental`).

Either way it fails to install for me:

```bash
Hint:  [Link]
Hint: mm: refc; threads: on; opt: speed; options: -d:release
113221 lines; 20.950s; 258.816MiB peakmem; proj: /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/nimble/src/nimble.nim; out: /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/bin/nimble [SuccessX]
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal.nim(53)            sysFatal
Error: unhandled exception: deps.nim(19, 3) `ok` git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas [AssertionDefect]
 * ERROR: dev-lang/nim-2.0.0::gentoo failed (compile phase):
 *   Failed to run command: ./koch tools
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 1372:  Called edo './koch' 'tools'
 *   environment, line  678:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "Failed to run command: $@"
 * 
```

**Comment by xgqt** [comment]
Those are the files in `dist` directory:

```bash
/var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/
├── checksums/
│   ├── README.md
│   ├── checksums.nimble
│   ├── src/
│   └── tests/
└── nimble/
    ├── changelog.markdown
    ├── ci/
    ├── config.nims
    ├── dist/
    ├── license.txt
    ├── nimble.bash-completion
    ├── nimble.nimble
    ├── nimble.zsh-completion
    ├── readme.markdown
    ├── src/
    ├── tests/
    └── todo.markdown
```

**Comment by listout** [comment]
> Either way it fails to install for me:

Do you mean install or compile? Cause it compiles fine for me https://0x0.st/HW-t.log and the install error is most probably due to not using sudo.

**Comment by xgqt** [comment]
If you are adding info please add a comment do not edit the last one.

> and the install error is most probably due to not using sudo.

That is correct for `src_install` since `dobin` requires root privs.

Try turning off ALL network connectivity (net interfaces) on your machine for time of emerging nim and see if you can get same error. If you have no net, then git clone should fail.

**Comment by listout** [comment]
Aha ... got it to reproduce
```
Hint:  [Link]
Hint: mm: refc; threads: on; opt: speed; options: -d:release
113221 lines; 6.653s; 258.785MiB peakmem; proj: /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/nimble/src/nimble.nim; out: /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/bin/nimble [SuccessX]
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal: unable to access 'https://github.com/nim-lang/atlas.git/': Could not resolve host: github.com
failed command: 'git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas', status: 128
fatal.nim(53)            sysFatal
Error: unhandled exception: deps.nim(19, 3) `ok` git clone -q https://github.com/nim-lang/atlas.git /var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0/dist/atlas [AssertionDefect]
 * ERROR: dev-lang/nim-2.0.0::gentoo failed (compile phase):
 *   Failed to run command: ./koch tools
 *
 * Call stack:
 *     ebuild.sh, line  136:  Called src_compile
 *   environment, line 1286:  Called edo './koch' 'tools'
 *   environment, line  592:  Called die
 * The specific snippet of code:
 *       "$@" || die -n "Failed to run command: $@"
 *
 * If you need support, post the output of `emerge --info '=dev-lang/nim-2.0.0::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-lang/nim-2.0.0::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/vbslogs/build/dev-lang/nim-2.0.0:20231001-175136.log'.
 * For convenience, a symlink to the build log is located at '/var/tmp/portage/dev-lang/nim-2.0.0/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-lang/nim-2.0.0/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0'
 * S: '/var/tmp/portage/dev-lang/nim-2.0.0/work/nim-2.0.0'
```

**Comment by xgqt** [comment]
@listout 

Now you see this is not unique :)

You will have to adjust your portage settings since this somehow passed via `emerge` for you.

**Comment by listout** [comment]
@xgqt did you see what the void devs did in https://github.com/void-linux/void-packages/commit/40a86587d4a956e607392eecdb348ecfd2e4ca22. Perhaps we could do something similar?

**Comment by xgqt** [comment]
> @xgqt did you see what the void devs did in [void-linux/void-packages@40a8658](https://github.com/void-linux/void-packages/commit/40a86587d4a956e607392eecdb348ecfd2e4ca22). Perhaps we could do something similar?

We do similar thing in few pkgs already - record git sha sums and then prevent the fetching.

You can base off of https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/clojure/clojure-1.11.1.ebuild in addition to Void's approach.

**Comment by CyberTailor** [comment]
I think we can just patch out "cloneDependency" calls from koch.nim

**Comment by CyberTailor** [comment]
Another option: write a replacement for Koch just for distro packaging needs. I don't think it should be an installable package, so it could be just stripped down upstream "koch.nim".

**Comment by CyberTailor** [comment]
I just looked and "boot()" function from "koch.nim" is just a few calls that could be inlined in the ebuild.

**Comment by CyberTailor** [comment]
If not ebuild, a new "nim-build.eclass" could be created.

**Pull request closed without merging**
