### PR TITLE
media-video/pitivi-0.98.1 add python:3.6 support

### PR DESCRIPTION
**Pull request by XVilka**

### CODE REVIEW

**Comment by monsieurp** [comment]
@XVilka please fix the QA warning.

**Comment by XVilka** [comment]
@monsieurp done.

**Comment by XVilka** [comment]
See https://bugs.gentoo.org/641780

**Comment by leio** [comment]
After nose2 is handled as talked about in bug, please rebase and add Closes: https://bugs.gentoo.org/641780 tag to the pitivi commit and please ping on the bugzilla bug. GNOME and GStreamer teams don't notice notifications from github, but bugzilla e-mail filtering and sorting is working very well.

**Comment by flappyports** [comment]
no activity

**Pull request closed without merging**
