### PR TITLE
media-fonts/ipamonafont: update HOMEPAGE and SRC_URI

### PR DESCRIPTION
**Pull request by shimataro**
Update source URL because hosting service (geocities.jp) is out of service.

### CODE REVIEW

**Comment by wimmuskee** [comment]
Hi, the commit messages needs a signoff line to be accepted. Also, if accepted, this PR closes bug [682546](https://bugs.gentoo.org/682546), so you can add a line in the commit message for that as well.

See the [specification](https://www.gentoo.org/glep/glep-0066.html#commit-messages) for more info.

**Comment by shimataro** [comment]
@wimmuskee 
Oops, sorry.
Is this OK? 7f9f3a8

**Comment by wimmuskee** [comment]
Nope, you should delete that last commit, and amend the commit message for the actual commit. 

Do a "git commit --amend", and make sure the first line is the main commit message: media-fonts/ipamonafont .....

Leave the the second line blank, and add the **Signed-off-by** line and the **Closed** line. Save the commit, and do a git push force to your own branch, that should update the PR.

If you're unsure, look at other PR's without the green "no signoff" and with the pink "bug linked" flags. Also, read the "Copyright policy change" in this ticket.

**Comment by shimataro** [comment]
@wimmuskee 
Thank you for your kind instruction.
How about this? 5b8369e 
<https://github.com/gentoo/gentoo/pull/12579/commits>

**Comment by wimmuskee** [comment]
Looks good. 

"In order to force reassignment and/or bug reference scan, please append [please reassign] to the **pull request** title."  (edit button at top of this PR; if everything is allright, the missing data flags will be gone)

After that, it's up to the Gentoo devs, but at least your PR is correct. Patience is a virtue :) , sometimes it's pulled in a couple of hours, sometimes it takes a few months.

**Pull request closed without merging**
