### PR TITLE
x11-misc/light-locker: Support >=systemd-209

### PR DESCRIPTION
**Pull request by YukiOhtsuka**
Currently, emerge fails on configure phase saying below:

> checking for SYSTEMD... no
> configure: error: Systemd support explicitly required, but systemd not found

light-locker is depending on libsystemd-login. This library is, however, merged
into libsystemd as of systemd 209.

This patch fix configure.ac to refer libsystemd instead of libsystemd-login.

https://github.com/the-cavalry/light-locker/issues/64
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=779749

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by monsieurp** [comment]
@Calchan

**Comment by monsieurp** [comment]
@mgorny might be of assistance with all things systemd related.

**Comment by diogocp** [comment]
You should submit this upstream too.

**Comment by YukiOhtsuka** [comment]
How about this one?
What can I do to get this merged?

**Comment by YukiOhtsuka** [comment]
sorry. I am not sure if I have made a correct report to merge github.

**Comment by Calchan** [comment]
Can you please post your patch at https://bugs.gentoo.org/show_bug.cgi?id=588894 ?

I don't have access to merge PRs here. Also, bugs.gentoo.org is our official way of following up on bugs and development.

Thanks,
Calchan.

**Comment by monsieurp** [comment]
@YukiOhtsuka I'm going to have to close this PR I'm afraid :(. Could you file a new one? Also please do not merge master back into your new branch and then push. It messes up everything.

**Comment by Calchan** [comment]
FYI, I have just bumped  light-locker in the Gentoo tree and it says it supports "new" systemd. Please check it and file a bug on bugs.gentoo.org if you find problems with it.

**Comment by YukiOhtsuka** [comment]
Sorry, I couldn't answer your comment until now.
I made patch(https://bugs.gentoo.org/show_bug.cgi?id=588894).
I verify it, and it is no probrem.

2017-07-29 2:08 GMT+09:00 Calchan <notifications@github.com>:

**Pull request closed without merging**
