### PR TITLE
sci-biology/abyss: ebuild tweaks

### PR DESCRIPTION
**Pull request by mmokrejs**

### CODE REVIEW

**Comment by a17r** [comment]
Please never merge master into your PR branch. Remove all commits except your own changes, and force-push over the remote branch.

**Comment by mmokrejs** [comment]
Sorry Andreas, I will never learn how to handle the git. Please send me the commands I could copy&paste to undo this mess. I am unable to understand the docs and various forums.

**Comment by a17r** [comment]
It does not make sense without your own interaction, you need to understand the commands. Please for now just delete your branch, and redo your change with a new PR. Then simply never ever merge master into a PR again.

**Comment by a17r** [comment]
Before you create any new branch, make sure `HEAD` has not diverged from upstream/master.
`git pull --rebase upstream master`

**Comment by mmokrejs** [comment]
Thank you, the `upstream master` was the thing I was failing to find by Google. The page https://wiki.gentoo.org/wiki/Github_Pull_Requests should include what is one supposed to do after returning to git tree a few months later. The example only teaches how to start from scratch, but not how to *re-start*.

Anyway:

```
$ git pull --rebase upstream master
remote: Counting objects: 5, done.
remote: Total 5 (delta 4), reused 5 (delta 4), pack-reused 0
Unpacking objects: 100% (5/5), done.
From https://github.com/gentoo/gentoo
 * branch                    master     -> FETCH_HEAD
   f25169de9a9..a659d0f7588  master     -> upstream/master
First, rewinding head to replay your work on top of it...
Applying: kde-frameworks/knotifications: Re-add USE=dbus fix
Applying: dev-python/graph-tool: amd64 stable wrt bug #606076
Using index info to reconstruct a base tree...
M	dev-python/graph-tool/graph-tool-2.19.ebuild
Falling back to patching base and 3-way merge...
Auto-merging dev-python/graph-tool/graph-tool-2.19.ebuild
CONFLICT (content): Merge conflict in dev-python/graph-tool/graph-tool-2.19.ebuild
error: Failed to merge in the changes.
Patch failed at 0002 dev-python/graph-tool: amd64 stable wrt bug #606076
The copy of the patch that failed is found in: .git/rebase-apply/patch

Resolve all conflicts manually, mark them as resolved with
"git add/rm <conflicted_files>", then run "git rebase --continue".
You can instead skip this commit: run "git rebase --skip".
To abort and get back to the state before "git rebase", run "git rebase --abort".
```

It is still the same story. I will just `rm -rf ./gentoo` and zap the forked repo on my github saying `This branch is 39573 commits ahead, 56096 commits behind gentoo:master. `, and loose my past attempts which were also rejected with words like "please rebase". As you can see, I am not learning, sorry.

```
$ git branch -l
  Parallel_Studio_XE_2017
  add_hmmer_slot
  ghostscript-gpl_fix_EPREFIX
  master
  velvet_variables
```

BTW, all examples how toclone repo. make a branch, enter a branch, commit, submit a pull request should continue mandatorily with:

`git checkout master`

because everybody just forgets and remains in the branch. So many people have merged multiple patches into same pull request.

**Pull request closed without merging**
