### PR TITLE
app-crpyt/tpm2-tss: Enable libressl support

### PR DESCRIPTION
**Pull request by salahcoronya**
libressl support was removed form the this package previously because libressl did not support some functions needed: https://github.com/tpm2-software/tpm2-tss/issues/1235 . Now, however, this no longer seems to be a problem, and it compiles just fine with the current stable.

### CODE REVIEW

**Comment by PPed72** [comment]
Tests do not compile (at least for 2.4.5-r1):
/bin/sh ./libtool  --tag=CC   --mode=link x86_64-pc-linux-gnu-gcc  -I./src -I./include/tss2 -I./test/fuzz/tcti     -I./src/tss2-mu -I./src/tss2-sys -I./src/tss2-esys -I./src/tss2-fapi -Wno-unused-parameter -Wno-missing-field-initializers   -O2 -pipe -frecord-gcc-switches -march=amdfam10 -flto=4 -fno-lto  -lcrypto  -Wl,--wrap=Tss2_TctiLdr_Initialize -Wl,--wrap=Tss2_TctiLdr_Finalize -Wl,-O1 -Wl,--as-needed -Wl,--hash-style=gnu -Wl,--sort-common -flto=4 -fno-lto -o test/unit/esys-nulltcti test/unit/esys_nulltcti-esys-nulltcti.o src/tss2-esys/test_unit_esys_nulltcti-esys_context.o src/tss2-esys/test_unit_esys_nulltcti-esys_iutil.o src/tss2-esys/test_unit_esys_nulltcti-esys_crypto.o src/tss2-esys/test_unit_esys_nulltcti-esys_crypto_ossl.o -lcmocka      src/tss2-mu/libtss2-mu.la src/tss2-tcti/libtss2-tctildr.la src/tss2-tcti/libtss2-tcti-device.la  src/tss2-sys/libtss2-sys.la src/tss2-esys/libtss2-esys.la src/tss2-rc/libtss2-rc.la src/tss2-fapi/libtss2-fapi.la -lcrypto  libutil.la  -ldl  
src/tss2-esys/.libs/libtss2-esys.so: error: undefined reference to 'RAND_OpenSSL'
src/tss2-esys/.libs/libtss2-esys.so: error: undefined reference to 'EC_POINT_get_affine_coordinates'
src/tss2-esys/.libs/libtss2-esys.so: error: undefined reference to 'EC_POINT_set_affine_coordinates'
collect2: error: ld returned 1 exit status
distcc[1981] ERROR: compile (null) on localhost failed
make[1]: *** [Makefile:12278: test/unit/tctildr-dl] Error 1
make[1]: *** Waiting for unfinished jobs....

**Comment by PPed72** [comment]
Same for 3.0.3-r1...

**Comment by salahcoronya** [comment]
Ok, after more compile testing I finally got that it compiles the tests, as well as tpm2-tools. tpm2-tools needs a patch which can be found in a different PR of mine: https://github.com/gentoo/gentoo/pull/18721 . Of course this may be pointless given the current discussion on the mailing list: https://archives.gentoo.org/gentoo-dev/message/9a92320c599e63c8c18b2ed29050f22f

**Review by juippis — COMMENTED** [review]
Yeah, I don't think we want to **introduce** libressl support anymore. **Fixing** it is different thing.

**Comment by salahcoronya** [comment]
Yeah, I'll go ahead and close this and mark the corresponding bug WONTFIX, but include the patches in the bug so if its desired to submit them upstream or in an overlay they will be available.

**Pull request closed without merging**
