### PR TITLE
media-video/aegisub: add new snapshot and enable tests

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @monsieurp.

**Comment by mgorny** [comment]
First comment: masking `test` flag does not guarantee disabling the tests. You can do `RESTRICT="x86? ( test )"`, I think (please test).

**Comment by Coacher** [comment]
@mgorny, right. I forgot about this "feature".

**Comment by monsieurp** [comment]
LGTM.

**Comment by Coacher** [comment]
I still should work on that RESTRICT thing.
In any case thank you, @monsieurp

**Comment by Coacher** [comment]
> I still should work on that RESTRICT thing.

Tests aren't built and silently skipped with USE='-test'.
Thus it isn't necessary to additionally RESTRICT them on x86.
All is good as it is now.

**Pull request closed without merging**
