### PR TITLE
media-libs/openexr: replace 3.2.2 with 3.2.3

### PR DESCRIPTION
**Pull request by Jamim**
_Hello everyone,_

**OpenEXR** 3.2.3 [was released](https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.2.3) recently. The changes are mostly about fixes.
It would be nice to have it in the Portage tree.

_These changes also:_
  - fix/simplify handling of the `test` USE flag
  - fix handling of the `examples` USE flag
  - improve handling of the `doc` USE flag
  - fix the `RDEPEND`

Closes: https://bugs.gentoo.org/925128
Closes: https://bugs.gentoo.org/925198

_Best regards!_

### CODE REVIEW

**Comment by Jamim** [comment]
_Hello @arthurzam,_

Would you mind reviewing this PR? It bumps **OpenEXR** which is [related](https://imath.readthedocs.io/en/latest/#imath) to **Imath** that you helped to update recently.

_Thanks in advance!_

**Comment by Jamim** [comment]
_Hello @negril,_

I suppose this PR might be interesting to you taking into account your previous work on OpenEXR and other packages related to [Academy Software Foundation](https://github.com/AcademySoftwareFoundation).

_Best regards!_

**Comment by negril** [comment]
Can you change the `RDEPEND` to `app-arch/libdeflate[zlib]`, see https://bugs.gentoo.org/925198#c9?

You can then change `Bug: https://bugs.gentoo.org/925128` to `Closes: https://bugs.gentoo.org/925128`. And add `Closes: https://bugs.gentoo.org/925198` so the Bugs are closed on merge.

other wise lgtm. Thanks!

**Comment by Jamim** [comment]
Thank you for the review, @negril! 🙇🏼

I've updated the `RDEPEND` as you suggested.
However, I don't think `Closes:` should be used in this case since this PR doesn't fix corresponding issues for older versions of OpenEXR which remains in the Portage tree.

**Comment by negril** [comment]
It fixes them by making them obsolete. `3.2.2` can't get stabilised due to the bugs anyway. And I'd have to close the bugs after this is merged by hand.

Thinking about it you could even remove the old version in this PR, or git move the `3.2.2` ebuild to the `3.2.3` ebuild.

**Comment by Jamim** [comment]
_Hello @negril,_
I've updated the PR, so now it replaces `3.2.2` with `3.2.3`.

**Comment by Jamim** [comment]
_Hello @lu-zero,_

While @waebbl is not responding, would you mind reviewing this PR or suggesting a relevant person who can do so?
I'm asking you since you are mentioned as a lead of [Project:Video](https://wiki.gentoo.org/wiki/Project:Video).

_Thanks in advance!_

**Comment by Jamim** [comment]
> Can you rebase to master and incorporate the changes in #35800 please?

Sure, I've rebased it onto the `master` branch. Thank you, @negril!

**Comment by negril** [comment]
lgtm

**Pull request closed without merging**
