### PR TITLE
cmake-multilib: drop cmake-utils support

### PR DESCRIPTION
**Pull request by a17r**
Quoting @jkroonza:
> Note to others: The CMAKE_ECLASS flag with this commit now defaults to cmake for all EAPI versions, cmake-utils was no longer functional either way (eclass no longer in tree). This just brings all into alignment with that reality.

See also: https://archives.gentoo.org/gentoo-dev/message/d6df88f6bec85ef7324a0e22590bfbd5

### CODE REVIEW

**Review by jkroonza — APPROVED** [review]
W.r.t mariadb-connector-odbc.

Note to others:  The CMAKE_ECLASS flag with this commit now defaults to cmake for all EAPI versions, cmake-utils was no longer functional either way (eclass no longer in tree).  This just brings all into alignment with that reality.

**Review by sarnex — APPROVED** [review]
Sorry for late reply. shaderc change looks good

**Review by mattst88 — APPROVED** [review]
Looks good for x11@ packages.

**Review by chewi — APPROVED** [review]

**Review by sarnex — APPROVED** [review]

**Review by juippis — APPROVED** [review]
Thanks!

**Review by mgorny — APPROVED** [review]
LGTM for everything.

**Pull request merged**
