### PR TITLE
kicad maintenance

### PR DESCRIPTION
**Pull request by zpuskas**
- sci-electronics/kicad-meta: drop 7.0.8
- sci-electronics/kicad-meta: drop 7.0.9
- sci-electronics/kicad: drop 7.0.8-r1
- sci-electronics/kicad: drop 7.0.9
- sci-electronics/kicad-footprints: drop 7.0.8
- sci-electronics/kicad-footprints: drop 7.0.9
- sci-electronics/kicad-packages3d: drop 7.0.8
- sci-electronics/kicad-packages3d: drop 7.0.9
- sci-electronics/kicad-symbols: drop 7.0.8
- sci-electronics/kicad-symbols: drop 7.0.9
- sci-electronics/kicad-templates: drop 7.0.8
- sci-electronics/kicad-templates: drop 7.0.9
- app-doc/kicad-doc: drop 7.0.8
- app-doc/kicad-doc: drop 7.0.9
- sci-electronics/kicad: add 7.0.11
- sci-electronics/kicad: add 8.0.1
- sci-electronics/kicad-footprints: add 7.0.11
- sci-electronics/kicad-footprints: add 8.0.1
- sci-electronics/kicad-packages3d: add 7.0.11
- sci-electronics/kicad-packages3d: add 8.0.1
- sci-electronics/kicad-symbols: add 7.0.11
- sci-electronics/kicad-symbols: add 8.0.1
- sci-electronics/kicad-templates: add 7.0.11
- sci-electronics/kicad-templates: add 8.0.1
- app-doc/kicad-doc: add 7.0.11
- app-doc/kicad-doc: add 8.0.1
- sci-electronics/kicad-meta: add 7.0.11
- sci-electronics/kicad-meta: add 8.0.1

### CODE REVIEW

**Comment by zpuskas** [comment]
I've added 7.0.11 as it's a bugfix to the 7 series and some people in industry might want to use 7 series a bit longer before migrating to 8 series.

**Comment by vowstar** [comment]
Thank you for your maintenance. I agree with your point of view. There are still many people using 7.0.x to complete their work in serious production environments.

**Comment by zpuskas** [comment]
Please don't merge yet, I've found that test still fails. I have a fix, I'm in progress back testing it. Will update the PR with an additional commit in ~1 hour.

**Comment by zpuskas** [comment]
Done, ready to merge.

**Comment by dlan17** [comment]
btw, strictly, mkdir also need "||die", I just fixed it & pushed, thanks

**Pull request closed without merging**
