### PR TITLE
net-misc/yt-dlp: add official HOMEPAGE

### PR DESCRIPTION
**Pull request by youngunix**
updated the ebuilds with the official HOMEPAGE (landing page).

### CODE REVIEW

**Comment by ionenwks** [comment]
Isn't it a bit early? I mean I see the (still open) https://github.com/yt-dlp/yt-dlp/issues/8632 but there's no reference to it in the repo's description nor README.md, and [pypi](https://pypi.org/project/yt-dlp/) still lists github as the homepage at the moment.

I don't think I want to take it as "official" downstream when upstream hasn't really taken it in yet.

**Comment by youngunix** [comment]
> Isn't it a bit early? I mean I see the (still open) [yt-dlp/yt-dlp#8632](https://github.com/yt-dlp/yt-dlp/issues/8632) but there's no reference to it in the repo's description nor README.md, and [pypi](https://pypi.org/project/yt-dlp/) still lists github as the homepage at the moment.
> 
> I don't think I want to take it as "official" downstream when upstream hasn't really taken it in yet.

We are working on those areas with the developer. I'll update this PR once the other ones are finalized. Thanks

**Comment by ionenwks** [comment]
Alright then, I'll wait.

That aside, for when it's time to merge, please squash the commits (updating HOMEPAGE is normally done in a single commit for all ebuilds within a same package), and drop the likely added by mistake bluefish bump/manifest commit (it's okay to force push for a PR here).

Commit summaries should also be prefixed with the package, e.g. `net-misc/yt-dlp: update HOMEPAGE`

If unfamiliar with git, I could trivially fix these issues on merge though.

**Comment by youngunix** [comment]
We have failed to come to an agreement with the developer and will not proceed with this endeavor.

**Pull request closed without merging**
