### PR TITLE
x11-misc/cbatticon: version bump to 1.5.0

### PR DESCRIPTION
**Pull request by hasufell**
@gentoo/desktop-misc

### CODE REVIEW

**Comment by hasufell** [comment]
@mgorny how does this work with herds?

**Comment by mgorny** [comment]
You go into admin and create the team :P. Since you aren't infra, you ask me to create the team for you.

**Comment by hasufell** [comment]
> Since you aren't infra, you ask me to create the team for you.

I ask you to create them for me.

**Comment by mgorny** [comment]
@gentoo/desktop-misc. Put whoever was in herds.xml, let's hope this file was actually up-to-date.

**Pull request closed without merging**
