### PR TITLE
cmake.eclass EAPI-7 stragglers cleanup

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
ACK for net-libs/libad9361-iio, thanks!

**Review by Chiitoo — APPROVED** [review]
Thanks again!

**Comment by janhenke** [comment]
Hi,
I got subscribed as dec-cpp/ms-gsl maintainer. But I no longer see that package mentioned. Can you confirm if this PR still affects my package?

**Comment by a17r** [comment]
@janhenke cleanup of your package is blocked by old telegram: https://bugs.gentoo.org/887547

**Comment by misanthropos** [comment]
You could drop the string-theory-3.5 commit. I have a new PR for 3.6

**Comment by a17r** [comment]
@misanthropos do not add and drop ebuilds in the same commit. since you'll have to rebase your PR anyway, shall I pick my change to ::gentoo right away?

**Comment by misanthropos** [comment]
> @misanthropos do not add and drop ebuilds in the same commit. since you'll have to rebase your PR anyway, shall I pick my change to ::gentoo right away?
Yeah. I will create a new PR for 3.6 then.

**Comment by a17r** [comment]
> > Yeah. I will create a new PR for 3.6 then.

@misanthropos Not necessary, just force-push!

**Comment by thesamesam** [comment]
Please leave ccache for now, there's a reported bug (which I need to reassign) which may be a regression

**Comment by hansfn** [comment]
featherpad will be fixed in #28755.

**Comment by a17r** [comment]
> featherpad will be fixed in #28755.

I would prefer a simple ACK rather than every single maintainer open their own PR to redo the work, but hey.

**Comment by hansfn** [comment]
> > featherpad will be fixed in #28755.
> 
> I would prefer a simple ACK rather than every single maintainer open their own PR to redo the work, but hey.

The PR adds a new version and at the same time removes the old versions. Posting here was just for information.

**Comment by arkamar** [comment]
ACK `mail-filter/rspamd`

**Comment by stkw0** [comment]
ACK dev-libs/poco

**Comment by thesamesam** [comment]
ok for ntirpc

**Review by Flowdalic — APPROVED** [review]

**Comment by DarkDefender** [comment]
ok for oidn (and I this osl is ok too, unless redchillipadi has any objections)

**Pull request merged**
