### PR TITLE
net-misc/cfengine: version bump 3.12.2

### PR DESCRIPTION
**Pull request by crorvick**
3.12 is the latest LTS release.

### CODE REVIEW

**Comment by Whissi** [comment]
Are you still using Gentoo and are interested in cfengine?

I am asking because cfengine in Gentoo is really outdated and when reading current bugs we don't have a version in repository which should become stable. However, current cfengine versions are blocking openssl removal. If nobody is interested in maintaining this package we will probably have to last-rite package.

**Comment by ajakk** [comment]
Seems like no one is there. :(

**Comment by crorvick** [comment]
On Thu, Mar 25, 2021 at 11:58 AM ajakk ***@***.***> wrote:

> Seems like no one is there. :(
>

Sorry, I forgot to respond.  I'm here.  I've tried contributing to
net-misc/cfengine but it's very hard to get anything through.  Would be
happy to help if contributions will get picked up.

**Comment by crorvick** [comment]
> Are you still using Gentoo and are interested in cfengine?
> 
> I am asking because cfengine in Gentoo is really outdated and when reading current bugs we don't have a version in repository which should become stable. However, current cfengine versions are blocking openssl removal. If nobody is interested in maintaining this package we will probably have to last-rite package.

I am interested but how do I ensure my contributions are worth the effort?  It seems a bit disingenuous to let version bumps go stale over more than a year and then decide they are not suitable  What needs to happen to allow contributions through in a timely fashion?

**Comment by ajakk** [comment]
> What needs to happen to allow contributions through in a timely fashion?

An important part of this is timely response to comments on your pull requests. If you're still interested in this, we need to ensure that it can merge properly (there seems to be a merge conflict) and address the open bugs. You should also update this PR to bump to the current newest version of cfengine.

**Comment by crorvick** [comment]
> An important part of this is timely response to comments on your pull requests.

Huh?  Are you referring to the "are you still interested in cfengine ... we will probably have to last-rite package" comment?  That was posted over a year after pull request.  I'm asking how to better engage with the gatekeepers to get contributions through in a timely fashion.  Clearly waiting 15 months for a response is a completely broken process regardless of whether I replied immediately or not.

**Comment by crorvick** [comment]
> If you're still interested in this, we need to ensure that it can merge properly (there seems to be a merge conflict) and address the open bugs.

The open bugs look trivial to resolve.  I will push a new version bump along with fixes in the next few days.

**Comment by ajakk** [comment]
Sorry, I missed the time separation between the PR opening and that comment. In this case, you got really unlucky with this contribution because the maintainer of cfengine (the sysadmin project) is not that active, and without anyone on that team looking for PRs assigned to them this PR was easy to disappear in the sea of PRs. If you have a PR sit this long in the future you can try contacting the proxy-maint team, a great way to do this is by asking for someone to look at the PR in #gentoo-proxy-maint on Freenode.

**Comment by ajakk** [comment]
> The open bugs look trivial to resolve. I will push a new version bump along with fixes in the next few days.

Ping?

**Comment by crorvick** [comment]
Porting the SSL fixes turned out to be fairly involved and took longer than
expected, so needed to table this.  Spring and summer is really busy atm
but will probably pick this up in the next few weeks.

**Comment by ajakk** [comment]
Ping?

**Comment by arkamar** [comment]
The package was removed from the tree in commit 36937c9304bd - `net-misc/cfengine: treeclean`

**Pull request closed without merging**
