### PR TITLE
dev-perl/Gtk3: bump to 0.38.0 and EAPI 7

### PR DESCRIPTION
**Pull request by cjmayo**
Closes: https://bugs.gentoo.org/711366
Package-Manager: Portage-3.0.17, Repoman-3.0.2
Signed-off-by: Chris Mayo <aklhfex@gmail.com>

---

```diff
--- Gtk3-0.34.0.ebuild
+++ Gtk3-0.38.0.ebuild
@@ -1,15 +1,15 @@
-# Copyright 1999-2019 Gentoo Authors
+# Copyright 1999-2021 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=6
+EAPI=7
 DIST_AUTHOR=XAOC
-DIST_VERSION=0.034
+DIST_VERSION=0.038
 inherit perl-module virtualx
 
 DESCRIPTION="Perl interface to the 3.x series of the gtk+ toolkit"
 LICENSE="LGPL-2.1+"
 SLOT="0"
-KEYWORDS="amd64 x86"
+KEYWORDS="~amd64 ~x86"
 IUSE="test"
 RESTRICT="!test? ( test )"
 
@@ -28,11 +28,6 @@
 	)
 "
 
-PATCHES=(
-	# Fixed in next version, bug #683046
-	"${FILESDIR}"/${P}-gdk-pixbuf-test.patch
-)
-
 src_test() {
 	virtx perl-module_src_test
 }
```

### CODE REVIEW

**Comment by thesamesam** [comment]
Hmm:
```
>>> Test phase: dev-perl/Gtk3-0.34.0
 * Scanning for an open DISPLAY to start Xvfb ...
 * Starting Xvfb on $DISPLAY=10 ...
 * Test::Harness Jobs=4
make -j4 test TEST_VERBOSE=0
PERL_DL_NONLAZY=1 "/usr/bin/perl" "-MExtUtils::Command::MM" "-MTest::Harness" "-e" "undef *Test::Harness::Switches; test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/signals.t .................... No subtests run
t/00-init.t .................... Failed 16/16 subtests
t/floating-refs.t .............. No subtests run
t/overrides.t .................. No subtests run
t/vfuncs-double-setup.t ........ No subtests run
t/zz-GdkEvent.t ................ No subtests run
t/zz-GtkActionGroup.t .......... No subtests run
t/vfuncs-destroy.t ............. No subtests run
t/zz-GtkBuilder.t .............. No subtests run
t/zz-GtkCellLayoutIface.t ...... No subtests run
t/zz-GtkContainer.t ............ No subtests run
t/zz-GtkCellRendererIface.t .... No subtests run
t/zz-GtkDialog.t ............... No subtests run
t/zz-GtkImage.t ................ No subtests run
t/zz-GtkInfoBar.t .............. No subtests run
t/zz-GtkRadioAction.t .......... No subtests run
t/zz-GtkRadioButton.t .......... No subtests run
t/zz-GtkRadioMenuItem.t ........ No subtests run
t/zz-GtkRadioToolButton.t ...... No subtests run
t/zz-GtkRecentChooserDialog.t .. No subtests run
t/zz-GtkTextBuffer.t ........... No subtests run
t/zz-GtkTreeModelIface.t ....... No subtests run

Test Summary Report
-------------------
t/signals.t                  (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/00-init.t                  (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: Bad plan.  You planned 16 tests but ran 0.
t/floating-refs.t            (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/overrides.t                (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/vfuncs-double-setup.t      (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GdkEvent.t              (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkActionGroup.t        (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/vfuncs-destroy.t           (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkBuilder.t            (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkCellLayoutIface.t    (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkContainer.t          (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkCellRendererIface.t  (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkDialog.t             (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkImage.t              (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkInfoBar.t            (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkRadioAction.t        (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkRadioButton.t        (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkRadioMenuItem.t      (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkRadioToolButton.t    (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkRecentChooserDialog.t (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkTextBuffer.t         (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
t/zz-GtkTreeModelIface.t     (Wstat: 15 Tests: 0 Failed: 0)
  Non-zero wait status: 15
  Parse errors: No plan found in TAP output
Files=22, Tests=0,  2 wallclock secs ( 0.05 usr  0.06 sys +  4.62 cusr  1.13 csys =  5.86 CPU)
Result: FAIL
Failed 22/22 test programs. 0/0 subtests failed.
make: *** [Makefile:834: test_dynamic] Error 255
emake failed
```

But 0.34.0 fails too.

**Comment by cjmayo** [comment]
That looks like the log for 0.34.0:

> ```
> >>> Test phase: dev-perl/Gtk3-0.34.0
> ```

0.34.0 does fail for me:

```
t/zz-GtkDialog.t ............... ok                                     
===(     702;0   37/233  0/? )==========================================
Can't find information for method TreeModel::sort_new_with_model at t/overrides.t line 466.
# Looks like your test exited with 255 just after 112.
```

but that was fixed in 0.37.0:
https://gitlab.gnome.org/GNOME/perl-gtk3/-/blob/ac5ace1e5839b992693fad13ebdc08ec7cab1876/NEWS#L13

and all tests pass for me in 0.38.0.

**Comment by cjmayo** [comment]
I'm using amd64 stable dev-lang/perl-5.30.3.

There is a report of similar errors on Windows with perl-5.32.0:
https://gitlab.gnome.org/GNOME/perl-gtk3/-/issues/9

**Comment by cjmayo** [comment]
dev-perl/Gtk3-0.38.0 now in the tree.

**Pull request closed without merging**
