### PR TITLE
dev-lang/*: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from dev-lang.
Please review.

### CODE REVIEW

**Comment by floppym** [comment]
I think there are too many unrelated packages here, and this requires review by individual maintainers.

**Comment by mm1ke** [comment]
I do think too the QA checks are unrelated to my PR. Anyway, anything i should change with my PR so reviewing will be easier?

**Comment by floppym** [comment]
If you can split the pull request based on maintainer instead of by the package category, that would be helpful. Also, if you can @ mention the maintainer on each pull request, that's less work we have to do.

**Comment by mm1ke** [comment]
I'll gonna close this PR.
I did split this PR for each maintainer and created another PR for packages were i couldn't find a maintainer (which is on github). I hope this helps :)

**Pull request closed without merging**
