### PR TITLE
dev-lang/julia: include ${EPREFIX} in install prefix

### PR DESCRIPTION
**Pull request by crorvick**
Bug: http://bugs.gentoo.org/651954

### CODE REVIEW

**Comment by flappyports** [comment]
No activity in 45+ days.

**Comment by crorvick** [comment]
@flappyports, exactly what activity were you looking for?

**Comment by flappyports** [comment]
@crorvick For it to be merged or the maintainer to do something with it.  Provide feedback etc.

**Comment by flappyports** [comment]
@crorvick I would suggest finding someone on the respective team and pinging them.

**Pull request closed without merging**
