### PR TITLE
dev-util/reuse: new package, add 2.1.0

### PR DESCRIPTION
**Pull request by jonasstein**
@python comments are appreciated
note to myself: Remember to add
Closes: https://bugs.gentoo.org/715158

### CODE REVIEW

**Comment by ulm** [comment]
Ebuild written in today's Gentoo e.V. workshop, teamwork by @jonasstein, @hamarituc, and @ulm. :smile:

**Comment by thesamesam** [comment]
You want @gentoo/python.

**Review by thesamesam — APPROVED** [review]
Looks ok.

**Comment by jonasstein** [comment]
merged. Closing.

**Pull request closed without merging**
