### PR TITLE
dev-java/logback-core: dependency updates | dev-java/jakarta-servlet-api: new package, add 4.0.4

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by dwfreed** [comment]
Shouldn't the different servlet API providers block each other? Since presumably they provide the same files.  Also shouldn't jakarta-servlet-api be added to the servlet-api virtual?  And if both of these questions are correct, then the logback-core dependency shouldn't change, as something else on the system may require the tomcat or resin version of the servlet API.

**Comment by Flowdalic** [comment]
Also, pleased drop the keywords instead of masking them.

**Comment by vaukai** [comment]
> Also, pleased drop the keywords instead of masking them.

Keywords dropped as requested.

**Comment by vaukai** [comment]
> Shouldn't the different servlet API providers block each other? 

Isn't that question completely independent from this PR? Maybe better be discussed on IRC?

**Comment by Flowdalic** [comment]
> > Shouldn't the different servlet API providers block each other?
> 
> Isn't that question completely independent from this PR? Maybe better be discussed on IRC?

Since it is related to a new package this PR adds, it seems sensible to discuss it here. That said dev-java/jakarta-servlet-api installs

```
/usr/share/jakarta-servlet-api-4/package.env
/usr/share/jakarta-servlet-api-4/lib/jakarta-servlet-api.jar
/usr/share/doc/jakarta-servlet-api-4.0.4/README.md.bz2
/usr/share/doc/jakarta-servlet-api-4.0.4/CONTRIBUTING.md.bz2
/usr/share/doc/jakarta-servlet-api-4.0.4/NOTICE.md.bz2
```

so there shouldn't be a file collision with the other servlet API providers. So merging this should be fine.

We can later discuss if logback-core gets a dependency like `|| ( dev-java/jakarta-servlet-api java-virtuals/servlet-api )` and/or if we add jakarta-servlet-api as provider for java-virtuals/servlet-api. Ideally we would do both.

**Pull request closed without merging**
