### PR TITLE
app-misc/anki: version bump to 2.1.11

### PR DESCRIPTION
**Pull request by kamillys**
Bug: https://bugs.gentoo.org/652000

### CODE REVIEW

**Comment by a17r** [comment]
Please `git pull --rebase` on top of git master. Also, you can add `Bug:` reference in git summary to https://bugs.gentoo.org/652000

**Comment by kamillys** [comment]
Ping @a17r

**Comment by a17r** [comment]
It's not for me to merge this. The package has a maintainer, @patricklauer

**Comment by ljakab** [comment]
How can we get this moving if @patricklauer is not responsive?

**Comment by juippis** [comment]
The maintainer doesn't use Github at all, and apparently has trouble viewing bugs too. This package is already updated to the latest version in Gentoo tree (without closing the bug), so sorry your contribution was ignored, but nothing could be done here :\

**Comment by kamillys** [comment]
Nah, happens. I (and probably some other people) just wanted this package to be bumped so I am happy that it is updated in main repo. However it is kinda sad that I am unable to reach maintainer to help keeping packages up to date.

**Comment by juippis** [comment]
There are few devs who isolate themselves from all platforms. If nothing else seems to be working, e-mailing them directly might... Hope this one incident wont stop you from contributing. Bad luck you stumpled upon someone who's not communicating, but most of the maintainers are open for help :)

**Pull request closed without merging**
