### PR TITLE
dev-util/pkgconf: bump to 1.3.5

### PR DESCRIPTION
**Pull request by doughdemon**
Just renamed version 1.2.2 ebuild

### CODE REVIEW

**Comment by Dessa** [comment]
is there a reason why this isn't 1.3.5?

**Comment by doughdemon** [comment]
> is there a reason why this isn't 1.3.5?

No, that was just oversight. It's fixed now. Thanks.

**Comment by mgorny** [comment]
It seems that the bump was done independently.

**Comment by floppym** [comment]
Sorry, it's probably better to ping me on IRC or via Bugzilla; I don't pay close attention to github.

**Pull request closed without merging**
