### PR TITLE
app-shells/thefuck: bump to 3.28

### PR DESCRIPTION
**Pull request by aphypnise**
Also added python 3.7 as supported version.

Package-Manager: Portage-2.3.54, Repoman-2.3.12
Signed-off-by: Andrew Attali <me@aphypnise.eu>

### CODE REVIEW

**Comment by holgersson32644** [comment]
Thanks for your submission! I'm currently lacking time to manage my ebuilds, so do you want to take ove the proxied maintenance of this one?

As far as I can tell the ebuild itself is fine and working for python2_7 and python3_6, but I have no python3_7 yet. Can you please paste the output of running tests with python3_7?

**Comment by aphypnise** [comment]
Tests done and are successful, I've attached the logs.

I don't mind to take over the proxied maintenance, but I don't know what's the procedure for the metadata.xml, if I just need to add myself, is there is a "former maintainer" tag or something like that.

[test.log](https://github.com/gentoo/gentoo/files/2736552/test.log)

**Comment by holgersson32644** [comment]
> Tests done and are successful, I've attached the logs.
> 
> I don't mind to take over the proxied maintenance, but I don't know what's the procedure for the metadata.xml, if I just need to add myself, is there is a "former maintainer" tag or something like that.
> 
> [test.log](https://github.com/gentoo/gentoo/files/2736552/test.log)

Thanks, looks good (however, a dev has to merge it as I can't do it).
To become a proxied maintainer in general you just need to add yourself as a person and
the proxied maintenance as a project. In our case you can subsitute my contact data with yours in a second commit.

**Comment by aphypnise** [comment]
Done, perhaps the commit message need to be more explicit and reference this pull-request, though.

**Comment by Whissi** [comment]
Getting test failures: [build.zip](https://github.com/gentoo/gentoo/files/2775108/build.zip)
Interesting: I cannot find the failing tests in your build.log.

I'll merge but please look into these issues.

**Pull request closed without merging**
