### PR TITLE
ebuilds

### PR DESCRIPTION
**Pull request by vieridipaola**
patches for squid, squidclamav, c-icap, samba, and yamdi.

### CODE REVIEW

**Comment by vieridipaola** [comment]
Bug: https://bugs.gentoo.org/590374
Bug: https://bugs.gentoo.org/606994
Bug: https://bugs.gentoo.org/629066
Bug: https://bugs.gentoo.org/556306
Bug: https://bugs.gentoo.org/554488
Bug: https://bugs.gentoo.org/651950
Signed-off-by: Vieri Di Paola <rentorbuy@yahoo.com>

**Comment by mgorny** [comment]
1. Please stop spamming.
2. Please use git cli to create the PR, not github ui.
3. Please read the documentation on how to create PRs and use github.

**Comment by vieridipaola** [comment]
1. I did not spam. I tried to add a Signed-off-by message to each commit (10).
2. why isn't github UI allowedf?
3. there's isn't much to-the-point Gentoo-specific documentation to create PRs. Generic Github docs siply say to fork, make changes and issue a PR. It would be nice if you could be a tad more precise before closing. eg. do I need to create a single PR for each ebuild I wish to modify or add?

**Comment by mgorny** [comment]
Because GitHub UI doesn't create good commits and we have reasons not to trust people who use it that they have tested what they are actually submitting. Sorry, you need to learn how to use git if you want to contribute, and you are expected to use repoman to commit. The documentation can be found in devmanual and on Gentoo Wiki. GLEP 66 is relevant too.

**Comment by vieridipaola** [comment]
Would you mind taking a quick look at this forum post please?
https://forums.gentoo.org/viewtopic-p-8287620.html
Your feedback is greatly appreciated.

**Pull request closed without merging**
