### PR TITLE
Libuv bump, add verify-sig support

### PR DESCRIPTION
**Pull request by hlein**

### CODE REVIEW

**Comment by jsmolic** [comment]
Can you split the version bump and implementing verify-sig into separate commits? I can test and merge the bump, but for verify-sig I would need someone more familiar with it to take a look.

**Comment by hlein** [comment]
> Can you split the version bump and implementing verify-sig into separate commits? I can test and merge the bump, but for verify-sig I would need someone more familiar with it to take a look.

Sure. Just to be clear, since they'll build on each other, one PR with a commit that adds the new version as-is and then another commit that updates that to add verify-sig? (Since the keyring package addition is also typically its own commit, that'd be inbetween those two.)

**Comment by jsmolic** [comment]
> > Can you split the version bump and implementing verify-sig into separate commits? I can test and merge the bump, but for verify-sig I would need someone more familiar with it to take a look.
> 
> Sure. Just to be clear, since they'll build on each other, one PR with a commit that adds the new version as-is and then another commit that updates that to add verify-sig? (Since the keyring package addition is also typically its own commit, that'd be inbetween those two.)

Yes, in total should be 3 commits (version bump as-is, keyring package and verify-sig support)

**Comment by hlein** [comment]
> Yes, in total should be 3 commits (version bump as-is, keyring package and verify-sig support). You can do it all in this PR, and I'll just cherry-pick the first commit

OK done.

**Comment by hlein** [comment]
> > Yes, in total should be 3 commits (version bump as-is, keyring package and verify-sig support). You can do it all in this PR, and I'll just cherry-pick the first commit
> 
> OK done.

Sorry, one more change, should be ready now.

I anticipated future headaches if you first cherry-pick just the first bump commit, because for signature verification we have to change where we pull the distfile from. The github tarball, which is what we've historically used, does not match the version that they publish with a signature on their project website. If in the future we change the same filename to come from different places, with different checksums, then Manifest verification will have a fit.

The initial 1.48.0 ebuild could change `SRC_URI` to point to that project website straight away, but rather than make that big of a change I just make it save with a `.gh.tar.gz` extension. I see that done a lot in `dev-python` packages but it's not exclusive to that.

Anyway, that should make for a barely-noticable difference in the bump commit, and lets the `SRC_URI`-changing revision that adds signature verification remain straightforward.

> for verify-sig I would need someone more familiar with it to take a look

Regarding that: I'm a PGP user for decades but my first look at `sec-keys/` packages was earlier this week. Retrieving the keys for this package was kind of a pain (see comments in `sec-keys/openpgp-keys-libuv`and the upstream issues they point to). I'd be happy to be on the hook as a proxy maintainer for the keys package.

**Comment by jsmolic** [comment]
We can also switch to the new distfile in 1.48.0 right away

**Comment by hlein** [comment]
> We can also switch to the new distfile in 1.48.0 right away

No objection :) Do you want me to make that change and update the PR?

**Comment by jsmolic** [comment]
> > We can also switch to the new distfile in 1.48.0 right away
> 
> No objection :) Do you want me to make that change and update the PR?

Sure, go for it

**Comment by jsmolic** [comment]
@hlein Could you also update the live ebuild in this PR to keep it in sync?

**Comment by hlein** [comment]
> @hlein Could you also update the live ebuild in this PR to keep it in sync?

Sure, done... hopefully ;)

**Comment by thesamesam** [comment]
Done with followup in 0b5c48c56266fff609ac1f65359eb723c811f2d6. If we haven't heard off upstream by the time a new release is out (at the latest), we'll try ping again, as the key situation really isn't ideal...

**Pull request closed without merging**
