### PR TITLE
Fix postinst script of sys-apps/baselayout-java

### PR DESCRIPTION
**Pull request by BoleynSu**
The old postinst will not work for binpkg. This CL fixes it.

### CODE REVIEW

**Comment by BoleynSu** [comment]
FYI. The same change for chrome os is at https://chromium-review.googlesource.com/c/chromiumos/overlays/portage-stable/+/2566311

**Comment by BoleynSu** [comment]
@gyakovlev please take a look.

**Comment by thesamesam** [comment]
Yep, we shouldn't be using EROOT in src_install anyway. I'll let @gyakovlev check this first though.

**Comment by BoleynSu** [comment]
Changed Bug: to Closes: according to the comment in https://bugs.gentoo.org/757837.

**Comment by gyakovlev** [comment]
ack, will test soon.

**Comment by BoleynSu** [comment]
Friendly ping

**Review by gyakovlev — APPROVED** [review]

**Comment by gyakovlev** [comment]
thanks, merged

**Comment by BoleynSu** [comment]
Hi @gyakovlev, it seems that the commit is still not merged yet. Could you please take a look?

**Pull request closed without merging**
