### PR TITLE
app-admin/ryzen_smu: 0.1.5 version bump

### PR DESCRIPTION
**Pull request by sqozz**

### CODE REVIEW

**Comment by slashbeast** [comment]
I was not aware the project moved to gitlab and github was no longer being updated, I will test it this weekend and merge if everything is okay. Thanks for pull request.

**Comment by sqozz** [comment]
did you have a chance to test my changes by chance? I'd really like to see a [ryzen_monitor_ng](https://github.com/mann1x/ryzen_monitor_ng) compatible module in the tree :)

**Comment by slashbeast** [comment]
Apologies for a delay, I have added it to calendar to sort it out tomorrow.

**Comment by slashbeast** [comment]
@sqozz the ryzen_smu module here does not seems to be compatible with neither the in-tree ryzen_monitor neither the ryzen_monitor_ng I pulled off github. Can you link me to a working monitor that you mention? I would rather not push it into tree if we have no working monitor around.

````
Error accessing SMU: SMU Driver Version Incompatible With Library Version
````

**Comment by jonasstein** [comment]
closed by 64cb5946d3ffd59181b4a09e0cff32ca148ee2e8 please try it out.

**Pull request closed without merging**
