### PR TITLE
sway: add 1.8-rc1 ebuild

### PR DESCRIPTION
**Pull request by funkycode**
Adding sway wm 1.8-rc1 ebuild, was able to build and are running it with wlroots 0.16
Release details: https://github.com/swaywm/sway/releases/tag/1.8-rc1
As it's my first PR to gentoo portage, will be grateful for some guidance in case I did something incorrectly

### CODE REVIEW

**Comment by kostadin04** [comment]
-rc2 has been released upstream

**Comment by SpeedJack** [comment]
I would not add a RC version to the tree, as this will cause all users with sway to get the (possibly unstable) RC version installed in their system as an update. Note that, actually, revisioned ebuilds for the 1.7 version of sway (`1.7-rX`) have not passed the stabilization process: so users with sway installed are probably using the testing branch now, but they do not expect to receive an update to a RC version. I think it's better to wait for the 1.8 stable release: it should come in just a few weeks.

**Comment by arkamar** [comment]
This seems to be obsolete, there is `gui-wm/sway-1.8.1` present the tree for few months already.

**Comment by AndrewAmmerlaan** [comment]
Closing since it seems the objective of this PR has been reached and it is now obsolete. Please re-open if this is not the case.

**Pull request closed without merging**
