### PR TITLE
app-dicts/myspell-en: bump to 20221201

### PR DESCRIPTION
**Pull request by kuraga**
20221201 version of English dictionaries for myspell/hunspell is out: https://extensions.libreoffice.org/en/extensions/show/english-dictionaries

Closes: https://bugs.gentoo.org/884435

### CODE REVIEW

**Comment by scardracs** [comment]
You may also want to drop 20221001 and ask for a 20221101 stablereq, in order to drop the oldest one too

**Comment by kuraga** [comment]
See also: #28944, https://bugs.gentoo.org/889416

**Comment by scardracs** [comment]
Please maintain only one PR (and mind pushing just one version as the 2022 version is outdated rn)

**Comment by kuraga** [comment]
@scardracs , thanks!

Situation:
1. `20121201` version's PR had been submitted.
2. `20121201` version's PR hasn't been handled for month.
3. `20121301` version is out.

Which my actions are, exactly?

**Comment by scardracs** [comment]
> @scardracs , thanks!
> 
> 
> 
> There is a situation:
> 
> 1. `20221201` version's PR had been submitted.
> 
> 2. `20221201` version's PR hasn't been handled for month.
> 
> 3. `20230101` version is out.
> 
> 
> 
> Which my actions are, exactly?

I mean, maintain only 20230101 instead of 20221201 and close this PR

**Pull request closed without merging**
