### PR TITLE
Skip tests for watchman dependencies

### PR DESCRIPTION
**Pull request by sin-ack**
I found these tests to be failing in an arm64 QEMU chroot.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Isn't it the other way around? The other PR should depend on this one, as it was needed to get tests passing (via skips).

**Comment by sin-ack** [comment]
> Isn't it the other way around? The other PR should depend on this one, as it was needed to get tests passing (via skips).

Hmm, does the arch team do their keywording independently? My understanding was that they would test on real hardware with no tests skipped, and then these would be adjusted as needed. If the other PR depends on this one, then we might potentially skip tests that pass on hardware.

**Comment by thesamesam** [comment]
If you hit the failures, it's very likely the arch testing will too. It's somewhat rare to have a test which passes on real hardware but fails in emulation (it happens, but not often). So, your approach here is valid if you want to stick with it, but unusual.

**Comment by sin-ack** [comment]
@thesamesam Done.

**Comment by thesamesam** [comment]
The CI failure is unrelated. Thanks, merging.

**Pull request closed without merging**
