### PR TITLE
Upgrades and fixes for any1 software (aml, neatvnc, wayvnc)

### PR DESCRIPTION
**Pull request by Hello71**

### CODE REVIEW

**Comment by chewi** [comment]
Thanks, that certainly lightens my load. Any particular reason you didn't add the version constraints to neatvnc and wayvnc 9999?

**Comment by Hello71** [comment]
> Any particular reason you didn't add the version constraints to neatvnc and wayvnc 9999?

not sure if there's any policy here, I was thinking about what happens if the version requirement changes in future. actually, now that I think about it, it's currently wrong because neatvnc requires aml<0.4 but actually aml-9999 is currently 0.3.x. probably need to think more about this issue

**Comment by Hello71** [comment]
I think it's probably best to just use a >= dep and then handle upstream breaking changes when they occur. that's how we handle breaking API changes in other packages, add = or < deps when they occur.

**Comment by chewi** [comment]
Ugh, I forgot this was here and did the bumps myself. Sorry! I have now applied your wayvnc fixes though. Also neatvnc fixed the header issue upstream.

**Pull request closed without merging**
