### PR TITLE
dev-util/bats: drop old

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
actually wanted to remove 1.7.0 as well, but that is stable for hppa

**Comment by scardracs** [comment]
> actually wanted to remove 1.7.0 as well, but that is stable for hppa

Minding stablereq 1.8.2? It's on ::gentoo for [more than 30 days](https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=4f1c20ad961c3b89ff40b4009b4bb5d88164f011)

**Comment by henning-schild** [comment]
I did not know there was a stable request. We can make 1.8.0 the new stable, but 1.8.2 looks not too far off and only contain fixes of bugs, so it likely the better candidate.

**Comment by henning-schild** [comment]
Ok, i will just close this. I think whichever version becomes the next stable should be a good candidate, and will drop old ebuilds later.

**Pull request closed without merging**
