### PR TITLE
net-im/telegram-desktop: Bump to 4.8.1

### PR DESCRIPTION
**Pull request by mid-kid**
@gyakovlev

### CODE REVIEW

**Comment by mid-kid** [comment]
Jinxed again by the devs. Testing 4.8.1 tomorrow...

**Comment by mid-kid** [comment]
Done

**Comment by thesamesam** [comment]
Please fix CI.

**Comment by mid-kid** [comment]
Damn, the CI strikes back.
Since I'm not sure if I'm allowed to mark an upgrade to tg_owt as stable (it's a minor patch, but I bumped the version number...), I've kept the original 4.6.5 version.

**Pull request closed without merging**
