### PR TITLE
dev-util/idea-ultimate: revision bump

### PR DESCRIPTION
**Pull request by switch87**
small revision, removed slotting so only 1 version can be installed at once.
Bug [561210](https://bugs.gentoo.org/show_bug.cgi?id=561210)

### CODE REVIEW

**Comment by switch87** [comment]
I also removed the old idea 15 pre-release because it is not working any more and added a new pre-release.

**Comment by switch87** [comment]
@monsieurp, #118 leaves in a not-working ebuild and does not fix any of the existing ebuilds, so I suggest to merge this one, so @tomboy-64 can do a new request for his minor adjustment on the updated ebuilds.

**Comment by mgorny** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
@switch87 Can I close this PR?

**Pull request closed without merging**
