### PR TITLE
mail-filter/postgrey: version bump to 1.37

### PR DESCRIPTION
**Pull request by stefangweichinger**
https://bugs.gentoo.org/show_bug.cgi?id=603394

### CODE REVIEW

**Comment by stefangweichinger** [comment]
*bump*

**Comment by stefangweichinger** [comment]
Bump

**Comment by kensington** [comment]
Hey, sorry about the delay.

Checking this, it looks like prepare fails with USE="targrey".

**Comment by stefangweichinger** [comment]
what should I do? This is a plain copy from the ebuild in portage (so that one should fail as well, right?).

**Comment by kensington** [comment]
It applies fine in 1.36-r1, so 1.37 must have introduced some changes causing targrey-0.31-postgrey-1.34.patch to no longer apply. So the options would be to create/obtain a new version of the targrey patch that applies cleanly to 1.37, or remove the USE flag.

**Comment by stefangweichinger** [comment]
Never tested with USE=targrey, right ... hmm, gotta have a look.

**Comment by stefangweichinger** [comment]
googled for upstream patches, patch against 1.34 is latest. I tend to drop that patch and USE-flag.
If users want it back, they will complain.

**Comment by kensington** [comment]
OK, targrey is gone and everything is squashed into 3d518220c62d039822184552c738436d7700c6f8. Thanks!

**Pull request closed without merging**
