### PR TITLE
www-servers/nginx-unit: Bump to version 1.12

### PR DESCRIPTION
**Pull request by rseichter**

### CODE REVIEW

**Comment by asarubbo** [comment]
Atm, we are missing the support for java, go, nodejs. Any chance to add them?

**Comment by rseichter** [comment]
I have tried my hand at Go et al with earlier versions of NGINX-Unit, but quickly ran into problems. Perhaps it is time to revisit the issue now that Unit has matured a bit. It would take me a while before I can look into this however, and that's definitely something for another pull request.

**Comment by juippis** [comment]
Please one commit for addition and one for removal.

**Comment by rseichter** [comment]
@juippis Once again GitHub represents adding ebuild 1.12 followed by deleting 1.10 as a rename operation 1.10 -> 1.12. Individual commits show that I did it correctly. This is a GitHub problem I cannot do anything about.

**Comment by juippis** [comment]
Now it looks and works (git-wise) like it should. Thanks!

**Pull request closed without merging**
