### PR TITLE
www-servers/tomcat: add systemd support.

### PR DESCRIPTION
**Pull request by nE0sIghT**
As part of systemd support multi instance feature reworked a bit:
1. Instance manager dropped. OpenRC init script may be symlinked now.
2. Instances are managed through config files in /etc/conf.d
3. By default instances are located in /var/lib/tomcats folder as in RHEL
4. Non named systemd unit provided and openrc init script may be started without instance symlink

I'm aware about systemd QA notices however /etc/conf.d is best place for configuration files in that case imho.

Bugs fixed:
https://bugs.gentoo.org/show_bug.cgi?id=485000
https://bugs.gentoo.org/show_bug.cgi?id=567892

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/java

**Comment by chewi** [comment]
This isn't any reflection on the work (I haven't looked at it yet) but just a note to @monsieurp and whoever to not merge this without me or @fordfrog okaying it first. We're both kinda busy.

**Comment by monsieurp** [comment]
I was going to hit the Merge pull request button but thanks for letting me know James. You just avoided a catastrophe.

**Comment by monsieurp** [comment]
James, have you got round to reviewing this PR? My guess is you haven't. :cry:

**Comment by chewi** [comment]
I've skimmed through this now and I like the overall approach but there's some minor points that need addressing.

You shouldn't source `/lib/gentoo/functions.sh` into the context of the OpenRC init script. OpenRC has its own binary versions of these functions under `/lib/rc/bin`. See if there's a way to determine whether you're running under OpenRC or not to make this conditional. You also need to apply `@GENTOO_PORTAGE_EPREFIX@` to the path.

This isn't your fault as the current version already does this but the other instances of `@GENTOO_PORTAGE_EPREFIX@` are wrong. It has a leading slash, not a trailing slash. Change `/@GENTOO_PORTAGE_EPREFIX@` to `@GENTOO_PORTAGE_EPREFIX@/`.

**Comment by nE0sIghT** [comment]
New commit pushed.

1. Added check for RC_SVCNAME environment variable before including gentoo-functions
2. Fixed GENTOO_PORTAGE_EPREFIX slashes.
3. Fixed path to configuration file in error message
4. Synced versions with main tree

**Comment by nE0sIghT** [comment]
Ping

**Comment by chewi** [comment]
We've actually been looking at this in conjunction with some other big tomcat changes. I was going to merge it the other day but I hadn't noticed that it does away with the instance manager. This is probably the way to go but it is a breaking change for end users and I want to make sure we get such a change right first time.

**Comment by nE0sIghT** [comment]
I see, thanks. Just say if I can help somehow

**Comment by fordfrog** [comment]
@chewi what are your concerns at this moment? yes, it breaks how tomcat is deployed but we already did that once when we introduced the manager. in my opinion we should introduce news item for this change so things do not stop to work accidentaly without the administrators/users noticing it. otherwise i think this is the right way to go with regard to multiple instances implementation.

**Comment by wltjr** [comment]
Keep in mind tomcat does not work out of the box. If you emerge tomcat it will not start, there is no init script till it is created by the instance manager. Which creates it outside of portage and causes it to not be updated when the package init script is updated. Really can't make things worse than they are, I am for the change. I have always hated the instance manager, it was not done the gentoo way. This seems to be with symlinks to init script for instances, and env files for instances. 👍

**Comment by orlitzky** [comment]
I host a few tomcat websites but don't know much about the Java ecosystem generally. I would really appreciate a wiki page that tells me how to keep my existing sites running, and how to migrate them to the new init design.

**Comment by fordfrog** [comment]
@nE0sIghT do i get it right that with this new implementation i can run only one instance of each tomcat slot or i missed something?

**Comment by orlitzky** [comment]
@fordfrog I believe this reverts to the "usual" way of running multiple instances of a service with OpenRC. Consider for example your network service: there's only one real script, `/etc/init.d/net.lo`, and then to create a network service for `eth0`, you create a symlink to `/etc/init.d/net.lo` called `/etc/init.d/net.eth0`. Inside the init script, the `RC_SVCNAME` variable is used to figure out which interface to actually bring up.

I haven't tried it, but I think the idea is the same here. To create a new instance, you would create a new symlink called `/etc/init.d/<instance-name>` and point it at the one tomcat init script. I'm not sure how the rest of the instance creation (config files, log files, etc.) would go.

**Comment by nE0sIghT** [comment]
@fordfrog 
You can run any number of instances regardless of slot.

With systemd you just enable them using named unit.
With openrc you should create symlinks as @orlitzky said.

**Comment by fordfrog** [comment]
so generally, the following "two" directories are shared among all instances withing the same slot unless user modifies the paths, right?

(from tomcat-r1.config)
CATALINA_TMPDIR="@GENTOO_PORTAGE_EPREFIX@/var/cache/tomcat-@SLOT@/temp"
#CATALINA_WORKDIR="@GENTOO_PORTAGE_EPREFIX@/var/cache/tomcat-@SLOT@/temp"

**Comment by nE0sIghT** [comment]
@fordfrog 

That's right.

**Comment by orlitzky** [comment]
I think sharing the `work` and `temp` directories by default should be avoided, if possible. Sharing `/tmp` has caused thousands of security vulnerabilities, and sharing the tomcat `temp` directory in particular goes against their recommendations. From https://tomcat.apache.org/tomcat-7.0-doc/security-howto.html:

> File permissions should also be suitably restricted. Taking the Tomcat instances at the ASF as an example (where auto-deployment is disabled and web applications are deployed as exploded directories), the standard configuration is to have all Tomcat files owned by root with group Tomcat and whilst owner has read/write privileges, group only has read and world has no permissions. The exceptions are the logs, temp and work directory that are owned by the Tomcat user rather than root. This means that even if an attacker compromises the Tomcat process, they can't change the Tomcat configuration, deploy new web applications or modify existing web applications. The Tomcat process runs with a umask of 007 to maintain these permissions.

**Comment by nE0sIghT** [comment]
@orlitzky 

That's why it should be overriden for new instances.
Default value is for single instance only. We can describe this in wiki.

**Comment by orlitzky** [comment]
@nE0sIghT is there a reason it can't be done for you? For example, instead of

```bash
CATALINA_TMPDIR="@GENTOO_PORTAGE_EPREFIX@/var/cache/tomcat-@slot@/temp"
```

you could have

```bash
CATALINA_TMPDIR="@GENTOO_PORTAGE_EPREFIX@/var/cache/@RC_SVCNAME@/temp"
```

Then, in the init script, you would replace the `RC_SVCNAME` placeholder with its value (that OpenRC provides). Prior to starting the daemon, `checkpath` could be used to ensure that the directory exists and has the correct permissions. I don't see where `/var/cache/tomcat-@slot@/temp` is being created... since directories under `/var/cache` can disappear, that `checkpath` may need to be added anyway, unless Tomcat creates the paths itself when it starts.

Unrelated: why `/var/logs` and not `/var/log`?

**Comment by nE0sIghT** [comment]
> Then, in the init script, you would replace the RC_SVCNAME placeholder with its value

```@GENTOO_PORTAGE_EPREFIX@``` is replaced at install time.
```$RC_SVCNAME``` is resolved in OpenRC init scripts only.
What are you suggest for systemd?

Did you tried to implement your suggestion?

> Unrelated: why /var/logs and not /var/log?

It's typo. Thanks for notice.

**Comment by orlitzky** [comment]
I don't use systemd, so I can't promise this will work, but it has some template variables as well:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html

You might be able to use `%i` or `%n` instead of `$RC_SVCNAME`.

**Comment by nE0sIghT** [comment]
@orlitzky 
For what you suggest we should implement some replacement hack in init engines.
I do not think it's right way.

Just try to implement your suggestion with openrc.

**Comment by nE0sIghT** [comment]
Hello again, we will celebrate 2 years this PR exists soon :-)
I rebased changes on top of current master also fixed /var/logs typo.

I would be glad to get review on this PR and get it finally merged.

**Comment by flappyports** [comment]
ping

**Comment by nE0sIghT** [comment]
I will rebase it to latest tomcat versions.

**Comment by chewi** [comment]
Sorry, this isn't your fault but I'm going to be very blunt. If you want to see this merged, you're going to have to become a dev and take responsibility for it. @fordfrog evidently only has time to bump Tomcat when necessary and I'm not about to take this on because the fall out from users could be quite big. I'm half way out the door from the Java team with my own involvement being limited to JVMs these days and even that is something I have little personal interest in now. Beyond that, we only see sporadic contributions from one or two others. It sucks but that's just how it is.

**Comment by wltjr** [comment]
@nE0sIghT if you become a dev you will need to take over dev-java as there are countless outdated packages. For example Tomcat 9.0.8 needs a newer [ecj](https://bugs.gentoo.org/657040). Much less anything else like Java 10+ etc. Its a big undertaking. Just so you have a clue what your getting into. Also this needs considerable work to be added. I did some of the necessary work over a year ago. But likely needs more work. I just fixed it for my needs.

**Pull request closed without merging**
