### PR TITLE
www-client/firefox: Re-add dbus USE flag

### PR DESCRIPTION
**Pull request by neeshy**
This uses a patch originally taken from KISS Linux: https://github.com/kisslinux/repo/blob/35fd7ff2fe1ec6f814bfc40c6d7122404af70088/extra/firefox/patches/firefox-72-no-dbus.patch
The patch has been ported to Firefox 74.

### CODE REVIEW

**Comment by Whissi** [comment]
Thanks. Is there an upstream bug for this change? Problem is: When we add this now and it won't work with next firefox release anymore, we would face some problems:

- If we drop the patch again, people started to rely on that feature will be unhappy
- If we delay release of next firefox until someone ported that patch, people not interested in that feature but interested in latest firefox will be unhappy.
- In the end it will be Gentoo Mozilla project who has to do the work and it's currently a 1-2 people project and at least 50% of that project isn't interested in that patch.

**Comment by anarchpenguin** [comment]
Closing we are not gonna support such an implementation,

**Comment by neeshy** [comment]
> Thanks. Is there an upstream bug for this change? Problem is: When we add this now and it won't work with next firefox release anymore, we would face some problems:
That's true, but for now removing a dependency on dbus through this patch is trivial, as is porting between firefox releases.

Some background: There was a regression in upstream firefox which forced building against dbus due to some parts of audio_thread_priority depending on it. The related bug report can be found here: https://bugzilla.mozilla.org/show_bug.cgi?id=1561207

>     * If we drop the patch again, people started to rely on that feature will be unhappy
Those people (who want to have systems without dbus) will be unhappy anyway if you don't incorporate the patch.

>     * If we delay release of next firefox until someone ported that patch, people not interested in that feature but interested in latest firefox will be unhappy.
The patch was trivial to port, it took about 10 minutes on each firefox release. All the patch actually does is prevent the audio_thread_priority, dbus, and libdbus crates from being pulled in via cargo, and it also removes the corresponding sections of code which use audio_thread_priority.

>     * In the end it will be Gentoo Mozilla project who has to do the work and it's currently a 1-2 people project and at least 50% of that project isn't interested in that patch.
If you'd like, I can port the patch on each firefox release. I'll be doing that for my own benefit anyway.

> Closing we are not gonna support such an implementation,
Why so hasty?

**Comment by anarchpenguin** [comment]
Instead of spending all that time porting the patch do as upstream has requested and ifdef the code so it can be enabled/disabled via --disable-dbus. Is rather foolish to continue to do the same thing when you know it will never be excepted upstream as is.

**Pull request closed without merging**
