### PR TITLE
dev-java/log4j: Dropped jmx use flag as it is in the jdk/jre since 1.5

### PR DESCRIPTION
**Pull request by wltjr**

### CODE REVIEW

**Comment by jlec** [comment]
Could you please format your commit message like
```
cat/pkg: TITLE

message
```

**Comment by jlec** [comment]
Thanks for taking care. Could you also fix the commit message as well? That is what will end in the main repo.

**Comment by mgorny** [comment]
@gentoo/java

**Comment by chewi** [comment]
Merged with thanks. I'd be grateful if you could carry this through to its logical conclusion and remove remaining instances of java-virtuals/jmx, then we can last-rite both that and dev-java/sun-jmx.

**Pull request merged**
