### PR TITLE
app-editors/emacs: explicitly add USE=wayland

### PR DESCRIPTION
**Pull request by mazunki**
refactor the handling of USE="gtk -X" to explicitly just depend on USE=wayland, since some users may have globally enabled Xwayland support.

Closes: https://bugs.gentoo.org/931203

### CODE REVIEW

**Comment by ulm** [comment]
AFAICS, that doesn't add anything new, so it would be redundant with existing USE flags.

**Comment by mazunki** [comment]
@ulm The main change here is that if the user has USE=wayland in globals, pgtk support will be added regardless of USE=X state.

This would save the next wayland user which has USE=X enabled by default from the same debugging I had to go through.

**Comment by mazunki** [comment]
I've edited the patch to remove the unnecessary and against-policy `RESTRICTED_USE` conditions. The same/similar conditions are applied in src_configure anyway.

**Comment by ulm** [comment]
Sorry, this is not going to happen.

**Pull request closed without merging**
