### PR TITLE
dev-libs/hyperscan: bump to 4.4.1-r1, fix 616626

### PR DESCRIPTION
**Pull request by croessner**
Gentoo-Bug: 616626

### CODE REVIEW

**Comment by croessner** [comment]
Could someone please re-add my mail address? I already fixed that.

**Comment by croessner** [comment]
@djc here we go :-)

**Comment by djc** [comment]
@mgorny already added it back in 3d4f9b225525a4b3c5f56bcb343a883d8d5caed0.

**Comment by djc** [comment]
Are you sure that these are only build-time dependencies, not run-time dependencies? It seems unlikely that libpcap is only used at build time.

**Comment by croessner** [comment]
`rns root@mx  ~ # ldd /usr/lib/libhs.so.4.4.1                                                                                         linux-vdso.so.1 (0x0000031d43f65000)                                                                                         libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libstdc++.so.6 (0x0000031d4310d000)                                 libm.so.6 => /lib64/libm.so.6 (0x0000031d42e08000)                                                                           libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/5.4.0/libgcc_s.so.1 (0x0000031d42bf1000)                                   libc.so.6 => /lib64/libc.so.6 (0x0000031d42848000)
        /lib64/ld-linux-x86-64.so.2 (0x0000031d43d43000)                                                                     rns root@mx  ~ # ldd /usr/lib/libhs_runtime.so.4
        linux-vdso.so.1 (0x000003385e333000)
        libc.so.6 => /lib64/libc.so.6 (0x000003385d9e3000)                                                                           /lib64/ld-linux-x86-64.so.2 (0x000003385e111000)`

I can not see any deps in the shared libs. And also the docs said that it is only required for building. So I did not add them to RDEPEND.

**Comment by croessner** [comment]
Sorry, had to reformat it for you.

**Comment by djc** [comment]
Great, this compiles for me. Rebased as 4e718599e95198a9017656f40d068b6f99719cb0 and pushed.

**Pull request closed without merging**
