### PR TITLE
Add newer Request Tracker version

### PR DESCRIPTION
**Pull request by timorl**
This is my first PR to Gentoo so I'm mentally prepared for having done a lot wrong. Various thoughts in no particular order:

1. This required adding two Perl modules and updating one.
2. I wasn't sure whether to remove the previous version, so I didn't.
3. I changed some use flags to support nginx. This feels a bit weird, since I was under the impression that `www-apps` usually don't specify which webserver they'll use for proxying, but I was trying to change as little as possible and earlier versions did that, so I kept (and expanded) it.
4. I also mostly have an ebuild for 4.4.7 and if I knew how to do slots I would've probably included it in this PR as well (although I'm not sure it's worth it).
5. I checked that this actually works, i.e. I am currently running a vhost+nginx instance of RT installed from this ebuild on my homeserver.
6. I haphazardly bumped EAPI to 8 and only did one change resulting from `pkgcheck` complaining.
7. Speaking of `pkgcheck`, it definitely doesn't give me a clean pass, but much of it doesn't seem to be caused by this PR.
8. Although there is some stuff with keywords – I only added `~amd64` in most places, since this is the only one I actually tried running this on.
9. This also fixes [920201](https://bugs.gentoo.org/920201) through the changes in the Makefile patch – the previous patch was doing approximately nothing, since the `.NOTPARALLEL` directive impacts how the _dependencies_ of its arguments are run, not the arguments themselves. This could've possibly been a separate PR.
10. Cleaned up the Perl dependencies by running the installation without them and seeing what it complains about. I think there are quite a couple in 4.4.4 that are unneeded, but too lazy to check and since I didn't touch that it's not my fault. :P

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by titanofold** [comment]
Thanks so much for getting this started! I was just talking about how I needed to get this packaged bump in gentoo-dev.

I do use RT at work in production for handling customer service emails, so I'm keen on getting this going.

There's a file that lists the modules needed. I'll dig into this today or tomorrow.

**Comment by arthurzam** [comment]
@titanofold please handle is soon, since this package is currently EAPI=6, and I prefer not to last-rite it if there is progress.

**Review by titanofold — COMMENTED** [review]
In Gentoo, we generally add and remove as separate commits. The drop doesn't need to happen for us to have 1.820.0 added.

**Comment by arthurzam** [comment]
@titanofold I'm going to last-rite `www-apps/rt` on 2024-07-26 for 30 days on the grounds of it being EAPI=6 only package (one of the last in tree). Please handle it soon, even if you need to edit this PR by yourself (after merge, extra commits).

**Comment by timorl** [comment]
My update telling me that the ebuild I wrote myself has been hardmasked was a bit of a jumpscare, especially since the reason was that it had EAPI 6, while I specifically made it 8. :D

Anyway, re-added 1.760.0, but in a lazy way, so I'm not sure the commit is in the correct format etc.

**Comment by vaukai** [comment]
> My update telling me that the ebuild I wrote myself has been hardmasked was a bit of a jumpscare, especially since the reason was that it had EAPI 6, while I specifically made it 8. :D

You might want to add another commit removing [these lines from package.mask](https://github.com/gentoo/gentoo/blob/master/profiles/package.mask#L59-L63).

> 
> Anyway, re-added 1.760.0 [...]

Why?

**Comment by timorl** [comment]
> > My update telling me that the ebuild I wrote myself has been hardmasked was a bit of a jumpscare, especially since the reason was that it had EAPI 6, while I specifically made it 8. :D
> 
> You might want to add another commit removing [these lines from package.mask](https://github.com/gentoo/gentoo/blob/master/profiles/package.mask#L59-L63).

I wanted to avoid the merge, but turns out it was clean, so done. ^^

> 
> > Anyway, re-added 1.760.0 [...]
> 
> Why?

Uh, that's the only comment I got from @titanofold , but I might've misunderstood something. <_<"

**Comment by parona-source** [comment]
The best way to approach is to rebase the PR so that history doesnt include a mention of the removal/re-adding and so that the merge commit doesnt show up.

https://www.gentoo.org/glep/glep-0066.html#id6

Id first start off with making sure you have gentoo upstream as a remote like `git remote add upstream https://github.com/gentoo/gentoo`, pull it with rebase so that git can figure out it can remove the merge commits with `git pull upstream master --rebase`. Then you will have a clean slate to rebase your PR manually.

https://git-rebase.io/

Here id do a mix of fixup+reword where I would fixup the "dev-perl/DBIx-SearchBuilder: re-add 1.760.0" into "dev-perl/DBIx-SearchBuilder: add 1.820.0, drop 1.760.0" and then reword it into "dev-perl/DBIx-SearchBuilder: add 1.820.0".

If you need assistance you can ask in #gentoo-dev-help over on IRC.

**Comment by timorl** [comment]
Sure, have some history rewrites then. I hope this still works.

**Comment by vaukai** [comment]
> Sure, have some history rewrites then. I hope this still works.

one commit missing. before you can unmask you should drop 4.4.4-r4

**Comment by timorl** [comment]
> > Sure, have some history rewrites then. I hope this still works.
> 
> one commit missing. before you can unmask you should drop 4.4.4-r4

Or apparently I can forget about this and then get reminded when someone does it for me. :P Anyway, rebased, and since 4.4.4-r4 was already dropped this should be fine?

**Comment by vaukai** [comment]
> > > Sure, have some history rewrites then. I hope this still works.
> > 
> > 
> > one commit missing. before you can unmask you should drop 4.4.4-r4
> 
> Or apparently I can forget about this and then get reminded when someone does it for me. :P Anyway, rebased, and since 4.4.4-r4 was already dropped this should be fine?

according to https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dad331077a019561290ee2f024fcdfe7a52231e0 you might consider closing this PR

**Comment by timorl** [comment]
> > > > Sure, have some history rewrites then. I hope this still works.
> > > 
> > > 
> > > one commit missing. before you can unmask you should drop 4.4.4-r4
> > 
> > 
> > Or apparently I can forget about this and then get reminded when someone does it for me. :P Anyway, rebased, and since 4.4.4-r4 was already dropped this should be fine?
> 
> according to https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dad331077a019561290ee2f024fcdfe7a52231e0 you might consider closing this PR

Wait, why? Oh no, if it was removed this means it's no longer supported in any way, and in particular re-adding this version would have to go through some process I don't know? So everything I did here was completely wasted effort? Is this how it works? ;_;

**Comment by vaukai** [comment]
> > > > > Sure, have some history rewrites then. I hope this still works.
> > > > 
> > > > 
> > > > one commit missing. before you can unmask you should drop 4.4.4-r4
> > > 
> > > 
> > > Or apparently I can forget about this and then get reminded when someone does it for me. :P Anyway, rebased, and since 4.4.4-r4 was already dropped this should be fine?
> > 
> > 
> > according to https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dad331077a019561290ee2f024fcdfe7a52231e0 you might consider closing this PR
> 
> Wait, why? Oh no, if it was removed this means it's no longer supported in any way, and in particular re-adding this version would have to go through some process I don't know? So everything I did here was completely wasted effort? Is this how it works? ;_;

it is still possible to `git revert` a removal. e. g. https://gitweb.gentoo.org/repo/gentoo.git/log/dev-java/commons-imaging?showmsg=1

**Comment by timorl** [comment]
> > > > > > Sure, have some history rewrites then. I hope this still works.
> > > > > 
> > > > > 
> > > > > one commit missing. before you can unmask you should drop 4.4.4-r4
> > > > 
> > > > 
> > > > Or apparently I can forget about this and then get reminded when someone does it for me. :P Anyway, rebased, and since 4.4.4-r4 was already dropped this should be fine?
> > > 
> > > 
> > > according to https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=dad331077a019561290ee2f024fcdfe7a52231e0 you might consider closing this PR
> > 
> > 
> > Wait, why? Oh no, if it was removed this means it's no longer supported in any way, and in particular re-adding this version would have to go through some process I don't know? So everything I did here was completely wasted effort? Is this how it works? ;_;
> 
> it is still possible to `git revert` a removal. e. g. https://gitweb.gentoo.org/repo/gentoo.git/log/dev-java/commons-imaging?showmsg=1

If it's not a process problem, then I don't get it – this PR adds `www-apps/rt-5.0.6`, same as it did when I started it, your last comment said it should also remove 4.4.4-r4, which happened (in the commit you linked), but when it happened you are telling me to close the PR and, uh, I'm just confused. Reverting the removal doesn't help, since the removal was of version 4.4.4-r4 which should have been removed, no?

Ohhh, wait, I don't think this helps much with my confusion as to what you are trying to tell me, but I think I at least noticed that I dropped a couple of files from `files/` during the rebase (to be precise `config.layout-gentoo`, `postinstall-en.txt`, and `reconfig`). Not sure whether I should try getting them back, since I don't know what the status of this PR is, so I would like to first clear that up. <_<" Will this be likely/possibly accepted after I get these files back?

**Comment by vaukai** [comment]
> " Will this be likely/possibly accepted after I get these files back?

Depends on who's reviewing your PR? 
add one commit `git revert dad331077a019561290ee2f024fcdfe7a52231e0`
then rebase to make this one the first

**Comment by timorl** [comment]
Ok, I reverted this commit, then rebased my work on top of that, and then cherry-picked it to remove 4.4.4-r4 again.

**Comment by vaukai** [comment]
> Ok, I reverted this commit, then rebased my work on top of that, and then cherry-picked it to remove 4.4.4-r4 again.

your last commit message looks weird, compare with [commit messages found here](https://gitweb.gentoo.org/repo/gentoo.git/log/profiles/package.mask?qt=grep&q=remove+mask)

**Comment by timorl** [comment]
> your last commit message looks weird, compare with [commit messages found here](https://gitweb.gentoo.org/repo/gentoo.git/log/profiles/package.mask?qt=grep&q=remove+mask)

Fair enough, I tried to cheat by reusing the original commit that removed 4.4.4-r4, but that didn't really make sense on reflection. Is it alright now?

**Comment by vaukai** [comment]
> > your last commit message looks weird, compare with [commit messages found here](https://gitweb.gentoo.org/repo/gentoo.git/log/profiles/package.mask?qt=grep&q=remove+mask)
> 
> Fair enough, I tried to cheat by reusing the original commit that removed 4.4.4-r4, but that didn't really make sense on reflection. Is it alright now?

for removing the entry from `package.use.mask`you'd better use a separate commit.
the other commit for old version removal can use the automatic commit message.

**Comment by arthurzam** [comment]
> If it's not a process problem, then I don't get it – this PR adds `www-apps/rt-5.0.6`, same as it did when I started it, your last comment said it should also remove 4.4.4-r4, which happened (in the commit you linked), but when it happened you are telling me to close the PR and, uh, I'm just confused. Reverting the removal doesn't help, since the removal was of version 4.4.4-r4 which should have been removed, no?
> 
> Ohhh, wait, I don't think this helps much with my confusion as to what you are trying to tell me, but I think I at least noticed that I dropped a couple of files from `files/` during the rebase (to be precise `config.layout-gentoo`, `postinstall-en.txt`, and `reconfig`). Not sure whether I should try getting them back, since I don't know what the status of this PR is, so I would like to first clear that up. <_<" Will this be likely/possibly accepted after I get these files back?

First of all, I'm the one who pkgremoved this package, since it was EAPI=6 only and no reply from maintainer.

I very much appreciate this PR. I think the new ebuild you did has at least the same quality as previous one, so if there is maintainer timeout of 30 days from this message, I'll merge this PR myself. I can't know if it works or not, but it is as good as we can.

**Comment by timorl** [comment]
> for removing the entry from `package.use.mask`you'd better use a separate commit. the other commit for old version removal can use the automatic commit message.

I manually named it "drop $VERSION" and added a separate commit for unmasking, maybe this time it's alright. ^^"

**Comment by timorl** [comment]
@arthurzam soft nudge. I'm not at all in a rush, just trying to make sure this is not forgotten. :)

**Comment by arthurzam** [comment]
> @arthurzam soft nudge. I'm not at all in a rush, just trying to make sure this is not forgotten. :)

Sorry, it was forgotten :(

I've started the timer of 30 days from 2024-08-27, 30 days passed, I call maintainer timeout. Let me merge it.

**Pull request closed without merging**
