### PR TITLE
Delete scapy-python3

### PR DESCRIPTION
**Pull request by gpotter2**
I thought I'd help by making the PR. Thanks for your time

- Deprecated since net-analyser/scapy supports Python 3.
- Has no dependents.
- I have consent from the current Gentoo maintainer, which I contacted a week ago.

Signed-off-by: gpotter2 <gabriel@potter.fr>

### CODE REVIEW

**Comment by gpotter2** [comment]
Hi again & sorry for bothering,
Any news @klausman ?
Thanks for your time

**Comment by SoapGentoo** [comment]
@gpotter2 this should have been last-rited and not just deleted from the tree

**Comment by gpotter2** [comment]
@SoapGentoo I have no idea I am new to Gentoo. That's what PR reviews are for

**Comment by Chiitoo** [comment]
As an additional future note, the Certificate of Origin [1] (Signed-off-by) should include a real name.

Also, the git commit summary line isn't following our specification [2].

Welcome to Gentoo!  :]

1. https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin
2. https://www.gentoo.org/glep/glep-0066.html#commit-messages

**Pull request closed without merging**
