### PR TITLE
dev-libs/libsecp256k1: drop old + fix bug 729888

### PR DESCRIPTION
**Pull request by whitslack**
@thesamesam: Note, the first commit removes two redundant `package.use.mask` specifications that were already specified (more broadly) later down in their respective files.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --git-remote whitslack --commits whitslack/master --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Merged too quickly -- old Electrum is a problem.

**Comment by whitslack** [comment]
My bad. I thought `dev-libs/libsecp256k1-0.3.2` had been stabilized.

**Comment by whitslack** [comment]
Shouldn't `pkgcheck` catch this sort of issue? :thinking:

**Comment by Flowdalic** [comment]
> Shouldn't `pkgcheck` catch this sort of issue? 🤔

IIRC only via a tree-wide visibility check by running `pkgcheck scan -c VisiblityCheck` in the repo's root directory.

**Comment by whitslack** [comment]
> running `pkgcheck scan -c VisiblityCheck` in the repo's root directory.

Probably wouldn't do anything useful for me since my setup doesn't seem to be what `pkgcheck` is expecting. I have several Git worktrees (see `man git-worktree`) attached to a single, shallow Git repo that itself has no tree checked out, and the subordinate worktrees each have a sparse checkout (see `man git-sparse-checkout`) containing a distinct subset of package directories. Then, my local repo at `/var/db/repos/local`, which is not under source code management, contains symlinks to package directories inside my various Git worktrees as well as some actual directories containing local ebuilds that are not in any Git repo. This setup gives me a hybrid `local` repo that appears to contain ebuilds from multiple disjoint branches-in-progress simultaneously. It avoids the problem I would otherwise have, whereby switching a solitary Git worktree to another branch to work on a different package would make my works-in-progress on other branches "disappear" from my local repo and would thus cause Portage to want to downgrade the packages in any no-longer-checked-out branches. Instead, I have all of my pending branches checked out concurrently, in separate worktrees, so that Portage can see them all simultaneously, but I avoid the disk waste that would come from having multiple full checkouts of the tree. The downside is that I'm never running `pkgcheck` in anything remotely resembling a fully populated repo, and sometimes it bombs entirely, complaining that my current working directory is not within a Git repo despite that it most certainly is. If anyone has any alternative ideas that would allow me to keep multiple irons in the fire concurrently without needing to keep multiple full copies of the repo on disk, I'm open to suggestions.

**Comment by whitslack** [comment]
@thesamesam: `dev-libs/libsecp256k1-0.3.2` has now been [stabilized](https://bugs.gentoo.org/942991), but it looks like that was unnecessary, as the old version of `net-misc/electrum` that needed `<dev-libs/libsecp256k1-0.4` was removed from the tree in the meantime. I feel bad about requesting stabilization of 0.3.2 only to turn around and remove it from the tree, but we really don't need 0.3.2 anymore now that that old Electrum is gone. Should I revise this PR to drop 0.3.2 as well?

In general is there any reason to retain versions of a package older than the most recent stabilized version, assuming that no other packages strictly require older versions? In other words, since 0.5.1 is stabilized now, should I make this PR drop everything older than 0.5.1?

**Comment by thesamesam** [comment]
I generally wait a bit after a new version becomes visible (at any level) in case of regressions so users can downgrade. In this case, users of electrum (or whatever) will only now be able to upgrade, so giving a bit of a grace period might be nice. But you can balance that against the likelihood of regressions / diff between releases.

It's OK if you want to clean them all up now.

**Comment by whitslack** [comment]
If there had been more significant changes between releases, I would be more inclined to keep older versions around for longer, but the differences between 0.3.2 and 0.5.1 are pretty minor. Now, the latest released 0.6.0 is a different matter, as it introduces an entirely new module.

**Pull request closed without merging**
