### PR TITLE
media-libs/tg_owt: Bump to pre20220811

### PR DESCRIPTION
**Pull request by rakino**
Just bumping Telegram Desktop for Guix and found some nice patches here. XD

I've updated the X11 patch so I want to make it available here.

Thanks!

### CODE REVIEW

**Comment by mid-kid** [comment]
I can't bump this package without also modifying the telegram-desktop ebuild since it hardcodes the dependency version. I generally check if the changes in the repository have any effect on the library code (as in it's not just build-related or documentation) before bumping this package and having everyone and their dog rebuild it. The only new commit seems to be https://github.com/desktop-app/tg_owt/commit/a5fbc9123e056e611e69acf0ceb4252ddd838adb, which doesn't really affect us.

Also, while usually distros try to only carry patches when they can't be upstreamed for whatever reason, this is a classic case of "I can't be f-ed to make a pr". I'd rather upstream it...

**Comment by rakino** [comment]
@mid-kid Thank you! Just made a pr (107) to upstream =)

**Comment by rakino** [comment]
Upstreamed :) , so closing the PR.

**Comment by mid-kid** [comment]
Thanks a lot!

**Pull request closed without merging**
