### PR TITLE
net-proxy/squid: upstream patches and multiple instances

### PR DESCRIPTION
**Pull request by vieridipaola**
ebuilds and files to support upstream patch releases (stable)
and multiple instances for both Squid 3 and 4.

Bug: https://bugs.gentoo.org/606994
Bug: https://bugs.gentoo.org/629066
Bug: https://bugs.gentoo.org/663302
Signed-off-by: Vieri <rentorbuy@yahoo.com>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by hydrapolic** [comment]
Thanks for working on this, i'll try and test it as we use squid.

**Comment by vieridipaola** [comment]
OK, thanks. You might also be interested in c-icap if you use it:
https://github.com/gentoo/gentoo/pull/10613

**Comment by vieridipaola** [comment]
I don't know if you also make use of c-icap + squidclamav, but here's the link anyway:
https://github.com/gentoo/gentoo/pull/10624

**Comment by vieridipaola** [comment]
Proposing fix for bashisms and FHS issue.

**Comment by hydrapolic** [comment]
@Zlogene

**Comment by hydrapolic** [comment]
Thanks @Zlogene and @vieridipaola

**Comment by vieridipaola** [comment]
Thanks to both of you. Just one question though. The init script that has been included is the older one without the bashisms corrected.
The bashism-less net-proxy/squid/files/squid.initd-r5 is here: https://github.com/gentoo/gentoo/pull/10614/files

Is there a reason why you left this version out?

**Comment by hydrapolic** [comment]
@vieridipaola let's improve this in https://bugs.gentoo.org/679576

**Comment by hydrapolic** [comment]
@vieridipaola, merged to the tree.

**Comment by vieridipaola** [comment]
Thank you very much.

And now for c-icap... (hint ;.) )

**Pull request closed without merging**
