### PR TITLE
dev-python/pyswisseph: New Package

### PR DESCRIPTION
**Pull request by lluixhi**

### CODE REVIEW

**Comment by blueness** [comment]
what are these packages about?  i can proxy for you if you like

**Comment by blueness** [comment]
astrology?!?!

**Comment by monsieurp** [comment]
What @blueness said. What are these packages about exactly? Please provide some background and a bug number. "New package" is clearly not a good enough description.

**Comment by lluixhi** [comment]
@blueness @monsieurp
Yeah they're astrology packages :P
 
Here's a bug report: https://bugs.gentoo.org/show_bug.cgi?id=586110

**Comment by blueness** [comment]
not sure if it should be app-misc or a game, but I'll put this on the tree sometime later today

**Comment by lluixhi** [comment]
@blueness 
I put it under app-misc because app-misc/astrolog, the CLI astrology program is in there.

Though I suppose we could put it in games :P

**Comment by blueness** [comment]
nah leave it in app-misc.  the categories are not cut and dry and consistency is important.

**Comment by blueness** [comment]
done

**Comment by lluixhi** [comment]
Hey @blueness 
Did you forget about this, or were you not going to merge it?

**Comment by lluixhi** [comment]
bumping

**Pull request closed without merging**
