### PR TITLE
dev-qt/qtcore: use link option -pthread instead of -lpthread

### PR DESCRIPTION
**Pull request by Rabenda**
Bug: https://bugs.gentoo.org/803470
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Han Gao <rabenda.cn@gmail.com>

### CODE REVIEW

**Comment by a17r** [comment]
We will only change ~arch ebuilds here, no changes to stable please.

**Comment by Rabenda** [comment]
> We will only change ~arch ebuilds here, no changes to stable please.

Let me remove 5.15.2 edits?

**Comment by jsmolic** [comment]
> > We will only change ~arch ebuilds here, no changes to stable please.
> 
> Let me remove 5.15.2 edits?

Yes, you can keep the patch applied only to 5.15.3 version

**Comment by dlan17** [comment]
I've tested this patch in RISC-V hw (which is unmatched box), all are good
(note: only dev-qt/qtwebengine has user patches applied which we don't intend to push to official portage tree) 

=== here is the package list which installed

dev-qt/assistant-5.15.3
dev-qt/designer-5.15.3
dev-qt/linguist-5.15.3
dev-qt/linguist-tools-5.15.3
dev-qt/pixeltool-5.15.3
dev-qt/qdbus-5.15.3
dev-qt/qdbusviewer-5.15.3
dev-qt/qdoc-5.15.3
dev-qt/qt-docs-5.15.2_p202011130614
dev-qt/qt3d-5.15.3
dev-qt/qtbluetooth-5.15.3
dev-qt/qtcharts-5.15.3
dev-qt/qtchooser-66-r2
dev-qt/qtconcurrent-5.15.3
dev-qt/qtcore-5.15.3
dev-qt/qtdatavis3d-5.15.3
dev-qt/qtdbus-5.15.3
dev-qt/qtdeclarative-5.15.3
dev-qt/qtdiag-5.15.3
dev-qt/qtgamepad-5.15.3
dev-qt/qtgraphicaleffects-5.15.3
dev-qt/qtgui-5.15.3
dev-qt/qthelp-5.15.3
dev-qt/qtimageformats-5.15.3
dev-qt/qtlocation-5.15.3
dev-qt/qtmultimedia-5.15.3
dev-qt/qtnetwork-5.15.3
dev-qt/qtnetworkauth-5.15.3
dev-qt/qtopengl-5.15.3
dev-qt/qtpaths-5.15.3
dev-qt/qtplugininfo-5.15.3
dev-qt/qtpositioning-5.15.3
dev-qt/qtprintsupport-5.15.3
dev-qt/qtquickcontrols-5.15.3
dev-qt/qtquickcontrols2-5.15.3
dev-qt/qtquicktimeline-5.15.3
dev-qt/qtscript-5.15.3
dev-qt/qtscxml-5.15.3
dev-qt/qtsensors-5.15.3
dev-qt/qtserialbus-5.15.3
dev-qt/qtserialport-5.15.3
dev-qt/qtspeech-5.15.3
dev-qt/qtsql-5.15.3
dev-qt/qtsvg-5.15.3
dev-qt/qttest-5.15.3
dev-qt/qttranslations-5.15.3
dev-qt/qtvirtualkeyboard-5.15.3
dev-qt/qtwayland-5.15.3
dev-qt/qtwaylandscanner-5.15.3
dev-qt/qtwebchannel-5.15.3
dev-qt/qtwebengine-5.15.3_p20220310
dev-qt/qtwebsockets-5.15.3
dev-qt/qtwebview-5.15.3
dev-qt/qtwidgets-5.15.3
dev-qt/qtx11extras-5.15.3
dev-qt/qtxml-5.15.3
dev-qt/qtxmlpatterns-5.15.3

**Comment by dlan17** [comment]
@a17r hi, wonder if possible, can you merge this patch into the qtbase-5.15.3-gentoo-kde-1.tar.xz? might need to do a bump version, so instead of putting it under ${FILESDIR}..

**Comment by Pesa** [comment]
> @a17r hi, wonder if possible, can you merge this patch into the qtbase-5.15.3-gentoo-kde-1.tar.xz? might need to do a bump version, so instead of putting it under ${FILESDIR}..

I don't think that's appropriate.

**Comment by dlan17** [comment]
> > @a17r hi, wonder if possible, can you merge this patch into the qtbase-5.15.3-gentoo-kde-1.tar.xz?
> 
> I don't think that's appropriate.

never mind, this is merely a suggestion, do whatever fit for you

> maybe change "atomic" in the patch file name to "pthread"?
> 
> has anyone tested on other minor/exotic arches?

I could give a test on arm64 (which I have)..

**Comment by Rabenda** [comment]
> maybe change "atomic" in the patch file name to "pthread"?
> 
> has anyone tested on other minor/exotic arches?

Rename finished.

**Comment by dlan17** [comment]
Hi, I've tested the patch both on arm(32bit) and arm64, no regressions found.

long story, the error from dev-qt/qt3d is that riscv64 lack 1byte atomic instruction, but the problem doesn't exist on arm/arm64, so even without this patch, qt3d just build fine there.
anyway, I've tried applied this patch both on arm and arm64, and see no regressions.

`renderview.cpp:(.text+0x4a96): undefined reference to `__atomic_exchange_1'`

**Review by Pesa — APPROVED** [review]
Thanks

**Pull request closed without merging**
