### PR TITLE
www-apps/gitea: minor version bump

### PR DESCRIPTION
**Pull request by nemunaire**

### CODE REVIEW

**Comment by hydrapolic** [comment]
Tested on amd64, works fine, thanks.

**Comment by stknob** [comment]
You might want to bump this up to 1.14.4, which has been released a couple of days ago.

**Review by juippis — COMMENTED** [review]
^ Can we do that please?

**Comment by hydrapolic** [comment]
Meanwhile 1.14.6 got released.

**Comment by nemunaire** [comment]
Sorry, this is too much waste of time for me. The 1.15 release is on the way since a few days and will certainly be released before this PR is merged, again.

When the proxy-maintainer initiative began, there wasn't such delays and it was a pleasure for me to contribute. Today, with a rapidly evolving project like Gitea, I don't think that the proxy-maintainer system is still appropriate for this. I left the project to maintainer-needed if anyone thinks this project still has a place in the tree. Personally, I think it's waste of time for both the maintainer and the proxy-maintainer team.

**Comment by hydrapolic** [comment]
> Sorry, this is too much waste of time for me. The 1.15 release is on the way since a few days and will certainly be released before this PR is merged, again.
> 
> When the proxy-maintainer initiative began, there wasn't such delays and it was a pleasure for me to contribute. Today, with a rapidly evolving project like Gitea, I don't think that the proxy-maintainer system is still appropriate for this. I left the project to maintainer-needed if anyone thinks this project still has a place in the tree. Personally, I think it's waste of time for both the maintainer and the proxy-maintainer team.

Sad to see you go, but I understand. How about moving it to https://wiki.gentoo.org/wiki/Project:GURU ?

**Pull request closed without merging**
