### PR TITLE
net-im/discord: Add wayland support

### PR DESCRIPTION
**Pull request by bigfootjon**
Discord appears to support wayland when launched with these options, it just needs to be enabled manually.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by kostadinsh** [comment]
`--ozone-platform-hint=auto` should be sufficient

**Comment by bigfootjon** [comment]
I initially thought so too, but this didn’t work when I tried it locally. I didn’t have time to look into why since this option worked

**Comment by bigfootjon** [comment]
Finally had a chance to try it again and got this with `...=auto`:

```
[1640305:0613/191504.741763:FATAL:platform_selection.cc(45)] Invalid ozone platform: auto
Trace/breakpoint trap (core dumped)
```

**Comment by bigfootjon** [comment]
`auto` still doesn't work even after updating my system to 0.0.57. This is the last package that I use that depends on xwayland so I'd really like to see this merged!

**Pull request closed without merging**
