### PR TITLE
net-im/profanity: bump to 0.9.5

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by andrey-utkin** [comment]
Thanks, merged as 4443cbeea54b0100b3c8557fa676d00b63782735

@jsmolic would you be interested in becoming Gentoo developer?

**Comment by jsmolic** [comment]
@andrey-utkin Thank you! Yes, I would very much like to become Gentoo developer. I have not managed to find a mentor yet, so I will try to work on that and on the ebuild quiz as well.

**Comment by andrey-utkin** [comment]
@jsmolic in my opinion the role of mentor is overrated. Feel free to treat me as your mentor. I will answer your questions as I can. The most important step is to answer the ebuild quiz (a very boring but currently a necessary step, sorry).

**Comment by jsmolic** [comment]
@andrey-utkin Thank you very much. I do not mind answering the quiz, I am aware that ebuild maintenance requires knowledge and attention to details. I will start working on the ebuild quiz, it might take me few weeks before I complete all questions. Can I contact you via mail after I make some progress with the quiz?

**Comment by andrey-utkin** [comment]
@jsmolic yes please!

**Pull request closed without merging**
