### PR TITLE
dev-perl/Image-Sane: New ebuild, continuation of dev-perl/Sane

### PR DESCRIPTION
**Pull request by cjmayo**
Package-Manager: Portage-2.3.6, Repoman-2.3.2

---

Continued development of dev-perl/Sane, can be installed at the same time.
https://sourceforge.net/p/gscan2pdf/mailman/message/35922909/

Needed for new versions of media-gfx/gscan2pdf.

A couple of extra dependencies over dev-perl/Sane and updated to EAPI 6.

Tests pass for me with -j 8.

```
--- Sane-0.50.0-r1.ebuild
+++ Image-Sane-0.12.ebuild
-EAPI=5
+EAPI=6
 
-MODULE_AUTHOR=RATCLIFFE
-MODULE_VERSION=0.05
+DIST_AUTHOR=RATCLIFFE
 inherit perl-module
 
-DESCRIPTION="The Sane module allows you to access SANE-compatible scanners in a Perl"
+DESCRIPTION="The Image-Sane module allows you to access SANE-compatible scanners from Perl"
 
 SLOT="0"
-KEYWORDS="amd64 x86"
+KEYWORDS="~amd64 ~x86"
 IUSE="test"
 
-RDEPEND=">=media-gfx/sane-backends-1.0.19"
+RDEPEND="
+	dev-perl/Exception-Class
+	>=media-gfx/sane-backends-1.0.19"
 DEPEND="${RDEPEND}
 	dev-perl/ExtUtils-Depends
 	dev-perl/ExtUtils-PkgConfig
-	test? ( dev-perl/Test-Pod )"
-
-SRC_TEST="do"
+	test? (
+		dev-perl/Test-Pod
+		dev-perl/Test-Requires )"
```

### CODE REVIEW

**Comment by cjmayo** [comment]
@gentoo/perl

**Comment by monsieurp** [comment]
Thanks for the PR. LGTM. @kentfredric @akhuettel what's your take on this?

**Comment by kentfredric** [comment]
Note, there's a reason we have the version scheme with x.yyy.zz and not upstreams version: Upstream versions and gentoo versions are incompatible with each other.

Hence, this should have a version that is produced by `dev-perl/Gentoo-PerlMod-Version` via 
```bash
gentoo-perlmod-version.pl 0.12
# 0.12 => 0.120.0
```

So "0.120.0" is the correct version for use in Gentoo.

Yes, it deviates from the rest of Gentoo, but that's mostly because upstreams *other* than Perl happen to use the same version semantics as Gentoo does. Perl's version scheme is weird and surprising, and this normalization takes away most of the problems.

**Comment by kentfredric** [comment]
+		dev-perl/Test-Pod
+		dev-perl/Test-Requires )

Dependencies on Test-Pod usually indicate a mortal sin, which should be avoided if all possible:

Primarily: Authortests being exposed to users.

Pod, Pod-Coverage, Perl-Critic and the like have no place being run on Gentoo users machines, as they only serve as a source of false-failures, and discourage people from testing, and additionally complicate the dependency tree of testing, and additionally complicate stabilization efforts.

Hence, for those kinds of tests, depending on how they're done, we make use of either the variable `PERL_RM_FILES=( )` or the function `perl_rm_files`  ( If you have app-portage/eclass-manpages installed, you can read their documentation with `man perl-module.eclass` )

**Comment by kentfredric** [comment]
Also, the DESCRIPTION is a bit crazy.

> The Image-Sane module  

This is not helpful to anyone. We already know what it is, so the DESCRIPTION should be reduced to describe its purpose, not what it is.

**Comment by kentfredric** [comment]
Dependencies upstream also indicate you need a runtime dep on `dev-perl/Readonly`, 

And there's a directory full of examples that should probably be added with:

```bash
DIST_EXAMPLES=( "examples/*" )
```

Before the inherit line.

**Comment by cjmayo** [comment]
Thanks for the explanations:
- Renumbered as 0.120.0
- dev-perl/Test-Pod removed. Works fine, test just skips if not installed
- DESCRIPTION simplified
- Added DIST_EXAMPLES

**Comment by kentfredric** [comment]
> Works fine, test just skips if not installed

I prefer the test itself nuked. Mostly, because even having the test *run* if it *is* installed, is a potential problem.

There are historically quite a few failures in portage which are functionally *useless*, because they fail the Pod tests.

What does this mean for the code? Nothing. There's nothing wrong with the code when Pod tests fail.

And because the tests and the rules are defined *externally*, a dist can be fine today, and fail tomorrow, all without adding any value.

And there are a bunch of other tests in that dist that are useless in the same way: That when they do their job, they're useless, and when they don't do their job, they're useless.

-  `t/pod.t`   - as above 
- `t/91_critic.t` - same problem, domain, useless test 
- `t/90_MANIFEST.` - Again, useful only to authors (half of it requires running from the git checkout, and the other half just checks somebody put the right version in the documentation )

All 3 tests should never be permitted to execute, and will only waste cpu cycles loading loading the 30 files that make up newer Test::More versions to simply execute a print statement, in the best of conditions.

**Comment by cjmayo** [comment]
OK (I'll use this in my own gscan2pdf test ebuild). Added:

```
PERL_RM_FILES=( t/{90_MANIFEST,91_critic,pod}.t )
```

**Comment by kentfredric** [comment]
Thanks, merged.

**Pull request closed without merging**
