### PR TITLE
Kodi fixes and improvements

### PR DESCRIPTION
**Pull request by Karlson2k**
Fixed Kodi dependencies, required combinations of use flags and other minor improvements.

Looks like many dependencies were just taken from Kodi documentation, while some of them are used only to build internal version of some system libraries. As Kodi on Gentoo uses system libraries (except FFmpeg), there are no need for many dependencies.

### CODE REVIEW

**Comment by Karlson2k** [comment]
Looks like BDEPEND/RDEPEND need some more work. The rest is fine.

**Comment by Karlson2k** [comment]
Added `metadata.xml` information from previous PRs (seems accidentally missing), added some simplification.

@candrews Could you have a look?

**Comment by Karlson2k** [comment]
Added 'eventclients' USE flag.

I think this is a final commit as currently all Kodi parameters are handled. Not more commits are expected before release of v19.

**Comment by Karlson2k** [comment]
@gentoo-repo-qa-bot Second time reports already fixed error and referred non-existing strings in ebuild. 
What's going on?

**Comment by Karlson2k** [comment]
Thanks, @candrews!
The Kodi release is postponed, but probably will be made in the next few days. Just need to make a final polishing.

**Comment by candrews** [comment]
I'm super psyched for the release!

And thank you for your work on the ebuilds in Gentoo :clap:

**Pull request closed without merging**
