### PR TITLE
Graduate loong profiles from exp status

### PR DESCRIPTION
**Pull request by xen0n**
The day has come!

### CODE REVIEW

**Comment by xen0n** [comment]
tl;dr: `PROPERTIES="live"`

Seems we have to wait a bit more ;-)

**Comment by mgorny** [comment]
You can drop that when you're adding keywords. I've merely added it to silence "no KEYWORDS" warnings.

**Comment by mgorny** [comment]
(or maybe simply because 16.x didn't have snapshots at the time)

**Comment by xen0n** [comment]
> You can drop that when you're adding keywords. I've merely added it to silence "no KEYWORDS" warnings.

Thanks for the quick reply and clarification. I'll include those changes for CI shortly. :)

**Review by thesamesam — APPROVED** [review]

**Pull request closed without merging**
