### PR TITLE
[Bug 574304] sys-apps/roccat-tools-3.9 version bump

### PR DESCRIPTION
**Pull request by dpisklov**
Finally, ebuild for sys-apps/roccat-tools-3.9.0 and its dependency dev-libs/libgaminggear, adding support for new devices.

### CODE REVIEW

**Comment by dpisklov** [comment]
commits causing qa issues have been overwritten

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
LGTM.

**Comment by idella** [comment]
Try and move up to using repoman commit for submission of patches.  You will require the gpg key setup to sign the Manifest file, and so forth.  git commit 'works'

**Pull request closed without merging**
