### PR TITLE
media-sound/spotify: bump to 1.0.92, fix compressed doc QA, remove old

### PR DESCRIPTION
**Pull request by realnc**
Fixed QA warning about installing compressed files into /usr/share/doc. File is now decompressed before dodoc.

### CODE REVIEW

**Comment by realnc** [comment]
@prometheanfire revbumped.

**Comment by prometheanfire** [comment]
and I meant to ask if you could amend your commits :|

**Comment by juippis** [comment]
@realnc, if you want to automate that signed-off-by thingie, add `DCO_SIGNED_OFF_BY="Nikos Chantziaras <realnc@gmail.com>"` into your make.conf to get it right everytime with repoman. I presume you've already read and agreed the new terms.
Sorry for jumping in, but you seem active and thought this tip would come handy in future.

**Comment by realnc** [comment]
@juippis Thanks for the tip. Didn't know that.

@prometheanfire Changed the signed-off-by line. I had looked at a few examples on GH to check how it's supposed to be formatted, but it seems GH just eats up the angle brackets when displaying them in comments.

**Comment by prometheanfire** [comment]
your first commit still doesn't have a properly formatted singoff

https://github.com/gentoo/gentoo/pull/10249/commits/a80e7379d46de0de0607474ae216053b4b55b2e9

**Pull request closed without merging**
