### PR TITLE
app-misc/fzf: new package

### PR DESCRIPTION
**Pull request by heroin-moose**
Closes: https://bugs.gentoo.org/718142
Signed-off-by: Olaf Torvaldsson <consus@ftml.net>

### CODE REVIEW

**Comment by Alessandro-Barbieri** [comment]
See also #15377

**Comment by heroin-moose** [comment]
Damn, missed that.

**Comment by heroin-moose** [comment]
This ebuild does have a fix for the compilation error (LDFLAGS not escaped, patch submitted upstream). Also I had a very productive session on #gentoo-dev-help addressing some of the issues of the #15377.

**Comment by juippis** [comment]
Are there still some notable differences between this and #15377? I'd like to merge #15377 and you can become the co-maintainer for that and work with the current maintainer in discussing and fixing what you find.

**Comment by heroin-moose** [comment]
Why not.

**Pull request closed without merging**
