### PR TITLE
net-im/telegram-desktop-bin: version bump to v1.8.4 and cleanup

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by henning-schild** [comment]
I actually think the binary should be moved to /opt for clean packaging of a -bin ebuild. Let me know what you think about that. If you agree i would make this move in this PR. And that might require a bug, not sure.

**Comment by henning-schild** [comment]
renaming to WIP, upstream came with a new bugfix release, comments on opt still welcome

**Comment by juippis** [comment]
/opt is usually used when programs don't respect the unix/linux filesystem hierarchy and "require" the directory structure to be as it is in order for the program to work. In my eyes, it doesn't seem to be the case with this one. This just installs a binary, a .desktop launcher and some icons. Everything seems to be in place. I don't really mind either way where the bin lies, as long as it doesn't break stuff. 
However I don't agree with the way you're making the change. First bumping version, then a separate commit with weird replicate of a wrapper. 
Whatever you decide, just do it in a single version bump and maybe add some REPLACING_VERSIONS info message that the path has been changed.

**Comment by henning-schild** [comment]
The weird structure was just so that someone could merge the first two without merging the move to opt. I just dropped that now and we are good to go.

**Pull request closed without merging**
