### PR TITLE
dev-util/jenkins-bin: Move LTS version to SLOT="lts"

### PR DESCRIPTION
**Pull request by bjacquin**
Bump LTS version to 2.32.1

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by monsieurp** [comment]
@bjacquin hi! patrick never looks at Github PRs. Your contribution will rot away here forever unless a bug is filed.

**Comment by bjacquin** [comment]
Thanks @monsieurp I created https://bugs.gentoo.org/show_bug.cgi?id=607434

**Comment by bjacquin** [comment]
Thanks, I just created https://bugs.gentoo.org/show_bug.cgi?id=607434

**Comment by bdouxx** [comment]
Is it possible to become a co-maintainer for this package?
It's a binary package which have a new version each week : https://jenkins.io/changelog/
There is no specific update in ebuild file, only a new version in the name

**Comment by bjacquin** [comment]
Closing this request since it was handled in https://bugs.gentoo.org/show_bug.cgi?id=607434

**Pull request closed without merging**
