### PR TITLE
sci-mathematics/jags: Version bump for 4.3.0

### PR DESCRIPTION
**Pull request by xfim**
Also, updated to EAPI 7.

Package-Manager: Portage-2.3.89, Repoman-2.3.20

### CODE REVIEW

**Comment by xfim** [comment]
Closes: https://bugs.gentoo.org/711304

**Comment by xfim** [comment]
Can we close this by accepting the PR and merge it to the main branch?

**Comment by ajakk** [comment]
Not quite yet. Please squash your commits and make sure the signoff ends up in the resulting commit.

**Comment by AndrewAmmerlaan** [comment]
I squashed them for you while merging. Next time please use `git rebase -i HEAD~2` and change `pick` for the final commit to `squash` to squash the commits into one. If you are unfamiliar with the procedure, I recommend reading a tutorial on interactive git rebasing, because it is not quite trivial.

(Also EAPI 7 introduces `BDEPEND`, which we should use here for the packages that are *executed* during the build phase of this package)

**Comment by xfim** [comment]
Thank you, @AndrewAmmerlaan for your tip and explanation. I will try to proceed with more care next time.

**Pull request closed without merging**
