### PR TITLE
net-vpn/protonvpn-cli: vbump

### PR DESCRIPTION
**Pull request by ILMostro**
Closes: https://bugs.gentoo.org/753296
* version bump to 2.2.4

Package-Manager: Portage-3.0.8, Repoman-3.0.2
Signed-off-by: Amel Hodzic <ilmostro7@gmail.com>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Please split adding and removing versions to separate commits.

**Comment by ILMostro** [comment]
Yikes,

I'm not sure if I still have access to this.

**Comment by ILMostro** [comment]
All right,

I've separated the vbump and the removal of v2.2.0 into two separate commit now.

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Nope. All commits must be signed off.
https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

**Review by juippis — COMMENTED** [review]
Your sign-off is not good enough, please read 
https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin

Come on it can't be this hard with you everytime...
You can add the `SIGNED_OFF_BY` line in your *make.conf* to make it happen automatically with **repoman**. And you can override this env variable if you don't want to sign off other stuff you commit. Or make an alias `prrepoman` to sign these PRs.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
