### PR TITLE
app-accessibility/speech-dispatcher: bump version and fix the default backend

### PR DESCRIPTION
**Pull request by mehw**
This fixes the default backend in `app-accessibility/speech-dispatcher-0.9.1`, and bumps to version `0.10.2`.

**Keywords changed to espeak-ng's ones to pass the tests: `KEYWORDS="~amd64 ~arm ~arm64 ~ppc ~ppc64 ~x86"`.**

`speech-dispatcher-0.10.2` compiles and runs fine when executing `spd-say hello`.

The default backend for both `0.9.1` and `0.10.2` is `espeak-ng` (see [speechd.conf v0.9.1](https://github.com/brailcom/speechd/blob/5471644fe0e11377d564fd4040832cbe910f3957/config/speechd.conf) and [speechd.conf v.0.10.2](https://github.com/brailcom/speechd/blob/82029c88efcf5a7ef9f480440aad91a826dd5219/config/speechd.conf)).

Also, `app-accessibility/festival-freebsoft-utils` is no longer in the tree, suggest to look at https://freebsoft.org/festival-freebsoft-utils intead.

Thanks.

`$ diff speech-dispatcher-0.9.1.ebuild speech-dispatcher-0.9.1-r1.ebuild`
```
15,16c15,16
< KEYWORDS="~alpha amd64 arm arm64 ~hppa ~ia64 ppc ppc64 ~riscv sparc x86 ~amd64-linux ~x86-linux"
< IUSE="alsa ao +espeak flite nas pulseaudio python"
---
> KEYWORDS="~amd64 ~arm ~arm64 ~ppc ~ppc64 ~x86"
> IUSE="alsa ao espeak +espeak-ng flite nas pulseaudio python"
27a28
> 	espeak-ng? ( app-accessibility/espeak-ng )
51a53
> 		$(use_with espeak-ng)
98,99c100,101
< 	if ! use espeak; then
< 		ewarn "You have disabled espeak, which is speech-dispatcher's"
---
> 	if ! use espeak-ng; then
> 		ewarn "You have disabled espeak-ng, which is speech-dispatcher's"
115,116c117,118
< 	elog "For festival support, you need to"
< 	elog "install app-accessibility/festival-freebsoft-utils."
---
> 	elog "For festival support, you need to install"
> 	elog "https://freebsoft.org/festival-freebsoft-utils"

```

`$ diff speech-dispatcher-0.9.1-r1.ebuild speech-dispatcher-0.10.2.ebuild`
```
38,39d37
< PATCHES=( "${FILESDIR}/${P}-fno-common.patch" )
< 
49a48
> 		--with-voxin=no

```

### CODE REVIEW

**Comment by fordfrog** [comment]
@mehw thanks for the bump and the comment to it, it is really helpful :-)

@thesamesam please how do we handle those dropped arches? i'm not familiar with the status of those and which of them we still actively support.

**Comment by mehw** [comment]
@fordfrog you're welcome ;)

@thesamesam, below the errors running [CI](https://qa-reports.gentoo.org/output/gentoo-ci/2c295ef570/output.html#app-accessibility/speech-dispatcher):
```
0.10.2 | NonsolvableDepsInDev | nonsolvable depset(depend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInDev | nonsolvable depset(rdepend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInStable | nonsolvable depset(depend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (20 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInStable | nonsolvable depset(rdepend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (20 total): solutions: [ app-accessibility/espeak-ng ]

0.9.1-r1 | NonsolvableDepsInDev | nonsolvable depset(depend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInDev | nonsolvable depset(rdepend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInStable | nonsolvable depset(depend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (20 total): solutions: [ app-accessibility/espeak-ng ]
  | NonsolvableDepsInStable | nonsolvable depset(rdepend) keyword(~alpha) stable profile (default/linux/alpha/17.0) (20 total): solutions: [ app-accessibility/espeak-ng ]
```

**Comment by mattst88** [comment]
cc: @williamh

**Comment by mehw** [comment]
The default backend has been fixed in the latest speech-dispatcher-0.11.1 ebuild, version 0.9.1 is still unfixed, though.

This PR could be considered kinda of obsolete now.

**Pull request closed without merging**
