### PR TITLE
app-admin/gtkdiskfree: Fix call to undeclared function setlocale

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/894204

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Can't test this on musl due to https://bugs.gentoo.org/908071 :\

**Comment by listout** [comment]
> Can't test this on musl due to https://bugs.gentoo.org/908071 :\

It requires musl-1.2.3-rx for librsvg to get librsvg

**Comment by juippis** [comment]
Yeah but we should look into patching librsvg for musl-1.2.4 before fixing its deps. Or if that seems impossible, we can mask the broken version on musl profile.

**Comment by thesamesam** [comment]
For now, please just test with musl-1.2.3 instead wrt librsvg/Rust issues.

**Comment by juippis** [comment]
I can indeed make a binpkg using musl-1.2.3 to not hit this issue every time, but I do feel like it should be fixed with profiles if possible.

**Comment by thesamesam** [comment]
It's orthogonal to this and not worth worrying about here given the Rust situation is a massive headache. That's being handled separately.

**Comment by juippis** [comment]
Oh yes, don't worry I wasn't asking @listout to handle the masking :) just talking out loud here, I'm willing to get involved **if** there is no plan in place! 

I'll process this PR tomorrow.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
