### PR TITLE
app-office/gtg: add ebuild for 0.6 and drop 0.4.0

### PR DESCRIPTION
**Pull request by ran-dall**
This commit also bumps Python compatibility up to `3.10`.

Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
Please drop old in a separate commit.

**Comment by thesamesam** [comment]
The release notes mention using `pytest` now:
```

+ Backend, Code Quality, and Performance Improvements:
+
[...]
+ • Switched to Pytest for unit testing
+
```

**Comment by thesamesam** [comment]
Fixed, thanks. Please make sure to run tests when bumping though.

**Comment by ran-dall** [comment]
> Fixed, thanks. Please make sure to run tests when bumping though.

@thesamesam My bad, will do from now on. Thank you for taking care of it, and letting me know.

**Pull request closed without merging**
