### PR TITLE
sys-boot/uefi-mkconfig: Add v2.0 and drop v1.4 and v1.5

### PR DESCRIPTION
**Pull request by Biosias**
Add version 2.0 and remove 1.4 and 1.5

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
There's some problem, if there are kernels installed in the efistub layout then uefi-mkconfig adds no entries

**Comment by Biosias** [comment]
Hmmm, could you send me output of uefi-mkconfig and also ls of said directory ? This is very weird, I've tested this on a few separate machines and haven't seen anything like this

**Comment by AndrewAmmerlaan** [comment]
Not at home right now but the layout was:
```
/efi/EFI/Gentoo/kernel-6.9.9-gentoo-dist.efi
/efi/EFI/Gentoo/initramfs-6.9.9-gentoo-dist.img
/efi/EFI/Gentoo/intel-uc.img
/efi/EFI/Linux/linux-6.9.9-gentoo-dist.efi
```
I.e. one kernel version in both UKI and plain format

Output was first the warning about empty `uefi-mkconfig` config file (intentional, I don't need a cmdline), then warning about missing `root=` (also intentional) then it should says that it is adding entries for those two kernels (UKI and plain) but it does not.

**Comment by Biosias** [comment]
Could you please open an issue for this on uefi-mkconfig repo? I'll close this PR until this is investigated.

Just to add, I just simulated what you have described and it worked correctly.

**Comment by AndrewAmmerlaan** [comment]
Opened as https://github.com/Biosias/uefi-mkconfig/issues/16

**Pull request closed without merging**
