### PR TITLE
Add symbolic icon size to desktop.eclass

### PR DESCRIPTION
**Pull request by ixti**
Signed-Off-By: Alexey Zapparov <alexey@zapparov.com>

### CODE REVIEW

**Comment by ixti** [comment]
cc: @mgorny @ulm

**Comment by ulm** [comment]
Where is `symbolic` specified? https://specifications.freedesktop.org/icon-theme-spec/icon-theme-spec-latest.html doesn't have it.

**Comment by ixti** [comment]
@ulm I think it's Gnome's thing:

* https://developer.gnome.org/hig/guidelines/ui-icons.html
* https://wiki.gnome.org/Design/OS/SymbolicIcons

```
> equery belongs /usr/share/icons/hicolor/symbolic/apps/* | cut -f1 -d' ' | uniq
app-arch/file-roller-3.42.0
app-crypt/seahorse-41.0-r1
app-dicts/gnome-dictionary-40.0-r1
app-editors/gedit-42.0
app-text/evince-42.2
games-arcade/gnome-nibbles-3.38.2
games-arcade/gnome-robots-40.0
games-board/four-in-a-row-3.38.1
games-board/gnome-chess-42.0
games-board/gnome-mahjongg-3.38.3
games-board/gnome-mines-40.1
games-board/iagno-3.38.1
games-board/tali-40.7
games-puzzle/five-or-more-3.32.3
games-puzzle/gnome-klotski-3.38.2
games-puzzle/gnome-sudoku-42.0
games-puzzle/gnome-taquin-3.38.1
games-puzzle/hitori-3.38.3
games-puzzle/lightsoff-40.0.1
games-puzzle/quadrapassel-40.2
games-puzzle/swell-foop-41.1
gnome-base/gnome-control-center-42.1
gnome-base/gnome-shell-42.1
gnome-base/nautilus-42.1.1
gnome-extra/gnome-boxes-42.0.1
gnome-extra/gnome-calculator-42.0
gnome-extra/gnome-calendar-42.1
gnome-extra/gnome-characters-42.0
gnome-extra/gnome-clocks-42.0
gnome-extra/gnome-contacts-42.0
gnome-extra/gnome-system-monitor-42.0
gnome-extra/gnome-tweaks-40.10
gnome-extra/gnome-weather-42.0
gnome-extra/yelp-42.1
mail-client/evolution-3.44.1
media-gfx/eog-42.1
media-gfx/gnome-font-viewer-42.0
media-gfx/gnome-photos-42.0
media-gfx/gnome-screenshot-41.0
media-gfx/inkscape-1.1.2-r1
media-gfx/shotwell-0.30.15
media-gfx/simple-scan-42.1
media-sound/gnome-music-42.1
media-sound/helvum-0.3.4-r1
media-video/cheese-41.1
media-video/mpv-0.34.1-r1
media-video/peek-1.5.1
media-video/totem-42.0-r1
net-libs/gnome-online-accounts-3.44.0
net-p2p/transmission-3.00-r1
sys-apps/baobab-42.0
www-client/epiphany-42.2
www-client/firefox-bin-101.0.1
x11-terms/gnome-terminal-3.44.0
```

**Comment by ulm** [comment]
@gentoo/gnome: Do you approve?

**Review by leio — APPROVED** [review]

**Comment by ulm** [comment]
By the policy in https://devmanual.gentoo.org/eclass-writing/index.html#adding-and-updating-eclasses the patch should be posted to the gentoo-dev list for review.

@ixti: Can you post this to the mailing list, or should I do it?

**Comment by ixti** [comment]
> @ixti: Can you post this to the mailing list, or should I do it?

@ulm I have posted patch to gentoo-dev ML (cc-d base-system, you, and @leio). Hope I made it right. Although I completely forgot to sign the message. :D

**Comment by ulm** [comment]
Thanks.

**Pull request closed without merging**
