### PR TITLE
net-nntp/nzbget: version bump to v16.4

### PR DESCRIPTION
**Pull request by tomboy-64**
A couple of slight changes, so it works with the new github download location. Also AUTHORS has been removed; README.md has been added.
Everything else is the same.

### CODE REVIEW

**Comment by tomboy-64** [comment]
@swegener

**Comment by tomboy-64** [comment]
@gentoo/proxy-maint might be a job for you guys. as seen [here](bugs.gentoo.org/show_bug.cgi?id=550486) the ebuild maintainer seems to slack off a bit.

**Comment by swegener** [comment]
Please download the .tar.gz instead of the .zip.

Upstream provides release tarballs at https://github.com/nzbget/nzbget/releases/tag/v16.4
Sometimes the build system generates files for releases that are not under version control. It seems to work here, because they are checking in the configure script, which I personally dislike, because it might lead to spurious timestamp-based rebuilds.

**Comment by tomboy-64** [comment]
@swegener Changed the URI. Also added slots to the dependency on ncurses and openssl to make repoman warnings go away.

**Pull request merged**
