### PR TITLE
app-admin/logstash-bin: bump to 5.5.3/5.6.1, drop old

### PR DESCRIPTION
**Pull request by hydrapolic**

### CODE REVIEW

**Comment by ferki** [comment]
Nice, thanks!

Couple of quick questions (without testing these cases out yet):
1. Would the move of the pidfile interfere with shutting down an already running instance? (Also, should existing users remove the old pidfile dir?)
2. Should users move the data they may already have in `/opt/logstash/data`?

I _guess_ it might be enough to just notify the users on upgrade, to make sure they can check if they need clean up and/or move data properly (on first install these doesn't seem to matter).

**Comment by hydrapolic** [comment]
1) Yes, the logstash instance will not stop and the user will notice as he will not be able to start a new one. But I do suppose the Gentoo users are smart enough to find the old process and kill it (there will be a hint in the log "already running"). The old piddir will disappear after the reboot, so no action is needed.

2) I only run two instances of logstash, but haven't found anything valuable in the data directory - only the uuid that is generated automatically.

**Comment by ferki** [comment]
I believe the data directory mostly (only?) used for the persistent queue, which might be important during non-normal operation (e.g. abnormal pipeline termination, or similar), that might happen after moving the pidfile, and killing the process forcefully (see [Shutting Down Logstash](https://www.elastic.co/guide/en/logstash/5.5/shutdown.html)).

Other use case for the persistent queues is to provide buffering during bursts and/or when the delivery is slower than the incoming amount of logs. So normally there's no data, but if there is something, then it is most probably important (and need to be picked up by the new process).

I also think Gentoo users who are using persistent queues are also able to shut down the old instance properly, and check if there's any data to be moved. Though after thinking a lot about this, I'd say the ebuild should at least remind the user about these, as I'm afraid it can lead to a potential data loss. Something along the lines of:

```
The default pidfile directory has been changed from /run/logstash to /run. Please ensure any running logstash processes are shut down cleanly.
The default data directory has been moved from /opt/logstash/data to /var/lib/logstash/data. Please check and move its contents as necessary.
```

Maybe I'm just overly cautious :)

**Comment by hydrapolic** [comment]
Yeah, that sounds reasonable @ferki. I'll add it to the PR and bump to 5.5.3 instead.

Thanks!

**Comment by hydrapolic** [comment]
@ferki @orlitzky, ok with this PR?

**Comment by ferki** [comment]
@hydrapolic: for me, it looks working correctly and as intended :+1:

**Comment by orlitzky** [comment]
Personally I would remove `LS_PIDFILE` from the conf.d file and just set `pidfile="/run/${RC_SVCNAME}.pid"` (which will be unique, because the service name is). That way no one can try to change the PID file location and cause themselves problems. But the vulnerability is fixed, so it's good by me.

**Comment by hydrapolic** [comment]
Yes that's a good point, I'll make it so.

**Comment by orlitzky** [comment]
Pulled, thank you!

**Comment by hydrapolic** [comment]
Thanks @orlitzky and @ferki.

**Pull request closed without merging**
