### PR TITLE
Cleanup

### PR DESCRIPTION
**Pull request by a17r**
some are broken by >=OpenSSL-1.1, some are EAPI-cleanups, all are overshadowed by latest stable versions.

### CODE REVIEW

**Comment by robbat2** [comment]
+1 for these as base-system/sysadmin:
net-firewall/ebtables: @gentoo/base-system
sys-apps/groff: @gentoo/base-system
sys-apps/ipmitool: @gentoo/sysadmin
sys-block/vblade: @gentoo/base-system

**Comment by a17r** [comment]
@aballier

**Comment by aballier** [comment]
> @aballier

sorry, i had missed that

if that's just removing overshadowed versions and CI is happy, then I'm fine with it

**Comment by a17r** [comment]
> if that's just removing overshadowed versions and CI is happy, then I'm fine with it

Thanks!

**Pull request closed without merging**
