### PR TITLE
Exiv2 9999 ebuild

### PR DESCRIPTION
**Pull request by dannftk**
Provided the exiv2 ebuild that lets you obtain the lastest sources from github

### CODE REVIEW

**Comment by dannftk** [comment]
May someone take a look at it?

**Comment by a17r** [comment]
Who is going to maintain it?

**Comment by dannftk** [comment]
Maintain what? This is the ebuild providing an opportunity to fetch the latest sources, nothing more. Plenty of gentoo's packages have this type of ebuild, don't they?

**Comment by a17r** [comment]
Every ebuild needs maintenance, if no one does that, there is no point in having it.

**Comment by dannftk** [comment]
What does 'maintenance' imply in this case? What responsibilities must a maintainer carry on?

**Comment by a17r** [comment]
Tracking upstream to keep dependencies up to date, keeping the ebuild itself up to date in relation to the eclass and EAPI updates, bumping subslot, answering to bugs filed related to the live ebuild.

**Comment by dannftk** [comment]
There are maintainers @gentoo/graphics and @gentoo/kde, we might need to reach out to them

**Comment by a17r** [comment]
Yes, there is graphics@..., but I have been basically the only one doing version bumps and taking care of security bugs on this package for more than 4 years. I did not feel the urge to add a live ebuild during all that time.

**Comment by dannftk** [comment]
I just need this package built against c++17, but current version 0.27.2 does not allow this because it declares std::auto_ptr forbidden in c++17. The new release is gonna be published on unknown time, the main contributor has retired from the project. I thought it would be useful to provide a live ebuild since the project is in [hard-maintenance mode](https://github.com/Exiv2/exiv2/issues/1018). So, do we need still to wait a new release 0.27.3 up and provide the ebuild for it? Or can we provide a live ebuild to keep up with the latest changes those are promised to contain bug fixes only in the nearest time? Is it dangerous to provide a live ebuild? As I understand, live ebuild doesn't promise anything, it is known to be unstable-prone since it is fetched from the always updated repository, even though the master branch of a project is pulled up

**Comment by a17r** [comment]
> I just need this package built against c++17, but current version 0.27.2 does not allow this because it declares std::auto_ptr forbidden in c++17.

You need it? Or a dependency needs it? Can you provide a link?

**Comment by dannftk** [comment]
Ok, I've realized you haven't stood by the idea of providing live ebuild, I will roll the changes back 
May I provide a patch that will get the exiv-0.27.2 to support C++11/C++14/C++17? I will get rid of 'register' storage specifier for some variables and substitute std::auto_ptr by safer type std::unique_ptr. Both 'register' and std::auto_ptr are deprecated stuff in c++11/c++14 and removed in c++17. My motivation is that compilers are getting developed and supported newer standards, sooner or later it will come to getting most of packages to work with >= c++11 and then >= c++17. One of the reverse dependency is gexiv2 project, it uses c++11. Due to this, gexiv2 warns that exiv2's header uses std::auto_ptr which is deprecated and also is confirmed to be bad practice. I prepared the patch that gets rid of std::auto_ptr and 'register' specifier, basing on the commits from the exiv2 project
If some reverse dependency like gexiv2 happen to move to c++17 we will be ready

**Pull request closed without merging**
