### PR TITLE
dev-python/backports-functools-lru-cache: remove conflicting bytecode files

### PR DESCRIPTION
**Pull request by sbraz**
Credits to @mgorny

### CODE REVIEW

**Comment by sbraz** [comment]
Please don't merge, I have to fix something.

**Comment by sbraz** [comment]
Edited to fix https://bugs.gentoo.org/show_bug.cgi?id=621196

**Comment by sbraz** [comment]
I still have `/usr/lib64/pypy3/site-packages/backports/__pycache__/__init__.pypy3-57.pyc` and other similar files,  I don't know how to properly delete those.

**Comment by floppym** [comment]
backports-functools-lru-cache-1.4 only supports python2, so you do not need to worry about the `__pycache__` directory for this package.

**Pull request closed without merging**
