### PR TITLE
net-p2p/airdcpp-webclient: new package and its Web UI

### PR DESCRIPTION
**Pull request by sbraz**
Please don't merge, I'm not entirely done with this (I plan on adding an init script) but I'd like some feedback :)
Ping @gktrk @monsieurp 
Related issue upstream: https://github.com/airdcpp-web/airdcpp-webclient/issues/38

### CODE REVIEW

**Comment by gktrk** [comment]
I'm not exactly sure about airdcpp-webui only depending on airdcpp-webclient. My understanding is that the webui requires nodejs, but webclient has nodejs only in DEPEND. I think, at the very least, webui needs to have nodejs in RDEPEND.

Does the webui have the capability to talk to an AirDC++ instance on a remote machine, or is it local-host only? If the former is the case, I would argue that webui does not even depend on webclient. This would be similar to transmission-remote-gtk not pulling in transmission as a dependency. I must admit that I am not familiar with nodejs and apologize if I am not making sense.

@monsieurp is more qualified to comment on this but aren't you introducing a circular dependency by making airdcpp-webclient depend on airdcpp-webui which in turn depends on airdcpp-webclient?

**Comment by idella** [comment]
circular dependencies are highly undesirable, nut sometimes unavoidable. Try to resolve this if it is the case

**Comment by sbraz** [comment]
@gktrk I added the die :)
nodejs is only needed [during installation](https://github.com/airdcpp-web/airdcpp-webclient/blob/master/CMakeLists.txt#L159) and the author and I agreed that this needs to be rewritten using something other than JS.
The web UI itself does not require nodejs, it is served by the daemon (airdcpp-webclient), hence it needs to be on the same host.
You were right about the circular dependencies, I used PDEPEND to avoid them.

**Comment by idella** [comment]
anyway merged

**Pull request closed without merging**
