### PR TITLE
sys-devel/llvm-roc: Version bump to 4.2.0 and QA

### PR DESCRIPTION
**Pull request by justxi**
Signed-off-by: Wilfried Holzke <gentoo@holzke.net>
Package-Manager: Portage-3.0.18, Repoman-3.0.2

### CODE REVIEW

**Comment by justxi** [comment]
@candrews Anything wrong with this?

**Comment by candrews** [comment]
Looks good! Sorry for the delay

**Comment by justxi** [comment]
No problem. Now I can push the other ebuilds.

**Comment by candrews** [comment]
> No problem. Now I can push the other ebuilds.

This PR introduced a bug: https://bugs.gentoo.org/798927

Can you please address it?

**Comment by justxi** [comment]
Yes... sorry... added an old ebuild :(.

**Comment by heroxbd** [comment]
@justxi have you documented the rationale removing `hip-4.0.0-hip-location.patch`？

**Comment by justxi** [comment]
@heroxbd No. It did not apply and if I remember correctly, I was already applied. Otherwise I would had created an updated patch.

**Comment by heroxbd** [comment]
> @heroxbd No. It did not apply and if I remember correctly, I was already applied. Otherwise I would had created an updated patch.

It was removed without a refreshed patch.

**Comment by justxi** [comment]
As I said, I think the patch was no longer necessary.

**Comment by heroxbd** [comment]
> As I said, I think the patch was no longer necessary.

Clarified, thanks!

The patch is still necessary to let llvm-roc find HIP in Gentoo.  It worked because of the `ROCM_PATH` in `/etc/env.d`.   I would like to minimize the usage of environment variables for ROCm and reintroduce this patch.

**Pull request closed without merging**
