### PR TITLE
virtual/jpeg: SLOT=62 should have lower default precedence

### PR DESCRIPTION
**Pull request by SoapGentoo**
* r100-199 is reserved for SLOT=62
* >=r200 is reserved for SLOT=0, in order to take precedence
  over the SLOT=62 ebuild

Package-Manager: Portage-2.3.66, Repoman-2.3.12
Signed-off-by: David Seifert <soap@gentoo.org>

### CODE REVIEW

**Comment by a17r** [comment]
shouldn't we get rid of the virtual altogether?

**Comment by mgorny** [comment]
…or at least the compat slot of the virtual.

**Comment by stefson** [comment]
app-text/mupdf may need some attention, it doesn't say from which slot to choose from.

**Comment by SoapGentoo** [comment]
@stefson mupdf is built from source, hence it should use `SLOT=0`. With the new binary compat package, that isn't relevant anymore though

**Pull request closed without merging**
