### PR TITLE
media-gfx/graphicsmagick: reinstate JPEG-2000 support, remove broken USE="svg"

### PR DESCRIPTION
**Pull request by hhoffstaette**
This reinstates JPEG-2000 support, removes the broken "svg" USE flag and tidies up the imagemagick virtual to make svg optional. Also update HOMEPAGE, git repo and SRC_URI as they changed upstream.

The last commit (updating SRC_URI) is now being flagged by pkgcheck as SuspiciousSrcUriChange (probably a security measure?), so if we prefer server-side redirects then this could be skipped.

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Now that I p.use.masked hppa for jasper, I get similar messages for ppc and ia64:
```
  NonsolvableDepsInDev: version 1.3.43-r1: nonsolvable depset(depend) keyword(~ppc) dev profile (default/linux/ppc/17.0/musl) (55 total): solutions: [ media-libs/jasper:= ]
  NonsolvableDepsInDev: version 1.3.43-r1: nonsolvable depset(rdepend) keyword(~ppc) dev profile (default/linux/ppc/17.0/musl) (55 total): solutions: [ media-libs/jasper:= ]
  NonsolvableDepsInStable: version 1.3.43-r1: nonsolvable depset(depend) keyword(~ia64) stable profile (default/linux/ia64/17.0) (80 total): solutions: [ media-libs/jasper:= ]
  NonsolvableDepsInStable: version 1.3.43-r1: nonsolvable depset(rdepend) keyword(~ia64) stable profile (default/linux/ia64/17.0) (80 total): solutions: [ media-libs/jasper:= ]
```

I tried to p.use.mask for ppc as well, but then it started to complain about ppc64 as well and it made me wonder if I'm missing something; sprinkling more p.use.masks seemed wrong to me, since it indicates that gm has way too many ~arch keywords where it was probably never tested.
Suggestions welcome.

**Comment by hhoffstaette** [comment]
cc: @thesamesam review/push please?

**Comment by thesamesam** [comment]
> sprinkling more p.use.masks seemed wrong to me, since it indicates that gm has way too many ~arch keywords where it was probably never tested.

No, I think it really does work in all those places. But jasper isn't available in all those places, so...

Anyway, the right thing to do is to litter the masks everywhere, yeah, given we tried the kwing bug and it got stuck. I can do that if you want.

**Comment by hhoffstaette** [comment]
> > sprinkling more p.use.masks seemed wrong to me, since it indicates that gm has way too many ~arch keywords where it was probably never tested.
> 
> No, I think it really does work in all those places. But jasper isn't available in all those places, so...
> 
> Anyway, the right thing to do is to litter the masks everywhere, yeah, given we tried the kwing bug and it got stuck. I can do that if you want.



> > sprinkling more p.use.masks seemed wrong to me, since it indicates that gm has way too many ~arch keywords where it was probably never tested.
> 
> No, I think it really does work in all those places. But jasper isn't available in all those places, so...
> 
> Anyway, the right thing to do is to litter the masks everywhere, yeah, given we tried the kwing bug and it got stuck. I can do that if you want.

That would be the fastest way, thank you. Like I said i just wasn't sure if I was missing something, not to mention ppc64 big vs. little endian and whatnot. And why do we still have ia64 :sob:

**Comment by thesamesam** [comment]
OK, lemme do it now so I don't forget ;)

And no, I'm glad you double checked. It's important to do this if something feels off.

**Pull request closed without merging**
