### PR TITLE
net-irc/weechat: remove PHP support, additional maintainer

### PR DESCRIPTION
**Pull request by zpuskas**
Signed-off-by: Zoltan Puskas <zoltan@sinustrom.info>

### CODE REVIEW

**Comment by gyakovlev** [comment]
hey!
can you do 1 thing before we proceed on this?
let's disable php useflag and deps. revbump the last version without removing original, and sync changes to 9999.

context: https://bugs.gentoo.org/705702
tldr: we can't really support php without python-like eclasses and tooling, and it's not that there are many weechat php scripts around ;-) so let's disable instead of pretending we support it.

**Comment by zpuskas** [comment]
Yeah, can do, and it's also a good first task for me on this particular ebuild.

**Comment by zpuskas** [comment]
Done, PHP is removed.

**Comment by gyakovlev** [comment]
thanks!
I separated 9999 commit and merged your changes as is (sans 9999 part).

in case you have weechat PRs and I'm not responsive - I give proxy-main team full permission to merge your PRs, you can point them to this comment in case it's questioned.

**Pull request closed without merging**
