### PR TITLE
dev-java/protobuf-java: add 3.25.2

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
i merged it, but `pkgcheck` is not happy on that package:
```
  NonexistentDeps: version 3.23.0: BDEPEND: nonexistent package: ~dev-libs/protobuf-23.0:0
  NonexistentDeps: version 3.25.1: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.1:0
  NonexistentDeps: version 3.25.2: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.2:0
```

**Comment by vaukai** [comment]
> i merged it, but `pkgcheck` is not happy on that package:
> 
> ```
>   NonexistentDeps: version 3.23.0: BDEPEND: nonexistent package: ~dev-libs/protobuf-23.0:0
>   NonexistentDeps: version 3.25.1: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.1:0
>   NonexistentDeps: version 3.25.2: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.2:0
> ```

maybe something wrong in `profiles/base/package.use.mask`? until we [unmasked it for 3.23.3](https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/base/package.use.mask?id=4d4264ca1d975170a0daff2b3c427be8b7ef4270) there were no such complaints.

**Comment by fordfrog** [comment]
> > i merged it, but `pkgcheck` is not happy on that package:
> > ```
> >   NonexistentDeps: version 3.23.0: BDEPEND: nonexistent package: ~dev-libs/protobuf-23.0:0
> >   NonexistentDeps: version 3.25.1: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.1:0
> >   NonexistentDeps: version 3.25.2: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.2:0
> > ```
> 
> maybe something wrong in `profiles/base/package.use.mask`? until we [unmasked it for 3.23.3](https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/base/package.use.mask?id=4d4264ca1d975170a0daff2b3c427be8b7ef4270) there were no such complaints.

well, those versions are in the deps but don't exist in the main tree.

**Comment by fordfrog** [comment]
> > > > i merged it, but `pkgcheck` is not happy on that package:
> > > > ```
> > > >   NonexistentDeps: version 3.23.0: BDEPEND: nonexistent package: ~dev-libs/protobuf-23.0:0
> > > >   NonexistentDeps: version 3.25.1: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.1:0
> > > >   NonexistentDeps: version 3.25.2: BDEPEND: nonexistent package: ~dev-libs/protobuf-25.2:0
> > > > ```
> > > 
> > > 
> > > maybe something wrong in `profiles/base/package.use.mask`? until we [unmasked it for 3.23.3](https://gitweb.gentoo.org/repo/gentoo.git/commit/profiles/base/package.use.mask?id=4d4264ca1d975170a0daff2b3c427be8b7ef4270) there were no such complaints.
> > 
> > 
> > well, those versions are in the deps but don't exist in the main tree.
> 
> should we try removing those lines from the affected versions, the re-adding them once suitable system-protoc becomes available? is it worth the effort?

are they really needed for building?

**Pull request closed without merging**
