### PR TITLE
kde-{base,plasma}/khelpcenter: pkgmove to kde-apps/khelpcenter

### PR DESCRIPTION
**Pull request by a17r**
@gentoo/kde

### CODE REVIEW

**Comment by johu** [comment]
KDE Plasma is under stabilization. This is not needed yet.

**Comment by a17r** [comment]
I think it'd actually help a bit with KDE4 -> Plasma-5 migration, but yes it can wait.

**Comment by johu** [comment]
Could you please update the PR according to the suggestions made in kde overlay PR (please remove those commits which are not directly needed for the package move)? I want to do the move together with kde overlay PR.

**Comment by a17r** [comment]
Unfortunately need to restore my changes here, will see to have it back in the evening.

**Comment by johu** [comment]
Thanks. Picked.f672644a2ec6bb83642fe1ccbf1cebdcc90d88db..1561088e0875f702d5b569eed05a3bcbfdcb5934

**Pull request closed without merging**
