### PR TITLE
sys-fs/genfstab: bump to 28, EAPI 8

### PR DESCRIPTION
**Pull request by scardracs**
Signed-off-by: Marco Scardovi <mscardovi@icloud.com>

### CODE REVIEW

**Comment by mattst88** [comment]
Your second commit undoes the changes to `metadata.xml` from your first commit.

**Comment by mattst88** [comment]
The commit that dropped you as a maintainer did this:

````diff
-       <maintainer type="person" proxied="yes">
-               <email>marco@scardovi.com</email>
-               <name>Marco Scardovi</name>
-       </maintainer>
-       <maintainer type="person" proxied="proxy">
-               <email>mattst88@gentoo.org</email>
-               <name>Matt Turner</name>
-       </maintainer>
+       <!-- maintainer-needed -->
````

so we should add me as a maintainer rather than proxy-maint.

**Comment by scardracs** [comment]
> Your second commit undoes the changes to `metadata.xml` from your first commit.

I'm gonna fix it ASAP

**Comment by scardracs** [comment]
> The commit that dropped you as a maintainer did this:
> 
> 
> 
> ````diff
> 
> -       <maintainer type="person" proxied="yes">
> 
> -               <email>marco@scardovi.com</email>
> 
> -               <name>Marco Scardovi</name>
> 
> -       </maintainer>
> 
> -       <maintainer type="person" proxied="proxy">
> 
> -               <email>mattst88@gentoo.org</email>
> 
> -               <name>Matt Turner</name>
> 
> -       </maintainer>
> 
> +       
> 
> ````
> 
> 
> 
> so we should add me as a maintainer rather than proxy-maint.

Do you prefer to be only you the maintainer or readd this as is?

**Comment by mattst88** [comment]
Readding as-is is fine with me if you plan to continue maintaining it :)

**Comment by scardracs** [comment]
> Readding as-is is fine with me if you plan to continue maintaining it :)

Yep, I am as actually I'm maintaining both upstream and downstream 😅

**Comment by scardracs** [comment]
It should be ok now

**Pull request closed without merging**
