### PR TITLE
 dev-db/mariadb: bump to 10.3.34/10.3.35

### PR DESCRIPTION
**Pull request by hydrapolic**
Tests pass on amd64:
```
ulimit -n 16500
MTR_PARALLEL=64 USE='extraengine perl server xml' FEATURES='test userpriv' emerge -v1 =dev-db/mariadb-10.3.34
```
```
ulimit -n 16500
MTR_PARALLEL=64 USE='extraengine perl server xml' FEATURES='test userpriv' emerge -v1 =dev-db/mariadb-10.3.35
```

```
--- mariadb-10.3.32.ebuild      2022-05-31 18:32:10.234394185 +0000
+++ mariadb-10.3.34.ebuild      2022-05-31 18:38:13.457031046 +0000
@@ -10,7 +10,7 @@
        multiprocessing java-pkg-opt-2 cmake
 
 # Patch version
-PATCH_SET="https://dev.gentoo.org/~whissi/dist/${PN}/${PN}-10.3.32-patches-01.tar.xz"
+PATCH_SET="https://github.com/hydrapolic/gentoo-dist/raw/master/${PN}/${PN}-10.3.34-patches-01.tar.xz"
 
 SRC_URI="mirror://mariadb/${PN}-${PV}/source/${P}.tar.gz
        ${PATCH_SET}"
@@ -30,9 +30,9 @@
 REQUIRED_USE="jdbc? ( extraengine server !static )
        server? ( tokudb? ( jemalloc !tcmalloc ) )
        ?? ( tcmalloc jemalloc )
-       static? ( yassl !pam )"
+       static? ( yassl !extraengine !pam )"
 
-KEYWORDS="~alpha amd64 arm arm64 ~hppa ~ia64 ~mips ppc ppc64 ~s390 ~sparc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
 
 # Shorten the path because the socket path length must be shorter than 107 chars
 # and we will run a mysql server during test phase
@@ -454,7 +454,7 @@
 }
 
 # Official test instructions:
-# USE='extraengine perl server' \
+# USE='extraengine perl server xml' \
 # FEATURES='test userpriv' \
 # ebuild mariadb-X.X.XX.ebuild \
 # digest clean package
@@ -682,6 +682,9 @@
                        rm "${ED}/usr/bin/${scriptremove}" || die
                fi
        done
+
+       # Remove dangling symlink
+       rm "${ED}/usr/$(get_libdir)/libmariadb.a" || die
 }
 
 pkg_preinst() {
```

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
With 
```
USE="-backup bindist client-libs -cracklib extraengine galera -innodb-lz4 -innodb-lzo innodb-snappy -jdbc -jdbc jemalloc kerberos -latin1 -mroonga numa odbc oqgraph -pam perl profiling -rocksdb server -sphinx -sst-mariabackup -sst-rsync static -systemtap -tcmalloc tokudb xml yassl" emerge -1av =dev-db/mariadb-10.3.34
```
I get:
```
CMake Error at cmake/plugin.cmake:298 (MESSAGE):
  Plugin SPIDER cannot be built
Call Stack (most recent call first):
  CMakeLists.txt:424 (CONFIGURE_PLUGINS)
```

Let me know if you can't replicate, I'll upload the logs (they seem pretty huge)

```
The servers were restarted 1016 times
Spent 4756.446 of 1777 seconds executing testcases

Completed: All 3586 tests were successful.

677 tests were skipped, 256 by the test itself.

 * Tests successfully completed
>>> Completed testing dev-db/mariadb-10.3.34
```

**Comment by hydrapolic** [comment]
> 

Thanks for testing, seems like this combination is problematic (testing with 10.3.35):

USE="extraengine static yassl -pam" emerge -1av =dev-db/mariadb-10.3.35

**Comment by hydrapolic** [comment]
Added blocker on extraengine for USE=static.

**Comment by hydrapolic** [comment]
Thank you @thesamesam

**Pull request closed without merging**
