### PR TITLE
app-admin/webapp-config: enable python3_7

### PR DESCRIPTION
**Pull request by matoro**
All tests pass under python 3.7 per this build log:
https://gist.github.com/matoro/1808592dcc9cf09f344a907c8a2fb1af

### CODE REVIEW

**Comment by candrews** [comment]
@matoro can please add a sign off to the commit?

**Comment by matoro** [comment]
@candrews I added it in a force push, how do I get the bot to rescan?

**Comment by juippis** [comment]
You need to sign-off with your real name, please read https://dev.gentoo.org/~mgorny/articles/new-gentoo-copyright-policy-explained.html#certificate-of-origin-approval and amend if you agree.

Also `s/Foundation/Authors`, you should use repoman to commit to fix these little things automatically ;)

**Comment by blueness** [comment]
it looks like his real name to me.  pushed.

**Comment by juippis** [comment]
@blueness 
`author | matoro <matoro@users.noreply.github.com>`

[162ff05d4c677877e863fe8ab80a5396f88b6108](https://gitweb.gentoo.org/repo/gentoo.git/commit/app-admin/webapp-config?id=162ff05d4c677877e863fe8ab80a5396f88b6108)

"ok"

**Pull request closed without merging**
