### PR TITLE
Bump version dev-python/pygobject to 3.34.0

### PR DESCRIPTION
**Pull request by linux923344**
Package-Manager: Portage-2.3.79
Signed-off-by: Marcin "Y0rune" Wozniak <y0rune@aol.com>

https://bugs.gentoo.org/704130

### CODE REVIEW

**Comment by wimmuskee** [comment]
Some non-dev comments:
* you should rebase your commits (one commit for each logical change)
* follow the commit message standard, eg: dev-python/pygobject: version bump to 3.34.0
* signoff your commits
* when closing or referencing bugs, do so from the commit message using the "Closes" or "Bug" keywords; I think you just want to reference 704130, but close 704196

For more info, see https://devmanual.gentoo.org/ebuild-maintenance/git/index.html

Also, while you're at it, take a look at https://bugs.gentoo.org/703002 and update HOMEPAGE for the new ebuild.

**Comment by linux923344** [comment]
Sorry for do it not good I mean commited. This is the first pull request. I want to be part of the Gentoo Community :3 The next pull request and ebuild will be better  ;)

**Comment by wimmuskee** [comment]
No worries, we all have to start somewhere.

**Comment by wimmuskee** [comment]
I'm afraid you cannot wait for the next PR to improve ;) All commits added to the tree have to comply to these standards. However, it's not difficult:

* You have to rebase all the commits in your branch, _git rebase -i HEAD~5_  (for 5 commits) and pick the first one, and fixup the others.
* Then amend your commit message, _git commit --amend_ (to change the commit message, and include the bug references and signoff).
* Force push the result to update the PR, _git push -f origin dev-python/pygobject-3.34.0_

If you're unsure about the first 2 steps, just make a local copy of your branch and try them out there.

**Comment by linux923344** [comment]
I did like you wrote.

**Comment by wimmuskee** [comment]
The last commit now has a signoff message. However
* I still see 5 commits in the PR instead of one.
* the commit summary line does not start with "dev-python/pygobject:"
* reference to a bug not with "Bugs:", but with "Bug:"
* also add "Closes: https://bugs.gentoo.org/704196"

**Comment by linux923344** [comment]
I created new branch with that tips like you wrote, but I also create new pull reqyest https://github.com/gentoo/gentoo/pull/14238

**Pull request closed without merging**
