### PR TITLE
dev-libs/date: add patch for current_zone() error

### PR DESCRIPTION
**Pull request by suoyuan666**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by suoyuan666** [comment]
There is a problem with `inline static std::string get_alpha_word(std::istream& in)` in dev-libs/date, which causes an exception in the call of `const time_zone* current_zone()`
Related link: https://github.com/Alexays/Waybar/issues/3643

**Review by eli-schwartz — CHANGES_REQUESTED** [review]
> Related link: [Alexays/Waybar#3643](https://github.com/Alexays/Waybar/issues/3643)

I wonder why you link to a waybar bug report and then try to patch *date*? Shouldn't you be reporting this to *date*?

Does the *date* project believe this patch is a correct answer?

**Comment by suoyuan666** [comment]
> > Related link: [Alexays/Waybar#3643](https://github.com/Alexays/Waybar/issues/3643)
> 
> I wonder why you link to a waybar bug report and then try to patch _date_? Shouldn't you be reporting this to _date_?
> 
> Does the _date_ project believe this patch is a correct answer?

Because I encountered this problem when using waybar, I put this bug report here. In fact, date also solves this problem, but it is not the version in the gentoo repository.
https://github.com/HowardHinnant/date/commit/51ce7e131079c061533d741be5fe7cca57f2faac

**Comment by suoyuan666** [comment]
> > > Related link: [Alexays/Waybar#3643](https://github.com/Alexays/Waybar/issues/3643)
> > 
> > 
> > I wonder why you link to a waybar bug report and then try to patch _date_? Shouldn't you be reporting this to _date_?
> > Does the _date_ project believe this patch is a correct answer?
> 
> Because I encountered this problem when using waybar, I put this bug report here. In fact, date also solves this problem, but it is not the version in the gentoo repository. [HowardHinnant/date@51ce7e1](https://github.com/HowardHinnant/date/commit/51ce7e131079c061533d741be5fe7cca57f2faac)

**Comment by JonasToth** [comment]
I believe the new release should be added now. not sure if carrying this patch here is necessary in that case?

https://github.com/HowardHinnant/date/releases/tag/v3.0.2

**Comment by suoyuan666** [comment]
> I believe the new release should be added now. not sure if carrying this patch here is necessary in that case?
> 
> https://github.com/HowardHinnant/date/releases/tag/v3.0.2

The new version has indeed solved this problem. You are right. I will close this request and request an upgrade to the new version later.

**Pull request closed without merging**
