### PR TITLE
x11-misc/xscreensaver: add 6.06

### PR DESCRIPTION
**Pull request by Schievel1**
This version bump introduces some regressions to make that ebuild easier to maintain. 

I got rid of USE flags for options that are not supported by upstream anymore. 
1. gtk - building without gtk is not an option anymore. The xscreensaver-settings is always build and installed.
2. gdk-pixbuf - sine -gtk is gone building without gdk-pixbuf will not work anymore
3. png - building without png is not supported by upstream anymore

I left the patches and such in for now but commented them out, when we agree on this I will remove them and we can merge. 

@hartwork you might want to have a look 
See also https://bugs.gentoo.org/885441

Fixes for this version:
Bug: https://bugs.gentoo.org/898328 

Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

### CODE REVIEW

**Comment by Schievel1** [comment]
@Flowdalic this is taking too long for my taste. @hartwork and me agreed in this bug (https://bugs.gentoo.org/885441) that we drop most of the options to simplify this ebuild. Can we get this merged?

**Comment by Flowdalic** [comment]
@Schievel1 You are right, that takes too long.  And I can totally understand that this is frustrating.

Sometimes it is necessary to friendly ping the person who is assumed to take the next step. Between various bug trackers, mailing lists and chats, things easily slip through the cracks.

I've asked for a ack from @hartwork because he was the one who interacted with you in the mentioned bug and is probably the most knowledgeable person to review that.

That said, any member of the proxy-maint team may review your changes and, if found to be sound, merge this.

@hartwork friendly ping, could you review and ideally approve this?

**Comment by Schievel1** [comment]
Sorry, if it came across a bit harsh I apologize and I can assure you this was never the intention.
I appreciate the work that you guys are doing and it's totally understandable when a thing takes longer. We all do this in our free time after all.

**Comment by Flowdalic** [comment]
> Sorry, if it came across a bit harsh I apologize and I can assure you this was never the intention.

No worries and no hurt feelings.

As a xscreensaver user myself I am glad that someone maintains this package. So I have also an intrinsic interest that this PR moves forward. OTOH, what happened is that I clicked the "request review from @hartwork" button and never looked back at it (because the ball was now in someone else's field).

I am sure we can get this to move forward. Let's give @hartwork some days to respond, and if you do not hear from him back, then feel free to ping me, or anyone else from the proxy-maint team, again (for example via github or IRC).

Thanks again for your contribution to Gentoo and work on xscreensaver.

**Review by juippis — APPROVED** [review]
```
 * QA Notice: This package installs one or more .desktop files that do not
 * pass validation.
 * 
 * 	/usr/share/applications/xscreensaver-settings.desktop: error: value item "Screensaver" in key "Categories" in group "Desktop Entry" is a reserved category, so a "OnlyShowIn" key must be included
 * 	/usr/share/applications/xscreensaver.desktop: error: value item "Screensaver" in key "Categories" in group "Desktop Entry" is a reserved category, so a "OnlyShowIn" key must be included
 * 
```

**Pull request closed without merging**
