### PR TITLE
sys-libs/glibc: fix symlinks that cross /usr boundary

### PR DESCRIPTION
**Pull request by matijaskala**

### CODE REVIEW

**Comment by gyakovlev** [comment]
Hi
just a suggestion: to make review easier you could post a diff here in case you add a new revision like in this PR and github does not display changes.

Saves a lot of reviewer's time and increases probability of quicker review =)

```diff
--- glibc-2.26-r7.ebuild        2018-06-06 08:27:49.426052371 -0700
+++ glibc-2.26-r8.ebuild        2018-06-06 16:24:31.793875678 -0700
@@ -18,7 +18,7 @@
        EGIT_REPO_URI="git://sourceware.org/git/glibc.git"
        inherit git-r3
 else
-       KEYWORDS="~alpha amd64 ~arm arm64 ~hppa ia64 m68k ~mips ~ppc ~ppc64 s390 sh ~sparc x86"
+       KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~m68k ~mips ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86"
        SRC_URI="mirror://gnu/glibc/${P}.tar.xz"
 fi
 
@@ -624,6 +624,35 @@
                mv "${ED}"$(alt_usrlibdir)/libm-${upstream_pv}.a "${ED}"$(alt_usrlibdir)/${P}/libm-${upstream_pv}.a || die
        fi
 
+       # Fix symbolic links that cross /usr boundary
+       local flags=( ${CFLAGS} ${LDFLAGS} -Wl,--verbose )
+       if $(tc-getLD) --version | grep -q 'GNU gold' ; then
+               local d="${T}/bfd-linker"
+               mkdir -p "${d}"
+               ln -sf $(which ${CHOST}-ld.bfd) "${d}"/ld
+               flags+=( -B"${d}" )
+       fi
+       local output_format=$($(tc-getCC) "${flags[@]}" 2>&1 | sed -n 's/^OUTPUT_FORMAT("\([^"]*\)",.*/\1/p')
+       [[ -n ${output_format} ]] && output_format="OUTPUT_FORMAT ( ${output_format} )"
+       for i in "${ED}"$(alt_usrlibdir)/lib*.so ; do
+               j="$(readlink "${i}")"
+               [[ ${j} == ../../lib*/lib*.so* ]] || continue
+               rm "${i}" || die
+               cat > "${i}" <<-END_LDSCRIPT
+               /* GNU ld script
+                  Since Gentoo has critical dynamic libraries in /lib, and the static versions
+                  in /usr/lib, we need to have a "fake" dynamic lib in /usr/lib, otherwise we
+                  run into linking problems.  This "fake" dynamic lib is a linker script that
+                  redirects the linker to the real lib.  And yes, this works in the cross-
+                  compiling scenario as the sysroot-ed linker will prepend the real path.
+
+                  See bug https://bugs.gentoo.org/4411 for more info.
+                */
+               ${output_format}
+               GROUP ( ${EPREFIX}${j#../..} )
+               END_LDSCRIPT
+       done
+
        # We'll take care of the cache ourselves
        rm -f "${ED}"/etc/ld.so.cache
```




\`\`\`diff
+diff
-text
here 
\`\`\`

**Comment by trofi** [comment]
I'd like to see 2 more tweaks here:
- patch description should clearly explain what will change on disk. Do we convert some symlinks into ldscripts? Which ones and why? What is broken today? I don't understand it now.
- `-9999` should be fixed as well ebuild

**Comment by matijaskala** [comment]
I made the description more detailed.
```diff
        fi
 
        # Fix symbolic links that cross /usr boundary
+       # If prefix is used and ${EROOT}/usr is a symlink to '.',
+       # then these libraries will be symlinks, pointing to the
+       # host system:
+       #       libanl.so
+       #       libBrokenLocale.so
+       #       libcidn.so
+       #       libcrypt.so
+       #       libdl.so
+       #       libmvec.so
+       #       libnss_db.so
+       #       libnss_dns.so
+       #       libnss_files.so
+       #       libnss_hesiod.so
+       #       libresolv.so
+       #       librt.so
+       #       libthread_db.so
+       #       libutil.so
+       # Convert them to ldscripts
        local flags=( ${CFLAGS} ${LDFLAGS} -Wl,--verbose )
        if $(tc-getLD) --version | grep -q 'GNU gold' ; then
                local d="${T}/bfd-linker"
```
Is it clear enough or should I rephrase it?

**Comment by trofi** [comment]
I still don't understand. Let's take an example `libdl.so` today. Before the change the layout was:
```
/usr/lib64/libdl.a
/usr/lib64/libdl.so -> ../../lib64/libdl.so.2
/lib64/libdl.so.2 -> libdl-2.27.so
/lib64/libdl-2.27.so
```

What is the final layout?

Your change implies that `/lib64` and `/usr/lib64` are in fact the same directory and problems happen at merge time when package's symlink lands at the same place as the file itself. Namely `/lib64/libdl-2.27.so` on top of `/usr/lib64/libdl.so` (or the other way around). Do I understand that correctly?

Below I assume I do understand the issue correctly. And I still don't understand new layout. If I read the following correctly:
```diff
+		[[ ${j} == ../../lib*/lib*.so* ]] || continue
+		rm "${i}" || die
+		cat > "${i}" <<-END_LDSCRIPT
```
this changes `/usr/lib64/libdl.so` symlink to `/usr/lib64/libdl.so` ldscript but does not change file name or directory. Thus the layout will not change and file clash would not be fixed. What gets better then?

One note:
I personally think individual packages can not (and should not) guard against unexpected symlinks on user's system but `portage` could. For example `portage` might be able omit installing a symlink (or mangle a symlink to accomodate non-standard user's symlink tree) if it would see that symlink and actual file both land on the same resolved path. It is harder to do with ldscript and actual dynamic library. Thus I think `portage` would be better place to handle this kind of problems.

**Comment by matijaskala** [comment]
This is not about a file clash. This is about symlinks that point to the wrong location.
The issue only appears on hurd systems.
```diff
@@ -1134,9 +1134,12 @@ glibc_do_src_install() {
 	fi
 
 	# Fix symbolic links that cross /usr boundary
-	# If prefix is used and ${EROOT}/usr is a symlink to '.',
-	# then these libraries will be symlinks, pointing to the
-	# host system:
+	# If we have /usr/i686-gnu/usr pointing to /usr/i686-gnu,
+	# then a symlink inside /usr/i686-gnu/usr/lib that points to
+	# ../../lib/libsomething-2.so will be installed to /usr/i686-gnu/lib
+	# and will end up pointing to /usr/lib/libsomething-2.so
+	# instead of /usr/i686-gnu/lib/libsomething-2.so.
+	# Affected symlinks:
 	# 	libanl.so
 	# 	libBrokenLocale.so
 	# 	libcidn.so
@@ -1151,7 +1154,8 @@ glibc_do_src_install() {
 	# 	librt.so
 	# 	libthread_db.so
 	# 	libutil.so
-	# Convert them to ldscripts
+	# Moving them to /lib would break normal systems
+	# so convert them to ldscripts instead.
 	local flags=( ${CFLAGS} ${LDFLAGS} -Wl,--verbose )
 	if $(tc-getLD) --version | grep -q 'GNU gold' ; then
 		local d="${T}/bfd-linker"
```

**Comment by trofi** [comment]
Aha, makes some sense. And I also managed to confuse myself as my initial example did not have file clash either :) My apologies.

> If we have /usr/i686-gnu/usr pointing to /usr/i686-gnu

Why do you need to do it?

**Comment by matijaskala** [comment]
Because gcc expects to find hurd headers in both `/include` and `/usr/include`.
I've read that on hurd, `/usr` is a symlink to `.`, so I thought creating this symlink would be the simplest way to resolve compile errors.

**Comment by trofi** [comment]
For example on debian-hurd `/usr` is not a symlink to `.` and `/include` does not exist there.

I would suggest try harder to avoid `/usr` symlinks or any symlinks used to install packages over them. glibc won't be the only broken package.

Other cross-targets in gentoo set only `sys-include` as a symlink, not the whole `/usr`. I understand that `hurd` explicitly claims `/usr` is not needed but gentoo does install most of packages over `/usr` today.

https://github.com/trofi/gentoo-hurd was my attempt to get hurd running. It can cross-build basic userland. There I did `usr/include` -> `include` symlink in `sys-kernel/gnumach` out of laziness. But I think it can (and should) also be solved by passing `--with-native-system-header-dir=/usr/include` to `gcc`'s configure. It would also allow us to get rid of similar `sys-include` symlink hacks in `dev-util/mingw64-runtime`, `sys-freebsd/freebsd-lib`, `sys-libs/uclibc-ng`, `sys-libs/uclibc`

**Pull request closed without merging**
