### PR TITLE
dev-java/jsr250 : version bump to 1.2

### PR DESCRIPTION
**Pull request by stefan-langenmaier**

### CODE REVIEW

**Comment by chewi** [comment]
Thanks for this. It's good but just a few things.
* I know you didn't use repoman because you spelt the package name wrong, repoman wouldn't add a space before the colon, and it adds a Package-Manager footer. The commit message isn't that important but the repoman checks are.
* Always specify the oldest jdk/jre version that we have in the tree, currently 1.7. We cannot test with older versions and upstream doesn't always get it right. Ideally test building it yourself with Java 7 and 8 and tell us you've done so.
* It's a minor version change and this is only used by maven-bin so it's probably fine but use java-apicheck to determine whether a new SLOT is needed. It could have a totally different ABI! Again, let us know you've done so.

**Comment by stefan-langenmaier** [comment]
Sorry for the shitty pull request. I'll update the ebuild.

I didn't know about java-apicheck, it looks quite handy but the japitools seem to have a problem.

`Error: Could not find or load main class net.wuffies.japi.Japize`

Anyway I shouldn't do bug reports in such a haste. :) Thanks for taking the time to reply.

**Comment by chewi** [comment]
Please excuse @monsieurp, he's... special.

**Comment by monsieurp** [comment]
Sorry, I didn't mean to merge this PR. I've reverted the commit btw. @chewi knows how special I am.

**Comment by stefan-langenmaier** [comment]
No worries guys. I'm sure we get this sorted out. :)

**Comment by chewi** [comment]
I've fixed japitools. It was broken by a recent eclass change.

**Comment by stefan-langenmaier** [comment]
Thanks for the fix in japitool. I could run java-apicheck. It says "All good" and "0 unique errors".

I also bumped the jdk/jre deps to 1.7 and I compiled it correctly with java7 and java8.

repoman was also complaining about ppc64 so I added it also as unstable keyword.

**Comment by chewi** [comment]
Good job, thanks! You can readd any existing keywords as unstable ones without testing as long as it's not a major new version.

**Pull request closed without merging**
