### PR TITLE
WIP: app-shells/pwsh: Initial import (bug 798972)

### PR DESCRIPTION
**Pull request by zmedico**
TODO: Make it work with network-sandbox enabled.
```
$ sudo FEATURES=test PORTAGE_LOG_FILTER_FILE_CMD=ansifilter ebuild pwsh-7.1.3.ebuild manifest clean install

 * Package:    app-shells/pwsh-7.2.0
 * Repository: gentoo
 * Maintainer: dotnet@gentoo.org
 * Upstream:   https://github.com/PowerShell/PowerShell/issues
 * USE:        abi_x86_64 amd64 elibc_glibc kernel_linux userland_GNU
 * FEATURES:   network-sandbox preserve-libs sandbox test userpriv usersandbox

>>> Unpacking source...
>>> Unpacking pwsh-7.2.0.tar.gz to /var/tmp/portage/app-shells/pwsh-7.2.0/work
>>> Source unpacked in /var/tmp/portage/app-shells/pwsh-7.2.0/work
>>> Preparing source in /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0 ...
 * Start-PSBootstrap
==WARNING: The current OS : gentoo is not supported for building PowerShell.
Installing PowerShell build dependencies
VERBOSE: Calling Find-Dotnet from Start-PSBootstrap
VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
VERBOSE: Back from calling Find-Dotnet from Start-PSBootstrap
=dotnet is already installed.  Skipping installation.
 * Start-PSBuild
==WARNING: The current OS : gentoo is not supported for building PowerShell.
VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
=VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
VERBOSE: Using configuration 'Debug'
VERBOSE: Using framework 'net6.0'
VERBOSE: Using runtime 'linux-x64'
VERBOSE: Top project directory is /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix
Run dotnet restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix --runtime linux-x64 /property:SDKToUse=Microsoft.NET.Sdk --verbosity quiet
=
Welcome to .NET 6.0!
---------------------
SDK Version: 6.0.100

Telemetry
---------
The .NET tools collect usage data in order to help us improve your experience. It is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

----------------
Installed an ASP.NET Core HTTPS development certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only).
Learn about HTTPS: https://aka.ms/dotnet-https
----------------
Write your first app: https://aka.ms/dotnet-hello-world
Find out what's new: https://aka.ms/dotnet-whats-new
Explore documentation: https://aka.ms/dotnet-docs
Report issues and find source on GitHub: https://github.com/dotnet/core
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli
--------------------------------------------------------------------------------------
======0;
Done restoring /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix
Run dotnet restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/TypeCatalogGen --runtime linux-x64 /property:SDKToUse=Microsoft.NET.Sdk --verbosity quiet
==0;
Done restoring /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/TypeCatalogGen
Run dotnet restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/ResGen --runtime linux-x64 /property:SDKToUse=Microsoft.NET.Sdk --verbosity quiet
==0;
Done restoring /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/ResGen
Run dotnet restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Modules --runtime linux-x64 /property:SDKToUse=Microsoft.NET.Sdk --verbosity quiet
==0;
Done restoring /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Modules
Run ResGen (generating C# bindings for resx files)
VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
=Run TypeGen (generating CorePsTypeCatalog.cs)
VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
==0;
===0;
Run dotnet publish /property:GenerateFullPaths=true /property:ErrorOnDuplicatePublishOutputFiles=false --self-contained /property:IsWindows=false --configuration Debug --framework net6.0 --runtime linux-x64 /property:ReleaseTag=7.2.0 /property:SDKToUse=Microsoft.NET.Sdk from /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix
=Microsoft (R) Build Engine version 17.0.0+c9eb9dd64 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
===  Restored /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/powershell-unix.csproj (in 850 ms).
  6 of 7 projects are up-to-date for restore.
==  System.Management.Automation -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/System.Management.Automation/bin/Debug/net6.0/System.Management.Automation.dll
  Microsoft.PowerShell.Security -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Microsoft.PowerShell.Security/bin/Debug/net6.0/Microsoft.PowerShell.Security.dll
  Microsoft.PowerShell.ConsoleHost -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Microsoft.PowerShell.ConsoleHost/bin/Debug/net6.0/Microsoft.PowerShell.ConsoleHost.dll
  Microsoft.PowerShell.Commands.Utility -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Microsoft.PowerShell.Commands.Utility/bin/Debug/net6.0/Microsoft.PowerShell.Commands.Utility.dll
  Microsoft.PowerShell.Commands.Management -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Microsoft.PowerShell.Commands.Management/bin/Debug/net6.0/Microsoft.PowerShell.Commands.Management.dll
  Microsoft.PowerShell.SDK -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/Microsoft.PowerShell.SDK/bin/Debug/net6.0/Microsoft.PowerShell.SDK.dll
  powershell-unix -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/pwsh.dll
  powershell-unix -> /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/
=0;
PowerShell output: /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/pwsh
Restore PowerShell modules to /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish
VERBOSE: In Find-DotNet
=VERBOSE: dotnetCLIInstalledVersion = 6.0.100
chosenDotNetVersion = 6.0.100-rtm.21527.11
WARNING: The 'dotnet' in the current path can't find SDK version 6.0.100, prepending /var/tmp/portage/app-shells/pwsh-7.2.0/homedir/.dotnet to PATH.
=Name='PowerShellGet', Version='2.2.5', Destination='/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/Modules'
Name='PackageManagement', Version='1.4.7', Destination='/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/Modules'
Name='Microsoft.PowerShell.Archive', Version='1.2.5', Destination='/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/Modules'
Name='PSReadLine', Version='2.1.0', Destination='/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/Modules'
Name='ThreadJob', Version='2.0.3', Destination='/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/bin/Debug/net6.0/linux-x64/publish/Modules'
>>> Source compiled.
>>> Test phase: app-shells/pwsh-7.2.0
 * --version ...
 [ ok ]
 * hello world ...
 [ ok ]
>>> Completed testing app-shells/pwsh-7.2.0

>>> Install app-shells/pwsh-7.2.0 into /var/tmp/portage/app-shells/pwsh-7.2.0/image
>>> Completed installing app-shells/pwsh-7.2.0 into /var/tmp/portage/app-shells/pwsh-7.2.0/image

 * Final size of build directory: 202812 KiB (198.0 MiB)
 * Final size of installed tree:  252244 KiB (246.3 MiB)

strip: x86_64-pc-linux-gnu-strip --strip-unneeded -N __gentoo_check_ldflags__ -R .comment -R .GCC.command.line -R .note.gnu.gold-version
   /usr/lib64/pwsh/libpsl-native.so
   /usr/lib64/pwsh/publish/libpsl-native.so
   /usr/lib64/pwsh/libpsrpclient.so
   /usr/lib64/pwsh/publish/libpsrpclient.so
```
WIth network-sandbox it fails like this:
```
Failed to restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix, retrying...
/opt/dotnet-sdk-bin-6.0/sdk/6.0.100/NuGet.targets(130,5): error : Unable to load the service index for source https://api.nuget.org/v3/index.json. [/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/powershell-unix.csproj]
/opt/dotnet-sdk-bin-6.0/sdk/6.0.100/NuGet.targets(130,5): error :   Network is unreachable (api.nuget.org:443) [/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/powershell-unix.csproj]
/opt/dotnet-sdk-bin-6.0/sdk/6.0.100/NuGet.targets(130,5): error :   Network is unreachable [/var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix/powershell-unix.csproj]
Failed to restore /var/tmp/portage/app-shells/pwsh-7.2.0/work/PowerShell-7.2.0/src/powershell-unix, retrying...
Exception: Execution of { dotnet restore $project $RestoreArguments } by build.psm1: line
745 failed with exit code 1

 * ERROR: app-shells/pwsh-7.2.0::gentoo failed (compile phase):
 *   Start-PSBuild  failed
```

Bug: https://bugs.gentoo.org/798972
Signed-off-by: Zac Medico <zmedico@gentoo.org>

### CODE REVIEW

**Comment by mid-kid** [comment]
The `network-sandbox` issue can be solved by building once, grabbing all the `*.nupkg` in a directory and putting them somewhere, and before the build, running `dotnet nuget add source /path/to/dir`. Note, however, that `*.nupkg` contain prebuilt binaries, and building the entire dependency tree from source is a massive pain, as there's no standardized method of obtaining the package's sources, and some packages require extra steps (generating files) to build.

**Comment by zmedico** [comment]
This sounds promising:

https://www.codurance.com/publications/2015/05/04/creating-a-local-nuget-repository

I see that the packages have manual download instructions like this:

https://www.powershellgallery.com/packages/ThreadJob/2.0.3#manual-download

The sha512 of https://psg-prod-eastus.azureedge.net/packages/threadjob.2.0.3.nupkg matches the one that nupkg downloaded to /var/tmp/portage/app-shells/pwsh-7.1.3/homedir/.nuget/packages/threadjob/2.0.3/threadjob.2.0.3.nupkg.

**Comment by zmedico** [comment]
We may have something useful here:

https://gitweb.gentoo.org/repo/proj/dotnet.git/tree/eclass/nuget.eclass
https://gitweb.gentoo.org/repo/proj/dotnet.git/tree/eclass/nupkg.eclass

**Comment by mid-kid** [comment]
Yeah, the only annoying part about .nupkg files is that they're prebuilts and can contain natives. Other than that that approach will work.

**Comment by xgqt** [comment]
Good news are that nuget packages can be asily bundles and then restored from a specified directory https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-lang/boogie/boogie-2.15.8-r4.ebuild#n69

Bad news are that PowerShell .NET version restrictions are very picky, currently you cannot compile PWSH with .NET SDK 6.0.402 for example.

**Comment by mid-kid** [comment]
I'd rename the `*-deps.tar.xz` package to `*-prebuilts.tar.xz` or something to that effect, to convey that they're binaries, not sources, unlike go's `*-deps.tar.xz` packages.

**Comment by xgqt** [comment]
> I'd rename the `*-deps.tar.xz` package to `*-prebuilts.tar.xz` or something to that effect, to convey that they're binaries, not sources, unlike go's `*-deps.tar.xz` packages.

Good idea!

**Comment by xgqt** [comment]
app-shells/pwsh merged into ::gentoo. Thanks to everybody who participated!
@mid-kid 
@zmedico 
@navi-desu 
@thesamesam

**Pull request closed without merging**
