### PR TITLE
dev-php/composer: bump to 1.6.5

### PR DESCRIPTION
**Pull request by hydrapolic**
1.6.4
**Security fixes** in some edge case scenarios, recommended update for all users
Fixed regression in version guessing of path repositories
Fixed removing aliased packages from the repository, which might resolve some odd update bugs
Fixed updating of package URLs for GitLab
Fixed run-script --list failing when script handlers were defined
Fixed init command not respecting the current php version when selecting package versions
Fixed handling of uppercase package names in why/why-not commands
Fixed exclude-from-classmap symlink handling
Fixed filesystem permissions of PEAR binaries
Improved performance of subversion repos
Other minor fixes

1.6.5
Fixed regression in 1.6.4 causing strange update behaviors with dev packages
Fixed regression in 1.6.4 color support detection for Windows
Fixed issues dealing with broken symlinks when switching branches and using path repositories
Fixed JSON schema for package repositories
Fixed issues on computers set to Turkish locale
    Fixed classmap parsing of files using short-open-tags when they are disabled in php

### CODE REVIEW

**Comment by hydrapolic** [comment]
@GuillaumeSeren @orlitzky

**Comment by hydrapolic** [comment]
1.6.5:

    Fixed regression in 1.6.4 causing strange update behaviors with dev packages
    Fixed regression in 1.6.4 color support detection for Windows
    Fixed issues dealing with broken symlinks when switching branches and using path repositories
    Fixed JSON schema for package repositories
    Fixed issues on computers set to Turkish locale
    Fixed classmap parsing of files using short-open-tags when they are disabled in php

**Comment by mgorny** [comment]
Thanks! @GuillaumeSeren, thanks for reviewing. I'm going to merge now.

**Comment by hydrapolic** [comment]
Thank you guys :)

**Pull request closed without merging**
