### PR TITLE
dev-python/webtest: remove python2

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Package-Manager: Portage-2.3.99, Repoman-2.3.22
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks. And I thought I've only seen some revdeps with these packages but I guess they're gone now. I'll recheck and merge them.

**Comment by mgorny** [comment]
Oh wait, you've only introduced meaningless revbumps. This doesn't help at all.

**Comment by Alessandro-Barbieri** [comment]
so? what's up now?

**Comment by mgorny** [comment]
1. This will only cause a lot of warnings from Portage for people who can't upgrade.
2. Developers will accidentally miss py2 when bumping, so people will miss updates.

There's no point in putting effort to do this while there are still revdeps that need py2.

**Comment by Alessandro-Barbieri** [comment]
I see no revdeps for `dev-python/webtest[python_targets_python2_7]`

**Comment by mgorny** [comment]
I see at least three:

```
dev-python/pecan:0
        1.3.3-r2: S         3.6 3.7 3.8
dev-python/pypiserver:0
        1.3.1-r1: S     2.7 3.6 3.7 3.8 pypy3
dev-python/pyquery:0
           1.4.1: S     2.7 3.6 3.7 3.8 pypy3
dev-python/test_server:0
          0.0.31: ~         3.6 3.7 3.8 pypy3
dev-python/wsgiproxy2:0
           0.4.6: S     2.7 3.6 3.7 3.8 pypy3
dev-util/conan:0
          1.23.0: ~   #     3.6 3.7
          1.24.1: ~         3.6 3.7
net-im/err:0
        5.2.0-r1: ~         3.6

**Pull request closed without merging**
