### PR TITLE
sys-kernel/scx: new package

### PR DESCRIPTION
**Pull request by vimproved**
Given that 6.10 is now out, and the 6.11 RCs will soon be coming with sched-ext support, I figured it was about the right time to put this up as a draft PR.

To do:
- Add kernel config checks
- ~~Sort out if there's a better solution to the bpftool version check removal patch, however this is an issue caused entirely by Gentoo's packaging so I'm not sure.~~
- The nested Cargo inside of meson shenanigans going on here doesn't sit well with me. I haven't run into any issues, but it feels like they're just waiting to happen. I should consider building the C schedulers via meson, but then building the rust schedulers standalone with cargo.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by hhoffstaette** [comment]
I see that you pushed 1.0.4 to guru - can this be closed?

**Comment by vimproved** [comment]
> I see that you pushed 1.0.4 to guru - can this be closed?

For now, yeah. It can be imported from GURU later if it's warranted.

**Comment by thesamesam** [comment]
Still happy to bring it in to ::gentoo (which I took to be the plan, even).

**Comment by vimproved** [comment]
> Still happy to bring it in to ::gentoo (which I took to be the plan, even).

Sounds good. I'd like to fix a couple issues while it's in GURU first, and wait until 1.0.5 is released though, because the cargo workspace setup is still shifting around a bit upstream.

**Pull request closed without merging**
