### PR TITLE
net-proxy/squid: bump to 5.4.1

### PR DESCRIPTION
**Pull request by hydrapolic**
```
--- squid-4.17.ebuild   2022-02-19 10:09:51.941858004 +0000
+++ squid-5.4.1.ebuild  2022-02-19 10:14:28.526086477 +0000
@@ -1,20 +1,21 @@
 # Copyright 1999-2022 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI=7
+EAPI="8"
 
 inherit autotools flag-o-matic linux-info pam systemd toolchain-funcs
 
 DESCRIPTION="A full-featured web proxy cache"
 HOMEPAGE="http://www.squid-cache.org/"
 
+MY_PV_MAJOR=$(ver_cut 1)
 # Upstream patch ID for the most recent bug-fixed update to the formal release.
 r=
 #r=-20181117-r0022167
 if [ -z "$r" ]; then
-       SRC_URI="http://www.squid-cache.org/Versions/v${PV%.*}/${P}.tar.xz"
+       SRC_URI="http://www.squid-cache.org/Versions/v${MY_PV_MAJOR}/${P}.tar.xz"
 else
-       SRC_URI="http://www.squid-cache.org/Versions/v${PV%.*}/${P}${r}.tar.bz2"
+       SRC_URI="http://www.squid-cache.org/Versions/v${MY_PV_MAJOR}/${P}${r}.tar.bz2"
        S="${S}${r}"
 fi
 
@@ -59,7 +60,8 @@
        ecap? ( virtual/pkgconfig )
        test? ( dev-util/cppunit )"
 
-RDEPEND="${COMMON_DEPEND}
+RDEPEND="!!<net-proxy/squid-5
+       ${COMMON_DEPEND}
        samba? ( net-fs/samba )
        perl? ( dev-lang/perl )
        mysql? ( dev-perl/DBD-mysql )
@@ -78,7 +80,7 @@
 }
 
 src_prepare() {
-       eapply "${FILESDIR}/${PN}-4.3-gentoo.patch"
+       eapply "${FILESDIR}/${PN}-5.3-gentoo.patch"
 
        sed -i -e 's:/usr/local/squid/etc:/etc/squid:' \
                INSTALL QUICKSTART \
```

Example NEWS item:
```
Title: net-proxy/squid-5 upgrade
Author: Tomáš Mózes <hydrapolic@gmail.com>
Posted: 2022-02-19
Revision: 1
News-Item-Format: 2.0
Display-If-Installed: <net-proxy/squid-5

Squid error files in version 4 are incompatible with error files
in version 5.

You need to remove squid version 4 prior to installing version 5:
emerge -avC net-proxy/squid
emerge -av net-proxy/squid

You can read more here:
https://forums.gentoo.org/viewtopic-p-8651905.html
```

The hard block is there due to https://forums.gentoo.org/viewtopic-p-8651905.html

Does not YET contain https://github.com/gentoo/gentoo/pull/23545

### CODE REVIEW

**Comment by thesamesam** [comment]
@mikhailkoliada

**Comment by thesamesam** [comment]
The hard block is sad and I think it'd be worth doing a news item for this given it requires manual user intervention. We didn't do it for the android-whatever thing and I regret that.

**Comment by mikhailkoliada** [comment]
> The hard block is sad and I think it'd be worth doing a news item for this given it requires manual user intervention. We didn't do it for the android-whatever thing and I regret that.

It depends, squid 5.x is known to be different from the older versions and portage gonna tell you about hard blockers in anyway

**Comment by mikhailkoliada** [comment]
apart from that feel free to commit (I can't commit from my GitHub account)

**Comment by hydrapolic** [comment]
> The hard block is sad and I think it'd be worth doing a news item for this given it requires manual user intervention. We didn't do it for the android-whatever thing and I regret that.

Agree, a news item is a good idea.

**Comment by hydrapolic** [comment]
Updated to version 5.4.1, added NEWS item (first comment).

**Comment by hydrapolic** [comment]
Thanks @Zlogene @mikhailkoliada. Should we also send the NEWS item to gentoo-dev ML?

**Pull request closed without merging**
