### PR TITLE
net-misc/linuxptp: Make kernel config advisory

### PR DESCRIPTION
**Pull request by pstew-dd**
Packages that don't actually have a compile dependency on kernel
configuration should not require access to kernel configuration
at build time.  Instead these checks should be advisory.

Signed-off-by: Paul Stewart <pstew@google.com>

### CODE REVIEW

**Comment by pstew-dd** [comment]
@dl1jbe could you have a look at this?  I guess I missed the step to ping a maintainer.

**Comment by juippis** [comment]
Some people don't have Github notifications on, the Gentoo bot should have already pinged him. 

You'd maybe be luckier if you opened a bug for this package in bugzilla, you can then link this PR to that bug.
(@gyakovlev)

**Comment by pstew-dd** [comment]
I've created bug #685278 .  How do I associate it with this change?   Sorry, this is my first time.  I see how to do it by adding  "Bug: ..." to my commit message, but I assume that this would mead I'd need to close this merge request and create a new commit and merge request.  However it seemed from your message that the association can be made a different way?

**Comment by juippis** [comment]
You can use git commit --amend to edit the latest commit message, I don't remember the exact syntax but I think that's it. You can also use git rebase -i HEAD~1 and 'edit' the latest commit message.

Then force-push update. You should work in branches, rather than master, because rebasing master could introduce something that breaks this PR :p

**Comment by pstew-dd** [comment]
The result is the same with the rebase as it is with the "git commit --amend" (why shouldn't int be -- you still need to do a commit --amend in both cases):

$ git status
On branch master
Your branch and 'origin/master' have diverged,
and have 1 and 1 different commits each, respectively.
  (use "git pull" to merge the remote branch into yours)

At this point, since there's already a commit "upstream" (the one for which I have this pull request for), I'd be rewriting history in order to continue to use this pull request.  I'm not allowed to do that.  The only thing close to that would be an intervening revert or throwing away this merge request and starting over from scratch with a new pull request.  If you feel this materially affects my ability to get the attention of a maintainer to accept this commit, I'm okay with doing that, I suppose.

**Comment by juippis** [comment]
I think the bug is best what you can do to get his attention. You can manually link this PR in the bug too, 
(`https://github.com/gentoo/gentoo/pull/11566`) and then @dl1jbe can add the `Closes: ` info if he decides to merge your commit.

**Pull request closed without merging**
