### PR TITLE
net-mail/mu: bump to 1.3.5

### PR DESCRIPTION
**Pull request by 00-matt**

### CODE REVIEW

**Comment by juippis** [comment]
You should split addition and removal into their own commits. Don't use `git mv`.

**Comment by 00-matt** [comment]
Fixed :)

**Comment by juippis** [comment]
Thanks! 

In future, I'd like to see the attempt be made at enabling gtk and webkit support. If they are built-in, and working, Gentoo should have the optionality ;)

**Comment by 00-matt** [comment]
@juippis Thanks! The upstream says that the webkit+gtk UI is just a toy and not for distribution, but I don't think a USE flag will hurt anybody :)

**Pull request closed without merging**
