### PR TITLE
dev-python/PyQt6 + www-client/qutebrowser qt6 live test

### PR DESCRIPTION
**Pull request by ionenwks**
Just revised/bumped these a bit, so tossing here while it waits for Qt6 wrt https://github.com/gentoo/gentoo/pull/25635 notably for if anyone need to do early testing/work with PyQt6 on other packages (rebase on top of qt6 PR or use ::qt overlay if want to test this).

(will add these to Qt6 masks on merge, for qutebrowser may later mask just the USE if 3.0.0 releases while qt6 is still masked)

### CODE REVIEW

**Comment by Pesa** [comment]
@ionenwks I was wondering why `PN` has an underscore instead of a hyphen? The latter is what's used on pypi, and also by `dev-python/PyQt5-sip`.
https://pypi.org/project/PyQt6-WebEngine/
https://pypi.org/project/PyQt6-sip/

**Comment by thesamesam** [comment]
> @ionenwks I was wondering why `PN` has an underscore instead of a hyphen? The latter is what's used on pypi, and also by `dev-python/PyQt5-sip`. [pypi.org/project/PyQt6-WebEngine](https://pypi.org/project/PyQt6-WebEngine/) [pypi.org/project/PyQt6-sip](https://pypi.org/project/PyQt6-sip/)

I remember being confused by this, came up https://github.com/gentoo/qt/pull/253#issue-1208442970, but maybe got renamed on pypi since?

**Comment by ionenwks** [comment]
The tarball still use _ and dev-python/ typically tries to avoid a bunch of MY_P and S redefinition.

**Comment by ionenwks** [comment]
aka if look at files on pypi it's
```
PyQt6_sip-13.4.0.tar.gz
PyQt6_WebEngine-6.3.1.tar.gz
```

**Comment by ionenwks** [comment]
Also, pypi doesn't allow _ in the name afaik. See sphinx_rtd_theme's metadata.xml where they use their intended underscores only on github and pypi's tarball. Was thinking to use the occasion to adopt the common practice rather than match old. Not that couldn't rename if felt really needed.

**Comment by Pesa** [comment]
Well, it's your package so up to you, but IMHO the most important consideration in this case is to match upstream's canonical name, not the tarball. Tarball naming conventions can and do change (PyQt itself changed multiple times over the years), while the "canonical" package name is typically fairly stable.

Moreover, `PN` is user visible, while the source tarball name merely an implementation detail. Saving one or two lines in the ebuild shouldn't be a more important goal than minimizing users' confusion.

> Was thinking to use the occasion to adopt the common practice

What common practice are you referring to? Gentoo's? pypi's?

And btw, years ago when I inherited PyQt, I was told that the preference of Gentoo's python team was to downcase all package names. After all, `pip` is case insensitive. I guess the policy changed since then? (I didn't rename the package at the time to avoid pointless churn)

**Comment by a17r** [comment]
Agree, tarball naming comes and goes, that should not influence `PN`.

**Comment by ionenwks** [comment]
> And btw, years ago when I inherited PyQt, I was told that the preference of Gentoo's python team was to downcase all package names. After all, `pip` is case insensitive. I guess the policy changed since then? (I didn't rename the package at the time to avoid pointless churn)

There's been tons of pkg-moves to revert that, e.g. `dev-python/ipy -> IPy`, or `configargparse -> ConfigArgParse` and the MY_P are being removed left and right, stuff like missing python- prefix are also being added where used and removed if not rather than try to match:
```
3Q-2021:move dev-python/dbusmock dev-python/python-dbusmock
3Q-2021:move dev-python/python-backoff dev-python/backoff
```
Of course the _ are also kept where used (sphinx_rtd_theme despite pypi is sphinx-rtd-theme), so at this point I was just going with avoiding MY_P in dev-python

**Comment by ionenwks** [comment]
No strong opinion about changing it back still, although I wish that conversion had continued back on ::qt before merging this.

**Comment by ionenwks** [comment]
One difference is that there's no github to confirm with PyQt (the _ are often based on github), so it feels kind of all over the place of what should really be used.

**Comment by ionenwks** [comment]
But well, given the above I think I'll go ahead and change it. Given it's still masked I guess I'll skip the pkgmove too.

**Comment by mgorny** [comment]
For the record, I've been mostly renaming packages whose names didn't match either the upstream repo or pypi. For new packages and rename targets, I generally chose whatever name didn't require MY_P.

**Comment by ionenwks** [comment]
> For the record, I've been mostly renaming packages whose names didn't match either the upstream repo or pypi. For new packages and rename targets, I generally chose whatever name didn't require MY_P.

Yeah, it's the impression I got having a second look wrt github names. Anyway, using PyQt6-sip now.

**Comment by Pesa** [comment]
> > And btw, years ago when I inherited PyQt, I was told that the preference of Gentoo's python team was to downcase all package names. After all, `pip` is case insensitive. I guess the policy changed since then? (I didn't rename the package at the time to avoid pointless churn)
> 
> There's been tons of pkg-moves to revert that, e.g. `dev-python/ipy -> IPy`, or `configargparse -> ConfigArgParse` and the MY_P are being removed left and right, stuff like missing python- prefix are also being added where used and removed if not rather than try to match:

Understood. Thanks for clarifying the new policy.

> One difference is that there's no github to confirm with PyQt (the _ are often based on github), so it feels kind of all over the place of what should really be used.

Yeah, the `-sip` modules are derived from the same source repo as `sip` itself, so you won't find the answer there. The closest piece of evidence is PyQt-builder, whose hg repo is spelled with a hyphen. There's also a PyQt6-Docs repo which also uses the hyphen.

**Pull request closed without merging**
