### PR TITLE
net-mail/notmuch: upstream release 0.28.3

### PR DESCRIPTION
**Pull request by rseichter**
@aidecoe : I don't intend to barge into your territory here, but the last available Gentoo ebuild is for Notmuch version 0.27 which was released in June 2018. There have been four upstream releases since then, 0.28.3 being the most current one, with various improvements. I have copied your latest ebuild and made no modifications.

### CODE REVIEW

**Comment by aidecoe** [comment]
Thanks! Have you run ebuild tests as well? I had 0.28, but tests were failing. I was stuck and didn't have enough time to investigate. I'll have a closer look tomorrow at latest version. I remember that some deps need updating as well.

**Comment by rseichter** [comment]
Build tests require dev-util/valgrind which in turn needs a glibc with debug symbols, and I don't have these. So, no tests here. However, I have been using the 0.28.2 Notmuch binaries locally without issues for a while now; Notmuch being my primary mail client.

**Comment by rseichter** [comment]
Updated the PR for version 0.28.3 (freshly released).

**Comment by aidecoe** [comment]
Sorry I could not merge yours. I had to deal with tests. There were actually 2 issues: xapian versions 1.4.7 and 1.4.8 are broken; plus additional fix for tests specifically was required because of portage network-sandbox feature.

0.28.3 is pushed.

**Comment by rseichter** [comment]
> Sorry I could not merge yours. I had to deal with tests.

No worries. You are the designated maintainer anyway, and the main thing is that the latest Notmuch release becomes available for all Gentoo users.

**Pull request closed without merging**
