### PR TITLE
net-p2p/qbittorrent: add 4.6.2, step down as maintainer

### PR DESCRIPTION
**Pull request by xbt573**
bumped version to 4.6.2, removed myself as maintainer
maybe i will update qbittorrent sometimes, but not as maintainer (version 4.6.2 released a month ago and i forgot about it)
have a good holidays guys :tada:

### CODE REVIEW

**Comment by stkw0** [comment]
Thank you very much for your work with qbittorrent :hugs:  Please, could you add me as a proxy-maint? 
```
	<maintainer type="person" proxied="yes">
		<email>davidroman96@gmail.com</email>
		<name>David Roman</name>
	</maintainer>
```

**Comment by xbt573** [comment]
> Please, could you add me as a proxy-maint?
i think it will be better to create different PR for it, becoming proxy maintainer is not only a metadata.xml change

**Comment by stkw0** [comment]
I'm already registered as proxy maintainer (already maintaining different packages) so afaik only requires a change on the metadata file.

**Comment by thesamesam** [comment]
We normally do such things as a separate PR, yeah.

Thanks both!

**Pull request closed without merging**
