### PR TITLE
media-libs/libwebp: version bump to 0.5.1

### PR DESCRIPTION
**Pull request by andkit**
New subslot, otherwise no modifications from 0.4.2

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/graphics @floppym

**Comment by floppym** [comment]
This version does not compile for me. It appears there is a missing `-lm` somewhere.

```
../src/mux/.libs/libwebpmux.so: error: undefined reference to 'pow'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:523: webpmux] Error 1
make[1]: *** Waiting for unfinished jobs....
../src/mux/.libs/libwebpmux.so: error: undefined reference to 'pow'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:515: gif2webp] Error 1
```

**Comment by floppym** [comment]
Reported upstream.

https://bugs.chromium.org/p/webp/issues/detail?id=306

**Comment by floppym** [comment]
I committed an updated ebuild.

**Pull request closed without merging**
