### PR TITLE
media-sound/playerctl: add 2.4.1

### PR DESCRIPTION
**Pull request by parona-source**
Havent tested x86, but I have no reason to doubt it wont work. Dropped arm64 keyword due to it lacking in dev-python/dbus-next.

### CODE REVIEW

**Comment by parona-source** [comment]
Almost got to a one year anniversary.

**Comment by parona-source** [comment]
PS @thesamesam regarding tests its just one tests which tests the system bus and requires a special config.

https://github.com/altdesktop/playerctl/blob/master/test/data/dbus-system.conf

so better to deselect and still use the rest of the tests

```
EPYTEST_DESELECT=(
	# Requires a lenient dbus config systemwide
	# See test/data/dbus-system.conf and how its used in Dockerfile
	"test/test_basics.py::test_system_list_players"
	# Daemon tests are inconsistent, occasional failure occurs in upstream CI as well.
	"test/test_daemon.py"
)
```

**Comment by thesamesam** [comment]
Thanks, and sorry, I'd completely missed this

**Comment by thesamesam** [comment]
IIRC I didn't do that because the remaining tests looked really bare so I wasn't sure of a point, but let's do it. I'll take a look shortly.

**Comment by thesamesam** [comment]
They still don't pass for me:
```
FAILED test/test_basics.py::test_list_names - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_basics.py::test_queries - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_commands.py::test_commands - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_follow.py::test_follow - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_follow.py::test_follow_selection - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_follow.py::test_follow_selection_any - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_follow.py::test_follow_all_players - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_format.py::test_emoji - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_format.py::test_format - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_selection.py::test_selection - AttributeError: 'coroutine' object has no attribute 'split'
FAILED test/test_selection.py::test_daemon_selection - AttributeError: 'coroutine' object has no attribute 'split'
```

I'll push your work w/ tests restricted but please make a followup to fix up the tests fully.

**Comment by parona-source** [comment]
Ill have a proper look at that, I dont recall seeing any error resembling that. Which is odd as the ebuild doesnt do anything different like enabling python3.12 which would make the cause obvious.

**Comment by parona-source** [comment]
Its related to asyncio-mode. Tests pass if asyncio-mode is set to auto, so something changed with strict during the year or so I last touched it.

**Pull request closed without merging**
