### PR TITLE
dev-libs/glib, dev-util/glib-utils, dev-util/gdbus-codegen: Version bump to 2.74.6

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
If you have the time and inclination, it would be great to see if we can patch glib to skip the test mentioned in https://bugs.gentoo.org/871330

**Comment by flint2** [comment]
> If you have the time and inclination, it would be great to see if we can patch glib to skip the test mentioned in https://bugs.gentoo.org/871330

Sorry, I cannot reproduce the issue with: ebuild dev-libs/glib/glib-2.74.6.ebuild test
.....
311/313 glib:gio / resources                            OK               0.05s
312/313 glib:gio / gsettings                            OK               0.72s
313/313 glib:gio+no-valgrind / codegen.py               OK              13.75s

Ok:                 313 
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0

**Comment by mattst88** [comment]
Do you have `sys-devel/gdb` installed? Sam says in [this comment](https://bugs.gentoo.org/871330#c4) that the test only runs if gdb is present.

**Comment by flint2** [comment]
> Do you have `sys-devel/gdb` installed? Sam says in [this comment](https://bugs.gentoo.org/871330#c4) that the test only runs if gdb is present.

Yes, I have it

dox gentoo # equery l gdb                                
 * Searching for gdb ...
[IP-] [  ] sys-devel/gdb-13.1:0
dox gentoo # equery u gdb
[ Legend : U - final flag setting for installation]
[        : I - package is installed with flag     ]
[ Colors : set, unset                             ]
 * Found these USE flags for sys-devel/gdb-13.1:
 U I
 - - guile                           : Add support for the guile Scheme interpreter
 - - lzma                            : Support lzma compression in ELF debug info
 - - multitarget                     : Support all known targets in one gdb binary
 + + nls                             : Add Native Language Support (using gettext - GNU locale utilities)
 + + python                          : Enable support for the new internal scripting language, as well as extended pretty printers
 + + python_single_target_python3_10 : Build for Python 3.10 only
 - - python_single_target_python3_11 : Build for Python 3.11 only
 - - python_single_target_python3_9  : Build for Python 3.9 only
 + + server                          : Install the "gdbserver" program (useful for embedded/remote targets)
 - - sim                             : Build gdb's simulators for various hardware platforms. See https://sourceware.org/gdb/wiki/Sim.
 - - source-highlight                : Enable listing highlighting via dev-util/source-highlight
 - - test                            : Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can
                                       be toggled independently)
 - - vanilla                         : Do not add extra patches which change default behaviour; DO NOT USE THIS ON A GLOBAL SCALE as the severity
                                       of the meaning changes drastically
 + + xml                             : Support parsing XML data files needed (at least) for cpu features, memory maps, and syscall tracing
 - - xxhash                          : Use dev-libs/xxhash to speed up internal hashing.
 - - zstd                            : Enable support for ZSTD compression
 
 
 
 ================================== 313/313 ===================================
test:         glib:gio+no-valgrind / codegen.py
start time:   21:40:48
duration:     6.30s
result:       exit status 0
command:      GIO_MODULE_DIR='' G_TEST_SRCDIR=/var/tmp/portage/dev-libs/glib-2.74.6/work/glib-2.74.6/gio/tests G_TEST_BUILDDIR=/var/tmp/portage/dev-libs/glib-2.74.6/work/glib-2.74.6-abi_x86_64.amd64/gio/tests GIO_LAUNCH_DESKTOP=/var/tmp/portage/dev-libs/glib-2.74.6/work/glib-2.74.6-abi_x86_64.amd64/gio/gio-launch-desktop MALLOC_PERTURB_=123 /usr/bin/python3.10 -B /var/tmp/portage/dev-libs/glib-2.74.6/work/glib-2.74.6-abi_x86_64.amd64/../glib-2.74.6/gio/tests/codegen.py

**Pull request closed without merging**
