### PR TITLE
EAPI6--

### PR DESCRIPTION
**Pull request by a17r**
Maintainers, please ACK (and cleanup other stale versions yourselves preferably)

### CODE REVIEW

**Review by chewi — APPROVED** [review]
Fine for clanlib.

**Comment by ulm** [comment]
Ack for app-emacs/edb.

**Comment by hlein** [comment]
Ack for app-crypt/loop-aes-losetup

**Comment by madmartin** [comment]
removing app-backup/rear will collide with PR #26828 (opened 6 days ago)

**Comment by a17r** [comment]
> removing app-backup/rear will collide with PR #26828 (opened 6 days ago)

It would autoresolve on rebase, right?

**Comment by blueness** [comment]
Fine for app-doc/halibut

**Comment by benkohler** [comment]
Ack for app-cdr/dumpet

**Comment by madmartin** [comment]
> > removing app-backup/rear will collide with PR #26828 (opened 6 days ago)
> 
> It would autoresolve on rebase, right?

Hmm.. can you explain please? What should be rebased and in which order?

**Comment by maxsatula** [comment]
@a17r you did not have to drop dev-db/ocp-0.2-r1, but that's ok with me. ACK for dev-db/ocp

**Comment by a17r** [comment]
> @a17r you did not have to drop dev-db/ocp-0.2-r1

Dropping EAPI-6 is what this PR is about, would there still be any reason for anyone to mask 0.3 *3.5 years* after it was added in order to downgrade?

**Comment by a17r** [comment]
> > > removing app-backup/rear will collide with PR #26828 (opened 6 days ago)
> > 
> > 
> > It would autoresolve on rebase, right?
> 
> Hmm.. can you explain please? What should be rebased and in which order?

No matter if I picked your removal commit in the other PR or this one, it should be fine after a `git rebase master` and force-push.

**Comment by mattst88** [comment]
> app-admin/pwgen: julian[at]simioni.org, @perfinion, https://github.com/orgs/gentoo/teams/releng, https://github.com/orgs/gentoo/teams/proxy-maint

Approved for releng.

**Comment by perfinion** [comment]
> app-admin/pwgen: @perfinion, https://github.com/orgs/gentoo/teams/releng
> app-crypt/ima-evm-utils: https://github.com/orgs/gentoo/teams/hardened

Both okay :)

**Comment by monsieurp** [comment]
> app-misc/ttyload: @monsieurp, @gentoo/shell-tools

👌

**Comment by prometheanfire** [comment]
> app-admin/augeas: @prometheanfire

ack

**Review by mschiff — APPROVED** [review]

**Review by mschiff — APPROVED** [review]

**Comment by atupone** [comment]
tcltk team (me) is ok (and deleted) regarding to dev-util/tkdiff

**Comment by robbat2** [comment]
+1 for mirdir

**Review by chewi — APPROVED** [review]
Fine for libdvbcsa.

**Review by voyageur — APPROVED** [review]
Ack for x11-plugins/wmsysmon

**Comment by Philippe23** [comment]
Fine for postforward.

**Comment by candrews** [comment]
Ack for net-libs/shairplay

**Review by candrews — APPROVED** [review]

**Comment by jkroonza** [comment]
ACK for x11-wm/evilwm - thank you.

**Review by chewi — APPROVED** [review]
Fine for dtv-scan-tables.

**Comment by PPed72** [comment]
Fine for net-misc/netkit-telnetd. https://github.com/gentoo/gentoo/pull/27056

**Review by akhuettel — APPROVED** [review]
OK for xosview

**Comment by MathyV** [comment]
Fine for net-vpn/networkmanager-fortisslvpn

**Comment by mattst88** [comment]
Ack for catalyst.

**Comment by slashbeast** [comment]
redshift ack, thanks for taking care of it.

**Review by jkroonza — APPROVED** [review]
ACK for xbindkeys.

**Comment by floppym** [comment]
ACK on dev-libs/openssl-compat:0.9.8. It appears to have no in-tree revdeps. We can restore it with a newer EAPI if someone has a good use case for it.

**Comment by floppym** [comment]
sys-apps/gsmartcontrol and sys-apps/minised seem fine as well.

**Pull request merged**
