### PR TITLE
Do not remove .egg-info

### PR DESCRIPTION
**Pull request by parona-source**

### CODE REVIEW

**Comment by parona-source** [comment]
Ceph takes a while to finish, so ill mark it as ready once ive tested both 16 and 18.

**Comment by chutz** [comment]
Does the removal of `.egg-info` break anything in bcc? I haven't seen any reports, and my local testing was fine.

**Comment by parona-source** [comment]
It doesn't break anything as nothing appears to depends on the package having metadata. Its just the incorrect way to handle it.

**Comment by eli-schwartz** [comment]
> Does the removal of `.egg-info` break anything in bcc? I haven't seen any reports, and my local testing was fine.

Upstream setuptools intends to "someday remove support for executing the setup.py file with the install argument".

What the timeline for that is, is unknown and underspecified. The consequences will be that the package stops building at all -- cmake will error out.

This package doesn't use distutils-r1.eclass so the timeline for eclass deprecation of non-pep517 mode is irrelevant. It can be argued that that means the QA check is wrong and a false positive.

**Comment by mgorny** [comment]
The QA check was added deliberately to catch packages that don't use the eclass, yet use deprecated setuptools logic.

**Comment by eli-schwartz** [comment]
Thanks for clarifying. Can you suggest a general approach to be used for projects that don't use the eclass, and don't use the deprecated setuptools logic, but call a large, nontrivial build system that internally uses the deprecated setuptools logic without an escape hatch and cannot even be used standalone due to the setup.py itself being generated by the "real" build system?

**Comment by mgorny** [comment]
> Thanks for clarifying. Can you suggest a general approach to be used for projects that don't use the eclass, and don't use the deprecated setuptools logic, but call a large, nontrivial build system that internally uses the deprecated setuptools logic without an escape hatch and cannot even be used standalone due to the setup.py itself being generated by the "real" build system?

Last rite them.

**Pull request closed without merging**
