### PR TITLE
games-board/megamek: add 0.49.19

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by fordfrog** [comment]
is that missing gco sign-off caused by some commits with no empty line before the sign-off?

**Comment by vaukai** [comment]
> is that missing gco sign-off caused by some commits with no empty line before the sign-off?

it was caused by the two reversals where i had to use `git commit` instead of `pkgdev commit`. there i added sign-off later but that label didn't go away.

anyway, this PR is meant to be assigned to games team.

**Comment by fordfrog** [comment]
i guess those 3 commits for commons-text can be squashed.

**Comment by vaukai** [comment]
> i guess those 3 commits for commons-text can be squashed.

i wasn't sure, so just squashed.

**Comment by fordfrog** [comment]
it doesn't run for me:
```
$ megamek 

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by vaukai** [comment]
> it doesn't run for me:
> 
> ```
> $ megamek 
> 
> Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
> ```

what is it missing? how to find out?

**Comment by fordfrog** [comment]
> what is it missing? how to find out?

it doesn't show the full stacktrace so it's hard to tell. i was first waiting whether you have any clue before digging in.

here is some info that might be helpful:
```
$ GJL_DEBUG=y megamek
Calling: gjl --package megamek --get-args --get-vm
Using: openjdk-21
Running: exec java  -classpath /usr/share/megamek/lib/megamek.jar -Djava.library.path=/lib64  megamek.MegaMek  

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by vaukai** [comment]
> > what is it missing? how to find out?
> 
> it doesn't show the full stacktrace so it's hard to tell. i was first waiting whether you have any clue before digging in.
> 
> here is some info that might be helpful:
> 
> ```
> $ GJL_DEBUG=y megamek
> Calling: gjl --package megamek --get-args --get-vm
> Using: openjdk-21
> Running: exec java  -classpath /usr/share/megamek/lib/megamek.jar -Djava.library.path=/lib64  megamek.MegaMek  
> 
> Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "main"
> ```

ah, thanks for `$ GJL_DEBUG=y`.
i am converting this PR to `draft` so it will be the last [blocker](https://bugs.gentoo.org/showdependencytree.cgi?id=803521&hide_resolved=1) in [eapi 7](https://qa-reports.gentoo.org/output/eapi-per-eclass/java-ant-2.eclass/7.txt) and we can save our time for `hsqldb` (needs help for `src_install()`) and the other commits in https://github.com/gentoo/gentoo/pull/37022.

**Comment by fordfrog** [comment]
looking at `package.env` there are really no runtime deps:
```
DESCRIPTION="Unofficial online version of the Classic BattleTech board game"
GENERATION="2"
SLOT="0"
CATEGORY="games-board"
PVR="0.49.19"
LIBDIR="lib64"
CLASSPATH="/usr/share/megamek/lib/megamek.jar"
VM=">=virtual/jre-11:*"
BUILD_DEPEND="commons-logging:commons-text:jackson-databind:jackson-dataformat-yaml:jakarta-mail:jaxb-api-4:log4j-12-api-2"
TARGET="11"
SOURCE="11"
MERGE_VM="openjdk-21"
```

**Comment by vaukai** [comment]
> looking at `package.env` there are really no runtime deps:
> 
> ```
> DESCRIPTION="Unofficial online version of the Classic BattleTech board game"
> GENERATION="2"
> SLOT="0"
> CATEGORY="games-board"
> PVR="0.49.19"
> LIBDIR="lib64"
> CLASSPATH="/usr/share/megamek/lib/megamek.jar"
> VM=">=virtual/jre-11:*"
> BUILD_DEPEND="commons-logging:commons-text:jackson-databind:jackson-dataformat-yaml:jakarta-mail:jaxb-api-4:log4j-12-api-2"
> TARGET="11"
> SOURCE="11"
> MERGE_VM="openjdk-21"
> ```

so one day i should try with most deps put in `CP_DEPEND` and `java-pkg_dojar` all deps bundled from `SRC_URI`.
also would be good to check the [startup.sh](https://github.com/MegaMek/megamek/blob/master/megamek/startup.sh) for more information.
and i just recalled there was one game using [--pwd](https://gitweb.gentoo.org/repo/gentoo.git/tree/games-strategy/freecol/freecol-1.0.0.ebuild).

**Comment by chewi** [comment]
[microsoft-identity-broker](https://github.com/gentoo/gentoo/blob/96c790be4d9760a9447a8b462bdae812b606552a/sys-auth/microsoft-identity-broker/microsoft-identity-broker-2.0.0.ebuild) is a good example of how to do this right.

**Comment by vaukai** [comment]
> [microsoft-identity-broker](https://github.com/gentoo/gentoo/blob/96c790be4d9760a9447a8b462bdae812b606552a/sys-auth/microsoft-identity-broker/microsoft-identity-broker-2.0.0.ebuild) is a good example of how to do this right. Ignore the wrapper stuff though.

thanks for the hint - will check it when getting back to this package

**Pull request closed without merging**
