### PR TITLE
app-forensics/chkrootkit: Change maintainer and remove obsolete ebuild data

### PR DESCRIPTION
**Pull request by JordyZomer**
Hello,

I would like to maintain the chkrootkit package and I have added a patch to bug 509000:

https://bugs.gentoo.org/509000

Kind Regards,

Jordy Zomer

### CODE REVIEW

**Comment by JordyZomer** [comment]
Updated the Manifests file so the obsolete ebuild is gone and doesn't pollute the repo.

**Comment by monsieurp** [comment]
Hi @JordyZomer. Please make sure to read https://wiki.gentoo.org/wiki/Gentoo_GitHub#Commit_format to format your commit message properly.

**Comment by JordyZomer** [comment]
@monsieurp thank you a lot, bookmarked it. Do I have to change them?

**Comment by monsieurp** [comment]
Yes, please.

**Comment by monsieurp** [comment]
Just squash all your commits into one single commit and push force it.

**Comment by JordyZomer** [comment]
@monsieurp better now? :)

**Comment by diogocp** [comment]
What you need to change is the commit message, not the pull request title (although fixing the PR title is also welcome). You also did not squash the commits, you just added more of them. See https://stackoverflow.com/questions/5189560 for how to squash.

You say you have added a patch to [bug 509000](https://bugs.gentoo.org/509000), but this PR does not include the patch. Did you forget it? If you add a commit that fixes a bug, you should also [link to that bug  in the commit message](https://wiki.gentoo.org/wiki/Gentoo_GitHub#Links_to_bug_report.28s.29).

Finally, since you are not a Gentoo developer, you need to add proxy-maint@gentoo.org as maintainer to metadata.xml ([example](https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Proxied_maintainer_in_metadata.xml)). While you're doing that, make sure to fix the indentation, because right now it uses both tabs and spaces.

**Pull request closed without merging**
