### PR TITLE
net-libs/libwebsockets: bump to 1.7.9

### PR DESCRIPTION
**Pull request by mapx**

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by mapx** [comment]
@gktrk Sorry I didn't realized they are not simple security updates like their version numbers indicate. 

Some new USEs are included in the updated commit:
`cgi`, `http-proxy`, `access-log`, and `server-status`

`LWS_WITH_LWSWS` and `LWS_WITH_PLUGINS` are not introduced because the former requires the later and enabling `LWS_WITH_PLUGINS` leads to a make error.

Thanks :)

**Comment by gktrk** [comment]
Per: 
```
if (LWS_WITH_HTTP_PROXY)
	find_library(LIBHUBBUB_LIBRARIES NAMES libhubbub)
	list(APPEND LIB_LIST ${LIBHUBBUB_LIBRARIES} )
endif()
```

I think we need to depend on `net-libs/libhubbub`. Did you actually get a chance to test these newly added USE flags?

Also, I see the following in their cmake file which makes me wonder whether they are of any use without the plugins support:

```
if (LWS_WITH_SERVER_STATUS)
	install(FILES plugins/server-status.html;plugins/lwsws-logo.png
		DESTINATION share/libwebsockets-test-server/server-status
			COMPONENT examples)
endif()
```

```
if (LWS_WITH_SERVER_STATUS)
		create_plugin(protocol_lws_server_status
			      "plugins/protocol_lws_server_status.c")
endif()
```

Indeed, I compiled the package with and without `USE='access-log server-status` and I saw no difference in installed files on the system.

Can we double check? Thanks.

**Comment by mapx** [comment]
@gktrk It looks like you have found a syntax error in its `CMakeLists.txt` so that `libhubbub` cannot be found.
A pull request https://github.com/warmcat/libwebsockets/pull/645 is created. Let's wait for a little while.
Thanks for pointing it out :)

**Comment by gktrk** [comment]
Looks like we're gonna have to backport your patch, I don't see upstream releases with your fix.

**Comment by mapx** [comment]
New releases with the fix are yet to come. The upstream promises to apply it in v2.0-stable, v2.1-stable and master, which imples that 1.7.x becomes a legacy version.
How about only releasing 1.7,9 ebuild without `http-proxy` and this time?

**Comment by gktrk** [comment]
That should be fine. What do you think of my comment about `access-log` and `server-status` flags wrt plugins support?

**Comment by mapx** [comment]
These additional flags come along with v2.0 and v2.1. I incorrectly added them to 1.7.9 ebuild.

`server-status` seems enable `LWS_WITH_PLUGINS`. The feature will be checked once new version is released.

And you are right: it is better to split each version bump into its own commit whenever possible :)

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/3ce3961...67cf2ed. Thanks!

Also glad that I was able to demonstrate the importance of separate atomic commits ;)

**Pull request closed without merging**
