### PR TITLE
sci-physics/rivet: add 3.1.9, 9999

### PR DESCRIPTION
**Pull request by APN-Pucky**
PR created by [pkgpr](https://github.com/APN-Pucky/pkgpr).

Given the upstream problem https://gitlab.com/hepcedar/rivet/-/issues/441 I think it is best to also provide the predecessor version to 3.1.10 and a live ebuild. Both are viable solutions to the issue, until there is a new release (or I decide to make a  `_p2024...` ebuild).

### CODE REVIEW

**Comment by Jamim** [comment]
_Hello @APN-Pucky,_
Would you mind adding [4.0.0](https://gitlab.com/hepcedar/rivet/-/releases/rivet-4.0.0) as well?
_Thanks in advance!_

**Comment by APN-Pucky** [comment]
> _Hello @APN-Pucky,_ Would you mind adding [4.0.0](https://gitlab.com/hepcedar/rivet/-/releases/rivet-4.0.0) as well? _Thanks in advance!_

Yes, I was planning to and I have it prepared already. However I was not sure if it should be put in slot `:4`, while slot 3 and 4 can not be installed simultaneous. @AndrewAmmerlaan can you maybe suggest what would be best? Should there be a `:4-9999` too (they have two release branches) or follow the naming scheme of sci-physics/root?

**Comment by AndrewAmmerlaan** [comment]
> > _Hello @APN-Pucky,_ Would you mind adding [4.0.0](https://gitlab.com/hepcedar/rivet/-/releases/rivet-4.0.0) as well? _Thanks in advance!_
> 
> Yes, I was planning to and I have it prepared already. However I was not sure if it should be put in slot `:4`, while slot 3 and 4 can not be installed simultaneous. @AndrewAmmerlaan can you maybe suggest what would be best? Should there be a `:4-9999` too (they have two release branches) or follow the naming scheme of `sci-physics/root`?

You can put it in a separate slot for aesthetic reasons and add a blocker. Personally I don't like (ab)using the slots for the major version number when there is no parallel install capability, but it is done in other places as well and we already have the 3.x.y versions in slot 3 anyway. So I'll let you decide, as far as I know there is no official consensus or policy on whether slots may be used like this.

If upstream has two (actively maintained) release branches then I do think it makes sense to have two `9999` ebuilds. Note though that this does not mean that we _have_ to put them in separate slots, see for example `media-video/vlc` which has two live ebuilds but only one slot.

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1:

**Pull request closed without merging**
