### PR TITLE
dev-python/pyroute2: bump to 0.7.1

### PR DESCRIPTION
**Pull request by henning-schild**
Closes: https://bugs.gentoo.org/815394
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
upstream has already merged code for simpler packaging on their master branch https://github.com/svinota/pyroute2/issues/935

this 9999 would currently build a 0.6.13+

since we have that bug open we might as well have a 9999 version in the tree, in addition that gave the chance to test things before upstream releases a 0.7

**Comment by Alessandro-Barbieri** [comment]
Please don't close the bug, I have no use of a 9999 package

**Comment by juippis** [comment]
0.7.1 seems to have been released yesterday. Could you update the PR for that? 

In future you can do "snapshot" packages based on github commits, just look for a good healthy commit to base your snapshot on. And it seems this particular upstream even does rc's so that's a good point to base a snapshot on.

**Comment by henning-schild** [comment]
I am looking into that new release. But it seems to be using a thing called "nox" and a `pyproject.toml` without a `setup.py`. portage is suggesting to use `DISTUTILS_USE_SETUPTOOLS=pyproject.toml` but that does not seem to work and seems deprecated.

Long story short, they switched to some packaging tool which does not seem to work in gentoo ... yet. It is also possible that i simply do not get how to package that now. Seems i have to at some point understand that whole PEP517 setuptools.

What i found so far is

https://github.com/svinota/pyroute2/issues/939

and

https://blogs.gentoo.org/mgorny/2021/11/07/the-future-of-python-build-systems-and-gentoo/

**Comment by henning-schild** [comment]
looks like that pyproject.toml might be invalid, https://github.com/svinota/pyroute2/pull/961

**Comment by henning-schild** [comment]
That upstream patch i wrote was applied, if needed i could include the upstream sha into that cherry-pick. And upstream might follow up with a release.

But i think we can proceed here. If there will be another release we can bump, and i think we do not need to include the upstream sha into the now "cherry-pick" fix.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
