### PR TITLE
keyword app-text/writerperfect for riscv

### PR DESCRIPTION
**Pull request by bekcpear**
tatt report(with 'test' USE enabled):
[atoms.report.txt](https://github.com/gentoo/gentoo/files/8308357/atoms.report.txt)

running test:
Screenshot_20220318_140418

known potential upstream bug:
https://bugs.gentoo.org/835525

### CODE REVIEW

**Comment by jsmolic** [comment]
@bekcpear Hi, you mentioned asking on the mailing list in https://bugs.gentoo.org/835525#c4, did you get any additional info regarding the issue?

**Comment by bekcpear** [comment]
> @bekcpear Hi, you mentioned asking on the mailing list in https://bugs.gentoo.org/835525#c4, did you get any additional info regarding the issue?

No, I haven't got any reply yet. I create a ticket here (https://sourceforge.net/p/libwpd/tickets/20/), and asked again.

**Comment by jsmolic** [comment]
Can you arrange commits following the dependency chain (i.e. writerperfect should be the last commit)? For example when checked out at current writerperfect commit I get:
```
app-text/writerperfect
  NonsolvableDepsInDev: version 0.9.6: nonsolvable depset(depend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ =app-text/libabw-0.1*, =app-text/libebook-0.1*, =app-text/libmwaw-0.3*, media-libs/libeot ]
  NonsolvableDepsInDev: version 0.9.6: nonsolvable depset(rdepend) keyword(~riscv) dev profile (default/linux/riscv/20.0/rv64gc/lp64/desktop) (12 total): solutions: [ =app-text/libabw-0.1*, =app-text/libebook-0.1*, =app-text/libmwaw-0.3*, media-libs/libeot ]
  NonsolvableDepsInStable: version 0.9.6: nonsolvable depset(depend) keyword(~riscv) stable profile (default/linux/riscv/20.0/rv64gc/lp64) (4 total): solutions: [ =app-text/libabw-0.1*, =app-text/libebook-0.1*, =app-text/libmwaw-0.3*, media-libs/libeot ]
  NonsolvableDepsInStable: version 0.9.6: nonsolvable depset(rdepend) keyword(~riscv) stable profile (default/linux/riscv/20.0/rv64gc/lp64) (4 total): solutions: [ =app-text/libabw-0.1*, =app-text/libebook-0.1*, =app-text/libmwaw-0.3*, media-libs/libeot ]
```

**Comment by bekcpear** [comment]
> Can you arrange commits following the dependency chain

Thanks for reminding, done.

**Comment by jsmolic** [comment]
Thanks for updating it. I think the issue linked is not risc-v specific as I encountered it on amd64 too so it won't block merging.

**Pull request closed without merging**
