### PR TITLE
Various py3.12 bumps

### PR DESCRIPTION
**Pull request by vimproved**

### CODE REVIEW

**Comment by thesamesam** [comment]
Do tests pass for all of these?

**Comment by vimproved** [comment]
> Do tests pass for all of these?

1. glib-utils does not have tests.
2. mesa fails, but it doesn't appear to be related to the python bump, since I can replicate without py3.12 (same issue as https://bugs.gentoo.org/830728).
3. systemd-utils passes.
4. xcb-proto passes.
5. libdrm has RESTRICT=test.
6. libxcb passes.
7. glib fails, but once again it doesn't appear related to the py3.12

**Comment by mgorny** [comment]
You have two commits with summary saying mesa.

**Comment by vimproved** [comment]
> You have two commits with summary saying mesa.

Fixed.

**Pull request closed without merging**
