### PR TITLE
app-misc/timew: add manpages

### PR DESCRIPTION
**Pull request by janko-j1**
Closes: https://bugs.gentoo.org/851873

Signed-off-by: David Denoncin <ddenoncin@gmail.com>

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks. Since this modifies the content of the installed package image, it requires a version bump.

**Comment by janko-j1** [comment]
Argh I hope that at some point I'll get that right. I assumed you meant *revision* bump ;-) Thanks.

**Comment by Flowdalic** [comment]
> Argh I hope that at some point I'll get that right. I assumed you meant _revision_ bump ;-) Thanks.
Yes, right, *revision* bump. :)

Please also drop the old revision, as there is no need to keep it.

**Comment by janko-j1** [comment]
Thanks, done. I ran pkgcheck as I forgot to do so before and amended the name of the revised file.

**Comment by Flowdalic** [comment]
I mean to drop 1.3.1, i.e. the last *revision*, not the last version (which we may want to keep for stabilization reasons). As a general rule of thumb, if you do a "trivial" fix for an not-stabilized ebuild which requires a new revision, then also remove the old revision.

Note that you may want to consider using readme.gentoo-r1.ecass and bump the package to EAPI 8.

**Pull request closed without merging**
