### PR TITLE
net-misc/x2goclient: Eliminate qt4 vs. qt5 REQUIRED_USE conflict

### PR DESCRIPTION
**Pull request by a17r**
Instead, nsplugin does not work with USE=qt5
Gentoo-bug: 597420

Fix translations along the way. Smaller patch.

PS: I'm not actually using this package, so it needs runtime testing.

@voyageur

### CODE REVIEW

**Comment by voyageur** [comment]
Hmm translations (at least French one) worked for me with the current in-tree patch?
I will check for the nsplugin build, it may be related to a currently open bug where compilation fails on qt4 specific includes. But no promises until end of next week (travelling at the moment).

Note that x2goclient qt5 support is still in the "shiny new" state, so it needs testing and probably additional fixes before switching away from qt4 default

**Comment by a17r** [comment]
@voyageur I was getting complaints during configure about nonexisting qm paths inside resources.qrc (with the original patch) and indeed the tarball only ships *.ts instead.

**Comment by voyageur** [comment]
@a17r I just checked and while the configure step does complain about the missing files, they are the first ones generated at compile step:
```
>>> Configuring source in /var/tmp/portage/net-misc/x2goclient-4.0.5.2/work/x2goclient-4.0.5.2 ...
 * Running qmake ...
Project MESSAGE: if you want to build x2goplugin you should export X2GO_CLIENT_TARGET=plugin
Project MESSAGE: building x2goclient with ldap and cups
RCC: Error in '../x2goclient-4.0.5.2/res/resources.qrc': Cannot find file 'i18n/x2goclient_da.qm'
[...]                                                                                                                                                 [ ok ]
>>> Source configured.
>>> Compiling source in /var/tmp/portage/net-misc/x2goclient-4.0.5.2/work/x2goclient-4.0.5.2 ...
make -j8 
/usr/lib64/qt5/bin/lrelease ../x2goclient-4.0.5.2/res/i18n/x2goclient_de.ts
/usr/lib64/qt5/bin/lrelease ../x2goclient-4.0.5.2/res/i18n/x2goclient_da.ts
[...]
```
Maybe worth a check with upstream, but qm files generation in src_compile looks like a fine place (and less ebuild-specific build parts).

As for the rest, restricting the USE=nsplugin support and trimming the patch (already merged upstream so next version won't need it) looks OK

**Comment by a17r** [comment]
Certainly better than doing this manually in src_prepare, so removed that. Thanks!

**Comment by a17r** [comment]
@voyageur good to go now, I hope? ;)

**Comment by voyageur** [comment]
Thanks for your changes :)

**Pull request closed without merging**
