### PR TITLE
riscv: keyword dev-python/dask

### PR DESCRIPTION
**Pull request by alexfanqi**
tested on sifive unmatched

### CODE REVIEW

**Comment by mgorny** [comment]
Have you tested with `ALLOW_TEST="network"`? If not, you may want to retest at least imageio, and look for other packages on the list that have `PROPERTIES="test_network"`.

**Comment by mgorny** [comment]
CC @gentoo/risc-v

**Comment by alexfanqi** [comment]
> PROPERTIES="test_network"

I didn't :-P Thanks for the tips. I will retest and come back later

**Comment by alexfanqi** [comment]
`grep PROPERTIES $(git diff --name-only official/master..HEAD)` shows imageio is the only package requires `ALLOW_TEST="network"`. I removed it from this pr for now and will retest it in another pr.

**Pull request closed without merging**
