### PR TITLE
net-im/signal-cli-bin: add 0.12.5

### PR DESCRIPTION
**Pull request by MrRoy**

### CODE REVIEW

**Comment by dlan17** [comment]
@MrRoy are you still interested in maintaining this package? it seems there is new release 0.12.7

@madmartin are still active? and ok to co-maintain?

thanks all

**Comment by MrRoy** [comment]
@dlan17 yes, I will update the PR for 0.12.7, I hadn't noticed it was released :)

**Comment by MrRoy** [comment]
@dlan17 done

**Comment by madmartin** [comment]
> 
> @madmartin are still active? and ok to co-maintain?
> 

@dlan17 Yes still active (but sometimes lazy...) and I'm fine with co-maintainers

**Pull request closed without merging**
