### PR TITLE
Weboob 2.0

### PR DESCRIPTION
**Pull request by laurentb**
As requested, #15160 but done by me.

> Deprecate old Python2 olny 1.3 version and add new, revent 2.0 version, that is Pyton3 compatible. The ebuild is mostly based on upstream's ebuild with some polishing.

### CODE REVIEW

**Comment by zpuskas** [comment]
Please update the Signed-off-by in the commit messages, since you are submitting the change and it's signed by your GPG keys.

**Comment by juippis** [comment]
Looks like this was deleted from Gentoo.

**Comment by laurentb** [comment]
It was deleted for a reason that this PR fixes

**Comment by juippis** [comment]
This patch wouldn't apply cleanly to ::gentoo repo anymore. And the bugs were closed. 

What you can do, is submit this as a new package where you + proxy-maint are the sole maintainers. Clearly the previous maintained didn't care about this package, and we don't see notifications for packages belonging to other devs. I'm just cleaning Github where possible.

**Pull request closed without merging**
