### PR TITLE
www-client/chromium: Stabilize 107.0.5304.121 amd64, #883033

### PR DESCRIPTION
**Pull request by elkablo**
Signed-off-by: Marek Behún <kabel@kernel.org>

### CODE REVIEW

**Comment by scardracs** [comment]
It's not like that. Stabilization is required over b.g.o and then it's the arch team that decide if stabilize or not a package. Please close this PR. https://wiki.gentoo.org/wiki/Stable_request

**Comment by stha09** [comment]
Maintainers can stabilize on amd64 themselves and there is a bug open asking for it.

**Comment by stha09** [comment]
@floppym I think it is ok to merge.

**Comment by scardracs** [comment]
> Maintainers can stabilize on amd64 themselves and there is a bug open asking for it.

It should be a good idea to link the bug then.

**Pull request closed without merging**
