### PR TITLE
media-video/mpv: update live ebuild

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by l29ah** [comment]
HTTPS should be preferred as it's more secure.

**Comment by Coacher** [comment]
> HTTPS should be preferred as it's more secure.

See https://github.com/gentoo/gentoo/pull/2572/commits/37a4eb12691b27631f4f23fe60dc26aff5f4fe47

**Comment by l29ah** [comment]
It prefers git://.

**Comment by Coacher** [comment]
See commit message in https://github.com/gentoo/gentoo/pull/2572/commits/37a4eb12691b27631f4f23fe60dc26aff5f4fe47. There's an answer why https cannot be preferred with the current git-r3 behaviour.

**Comment by mgorny** [comment]
> See commit message in https://github.com/gentoo/gentoo/pull/2572/commits/37a4eb12691b27631f4f23fe60dc26aff5f4fe47. There's an answer why https cannot be preferred with the current git-r3 behaviour.

If you have a problem with git-r3 behavior, then report a bug. Things won't get fixed when people silently workaround them in ebuilds and expect eclass maintainers to read random commit messages or consult a crystal ball.

**Comment by Coacher** [comment]
https://github.com/gentoo/gentoo/commit/24db6037e69ca7fe9c425cec72111866377adb25 made it to the tree. I'll update this PR accordingly later today.

**Comment by Coacher** [comment]
Updated and ready for merge.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by Coacher** [comment]
Thank you, @gktrk.

**Pull request closed without merging**
