### PR TITLE
Hyprland update

### PR DESCRIPTION
**Pull request by JohnMH**
Adds hyprutils 0.2.1, sync live deps. Clean old versions.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by JohnMH** [comment]
@MrRoy Please take a look when you get a chance.

**Review by MrRoy — APPROVED** [review]
LGTM, thanks !

**Comment by JohnMH** [comment]
Added hyprland 0.42.0.

**Comment by JohnMH** [comment]
@MrRoy If you don't mind, please take a look again.

**Pull request closed without merging**
