### PR TITLE
zig.eclass: new eclass

### PR DESCRIPTION
**Pull request by vimproved**
This is an eclass to help with building programs that use Zig's "build system." It includes things such as PIE support and the ability to set min/max for Zig versions.

### CODE REVIEW

**Comment by vimproved** [comment]
See https://codeberg.org/vimproved/overlay/src/branch/master/gui-wm/river/river-0.2.4.ebuild for an example ebuild using this eclass. Currently `sys-fs/ncdu` is the only ebuild in ::gentoo that would use this.

**Comment by thesamesam** [comment]
I think this is proabbly good to go given no eclass comments. Maybe port an ebuild to it in this PR though?

**Comment by vimproved** [comment]
> I think this is proabbly good to go given no eclass comments. Maybe port an ebuild to it in this PR though?

I was considering doing `sys-fs/ncdu` (appears to be the only revdep of zig in tree) but I didn't want to mess with other people's packages.

**Comment by vimproved** [comment]
Changelog:
- Added ZIG_BUILD_TYPE to control the build type passed to `-Doptimize`
- Made ZIG_MAX and ZIG_MIN properly handle setting dependencies
- Made ZIG_MAX exclusive

**Comment by vimproved** [comment]
@BratishkaErik, do you see any problems with this?

**Comment by BratishkaErik** [comment]
> @BratishkaErik, do you see any problems with this?

oh I didn't even know about thins until your ping :) I'm heading to study rn so will review only later (thank you in advance!), but in general this looks fine to me, except:

It probably should've been done as two separate eclass-es instead, one for detecting and using Zig's version and other properties (I suggest zig-toolchain name) and another purely for ZBS (zig-build?). I suggest to extract them now (second should inherit from first).
I'm not 100% sure if adding two new eclasses in one PR is allowed, IIRC it is, but if it is not I'd suggest to PR zig-toolchain first.

Other than that, everything else is not blocking this PR. But again, I'll be able to reciew it more properly only after studying, sorry.

**Comment by vimproved** [comment]
I'm going to close this right now and open a new PR once zig 0.12 has been released with its better support for a global package cache.

**Pull request closed without merging**
