### PR TITLE
media-plugins/hexter: drop gtk2 support

### PR DESCRIPTION
**Pull request by epsilon-0**
Closes: https://bugs.gentoo.org/769035
Package-Manager: Portage-3.0.14, Repoman-3.0.2

### CODE REVIEW

**Comment by fordfrog** [comment]
@epsilon-0 is there any gui replacement? or there's no need for gui and the text interface is sufficient?

**Comment by epsilon-0** [comment]
@fordfrog unsure, I don't use hexter.
I had looked around a bit upstream in the options and it *seems* like textui should be enough.

**Comment by fordfrog** [comment]
@epsilon-0 i'd give it some more time if you don't mind. still not sure whether to drop it already to the textui only interface.

**Comment by epsilon-0** [comment]
yes, no problem, theres no hurry.

**Comment by fordfrog** [comment]
@epsilon-0 thanks!

**Pull request closed without merging**
