### PR TITLE
media-libs/vulkan-loader: Version bump

### PR DESCRIPTION
**Pull request by FireBurn**
I was seeing stange behaviour with 1.3.204:

https://github.com/HansKristian-Work/vkd3d-proton/issues/1003

The fix was added in 1.3.205, 1.3.206 was just released to bump to that

https://github.com/KhronosGroup/Vulkan-Loader/commit/356945ba6607b238929ed80e2181dadd123079c8

Signed-off-by: Mike Lothian <mike@fireburn.co.uk>

### CODE REVIEW

**Comment by stefson** [comment]
please don't forget to bump the headers as well

**Comment by mattst88** [comment]
We should cherry-pick the patch to v1.3.204. We don't want to package non "SDK" tagged versions.

**Comment by mattst88** [comment]
I don't know what's going on. I'm confused how you could be seeing strange behavior from something in v1.3.204 (the physical device ordering change) because it doesn't look like that's actually included in the `sdk-1.3.204.0` tag that our `media-libs/vulkan-loader-1.3.204` corresponds to.

Are you actually using `media-libs/vulkan-loader-1.3.204` from ::gentoo or are you using the v1.3.204 tag from some local ebuild in your overlay? It looks like you're not using the sdk- tags according to https://github.com/FireBurn/Overlay/commit/548b29f33b1abd63340c0b5a2248eb51e1c79bd3 in which case... ugh, thanks for really confusing things?

I've filed an issue to try to figure out why the sdk-1.3.204.0 and v1.3.204 tags are so different, here: https://github.com/KhronosGroup/Vulkan-Loader/issues/862

**Comment by FireBurn** [comment]
I saw the issue with vulkan-loader-1.3.204::gentoo

It took me a while to figure out it was the loader that was the issue, I tried different versions of wine, mesa, the kernel, proton, vkd3d-proton. Only going back to very old versions of vkd3d-proton fixed it (pre device filter it would seem)

Testing vulkan-loader-1.3.206 from my overlay using non sdk tags fixed the issue, I'm assuming it was KhronosGroup/Vulkan-Loader@356945b but I didn't actually bisect it

**Comment by mattst88** [comment]
Okay, thanks. Sounds like what we do know for sure is

- `sdk-1.3.204.0` is broken
- `v1.3.206` is working

But we do not know which commit breaks things nor which commit fixes things.

**Comment by mattst88** [comment]
From the response in https://github.com/KhronosGroup/Vulkan-Loader/issues/862 it's expected that the `sdk-1.3.204.0` differs significantly from `v1.3.204` because `v1.3.204` was evidently chock full of bugs.

But your report evidently indicates that `sdk-1.3.204.0` had some bad bug too. /o\

If you could bisect and find the fix, we could apply it, but bumping to `v1.3.206` isn't an option.

**Comment by FireBurn** [comment]
So that sounded easy, but has proven less so

I've been using the 9999 ebuild to aid bisecting, the sdk-1.3.204.0 commit just errors out - I've no idea why

`EGIT_OVERRIDE_COMMIT_KHRONOSGROUP_VULKAN_LOADER=6a2458b649aae2a8bec8259c2485e7c0bd0465ae emerge =vulkan-loader-9999 -O1`

It also turns out that v1.3.204 works perfectly fine

So I thought I'd try bisecting between sdk-1.2.298.1 to see if that makes a difference but again I emerge that commit

```
axion /home/fireburn/Vulkan-Loader # export EGIT_OVERRIDE_COMMIT_KHRONOSGROUP_VULKAN_LOADER=0ca96994f92b6f21b37badd6c99b22f61bfec932
axion /home/fireburn/Vulkan-Loader # emerge vulkan-loader -O1

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) media-libs/vulkan-loader-9999::gentoo
>>> Unpacking source...
 * Repository id: KhronosGroup_Vulkan-Loader.git
 * Using EGIT_OVERRIDE_COMMIT_KHRONOSGROUP_VULKAN_LOADER=0ca96994f92b6f21b37badd6c99b22f61bfec932
 * No support will be provided.
 * Fetching https://github.com/KhronosGroup/Vulkan-Loader.git ...
git fetch https://github.com/KhronosGroup/Vulkan-Loader.git +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/media-libs/vulkan-loader/0/__main__ 0ca96994f92b6f21b37badd6c99b22f61bfec932
fatal: update_ref failed for ref 'refs/git-r3/media-libs/vulkan-loader/0/__main__': cannot update ref 'refs/git-r3/media-libs/vulkan-loader/0/__main__': trying to write ref 'refs/git-r3/media-libs/vulkan-loader/0/__main__' with nonexistent object 0ca96994f92b6f21b37badd6c99b22f61bfec932
 * ERROR: media-libs/vulkan-loader-9999::gentoo failed (unpack phase):
 *   Referencing 0ca96994f92b6f21b37badd6c99b22f61bfec932 failed (wrong ref?).
 * 
 * Call stack:
 *     ebuild.sh, line  127:  Called src_unpack
 *   environment, line 3097:  Called git-r3_src_unpack
 *   environment, line 2241:  Called git-r3_src_fetch
 *   environment, line 2235:  Called git-r3_fetch
 *   environment, line 2148:  Called die
 * The specific snippet of code:
 *                   die "Referencing ${remote_ref} failed (wrong ref?).";
 * 
 * If you need support, post the output of `emerge --info '=media-libs/vulkan-loader-9999::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=media-libs/vulkan-loader-9999::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/media-libs/vulkan-loader-9999/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/media-libs/vulkan-loader-9999/temp/environment'.
 * Working directory: '/var/tmp/portage/media-libs/vulkan-loader-9999/work'
 * S: '/var/tmp/portage/media-libs/vulkan-loader-9999/work/vulkan-loader-9999'

```

**Comment by FireBurn** [comment]
How would you feel about using the v1.3.204 tarball in an r1 build? At least until Kronos gets a working version out

**Comment by mattst88** [comment]
1.3.211 is in ::gentoo now.

**Comment by FireBurn** [comment]
Thanks Matt

**Pull request closed without merging**
