### PR TITLE
app-admin/lastpass: bump to 4.1.2, drop firefox, add opera flag #571280 #525908

### PR DESCRIPTION
**Pull request by gktrk**
Beginning with lastpass-4, the Firefox add-on is self-contained and can be
installed from inside the browser. Therefore, drop the firefox USE flag.

Since Opera is based on the Chrome/Chromium engine now, add a USE flag
to enable support for Opera.

Do not install libnplastpass[64].so files anymore. NPAPI support is
dropped from Chrome/Chromium a while ago and Firefox was the only
consumer of these files.

Also, bump the ebuild to eapi 6.

Gentoo-Bug: https://bugs.gentoo.org/571280
Gentoo-Bug: https://bugs.gentoo.org/525908

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by gktrk** [comment]
please do not merge this. there is a discussion going on in https://bugs.gentoo.org/show_bug.cgi?id=571280.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
gokturk it is not clear if this is ready for submission.  Does robbat2 even use github ? The last entry in the bug ends in a question

**Comment by gktrk** [comment]
it is not ready for merge. I talked to robbat on #gentoo-dev and we have a different plan for this. robbat will cherry-pick, so @proxy-maint doesn't have to worry about merging this.

**Comment by idella** [comment]
ok thnks

**Pull request closed without merging**
