### PR TITLE
app-emulation/xen: bump to 4.10.2 / drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
4.10.2 tested on (~)amd64.

### CODE REVIEW

**Comment by hydrapolic** [comment]
@dlan17

**Comment by Whissi** [comment]
Can you please rebase with SOB (GCO sign-off)?

**Comment by hydrapolic** [comment]
@Whissi, all commits contain the signed-off line. I forgot to include it in the first push, but the no-signoff seems to be sticky.

**Comment by Whissi** [comment]
You are right, I didn't check all commits. Incoming push.

**Comment by hydrapolic** [comment]
Thanks @Whissi

**Pull request closed without merging**
