### PR TITLE
app-admin/filebeat-bin: new ebuild

### PR DESCRIPTION
**Pull request by hydrapolic**
https://bugs.gentoo.org/show_bug.cgi?id=567698

Upstream replaces app-admin/logstash-forwarder with this.

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint  ?

**Comment by hydrapolic** [comment]
Yes, I would wish to proxy maintain this package.

**Comment by idella** [comment]
merged

**Comment by hydrapolic** [comment]
Thanks @idella

**Pull request merged**
