### PR TITLE
dev-libs/libsecp256k1: cleanups, new proxied maintainer, disable USE="asm" by default except on amd64

### PR DESCRIPTION
**Pull request by whitslack**
@thesamesam As requested.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --git-remote whitslack --commits whitslack/master --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please consider adopting bitcoin* as well. Thanks!

**Comment by whitslack** [comment]
> Please consider adopting bitcoin* as well. Thanks!

All of the bitcoin packages other than `net-p2p/bitcoin-core` are obsolete (and likely even hazardous at this point) and should be tree-cleaned. But I don't want to be the one to do it since I got reverted when I did that in Bitcoin overlay.

**Comment by whitslack** [comment]
I'm already the (sole) proxy maintainer of `net-p2p/bitcoin-core`. :slightly_smiling_face:

**Comment by thesamesam** [comment]
Oh! Sorry. Not sure why I got confused..

**Pull request closed without merging**
