### PR TITLE
profiles/thirdpartymirrors: adjust mplayer mirror group

### PR DESCRIPTION
**Pull request by benkohler**
This change adjusts the mplayer group in profiles/thirdpartymirrors to match the current upstream list at http://mplayerhq.hu .  I've removed 3 servers and added 4.  I removed the ftp.fu-berlin.de mirror because it's not listed upstream and there's another german FTP mirror on the official list.

Before:
Testing "mplayer" mirror group...
good: http://www1.mplayerhq.hu/MPlayer
good: http://www2.mplayerhq.hu/MPlayer
bad:  http://www3.mplayerhq.hu/MPlayer
bad:  http://www4.mplayerhq.hu/MPlayer
good: http://www5.mplayerhq.hu/MPlayer
good: http://www7.mplayerhq.hu/MPlayer
good: http://www8.mplayerhq.hu/MPlayer
good: ftp://ftp.fu-berlin.de/unix/X11/multimedia/MPlayer

After:
Testing "mplayer" mirror group...
good: http://www1.mplayerhq.hu/MPlayer
good: http://www2.mplayerhq.hu/MPlayer
good: http://www5.mplayerhq.hu/MPlayer
good: http://www7.mplayerhq.hu/MPlayer
good: http://www8.mplayerhq.hu/MPlayer
good: ftp://ftp1.mplayerhq.hu/MPlayer/
good: ftp://ftp6.mplayerhq.hu/MPlayer/
good: ftp://ftp7.mplayerhq.hu/MPlayer/
good: ftp://ftp8.mplayerhq.hu/MPlayer/

### CODE REVIEW

**Comment by benkohler** [comment]
Gentoo bug #563712 https://bugs.gentoo.org/show_bug.cgi?id=563712

**Comment by hasufell** [comment]
The commit message needs a bit of work. Bug report and description should be inside the commit message and the summary shorter. E.g.

```
profiles: fix mplayer mirrors

This change adjusts the mplayer group in profiles/thirdpartymirrors
to match the current upstream list at http://mplayerhq.hu. I removed
the ftp.fu-berlin.de mirror because it's not listed upstream and
there's another german FTP mirror on the official list.

Gentoo-Bug: 563712
```

**Comment by benkohler** [comment]
I will work on that soon, thanks for the guidance

**Comment by mgorny** [comment]
You may also want to consider PGP-signing your commits. https://wiki.gentoo.org/wiki/Project:Gentoo-keys/Generating_GLEP_63_based_OpenPGP_keys as the reference point for random related docs.

**Comment by aballier** [comment]
@mgorny : commit looks fine, but what about pgp signing ? is it mandatory for merging it ?

**Comment by mgorny** [comment]
No, it's not. Feel free to merge as-is.

**Pull request merged**
