### PR TITLE
app-editors/{vscode,vscodium}:  small dependency fixes

### PR DESCRIPTION
**Pull request by AdelKS**
Hello @arthurzam 

I couldn't find any hard evidence that vscode (or eletron), dependent on either ibus or fcitx (other than in that snap package maker code). So here I am going [EDIT] for not explicitly depending on either [/EDIT]

Adel

### CODE REVIEW

**Comment by naota** [comment]
Copy-pasting from my bugzilla comment: https://bugs.gentoo.org/915380#c2

The ibus dependency for the snap package is added by this commit:

https://github.com/microsoft/vscode/commit/b2a1932329332814312f9f1623fa34ceb53da48d

The line below in the modified file, suggests vscode at least supports both ibus and fcitx.

https://github.com/microsoft/vscode/blob/main/resources/linux/snap/electron-launch#L248

Also, that dependency is imposed by arbitalily setting GTK_IM_MODULE_FILE in "resources/linux/snap/electron-launch", which should be a file for executing vscode within a snap environment. So, that is a dependency for the snap package, but, I believe, is not a dependency for vscode itself.

**Comment by AdelKS** [comment]
Copy pasting too: Thanks for your feedback @naota !  You suggest removing the explicit on `ibus` and `fcitx5` altogether ?

**Comment by naota** [comment]
I'd suggest removing both altogether.

From this dpkg output, I can't see anything related to ibus or fcitx, so they are not a dependency for vscode itself.
https://github.com/gentoo/gentoo/pull/33221#issue-1930940668

In the end, people only using ASCII had no problem using vscode without input methods like ibus or fcitx... No?

**Comment by AdelKS** [comment]
@arthurzam should be good now.

**Review by juippis — COMMENTED** [review]
I'm getting:
```
 * QA Notice: Unresolved soname dependencies:
 * 
 * 	/opt/vscodium/codium: libcups.so.2
 * 
```
cups seems to be hardlinked in this binary. Weirdly it doesn't seem tobe an issue with vscode.

Both vscodium and vscode depend on dbus too, could you add the dbus dep while at it? 

removing ibus seems correct though.

**Comment by AdelKS** [comment]
> cups seems to be hardlinked in this binary. Weirdly it doesn't seem tobe an issue with vscode.

I guess we keep it until they remove it upstream: https://github.com/VSCodium/vscodium/issues/1680

I added dbus

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
