### PR TITLE
www-client/firefox-bin: version bump, remove obsolete

### PR DESCRIPTION
**Pull request by Vindex17**
Simple version bump to bug-fix releases, to solve crashes and vulnerabilities

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for your work. Is there a bug number associated with this PR?

**Comment by monsieurp** [comment]
@axs-gentoo @ZeroChaos- please have a look, thanks.

**Comment by Vindex17** [comment]
No bugs for this PR

**Comment by axs-gentoo** [comment]
The actions taken in this commit have already been done in the base git repo.

**Pull request closed without merging**
