### PR TITLE
sys-libs/libseccomp: rebase experimental-loong patches

### PR DESCRIPTION
**Pull request by matoro**
The fix backported in d58730757b79ce429d5fbe8f35dede6074d4c243 was already in the loong tree which makes the patch fail to apply.  Rebase this and also now rather than having a huge patch that doesn't correspond to VCS with a bunch of checked-in autotools stuff, use the github diff and eautoreconf for 9999 and loong.

Fixes: d58730757b79 ("sys-libs/libseccomp: backport fix for arch-syscall-check")
Bug: https://bugs.gentoo.org/926648

### CODE REVIEW

**Comment by matoro** [comment]
CC @xen0n

**Comment by floppym** [comment]
This adds an unconditional dependency on autoconf/automake/libtool, but that dependency is only needed for loong.

**Comment by matoro** [comment]
> This adds an unconditional dependency on autoconf/automake/libtool, but that dependency is only needed for loong.

There isn't any way to conditionally inherit an eclass is there?  Maybe I could check `ARCH` environment variable?

**Comment by floppym** [comment]
You can do this:
```
AUTOTOOLS_AUTO_DEPEND=no
...
inherit autotools
...
BDEPEND="experimental-loong? ( ${AUTOTOOLS_DEPEND} )"
```

**Comment by matoro** [comment]
> You can do this:
> 
> ```
> AUTOTOOLS_AUTO_DEPEND=no
> ...
> inherit autotools
> ...
> BDEPEND="experimental-loong? ( ${AUTOTOOLS_DEPEND} )"
> ```

Done, I also made it work with `-9999` in the event this needs to get carried over later (it's all upstream for now).

**Comment by xen0n** [comment]
Merged with commit a65ce7b0b71668fb49b960d7259b36eba6ab34cc, thanks!

**Pull request closed without merging**
