### PR TITLE
sci-libs/opencascade: bump to version 7.4.0

### PR DESCRIPTION
**Pull request by waebbl**
Closes: https://bugs.gentoo.org/696596
Package-Manager: Portage-2.3.76, Repoman-2.3.17
Signed-off-by: Bernd Waibel <waebbl@gmail.com>

### CODE REVIEW

**Comment by waebbl** [comment]
Fixed QA issue from CI report and cleaned up comments.
Removed and restricted `USE=test`. Tests can not easily be run, but instead need a proper set-up rather big environment to be able to run.

**Comment by juippis** [comment]
More QA issues, 
```

 * Messages for package sci-libs/opencascade-7.4.0:

 * One or more CMake variables were not used by the project:
 *   USE_GL2PS
 * QA Notice: Pre-stripped files found:
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIVtkDraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKQADraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTObjDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDEDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKDCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXSDRAW.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKViewerTest.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTopTest.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKDraw.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKRWMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKVRML.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDESTEP.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXDEIGES.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIGES.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEP.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEP209.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEPAttr.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKSTEPBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXSBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKVCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTObj.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKStd.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKStdL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXml.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBin.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXmlL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBinL.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKLCAF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKCDF.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKIVtk.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMeshVS.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKOpenGl.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKV3d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKService.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKXMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMesh.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKFeat.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKOffset.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKFillet.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKHLR.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBool.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKShHealing.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBO.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKPrim.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKTopAlgo.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKGeomAlgo.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKBRep.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKGeomBase.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKG3d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKG2d.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKMath.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/lib64/libTKernel.so.7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/Tutorial-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/IESample-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/FuncDemo-7.4.0
 * /usr/lib64/opencascade-7.4.0/ros/bin/DRAWEXE-7.4.0
```
https://wiki.gentoo.org/wiki/Package_testing#make.conf

It's a monstrous package, so really good job so far :)
Fix at least the unnecessary configure option, then make a fix for pre-stripped either now or for the next version, whichevers suits you better.

**Comment by waebbl** [comment]
I have those noted too. For the last version, I could solve the issue by adding `set(CMAKE_INSTALL_DO_STRIP OFF)` to CMakeLists.txt. But this doesn't work anymore with the cmake version I've installed (3.14.6).
Also there were some installation issue, related to the cmake files and slotting. I'm working on fixing these and the issues above and prepare another push.

**Comment by waebbl** [comment]
Removed the GL2PS warning and cleaned up installation of cmake files with respect to slotting.
About slotting, I was thinking if I should change sub-slotting, making the version like `7/7.4.0`. I'm not sure, how meaningful it is to be able to have 2 different minor versions installed. I think this would make more sense with respect to major versions.

**Pull request closed without merging**
