### PR TITLE
dev-python/{cssutils,pypeg2}, www-client/qutebrowser: python 3.6 support

### PR DESCRIPTION
**Pull request by Hummer12007**
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=612502

### CODE REVIEW

**Comment by mgorny** [comment]
Did you test those packages with FEATURES=test? Please look at the impl testing guide: https://wiki.gentoo.org/wiki/Project:Python/Adding_and_Removing_Python_implementations

**Comment by Hummer12007** [comment]
Tests work for me (except, a dependency on dev-python/nose was missing in cssutils).

**Comment by mgorny** [comment]
Ok, thanks. The revbump for test dep is unnecessary since it affects build-time deps only. I'll collapse it when merging it.

**Comment by mgorny** [comment]
One more note: please remember to update year in the copyright header when you touch ebuilds, and to run `repoman full` for every change.

**Pull request closed without merging**
