### PR TITLE
dev-java/icu4j: add 75.1

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Review by fordfrog — COMMENTED** [review]
it's true that it better matches remote-id and src uri, but on the other hand, nobody calls it velocity-engine afaics: https://repology.org/project/velocity/versions

**Review by fordfrog — APPROVED** [review]
i just re-added `>=dev-java/ant-1.10.14:0[junit]` to the deps as iirc we should not be so eager to remove versions from deps even if we don't have any older version anymore.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by vaukai** [comment]
> is this supposed to be merged or is just a preparation step?

better not merge, leave it open for the release.
it is mainly for testing qa and to remind us the gson slot move.

**Comment by fordfrog** [comment]
> > is this supposed to be merged or is just a preparation step?
> 
> better not merge, leave it open for the release. it is mainly for testing qa and to remind us the gson slot move.

so i guess you can switch it to draft now as i merged the other commits.

**Pull request closed without merging**
