### PR TITLE
media-gfx/openscad: version bump to 2015.03_p2 & bugfix

### PR DESCRIPTION
**Pull request by tomboy-64**
- bump to patchlevel 2
- fix segfault when using with qt{opengl,gui}:4[egl] -> enforce USE=-egl
- update dependency list
- port to EAPI 6

Package-Manager: portage-2.2.28
RepoMan-Options: --ignore-arches

### CODE REVIEW

**Comment by monsieurp** [comment]
I don't know how to reach out to mattm.

**Comment by tomboy-64** [comment]
I filed a [Bugreport](https://bugs.gentoo.org/show_bug.cgi?id=577732) - once it gets assigned to him, I hope he receives a mail about it.

**Comment by idella** [comment]
That is ridiculous.  Developers should not be impossible to find. The perennial email.

**Comment by monsieurp** [comment]
I don't want to spoil the fun but...
> [12:01:43] [ @monsieurp ] !seen mattm
> [12:01:43] [ +willikins ] monsieurp: MattM was last seen 1 year, 1 month, 22 days, 16 hours, 54 minutes and 22 seconds ago, quitting IRC (Remote host closed the connection)

Let's proceed and have a developer with qmake expertise sign off on your changes, shall we? @kensington can you volunteer?

**Comment by kensington** [comment]
There's qt4/qt5 USE flags introduced but it seems only qt4 is used?

**Comment by tomboy-64** [comment]
An oversight on my part. I attempted to introduce optional support for qt5.

The package actually builds fine against qt5 - but it would require qscintilla to get slotted. Which is [not gonna happen](https://bugs.gentoo.org/show_bug.cgi?id=541604).

I've removed it.

**Comment by kensington** [comment]
Thanks a lot! Picked as 0d2b3ad098e2b733b572eb6d5105aada9bf61db1.

**Pull request closed without merging**
