### PR TITLE
www-client/seamonkey-2.53.17.1-r1: x86 build fix and ffmpeg-6 support

### PR DESCRIPTION
**Pull request by BioMike**
This fixes the build on x86 for 2.53.17.1 with an x86 specific patch. Support for >=media-video/ffmpeg-6 is included.

Closes: https://bugs.gentoo.org/915336
Closes: https://bugs.gentoo.org/917593

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
This is now hitting the system-icu issue with icu-74.1 installed. Should I use.mask system-icu for seamonkey, or can you find a patch? Firefox and Thunderbird has been patched conditionally to workaround it, see their ebuilds and patchsets.

**Comment by BioMike** [comment]
I think I can reuse the FF/TB patch, but have no ways to test it quickly.

**Comment by BioMike** [comment]
The patch is included in a new patches tarball. I kept the name the same, so you have to delete the old tarball before testing.

**Review by juippis — APPROVED** [review]
Thanks!

EDIT: can't push, some hiccup on our infra. Will retry in the morning.

**Comment by stefson** [comment]
has the icu-74.1 bug been reported upstream yet?

**Comment by BioMike** [comment]
Yes, upstream seems to be aware of this: https://bugzilla.mozilla.org/show_bug.cgi?id=1864745 .

**Comment by stefson** [comment]
Well, that is not the same bug. It's about a link failure against <system-icu-74 in 2.53.18b1 and not about the well known compile error of stable seamonkey against icu-74.1

**Pull request closed without merging**
