### PR TITLE
dev-libs/xerces-c: restore patch to fix install location

### PR DESCRIPTION
**Pull request by littlewu2508**
Closes: https://bugs.gentoo.org/913045

### CODE REVIEW

**Comment by heroxbd** [comment]
xerces-c-3.2.4.ebuild is stabilized.   You cannot do a revision bump while keeping the stable status.

Because xerces-c-3.2.4.ebuild is the only stabilized one, you need to keep it while bumping the revision.

See: https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html

**Comment by thesamesam** [comment]
Thanks, I've fixed it with `git mv` given it's clearly broken.

Also added some more info in b03595edbc4e8b9ddc6588d05ce190cbd82067e0 to hopefully avoid it being dropped in future. Apologies for the error.

**Comment by heroxbd** [comment]
Thanks Sam!

**Comment by littlewu2508** [comment]
> xerces-c-3.2.4.ebuild is stabilized. You cannot do a revision bump while keeping the stable status.
> 
> Because xerces-c-3.2.4.ebuild is the only stabilized one, you need to keep it while bumping the revision.
> 
> See: https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html

Thank you for the reminder! I will read the dev manual more carefully. And thanks to Sam for adding more info!.

**Pull request closed without merging**
