### PR TITLE
dev-util/mingw64-toolchain + dxvk + vkd3d-proton new packages

### PR DESCRIPTION
**Pull request by ionenwks**
Tossing this here first for a bit if anyone has suggestions or spot anything off.

mingw64-toolchain support in wine's ebuilds can be handled after it's merged/tested (all it needs is BDEPEND on `dev-util/mingw64-toolchain[${MULTILIB_USEDEP}]` + `PATH=${BROOT}/usr/lib/mingw64-toolchain:${PATH}` and it'll build -- albeit ebuild does has_version cross-* then die atm, in dxvk's ebuild I still allow crossdev through USE=crossdev-mingw).

(still doing some testing, likely not final -- ~haven't tried x86 yet too~)

Edit (changelog):
 - fixed logic for ~x86
 - check g++ rather than gcc in dxvk's crossdev-mingw, error is cryptic if cross has USE=-cxx, also check posix threads on both compilers if multilib (but really, just use mingw64-toolchain instead :eyes:)
 - renamed dlltool patch, name was misleading
 - added mingw's idl compiler (widl), so that packages that use it (e.g. vkd3d-proton), don't need to depend on wine to build
- changed i686 wrappers to use full paths
- no longer install dxvk tests
- did some re-arrangement to mingw64-runtime, and now building native tools + gets widl as well
- added vkd3d-proton :eyes:
- add missing die for vkd3d-proton widl check
- build in source dir for mingw64-runtime tools like the rest, simplifies (only headers need out of source)
- unset toolchain vars for mingw64-runtime when cross-compiling like other ebuilds (e.g. CC=clang will build tools with clang, then switch to mingw-gcc rather than just fail)

(and seems ready now, have another thing planned but that will take a while, so let's merge this to get some testing in)

### CODE REVIEW

**Comment by stefson** [comment]
so this is kind of an umbrella ebuild to replace the whole of crossdev mingw setup? 

in any case, do you care to add the patch to all affected versions of dev-util/mingw64-runtime as well?

**Comment by ionenwks** [comment]
> so this is kind of an umbrella ebuild to replace the whole of crossdev mingw setup?

yes

> in any case, do you care to add the patch to all affected versions of dev-util/mingw64-runtime as well?

mingw64-runtime is not affected given it never enables lib32 and lib64 at same time

**Comment by stefson** [comment]
I see, you have full multilib support implemented - that would be helpfull to not juggle with two different toolchains at the same time if wine multilib is desired.  

Maybe you can avoid the patch if you update to binutils-2.38-r2, which has the fix for the dlltool breakage?

**Comment by ionenwks** [comment]
Primary intend is to simplify this for users, not for the ebuild. I personally think ebuilds should support both ways to build for users that are happy with their crossdev setups and default to mingw64-toolchain given that will be more reliable (not that I plan to keep my crossdev mingw around, so I have no strong feelings there).

The patch is unrelated to binutils, and only mingw64-runtime-10.0.0 is affected (build system picks temporary files to use with dlltool but they clash when building with --enable-lib32 and lib64 at same time), it'll be gone next version given it's a backport.

**Pull request closed without merging**
