### PR TITLE
kde-apps/libkcompactdisc: Fix build without alsa

### PR DESCRIPTION
**Pull request by a17r**
@gentoo/kde 

(patch already upstreamed)

### CODE REVIEW

**Comment by johu** [comment]
You are adding a stable revision to the tree...How about to finish your quizzez?

**Comment by a17r** [comment]
Yes, I hoped to get away with it ;) Patch is a build fix, the bump makes sure everyone gets the libkcompactdisc they wanted (USE=-alsa has been dysfunctional until now).

**Comment by johu** [comment]
It is not allowed for such rare case fix. If you would have done your quizzez you would know that...That was the remark to the quizzez

**Comment by kensington** [comment]
Thanks, picked as 6742b0a334a7f354c390e7e454cfb81c1a8160e2...70cebe39217306e64304bd5455a8f04cd6016835.

**Pull request closed without merging**
