### PR TITLE
mail-filter/maildrop: fix conflict with netqmail

### PR DESCRIPTION
**Pull request by jendis**
Remove files conflicting with netqmail:
 * /usr/share/man/man5/maildir.5.bz2
 * /usr/share/man/man1/maildirwatch.1.bz2
 * /usr/share/man/man1/maildirmake.1.bz2

### CODE REVIEW

**Comment by orbea** [comment]
> Remove files conflicting with netqmail:

Are these files different from what netqmail installs? Would it be better to rename them instead of removing them?

**Comment by jendis** [comment]
these files are identical to those originating from `netqmail`.
There can arise a hypothetical situation where `netqmail` changes these files, but I'm sure that this is not going to happen for at least the lifetime of this `maildrop` version (and probably many others).
Anyway I haven't proposed the removal of the `maildirwatch` and `maildirmake` binaries because I haven't noticed that the `metadata.xml` explicitly mentions that `tools` installs these. So probably the right thing should also be the removal of these binaries when the `tools` use flag is disabled.
So I finally think that rename solution conflicts with the purpose of the `tools` use flag (and honestly I have no idea to what name should be renamed).

**Comment by jendis** [comment]
I've finally decided to propose removal of the `maildirwatch` and `maildirmake`

**Comment by orbea** [comment]
> So I finally think that rename solution conflicts with the purpose of the `tools` use flag (and honestly I have no idea to what name should be renamed).

Hypothetically you could just append `-maildrop` at the end of the name, but your reasoning seems sound. Thanks for explaining.

**Pull request closed without merging**
