### PR TITLE
Adopt Lpeg, add LuaJIT support.

### PR DESCRIPTION
**Pull request by lluixhi**

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Hi and thanks for the PR! Could you please rebase against master? Your patch doesn't apply cleanly. The metadata.xml file changed between the moment you altered it and now.

**Comment by lluixhi** [comment]
@monsieurp Yeah, no problem. Looks like I submitted the pull request just before the package became part of the getoo vim project.

**Comment by monsieurp** [comment]
Yes it's fine. I'm merging it. Thanks!

**Pull request closed without merging**
