### PR TITLE
net-im/telegram-desktop: Bump to 4.0.2

### PR DESCRIPTION
**Pull request by mid-kid**
Turns out they never really dropped Qt5 support, only for some wayland
integrations. I've tried to research what this means but I actually have
no idea beyond some mentions of "xdg-shell".

This is why I warn about it in the postinst, even if it may not be
meaningful...

Debian ships the package the same way.

@gyakovlev

### CODE REVIEW

**Comment by gyakovlev** [comment]
sorry for delay, on it.
need to check with qt team on qt6 flag first but I see no problem personally as long as it's masked.
some activity is going on in https://github.com/gentoo/gentoo/pull/25635 still

**Comment by gyakovlev** [comment]
we have to hold off until the qt6 pr is merged, that's going to happen soon (probably 1-2 days).

**Comment by gyakovlev** [comment]
ok this PR was last motivation needed to get https://github.com/gentoo/gentoo/pull/25635 merged.

**Comment by gyakovlev** [comment]
https://archives.gentoo.org/gentoo-dev/message/2219ad7b15b0731a91a23f644b43ec06

I separated mask commit and changed text a bit, hope you don't mind.
generally mask commits should be separate and ordered before masked package.
so you mask first, add package affected by mask second. that prevents funny things with webrsync. rare, but happens.


tested, works fine for me on ppc64 with qt5, qt6 is untested by me yet. I still need to port qtwqebengine and couple of minor things to ppc64 before I can start testing it.

**Comment by gyakovlev** [comment]
we actually went with global `qt6` useflag mask.
https://github.com/gentoo/gentoo/commit/745af70a74cc378fb2f8dd3b561169d75d0b50b3

**Comment by mid-kid** [comment]
Thanks a lot for merging it! Glad qt6 is finally on-track :)

**Pull request closed without merging**
