### PR TITLE
*/*: speed up cargo SRC_URI generation

### PR DESCRIPTION
**Pull request by antecrescent**
```sh
git grep -rlE '^inherit .*cargo' | grep '.ebuild$' |\
xargs pkgcheck scan -k SuboptimalCratesSeparator,SuboptimalCratesURICall \
-R FormatReporter --format '{category}/{package}/{package}-{version}.ebuild' |\
xargs sed -i -e 's/\$(cargo_crate_uris\( \${CRATES}\)\?)/\${CARGO_CRATE_URIS}/' \
-e 's/^\([[:space:]]*\|CRATES="\)\([a-zA-Z0-9_-]\+\)-\([0-9]\+\.[0-9]\+\.[0-9]\+.*\)/\1\2@\3/'
```

The second sed pattern breaks down into
(optional leading white space OR `CRATES="`)(crate validation regex [from cargo.eclass](https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/cargo.eclass#n178))

Using this script, I changed
* crates `foo-1.2.3` to `foo@1.2.3`
* `$(cargo_crate_uris)` and `$(cargo_crate_uris ${CRATES})` to `${CARGO_CRATE_URIS}`

`dev-util/cargo-c-0.9.14` is a false positive for `SuboptimalCratesSeparator` due to an empty `${MY_P}` in `CRATES`.

---
Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by mgorny** [comment]
Thanks for doing this!

**Comment by antecrescent** [comment]
I am currently compiling the affected packages to verify that I didn't break anything. Once that's done, I'll mark it as ready for review :)

**Comment by mgorny** [comment]
I'm sorry to say but this really isn't feasible as all-in-one commit, because the individual packages are outdated already and it's a mess to update. Please rebase, split it to one commit per package, I'll merge then these that are up-to-date and reiterate over the rest.

**Comment by antecrescent** [comment]
Sorry for the inactivity, I just rebased and split the changes into per-package commits as requested. I'm still interested in getting this merged eventually and I'll try helping with updating outdated/broken packages.

**Pull request closed without merging**
