### PR TITLE
dev-php/pecl-xdiff: version bump 2.0.1

### PR DESCRIPTION
**Pull request by anthonyryan1**
* EAPI=6
* Bump php-ext-pecl
* Remove php5-4 from older version

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by orlitzky** [comment]
Thanks! Can you please remove `php5-5` as well? We're going to remove it from the tree "any day now." And in the new version, these two variables
```bash
PHP_EXT_INI="yes"
PHP_EXT_ZENDEXT="no"
```
have the default values and can be dropped.

**Comment by anthonyryan1** [comment]
Corrected, now removing PHP 5.5 as well, and removed default values being re-stated.

**Comment by orlitzky** [comment]
Sorry, I missed one other thing the first time around. The `USE_PHP` variable gets translated into dependencies by the eclass, and dependency changes require a new revision (-r4). Can you rename `pecl-xdiff-1.5.2-r3.ebuild` to `pecl-xdiff-1.5.2-r4.ebuild`, too?

**Comment by anthonyryan1** [comment]
Corrected, I knew that would be required for an RDEPEND addition, but hadn't realized a bump would be necessary when removing.

**Comment by anthonyryan1** [comment]
Since this needed a revbump anyway, I've amended things again, bumping the older ebuild to EAPI 6 as well.

**Comment by orlitzky** [comment]
Thanks, I just pulled it. Dependency removals can cause problems for the same reasons as additions can. For example, if someone installed an old versions of pecl-xdiff that had `php5-5` in `USE_PHP`, their package manager would record the fact that it depended on `php:5.5`. If we remove `php:5.5` from the tree before they install your new revision, it could cause the package manager to get confused: the user has something installed that depends on `php:5.5`, but there is no `php:5.5` in the tree.

There are various unreliable hacks intended to sweep that under the rug, but it's better to play it safe.

**Pull request closed without merging**
