### PR TITLE
app-text/tree: add 2.1.3

### PR DESCRIPTION
**Pull request by emanuele6**
Copied from tree-2.1.1-r1.ebuild, and fixed VariableOrderWrong warning.
("S" should occur before "KEYWORDS", "SLOT")

https://gitlab.com/OldManProgrammer/unix-tree/-/tags/2.1.3

Signed-off-by: Emanuele Torre <torreemanuele6@gmail.com>

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Flowdalic** [comment]
The CI report could be from a time where the checks where non-deterministic (I remember something about that being discussed in #gentoo-dev)

> EclassExportFuncsBeforeInherit	guile: EXPORT_FUNCTIONS (line 356) called before inherit (line 96)

@emanuele6 could you add `[please reassign]` to the PR title to trigger a re-run of the CI? Maybe this time its green

**Comment by emanuele6** [comment]
I rebased the commit on master and force pushed to make the CI re-run.

**Comment by jonasstein** [comment]
Thank you for the PR. When you run 
`pkgcheck scan --net`
in the ebuild folder, you can see that the HOMEPAGE is 404. 
It makes sense to fix that at once for all .ebuilds, so we do not have too many commits for trivial changes. 
You can try it, if you want. I can look into this next weekend again.

**Comment by emanuele6** [comment]
I didn't fix the older packages because I wanted to avoid touching stable ebuilds, but I can fix them as well since you want that.

I think the page was still working when I sent the PR: I remember checking it; but the README of tree does say

>   Old site for as long as it lasts:
>  http://mama.indstate.edu/users/ice/tree/
>  ftp://mama.indstate.edu/linux/tree/

So it was probably bound to disappear eventually and now it did; I will remove mentions of it from the old ebuilds too

**Pull request closed without merging**
