### PR TITLE
sys-libs/uclibc removal

### PR DESCRIPTION
**Pull request by Whissi**
Testing removal of sys-libs/uclibc in favor of sys-libs/uclibc-ng wrt bug https://bugs.gentoo.org/show_bug.cgi?id=622456

### CODE REVIEW

**Comment by blueness** [comment]
is this just a test because we need to proceed by masking and sending out a news item.

**Comment by Whissi** [comment]
Right, this was just a test. Now we know that we can just start the normal last rite process... nothing depends on it.

**Comment by mgorny** [comment]
Note that CI doesn't check dev/exp profiles, so it won't help you here. You can try making the uclibc profiles stable if you want to test them (in the PR) but expect a lot of irrelevant failures you're going to have to process manually.

**Comment by monsieurp** [comment]
@Whissi: what's the deal here? why is this PR still open? I'm going to close it. Feel free to reopen it if you need to make further changes.

**Pull request closed without merging**
