### PR TITLE
net-misc/libres3: new ebuild

### PR DESCRIPTION
**Pull request by tomboy-64**
@aballier finally.

### CODE REVIEW

**Comment by tomboy-64** [comment]
```
>>> Test phase: net-misc/libres3-1.1
W: Tests are turned off, consider enabling with 'ocaml setup.ml -configure --enable-tests'
>>> Completed testing net-misc/libres3-1.1
```

Not really sure what to do about this?
This happens when I run `FEATURES=test emerge libres3`.

**Comment by aballier** [comment]
```
W: Tests are turned off, consider enabling with 'ocaml setup.ml -configure --enable-tests'
```
means you need to set `OASIS_BUILD_TESTS=1` before inherit :)

**Comment by tomboy-64** [comment]
Today I got the heads up that it might take a while for ocamlnet-4 support to be completed. Hence I decided to revert to the old "ugly" dependency on <ocamlnet-4.
It builds fine and tests complete as well. Upon completion of ocamlnet-4 support I'll push a revbump.

**Comment by aballier** [comment]
ok; please keep it mind that this implies I don't include it in my ocaml checks when I bump some of its deps since I need to use latest versions

**Comment by tomboy-64** [comment]
Of course. I am maintainer and I get to keep the pieces when **** breaks ;)

**Comment by aballier** [comment]
ok, so I get some files mis-placed:

```
>>> /usr/share/doc/libres3-1.1/html/COPYING
```

shouldn't be installed

```
>>> /usr/share/doc/libres3-1.1/html/manual.pdf
```

shouldnt be in html subdir

```
>>> /usr/share/doc/libres3-1.1/html/logrotate.d/
>>> /usr/share/doc/libres3-1.1/html/logrotate.d/libres3
```

should be `/etc/logrotate.d/`

```
>>> /usr/share/doc/libres3-1.1/html/README
```

shouldn't be in html subdir

```
>>> /usr/share/doc/libres3-1.1/html/s3genlink.py
```

no clue, but it's not html either :)

```
>>> /usr/etc/libres3/libres3-insecure.sample.s3cfg
>>> /usr/etc/libres3/mime.types
>>> /usr/etc/libres3/libres3.sample.s3cfg
```
should probably be '/etc/libres3'

```
>>> /usr/var/log/libres3/
>>> /usr/var/log/libres3/info.log
```

should probably be `/var/log/libres3/info.log`

**Comment by idella** [comment]
@aballier is this one for you too?

**Comment by mgorny** [comment]
@idella, yes, he does ocaml stuff here.

**Comment by idella** [comment]
Yes, he told me. k

**Comment by tomboy-64** [comment]
Thanks for updating oasis.eclass. Had that in the pipeline myself, but got sidetracked over the weekend.

**Comment by idella** [comment]
+	<herd>ml</herd>
+	<herd>proxy-maintainers</herd>
+	<maintainer>
+		<email>tomboy64@sina.cn</email>
+	</maintainer>

the project (or herd) not notified ???

**Comment by idella** [comment]
Hmm I'm actually in doubt over this.  This package is not a core ocaml package, I initially presumed aballier ought cover it but otherwise it should be managed by proxy-maintainers

**Comment by tomboy-64** [comment]
@idella: Are you referring to the ml-herd assignment in metadata.xml? This was added per request from aballier. My initial version didn't contain it.
If you're not, please clarify :)

**Comment by idella** [comment]
right. aballier and I agreed that the submissions via these pull reqs be committed by him. The presence if the proxy-maintainers herd introduces dual authority devs of the package. Actually it doesn't even do that. HE asked you to add it with proxy-maintainers, however he himself isn't added as a dev status maintainer. By protocol that means that only members of the proxy-maint team are auth'd to commit it, (plus the Owners here) clashing with our personal agreement. A package dealing with ocaml itself I readily step back from. This package is merely a lib, therefore it appears quite pertinent as one for me to commit. As user this is not your concern. I want a clear ruling as to whether this is a package that comes under the ocaml banner, or not. If not, then i expect to be left to commit the final patch once reviewed to a fit state here.

**Comment by mgorny** [comment]
@idella, I don't know what protocol you refer to. By protocol, authority goes top-to-bottom, and `<herd>ml</herd>` comes before proxy-maintainers, which means you're only backup.

**Comment by aballier** [comment]
@idella the idea here is that ocaml stuff being quite specific and often very fragile is better to have ml herd; there is no such rule that any ocaml package must have ml herd, but from my experience, when it's not the case, package will bitrot and break for long times when its underlying libraries change... A recent example of this is https://bugs.gentoo.org/show_bug.cgi?id=559624
Moreover, if someone wants to maintain ocaml stuff, that someone could make everyone save time by joining ml herd and learning the specifics rather than trying to invent protocols to gain pseudo-authority on who is to commit what...

the point of having proxy-maints here is that ml herd is a single person and blocking non-dev contributions because that someone went to vacations is not nice

**Comment by idella** [comment]
@aballier I was merely checking. That was what I thought in from our first 'discussion'. One is allowed to check and clarify. I saw that this might not be " ocaml stuff". Since it is, the place to commit is for you, never a problem/

**Comment by tomboy-64** [comment]
@aballier sorry for the delay; apparently i forgot to post a comment after my latest commit.

**Comment by aballier** [comment]
merged, thanks!

**Comment by aballier** [comment]
note:
```
RepoMan scours the neighborhood...
  ebuild.minorsyn               1
   net-misc/libres3/libres3-1.1.ebuild: Unquoted Variable on line: 56
```

there is nothing you can do about this, I should first update oasis.eclass to accept bash arrays as configure args...

**Comment by tomboy-64** [comment]
yeah, i know.

**Pull request merged**
