### PR TITLE
app-dicts/myspell-{en,fr}: closes bugs

### PR DESCRIPTION
**Pull request by scardracs**
Closes: #16938
Bug: https://bugs.gentoo.org/731704
Closes: https://bugs.gentoo.org/794991

Package-Manager: Portage-3.0.19, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by ionenwks** [comment]
Do think think other files matter? Diff of filelists contain:
```
-/usr/share/hunspell/fr_FR.aff
-/usr/share/hunspell/fr_FR.dic
-/usr/share/hyphen/hyph_fr_FR_v3.dic
+/usr/share/hunspell/fr-toutesvariantes.aff
+/usr/share/hunspell/fr-toutesvariantes.dic
+/usr/share/hyphen/hyph_fr.dic
+/usr/share/hyphen/hyph_fr.iso8859-1.dic

-/usr/share/myspell/fr_FR.aff
-/usr/share/myspell/fr_FR.dic
-/usr/share/myspell/hyph_fr_FR_v3.dic
-/usr/share/myspell/th_fr_FR_v3.dat
-/usr/share/myspell/th_fr_FR_v3.idx
-/usr/share/mythes/th_fr_FR_v3.dat
-/usr/share/mythes/th_fr_FR_v3.idx
+/usr/share/myspell/fr-toutesvariantes.aff
+/usr/share/myspell/fr-toutesvariantes.dic
+/usr/share/myspell/hyph_fr.dic
+/usr/share/myspell/hyph_fr.iso8859-1.dic
+/usr/share/myspell/thes_fr.dat
+/usr/share/myspell/thes_fr.idx
+/usr/share/mythes/thes_fr.dat
+/usr/share/mythes/thes_fr.idx
```
I don't really know these myself.

**Comment by scardracs** [comment]
> Do think think other files matter? Diff of filelists contain:
> ```
> -/usr/share/hunspell/fr_FR.aff
> -/usr/share/hunspell/fr_FR.dic
> -/usr/share/hyphen/hyph_fr_FR_v3.dic
> +/usr/share/hunspell/fr-toutesvariantes.aff
> +/usr/share/hunspell/fr-toutesvariantes.dic
> +/usr/share/hyphen/hyph_fr.dic
> +/usr/share/hyphen/hyph_fr.iso8859-1.dic
> 
> -/usr/share/myspell/fr_FR.aff
> -/usr/share/myspell/fr_FR.dic
> -/usr/share/myspell/hyph_fr_FR_v3.dic
> -/usr/share/myspell/th_fr_FR_v3.dat
> -/usr/share/myspell/th_fr_FR_v3.idx
> -/usr/share/mythes/th_fr_FR_v3.dat
> -/usr/share/mythes/th_fr_FR_v3.idx
> +/usr/share/myspell/fr-toutesvariantes.aff
> +/usr/share/myspell/fr-toutesvariantes.dic
> +/usr/share/myspell/hyph_fr.dic
> +/usr/share/myspell/hyph_fr.iso8859-1.dic
> +/usr/share/myspell/thes_fr.dat
> +/usr/share/myspell/thes_fr.idx
> +/usr/share/mythes/thes_fr.dat
> +/usr/share/mythes/thes_fr.idx
> ```
> I don't really know these myself.

I don't think other files do something useful for us. Do you think we can simply remove them?

**Comment by ionenwks** [comment]
I was mostly wondering if there's some applications that would still look for the other names with "fr_FR" in them, aka not just fr_FR.aff, also since you're moving it, raises the question of if anything will still be looking for fr-toutevariantes.aff over fr_FR.aff

But as I said, I don't know these, just concerned whether it's the right/complete fix.

**Comment by oniGino** [comment]
im a little concerned on the removal of the fr dic files here. those are usually needed

**Comment by scardracs** [comment]
> im a little concerned on the removal of the fr dic files here. those are usually needed

Hi! Is it ok for you how i set up myspell-en?

**Comment by oniGino** [comment]
> > im a little concerned on the removal of the fr dic files here. those are usually needed
> 
> Hi! Is it ok for you how i set up myspell-en?

yeah the en changes look fine, cant speak to the fr changes though

**Comment by scardracs** [comment]
> > > im a little concerned on the removal of the fr dic files here. those are usually needed
> > 
> > Hi! Is it ok for you how i set up myspell-en?
> 
> yeah the en changes look fine, cant speak to the fr changes though

I have addedy thoughts on fr version too ;)

**Comment by scardracs** [comment]
@oniGino I've requested a stabilization for 2019 version in order to drop olders. If you have any point please comment here https://bugs.gentoo.org/795096

**Review by juippis — APPROVED** [review]
I tried french language on gedit, and it works for me now.

Please remember to have meaningful summaries, 
https://www.gentoo.org/glep/glep-0066.html#commit-messages

**Comment by scardracs** [comment]
> I tried french language on gedit, and it works for me now.
> 
> Please remember to have meaningful summaries, 
> https://www.gentoo.org/glep/glep-0066.html#commit-messages

Sorry, PRs i normally opens are self-explanatory but i will take more care on it :)

**Pull request closed without merging**
