### PR TITLE
media-sound/gmusicbrowser: fix install of icons

### PR DESCRIPTION
**Pull request by bor**
due to changes in the last version (1.1.15)

### CODE REVIEW

**Comment by bor** [comment]
@mgorny got it.
The branch is updated.

**Comment by bor** [comment]
Question to sound@gentoo.org guys: Can I add myself as proxy-maint?
Have another ideas how to improve:  add some USE flags, add gst-1 support, etc

**Comment by mgorny** [comment]
@Polynomial-C seems to be the last person touching it. But I think it'd be fine since it is pretty much not touched since @hasufell left.

**Comment by mgorny** [comment]
@gentoo/proxy-maint also.

**Comment by bor** [comment]
Sorry, forgot to run 'repoman fix' after remove old version

**Comment by SoapGentoo** [comment]
@bor yes you can add yourself as proxy-maint if you're willing to take care of this package.

**Pull request closed without merging**
