### PR TITLE
net-proxy/squid: security bump to 4.8

### PR DESCRIPTION
**Pull request by hydrapolic**
Tested on ~amd64.

Thanks!

### CODE REVIEW

**Comment by Zlogene** [comment]
I have added it.

**Comment by hydrapolic** [comment]
> I have added it.

Thanks @Zlogene. Can you please remove WANT_AUTOMAKE="1.15"? It works with the latest without problems.

**Comment by Zlogene** [comment]
> > I have added it.
> 
> Thanks @Zlogene. Can you please remove WANT_AUTOMAKE="1.15"? It works with the latest without problems.

Indded it does, thanks, removed!

**Comment by hydrapolic** [comment]
Thanks @Zlogene ;)

**Pull request closed without merging**
