### PR TITLE
Add dev-lang/ispc-1.13.0 and -9999

### PR DESCRIPTION
**Pull request by Cheaterman**

### CODE REVIEW

**Comment by Cheaterman** [comment]
Associated bug report: https://bugs.gentoo.org/729924

**Comment by Cheaterman** [comment]
Feel free to not merge the -9999 ebuild and patchset, it's mostly here for demonstration purposes.

**Comment by junghans** [comment]
Merged.

**Comment by junghans** [comment]
@Cheaterman I haven't used ispc in years, do you want to become the maintainer for it?

**Comment by Cheaterman** [comment]
@junghans ispc is merely a dependency of a dependency for me, I'm using blender:28 from ::cg overlay, and its dependency media-libs/oidn has ispc as a dependency itself, so I'm really not sure that I'm qualified to become a maintainer for it... Sorry :-s

**Comment by junghans** [comment]
@Cheaterman no problem is just dropped to maintainer needed.

**Comment by Cheaterman** [comment]
On the other hand, with blender 2.8 coming to the main Portage tree, many people will depend on ispc in the future for oidn (including me), so there will be no shortage of fixes and version bumps if/when needed at that point. I just think it would be ideal if the ispc maintainer was someone who actually uses it directly :-)

**Pull request closed without merging**
