### PR TITLE
Add support to build rust, mesa and spidermonkey with llvm-12

### PR DESCRIPTION
**Pull request by J-Bu**
Update ebuilds and backport upstream patches to build successfully with llvm-12

### CODE REVIEW

**Review by Whissi — CHANGES_REQUESTED** [review]
NAK from mozilla project due to https://bugzilla.mozilla.org/show_bug.cgi?id=1658401 (LLVM 12 support will land with next version which should land this week). So please drop spidermonkey from your PR.

**Comment by J-Bu** [comment]
@Whissi 
Strange, I did a successfull testbuild of spidermonkey-78.9.0 with llvm and clang 12 but I can remove it from the PR

**Comment by stefson** [comment]
I'm certainly not a dev, but you might have better chances to get the dev-lang/rust changes merged if you don't git mv the -r2 to -r3, but rather copy the 1.51.0-r2 ebuild and add a silly high number to revision, such as -r99 or something along those lines, and you will have to drop keywords entirely. This will be enough to signal everyone to stay away from it, and everyone who wants to play with fire can keyword the ebuild locally. 

regaring mesa, I read through the upstream issue and it seems to cause further issues down the road with unreleased llvm-13, so maybe its best to wait and see this fixed properly?

**Comment by telans** [comment]
> dev-lang/rust-1.51 is stable candidate (to address some security issues) and will not gain llvm:12 support.

Why not revbump rust-1.51 for one version in testing + llvm:12, and one version stable + llvm:11?

**Pull request closed without merging**
