### PR TITLE
media-libs/libmygpo-qt: Add USE=qt4,qt5 via multibuild

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by rindeal** [comment]
You may want to have a look at a "trick" I used to deduplicate the `src_configure()` - https://github.com/gentoo/gentoo/pull/1185/commits/f4bf68305f1c14bcb663afc5c29e1fa11056f2c6

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
a17r  it appears the maintainer for both of these is Nikoli who is known to have abandoned his packages, ot at least has not been attending to them for an extended period.  If you offer, or wish, to take over maintainership, we can begin reviewing these patches.  Otherwise they are basically in a limbo.

**Comment by a17r** [comment]
This is merely the result of packaging clementine-qt5, which anyway is not ready yet. Not that I personally listen to podcasts...

**Comment by a17r** [comment]
closing for now, as clementine-qt5 currently isn't going anywhere.

**Pull request closed without merging**
