### PR TITLE
Add new package app-shells/mpv-bash-completion and revbump media-video/mpv

### PR DESCRIPTION
**Pull request by Coacher**
Add app-shells/mpv-bash-completion package, which provides mpv command-line completion via bash-completion, since recent versions of app-shells/bash-completion dropped mpv completion.

Revbump media-video/mpv to make users aware of the new package and backport a couple more upstream fixes on the way.

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
This LGTM.

**Comment by Coacher** [comment]
Thank you, @monsieurp.

**Pull request closed without merging**
