### PR TITLE
app-office/scribus: optfeature antiword

### PR DESCRIPTION
**Pull request by jeffgazso**
Signed-off-by: Jeffery Gazso <jeff.gazso@gmail.com>

### CODE REVIEW

**Comment by jeffgazso** [comment]
Adds `app-text/antiword` as an optfeature enabling MS Word legacy `.doc` file import support if installed. Let me know if this one looks better @thesamesam or if anything needs to be amended.

**Comment by thesamesam** [comment]
It's only been 2 days total. Not had a chance to look again.

**Comment by jeffgazso** [comment]
@thesamesam, Oops, sorry. I haven't gotten a feel for Gentoo's operational tempo for things like PR's yet. I wasn't trying to be a pain.

**Comment by thesamesam** [comment]
git author is still wrong: `Author: Your Name <you@example.com>` (also, we need to put `xdg_pkg_postinst` in pkg_postinst() as you're now shadowing the eclass call, but rI can do that on merge).

**Comment by thesamesam** [comment]
ping

**Comment by jeffgazso** [comment]
@thesamesam thanks for the ping, this completely slipped my mind.

So, as far as I can see on my end everything looks right. I do not see `Author: Your Name <you@example.com>` anywhere. Every `git` command I can think to run shows my info instead. Obviously there is something I'm missing because you see something different. 

I don't want to make an annoyance of myself by attempting to troubleshoot this over the comments in a PR request. I'm going to go post on the forum, reference this bug, and ask for pointers. Thanks again for the reminder.

**Comment by jeffgazso** [comment]
With the help of some nice folks on the forum, I have spotted the likely reason `Author: Your Name <you@example.com>` is was set. It's fixed now. Now I've got a few other minor things to figure out and then I'll push this up. It's Christmas Eve here, so give me a bit.

**Comment by jeffgazso** [comment]
I ran a `git commit --amend -s` it shows my name and not boilerplate on this end. With that set, I pushed it out. Let me know if something still isn't right.

**Pull request closed without merging**
