### PR TITLE
dev-libs/sway: include stdint to be compatible with musl

### PR DESCRIPTION
**Pull request by ntzrmtthihu777**
See SirCmpwn/sway@4bf8b6b43b9640700eadd7c7d1a432dd91ef473d

Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by Hummer12007** [comment]
0.14 is coming in a few weeks, so I'd suggest you used the live version for the time being.

**Comment by Hummer12007** [comment]
If you're adamant that it needs to be done NOW, please include
https://github.com/SirCmpwn/sway/pull/1259.patch
and
https://github.com/SirCmpwn/sway/pull/1255.patch
Please revbump as well.

**Comment by Hummer12007** [comment]
You'd have to include them as a single file.

**Comment by ntzrmtthihu777** [comment]
@Hummer12007 I would use the live ebuild, were it not for [this](https://paste.pound-python.org/show/1wl5vsMecgQ9gcnUskap/) build failure.

Do you mean both patches you provided, or all the patches including the stdint one?

**Comment by ntzrmtthihu777** [comment]
I realize that I could just install dbus, but it should be pulled in as a dep properly, I'd think.

**Comment by Hummer12007** [comment]
All the three.

**Comment by mgorny** [comment]
I suppose you'll want to rename the patch since it's no longer just about musl.

**Comment by Hummer12007** [comment]
Oh, wait. You're doing it wrong. Instead of calling `eapply ...patch` set
```
PATCHES=( "${FILESDIR}/...patch" )
```
before src_prepare().

**Comment by ntzrmtthihu777** [comment]
Well sway just released 0.14.0, which works with musl just fine. Will close this pr.

**Pull request closed without merging**
