### PR TITLE
kde-frameworks/kwallet: Update gpgmepp package name

### PR DESCRIPTION
**Pull request by a17r**
Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by johu** [comment]
Thanks. Patch applied.

**Comment by hasufell** [comment]
@johu by cherry-picking/applying directly you remove the user signature

**Comment by johu** [comment]
@hasufell what indicates in github that the commit is signed? And how will it behave on rebase?

**Comment by hasufell** [comment]
check with: `git log --show-signature`

to preserve signatures you have to merge, an example is here https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Pull_requests_from_users

After review you should ask the user to rebase and then force a merge commit via `--no-ff`. When you get push conflicts, make sure you pass do `git pull --rebase=preserve` so it preserves the merge stuff. I think that should keep the signatures.

**Comment by johu** [comment]
@hasufell  But the gkeys signature verification will only cover dev keys so why is this needed?

**Comment by hasufell** [comment]
> But the gkeys signature verification will only cover dev keys so why is this needed?

It is not needed, but you are removing the possibility to verify the _author_ of the commit (a17r). The committer is you.

**Comment by mgorny** [comment]
Yeah, don't take extra kudos from the user!

**Pull request closed without merging**
