### PR TITLE
Update virtual/httpd-basic and virtual/httpd-cgi to include www-servers/hiawatha

### PR DESCRIPTION
**Pull request by hasufell**
https://bugs.gentoo.org/show_bug.cgi?id=515566

### CODE REVIEW

**Comment by hasufell** [comment]
@mgorny I need @gentoo/web-apps here

**Comment by mgorny** [comment]
To update virtuals? Are you serious?

**Comment by hasufell** [comment]
@mgorny I don't touch those beasts often, so I don't really know the conventions. revbump, version bump, stable keywords, etc?

**Comment by monsieurp** [comment]
@hasufell A revbump should do. I recently had to take off skunkweb from two of the virtuals you've cited and a revbump was fine.

**Comment by hasufell** [comment]
> A revbump should do

that's what I did, but I dropped the keywords back to `~arch`, is that correct?

**Comment by mgorny** [comment]
No, virtuals always keep keywords matching the best visible package.

**Pull request closed without merging**
