### PR TITLE
new package Lidarr

### PR DESCRIPTION
**Pull request by PF4Public**
I hope @candrews won't mind keeping an eye on this package

### CODE REVIEW

**Comment by candrews** [comment]
Thank you!

**Comment by PF4Public** [comment]
@candrews Just synced gentoo and installed new packages over my unpacked ones and everything works as expected… Except a mistake sneaked into logrotate of Lidarr. 🤦
It should be 
```diff
--- <unbenannt>
+++ <unbenannt>
@@ -1,4 +1,4 @@
-/var/lib/lidarr/.config/lidarr/logs/*.txt{
+/var/lib/lidarr/.config/Lidarr/logs/*.txt{
     missingok
     su lidarr lidarr
 }
```

Would you be able to fix this when updating to the next release? It is too trivial to start a PR just for that. :(

**Comment by candrews** [comment]
Sure I can do that.

**Comment by candrews** [comment]
Can you please submit a PR adding yourself as a proxy maintainer to the metadata.xml for all of the lidarr and jacket packages and mention me in it so I can quickly merge it?

https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Proxied_maintainer_in_metadata.xml

**Comment by PF4Public** [comment]
> for all of the lidarr and jackett packages

What do you mean? I'm confused by your usage of pronoun "all" along with "lidarr" and "jackett". Do you mean _both_ of them or _all_ of them: *arr + jackett?

BTW, @candrews what is your current workflow w.r.t. bumping all of these packages? I think I can automate this process in the same manner as I did it [in my overlay](https://github.com/PF4Public/gentoo-overlay/commits?author=oegniwgrogklfepog%5Bbot%5D). But since I don't belong to gentoo org, someone will still need to merge my automated PRs. Would it be useful?

**Comment by candrews** [comment]
I meant all of the lidarr and jackett packages, including the primary application packages as well as the user and group packages.

I use a feed reader to monitor the release feeds and manually bump when new versions becomes available. I'm curious to learn more about your workflow, I'm always looking for better approaches :-)

**Comment by PF4Public** [comment]
> I meant all of the lidarr and jackett packages, including the primary application packages as well as the user and group packages.

OK

> I use a feed reader to monitor the release feeds and manually bump when new versions becomes available. I'm curious to learn more about your workflow, I'm always looking for better approaches :-)

I have a cron job, that uses GitHub API to pull tags/releases of each of monitored packages, compares versions available and the versions in my repository, copies ebuild with new name, pulls my repository with rebase (for the cases where I update my overlay in the meanwhile) and pushes changes back.

Then I have GitHub Workflow that [tests newly added ebuilds with several of important USE flags](https://github.com/PF4Public/gentoo-overlay/blob/5df4fe3c1aa314f2c88c65840317b57085d5b334/.github/workflows/electron.yml#L60-L70). 

Using GitHub API again cron job then checks if the Workflow was a success and if it was it marks ebuild as stable and removes older ones. IF there was a failure on important USE flags, I get a notification over GitHub and fix what was broken manually.

The previous step repeats and if the last Workflow run was a success (after my fixes), ebuild is marked stable and older ones removed.

It is a Perl script if you're curious.

I think GitHub has an API to also create a PR programmatically, so I could implement that too in case that it would be potentially easier to merge a PR compared to your current workflow.

**Pull request closed without merging**
