### PR TITLE
net-irc/weechat: add 4.1.1, 4.0.6

### PR DESCRIPTION
**Pull request by sevz17**

### CODE REVIEW

**Comment by Flowdalic** [comment]
4.0.5 seems like something we could (and if so, should) stabilize, not drop. Or is there a reason, like a known regression in the release, to drop 4.0.5?

**Comment by zpuskas** [comment]
Yeah, I agree. We should stabilize 4.0.5 and drop 4.0.2 instead. I'll take a look at the 4.1.1 commit later today.

**Review by zpuskas — CHANGES_REQUESTED** [review]
Best practice usually is to add new ebuild first, and then drop an old one in a separate commit.

**Comment by zpuskas** [comment]
The 4.1.1 commit looks good to me.

**Comment by sevz17** [comment]
My apologies for disappearing.

I could have been too hasty in dropping 4.0.5, upstream says it fixes a build error when building without nls but after testing in my machine it builds fine, so just adding 4.0.6

**Comment by zpuskas** [comment]
Would you mind also dropping 4.0.2, since 4.0.4 is stable already, thus there is no point in keeping it around. Otherwise LGTM.

**Comment by Flowdalic** [comment]
> Would you mind also dropping 4.0.2

done

**Pull request closed without merging**
