### PR TITLE
Add ~arm to several packages.

### PR DESCRIPTION
**Pull request by DarthGandalf**
I successfully installed and used them on Raspberry Pi 3 board:
dev-python/dpkt-1.8-r1
dev-python/netaddr-0.7.18
net-analyzer/scapy-2.3.1
net-firewall/firehol-3.0.1
net-misc/iprange-1.0.2
net-misc/ndppd-0.2.3

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi. Thanks for your work. Please make sure to respect our commit format when filing a PR: https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format.

**Comment by blueness** [comment]
also, the keywords should be in alphabetical order.  take a look at other ebuilds for examples.  i can commit afterwards.

**Comment by blueness** [comment]
also, i know it might be annoying, but each pkg should be its own commit.  the reason is that we should be able to revert each one separately rather than adding new commits.  this is a minor point for adding keywords, but in general, just keep that in mind.  individual commits addressing individual issues so they can be reverted without messing up other things we don't want reverted.

**Comment by DarthGandalf** [comment]
I've updated the PR, PTAL.

**Comment by blueness** [comment]
okay its done.  thanks for testing.

**Comment by DarthGandalf** [comment]
Thanks for quick review!

**Comment by blueness** [comment]
i had to pull back on scapy because you didn't also keyword the dependencies.  so here's how you fix it.  cd /usr/portage/netanalyzer/scapy ; repoman full.  when you see the report, test those packages keyword then and then run repoman full on those packages too.  sometimes the dependencies can go several levels deep.  *all* of the dependencies must be keyworded else you get a QA error.

**Comment by DarthGandalf** [comment]
Oops, sorry.
I installed it without use-flags which add those dependencies. I'll try repoman.

**Pull request closed without merging**
