### PR TITLE
net-firewall/ebtables: Update SRC_URI from ftp to http

### PR DESCRIPTION
**Pull request by brianmego**
Package-Manager: Portage-3.0.9, Repoman-3.0.2

### CODE REVIEW

**Comment by brianmego** [comment]
https://bugs.gentoo.org/761990

**Comment by Montana** [comment]
Hey @brianmego, w
I was having similar issue. Is it repro every single time on your side?

**Review by floppym — CHANGES_REQUESTED** [review]
To reiterate the boiler-plate text:

Please read the terms of [Gentoo Certificate of Origin](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin) and acknowledge them by adding a sign-off to all your commits.

**Comment by floppym** [comment]
Also, please add this to the commit message:
```
Closes: https://bugs.gentoo.org/761990
```

**Comment by brianmego** [comment]
@Montana 100% reproducible, yes. @floppym I'll get that done tonight. Thanks.

**Comment by brianmego** [comment]
@floppym Pretty sure I added the sign-off, but the missing label remains. I'm guessing this is an automation issue, but if I have additional work to do to comply, please let me know and I'll take a look.

**Pull request closed without merging**
