### PR TITLE
Cinnamon updates (24/09/26)

### PR DESCRIPTION
**Pull request by SparkyBluefang**
* Drop Cinnamon 6.0
* Update cinnamon-screensaver to 6.2.1

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
Are the two linked muffin bugs actually fixed by 6.2 or were they fixed long ago and should be closed on their own? Especially since you said on the linked tickets that you could not reproduce...

**Comment by SparkyBluefang** [comment]
> Are the two linked muffin bugs actually fixed by 6.2 or were they fixed long ago and should be closed on their own? Especially since you said on the linked tickets that you could not reproduce...

832474 is presumably fixed by newer versions, as I believe there have been various clang fixes from upstream rebases. But both of them ultimately haven't been updated since they were reported (i.e. no feedback/additional info provided, haven't been reported/reproduced on newer versions, etc).

**Comment by eli-schwartz** [comment]
> 832474 is presumably fixed by newer versions, as I believe there have been various clang fixes from upstream rebases.

This is wishy-washy.

And I have tested it and -Werror=format-nonliteral still triggers that error.

Even if it was gone -- what is your reason for thinking that the bug report should be closed with the statement that it is "fixed by removing the 6.0 ebuild, which was the last ebuild to have that bug"?

> But both of them ultimately haven't been updated since they were reported (i.e. no feedback/additional info provided, haven't been reported/reproduced on newer versions, etc).

It is a tinderbox bug provided as an automatic report and it is quite common to not get any responses from the automated report. I wish this were not so, but it is. The lack of response is not connected to whether or not it is still reproducible.

**Comment by SparkyBluefang** [comment]
> It is a tinderbox bug provided as an automatic report and it is quite common to not get any responses from the automated report. I wish this were not so, but it is. The lack of response is not connected to whether or not it is still reproducible.

I thought tinderbox reported issues were supposed to be updated if they were reproduced on newer versions.

```
19) Valid from 2021-09-28 When there is an open bug about a package, in case the bug is reproduced with a newer version, a comment on the bug is added and the summary is updated with new new version that reproduces the issue.
```

I had assumed that since there weren't any reports on newer versions, that it was fixed in at least muffin 5.4.

> And I have tested it and -Werror=format-nonliteral still triggers that error.
> 
> Even if it was gone -- what is your reason for thinking that the bug report should be closed with the statement that it is "fixed by removing the 6.0 ebuild, which was the last ebuild to have that bug"?

Is this a clang specific issue? Unless I'm doing something wrong, I still can't reproduce with `gcc-13.3.1_p20240614`, and I don't have clang on my system.

```
CFLAGS="-march=native -O2 -pipe -Werror=format-nonliteral" CXXFLAGS="-march=native -O2 -pipe -Werror=format-nonliteral" FEATURES="test" USE="test xvfb" emerge -av1 muffin 
```

I get test failures (937350 - new) but not any compile errors.

Can you attach a build failure log to that bug? I'll file a bug upstream, but I should probably have something newer than a 2.5 year old log on a 5 version old release.... However, the last time I filed an upstream bug about compiler flags, that turned into a cat fight that I want \*no\* part in repeating. So we'll see how that goes.

And what about 915169? I couldn't reproduce that one either, and Joonas never replied.

For now, I've removed both `Closes`.

**Comment by eli-schwartz** [comment]
> Can you attach a build failure log to that bug? I'll file a bug upstream, but I should probably have something newer than a 2.5 year old log on a 5 version old release.... However, the last time I filed an upstream bug about compiler flags, that turned into a cat fight that I want *no* part in repeating. So we'll see how that goes.

It's fairly easy these days to install clang due to the availability of the binhost.

```
FAILED: clutter/clutter/libmuffin-clutter-0.so.0.0.0.p/clutter-main.c.o 
clang -Iclutter/clutter/libmuffin-clutter-0.so.0.0.0.p -Iclutter/clutter -I../muffin-6.2.0/clutter/clutter -Iclutter -I../muffin-6.2.0/clutter -Icogl -I../muffin-6.2.0/cogl -Icogl/cogl -I../muffin-6.2.0/cogl/cogl -I/usr/include/atk-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/lib64/libffi/include -I/usr/include/cairo -I/usr/include/libpng16 -I/usr/include/freetype2 -I/usr/include/harfbuzz -I/usr/include/pixman-1 -I/usr/include/gio-unix-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/json-glib-1.0 -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/graphene-1.0 -I/usr/lib64/graphene-1.0/include -fvisibility=hidden -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -D_GNU_SOURCE -pipe -march=native -fstack-protector-all -O2 -fdiagnostics-color=always -frecord-gcc-switches -Wformat -Werror=format-security -Werror=format-nonliteral -fPIC -mfpmath=sse -msse -msse2 -pthread '-DCLUTTER_SYSCONFDIR="/etc"' -DCLUTTER_COMPILATION=1 -DCOGL_DISABLE_DEPRECATION_WARNINGS '-DG_LOG_DOMAIN="Clutter"' -MD -MQ clutter/clutter/libmuffin-clutter-0.so.0.0.0.p/clutter-main.c.o -MF clutter/clutter/libmuffin-clutter-0.so.0.0.0.p/clutter-main.c.o.d -o clutter/clutter/libmuffin-clutter-0.so.0.0.0.p/clutter-main.c.o -c ../muffin-6.2.0/clutter/clutter/clutter-main.c
../muffin-6.2.0/clutter/clutter/clutter-main.c:2683:46: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
 2683 |   g_logv (G_LOG_DOMAIN, G_LOG_LEVEL_MESSAGE, fmt, var_args);
      |                                              ^~~
../muffin-6.2.0/clutter/clutter/clutter-main.c:2723:46: error: format string is not a string literal [-Werror,-Wformat-nonliteral]
 2723 |   g_logv (G_LOG_DOMAIN, G_LOG_LEVEL_MESSAGE, fmt, args);
      |                                              ^~~
2 errors generated.
```

https://clang.llvm.org/docs/AttributeReference.html#format clang implements this slightly different from GCC

**Comment by eli-schwartz** [comment]
> And what about 915169? I couldn't reproduce that one either, and Joonas never replied.

If you cannot reproduce it we should just close it as "RESOLVED WORKSFORME" without tying it to this cleanup. :)

**Comment by SparkyBluefang** [comment]
I filed https://github.com/linuxmint/muffin/issues/703 in case it's worth tracking the issue upstream. But I've removed the `closes` from the commit, and I feel no need to tie bug clean-up to this PR. I thought it would just be some unobjectionable fall cleaning of stale bugs, but I guess not >_<

**Comment by eli-schwartz** [comment]
> However, the last time I filed an upstream bug about compiler flags, that turned into a cat fight that I want *no* part in repeating. So we'll see how that goes.

.... and lol...

**Pull request closed without merging**
