### PR TITLE
net-misc/axel: fixes and new version

### PR DESCRIPTION
**Pull request by ordex**
With this PR I get rid of two old ebuilds (buggy versions not maintained by upstream anymore); I fix some instructions and I introduce a new version released this night (2.15).

### CODE REVIEW

**Comment by monsieurp** [comment]
@jlec ping

**Comment by jlec** [comment]
@ordex we cannot drop version 2.4 yet as it is the last stable. PLease add it back again

**Comment by ordex** [comment]
@jlec 2.4 has been added back. Any link for me to read so I can understand how stabilization works? (i.e. when can a new version be declared stable and an old one can be purged out?)

**Comment by monsieurp** [comment]
@ordex https://wiki.gentoo.org/wiki/Stable_request

**Pull request closed without merging**
