### PR TITLE
sys-kernel/linux-firmware: Change source URL to reliable mirror

### PR DESCRIPTION
**Pull request by pothos**
The caching git web view which was used as source location is not
reliable because the cache can be corrupt, the gzip compression of the
snapshot can change, and the cache is produced by the web server which
is not there to give high security guarantees. At least with the
files served for linux-firmware-20191022 we experienced a file length
change (and thus a checksum change) yesterday.
Switch to the recommended mirror under
https://mirrors.edge.kernel.org/pub/linux/kernel/firmware/
which also hosts signatures and is not having the downsides mentioned
above (all information is based on a reply from Konstantin Ryabitsev
after we notified webmaster@kernel.org about this incident).

Should I have only changed the 99999999 file because the Gentoo mirrors are supposed to serve the correct files? Maybe because we used linux-firmware-20191022 we hit this depending on whether source files for old ebuilds are still in the Gentoo mirror?

### CODE REVIEW

**Comment by Whissi** [comment]
Could you please forward the mail conversation you had with upstream? You can get my contact address from https://wiki.gentoo.org/wiki/User:Whissi

**Comment by ZeroChaos-** [comment]
@Whissi since you are already engaged here I happily yield to your discretion on this subject.

**Comment by Whissi** [comment]
Thank you.

I disagree with most concerns but we will upgrade SRC_URI for non-snapshot releases.

**Comment by pothos** [comment]
Thanks

**Pull request closed without merging**
