### PR TITLE
net-libs/iojs: masked for removal (merge on 08/03)

### PR DESCRIPTION
**Pull request by jbergstroem**
Not sure if this is the right way to bring forth a suggested ebuild removal; but as co-maintainer I can at least vouch the warrant for removal. If this should be done from a PR I'm not sure, but lets find out!

iojs and nodejs merged and formed the new major version nodejs 4.0. iojs will not be maintained after 3.3.x and all users are suggested to move to nodejs 4 (or newer) as quick as possible to avoid any security-related issues.

Question: How would this be communicated to users? Can we tell users to update to nodejs some way?

/cc @patricklauer. Couldn't find the treecleaners group on github?

### CODE REVIEW

**Comment by idella** [comment]
std. procedure to my knowledge is last rite notification to the dev & dev-announce ML. The submission of the same as a bug in bugzilla is purely optional.

**Comment by monsieurp** [comment]
@idella: indeed but someone on the Gentoo end has to do it.

**Comment by monsieurp** [comment]
"Question: How would this be communicated to users? Can we tell users to update to nodejs some way?"

@jbergstroem: When masking the package, we can explain why iojs is being removed. If necessary, we can put together a news item. As far as I understand, net-libs/iojs is now deprecated (defunct?) and can be removed from the tree. Please file a bug and ask for the package removal cause it's the preferred method. Once the deed is done, we'll merge your PR and last-rite the package.

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by jbergstroem** [comment]
@monsieurp bug here: https://bugs.gentoo.org/show_bug.cgi?id=573870

**Comment by monsieurp** [comment]
Ping us back on 08/03 to have this PR merged. Cheers.

**Pull request merged**
