### PR TITLE
x11-wm/page: Drop inactive proxied maintainer

### PR DESCRIPTION
**Pull request by mattst88**
cc: @monsieurp, @gschwind

### CODE REVIEW

**Comment by mattst88** [comment]
I can leave you as a maintainer, but like I mentioned you haven't ever committed to ::gentoo and you don't seem to be active on bugzilla. There are two open bugs against the package that you, as the upstream maintainer, should be able to fix easily.

**Comment by gschwind** [comment]
My appologies, I think I had already worked on bugzilla issue, but I'm quite bussy and I forgot to push then.

I will have a look :)

**Comment by mattst88** [comment]
I pushed the fix to the `HOMEPAGE` but not the change to metadata.xml. I'll check back to see if you have some activity in a few months.

**Comment by gschwind** [comment]
Hello,

I did updated page package, and I submited a new ebuild into bugzilla

Best regards

**Pull request closed without merging**
