### PR TITLE
www-servers/tomcat: drop 9.0.91 | media-tv/mythtv: drop 33.1-r1 | games-board/megamek: drop 0.34.10-r2| media-video/bdsup2sub: treeclean

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog i guess you haven't got an email from this PR. 
https://marc.info/?l=gentoo-dev&m=171990454516312&w=2

**Comment by fordfrog** [comment]
> @fordfrog i guess you haven't got an email from this PR. https://marc.info/?l=gentoo-dev&m=171990454516312&w=2

i probably did, but i guess i missed it.

**Comment by fordfrog** [comment]
@vaukai what's the status here? ready to merge?

**Comment by vaukai** [comment]
> @vaukai what's the status here? ready to merge?

Yep, ready.

**Review by fordfrog — APPROVED** [review]

**Comment by vaukai** [comment]
rebased for mythtv

**Comment by vaukai** [comment]
@fordfrog i've just re-tested everything in this PR and i'd appreciate if you could continue here.

be aware that `amap`, `cxprolog` and `mythtv` have optional `java`. 
`smtinterpol` uses several bundled dependencies (special versions, there i gave up) and code generation. will open a bug report after merge.

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
@vaukai what's approved is merged

**Comment by vaukai** [comment]
> @vaukai what's approved is merged

thanks. i will just remove hardcoded from `megamek-0.34.10-source8.patch` and rebase

**Comment by vaukai** [comment]
@fordfrog `smtinterpol` is one that needs stabilization while `mythtv` and `megamek` could be cleaned up right after merge, so i moved `smtinterpol` to top.

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
i merged everything except the two drops, for now.

**Comment by chewi** [comment]
I feel like I'm missing some context here. MegaMek hasn't been bumped. I know you tried, and it didn't work out. I'm still a bit sad about that. You can't just drop it entirely like this though, it has to be last-rited first.

**Comment by vaukai** [comment]
> I feel like I'm missing some context here. MegaMek hasn't been bumped. I know you tried, and it didn't work out. I'm still a bit sad about that. You can't just drop it entirely like this though, it has to be last-rited first.

this is about dropping `-r2` while `-r3` will stay.

**Review by chewi — APPROVED** [review]
Ah okay, my repo was behind, so I didn't see -r3.

**Pull request closed without merging**
