### PR TITLE
dev-db/sqlite: add 3.35.1

### PR DESCRIPTION
**Pull request by oz123**
Also enabled new SQL math functions added in this version.

I disabled the patches from previous version, they won't apply. If these patches are really needed, I can invest the time to fix them. I have not spent much time looking into this.

Signed-off-by: Oz N Tiram <oz.tiram@gmail.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
@Arfrever

**Comment by dongsupark** [comment]
FYI, I filed another PR https://github.com/gentoo/gentoo/pull/19972 to fix bugs in sqlite ebuilds.
If this PR for 3.35.1 were merged first, then I could rebase my PR and add more code.

**Comment by oz123** [comment]
@Arfrever closing this as this version was bumped in
4e190cb13bdb797d59b5c357b4a1d464231e093a.

Please consider enabling the new built-in math functions.

**Comment by Arfrever** [comment]
They are enabled. See `ENABLE_MATH_FUNCTIONS`:
```
$ sqlite3
SQLite version 3.35.3 2021-03-26 12:12:52
Enter ".help" for usage hints.
Connected to a transient in-memory database.
Use ".open FILENAME" to reopen on a persistent database.
sqlite> pragma compile_options;
COMPILER=gcc-10.2.0
ENABLE_API_ARMOR
ENABLE_BYTECODE_VTAB
ENABLE_COLUMN_METADATA
ENABLE_DBSTAT_VTAB
ENABLE_FTS3
ENABLE_FTS3_PARENTHESIS
ENABLE_FTS4
ENABLE_FTS5
ENABLE_GEOPOLY
ENABLE_HIDDEN_COLUMNS
ENABLE_ICU
ENABLE_JSON1
ENABLE_MATH_FUNCTIONS
ENABLE_MEMSYS5
ENABLE_NORMALIZE
ENABLE_PREUPDATE_HOOK
ENABLE_RBU
ENABLE_RTREE
ENABLE_SESSION
ENABLE_STMTVTAB
ENABLE_STMT_SCANSTATUS
ENABLE_UNKNOWN_SQL_FUNCTION
ENABLE_UNLOCK_NOTIFY
ENABLE_UPDATE_DELETE_LIMIT
HAVE_ISNAN
SECURE_DELETE
SOUNDEX
TEMP_STORE=1
THREADSAFE=1
USE_URI
sqlite>
```

**Comment by oz123** [comment]
@Arfrever thanks for the really quick response. I was not aware it is enabled by default.

**Pull request closed without merging**
