### PR TITLE
dev-python/future: add 1.0.0

### PR DESCRIPTION
**Pull request by lanodan**
By the way upstream says this should be the last version of future.

### CODE REVIEW

**Comment by mgorny** [comment]
Do the tests pass for you? I've tried bumping it a few days ago, and had lots of test failures.

**Comment by lanodan** [comment]
Yeah the tests pass on py3.11 here (and don't on py3.12 which is why I didn't mark it as compatible)

**Comment by arthurzam** [comment]
Tested the ebuild:

- passed on python 3.10 and 3.11
- failed on pypy3

```
FAILED tests/test_future/test_builtins.py::BuiltinTest::test_exec_globals - AssertionError: NameError not raised by exec
FAILED tests/test_future/test_futurize.py::TestFuturizeSimple::test_raw_input - AssertionError: b'Traceback (most recent call last):\n  Fil[141 chars]or\n' != b''
FAILED tests/test_future/test_int.py::IntTestCases::test_intconversion - RecursionError: maximum recursion depth exceeded
FAILED tests/test_future/test_isinstance.py::TestIsInstanceIsSubclass::test_isinstance_recursion_limit - AssertionError: RuntimeError not raised by blowstack
FAILED tests/test_future/test_isinstance.py::TestIsInstanceIsSubclass::test_subclass_recursion_limit - AssertionError: RuntimeError not raised by blowstack
```

**Comment by mgorny** [comment]
On top of that, it has py3.12 revdeps, so not everyone could upgrade, and given we're phasing it out, bumping at this point seems a bit like pointless hassle.

**Pull request closed without merging**
