### PR TITLE
app-admin/lastpass-cli: bump to version 0.7.1

### PR DESCRIPTION
**Pull request by gktrk**
Patching Makefile in src_prepare to disable stripping on install
isn't needed anymore. See upstream commit 17b5d40 for more info.

Package-Manager: portage-2.2.24

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
LGTM. Let's wait till the CI tests are over.

**Comment by gktrk** [comment]
Unfortunately this one isn't proxy-maint. Need @jdhore for this one.

**Comment by blueness** [comment]
this merge clobbered my changes which added libressl support.

**Comment by blueness** [comment]
i re-added libressl support.  we need to be careful when merging because the tree and the pr may diverge.

**Comment by gktrk** [comment]
sorry, I should have tried to rebase one more time perhaps.

**Comment by blueness** [comment]
@gktrk actually, thinking about this, i don't see how we're going to easily avoid situations where a pr and the tree diverge.  i think the maintainer just needs to be aware and vigilant.  anyhow, thanks for the contribution!  we're all getting used to this new work flow and the last thing i want to do is discourage user from contributing because of a hiccup.

**Pull request merged**
