### PR TITLE
sys-libs/libapparmor && sys-apps/apparmor{,utils}: Version bump.

### PR DESCRIPTION
**Pull request by gkranis**
There is a relevant bump request bug 554984 in bugzilla
I am not sure if the private api change is the right way to fix this, please advise.
I'm sorry for any ugliness in the ebuilds, feedback is welcome :)

### CODE REVIEW

**Comment by monsieurp** [comment]
@kensington

**Comment by kensington** [comment]
Thanks a lot for working on this. The build fix seems to work fine, but I'm running a number of runtime issues with the python tools (such as not being able to import LibAppArmor).

**Comment by gkranis** [comment]
You are right, I get those too.
I quickly changed python target to 3.4 and run  python3.4 /usr/sbin/aa-autodep man and it run without issues

**Comment by kensington** [comment]
Thanks again for resolving the dynamic linking issue. This is now rebased in 4a18bafabd4c05adce58406424f697e4c88362b3..526dbc4117bf53335b49bb5d2a13d0ff2c95c35e with some various other fixes too.

**Pull request closed without merging**
