### PR TITLE
media-gfx/splash-themes-livecd: Update rc_init-pre to use new path for functions.sh

### PR DESCRIPTION
**Pull request by ShyPixie**
@mgorny 
https://bugs.gentoo.org/show_bug.cgi?id=504394
https://bugs.gentoo.org/show_bug.cgi?id=504116

### CODE REVIEW

**Comment by mgorny** [comment]
Please amend the commit message to meet git in standards.

    category/package: short summary line, optionally #nnnnnn 
    
    Extended description if necessary

In particular, the first line must be no longer than 75 chars and must not be wrapped.

**Comment by ShyPixie** [comment]
@mgorny Sorry. Done.

**Comment by mgorny** [comment]
1. This is not a good commit message. The key point is using gentoo-functions, not 'fixing' something because it isn't broken in the first place.
2. gentoo-functions is a runtime dependency (RDEPEND).

**Comment by ShyPixie** [comment]
@mgorny 
1. Done.
2. You corrected me earlier and you commit this as DEPEND on a previous commit. I just followed. See https://github.com/gentoo/gentoo/commit/5eba5408de4b0c5f5d96f34bfbea366e141ae305. Done, anyway.

**Comment by mgorny** [comment]
1. We still didn't understand each other correctly. I mean gentoo-functions should be the important thing noted in summary line. Like when you do `git log --oneline`, you see 'Update rc_init-pre' and you scratch your head and have to check the commit. If you said, say, 'Use functions.sh from gentoo-functions', it would be much more helpful.
2. Yes, I didn't notice that earlier and got shouted at for merging it.

**Comment by ShyPixie** [comment]
@mgorny You're right. Done.

**Comment by mgorny** [comment]
Both merged, thanks.

**Pull request merged**
