### PR TITLE
dev-util/{buildbot-worker,buildbot}, net-misc/crossbar: remove unused patches/files

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes some unused service files and one patch from:
dev-util/buildbot-worker
dev-util/buildbot
net-misc/crossbar

Please review.

### CODE REVIEW

**Comment by kensington** [comment]
Thanks, picked as c59cdcb23775f4273e1d717780418ff30c7c73ee...bf6d0cba4d23dc69f652eecd009a2e237abef542.

**Comment by dol-sen** [comment]
Hmm, thanks kensington, but I only wanted the one patch removed.  I was going to add the service files to the ebuilds like they should have been.  But not using systemd, I didn't realize they weren't being installed.

**Comment by kensington** [comment]
Sorry, @dol-sen. Many of these PRs sadly get left to bitrot so I try to jump on them when I see them. Would you like me to restore the service files?

**Comment by dol-sen** [comment]
No, I'll do it with the changes in the ebuilds.

**Pull request closed without merging**
