### PR TITLE
dev-java/jnr-ffi: bump to 2.2.8

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog Do you have an idea regarding these compile errors ?
```
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
src/main/java/jnr/ffi/provider/jffi/StubCompiler.java:56: error: an enum switch case label must be the unqualified name of an enumeration constant
                case AARCH64:
                     ^
src/main/java/jnr/ffi/provider/jffi/StubCompiler.java:122: error: an enum switch case label must be the unqualified name of an enumeration constant
                case AARCH64:
                     ^
src/main/java/jnr/ffi/provider/jffi/X86MethodGenerator.java:76: error: cannot find symbol
        if (!platform.getCPU().equals(Platform.CPU.I386) && !platform.getCPU().equals(Platform.CPU.X86_64) && !platform.getCPU().equals(Platform.CPU.AARCH64)) {
                                                                                                                                                    ^
  symbol:   variable AARCH64
  location: class CPU
src/main/java/jnr/ffi/provider/InterfaceScanner.java:78: warning: non-varargs call of varargs method with inexact argument type for last parameter;
            isDefault = Method.class.getMethod("isDefault", null);
                                                            ^
  cast to Class<?> for a varargs call
  cast to Class<?>[] for a non-varargs call and to suppress this warning
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
3 errors
2 warnings

```

**Comment by fordfrog** [comment]
everything merged except `dev-java/jnr-ffi`. i was not able to get rid of the errors. anyway, it compiles fine if using maven.

**Comment by fordfrog** [comment]
i had a look at it but i was pretty tired at that time so i got pretty confused. but i recall there might be some extra code in `pom.xml` that generates somethings so you might want to have a look at it.

**Comment by vaukai** [comment]
What maven does [is this](https://github.com/gentoo/gentoo/pull/20697/commits/4b62cad6ffed78e391f827371fe4263e88451175#diff-97589a95f719ec1c10ca3adf630fd951b264630d8ae2f4685945aa2b02fe081dR69-R74)
```
#	<exec failonerror="true" dir="/var/tmp/portage/dev-java/jnr-ffi-2.2.4/work/jnr-ffi-jnr-ffi-2.2.4" executable="make">
#		<arg line="-f libtest/GNUmakefile"/>
#		<arg line="BUILD_DIR=/var/tmp/portage/dev-java/jnr-ffi-2.2.4/work/jnr-ffi-jnr-ffi-2.2.4/target"/>
#		<arg line="CPU=amd64"/>
#	</exec>${tasks}</tasks>
```
So I tried 
```
emake -f libtest/GNUmakefile \
BUILD_DIR=target \
CPU=amd64 || die
```
but doen't help - the error persists

**Comment by fordfrog** [comment]
i just had a look at it but didn't find the cause.

looking at the compiled file, it contains the enum:
```
# javap target/classes/jnr/ffi/Platform\$CPU.class 
Compiled from "Platform.java"
public final class jnr.ffi.Platform$CPU extends java.lang.Enum<jnr.ffi.Platform$CPU> {
  public static final jnr.ffi.Platform$CPU I386;
  public static final jnr.ffi.Platform$CPU X86_64;
  public static final jnr.ffi.Platform$CPU PPC;
  public static final jnr.ffi.Platform$CPU PPC64;
  public static final jnr.ffi.Platform$CPU PPC64LE;
  public static final jnr.ffi.Platform$CPU SPARC;
  public static final jnr.ffi.Platform$CPU SPARCV9;
  public static final jnr.ffi.Platform$CPU S390X;
  public static final jnr.ffi.Platform$CPU MIPS32;
  public static final jnr.ffi.Platform$CPU ARM;
  public static final jnr.ffi.Platform$CPU AARCH64;
  public static final jnr.ffi.Platform$CPU MIPS64EL;
  public static final jnr.ffi.Platform$CPU UNKNOWN;
  public static jnr.ffi.Platform$CPU[] values();
  public static jnr.ffi.Platform$CPU valueOf(java.lang.String);
  public java.lang.String toString();
  static {};
}
```

changing the failing enum from `AARCH64` to something different (in my case `PPC`) fixed the compilation, but that's not a fix in fact.

**Comment by fordfrog** [comment]
i just gave this a try with the just-merged `jffi` and i get bunch of following errors. i suppose the solution should be the same as in case of `jffi`:
```
1) shortByReference(jnr.ffi.ArrayTest)
java.lang.UnsatisfiedLinkError: libtest.so: cannot open shared object file: No such file or directory
	at jnr.ffi.provider.jffi.NativeLibrary.loadNativeLibraries(NativeLibrary.java:101)
	at jnr.ffi.provider.jffi.NativeLibrary.getNativeLibraries(NativeLibrary.java:79)
	at jnr.ffi.provider.jffi.NativeLibrary.getSymbolAddress(NativeLibrary.java:58)
	at jnr.ffi.provider.jffi.NativeLibrary.findSymbolAddress(NativeLibrary.java:68)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.generateInterfaceImpl(AsmLibraryLoader.java:136)
	at jnr.ffi.provider.jffi.AsmLibraryLoader.loadLibrary(AsmLibraryLoader.java:84)
	at jnr.ffi.provider.jffi.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:44)
	at jnr.ffi.LibraryLoader.load(LibraryLoader.java:418)
	at jnr.ffi.TstUtil.loadTestLib(TstUtil.java:56)
	at jnr.ffi.TstUtil.loadTestLib(TstUtil.java:46)
	at jnr.ffi.ArrayTest.setUpClass(ArrayTest.java:115
```

**Comment by fordfrog** [comment]
@vaukai thanks! :-) i did some cleanup during the merge. did not merge `2.2.4` at all as it is obsoleted by `2.2.8` and the tests would need to be resolved. and also did not merge `2.0.2-r1` with eapi update as that version is obsoleted by `2.2.8` as well. we can stabilize `2.2.8' sooner to get rid of those old versions.

**Pull request closed without merging**
