### PR TITLE
[wip] dev-java/jackson: bump to 2.9.8

### PR DESCRIPTION
**Pull request by matoro**

### CODE REVIEW

**Comment by juippis** [comment]
1: Invalid sign-off, 
2: Don't use `git mv`, but create a new copy and commit that instead - you can't drop the 2.8.5 because it has reverse dependencies, 
3: Use repoman to check your contribtution, and preferably to commit - it would have told you about this error.

**Comment by matoro** [comment]
Yeah, that was my bad.  I think the better idea is to bump the entire jackson family up.  The issue I've run into is that dev-java/jackson-module-jaxb-annotations has been deprecated as a standalone module and has instead been moved into https://github.com/FasterXML/jackson-modules-base , so I'm not sure if the better approach is to create one package that includes all of those modules or simply only use part of the source tree to bump the jaxb module.

**Comment by monsieurp** [comment]
Thanks @matoro for working on this. Don't hesitate to ping me if you need help (I'm part of the Java team). As @juippis pointed out already, please avoid to just plain `mv`, create a copy, add it to repository, run `repoman full -d` for a full QA scan and finally `repoman commit` to commit. Thanks!

**Comment by wimmuskee** [comment]
jackson-2.9.10 has been added with https://github.com/gentoo/gentoo/commit/571aeaecbaf3738fa9204aeb4a34de167da23021. This PR can probably be closed.

**Pull request closed without merging**
