### PR TITLE
dev-python/pyacoustid: enable py3.11

### PR DESCRIPTION
**Pull request by arkamar**
This package does not have any tests available, however, I run time tested it with an example from upstream README https://github.com/beetbox/pyacoustid#running. It returned the same result in all 3 python versions. The test needs internet connection.

### CODE REVIEW

**Comment by thesamesam** [comment]
Could you wire that up in python_test? It's better than nothing.

**Comment by arkamar** [comment]
Yes, I can do that, but the test needs some mp3 file. Do you know about some that we can use? I tried to grep some in ::gentoo tree, but I didn't find anything there.

**Comment by thesamesam** [comment]
https://freesound.org/ seems to have freely licenced samples we can use. Pick anything (maybe something like a cow mooing etc if you want some humour, given it's Gentoo)

**Comment by arkamar** [comment]
I took some random song which produces any output to the log, it is better for log inspection. It was needed to enable `ffmpeg` use in `dev-python/audioread` so I revbumped the ebuild and dropeed keywords to `~all`.

**Comment by thesamesam** [comment]
Spoil sport, but I admire the effort 😄

**Comment by arkamar** [comment]
The test song is stored as `${PN}-test.mp3`. I originally used `${P}` but it seems to be unncessary to have same copy for every potential version.

**Pull request closed without merging**
