### PR TITLE
[WiP] LLDB reintroduction

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@aballier, @austin987, @blueness, @lu-zero, @williamh

**Comment by mgorny** [comment]
Now that everyone's highlighted, I need help. The ebuild is hacky to an awful degree of hackery but it should build with USE=-ncurses. However, I'm getting some missing symbols:

```
lib64/liblldbSymbol.a(ClangASTContext.cpp.o):(.data.rel.ro._ZTI22NullDiagnosticConsumer[_ZTI22NullDiagnosticConsumer]+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
lib64/liblldbSymbol.a(ClangASTImporter.cpp.o):(.data.rel.ro._ZTIN12lldb_private16ClangASTImporter6MinionE[_ZTIN12lldb_private16ClangASTImporter6MinionE]+0x10): undefined reference to `typeinfo for clang::ASTImporter'
lib64/liblldbPluginExpressionParserClang.a(ClangModulesDeclVendor.cpp.o):(.data.rel.ro._ZTIN12_GLOBAL__N_125StoringDiagnosticConsumerE+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
lib64/liblldbPluginExpressionParserClang.a(ASTResultSynthesizer.cpp.o):(.data.rel.ro._ZTIN12lldb_private20ASTResultSynthesizerE[_ZTIN12lldb_private20ASTResultSynthesizerE]+0x10): undefined reference to `typeinfo for clang::SemaConsumer'
lib64/liblldbPluginExpressionParserClang.a(ASTStructExtractor.cpp.o):(.data.rel.ro._ZTIN12lldb_private18ASTStructExtractorE[_ZTIN12lldb_private18ASTStructExtractorE]+0x10): undefined reference to `typeinfo for clang::SemaConsumer'
lib64/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTIN12lldb_private21ClangExpressionParser25LLDBPreprocessorCallbacksE[_ZTIN12lldb_private21ClangExpressionParser25LLDBPreprocessorCallbacksE]+0x10): undefined reference to `typeinfo for clang::PPCallbacks'
lib64/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTI29ClangDiagnosticManagerAdapter[_ZTI29ClangDiagnosticManagerAdapter]+0x10): undefined reference to `typeinfo for clang::DiagnosticConsumer'
lib64/liblldbPluginExpressionParserClang.a(ClangExpressionParser.cpp.o):(.data.rel.ro._ZTIZN12lldb_private21ClangExpressionParser17RewriteExpressionERNS_17DiagnosticManagerEE16RewritesReceiver+0x10): undefined reference to `typeinfo for clang::edit::EditsReceiver'
lib64/liblldbSymbol.a(ClangExternalASTSourceCommon.cpp.o):(.data.rel.ro._ZTIN12lldb_private28ClangExternalASTSourceCommonE[_ZTIN12lldb_private28ClangExternalASTSourceCommonE]+0x10): undefined reference to `typeinfo for clang::ExternalASTSource'
collect2: error: ld returned 1 exit status
```

Any idea what could be happening? The classes are obviously declared in headers. Tried building clang as static and shared libs, same issue in both cases.

Also @SoapGentoo maybe?

[lldb-log.txt](https://github.com/gentoo/gentoo/files/548577/lldb-log.txt)

**Comment by mgorny** [comment]
Ok, figured out what the issue is. We're explicitly enabling RTTI in LLVM (why?) which doesn't match upstream defaults. Now, it seems that other LLVM projects fail to check that. For some reason, clang is built with `-fno-rtti` but LLDB without. You can guess the result.

I'm going to try to patch this upstream.

**Comment by SoapGentoo** [comment]
what's upstreams rationale for building without RTTI? I know GCC also builds without RTTI, but they don't have a lot of LLVM-like interdependencies.

**Comment by mgorny** [comment]
@SoapGentoo, ask upstream. I don't really have the time to figure all this out. I've already lost an hour on this.

**Comment by mgorny** [comment]
724c2d913874778d6527b9200c9be679215fbfcf fixed it. Now to lot of direct LLDB issues…

**Pull request closed without merging**
