### PR TITLE
sys-process/atop: systemd support

### PR DESCRIPTION
**Pull request by den4ix**
https://bugs.gentoo.org/show_bug.cgi?id=553310

Package-Manager: portage-2.2.20.1

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/base-system

**Comment by mgorny** [comment]
Not saying i like running stuff from /etc but there irrelevant.

**Comment by monsieurp** [comment]
Dear @mgorny and @gentoo/base-system folks, is someone working towards merging this PR at some point? It's been on hold for months. I suggest closing it if you're not interested.

**Comment by den4ix** [comment]
sorry, I submitted this patch while was working with systemd for quite a bit, since then I moved back to openrc, so can't work on it anymore.

**Comment by floppym** [comment]
I don't know how this software is supposed to work, so I cannot provide any useful review here.

If these are indeed units as shipped by upstream, I suppose it is fine to install them.

**Pull request merged**
