### PR TITLE
mail-client/roundcube: Don't depend on dev-lang/php[crypt]

### PR DESCRIPTION
**Pull request by candrews**
The crypt use flag was removed in dev-lang/php-7.2 and roundcube doesn't use it

Closes: https://bugs.gentoo.org/639394
Package-Manager: Portage-2.3.16, Repoman-2.3.6

### CODE REVIEW

**Comment by titanofold** [comment]
I don't think this requires a revbump. It hasn't been stabled on any arch, and it doesn't really affect the outcome. Additionally, 7.2 is still masked.

It is only preventing the emerge of a masked package rather than producing something broken.

I vote we just edit it in place.

**Comment by candrews** [comment]
> I don't think this requires a revbump. It hasn't been stabled on any arch, and it doesn't really affect the outcome. Additionally, 7.2 is still masked.

According to https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html I believe this change does require a revbump. And the devmanual doesn't provide any exceptions regarded arch stabilization status or masking.

> 
> It is only preventing the emerge of a masked package rather than producing something broken.
> 
7.2 is ~keyworded, but it isn't hard masked.

> I vote we just edit it in place.

Imagine this scenario:
User has php 7.1, emerges mail-client/roundcube-1.3.3 (before this change), everything is great. They then update the portage tree, and they get the new mail-client/roundcube-1.3.3 ebuild. They try to upgrade to php 7.2, but are blocked because php 7.1 doesn't have the crypt use flag. They're mystified... how do they solve this problem? Portage won't tell them that mail-client/roundcube-1.3.3 needs to re-emerged to get the change that would fix their problem.

**Comment by candrews** [comment]
I'll merge this (probably) tomorrow unless there are objections.

**Comment by titanofold** [comment]
I replied to you in IRC, but you must have missed it. I'm sorry it took so long. My original response was typed up at work, and apparently I didn't click on comment.

> According to https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html I believe this change does require a revbump. And the devmanual doesn't provide any exceptions regarded arch stabilization status or masking.

Thank you for the reference. However, it isn't exhaustive in its examples, but provides us a guide. Obviously, I think this particular situation is a gray area.

> 7.2 is ~keyworded, but it isn't hard masked.

My machine was a few (a lot) hours out of date, and I hadn't realized the mask was lifted.

> Imagine this scenario:
> User has php 7.1, emerges mail-client/roundcube-1.3.3 (before this change), everything is great. They then update the portage tree, and they get the new mail-client/roundcube-1.3.3 ebuild. They try to upgrade to php 7.2, but are blocked because php 7.1 doesn't have the crypt use flag. They're mystified... how do they solve this problem? Portage won't tell them that mail-client/roundcube-1.3.3 needs to re-emerged to get the change that would fix their problem.

My concern is that we're communicating that something greater than a dependency correction is involved with this revision bump. There's more to updating roundcube than a simple emerge. We're asking admins to update all their webapp sites with it. I think the fastest update I've done took me about 10 minutes, but I'm the only user and it doesn't matter if it fails for me. Others are probably a bit more detailed about it.

This is why I'm favoring edit-in-place over revbump. We're asking for admins to do a lot of work for, essentially, zero benefit with the revbump.

Other than a clear commit message that may be missed, I don't know if there's an appropriate means for us to communicate that a webapp update isn't necessary for those moving from 1.3.3 to 1.3.3-r1.

**Comment by candrews** [comment]
19b244aeb7fe3eba32a301d329091c065ea1c750

**Pull request closed without merging**
