### PR TITLE
acct-{group,user}/netbox: drop residual packages

### PR DESCRIPTION
**Pull request by scardracs**
Closes: https://bugs.gentoo.org/793272

Removing also tablib and markuppy as they were libraries for netbox
Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Marco Scardovi marco@scardovi.com

### CODE REVIEW

**Comment by thesamesam** [comment]
See the blocker bug, we’re not clear that we want to do this yet.

**Comment by juippis** [comment]
+ we need to go through the proper last-rite prodecure before removing packages from tree ;)

https://devmanual.gentoo.org/ebuild-maintenance/removal/index.html#removing-a-package
for markuppy and tablib. 

I'll be back in the morning and we can continue then!

**Review by juippis — APPROVED** [review]
Cherry-picking the 2nd commit.

**Comment by juippis** [comment]
Please send the last-rites message to gentoo-dev next - you can find multiple examples.

**Comment by scardracs** [comment]
> Please send the last-rites message to gentoo-dev next - you can find multiple examples.

Done, thanks :)

**Pull request closed without merging**
