### PR TITLE
profiles/prefix: Split clang-lld feature into two

### PR DESCRIPTION
**Pull request by DarthGandalf**
Generic prefix parent has to override LDFLAGS from clang feature, because they are not compatible otherwise, but it brings sys-devel/binutils-apple which doesn't work on the clang prefix.

Bug: https://bugs.gentoo.org/758167

### CODE REVIEW

**Comment by DarthGandalf** [comment]
@grobian

**Comment by grobian** [comment]
I don't understand this -1 and -2, you say you need to override something, but can't you just negate that?

**Comment by DarthGandalf** [comment]
Among all the other useful things, profiles/features/llvm/make.defaults adds `-Wl,--as-needed` to LDFLAGS, which doesn't work on Mac. profiles/prefix/darwin/make.defaults sets LDFLAGS to `-Wl,-dead_strip_dylibs` ignoring previous value of LDFLAGS, fixing that, so it has to go after the  profiles/features/llvm.

I can change their order, but I don't want to repeat the LDFLAGS line from profiles/prefix/darwin/make.defaults in every profiles/prefix/darwin/macos/NN.NN/

**Comment by DarthGandalf** [comment]
@grobian do you prefer #35260 instead or some other approach?

**Comment by grobian** [comment]
yes let's do the re-definition approach from https://github.com/gentoo/gentoo/pull/35260

**Pull request closed without merging**
