### PR TITLE
dev-db/redis: add 7.4.0

### PR DESCRIPTION
**Pull request by hydrapolic**
USE=jemalloc is broken:
```
=== REDIS BUG REPORT START: Cut & paste starting from here ===
29834:M 14 Aug 2024 11:56:10.459 # === ASSERTION FAILED ===
29834:M 14 Aug 2024 11:56:10.459 # ==> zmalloc.c:684 '!je_mallctl(buf, &curregs, &sz, NULL, 0)' is not true

------ STACK TRACE ------

29841 bio_aof
/lib64/libc.so.6(+0x85b9e) [0x7fc889410b9e]
/lib64/libc.so.6(pthread_cond_wait+0x21d) [0x7fc88941340d]
/usr/sbin/redis-server 0.0.0.0:6379(bioProcessBackgroundJobs+0x1bd) [0x556fa63d99ed]
/lib64/libc.so.6(+0x891c9) [0x7fc8894141c9]
/lib64/libc.so.6(+0x10407c) [0x7fc88948f07c]

29840 bio_close_file
/lib64/libc.so.6(+0x85b9e) [0x7fc889410b9e]
/lib64/libc.so.6(pthread_cond_wait+0x21d) [0x7fc88941340d]
/usr/sbin/redis-server 0.0.0.0:6379(bioProcessBackgroundJobs+0x1bd) [0x556fa63d99ed]
/lib64/libc.so.6(+0x891c9) [0x7fc8894141c9]
/lib64/libc.so.6(+0x10407c) [0x7fc88948f07c]

29842 bio_lazy_free
/lib64/libc.so.6(+0x85b9e) [0x7fc889410b9e]
/lib64/libc.so.6(pthread_cond_wait+0x21d) [0x7fc88941340d]
/usr/sbin/redis-server 0.0.0.0:6379(bioProcessBackgroundJobs+0x1bd) [0x556fa63d99ed]
/lib64/libc.so.6(+0x891c9) [0x7fc8894141c9]
/lib64/libc.so.6(+0x10407c) [0x7fc88948f07c]

29834 redis-server *
/usr/sbin/redis-server 0.0.0.0:6379(zmalloc_get_frag_smallbins_by_arena+0x238) [0x556fa635bac8]
/usr/sbin/redis-server 0.0.0.0:6379(zmalloc_get_allocator_info+0x155) [0x556fa635bc95]
/usr/sbin/redis-server 0.0.0.0:6379(cronUpdateMemoryStats+0x87) [0x556fa634a767]
/usr/sbin/redis-server 0.0.0.0:6379(serverCron+0x41c) [0x556fa634f97c]
/usr/sbin/redis-server 0.0.0.0:6379(+0x4a3d8) [0x556fa633d3d8]
/usr/sbin/redis-server 0.0.0.0:6379(aeMain+0x1d) [0x556fa633ddcd]
/usr/sbin/redis-server 0.0.0.0:6379(main+0x348) [0x556fa63390c8]
/lib64/libc.so.6(+0x25dbe) [0x7fc8893b0dbe]
/lib64/libc.so.6(__libc_start_main+0x89) [0x7fc8893b0e79]
/usr/sbin/redis-server 0.0.0.0:6379(_start+0x25) [0x556fa6339725]

4/4 expected stacktraces.

------ STACK TRACE DONE ------
```

Some test failures:
```
!!! WARNING The following tests failed:

*** [err]: Test Command propagated to replica as expected (listpack) in tests/unit/type/hash-field-expire.tcl
Expected 'hdel h1 f1' to match 'hpexpireat h2 * FIELDS 1 f1' (context: type source line 971 file /var/tmp/portage/dev-db/redis-7.4.0/work/redis-7.4.0/tests/support/util.tcl cmd {assert_match [lindex $patterns $j] [read_from_aof $fp]} proc
 ::assert_aof_content level 1) 
*** [err]: Test Command propagated to replica as expected (ht) in tests/unit/type/hash-field-expire.tcl
Expected 'hdel h1 f1' to match 'hset h2 f1 v1 f2 v2 f3 v3 f4 v4' (context: type source line 971 file /var/tmp/portage/dev-db/redis-7.4.0/work/redis-7.4.0/tests/support/util.tcl cmd {assert_match [lindex $patterns $j] [read_from_aof $fp]} 
proc ::assert_aof_content level 1) 
```

When installed without jemalloc, redis-benchmark passed on my box, tried putting on a testing machine, seems that it works.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by arkamar** [comment]
The `jemalloc` issue is there since commit https://github.com/redis/redis/commit/f6785df663928d6614030e93aaeafa4a3b24ae3f which was created in PR https://github.com/redis/redis/pull/12996.

**Comment by arkamar** [comment]
The `jemalloc` issue disappears when `USE=stats` is set for `jemalloc`.

**Comment by arkamar** [comment]
ah, it makes sense, `stats.arenas.%u.bins.%u.curregs` is available only if `jemalloc` is configured with `stats` enabled, see https://jemalloc.net/jemalloc.3.html. And here is related part in redis code https://github.com/redis/redis/blob/c9d29f6a918c335bc1778d9f68e521c1bbb36a0f/src/zmalloc.c#L681-L684

**Comment by hydrapolic** [comment]
Thanks @arkamar :)

**Pull request closed without merging**
