### PR TITLE
media-video/ffmpeg: Add USE flag for sofalizer filter'

### PR DESCRIPTION
**Pull request by fhlfibh**
media-video/ffmpeg: Add USE flag for sofalizer filter'

### CODE REVIEW

**Comment by aballier** [comment]
repoman says:
```
  IUSE.invalid [fatal]          1
   media-video/ffmpeg/ffmpeg-9999.ebuild: sofalizer
```

(please fill the description in metadata.xml)

Also, when you rebase, please use 'media-video/ffmpeg: Add USE flag for sofalizer filter' as commit message

**Comment by fhlfibh** [comment]
Added USE flag description, and changed commit's message.
I don't know how to rebase and squash, sorry...

**Comment by aballier** [comment]
just use 'git rebase -i origin/master' (or what your remote is called) and see the doc in there; you can squash easily


'git commit --amend' lets you change easily the commit message


then push --force to your branch and be done

**Comment by fhlfibh** [comment]
Please don't merge this pull-request, I will close it and make the new one, from the beginning.

**Comment by fhlfibh** [comment]
The new one https://github.com/gentoo/gentoo/pull/3669

**Pull request closed without merging**
