### PR TITLE
sys-fs/zfs{,-kmod}: update to 2.2.5

### PR DESCRIPTION
**Pull request by BluCobalt**
Bump version of `sys-fs/zfs` and `sys-fs/zfs-kmod` to 2.2.5.

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by BluCobalt** [comment]
I'm not really sure how to run `pkgcheck scan --commits --net`, as mentioned by the above checklist..... it just errors for me: https://bpa.st/GCRA

**Comment by thesamesam** [comment]
One commit per package please (same PR is fine).

As for the crash you had:
```
  PythonCompatUpdate: version 9999: PYTHON_COMPAT update available: python3_13
pkgcheck scan: error: Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/addons/git.py", line 173, in changes
    changes = deque(next(self.git_log).strip("\x00").split("\x00"))
                    ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/addons/git.py", line 135, in __next__
    raise StopIteration
StopIteration

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/pkgcheck/pipeline.py", line 237, in _run
    if results := tuple(runner.run(restriction)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/pkgcheck/runners.py", line 68, in run
    for item in self.source.itermatch(restrict):
  File "/usr/lib/python3.12/site-packages/pkgcheck/sources.py", line 37, in itermatch
    yield from self.source
  File "/usr/lib/python3.12/site-packages/pkgcheck/addons/git.py", line 217, in __next__
    for status, atoms in self.changes:
RuntimeError: generator raised StopIteration
```

File a pkgcheck bug? It might be confused by the braces though in the commit msg.

**Comment by BluCobalt** [comment]
I'm not terribly sure how to separate each package into one commit. Can I do that with the pr already created?

**Comment by thesamesam** [comment]
```
git reset HEAD~1 # no --hard here
cd sys-fs/zfs
pkgdev commit
cd ../..
cd sys-fs/zfs-kmod
pkgdev commit
git push -f # force-pushes are fine to branches used for PRs
```

**Comment by MatthewGentoo** [comment]
I think it could be good to bump `MODULES_KERNEL_MAX` in the live ebuild too

**Comment by thesamesam** [comment]
You seem to have changed lots of the formatting in the ebuild. I'll fix it up on merge but please be careful about that in future (looks like maybe tabs got converted to spaces?)

**Comment by thesamesam** [comment]
I'm going to wire up `--with-libunwind` too (noticed with `pkgdiff-mg ...`).

**Comment by BluCobalt** [comment]
> You seem to have changed lots of the formatting in the ebuild. I'll fix it up on merge but please be careful about that in future (looks like maybe tabs got converted to spaces?)

Ah, sorry. I originally added the new versions through GitHub web so I suspect that that's why   it got changed. Thank you for catching it ;)

**Pull request closed without merging**
