### PR TITLE
sys-cluster/mpich: Enable fortran for multilib and version bump to 3.3

### PR DESCRIPTION
**Pull request by swordencao**
* The `multilib-native-use-enable fortran` conflicts with the fortran removal part of the patch (bug 540508), so re-enable the `fortran` flag and therefore the patch works.
* Version bumps to 3.3.

Closes: https://bugs.gentoo.org/680236
Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Jian Cao sworden.cao@gmail.com

### CODE REVIEW

**Comment by swordencao** [comment]
Use `>=hwloc-2.0.2` due to macros broken in `=hwloc1.11.2-r1`.

**Comment by jsbronder** [comment]
- When bumping the version, the keywords should all go back to testing (repoman would have warned you about this).  Fixing this will remove the requirement to stabilize hwloc-2.0.2
```
  KEYWORDS.stable [fatal]       1
   sys-cluster/mpich/mpich-3.3.ebuild added with stable keywords: amd64 hppa ppc ppc64 x86
```

- Stabilization is typically done by the arch teams after a package has been in the tree for a while, see https://wiki.gentoo.org/wiki/Stable_request

- Did you verify that multilib still works with the fortran flag enabled/disable?  That is making sure you're building mpich (and deps) for both `abi_x86_32` and `abi_x86_64`

**Comment by swordencao** [comment]
Yes, multilib works for `fortran` flag and both `abi_x86_32` and `abi_x86_64` compiled and installed as expected.

**Comment by jsbronder** [comment]
Great.  Mind squashing this down to just 2 commits?
- One for fixing fortran
- One for the version bump

**Comment by swordencao** [comment]
Pushed these commits. Thanks Justin;)

**Comment by jsbronder** [comment]
I'm getting errors similar to those for openmpi (https://bugs.gentoo.org/671510) with x86_32 enabled:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib64/libhwloc.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib64/libhwloc.so: error adding symbols: File in wrong format
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1391: hydra_nameserver] Error 1
make[3]: *** Waiting for unfinished jobs....
make[3]: *** [Makefile:1398: hydra_persist] Error 1
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib64/libhwloc.so: error adding symbols: File in wrong format
```
Are you seeing this with both 64 and 32 bit builds enabled?  The appropriate files for hwloc do appear to be installed:
```
/usr/lib32/libhwloc.la
/usr/lib32/libhwloc.so
/usr/lib32/libhwloc.so.15
/usr/lib32/libhwloc.so.15.0.1
/usr/lib32/pkgconfig
/usr/lib32/pkgconfig/hwloc.pc
```
So I'm not sure if this is my setup or something else.

**Comment by swordencao** [comment]
* Getting this error after bumping version to 3.3 and I found a lot of library paths not respecting to multilib so I create a patch to fix them.
* For bug 671510 see my another PR https://github.com/gentoo/sci/pull/910.

**Comment by jsbronder** [comment]
Still seeing lib64 getting picked up:
```
$ ebuild mpich-3.3.ebuild install
...
libtool: link: x86_64-pc-linux-gnu-gcc -m32 -O2 -pipe -march=native -O0 -g -o hydra_pmi_proxy pm/pmiserv/hydra_pmi_proxy-pmip.o pm/pmiserv/hydra_pmi_proxy-pmip_cb.o pm/pmiserv/hydra_pmi_proxy-pmip_utils.o pm/pmiserv/hydra_pmi_proxy-pmip_pmi_v1.o pm/pmiserv/hydra_pmi_proxy-pmip_pmi_v2.o pm/pmiserv/hydra_pmi_proxy-common.o pm/pmiserv/hydra_pmi_proxy-pmi_v2_common.o  -L. -L/usr/lib64 -L/usr/lib /var/tmp/portage/sys-cluster/mpich-3.3/work/mpich-3.3-abi_x86_32.x86/src/pm/hydra/.libs/libhydra.a mpl/.libs/libmpl.a -lpthread /usr/lib64/libhwloc.so -lm -ludev -lpciaccess -lOpenCL
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libhwloc.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1391: hydra_nameserver] Error 1
make[3]: *** Waiting for unfinished jobs....
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libhwloc.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:1398: hydra_persist] Error 1
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib64/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.so when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: skipping incompatible /usr/lib/libpthread.a when searching for -lpthread
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: /usr/lib64/libhwloc.so: error adding symbols: file in wrong format
collect2: error: ld returned 1 exit status
```

**Comment by swordencao** [comment]
Missed `eautoreconf` for generating configure files in sub-directories, should work now ;)

**Comment by jsbronder** [comment]
Great work!  Merged.
```
f12adbee3cb0 sys-cluster/mpich: Version bump to 3.3
749d4bc2ae7b sys-cluster/mpich: Enable fortran for multilib
```

**Comment by pavanbalaji** [comment]
Thanks, @jsbronder.  This will be a good thing to fix upstream.  Would you be able to create a PR for upstream mpich (https://github.com/pmodels/mpich)?  Please note a few things:

1. The current code searches for `lib64` and if it doesn't find it, it'll use `lib`.  Having a separate configure option for it is hardcoding either `lib64` or `lib`.  I think that should be a priority order instead, i.e., one of `lib64,lib`, `lib,lib64`, `lib64` or `lib`.

2. Some of the macros are used for multiple libraries.  Changing `--with-prefix-libdir` changes the libdir for all of them, isn't it?

3. The changes to `libfabric` need to be upstreamed to `libfabric`, not to `mpich`.

**Comment by jsbronder** [comment]
I just merged it, the work was all done by @swordencao

**Comment by swordencao** [comment]
Thanks for suggestion @pavanbalaji, I'm working on it and will create PR for `mpich` and `libfabric`.

**Pull request closed without merging**
