### PR TITLE
media-video/mkvtoolnix-48.0.0-r1 add dbus USE flag

### PR DESCRIPTION
**Pull request by jeandestouches**
(First pull request, hopefully I got it right)
When qt5 USE flag is enabled, it pulls qtdbus which depends on dbus.
qtdbus isn't needed to execute mkvtoolnix gui when qtdbus/dbus is not installed, it works just fine.

So, this change adds a dbus flag (within qt5 USE)
And also adds a small little patch to undef qtdbus when dbus USE flag is disabled. (Needed to allow compilation on a system without qtdbus) See this thread for reference : https://forums.gentoo.org/viewtopic-t-1101168.html

--- 1/configure   2019-03-07 12:52:33.594252613 -0600
+++ 2/configure   2019-03-07 12:57:28.576229245 -0600
@@ -9287,7 +9287,7 @@
   with_qt_pkg_config_modules="$with_qt_pkg_config_modules,Qt5DBus"
 fi
 
-$as_echo "#define HAVE_QTDBUS 1" >>confdefs.h
+$as_echo "#undef HAVE_QTDBUS" >>confdefs.h
 
     fi

### CODE REVIEW

**Comment by a17r** [comment]
Is this patch upstream or in the process of being upstreamed? The fact that it is a conditional patch indicates it is not upstreamable, and Gentoo can't accept it.

**Comment by jeandestouches** [comment]
> Is this patch upstream or in the process of being upstreamed? The fact that it is a conditional patch indicates it is not upstreamable, and Gentoo can't accept it.

It isn't. I opened a bug on mkvtoolnix : https://gitlab.com/mbunkus/mkvtoolnix/-/issues/2886
mkvtoolnix's dev is willing to integrate a patch if someone's comes up with one. Unfortunately I lack the knowledge to do it myself.
Since the patch is quite small and only undef QTDBUS when user builds it with USE="-dbus", I've thought it could be acceptable. If it is not, my bad.

**Comment by a17r** [comment]
> Maybe then, only commit [a1a03d4](https://github.com/gentoo/gentoo/commit/a1a03d42b331ba72c6e12af630d09f5a9d124542) (add dbus USE flag) could be accepted since it doesn't use the patch & src_prepare "epatch"

This would effectively introduce build system automagic to Gentoo ebuilds which is unacceptable. If `sys-apps/dbus` is installed, your ebuild would link to it no matter what the status of USE=dbus is. If the flag has no according build system switch it can not be added.

**Comment by jeandestouches** [comment]
> This would effectively introduce build system automagic to Gentoo ebuilds which is unacceptable. If `sys-apps/dbus` is installed, your ebuild would link to it no matter what the status of USE=dbus is. If the flag has no according build system switch it can not be added.
I see so this need to be solved upstream. Well, I will close that pull request then.

**Pull request closed without merging**
