### PR TITLE
dev-go/go-bindata: bump to 1.0.0

### PR DESCRIPTION
**Pull request by hydrapolic**
Closes: https://bugs.gentoo.org/676102
Closes: https://bugs.gentoo.org/680734

Signed-off-by: Tomáš Mózes <hydrapolic@gmail.com>

### CODE REVIEW

**Comment by Dessa** [comment]
wait. *another* go-bindata fork? (refs. https://github.com/Dr-Terrible/go-overlay/issues/76 )
though, going for the least invasive bump (which this one seems to be?) is probably a better idea; its food for thought anyway.

**Comment by hydrapolic** [comment]
Yes, it's a mess, I agree.

I tried some the other forks, but for example gitea failed to build, it hang on gofmt. Suggestions are welcome of course, if we want some other fork for example.

**Comment by hydrapolic** [comment]
Thanks @mgorny

**Comment by stikonas** [comment]
This pull request dropped ~arm64 keywords

**Comment by hydrapolic** [comment]
@stikonas, this PR was opened before ~arm64 was added.

**Pull request closed without merging**
