### PR TITLE
mail-filter/opendkim: Added query_cache and stats USE flags

### PR DESCRIPTION
**Pull request by rseichter**
Added new USE flags `query_cache` to enable query caching and `stats` to enable statistics. In previous ebuild versions, these features were always enabled.

### CODE REVIEW

**Comment by rseichter** [comment]
> https://qa-reports.gentoo.org/output/gentoo-ci/fcb0042/output.html#mail-filter/opendkim

@orlitzky Looks like this ebuild causes issues related to OpenDBX and ARM profiles. I have no experience with Gentoo on ARM, and I was wondering if you might have some advice?

**Comment by orlitzky** [comment]
The `opendbx` flag is masked for OpenDKIM on ARM. You can find the following in the ::gentoo repo in `profiles/arch/arm/package.use.mask`:

```
# Markus Meier <maekke@gentoo.org> (04 May 2014)
# Unkeyworded deps, bug #509082
mail-filter/opendkim opendbx
```

Since your new `stats` flag requires `opendbx`, you should mask `stats` there too. Otherwise people who enable `USE=stats` on ARM will have a USE-dependency they can't satisfy.

**Comment by rseichter** [comment]
Thanks for the pointer. I have updated the mask file. I usually squash my commits, but in this case I deliberately left them separate for now. I hope that's correct?

**Comment by orlitzky** [comment]
Yeah, that's right. But two days ago someone went through that file and changed all of the date formats, so now your patch doesn't apply (and it would use a different date format). Can you please update it to use YYYY-MM-DD and rebase it? Sorry for the hassle.

**Comment by rseichter** [comment]
I've pushed again, with `profiles/arch/arm/package.use.mask` based on the current master branch's version.

**Comment by orlitzky** [comment]
Something is still weird with the second patch, it's trying to change all of the dates again.

**Comment by rseichter** [comment]
Is that not to be expected? I created this branch before all the dates were changed.

**Comment by orlitzky** [comment]
The changes still need to be there, but they shouldn't be in _your_ commit. I have to apply the patch https://github.com/gentoo/gentoo/pull/12353/commits/ee13c1ccc087b39321a9b5f178ffd4b91250cefe on top of gentoo/master, so it's going to fail trying to re-make all of those date changes. (I could apply it to the tree from a week ago, but then I can't push, because the real tree only accepts fast-forwards). I think your opendkim-190629 branch needs to be rebased on top of gentoo/master; then the pull request should show only the date change relevant to the opendkim mask.

**Comment by rseichter** [comment]
Apparently I have made things worse by trying to make them better. This merge request seems pretty much screwed now. ☹️

**Comment by orlitzky** [comment]
Thanks, it applies now =)

This pattern is so common,

```bash
if use stats; then
	myconf+=( --enable-stats )
fi
```

that we have a dedicated helper function for it. Instead, you can add it directly to the `econf` call a little bit later with

```bash
econf \
	...
	$(use_enable stats) \
	...       
```

You can do the same thing with the `querycache` flag. Since that USE flag name isn't exactly the same as the configure flag, you have two options:

1. Change the flag name to contain an underscore, or
2. Pass the extra option to use_enable, e.g. `$(use_enable querycache query_cache)`

Finally, why enable querycache and berkdb by default? Thanks to that include-dir bug, know that nobody was using it, so `USE=berkdb` by default will pull in some extra unused dependencies on most peoples' machines unless they mask that flag for opendkim.

**Comment by rseichter** [comment]
> Finally, why enable querycache and berkdb by default?

The `berkdb` flag was already enabled in -r15, so I thought that if this dependency is pulled in by default anyway, why not enable `query_cache` as well? I have now disabled both USE flags.

**Comment by orlitzky** [comment]
Oh I didn't realize berkdb was already defaulted on. The test suite has started failing for me again, but I don't think it's related to any recent changes (-r8 fails too). Pulled and merged. Thanks!

**Pull request closed without merging**
