### PR TITLE
package.mask: Last-rite split gtk-sharp and gnome-sharp packages

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/dotnet

**Comment by mpkh** [comment]
@mgorny LGTM, related bug https://bugs.gentoo.org/show_bug.cgi?id=619182

**Comment by mgorny** [comment]
Sadly, this doesn't include any of the packages listed in that bug. It seems that they aren't included in those two combined packages. And most of them have a single revdep.

**Comment by mpkh** [comment]
@mgorny ahm... yes, you're right.

**Pull request closed without merging**
