### PR TITLE
lighttpd.initd changes

### PR DESCRIPTION
**Pull request by alexkapshuk**

### CODE REVIEW

**Comment by hwoarang** [comment]
This pull request needs improvement

First of all, please fix up the history. There is no reason for the `Merge pull request #1 from alexkapshuk/alexkapshuk-patch-1` commit there. Please rebase your branch properly

Second of all, you make a change to an ebuild file so you need to submit a new revision of the ebuild otherwise people will not get your new changes

**Comment by alexkapshuk** [comment]
I've rebased my branch as you suggested, which resulted in my previous commit being reverted, if I read this correctly.
You said I modified an ebuild. As far as I'm aware, my patch concerns file lighttpd.initd, not an ebuild.
Can you please elaborate on that a bit more? 
Thanks.

**Comment by hwoarang** [comment]
I am sorry this is still not correct. You are now asking me to pull 3 commits instead of one which would be the ideal scenario. Sounds like you need to do some reading on git. Overall, it's best if you start fresh, fork the repo, create a new branch, apply and commit your patch and then send your pull request. But please do some reading about Git.

You have modified an init script and as per the Gentoo policy, if you modify any of the installed files you need to commit a new revision of the ebuild so users will be forced to update and get your new changes. If you don't, nobody who already has lighttpd installed will get your changes.

**Comment by alexkapshuk** [comment]
Thanks for your response and for being patient with me. I am new to github. I'll go ahead and do some homework as you suggested.

**Comment by mgorny** [comment]
@hwoarang, does his first commit look fine to you? If so, we can just cherry-pick it.

**Comment by monsieurp** [comment]
Thank you for your work. @hwoarang is apparently not interested in merging your contribution. Let's close this PR.

**Pull request closed without merging**
