### PR TITLE
games-strategy/ja2-stracciatella: add 0.21.0, drop 0.20.0

### PR DESCRIPTION
**Pull request by misanthropos**

### CODE REVIEW

**Comment by Flowdalic** [comment]
Should we maybe keep 0.20.0 and stabilize it?

**Comment by Flowdalic** [comment]
> > Should we maybe keep 0.20.0 and stabilize it?

Note that I leave it to the discretion of the package maintainer whether or not to stabilize a version. I just wondered if there is a reason to not stabilize 0.20, especially since we have no stable version right now for this package. If you feel that this version isn't ready, then that is fine. However,
 
> According to https://ja2-stracciatella.github.io/news/ : Through 340 commits at least 44 bugs were fixed, 23 of which are known to affect vanilla.

Are there any serious bugs fixed? Is 0.20 unplayable?

> Also development is continuing and people should not run into and report resolved bugs.

If this where an argument against stabilization, then we could hardly stabilize packages ever.

```
 * ERROR: games-strategy/ja2-stracciatella-0.21.0::gentoo failed (prepare phase):
 *   patch -p1  failed with /data-scratch/var-tmp/portage/games-strategy/ja2-stracciatella-0.21.0/files/ja2-stracciatella-0.20.0-lua-cmake.patch
 ```

```
rename from games-strategy/ja2-stracciatella/files/ja2-stracciatella-0.20.0-lua-cmake.patch
rename to games-strategy/ja2-stracciatella/files/ja2-stracciatella-0.21.0-lua-cmake.patch
```

There is no need to rename the patch if it is identical. Please drop the rename from the commit and check that the submitted ebuild is functional.

**Comment by misanthropos** [comment]
> Note that I leave it to the discretion of the package maintainer whether or not to stabilize a version. I just wondered if there is a reason to not stabilize 0.20, especially since we have no stable version right now for this package. If you feel that this version isn't ready, then that is fine. However,
> 
> > According to https://ja2-stracciatella.github.io/news/ : Through 340 commits at least 44 bugs were fixed, 23 of which are known to affect vanilla.
> 
> Are there any serious bugs fixed? Is 0.20 unplayable?

0.20.0 is playable. Many bugs are special cases one runs into during a campaign and are better avoided because they can be quite frustrating.

> 
> > Also development is continuing and people should not run into and report resolved bugs.
> 
> If this where an argument against stabilization, then we could hardly stabilize packages ever.
> 

I misunderstood "stabilization". But one thing which keeps me from that is I have no clue how tests are supposed to work. I need to put time into that and frankly have not found the muse to do that.

> That aside, the 0.21.0 ebuild does not work:
> 
> ```
>  * ERROR: games-strategy/ja2-stracciatella-0.21.0::gentoo failed (prepare phase):
>  *   patch -p1  failed with /data-scratch/var-tmp/portage/games-strategy/ja2-stracciatella-0.21.0/files/ja2-stracciatella-0.20.0-lua-cmake.patch
> ```
> 
> ```
> rename from games-strategy/ja2-stracciatella/files/ja2-stracciatella-0.20.0-lua-cmake.patch
> rename to games-strategy/ja2-stracciatella/files/ja2-stracciatella-0.21.0-lua-cmake.patch
> ```
> 
> There is no need to rename the patch if it is identical. Please drop the rename from the commit and check that the submitted ebuild is functional.

OK - my bad. I overlooked the version of patch file being fixed to 0.20.0. The ebuild should be functional otherwise.

The moment I understand the test cases I will request stabilization for ja2s.

**Comment by Flowdalic** [comment]
Plugging the testsuite into the ebuild is certainly always a good idea. But for leaf packages, especially for games, running the game and playing it would also be good enough for stabilization.

Thanks for your contribution.

**Comment by Flowdalic** [comment]
BTW, is the virtual/rust RDEPEND required? Could't it be a DEPEND instead?

**Comment by misanthropos** [comment]
> BTW, is the virtual/rust RDEPEND required? Could't it be a DEPEND instead?

DEPEND should be enough. I will take it into account.

**Pull request closed without merging**
