### PR TITLE
X11 misc/redshift python37 support

### PR DESCRIPTION
**Pull request by aidanharris**
Depends on #11041

### CODE REVIEW

**Comment by juippis** [comment]
You seem to include the pyxdg bump in here that you first referenced to other PR (11041). Aren't they exactly the same commits? 

Adding python3.7 but doing nothing else shouldn't require you to revbump a package, since it gets hit by -N anyway. (Also, there are some outdated things in your ebuilds so a fresh ebuild should address those)

**Comment by hartwork** [comment]
> (Also, there are some outdated things in your ebuilds so a fresh ebuild should address those)

I think that's asking for more than needed, in my eyes. Let's fix one thing at a time.

**Comment by hartwork** [comment]
@aidanharris I reverted the EAPI bump in redshift for a quick fix because there is no `gnome2_icon_cache_update` in EAPI 7 hence the bump would ne more work. New pull request welcome after merge.

> You seem to include the pyxdg bump in here that you first referenced to other PR (#11041). Aren't they exactly the same commits?

I think Aidan included pyxdg because Python 3.7 support there is a dependency of Python 3.7 support in redshift.

> Adding python3.7 but doing nothing else shouldn't require you to revbump a package, since it gets hit by -N anyway.

Interesting thought. I don't think it makes much of a difference for this very case. If there's a policy on that, please let me know.

**Comment by hartwork** [comment]
Merged, thank you!

**Comment by juippis** [comment]
> Interesting thought. I don't think it makes much of a difference for this very case. If there's a policy on that, please let me know.

It's in the devmanual? Also if you check what members of python project did when adding python3.7 to existing ebuilds, they didn't revbump those packages.

**Pull request closed without merging**
