### PR TITLE
net-analyzer/nagios-core: update apache define for current eselect-php

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by hydrapolic** [comment]
@orlitzky

**Comment by orlitzky** [comment]
Obviously correct, I'm in the middle of something right now but anyone feel free to merge this.

**Comment by orlitzky** [comment]
Merged, thanks!

**Comment by hydrapolic** [comment]
Thank you

**Pull request closed without merging**
