### PR TITLE
Create deluge-1.3.12.ebuild

### PR DESCRIPTION
**Pull request by PPed72**
Fixes bugs #561298, #560404, #531370

### CODE REVIEW

**Comment by mgorny** [comment]
Welcome, Paolo, and thanks for contributing to Gentoo. Before we could merge your pull request, there are some issues that need to be fixed. Are you interested in improving your ebuild skills and getting the ebuild ready for direct git merge? If so, here are a few of my observations so far:

1. bug #561298 looks irrelevant, probably a typo.
2. Bug #531370 is already worked around and left open for a better fix.
3. Your editor seems to have replaced tab indents by spaces. Please don't do that. All ebuilds are required to be tab-indented, with no space indentation or alignment. This also made diffing really hard.
4. distutils-r1 automatically adds `${PYTHON_DEPS}` to RDEPEND and DEPEND, so you don't have to do that.
5. Is setuptools really a run-time dependency? (it looks a little bit suspicious, that's why I'm asking)
6. Why are you adding shebang fixing prior to compilation? In any case, it doesn't really belong in `python_prepare_all()`, instead `python_prepare()` if at all. While this doesn't make a difference in the current ebuild, if someone enabled multi-python build in the future the code would set the shebangs incorrectly.
7. Please don't add verbosity to the setup.cfg workaround. It doesn't provide useful information to our users.
8. Please follow the best practices on git commit messages. Always start with package, i.e. `net-p2p/deluge: ...`, then state the most important changes, empty line, expand on the changes. Try to be concise yet clear. For version bumps, it's best to just say `Bump to 1.3.12` as it clearly tells user what is happening. It's usually worthwhile to mention other changes you needed to do in the commit message body. Sometimes it's nice to mention what kind of bugs/fixes there were rather than just numbers you'd have to cross-reference.

**Comment by PPed72** [comment]
In data martedì 10 novembre 2015 11:39:29, Michał Górny ha scritto:
> Welcome, Paolo, and thanks for contributing to Gentoo. Before we could merge
> your pull request, there are some issues that need to be fixed. Are you
> interested in improving your ebuild skills and getting the ebuild ready for
> direct git merge? If so, here are a few of my observations so far:
> 
> 1. bug #561298 looks irrelevant, probably a typo.

It is. I meant #561398: net-p2p/deluge-1.3.11 missing dependency: setuptools

> 2. Bug #531370 is already worked around and left open for a better fix.

OK.

> 3. Your editor seems to have replaced tab indents by spaces. Please don't do
> that. All ebuilds are required to be tab-indented, with no space
> indentation or alignment. This also made diffing really hard.

I'm sorry, I'm still learning to use github, and I didn't notice the option in 
the online editor. I'll clean it up.

> 4. distutils-r1 automatically adds `${PYTHON_DEPS}` to RDEPEND and DEPEND,
> so you don't have to do that.

I didn't know this. I just copied that from an ebuild I saw hanging around 
somewhere. I'll fix this as well.

> 5. Is setuptools really a run-time dependency?
> (it looks a little bit suspicious, that's why I'm asking)

Maybe not runtime, but it looks like it's build-time (see bug #561398 
mentioned above). I'll fix it.

> 6. Why are you adding shebang fixing prior to compilation? In any case, it
> doesn't really belong in `python_prepare_all()`, instead `python_prepare()`
> if at all. While this doesn't make a difference in the current ebuild, if
> someone enabled multi-python build in the future the code would set the
> shebangs incorrectly.

Thanks for the explanation, I'll experiment a bit, and then I'll eventually 
remove it.

> 7. Please don't add verbosity to the setup.cfg workaround. It
> doesn't provide useful information to our users.

Ok.

> 8. Please follow the best practices on git commit messages. Always start
> with package, i.e. `net-p2p/deluge: ...`, then state the most important
> changes, empty line, expand on the changes. Try to be concise yet clear. For
> version bumps, it's best to just say `Bump to 1.3.12` as it clearly tells 
> user what is happening. It's usually worthwhile to mention other changes you
> needed to do in the commit message body. Sometimes it's nice to mention what
> kind of bugs/fixes there were rather than just numbers you'd have to
> cross-reference.

Thanks again for the nice explanations. I'll try to keep them in mind.
Do you think it's better that I close this pull request and then open a new 
one with the corrections, or should I keep working in this one? I'd opt for 
the first, as it's probably cleaner, but I'm open to suggestions.

-- 
Paolo Pedroni
paolo.pedroni<at>iol.it

**Comment by mgorny** [comment]
On Wed, 11 Nov 2015 01:04:27 -0800
Paolo Pedroni <notifications@github.com> wrote:

> In data martedì 10 novembre 2015 11:39:29, Michał Górny ha scritto:
> > 3. Your editor seems to have replaced tab indents by spaces. Please don't do
> > that. All ebuilds are required to be tab-indented, with no space
> > indentation or alignment. This also made diffing really hard.  
> 
> I'm sorry, I'm still learning to use github, and I didn't notice the option in 
> the online editor. I'll clean it up.

It's actually better to use an offline editor and offline git ;-). I
never used the online editor but I'm pretty sure you're going to hit
some obstacle preventing you from further work this way. So if you're
going to be a long-time contributor, you'll definitely need to get
a good set of tools.

> > 4. distutils-r1 automatically adds `${PYTHON_DEPS}` to RDEPEND and DEPEND,
> > so you don't have to do that.  
> 
> I didn't know this. I just copied that from an ebuild I saw hanging around 
> somewhere. I'll fix this as well.

Do you happen to recall what ebuild this was? It's always good to fix
bad examples we have.

> > 6. Why are you adding shebang fixing prior to compilation? In any case, it
> > doesn't really belong in `python_prepare_all()`, instead `python_prepare()`
> > if at all. While this doesn't make a difference in the current ebuild, if
> > someone enabled multi-python build in the future the code would set the
> > shebangs incorrectly.  
> 
> Thanks for the explanation, I'll experiment a bit, and then I'll eventually 
> remove it.

I'm mostly asking because the eclass puts some effort to ensure
the correct Python version is used. There are some cases when shebang
editing is needed during build but those are rather exceptions.

> > 8. Please follow the best practices on git commit messages. Always start
> > with package, i.e. `net-p2p/deluge: ...`, then state the most important
> > changes, empty line, expand on the changes. Try to be concise yet clear. For
> > version bumps, it's best to just say `Bump to 1.3.12` as it clearly tells 
> > user what is happening. It's usually worthwhile to mention other changes you
> > needed to do in the commit message body. Sometimes it's nice to mention what
> > kind of bugs/fixes there were rather than just numbers you'd have to
> > cross-reference.  
> 
> Thanks again for the nice explanations. I'll try to keep them in mind.
> Do you think it's better that I close this pull request and then open a new 
> one with the corrections, or should I keep working in this one? I'd opt for 
> the first, as it's probably cleaner, but I'm open to suggestions.

The usual github workflow is to reuse one pull request so that
the history of changes is clearly available. Depending on your
preferences, you either add commits until the review is complete
and then do an interactive rebase to squash them into one, or replace
the current commits immediately (`git commit --amend` or interactive
rebase). In any case, you need to `git push --force` over the branch
you're using for the pull request.

-- 
Best regards,
Michał Górny
<http://dev.gentoo.org/~mgorny/>

**Comment by PPed72** [comment]
In data mercoledì 11 novembre 2015 01:26:19, Michał Górny ha scritto:
> On Wed, 11 Nov 2015 01:04:27 -0800
> 
> Paolo Pedroni <notifications@github.com> wrote:
> > In data martedì 10 novembre 2015 11:39:29, Michał Górny ha scritto:
> > > 3. Your editor seems to have replaced tab indents by spaces. Please
> > > don't do that. All ebuilds are required to be tab-indented, with no
> > > space
> > > indentation or alignment. This also made diffing really hard.
> > 
> > I'm sorry, I'm still learning to use github, and I didn't notice the
> > option in the online editor. I'll clean it up.
> 
> It's actually better to use an offline editor and offline git ;-). I
> never used the online editor but I'm pretty sure you're going to hit
> some obstacle preventing you from further work this way. So if you're
> going to be a long-time contributor, you'll definitely need to get
> a good set of tools.

I will do, in time.

> 
> > > 4. distutils-r1 automatically adds `${PYTHON_DEPS}` to RDEPEND and
> > > DEPEND,
> > > so you don't have to do that.
> > 
> > I didn't know this. I just copied that from an ebuild I saw hanging around
> > somewhere. I'll fix this as well.
> 
> Do you happen to recall what ebuild this was? It's always good to fix
> bad examples we have.

https://531370.bugs.gentoo.org/attachment.cgi?id=390730

> 
> > > 6. Why are you adding shebang fixing prior to compilation? In any case,
> > > it
> > > doesn't really belong in `python_prepare_all()`, instead
> > > `python_prepare()`
> > > if at all. While this doesn't make a difference in the current ebuild,
> > > if
> > > someone enabled multi-python build in the future the code would set the
> > > shebangs incorrectly.
> > 
> > Thanks for the explanation, I'll experiment a bit, and then I'll
> > eventually
> > remove it.
> 
> I'm mostly asking because the eclass puts some effort to ensure
> the correct Python version is used. There are some cases when shebang
> editing is needed during build but those are rather exceptions.

Now that I see, I probably lifted it from the ebuild above as well...

> The usual github workflow is to reuse one pull request so that
> the history of changes is clearly available. Depending on your
> preferences, you either add commits until the review is complete
> and then do an interactive rebase to squash them into one, or replace
> the current commits immediately (`git commit --amend` or interactive
> rebase). In any case, you need to `git push --force` over the branch
> you're using for the pull request.

Thanks, for this time I think I'll close the pull request and do it again, 
since I've lost the original branch (still learning to use github, you 
know...), for the future I'll do as you say.

Best regards.

-- 
Paolo Pedroni
paolo.pedroni<at>iol.it

**Pull request closed without merging**
