### PR TITLE
 xfce-extra/xfce4-whiskermenu-plugin: Version bumps

### PR DESCRIPTION
**Pull request by tietzc**
Package-Manager: Portage-2.3.13, Repoman-2.3.3

### CODE REVIEW

**Comment by mgorny** [comment]
Removing .po files is not a valid use case for L10N. Remove that altogether.

**Comment by tietzc** [comment]
So `src_prepare` should be simply obliterated keeping all .po files in place?

**Comment by mgorny** [comment]
Yes

**Comment by tietzc** [comment]
Done.

**Comment by tietzc** [comment]
Rebased against master in order to comply with recent manifest changes.

**Pull request closed without merging**
