### PR TITLE
dev-util/gtk-doc: Rebase to 1.32

### PR DESCRIPTION
**Pull request by zippy2**
There is new version available that solves some issues. The major
one being python3 support. In fact, all perl scripts were
converted to python so we can drop that dependency. There is on
downside to this change though, we can't split some files into
gtk-doc-am now, because we would need to drag all internal python
modules with it.

The 'highlight' feature was turned on and can't be changed at
configure time anymore (upstream commit 232698c6d21a).

Signed-off-by: Michal Privoznik <mprivozn@redhat.com>

### CODE REVIEW

**Comment by zippy2** [comment]
CC @pacho2

**Comment by mattst88** [comment]
Thanks for the contribution. It looks like another developer committed a version bump without noticing this pull request. Sorry about that :(

**Comment by zippy2** [comment]
That is okay. I need to learn what the best practice is. I was sending patches to mailing list (gentoo-dev) but that stroke a wave of resistance from some developers there. They suggested to use github (which led to another long discussion what tool to use). I understand that Gentoo is based on volunteers, I just want to learn how to increase my chances of merging a patch (being an upstream developer of libvirt project AND a Gentoo user I often post patches against app-emulation/* but these are usually ignored for quite long time).

**Comment by mattst88** [comment]
You did exactly the right thing. It was our (Gentoo Developers) fault. :(

**Pull request closed without merging**
