### PR TITLE
net-libs/c-client: clang-16 fixes; virtual/imap-c-client: treeclean

### PR DESCRIPTION
**Pull request by arkamar**
Those are two quite independent set of changes. First is fix of clang-16 related issues in `net-libs/c-client`, I decided to do a revbump because I also bumped `EAPI` to 8 among other changes. Then I noticed that `net-libs/c-client` was used only by `virtual/imap-c-client` as a last provider and this virtual was used only by `net-misc/asterisk` and `dev-lang/php`, which makes it good candidate for removal. I followed steps from [devmanual](https://devmanual.gentoo.org/ebuild-maintenance/removal/index.html#removing-a-virtual-package) and treeclean it.

### CODE REVIEW

**Comment by orlitzky** [comment]
asterisk and php will need new revisions (usually dropped to ~arch, but may be skipped in this case?) because `RDEPEND` has changed. Without new revisions, anyone who already has those packages installed will retain `virtual/imap-c-client` under `/var/db/pkg` and that can make portage go berserk after `virtual/imap-c-client` is treecleaned.

The virtual should be masked for a month before actually treecleaning it, too, as a favor to overlay maintainers.

**Comment by arkamar** [comment]
> asterisk and php will need new revisions (usually dropped to ~arch, but may be skipped in this case?) because `RDEPEND` has changed. Without new revisions, anyone who already has those packages installed will retain `virtual/imap-c-client` under `/var/db/pkg` and that can make portage go berserk after `virtual/imap-c-client` is treecleaned.

Yes, I understand that and it makes sense to me. I would do it normally, however, I have got an impression that it is not needed/wanted in this specific case, see this item from devmanual:
> - Update all ebuilds not to reference the virtual. Since there is no urgent need to remove the virtual from user systems and the resulting rebuilds would be unnecessary, do not bump ebuilds when replacing the dependency. 

I understand it in such a way, that affected packages stay installed with virtual, but when they are bumped in natural way in future (like version bump) the dependency on virtual is lost and it will be suggested for cleaning.

> The virtual should be masked for a month before actually treecleaning it, too, as a favor to overlay maintainers.

Really? I am not sure about this, see this item from devmanual:
> - If the virtual is being removed along with any of its providers, include the virtual in the last-rites mail. However, please do not include it in the `package.mask` entry as users do not need to be forced to proactively unmerge it. Instead, add it to `package.deprecated` to warn developers not to depend on it. Wait the time appropriate for the last rites. 

which I understand in such a way that it is needed to add the virtual to `package.deprecated` only if there are last-rited packages involved, but this is not the case.

**Comment by jkroonza** [comment]
> > asterisk and php will need new revisions (usually dropped to ~arch, but may be skipped in this case?) because `RDEPEND` has changed. Without new revisions, anyone who already has those packages installed will retain `virtual/imap-c-client` under `/var/db/pkg` and that can make portage go berserk after `virtual/imap-c-client` is treecleaned.
> 
> Yes, I understand that and it makes sense to me. I would do it normally, however, I have got an impression that it is not needed/wanted in this specific case, see this item from devmanual:
> 
> > * Update all ebuilds not to reference the virtual. Since there is no urgent need to remove the virtual from user systems and the resulting rebuilds would be unnecessary, do not bump ebuilds when replacing the dependency.
> 
> I understand it in such a way, that affected packages stay installed with virtual, but when they are bumped in natural way in future (like version bump) the dependency on virtual is lost and it will be suggested for cleaning.

Perfect.  I agree.  In the meantime, if the virtual is added to package.mask, users will obtain errors/warnings about having masked packages installed.  Which leads into ...

> > The virtual should be masked for a month before actually treecleaning it, too, as a favor to overlay maintainers.
> 
> Really? I am not sure about this, see this item from devmanual:
> 
> > * If the virtual is being removed along with any of its providers, include the virtual in the last-rites mail. However, please do not include it in the `package.mask` entry as users do not need to be forced to proactively unmerge it. Instead, add it to `package.deprecated` to warn developers not to depend on it. Wait the time appropriate for the last rites.
> 
> which I understand in such a way that it is needed to add the virtual to `package.deprecated` only if there are last-rited packages involved, but this is not the case.

I suspect this is a wording and/or punctuation issue, I suspect this means to say:

1.  Do not add the virtual to package.mask, add it to package.deprecated instead.
2.  If you're sending a last-rites for one of the providers, mention the virtual in that email, otherwise do not bother sending an email.

Seeing that I've not written the policy, the disclaimer that I'm a proxy-maintainer and the above is my interpretation applies :).  Furthering to this, I would probably as a courtesy send an email to gentoo-dev regardless about the deprecation.

**Comment by arkamar** [comment]
> > The virtual should be masked for a month before actually treecleaning it, too, as a favor to overlay maintainers.
>
> ...
> which I understand in such a way that it is needed to add the virtual to `package.deprecated` only if there are last-rited packages involved, but this is not the case.

Oh, I see, **overlay maintainers**, I missed that. Ok, I'll add it to `package.deprecated` instead of treeclean.

**Comment by arkamar** [comment]
FP, `virtual/imap-c-client` is declared as deprecated in `package.deprecated` list instead of tree clean.

**Comment by orlitzky** [comment]
The devmanual is wrong. If the virtual is removed while people still have it listed as a dependency in `/var/db/pkg`, portage will have trouble resolving dependencies. This has happened many times, e.g. https://archives.gentoo.org/gentoo-dev/message/64c42804eb4cf4bc7d1161a2e9222c6a

**Comment by thesamesam** [comment]
Yes, it's wrong, and I'm going to fix it.

**Comment by arkamar** [comment]
Ok, thank you for the thread and explanation, I'll do the bumps.

**Comment by arkamar** [comment]
Force push with revbumped `net-misc/asterisk` and `dev-lang/php` packages.

**Comment by thesamesam** [comment]
> Yes, it's wrong, and I'm going to fix it.

See https://github.com/gentoo/devmanual/pull/303. It's been on my list to fix for a while and I'm sorry I didn't get to it sooner.

**Comment by jkroonza** [comment]
On the topic of deprecation of (presumably virtual) packages:

Should we not rather just mark as deprecated and replace as and when normal bumps happen?  In other words, existing dependencies may remain, but no new packages (or revisions) may use the deprecated (virtual) package?  If these don't want to go away (perhaps due to infrequent releases of depending packages) then obviously we still have the option of forcing the matter by way of a revbump.  I feel (not overly strongly, so whatever) that rebuilds just for the sake of getting rid of a virtual package is a pointless rebuild, especially on larger more involved packages (php for example can take a significant amount of time to rebuild, although it's not generally hours).

**Comment by arkamar** [comment]
@jkroonza, yes you are right. And this is what devmanual says, which I find out after yet another re-reading of [Removing a virtual package](https://devmanual.gentoo.org/ebuild-maintenance/removal/#removing-a-virtual-package) section.

I will remove `net-misc/asterisk` and `dev-lang/php` revbump commits from this PR now, and give them appropriate time for natural bump (1 month?). After that period I will create new PR with `virtual/imap-c-client` treeclean and necessary revbumps of packages that didn't make it naturally.

 I should read more careful next time :) thanks everyone for helping me to clarify this workflow.

**Comment by thesamesam** [comment]
The CI "failure" is fine, as it's "just" new warnings which are intentional here.

**Comment by arkamar** [comment]
> The CI "failure" is fine, as it's "just" new warnings which are intentional here.

Thanks, I was almost about to restore previous state :)

**Comment by orlitzky** [comment]
> I will remove `net-misc/asterisk` and `dev-lang/php` revbump commits from this PR now, and give them appropriate time for natural bump (1 month?). After that period I will create new PR with `virtual/imap-c-client` treeclean and necessary revbumps of packages that didn't make it naturally.

This should also be fine. It's only two packages and a few ebuilds that are affected by the removal, so if you don't mind waiting, it will be easy to verify that the affected ebuilds all have newer versions/revisions before proceeding.

"Luckily" dev-lang/php has frequent releases to fix security issues, and they get stabilized quickly to obsolete the older ebuilds.

**Pull request closed without merging**
