### PR TITLE
app-portage/elt-patches: Move patching code to the script (early test)

### PR DESCRIPTION
**Pull request by mgorny**
Based on work of @chewi, I've attempted to move elibtoolize function to a split script in the package. Testing and review appreciated.

The code lives on eltpatch branch of elt-patches: https://gitweb.gentoo.org/proj/elt-patches.git/tree/?h=eltpatch. I've also uploaded a distfile to ease testing.

### CODE REVIEW

**Comment by mgorny** [comment]
Few notes so far:
* e-messages are not colorful for some reason, maybe it's a problem with gentoo-functions.sh;
* ewarn and friends are not logged by Portage. Maybe we want to move some of the messages to the eclass? Like double-call for eltpatch.

**Comment by mgorny** [comment]
To help reviewing:

```
--- /home/mgorny/git/gentoo/eclass/libtool.eclass	2017-04-22 09:36:40.078845869 +0200
+++ /home/mgorny/git/elt-patches/eltpatch.in	2017-04-22 09:27:18.995809518 +0200
@@ -1,29 +1,14 @@
+#!/bin/bash
 # Copyright 1999-2017 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
-# @ECLASS: libtool.eclass
-# @MAINTAINER:
-# base-system@gentoo.org
-# @BLURB: quickly update bundled libtool code
-# @DESCRIPTION:
-# This eclass patches ltmain.sh distributed with libtoolized packages with the
-# relink and portage patch among others
-#
-# Note, this eclass does not require libtool as it only applies patches to
-# generated libtool files.  We do not run the libtoolize program because that
-# requires a regeneration of the main autotool files in order to work properly.
-
-if [[ -z ${_LIBTOOL_ECLASS} ]]; then
-_LIBTOOL_ECLASS=1
-
-DEPEND=">=app-portage/elt-patches-20170317"
+source "/lib/gentoo/functions.sh" || exit 1
 
-libtool_elt_patch_dir() {
-	echo "${EPREFIX}/usr/share/elt-patches"
+die() {
+	eerror "${@}"
+	exit 1
 }
 
-inherit multilib toolchain-funcs
-
 #
 # See if we can apply $2 on $1, and if so, do it
 #
@@ -33,7 +18,7 @@ ELT_try_and_apply_patch() {
 	local patch=$2
 	local src=$3
 	local disp="${src} patch"
-	local log="${T}/elibtool.log"
+	local log="${ELT_LOGDIR:-${TMPDIR}}/elibtool.log"
 
 	if [[ -z ${_ELT_NOTED_TMP} ]] ; then
 		_ELT_NOTED_TMP=true
@@ -55,7 +40,7 @@ ELT_try_and_apply_patch() {
 		einfo "  Applying ${disp} ..."
 		patch -p0 -g0 --no-backup-if-mismatch "${file}" "${patch}" >> "${log}" 2>&1
 		ret=$?
-		export ELT_APPLIED_PATCHES="${ELT_APPLIED_PATCHES} ${src}"
+		ELT_APPLIED_PATCHES="${ELT_APPLIED_PATCHES} ${src}"
 	else
 		ret=1
 	fi
@@ -84,26 +69,26 @@ ELT_walk_patches() {
 	local ret=1
 	local file=$1
 	local patch_set=$2
-	local patch_dir="$(libtool_elt_patch_dir)/${patch_set}"
+	local patch_dir="@ELT_patchdir@/${patch_set}"
 	local rem_int_dep=$3
 
 	[[ -z ${patch_set} ]] && return 1
 	[[ ! -d ${patch_dir} ]] && return 1
 
 	# Allow patches to use @GENTOO_LIBDIR@ replacements
-	local sed_args=( -e "s:@GENTOO_LIBDIR@:$(get_libdir):g" )
+	local sed_args=( -e "s:@GENTOO_LIBDIR@:@ELT_libdir@:g" )
 	if [[ -n ${rem_int_dep} ]] ; then
 		# replace @REM_INT_DEP@ with what was passed
 		# to --remove-internal-dep
 		sed_args+=( -e "s|@REM_INT_DEP@|${rem_int_dep}|g" )
 	fi
 
-	pushd "$(libtool_elt_patch_dir)" >/dev/null || die
+	pushd "@ELT_patchdir@" >/dev/null || die "pushd to elt-patch dir failed"
 
 	# Go through the patches in reverse order (newer version to older)
 	for patch in $(find "${patch_set}" -maxdepth 1 -type f | LC_ALL=C sort -r) ; do
-		tmp="${T}/libtool-elt.patch"
-		sed "${sed_args[@]}" "${patch}" > "${tmp}" || die
+		tmp="${TMPDIR}/libtool-elt.patch"
+		sed "${sed_args[@]}" "${patch}" > "${tmp}" || die "sed on patch ${patch} failed"
 		if ELT_try_and_apply_patch "${file}" "${tmp}" "${patch}" ; then
 			# Break to unwind w/popd rather than return directly
 			ret=0
@@ -173,8 +158,7 @@ elibtoolize() {
 				force="true"
 				;;
 			-*)
-				eerror "Invalid elibtoolize option: ${x}"
-				die "elibtoolize called with ${x} ??"
+				die "Invalid elibtoolize option: ${x}"
 				;;
 			*)	dirs+=( "${x}" )
 		esac
@@ -192,7 +176,7 @@ elibtoolize() {
 		*-mint*)    elt_patches+=" mint-conf" ;;
 	esac
 
-	if $(tc-getLD) --version 2>&1 | grep -qs 'GNU gold'; then
+	if ${LD} --version 2>&1 | grep -qs 'GNU gold'; then
 		elt_patches+=" gold-conf"
 	fi
 
@@ -207,7 +191,7 @@ elibtoolize() {
 
 	local d p ret
 	for d in "${dirs[@]}" ; do
-		export ELT_APPLIED_PATCHES=
+		ELT_APPLIED_PATCHES=
 
 		if [[ -f ${d}/.elibtoolized ]] ; then
 			${force} || continue
@@ -291,7 +275,7 @@ elibtoolize() {
 					ret=$?
 					;;
 				cross)
-					if tc-is-cross-compiler ; then
+					if [[ ${CBUILD:-${CHOST}} != ${CHOST} ]] ; then
 						ELT_walk_patches "${d}/ltmain.sh" "${p}"
 						ret=$?
 					fi
@@ -333,8 +317,7 @@ elibtoolize() {
 								local version=$(ELT_libtool_version "${d}"/ltmain.sh)
 								echo
 								eerror "Portage patch failed to apply (ltmain.sh version ${version})!"
-								eerror "Please file a bug report to add a proper patch."
-								die "Portage patch failed to apply!"
+								die "Please file a bug report to add a proper patch."
 							fi
 							# We do not want to run libtoolize ...
 							ELT_APPLIED_PATCHES="portage"
@@ -355,8 +338,7 @@ elibtoolize() {
 				  ${do_only_patches} == "no" && \
 				  ${deptoremove} == "" ]]
 			then
-				ewarn "Cannot apply any patches, please file a bug about this"
-				die
+				die "Cannot apply any patches, please file a bug about this"
 			fi
 		fi
 
@@ -426,8 +408,7 @@ elibtoolize() {
 						if [[ ${CHOST} == *-freebsd* ]] ; then
 							if [[ -z $(grep 'Handle Gentoo/FreeBSD as it was Linux' \
 								"${d}/configure" 2>/dev/null) ]]; then
-								eerror "  FreeBSD patch set '${p}' failed to apply!"
-								die "FreeBSD patch set '${p}' failed to apply!"
+								die "  FreeBSD patch set '${p}' failed to apply!"
 							fi
 						fi
 						;;
@@ -440,13 +421,10 @@ elibtoolize() {
 
 		rm -f "${d}/libtool"
 
-		> "${d}/.elibtoolized"
+		echo "${ELT_APPLIED_PATCHES}" > "${d}/.elibtoolized"
 	done
 }
 
-uclibctoolize() { die "Use elibtoolize"; }
-darwintoolize() { die "Use elibtoolize"; }
-
 # char *VER_major(string)
 #
 #    Return the Major (X of X.Y.Z) version
@@ -506,4 +484,5 @@ VER_to_int() {
 	return 1
 }
 
-fi
+elibtoolize "${@}"
+exit 0
```

**Comment by chewi** [comment]
When you mentioned `ELT_APPLIED_PATCHES` on IRC, I also thought of writing it to a file. Don't you need to read it back somewhere though?

**Comment by mgorny** [comment]
> Don't you need to read it back somewhere though?

I'm not sure to what purpose, really. The `elibtoolize()` code wipes it at the beginning of the loop, so ensuring persistence there is pointless. We could re-export it in eclass for environment files in vdb — but I'm not sure if it's really meaningful, especially that it only contains the value for the last file processed.

**Comment by chewi** [comment]
Okay, I was under the impression it was reused across calls.

**Comment by heroxbd** [comment]
The directory of functions.sh does not take EPREFIX into account, resulting in [bug 627824](https://bugs.gentoo.org/show_bug.cgi?id=627824).

**Pull request closed without merging**
