### PR TITLE
media-gfx/gimp: webkit-gtk slot 4

### PR DESCRIPTION
**Pull request by P424D0X**
Update from webkit-gtk slot 2 to 4

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks. Is there a bug number concerning this change?

**Comment by monsieurp** [comment]
@hartwork

**Comment by hartwork** [comment]
Hi!

Slot 4 does not seem right to me: Gimp uses pkg-config to check for  package `webkit-1.0`, which slot 4 does not seem to provide.

**Comment by monsieurp** [comment]
@P424D0X ping?

**Comment by mgorny** [comment]
I'm going to close this due to lack of activity. Feel free to reopen once the maintainer's concerns are evaluated.

**Pull request closed without merging**
