### PR TITLE
net-misc/httpie: Bump to version 1.0.3

### PR DESCRIPTION
**Pull request by rseichter**
Upstream release 1.0.3, removed obsolete ebuilds.

### CODE REVIEW

**Comment by juippis** [comment]
Noo theres too much happening in one commit, please split addition and removal into their separate commits.

**Comment by rseichter** [comment]
Seriously? In previous PRs, I have been urged to squashing commits. In this case, I bump the version because of an automated QA notice (!) and I remove old, non-stable ebuilds.

Please process this pull request as-is, it does not hurt anybody.

**Comment by juippis** [comment]
You've probably been asked to squash some ebuild fixes, after review, into the initial version bump. Not bump + removal into one. 

I already see something suspicious in the ebuild (setuptools), but unfortunately because I can't view the whole file easily, can't confirm if it's a mistake or not (which EAPI is being used?). So it hurts the review process already. Not to mention there's a reason why Gentoo devs split these commits into two, it makes reverting easier.

**Comment by rseichter** [comment]
Commits are split. The only difference between ebuilds 1.0.3 and the previous (stable) one are the KEYWORDS.

**Comment by juippis** [comment]
When running tests, 
```
======================================== FAILURES ========================================
______________ TestBinaryResponseData.test_binary_suppresses_when_terminal _______________

self = <test_binary.TestBinaryResponseData object at 0x7f1652a92d68>
httpbin = <Server(<class 'pytest_httpbin.serve.Server'>, started 139733878208256)>

    def test_binary_suppresses_when_terminal(self, httpbin):
        r = http('GET', httpbin + '/bytes/1024')
>       assert BINARY_SUPPRESSED_NOTICE.decode() in r
E       AssertionError: assert '\n+-----------------------------------------+\n| NOTE: binary data not shown in terminal |\n+-----------------------------------------+' in 'HTTP/1.1 200 OK\r\nAccess-Control-Allow-Credentials: true\r\nAccess-Control-Allow-Origin: *\r\nConnection: Close\r\nC...����!o�\nc��{R\x07�X��-�G�\x10+��T�F� �\x0e\x12Z�4�\x0c�\x1f�I%�Sg�v�ڈ�C���M?\x11\x17D*\t\x06,\x1f����~�������<}B�\n\n'
E        +  where '\n+-----------------------------------------+\n| NOTE: binary data not shown in terminal |\n+-----------------------------------------+' = <built-in method decode of bytes object at 0x7f1654500420>()
E        +    where <built-in method decode of bytes object at 0x7f1654500420> = b'\n+-----------------------------------------+\n| NOTE: binary data not shown in terminal |\n+-----------------------------------------+'.decode

tests/test_binary.py:38: AssertionError
---------------------------------- Captured stderr call ----------------------------------
127.0.0.1 - - [13/Oct/2019 12:24:00] "GET /bytes/1024 HTTP/1.1" 200 1024
==================================== warnings summary ====================================
tests/test_auth.py::test_basic_auth[https]
tests/test_auth.py::test_digest_auth[https---auth-type]
tests/test_auth.py::test_digest_auth[https--A]
tests/test_auth.py::test_credentials_in_url[https]
tests/test_auth.py::test_credentials_in_url_auth_flag_has_priority[https]
tests/test_downloads.py::TestDownloads::test_actual_download[https]
tests/test_httpie.py::test_GET[https]
tests/test_httpie.py::test_DELETE[https]
tests/test_httpie.py::test_PUT[https]
tests/test_httpie.py::test_POST_JSON_data[https]
tests/test_httpie.py::test_POST_form[https]
tests/test_httpie.py::test_POST_form_multiple_values[https]
tests/test_httpie.py::test_POST_stdin[https]
tests/test_httpie.py::test_headers[https]
tests/test_httpie.py::test_headers_unset[https]
tests/test_httpie.py::test_headers_empty_value[https]
tests/test_httpie.py::test_json_input_preserve_order[https]
tests/test_cli.py::TestSchemes::test_default_scheme
tests/test_ssl.py::test_ssl_version[ssl2.3]
tests/test_ssl.py::test_ssl_version[tls1]
tests/test_ssl.py::test_ssl_version[tls1.1]
tests/test_ssl.py::test_ssl_version[tls1.2]
tests/test_ssl.py::TestClientCert::test_cert_and_key
tests/test_ssl.py::TestClientCert::test_cert_pem
tests/test_ssl.py::TestServerCert::test_verify_custom_ca_bundle_path
  /usr/lib64/python3.6/site-packages/urllib3/connection.py:362: SubjectAltNameWarning: Certificate for 127.0.0.1 has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
    SubjectAltNameWarning

tests/test_ssl.py::TestServerCert::test_verify_no_OK
tests/test_ssl.py::TestServerCert::test_verify_false_OK[false]
tests/test_ssl.py::TestServerCert::test_verify_false_OK[fALse]
  /usr/lib64/python3.6/site-packages/urllib3/connectionpool.py:847: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
    InsecureRequestWarning)

-- Docs: https://docs.pytest.org/en/latest/warnings.html
============= 1 failed, 234 passed, 4 skipped, 28 warnings in 13.09 seconds ==============
 * ERROR: net-misc/httpie-1.0.3::testworld failed (test phase):
 *   Tests failed with python3.6
```
2.7 succeeded. 

Also if you look at your commits, you just remove the ebuilds in the first commit, but update manifest in the 2nd. Thus introducing a broken tree after your first commit. It should be easy to fix.

**Comment by rseichter** [comment]
> Also if you look at your commits, you just remove the ebuilds in the first commit, but update manifest in the 2nd. Thus introducing a broken tree after your first commit. It should be easy to fix.

Listing _unused_ checksums in the Manifest creates a broken tree? That would be quite an oversight in Portage, don't you think?

**Comment by rseichter** [comment]
As for the test failing, the source code states "pytest-httpbin doesn't support ssl3". I patched the tests in earlier httpie versions; probably I should disable them instead.

**Comment by rseichter** [comment]
From what I can see, the failing test is an upstream problem. The author parses a byte stream containing a multi-line error message, and my guess is that the decoding falls flat.

**Comment by juippis** [comment]
> Listing _unused_ checksums in the Manifest creates a broken tree? That would be quite an oversight in Portage, don't you think?

Hmm, good point, I'm not sure if it affects metadata generation at all in the end.

Anyway am happy now, thanks for your patience and keeping this package up to date!

**Pull request closed without merging**
