### PR TITLE
dev-php/pecl-cassandra: Add DataStax PHP driver for Apache Cassandra

### PR DESCRIPTION
**Pull request by geaaru**
Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by geaaru** [comment]
Hi, so, can anyone said me how can I resolve this check ? They are related with missing dependencies ?

Thanks in advance

**Comment by wlisik** [comment]
this bot is PITA in fact, just ignore it and force push your changes. Everything is ok with your changes.

**Comment by monsieurp** [comment]
@wlisik Hi. What are you on about? the bot is a PITA? It makes sure new changes comply with our QA standards, are consistent and don't mess up the tree. Criticism is a good thing but don't go over the top and spread FUD. Thank you.

**Comment by monsieurp** [comment]
@geaaru Hi. Please make sure to read https://wiki.gentoo.org/wiki/Gentoo_Github and the Q&A section in particular. Most of the answers to your questions are in this document. Thank you.

**Comment by monsieurp** [comment]
Also, since this is a new package, the commit message must be detailed as much as possible. See https://wiki.gentoo.org/wiki/Gentoo_Github#New_packages.

**Comment by geaaru** [comment]
Hi guys, commit is been done with repoman as describe on gentoo howto.

**Comment by wlisik** [comment]
@monsieurp I quite dont get the sense of this bot's existance. Shouldnt be replaced with human? Wouldnt it be wiser?

**Pull request closed without merging**
