### PR TITLE
net-misc/strongswan plugin unbound needs net-libs/ldns

### PR DESCRIPTION
**Pull request by maggu2810**
Signed-off-by: Markus Rathgeb <maggu2810@gmail.com>

### CODE REVIEW

**Comment by maggu2810** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=529910

**Comment by monsieurp** [comment]
Hi there and thank you for you work. Could you format the commit message according to our standards? that is: "cat/pkg: commit message"

If you want to specify a bug number, you can use the "Gentoo-Bug:" header in the commit message.

**Comment by monsieurp** [comment]
@patricklauer

**Comment by maggu2810** [comment]
@monsieurp: Commit message has been changed. Sorry about that.

**Pull request merged**
