### PR TITLE
app-dicts/myspell-ru-20180627: version bump

### PR DESCRIPTION
**Pull request by perfect7gentleman**
Fixes bug https://bugs.gentoo.org/667146

### CODE REVIEW

**Comment by perfect7gentleman** [comment]
> It seems that you've split in two somehow. Please fix this pull request.

How?

**Comment by mgorny** [comment]
Ping. There's still missing sign-off, and wrong bug-handling tags.

**Comment by perfect7gentleman** [comment]
> Ping. There's still missing sign-off, and wrong bug-handling tags.
I tried to push but there's error.

**Comment by mgorny** [comment]
We can't help you if you don't tell us what it says.

**Comment by perfect7gentleman** [comment]
```
Username for 'https://github.com': perfect7gentleman
Password for 'https://perfect7gentleman@github.com': 
remote: Permission to gentoo/gentoo.git denied to perfect7gentleman.
fatal: unable to access 'https://github.com/gentoo/gentoo/': The requested URL returned error: 403
```

**Comment by mgorny** [comment]
Why are you trying to push via https? Use the ssh URL instead. Use `git remote set-url ...` to change it.

**Comment by mgorny** [comment]
Ping.

**Comment by perfect7gentleman** [comment]
Yep, I'm still here.

**Comment by kuraga** [comment]
New PR: https://github.com/gentoo/gentoo/pull/13344

**Comment by juippis** [comment]
883535534dcb71a71a1a7b3653bbd71f78704b5c

**Pull request closed without merging**
