### PR TITLE
sci-geosciences/qmapshack: Version bump to version 1.6.1

### PR DESCRIPTION
**Pull request by P424D0X**

### CODE REVIEW

**Comment by monsieurp** [comment]
Please format your commit: https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format. Thank you!

**Comment by monsieurp** [comment]
@SoapGentoo

**Comment by SoapGentoo** [comment]
@P424D0X please format your commit messages, and also switch to `EAPI=6` please. Once that's done, we will merge it.

**Comment by SoapGentoo** [comment]
@P424D0X thanks for updating, could you rebase your commits on latest master and squash them together? See http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

**Comment by monsieurp** [comment]
rebasing != pulling. You cocked up a bit this PR now..

**Comment by monsieurp** [comment]
Please rebase accordingly and file another PR.

**Pull request closed without merging**
