### PR TITLE
net-wireless/hostapd-9999

### PR DESCRIPTION
**Pull request by Perlovka**
Hi,
because of current hostapd release is pretty old and does not work clean on recent kernels
(https://forums.gentoo.org/viewtopic-t-1080820.html), and there are no response for new release request (http://lists.infradead.org/pipermail/hostap/2018-April/038490.html) I'm proposing live ebuild from upstream git.
Second commit also fixes typo from parent ebuilds (2.6-r4).
P.S. homepage and download link also changed to current.

### CODE REVIEW

**Comment by Perlovka** [comment]
Full diff from 2.6-r4
```
--- hostapd-2.6-r4.ebuild	2018-06-01 16:54:48.400265591 +0300
+++ hostapd-9999.ebuild	2018-06-01 19:03:00.062249207 +0300
@@ -6,12 +6,20 @@
 inherit toolchain-funcs eutils systemd savedconfig
 
 DESCRIPTION="IEEE 802.11 wireless LAN Host AP daemon"
-HOMEPAGE="http://hostap.epitest.fi"
-SRC_URI="http://hostap.epitest.fi/releases/${P}.tar.gz"
+HOMEPAGE="https://w1.fi/hostapd"
+
+if [[ $PV == 9999 ]]; then
+	inherit git-r3
+	EGIT_REPO_URI="https://w1.fi/hostap.git"
+	KEYWORDS=""
+else
+	SRC_URI="https://w1.fi/releases/${P}.tar.gz"
+	KEYWORDS="~amd64 ~arm ~mips ~ppc ~x86"
+fi
 
 LICENSE="BSD"
 SLOT="0"
-KEYWORDS="~amd64 ~arm ~mips ~ppc ~x86"
+
 IUSE="internal-tls ipv6 libressl logwatch netlink sqlite +wps +crda"
 
 DEPEND="
@@ -46,23 +54,25 @@
 	# i.e. anything outside ${S}/${PN}
 	pushd ../ >/dev/null || die
 
-	# Add LibreSSL compatibility patch bug (#567262)
-	eapply "${FILESDIR}/${P}-libressl-compatibility.patch"
+	if [[ $PV != 9999 ]]; then
+		# Add LibreSSL compatibility patch bug (#567262)
+		eapply "${FILESDIR}/${P}-libressl-compatibility.patch"
+
+		# https://w1.fi/security/2017-1/wpa-packet-number-reuse-with-replayed-messages.txt
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0001-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0002-Prevent-reinstallation-of-an-already-in-use-group-ke.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0003-Extend-protection-of-GTK-IGTK-reinstallation-of-WNM-.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0004-Prevent-installation-of-an-all-zero-TK.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0005-Fix-PTK-rekeying-to-generate-a-new-ANonce.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0006-TDLS-Reject-TPK-TK-reconfiguration.patch"
+		eapply "${FILESDIR}/2017-1/rebased-v2.6-0008-FT-Do-not-allow-multiple-Reassociation-Response-fram.patch"
+	fi
 
-	# https://w1.fi/security/2017-1/wpa-packet-number-reuse-with-replayed-messages.txt
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0001-hostapd-Avoid-key-reinstallation-in-FT-handshake.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0002-Prevent-reinstallation-of-an-already-in-use-group-ke.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0003-Extend-protection-of-GTK-IGTK-reinstallation-of-WNM-.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0004-Prevent-installation-of-an-all-zero-TK.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0005-Fix-PTK-rekeying-to-generate-a-new-ANonce.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0006-TDLS-Reject-TPK-TK-reconfiguration.patch"
-	eapply "${FILESDIR}/2017-1/rebased-v2.6-0008-FT-Do-not-allow-multiple-Reassociation-Response-fram.patch"
 	default
 	popd >/dev/null || die
 
 	sed -i -e "s:/etc/hostapd:/etc/hostapd/hostapd:g" \
 		"${S}/hostapd.conf" || die
-
 }
 
 src_configure() {
@@ -82,7 +92,7 @@
 	echo "CONFIG_ERP=y" >> ${CONFIG}
 	echo "CONFIG_EAP_MD5=y" >> ${CONFIG}
 
-	if use internal-tls && !use libressl; then
+	if use internal-tls && ! use libressl; then
 		echo "CONFIG_TLS=internal" >> ${CONFIG}
 	else
 		# SSL authentication methods
@@ -183,7 +193,7 @@
 src_compile() {
 	emake V=1
 
-	if use libressl || !use internal-tls; then
+	if use libressl || ! use internal-tls; then
 		emake V=1 nt_password_hash
 		emake V=1 hlr_auc_gw
 	fi
@@ -198,7 +208,7 @@
 	dosbin ${PN}
 	dobin ${PN}_cli
 
-	if use libressl || !use internal-tls; then
+	if use libressl || ! use internal-tls; then
 		dobin nt_password_hash hlr_auc_gw
 	fi
```

**Comment by a17r** [comment]
You can remove all those patch references since they will be obsolete in any future release.

Live ebuilds are no replacement for release ebuilds. If new kernels require a newer version of this package, why not make a snapshot that you can stabilise if no issues arise?

**Comment by Perlovka** [comment]
This ebuild is not intended to replace release one. Just possibility to compile current upstream master.
As for patches, i've seen many ebuilds that are common for both release and live version, so I did the same. Is this a good practice, or I should rebase this to keep only live ebuild relevant things?

**Comment by a17r** [comment]
>As for patches, i've seen many ebuilds that are common for both release and live version, so I did the same.

Yes, but they don't have obsolete patches in common.

**Comment by Perlovka** [comment]
Removed patches.

**Comment by andrey-utkin** [comment]
Hi @Perlovka, sorry for no response for long time. Will handle this now.

**Comment by andrey-utkin** [comment]
@Perlovka you are also welcome to second my request to hostapd developers about issuing a new proper release: http://lists.infradead.org/pipermail/hostap/2018-April/038490.html

**Comment by andrey-utkin** [comment]
@a17r thanks for your review.

> If new kernels require a newer version of this package, why not make a snapshot that you can stabilise if no issues arise?

We have discussed this with net-wireless/hostapd comaintainer, @ZeroChaos- . His general rule is to not stabilize snapshot ebuilds, and there is no reason for hostapd to be an exception. I am inclined to agree with him, especially given he has much more experience with wifi stuff. But indeed, up-to-date snapshot ebuild in testing status (`~arch`) is better than unkeyworded live ebuild only. So I will do a snapshot ebuild, too. We will see how it goes and maybe we'll agree on stabilizing it later.

**Comment by ZeroChaos-** [comment]
Apologies for not noticing this till now.  I will review and merge this
myself when I get a few minutes, I am traveling with limited access right
now.  I have no real issue if someone wants a snapshot ebuild, but know
that I am not going to stabilize it without a valid bug fix which is very
important, and even then the amount of testing required would he
prohibitive.

That said, I don't have an issue with grabbing a random snapshot and
putting it in ~arch, let the people who want to run testing do some testing
:-)

**Comment by andrey-utkin** [comment]
Thanks to all participants!

**Comment by andrey-utkin** [comment]
It's fine, in my mailer your message appears as a reply in my thread.

**Pull request closed without merging**
