### PR TITLE
media-sound/qtractor: Bump to 0.9.4

### PR DESCRIPTION
**Pull request by simonvanderveldt**
Qt4 support was dropped in it's entirety so I've removed the econf flag for it.
With the removal of Qt4 support the `--with-qt5` flag was also dropped, so removed that as well. Emering/compilation still works fine.
Also validated that running and opening/using projects works correctly.

P.S. This is a bump and drop in 1 commit, I'm not sure if that's OK or not. If not just let me know I'll split it into 2 commits.

### CODE REVIEW

**Comment by a17r** [comment]
Also, please add your signoff so we can merge your PR.

**Comment by simonvanderveldt** [comment]
> Indeed, please keep them separate commits. Also, only drop it if you are absolutely sure there is no regression over 0.9.2 that may be worth keeping the old version for some time. ;)

Done. There are no real significant changes between 0.9.2 and 0.9.4 and it's all working fine so I think this is fine. Rui only does small changes nowadays so breakage seldom happens :)

> Also, for EAPI-7 you should move all content of `DEPEND` (except `RDEPEND` inheritance) into `BDEPEND` instead.

I've incorporated this change, also moved `DEPEND` into `RDEPEND` instead of the other way around since that seems to be the suggested way of doing this. Hope this is correct.

Added my signoff to the commits as well.

**Comment by simonvanderveldt** [comment]
Yeah, I noticed those. That was already the case for the old(er) version(s) as well though.

What would be the suggested way to fix this?
Add a patch that removed this line + the next https://github.com/rncbc/qtractor/blob/master/Makefile.in#L348
and then add a doins for the man pages?

**Comment by a17r** [comment]
Removing line 349 should be enough, you can add the fix in a separate commit ofc.

**Comment by simonvanderveldt** [comment]
@a17r I've added a patch that should address the QA issue.

**Pull request closed without merging**
