### PR TITLE
dev-java/icedtea-3: add infinality patchset

### PR DESCRIPTION
**Pull request by nE0sIghT**
With dev-java/icedtea:8 fonts smoothing (in Netbeans IDE for example) looks terrible.
None of "awt.useSystemAAFontSettings" values helps.

With this change fonts looks almost same as in icedtea:7 with infinality use flag.

Infinality patches are from https://aur.archlinux.org/packages/jdk8-openjdk-infinality/

#### Icedtea:7 with infinality
Icedtea:7 with infinality
#### Icedtea:8 without infinality
Icedtea:8 without infinality
#### Icedtea:8 with infinality
Icedtea:8 with infinality

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/java @chewi

**Comment by chewi** [comment]
@gnu-andrew, is there any particular reason why Infinality wasn't added to the release? Obviously you were trying to get it out ASAP but just wondering.

**Comment by rindeal** [comment]
:+1: , I've been wondering myself as to when this will be supported - https://github.com/gentoo/java-overlay/issues/31

**Comment by TheIndifferent** [comment]
@nE0sIghT could you please attach 2 screenshots:
- font preview under Tools - Options - Fonts and Colors, press change font button (sorry no idea how it was translated to Russian).
- minimize Projects window width so part of the text will not fit, then rollover and wait for tooltip to appear.

I remember that there was some issue with default rendering type being monochrome and current openJDK font rendering did not allow me to fix it nicely and cleanly. Maybe when NetBeans will be able to run on OpenJDK 9 I will have time and inspiration to implement better font rendering, with all those issues fixed.

**Comment by nE0sIghT** [comment]
@TheIndifferent which version of icedtea you want to see? Icedtea 3 with infinality patches applied?

**Comment by TheIndifferent** [comment]
@nE0sIghT yes, and if that is not a problem then comparison to icedtea 3 without infinality would be interesting too.

**Comment by nE0sIghT** [comment]
@TheIndifferent 

#### Icedtea:8 without infinality
Fonts
Popup

#### Icedtea:8 with infinality
Fonts
Popup

**Comment by TheIndifferent** [comment]
@nE0sIghT very interesting, so it falls back from LCD to grayscale rendering, which is still better than without the patches...

Is it possible for Gentoo **not** to have infinality freetype2/fontconfig installed? How will it behave if system does not have infinality installed, but openjdk was build with infinality support?

**Comment by chewi** [comment]
@TheIndifferent, this is enforced by USE flags in the package manager so no need to worry about that.

**Comment by TheIndifferent** [comment]
@chewi I see. I haven't tested those openjdk patches with printing and headless painting with miss-configured fontconfig, but those are not very popular nowadays probably. No other possible showstopper comes to mind.

**Comment by mgorny** [comment]
@monsieurp, @chewi, can we move this forward?

**Comment by monsieurp** [comment]
All things IcedTea-related are James' territory. Not my call, sorry. :(

**Comment by gnu-andrew** [comment]
It's scheduled for inclusion in 3.1.0: http://icedtea.classpath.org/bugzilla/show_bug.cgi?id=2931
I'll let you know when it appears in a pre-release so you can test it.

**Comment by chewi** [comment]
Thanks @gnu-andrew, I couldn't quite remember what we'd said about it in the end. I was at least going to wait till the next release anyway.

**Comment by nE0sIghT** [comment]
I think we can close this PR.

**Comment by chewi** [comment]
Agreed.

**Pull request closed without merging**
