### PR TITLE
sys-kernel/ck-sources: Version bump and removal of old

### PR DESCRIPTION
**Pull request by cbpeckles**
Version bump for long-term kernel releases as well as removing their
old counterparts.  Ebuilds for current stable kernel releases 4.5.7
and 4.6.2 were also added.  BFQ support for kernel 4.6.x has not been
released and is therefore not included in its respective ebuild.

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by monsieurp** [comment]
Hello and thanks for the PR. This is a maintainer-needed package. Would you be interested in maintaining it? Thanks for letting us know.

**Comment by cbpeckles** [comment]
I would.  I made a thread about this on the gentoo bugzilla.  link here: https://bugs.gentoo.org/show_bug.cgi?id=585552  It currently says that an existing bug is blocking it.  The bug in question is just asking for an ebuild update that was resolved long ago.  This PR also resolves it.  The other bug when searching for ck-sources is worked around in the src_prepare section.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Note to self: close https://bugs.gentoo.org/show_bug.cgi?id=586472 on merge

**Comment by gktrk** [comment]
The following versions are failing to compile with `allyesconfig` and seem to be Brain Fuck Scheduler related. Are these known issues? `defconfig` works fine on the other hand. I just want to make sure we are not missing any patches here.

```
/var/tmp/portage/sys-kernel/ck-sources-3.14.72/image/usr/src/linux-3.14.72-ck $ make
make[1]: Nothing to be done for 'all'.
make[1]: Nothing to be done for 'relocs'.
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
make[3]: 'arch/x86/realmode/rm/realmode.bin' is up to date.
  BC      kernel/timeconst.h
  CC      kernel/time.o
  CC      kernel/sched/bfs.o
kernel/sched/bfs.c: In function ‘_cond_resched’:
kernel/sched/bfs.c:4604:6: error: too few arguments to function ‘should_resched’
  if (should_resched()) {
      ^
In file included from include/linux/preempt.h:20:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
/var/tmp/portage/sys-kernel/ck-sources-3.14.72/image/usr/src/linux-3.14.72-ck/arch/x86/include/asm/preempt.h:108:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
kernel/sched/bfs.c: In function ‘__cond_resched_lock’:
kernel/sched/bfs.c:4622:16: error: too few arguments to function ‘should_resched’
  int resched = should_resched();
                ^
In file included from include/linux/preempt.h:20:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
/var/tmp/portage/sys-kernel/ck-sources-3.14.72/image/usr/src/linux-3.14.72-ck/arch/x86/include/asm/preempt.h:108:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
kernel/sched/bfs.c: In function ‘__cond_resched_softirq’:
kernel/sched/bfs.c:4644:6: error: too few arguments to function ‘should_resched’
  if (should_resched()) {
      ^
In file included from include/linux/preempt.h:20:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
/var/tmp/portage/sys-kernel/ck-sources-3.14.72/image/usr/src/linux-3.14.72-ck/arch/x86/include/asm/preempt.h:108:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
scripts/Makefile.build:308: recipe for target 'kernel/sched/bfs.o' failed
make[2]: *** [kernel/sched/bfs.o] Error 1
scripts/Makefile.build:455: recipe for target 'kernel/sched' failed
make[1]: *** [kernel/sched] Error 2
Makefile:849: recipe for target 'kernel' failed
make: *** [kernel] Error 2
```

```
/var/tmp/portage/sys-kernel/ck-sources-3.18.35/image/usr/src/linux-3.18.35-ck $ make
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
make[1]: 'arch/x86/purgatory/kexec-purgatory.c' is up to date.
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      kernel/sched/stats.o
In file included from include/linux/srcu.h:33:0,
                 from include/linux/notifier.h:15,
                 from include/linux/memory_hotplug.h:6,
                 from include/linux/mmzone.h:790,
                 from include/linux/gfp.h:5,
                 from include/linux/slab.h:14,
                 from kernel/sched/stats.c:2:
kernel/sched/stats.c: In function ‘show_schedstat’:
kernel/sched/bfs_sched.h:119:27: error: ‘sched_domains_mutex’ undeclared (first use in this function)
          lockdep_is_held(&sched_domains_mutex))
                           ^
include/linux/rcupdate.h:527:53: note: in definition of macro ‘rcu_lockdep_assert’
   if (debug_lockdep_rcu_enabled() && !__warned && !(c)) { \
                                                     ^
include/linux/rcupdate.h:707:2: note: in expansion of macro ‘__rcu_dereference_check’
  __rcu_dereference_check((p), rcu_read_lock_held() || (c), __rcu)
  ^
kernel/sched/bfs_sched.h:118:2: note: in expansion of macro ‘rcu_dereference_check’
  rcu_dereference_check((p), \
  ^
kernel/sched/bfs_sched.h:119:10: note: in expansion of macro ‘lockdep_is_held’
          lockdep_is_held(&sched_domains_mutex))
          ^
kernel/sched/bfs_sched.h:129:14: note: in expansion of macro ‘rcu_dereference_check_sched_domain’
  for (__sd = rcu_dereference_check_sched_domain(cpu_rq(cpu)->sd); __sd; __sd = __sd->parent)
              ^
kernel/sched/stats.c:54:3: note: in expansion of macro ‘for_each_domain’
   for_each_domain(cpu, sd) {
   ^
kernel/sched/bfs_sched.h:119:27: note: each undeclared identifier is reported only once for each function it appears in
          lockdep_is_held(&sched_domains_mutex))
                           ^
include/linux/rcupdate.h:527:53: note: in definition of macro ‘rcu_lockdep_assert’
   if (debug_lockdep_rcu_enabled() && !__warned && !(c)) { \
                                                     ^
include/linux/rcupdate.h:707:2: note: in expansion of macro ‘__rcu_dereference_check’
  __rcu_dereference_check((p), rcu_read_lock_held() || (c), __rcu)
  ^
kernel/sched/bfs_sched.h:118:2: note: in expansion of macro ‘rcu_dereference_check’
  rcu_dereference_check((p), \
  ^
kernel/sched/bfs_sched.h:119:10: note: in expansion of macro ‘lockdep_is_held’
          lockdep_is_held(&sched_domains_mutex))
          ^
kernel/sched/bfs_sched.h:129:14: note: in expansion of macro ‘rcu_dereference_check_sched_domain’
  for (__sd = rcu_dereference_check_sched_domain(cpu_rq(cpu)->sd); __sd; __sd = __sd->parent)
              ^
kernel/sched/stats.c:54:3: note: in expansion of macro ‘for_each_domain’
   for_each_domain(cpu, sd) {
   ^
scripts/Makefile.build:257: recipe for target 'kernel/sched/stats.o' failed
make[2]: *** [kernel/sched/stats.o] Error 1
scripts/Makefile.build:402: recipe for target 'kernel/sched' failed
make[1]: *** [kernel/sched] Error 2
Makefile:942: recipe for target 'kernel' failed
make: *** [kernel] Error 2
```

```
/var/tmp/portage/sys-kernel/ck-sources-3.4.112/image/usr/src/linux-3.4.112-ck $ make
make[1]: Nothing to be done for 'all'.
make[1]: Nothing to be done for 'relocs'.
  CHK     include/linux/version.h
  CHK     include/generated/utsrelease.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CHK     kernel/config_data.h
  GEN     .version
  CHK     include/generated/compile.h
  UPD     include/generated/compile.h
  CC      init/version.o
  LD      init/built-in.o
  LD      .tmp_vmlinux1
kernel/built-in.o: In function `show_schedstat':
/var/tmp/portage/sys-kernel/ck-sources-3.4.112/image/usr/src/linux-3.4.112-ck/kernel/sched/stats.c:47: undefined reference to `sched_domains_mutex'
Makefile:879: recipe for target '.tmp_vmlinux1' failed
make: *** [.tmp_vmlinux1] Error 1
```

```
/var/tmp/portage/sys-kernel/ck-sources-4.1.26/image/usr/src/linux-4.1.26-ck $ make
  CHK     include/config/kernel.release
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CHK     include/generated/bounds.h
  CHK     include/generated/asm-offsets.h
  CALL    scripts/checksyscalls.sh
  CHK     include/generated/compile.h
  CC      kernel/sched/bfs.o
kernel/sched/bfs.c: In function ‘_cond_resched’:
kernel/sched/bfs.c:4683:6: error: too few arguments to function ‘should_resched’
  if (should_resched()) {
      ^
In file included from include/linux/preempt.h:18:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
./arch/x86/include/asm/preempt.h:93:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
kernel/sched/bfs.c: In function ‘__cond_resched_lock’:
kernel/sched/bfs.c:4701:16: error: too few arguments to function ‘should_resched’
  int resched = should_resched();
                ^
In file included from include/linux/preempt.h:18:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
./arch/x86/include/asm/preempt.h:93:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
kernel/sched/bfs.c: In function ‘__cond_resched_softirq’:
kernel/sched/bfs.c:4723:6: error: too few arguments to function ‘should_resched’
  if (should_resched()) {
      ^
In file included from include/linux/preempt.h:18:0,
                 from include/linux/spinlock.h:50,
                 from include/linux/mmzone.h:7,
                 from include/linux/gfp.h:5,
                 from include/linux/mm.h:9,
                 from kernel/sched/bfs.c:31:
./arch/x86/include/asm/preempt.h:93:29: note: declared here
 static __always_inline bool should_resched(int preempt_offset)
                             ^
scripts/Makefile.build:258: recipe for target 'kernel/sched/bfs.o' failed
make[2]: *** [kernel/sched/bfs.o] Error 1
scripts/Makefile.build:403: recipe for target 'kernel/sched' failed
make[1]: *** [kernel/sched] Error 2
Makefile:952: recipe for target 'kernel' failed
make: *** [kernel] Error 2
```

**Comment by gktrk** [comment]
The culprit is [1055_linux-3.14.56.patch](https://dev.gentoo.org/~mpagano/genpatches/trunk/3.14/1055_linux-3.14.56.patch). Specifically:

```
-static __always_inline bool should_resched(void)
+static __always_inline bool should_resched(int preempt_offset)
```

This looks like an upstream (ckolivas) bug.

**Comment by gktrk** [comment]
The following patch fixes the should_resched() build failure. Will contact upstream.

```
--- a/kernel/sched/bfs.c
+++ b/kernel/sched/bfs.c
@@ -4601,7 +4601,7 @@
 
 int __sched _cond_resched(void)
 {
-       if (should_resched()) {
+       if (should_resched(0)) {
                __cond_resched();
                return 1;
        }
@@ -4619,7 +4619,7 @@
  */
 int __cond_resched_lock(spinlock_t *lock)
 {
-       int resched = should_resched();
+       int resched = should_resched(0);
        int ret = 0;
 
        lockdep_assert_held(lock);
@@ -4641,7 +4641,7 @@
 {
        BUG_ON(!in_softirq());
 
-       if (should_resched()) {
+       if (should_resched(0)) {
                local_bh_enable();
                __cond_resched();
                local_bh_disable();
```

**Comment by gktrk** [comment]
Actually, @cbpeckles: given you will be the maintainer for this package, can you contact upstream instead?

**Comment by monsieurp** [comment]
ping?

**Comment by monsieurp** [comment]
ping?!

**Comment by monsieurp** [comment]
@cbpeckles / @gktrk hi! what's the deal with this PR? who's in charge of contacting upstream? who's in charge of maintaining this package?

**Comment by gktrk** [comment]
I am waiting on user response to proceed further with this merge. As is, it is not ready for merge.

**Comment by SoapGentoo** [comment]
@gktrk can we just keep the broken release and move to the next 4.(x+1) release?

**Comment by gktrk** [comment]
I haven't heard back from the user. My issue is mainly with how we package this. My understanding is that ckolivas doesn't rebase these patches on top of the LTS releases. So we take a patchset that is meant to be applied on top of a regular kernel release, and apply it on top of the long term patches. For example the patch calls the function `should_resched()` with no argument but in the LTS version it takes an integer e.g. `should_resched(0)`. I'm not sure how to proceed.

**Comment by monsieurp** [comment]
@SoapGentoo @gktrk what do we do with this PR folks?

**Comment by mkszuba** [comment]
No maintainer again, known issues, QA checks failing, no activity for months... I would say we should drop it.

**Comment by mgorny** [comment]
@gentoo/treecleaner

**Comment by flberger** [comment]
FYI, Gentoo forum user 'hnaparst' is offering ebuilds for Con's latest BFS rewrite 'MuQSS' in his overlay at https://github.com/hnaparst/overlay , reportedly working for a couple of users (me included). See https://forums.gentoo.org/viewtopic-t-1052388-highlight-.html (Pointed out by thunderrd at https://bugs.gentoo.org/show_bug.cgi?id=569262#c6 )

Maybe that user is interested in maintaining. Else, when dropping the package, a hint at that overlay might be useful.

**Comment by thunderrd** [comment]
A sad situation for an important kernel patchset.

It is my understanding that hnaparst used to maintain this package for Gentoo, and for some reason unknown to me he doesn't anymore.  Two other people have expressed interest in the forums thread in the past several months; what happened to them?

**Comment by gktrk** [comment]
This package has been bumped to 4.9.4 in https://github.com/gentoo/gentoo/compare/deb8b48...dcf3748. Closing the PR.

**Pull request closed without merging**
