### PR TITLE
media-video/obs-studio: Version bump to 29.0.2

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by Chiitoo** [comment]
Thanks!

The hashes for OBS_BROWSER_COMMIT and OBS_WEBSOCKET_COMMIT need some updating [1], and the rest can be found under websocket [2], although those seem to be okay still for this release.

1. https://github.com/obsproject/obs-studio/tree/29.0.2/plugins
2. https://github.com/obsproject/obs-websocket/tree/31f9845b6132e6c1529401292bc1125401e2a324/deps

**Comment by flint2** [comment]
> Thanks!
> 
> The hashes for OBS_BROWSER_COMMIT and OBS_WEBSOCKET_COMMIT need some updating [1], and the rest can be found under websocket [2], although those seem to be okay still for this release.
> 
>     1. https://github.com/obsproject/obs-studio/tree/29.0.2/plugins
> 
>     2. https://github.com/obsproject/obs-websocket/tree/31f9845b6132e6c1529401292bc1125401e2a324/deps

Changed in https://github.com/gentoo/gentoo/commit/94edf7f2bedbcd3a3a029dd85748bea160d2ed36

Thanks!

**Comment by Chiitoo** [comment]
Hmmm, that websocket commit, ddd139255bb8efcfde41536f8fb3044354fed46e, looks like it's from 'master'.

For obs-studio-29.0.2 (and even 'master'), it should be 31f9845b6132e6c1529401292bc1125401e2a324 still as seen in the plugins directory [1].

Thanks again!

1. https://github.com/obsproject/obs-studio/tree/29.0.2/plugins

**Comment by flint2** [comment]
> Hmmm, that websocket commit, ddd139255bb8efcfde41536f8fb3044354fed46e, looks like it's from 'master'.
> 
> For obs-studio-29.0.2 (and even 'master'), it should be 31f9845b6132e6c1529401292bc1125401e2a324 still as seen in the plugins directory [1].
> 
> Thanks again!
> 
>     1. https://github.com/obsproject/obs-studio/tree/29.0.2/plugins

Corrected in https://github.com/gentoo/gentoo/commit/bd04ac65104c655558d27ed1e08b892fbf1f276d
Thanks!

**Comment by Chiitoo** [comment]
The websocket ddd139255bb was still in the Manifest, but I removed it while committing.

Thank you!

**Pull request closed without merging**
