### PR TITLE
net-misc/networkmanager: 1.28.0 version bump

### PR DESCRIPTION
**Pull request by candrews**
Closes: https://bugs.gentoo.org/764311
Closes: https://bugs.gentoo.org/738614
Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Craig Andrews <candrews@gentoo.org>

### CODE REVIEW

**Comment by candrews** [comment]
@winterheart here's the bump [you were talking about](https://github.com/gentoo/gentoo/pull/18568#issuecomment-740911402)

**Comment by mattst88** [comment]
Thanks. Any chance you'd be interested in trying to bump `net-misc/modemmanager` at the same time (since it and networkmanager are pretty connected)?

**Comment by mattst88** [comment]
Please incorporate @dm0-'s EAPI=7 changes from https://github.com/gentoo/gentoo/pull/18813 in this bump and add PYTHON_COMPAT=python3_9 support.

**Comment by candrews** [comment]
> Please incorporate @dm0-'s EAPI=7 changes from #18813 in this bump and add PYTHON_COMPAT=python3_9 support.

Done. I incorporated these changes: https://github.com/gentoo/gentoo/pull/18813/commits/795e73e71bfce022389f30e4c3e8c34c70eff84b

**Comment by candrews** [comment]
> Thanks. Any chance you'd be interested in trying to bump `net-misc/modemmanager` at the same time (since it and networkmanager are pretty connected)?

I don't use modemmanager, so not really... but I did it anyways :) I created a separate PR for that: https://github.com/gentoo/gentoo/pull/18985

**Pull request closed without merging**
