### PR TITLE
Bump sys-cluster/singularity to 2.3.1

### PR DESCRIPTION
**Pull request by cromega**
@jlec ping!

### CODE REVIEW

**Comment by jlec** [comment]
@cromega please diff the the tarball content of the old and new version. There are several significant differences including python bindings which need to include in the ebuild.

I don't have a linux box at hand so I couldn't test build it yet.

**Comment by cromega** [comment]
@jlec I am using 2.3.1 from this ebuild. I will check the diff anyway to see if there's something obvious and I will try to build it in a container without additional python packages installed. Will update you a bit later.

**Comment by cromega** [comment]
@jlec the python imports are all std packages and the package can be built with either python 2.7 or 3.6 installed.

**Comment by jlec** [comment]
@cromega Please do not drop the old version straight away.

While a simple c&p might work, especially additional python support requires the usage of the python*eclasses. Also we might like to look into multi ABI python support if that works.

**Comment by cromega** [comment]
@jlec yessir o>

**Comment by jlec** [comment]
Please have a look at e48d15c0567348bce2ea174432a066ddfc4f3de5

This is the diff to the old one

```diff
--- singularity-2.2.1.ebuild	2017-04-30 12:01:09.425885107 +0100
+++ singularity-2.3.1.ebuild	2017-07-09 19:48:31.167115391 +0100
@@ -3,7 +3,9 @@

 EAPI=6

-inherit eutils
+PYTHON_COMPAT=( python{2_7,3_{4,5,6}} )
+
+inherit autotools eutils python-single-r1

 DESCRIPTION="Application containers for Linux"
 HOMEPAGE="http://singularity.lbl.gov/"
@@ -12,20 +14,35 @@
 SLOT="0"
 LICENSE="cctbx-2.0"
 KEYWORDS="~amd64 ~x86 ~amd64-linux ~x86-linux"
-IUSE="examples"
+IUSE="examples slurm static-libs +suid"
+
+RDEPEND="
+	sys-cluster/slurm
+"
+DEPEND="${RDEPEND}"

 PATCHES=(
-	"${FILESDIR}"/${P}-glibc-2.25.patch
+	"${FILESDIR}"/${P}-slurm.patch
 )

+src_prepare() {
+	default
+	# automake version hardcoding
+	eautoreconf
+}
+
 src_configure() {
-	econf --with-userns
+	econf \
+		--with-userns \
+		$(use_with slurm) \
+		$(usex suid "" "--disable-suid") \
+		$(use_enable static-libs static)
 }

 src_install() {
 	MAKEOPTS+=" -j1"
 	default
 	prune_libtool_files
-	dodoc ChangeLog
+	dodoc ChangeLog AUTHORS.md CONTRIBUTING.md
 	use examples && dodoc -r examples
 }
```

**Pull request closed without merging**
