### PR TITLE
sci-mathematics/singular: upstream bump

### PR DESCRIPTION
**Pull request by kiwifb**
Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: François René Pierre Bissey <frp.bissey@gmail.com>

### CODE REVIEW

**Comment by kiwifb** [comment]
For people keeping scores, there is still not much for julia support apart from the configuration switch and a couple of comments in the code.

**Comment by orlitzky** [comment]
Can you add the patches for https://bugs.gentoo.org/776643 and https://bugs.gentoo.org/830279 please? I've already promised to do so in the bug comments.

**Comment by kiwifb** [comment]
Will do ASAP.

**Comment by kiwifb** [comment]
Added the backports.

**Comment by thesamesam** [comment]
You should feel free to add yourself to any of these packages if you wish.

**Comment by kiwifb** [comment]
Will think about it but I'd like to have this in first. I'll probably open a proper bug and include it if I do 4.3.0p1.

**Pull request closed without merging**
