### PR TITLE
Dahdi 3.2.0

### PR DESCRIPTION
**Pull request by jkroonza**

### CODE REVIEW

**Comment by jkroonza** [comment]
And already extra patches are required ... such is the life of DAHDI I guess.  Still don't know why this can't just be upstreamed into the kernel.

**Review by juippis — COMMENTED** [review]
I'm still getting:
```
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c: In function 'dahdi_seq_show':
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:931:13: warning: the comparison will always evaluate as 'true' for the address of 'name' will never be NULL [-Waddress[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Waddress]]
  931 |         if (s->name)
      |             ^
In file included from /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:64:
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/include/dahdi/kernel.h:921:14: note: 'name' declared here
  921 |         char name[40];                  /*!< Span name */
      |              ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:933:13: warning: the comparison will always evaluate as 'true' for the address of 'desc' will never be NULL [-Waddress[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Waddress]]
  933 |         if (s->desc)
      |             ^
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/include/dahdi/kernel.h:922:14: note: 'desc' declared here
  922 |         char desc[80];                  /*!< Span description */
      |              ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:972:21: warning: the comparison will always evaluate as 'true' for the address of 'name' will never be NULL [-Waddress[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Waddress]]
  972 |                 if (chan->name)
      |                     ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/include/dahdi/kernel.h:400:14: note: 'name' declared here
  400 |         char name[40];
      |              ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:272:27: error: initialization of 'int (*)(const struct device *, struct kobj_uevent_env *)' from incompatible pointer type 'int (*)(struct device *, struct kobj_uevent_env *)' [-               Werror=incompatible-pointer-types[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types]]
  272 |         .uevent         = span_uevent,
      |                           ^~~~~~~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:272:27: note: (near initialization for 'spans_bus_type.uevent')
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:709:27: error: initialization of 'int (*)(const struct device *, struct kobj_uevent_env *)' from incompatible pointer type 'int (*)(struct device *, struct kobj_uevent_env *)' [-               Werror=incompatible-pointer-types[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types]]
  709 |         .uevent         = device_uevent,
      |                           ^~~~~~~~~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:709:27: note: (near initialization for 'dahdi_device_bus.uevent')
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c: In function '__dahdi_hooksig_pvt':
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8477:20: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
 8477 |                 if (chan->txstate != DAHDI_TXSTATE_OFFHOOK) break;
      |                    ^
cc1: some warnings being treated as errors
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8493:12: note: here
 8493 |            case DAHDI_SIG_FXSGS:  /* FXS Groundstart */
      |            ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8504:20: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
 8504 |                 if (rxsig == DAHDI_RXSIG_START) {
      |                    ^
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8512:12: note: here
 8512 |            case DAHDI_SIG_FXOLS: /* FXO Loopstart */
      |            ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c: In function 'dahdi_rbsbits':
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8607:20: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
 8607 |                 if (!(cursig & DAHDI_BBIT)) {
      |                    ^
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:8612:13: note: here
 8612 |             case DAHDI_SIG_EM_E1:
      |             ^~~~
make[2]: *** [scripts/Makefile.build:252: /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from ./include/linux/string.h:254,
                 from ./include/linux/bitmap.h:11,
                 from ./include/linux/cpumask.h:12,
                 from ./arch/x86/include/asm/paravirt.h:17,
                 from ./arch/x86/include/asm/cpuid.h:62,
                 from ./arch/x86/include/asm/processor.h:19,
                 from ./arch/x86/include/asm/timex.h:5,
                 from ./include/linux/timex.h:67,
                 from ./include/linux/time32.h:13,
                 from ./include/linux/time.h:60,
                 from ./include/linux/stat.h:19,
                 from ./include/linux/module.h:13,
                 from /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:40:
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c: In function '__dahdi_process_getaudio_chunk':
./include/linux/fortify-string.h:59:33: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
   59 | #define __underlying_memset     __builtin_memset
      |                                 ^
./include/linux/fortify-string.h:453:9: note: in expansion of macro '__underlying_memset'
  453 |         __underlying_memset(p, c, __fortify_size);                      \
      |         ^~~~~~~~~~~~~~~~~~~
./include/linux/fortify-string.h:461:25: note: in expansion of macro '__fortify_memset_chk'
  461 | #define memset(p, c, s) __fortify_memset_chk(p, c, s,                   \
      |                         ^~~~~~~~~~~~~~~~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:7928:25: note: in expansion of macro 'memset'
 7928 |                         memset(txb + 1, txb[0], DAHDI_CHUNKSIZE - 1);
      |                         ^~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:7930:17: note: here
 7930 |                 case DAHDI_CONF_CONF:   /* Normal conference mode */
      |                 ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:7931:28: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
 7931 |                         if (is_pseudo_chan(ms)) /* if pseudo-channel */
      |                            ^
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:7954:17: note: here
 7954 |                 case DAHDI_CONF_CONFMON:        /* Conference monitor mode */
      |                 ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c: In function '__dahdi_process_putaudio_chunk':
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:9044:28: warning: this statement may fall through [-Wimplicit-fallthrough=[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wimplicit-fallthrough=]]
 9044 |                         if (is_pseudo_chan(ms)) /* if a pseudo-channel */
      |                            ^
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.c:9059:17: note: here
 9059 |                 case DAHDI_CONF_CONFANN:  /* Conference with announce */
      |                 ^~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.c: In function 'fixed_devfiles_remove':
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.c:384:17: warning: this 'if' clause does not guard... [-Wmisleading-indentation[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wmisleading-indentation]]
  384 |                 if (d && !IS_ERR(d))
      |                 ^~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.c:40:9: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'
   40 |         device_destroy(dahdi_class, MKDEV(DAHDI_MAJOR, num))
      |         ^~~~~~~~~~~~~~
/var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.c:387:25: note: in expansion of macro 'DEL_DAHDI_DEV'
  387 |                         DEL_DAHDI_DEV(fixed_minors[i].minor);
      |                         ^~~~~~~~~~~~~
# cmd_check_local_export /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.o
  ./scripts/check-local-export /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs-chan.o
# cmd_check_local_export /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.o
  ./scripts/check-local-export /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-base.o
make[1]: *** [Makefile:2025: /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi] Error 2
make: *** [Makefile:74: modules] Error 2
 * ERROR: net-misc/dahdi-3.2.0::gentoo failed (compile phase):
 *   emake failed
```
I think this is it again:
`cc1: some warnings being treated as errors`

**Comment by jkroonza** [comment]
> /var/tmp/portage/net-misc/dahdi-3.2.0/work/dahdi-linux-3.2.0/drivers/dahdi/dahdi-sysfs.c:272:27: error: initialization of 'int (*)(const struct device *, struct kobj_uevent_env *)' from incompatible pointer type 'int (*)(struct device *, struct kobj_uevent_env *)' [-               Werror=incompatible-pointer-types[https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html#index-Wincompatible-pointer-types]]

So that is an error ... due to -Werror=incompatible-pointer-types.

That can be fixed, not sure why my compile doesn't use -Werror=incompatible-pointer-types - you using gcc or clang?  You kernel version?  Other similar things I also tracked to the kernel sources ... so I'm wondering if this isn't another of those cases where perhaps you're using some set of kernel sources which sets these options where the ones I got doesn't.  Also, version of compiler ... the above is def an error though, busy cooking a patch now for that, however, please note:

jkroon@plastiekpoot /usr/src/linux $ grep -r incompatible-pointer-types *
...
Makefile:KBUILD_CFLAGS   += $(call cc-option,-Werror=incompatible-pointer-types)

Looking through the dahdi-linux code I can't find incompatible-pointer-types anywhere, so I'm 99% certain it's coming from the kernel sources.

Looking at vanilla kernel sources for the relevant struct to which is benig assigned on line 272 above, from include/linux/device/bus.h, for struct bus_type, the uevent pointer:

 93     int (*uevent)(struct device *dev, struct kobj_uevent_env *env);

Yours however seems to have a const for that struct device *dev.  So I *suspect* it's your specific kernel sources that's causing this problem.  If I change the definition of the assignment so that it will work for you, my kernel fails with a similar error (although IMHO a more strict const in the function being assigned to the pointer should be fine ... but it's not.

I fixed the EAPI=8's locally so long.

**Comment by juippis** [comment]
All testing is done inside a bare-minimum container which is always up-to-date on latest ~amd64, that means currently gcc-13 is being used. The container has ~amd64 gentoo-kernel-bin installed (6.3) and packages **should** use that, however if they seek real /dev etc then it uses host's kernel which is the stable LTS one (6.1) with custom config yes.

**Comment by jkroonza** [comment]
> All testing is done inside a bare-minimum container which is always up-to-date on latest ~amd64, that means currently gcc-13 is being used. The container has ~amd64 gentoo-kernel-bin installed (6.3) and packages **should** use that, however if they seek real /dev etc then it uses host's kernel which is the stable LTS one (6.1) with custom config yes.

The gentoo-kernel-bin here is the important bit.  Will see if at some point I can figure out if it's possible to sit down and see how to detect that variance in const to try and compensate for that somehow.

Thanks for the information, it really helps a lot.  I *suspect* the const there comes as part of the of the "with Gentoo patches" (but last I checked these patches didn't perform such invasive things, mostly just changed defaults for stuff that really could be set via sysctl anyway).

**Pull request closed without merging**
