### PR TITLE
dev-php/pecl-mongodb: version bump to 1.5.3

### PR DESCRIPTION
**Pull request by askovpen**
Signed-off-by: Alexander N. Skovpen alexander@skovpen.org
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by hydrapolic** [comment]
Why did you remove libbson/mongo-c-driver? According to the changelog, it got bumped to version 1.13.0.

https://pecl.php.net/package-changelog.php?package=mongodb&release=1.5.3:
```
* [PHPC-1270] - Upgrade libmongoc to 1.13.0
```

**Comment by askovpen** [comment]
> Why did you remove libbson/mongo-c-driver?

this version have it inside.

**Comment by hydrapolic** [comment]
In Gentoo, we try to unbundle the dependencies, so they can be shared. In your 1.5.3 ebuild you removed dependency on libbson/mongo-c-driver and stopped using the --with-libbson and --with-libmongoc flags to use system dependencies. Please bump libbson/mongo-c-driver and use those system libraries instead, thanks.

```
--- /usr/portage/dev-php/pecl-mongodb/pecl-mongodb-1.5.2.ebuild 2018-08-28 02:09:19.000000000 +0200
+++ pecl-mongodb-1.5.3.ebuild   2018-12-14 13:09:19.181545271 +0100
@@ -20,8 +20,6 @@
        php_targets_php7-0? ( dev-lang/php:7.0[json,ssl,zlib] )
        php_targets_php7-1? ( dev-lang/php:7.1[json,ssl,zlib] )
        php_targets_php7-2? ( dev-lang/php:7.2[json,ssl,zlib] )
-       >=dev-libs/libbson-1.12.0
-       >=dev-libs/mongo-c-driver-1.12.0[sasl?,ssl]
        !libressl? ( dev-libs/openssl:0= )
        libressl? ( dev-libs/libressl:0= )
        sasl? ( dev-libs/cyrus-sasl )
@@ -32,8 +30,6 @@
 src_configure() {
        local PHP_EXT_ECONF_ARGS=(
                --enable-mongodb
-               --with-libbson
-               --with-libmongoc
                --with-mongodb-sasl=$(usex sasl)
        )
        php-ext-source-r3_src_configure
```

**Comment by askovpen** [comment]
try build and you are see, that using mongo-c-driver, bson, mongoc latest from bundle. not system. 
flags --with-libbson, --with-libmongoc for using this libs from systems. else from bundle.

**Comment by askovpen** [comment]
for standalone mongo-c-driver-1.13.0 need patches to build on gentoo. if you can patch it, you can make pecl-mongodb-1.5.3-r1.ebuild with shared depencies.

**Comment by hydrapolic** [comment]
https://bugs.gentoo.org/251464

**Comment by hydrapolic** [comment]
https://github.com/gentoo/gentoo/pull/10640

**Comment by Whissi** [comment]
Closed via #10640.

**Pull request closed without merging**
