### PR TITLE
gnome-extra/gnome-characters: Version bump to 45_alpha

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
````
+compile_schemas = find_program('glib-compile-schemas', required: false)
+if compile_schemas.found()
+  settings_schemas = custom_target('settings-schemas',
+    command: [compile_schemas, '@CURRENT_SOURCE_DIR@', '--targetdir=@OUTDIR@'],
+    input: gschema_file,
+    output: 'gschemas.compiled',
+  )
+endif
````

This needs glib in BDEPEND.

**Comment by flint2** [comment]
> ```diff
> +xvfb_run = find_program('xvfb-run', required: false)
> ```
> 
> The test suite fails for me without xvfb-run installed. Dependency is needed.

Added in https://github.com/gentoo/gentoo/commit/e66fefc9f958bd5ee8aef49840ff5bec7104df70

One test still failing


 ✀  
stderr:
Failed to create /var/lib/portage/home/.cache for shader cache (Permission denied)---disabling.

(gjs-console:68): Gdk-WARNING **: 21:44:46.696: The program 'gjs-console' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 192 error_code 165 request_code 149 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)



Summary of Failures:

2/2 Util             FAIL            0.14s   exit status 1

Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0

**Comment by flint2** [comment]
Still failing 1 test

------------------------------------------------------------------------------------------------

Test phase: gnome-extra/gnome-characters-45_alpha
 * Starting Xvfb ...
 * Xvfb started on DISPLAY=:2
dbus-daemon[43]: Cannot setup inotify for '/root/.local/share/flatpak/exports/share/dbus-1/services'; error 'Permission denied'
ninja: no work to do.
ninja: Entering directory `/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
ninja: no work to do.
dbus-daemon[43]: [session uid=250 pid=43] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=250 pid=77 comm="/usr/bin/appstream-util validate-relax --nonet dat")
dbus-daemon[43]: [session uid=250 pid=43] Successfully activated service 'org.gtk.vfs.Daemon'
1/2 validate-appdata        OK              0.06s
2/2 Util                    FAIL            0.13s   exit status 1
>>> GSETTINGS_BACKEND=memory GI_TYPELIB_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/lib GSETTINGS_SCHEMA_DIR=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/data LD_LIBRARY_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/lib MALLOC_PERTURB_=10 GJS_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha/src:/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/src /usr/bin/xvfb-run -a /usr/bin/gjs-console /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/../gnome-characters-45.alpha/tests/testUtil.js


Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/meson-logs/testlog.txt
A connection to the bus can't be made
 * ERROR: gnome-extra/gnome-characters-45_alpha::gentoo failed (test phase):
 *   Failed to run 'dbus-run-session meson test -C /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_test
 *   environment, line 2489:  Called virtx 'dbus-run-session' 'meson' 'test' '-C' '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
 *   environment, line 3281:  Called die
 * The specific snippet of code:
 *       [[ ${retval} -ne 0 ]] && die "Failed to run '$@'";
 * 
 * If you need support, post the output of `emerge --info '=gnome-extra/gnome-characters-45_alpha::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=gnome-extra/gnome-characters-45_alpha::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha'
 * S: '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha'

**Comment by mattst88** [comment]
Please wrap logs in triple ` marks to make them readable.

**Comment by mattst88** [comment]
```diff
--- gnome-characters-44.0.ebuild	2023-05-03 13:26:32.319237798 -0400
+++ gnome-characters-45_alpha.ebuild	2023-07-11 22:25:19.765955405 -0400
@@ -3,14 +3,14 @@
 
 EAPI=8
 
-inherit gnome.org gnome2-utils meson xdg
+inherit gnome.org gnome2-utils meson virtualx xdg
 
 DESCRIPTION="Unicode character map viewer and library"
 HOMEPAGE="https://wiki.gnome.org/Design/Apps/CharacterMap"
 
 LICENSE="GPL-2+ BSD"
 SLOT="0"
-KEYWORDS="amd64 arm64 ~ppc64 ~riscv x86"
+KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"
 
 RDEPEND="
 	>=dev-libs/gjs-1.50
@@ -28,8 +28,13 @@
 	dev-util/glib-utils
 	>=sys-devel/gettext-0.19.8
 	virtual/pkgconfig
+	x11-misc/xvfb-run
 "
 
+src_test() {
+	XDG_SESSION_TYPE=x11 virtx dbus-run-session meson test -C "${BUILD_DIR}" || die 'tests failed'
+}
+
 pkg_postinst() {
 	xdg_pkg_postinst
 	gnome2_schemas_update
```

- The build system runs `xvfb-run` itself, so we don't need virtx/dbus-run-session
- `x11-misc/xvfb-run` is a conditional test dependency

**Pull request closed without merging**
