### PR TITLE
x11-drivers/xf86-video-virtualbox-5.1.24: missing dependency on x11-proto/presentproto and x11-proto/dri3proto

### PR DESCRIPTION
**Pull request by isavl**
Gentoo-Bug: https://bugs.gentoo.org/625748

### CODE REVIEW

**Comment by Polynomial-C** [comment]
Please do not add all these useless empty lines everywhere.

**Comment by isavl** [comment]
Ohhh ok sorry, i just copy from my local repo and i do not think about this.

**Comment by Polynomial-C** [comment]
So are you going to remove those empty lines from this PR?

**Comment by isavl** [comment]
I think you already remove those lines. But ok i will make it.

**Pull request closed without merging**
