### PR TITLE
sci-libs/dcmtk: version bump 3.6.4

### PR DESCRIPTION
**Pull request by TheChymera**

### CODE REVIEW

**Comment by TheChymera** [comment]
@mgorny hi, can you help me merge this?

**Comment by juippis** [comment]
LGTM. Could you verify whether "-DBUILD_SHARED_LIBS=ON" is needed with EAPI-7 anymore?

**Comment by TheChymera** [comment]
@juippis well, removing that bit changes the cmake command from:

```
cmake -C /var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_SHARED_LIBS=ON -DDCMTK_WITH_ICU=ON -DDCMTK_WITH_TIFF=yes -DDCMTK_WITH_PNG=yes -DDCMTK_WITH_XML=yes -DDCMTK_WITH_ZLIB=yes -DDCMTK_WITH_OPENSSL=yes -DDCMTK_WITH_DOXYGEN=no -DDCMTK_WITH_THREADS=yes -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4
```

to

```
cmake -C /var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4_build/gentoo_common_config.cmake -G Ninja -DCMAKE_INSTALL_PREFIX=/usr -DDCMTK_WITH_ICU=ON -DDCMTK_WITH_TIFF=yes -DDCMTK_WITH_PNG=yes -DDCMTK_WITH_XML=yes -DDCMTK_WITH_ZLIB=yes -DDCMTK_WITH_OPENSSL=yes -DDCMTK_WITH_DOXYGEN=no -DDCMTK_WITH_THREADS=yes -DCMAKE_BUILD_TYPE=Gentoo -DCMAKE_TOOLCHAIN_FILE=/var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4_build/gentoo_toolchain.cmake  /var/tmp/portage/sci-libs/dcmtk-3.6.4/work/dcmtk-3.6.4
```

is that what you meant?

**Comment by TheChymera** [comment]
@juippis The diff between the logs is quite substantial as well:

With `"-DBUILD_SHARED_LIBS=ON`: 
[dcmtk-3.6.4-build.log](https://github.com/gentoo/gentoo/files/3473036/dcmtk-3.6.4-build.log)

Without `"-DBUILD_SHARED_LIBS=ON`: 
[_dcmtk-3.6.4-build.log](https://github.com/gentoo/gentoo/files/3473040/_dcmtk-3.6.4-build.log)

, so I assume it's still needed.

**Comment by juippis** [comment]
I mean, with EAPI-7 cmake-utils.eclass already sets "-DBUILD_SHARED_LIBS=ON" as default so the line _shouldn't_ be needed. Well leave it on for now, I'll test and see what happens.

**Comment by juippis** [comment]
```
 * The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/etc
 * 
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
```
```
# equery f dcmtk | grep /etc
/usr/etc
/usr/etc/dcmtk
/usr/etc/dcmtk/dcmpstat.cfg
/usr/etc/dcmtk/dcmqrscp.cfg
/usr/etc/dcmtk/filelog.cfg
/usr/etc/dcmtk/logger.cfg
/usr/etc/dcmtk/printers.cfg
/usr/etc/dcmtk/storescp.cfg
/usr/etc/dcmtk/storescu.cfg
```
Are these sample configs? Maybe put them under doc? Otherwise everything is fine.

If their install path isn't easily configurable I can merge this for now (and you figure it out in the next bump) but brace for receiving a bug report about this :P

**Comment by TheChymera** [comment]
@juippis I'm pretty sure those are config files used by the program. There's no notice of them being examples, there's plenty of uncommented lines in all of them, and their diffs are rather substantial.

**Comment by juippis** [comment]
Ok, let's not hold this one for it. But please ask upstream why this weird pathing and try to get it changed for next release...

**Comment by TheChymera** [comment]
Ok, I ended up addressing this anyway. It was an easy fix, and maybe best to address this now, lest we forget:

https://github.com/gentoo/gentoo/pull/12656

**Pull request closed without merging**
