### PR TITLE
net-analyzer/ndoutils: Install ndo2db and ndomod.o appropriate to nagios version

### PR DESCRIPTION
**Pull request by bjacquin**
Gentoo Bug #564194

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/netmon

**Comment by mgorny** [comment]
Also, your commit messages seem to be too long!

**Comment by bjacquin** [comment]
Fixed in last push

**Comment by mgorny** [comment]
Sorry, github disagrees ;-).

**Comment by bjacquin** [comment]
Can you be more specific, I'm not sure to understand what is too long :/

**Comment by mgorny** [comment]
Well, unless this differs per user… github truncates it above the comments.

**Comment by bjacquin** [comment]
Is 70 and 74 chars too long ?

**Comment by mgorny** [comment]
I think github uses 69. Coincidence, probably.

**Comment by bjacquin** [comment]
Are you OK then with the commit message ?

**Comment by mgorny** [comment]
Well, rules say 75 so I'm not going to complain though I personally preferred if you stayed below 70. But that's just a trivial note, we're waiting for netmon people to reply.

**Comment by monsieurp** [comment]
Maintainer timeout. We're going to go ahead and merge this PR.

**Comment by jer-gentoo** [comment]
On Tue, 17 Nov 2015 05:50:38 -0800
monsieurp <notifications@github.com> wrote:

> Maintainer timeout. We're going to go ahead and merge this PR.
> 
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/gentoo/gentoo/pull/294#issuecomment-157374825

Please use official Gentoo channels to report bugs and suggest patches.


     jer

**Comment by mgorny** [comment]
Then please be kind enough to read bugs on those official channels because the bug hasn't seen a single reply in a month.

**Pull request merged**
