### PR TITLE
net-misc/r8152: add 2.17.1; drop 2.16.3

### PR DESCRIPTION
**Pull request by jayofdoom**
Leaves -r1 version of 2.16.3. Leaves no stable version of r8152; this is OK as it more accurately reflects the testing of this package (otherwise I would've stablereq'd the -r1 version months ago).

2.17.1 is the new Realtek version of this driver. Removed patches have the fixes integrated in the driver. Tests working on my system with 6.5.11.

### CODE REVIEW

**Comment by Flowdalic** [comment]
Dropping 2.6.13 removes the only stable version for this package. Is this intentional?

**Comment by thesamesam** [comment]
I think you're missing a change from dc068bcf6f51e41c5a9c9f1104b2f162afd7f29b.

**Comment by jayofdoom** [comment]
Thanks @thesamesam, I get rebases for free in Gerrit; I forget sometimes we need to manually do 'em here.

**Comment by jayofdoom** [comment]
Needed to reflect the effective change in the new ebuild as well; that's done now too.

**Pull request closed without merging**
