### PR TITLE
net-analyzer/prettyping: Change to "maintainer needed"

### PR DESCRIPTION
**Pull request by rseichter**
Stepping down as maintainer.

### CODE REVIEW

**Comment by telans** [comment]
Feel free to replace with my information as a proxy maintainer.

```
    <maintainer type="person">
        <email>telans@posteo.de</email>
        <name>Theo Anderson</name>
    </maintainer>
```

`Signed-off-by: Theo Anderson <telans@posteo.de>`

**Comment by telans** [comment]
Well if whoever merges could do that would be appreciated.

**Review by a17r — APPROVED** [review]
Sad to hear.

**Comment by a17r** [comment]
@telans, you asked for it.

**Pull request closed without merging**
