### PR TITLE
net-proxy/3proxy: Version bump to 0.7.1.2

### PR DESCRIPTION
**Pull request by powerman**
I've tried to finish work started by @yurats in https://github.com/gentoo/gentoo-portage-rsync-mirror/pull/107 as per request in https://bugs.gentoo.org/show_bug.cgi?id=547234#c12

I've set license=BSD but I'd like someone to double-check is it correct for this package's license: https://github.com/z3APA3A/3proxy/blob/devel/copying

The keyword=~ppc was dropped from original ebuild, but I've no idea is there any real reason for this. I've added it back, but I don't have PPC to test is it actually supported.

Also this version is already outdates, official site says "It's recommended to move to >=0.8.2 or 0.7.1.4 due to security/stability reasons.". So I'd like to update ebuild at least to 0.7.1.4.

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thank you for the PR. Would you like to take over maintainership of this package?

**Comment by wraeth** [comment]
@monsieurp see also https://bugs.gentoo.org/show_bug.cgi?id=547234

**Comment by monsieurp** [comment]
Thanks for the pointer.

**Comment by powerman** [comment]
> Would you like to take over maintainership of this package?

Yes.

**Comment by monsieurp** [comment]
Right. Merging this PR right away then and then I'll assign this package to you.

**Pull request closed without merging**
