### PR TITLE
sys-auth/sssd: Reintroduce python USE flag

### PR DESCRIPTION
**Pull request by arkamar**

### CODE REVIEW

**Comment by arkamar** [comment]
@Zlogene, @alexxy could you look at this PR please? I'll adapt it to a current state if you agree with this change. Thanks.

**Comment by Dessa** [comment]
the buildsystem is pretty broken still. it does require python when building either way but "detects" a non-present python2; this can be amended by passing --without-python2-bindings while still passing --with-python3-bindings

with python2 EOL this might be a "solution" but that would still unconditionally install the bindings. i guess a configure.ac patch is in order.

**Comment by arkamar** [comment]
@Dessa I agree, `configure.ac` should be patched. I'll look at it.

Btw, it also means that `>=sys-auth/sssd-2` packages currently available in ::gentoo will fail to install in python2 disabled environments.

**Comment by arkamar** [comment]
The patch for `configure.ac` has been accepted in mainstream https://github.com/SSSD/sssd/pull/993

**Pull request closed without merging**
