### PR TITLE
media-gfx/cura: version bump to 4.4.1

### PR DESCRIPTION
**Pull request by Perlovka**

### CODE REVIEW

**Comment by rndevfx** [comment]
Please add `dev-python/requests` - it's a dependency: https://bugs.gentoo.org/697954

**Comment by Perlovka** [comment]
@rndevfx thanks, fixed.

**Comment by juippis** [comment]
I'm sorry, but this PR is a bit outdated with latest Python changes. You'll need to see how python-single-r1 was fixed to current ::gentoo ebuilds, then update this PR accordingly. 

https://blogs.gentoo.org/mgorny/2020/02/10/no-more-python_targets-in-single-r1/

**Comment by Perlovka** [comment]
Closing outdated, new version: https://github.com/gentoo/gentoo/pull/14813

**Pull request closed without merging**
