### PR TITLE
dev-python/cryptography-2.5 version bump

### PR DESCRIPTION
**Pull request by candrews**
dev-python/cryptography-vectors-2.5 version bump https://bugs.gentoo.org/678180
dev-python/cryptography-2.5 version bump https://bugs.gentoo.org/678176

### CODE REVIEW

**Comment by prometheanfire** [comment]
https://github.com/pyca/cryptography/compare/2.4.2...2.5#diff-2eeaed663bd0d25b7e608891384b7298

deps need updating

**Comment by candrews** [comment]
@prometheanfire thanks for pointing that out

I assume we want to keep the dependency on dev-python/idna - or do you want to add an idna use flag?

The only other relevant change seems to be with cffi, so I've force pushed an update to fix that.

How's it look now?

**Comment by prometheanfire** [comment]
Ya, that link didn't work so well...
It does not look we do docs builds so the twine change isn't needed.
`idna` may be useful, but I'd call the use flag something like `u-label`.  I'd add the flag since the support is going away now (the dep was moved to optional in setup.py).

**Comment by candrews** [comment]
> `idna` may be useful, but I'd call the use flag something like `u-label`. I'd add the flag since the support is going away now (the dep was moved to optional in setup.py).

I used `idna` as the use flag name as I don't think this change is as much about `u-label` (according to https://github.com/pyca/cryptography/blob/master/CHANGELOG.rst the `u-label` change was in 2.1 and was backwards incompatible). I may be mistaken; apologies if that's the case. Feel free to let me know and I can change the PR (but you may need to fill me in on what the metadata.xml use flag description should be).

**Comment by prometheanfire** [comment]
nah, idna is fine, I didn't have a great preference.

**Comment by prometheanfire** [comment]
merged

**Pull request closed without merging**
