### PR TITLE
dev-lang/ruby: Fix build for ABI=x32

### PR DESCRIPTION
**Pull request by bjacquin**
Bug: #480238
Bug: #419851

From: http://git.meleeweb.net/gentoo/portage.git/tree/dev-lang/ruby

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/ruby

**Comment by mrueg** [comment]
Are those patches included in upstreams repository? We'd rather want to use new upstream versions than maintaining additional patches offline.

**Comment by bjacquin** [comment]
Yes, they are, please see the svn revision id in the patches

**Comment by mgorny** [comment]
@mrueg, can I merge it or do you want to?

**Comment by graaff** [comment]
This PR cannot be merged because we use patchsets for dev-lang/ruby, not individual in-tree patches. Furthermore it makes no sense to apply this to ruby 1.9 given that we will mask it in a few weeks at the most.

**Comment by mgorny** [comment]
I'm going to assume you will fix the issue in your patchsets, therefore closing this.

**Comment by graaff** [comment]
Now fixed in 2.0.0_p647-r1

**Pull request closed without merging**
