### PR TITLE
sci-libs/gdal: use parquet

### PR DESCRIPTION
**Pull request by t0b3**
Enables read/write parquet data format _(dev-libs/apache-arrow)_

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by t0b3** [comment]
@AndrewAmmerlaan this PR will help to support geoparquet in QGIS :+1: can you give your review? - THX

**Comment by AndrewAmmerlaan** [comment]
At first glance, looks good. But I see that there is version 3.9.0 available upstream, if possible it would be great to introduce the new flag together with the version bump. This avoids the need for a revision bump and overall saves a rebuild for users of this package.

**Comment by t0b3** [comment]
@AndrewAmmerlaan sure that's even better, so I bumped to v3.9.0 :+1: and hope you like it :smile:

**Comment by AndrewAmmerlaan** [comment]
Nice work, Thanks :+1:

**Pull request closed without merging**
