### PR TITLE
games-emulation/ppsspp: bug fix #572606

### PR DESCRIPTION
**Pull request by RobinDX**
Fixed https://bugs.gentoo.org/show_bug.cgi?id=572606

### CODE REVIEW

**Comment by RobinDX** [comment]
@monsieurp

**Comment by RobinDX** [comment]
dev-go/godep ?

**Comment by monsieurp** [comment]
Ignore it, this issue is unrelated to your changes.

**Comment by RobinDX** [comment]
@monsieurp
I think i should close it ,and  commit again .
So QA will check again .

**Pull request closed without merging**
