### PR TITLE
net-libs/rb_libtorrent: fix linking of python bindings

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo-bug: 576910
Thanks to Jan Chren (rindeal) \<dev.rindeal+bugs.gentoo.org@gmail.com\>
for the ebuild, I've simply ported the good bits to the current one.

### CODE REVIEW

**Comment by monsieurp** [comment]
@hwoarang

**Comment by hwoarang** [comment]
Thanks for the ebuild. Can't really test it myself at the moment so if it works for you lets merge it. @monsieurp please? :)

**Comment by sbraz** [comment]
@PPed72 Why do you use `return 1` instead of `die` in the python functions?

**Comment by PPed72** [comment]
I just copied what was in rindeal's ebuild without noticing. If it's necessary I'll fix it.

**Comment by sbraz** [comment]
Well it's quite unusual but I don't know if it's plain wrong. I just noticed while trying to make it compile (https://bugs.gentoo.org/show_bug.cgi?id=581362).

**Comment by rindeal** [comment]
it is plain wrong as there is no `|| die` after calling `python_*()` functions. I've fixed it in my overlay more than a week ago. I probably wrote it initially because of a context switching error when working on some init scripts.

**Comment by sbraz** [comment]
@rindeal care to make a PR? It would be nice to have the python module fixed.

**Comment by PPed72** [comment]
Made PR 1394, also fixes gentoo bug #581274

**Pull request closed without merging**
