### PR TITLE
sys-devel/{llvm, mlir, flang}

### PR DESCRIPTION
**Pull request by dzejej**
Fortran ebuild and deps for llvm. It could compile simple fortran progs, but it requires lib path for fortran specific libs e.g
flang-new -L/usr/lib/llvm/15/lib64 test.f90

In llvm ebuild I added libs necessary for flang - they are masked by flang use flag

Signed-off-by: Janusz Andrzejewski <janusz.andrzejewski@gmail.com>

### CODE REVIEW

**Comment by mgorny** [comment]
Thank you for your effort but we don't accept static libraries in LLVM Gentoo packages and MLIR/Flang is not yet ready for dynamic linking.

**Comment by mgorny** [comment]
https://discourse.llvm.org/t/trying-to-get-mlir-link-mlir-dylib-implemented/66086/24 is the related discussion.

**Comment by dzejej** [comment]
OK. But standard llvm has also static library, for example

/usr/lib/llvm/15/lib64/libLLVMDemangle.a

/usr/lib/llvm/14/lib64/libLLVMDemangle.a

(In fact there are 3 static library in standard llvm instalation)

There is no static libarry in mlir and there is only one static library in flang.

In summary llvm versus flang it is 3:1   :)

**Comment by mgorny** [comment]
Ah, I meant the component libraries (vs "dylib", i.e. "one library to bind them all"). You're using `BUILD_SHARED_LIBS` — this is something I've been considering but unfortunately it's unsupported upstream and that's not something I'd like to venture into if upstream is willing to provide a better option in the near future.

**Comment by band-a-prend** [comment]
@mgorny 
The Termux package mlir as llvm sub-project (build as part of libllvm):
https://github.com/termux/termux-packages/blob/master/packages/libllvm/build.sh
https://github.com/termux/termux-packages/blob/master/packages/libllvm/mlir.subpackage.sh
(`-DLLVM_ENABLE_PROJECTS='clang;clang-tools-extra;lldb;mlir'`)

and then build flang: https://github.com/termux/termux-packages/blob/master/packages/flang/build.sh

But I didn't investigate their build.sh files more in more detail.

**Pull request closed without merging**
