### PR TITLE
python: BSD Userland Fixes + pypy3.10 + strip-lto for python+cargo

### PR DESCRIPTION
**Pull request by vimproved**
--reflink=auto has become the default behaviour in coreutils 9, and is not compatible with BSD userland.

### CODE REVIEW

**Review by thesamesam — APPROVED** [review]

**Review by mgorny — APPROVED** [review]
Sure, WFM. Just please do in all eclasses at once to avoid multiple regens.

**Comment by mgorny** [comment]
Hmm, perhaps we could also stabilize PyPy3.10 and remove PyPy3.9 in the same push.

**Comment by thesamesam** [comment]
The only other hit i see is:
```
dev-cpp/cpp-httplib/cpp-httplib-0.13.0.ebuild:47:       cp -p -R --reflink=auto "${S}/test" ./test || die
dev-cpp/cpp-httplib/cpp-httplib-0.12.6.ebuild:47:       cp -p -R --reflink=auto "${S}/test" ./test || die
dev-cpp/cpp-httplib/cpp-httplib-0.12.3.ebuild:47:       cp -p -R --reflink=auto "${S}/test" ./test || die
```

But if you have any other eclass fixes for diff. userland brewing, let's pile them in together.

**Comment by vimproved** [comment]
I haven't run into anything else yet, but I'll do a world rebuild and see if I get any hits.

**Comment by vimproved** [comment]
Also, would you like me to put cpp-httplib in a separate commit or the same commit as the eclasses?

**Comment by mgorny** [comment]
Ah, sorry, misunderstanding. I meant *one push*, i.e. the same pull request, not *one commit*.

**Comment by vimproved** [comment]
> Ah, sorry, misunderstanding. I meant _one push_, i.e. the same pull request, not _one commit_.

Oh, my bad.

**Comment by thesamesam** [comment]
(Could you re-split the eclass commits?)

**Comment by vimproved** [comment]
> (Could you re-split the eclass commits?)

Done.

**Comment by thesamesam** [comment]
I've cherry-picked the httplib bit, I'll leave the eclass bits for mgorny to cherry-pick and push with other bits he's planning.

**Comment by mgorny** [comment]
@gentoo/python, I've added a bunch of changes related to PyPy3.10 + cargo LTO hack. Please review.

**Review by thesamesam — APPROVED** [review]

**Review by arthurzam — APPROVED** [review]
LGTM, thanks for your work!

**Pull request closed without merging**
