### PR TITLE
media-sound/gst123:fixes src configure error

### PR DESCRIPTION
**Pull request by RobinDX**
Fix src configure error after sys-libs/ncurses  version upgrade to 6
This fixes https://bugs.gentoo.org/show_bug.cgi?id=558182

### CODE REVIEW

**Comment by monsieurp** [comment]
Thank your for the PR. Your commit message is a bit messed up, could you mend it please? Also, "bugfix" alone as a commit message isn't very much explanatory. Could you expend a bit more on what the actual fix is? Something like "Resolve issue with configure and ncurses.". Last but not least, please leave a space after the colon:
"media-sound/gfx: commit message here"

**Comment by monsieurp** [comment]
@SoapGentoo @aballier @gentoochainsaw @yngwin @chutz

**Comment by monsieurp** [comment]
@RobinDX editing the PR title on Github has no effect on the commit message in git i.e. it doesn't change it. We care more about your commit message in git than here. ;)

**Comment by gentoochainsaw** [comment]
On behalf of sound, signing off on commit contents. Once team github is happy with commit message formatting & contents, they may commit to the main tree immediately. RobinDX, thank you.

**Pull request closed without merging**
