### PR TITLE
dev-python/rtslib-fb: version bump to 2.1.61

### PR DESCRIPTION
**Pull request by diogocp**
- Update SRC_URI to point to GitHub instead of PyPI
- Update dependencies (pyudev and six)
- Install man pages

@prometheanfire

### CODE REVIEW

**Comment by monsieurp** [comment]
@prometheanfire ping

**Comment by prometheanfire** [comment]
I'm not sure I agree with not using pypi, can you tell us why you changed that?

**Comment by diogocp** [comment]
Just because the latest releases are not on pypi.

**Comment by prometheanfire** [comment]
created https://github.com/open-iscsi/rtslib-fb/issues/80

**Comment by prometheanfire** [comment]
fixed, can you convert it back to pypi?

**Comment by diogocp** [comment]
Done, although unfortunately the pypi package does not include the man pages.

**Comment by prometheanfire** [comment]
can they be built?

**Comment by diogocp** [comment]
No, I don't think so.

**Comment by diogocp** [comment]
Can we merge this now and figure out what to do about the man pages later?

**Comment by prometheanfire** [comment]
well, merged it, this should have closed, but meh

**Pull request closed without merging**
