### PR TITLE
www-apps/hugo: bump version to 0.50

### PR DESCRIPTION
**Pull request by g4s8**
Bug: https://bugs.gentoo.org/670470
Package-Manager: Portage-2.3.76, Repoman-2.3.16
Signed-off-by: Kirill Che <g4s8.public@gmail.com>

### CODE REVIEW

**Comment by juippis** [comment]
```
>>> Compiling source in /tmp/portage/www-apps/hugo-0.50/work/hugo-0.50 ...
/tmp/portage/www-apps/hugo-0.50/work/hugo-0.50/src/github.com/gohugoio/hugo /tmp/portage/www-apps/hugo-0.50/work/hugo-0.50
mkdir: created directory 'bin'
go: github.com/BurntSushi/locker@v0.0.0-20171006230638-a6e239ea1c69: Get https://proxy.golang.org/github.com/%21burnt%21sushi/locker/@v/v0.0.0-20171006230638-a6e239ea1c69.mod: dial tcp: lookup proxy.golang.org on 192.168.1.1:53: dial udp 192.168.1.1:53: connect: network is unreachable
 * ERROR: www-apps/hugo-0.50::testworld failed (compile phase):
 *   (no error message)
 *
 * Call stack:
 *     ebuild.sh, line 125:  Called src_compile
 *   environment, line 1162:  Called die
 * The specific snippet of code:
 *       GOPATH="${S}" go build -v -ldflags "-X ${EGO_PN}/hugolib.CommitHash=${GIT_COMMIT}" $(usex sass "-tags extended" "") -o ${S}/bin/hugo || die;
 *
 * If you need support, post the output of `emerge --info '=www-apps/hugo-0.50::testworld'`,
 * the complete build log and the output of `emerge -pqv '=www-apps/hugo-0.50::testworld'`.
 * The complete build log is located at '/tmp/portage/www-apps/hugo-0.50/temp/build.log'.
 * The ebuild environment file is located at '/tmp/portage/www-apps/hugo-0.50/temp/environment'.
 * Working directory: '/tmp/portage/www-apps/hugo-0.50/work/hugo-0.50/src/github.com/gohugoio/hugo'
 * S: '/tmp/portage/www-apps/hugo-0.50/work/hugo-0.50'

>>> Failed to emerge www-apps/hugo-0.50, Log file:
```

You should take a look if the new **go-module.eclass** can help you package this program.
https://gitweb.gentoo.org/repo/gentoo.git/tree/eclass/go-module.eclass

**Comment by g4s8** [comment]
@juippis thanks. I replaced `eclass` with `go-module`, it disables network with `export GOFLAGS="-mod=vendor -v -x"`. Can you please check it again?

**Comment by g4s8** [comment]
@juippis also fixed licenses, same as here: https://github.com/gentoo/gentoo/pull/13127#issuecomment-538996606

**Comment by juippis** [comment]
Works now, I asked a member of our license team what should be done with the BSD3-CLAUSE license. I'll get back at these when I receive a reply.

**Comment by juippis** [comment]
Apparently plain BSD is fine, 
https://wiki.gentoo.org/wiki/License_groups/OSI-APPROVED

Thanks!

**Pull request closed without merging**
