### PR TITLE
dev-dotnet/libgdiplus: bump to 4.2, fixes #571610

### PR DESCRIPTION
**Pull request by sbraz**
@Polynomial-C This fixes https://bugs.gentoo.org/show_bug.cgi?id=571610.
I dropped the patches because the underlinking was fixed in the source and the other one was related to compilation with giflib (and this part is fixed too); `-fno-strict-aliasing` seemed to be useless too; eventually there were no references to `ungif` in `configure.ac` so I dropped the whole prepare function.
The package compiled fine with `-j9` so I dropped the `MAKEOPTS` line.
I removed the restriction on tests since they passed.

There is a QA warning, I'm not sure what do do about it:
```
 * QA Notice: Package triggers severe warnings which indicate that it
 *            may exhibit random runtime failures.
 * testgdi.c:48:2: warning: implicit declaration of function 'GdipCreateFromXDrawable_linux' [-Wimplicit-function-declaration]
``` 
Here is the diff with the older ebuild.
```diff
--- libgdiplus-3.12.ebuild      2016-01-06 01:01:00.582932538 +0100
+++ libgdiplus-4.2.ebuild       2016-01-17 21:33:40.221654754 +0100
@@ -1,10 +1,10 @@
-# Copyright 1999-2015 Gentoo Foundation
+# Copyright 1999-2016 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
 EAPI=5
 
-inherit autotools eutils dotnet flag-o-matic
+inherit eutils dotnet
 
 DESCRIPTION="Library for using System.Drawing with mono"
 HOMEPAGE="http://www.mono-project.com"
@@ -31,29 +31,14 @@
        !cairo? ( >=x11-libs/pango-1.20 )"
 DEPEND="${RDEPEND}"
 
-PATCHES=(
-       "${FILESDIR}/${P}-giflib-quantizebuffer.patch"
-       "${FILESDIR}/${P}-underlinking.patch"
-       )
-
-RESTRICT="test"
-
-src_prepare() {
-       epatch "${PATCHES[@]}"
-       sed -i -e 's:ungif:gif:g' configure.ac || die
-       append-flags -fno-strict-aliasing
-       eautoreconf
-}
-
 src_configure() {
        econf \
                --disable-dependency-tracking \
                --disable-static \
-               $(usex cairo "" "--with-pango")
+               $(use_with cairo pango)
 }
 
 src_install () {
-       MAKEOPTS+=" -j1"
        default
 
        dotnet_multilib_comply
```
```

### CODE REVIEW

**Comment by idella** [comment]
The
 warning: implicit declaration of function
is merely a warning and by definition is 'tolerable'

**Comment by idella** [comment]
this appears to have stalled?

**Comment by Heather** [comment]
Thank you, merged: https://github.com/gentoo/gentoo/commit/89964fa44882eb46c7d559e59b4f053a0672c124

**Comment by aleclearmind** [comment]
The new ebuild introduced a subtle bug: `$(usex cairo "" "--with-pango")` does exactly the opposite of `$(use_with cairo pango)`. Also `--without-pango` seems ineffective, using `--with-cairo` instead works, despite not appearing in `./configure --help`. However this will raise a QA warning, the other option is sticking with the old `$(usex cairo "" "--with-pango")` which is less elegant but works as expected.

See bug [#432224](https://bugs.gentoo.org/show_bug.cgi?id=432224#c19).

**Comment by Heather** [comment]
@aleclearmind thanks for that point, may you open pull request for overlay https://github.com/gentoo/dotnet

**Comment by sbraz** [comment]
@Heather I made another pull request to fix this ASAP yesterday, it's already in Gentoo: https://github.com/gentoo/gentoo/commit/311ffe1a3321b5b0f597f2ad124a9874ef16707b

**Pull request closed without merging**
