### PR TITLE
dev-python/nltk: bump to 3.2.2 + 3.5 support

### PR DESCRIPTION
**Pull request by genoob**
Version bump to nltk-3.2.2.
Adding support for python-3.5 (since it's available to install on pip3.5 I figured it would simply require adding 3_5 to PYTHON_COMPAT )

### CODE REVIEW

**Comment by Moiman** [comment]
Can you squash commits into one.

**Comment by genoob** [comment]
If it makes things easier, I've made a patch file for the commit:
https://gist.github.com/genoob/89aabf5e1109e2a365dec0df0de56918#file-77bc24b0afaa26aa4fe28446497d2942e114f626-patch

**Comment by gktrk** [comment]
Ping. Is this PR still valid? 3.2.2. is already in the tree.

**Comment by mgorny** [comment]
Closing due to no activity, and the commits looking like a mess. Feel free to open a new PR if there's still anything to be done here.

**Pull request closed without merging**
