### PR TITLE
dev-libs/rocm-opencl-runtime

### PR DESCRIPTION
**Pull request by justxi**

### CODE REVIEW

**Comment by candrews** [comment]
I'm happy to merge when the QA issue have been resolved. Thanks for your continued contributions!

**Comment by justxi** [comment]
Are the QA issues related to our stuff? I don´t see anything.
In the meantime I am working on the other ebuilds... til dev-util/hip...

**Comment by ionenwks** [comment]
> Are the QA issues related to our stuff? I don´t see anything.
> In the meantime I am working on the other ebuilds... til dev-util/hip...

There was a temporary issue, rebasing should give a proper report.

**Comment by candrews** [comment]
I manually checked and this PR looks good :+1:

**Pull request closed without merging**
