### PR TITLE
Qt 5.15 revdep fixes (missing QPainterPath) and some more

### PR DESCRIPTION
**Pull request by a17r**
Maintainers please ACK.

### CODE REVIEW

**Comment by stefson** [comment]
I'm just strolling by, but I'm almost certain that you're going to be told to please fill out two seperate pullrequests for the two packages you're taking care of here.

**Comment by a17r** [comment]
> I'm just strolling by, but I'm almost certain that you're going to be told to please fill out two seperate pullrequests for the two packages you're taking care of here.

No, I'm a maintainer and only need a short okay to push myself.

**Comment by G10h4ck** [comment]
The retroshare part seems good (proxymaint here)

**Comment by ZeroChaos-** [comment]
ACK for inspectrum, thanks!

**Comment by a17r** [comment]
> No, I'm a maintainer and only need a short okay to push myself.

That said, I'll assume maintainer timeout on the rest.

**Pull request merged**
