### PR TITLE
sys-fs/compsize: EAPI 7, bump to 1.3, update 9999

### PR DESCRIPTION
**Pull request by telans**
Closes: https://bugs.gentoo.org/689144

Package-Manager: Portage-3.0.2, Repoman-2.3.23
Signed-off-by: Theo Anderson <telans@posteo.de>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
There should be multiple commits to this, not just one. 

Let me see, here are the commits:
 - Changes to 1.1 don't seem to require a revbump, but could be that Github is lazy to show all the changes.
 - Bump to 1.3, we can forget about adding 1.2 because no one will have it installed with 1.3 in-tree.
 - Update -9999 ebuild.
 - Update metadata.xml.

That should be 4 commits. I'm not really sure if 1.1 needs to be touched at all either here.

**Comment by telans** [comment]
Thanks for the review @juippis 

I figured it's worth updating 1.1 just to get rid of EAPI 6 (and that probably doesn't need a revbump)

**Comment by juippis** [comment]
Not sure if I missed it the first them then, but yes, updating EAPI usually does require a revbump. Is there a reason to update it though? EAPI-6 is still perfectly fine.

**Comment by telans** [comment]
> Is there a reason to update it though?

Just thought I'd update it along with everything else, unless you'd rather it be left alone. Cheers

**Review by juippis — APPROVED** [review]
Yeah, let's not touch it this time, I'll drop the commit. You'll most likely be removing that anyway since you introduced a newer version with same KEYWORDS. 

Thanks!

**Pull request closed without merging**
