### PR TITLE
dev-python/lxml: Backport py3.12 unicode fix

### PR DESCRIPTION
**Pull request by vimproved**
Pretty sure this doesn't require a revbump since it just adds preprocessor stuff, correct me if I'm wrong.

### CODE REVIEW

**Comment by thesamesam** [comment]
It already has 3.12, so if this makes a difference to runtime at all with 3.12, then yes it does (as it affects the built product - usually what preprocessor stuff is for).

But to put it another way: how did you hit this bug? If it was in something _using_ lxml, then yes, we need a new revision.

**Comment by vimproved** [comment]
> It already has 3.12, so if this makes a difference to runtime at all with 3.12, then yes it does (as it affects the built product - usually what preprocessor stuff is for).
> 
> But to put it another way: how did you hit this bug? If it was in something _using_ lxml, then yes, we need a new revision.

It doesn't build with 3.12 for me without this patch.

**Comment by vimproved** [comment]
> > It already has 3.12, so if this makes a difference to runtime at all with 3.12, then yes it does (as it affects the built product - usually what preprocessor stuff is for).
> > But to put it another way: how did you hit this bug? If it was in something _using_ lxml, then yes, we need a new revision.
> 
> It doesn't build with 3.12 for me without this patch.

Seems that this bug only actually happens on musl. No idea why.

**Comment by thesamesam** [comment]
Huh! Let's revbump to be safe then, as this seems kind of like a grey area (wonder if it behaves correctly on glibc).

**Pull request closed without merging**
