### PR TITLE
dev-perl/Test-Regexp: New ebuild

### PR DESCRIPTION
**Pull request by anthonyryan1**
This package contains the testing harness used by
dev-perl/Regexp-Common, without this package many of it's
tests are skipped even when building with FEATURES="test"

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by kentfredric** [comment]
Upstream for this package only currently says LICENSE = "mit" where I can see, did I miss something?

**Comment by kentfredric** [comment]
And here, because of the Test::Tester dep, you should have a dependency on >=virtual/perl-Test-Simple-1.1.14

So 
```diff
+IUSE="test"

 DEPEND="
    ...
+    test? (  >=virtual/perl-Test-Simple-1.1.14 )
 "
```
RDEPEND should also state a dependency on all of the following ( without versions ):

```
virtual/perl-Test-SImple
virtual/perl-Exporter
```
( And that Exporter dep should be in RDEPEND not DEPEND )

**Comment by anthonyryan1** [comment]
You're correct about the license, given this is just the test harness for another package I copied the license from it (expecting given they're developed together by the same person and only useful together, that they would have the same license). I overlooked that, sorry.

I've added the test use flag and corrected the DEPEND and RDEPEND blocks.

I've removed the coverage and documentation tests as you advised.

Thank you for the feedback, I certainly overlooked quite a bit on this. Please let me know if you have any further suggestions.

**Comment by kentfredric** [comment]
Thanks. :)

**Pull request closed without merging**
