### PR TITLE
x11-misc/sddm: add 9999

### PR DESCRIPTION
**Pull request by Kangie**
renamed some patch files to avoid duplication as they've been stable for three releases

Signed-off-by: Matt Jolly <Matt.Jolly@footclan.ninja>

### CODE REVIEW

**Comment by Kangie** [comment]
With sddm/sddm#1471 indicating that there's no real blockers for the 0.20.0 release (which seems to have been delayed), and an annoying bug on 0.18.1-r6 causing 30+ second shutdowns from plasma on wayland that has been fixed in 'develop' I figured that it was time to revisit this package and confirm that it still builds and passes tests, and that a version bump is quick and painless.

I note that the 0.18.1 pam patches have a PR upstream at sddm/sddm#1165, however it's been sitting since 2019 - how sure are we that these patches need to be applied (based on upstream's comments)? I can't find a bugzilla entry nor any other discussion around them than is available in the linked PR.

I can take a look at rebasing them for -9999 (and submitting a new PR if the old one can't be merged) if that's the case.

**Comment by a17r** [comment]
Creating a 9999 sddm ebuild is not a valid fix for a bug existing in current version. If you point us to the fix for the mentioned problem, we can try to backport it.

We know that sddm builds fine from master, and there's a more up to date version of the ebuild here: https://github.com/gentoo/gentoo/pull/18935 I will see to force-push a non-conflicting branch there in the upcoming days.

**Comment by Kangie** [comment]
Agreed that a live ebuild isn't a "fix" for an existing ebuild - I wouldn't expect an average Gentoo user to unmask "**" for a package unless they have good reason to do so - for me that's 'See if the bug I'm experiencing still exists in the live code'.

I took a brief look at backporting appropriate fixes for 0.19.0/0.18.1, but haven't yet had time to bisect and work out exactly where upstream fixed those issues. My current suspicion is that it was relatively recently.

There is a current PR on upstream/develop to "fix" this issue, even though I can't seem to replicate it via the live ebuild. I think that there is a bit of confusion out there around the 'wayland shutdown delay' issues with SDDM (aside from the fact that they existed when 0.19.0 was released).

My initial assessment however is that backporting appropriate patches is effectively updating 0.19.0 to somewhere close to 'develop' anyway, and figured that adding a live ebuild updated from develop rather than 0.19.0+140 commits would be more appropriate (although pointing SDDM 0.19.0_p<date> at the current head of develop as per your linked PR seems like a much better option).

Regardless, we don't have a live ebuild in ::gentoo and I can't see a reason *not* to add one for users that want to unmask it so I'll ask again:

How sure are we that the `revert-honor-pam` patches need to be applied? The PR for those upstream has been outstanding since 2019, so they obviously don't think that it's an issue.

I'm happy to do the work to reapply them for the live ebuild if there's a valid reason to do so, which will have also enable us to update your PR to the current head of develop.

I'm also happy to pull in/update the ebuild and patches from the linked PR to save you some work! If not I can just keep the live ebuild in a local overlay.

I note that as a contributor I'm assuming that open PRs that haven't had any action in 6+ months are dead and should be ignored.

**Comment by jospezial** [comment]
@Kangie There is https://github.com/gentoo/qt/blob/master/x11-misc/sddm/sddm-9999.ebuild
Could be easier to do changes there first.

**Comment by Kangie** [comment]
@a17r FYI I've rebased all of the patches on the current head of `develop`, it compiles, but there's a bug I'm tracking down where sddm either isn't writing the cookie to /tmp like it's supposed to, or permissions are wrong.

**Comment by a17r** [comment]
As has been said, qt overlay has an existing sddm-9999 ebuild for you to try.

Keeping these huge patches is not sustainable. The effort is laudable, but we would not be keeping them without their current version submitted to upstream review. If their respective original PRs are stale, you might want to drop them a note, and after some time, consider opening your own PR with the rebased patches, since you've done the work already.

**Comment by Kangie** [comment]
Sounds like a plan - I'm in the middle of spinning up a VM for some quick testing anyway. I'll close this PR and see what can be done about getting the various stale patches that I updated from your PR upstreamed so that this can be revisited.

**Pull request closed without merging**
