### PR TITLE
media-libs/libplacebo: update to v2.72.2

### PR DESCRIPTION
**Pull request by haasn**
Simple bug fix release, most notably extending the range of supported
glslang versions. There's no point in keeping the old version around.

Signed-off-by: Niklas Haas <git@haasn.xyz>
Closes: https://bugs.gentoo.org/753602

### CODE REVIEW

**Review by juippis — APPROVED** [review]
For whatever reason, looks like tests fail always when `opengl` USE is enabled.
```
>>> Source compiled.
>>> Test phase: media-libs/libplacebo-2.72.2
 * abi_x86_32.x86: running multilib-minimal_abi_src_test
meson test -C /var/tmp/portage/gpm/portage/media-libs/libplacebo-2.72.2/work/libplacebo-v2.72.2-abi_x86_32.x86 --num-processes 16 -t 10
ninja: Entering directory `/var/tmp/portage/gpm/portage/media-libs/libplacebo-2.72.2/work/libplacebo-v2.72.2-abi_x86_32.x86'
ninja: no work to do.
1/7 context.c            OK             0.02s
2/7 colorspace.c         OK             0.02s
3/7 dither.c             OK             0.04s
4/7 dummy.c              OK             0.08s
5/7 filters.c            OK             0.01s
6/7 utils.c              OK             0.01s
7/7 opengl_surfaceless.c FAIL           0.13s (exit status 1)

Ok:                 6   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gpm/portage/media-libs/libplacebo-2.72.2/work/libplacebo-v2.72.2-abi_x86_32.x86/meson-logs/testlog.txt
 * ERROR: media-libs/libplacebo-2.72.2::testworld failed (test phase):
 *   tests failed
```
```
[ERROR] >>> Not all runs were successful.
atom: =media-libs/libplacebo-2.72.2, USE flags: 'glslang -lcms opengl -shaderc -vulkan'
atom: =media-libs/libplacebo-2.72.2, USE flags: '-glslang lcms opengl shaderc vulkan'
atom: =media-libs/libplacebo-2.72.2, USE flags: 'glslang lcms opengl -shaderc -vulkan'
```

**Comment by haasn** [comment]
@juippis Can you attach the contents of the referenced `/var/tmp/portage/gpm/portage/media-libs/libplacebo-2.72.2/work/libplacebo-v2.72.2-abi_x86_32.x86/meson-logs/testlog.txt`?

**Comment by juippis** [comment]
[libplacebo-2.7.2-meson-testsuite.log](https://github.com/gentoo/gentoo/files/5561551/libplacebo-2.7.2-meson-testsuite.log)

I see `Failed to create /var/tmp/portage/.cache for shader cache (Permission denied)---disabling.` but no idea where this path is coming from, but most likely related to my containers that'd need some maintenance.

And only happens with `opengl` USE on.

**Comment by haasn** [comment]
That cache error seems unrelated. The actual test that fails is the roundtrip of 3D `rgba32f` textures. As for why that's the case, I have no idea, especially since it works for 2D. I'd probably have to reproduce it myself. Does the error happen consistently for you?

I have almost the same GPU, but I'm not sure how you set up your test environment. (On my end, the portage sandbox prevents the test from accessing the GPU altogether)

**Comment by juippis** [comment]
Yep, always with `USE="opengl"` it fails. I tested it on my live systemd and it fails too, but at least I didn't get the permission denied this time. Normally I use unprivileged LXD containers.

With `USE="-opengl`" it always passes, regardless of other USE flags.

Let me know if you want something more.

**Pull request closed without merging**
