### PR TITLE
net-libs/rb_libtorrent: fix miscellaneous issues

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo-bug: 581274

### CODE REVIEW

**Comment by monsieurp** [comment]
@hwoarang pls review

**Comment by monsieurp** [comment]
@hwoarang has gone AWOL. @rindeal could you kindly ack this PR? apparently, you filed the bug report as well in the first place.

**Comment by rindeal** [comment]
This is the exact copy of the fix + the `return` -> `die()` thing, which I suggested in some other discussion. I think it should be merged ASAP as the build fails in 100% cases on new installations without it, so it probably cannot get any worse.

**Comment by monsieurp** [comment]
Okay thanks. Will shortly merge it.

**Pull request closed without merging**
