### PR TITLE
mail-client/alot: fix tests and add live ebuild

### PR DESCRIPTION
**Pull request by GuillaumeSeren**

### CODE REVIEW

**Comment by juippis** [comment]
This doesnt apply cleanly anymore, could you please rebase against fresh master?

Dont add python3.5 anymore, its been removed.

**Comment by GuillaumeSeren** [comment]
Hello @juippis 
Thank you for your time.

I have upgraded the branch, according to your feedback.

**Comment by juippis** [comment]
Sorry if I failed to see it the first time, but please don't revbump in the first commit just to fix failing tests. That will cause everyone to rebuild it, while a small minority will be interested in tests.
Also you have a typo in your message box, `Close:`. 
Other than that, it builds fine.

**Comment by GuillaumeSeren** [comment]
Hello @juippis ,

> but please don't revbump in the first commit just to fix failing tests. 

I am not sure exactly what you expect here, but to avoid people from upgrading just for the test,
I did not add the test on the 0.8.1 but only on the 0.8.1-r1 and 9999 version.

I fixed the typo on the `Close` tag of the first commit.

Thank you for your time !

**Comment by GuillaumeSeren** [comment]
Hey @juippis 
I have upgraded the branch, instead of adding a new 0.8.1-r1 I added the test fix in the 0.8.1

:coffee:

**Pull request closed without merging**
