### PR TITLE
dev-lang/mono-basic: restrict tests

### PR DESCRIPTION
**Pull request by ConiKost**
Tests do need internet access, so network-sandbox must be disabled.
But tests also seems to fail. No response from upstream.

Also bumped to EAPI="7".

Closes: https://bugs.gentoo.org/656682
Closes: https://bugs.gentoo.org/655900
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>
Package-Manager: Portage-2.3.50, Repoman-2.3.11

### CODE REVIEW

**Comment by ConiKost** [comment]
I bumped also to EAPI=7, as I had in mind, that with a new EAPI I should rev bump? If not needed, will change.

**Comment by mgorny** [comment]
Then please mention it in the commit message.

**Comment by ConiKost** [comment]
Ok, done :-)

**Comment by mgorny** [comment]
Looks good at a first glance. My testing queue is quite big right now, so please ping me later if nobody else gets around to test it.

**Pull request closed without merging**
