### PR TITLE
dev-db/mariadb: add 10.4.28, 10.5.19, 10.6.12, 10.11.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Tests pass on ~amd64.

```bash
--- mariadb-10.4.27.ebuild      2023-01-25 14:11:28.191851431 +0000
+++ mariadb-10.4.28.ebuild      2023-02-10 07:16:59.992893659 +0000
@@ -1,7 +1,7 @@
 # Copyright 1999-2023 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI="7"
+EAPI="8"
 SUBSLOT="18"
 
 JAVA_PKG_OPT_USE="jdbc"
@@ -32,7 +32,7 @@
        ?? ( tcmalloc jemalloc )
        static? ( yassl !pam )"
 
-KEYWORDS="~alpha amd64 ~arm arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
 
 # Shorten the path because the socket path length must be shorter than 107 chars
 # and we will run a mysql server during test phase
@@ -101,6 +101,10 @@
        !dev-db/mariadb:10.6
        !dev-db/mariadb:10.7
        !dev-db/mariadb:10.8
+       !dev-db/mariadb:10.9
+       !dev-db/mariadb:10.10
+       !dev-db/mariadb:10.11
+       !dev-db/mariadb:11.0
        !<virtual/mysql-5.6-r11
        !<virtual/libmysqlclient-18-r1
        ${COMMON_DEPEND}
@@ -199,6 +203,8 @@
 
 src_prepare() {
        eapply "${WORKDIR}"/mariadb-patches
+       eapply "${FILESDIR}"/${PN}-10.6.11-gssapi.patch
+       eapply "${FILESDIR}"/${PN}-10.6.12-gcc-13.patch
 
        eapply_user
```

```bash
--- mariadb-10.5.18.ebuild      2023-01-25 14:11:28.191851431 +0000
+++ mariadb-10.5.19.ebuild      2023-02-10 07:16:59.992893659 +0000
@@ -1,7 +1,7 @@
 # Copyright 1999-2023 Gentoo Authors
 # Distributed under the terms of the GNU General Public License v2
 
-EAPI="7"
+EAPI="8"
 SUBSLOT="18"
 
 JAVA_PKG_OPT_USE="jdbc"
@@ -10,7 +10,7 @@
        multiprocessing java-pkg-opt-2 cmake
 
 # Patch version
-PATCH_SET="https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.5.17-patches-01.tar.xz"
+PATCH_SET="https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.5.19-patches-01.tar.xz"
 
 SRC_URI="mirror://mariadb/${PN}-${PV}/source/${P}.tar.gz
        ${PATCH_SET}"
@@ -31,7 +31,7 @@
        ?? ( tcmalloc jemalloc )
        static? ( yassl !pam )"
 
-KEYWORDS="~alpha amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
 
 # Shorten the path because the socket path length must be shorter than 107 chars
 # and we will run a mysql server during test phase
@@ -108,6 +108,10 @@
        !dev-db/mariadb:10.6
        !dev-db/mariadb:10.7
        !dev-db/mariadb:10.8
+       !dev-db/mariadb:10.9
+       !dev-db/mariadb:10.10
+       !dev-db/mariadb:10.11
+       !dev-db/mariadb:11.0
        !<virtual/mysql-5.6-r11
        !<virtual/libmysqlclient-18-r1
        selinux? ( sec-policy/selinux-mysql )
@@ -207,6 +211,8 @@
 
 src_prepare() {
        eapply "${WORKDIR}"/mariadb-patches
+       eapply "${FILESDIR}"/${PN}-10.6.11-gssapi.patch
+       eapply "${FILESDIR}"/${PN}-10.6.12-gcc-13.patch
 
        eapply_user
```

```bash
--- mariadb-10.6.11-r1.ebuild   2023-02-06 05:01:10.430348044 +0000
+++ mariadb-10.6.12.ebuild      2023-02-10 07:16:59.993893662 +0000
@@ -11,7 +11,7 @@
 
 HOMEPAGE="https://mariadb.org/"
 SRC_URI="mirror://mariadb/${PN}-${PV}/source/${P}.tar.gz
-       https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.6.10-patches-01.tar.xz"
+       https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.6.12-patches-01.tar.xz"
 
 DESCRIPTION="An enhanced, drop-in replacement for MySQL"
 LICENSE="GPL-2 LGPL-2.1+"
@@ -106,6 +106,10 @@
        !dev-db/mariadb:10.5
        !dev-db/mariadb:10.7
        !dev-db/mariadb:10.8
+       !dev-db/mariadb:10.9
+       !dev-db/mariadb:10.10
+       !dev-db/mariadb:10.11
+       !dev-db/mariadb:11.0
        !<virtual/mysql-5.6-r11
        !<virtual/libmysqlclient-18-r1
        selinux? ( sec-policy/selinux-mysql )
@@ -207,7 +211,7 @@
        eapply "${WORKDIR}"/mariadb-patches
        eapply "${FILESDIR}"/${PN}-10.6.11-gssapi.patch
        eapply "${FILESDIR}"/${PN}-10.6.11-include.patch
-       eapply "${FILESDIR}"/${PN}-10.6.11-gcc-13.patch
+       eapply "${FILESDIR}"/${PN}-10.6.12-gcc-13.patch
 
        eapply_user
```

```bash
--- mariadb-10.6.12.ebuild      2023-02-10 07:16:59.993893662 +0000
+++ mariadb-10.11.1.ebuild      2023-02-10 07:16:59.991893655 +0000
@@ -11,7 +11,7 @@
 
 HOMEPAGE="https://mariadb.org/"
 SRC_URI="mirror://mariadb/${PN}-${PV}/source/${P}.tar.gz
-       https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.6.12-patches-01.tar.xz"
+       https://github.com/hydrapolic/gentoo-dist/raw/master/mariadb/mariadb-10.11.1-patches-01.tar.xz"
 
 DESCRIPTION="An enhanced, drop-in replacement for MySQL"
 LICENSE="GPL-2 LGPL-2.1+"
@@ -28,7 +28,8 @@
        ?? ( tcmalloc jemalloc )
        static? ( yassl !pam )"
 
-KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~loong ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+#KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~loong ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86 ~amd64-linux ~x86-linux ~ppc-macos ~x64-macos ~x64-solaris ~x86-solaris"
+KEYWORDS=""
 
 # Shorten the path because the socket path length must be shorter than 107 chars
 # and we will run a mysql server during test phase
@@ -37,6 +38,7 @@
 # Be warned, *DEPEND are version-dependant
 # These are used for both runtime and compiletime
 COMMON_DEPEND="
+       dev-libs/libfmt:=
        >=dev-libs/libpcre2-10.34:=
        >=sys-apps/texinfo-4.7-r1
        sys-libs/ncurses:0=
@@ -96,22 +98,16 @@
        static? ( sys-libs/ncurses[static-libs] )
 "
 RDEPEND="${COMMON_DEPEND}
-       !dev-db/mysql !dev-db/mariadb-galera !dev-db/percona-server !dev-db/mysql-cluster
-       !dev-db/mariadb:0
-       !dev-db/mariadb:5.5
-       !dev-db/mariadb:10.1
-       !dev-db/mariadb:10.2
+       !dev-db/mysql !dev-db/percona-server
        !dev-db/mariadb:10.3
        !dev-db/mariadb:10.4
        !dev-db/mariadb:10.5
+       !dev-db/mariadb:10.6
        !dev-db/mariadb:10.7
        !dev-db/mariadb:10.8
        !dev-db/mariadb:10.9
        !dev-db/mariadb:10.10
-       !dev-db/mariadb:10.11
        !dev-db/mariadb:11.0
-       !<virtual/mysql-5.6-r11
-       !<virtual/libmysqlclient-18-r1
        selinux? ( sec-policy/selinux-mysql )
        server? (
                columnstore? ( dev-db/mariadb-connector-c )
```

### CODE REVIEW

**Comment by hydrapolic** [comment]
Added the gssapi patch from 10.6 to 10.4/10.5 as it failed on one of my machine. Also added the gcc-13 patch if anyone needs it.

**Comment by vaukai** [comment]
Recommendation for `virtual/jdk` and `virtual/jre` is putting the [`:*` slot operator](https://wiki.gentoo.org/wiki/Java_Developer_Guide#JDK/JRE).

**Comment by hydrapolic** [comment]
> Recommendation for `virtual/jdk` and `virtual/jre` is putting the [`:*` slot operator](https://wiki.gentoo.org/wiki/Java_Developer_Guide#JDK/JRE).

Thanks, can test out for next version (https://bugs.gentoo.org/894276).

**Comment by thesamesam** [comment]
Thanks! Please make sure you check over `pkgdiff -b old.ebuild new.ebuild` output (`-b` is for build-system only changes, you can do it without `-b` too and have a quick look as well) to see if we need to adapt the ebuild at all, especially for 10.11. It's unkeyworded so I figured I'd comment and give you a chance to look over it first.

(This is a useful thing to do in general, fwiw)

Many thanks!

**Comment by hydrapolic** [comment]
> 

Thanks @thesamesam, I'm sure we'll improve the ebuild for 11.x in the future, it's just a first version working for my use-case.

**Pull request closed without merging**
