### PR TITLE
dev-python/traitlets: Fixes + Version bump

### PR DESCRIPTION
**Pull request by marbre**
dev-python/six is required for traitlets > 4.0.0. I assume this was unnoticed since it is installed on most systems. I think a revision bump is not necessary. Furthermore, the PR includes a bump to 4.2.2.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/python

**Comment by marbre** [comment]
I think this should be assigned to @gentoo/sci.

**Comment by monsieurp** [comment]
@jlec @SoapGentoo then.

**Comment by marbre** [comment]
@jlec @SoapGentoo I we could go forward with this request.

**Comment by SoapGentoo** [comment]
@marbre Sorry for taking so long, I'm a bit swamped atm.

**Comment by marbre** [comment]
@SoapGentoo No problem, take the time you need for the following requests :)

**Pull request closed without merging**
