### PR TITLE
dev-libs/libcec: bump to 4.0.7, fixes and improvements 

### PR DESCRIPTION
**Pull request by Karlson2k**
* Fixed man page for cec-client
* Fixed ChangeLog
* Fixed Dependencies
* Added Linux kernel CEC Framework support
* cec-client and other test tools are optional now (new USE flag)
* udev is optional now (libcec could use SYSFS for detection)
* Added installation of USB-CEC rules for udev
* Fixed byte-compiling Python module

### CODE REVIEW

**Comment by Karlson2k** [comment]
Updated with additional improvements.
@candrews Kodi ebuild dependencies need to be updated as libcec-6.x (ebuild is not prepared yet) is not compatible with Leia.

**Comment by Karlson2k** [comment]
Added missing metadata.xml changes

**Comment by Karlson2k** [comment]
Should I squash down commits for clarity?

**Comment by Karlson2k** [comment]
@whyman It's ready to be merged.

**Comment by whyman** [comment]
@Karlson2k can you squash and rebase please?

**Comment by Karlson2k** [comment]
> @Karlson2k can you squash and rebase please?

@whyman Done.

**Comment by Karlson2k** [comment]
Updated once more with one minor fix.

**Comment by candrews** [comment]
> Kodi ebuild dependencies need to be updated as libcec-6.x (ebuild is not prepared yet) is not compatible with Leia.

Thank you! Can you please submit a PR when appropriate?

And thank you very much for all of your work, your contributions are greatly valued.

**Comment by candrews** [comment]
@whyman can we merge this now?

**Comment by whyman** [comment]
I will try to get this merged soon

**Comment by Karlson2k** [comment]
> I will try to get this merged soon

Great.
It has been tested on my HTPC for more than two week, so the next request will be stabilisation of this version. :)

**Comment by Karlson2k** [comment]
@whyman Rebased again for your convenience.

**Pull request closed without merging**
