### PR TITLE
games-emulation/ryujinx: bump and add missing deps

### PR DESCRIPTION
**Pull request by Tatsh**
These may be linking opportunistically (or may be actually required). This change will make builds more consistent across different machines.

```
$ readelf -d /usr/share/ryujinx-1.1.1093/libsoundio.so

Dynamic section at offset 0x13db8 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libjack.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libpulse.so.0]
 0x0000000000000001 (NEEDED)             Shared library: [libasound.so.2]
```

```
$ readelf -d /usr/share/ryujinx-1.1.1093/libglfw-wayland.so.3.3

Dynamic section at offset 0x40cf0 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libm.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libwayland-client.so.0]
```

```
$ readelf -d /usr/share/ryujinx-1.1.1093/libglfw.so.3.3

Dynamic section at offset 0x44df0 contains 27 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libX11.so.6]
```

### CODE REVIEW

**Comment by xgqt** [comment]
Needs revbump.

**Comment by xgqt** [comment]
Maybe bump to new version also? :D

**Comment by Tatsh** [comment]
> Maybe bump to new version also? :D

Will do.

**Comment by xgqt** [comment]
thx, lgtm, will build & merge in

**Pull request closed without merging**
