### PR TITLE
net-p2p/litecoin*: Fixing dependency bug and version bumps 

### PR DESCRIPTION
**Pull request by marcpopp**
This pull request is fixing 3 bugs. 
I didn't file one each, I don't know, what your preference is.

https://bugs.gentoo.org/show_bug.cgi?id=592018
https://bugs.gentoo.org/show_bug.cgi?id=592100
https://bugs.gentoo.org/show_bug.cgi?id=592112

Changes to existing ebuild and new ebuilds tested locally with qt4 and qt5.

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks a lot. I'm going to have to close this PR due to your first commit. Do not pull from master after creating your branch please, it messes up the branch altogether. File a similar PR without pulling from master this time round. Cheers.

**Comment by monsieurp** [comment]
Also, fixing three bugs in one single PR is fine and encouraged.

**Comment by blueness** [comment]
each fix should be one commit, and multiple related commits in one pr is fine

**Comment by marcpopp** [comment]
No Problem! Thank you for the info. I opened a new Request: https://github.com/gentoo/gentoo/pull/2144

**Pull request closed without merging**
