### PR TITLE
dev-python/pandas-datareader: new package

### PR DESCRIPTION
**Pull request by TheChymera**
Package-Manager: Portage-2.3.49, Repoman-2.3.10

### CODE REVIEW

**Comment by mgorny** [comment]
```
>>> Test phase: dev-python/pandas-datareader-0.7.0
 * python2_7: running distutils-r1_run_phase python_test
=============================================================== test session starts ===============================================================
platform linux2 -- Python 2.7.15, pytest-3.8.0, py-1.5.4, pluggy-0.7.1
rootdir: /tmp/portage/dev-python/pandas-datareader-0.7.0/work/pandas-datareader-0.7.0, inifile:
plugins: mock-1.10.0

========================================================== no tests ran in 0.01 seconds ===========================================================
ERROR: file not found: xX
```

Also, `pytest` is the new way of calling pytest.

**Comment by TheChymera** [comment]
@mgorny  ok

**Comment by mgorny** [comment]
```
============================== 68 failed, 19 passed, 58 skipped, 40 xfailed, 1 xpassed, 8 warnings in 84.62 seconds ===============================
```
[dev-python:pandas-datareader-0.7.0:20180928-083840.log](https://github.com/gentoo/gentoo/files/2427435/dev-python.pandas-datareader-0.7.0.20180928-083840.log)

**Comment by mgorny** [comment]
Read the big section on how Internet access is forbidden and lets users send Internet bills over to you: https://devmanual.gentoo.org/ebuild-writing/functions/src_test/index.html

**Comment by TheChymera** [comment]
@mgorny ok, I had a alook at other ebuilds and I can't figure out what best to do. Do I:

1. `RESTRICT="test"`
2. sed/rm all of the network bits out (which is more than half the test suite)
3. sed/rm all of the network bits out only `if has network-sandbox ${FEATURES}`

?

**Comment by mgorny** [comment]
1 or 2. Figure out how useful the suite is without Internet. Also file a request upstream to consider mocking/replay-based tests since using Internet services is unreliable at best.

**Comment by TheChymera** [comment]
The test suite is not particularly useful without internet connectivity, since this is what the package does, read data from the internet. Upstream seems uninterested in solving the issue: https://github.com/pydata/pandas-datareader/issues/586

So I have moved to restrict testing.

**Comment by mgorny** [comment]
Thanks. I have verified that all but two Yahoo tests consistently pass on all impls. I'll merge now.

**Pull request closed without merging**
