### PR TITLE
net-nntp/pan: fix crash at startup

### PR DESCRIPTION
**Pull request by PPed72**
Gentoo bug #570108

### CODE REVIEW

**Comment by Tranquility** [comment]
Thanks, but please don't patch the old version. Since your patch changes what gets installed for the user you need to bump the revision. So create -r2 and only do the change there.

**Comment by PPed72** [comment]
Done...

**Comment by monsieurp** [comment]
@Tranquility do you deem the contribution good to go? Please ack and I'll merge it, and close the bug whilst at it.

**Comment by Tranquility** [comment]
@PPed72 Thanks for your contribution! 

I merged it and closed the bug.

**Pull request merged**
