### PR TITLE
net-wireless/wpa_supplicant: Fix #615872

### PR DESCRIPTION
**Pull request by charIes17**

### CODE REVIEW

**Comment by charIes17** [comment]
@ZeroChaos- 
I have seen you commit https://gitweb.gentoo.org/repo/gentoo.git/commit/net-wireless/wpa_supplicant?id=dc60b14d 
There still remains the wrongly named .desktop file (see https://bugs.gentoo.org/615872) which is fixed in #5236 
( mv "${ED%/}"/usr/share/applications/wpa_gui{-wpa_supplicant,}.desktop || die ].

**Comment by kristjanbb** [comment]
src_configure() additions required to solve [bug 628638](https://bugs.gentoo.org/show_bug.cgi?id=628638)

		# Enable essentials for AP/P2P
		if use ap || use p2p ; then
			# Enabling HT support (802.11n)
			Kconfig_style_config IEEE80211N
	
			# Enabling VHT support (802.11ac)
			Kconfig_style_config IEEE80211AC
		fi

**Comment by flappyports** [comment]
@charIes17 still working this?

**Comment by charIes17** [comment]
As everything contributed to wpa_supplicant gets completely ignored, maybe its better to not waste any more time on it.

**Pull request closed without merging**
