### PR TITLE
Bump qross{core,python} version and move them to Qt5 build

### PR DESCRIPTION
**Pull request by 0xd34df00d**
The only packages depending on them belong to LeechCraft, so nothing would be broken by moving to Qt5.

### CODE REVIEW

**Comment by 0xd34df00d** [comment]
@SoapGentoo this kinda relates to leechcraft.

**Comment by SoapGentoo** [comment]
@0xd34df00d please make the **COMMITMSG**s in standard Gentoo format: https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by 0xd34df00d** [comment]
@SoapGentoo done, thanks!

Mentioned both packages in a shell-ish syntax, hopefully that's OK. Let me know if there is a better way of handling this (naturally, these two packages go hand-in-hand, it doesn't make much sense to bump or change Qt's version of one of them without doing that with the other as well).

**Comment by SoapGentoo** [comment]
@0xd34df00d sure, could you just split up the commit? In general `app-A/{foo,bar}:` makes it harder to grep the log, hence we like to keep package commits separate (if possible). So you could first bump the core one, then the python one, and the depgraph would always be happy. Last thing: can you drop `src_configure()` and just do a global `mycmakeargs=( -DUSE_QT5=ON )`?

**Comment by 0xd34df00d** [comment]
@SoapGentoo done. I'm still not sure how to handle the move to Qt5 of -9999 in this manner, though. Both packages have to be built with the same Qt version (and this is the reason I didn't split the bump and Qt version change for the libraries), so the change should happen to both packages in one commit.

I've thus removed this change from this PR, it can be done either later in this PR or in a different one.

**Pull request closed without merging**
