### PR TITLE
Boost cleanup

### PR DESCRIPTION
**Pull request by SoapGentoo**

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@zpuskas Mind if I drop 4.0.1-r1 of kicad? It would help me in cleaning up older boost versions

**Comment by SoapGentoo** [comment]
@hydrapolic any idea why `dev-db/percona-xtrabackup` is pinned to version 1.59 of `dev-libs/boost`? I'd link to clean it up and get rid of the ancient versions

**Comment by zpuskas** [comment]
@SoapGentoo: just to feed the gnomes of bureaucracy and leave a paper trail, as per our IRC convo, feel free to remove kicad-4.0.1-r1

**Comment by hydrapolic** [comment]
@SoapGentoo, I wasn't able to compile percona-xtrabackup with other boost versions. I tried with version 2.4.4 and boost 1.60/1.61 with no luck. Thanks for your new revision, will check out.

**Pull request closed without merging**
