### PR TITLE
dev-util/gprofng-gui: new package, add 1.1

### PR DESCRIPTION
**Pull request by vaukai**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by thesamesam** [comment]
When I open it, almost al buttons are greyed out.

I do see:
```
$ GDK_SCALE=3 gp-display-gui 
Cannot find resource bundle.
```

Is it related?

**Comment by thesamesam** [comment]
Nevermind! I was foolish and didn't have binutils[gprofng] here.

**Comment by vaukai** [comment]
> Nevermind! I was foolish and didn't have binutils[gprofng] here.

Add it to `RDEPEND`?

**Comment by thesamesam** [comment]
Yeah, will do now (it can work remotely somehow but I'm not going to worry about that).

However, when I try to profile an application ("create an experiment", then just pick anything like konsole/dolphin/whatever), it fails to run because it looks in `/usr/local`. But if I build with autotools, it works OK.

**Comment by thesamesam** [comment]
`Makefile.am` does:
```
gp-display-gui: $(srcdir)/gprofng-gui.sh
        @echo "================= $@"
        sed -e "s~REPLACE_ME_WITH_VERSION~$(VERSION)~" < $(srcdir)/gprofng-gui.sh \
          | sed -e "s~GPROFNG_bindir=~GPROFNG_bindir='$(bindir)'~" \
          | sed -e "s~GPROFNG_libdir=~GPROFNG_libdir='$(libdir)'~" \
          | sed -e "s~GPROFNG_datadir=~GPROFNG_datadir='$(datadir)'~" \
          > $@
        chmod +x $@
```

But I wonder -- is there a reason to not use autotools here?

This works OK for me (I think):
```
# Copyright 2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

inherit java-pkg-2

DESCRIPTION="Full-fledged graphical interface to operate gprofng"
HOMEPAGE="https://www.gnu.org/software/gprofng-gui/"
SRC_URI="https://ftp.gnu.org/gnu/gprofng-gui/${P}.tar.gz"
S="${WORKDIR}/${P}"

LICENSE="GPL-2"
SLOT="0"
KEYWORDS="~amd64"

DEPEND=">=virtual/jdk-1.8:*"
RDEPEND="
        sys-devel/binutils:*[gprofng]
        >=virtual/jre-1.8:*
"

src_prepare() {
        default
        java-pkg-2_src_prepare
}
```

**Comment by vaukai** [comment]
> `Makefile.am` does:
> 
> ```
> gp-display-gui: $(srcdir)/gprofng-gui.sh
>         @echo "================= $@"
>         sed -e "s~REPLACE_ME_WITH_VERSION~$(VERSION)~" < $(srcdir)/gprofng-gui.sh \
>           | sed -e "s~GPROFNG_bindir=~GPROFNG_bindir='$(bindir)'~" \
>           | sed -e "s~GPROFNG_libdir=~GPROFNG_libdir='$(libdir)'~" \
>           | sed -e "s~GPROFNG_datadir=~GPROFNG_datadir='$(datadir)'~" \
>           > $@
>         chmod +x $@
> ```
> 
> But I wonder -- is there a reason to not use autotools here?

Missing experience with `autotools`, `Makefile*,` ...
But I see Makefile calls javac (directly instead of using ejavac)

**Comment by thesamesam** [comment]
Thank you! I'm going to see how the autotools build goes. I've used your commit then changed to autotools as you deserve the credit.

**Pull request closed without merging**
