### PR TITLE
net-fs/samba: pam+winbind authentication

### PR DESCRIPTION
**Pull request by vieridipaola**
PAM winbind authentication configuration.

Bug: https://bugs.gentoo.org/590374
Signed-off-by: Vieri <rentorbuy@yahoo.com>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by Polynomial-C** [comment]
What about samba-4.7.x and samba-4.9.x versions?

**Comment by vieridipaola** [comment]
Sorry, this is my first "successful" commit. I only worked on the currently stable Samba ebuild because that's the one I use in production. So I'm sure it works as expected. The patch is trivial, and should work just fine on ~, but I can't really test it right now. Is it necessary to work on the latest ebuild?

Also, maybe my commit could be improved if it were a patch and not a "new" ebuild. When modifying an ebuild, I guess I shouldn't rename the file, but edit it. This way, the commit would be a diff.
Am I right?

**Comment by vieridipaola** [comment]
As requested, feature added to samba-4.7.x, samba-4.8.x, and samba-4.9.x

**Comment by Polynomial-C** [comment]
Sorry, I became sick meanwhile and lost track of this PR. Can you please re-base your changes against current samba packages (there's now also `samba-4.10.0_rc1` in the tree)?
Just drop me another comment here when you've finsihed the rebaisng and I gonna merge the PR.

**Comment by vieridipaola** [comment]
No worries. Hope you fully recovered.

I updated the commit.

**Pull request closed without merging**
