### PR TITLE
Enable support for managing GNOME Shell extensions with Google Chrome browser and derivatives

### PR DESCRIPTION
**Pull request by nE0sIghT**
1. Added [gnome-extra/gs-chrome-connector](https://github.com/nE0sIghT/chrome-gnome-shell) package that provides (in conjunction with [additional browser extension](https://chrome.google.com/webstore/detail/gnome-shell-integration/gphhapmejobijbbhgpjhcjognlahblep)) integration with GNOME Shell and the corresponding extensions repository https://extensions.gnome.org for Google Chrome browser and derivatives.
2. Added optional "chrome" use flag for gnome-base/gnome-shell that provides runtime dep for gnome-extra/gs-chrome-connector.

### CODE REVIEW

**Comment by monsieurp** [comment]
@EvaSDK @jcallen-gentoo @pacho2

**Comment by EvaSDK** [comment]
While I like the intended feature, what I would prefer is to have this directly in gnome-shell sources. Also, if this was something that works with any webkit browser, it would be far easier to make it into the tree than just google chrome based browsers. Finally, even if this is packaged, it still requires manual installation of a chrome extension on top of all of this. This is imho not complete enough.

**Comment by nE0sIghT** [comment]
> Finally, even if this is packaged, it still requires manual installation of a chrome extension on top of all of this.

I just pushed new commits with "gs-chrome-connector" renamed to "chrome-gnome-shell" and version bump. Package [now provides preference files](https://github.com/nE0sIghT/chrome-gnome-shell/commit/a4426cea24be1a8d764705a275b16a39fecc70e6) for automatic [extension distribution](https://developer.chrome.com/extensions/external_extensions) - it will be installed from Chrome web store at next browser start.

> While I like the intended feature, what I would prefer is to have this directly in gnome-shell sources.

Agreed. But sadly there is [almost 2 years bug report at bugs.gnome.org](https://bugzilla.gnome.org/show_bug.cgi?id=727936) exists with no progress.

>  Also, if this was something that works with any webkit browser

Which browsers do you mean? There is Google Chrome, Chromium and Vivaldi browsers in main tree which works with this solution.
Opera not works, however it may work but some additional changes are needed (publishing to Opera store and install configuration files in different locations as I understand) and I have no interest in such changes.
I do not think vimb or surf have plugins support at all.
Konqueror and other Qt based browsers are strange choice for GNOME users :-)
Moreover I do not think there is silver bullet possible for all Webkit based browsers.

**Comment by nE0sIghT** [comment]
I close this now because project is in process of migration to GNOME infrastructure.
When 1st release as GNOME project will be available I will create new PR.

**Pull request closed without merging**
