### PR TITLE
media-libs/glew: new useflag wayland-only

### PR DESCRIPTION
**Pull request by kuroya2mouse**
new useflag as in media-libs/glwf

### CODE REVIEW

**Comment by winterheart** [comment]
Why not just `X` USE-flag enabled by default? According to docs, `SYSTEM=linux-egl` requires media-libs/mesa in DEPEND.

**Comment by kuroya2mouse** [comment]
> Why not just `X` USE-flag enabled by default?
i add as in media-libs/glwf
>requires media-libs/mesa in DEPEND.
virtual/opengl is not enough?

**Comment by kuroya2mouse** [comment]
wayland-only because `SYSTEM=linux-egl` not work in X11

**Comment by chewi** [comment]
Thank you for your contribution. I understand your reasoning here, and I think it is correct, except I wonder whether `linux-egl-glvnd` would be more appropriate. libglvnd is basically mandatory on Linux now, and this might even work on X11 too?

P.S. Please be careful not to make unnecessary changes (i.e. moving lines around) and remember that you can amend and force push this commit without having to open a new PR.

**Comment by chewi** [comment]
Hmm, I fudged glvnd with the current version to try supertux while unsetting `WAYLAND_DISPLAY` (forcing Xwayland) and it still gave the same error as using plain EGL.

```
env -u WAYLAND_DISPLAY supertux2 --renderer opengl
[FATAL] /var/tmp/portage/games-arcade/supertux-0.6.3-r2/work/SuperTux-v0.6.3-Source/src/supertux/main.cpp:672 Unexpected exception: GLVideoSystem: GlewError: Missing GL version
```

I tried it with git master too, but no dice. I notice that glew tries to link libOpenGL when using libglvnd, but `-Wl,--as-needed` ends up dropping it, like it isn't even used.

**Comment by chewi** [comment]
I'm also confused because EGL is generally supposed to work on X11 anyway, although that may require additional code in glew. I'll ask upstream.

**Comment by kuroya2mouse** [comment]
> I'll ask upstream.
Okay.

**Pull request merged**
