### PR TITLE
media-video/mpv: fix dev-lang/lua dependency wrt bug 586318, update 9999

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by mgorny** [comment]
Thanks a lot! Please update the bug now ;-).

**Comment by gktrk** [comment]
don't you guys need a revbump here to propagate the changes to vdb?

**Comment by Coacher** [comment]
@gktrk, mpv-0.17.0 will be revbumped as soon as I can catch @wraeth online.
mpv-0.9.2 is EOL.

**Pull request merged**
