### PR TITLE
media-gfx/graphicsmagick: remove broken USE=svg

### PR DESCRIPTION
**Pull request by hhoffstaette**
Closes: https://bugs.gentoo.org/921532
~Closes: https://bugs.gentoo.org/913069~

~jpeg2k support configure/compile-tested against jasper-4.0.0.~

jpeg2k commit moved to https://github.com/gentoo/gentoo/pull/34699

### CODE REVIEW

**Comment by hhoffstaette** [comment]
Well, dang. Problems are:
- missing keywords for jasper (~loong and ~hppa)
- tuxpaint & imagemagick-tools (a virtual) want to propagate svg because imagemagick still has USE=svg. I have no idea whether IM's svg support actually builds/works.

Suggestions welcome, I didn't even know we had a virtual for IM/GM. :(

**Comment by ConiKost** [comment]
It looks like, that four packages to exist, which depend on ```virtual/imagemagick-tools[svg]```. So those will also need to drop the use flag. As for ```media-gfx/tuxpaint```, this would also need to drop the use flag.

```
dev-python/sphinx/sphinx-7.2.6.ebuild:          virtual/imagemagick-tools[jpeg,png,svg]
app-office/lyx/lyx-2.3.7.ebuild:        virtual/imagemagick-tools[png,svg?]
kde-apps/kwave/kwave-23.08.3.ebuild:            virtual/imagemagick-tools[png,svg]
app-admin/usbview/usbview-3.0.ebuild:   virtual/imagemagick-tools[png,svg]
```

> IM's SVG writer generates the same wrong SVG as GM when enabled. For reading SVGs it uses librsvg via an external delegate (rsvg-convert) and generates correct output, unlike GM as well.

Well, the question is, do the other packages, which currently depend von ```svg```, also work, when svg is disabled on IM/GM?

**Comment by hhoffstaette** [comment]
> Well, the question is, do the other packages, which currently depend von `svg`, also work, when svg is disabled on IM/GM?

Unclear since both IM and GM behave differently for reading and writing (so 4 combinations of unlear requirements). The use flag itself doesn't say what is required.

**Comment by hhoffstaette** [comment]
I'll respin this PR and separate the two bugs since the svg problem is independent of reinstating jpeg2k.

**Comment by hhoffstaette** [comment]
Closing this in favor of a different approach hat doesn't require fiddling with any dependent packages and whatnot.

**Pull request closed without merging**
