### PR TITLE
x11-wm/dwm: Version bump to 6.1

### PR DESCRIPTION
**Pull request by mhz-tamb**

### CODE REVIEW

**Comment by monsieurp** [comment]
uh? This PR looks legit to me. Why did you close it?

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by mhz-tamb** [comment]
I hurried and just copied the old ebuild, but it was incorrect

**Comment by monsieurp** [comment]
commit 9a03e83 (HEAD, master)
Author: Patrice Clement <monsieurp@gentoo.org>
Date:   Sat Nov 14 16:03:46 2015 +0000

    x11-wm/dwm: Version bump courtesy of Sergey Shiryaev <sergey@shiryaev.pro>.
    
    Package-Manager: portage-2.2.20.1
    Signed-off-by: Patrice Clement <monsieurp@gentoo.org>

 create mode 100644 x11-wm/dwm/dwm-6.1.ebuild

Please rebase instead HEAD of merging it next time. Cheers.

**Pull request closed without merging**
