### PR TITLE
www-apps/kibana-bin: security bump to 5.6.5/6.0.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Security bug: https://bugs.gentoo.org/640532

### CODE REVIEW

**Comment by hydrapolic** [comment]
@monsieurp I didn't want to link the bug because it would automatically close the bug and I think only the security team can that. Are security bugs handled differently? If so,I'll add the header of course.

**Comment by hydrapolic** [comment]
Should I link it with Bug or Closes?

**Comment by monsieurp** [comment]
`Bug:` :+1:

**Comment by hydrapolic** [comment]
@monsieurp, Bugs added ;)

**Comment by hydrapolic** [comment]
Thank you for your time @monsieurp

**Pull request closed without merging**
