### PR TITLE
games-misc/oshu - Fast osu! port for Linux (and more) (gentoo#648642)

### PR DESCRIPTION
**Pull request by lanodan**
Pull request for this new package bug https://bugs.gentoo.org/648642.
Required fixes and some extra ones are done, and it builds.

Also in case you’re wondering: I haven’t included the git-based ebuild because oshu is currently moving to cmake.

### CODE REVIEW

**Comment by monsieurp** [comment]
My dream comes true... at last.

**Comment by monsieurp** [comment]
Amazing. I work with the bloke who wrote that software. He's in for a surprise!

**Comment by lanodan** [comment]
No so much of a surprise actually as I’ve been in contact and asked before in the IRC channel of oshu.
But wow, what a small world.

**Comment by monsieurp** [comment]
The ebuild looks good to me. @fmang what do you think?

**Comment by fmang** [comment]
It's fantastic! :unicorn: 

I suppose the CC license was added for the default sample set, but nothing seems to link the oshu ebuild to that new CC license file.

**Comment by lanodan** [comment]
[fmang commented Feb 26, 2018]
> I suppose the CC license was added for the default sample set, but nothing seems to link the oshu ebuild to that new CC license file.

Oh, yeah. I may have been removed after I’ve done too much rebase to adapt to gentoo git policy.

**Comment by monsieurp** [comment]
I will squash this contribution into a single commit. Hope you don't mind.

**Pull request closed without merging**
