### PR TITLE
net-analyzer/kapacitor: bump version 1.5.5

### PR DESCRIPTION
**Pull request by podshumok**
fix rebuild at install phase
fix version output
provide global use flags bash-completion doc systemd

### CODE REVIEW

**Comment by juippis** [comment]
Same thing here, looks like the maintainer doesn't use Github. 

You have better chances of reaching them by opening a bug at bugzilla. You can then link this PR to that bug, for the maintainer to review and merge, if they so wish.

**Comment by wimmuskee** [comment]
I think this one can be closed, 1.5.5 added to the tree with: https://github.com/gentoo/gentoo/commit/e3580775a6a8da149d1797ec0416bbd09a1aa714

**Comment by podshumok** [comment]
there are still a few bugs that are fixed here but not in the master

**Comment by ajakk** [comment]
> there are still a few bugs that are fixed here but not in the master

In this case you should file bugs on Bugzilla so the maintainer knows about them. Closing since this PR is broken anyway and causes a merge conflict.

**Comment by podshumok** [comment]
Multiple bugs about this are on Bugzilla and the maintainer ignores them, hence I stopped rebasing. Last time I checked the bug was still there, just write `kapacitor --version` to see it.

**Pull request closed without merging**
