### PR TITLE
Enhancement proposal for net-irc/irker

### PR DESCRIPTION
**Pull request by bjacquin**
6c80a09 net-irc/irker: Version bump
f2b3726 net-irc/irker: Default logging is now syslog instead of file
951d77f net-irc/irker: irk and irkerhook.py are not python3 friendly
576e5706 net-irc/irker: Install systemd service on every system.
74c6b11 net-irc/irker: Prune old versions

### CODE REVIEW

**Comment by monsieurp** [comment]
@patricklauer

**Comment by gktrk** [comment]
I would like to point out some missing things if you don't mind:

net-irc/irker/irker-2.16.ebuild:
- outdated copyright year
- missing '|| die' on line 30
- missing '|| die' on line 33

Similar cases exist for other ebuilds as well.

**Comment by bjacquin** [comment]
Thanks for the review, all of it should now be fixed.

**Comment by monsieurp** [comment]
Hi @bjacquin and thank you for your PR. Could you please file a bug for this bug? @patricklauer would prefer reviewing your changes through a proper Bugzilla bug. Thanks in advance.

**Pull request closed without merging**
