### PR TITLE
net-misc/mosh: add patch to enable the compilation with clang

### PR DESCRIPTION
**Pull request by geraint0923**
Fix is introduced to mosh official at:
https://github.com/mobile-shell/mosh/commit/e5f8a826ef9ff5da4cfce3bb8151f9526ec19db0

Signed-off-by: Yang Yang <geraint0923@gmail.com>

### CODE REVIEW

**Review by Flowdalic — CHANGES_REQUESTED** [review]
LGTM, but you should consider deleting the 1.3.2-r1 ebuild. Also the commit subject should be something like "net-misc/mosh: add patch to enable compilation with clang".

**Comment by geraint0923** [comment]
Thanks for the review! Just addressed the comments.

**Comment by geraint0923** [comment]
@Amynka  @Flowdalic  Kindly ping:) since 9999 has been removed, patching will be the only way to make mosh work with clang in Gentoo distro. Thanks!

**Comment by Amynka** [comment]
> @Amynka @Flowdalic Kindly ping:) since 9999 has been removed, patching will be the only way to make mosh work with clang in Gentoo distro. Thanks!

Sorry I commented and forgot to submit it..  Can we please adjust the name? Thanks a lot and sorry again

**Comment by geraint0923** [comment]
Thanks @Amynka for the review! Just updated the PR and addressed the comments.

**Pull request closed without merging**
