### PR TITLE
sys-block/gparted: Port USE=kde to kde-plasma/kde-cli-tools[kdesu]

### PR DESCRIPTION
**Pull request by a17r**
* simple change that works for me, only lines affected are 25 and 83
* had to mask gparted[kde] on ppc for lack of keyword

@EvaSDK @gentoo/gnome

### CODE REVIEW

**Comment by EvaSDK** [comment]
It would be nice to not loose the feature on ppc but other than that, feel free to go ahead.

**Comment by a17r** [comment]
Qt-5.6.1 would be ready, but it would require ~ppc keywording of at least several KDE Frameworks which hasn't happened yet

**Comment by kensington** [comment]
Nobody seems to be doing ppc keywording lately so I doubt KDE Frameworks will get any keywords. Even in KDE 4 ppc support is disappearing due to lack of arch team interest.

**Comment by a17r** [comment]
So, since feature will be lost for ppc either way I guess it should not hold up merging.

**Comment by EvaSDK** [comment]
Ok, go ahead then.

**Comment by kensington** [comment]
Thanks, picked as af63842d08b5ac9f983aaa22c442e9127708c324...426c3ae8f86d45a5ca0a443b8569a5d1a113385b. I split the profile change into a separate commit.

**Pull request closed without merging**
