### PR TITLE
sys-devel/gdb: proper handling of locale files

### PR DESCRIPTION
**Pull request by jvesely**
fix handling of locales
https://bugs.gentoo.org/show_bug.cgi?id=402309

### CODE REVIEW

**Comment by monsieurp** [comment]
@dirtyepic @blueness

**Comment by monsieurp** [comment]
@blueness ping

**Comment by vapier** [comment]
i don't think this is the way to go.  should keep the discussion on the bug though.

**Comment by jvesely** [comment]
"keep discussion on the bug"  The one in relevant bug (402309) died 4 years ago. 

If you're implying that there should be a general solution, is there any such ongoing effort? can you provide any pointers?

**Comment by vapier** [comment]
the bug is still open.  if you have follow up comments, then post them there.

**Pull request closed without merging**
