### PR TITLE
app-backup/qt4-fsarchiver: version bump

### PR DESCRIPTION
**Pull request by necrose99**
https://github.com/necrose99/necromancy-overlay/tree/master/app-backup/qt4-fsarchiver

inherit qt4-build qt5-build versionator qmake-utils ? eclasses may have changed.

### CODE REVIEW

**Comment by hasufell** [comment]
I don't understand what this PR is meant for. You cannot update a Manifest without adding the ebuilds. How is that supposed to work?

**Comment by hasufell** [comment]
Add your commits from the other PRs here.

**Comment by necrose99** [comment]
qt4-fsarchiver-0.6.19.7 ebuild cp to qt4-fsarchiver-0.6.19.15.ebuild , qt4-fsarchiver-0.6.19.14.ebuild
qt4-fsarchiver-0.6.19.15.ebuild

**Comment by necrose99** [comment]
https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/app-backup/qt4-fsarchiver/qt4-fsarchiver-0.6.19.13.ebuild
https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/app-backup/qt4-fsarchiver/qt4-fsarchiver-0.6.19.14.ebuild
https://raw.githubusercontent.com/necrose99/necromancy-overlay/master/app-backup/qt4-fsarchiver/qt4-fsarchiver-0.6.19.15.ebuild

note I have some distfiles mirrored however hash/s might be off. 
https://github.com/necrose99/qt4-fsarchiver/raw/master/SRC-TARBALLS/${MY_P}.tar.gz"

**Comment by mgorny** [comment]
@necrose99, this is not CVS. All files relevant to a particular version should go in one commit. That said, you shouldn't add more than one version at once. And unless really beneficial or necessary, you should just limit yourself to the newest version.

**Comment by idella** [comment]
ditto

**Comment by mgorny** [comment]
@necrose99, are you still there? We find it really hard to understand your comments so far. Please wrap up the change in a single proper git commit and reopen this pull request after force-pushing to the appropriate branch.

**Comment by necrose99** [comment]
alright i'll make a branch to avoid any commit/s noise from others so far the same ebuild has serviced me well for a number of bumps.

**Pull request closed without merging**
