### PR TITLE
dev-python/diff-match-patch: Version bump 20181111

### PR DESCRIPTION
**Pull request by AndrewAmmerlaan**
Breaking up PR into smaller parts: https://github.com/gentoo/gentoo/pull/13988

Bug: https://bugs.gentoo.org/702458
Signed-off-by: Andrew Ammerlaan <andrewammerlaan@riseup.net>
Package-Manager: Portage-2.3.81, Repoman-2.3.20

### CODE REVIEW

**Comment by aidecoe** [comment]
FYI just found out that the original diff-match-patch is maintained at https://github.com/google/diff-match-patch and the changes are actually more recent than forked one used by this ebuild.

**Comment by aidecoe** [comment]
Feel free to bump as it is for now, because the Google's isn't packages properly as Python package.

**Comment by AndrewAmmerlaan** [comment]
@hartwork I have re-added python3_5 and the missing arch, I also update the EAPI version.

**Comment by AndrewAmmerlaan** [comment]
> FYI just found out that the original diff-match-patch is maintained at https://github.com/google/diff-match-patch and the changes are actually more recent than forked one used by this ebuild.

I also found this earlier, but the folks at google apparently don't feel like packaging diff-match-patch for pip/pypi: https://github.com/google/diff-match-patch/issues/17 

The pypi package originates from [here](https://github.com/diff-match-patch-python/diff-match-patch) which is a fork of the google repository. It doesn't have a newer version though. However, the files in the python3 directory of google's repo, seems to suggest that there was only [1 commit](https://github.com/google/diff-match-patch/commit/ffe7c7be61a0084ac79632f12811bb6dd7ace35c#diff-5680d2f2b99ecc1f9cd4ada8fb8df1a6) since the 11th of November last year. I suppose we could make a pull request to the python fork to pull that single commit and release a new version on pypi. But the change seems so small that I don't really feel like spending time on that.

**Comment by AndrewAmmerlaan** [comment]
> … but I do not find a line distutils_enable_tests setup.py in the new EAPI 7 diff-match-patch-20181111.ebuild. To me it looks like we're dropping tests here — is it missing on purpose?

The 20121119 ebuild does not contain `IUSE="test"`, so I was a bit confused as to why the `python_test()` was in there to begin with. Unless I'm mistaken the test use flag should be there to correctly enable test support. Should I add `distutils_enable_tests setup.py` anyway?

**Comment by hartwork** [comment]
> > … but I do not find a line distutils_enable_tests setup.py in the new EAPI 7 diff-match-patch-20181111.ebuild. To me it looks like we're dropping tests here — is it missing on purpose?
> 
> The 20121119 ebuild does not contain `IUSE="test"`, so I was a bit confused as to why the `python_test()` was in there to begin with. Unless I'm mistaken the test use flag should be there to correctly enable test support, so I figured the `python_test()` function wasn't doing anything and removed it. 

The way I understood the use flag `test` is that it only exists where extra dependencies are needed for tests a la `test? ( ... )` or if there's some need for `use test && ...` inside the ebuild. That would be in line with the description of the ebuild at https://packages.gentoo.org/useflags/test:
> Enable dependencies and/or preparations necessary to run tests (usually controlled by FEATURES=test but can be toggled independently) 

What do you think?

> Should I add `distutils_enable_tests setup.py` anyway?

Yes — saw you already did. Thank you!

**Comment by hartwork** [comment]
Merged now.

I took the liberty of integrating this patch to the ebuild because I noticed the tests would fail otherwise. I hope that's in your best interest.

```diff
diff --git a/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild b/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
index c6ba632e8d62..bde087ebd037 100644
--- a/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
+++ b/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
@@ -15,4 +15,4 @@ LICENSE="Apache-2.0"
 SLOT="0"
 KEYWORDS="~amd64 ~arm64 ~x86"
 
-distutils_enable_tests setup.py
+distutils_enable_tests pytest
```

**Comment by AndrewAmmerlaan** [comment]
> Merged now.
> 
> I took the liberty of integrating this patch to the ebuild because I noticed the tests would fail otherwise. I hope that's in your best interest.
> 
> ```diff
> diff --git a/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild b/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
> index c6ba632e8d62..bde087ebd037 100644
> --- a/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
> +++ b/dev-python/diff-match-patch/diff-match-patch-20181111.ebuild
> @@ -15,4 +15,4 @@ LICENSE="Apache-2.0"
>  SLOT="0"
>  KEYWORDS="~amd64 ~arm64 ~x86"
>  
> -distutils_enable_tests setup.py
> +distutils_enable_tests pytest
> ```

Awesome, thank you

**Pull request closed without merging**
