### PR TITLE
I2p

### PR DESCRIPTION
**Pull request by tomboy-64**
- further specify JVM requirements for i2p
- add tomboy64@sina.cn as proxy-maintainer

### CODE REVIEW

**Comment by tomboy-64** [comment]
oh, forgot
@gentoo/proxy-maint

**Comment by idella** [comment]
@chewi

**Comment by idella** [comment]
the 4b1df23 is a revbump which need be stipulated in the commit msg.
Whether this can become supervised by the proxy-maintainers is unclear inasmuch as the proxied tharvik appears to have had no involvement as yet.
Also he requires a name set in metadata

**Comment by tomboy-64** [comment]
@tharvik Please have a look at the changes.
I don't mean to intrude; I've been working on the I2P ebuild on and off for the past couple of years. Last week (before you bumped) I started working on 0.9.24 since I then became aware of the ECDSA mess with sunec/gentoo JVMs.
Your work is fine, I just felt more precise RDEPEND listings were in order.

Feel free to censor; again: I only mean to help, not intrude on your work.

**Comment by tharvik** [comment]
@tomboy-64 Thanks! That's nice to have people reviewing my ebuilds, have some feedback.

For your changes, I'm still in favor of keeping as optional.

Also, currently, you have some duplicates specification
```
dev-java/icedtea:7[-sunec]
dev-java/icedtea:7[nss,-sunec]
dev-java/icedtea-bin:7[nss]
dev-java/icedtea-bin:7
```
Which means that `nss` can either be enabled or not. Which is always the case for boolean variable such as USE flags.

What we can do, is to have the USE flag `ecdsa` (disable by default), which will select the correct JVM. Do you want to do it?

**Comment by monsieurp** [comment]
@tharvik hi and thanks for reviewing this ebuild. I'll be waiting for your approval before merging this PR.

**Comment by chewi** [comment]
Sorry I missed the duplication when I initially reviewed this. I like @tharvik's ecdsa USE flag idea.

**Comment by tomboy-64** [comment]
I can certainly see the appeal of an ecdsa USE flag. However I approached this ebuild with the assumption that ECDSA support should be enabled. It isn't that much of a problem, considering that sunec is apparently generally unreliable. All this ebuild does is nudge the user in the right direction and prevent the damage the sunec useflag would do. Whether i2p actually runs with a suitable JVM is not under portage's control anyway. At the very least, I would leave ```+ecdsa``` then, not have it disabled per default.

I'll think about a solution for that use-flag; it's gonna take me a few days, though. I'm busy until (probably) the weekend. It's not just the JDK dependency; removing the need for ecdsa deps would imply optionally removing bcprov as well.

**Comment by tharvik** [comment]
> I can certainly see the appeal of an ecdsa USE flag. However I approached this ebuild with the assumption that ECDSA support should be enabled. It isn't that much of a problem, considering that sunec is apparently generally unreliable. All this ebuild does is nudge the user in the right direction and prevent the damage the sunec useflag would do. Whether i2p actually runs with a suitable JVM is not under portage's control anyway. At the very least, I would leave +ecdsa then, not have it disabled per default.
> 
I see your point, let's go with enable by default then
> I'll think about a solution for that use-flag; it's gonna take me a few days, though. I'm busy until (probably) the weekend. It's not just the JDK dependency; removing the need for ecdsa deps would imply optionally removing bcprov as well.
> 
Conditional dependency are not very hard to write on Gentoo, it's quite well documented and readable. Thanks for doing it.

**Pull request merged**
