### PR TITLE
Topic/nitrocli rust 1.35

### PR DESCRIPTION
**Pull request by d-e-s-o**
This pull request does two things for app-crypt/nitrocli:
1) it removes the old 0.2.2 version for 0.2.3 works just fine.
2) it black lists Rust 1.35 (or greater) for the remaining 0.2.3 ebuild, required for [bug #686870](https://bugs.gentoo.org/686870).

Please let me know if procedure dictates to create a new ebuild (0.2.3-r2) instead.

### CODE REVIEW

**Comment by d-e-s-o** [comment]
@gyakovlev , it would be great if you were to take another look here! :-)

**Comment by d-e-s-o** [comment]
(for the record: I did verify that the ebuild builds with rust-bin-1.34.2)

**Comment by d-e-s-o** [comment]
Good suggestion! Thanks, I've reworked the pull request.

**Comment by gyakovlev** [comment]
seems you copied the Manifest from overlay that is not set up with `thin-manifests`, hence the patch got into Manifest file as AUX entry.

remove this line from Manifest
`AUX nitrocli_-_fix-rust-1.35-build.patch`

**Comment by gyakovlev** [comment]
you can also add `thin-manifests = true` to your overlay where you develop ebuilds for gentoo tree.
https://wiki.gentoo.org/wiki/Repository_format/package/Manifest#Thin_Manifest

**Comment by gyakovlev** [comment]
ok I pushed, removing that line from Manifest.
thanks

**Comment by d-e-s-o** [comment]
Thanks Georgy! I'll try to remember this part about the Manifest (and see if `thin-manifests` makes sense for me).

**Pull request closed without merging**
