### PR TITLE
dev-util/buildbot: Support for multiple buildmaster instances, #570666

### PR DESCRIPTION
**Pull request by seifertm**
This pull request adds support for starting multiple instances of buildmaster on both OpenRC and systemd installations. It also bumps the version of the newest ebuild from 0.8.12-r1 to 0.8.12-r2 and removes the old revision.

Fixes https://bugs.gentoo.org/show_bug.cgi?id=570666

### CODE REVIEW

**Comment by hwoarang** [comment]
Looks reasonable. However I think that may break existing installations unless you already have buildmaster.<yourmaster> file around. Is that correct? do you think we need to inform the users of this changes using elog and friends?

**Comment by monsieurp** [comment]
ping @seifertm

**Comment by seifertm** [comment]
Aww, sorry...

Thanks for looking into it. You are right that existing installations will stop working, because it is not possible to start the service without specifying an instance name. (I assume the same is true for the systemd service.)

The migration shouldn't be a big issue, though, because any existing ``.cfg`` should be reusable.

I will add a notification and probably look into an ``emerge --config`` that helps setting up an instance this evening.

**Comment by seifertm** [comment]
What's your opinion on this, @hwoarang?

**Comment by hwoarang** [comment]
I think it looks reasonable but seems https://github.com/gentoo/gentoo/pull/1027/commits/b2d1c436e7a87921ca504ea3173ab2b4cdea8b06 needs some whitespace fixing

**Comment by seifertm** [comment]
Here we go. Repoman is also satisfied now :)

**Comment by seifertm** [comment]
`pkg_config` now also creates `/var/lib/buildmaster`, if the directory does not exist.

**Comment by monsieurp** [comment]
@hwoarang ping

**Comment by hwoarang** [comment]
@monsieurp please go ahead and merge it. I don't see anything obviously wrong with it but I am sure some migrations will go wrong :) @seifertm thank you for your work. Please have a look on the bugzilla over the next few weeks to react to potential bugs because of that change as I will not be around much (as you see ;))

**Comment by monsieurp** [comment]
@hwoarang OK. Thanks for signing off it! :+1:

**Comment by seifertm** [comment]
Thanks to the both of you.

I will have a look in the bug tracker, in case anything pops up. The one who breaks it has to fix it, I guess :)

**Pull request closed without merging**
