### PR TITLE
sci-libs/gmsh: various improvements

### PR DESCRIPTION
**Pull request by efferre79**
I have introduced the installation of private API files because they will be likely needed in future by kicad (https://gitlab.com/kicad/code/kicad/-/merge_requests/1210#62ca074374ee4512a7efb645fa1f53aa72f86acb)

### CODE REVIEW

**Comment by tamiko** [comment]
Merci. I'll have a look tomorrow :-)

**Comment by efferre79** [comment]
@tamiko with last commit I have tried cleaning the USE flag usage in the latest version ebuild, it's not perfect but it should limit the building against in-source code (annlib is not in portage). I am not sure about how is used the mpi conditional USE dependency. Even with this PR gmsh's CMakeLists.txt still has many other flags and combinations not supported.

**Comment by tamiko** [comment]
@efferre79 Thanks a lot for the help.

**Comment by tamiko** [comment]
Merged. Merci!

**Pull request closed without merging**
