### PR TITLE
dev-perl/ version bumps from dev-perl/G* to dev-perl/K*

### PR DESCRIPTION
**Pull request by kentfredric**
/cc: @akhuettel @monsieurp 

Miscellaneous version bumps, some have been stale since 2014.

PerlIO-via-Timeout needed bumping for IO-Socket-Timeout.

Additional Defects noticed for some TODO:
- [x] `dev-perl/HTTP-Cookies` says `6.0.1` when it should be `6.10.0`
- [x] `dev-perl/HTTP-Negotiate` says `6.0.1` when it should be `6.10.0`
- [x] `dev-perl/ImageInfo` should be `dev-perl/Image-Info`
- [x] `dev-perl/ImageSize` should be `dev-perl/Image-Size`

### CODE REVIEW

**Comment by monsieurp** [comment]
Looks good to me.

**Comment by kentfredric** [comment]
HTTP-Negotiate and HTTP-Cookies cleaned up as per irc convo.

**Comment by kentfredric** [comment]
ImageSize/ImageInfo changes I'll put in a seperate pull once this one is merged because I want to be sure my process is right and I might need a few rebases.

https://github.com/kentfredric/gentoo/compare/perl-Gxx...perl-ImageSize?expand=1

**Comment by monsieurp** [comment]
Thanks a lot Kentz.

**Pull request merged**
