### PR TITLE
x11-libs/goocanvas: fix gcc-14

### PR DESCRIPTION
**Pull request by parona-source**
Closes: https://bugs.gentoo.org/919442

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by pacho2** [comment]
I am not sure if these gcc-14 fixes would qualify for a revision bump 🤔

**Comment by parona-source** [comment]
> I am not sure if these gcc-14 fixes would qualify for a revision bump 🤔

Cant say I have enough authority in the subject to say, asked about it in #gentoo-toolchain.

**Comment by parona-source** [comment]
> <@dilfridge> parona: that should be fine without revbump

@pacho2

**Comment by parona-source** [comment]
To clarify this was only in reference to this change rather than in general.

**Comment by thesamesam** [comment]
Yeah, the rule in general is:
* implicit function declarations always need it
* int-conversion almost surely does (with the exception of 0 vs NULL)
* incompatible pointer types need it unless you're casting to the type it was anyway
But if you're in doubt, you should. Lots of these fixes are really runtime ones.

**Comment by pacho2** [comment]
Thanks for the info!

**Pull request closed without merging**
