### PR TITLE
dev-util/glslang: fix LICENSE

### PR DESCRIPTION
**Pull request by ddmail2009**
Fix License from BSD to Apache-2.0.

Signed-off-by: Po-Hsien Wang <ddmail2009@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
Also, the commit message should be of the form "category/package: ...". For instance, dev-util/glslang: ...

**Comment by ddmail2009** [comment]
I'm not really familiar with the LICENSE thing.
Browsing through history of glsl repository, my take is that https://github.com/KhronosGroup/glslang/commit/b23d232ec5222a168d248d757b8bdb71c75241cb changes the license part.

vulkan-tools/ and spirv-tools/ are both licensed under "Apache-2.0" and I have no problem building it.

**Comment by mattst88** [comment]
For the title, you have to git commit --amend your patch and force push it. It's not sufficient to change the title of the pull request.

Looking in the glslang code, I see plenty of files that contain licenses that look like BSD and also some that are Apache. I think LICENSE="BSD Apache-2.0" is more correct.

**Comment by ddmail2009** [comment]
Thanks mattst88@.
I updated to actual commit message and changed the license to "BSD Apache-2.0" as I see files under BSD license as well.

**Comment by ddmail2009** [comment]
After deep look through, I'm not sure if we need Apache-2.0 or not now. It seems most of the core function is under BSD and nothing is changed recently. glslang SPIRV and some file is under Apache-2. Based on the git history, "BSD" is listed as the only license for a long time. Maybe it is just some problem of my local build system.

I think I'll drop this PR and go investigating why my build is not working as for right now.

**Pull request closed without merging**
