### PR TITLE
Remove multilib stuff from virtual/pkgconfig

### PR DESCRIPTION
**Pull request by floppym**
Bug: https://bugs.gentoo.org/723112

### CODE REVIEW

**Comment by floppym** [comment]
I don't think we actually need the `i686-pc-linux-gnu-pkg-config` binary at all. As a followup to this pull request, I will look into removing the multilib binaries from dev-util/pkgconf and dev-util/pkgconfig.

The `multilib_toolchain_setup` function sets the `PKG_CONFIG_LIBDIR` environment variable, which should suffice for finding libraries for secondary ABIs, regardless of the ABI under which pkg-config was built.

**Comment by floppym** [comment]
It might make sense to set `PKG_CONFIG_SYSTEM_LIBRARY_PATH` in `multilib_toolchain_setup`.
```
     PKG_CONFIG_SYSTEM_LIBRARY_PATH
             List of paths that are considered system library paths by the
             toolchain.  This is a pkgconf-specific extension.
```

**Comment by leio** [comment]
I'm not convinced we don't need a i686-pc-linux-gnu-pkgconfig and such. Especially as evident by a i686-pc-linux-gnu crossdev messing things up - clearly something makes it be used; and there's no commit here that changes that.

**Comment by floppym** [comment]
Summarizing a conversation from #gentoo-desktop:

1. Overriding PKG_CONFIG_LIBDIR will suffice to make pkg-config look in the right place. We already do this.
2. Overriding PKG_CONFIG_SYSTEM_LIBRARY_PATH will eliminate unnecessary `-L` options from the output for non-native libdirs. I will add a patch for this.
3. To prevent the crossdev pkg-config from being used by accident, we should probably export PKG_CONFIG in multilib_toolchain_setup. I will add a patch for this.

**Comment by leio** [comment]
Cautiously optimistic about this now, but I think we should really make sure it'll work with the next step for non-native multilib builds for sure when there's no non-native CHOST pkg-config binary before proceeding to already remove all the deps in consumers.

I think one thing, that may turn out a problem for multilib removal in pkgconf itself, is straight-forward usage outside package manager -- assuming that e.g. the i686-pc-linux-gnu-pkg-config calls default to the lib32 packages in the lack of any PKG_CONFIG_* env var being set up. With a CHOST version being present, you just set the standard PKG_CONFIG configure precious variable and everything else will work - without a CHOST version, it'll complicate matters more for being able to test a 32bit build of your application as developed by upstream on a Gentoo box. Though that shouldn't matter for the deps in portage, given the env var that package manager/eclasses do know to automatically set up.

**Comment by floppym** [comment]
> I think one thing, that may turn out a problem for multilib removal in pkgconf itself, is straight-forward usage outside package manager

I guess we could keep the multilib binary logic there, or possibly provide compatibility wrappers via an external package similar to sys-devel/multilib-gcc-wrapper.

**Comment by mgorny** [comment]
Hmm, I'm wondering if these mass changes are kosher. I mean, if people don't rebuild these packages, the PM's going to continue pulling multilib pkg-config which no longer exists.

**Comment by floppym** [comment]
@mgorny I don't think it matters when the dependencies are in BDEPEND or DEPEND.

I'll take a look for any RDEPEND entries, and revbump as appropriate.

**Comment by floppym** [comment]
If there are no objections, I will plan on merging this over the weekend.

**Comment by floppym** [comment]
Merged in e76c7f69bf4755eb3c08aa290d072541d0fd65db.

**Pull request closed without merging**
