### PR TITLE
net-im/skypeforlinux: Bump version to 8.50.0.38

### PR DESCRIPTION
**Pull request by jvesely**
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
@SoapGentoo , interested in this one?

**Comment by jvesely** [comment]
ping.
@oniGino,  are you maintaining skypeforlinux?

**Comment by juippis** [comment]
Thanks for this PR. LGTM, apart from
```

 * The ebuild is installing to one or more unexpected paths:
 *
 *   /usr/share/doc/skypeforlinux
 *
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
```

Please fix that while we wait for @oniGino for a bit more. He might have some work in progress, or be on a holiday or something. @oniGino please review, and add your approval or comments regarding this PR.

**Comment by oniGino** [comment]
Well /usr/share/doc/skypeforlinux is a known issue, if you fix it you break the GUI help menu that is hard coded for that path...

As for the rest, this looks fine

**Pull request closed without merging**
