### PR TITLE
dev-db/mongodb: 5.0.30 bump and 4.4 removal

### PR DESCRIPTION
**Pull request by Dessa**
NOTE: this used to have clang logic, but got canned due to changed scope

4.4 is gone now, it is EOL for a while and everybody should have upgraded to 5.0 at this point
this has been tested with gcc-{14,15} on amd64

```
--- mongodb-5.0.26.ebuild	2024-11-21 13:57:21.317354126 +0100
+++ mongodb-5.0.30.ebuild	2024-11-21 14:31:55.538511697 +0100
@@ -3,7 +3,7 @@
 
 EAPI=8
 
-PYTHON_COMPAT=( python3_{10..12} )
+PYTHON_COMPAT=( python3_{10..13} )
 
 SCONS_MIN_VERSION="3.3.1"
 CHECKREQS_DISK_BUILD="2400M"
@@ -17,12 +17,12 @@
 
 DESCRIPTION="A high-performance, open source, schema-free document-oriented database"
 HOMEPAGE="https://www.mongodb.com"
-SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.gh.tar.gz"
+SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.tar.gz"
 S="${WORKDIR}/${MY_P}"
 
 LICENSE="Apache-2.0 SSPL-1"
 SLOT="0"
-KEYWORDS="amd64 ~arm64 -riscv"
+KEYWORDS="~amd64 ~arm64 -riscv"
 CPU_FLAGS="cpu_flags_x86_avx"
 IUSE="debug kerberos mongosh ssl +tools ${CPU_FLAGS}"
 
@@ -33,11 +33,12 @@
 RDEPEND="acct-group/mongodb
 	acct-user/mongodb
 	>=app-arch/snappy-1.1.7:=
+	app-arch/zstd:=
 	>=dev-cpp/yaml-cpp-0.6.2:=
 	dev-libs/boost:=[nls]
 	>=dev-libs/libpcre-8.42[cxx]
-	app-arch/zstd:=
 	dev-libs/snowball-stemmer:=
+	net-misc/curl
 	>=sys-libs/zlib-1.2.12:=
 	kerberos? ( dev-libs/cyrus-sasl[kerberos] )
 	ssl? (
@@ -63,7 +64,7 @@
 
 PATCHES=(
 	"${FILESDIR}/${PN}-4.4.1-boost.patch"
-	"${FILESDIR}/${PN}-4.4.1-gcc11.patch"
+	"${FILESDIR}/${PN}-5.0.30-gcc-11.patch"
 	"${FILESDIR}/${PN}-5.0.2-fix-scons.patch"
 	"${FILESDIR}/${PN}-5.0.2-no-compass.patch"
 	"${FILESDIR}/${PN}-5.0.2-skip-no-exceptions.patch"
@@ -76,6 +77,7 @@
 	"${FILESDIR}/${PN}-4.4.29-no-enterprise.patch"
 	"${FILESDIR}/${PN}-5.0.26-boost-1.85.patch"
 	"${FILESDIR}/${PN}-5.0.26-boost-1.85-extra.patch"
+	"${FILESDIR}/${PN}-5.0.30-gcc-15.patch"
 )
 
 python_check_deps() {
@@ -129,7 +131,7 @@
 		VERBOSE=1
 		VARIANT_DIR=gentoo
 		MONGO_VERSION="${PV}"
-		MONGO_GIT_HASH="0b4f1ea980b5380a66425a90b414106a191365f4"
+		MONGO_GIT_HASH="966efda23d779a86c76c34e1b13e561d68f2bb37"
 
 		--disable-warnings-as-errors
 		--force-jobs # Reapply #906897, fix #935274
@@ -172,7 +174,7 @@
 }
 
 src_compile() {
-	PREFIX="${EPREFIX}/usr" ./buildscripts/scons.py "${scons_opts[@]}" install-core || die
+	PREFIX="${EPREFIX}/usr" ./buildscripts/scons.py "${scons_opts[@]}" install-devcore || die
 }
 
 src_install() {

```
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by Dessa** [comment]
looks like an update is in order:

- apparently, 5.0.30 is released. i say apparently because nothing has been pushed to github outside of master in the last three weeks and there was also no release post for it, so im not sure whats going on.
- i have decided that im going to drop llvm support for 5.0 since its an EOL branch now, even if there will be a .31 (which is not impossible)
- llvm support in general is not really something i look forward to, essentially, how it looks like, i'd have to backport stuff from 8.0 due to std::variant, which is way outside of my wheelhouse, maybe i find another way somehow

waiting on the tags now, mostly.

**Comment by thesamesam** [comment]
```
-SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.gh.tar.gz"
+SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.tar.gz"
```

The .gh. part is preferable for autogenerated tarballs in case we ever want to use a release tarball. I'll change that on merging. Thanks.

**Comment by thesamesam** [comment]
Note that dropping 4.x may be problematic as IIRC it's the last version which supports some HW. We had some complaints in the past. But I'll merge it, just keep an eye out for bugs please.

**Comment by Dessa** [comment]
> ```
> -SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.gh.tar.gz"
> +SRC_URI="https://github.com/mongodb/mongo/archive/refs/tags/${MY_PV}.tar.gz -> ${P}.tar.gz"
> ```
> 
> The .gh. part is preferable for autogenerated tarballs in case we ever want to use a release tarball. I'll change that on merging. Thanks.

I was under the impression this only applied to Python ebuilds that are on pypi but are pulled from github, thanks for the clarification

**Pull request closed without merging**
