### PR TITLE
app-misc/elasticsearch: bump to 2.4.4/5.1.2

### PR DESCRIPTION
**Pull request by hydrapolic**

### CODE REVIEW

**Comment by gktrk** [comment]
https://bugs.gentoo.org/show_bug.cgi?id=606456

**Comment by gktrk** [comment]
Do you want me to hold this until Bug 597454 is resolved?

**Comment by hydrapolic** [comment]
@gktrk, this should resolve bug 597454.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/ed22be7...e9081ed. Thanks!

**Comment by gktrk** [comment]
Sorry, closed the wrong PR

**Comment by gktrk** [comment]
Looks like you forgot the keepdir for scripts in 2.4.4. I will fix it before the merge.

**Comment by gktrk** [comment]
And the second commit would require a revbump because it's installing a different init file. Optionally, we can fixup to the first commit instead.

**Comment by hydrapolic** [comment]
I'll make the changes and push them.

**Comment by hydrapolic** [comment]
ad comment 1)
In 2.4.4, the scripts directory has to stay as dodir because else ES will print this in the log:

`
[2017-02-13 13:25:44,592][WARN ][watcher                  ] cannot notify file changes listener
java.lang.IllegalArgumentException: script file extension not supported [keep_app-misc_elasticsearch-0]
        at org.elasticsearch.script.ScriptService.getScriptEngineServiceForFileExt(ScriptService.java:220)
        at org.elasticsearch.script.ScriptService.access$1300(ScriptService.java:82)
        at org.elasticsearch.script.ScriptService$ScriptChangesListener.onFileInit(ScriptService.java:531)
        at org.elasticsearch.watcher.FileWatcher$FileObserver.onFileCreated(FileWatcher.java:256)
`

ad comment 2)
Since both commits are probably going to be done at once, there is a very low (zero) chance that somebody will emerge 5.1.2 without the new systemd file.

**Comment by gktrk** [comment]
Hmm, so here's the problem. The PMS [says](https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-15400012.2.2) that:

```
Behaviour upon encountering an empty directory is undefined.
Ebuilds must not attempt to install an empty directory.
```

Would ES complain if we installed the same empty file with the proper script extension in the ebuild manually?

And about your second comment, relying on git push for atomic behavior is a QA violation AFAIK and I like my commit access when it's not taken away from me :) Every commit should move the tree from one stable state to another.

**Comment by gktrk** [comment]
Ah, it supports multiple scripting languages. I thought I can get away with something like `.keep_app-misc_elasticsearch-0.groovy` but I'm not sure what would happen if I change the `script.default_lang` attribute to, say, python.

What if we don't install the empty directory at all though? I created a new elasticsearch instance under `/etc/elasticsearch/testing` without creating the `scripts` directory, and ES created an empty one for me on launch.

**Comment by hydrapolic** [comment]
I've tried removing the scripts directory, but ES failed to start and 
couldn't create the directory as it's owned by root.

dodir -> init.d checkpath

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/f87ac1e...ce0c1b6. Thanks for going through all the pain to get it fixed.

**Comment by hydrapolic** [comment]
Thanks @gktrk

**Pull request closed without merging**
