### PR TITLE
net-analyzer/nrpe: bump to 3.2.0, drop old

### PR DESCRIPTION
**Pull request by hydrapolic**
Package-Manager: Portage-2.3.6, Repoman-2.3.2

### CODE REVIEW

**Comment by hydrapolic** [comment]
@orlitzky

**Comment by hydrapolic** [comment]
@orlitzky, interesting commit:
https://github.com/NagiosEnterprises/nrpe/commit/bc020a7cfe8535611cbc710566ce2f436feeb372

**Comment by orlitzky** [comment]
Pulled, thanks!

**Comment by hydrapolic** [comment]
Thank you

**Pull request closed without merging**
