### PR TITLE
Dev lang/lua

### PR DESCRIPTION
**Pull request by shuber2**
Fixes issues with the slotted lua-5.3.5, in particular related to https://bugs.gentoo.org/602476

### CODE REVIEW

**Comment by lanodan** [comment]
Might be better to look in the lua overlay instead as in the main repo lua-5.2 and later is masked. (See “Masked slotted lua for testing” in `profiles/package.mask`)

**Comment by shuber2** [comment]
@lanodan Thank you. However, I really would like to improve lua in official portage. (Btw, also lua:5.1 is masked, so are all slotted lua versions.)

**Comment by robbat2** [comment]
Please review against `lua-5.2.4-r1.ebuild` and `lua-5.3.5-r1.ebuild`, which was written without prior knowledge of this PR.

**Comment by shuber2** [comment]
Tested with lua-5.3.5-r1.ebuild and works. Thank you.

**Pull request closed without merging**
