### PR TITLE
cmake-utils.eclass: Fix multi-arg CC/CXX/FC, #542530

### PR DESCRIPTION
**Pull request by mgorny**
@gentoo/kde

### CODE REVIEW

**Comment by mgorny** [comment]
@toralf, could you tinderbox this, please? Only needs testing on CMake multilib packages, i.e. `grep -l _eclass.*cmake.*multilib-build` in md5-cache ;-).

**Comment by toralf** [comment]
The eclass patch will be applied now after each sync of the portage tree too eternity or till that patch will be recalled.. And I added to all current 10 work queues these packages:

`(cd /usr/portage/metadata/md5-cache/; grep -lR _eclass.*cmake.*multilib-build ./ ) | xargs qatom | cut -f1-2 -d' ' | tr ' ' '/' | sort -u --random-sort`

**Comment by mgorny** [comment]
Thanks. Just to clarify, are tinderbox runs done with `ABI_X86="32 64"`?

**Comment by junghans** [comment]
Will this work for `CC="ccache gcc"`?

**Comment by mgorny** [comment]
> Will this work for `CC="ccache gcc"`?

No. I should probably add an assertion to make sure second parameter is an option.

But anyway, why would you do something like that? You can utilize ccache by putting the shadow directory in PATH. Like emerge does.

**Comment by toralf** [comment]
>  Just to clarify, are tinderbox runs done with ABI_X86="32 64"?

ick, no, but since 2 minutes (c3340e0280be2b599b9b13dea17d1581a520329c) it does it - thx for pointing to that missing feature.

**Comment by kensington** [comment]
I haven't tested but ``CMAKE_C_COMPILE_OBJECT`` and ``CMAKE_CXX_COMPILE_OBJECT`` reference ``CPPFLAGS`` so it's possible that will need handling too.

**Comment by mgorny** [comment]
@reavertm has proposed a better solution on the bug, so I'm closing this.

**Pull request closed without merging**
