### PR TITLE
media-gfx/oxipng: add 6.0.0

### PR DESCRIPTION
**Pull request by negge**

### CODE REVIEW

**Comment by Kangie** [comment]
Thanks! I'll take a look when I have some time today!

**Comment by Kangie** [comment]
Hey @negge thanks for submitting this PR.

The first "Issue" that I can see is that you haven't asked the bot rescan your commit to remove the 'no-signoff' tag - you just need to append `[please reassign]` to the PR title and the bot will take care of that now that your commit is updated. :)

The actual feedback that I have is:

1. You can remove `RESTRICT="mirror"` and comment above; if it's making it into `::gentoo` the packages will be mirrored.
2. In `metadata.xml`, could you please indent the `longdescription` appropriately? It's also a little wordy - if you remove everything but current [Line 18](https://github.com/gentoo/gentoo/pull/27158/files#diff-ccc3473f2790c3d9c39340bcc2be05080f558cf550980708e89f55d196e064e1R18) I think it keeps the essence of what we need to communicate; the upstream URI is there for people that want a look over the history!

Outside of that, I've taken your commit and built it locally and confirmed that it's passing tests on `~amd64`, so it's looking pretty good.

I'll need to look over the licences a bit when I have some time later today; there might be some additional feedback once I do.

Cheers!

**Comment by Kangie** [comment]
@lo48576: Courtesy ping since you're maintaining this on `::guru`; any thoughts? Would you like to be put down as an additional maintainer here?

@thesamesam: Licences look good (validated against `cargo-license`). For stuff like this we may need to look at increasing the complexity of license parsing OR insisting that crates be added to the tree (but I see that getting messy), I get:

```bash 
kangie@monolith ~/oxipng (master) $ /home/kangie/.cargo/bin/cargo-license --avoid-build-deps
0BSD OR Apache-2.0 OR MIT (1): adler
Apache-2.0 (3): libdeflate-sys, libdeflater, zopfli
Apache-2.0 AND Zlib OR MIT AND Zlib (2): cloudflare-zlib, cloudflare-zlib-sys
Apache-2.0 OR MIT (45): bit-vec, bitflags, cfg-if, clap, clap_lex, crc, crc-catalog, crc32fast, crossbeam-channel, crossbeam-deque, crossbeam-epoch, crossbeam-utils, deflate, either, filetime, glob, hashbrown, hermit-abi, indexmap, iter-read, itertools, libc, log, num-integer, num-rational, num-traits, num_cpus, once_cell, os_str_bytes, png, rayon, rayon-core, scopeguard, stderrlog, thread_local, wild, winapi, winapi-i686-pc-windows-gnu, winapi-x86_64-pc-windows-gnu, windows-sys, windows_aarch64_msvc, windows_i686_gnu, windows_i686_msvc, windows_x86_64_gnu, windows_x86_64_msvc
Apache-2.0 OR MIT OR Zlib (3): bytemuck, miniz_oxide, miniz_oxide
MIT (10): atty, color_quant, image, memoffset, oxipng, redox_syscall, rgb, strsim, textwrap, typed-arena
MIT OR Unlicense (3): byteorder, termcolor, winapi-util
Zlib (1): adler32

```

Which, I guess expands out to `Apache-2.0 && ZLib && MIT` after some manual parsing...

@negge apparently also has access to `arm64` and `riscv` hardware, so don't be surprised if those additional keywords turn up. :)

**Comment by negge** [comment]
> @negge apparently also has access to `arm64` and `riscv` hardware, so don't be surprised if those additional keywords turn up. :)

Yep I also tested on arm64 and riscv and have added the masked KEYWORDS.

**Comment by lo48576** [comment]
> @lo48576: Courtesy ping since you're maintaining this on `::guru`; any thoughts? Would you like to be put down as an additional maintainer here?

@Kangie Thank you for pinging me. Yes, I'd like to continue contributing as an additional maintener of this package.

I think this package is worth adding to the ::gentoo because:

* Famous alternative (media-gfx/optipng) seems like not actively maintained (the last release is 2017-12-27), and repository under development is not found (possibly not open?).
* In contrast, oxipng is at least actively maintained and bugs would be fixed sooner.
* I'm using oxipng everywhere (for example taking screen capture and automatically compress it), but I have no recollection having trouble with it. I think oxipng is stable enough.

My concern is <https://bugs.gentoo.org/860063> (and maybe <https://bugs.gentoo.org/709568#c7>), the LTO issue related to Rust.
I believe it may not affect so many users, but I don't know ideal solution and don't know this package can be added with this unsolved issue.

**Comment by thesamesam** [comment]
I'm very happy to proceed then.

As for LTO - don't worry about it for Rust. It's a pain and many Rust packages have this issue. Just add filter-lto for now.

**Comment by thesamesam** [comment]
@Kangie Thanks a lot - huge help. As for licences, I tend to include them almost-literally - I avoid simplifying to the point of dropping licenses just in case, especially given this is all so fluid that we have to update LICENSE really often anyway (no point in having lots of manual post-processing). It's better to be right & a bit verbose than not for this.

Remember we can use || ( ... ) for OR and no operator implies AND.

**Comment by negge** [comment]
> @Kangie Thank you for pinging me. Yes, I'd like to continue contributing as an additional maintener of this package.

Done.

> As for LTO - don't worry about it for Rust. It's a pain and many Rust packages have this issue. Just add filter-lto for now.

Done.

> @Kangie Thanks a lot - huge help. As for licences, I tend to include them almost-literally - I avoid simplifying to the point of dropping licenses just in case, especially given this is all so fluid that we have to update LICENSE really often anyway (no point in having lots of manual post-processing). It's better to be right & a bit verbose than not for this.

Done.

@thesamesam Can you have another look and let me know if anything else needs to be addressed?

**Comment by Kangie** [comment]
@lo48576 

Looks like the below will resolve your issues with rust packages reported [here](https://bugs.gentoo.org/709568#c7).

```ebuild
src_configure() {
	filter-lto
}
```

**Pull request closed without merging**
