### PR TITLE
media-video/mpv: verbump to 0.23.0

### PR DESCRIPTION
**Pull request by Coacher**
This version fixes bug 603122. There are also other minor cleanups.

@monsieurp, please, take care of this PR since I've put your name in package.use.mask entry as we did before. I hope you don't mind. Please also don't close bug 603122. I'll update it accordingly myself afterwards.

### CODE REVIEW

**Comment by monsieurp** [comment]
OK.

**Comment by Coacher** [comment]
Thank you very much, @monsieurp.

**Comment by trofi** [comment]
Masking `mpv[libav]` effectively blocks `libav` users from upgrading `mpv`.
portage tells them to install `ffmpeg` and uninstall `libav`.

**Comment by Coacher** [comment]
I know. @trofi, let's discuss this at https://bugs.gentoo.org/show_bug.cgi?id=603992

**Comment by trofi** [comment]
Thanks! CCed.

**Pull request closed without merging**
