### PR TITLE
sys-libs/db: port to EAPI 6

### PR DESCRIPTION
**Pull request by hanetzer**
There are some problems with this one I can't quite solve myself. The upstream
patches seem to be formatted to be -p0, which means they can't be just slapped
into the PATCHES array. One suggestion would be to mirror them in a devspace,
modified to be -p1 applicable (and preferably converted to a unified diff format,
as the context diff used by upstream is 1. very large relatively speaking to a unified
diff and 2. difficult to easily assess visually, as compared to unified diffs).

See also #8314

### CODE REVIEW

**Comment by Whissi** [comment]
Are you willing to contribute the reformatted patch? If it will be to large, I/we will host it following Gentoo rules.

**Comment by hanetzer** [comment]
@Whissi yeah, I can do it. the sizes will be cut pretty drastically by changing from a context
diff to a unified one, but the ebuilds here touched don't currently have one.

**Comment by robbat2** [comment]
Please create a bug for this, and include a diff between ebuild versions for easier review. There's probably a way to avoid reformatting the patch, but I'll have to look a little closer (I would prefer it remain untouched esp. that the newer versions of db upstream went to AGPL).

**Comment by hanetzer** [comment]
@robbat2 Will do, and there probably is a way to do it without reformatting (hypothetical)
patches, it will likely be ugly af and as I mentioned, a unified diff is smaller than a context
diff by about 1/3 to 1/5, depending.

**Comment by hanetzer** [comment]
@Whissi @robbat2 been doing a bit of research. One can use quilt to easily convert between
a context and unified diff. Given sys-libs/db-4.3.29_p1-r1 as an example, one would convert the
patch like so:
```bash
$ ebuild db-4.3.29_p1-r1.ebuild clean unpack
$ cd $PORTAGE_TMPDIR/sys-libs/db-4.3.29_p1-r1/work/db-4.3.29
# this being EAPI=0 patching happens in src_unpack, which is unfortunate. However, we can
# use patch's -R option to reverse the patches applied. Its probably best to reverse patches
# in the opposite order they are applied. Newer EAPI should not do this, so the following step
# is unneeded for them, but I put it here for documentations sake.
$ patch -p0 -R < ../../distdir/patch.4.3.29.1
$ quilt new patch.4.3.29.1-r1.patch # new name to not conflict with original
# We pass --quiltrc - to ignore both the users and the system's quiltrc files to avoid contaminating
# ''official'' patches with user preferences, if any, and the system quiltrc can cause issues as well.
$ quilt --quiltrc - fold -p0 < ../../distdir/patch.4.3.29.1
$ quilt refresh
# your new -p1 unified diff can be found at $PORTAGE_TMPDIR/sys-libs/db-4.3.29_p1-r1/work/db-4.3.29/patches/patch.4.3.29.1-r1.patch
$ wc -c ../../distdir/patch.4.3.29.1
835 ../../distdir/patch.4.3.29.1
$ wc -c patches/patch.4.3.29.1-r1.patch
557 patches/patch.4.3.29.1-r1.patch
# An approximate 1/3 size reduction
```

Before:
```diff
*** mp/mp_fget.c.orig	2006-05-30 20:44:11.000000000 -0700
--- mp/mp_fget.c	2006-05-30 20:44:22.000000000 -0700
***************
*** 577,584 ****
  	 */
  	if (state != SECOND_MISS && bhp->ref == 1) {
  		bhp->priority = UINT32_MAX;
! 		SH_TAILQ_REMOVE(&hp->hash_bucket, bhp, hq, __bh);
! 		SH_TAILQ_INSERT_TAIL(&hp->hash_bucket, bhp, hq);
  		hp->hash_priority =
  		    SH_TAILQ_FIRST(&hp->hash_bucket, __bh)->priority;
  	}
--- 577,587 ----
  	 */
  	if (state != SECOND_MISS && bhp->ref == 1) {
  		bhp->priority = UINT32_MAX;
! 		if (SH_TAILQ_FIRST(&hp->hash_bucket, __bh) !=
! 		     SH_TAILQ_LAST(&hp->hash_bucket, hq, __bh)) {
! 			SH_TAILQ_REMOVE(&hp->hash_bucket, bhp, hq, __bh);
! 			SH_TAILQ_INSERT_TAIL(&hp->hash_bucket, bhp, hq);
! 		}
  		hp->hash_priority =
  		    SH_TAILQ_FIRST(&hp->hash_bucket, __bh)->priority;
  	}
```

After:
```diff
--- a/mp/mp_fget.c
+++ b/mp/mp_fget.c
@@ -577,8 +577,11 @@ alloc:		/*
 	 */
 	if (state != SECOND_MISS && bhp->ref == 1) {
 		bhp->priority = UINT32_MAX;
-		SH_TAILQ_REMOVE(&hp->hash_bucket, bhp, hq, __bh);
-		SH_TAILQ_INSERT_TAIL(&hp->hash_bucket, bhp, hq);
+		if (SH_TAILQ_FIRST(&hp->hash_bucket, __bh) !=
+		     SH_TAILQ_LAST(&hp->hash_bucket, hq, __bh)) {
+			SH_TAILQ_REMOVE(&hp->hash_bucket, bhp, hq, __bh);
+			SH_TAILQ_INSERT_TAIL(&hp->hash_bucket, bhp, hq);
+		}
 		hp->hash_priority =
 		    SH_TAILQ_FIRST(&hp->hash_bucket, __bh)->priority;
 	}
```

**Comment by hanetzer** [comment]
Oh! I just found an even better way. Using `dev-util/patchutils-0.3.4::gentoo`, you will need
to remove lines like `diff -ur SDL2-2.0.8/src/SDL.c SDL2-2.0.8.new/src/SDL.c` first, but after
that, its as simple as `filterdiff --format=unified < patch.4.3.29.1 > patch.4.3.29.1-r1.patch`
You can even do this within vim with `:%!filterdiff --format=unified`

**Comment by robbat2** [comment]
Yep, patchutils is one of the conversion tools. I was planning on using it during src_prepare and keeping upstream's patches pristine until that (so it would convert every time, and we would not mirror patches with AGPL issues)

**Comment by hanetzer** [comment]
What problem does the AGPL bring here? And while converting from context to unified
is useful, the real importance here is -p0 to -p1, and we can't always be certain that every
patch coming from that upstream is going to be -p0, so scripting a solution may be more
work than needed.

**Comment by robbat2** [comment]
There was at least one patch I saw that was a backport from DB-6 to older DB versions, which would have a nasty side-effect of bringing AGPL to the older versions. filterdiff can also convert `-pM` -> `-pN` where N > M.

**Comment by hanetzer** [comment]
@robbat2 I'm purely talking about the patches we currently use. If we're already using them, that
'side effect' has already long happened.

**Pull request closed without merging**
