### PR TITLE
dev-python/jaraco-stream: bump to 1.1.1

### PR DESCRIPTION
**Pull request by sbraz**
This is a rather simple version bump which didn't require any change to the ebuild.

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
Tests fail for me with the following:

```
========================================================= test session starts ==========================================================
platform linux2 -- Python 2.7.10, pytest-2.8.7, py-1.4.30, pluggy-0.3.1
rootdir: /var/tmp/portage/dev-python/jaraco-stream-1.1.1/work/jaraco.stream-1.1.1, inifile: pytest.ini
collected 0 items / 2 errors

================================================================ ERRORS ================================================================
_______________________________________________ ERROR collecting jaraco/stream/buffer.py _______________________________________________
/usr/lib64/python2.7/site-packages/py/_path/local.py:668: in pyimport
    raise self.ImportMismatchError(modname, modfile, self)
E   ImportMismatchError: ('jaraco.stream.buffer', '/var/tmp/portage/dev-python/jaraco-stream-1.1.1/work/jaraco.stream-1.1.1-python2_7/lib/jaraco/stream/buffer.py', local('/var/tmp/portage/dev-python/jaraco-stream-1.1.1/work/jaraco.stream-1.1.1/jaraco/stream/buffer.py'))
________________________________________________ ERROR collecting jaraco/stream/gzip.py ________________________________________________
/usr/lib64/python2.7/site-packages/py/_path/local.py:650: in pyimport
    __import__(modname)
../jaraco.stream-1.1.1-python2_7/lib/jaraco/stream/gzip.py:11: in <module>
    from more_itertools.more import peekable
E   ImportError: No module named more_itertools.more
======================================================= 2 error in 0.24 seconds ========================================================
```

**Comment by sbraz** [comment]
This should work now. I was missing a dependency and there was an issue similar to the rst.linker one.

**Comment by gktrk** [comment]
Merged https://github.com/gentoo/gentoo/commit/82c54423bf0ea24eb6cd4f43bca6f8e44c238c92. Thanks!

**Pull request closed without merging**
