### PR TITLE
gitignore: add pkg_desc_index

### PR DESCRIPTION
**Pull request by hasufell**

### CODE REVIEW

**Comment by hasufell** [comment]
@mgorny this file should definitely be in gitignore, no?

**Comment by mgorny** [comment]
@gentoo/owners, please confirm.

**Comment by mgorny** [comment]
Also `use.local.desc`.

**Comment by hasufell** [comment]
That's already there https://github.com/gentoo/gentoo/blob/master/.gitignore

**Comment by hasufell** [comment]
I want to push push push push :dancers:

**Comment by mgorny** [comment]
Nobody objected so far, you've got my blessing.

**Comment by hasufell** [comment]
https://github.com/gentoo/gentoo/commit/71223a61d552bf30e2752aaa81062136247ed621

**Pull request closed without merging**
