### PR TITLE
Fix asciidoc deps

### PR DESCRIPTION
**Pull request by marcecj**
(This is a continuation of PR #291, which is thus obsolete.)

This small patch series attempts to fix some dependency issues with app-text/asciidoc, as detailed in bug #366763. It revbumps app-text/asciidoc to add a dependency on dblatex and on www-client/w3m or www-client/lynx, one of which is needed for the text output of a2x to work (i.e., `a2x -f text`).  I will probably add app-text/highlight as another alternative to dev-python/pygments after I've tested it.

Furthermore, I have added myself as proxy-maintainer at the suggestion of @djc and removed him as maintainer.

### CODE REVIEW

**Comment by marcecj** [comment]
The question remains about how to handle the deps.  One problem is that a package can override the syntax highlighter used, and I'm not sure how it should best be dealt with.  I will look into it more, but wanted to give a heads up that this is still an open problem.

**Comment by mgorny** [comment]
One possible solution is to expect consumers to DEPEND on additional tools explicitly.

**Comment by marcecj** [comment]
Yeah, I considered that option, too.  The dep in asciidoc itself is then explicitly for *users* of asciidoc and can remain unchanged.  Furthermore, I would argue that the lack of bugs in this regard implies that none of the reverse deps of asciidoc are doing anything fancy in this regard.

**Comment by marcecj** [comment]
OK, this should be the last commit, @mgorny, feel free to comment now.  One thing I'm not sure of: do the dep changes in the last two commits warrant revbumps?  I remember from skimming gentoo-dev that I probably should revbump when changing deps (something about how the deps are recorded after a package is merged and how that can cause dependency problems later on), but the current devmanual doesn't mention that.

**Comment by idella** [comment]
See the new dep dblatex's KEYWORDS then see those of the current asciidoc.This will take more than 1 more commit. The new dep has minimal keywords creating a qa violation. Are you familar with the procedures re keywords; This also indicates you have not yet run repoman full. I am not familiar with your degree of familiarity with repoman itself, the primary qa tool.

**Comment by marcecj** [comment]
Yes, you may have noticed that the same issue cropped up in #291 (in a comment to an outdated diff).  I do in fact *always* run `repoman full -d` before committing and pushing, but am unfamiliar with keywording procedures, so I left things as in #291.  After looking at https://devmanual.gentoo.org/keywording/index.html, my understanding is that:

1. I should postpone adding the dblatex dep, and
2. a bug will have to be opened for keywording dblatex, though I'm not sure who is responsible: me, because I want the keywords, or @zpuskas, because he maintains dblatex?

Is that correct?

(And yes, I should get around to reading through the whole devmanual, I simply haven't had a chance to yet.)

**Comment by marcecj** [comment]
OK, I dropped the dblatex dep.  I'll re-add it once that's possible.

**Comment by idella** [comment]
You have this the wrong way around. The idea is keep the dep and get the keywords updated.
Re-read the docs. Steps; drop keywords form the asciidoc then make a keyword request for them to be
1. all re-added to asciidoc
2. Added to tenew dep for the first time
by the arch teams. This is all in the devmanual.

**Comment by marcecj** [comment]
@idella, thanks for the explanation, I finally found the relevant section ("Keywording on Upgrades").  I take it that this is for making arch testing easier?  And yes, I already mentioned that I need to read the devmanual in full ;-), which I will do before making any more changes to this PR.  In the meantime, feel free to review the other changes.

**Comment by idella** [comment]
/77478d8ba5866c3aea2392e1bc776398506177f3:

commit msg:
"Add a dep on app-text/highlight as another alternative syntax-highlighter for
asciidoc, see http://asciidoc.org/source-highlight-filter.html."

is longish, but still works. This is purely stylistic. Commit msgs are an art not a science.
The guides in gentoo protocol promote terse and to the point. I would do something like:

"add alternative syntax-highlighter to options offered bu IUSE 'highlight'"
stop. The link amounts to too much info.

highlight? ( || ( dev-python/pygments[${PYTHON_USEDEP}] dev-util/source-highlight app-text/highlight ) )
is far toooo looong. Use line breaks with '\'

**Comment by marcecj** [comment]
> commit msg:
> "Add a dep on app-text/highlight as another alternative syntax-highlighter for
> asciidoc, see http://asciidoc.org/source-highlight-filter.html."
> 
> is longish, but still works. This is purely stylistic. Commit msgs are an art not a science.
> The guides in gentoo protocol promote terse and to the point. I would do something like:
> 
> "add alternative syntax-highlighter to options offered bu IUSE 'highlight'"
> stop. The link amounts to too much info.

I'll think of something.  I agree that adding the URL was unnecessary.

> highlight? ( || ( dev-python/pygments[${PYTHON_USEDEP}] dev-util/source-highlight app-text/highlight ) )
> is far toooo looong. Use line breaks with '\'

Done, I'll push it in a second.

> ___________________________________________________-
> PYTHON_COMPAT=( python2_7 pypy )
> 
> Have you actually runtested on pypy?

No, because I didn't add that.  But thanks for pointing that out anyway, because I should install pypy to be able to test that.  Is there a policy on re-testing `$PYTHON_COMPAT` (other than "use common sense", I mean)?

Anyway, here's a proper diff to better show what actually changed:

    % git diff master.. -C -C .

    diff --git a/app-text/asciidoc/asciidoc-8.6.9-r1.ebuild b/app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
    similarity index 85%
    copy from app-text/asciidoc/asciidoc-8.6.9-r1.ebuild
    copy to app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
    index 1bf0d2f..6b9daea 100644
    --- a/app-text/asciidoc/asciidoc-8.6.9-r1.ebuild
    +++ b/app-text/asciidoc/asciidoc-8.6.9-r2.ebuild
    @@ -11,7 +11,7 @@ inherit python-single-r1
     DESCRIPTION="A text document format for writing short documents, articles, books and UNIX man pages"
     HOMEPAGE="http://asciidoc.org/"
     SRC_URI="mirror://sourceforge/project/${PN}/${PN}/${PV}/${P}.tar.gz"
    -KEYWORDS="alpha amd64 arm ~arm64 hppa ia64 ~mips ppc ppc64 ~s390 ~sh sparc x86 ~amd64-fbsd ~x86-fbsd ~x86-freebsd ~amd64-linux ~arm-linux ~x86-linux ~ppc-macos ~x86-macos ~x86-solaris"
    +KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~s390 ~sh ~sparc ~x86 ~amd64-fbsd ~x86-fbsd ~x86-freebsd ~amd64-linux ~arm-linux ~x86-linux ~ppc-macos ~x86-macos ~x86-solaris"
     
     LICENSE="GPL-2"
     SLOT="0"
    @@ -23,7 +23,12 @@ RDEPEND=">=app-text/docbook-xsl-stylesheets-1.75
     		dev-libs/libxslt
     		graphviz? ( media-gfx/graphviz )
     		app-text/docbook-xml-dtd:4.5
    -		highlight? ( || ( dev-python/pygments[${PYTHON_USEDEP}] dev-util/source-highlight ) )
    +		|| ( www-client/w3m www-client/lynx )
    +		highlight? ( || (
    +			dev-util/source-highlight \
    +			dev-python/pygments[${PYTHON_USEDEP}] \
    +			app-text/highlight
    +		) )
     		${PYTHON_DEPS}
     "
     DEPEND="test? ( dev-util/source-highlight
    diff --git a/app-text/asciidoc/asciidoc-9999.ebuild b/app-text/asciidoc/asciidoc-9999.ebuild
    index 038e1f9..070610c 100644
    --- a/app-text/asciidoc/asciidoc-9999.ebuild
    +++ b/app-text/asciidoc/asciidoc-9999.ebuild
    @@ -30,7 +30,12 @@ RDEPEND=">=app-text/docbook-xsl-stylesheets-1.75
     		dev-libs/libxslt
     		graphviz? ( media-gfx/graphviz )
     		app-text/docbook-xml-dtd:4.5
    -		highlight? ( || ( dev-python/pygments[${PYTHON_USEDEP}] dev-util/source-highlight ) )
    +		|| ( www-client/w3m www-client/lynx )
    +		highlight? ( || (
    +			dev-util/source-highlight \
    +			dev-python/pygments[${PYTHON_USEDEP}] \
    +			app-text/highlight
    +		) )
     		${PYTHON_DEPS}
     "
     DEPEND="test? ( dev-util/source-highlight
    diff --git a/app-text/asciidoc/metadata.xml b/app-text/asciidoc/metadata.xml
    index 5b4dfca..65b9a64 100644
    --- a/app-text/asciidoc/metadata.xml
    +++ b/app-text/asciidoc/metadata.xml
    @@ -1,9 +1,11 @@
     <?xml version="1.0" encoding="UTF-8"?>
     <!DOCTYPE pkgmetadata SYSTEM "http://www.gentoo.org/dtd/metadata.dtd">
     <pkgmetadata>
    +	<herd>proxy-maintainers</herd>
     	<maintainer>
    -		<email>djc@gentoo.org</email>
    -		<name>Dirkjan Ochtman</name>
    +		<email>marcec@gmx.de</email>
    +		<name>Marc Joliet</name>
    +		<description>Proxied maintainer. Assign bugs to him.</description>
     	</maintainer>
     	<use>
     		<flag name="highlight">Enable source code highlighting</flag>

**Comment by marcecj** [comment]
(Still reading the devmanual, BTW.  Also, are there other docs I should read?)

**Comment by idella** [comment]
646247d151..... looks fine. Again style convention here.

```ebuild
			dev-python/pygments[${PYTHON_USEDEP}] \
			app-text/highlight
		) )
```

No-one would ever dare mark you 'wrong' on this but this is a teaching session on general ebuild writing, so, by convention it is normally done as:

```ebuild
			dev-python/pygments[${PYTHON_USEDEP}] \
			app-text/highlight )
			)
```
and I wouldn't urge you to change it here. Just take mental note.

re pypy (sighs), it's required to runtest an any and all py targets, sadly many just don't do it with pypy. Once tested once, it will be fine 99% of the time in future bumps. If you don't and it fails a test in a testsuite actually added in the tarball, the rule applies. You bend it you mend it.

This is all looking good, you've done a fine job. I am however confused over the plethora of commits. I think some are defunct and can be closed.  re the addition of dblatex and i am confused. I can say if it were me,i would drop all keywords not supported by the new dep and make the keyword request. In practice i can just make that for you even. It's more important to get the new dep added, wating for later will merely delay the same pain. While there are 2 ways to add the keywords, the method used 99% of the time is to drop and re-add.

Gentoo has a mass of docs yes, but between the devmanual and the general wiki, you will have anything needed covered there. The management of keywords in dropping and re-adding is not typical and has pushed you a little further than usual. You are doing fine here.

Tidy these up, ammend / delete commits as required and repost and we should be about ready to merge.

**Comment by marcecj** [comment]
> 646247d..... looks fine. Again style convention here.
> 
>             dev-python/pygments[${PYTHON_USEDEP}] \
>             app-text/highlight
>         ) )
> 
> No-one would ever dare mark you 'wrong' on this but this is a teaching session on general ebuild writing, so, by convention it is normally done as:
> 
>             dev-python/pygments[${PYTHON_USEDEP}] \
>             app-text/highlight )
>             )
> 
> and I wouldn't urge you to change it here. Just take mental note.

I was undecided myself.  My rationale there was that the opening braces are also on one line, but I admit it looks somewhat awkward.  Mental note taken.

> re pypy (sighs), it's required to runtest an any and all py targets, sadly many just don't do it with pypy. Once tested once, it will be fine 99% of the time in future bumps. If you don't and it fails a test in a testsuite actually added in the tarball, the rule applies. You bend it you mend it.

Right, when *bumping* it definitely makes sense to re-test, but I didn't consider it, since this is just a revbump that fixes some dependencies.

> This is all looking good, you've done a fine job. I am however confused over the plethora of commits. I think some are defunct and can be closed. re the addition of dblatex and i am confused. I can say if it were me,i would drop all keywords not supported by the new dep and make the keyword request. In practice i can just make that for you even. It's more important to get the new dep added, wating for later will merely delay the same pain. While there are 2 ways to add the keywords, the method used 99% of the time is to drop and re-add.

With regards to the commits: since I updated the branch by force-pushing, can it be that you're seeing old ones?  There should only be 6 commits, as listed in the "Commits" tab.

With regards to dblatex: perhaps I was over-thinking, but my original thought was that it would be nice to get the other fixes in without dropping keywords, then deal with dblatex separately.  But I suppose that while I'm revbumping to ~arch, it makes more sense to do as much as possible there.  So I'll re-add the dep, then.

> Gentoo has a mass of docs yes, but between the devmanual and the general wiki, you will have anything needed covered there. The management of keywords in dropping and re-adding is not typical and has pushed you a little further than usual. You are doing fine here.

OK :-)

> Tidy these up (IF required), amend / delete commits as required and repost and we should be about ready to merge.

Alright, I'll make the aforementioned changes soon.

**Comment by marcecj** [comment]
OK, pushed.

**Comment by marcecj** [comment]
Oh, and FWIW: I'm fine with opening the bug myself.  I can do that after this is merged (at least within 24h), unless you'd prefer to do it.

**Comment by idella** [comment]
Slightly confused. I was expecting to find the lines described above as

```ebuild
                highlight? ( || ( dev-util/source-highlight 
                        dev-python/pygments[${PYTHON_USEDEP}] 
                        app-text/highlight ) )
```
but they're all back in one line again.  Since you need tidy the commit msgs, you may as well redo this, but we also agreed it's stylistic and not obligatory.

Commit # 1.  msg
" app-text/asciidoc: revbump to add missing deps"
It's convention to add the version in this line now;  "revbump to 8.6.9-r2 to add missing deps"

"Revbump to add missing deps and drop keywords to match app-text/dblatex."
Repeating yrself here; reduce to;   "drop keywords to match app-text/dblatex" is fine

Commit # 2; msg
"app-text/asciidoc: add dep on app-text/highlight "
ditto; the verion (revbumped) here ought be added. 

"Add app-text/highlight to the list of providers for IUSE "highlight"."
Again repeating yrself here. I would do something like:

"Add  provider "app-text/highlight" behind IUSE highlight"
That ought do it i believe

**Comment by idella** [comment]
oh I forgot;

```bash
   app-text/asciidoc/asciidoc-8.6.9-r1.ebuild: DESCRIPTION is 86 characters (max 80)
   app-text/asciidoc/asciidoc-8.6.9-r2.ebuild: DESCRIPTION is 86 characters (max 80)
   app-text/asciidoc/asciidoc-9999.ebuild: DESCRIPTION is 86 characters (max 80)
```

**Comment by marcecj** [comment]
> Slightly confused. I was expecting to find the lines described above as
> 
>                 highlight? ( || ( dev-util/source-highlight 
>                         dev-python/pygments[${PYTHON_USEDEP}] 
>                         app-text/highlight ) )
> 
> but they're all back in one line again. Since you need tidy the commit msgs, you may as well redo this, but we also agreed it's stylistic and not obligatory.

Yeah, you only pointed at the closing braces though, but while I'm at it, it's a `git commit --amend` away, so not a big deal.

*looks at repo on laptop*

Oh... I see what you *actually* mean, I thought you were referring to the closing braces being on one line.  See, this is an example of why a force-push model isn't optimal in a distributed setting.  I did the previous changes on my laptop but forgot to reset to the remote branch first, so I lost the commit that split the deps onto separate lines, which I did on my desktop; it was still there, so thankfully it was straightforward to fix by rebasing on top of the remote branch.

So yeah, sorry about that!  I should've diffed against the remote branch before force-pushing, then I would've noticed.  (Normally I fetch from origin before working, but I must have forgotten, or not paid enough attention to the output.)

> Commit # 1. msg
> " app-text/asciidoc: revbump to add missing deps"
> It's convention to add the version in this line now; "revbump to 8.6.9-r2 to add missing deps"

OK, I didn't know that, I'll amend that if I can fit it in the summary line.

> "Revbump to add missing deps and drop keywords to match app-text/dblatex."
> Repeating yrself here; reduce to; "drop keywords to match app-text/dblatex" is fine

OK.  I was going to argue that (AFAIK) the usual recommendation is to repeat the contents of the summary line, but if it fits on one line, the repetition is much more noticeable.

> Commit # 4; msg
> "app-text/asciidoc: add dep on app-text/highlight "
> ditto; the verion (revbumped) here ought be added.

Wait a second, are you saying I should revbump for this change? I asked about it before but nobody answered.   Or do you mean that I should specify the version the change applies to?  I'll leave it for now.

> "Add app-text/highlight to the list of providers for IUSE "highlight"."
> Again repeating yrself here. I would do something like:
> 
> "Add provider "app-text/highlight" behind IUSE highlight"

Hmmm... I went with something different.  What do you think?

> That ought do it i believe

> oh I forgot;
> 
>    app-text/asciidoc/asciidoc-8.6.9-r1.ebuild: DESCRIPTION is 86 characters (max 80)
>    app-text/asciidoc/asciidoc-8.6.9-r2.ebuild: DESCRIPTION is 86 characters (max 80)
>    app-text/asciidoc/asciidoc-9999.ebuild: DESCRIPTION is 86 characters (max 80)

Repoman doesn't warn me of this, is this with ~arch portage, or some other tool?  Anyway, it's a quick fix, but this PR was supposed to be about dependency fixes (and assigning myself as proxy-maintainer), so it's off-topic in my opinion, but at the same time, I understand the pragmatism of just going ahead and doing it.  (Also, the dev-ruby/asciidoctor DESCRIPTION is even longer; not that that's an excuse, I just find it amusing ;-) .)

**Comment by idella** [comment]
See here;
 Commits 6 Files changed 3 

So you've taken 6 commits to have changed 3 files. This means you have multiple commits on the one file. Hence the confusion. I did not mean a separate revbump for a separate issue. It is utterly unnecessary to do so. It is always sane to put > 1 change into 1 single revbump all at once. The cases requiring separate revebumps would be rare.

 I would do something like:

"Add provider "app-text/highlight" behind IUSE highlight"
A commit msg is an art form. I put what I *would* do. Being a work or art it is by its nature one of personal preference. While I think mine is better, that's because I am me. AS long as your selected messages meets criteria and wroks, it's fine.

**Comment by marcecj** [comment]
> See here;
> Commits 6 Files changed 3
> 
> So you've taken 6 commits to have changed 3 files. This means you have multiple commits on the one file. Hence the confusion. I did not mean a separate revbump for a separate issue. It is utterly unnecessary to do so. It is always sane to put > 1 change into 1 single revbump all at once. The cases requiring separate revebumps would be rare.

OK

> I would do something like:
> 
> "Add provider "app-text/highlight" behind IUSE highlight"
> A commit msg is an art form. I put what I would do. Being a work or art it is by its nature one of personal preference. While I think mine is better, that's because I am me. AS long as your selected messages meets criteria and works, it's fine. No room for being clobbered there.

OK, in that case I'll leave it as is.  You repeating your preference merely gave me the impression that there was something wrong with mine.

> app-text/asciidoc/asciidoc-8.6.9-r1.ebuild: DESCRIPTION is 86 characters (max 80)
> 
> "it's off-topic in my opinion, but at the same time, I understand the pragmatism of just going ahead and doing it. "
> 
> exactly. merry-go-rounds and roundabouts. 2 points;
> 1. It is qa. When it comes to qa, I don't really think it is off topic.2
> 2. It is highlighted in yellow. It's a non fatal warning.
> which illustrates my point; merry-go-rounds and roundabouts
> 
> That the other DESCRIPTION is even longer is merely proof that the check on the length of DESCRIPTION by repoman is a recent addition in its code. The rule of limit of its length is long standing

Alright, then in the interest of stopping this merry-go-round I'll just fix it in *this* PR.  (But later, when I have the time.) 

Is that about it?

**Comment by idella** [comment]
looks complete to me yes

**Comment by marcecj** [comment]
OK, I pushed the description change.  I only changed the ebuilds mentioned by repoman since I'm probably going to delete the other three anyway, at the very least the oldest two; they're old (2011 and 2012) and 8.6.5 uses a deprecated EAPI.  (Of course I'll wait until I've read the devmanual before actually doing it, but right now that's what I think I'll be doing.)

I'll just go ahead and thank you for all the comments and information!  Whatever other general questions I have (or will think of) I will ask on IRC (I simply haven't gotten around to setting that up yet).

**Comment by idella** [comment]
merged

**Pull request merged**
