### PR TITLE
games-strategy/hedgewars: bump version to 1.0.0

### PR DESCRIPTION
**Pull request by CaseOf**
Hedgewars project have released version 1.0.0 today.
http://hedgewars.org/node/9014

### CODE REVIEW

**Comment by a17r** [comment]
Please don't add and remove ebuilds in the same commit.

No changes between 0.9.25 and 1.0.0?

**Comment by chewi** [comment]
I was just looking at this myself. I don't care too much about the rename thing but yeah, it's generally frowned upon. I've tried it out and it works fine. Admittedly I didn't try the server.

**Comment by CaseOf** [comment]
I did build it. I’m also using a -9999 version on my overlay and talking to hedgewars developers on IRC. There is some changes to do on the ebuild, just wait a bit.

**Comment by a17r** [comment]
```
# @ECLASS-VARIABLE: CMAKE_BUILD_TYPE
# @DESCRIPTION:
# Set to override default CMAKE_BUILD_TYPE. Only useful for packages
# known to make use of "if (CMAKE_BUILD_TYPE MATCHES xxx)".
# If about to be set - needs to be set before invoking cmake-utils_src_configure.
# You usualy do *NOT* want nor need to set it as it pulls CMake default build-type
# specific compiler flags overriding make.conf.
: ${CMAKE_BUILD_TYPE:=Gentoo}
```

**Comment by CaseOf** [comment]
entirely changed the commit.

**Comment by CaseOf** [comment]
updated Manifest since upstream added binaries by mistake in the archive and have removed them now.

**Comment by chewi** [comment]
Sorry for not getting to this quicker. Unfortunately @Polynomial-C added the same version to the tree a couple of days after your amendment.

I'm a bit confused by upstream's requests. All the patches still apply so in what way are they outdated? Changing `CMAKE_BUILD_TYPE` shouldn't be necessary and can be detrimental. Some Gentoo-specific tweaks are made by the eclass based on this and the build itself ends up using `Release` anyway.

```
-- Unknown build type Gentoo, using default (Release)
```

**Comment by CaseOf** [comment]
In my tests, official tarball was always using Debug target if not set.
And upstream said patches are outdated because these issues are fixed in upstream code.
They also said they don’t know what are results with these patches set on builds.
You can still talk to them in #hedgewars channel on Freenode IRC network.

**Comment by CaseOf** [comment]
About patch hedgewars-0.9.22-rpath-fix.patch, it has zero effects on the build as it is patching a section for macOS builds.

**Comment by CaseOf** [comment]
and the debian patch thing was for a droplet bug in 0.9.23 that was fixed long time ago.
then all these patches are pointless

**Comment by CaseOf** [comment]
Also if you want to keep debian stuff, prefer to use theirs for 1.0.0 instead of 0.9.23 which can lead to unknown behavior on a newer version.

**Comment by chewi** [comment]
Thanks for going into detail here. The rpath patch isn't for MacOS (it's the `else` clause) it is only applies when `/usr` isn't in the prefix. It always is for us.

**Pull request closed without merging**
