### PR TITLE
sci-libs/opencascade: drop 7.5.1-r1

### PR DESCRIPTION
**Pull request by waebbl**
cleanup

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by ionenwks** [comment]
Can't clean this one yet, requires cleaning dealii-9.3.0-r1 first (9.3.1 has CAS_VERSION=7.5.2 but older one is still 7.5.1), I wonder why CI didn't pick that up.

**Comment by waebbl** [comment]
Yeah I wonder too. The `check-revdep` script from `app-portage/mgorny-dev-scripts` picks it up, but I haven't run the check before pushing this. I want to remove 7.4.0 soonish too, and will go and check more thoroughly on revdeps.
Thanks for pointing this out.

**Comment by waebbl** [comment]
Wondering even more, as `dealii-9.2.0-r1` accepts any slot of opencascade. Might this be a leftover from occt-6* still in the tree? If so, could we clean this version or does it build with 7.5.2?
pinging @tamiko as maintainer

**Comment by waebbl** [comment]
dealii has been updated to support 7.5.3. Thanks @tamiko for updating the package.

Tried to cleanup 7.5.2 as well, but kicad depends on <7.5.3 as of now.

Going to start testing of deslotting the package and get rid of the eselect module and in the process add a (masked) 7.6.0_beta from my overlay.

**Review by ionenwks — APPROVED** [review]
Yep, all good now, thanks.

> Going to start testing of deslotting the package and get rid of the eselect module and in the process add a (masked) 7.6.0_beta from my overlay.

That sounds nice, hope it'll go well.

**Comment by waebbl** [comment]
> > Going to start testing of deslotting the package and get rid of the eselect module and in the process add a (masked) 7.6.0_beta from my overlay.
> 
> That sounds nice, hope it'll go well.

I'm hoping too that it goes well. It would simplify revdeps a lot.

**Pull request closed without merging**
