### PR TITLE
gnome-base/gvfs: bump to 1.48.0

### PR DESCRIPTION
**Pull request by scardracs**
drop patch (is not required anymore)
move to virtual/libusb

Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by mattst88** [comment]
A lot of version bumping is checking dependencies. I usually diff `meson.build` and `meson_options.txt` between packaged versions to see what's changed. I appreciate the PR, but unless you do that bit of the work as well it's not really saving me any time :(

**Comment by scardracs** [comment]
> A lot of version bumping is checking dependencies. I usually diff `meson.build` and `meson_options.txt` between packaged versions to see what's changed. I appreciate the PR, but unless you do that bit of the work as well it's not really saving me any time :(

Actually PATCH looks like it's not required anymore... I'm trying to make test working but actually looks like it compiles without problems

**Comment by mattst88** [comment]
Yes, dropping the patch is fine because it's upstream and included in the 1.48.0 release.

What I mean are the versions in the `DEPEND` variables. E.g., here's the diff of 1.44.1's `meson.build` vs 1.48.0's `meson.build`:

````diff
--- gvfs-1.44.1/work/gvfs-1.44.1/meson.build	2021-04-14 16:09:36.197152029 -0400
+++ gvfs-1.48.0/work/gvfs-1.48.0/meson.build	2021-03-19 10:04:53.887319800 -0400
@@ -1,9 +1,9 @@
 project(
   'gvfs', 'c',
-  version: '1.44.1',
+  version: '1.48.0',
   license: 'LGPL2+',
   default_options: 'buildtype=debugoptimized',
-  meson_version: '>= 0.50.0',
+  meson_version: '>= 0.53.0',
 )
 
 gvfs_name = meson.project_name()
@@ -231,7 +231,7 @@
 
 gio_dep = dependency('gio-2.0')
 gio_unix_dep = dependency('gio-unix-2.0')
-glib_dep = dependency('glib-2.0', version: '>= 2.57.2')
+glib_dep = dependency('glib-2.0', version: '>= 2.65.1')
 gobject_dep = dependency('gobject-2.0')
 gsettings_desktop_schemas_dep = dependency('gsettings-desktop-schemas', version: '>= 3.33.0')
 
@@ -419,7 +419,7 @@
 if enable_google
   assert(enable_goa, 'Google backend requested but GOA is required')
 
-  libgdata_dep = dependency('libgdata', version: '>= 0.17.11')
+  libgdata_dep = dependency('libgdata', version: '>= 0.18.0')
 endif
 
 # *** Check for gphoto2 ***
@@ -490,37 +490,42 @@
   gio_giomoduledir,
 )
 
-output = gvfs_name + ' ' + gvfs_version + ' configuration summary:\n'
-output += '\n'
-output += '  systemduserunitdir: ' + systemd_systemduserunitdir + '\n'
-output += '  tmpfilesdir: ' + systemd_tmpfilesdir + '\n'
-output += '\n'
-output += '  admin: ' + enable_admin.to_string() + '\n'
-output += '  afc: ' + enable_afc.to_string() + '\n'
-output += '  afp: ' + enable_afp.to_string() + '\n'
-output += '  archive: ' + enable_archive.to_string() + '\n'
-output += '  cdda: ' + enable_cdda.to_string() + '\n'
-output += '  dnssd: ' + enable_dnssd.to_string() + '\n'
-output += '  goa: ' + enable_goa.to_string() + '\n'
-output += '  google: ' + enable_google.to_string() + '\n'
-output += '  gphoto2: ' + enable_gphoto2.to_string() + '\n'
-output += '  http: ' + enable_http.to_string() + '\n'
-output += '  mtp: ' + enable_mtp.to_string() + '\n'
-output += '  nfs: ' + enable_nfs.to_string() + '\n'
-output += '  sftp: ' + enable_sftp.to_string() + '\n'
-output += '  smb: ' + enable_samba.to_string() + '\n'
-output += '  udisks2: ' + enable_udisks2.to_string() + '\n'
-output += '\n'
-output += '  bluray: ' + enable_bluray.to_string() + '\n'
-output += '  fuse: ' + enable_fuse.to_string() + '\n'
-output += '  gcr: ' + enable_gcr.to_string() + '\n'
-output += '  gcrypt: ' + enable_gcrypt.to_string() + '\n'
-output += '  gudev: ' + enable_gudev.to_string() + '\n'
-output += '  keyring: ' + enable_keyring.to_string() + '\n'
-output += '  logind: ' + enable_logind.to_string() + '\n'
-output += '  libusb: ' + enable_libusb.to_string() + '\n'
-output += '\n'
-output += '  devel_utils: ' + enable_devel_utils.to_string() + '\n'
-output += '  installed_tests: ' + enable_installed_tests.to_string() + '\n'
-output += '  man: ' + enable_man.to_string() + '\n'
-message(output)
+summary({
+  'systemduserunitdir': systemd_systemduserunitdir,
+  'tmpfilesdir': systemd_tmpfilesdir,
+}, section: 'Directories')
+
+summary({
+  'admin': enable_admin,
+  'afc': enable_afc,
+  'afp': enable_afp,
+  'archive': enable_archive,
+  'cdda': enable_cdda,
+  'dnssd': enable_dnssd,
+  'goa': enable_goa,
+  'google': enable_google,
+  'gphoto2': enable_gphoto2,
+  'http': enable_http,
+  'mtp': enable_mtp,
+  'nfs': enable_nfs,
+  'sftp': enable_sftp,
+  'smb': enable_samba,
+  'udisks2': enable_udisks2,
+}, section: 'Backends')
+
+summary({
+  'bluray': enable_bluray,
+  'fuse': enable_fuse,
+  'gcr': enable_gcr,
+  'gcrypt': enable_gcrypt,
+  'gudev': enable_gudev,
+  'keyring': enable_keyring,
+  'logind': enable_logind,
+  'libusb': enable_libusb,
+}, section: 'Dependencies')
+
+summary({
+  'devel_utils': enable_devel_utils,
+  'installed_tests': enable_installed_tests,
+  'man': enable_man,
+})
````

The required versions of glib and libgdata have changed, but the new ebuild does not reflect that.

**Comment by scardracs** [comment]
> Yes, dropping the patch is fine because it's upstream and included in the 1.48.0 release.
> 
> What I mean are the versions in the `DEPEND` variables. E.g., here's the diff of 1.44.1's `meson.build` vs 1.48.0's `meson.build`:
> 
> ```diff
> --- gvfs-1.44.1/work/gvfs-1.44.1/meson.build	2021-04-14 16:09:36.197152029 -0400
> +++ gvfs-1.48.0/work/gvfs-1.48.0/meson.build	2021-03-19 10:04:53.887319800 -0400
> @@ -1,9 +1,9 @@
>  project(
>    'gvfs', 'c',
> -  version: '1.44.1',
> +  version: '1.48.0',
>    license: 'LGPL2+',
>    default_options: 'buildtype=debugoptimized',
> -  meson_version: '>= 0.50.0',
> +  meson_version: '>= 0.53.0',
>  )
>  
>  gvfs_name = meson.project_name()
> @@ -231,7 +231,7 @@
>  
>  gio_dep = dependency('gio-2.0')
>  gio_unix_dep = dependency('gio-unix-2.0')
> -glib_dep = dependency('glib-2.0', version: '>= 2.57.2')
> +glib_dep = dependency('glib-2.0', version: '>= 2.65.1')
>  gobject_dep = dependency('gobject-2.0')
>  gsettings_desktop_schemas_dep = dependency('gsettings-desktop-schemas', version: '>= 3.33.0')
>  
> @@ -419,7 +419,7 @@
>  if enable_google
>    assert(enable_goa, 'Google backend requested but GOA is required')
>  
> -  libgdata_dep = dependency('libgdata', version: '>= 0.17.11')
> +  libgdata_dep = dependency('libgdata', version: '>= 0.18.0')
>  endif
>  
>  # *** Check for gphoto2 ***
> @@ -490,37 +490,42 @@
>    gio_giomoduledir,
>  )
>  
> -output = gvfs_name + ' ' + gvfs_version + ' configuration summary:\n'
> -output += '\n'
> -output += '  systemduserunitdir: ' + systemd_systemduserunitdir + '\n'
> -output += '  tmpfilesdir: ' + systemd_tmpfilesdir + '\n'
> -output += '\n'
> -output += '  admin: ' + enable_admin.to_string() + '\n'
> -output += '  afc: ' + enable_afc.to_string() + '\n'
> -output += '  afp: ' + enable_afp.to_string() + '\n'
> -output += '  archive: ' + enable_archive.to_string() + '\n'
> -output += '  cdda: ' + enable_cdda.to_string() + '\n'
> -output += '  dnssd: ' + enable_dnssd.to_string() + '\n'
> -output += '  goa: ' + enable_goa.to_string() + '\n'
> -output += '  google: ' + enable_google.to_string() + '\n'
> -output += '  gphoto2: ' + enable_gphoto2.to_string() + '\n'
> -output += '  http: ' + enable_http.to_string() + '\n'
> -output += '  mtp: ' + enable_mtp.to_string() + '\n'
> -output += '  nfs: ' + enable_nfs.to_string() + '\n'
> -output += '  sftp: ' + enable_sftp.to_string() + '\n'
> -output += '  smb: ' + enable_samba.to_string() + '\n'
> -output += '  udisks2: ' + enable_udisks2.to_string() + '\n'
> -output += '\n'
> -output += '  bluray: ' + enable_bluray.to_string() + '\n'
> -output += '  fuse: ' + enable_fuse.to_string() + '\n'
> -output += '  gcr: ' + enable_gcr.to_string() + '\n'
> -output += '  gcrypt: ' + enable_gcrypt.to_string() + '\n'
> -output += '  gudev: ' + enable_gudev.to_string() + '\n'
> -output += '  keyring: ' + enable_keyring.to_string() + '\n'
> -output += '  logind: ' + enable_logind.to_string() + '\n'
> -output += '  libusb: ' + enable_libusb.to_string() + '\n'
> -output += '\n'
> -output += '  devel_utils: ' + enable_devel_utils.to_string() + '\n'
> -output += '  installed_tests: ' + enable_installed_tests.to_string() + '\n'
> -output += '  man: ' + enable_man.to_string() + '\n'
> -message(output)
> +summary({
> +  'systemduserunitdir': systemd_systemduserunitdir,
> +  'tmpfilesdir': systemd_tmpfilesdir,
> +}, section: 'Directories')
> +
> +summary({
> +  'admin': enable_admin,
> +  'afc': enable_afc,
> +  'afp': enable_afp,
> +  'archive': enable_archive,
> +  'cdda': enable_cdda,
> +  'dnssd': enable_dnssd,
> +  'goa': enable_goa,
> +  'google': enable_google,
> +  'gphoto2': enable_gphoto2,
> +  'http': enable_http,
> +  'mtp': enable_mtp,
> +  'nfs': enable_nfs,
> +  'sftp': enable_sftp,
> +  'smb': enable_samba,
> +  'udisks2': enable_udisks2,
> +}, section: 'Backends')
> +
> +summary({
> +  'bluray': enable_bluray,
> +  'fuse': enable_fuse,
> +  'gcr': enable_gcr,
> +  'gcrypt': enable_gcrypt,
> +  'gudev': enable_gudev,
> +  'keyring': enable_keyring,
> +  'logind': enable_logind,
> +  'libusb': enable_libusb,
> +}, section: 'Dependencies')
> +
> +summary({
> +  'devel_utils': enable_devel_utils,
> +  'installed_tests': enable_installed_tests,
> +  'man': enable_man,
> +})
> ```
> 
> The required versions of glib and libgdata have changed, but the new ebuild does not reflect that.

I have already fix them, I'm waiting to upload them when test will be fixed :)

**Pull request closed without merging**
