### PR TITLE
dev-db/mariadb: add 10.6.17, 10.11.7

### PR DESCRIPTION
**Pull request by hydrapolic**
https://mariadb.com/kb/en/mariadb-10-6-17-release-notes/
https://mariadb.com/kb/en/mariadb-10-11-7-release-notes/

Dropping the include patch. It now builds with USE=columnstore (tested on amd64).

```bash
--- mariadb-10.6.16.ebuild      2024-02-15 03:59:46.083493763 +0000
+++ mariadb-10.6.17.ebuild      2024-02-23 06:35:04.957411220 +0000
@@ -217,7 +217,6 @@
 src_prepare() {
        eapply "${WORKDIR}"/mariadb-patches
        eapply "${FILESDIR}"/${PN}-10.6.11-gssapi.patch
-       eapply "${FILESDIR}"/${PN}-10.6.11-include.patch
        eapply "${FILESDIR}"/${PN}-10.6.12-gcc-13.patch
 
        eapply_user
```

### CODE REVIEW

**Comment by arkamar** [comment]
ah, I see, the `filter-lto` was added after this PR, few days ago, see https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=3feee7984bf0b20f52f20dec288f152d756004da.

**Comment by arkamar** [comment]
Just for the record, both fail with this error:
```
CURRENT_TEST: main.ssl_crl
--- /var/tmp/portage/dev-db/mariadb-10.11.7/work/mysql/mysql-test/main/ssl_crl.result   2024-02-01 17:44:36.000000000 +0000
+++ /var/tmp/portage/dev-db/mariadb-10.11.7/work/mysql/mysql-test/main/ssl_crl.reject   2024-03-07 14:25:49.246417953 +0000
@@ -2,4 +2,4 @@
 Variable_name  Value
 Ssl_version    TLS_VERSION
 # try logging in with a certificate in the server's --ssl-crl : should fail
-ERROR 2026 (HY000): TLS/SSL error: sslv3 alert certificate revoked
+ERROR 2026 (HY000): TLS/SSL error: ssl/tls alert certificate revoked

mysqltest: Result length mismatch
```
This happens because of this change in openssl-3.2.*: https://github.com/openssl/openssl/commit/81b741f68984b2620166d0d6271fbd946bab9e7f

**Comment by hydrapolic** [comment]
Actually, for this versions, I haven't run the tests. However I was doing massive testing on it (migrating production between various DC), so it's a bit battle tested ;)

**Comment by arkamar** [comment]
I am not going to block the merge because of this test. It is obviously test issue.

**Comment by hydrapolic** [comment]
Pushed an update @arkamar, only the include patch is removed since it was upstreamed.

**Comment by arkamar** [comment]
I added following to the commit message:
> The include patch is removed since it was upstreamed.

It is useful info and it is always better to have it there.

**Comment by hydrapolic** [comment]
> I added following to the commit message:
> 
> > The include patch is removed since it was upstreamed.
> 
> It is useful info and it is always better to have it there.

I thought you mean the lto removal, now I see. Thanks for the help @arkamar !

**Pull request closed without merging**
