### PR TITLE
dev-libs/aws-checksums: bump to 0.1.9

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by Yamakuzure** [comment]
@jsmolic : Current versions are aws-c-common-0.1.54 and aws-checksums-0.1.9

**Comment by jsmolic** [comment]
@Yamakuzure Thanks, done!\
I suppose you want to maintain these packages again, so I added that here

**Comment by Yamakuzure** [comment]
@jsmolic : Thanks alot! :smile:

**Comment by Yamakuzure** [comment]
This should be merged right before #17536.

**Comment by Yamakuzure** [comment]
Unfortunately the SDK needs a higher version of aws-c-event-stream, which needs a higher version of aws-c-common, or the test suite fails.

I have put down my aws-c-event-stream PR and am preparing a fixing PR for aws-c-common, aws-c-event-stream and aws-sdk-cpp, which will fix https://bugs.gentoo.org/742650

I *think* aws-checksums is just fine, so if you could kindly take out aws-c-common (if the bumped aws-checksums is okay with the old aws-c-common), then our PRs wouldn't bite each other.

However, if aws-checksums also needs a higher aws-c-common version, then please tell me, and I'll add it to my fixing PR.

**Comment by jsmolic** [comment]
@Yamakuzure Done, I think that bumped `aws-checksums` work with old `aws-c-common`, in any case, this could be merged before https://github.com/gentoo/gentoo/pull/17576

**Comment by jsmolic** [comment]
@juippis Can you push this now that https://github.com/gentoo/gentoo/pull/17576 will be merged? Thanks!

**Comment by juippis** [comment]
Hmm, I didn't see any problems testing the other aws PR. Although I did no runtime testing. Can you quickly explain what's the situation in here?

**Comment by jsmolic** [comment]
> Hmm, I didn't see any problems testing the other aws PR. Although I did no runtime testing. Can you quickly explain what's the situation in here?

Initially I updated `aws-c-checksums` and `aws-c-common`, but @Yamakuzure opened new PRs in the meantime that caused conflicts with this one. Long story short, `aws-sdk-cpp` required `aws-c-common` to be updated at the same time, but it was not, which led to new bugs being reported. I think `aws-c-checksums` does not seem to cause conflicts with other packages. Given that  this was opened for a month, and other aws PRs were merged in the meantime I thought I'd ping you :)\
Anyway It's up to you, I can close this PR and let @Yamakuzure handle the update.

**Review by juippis — APPROVED** [review]
Not like this hurts anyone to update though...

**Comment by jsmolic** [comment]
@juippis Thanks!

**Comment by juippis** [comment]
You too!

**Pull request closed without merging**
