### PR TITLE
sci-biology/bcftools: fix PYTHON_COMPAT, add missing matplotlib dep

### PR DESCRIPTION
**Pull request by mmokrejs**

### CODE REVIEW

**Comment by mmokrejs** [comment]
@SoapGentoo  @heroxbd Please merge this simple fix/cleanup.

**Comment by SoapGentoo** [comment]
@mmokrejs your dependency specification of matplotlib was incorrect, I fixed it, but please don't forget `${PYTHON_USEDEP}` on python packages

**Comment by mmokrejs** [comment]
> @mmokrejs your dependency specification of matplotlib was incorrect, I fixed it, but please don't forget `${PYTHON_USEDEP}` on python packages

@SoapGentoo Indeed, I totally forgot about the `${PYTHON_USEDEP}`. Thank you. This is something the many EAPI bumps could take care of, btw.

**Comment by heroxbd** [comment]
Thank you David!

**Pull request closed without merging**
