### PR TITLE
sys-apps/ucspi-ssl: Version bump to 0.99e

### PR DESCRIPTION
**Pull request by powerman**
Closes: https://bugs.gentoo.org/678930
Closes: https://bugs.gentoo.org/625574
Closes: https://bugs.gentoo.org/645252
Package-Manager: Portage-2.3.51, Repoman-2.3.11
Signed-off-by: Aleksandr Efros <powerman-asdf@yandex.ru>

### CODE REVIEW

**Comment by powerman** [comment]
Just wondering is I'm supposed to manually append `Signed-off-by: ` line each time I run `repoman -dx commit`, or there is a way to automate this crap?

**Comment by juippis** [comment]
> or there is a way to automate this crap?

yes, DCO_SIGNED_OFF_BY value in your make.conf, that works when you commit with repoman.

**Comment by powerman** [comment]
Is there any issues with this PR, or it's normal to have PR not merged in 3 weeks?

**Comment by powerman** [comment]
Thanks @steils. Maybe you can also take a look at https://github.com/gentoo/gentoo/pull/11220?

**Pull request closed without merging**
