### PR TITLE
app-text/po4a: apply patch from upstream for xsl lookup

### PR DESCRIPTION
**Pull request by clan**
otherwise build will failed w/:

1. can't find xsl file
2. can't get xsl from net because of -nonet option

patch is from upstream

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by hattya** [comment]
[bug #939204](https://bugs.gentoo.org/939204) will fix this issue.

**Comment by clan** [comment]
Can we fix the more recent stable ebuild if future stable ebuild won't be marked as stable in short time?

**Comment by thesamesam** [comment]
Yeah, I think it makes sense given the stablereq seems stuck.

**Comment by thesamesam** [comment]
... but the patch isn't in this PR?

**Comment by clan** [comment]
@hattya please consider merge this one if no more issues, 3 months passed, ...

**Pull request closed without merging**
