### PR TITLE
dev-python/configargparse: bump to 0.13.0 & remove old

### PR DESCRIPTION
**Pull request by juippis**
A dependency needed for a package I wish to maintain later. I can become a proxy-maintainer for this if it's ok for gentoo/python. 

Couldn't get the tests to pass, I spent a lot of time trying. Decided it's not worth it. At least one failure has been reported upstream without any responds.

Updated EAPI to 7 and added python3.7 to PYTHON_COMPAT. Builds and as far as I can see, works fine. Nothing seemed to need =0.12.0 so I remove it here. The CI bot will let me know...

### CODE REVIEW

**Comment by mgorny** [comment]
The tests pass for me when run from git checkout via `tox` for py34/35, so we should really make them work in the ebuild as well. There's one failure with 36/37 but there's apparently [a fix for it](https://github.com/bw2/ConfigArgParse/pull/123). Apparently there's also some failure with py27 but that might be just me not testing it correctly.

**Comment by juippis** [comment]
>There's one failure with 36/37 but there's apparently a fix for it.

I did find and use the patch in PR, but ran into two different test failures after. One with [FormatHelp](https://github.com/bw2/ConfigArgParse/blob/master/tests/test_configargparse.py#L728) and other with TestMisc. 

The one with FormatHelp was similar to patched one, with failing regexp. Did my best to make them match, but I'm going to try a bit harder tomorrow then. Can't remember the one with TestMisc anymore, but I'll see it tomorrow :)

**Comment by mgorny** [comment]
Thank you, your help with this is much appreciated. I'd suggest to start with py3.4+3.5 since we know that those two should work. Then start fixing issues from there.

**Comment by juippis** [comment]
At this point, tests with `python2.7`, `python3.4` and `python3.5` succeed. I'm not sure anymore if they work "vanilla" or due to modifications, I've pretty much patched out failing parts from the test file :). Not the cleanest solution but getting forward...

So after removing failing parts from the test file, it fails with `python3.6` and `python3.7` to something that it hadn't even attempted doing with earlier versions. Getting, 
```
test_help_with_metavar (__main__.TestWrappingMetavar) ... Command Line Args:   -c /tmp/portage/dev-python/configargparse-0.13.0/temp/tmpr00agdua
Config File (/tmp/portage/dev-python/configargparse-0.13.0/temp/tmpr00agdua):
  genome:            hg20
FAIL

======================================================================
FAIL: test_help_with_metavar (__main__.TestWrappingMetavar)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "<string>", line 5018, in test_help_with_metavar
AssertionError: 'usage: test_configargparse.py [-h] [--proxy <http[134 chars]4>\n' != 'usage: this_is_spammy_prog_with_a_long_name_sorry[177 chars]4>\n'
- usage: test_configargparse.py [-h] [--proxy <http[s]://example:1234>]
+ usage: this_is_spammy_prog_with_a_long_name_sorry_about_the_name
+        [-h] [--proxy <http[s]://example:1234>]
  
  optional arguments:
    -h, --help            show this help message and exit
    --proxy <http[s]://example:1234>


----------------------------------------------------------------------
Ran 1590 tests in 2.528s

FAILED (failures=1)
Traceback (most recent call last):
  File "tests/test_configargparse.py", line 849, in <module>
    exec(test_argparse_source_code)
  File "<string>", line 5030, in <module>
  File "<string>", line 5022, in test_main
  File "/usr/lib64/python3.6/test/support/__init__.py", line 1998, in run_unittest
    _run_suite(suite)
  File "/usr/lib64/python3.6/test/support/__init__.py", line 1917, in _run_suite
    raise TestFailed(err)
test.support.TestFailed: Traceback (most recent call last):
  File "<string>", line 5018, in test_help_with_metavar
AssertionError: 'usage: test_configargparse.py [-h] [--proxy <http[134 chars]4>\n' != 'usage: this_is_spammy_prog_with_a_long_name_sorry[177 chars]4>\n'
- usage: test_configargparse.py [-h] [--proxy <http[s]://example:1234>]
+ usage: this_is_spammy_prog_with_a_long_name_sorry_about_the_name
+        [-h] [--proxy <http[s]://example:1234>]
  
  optional arguments:
    -h, --help            show this help message and exit
    --proxy <http[s]://example:1234>

```

And that failure seems to be coming from python's own `test_argparse.py`. Something has probably changed because this failure only appears with 3.6 and 3.7, but not earlier 

```
# equery f python | grep -i test_argparse.py
/usr/lib64/python2.7/test/test_argparse.py
/usr/lib64/python2.7/test/test_argparse.pyc
/usr/lib64/python2.7/test/test_argparse.pyo
/usr/lib64/python3.4/test/test_argparse.py
/usr/lib64/python3.5/test/test_argparse.py
/usr/lib64/python3.6/test/test_argparse.py
/usr/lib/python3.7/test/test_argparse.py
```

[See also](https://github.com/bw2/ConfigArgParse/blob/master/tests/test_configargparse.py#L1035)

Not sure how I should proceed because I don't know how to disable or fix this one. Only enable tests with python2.7, 3.4 and 3.5? 

For the record, it seems like Debian packages this with python2, Fedora doesn't seem to run tests and Arch ignores test results and installs nevertheless (so no help from neighbours).

**Comment by juippis** [comment]
Don't see any differences,

`COLS="200" EMERGE_DEFAULT_OPTS="--jobs=1"  FEATURES="test" emerge configargparse::localhost`

This is what you meant I hope? Tried with 80, 180, 200 and 1500.

**Comment by juippis** [comment]
If I uncomment lines [1055-1063](https://github.com/bw2/ConfigArgParse/blob/master/tests/test_configargparse.py#L1055) then tests pass, but it seems to lower the amount of tests drastically. Haven't figured other ways to get forward with this so far. 

```
 * python3_6: running distutils-r1_run_phase python_test
running test
running egg_info
writing ConfigArgParse.egg-info/PKG-INFO
writing dependency_links to ConfigArgParse.egg-info/dependency_links.txt
writing requirements to ConfigArgParse.egg-info/requires.txt
writing top-level names to ConfigArgParse.egg-info/top_level.txt
reading manifest file 'ConfigArgParse.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ConfigArgParse.egg-info/SOURCES.txt'
running build_ext
testAddArgsErrors (tests.test_configargparse.TestBasicUseCases) ... ok
testAutoEnvVarPrefix (tests.test_configargparse.TestBasicUseCases) ... ok
testBasicCase1 (tests.test_configargparse.TestBasicUseCases) ... ok
testBooleanValuesCanBeExpressedAsNumbers (tests.test_configargparse.TestBasicUseCases) ... ok
testConfigFileSyntax (tests.test_configargparse.TestBasicUseCases) ... ok
testConfigOrEnvValueErrors (tests.test_configargparse.TestBasicUseCases) ... ok
testEnvVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testPositionalAndConfigVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testPositionalAndEnvVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testSubParsers (tests.test_configargparse.TestBasicUseCases) ... ok
testDefaultConfigFileParser_All (tests.test_configargparse.TestConfigFileParsers) ... ok
testDefaultConfigFileParser_Basic (tests.test_configargparse.TestConfigFileParsers) ... ok
testYAMLConfigFileParser_All (tests.test_configargparse.TestConfigFileParsers) ... ok
testYAMLConfigFileParser_Basic (tests.test_configargparse.TestConfigFileParsers) ... ok
test_missing_argument_name_in_message (tests.test_configargparse.TestMessageContentError) ... ok
test_optional_optional_not_in_message (tests.test_configargparse.TestMessageContentError) ... ok
test_optional_positional_not_in_message (tests.test_configargparse.TestMessageContentError) ... ok
testAddArguments_ArgValidation (tests.test_configargparse.TestMisc) ... ok
testAddArguments_IsConfigFilePathArg (tests.test_configargparse.TestMisc) ... ok
testConstructor_ConfigFileArgs (tests.test_configargparse.TestMisc) ... Command Line Args:   -c /tmp/portage/dev-python/configargparse-0.13.0/temp/tmptu3xtw_2
Config File (/tmp/portage/dev-python/configargparse-0.13.0/temp/tmptu3xtw_2):
  genome:            hg20
ok
testConstructor_WriteOutConfigFileArgs (tests.test_configargparse.TestMisc) ... /usr/lib64/python3.6/argparse.py:203: ResourceWarning: unclosed file <_io.FileIO name=3 mode='wb' closefd=True>
  self.formatter = formatter
/usr/lib64/python3.6/argparse.py:203: ResourceWarning: unclosed file <_io.FileIO name=4 mode='wb' closefd=True>
  self.formatter = formatter
ok
testConstructor_WriteOutConfigFileArgs2 (tests.test_configargparse.TestMisc) ... ok
testConstructor_WriteOutConfigFileArgsLong (tests.test_configargparse.TestMisc)
Test config writing with long version of arg ... ok
testGlobalInstances (tests.test_configargparse.TestMisc) ... ok
testGlobalInstances_WithName (tests.test_configargparse.TestMisc) ... ok
testKwrgsArePassedToArgParse (tests.test_configargparse.TestMisc) ... /usr/lib64/python3.6/site-packages/mock/mock.py:1986: ResourceWarning: unclosed file <_io.FileIO name=3 mode='rb+' closefd=True>
  setattr(_type, entry, MagicProxy(entry, self))
/usr/lib64/python3.6/site-packages/mock/mock.py:1986: ResourceWarning: unclosed file <_io.FileIO name=4 mode='rb+' closefd=True>
  setattr(_type, entry, MagicProxy(entry, self))
ok
testMethodAliases (tests.test_configargparse.TestMisc) ... ok
test_AbbrevConfigFileArgs (tests.test_configargparse.TestMisc)
Tests that abbreviated values don't get pulled from config file. ... ok

----------------------------------------------------------------------
Ran 28 tests in 0.073s

OK
 * python3_7: running distutils-r1_run_phase python_test
running test
running egg_info
writing ConfigArgParse.egg-info/PKG-INFO
writing dependency_links to ConfigArgParse.egg-info/dependency_links.txt
writing requirements to ConfigArgParse.egg-info/requires.txt
writing top-level names to ConfigArgParse.egg-info/top_level.txt
reading manifest file 'ConfigArgParse.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'ConfigArgParse.egg-info/SOURCES.txt'
running build_ext
testAddArgsErrors (tests.test_configargparse.TestBasicUseCases) ... ok
testAutoEnvVarPrefix (tests.test_configargparse.TestBasicUseCases) ... ok
testBasicCase1 (tests.test_configargparse.TestBasicUseCases) ... ok
testBooleanValuesCanBeExpressedAsNumbers (tests.test_configargparse.TestBasicUseCases) ... ok
testConfigFileSyntax (tests.test_configargparse.TestBasicUseCases) ... ok
testConfigOrEnvValueErrors (tests.test_configargparse.TestBasicUseCases) ... ok
testEnvVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testPositionalAndConfigVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testPositionalAndEnvVarLists (tests.test_configargparse.TestBasicUseCases) ... ok
testSubParsers (tests.test_configargparse.TestBasicUseCases) ... ok
testDefaultConfigFileParser_All (tests.test_configargparse.TestConfigFileParsers) ... ok
testDefaultConfigFileParser_Basic (tests.test_configargparse.TestConfigFileParsers) ... ok
testYAMLConfigFileParser_All (tests.test_configargparse.TestConfigFileParsers) ... /usr/lib/python3.7/site-packages/yaml/constructor.py:126: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  if not isinstance(key, collections.Hashable):
ok
testYAMLConfigFileParser_Basic (tests.test_configargparse.TestConfigFileParsers) ... ok
test_missing_argument_name_in_message (tests.test_configargparse.TestMessageContentError) ... ok
test_optional_optional_not_in_message (tests.test_configargparse.TestMessageContentError) ... ok
test_optional_positional_not_in_message (tests.test_configargparse.TestMessageContentError) ... ok
testAddArguments_ArgValidation (tests.test_configargparse.TestMisc) ... ok
testAddArguments_IsConfigFilePathArg (tests.test_configargparse.TestMisc) ... ok
testConstructor_ConfigFileArgs (tests.test_configargparse.TestMisc) ... Command Line Args:   -c /tmp/portage/dev-python/configargparse-0.13.0/temp/tmpz_vap69m
Config File (/tmp/portage/dev-python/configargparse-0.13.0/temp/tmpz_vap69m):
  genome:            hg20
ok
testConstructor_WriteOutConfigFileArgs (tests.test_configargparse.TestMisc) ... ok
testConstructor_WriteOutConfigFileArgs2 (tests.test_configargparse.TestMisc) ... /usr/lib/python3.7/argparse.py:177: ResourceWarning: unclosed file <_io.FileIO name=3 mode='wb' closefd=True>
  max(width - 20, indent_increment * 2))
/usr/lib/python3.7/argparse.py:177: ResourceWarning: unclosed file <_io.FileIO name=4 mode='wb' closefd=True>
  max(width - 20, indent_increment * 2))
/usr/lib/python3.7/argparse.py:177: ResourceWarning: unclosed file <_io.FileIO name=5 mode='rb+' closefd=True>
  max(width - 20, indent_increment * 2))
ok
testConstructor_WriteOutConfigFileArgsLong (tests.test_configargparse.TestMisc)
Test config writing with long version of arg ... ok
testGlobalInstances (tests.test_configargparse.TestMisc) ... ok
testGlobalInstances_WithName (tests.test_configargparse.TestMisc) ... ok
testKwrgsArePassedToArgParse (tests.test_configargparse.TestMisc) ... ok
testMethodAliases (tests.test_configargparse.TestMisc) ... /usr/lib/python3.7/argparse.py:1246: ResourceWarning: unclosed file <_io.FileIO name=3 mode='rb+' closefd=True>
  super(_ActionsContainer, self).__init__()
ok
test_AbbrevConfigFileArgs (tests.test_configargparse.TestMisc)
Tests that abbreviated values don't get pulled from config file. ... ok

----------------------------------------------------------------------
Ran 28 tests in 0.079s

OK
 * python2_7: running distutils-r1_run_phase _distutils-r1_clean_egg_info
 * python3_4: running distutils-r1_run_phase _distutils-r1_clean_egg_info
 * python3_5: running distutils-r1_run_phase _distutils-r1_clean_egg_info
 * python3_6: running distutils-r1_run_phase _distutils-r1_clean_egg_info
 * python3_7: running distutils-r1_run_phase _distutils-r1_clean_egg_info
>>> Completed testing dev-python/configargparse-0.13.0
```

28 tests compared to previous 1586. Still, seems to test "the important stuff". Installs and works fine as far as I can tell. Anyway, wanted to give some sort of status update here, and looking for guidance how to continue.

**Comment by juippis** [comment]
Looks like it's been bumped, can't say I'm not happy about it :)

**Pull request closed without merging**
