### PR TITLE
net-misc/networkmanager: Version bump to 1.48.4

### PR DESCRIPTION
**Pull request by flint2**

### CODE REVIEW

**Comment by mattst88** [comment]
Does this test fail for you?

```
=================================== 27/73 ====================================
test:         config/test-config
start time:   14:41:44
duration:     0.14s
result:       exit status 5
command:      MALLOC_PERTURB_=23 /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh --called-f
rom-make /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64 '' '' '' --launch-dbus=auto /var/tmp/p
ortage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config
----------------------------------- stdout -----------------------------------
TAP version 13
# random seed: R02Sc7facb55bc1103446838c775af90e6ea
1..14
# Start of config tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
ok 1 /config/simple
ok 2 /config/non-existent
ok 3 /config/parse-error
ok 4 /config/no-auto-default
ok 5 /config/confdir
ok 6 /config/confdir-parse-error
ok 7 /config/warnings
# (../NetworkManager-1.45.2/src/core/tests/config/test-config.c:1107) invalid value in config-data .intern.with-whitespace.key2 = (null) (instead of " b c\,  d  ")
exec "/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config" failed
 with exit code 133
----------------------------------- stderr -----------------------------------
/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh: line 307:   337 Trace/breakpoint trap   (c
ore dumped) "${NMTST_DBUS_RUN_SESSION[@]}" "$TEST" "${TEST_ARGV[@]}"
==============================================================================
```

It's the only failure for me.

**Comment by mattst88** [comment]
Looks like it fails in 1.44.0 as well. I don't recall that happening when we added that version.

**Comment by flint2** [comment]
> Does this test fail for you?
> 
> ```
> =================================== 27/73 ====================================
> test:         config/test-config
> start time:   14:41:44
> duration:     0.14s
> result:       exit status 5
> command:      MALLOC_PERTURB_=23 /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh --called-f
> rom-make /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64 '' '' '' --launch-dbus=auto /var/tmp/p
> ortage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config
> ----------------------------------- stdout -----------------------------------
> TAP version 13
> # random seed: R02Sc7facb55bc1103446838c775af90e6ea
> 1..14
> # Start of config tests
> # GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
> ok 1 /config/simple
> ok 2 /config/non-existent
> ok 3 /config/parse-error
> ok 4 /config/no-auto-default
> ok 5 /config/confdir
> ok 6 /config/confdir-parse-error
> ok 7 /config/warnings
> # (../NetworkManager-1.45.2/src/core/tests/config/test-config.c:1107) invalid value in config-data .intern.with-whitespace.key2 = (null) (instead of " b c\,  d  ")
> exec "/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config" failed
>  with exit code 133
> ----------------------------------- stderr -----------------------------------
> /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh: line 307:   337 Trace/breakpoint trap   (c
> ore dumped) "${NMTST_DBUS_RUN_SESSION[@]}" "$TEST" "${TEST_ARGV[@]}"
> ==============================================================================
> ```
> 
> It's the only failure for me.

Yes, same FAIL

```
meson test --print-errorlogs -C /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64 --num-processes 12
ninja: Entering directory `/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64'
ninja: no work to do.
 1/72 check-local-gitlab-ci                                   OK               0.04s
 2/72 check-tree                                              OK               0.04s
 3/72 check-local-gen-metadata-nm-settings-libnm-core         OK               0.04s
 4/72 check-settings-docs                                     OK               0.03s
 5/72 check-local-gen-metadata-nm-settings-nmcli              OK               0.03s
 6/72 dnsmasq/test-dnsmasq-utils                              OK               0.03s
 7/72 platform/test-address-fake                              OK               0.02s
 8/72 platform/test-address-linux                             OK               0.05s
 9/72 platform/test-cleanup-fake                              OK               0.05s
10/72 platform/test-cleanup-linux                             OK               0.05s
11/72 platform/test-link-fake                                 OK               0.05s
12/72 platform/test-link-linux                                OK               0.04s
13/72 platform/test-route-fake                                OK               0.04s
14/72 platform/test-nmp-object                                OK               0.05s
15/72 platform/test-route-linux                               OK               0.04s
16/72 platform/test-tc-linux                                  OK               0.05s
17/72 check-local-exports-libnm                               OK               0.12s
18/72 platform/test-platform-general                          OK               0.07s
19/72 test-core                                               OK               0.06s
20/72 test-dcb                                                OK               0.05s
21/72 supplicant/test-supplicant-config                       OK               0.08s
22/72 test-l3cfg                                              OK               0.06s
23/72 test-utils                                              OK               0.06s
24/72 test-wired-defname                                      OK               0.06s
25/72 test-systemd                                            OK               0.06s
26/72 dhcp/test-dhcp-dhclient                                 OK               0.08s
27/72 dhcp/test-dhcp-utils                                    OK               0.09s
28/72 config/test-config                                      FAIL             0.16s   exit status 5
>>> MALLOC_PERTURB_=232 /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh --called-from-make /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64 '' '' '' --launch-dbus=auto /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config
――――――――――――――――――――――――――――――――――――― ✀  ―――――――――――――――――――――――――――――――――――――
stdout:
TAP version 13
# random seed: R02S194fafe0bc7a4d6d218b4de479e14e1f
1..14
# Start of config tests
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
ok 1 /config/simple
ok 2 /config/non-existent
ok 3 /config/parse-error
ok 4 /config/no-auto-default
ok 5 /config/confdir
ok 6 /config/confdir-parse-error
ok 7 /config/warnings
# (../NetworkManager-1.45.2/src/core/tests/config/test-config.c:1107) invalid value in config-data .intern.with-whitespace.key2 = (null) (instead of " b c\,  d  ")
exec "/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/src/core/tests/config/test-config" failed with exit code 133
stderr:
/var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2/tools/run-nm-test.sh: line 307:   284 Trace/breakpoint trap   (core dumped) "${NMTST_DBUS_RUN_SESSION[@]}" "$TEST" "${TEST_ARGV[@]}"
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

29/72 wwan/test-service-providers                             OK               0.10s
30/72 test-devices-wifi                                       OK               0.09s
31/72 devices/test-lldp                                       OK               0.09s
32/72 check-wwan                                              OK               0.15s
33/72 check-local-devices-adsl                                OK               0.16s
34/72 sym/libnm-ppp-plugin.so                                 OK               0.09s
35/72 sym/libnm-device-plugin-adsl.so                         OK               0.08s
36/72 check-local-devices-wifi                                OK               0.16s
37/72 check-local-devices-bluetooth                           OK               0.17s
38/72 sym/libnm-wwan.so                                       OK               0.08s
39/72 test-keyfile-settings                                   OK               0.15s
40/72 sym/libnm-device-plugin-wwan.so                         OK               0.09s
41/72 sym/libnm-device-plugin-bluetooth.so                    OK               0.09s
42/72 sym/libnm-device-plugin-wifi.so                         OK               0.09s
43/72 src/libnm-glib-aux/tests/test-shared-general            OK               0.09s
44/72 src/libnm-glib-aux/tests/test-json-aux                  OK               0.09s
45/72 src/libnm-platform/tests/test-nm-platform               OK               0.10s
46/72 src/libnm-core-impl/tests/test-compare                  OK               0.09s
47/72 src/libnm-core-impl/tests/test-secrets                  OK               0.08s
48/72 src/libnm-core-impl/tests/test-keyfile                  OK               0.10s
49/72 src/libnm-core-impl/tests/test-crypto                   OK               0.13s
50/72 src/libnm-core-impl/tests/test-settings-defaults        OK               0.10s
51/72 check-config-options                                    OK               0.21s
52/72 src/libnm-client-impl/tests/test-libnm                  OK               0.12s
53/72 src/libnm-client-aux-extern/tests/test-libnm-client-aux OK               0.07s
54/72 src/libnm-core-impl/tests/test-general                  OK               0.21s
55/72 src/libnmc-setting/tests/test-libnmc-setting            OK               0.06s
56/72 src/nm-dispatcher/tests/test-dispatcher-envp            OK               0.08s
57/72 nm-initrd-generator/tests/test-dt-reader                OK               0.07s
58/72 nm-initrd-generator/tests/test-ibft-reader              OK               0.07s
59/72 src/libnm-core-impl/tests/test-setting                  OK               0.27s
60/72 src/nm-cloud-setup/tests/test-cloud-setup-general       OK               0.10s
61/72 nm-initrd-generator/tests/test-cmdline-reader           OK               0.12s
62/72 check-local-libnm-gir                                   OK               0.34s
63/72 src/libnm-client-impl/tests/test-remote-settings-client OK               0.40s
64/72 check-docs                                              OK               0.31s
65/72 check-nm-autoptr                                        OK               0.38s
66/72 check-vapi                                              OK               0.47s
67/72 check-local-tests-cloud-setup                           OK               0.60s
68/72 test-core-with-expect                                   OK               1.33s
69/72 src/libnm-client-impl/tests/test-secret-agent           OK               3.11s
70/72 src/libnm-client-impl/tests/test-nm-client              OK               4.42s
71/72 check-local-tests-client                                OK               7.51s
72/72 ndisc/test-ndisc-fake                                   OK              20.92s

Summary of Failures:

28/72 config/test-config                                      FAIL             0.16s   exit status 5

Ok:                 71  
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/net-misc/networkmanager-1.45.2/work/NetworkManager-1.45.2-abi_x86_64.amd64/meson-logs/testlog.txt

```

```
 # equery b /usr/include/glib-2.0/gio/gvfs.h
 * Searching for /usr/include/glib-2.0/gio/gvfs.h ... 
dev-libs/glib-2.77.3 (/usr/include/glib-2.0/gio/gvfs.h)
# equery b /usr/lib64/gio/modules/libgvfsdbus.so
 * Searching for /usr/lib64/gio/modules/libgvfsdbus.so ... 
gnome-base/gvfs-1.50.6 (/usr/lib64/gio/modules/libgvfsdbus.so)
```

**Comment by flint2** [comment]
Test OK
```

>>> Test phase: net-misc/networkmanager-1.45.4
 * abi_x86_64.amd64: running multilib-minimal_abi_src_test
 * Checking whether python3_12 is suitable ...
 *   dev-lang/python:3.12 ...                                                                               [ ok ]
 *   python_check_deps ...
 *     dev-python/pygobject:3[python_targets_python3_12(-)] ...                                             [ ok ]
 *     dev-python/dbus-python[python_targets_python3_12(-)] ...                                             [ ok ]
 *     dev-python/pygobject:3[python_targets_python3_12(-)] ...                                             [ ok ]
 * Using python3.12 to build (via EPYTHON)
 * Starting Xvfb ...
 * Xvfb started on DISPLAY=:2
meson test --print-errorlogs -C /var/tmp/portage/net-misc/networkmanager-1.45.4/work/NetworkManager-1.45.4-abi_x86_64.amd64 --num-processes 12
ninja: Entering directory `/var/tmp/portage/net-misc/networkmanager-1.45.4/work/NetworkManager-1.45.4-abi_x86_64.amd64'
ninja: no work to do.
 1/72 check-local-gitlab-ci                                   OK               0.05s
 2/72 check-tree                                              OK               0.05s
 3/72 check-local-gen-metadata-nm-settings-libnm-core         OK               0.05s
 4/72 check-settings-docs                                     OK               0.04s
 5/72 check-local-gen-metadata-nm-settings-nmcli              OK               0.04s
 6/72 dnsmasq/test-dnsmasq-utils                              OK               0.04s
 7/72 platform/test-address-fake                              OK               0.07s
 8/72 platform/test-address-linux                             OK               0.07s
 9/72 platform/test-cleanup-fake                              OK               0.09s
10/72 platform/test-cleanup-linux                             OK               0.08s
11/72 platform/test-link-fake                                 OK               0.09s
12/72 platform/test-link-linux                                OK               0.08s
13/72 platform/test-nmp-object                                OK               0.09s
14/72 platform/test-route-fake                                OK               0.08s
15/72 platform/test-route-linux                               OK               0.08s
16/72 platform/test-platform-general                          OK               0.11s
17/72 check-local-exports-libnm                               OK               0.19s
18/72 platform/test-tc-linux                                  OK               0.11s
19/72 supplicant/test-supplicant-config                       OK               0.12s
20/72 test-core                                               OK               0.10s
21/72 config/test-config                                      OK               0.12s
22/72 test-dcb                                                OK               0.09s
23/72 test-l3cfg                                              OK               0.11s
24/72 test-utils                                              OK               0.11s
25/72 test-wired-defname                                      OK               0.10s
26/72 test-systemd                                            OK               0.13s
27/72 dhcp/test-dhcp-dhclient                                 OK               0.15s
28/72 dhcp/test-dhcp-utils                                    OK               0.15s
29/72 wwan/test-service-providers                             OK               0.15s
30/72 test-devices-wifi                                       OK               0.13s
31/72 check-local-devices-adsl                                OK               0.22s
32/72 devices/test-lldp                                       OK               0.16s
33/72 sym/libnm-ppp-plugin.so                                 OK               0.12s
34/72 sym/libnm-device-plugin-adsl.so                         OK               0.13s
35/72 check-wwan                                              OK               0.27s
36/72 check-local-devices-bluetooth                           OK               0.26s
37/72 test-keyfile-settings                                   OK               0.19s
38/72 sym/libnm-wwan.so                                       OK               0.12s
39/72 check-local-devices-wifi                                OK               0.28s
40/72 sym/libnm-device-plugin-wwan.so                         OK               0.13s
41/72 sym/libnm-device-plugin-bluetooth.so                    OK               0.14s
42/72 sym/libnm-device-plugin-wifi.so                         OK               0.13s
43/72 src/libnm-glib-aux/tests/test-shared-general            OK               0.13s
44/72 src/libnm-glib-aux/tests/test-json-aux                  OK               0.12s
45/72 src/libnm-platform/tests/test-nm-platform               OK               0.12s
46/72 src/libnm-core-impl/tests/test-compare                  OK               0.12s
47/72 src/libnm-core-impl/tests/test-crypto                   OK               0.15s
48/72 check-config-options                                    OK               0.24s
49/72 src/libnm-core-impl/tests/test-keyfile                  OK               0.15s
50/72 src/libnm-core-impl/tests/test-secrets                  OK               0.14s
51/72 src/libnm-core-impl/tests/test-settings-defaults        OK               0.10s
52/72 src/libnm-client-impl/tests/test-libnm                  OK               0.14s
53/72 src/libnm-core-impl/tests/test-general                  OK               0.26s
54/72 src/libnm-client-aux-extern/tests/test-libnm-client-aux OK               0.12s
55/72 src/nm-dispatcher/tests/test-dispatcher-envp            OK               0.10s
56/72 src/libnmc-setting/tests/test-libnmc-setting            OK               0.15s
57/72 nm-initrd-generator/tests/test-dt-reader                OK               0.12s
58/72 nm-initrd-generator/tests/test-ibft-reader              OK               0.13s
59/72 src/libnm-core-impl/tests/test-setting                  OK               0.38s
60/72 src/nm-cloud-setup/tests/test-cloud-setup-general       OK               0.12s
61/72 nm-initrd-generator/tests/test-cmdline-reader           OK               0.16s
62/72 check-local-libnm-gir                                   OK               0.43s
63/72 src/libnm-client-impl/tests/test-remote-settings-client OK               0.60s
64/72 check-docs                                              OK               0.40s
65/72 test-core-with-expect                                   OK               1.36s
66/72 check-nm-autoptr                                        OK               0.52s
67/72 check-vapi                                              OK               0.58s
68/72 check-local-tests-cloud-setup                           OK               0.86s
69/72 src/libnm-client-impl/tests/test-secret-agent           OK               3.58s
70/72 src/libnm-client-impl/tests/test-nm-client              OK               5.50s
71/72 check-local-tests-client                                OK              10.25s
72/72 ndisc/test-ndisc-fake                                   OK              20.49s

Ok:                 72  
Expected Fail:      0   
Fail:               0   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/net-misc/networkmanager-1.45.4/work/NetworkManager-1.45.4-abi_x86_64.amd64/meson-logs/testlog.txt
>>> Completed testing net-misc/networkmanager-1.45.4
```

**Pull request closed without merging**
