### PR TITLE
net-analyzer/fail2ban: add py3.5, drop old patches, fix fbsd deps

### PR DESCRIPTION
**Pull request by sbraz**
Patches are no longer required as per:
https://github.com/fail2ban/fail2ban/commit/294a7790a9a32f98448e1e2a2d7a5cfdf741c35f
https://github.com/fail2ban/fail2ban/commit/869d99dd377ff45efa5796bb3be2500e41f32dc3

This is almost the same as https://github.com/gentoo/gentoo/pull/736, here's the diff between the normal and live ebuilds:
```diff
--- fail2ban-0.9.3-r1.ebuild	2016-01-31 16:30:10.166344845 +0100
+++ fail2ban-99999999.ebuild	2016-02-11 01:02:59.833721244 +0100
@@ -6,15 +6,15 @@
 PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} pypy )
 DISTUTILS_SINGLE_IMPL=1
 
-inherit distutils-r1 eutils systemd vcs-snapshot
+inherit distutils-r1 eutils systemd git-r3
 
 DESCRIPTION="scans log files and bans IPs that show malicious signs"
 HOMEPAGE="http://www.fail2ban.org/"
-SRC_URI="https://github.com/${PN}/${PN}/tarball/${PV} -> ${P}.tar.gz"
+EGIT_REPO_URI="https://github.com/${PN}/${PN}"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS="~amd64 ~arm ~hppa ~ppc ~ppc64 ~sparc ~x86 ~x86-fbsd"
+KEYWORDS=""
 IUSE="selinux systemd"
 
 RDEPEND="
@@ -37,23 +37,17 @@
 	# Replace /var/run with /run, but not in the top source directory
 	sed -i -e 's|/var\(/run/fail2ban\)|\1|g' $( find . -mindepth 2 -type f ) || die
 
-	# Fix bashisms and do not direct useful output to /dev/null (bug #536320)
-	# Remove global logrotate settings (bug #549856)
-	epatch \
-		"${FILESDIR}"/${PN}-0.9.2-initd.patch \
-		"${FILESDIR}"/${PN}-0.9.2-logrotate.patch
-
 	distutils-r1_src_prepare
 }
 
 python_test() {
-	${EPYTHON} bin/${PN}-testcases
+	${EPYTHON} bin/${PN}-testcases || die "tests failed with ${EPYTHON}"
 }
 
 src_install() {
 	distutils-r1_src_install
 
-	rm -rf "${D}"/usr/share/doc/${PN} "${D}"/run
+	rm -r "${D}"/usr/share/doc/${PN} "${D}"/run || die
 
 	# not FILESDIR
 	newconfd files/gentoo-confd ${PN}
@@ -96,7 +90,6 @@
 			elog "If you want to use ${PN}'s persistent database, then reinstall"
 			elog "dev-lang/python with USE=sqlite"
 		fi
-
 		if has_version sys-apps/systemd[-python]; then
 			elog "If you want to track logins through sys-apps/systemd's"
 			elog "journal backend, then reinstall sys-apps/systemd with USE=python"

```

### CODE REVIEW

**Comment by idella** [comment]
Do you really want this 
DOCS=( ChangeLog DEVELOP README.md THANKS TODO doc/run-rootless.txt )
?
I'd probably prefer to let the eclass install its default and then add to it with:

local DOCS="$DOCS[@] this and that" within the python_install() or python_install_all().

Also 
src_prepare() -> python_prepare_all()
distutils-r1_src_prepare -> distutils-r1_ python_prepare_all

${EPYTHON} bin/${PN}-testcases -> "${PYTHON}" bin/${PN}-testcases
src_install() -> python_install()
distutils-r1_src_install -> distutils-r1_python_install

 			elog has 3 tab spaces but I don't see it needs any more than one.

and then
+	kernel_linux? ( net-firewall/iptables ) 
poses more uncertainties.

**Comment by NP-Hardass** [comment]
Please include sys-freebsd/freebsd-pf for BSD in place of iptables.

**Comment by idella** [comment]
this first request above is itself up for review. The surplanting of sys-freebsd/freebsd-pf over  iptables is a bold, eeer, move? The second appears sound

**Comment by NP-Hardass** [comment]
I'm on the Gentoo BSD team, and that is what I'd like done :P.
There is no iptables for freebsd because iptables relies on things specific to the linux kernel. I've chosen to resolve this in the simple way of setting the dep to a bsd firewall software to handle it for the time being, hence the TODO.
No boldness to be found.

**Comment by sbraz** [comment]
@NP-Hardass @idella This should address most of the issues you raised. I have not had time to refactor DOCS yet, I'll do it later today.
Let me know if you think of other fixes I should apply. Maybe when all looks good we can fix the non-live ebuild as well.

**Comment by idella** [comment]
You already know what I think. Now you need find someone to commit your patch whatever state it reaches on becoming final. I cannot

**Comment by sbraz** [comment]
@vapier can you look at this please?

**Comment by sbraz** [comment]
Rewrote using more detailed commits. Here is the diff between the live and stable ebuild:
```diff
--- fail2ban-0.9.3-r1.ebuild    2016-02-24 13:56:42.875088879 +0100
+++ fail2ban-99999999.ebuild    2016-02-24 14:00:43.207807162 +0100
@@ -6,15 +6,15 @@
 PYTHON_COMPAT=( python{2_7,3_3,3_4,3_5} pypy )
 DISTUTILS_SINGLE_IMPL=1
 
-inherit distutils-r1 eutils systemd vcs-snapshot
+inherit distutils-r1 eutils systemd git-r3
 
 DESCRIPTION="scans log files and bans IPs that show malicious signs"
 HOMEPAGE="http://www.fail2ban.org/"
-SRC_URI="https://github.com/${PN}/${PN}/tarball/${PV} -> ${P}.tar.gz"
+EGIT_REPO_URI="https://github.com/${PN}/${PN}"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS="amd64 arm hppa ~ppc ppc64 ~sparc x86 ~x86-fbsd"
+KEYWORDS=""
 IUSE="selinux systemd"
 
 # TODO support ipfw and ipfilter
@@ -40,12 +40,6 @@
        find . -mindepth 2 -type f -exec \
                sed -i -e 's|/var\(/run/fail2ban\)|\1|g' {} + || die
 
-       # Fix bashisms and do not direct useful output to /dev/null (bug #536320)
-       # Remove global logrotate settings (bug #549856)
-       epatch \
-               "${FILESDIR}"/${PN}-0.9.2-initd.patch \
-               "${FILESDIR}"/${PN}-0.9.2-logrotate.patch
-
        distutils-r1_python_prepare_all
 }
 
```

**Comment by vapier** [comment]
changes look fine to me.  thanks!

**Comment by monsieurp** [comment]
Merged.

**Pull request closed without merging**
