### PR TITLE
media-video/makemkv: update

### PR DESCRIPTION
**Pull request by rindeal**
`repoman` currently complaints about linguas not being present in `linguas.desc` file, but I don't know what could be done about it.

@chewi

### CODE REVIEW

**Comment by chewi** [comment]
Thanks, good stuff here. I can be a bit picky so I hope you don't mind me giving some feedback.

`fdo-mime_desktop_database_update` is used to update MIME information from .desktop files but we create the .desktop file ourselves and it doesn't contain any MIME entries.

I think the `use qt4 || use qt5` stuff around the icon cache functions is needlessly complicated. `gnome2_icon_savelist` checks whether any icons have been installed and if none have then `gnome2_icon_cache_update` doesn't do anything.

I've never seen more than one `inherit` in an ebuild before. I don't think it's technically wrong but it's still unusual and I guess most people put them together near the top because `man 5 ebuild` says this.

> Also note that the inherit statement must come before other variable declarations unless these variables are used in global scope of eclasses.

I found the location stuff a bit confusing at first. I guess it's okay but I'll see if we can patch around it instead because /opt/share is a bit weird. We already patch some of the paths anyway.

**Comment by rindeal** [comment]
Thank you for your feedback, it's great, I usually learn something new and this case is no exception

I always though that `fdo-mime_desktop_database_update()` is a general handler for all `.desktop` things. So this means that things like `kbuildsycoca5` are self-contained contrary to these gnome2 utils and `fdo-mime*` are probably unrelated to both of them. Well, that's kinda mess, but I hope I'll remember it from now on.

When `fdo-mime` is out now, I'll remove the dedicated function, but still I'd like to keep it at least as:
``` ebuild
use qt4 || use qt5 && gnome2_icon_savelist
```
so that it's not called when no one wants it.

Regarding the `inherit`s, it's true, I also have never seen someone else coding like this. Still, `l10n` is so far the only eclass which I'm putting after `*DEPEND` vars, because `PLOCALES` is quite wildly used and can quickly become a huge string/array, which hurts readability as `DESCRIPTION` and alike are then pushed too far from the header.
The man page says a general rule, because putting inherits at the top of the ebuild is a safety measure against eclasses which declare variables like `HOMEPAGE`, but this is not the case with ultra lightweight and single purpose eclasses like `l10n`. But it's just my opinion, you're the boss here.

> I found the location stuff a bit confusing at first

That makes me sad as I tried to make the situation as clear as possible: explanation at the top, special variable for each root dir, dedicated `into`/`insinto` for each logical block...
`/opt/share` is simply an optionally shared directory :smiley:. , a bit uncommon, but Google says we wouldn't be alone in the universe with this directory.

My order of preferences in situations like this is: _no patching_ -> _sed_/... -> _patch_, but I'm a lazy person, so if you want to go with patching, you have my blessing.

Btw. do you know what about those nonstandard `PLOCALES`?

**Comment by rindeal** [comment]
So, I removed `fdo-mime*()`s, and the wrapper around `gnome2_icon*()`. Also I added custom entries to metadata.xml for each locale, which finally makes repoman happy.

**Comment by chewi** [comment]
I have partially merged your changes, giving credit to you where I can. Read the commit messages for the long version but the short version is that patching around the "share" issue wasn't an option and it was far simpler all round to just stick everything under /usr. I also didn't like the non-standard locales so I remapped them with an associative array. I just need to merge my fix for l10n.eclass for the check to properly. Thanks for your help.

**Comment by rindeal** [comment]
> I also didn't like the non-standard locales so I remapped them with an associative array. I just need to merge my fix for l10n.eclass for the check to properly. Thanks for your help.

That sounds like https://github.com/rindeal/gentoo-overlay/issues/33.

**Comment by chewi** [comment]
Oh sorry, I was unaware of that. I didn't think non-standard locales were that common? Did you propose that purely because of MakeMKV?

**Comment by rindeal** [comment]
> I didn't think non-standard locales were that common?

Actually, they're all standard, it's just some use different ISO standards than the others, so to keep the freedom of choice for developers, Gentoo should support any of them.

> Did you propose that purely because of MakeMKV?

Not purely, though the idea with the mapping was because of this issue with MakeMKV, the other enhancements are to make the eclass more useful and convenient to use, because the current state  looks more like a draft rather than an eclass ready to be used as widely as it is now.

**Pull request closed without merging**
