### PR TITLE
app-text/linuxdoc-tools: add missing dep on sys-devel/flex

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by Coacher** [comment]
^^Unrelated xapian problems.

**Comment by mgorny** [comment]
Please blame @blueness for them ;-). They're fixed now, and I'm going to take a look at your PR.

**Comment by mgorny** [comment]
Ok, it is trivial yet there is one more thing you need to do. Three quick points for you:

1. Since you are changing runtime dependencies (`RDEPEND` indirectly), you need to bump the revision of the package. Otherwise, users who already installed it may not get the update and keep missing flex.
2. The package has stable keywords, so normally you'd change them to ~arch when revbumping. However, we're talking about trivial dependency change and flex should be stable on all relevant arches, so you can keep them as-is. If you committed using repoman, you'd use `repoman commit -S` to allow stable keywords. If you committed without using repoman, remember to run `repoman full` after adding all files or after committing.
3. Since both revisions will have the same keywords, and there will be no real reason to downgrade to older revision, you should also drop the old revision when revbumping. Do it in the same commit, and git will easily figure out it's file move and show a nice diff.
4. Since you will be updating your commit anyway, you may want to rebase against fresh `origin/master`. This will kill those QA warnings (since they were fixed already), and also reduce the length of duplicated history.
5. If you're planning to stay longer, you may consider PGP-signing your commits (`git commit -S`). If you don't have a nice PGP key yet, I suggest looking at https://wiki.gentoo.org/wiki/Project:Gentoo-keys/Generating_GLEP_63_based_OpenPGP_keys.

1-3 needed to merge, 4-5 entirely optional ;-).

**Comment by Coacher** [comment]
Thank you for your feedback.

1,2,3. Users won't be able to build it without flex, so no revbump is needed here for missed runtime deps.
4. Done.

**Comment by Coacher** [comment]
5. What is the point of PGP-signing if I don't have the write access to the main repo anyway? My commit will be signed by the dev who merges my changes, no?

**Comment by mgorny** [comment]
Hmm, that's a fair point. However, a counter-argument would be that they could unmerge flex after building it (i.e. due to `emerge --depclean`), and I suspect that would break the package, wouldn't it? ;-)

As for PGP-signing, if I merge your pull request, the merge commit will be signed by me and the underlying commit will keep the original signature. That's pretty much the point beyond using merge commits. Sadly, I can't promise that some developer with poor git skills won't commit it before me :-(.

**Comment by mgorny** [comment]
Oh, and just to be clear, I'm not forcing you to revbump. I like that you think. I've given you one more point to consider, and it's up to you to decide if the revbump is desired or not. You know the risks, you know the gains ;-).

**Comment by Coacher** [comment]
>Hmm, that's a fair point. However, a counter-argument would be that they could unmerge flex after building it (i.e. due to emerge --depclean), and I suspect that would break the package, wouldn't it? ;-)

I agree, it would. I will note this for the future. However, I don't think accidental flex unmerge is possible because packages like gcc, binutils and xorg-server depend on it.

So, I say we don't need to revbump in this particular case. Please merge as is.

**Comment by Coacher** [comment]
Nice. Thanks.

**Pull request merged**
