### PR TITLE
net-libs/tox: add slot to the ebuilds

### PR DESCRIPTION
**Pull request by zetok**
As mentioned in the bug #601038

### CODE REVIEW

**Comment by gktrk** [comment]
why are we adding subslots? also  can you split the `EGIT_REPO_URI` change to a separate URI?

**Comment by zetok** [comment]
>why are we adding subslots?

Subslots seem like the right tool for handling API differences between versions.

>also can you split the `EGIT_REPO_URI` change to a separate URI?

Do you mean a separate commit?

**Comment by gktrk** [comment]
Sorry for the typo, I meant separate commits.

**Comment by zetok** [comment]
Reverted the change to `EGIT_REPO_URI`

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/cbd4886...0686d87. Thanks!

**Pull request closed without merging**
