### PR TITLE
dev-java/sbt-bin: new ebuild

### PR DESCRIPTION
**Pull request by mazgi**
I propose binary package for sbt.

I think that useful to reducing the build time.
How likely do you?

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/java

**Comment by monsieurp** [comment]
Thanks @mazgi for your PR. I left a couple of comments. Could you please apply these changes across all ebuilds? Also, commit messages have to respect this format: category/ebuild: message. In your case, the commit message must be changed to "dev-java/sbt-bin: Import ebuilds.". Thank you.

**Comment by chewi** [comment]
The sbt ebuild we have in the tree already has a binary USE flag.

**Comment by mazgi** [comment]
@monsieurp  @chewi Thank you for your advices.
I'll do it!

@chewi I want to provide the official sbt, including the files ( `bin/*`, `conf/*` ).
Will you let me know what you think about it?

**Comment by mazgi** [comment]
I did it :smiley:

**Comment by monsieurp** [comment]
Merged + I added the metadata.xml file. It's an important file so please don't forget it next time you send a PR. Thanks a lot for your work. Cheers.

**Comment by mazgi** [comment]
Good to know!
Thanks for your merge and many modified.
I think I've learned a lot.

**Pull request merged**
