### PR TITLE
net-misc/asterisk: Cleanup old versions.

### PR DESCRIPTION
**Pull request by jkroonza**
Signed-off-by: Jaco Kroon <jaco@uls.co.za>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
FYI we expect a CI check return positive result before reviewing. You should fix the issue caused.

**Comment by a17r** [comment]
Well, you can't drop the latest stable `13.36.0` - or in fact all stable versions as long as one stable revdep remains.

**Comment by a17r** [comment]
```
$ eshowkw asterisk
Keywords for net-misc/asterisk:
           |                             |   u   |  
           | a   a     p s     a   r     |   n   |  
           | m   r h   p p   s l i i m m | e u s | r
           | d a m p p c a x 3 p a s 6 i | a s l | e
           | 6 r 6 p p 6 r 8 9 h 6 c 8 p | p e o | p
           | 4 m 4 a c 4 c 6 0 a 4 v k s | i d t | o
-----------+-----------------------------+-------+-------
13.34.0    | + ~ ~ o ~ ~ o + o o o o o o | 7 # 0 | gentoo
13.35.0    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
13.36.0    | + ~ ~ o ~ ~ o + o o o o o o | 7 o   | gentoo
13.37.0    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
13.38.1    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
13.38.1-r1 | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
16.12.0-r1 | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
16.13.0    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
16.14.0    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
16.15.1    | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 #   | gentoo
16.15.1-r1 | ~ ~ ~ o ~ ~ o ~ o o o o o o | 7 o   | gentoo
```

Still the same problem, you can't drop 13.36.0 yet.

**Comment by jkroonza** [comment]
Aware, waiting for stabilization on https://bugs.gentoo.org/761313

In the meantime I guess I can push -r2 for sub slots.

**Comment by thesamesam** [comment]
Please rerun CI now that stabilisation is done

**Pull request closed without merging**
