### PR TITLE
lxde-base/lxterminal-0.2.0: add gtk3 use flag

### PR DESCRIPTION
**Pull request by khumarahn**
`lxde-base/lxterminal-0.2.0` can use gtk3 if `--enable-gtk3` is passed to `./configure`. This also makes use of `x11-libs/vte:2.90` instead of `x11-libs/vte:0` which is used for gtk2.

Using `x11-libs/vte:2.90` over `x11-libs/vte:0` has an advantage that the bug https://bugzilla.gnome.org/show_bug.cgi?id=542087 is fixed. This bug causes visual glitches in certain situations (see https://github.com/mobile-shell/mosh/issues/325 ).

### CODE REVIEW

**Comment by rindeal** [comment]
I suggest:
 - bump EAPI
 - use an array instead of breaking lines in `src_configure()`
 - move `DOCS` after `*DEPEND`

**Comment by khumarahn** [comment]
@rindeal, done! I did not do array for econf, but just wrote the whole thing on one line. There is just one argument anyway.

**Comment by rindeal** [comment]
Ok, thanks.

**Comment by monsieurp** [comment]
@jauhien

**Pull request closed without merging**
