### PR TITLE
ipython and matplotlib pypy3 support

### PR DESCRIPTION
**Pull request by tgbugs**
This PR includes all dependencies needed to run ipython on pypy3.

There are multiple build failures at the moment. This PR is being created so that there is a place to discuss specific issues related to the dependency tree.

The commits are not atomic at the moment but can be made so if needs be.

Closes: https://bugs.gentoo.org/729958

Supersedes:
https://github.com/gentoo/gentoo/pull/16466

### CODE REVIEW

**Comment by tgbugs** [comment]
Table with report on the status of individual packages for compile and test.

<table border="2" cellspacing="0" cellpadding="6" rules="groups" frame="hsides">


<colgroup>
<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />

<col  class="org-left" />
</colgroup>
<thead>
<tr>
<th scope="col" class="org-left">atom</th>
<th scope="col" class="org-left">compile</th>
<th scope="col" class="org-left">test</th>
<th scope="col" class="org-left">test-dep</th>
<th scope="col" class="org-left">notes</th>
</tr>
</thead>

<tbody>
<tr>
<td class="org-left">dev-python/PyQt-builder-1.12.2</td>
<td class="org-left">ok</td>
<td class="org-left">none</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/PyQt5-sip-12.11.0</td>
<td class="org-left">ok</td>
<td class="org-left">none</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/PyQt5-5.15.7</td>
<td class="org-left">fail</td>
<td class="org-left">?</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">oom</td>
</tr>


<tr>
<td class="org-left">dev-python/QtPy-2.3.0</td>
<td class="org-left">fail</td>
<td class="org-left">?</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">dep on fail</td>
</tr>


<tr>
<td class="org-left">dev-python/aiohttp-cors-0.7.0-r2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">dev-python/black</td>
<td class="org-left">wat</td>
</tr>


<tr>
<td class="org-left">dev-python/black-22.12.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/black-23.1.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/cchardet-2.1.7</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/cchardet-2.1.7-r1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/comm-0.1.2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/dictdiffer-0.9.0-r1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/fuzzywuzzy-0.18.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">via dev-python/sphobjinv</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/gmpy-2.1.5</td>
<td class="org-left">fail</td>
<td class="org-left">fail</td>
<td class="org-left">dev-python/twisted</td>
<td class="org-left">cpython api</td>
</tr>


<tr>
<td class="org-left">dev-python/ipykernel-6.20.2</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">qt test fails</td>
</tr>


<tr>
<td class="org-left">dev-python/ipykernel-6.21.2</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">qt test fails</td>
</tr>


<tr>
<td class="org-left">dev-python/ipython-8.8.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">audio tests fail</td>
</tr>


<tr>
<td class="org-left">dev-python/ipython-8.9.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">audio tests fail</td>
</tr>


<tr>
<td class="org-left">dev-python/ipython-8.10.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">audio tests fail</td>
</tr>


<tr>
<td class="org-left">dev-python/ipywidgets-8.0.4</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/jupyter_client-7.4.9</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/jupyter_client-8.0.2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/jupyter_client-8.0.3</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/jupyter_core-5.1.5</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/jupyter_core-5.2.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/matplotlib-3.6.1</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/matplotlib-3.6.2</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/matplotlib-3.6.3</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/matplotlib-3.7.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/mypy-0.991</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">via dev-python/nptyping</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/mypy-1.0.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">via dev-python/nptyping</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/mypy-1.0.1</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">via dev-python/nptyping</td>
<td class="org-left">multiple fails</td>
</tr>


<tr>
<td class="org-left">dev-python/nptyping-2.3.1</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">dev-python/sphinx-autodoc-typehints</td>
<td class="org-left">test_immutable</td>
</tr>


<tr>
<td class="org-left">dev-python/nptyping-2.5.0</td>
<td class="org-left">ok</td>
<td class="org-left">fail</td>
<td class="org-left">dev-python/sphinx-autodoc-typehints</td>
<td class="org-left">test_immutable</td>
</tr>


<tr>
<td class="org-left">dev-python/numpy-1.24.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/prometheus_client-0.16.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/prompt-toolkit-3.0.36</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/pydata-sphinx-theme-0.7.2-r1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/pytest-check-2.1.2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">yes</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/pytest-check-2.1.3</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">yes</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/pytest-check-2.1.4</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">yes</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/pytest_jupyter-0.6.2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">yes</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/qtconsole-5.4.0</td>
<td class="org-left">fail</td>
<td class="org-left">?</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">dep on fail</td>
</tr>


<tr>
<td class="org-left">dev-python/selenium-4.5.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">via aiohttp-cors/aiohttp-cors</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sip-4.19.25-r1</td>
<td class="org-left">ok</td>
<td class="org-left">none</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sip-6.7.5-r1</td>
<td class="org-left">ok</td>
<td class="org-left">none</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sphinx-autodoc-typehints-1.22</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sphinxcontrib-github-alt-1.2-r2</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sphinxcontrib-spelling-7.7.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sphinxcontrib-spelling-8.0.0</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/sphobjinv-2.3.1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">dev-python/sphinx-autodoc-typehints</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/stdio-mgr-1.0.1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/typeguard-2.13.3-r1</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">via dev-python/nptyping</td>
<td class="org-left">&#xa0;</td>
</tr>


<tr>
<td class="org-left">dev-python/widgetsnbextension-4.0.5</td>
<td class="org-left">ok</td>
<td class="org-left">ok</td>
<td class="org-left">&#xa0;</td>
<td class="org-left">&#xa0;</td>
</tr>
</tbody>
</table>

**Comment by mgorny** [comment]
This overlaps with #29636.

**Comment by tgbugs** [comment]
The out of memory error when building PyQt5 happens during what appears to be an implicit call to `__repr__` a `sipbuild.generator.specification.WrappedClass` instance.

**Comment by tgbugs** [comment]
re: overlap with https://github.com/gentoo/gentoo/pull/29636.

My ideal solution to the issue would be to fix the dependencies so that ipython does not depend on matplotlib unless a use flag is set.

This is what I do in my overlay https://github.com/tgbugs/tgbugs-overlay/blob/257f40ee24170b5b79e62d9e627b409dffd3b9a0/dev-python/ipython/ipython-8.5.0.ebuild#L19 where I added an explicit `matplotlib` use flag to the ipython ebuild, and fixed the matplotlib-inline ebuild to not depend on matplotlib since it is explicitly supposed to act as a stub and not pull in matploblib by default.

**Comment by tgbugs** [comment]
Proposal for way forward.
1. submit a new request for the packages where pypy3 tests are passing so that they can start being maintained in tree
2. a pull request to add `IUSE=matplotlib` to the ipython ebuild so that the matplotlib pypy3 support can be decoupled, (also because matplotlib is not a hard requirement, and there are many CI use cases where that dependency is not desireable)
3. a final pull request for the packages that currently have failing tests and other issues (e.g. pyqt5 memory issues due to some insanity in data class __repr__).

**Comment by AndrewAmmerlaan** [comment]
Closing since it seems the objective of this PR has been reached and it is now obsolete. Please re-open if this is not the case.

**Pull request closed without merging**
