### PR TITLE
sys-devel/llvm: removed implicit dependency on binutils

### PR DESCRIPTION
**Pull request by karlguy**
Binutils should be an implicit system dependency. No need to force llvm to pull it in.

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/prefix, do you need that binutils-apple dep there?

**Comment by grobian** [comment]
Only if there's a specific version requirement, else, we'd always have binutils-apple available.

**Comment by mgorny** [comment]
The ebuild in q has

>=sys-devel/binutils-apple-5.1

**Comment by mgorny** [comment]
Alternatively, i suppose we can replace the `||` with `kernel_Darwin?`.

**Comment by grobian** [comment]
kernel_Darwin, or elibc_Darwin conditional would be fine.

**Comment by karlguy** [comment]
@mgorny done

**Pull request closed without merging**
