### PR TITLE
dev-embedded/arduino: fix #610036 dead SRC_URI googlecode and new EAPI

### PR DESCRIPTION
**Pull request by madmartin**
- Bug https://bugs.gentoo.org/show_bug.cgi?id=610036
- changed SRC_URI from googlecode.com to github
- updated ebuild EAPI 4 -> 6

Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by monsieurp** [comment]
Please file another PR without the last two commits i.e. without merging master back into the branch.

**Comment by madmartin** [comment]
@monsieurp can you please explain why?

**Comment by monsieurp** [comment]
Hi. Merging the master branch back into a contribution is considered bad practice and messes up the whole thing altogether. I don't think it was intended, was it? As I said, file the exact same PR and leave it as is.

**Comment by madmartin** [comment]
@monsieurp yes, this was intended, because the qa-bot had tons of complains about things I have never touched. On my first PR I was told to exactly do that what you disliked - update branch from master and push again, which calmed the qa-bot.

**Pull request closed without merging**
