### PR TITLE
app-mobilephone/gammu: update to 1.36.8.

### PR DESCRIPTION
**Pull request by Elizafox**
Does what it says on the tin.

I am also taking charge of this package.

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
Right, while Elizafox will be proxy maintainer of this package, the issue of the previous contributor Andrey, from the original bug, need be addressed and dealt with. In brief, a number of fundamentals need be clarified which have been skipped over. Andrey warrants some recognition but has made it difficult by exchanging from the limitations of bugzilla, Remember, while restrictive, this arena and irx are merely options, not essential fora.

**Comment by idella** [comment]
time to get onto this agin

**Comment by Elizafox** [comment]
I don't want to do this anymore.

**Pull request closed without merging**
