### PR TITLE
app-editors/gedit: add python3_7 support

### PR DESCRIPTION
**Pull request by okias**
Compile and run tested.

Signed-off-by: David Heidelberg <david@ixit.cz>

### CODE REVIEW

**Comment by okias** [comment]
hello guys? please merge.

**Comment by okias** [comment]
can we please merge this oneliner which ad python 3.7 support?

**Comment by juippis** [comment]
The Gnome team is better at responding bugs. I think you should open one, then you can amend your git commit and link the PR and bug together by using `Closes: ` tag in message box.

Or join `#gentoo-desktop` and ping @leio until he says something :)
(@gyakovlev)

**Comment by juippis** [comment]
The Gnome team is better at responding bugs. I think you should open one, then you can amend your git commit and link the PR and bug together by using `Closes: ` tag in message box.

Or join `#gentoo-desktop` and ping @leio until he says something :)
(@gyakovlev)

**Comment by okias** [comment]
well, it's not in GX86 yet, but at least gnome-next has it, so I guess as it's ignored, I'll not rebase.

**Pull request closed without merging**
