### PR TITLE
sci-calculators/bc-gh: bump to 6.1.1

### PR DESCRIPTION
**Pull request by gavinhoward**
Signed-off-by: Gavin Howard <gavin@yzena.com>

### CODE REVIEW

**Review by juippis — APPROVED** [review]
```
 * QA Notice: Files built without respecting LDFLAGS have been detected
 *  Please include the following list of files in your report:
 * /usr/bin/bc-gh
 * QA Notice: Pre-stripped files found:
 * /usr/bin/bc-gh
```
You'll get a bug report about these, just FYI. When did these start to appear...?

**Comment by ionenwks** [comment]
Last version didn't have -s I can see, `-T` configure option is supposed to disable it but comparing with previous there's a few new `strip_bin=1` with predefined build stuff that I guess(?) are overriding it.

(note it respects LDFLAGS, but pre-stripping prevents the LDFLAGS check from working)

**Comment by gavinhoward** [comment]
I attempted to run the required checks before committing; I missed the fact that `pkgdev scan` is not done by default. Whoops.

I will have a PR with a fix.

**Comment by gavinhoward** [comment]
Oh, whoops, you already have a fix. Sigh...I've updated my local stuff to use the fix and will use that from now on.

My apologies.

**Comment by ionenwks** [comment]
> I attempted to run the required checks before committing; I missed the fact that `pkgdev scan` is not done by default. Whoops.

This one isn't from pkgcheck, it's qa emitted by portage and other qa scripts using `eqawarn` when emerging. You can always see it in the build.log, but if you want to reduce chances to miss it you can add this to your make.conf:
```
PORTAGE_ELOG_CLASSES="${PORTAGE_ELOG_CLASSES} qa"
```
So it'll repeat the message after emerging similarly to `elog` messages.

**Pull request closed without merging**
