### PR TITLE
media-gfx/imv: version bump to 2.1.0

### PR DESCRIPTION
**Pull request by Hummer12007**
Updated media-gfx/imv
@gentoo/proxy-maint

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
What you have not done is included in the commit msg is that you have set sys-apps/renameutils as a blocker also in the live ebuild, and dropped the now old 2.0.0.  These are fairly non fatal so I shll add these myself en route `$ git pram`, and take note for future reference. Also I will add the ref to the gentoo bug. Note I do this on the basis you are in fact familiar with git as a vcs and these are realtively minor.

**Comment by idella** [comment]
atm I cannot because I am getting a build failure

**Comment by idella** [comment]
These were dealt with in the channel and an edited improvement is planned

**Pull request closed without merging**
