### PR TITLE
games-strategy/endless-sky: new ebuild: endless-sky-0.8.11

### PR DESCRIPTION
**Pull request by tomboy-64**
Package-Manager: portage-2.2.26
RepoMan-Options: --ignore-arches

### CODE REVIEW

**Comment by tomboy-64** [comment]
@gentoo/proxy-maint
@gentoo/games

**Comment by tomboy-64** [comment]
@monsieurp better?

**Comment by monsieurp** [comment]
LGTM! :+1:

**Comment by idella** [comment]
flagged this for addition soon

**Comment by tomboy-64** [comment]
go ahead please
and one more to waste more time.

**Pull request merged**
