### PR TITLE
sci-physics/lhapdf: only depend on cython with python

### PR DESCRIPTION
**Pull request by APN-Pucky**
PR created by [pkgpr](https://github.com/APN-Pucky/pkgpr).

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
The keywording should be done via Keyword Request on bugs.gentoo.org: https://devmanual.gentoo.org/keywording/index.html

**Comment by APN-Pucky** [comment]
> The keywording should be done via Keyword Request on bugs.gentoo.org: https://devmanual.gentoo.org/keywording/index.html

I see, that's because I am still proxied.

**Comment by AndrewAmmerlaan** [comment]
> > The keywording should be done via Keyword Request on bugs.gentoo.org: https://devmanual.gentoo.org/keywording/index.html
> 
> I see, that's because I am still proxied.

No, it's because you're not on the Arch teams for those architectures (and neither am I, so I should also not add these keywords).

**Comment by APN-Pucky** [comment]
2024-09-25_12-04-34_sci

From that I understood it as I just need to test it on my arm64, arm and riscv pc's as comitter.
Regardless, I changed it to only the `python?` fix and will open the reports.

**Comment by AndrewAmmerlaan** [comment]
> 2024-09-25_12-04-34_sci
> 
> From that I understood it as I just need to test it on my arm64, arm and riscv pc's as comitter. Regardless, I changed it to only the `python?` fix and will open the reports.

As I understand it, different Arch Teams have different policies when it comes to adding that architecture as a keyword that supplement what is written in the devmanual here (and these policies are documented on the wiki page of that Arch Team). I'm actually not sure what the current policy is for arm(64) and riscv. I usually just file keywording requests, but that is also because I am only involved with amd64 and don't really use anything else. 

Because of my personal unfamiliarity with anything non-amd64 I am hesitant to merge in any non-amd64 keywords myself, even though I do trust that you have properly tested this on these architectures.

**Pull request closed without merging**
