### PR TITLE
sys-fs/cryfs: Version bump to 0.10.1

### PR DESCRIPTION
**Pull request by automorphism88**
Closes https://bugs.gentoo.org/678572

Note that the new version requires boost to be >=1.65.1, so that currently means boost-1.70.0 must be unmasked in order to upgrade.

### CODE REVIEW

**Comment by linxon** [comment]
I did not have time to apply the changes for this version as requested @a17r in https://github.com/gentoo/gentoo/pull/11646 PR
do you can replace/test this ebuild?

```bash
# Copyright 1999-2019 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=7

CMAKE_BUILD_TYPE=Release
PYTHON_COMPAT=( python{2_7,3_{5,6,7}} )

inherit cmake-utils flag-o-matic linux-info python-any-r1

DESCRIPTION="Encrypted FUSE filesystem that conceals metadata"
HOMEPAGE="https://www.cryfs.org/"

if [[ "${PV}" == *9999 ]] ; then
	inherit git-r3
	EGIT_REPO_URI="https://github.com/cryfs/cryfs"
else
	SRC_URI="https://github.com/cryfs/cryfs/releases/download/${PV}/${P}.tar.xz"
	KEYWORDS="~amd64 ~arm ~arm64 ~x86"
	S="${WORKDIR}"
fi

SLOT=0
IUSE="custom-optimization libressl test update-check"

LICENSE="LGPL-3 BSD-2 MIT"
# cryfs - LGPL-3
# scrypt - BSD-2
# spdlog - MIT

RDEPEND="
	>=dev-libs/boost-1.56:=
	>=dev-libs/crypto++-5.6.3:=
	net-misc/curl:=
	>=sys-fs/fuse-2.8.6:=
	!libressl? ( dev-libs/openssl:0= )
	libressl? ( dev-libs/libressl:= )"

DEPEND="${RDEPEND}
	${PYTHON_DEPS}"

pkg_setup() {
	local CONFIG_CHECK="~FUSE_FS"
	local WARNING_FUSE_FS="CONFIG_FUSE_FS is required for cryfs support."

	check_extra_config
}

src_prepare() {
	# remove tests that require internet access to comply with Gentoo policy
	sed \
		-e '/CurlHttpClientTest.cpp/d' \
		-e '/FakeHttpClientTest.cpp/d' \
		-i test/cpp-utils/CMakeLists.txt || die 'sed failed!'

	# remove non-applicable warning
	sed \
		-e '/WARNING! This is a debug build. Performance might be slow./d' \
		-i src/cryfs-cli/Cli.cpp || die 'sed failed!'

	cmake-utils_src_prepare
}

src_configure() {
	local mycmakeargs=(
		"-DBoost_USE_STATIC_LIBS=off"
		"-DCRYFS_UPDATE_CHECKS=$(usex update-check)"
		"-DBUILD_TESTING=$(usex test)"
	)

	use custom-optimization || append-flags -O3

	cmake-utils_src_configure
}

src_test() {
	local TMPDIR="${T}"
	local tests_failed

	addread /dev/fuse
	addwrite /dev/fuse

	for i in gitversion cpp-utils parallelaccessstore blockstore blobstore fspp cryfs cryfs-cli; do
		"${BUILD_DIR}"/test/${i}/${i}-test || tests_failed+=( "${i}" )
	done

	adddeny /dev/fuse

	if [[ -n ${tests_failed[@]} ]]; then
		eerror "The following tests failed:"
		eerror "${tests_failed[@]}"
		die "At least one test failed"
	fi
}

src_install() {
	# work around upstream issue with cmake not creating install target
	# in Makefile if we enable BUILD_TESTING
	dobin "${BUILD_DIR}/src/cryfs-cli/cryfs"

	gzip -cd "${BUILD_DIR}/doc/cryfs.1.gz" > "${T}/cryfs.1" || die
	doman "${T}/cryfs.1"

	einstalldocs
}

```

**Comment by automorphism88** [comment]
I have incorporated most of the changes into a revised version which I've now pushed to this branch.

I left the assignment of `CMAKE_BUILD_TYPE` as local to `src_configure` instead of globally at the top of the ebuild, because it works fine that way and there's no need for it to be global (IIRC, my original version of this ebuild did define it globally similarly to this, and it was made `local` in the process of editing it for approval).

I went ahead and dropped the `CMAKE_MAKEFILE_GENERATOR=emake` from the top of the ebuild even though I wasn't the one who originally put it there and I'm not sure why it was added. It does seem to work without it.

**Comment by automorphism88** [comment]
I also noticed that upstream is now bundling crypto++ (version 8.1, newer than we have in the portage tree) and the system crypto++ isn't used, so I removed crypto++ from `RDEPEND` and added its license (Boost-1.0) to `LICENSE` with comment.

**Comment by automorphism88** [comment]
The `CMAKE_MAKEFILE_GENERATOR=emake` does appear to be in fact necessary and removing it broke the ebuild. Not sure if that other ebuild in the above comment was ever tested, but I'm guessing not. I fixed the ebuild by restoring that line.

**Comment by automorphism88** [comment]
> ## Pull request CI report
> 
> _Report generated at_: 2019-05-13 16:21 UTC
> _Newest commit scanned_: [1a1da22](https://github.com/gentoo/gentoo/commit/1a1da22e5e59abfafad39ecfb0ca1b08910619ce)
> _Status_: x **broken**
> 
> New issues caused by PR:
> https://qa-reports.gentoo.org/output/gentoo-ci/fcd1edd/output.html#sys-fs/cryfs
> 
> Issues already there before the PR (double-check them):
> https://qa-reports.gentoo.org/output/gentoo-ci/fcd1edd/output.html#media-libs/mesa

This appears to just be because boost 1.70 is still masked.

**Comment by automorphism88** [comment]
`EAPI=7` also seems to cause problems. I have not yet figured out why but for now I've just reverted it back to `EAPI=6`.

**Comment by a17r** [comment]
What problem is there with EAPI-7?

**Comment by automorphism88** [comment]
> What problem is there with EAPI-7?

As I said, I have yet to figure out the exact cause, but the build fails with `EAPI=7` and succeeds with `EAPI=6`, with no other changes. So far all I have done is to experiment with adding/removing various changes between the ebuild in my original PR (which I tested thoroughly before opening the PR, and have not found any problems with) and the one in the comment above. In the course of those experiments, I discovered that `EAPI=7` and removing the `CMAKE_MAKEFILE_GENERATOR` declaration I mentioned above both independently cause the build to fail. 

The exact nature of the failure varies (from missing source files to linking errors, at various different points in the build) which seems to point to it breaking in multiple ways and `MAKEOPTS="-j4"` creating a race between multiple errors. I need to do some experiments with single-threaded builds to see what happens. I also haven't done things like look for differences between the working/broken Makefiles produced by cmake at this point. I've been focused on trying to figure out what was breaking things via trial and error and haven't yet had time to figure out why.

However, given the issues I've had with this ebuild in the past related to the interaction between the `cmake-utils` eclass and the upstream build system, and the need for multiple workarounds to make it work, I would guess it is probably related to that - even a small change in the behavior of `cmake-utils` would be likely to break something that is already fragile and held together with multiple hacks.

I'm not sure when I'll have a chance to look at this in more detail. Nor am I sure whether it will be easy or difficult to figure out the source of the problem, or to fix it. But considering EAPI 5 is still used in many ebuilds, it doesn't seem particularly urgent, when this ebuild works fine with EAPI 6.

**Comment by a17r** [comment]
I would argue there is not a lot of difference in cmake-utils.eclass going from EAPI-6 to 7, so fixing would be better than reverting to old EAPI. That we still have EAPI-5 consumers there (and the list keeps growing) makes me sad, but it's no excuse.

**Comment by a17r** [comment]
So as expected, code fails because of `BUILD_SHARED_LIBS=ON` as follows:

```
/usr/bin/x86_64-pc-linux-gnu-g++ -fPIC -O2 -march=amdfam10 -pipe -fomit-frame-pointer -O3 -Wl,-O1 -Wl,--as-needed -shared -Wl,-soname,libcryfs-cli.so -o libcryfs-cli.so CMakeFiles/cryfs-cli.dir/Cli.cpp.o CMakeFiles/cryfs-cli.dir/VersionChecker.cpp.o CMakeFiles/cryfs-cli.dir/CallAfterTimeout.cpp.o CMakeFiles/cryfs-cli.dir/Environment.cpp.o CMakeFiles/cryfs-cli.dir/program_options/utils.cpp.o CMakeFiles/cryfs-cli.dir/program_options/ProgramOptions.cpp.o CMakeFiles/cryfs-cli.dir/program_options/Parser.cpp.o -Wl,-rpath,/var/tmp/portage/sys-fs/cryfs-0.10.1/work/cryfs-0.10.1_build/vendor/cryptopp ../cryfs/libcryfs.a ../cpp-utils/libcpp-utils.a ../gitversion/libgitversion.a ../fspp/fuse/libfspp-fuse.a ../blobstore/libblobstore.a ../blockstore/libblockstore.a -lboost_program_options-mt ../fspp/fs_interface/libfspp-interface.a ../cpp-utils/libcpp-utils.a -lcurl -ldl ../../vendor/spdlog/libspdlog.a ../../vendor/cryptopp/libcryptopp.so -fopenmp -lgomp -lpthread -lboost_filesystem-mt -lboost_system-mt -lboost_thread-mt -lpthread -lboost_chrono-mt -lboost_date_time-mt -lboost_atomic-mt -lrt -lfuse 
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../cryfs/libcryfs.a(CryConfigFile.cpp.o): relocation R_X86_64_TPOFF32 against symbol `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../cryfs/libcryfs.a(CryDevice.cpp.o): relocation R_X86_64_TPOFF32 against symbol `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../cpp-utils/libcpp-utils.a(memory_nonwindows.cpp.o): relocation R_X86_64_TPOFF32 against symbol `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../fspp/fuse/libfspp-fuse.a(Fuse.cpp.o): relocation R_X86_64_TPOFF32 against symbol `_ZGVZN6spdlog7details2os9thread_idEvE3tid' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../cryfs/libcryfs.a(CryCipher.cpp.o): warning: relocation against `_ZTVN5cryfs22ConcreteInnerEncryptorIN8cpputils10AES256_CFBEEE' in read-only section `.text._ZNK17CryCipherInstanceIN8cpputils10AES256_CFBEE26createInnerConfigEncryptorERKNS0_13EncryptionKeyE[_ZNK17CryCipherInstanceIN8cpputils10AES256_CFBEE26createInnerConfigEncryptorERKNS0_13EncryptionKeyE]'
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: ../cryfs/libcryfs.a(CryConfigLoader.cpp.o): relocation R_X86_64_PC32 against symbol `_ZN3fmt8internal9BasicDataIvE6DIGITSE' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc/x86_64-pc-linux-gnu/8.2.0/../../../../x86_64-pc-linux-gnu/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
```

This is coming from the bundled libs that are apparently not build option safe.

**Comment by a17r** [comment]
> I also noticed that upstream is now bundling crypto++ (version 8.1, newer than we have in the portage tree) and the system crypto++ isn't used, so I removed crypto++ from `RDEPEND` and added its license (Boost-1.0) to `LICENSE` with comment.

Often the necessary version bump is only one report away ;)
https://bugs.gentoo.org/show_bug.cgi?id=686792

**Comment by mgorny** [comment]
Add this package to the big package.mask entry for boost revdeps.

**Pull request closed without merging**
