### PR TITLE
dev-games/aseprite: Bump to 1.1.4.1, drop old

### PR DESCRIPTION
**Pull request by winterheart**
New version 1.1.4.1, dropping failed 1.0.6 and 9999.
Added slot for virtual/jpeg:0 for 0.9.5-r1.

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by monsieurp** [comment]
Hello and thank you for the PR. This is a maintainer-needed package. Would you be willing to take over maintainership?

**Comment by winterheart** [comment]
Yes, what I should to do?

**Comment by monsieurp** [comment]
You need to make sure you have an account in our bug tracker https://bugs.gentoo.org/. Please file a bug and assign it to me. I will add your email address to the metadata.xml file, merge this PR and close the bug whilst at it.

**Comment by winterheart** [comment]
Here bug: https://bugs.gentoo.org/show_bug.cgi?id=580556

**Pull request closed without merging**
