### PR TITLE
sys-cluster/charliecloud: Initial commit.

### PR DESCRIPTION
**Pull request by olifre**
This packages an initial live ebuild.
Current upstream releases can not be sensibly packaged,
but the next release will be packaging-friendly.

Package-Manager: Portage-2.3.16, Repoman-2.3.6

### CODE REVIEW

**Comment by olifre** [comment]
Some extra information for the review:
- Tests can not work. Upstream's test suite is extremely complete, but makes use of kernel user namespaces, which currently appears to fail with Gentoo's sandbox. 
- Building documentation when `suid` is activated does not work (hence the `ewarn`). This is the case since during documentation, build binaries are called, and they expect to have the `suid` bit already set (and fail otherwise).

**Comment by olifre** [comment]
> Could you also provide an ebuild to install a release of the package in question? Thanks!

Ok - the problem with that is that there is no release yet which can be sensibly packaged. 
The first release which allows for packaging will be 0.2.3, which may be a few weeks / months in the future only. So I'll have to come back to this PR at a (significantly) later point only. 

Background info: Package does not use automake / cmake or any build system, but makefiles only. Releases <=0.2.2 do not implement distdir yet, and don't use suitable install and runtime locations. 
I've fixed that upstream, but the release is still pending. 

So that means we'll keep that open until I see a new release, and then I come back to it?

**Comment by monsieurp** [comment]
Alright. You can try to _cut_ a release yourself using a given commit from the repo. We also accept that sort of solution. Have a look at this ebuild if you want: https://gitweb.gentoo.org/repo/gentoo.git/tree/app-vim/vim2hs/vim2hs-0.1_p20171106.ebuild

**Comment by olifre** [comment]
> Alright. You can try to cut a release yourself using a given commit from the repo. We also accept that sort of solution.

Perfect - I was not aware this is accepted policy for such special cases!
I added `charliecloud-0.2.3_pre20171121.ebuild` to the PR, squashed and repushed.

**Pull request closed without merging**
