### PR TITLE
dev-util/serialtalk: Initial commit.

### PR DESCRIPTION
**Pull request by olifre**
This packages the released version 1.2
and adds a live-ebuild.

Gentoo-Bug: https://bugs.gentoo.org/582182

Package-Manager: portage-2.2.28

I hope the metadata.xml is correct.

### CODE REVIEW

**Comment by idella** [comment]
The metadata is fine. I shall fetch it and look closely at it in runtest now

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
This is a simple ebuild, passes all required, runtests fine, the ebuilds I found 1 minor flaw
- the eclass versionator is never used.

**Comment by olifre** [comment]
> This is a simple ebuild, passes all required, runtests fine, the ebuilds I found 1 minor flaw

Thanks! Yes, indeed - I can of course just remove that. 
Is it preferrable to add this change in a second commit to the PR, or should I squash it in and re-push into the PR with `--force` ?

**Comment by idella** [comment]
well, squash is optional. generally interactive edit of the commit, git pull --rebase (important) git force push

**Comment by olifre** [comment]
> well, squash is optional. but in this case yes. Generally interactive edit of the commit, git pull --rebase (important) git force push

Thanks - since forced push is not so often applicable and this is my first PR into gentoo, I thought I'd better ask. 
The updated commit is pushed now. Thanks!

**Comment by olifre** [comment]
As expected - I forgot the rebase :-(. 
Should be fixed now.

**Comment by olifre** [comment]
I do not understand - can somebody explain the errors to me?
As seen here: https://github.com/olifre/gentoo/commits/serialtalk
my branch is up to date, rebased onto gentoo/gentoo master, with the single commit added... Am I missing something?

**Comment by idella** [comment]
2 points. can you
1.  ${PF}.tar.gz"  ->  ${P}.tar.gz"
${P}.nnnnnn is the norm.

2. Can you also delete line 12. from the live ebuild.  Internal portage too9ld have difficulty with that

**Comment by olifre** [comment]
Both done - thanks for all the assistance, I'll make sure to keep everything in mind for any later PR!

**Pull request closed without merging**
