### PR TITLE
app-office/skrooge: Version bump

### PR DESCRIPTION
**Pull request by a17r**
~~Please note that I wasn't able to build app-office/skrooge with qt-5.4.2 and my only box having 5.5 is currently M.I.A. due to ncurses fun.~~

Current version is 2.1.1, identified gcc-4.8.5 as my previous build problem - with >=gcc-4.9.0 this version does build fine. ~~Not sure how to proceed.~~

### CODE REVIEW

**Comment by a17r** [comment]
OK, everything's fine building w/ qt-5.4.2 as well. Fixed (R)DEPENDs.

**Comment by mgorny** [comment]
@gentoo/kde

**Comment by a17r** [comment]
Currently waiting for 2.1.1 tarballs to arrive, tagged 47 hours ago.

**Comment by a17r** [comment]
Added active gcc check.

**Comment by a17r** [comment]
(wasn't me)

**Comment by kensington** [comment]
Thanks, merged. I kept 2.0.0 for now because it's not recommended to add and remove versions in the same commit, and it's nice to keep an earlier version for a bit just in case there's some horrible unforeseen breakage.

**Pull request closed without merging**
