### PR TITLE
net-im/slack: version bump to 4.28.182 and cleanup

### PR DESCRIPTION
**Pull request by SpiderX**

### CODE REVIEW

**Comment by SpiderX** [comment]
This is a binary package and its depends on deprecated packages:

```
$ ldd /usr/bin/slack | grep atk
        libatk-1.0.so.0 => /usr/lib64/libatk-1.0.so.0 (0x00007f5f5f6e8000)
        libatk-bridge-2.0.so.0 => /usr/lib64/libatk-bridge-2.0.so.0 (0x00007f5f5f6af000)

```

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Sorry, meant to say: It doesn't look like wayland is optional. Could you take another look? (Also would be wonderful if you rebased against master, since slack-4.23.0 has been moved)

**Comment by qpfiffer** [comment]
@juippis See [this bug report.](https://bugs.gentoo.org/858191)

It is likely that since this is an Electron app, `libwayland-client.so.0` is not needed for this to work on systems without Wayland. I'm not quite sure what the full fix here is, but it is likely that the same `--use-gl=desktop` cli arg would work for X11.

**Review by juippis — APPROVED** [review]
I think I agree with the resolution of that bug... I'll add the wayland dep in a separate commit. It's a binary package and clearly linking against wayland. I don't know if libGLESv2.so is used or not, since you should have that by your systems virtual/opengl but that's to be figured in a separate bug. I imagine you can just remove the bundled libGLESv2.so - but I don't know for sure! It could be slack has modified it to their needs.

**Comment by qpfiffer** [comment]
It does look slightly modified based on Electron `v21.0.1` vs. Slack `4.29.144` which uses the same Electron base:

```
λ:/opt/slack md5sum libGLESv2.so
c0b1730ca1dfb509c9622876eb7b770d  libGLESv2.so

λ:~/Downloads/electron_unzip md5sum libGLESv2.so
bc9a775d701c217f91bc770046155a24  libGLESv2.so
```

Interesting.

**Pull request closed without merging**
