### PR TITLE
app-text/{asciidoc,hunspell}: add myself as a maintainer

### PR DESCRIPTION
**Pull request by scardracs**
Asciidoc and hunspell are actually packages used for lots things in Linux (for eg: dracut, git, genfstab, just to call some of these). I'm gonna take them as maintainer (but I still think a dev would be a better option).

Signed-off-by: Marco Scardovi <mscardovi@icloud.com>

### CODE REVIEW

**Comment by ajakk** [comment]
Could you maybe fix some of their bugs, then?

**Comment by scardracs** [comment]
> Could you maybe fix some of their bugs, then?

Did I miss something? I've look over bgo but I don't see any bugs that need to be fixed asap

**Comment by ajakk** [comment]
> > Could you maybe fix some of their bugs, then?
> 
> Did I miss something? I've look over bgo but I don't see any bugs that need to be fixed asap

Well, a bug needing to be fix "asap" isn't a prerequisite to fixing it. I'm not why we should merge a PR of entirely non-functional commits.

**Comment by scardracs** [comment]
> > > Could you maybe fix some of their bugs, then?
> > 
> > 
> > Did I miss something? I've look over bgo but I don't see any bugs that need to be fixed asap
> 
> Well, a bug needing to be fix "asap" isn't a prerequisite to fixing it. I'm not why we should merge a PR of entirely non-functional commits.

Sorry if I haven't explained me enough well: I don't see any bug that require any particular attention for both asciidoc nor hunspell

**Comment by ajakk** [comment]
There seem to be a few:

https://bugs.gentoo.org/buglist.cgi?f1=short_desc&o1=anywords&query_format=advanced&resolution=---&v1=app-text%2Fhunspell%2Capp-text%2Fasciidoc

**Comment by scardracs** [comment]
> There seem to be a few:
> 
> https://bugs.gentoo.org/buglist.cgi?f1=short_desc&o1=anywords&query_format=advanced&resolution=---&v1=app-text%2Fhunspell%2Capp-text%2Fasciidoc

https://bugs.gentoo.org/705122: bug upstream, I can't fix by miself. Still open, it was proposed as fix on v10 (which is already out)
https://bugs.gentoo.org/834835: manpages are not present on pipy, if we want them we need to install the version from GH
https://bugs.gentoo.org/481618: I don't really understand what's the problem. The bug is old as universe and seems no one cared it at all. I'd close it and set as obsolete
https://bugs.gentoo.org/366763: even older. dblatex is not used since years and on ::gentoo is dead since long time
https://bugs.gentoo.org/866093: already dropped 1.7.0 on https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=65514e34b3955abc59013b1ca04f97fd7a101b55, we need the glsa

**Comment by ajakk** [comment]
So, at least one of those seems actionable?

**Comment by scardracs** [comment]
> So, at least one of those seems actionable?

wrt dblatex https://bugs.gentoo.org/366763#c18, https://bugs.gentoo.org/366763#c21

**Pull request closed without merging**
