### PR TITLE
net-im/telegram-desktop-bin: Version bump to 1.2.1 + Cleanup

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by henning-schild** [comment]
@NP-Hardass @gavv

**Comment by henning-schild** [comment]
updated the cleanup patch to close https://bugs.gentoo.org/618024

**Comment by NP-Hardass** [comment]
LGTM,  but needs the signoff of the proxy-maintainer @gavv before I can merge it.

**Comment by gavv** [comment]
Looks good to me too.

**Pull request closed without merging**
