### PR TITLE
app-forensics/sleuthkit: build without BSFIX, drop java-ant2

### PR DESCRIPTION
**Pull request by vaukai**
Closes: https://bugs.gentoo.org/811207

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog

**Comment by gktrk** [comment]
@vaukai I see that you have a tracker here: https://bugs.gentoo.org/853109 I looked at the other bugs in the tracker, including closed bugs. Does this CR fix https://bugs.gentoo.org/811207? There is no `Closes:` tag in the commit but I wanted to double check with you.

I also don't understand why this is better than inheriting `java-ant-2` ? Is it just a simplification of the ebuild that replaces BSFIX with `ANT_OPTS` and explicitly pulls in ant instead of the eclass doing it?

Also, I don't know if it matters but your change in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c8b8fbed07b0046e7251f3253a079a7f961c046a pulls in ant with the SLOT 0 but your change here does not. Is this intentional?

**Comment by vaukai** [comment]
> @vaukai I see that you have a tracker here: https://bugs.gentoo.org/853109 I looked at the other bugs in the tracker, including closed bugs. Does this CR fix https://bugs.gentoo.org/811207? There is no `Closes:` tag in the commit but I wanted to double check with you.

@gktrk that tracker is old and should be ckecked if any of its blockers can be reproduced. [bug 811207](https://bugs.gentoo.org/811207) should be closed as "obsolete" on removal of `sleuthkit-4.11.1-r2` .
> 
> I also don't understand why this is better than inheriting `java-ant-2` ? Is it just a simplification of the ebuild that replaces BSFIX with `ANT_OPTS` and explicitly pulls in ant instead of the eclass doing it?

`java-ant-2.eclass` will most probably go away as it depends on `javatoolkit` which is an undocumented blackbox. and the ebuilds are getting much clearer when eant is controlled by `ant` configuration options instead of doing that behind the stages by using eclass variables.


> 
> Also, I don't know if it matters but your change in https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c8b8fbed07b0046e7251f3253a079a7f961c046a pulls in ant with the SLOT 0 but your change here does not. Is this intentional?

thanks for pointing me here. just added that slot.

**Comment by vaukai** [comment]
@gktrk time for stabilization has come. will you pls be so kind as to add `cc-arches` to https://bugs.gentoo.org/938954

**Pull request closed without merging**
