### PR TITLE
net-im/qtox: bump version to v1.6.0 and remove outdated versions

### PR DESCRIPTION
**Pull request by zetok**

### CODE REVIEW

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
I think we may be missing a few deps here. Looks like there was a switch to libsodium: https://github.com/qTox/qTox/compare/v1.5.0...v1.6.0#diff-6a074c693ab3fcda2a48f60a4ef75bd5R102 and qtwidgets: https://github.com/qTox/qTox/compare/v1.5.0...v1.6.0#diff-c0cb3774560ba6d364d907e95052b8f2R23. This is also present in the scanelf output:

```
$ scanelf -n /var/tmp/portage/net-im/qtox-1.6.0/image/usr/bin/qtox 
 TYPE   NEEDED FILE 
ET_EXEC libtoxcore.so.0,libtoxav.so.0,libtoxencryptsave.so.0,libsodium.so.13,libopenal.so.1,libqrencode.so.3,libsqlcipher.so.0,libX11.so.6,libXss.so.1,libgtk-x11-2.0.so.0,libgdk-x11-2.0.so.0,libgio-2.0.so.0,libcairo.so.2,libgdk_pixbuf-2.0.so.0,libgobject-2.0.so.0,libglib-2.0.so.0,libavformat.so.56,libavdevice.so.56,libavcodec.so.56,libavutil.so.54,libswscale.so.3,libQt5Svg.so.5,libQt5Widgets.so.5,libQt5Gui.so.5,libQt5Network.so.5,libQt5Xml.so.5,libQt5Sql.so.5,libQt5Core.so.5,libpthread.so.0,libstdc++.so.6,libm.so.6,libc.so.6 /var/tmp/portage/net-im/qtox-1.6.0/image/usr/bin/qtox
```

Also, should we look into building docs in the ebuild? https://github.com/qTox/qTox/compare/v1.5.0...v1.6.0#diff-9817733373755d3a0323485486707313R23

**Comment by zetok** [comment]
>I think we may be missing a few deps here. Looks like there was a switch to libsodium: qTox/qTox@v1.5.0...v1.6.0#diff-6a074c693ab3fcda2a48f60a4ef75bd5R102 (…)

qTox depends on `net-libs/tox`, which already depends on `libsodium`, and that dependency is not going from `tox` away. Anyway, added an explicit dependency.

>(…) and qtwidgets: qTox/qTox@v1.5.0...v1.6.0#diff-c0cb3774560ba6d364d907e95052b8f2R23.

Err, there was no change to Qt deps for a very long time.. Regardless, good catch with `qtwidgets`. I've added it to this ebuild and I'll make a PR to add it to other ebuilds. Kinda surprising that for years no one complained about it missing :D 

>Also, should we look into building docs in the ebuild? qTox/qTox@v1.5.0...v1.6.0#diff-9817733373755d3a0323485486707313R23

Doxygen is used only for internal docs for people who want to develop qTox. When it comes to docs for users, there is `doc/user_manual_en.md`, but I have no idea how to get a markdown doc properly provided in Gentoo.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/d16f74e...840ede2. Thanks!

For the future, let's try to split bumps from removals with separate commits.

**Pull request closed without merging**
