### PR TITLE
sys-apps/portage: Add USE=gemato to enable rsync verification by default

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by zmedico** [comment]
I see the hook here:

https://github.com/mgorny/gemato/blob/master/utils/repo.postsync.d/00gemato

How will it behave if the local copy of pubring.gpg is really old?

**Comment by mgorny** [comment]
It will probably fail due to expired key. FWICS, you need to update that package every half a year or so.

**Comment by zmedico** [comment]
I can imagine that lots of people are going to see the expired key error. Is the message going to be helpful enough that they can easily figure out the correct course of action?

**Comment by mgorny** [comment]
I'm going to have to check that. I suppose they're going to see the standard gpg error message for expired key.

**Comment by mgorny** [comment]
That said, I suppose I can make the ebuild `>=` depend on new enough gentoo-keys version to avoid this.

**Comment by mgorny** [comment]
@zmedico, would that `>=` solution work for you?

**Comment by zmedico** [comment]
Do the new keys have no expiration? That sounds kind of odd.

**Comment by mgorny** [comment]
They do have expiration. I'm just thinking that forcing people to upgrade before upgrading Portage reduces the risk of immediate breakage.

**Comment by zmedico** [comment]
Experience shows that lots of people are going to see their keys expire. Maybe we can trigger a message to advise them that this problem is expected when the app-crypt/gentoo-keys package is out of date?

**Comment by grobian** [comment]
Perhaps this is backwards thinking, but if the key is installed by an ebuild, can't we then also put the key in the rsync tree itself?  That way, a --sync will ensure an uptodate key is available.

**Comment by mgorny** [comment]
> Perhaps this is backwards thinking, but if the key is installed by an ebuild, can't we then also put the key in the rsync tree itself? That way, a --sync will ensure an uptodate key is available.

This would mean that any attacker can replace the key at any time and make the whole tree look good instantly. The current system is not perfect but past bootstrap we're at least verifying state *(m+n)* with previous state *m*.

**Comment by mgorny** [comment]
> Experience shows that lots of people are going to see their keys expire. Maybe we can trigger a message to advise them that this problem is expected when the app-crypt/gentoo-keys package is out of date?

The question is: how? Since the postsync hook is the only link to gentoo-keys, gemato tool itself should not care about that file. I'd really like to avoid attempting to provide deep error parsing and passthrough, and even more to avoid grepping the output.

External documentation then?

**Comment by grobian** [comment]
The idea of a public key is that it can be public isn't it?  So the only check you need is to have a well known key ID that stuff is supposed to be signed with.  gpg --recv-key FOO would basically be the same thing (or ignoring an expired key for that matter).

yum IIRC presents you with a dialog that says to add a key (with all the fluff and url where to check) and/or update it.  Perhaps this would be something Portage could handle?

**Comment by mgorny** [comment]
This is really a topic that gkeys project was supposed to deal with.

**Comment by zmedico** [comment]
If it fails for any reason, it could show a https:// link to a wiki article that discusses solutions.

The gkeys stuff isn't 100% essential.

**Comment by mgorny** [comment]
I'm going to close this and open a new one since we have a new approach now.

**Pull request closed without merging**
