### PR TITLE
net-nntp/nzbget: bump to 17.0_pre1660 and minor metadata addition

### PR DESCRIPTION
**Pull request by sbraz**
Hi @swegener, can you look at this? I've only been able to test it on amd64, arm and x86.
The changes are detailed in the commits. Here is a diff to the previous ebuild:
```diff
--- nzbget-16.4.ebuild  2016-02-13 19:06:40.158464359 +0100
+++ nzbget-17.0_pre1660.ebuild  2016-03-20 16:42:32.589072417 +0100
@@ -2,54 +2,70 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
-EAPI=5
+EAPI=6
 
-inherit autotools eutils user
+inherit autotools eutils flag-o-matic user
 
-MY_P=${P/_pre/-testing-r}
+MY_PV=${PV/_pre/-r}
+MY_P=${PN}-${PV/_pre/-testing-r}
 
 DESCRIPTION="A command-line based binary newsgrapper supporting .nzb files"
 HOMEPAGE="http://nzbget.net/"
-SRC_URI="https://github.com/${PN}/${PN}/releases/download/v${PV}/${P}-src.tar.gz"
+SRC_URI="https://github.com/${PN}/${PN}/releases/download/v${MY_PV}/${MY_P}-src.tar.gz -> ${P}.tar.gz"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS="~amd64 ~ppc ~x86"
-IUSE="debug gnutls ncurses parcheck ssl zlib"
+KEYWORDS="~amd64 ~arm ~ppc ~x86"
+IUSE="debug gnutls ncurses parcheck ssl test zlib"
 
 RDEPEND="dev-libs/libxml2
        ncurses? ( sys-libs/ncurses:0 )
-       parcheck? (
-               app-arch/libpar2
-               dev-libs/libsigc++:2
-       )
        ssl? (
                gnutls? ( net-libs/gnutls )
-               !gnutls? ( dev-libs/openssl:0 )
+               !gnutls? ( dev-libs/openssl:0= )
        )
        zlib? ( sys-libs/zlib )"
-DEPEND="${RDEPEND}
-       virtual/pkgconfig"
-
+DEPEND="${RDEPEND}"
 DOCS=( ChangeLog README nzbget.conf )
 
-S=${WORKDIR}/${P/_pre*/-testing}
+S=${WORKDIR}/${PN}-${PV/_pre*/-testing}
 
-src_prepare() {
-       epatch "${FILESDIR}/${PN}-14.0_pre1145-tinfo.patch"
+# Fix linking for ncurses[tinfo]
+# https://github.com/nzbget/nzbget/issues/188
+# https://bugs.gentoo.org/527262
+
+# Add a missing autoconf macro
+# https://github.com/nzbget/nzbget/pull/189
+PATCHES=(
+       "${FILESDIR}/${PN}-17.0_pre1660-ncurses-tinfo.patch"
+       "${FILESDIR}/${PN}-17.0_pre1660-add-missing-macro.patch"
+)
+
+pkg_pretend() {
+       if [[ ${MERGE_TYPE} != binary ]] && ! test-flag-CXX -std=c++14; then
+               eerror "${P} requires a C++14-capable compiler. Your current compiler"
+               eerror "does not seem to support the -std=c++14 option. Please"
+               eerror "upgrade to gcc-4.9 or an equivalent version supporting C++14."
+               die "The currently active compiler does not support -std=c++14"
+       fi
+}
 
+src_prepare() {
+       default
        sed -i 's:^ScriptDir=.*:ScriptDir=/usr/share/nzbget/ppscripts:' nzbget.conf || die
 
-       sed \
+       sed -i \
                -e 's:^MainDir=.*:MainDir=/var/lib/nzbget:' \
                -e 's:^LockFile=.*:LockFile=/run/nzbget/nzbget.pid:' \
                -e 's:^LogFile=.*:LogFile=/var/log/nzbget/nzbget.log:' \
                -e 's:^WebDir=.*:WebDir=/usr/share/nzbget/webui:' \
                -e 's:^ConfigTemplate=.*:ConfigTemplate=/usr/share/nzbget/nzbget.conf:' \
                -e 's:^DaemonUsername=.*:DaemonUsername=nzbget:' \
-               "${S}"/nzbget.conf > "${S}"/nzbgetd.conf || die
+               nzbgetd.conf || die
 
-       sed -i "/^dist_doc_DATA/d" Makefile.am || die
+       # Don't install a duplicate README which causes make install to fail
+       # https://github.com/nzbget/nzbget/issues/135 
+       sed -i "\|^\tlib/par2/README|d" Makefile.am || die
 
        eautoreconf
 }
@@ -61,9 +77,14 @@
                $(use_enable parcheck) \
                $(use_enable ssl tls) \
                $(use_enable zlib gzip) \
+               $(use_enable test tests) \
                --with-tlslib=$(usex gnutls GnuTLS OpenSSL)
 }
 
+src_test() {
+       ./nzbget --tests || die "Tests failed"
+}
+
 src_install() {
        default
 

```

### CODE REVIEW

**Comment by sbraz** [comment]
Maybe fetching the missing macro / adding it with a patch is cleaner. Let me know what way is preferred.

**Comment by sbraz** [comment]
@peti Hi, as you can see we are running into problems with `AX_CXX_COMPILE_STDCXX` because it is not present in the latest release of autoconf-archive.
This macro would certainly be useful for other packages as well, do you plan on making a new release soon?

**Comment by peti** [comment]
I can release a new version later today if that would help. The archive is in a stable state, I just didn't get around to uploading a new version yet. Will do it in a little while.

**Comment by sbraz** [comment]
@peti Thank you, this will be useful indeed :)

**Comment by peti** [comment]
http://ftpmirror.gnu.org/autoconf-archive/autoconf-archive-2016.03.20.tar.xz is being picked up by the various mirrors as we speak. I'll post the announcement in a few hours.

**Comment by sbraz** [comment]
Thanks, we've already added it to Gentoo: https://github.com/gentoo/gentoo/commit/8f50a14519aebcf8b30f2f74d40d4bba338ef296

**Comment by swegener** [comment]
Your sed -i change to nzbgetd.conf doesn't work, because nzbgetd.conf doesn't exist in the tarball.
Could you update the m4 macro to match the upstream version that accepts gcc 4.9?

**Comment by sbraz** [comment]
```diff
--- nzbget-16.4.ebuild	2016-02-13 19:06:40.158464359 +0100
+++ nzbget-17.0_pre1660.ebuild	2016-03-23 23:13:15.015490253 +0100
@@ -2,42 +2,57 @@
 # Distributed under the terms of the GNU General Public License v2
 # $Id$
 
-EAPI=5
+EAPI=6
 
-inherit autotools eutils user
+inherit autotools eutils flag-o-matic user
 
-MY_P=${P/_pre/-testing-r}
+MY_PV=${PV/_pre/-r}
+MY_P=${PN}-${PV/_pre/-testing-r}
 
 DESCRIPTION="A command-line based binary newsgrapper supporting .nzb files"
 HOMEPAGE="http://nzbget.net/"
-SRC_URI="https://github.com/${PN}/${PN}/releases/download/v${PV}/${P}-src.tar.gz"
+SRC_URI="https://github.com/${PN}/${PN}/releases/download/v${MY_PV}/${MY_P}-src.tar.gz -> ${P}.tar.gz"
 
 LICENSE="GPL-2"
 SLOT="0"
-KEYWORDS="~amd64 ~ppc ~x86"
-IUSE="debug gnutls ncurses parcheck ssl zlib"
+KEYWORDS="~amd64 ~arm ~ppc ~x86"
+IUSE="debug gnutls ncurses parcheck ssl test zlib"
 
 RDEPEND="dev-libs/libxml2
 	ncurses? ( sys-libs/ncurses:0 )
-	parcheck? (
-		app-arch/libpar2
-		dev-libs/libsigc++:2
-	)
 	ssl? (
 		gnutls? ( net-libs/gnutls )
-		!gnutls? ( dev-libs/openssl:0 )
+		!gnutls? ( dev-libs/openssl:0= )
 	)
 	zlib? ( sys-libs/zlib )"
 DEPEND="${RDEPEND}
 	virtual/pkgconfig"
-
 DOCS=( ChangeLog README nzbget.conf )
 
-S=${WORKDIR}/${P/_pre*/-testing}
+S=${WORKDIR}/${PN}-${PV/_pre*/-testing}
 
-src_prepare() {
-	epatch "${FILESDIR}/${PN}-14.0_pre1145-tinfo.patch"
+# Fix linking for ncurses[tinfo]
+# https://github.com/nzbget/nzbget/issues/188
+# https://bugs.gentoo.org/527262
+
+# Add a missing autoconf macro
+# https://github.com/nzbget/nzbget/pull/189
+PATCHES=(
+	"${FILESDIR}/${PN}-14.0_pre1145-tinfo.patch"
+	"${FILESDIR}/${PN}-17.0_pre1660-add-missing-macro.patch"
+)
+
+pkg_pretend() {
+	if [[ ${MERGE_TYPE} != binary ]] && ! test-flag-CXX -std=c++14; then
+		eerror "${P} requires a C++14-capable compiler. Your current compiler"
+		eerror "does not seem to support the -std=c++14 option. Please"
+		eerror "upgrade to gcc-4.9 or an equivalent version supporting C++14."
+		die "The currently active compiler does not support -std=c++14"
+	fi
+}
 
+src_prepare() {
+	default
 	sed -i 's:^ScriptDir=.*:ScriptDir=/usr/share/nzbget/ppscripts:' nzbget.conf || die
 
 	sed \
@@ -47,9 +62,11 @@
 		-e 's:^WebDir=.*:WebDir=/usr/share/nzbget/webui:' \
 		-e 's:^ConfigTemplate=.*:ConfigTemplate=/usr/share/nzbget/nzbget.conf:' \
 		-e 's:^DaemonUsername=.*:DaemonUsername=nzbget:' \
-		"${S}"/nzbget.conf > "${S}"/nzbgetd.conf || die
+		nzbget.conf > nzbgetd.conf || die
 
-	sed -i "/^dist_doc_DATA/d" Makefile.am || die
+	# Don't install a duplicate README which causes make install to fail
+	# https://github.com/nzbget/nzbget/issues/135 
+	sed -i "\|^\tlib/par2/README|d" Makefile.am || die
 
 	eautoreconf
 }
@@ -61,9 +78,14 @@
 		$(use_enable parcheck) \
 		$(use_enable ssl tls) \
 		$(use_enable zlib gzip) \
+		$(use_enable test tests) \
 		--with-tlslib=$(usex gnutls GnuTLS OpenSSL)
 }
 
+src_test() {
+	./nzbget --tests || die "Tests failed"
+}
+
 src_install() {
 	default
 

```

**Comment by swegener** [comment]
The patch is too large, it contains changes to Makefile.in, aclocal.m4 and configure, which we don't need.

**Comment by sbraz** [comment]
@swegener I had just applied the patch from upstream: https://github.com/nzbget/nzbget/commit/1f83fb8a3969ea87b828556441fb4883810b3430
It's fixed now: I just edit configure.ac and add the macro. The patch is under 20k.

**Pull request merged**
