### PR TITLE
sys-kernel/ugrd: add 1.19.3, drop 1.19.2

### PR DESCRIPTION
**Pull request by desultory**
bump with some bug fixes for compressed kmods, and improved kmod masking.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
Thanks :+1: 

For the next time, could you please put the dropping of old versions in a separate commit? This is what we usually do because it makes reverting a bit easier if it would be required.

**Comment by desultory** [comment]
> Thanks 👍
> 
> For the next time, could you please put the dropping of old versions in a separate commit? This is what we usually do because it makes reverting a bit easier if it would be required.

So the first commit deletes the old ebuild and updates the manifest; the second adds the new ebuild and updates the manifest as well?

**Comment by AndrewAmmerlaan** [comment]
> > Thanks 👍
> > For the next time, could you please put the dropping of old versions in a separate commit? This is what we usually do because it makes reverting a bit easier if it would be required.
> 
> So the first commit deletes the old ebuild and updates the manifest; the second adds the new ebuild and updates the manifest as well?

The other way around. So first add a new version, updating the manifest, then drop old versions, updating the manifest again.

This makes the revert "clean" if we want to re-add the older version for whatever reason.

**Comment by desultory** [comment]
> > > Thanks 👍
> > > For the next time, could you please put the dropping of old versions in a separate commit? This is what we usually do because it makes reverting a bit easier if it would be required.
> > 
> > 
> > So the first commit deletes the old ebuild and updates the manifest; the second adds the new ebuild and updates the manifest as well?
> 
> The other way around. So first add a new version, updating the manifest, then drop old versions, updating the manifest again.
> 
> This makes the revert "clean" if we want to re-add the older version for whatever reason.

that makes sense, thanks for the explanation.

**Pull request closed without merging**
