### PR TITLE
net-libs/tox: strip vulnerable versions.

### PR DESCRIPTION
**Pull request by xWNgLWT0mQf**
This commit removes all versions older than 0.2.8 since they are
vulnerable to remote DDoS attacks. This commit also removes a local
use flag definition since it is deprecated in the newer versions.

Bug: https://bugs.gentoo.org/668264
Closes: https://bugs.gentoo.org/628530
Signed-off-by: Josiah Mullins <JoMull01@protonmail.com>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by mgorny** [comment]
It seems that you need to remove some toxic versions first. Please add a commit removing the appropriate versions first.

**Comment by mgorny** [comment]
I was waiting for CI results. I guess you didn't rebase?

**Comment by xWNgLWT0mQf** [comment]
No, I didn't. I didn't think it necessary since the change didn't effect this commit. Is it possible to restart the CI tests without a new commit or rebase?

**Comment by xWNgLWT0mQf** [comment]
If there isn't, should I close the pull request and then make a new pull request?

**Comment by mgorny** [comment]
It is but CI checks ::gentoo exactly as in commit, so it won't notice the other PR merged. Just rebase and `git push --force`.

**Comment by xWNgLWT0mQf** [comment]
Sorry about the title, I thought that I had rebased that. I will fix it.

**Comment by xWNgLWT0mQf** [comment]
How did it fail? I just rechecked, and toxic-0.8.0-r1 is not in the tree any more.

**Comment by mgorny** [comment]
You didn't rebase against newer state of ::gentoo.

**Comment by xWNgLWT0mQf** [comment]
Since the check has passed and the PR still hasn't been merged, I have to conclude that something is wrong. What do I need to do to make this PR meet standards?

**Pull request closed without merging**
