### PR TITLE
gui-apps/tuigreet: version bump and add myself as maintainer

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This is a simple version bump for `tuigreet`. Since it's maintainer-needed i'll also decided to take over it.

### CODE REVIEW

**Comment by DarkDefender** [comment]
Awesome!
Could you add this fix to the live and 0.8.0 ebuild?
https://bugs.gentoo.org/832445

**Comment by mm1ke** [comment]
> Awesome! Could you add this fix to the live and 0.8.0 ebuild? https://bugs.gentoo.org/832445

Hi, thanks for the hint. 
I've included your changes from the bug report. Should be fixed with 0.8.0 and 9999 then.

**Comment by DarkDefender** [comment]
I would do the version bump and then do a separate commit that integrates the patch.
This way you can have a `Closes: https://bugs.gentoo.org/832445` in the commit message to automatically close the bug report when the commit is merged.

Now it seems a bit weird that the addition is split into the bump commit and the EAPI commit.

**Comment by mm1ke** [comment]
@DarkDefender good point, i've updated the PR and made a separate commit for the fix.

**Comment by DarkDefender** [comment]
@mm1ke Thanks! Looks good to me now!

@thesamesam I guess it is ok to poke you about getting this merged?

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
