### PR TITLE
media-libs/opencv: 4.8.0-r1 drop broken protobuf patch

### PR DESCRIPTION
**Pull request by negril**
This might be the cause for runtime failures.
Bug: https://bugs.gentoo.org/916189

### CODE REVIEW

**Comment by a17r** [comment]
You can't do this without version bump. So `4.8.0-r2` is correct, for 4.8.1 just drop this change and cleanup -r0 in your other PR where you bump to 4.8.1-r1.

**Comment by negril** [comment]
I would want to do the 4.8.1-r1 bump first.

**Comment by a17r** [comment]
> I would want to do the 4.8.1-r1 bump first.

Then you need to fix that. I'm just saying you can't change 4.8.1 in here without revbumping as well, so rather than doing it, just drop the change and focus on 4.8.1-r1 in your other PR instead.

**Comment by a17r** [comment]
Note to potential merger: Depends on https://github.com/gentoo/gentoo/pull/34662 for being able to remove the patch.

**Comment by thesamesam** [comment]
https://github.com/gentoo/gentoo/pull/34662 is merged now.

Should we leave this one for now to see if ffe7db9fea449121418607737c320c312bebb7f9 was enough?

**Comment by thesamesam** [comment]
Ah, wait, it's another bug.

**Pull request closed without merging**
