### PR TITLE
games-sports/vdrift: Add live ebuild, remove outdated ebuilds

### PR DESCRIPTION
**Pull request by MatthiasCoppens**
The 2012 ebuilds don't build anymore. I asked upstream for a new release.
This live ebuild fetches the source from GitHub and the game data from SourceForge as explained right here:
https://github.com/VDrift/vdrift/blob/master/docs/Getting_the_development_version.md.

Package-Manager: Portage-3.0.4, Repoman-3.0.1
Signed-off-by: Matthias Coppens <coppens.matthias.abc@gmail.com>

### CODE REVIEW

**Comment by rossbridger** [comment]
Why name the live version 9999999 instead of 9999 as per the usual naming convention?

**Comment by MatthiasCoppens** [comment]
> Why do you name the live version 9999999 instead of 9999 as per the usual naming convention?

The versioning scheme uses the date of the release as the version, the previous version for example was `vdrift-20120722`.

**Comment by rossbridger** [comment]
But you also have deleted all the previous versions. I think the usual date related versioning scheme is something like vdrift-0_p20120722.

**Comment by MatthiasCoppens** [comment]
I'll change it to `-9999`. Once upstreams releases a new version we still can choose between `-YYYY.MM.DD` (like `youtube-dl`) or `-0_pYYYYMMDD`.

**Comment by scardracs** [comment]
Kind ping: this package has been dropped so please close that PR or decide to re-add it

**Comment by ionenwks** [comment]
Re-adding and modernizing is still something I'm keeping a note at which I don't know if/when I'll look at -- but guess there's no need to keep this old PR open with the package gone from the tree.

**Pull request closed without merging**
