### PR TITLE
app-emulation/cloud-init: add python 3.10

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://bugs.gentoo.org/829969

### CODE REVIEW

**Comment by t0b3** [comment]
@prometheanfire any comments on this PR?

**Review by holmanb — APPROVED** [review]
Upstream cloud-init [currently tests](https://github.com/canonical/cloud-init/blob/main/.travis.yml#L154) and [supports](https://cloudinit.readthedocs.io/en/latest/topics/contributing.html?highlight=3.6#python-support) Python versions 3.6 through 3.10, this looks good to me.

Unrelated: Since release 22.1 was released in February a version bump would also be appropriate (21.2 is multiple releases behind upstream), though I suspect that there might be patch conflicts as a couple of Gentoo patches got pushed upstream in the last release cycle.

**Comment by thesamesam** [comment]
@holmanb Thanks!

**Comment by t0b3** [comment]
superseeded by https://github.com/gentoo/gentoo/pull/24949

**Pull request closed without merging**
