### PR TITLE
sys-apps/s6-rc: New package

### PR DESCRIPTION
**Pull request by atlaua**
s6-rc is a service manager based on the sys-apps/s6 supervision suite.

https://bugs.gentoo.org/show_bug.cgi?id=576678 (aka pull request #996) needs to be fixed first before this can be merged.

### CODE REVIEW

**Comment by williamh** [comment]
@atlaua:
Do you want to continue proxy maintaining this once it is in the tree, or do you want me to maintain it since I maintain the scarnet software in the tree anyway?

**Comment by idella** [comment]
@williamh ty for your reply

**Comment by atlaua** [comment]
@williamh: I'd like to maintain s6-rc, but it'd of course make sense if you maintain it, too. Feel free to add yourself as a co-maintainer, replacing the proxy-maint project. The `<description>Proxied maintainer; set to assignee in all bugs</description>` block should probably be removed in that case.

Same goes for sys-apps/s6-linux-utils, sys-apps/s6-portable-utils (already in the tree) and sys-apps/s6-linux-init (#1001), of course.

**Comment by monsieurp** [comment]
@williamh @gentoo/proxy-maint

**Comment by williamh** [comment]
I need to do one more thing before I merge this and #1001.
I only have amd64 hardware, so I need to find out for sure if I can merge them with KEYWORDS="~amd64 ~x86" or if I need to drop the~x86.

**Comment by atlaua** [comment]
The skarnet tools work fine on x86, according to Laurent. Unfortunately I don't have any x86 hardware either, so I'm fine with dropping ~x86 if our distro policies require it.

**Comment by williamh** [comment]
The first commit on this pull request was accepted. However, I have major misgivings about the second one. Consider what would happen if you were using s6-rc and rebuilt with a different livedir on the same system. I suspect that would lead to major breakage.

I am closing this p/r, but feel free to comment if you think it should be re-opened.

**Comment by atlaua** [comment]
@williamh I'd prefer if the second commit were also merged. I'm personally using its functionality; being able to configure the default livedir is quite useful for me.

I don't really think the breakage caused by careless changes of S6RC_LIVEDIR would be "major", anyway. Sure, s6-rc invocations using the default livedir would fail until the system is rebooted, but that could easily be circumvented by invoking "s6-rc -l oldlivedir".

Also, how's this different from USE flags or other build configuration? Changing such settings without thinking about the consequences can break things; nevertheless our community has always opted to provide configurability where it makes sense.

**Comment by williamh** [comment]
You are correct that we provide for configurability where it makes sense. In this case, the default for livedir matches fhs, and we follow FHS unless there is a very good reason not to. Also, you mention the -l switch. This switch can be used at any point to point to a different livedir than the default if you need to for some reason. Making this default configurable at build time without a strong justification for doing so can cause more harm than good.

**Comment by atlaua** [comment]
Of course, you're right that I could simply use the -l option. So far,
I was to lazy to type "s6-rc -l mylivedir' or create an alias for it, so
I used the --livedir configure option. But I've just realized that I'll
need to create some aliases for the s6-rc commands anyway, so it's okay
by me if you don't merge the second commit.

**Comment by williamh** [comment]
I have replaced proxy-maint with myself as your co-maintainer in s6-portable-utils and s6-linux-utils.

**Pull request closed without merging**
