### PR TITLE
sys-kernel/rt-sources version bumps

### PR DESCRIPTION
**Pull request by lilrc**
The title and the commit messages says it all.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by perfinion** [comment]
@lilrc kernel sources are typically different from other packages in that it can take users a while to actually build and reboot into the new sources. It might be a better idea to just add the new bumps first without removing the old ones, then in a month or whatever drop all the old ones. (ie do a cp instead of mv, then in a month rm the old ones)

But that said, I dont know much about rt-sources and if bumps have always been like this then by all means continue. It looks like there hasnt been much activity since the git switch so I cant easily see what the policy was before. rt-sources probably isnt used on servers as much so rebooting to the new kernel is easier

thoughts?

**Comment by lilrc** [comment]
I see; those are valid points. I cannot recall if psomas did like you suggested or like I am doing now. Maybe this procedure can be accepted for now and I'll do as you suggested next time? If not I will redo my changes and open another PR. However, these packages has indeed not received much attention so I doubt anyone will complain about move-bumping, rather than copy-bumping.

**Comment by lilrc** [comment]
Oh, @perfinion, I forgot.

**Comment by perfinion** [comment]
yep sounds fine to me, was mainly just so you are aware. I'll merge this in as soon as I get time.

**Comment by perfinion** [comment]
@lilrc thanks the work on this :D 
Do you want me to add you as a proxied-maintainer for this package too?

**Comment by lilrc** [comment]
@perfinion, sure! Thanks!

**Comment by lilrc** [comment]
@perfinion, just to obviate any uncertanties; that was an affirmative answer to whether I want you to add me as proxy-maintainer. ;)

**Comment by perfinion** [comment]
@lilrc done :D 

commit a6a1c736c9eaf6f7a9ddb7d7edda8848364b0d98
Author: Jason Zaman <perfinion@g.o>
Date:   Fri Feb 26 21:47:33 2016

    sys-kernel/rt-sources: Add Karl Linden as Proxy Maintainer
    
    And move psomas down since he's been on devaway for a few years
    
    Package-Manager: portage-2.2.26

**Pull request merged**
