### PR TITLE
app-editors/vscode: fix permissions

### PR DESCRIPTION
**Pull request by Miezhiko**

### CODE REVIEW

**Comment by arthurzam** [comment]
This change affects existing user installs, so a revision bump is needed.
You can do it directly using `git mv ...`.

Also, I suspect this same change is needed for `app-editors/vscodium`

**Comment by AdelKS** [comment]
I cannot reproduce on my machine the issue this PR is fixing, although I am not against it.

I tried `vscode` on xorg/openbox/lxqt, and its wayland counterpart on Gnome: they started without problems. vscodium wayland on Gnome didn't want to launch but the issue seems to be different...

**Comment by Miezhiko** [comment]
@arthurzam pushed with `-r1`
@AdelKS I was able to reproduce it myself, later I've seen another user who wasn't able to start vscode because of this

**Comment by AdelKS** [comment]
Please remove the vscode ebuild 1.66.0, then do the same for vscodium :D

**Comment by Miezhiko** [comment]
@AdelKS done

**Review by arthurzam — APPROVED** [review]
@Miezhiko Great work - thank you 😄

**Pull request closed without merging**
