### PR TITLE
www-servers/nginx: add nginx-vod module

### PR DESCRIPTION
**Pull request by Tatsh**

### CODE REVIEW

**Comment by Tatsh** [comment]
This is updated for the latest versions of nginx. Also fixes other issues.

**Comment by ajakk** [comment]
Still interested in this? At a minimum we need a GCO signoff as gentoo-bot suggested.

**Comment by Tatsh** [comment]
> Still interested in this? 

Yes. I will fix this branch.

**Comment by Tatsh** [comment]
Fixed.

**Comment by ajakk** [comment]
Ping Whissi.

**Comment by ajakk** [comment]
ConiKost, @hydrapolic, you've touched nginx a bit lately, any opinion on this?

**Comment by ConiKost** [comment]
> ConiKost, @hydrapolic, you've touched nginx a bit lately, any opinion on this?

IMHO, looks good. But needs to be rebased to newest version and tested, as with 1.23.x some ABI changes happend.

**Comment by hydrapolic** [comment]
Looks like the others, so no objections there.

However the question is if it wouldn't be better to add modules as separate packages (ebuilds).

**Comment by ajakk** [comment]
> Looks like the others, so no objections there.
> 
> However the question is if it wouldn't be better to add modules as separate packages (ebuilds).

That would depend on https://github.com/gentoo/gentoo/pull/16053, I think?

**Comment by hydrapolic** [comment]
> > Looks like the others, so no objections there.
> > However the question is if it wouldn't be better to add modules as separate packages (ebuilds).
> 
> That would depend on #16053, I think?

Yes

**Comment by scardracs** [comment]
Ping, is that PR still valid? If so, would you mind rebasing on latest version which contains security fix?

**Comment by ConiKost** [comment]
Closing in favor of https://github.com/gentoo/gentoo/pull/36326

**Pull request closed without merging**
