### PR TITLE
sys-apps/apparmor: add Make.rules patch

### PR DESCRIPTION
**Pull request by reagentoo**
Prevent AppArmor parser errors
@kensington @mgorny Hi. Please review this PR.
I had some problems after update:
https://i.imgur.com/NlZkZ3T.png

Additional info:
https://bugs.archlinux.org/task/65847
https://gitlab.com/apparmor/apparmor/issues/74
https://gitlab.com/apparmor/apparmor/uploads/7823a72985e91c46f611cddee7ef4972/rules.patch

### CODE REVIEW

**Comment by reagentoo** [comment]
@kensington Are you going to review this PR?
@mgorny @a17r FYI

**Comment by kensington** [comment]
The patch here looks quite different to the one from upstream to address this problem. I did ask in the bug, but I haven't gotten a response yet. So, I can't approve a patch without any indication about what it's actually trying to do and why it differs from upstream.

**Comment by reagentoo** [comment]
> The patch here looks quite different to the one from upstream to address this problem. I did ask in the bug, but I haven't gotten a response yet. So, I can't approve a patch without any indication about what it's actually trying to do and why it differs from upstream.

This patch contains the minimum changes required for correct build.
Please look at the Arch's pkg:
https://git.archlinux.org/svntogit/packages.git/tree/trunk?h=packages/apparmor
https://git.archlinux.org/svntogit/packages.git/tree/trunk/apparmor-2.13.4-fix_make.patch?h=packages/apparmor

**Comment by kensington** [comment]
Thanks for the explanation. I've done some testing, and it looks like it's not backwards compatible with older/stable versions of make:
```../common//Make.rules:84: *** unterminated call to function 'shell': missing ')'.  Stop.```

**Comment by kensington** [comment]
This should be fixed in 3.0.0.

**Pull request closed without merging**
