### PR TITLE
python-utils-r1.eclass: Check for occluded packages before testing

### PR DESCRIPTION
**Pull request by mgorny**
Add a check for installed packages being occluded by the working directory when calling epytest and eunittest.  This is primarily meant to detect C extensions being missed.

### CODE REVIEW

**Review by arthurzam — APPROVED** [review]
I don't have full background knowledge to understand if the results are correct or not, but as long as we review it manually when used (`PYTHON_EXPERIMENTAL_QA=1`) I think this is great.
Just make sure we don't run tinderbox runs over it, for now.

**Review by thesamesam — APPROVED** [review]
Great idea, let's try it out.

**Review by ionenwks — APPROVED** [review]
lgtm, will enable locally too -- not that I maintain a whole lot of packages with extensions to have much to say here

fwiw it does trigger the message on dev-python/adblock (this has no pure python fallback and no tests are skipped), but that's because that rather than remove the whole directory it only removes `__init__.py` because a test looks for adblock.pyi in there -- that been enough to stop it from using that directory and fail horribly.

Ideally I should fix their layout to do what maturin upstream suggests (then no workaround nor rm -rf would be needed), but I never got to that.

**Comment by ionenwks** [comment]
> fwiw it does trigger the message on dev-python/adblock

(note I do consider this bit of a obscure case, so I could just change how it handles it rather than require changes here)

**Pull request closed without merging**
