### PR TITLE
acct-user/havp: remove unused variable

### PR DESCRIPTION
**Pull request by arkamar**
The `ACCT_HOME_USER` should have been `ACCT_USER_HOME` most probably, because pre-GLEP 81 ebuild used
```
   enewuser ${PN} -1 -1 /etc/${PN} ${PN}
```
However, no one complained about the default `/dev/null` home in last few years. I don't see any signs indicating why `/etc/havp` should be used. Therefore, it seems appropriate to remove the unused variable `ACCT_HOME_USER`.

### CODE REVIEW

**Review by ConiKost — CHANGES_REQUESTED** [review]
Change is fine for me, but please revbump and update to EAPI=8 please. Thanks!

**Comment by arkamar** [comment]
I have increased `EAPI` in both `acct-user` and `acct-group`.

**Comment by Flowdalic** [comment]
I don't see a reason to revbump. Am I missing something?

**Comment by thesamesam** [comment]
Yes, it'll change the behaviour of a binpkg.

**Comment by Flowdalic** [comment]
> Yes, it'll change the behaviour of a binpkg.

Thanks, but could you elaborate a bit more? What is the the behavioral change? And what is triggering it?

**Comment by thesamesam** [comment]
With a revbump:
* If you have a binpkg for havp-0-r0 and install it, you get one behaviour.
* If you have a binpkg for havp-0-r1 and install it, you get different behaviour.

Without a revbump:
* If you have a binpkg for havp-0-r0 and install it, you get one behaviour.
* If you build from "source" havp-0-r1 and install it, you get different behaviour.

It's unexpected to have observable changes without changing revision.

**Comment by Flowdalic** [comment]
> It's unexpected to have observable changes without changing revision.

Right, that is our very sensible rule for revbumps. But I don't see how this PR introduces observable changes, hence I asked about an explanation *what* the different behavior is. I am surely missing something and like to learn what that is.

**Comment by thesamesam** [comment]
Oh, in this case, nothing other than we want to refresh the EAPI and ebuild stored in vdb.

**Comment by arkamar** [comment]
I guess that `pkg_*` phases will be refreshed in vdb as well with up to date checks.

**Review by ConiKost — APPROVED** [review]

**Pull request closed without merging**
