### PR TITLE
dev-libs/device-atlas-api-c: remove stable keywords

### PR DESCRIPTION
**Pull request by mgorny**
The stable versions can no longer be fetched, and this is going to be a perpetual problem.

### CODE REVIEW

**Comment by mgorny** [comment]
Oops, wrong package.

**Comment by bjacquin** [comment]
@devnexen according to @mgorny comments, would you be able to find a way to make old releases available on the website ? Could you talk internally on this matter ?

**Comment by devnexen** [comment]
I ll do my best to uncover the 2.1.2 but on the website not going to happen.

**Comment by bjacquin** [comment]
@mgorny any objection to remove dev-libs/device-atlas-api-c from portage tree to keep consistency in haproxy stable release ?

**Comment by mgorny** [comment]
I don't understand. Do you want to remove the package completely?

**Comment by bjacquin** [comment]
Well, as you mentioned, the stable versions can no longer be fetched, and this is going to be a perpetual problem since only the latest version of the source code would be fetchable for a user. Also a stable version of haproxy cannot depend on a testing version of dev-libs/device-atlas-api-c. I don't mind keeping dev-libs/device-atlas-api-c a dependy of testing only version of haproxy

**Comment by mgorny** [comment]
The 'stable mask' included in this PR ensures that the USE flag is visible only to ~arch users, so stable haproxy users are not affected.

**Pull request closed without merging**
