### PR TITLE
dev-util/flawfinder: bump to 2.0.10

### PR DESCRIPTION
**Pull request by oxr463**
Signed-off-by: Lucas Ramage <ramage.lucas@protonmail.com>
Package-Manager: Portage-2.3.67, Repoman-2.3.14

### CODE REVIEW

**Comment by oxr463** [comment]
> When you don't test your packages, a puppy becomes sad.
> 
> ```
>  * python3_5: running distutils-r1_run_phase python_test
> make -j12 test 
> test_001 (text output)
> test_002 (HTML output)
> test_003 (CSV output)
> test_004 (single-line)
> test_005 (diff)
> test_006 (save/load hitlist)
> test_007 (setup.py sane)
> test_008 (diff hitlist)
> Traceback (most recent call last):
>   File "./flawfinder", line 2234, in <module>
>     sys.exit(flawfind())
>   File "./flawfinder", line 2227, in flawfind
>     show_final_results()
>   File "./flawfinder", line 2099, in show_final_results
>     diff_hitlist = pickle.load(diff_file)
>   File "/usr/lib64/python3.5/codecs.py", line 321, in decode
>     (result, consumed) = self._buffer_decode(data, self.errors, final)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0x80 in position 0: invalid start byte
> make: *** [makefile:187: test_008] Error 1
> make: *** Waiting for unfinished jobs....
> ```

I do test! I ran `FEATURES="test" ACCEPT_KEYWORDS="~amd64" emerge dev-util/flawfinder` in my Gentoo 17.1 LXC container. Maybe I need a better way to do it. :/

**Comment by oxr463** [comment]
```sh
FEATURES="test" ACCEPT_KEYWORDS="~amd64" PYTHON_TARGETS="python2_7 python3_5 python3_6 python3_7" emerge dev-util/flawfinder
```

**Comment by mgorny** [comment]
I can reproduce it with all py3 versions, also outside Portage (i.e. `tar -xf flawfinder*.tar; cd flawfinder*; make check`).

**Comment by mgorny** [comment]
I'll send a fix upstream.

**Comment by mgorny** [comment]
And done: https://sourceforge.net/p/flawfinder/patches/3/

Let's either wait and see if upstream makes a quick release, or add it as a patch.

**Comment by oxr463** [comment]
> And done: https://sourceforge.net/p/flawfinder/patches/3/
> 
> Let's either wait and see if upstream makes a quick release, or add it as a patch.

Sounds good to me. I'd prefer waiting on upstream as long as it doesn't take too long.

**Comment by mgorny** [comment]
Upstream made a release.

**Comment by oxr463** [comment]
I'll bump and test again.

**Comment by mgorny** [comment]
It seems that you haven't updated the commits.

**Comment by oxr463** [comment]
No, not yet.

**Pull request closed without merging**
