### PR TITLE
[media-gfx/blender] Version bump

### PR DESCRIPTION
**Pull request by DarkDefender**
There was a quick corrective release for 3.1.1 as some critical bugs made it into 3.1.1.

I also updated the partio ebuild so that OSL can be built with the non live version of it.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Could you re-do the partio bump? You're pushing a new version straight to stable and removing old stable, which is not preferable. You should just add a new version with ~keywords (`ekeyword ~all new-version.ebuild`) and leave the old version untouched.

**Comment by juippis** [comment]
Nevertheless, we have to walk through the standard procedure of stabilizing. We can fast-stabilize though, requesting it immediately after it's been pushed, and not wait for the "mandatory" 30 days.

**Comment by DarkDefender** [comment]
Keyworded the partio ebuild as requested.

**Comment by juippis** [comment]
Please just leave the old version as-is, don't touch it all. We'll handle the stabilization and removal afterwards.

**Comment by DarkDefender** [comment]
Done

**Review by juippis — COMMENTED** [review]
Thanks! Looking good, but I can't seem to install blender.
```
python3.10/site-packages/numpy/matrixlib/setup.py
CMake Error at source/creator/cmake_install.cmake:274 (file):
  file INSTALL cannot find "/usr/lib/python3.10/site-packages/Cython": No
  such file or directory.
Call Stack (most recent call first):
  cmake_install.cmake:51 (include)


FAILED: CMakeFiles/install.util
cd /var/tmp/portage/media-gfx/blender-3.1.2/work/blender-3.1.2_build && /usr/bin/cmake -P           cmake_install.cmake
ninja: build stopped: subcommand failed.
 * ERROR: media-gfx/blender-3.1.2::gentoo failed (install phase):
```

**Comment by DarkDefender** [comment]
That's weird. Numpy should pull in Cython so you should have it installed.
The ebuild works for me.

Perhaps your python slots have not propagated correctly?
IE the Blender build requires numpy with python3_10 which in turn should pull in cython with python3_10.
But maybe your cython are not installed into the 3.10 site-packages?

**Comment by juippis** [comment]
cython is a BDEPEND for numpy. So when using binpackages, like in this case, it won't get pulled. A perfect reason why we don't depend on indirect deps like this. If your package needs something, list it as a dependency. Don't trust that it'll get pulled "via the other deps" ;)

But I'll install cython, do test runs and merge if it fixes blender. Will add the BDEPEND on cython during merge.

**Comment by DarkDefender** [comment]
I think you misunderstand. Blender has a python plugin system that depends on numpy. Numpy has a cython hard dependency. During installation Blender makes sure that the numpy install is going to work correctly (otherwise plugins in blender will work weirdly), so it checks for Cython.

I don't see how using bin packages should require every package to list second hand dependencies for every package it depends on. That seems like an issue that binpackages.
In this case it seems like your binpackage might have installed numpy but not the dependencies of numpy (which means that numpy will probably not work correctly either).

**Comment by juippis** [comment]
The thing is, numpy lists cython as a build-time dependency. Not as runtime dependency. So if you've managed to build the package as a binpackage before, you won't pull the build-time dependencies anymore, only runtime-dependencies. Blender requires cython. Hence depend on cython.

**Comment by DarkDefender** [comment]
Ok, got it. Thanks for pointing this out and educating me about these things.

Is there any other build failures you get from using bin packaging?
So I'll have a list of packages to add.

You can try to compile the live version of Blender and run the automated tests to see if things are working correctly.
(The 3.1.2 ebuild will have a few test faliures that has been fixed already in master).

**Comment by DarkDefender** [comment]
Actually nevermind about the live ebuild. Seems like someone pushed a change to Cycles that only works with older TBB versions. -_-

**Review by juippis — APPROVED** [review]

**Comment by DarkDefender** [comment]
@juippis I'm confused. I guess we will do a follow up pull request for the build depend issue (that affects at least Cython)?

**Comment by juippis** [comment]
I added f253ee0122a5bdc78e81f27a9448b2e55f9e2536 which is purely a guess, would appreciate if you investigated it a bit more.

**Comment by DarkDefender** [comment]
@juippis I've done more research and it seems like this is more of a missing dependency.
If you look at the default available packages in the official Blender releases.
For example the latest build has these packages in the bundled python runtime (`3.2/python/lib/python3.10/site-packages/`):
```
certifi  charset_normalizer  Cython  idna  libextern_draco.so  numpy  requests  urllib3  zstandard
```
So Blender does bundle Cython per default. Also some of the default addons use Cython for certain things.
Therefore I think that we can probably say that the packages listed above is runtime dependencies of blender.

It seems like `certifi`, `urllib3` and friends are pulled in by requests as well.
However as you stated, it is probably best to list these are runtime deps so we don't have the implicit dependency pulls, right?

For draco, I have to look into that more as it is a library that is currently bundled with Blender to support saving compressed .gltf files. I will have to ask the glft developers why this is in there as some tests showed that the compressed gltf files didn't seem to be well supported in Unreal Engine for example. 

So to wrap this up:
Should I simply just add all of the python dependencies explicitly in the ebuild that has been listed above (except draco)?
Is that a solution you think is fine?

**Comment by juippis** [comment]
> 
> So to wrap this up: Should I simply just add all of the python dependencies explicitly in the ebuild that has been listed above (except draco)? Is that a solution you think is fine?

Yes, that sounds good.

**Pull request closed without merging**
