### PR TITLE
app-containers/docker-buildx: add 0.11.2; drop old

### PR DESCRIPTION
**Pull request by Kangie**

### CODE REVIEW

**Comment by Kangie** [comment]
I've done the last few bumps on this package - I'll reach out to the proxy maintainer and find out what's happening there; I'm happy to adopt it if orphaned.

**Comment by thesamesam** [comment]
maybe cherry-pick their commit instead first, then do yours on top?

**Comment by nabbi** [comment]
This package likely should be now be maintained by "containers" vs a "proxy-maintainer" as this shifted from a nice to have to a must have package in the tree. I'm fine with however you wish to merge the PR's together. Thank you

**Comment by thesamesam** [comment]
> 

That doesn't mean you can't co-maintain it, fwiw. But @juippis points out containers@ doesn't maintain packages at the moment anyway..

**Pull request closed without merging**
