### PR TITLE
media-sound/mpd: use upstream systemd user service

### PR DESCRIPTION
**Pull request by lukash**
Copying over the system service stopped working after upstream changes,
a user service file was provided instead.

https://bugs.musicpd.org/view.php?id=4608

### CODE REVIEW

**Comment by lukash** [comment]
Can this be merged? Or would you prefer no revbump so that you could see in the diff what's changed?

**Comment by SoapGentoo** [comment]
@lukash can you rebase, so the authoring date is recent? Then I'll merge it

**Comment by lukash** [comment]
@SoapGentoo sure, I'll do it in the evening or tomorrow. Thanks.

**Comment by lukash** [comment]
@SoapGentoo I've rebased it, but that didn't change the commit date. So I've amended that too, if that's what you meant. Should be good to go now.

**Comment by lukash** [comment]
@SoapGentoo nudge nudge :) I would be much less happy to rebase it again...

**Pull request closed without merging**
