### PR TITLE
app-admin/filebeat: bump to 5.1.1

### PR DESCRIPTION
**Pull request by hydrapolic**
Thank you! :)

### CODE REVIEW

**Comment by gktrk** [comment]
The tests fail for me:

```
>>> Test phase: app-admin/filebeat-5.1.1
make -j4 -l4   check
make -C libbeat check || exit 1; make -C packetbeat check || exit 1; make -C filebeat check || exit 1; make -C winlogbeat check || exit 1; make -C metricbeat check || exit 1; make -C heartbeat check || exit 1;
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/libbeat'
go vet github.com/elastic/beats/libbeat/...
warning: "github.com/elastic/beats/libbeat/..." matched no packages
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/libbeat'
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/packetbeat'
go vet github.com/elastic/beats/packetbeat/...
warning: "github.com/elastic/beats/packetbeat/..." matched no packages
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/packetbeat'
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/filebeat'
go vet github.com/elastic/beats/filebeat/...
warning: "github.com/elastic/beats/filebeat/..." matched no packages
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/filebeat'
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/winlogbeat'
go vet github.com/elastic/beats/winlogbeat/...
warning: "github.com/elastic/beats/winlogbeat/..." matched no packages
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/winlogbeat'
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/metricbeat'
warning: "github.com/elastic/beats/metricbeat/..." matched no packages
go vet 
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/metricbeat'
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/heartbeat'
go vet github.com/elastic/beats/heartbeat/...
warning: "github.com/elastic/beats/heartbeat/..." matched no packages
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/heartbeat'
# Validate that all updates were commited
make update
make[1]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats'
make -C libbeat collect
make[2]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/libbeat'
cat _meta/fields.common.yml > _meta/fields.generated.yml
cat processors/*/_meta/fields.yml >> _meta/fields.generated.yml
make[2]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/libbeat'
make -C packetbeat update || exit 1; make -C filebeat update || exit 1; make -C winlogbeat update || exit 1; make -C metricbeat update || exit 1; make -C heartbeat update || exit 1;
make[2]: Entering directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/packetbeat'
cat _meta/fields_base.yml > _meta/fields.yml
bash: virtualenv: command not found
../libbeat/scripts/Makefile:182: recipe for target 'python-env' failed
make[2]: *** [python-env] Error 127
make[2]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats/packetbeat'
Makefile:39: recipe for target 'update' failed
make[1]: *** [update] Error 1
make[1]: Leaving directory '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats'
Makefile:56: recipe for target 'check' failed
make: *** [check] Error 2
 * ERROR: app-admin/filebeat-5.1.1::gentoo failed (test phase):
 *   Make check failed. See above for details.
 * 
 * Call stack:
 *            ebuild.sh, line 115:  Called src_test
 *          environment, line 349:  Called default
 *   phase-functions.sh, line 805:  Called default_src_test
 *   phase-functions.sh, line 834:  Called __eapi0_src_test
 *     phase-helpers.sh, line 760:  Called die
 * The specific snippet of code:
 *   		$emake_cmd ${internal_opts} check || \
 *   			die "Make check failed. See above for details."
 * 
 * If you need support, post the output of `emerge --info '=app-admin/filebeat-5.1.1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=app-admin/filebeat-5.1.1::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/app-admin/filebeat-5.1.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/app-admin/filebeat-5.1.1/temp/environment'.
 * Working directory: '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats'
 * S: '/var/tmp/portage/app-admin/filebeat-5.1.1/work/src/github.com/elastic/beats'
```

**Comment by hydrapolic** [comment]
I've never run tests before, because the complete test suite needs docker/docker-compose. I've at least added a go vet check. Thanks for testing out.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/beef8ff...e898302. Thanks!

**Comment by hydrapolic** [comment]
Thanks

**Pull request closed without merging**
