### PR TITLE
app-text/wgetpaste: pull some stuff from upstream

### PR DESCRIPTION
**Pull request by xxc3nsoredxx**
See also: https://github.com/zlin/wgetpaste/pull/46 https://github.com/zlin/wgetpaste/pull/51

### CODE REVIEW

**Comment by xxc3nsoredxx** [comment]
I'm gonna add some more stuff.

**Comment by thesamesam** [comment]
@dlan17 the version you merged looks different?

**Comment by xxc3nsoredxx** [comment]
@dlan17 yeah, you didn't grab the stuff I added last night. Only the stuff pre-force-push

**Comment by dlan17** [comment]
@xxc3nsoredxx  I've fixed, revert old & pushed new. btw, I don't think the new revision should go to stable straightly, so I've dropped all keywords to unstable, please file a bug in b.g.o if you have valid reason (security?) for quick stabilization, otherwise go through normal procedure

**Comment by xxc3nsoredxx** [comment]
@dlan17 Coolio. I'm wondering whether it should be bumped to `-r5` in case anyone updated their system before your fix commits.

I think it was either @thesamesam or @ionenwks who said some time ago that, being just a bash script, pushing straight to stable should be OK. But it's fine, can just go through the normal process again.

**Pull request closed without merging**
