### PR TITLE
app-admin/chezmoi-bin: new package

### PR DESCRIPTION
**Pull request by pdemonaco**
Manage your dotfiles across multiple machines, securely.

Bug: https://bugs.gentoo.org/688190
Package-Manager: Portage-2.3.66, Repoman-2.3.11

### CODE REVIEW

**Comment by pdemonaco** [comment]
Ping! 

(It's not clear in the proxy-maint guide how to actually make a ping comment so I hope this works)

**Comment by pdemonaco** [comment]
None of these include chezmoi

**Comment by AndrewAmmerlaan** [comment]
Hi there,

Sometimes 'new package' PRs get snowed under by all the other ones (new packages are low priority compared to fixes to already existing packages). If you'd like to make this ebuild available to the Gentoo users anyway, might I suggest the [GURU overlay](https://wiki.gentoo.org/wiki/Project:GURU). This is an ebuild repository maintained collaboratively by Gentoo users. To gain access to the repository, simply create an "Access request" on bugs.gentoo.org.

**Comment by mjeveritt** [comment]
See also https://gitweb.gentoo.org/repo/proj/guru.git/commit/?id=14b3b3ceccdddd7bfad79f7e6d6ff1d62a3b1ab9

**Comment by ajakk** [comment]
Closing here in favor of the GURU version given proxy-maint doesn't add new leaf packages anymore. Thanks for your work on this!

**Pull request closed without merging**
