### PR TITLE
step down from proxied maintenance for app-editors/retext and deps

### PR DESCRIPTION
**Pull request by holgersson32644**
- app-editors/retext: Move to maintainer-needed
- dev-python/markups: Remove myself (and p.m.) as maintainer

### CODE REVIEW

**Comment by thesamesam** [comment]
Is everything okay?

**Comment by holgersson32644** [comment]
> Is everything okay?
Sure, but thanks for asking. Dropping retext is on my agenda for a long time as I don't use it anymore - just waited to get the current version stable first ;-)

**Comment by thesamesam** [comment]
> Is everything okay?
> Sure, but thanks for asking. Dropping retext is on my agenda for a long time as I don't use it anymore - just waited to get the current version stable first ;-)

No problem, just wanted to check! I’m away from terminal for the day but will merge if nobody else does when I can.

**Review by juippis — APPROVED** [review]
Could you send the "up for grabs" mail to gentoo-dev? Please let me know and I'll do it if you don't want.

**Comment by holgersson32644** [comment]
> Could you send the "up for grabs" mail to gentoo-dev? Please let me know and I'll do it if you don't want.

Already done: https://archives.gentoo.org/gentoo-dev/message/be9ffc14f9942e6276dc80047d794e39

**Pull request closed without merging**
