### PR TITLE
Replace sys-apps/hwids with sys-apps/hwdata

### PR DESCRIPTION
**Pull request by floppym**
See bug [717216](https://bugs.gentoo.org/717216).

### CODE REVIEW

**Comment by gyakovlev** [comment]
ack for **sys-apps/lsvpd**

**Comment by floppym** [comment]
cc @ZeroChaos-

**Comment by ZeroChaos-** [comment]
<voice="mars attacks">ACK ACK ACK ACK ACK</voice>

**Review by mattst88 — APPROVED** [review]
For gnome and x11, I approve.

**Pull request merged**
