### PR TITLE
dev-java/commons-logging: add 1.3.1

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Review by fordfrog — COMMENTED** [review]
you dropped the tests completely here?

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by vaukai** [comment]
> you dropped the tests completely for commons-logging?

that's what i did, yes. intention is to come back here after solving https://bugs.gentoo.org/921398. but this could take some time.
could you please proceed with some of:
- https://github.com/gentoo/gentoo/pull/35987
- https://github.com/gentoo/gentoo/pull/34180
- https://github.com/gentoo/gentoo/pull/35321,  if you agree
- https://github.com/gentoo/gentoo/pull/35979
- https://github.com/gentoo/gentoo/pull/35984
- https://github.com/gentoo/gentoo/pull/35946
- https://github.com/gentoo/gentoo/pull/35907
-

**Comment by fordfrog** [comment]
> > you dropped the tests completely for commons-logging?

can't we just use the patch mentioned in the bug?

> that's what i did, yes. intention is to come back here after solving https://bugs.gentoo.org/921398. but this could take some time. could you please proceed with some of:
> 
> * [java-vm-2.eclass: drop EAPI 6 | virtual/jdk: drop dev-java/icedtea-bin #35987](https://github.com/gentoo/gentoo/pull/35987)
> * [dev-java/caffeine: min java 11 #34180](https://github.com/gentoo/gentoo/pull/34180)
> * [profiles/package.mask: last rite dev-java/{gin,gwt,validation-api} #35321](https://github.com/gentoo/gentoo/pull/35321),  if you agree
> * [dev-java/antlr: java21.patch #35979](https://github.com/gentoo/gentoo/pull/35979)
> * [dev-java/antlr-tool: 3.5.3-java21.patch #35984](https://github.com/gentoo/gentoo/pull/35984)
> * [dev-java/jakarta-xml-soap-api: drop SecurityManager #35946](https://github.com/gentoo/gentoo/pull/35946)
> * [dev-java/jdbc-mysql: restrict to <dev-java/protobuf-java-3.26.0 #35907](https://github.com/gentoo/gentoo/pull/35907)

i'll try to review those over the weekend

**Comment by vaukai** [comment]
> can't we just use the patch mentioned in the bug?

one more thing to try, will check.

**Comment by fordfrog** [comment]
so now the list of prs is completely resolved.

**Comment by fordfrog** [comment]
so can you reintroduce the tests here? i guess only three packages are left to unblock openjdk-21 stabilization. i commented on the other two already, they're waiting for me, this one can have the tests back.

**Comment by vaukai** [comment]
> so can you reintroduce the tests here?

that will be one of my next activities, sure.

**Comment by fordfrog** [comment]
there is some stuff missing from the classpath:
```
>>> Test phase: dev-java/commons-logging-1.3.1
 * java-pkg_ensure-dep: The ebuild is attempting to use javax-servlet-api-2.5, which is not declared with a SLOT in DEPEND.
 * java-pkg_ensure-dep: The ebuild is attempting to use junit-4, which is not declared with a SLOT in DEPEND.
javac -source 1.8 -target 1.8 -d target/test-classes -encoding iso-8859-1 -classpath target/test-classes:commons-logging.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-servlet-api-4/lib/jakarta-servlet-api.jar:/usr/share/slf4j-api/lib/slf4j-api.jar @test_sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
warning: [options] source value 8 is obsolete and will be removed in a future release
warning: [options] target value 8 is obsolete and will be removed in a future release
warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
src/test/java/org/apache/commons/logging/impl/WeakHashtableTestCase.java:44: warning: 'yield' may become a restricted identifier in a future release
                    yield();
                    ^
  (to invoke a method called yield, qualify the yield with a receiver or type name)
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:23: error: cannot find symbol
import org.apache.commons.logging.impl.Log4jApiLogFactory;
                                      ^
  symbol:   class Log4jApiLogFactory
  location: package org.apache.commons.logging.impl
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:24: error: package org.apache.logging.log4j does not exist
import org.apache.logging.log4j.Level;
                               ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:25: error: package org.apache.logging.log4j does not exist
import org.apache.logging.log4j.Marker;
                               ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:26: error: package org.apache.logging.log4j does not exist
import org.apache.logging.log4j.MarkerManager;
                               ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:27: error: package org.apache.logging.log4j.core does not exist
import org.apache.logging.log4j.core.LogEvent;
                                    ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:28: error: package org.apache.logging.log4j.core does not exist
import org.apache.logging.log4j.core.LoggerContext;
                                    ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:29: error: package org.apache.logging.log4j.core.config does not exist
import org.apache.logging.log4j.core.config.Configuration;
                                           ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:30: error: package org.apache.logging.log4j.core.test.appender does not exist
import org.apache.logging.log4j.core.test.appender.ListAppender;
                                                  ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:31: error: package org.apache.logging.log4j.message does not exist
import org.apache.logging.log4j.message.ObjectMessage;
                                       ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:32: error: package org.apache.logging.log4j.message does not exist
import org.apache.logging.log4j.message.SimpleMessage;
                                       ^
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:41: error: cannot find symbol
    private static final Marker MARKER = MarkerManager.getMarker("COMMONS-LOGGING");
                         ^
  symbol:   class Marker
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                         ^
  symbol:   class Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:47: error: cannot find symbol
    private ListAppender appender;
            ^
  symbol:   class ListAppender
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:30: error: package ch.qos.logback.classic does not exist
import ch.qos.logback.classic.Level;
                             ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:31: error: package ch.qos.logback.classic does not exist
import ch.qos.logback.classic.Logger;
                             ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:32: error: package ch.qos.logback.classic does not exist
import ch.qos.logback.classic.LoggerContext;
                             ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:33: error: package ch.qos.logback.classic.spi does not exist
import ch.qos.logback.classic.spi.ILoggingEvent;
                                 ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:34: error: package ch.qos.logback.classic.spi does not exist
import ch.qos.logback.classic.spi.ThrowableProxy;
                                 ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:35: error: package ch.qos.logback.core.filter does not exist
import ch.qos.logback.core.filter.Filter;
                                 ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:36: error: package ch.qos.logback.core.read does not exist
import ch.qos.logback.core.read.ListAppender;
                               ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:37: error: package ch.qos.logback.core.spi does not exist
import ch.qos.logback.core.spi.FilterReply;
                              ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:46: error: cannot find symbol
    private static final Level[] levels = {Level.ERROR, // SLF4J has no FATAL level
                         ^
  symbol:   class Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:51: error: cannot find symbol
    private ListAppender<ILoggingEvent> appender;
            ^
  symbol:   class ListAppender
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:51: error: cannot find symbol
    private ListAppender<ILoggingEvent> appender;
                         ^
  symbol:   class ILoggingEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:41: error: cannot find symbol
    private static final Marker MARKER = MarkerManager.getMarker("COMMONS-LOGGING");
                                         ^
  symbol:   variable MarkerManager
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                           ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                        ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                                     ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                                                 ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                                                             ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:43: error: cannot find symbol
    private static final Level[] levels = {Level.FATAL, Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                                                                          ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:53: error: cannot find symbol
        final LoggerContext context = LoggerContext.getContext(false);
              ^
  symbol:   class LoggerContext
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:53: error: cannot find symbol
        final LoggerContext context = LoggerContext.getContext(false);
                                      ^
  symbol:   variable LoggerContext
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:54: error: cannot find symbol
        final Configuration config = context.getConfiguration();
              ^
  symbol:   class Configuration
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:60: error: cannot find symbol
        assertEquals(Log4jApiLogFactory.class, factory.getClass());
                     ^
  symbol:   class Log4jApiLogFactory
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:79: error: cannot find symbol
        final ObjectMessage expectedMessage = new ObjectMessage(OBJ);
              ^
  symbol:   class ObjectMessage
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:79: error: cannot find symbol
        final ObjectMessage expectedMessage = new ObjectMessage(OBJ);
                                                  ^
  symbol:   class ObjectMessage
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:80: error: cannot find symbol
        final List<LogEvent> events = appender.getEvents();
                   ^
  symbol:   class LogEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:84: error: cannot find symbol
                final LogEvent event = events.get(2 * lev + hasThrowable);
                      ^
  symbol:   class LogEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:105: error: cannot find symbol
        final List<LogEvent> events = appender.getEvents();
                   ^
  symbol:   class LogEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:107: error: cannot find symbol
        assertEquals("Correct message type.", new ObjectMessage(OBJ), events.get(0).getMessage());
                                                  ^
  symbol:   class ObjectMessage
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/log4j2/CallerInformationTestCase.java:108: error: cannot find symbol
        assertEquals("Correct message type.", new SimpleMessage(STRING), events.get(1).getMessage());
                                                  ^
  symbol:   class SimpleMessage
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/security/MockSecurityManager.java:28: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
public class MockSecurityManager extends SecurityManager {
                                         ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:70: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
    private SecurityManager oldSecMgr;
            ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:75: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
        oldSecMgr = System.getSecurityManager();
                          ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:82: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
        System.setSecurityManager(oldSecMgr);
              ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:99: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
        System.setSecurityManager(mySecurityManager);
              ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:125: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(null);
                  ^
src/test/java/org/apache/commons/logging/security/SecurityAllowedTestCase.java:139: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(oldSecMgr);
                  ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:75: warning: [removal] SecurityManager in java.lang has been deprecated and marked for removal
    private SecurityManager oldSecMgr;
            ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:98: warning: [removal] getSecurityManager() in System has been deprecated and marked for removal
        oldSecMgr = System.getSecurityManager();
                          ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:111: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
        System.setSecurityManager(oldSecMgr);
              ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:129: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
        System.setSecurityManager(mySecurityManager);
              ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:145: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(oldSecMgr);
                  ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:159: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(oldSecMgr);
                  ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:182: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
        System.setSecurityManager(mySecurityManager);
              ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:190: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(oldSecMgr);
                  ^
src/test/java/org/apache/commons/logging/security/SecurityForbiddenTestCase.java:196: warning: [removal] setSecurityManager(SecurityManager) in System has been deprecated and marked for removal
            System.setSecurityManager(oldSecMgr);
                  ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:46: error: cannot find symbol
    private static final Level[] levels = {Level.ERROR, // SLF4J has no FATAL level
                                           ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:47: error: cannot find symbol
            Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
            ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:47: error: cannot find symbol
            Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                         ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:47: error: cannot find symbol
            Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                     ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:47: error: cannot find symbol
            Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                 ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:47: error: cannot find symbol
            Level.ERROR, Level.WARN, Level.INFO, Level.DEBUG, Level.TRACE};
                                                              ^
  symbol:   variable Level
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:57: error: cannot find symbol
        final LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
              ^
  symbol:   class LoggerContext
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:57: error: cannot find symbol
        final LoggerContext context = (LoggerContext) LoggerFactory.getILoggerFactory();
                                       ^
  symbol:   class LoggerContext
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:58: error: cannot find symbol
        final Logger logger = context.getLogger(Logger.ROOT_LOGGER_NAME);
              ^
  symbol:   class Logger
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:58: error: cannot find symbol
        final Logger logger = context.getLogger(Logger.ROOT_LOGGER_NAME);
                                                ^
  symbol:   variable Logger
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:59: error: cannot find symbol
        appender = (ListAppender) logger.getAppender("LIST");
                    ^
  symbol:   class ListAppender
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:61: error: cannot find symbol
        appender.addFilter(new Filter<ILoggingEvent>() {
                               ^
  symbol:   class Filter
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:61: error: cannot find symbol
        appender.addFilter(new Filter<ILoggingEvent>() {
                                      ^
  symbol:   class ILoggingEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:63: error: cannot find symbol
            public FilterReply decide(final ILoggingEvent event) {
                                            ^
  symbol: class ILoggingEvent
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:63: error: cannot find symbol
            public FilterReply decide(final ILoggingEvent event) {
                   ^
  symbol: class FilterReply
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:62: error: method does not override or implement a method from a supertype
            @Override
            ^
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:66: error: cannot find symbol
                return FilterReply.NEUTRAL;
                       ^
  symbol: variable FilterReply
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:91: error: cannot find symbol
        final List<ILoggingEvent> events = new ArrayList<>(appender.list);
                   ^
  symbol:   class ILoggingEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:95: error: cannot find symbol
                final ILoggingEvent event = events.get(2 * lev + hasThrowable);
                      ^
  symbol:   class ILoggingEvent
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:106: error: cannot find symbol
                final ThrowableProxy throwableProxy = (ThrowableProxy) event.getThrowableProxy();
                      ^
  symbol:   class ThrowableProxy
  location: class CallerInformationTestCase
src/test/java/org/apache/commons/logging/slf4j/CallerInformationTestCase.java:106: error: cannot find symbol
                final ThrowableProxy throwableProxy = (ThrowableProxy) event.getThrowableProxy();
                                                       ^
  symbol:   class ThrowableProxy
  location: class CallerInformationTestCase
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
63 errors
21 warnings
 * ERROR: dev-java/commons-logging-1.3.1::gentoo failed (test phase):
 *   ejavac failed
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_test
 *   environment, line 2496:  Called java-pkg-simple_src_test
 *   environment, line 1027:  Called ejavac '-d' 'target/test-classes' '-encoding' 'iso-8859-1' '-classpath' 'target/test-classes:commons-logging.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-servlet-api-4/lib/jakarta-servlet-api.jar:/usr/share/slf4j-api/lib/slf4j-api.jar' '@test_sources.lst'
 *   environment, line  661:  Called die
 * The specific snippet of code:
 *       "${args[@]}" || die "ejavac failed"
 * 
 * If you need support, post the output of `emerge --info '=dev-java/commons-logging-1.3.1::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=dev-java/commons-logging-1.3.1::gentoo'`.
!!! When you file a bug report, please include the following information:
GENTOO_VM=openjdk-21  CLASSPATH="" JAVA_HOME="/usr/lib64/openjdk-21"
JAVACFLAGS="-source 1.8 -target 1.8" COMPILER=""
and of course, the output of emerge --info =commons-logging-1.3.1
 * The complete build log is located at '/var/tmp/portage/dev-java/commons-logging-1.3.1/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/dev-java/commons-logging-1.3.1/temp/environment'.
 * Working directory: '/var/tmp/portage/dev-java/commons-logging-1.3.1/work/commons-logging-1.3.1-src'
 * S: '/var/tmp/portage/dev-java/commons-logging-1.3.1/work/commons-logging-1.3.1-src'
```

**Comment by vaukai** [comment]
> there is some stuff missing from the classpath:

just fixed.

**Pull request closed without merging**
