### PR TITLE
app-crypt/{trousers,tpm2-tss,tpm2-abrmd}: Implement GLEP 81

### PR DESCRIPTION
**Pull request by salahcoronya**
All 3 packages create the 'tss' user, so this factors it out. (Not included is app-crypt/tpm-emulator, as its only EAPI 6, it hasn't had a release in at least 5 years, and only emulates TPM 1.2)

### CODE REVIEW

**Comment by orlitzky** [comment]
Does your `tss` user really need its home directory to be `/var/lib/tpm` for these packages to run, or is that just a convenient way to create the directory with the ownership and permissions that you want? If it's the latter, please leave its home directory at the default (`/dev/null`) and create the directory in the package that uses `/var/lib/tpm` instead. This will take an extra line or two, but avoids some problems that we noticed right after the GLEP was approved (see [bug 693964](https://bugs.gentoo.org/693964), which I am about to push to the devmanual myself if no one else will).

**Comment by salahcoronya** [comment]
I tested the packages and the tss user does NOT need `/var/lib/tpm` to be the home directory for these packages to run. I have therefore modified the acct-user/tss package to use the default directory. app-crypt/trousers does use the directory though, so i re-added the keepdir/fowners lines back to it. The other 2 packages don't care about it.

**Comment by orlitzky** [comment]
Thanks for going the extra mile!

**Comment by juippis** [comment]
Well, the crypto team looks a bit unresponsive here. I'm however a bit afraid to merge this as-is, and I'd require a revbump (and resetting trousers to ~keywords) with your modifications to these ebuilds.

**Comment by salahcoronya** [comment]
Done. I have rebased, revbump'd all packages touched, reset trousers to ~arch, and fixed all problem detected by CI.

**Pull request closed without merging**
