### PR TITLE
dev-ruby/rails:5.2 add USE_RUBY=ruby27 support

### PR DESCRIPTION
**Pull request by winterheart**
dev-ruby/rails:5.2 required by www-apps/redmine which stuck in ruby26 due unmet dependencies on ruby27 target.

List of packages:

dev-ruby/arel/arel-9.0.0.ebuild
dev-ruby/actioncable/actioncable-5.2.8.ebuild
dev-ruby/actionmailer/actionmailer-5.2.8.ebuild
dev-ruby/actionpack/actionpack-5.2.8.ebuild
dev-ruby/actionview/actionview-5.2.8.ebuild
dev-ruby/activejob/activejob-5.2.8.ebuild
dev-ruby/activemodel/activemodel-5.2.8.ebuild
dev-ruby/activerecord/activerecord-5.2.8.ebuild
dev-ruby/activestorage/activestorage-5.2.8.ebuild
dev-ruby/rails/rails-5.2.8.ebuild
dev-ruby/railties/railties-5.2.8.ebuild

### CODE REVIEW

**Comment by thesamesam** [comment]
Per my comment on the bug, do you get tests passing for these?

**Comment by graaff** [comment]
Tests don't pass for me at the moment. They also fail with ruby26 so I guess this is a generic problem, but it needs to be addressed before we can add these ruby targets.

**Comment by thesamesam** [comment]
Will do, thank you! (Reason I just mentioned "graaff said" in the bug was b/c I hadn't tried myself in ages, so had no specifics to review to, wasn't doubting they failed fwiw, but it read a bit unclearly)

**Comment by graaff** [comment]
Due to security bug https://bugs.gentoo.org/857840 I have added 5.2.8.1 today and also added the ruby27 target. Thanks for doing the work on this PR.

**Pull request closed without merging**
