### PR TITLE
dev-lang/rust: Fix build with musl 1.2.4

### PR DESCRIPTION
**Pull request by vimproved**
Rust 1.72.0 bumped the version of the libc crate required by the std to 0.2.146, which finally means that the stdlib no longer references LFS64 symbols. This commit make rust 1.72.0 bootstrap from 1.72.0, and adds a patch that bumps all remaining dependencies on libc <0.2.146 in vendored crates.

### CODE REVIEW

**Comment by vimproved** [comment]
Pinging @xen0n since he's been doing a lot of rust work while gyakovlev is away.

**Comment by orbea** [comment]
@vimproved You might want to link this to the Gentoo issue. https://bugs.gentoo.org/903607

**Comment by vimproved** [comment]
Any clue what's going on with the CI?

**Comment by orbea** [comment]
> Any clue what's going on with the CI? pkgcheck isn't giving me anything...
```
ConflictingChksums	distfile 'rust-1.72.0-arm-unknown-linux-gnueabihf.tar.xz' has different checksums (blake2b, sha512, size) for package: dev-lang/rust
```
I ran into it when applying your fix locally, my workaround was to remove `rust-1.72.0-arm-unknown-linux-gnueabihf.tar.xz*` from `/var/cache/distfiles` and the corresponding lines from the `Manifest` file, then regenerated the Manifest with `pkgdev manifest`.

I have also run into similar in the past with older rust versions for other bootstrap tarballs, maybe upstream is modifying these files after release?

**Comment by vimproved** [comment]
> > Any clue what's going on with the CI? pkgcheck isn't giving me anything...
> 
> ```
> ConflictingChksums	distfile 'rust-1.72.0-arm-unknown-linux-gnueabihf.tar.xz' has different checksums (blake2b, sha512, size) for package: dev-lang/rust
> ```
> 
> I ran into it when applying your fix locally, my workaround was to remove `rust-1.72.0-arm-unknown-linux-gnueabihf.tar.xz*` from `/var/cache/distfiles` and the corresponding lines from the `Manifest` file, then regenerated the Manifest with `pkgdev manifest`.
> 
> I have also run into similar in the past with older rust versions for other bootstrap tarballs, maybe upstream is modifying these files after release?

Must have only partially downloaded. I think I fixed it.

**Comment by svmhdvn** [comment]
Any progress on this PR? I'm running into these build issues in the musl+clang system profile.

**Comment by vimproved** [comment]
> Any progress on this PR? I'm running into these build issues in the musl+clang system profile.

This has been ready on my end for a while, although it appears that it needs to be rebased.

**Review by xen0n — APPROVED** [review]
Ah, I've never noticed before that this only touches `dev-lang/rust` and nothing else. Should be good to go (we can always fix later should anything go wrong), sorry for the long delay!

**Pull request closed without merging**
