### PR TITLE
Apply libquicktime-1.2.4-ffmpeg29.patch when building libquicktime-12.4 against >=media-video/libav-12

### PR DESCRIPTION
**Pull request by Peter-Levine**
Adds libquicktime-1.2.4-r2.ebuild based on libquicktime-1.2.4-r1.ebuild.

Changes `has_version '>=media-video/ffmpeg-2.9' && epatch "${FILESDIR}"/${P}-ffmpeg29.patch` to 
`has_version '>=media-video/ffmpeg-2.9' || has_version '>=media-video/libav-12' && epatch "${FILESDIR}"/${P}-ffmpeg29.patch`

See https://bugs.gentoo.org/show_bug.cgi?id=609186

### CODE REVIEW

**Comment by aballier** [comment]
why the revbump ? it seems to be a build fix.

**Comment by Peter-Levine** [comment]
> why the revbump ? it seems to be a build fix.

@aballier You're right.  Should be OK now.

**Comment by aballier** [comment]
Hmm, no, please squash the two commits

**Comment by Peter-Levine** [comment]
@aballier Sorry.  Not much experience with git beyond 'clone', 'pull' and 'push'.
Here: https://github.com/gentoo/gentoo/pull/3974

**Pull request closed without merging**
