### PR TITLE
media-sound/gnome-music: Version bump to 44.0, media-libs/grilo, media-plugins/grilo-plugins: Version bump to 0.3.15-r1

### PR DESCRIPTION
**Pull request by flint2**
Keep it masked or do not merge, libsoup issue still present at runtime

/usr/bin/gnome-music

(org.gnome.Music:328788): libsoup-ERROR **: 20:22:59.609: libsoup3 symbols detected. Using libsoup2 and libsoup3 in the same process is not supported.
zsh: trace trap (core dumped)  /usr/bin/gnome-music

Additionally 1 test failed
2/2 Validate appdata file        FAIL            0.01s   exit status 1
>>> MALLOC_PERTURB_=233 /usr/bin/appstream-util validate-relax /var/tmp/portage/media-sound/gnome-music-44_rc/work/gnome-music-44_rc-build/data/org.gnome.Music.appdata.xml
(process:37): dconf-WARNING **: 20:27:51.614: Unable to open /root/.local/share/flatpak/exports/share/dconf/profile/user: Permission denied
Validation of files failed

### CODE REVIEW

**Comment by mattst88** [comment]
I think libsoup:2.4 is being pulled in by

````
	>=media-libs/grilo-0.3.13:0.3[introspection]
	>=media-plugins/grilo-plugins-0.3.13:0.3
````

grilo has a soup 2.4 vs 3.0 configuration option. We should revbump grilo and switch to libsoup 3.0, but then packages like `media-sound/pragha` depend on grilo and libsoup-2.4 /o\

Adding a libsoup-3.0 grilo would be good though. I think gnome-photos needs it too.

**Comment by mattst88** [comment]
(gnome-photos PR is here: https://github.com/gentoo/gentoo/pull/29989)

**Comment by flint2** [comment]
> I think libsoup:2.4 is being pulled in by
> 
> ```
> 	>=media-libs/grilo-0.3.13:0.3[introspection]
> 	>=media-plugins/grilo-plugins-0.3.13:0.3
> ```
> 
> grilo has a soup 2.4 vs 3.0 configuration option. We should revbump grilo and switch to libsoup 3.0, but then packages like `media-sound/pragha` depend on grilo and libsoup-2.4 /o\
> 
> Adding a libsoup-3.0 grilo would be good though. I think gnome-photos needs it too.

Added libsoup-3.0 grilo via soup3 USE flag , this way music 44 can use it, let me know if is better to use a slotted grilo 
opensubtitles and youtube plugins depend on libsoup-2.4, so are disabled it if soup3 USE

Now Music opens ok

**Comment by flint2** [comment]
gnome-music 44.0 released

**Comment by mattst88** [comment]
I suggest that we have

- `media-libs/grilo-0.3.15-r300` for `libsoup:3.0`
- `media-plugins/grilo-plugins-0.3.15-r300` for `libsoup:3.0`

rather than a `soup3` USE flag. We'll need to update reverse dependencies to depend on either < -r300 or >= -r300 depending on whether they're ready for libsoup:3.0. Awful :(

I think we also need to package `net-libs/libdmapsharing:4.0` (version 3.9.11 appears to be the latest) for this effort, since it supports libsoup:3.0.

Reverse dependencies of `media-libs/grilo` and `media-plugins/grilo-plugins` are:

### `media-gfx/gnome-photos`

Unfortunately there's nothing of value in https://github.com/gentoo/gentoo/pull/29989 but here's the comment I left:

> I believe the problem is net-misc/gnome-online-miners which depends on net-libs/libzapojit, net-libs/libgfbgraph, and dev-libs/libgdata which all depend on libsoup:2.4. But... gnome-online-miners is in RDEPEND only, so on second though I'm not 100% sure that will mean gnome-photos will load both libsoup versions into the same process.

Honestly at this point I'm ready to nuke gnome-photos and never think about this again.

- `media-sound/gnome-music`

This PR.

### `media-sound/pragha`

Still stuck on libsoup:2.4. No activity upstream. Maybe treeclean eventually? Cc: @gentoo/xfce

Will need to depend on grilo < -r300.

### `media-sound/rhythmbox`

There's an upstream issue here (https://gitlab.gnome.org/GNOME/rhythmbox/-/issues/1996) for porting to libsoup:3.0 and a patch, but Fedora has chosen to simply disable the functionality that depends on grilo (see https://bugzilla.redhat.com/show_bug.cgi?id=2169171)

For us that means we should package.use.mask rhythmbox's `USE=upnp-av` flag.

### `media-video/totem`

I don't see any other dependencies that depend on libsoup:3.0, so I think there's nothing to do here.

### `net-misc/gnome-online-miners`

Only a dependency of gnome-photos (and one that needs to be investigated—I think it just uses some binaries from it and doesn't link with it). I'd love to see this go away with gnome-photos as well.

**Comment by mattst88** [comment]
Yeah, thinking about it more, I think I'm just going to mask the following packages for removal:

- `net-libs/libgfbgraph` (only revdeps are gnome-online-miners and gnome-photos; stuck on libsoup:2.4, see https://gitlab.gnome.org/GNOME/libgfbgraph/-/merge_requests/6#note_1539288)
- `net-libs/libzapojit` (Archived upstream; stuck on libsoup:2.4; only revdep is gnome-online-miners)
- `net-misc/gnome-online-miners` (Archived upstream, only revdep is gnome-photos)
- `sci-geosciences/geocode-glib:0` (only revdep is gnome-photos; libsoup:2.4 slot)
- And `media-gfx/gnome-photos` if it can't work without these packages

**Comment by mattst88** [comment]
> I suggest that we have
>
> -    media-libs/grilo-0.3.15-r300 for libsoup:3.0
> -    media-plugins/grilo-plugins-0.3.15-r300 for libsoup:3.0
>
> rather than a soup3 USE flag. We'll need to update reverse dependencies to depend on either < -r300 or >= -r300 depending on whether they're ready for libsoup:3.0. Awful :(

On second thought, that wouldn't be good once 0.3.16 is released. Maybe the USE flag is for the best.

**Comment by flint2** [comment]
> > I suggest that we have
> > 
> > * media-libs/grilo-0.3.15-r300 for libsoup:3.0
> > * media-plugins/grilo-plugins-0.3.15-r300 for libsoup:3.0
> > 
> > rather than a soup3 USE flag. We'll need to update reverse dependencies to depend on either < -r300 or >= -r300 depending on whether they're ready for libsoup:3.0. Awful :(
> 
> On second thought, that wouldn't be good once 0.3.16 is released. Maybe the USE flag is for the best.

Should we continue the effort on music and photos or let it go the flatpak way?

**Comment by mattst88** [comment]
I guess let's actually just mask `USE=soup` on `media-sound/pragha`, and add grilo -r1 with a hard-switchover to libsoup:3.0.

I'll figure out what to do about gnome-photos and rhythmbox.

**Comment by mattst88** [comment]
Well, I gave it a try. grilo and grilo-plugins are a mess, and I don't feel like applying 10+ patches (see https://gitlab.gnome.org/GNOME/grilo/-/issues/151). So I'm going to put this on the backburner for now. What a fucking mess. :(

FWIW, here are some fixups I made in this attempt:

## grilo-plugins

````
commit d5c6386c115af8983a0af781a8e41574e32874a6
Author: Matt Turner <mattst88@gentoo.org>
Date:   Wed Mar 29 23:07:09 2023 -0400

    fixup! media-plugins/grilo-plugins: Version bump to 0.3.15-r1

diff --git a/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild b/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
index 00dce3721de8..6a78f8eb6528 100644
--- a/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
+++ b/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
@@ -11,7 +11,7 @@ HOMEPAGE="https://wiki.gnome.org/Projects/Grilo"
 LICENSE="LGPL-2.1+"
 SLOT="0.3"
 KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86"
-IUSE="daap chromaprint flickr freebox gnome-online-accounts lua soup3 test thetvdb tracker upnp-av +youtube"
+IUSE="daap chromaprint flickr freebox gnome-online-accounts lua +soup3 test thetvdb tracker upnp-av +youtube"
 RESTRICT="!test? ( test )"
 REQUIRED_USE="
 	lua? ( ${LUA_REQUIRED_USE} )
@@ -23,7 +23,7 @@ REQUIRED_USE="
 # TODO: validate upnp-av dleyna deps
 RDEPEND="
 	>=dev-libs/glib-2.66:2
-	>=media-libs/grilo-0.3.13:${SLOT}=[playlist]
+	>=media-libs/grilo-0.3.13:${SLOT}=[playlist,soup3(-)=]
 	freebox? ( net-dns/avahi[dbus] )
 	>=dev-libs/gom-0.4
 	chromaprint? (
@@ -32,7 +32,7 @@ RDEPEND="
 		media-plugins/gst-plugins-chromaprint:1.0
 	)
 	dev-libs/json-glib
-	daap? ( >=net-libs/libdmapsharing-2.9.12:3.0 )
+	daap? ( >=net-libs/libdmapsharing-3.9.11:4.0 )
 	media-libs/libmediaart:2.0
 	soup3? (  net-libs/libsoup:3.0 )
 	!soup3? ( net-libs/libsoup:2.4 )
@@ -44,10 +44,7 @@ RDEPEND="
 	dev-db/sqlite:3
 	>=dev-libs/totem-pl-parser-3.4.1:=
 	tracker? ( app-misc/tracker:3= )
-	upnp-av? (
-		net-libs/dleyna-connector-dbus
-		net-misc/dleyna-server
-	)
+	upnp-av? ( net-libs/dleyna:1.0= )
 	lua? (
 		${LUA_DEPS}
 		app-arch/libarchive
````

## grilo

````
commit ad584576b5335523e8cd499e10c6747b49a48606
Author: Matt Turner <mattst88@gentoo.org>
Date:   Wed Mar 29 22:49:18 2023 -0400

    fixup! media-libs/grilo: Version bump to 0.3.15-r1

diff --git a/media-libs/grilo/grilo-0.3.15-r1.ebuild b/media-libs/grilo/grilo-0.3.15-r1.ebuild
index 75a91b30e98a..4a8830bdf569 100644
--- a/media-libs/grilo/grilo-0.3.15-r1.ebuild
+++ b/media-libs/grilo/grilo-0.3.15-r1.ebuild
@@ -13,7 +13,7 @@ LICENSE="LGPL-2.1+"
 SLOT="0.3/0" # subslot is libgrilo-0.3 soname suffix
 KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86"
 
-IUSE="gtk gtk-doc +introspection +playlist soup3 test vala"
+IUSE="gtk gtk-doc +introspection +playlist +soup3 test vala"
 REQUIRED_USE="vala? ( introspection )"
 RESTRICT="!test? ( test )"
````

We'll also need to mask grilo-plugins' IUSE=youtube.

**Comment by flint2** [comment]
> Well, I gave it a try. grilo and grilo-plugins are a mess, and I don't feel like applying 10+ patches (see https://gitlab.gnome.org/GNOME/grilo/-/issues/151). So I'm going to put this on the backburner for now. What a fucking mess. :(
> 
> FWIW, here are some fixups I made in this attempt:
> ## grilo-plugins
> 
> ```
> commit d5c6386c115af8983a0af781a8e41574e32874a6
> Author: Matt Turner <mattst88@gentoo.org>
> Date:   Wed Mar 29 23:07:09 2023 -0400
> 
>     fixup! media-plugins/grilo-plugins: Version bump to 0.3.15-r1
> 
> diff --git a/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild b/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
> index 00dce3721de8..6a78f8eb6528 100644
> --- a/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
> +++ b/media-plugins/grilo-plugins/grilo-plugins-0.3.15-r1.ebuild
> @@ -11,7 +11,7 @@ HOMEPAGE="https://wiki.gnome.org/Projects/Grilo"
>  LICENSE="LGPL-2.1+"
>  SLOT="0.3"
>  KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86"
> -IUSE="daap chromaprint flickr freebox gnome-online-accounts lua soup3 test thetvdb tracker upnp-av +youtube"
> +IUSE="daap chromaprint flickr freebox gnome-online-accounts lua +soup3 test thetvdb tracker upnp-av +youtube"
>  RESTRICT="!test? ( test )"
>  REQUIRED_USE="
>  	lua? ( ${LUA_REQUIRED_USE} )
> @@ -23,7 +23,7 @@ REQUIRED_USE="
>  # TODO: validate upnp-av dleyna deps
>  RDEPEND="
>  	>=dev-libs/glib-2.66:2
> -	>=media-libs/grilo-0.3.13:${SLOT}=[playlist]
> +	>=media-libs/grilo-0.3.13:${SLOT}=[playlist,soup3(-)=]
>  	freebox? ( net-dns/avahi[dbus] )
>  	>=dev-libs/gom-0.4
>  	chromaprint? (
> @@ -32,7 +32,7 @@ RDEPEND="
>  		media-plugins/gst-plugins-chromaprint:1.0
>  	)
>  	dev-libs/json-glib
> -	daap? ( >=net-libs/libdmapsharing-2.9.12:3.0 )
> +	daap? ( >=net-libs/libdmapsharing-3.9.11:4.0 )
>  	media-libs/libmediaart:2.0
>  	soup3? (  net-libs/libsoup:3.0 )
>  	!soup3? ( net-libs/libsoup:2.4 )
> @@ -44,10 +44,7 @@ RDEPEND="
>  	dev-db/sqlite:3
>  	>=dev-libs/totem-pl-parser-3.4.1:=
>  	tracker? ( app-misc/tracker:3= )
> -	upnp-av? (
> -		net-libs/dleyna-connector-dbus
> -		net-misc/dleyna-server
> -	)
> +	upnp-av? ( net-libs/dleyna:1.0= )
>  	lua? (
>  		${LUA_DEPS}
>  		app-arch/libarchive
> ```
> 
> ## grilo
> 
> ```
> commit ad584576b5335523e8cd499e10c6747b49a48606
> Author: Matt Turner <mattst88@gentoo.org>
> Date:   Wed Mar 29 22:49:18 2023 -0400
> 
>     fixup! media-libs/grilo: Version bump to 0.3.15-r1
> 
> diff --git a/media-libs/grilo/grilo-0.3.15-r1.ebuild b/media-libs/grilo/grilo-0.3.15-r1.ebuild
> index 75a91b30e98a..4a8830bdf569 100644
> --- a/media-libs/grilo/grilo-0.3.15-r1.ebuild
> +++ b/media-libs/grilo/grilo-0.3.15-r1.ebuild
> @@ -13,7 +13,7 @@ LICENSE="LGPL-2.1+"
>  SLOT="0.3/0" # subslot is libgrilo-0.3 soname suffix
>  KEYWORDS="~alpha ~amd64 ~arm ~arm64 ~ia64 ~ppc ~ppc64 ~riscv ~sparc ~x86"
>  
> -IUSE="gtk gtk-doc +introspection +playlist soup3 test vala"
> +IUSE="gtk gtk-doc +introspection +playlist +soup3 test vala"
>  REQUIRED_USE="vala? ( introspection )"
>  RESTRICT="!test? ( test )"
> ```
> 
> We'll also need to mask grilo-plugins' IUSE=youtube.

grilo-plugins-0.3.16 is out, enabling libsoup3 for dmap (IUSE daap) libdmapsharing-4.0 , but does not compile because is trying to find libdmapsharing-3

`NEW in grilo-plugins-0.3.16
===========================
  * !132 tracker3: update fts query
  * !133 dmap: enable with libsoup3 supported libdmapsharing-4.0
  * !131 lua-factory: add support to 5.4
  * !128 !129 !135 build: libsoup3 related fixes
  * !127 flickr: remove GOA support
  * !126 tmdb: without config, fix single request`

**Pull request closed without merging**
