### PR TITLE
ruby-ng.eclass: killing old implementations

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by graaff** [comment]
Sounds good to me. Feel free to merge when the QA checks are clean. I've added a reminder to include this in forthcoming "how to remove a ruby version" notes.

**Comment by mgorny** [comment]
@graaff, thanks. I'll ping you once I have a complete set.

**Comment by chewi** [comment]
That's fine. I don't see jruby coming back at least until Java team has a new plan worked out. Shame, we just started using it at work.

**Comment by graaff** [comment]
Looks good to me. Thanks!

**Comment by mgorny** [comment]
Merged, thanks!

**Pull request closed without merging**
