### PR TITLE
dev-util/pkgconf: bump to version 0.9.12.

### PR DESCRIPTION
**Pull request by Elizafox**
This version fixes some deduplication edge cases on -L and -I CFLAGS/LIBS.

### CODE REVIEW

**Comment by idella** [comment]
KEYWORDS="alpha amd64 arm ~arm64 hppa ia64 ~m68k ~mips ppc ppc64 ~s390 ~sh sparc x86 
All need conversion to ~ status.
I have added you to metadata

**Comment by idella** [comment]
@gentoo/proxy-maint

**Comment by Elizafox** [comment]
Thanks for pointing that out; fixed.

**Comment by idella** [comment]
merged

**Pull request merged**
