### PR TITLE
cargo.eclass: allow passing additional arguments to cargo

### PR DESCRIPTION
**Pull request by gyakovlev**
@gentoo/rust

### CODE REVIEW

**Comment by djc** [comment]
LGTM. Out of interest, what do you want these for?

**Comment by gyakovlev** [comment]
> LGTM. Out of interest, what do you want these for?

most common use in mind is cargo's `--freatures` option to enable optional features without just copying entire src functions from the ebuild.

https://doc.rust-lang.org/cargo/reference/manifest.html#the-features-section

like in the example
`$(usex pcre "--features pcre2" "")`


there is another way suggested by mgorny on dev@, by simply passing `"${@}"` to the function
https://archives.gentoo.org/gentoo-dev/message/8de1220aa77c6de673338fb9aae3d5d6

```diff
diff --git a/eclass/cargo.eclass b/eclass/cargo.eclass
index 50f7830c51b..aa889751fef 100644
--- a/eclass/cargo.eclass
+++ b/eclass/cargo.eclass
@@ -122,7 +122,7 @@ cargo_src_compile() {
 
        export CARGO_HOME="${ECARGO_HOME}"
 
-       cargo build -j $(makeopts_jobs) $(usex debug "" --release) \
+       cargo build -j $(makeopts_jobs) $(usex debug "" --release) "${@}" \
                || die "cargo build failed"
 }
 
@@ -132,7 +132,7 @@ cargo_src_compile() {
 cargo_src_install() {
        debug-print-function ${FUNCNAME} "$@"
 
-       cargo install -j $(makeopts_jobs) --root="${D}/usr" $(usex debug --debug "") \
+       cargo install -j $(makeopts_jobs) --root="${D}/usr" $(usex debug --debug "") "${@}" \
                || die "cargo install failed"
        rm -f "${D}/usr/.crates.toml"
```

this one even simpler and cleaner
let's wait a bit, I'll test that simpler variant on packages and update PR and patch on mailing list.

**Comment by gyakovlev** [comment]
I've updated the patch, also added standard `src_test`
also posted on dev ml for review

**Comment by djc** [comment]
LGTM for the Rust project.

**Comment by gyakovlev** [comment]
merged.

**Pull request closed without merging**
