### PR TITLE
games-action/polymc: bump version to 1.3.1

### PR DESCRIPTION
**Pull request by flowln**
No changes from the previous version!

### CODE REVIEW

**Comment by AndrewAmmerlaan** [comment]
@flowln Looks good but we are missing a sign-off on your commit. Note that due to recent changes in pkgdev, the automatic sign-off is now **opt-in**. You can enable it in `~/.config/pkgdev/pkgdev.conf`:
```
[DEFAULT]
commit.signoff = true
```

Where you can also replace `DEFAULT` with `gentoo` to only sign-off commits to `::gentoo`.

I'll merge this anyway since the file is exactly identical to the file we already have in the repository.

**Comment by flowln** [comment]
> Note that due to recent changes in pkgdev, the automatic sign-off is now opt-in.

Ahh so that's what happened, sorry, i'll update my config :sweat:

**Comment by flowln** [comment]
@AndrewAmmerlaan I've updated it!

**Comment by AndrewAmmerlaan** [comment]
> @AndrewAmmerlaan I've updated it! (Ok, too late :p won't happen next time, I promise!)

No worries, thanks for the PR :+1:

**Pull request closed without merging**
