### PR TITLE
dev-python/{hiredis,jmespath}: drop old

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes some old ebuilds from the tree (EAPI4 and EAPI5)
Please review.

### CODE REVIEW

**Comment by flappyports** [comment]
please rebase

**Comment by mm1ke** [comment]
@flappyports done, just rebased

**Comment by a17r** [comment]
I've merged all package droppings without dedicated maintainer.

**Comment by mm1ke** [comment]
@a17r thanks, i've rebased again my PR

**Pull request closed without merging**
