### PR TITLE
net-firewall/fwknop: revbump to 2.6.8-r2, verbump to 2.6.9

### PR DESCRIPTION
**Pull request by Coacher**

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint

**Comment by gktrk** [comment]
@Coacher [lib/fko.h](https://github.com/mrash/fwknop/blob/master/lib/fko.h#L16): "either version 2 of the License, or (at your option) any later version" Reads like GPL-2+ to me. Also I am really curious what pulls in GPL-1, would you kindly point me to it?

**Comment by Coacher** [comment]
@gktrk, many files have the GPL2+ header, but there are also some files that doesn't have any copyright header at all and upstream says in docs that client and server are licensed as GPL2. Thus it's GPL2 only, not GPL2+.

As for your GPL1 question: https://github.com/mrash/fwknop/blob/master/python/setup.py#L33

**Comment by Coacher** [comment]
I've pinged upstream re their license and it turns out their docs are outdated on this matter: https://github.com/mrash/fwknop/issues/222

I'll update this PR accordingly soon.

**Comment by Coacher** [comment]
I've updated the PR wrt license. It's good to go now.

**Comment by Coacher** [comment]
There were some doubts whether BSD should be added to LICENSE, because fwknop has come C code under BSD.
Since BSD (3-clause) is (GPL-2+)-compatible and upstream has chosen GPL-2+ as their license, the resulting binaries are GPL-2+ only (no BSD). See https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean. Thus BSD isn't needed in LICENSE.
This was also confirmed in #gentoo-dev-help by bernalex (who is a member of licenses project):
```
[Friday 03 June 2016] [23:49:29] <Coacher>	Hello. AFAIK BSD (as in licenses/BSD) is GPL-compatible. According to https://www.gnu.org/licenses/gpl-faq.html#WhatDoesCompatMean, this allows to compile BSD C code with GPL C code into a single shared library that will be GPL. Should one include BSD in LICENSE in such case given that the original C files are never installed and upstream says their project is GPL without mentioning BSD?
[Friday 03 June 2016] [23:56:21] <bernalex>	Coacher: the licence of the derivative work is what is to be included. if the derivative work is GPL, the BSD licence is no longer relevant.
[Friday 03 June 2016] [23:57:49] <Coacher>	bernalex: Just to make sure I understand correctly. In this case the resulting shared library is the derivative work, right?
[Friday 03 June 2016] [23:59:50] <bernalex>	Coacher: yes.
[Saturday 04 June 2016] [00:00:37] <Coacher>	bernalex: Ok. Thank you very much.
```

**Comment by Coacher** [comment]
Meanwhile 2.6.9 was released. I've updated the PR accordingly.

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by Coacher** [comment]
Thank you, @gktrk.

**Pull request closed without merging**
