### PR TITLE
gui-wm/gamescope: update to 3.14.18 (solve most nvidia bugs) and working 9999

### PR DESCRIPTION
**Pull request by MrDuartePT**
This PR have the intention of adding a working 9999 gamescope ebuild and update to version 3.14.18
The ebuild for 3.14.18 needed some change to build properly, the ebuild was failing compile with errors do the `drm` backend being enable (see https://github.com/ValveSoftware/gamescope/issues/1320#issuecomment-2128265761 and 
https://github.com/ValveSoftware/gamescope/issues/1320#issuecomment-2129672489 , build log also in the attachments)

Also looking at meson.build file of gamescope, also show that the official build of gamescope dosent use the [`drm` backend](https://github.com/ValveSoftware/gamescope/blob/420eb91387a484fd7b1ea71449091f0480d9e538/src/meson.build#L31), that can be because gamescope have there own drm implemation, so I don't understanding why the gentoo ebuild requires wlroots to be build with it.

- [x] Also I will try to build gamescope-9999 using wlroots-9999, with the `drm` useflag enable to see if causes any problems building gamescope using system wlroots.

Note: version 3.14.17 is provided as fallback since it dosen't required the change to wlroots build flags
[gamescope-build.log](https://github.com/gentoo/gentoo/files/15439619/gamescope-build.log)

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by MrDuartePT** [comment]
> * [x]  Also I will try to build gamescope-9999 using wlroots-9999, with the `drm` useflag enable to see if causes any problems building gamescope using system wlroots.

Ok I don't get very far (as I was expecting) it seems to be a bug in wlroots upstream and dev-libs/libliftoff-0.5.0_rc1, upsream gamescope don't have that problems because they dont build using `drm` backend:

**Comment by chewi** [comment]
Sorry, I've been away a few days. Need a little longer to catch up.

**Comment by MrDuartePT** [comment]
> Sorry, I've been away a few days. Need a little longer to catch up.

No problem 👍

**Comment by chewi** [comment]
I've taken 3.14.18, thanks. I had already taken libliftoff 0.5.0 (final) in #36938.

Please don't submit 9999. I said I didn't want it before, and untangling it from your submission makes life harder for me.

Thanks for working out the wlroots backend issue. I probably enabled drm because we had all the dependencies covered anyway, but I guess it doesn't help.

**Comment by MrDuartePT** [comment]
> Please don't submit 9999. I said I didn't want it before, and untangling it from your submission makes life harder for me.

Sorry about that I probably forgot about it.

**Pull request closed without merging**
