### PR TITLE
Bump spyder to 3.2.8 and add support for QtWebengine.

### PR DESCRIPTION
**Pull request by holgersson32644**
Runs fine, but **I did not test this with qtwebkit** as I simply don't have it on any system.

### CODE REVIEW

**Comment by holgersson32644** [comment]
dev-python/cloudpickle[${PYTHON_USEDEP}] is missing, I’m on it.

**Comment by holgersson32644** [comment]
-> Dep added and deps reorganised alphabetically.

**Comment by mgorny** [comment]
Well, let's see how many days it takes me to build it ;-).

**Comment by holgersson32644** [comment]
Fixed in commit 4a840b79c169fca88e28f2aa4ddc97c5b7ac3eea.

**Pull request closed without merging**
