### PR TITLE
dev-java/antlr-runtime: new package | dev-java/stringtemplate: Slot 4 depend on antlr-runtime 

### PR DESCRIPTION
**Pull request by vaukai**
Bug: https://bugs.gentoo.org/742554

Compared with https://repo1.maven.org/maven2/org/antlr/antlr-runtime/3.5.2/antlr-runtime-3.5.2.jar it looks good

Package-Manager: Portage-3.0.18, Repoman-3.0.2
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by fordfrog** [comment]
nice :-) we still need the remaining two packages though as this should be rather replacement for current antlr instead of an add-on to an existing ebuild :-)

**Comment by vaukai** [comment]
> nice :-) we still need the remaining two packages though as this should be rather replacement for current antlr instead of an add-on to an existing ebuild :-)

Just added a draft `stringtemplate-4.0.8-r2.ebuild` which still has problems.  Guess it needs something like [here in line 60](https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-java/stringtemplate/stringtemplate-4.0.8-r1.ebuild#n60) but I can't get it work :-(

**Comment by vaukai** [comment]
Trying with `antlr3 -o` in `stringtemplate-4.3.1.ebuild`
```
src_compile() {
    antlr3 -o ${JAVA_SRC_DIR}/org/stringtemplate/v4/compiler $(find ${JAVA_SRC_DIR} -name "*.g") || die
    java-pkg-simple_src_compile
}
```
leads to:
```
 * Compiling ...
warning: [options] bootstrap class path not set in conjunction with -source 8
src/org/stringtemplate/v4/gui/JTreeScopeStackModel.java:74: error: cannot find symbol
            root.insertChild(0, templateNode);
                ^
  symbol:   method insertChild(int,StringTree)
  location: variable root of type CommonTree
src/org/stringtemplate/v4/compiler/Compiler.java:173: error: incompatible types: Object cannot be converted to CommonTree
            impl.ast = r.getTree();
                                ^
Note: src/org/stringtemplate/v4/gui/STViz.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
2 errors
1 warning
```

**Comment by vaukai** [comment]
TODO;
*  `dev-java/openjfx-11.0.9_p0.ebuild` needs to be moved to using antlr-runtime-3,5,2
*  solve stringtemplate

**Pull request closed without merging**
