### PR TITLE
dev-ruby/travis: initial commit

### PR DESCRIPTION
**Pull request by junghans**
@gentoo/ruby: Last, but not least!

### CODE REVIEW

**Comment by graaff** [comment]
I see a lot of test failures like this:

```
Failures:

  1) Travis::CLI::Cancel travis cancel
     Failure/Error: run_cli('cancel', '-t', 'token').should be_success
       expected success? to return true, got false
     # ./spec/cli/cancel_spec.rb:5:in `block (2 levels) in <top (required)>'

  2) Travis::CLI::Cancel travis cancel 6180.1
     Failure/Error: run_cli('cancel', '6180.1', '-t', 'token').should be_success
       expected success? to return true, got false
     # ./spec/cli/cancel_spec.rb:11:in `block (2 levels) in <top (required)>'

  3) Travis::CLI::Encrypt travis encrypt foo
     Failure/Error: run_cli('encrypt', 'foo').should be_success
       expected success? to return true, got false
     # ./spec/cli/encrypt_spec.rb:5:in `block (2 levels) in <top (required)>'
```

If you don't see them then this might be due to having travis already installed, given that these seem to be about the command line tools.

**Comment by junghans** [comment]
On a fresh re-install I see:
```
stty: standard input: Inappropriate ioctl for device
```
and the errors as you!

Should we put `RESTRICT="test"`?

**Comment by monsieurp** [comment]
@junghans if tests do not pass, please do use `RESTRICT="test"`.

**Comment by junghans** [comment]
Done!

**Pull request merged**
