### PR TITLE
dev-util/cscope: Fix direct call of pkg-config in configure script

### PR DESCRIPTION
**Pull request by semihalf-czapiga-jakub**
Signed-off-by: Jakub Czapiga <jacz@semihalf.com>

### CODE REVIEW

**Comment by thesamesam** [comment]
Would you mind making a patch to `configure.ac` instead, especially given we already call `eautoreconf`?

But huge thanks for the change!

**Comment by semihalf-czapiga-jakub** [comment]
@thesamesam Is the new version close, to what You anticipated?
Regarding pushing changes to upstream: I do not think, that cscope repository is even alive at this point. It's a great project, but their website is old, and mentions only version 15.8a (release around 2012).

**Comment by semihalf-czapiga-jakub** [comment]
@thesamesam Can you take a look? Is it my fault that bot closed this PR?

**Comment by thesamesam** [comment]
Nono, it's all OK, it's actually merged -- it's just because of how we merge commits (github is a mirror, so I apply patches with `git am`).

Your commit is safe & sound here: https://github.com/gentoo/gentoo/commit/19edcd377f662c55aae15bc8fc15ae0fe7e07c3a. Thank you!

**Comment by semihalf-czapiga-jakub** [comment]
Oh. Thank you very much :)

**Pull request closed without merging**
