### PR TITLE
dev-util/bats: bump to 1.2.1

### PR DESCRIPTION
**Pull request by henning-schild**
The project has been forked and now internally called "bats-core", let
us keep the original name for now.

Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by ntnn** [comment]
See the discussion in #12280

**Comment by ntnn** [comment]
@henning-schild I'd suggest you ask for a proxy maintainer on the proxy-maintainers mailing list and/or in #gentoo-proxy-maint on freenode and take over the dev-util/bats ebuild.
If you aim to be a gentoo developer you could also ask for a mentor who can then be your proxy maintainer until you've passed your quizzes:
https://wiki.gentoo.org/wiki/Project:ComRel/Developer_Handbook/Becoming_a_developer

**Comment by ntnn** [comment]
FWIW I've already had bats-core and some bats libs ready in my personal overlay since 2018:
https://github.com/ntnn/gentoo-thabairne/tree/master/dev-util/

You're welcome to update the ebuilds to EAPI 7 and bring them into the tree with your mentor/proxy-maint.

**Comment by henning-schild** [comment]
In fact i already proxy maintain `net-im/telegram-desktop-bin` and am active with a few more. I will see about the process and apply for this one.

**Comment by henning-schild** [comment]
@Polynomial-C i took the liberty to just add myself as proxy maint, that was suggested on IRC by @ajakk (who hopefully is ajak on IRC)

**Comment by henning-schild** [comment]
We could also call it "bats-core" and introduce a conflict on the old unmaintained "fork-off"

**Comment by Polynomial-C** [comment]
@henning-schild: I can merge this but I will also remove Nelo and myself from `metadata.xml` as well because we both no longer have interest in this package. Are you okay with that?

**Comment by henning-schild** [comment]
@Polynomial-C sure go ahead

**Pull request closed without merging**
