### PR TITLE
dev-tex/biber: remove unused patch

### PR DESCRIPTION
**Pull request by mm1ke**
Hi @mrueg 

This PR removes a unused patch in **dev-tex/biber.**
Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
ping. just rebased my PR. :)

**Comment by mm1ke** [comment]
ping, just another rebase of my PR :)

**Comment by mm1ke** [comment]
ping, another rebase :)

**Comment by SoapGentoo** [comment]
@mm1ke you'll have to upload this one onto the bugtracker, as @mrueg will not use Github.

**Pull request closed without merging**
