### PR TITLE
app-shells/fzf: version bump to v0.30.0

### PR DESCRIPTION
**Pull request by ran-dall**
This commits add an ebuild for app-shells/fzf v0.30.0.

Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Comment by ran-dall** [comment]
Please don't merge. This ebuild needs the `EGO_SUM` to be switched to a *-deps tarball.

**Comment by ran-dall** [comment]
I've converted over this ebuild to use a tarball for `EGO_SUM`.

https://github.com/ran-dall/portage-deps/blob/master/fzf-0.30.0-deps.tar.xz

**Comment by ran-dall** [comment]
I guess this can be closed as @mattst88 pushed https://github.com/gentoo/gentoo/commit/d9cfe284cf9137efe59ba6571591ce6fdb6f7064 already.

**Comment by mattst88** [comment]
Sorry, I didnt think to look for a pull request.

**Comment by ran-dall** [comment]
@mattst88 It's alright, mate! It got updated; that's all that matters.

**Pull request closed without merging**
