### PR TITLE
Python 8

### PR DESCRIPTION
**Pull request by thebitpit**
media-tv/mythtv: Add support for Python 3.8
media-plugins/mythplugins: Add support for Python 3.8
Signed-off-by: Wilson Michaels <thebitpti@austincustomerrands.com>

### CODE REVIEW

**Comment by a17r** [comment]
Please make sure to get rid of any spurious merge commit before you open PRs.

**Comment by thebitpit** [comment]
> Please make sure to get rid of any spurious merge commit before you open PRs.

I spent a lot more time trying (and failing) to do that than it took to make the changes and test them.
What is the procedure for getting rid of a spurious merge commit?

**Comment by thebitpit** [comment]
> Please make sure to get rid of any spurious merge commit before you open PRs.

I spent a lot more time trying (and failing) to do that than it took to make the changes and test them.
What is the procedure for getting rid of a spurious merge commit?

**Comment by thebitpit** [comment]
Closing PR to make one without spurious merge commit.

**Comment by juippis** [comment]
What is your prodecure for creating PRs? I think you're merging into your branch, evne though you can update your master before creating a new branch, and/or you can rebase your master into your branch.

Ie,
```
git checkout master
git fetch upstream
git pull upstream master

git checkout -b mynewbranch
```
And to update branch with master,
```
git checkout master
git fetch upstream
git pull upstream master

git checkout mybranch
git rebase master
```
or
```
git checkout mybranch2
git pull --rebase upstream master
```

**Pull request closed without merging**
