### PR TITLE
x11-misc/rofi-file-browser-extended: Fix incompatible pointer type

### PR DESCRIPTION
**Pull request by listout**
And some other build time warnings

Closes: https://bugs.gentoo.org/928491

### CODE REVIEW

**Comment by Flowdalic** [comment]
Thanks for your contribution.

I know that upstream appears to be abandoned, but could you still also send a PR upstream and link that PR here?

**Comment by Flowdalic** [comment]
> Send the patch [upstream](https://github.com/marvinkreis/rofi-file-browser-extended/pull/54) (made a PR) and linked it in the patch here.

Thanks.

Please also add the missing Signed-off-by git trailer to your commit in this PR.

**Comment by Flowdalic** [comment]
@listout friendly ping about the missing signed-off-by git trailer

**Comment by listout** [comment]
Ack, will fix it.

**Comment by listout** [comment]
@Flowdalic done, thank you and sorry for the delay.

**Pull request closed without merging**
