### PR TITLE
mail-filter/spamassassin: remove unused file

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes a unused file from:
mail-filter/spamassassin

Please review

### CODE REVIEW

**Comment by Philippe23** [comment]
I agree with @mm1ke, that file does not look like it's used anymore.

Same with `3.4.1-spamd.conf`, `3.4.1-spamd.init`, nor `spamassassin.service.conf` from what I see.

**Comment by monsieurp** [comment]
Thanks for the feedback. @Philippe23 can we punt it then?

**Comment by Philippe23** [comment]
@monsieurp I removed all of them locally and tested `spamassassin-3.4.1-r21.ebuild` and it works fine and double-checked that it's not referenced in the other spamassassin ebuilds.

I vote nuke it/accept the PR.

**Comment by mm1ke** [comment]
@Philippe23 
Thanks for checking, i've updated the PR and added the other files too.

**Pull request closed without merging**
