### PR TITLE
media-video/mpv: version bump to 0.14.0, revision bump to 0.11.0-r1, update live

### PR DESCRIPTION
**Pull request by Coacher**
Fix bugs: 565618, 565646, 562394, 568018, 564656.

Based on and supersedes PRs #318 and #511.

This is the updated version of PR #511 that includes changes proposed by @mgorny.
I don't want to force push to my previous PR as GitHub sometimes loses line comments this way.

CC @maksbotan, @yngwin, @mgorny, @idella.

### CODE REVIEW

**Comment by Coacher** [comment]
**A package USE mask is required** for `media-video/mpv test` on alpha arch **prior to merging** this one. QA checks are expected to fail because of this.

**Comment by Coacher** [comment]
**A package USE mask is required** for `media-video/mpv uchardet` in base and **package USE unmask** for `media-video/mpv uchardet` on amd64 and x86 **prior to merging** this one. QA checks are expected to fail because of this.

**Comment by monsieurp** [comment]
@gentoo/video @gentoo/proxy-maint

**Comment by Coacher** [comment]
@perfinion re https://github.com/gentoo/gentoo/pull/511#issuecomment-167491953

I've just tried and added `media-video/mpv test` USE mask in my overlay. `FEATURES='test' emerge -pv mpv` command does not enable `test` USE. Test suite will fail miserably though ofc.

**Comment by Coacher** [comment]
Rebased on top of changes mentioned above made by idella4 and repushed.

**Pull request merged**
