### PR TITLE
dev-util/bear: support python-3.10 in dev-util/bear-2.4.4-r1

### PR DESCRIPTION
**Pull request by dpronin**
enabled opportunity for a user to use python-3.10 for
dev-util/bear-2.4.4-r1

Signed-off-by: Denis Pronin <dannftk@yandex.ru>

### CODE REVIEW

**Comment by dpronin** [comment]
@gyakovlev, will we merge it in?

**Comment by dpronin** [comment]
ping

**Comment by gyakovlev** [comment]
was away, testing

**Comment by gyakovlev** [comment]
```
test 1
    Start 1: func_test

1: Test command: /usr/sbin/lit "-DEAR_EXE=/var/tmp/portage/dev-util/bear-2.4.4-r1/work/bear-2.4.4_build/bear/bear" "-DEAR_LIB=/var/tmp/portage/dev-util/bear-2.4.4-r1/work/bear-2.4.4_build/libear/libear.so" "-v" "/var/tmp/portage/dev-util/bear-2.4.4-r1/work/Bear-2.4.4/test"
1: Test timeout computed to be: 10000000
1: -- Testing: 29 tests, 29 workers --
1: XFAIL: bear :: functional/cases/exit_code/exit_code_for_empty.ft (1 of 29)
1: PASS: bear :: functional/cases/exit_code/exit_code_for_success.ft (2 of 29)
1: XFAIL: bear :: functional/cases/exit_code/exit_code_for_fail.ft (3 of 29)
1: PASS: bear :: functional/cases/result/define_with_nonutf_encode.fts (4 of 29)
1: PASS: bear :: functional/cases/exit_code/exit_code_for_help.ft (5 of 29)
1: PASS: bear :: functional/cases/intercept/empty_argument.fts (6 of 29)
1: PASS: bear :: functional/cases/intercept/parallel_build.fts (7 of 29)
1: PASS: bear :: functional/cases/intercept/broken_build.fts (8 of 29)
1: PASS: bear :: functional/cases/result/exclude.fts (9 of 29)
1: PASS: bear :: functional/cases/intercept/noisy_build.fts (10 of 29)
1: PASS: bear :: functional/cases/result/duplicate_entries.fts (11 of 29)
1: PASS: bear :: functional/cases/result/assembly_sources.fts (12 of 29)
1: PASS: bear :: functional/cases/intercept/successful_build.fts (13 of 29)
1: PASS: bear :: functional/cases/result/field_output.fts (14 of 29)
1: PASS: bear :: functional/cases/intercept/clean_env_build.fts (15 of 29)
1: PASS: bear :: functional/cases/result/output_kept.fts (16 of 29)
1: PASS: bear :: functional/cases/result/multiple_source_build.fts (17 of 29)
1: PASS: bear :: functional/cases/result/define_with_quote.fts (18 of 29)
1: PASS: bear :: functional/cases/result/file_path_relative.fts (19 of 29)
1: PASS: bear :: functional/cases/result/define_with_escaped_quote.fts (20 of 29)
1: PASS: bear :: functional/cases/result/define_with_unicode.fts (21 of 29)
1: PASS: bear :: functional/cases/result/directory_path_absolute.fts (22 of 29)
1: PASS: bear :: functional/cases/result/flags_filtered.fts (23 of 29)
1: PASS: bear :: functional/cases/result/extend_build_with_missing.fts (24 of 29)
1: PASS: bear :: functional/cases/result/extend_build.fts (25 of 29)
1: PASS: bear :: functional/cases/intercept/unkown_compiler_recognised.fts (26 of 29)
1: PASS: bear :: functional/cases/fortran/compile_fortran.fts (27 of 29)
1: PASS: bear :: functional/cases/end-to-end/qmake.ft (28 of 29)
1: PASS: bear :: functional/cases/exec_calls/run_exec_test.ft (29 of 29)
1: 
1: Testing Time: 1.56s
1:   Passed           : 27
1:   Expectedly Failed:  2
1/1 Test #1: func_test ........................   Passed    1.74 sec

100% tests passed, 0 tests failed out of 1

Total Test time (real) =   1.76 sec
>>> Completed testing dev-util/bear-2.4.4-r1
```
lgtm, will merge soon.

**Comment by dpronin** [comment]
Where have you found these tests? Next time I can do it myself

**Comment by gyakovlev** [comment]
in the directory with ebuild, while having all deps and test deps installed (`emerge =bear-2.4.4-r1 --with-test-deps --onlydeps`):

`FEATURES="-usersandbox -sandbox" ebuild bear-2.4.4-r1.ebuild clean test`

will run the test suite.

**Pull request closed without merging**
