### PR TITLE
profiles/*: Add missing eapi files

### PR DESCRIPTION
**Pull request by ulm**

### CODE REVIEW

**Comment by ulm** [comment]
@gentoo/prefix @gentoo/amd64 @gentoo/arm @gentoo/arm64 @gentoo/mips @gentoo/ppc @gentoo/x86: Please review.

**Comment by ulm** [comment]
Git's rename detection is stupid. Best if you look at the two commits separately.

**Comment by grobian** [comment]
ack

**Comment by ulm** [comment]
Merged.

**Pull request closed without merging**
