### PR TITLE
Reenable systemd units that create symlinks via the 'Alias' option

### PR DESCRIPTION
**Pull request by floppym**
This is needed to keep things working when some packages are rebuilt after upgrading to systemd 234.

### CODE REVIEW

**Comment by floppym** [comment]
cc @gentoo/kde @gentoo/gnome @gentoo/lxqt @gentoo/systemd

**Comment by EvaSDK** [comment]
it sounds to me as it should apply to a lot more than this. Shouldn't apply to any package providing units ? What about user units ?

**Comment by floppym** [comment]
> Shouldn't apply to any package providing units ?

Most units are unaffected by the rootprefix change; systemd ignores symlink targets within .wants/ directories.

> What about user units ?

Impossible to fix from the package manager.

**Comment by EvaSDK** [comment]
+1 for merge but I think some kind of announcement must be done to fellow devs so we do not miss this new systemd eclass call when needed. Maybe a QA check in portage like the recently added icon cache update detection.

**Comment by floppym** [comment]
> What about user units ?

Actually, user-units are unaffected by the rootprefix change: they still get installed in `/usr/lib/systemd/user` since they are not "boot-critical". So nothing to really worry about there.

**Comment by mgorny** [comment]
I think it'd be nice to actually explain there when it needs to be used and when not.

**Comment by floppym** [comment]
I added a paragraph explaining intended use of the `systemd_reenable` function.

**Comment by floppym** [comment]
Rebased and merged.

**Pull request closed without merging**
