### PR TITLE
Update to webkit-gtk 2.32.0

### PR DESCRIPTION
**Pull request by Sadoon-AlBader**
Just a version bump, works fine on x86_64, testing ppc64le now.

Signed-off-by: Sadoon AlBader sadoon_albader@protonmail.com

### CODE REVIEW

**Comment by scardracs** [comment]
You have not run ebuild webkit-gtk-2.32.0.ebuild manifest before uploading it

**Comment by Sadoon-AlBader** [comment]
> You have not run ebuild webkit-gtk-2.32.0.ebuild manifest before uploading it

Apologies, will send a commit correcting that.
Otherwise the software runs fine on my machines, both x86_64 and ppc64le, currently testing ppc.

**Comment by scardracs** [comment]
> > You have not run ebuild webkit-gtk-2.32.0.ebuild manifest before uploading it
> 
> Apologies, will send a commit correcting that.
> Otherwise the software runs fine on my machines, both x86_64 and ppc64le, currently testing ppc.

Do not need to apologize ;)

**Comment by Sadoon-AlBader** [comment]
> > > You have not run ebuild webkit-gtk-2.32.0.ebuild manifest before uploading it
> > 
> > 
> > Apologies, will send a commit correcting that.
> > Otherwise the software runs fine on my machines, both x86_64 and ppc64le, currently testing ppc.
> 
> Do not need to apologize ;)

Thank you :)
I beleive now it is fixed.

**Comment by scardracs** [comment]
You can't remove 2.30.5 if it is a revdep of other packages

**Comment by mattst88** [comment]
Please rebase the PR.

Also... were there really no dependency or other packaging changes, or did you not check? :)

**Comment by mattst88** [comment]
> Please rebase the PR.
> 
> Also... were there really no dependency or other packaging changes, or did you not check? :)

There were a couple, which I've handled in a PR that adds webkit-gtk-2.32.0 and epiphany-40.0.

**Pull request closed without merging**
