### PR TITLE
lxde-base/lxpanel: version bump 0.8.2 => 0.9.1

### PR DESCRIPTION
**Pull request by charIes17**
Gentoo-Bug: 601586

### CODE REVIEW

**Comment by khumarahn** [comment]
There is an annoying problem with the battery indicator on laptops not working in 0.9.1, see
https://sourceforge.net/p/lxde/bugs/848/

**Comment by charIes17** [comment]
Battery indicator wfm.  Using fluxbox without just with lxpanel and some goodies, not lxde-meta.

**Comment by khumarahn** [comment]
Can you check if you have the file `/sys/class/power_supply/BAT<something>/charge_now`? What kernel are you using?

**Comment by charIes17** [comment]
$ uname -r
4.4.26-gentoo

Indicator is green with
$ cat /sys/class/power_supply/C1BC/uevent 
POWER_SUPPLY_NAME=C1BC
POWER_SUPPLY_STATUS=Charging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=10800000
POWER_SUPPLY_VOLTAGE_NOW=12731000
POWER_SUPPLY_CURRENT_NOW=2278000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4042000
POWER_SUPPLY_CHARGE_FULL=4042000
POWER_SUPPLY_CHARGE_NOW=3437000
POWER_SUPPLY_CAPACITY=85
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=Primary
POWER_SUPPLY_MANUFACTURER=Hewlett-Packard
POWER_SUPPLY_SERIAL_NUMBER=10240 2013/01/08

and yellow with
 $ cat /sys/class/power_supply/C1BC/uevent 
POWER_SUPPLY_NAME=C1BC
POWER_SUPPLY_STATUS=Discharging
POWER_SUPPLY_PRESENT=1
POWER_SUPPLY_TECHNOLOGY=Li-ion
POWER_SUPPLY_CYCLE_COUNT=0
POWER_SUPPLY_VOLTAGE_MIN_DESIGN=10800000
POWER_SUPPLY_VOLTAGE_NOW=11961000
POWER_SUPPLY_CURRENT_NOW=1433000
POWER_SUPPLY_CHARGE_FULL_DESIGN=4042000
POWER_SUPPLY_CHARGE_FULL=4042000
POWER_SUPPLY_CHARGE_NOW=3450000
POWER_SUPPLY_CAPACITY=85
POWER_SUPPLY_CAPACITY_LEVEL=Normal
POWER_SUPPLY_MODEL_NAME=Primary
POWER_SUPPLY_MANUFACTURER=Hewlett-Packard
POWER_SUPPLY_SERIAL_NUMBER=10240 2013/01/08

**Comment by khumarahn** [comment]
Can you try kernel 4.8?
```
$ ls -al /sys/class/power_supply/BAT1/
total 0
drwxr-xr-x 3 root root    0 Dec 17 13:20 .
drwxr-xr-x 3 root root    0 Dec 17 13:20 ..
-rw-r--r-- 1 root root 4096 Dec 17 13:20 alarm
-r--r--r-- 1 root root 4096 Dec 17 13:20 capacity
-r--r--r-- 1 root root 4096 Dec 17 13:20 capacity_level
-r--r--r-- 1 root root 4096 Dec 17 13:20 cycle_count
lrwxrwxrwx 1 root root    0 Dec 17 13:20 device -> ../../../PNP0C0A:00
-r--r--r-- 1 root root 4096 Dec 17 13:20 energy_full
-r--r--r-- 1 root root 4096 Dec 17 13:20 energy_full_design
-r--r--r-- 1 root root 4096 Dec 17 13:20 energy_now
-r--r--r-- 1 root root 4096 Dec 17 13:20 manufacturer
-r--r--r-- 1 root root 4096 Dec 17 13:20 model_name
drwxr-xr-x 2 root root    0 Dec 17 13:20 power
-r--r--r-- 1 root root 4096 Dec 17 13:20 power_now
-r--r--r-- 1 root root 4096 Dec 17 13:20 present
-r--r--r-- 1 root root 4096 Dec 17 13:20 serial_number
-r--r--r-- 1 root root 4096 Dec 17 13:20 status
lrwxrwxrwx 1 root root    0 Dec 17 13:20 subsystem -> ../../../../../../../../class/power_supply
-r--r--r-- 1 root root 4096 Dec 17 13:20 technology
-r--r--r-- 1 root root 4096 Dec 17 13:20 type
-rw-r--r-- 1 root root 4096 Dec 17 13:20 uevent
-r--r--r-- 1 root root 4096 Dec 17 13:20 voltage_min_design
-r--r--r-- 1 root root 4096 Dec 17 13:20 voltage_now
```
I miss files `charge_now`, `charge_full` and `charge_full_design`. It seems that without these, the battery indicator does not work. It could instead use `energy_now`, but it does not.

**Comment by charIes17** [comment]
OT here.  Let's discuss the network interface matter in forums.gentoo.org

**Pull request closed without merging**
