### PR TITLE
dev-libs/capstone: fix installed pkg-config file

### PR DESCRIPTION
**Pull request by hamarituc**
Closes: https://bugs.gentoo.org/858350
Signed-off-by: Mario Haustein <mario.haustein@hrz.tu-chemnitz.de>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
I wonder if that's by-design from upstream and maybe we should follow it? You can use `QA_PKGCONFIG_VERSION=""` globally in the ebuild to disable the check. Prevents a revbump too.

**Comment by hamarituc** [comment]
> I wonder if that's by-design from upstream and maybe we should follow it? You can use `QA_PKGCONFIG_VERSION=""` globally in the ebuild to disable the check. Prevents a revbump too.

This approach sounds better. I fixed it.

**Review by juippis — APPROVED** [review]
Thanks!

**Comment by thesamesam** [comment]
The fix used here is just going to lead to problems in the future. Just do =PV/rc* or similar?

**Comment by hamarituc** [comment]
> The fix used here is just going to lead to problems in the future. Just do =PV/rc* or similar?

See https://github.com/gentoo/gentoo/pull/26751/commits/78cb0f186446b500d492bdafb0411d279a5b0eca. Is it what you meant?

**Comment by thesamesam** [comment]
Almost -- could you try QA_PKGCONFIG_VERSION=${PV/_rc/}?

**Comment by hamarituc** [comment]
> Almost -- could you try QA_PKGCONFIG_VERSION=${PV/_rc/}?

No matter how you look at it, it remains odd. Upstream labels the release as 5.0_rc2 (without patch level) but ships the pkg-config file including the patch level (5.0.0). Thus `${PV/_rc*/}` yields `5.0` instead of `5.0.0`. There is no systematic approach to solve it. I would like suggest to keep it as proposed and to label upcoming releases according to the pkg-config file instead if the git release tags.

**Comment by thesamesam** [comment]
The existing approach (as in the one currently in ::gentoo) means you can silently keep it and not realise. Any approach is better than that, including your suggestion if you want.

**Pull request closed without merging**
