### PR TITLE
sys-kernel/ck-sources: update ck-patches homepage

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by gktrk** [comment]
Waiting for approval of @kuzetsa

**Comment by kuzetsa** [comment]
Oh! Thanks for catching this.  
Technically this new address does work, **however:**

HTTP 302 (*temporary redirect*) is in use at: [kernel.kolivas.org](http://kernel.kolivas.org),   
which correctly redirects to the same infrastructure. I'd prefer to use this URL instead, as upstream probably keeps this address up-to-date anyway (*seeing as the kernel.kolivas.org address is in the upstream IRC channel topic*)

Would mind updating the PR to that address instead?  
Either way, the old URL is a broken link & needs changed. Thanks.

**Comment by soredake** [comment]
@kuzetsa updated.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/b35ab638e37...f3de99e5690. Thanks!

**Pull request closed without merging**
