### PR TITLE
profiles: unmask plotutils on arm

### PR DESCRIPTION
**Pull request by doughdemon**
https://bugs.gentoo.org/587828

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks. What's the plan here? what do you expect us to do?

**Comment by junghans** [comment]
Wait for https://bugs.gentoo.org/show_bug.cgi?id=574242 and we will drop gnuplot-4.6.5

**Comment by doughdemon** [comment]
Thanks.
I'll rebase and reopen when gnuplot-4.6.5 is dropped.

**Comment by junghans** [comment]
Just drop =gnuplot-4.6.5 to ~arm (5.0.1-r1 is already stable on arm).

**Comment by monsieurp** [comment]
@junghans Hi! Is it ready for merge?

**Comment by monsieurp** [comment]
@junghans ping

**Comment by monsieurp** [comment]
pong.

**Comment by doughdemon** [comment]
Why was this closed?

**Pull request closed without merging**
