### PR TITLE
Firefox wayland pgo

### PR DESCRIPTION
**Pull request by juippis**
```diff
--- wlroots-0.15.1.ebuild	2022-09-28 18:38:29.916445934 +0300
+++ wlroots-0.15.1-r1.ebuild	2022-09-28 18:39:31.741510599 +0300
@@ -14,12 +14,12 @@
 	SLOT="0/9999"
 else
 	SRC_URI="https://gitlab.freedesktop.org/${PN}/${PN}/-/archive/${PV}/${P}.tar.gz"
-	KEYWORDS="amd64 arm64 ~loong ~ppc64 ~riscv x86"
+	KEYWORDS="~amd64 ~arm64 ~loong ~ppc64 ~riscv ~x86"
 	SLOT="0/$(ver_cut 2)"
 fi
 
 LICENSE="MIT"
-IUSE="vulkan x11-backend X"
+IUSE="tinywl vulkan x11-backend X"
 
 DEPEND="
 	>=dev-libs/libinput-1.14.0:0=
@@ -54,11 +54,13 @@
 	virtual/pkgconfig
 "
 
+PATCHES=( "${FILESDIR}"/wlroots-0.15.1-tinywl-dont-crash-upon-missing-keyboard.patch )
+
 src_configure() {
 	# xcb-util-errors is not on Gentoo Repository (and upstream seems inactive?)
 	local emesonargs=(
 		"-Dxcb-errors=disabled"
-		"-Dexamples=false"
+		$(meson_use tinywl examples)
 		-Drenderers=$(usex vulkan 'gles2,vulkan' gles2)
 		-Dxwayland=$(usex X enabled disabled)
 		-Dbackends=drm,libinput$(usex x11-backend ',x11' '')
@@ -67,6 +69,14 @@
 	meson_src_configure
 }
 
+src_install() {
+	meson_src_install
+
+	if use tinywl; then
+		dobin "${BUILD_DIR}"/tinywl/tinywl
+	fi
+}
+
 pkg_postinst() {
 	elog "You must be in the input group to allow your compositor"
 	elog "to access input devices via libinput."
```

### CODE REVIEW

**Comment by juippis** [comment]
@Hello71 

would you help maintain the codebase if it was used like this? :) at least for now.

**Review by arthurzam — APPROVED** [review]
Approved for `wlroots` part, as long as it works for you 😄

**Comment by Hello71** [comment]
sure, that looks basically fine to me, as long as it works for you. the main change I want to do eventually is replace coproc with something else, since bash officially only supports one coproc at a time. if it's only in one ebuild that's not an issue though. there's also a question of whether to do pgo with X or wayland if both are enabled, and whether that should be handled in the eclass or per-ebuild, and if the latter, whether there should be a policy recommending one or the other. for firefox specifically I think it's probably fine either way.

**Comment by juippis** [comment]
Because it seems that in this PR I forgot to edit `VIRTUALX_REQUIRED` value.

**Comment by eternal-sorrow** [comment]
@juippis so?

**Pull request closed without merging**
