### PR TITLE
x11-terms/guake: Add python 3.8 compat

### PR DESCRIPTION
**Pull request by Mord3rca**
Closes: https://bugs.gentoo.org/759529
Signed-off-by: Mord3rca <morderca@morderca.net>

### CODE REVIEW

**Comment by telans** [comment]
Why not bump it all the way to `python3_9`?

**Comment by Mord3rca** [comment]
I've done this modification to use PYTHON_SINGLE_TARGET="python3_8"

So ... I did not tested the python3_9 compatibility, if it's safe, I can change that

**Comment by telans** [comment]
You can check for any dependency issues with `repoman full -dx --if-modified=y`

**Comment by thesamesam** [comment]
@telans Right, although testing with Python 3.9 is still important

**Comment by Mord3rca** [comment]
So, I've installed gentoo on a VM with Gnome / XFCE

The installation with python 3.8 was fine. Nothing was wrong, everything worked out of the box.

However, for the python 3.9 targets .... A lot of packages block the installation of guake. (because they want python3.8)
+ depending on the graphical program used, blocking packages are different.

So, I won't change the compat to python3.9 for now. It seems risky. + This is supposed to be a small PR ^^"

**Pull request closed without merging**
