### PR TITLE
games-emulation/ppsspp:new ebuild

### PR DESCRIPTION
**Pull request by RobinDX**

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Adding a sole live ebuild to Portage isn't going to fly as it needs constant caring/updating. There seems to be at least a couple of releases put out by the PPSSPP community: 1.1.1 and 1.1 according to their website. Could you include one of these in your PR? Thank you.

**Comment by RobinDX** [comment]
@monsieurp
Although ppsspp has release versions,but the needed src such as ppsspp-ffmpeg pspautotesrs and minidx has no version .
Them changing constantly.
Because of this ， I dont think that makes sense about version
But I will try to add a ppsspp-1.1.1.ebuild 
after ppsspp add into portage tree.
I hope just  remove EGIT_REPO_URI then add SRC_URI will works.

**Comment by monsieurp** [comment]
OK. Give it a try with these two URLs:
https://github.com/hrydgard/ppsspp/archive/v1.1.1.zip
https://github.com/hrydgard/ppsspp/archive/v1.1.zip

**Comment by RobinDX** [comment]
Change ppsspp-9999.ebuid name to ppsspp-1.1.1.ebuild.
Then  add one line : 
EGIT_COMMIT="v${PV}"   
OK , it works.

**Comment by RobinDX** [comment]
@monsieurp
New pull  requests
https://github.com/gentoo/gentoo/pull/669

**Pull request closed without merging**
