### PR TITLE
sci-libs/ceres-solver: fix CI issues

### PR DESCRIPTION
**Pull request by waebbl**
- address MissingUseDepDefault  and for 1.12.0 also DeprecatedInsinto issues from pkgcheck
- remove slot and subslot operators on dependencies without slots

Package-Manager: Portage-2.3.96, Repoman-2.3.22
Signed-off-by: Bernd Waibel <waebbl@gmail.com>

### CODE REVIEW

**Comment by a17r** [comment]
I'd much rather have 1.14.0 fixed, stabilised and 1.12.0 dropped asap.

**Comment by waebbl** [comment]
@a17r ok, I thought about it, but want to get some feedback first. There are some other packages in the sci-* categories in the above CI list, I to look after, which have several unstable versions (e.g. suitesparse, spqr and others). I'm going to handle those the same way.

**Comment by waebbl** [comment]
One question, I tried to change the default for metis USE flag from my former `(+)` to `(-)`, because `cholmod-2.1.2` has the flag unset by default. But this will pull in `=sci-libs/cholmod-2.1.2 metis` instead of using the current 3.0.13 which is pulled in with a default of `(+)`. Any idea what's causing this and how I could resolve it?

**Comment by a17r** [comment]
> One question, I tried to change the default for metis USE flag from my former `(+)` to `(-)`, because `cholmod-2.1.2` has the flag unset by default.

That is not what `(+)` and `(-)` do. They are here to tell portage what to expect from a dependency version *without* that use flag (feature present or not).

**Comment by waebbl** [comment]
> > One question, I tried to change the default for metis USE flag from my former `(+)` to `(-)`, because `cholmod-2.1.2` has the flag unset by default.
> 
> That is not what `(+)` and `(-)` do. They are here to tell portage what to expect from a dependency version _without_ that use flag (feature present or not).
> 

I know that, my question is, why does `(+)` pulls in the latest release correctly, while `(-)` tries to pull in `cholmod-2.1.2` and produces a dependency conflict? I want to change from `(+)` to `(-)`, because `cholmod-2.1.2` doesn't have the flag set by default, so, in my opinion it's more reasonable to expect it unset.

**Comment by a17r** [comment]
> I know that, my question is, ...

No, I'm not sure you got it. ;) There is no choice between those two. Either `(+)` or `(-)` is right, and the other setting wrong.

`sci-libs/cholmod[ceres(+)]` will let you upgrade to cholmod-3.0.13 because portage assumes to feature denoted by the use flag is incorporated into that version.
`sci-libs/cholmod[ceres(-)]` won't let you upgrade because with 3.0.13 missing that flag, portage assumes the version is missing that feature.

**Comment by waebbl** [comment]
> > I know that, my question is, ...
> 
> No, I'm not sure you got it. ;) There is no choice between those two. Either `(+)` or `(-)` is right, and the other setting wrong.
> 

This surprises me.

> `sci-libs/cholmod[ceres(+)]` will let you upgrade to cholmod-3.0.13 because portage assumes the feature denoted by the use flag is incorporated into that version.
> `sci-libs/cholmod[ceres(-)]` won't let you upgrade because with 3.0.13 missing that flag, portage assumes the version is missing that feature.
> 

Hmm, from the PMS, I do understand this differently. Quote:

"In a 4-style use dependency, the flag name may immediately be followed by a default specified by either (+) or (-). The former indicates that, when applying the use dependency to a package that does not have the flag in question in IUSE_REFERENCEABLE, the package manager shall behave as if the flag were present and enabled; the latter, present and disabled."

I interpret this as follows: if I use `sci-libs/cholmod[metis(+)]` and cholmod doesn't have a metis USE flag, then portage assumes, it has the flag and it is set. If I use `sci-libs/cholmod[metis(-)]` and cholmod doesn't have a metis USE flag, then portage assumes it has the flag and it's disabled. It tells nothing about whether the feature described by the flag has to be actually present or not. I'm not 100% sure about how to interpret IUSE_REFERENCABLE and are using a naive approach for this term, maybe this is the point where I'm getting stuck.

An example to illustrate my POV. Let's assume package `foo/bar-1` exposes a feature via a cmake option called `flag`. A later version `foo/bar-2` doesn't expose this option any longer. This can mean two things:
- the feature denoted by this option has become mandatory and is always built
- the feature has been removed

Let's further assume, package `bar/foo-1` rdepends on `foo/bar` like `>=foo/bar-1[flag]`. When updating the ebuild `bar/foo-1` a dependency of `>=foo/bar-1[flag(+)]` would mean, that portage should assume, the first option is true, a setting of `>=foo/bar-1[flag(-}]` would mean, portage should assume the latter option is true. Which option is actually true, is still unanswered.

> Whether the flag is default enabled or not on cholmod does not matter here.

This is clear, I was just thinking it's more **reasonable** to use the other, i.e. `(-)` case, as it would mirror the default setting.

**Comment by waebbl** [comment]
> > This is clear, I was just thinking it's more reasonable to use the other, i.e. (-) case, as it would mirror the default setting.
> 
> But the use of `(+)` vs `(-)` doesn't have anything to do with defaults. It has everything to do with whether the feature controlled by the USE flag is enabled in versions of the package that do not have the USE flag.
> 
> I'm confused why you're confused :)

:D 
Well, a minus looks very much like 'unset' and a plus very much like 'set'. So when the default is unset, I would use the `(-)` and when the default is set, I would use the `(+)`, independently whether these two things have anything to do with each other or not. This was due to how I understood the 4-style-use-dependencies until now.

Thanks @dwfreed this makes things much more clear. For case 4, how will the package manager decide if dependency is not satisfied but there are two packages, one which applies for case 1 and the other for case 2? Which one will it choose?

**Comment by dwfreed** [comment]
That part is not defined by PMS; portage usually will use the package that case 1 applies to, and if the other package (the one that case 2 applies to) is a newer version, complain that it can't be used until USE flags are updated to meet the dependency.

**Comment by waebbl** [comment]
Ok, tnanks you!

**Comment by mattst88** [comment]
> > > This is clear, I was just thinking it's more reasonable to use the other, i.e. (-) case, as it would mirror the default setting.
> > 
> > 
> > But the use of `(+)` vs `(-)` doesn't have anything to do with defaults. It has everything to do with whether the feature controlled by the USE flag is enabled in versions of the package that do not have the USE flag.
> > I'm confused why you're confused :)
> 
> :D
> Well, a minus looks very much like 'unset' and a plus very much like 'set'. So when the default is unset, I would use the `(-)` and when the default is set, I would use the `(+)`, independently whether these two things have anything to do with each other or not. This was due to how I understood the 4-style-use-dependencies until now.

But... you even said this:

> I interpret this as follows: if I use sci-libs/cholmod[metis(+)] and cholmod doesn't have a metis USE flag, then portage assumes, it has the flag and it is set

/me sighs

**Comment by waebbl** [comment]
> > Well, a minus looks very much like 'unset' and a plus very much like 'set'. So when the default is unset, I would use the `(-)` and when the default is set, I would use the `(+)`, independently whether these two things have anything to do with each other or not. This was due to how I understood the 4-style-use-dependencies until now.
> 
This quote only refers to IUSE and it's default values.
 
> But... you even said this:
> 
> > I interpret this as follows: if I use sci-libs/cholmod[metis(+)] and cholmod doesn't have a metis USE flag, then portage assumes, it has the flag and it is set
> 
> /me sighs

This one is my understanding of PMS on how portage handles the `(+)` and `(-)`.

They are completely independent concepts and not related in any way and never were.

**Pull request closed without merging**
