### PR TITLE
Fixes `Service 'epmd' needs non existent service 'net.lo'`

### PR DESCRIPTION
**Pull request by ignamartinoli**
I personally don't have `netifrc`. I manage all my networking from `iwd`, hence I don't have `net.lo` files.
Every time the cache reloads (for example when I run `rc-service bluetooth restart`) I received the message ``Service `epmd' needs non existent service `net.lo'``. I discussed it with [this](https://forums.gentoo.org/viewtopic-t-1152539-highlight-.html) Gentoo Forum post and applied it to my machine, it worked.
So to standardize `epmd`, this PR make it search for a `loopback` interface instead of `net.lo`.

It's my first ever commit, so check it out, I really hope I did it well. :-)

It should fix [this](https://bugs.gentoo.org/857099) bug.

### CODE REVIEW

**Comment by ignamartinoli** [comment]
It should fix this bug: https://bugs.gentoo.org/857099

**Comment by thesamesam** [comment]
Hi & welcome!

1. Could you squash the two commits into one?
2. Could you include your signoff in the commit (see the bot's message)? `git commit -s` can do this.
3. In the commit, as a trailer, add 'Closes: https://bugs.gentoo.org/857099'.

The final commit message overall should look something like:
```
dev-lang/erlang: fix localhost dependency in init script

net.lo only exists if using netifrc.

Closes: https://bugs.gentoo.org/857099
Signed-off-by: Foo Bar <foo@example.com>
```

4. Now, for the nitty ebuild bits, the change looks good by itself! We do need to revbump to make sure this change gets out to users though, because it affects the installed files (and IMO the bug is quite bad). See https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html.

I would, tbh, just `git mv` each of the existing ebuilds up by one revision, given this is an uncontroversial fix.

**Comment by ignamartinoli** [comment]
Alright @thesamesam, that's a little bit foreign to me, but I will look up how to do those 4 things (I'm really new to all this hehe)

**Comment by thesamesam** [comment]
> Alright @thesamesam, that's a little bit foreign to me, but I will look up how to do those 4 things (I'm really new to all this hehe)

No worries at all! If you need more detail on a point, just let me know and I can give it (it's hard to know what level of detail to default to sometimes).

**Comment by ignamartinoli** [comment]
Emm, @thesamesam, I need help :'/
Let's begin with the first point: squashing
I did all this from the GitHub web interface and I can't find the squashing option. Do you know where it should be located?
(I'm really bad at using `git`)

**Comment by thesamesam** [comment]
I'm not sure if the github website will let you squash. I think we might need to embrace `git` on the command line. github's clients (like GUIs) might actually let you do this too.

By the way, if at any point this is a bit much, I can handle the git stuff. But I don't think you'll regret trying!

1. Fork gentoo.git (go to https://github.com/gentoo/gentoo, press "Fork")
2. `mkdir -p ~/git && cd ~/git && git clone https://github.com/gentoo/gentoo`
3. `cd ~/git/gentoo && git remote add fork https://github.com/ignamartinoli/gentoo`. At this point, you now have a clone of our repository, and your `git` knows about two places. The main Gentoo repo (`origin`) and your fork (`fork` - we could pick a different name. I call mine `sam`).
4. `git checkout -b fix-erlang-service`
5. Make your changes in `dev-lang/erlang` (edit the service files again) and `git add files/`
6. `git mv erlang-23.3.4.12.ebuild erlang-23.3.4.12-r1.ebuild` etc (for all of the existing ones)
7. For now, I won't expose you to `pkgdev commit`, so try `git commit -s`, and write in the commit message like I gave above.
8. `git push fork fix-erlang-service`
9. Done, maybe?

**Comment by MatthewGentoo** [comment]
Sam's instructions should get you there, but if you get stuck or would like any extra help, please feel free to join [#gentoo-proxy-maint](https://web.libera.chat/?nick=%20ignamartinoli?#gentoo-proxy-maint) or #gentoo-dev-help on Libera :)

**Comment by ignamartinoli** [comment]
@thesamesam Thanks Sam for taking the time to help me, your post taught me a lot about `git`!
I followed through every step successfully. There is something more that I can do? :)

**Comment by thesamesam** [comment]
So glad to hear it! I forgot one last step: https://github.com/gentoo/gentoo/compare and make a new pull request from your fork & branch to here. (It'll make a new PR, separate from this one.)

**Comment by ignamartinoli** [comment]
Thanks @thesamesam, this is the new PR: https://github.com/gentoo/gentoo/pull/26303

**Pull request closed without merging**
