### PR TITLE
profiles/package.mask: mask sci-libs/{blas,cblas,lapack}

### PR DESCRIPTION
**Pull request by epsilon-0**
Signed-off-by: Aisha Tammy <gentoo@aisha.cc>

### CODE REVIEW

**Comment by rossbridger** [comment]
Doesn't this collide with https://github.com/gentoo/gentoo/pull/17836?

**Comment by epsilon-0** [comment]
@rossbridger 
yea this is being done earlier so that people can have time to prepare.
then we will do the removal later.

**Comment by epsilon-0** [comment]
@SoapGentoo here it is

**Review by SoapGentoo — APPROVED** [review]

**Comment by SoapGentoo** [comment]
@epsilon-0 could you rebase this commit pls?

**Pull request closed without merging**
