### PR TITLE
x11-misc/gtkdialog: request for not treeclean: supports gtk-3. standalone application

### PR DESCRIPTION
**Pull request by mazes-80**
> # Matt Turner <mattst88@gentoo.org> (2022-10-14)
> # Unmaintained upstream with last commit in 2013.
As suggested chatting on IRC, I may end up modernizing this piece of code and provide support for gtk:4

> No reverse dependencies.

This is also a standalone app. I use it in combination with dialog, so I can test remotely everthing works ok using classic dialog, the distant user just sees a graphical interface. zenity, which seems standard for those fast front end now,  does not allow match dialog syntax. Also it as bunch of extra dependencies that may be a bit overkill for the distant host, a raspberry can do it, but for this one, storage is dedicated to astronomical datas and images provided by the controlled telescope.

> # Depends on unmaintained packages:
> #       - x11-libs/gtk+:2
> #       - x11-libs/vte:0
Those dependencies are only optional if you want to compile with gtk2 instead of default gtk3

This PR drops gtk-2 support and modernize a bit the ebuild.

### CODE REVIEW

**Comment by mgorny** [comment]
CC @mattst88

**Review by mattst88 — CHANGES_REQUESTED** [review]
I'm okay with this, but the commit needs your S-o-b tag.

**Comment by mattst88** [comment]
> I'm okay with this, but the commit needs your S-o-b tag.

Still need this. Still planning to remove the package otherwise...

**Comment by mazes-80** [comment]
Le Tue, 25 Oct 2022 08:38:56 -0700,
Matt Turner ***@***.***> a écrit :

> > I'm okay with this, but the commit needs your S-o-b tag.  
> 
> Still need this. Still planning to remove the package otherwise...
> 

I always forget signing. I'll force push with signing friday evening,
busy until

**Comment by mazes-80** [comment]
Added signoff

**Pull request closed without merging**
