### PR TITLE
removed link to advertising homepage, fix #507900

### PR DESCRIPTION
**Pull request by jonasstein**
https://bugs.gentoo.org/show_bug.cgi?id=507900

### CODE REVIEW

**Comment by gktrk** [comment]
The deeper issue here is the sources are not available in SRC_URI anymore. We only host it in our mirrors apparently.

**Comment by gktrk** [comment]
http://www.antitachyon.com/Content/10_Produkte/50_Utilities.html still lists psmark

**Comment by jonasstein** [comment]
@gktrk nice catch. I contact them concerning the source

**Comment by monsieurp** [comment]
The commit format is incorrect. Please follow read our guidelines: https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format. Thanks.

**Comment by monsieurp** [comment]
ping?

**Comment by monsieurp** [comment]
ping!?

**Pull request closed without merging**
