### PR TITLE
dev-python/{ipython,matplotlib,numpy}: pypy3 support

### PR DESCRIPTION
**Pull request by tgbugs**
This PR pulls in all the changes needed to dependencies to add pypy3
support to ipython. Currently only the matplotlib use flag works under
pypy3, pypy3 support for nbconvert and notebook use flags has not been
implemented yet.

Also included is pypy3 support for numpy.

Closes: https://bugs.gentoo.org/729958

Supersedes:
https://github.com/gentoo/gentoo/pull/16453
https://github.com/gentoo/gentoo/pull/16454
https://github.com/gentoo/gentoo/pull/16456
https://github.com/gentoo/gentoo/pull/16457
https://github.com/gentoo/gentoo/pull/16458
https://github.com/gentoo/gentoo/pull/16462

### CODE REVIEW

**Comment by tgbugs** [comment]
This is still missing a few dependencies such as ipykernel, and I suspect that ipython itself will trigger https://bugs.gentoo.org/465546

**Comment by tgbugs** [comment]
And indeed as expected.
```
 * ERROR: dev-python/ipython-7.15.0::local failed (install phase):
 *   Package installs 'share' in PyPy prefix, see bug #465546.
 * 
 * Call stack:
 *     ebuild.sh, line  125:  Called src_install
 *   environment, line 3180:  Called distutils-r1_src_install
 *   environment, line 1342:  Called _distutils-r1_run_foreach_impl 'python_install'
 *   environment, line  551:  Called python_foreach_impl 'distutils-r1_run_phase' 'python_install'
 *   environment, line 2778:  Called multibuild_foreach_variant '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_install'
 *   environment, line 2218:  Called _multibuild_run '_python_multibuild_wrapper' 'distutils-r1_run_phase' 'python_install'
 *   environment, line 2216:  Called _python_multibuild_wrapper 'distutils-r1_run_phase' 'python_install'
 *   environment, line  963:  Called distutils-r1_run_phase 'python_install'
 *   environment, line 1312:  Called python_install
 *   environment, line 2932:  Called distutils-r1_python_install
 *   environment, line 1240:  Called die
 * The specific snippet of code:
 *           die "Package installs 'share' in PyPy prefix, see bug #465546.";
```

**Comment by mgorny** [comment]
If that's of any help, you can use `gpy-impl` from gpyutils to edit PYTHON_COMPAT without having to tediously update it yourself.

**Comment by mgorny** [comment]
I presume you're using the newest version of PyPy3, correct? I'd guess ipython does something horrible and it fails :-(.

What's the motivation for adding pypy3 everywhere? IPython-ing with it or sth else?

**Comment by tgbugs** [comment]
Well that is a lot of unsolvable dependency errors. Looks like I will need to retest since something seems to have changed in the rest of the tree since these were originally added.

**Comment by tgbugs** [comment]
@mgorny I think that this is pretty much ready to go.

The only issues during testing are with dev-python/prompt_toolkit and dev-python/pyzmq.
I'm 99% certain that the prompt_toolkit issue is a bug in the tests, and everything seems to be ok at runtime.
I haven't noted any issues with the test failures in pyzmq, and the failures are the same as for the other
python implementations that are currently enabled.

I'm not sure what the non-solvable dependencies errors are being caused by in the QA report.

**Comment by ajakk** [comment]
Still interested in this? If so this needs an update.

**Comment by tgbugs** [comment]
Yes, and will update.

**Comment by scardracs** [comment]
@ajakk @mgorny  after 2 years no update at all, could we conseder that PR dead?

**Comment by tgbugs** [comment]
Go ahead and kill this one. I can create another one.

**Comment by scardracs** [comment]
> Go ahead and kill this one. I can create another one.

I can't do it, only you and devs can do that

**Comment by tgbugs** [comment]
I will create a new version of this that is up-to-date at some point in the future.

**Pull request closed without merging**
