### PR TITLE
media-tv/kodi-15.1 Fix emerge error "JsonSchemaBuilder: Command not found"

### PR DESCRIPTION
**Pull request by candrews**
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=558798

### CODE REVIEW

**Comment by candrews** [comment]
@vapier can you please accept this PR or tell me what's wrong so I can fix it? :)

Thanks!

**Comment by mgorny** [comment]
Is there an upstream bug report for this?

**Comment by vapier** [comment]
should be handled by commit 4a263371420a79472a74be5688a3cd706cb26d62

**Comment by vapier** [comment]
i would close this, but it doesn't look like the members list is kept in sync between the repos & organization

**Comment by vapier** [comment]
forgot to push; should be handled by commit 89417912ce79d5e1f497625ce13ed02b2003b08b

**Pull request closed without merging**
