### PR TITLE
sci-libs/vtk: update dependency on dev-python/sip, remove old

### PR DESCRIPTION
**Pull request by waebbl**
drop 8.2.0{-r{1,2}}

Use slotted dev-python/sip package
Remove obsolete commented cmake variable

Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by thesamesam** [comment]
I'd squash the second 'update dependency' commit

**Comment by waebbl** [comment]
Should I drop the `-r1` and `-r2` too then, and only push an `-r3`

**Comment by thesamesam** [comment]
I usually wimp out and do r1 -> r3 and r2 -> r4, but I don't see a point in keeping old versions around here actually, so go for it

**Comment by waebbl** [comment]
I was thinking about dropping r1 anyway, and if a revbump is needed it makes even more sense :)

**Pull request closed without merging**
