### PR TITLE
dev-libs/wlc: add missing virtual/libudev depend

### PR DESCRIPTION
**Pull request by Hummer12007**
It can cause trouble for some users: (SirCmpwn/sway#1138)
@gentoo/proxy-maint

### CODE REVIEW

**Comment by Hummer12007** [comment]
@gktrk done

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/5078355...85682d6. Thanks!

**Comment by DmitryHetman** [comment]
Still doesn't work. Same error.

**Comment by DmitryHetman** [comment]
Still doesn't work. Same error.

**Pull request closed without merging**
