### PR TITLE
{dev-python, dev-libs, dev-ros}/*: Update homepage links

### PR DESCRIPTION
**Pull request by jsmolic**
Continuing homepage cleanup:

**ROS packages:**
* `http://wiki.ros.org` -----> `https://wiki.ros.org`

### CODE REVIEW

**Comment by jsmolic** [comment]
This is rebased and ready to merge now

**Comment by jsmolic** [comment]
Hi @aballier, could you please review this pull request? I opened this a while ago to update homepages, but I keep having to rebase due to changes in ebuilds...\
Thanks, Jakov

**Comment by flappyports** [comment]
Sorry, didn't catch this in time. It needs rebased again.

**Comment by jsmolic** [comment]
@flappyports Done, thanks for taking a look

**Comment by jsmolic** [comment]
(@flappyports small ping :-) )

**Comment by jsmolic** [comment]
@thesamesam Thanks!

**Pull request closed without merging**
