### PR TITLE
net-p2p/deluge: Use /run instead of /var/run

### PR DESCRIPTION
**Pull request by anthonyryan1**
* Migrate from /sbin/runscript to /sbin/openrc-run
* Bump ebuild with new init script moving runtime data into /run
* Apply missing changes to live  ebuild
* Minor whitespace fixes

Gentoo-bug: 468340

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by anthonyryan1** [comment]
Just realized there's a possible merge conflict with #913. I would be happy to close this and rebase at a later date if that is inconvenient.

**Comment by monsieurp** [comment]
@krifisk @gentoo/proxy-maint

**Comment by monsieurp** [comment]
@anthonyryan1 I think #913 is taking precedence here over this PR.

**Comment by anthonyryan1** [comment]
I'll rebase once #913 is complete.

**Pull request closed without merging**
