### PR TITLE
app-emacs/org-mode: bump to 9.7.5

### PR DESCRIPTION
**Pull request by lima-limon-inc**
Bug: https://bugs.gentoo.org/934741

---

Please check all the boxes that apply:

- [X] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by lima-limon-inc** [comment]
Was a duplicate of: https://bugs.gentoo.org/934738

**Comment by xgqt** [comment]
please, drop & bump in separate commits

**Comment by lima-limon-inc** [comment]
> please, drop & bump in separate commits

Noted! Changed in latest commits

**Comment by xgqt** [comment]
Bot of those commits miss regenned manifests.

in drop the appropriate distfile should be gone, in bump added

**Comment by lima-limon-inc** [comment]
> Bot of those commits miss regenned manifests.
> 
> in drop the appropriate distfile should be gone, in bump added

Oh! I completely missed it. My apologies.


Thank you @xgqt for taking the time to fix it.


Have a good week!

**Pull request closed without merging**
