### PR TITLE
dev-java/icu4j: export LC_ALL for tests

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog 
I am adding `LC_ALL="C.UTF-8"` to the tests. This should solve at least one of your two failing test cases.  The other I could not even reproduce, but maybe also solved.
I also hoped to get rid of the patch but those test failures unfortunately wont go away with setting `LC_ALL`.

**Comment by fordfrog** [comment]
> @fordfrog I am adding `LC_ALL="C.UTF-8"` to the tests. This should solve at least one of your two failing test cases. The other I could not even reproduce, but maybe also solved. I also hoped to get rid of the patch but those test failures unfortunately wont go away with setting `LC_ALL`.

i think those tests expect united states settings and pacific time zone, so imo it should be this way (i didn't test it though, but it's obvious from the failures):
```
export LC_ALL="en_US.UTF-8" TZ="US/Pacific"
```
to use my environment for the tests to get the errors, you can use this:
```
export LC_ALL="cs_CZ.UTF-8" TZ="Europe/Prague"
```

**Comment by vaukai** [comment]
> > @fordfrog I am adding `LC_ALL="C.UTF-8"` to the tests. This should solve at least one of your two failing test cases. The other I could not even reproduce, but maybe also solved. I also hoped to get rid of the patch but those test failures unfortunately wont go away with setting `LC_ALL`.
> 
> i think those tests expect united states settings and pacific time zone, so imo it should be this way (i didn't test it though, but it's obvious from the failures):
> 
> ```
> export LC_ALL="en_US.UTF-8" TZ="US/Pacific"
> ```
> 
> to use my environment for the tests to get the errors, you can use this:
> 
> ```
> export LC_ALL="cs_CZ.UTF-8" TZ="Europe/Prague"
> ```

@fordfrog Thanks for the input. My main fault was forgetting about `TZ`. 
Also created `cs_CZ.UTF-8` on my system and verified that the problem should be solved.

**Comment by vaukai** [comment]
> does that make the patch obsolete?

Yes. Should have deleted

**Pull request closed without merging**
