### PR TITLE
dev-python/jupyter_console: add python-3.7

### PR DESCRIPTION
**Pull request by abecerra**
add python-3.7

Tested-by: Andrés Becerra <andres.becerra@gmail.com>
Signed-off-by: Andrés Becerra <andres.becerra@gmail.com>

### CODE REVIEW

**Comment by flappyports** [comment]
@abecerra , please Sign-off on the commit as this is a requirement. You can feel free to add both "Tested-by" and "Signed-off-by".

**Comment by abecerra** [comment]
> @abecerra , please Sign-off on the commit as this is a requirement. You can feel free to add both "Tested-by" and "Signed-off-by".

@flappyports I think I signed off the commit by adding my public gpg key to github settings.

**Comment by flappyports** [comment]
@abecerra you have to add "Signed-off-by" in the commit msg. e.g. 'git commit -s'

**Comment by abecerra** [comment]
> @abecerra you have to add "Signed-off-by" in the commit msg. e.g. 'git commit -s'

I think I did it correctly this time.

**Pull request closed without merging**
