### PR TITLE
app-cdr/cdw: EAPI=7 bump

### PR DESCRIPTION
**Pull request by arthurzam**
- `EAPI=7` bump
- fix dependency on `dev-libs/libcdio` - need to rebuild on sub-SLOT change.
- updated both live version and regular version (bumped `r0 -> r1`)

### CODE REVIEW

**Comment by mgorny** [comment]
Would you be interested in becoming the maintainer for this package?

**Comment by arthurzam** [comment]
@mgorny Yes, will be glad.
Should I just add myself as a proxy-maintainer in `metadata.xml`?

**Comment by mgorny** [comment]
Please do. Also please verify the license in case you didn't do that, https://devmanual.gentoo.org/general-concepts/licenses/index.html#gpl-x-vs-gpl-x+

**Comment by arthurzam** [comment]
@mgorny Thank you - have done all.
Found out it was really `GPL-2+` as you suspected. Added the third commit to fix the stable ebuild.
Added a new commit setting myself in `metadata.xml`

**Comment by mgorny** [comment]
Thanks a lot. I'm going to reorder the commit a bit to have license change first, since all the remaining commits already have the correct license.

**Pull request closed without merging**
