### PR TITLE
dev-libs/imath: drop 3.1.5

### PR DESCRIPTION
**Pull request by waebbl**
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by scardracs** [comment]
You should have to drop media-libs/openexr-3.1.5-r1 but unfortunately it's the latest release

**Comment by waebbl** [comment]
> You should have to drop media-libs/openexr-3.1.5{,-r1} but unfortunately they are the latest releases

I know, not -r1, but openexr-3.1.5. But it seems like -r1 hasn't been stabilized for x86, despite the bug in #890445 is telling so.

**Comment by dlan17** [comment]
> > You should have to drop media-libs/openexr-3.1.5{,-r1} but unfortunately they are the latest releases
> 
> I know, not -r1, but openexr-3.1.5. But it seems like -r1 hasn't been stabilized for x86, despite the bug in #890445 is telling so.

x86 stabilization fixed in tree, let me know if you want to drop openexr-3.1.5? you can either ping me in IRC or send a PR (if you want)

**Comment by waebbl** [comment]
I'm a little confused now. The package breaks the tree and yet get's merged? I was planning on adding openexr-3.1.5 drop to this PR, but will now open a new one for it. Think I have to be really quick in setting draft mode if such happens in the future :)

**Comment by scardracs** [comment]
> I'm a little confused now. The package breaks the tree and yet get's merged? I was planning on adding openexr-3.1.5 drop to this PR, but will now open a new one for it. Think I have to be really quick in setting draft mode if such happens in the future :)

@dlan17 managed to fix it on tree before the merge :)

**Comment by thesamesam** [comment]
They committed:
```
  1 commit f324f03a1190c04e0e51b810df2d3dde82a13917
  2 Author: Yixun Lan <dlan@gentoo.org>
  3 Date:   Fri Jan 13 08:19:06 2023 +0800
  4
  5     media-libs/openexr: drop 3.1.5
  6
  7     this is necessary after dev-libs/imath-3.1.5 dropped
  8
  9     Signed-off-by: Yixun Lan <dlan@gentoo.org>
 10
```

**Comment by waebbl** [comment]
TBH, I don't understand the urgency in this. Wouldn't there be time to wait for the maintainer to fix it? I'm usually quite responsive on GitHub.
Thanks for taking 'care' of this, I think.

**Comment by scardracs** [comment]
> TBH, I don't understand the urgency in this. Wouldn't there be time to wait for the maintainer to fix it? I'm usually quite responsive on GitHub.
> 
> Thanks for taking 'care' of this, I think.

I have no answer about that. Sometimes PRs stays here for days/weeks/months/years and sometimes they are merged asap.

**Comment by thesamesam** [comment]
> TBH, I don't understand the urgency in this. Wouldn't there be time to wait for the maintainer to fix it? I'm usually quite responsive on GitHub. Thanks for taking 'care' of this, I think.

This comes across as a bit sarcastic but I hope it wasn't meant that way. @dlan is new to helping out with proxy maint and he's learning the ropes. I suspect he was trying to be helpful by not making you go through another ping/pong to get your change in.

**Comment by juippis** [comment]
Sometimes it's faster for **everyone** to make these (small) fixes on our side. If there's a compilation failure that's not obvious, I prefer to let the author fix it since most likely it requires a deeper dive to the project, and the maintainer is hopefully more involved with the project having a better clue about the issue, allowing me to spend time reviewing other PRs. 

Some obvious compilation issues, like missing deps, I also fix while merging the PR. 

So you just make a decision how everyone involved has to spend the least amount of time to get the contribution in :)

**Comment by waebbl** [comment]
> meant

I'm sorry to say that, but the last sentence was meant sarcastic. I'm happy if new people join us and help out, but the certain circumstances on this makes me feel like if wasn't actually helping me (although it did, because I no longer need to take care of dropping the version) but was a frustrating experience. Usually I'm also ok if reviewers change simple things, like juippis said.
I was awaiting a response from Sam on IRC to decide whether I can just add the openexr-3.1.5 to this PR or have to wait until the x86 stabilization has been done. While I was awake, Sam couldn't answer my question and the answer from [dlan](https://github.com/gentoo/gentoo/pull/29081#issuecomment-1381137749) came while I was already sleeping. This morning when I was checking, all was set and done and control of this completely stripped off of me. Why telling me, I can open a new PR for dropping openexr, when it's being done a few minutes later anyway?
I apologize to dlan for being sarcastic in this. Still, I think it would have been a good move to wait for a reaction on the message.

**Pull request closed without merging**
