### PR TITLE
net-mail/dbmail: Migrate to /run and EAPI 6

### PR DESCRIPTION
**Pull request by cjmayo**
Also:
- Install man pages
- Remove sqlite USE flag
- Minor repoman fixes and other tidy-ups

Gentoo-Bug: https://bugs.gentoo.org/529504
Gentoo-Bug: https://bugs.gentoo.org/529506

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. Looks good. Could you append a `|| die` call to the end of each sed call?

**Comment by cjmayo** [comment]
die's added.

**Comment by cjmayo** [comment]
Got rid of the commented out:
```
#sed -i -e "s:#library_directory:library_directory:" dbmail.conf || die
```
it's mentioned in pkg_postinst anyway.

There are comments about updating the init scripts upstream. Seems like a good idea. There's no explicit copyright or licence on them though. Can I submit them?

**Comment by LordVan** [comment]
commited f3ab3bb6a36ea856741f7cd294beefcb4b04b1d1

**Pull request closed without merging**
