### PR TITLE
dev-lang/spidermonkey: add ARCH=riscv support

### PR DESCRIPTION
**Pull request by dlan17**
for now, these patches only support riscv64/lp64d

0008-riscv64-generic-support.patch took from upstream [1]
0009-riscv64-rust-fix.patch took from debian's repo [2]

[1] https://bugzilla.mozilla.org/show_bug.cgi?id=1318905
[2] https://salsa.debian.org/gnome-team/mozjs/-/blob/debian/78/master/debian/patches/Add-riscv64-support.patch

Bug: https://bugs.gentoo.org/781137
Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Yixun Lan <dlan@gentoo.org>

### CODE REVIEW

**Comment by dlan17** [comment]
@gentoo/mozilla 
hi guys, please help review, this PR try to add ARCH=riscv support, current only riscv64/lp64d is enabled

patch 0008 from upstream [1], patch 0009 from debian's repo [2]

Note: I've manually created the patch tarballs [3], not sure if the strict "git format-patch" way is required or not,
feel free to help (adjust the tarball or ebuild), thanks

[1] https://dev.gentoo.org/~dlan/mozilla/patchsets/0008-riscv64-generic-support.patch
[2] https://dev.gentoo.org/~dlan/mozilla/patchsets/0009-riscv64-rust-fix.patch
[3] https://dev.gentoo.org/~dlan/mozilla/patchsets/spidermonkey-78-patches-04.tar.xz

**Comment by stefson** [comment]
can you please state what the CHOST of the cross-gcc compiler is, and what the rust target is called? I may jump in and test this with cross compile, and need this information for bootstrapping the rust cross toolchain. Thanks.

**Comment by dlan17** [comment]
> can you please state what the CHOST of the cross-gcc compiler is, and what the rust target is called? I may jump in and test this with cross compile, and need this information for bootstrapping the rust cross toolchain. Thanks.

I don't do cross compiling, but instead, doing native compiling on Gentoo RISC-V machine

**Comment by Whissi** [comment]
I'll review in next days, thank you.
I added "do not merge" because we have to integrate this in our patch set currently maintained at https://github.com/Whissi/gentoo-mozilla.

**Comment by dlan17** [comment]
> I'll review in next days, thank you.
@Whissi 
thanks for review, feel free to amend the patches, add commit message (which I haven't maintained it using patch set)
also you can revert the change to PATCH_URIS once you have new patch tarball generated

**Pull request closed without merging**
