### PR TITLE
dev-libs/libthreadar: bump to v1.3.2

### PR DESCRIPTION
**Pull request by ceamac**
Minor bugfix release

### CODE REVIEW

**Comment by thesamesam** [comment]
Note that we should stabilise a newer version of dar soon. If we clean up the old version here, we're kind of delaying that. Should I drop the cleanup?

**Comment by ceamac** [comment]
Sure, if it helps with new stable version let's keep two versions

**Comment by thesamesam** [comment]
Thanks for the quick reply!

**Comment by ceamac** [comment]
Thank you for the quick review :)

**Comment by thesamesam** [comment]
https://github.com/gentoo/gentoo/commit/ec743ec9bd3fb29375403ba2392516e33d0842cf

**Pull request closed without merging**
