### PR TITLE
dev-java/openjdk: add 23_p37

### PR DESCRIPTION
**Pull request by vaukai**
needs help on `dev-java/openjdk-23_p37`:
```
/var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/src/java.desktop/share/native/libfontmanager/HBShaper_Panama.c:27:10: fatal error: hb.h: No such file or directory
   27 | #include "hb.h"
      |          ^~~~~~
compilation terminated.
+ exitcode=1
+ /bin/cp /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/support/native/java.desktop/libfontmanager/HBShaper_Panama.o.log /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/make-support/failure-logs/support_native_java.desktop_libfontmanager_HBShaper_Panama.o.log
+ /bin/cp /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/support/native/java.desktop/libfontmanager/HBShaper_Panama.o.cmdline /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/make-support/failure-logs/support_native_java.desktop_libfontmanager_HBShaper_Panama.o.cmdline
+ exit 1
/var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/src/java.desktop/share/native/libfontmanager/HBShaper.c:28:10: fatal error: hb.h: No such file or directory
   28 | #include "hb.h"
      |          ^~~~~~
compilation terminated.
```

Both `Java 23` and `Java 24` do not have LTS and are not forseen to get keyworded or even stabilized.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Review by fordfrog — APPROVED** [review]

**Comment by fordfrog** [comment]
merged everything except wip

**Comment by fordfrog** [comment]
> needs help on `dev-java/openjdk-23_p37`:
> 
> ```
> /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/src/java.desktop/share/native/libfontmanager/HBShaper_Panama.c:27:10: fatal error: hb.h: No such file or directory
>    27 | #include "hb.h"
>       |          ^~~~~~
> compilation terminated.
> + exitcode=1
> + /bin/cp /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/support/native/java.desktop/libfontmanager/HBShaper_Panama.o.log /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/make-support/failure-logs/support_native_java.desktop_libfontmanager_HBShaper_Panama.o.log
> + /bin/cp /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/support/native/java.desktop/libfontmanager/HBShaper_Panama.o.cmdline /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/build/linux-x86_64-server-release/make-support/failure-logs/support_native_java.desktop_libfontmanager_HBShaper_Panama.o.cmdline
> + exit 1
> /var/tmp/portage/dev-java/openjdk-23_p37/work/jdk23u-jdk-23-ga/src/java.desktop/share/native/libfontmanager/HBShaper.c:28:10: fatal error: hb.h: No such file or directory
>    28 | #include "hb.h"
>       |          ^~~~~~
> compilation terminated.
> ```
> 
> Both `Java 23` and `Java 24` do not have LTS and are not forseen to get keyworded or even stabilized.

this is probably a header file from harfbuzz. you might want to change the line to `#include <hb.h>`.

**Comment by hhoffstaette** [comment]
> this is probably a header file from harfbuzz. you might want to change the line to `#include <hb.h>`.

Good idea, but not enough. My first attempt was to fix all `"hb_whatever.h"` includes to `<harfbuzz/hb_whatever.h>` and that made it build, so obviously it should have added `-I/usr/include/harfbuzz` somewhere. In theory it did, since the generated `build/linux-x86_64-server-release/spec.gmk` contains:
```
USE_EXTERNAL_HARFBUZZ := true
HARFBUZZ_CFLAGS := -I/usr/include/harfbuzz -I/usr/include/freetype2 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include
HARFBUZZ_LIBS := -lharfbuzz
```

..but in practice it did **not**, since `make/modules/java.desktop/lib/ClientLibraries.gmk` straight up forgot to add `HARFBUZZ_CFLAGS` in the case of external harfbuzz. You can verify this by e.g. touching HBShaper.c and inspecting the executed command line, where the required `-I/usr/include/harfbuzz` is simply missing.

The following patch makes it work:
```
--- jdk23u-jdk-23-ga/make/modules/java.desktop/lib/ClientLibraries.gmk~	2024-08-20 17:57:04.000000000 +0200
+++ jdk23u-jdk-23-ga/make/modules/java.desktop/lib/ClientLibraries.gmk	2024-09-20 10:00:52.460817053 +0200
@@ -279,6 +279,7 @@ endif
 ################################################################################
 
 ifeq ($(USE_EXTERNAL_HARFBUZZ), true)
+   LIBFONTMANAGER_CFLAGS += $(HARFBUZZ_CFLAGS)
    LIBFONTMANAGER_EXTRA_SRC =
    LIBFONTMANAGER_LIBS += $(HARFBUZZ_LIBS)
 else

```

**Comment by fordfrog** [comment]
@vaukai as we don't have `openjfk:23`, the use flag should be masked to prevent any emerge issues.

**Comment by vaukai** [comment]
> @vaukai as we don't have `openjfk:23`, the use flag should be masked to prevent any emerge issues.

i will do that late tonight or tomorrow. also the other version except `8` are causing `pkgcheck` to complain.

**Comment by fordfrog** [comment]
> > @vaukai as we don't have `openjfk:23`, the use flag should be masked to prevent any emerge issues.
> 
> i will do that late tonight or tomorrow. also the other version except `8` are causing `pkgcheck` to complain.

yes, but this version doesn't have the use flag masked so when it is enabled, the emerge doesn't even start.

**Pull request closed without merging**
