### PR TITLE
dev-util/intel-graphics-compiler: put the package version into cmake configuration

### PR DESCRIPTION
**Pull request by vmustya**

### CODE REVIEW

**Comment by ConiKost** [comment]
Could you explain for me, where that version information is being shown or used?

**Comment by vmustya** [comment]
> Could you explain for me, where that version information is being shown or used?

Currently the major and minor version numbers really matter, because they define IGC API version. The build version number is used only as a shared library suffix like `libigc.so.1.0.12504`. However, it may be useful when a user reports a functional IGC bug.

**Comment by janhenke** [comment]
> > Could you explain for me, where that version information is being shown or used?
> 
> Currently the major and minor version numbers really matter, because they define IGC API version. The build version number is used only as a shared library suffix like `libigc.so.1.0.12504`. However, it may be useful when a user reports a functional IGC bug.

Could you please open an upstream bug in that case? I do not see it as a packaging issue, but something upstream should address themselves in their build system.

**Comment by vmustya** [comment]
> Could you please open an upstream bug in that case? I do not see it as a packaging issue, but something upstream should address themselves in their build system.

I'm the upstream developer, and I don't really see IGC bugs here. It's just a kind of design, where the package/SO version is only configured by build system. So we don't push it into IGC repo.

**Comment by janhenke** [comment]
> > Could you please open an upstream bug in that case? I do not see it as a packaging issue, but something upstream should address themselves in their build system.
> 
> I'm the upstream developer, and I don't really see IGC bugs here. It's just a kind of design, where the package/SO version is only configured by build system. So we don't push it into IGC repo.

So every distro has to do it themselves? Why don't you set these variables inside the CMakeSources.txt? Again, I do not think our build system is the right place for what you are trying to archive. Either the upstream build system sets the version themselves, or it is not needed. In case of big reports, it does not matter what is in die CMake files, the version is already included in the build log via the package name.

**Comment by vmustya** [comment]
> So every distro has to do it themselves?
Yes

> Why don't you set these variables inside the CMakeSources.txt? Again, I do not think our build system is the right place for what you are trying to archive. Either the upstream build system sets the version themselves, or it is not needed. In case of big reports, it does not matter what is in die CMake files, the version is already included in the build log via the package name.

The major and minor version numbers are assigned manually, so they are pushed into upstream cmake file. However, the build/patch number is assigned by CI, so it cannot be committed into the repo.

Actually this change is just nice-to-have for IGC. However, we have similar issue for NEO runtime (dev-libs/intel-compute-runtime), which has version numbers like `YY.WW.RRRRR`, where YY is year, WW is week and RRRRR is a revision number. This version is available for uses thru OpenCL and LevelZero API calls:
```
$ clinfo
...
Number of devices                                 1
  Device Name                                     Intel(R) Graphics [0x56a5]
  Device Vendor                                   Intel(R) Corporation
  Device Vendor ID                                0x8086
  Device Version                                  OpenCL 3.0 NEO 
  Device UUID                                     86800000-a556-0000-0000-000000000000
  Driver UUID                                     32322e35-312e-3032-3531-343200000000
  Valid Device LUID                               No
  Device LUID                                     10ce-2885fd7f0000
  Device Node Mask                                0
  Device Numeric Version                          0xc00000 (3.0.0)
  Driver Version                                  22.43.024558
...
```

**Comment by janhenke** [comment]
Sorry, the more you tell me, the more I get the feeling your change is completely the wrong thing to do and even downright a dangerous thing to do.

To reiterate: Distribution packaging is not the place to assign version numbers into the code. If we assign a version number as part of the packaging, that must be up to our own choice what exactly we put there. I.e. if we as distro want to distinguish something.

If you, as software authors assign a version number, it is your job to set it in the build system and/or source code. Under no circumstance it is correct to set these via external input during building. Your software must work correctly in the default configuration, i.e. without any external input.

Also as a side note: I find it strange that you expect every distro out there to package your software exactly according your wishes. Besides what happens if someone checks out your repository and builds it?

I strongly feel this PR should not be merged and you need an upstream solution. Aside, I am still not sure what exact problem you are trying to solve? Maybe this is an instance of an x for y problem. I am also certain that others already faced a similar problem and found a solution without any external input.

**Comment by SoapGentoo** [comment]
I completely agree with @janhenke here, this makes absolutely no sense from a packaging point of view. My guess is that you want something similar to what GNU software does:

    $ cp --version
    cp (GNU coreutils) 9.1
    Packaged by Gentoo (9.1-r2 (p0))

i.e. you want to know that when a user reports a bug, it's from Gentoo with some modifications (which you can then look up).

I mean, do you want to go around 300 Linux distros and add this admittedly brittle versioning code outside the build system? I don't see how you expect this to scale, because I can't see it scale.

**Comment by sarnex** [comment]
@vmustya Hey! I didn't know you used Gentoo!

As the vulkan/spirv mantainer I agree with the above takes as well, you can ping me internally when I'm back next week if you want to brainstorm

**Comment by ConiKost** [comment]
Closing.

**Pull request closed without merging**
