### PR TITLE
profiles: add experimental riscv64-lp64 musl profile

### PR DESCRIPTION
**Pull request by blueness**
Signed-off-by: Anthony G. Basile <blueness@gentoo.org>

### CODE REVIEW

**Comment by blueness** [comment]
The profile stack for default/linux/riscv/20.0/rv64gc/lp64d/musl which is currently in the tree  is 
/var/db/repos/gentoo/profiles/base
/var/db/repos/gentoo/profiles/default/linux
/var/db/repos/gentoo/profiles/arch/base
/var/db/repos/gentoo/profiles/arch/riscv
/var/db/repos/gentoo/profiles/default/linux/riscv
/var/db/repos/gentoo/profiles/releases
/var/db/repos/gentoo/profiles/releases/17.0
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc
/var/db/repos/gentoo/profiles/arch/riscv/rv64gc/lp64d
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc/lp64d
/var/db/repos/gentoo/profiles/features/musl
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc/lp64d/musl

The profile stack for the proposed profile in this PR default/linux/riscv/20.0/rv64gc/lp64/musl is
/var/db/repos/gentoo/profiles/base
/var/db/repos/gentoo/profiles/default/linux
/var/db/repos/gentoo/profiles/arch/base
/var/db/repos/gentoo/profiles/arch/riscv
/var/db/repos/gentoo/profiles/default/linux/riscv
/var/db/repos/gentoo/profiles/releases
/var/db/repos/gentoo/profiles/releases/17.0
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc
/var/db/repos/gentoo/profiles/arch/riscv/rv64gc/lp64
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc/lp64
/var/db/repos/gentoo/profiles/features/musl
/var/db/repos/gentoo/profiles/default/linux/riscv/20.0/rv64gc/lp64/musl

Carefully notice that they are identical except lp64d -> lp64.

So far testing lookings good.  I just want a second pair of eyes in case I missed something.

**Review by akhuettel — APPROVED** [review]

**Review by thesamesam — APPROVED** [review]
Nice!

**Comment by dlan17** [comment]
great job! thanks!

**Review by dlan17 — APPROVED** [review]

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
