### PR TITLE
x11-libs/gdk-pixbuf: Bump to 2.42.12

### PR DESCRIPTION
**Pull request by flint2**
x11-libs/gdk-pixbuf: Bump to 2.42.12

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [X] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [X] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [X] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by leio** [comment]
What about gif support? What about `ani`, `bmp`, `icns`, `ico`, `pnm`, `qtif`, `tga`, `xbm` and `xpm` support?
These are basic meson_options.txt diffing results on there being new options. You really really need to spot these while doing bumps.

**Comment by flint2** [comment]
> What about gif support? What about `ani`, `bmp`, `icns`, `ico`, `pnm`, `qtif`, `tga`, `xbm` and `xpm` support? These are basic meson_options.txt diffing results (between previous version and bumped to versions) showing there being new options. You really really need to spot these while doing bumps. Not being sure about `others` in regards to having support for them vs security risks of weakly maintained loaders is also why I didn't bump this long ago myself - someone needs to think about this and make a decision, probably documenting it in the git log.

Added gif and others IUSE

**Comment by pacho2** [comment]
In my opinion, as none of those flags add any new dependency, I see two options:

1. Simply enable them unconditionally, as, for example, Debian is doing. 

Looking at the formats covered by "others":
https://gitlab.gnome.org/GNOME/gdk-pixbuf/-/blob/master/meson.build?ref_type=heads#L286

Even if they are rarely used, they are still used. Hiding the support behind "others" USE flag will make their support hard to find by the users. Even if they are "weakly" maintained, I guess that, at least, regarding potential security issues, Debian people will also look at them.

2. The other option I see is to add one USE per format and append the enabled formats to the builtin_loaders configure option

**Comment by flint2** [comment]
> 2\. format

removed ` others` IUSE , build others unconditionally in https://github.com/gentoo/gentoo/commit/edf676b8587ce995a0ac315bf15ae6029b42c520

**Pull request closed without merging**
