### PR TITLE
dev-util/intel-graphics-system-controller: move to dev-util/igsc, add 0.9.3

### PR DESCRIPTION
**Pull request by alfredfo**
Name very long and hard to find. 'igsc' is used both on Arch and
COPR. Intel calls it igsc themselves, and is used on forums.

Also avoids MY_P and MY_PN variables.

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by janhenke** [comment]
I am *not* in favour of this rename. For one the short form igsc is even more obscure and not obvious, thus qualifies as *hard to find*. Also the name being rather long does not really consitute a reason to change it.

**Comment by janhenke** [comment]
So nack from me, I am not convinced.

**Comment by alfredfo** [comment]
> So nack from me, I am not convinced.

Okay, should I make another PR with 0.9.3 calling it intel-graphics-system-compiler?

**Comment by ConiKost** [comment]
> Okay, should I make another PR with 0.9.3 calling it intel-graphics-system-controller?

Yes, please.

**Pull request closed without merging**
