### PR TITLE
Bump alsa packages to 1.2.11

### PR DESCRIPTION
**Pull request by vadorovsky**
Bump

- media-libs/alsa-lib
- media-sound/alsa-tools
- media-sound/alsa-utils

to 1.2.11. See the commit messages for details.

### CODE REVIEW

**Comment by thesamesam** [comment]
The whole ALSA stack should be done together (same PR, sep commits)

**Comment by vadorovsky** [comment]
@thesamesam OK, I think that should be all alsa packages which are affected by 1.2.11 update. Are you fine with the PR desc and commit messages?

I marked as a draft, because I still want to test it properly today, I will ping you once I'm ready.

**Comment by thesamesam** [comment]
> @thesamesam OK, I think I bumped all alsa packages which are affected by 1.2.11 update. Are you fine with the PR desc and commit messages?

They look good! Thank you.

Just remember to `ekeyword ~all ...` which should fix the CI failure (see https://devmanual.gentoo.org/keywording/index.html#keywording-on-upgrades).

> 
> I marked as a draft, because I still want to test it properly today, I will ping you once I'm ready.

**Comment by vadorovsky** [comment]
@thesamesam Alright, all packages work for me and I updated the keywords. Thanks for review!

**Comment by thesamesam** [comment]
Will review later on, thanks! Could you rebase one more time, as I've just fixed the CI failure?

**Comment by thesamesam** [comment]
Thank you! I'm sorry I was slow to review too.

**Pull request closed without merging**
