### PR TITLE
dev-libs/librelp: Bump to v1.2.12

### PR DESCRIPTION
**Pull request by Whissi**
Simple bump.

I verified building on ~arm64 on my own.

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. Are you sure about the bug number?

**Comment by monsieurp** [comment]
@dev-zero

**Comment by Whissi** [comment]
Yes, I am sure about the bug number. The bug was about keywording rsyslog for arm64 and librelp is an optional dependency for rsyslog.

**Comment by Whissi** [comment]
Closing, now in tree: 79b25fdf3161852413db5082ee0f121e6805be84, 42c4184d3697a7c45ecfb5e7222b2bff60bd217f and 403096c6583dc4ffd24b9bc1006c3f2cf6f00246

**Pull request closed without merging**
