### PR TITLE
dev-python/{shibokent6,pyside6,pyside6-tools} - bump to 6.4.0

### PR DESCRIPTION
**Pull request by waebbl**
**dev-python/shiboken6: add 6.4.0**

Need to restrict to <clang-16 for now, bug #873391

Bug: https://bugs.gentoo.org/873391
Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

**dev-python/pyside6: add 6.4.0**

- add charts and network-auth modules
- add templates for httpserver, pdf{,widgets} and spatialaudio modules
- adjust some required use and outdated dependencies

Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

**dev-python/pyside6-tools: add 6.4.0**

Signed-off-by: Bernd Waibel <waebbl-gentoo@posteo.net>

### CODE REVIEW

**Comment by waebbl** [comment]
Should be ready for review. Hopefully I catched any detail.

On a side note: I'd like to have the essential modules removed from the USE flags. These are Core, Gui, Widgets, PrintSupport, Sql, Network, Test(lib), Concurrent:
- fewer USE flags -> easier testing
- greatly simplified logic for REQUIRED_USE
- although the package builds with these modules off, testing is not supported by such configurations according to the output from cmake
- configurations with essential modules disabled call for issues, with might not be easy to catch or analyze
WDYT?

**Comment by AndrewAmmerlaan** [comment]
> Should be ready for review. Hopefully I catched any detail.

Great, Thanks, I'll test and merge soon (probably this weekend).

> On a side note: I'd like to have the essential modules removed from the USE flags. These are Core, Gui, Widgets, PrintSupport, Sql, Network, Test(lib), Concurrent:
> 
>     * fewer USE flags -> easier testing
> 
>     * greatly simplified logic for REQUIRED_USE
> 
>     * although the package builds with these modules off, testing is not supported by such configurations according to the output from cmake
> 
>     * configurations with essential modules disabled call for issues, with might not be easy to catch or analyze
>       WDYT?

I'd like to keep pyside{2,6} as close as possible to pyqt{5,6}. This makes maintaining QtPy a bit easier. So I think we should discuss this first with the Qt Team.

**Comment by waebbl** [comment]
> I'd like to keep pyside{2,6} as close as possible to pyqt{5,6}. This makes maintaining QtPy a bit easier. So I think we should discuss this first with the Qt Team.

That's ok. I don't know the build systems of PyQt or QtPy, but it seems, like PySide is quite sensitive when it comes to potentially invalid combinations of build time options. Although it does allow them, it at least gives warnings, but silently disables the requested features.
I see no reason however, why we should not depart from the pyside2 / pyqt5 set of USE flags. Qt6 is something new, it doesn't have to have the same set of options as Qt5.

**Comment by waebbl** [comment]
Another note: the patch for bug #873391 should eventually also be applied to shiboken2-5.15.5 and shiboken6-6.3.2. If 5.15.6 and 6.4.0 are failing with clang-16 so most like will also do the earlier versions. I didn't include it here, because it's a different topic.

**Comment by AndrewAmmerlaan** [comment]
> Another note: the patch for bug #873391 should eventually also be applied to shiboken2-5.15.5 and shiboken6-6.3.2. If 5.15.6 and 6.4.0 are failing with clang-16 so most like will also do the earlier versions. I didn't include it here, because it's a different topic. Also I wasn't sure about the cleanup plans for these versions.

Additionally, we need to be a bit stricter in which versions of the qt packages we pull in. For example, pyside 6.3.2 fails to compile with qtbase 6.4.0. I'll fix this in a followup commit.

**Comment by AndrewAmmerlaan** [comment]
Great work, Thanks :+1:

**Comment by waebbl** [comment]
> > Another note: the patch for bug #873391 should eventually also be applied to shiboken2-5.15.5 and shiboken6-6.3.2. If 5.15.6 and 6.4.0 are failing with clang-16 so most like will also do the earlier versions. I didn't include it here, because it's a different topic. Also I wasn't sure about the cleanup plans for these versions.
> 
> Additionally, we need to be a bit stricter in which versions of the qt packages we pull in. For example, pyside 6.3.2 fails to compile with qtbase 6.4.0. I'll fix this in a followup commit.

Yes, they started with some pyside2-5.x version to be stricter, yet didn't require the exact same version then. Maybe we should handle these package the same way as any other Qt package and strictly require the same version?

**Comment by waebbl** [comment]
Thanks for merging! :+1:

**Pull request closed without merging**
