### PR TITLE
net-misc/pedro: patches for implicit function declarations (and drop 1.6)

### PR DESCRIPTION
**Pull request by navi-desu**
I'll also be emailing the patch to the address listed on the home page.

Closes: https://bugs.gentoo.org/870724

### CODE REVIEW

**Comment by navi-desu** [comment]
Upstream is looking into the patch for a next release.

**Comment by a17r** [comment]
It seems they made that release: https://staff.itee.uq.edu.au/pjr/HomePages/PedroHome.html

**Comment by arkamar** [comment]
1.14 was released some time ago, it includes fix for implicit function declaration and one more fix. 1.6 was removed some time ago from our tree. Version bump would address both bugs, https://bugs.gentoo.org/870724 and https://bugs.gentoo.org/913494.

@navi-desu do you want to do the version bump?

**Comment by arkamar** [comment]
bumped in commit ef1bbbf45cd1 - `net-misc/pedro: add 1.14`

**Pull request closed without merging**
