### PR TITLE
app-editors/zed: add 0.159.10

### PR DESCRIPTION
**Pull request by robert7k**
Mask package for musl, as it is not supported by upstream, see https://zed.dev/blog/remote-development

Closes: https://bugs.gentoo.org/940473

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Can't download the crates, 
```
!!! Couldn't download 'zed-0.159.10-crates.tar.xz'. Aborting.
```

**Comment by robert7k** [comment]
> Can't download the crates,
> 
> ```
> !!! Couldn't download 'zed-0.159.10-crates.tar.xz'. Aborting.
> ```

Fixed.

**Review by juippis — COMMENTED** [review]
Compilation dies to:
```
error: failed to run custom build command for `wasmtime-c-api-impl v24.0.0`

Caused by:
  process didn't exit successfully: `/var/tmp/portage/app-editors/zed-0.159.10/work/zed-0.159.10/target/release/build/wasmtime-c-api-impl-2eca650eb4af0449/build-script-build` (exit status: 101)
  --- stdout
  cargo:rerun-if-changed=cmake/features.cmake
  cargo:rerun-if-changed=cmake/install-headers.cmake
  cargo:rerun-if-changed=include

  --- stderr
  thread 'main' panicked at /var/tmp/portage/app-editors/zed-0.159.10/work/cargo_home/gentoo/wasmtime-c-api-impl-24.0.0/build.rs:41:33:
  failed to spawn `cmake`: Os { code: 2, kind: NotFound, message: "No such file or directory" }
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
 * ERROR: app-editors/zed-0.159.10::gentoo failed (compile phase):
 *   cargo build failed
```
every time.

**Review by juippis — APPROVED** [review]
Heh, actually read the error later on. Just needs to bdepend on cmake.

**Pull request closed without merging**
