### PR TITLE
enlightenment: git-2->git-r3 plus ebuild fixes found while testing.

### PR DESCRIPTION
**Pull request by hanetzer**
In order to reduce the amount of 'false positives' for ebuilds using git-2, I've
decided to handle the last few eclasses which use it themselves, as the qa
sites cannot generally tell the difference between an ebuild which directly
inherits an eclass and one that inherited it from an eclass it inherits.

enlightenment.eclass is handled here, and I've tested each live ebuild which
uses it. I've found some issues which are a direct result of my changes, and
some that exist without them.

### CODE REVIEW

**Comment by juippis** [comment]
I commented this on IRC, but Ill repeat here: 
 - the next time I touch any efl ebuild, or bump it to 1.21, Ill also remove -9999. Im not even sure -9999 compiles anymore, and if it does, it wont produce quality EFL.
 - when ever I update any E-related packages, Im moving away from using enlightenment.eclass. Im not sure that enlightenment.eclass can be removed from the tree within 2018 without touching older ebuilds. Also, much depends on arch keywording and stabilization ;)
 - Im gonna ask to stabilize efl-1.18 during June and when that happens, I will last-rite old E libraries and plugins. evas_generic_loaders being one of them.

So I dont know if this fixes some current QA issues, but in my mind none of the changes in here will be long-term/useful, since Im trying hard to get rid of _all_ of the files modified in this commit ;)

All that being said, I dont really mind whether this gets merged for now, or not :)

**Comment by hanetzer** [comment]
Honestly if @juippis is gonna retool them all anyways that sounds reasonable.

**Comment by juippis** [comment]
Sure. I can make a PR in 2-3 days (away from home atm), or you can remove them before that - I dont mind. I can reference this PR in that one, then. 

What about ebuilds and enlightenment.eclass, that has the "IF PV = 9999" check, should those be cleaned as well, or just remove them with time (updates)?

**Comment by mgorny** [comment]
I'd leave that up to @hanetzer ;-).

**Comment by hanetzer** [comment]
@mgorny this is ready to go. Honestly I could nix out the git logic entirely,
but I figure with new iterations of enlightenment ebuilds not using the eclass
its probably overkill.

**Comment by mgorny** [comment]
I don't really any purpose in doing this but it's up for @juippis to decide.

**Comment by juippis** [comment]
There shouldnt be any -9999 ebuilds left that use this eclass ;)

However since git-r2 has been deprecated, this merge shouldnt hurt the QA situation. enlightenment.eclass will stay in the tree for a ~long time, unless _someone_ rewrites old efl ebuilds. I dont want to touch them...

So for that reason I approve.

**Pull request closed without merging**
