### PR TITLE
sys-apps/flashrom: Add Atmel AT25DF021A support via patch

### PR DESCRIPTION
**Pull request by luke-jr**
The Atmel AT25DF021A is used for the FPGA firmware in Raptor Talos II POWER9 workstations.

The patch is controlled by a USE flag since it is non-standard and adds a SRC_URI.

The ebuild revision is not bumped, because it is only ~arch, has a USE flag change, and is identical to the prior package without that USE flag set.

### CODE REVIEW

**Comment by mgorny** [comment]
Did you manage to contact Peter somehow? If you can't reach him otherwise, please report a bug for this and link it with the PR.

**Comment by luke-jr** [comment]
Yes.

FWIW, upstream merged this in June (with some minor changes): https://review.coreboot.org/cgit/flashrom.git/commit/?id=0b59b0dafc219ba73ee2af5404ce626575d74c6f

**Comment by juippis** [comment]
I see flashrom-1.1 was added. Is this PR still relevant? It does touch 1.0 which is still in tree... Can you rebase if yes?

**Comment by luke-jr** [comment]
Probably irrelevant now

**Pull request closed without merging**
