### PR TITLE
dev-libs/serd: add python 3.10

### PR DESCRIPTION
**Pull request by t0b3**
Closes: https://bugs.gentoo.org/829422

### CODE REVIEW

**Comment by fordfrog** [comment]
@t0b3 sorry, i did notice that on your previous commit just after pushing it to the main tree, so i did not write you that, but according to our rules, your commit message should contain your name, not your nick. that affects all your push requests. please fix that.

**Comment by t0b3** [comment]
@fordfrog thanks for your hint how to prepare the commits. I'll happily do
so for future contributions. Currently I'm only on emails for the upcoming
weeks. You are very welcome to change to my real name or drop my name if
you prefer.

Miroslav Šulc ***@***.***> wrote on Sat., 18. Dez. 2021,
07:51:

**Comment by fordfrog** [comment]
@t0b3 ok, i'll use the name from the email addres, is that ok? :-)

**Comment by t0b3** [comment]
Perfect +1

Miroslav Šulc ***@***.***> wrote on Sat., 18. Dez. 2021,
08:56:

**Comment by fordfrog** [comment]
@t0b3 merged, thanks!

**Comment by t0b3** [comment]
@fordfrog You are welcome.
Ago tells in https://bugs.gentoo.org/829568 serd fails. probably due to
missing sphinx in bdeps. Can you have a look?

Miroslav Šulc ***@***.***> schrieb am Sa., 18. Dez. 2021,
12:59:

**Pull request closed without merging**
