### PR TITLE
net-im/telegram-desktop-bin: Bump version to 1.9.12

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
Will do, already got  a mail about a new release before this review ...

**Comment by henning-schild** [comment]
> I've heard you need to add `RESTRICT="splitdebug"` for this one, but add it for the next version bump and test it before pushing a commit.

Could you please go into more detail on this remark? I added that to the next release and played with FEATURES="splitdebug", but did not see any differing merge output or otherwise any change.

What is the issue behind the change, how to reproduce test whether adding the line fixes the issue?

**Comment by juippis** [comment]
> 
> Could you please go into more detail on this remark? I added that to the next release and played with FEATURES="splitdebug", but did not see any differing merge output or otherwise any change.

That sounds good.

> 
> What is the issue behind the change, how to reproduce test whether adding the line fixes the issue?

The debug symbols somehow conflict with the non-bin version, I just learned it myself and haven't really digged further. I **guess** it somehow makes debugging (stracing for example) the non-bin version impossible if this has been installed prior and gdb'd. Or something along those lines...

`man 5 ebuild`
>Disables splitdebug for specific packages. This is for packages with binaries that trigger problems with splitdebug, such as file-collisions between symlinks in /usr/lib/debug/.build-id (triggered by bundled libraries).

**Comment by henning-schild** [comment]
I have seen the new non-bin version and already used it myself. Looking forward to dropping bin eventually. There already is a blocker in place so both can not be installed at the same time. If there is an issue with migrating between the two ... related to debugging ... i guess a bug would be the way to go. Instead of rumors that nobody understands.

**Pull request closed without merging**
