### PR TITLE
Various packages: Fix app-crypt/swtpm[gnutls] dependency

### PR DESCRIPTION
**Pull request by salahcoronya**
The "gnutls"  USE flag on app-crypt/swtpm determines whether or not swtpm_cert utility is built. The swtpm_cert is required to provision the EK cert and TPM cert. However, many programs use app-crypt/swtpm for testing and don't need the certs for the tests, or will simply skip those tests if not present. 

app-crypt/libsecret and app-crypt/tpm2-openssl don't require the TPM to have an EK or TPM cert, so I've modified the script to not provision those and remove the gnutls dependency. On the other hand, app-emulation/libvirt HAS to have swtpm_cert to correctly provision TPM for operating system (like Windows) that care the EK cert and TPM cert are present. So update it to require app-crypt/swtpm[gnutls]. The other programs that have swtpm dependencies seems to function fine with -gnutls.

### CODE REVIEW

**Comment by tamiko** [comment]
@salahcoronya I have changed app-crypt/swtpm to the version you originally suggested, meaning without USE=gnutls. Would you mind updating all dependencies in here either by dropping the use flag or by using `[gnutls(+)]` so that dependencies don't break?

**Comment by mattst88** [comment]
That's really something that should have been done before landing the breaking change, isn't it?

**Comment by salahcoronya** [comment]
The entire pull request was to add gnutls USE flag to dependencies. If there's no more flag, and support is unconditional, then this PR is not needed.

**Comment by tamiko** [comment]
@mattst88 No, on the contrary. This PR is the breaking change. With one exception (`tpm2-openssl`, that I unfortunately missed) we never had a dependency on `swtpm[gnutls]`

**Comment by tamiko** [comment]
@salahcoronya Then, let's close this PR for now. Provided the changes to `app-crypt/libsecret` have some utility on its own, what about putting those into a separate PR and pinging the gnome team?

**Pull request closed without merging**
