### PR TITLE
drop references to ruby versions no longer in tree

### PR DESCRIPTION
**Pull request by DerDakon**
This has no particular reason, I just stumbled over it.

The first patch was created using

```shell
sed -r 's/USE_RUBY="(ruby20 )?(ruby21 )?/USE_RUBY="/' -i $(git grep -l ruby2[01])
```
with a manual fix for virtual/ruby.

There are more places, most need someone actually knowing what's happening there (i.e. @graaff).

A good starting point is

```shell
git grep ruby2[01]
```

### CODE REVIEW

**Comment by graaff** [comment]
I'm hesitant to apply something like this. Unknown ruby targets are simply ignored, so there is no issue with keeping them around. Normally we remove them as we are doing work on ebuilds anyway.

For the most part doing this scripted will work, but there are a few edge cases that may be problematic, e.g. we sometimes play tricks with USE_RUBY in order to work around circular dependency bootstrapping issues. USE_RUBY may also end up empty, although that doesn't seem likely to happen. It looks like you took that into account in the 2nd commit. Did you run into any other issues?

**Comment by DerDakon** [comment]
No, there have been no issues for me. It was just that I was looking on some ebuild and thought "why is this still in there?" If you don't like it I have no problem with just dropping it.

OTOH when this is applied a warning can be issued for unknown ruby targets to help people spotting typos in their ebuilds.

**Comment by mgorny** [comment]
@graaff, I'm leaving this for you to handle.

**Comment by flappyports** [comment]
@DerDakon @graaff Any intent on still working this PR?

**Comment by DerDakon** [comment]
refreshed it for the sake of simplicity, but can be closed if @graaff want's to handle it differently

**Pull request closed without merging**
