### PR TITLE
sys-cluster/torque: Fix register sotrage class specifier not allowed

### PR DESCRIPTION
**Pull request by listout**
Closes: https://bugs.gentoo.org/898574

### CODE REVIEW

**Comment by listout** [comment]
I'll create upstream PR and link it here. In the meanwhile, if @thesamesam or @juippis can please version bump the package to 6.1.3

**Comment by listout** [comment]
https://github.com/adaptivecomputing/torque/pull/475

**Comment by thesamesam** [comment]
I looked at bumping this _ages_ ago and found there was something weird about newer versions.

**Comment by listout** [comment]
> I looked at bumping this _ages_ ago and found there was something weird about newer versions.

alright, what would you suggest we should do instead for this? For the current version in gentoo tree, the patch will do the job.

**Comment by thesamesam** [comment]
ok, let's just apply it

**Comment by thesamesam** [comment]
thanks!

**Pull request closed without merging**
