### PR TITLE
treewide: unquote EAPIs

### PR DESCRIPTION
**Pull request by hanetzer**
I figured we should standardize one way or the other, with or without
quotes, and I don't want to think of the magick required to add quotes
to every EAPI assignment in each ebuild. This should ease using git grep
to find ebuilds with outdated EAPIs as we go along.

Yes, I realize this is a lot of change, but I think its worthwhile to do so.
```
git grep EAPI=\" | wc -l
6301
git grep EAPI=[0123456] | wc -l
30056
```

Change was made via `for i in {0..6}; do sed -i s:EAPI=\"$i\":EAPI=$i: */*/*.ebuild; done`
Just go ahead and kill them off.

### CODE REVIEW

**Comment by radhermit** [comment]
Honestly, I don't see the point of this as long as the spec allows quotes. In addition, one can just use a tool that can query against the metadata (eix, pquery, etc) instead of grepping the raw files.

**Comment by radhermit** [comment]
My underlying point was, it's pointless to make such a change without reinforcement to back it up in the form of repoman/pkgcheck or similar changes.

As far as I recall, all your other examples of terrible formatting are already caught by QA tools, and EAPI quoting vs non-quoting in particular isn't terrible formatting, imho.

**Comment by hanetzer** [comment]
Also a good point. Needs some bite in order to be able to make it stick, so to speak.

**Comment by Zlogene** [comment]
I agree with @radhermit, the changes are honestly pointless

**Comment by radhermit** [comment]
Yep, I'm closing this as we're not interested in this type of tree-wide change.

**Pull request closed without merging**
