### PR TITLE
media-libs/glfw: rename wayland useflag to wayland-only

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
Closes: https://bugs.gentoo.org/616968
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by pinkflames** [comment]
FWIW, I support this.

**Comment by mattst88** [comment]
I think this is a good solution. We made a similar change with `gles2` → `gles2-only` a while back.

**Comment by chewi** [comment]
Ahem, I like the idea but I don't think you tested this. Looks like your `usex` change is the wrong way round.

```
>>> Configuring source in /var/tmp/portage/media-libs/glfw-3.3.4/work/glfw-3.3.4 ...
 * ERROR: media-libs/glfw-3.3.4::gentoo failed (configure phase):
 *   USE Flag 'wayland' not in IUSE for media-libs/glfw-3.3.4
 * 
 * Call stack:
 *          ebuild.sh, line  127:  Called src_configure
 *        environment, line 2103:  Called usex 'wayland' 'wayland-only'
 *   phase-helpers.sh, line  213:  Called use 'wayland'
 *   phase-helpers.sh, line  252:  Called die
 * The specific snippet of code:
 *   				die "USE Flag '${u}' not in IUSE for ${CATEGORY}/${PF}"
```

**Comment by ionenwks** [comment]
I was pondering what to do with this (other distros have done things such as wrappers to load the right library), I guess could potentially have used a eselect to let users switch, but I don't feel it's overly needed as long as it's clear what users are getting. So I'm okay with this as well.

**Review by ionenwks — APPROVED** [review]
Guess I'll do this now and egl(+) at same time.

I'll take only the changes to 3.3.4-r1, this is due to be stabled soon'ish either way.

**Pull request closed without merging**
