### PR TITLE
⬆️ media-libs/openexr: add 3.2.4

### PR DESCRIPTION
**Pull request by Jamim**
_Hello @negril,_

**OpenEXR** 3.2.4 [was released](https://github.com/AcademySoftwareFoundation/openexr/releases/tag/v3.2.4) recently.
It would be nice to have it in the Portage tree.

Changelog:
  - https://github.com/AcademySoftwareFoundation/openexr/blob/v3.2.4/CHANGES.md#version-324-march-26-2024

Based on:
  - [openexr/openexr-3.2.3::gentoo](https://gitweb.gentoo.org/repo/gentoo.git/commit/media-libs/openexr/openexr-3.2.3.ebuild?id=44e968379c2b7b4c6154c184f5f1fea18407a343) from #35692

<details>
<summary>diff -u openexr-3.2.{3,4}.ebuild</summary>

```diff
--- openexr-3.2.3.ebuild	2024-03-17 15:55:53.962592128 +0300
+++ openexr-3.2.4.ebuild	2024-03-27 00:14:26.177712318 +0300
@@ -125,13 +125,13 @@
 }
 
 src_test() {
-    local CMAKE_SKIP_TESTS=()
+	local CMAKE_SKIP_TESTS=()
 
-    use x86 && CMAKE_SKIP_TESTS+=(
-        '^OpenEXR.testDwaLookups$'
-    )
+	use x86 && CMAKE_SKIP_TESTS+=(
+		'^OpenEXR.testDwaLookups$'
+	)
 
-    cmake_src_test
+	cmake_src_test
 }
 
 src_install() {
```

</details>

_Best regards!_

### CODE REVIEW

**Comment by Jamim** [comment]
_Hello @negril,_
Would you mind reviewing this PR?
_Thanks in advance!_

**Comment by negril** [comment]
It's a trivial copy that only fixes indents. Nothing to review really.

**Comment by Jamim** [comment]
> It's a trivial copy that only fixes indents. Nothing to review really.

That's true! 💯
However, I believe it doesn't mean trivial bumps can be merged blindly nor they should be ignored.

**Comment by Jamim** [comment]
_Hello @Flowdalic,_

Thank you for merging changes from #35692!
Would you mind taking a look at this PR as well?

_Thanks in advance!_

**Comment by Jamim** [comment]
_Hello @arthurzam,_

Would you mind merging these changes?

_Thanks in advance!_

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
