### PR TITLE
cmake-eapi5cleanup

### PR DESCRIPTION
**Pull request by a17r**
All versions have newer arch or ~arch packages available. Please ACK.

### CODE REVIEW

**Comment by a17r** [comment]
Cleaning up `cmake-utils.eclass` revdeps with EAPI-5.

@gentoo/games:
```
dev-libs/libgaminggear
games-strategy/wesnoth
```

@gentoo/graphics: `media-gfx/enblend`
@gentoo/lxqt: `media-gfx/lximage-qt`
@gentoo/printing: `media-libs/vigra`
@gentoo/radio, @ZeroChaos-:
```
net-libs/libhackrf
net-wireless/gr-osmosdr
net-wireless/hackrf-tools
net-wireless/inspectrum
net-wireless/rtl-sdr
net-wireless/uhd
```

@gentoo/sound: `media-libs/chromaprint`

@aliceinwire: `app-admin/clog`
@Amynka: `dev-cpp/gflags`
@dpisklov: `dev-libs/libgaminggear`
@jlec: `net-analyzer/zmap`
@NP-Hardass: `x11-misc/virtualgl`
@tamiko: `sci-visualization/paraview`
@voyageur: `media-gfx/freepv`

**Comment by ZeroChaos-** [comment]
radio/myself: ACK

**Comment by SoapGentoo** [comment]
sound: ACK

**Comment by maekke** [comment]
graphics: ACK

**Comment by voyageur** [comment]
media-gfx/freepv: ACK

**Comment by NP-Hardass** [comment]
x11-misc/virtualgl: ACK

**Pull request closed without merging**
