### PR TITLE
net-proxy/haproxy: Add ~arm keyword

### PR DESCRIPTION
**Pull request by bjacquin**
Tested on Scaleway C1

Package-Manager: portage-2.2.26

### CODE REVIEW

**Comment by idella** [comment]
Correct me if I'm wrong but this requires a full keyword request bug via bugzilla.  The above can be submitted as evdence to support the merot of its addition

**Comment by bjacquin** [comment]
Sure, https://bugs.gentoo.org/show_bug.cgi?id=575348 have been created. Thanks!

**Comment by idella** [comment]
yw

**Comment by monsieurp** [comment]
@akhuettel @blueness @Zlogene @ZeroChaos- @asarubbo

**Comment by steev** [comment]
lgtm

**Comment by monsieurp** [comment]
Merged.

**Pull request closed without merging**
