### PR TITLE
Electron, Atom updates

### PR DESCRIPTION
**Pull request by elprans**
This update brings version bumps to Electron (0.37.8, 1.3.5) and Atom (1.10.2).

The biggest change is that Electron builds are now slotted (x.y).  This is necessary, as Electron usually breaks backwards compatibility with every x.y release, and apps need a stable target.  I've also added `eselect-electron` ebuild to switch `/usr/bin/electron` and `/usr/include/electron` symlinks.

There are also some build fixes and ebuild cleanups.

### CODE REVIEW

**Comment by floppym** [comment]
I'm curious about the eselect module; you say change an include directory symlink, but what about the library .so symlink?

I'm wondering if any of that is actually necessary; don't the consumers need to know what version of electron they are building against? Why does there need to be a systemwide "default"?

**Comment by elprans** [comment]
There is no library .so, actually.  There's just the electron executable.  Electron apps do not _link_ against it, you just run it with your app path as an argument.

> I'm wondering if any of that is actually necessary; don't the consumers need to know what version of electron they are building against? Why does there need to be a systemwide "default"?

Well, I guess I just followed a custom that every ebuild that has slotted binaries provides an eselect module.  It is true that Portage ebuilds will target a specific slot and will not care for the symlinks, but end users might still find this useful.  But if you think the eselect module is wholly redundant, it can easily be dropped.

**Comment by elprans** [comment]
@gentoo/proxy-maint

**Comment by floppym** [comment]
Thanks for explaining. I don't really care either way.

**Comment by dlan17** [comment]
@elprans I just leave yourself to close/handle all bugs in b.g.o, thanks

**Pull request closed without merging**
