### PR TITLE
media-gfx/gimp: 9999, option 'lua' changed to type boolean

### PR DESCRIPTION
**Pull request by band-a-prend**
Closes: https://bugs.gentoo.org/939850

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by band-a-prend** [comment]
Check fail isn't related to media-gfx/gimp package.

**Comment by robertkirkman** [comment]
I encountered this problem, so I tested the patch like this
```
sudo su
cd /var/db/repos/gentoo/
wget  https://github.com/gentoo/gentoo/pull/38760.diff 
patch -p1 < 38760.diff
emerge =gimp-9999
```
and it works for me to fix the error, thanks!

**Review by ceamac — APPROVED** [review]
Tested with gcc 13, 14, 15 and clang 18.  Also passes the tests.

FYI, 2.99.18-r1 passes the tests, 2.10.38 still fails.

**Comment by band-a-prend** [comment]
@ceamac, thanks!

**Pull request closed without merging**
