### PR TITLE
dev-python/elasticsearch-curator: bump to 4.2.6

### PR DESCRIPTION
**Pull request by hydrapolic**
This needs certifi-2017.01.23 - please do not merge until it has landed in the repo.

https://bugs.gentoo.org/show_bug.cgi?id=607540

### CODE REVIEW

**Comment by gktrk** [comment]
We need to bump a few things it seems :)

```
NonExistentDeps	depset rdepends: nonexistent dep: [ >=dev-python/certifi-2017.1.23 ]
```

**Comment by hydrapolic** [comment]
Certifi bumped today,so this should work now.

**Comment by gktrk** [comment]
Merged in https://github.com/gentoo/gentoo/compare/ed22be7...e9081ed. Thanks!

**Comment by hydrapolic** [comment]
Thank you!

**Pull request closed without merging**
