### PR TITLE
selective package de-stabilization on ~ppc

### PR DESCRIPTION
**Pull request by gyakovlev**
CI torture checks for for https://bugs.gentoo.org/823768

### CODE REVIEW

**Comment by thesamesam** [comment]
We probably can’t do ipython given it gets dragged in for tests a lot in Python land. If we can drop it now, chances are we would have to restore it again soon :(

**Comment by gyakovlev** [comment]
the intention to de-stabilize some revdeps as well.

ipython/jupyter is the most painful stack to bump/stabilize afaik.

**Comment by thesamesam** [comment]
The problem is that we AFAIK intentionally stabled it and the stack because of how common of a dep it is (like scipy, matplotlib)

**Comment by gyakovlev** [comment]
ok that was bad idea indeed, closing

**Pull request closed without merging**
