### PR TITLE
{,g}vim: build against multiple python versions

### PR DESCRIPTION
**Pull request by Uroc327**
As some plugins may require python2 and other may require python3, vim
provides a compile-time option to build against multiple python versions
and choose the correct one dynamically.

Signed-off-by: Constantin Runge <c.runge@cssbook.de>

### CODE REVIEW

**Comment by hanetzer** [comment]
It appears that versionator is not at all in use here. Drop it if possible?

**Comment by a17r** [comment]
This PR needs a rebase.

**Comment by Uroc327** [comment]
@a17r rebased onto latest master

**Comment by radhermit** [comment]
Closing as this won't be accepted into the current tree (see bug #706644 for more info) and newer ebuilds already drop python2 support so this is kind of pointless going forward anyway.

**Pull request closed without merging**
