### PR TITLE
app-misc/elasticsearch: remove unused files

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR  removes some unused files from:
app-misc/elasticsearch

Please review.

### CODE REVIEW

**Comment by hydrapolic** [comment]
Looks good, thanks :)

**Comment by mgorny** [comment]
(also your remaining new PRs)

**Comment by mm1ke** [comment]
@mgorny 
I've read the new copyright policy but i'm not sure what exactly i have to update here? Do i need sign my PR's now (which shouldn't be a problem, but so far i didn't notice it was enforced) or do i miss something else? Also, as far as i understand the new copyright policy, future ebuilds should contain ```Gentoo Authors``` instead of ```Gentoo Foundation``` in it's copyright - right? However, i haven't seen any ebuilds yet having that, nor do i actually touch any ebuilds with this PR.
Please help :/

**Comment by hydrapolic** [comment]
Add signed-off-by line as in https://github.com/gentoo/gentoo/commit/c2f8dd5d0a2c25cf357cdca706e297306261e01e

**Comment by mm1ke** [comment]
@hydrapolic 
Thanks for the Info, updated my PR :)

**Comment by mgorny** [comment]
Looks good now, thanks!

**Pull request closed without merging**
