### PR TITLE
faudio-23-10 version bump

### PR DESCRIPTION
**Pull request by mipseb**
This is currently broken.

### CODE REVIEW

**Comment by juippis** [comment]
Let us know when it's not a draft anymore. What exactly is broken?

**Comment by powerman** [comment]
While re-emerging world after profile update to 23.0 I got this error:
```
app-emulation/faudio:0

  (app-emulation/faudio-23.02:0/0::gentoo, ebuild scheduled for merge) USE="-debug -dumpvoices -test" ABI_X86="(64)" pulled in by
    app-emulation/faudio (Argument)

  (app-emulation/faudio-21.01:0/0::gentoo, installed) USE="userland_GNU -debug -dumpvoices -gstreamer -test -utils -xnasong" ABI_X86="32 (64)" pulled in by
    app-emulation/faudio[abi_x86_32] required by @esteam 
                         ^^^^^^^^^^                                          
```
Any change this PR will fix it?

**Comment by Kangie** [comment]
> While re-emerging world after profile update to 23.0 I got this error:
> 
> ```
> app-emulation/faudio:0
> 
>   (app-emulation/faudio-23.02:0/0::gentoo, ebuild scheduled for merge) USE="-debug -dumpvoices -test" ABI_X86="(64)" pulled in by
>     app-emulation/faudio (Argument)
> 
>   (app-emulation/faudio-21.01:0/0::gentoo, installed) USE="userland_GNU -debug -dumpvoices -gstreamer -test -utils -xnasong" ABI_X86="32 (64)" pulled in by
>     app-emulation/faudio[abi_x86_32] required by @esteam 
>                          ^^^^^^^^^^                                          
> ```
> 
> Any chance this PR will fix it?

Unlikely. That's portage telling you that the later version is available but that the version at the bottom is required by `@esteam`. Look into why that version is pinned to resolve it - strictly not an error, but for your information about why the latest version isn't being installed.

**Comment by mipseb** [comment]
> Let us know when it's not a draft anymore. What exactly is broken?

As of now, nothing. Thank you for your patience.

**Comment by thesamesam** [comment]
There's https://github.com/gentoo/gentoo/pull/36070 too?

**Pull request closed without merging**
