### PR TITLE
dev-python/importlib_resources: Remove myself from maintainer list

### PR DESCRIPTION
**Pull request by rseichter**

### CODE REVIEW

**Comment by sbraz** [comment]
Hey @rseichter, I can merge that. Just curious though, why are you removing yourself?

**Comment by rseichter** [comment]
Hello @sbraz . I introduced the package to Gentoo as a proxy maintainer. Since you and the Python team have taken responsibility, it does not seem useful to have myself and the Proxy Maintainers team listed. Besides, now that Python 3.7 has become Gentoo standard, I expect this backport library to become obsolete soon.

**Comment by sbraz** [comment]
Thanks for the reply, makes sense to me. I removed the proxy-maint project on merge.

**Comment by rseichter** [comment]
> I removed the proxy-maint project on merge.

Thanks. I had thought of doing that myself, but did not want to overstep any boundaries.

**Pull request closed without merging**
