### PR TITLE
media-video/aegisub: add missing pthread flags

### PR DESCRIPTION
**Pull request by Coacher**
This also fixes build with GCC-5.

Gentoo-Bug: 568878

### CODE REVIEW

**Comment by Coacher** [comment]
No revbump needed here.

**Comment by idella** [comment]
Coacher, as we discussed, you need use repoman commit rather than git commit.
The check has validated the ebuild so it passes, but now for the state of the final git patch. Also you could possibly do with purging some old vns.

**Comment by Coacher** [comment]
Rebased to commit with repoman. I'd like to cleanup old versions. But first I need 3.2.2 to go stable. And for 3.2.2 to go stable I need Gentoo bug 568878 to be fixes. And for this I need this PR to be merged.
As soon as this one is merged I'll file STABLEREQ, then will remove unneeded versions.

**Comment by Moiman** [comment]
Could you try to upstream this: https://github.com/Aegisub/Aegisub

**Comment by Coacher** [comment]
@Moiman,I will try. It is on my TODO list. Aegisub upstream is not very active on merging PRs though (https://github.com/Aegisub/Aegisub/pulls). This has already been discussed at #gentoo-proxy-maint.

**Comment by idella** [comment]
Sounds like a plan

**Comment by Coacher** [comment]
Thank you, @idella.

**Pull request merged**
