### PR TITLE
dev-cpp/libcmis, dev-libs/liborcus, app-office/libreoffice: version bumps

### PR DESCRIPTION
**Pull request by a17r**
libcmis package moved to github.

- Fixed a crash when server response did not contain cmis:baseTypeId property (tdf#90351)
- Removed the requirement for non-empty password when using HTTP authentication credentials
- Fixed build with boost 1.60 and gcc 5
- Fixed a few problems found by Coverity
- Fixed a busload of memory leaks

libreoffice-5.1.1.3: Released, add patch to fix https://bugs.gentoo.org/show_bug.cgi?id=575732

### CODE REVIEW

**Comment by monsieurp** [comment]
@akhuettel

**Comment by kentfredric** [comment]
```dev-vcs/git-num metadata.xml <maintainer/> tag for mrueg@gentoo.org has type='(none)', should be 'person' or 'project'```

**Comment by monsieurp** [comment]
@kentfredric http://gifrific.com/wp-content/uploads/2014/01/Staring-Confused-Ron-Swanson.gif

**Comment by akhuettel** [comment]
Rebased and pushed.

**Pull request closed without merging**
