### PR TITLE
media-gfx/mypaint: TypeError: GLib.filename_to_utf8() takes exactly 2 arguments (4 given) - patch

### PR DESCRIPTION
**Pull request by lekto**
https://bugs.gentoo.org/show_bug.cgi?id=591180

### CODE REVIEW

**Comment by gktrk** [comment]
@hwoarang

**Comment by monsieurp** [comment]
ping @hwoarang

**Comment by hwoarang** [comment]
- Why two commits? Make it a single commit. You add a patch and then you add the patch to the ebuild. All has to be done in one go

- This is an upstream patch. Grab the patch from the git repo so we have the full commit hash and the commit message. Does it make sense?

**Comment by monsieurp** [comment]
ping?

**Comment by monsieurp** [comment]
pong.

**Pull request closed without merging**
