### PR TITLE
dev-lang/zig: add 0.12.0

### PR DESCRIPTION
**Pull request by 0x5a4**

### CODE REVIEW

**Comment by 0x5a4** [comment]
Im currently investigating some test failures, so maybe dont merge this yet...

**Comment by 0x5a4** [comment]
It seems the failure is specific to portage running the test and the way it sets up the build directory. So the resulting package is fine.

I could just patch the relevant test to be skipped?

**Comment by thesamesam** [comment]
cc @BalkanMadman (the bot doesn't seem to recognise your account/email?)

**Comment by thesamesam** [comment]
Sorry, I was going off memory and I thought you maintained Zig -- you don't :)

**Comment by thesamesam** [comment]
Now, ccing the right person.. cc @BratishkaErik

**Comment by BratishkaErik** [comment]
> Now, ccing the right person.. cc @BratishkaErik

LGTM, and by the way can you fix my email in this bot? I think this is the reason why my two other PRs did not get a review for weeks...

**Comment by thesamesam** [comment]
@mgorny Could you take a look? I've no idea how the mapping works.

**Comment by Flowdalic** [comment]
> And by the way can you please fix my email in this bot?

Is your email public in your github profile? Is it the same that you use in the package's metadata?

**Comment by BratishkaErik** [comment]
> Is your email public in your github profile? Is it the same that you use in the package's metadata?

It is the same as in metadatas, yes, but it's not primary or secondary and is not visible. Thank you very much!!! Just changed it to primary and visible, will check with in a new PR.

**Pull request closed without merging**
