### PR TITLE
dev-cpp/notcurses: update 2.2.3 -> 2.2.8

### PR DESCRIPTION
**Pull request by dankamongmen**
Tested with `ebuild`, seemed to work. I'm the upstream author. This release adds Sixel and Kitty bitmap support, among other new features and bugfixes.

Signed-off-by: nick black <nickblack@linux.com>

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Hey, 

I know this sounds weird regarding git workflow, but please split adding a new version and removing older version to separate commits. So this should be 2 commits instead of 1.
https://www.gentoo.org/glep/glep-0066.html#splitting-commits

The biggest reason being, while not relevant here, if we have to revert the commit for removing an older version, it'd also revert adding the later version. It's usually a problem with packages that have reverse dependencies.

**Comment by dankamongmen** [comment]
> Hey,
> 
> I know this sounds weird regarding git workflow, but please split adding a new version and removing older version to separate commits. So this should be 2 commits instead of 1.
> https://www.gentoo.org/glep/glep-0066.html#splitting-commits
> 
> The biggest reason being, while not relevant here, if we have to revert the commit for removing an older version, it'd also revert adding the later version. It's usually a problem with packages that have reverse dependencies.

no problem; i'll get to this tonight and ping you with a PTAL.

**Comment by dankamongmen** [comment]
The link isn't quite clear on what should happen, syntactically -- I'm assuming that the first commit ought add the new ebuild file and the two new lines to the Manifest, while the second ought remove the old ebuild file and the two old lines from the Manifest? I've got that ready if so, about to push.

**Comment by dankamongmen** [comment]
> The link isn't quite clear on what should happen, syntactically -- I'm assuming that the first commit ought add the new ebuild file and the two new lines to the Manifest, while the second ought remove the old ebuild file and the two old lines from the Manifest? I've got that ready if so, about to push.

done, and you get a shiny new 2.2.8 out of it, too. =]

**Review by juippis — APPROVED** [review]
You got it, thanks!

**Comment by juippis** [comment]
You forgot the sign-off from your 2nd commit, but I presume it was a mistake and will add it.

**Comment by dankamongmen** [comment]
> You forgot the sign-off from your 2nd commit, but I presume it was a mistake and will add it.

sorry about that; i'll try and remember next time. maybe i can set up a git commit hook for that? either way, thanks for the merge, and the advice!

**Comment by juippis** [comment]
There are three tools you can commit with, with pre-generated summary templates and sign-off lines added for you:
https://packages.gentoo.org/packages/app-portage/repoman (the most popular one), 
https://packages.gentoo.org/packages/dev-util/pkgdev
https://packages.gentoo.org/packages/app-portage/mgorny-dev-scripts (pkgcommit)

At least for repoman you need to add `SIGNED_OFF_BY="Name <e@ma.il>"` line in your */etc/portage/make.conf*. For pkgdev and pkgcommit, I presume it comes from your local git config.

Then you can use the tools to do your commits, 
```
edit your.ebuild
repoman manifest
git add Manifest your.ebuild
repoman ci
git push
```
(note that **repoman** and **pkgdev** will generate the manifest for you, and git add it also)

Let me know if you have questions, but do try them out :)

**Pull request closed without merging**
