### PR TITLE
app-misc/remind: add 05.00.05

### PR DESCRIPTION
**Pull request by emanuele6**
The ebuild is just a copy of remind-04.02.02.ebuild with the files/remind-include-fix.patch patch removed since it has been upstream in version `04.02.03`.

Ref: https://git.skoll.ca/Skollsoft-Public/Remind/commit/d1384a8f698661

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by zpuskas** [comment]
Thanks for the bump, will test it tomorrow.

**Comment by zpuskas** [comment]
I've tested it and it LGTM. Can be merged. Thank you @emanuele6 for the PR.

**Comment by emanuele6** [comment]
`05.00.03` has been released today, should I replace the `05.00.02` ebuild with it, so I keep `05.00.02` and add a separata ebuild for `05.00.03`? (in a different PR?)

**Comment by zpuskas** [comment]
@emanuele6 Just update this PR to be 05.00.03 instead. Once you pushed the updated PR I'll test it for you.

**Comment by zpuskas** [comment]
Tested 05.00.04. Both ebuild and remind itself LGTM, can be merged.

**Pull request closed without merging**
