### PR TITLE
dev-libs/modsecurity: add 3.0.13

### PR DESCRIPTION
**Pull request by hydrapolic**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by juippis — APPROVED** [review]
Hmm,
```
CMP: dev-libs/modsecurity-3.0.12/image with dev-libs/modsecurity-3.0.13/image
   ABI: libmodsecurity.so.3(64) func(+107,-164) vars(+1,-4) [BREAKING]
------> ABI(+108,-168,>B<)
```

**Comment by hydrapolic** [comment]
Thanks @juippis

**Comment by hydrapolic** [comment]
> Hmm,
> 
> ```
> CMP: dev-libs/modsecurity-3.0.12/image with dev-libs/modsecurity-3.0.13/image
>    ABI: libmodsecurity.so.3(64) func(+107,-164) vars(+1,-4) [BREAKING]
> ------> ABI(+108,-168,>B<)
> ```

Haven't observed issues after deploying this version. 

How did you get that output please?

**Comment by juippis** [comment]
I did try compiling nginx with the modsecurity use flag on. It links to libmodsecurity. I added a subslot binder to nginx for it.

You can run **abidiff** from **libabigail** package to compare libraries. https://github.com/ionenwks/iwdevtools?tab=readme-ov-file#qa-cmp iwdevtools can be utilized for that during version bumps.

**Comment by hydrapolic** [comment]
Thanks

**Pull request closed without merging**
