### PR TITLE
media-video/mpv: Version bump (v0.34.1)

### PR DESCRIPTION
**Pull request by FireBurn**
Signed-off-by: Mike Lothian <mike@fireburn.co.uk>

### CODE REVIEW

**Comment by thesamesam** [comment]
@mikhailkoliada

**Comment by ionenwks** [comment]
> mikhailkoliada

Wrong person -- @Zlogene, also in https://github.com/gentoo/gentoo/pull/23605 and maybe others.

**Comment by mikhailkoliada** [comment]
@thesamesam could you please merge it? my setup is still incomplete after relocation

**Comment by thesamesam** [comment]
@mikhailkoliada sure!

**Pull request closed without merging**
