### PR TITLE
app-admin/syslog-ng: Bump to 3.14.1 and fix capability support.

### PR DESCRIPTION
**Pull request by holgersson32644**
Starting syslog-ng as user was broken, mostly due to mistakes in the
daemon file. It closes bug #544766, as the main intention was the
use startup and filecaps bring other implications wrt security.

Closes: https://bugs.gentoo.org/544766
Package-Manager: Portage-2.3.24, Repoman-2.3.6
--
Changes:

-> IUSE="+caps", and add user syslog-ng when caps is set
-> dropped copyright line from hardened config to make file homogen
-# Copyright 1999-2017 Gentoo Foundation
-# Distributed under the terms of the GNU General Public License v2)
-> fixed daemon file/init script (let daemon start as root and drop its right itself + set command_background=1 for PID file generation outside of syslog-ng)
-> enabled python3_5 - upstream doc seem to be outdated

### CODE REVIEW

**Comment by hydrapolic** [comment]
Thanks for the PR :)

Bug https://bugs.gentoo.org/544766 added USE=filecaps, but I don't see it here - was that the intention?

**Comment by holgersson32644** [comment]
Yes, I did that intentionally. The bug report *sounds to me* as the primary goal was to 
run syslog-ng as a non-root user. As the old daemon file had simply a bug (starting syslog-ng as a user via openrc-run instead of starting the binary as root and dropping privileges to the user) the only working way was through filecaps.

filecaps on the other hand have a bit odd smelling, as they need to set specific bits on the binary and everyone that can run the actual binary has automagically the rights of syslog (in case of something like ping I wouldn't care).

So in my eyes working USE="cap" solves the issue. I’ll post a short statement in the bugtracker and ask the reporting user if he’s fine with this.

PS: The old syslog-ng versions aren't touched by this PR, so the mentioned bug in the daemon file exists pre 3.14.1.

**Comment by hydrapolic** [comment]
Enough if we enhance the new version,we won't touch the older ones.

**Comment by hydrapolic** [comment]
Please let's close this and continue with https://github.com/gentoo/gentoo/pull/7384.

**Pull request closed without merging**
