### PR TITLE
libtermkey version update

### PR DESCRIPTION
**Pull request by uxcn**
This is a patch for https://bugs.gentoo.org/show_bug.cgi?id=566692 (https://github.com/neovim/neovim/issues/2048).

### CODE REVIEW

**Comment by mgorny** [comment]
@radhermit ?

**Comment by Tranquility** [comment]
@uxcn thanks, can you please just add the new version without removing the old one. I will merge it afterwards.

**Comment by uxcn** [comment]
@Tranquility, I modified it to preserve the older version.  Is there a policy for removing older versions of packages?

**Comment by Tranquility** [comment]
@uxcn There is no hard policy. It really depends on the package how many old versions you keep behind, but I like to leave at least one to give the user the chance to install an older version, if there are any regressions in the new one.
It is also good to make the commits [atomic](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Atomicity) and not remove the old version in the same commit.

And I should have told you the first time but can you please update the commit subject to add the category? You can see the guide here https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Commit_message_format

**Comment by uxcn** [comment]
Thanks @Tranquility.  I have run into issues in the past where a new version has a bug, and the last good version is removed.  Seemingly even if there's a binary package cached, portage won't recognize it.  I've updated the commit message to match the format described.

Let me know if there are any more issues.

**Comment by Tranquility** [comment]
Thanks, LGTM. I merged it.

**Pull request merged**
