### PR TITLE
Delete gimps-29.4.5.ebuild

### PR DESCRIPTION
**Pull request by PPed72**
Remove old.

Closes: https://bugs.gentoo.org/650562

### CODE REVIEW

**Comment by a17r** [comment]
Please sqash your commits into one.

**Comment by PPed72** [comment]
Ok. Closing, will open a new one.

**Comment by a17r** [comment]
Please don't, just force-push over your existing remote branch.

**Comment by PPed72** [comment]
Too late, sorry. I'll remember for next time, I'm not very good at git.

**Pull request closed without merging**
