### PR TITLE
Sync ::haskell to ::gentoo

### PR DESCRIPTION
**Pull request by solpeth**
cc @trofi 

Another attempt at bringing `::gentoo` in line with `::haskell`. Rather than trying to update every single package in `hackport status --to-portage`, I've decided to focus on synchronising with `::haskell` a handful of key packages that already exist in `::gentoo` - in effect, defining a list of packages that the Gentoo Haskell project will try to maintain in `::gentoo` and keep in sync with `::haskell`. This should help to define the scope of the two ebuild repositories, i.e. `::gentoo` for common haskell packages, `::haskell` for a wider variety of packages (and as a more experimental testing ground). The distinction should not be in which repository is more up to date, which is what currently seems to be the (unintended) distinction. Should this distinction be desirable, I will also adjust `hackport` to emit a warning at the normal verbosity level if the package being bumped should also be bumped in `::gentoo`, or something to that effect, to assist with keeping the repositories in sync.

The packages that I suggest to be part of this group are (and subject to change; ticks indicate that the required commits are already in place):

- [x] `dev-lang/ghc` and its core libraries
- [x] `dev-haskell/cabal-install`
- [x] `dev-haskell/haddock`
- [x] `app-portage/hackport`
- [x] `app-text/pandoc`
- [x] `dev-haskell/hakyll` (see [682978](https://bugs.gentoo.org/682978))
- [x] `dev-haskell/hlint`
- [x] `dev-haskell/stack`
- [x] `dev-haskell/stack-bin`
- [x] `dev-haskell/yesod` and other yesod* packages
- [x] `dev-vcs/darcs`
- [x] `dev-vcs/git-annex` (see [659288](https://bugs.gentoo.org/659288))
- [x] `x11-wm/xmonad`
- [x] `x11-misc/xmobar`

Please add more if appropriate.

The process I am following is:

1. Attempt to add each of these packages to `::gentoo`, and add any missing dependencies along the way. This is all done by directly copying ebuilds from `::haskell`
2. Once the above list is complete, run `repoman -dx scan` on the directories affected, such as `dev-haskell`, `x11-wm` and so on. Fix any repoman warnings by bumping packages. At this point, if we run into conflicts with other packages which have no reverse dependencies but are not a part of the above list (and assuming we decide not to add those packages to the above list), I suggest we mask these packages with a message along the lines of `Scheduled for removal on <date>. Please enable the ::haskell repository to continue to use this package. If you think this removal is incorrect, please open a bug at bugs.gentoo.org`
3. With no `::haskell` repository, build the above list of packages. Everything should build and there should be no circular dependencies.

After step 3 above, this PR should be ready for merging. Given that this would be going into `::gentoo` rather than `::haskell`, I think we would benefit from wider testing than just from me.

Thoughts on this @trofi?

### CODE REVIEW

**Comment by solpeth** [comment]
Update: all of the commits for the above list of package are now in place. I'll be testing this in a chroot over the next little while, and if everything works I'll consider this ready for review. @trofi, would it be possible for you to also test this, if you have time? I will regardless do the testing myself but I would be most grateful for your help.

Side note: a lot of the QA check failures are due to the metadata.xml file having empty <use> elements or long descriptions matching descriptions. That was particularly unexpected given this seems to me to be the status quo for us in `::haskell`, but please let me know if this should be cleaned up before merging.

**Comment by mgorny** [comment]
> Side note: a lot of the QA check failures are due to the metadata.xml file having empty elements or long descriptions matching descriptions. That was particularly unexpected given this seems to me to be the status quo for us in `::haskell`, but please let me know if this should be cleaned up before merging.

Yes, it should. Otherwise, it would introduce a lot of QA warnings in ::gentoo.

**Comment by solpeth** [comment]
@mgorny thank you for the clarification. I'll clean up the `metadata.xml`s which this PR adds and push again when I expect it to be clean.

**Comment by solpeth** [comment]
Update: `ghc-8.8.4` installs as expected in a clean `~amd64` chroot (installed directly, rather than as part of `haskell-platform`). Now working through the conflicts for the above list of packages where I'll push the required changes. Once that's clean, I think this should be ready to go for at least wider testing.

**Comment by solpeth** [comment]
This PR should now be ready for review. Tested in a clean ~amd64 chroot, all packages in the above list successfully build with no circular dependencies with `FEATURES=test` enabled. I propose that any other breakages outside of that list be dealt with as they appear.

@trofi, how does this sound?

**Comment by trofi** [comment]
Sounds good! Pulled everything as is.

That's a massive amount of work. Thank you!

**Comment by solpeth** [comment]
You're welcome! I'll be around for the next little while in case of issues.

**Pull request closed without merging**
