### PR TITLE
www-apps/hugo-0.76.3 version bump

### PR DESCRIPTION
**Pull request by chusopr**

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
Please separate adding a new version and removing old version to 2 different commits.

**Comment by chusopr** [comment]
Fixed!

Although I see very often commits in master that add the new version and remove the old one in one single step.

**Comment by Dessa** [comment]
looks like 0.76.3 is now the latest version

**Comment by chusopr** [comment]
Yes, 0.76.3 was released yesterday. I will update the PR tomorrow.

**Comment by chusopr** [comment]
Updated PR with newer latest version

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
