### PR TITLE
dev-python/python-auto-select: new package

### PR DESCRIPTION
**Pull request by floppym**
Closes: https://bugs.gentoo.org/662422
Package-Manager: Portage-2.3.43_p8, Repoman-2.3.10_p7

### CODE REVIEW

**Comment by floppym** [comment]
This is a rough first draft, so please tear it apart.

I'm not sure about the cat/package name.

**Comment by djc** [comment]
Cool, thanks for working on this!

Let me try to describe the logic here to see if I've gotten it correct: we use `python_foreach_impl` to loop over all Python implementations. `python_foreach_impl` uses the implementations from `_python_obtain_impls`, which loops over `_PYTHON_SUPPORTED_IMPLS`. That in turn contains all implementations from `_PYTHON_ALL_IMPLS` (which are ordered least-preferred to most-preferred -- in practice, earlier to later -- with CPython after other impls), constrained by whether they're supported by the current ebuild.

Q: Your ebuild only states compatibility with CPython; should we not support pypy here, too?

So then, this ebuild will basically pick the latest 2.x and 3.x that is allowed by `PYTHON_TARGETS` and sets it as the default, as soon as this ebuild is installed.

Q: Not sure if the `echoit` stuff is just for debugging, it might make sense to put a more human-friendly `elog` in there if something is changed.

Conceptually it's an interesting problem. I think Gentoo often likes to leave migrations to be done manually by users, which I find sensible. On the other hand, I've explicitly left `PYTHON_TARGETS` undefined so that I get new versions as the python team stabilizes them (and it's good to have this option for users who don't crate that much what version they get). In a sense, maybe this is the wrong choice for me because I actively use Python for a bunch of things and thus my scripts break.

That said, I think installing your ebuild would probably be helpful for me... but I'm not sure it should be pulled in for everyone automatically, as it can be a bit too magic. Although it might work to warn users as part of a news item that this is the behavior and/or is an option for them.

cat/package, maybe `app-eselect/eselect-python-auto`? Since it's pretty tightly coupled to `eselect` and `eselect-python`...

**Comment by floppym** [comment]
> At the moment, eselect-python does not support setting pypy as the system default python. If you run eselect python set pypy, you will get an error stating it is invalid.

Actually, `eselect python set` supports pypy. `eselect python set --python{2,3}` do not. I'm not sure quite how to deal with that.

**Comment by mgorny** [comment]
The way to deal with that is not to use that crap. That `set` interface is merely compatibility cruft for old ebuilds, which causes the issues you're running into in the first place. So instead of making things worse, we could tell users how to fix the mess.

If you want to use the newest version of Python, always, then just clear `python-exec.conf`. Done. You don't need to edit it every Thursday or rely on compat cruft randomly shifting entries inside.

If you want that + `python` preferring python2, just put python2_7 in `python-exec.conf`. Done.

Don't ever use `eselect python set ...` because it doesn't do what you think it does.

**Comment by floppym** [comment]
How do we address the case where python3.7 is installed, but not enabled in PYTHON_TARGETS? An empty python-exec.conf does not work very well for that?

**Comment by mgorny** [comment]
We don't, I guess. If you really want to play with it, don't use `eselect python` and edit `python-exec.conf` directly.

**Comment by floppym** [comment]
@djc Would using an empty python-exec.conf work for you? That would cause /usr/bin/python to default to the greatest version of python3 currently installed.

**Comment by djc** [comment]
I guess? I've never touched that file before, and this is the first time I hear about it.

It's not that I want my `python` to default to the latest version -- I want it to default to a version that has all the dependencies installed in it. As far as I understand it, that does not mean taking the latest version -- it means taking some version that's in `PYTHON_TARGETS`.

**Comment by mgorny** [comment]
Except you'd need to somehow account for the update taking place *after* all packages are upgraded. The truth is, you can't really do it properly without two-step rebuild, i.e.:

1. Rebuilding everything with old+new,
2. Updating `python-exec.conf`,
3. Rebuilding everything with just new.

**Comment by djc** [comment]
So yes, that is the perfect solution which allows all the scripts to keep working continuously, but it's also somewhat expensive in terms of rebuilding all the packages twice.

I guess what I want is, at the end of a python emerge:

- if PV in PYTHON_TARGETS && current default not in PYTHON_TARGETS:
   - make this the default

**Comment by monsieurp** [comment]
@mgorny @djc: what's the status here? can we merge this PR or not?

**Pull request closed without merging**
