### PR TITLE
app-emulation/libvirt-9999: build out of tree

### PR DESCRIPTION
**Pull request by zippy2**
Libvirt forbade in tree builds in preparation to switch to meson:

https://libvirt.org/git/?p=libvirt.git;a=commitdiff;h=f96395e78eaccffbf128336382c74b1250f04032

### CODE REVIEW

**Comment by zippy2** [comment]
@cardoe @tamiko ping?
Please note that current live ebuild is broken and fails to build.

**Comment by cardoe** [comment]
On 11/29/19 2:18 AM, Michal Prívozník wrote:

> @cardoe <https://github.com/cardoe> @tamiko 
> <https://github.com/tamiko> ping?
> Please note that current live ebuild is broken and fails to build.
>
Sorry. My delay here has been that I broke the machine I commit from 
(well its a VM and I broke the underlying box) mixed with the holidays 
in the States. I'll commit this as soon as I can.

--

Doug

**Comment by cardoe** [comment]
Can't currently build this:
```
 * Fetching https://git.savannah.gnu.org/git/gnulib.git/ ...
git fetch https://git.savannah.gnu.org/git/gnulib.git/ --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
fatal: unable to access 'https://git.savannah.gnu.org/git/gnulib.git/': The requested URL returned error: 502
 * ERROR: app-emulation/libvirt-9999::gentoo failed (unpack phase):

**Comment by zippy2** [comment]
> Can't currently build this:
> 
> ```
>  * Fetching https://git.savannah.gnu.org/git/gnulib.git/ ...
> git fetch https://git.savannah.gnu.org/git/gnulib.git/ --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +HEAD:refs/git-r3/HEAD
> fatal: unable to access 'https://git.savannah.gnu.org/git/gnulib.git/': The requested URL returned error: 502
>  * ERROR: app-emulation/libvirt-9999::gentoo failed (unpack phase):
> ```

Yeah, gnulib doesn't have the most reliable server there is. Libvirt's switching over to GLib, but it's a long run. Try again later please.

**Pull request closed without merging**
