### PR TITLE
app-editors/atom: Version bump to 1.15.0.

### PR DESCRIPTION
**Pull request by elprans**
Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=608478

Package-Manager: Portage-2.3.4, Repoman-2.3.1

### CODE REVIEW

**Comment by mpkh** [comment]
@elprans just in case of interest: will it be hard to add 1.16 beta 0 either?

**Comment by elprans** [comment]
> just in case of interest: will it be hard to add 1.16 beta 0 either?

Shouldn't be too hard.

**Comment by mpkh** [comment]
@elprans 1.16?

**Comment by elprans** [comment]
https://github.com/gentoo/gentoo/pull/4518

**Pull request closed without merging**
