### PR TITLE
net-wireless/gnuradio: version bump to 3.8.0.0

### PR DESCRIPTION
**Pull request by cjmayo**
Added modtool USE flag.

Bug: https://bugs.gentoo.org/691960

Package-Manager: Portage-2.3.79, Repoman-2.3.16
Signed-off-by: Chris Mayo <aklhfex@gmail.com>

---

Quite a lot of changes, shown below, I'm happy to talk about any of them.

I haven't tried uhd, jack, oss, or portaudio USE flags, otherwise all tests passing for me (complete suite now used).

net-wireless/uhd is currently Python 2 only, I've attempted to code around that and make repoman happy. repoman also led me to drop ~arm (for dev-python/click-plugins)

```diff
--- gnuradio-3.7.13.5.ebuild
+++ gnuradio-3.8.0.0.ebuild
@@ -2,10 +2,10 @@
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=6
-PYTHON_COMPAT=( python2_7 )
+PYTHON_COMPAT=( python2_7 python3_{6,7} )
 
 CMAKE_BUILD_TYPE="None"
-inherit cmake-utils eutils gnome2-utils python-single-r1 python-utils-r1 xdg-utils
+inherit cmake-utils eutils gnome2-utils python-single-r1 python-utils-r1 virtualx xdg-utils
 
 DESCRIPTION="Toolkit that provides signal processing blocks to implement software radios"
 HOMEPAGE="https://www.gnuradio.org/"
@@ -17,61 +17,52 @@
 	inherit git-r3
 	KEYWORDS=""
 else
-	SRC_URI="https://github.com/gnuradio/gnuradio/releases/download/v${PV}/${P}.tar.xz
-		https://dev.gentoo.org/~zerochaos/patches/${PN}-3.7.13-1-qt5.tar.xz
-		https://dev.gentoo.org/~zerochaos/patches/${PN}-3.7.13-codec2.tar.xz"
-	KEYWORDS="~amd64 ~arm ~x86"
+	SRC_URI="https://github.com/gnuradio/gnuradio/releases/download/v${PV}/${P}.tar.xz"
+	KEYWORDS="~amd64 ~x86"
 fi
-if [[ ${PV} == "3.7.9999" ]]; then
-	EGIT_BRANCH="maint-3.7"
-fi
-
-IUSE="+audio +alsa atsc +analog +digital channels doc dtv examples fcd fec +filter grc jack log noaa oss pager performance-counters portaudio +qt5 sdl test trellis uhd vocoder +utils wavelet wxwidgets zeromq"
+
+IUSE="+audio +alsa +analog +digital channels doc dtv examples fec +filter grc jack modtool oss performance-counters portaudio +qt5 sdl test trellis uhd vocoder +utils wavelet zeromq"
+
+RESTRICT="!test? ( test )"
 
 REQUIRED_USE="${PYTHON_REQUIRED_USE}
-		audio? ( || ( alsa oss jack portaudio ) )
-		alsa? ( audio )
-		oss? ( audio )
-		jack? ( audio )
-		portaudio? ( audio )
-		analog? ( filter )
-		digital? ( filter analog )
-		dtv? ( fec )
-		pager? ( filter analog )
-		qt5? ( filter )
-		uhd? ( filter analog )
-		fcd? ( || ( alsa oss ) )
-		wavelet? ( analog )
-		wxwidgets? ( filter analog )"
-
-# bug #348206
-# comedi? ( >=sci-electronics/comedilib-0.8 )
-# boost-1.52.0 is blacklisted, bug #461578, upstream #513, boost #7669
+	audio? ( || ( alsa oss jack portaudio ) )
+	alsa? ( audio )
+	jack? ( audio )
+	oss? ( audio )
+	portaudio? ( audio )
+	analog? ( filter )
+	channels? ( filter analog qt5 )
+	digital? ( filter analog )
+	dtv? ( filter analog fec )
+	modtool? ( utils )
+	qt5? ( filter )
+	trellis? ( analog digital )
+	uhd? ( filter analog python_targets_python2_7 )
+	vocoder? ( filter analog )
+	wavelet? ( analog )
+"
+
 RDEPEND="${PYTHON_DEPS}
 	>=dev-lang/orc-0.4.12
 	dev-libs/boost:0=[python,${PYTHON_USEDEP}]
-	!<=dev-libs/boost-1.52.0-r6:0/1.52
-	dev-python/mako[${PYTHON_USEDEP}]
+	dev-libs/log4cpp
 	dev-python/six[${PYTHON_USEDEP}]
 	sci-libs/fftw:3.0=
-	alsa? (
-		media-libs/alsa-lib:=
-	)
-	fcd? ( virtual/libusb:1 )
+	sci-libs/mpir
+	alsa? ( media-libs/alsa-lib:= )
+	fec? ( sci-libs/scipy )
 	filter? ( sci-libs/scipy )
 	grc? (
-		dev-python/cheetah[${PYTHON_USEDEP}]
-		dev-python/lxml[${PYTHON_USEDEP}]
-		>=dev-python/pygtk-2.10:2[${PYTHON_USEDEP}]
+		dev-python/mako[${PYTHON_USEDEP}]
 		dev-python/numpy[${PYTHON_USEDEP}]
-	)
-	jack? (
-		media-sound/jack-audio-connection-kit
-	)
-	log? ( dev-libs/log4cpp )
-	portaudio? (
-		>=media-libs/portaudio-19_pre
-	)
+		dev-python/pygobject[${PYTHON_USEDEP}]
+		dev-python/pyyaml[${PYTHON_USEDEP}]
+		x11-libs/gtk+:3[introspection]
+		x11-libs/pango[introspection]
+	)
+	jack? ( media-sound/jack-audio-connection-kit )
+	portaudio? ( >=media-libs/portaudio-19_pre )
 	qt5? (
 		dev-python/PyQt5[opengl,${PYTHON_USEDEP}]
 		dev-qt/qtcore:5
@@ -80,19 +71,23 @@
 		dev-qt/qtwidgets:5
 	)
 	sdl? ( >=media-libs/libsdl-1.2.0 )
-	uhd? ( >=net-wireless/uhd-3.9.6:=[${PYTHON_USEDEP}] )
-	utils? ( dev-python/matplotlib[${PYTHON_USEDEP}] )
-	vocoder? ( media-sound/gsm
-		>=media-libs/codec2-0.8.1 )
-	wavelet? (
-		>=sci-libs/gsl-1.10
-	)
-	wxwidgets? (
-		dev-python/wxpython:3.0[${PYTHON_USEDEP}]
-		dev-python/numpy[${PYTHON_USEDEP}]
-	)
+	trellis? ( sci-libs/scipy )
+	uhd? (
+		$(python_gen_cond_dep '>=net-wireless/uhd-3.9.6:=[${PYTHON_USEDEP}]' python2_7)
+	)
+	utils? (
+		dev-python/click[${PYTHON_USEDEP}]
+		dev-python/click-plugins[${PYTHON_USEDEP}]
+		dev-python/mako[${PYTHON_USEDEP}]
+		dev-python/matplotlib[${PYTHON_USEDEP}]
+	)
+	vocoder? (
+		media-sound/gsm
+		>=media-libs/codec2-0.8.1
+	)
+	wavelet? ( >=sci-libs/gsl-1.10 )
 	zeromq? ( >=net-libs/zeromq-2.1.11 )
-	"
+"
 
 DEPEND="${RDEPEND}
 	app-text/docbook-xml-dtd:4.2
@@ -111,20 +106,10 @@
 src_prepare() {
 	gnome2_environment_reset #534582
 
-	if [[ ${PV} == "9999" ]]; then
-		true
-	else
-		epatch "${FILESDIR}"/gnuradio-wxpy3.0-compat.patch
-	fi
-	# Useless UI element would require qt3support, bug #365019
-	sed -i '/qPixmapFromMimeSource/d' "${S}"/gr-qtgui/lib/spectrumdisplayform.ui || die
-	epatch "${WORKDIR}"/qt5-maint-00*.patch
-	epatch "${WORKDIR}"/codec2-next-00*.patch
-	epatch "${FILESDIR}"/${PN}-3.7.13.5-boost-1.70-asio.patch
-
-	use !alsa && sed -i 's#version.h#version-nonexistant.h#' cmake/Modules/FindALSA.cmake
-	use !jack && sed -i 's#jack.h#jack-nonexistant.h#' cmake/Modules/FindJack.cmake
-	use !portaudio && sed -i 's#portaudio.h#portaudio-nonexistant.h#' cmake/Modules/FindPortaudio.cmake
+	use !alsa && sed -i 's#version.h#version-nonexistent.h#' cmake/Modules/FindALSA.cmake
+	use !jack && sed -i 's#jack.h#jack-nonexistent.h#' cmake/Modules/FindJACK.cmake
+	use !oss && sed -i 's#soundcard.h#oss-nonexistent.h#g' cmake/Modules/FindOSS.cmake
+	use !portaudio && sed -i 's#portaudio.h#portaudio-nonexistent.h#g' cmake/Modules/FindPORTAUDIO.cmake
 
 	cmake-utils_src_prepare
 }
@@ -140,43 +125,31 @@
 		-DENABLE_GR_BLOCKS=ON
 		-DENABLE_GR_FFT=ON
 		-DENABLE_GR_AUDIO=ON
-		-DENABLE_GR_AUDIO_ALSA="$(usex alsa)"
 		-DENABLE_GR_ANALOG="$(usex analog)"
-		-DENABLE_GR_ATSC="$(usex atsc)"
 		-DENABLE_GR_CHANNELS="$(usex channels)"
 		-DENABLE_GR_DIGITAL="$(usex digital)"
 		-DENABLE_DOXYGEN="$(usex doc)"
 		-DENABLE_SPHINX="$(usex doc)"
 		-DENABLE_GR_DTV="$(usex dtv)"
-		-DENABLE_GR_FCD="$(usex fcd)"
 		-DENABLE_GR_FEC="$(usex fec)"
 		-DENABLE_GR_FILTER="$(usex filter)"
 		-DENABLE_GRC="$(usex grc)"
-		-DENABLE_GR_AUDIO_JACK="$(usex jack)"
-		-DENABLE_GR_LOG="$(usex log)"
-		-DENABLE_GR_NOAA="$(usex noaa)"
-		-DENABLE_GR_AUDIO_OSS="$(usex oss)"
-		-DENABLE_GR_PAGER="$(usex pager)"
-		-DENABLE_ENABLE_PERFORMANCE_COUNTERS="$(usex performance-counters)"
-		-DENABLE_GR_AUDIO_PORTAUDIO="$(usex portaudio)"
+		-DENABLE_GR_MODTOOL="$(usex modtool)"
+		-DENABLE_PERFORMANCE_COUNTERS="$(usex performance-counters)"
 		-DENABLE_TESTING="$(usex test)"
 		-DENABLE_GR_TRELLIS="$(usex trellis)"
 		-DENABLE_GR_UHD="$(usex uhd)"
 		-DENABLE_GR_UTILS="$(usex utils)"
 		-DENABLE_GR_VOCODER="$(usex vocoder)"
 		-DENABLE_GR_WAVELET="$(usex wavelet)"
-		-DENABLE_GR_WXGUI="$(usex wxwidgets)"
 		-DENABLE_GR_QTGUI="$(usex qt5)"
-		-DDESIRED_QT_VERSION="$(usex qt5 5)"
 		-DENABLE_GR_VIDEO_SDL="$(usex sdl)"
 		-DENABLE_GR_ZEROMQ="$(usex zeromq)"
-		-DENABLE_GR_CORE=ON
 		-DSYSCONFDIR="${EPREFIX}"/etc
 		-DPYTHON_EXECUTABLE="${PYTHON}"
 		-DGR_PYTHON_DIR="${PYTHON_SITEDIR}"
 		-DGR_PKG_DOC_DIR="${EPREFIX}/usr/share/doc/${PF}"
 	)
-	use vocoder && mycmakeargs+=( -DGR_USE_SYSTEM_LIBGSM=TRUE )
 	cmake-utils_src_configure
 }
 
@@ -211,47 +184,29 @@
 		doicon "${fd_path}/"*.png
 	fi
 
-	python_fix_shebang "${ED}"
+	# Remove incorrectly byte-compiled Python files and replace
+	find "${ED}"/usr/lib -name "*.pyc" -exec rm {} \; || die
+	find "${ED}"/usr/lib -name "*.pyo" -exec rm {} \; || die
+	python_optimize
 }
 
 src_test()
 {
-	ctest -E qtgui
+	virtx cmake-utils_src_test
 }
 
 pkg_postinst()
 {
-	local GRC_ICON_SIZES="32 48 64 128 256"
-
 	if use grc ; then
 		xdg_desktop_database_update
 		xdg_mimeinfo_database_update
-		for size in ${GRC_ICON_SIZES} ; do
-			xdg-icon-resource install --noupdate --context mimetypes --size ${size} \
-				"${EROOT}/usr/share/pixmaps/grc-icon-${size}.png" application-gnuradio-grc \
-				|| die "icon resource installation failed"
-			xdg-icon-resource install --noupdate --context apps --size ${size} \
-				"${EROOT}/usr/share/pixmaps/grc-icon-${size}.png" gnuradio-grc \
-				|| die "icon resource installation failed"
-		done
-		xdg-icon-resource forceupdate
 	fi
 }
 
 pkg_postrm()
 {
-	local GRC_ICON_SIZES="32 48 64 128 256"
-
 	if use grc ; then
 		xdg_desktop_database_update
 		xdg_mimeinfo_database_update
-		for size in ${GRC_ICON_SIZES} ; do
-			xdg-icon-resource uninstall --noupdate --context mimetypes --size ${size} \
-				application-gnuradio-grc || ewarn "icon uninstall failed"
-			xdg-icon-resource uninstall --noupdate --context apps --size ${size} \
-				gnuradio-grc || ewarn "icon uninstall failed"
-
-		done
-		xdg-icon-resource forceupdate
-	fi
-}
+	fi
+}
```

### CODE REVIEW

**Comment by ZeroChaos-** [comment]
cool, I appreciate the effort you put into this.  I'll need to pick this up when I have a bit of time for testing.  I'll add it on my list but probably gonna be a week or so.

**Comment by cjmayo** [comment]
No hurry, definitely worth more testing. I should have said I didn't check Python 2, only that it wouldn't let me have USE="uhd" with Python 3.7.

**Comment by cjmayo** [comment]
Updated with a few more things. I think this is now ready to bump to EAPI 7, but BDEPEND would need creating.

```diff
--- a/net-wireless/gnuradio/gnuradio-3.8.0.0.ebuild
+++ b/net-wireless/gnuradio/gnuradio-3.8.0.0.ebuild
@@ -5,7 +5,7 @@ EAPI=6
 PYTHON_COMPAT=( python2_7 python3_{6,7} )
 
 CMAKE_BUILD_TYPE="None"
-inherit cmake-utils eutils gnome2-utils python-single-r1 python-utils-r1 virtualx xdg-utils
+inherit cmake-utils desktop python-single-r1 python-utils-r1 virtualx xdg-utils
 
 DESCRIPTION="Toolkit that provides signal processing blocks to implement software radios"
 HOMEPAGE="https://www.gnuradio.org/"
@@ -56,7 +56,7 @@ RDEPEND="${PYTHON_DEPS}
 	grc? (
 		dev-python/mako[${PYTHON_USEDEP}]
 		dev-python/numpy[${PYTHON_USEDEP}]
-		dev-python/pygobject[${PYTHON_USEDEP}]
+		dev-python/pygobject:3[${PYTHON_USEDEP}]
 		dev-python/pyyaml[${PYTHON_USEDEP}]
 		x11-libs/gtk+:3[introspection]
 		x11-libs/pango[introspection]
@@ -104,7 +104,7 @@ DEPEND="${RDEPEND}
 "
 
 src_prepare() {
-	gnome2_environment_reset #534582
+	xdg_environment_reset #534582
 
 	use !alsa && sed -i 's#version.h#version-nonexistent.h#' cmake/Modules/FindALSA.cmake
 	use !jack && sed -i 's#jack.h#jack-nonexistent.h#' cmake/Modules/FindJACK.cmake
@@ -199,6 +199,7 @@ pkg_postinst()
 {
 	if use grc ; then
 		xdg_desktop_database_update
+		xdg_icon_cache_update
 		xdg_mimeinfo_database_update
 	fi
 }
@@ -207,6 +208,7 @@ pkg_postrm()
 {
 	if use grc ; then
 		xdg_desktop_database_update
+		xdg_icon_cache_update
 		xdg_mimeinfo_database_update
 	fi
 }
```

**Comment by cjmayo** [comment]
I think this is my last update. I'll turn my attention upstream now.

I can't see that these pixmaps do anything:
```
/usr/share/pixmaps/grc-icon-128.png
/usr/share/pixmaps/grc-icon-16.png
/usr/share/pixmaps/grc-icon-24.png
/usr/share/pixmaps/grc-icon-256.png
/usr/share/pixmaps/grc-icon-32.png
/usr/share/pixmaps/grc-icon-48.png
/usr/share/pixmaps/grc-icon-64.png
```
and the MIME and desktop file are being installed OK.

```diff
--- a/net-wireless/gnuradio/gnuradio-3.8.0.0.ebuild
+++ b/net-wireless/gnuradio/gnuradio-3.8.0.0.ebuild
@@ -5,7 +5,7 @@ EAPI=6
 PYTHON_COMPAT=( python2_7 python3_{6,7} )
 
 CMAKE_BUILD_TYPE="None"
-inherit cmake-utils desktop python-single-r1 python-utils-r1 virtualx xdg-utils
+inherit cmake-utils python-single-r1 python-utils-r1 virtualx xdg-utils
 
 DESCRIPTION="Toolkit that provides signal processing blocks to implement software radios"
 HOMEPAGE="https://www.gnuradio.org/"
@@ -170,23 +170,12 @@ src_install() {
 		rm -rf "${ED}"/usr/share/doc/${PF}/xml || die
 	fi
 
-	# We install the mimetypes to the correct locations from the ebuild
+	# Remove duplicated icons, MIME and desktop files and installation script
 	rm -rf "${ED}"/usr/share/${PN}/grc/freedesktop || die
 	rm -f "${ED}"/usr/libexec/${PN}/grc_setup_freedesktop || die
 
-	# Install icons, menu items and mime-types for GRC
-	if use grc ; then
-		local fd_path="${S}/grc/scripts/freedesktop"
-		insinto /usr/share/mime/packages
-		doins "${fd_path}/${PN}-grc.xml"
-
-		domenu "${fd_path}/"*.desktop
-		doicon "${fd_path}/"*.png
-	fi
-
 	# Remove incorrectly byte-compiled Python files and replace
-	find "${ED}"/usr/lib -name "*.pyc" -exec rm {} \; || die
-	find "${ED}"/usr/lib -name "*.pyo" -exec rm {} \; || die
+	find "${ED}"/usr/lib -name "*.py[co]" -exec rm {} \; || die
 	python_optimize
 }
```

**Comment by cjmayo** [comment]
Updated gsl dependency and commit message for https://bugs.gentoo.org/703450

```diff
--- a/gnuradio-3.8.0.0.ebuild
+++ b/gnuradio-3.8.0.0.ebuild
@@ -51,7 +51,10 @@
 	sci-libs/fftw:3.0=
 	sci-libs/mpir
 	alsa? ( media-libs/alsa-lib:= )
-	fec? ( sci-libs/scipy )
+	fec? (
+		sci-libs/gsl
+		sci-libs/scipy
+	)
 	filter? ( sci-libs/scipy )
 	grc? (
 		dev-python/mako[${PYTHON_USEDEP}]
@@ -85,7 +88,7 @@
 		media-sound/gsm
 		>=media-libs/codec2-0.8.1
 	)
-	wavelet? ( >=sci-libs/gsl-1.10 )
+	wavelet? ( sci-libs/gsl )
 	zeromq? ( >=net-libs/zeromq-2.1.11 )
 "
```

**Comment by cjmayo** [comment]
Drop python-utils-r1.

**Comment by cjmayo** [comment]
I have an update for new PYTHON_SINGLE_USEDEP/PYTHON_MULTI_USEDEP but repoman won't allow it to be commited:
* to keep supporting Python 2.7, dev-python/click-plugins would need Python 2 support added back
* to go Python 3 only, net-wireless/uhd would need Python 3 support

**Comment by ZeroChaos-** [comment]
Thanks @cjmayo, I finally got around to adding 3.8.x.x and your work was super helpful!  3.8.1.0 is in the tree, hope it works well.

**Pull request closed without merging**
