### PR TITLE
sci-calculators/bc-gh: add 7.0.3 and delete old unstable versions

### PR DESCRIPTION
**Pull request by gavinhoward**
---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
The CI issue is unrelated.

**Comment by gavinhoward** [comment]
Yeah, Sam said so on IRC, but he also told me to rebase after he fixed it.

**Comment by eli-schwartz** [comment]
Did he fix it? I was under the impression that it's a pkgcheck bug. And indeed it failed again. :)

**Comment by gavinhoward** [comment]
I think you're right. Sorry.

**Pull request closed without merging**
