### PR TITLE
media-gfx/iscan-plugin-gt-f720: bump to EAPI=7

### PR DESCRIPTION
**Pull request by 4z0r**
Signed-off-by: Ovidiu - Dan Bogat <4z0r@ovidiu.at>

### CODE REVIEW

**Comment by 4z0r** [comment]
Do not mind the linked bug for this PR! ( 406425 )

This PR should only handle the EAPI bump to 7 and a resulting cleanup for 'versionator' and the Package name.

The linked bug describes a "version bump" and I've created a separate PR for that in #10296

**Comment by a17r** [comment]
Why two PRs for the same package though?

**Comment by 4z0r** [comment]
one (this one) was an EAPI bump from 4 to 7 with the plugin version remaining the same (so the scanner should still work as expected) with the iscan plugin version remaining at 0.1.2. I've used this to better get acquainted with the ebuild / plugin itself.

the other pr is a pure version bump of the plugin. a whole new ebuild to version 1.1.2 (again with EAPI 7) and the keywords set to ~(amd64 and x86).

**Comment by 4z0r** [comment]
Both ebuilds will provide a firmware bin which has not changes at all (except for the timestamp, 2009 and 2011).

The provided library however changes, and thus the version bump with a separate PR. 

This PR is for media-gfx/iscan-plugin-gt-f720/iscan-plugin-gt-f720-0.0.1.2.ebuild (already part of the tree):
```bash
gentoo ~/esci-interpreter-gt-f720-0.0.1-2.i386/usr/lib/esci # md5sum libesci-interpreter-gt-f720.so.0.0.0
15416fe0b0583d176cb9270025f191cd  libesci-interpreter-gt-f720.so.0.0.0
```
which contains only an EAPI bump and a versioning cleanup within the ebuild (due to EAPI 7).

The other pr with the version bump would be a new ebuild file into the tree with a changed library (namely to handle both architectures I've thus keyworded them with ~) "iscan-plugin-gt-f720-0.1.1.2.ebuild":

```bash
gentoo ~/iscan-gt-f720-bundle-1.0.1.x64.rpm/plugins/esci-interpreter-gt-f720-0.1.1-2.x86_64/usr/lib64/esci # md5sum libesci-interpreter-gt-f720.so.0.0.0
bca998f4ab5b6d07ce396d5b56e5d0e4  libesci-interpreter-gt-f720.so.0.0.0
```

Firmware bin esfw8b.bin is the same in both versions.

Mentioning the Bug 406425 in this PR might have a bit unfortunate in retrospect since it asked specifically for a version bump of the library / plugin. Sorry.

**Comment by 4z0r** [comment]
I've squashed the commits into 1 and cleaned up the format of the commit message

**Comment by 4z0r** [comment]
I'll close this PR as I've merged this EAPI bump to the version bump PR #10296

**Pull request closed without merging**
