### PR TITLE
mail-mta/postfix: systemd hardening

### PR DESCRIPTION
**Pull request by candrews**
https://bugs.gentoo.org/show_bug.cgi?id=586994

### CODE REVIEW

**Comment by candrews** [comment]
I've set CapabilityBoundingSet to a value that works. I think we could do better, though... CapabilityBoundingSet should (ideally) be a whitelist (not a blacklist). I think someone more familiar with postfix's internal implementation could set this to a more secure value. In any case, what I've submitted works, so at least it won't break anything, and it's better than Gentoo does today.

**Comment by Polynomial-C** [comment]
I'm neither a postfix maintainer nor do I even have the tiniest interest in systemd crap.

**Comment by monsieurp** [comment]
@candrews the bug number for this issue is incorrect as it points to a different bug (apache2). sorry @Polynomial-C for the wrong assignation.

**Comment by rich0** [comment]
merged into gentoo

**Pull request closed without merging**
