### PR TITLE
media-tv/tvheadend: add epatch_user to src_prepare

### PR DESCRIPTION
**Pull request by herrnst**
Allow for automatic apply of patched dropped in /etc/portage/patches/.

Repoman 2.3.3 (portage-2.3.13)

### CODE REVIEW

**Comment by a17r** [comment]
It is not necessary to open another PR while you are working on an existing one for the same ebuild.

**Comment by herrnst** [comment]
Oh, ok. Will take note of this for the next time, thanks. Was just following common advice to create one pull per feature/subject.

**Comment by SoapGentoo** [comment]
also, please prefer porting ebuilds to EAPI 6 and relying on its `eapply_user` than the epatch abomination

**Comment by kensington** [comment]
Thanks for your contribution! Unfortunately, this was since obsoleted by f3544384630a818ea97571db41ee93919ad9c719.

**Pull request closed without merging**
