### PR TITLE
Port various to cmake.eclass

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by candrews** [comment]
At a glance, the packages assigned to me. I trust that you've made a sane change :)

**Comment by a17r** [comment]
Thanks for your trust. Btw, I'm also seeing `-DCMAKE_INSTALL_PREFIX="${EPREFIX}/usr/"` in some ebuilds and I am going to drop that. It is of course already done by cmake.eclass.

**Comment by swegener** [comment]
app-arch/brotli fails to build with these changes:

```
>>> Unpacking source...
>>> Unpacking brotli-1.0.7.tar.gz to /var/tmp/portage/app-arch/brotli-1.0.7/work
>>> Source unpacked in /var/tmp/portage/app-arch/brotli-1.0.7/work
>>> Preparing source in /var/tmp/portage/app-arch/brotli-1.0.7/work/brotli-1.0.7 ...
 * Will copy sources from /var/tmp/portage/app-arch/brotli-1.0.7/work/brotli-1.0.7_build
 * python2_7: copying to /var/tmp/portage/app-arch/brotli-1.0.7/work/brotli-1.0.7_build-python2_7
cp: cannot stat '/var/tmp/portage/app-arch/brotli-1.0.7/work/brotli-1.0.7_build': No such file or directory
 * ERROR: app-arch/brotli-1.0.7::gentoo failed (prepare phase):
 *   (no error message)
```

**Comment by candrews** [comment]
All media-plugins/kodi-* packages and net-libs/quiche fail too.

@a17r can you please fix this issue (or revert the change)?

Thanks!

**Comment by a17r** [comment]
that shouldn't happen, I'll investigate.

**Comment by a17r** [comment]
@swegener: app-arch/brotli is not reproducible here, when did you last sync?

**Comment by a17r** [comment]
@candrews missed to check kodi-addons, but it is easily fixable, sorry.

**Comment by a17r** [comment]
Both net-libs/quiche and app-arch/brotli reverted, error is strange but ebuilds are also strange. Need more investigation what's causing the difference in behaviour.

**Comment by candrews** [comment]
Thanks for addressing these issues so quickly - and don't worry about it, it's software and we're human, stuff happens :-)

**Pull request merged**
