### PR TITLE
dev-lang/rust: add 1.62.0, drop 1.61.0-r1

### PR DESCRIPTION
**Pull request by Kelvium**
Signed-off-by: Nikita Romanyuk <kelvium@yahoo.com>

### CODE REVIEW

**Comment by Kelvium** [comment]
Should not be merged until ~gyakovlev has rust-bin 1.62.0 tarball at 'https://dev.gentoo.org/~gyakovlev/distfiles/dev-lang/rust-bin/rust-1.62.0-sparc64-unknown-linux-gnu.tar.xz'

**Comment by gyakovlev** [comment]
did you even test that? =)

Please, test PRs before opening.
there are 3 patches that would not apply, but you did not remove those. `src_prepare()` phase will fail.

I'll close the PR, I'm working on bump right now, will land very soon.
bumping rust is not simple copy of ebuild and update to manifest.

I have very brief checklist documented here:
https://wiki.gentoo.org/wiki/User:GYakovlev/Rust_bump

**Comment by gyakovlev** [comment]
also we don't drop old versions right away, especially on major bump, not a revbump.

it's ok to rename from 1.61.0-r1 to 1.61.0-r2 (sometimes)
but it's not ok to simply mv 1.61.0-r1 to 1.62.0

**Comment by Kelvium** [comment]
got it =)

**Comment by gyakovlev** [comment]
fyi, just landed. enjoy.

**Pull request closed without merging**
