### PR TITLE
[WONTFIX] syslog-ng: Add filecaps support for non-root start.

### PR DESCRIPTION
**Pull request by holgersson32644**
@hydrapolic's version bump in https://github.com/gentoo/gentoo/pull/7384 works only with USE="caps" and root, not with other users.

If @hydrapolic doesn't complain I’d like to add myself as another proxied maintainer.

Edit: My previous commits introduced a serious bug into the daemon/init script while trying to get syslog-ng started with USE="-filecaps caps" as a user. This won't work, so I dropped it, fixed stuff and rebased.

### CODE REVIEW

**Comment by orlitzky** [comment]
I think the name of the new flag should be `USE=filecaps` instead of `USE=extra-caps`?

The `fcaps` should be done in `src_install`, on the copy of the binary in `${D}`. If you use a relative path, the `${D}` should be prepended for you.

I think the additional "chown" is to fix the group on existing installs that were made without filecaps? If so, it could probably be `chown --no-dereference --from=:root syslog-ng`, and wrapped in a `REPLACING_VERSIONS` check with a comment about why it's there.

Otherwise, I don't know enough about capabilities to be of much help. It seems to me that anyone with `CAP_CHOWN` can trivially gain root, so it's a lot of trouble (and with a scary setuid binary) to let non-root users who must be completely trusted anyway run this. Probably someone with more imagination has a good reason for doing that, though.

**Comment by Whissi** [comment]
@orlitzky I disagree regarding naming of USE flags. *Filecaps* should be used when the ebuild sets file capabilities in _pkg_postinst_ (note that this doesn't work in _src_install_!), also see [fcaps eclass](https://devmanual.gentoo.org/eclass-reference/fcaps.eclass/) and https://packages.gentoo.org/useflags/filecaps.

And caps is used when we link against libcap, i.e. the resulting binary is able to drop privs on its own.

**Comment by orlitzky** [comment]
@Whissi nevermind, you're right about the flag name.

For "fcaps", when you call it yourself, I think it will work in src_install? That's what the documentation suggests anyway -- I think it's only when you use `FILECAPS=( ... )` that it uses pkg_postinst. And using pkg_postinst is unsafe for the same reasons that calling "chown" in postinst is unsafe, so I'm afraid to even go look at the existing uses in the tree...

**Comment by Whissi** [comment]
Well, calling fcaps in src_install works but I think the binary package is unable to record set capabilities, see fcap's eclass note:

>  Due to probable capability-loss on moving or copying, this happens in pkg_postinst-phase (at least for now). 

So when you build syslog-ng on a build host with filecaps USE flag set and install the binary package on the client, no capabilities are set. That's why you should set capabilities in pkg_postinst which will be executed even on binary merge.

Isn't it only unsafe when doing this in locations writable for normal users? syslog-ng ebuild from this PR for example is calling fcaps on /usr/sbin/... should be safe, not?

**Comment by holgersson32644** [comment]
To avoid confusion I renamed extra-caps into extra-filecaps (as they set more *filecaps* and don't touch the "normal" ones) - this is not yet commited or pushed.

@orlitzky, I read the article on your [Website](https://michael.orlitzky.com/articles/end_root_chowning_now_(make_pkg_postinst_great_again).xhtml). I can move the chown as fown into src_install, but then I need to move also the enewuser to pkg_setup, as portage needs to know the user syslog-ng first. This works, but would create a user syslog-ng on e.g. buildservers aswell (correct me if I’m wrong here).

The fcaps command can't be moved though as it's described in the fcaps eclass (due to the loss of fcaps when copying the file).


@hydrapolic Great ;-)

**Comment by orlitzky** [comment]
> Isn't it only unsafe when doing this in locations writable for normal users? syslog-ng ebuild from this PR for example is calling fcaps on /usr/sbin/... should be safe, not?

Right. This usage is safe, but the eclass happily calls chown/chmod on the paths that you give it, on the live filesystem. There's no attempt made to ensure that they're not in user-owned directories, so it's the other ebuilds using `FILECAPS=()` that I worry about.

I haven't checked (of course =) but I would bet that the eclass uses pkg_postinst for the same reason that chown is called in pkg_postinst here: portage won't update file capabilities on a pre-existing file. So just like with owner/group changes, you need to fix the filecaps somehow? Maybe. Anyway, I didn't mean to derail the discussion =P

**Comment by holgersson32644** [comment]
@orlitzky & @Whissi: This all sounds to me as the initial approach is far from perfect but in this case OK. I just pushed the changes (IUSE="extra-filecaps" instead of "extra-caps") and if you don't have further objections I’ll ping one of you later when the QA bot ran again.

**Comment by Whissi** [comment]
Please move

> enewuser syslog-ng

into _pkg_setup_ phase. Remember that _pkg_postinst_ phase can fail but at this time, the PM has already merged the image onto user's system.

I am also not happy about the "extra-*" thing and the idea itself: Why are you doing this at all? I guess to improve security. However, a process with "cap_dac_override" is already privileged in a way that I prefer running directly as root instead of hiding the fact that this process can become root all the time. I.e. you are giving the user the impression "Hey, syslog-ng became more secure because we are now running as dedicated user instead of root"... however, the dedicated user can use the process' privileges (capabilities) to get root instantly...

**Comment by holgersson32644** [comment]
The main idea was to a) improve security,  and b) add the filecaps support that was requested by another user in https://bugs.gentoo.org/544766.
wrt a): syslog-ng has a --caps parameter, that should specify the used capabilites but often fails even with examples from the upstream documentation. Without the --caps parameter syslog-ng catches *all* caps it could possible get (according to pscap).
With filecaps and non-root startup the defacto used caps are more limited.
This PR is a workaround for upstream issues (or one in our daemon file I didn't find yet).

**Comment by Whissi** [comment]
Well, like said, replacing root by a separated user who will run the service but grant root permissions to the binary via Linux capabilities is a bad idea to my knowledge and doesn't improve security -- quite the opposite especially when you stop using a working _libcap_ implementation due to that. But feel free to convince me that I am wrong. :)

I strongly disagree with the user comment [from the patch](https://bugs.gentoo.org/attachment.cgi?id=399956):

```diff
+pkg_setup() {
+	if use caps; then
+		ewarn "\"caps\" USE flag is only useful for limiting privileges when running syslog-ng as root."
+		ewarn "It is suggested to use \"filecaps\" instead and run as syslog-ng user."
+	fi
+}
```
I still don't know _syslog-ng_. When build with `--enable-linux-caps`, i.e. linked against _libcap_, what will happen if you start the service as root? I.e. how is _libcap_ used?

I now read that _syslog-ng_ (the daemon) supports a `--caps` parameter. I would suggest top drop filecaps usage at all and update runscript and its conf file to add support for daemon's args instead. This will allow an user interested in that feature to pass his/her individual settings.

**Comment by kensington** [comment]
Some packages use pkg_postinst to set caps because there are several bugs in portage (bug #649524 is one such example) causing caps set in src_install not to make it to the live filesystem.

**Comment by holgersson32644** [comment]
> But feel free to convince me that I am wrong. :)

Too late, happend the other way around. I fear I got blinded by the non-root user ignoring the relevant capability impact :-/
Upstream offers two different mechanisms:
i) using caps which works to some extend
ii) dropping rights with --user and --group

@hydrapolic can you actually run syslog-ng with the current in-tree daemon file (/etc/init.d/syslog-ng)? Unfortunately I can't (neither with nor without USE="caps").


I think I should do the following:
- provide a working caps line in a comment in /etc/conf.d/syslog-ng, where the daemon args are specified (and commit that without a revbump)
- if non-root startup works, explain what steps are necessary (and note the drawbacks)
- if it doesn't work: fix if possible or drop the SYSLOG_NG_USER and _GROUP variables
to avoid confusion of other users. I would use ewarn in postinstall and a revbump to notify users about this changed use.
- keep this filecaps implementation, enable caps by default (USE="caps") and print a big fat warning in pkg_setup() and a fixed commit message.

**Comment by hydrapolic** [comment]
Thank you guys very much for the input, appreciated :)

@holgersson32644, yes, 3.14.1 works for me on multiple machines (with/without caps). What error do you get? What is your configuration? I'm using the hardened configuration without much modifications.

We don't need to pass any special --caps options to syslog-ng:
https://syslog-ng.com/documents/html/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html/syslog-ng.8.html

```
If the --no-caps option is not set,syslog-ng OSE has been compiled with the --enable-linux-caps compile option, and the host supports CAP_SYSLOG, syslog-ng OSE uses the following capabilities: "cap_net_bind_service, cap_net_broadcast, cap_net_raw, cap_dac_read_search, cap_dac_override, cap_chown, cap_fowner=p cap_syslog=ep"
```

It's enough to compile with USE=caps and don't set --no-caps:

```
# pscap  | grep syslog-ng
1     1715  root        syslog-ng         full
1715  1716  root        syslog-ng         chown, dac_override, dac_read_search, fowner, net_bind_service, net_broadcast, net_raw, syslog +
```

For non-root setups simply set SYSLOG_NG_GROUP/SYSLOG_NG_USER. Tested on a machine with logs owned by the user and it worked properly. Why do you want to drop thes variables?

In order to improve security, we could default to USE=+caps, I agree.

**Comment by holgersson32644** [comment]
@hydrapolic, root startup works fine, of course.
> Why do you want to drop these variables?

That was just meant as the last option if they don't work and can't get fixed. As we speak about it: When I try to start syslog-ng as an user I get (with USE="-caps" withouth the cap error message, of course):
```Starting syslog-ng ...
syslog-ng         |syslog-ng: Error setting capabilities, capability management disabled; error='Operation not permitted'
syslog-ng         |[2018-03-15T10:44:17.928699] Error opening control socket, bind() failed; socket='/run/syslog-ng.ctl', error='Address already in use (98)'
syslog-ng         |[2018-03-15T10:44:17.938010] system(): The kernel message buffer is not readable, please check permissions if this is unintentional.; device='/proc/kmsg', error='Permission denied (13)'
syslog-ng         |[2018-03-15T10:44:17.941810] Error binding socket; addr='AF_UNIX(/dev/log)', error='Address already in use (98)'
syslog-ng         |[2018-03-15T10:44:17.941839] Error initializing message pipeline; plugin name='unix-dgram', location='source generator system:4:14'
syslog-ng         |\ * start-stop-daemon: failed to start `/usr/sbin/syslog-ng'
syslog-ng         | * Failed to start syslog-ng                                                                                  [ !! ]
syslog-ng         | * ERROR: syslog-ng failed to start
```

**Comment by hydrapolic** [comment]
Running syslog-ng as a regular user gives sense for example to read from the network and save to a file (maybe aggregate logs). For regular local syslog I would compile with USE=caps and start as root as it will drop unnecessary caps.

**Comment by holgersson32644** [comment]
@hydrapolic, valid point. There is another issue:
filecaps is enforce active by the fcaps eclass through IUSE="+filecaps", and the only workaround seems to be a package.use entry in the base profile (thanks floppym ;).

For a use case we shouldn't encourage and that I want "just to support" that is IMHO too much tree fiddling. I therefore close this PR, and paste the ebuild into the original bug with an explanation why caps should be preferred and would ask you, @hydrapolic, to close it as WONTFIX (if you can do that as assignee). Any objections?

**Comment by hydrapolic** [comment]
I think we can leave the bug open if anyone else has the same thing in mind because maybe we can do it in a better way maybe later on, who knows.

The +caps is a good idea for the next release, the network gathering you mean running as unprivileged user?

**Comment by holgersson32644** [comment]
> […] the network gathering you mean running as unprivileged user?

Yes, exactly.

> I think we can leave the bug open if anyone else has the same thing in mind because maybe we can do it in a better way maybe later on, who knows.

I can live with that — however, I’m closing this PR now ;)

**Pull request closed without merging**
