### PR TITLE
mail-filter/amavisd-new: Upstream release 2.12.0

### PR DESCRIPTION
**Pull request by rseichter**
This ebuild uses EAPI 7 and introduces mutually exclusive USE flags `rspamd` and `rspamd-https` to support Amavis' new [Rspamd extension](https://gitlab.com/amavis/amavis/blob/v2.12.0/RELEASE_NOTES).

### CODE REVIEW

**Comment by orlitzky** [comment]
I'm guessing you dropped the ppc64 keyword because it's missing for some of the new dependencies? When that happens, you have to file a bug notifying the arch team for the keyword that was dropped:

https://devmanual.gentoo.org/keywording/index.html#keywording-on-upgrades

And with the move to `EAPI=7`, we'll have to sort out the new dependency class:

https://dev.gentoo.org/~mgorny/articles/the-ultimate-guide-to-eapi-7.html#build-time-dependencies-split-into-depend-and-bdepend

Of the two existing build-dependencies, I think perl and sed definitely need to be in BDEPEND. Only perl needs to be in RDEPEND. And I don't know what needs to be in DEPEND. Probably only perl, or nothing at all. Someone on the perl team has probably already figured this out.

**Comment by orlitzky** [comment]
And we don't have to do this right away, but [GLEP81](https://www.gentoo.org/glep/glep-0081.html) was approved last week. At some point we should [reserve a UID/GID](https://wiki.gentoo.org/wiki/Project:Quality_Assurance/UID_GID_Assignment) (probably 333, to match Arch) and create separate user/group packages for amavis.

**Comment by rseichter** [comment]
> I'm guessing you dropped the ppc64 keyword because it's missing for some of the new dependencies?

Quite so, Repoman reported fatal issues:
```
> repoman -dx full

RepoMan scours the neighborhood...
  RDEPEND.suspect               2
   mail-filter/amavisd-new/amavisd-new-2.11.1-r3.ebuild: 'app-arch/cabextract'
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: 'app-arch/cabextract'
  dependency.bad [fatal]        5
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: RDEPEND: ~ppc64(default/linux/powerpc/ppc64/17.0/64bit-userland)
['dev-perl/LWP-UserAgent-Determined']
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: RDEPEND: ~ppc64(default/linux/powerpc/ppc64/17.0/64bit-userland/desktop)
['dev-perl/LWP-UserAgent-Determined']
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: RDEPEND: ~ppc64(default/linux/powerpc/ppc64/17.0/64bit-userland/desktop/gnome)
['dev-perl/LWP-UserAgent-Determined']
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: RDEPEND: ~ppc64(default/linux/powerpc/ppc64/17.0/64bit-userland/desktop/gnome/systemd)
['dev-perl/LWP-UserAgent-Determined']
   mail-filter/amavisd-new/amavisd-new-2.12.0.ebuild: RDEPEND: ~ppc64(default/linux/powerpc/ppc64/17.0/64bit-userland/developer)
['dev-perl/LWP-UserAgent-Determined']
Please fix these important QA issues first.
```

> When that happens, you have to file a bug notifying the arch team for the keyword that was dropped

Understood, I will do that.

> And with the move to `EAPI=7`, we'll have to sort out the new dependency class

Do you know somebody on the Perl team that could help us decide what needs to be in DEPEND et al?

**Comment by rseichter** [comment]
> At some point we should reserve a UID/GID

GLEP 81 states "Before adding a new user and/or group, the developer must send a RFC to the gentoo-dev mailing list". I believe I am allowed to post on gentoo-dev, but since I am not an official developer, I wonder if you'd prefer sending that RFC yourself? I am not shying away from it, but you are the official ebuild maintainer.

**Comment by orlitzky** [comment]
> Do you know somebody on the Perl team that could help us decide what needs to be in DEPEND et al?

I didn't have anyone in particular in mind, but anyone who's bumped a perl ebuild to EAPI 7 should have some idea. I would just ask in #gentoo-perl on IRC and see if anyone responds.

> I wonder if you'd prefer sending that RFC yourself? I am not shying away from it, but you are the official ebuild maintainer.

We've only had a few of these, but so far the trend is to send the patch set to the mailing list which then constitutes your RFC, e.g.

  * https://archives.gentoo.org/gentoo-dev/message/a12405317dc2452c06f6df92ea831c4e
  * https://archives.gentoo.org/gentoo-dev/message/7a02b8a393fad11c5bd69430f3ceb3c9
  * https://archives.gentoo.org/gentoo-dev/message/e953d4cacb974ee1db62773d30d77f63

If you create the new user/group packages, you would have to `git send-email` those patches, because I wouldn't have them. A link to a pull request might also work, though, and I could send that if you want.

**Comment by kentfredric** [comment]
> Of the two existing build-dependencies, I think perl and sed definitely need to be in BDEPEND. Only perl needs to be in RDEPEND. And I don't know what needs to be in DEPEND. Probably only perl, or nothing at all. Someone on the perl team has probably already figured this out.

I don't understand, how can I help? 

```
[05:40:25] <Morbius> Hello. Would somebody here be willing to have a look at https://github.com/gentoo/gentoo/pull/12581 (the latest Amavis ebuild) re DEPEND/RDEPEND/BDEPEND? I want to update from EAPI 6 to 7 (among other things), and MJO and I are wondering about the dependencies.
[07:13:19] <-- Morbius (~Morbius@p200300E2D70E6E005C907BCDAED32584.dip0.t-ipconnect.de) has quit (Quit: Textual IRC Client: www.textualapp.com)

[23:16:45] <Morbius> I tried IRC by the way, but got no response, so I thought I'd try the mention.
```
You may have to wait a little longer than one hour for a response, some of us have other things to do :)

**Comment by rseichter** [comment]
> I don't understand, how can I help?

With the move to EAPI 7, I'd like a person with better Perl knowledge to check if I populated BDEPEND, RDEPEND and DEPEND correctly. I assume that DEPEND can remain empty, given that the various Perl modules are only required at runtime. Is that correct? I'm not sure if @orlitzky has questions beyond that point.

> You may have to wait a little longer than one hour for a response, some of us have other things to do :)

As do I. 😉 I could not stick around for longer than 90 minutes yesterday, so I asked about the proper way to mention the Perl team on GitHub. Turns out I don't have the necessary privileges, so thank you for answering to my call nonetheless.

**Comment by kentfredric** [comment]
> With the move to EAPI 7, I'd like a person with better Perl knowledge to check if I populated BDEPEND, RDEPEND and DEPEND correctly. I assume that DEPEND can remain empty, given that the various Perl modules are only required at runtime. Is that correct? I'm not sure if @orlitzky has questions beyond that point.

Hard to say at scale as dev-perl/ and friends don't support EAPI7 yet ( perl-module.eclass yet to be updated ), and so I haven't had experience with this in practice.

I'd say that based on this definition:

> Dependencies that need to be run during the build, and therefore must run on the system used to build packages (CBUILD). Those include toolchain, build system tooling (autotools, CMake), various language interpreters (Perl, Python), preprocessors (SWIG) and other tools (e.g. pkg-config). Those are placed in BDEPEND now.

That yes, perl should probably be in BDEPEND and not in DEPEND.

But I'm not fully aware of how this will affect anything that links to libperl, which might happen if you have any XS components, or components that say, embed a perl interpreter.

**Comment by kentfredric** [comment]
>>    When that happens, you have to file a bug notifying the arch team for the keyword that was dropped

> Understood, I will do that.

Even if you don't, my tools *might* notice organically and it *might* just get entered into one of my bulk-requests :)

**Comment by rseichter** [comment]
If you have not found an obvious flaw in the current dependency definitions, I'm content. Thanks for checking. As for the dropped ppc64 flag, I filed [this bug report](https://bugs.gentoo.org/691340).

**Comment by orlitzky** [comment]
Shower insight: do we need perl *at all* for the build? This isn't like spamassassin where there's a Makefile.PL to process. As far as I can see, the entire build/install process is done manually with dobin, dodoc, etc. Maybe we don't need perl in either BDEPEND or DEPEND.

**Comment by orlitzky** [comment]
It looks like sed is redundant for the same reason. We only use it in the ebuild, and the PMS guaranteed that it will exist there:

https://dev.gentoo.org/~ulm/pms/head/pms.html#x1-11800012.1.1

**Comment by orlitzky** [comment]
Since `USE=rspamd-https` does what `USE=rspamd` does and more, do you really want portage to throw an error if both are set? In other words, if I have `USE=rspamd rspamd-http`, then modulo that `REQUIRED_USE` line, everything would work as expected.

Otherwise, LGTM and I'll merge it.

**Comment by rseichter** [comment]
> Since `USE=rspamd-https` does what `USE=rspamd` does and more, do you really want portage to throw an error if both are set?

I thought about that before I chose to add REQUIRED_USE. `rspamd-https` offers a superset of the `rspamd` functionality, and I did not know how to properly set the dependencies in this case. Hence, I thought that making the flags mutually exclusive would be a reasonable approach.

Dropping REQUIRED_USE would mean that the contents of MY_RSPAMD_DEPEND would appear twice in RDEPEND if the user sets both flags. I thought that might be a problem, but perhaps it is not?

**Comment by orlitzky** [comment]
If you ever _have_ to, you could separate the clauses into three conditions: if one is set, if the other is set, if both are set.... sometimes you wind up doing that in the src/pkg phases when there are a lot of interacting USE flags. But, for dependencies, it doesn't matter. The package manager doesn't mind duplicates.

**Comment by orlitzky** [comment]
:thumbsup:

**Pull request closed without merging**
