### PR TITLE
net-voip/murmur: Changed doc_contents from murmurd to mumble-server.

### PR DESCRIPTION
**Pull request by GrataHonoria**
Trying the command in the doc_contents results in:
`murmurd: command not found`
But the command:
`mumble-server -ini /etc/murmur/murmur.ini -supw <pw>`
works.

### CODE REVIEW

**Comment by DarkDefender** [comment]
I also ran into this issue.
Additionally the line after this one doesn't seem to be correct either.
`chown murmur:murmur /var/lib/murmur/murmur.sqlite`
After running `mumble-server -ini /etc/murmur/murmur.ini -supw <pw>`
The sqlite database is instead created in `/etc/murmur/murmur.sqlite`

In addition to that, the openrc scripts also doesn't seem to work.
It fails to start with:
```
* Starting murmur ...
murmurd: failed to open logfile murmur.log: no logging will be done
* start-stop-daemon: did not create a valid pid in `/run/murmur/murmur.pid'
* Failed to start murmur
* ERROR: murmur failed to start
```

**Comment by 0xC0ncord** [comment]
> The sqlite database is instead created in /etc/murmur/murmur.sqlite

It seems like at some point the default location for where it gets created has changed. I never noticed this since I always had it manually specified, but I was able to confirm the issue.

> In addition to that, the openrc scripts also doesn't seem to work. [...]

Looks like just making the init script write the PID file to `/run/murmur.pid` instead of `/run/murmur/murmur.pid` would be the simplest solution.

**Comment by DarkDefender** [comment]
Sorry for the log wait. I got it to work, but I needed to:
1. Set the `pidfile` option to `/run/murmur/murmur.pid` in `.ini` config file

2. Change `logfile` setting to `/var/log/murmur/murmur.log` in ini file

3. Specify the data base location (`database`) to `/var/lib/murmur/database.sqlite` in the ini file
Otherwise it would complain that the database was read only and wouldn't start.

4. Needed to add `avahi-daemon` to `use` in the depend section in the `init.d` script to get zeroconf functionality to work.

**Comment by 0xC0ncord** [comment]
Superseded by #30788

**Pull request closed without merging**
