### PR TITLE
dev-java/commons-codec: bump to 1.15

### PR DESCRIPTION
**Pull request by vaukai**
Before I start excluding tests:
```
Time: 36.468
There were 3 failures:
1) testSha224_PathAsHex(org.apache.commons.codec.digest.DigestUtilsTest)
java.nio.file.NoSuchFileException: src/test/resources/org/apache/commons/codec/empty.bin
        at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
        at java.base/sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:219)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:371)
        at java.base/java.nio.file.Files.newByteChannel(Files.java:422)
        at java.base/java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:420)
        at java.base/java.nio.file.Files.newInputStream(Files.java:156)
        at org.apache.commons.codec.digest.DigestUtils.updateDigest(DigestUtils.java:1485)
        at org.apache.commons.codec.digest.DigestUtils.digest(DigestUtils.java:1632)
        at org.apache.commons.codec.digest.DigestUtils.digestAsHex(DigestUtils.java:1713)
        at org.apache.commons.codec.digest.DigestUtilsTest.testSha224_PathAsHex(DigestUtilsTest.java:343)
2) testDigestAs(org.apache.commons.codec.digest.DigestUtilsTest)
java.io.FileNotFoundException: src/test/resources/org/apache/commons/codec/empty.bin (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.apache.commons.codec.digest.DigestUtils.updateDigest(DigestUtils.java:1418)
        at org.apache.commons.codec.digest.DigestUtils.digest(DigestUtils.java:1602)
        at org.apache.commons.codec.digest.DigestUtils.digestAsHex(DigestUtils.java:1683)
        at org.apache.commons.codec.digest.DigestUtilsTest.testDigestAs(DigestUtilsTest.java:121)
3) testSha224_FileAsHex(org.apache.commons.codec.digest.DigestUtilsTest)
java.io.FileNotFoundException: src/test/resources/org/apache/commons/codec/empty.bin (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:219)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.apache.commons.codec.digest.DigestUtils.updateDigest(DigestUtils.java:1418)
        at org.apache.commons.codec.digest.DigestUtils.digest(DigestUtils.java:1602)
        at org.apache.commons.codec.digest.DigestUtils.digestAsHex(DigestUtils.java:1683)
        at org.apache.commons.codec.digest.DigestUtilsTest.testSha224_FileAsHex(DigestUtilsTest.java:330)

FAILURES!!!
Tests run: 1157,  Failures: 3
```
Having the kernel compiled with `CONFIG_MODULE_SIG_SHA224=y` did not help :-(

### CODE REVIEW

**Comment by vaukai** [comment]
One test excluded:
```
1 warning
JUnit version 4.13.2-SNAPSHOT
.................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................Test with String : 4003 millis
Test with StringBuilder : 3494 millis
Test with cached String : 2778 millis
Test with cached StringBuilder : 3186 millis
...................Time for encoding 80,000 times the input 'Angelo': 7,959 millis.
......................................................................................................................................................................................................................................................................................................I.......................................................................................
Time: 36.046

OK (1121 tests)
```

**Comment by fordfrog** [comment]
it's probably a path being different when running the tests our way, just recently i had to tweak apache rat for the same reason. i will have a look at it.

**Comment by fordfrog** [comment]
settings `S` to something more standard fixed the tests, see 0325d58168f7924895881e1284210b0380cc5f8b

**Comment by fordfrog** [comment]
@vaukai thanks! i also removed the unused file, see 9afc58be0192edc1faa1a8c26b8ca75d0d4235b2

**Comment by vaukai** [comment]
> settings `S` to something more standard fixed the tests, see [0325d58](https://github.com/gentoo/gentoo/commit/0325d58168f7924895881e1284210b0380cc5f8b)

Yes, sometimes adjusting `S` does help.  In this case I didn't see the solution :-(

**Comment by fordfrog** [comment]
i suppose it's always safer to set `S` for maven-built projects to the dir where `src` dir is present.

**Comment by vaukai** [comment]
@fordfrog 
Please don't forget (after waiting some days) to cc-arces on https://bugs.gentoo.org/784128

**Pull request closed without merging**
