### PR TITLE
app-misc/mosquitto: added systemd notify support

### PR DESCRIPTION
**Pull request by expeditioneer**
Closes: https://bugs.gentoo.org/878969

### CODE REVIEW

**Comment by mattst88** [comment]
Would be nice to have a commit message to explain... anything about what we're doing here.

Barring that, let me see what I can deduce.

So the diff between this and the existing mosquitto ebuild is

````diff
--- mosquitto-2.0.15.ebuild	2023-03-01 12:17:53.933406362 -0500
+++ mosquitto-2.0.15-r1.ebuild	2023-03-21 23:26:35.230597552 -0400
@@ -12,7 +12,7 @@
 
 LICENSE="EPL-1.0"
 SLOT="0"
-KEYWORDS="amd64 arm ~arm64 x86"
+KEYWORDS="~amd64 ~arm ~arm64 ~x86"
 IUSE="bridge examples +persistence +srv ssl tcpd test websockets"
 RESTRICT="!test? ( test )"
 
@@ -51,6 +51,7 @@
 		WITH_BRIDGE="$(usex bridge)" \
 		WITH_PERSISTENCE="$(usex persistence)" \
 		WITH_SRV="$(usex srv)" \
+		WITH_SYSTEMD="$(usex systemd ON OFF)" \
 		WITH_TLS="$(usex ssl)" \
 		WITH_WEBSOCKETS="$(usex websockets)" \
 		WITH_WRAP="$(usex tcpd)" \
@@ -100,7 +101,7 @@
 	doins mosquitto.conf
 	insinto /usr/share/mosquitto
 	doins misc/letsencrypt/mosquitto-copy.sh
-	systemd_dounit "${FILESDIR}/mosquitto.service"
+	systemd_newunit "${FILESDIR}/mosquitto.notify.service" mosquitto.service
 
 	if use examples; then
 		docompress -x "/usr/share/doc/${PF}/examples"
````

Okay, so set `WITH_SYSTEMD` based on the `systemd` USE flag... except

````
 *   USE Flag 'systemd' not in IUSE for app-misc/mosquitto-2.0.15-r1
````

Okay, so totally untested as well \o/

Beyond that, replace the existing `mosquitto.service` file which uses `Type=simple` with one that uses `Type=notify`. Some explanation of why that is better would be nice, but I see that mosquitto actually provides a service file (that uses `Type=notify`) — `service/systemd/mosquitto.service.notify`. Why don't we just use that? I expect that one has been tested.

**Comment by mattst88** [comment]
Additionally,

````c
#ifdef WITH_SYSTEMD
#  include <systemd/sd-daemon.h>
#endif
[...]
#ifdef WITH_SYSTEMD
	sd_notify(0, "READY=1");
#endif
````

Presumably we need a dependency on `sys-apps/systemd`.

**Comment by expeditioneer** [comment]
> 
> Okay, so totally untested as well \o/
> 

To my defense - not totally untested but badly tested. Since i only executed via `ebuild` and not `emerge`.

**Comment by mattst88** [comment]
Thanks!

**Pull request closed without merging**
