### PR TITLE
Various cleanups

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Review by sarnex — APPROVED** [review]
Reviewed shaderc changes

**Review by Pesa — APPROVED** [review]
Thanks

**Comment by a17r** [comment]
@sarnex thanks!

**Review by SoapGentoo — APPROVED** [review]
Thanks for taking care of this

**Comment by akhuettel** [comment]
For some reason the ci-bot does not pick up the libreoffice-bin breakage. Please remove old boost only after libreoffice-bin-6.4.7.2_p1 is also stable on amd64.

**Comment by akhuettel** [comment]
@a17r , you know, we do have some irc channels for communication?

**Comment by a17r** [comment]
> For some reason the ci-bot does not pick up the libreoffice-bin breakage.

Not sure what you mean: Commit e03bf063baf8f1a990ccf039688b00688cc64517

**Comment by akhuettel** [comment]
> > For some reason the ci-bot does not pick up the libreoffice-bin breakage.
> 
> Not sure what you mean: Commit [e03bf06](https://github.com/gentoo/gentoo/commit/e03bf063baf8f1a990ccf039688b00688cc64517)

Oh sorry, my fault. Go ahead then.. :+1:

**Review by prometheanfire — APPROVED** [review]

**Review by perfinion — APPROVED** [review]
ACK, yeah long overdue for these to go. Thanks for taking care of this :)

**Pull request merged**
