### PR TITLE
dev-ml/ocaml-pcap: new ebuild

### PR DESCRIPTION
**Pull request by tomboy-64**
- needed as a transitive dependency of Libre S3 1.1 (net-misc/libres3)
- explicit support for MirageOS is not enabled

@aballier

### CODE REVIEW

**Comment by aballier** [comment]
this one fails to build here:
```
>>> Configuring source in /var/tmp/portage/dev-ml/ocaml-pcap-0.3.3/work/ocaml-pcap-0.3.3 ...
File "setup.ml", line 213, characters 8-26:
Warning 3: deprecated: String.set
Use Bytes.set instead.
File "setup.ml", line 1793, characters 6-24:
Warning 3: deprecated: Lazy.lazy_from_fun
Use Lazy.from_fun instead.
ocamlfind: Package `cstruct.syntax' not found
W: Field 'pkg_cstruct_syntax' is not set: Command ''/usr/bin/ocamlfind' query -format %d cstruct.syntax > '/var/tmp/portage/dev-ml/ocaml-pcap-0.3.3/temp/oasis-777e81.txt'' terminated with error code 2
E: Cannot find findlib package cstruct.syntax
E: Failure("1 configuration error")
 * ERROR: dev-ml/ocaml-pcap-0.3.3::gentoo failed (configure phase):
 *   (no error message)
 * 
```

**Comment by tomboy-64** [comment]
@aballier should be fixed now. try again.

**Comment by aballier** [comment]
please add a commit making camlp4 useflag default on ocaml-cstruct then; otherwise it'd annoy ppl that want to install it :)

**Comment by tomboy-64** [comment]
@aballier Okay, looks good to me. lgtm.

**Comment by aballier** [comment]
thx, merged!

**Pull request closed without merging**
