### PR TITLE
net-misc/curl: backport one more noproxy regression patch to 7.86.0

### PR DESCRIPTION
**Pull request by henning-schild**
Signed-off-by: Henning Schild <henning@hennsch.de>

### CODE REVIEW

**Comment by henning-schild** [comment]
Not sure the "git mv" was right or if we need r2 and r3 because r2 is already stable for some arches.

**Comment by thesamesam** [comment]
> Not sure the "git mv" was right or if we need r2 and r3 because r2 is already stable for some arches.

I've dropped back to ~arch for that reason in a new revision, yeah. Thanks for the PR!

**Comment by thesamesam** [comment]
Patch doesn't apply:
```
 * Applying curl-7.86.0-noproxy-tailmatch-like-in-7.85.0-and-earlier.patch ...
patching file docs/libcurl/opts/CURLOPT_NOPROXY.3
Hunk #1 succeeded at 41 (offset 1 line).
patching file lib/noproxy.c
Hunk #1 succeeded at 183 (offset -4 lines).
patching file tests/unit/unit1614.c
Hunk #1 FAILED at 85.
1 out of 1 hunk FAILED -- saving rejects to file tests/unit/unit1614.c.rej                                                                                                                               [ !! ]
 * ERROR: net-misc/curl-7.86.0-r3::gentoo failed (prepare phase):
 *   patch -p1  failed with /var/tmp/portage/net-misc/curl-7.86.0-r3/files/curl-7.86.0-noproxy-tailmatch-like-in-7.85.0-and-earlier.patch
 *
```

:(

**Comment by henning-schild** [comment]
@thesamesam Thanks for fixing and taking care!

**Pull request closed without merging**
