### PR TITLE
eclass: ELT-patches: Add support for cross library linking

### PR DESCRIPTION
**Pull request by g-braeunlich**
Gentoo-Bug: https://bugs.gentoo.org/590404

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. eclass changes must be discussed on the gentoo-dev mailing list first. Please send your diff there. I'm closing this PR for the time being but feel free to reopen it once developers have signed off on your changes. Cheers.

**Comment by monsieurp** [comment]
The mailing list address is: gentoo-dev@gentoo.org

**Comment by g-braeunlich** [comment]
Do you mean gentoo-dev@lists.gentoo.org?

**Comment by monsieurp** [comment]
Indeed. Thanks for correcting me.

**Pull request closed without merging**
