### PR TITLE
media-libs/waffle: Put libX11 behind existing USE=X

### PR DESCRIPTION
**Pull request by lanodan**
Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

### CODE REVIEW

**Comment by mattst88** [comment]
It should be more than that, right? With `USE=-X` I see

> Dependency x11-xcb skipped: feature glx disabled

so I think libxcb should be conditional as well. Maybe also xcb-proto? You'll have to check.

Also there's a 9999 ebuild. Please update it too.

**Comment by mattst88** [comment]
Ping?

**Comment by lanodan** [comment]
Done, as noted in the commit message I also removed `virtual/opengl` as mesa is already in the dependencies.

**Comment by mattst88** [comment]
Thanks!

**Pull request closed without merging**
