### PR TITLE
x11-misc/mugshot: bump to version 0.4.2

### PR DESCRIPTION
**Pull request by ConiKost**
Also added python3.7 support and bumped to EAPI=7.

Closes: https://bugs.gentoo.org/696564
Package-Manager: Portage-2.3.76, Repoman-2.3.17
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by juippis** [comment]
```
>>> Source compiled.
>>> Test phase: dev-python/python-distutils-extra-2.39-r1
 * python2_7: running distutils-r1_run_phase python_test
============================== test session starts ===============================
platform linux2 -- Python 2.7.16, pytest-4.5.0, py-1.5.4, pluggy-0.12.0 -- /usr/bin/python2.7
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/python-distutils-extra-2.39-r1/work/python-distutils-extra-2.39
collecting ... collected 26 items / 9 deselected / 17 selected

test/auto.py::T::test_apport_hook PASSED                                   [  5%]
test/auto.py::T::test_binary_files PASSED                                  [ 11%]
test/auto.py::T::test_data PASSED                                          [ 17%]
test/auto.py::T::test_dbus PASSED                                          [ 23%]
test/auto.py::T::test_empty PASSED                                         [ 29%]
test/auto.py::T::test_etc PASSED                                           [ 35%]
test/auto.py::T::test_gsettings PASSED                                     [ 41%]
test/auto.py::T::test_help_docbook PASSED                                  [ 47%]
test/auto.py::T::test_help_mallard PASSED                                  [ 52%]
test/auto.py::T::test_icons PASSED                                         [ 58%]
test/auto.py::T::test_manpages PASSED                                      [ 64%]
test/auto.py::T::test_scripts PASSED                                       [ 70%]
test/auto.py::T::test_sdist PASSED                                         [ 76%]
test/auto.py::T::test_standard_files PASSED                                [ 82%]
test/auto.py::T::test_ui PASSED                                            [ 88%]
test/auto.py::T::test_utf8_filenames PASSED                                [ 94%]
test/auto.py::T::test_vcs PASSED                                           [100%]

==================== 17 passed, 9 deselected in 2.38 seconds =====================
 * python3_5: running distutils-r1_run_phase python_test
============================== test session starts ===============================
platform linux -- Python 3.5.7, pytest-4.5.0, py-1.5.4, pluggy-0.12.0 -- /usr/bin/python3.5
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/python-distutils-extra-2.39-r1/work/python-distutils-extra-2.39
collecting ... collected 26 items / 9 deselected / 17 selected

test/auto.py::T::test_apport_hook PASSED                                   [  5%]
test/auto.py::T::test_binary_files PASSED                                  [ 11%]
test/auto.py::T::test_data PASSED                                          [ 17%]
test/auto.py::T::test_dbus PASSED                                          [ 23%]
test/auto.py::T::test_empty PASSED                                         [ 29%]
test/auto.py::T::test_etc PASSED                                           [ 35%]
test/auto.py::T::test_gsettings PASSED                                     [ 41%]
test/auto.py::T::test_help_docbook PASSED                                  [ 47%]
test/auto.py::T::test_help_mallard PASSED                                  [ 52%]
test/auto.py::T::test_icons PASSED                                         [ 58%]
test/auto.py::T::test_manpages PASSED                                      [ 64%]
test/auto.py::T::test_scripts PASSED                                       [ 70%]
test/auto.py::T::test_sdist PASSED                                         [ 76%]
test/auto.py::T::test_standard_files PASSED                                [ 82%]
test/auto.py::T::test_ui PASSED                                            [ 88%]
test/auto.py::T::test_utf8_filenames PASSED                                [ 94%]
test/auto.py::T::test_vcs PASSED                                           [100%]

==================== 17 passed, 9 deselected in 3.43 seconds =====================
 * python3_6: running distutils-r1_run_phase python_test
============================== test session starts ===============================
platform linux -- Python 3.6.9, pytest-4.5.0, py-1.5.4, pluggy-0.12.0 -- /usr/bin/python3.6
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/python-distutils-extra-2.39-r1/work/python-distutils-extra-2.39
collecting ... collected 26 items / 9 deselected / 17 selected

test/auto.py::T::test_apport_hook PASSED                                   [  5%]
test/auto.py::T::test_binary_files PASSED                                  [ 11%]
test/auto.py::T::test_data PASSED                                          [ 17%]
test/auto.py::T::test_dbus PASSED                                          [ 23%]
test/auto.py::T::test_empty PASSED                                         [ 29%]
test/auto.py::T::test_etc PASSED                                           [ 35%]
test/auto.py::T::test_gsettings PASSED                                     [ 41%]
test/auto.py::T::test_help_docbook PASSED                                  [ 47%]
test/auto.py::T::test_help_mallard PASSED                                  [ 52%]
test/auto.py::T::test_icons PASSED                                         [ 58%]
test/auto.py::T::test_manpages PASSED                                      [ 64%]
test/auto.py::T::test_scripts PASSED                                       [ 70%]
test/auto.py::T::test_sdist PASSED                                         [ 76%]
test/auto.py::T::test_standard_files PASSED                                [ 82%]
test/auto.py::T::test_ui PASSED                                            [ 88%]
test/auto.py::T::test_utf8_filenames PASSED                                [ 94%]
test/auto.py::T::test_vcs PASSED                                           [100%]

==================== 17 passed, 9 deselected in 3.43 seconds =====================
 * python3_7: running distutils-r1_run_phase python_test
============================== test session starts ===============================
platform linux -- Python 3.7.4, pytest-4.5.0, py-1.5.4, pluggy-0.12.0 -- /usr/bin/python3.7
cachedir: .pytest_cache
rootdir: /tmp/portage/dev-python/python-distutils-extra-2.39-r1/work/python-distutils-extra-2.39
collecting ... collected 26 items / 9 deselected / 17 selected

test/auto.py::T::test_apport_hook FAILED                                   [  5%]
test/auto.py::T::test_binary_files PASSED                                  [ 11%]
test/auto.py::T::test_data PASSED                                          [ 17%]
test/auto.py::T::test_dbus PASSED                                          [ 23%]
test/auto.py::T::test_empty PASSED                                         [ 29%]
test/auto.py::T::test_etc PASSED                                           [ 35%]
test/auto.py::T::test_gsettings PASSED                                     [ 41%]
test/auto.py::T::test_help_docbook PASSED                                  [ 47%]
test/auto.py::T::test_help_mallard PASSED                                  [ 52%]
test/auto.py::T::test_icons PASSED                                         [ 58%]
test/auto.py::T::test_manpages PASSED                                      [ 64%]
test/auto.py::T::test_scripts PASSED                                       [ 70%]
test/auto.py::T::test_sdist PASSED                                         [ 76%]
test/auto.py::T::test_standard_files PASSED                                [ 82%]
test/auto.py::T::test_ui PASSED                                            [ 88%]
test/auto.py::T::test_utf8_filenames PASSED                                [ 94%]
test/auto.py::T::test_vcs PASSED                                           [100%]

==================================== FAILURES ====================================
_______________________________ T.test_apport_hook _______________________________

self = <auto.T testMethod=test_apport_hook>

        def test_apport_hook(self):
            '''Apport hooks'''

            self._mksrc('apport/foo.py', '''import os, apport
    def add_info(report):
        pass
    ''')

            self._mksrc('apport/source_foo.py', '''import os, apport
    def add_info(report):
        pass
    ''')

            (o, e, s) = self.do_install()
            self.assertFalse('following files are not recognized' in o, o)

            f = self.installed_files()
>           self.assertEqual(len(f), 3, f) # 2 hook files plus .egg-info
E           AssertionError: 0 != 3 : []

test/auto.py:198: AssertionError
=============== 1 failed, 16 passed, 9 deselected in 3.11 seconds ================
 * ERROR: dev-python/python-distutils-extra-2.39-r1::testworld failed (test phase)
```
all other tests pass except python-3.7, so I'm a bit sceptical ;)

**Comment by ConiKost** [comment]
> all other tests pass except python-3.7, so I'm a bit sceptical ;)

My bad, I had should run the tests by my self, somehow I missed that. I did now update to an even newer version, 2.42. That one works with python3.7 according to the changelog and locally all tests pass.

**Comment by juippis** [comment]
```
 * The ebuild is installing to one or more unexpected paths:
 * 
 *   /usr/share/doc/mugshot
 * 
 * Please fix the ebuild to use correct FHS/Gentoo policy paths.
```
any chance to fix this?

**Comment by ConiKost** [comment]
Added some workaround, it's the same, as ```catfish/catfish``` is doing.

**Comment by juippis** [comment]
Thanks!

**Pull request closed without merging**
