### PR TITLE
media-sound/podget: verbump to 0.8

### PR DESCRIPTION
**Pull request by Coacher**
Package-Manager: portage-2.3.0_rc1

### CODE REVIEW

**Comment by Coacher** [comment]
CC @gentoo/proxy-maint, @Kitcat490

**Comment by gktrk** [comment]
LGTM, waiting for the other maintainer's ack.

**Comment by Kitcat490** [comment]
Unfortunately podget seems to have some issues with config files created by the current version and gives this error: 

`kitcat490@r52 ~ $ podget
podget
/home/kitcat490/.podget/podgetrc was created by an older version of podget than is needed by this version.

This version of podget requires a configuration produced for version 0.7.0 or newer.  This configuration
was produced by version 0.8

Please update your configuration by creating a new one with the command 'podget --create-config <FILENAME>'
and then comparing its contents to your old configuration.  Once the new file has been updated to reflect
your desired configuration, move it in place of the old one.

Closing session.
`

I'll report the bug upstream. Probably best to wait on the update until that gets fixed.

**Comment by Kitcat490** [comment]
https://github.com/dvehrs/podget/issues/12

**Comment by Coacher** [comment]
Upstream doesn't want to do a bugfix release yet.
I've updated the 0.8 ebuild to workaround the aforementioned bug for now.

**Comment by Kitcat490** [comment]
Okay, everything seems to be working nicely now

**Pull request closed without merging**
