### PR TITLE
app-crypt/keybase: fixing non-working KBFS (needs SUID)

### PR DESCRIPTION
**Pull request by thinrope**
Bug: https://bugs.gentoo.org/649634
Reported-by: Kalin KOZHUHAROV <kalin@thinrope.net>

Updating both 1.0.44 and 9999 with the same logic.
I guess I don't need to update the Manifest...
@nicolasbock please guide me if I need to do something better (for the next time).

### CODE REVIEW

**Comment by nicolasbock** [comment]
Thanks @thinrope I will give it a whirl.

**Comment by ArsenArsen** [comment]
Any updates on this? I've found the changes work to fix `run_keybase` (and the underlying `keybase-mount-helper`)

**Comment by thinrope** [comment]
I haven't had any issues for over a month, did a few rebuilds of the package. The newly released upstream 1.0.47 though seems to break things again, no simple revbump possible.
But I guess we should get this working 1.0.44 in the tree at least!

**Comment by thinrope** [comment]
Closing, please move to PR #8108 @nicolasbock or anybody else :-D

**Comment by nicolasbock** [comment]
Sorry @thinrope for dropping the ball on this. I will have a look at #8108 . Thanks!

**Pull request closed without merging**
