### PR TITLE
media-plugins/ir_lv2: version bump to 1.3.4 + add zero-latency version

### PR DESCRIPTION
**Pull request by puleglot**
Closes: https://bugs.gentoo.org/417395
Closes: https://bugs.gentoo.org/655968

### CODE REVIEW

**Comment by puleglot** [comment]
Depends on https://github.com/gentoo/gentoo/pull/12210 (=media-libs/zita-convolver-4*)

**Comment by fordfrog** [comment]
looks good to me, though i'd prefer patching Makefile rather than using sed as sed is a "blind" fix whereas patch simply stops to apply when something changes. also not sure whether it is needed to slot the 1.2 branch. imo it would be sufficient to put info in 1.3 branch postinst that if user wants zero latency, she should mask 1.3 branch. that would also prevent two versions being installed at the same time and the package block would not be needed. or am i missing something?

**Comment by puleglot** [comment]
> looks good to me, though i'd prefer patching Makefile rather than using sed as sed is a "blind" fix whereas patch simply stops to apply when something changes. 

I agree, will do that. Also the first sed statement is not needed anymore, so the patch will be small (if compared with 1.3.2).

> also not sure whether it is needed to slot the 1.2 branch. imo it would be sufficient to put info in 1.3 branch postinst that if user wants zero latency, she should mask 1.3 branch. that would also prevent two versions being installed at the same time and the package block would not be needed. or am i missing something?

The benefit of a slot is that it can be recorded in a world file. nginx ebuild is doing the same for example. On the other hand this is indeed abusing the slot concept and portage doesn't store slot in a world file if only one slot is installed. So I will probably remove slotting.

**Comment by fordfrog** [comment]
thank you! :-)

**Pull request closed without merging**
