### PR TITLE
[CI] LLVM 3.5.0 cleanup

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/x11, @gentoo/qt.

**Comment by Civil** [comment]
@grobian I think MacOS X Prefix still rely on old LLVM 3.5, right?

**Comment by mgorny** [comment]
> @grobian I think MacOS X Prefix still rely on old LLVM 3.5, right?

Yes, that's why I plan to keep newest version from each 'branch' indefinitely, i.e. 3.5.2. I think that's what was originally requested, and since LLVM keeps compatibility for major.minor.* that should be fine.

**Comment by grobian** [comment]
agreed, 3.5.2 is fine

**Comment by mgorny** [comment]
@Pesa, could you confirm lastriting of qtopenvg?

**Comment by mattst88** [comment]
Mesa changes look good to me. Thanks!

**Comment by Pesa** [comment]
> @Pesa, could you confirm lastriting of qtopenvg?

Yeah absolutely. Thanks.

**Pull request closed without merging**
