### PR TITLE
Jdk9 slot updates

### PR DESCRIPTION
**Pull request by labre**
(repeating latest commit message)
dev-java/java-sdk-docks-1.9.0.1: new slot; version bump
dev-java/oracle-jdk-bin-1.9.0.1: new slot; adapted ebuild
dev-java/oracle-jre-bin-1.9.0.1: new slot; adapted ebuild
virtual/jdk-1.9.0: new slot; adapted since icedtea{,-bin}:9 unavailable
virtual/jre-1.9.0: new slot; version bump

Current issues:

– vm symlink is broken because JAVA_HOME is parsed incorrectly by
  java-vm-2 eclass. The string is passed unexpanded. This is the main
  remaining issue.
  
– Classpath in env is incorrect, because all referenced jars have been
  removed. However JDK9 seems to have introduced a module system,
  which supposedly makes it obsolete. At least small stuff is
  compiling with the correct symlink.

– derby use flag is either obsolete or the referenced files have been
  renamed. It’s commented out for now.

– virtual/jdk can’t depend on icedtea{-bin}:9 for now, because they
  are unavailable. This would cause issues, if something depends on
  virtual/jre:1.9, because that depends on jdk:1.9, thus pulling in
  ocacle-jdk-bin:1.9, which may be undesired.

Please add the work-in-progress and help-needed tags. I never intended
to create the complete slot update, I just was surprised, that I got
this far as a user, that never took a second look into those ebuilds.

Finished:

JDK/JRE ebuilds

– All download file names have been updated.

– Tracking from librt.jar does not cause sandbox violations anymore,
  because it is inexistent. (Commented out)

– File paths in jdk were preceeded by jre/, which is obsolete. The
  wildcard in the jre ebuild could be obsolete, although it does not
  break anything.

– COPYRIGHT has been moved to legal/java.base/COPYRIGHT. Corrected it.

– Demos are not a vailable yet.  Emptied the array for now.  File names have yet to be corrected; I can’t predict them completely.

– 32bit arches have been removed, since there are no downloads for them.

– JCE relevant code has been removed, because it is now part of the
  main downloads.

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks @labre. Could you rebase your commits and rewrite the history of this PR? You've pulled from master and merged changes back which messes up everything. If it's too complicated, simply close this PR and file another one.

**Comment by labre** [comment]
Closing this PR for now, such that it”s branched from a clean upstream master.

**Comment by monsieurp** [comment]
:D I posted my comment exactly when you closed the PR! That is clearly magic. Maybe our minds can communicate?

**Comment by chewi** [comment]
As mentioned, I don't know when we'll get to this but I'll try my best.

Please be aware that this isn't the first PR we've had for Oracle's Java 9. I don't know whether that one dealt with any of the issues you mentioned.

We don't want to version this as 1.9.x.x any more, please use 9.x.x and just 9 for the virtuals.

**Comment by chewi** [comment]
See #1721.

**Comment by labre** [comment]
Damned. I should have checked that, before. I’ll rebase my PR on that one (can’t push to that branch) and check for the issues to persist. Don’t have seen any handling of it, though, so I assume, that it persists.

**Pull request closed without merging**
