### PR TITLE
net-misc/seafile-client: Fix Qt5 selection

### PR DESCRIPTION
**Pull request by moschlar**
Followup to #4489.
Also fixes wrong path to ` ${P}-only-use-qttest-where-needed.patch` 😊.

### CODE REVIEW

**Comment by moschlar** [comment]
I thought that, too, but I couldn't get it to work on the first try, so I figured to keep it similar to upstream for the time being...

But now it works - although only with the intermediary variable `DETECTED_QT_VERSION`...
Dunno why...

**Comment by mgorny** [comment]
> But now it works - although only with the intermediary variable `DETECTED_QT_VERSION`...

I suppose that's a custom variable invented by upstream. For a proper upstream patch you'd probably want to replace all occurrences of it. However, if they are spread too much, I think what you did here is fine for Gentoo uses.

@Pesa, is this good?

**Comment by moschlar** [comment]
@pesa, it's not! ;-)

**Comment by mgorny** [comment]
I've merged this but accidentally pasted the wrong thing.

```
commit 0b01ca373c77869e8ea182cc848428a738c2fc22
Author:     Moritz Schlarb <moschlar@metalabs.de>
AuthorDate: Wed Apr 26 19:29:21 2017
Commit:     Michał Górny <mgorny@gentoo.org>
CommitDate: Thu Apr 27 16:33:29 2017

    net-misc/seafile-client: Fix Qt5 selection
    
    Closes: https://bugs.gentoo.org/show_bug.cgi?id=602440#c1

**Pull request closed without merging**
