### PR TITLE
app-editors/ghostwriter: new ebuild

### PR DESCRIPTION
**Pull request by suhr**

### CODE REVIEW

**Comment by monsieurp** [comment]
I'm not well-versed in Qt-related ebuilds. @a17r could you please review it? or someone from the @gentoo/kde team?

**Comment by idella** [comment]
the metadata.xml file on this is another half completed. While you are welcome to be proxied, you have not stipulated a project, at all. Between proxy-maintainers and kde, both qualify, however to designate the kde or even qt project, you need to have discussed and be given invitation by them.  The proxy-maintainers will take you on otherwise

**Comment by suhr** [comment]
Um... should I do/add anything special?

**Comment by monsieurp** [comment]
@suhr no i'll take care of adding proxy maint to the metadata.xml file. don't worry.

**Comment by monsieurp** [comment]
Merged.

**Pull request closed without merging**
