### PR TITLE
www-client/chromium: add ppc64le patchset from raptor engineering

### PR DESCRIPTION
**Pull request by darkbasic**
Closes: https://bugs.gentoo.org/669748

Hi, I've been maintaining ppc64le ebuilds for Chromium and Electron in https://github.com/PF4Public/gentoo-overlay for quite some time.

Gentoo used to use the Void Linux patchset, which is a simplified version which only supports kernels with a 4K page size.
Unfortunately the Chromium ebuild has been left out of sync with the Void patchset in the past year.

I propose to land the Raptor Engineering ppc64 patchset instead, because I already maintain it for electron and ungoogled-chromium in PF4Public.

Future versions might work out of the box or might not, that's why I left the 107 patchset in the chromium 108 ebuild despite not being tested. Instead I've removed the ~ppc64 keyword and I will create a new PR to re-add it once it's being tested, updating the patchset whenever needed.

Whenever new versions get released you can safely keep the ~ppc64 keyword for minor version updates and remove it for major version ones.

### CODE REVIEW

**Comment by darkbasic** [comment]
I've rebased it to add the missing GCO sign-off, so the label can be removed.

**Comment by gyakovlev** [comment]
does the list of patches follows exact order from `series` file or is it altered in some way?

in that case you just use order from series: you can dynamically read file names instead of hardcoding into ebuild

here's an example how to do it (make it ppc64 conditional ofc)
```
        local p
        for p in $(grep -v "^#" "${WORKDIR}"/debian/patches/series || die); do
                eapply "${WORKDIR}"/debian/patches/${p}
        done
```

**Comment by gyakovlev** [comment]
I'm testing it right now, you can expect me to basic-test it in the future if chromium maintainers agree to merge.
however I got burned maintaining this patchset in the past and will not have enough time to deep dive, ENOTIME.
But I'm glad someone finally doing it.

I can't merge it, but I will get back with test results bit later today.

**Comment by darkbasic** [comment]
> does the list of patches follows exact order from series file or is it altered in some way?

Slightly altered: I carry a custom version of `fix-breakpad-compile.patch` because apparently there is a slight difference between Debian sources and Gentoo sources and the original patch doesn't apply.

**Comment by gyakovlev** [comment]
[chromium-ppc64le-pr28191.build.log.gz](https://github.com/gentoo/gentoo/files/9974723/chromium-ppc64le-pr28191.build.log.gz)
image
image
image

build lgtm, tested `chromium-107.0.5304.87.ebuild`

**Comment by darkbasic** [comment]
> anyway, reading series is a suggestion, not a requirement.

It's probably a good idea to read the series, because patches are often added/deleted and I have to manually check and modify the list otherwise.

**Review by gyakovlev — APPROVED** [review]

**Comment by gyakovlev** [comment]
thanks for all the work, @floppym approved those changes on IRC so it's merged.
I fixed missing quoting around one of patches in follow up commit and changed second commit message instead of squashing.

**Pull request closed without merging**
