### PR TITLE
dev-games/aseprite: Bump to 1.1.7, remove old.

### PR DESCRIPTION
**Pull request by winterheart**
Added bundled allegro library support for resizing feature (Bug #588832).

Gentoo-Bug: https://bugs.gentoo.org/588832

Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by winterheart** [comment]
@gentoo/proxy-maint

**Comment by gktrk** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
Hi. Could you please rebase against master? For some reason I can't merge your PR. Thanks.

**Comment by winterheart** [comment]
I'm totally screwed it. Can I create clean pr for bump?

**Comment by winterheart** [comment]
@monsieurp OK, I figured out what wrong. That wierd ^M in patch for 1.1.4.1
I reworked commit only for adding 1.1.7. Can you please directy delete `aseprite-1.1.4.1.ebuild` and `files/aseprite-1.1.4.1_underlinking.patch` for me?

**Comment by monsieurp** [comment]
Clean up done in b59f9d201c94f30a5ab8584f708f0905ae5f79f9.

**Pull request closed without merging**
