### PR TITLE
dev-perl/Net-Netmask: Version bump for security fix

### PR DESCRIPTION
**Pull request by hlein**
Fixes type confusion with leading zeros in IP octets.
Also, upstream author has changed.

Signed-off-by: Hank Leininger <hlein@korelogic.com>
Bug: https://bugs.gentoo.org/779163
Package-Manager: Portage-3.0.17, Repoman-3.0.2

### CODE REVIEW

**Comment by hlein** [comment]
poke @thesamesam , thanks!

**Comment by thesamesam** [comment]
@hlein Thanks for the ping! I'll ask dilfridge (@akhuettel) to look at it, and if he doesn't get to it, let me know/I'll test myself (just ping me if I don't remember).

**Comment by hlein** [comment]
Sweet, ty both :)

**Comment by thesamesam** [comment]
okay, dilfridge beat us to this (a56f6a5aa63c9154db93a17e57927fb8ac9211bc). I need to swot up on my Perl packaging (I think I'm pretty much there) so things don't languish in future. Thanks though!

(I think he's going through all of dev-perl/* alphabetically.)

**Pull request closed without merging**
