### PR TITLE
*/*: remove a few live ebuilds

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes a few live ebuilds of packages which weren't updated for a couple of years. I think it makes no sense to keep these ebuilds, especially when the non-live ebuild is already at HEAD.

**app-misc/figlet**: only one additional commit from 2020 regarding snapcraft
**app-portage/pgo**: latest commit is the tag for 0.0.3, 4 years ago
**media-fonts/solarize**: latest ebuild is latest commit, latest commit is from 10 years ago
**media-gfx/sxiv**: only 2 additional commits from 2021 and 2023 regarding some link updates, repo was archived 2023
**net-voip/umurmur**: latest ebuild is latest commit, latest commit is from 3 years ago
**sys-power/intel-undervolt**: latest ebuild is latest commit, latest commit 5 years ago
**x11-misc/urxvt-font-size**: one additional commit from 7 years ago regarding some link updates
**x11-wm/wmfs**: latest ebuild is latest commit, latest commit 6 years ago

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by eli-schwartz** [comment]
> This PR removes a few live ebuilds of packages which weren't updated for a couple of years. I think it makes no sense to keep these ebuilds, especially when the non-live ebuild is already at HEAD.

Can you include this info in the individual commit messages?

**Comment by mm1ke** [comment]
> > This PR removes a few live ebuilds of packages which weren't updated for a couple of years. I think it makes no sense to keep these ebuilds, especially when the non-live ebuild is already at HEAD.
> 
> Can you include this info in the individual commit messages?

Sure, done :)

**Comment by vitaly-zdanevich** [comment]
> **media-fonts/solarize**: latest ebuild is latest commit, latest commit is from 10 years ago

Are you sure that you want some updates for a font?

**Comment by vitaly-zdanevich** [comment]
> **net-voip/umurmur**: latest ebuild is latest commit, latest commit is from 3 years ago

image

**Comment by eli-schwartz** [comment]
@vitaly-zdanevich,

> > **media-fonts/solarize**: latest ebuild is latest commit, latest commit is from 10 years ago
> 
> Are you sure that you want some updates for a font?

But there aren't any updates, that's kind of the entire point?

As for umurmur, why are you responding to this by posting a screenshot, of mumble? They are different packages, different software, different git repos. How is the umurmur live ebuild supposed to use *mumble* updates?

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
