### PR TITLE
net-im/telegram-desktop-bin: version bump to 1.1.0

### PR DESCRIPTION
**Pull request by gsora**
Package-Manager: Portage-2.3.3, Repoman-2.3.1

### CODE REVIEW

**Comment by SoapGentoo** [comment]
@gsora please rebase your branch, all those commits from you merging them.

**Comment by gsora** [comment]
My git capabilities aren't working today, and I've completely broke my entire portage fork.

To prevent further troubles, please close this pull request, I'll send a new one as soon as I repair this mess.

**Comment by SoapGentoo** [comment]
@gsora here's a deal, you can give me access to your repo and then I can fix it for you?

**Comment by gsora** [comment]
@SoapGentoo I'm on `gentoo-dev-help` on freenode, mind if we take this conversation there? I would like to know more about how to clear this mess :-)

**Comment by mgorny** [comment]
Closing in favor of #4682. I'm sorry, I hope you didn't put too much work in it.

**Comment by gsora** [comment]
No problem 🙂

**Pull request closed without merging**
