### PR TITLE
sys-boot/grub: add boot loader spec and devicetree patches

### PR DESCRIPTION
**Pull request by sarnold**
* adds base BLS config module for common boot flows
* adds devicetree loading patch with config key for default dtb
* integrates on top of kernel globs patch (list of optional cfg vars)

### CODE REVIEW

**Comment by floppym** [comment]
I would prefer not to add new features to grub-2.06 at this point.

**Comment by sarnold** [comment]
So...  rebase / address comments and migrate patches to 2.12?

**Comment by sarnold** [comment]
i can't really touch this until this nasty flu is over with, but this is the source of the patches:

* https://src.fedoraproject.org/rpms/grub2/tree/rawhide
* blscfg patch is 0021 and devicetree loading patch is 0022

**Comment by floppym** [comment]
Actually, I had assumed the patches had been submitted upstream already. It seems that is not the case.

I do not wish to maintain feature enhancements that have not made it upstream. I would suggest using user patching, or forking the ebuild locallly.

**Comment by sarnold** [comment]
Well, then that kinda kills the whole idea of u-boot-with-grub for distro boot.  Without the devicetree loading patch it turns into a manual and error-prone will-it-boot scenario. <sigh>  I was really hoping we could make arm64 a first-class distroboot customer.

**Comment by floppym** [comment]
I would suggest you encourage the patch author to submit his work upstream.

**Comment by sarnold** [comment]
Judging by the large number of patches that would achieve approx. zero for a single patch.

**Comment by floppym** [comment]
Have you asked him about it?

**Comment by floppym** [comment]
Let's revisit this if/when the patches get sent upstream in some form.

**Pull request closed without merging**
