### PR TITLE
dev-java/japitools: Various bug fixes and changes

### PR DESCRIPTION
**Pull request by wltjr**
@gentoo/java @chewi 
install bins, correct classpath in bins, add missing runtime dep
dev-lang/perl, switched EAPI to 6, updated java version to 1.7

Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by wltjr** [comment]
I just realized I removed the stable version, which I should correct. However the stable version is not stable but broken, so I am not sure having it around really matters. Maybe this should just go straight to stable if dependent packages are stable since they will not work, like java-apicheck which calls japize. Which is presently missing from the current -r2 that is stable. Shows those packages were never really tested when marked stable, beyond dropping the bins and other changes missing from -r1 in -r2.

**Comment by wltjr** [comment]
equery files japitools
 * Searching for japitools ...
 * Contents of dev-java/japitools-0.9.7-r3:
/usr
/usr/bin
/usr/bin/japicompat
/usr/bin/japiextractpkgs
/usr/bin/japilist
/usr/bin/japiohtml
/usr/bin/japiotext
/usr/bin/japize
/usr/bin/japizejdks
/usr/share
/usr/share/ant
/usr/share/ant/tasks
/usr/share/ant/tasks/japitools
/usr/share/japitools
/usr/share/japitools/lib
/usr/share/japitools/lib/japitools.jar
/usr/share/japitools/package.env


equery files japitools
 * Searching for japitools ...
 * Contents of dev-java/japitools-0.9.7-r2:
/usr
/usr/share
/usr/share/ant
/usr/share/ant/tasks
/usr/share/ant/tasks/japitools
/usr/share/japitools
/usr/share/japitools/lib
/usr/share/japitools/lib/japitools.jar
/usr/share/japitools/package.env


dev japitools # equery files japitools
 * Searching for japitools ...
 * Contents of dev-java/japitools-0.9.7-r1:
/usr
/usr/bin
/usr/bin/japicompat
/usr/bin/japiextractpkgs
/usr/bin/japilist
/usr/bin/japiohtml
/usr/bin/japiotext
/usr/bin/japize
/usr/bin/japizejdks
/usr/share
/usr/share/japitools
/usr/share/japitools/lib
/usr/share/japitools/lib/japitools.jar
/usr/share/japitools/package.env

**Comment by wltjr** [comment]
Modified to go straight to stable so CI checks pass, only 1 dependent package that is already stable and is broken without this fix. Oddly repoman did not complain, maybe since I did scan vs full. Repoman did complain when I went to commit with stable keywords, go figure...

**Comment by chewi** [comment]
Merged, thank you.

**Pull request closed without merging**
