### PR TITLE
dev-lang/rust: port fix for compile fault with +parallel +miri

### PR DESCRIPTION
**Pull request by Miezhiko**
https://github.com/rust-lang/rust/issues/87623

### CODE REVIEW

**Comment by gyakovlev** [comment]
thanks.
merged but not sure if we should keep that useflag really, it's not very suited for release builds and I often have to patch it.

**Comment by Miezhiko** [comment]
@gyakovlev I wish rust team care about those flags on release because those are experimental features users may want to try, and some of those (for example FFI) are useful and even important, forcing users to use unstable version to use experimental features is strange.

**Comment by gyakovlev** [comment]
@Miezhiko I think they have a valid reason for it.
if experimental/unstable features were easy to toggle, other developers/users would rely on them. but features are unstable and do not have stability guarantee, so users and other developers would run into a lot of compatibility problems. frustrating experience for whole ecosystem.

gentoo is kinda unique here, because we can toggle nightly enablement for releases and use -Z flags =)

I meant removing `miri` flag, not nightly btw.
`miri` breaks too often.
or may be I'll just mask it, so users can still try it out.

**Comment by Miezhiko** [comment]
@gyakovlev I think for gentoo it will be just easier to support those flags on release instead of providing -beta and -nightly versions in addition to stable.

**Comment by gyakovlev** [comment]
indeed it is. that's why we don't have beta slots anymore ( we used to ).

I just don't see too much value supporting miri specifically. it's very niche and brittle. I'm not actively testing/using it myself. but if you notice breakage like this one I'll happily merge fixes.

`nightly` is very useful. not doubt.

**Comment by CaptainBloodz** [comment]
miri failed to build:
emerge --info rust
Portage 3.0.20 (python 3.9.6-final-0, default/linux/amd64/17.1, gcc-11.2.0, glibc-2.33-r1, 5.13.9-gentoo-r8168 x86_64)
=================================================================
                         System Settings
=================================================================
System uname: Linux-5.13.9-gentoo-r8168-x86_64-Intel-R-_Core-TM-_i3-6100_CPU_@_3.70GHz-with-glibc2.33
KiB Mem:     3941572 total,   1654044 free
KiB Swap:   18802684 total,  18039324 free
...
ACCEPT_KEYWORDS="amd64"
ACCEPT_LICENSE="* -@EULA"
CBUILD="x86_64-pc-linux-gnu"
CFLAGS="-march=native -mtune=native   -O2             -pipe      -Wa,-mbranches-within-32B-boundaries "
CHOST="x86_64-pc-linux-gnu"
CONFIG_PROTECT="/etc /usr/share/config /usr/share/gnupg/qualified.txt"
CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.4/ext-active/ /etc/php/cgi-php7.4/ext-active/ /etc/php/cli-php7.4/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/splash /etc/terminfo /etc/texmf/language.dat.d /etc/texmf/language.def.d /etc/texmf/updmap.d /etc/texmf/web2c"
CXXFLAGS="-march=native -mtune=native   -O2             -pipe      -Wa,-mbranches-within-32B-boundaries     "
DISTDIR="/var/cache/distfiles"
EMERGE_DEFAULT_OPTS="--alert y          --alphabetical          --ask-enter-invalid          --autounmask y           --autounmask-only n           --autounmask-unrestricted-atoms y     --autounmask-write y          --misspell-suggestions n       --noconfmem          --nospinner            --tree       --with-bdeps y"
ENV_UNSET="CARGO_HOME DBUS_SESSION_BUS_ADDRESS DISPLAY GOBIN GOPATH PERL5LIB PERL5OPT PERLPREFIX PERL_CORE PERL_MB_OPT PERL_MM_OPT XAUTHORITY XDG_CACHE_HOME XDG_CONFIG_HOME XDG_DATA_HOME XDG_RUNTIME_DIR"
FCFLAGS="-march=native -mtune=native   -O2             -pipe      -Wa,-mbranches-within-32B-boundaries "
FEATURES="assume-digests binpkg-docompress binpkg-dostrip binpkg-logs compress-build-logs config-protect-if-modified distlocks ebuild-locks fixlafiles ipc-sandbox merge-sync multilib-strict network-sandbox news parallel-fetch pid-sandbox preserve-libs protect-owned qa-unresolved-soname-deps sandbox sfperms split-elog strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync"
FFLAGS="-march=native -mtune=native   -O2             -pipe      -Wa,-mbranches-within-32B-boundaries "
GENTOO_MIRRORS="http://ftp.free.fr/mirrors/ftp.gentoo.org/ https://mirrors.evowise.com/gentoo/ http://mirror.dkm.cz/gentoo/ http://mirror.eu.oneandone.net/linux/distributions/gentoo/gentoo/ http://mirror.netcologne.de/gentoo/ http://mirror.leaseweb.com/gentoo/ http://mirror.bytemark.co.uk/gentoo/ http://gentoo.mirror.web4u.cz/ http://linux.rz.ruhr-uni-bochum.de/download/gentoo-mirror/"
LANG="fr_FR.utf8"
LDFLAGS="  -Wl,-O1       -Wl,-fuse-ld=bfd       -march=native -mtune=native   -O2             -pipe      -Wa,-mbranches-within-32B-boundaries  "
LINGUAS="fr"
MAKEOPTS="-j3 -l3"
PKGDIR="/var/cache/binpkgs"
PORTAGE_COMPRESS="lzma"
PORTAGE_COMPRESS_FLAGS="-9"
PORTAGE_CONFIGROOT="/"
PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
PORTAGE_TMPDIR="/var/tmp"
RUSTFLAGS="-C target-cpu=skylake -C llvm-args=-x86-branches-within-32B-boundaries -C opt-level=3"
USE="amd64 asm libglvnd minimal split-usr verify-sig" ABI_X86="64" ALSA_CARDS="hda-intel" CPU_FLAGS_X86="aes avx avx2 f16c fma3 mmx mmxext pclmul popcnt rdrand sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GRUB_PLATFORMS="pc" INPUT_DEVICES="libinput" KERNEL="linux" L10N="fr" PHP_TARGETS="php7-4" PYTHON_SINGLE_TARGET="python3_9" PYTHON_TARGETS="python3_9" QEMU_USER_TARGETS="aarch64" RUBY_TARGETS="ruby26" USERLAND="GNU" VIDEO_CARDS="intel i965 iris"
Unset:  CC, CPPFLAGS, CTARGET, CXX, INSTALL_MASK, LC_ALL, PORTAGE_BINHOST, PORTAGE_BUNZIP2_COMMAND, PORTAGE_RSYNC_EXTRA_OPTS

=================================================================
                        Package Settings
=================================================================

dev-lang/rust-1.54.0::gentoo was built with the following:
USE="clippy -debug -doc -miri nightly parallel-compiler -rls rustfmt system-bootstrap -system-llvm -test verify-sig -wasm" ABI_X86="-32 (64) (-x32)" CPU_FLAGS_X86="sse2" LLVM_TARGETS="-AArch64 -AMDGPU -ARM -AVR -BPF -Hexagon -Lanai -MSP430 -Mips -NVPTX -PowerPC -RISCV -Sparc -SystemZ -WebAssembly (X86) -XCore"
FEATURES="strict news pid-sandbox split-elog userfetch sfperms protect-owned unmerge-orphans assume-digests usersync multilib-strict ebuild-locks binpkg-logs qa-unresolved-soname-deps userpriv unknown-features-warn usersandbox distlocks fixlafiles compress-build-logs binpkg-docompress preserve-libs sandbox unmerge-logs parallel-fetch config-protect-if-modified ipc-sandbox merge-sync network-sandbox binpkg-dostrip"
Seems properly patched:
 * Applying 1.54.0-parallel-miri.patch ...
patching file src/tools/miri/src/bin/miri.rs
Hunk #2 succeeded at 12 with fuzz 2 (offset -1 lines).
Hunk #3 succeeded at 42 (offset -1 lines).
 [ ok ]
>>> Source prepared.
[dev-lang:rust-1.54.0:20210809-202925.log.gz](https://github.com/gentoo/gentoo/files/6957893/dev-lang.rust-1.54.0.20210809-202925.log.gz)

**Comment by Miezhiko** [comment]
For me miri builds fine but I bootstrap rust from same version as I build, they did some changes that could be related with it but I'm not 100% sure.

@gyakovlev e.g. I don't understand why you are using previous version for stage 0 when you actually can use the same version: https://github.com/Miezhiko/mawa/blob/mawa/dev-lang/rust/rust-1.54.0.ebuild#L25

**Comment by gyakovlev** [comment]
build failure above not related to this patch, different codepath. it also bootstraps from same version and fails in stage2 build( so it's using already built stage1 to rebuild itself). I suspect crazy ricer flags so I'm not touching it.

as for why using older bootstrap - because it's recommended by upstream, it's what they use for releases,  and on multiple occasions same version bootstrap actually failed without extra patches. I do patch it, but prefer safe way by default.
check: https://github.com/rust-lang/rust/blob/1.54.0/src/stage0.txt

**Comment by CaptainBloodz** [comment]
Worked bootstraping from previous version with 'crazy ricer' settings removed.
My apologizes for the noise.
Thks

**Pull request closed without merging**
