### PR TITLE
rocm: update to 5.4.3

### PR DESCRIPTION
**Pull request by darkbasic**
I've bumped anything that is required by `dev-libs/rocm-opencl-runtime` to see if I could get it working on ppc64le: https://bugs.gentoo.org/895286

The only changes I had to make were reverting a commit in rocm-device-libs because it requires LLVM 16 (https://bugs.gentoo.org/895286#c9) and dropping `rocm-comgr-5.1.3-llvm-15-remove-zlib-gnu` from `rocm-comgr` because the patch has been upstreamed.

I can't test OpenCL (it fails at runtime on ppc64) nor HIP (not supported on RX 570) so I'll leave this open as draft in case someone else wants to continue it.

### CODE REVIEW

**Comment by littlewu2508** [comment]
@darkbasic thanks for the update.

Did you run tests from the rocm-device-libs and rocm-comgr package? They does not require any GPU, and should be in good shape on many architectures, since they are basically extensions to clang.

Also, I would recommend one commit per one new package, and add your sign-off for each commit. You can use `pkgdev commit` provided by `dev-util/pkgdev` to directly start from a commit template.

**Comment by littlewu2508** [comment]
> I can't test OpenCL (it fails at runtime on ppc64) nor HIP (not supported on RX 570) so I'll leave this open as draft in case someone else wants to continue it.

So it's still failing for 5.4.3?

HIP should work on RX570 after `export ROC_ENABLE_PRE_VEGA=1`. But There can still be runtime issues

**Comment by darkbasic** [comment]
> Have you run tests from the rocm-device-libs and rocm-comgr package? 

Yes and they all pass.

What I didn't run where `dev-libs/rocm-opencl-runtime` tests (I read they were [supposed to pass](https://github.com/gentoo/gentoo/commit/09aeb68cfc4484487031cb392e926ba03b0095f1) on 5.4.3 so I skipped them), but apparently I cannot even compile it with the `+test` use flag:

```
[122/224] /usr/bin/powerpc64le-unknown-linux-gnu-g++ -DCL_TARGET_OPENCL_VERSION=220 -DEMU_ENV=1 -DUSE_OPENGL=1 -Doclperf_EXPORTS -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/khronos/headers/opencl2.2 -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/common -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/amdocl  -O2 -pipe -mcpu=power9 -mtune=power9 -ggdb3 -Wall -fPIC -std=c++14 -MD -MT tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o -MF tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o.d -o tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o -c /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.cpp
FAILED: tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o 
/usr/bin/powerpc64le-unknown-linux-gnu-g++ -DCL_TARGET_OPENCL_VERSION=220 -DEMU_ENV=1 -DUSE_OPENGL=1 -Doclperf_EXPORTS -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/khronos/headers/opencl2.2 -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/common -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/include -I/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/amdocl  -O2 -pipe -mcpu=power9 -mtune=power9 -ggdb3 -Wall -fPIC -std=c++14 -MD -MT tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o -MF tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o.d -o tests/ocltst/module/perf/CMakeFiles/oclperf.dir/OCLPerfKernelThroughput.cpp.o -c /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.cpp
In file included from /var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.cpp:21:
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:16: error: typedef ‘CPUKernel’ is initialized (use ‘decltype’ instead)
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                ^~~~~~~~~
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:27: error: ‘__m128’ was not declared in this scope; did you mean ‘__ibm128’?
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                           ^~~~~~
      |                           __ibm128
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:35: error: expected primary-expression before ‘,’ token
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                                   ^
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:37: error: ‘__m128’ was not declared in this scope; did you mean ‘__ibm128’?
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                                     ^~~~~~
      |                                     __ibm128
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:45: error: expected primary-expression before ‘,’ token
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                                             ^
/var/tmp/portage/dev-libs/rocm-opencl-runtime-5.4.3/work/ROCm-OpenCL-Runtime-rocm-5.4.3/tests/ocltst/module/perf/OCLPerfKernelThroughput.h:48:47: error: expected primary-expression before ‘unsigned’
   48 | typedef void (*CPUKernel)(__m128 *, __m128 *, unsigned int);
      |                                               ^~~~~~~~
```

This must be ppc64 specific because @thesamesam managed to run the tests.

> Also, I would recommend one commit per one new package, and add your sign-off for each commit.

Sure, I'll rebase it.

> So it's still failing for 5.4.3?

On ppc64le it does: https://github.com/RadeonOpenCompute/ROCm-OpenCL-Runtime/issues/158
Not sure if it fails on amd64 as well, tests are passing now so it's definitely worth a shot.

> HIP should work on RX570 after export ROC_ENABLE_PRE_VEGA=1. But There can still be runtime issues

Last time I've tried it didn't work on Arch Linux amd64, but lots of time had passed so it's worth another try.

**Comment by darkbasic** [comment]
@littlewu2508 it's split into commits and signed now.

**Comment by littlewu2508** [comment]
LGTM after some testing

**Pull request closed without merging**
