### PR TITLE
net-im/telegram-desktop: Bump to 4.6.2

### PR DESCRIPTION
**Pull request by mid-kid**
Supersedes https://github.com/gentoo/gentoo/pull/29418

@gyakovlev

### CODE REVIEW

**Comment by joecool1029** [comment]
They haven't pushed the release yet but 4.6.2 added the cmath patch, should be released today so will be able to drop that once it's up.

**Comment by mid-kid** [comment]
Oh alright, in that case we should wait.

**Comment by joecool1029** [comment]
4.6.2 out but happened again. https://github.com/gentoo/gentoo/commit/8c7deef693ab93595c9cd11c2259d55bd3de95af

I got the patch merged just a bit ago if you just want to wait for another minor release.

**Comment by mid-kid** [comment]
Thanks a lot! I'm always confused when it comes to how many minor patches the telegram guys are going to release. I'll just bump it here, include the patch and call it a day.

**Comment by mid-kid** [comment]
finished building and testing
@gyakovlev

**Comment by gyakovlev** [comment]
question.
does it really `exactly-one-of` enchant or hunspell?

`^^ ( enchant hunspell )` requires at most one enabled, and at least one too.
yet previous logic required exactly one if USE=spell was enabled.
it certainly was possible to build without USE=spell (thus without enchant or hunspell)

this should be probably changet to `??` - at-most-one-of, if you are dropping outer spell cond.

https://wiki.gentoo.org/wiki/User:Sam/Portage_help/Understanding_REQUIRED_USE

**Comment by gyakovlev** [comment]
ah I see, you made spell not-optional via cmake? in that case `^^` will do.

just for clarity, here's the diff

```diff
--- telegram-desktop-4.5.3.ebuild       2023-01-22 15:25:44.540880002 -0800
+++ telegram-desktop-4.6.2.ebuild       2023-02-10 23:06:05.841537275 -0800
@@ -17,11 +17,9 @@
 LICENSE="BSD GPL-3-with-openssl-exception LGPL-2+"
 SLOT="0"
 KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv"
-IUSE="+dbus enchant +fonts +hunspell +jemalloc screencast +spell qt6 qt6-imageformats wayland +X"
+IUSE="+dbus enchant +fonts +hunspell +jemalloc screencast qt6 qt6-imageformats wayland +X"
 REQUIRED_USE="
-       spell? (
-               ^^ ( enchant hunspell )
-       )
+       ^^ ( enchant hunspell )
        qt6-imageformats? ( qt6 )
 "
 
@@ -89,6 +87,7 @@
 PATCHES=(
        "${FILESDIR}/tdesktop-4.2.4-jemalloc-only-telegram.patch"
        "${FILESDIR}/tdesktop-4.4.1-fix-dupe-main-decl.patch"
+       "${FILESDIR}/tdesktop-4.6.2-fix-gcc12-optional.patch"
 )
 
 # Current desktop-file-utils-0.26 does not understand Version=1.5
@@ -136,7 +135,6 @@
                -DDESKTOP_APP_DISABLE_X11_INTEGRATION=$(usex !X)
                -DDESKTOP_APP_DISABLE_WAYLAND_INTEGRATION=$(usex !wayland)
                -DDESKTOP_APP_DISABLE_JEMALLOC=$(usex !jemalloc)
-               -DDESKTOP_APP_DISABLE_SPELLCHECK=$(usex !spell)  # enables hunspell (recommended)
                -DDESKTOP_APP_USE_ENCHANT=$(usex enchant)  # enables enchant and disables hunspell
                -DDESKTOP_APP_USE_PACKAGED_FONTS=$(usex !fonts)  # use system fonts instead of bundled ones
        )

```

**Comment by mid-kid** [comment]
Yeah, see the commit description and discussion at https://github.com/telegramdesktop/tdesktop/commit/f5be551ff8bb16f92638d4ddb5097a4e64507851#r99549281

Spelling isn't optional anymore (the option exists but leads to a broken build if used), and enabling enchant still disables hunspell. I could reduce it to only a use flag for enchant, implicitly disabling hunspell if enabled, if that's more appropriate.

**Comment by mid-kid** [comment]
Alright, there's some other changes that I keep forgetting to make so I should really keep a list for this...

**Pull request closed without merging**
