### PR TITLE
profiles/package.mask: Keep dev-java/jrobin

### PR DESCRIPTION
**Pull request by vaukai**
@jsmolic 
This package is EAPI 8

Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by jsmolic** [comment]
Can you drop the EAPI 5 ebuild while at it?

**Comment by ionenwks** [comment]
> Can you drop the EAPI 5 ebuild while at it?

It's still waiting for stabilization, but the EAPI=8 -r2 is from Feb 18 so it'd be about time to.

**Comment by vaukai** [comment]
> > Can you drop the EAPI 5 ebuild while at it?
> 
> It's still waiting for stabilization, but the EAPI=8 -r2 is from Feb 18 so it'd be about time to.

author | Volkmar W. Pogatzki <gentoo@pogatzki.net> | 2022-02-18 16:35:25 +0100
committer | Sam James <sam@gentoo.org> | 2022-03-16 22:28:01 +0000

So we could stabilize on April 15, right?

**Comment by ionenwks** [comment]
Yeah, see my edit. I noticed the right date after. Although note it's not always necessary to wait the full 30 days, I often do less when it's just ebuild changes / revbumps unless it's something big.

**Pull request closed without merging**
