### PR TITLE
dev-libs/appstream: add 0.16.1

### PR DESCRIPTION
**Pull request by ran-dall**
Adds the latest version of `appstream`

### CODE REVIEW

**Comment by ConiKost** [comment]
Reopen, sorry, this was not meant to be merged.

**Comment by a17r** [comment]
My thoughts exactly, since this is a 1:1 copy of 0.15.6 but has `+conf.set('HAVE_SYSTEMD', get_option('systemd'))` in build sys.

**Comment by a17r** [comment]
https://bugs.gentoo.org/904521

**Comment by a17r** [comment]
closing then as a blind copy-paste attempt.

**Pull request closed without merging**
