### PR TITLE
dev-python/ipython: Version bump to 5.8.0

### PR DESCRIPTION
**Pull request by marbre**
Copy of the 5.4.1-r1 ebuild with unstable keywords. Tests pass with python{2_7,3_4,3_6} on my machine.

### CODE REVIEW

**Comment by mgorny** [comment]
When you say it's a copy, I have to ask: did you compare the tarballs and verify that no changes are needed?

**Comment by marbre** [comment]
I checked the `setup.py` in the iython repo to check for changed dependencies. The tarballs of course differ since the software changed.

**Comment by marbre** [comment]
Cannot reproduce the issue with python2.7 on my machine:
```
Test group: lib
.................................................S....................S......
----------------------------------------------------------------------
Ran 77 tests in 1.899s

OK (SKIP=2)
```
Does the **stable** `ipython-5.4.1-r1` fails on your system too?

**Comment by mgorny** [comment]
Do you have USE=tk on Python? If not, I'm going to guess this test is being skipped for you.

**Comment by marbre** [comment]
Correct guess ;)

**Comment by mgorny** [comment]
Do you want to finish it or should I do it?

**Comment by marbre** [comment]
I would appreciate if you could take over, as I am a little to busy at the moment.

**Pull request closed without merging**
