### PR TITLE
net-dns/bind-tools: add missing die statements for 9.12.2_p2-r1

### PR DESCRIPTION
**Pull request by juippis**
@candrews & @idl0r 

Built it and ran (some of the) binaries, seems to work but please test it. I ignored "styling issues", like sorting *DEPEND lists. 

Switched away from CDEPEND since it's not allowed to be used. I'll take a look at bind when I have more time.

### CODE REVIEW

**Comment by juippis** [comment]
@candrews, ping?

**Comment by candrews** [comment]
I like it - but I'm not the maintainer.

@idl0r what do you think? Does this require a revision bump (I'm thinking it would)?

**Comment by juippis** [comment]
(I don't think so, since it doesn't change runtime behaviour, and the enhancements are just for building + cosmetic)

**Comment by juippis** [comment]
@candrews seems like @idl0r is on devaway, btw.

**Comment by juippis** [comment]
I did take a look and for me to be happy with it, I want to test it througly. It had many different conditions so it takes a lot of time, but hey, christmas holidays ;)

**Comment by a17r** [comment]
Please rebase your changes on top of latest bind-tools version in tree.

**Comment by juippis** [comment]
Why bother.

**Pull request closed without merging**
