### PR TITLE
Add app-crypt/veracrypt-1.25.9

### PR DESCRIPTION
**Pull request by ran-dall**
Signed-off-by: Randall T. Vasquez <ran.dall@icloud.com>

### CODE REVIEW

**Review by gktrk — APPROVED** [review]
@thesamesam could you merge this for me? I checked the tag diff, no significant changes.

**Comment by thesamesam** [comment]
Will do @gktrk! Cheers

**Comment by ran-dall** [comment]
@thesamesam It might be an idea to drop the older ebuilds due to them being able to finish making a new encrypted disk (https://github.com/veracrypt/VeraCrypt/issues/896). I know, for sure, `1.25.7` doesn't work properly.

**Comment by thesamesam** [comment]
Remember our commit message format is: "cat/pkg: add 1.25.9" etc. But I think you made this PR before you learned of the wodners of pkgdev, so no need to fix it here, I will.

**Comment by ran-dall** [comment]
> Remember our commit message format is: "cat/pkg: add 1.25.9" etc. But I think you made this PR before you learned of the wodners of pkgdev, so no need to fix it here, I will.

@thesamesam It's true, and I've been using `pkgdev` since. 🙃 Regardless, thank you for fixing it.

**Pull request closed without merging**
