### PR TITLE
dev-haskell/*: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR removes unused patches from dev-haskell/*
Please review.

### CODE REVIEW

**Comment by monsieurp** [comment]
@trofi

**Comment by monsieurp** [comment]
Thanks for the PR btw. We shall squash it on our end into a single commit prior to merging it. @trofi pls sign off on it and I'll take care of the rest.

**Comment by trofi** [comment]
Looks good. Thank you!

I'd say having 1 commit per package is even better to preserve as is.
It will make revert of a single change a trivial operation in case of
odd cases of unobviously used patches.

@mm1ke, what did you use to find the orphan patches? I'd like to apply the same
time to time to ::haskell overlay where patch churn is even higher.

**Comment by mm1ke** [comment]
@trofi i've wrote my own script in order to find wasted patches.
I did some cleanups and added the script to github (https://github.com/mm1ke/gentoo-scripts/tree/master/gentoo). 
However, bare in mind, i wrote this on an afternoon and it's far from perfect. There are still quite a lot of false-positives, and i usually double check every unused patch found. However, patches to improve the script are welcomed :)

**Comment by monsieurp** [comment]
Thanks a lot! Patch merged.

**Pull request closed without merging**
