### PR TITLE
sec-keys/openpgp-keys-yubico: add 20240704, drop 20240628

### PR DESCRIPTION
**Pull request by hamarituc**
version bump

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Review by eli-schwartz — COMMENTED** [review]
Why remove 20240628 but not 20230825?

**Comment by hamarituc** [comment]
> Why remove 20240628 but not 20230825?

You a right. It can be removed as well. I dropped this ebuild as well.

**Comment by ajakk** [comment]
> > Why remove 20240628 but not 20230825?
> 
> You a right. It can be removed as well. I dropped this ebuild as well.

It looks like you didn't but I went ahead and did it in a separate commit on merge. Thanks!

**Comment by hamarituc** [comment]
> > > Why remove 20240628 but not 20230825?
> > 
> > 
> > You a right. It can be removed as well. I dropped this ebuild as well.
> 
> It looks like you didn't but I went ahead and did it in a separate commit on merge. Thanks!

Sorry, I forgot to push my changes :see_no_evil:

**Pull request closed without merging**
