### PR TITLE
dev-python/pep8: restore compatibility with flake8

### PR DESCRIPTION
**Pull request by Coacher**
Hello.

pep8-1.6.0 introduced [a change](https://github.com/PyCQA/pep8/issues/368) that broke flake8. Upstream later [reverted this change](https://github.com/PyCQA/pep8/commit/435d1cbf995a659a82d1d4b42d25e3459556ef21) to restore broken compatibility with flake8, but it happened after pep8-1.6.2 release.

Upstream [does not want to rush to a new release](https://github.com/PyCQA/pep8/issues/427#issuecomment-129502134) so it would be nice to have this compatibility problem solved for Gentoo users in the meantime.

Also revbump flake8 to only exclude known bad versions of pep8 [as it is done upstream](https://gitlab.com/pycqa/flake8/commit/d41701df3be7e3d04ba1fcc1e178fd777c6ff352) to allow the patched version of pep8 to coexist with flake8.

### CODE REVIEW

**Comment by mgorny** [comment]
The summary line of commit messages should shortly describe most important changes. 'Revbump' is not a useful information there.

**Comment by mgorny** [comment]
@gentoo/python

**Comment by Coacher** [comment]
I've updated summaries.

**Comment by floppym** [comment]
LGTM

**Comment by Coacher** [comment]
QA problems 'come from the underlying Gentoo repository state rather than the pull request itself' in this case.

**Comment by floppym** [comment]
Actually, this patchset is insufficient.

flake8's setup.py contians this in install_requires:

```
    install_requires=[
        "pyflakes >= 0.8.1, < 0.9",
        "pep8 >= 1.5.7, != 1.6.0, != 1.6.1, != 1.6.2",
        "mccabe >= 0.2.1, < 0.4",
    ],
```

We would need to change the version of the installed pep8, or remove the `!= 1.6.2` restriction from flake8. Otherwise, flake8 will fail when running tests and at run time.

**Comment by Coacher** [comment]
Thank you for pointing this out.

**Comment by Coacher** [comment]
Updated to remove `, != 1.6.2` from setup.py

**Comment by Coacher** [comment]
Ian merged this PR halfway through. Some changes were not added.
Here's a patch to fix this:
```
--- a/dev-python/flake8/flake8-2.4.1-r1.ebuild
+++ b/dev-python/flake8/flake8-2.4.1-r1.ebuild
@@ -21,7 +21,8 @@ RDEPEND=">=dev-python/pyflakes-0.8.1[${PYTHON_USEDEP}]
        <dev-python/pyflakes-0.9[${PYTHON_USEDEP}]
        >=dev-python/pep8-1.5.7[${PYTHON_USEDEP}]
        !=dev-python/pep8-1.6.1[${PYTHON_USEDEP}]
-       "
+       !=dev-python/pep8-1.6.2[${PYTHON_USEDEP}]
+"
 PDEPEND=">=dev-python/mccabe-0.2.1[${PYTHON_USEDEP}]
        <dev-python/mccabe-0.4[${PYTHON_USEDEP}]"
 DEPEND="${RDEPEND}
@@ -33,6 +34,8 @@ DEPEND="${RDEPEND}
 python_prepare_all() {
        # This tests requires / assumes this version is already installed.
        sed -e 's:test_register_extensions:_&:' -i flake8/tests/test_engine.py || die
+       # Gentoo has flake8 support restored in >=pep8-1.6.2-r1.
+       sed -e 's:, != 1.6.2::' -i setup.py || die
        distutils-r1_python_prepare_all
 }
```
I've also attached it here https://bugs.gentoo.org/show_bug.cgi?id=561394
Not sure if I need to update PR again.

**Comment by Coacher** [comment]
CC @idella

**Comment by Coacher** [comment]
Missing changes were added in 6a35da2. Closing.

**Pull request closed without merging**
