### PR TITLE
media-tv/mythtv: fixes branch

### PR DESCRIPTION
**Pull request by thebitpit**
Closes: https://bugs.gentoo.org/772248
Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Wilson Michaels <thebitpit@austincustomerrands.com>

### CODE REVIEW

**Comment by thebitpit** [comment]
This is a liveVCS ebuild.  A snapshot would be OK to fix this bug, but I could not figure out how to make a snapshot file and where to store it.

**Comment by juippis** [comment]
Since the project is hosted in Github, Github itself can provide a snapshotted archive to use. 
Please check https://gitweb.gentoo.org/repo/gentoo.git/tree/dev-libs/qtcompress/qtcompress-0_p20180513.ebuild for an example how to do it.

You'll want to version your ebuild as `-31.0_p20210225` where the date is the **date of your snapshot commit**.

**Comment by thebitpit** [comment]
> Since the project is hosted in Github, Github itself can provide a snapshotted archive to use.
I am not authorized to commit to official MythTV repository <MythTV/mythtv>. Do I commit a tag on my github fork <thebitbpit/mythtv> and use that?

**Comment by thebitpit** [comment]
Remove LiveVCS ebuild and add snapshot ebuild. The snapshot ebuild also works for new upstream versions by using a regular version ebuild file name. (i.e. no _p<date> in file name)

**Review by juippis — APPROVED** [review]
Yes, like this, thanks! I had to regenerate the manifest but it works really well after.

**Comment by juippis** [comment]
```
media-tv/mythtv
  PythonCompatUpdate: version 31.0-r5: PYTHON_COMPAT update available: python3_9
  PythonCompatUpdate: version 31.0_p20210225: PYTHON_COMPAT update available: python3_9
```

**Pull request closed without merging**
