### PR TITLE
Add missing CPE tags for Gentoo packages

### PR DESCRIPTION
**Pull request by bsdnet**
Those CPE tags are  from official CPE tag database official-cpe-dictionary_v2.3.xml downloaded from 
https://nvd.nist.gov/products/cpe.

### CODE REVIEW

**Comment by thesamesam** [comment]
You may want to squash some of these commits. Thanks for adding in these important tags.

**Comment by bsdnet** [comment]
> You may want to squash all of these commits. Thanks for adding in these important tags.
> 
> You can run pkgcheck locally to get the same errors as the CI gives you, to save time on iterations.

Thanks, Good to know that that pkgcheck will help.
I have squashed all the changes into one.

**Comment by bsdnet** [comment]
Is anything needed from me  to merge this PR?

**Comment by Whissi** [comment]
No, we need one commit per package. Sorry for that.

**Comment by bsdnet** [comment]
/thesamesam 

Please take a look to see whether it is okay to merge in. I have done one commit per package.

**Comment by Whissi** [comment]
Thank you very much.

**Pull request closed without merging**
