### PR TITLE
net-im/telegram-desktop-bin: add 4.6.0

### PR DESCRIPTION
**Pull request by joecool1029**
https://github.com/telegramdesktop/tdesktop/releases/tag/v4.6.0

Signed-off-by: Joe Kappus <joe@wt.gd>

### CODE REVIEW

**Comment by henning-schild** [comment]
thanks for doing that

usually tdesktop needs 1-5 fixup releases so it is wise to wait ;) but we can move with them, most of the time they release those fixes faster than gentoo PRs get merged

**Comment by joecool1029** [comment]
I've noticed they've been doing more pre-release releases the last few cycles. It seems to be reducing the issues seen in their releases. In any case, can't we stablereq once we're sure a new version isn't causing issues?

**Comment by henning-schild** [comment]
Not sure about that, they always did pre-releases in the last years and i think still most of the real releases have been followed up quickly with fixes.
The application itself does have an auto-self-update, which is disabled in gentoo for obvious reasons. Not sure if that self-update would pick up pre-releases ... at the end it seems like issues in releases are found often. So the pre-releases do not seem to be used by enough early-adopters.

In gentoo this thing was never "stable". We merge what we get as "~" ... and very often they fix up faster than we merge.

Just let us see how this round goes. Maybe we will be fast enough ... and have to take a potential fix later. While i watch upstream ... i usually give them a few days before i even open a PR.

**Comment by joecool1029** [comment]
Eh, on one hand we have to worry about obvious crashes and regressions added in new bin versions, on the other hand if you leave users on old versions they'll start to see messages 'this content is not supported by your telegram version' because the developers like to move fast and add crap.

But this is a bin package, it's not the gigantic PITA that bringing up the source package sometimes is, I can absolutely understand holding off merging https://github.com/gentoo/gentoo/pull/29418 so we can have one less patch in the tree.

**Comment by henning-schild** [comment]
i do not want to hold up, the order of events is not in my hands ... i just know that in the past the events on tdesktop happened faster than gentoo could follow ... let us see what happens this time

**Pull request closed without merging**
