### PR TITLE
net-misc/eventd: verbump to 0.22.0

### PR DESCRIPTION
**Pull request by Coacher**
Upstream now uses meson build system exclusively, so port ebuild to it.
There's no eclass available now, so implement some generic bits as well.

Package-Manager: Portage-2.3.5, Repoman-2.3.2

### CODE REVIEW

**Comment by mgorny** [comment]
Is there much of a hurry on this? The eclass for meson is work-in-progress, so maybe we could delay it a few days.

**Comment by Coacher** [comment]
No. See also https://bugs.gentoo.org/show_bug.cgi?id=616982#c1
I personally would prefer not to reimplement meson and ninja-utils eclasses.
meson.eclass is not even on g-dev yet though.

**Comment by Coacher** [comment]
> meson.eclass is in place, please update ;-).

After bug 619718 is fixed. I think that nice eclass should take care of einstalldocs for me. meson.eclass isn't nice yet :)

**Comment by Coacher** [comment]
RESOLVED OBSOLETE. See PR reference above.

**Pull request closed without merging**
