### PR TITLE
sci-libs/vtk: added support for qt5

### PR DESCRIPTION
**Pull request by timeraider4u**
Package-Manager: portage-2.3.0

### CODE REVIEW

**Comment by a17r** [comment]
If Qt5 support works fine, please remove the Qt4 option entirely to not create another REQUIRED_USE conflict for users.

**Comment by timeraider4u** [comment]
@a17r: Thank you for your quick feedback! I have updated my pull request with the suggestions made by you. Here is the diff between the latest two ebuild revisions: 
`diff -Naur sci-libs/vtk/vtk-6.1.0-r3.ebuild sci-libs/vtk/vtk-6.1.0-r4.ebuild 
--- sci-libs/vtk/vtk-6.1.0-r3.ebuild    2016-10-25 23:11:06.627428044 +0200
+++ sci-libs/vtk/vtk-6.1.0-r4.ebuild    2016-10-25 23:37:58.171360645 +0200
@@ -30,12 +30,12 @@
 SLOT="0"
 IUSE="
        all-modules aqua boost cg doc examples imaging ffmpeg gdal java json kaapi mpi
-       mysql odbc offscreen postgres python qt4 rendering smp tbb test theora tk tcl
+       mysql odbc offscreen postgres python qt5 rendering smp tbb test theora tk tcl
        video_cards_nvidia views web xdmf2 R +X"
 
 REQUIRED_USE="
        all-modules? ( python xdmf2 )
-       java? ( qt4 )
+       java? ( qt5 )
        python? ( ${PYTHON_REQUIRED_USE} )
        tcl? ( rendering )
        smp? ( ^^ ( kaapi tbb ) )
@@ -67,8 +67,8 @@
        boost? ( >=dev-libs/boost-1.40.0[mpi?] )
        cg? ( media-gfx/nvidia-cg-toolkit )
        examples? (
-               dev-qt/qtcore:4
-               dev-qt/qtgui:4
+               dev-qt/qtcore:5
+               dev-qt/qtgui:5
                sci-libs/vtkdata
        )
        ffmpeg? ( virtual/ffmpeg )
@@ -87,14 +87,14 @@
                dev-python/sip[${PYTHON_USEDEP}]
                )
        )
-       qt4? (
-               dev-qt/designer:4
-               dev-qt/qtcore:4
-               dev-qt/qtgui:4
-               dev-qt/qtopengl:4
-               dev-qt/qtsql:4
-               dev-qt/qtwebkit:4
-               python? ( dev-python/PyQt4[${PYTHON_USEDEP}] )
+       qt5? (
+               dev-qt/designer:5
+               dev-qt/qtcore:5
+               dev-qt/qtgui:5
+               dev-qt/qtopengl:5
+               dev-qt/qtsql:5
+               dev-qt/qtwebkit:5
+               python? ( dev-python/PyQt5[${PYTHON_USEDEP}] )
                )
        tbb? ( dev-cpp/tbb )
        tcl? ( dev-lang/tcl:0= )
@@ -219,7 +219,6 @@
                $(cmake-utils_use doc DOCUMENTATION_HTML_HELP)
                $(cmake-utils_use imaging VTK_Group_Imaging)
                $(cmake-utils_use mpi VTK_Group_MPI)
-               $(cmake-utils_use qt4 VTK_Group_Qt)
                $(cmake-utils_use rendering VTK_Group_Rendering)
                $(cmake-utils_use tk VTK_Group_Tk)
                $(cmake-utils_use views VTK_Group_Views)
@@ -296,20 +295,21 @@
                )
        fi

-       if use qt4; then
+       if use qt5; then
                mycmakeargs+=(
                        -DVTK_USE_QVTK=ON
                        -DVTK_USE_QVTK_OPENGL=ON
                        -DVTK_USE_QVTK_QTOPENGL=ON
                        -DQT_WRAP_CPP=ON
                        -DQT_WRAP_UI=ON
-                       -DVTK_INSTALL_QT_DIR=/$(get_libdir)/qt4/plugins/designer
-                       -DDESIRED_QT_VERSION=4
-                       -DVTK_QT_VERSION=4
-                       -DQT_MOC_EXECUTABLE="$(qt4_get_bindir)/moc"
-                       -DQT_UIC_EXECUTABLE="$(qt4_get_bindir)/uic"
-                       -DQT_INCLUDE_DIR="${EPREFIX}/usr/include/qt4"
-                       -DQT_QMAKE_EXECUTABLE="$(qt4_get_bindir)/qmake"
+                       -DVTK_INSTALL_QT_DIR=/$(get_libdir)/qt5/plugins/designer
+                       -DDESIRED_QT_VERSION=5
+                       -DVTK_QT_VERSION=5
+                       -DQT_MOC_EXECUTABLE="$(qt5_get_bindir)/moc"
+                       -DQT_UIC_EXECUTABLE="$(qt5_get_bindir)/uic"
+                       -DQT_INCLUDE_DIR="${EPREFIX}/usr/include/qt5"
+                       -DQT_QMAKE_EXECUTABLE="$(qt5_get_bindir)/qmake"
+                       -DVTK_Group_Qt:BOOL=ON
                )
        fi
`

**Comment by SoapGentoo** [comment]
personally I'd love to just ditch the 6 series completely and start working on getting 7.x into the tree. I'll have a look though.

**Comment by a17r** [comment]
@timeraider4u thanks, as you can see the diff is also nicely shown by Github (see 'files changed' tab)

**Comment by timeraider4u** [comment]
@a17r: Ahh, thanks, now I understood what you meant in your first comment ;-). Good to know that Github re-uses git's re-use algorithm.

**Comment by timeraider4u** [comment]
@SoapGentoo : If you are planning to update vtk to version 7+, you might also want to consider the ebuild at https://github.com/timeraider4u/sci/blob/master/sci-libs/vtk/vtk-6.1.0-r3.ebuild where I already tried to migrate some parts of the vtk-ebuild to EAPI version 6.

**Pull request closed without merging**
