### PR TITLE
app-text/po4a-r3: Fix LINGUAS support

### PR DESCRIPTION
**Pull request by jvesely**
fix array append
perl_rm_files takes relative paths not absolute
remove translated manpages

### CODE REVIEW

**Comment by idella** [comment]
the maintainer of this package is listed here
I have notified him by another another forum

**Comment by idella** [comment]
@Fat-Zer

**Comment by Fat-Zer** [comment]
Looks good.

But this needs to be a revbump, because you're changing the installed files.

**Comment by idella** [comment]
Correct

**Comment by jvesely** [comment]
branch updated

**Comment by Fat-Zer** [comment]
Everything is great now, @idella, you may go ahead and merge...
Note, if you will try to build with FEATURES=test you should use emerge to pull in dependencies

**Comment by idella** [comment]
Edited commit msg slightly to std format.

**Pull request closed without merging**
