### PR TITLE
Rust 1.74.1

### PR DESCRIPTION
**Pull request by xen0n**
I didn't have the time to perform the full test procedure this time (see my devaway), so someone else would have to test.

Also, @vimproved: I didn't know how you created the libc bump patch for musl, and the 1.72.0 patch no longer cleanly applies, so I've temporarily dropped it. Feel free to put up a refresh PR for that to restore musl builds!

### CODE REVIEW

**Comment by orbea** [comment]
> Also, @vimproved: I didn't know how you created the libc bump patch for musl, and the 1.72.0 patch no longer cleanly applies, so I've temporarily dropped it. Feel free to put up a refresh PR for that to restore musl builds!

It would be a great inconvenience to push a ebuild with this broken again, can you please work this out before merging the new version so we don't have to wait for several more months?

**Comment by xen0n** [comment]
> > Also, @vimproved: I didn't know how you created the libc bump patch for musl, and the 1.72.0 patch no longer cleanly applies, so I've temporarily dropped it. Feel free to put up a refresh PR for that to restore musl builds!
> 
> It would be a great inconvenience to push a ebuild with this broken again, can you please work this out before merging the new version so we don't have to wait for several more months?

I would try my best to fix it before pushing though.

**Comment by ionenwks** [comment]
Haven't tried but patch is probably still usable by just dropping chunks that don't apply, e.g. addr2line uses libc-0.2.147 now so changing that one is no longer needed, but then e.g. crossbeam-channel is still on 0.2.141.

Worst case could always mask the bump on musl profiles until it gets looked at.

**Comment by 12101111** [comment]
The libc patch is not needed. I can upgrade from 1.72.0 to 1.73.0 and from 1.73.0 to 1.74.0 **without** this patch on aarch64-unknown-linux-musl system and x86_64-pc-linux-musl system (musl/llvm profile, with USE=system-bootstrap)

**Comment by vimproved** [comment]
> The libc patch is not needed. I can upgrade from 1.72.0 to 1.73.0 and from 1.73.0 to 1.74.0 **without** this patch on aarch64-unknown-linux-musl system and x86_64-pc-linux-musl system (musl/llvm profile, with USE=system-bootstrap)

Yes, I'm aware it's not needed to upgrade, but since the old libc deps end up getting compiled into static libraries, any issues caused by them wouldn't end up manifesting until something linked against them. Either way, it's probably fine to just merge this and deal with any issues later.

**Comment by thesamesam** [comment]
I wasn't actually planning on pushing it when I did, as I'd just had the patches in my tree to export, but I don't think it's worth masking/reverting as everything built fine for me anyway and I know some people had tested 1.74.0 as well.

Thanks!

**Pull request closed without merging**
