### PR TITLE
app-office/skrooge: Version bump 2.2.0

### PR DESCRIPTION
**Pull request by a17r**
See also: https://skrooge.org/skrooge_2.2.0

YES, skrooge cmake uses uppercase FIND_PACKAGE...

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/kde

**Comment by kensington** [comment]
I made some minor skrooge changes in the overlay, if you agree I'll squash them with this before merging.

**Comment by a17r** [comment]
Sure, do it!

**Comment by kensington** [comment]
Thanks, applied.

**Pull request closed without merging**
