### PR TITLE
dev-util/cccc: remove unused patches

### PR DESCRIPTION
**Pull request by mm1ke**
Hi @sarnold 

This PR removes 2 unused patches from dev-util/cccc. Please review.

I also saw that the ebuild uses a patch (when setting the mfc use flag) which actually doesn't exist.
I haven't test build the package, but it can't work right now (at least with the mfc use flag set).
Either we remove the patch from the ebuild or add the patch to the files directory.

BTW, if you want i can also create a bug report for it.

### CODE REVIEW

**Comment by mm1ke** [comment]
ping, just rebased my PR :)

**Comment by mm1ke** [comment]
ping, just rebased my PR :)

**Comment by mgorny** [comment]
Looks good, i'll merge it. Could you create the bug report about the missing patch? I just meant to do that but since you already offered to… ;-)

**Comment by mm1ke** [comment]
@mgorny, done: https://bugs.gentoo.org/show_bug.cgi?id=602368

**Pull request closed without merging**
