### PR TITLE
mail-client/neomutt: Version bump 20231103

### PR DESCRIPTION
**Pull request by nicolasbock**
This change also addresses Sam James' suggestion regarding the two
sanitize compile flags. They are now activated via CFLAGS and not USE
flags.

Bug: https://bugs.gentoo.org/905838
Signed-off-by: Nicolas Bock <nicolasbock@gentoo.org>

### CODE REVIEW

**Comment by nicolasbock** [comment]
Thanks @thesamesam for your comment in https://bugs.gentoo.org/905838. Is this how you mean to use the sanitize options? Thanks!

**Comment by mschiff** [comment]
ok, thanks! 

And how would one build neomutt with --asan now? I guess I must have missed something but I don't see yet how this solution is more useful for the user than a USE flag?

**Comment by nicolasbock** [comment]
You now need to pass the sanitize flags via `CFLAGS`. E.g.
```console
CLFAGS="-fsanitize=address" ebuild neomutt-20231103.ebuild configure
```
I am not sure this approach is more useful but it seems to be more "standard" according to @thesamesam . Please correct me though if I misunderstood @thesamesam .

**Comment by nicolasbock** [comment]
There are a number of packages though that use `USE` flags, most notably maybe
```console
sys-libs/compiler-rt-sanitizers
```

**Comment by thesamesam** [comment]
> There are a number of packages though that use `USE` flags, most notably maybe
> 
> ```
> sys-libs/compiler-rt-sanitizers

This one is _providing_ asan and ubsan for LLVM.

> dev-lang/gnat-gpl

This is for building support within the compiler, like for GCC.

> dev-lang/moarvm

This one is the odd one out.

**Comment by thesamesam** [comment]
> You now need to pass the sanitize flags via `CFLAGS`. E.g.
> 
> ```
> CLFAGS="-fsanitize=address" ebuild neomutt-20231103.ebuild configure
> ```
> 
> I am not sure this approach is more useful but it seems to be more "standard" according to @thesamesam . Please correct me though if I misunderstood @thesamesam .

Yeah, exactly. People should use https://wiki.gentoo.org/wiki/AddressSanitizer#Per-package. We don't add USE flags for every single possible compiler flag, and this also means users have things setup correctly wrt sandbox.

**Review by thesamesam — APPROVED** [review]
Thank you!

**Comment by nicolasbock** [comment]
Ok, perfect, that makes sense @thesamesam

**Comment by nicolasbock** [comment]
Closed with 4de47c94f583d30b2cbb6325dc695c4184d04f2f

**Pull request closed without merging**
