### PR TITLE
games-engines/odamex: Version bump to 0.9.0

### PR DESCRIPTION
**Pull request by vilhelmgray**
Closes: https://bugs.gentoo.org/777651
Signed-off-by: William Breathitt Gray <vilhelm.gray@gmail.com>

### CODE REVIEW

**Comment by vilhelmgray** [comment]
I need some assistance on this ebuild. I've unbundled jsoncpp so that we use the system-provided one now. Unfortunately, I get some C++11 errors when trying to compile with the system-provided `/usr/include/jsoncpp/json.h` header.

**Comment by juippis** [comment]
@SoapGentoo could you take a look?

**Comment by ionenwks** [comment]
> I need some assistance on this ebuild. I've unbundled jsoncpp so that we use the system-provided one now. Unfortunately, I get some C++11 errors when trying to compile with the system-provided `/usr/include/jsoncpp/json.h` header.

As far as I'm aware jsoncpp-1.x.x hard-requires c++11, but package uses -std=gnu++98 and bundles a 7 years old jsoncpp.

I tried to build it against system jsoncpp-0.11.0 (released last year) to test and it built fine, but that's not available in ::gentoo and would partly conflict (just the pkgconfig file) with jsoncpp-1.x.x if wanted to slot it.

**Comment by vilhelmgray** [comment]
Should we use the bundled jsoncpp in this case for now then?

**Comment by juippis** [comment]
I don't really see any other viable option here. You should try to get upstream update their code though ;)

**Comment by vilhelmgray** [comment]
I've updated this PR so we link to the internal jsoncpp. I've also opened https://github.com/odamex/odamex/issues/261 to request upstream to allow linking to the system-provided libraries, as well as https://github.com/odamex/odamex/pull/262 to add support for the CMake "Gentoo" build type.

**Review by juippis — APPROVED** [review]

**Pull request closed without merging**
