### PR TITLE
gnome-base/nautilus: Version bump to 43.2

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
````diff
-		$(meson_use gstreamer) # gstreamer audio-video-properties extension
+		#$(meson_use gstreamer) # gstreamer audio-video-properties extension
````

Is this intentional?

**Comment by flint2** [comment]
> ```diff
> -		$(meson_use gstreamer) # gstreamer audio-video-properties extension
> +		#$(meson_use gstreamer) # gstreamer audio-video-properties extension
> ```
> 
> Is this intentional?

Yes, it´s not compiling with this option, maybe a removed patch (because failed) is needed back?

**Comment by flint2** [comment]
> > ```diff
> > -		$(meson_use gstreamer) # gstreamer audio-video-properties extension
> > +		#$(meson_use gstreamer) # gstreamer audio-video-properties extension
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Is this intentional?
> 
> Yes, it´s not compiling with this option, maybe a removed patch (because failed) is needed back?

Solved in https://github.com/gentoo/gentoo/pull/29008/commits/d5ded9eb08e1c724c1d08cd05b4dacc792a11eb2

**Comment by mattst88** [comment]
Thanks!

To confirm, this test now fails, right?

````
13/16 nautilus                                               FAIL             0.53s   killed by signal 5 SIGTRAP
>>> G_DEBUG=fatal-warnings MALLOC_PERTURB_=109 RUNNING_TESTS=TRUE GSETTINGS_SCHEMA_DIR=/var/tmp/portage/gnome-base/nautilus-43.2/work/nautilus-43.2-build/data /var/tmp/portage/gnome-base/nautilus-43.2/work/nautilus-43.2-build/src/nautilus --check
 ✀  
stderr:
** Message: 22:19:08.922: Connecting to org.freedesktop.Tracker3.Miner.Files
running nautilus_self_check_file_utilities
running nautilus_self_check_file_operations
running nautilus_self_check_directory

** (org.gnome.Nautilus:71): WARNING **: 22:19:09.362: Unable to create connection for session-wide Tracker indexer: Process org.freedesktop.Tracker3.Miner.Files received signal 5
````

I see some changes upstream that look like they're probably to blame—https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/1026

**Pull request closed without merging**
