### PR TITLE
net-misc/asterisk: use freeradius-client instead of radiusclient-ng

### PR DESCRIPTION
**Pull request by puleglot**
net-dialup/radiusclient-ng is no longer maintained upstream. It was
superseded by net-dialup/freeradius-client

Gentoo-Bug: 563410

### CODE REVIEW

**Comment by mgorny** [comment]
How would you feel about getting PGP signatures on your commits? ;-) https://wiki.gentoo.org/wiki/Project:Gentoo-keys/Generating_GLEP_63_based_OpenPGP_keys is the best start point for various docs, I guess.

**Comment by mgorny** [comment]
Direct diff since git doesn't want to notice the copy ;-).

```
--- asterisk-13.5.0-r1.ebuild	2015-10-06 22:30:27.838674259 +0200
+++ asterisk-13.5.0-r2.ebuild	2015-10-18 17:14:31.006118330 +0200
@@ -63,7 +63,7 @@ CDEPEND="dev-db/sqlite:3
 	osplookup? ( net-libs/osptoolkit )
 	portaudio? ( media-libs/portaudio )
 	postgres? ( dev-db/postgresql:* )
-	radius? ( net-dialup/radiusclient-ng )
+	radius? ( net-dialup/freeradius-client )
 	snmp? ( net-analyzer/net-snmp )
 	span? ( media-libs/spandsp )
 	speex? ( media-libs/speex )
@@ -218,7 +218,7 @@ src_install() {
 	emake DESTDIR="${D}" install
 
 	if use radius; then
-		insinto /etc/radiusclient-ng/
+		insinto /etc/radiusclient/
 		doins contrib/dictionary.digium
 	fi
 	diropts -m 0750 -o root -g asterisk

**Comment by mgorny** [comment]
@gentoochainsaw

**Comment by mgorny** [comment]
@gentoochainsaw the big shiny 'merge' button won't help ya. The merge commit need to be pushed to git.g.o actually. I'll do that for you now.

**Comment by gentoochainsaw** [comment]
Don't give me buttons that don't do anything...

**Comment by mgorny** [comment]
@gentoochainsaw can't do nothing about it. Either you have both 'merge' and 'close', or none. And @vapier complained when I disabled both by default…

**Pull request merged**
