### PR TITLE
net-im/skypeforlinux: Bump version to 8.52.0.138

### PR DESCRIPTION
**Pull request by jvesely**
Bug: https://bugs.gentoo.org/692692
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
The bumped ebuild includes added kernel config checks

**Comment by juippis** [comment]
1st: I was suspicious if using chromium-2.eclass was a bit too much for a simple thing like this. It seems pretty light, and accectable if all of the requirements are needed with skype as well. AFAIK the talk was only about USER_NS, while now it requires a lot more.

2nd: You need to shrink your git commit summary so it doesn't wrap, I think the limit is 72 chars :)

3rd: Addition and removal of ebuilds go into separate commits. Don't use `git mv`. 

4th: You can squash the first two commits, ie add the kernel checks during a version bump for final version (no need for 2 commits).

**Comment by jvesely** [comment]
> 1st: I was suspicious if using chromium-2.eclass was a bit too much for a simple thing like this. It seems pretty light, and accectable if all of the requirements are needed with skype as well. AFAIK the talk was only about USER_NS, while now it requires a lot more.
> 
> 2nd: You need to shrink your git commit summary so it doesn't wrap, I think the limit is 72 chars :)
> 
> 3rd: Addition and removal of ebuilds go into separate commits. Don't use `git mv`.
> 
> 4th: You can squash the first two commits, ie add the kernel checks during a version bump for final version (no need for 2 commits).

done. thanks for the review.
I think that all configuration options are needed it just that `USER_NS` got hit in bug #692692.

**Comment by juippis** [comment]
Thanks :)

**Pull request closed without merging**
