### PR TITLE
dev-python/*: correct DISTUTILS_USE_SETUPTOOLS

### PR DESCRIPTION
**Pull request by jsmolic**

### CODE REVIEW

**Comment by mgorny** [comment]
Have you checked them for false positives?

**Comment by jsmolic** [comment]
@mgorny Good point, I think I found some falses ([#745678](https://bugs.gentoo.org/745678), [#746233](https://bugs.gentoo.org/746233), [#746683](https://bugs.gentoo.org/746683)). There are possibly few more, so I dropped those for now and will look into them further, the rest should be OK

**Comment by mgorny** [comment]
Things to look for:

1. `console_scripts` type entry points (in setup.py or setup.cfg)
2. `pkg_resources` imports inside the package

If either is present, rdepend is correct. We don't check directly for the latter but instead rely on upstream having a install_requires on setuptools.

Please let me know if the check gets this wrong. Note that some packages removed pkg_resources use but didn't remove setuptools install_requires, that's an upstream bug to fix.

**Comment by jsmolic** [comment]
@mgorny Thanks, I'm  reading through the Python guide now. Just to clarify, any type of entry points suggests rdepend, or only `console_scripts` ones?

**Comment by sbraz** [comment]
@jsmolic I think it's only console_scripts, you can also `qlist -e package | xargs grep -E 'pkg_resources|setuptools'` or something to check whether it is used. In some cases setuptools is used but not declared in `install_requires`. In that case, an upstream bug needs to be filed.

**Comment by jsmolic** [comment]
I checked everything, and most of the bug reports are good, those are marked as OK. I opened a bunch of upstream bugs, comment and links are included next to packages for which I opened bugs. 
There are few false reports so those bugs can probably be closed.

(I'm not 100% sure about few bugs, so I will go through those again tomorrow, those commits are dropped from the PR)

Here is the full report:

`dev-python/pytest-pylint` - OK
`dev-python/cython` - OK
`dev-python/zope-interface` - OK 
`dev-python/zope-event` - OK
`dev-python/zope-component` - OK
`dev-python/zope-testing` - OK
`dev-python/requests-mock` - OK
`dev-python/sphinx_rtd_theme` - OK
`dev-python/jsonpickle` - OK
`dev-python/readme_renderer` - OK
`dev-python/cheetah3` - OK

`dev-python/autopep8` - OK, uses setuptools as rdepend , but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/hhatto/autopep8/issues/573)

`dev-python/python-vitrageclient` - OK, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://storyboard.openstack.org/#!/story/2008245)

`dev-python/python-blazarclient` - OK, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://bugs.launchpad.net/blazar/+bug/1899382)

`dev-python/alembic` - OK, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/alembic/alembic/issues/319)

`dev-python/unittest2` - OK, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/testing-cabal/unittest-ext/issues/103)

`dev-python/google-auth-oauthlib` - OK, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/googleapis/google-auth-library-python-oauthlib/issues/91)

`dev-python/cairocffi` - (https://bugs.gentoo.org/747709)  - **False report**, does not use setuptools, but mentions it in `install_requires` (Upstream bug -> https://github.com/Kozea/cairocffi/issues/163)

`dev-python/cssselect2` -(https://bugs.gentoo.org/747715) -  **False report**, does not use setuptools, but mentions it in `install_requires` (Upstream bug -> https://github.com/Kozea/cssselect2/issues/18


`dev-python/repoze-lru` (https://bugs.gentoo.org/745675) - **False report**, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/repoze/repoze.lru/issues/32)

`dev-python/pastedeploy` - (https://bugs.gentoo.org/745678) - **False report**, uses setuptools as rdepend, but it's not mentioned in `install_requires` (Upstream bug -> https://github.com/Pylons/pastedeploy/issues/28)

**Comment by mgorny** [comment]
That's surprisingly many. I've chosen alembic randomly, and I don't see how it uses setuptools at runtime. Could you elaborate?

**Comment by jsmolic** [comment]
Heh I actually opened up a bug for alembic at the wrong repo, it should be https://github.com/sqlalchemy/alembic, which has console_scripts entry point in setup py (https://github.com/sqlalchemy/alembic/blob/master/setup.py#L78)

**Comment by mgorny** [comment]
console_scripts mustn't have install_requires. Dependency on setuptools is an implementation detail.

**Comment by jsmolic** [comment]
Thanks, I will close the first few opened upstream issues then. I have updated the list accordingly.

**Comment by jsmolic** [comment]
`dev-python/PyContracts` - OK
`dev-python/PyUtilib` - OK
`dev-python/HeapDict` - OK
`dev-python/aiosmtpd` - OK
`dev-python/alabaster` - OK
`dev-python/betamax` - OK
`dev-python/beagle` - OK, [uses setuptools at rdepend](https://github.com/beaglecli/beagle/blob/master/beagle/app.py#L16) but does not list it in install_requires (Upstream PR -> https://github.com/beaglecli/beagle/pull/14)
`dev-python/blurb` - OK
`dev-python/celery` - OK
`dev-python/crcmod` - OK
`dev-python/ctypescrypto` - OK

**Comment by mgorny** [comment]
I just need to know if you checked it all for false positives.

**Comment by jsmolic** [comment]
> I just need to know if you checked it all for false positives.

Out of bugs addresed in this PR, there were 4 false reports, I'll mention them again here. All of them were caused by upstream not adding/removing setuptools from `install_requires` , and 3 out of 4 have already been fixed upstream


dev-python/cairocffi - (https://bugs.gentoo.org/747709) - False report, does not use setuptools, but mentions it in install_requires (Upstream bug -> Kozea/cairocffi#163)

dev-python/cssselect2 -(https://bugs.gentoo.org/747715) - False report, does not use setuptools, but mentions it in install_requires (Upstream bug -> Kozea/cssselect2#18

dev-python/repoze-lru (https://bugs.gentoo.org/745675) - False report, uses setuptools as rdepend, but it's not mentioned in install_requires (Upstream bug -> repoze/repoze.lru#32)

dev-python/pastedeploy - (https://bugs.gentoo.org/745678) - False report, uses setuptools as rdepend, but it's not mentioned in install_requires (Upstream bug -> Pylons/pastedeploy#28)

**Comment by mgorny** [comment]
Do I see correctly that you've skipped these packages here, so effectively everything here is verified and good?

**Comment by jsmolic** [comment]
Yes, I skipped those 4 packages as there is nothing to fix so those bugs can be closed. Rest of the bug reports are OK and checked

**Comment by jsmolic** [comment]
Actually I can add `DISTUTILS_USE_SETUPTOOLS=no` for first 2 and `DISTUTILS_USE_SETUPTOOLS=rdepend` for other 2 packages, but I don't know if the same bug reports will reapper later...

**Comment by mgorny** [comment]
Just leave them as-is for now.

**Comment by mgorny** [comment]
(presumably the new version will give a correct warning)

**Comment by mgorny** [comment]
Thanks for doing this!

**Comment by jsmolic** [comment]
Thanks to you as well

**Pull request closed without merging**
