### PR TITLE
Fix libtool on darwin

### PR DESCRIPTION
**Pull request by DarthGandalf**
@grobian @thesamesam

### CODE REVIEW

**Comment by orbea** [comment]
Hard coding `libtool` might break the build with slibtool, but does that even work as is? Its strange that llvm would want to use libtool at all...

**Comment by DarthGandalf** [comment]
@orbea this is how it uses it: https://github.com/llvm/llvm-project/blob/llvmorg-17.0.6/llvm/cmake/modules/UseLibtool.cmake.

Without this, it uses the libtool provided by XCode, which might or might not work depending on CFLAGS, see the attached bug.

**Comment by thesamesam** [comment]
I think this is fine for now. We need to figure out slibtool on macOS but getting an LLVM bootstrap working at all properly is critical and more important before we work on alt configs.

**Comment by grobian** [comment]
> Hard coding `libtool` might break the build with slibtool, but does that even work as is? Its strange that llvm would want to use libtool at all...

macOS/Darwin `libtool` is not GNU `glibtool` or `slibtool`.  It is a helper available in the system toolchain to create libraries.  It is similar to ranlib, but then for dynamic libraries, and specific to Darwin platforms only.

**Comment by grobian** [comment]
> I think this is fine for now. We need to figure out slibtool on macOS but getting an LLVM bootstrap working at all properly is critical and more important before we work on alt configs.

I thought `slibtool` just compiled/worked, but that we couldn't use it because it wasn't 100% compatible at the time.  But like I wrote before, slibtool vs GNU libtool is a completely different thing than Darwin libtool.

**Pull request closed without merging**
