### PR TITLE
cmake-multilib.eclass EAPI-7 cleanups

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by a17r** [comment]
games-emulation/ppsspp - subslot dep is real?

**Review by sarnex — APPROVED** [review]
vulkan stack rb

**Comment by sarnex** [comment]
> games-emulation/ppsspp - subslot dep is real?
seems like yes, fails to run if compiled with 0/12 slot
```
PPSSPPQt: error while loading shared libraries: libglslang.so.11: cannot open shared object file: No such file or directory
```

**Comment by a17r** [comment]
https://bugs.gentoo.org/894582

**Comment by xgqt** [comment]
games-emulation/ppsspp issue resolved!

**Review by xgqt — APPROVED** [review]

**Pull request merged**
