### PR TITLE
dev-util/nvidia-cuda-toolkit: Bump to 10.1.105

### PR DESCRIPTION
**Pull request by jvesely**
Other changes:
Bump to EAPI=7
Don't use versionator
Update SRC_URI file name
Don't unpack the source file twice
Use dobin + doins instead of mv

Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
I've tested the build by rebuilding pycuda and running simple kernel.
Useflags mostly remove content +doc adds documentation and Oleg confirmed that it works in https://bugs.gentoo.org/679412

**Comment by hsntgm** [comment]
@jvesely did you look to https://bugs.gentoo.org/681694
They changed the folder structure for the install, cublas was moved to a separate folder.
Is this PR fixing it?

Also cudnn depends to cuda toolkit.I think for being sure, this package must be test by calling cudnn directly too.

Let me know if you want to work together for both packages.I need them urgently.

**Comment by jvesely** [comment]
> @jvesely did you look to https://bugs.gentoo.org/681694
> They changed the folder structure for the install, cublas was moved to a separate folder.
> Is this PR fixing it?

the ebuild changes dir to `builds/cuda-toolkit` and install stuff from there.
`libcublas` and `libcublas` are installed correctly (no broken linkage), but I haven't tested them.

> 
> Also cudnn depends to cuda toolkit.I think for being sure, this package must be test by calling cudnn directly too.
> 
> Let me know if you want to work together for both packages.I need them urgently.

I don't, sorry. I have no interest beyond getting the basic toolkit and pycuda working on a system with gcc 8.2.
That said, afaict, the toolkit installation should be compatible, so there shouldn't be problems for dependent packages.

**Comment by jvesely** [comment]
@perfinion, @alexxy  you handled the previous bump. Any thoughts on this one?

**Comment by perfinion** [comment]
This mostly looks good to me, it installs on my system. I bumped cudnn too. I need to test TensorFlow with it first then I'll merge it tomorrow.

**Comment by jvesely** [comment]
> This mostly looks good to me, it installs on my system. I bumped cudnn too. I need to test TensorFlow with it first then I'll merge it tomorrow.

Hi @perfinion , has there been any problem with TensorFlow?

**Comment by perfinion** [comment]
@jvesely yeah, cuda-10.1 is kind of a mess haha. TensorFlow doesnt work at all with it yet. I just set the deps on TF to force only 10.0 for now. When upstream ports it to cuda 10.1 then i'll backport the patch. 

I pushed everything now. Thanks for the patch :).

**Pull request closed without merging**
