### PR TITLE
app-crypt/keybase Version bump from 4.7.0 to 5.1.1 build

### PR DESCRIPTION
**Pull request by Rudi9719**
Signed-off-by: Gregory 'Rudi' Rudolph-Alverson rudi@nmare.net

### CODE REVIEW

**Comment by nicolasbock** [comment]
@Rudi9719 Try removing the Manifest file.

**Comment by Rudi9719** [comment]
It looks like the manifest file is required?

**Comment by nicolasbock** [comment]
Hmm, ok that's a good point. Could you add it again? Sorry for that back and forth. Let's try again what error message you are getting with the Manifest.

**Comment by Rudi9719** [comment]
I added it back, I removed more ebuilds so it just has the 9999 ebuild (Assuming that's latest?) and the 5.1.1 version since the older versions may not be compatible (I noticed that it was out of date due to features not working properly)

**Comment by nicolasbock** [comment]
Yes, the `9999` version is the live ebuild, i.e. it pulls from git and then builds the client. Thanks!

**Comment by nicolasbock** [comment]
Have you looked into `repoman`? That takes care of manifests and things like that automatically.

**Comment by nicolasbock** [comment]
I think this looks good. I'll merge it. Thanks for the help!

**Comment by Rudi9719** [comment]
I'll look into `repoman` and try to keep a more thorough eye on the versions in the future! Thank you so much for helping me figure this out!

**Pull request closed without merging**
