### PR TITLE
*/* xfce.org to https

### PR DESCRIPTION
**Pull request by soredake**

### CODE REVIEW

**Comment by mgorny** [comment]
Did you happen to test all those URLs or is it something for me to do? ;-)

**Comment by soredake** [comment]
@mgorny links work, there are a couple of links with redirects.

**Comment by mgorny** [comment]
By 'redirects', I suppose you mean 'redirects because of old link or something', not 'redirects from https back to http'? ;-)

**Comment by soredake** [comment]
@mgorny this  `'redirects because of old link or something'`

full list by awesome_bot
```
  2. [L05] 302 https://goodies.xfce.org/projects/applications/parole/  → https://docs.xfce.org/apps/parole/start
  3. [L59]  http://foo-projects.org/~benny/projects/xfce4-dev-tools/ execution expired 
  4. [L61] 302 http://thunar.xfce.org/  → http://www.xfce.org/ 
  5. [L63] 301 https://www.xfce.org/projects/libraries/  → http://docs.xfce.org/xfce/exo// 
  6. [L64] 404 https://www.xfce.org/projects/libxfce4  
  7. [L65] 301 https://www.xfce.org/projects/terminal/  → http://docs.xfce.org/apps/terminal// 
  8. [L66] 301 https://www.xfce.org/projects/thunar/  → http://docs.xfce.org/xfce/thunar// 
  9. [L67] 404 https://www.xfce.org/projects/xfce4-mixer/ 
```

**Comment by soredake** [comment]
I can update this links, if you want.

**Comment by mgorny** [comment]
That would be really great, TIA!

**Comment by soredake** [comment]
Done.

**Comment by mgorny** [comment]
@perfinion, care to fix those yourself? ;-)

**Comment by soredake** [comment]
@mgorny done.

**Comment by perfinion** [comment]
@soredake Thanks a ton for all the cleanups! I've merged this in, will push in a while :)

**Pull request closed without merging**
