### PR TITLE
ca-certificates: depend either on c_rehash or latest openssl that provides it

### PR DESCRIPTION
**Pull request by Wonko7**
Without this, openssl-1.0.2d-r1 won't merge because of a file collision with app-misc/c_rehash. 
With this modification, depclean will remove c_rehash, and then openssl can be merged.

### CODE REVIEW

**Comment by hasufell** [comment]
what the? That's not correct

**Comment by hasufell** [comment]
`openssl-1.0.2d-r1` does _not_ install `c_rehash` anymore and `app-misc/c_rehash` does block `!<dev-libs/openssl-1.0.2d-r1:0`, so there can't be any file collision

**Comment by Wonko7** [comment]
Well then there's something wrong with the openssl-1.0.2d-r1 ebuild, because I'm getting: 
 * Messages for package dev-libs/openssl-1.0.2d-r1:
 * Detected file collision(s):
 *      /usr/bin/c_rehash
 * Searching all installed packages for file collisions...
 * app-misc/c_rehash-1.7-r1:0::gentoo
 *      /usr/bin/c_rehash

**Comment by hasufell** [comment]
This is going to be fixed soon, but differently.

**Comment by hasufell** [comment]
https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=c4c12cc9ea4ca269107df171634d8994c65db05e

**Pull request closed without merging**
