### PR TITLE
net-p2p/qbittorrent: add 4.6.3

### PR DESCRIPTION
**Pull request by stkw0**
Also:
 - add myself as a maintainer
 - drop 4.6.0

### CODE REVIEW

**Comment by thesamesam** [comment]
See also https://github.com/gentoo/gentoo/pull/34949.

**Comment by thesamesam** [comment]
You're still free to adopt the package with Eli though.

**Comment by stkw0** [comment]
Thanks. Maybe in a future I will. If the other person is already active we would need to coordinate to avoid making two times the same PR, etc. So, for now I think it's easier to let the other maintainer take care of it.

**Comment by eli-schwartz** [comment]
Hmm, really that bug report should have been closed when 4.6.1 was added to the tree on the grounds that it was fixed at that time.

The existence of an older ebuild with the bug still there doesn't mean the bug wasn't fixed. :)

**Comment by stkw0** [comment]
I think that if an older ebuild has a known issue that can be hit by a user, makes sense to keep the bug open (even more if the ebuild references a specific version). Obviously, it would be better to fix the ebuild or drop it instead of keeping a buggy version when a new one doesn't has that problem.

**Pull request closed without merging**
