### PR TITLE
www-client/chromium: add "extra-fonts" USE flag

### PR DESCRIPTION
**Pull request by maciejsszmigiero**
www-client/chromium has long recommended installing a set of extra font
packages that are needed by some websites.

However, if they are installed separately they won't be marked as
dependencies of www-client/chromium.
This means that one has to remember to manually remove them when removing
chromium (and that's bad since human memory is limited).

Let's make these packages an optional runtime dependency of
www-client/chromium instead (behind "extra-fonts" USE flag) so they will be
correctly accounted for by depclean.

### CODE REVIEW

**Comment by floppym** [comment]
I do not agree with this change and will not merge it.

**Comment by maciejsszmigiero** [comment]
So how people that follow www-client/chromium ebuild advice and install these
additional fonts are supposed to know they need to remove them when they
(possibly much later) uninstall www-client/chromium?

If they are supposed to "just remember" to do it then that equals to moving
a job that is hard for a human to do but is very easy for a computer to do
from a computer to a human - a bad thing.

BTW: If you want to solve this issue in a different way than I did in this
pull request I'm fine with that, naturally.
The reason that I've opened a PR and not a bug is because I thought
proposing a 'turnkey' solution would involve less maintainer work and
so would result in resolving the issue faster.

**Comment by floppym** [comment]
> So how people that follow www-client/chromium ebuild advice and install these additional fonts are supposed to know they need to remove them when they (possibly much later) uninstall www-client/chromium?

I don't see this as a problem that needs solving.

If people want to display foreign characters, they will need extra fonts. If they don't care about foreign characters, they wont install them in the first place. Whether they have Chromium installed or not is not really relevant in that case.

The elog message is merely a suggestion so that people don't file bugs when they see missing characters on web pages.

**Comment by maciejsszmigiero** [comment]
> If people want to display foreign characters, they will need extra fonts.

If I were a Chinese I wouldn't consider Chinese characters 'foreign'.
Gentoo is a global distribution, so we should look at issues from
a global perspective.

Let's consider a possible use case of this package:
1) A user installs www-client/chromium,
2) www-client/chromium prints a message during installation
that some web pages (which ones? the message doesn't say)
may need some extra fonts (again, it is unspecified which
particular ones from the presented list),
3) Because the message isn't very specific the user does not
install any of these fonts at this time.

Some time later the user visits a web page and sees that some
characters aren't displayed correctly.
Would he or she remember the message printed at the package
install time? Probably not, but let's assume that he or she does,
so:
4) The user installs these 9 suggested font packages.

Once again, some time has passed.
The user has determined he or she does not like
the Chromium browser anymore, so:
5) The user uninstalls www-client/chromium,
6) Because a long time has passed since point 4) the user most likely
doesn't remember that he or she also installed these extra font packages
so he or she does not unmerge them with www-client/chromium,
7) Since these font packages aren't specified as dependencies
of the Chromium package they aren't removed as a part of a depclean,
8) The user has 'orphaned' font packages in the system, unneeded but
still installed.

Considering that adding this new USE flag has a nearly zero cost why
not do it as a courtesy to the user from the example above?

BTW, from these 9 suggested font packages 3 seem to not have any reverse
dependency at all (bitstream-cyberbit, ipamonafont, takao-fonts) while one
more (ja-ipafonts) only has a reverse dependency on an upstream-unmaintained
media-fonts/infinality-ultimate-meta package.

**Comment by floppym** [comment]
Sorry, but I'm not going to argue about this any further. Thank you for the patch, but I will not be merging it.

**Pull request closed without merging**
