### PR TITLE
games-strategy/s25rttr: fix QA issues

### PR DESCRIPTION
**Pull request by stefson**
Fixes: https://bugs.gentoo.org/660270

ccing @pacho2 and @a17r , could either of you merged this?

### CODE REVIEW

**Comment by stefson** [comment]
reopening and pinging @mgorny

**Comment by chewi** [comment]
If you're removing that line then the `case` statement above it can go too.

**Comment by stefson** [comment]
Can please refer to the lines to be removed? I'm also not really happy with the build system, but upstream has almost entirely rewritten the source code since 0.8.0 was released, 0.9.0 is in the making. I've got a working live ebuild in my overlay if you're interested.

**Comment by chewi** [comment]
Lines 48-55.

That's good news but we can wait. Did you notice that 0.8.2 was released this week?

**Comment by stefson** [comment]
Hmm, not sure what you're refering to. 0.8.2 has been branched severall times with I believe patchlevel 18 beind released back in 2017. In any case: I removed the lines, is it good to go?

**Comment by chewi** [comment]
Sorry I was confused by their downloads page. Merged.

**Comment by stefson** [comment]
You might want to add their github repo as a second homepage? 😅

**Pull request closed without merging**
