### PR TITLE
app-text/discount: version bump to 2.2.4

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by l29ah** [comment]
Bureaucracy grows steadily, sir!

**Comment by hsoft** [comment]
Here's more bureaucracy for you :) You should add a link to https://bugs.gentoo.org/658482 in your commit (`Bug: https://bugs.gentoo.org/658482`)

**Comment by hsoft** [comment]
@l29ah it looks like the current proxied maintainer for this package isn't very active. Would to be interested in proxy-maintaining this?

**Comment by l29ah** [comment]
Not sure if i'm enthusiastic enough after https://github.com/gentoo/gentoo/pull/9716, but i'd give it a try.

**Comment by hsoft** [comment]
I've pinged the current maintainer in https://bugs.gentoo.org/658482 . If you submit another PR on this package and that Dmitry hasn't stepped up, add yourself as maintainer in `metadata.xml`.

**Pull request closed without merging**
