### PR TITLE
Add dev-python/uvloop

### PR DESCRIPTION
**Pull request by elprans**
uvloop is a fast, drop-in replacement of the built-in asyncio
event loop. uvloop is implemented in Cython and uses libuv under
the hood.

http://github.com/MagicStack/uvloop

Gentoo-Bug: https://bugs.gentoo.org/show_bug.cgi?id=582768
Package-Manager: portage-2.2.28

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by idella** [comment]
PYTHON_COMPAT=( python3_5 ) only?

**Comment by monsieurp** [comment]
For some reason, I cannot fetch the package sources when testing it. Also, as Ian just pointed out, why is python 3.5 supported for this ebuild? Can't we add more implementations?

**Comment by elprans** [comment]
> For some reason, I cannot fetch the package sources when testing it. 

Appears to be a PyPI mirror issue.  I'll see if that can be sorted out.

> Also, as Ian just pointed out, why is python 3.5 supported for this ebuild? Can't we add more implementations?

Current version of uvloop is python-3.5-only at this moment, as it implements asyncio APIs found only in 3.5.

**Comment by elprans** [comment]
Download works for me now:

```bash
Calculating dependencies... done!
[ebuild   R   ~] dev-python/uvloop-0.4.19::sprymix  USE="{-test*}" PYTHON_TARGETS="python3_5" 1,738 KiB

Total: 1 package (1 reinstall), Size of downloads: 1,738 KiB

Would you like to merge these packages? [Yes/No] 

>>> Verifying ebuild manifests

>>> Emerging (1 of 1) dev-python/uvloop-0.4.19::sprymix
>>> Downloading 'http://distfiles.gentoo.org/distfiles/uvloop-0.4.19.tar.gz'
--2016-05-12 11:19:56--  http://distfiles.gentoo.org/distfiles/uvloop-0.4.19.tar.gz
Resolving distfiles.gentoo.org... 140.211.166.134, 156.56.247.195, 64.50.236.52, ...
Connecting to distfiles.gentoo.org|140.211.166.134|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-12 11:19:57 ERROR 404: Not Found.

>>> Downloading 'https://pypi.python.org/packages/source/u/uvloop/uvloop-0.4.19.tar.gz'
--2016-05-12 11:19:57--  https://pypi.python.org/packages/source/u/uvloop/uvloop-0.4.19.tar.gz
Resolving pypi.python.org... 23.235.40.223
Connecting to pypi.python.org|23.235.40.223|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-05-12 11:19:57 ERROR 404: Not Found.

>>> Downloading 'https://pypi.io/packages/source/u/uvloop/uvloop-0.4.19.tar.gz'
--2016-05-12 11:19:57--  https://pypi.io/packages/source/u/uvloop/uvloop-0.4.19.tar.gz
Resolving pypi.io... 151.101.128.223, 151.101.64.223, 151.101.0.223, ...
Connecting to pypi.io|151.101.128.223|:443... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://files.pythonhosted.org/packages/source/u/uvloop/uvloop-0.4.19.tar.gz [following]
--2016-05-12 11:19:57--  https://files.pythonhosted.org/packages/source/u/uvloop/uvloop-0.4.19.tar.gz
Resolving files.pythonhosted.org... 172.111.69.6                                                                                                                                                                                                                                                                               
Connecting to files.pythonhosted.org|172.111.69.6|:443... connected.                                                                                                                                                                                                                                                           
HTTP request sent, awaiting response... 302 Found                                                                                                                                                                                                                                                                              
Location: https://files.pythonhosted.org/packages/34/17/08d8849f8dc303165d10db4889bb71c35e54ad04df3ddc99118a8e8a1759/uvloop-0.4.19.tar.gz [following]                                                                                                                                                                          
--2016-05-12 11:19:58--  https://files.pythonhosted.org/packages/34/17/08d8849f8dc303165d10db4889bb71c35e54ad04df3ddc99118a8e8a1759/uvloop-0.4.19.tar.gz                                                                                                                                                                       
Reusing existing connection to files.pythonhosted.org:443.                                                                                                                                                                                                                                                                     
HTTP request sent, awaiting response... 200 OK                                                                                                                                                                                                                                                                                 
Length: 1778724 (1.7M) [application/octet-stream]                                                                                                                                                                                                                                                                              
Saving to: ‘/srv/portage/distfiles/uvloop-0.4.19.tar.gz’                                                                                                                                                                                                                                                                       
                                                                                                                                                                                                                                                                                                                               
/srv/portage/distfi 100%[=====================>]   1.70M  1.90MB/s   in 0.9s                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                               
2016-05-12 11:19:59 (1.90 MB/s) - ‘/srv/portage/distfiles/uvloop-0.4.19.tar.gz’ saved [1778724/1778724]                                                                                                                                                                                                                        
                                                                                                                 
```

**Comment by idella** [comment]
I shall look more closely shortly

**Comment by idella** [comment]
'Programming Language :: Python :: 3.5',
You do NOT have to be so strictly obedient to the settings like this.
except in this case
```bash
 File "setup.py", line 10, in <module>
    raise RuntimeError('uvloop requires Python 3.5 or greater')
```
```bash
dev-python/uvloop $ ls /path/2/uvloop-0.4.19/examples/bench/examples/bench
```

displays you have skipped over installing the examples. Why so?
I normally ALWAYS include the examples if present in pythonic ebuilds, purely on the basis of gentoo is about choice.
Upstream made examples but you do not make them available to user. For the sake of around 3 more lines of basic code.
Why so?

**Comment by idella** [comment]
Also
DOCS=( README.rst )
not required.  The python eclass distutils-r1 supplies a default install of any pertinent DOCS. You set the car DOCS if you really wish to over ride what is installed by default by the eclass.

**Comment by elprans** [comment]
> displays you have skipped over installing the examples. Why so?
I normally ALWAYS include the examples if present in pythonic ebuilds, purely on the basis of gentoo is about choice.

EXAMPLES are banned in EAPI 6:

https://archives.gentoo.org/gentoo-dev/message/aa252840667dfbab3cf7d20ce1759d0e

**Comment by elprans** [comment]
Pushed an updated version.

**Comment by idella** [comment]
elprans lemme explain
in EAPI 5 there was a var EXAMPLES which had a default install by distutils-r1.
In EAPI 6 this var was banned but the examples can still be managed. You only need to look through dev-python and find some examples of examples in EAPI 6.
Basically you use the old fashioned approach to do them. Quite easy.

I shall git into your branch and add it since examples are purely an option anyway. While I prefer you still to add them, you can do so in a separate pull re, with a revbump since the state of the installed files will differ.

**Comment by idella** [comment]
Hmm I see there has been a new release to uvloop-0.4.20. The doc build nptmally requires to add html but this does a default build of html.

For an example, see irc-14.2.ebuild. I shall add shortly

**Comment by elprans** [comment]
> elprans lemme explain
> in EAPI 5 there was a var EXAMPLES which had a default install by distutils-r1.
> In EAPI 6 this var was banned but the examples can still be managed. You only need to look through dev-python and find some examples of examples in EAPI 6.

OK. I pushed an updated version that installs examples.

**Comment by idella** [comment]
that was quick

**Comment by idella** [comment]
<longdescription> in metadata could be line split but you can do that next time
adding

**Comment by idella** [comment]
Also edited the commit msg to match required form for gentoo format. Please take note and use in furture submissions.  It need begin with the package <atom> 
The extended description form line 3 is fine.

**Pull request closed without merging**
