### PR TITLE
net-im/synapse: Matrix homeserver and its dependencies

### PR DESCRIPTION
**Pull request by arkamar**
This is a set of ebuilds needed for `net-im/synapse` matrix.org reference server which I am willing to maintain in `::gentoo`. I was brewing them in private and later in [public overlay](https://github.com/arkamar/synapse-overlay) for few months already and I would say they are in decent shape now.
- All ebuilds use new `PEP517`.
- Tests mostly work, with following exceptions (related ebuilds set `RESTRICT="test"`):
	- `dev-python/pymacaroons` - it requires `<dev-python/hypothesis-2.0.0` which is not available in `::gentoo` anymore.
	- `dev-python/frozendict` - most of tests pass, but 7 of 477 tests fail with py3.9 and 1 of 483 fails with py3.10. py3.11 is not supported yet.
- UID/GID in `acct-{user,group}/synapse` are set to `519`, see https://github.com/gentoo/api-gentoo-org/pull/526.
- `net-im/synapse` is usually released every 14 days and ebuild version bumps are pretty straight forward. 

I wrote `synapse.initd` in order to make `net-im/synapse` package complete, it works, but I don't use OpenRC nor Systemd and it would most probably require some revisions.

So, tell me, what do you think?

### CODE REVIEW

**Comment by arkamar** [comment]
I force-pushed `net-im/synapse` in order to fix dependency requierements to `=dev-python/matrix-common-1.1*` which I found when `dev-python/matrix-common` was bumped to `1.2.1`. `dev-python/canonicaljson` is bumped as well.

**Comment by arkamar** [comment]
FP on top of current `master`, I have changed UID/GID to 515 as requested in https://github.com/gentoo/api-gentoo-org/pull/526. `net-im/synapse` is bumped to `1.61.0`.

**Comment by arkamar** [comment]
FP with version bumped to `1.61.1`.

**Comment by arkamar** [comment]
FP with `net-im/synapse-1.62.0` and passing tests. This version requires `>=dev-python/matrix-common-1.2.1`, therefore, older version is no longer necessary.

**Comment by arkamar** [comment]
FP with updated UID/GID to 519 in `acct-*/synapse` due to a rebase in https://github.com/gentoo/api-gentoo-org/pull/526.

**Comment by thesamesam** [comment]
Great work and a much-in-demand package!

**Comment by arkamar** [comment]
Thanks!

**Pull request closed without merging**
