### PR TITLE
bump mail-client/evolution, gnome-extra/evolution-ews, gnome-extra/evolution-data-server

### PR DESCRIPTION
**Pull request by Schievel1**
Signed-off-by: Pascal Jäger <pascal.jaeger@leimstift.de>

- [x] mail-client/evolution requires webkit2gtk-4.1 slot, so this PR has to wait until this is done. 
- [x] gnome-extra/evolution-ews is asking for libuhttpmock-1.0, but on their repo the latest tag has only 0.0. This is only relevant when USE="test"
- [ ] gnome-extra/evolution-data-server and mail-client/evolution require dev-lib/libgweather-3.91.0 when USE="weather". (Default is +weather, so careful). libgweather-3.91.0 does not exist yet.  See https://github.com/gentoo/gentoo/pull/27375

### CODE REVIEW

**Comment by mattst88** [comment]
>  gnome-extra/evolution-data-server and mail-client/evolution require dev-lib/libgweather-3.91.0 when USE="weather". (Default is +weather, so careful). libgweather-3.91.0 does not exist yet.

This is just `dev-libs/libgweather:4.0`.

**Comment by mattst88** [comment]
For evolution-data-server, I saw these things in the `pkgdiff -b` output:

- gcr and libgdata deps dropped
- ENABLE_GOOGLE option is removed
- libsoup :2.4 -> :3.0
- webkit2 2.28 -> 2.34
- new webkit2gtk4 dep (behind ENABLE_GTK4 option, not enabled yet)
- gtk 3.16 -> 3.20
- glib 2.46 -> 2.68
- json-glib becomes an unconditional dependency

Looks like you handled all of those properly. Did I miss anything?

**Comment by mattst88** [comment]
For evolution-ews, I saw these things in the pkgdiff -b output:

- glib 2.62 -> 2.68
- libsoup :2.4 -> :3.0
- new dependency on uhttpmock-1.0 (TODO)

Looks like you handled all of those properly. Did I miss anything?

**Comment by Schievel1** [comment]
> > gnome-extra/evolution-data-server and mail-client/evolution require dev-lib/libgweather-3.91.0 when USE="weather". (Default is +weather, so careful). libgweather-3.91.0 does not exist yet.
> 
> This is just `dev-libs/libgweather:4.0`.

I installed 4.0.0 but it still complains about that libgweather is not built with libsoup3

**Comment by mattst88** [comment]
> > > gnome-extra/evolution-data-server and mail-client/evolution require dev-lib/libgweather-3.91.0 when USE="weather". (Default is +weather, so careful). libgweather-3.91.0 does not exist yet.
> > 
> > 
> > This is just `dev-libs/libgweather:4.0`.
> 
> I installed 4.0.0 but it still complains about that libgweather is not built with libsoup3

This is confusing... I see libgweather-4.2.0 was just released, but its `meson.build` file says:

````
if get_option('soup2')
  libsoup_name = 'libsoup-2.4'
  libsoup_req_version = '>= 2.44.0'
  libsoup_api_version = '2.4'
  geocode_glib_dep = dependency('geocode-glib-1.0')
else
  libsoup_name = 'libsoup-3.0'
  libsoup_req_version = '>= 2.99.2'
  libsoup_api_version = '3.0'
  geocode_glib_dep = dependency('geocode-glib-2.0')
endif
````

but regardless of whether I build `geocode-glib` with `-Dsoup2=true` or `-Dsoup3=false` it only installs `geocode-glib-1.0.pc`.

The `geocode-glib` `NEWS` file says
````
3.26.3
------

This release adds support for libsoup 3.x. To use the libsoup 3.x build,
applications will need to be adapted to look for the "-2.0" version of the API.
This allows both native and interpreted applications to select which version
of libsoup they want geocode-glib to use as the backend, and for both versions
to be installed in distributions.
````

so I'm not sure if we're supposed to be manually renaming the geocode-glib files...? I've filed https://gitlab.gnome.org/GNOME/geocode-glib/-/issues/32 and asked what to do.

**Comment by mattst88** [comment]
For `evolution`, I saw these things in the `pkgdiff -b` output:

- glib 2.56 -> 2.66
- libsoup :2.4 -> :3.0
- gcr dep dropped
- webkit-gtk 2.28 -> 2.34 (and requires libsoup:3)
- geocode-glib 3.10 -> 3.26.3
- `ENABLE_WEATHER` / `WITH_GWEATHER4` options
- `ENABLE_CONTACT_MAPS` is disabled

**Review by mattst88 — CHANGES_REQUESTED** [review]

**Comment by Schievel1** [comment]
>     * `ENABLE_CONTACT_MAPS` is disabled

What? Why? Where?

**Comment by mattst88** [comment]
I've added `net-libs/uhttpmock-0.9.0:1.0` to Gentoo now that it has been released.

**Comment by Schievel1** [comment]
Now `pkgcheck` says 
```
  NonexistentDeps: version 3.46.0: RDEPEND: nonexistent packages: >=net-libs/webkit-gtk-2.34.0:4.1=, >=net-libs/webkit-gtk-2.34.0:4.1, >=sci-geosciences/geocode-glib-3.26.3:2
```
I have a question about that. In this example it can not resolve `webkit-gtk-2.34.0:4.1` because there is only version `2.38.0` for slot `:4.1`.
But that is what it requires in the meson.build. I guess this gets just resolved to the next newer version from slot `:4.1` anyway.
Should I change that in the ebuild to make pkgcheck happy?

**Pull request closed without merging**
