### PR TITLE
net-analyzer/linkchecker: bump to 10.1.0

### PR DESCRIPTION
**Pull request by hydrapolic**

### CODE REVIEW

**Comment by thesamesam** [comment]
Would be worth explaining in the commit message why/what it brings?

**Comment by hydrapolic** [comment]
> 

Nothing special here, just to keep up to date and have the latest linkchecker. Last release was almost a year ago, they don't really release/tag that often. The main branch has 114 commits since the last release.

**Comment by thesamesam** [comment]
lol, of course they just tagged a release too!

**Comment by hydrapolic** [comment]
> lol, of course they just tagged a release too!

I'll replace the snapshot with the new version, thanks for noticing.

**Comment by hydrapolic** [comment]
@thesamesam updated PR with the latest release.

**Comment by thesamesam** [comment]
Thanks!

**Comment by hydrapolic** [comment]
Thank you @thesamesam! :)

**Pull request closed without merging**
