### PR TITLE
dev-python/subunit: remove -Werror from configure.ac

### PR DESCRIPTION
**Pull request by crabbedhaloablution**
Closes: https://bugs.gentoo.org/744313
Package-Manager: Portage-3.0.12, Repoman-3.0.2
Signed-off-by: Peter Alfredsen <crabbedhaloablution@icloud.com>

### CODE REVIEW

**Review by floppym — CHANGES_REQUESTED** [review]
I would prefer this be done via a patch instead of sed.

**Review by prometheanfire — CHANGES_REQUESTED** [review]
I think I agree, a patch would be better (and could include the bug link in the patch header).

**Comment by crabbedhaloablution** [comment]
> I would prefer this be done via a patch instead of sed.
Updated.

**Review by prometheanfire — COMMENTED** [review]
Is it possible to use the `PATCHES=()` syntax here?  I feel like it should be.

**Comment by crabbedhaloablution** [comment]
> Is it possible to use the `PATCHES=()` syntax here? I feel like it should be.

Sure. Updated.

**Pull request closed without merging**
