### PR TITLE
app-text/sigil: version bump

### PR DESCRIPTION
**Pull request by tomboy-64**
[bug 566830](https://bugs.gentoo.org/show_bug.cgi?id=566830)

wfm.

### CODE REVIEW

**Comment by idella** [comment]
@gentoo/proxy-maint 

might be helpfull if you add this of your own accord

**Comment by idella** [comment]
This was held up over the commit msg lacking stating the vn. to which it was bumped; 0.9.0.
It appears the need to include the vn, is slightly contentious. It has been suggested as a normative format in past discussions re git conversions in past threads in the MLs.

**Comment by tomboy-64** [comment]
@idella frankly, i'm not bothered about it. I've been told vn isn't necessary; I've got no problem including it either.
Other suggestions?

**Comment by idella** [comment]
@tomboy-64  yes it's a triviality and we can live with it a committed as it was, but adding the vn. rounds it off better overall.
What I can say is that in my system here, adding @gentoo/proxy-maint

**Pull request merged**
