### PR TITLE
Splitting dev-libs/openssl-compat out of dev-libs/openssl

### PR DESCRIPTION
**Pull request by mgorny**
This splits the compatibility slots into a separate package to stop people from getting their dependencies wrong all the time. Also fixes a lot of wrong dependencies to prove the point.

### CODE REVIEW

**Comment by prototype99** [comment]
seems like a good idea, ultimately would it make the most sense to also add a virtual package?

**Comment by SoapGentoo** [comment]
@prototype99 the whole point is to avoid a virtual

**Comment by dhallas** [comment]
Nice :D

**Comment by haubi** [comment]
My first thought for what this new dev-libs/openssl-compat package could be about was:
Collect the compatibility code that applications need for adapting to new openssl API, so applications can use new openssl versions via the old API.
Now I realize that this is the libraries of the old openssl versions instead, my thought is:
What if we split out the libs even for current openssl version into dev-libs/openssl-libs, so dev-libs/openssl provides the executables only and depends on dev-libs/openssl-libs?
(would be a rename of this dev-libs/openssl-compat to dev-libs/openssl-libs)
After all, packages usually do depend on the openssl libraries, rarely the executables - at least not a specific version of the executables.

**Comment by mgorny** [comment]
> Now I realize that this is the libraries of the old openssl versions instead, my thought is:
> What if we split out the libs even for current openssl version into dev-libs/openssl-libs, so dev-libs/openssl provides the executables only and depends on dev-libs/openssl-libs?
> (would be a rename of this dev-libs/openssl-compat to dev-libs/openssl-libs)
> After all, packages usually do depend on the openssl libraries, rarely the executables - at least not a specific version of the executables.

This is tangential to the problem in question. The main point is not to have header+lib slots with lib-only slots in the same package.

**Comment by mgorny** [comment]
(rebased)

**Comment by haubi** [comment]
> The main point is not to have header+lib slots with lib-only slots in the same package.

Indeed, -compat does install the soname libs only, not the headers.
So I fail to grok the idea behind: How to link against the -compat libs?
Or is this about upgrading openssl with already installed (or binpkg) revdeps only?
But then, beyond the `RDEPEND="|| ( openssl-compat:1.0.0 =openssl-1.0* )"`, do we also need `DEPEND=" =openssl-1.0* "`?

**Comment by mgorny** [comment]
It's for prebuilt software only.

**Comment by haubi** [comment]
+1, even without the `DEPEND`: Indeed better break that one outdated package rather than showing an obscure openssl downgrade during world update, to increase chances to receive a patch for a package's openssl update.

**Pull request closed without merging**
