### PR TITLE
media-libs/openimageio: set correct source directory

### PR DESCRIPTION
**Pull request by negril**
Closes: https://bugs.gentoo.org/916320

### CODE REVIEW

**Review by AndrewAmmerlaan — COMMENTED** [review]
Are you sure this is required for all versions? Since the issue wasn't reported earlier I think only the latest version is affected.

**Comment by negril** [comment]
Yes, I tested all available versions. The repo moved on github and from that the source directory in the archive changed for all versions.

Hence why I suggested the renaming in https://github.com/gentoo/gentoo/pull/33306.

**Comment by AndrewAmmerlaan** [comment]
> Yes, I tested all available versions. The repo moved on github and from that the source directory in the archive changed for all versions.
> 
> Hence why I suggested the renaming in #33306.

Then we also need to update `SRC_URI` and regenerate the `Manifest`, or not touch the older versions at all. Otherwise we are going to break the older versions since the pre-move distfile is still in the cache.

**Comment by negril** [comment]
`SRC_URI` and `Manifest` are correct already see https://github.com/gentoo/gentoo/commits/master/media-libs/openimageio/Manifest.

**Comment by AndrewAmmerlaan** [comment]
> `SRC_URI` and `Manifest` are correct already see https://github.com/gentoo/gentoo/commits/master/media-libs/openimageio/Manifest.

I am confused, if the contents of the SRC_URI have changed, then the checksum must change, and thus the Manifest needs to be updated. What am I missing?

**Comment by thesamesam** [comment]
The distfiles didn't change, just the ebuild naming. It's from me undoing the rename.

**Comment by thesamesam** [comment]
Thank you!

**Comment by negril** [comment]
Andrew is partially right in that if you now re-manifest `-2.4.6.0` you get a different checksum. But since you normally pull this from the mirrors you get the old file. But this is a stable version so I didn't touch that.

**Comment by AndrewAmmerlaan** [comment]
> The distfiles didn't change, just the ebuild naming. It's from me undoing the rename.

That is part of it yes, but my confusion is about changing `S="${WORKDIR}/oiio-${PV}"` to `S="${WORKDIR}/OpenImageIO-${PV}"`, this must change the checksum right?

**Comment by thesamesam** [comment]
No, because the ebuilds were fine in the commit which added them. I just dropped the `S=` line inadvertently.

**Comment by AndrewAmmerlaan** [comment]
> No, because the ebuilds were fine in the commit which added them. I just dropped the `S=` line inadvertently (while dropping the renaming). I tested some but not all apparently.

aah, I see, now it makes sense. Thanks.

**Comment by thesamesam** [comment]
(I'm glad you asked these things, I just knew exactly what I'd done wrong when I saw the bug)

**Pull request closed without merging**
