### PR TITLE
dev-libs/rocm-opencl-runtime: ROCm-OpenCL-Runtime 3.5.0 version bump

### PR DESCRIPTION
**Pull request by justxi**
Signed-off-by: Wilfried Holzke <gentoo@holzke.net>
Package-Manager: Portage-2.3.99, Repoman-2.3.22

### CODE REVIEW

**Comment by candrews** [comment]
I think you forgot to add the dependency on `>=dev-libs/rocm-comgr-${PV}` :)

Even with that though, the build fails: [build.log](https://github.com/gentoo/gentoo/files/4748383/build.log)

**Comment by candrews** [comment]
It's an `-fno-common` bug... compiling with `CFLAGS="-fcommon"` succeeds. See https://bugs.gentoo.org/705764 and https://wiki.gentoo.org/wiki/Gcc_10_porting_notes/fno_common

**Comment by justxi** [comment]
In my ebuild https://github.com/justxi/gentoo/blob/b1bf28b4c3489e92743a4207ba065c186c1b0270/dev-libs/rocm-opencl-runtime/rocm-opencl-runtime-3.5.0.ebuild#L24 ">=dev-libs/rocm-comgr-${PV}" is there.

I tested only with "gcc-9.3.0" therefore I did not hit the "-fno-common" bug.
I will add the flag.

**Comment by justxi** [comment]
Works now on my system with gcc 9.3.0 and 10.1.0.

**Pull request closed without merging**
