### PR TITLE
dev-qt/qtwebengine: := dep on app-arch/snappy

### PR DESCRIPTION
**Pull request by l29ah**
libsnappy.so.1.1.5: cannot open shared object file: No such file or directory

### CODE REVIEW

**Comment by Pesa** [comment]
ACK for qtwebengine

**Comment by l29ah** [comment]
I don't get what's wrong with the leveldb subslot dep.

**Comment by Arfrever** [comment]
Subslots and `:=` operator in `*DEPEND` are supported since EAPI `5`. Majority of ebuilds of `dev-libs/leveldb` use EAPI `4`.

**Comment by l29ah** [comment]
okay

**Pull request closed without merging**
