### PR TITLE
sci-electronics/gtkwave: Bump to 3.3.111. Add gtk3 option.

### PR DESCRIPTION
**Pull request by jvesely**
Use gtk3-fied source archive (gtkwave-gtk3).
Add gtk3 useflag to select between gtk2 and gtk3.
Drop no longer supported configure options (and fatlines useflag).

Closes: https://bugs.gentoo.org/856829
Bug: https://bugs.gentoo.org/856829
Signed-off-by: Jan Vesely <jano.vesely@gmail.com>

### CODE REVIEW

**Comment by jvesely** [comment]
@SoapGentoo, you were the last to commit to sci-electronics/gtkwave. Any concerns about this PR? thank you.

**Comment by SoapGentoo** [comment]
@jvesely in fact, why even keep the Gtk2 option?

**Comment by jvesely** [comment]
> @jvesely in fact, why even keep the Gtk2 option?

I can drop it, didn't really check how many gtk2 packages there are or whether ppl would prefer gtk2 over gtk3.

**Comment by jvesely** [comment]
@SoapGentoo, does the modified version look ok to you?

**Comment by jvesely** [comment]
gentle ping

**Comment by AndrewAmmerlaan** [comment]
Very nice, Thanks :+1:

**Pull request closed without merging**
