### PR TITLE
app-text/calibre: add 7.3.0

### PR DESCRIPTION
**Pull request by eli-schwartz**

### CODE REVIEW

**Comment by zmedico** [comment]
Hi, did the test phase pass for you? I got this error. My environment is a little weird though because I was mid-world update when I decided to upgrade my PyQt6 packages using one of the [new gentoo binhosts](https://gentoo.osuosl.org/releases/amd64/binpackages/17.1/x86-64).
```
FAIL: test_safe_xml_fromstring (calibre.utils.xml_parse.find_tests.<locals>.TestXMLParse.test_safe_xml_fromstring)
----------------------------------------------------------------------
Traceback (most recent call last):e
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/utils/xml_parse.py", line 71, in test_safe_xml_fromstring
    t('SYSTEM', external, 'external', safe=False)
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/utils/xml_parse.py", line 69, in t
    self.assertEqual(got, expected, f'Unexpected result parsing: {raw!r}, got: {got!r} expected: {expected!r} with XML parser error: {err}')
AssertionError: <object object at 0x7f3a2712af40> != 'external' : Unexpected result parsing: '<!DOCTYPE foo [ <!ENTITY e SYSTEM "file:////var/tmp/portage/app-text/calibre-7.3.0/temp/tmpyfwpg32d" > ]><r>&e;</r>', got: <object object at 0x7f3a2712af40> expected: 'external' with XML parser error: Entity 'e' not defined, line 1, column 112 (<string>, line 1)
```

**Comment by zmedico** [comment]
> Hi, did the test phase pass for you? I got this error. My environment is a little weird though because I was mid-world update when I decided to upgrade my PyQt6 packages using one of the [new gentoo binhosts](https://gentoo.osuosl.org/releases/amd64/binpackages/17.1/x86-64).

My world update is still in progress. I ran the test phase a couple of more times and got some more failures that do not happen every time, but the test_safe_xml_fromstring has happened every time so far.
```
======================================================================
ERROR: test_fts_pool (calibre.db.tests.fts_api.FTSAPITest.test_fts_pool)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/tests/fts_api.py", line 90, in test_fts_pool
    check(id=1, book=1, format='TXT', searchable_text='a test text')
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/tests/fts_api.py", line 86, in check
    tr = self.text_records(fts)
         ^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/tests/fts_api.py", line 63, in text_records
    return fts.get_connection().get_dict('SELECT * FROM fts_db.books_text')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/backend.py", line 384, in get_dict
    desc = ans.getdescription()
           ^^^^^^^^^^^^^^^^^^^^
apsw.ExecutionCompleteError: Can't get description for statements that have completed execution

======================================================================
ERROR: test_export_import (calibre.db.tests.filesystem.FilesystemTest.test_export_import)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/tests/filesystem.py", line 283, in test_export_import
    raise ValueError('FTS indexing did not complete')
ValueError: FTS indexing did not complete

======================================================================
FAIL: test_safe_xml_fromstring (calibre.utils.xml_parse.find_tests.<locals>.TestXMLParse.test_safe_xml_fromstring)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/utils/xml_parse.py", line 71, in test_safe_xml_fromstring
    t('SYSTEM', external, 'external', safe=False)
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/utils/xml_parse.py", line 69, in t
    self.assertEqual(got, expected, f'Unexpected result parsing: {raw!r}, got: {got!r} expected: {expected!r} with XML parser error: {err}')
AssertionError: <object object at 0x7fbc2880ae50> != 'external' : Unexpected result parsing: '<!DOCTYPE foo [ <!ENTITY e SYSTEM "file:////var/tmp/portage/app-text/calibre-7.3.0/temp/tmprqt2ebjs" > ]><r>&e;</r>', got: <object object at 0x7fbc2880ae50> expected: 'external' with XML parser error: Entity 'e' not defined, line 1, column 112 (<string>, line 1)

======================================================================
FAIL: test_fts_search (calibre.db.tests.fts_api.FTSAPITest.test_fts_search)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/app-text/calibre-7.3.0/work/calibre-7.3.0/src/calibre/db/tests/fts_api.py", line 142, in test_fts_search
    self.assertFalse(fts.all_currently_dirty())
AssertionError: [(1, 'TXT'), (2, 'MD')] is not false

----------------------------------------------------------------------
Ran 329 tests in 161.539s

FAILED (failures=2, errors=2, skipped=10)
```

**Comment by eli-schwartz** [comment]
The test phase did indeed pass for me.

```
Ran 329 tests in 85.166s

OK (skipped=10)
>>> Completed testing app-text/calibre-7.3.0
```

**Comment by eli-schwartz** [comment]
> self.assertEqual(got, expected, f'Unexpected result parsing: {raw!r}, got: {got!r} expected: {expected!r} with XML parser error: {err}')
> AssertionError: <object object at 0x7f3a2712af40> != 'external' : Unexpected result parsing: '<!DOCTYPE foo [ <!ENTITY e SYSTEM "file:////var/tmp/portage/app-text/calibre-7.3.0/temp/tmpyfwpg32d" > ]><r>&e;</r>', got: <object object at 0x7f3a2712af40> expected: 'external' with XML parser error: Entity 'e' not defined, line 1, column 112 (<string>, line 1)

The result of a relatively simple bit of lxml.etree parsing resulted in a parser error for an undefined entity instead of reading the text "external" from a temp file.

**Comment by zmedico** [comment]
Thanks!

All tests passed for me after I upgraded to dev-deb/sqlite-3.44.2-r2 for bug 921490, and downgraded from dev-python/lxml-5.0.0 to dev-python/lxml-4.9.4 for the

**Comment by eli-schwartz** [comment]
Good call on the lxml issue being an upgrade to 5.0 -- I forwarded this upstream as https://bugs.launchpad.net/calibre/+bug/2048475

(The issue is that lxml has changed the defaults for security purposes.)

**Pull request closed without merging**
