### PR TITLE
app-text/pandoc: bump to 2.11.4

### PR DESCRIPTION
**Pull request by ezzieyguywuf**
- dev-haskell/citeproc: bump to 0.3.0.6, needed for pandoc update
- dev-haskell/commonmark: bump to 0.1.1.4, needed for newer pandoc
- dev-haskell/texmath: bump to 0.12.1.1, needed for newer pandoc
- app-text/pandoc: bump to 2.11.4, dep of rstudio update

NOTE: I will keep this in `DRAFT` form until I can verify that these newer
versions don't conflict with any other haskell packages in `::gentoo`

TODO
=====
- ~~update hakyll-4.13.4.1 ebuild to support newer pandoc~~ not needed, already allows `pandoc-2.11.4`, which is what we're trying to add
- [ ] remove old hakyll-4.13.4.0
- ~~update pandoc-citeproc-0.17.0.2 and revdeps to support newer pandoc~~
    - [x] open PR to last-rite pandoc-citproc
        - see #19893 
- [x] run test-suite for all new versions/packages
    - [x] dev-haskell/citeproc
    - [x] dev-haskell/commonmark
    - [x] dev-haskell/texmath
    - [x] app-text/pandoc
    - [x] dev-games/goatee
    - [x] games-board/goatee-gtk

### CODE REVIEW

**Comment by ezzieyguywuf** [comment]
@trofi ping, do you mind taking a look at this?

**Comment by trofi** [comment]
The pull request is still marked as draft. Is it ready? How did you test it?

**Comment by ezzieyguywuf** [comment]
> The pull request is still marked as draft. Is it ready? How did you test it?

I marked it as draft because I'd like some advice on how best to test.

I can compile a d run the test suite, but what can I do to ensure that other haskell packaged aren't negatively affected?

**Comment by trofi** [comment]
I suggest building all the reverse dependencies of touched packages. I personally keep a separate chroot for ::gentoo which I try to update occasionally.

**Comment by ezzieyguywuf** [comment]
> I suggest building all the reverse dependencies of touched packages. I personally keep a separate chroot for ::gentoo which I try to update occasionally.

Thanks for the tip. Per our conversation on IRC, I am doing the following:

```sh
# generate a list of all packages in ::gentoo maintained by the haskell team
ACCEPT_KEYWORDS='**' portageq --no-regex --no-version --maintainer-email="haskell@gentoo.org" --repo=gentoo > target_packages.txt

# emerge all these packages
emerge -ve1 --ignore-built-slot-operator-deps=y --usepkg=n $(cat target_packages.txt)
```

I'm working through some slot conflicts, but I'll post the final result once it is ready.

**Comment by ezzieyguywuf** [comment]
The following packages failed to build. I will do an investigation on each and provide my results here:

- [ ] dev-texlive/texlive-mathscience-2020
- [ ] dev-texlive/latexextra-2020-r2
- [ ] dev-haskell/lhs2tex-1.24
- [ ] dev-games/goatee-0.3.1.2
- [ ] games-board/goatee-gtk-0.3.1.1
- [ ] dev-haskell/geniplate-0.6.0.5
- [ ] dev-haskell/gtk-0.14.10-r3

**Pull request closed without merging**
