### PR TITLE
update media-sound/ario to the version 1.6

### PR DESCRIPTION
**Pull request by agicquel**
Link of the bug : https://bugs.gentoo.org/show_bug.cgi?id=679514

I have updated ario player to the version 1.6. Ario uses GTK3 so the patch is no longer needed. I have alors removed the obscure python plugin binding.

### CODE REVIEW

**Comment by juippis** [comment]
Your commit summary isn't following the guidelines in GLEP-66. You should fix it. You can also then include `Closes: ` and that bug number to automatically close the bug once this gets merged. You also need to read and accept the terms in GLEP-76, and then add a sign-off if you do. Link is above, certificate of origin. 

You should commit with repoman to get a body for correct git summary, and it can also add the sign-off for you automatically.

**Comment by a17r** [comment]
In addition to @juippis comment: Please describe your changes in the git summary (EAPI-7 bump, why was USE python dropped).

**Comment by agicquel** [comment]
Thank you @juippis ans @a17r for your indications. I'm very to new to gentoo devel. I will fix my commit today ;-)

**Comment by a17r** [comment]
Right now unfortunately this PR is unusable (see number of line changes)
- I would recommend to work on branches separate off master, but you can still work this way for now.
- NEVER `merge` into our branch (or master, like you did)
- Instead, use `git pull --rebase upstream master` (assuming `upstream` is your remote name for gentoo.git)

**Comment by agicquel** [comment]
I am very sorry I should have made a branch. I am not familiar with PR and I wasn't expecting this behaviour. I am on it !

**Pull request closed without merging**
