### PR TITLE
gnome-extra/gnome-calculator: Version bump to 45.alpha

### PR DESCRIPTION
**Pull request by flint2**
Signed-off-by: Guillermo Joandet <gjoandet@gmail.com>

### CODE REVIEW

**Comment by mattst88** [comment]
Do the tests fails for you?

```
dbus-daemon[43]: [session uid=250 pid=43] Activated service 'org.freedesktop.impl.portal.desktop.gnome' failed: Process org.freedesktop.impl.portal.desktop.gnome exited with status 1
dbus-daemon[43]: [session uid=250 pid=43] Activating service name='org.freedesktop.impl.portal.desktop.gnome' requested by ':1.3' (uid=250 pid=94 comm="/usr/libexec/xdg-desktop-portal")
error: Failed to initialize display server connection: Unsupported or missing session type ''
```

**Comment by mattst88** [comment]
Looks like setting `XDG_SESSION_TYPE=x11` in `src_test` resolves the issue.

**Comment by mattst88** [comment]
I suggest

```diff
diff --git a/gnome-extra/gnome-calculator/gnome-calculator-45_alpha.ebuild b/gnome-extra/gnome-calculator/gnome-calculator-45_alpha.ebuild
index d4600d805668..d2baf4a89433 100644
--- a/gnome-extra/gnome-calculator/gnome-calculator-45_alpha.ebuild
+++ b/gnome-extra/gnome-calculator/gnome-calculator-45_alpha.ebuild
@@ -42,6 +42,7 @@ BDEPEND="
 src_prepare() {
 	default
 	vala_setup
+	xdg_environment_reset
 }
 
 src_configure() {
@@ -59,7 +60,7 @@ src_configure() {
 }
 
 src_test() {
-	virtx dbus-run-session meson test -C "${BUILD_DIR}" || die 'tests failed'
+	XDG_SESSION_TYPE=x11 virtx dbus-run-session meson test -C "${BUILD_DIR}" || die 'tests failed'
 }
 
 pkg_postinst() {
```

**Comment by flint2** [comment]
> ```diff
> XDG_SESSION_TYPE=x11 
> ```

Now failing with 
==================================== 7/7 =====================================
test:         gci-entry-controller
start time:   21:24:02
duration:     0.33s
result:       killed by signal 5 SIGTRAP
command:      MALLOC_PERTURB_=187 LD_LIBRARY_PATH=/var/tmp/portage/gnome-extra/gnome-calculator-45_alpha/work/gnome-calculator-45_alpha-build/gcalc:/var/tmp/portage/gnome-extra/gnome-calculator-45_alpha/work/gnome-calculator-45_alpha-build/gci /var/tmp/portage/gnome-extra/gnome-calculator-45_alpha/work/gnome-calculator-45_alpha-build/tests/test-entry-controller
----------------------------------- stdout -----------------------------------
TAP version 13
# random seed: R02S806340d60662ee86256595824a0fe963
1..1
# Start of gci tests
# Start of entry tests
# GLib-GIO-DEBUG: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
# GLib-GIO-DEBUG: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
----------------------------------- stderr -----------------------------------

(/var/tmp/portage/gnome-extra/gnome-calculator-45_alpha/work/gnome-calculator-45_alpha-build/tests/test-entry-controller:61): Gdk-WARNING **: 18:24:02.809: The program '/var/tmp/portage/gnome-extra/gnome-calculator-45_alpha/work/gnome-calculator-45_alpha-build/tests/test-entry-controller' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadFBConfig'.
  (Details: serial 220 error_code 165 request_code 149 (GLX) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
==============================================================================


Summary of Failures:

7/7 gci-entry-controller FAIL            0.33s   killed by signal 5 SIGTRAP

Ok:                 6   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0

**Comment by flint2** [comment]
Still failing 1 test

>>> Test phase: gnome-extra/gnome-characters-45_alpha
 * Starting Xvfb ...
 * Xvfb started on DISPLAY=:2
dbus-daemon[43]: Cannot setup inotify for '/root/.local/share/flatpak/exports/share/dbus-1/services'; error 'Permission denied'
ninja: no work to do.
ninja: Entering directory `/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
ninja: no work to do.
dbus-daemon[43]: [session uid=250 pid=43] Activating service name='org.gtk.vfs.Daemon' requested by ':1.0' (uid=250 pid=77 comm="/usr/bin/appstream-util validate-relax --nonet dat")
dbus-daemon[43]: [session uid=250 pid=43] Successfully activated service 'org.gtk.vfs.Daemon'
1/2 validate-appdata        OK              0.06s
2/2 Util                    FAIL            0.13s   exit status 1
>>> GSETTINGS_BACKEND=memory GI_TYPELIB_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/lib GSETTINGS_SCHEMA_DIR=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/data LD_LIBRARY_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/lib MALLOC_PERTURB_=10 GJS_PATH=/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha/src:/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/src /usr/bin/xvfb-run -a /usr/bin/gjs-console /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/../gnome-characters-45.alpha/tests/testUtil.js


Ok:                 1   
Expected Fail:      0   
Fail:               1   
Unexpected Pass:    0   
Skipped:            0   
Timeout:            0   

Full log written to /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build/meson-logs/testlog.txt
A connection to the bus can't be made
 * ERROR: gnome-extra/gnome-characters-45_alpha::gentoo failed (test phase):
 *   Failed to run 'dbus-run-session meson test -C /var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
 * 
 * Call stack:
 *     ebuild.sh, line  136:  Called src_test
 *   environment, line 2489:  Called virtx 'dbus-run-session' 'meson' 'test' '-C' '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45_alpha-build'
 *   environment, line 3281:  Called die
 * The specific snippet of code:
 *       [[ ${retval} -ne 0 ]] && die "Failed to run '$@'";
 * 
 * If you need support, post the output of `emerge --info '=gnome-extra/gnome-characters-45_alpha::gentoo'`,
 * the complete build log and the output of `emerge -pqv '=gnome-extra/gnome-characters-45_alpha::gentoo'`.
 * The complete build log is located at '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/temp/environment'.
 * Working directory: '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha'
 * S: '/var/tmp/portage/gnome-extra/gnome-characters-45_alpha/work/gnome-characters-45.alpha'

**Comment by mattst88** [comment]
Please edit the last comment and wrap the log with triple "`" to fix the formatting.

**Comment by mattst88** [comment]
Looks like the PR passes tests for me now.

**Pull request closed without merging**
