### PR TITLE
media-radio/gpredict: Version bump to 2.2

### PR DESCRIPTION
**Pull request by cjmayo**
Install upstream desktop file only.

Package-Manager: Portage-2.3.14, Repoman-2.3.6

---

- Tarball is now a bz2
- Tidy up ebuild

```
--- gpredict-2.0.ebuild
+++ gpredict-2.2.ebuild
@@ -1,13 +1,11 @@
-# Copyright 1999-2017 Gentoo Foundation
+# Copyright 1999-2018 Gentoo Foundation
 # Distributed under the terms of the GNU General Public License v2
 
 EAPI=6
 
-inherit eutils
-
 DESCRIPTION="Real-time satellite tracking and orbit prediction application"
 HOMEPAGE="http://gpredict.oz9aec.net"
-SRC_URI="mirror://sourceforge/${PN}/${P}.tar.gz"
+SRC_URI="mirror://sourceforge/${PN}/${P}.tar.bz2"
 
 LICENSE="GPL-2"
 SLOT="0"
@@ -26,14 +24,4 @@
 
 DOCS=( AUTHORS ChangeLog NEWS README )
 
-src_prepare() {
-	eapply_user
-	# remove wrong doc location
-	epatch "${FILESDIR}/${PN}-2.0-doc.patch"
-}
-
-src_install() {
-	emake DESTDIR="${D}" install
-	einstalldocs
-	make_desktop_entry ${PN} "GPredict" "/usr/share/pixmaps/gpredict/icons/gpredict-icon.png" Science
-}
+PATCHES=( "${FILESDIR}/${PN}-2.2-doc.patch" )
```

### CODE REVIEW

**Comment by dl1jbe** [comment]
gpredict-2.2-doc.patch looks quite the same as the 2.0 one.
If possible please drop the additional patch file and use the old one.

**Comment by cjmayo** [comment]
OK. Updated to use the 2.0 patch.

**Comment by dl1jbe** [comment]
Thanks.
Just one additional question:
What happened to the make_desktop_entry during the install phase?

**Comment by cjmayo** [comment]
gpredict is installing its own desktop file from `data/desktop/gpredict.desktop` which is working fine for me on GNOME 3.

With the make_desktop_entry I end up with two icons.

**Comment by dl1jbe** [comment]
Ok, thanks. Just found it out myself.

**Comment by dl1jbe** [comment]
Applied and pushed. Thanks.

**Pull request closed without merging**
