### PR TITLE
net-im/slack: add 4.27.156, and drop old

### PR DESCRIPTION
**Pull request by peeweep**

### CODE REVIEW

**Comment by Kangie** [comment]
LGTM, I was about to submit the same PR!

**Comment by Kangie** [comment]
Actually, you've dropped the one that was on EAPI 8 and revbumped the one on EAPI 7. Please fix.

**Comment by peeweep** [comment]
Now 4.27.156 is on EAPI 8, thanks.

**Review by juippis — APPROVED** [review]

**Comment by juippis** [comment]
Sorry for taking this long, I took the PR with other bug fixes included.

**Pull request closed without merging**
