### PR TITLE
media-gfx/gimp: -9999, make python plug-ins mandatory (rm USE=python)

### PR DESCRIPTION
**Pull request by band-a-prend**
Closes: https://bugs.gentoo.org/937801

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by jospezial** [comment]
Reading the answers in https://gitlab.gnome.org/GNOME/gimp/-/issues/11935 I think we should depend on babl gegl 9999 and put some info into the ebuild about rebuilding them before gimp. Would be cool if we could force that deps rebuild in an ebuild but I am not aware of such eclass function.
On a world update with --changed-deps or  --newuse babl and gegl would not be rebuilt if only gimp has changes. That would only work with finer slots but that is not economical.
I use the live ebuilds and normally do emerge live-rebuild occasionally.

**Comment by band-a-prend** [comment]
Yes, I'm thinking about making gimp-9999 always depend on babl-9999 and gegl-9999 or alternatively set its versions always greater its release versions. Anyway it will require rebuild the 9999 versions of babl and gegl on gimp rebuild. I will set it to -9999 for both.

Actually I noticed early that gegl version increments on next commit after release but this changes isn't tracked in gimp repository at the time. But certain dev version could contain brackage changes too within it.

**Comment by thesamesam** [comment]
> I use the live ebuilds and normally do emerge live-rebuild occasionally.

I would really suggest using `smart-live-rebuild`. Breakage will happen occasionally and it's mostly unavoidable.

**Comment by band-a-prend** [comment]
I updated the pull request. The `>=` are used for `babl-9999` and `gegl-9999` to allow use the local revisions for this live ebuilds.

**Review by juippis — COMMENTED** [review]
```
cp: cannot stat '/var/tmp/portage/media-gfx/gimp-9999/work/gimp-9999-build/gimp-data/icons/Default/16/gimp-logo-shadow.png': No such file or directory
FAILED: install script '/usr/bin/sh -c mkdir -p "$MESON_INSTALL_DESTDIR_PREFIX/share/gimp/3.0/icons/Default/16x16/apps" && cp -f "/var/tmp/portage/media-gfx/gimp-9999/work/gimp-9999-build/gimp-data/icons/Default/16/gimp-logo-shadow.png" "$MESON_INSTALL_DESTDIR_PREFIX/share/gimp/3.0/icons/Default/16x16/apps/gimp-wilber.png"' failed with exit code 1.
 * ERROR: media-gfx/gimp-9999::gentoo failed (install phase):
 *   install failed
```

**Comment by band-a-prend** [comment]
Looks like https://bugs.gentoo.org/933533 and https://gitlab.gnome.org/GNOME/gimp-data/-/issues/3

It's still strange why it presences not for all systems. Maybe it race condition.

**Comment by juippis** [comment]
Good to know!

**Pull request closed without merging**
