### PR TITLE
dev-util/pycharm-professional: revision bump

### PR DESCRIPTION
**Pull request by switch87**
dev-util/pycharm-professional: dependency's, licenses and keywords

* added pip dependency
* changed and added the licenses
* added ~x86 keyword

Signed-off-by: Gert Pellin <gert@gepe-biljarts.be>

### CODE REVIEW

**Comment by monsieurp** [comment]
s#dev/utilS#dev/util ;)

**Comment by switch87** [comment]
:+1:  resolved that, its hard typing without tab completion :blush:

**Comment by hasufell** [comment]
if you fix non-trivial runtime dependencies, you have to do a revision bump

**Comment by mgorny** [comment]
@xmw

**Comment by monsieurp** [comment]
Merged :+1:

**Comment by switch87** [comment]
ok thanks

**Pull request closed without merging**
