### PR TITLE
net-vpn/i2pd version bump 2.38.0

### PR DESCRIPTION
**Pull request by khumarahn**
zero changes to the ebuild

### CODE REVIEW

**Comment by khumarahn** [comment]
I changed the systemd service file. That is cosmetics, replacement of the deprecated `PermissionsStartOnly` and also addition of
```
PrivateTmp=yes
ProtectSystem=yes
ProtectHome=yes
```

**Comment by khumarahn** [comment]
I extended restrictions to
```
# restrictions                                                                                            
ProtectSystem=full                                                                                        
ProtectHome=yes                                                                                           
ProtectControlGroups=yes                                                                                  
ProtectKernelLogs=yes                                                                                     
ProtectKernelModules=yes                                                                                  
ProtectKernelTunables=yes                                                                                 
ProtectClock=yes                                                                                          
PrivateUsers=yes                                                                                          
PrivateDevices=yes                                                                                        
PrivateTmp=yes                                                                                            
RestrictNamespaces=yes                                                                                    
RestrictSUIDSGID=yes                                                                                      
CapabilityBoundingSet=                                                                                    
NoNewPrivileges=yes  
```
This makes systemd-analyse almost happy
```
i2pd.service                              3.6 OK        🙂
```

**Comment by thesamesam** [comment]
Looks good, thanks!

**Comment by khumarahn** [comment]
@thesamesam many thanks! I wonder if you could maybe take a look at my other PR https://github.com/gentoo/gentoo/pull/20946
It is equally trivial but bumps a great package which has not been updated for long time.

**Pull request closed without merging**
