### PR TITLE
dev-lang/zig{,-bin}: add verify-sig support, fix build without LLVM on 9999

### PR DESCRIPTION
**Pull request by BratishkaErik**

### CODE REVIEW

**Comment by BratishkaErik** [comment]
I don't understand why my email is still crossed out by bot

**Comment by BratishkaErik** [comment]
Ping, I'd like to bump Zig to 0.12 based on this.

**Comment by LinuxUserGD** [comment]
> I don't understand why my email is still crossed out by bot

Maybe the missing `[please reassign]` to fix the bugzilla mapping in https://github.com/gentoo/gentoo/pull/35923?

**Comment by BratishkaErik** [comment]
> > I don't understand why my email is still crossed out by bot
> 
> Maybe the missing `[please reassign]` to fix the bugzilla mapping in https://github.com/gentoo/gentoo/pull/35923?

Hmm, but we have another PR after that moment (https://github.com/gentoo/gentoo/pull/36517), and email is crossed out there too

**Comment by BratishkaErik** [comment]
Nice, thanks!

**Comment by juippis** [comment]
@BratishkaErik I've updated your e-mail - it should be synced (and work) after ~48 hours.

**Comment by BratishkaErik** [comment]
> @BratishkaErik I've updated your e-mail - it should be synced (and work) after ~48 hours.

Hope it will work, thanks!

**Pull request closed without merging**
