### PR TITLE
dev-games/tiled: Version bump to 1.2.2

### PR DESCRIPTION
**Pull request by nicolasbock**
Package-Manager: Portage-2.3.51, Repoman-2.3.11
Signed-off-by: Nicolas Bock <nicolasbock@gentoo.org>

### CODE REVIEW

**Comment by nicolasbock** [comment]
@kensington ping?

**Comment by kensington** [comment]
On 12 February 2019 5:46:39 am AEDT, Nicolas Bock <notifications@github.com> wrote:
>@kensington ping?

I'm away right now, feel free to merge if it works for you.
-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by nicolasbock** [comment]
Thanks!

**Comment by kensington** [comment]
This was landed in 91e59573b69b7454834ca31d43c9b9884ffcbdf2.

**Pull request closed without merging**
