### PR TITLE
dev-java/jdom cleanup, part 1...

### PR DESCRIPTION
**Pull request by wltjr**
Updated dev-java/jdom slot from 1.0 -> 0 for v1. Removed old versions for a few packages in same slot.

### CODE REVIEW

**Comment by wltjr** [comment]
That should address the QA issues for Saxon, forgot to mention in the already lengthy commit message.

**Comment by chewi** [comment]
Wow, okay! I'll take a closer look at the weekend.

**Comment by hasufell** [comment]
I don't even know how to tag this :d

**Comment by wltjr** [comment]
This is just the beginning and minor compared to what will be coming next... Just testing out the waters before I dive in head first... :)

**Comment by mgorny** [comment]
I suggest squashing this a bit before merging.

**Comment by mgorny** [comment]
I see the right people have gotten it already but for the formality: @gentoo/java

**Comment by chewi** [comment]
Merged after some squashing and a couple of fixes.

**Pull request closed without merging**
