### PR TITLE
Clean up some GNOME packages after the eclass updates

### PR DESCRIPTION
**Pull request by dm0-**
@mattst88 Let me know which of these should get a new revision.  They all seem to produce the same binpkgs.

### CODE REVIEW

**Comment by leio** [comment]
I don't think librsvg-2.40 should get an EAPI bump, as it is security vulnerable and just promotes cross-compiling people to expose themselves to security issues more.

**Comment by dm0-** [comment]
@leio But librsvg-2.40 is the only version available for three CPUs I'm targeting: armv5, i686 with no SSE, and sh4.  Rust versions of librsvg are unkeyworded and/or masked in the arch profiles where there is no `dev-lang/rust-bin`.  Anyone with such CPUs is prevented from using the updated versions.

**Comment by mattst88** [comment]
> I don't think librsvg-2.40 should get an EAPI bump, as it is security vulnerable and just promotes cross-compiling people to expose themselves to security issues more.

I don't think this hurts anything. If its so vulnerable, we should just remove it from the tree, right? Otherwise, allowing easier cross-compilation to architectures without rust support seems fine...

**Comment by leio** [comment]
> @leio But librsvg-2.40 is the only version available for three CPUs I'm targeting: armv5, i686 with no SSE, and sh4. Rust versions of librsvg are unkeyworded and/or masked in the arch profiles where there is no `dev-lang/rust-bin`. Anyone with such CPUs is prevented from using the updated versions.

I'm sold with these arguments; unsure about revbump or not.

rust without SSE is possible to my knowledge, but not in Gentoo without lots of hoops.

**Pull request closed without merging**
