### PR TITLE
app-backup/spideroak-bin: mark 6.4.0 bug #633594

### PR DESCRIPTION
**Pull request by jfernandezalcon**
app-backup/spideroak-bin: mark 6.4.0 bug #633594

### CODE REVIEW

**Comment by jfernandezalcon** [comment]
Bug: https://bugs.gentoo.org/633594

**Comment by jfernandezalcon** [comment]
Bug: https://bugs.gentoo.org/633594

**Comment by jfernandezalcon** [comment]
Bug: https://bugs.gentoo.org/633594

**Comment by jfernandezalcon** [comment]
Bug: https://bugs.gentoo.org/633594

**Comment by jfernandezalcon** [comment]
Bug: https://bugs.gentoo.org/633594

**Comment by blueness** [comment]
Somethings messed up with this pull request.  You're adding 6.1.5 and the manifest is off.  Can you rebase your branch and try again.

**Comment by blueness** [comment]
okay i cleaned this up and pushed.

**Pull request closed without merging**
