### PR TITLE
games-puzzle/numptyphysics: fix patch

### PR DESCRIPTION
**Pull request by SobhanMP**

### CODE REVIEW

**Comment by SobhanMP** [comment]
no one?

**Comment by chewi** [comment]
Be patient. I've been without my desktop for 2 weeks.

**Comment by SobhanMP** [comment]
ok thanks

**Comment by monsieurp** [comment]
@chewi: I think this can be merged.

**Comment by chewi** [comment]
Helps if you don't delete the repository before we've had a change to merge. Merged it anyway.

**Pull request closed without merging**
