### PR TITLE
kde-plasma/breeze-gtk: Allow using C based sassc rather than ruby sass

### PR DESCRIPTION
**Pull request by FireBurn**
Signed-of-by: Mike Lothian <mike@fireburn.co.uk>

### CODE REVIEW

**Comment by graaff** [comment]
+1 from me as ruby maintainer, since it is not clear to what extend dev-ruby/sass will be maintained by the sass maintainers in the future.

**Comment by a17r** [comment]
we may as well replace dev-ruby/sass with dev-lang/sassc completely then. I'm not particularly happy about pulling in ruby there anyway.

**Comment by FireBurn** [comment]
I've bumped and replaced the dependency rather than allowing both

**Comment by a17r** [comment]
Thanks for your work! It had to be rebased again so I committed myself.

**Comment by FireBurn** [comment]
🤦🏻‍♂️

There commit shouldn't have needed rebasing

You've commited the change without a rev-bump

Can you fix this ASAP

**Comment by a17r** [comment]
Revbump is absolutely unnecessary.

**Comment by FireBurn** [comment]
https://wiki.gentoo.org/wiki/Project:Portage/Changed_Deps

**Comment by a17r** [comment]
Completely irrelevant for buildtime-only change.

**Pull request closed without merging**
