### PR TITLE
net-misc/dahdi: version bump to fix compiler problems.

### PR DESCRIPTION
**Pull request by jkroonza**
1.  clang/LLVM
2.  Kernel header changes (5.9 onwards)

Three additional patches added to the patch set (two of which from
dahdi-linux/next, and one just submitted):

09-dahdi-3.1.0-r3-remove-32bit-userspace-on-64bit-support.patch
10-dahdi-3.1.0-r3-ioctl-kernel-5.9.patch
11-dahdi-3.1.0-r3-clang.patch

09 is a dependency for 10, which is required since kernel version 5.9.
   The former seems to affect 32-bit userspace on 64-bit kernels only,
   and according to upstream there are no tests for this.

10 fixes the compile issues for kernels 5.9 onwards (which dropped ioctl
   from proc_ops structures.

11 imports clang fixes as per https://issues.asterisk.org/jira/browse/DAHLIN-385

Signed-off-by: Jaco Kroon <jaco@uls.co.za>
Closes: https://bugs.gentoo.org/748240
Closes: https://bugs.gentoo.org/740818

### CODE REVIEW

**Review by juippis — COMMENTED** [review]
It may be my system, it may be something else:
```
make -f ./scripts/Makefile.modpost
  sed 's/ko$/o/' /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/modules.order | scripts/mod/modpost -m -a   -o /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/Module.symvers -e -i Module.symvers   -T -
/var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/vpmadt032_loader/.vpmadt032_x86_64.o.cmd: No such file or directory
make[2]: *** [scripts/Makefile.modpost:111: /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/Module.symvers] Error 1
make[1]: *** [Makefile:1712: modules] Error 2
make[1]: Leaving directory '/usr/src/linux'
make: *** [Makefile:74: modules] Error 2
 * ERROR: net-misc/dahdi-3.1.0-r3::testworld failed (compile phase):
 *   emake failed
 * 
 * If you need support, post the output of `emerge --info '=net-misc/dahdi-3.1.0-r3::testworld'`,
 * the complete build log and the output of `emerge -pqv '=net-misc/dahdi-3.1.0-r3::testworld'`.
 * The complete build log is located at '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/temp/build.log'.
 * The ebuild environment file is located at '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/temp/environment'.
 * Working directory: '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0'
 * S: '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0'
```
I'm on kernel 5.10.9.

**Comment by jkroonza** [comment]
> It may be my system, it may be something else:
> 
> ```
> make -f ./scripts/Makefile.modpost
>   sed 's/ko$/o/' /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/modules.order | scripts/mod/modpost -m -a   -o /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/Module.symvers -e -i Module.symvers   -T -
> /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/vpmadt032_loader/.vpmadt032_x86_64.o.cmd: No such file or directory
> make[2]: *** [scripts/Makefile.modpost:111: /var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0/drivers/dahdi/Module.symvers] Error 1
> make[1]: *** [Makefile:1712: modules] Error 2
> make[1]: Leaving directory '/usr/src/linux'
> make: *** [Makefile:74: modules] Error 2
>  * ERROR: net-misc/dahdi-3.1.0-r3::testworld failed (compile phase):
>  *   emake failed
>  * 
>  * If you need support, post the output of `emerge --info '=net-misc/dahdi-3.1.0-r3::testworld'`,
>  * the complete build log and the output of `emerge -pqv '=net-misc/dahdi-3.1.0-r3::testworld'`.
>  * The complete build log is located at '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/temp/build.log'.
>  * The ebuild environment file is located at '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/temp/environment'.
>  * Working directory: '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0'
>  * S: '/var/tmp/portage/net-misc/dahdi-3.1.0-r3/work/dahdi-linux-3.1.0'
> ```
> 
> I'm on kernel 5.10.9.

Very interesting.  That looks like a build system failure, not code related.  Your kernel sources is prepped right?  Mind emailing me the full build.log?

**Review by juippis — APPROVED** [review]
I have no doubt it's my container then :) 

Let's send it to tinderbox.

**Comment by jkroonza** [comment]
> I have no doubt it's my container then :)
> 
> Let's send it to tinderbox.

That's one way - I would have preferred to confirm :).

Either way, thank you.

**Pull request closed without merging**
