### PR TITLE
sci-libs/cantera: pass AR env variable. Add lapack support.

### PR DESCRIPTION
**Pull request by band-a-prend**
* Pass AR env variable to be able to use llvm-ar instead of ar.
Closes: https://bugs.gentoo.org/773541

* Add lapack support

@asarubbo 
please check if this PR (especially first commit) fixes the issue.

### CODE REVIEW

**Review by juippis — APPROVED** [review]
Can't test the ar fix, but at least lapack works!

**Comment by juippis** [comment]
Actually it seems to fail with `-python` IUSE.

**Comment by band-a-prend** [comment]
@juippis 
tests fail with ` USE=-python` ?

**Comment by band-a-prend** [comment]
> Actually it seems to fail with `-python` IUSE.

Could I fix it without revbump?

**Comment by band-a-prend** [comment]
@juippis 
I fixed it in https://github.com/gentoo/gentoo/pull/20317 pull request
As installation was broken anyway I don't make revision bump this time.

**Comment by juippis** [comment]
Yep, looks good, thanks!

**Pull request closed without merging**
