### PR TITLE
app-text/xapian-omega, sys-devel/ct-ng, sys-kernel/hardened-sources, www-servers/varnish: use HTTPS

### PR DESCRIPTION
**Pull request by mm1ke**
Hi,

This PR fixes a few packages to use https instead of http for the HOMEPAGE

Please review.

### CODE REVIEW

**Comment by mm1ke** [comment]
rebased, any chance for a merge? :)

**Comment by blueness** [comment]
Thanks for these cleanups!  Did you test to see if those urls work?

**Comment by blueness** [comment]
never mind i just pushed this.  its safe enough

**Comment by mm1ke** [comment]
Hi, 

Yes, i do actually look if the links are working.
However, it looks like i've introduces a problem with sys-devel/ct-ng with this PR. I'm sorry about that and I already created a new PR which fixes this: https://github.com/gentoo/gentoo/pull/7425

**Pull request closed without merging**
