### PR TITLE
dev-python/pyxdg: Remove unused patch

### PR DESCRIPTION
**Pull request by anthonyryan1**
files/pyxdg-subprocess.patch is no longer used

Fixes https://bugs.gentoo.org/540940

### CODE REVIEW

**Comment by mgorny** [comment]
Please don't mix metadata change with patch removal. Those are two irrelevant changes which deserve separate commits. This would be especially important if we ever needed to restore the patch.

**Comment by anthonyryan1** [comment]
@mgorny Commit updated to only remove the patch file. I'll send a separate pull request for the metadata changes at a later time.

**Comment by mgorny** [comment]
Done, thanks. Next time, please consider signing the commit.

**Comment by mgorny** [comment]
As in, `git rebase -S` probably ;-).

**Pull request merged**
