### PR TITLE
app-office/borg: jgoodies-looks:2.6 slot update 

### PR DESCRIPTION
**Pull request by vaukai**

### CODE REVIEW

**Comment by fordfrog** [comment]
i just fixed the `dev-java/jgoodies-looks:2.6` issue in 82d52a7d556b982104ea41b90f1435235594c8f3.

**Comment by fordfrog** [comment]
i can't emerge `borg`, i get this error and atm don't have time to investigate it more:
```
BUILD FAILED
/var/tmp/portage/app-office/borg-1.7.4-r4/work/borg_src/BORGCalendar/ant/build.xml:104: java.lang.NoSuchMethodError: java.nio.CharBuffer.flip()Ljava/nio/CharBuffer;
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:81)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:66)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:118)
	at org.apache.tools.ant.util.ReaderInputStream.<init>(ReaderInputStream.java:93)
	at org.apache.tools.ant.taskdefs.Concat$ConcatResource.getInputStream(Concat.java:421)
	at org.apache.tools.ant.util.ResourceUtils.copyUsingStreams(ResourceUtils.java:766)
	at org.apache.tools.ant.util.ResourceUtils.copyResource(ResourceUtils.java:437)
	at org.apache.tools.ant.taskdefs.Concat.execute(Concat.java:802)
	at org.apache.tools.ant.UnknownElement.execute(UnknownElement.java:292)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tools.ant.dispatch.DispatchUtils.execute(DispatchUtils.java:99)
	at org.apache.tools.ant.Task.perform(Task.java:350)
	at org.apache.tools.ant.Target.execute(Target.java:449)
	at org.apache.tools.ant.Target.performTasks(Target.java:470)
	at org.apache.tools.ant.Project.executeSortedTargets(Project.java:1401)
	at org.apache.tools.ant.Project.executeTarget(Project.java:1374)
	at org.apache.tools.ant.helper.DefaultExecutor.executeTargets(DefaultExecutor.java:41)
	at org.apache.tools.ant.Project.executeTargets(Project.java:1264)
	at org.apache.tools.ant.Main.runBuild(Main.java:827)
	at org.apache.tools.ant.Main.startAnt(Main.java:223)
	at org.apache.tools.ant.launch.Launcher.run(Launcher.java:284)
	at org.apache.tools.ant.launch.Launcher.main(Launcher.java:101)
```

**Comment by vaukai** [comment]
> i can't emerge `borg`, i get this error and atm don't have time to investigate it more:

Just retried and here it still compiles http://ix.io/3nNZ

**Comment by vaukai** [comment]
> i can't emerge `borg`, i get this error and atm don't have time to investigate it more:

Today I am getting the same error - with the old -r3 revision and openjdk:8
So it seems not specific to the changes of this PR.

Regarding the history of this package it seems to never have had a stable version and actually has no consumers.
The only mention in `ebuilds` is [here](https://github.com/gentoo/gentoo/blob/master/app-backup/borgbackup/borgbackup-1.1.15.ebuild#L24-L26) as a strong blocker.

Why not last-rite this `app-office/borg`?

**Comment by fordfrog** [comment]
is there any up-to-date maintained repo or this package is abandoned?

**Pull request closed without merging**
