### PR TITLE
dev-lang/scala: restrict to virtual/jdk:1.8 for bug #932012

### PR DESCRIPTION
**Pull request by vaukai**
Closes: https://bugs.gentoo.org/932012

---

Please check all the boxes that apply:

- [x] I can submit this contribution in agreement with the [Copyright Policy](https://www.gentoo.org/glep/glep-0076.html#certificate-of-origin).
- [x] I have certified the above via adding a `Signed-off-by` line to *every* commit in the pull request.
- [x] This contribution has not been created with the assistance of Natural Language Processing artificial intelligence tools, in accordance with the [AI policy](https://wiki.gentoo.org/wiki/Project:Council/AI_policy).
- [x] I have run `pkgcheck scan --commits --net` to check for issues with my commits.

Please note that all boxes must be checked for the pull request to be merged.

### CODE REVIEW

**Comment by fordfrog** [comment]
i think it would be useful to first see the real deprecation reasons for these issues (using `-deprecation` switch):
```
[error] Test scala.tools.nsc.backend.jvm.opt.BoxUnboxTest.boxUnboxPrimitive failed: java.lang.AssertionError: assertion failed: The compiler issued non-allowed warnings or errors:
[error] pos: NoPosition there were two deprecation warnings; re-run with -deprecation for details WARNING, took 0.868 sec
[error]     at scala.Predef$.assert(Predef.scala:223)
[error]     at scala.tools.testing.Compiler.checkReport(BytecodeTesting.scala:73)
[error]     at scala.tools.testing.Compiler.compileToBytes(BytecodeTesting.scala:80)
[error]     at scala.tools.testing.Compiler.compileClasses(BytecodeTesting.scala:85)
[error]     at scala.tools.testing.Compiler.compileClass(BytecodeTesting.scala:89)
[error]     at scala.tools.nsc.backend.jvm.opt.BoxUnboxTest.boxUnboxPrimitive(BoxUnboxTest.scala:151)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
...
[error] Test scala.tools.nsc.backend.jvm.opt.BoxUnboxTest.tupleElimination failed: java.lang.AssertionError: assertion failed: The compiler issued non-allowed warnings or errors:
[error] pos: NoPosition there was one deprecation warning; re-run with -deprecation for details WARNING, took 0.373 sec
[error]     at scala.Predef$.assert(Predef.scala:223)
[error]     at scala.tools.testing.Compiler.checkReport(BytecodeTesting.scala:73)
[error]     at scala.tools.testing.Compiler.compileToBytes(BytecodeTesting.scala:80)
[error]     at scala.tools.testing.Compiler.compileClasses(BytecodeTesting.scala:85)
[error]     at scala.tools.testing.Compiler.compileClass(BytecodeTesting.scala:89)
[error]     at scala.tools.nsc.backend.jvm.opt.BoxUnboxTest.tupleElimination(BoxUnboxTest.scala:313)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
...
[error] Test scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest.noElimImpureConstructor failed: java.lang.AssertionError: assertion failed: The compiler issued non-allowed warnings or errors:
[error] pos: NoPosition there was one deprecation warning; re-run with -deprecation for details WARNING, took 0.065 sec
[error]     at scala.Predef$.assert(Predef.scala:223)
[error]     at scala.tools.testing.Compiler.checkReport(BytecodeTesting.scala:73)
[error]     at scala.tools.testing.Compiler.compileToBytes(BytecodeTesting.scala:80)
[error]     at scala.tools.testing.Compiler.compileClasses(BytecodeTesting.scala:85)
[error]     at scala.tools.testing.Compiler.compileClass(BytecodeTesting.scala:89)
[error]     at scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest.noElimImpureConstructor(MethodLevelOptsTest.scala:176)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
...
[error] Test scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest.elimUnusedTupleObjectStringBox failed: java.lang.AssertionError: assertion failed: The compiler issued non-allowed warnings or errors:
[error] pos: NoPosition there was one deprecation warning; re-run with -deprecation for details WARNING, took 0.248 sec
[error]     at scala.Predef$.assert(Predef.scala:223)
[error]     at scala.tools.testing.Compiler.checkReport(BytecodeTesting.scala:73)
[error]     at scala.tools.testing.Compiler.compileToBytes(BytecodeTesting.scala:80)
[error]     at scala.tools.testing.Compiler.compileClasses(BytecodeTesting.scala:85)
[error]     at scala.tools.testing.Compiler.compileClass(BytecodeTesting.scala:89)
[error]     at scala.tools.nsc.backend.jvm.opt.MethodLevelOptsTest.elimUnusedTupleObjectStringBox(MethodLevelOptsTest.scala:161)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```
for the following issues `javax.annotation.Resource` was not found on the classpath:
```
[error] Test scala.lang.annotations.RunTest.annotationInfoNotErased failed: scala.tools.reflect.ToolBoxError: reflective compilation has failed:
[error] 
[error] object Resource is not a member of package javax.annotation
[error] not found: type Resource
[error] <none> cannot be instantiated because it does not conform to its self-type <notype>
[error] value type is not a member of Nothing, took 0.716 sec
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:331)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:213)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:267)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$compile$13(ToolBoxFactory.scala:444)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:370)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:370)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:437)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:459)
[error]     at scala.tools.testing.Runner.run(RunTesting.scala:12)
[error]     at scala.lang.annotations.RunTest.annotationInfoNotErased(RunTest.scala:30)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
...
[error] Test scala.reflect.ClassOfTest.t9702 failed: scala.tools.reflect.ToolBoxError: reflective compilation has failed:
[error] 
[error] object Resource is not a member of package javax.annotation
[error] not found: type Resource
[error] value type is not a member of Nothing, took 0.542 sec
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.throwIfErrors(ToolBoxFactory.scala:331)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.wrapInPackageAndCompile(ToolBoxFactory.scala:213)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$ToolBoxGlobal.compile(ToolBoxFactory.scala:267)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.$anonfun$compile$13(ToolBoxFactory.scala:444)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.liftedTree2$1(ToolBoxFactory.scala:370)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl$withCompilerApi$.apply(ToolBoxFactory.scala:370)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.compile(ToolBoxFactory.scala:437)
[error]     at scala.tools.reflect.ToolBoxFactory$ToolBoxImpl.eval(ToolBoxFactory.scala:459)
[error]     at scala.tools.testing.Runner.run(RunTesting.scala:12)
[error]     at scala.reflect.ClassOfTest.t9702(ClassOfTest.scala:109)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[error]     at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[error]     at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[error]     at java.lang.reflect.Method.invoke(Method.java:566)
[error]     ...
```

**Comment by vaukai** [comment]
> for the following issues `javax.annotation.Resource` was not found on the classpath:

Wasn't [`javax.annotation` removed on java 11?](https://openjdk.org/jeps/320) And did you mean to try adding it from a package to scala*s classpath?
Could try later to find a way how to do that.

**Comment by fordfrog** [comment]
> Wasn't [`javax.annotation` removed on java 11?](https://openjdk.org/jeps/320) And did you mean to try adding it from a package to scala*s classpath? Could try later to find a way how to do that.

yes, it was. generally more stuff was removed in java 9 and 11 and it has to be replaced by external packages to restore the functionality.

**Comment by vaukai** [comment]
> > Wasn't [`javax.annotation` removed on java 11?](https://openjdk.org/jeps/320) And did you mean to try adding it from a package to scala*s classpath? Could try later to find a way how to do that.
> 
> yes, it was. generally more stuff was removed in java 9 and 11 and it has to be replaced by external packages to restore the functionality.

Looks like it needs https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-java/jsr250?id=d9f7842152a5e71fb21bfba0b4e22c93f57cb06f reverted but I have no idea how to apply it, not familiar with that build system.

**Comment by vaukai** [comment]
Commented on https://bugs.gentoo.org/932012

**Pull request closed without merging**
