### PR TITLE
dev-python/aiohttp: version bump to 0.21.5

### PR DESCRIPTION
**Pull request by radaiming**
I'd also like to add python3_5 to PYTHON_COMPAT, but its dependencies dev-python/sphinxcontrib-newsfeed dev-python/sphinxcontrib-spelling and www-servers/gunicorn doesn't have it in PYTHON_COMPAT yet.

Looks aiohttp and gunicorn should work with Python 3.5, but not quiet sure about sphinxcontrib-newsfeed and sphinxcontrib-spelling, they are not actively developing now. Any suggestion?

@alunduil

### CODE REVIEW

**Comment by alunduil** [comment]
@radaiming, I'd suggest just trying them with the addition to `PYTHON_COMPAT` and see if they work.  If not we may need to patch it and push it upstream.  I was going to take a look at this bump today as well.  Let me know if you want this merged or if I should just go ahead and update like I usually do.

As for `PYTHON3_5`, I've been patient but if someone wants to go through and force the update on its dependencies that would be excellent.

**Comment by radaiming** [comment]
I switched my default Python to 3.5.1, I'd like to be able to use some more libs. Some dependencies don't provide test scripts, I could only do some simple tests, if work I will update this PR, so please wait a while for merging, thanks :)

**Comment by idella** [comment]
Try to create a special bramnch for the purpose of pull reqs, is more reliable.

**Comment by radaiming** [comment]
Thanks, I saw others using master branch to send PR so I followed them. I'm having issue on signing the commits, I will update later.

**Comment by idella** [comment]
Applying: dev-python/aiohttp: version bump to 0.21.5
error: patch failed: dev-python/aiohttp/Manifest:1
error: dev-python/aiohttp/Manifest: patch does not apply
error: dev-python/aiohttp/aiohttp-0.21.5.ebuild: already exists in index

Something has gone awry in got re the Manifest file.
Can you create a branch, repeat your changes.
Close this pull req and make a fresh. The change of the branch alone warrants this. Otherwise the changes are fine.

**Comment by idella** [comment]
Signing the commits / Manifest file requires the full setup for a gpg key.  The proesses are well enough described in gentoo's own docs.

**Comment by radaiming** [comment]
Looks weird, the Manifest was updated in https://github.com/gentoo/gentoo.git master branch yesterday, when I rebasing onto it, I resolved the conflict, and looks github is also saying "This branch has no conflicts with the base branch".

I have gpg key, and there's no problem running gpg command to encrypt/sign, but when using with git it's reporting something like "Inappropriate ioctl for device", I'm searching for this error and will check the doc.

**Comment by radaiming** [comment]
Seems signing is dev's work, I don't need to do that right? I will create a new PR.

**Pull request closed without merging**
