### PR TITLE
net-libs/libsoup-2.64.2: add dev-lang/python-3.7

### PR DESCRIPTION
**Pull request by XVilka**
It also supports dev-lang/python:3.7 version

### CODE REVIEW

**Comment by XVilka** [comment]
I added signoff and force-pushed, but @gentoo-bot didn't remove the label.

**Comment by juippis** [comment]
Edit the Github issue title with appending `[please reassign]` there.

**Comment by XVilka** [comment]
ping?

**Comment by XVilka** [comment]
Anyone alive here? @gentoo/gnome

**Comment by XVilka** [comment]
Ping?

**Comment by XVilka** [comment]
Ping?

**Comment by leio** [comment]
2.64 doesn't use python during build at all, due to tld-parser.py generation being replaced with libpsl usage. So I've fixed it properly by removing python deps completely. When doing such work, please actually look inside what's going on there with the python deps.

**Comment by XVilka** [comment]
@leio thanks! Will do next time, sorry for the trouble.

**Pull request closed without merging**
