### PR TITLE
app-editors/vscode: version bump: 1.59.0

### PR DESCRIPTION
**Pull request by Kangie**
Package-Manager: Portage-3.0.20, Repoman-3.0.3
Signed-off-by: Matt Jolly <Matt.Jolly@footclan.ninja>

### CODE REVIEW

**Comment by AdelKS** [comment]
Hello! Thank you for your help, can you bump vscodium too ? I am away from my computer for one more week and will not be able to do it untill then.

**Comment by juippis** [comment]
I've heard some trouble with sandbox and either vscode, or vscodium, or perhaps both. We do 
`fperms u+s /opt/program/chrome-sandbox` on many of these electron-based apps. Can you check whether that binary exists, and use the fperms above?

**Comment by AdelKS** [comment]
Yes that binary does exist and currently it has `fperms +x /opt/${PN}/chrome-sandbox`, so you suggest putting `fperms u+s /opt/${PN}/chrome-sandbox` ? I did get some feedback about this indeed. I still don't understand why it works on my machine. Can you try this @Kangie ?

Thank you!

**Comment by Kangie** [comment]
@AdelKS All seems good here; both launch and behave as I expect.

**Comment by AdelKS** [comment]
Awesome thanks!

**Pull request closed without merging**
