### PR TITLE
all-in-one: add support for ppc64le platform

### PR DESCRIPTION
**Pull request by houstar**
This is the portage changes for support ppc64le platform and fixes the problem below

1. specified  $LD='ld -m elf64lppc' in ppc64le platform
2. added package.accept_keywords and package.use to ppc64le profiles
3. gcc5 can't define the inline function in headers
4. Open new bug#580512 in bugzilla to request and track 

https://bugs.gentoo.org/show_bug.cgi?id=580512

### CODE REVIEW

**Comment by blueness** [comment]
there are a lot of problems here.  1) putting all these changes in one commit makes it impossible to selectively commit or revert changes to different packages.  2) the changes to config.sub need to go upstream 3) package.accept_keywords is not allowed in a profile.  it short circuits arch testing for keywords and stablereq 4) you have numerous QA issues.  there are still other problems.  i would start by getting the changes to config.sub upstream to gnuconfig.  See http://savannah.gnu.org/projects/config

**Comment by monsieurp** [comment]
Disregard errors. Stricter QA checks have been turned on.

**Comment by monsieurp** [comment]
@blueness you're taking on this PR I gather.

**Comment by monsieurp** [comment]
What's the deal with this PR? @blueness is it ready to go?

**Comment by houstar** [comment]
@monsieurp @vapier @blueness I think it's the time to merge this PR

1. We've made stage3 and livecd by this PR and use this stage3 as development to build stage3 and livecd with systemd since April 5,2016.

2. We've released stage3 and livecd with systemd as Guest OS image which includes docker and k8s on [SuperVessel](https://ptopenlab.com).

3. Since these commits pushed to this PR were recored in [Gentoo ppc64le bugs](https://bugs.gentoo.org/buglist.cgi?f1=reporter&list_id=3179198&o1=equals&resolution=---&v1=%25user%25) , so I think it's convenient for the guys whom wants to build gentoo ppc64le.

**Comment by blueness** [comment]
@houstar @monsieurp the biggest problem i have is with osuosl's ppc64le openstack thing they gave us.  i can't test any of these patches.  there is a lot of work here because there's no way i can just more this as on pr.  i have to look at each package and make sure we're not breaking any QA rules.  

Leno I know this is frustrating for you, but I'm stuck without a reliabel ppc64le system.

**Comment by blueness** [comment]
@houstar i will try again this afternoon to get the ppc64le openstack stuff to work.  if we can't is there anything you can do at your end to give me access to a ppc64le system?

**Comment by houstar** [comment]
Hi @blueness ,

Sorry for delayed reply.
My colleague has erased and re-installed our system. So maybe next week i'll prepare a system that you can access from public. Thanks.

**Comment by houstar** [comment]
@blueness 

I've prepared the system for you access. This system was hosted in a private network behind firewall. Could you provide  an account in your public server as tunnel host that I can access ?Then I'll do 
#ssh -CfNg -R 8168:127.0.0.1:22 account@tunnel_host

So you can access from tunnel host like that #ssh -p 8168 root@localhost

**Comment by blueness** [comment]
if you don't need root i can give you access to one of my servers.

**Comment by houstar** [comment]
I don't need root privileges. please mail the normal user & password to lenohou@gmail.com. Thanks

**Comment by blueness** [comment]
sent

**Comment by houstar** [comment]
@blueness  I haven't saw it. Did you sent to my email: lenohou@gmail.com ? Thanks

**Comment by blueness** [comment]
resent

**Comment by houstar** [comment]
Done! thanks. please check your mailbox.

**Comment by blueness** [comment]
@houstar i see what you're up to with this pr but there's no way I can just commit it as one lump.  i need to go through the pkgs maintainers for reach pkg.  I'm willing to do that but i need to test and we're still having trouble getting a system for me going.

**Comment by houstar** [comment]
@blueness  Thanks Anthony. I think now you can access gentoo ppc64le in your system like:
ssh -p 8168 root@localhost

**Comment by mgorny** [comment]
I presume the PR should be closed now that you're working in the overlay.

**Comment by soredake** [comment]
Any updates?

**Pull request closed without merging**
