### PR TITLE
app-crypt/hashcat: update to 6.2.5

### PR DESCRIPTION
**Pull request by Miezhiko**
Also drop 6.2.4 and merged patches

### CODE REVIEW

**Comment by thesamesam** [comment]
Please cleanup in a separate commit but I'd also prefer to not get rid of the last version immediately. Thanks for the PR.

**Comment by Miezhiko** [comment]
@thesamesam done,
6.2.5 is minor release, mostly with bug fixes, I personally think it's good to drop merged patches and update.

**Comment by thesamesam** [comment]
> @thesamesam done, 6.2.5 is minor release, mostly with bug fixes, I personally think it's good to drop merged patches and update.

I understand that, but if we remove n-1 versions _immediately_, if there are regressions, people won't be able to easily get back to a version which works. We don't really gain anything at all from removing it instantly, it just makes it harder for people to downgrade if necessary.

Also, didn't they change some of the rocm requirements for this? (not checked yet, but saw the commits before)

**Comment by Miezhiko** [comment]
@thesamesam alright, I've dropped clean up commit.

**Comment by ZeroChaos-** [comment]
ACK

**Pull request closed without merging**
