### PR TITLE
mail-mta/exim: use freeradius-client instead of radiusclient

### PR DESCRIPTION
**Pull request by puleglot**
Use net-dialup/freeradius-client instead of net-dialup/radiusclient.

Also fix compilation with USE=radius. It was broken since 4.86 release.

### CODE REVIEW

**Comment by puleglot** [comment]
Ooops.. This require to keyword net-dialup/freeradius-client on more arches.

**Comment by puleglot** [comment]
@Pinkbyte what do you think?

**Comment by mgorny** [comment]
@puleglot, since this is a revbump, you can remove some extra keywords for now, and we'll request adding them synchronously to freeradius-client & exim.

**Comment by puleglot** [comment]
PR updated

**Comment by Pinkbyte** [comment]
Hm, last time i have tried to apply this updates - they were not enough to make exim actually work with radius. Did you check if it works, not only compiles without errors?

**Comment by puleglot** [comment]
Yes, it works. Tested with the following PLAIN auth configuration:
```
PLAIN:
  driver                     = plaintext
  server_set_id              = $auth2
  server_prompts             = :
  server_condition           = ${if radius{$auth2:$auth3}{yes}{no}}
```

**Comment by Pinkbyte** [comment]
Thanks, pushed to main tree. I will create apropriate keywords requests

commit 2091c3a9d7ceccca564d8277d4de8e0e934615d7
Author: Alexander Tsoy <alexander@tsoy.me>
Date:   Sun Oct 18 00:44:31 2015 +0300

    mail-mta/exim: use freeradius-client instead of radiusclient

    Also fix compilation with USE=radius. It was broken since
    4.86 release.

    Acked-by: Sergey Popov <pinkbyte@gentoo.org>
    Gentoo-Bug: 563356

**Pull request closed without merging**
