### PR TITLE
RIPE Atlas Sagan

### PR DESCRIPTION
**Pull request by danielquinn**
I spent a good chunk of time on `#gentoo-proxy-maint` today talking with the very helpful `idella4` in order to ensure that these packages were conforming to standards etc.  After lots of hacking at it, (s)he said that a pull request was the next step.

This is RIPE Atlas Sagan, a parsing library for results returned from the [RIPE Atlas](https://atlas.ripe.net/) system.  It's a dependency for the toolkit, sent in a separate pull request (#482).

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi Daniel

Thanks a lot for your PR. Great job. However, there's one tiny snag: when committing, please use the following format:

category/package-name: commit message

If you're looking for examples, look at this PR https://github.com/gentoo/gentoo/pull/447. Thanks in advance for editing your commit. Cheers.

**Comment by danielquinn** [comment]
I'd be happy to amend the commit... but I don't know how to do that.  Can you point me to something resembling a howto?

**Comment by danielquinn** [comment]
Nevermind, I figured it out :-)

**Comment by monsieurp** [comment]
@gentoo/proxy-maint

**Comment by monsieurp** [comment]
I'll merge them.

**Pull request merged**
