### PR TITLE
app-text/master-pdf-editor: version bump to 5.1.42

### PR DESCRIPTION
**Pull request by jpataias**
Version bump to 5.1.42

### CODE REVIEW

**Comment by jpataias** [comment]
Just read the copyright policy compliance. Just need to add: "Signed-off-by: João Santos <joaompssantos@gmail.com>", to all my future commits right?

**Comment by mgorny** [comment]
Yes, provided you take appropriate not to post copyright-infringing stuff.

**Comment by jpataias** [comment]
Made the necessary alterations to the commit message.

**Comment by mgorny** [comment]
Thank you. Let's wait a minute for the script to recheck and in the meantime I'm going to test it.

**Pull request closed without merging**
