### PR TITLE
dev-db/mycli: version bump to 1.7.1

### PR DESCRIPTION
**Pull request by jok-ts**
dev-python/ipython-4.2.0 brings a dependency on >=dev-python/prompt_toolkit-1.0.0 which the mycli versions in the tree don't accept. Support for that starts from mycli-1.7.0.

### CODE REVIEW

**Comment by monsieurp** [comment]
Thanks for the PR. Please make sure your commit message follow our guidelines [1]. Thanks.

[1]: https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format

**Comment by monsieurp** [comment]
@grknight @gentoo/python

**Comment by mgorny** [comment]
Yay, someone came to fix my irritation!

**Comment by mgorny** [comment]
Cherry-picked and pushed both, thanks!

**Pull request closed without merging**
