### PR TITLE
boost-1.60

### PR DESCRIPTION
**Pull request by iHateInventNames**
Change-Id: I06286e6e73728382795363c409d568957c76ba7c

### CODE REVIEW

**Comment by monsieurp** [comment]
Hi and thank you for your PR. Could you please rebase/amend your commit according to our standards? that is: "cat/pkg: commit msg". Thank you.

**Comment by monsieurp** [comment]
@jauhien @SoapGentoo @dev-zero @Pinkbyte

**Comment by iHateInventNames** [comment]
Updated

**Comment by SoapGentoo** [comment]
Boost is a massive package and probably the single most important C++ library. Have you tested this against a multitude of packages, especially the more problematic ones? We will definitely not merge such a package lightheartedly. See also: https://bugs.gentoo.org/show_bug.cgi?id=558794

**Comment by SoapGentoo** [comment]
Oh and before I forget: your commit message is still wrong. Proper commit messages do not include the version. Have a look at repoman (https://wiki.gentoo.org/wiki/Repoman).

**Pull request closed without merging**
