### PR TITLE
net-im/skypeforlinux: Bump version to 8.51.0.86

### PR DESCRIPTION
**Pull request by jvesely**

### CODE REVIEW

**Comment by jvesely** [comment]
@juippis, @oniGino, yet another bump.
The second patch removes the oldest version (8.50.x.xx), but I'm not sure if we should keep older versions of the same line (Y.XX).
Microsoft is not really verbose about the "bug fixes" so the old versions might be a security risk.

**Comment by juippis** [comment]
Waiting for @oniGino to answer that, and to check and test the ebuild.
I'd like to ask both of you if @jvesely wants to become a co-maintainer for this package, since you seem to do a lot for it.

**Comment by oniGino** [comment]
This Looks Fine

sorry, my new job is 60/wk so I'm going to be slow on reviewing these
@jvesely if you really want to co-maintain its fine by me. I don't use this app as much as I used to.

**Comment by juippis** [comment]
Thanks. @jvesely if you wish, just add yourself the next time you do something to this package :)

**Comment by jvesely** [comment]
Thanks. Does proxy-maintenance require some extra testing? I'll be using skypeforlinux on a weekly bases for at least a year so I've no problem opening these PRs is no problem.

**Comment by juippis** [comment]
You are expected to handle bugs that are opened for it. Currently seems like there are 2 open, I am not sure if a version bump has already fixed these. Seems pretty low maintenance package to start getting experience with!

**Comment by oniGino** [comment]
Just to give you some background there is only one thing that is a reoccurring topic for this package. Many people who want hacks installed that bypass the systemd/logind dependency requirement, I almost always reject these, since it adds instability to the package, requires us to merge new packages into tree and doesn't seem appropriate.
Also at some time in history this app worked without libsecret, but that's nolonger the case, so on occasion people ask for the dependency to be dropped..
 we can discuss those open tickets in email more later if you like.

Welcome to the party

**Pull request closed without merging**
