### PR TITLE
www-apps/gitea: bump to 1.15.10

### PR DESCRIPTION
**Pull request by scardracs**
Fix copyright dates
Drop remaining -9999 requirements (I'm gonna maintain it so I don't want any live package).

Package-Manager: Portage-3.0.30, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by scardracs** [comment]
TODO: readd the if... acct

**Comment by hydrapolic** [comment]
So are you going to take this or no? :)

**Comment by ionenwks** [comment]
> scardracs So are you going to take this or no? :)

I don't think so (see [bug #775974](https://bugs.gentoo.org/775974)), and it could certainly use a dedicated maintainer.

**Comment by hydrapolic** [comment]
Ok I'll open a PR myself then. Thanks @ionenwks

**Pull request closed without merging**
