### PR TITLE
media-sound/alsamixer: strsignal patch for bug #738176

### PR DESCRIPTION
**Pull request by pyeatt**
Closes: https://bugs.gentoo.org/738176
Suggested-by: Larry Pyeatt <larry.pyeatt@sdsmt.edu>
Signed-off-by:  Larry Pyeatt <larry.pyeatt@sdsmt.edu>

### CODE REVIEW

**Comment by thesamesam** [comment]
Nice! We don't need to revbump [because](https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html) this is a build-time fix but I can sort that on merge.

**Comment by pyeatt** [comment]
> Nice! We don't need to revbump [because](https://devmanual.gentoo.org/general-concepts/ebuild-revisions/index.html) this is a build-time fix but I can sort that on merge.
>
> Thank you for this (and well done on getting the sign-off right first time)

Thanks.  I actually cancelled my first pull request and got it right the second time.  Did not know about GLEP66 until the bot started complaining.

**Review by a17r — APPROVED** [review]
Thanks for your fix. Had to tweak the commit message a bit: `media-sound/alsamixer` -> `media-sound/alsamixergui`

**Comment by pyeatt** [comment]
oops.  Thanks.


Larry D. Pyeatt, PhD.
Department of Computer Science and Engineering
South Dakota School of Mines and Technology
larry.pyeatt@sdsmt.edu
http://www.mcs.sdsmt.edu/lpyeatt

________________________________

**Pull request closed without merging**
