### PR TITLE
net-proxy/squid: bump to 4.17

### PR DESCRIPTION
**Pull request by hydrapolic**
Copy of 4.15, compiles fine on ~amd64.

### CODE REVIEW

**Comment by hydrapolic** [comment]
@Zlogene

**Comment by mikhailkoliada** [comment]
@hydrapolic would you mind updating to 4.17? (I am barely using my personal github account these days)

**Comment by hydrapolic** [comment]
Sure @mikhailkoliada, PR updated.

**Comment by hydrapolic** [comment]
Thank you @mikhailkoliada @Zlogene

**Pull request closed without merging**
