### PR TITLE
net-misc/axel: Keyword 2.17.10 for ~mips

### PR DESCRIPTION
**Pull request by infiWang**
Signed-off-by: Raymond Wong <infiwang@pm.me>
Closes: https://bugs.gentoo.org/836586

### CODE REVIEW

**Comment by infiWang** [comment]
Related keyword bug: https://bugs.gentoo.org/836586

**Comment by slashbeast** [comment]
The commit message state mips, the change adds riscv. Can you please update the pull request with proper commit message?

**Comment by infiWang** [comment]
> The commit message state mips, the change adds riscv. Can you please update the pull request with proper commit message?

I don't think my commit has anything related to riscv, except the link to the bug which is a combined keywording request. 

~riscv keywording was finished by `0924d4b` previously.

**Comment by slashbeast** [comment]
All good, I saw riscv in bug, here mips but somehow overlooked mips that is also in the bug.

**Pull request closed without merging**
