### PR TITLE
dev-python/py-gfm: bump to 1.0.2

### PR DESCRIPTION
**Pull request by scardracs**
Add support to python3.9 (tested with 3.9.4)

Closes: https://bugs.gentoo.org/680260
Closes: https://bugs.gentoo.org/748477

Package-Manager: Portage-3.0.18, Repoman-3.0.3
Signed-off-by: Marco Scardovi <marco@scardovi.com>

### CODE REVIEW

**Comment by scardracs** [comment]
@thesamesam added test :)

**Comment by scardracs** [comment]
@mgorny could I ask if you can take a look here too?

**Comment by thesamesam** [comment]
Thanks!

**Comment by scardracs** [comment]
> Thanks!

Thanks to you too! :D

**Pull request closed without merging**
