### PR TITLE
www apps/gitea: bump to 1.10.1 and remove 1.8.3

### PR DESCRIPTION
**Pull request by xdch47**
Closes: https://bugs.gentoo.org/689748
Closes: https://bugs.gentoo.org/702192

### CODE REVIEW

**Comment by ulm** [comment]
This still doesn't appear to completely address the license issue of bug 694356, as far as github.com/couchbase/goutils/LICENSE.md is concerned.

**Comment by xdch47** [comment]
Could you please clarify your point, with substantial arguments?

I think it should accentually have been closed by #12597.
Summary of the discussion there:
1. upstream clearified license couchbase/goutils@b496390
2. the [orginal files](https://github.com/go-gitea/gitea/tree/master/vendor/github.com/couchbase/goutils) used by gitea do have all an Apache 2.0 license header, see:
 - [logger.go](https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/logging/logger.go)
 - [logger_golog.go](https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/logging/logger_golog.go)
 - [scramsha.go](https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/scramsha/scramsha.go)
 - [scramsha_http.go](https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/scramsha/scramsha_http.go)

Last but not least the [LICENSE ITSELF](https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/LICENSE.md):
```
License Grant. Couchbase Inc. hereby grants Licensee, free of charge,
the non-exclusive right to use, copy, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons 
to whom the Software is furnished to do so, subject to Licensee
including the following copyright notice in all copies
or substantial portions of the Software:

Couchbase (r) http://www.Couchbase.com Copyright 2016 Couchbase, Inc.
```

I'm not a license expert nor a lawyer, however with my minimal understanding I can not see any incompatibility to the Apache 2.0 license, except its declaration as "End-User Licence Agreement" - however the text is quite “permissive”, isn't it?

**Comment by xdch47** [comment]
however, you are - I'll try get this changed in Gitea upstream as well to kill all doubts.

**Comment by ulm** [comment]
> I'm not a license expert nor a lawyer, however with my minimal understanding I can not see any incompatibility to the Apache 2.0 license, except its declaration as "End-User Licence Agreement" - however the text is quite “permissive”, isn't it?

It is not at all permissive, but fundamentally non-free: It neither allows distribution of the source code (the license says that "'Software' means the object code"), nor does it allow distribution of modified versions.

See also [bug 694356 comment 3](https://bugs.gentoo.org/694356#c3):

> > https://github.com/go-gitea/gitea/blob/master/vendor/github.com/couchbase/goutils/LICENSE.md
> 
> This is non-free:
> - Clause 1 doesn't grant freedom 3 (no right to distribute modified versions).
> - By the paragraph following clause 1, only distribution of object code is allowed (no freedom 1, access to source code).
> - Clause 2 forbids reverse engineering.
> 
> However, it isn't the typical language used in an EULA, so I don't believe that it belongs in that group.

**Comment by ulm** [comment]
> however, you are

Well, I am not a lawyer. :)

> I'll try get this changed in Gitea upstream as well to kill all doubts.

Indeed, that would be the best solution.

**Comment by xdch47** [comment]
funny - I see quite tricky to deal with thoses license (it not merging a kind of modification?)
the clause 2/3 seems to be nonsense in this case… ^^
however the most confusion point for me is the that the files, which are taken from the [couchbase/goutils](https://github.com/couchbase/goutils) repo all have a apache to license header

**Comment by xdch47** [comment]
another question… the upstream license seems to be just an template, or am i wrong?

[LICENSE.md](https://github.com/couchbase/goutils/blob/master/LICENSE.md):189   Copyright {yyyy} {name of copyright owner}

should that be something like ``Copyright 2016-2019 Couchbase, Inc.``

**Comment by Dessa** [comment]
does DRONE_TAG actually work on your end? i am stuck with 1.9.0-dev and have yet to find the right way to change that.

**Comment by xdch47** [comment]
no it does not - never saw this since I disabled the showing version.

**Comment by xdch47** [comment]
@dessa could you please try the update version here ?

**Comment by xdch47** [comment]
fixed mistakes

**Comment by Dessa** [comment]
`Gitea version 1.10.1 built with GNU Make 4.2.1, go1.13.4 : bindata, pam`

thanks!

**Comment by xdch47** [comment]
thank you !!

**Comment by xdch47** [comment]
- remove closing license bug
- fix passing of `LDFLAGS`
- fix default file locations

**Pull request closed without merging**
