### PR TITLE
media-gfx/openexr_viewers: fix Cg libdir

### PR DESCRIPTION
**Pull request by waebbl**
* remove files/openexr_viewers-2.3.0-fix-cg-libdir.patch
* add files/openexr_viewers-2.3.0--with-cg-libdir.patch

Addresses an issue, where Cg libraries where not found on 32-bit
arches. The patch adds an option --with-cg-libdir to configure to
pass 32-/64-bit specific libraries of Cg to configure script.

Thanks to @Arfrever for reporting the issue.

See also
https://github.com/gentoo/gentoo/pull/10030#pullrequestreview-164522412

Closes: https://bugs.gentoo.org/668754
Signed-off-by: Bernd Waibel <waebbl@gmail.com>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by dracwyrm** [comment]
Double - in the patch name? It could really be just one. ;)

**Comment by waebbl** [comment]
Chose it to reflect the --with-cg-libdir option. Doesn't hurt anyone, does it?

**Comment by a17r** [comment]
Is this pending upstream?

**Comment by waebbl** [comment]
Yes it's still pending, no reply so far.

**Pull request closed without merging**
