### PR TITLE
stardict.eclass: avoid splitting filenames

### PR DESCRIPTION
**Pull request by l29ah**

### CODE REVIEW

**Comment by flappyports** [comment]
@l29ah Please discuss this eclass change on the gentoo-dev mailing list.  This is a Gentoo requirement before eclass changes are merged.

**Comment by l29ah** [comment]
Nah i'm too lazy, i'll just copy it to my overlay if you don't see a reason behind such a change.

**Comment by monsieurp** [comment]
@l29ah Hi! Eclass changes must be discussed on the gentoo-dev public mailing list. You're no exception. Please follow our official guidelines. Thank you for your contribution!

**Comment by l29ah** [comment]
I see that https://github.com/gentoo/gentoo/pull/15733 didn't require such a scrutiny. If the policies are changed, could you please merge my stuff as well?

**Pull request closed without merging**
