### PR TITLE
sci-electronics/kicad: Bump to 6.0.8

### PR DESCRIPTION
**Pull request by zpuskas**
- sci-electronics/kicad: add 6.0.8
- sci-electronics/kicad: remove obsolete optfeature
- sci-electronics/kicad-footprints: add 6.0.8
- sci-electronics/kicad-packages3d: add 6.0.8
- sci-electronics/kicad-symbols: add 6.0.8
- sci-electronics/kicad-templates: add 6.0.8
- app-doc/kicad-doc: add 6.0.8
- sci-electronics/kicad-meta: add 6.0.8

### CODE REVIEW

**Comment by zpuskas** [comment]
Actually, there is https://bugs.gentoo.org/873124 opened against KiCad, which needs to be addressed first. Please don't merge yet.

**Comment by jospezial** [comment]
@zpuskas @MatthewGentoo 
https://gitlab.com/kicad/code/kicad/-/tags/6.0.9
Stable release 6.0.9
That version has also a swig fix.
https://gitlab.com/kicad/code/kicad/-/commit/705570923e9c9e4516c3f3a2f98fd44ca44a607f

**Comment by jospezial** [comment]
Did your builds succeed with USE=ngspice ?
https://gitlab.com/kicad/code/kicad/-/issues/12665

**Comment by zpuskas** [comment]
> Did your builds succeed with USE=ngspice ? https://gitlab.com/kicad/code/kicad/-/issues/12665

Yes it did. The breakage in the aforementioned bug report is due to wxGTK-3.2.0, which is not in the main portage tree yet.

> @zpuskas @MatthewGentoo https://gitlab.com/kicad/code/kicad/-/tags/6.0.9 Stable release 6.0.9 That version has also a swig fix. https://gitlab.com/kicad/code/kicad/-/commit/705570923e9c9e4516c3f3a2f98fd44ca44a607f

Thanks, I'll take a look over the weekend, most likely will replace 6.0.8 if it works with both 4.0.2 and 4.1.0 versions of swig.

**Comment by jospezial** [comment]
> > Did your builds succeed with USE=ngspice ? https://gitlab.com/kicad/code/kicad/-/issues/12665
> 
> Yes it did. The breakage in the aforementioned bug report is due to wxGTK-3.2.0, which is not in the main portage tree yet. However they claim that it builds for them, so I'll check it out on my system sometime.

I only wonder too why [Wayne Stambaugh](https://gitlab.com/stambaughw) was able to build it on debian as reported in that upstream bug.

**Comment by jospezial** [comment]
@zpuskas 
https://bugs.gentoo.org/879945

**Pull request closed without merging**
