### PR TITLE
dev-python/yapf: Bump to version 0.28.0

### PR DESCRIPTION
**Pull request by Flowdalic**
Closes: https://bugs.gentoo.org/693580
Package-Manager: Portage-2.3.69, Repoman-2.3.16
Signed-off-by: Florian Schmaus <flo@geekplace.eu>

### CODE REVIEW

**Comment by juippis** [comment]
@TheChymera check, test and approve/disapprove please :)

**Comment by TheChymera** [comment]
@juippis bumped and tested https://github.com/gentoo/gentoo/pull/12894

**Comment by Flowdalic** [comment]
@TheChymera as far as I can tell, your PR #12984 is identical to mine (minus the whitespace fix and the e-mail address change, which is causing a Warning that there is no matching bugzilla account). Any reason you didn't just ack this PR?

**Comment by TheChymera** [comment]
@Flow didn't see it, went over it really fast and thought this was an issue and juippis asked me to fix it. If it's identical, it means it works, and we should pull yours. Thanks!

Still, shouldn't the copyright line read `1999-2019` instead of `2018-2019`?

**Comment by TheChymera** [comment]
I know I had the same variation in for the previous version, but now that I look at it, it seems pretty nonstandard.

```
chymera@quiethost /usr/portage $ ag "1999-2019" -l | wc -l
16179
chymera@quiethost /usr/portage $ ag "2018-2019" -l | wc -l
27
chymera@quiethost /usr/portage $ ag "2017-2019" -l | wc -l
34
chymera@quiethost /usr/portage $ ag "2016-2019" -l | wc -l
21
chymera@quiethost /usr/portage $ ag "2015-2019" -l | wc -l
9
chymera@quiethost /usr/portage $ ag "2014-2019" -l | wc -l
4
chymera@quiethost /usr/portage $ ag "2013-2019" -l | wc -l
2
```

**Pull request closed without merging**
