### PR TITLE
app-containers global moves

### PR DESCRIPTION
**Pull request by gyakovlev**
as discussed in https://archives.gentoo.org/gentoo-dev/message/67ecdd21af5eaddffd87e6707d54de61

not rushing it but let's get it done sooner than later.

### CODE REVIEW

**Comment by gyakovlev** [comment]
ok mass-move is not sustainable and painful to rebase, I'll move one by one instead. but leaving this for acks for now

**Comment by voyageur** [comment]
That looks like a bug in auto-assignement, it should be on app-emulation/docker maintainers, not x11-plugins/docker :)

**Comment by mgorny** [comment]
> That looks like a bug in auto-assignement, it should be on app-emulation/docker maintainers, not x11-plugins/docker :)

The PR modifies x11-plugins too:
```
diff --git a/x11-plugins/docker/docker-1.5-r2.ebuild b/x11-plugins/docker/docker-1.5-r2.ebuild
index 9f742ebe552d0..4871b7a4c8132 100644
--- a/x11-plugins/docker/docker-1.5-r2.ebuild
+++ b/x11-plugins/docker/docker-1.5-r2.ebuild
@@ -28,5 +28,5 @@ src_compile() {
 }
 
 pkg_postinst() {
-	einfo "To avoid collision with app-emulation/docker, binary was renamed to wmdocker"
+	einfo "To avoid collision with app-containers/docker, binary was renamed to wmdocker"
 }
```

**Comment by olifre** [comment]
> but leaving this for acks for now

I ack the changes to `sys-cluster/charliecloud`. Note that `sys-cluster/charliecloud` itself is also a candidate for the move, similar to others from `sys-cluster` such as `sys-cluster/singularity`.

**Comment by zmedico** [comment]
I ack the changes for all the packages I maintain.

**Review by zmedico — APPROVED** [review]

**Comment by voyageur** [comment]
> > That looks like a bug in auto-assignement, it should be on app-emulation/docker maintainers, not x11-plugins/docker :)
> 
> The PR modifies x11-plugins too:
> 
> ```
> diff --git a/x11-plugins/docker/docker-1.5-r2.ebuild b/x11-plugins/docker/docker-1.5-r2.ebuild
> index 9f742ebe552d0..4871b7a4c8132 100644
> --- a/x11-plugins/docker/docker-1.5-r2.ebuild
> +++ b/x11-plugins/docker/docker-1.5-r2.ebuild
> @@ -28,5 +28,5 @@ src_compile() {
>  }
>  
>  pkg_postinst() {
> -	einfo "To avoid collision with app-emulation/docker, binary was renamed to wmdocker"
> +	einfo "To avoid collision with app-containers/docker, binary was renamed to wmdocker"
>  }
> ```

Thanks mgorny, I only checked the commit messages, not the modified files! Ack for that minor change in x11-plugins/docker

**Comment by gyakovlev** [comment]
thanks all, majority merged.
I'll deal with the rest on 1by1 basis


here's a stupid but useful script I used to do the moves

it does not cover everything, but most:

```bash
#!/bin/bash

set -e
set -x

main() {
        local pkg="${1}"
        [[ -d app-emulation/${pkg} ]] || exit 1
        rg app-emulation/${pkg} || true
        cat app-emulation/${pkg}/metadata.xml
        git mv app-emulation/${pkg} app-containers/${pkg}
        set +x
        sed -i "s@app-emulation/${pkg}@app-containers/${pkg}@g" \
                app-emulation/*/*.ebuild \
                app-emulation/*/metadata.xml \
                app-containers/*/*.ebuild \
                app-containers/*/metadata.xml \
                sys-cluster/*/*.ebuild \
                sys-cluster/*/metadata.xml \
                acct-*/*/*.ebuild \
                acct-*/*/*.ebuild \
                acct-*/*/metadata.xml
        find profiles -type f | grep -v profiles/updates | xargs -n1 sed -i "s@app-emulation/${pkg}@app-containers/${pkg}@g"
        set -x
        git add app-emulation
        git add app-containers
        git add acct-*
        git add sys-cluster
        git add profiles
        echo move {app-emulation,app-containers}/${pkg} >> profiles/updates/4Q-2021
        git add profiles/updates
        git commit -v -m "Move {app-emulation -> app-containers}/${pkg}" --signoff

        rg app-emulation/${pkg} || true
        git status
}
main "${@}"
```

**Pull request closed without merging**
