### PR TITLE
app-editors/scite: Version Bump to 4.4.3.

### PR DESCRIPTION
**Pull request by dermoench42**
Actual enhancements and upstream bugfixes. See
http://www.scintilla.org/ScintillaHistory.html

Signed-off-by: Ervin Peters coder@ervnet.de
Package-Manager: Portage-2.3.99, Repoman-2.3.22

### CODE REVIEW

**Comment by dermoench42** [comment]
"gentoo-ci — PR introduced new issues"
Looking at 'Details' I found nothing related to 'app-editors/scite' or '/scite' ... any hints?

**Comment by dermoench42** [comment]
It is somehow annoying that sometimes I got ask "Why did you make separate pull requests?". I answered "atomic commits!" and got a replay 'not nessesary in this case'. And on this PR I am advised to split it to extremly atomic commits. I wish ther would be more consitency in communication. 
I'm an old man with a limited lifetime and therefore I do not like to waste that time with administrational/managing games.
Don't forget the goal is to provide a working software in a working tree, not the worship of poor documented complex rules. KISS might be an approach, the avoiding of tasks- or processor(you, me) witches also...
Just for your internal discussion.
Closed to continue with separated PRs.

**Comment by juippis** [comment]
Hi, 

sorry for your experience, but in my eyes our policy and standards are pretty clear. You're maybe not that familiar with Git so it can be hard to kind of imagine the git workflow? Please read https://www.gentoo.org/glep/glep-0066.html#splitting-commits

I'll quote and try to explain: 
`Use atomic commits — one commit per logical change.` I listed your logical changes above.
`When doing a version bump, it is usually not reasonable to split every necessary logical change into separate commit since the interim commits would correspond to a broken package. ` This means you can incorporate all of your changes to one commit on a **new ebuild file**, but when modifying **existing** ebuilds, the change should be **visible** and **revertable**. Talk about reverting a broken a commit, if you made **all** those changes in a **single** commit and **some part** of it proves out to be broken requiring reverting, we would lose **all** changes instead of the **one** broken one. 

As for opening new PRs, it'd be best for everyone if you just cleared your current git branch and committed the update here. Since now I will get a new e-mail instead of tracking existing e-mail threads, it will take time before I even see the new PR. Although there are many other members in the project, someone else might see it first. Just saying, you don't **need** to open a new pull request, when you can just use git tools to do the update in **this** PR.

Just a note, and no offense meant, but perhaps you'd like to read a git tutorial to get over these basic tasks?

I'm sorry you feel like your time is wasted, trust me, I don't feel any better about it either. Yes the main point is to have up-to-date working software in the tree, but I also hope you can see from a technical point of view why this particular GLEP was drafted, and why git history/workflow is important to us.

**Comment by dermoench42** [comment]
I have to apologize.
I mixed up the two concepts of PR' and 'Commit' in remembering the documentation, and got angry. You're right I'm still climbing the steep ladder to git concepts and knowledge, therefore reading documentation and tutorials. But the git functionality is abstract and must be applied to a semantic frame of the gentoo tree objecs. The lack of the big picture was my problem. For now I decided to see a branch as something like a 'project', merge/pull requests as a set of working changes in an temporal manner like a 'milestone' or a reached goal and commit as an atomic change related to either one 'abstraction level' xor existential changes to keep the cognitive load low.
To reflect this, I'd cleaned up my branches, delete this branch and will use only a branch called app-editors/scite from now on.
Additionally for information I stumbled (again) over nerd-typical optimised minimal communication since social communication uses pictures and is redundant with to weight and clarify.

Thanks for our work together.

further: https://github.com/gentoo/gentoo/pull/17080

**Pull request closed without merging**
