### PR TITLE
app-admin/mkosi: version bump to v19

### PR DESCRIPTION
**Pull request by YangMame**
new version is released

### CODE REVIEW

**Comment by 257** [comment]
[Split version bumps and ebuild cleanup in separate commits (makes reverting ebuild removals much easier).](https://wiki.gentoo.org/wiki/Gentoo_git_workflow#Atomicity)

**Comment by 257** [comment]
upstream has disabled gentoo tests, did you run tests locally? have a look at `.github/workflows/ci.yml`

**Comment by YangMame** [comment]
> upstream has disabled gentoo tests, did you run tests locally? have a look at `.github/workflows/ci.yml`

oh...seems like it really don't work anymore, it can't resolve dns when fetch snapshot
```
mkosi --debug --debug-shell --with-network -d gentoo --autologin build 
...
 * PGP verification method: gemato
 * Fetching most recent snapshot ...
 * Trying to retrieve 20231204 snapshot from http://distfiles.gentoo.org ...
 * Fetching file gentoo-20231204.tar.xz.md5sum ...
--2023-12-05 08:43:24--  http://distfiles.gentoo.org/snapshots/gentoo-20231204.tar.xz.md5sum
Resolving distfiles.gentoo.org... Failed to connect to /run/systemd/resolve/io.systemd.Resolve: No such file or directory
failed: Temporary failure in name resolution.
wget: unable to resolve host address ‘distfiles.gentoo.org’
...
```

**Comment by YangMame** [comment]
will have a try to fix it...

**Comment by Flowdalic** [comment]
Friendly ping

**Pull request closed without merging**
