### PR TITLE
Bump mail-client/evolution and its dependencies.

### PR DESCRIPTION
**Pull request by plaes**
It would be nice to get "stable" version to portage.

### CODE REVIEW

**Comment by mgorny** [comment]
@EvaSDK @tetromino @pacho2 @Tranquility

**Comment by pacho2** [comment]
This should go with the rest of Gnome 3.18 as done with ever major Gnome version

**Comment by Tranquility** [comment]
LGTM and if I remember correctly you have push access to the overlay. @plaes can you please push it to the overlay?

**Comment by plaes** [comment]
@Tranquility Ok, did that, though I would like to start moving evo-3.19 to overlay ;)

**Comment by EvaSDK** [comment]
Our users want all of Gnome 3.18, not just evolution so even though it works as a mostly stand-alone app, it's ecosystem makes it appear as part of a whole that we cannot ship right now. Imho this would create more noise for us.

**Comment by Tranquility** [comment]
I will close the PR. Users who want to install evolution before the new release lands in the tree can easily install it from the overlay.

**Pull request closed without merging**
