### PR TITLE
sys-apps/kexec-tools: Sync EAPI=8 to live ebuild & add 2.0.28

### PR DESCRIPTION
**Pull request by Leo3418**
As of now, the latest version of `kexec-tools` in `::gentoo` is 2.0.24, which no longer seems to work with the latest kernels (6.6+).  2.0.28 works with the latest kernels; I have been testing it for a week.

At the same time, bump EAPI of the live ebuild to 8, which other non-live ebuilds of `sys-apps/kexec-tools` have been using already.

### CODE REVIEW

**Comment by thesamesam** [comment]
OK. But if you're using this, could you consider co-maintaining it please?

**Comment by Leo3418** [comment]
> OK. But if you're using this, could you consider co-maintaining it please?

Sure.  For now, I'm happy to make a PR for every new upstream release of this package as long as I have time.  I'm not formally a proxy maintainer yet, but I could apply to be one if that helps make the process easier and becoming a p-m per se is also easy and fast.  I'm still hoping to have enough time to finish my paused Gentoo dev recruitment process; once I become a dev, I'll be certainly happy to co-maintain this package.

**Comment by thesamesam** [comment]
We know you, so all you have to do is follow https://wiki.gentoo.org/wiki/Project:Proxy_Maintainers/User_Guide#Proxied_maintainer_in_metadata.xml. The rest sounds good to me too!

**Comment by Leo3418** [comment]
Thanks @thesamesam!  Should a proxy maintainer bug be created for me as well?

**Comment by thesamesam** [comment]
They're created regularly on Sundays in batches. Thanks!

**Pull request closed without merging**
