### PR TITLE
app-doc/zeal: bump version to 0.3.1

### PR DESCRIPTION
**Pull request by soredake**
EAPI bump.
Added ~arm keyword.

### CODE REVIEW

**Comment by monsieurp** [comment]
hey. care to provide a log for the build on the arm platform?

**Comment by soredake** [comment]
@monsieurp for now i can't, sorry, but according to debian packages https://packages.debian.org/sid/zeal zeal can work on arm

**Comment by monsieurp** [comment]
Hi. The maintainer is not happy with the changes introduced by this PR so he will take it from there. I have reverted it.
@soredake: feel free to file another one based on @Tranquility's comments.
@Tranquility: you can merge this one or wait for @soredake's new PR.
Thanks!

**Comment by Tranquility** [comment]
@soredake sorry we had a little misunderstanding. I am perfectly happy with the changes. thanks you for you pull request. 

I will revert the revert again as soon as I am in front of a computer or maybe @monsieurp is faster and will do it for me.

**Comment by Tranquility** [comment]
It looks like the icons and desktop file are missing in the new version. I need to have a closer look to see what is going on.

**Pull request closed without merging**
