### PR TITLE
net-misc/ena-driver: Add upstream 2.5.0 version

### PR DESCRIPTION
**Pull request by gkelly**
- Copied from `2.2.3` ebuild.
- Tested by building with `linux-5.10.49-gentoo-r1` kernel.
- Removes `dodoc` line from previous ebuild, those files don't appear to be present.

### CODE REVIEW

**Comment by gkelly** [comment]
Just realized that this has an `RDEPEND` on unzip, while it doesn't use a zip file. I'll take that out.

**Comment by sormy** [comment]
The README file is presented but was renamed to `README.rst`

**Comment by sormy** [comment]
Also, might want to update `KEYWORDS` and include `~arm64`. It is supported and buildable on arm64 as well.

**Comment by AndrewAmmerlaan** [comment]
Closing since it seems the objective of this PR has been reached and it is now obsolete. Please re-open if this is not the case.

**Pull request closed without merging**
