### PR TITLE
profiles/package.mask: last rite dev-java/{gin,gwt,validation-api}

### PR DESCRIPTION
**Pull request by vaukai**
@fordfrog @Flowdalic

### CODE REVIEW

**Comment by Flowdalic** [comment]
@markwright as you are listed as maintainer for dev-java/gwt and dev-java/gin: any opinions on last riting them?

**Comment by vaukai** [comment]
> @markwright as you are listed as maintainer for dev-java/gwt and dev-java/gin: any opinions on last riting them?

Ping.

**Comment by vaukai** [comment]
> > @markwright as you are listed as maintainer for dev-java/gwt and dev-java/gin: any opinions on last riting them?
> 
> Ping.

Ping.

**Comment by vaukai** [comment]
Maintainer unresponsive, closing.

**Pull request closed without merging**
