### PR TITLE
enable pypy3 on smart-live-rebuild

### PR DESCRIPTION
**Pull request by ArsenArsen**
this enables smart-live-rebuild to be used when pypy3 is used to run emerge

NOTE: I didn't try FEATURES=test due to being out of time right now, I can do that before merging if so desired.

### CODE REVIEW

**Comment by thesamesam** [comment]
Please do, I suspect we haven't added it at some point for a reason.

**Comment by ArsenArsen** [comment]
Ah, that might be why, pkgcore doesn't have pypy3. I wonder whether this is an oversight or a lack of support

**Comment by thesamesam** [comment]
gentoopm only needs at least one of portage or pkgcore.

It's deeper than that, it's because even for portage, despite it having pypy3, the dep can't be satisfied on all profiles:
```
$ grep -rsin "pypy3" profiles/ | grep selinux
profiles/features/selinux/package.use.mask:24:sys-apps/portage python_targets_pypy3
profiles/features/selinux/package.use.mask:25:app-portage/elogv python_targets_pypy3
profiles/features/selinux/package.use.mask:26:app-portage/gentoolkit python_targets_pypy3
profiles/features/selinux/package.use.mask:27:app-portage/layman python_targets_pypy3
profiles/features/selinux/package.use.mask:28:app-portage/repoman python_targets_pypy3
```

The mask is:
```

# Brian Dolbec <dolsen@gentoo.org> (2014-09-17)
# mask pypy for several utilities due to incompatibility with libselinux
sys-apps/portage python_targets_pypy3
app-portage/elogv python_targets_pypy3
app-portage/gentoolkit python_targets_pypy3
app-portage/layman python_targets_pypy3
app-portage/repoman python_targets_pypy3
```

I have no idea what the incompatibility is. It kind of makes me think maybe libselinux and friends never got tested w/ pypy3. Anyway, we can just throw smart-live-rebuild and gentoopm into that mask, and we're good.

**Comment by ArsenArsen** [comment]
tests appear to pass on pypy3 also

**Pull request closed without merging**
