### PR TITLE
app-crypt/pinentry: 0.9.7 version bump, fix description length

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/crypto

**Comment by mgorny** [comment]
Nice piece of work you did there, btw.

**Comment by alonbl** [comment]
Hi,
Thank you for contributions.
Impossible to review in github, as no diff of previous ebuild is available.
Please file a bug and attach diffs.
Please separate diff of fixing description from version bump, these are not related.
Please avoid doing house keeping, we will do this at our own time.
Thanks!

**Comment by mgorny** [comment]
@alonbl, I must be using a different GitHub than you are since I clearly see a proper diff there…

**Comment by mgorny** [comment]
(in 'Files changed' tab)

**Comment by alonbl** [comment]
@mgorny: do you magically see what changed in the versionbump based on previous version?

**Comment by a17r** [comment]
@alonbl: I specifically removed 0.9.6-r5 because it has minimal diff over -r6 and shouldn't be used anyway. So you can look at it as if it were a diff over -r6 save for the lines
https://github.com/gentoo/gentoo/pull/465/files#diff-1787e4af6428863e779ec07881c7601bR45
and
https://github.com/gentoo/gentoo/pull/465/files#diff-1787e4af6428863e779ec07881c7601bR93

**Comment by a17r** [comment]
See also: https://bugs.gentoo.org/show_bug.cgi?id=568172

**Comment by monsieurp** [comment]
K_F bumped this package already and obsoleted this PR: https://gitweb.gentoo.org/repo/gentoo.git/commit/?id=3905265ef9ba1c5ce6f1ea6fbd556aadb0871da2. Closing.

**Pull request closed without merging**
