### PR TITLE
dev-java/easymock: EAPI 7

### PR DESCRIPTION
**Pull request by vaukai**
Patch out missing dependency on "com.google.dexmaker.stock"

Package-Manager: Portage-3.0.13, Repoman-3.0.2
Signed-off-by: Volkmar W. Pogatzki <gentoo@pogatzki.net>

### CODE REVIEW

**Comment by vaukai** [comment]
@fordfrog Do you see a chance to get the missing "com.google.dexmaker.stock" packaged?  If not we need to keep it patched out.

**Comment by fordfrog** [comment]
@vaukai examples are not installed auto-magically, you have to copy that `src_install` from the current ebuild to install examples.

**Comment by vaukai** [comment]
> @vaukai examples are not installed auto-magically, you have to copy that `src_install` from the current ebuild to install examples.

Not that simple.  Upstream moved to hosting their code on Github and the tarball there does not have the samples.jar or examples directoty.  Should I switch back to the Sourceforge-hosted tarball?

**Comment by fordfrog** [comment]
@vaukai you can keep it this way, but then you should drop `examples` use flag as it is not used anymore.

**Comment by vaukai** [comment]
> @vaukai you can keep it this way, but then you should drop `examples` use flag as it is not used anymore.

Done.

**Comment by fordfrog** [comment]
@vaukai cool, thanks! :-)

**Pull request closed without merging**
