### PR TITLE
Telegram bump

### PR DESCRIPTION
**Pull request by mipseb**
version bump for telegram-desktop-bin

### CODE REVIEW

**Comment by joecool1029** [comment]
You accidentally attached the bitwarden-bin bump commit to this one. Also look into using pkgdev commit to commit with, it'll detect the missing manifest files and generate them as needed.

**Comment by mipseb** [comment]
I just configured pkgdev and fixed a different package where I did the same thing but with two other packages left over, I am sincerely sorry. I will be fixing this as well.

**Comment by thesamesam** [comment]
There was already a PR for this, please don't snipe things if they have a maintainer and active PR already: https://github.com/gentoo/gentoo/pull/34192.

**Comment by henning-schild** [comment]
Not sure what happened here. A new contributor learned how to do things and made a few mistakes but finally got a few patches merged.

The telegram package usually needs some time to settle so i often take a slow approach. In the last few days we have seen several more updates from upstream, which i will deal with in a few days.

Anyhow, welcome @mipseb and thanks to @joecool1029 and others who made this one happen.

**Comment by thesamesam** [comment]
Yes, but a few PRs were done at once when this one could've been skipped as yours was already pending. It's worth carefully doing them right and not rushing to do many.

**Pull request closed without merging**
