### PR TITLE
dev-php/composer: Add bump to 1.3.2

### PR DESCRIPTION
**Pull request by GuillaumeSeren**
Hey !
This is the PR for the composer -1.3.2 with test suite,
it works well on my setup but I expect some rework to be needed due to the amount of related packages.

There is a Gentoo-Bug: [608136](https://bugs.gentoo.org/show_bug.cgi?id=608136)

### CODE REVIEW

**Comment by GuillaumeSeren** [comment]
I missed two phpunit packages, so here they are
* dev-php/phpunit-php-text-template
* dev-php/phpunit-mock-objects

**Comment by GuillaumeSeren** [comment]
So I started fixing qa, and removing packages that are not already in the tree (to add them later),
and adding missing medata file.

I am a bit stuck on that one
```
dev-php/phpunit-mock-objects/phpunit-mock-objects-3.4.3.ebuild: DEPEND: ~amd64(default/linux/amd64/13.0)
['>=dev-php/phpunit-php-text-template-1.2']
```

**Comment by GuillaumeSeren** [comment]
I have fixed the QA of theseer-DirectoryScanner, zetacomponents-console-tools, zetacomponents-base, zetacomponents-unit-test packages.

**Comment by GuillaumeSeren** [comment]
Hey,
it seems I managed to get the bot happy, can someone have a look to the PR,
might probably be something to find, @mgorny @hydrapolic @orlitzky 🍻

**Comment by GuillaumeSeren** [comment]
Hey,
it seems I managed to get the bot happy, can someone have a look to the PR,
might probably be something to find, @mgorny @hydrapolic @orlitzky 🍻

**Comment by hydrapolic** [comment]
Thanks for the PR @GuillaumeSeren.

Just merging composer yields this error:
```
$ composer -V
PHP Fatal error:  Uncaught RuntimeException: File not found: '/usr/share/php/phpunit-mock-object/autoload.php' in /usr/share/php/Fedora/Autoloader/functions.php:29
Stack trace:
#0 /usr/share/php/Fedora/Autoloader/Dependencies.php(65): Fedora\Autoloader\requireFile('/usr/share/php/...')
#1 /usr/share/php/Fedora/Autoloader/Dependencies.php(86): Fedora\Autoloader\Dependencies::process(Array, true)
#2 /usr/share/php/Composer/Composer/autoload.php(25): Fedora\Autoloader\Dependencies::required(Array)
#3 /usr/bin/composer(8): require('/usr/share/php/...')
#4 {main}
  thrown in /usr/share/php/Fedora/Autoloader/functions.php on line 29

Fatal error: Uncaught RuntimeException: File not found: '/usr/share/php/phpunit-mock-object/autoload.php' in /usr/share/php/Fedora/Autoloader/functions.php:29
Stack trace:
#0 /usr/share/php/Fedora/Autoloader/Dependencies.php(65): Fedora\Autoloader\requireFile('/usr/share/php/...')
#1 /usr/share/php/Fedora/Autoloader/Dependencies.php(86): Fedora\Autoloader\Dependencies::process(Array, true)
#2 /usr/share/php/Composer/Composer/autoload.php(25): Fedora\Autoloader\Dependencies::required(Array)
#3 /usr/bin/composer(8): require('/usr/share/php/...')
#4 {main}
  thrown in /usr/share/php/Fedora/Autoloader/functions.php on line 29
```

After installing dev-php/phpunit-mock-objects it works properly.
```
$ composer -V
Composer 1.3.2 2017-01-27 18:23:41
```

**Comment by GuillaumeSeren** [comment]
Hey @hydrapolic 
I think I cleaned a bit too much, I will check it thanks for the feedback.

**Comment by GuillaumeSeren** [comment]
Ok I fixed composer autoloader, and I also fixed symfony-cache
```
index b021eb2769..3197b6e45c 100644
--- a/dev-php/symfony-cache/symfony-cache-3.1.10.ebuild
+++ b/dev-php/symfony-cache/symfony-cache-3.1.10.ebuild
@@ -41,10 +41,10 @@ src_prepare() {
                cp "${FILESDIR}"/autoload.php "${S}"/autoload-test.php || die
                sed -i -e "s:__DIR__:__DIR__.'/src':" "${S}"/autoload-test.php || die
                # Some of the dependencies are not packaged yet
-               sed -i -e "s:));:\t\'/Cache/IntegrationTests/autoload.php\',\n));:" "${S}"/autoload-test.php
-               sed -i -e "s:));:\t\'/Doctine/Cache/autoload.php\',\n));:" "${S}"/autoload-test.php
-               sed -i -e "s:));:\t\'/Doctrine/dbal/autoload.php\',\n));:" "${S}"/autoload-test.php
-               sed -i -e "s:));:\t\'/nrk/predis/autoload.php\',\n));:" "${S}"/autoload-test.php
+               sed -i -e "s:));:\t\$vendorDir . \'/Cache/IntegrationTests/autoload.php\',\n));:" "${S}"/autoload-test.php
+               sed -i -e "s:));:\t\$vendorDir . \'/Doctine/Cache/autoload.php\',\n));:" "${S}"/autoload-test.php
+               sed -i -e "s:));:\t\$vendorDir . \'/Doctrine/dbal/autoload.php\',\n));:" "${S}"/autoload-test.php
+               sed -i -e "s:));:\t\$vendorDir . \'/nrk/predis/autoload.php\',\n));:" "${S}"/autoload-test.php
        fi
 }
```

**Comment by GuillaumeSeren** [comment]
Hey,
I have rebased the PR to adapt to new packages in gentoo with the adding of phpunit

**Comment by GuillaumeSeren** [comment]
Well I tested it more and some packages have changed name (sebastianbergman -> sebastian) so I have a bit more work to do, will update here soon.

**Comment by orlitzky** [comment]
Hi Guillaume.. this is simply too much for me to review all at once. I keep telling myself I'll find the time but I never do.

How would it look if you did only the composer version bump, and held off on the tests for a separate pull request? I think the version bump alone would be easy to review, and then I could consider the test additions separately. Then if that takes me longer to review, it's not as critical for people.

**Comment by orlitzky** [comment]
For example... I have a few minutes right now, but not a few hours. I would like to cherry-pick the symfony-process-2.x version bump, but since it introduces a test suite, I can't without reviewing all the other dependencies at the same time =)

**Comment by GuillaumeSeren** [comment]
@orlitzky Yes after rebasing there more things to review so let's bump it then add test later.

**Comment by GuillaumeSeren** [comment]
@orlitzky ok I will close this PR and make a new one for the last composer version (only bump without tests) for the composer-1.4.1

**Comment by GuillaumeSeren** [comment]
Here is the issue for bumping the 1.4.1 https://bugs.gentoo.org/show_bug.cgi?id=613898

**Pull request closed without merging**
