### PR TITLE
dev-php/phpunit: version bump, fix bug 639656

### PR DESCRIPTION
**Pull request by kitsunenokenja**
This is the continuation of PR #6783 which was improperly closed during the breach.

Review is required from a member of @gentoo/php to complete. M. Orlitzky has been a major contributor in getting this PR completed but is no longer available.

### CODE REVIEW

**Comment by Whissi** [comment]
Please update the PR. Once updated, we will merge in time (ping me if I shouldn't notice).

**Comment by lkraav** [comment]
Hi all. Thanks for the work thus far. I discovered today I can't unmerge PHP 7.1, because old phpunit-5 depends on it.

What would it take to get this PR to the finish line?

**Comment by Whissi** [comment]
@kitsunenokenja So could you please update and rebase (maybe re-create) this PR? Then we can merge...

**Comment by kitsunenokenja** [comment]
Great, there is finally interest in finishing this. I didn't want to do any updates only to see it grow stale another year and the majority of the proposed ebuilds would be obsolete for a second time.

This one's got a lot of deps, so I'll have to sweep through the whole lot and update accordingly.

**Comment by Whissi** [comment]
Thank you, I'll promise we will merge the new one in time :)

**Comment by kitsunenokenja** [comment]
Hey, I'm zooming through this dependency list. I think I will have an update in a day or two.

I am finding some old packages depending on PHP 7.0 which was dropped from Portage. I may make a separate PR requesting their removal to help tidy up further. Focusing on phpunit for the time being.

**Comment by kitsunenokenja** [comment]
ebuilds released. I could use a hand or two testing these!

**Comment by kitsunenokenja** [comment]
`repoman` compelled me to drop the phpunit5 ebuilds as it had numerous dep resolution issues and registered as fatal by the tool.

**Comment by lkraav** [comment]
@kitsunenokenja looking much forward to testing these. I browsed https://github.com/gentoo/gentoo/pull/9090/files#diff-25c0ef0711203a681af910f59fb23ffb and noticed PHPUnit 7.x is not there.

Unfortunately, some projects need additional time to catch up w/ PHPUnit 8, which includes bc breaks https://core.trac.wordpress.org/ticket/46149

Is there a way to get PHPUnit 7 in this PR as well?

**Comment by kitsunenokenja** [comment]
No problem at all. Added PHPUnit 7.5.6 and fixed up the ebuild for 8 to point to 8.0.4. I hadn't noticed at first that a patched version of 8 was already available.

It's likely I will need to do more rebasing based on testing. Please keep 'em coming!

**Comment by lkraav** [comment]
Hi @orlitzky. I see "review requested" has pointed to you, do you think it's possible for you to take a look or who else could do it?

**Comment by lkraav** [comment]
@kitsunenokenja it actually looks like `phpunit` Manifest is simply missing

```
6.5.5 | DeprecatedChksum | "phpunit-6.5.5.tar.gz" uses deprecated checksum set: ; expected: blake2b, sha512, size
-- | -- | --
  | MissingManifest | distfile missing from Manifest: [ phpunit-6.5.5.tar.gz ]
```

https://qa-reports.gentoo.org/output/gentoo-ci/87a2f49/output.html#dev-php/phpunit

**Comment by orlitzky** [comment]
> Hi @orlitzky. I see "review requested" has pointed to you, do you think it's possible for you to take a look or who else could do it?

I don't have the motivation to finish this. Composer packages are fundamentally broken and a huge, ongoing, waste of time to fix. At any point in time I'd rather be exercising, or reading, or working on a non-Composer package, or doing research, or getting drunk, or basically anything else.

The good news is, you don't need anyone in particular to review it -- just someone with a few tens of hours to throw away every time there's a minor version bump. The autoloaders we ship are basically a list of class names and the associated files that are used by a package. Manually searching through the files and listing all of the classes is obviously not a good way to do things, and is highly error-prone, and needs to be re-done for every version bump. Most of the packaging work is just testing that the list is correct; that is, that `autoload.php` actually works. Since PHP is a scripting language, and since composer encourages you to bundle a thousand junk libraries with no QA or test suites, you have to spend a few hours manually testing each one (again, for every minor version bump) to ensure that all of the code paths have been visited.

If you can find anyone willing to do that, they don't need to be a member of the PHP team to review this.

**Comment by lkraav** [comment]
Yep, sounds about right. Maybe the better move is to drop most such packages from the tree? Doesn't sound like there's a future in it. Everyone can just install things directly.

**Comment by orlitzky** [comment]
> Yep, sounds about right. Maybe the better move is to drop most such packages from the tree? Doesn't sound like there's a future in it. Everyone can just install things directly.

We've only added one such package that wasn't already in the tree; namely composer itself. And all of that work was contributed by another user.

Aside from that, I think PHPUnit is the only one we've spent much effort on because it's so crucial. PHPUnit is required to run the test suite for anything under dev-php in Gentoo. We don't want to disable all of the test suites in order to drop PHPUnit, but for any other package, you're right.

**Comment by mgorny** [comment]
So what do we do here?

**Comment by lkraav** [comment]
Looks like fixed out of nowhere by @bajoyasujoya and @Whissi? :tada: :1st_place_medal:

**Comment by juippis** [comment]
Sorry but looks like it's better to start over than to continue with this.

**Pull request closed without merging**
