### PR TITLE
media-libs/libid3tag: Bump to 0.16.0 (Tenacity fork)

### PR DESCRIPTION
**Pull request by lanodan**
Signed-off-by: Haelwenn (lanodan) Monnier <contact@hacktivis.me>

### CODE REVIEW

**Comment by Be-ing** [comment]
Please update to 0.16.1. I noticed the CMake config file was broken and the pkgconfig file was installed to a different path than what distros were using before (was `libid3tag.pc` in 0.16.0, fixed to `id3tag.pc` in 0.16.1).

**Comment by fordfrog** [comment]
@lanodan thanks!

**Comment by Be-ing** [comment]
@fordfrog why did you ignore my comment? Please update to 0.16.1 immediately; this likely broke something.

**Comment by fordfrog** [comment]
@Be-ing what do you mean exactly?

```
# equery meta libid3tag
 * media-libs/libid3tag [gentoo]
Maintainer:  sound@gentoo.org (Gentoo Sound project)
Upstream:    Remote-ID:   mad ID: sourceforge
Homepage:    https://github.com/tenacityteam/libid3tag
Location:    /var/db/repos/gentoo/media-libs/libid3tag
Keywords:    0.15.1b-r4:0: amd64 arm arm64 ppc ppc64 sparc x86 ~alpha ~amd64-linux ~hppa ~ia64 ~mips ~ppc-macos ~riscv ~s390 ~sparc-solaris ~sparc64-solaris ~x64-macos ~x64-solaris ~x86-linux ~x86-solaris
Keywords:    0.16.1-r1:0/0.16.1: ~alpha ~amd64 ~arm ~arm64 ~hppa ~ia64 ~mips ~ppc ~ppc64 ~riscv ~s390 ~sparc ~x86
License:     GPL-2

```

**Comment by lanodan** [comment]
[2021-08-16 07:14:37-0700] Be:
> @fordfrog why did you ignore my comment? Please update to 0.16.1 immediately; this likely broke something.

The update to 0.16.1 was done right after merging the commit in this PR.

**Comment by Be-ing** [comment]
Okay thanks for taking care of that. I did not see any reference to 0.16.1 in this PR before so I did not see that it was updated again.

**Pull request closed without merging**
