### PR TITLE
www-client/qutebrowser: fix desktop menu file name

### PR DESCRIPTION
**Pull request by steils**
Package-Manager: Portage-2.3.62, Repoman-2.3.12
Signed-off-by: Stefan Strogin <stefan.strogin@gmail.com>

### CODE REVIEW

**Comment by jsbronder** [comment]
So this was changed to to https://github.com/gentoo/gentoo/pull/11139#issuecomment-467371103, which links against https://github.com/qutebrowser/qutebrowser/pull/4547 where @ykgmfq quotes the Freedesktop Standard:
> The name of the desktop entry should follow the "reverse DNS" convention: it should start with a reversed DNS domain name controlled by the author of the application, in lower case. The domain name should be followed by the name of the application, which is conventionally written with words run together and initial capital letters (CamelCase). For example, if the owner of example.org writes "Foo Viewer", they might choose the name org.example.FooViewer, resulting in a file named org.example.FooViewer.desktop.

So it seems that according to the standard, this is the right filename.  However, on my machine only zathura is actually complying...

Let me know what you think.

**Comment by steils** [comment]
> Let me know what you think.

I think that after this change `xdg-mime` gone mad like this:

```
$ xdg-settings get default-web-browser                    
firefox-bin.desktop
$ xdg-settings set default-web-browser qutebrowser.desktop
$ xdg-settings get default-web-browser                    
firefox-bin.desktop
```

```
$ xdg-mime default qutebrowser.desktop text/html
$ xdg-mime query default text/html
firefox-bin.desktop
```

Because `xdg-mime` couldn't parse the line `text/html=qutebrowser.desktop` in my `~/.config/mimeapps.list` and went further to `/usr/share/applications/mimeinfo.cache` where it found the line `text/html=firefox-bin.desktop;qutebrowser.desktop;FBReader.desktop;firefox.desktop;`.

I debugged it a little and found that in `xdg-mime` the function `desktop_file_to_binary()` called from `check_mimeapps_list()` couldn't find the qutebrowser's binary.  `update-desktop-database` and `update-mime-database` didn't help.

**Comment by ykgmfq** [comment]
```
> xdg-settings set default-web-browser firefox.desktop
> xdg-settings get default-web-browser
firefox.desktop
> xdg-mime query default text/html
firefox.desktop
> xdg-settings set default-web-browser org.qutebrowser.qutebrowser.desktop
> xdg-settings get default-web-browser
org.qutebrowser.qutebrowser.desktop
> xdg-mime query default text/html
org.qutebrowser.qutebrowser.desktop
```
I don't actually use Gentoo, but this works as expected with the flatpak package.

**Comment by steils** [comment]
I am not against renaming the desktop file as such. But as a user I expect 1) that after the upgrade my MIME database and cache is updated, so that qutebrowser stays my default browser; 2) at least there should be a notification in `pkg_postinst()` about the renaming. If 1) is not possible, I would propose to keep the file name intact (in the distro).

**Comment by steils** [comment]
@jsbronder The default browser changed for me from `qutebrowser.desktop` to `firefox-bin.desktop` without any notification, after upgrading qutebrowser from 1.6.3 to 1.7.0 :/

**Comment by juippis** [comment]
Is this PR still relevant? I see qutebrowser has been dropped into m-n so at least you can merge this on your own @steils

**Pull request closed without merging**
