### PR TITLE
virtualx.eclass: use 'Xvfb -displayfd ...' and other minor optimizations

### PR DESCRIPTION
**Pull request by mgorny**

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/x11

**Comment by thesamesam** [comment]
I'd send this to the ML when you're ready.

**Comment by mgorny** [comment]
The previous version was wrong and left sandbox disabled for command. I've instead tried leaving sandbox on and nothing seems to break.

**Review by juippis — APPROVED** [review]
firefox[pgo] still works.

**Pull request merged**
