### PR TITLE
pecl-memcached: bump to 3.2.0 with new memcached library

### PR DESCRIPTION
**Pull request by hydrapolic**
Tests pass on ~amd64.

```
--- pecl-memcached-3.2.0.ebuild 2022-05-16 16:38:42.409036198 +0000
+++ pecl-memcached-3.2.0-r1.ebuild      2022-05-16 16:40:05.026417238 +0000
@@ -21,7 +21,7 @@
 
 RESTRICT="!test? ( test )"
 
-COMMON_DEPEND=">=dev-libs/libmemcached-1.0.14[sasl(-)?]
+COMMON_DEPEND="|| ( dev-libs/libmemcached-awesome[sasl(-)?] >=dev-libs/libmemcached-1.0.14[sasl(-)?] )
        sys-libs/zlib
        igbinary? ( dev-php/igbinary[php_targets_php7-4(-)?,php_targets_php8-0(-)?,php_targets_php8-1(-)?] )
 "
```

### CODE REVIEW

**Comment by thesamesam** [comment]
If memcached-awesome is preferred, we should put it first in || ( ... ). Could you rebase?

**Comment by hydrapolic** [comment]
> If memcached-awesome is preferred, we should put it first in || ( ... ). Could you rebase?

I put it secondary since it's a new package, but I've no problem with reversing the order. Will do.

**Comment by hydrapolic** [comment]
@thesamesam it's ready.

**Comment by hydrapolic** [comment]
Thank you @thesamesam

**Pull request closed without merging**
