### PR TITLE
app-containers/buildah: add 1.33.6

### PR DESCRIPTION
**Pull request by rahilarious**
Mod Bumps:
x/crypto 0.15.0 -> 0.17.0
x/sys 0.14.0 -> 0.15.0
x/term 0.14.0 -> 0.15.0

### CODE REVIEW

**Comment by zmedico** [comment]
Thanks!

**Comment by rahilarious** [comment]
> Thanks!

Updated bug https://bugs.gentoo.org/924456 to stabilize 1.33.6 instead of 1.33.5

**Comment by zmedico** [comment]
> > Thanks!
> 
> Updated bug https://bugs.gentoo.org/924456 to stabilize 1.33.6 instead of 1.33.5

Hmm, that's rushing it since it's only been released for 2 days. They already stabilized 1.33.5 for amd64. Maybe we should just stabilize 1.33.5 for now.

**Comment by rahilarious** [comment]
> > > Thanks!
> > 
> > 
> > Updated bug https://bugs.gentoo.org/924456 to stabilize 1.33.6 instead of 1.33.5
> 
> Hmm, that's rushing it since it's only been released for 2 days. They already stabilized 1.33.5 for amd64. Maybe we should just stabilize 1.33.5 for now.

In x/crypto mod bump, there might be security fixes which they'll announce later and then we'll have to stabilize again.  😅

But however you see fit.

**Comment by zmedico** [comment]
> > > Updated bug https://bugs.gentoo.org/924456 to stabilize 1.33.6 instead of 1.33.5
> > 
> > 
> > Hmm, that's rushing it since it's only been released for 2 days. They already stabilized 1.33.5 for amd64. Maybe we should just stabilize 1.33.5 for now.
> 
> In x/crypto mod bump, there might be security fixes which they'll announce later and then we'll have to stabilize again. 😅

That's okay, since it will give 1.33.6 a little more time in ~arch just in case there are any issues.

> But however you see fit.

I went ahead and rolled the stable request back to 1.33.5 for now. Thanks!

**Pull request closed without merging**
