### PR TITLE
java-pkg-simple.eclass: Implement java-pkg-simple-src_test.

### PR DESCRIPTION
**Pull request by monsieurp**
This is a first crack at https://bugs.gentoo.org/show_bug.cgi?id=564158. It
will probably need more love. For the time being, this commit looks after the
testing part of the request, that is bullet point number 2.

### CODE REVIEW

**Comment by monsieurp** [comment]
@gentoo/java will be handling this PR.

**Comment by hasufell** [comment]
great we still have a broken depgraph

**Comment by chewi** [comment]
@hasufell, nothing to do with us!

**Comment by hasufell** [comment]
> @hasufell, nothing to do with us!

I know :kiss:

**Comment by chewi** [comment]
For anyone who's just tuned in, we've discussed this on IRC and several improvements are needed. Primarily it needs to handle resources and do a better job of selecting which test classes to run.

**Comment by monsieurp** [comment]
We'll revisit this PR.. later.

**Pull request closed without merging**
