### PR TITLE
www-apps/gitea: version bump to 1.6.3

### PR DESCRIPTION
**Pull request by xdch47**
Closes: https://bugs.gentoo.org/672146
Signed-off-by: Felix Neumärker <xdch47@posteo.de>
Package-Manager: Portage-2.3.51, Repoman-2.3.11

### CODE REVIEW

**Comment by hydrapolic** [comment]
Thanks for the bump, can you please update to version 1.6.2? Just tested on my small instance and it works fine. Could you please also address https://bugs.gentoo.org/671596?

**Comment by xdch47** [comment]
Bump to 1.6.3

**Comment by hydrapolic** [comment]
Thanks, i'll test and report back.

**Comment by hydrapolic** [comment]
Thanks for the bump, tested your ebuild with 1.6.4 and it works fine on amd64 with openrc (mysql).

**Comment by xdch47** [comment]
… 1.7.1 has been released in the meantime

**Comment by xdch47** [comment]
See https://github.com/gentoo/gentoo/pull/10947

**Comment by xdch47** [comment]
Closed - duplicates with #10947

**Pull request closed without merging**
