### PR TITLE
sci-mathematics/topcom: new version

### PR DESCRIPTION
**Pull request by Alessandro-Barbieri**
* EAPI 7
* build dynamic libraries instead of static
* respect `*FLAGS`
* do not build with debug symbols

Package-Manager: Portage-2.3.87, Repoman-2.3.20
Signed-off-by: Alessandro Barbieri <lssndrbarbieri@gmail.com>

### CODE REVIEW

**Comment by kiwifb** [comment]
Hi Alessandro, I see you have fixed compilation with newer cddlib. I also see you just pass `--disable-static` can you expand on why? I must say with the current ebuild with `--disable-static` no library ends up being installed because there are only static one produced. Does your ebuild install those static libraries? Should we produce shared ones for an hypothetical downstream? The headers are shipped so I believe we should have some library as well.

**Comment by Alessandro-Barbieri** [comment]
I see an /usr/lib64/libTOPCOM.so.0.0.0 installed by my ebuild

**Comment by kiwifb** [comment]
That's interesting, there is no such thing when using the current 0.17.7 ebuild. This is an improvement. All around, I think your ebuild and patch are better than the current stuff in the tree. I wish I could merge it.

**Comment by orlitzky** [comment]
This looks good to me except for one thing: the examples really should be installed to the documentation directory. I'm guessing you wanted to move them because they're unusable when compressed? If so, you can disable the compression with
```bash
docompress -x "/usr/share/doc/${PF}/examples"
```

That's a fairly common occurrence, and you can see an example in sci-mathematics/glpk if necessary.

**Comment by orlitzky** [comment]
You actually still have to `dodoc -r` the examples _in addition to_ the call to `docompress`, but I just fixed that myself to avoid another back-and-forth on github. Thanks for the math/science help!

**Comment by kiwifb** [comment]
I thought for a moment you merged without fixing that 👍

**Comment by kiwifb** [comment]
Fix html doc installation issue at #19936 - no rev-bump since it is an issue preventing installation in the ebuild current shape.

**Pull request closed without merging**
