### PR TITLE
dev-python/blessings: add missing setuptools DEPEND, EAPI=6

### PR DESCRIPTION
**Pull request by sbraz**

### CODE REVIEW

**Comment by hartwork** [comment]
I can see these four changes in a single commit:
* Add setuptools to `DEPEND`
* Bump EAPI
* Add `bugs-to` info field to `metadata.xml`
* Change whitespace in `metadata.xml`

Personally, I would like to see:
* A revert of the whitespace change
* A few words on why setuptools is missing in the PR description

Thank you!

**Comment by sbraz** [comment]
On 9 Mar 2017 7:55 p.m., "Sebastian Pipping" <notifications@github.com>
wrote:

I can see these four changes in a single commit:

   - Add setuptools to DEPEND
   - Bump EAPI
   - Add bugs-to info field to metadata.xml

I didn't feel like that required a comment as it's quite trivial.


   - Change whitespace in metadata.xml

Personally, I would like to see:

   - A revert of the whitespace change

I thought tabs were the default since my vim uses them automatically. I'll
revert this.


   - A few words on why setuptools is missing in the PR description

Well they're required for setup.py. Would you like me to add something in
the commit message?



Thank you!

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/gentoo/gentoo/pull/4168#issuecomment-285445167>, or mute
the thread

**Comment by sbraz** [comment]
I updated the commit message to include the bugs-to thing, I thought it was small enough not to mention it. I've also reverted the whitespace change, I thought that tabs were preferred for metadata.

**Comment by hartwork** [comment]
@sbraz Thanks!
@SoapGentoo Well done, thanks!

**Pull request closed without merging**
