### PR TITLE
mail-filter/rspamd: add 3.7.4, drop 3.5-r1, sync live

### PR DESCRIPTION
**Pull request by arkamar**
See the commit message for 3.7.4.

### CODE REVIEW

**Comment by arkamar** [comment]
FP replacing 3.7.1 with recently released 3.7.3.

**Comment by arkamar** [comment]
FP with recent release 3.7.4.

**Comment by arkamar** [comment]
I will reset this PR to a previous state.

**Comment by vstakhov** [comment]
I think this particular bug is related solely to how another library is built. RHEL does not provide `fasttext` library for old versions and for non-amd64 architectures (it's very weird, I know). So I guess it is a distro specific issue completely.

**Comment by arkamar** [comment]
@vstakhov thank you for clarification.

**Pull request closed without merging**
