### PR TITLE
Keyword various things I've tested for ~ppc64

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Comment by naota** [comment]
LGTM

**Comment by Hummer12007** [comment]
ACK

**Comment by a17r** [comment]
Do you plan to do the same for the latest versions of kde-frameworks and kde-plasma/? Seems strange to stop at old 5.43 and 5.11.

**Comment by luke-jr** [comment]
I'm just using the amd64 keyword for most things, for now, so that's what I end up testing.

**Comment by a17r** [comment]
Please keyword latest versions in the future.

**Comment by luke-jr** [comment]
Even if I don't test them?

**Comment by a17r** [comment]
I can't test ~ppc64 (or any non-amd64 arch) either when I do a version bump, but now I have to make sure your keywords aren't blocking 5.43 removal when it's time for that.

**Pull request closed without merging**
