### PR TITLE
dev-debug: moves, part 3

### PR DESCRIPTION
**Pull request by mgorny**
- apitrace (unmaintained)
- bpftrace @chutz @jsmolic 
- d-feet, d-spy @gentoo/gnome 
- duma @bircoph 
- leaktracer (unmaintained)
- ltrace @mkszuba 
- strace @gentoo/base-system 
- sysdig @holgersson32644 
- systemtap @swegener 

Most of .ebuild updates are because of systemtap.

### CODE REVIEW

**Comment by hhoffstaette** [comment]
dev-util/scap-driver is part of sysdig, so if you move that then scap-driver should probably follow (it used to be called sysdig-driver..).

**Comment by mgorny** [comment]
> dev-util/scap-driver is part of sysdig, so if you move that then scap-driver should probably follow (it used to be called sysdig-driver..).

Thanks, added it.

**Review by thesamesam — APPROVED** [review]
ok when ci fixed

**Comment by mgorny** [comment]
> ok when ci fixed

CI is angry because crappy package uses `versionator.eclass`.

**Review by ArsenArsen — APPROVED** [review]

**Pull request closed without merging**
