### PR TITLE
dev-lua/penlight: Version bump to 1.5.4

### PR DESCRIPTION
**Pull request by Perlovka**
Package-Manager: Portage-2.3.48, Repoman-2.3.10

### CODE REVIEW

**Comment by Perlovka** [comment]
@Zlogene thanks, fixed.

**Comment by a17r** [comment]
ping @Zlogene

**Comment by juippis** [comment]
The maintainer doesn't seem to be using Github. You'd have better chance of reaching them via opening a bug in bugzilla. You can then link your PR in that bug for the maintainer to review, or merge, if they so wish.

**Comment by Perlovka** [comment]
Outdated

**Pull request closed without merging**
