### PR TITLE
dev-libs/libplatform-2.1.0.1: version bump

### PR DESCRIPTION
**Pull request by candrews**
https://bugs.gentoo.org/show_bug.cgi?id=603274

### CODE REVIEW

**Comment by candrews** [comment]
@v00d00 would you mind accepting this PR?

**Comment by v00d00** [comment]
No one assigned the actual bug to me to this first I am seeing on this.

That said, LGTM.

**Comment by candrews** [comment]
@v00d00 since you're the maintainer of the package, you have commit access, and you approve of this change, can you please merge it?

(I'm eager to get https://github.com/gentoo/gentoo/pull/3195/ reviewed and hopefully merged, and it is dependent upon upon this)

Thanks again!

**Comment by v00d00** [comment]
I would merge it, but I don't have my GPG keys on this machine (Im away from home for the festive period). I try to get somebody to merge it for you.

**Pull request closed without merging**
