### PR TITLE
net-p2p/syncthing: version bump to 0.14.2 & some fixes

### PR DESCRIPTION
**Pull request by bor**
@sbraz  @djc

### CODE REVIEW

**Comment by kensington** [comment]
@gentoo/proxy-maint

**Comment by sbraz** [comment]
There's a pending PR which should be merged before this: https://github.com/gentoo/gentoo/pull/1957

**Comment by djc** [comment]
Please rebase onto master.

**Comment by bor** [comment]
Done

**Comment by sbraz** [comment]
Shouldn't we also remove 14.0?

**Comment by sbraz** [comment]
Aaaaand now you can bump to 0.41.3 :)

**Comment by bor** [comment]
AFAIU there is good rule for syncthing: wait untill `.2` or `.3` for great releases :)

**Comment by bor** [comment]
Done

**Comment by djc** [comment]
Rebased and pushed as 14847206a11cc44ccc873fdecb7793e6b9771524 and 135559cec12c061547f872a37a05a42828342e70. Thanks!

**Pull request closed without merging**
