### PR TITLE
media-libs/ganv: fix compilation with --no-fdgl

### PR DESCRIPTION
**Pull request by lilrc**
Fixes bug #556518.

### CODE REVIEW

**Comment by mgorny** [comment]
@gentoo/proaudio

**Comment by lilrc** [comment]
No comment in three days. I guess the (mail) alias is useless, since the bug was not touched in two weeks even after I had attached the patch. [sigh]

**Comment by mgorny** [comment]
I'll try catching someone on IRC. ProAudio team kinda consists of people with little time for it.

**Comment by lilrc** [comment]
Thanks. :-) The next bugfixes will not be that urgent since I will not be stupid and base them on my master branch. :P

**Pull request closed without merging**
