### PR TITLE
EAPI4--

### PR DESCRIPTION
**Pull request by a17r**

### CODE REVIEW

**Comment by trofi** [comment]
OK for `dev-vcs/cvsps`. Generally I suggest not mixing ebuilds from different maintainers in a single pull request unless changes are interdependent. For example that would allow me to merge it directly without delay :)

**Comment by a17r** [comment]
@trofi even if I had no commit access you could always git am any individual commit.

**Comment by mm1ke** [comment]
@ a17r, since you're on it, i would have four other removal candidates :)

dev-haskell/ifelse/ifelse-0.85.ebuild
net-misc/getdate/getdate-1.2-r1.ebuild
net-firewall/ebtables/ebtables-2.0.10.4-r1.ebuild (ebtables-2.0.10.4 is EAPI4 too, but it's the only stable ebuild)
www-client/elinks/elinks-0.12_pre6-r1.ebuild

**Comment by a17r** [comment]
> dev-haskell/ifelse/ifelse-0.85.ebuild

I don't touch dev-haskell.
> net-misc/getdate/getdate-1.2-r1.ebuild

Done, thanks.
> net-firewall/ebtables/ebtables-2.0.10.4-r1.ebuild (ebtables-2.0.10.4 is EAPI4 too, but it's the only stable ebuild)

See also https://bugs.gentoo.org/724138

> www-client/elinks/elinks-0.12_pre6-r1.ebuild

Done, thanks.

**Comment by Polynomial-C** [comment]
:+1: for base-system packages

**Comment by robbat2** [comment]
:+1: for `smp_utils` and `libdbi-drivers`

**Pull request merged**
