### PR TITLE
sys-devel/llvm-roc: Use flag to optionaly build runtime libraries

### PR DESCRIPTION
**Pull request by justxi**
Signed-off-by: Wilfried Holzke <gentoo@holzke.net>
Package-Manager: Portage-2.3.103, Repoman-2.3.23

### CODE REVIEW

**Comment by candrews** [comment]
What are the runtime libraries? What are they used for / why would someone want them?

I'm trying to determine if the use flag should default to enabled and what other packages may depend on this use flag.

**Comment by justxi** [comment]
These are the libraries which would be installed by "sys-libs/compiler-rt".
They are needed e.g. by "hip".

**Comment by candrews** [comment]
If they're installed by sys-libs/compiler-rt, then why are they installed by this use flag too?
Should this flag conflict with sys-libs/compiler-rt or replace it?

**Comment by justxi** [comment]
No. 
For the system llvm/clang libs are installed by compiler-rt.
For llvm-roc we need the corresponding libs also.

**Comment by justxi** [comment]
Anything I can do here?

**Pull request closed without merging**
