### PR TITLE
x11-misc/xflux-gui: bump to version 1.2.0

### PR DESCRIPTION
**Pull request by ConiKost**
Also bumped to EAPI=7 and migrated from gnome2-utils to xdg-utils.
This version drops support for python2, but support for python3 was added.

Package-Manager: Portage-2.3.64, Repoman-2.3.12
Signed-off-by: Conrad Kostecki <conrad@kostecki.com>

### CODE REVIEW

**Comment by ConiKost** [comment]
> If your reason for this bump is python3, can you refer to an upstream issue request for a new release?

Mainly python3, yes. Development is currently actively. I can ask for a new release, but FWICS, this will take some time, until a new release will be there.

> Also, what about xflux-gui/fluxgui#113, does not sound very positive for this project?

That's very strange. I can't reproduce that for me. ```xflux``` just works perfectly fine here. Nothing broken??? Works on my Desktop and ThinkPad X260 just fine. Don't know, what to do in this case?

**Comment by a17r** [comment]
Very well if it works for you. Maybe wait for response of upstream before we merge this. If possible we should avoid using snapshots.

**Comment by ConiKost** [comment]
> Very well if it works for you. Maybe wait for response of upstream before we merge this. If possible we should avoid using snapshots.

Done, waiting now for response.

**Comment by ConiKost** [comment]
There is now a new release, 1.2.0 :) Will updated the PR.

**Comment by ConiKost** [comment]
Pushed 1.2.0 update :)

**Pull request closed without merging**
