### PR TITLE
dev-java/openjdk: openjdk source ebuild

### PR DESCRIPTION
**Pull request by oakad**
This is a first attempt at "pure" Openjdk ebuild. Unlike IcedTea, this ebuild builds Openjdk directly from upstream repository using upstream build setup (which is rather efficient, when compared to some other compiler builds).

Some existing issues:

1. Presently, only amd64 arch. Adoptopenjdk project has bootstrap tarballs for other arches as well, but I can not test those on my setup.

2. In general, bootstrap JVM should probably be decoupled from the specific ebuild version. It can be trivially build using this very ebuild, but I need some advice regarding how bootstrap tarballs are maintained in Gentoo distfiles system.

3. OPENJDK_JVM_VARIANTS needs to be made into a "magical" ebuild variable (beyond my control, clearly) 

4. Dependencies were established by building openjdk on clean up to date stage-3. Neither X11 nor Cups nor Alsa can be disabled in Linux builds, even if "headless" build is required.

5. check-reqs is not usable in EAPI-7? Is this an omission or is there some other methods to use?

6. Install keeps the entire JDK in one subdirectory in "/opt", as this was a traditional way for a long time.

Signed-off-by: Alex Dubov <oakad@yahoo.com>

### CODE REVIEW

**Comment by chewi** [comment]
It's a bit rough around the edges but it's helpful to know what is involved in building this. The main thing I want to say at this point is that I'd rather have a separate openjdk-bin package like #9502 to bootstrap with. Some people won't want to build the JDK from source and if we're going to package it for that reason then we may as well use it here.

**Comment by oakad** [comment]
It is rough, as stated. But I can not take it forward without assistance.

As to openjdk-bin - who builds it and how? The upstream only builds amd64, AdoptOpenjdk builds for all platforms (and that's what I am using presently).

I have opened an issue with AdoptOpenjdk to build a "minimal" tarball as well, which will be perfect for bootsrapping. However, their build system is currently in some sort of transition.

**Comment by chewi** [comment]
Okay, I didn't understand the distinction between OpenJDK and AdoptOpenJDK but now I do. I have no problem with using the AdoptOpenJDK builds instead, especially as they build for all the platforms we support bar x86, which I'm happy enough to exclude at this point. I think it would be okay to still call it openjdk-bin, as long as we mention AdoptOpenJDK in the description. I'll start moving on this.

It's mostly out of curiosity but I wonder if IcedTea can build OpenJDK 10. The build instructions say that usually at least the previous version is required, which would imply 9, but the major versions aren't as major as they used to be so I suspect 8 would still work. Maybe I'll give it a try just to see.

A minimal tarball sounds nice but I don't think we'd use it. There has always been demand for a -bin package in any case.

**Comment by oakad** [comment]
IcedTea is way slower than Openjdk when building from source is concerned (getting back to negative utility). Openjdk is using a very tightly optimized parallel build system which (I'd say subjectively) is faster than gcc, haskell/ghc and rust.

As to the boostrap issues: while many "lang" packages in portage have "-bin" versions, a more common approach to bootstrapping is via a dedicated tarball.  Consider rust, go, ghc.

**Comment by perfinion** [comment]
I just send a patch to update check-reqs.eclass to EAPI7 to the ML

**Comment by chewi** [comment]
@oakad, okay but I primarily meant using icedtea-bin. This would also allow big endian ppc64 users to build OpenJDK, which otherwise wouldn't be possible.

@perfinion, thanks although java-vm-2.eclass also needs the EAPI 7 treatment. I can take care of that one but it is blocked by xdg-utils.eclass.

**Comment by chewi** [comment]
openjdk-bin is now up. I'll start looking at this.

**Comment by chewi** [comment]
@oakad, your `REQUIRED_USE` line doesn't make any sense to me. Can you please explain it, specifically why you have put `||` inside `^^`?

**Comment by oakad** [comment]
@chewi Because "core" and "zero" ("hacker") jvm variants must be built exclusively, they can not be co-built and co-installed with the normal, "user" variants. Another option is to drop them entirely, and only stay with `|| ( jvm_variant_server jvm_variant_client jvm_variant_minimal)`

**Comment by oakad** [comment]
@chewi Because "core" and "zero" ("hacker") jvm variants must be built exclusively, they can not be co-built and co-installed with the normal, "user" variants. Another option is to drop them entirely, and only stay with `|| ( jvm_variant_server jvm_variant_client jvm_variant_minimal)`

**Pull request closed without merging**
