### PR TITLE
dev-python/agate: Fix the wrong description & homepage

### PR DESCRIPTION
**Pull request by vaartis**
Signed-off-by: Ekaterina Vaartis <vaartis@kotobank.ch>

### CODE REVIEW

**Comment by vaartis** [comment]
The bot is incorrect, it's _not_ a new package.

**Comment by mgorny** [comment]
> The bot is incorrect, it's _not_ a new package. @zmedico

I'm going to take a look why it gets confused. Maybe GH API changed or sth.

**Comment by vaartis** [comment]
> 
> 
> > The bot is incorrect, it's _not_ a new package. @zmedico
> 
> I'm going to take a look why it gets confused. Maybe GH API changed or sth.

May be because the package is just about an hour old, if that means anything.

**Comment by mgorny** [comment]
> May be because the package is just about an hour old, if that means anything.

Yep, it's on yet on the host that does the assignment. Maybe I should make it fetch `metadata.xml` via gitweb…

**Comment by zmedico** [comment]
Thanks!

**Pull request closed without merging**
