### PR TITLE
net-misc/icaclient: bump to 23.3.0.32 and enable usb redirection support

### PR DESCRIPTION
**Pull request by henning-schild**

### CODE REVIEW

**Comment by henning-schild** [comment]
marked as WIP, i will add usb redirection support with this one

**Comment by henning-schild** [comment]
marked as WIP, for the USB support the udev rule and the daemon might not be needed, and i need to test the systemd path, especially because of permissions on ``/dev/bus/usb/*/*

**Comment by henning-schild** [comment]
kind of related is https://github.com/henning-schild/aur-icaclient/pull/1, i wanted to look at arch anyhow and that was the first steps for systemd, will test systemd on gentoo-based as well to see if it also needs the udev rule for uaccess

**Comment by henning-schild** [comment]
Now tested on systemd and openrc based gentoo, works the same way. In gentoo usb devices are writable by the "usb" group, so no need to deploy an udev rule to append TAG "uaccess", instead users can join that group.

**Review by juippis — APPROVED** [review]
There's no need to revbump when the package hasn't been in the tree yet. I'll de-revbump but keep the separate commit. Thanks!

**Pull request closed without merging**
