### PR TITLE
Start database before pdns

### PR DESCRIPTION
**Pull request by petteyg**
bug #533162

### CODE REVIEW

**Comment by idella** [comment]
The patch might be fine but the commit msg is unusable.
Pleas peruse the docs supplied in gentoo wiki or github's own to see how a full commit message is written.

**Comment by petteyg** [comment]
It's also not signed, nor do you even apply things directly from GitHub AFAIK, so just cherry-pick it and amend the message if y'all want to apply it.

**Comment by idella** [comment]
petteyg what we want is to see you re-write the commit msg in required form.
I often edit a commit msg on addition, but I don't re-write them totally.
You can skip the writing of a commit msg by submitting exactly the same thing to a bug in bugzilla.
Part of the process of adding a fully git patch in this forum is to have it prepared fully in all aspects.
This is not.
Your reply basically says you fix the commit msg. I don't wish to bother. Hence the advantage of bugzilla in which the onus of making the commit msg is left only on a g developer.

**Comment by wraeth** [comment]
@swegener

**Comment by monsieurp** [comment]
This PR is two weeks old and no progress has been made so far. Please follow our guidelines described in https://wiki.gentoo.org/wiki/Gentoo_Github#Commit_format concerning commits and reopen if you're still interested in making a valuable PR. Thanks.

**Pull request closed without merging**
