### PR TITLE
net-im/signal-desktop-bin: add new version 6.1.0

### PR DESCRIPTION
**Pull request by robert7k**

### CODE REVIEW

**Review by ceamac — CHANGES_REQUESTED** [review]
Please remove the first `|| ( )` dependency, leave only `>=app-accessibility/at-spi2-core-2.46.0:2`.  The other one is obsolete.

Also `dosym -r` instead of `dosym ../../...`, the ebuild is EAPI 8.

**Comment by robert7k** [comment]
> Please remove the first `|| ( )` dependency, leave only `>=app-accessibility/at-spi2-core-2.46.0:2`. The other one is obsolete.

As long as the ebuilds are still available, this would unnecessarily force users  to switch, so I'm leaving this in place.

> Also `dosym -r` instead of `dosym ../../...`, the ebuild is EAPI 8.

Done.

**Comment by ceamac** [comment]
```
$ pkgcheck scan
net-im/signal-desktop-bin
  MissingRemoteId: missing remote-id of type 'github' with value 'signalapp/Signal-Desktop' (inferred from URI 'https://github.com/signalapp/Signal-Desktop')
  DeprecatedDep: version 6.1.0: RDEPEND: deprecated dependencies: app-accessibility/at-spi2-atk dev-libs/atk
```

Also check `profiles/package.deprecated`:
```
# Matt Turner <mattst88@gentoo.org> (2022-10-02)
# Dummy packages, now merged into app-accessibility/at-spi2-core.
# When possible, replace dependencies on these packages with a dependency on
#       >=app-accessibility/at-spi2-core-2.46.0
app-accessibility/at-spi2-atk
dev-libs/atk
```

If you look inside `atk-2.46.0.ebuild` or `at-spi2-atk-2.46.0.ebuild` (they are already stable), they are empty, they only depend on `>=app-accessibility/at-spi2-core-2.46.0`.  This is not about switching, the users already have switched, this is about not depending on them anymore so they can be cleaned.

Thank you.

**Comment by robert7k** [comment]
Convinced :-)

Done.

**Review by ceamac — APPROVED** [review]
Thank you

**Review by ceamac — CHANGES_REQUESTED** [review]
Oops, just noticed the keywords.  Please keep 6.0.0 and drop this to `~amd64`

**Comment by robert7k** [comment]
> Oops, just noticed the keywords. Please keep 6.0.0 and drop this to `~amd64`

We're always bumping stable for this ebuild. Older versions aren't supported by upstream anymore. See https://github.com/gentoo/gentoo/pull/23843#discussion_r806479441

**Review by ceamac — APPROVED** [review]
Nevermind, I found the comment in https://bugs.gentoo.org/831711

I'll merge it as it is.

**Comment by juippis** [comment]
Yeah, I usually test it on a stable amd64 container before merging, to see if runtime works correctly too.

**Comment by ceamac** [comment]
I run stable and I started it, it starts.  I don't have an account, so not sure how well it works, but at least it starts :)

**Pull request closed without merging**
