### PR TITLE
dev-python/cython: enable pypy and pypy3, + bump dev-python/numpy 1.16.4[pypy]

### PR DESCRIPTION
**Pull request by podshumok**
Hello!

It has been a while since Cython started to support both pypy and pypy3. Today there is nothing special in building it with pypy(3). The same is (more or less) true for packages built with cython.

So here is patched ebuild for cython (it is a trivial edit: ` PYTHON_COMPAT=( python2_7 python3_{5,6,7} pypy{,3} )`) and my question: how can we enable `pypy{,3}` builds for all packages using cython? Should I create a PR for each one of them or we can just make a bulk change somehow?

### CODE REVIEW

**Comment by mgorny** [comment]
No 'bulk changes'. Every package needs to be tested (as in, using actual tests). PyPy is known to cause problems due to some incompatibilities.

**Comment by podshumok** [comment]
OK, but I needed two packages here to pass repoman

**Comment by mgorny** [comment]
Sure. I'm going to test them, and add pypy if things work fine. You don't need revbumps for this btw. However, since changing that is more work than doing it from scratch, I'll just do it myself.

**Comment by podshumok** [comment]
So I could just change existing ebuild?

**Comment by mgorny** [comment]
For adding pypy*, yes.

**Comment by podshumok** [comment]
so should I close this or I can rebase and rename this PR converting it to numpy version bump?

**Comment by mgorny** [comment]
Did you make any actual changes to NumPy? If not, just close it, I have efficient scripts for bumping stuff.

**Comment by podshumok** [comment]
well bumping numpy wasn't straight-forward but nothing special had to be done (I needed to use doc URIs from previous version), newer version 1.17.0 would involve ebuild changes,

**Comment by podshumok** [comment]
@mgorny  could you please bump numpy?

**Comment by mgorny** [comment]
I'll look into it as time permits. Sadly, it takes some time to even build it, not to mention running the tests.

**Comment by mgorny** [comment]
I've managed to bump it to 1.16.5. 1.17.1 segfaults for me. Both versions don't work properly with PyPy.

**Comment by ajakk** [comment]
This hasn't been touched in ~1.5 years and seems to be broken anyway, closing.

**Pull request closed without merging**
