### PR TITLE
mail-filter/assp: Update init script

### PR DESCRIPTION
**Pull request by ConiKost**
mail-filter/assp: Update init script

Closes: https://bugs.gentoo.org/405527

### CODE REVIEW

**Comment by gyakovlev** [comment]
I'm not going to merge EAPI=0 ebuild, and since it's not proxy-maint ebuild - ping maintainer and check with them.
also sf page says `V1 development has been stopped at the end of 2014 (1.10.1 build 16060)`

**Comment by wltjr** [comment]
@gyakovlev congrats on becoming a dev, and the maintainer is misleading. It was a proxy maintained package since [I left as a developer in 2008](https://github.com/gentoo/gentoo-gitmig-20150809-draft/commit/3981d2423c0ac74bbad703b8e7a3b0bfd8748ca1#diff-5e8087ea0350aeff20740bcebfea4e5b) and has not had one since. You can find the real [history here](https://github.com/gentoo/gentoo-gitmig-20150809-draft/commits/master/mail-filter/assp), see the [last bump](https://github.com/gentoo/gentoo-gitmig-20150809-draft/commit/9a1c60d1ad8ba6213fc61f24c59e7457108be860#diff-5e8087ea0350aeff20740bcebfea4e5b) per my comments on [bug](https://bugs.gentoo.org/449850). I had good relations with Patrick and he proxied stuff for me for a few years. Till another in my many attempts to return was unsuccessfully. I stopped proxying and wasting Patricks time in such foolishness proxing. Over time has lead to many things being without a maintainer or people able to perform some things. Like the [oldest PR for another package I maintained](https://github.com/gentoo/gentoo/pull/1358). Tomcat gets bumped but any real work would come from me, thus PR being open still...

I am infamous, treated very poorly, blocked from all mailing lists, bugzilla, and likely here after this comment for an [unjustified never before 1yr ban, with option to extend indefinitely...](https://bugs.gentoo.org/640160) Many people have been destroying Gentoo since 2008. Keeping people like me out, hoping others will come along and maintain all the bit rotted cruft... I ended up replacing all of dev-java for Java > 1.8 and version bumps. Which will not hit Gentoo till who knows when if ever...

Regarding ASSP I recommend considering masking and removing. If others have not looked to update it to other 1.x release or 2.x. There are some perl deps not package in tree that are needed and also would need a maintainer. I would just punt the whole thing. Please do not take my work on 2.x and put it into tree given my treatment. Like another did for dev-db/firebird 3.x [getting it from another repo](https://github.com/gentoo/gentoo/commit/e246873f43db77850c172263be72bc5153b23adb#diff-7dc5e9ed8a228dd8f564e17d66c5559e) that came [from my repo](https://github.com/Obsidian-StudiosInc/os-xtoo/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aclosed+firebird)... The assp ebuild mostly my work, in tree, and surely in my repo. Thus best to just punt. I doubt anyone else is interested in maintaining or is using ASSP. I have used ASSP in production since [before I put it into tree](https://github.com/gentoo/gentoo-gitmig-20150809-draft/blob/master/mail-filter/assp/ChangeLog#L294), and still run it to this day. With no plans to stop running ASSP.  Same with Tomcat and Firebird... Note who [opened my communications channel bug]() and [who added Firebird 3.x](https://github.com/gentoo/gentoo/commit/2ee359baae6e5853d90f0ae511bdd9cb48d5aac2#diff-7dc5e9ed8a228dd8f564e17d66c5559e)...

Sorry for the length, but the backstory directly relates to this package and is yet another example. People think they are trying to make things better, and end up making it worse. Drive away one person does not mean another will come and fill their shoes... Over a decade later.... Others still have not learned this hard lesson... But are hopefully their ways which have never worked. Will magically start to someday... I hoped to be proven wrong, rather than right...

**Comment by ConiKost** [comment]
> Regarding ASSP I recommend considering masking and removing. If others have not looked to update it to other 1.x release or 2.x.

Fine for me, since I am not using it and don't plan to maintain it.

**Comment by wltjr** [comment]
@ConiKost not to discourage your efforts. But removal is likely best. There are other [open bugs](https://bugs.gentoo.org/buglist.cgi?quicksearch=mail-filter%2Fassp). Mostly all init related, but still needs a bump, other deps, and maybe other fixes.

**Pull request closed without merging**
