### PR TITLE
app-crypt/kbfs: new package, add 6.0.2, 9999

### PR DESCRIPTION
**Pull request by ran-dall**
Go mod Deps: https://file.io/igx532a7YPkB

Special Thanks to @simonvanderveldt for starting the work in this PR.

### CODE REVIEW

**Review by nicolasbock — CHANGES_REQUESTED** [review]
Hi @ran-dall ! Thanks for submitting this PR!

Please check the `SRC_URI`. I can't download the sources.

**Comment by ran-dall** [comment]
@nicolasbock It probably causes the deps aren't uploaded, and the `SRC_URI` doesn't specify the location. I told @thesamesam yesterday so he can pull them from this PR, from that file.io link. You can also download them and place the downloaded archive into `/var/cache/distfiles` to bypass the check.

**Comment by nicolasbock** [comment]
Could you elaborate how the zip file on file.io is generated?

**Comment by ran-dall** [comment]
@nicolasbock Sure. The general process is outlined here: https://devmanual.gentoo.org/eclass-reference/go-module.eclass/index.html; however, this took me a second because, in this case, you have to go into the `/go` directory and generate it from there.

**Comment by nicolasbock** [comment]
Thanks for the info @ran-dall . Let me have a quick look at those docs.

**Comment by nicolasbock** [comment]
Hi @ran-dall . I am having a hard time testing this. I am not running Gentoo anywhere at the moment and can't compile this module. The ebuild itself looks fine but QA is still having issues with the dependencies file. I can upload the file to my dev space if that would help.

**Comment by ran-dall** [comment]
@nicolasbock Sorry, mate, I got really busy there for a minute. So I've re-up'd the dep files to files.io: https://file.io/OytRndYmCril

You'd find both the deps for `kbfs` and `keybase` at that same link. From here, you can upload them to your Gentoo space and send me a link; I can then update both ebuilds.

To try this out locally, you should be able to drop both `.tar.xz` files into your `/var/cache/distfiles` directory and proceed.

**Comment by nicolasbock** [comment]
Hi @ran-dall . I am working on this PR and tried to download the deps. However, I am getting a message saying that the transfer request was deleted. Could you upload that file again?

**Comment by nicolasbock** [comment]
I don't have write access to this PR and can't change it. I pushed #29652 to test the modifications I made.

**Comment by nicolasbock** [comment]
Thanks @ran-dall for working on this!

**Pull request closed without merging**
