### PR TITLE
net-nds/389-ds-base: revbump to 1.3.4.7-r2 to fix bdb dep and nomenclature

### PR DESCRIPTION
**Pull request by anomaly256**
Correct slotted dep for sys-libs/db:5.3 and rename ALL_DEPEND to COMMON_DEPEND

### CODE REVIEW

**Comment by anomaly256** [comment]
@gentoo/proxy-maintainers

**Comment by gktrk** [comment]
Hi, I would like to make some comments on this submission if you don't mind:

You don't need 'sys-apps/sed' in DEPEND because it is an [implicit system dependency](https://gitweb.gentoo.org/repo/gentoo.git/tree/profiles/base/packages#n55). It will be satisfied by the package manager for you.

This ebuild lists "sys-libs/db:5.3" as a dependency, however, the [389 documentation](http://directory.fedoraproject.org/docs/389ds/development/building.html#berkeley-db) says "You need version 4.2.52 or later". Are the docs obsolete by any chance?

For `use auto-dn-suffix && myconf="${myconf} --enable-auto-dn-suffix"` on line 76, you can probably convert this into `$(usex auto-dn-suffix "--enable-auto-dn-suffix" "")` and pass it to econf directly. As you can guess, [usex](https://devmanual.gentoo.org/ebuild-writing/eapi/index.html#eapi=5) will pass the configure flag if USE flag is present, and "" if not.

Also, there's a missing '|| die' in line 124. File creation by shell redirection is not guaranteed to succeed. Optionally, you can use something like this I think, although it may be better to get a dev review this one:
```
newenvd - 08dirsrv <<-EOF
    LDPATH=/usr/$(get_libdir)/dirsrv
EOF
```

Good luck

**Comment by anomaly256** [comment]
Thanks for the feedback.  It is my understanding that this version does indeed require db5.3 - I've notified upstream about the documentation requiring updating.

Upstream has also, or is about to, release 1.3.4.8 as well - will take your advice onboard when doing the new ebuild and will probably do (another) revbump tonight for 1.3.4.7 to address the missing '|| die' to be safe.

**Comment by idella** [comment]
yes thanks gktrk.
The versioning as you can see is under control
from  grep "echo \"" -r  . in the  <cat> net-nds:
a plethora of ebuilds that utilise echo "$msg" without || die
mostly ebuilds of  openldap-2

It is not wrong to append "|| die", nor is it critical to leave it out with such a precedent.
It frankly requires a judgement call, or an overall tightening of what is required standard and what is not. Personally i don't think such trivial instances of this type warrant it.

**Comment by anomaly256** [comment]
Just spoke to wibrown@rh, db => 4 and db < 6 should suffice but they had hardcoded --with-db-inc=/usr/include/${CHOST}/db5.3/ in the configure line as their build env expects to be able to grep db.h and gentoo on ~amd64 moves it and symlinks /usr/include/db.h to db6's.  I'll investigate a better way to implement this as well

**Comment by gktrk** [comment]
@idella 
> It is not wrong to append "|| die", nor is it critical to leave it out with such a precedent.
It covers particular corner cases. For example, if redirection fails due to ENOSPC, the build may still succeed silently without actually installing the env file. This may be a rare thing to happen, but that's one of the reasons why we use die anyway.

I'm merely pointing things out here of course. The ebuild author and the proxy dev are ultimately the ones to evaluate the reviews and act as they see fit.

**Comment by anomaly256** [comment]
Thanks to @wraeth I believe I've found a fairly elegant solution to the db + configure issue.  Will try for -r3 tonight, hopefully the last one for a while :)

**Pull request merged**
