### PR TITLE
dev-java/jakarta-mail-api: new package

### PR DESCRIPTION
**Pull request by vaukai**
Test failures with `openjdk-8` [here](https://gist.github.com/vaukai/6f54160f4491f2e8769b888c6ef3a768), with [NullPointerException](https://gist.github.com/vaukai/6f54160f4491f2e8769b888c6ef3a768#file-stdin-L46-L48) coming [from here](https://github.com/eclipse-ee4j/mail/blob/e9816d067a64a5f8d5b4cc4abdf7ddefdbcdef3d/api/src/test/java/jakarta/mail/util/FactoryFinderTest.java#L55).
and test compile errors with `openjdk-11` [here](https://gist.github.com/vaukai/e377727e2a21558c76f104fbc8188fcb).

### CODE REVIEW

**Comment by fordfrog** [comment]
@vaukai do we really need the new slot for `dev-java/jakarta-activation-api`? i did comparison against `2.0.1` and there are mainly added new methods. also, nothing consumes slot `:2` atm afaics so i'd just continue with slot `:2' on the new version. any objections?

**Comment by vaukai** [comment]
> @vaukai do we really need the new slot for `dev-java/jakarta-activation-api`? i did comparison against `2.0.1` and there are mainly added new methods. also, nothing consumes slot `:2` atm afaics so i'd just continue with slot `:2' on the new version. any objections?

@fordfrog thanks for checking.  I also think it may continue with `:2`.  
But please be aware this PR is still in DRAFT mode until solving the [test failures](https://gist.github.com/vaukai/6f54160f4491f2e8769b888c6ef3a768) which might be due (?) to my ignorance of [filtering Version.java](https://github.com/eclipse-ee4j/mail/blob/e9816d067a64a5f8d5b4cc4abdf7ddefdbcdef3d/api/pom.xml#L254-L265).

**Comment by fordfrog** [comment]
@vaukai `dev-java/jakarta-activation-api` merged, thanks!

**Comment by Flowdalic** [comment]
I get the following test failures using openjdk-17 (not sure if related):

```>>> Test phase: dev-java/jakarta-mail-api-2.1.0
javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:jakarta-mail-api.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar @test_sources.lst
warning: [options] bootstrap class path not set in conjunction with -source 8
Note: src/test/java/jakarta/mail/internet/MailDateFormatTest.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 warning
JUnit version 4.13.2-SNAPSHOT
...........................................................................................................ParameterListTests
............NonAsciiFileNames
...E.E...............................................................................................................................................................................................................................................AppleFileNames
.E.I....
Time: 0.336
There were 3 failures:
1) testDecodeWithParams(jakarta.mail.internet.ContentDispositionNoStrictTest)
java.lang.AssertionError: Exception must not be thrown in non-strict mode
	at org.junit.Assert.fail(Assert.java:89)
	at jakarta.mail.internet.ContentDispositionNoStrictTest.testDecodeWithParams(ContentDispositionNoStrictTest.java:49)
2) testDecode(jakarta.mail.internet.ContentDispositionNoStrictTest)
java.lang.AssertionError: Exception must not be thrown in non-strict mode
	at org.junit.Assert.fail(Assert.java:89)
	at jakarta.mail.internet.ContentDispositionNoStrictTest.testDecode(ContentDispositionNoStrictTest.java:39)
3) testProp(jakarta.mail.internet.AppleFileNamesTest)
jakarta.mail.internet.ParseException: In parameter list <; filename=a b.txt>, expected ';', got "b.txt"
	at jakarta.mail.internet.ParameterList.<init>(ParameterList.java:301)
	at jakarta.mail.internet.AppleFileNamesTest.testProp(AppleFileNamesTest.java:36)
```

**Comment by vaukai** [comment]
@Flowdalic Sorry, cannot reproduce the failures you posted.  But let's do that later along with the other test failures.  Before that I'd like to get the test phase compilation errors solved.  (These didn't occur using jdk-8.)

Also @fordfrog Do you have an idea?

**system modules path not set in conjunction with -source 9**
**error: package is empty or does not exist**
```
 * Verbose logging for "ejavac" function
 * Compiler executable: javac
 * Extra arguments: -source 9 -target 9
 * Complete command:
 * javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
warning: [options] system modules path not set in conjunction with -source 9
src/test/java/module-info.java:24: error: package is empty or does not exist: jakarta.mail.event
    exports jakarta.mail.event;
                        ^
src/test/java/module-info.java:29: error: cannot find symbol
    uses jakarta.mail.Provider;
                     ^
  symbol:   class Provider
  location: package jakarta.mail
src/test/java/module-info.java:30: error: cannot find symbol
    uses jakarta.mail.util.StreamProvider;
                          ^
  symbol:   class StreamProvider
  location: package jakarta.mail.util
src/test/java/module-info.java:32: error: cannot find symbol
    provides jakarta.mail.util.StreamProvider with jakarta.mail.util.DummyStreamProvider;
                              ^
  symbol:   class StreamProvider
  location: package jakarta.mail.util
4 errors
```

**Comment by fordfrog** [comment]
> @Flowdalic Sorry, cannot reproduce the failures you posted. But let's do that later along with the other test failures. Before that I'd like to get the test phase compilation errors solved. (These didn't occur using jdk-8.)
> 
> Also @fordfrog Do you have an idea?
> 
> **system modules path not set in conjunction with -source 9** **error: package is empty or does not exist**
> 
> ```
>  * Verbose logging for "ejavac" function
>  * Compiler executable: javac
>  * Extra arguments: -source 9 -target 9
>  * Complete command:
>  * javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
> javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
> warning: [options] system modules path not set in conjunction with -source 9
> src/test/java/module-info.java:24: error: package is empty or does not exist: jakarta.mail.event
>     exports jakarta.mail.event;
>                         ^
> src/test/java/module-info.java:29: error: cannot find symbol
>     uses jakarta.mail.Provider;
>                      ^
>   symbol:   class Provider
>   location: package jakarta.mail
> src/test/java/module-info.java:30: error: cannot find symbol
>     uses jakarta.mail.util.StreamProvider;
>                           ^
>   symbol:   class StreamProvider
>   location: package jakarta.mail.util
> src/test/java/module-info.java:32: error: cannot find symbol
>     provides jakarta.mail.util.StreamProvider with jakarta.mail.util.DummyStreamProvider;
>                               ^
>   symbol:   class StreamProvider
>   location: package jakarta.mail.util
> 4 errors
> ```

i'd suggest to verify the jakarta jar file really contains those.

**Comment by vaukai** [comment]
> i'd suggest to verify the jakarta jar file really contains those.

It is all there and result of pkgdiff is very good.

Could the root cause be `@sources.lst` and `@test_sources.lst` being compiled `-classpath` instead with `--module-path`?
Complete log [is here](https://gist.github.com/vaukai/b97fef71f1bd1e6d06f3c7b38a402a6b).
```
$ grep -A2 'Complete command' /var/tmp/portage/dev-java/jakarta-mail-api-2.1.0/temp/build.log 

 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath /usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar @sources.lst
javac -source 1.8 -target 1.8 -d target/classes -encoding UTF-8 -classpath /usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar @sources.lst
--
 * Complete command:
 * javac -source 9 -target 9 -d target/classes -encoding UTF-8 --module-path /usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/main/java/module-info.java
javac -source 9 -target 9 -d target/classes -encoding UTF-8 --module-path /usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/main/java/module-info.java
--
 * Complete command:
 * javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:jakarta-mail-api.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar @test_sources.lst
javac -source 1.8 -target 1.8 -d target/test-classes -encoding UTF-8 -classpath target/test-classes:jakarta-mail-api.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar @test_sources.lst
--
 * Complete command:
 * javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
javac -source 9 -target 9 -d target/test-classes -encoding UTF-8 --module-path target/test-classes:jakarta-mail-api.jar:/usr/share/hamcrest-core-1.3/lib/hamcrest-core.jar:/usr/share/junit-4/lib/junit.jar:/usr/share/angus-activation/lib/angus-activation.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar:/usr/share/jakarta-activation-api-2/lib/jakarta-activation-api.jar --module-version 2.1.0 src/test/java/module-info.java
```

**Pull request closed without merging**
