### PR TITLE
sys-block/zram-init: version bump

### PR DESCRIPTION
**Pull request by beatussum**

### CODE REVIEW

**Comment by rossbridger** [comment]
I think installing the systemd units into /usr/lib/systemd/ is deprecated in favor of /lib/systemd/

**Comment by beatussum** [comment]
I don't manage to find this depreciation in the freedesktop documentation: could you tell me where you found it?

**Comment by rossbridger** [comment]
It's old news: https://www.gentoo.org/support/news-items/2017-07-16-systemd-rootprefix.html

**Comment by beatussum** [comment]
Thanks, I'll fix that.

**Comment by telans** [comment]
10.9 is available

**Comment by beatussum** [comment]
version bump

**Pull request closed without merging**
