### PR TITLE
app-vim/syntastic: version bump 3.7.0

### PR DESCRIPTION
**Pull request by lkraav**

### CODE REVIEW

**Comment by monsieurp** [comment]
@yngwin @radhermit

**Comment by monsieurp** [comment]
I'll merge it cause the bump is trivial.

**Comment by lkraav** [comment]
Thanks. In the process of PR-ing I noticed that the master HEAD moves very quickly. Does @gentoo-bot automatically rebase and merge or just merge?

**Comment by mgorny** [comment]
It only mirrors whatever was done on git.gentoo.org. in this case, it was a real merge since gh doesn't recognize rebased commits.

**Pull request merged**
