### PR TITLE
net-vpn/i2pd: version bump and new use flag

### PR DESCRIPTION
**Pull request by khumarahn**

### CODE REVIEW

**Comment by khumarahn** [comment]
Also there is a gentoo bug, which needs to be closed if this PR is approved.
https://bugs.gentoo.org/show_bug.cgi?id=628250

**Comment by blueness** [comment]
this adds a dependency on dev-cpp/websocketpp which is not keyworded ~arm while ip2d is.  you can catch the problem with `repoman full` which you should run in the ebuild directory before submitting the pull request to make sure it won't break the tree.

**Comment by khumarahn** [comment]
@blueness 

What is the proper way to resolve this? `dev-cpp/websocketpp` works fine on arm for me, and is designed for arm in particular, according to their github page. So maybe it needs to be keyworded with arm (and also ppc)?

Can you maybe push the commits except the one which adds the use flag?

**Comment by khumarahn** [comment]
I created a bug for dev-cpp/websocketpp. I _actually_ do not know what would be a good solution here.

**Comment by khumarahn** [comment]
No response for so long... I removed the controversial change.
@blueness ping

**Comment by blueness** [comment]
@khumarahn did you actually test dev-cpp/websocketpp on arm?  if so i can keyword it for you.

**Comment by blueness** [comment]
i've keyworded  dev-cpp/websocketpp for ~arm and ~ppc.  Please restore that option that depends on websocketpp.

**Comment by khumarahn** [comment]
I added back the websocketpp commit.

It is great you keyworded websocketpp. The test suite of websocketpp compiles and runs successfully on my arm box, except some known problems https://github.com/zaphoyd/websocketpp/issues/653 which don't seem to be arm specific.

**Comment by blueness** [comment]
pushed

**Pull request closed without merging**
