### PR TITLE
gui-apps/waybar: version bump to  0.9.9

### PR DESCRIPTION
**Pull request by JonasToth**
Updates `waybar` to version 0.9.9. With it comes a fix for `dev-libs/fmt` compatibility.

Bug: https://bugs.gentoo.org/830749

### CODE REVIEW

**Comment by mdirkse** [comment]
Any word on when this will get merged and a new version pushed?

**Comment by JonasToth** [comment]
> Any word on when this will get merged and a new version pushed?

This PR will be reviewed by a gentoo developer and if found ok merged. I can not merge this a proxy-maintainer and reviewers time is precious. I think its not possible to give a date, but usually it takes ~1 week or so until the reviewers catch up.

**Comment by ionenwks** [comment]
Sorry this took a while, missed that this was entirely broken in ~arch and these should preferably be processed faster.

**Comment by JonasToth** [comment]
I didn't write the a good title, sry :/

**Pull request closed without merging**
