### PR TITLE
gnome-base/{gnome, gnome-core-apps, gnome-core-libs, gnome-extra-apps, gnome-shell}, gnome-extra/{gnome-boxes, gnome-search-tool, gnome-shell-frippery, gnome-tweaks}, x11-misc/libinput-gestures, x11-wm/mutter: Update gnome description

### PR DESCRIPTION
**Pull request by Polluktus**
GNOME 3 in so longer available in repo.

### CODE REVIEW

**Comment by mattst88** [comment]
Thank you.

Please make one commit per package (so for example squash consecutive patches to `x11-mutter` together), and please prefix the commit titles with the `category/package:`.

**Comment by Polluktus** [comment]
Sorry, it's my first pull request, gonna make it right.

**Comment by ionenwks** [comment]
> Sorry, it's my first pull request, gonna make it right.

Don't worry about it, although there's no need to close it and make a new one when changes are requested, i.e. you can use --force to replace your branch

**Comment by mattst88** [comment]
Yeah, it's okay. Like Ionen says, you can just force push the branch to update it.

**Comment by mattst88** [comment]
I've fixed up the commits locally. Can I have your Signed-off-by tag in accordance with Gentoo's copyright policy (https://www.gentoo.org/glep/glep-0076.html)?

Also, if you wouldn't mind giving your real name?

Thanks!

**Comment by Polluktus** [comment]
I've made a proper pull request here https://github.com/gentoo/gentoo/pull/21396 with Signed-off-by tag.

**Pull request closed without merging**
