### PR TITLE
dev-lang/rust: Add rust-1.49.0.ebuild

### PR DESCRIPTION
**Pull request by marga-kinvolk**
This required a refactor of the gentoo-musl-target-specs.patch, to adopt
the new format of the target() method.

Signed-off-by: Margarita Manterola <marga@kinvolk.io>

### CODE REVIEW

**Comment by Uniminin** [comment]
Looks Good!

**Comment by Uniminin** [comment]
I've tried it on my system & it does not work on my system.

**Comment by Uniminin** [comment]
@markjolah ping! Add the patch

**Comment by Uniminin** [comment]
@marga-kinvolk ping! Add the patch

**Comment by marga-kinvolk** [comment]
I'm sorry, I don't understand the comment. The patch is in this PR, where is it missing from?

**Comment by Uniminin** [comment]
My bad. It's alright!

**Comment by Uniminin** [comment]
I was trying it on my system and it fails to merge. The build log: https://dpaste.com/3K4U6LYQF.txt

**Comment by dongsupark** [comment]
It looks good.
I have tested this PR on a clean Gentoo system.
It worked well. I have not seen build failures mentioned above.

**Comment by gyakovlev** [comment]
thanks! merged.

sorry for delay, was really busy.

**Pull request closed without merging**
