### PR TITLE
app-containers/crun: Depend on argp-standaolone on musl

### PR DESCRIPTION
**Pull request by vadorovsky**
Closes: https://bugs.gentoo.org/922292
Suggested-by: Han Puyu <w12101111@gmail.com>

### CODE REVIEW

**Comment by robertgzr** [comment]
I don't have a way to test this right now :P but if somebody chimes in or it's fine with a dev that is going to merge this :)

@vadorovsky you might want to fixup the commit message :) `s/argp-standaolone/argp-standalone/`

**Comment by vadorovsky** [comment]
@robertgzr If that makes it any easier for you - you can use `registry.github.com/vadorovsky/gentoo-musl-llvm:stage3` container image to quickly set up an Gentoo environment with musl. You could try running it with `--privileged` and set up Docker or podman with patched crun there.

In general, I have a set of Gentoo musl-llvm images here https://gitlab.com/vadorovsky/gentoo-musl-llvm/container_registry/, the stage4 tags are based on my overlay (https://gitlab.com/vadorovsky/overlay) where I already applies the change I'm proposing in this PR.

**Review by juippis — COMMENTED** [review]
I tried to compile this on a musl test system and got:
```
>>> Completed installing app-containers/crun-1.14.3 into /var/tmp/portage/app-containers/crun-1.14.3/image

 * Final size of build directory: 17880 KiB (17.4 MiB)
 * Final size of installed tree:    832 KiB

Files matching a file type that is not allowed:
   usr/lib/libcrun.so.0.0.0
 * ERROR: app-containers/crun-1.14.3::gentoo failed:
 *   multilib-strict check failed!
 * 
```
is my musl broken or something with this package? At least all the deps emerged succesfully so I'm leaning towards this package having something on musl.

**Review by juippis — APPROVED** [review]
Ah, I see after updating my containers from lxd to incus I lost `-multilib-strict` feature from an external **env/test.conf** on musl. Works again, will merge today at some point.

**Pull request closed without merging**
