### PR TITLE
media-video/mkvtoolnix: update GTK+ icon cache

### PR DESCRIPTION
**Pull request by fturco**

### CODE REVIEW

**Comment by radhermit** [comment]
This should be submitted against the latest version in the tree, especially since you're revbumping it anyway.

**Comment by fturco** [comment]
Can you be more specific, please? Should I fix only the latest versions (21.0.0/git)? I tested all versions (except 9.6.0), and they all have this problem.

**Comment by radhermit** [comment]
Yes, only fix the latest versions. That's how it generally should be handled when making changes that includes revbumping ebuilds since keywords need to be dropped anyway.

**Comment by radhermit** [comment]
Merged, thanks.

**Pull request closed without merging**
