### PR TITLE
dev-python/mccabe: fix multiple ebuild problems in 0.4.0

### PR DESCRIPTION
**Pull request by Coacher**
List of changes:
- fix HOMEPAGE, DESCRIPTION, remote-id
- remove unneeded pep8 dep
- fix pytest/pytest-runner dep
- fix tests
- enable tests

### CODE REVIEW

**Comment by Coacher** [comment]
Build and runtime test:
```
$ equery l flake8
 * Searching for flake8 ...
[IP-] [  ] dev-python/flake8-2.5.4:0
$ equery l pep8
!!! No installed packages matching 'pep8'
 * Searching for pep8 ...
$ equery l pytest-runner
!!! No installed packages matching 'pytest-runner'
 * Searching for pytest-runner ...
$ equery l pytest
!!! No installed packages matching 'pytest'
 * Searching for pytest ...
# emerge -1 mccabe
Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/mccabe-0.4.0::bonespirit
>>> Installing (1 of 1) dev-python/mccabe-0.4.0::bonespirit
>>> Jobs: 1 of 1 complete                           Load avg: 1.63, 1.56, 2.08
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
$ python /usr/lib64/python2.7/site-packages/mccabe.py stepbysteptest.py
7:1: 'StepByStepTest' 12
```

**Comment by Coacher** [comment]
Build and runtime test with test enabled:
```
$ equery l flake8
 * Searching for flake8 ...
[IP-] [  ] dev-python/flake8-2.5.4:0
$ equery l pep8
!!! No installed packages matching 'pep8'
 * Searching for pep8 ...
$ equery l pytest
!!! No installed packages matching 'pytest'
 * Searching for pytest ...
$ equery l pytest-runner
!!! No installed packages matching 'pytest-runner'
 * Searching for pytest-runner ...
$ equery l pytest
 * Searching for pytest ...
[IP-] [  ] dev-python/pytest-2.8.2:0
# FEATURES='test' USE='test' emerge -1 mccabe
Calculating dependencies... done!
>>> Verifying ebuild manifests
>>> Emerging (1 of 1) dev-python/mccabe-0.4.0::bonespirit
>>> Installing (1 of 1) dev-python/mccabe-0.4.0::bonespirit
>>> Jobs: 1 of 1 complete                           Load avg: 1.24, 1.38, 1.72
>>> Auto-cleaning packages...

>>> No outdated packages were found on your system.

 * GNU info directory index is up-to-date.
$ python /usr/lib64/python2.7/site-packages/mccabe.py stepbysteptest.py
7:1: 'StepByStepTest' 12
```

**Comment by Coacher** [comment]
Testsuite run:
```
$ ebuild mccabe-0.4.0.ebuild test
Appending /home/coacher/Work/bonespirit to PORTDIR_OVERLAY...
Forcing test.
 * mccabe-0.4.0.tar.gz SHA256 SHA512 WHIRLPOOL size ;-) ...                                                                                                                 [ ok ]
>>> Unpacking source...
>>> Unpacking mccabe-0.4.0.tar.gz to /var/tmp/portage/dev-python/mccabe-0.4.0/work
>>> Source unpacked in /var/tmp/portage/dev-python/mccabe-0.4.0/work
>>> Preparing source in /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0 ...
>>> Source prepared.
>>> Configuring source in /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0 ...
>>> Source configured.
>>> Compiling source in /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0 ...
 * python2_7: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python2.7 setup.py build
running build
running build_py
copying mccabe.py -> /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0-python2_7/lib
warning: build_py: byte-compiling is disabled, skipping.

 * python3_4: running distutils-r1_run_phase distutils-r1_python_compile
/usr/bin/python3.4 setup.py build
running build
running build_py
copying mccabe.py -> /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0-python3_4/lib
warning: build_py: byte-compiling is disabled, skipping.

>>> Source compiled.
>>> Test phase: dev-python/mccabe-0.4.0
 * python2_7: running distutils-r1_run_phase python_test
=============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /usr/bin/python2.7
cachedir: .cache
rootdir: /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0, inifile:
collecting ... collected 12 items

test_mccabe.py::McCabeTestCase::test_async_keywords SKIPPED
test_mccabe.py::McCabeTestCase::test_for_else_snippet PASSED
test_mccabe.py::McCabeTestCase::test_for_loop_snippet PASSED
test_mccabe.py::McCabeTestCase::test_if_elif_else_dead_path_snippet PASSED
test_mccabe.py::McCabeTestCase::test_nested_functions_snippet PASSED
test_mccabe.py::McCabeTestCase::test_print_message PASSED
test_mccabe.py::McCabeTestCase::test_recursive_snippet PASSED
test_mccabe.py::McCabeTestCase::test_sequential_snippet PASSED
test_mccabe.py::McCabeTestCase::test_sequential_unencapsulated_snippet PASSED
test_mccabe.py::McCabeTestCase::test_trivial PASSED
test_mccabe.py::McCabeTestCase::test_try_else PASSED
test_mccabe.py::RegressionTests::test_max_complexity_is_always_an_int PASSED

====================================================================== 11 passed, 1 skipped in 0.08 seconds =======================================================================
 * python3_4: running distutils-r1_run_phase python_test
=============================================================================== test session starts ===============================================================================
platform linux -- Python 3.4.3, pytest-2.8.2, py-1.4.30, pluggy-0.3.1 -- /usr/bin/python3.4
cachedir: .cache
rootdir: /var/tmp/portage/dev-python/mccabe-0.4.0/work/mccabe-0.4.0, inifile:
collecting ... collected 12 items

test_mccabe.py::McCabeTestCase::test_async_keywords SKIPPED
test_mccabe.py::McCabeTestCase::test_for_else_snippet PASSED
test_mccabe.py::McCabeTestCase::test_for_loop_snippet PASSED
test_mccabe.py::McCabeTestCase::test_if_elif_else_dead_path_snippet PASSED
test_mccabe.py::McCabeTestCase::test_nested_functions_snippet PASSED
test_mccabe.py::McCabeTestCase::test_print_message PASSED
test_mccabe.py::McCabeTestCase::test_recursive_snippet PASSED
test_mccabe.py::McCabeTestCase::test_sequential_snippet PASSED
test_mccabe.py::McCabeTestCase::test_sequential_unencapsulated_snippet PASSED
test_mccabe.py::McCabeTestCase::test_trivial PASSED
test_mccabe.py::McCabeTestCase::test_try_else PASSED
test_mccabe.py::RegressionTests::test_max_complexity_is_always_an_int PASSED

====================================================================== 11 passed, 1 skipped in 0.11 seconds =======================================================================
 * python2_7: running distutils-r1_run_phase _clean_egg_info
 * python3_4: running distutils-r1_run_phase _clean_egg_info
>>> Completed testing dev-python/mccabe-0.4.0
```

**Comment by Coacher** [comment]
See also https://bugs.gentoo.org/show_bug.cgi?id=575112

**Comment by Coacher** [comment]
CC @gentoo/python

**Comment by idella** [comment]
Most of these commits could be reduced into one or two. Splitting into separate commits is primarily for a clean revert in the future if needed.  These are trivial or deal with the test phase, therefore a common theme. Will test and looks more closely later

**Comment by idella** [comment]
The only point I could make is that it could be bumped EAPI to 6 without issue

**Comment by Coacher** [comment]
Indeed.

**Comment by idella** [comment]
merged

**Comment by Coacher** [comment]
Thank you very much, @idella.

Note that EAPI commit wasn't merged.

**Pull request closed without merging**
